### ISSUE TITLE
Double Header

### ISSUE THREAD

**Issue by nkhoshaf** [FreeCodeCamp/freecodecamp#1000]
Challenge http://www.freecodecamp.com/challenges/waypoint-get-set-for-basejumps has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

My Issue is that everything works except my site shows a double header.  Not sure why. 

![screen shot 2015-06-13 at 1 43 18 pm](https://cloud.githubusercontent.com/assets/9994709/8261987/ee413380-169c-11e5-946b-70fa7c570b1d.png)

**Comment by QuincyLarson** [comment]
Are you using Firefox?

**Comment by nkhoshaf** [comment]
I am using Chrome
