### ISSUE TITLE
The country `xk` or `Yugoslavia` cannot be found in the given url: https://www.flag-sprites.com

### ISSUE THREAD

**Issue by cmal** [FreeCodeCamp/FreeCodeCamp#10001]
#### Challenge Name

https://www.freecodecamp.com/challenges/show-national-contiguity-with-a-force-directed-graph

#### Issue Description

The given json has the country `xk` or `Yugoslavia`, but it cannot be found in the given url: https://www.flag-sprites.com

The flag-sprites website says: Macedonia, The Former Yugoslav Republic of (mk)
and the given json does also have a `Macedonia` or `mk`.
Maybe the data should be updated.
Thanks.

The information below is not useful for this question.
-----------------------
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by raisedadead** [comment]
Hi @cmal, 

Thanks a lot for reporting, and sorry to hear about the discrepancy, but unfortunately Free Code Camp does not own/control the data on the https://www.flag-sprites.com website, I am guessing you will have to reach out to their support email mentioned on the website as of this comment as "info@spectraweb.cz", with your concern.

Hope this helps, closing as not an issue with FCC code base.
