### ISSUE TITLE
malfunction with --Cards Sequence 3, 7, Q, 8, A should return "-1 Hold"-- chalenge

### ISSUE THREAD

**Issue by RaroHub** [FreeCodeCamp/FreeCodeCamp#10004]
var count = 0;

function cc(card) {
  // Only change code below this line
  
switch(card)
  {
    case 2, 3, 4, 5, 6: return "5 Bet";
    case 7, 8, 9: return "0 Hold";
    case 10, 'J', 'Q', 'K', 'A': return "-5 Hold";
    case 3, 7, 'Q', 8, 'A': return  "-1 Hold";
    case 2, 'J', 9, 2, 7: return "1 Bet";
    case 2, 2, 10: return "1 Bet";
    case 3, 2, 'A', 10, 'K': return "-1 Hold";      
  }
  
  return "Change Me";
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(3); cc(7); cc('Q'); cc(8); cc('A');

**Comment by dwd2010** [comment]
@RaroHub, Did you ask help in the fcc chat room first?

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by AnastCh** [comment]
if u still need an answer

var count = 0;

function cc(card) {

 if(card >= 2 && card <=6)
   {
     count++;
   }
 else if(card === 10 || card == "J" || card == "Q" || card == "K" || card == "A")
   {
     count--;
   }
  if(count > 0)
    {
      return count + " Bet";
    }
  return count + " Hold";

}
cc(2); cc(3); cc(7); cc('K'); cc('A');

**Comment by texas2010** [comment]
@AnastCh 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
