### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by goonboy** [FreeCodeCamp/FreeCodeCamp#10013]
Challenge [Comparisons with the Logical And Operator](https://www.freecodecamp.com/challenges/comparisons-with-the-logical-and-operator#?solution=%0Afunction%20testLogicalAnd(val)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20if%20(val%20%3C%3D%2050%20%26%26%20%3E%3D%2025)%20%7B%0A%20%20%20%20%20%0A%20%20%20%20%20%20return%20%22Yes%22%3B%0A%20%20%20%20%0A%20%20%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20%22No%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestLogicalAnd(51)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

"Instructions
Combine the two if statements into one statement which will return "Yes" if val is less than or equal to 50 and greater than or equal to 25. Otherwise, will return "No".

My code:
```javascript

function testLogicalAnd(val) {
  // Only change code below this line

  if (val <= 50 && >= 25) {
     
      return "Yes";
    
  }

  // Only change code above this line
  return "No";
}

// Change this value to test
testLogicalAnd(51);

```
![image](https://cloud.githubusercontent.com/assets/20263611/17275080/de596678-56af-11e6-928f-18bd62bb2976.png)

**Comment by goonboy** [comment]
I am miffed....

**Comment by bugron** [comment]
@goonboy thanks for posting this issue!
Your logical expression on line 5 is not constructed correctly. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Get-Help) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by goonboy** [comment]
Ok thanks.  

Sorry...I am a newbie..
