### ISSUE TITLE
Remove obsolete dependencies from package.json

### ISSUE THREAD

**Issue by bugron** [FreeCodeCamp/FreeCodeCamp#10017]
Since we don't use it anymore.

**Update:** -by @raisedadead:
Issue mods do not close this in a merge. Lets keep this a recurring open issue for first timers.

**Comment by bugron** [comment]
We also seems don't use `cheerio`, `nodemailer-ses-transport`, `react-toastr`, `sanitize-html`, `url-regex`, `xss-filters`, `gulp-dest`, `happy`, `loopback-testing`, `jquery` npm package, @BerkeleyTrue, @raisedadead please, confirm.

**Comment by raisedadead** [comment]
thanks for the issue, will have a look and get back

**Comment by kaylegh** [comment]
I removed the conresponding line, and wait for @raisedadead  return

**Comment by raisedadead** [comment]
Not Checked Yet | Package | Required 
---------------- | ------------ | ---------------
not yet | cheerio | 
Checked, dependency for loopback | nodemailer-ses-transport  | **YES** - Do NOT remove
not yet | react-toastr | 
not yet | sanitize-html | 
not yet | url-regex | 
not yet | xss-filters | 
not yet | gulp-dest | 
not yet | happy | 
not yet | loopback-testing jquery |

**Comment by raisedadead** [comment]
Will update when I can, but @BerkeleyTrue has to sign off on this.

**Comment by bugron** [comment]
@raisedadead don't you need to `import` or `require` nodemailer-ses-transport somewhere to actually use it or it's plugged in automatically?

**Comment by BerkeleyTrue** [comment]
@bugron A lot of modules are automatically imported by loopback.

What the hell is happy?

**Comment by bugron** [comment]
@BerkeleyTrue cool, just wanted to confirm (all other packages used by loopback either are inported or required of specified in middlewares json file).
https://www.npmjs.com/package/happy

**Comment by BerkeleyTrue** [comment]
react-toastr, cheerio, happy and loopback-testing should be removed.

**Comment by iamrudra** [comment]
I can take this one.

**Comment by shreya22** [comment]
hello everybody. m struggling with my first time contribution in opensource. one query.. when we see an open issue, we work towards it. but there may be many more working on the same thing. so, is it like a matter of time, the one submitting fast as soon as its open will be considered first and may win..?
thanks :)

**Comment by raisedadead** [comment]
Hi @kaylegh @iamrudra and @kaylegh, thanks for responding, and welcome to contributing to Free Code Camp. Glad to know that you are fired up for taking this up, and making it hard for us to decide :stuck_out_tongue_winking_eye: , so here is what we will do:

Each contributor can **take up just one dependency** that has been confirmed for removal. Comment below who;s gonna take what.

I think @kaylegh already has made a commit, so `async` has been done. Others please choose yours.
Make sure you go through the Contribution Guidelines and Refer especially on how to create a pull request.

Most importantly do not include issue nos anywhere, and in this particular case you can ignore the closes tag for the PR description.

Thanks a lot and happy fixing!

**Comment by shreya22** [comment]
i am taking this

**Comment by iamrudra** [comment]
@raisedadead - I will remove - react-toastr, cheerio. You said one but I guess we have 4 to divide between myself and @shreya22. Let me know if you **strictly** want me to take one.

**Comment by sync350** [comment]
Well, I'll jump in as well, new to open source contributions as well. I'll take loopback-testing

**Comment by abhisekp** [comment]
[**`npm-check`**](http://npm.im/npm-check) is a nice command line app to automagically :sparkles: report unwanted packages and can be removed easily.

**Comment by BerkeleyTrue** [comment]
@abhisekp Yes, that is a great project, but it gives a lot of false positives with applications that dynamically require modules like loopback does.

**Comment by raisedadead** [comment]
Hey guys! Thanks a lot for your willingness to contribute, we are glad to hear about your enthusiasm. 

Here's what we precisely want to avoid any confusions, but first we want you to understand that we look forward to every one's contribution, the point being, we are not looking for the fastest contributor, but more contributors who actually understand the process.

So, for now among the already identified packages, please take this in the following order:

1. @kaylegh please open a pull request if you are ready for `async`
2. @iamrudra : just one package this time, please open a PR for `react-toastr`, request you to check loads of  open issues marked `help wanted`
3. @shreya22 please open a pull request for `cheerio`
4. @sync350 yup `loopback-testing` is all yours.

Reach out to the Contributors chat should you need any further clarification.

**Comment by iamrudra** [comment]
@raisedadead - I really love the spirit here - Divide the trivial task among first timers to motivate them and get a rub of how open source works. I must say FCC is one of the best communities that I've seen.

**Comment by iamrudra** [comment]
- [ ] First PR towards FCC :smiley:

**Comment by BerkeleyTrue** [comment]
Closing in favor of #10395
