### ISSUE TITLE
Problem 172 : how to solve

### ISSUE THREAD

**Issue by unfomo1** [FreeCodeCamp/FreeCodeCamp#10015]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by bugron** [comment]
@unfomo1 thanks for posting this issue!
Closing. Please feel free to re-open with steps to reproduce the issue. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Get-Help) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
