### ISSUE TITLE
Do we need console on the non JS challenges?

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#10016]
![image](https://cloud.githubusercontent.com/assets/1884376/17275484/d1f4e25e-5727-11e6-9356-bcd7ebb6f305.png)

**Comment by BKinahan** [comment]
You could argue that the `running test` / `tests completed` messages are still useful to show that the tests are running correctly, although in a case where they run correctly once and then fail for some reason those messages will still be on display.

I'd say the console doesn't add anything crucial for any challenge which doesn't output values relevant to the challenge to it explicitly.

**Comment by atjonathan** [comment]
I like the feature, but I don't think it's necessary.

> I'd say the console **doesn't add anything crucial** for any challenge which doesn't output values relevant to the challenge to it explicitly.

:+1: 

cc/ @BerkeleyTrue

**Comment by BerkeleyTrue** [comment]
What's the current behavior in production? 

While we now have three states for the test suite (pass/fail/refreshing) we could always use more queues to indicate that the user's solution is being tested.

**Comment by raisedadead** [comment]
Currently production does not have console on non JS challenges.
