### ISSUE TITLE
"Profile Lookup" instructions are ambiguous and don't match "accepted solution"

### ISSUE THREAD

**Issue by orrow** [FreeCodeCamp/FreeCodeCamp#10028]
#### Challenge Name
Profile Lookup

https://www.freecodecamp.com/challenges/profile-lookup

#### Issue Description

The instructions include the following: 

> If firstName does not correspond to any contacts then return "No such contact"

> If prop does not correspond to any valid properties then return "No such property"

Problem 1:
According to the instructions, the function should not return "No such property" if prop corresponds to a valid property -- period -- regardless of the associated firstName.  However, the solution offered at https://freecodecamp.github.io/wiki/en/challenge-profile-lookup/  will return "No such property" in the case that there is an invalid property paired with a valid firstName -- even though the property exists paired with a different firstName.

Problem 2:
It is possible to have both an invalid firstName and an invalid prop.  In that case it is not clear, according to the instructions, what should be returned:  both "No such contact" and "No such property"?

Suggested solution:
Modify the last line of the instructions to say:  
"If the prop argument does not correspond to any valid properties of any contact matching the firstName argument, then return: "No" firstName "has a" prop "property".

**Comment by BKinahan** [comment]
Thanks for reporting this issue @orrow.
This section of the instructions:
>The function should check if `firstName` is an actual contact's `firstName` and the given property (`prop`) is a property of that contact.

does clarify implicitly what the function should do, but the final sentence of the instructions
>If `prop` does not correspond to any valid properties then return `"No such property"`

may add some ambiguity if that clarification is overlooked or misconstrued. To resolve this, the final sentence can be amended to
>If `prop` does not correspond to any valid properties of a contact found to match `firstName` then return `"No such property"`.

This should address both problems of ambiguity.

**To potential contributors**: 
This issue can be resolved by opening a pull request that changes line 5337 of [this file](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/429f7bea574dd4c8e03906780e09a27851489cb2/seed/challenges/01-front-end-development-certification/basic-javascript.json#L5337) as detailed above. Please follow the [Contributor's Guide](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and remember to visit the [HelpContributors](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you need any assistance. We're here to help!

**Comment by orrow** [comment]
Perfect!
