### ISSUE TITLE
Not passing the challenge even though I get the answer correctly returned.

### ISSUE THREAD

**Issue by siyafazila** [FreeCodeCamp/FreeCodeCamp#10029]
Challenge [Adding a default option in Switch statements](https://www.freecodecamp.com/challenges/adding-a-default-option-in-switch-statements#?solution=%0Afunction%20switchOfStuff(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20%20switch%20(val)%20%7B%0A%20%20%20%20%0A%20%20%20%20case%20%22a%22%3A%0A%20%20%20%20%20%20answer%20%3D%20%22apple%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%0A%20%20%20%20case%20%22b%22%3A%0A%20%20%20%20%20%20answer%20%3D%20%22bird%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%0A%20%20%20%20case%20%22c%22%3A%0A%20%20%20%20%20%20answer%20%3D%20%22cat%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%0A%20%20%20%20default%3A%0A%20%20%20%20%20%20answer%20%3D%20%22stuff%20%22%3B%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AswitchOfStuff(%22a%22)%3B%0AswitchOfStuff(%22b%22)%3B%0AswitchOfStuff(%22c%22)%3B%0AswitchOfStuff(%22d%22)%3B%0AswitchOfStuff(4)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function switchOfStuff(val) {
  var answer = "";
  // Only change code below this line
  
   switch (val) {
    
    case "a":
      answer = "apple";
      break;
    
    case "b":
      answer = "bird";
      break;
   
    case "c":
      answer = "cat";
      break;
    
    default:
      answer = "stuff ";
          
  }
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
switchOfStuff("a");
switchOfStuff("b");
switchOfStuff("c");
switchOfStuff("d");
switchOfStuff(4);
```

**Comment by BKinahan** [comment]
Thanks for reporting, but unfortunately your code is not quite correct. You have included an extra space at the end of the string `"stuff"`, and removing it allows your code to pass all the tests.

Remember to use the [Help chat](https://gitter.im/FreeCodeCamp/Help) if you get stuck writing code; it's easy to overlook small details like this and having a fresh set of eyes look at your code can make them easier to spot 😄 

Happy coding!

**Comment by ceotimgorman** [comment]
function switchOfStuff(val) {
  var answer = "";
  // Only change code below this line
  switch (val) {
  case("a"):
  answer = ("apple");
  break;

  case ("b"):
  answer = ("bird");
  break;

  case ("c"):
  answer = ("cat");
  break;

  default:
   answer = ("stuff");
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
switchOfStuff(1);

**Comment by dolly-developer** [comment]
yes, iIwas stuck too with similar error but using brackets and double quotes with cases , i passed the challange.
