### ISSUE TITLE
One of the test cases isn't a palindrome.

### ISSUE THREAD

**Issue by YanKozlovskiy** [FreeCodeCamp/FreeCodeCamp#10024]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20s%20%3D%20str.toLowerCase().split(%2F%5B%5E%5Cw%5D%2B%2Fg).join(%22%22)%3B%0A%20%20%0A%20%20function%20reverse(string)%20%7B%0A%20%20%09var%20str%20%3D%20string.split(%22%22)%3B%0A%20%20%20%20var%20reverse%20%3D%20%5B%5D%3B%0A%20%20%20%20for%20(var%20i%20%3D%20str.length%20-%201%3B%20i%20%3E%3D%200%3B%20i--)%20%7B%0A%20%20%20%20%20%20reverse.push(string%5Bi%5D)%3B%0A%20%20%7D%0A%20%20%20%20if%20(reverse.join(%22%22)%20%3D%3D%3D%20string)%20%7B%0A%20%20%20%20%20%20return%20true%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%20%20return%20reverse(s)%3B%0A%7D) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function palindrome(str) {
  // Good luck!
  var s = str.toLowerCase().split(/[^\w]+/g).join("");
  
  function reverse(string) {
  	var str = string.split("");
    var reverse = [];
    for (var i = str.length - 1; i >= 0; i--) {
      reverse.push(string[i]);
  }
    if (reverse.join("") === string) {
      return true;
    }
    return false;
  }
  return reverse(s);
}
```

**Comment by Chrono79** [comment]
No issue, you have to address underscores for deletion too with your regex.

**Comment by BKinahan** [comment]
@YanKozlovskiy Yes, your code is not quite complete as @Chrono79 indicated, because `\w` includes not only numbers and letters but also the underscore character.
