### ISSUE TITLE
Bug - Create a Block Element Bootstrap Button - Won't finish submitting.

### ISSUE THREAD

**Issue by g3istb0t** [FreeCodeCamp/FreeCodeCamp#10025]
Challenge Name: Create a Block Element Bootstrap Button
Link: https://goo.gl/7IEJ4j

Issue: 
Challenge wants you to bootstrap the btn-block class within the btn class. After entering in the code specified you can see the changes occur on the right side, with the button expanding across the screen. How ever the check off area it remains red, and when trying to hit submit it does not proceed. Here is the code that it wants you to submit -

`<button class="btn btn-block">Submit</button>`

and here is a screenshot of the code in action along with the red check-off area.

<img src="http://i.imgur.com/KCcsUy4.png">

Troubleshooting:
Closed and reopened browser
Cleared Cache/Cookies/Temp Files.
Attempted to use another browser (iexplore)
Reset code.
Deleted and re-wrote code.
Moved the positioning of the code, ie `<button class="btn-block btn">Like</button>`

Swapping the code around resolved the issue.  After changing the location of the class elements and hitting submit it proceeded as normal. I believe this is likely a bug

* Browser Name, Version:  Firefox 47.0
* Operating System:  Windows 10
* Mobile, Desktop, or Tablet:  Desktop

**Comment by dhcodes** [comment]
@g3istb0t Forgive me if this sounds obtuse, but are you clicking the "Run Tests" button or the "Submit" button because the latter is an example in the instructions and you need to click "Run Tests" to proceed. I ask because I replicated your steps and it worked for me (i.e. the tests passed) though I am on a diff. machine.

**Comment by raisedadead** [comment]
The tests need to be updated to allow any order for the classes.
`<button class="btn btn-block">` and `<button class="btn-block btn">` both are correct.

**Comment by atjonathan** [comment]
@raisedadead Both pass fine for me?

**Comment by raisedadead** [comment]
Oh, bummer. Yes. IDK the first instant I could not pass.
@g3istb0t Can you copy and share your original code in here?

**Comment by Bouncey** [comment]
I can't reproduce

**Comment by BKinahan** [comment]
Same here, can't reproduce this.

@g3istb0t Just to be absolutely clear, when you say
>How ever the check off area it remains red, and when trying to hit submit it does not proceed

and in general when you refer to pressing the submit button, you do mean the "Run tests" button and not any of the buttons actually labeled as `Submit`, correct?

**Comment by atjonathan** [comment]
Closing as stale. Please reopen if this issue still occurs!

**Comment by esanto1** [comment]
This is still an issue. Using Safari 9.1.2 to do the course and can't get past this section. I have also tried re-starting browser without luck and resetting the level without luck.

**Comment by esanto1** [comment]
<button class="btn btn-block">Like</button>
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit" class="btn-block btn">Submit</button>

**Comment by esanto1** [comment]
`  <button class="btn btn-block">Like</button>
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit" class="btn-block btn">Submit</button>`

**Comment by monstermeat** [comment]
This happened to me today, but changing the order of the classes didn't fix it.

Safari 9.1.2
OS X El Capitan 10.11.6
Desktop

**Comment by XenoDelMoto** [comment]
Same issue 
Chrome
Linux

**Comment by Bouncey** [comment]
@monstermeat @XenoDelMoto 

To be sure, you are still hitting the `Run Tests (ctrl+enter)` button to complete the challenge?

I still can't reproduce. 

@XenoDelMoto it would be great if you could paste your code here for us to see

**Comment by XenoDelMoto** [comment]
<link href="https://fonts.googleapis.com/css?family=Lobster"
rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text text-center">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="
https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.
"></a>

  <img src="https://bit.ly/fcc-running-cats" class="img-responsive"
alt="Three kittens running towards the camera. ">
  <button class="btn">Like</button>
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit btn btn-block ">Submit</button>
  </form>
</div>

**Comment by Bouncey** [comment]
@xenodelmoto there is an issue with your code, please reread the instructions. If you are still stuck, please click the 'Help' button and you will be taken to a dedicated chat room where people can advise you on you code

**Comment by monstermeat** [comment]
@Bouncey Yes, I was hitting the "Run tests" button like in every other assignment. However, the problem seems to have been corrected. I went again just now to the only assignment in the first four sections that was marked unfinished, didn't change a thing and tried again. This time, it worked.
