### ISSUE TITLE
Border radius - 50% vs 50px

### ISSUE THREAD

**Issue by ulmas** [FreeCodeCamp/freecodecamp#1002]
When completing this challenge, setting the border-radius to "50px" still marks it as complete.

Should only mark as complete if the value is "50%"

**Comment by QuincyLarson** [comment]
Nice catch! I'll fix this.

**Comment by digitaldak** [comment]
Quincy, I think this and 966 are the same, not sure how to link via this. Sorry.

**Comment by LumenTeun** [comment]
You're right @digitaldak, this is a dupe of #966.
To link to an issue in the same repo, you just need tu use a # before the number, like I did above. To notify a user, use @ and their username.

**Comment by clearsmoke** [comment]
..sorry, seeing this late, thanks guys!
