### ISSUE TITLE
Issue about Challenge - Target the same element with multiple jQuery Selectors

### ISSUE THREAD

**Issue by JaeLiao** [FreeCodeCamp/FreeCodeCamp#10021]
#### Challenge Name
Only add one class with each of your three selectors.

#### Issue Description
Only the task "Only add one class with each of your three selectors." fails. I think I've done that only one class is added with the the different selectors in my code.

#### Browser Information
Chrome 52.0.2743.82 m
Win10
Desktop

#### Your Code

```html
<script>
  $(document).ready(function() {
    $("button").addClass ("animated");
    $(".btn").addClass ("shake");
    $("#target1").addClass ("btn-primary");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```

#### Screenshot
![issue](https://cloud.githubusercontent.com/assets/5039640/17277312/8725d27e-5772-11e6-9d29-db203b136109.jpg)

**Comment by atjonathan** [comment]
Thanks for reporting this @JaeLiao, this is because our tests don't seem to allow for spaces in between `.addClass` and `(`**`className`**`)`. An example of what passes fine:
```js
$("button").addClass ("animated");
$(".btn").addClass ("shake");
$("#target1").addClass ("btn-primary");
```
We should adjust the tests to allow spaces :+1:

**Comment by dhcodes** [comment]
Tested locally and the added regex in the PR above seems to fix this. Hopefully it's gtg.

**Comment by katbryers** [comment]
Having the same error happen except non of my check list on the side will change.
and it won't run the test at all.

<img width="1276" alt="screen shot 2016-11-06 at 6 10 51 pm" src="https://cloud.githubusercontent.com/assets/23280379/20042687/94d8b59a-a44c-11e6-9b9a-6560d007844f.png">
