### ISSUE TITLE
target of children query doesn't let me go by even though all children elements are present

### ISSUE THREAD

**Issue by saraivenegas** [FreeCodeCamp/FreeCodeCamp#10030]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by BKinahan** [comment]
@saraivenegas Hi, could you please add some more information to your issue description to detail what is going on, and include your code?

It might be that there is some problem in your code that is preventing it from passing the tests. Be sure to visit the [Help chat](https://gitter.im/FreeCodeCamp/Help) when you are stuck with writing code.

**Comment by Bouncey** [comment]
Closing as stale, @saraivenegas if you are still having issues that cannot be resolved in gitter chat, please comment here.
