### ISSUE TITLE
Test case bug in 'Algorithm Inventory Update'

### ISSUE THREAD

**Issue by Np463** [FreeCodeCamp/FreeCodeCamp#10038]
Challenge [Inventory Update](https://www.freecodecamp.com/challenges/inventory-update#?solution=%0Afunction%20updateInventory(arr1%2C%20arr2)%20%7B%0A%20%20%20%20arr2.forEach(function(newItem)%20%7B%0A%20%20%20%20%20%20var%20found%20%3D%20false%3B%0A%20%20%20%20%20%20arr1.forEach(function(item%2C%20index)%20%7B%0A%20%20%20%20%20%20%20%20if(newItem%5B1%5D%20%3D%3D%3D%20item%5B1%5D)%20%7B%0A%20%20%20%20%20%20%20%20%20%20item%5B0%5D%20%3D%20newItem%5B0%5D%3B%0A%20%20%20%20%20%20%20%20%20%20found%20%3D%20true%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%20%20if(!found)%20%7B%0A%20%20%20%20%20%20%20%20arr1.push(newItem)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D)%3B%0A%20%20%20%20arr1.sort(function(a%2C%20b)%20%7B%0A%20%20%20%20%20%20if(a%5B1%5D%20%3E%20b%5B1%5D)%20%7B%0A%20%20%20%20%20%20%20%20return%201%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20if(a%5B1%5D%20%3C%20b%5B1%5D)%20%7B%0A%20%20%20%20%20%20%20%20return%20-1%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20return%200%3B%0A%20%20%20%20%7D)%3B%0A%20%20%20%20return%20arr1%3B%0A%7D%0A%0A%2F%2F%20Example%20inventory%20lists%0Avar%20curInv%20%3D%20%5B%0A%20%20%20%20%5B21%2C%20%22Bowling%20Ball%22%5D%2C%0A%20%20%20%20%5B2%2C%20%22Dirty%20Sock%22%5D%2C%0A%20%20%20%20%5B1%2C%20%22Hair%20Pin%22%5D%2C%0A%20%20%20%20%5B5%2C%20%22Microphone%22%5D%0A%5D%3B%0A%0Avar%20newInv%20%3D%20%5B%0A%20%20%20%20%5B2%2C%20%22Hair%20Pin%22%5D%2C%0A%20%20%20%20%5B3%2C%20%22Half-Eaten%20Apple%22%5D%2C%0A%20%20%20%20%5B67%2C%20%22Bowling%20Ball%22%5D%2C%0A%20%20%20%20%5B7%2C%20%22Toothpaste%22%5D%0A%5D%3B%0A%0A%2F%2FupdateInventory(curInv%2C%20newInv)%3B%0AupdateInventory(%5B%5B21%2C%20%22Bowling%20Ball%22%5D%2C%20%5B2%2C%20%22Dirty%20Sock%22%5D%2C%20%5B1%2C%20%22Hair%20Pin%22%5D%2C%20%5B5%2C%20%22Microphone%22%5D%5D%2C%20%5B%5B2%2C%20%22Hair%20Pin%22%5D%2C%20%5B3%2C%20%22Half-Eaten%20Apple%22%5D%2C%20%5B67%2C%20%22Bowling%20Ball%22%5D%2C%20%5B7%2C%20%22Toothpaste%22%5D%5D)) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.

**Issue Description:** Test case 3 adds the new inventory item quantities to the current item quantities, while the other test cases only change the current item quantities to the new quantities. For example, the test expects [88, "Bowling Ball"], when array 1 has [21, "Bowling Ball"] and array 2 has [67, "Bowling Ball]

My code:
```javascript

function updateInventory(arr1, arr2) {
    arr2.forEach(function(newItem) {
      var found = false;
      arr1.forEach(function(item, index) {
        if(newItem[1] === item[1]) {
          item[0] = newItem[0];
          found = true;
        }
      });
      if(!found) {
        arr1.push(newItem);
      }
    });
    arr1.sort(function(a, b) {
      if(a[1] > b[1]) {
        return 1;
      }
      if(a[1] < b[1]) {
        return -1;
      }
      return 0;
    });
    return arr1;
}

// Example inventory lists
var curInv = [
    [21, "Bowling Ball"],
    [2, "Dirty Sock"],
    [1, "Hair Pin"],
    [5, "Microphone"]
];

var newInv = [
    [2, "Hair Pin"],
    [3, "Half-Eaten Apple"],
    [67, "Bowling Ball"],
    [7, "Toothpaste"]
];

//updateInventory(curInv, newInv);
updateInventory([[21, "Bowling Ball"], [2, "Dirty Sock"], [1, "Hair Pin"], [5, "Microphone"]], [[2, "Hair Pin"], [3, "Half-Eaten Apple"], [67, "Bowling Ball"], [7, "Toothpaste"]])
```

**Comment by erictleung** [comment]
@Np463 thanks for the issue. However, the third test case is correct in what it is asking for. 

> Compare and update the inventory stored in a 2D array against a second 2D array of a fresh delivery. Update the current existing inventory item quantities (in `arr1`). 

What you need to do is to look at the first array give, `arr1`, and find what new inventory items you get in the second array given, `arr2`. Implicit in the instructions is that you need to add the items from `arr2` to `arr1`. Is my assumption correct that this was unclear from the instructions? 

I can agree that the instructions aren't very clear on what you need to do. But looking at the tests, you can get an idea of what you need to code up.

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help).
