### ISSUE TITLE
Problem with calling the function

### ISSUE THREAD

**Issue by illertimes** [FreeCodeCamp/FreeCodeCamp#10033]
Challenge [Write Reusable JavaScript with Functions](https://www.freecodecamp.com/challenges/write-reusable-javascript-with-functions#?solution=%0A%2F%2F%20Example%0Afunction%20ourReusableFunction()%20%7B%0A%20%20console.log(%22Heyya%2C%20World%22)%3B%0A%7D%0A%0AourReusableFunction()%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20reusableFunction()%20%7B%0A%20%20console.log('Hi%20World')%3B%0A%7D%0AreuseableFunction()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourReusableFunction() {
  console.log("Heyya, World");
}

ourReusableFunction();

// Only change code below this line
function reusableFunction() {
  console.log('Hi World');
}
reuseableFunction();

```

**Comment by dhcodes** [comment]
@illertimes I believe this is caused by a typo in your function call. `reuseableFunction` should be `reusableFunction()`. Remove the extra 'e' in reuseable an you'll be in business.

**Comment by illertimes** [comment]
@dhcodes  Thanks man I appreciate it... embarrassing to say the

**Comment by illertimes** [comment]
least

**Comment by djfliq1** [comment]
I did the same thing!
