### ISSUE TITLE
Urgent help please

### ISSUE THREAD

**Issue by EceDilek** [FreeCodeCamp/FreeCodeCamp#10036]
I have started this developing adventure just three hours ago. I guess 17th challenge is not something really tough but although searching the solution on the net, i couldnt find a way to solve it. Can you please tell me what is my mistake? I need to make the photo's size to 100 px. 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by BKinahan** [comment]
Hi, @EceDilek! First of all, welcome to FreeCodeCamp 😄 

Please note that issues are for reporting bugs with the challenges or the FreeCodeCamp website.

There is a [Help chat](https://gitter.im/FreeCodeCamp/Help) that you can use for help with writing code, and that is the best place for your question, so do check it out 👍 

Happy coding!
