### ISSUE TITLE
Typo and Broken Link

### ISSUE THREAD

**Issue by patallen** [FreeCodeCamp/freecodecamp#1004]
Challenge http://www.freecodecamp.com/challenges/waypoint-join-our-chat-room has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Typo:
3. Click this link, which will email you **can** invite to Free Code Camp's Slack chat rooms: http://freecodecamp.com/api/slack.

Also, the link doesn't send me an email... It just directs me back to the same page... I'm using FF on linux.

**Edit**:  Okay, I see now that it is not supposed to redirect you... Still no email, however. I've never been known to be patient though, maybe it is in queue.

**Comment by QuincyLarson** [comment]
@patallen I've heard Slack is having issues tonight. Be sure to check your spam folder and confirm that your email is correct.
