### ISSUE TITLE
Error: Can't execute code from a freed script. [Run test ctrl+entr not working]

### ISSUE THREAD

**Issue by VermaNo1** [FreeCodeCamp/FreeCodeCamp#10046]
![error](https://cloud.githubusercontent.com/assets/4408661/17326992/b07bcc9e-58d2-11e6-87a0-8199492a3cbe.jpg)
Challenge [Create Bootstrap Wells](https://www.freecodecamp.com/challenges/create-bootstrap-wells#?solution=%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%20well%22%3E%0A%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%20well%22%3E%0A%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6 well">

    </div>
    <div class="col-xs-6 well">

    </div>
  </div>
</div>

```

**Comment by raisedadead** [comment]
Interesting, and thanks for the issue, although I can't reproduce the same with the above code, I am a bit certain of why you maybe getting this.

As you type along your code, the same gets executed live (jQuery calls and executions happen live) on the iPhone preview.

So it's possible that while your code was being parsed, the script broke. This happens at times. Unfortunately I am not sure much can be done about it. We cannot certainly stop the live update, that would make the results counter-intuitive.

On that note your code above is also not correct, try reset and complete the code as needed by the challenge, I think you should be good.

Hint: You might have stuff in the wrong place and also have deleted some other stuff.
If you are stuck then click the Help button

**Comment by oxy-a** [comment]
I have the same problem.

**Comment by oxy-a** [comment]
I found the way this challenge works: you have to create two divs inside each col-xs-6 div's.
Here is my code:
```html

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well"></div>
    </div>
    <div class="col-xs-6">
      <div class="well"></div>
    </div>
  </div>
</div>
