### ISSUE TITLE
Changing font size of an Element

### ISSUE THREAD

**Issue by aljonimp11** [FreeCodeCamp/FreeCodeCamp#10049]
This is my current code, can someone please help me find my error. I have looked it over many times and still cannot find it.
<style>
  .red-text {color: red;}
  p {font-size: 16px;}
</style>
<h2 class="red-text">CatPhotoApp</h2>
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p2>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p2>

**Comment by oalhait** [comment]
Hi @aljonimp11, this isn't the place to get help with your code. Please ask in the [gitter chat](https://gitter.im/FreeCodeCamp/FreeCodeCamp) as well!

**Comment by aljonimp11** [comment]
Okay, thank you!
