### ISSUE TITLE
Is this a bug or I am wrong? I get the results correctly but still can not pass...

### ISSUE THREAD

**Issue by cagiant** [FreeCodeCamp/FreeCodeCamp#10047]
Challenge [Where do I belong](https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=%0Afunction%20getIndexToIns(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20arr%20%3D%20arr.sort(function(a%2Cb)%7B%0A%20%20%20%20return%20a%20%3E%20b%3B%0A%20%20%7D)%3B%0A%20%20for(var%20i%20in%20arr)%7B%0A%20%20%20%20if(arr%5Bi%5D%20%3E%20num)%7B%0A%20%20%20%20%20%20return%20i%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20%2B%2Bi%3B%0A%7D%0A%0AgetIndexToIns(%5B40%2C%2060%5D%2C%2050)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function getIndexToIns(arr, num) {
  // Find my place in this sorted array.
  arr = arr.sort(function(a,b){
    return a > b;
  });
  for(var i in arr){
    if(arr[i] > num){
      return i;
    }
  }
  return ++i;
}

getIndexToIns([40, 60], 50);

```

**Comment by oalhait** [comment]
Thanks for the issue submission, but your code has an issue. Your for loop uses variable i, but you then attempt to return i outside the for loop, which doesn't work because i isn't initialized outside the loop. You should initialize a variable outside the for loop as 0, and then increment it until it is the size of array. You should then just return it unincremented, as the number will be the size of arr (also 1+ the last index) when the loop exits. I edited your code, and this passed: 
```javascript
function getIndexToIns(arr, num) {
  // Find my place in this sorted array.
  arr = arr.sort(function(a,b){
    return a > b;
  });
  var x = 0;
  while(x < arr.length){
    if(arr[x] >= num){
      return x;
    }
    ++x;
  }
  return x;
}

getIndexToIns([40, 60], 50);
```

**Comment by oalhait** [comment]
Next time, it would be faster for you to check with [the FCC gitter chat](https://gitter.im/FreeCodeCamp/FreeCodeCamp); you'll get a quick response, and confirmation on whether or not it's a bug.

**Comment by raisedadead** [comment]
Thanks @oalhait for the clarification. 

@cagiant please discuss coding assistance in chat as mentioned, GitHub issues are for bugs on the website only.

**Comment by cagiant** [comment]
Thank all of you for your replies.   I will do as suggested in the emails.

发件人: Omar Alhait [mailto:notifications@github.com]
发送时间: 2016年8月2日 21:20
收件人: FreeCodeCamp/FreeCodeCamp
抄送: Cary; Author
主题: Re: [FreeCodeCamp/FreeCodeCamp] Is this a bug or I am wrong? I get the results correctly but still can not pass... (#10047)


Thanks for the issue submission, but your code has an issue. Your for loop uses variable i, but you then attempt to return i outside the for loop, which doesn't work because i isn't initialized outside the loop. You should initialize a variable outside the for loop as 0, and then increment it until it is the size of array. You should then just return it unincremented, as the number will be the size of arr (also 1+ the last index) when the loop exits. I edited your code, and this passed:

function getIndexToIns(arr, num) {

  // Find my place in this sorted array.

  arr = arr.sort(function(a,b){

    return a > b;

  });

  var x = 0;

  while(x < arr.length){

    if(arr[x] >= num){

      return x;

    }

    ++x;

  }

  return x;

}



getIndexToIns([40, 60], 50);
