### ISSUE TITLE
CSS correct, but not allowing me to continue

### ISSUE THREAD

**Issue by Laurensly** [FreeCodeCamp/FreeCodeCamp#10040]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

It has instructed me to create a style element using CSS that defines the h2 element as being blue. I have done this, but it says otherwise, which prevents me from fully completing my course.

My code:
```html
<style>
  h2 {color: blue;}
</style>

```

**Comment by dwd2010** [comment]
@Laurensly, did you delete h2 element?  there suppose to have more code. I dont see other code in there.

**Comment by Laurensly** [comment]
wow, I'm oblivious. I accidentally deleted my greater than sign. Fixed it though. Thanks! @dwd2010

**Comment by dwd2010** [comment]
Next time, use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!

**Comment by Laurensly** [comment]
Yes, I did. Since I thought it was a bug issue, I came here. The other chatters also thought the same thing. But, thank you for your suggestion. @dwd2010

**Comment by dwd2010** [comment]
@Laurensly, yeah. It is fine. all good.
