### ISSUE TITLE
[beta] Side of HTML Preview Hidden

### ISSUE THREAD

**Issue by adamisntdead** [FreeCodeCamp/FreeCodeCamp#10053]
![Screenshot](http://image.prntscr.com/image/8f7700527aea482192d06c25b3cfad4a.png)

#### Not sure if there is already an issue about this
The side of the html preview is hidden behind the code editor, see screenshot above

I would probably be able to fix this?

_On Chrome (iMac, El Capitan) - Screen size: 1920 x 1080_

**Comment by BKinahan** [comment]
Related to #9955.

Duplicate?

**Comment by adamisntdead** [comment]
Yes! Didn't know that existed, closing in favour of #9955
