### ISSUE TITLE
Bug in the web

### ISSUE THREAD

**Issue by Bisket17** [FreeCodeCamp/FreeCodeCamp#10054]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by Bisket17** [comment]
style>
  h2 {
    color: blue;
  }
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>  That's throwing an error

**Comment by BKinahan** [comment]
Hi @Bisket17, could you please provide some more information, such as which challenge you have noticed a problem with, and what your code is? There are sections in the issue description for this data, so it would be useful to edit your first comment on this issue to describe what is happening.

If you simply need help with writing the code for the challenge, please visit the [Help chat](https://gitter.im/FreeCodeCamp/Help).

**Comment by BKinahan** [comment]
Closing this as stale.

@Bisket17 You can reopen the issue if you have more information to add.

Happy coding!
