### ISSUE TITLE
Make "Learn how FCC Works" challenge easier to navigate (UX)

### ISSUE THREAD

**Issue by oalhait** [freeCodeCamp/freeCodeCamp#10056]
#### Challenge Name

[Learn how Free Code Camp Works](https://www.freecodecamp.com/challenges/learn-how-free-code-camp-works)
#### Issue Description

Going through the 12 slide slideshow is a bit tedious, as you have to keep pressing "Go to my next step" (as opposed to pressing arrow keys to navigate between slides). The image sizes are also not relative to the screen height, so if your window is small you'll have to scroll down every time to read the text/switch between slides. 
#### Screenshot

<img width="1087" alt="screen shot 2016-08-02 at 4 49 39 pm" src="https://cloud.githubusercontent.com/assets/5378470/17349463/c5b894e8-58d2-11e6-9951-98527e6f3e8c.png">
<img width="1088" alt="screen shot 2016-08-02 at 4 49 28 pm" src="https://cloud.githubusercontent.com/assets/5378470/17349464/c8f03d32-58d2-11e6-8253-c1b862072637.png">
<img width="1095" alt="screen shot 2016-08-02 at 4 46 15 pm" src="https://cloud.githubusercontent.com/assets/5378470/17349466/cc4c1064-58d2-11e6-8d66-f6c53143895c.png">

**Comment by atjonathan** [comment]
I also think that this challenge could do with some UX improvements. To start, I think all of these challenges should be able to be navigated via the arrow keys. The issue with scrolling is annoying also. The images could probably be made smaller.

cc / @FreeCodeCamp/issue-moderators

**Comment by QuincyLarson** [comment]
@atjonathan @oalhait yes - we plan to significantly reduce the length of these. If we used a fixed height for the images and their text, we could eliminate a lot of the variability in height. 

I think the most immediate improvement would be to go to the next challenge with the left and right arrows.

**Comment by oalhait** [comment]
I'll take on the left/right arrow issue! One question though: where do I find the html/css/js of the specific challenge?

**Comment by raisedadead** [comment]
Hi @oalhait thanks for helping out on the UX.

The challenges are now on react infrastructure, most of the views/controllers are in the `/common/app`, challenges are json files that are in the `/seed` directory.

The views are all JSX, styles are LESS

Do look a the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md)., happy fixing!

And reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors). for assistance.

**Comment by iamrudra** [comment]
@oalhait - BTW - The link in your first description of the issues points to localhost ;)

**Comment by oalhait** [comment]
@raisedadead thanks for the tips, I'm on it now! 
and @iamrudra HAHAHA oops, was viewing on my local instance

**Comment by sachinmour** [comment]
![arrow](http://i.makeagif.com/media/8-08-2016/kXM6o2.gif)

**Comment by QuincyLarson** [comment]
@sachinmour Oh - when I said arrow keys I meant on the keyboard - not adding additional UI elements.

Rather than add additional buttons, I think it would be better to ensure that the next step button and previous step buttons are always in the same place (by constraining the height of images/text) so you could just click them repeatedly. 

But we do want to add some hotkeys. The hotkeys are located in main.js

**Comment by sachinmour** [comment]
@QuincyLarson got it..

**Comment by sachinmour** [comment]
![10056](http://i.makeagif.com/media/8-16-2016/0CQjc-.gif)
@QuincyLarson

**Comment by anush6533** [comment]
Is the challenge solved ?

**Comment by ktajpuri** [comment]
This doesn't work yet?? Does it require some help?

**Comment by atjonathan** [comment]
This issue is open as `help wanted` @ktajpuri, @anush6533

**Comment by raisedadead** [comment]
We have transitioned to a smaller set of navigation on the beta, I guess we could close this @QuincyLarson ?

**Comment by QuincyLarson** [comment]
@raisedadead Yes - I don't think it's worth improving at this point. We only use a few of these slide challenges, and they're short - I think the longest one is like 4 slides.
