### ISSUE TITLE
nested anchor bug

### ISSUE THREAD

**Issue by znllnz** [FreeCodeCamp/FreeCodeCamp#10051]
#### Challenge Name
https://www.freecodecamp.com/challenges/nest-an-anchor-element-within-a-paragraph#

#### Issue Description
it says the anchor link is not nested in a <p> tag, when it clearly is

#### Browser Information
chrome current build
osx most recent update
macbook air

#### Your Code
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<a href="http://www.freecatphotoapp.com">cat photos</a>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

<p>View more 
  <a href="http://freecatphotoapp.com"> 
    cat photos
  </a> 
 if you please.</p>
```

This returns a message saying <a> needs to be nested but if I remove the first <a>, and/or replace it with the nested <a> from below it says I need <a> and an <a> nested in a </p>

 

#### Screenshot
![screen shot 2016-08-02 at 11 46 26 am](https://cloud.githubusercontent.com/assets/20784472/17337100/f03114ce-58a6-11e6-95fb-beb3dd5eb77e.png)
![screen shot 2016-08-02 at 11 45 30 am](https://cloud.githubusercontent.com/assets/20784472/17337121/01e08434-58a7-11e6-966b-c7d912e158b9.png)

**Comment by dwd2010** [comment]
@znllnz, you forget to add www in the link. that is how it wont passed. if you dont understand and you could ask help at chat room.
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!

**Comment by znllnz** [comment]
I LITERALLY COPIED THE URL FROM THE INSTRUCTIONS

**Comment by dwd2010** [comment]
@znllnz, I trying to say your code is incorrect. I did check it myself. by the way, I am talking about link in your code.
