### ISSUE TITLE
Information on contributor's guide is slightly off

### ISSUE THREAD

**Issue by iamrudra** [FreeCodeCamp/FreeCodeCamp#10068]
#### Contributor's guide

https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#getting-started

#### Issue Description

The guide says app runs at localhost:3001 but I tried it today and it runs at localhost:3000

#### Browser Information

* Browser Name, Version: Chrome, 52.0.2743.82 (64-bit)
* Operating System: Ubuntu 16.04

#### Your Code

```js
 N/A
```

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/12117759/17388546/c4db7402-59b1-11e6-877c-12919d45466d.png)

**Comment by oalhait** [comment]
I just tested this, and it works if you run http://localhost:3000 or 3001. However, on 3001, you get on interesting toast message on page load in the top right corner: 

<img width="196" alt="screen shot 2016-08-03 at 10 37 31 pm" src="https://cloud.githubusercontent.com/assets/5378470/17391450/12aaa356-59cb-11e6-8607-b961cea73449.png">
no clue what BrowserSync is, but I'm sure someone else can explain it. For the most part though, it seems like there is no difference between them.

**Comment by iamrudra** [comment]
@oalhait - For some reason (i haven't looked deeper) I cannot get it to run on `3001`

**Comment by raisedadead** [comment]
Hey guys, yes it will run at both the ports. 
The node server runs at 3000 and the [BrowserSync](https://www.browsersync.io) proxies it at 3001

You could connect to either, on 3000 you would just hit refresh once you edit some code in the editor.
Thanks for reporting but the Guide intends not to have them both mentioned to avoid confusion

Thanks and happy fixing!

P.S : Please head out to the Contributors Chat room, you will get clarifications very fast in there.
