### ISSUE TITLE
A vs An typo

### ISSUE THREAD

**Issue by patallen** [FreeCodeCamp/freecodecamp#1006]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-text-field has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Grammar: Should be 'a text field...'
Your app should have **an** text field input element.

**Comment by NatashaHaggard** [comment]
Fixed, opened a pull request  - https://github.com/FreeCodeCamp/freecodecamp/pull/1073
