### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by kaiTEM** [FreeCodeCamp/FreeCodeCamp#10061]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20h2%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  h2 {
    color: blue;
  }
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by dhcodes** [comment]
@kaiTEM Have you pasted the code you tried? I think the code above is from an earlier challenge. The directions state: 

> Inside your style element, change the h2 selector to .red-text and update the color's value from blue to red.

> Give your h2 element the class attribute with a value of 'red-text'.

but you haven't attempted that in the code above. Can you be more specific about what bug you are experiencing?

**Comment by BKinahan** [comment]
@kaiTEM Please provide more information about the issue you are experiencing.

**Comment by dwd2010** [comment]
well, that code is incorrect.  but we could wait for their respond.

**Comment by dwd2010** [comment]
@kaiTEM, 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

P.S. If you still have a problem with this challenges. please respond back to us at here. Thanks
Happy Coding!
