### ISSUE TITLE
Download all Gitter data for open dataset

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#10069]
We are planning to delete all the inactive Gitter rooms. Before we do, we need to make a full dump of all activity in those Gitter rooms, which we can then release as an open dataset.

**Comment by iamrudra** [comment]
@QuincyLarson - I haven't worked with Gitter ever - Any pointers on how can this be done? That will give me a head start in evaluating the level of effort and let you know if I can take this up.

**Comment by QuincyLarson** [comment]
@iamrudra we will need to talk with the Gitter team first. I will post additional details as soon as I have them.

**Comment by iamrudra** [comment]
@QuincyLarson - Sure. Update it on the thread once you have the info! :+1:

**Comment by QuincyLarson** [comment]
@iamrudra Here's the API the Gitter team pointed us toward: https://developer.gitter.im/docs/messages-resource

Please take a look at it and see if you write a script that can successfully download all the messages in a relatively small room as a test, such as: https://gitter.im/FreeCodeCamp/hikes

**Comment by BerkeleyTrue** [comment]
Closing as duplicating of #8418

**Comment by abhisekp** [comment]
@QuincyLarson My other script in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8418#issuecomment-242353108 can also be used to get 100000000000s of past messages without worrying about api rate limits :smile:

**Comment by abhisekp** [comment]
@QuincyLarson the script written in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8418#issuecomment-242353108 has the ability to download 10000000000s of past messages from a room without worrying about rate limitations. But due to gitter limitations, it downloads in burst of 100 messages and it took around 2-3 mins to download the whole 981 messages in the [**FreeCodeCamp/hikes**](https://gitter.im/FreeCodeCamp/hikes) room.

It can be optimized. (*theoretically thought of a method but not implemented*)

**Comment by QuincyLarson** [comment]
@abhisekp We have around My estimate is that it would take about 17 days to download a million messages, and I suspect our main chat room has more than that. If you could optimize it, great. 

Otherwise, I recommend we get this script ready to run continuously on a server for many different rooms. We also need the server to put this data somewhere. If it could output a .csv file for each room, that would be nice, because we could just release the CSV as open data.

We could focus on all the rooms we plan to delete first, then start running it on our main rooms (that won't be deleted).
