### ISSUE TITLE
Mouse cursor blinking disappears when it reaches a link inside <a href=>

### ISSUE THREAD

**Issue by HQuser** [FreeCodeCamp/FreeCodeCamp#10078]
Challenge [Quoting Strings with Single Quotes](https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes#?solution=%0Avar%20myStr%20%3D%20''%3Ca%20href%3D%22http%3A%2F%2Fwww.example.com%5C%22%20target%3D%5C%22_blank%5C%22%3ELink%3C%2Fa%3E'%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = ''<a href="http://www.example.com\" target=\"_blank\">Link</a>';



```

**Comment by BKinahan** [comment]
That's unusual. I'm not able to reproduce it with your code. Try refreshing the page, and if you still have the issue, see if it persists when the correct code is used, and then report back in this thread with this further information 😄 

If you need assistance writing the correct code, please visit the [Help chat](https://gitter.im/FreeCodeCamp/Help).

**Comment by HQuser** [comment]
@BKinahan It is happening in Google Chrome with Windows 10 X64, In Mozilla there's no such issue.
So I believe this site has some issues with Google Chrome?
