### ISSUE TITLE
Deploying api project 'URL Shortener' to Hyperdev in the format of the current example does not work

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#10076]
#### Challenge Name

[Backend API Projects - URL Shortener](https://www.freecodecamp.com/challenges/url-shortener-microservice)

#### Issue Description

[My URL Shortener](https://cat-swoop.hyperdev.space)

When appending a URL to the apps address, Hyperdev replaces `//` with `/` in the request, so the regex does not match a valid URL and returns an error to the user.

I have opened a question on their [discourse](https://support.hyperdev.com/t/hyperdev-replaces-with-in-requests-to-my-app/506/1)

The app worked locally.

**Comment by raisedadead** [comment]
@Bouncey: @Em-Ant is working on the prototypes for these HyperDev challenges. Perhaps he is the best person to reach out to.

**Comment by Em-Ant** [comment]
[My version](https://hyperdev.com/#!/project/fan-nape) seems to work (If something breaks, please tell me). I used regex to match URLs like you. In your code you are manually parsing the URL, maybe the problem is there.

**Comment by raisedadead** [comment]
Thanks @Em-Ant, blocking this for closure once we have the examples on HyperDev officially on Free Code Camp

**Comment by Bouncey** [comment]
Fixed it - closing
