### ISSUE TITLE
Exact Change Problem Issue

### ISSUE THREAD

**Issue by FatKoala** [FreeCodeCamp/FreeCodeCamp#10074]
#### Challenge Name

https://www.freecodecamp.com/challenges/exact-change

#### Issue Description

I had problem with this problem due to inaccurate calculations while working with "0.01" value. Sometimes returning value of calculation had wrong value after 7 or 8 decimal places (for example 1.01 - 0.01 = 0.999999996).
Did anyone else had similar problem?
I managed to solve it but still took me a lot of time to do it due to this issue that shouldn't happen... Anyone have any idea why it is so. My opinion is that it is due to way that js saves integer and float values...

#### Browser Information

* Browser Name, Version: Google Chrome, 52.0.2743.82 (64-bit)
* Operating System: Linux Ubuntu 16.04
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js
 
```

**Comment by BKinahan** [comment]
Hi, @FatKoala. You can read all about floating point arithmetic (and good ways to handle it) [here](http://floating-point-gui.de/) and other places online.

And a fun fact: JavaScript doesn't make a type distinction between floats and integers. `1` and `1.00000` are the same number in JS (though this isn't strictly the cause of the floating point precision errors you experienced).

It might be worthwhile to include a resource about floating point arithmetic (though not necessarily the one I linked to above) in the Helpful Links of this challenge as it is probably the first one which requires users to understand the precision issues it raises.

\cc @FreeCodeCamp/issue-moderators for feedback on adding such a link (and which link to add)

**Comment by raisedadead** [comment]
Yeah this is a very interesting topic and should be broached IMHO.

In JavaScript there is just on numeric Data type that is `number` and it's usually a 64 bit floating point (considering how Browsers (JS Engines to be precise) are implementing them).

Let's tag this as Help wanted for some one in the community to link up a good resource. I'll try and look up as well, but yeah it's better if it comes from someone who perhaps is a Language expert.

**Comment by FatKoala** [comment]
Thanks for the link, it was helpful... got really frustrated about problem while I was coding... now it has sense... I agree that it should be linked somewhere or explained earlier that those things happen...

**Comment by dhcodes** [comment]
I poked around a bit and @BKinahan's link seems to be at least as good if not better than most and seems to be a straight-forward site. I vote we use his link. I'm happy to do the PR unless someone else wants to.

**Comment by raisedadead** [comment]
@dhcodes please go ahead, :wink:
