### ISSUE TITLE
My FCC challenges have started all the way from the beginning. Also, my FCC appears in mobile format

### ISSUE THREAD

**Issue by jeffersonnnn** [FreeCodeCamp/FreeCodeCamp#10075]
#### Challenge Name

freecodecamp.com/jeffersonnnn

#### Issue Description

Now, i upgraded my laptop from Windows & to Windows 10 the day before. I use Chrome so i went ahead to download and sign in to chrome browser to access my FCC page. Worryingly, i can't seem to start from where i stopped in my challenges even though my profile acknowleges that i have gone above and beyond that place

Also, my FCC also appears to be in mobile format. I think...because i am not sure. i just isn't as it should be. 
 

#### Browser Information

* Browser Name, Version: Chrome Version 52.0.2743.116 m
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop
![camper jeffersonnnn s code portfolio free code camp](https://cloud.githubusercontent.com/assets/20580125/17394040/ef0acb90-59db-11e6-994c-1141a8b43109.png)
![say hello to html elements free code camp](https://cloud.githubusercontent.com/assets/20580125/17394042/efd6e96e-59db-11e6-959e-e14da625c030.png)

#### Your Code

```js
 
```

#### Screenshot

![Uploading Say Hello to HTML Elements   Free Code Camp.png…]()

**Comment by qmikew1** [comment]
Seems to be some compound issues going (imo more hardware related but I'll leave that to a mod).
1. When you upgraded from (presumably from win 7), it's possible that your local cache was cleared. (but as you've discovered you can access your solution from profile (that's normal in terms of cache btw).
2. The browser view. That newer chrome release based on some comments in forums etc., has had some UI changes (might be what you're perceiving) - **You might might want to include additional information like:
1. What kind of device is it and was chrome showing a desktop view in old chrome/windows version?
2. Have you tried looking at fcc from edge (default browser) just to see if it too renders in mobile view?
3. Do other sites in this new chrome version also display/render in mobile view?**

**Comment by jeffersonnnn** [comment]
oh thank you for being swift with a reply.
1. Indeed, i upgraded from win 7, so yeah.
2. I hope that this new feature(s) is not here to stay. 
a. I run with a core2duo on HP Pavilion dv6000; under win 7, i had the desktop version.
b. I have, i get the same mobile view.
c. No other site renders in mobile view with this new chrome and/or windows 10. it seems site-specific.

**Comment by jeffersonnnn** [comment]
Help needed!

**Comment by raisedadead** [comment]
@jeffersonnnn thanks for reporting. 

Luckily I am on a Windows 10, so I am all in to help resolve this. But meanwhile we request your patience, this being an isolated case for now atleast.

Just consolidating the scenario:
- [ ] Windows 10 , Chrome Version 52.0.2743.116 m
- [ ] Issue is also on all other browsers (including Edge)
- [ ] Machine is a Core 2 Duo, HP Pavilion DV 6000
- [ ] Issue wasn't present on your Win7 earlier.
- [ ] Issue is site specific, that is it is on Free Code Camp's website only

Just a few more in depth details should get us thru:

1. Could you check your system spec once and dump it here, it's available under `Settings > System . About`
2. What's the screen resolution of your machine, right now? Should be available in Settings > Personalization > Display
3. Have you upgraded to the latest graphics drivers for your System, to check that resolution is at par that your hardware supports?

Thanks.

**Comment by jeffersonnnn** [comment]
@raisedadead thank you!

All the above information remain true. 

1.
Edition                                  Windows 10 Enterprise
Product ID                            00329-00000-00003-AA172
Processor                              Intel(R) core(TM)2 CPU        T5600 @ 1.83 GHz GHz
Installed RAM                        2.00 GB
System type                           32-bit operating system, x64-based processor
Pen and Touch                       No pen or touch input is available for this display

2.
Resolution stands at 1024 x 768

3. 
i am missing a fair number of drivers as my upgrade wasn't done *properly. As it stands, i should have the nvidia geforce go7400 driver for my display but  it is missing. 

Can the above be the problem? hm. 

blessings on you and yours @raisedadead !

**Comment by raisedadead** [comment]
I just see two things with the second being a problem mostly:

> System type 32-bit operating system, x64-based processor: 
While it's not necessary, your processor does support a 64 bit OS, why not have Windows 10 64 bit? You don't have to answer this, and again this is not required as well.

> And yeah with the Graphics you mention, upgrading the drivers might resolve the issue. Was your resolution the same when your were on Windows 7?

**Comment by qmikew1** [comment]
The model specs suggests 1280x800 was the base - Almost guaranteed a driver or settings issue

**Comment by jeffersonnnn** [comment]
Well, the computer tech gave a long and convoluted explaination why i presently run a 32-bit on a x64-based processor. If it is absolutely necessary, i can go back to win 7.

I shall redownload my nvidia driver right now to see if that is responsible for the mobile view problem.

Any ideas about the other issue?

**Comment by raisedadead** [comment]
Downgrading to windows 7 : No not needed, stick with Win10 32 bit. That's okay.
Upgrade your drivers and run a windows update as well.

Let us know how it goes.

**Comment by qmikew1** [comment]
I feel for you (though I run linux and have my win10 installs in VMs so can't help you with a native hardware experience/troubleshooting). Really, though I think this is hardware related and less about site - If you google 'windows 10 nvidia problems' you get a ton of stuff ([e.g,](https://www.reddit.com/r/nvidia/comments/3krzli/windows_10_and_the_recent_nvidia_drivers/) - My guess is that you would have better luck in windows-hardware type forums etc. (as well as being prepared to troubleshoot a problematic upgrade (things don't always go smoothly, but that's part of the 'fun'). Maybe, also,  touching base with folks in the [general fcc gitter room](https://gitter.im/FreeCodeCamp/FreeCodeCamp) as you're doing this would be a good way to sort of walk through this in real time - But, again, just one person's opinion.

**Comment by alistermada** [comment]
It's possible that the mobile view could be due to zoom settings. I can get partial mobile view if I zoom in enough that the challenge switches to mobile view but the navbar stays the same. 

![image](https://cloud.githubusercontent.com/assets/12993334/17460140/ee3fdaa8-5c82-11e6-9eeb-12105b4da764.png)

**Comment by jeffersonnnn** [comment]
Thanks guys. my FCC is now in the right viewing format and i am at the right point in my challenges. What i eventually did was to downgrade back to win 7 because the combination of win 10 and the display driver i use for my laptop is ill fated. Apparently, there are compatibility issues. I couldn't have gotten ahead without the insights from this forum. Thanks all, you guys rock.

**Comment by BerkeleyTrue** [comment]
@jeffersonnnn glad it worked out.

Happy Coding
