### ISSUE TITLE
Incomplete style element removes test results from page until completed

### ISSUE THREAD

**Issue by digitaldak** [FreeCodeCamp/freecodecamp#1007]
Challenge http://www.freecodecamp.org/challenges/waypoint-use-css-selectors-to-style-elements has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

See screenshot, should be explanatory. 
Thought it was a neat bug in all truth.

![waypoint-use-css-selectors-to-style-elements](https://cloud.githubusercontent.com/assets/3256176/8265978/769be844-16c8-11e5-8ed2-c5cfb35f96fe.png)

**Comment by BerkeleyTrue** [comment]
This is expected behavior. Prevents the tests from crashing the browser.

Happy Coding!
