### ISSUE TITLE
Console reporting "Infinite loop potentials at line 8" no matter what I put for the loop. (originally I had the loop as a while(counter < num) and got the same error

### ISSUE THREAD

**Issue by ChristianRosa** [FreeCodeCamp/FreeCodeCamp#10082]
Challenge [Sum All Odd Fibonacci Numbers](https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers#?solution=function%20sumFibs(num)%20%7B%0A%20%20%0A%20%20var%20counter%20%3D%200%3B%0A%20%20var%20numArr%20%20%3D%20%5B1%2C1%5D%3B%0A%20%20var%20total%20%20%20%3D%200%3B%0A%20%20%0A%20%20for(var%20x%20%3D%200%3B%20x%20%3C%2010%3B%20x%2B%2B)%7B%0A%20%20%20%20counter%20%3D%20numArr%5BnumArr.length%20-1%5D%20%2B%20numArr%5BnumArr.length%20-2%5D%3B%0A%20%20%20%20%0A%20%20%20%20numArr.push(counter)%3B%0A%20%20%20%20%0A%20%20%20%20alert(numArr)%3B%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20total%20%3D%20numArr.reduce(function(a%2Cb)%7B%0A%20%20%20%20%0A%20%20%20%20if(!b%252)%7B%0A%20%20%20%20%20%20return%20a%20%2B%20b%3B%0A%20%20%20%20%7D%0A%20%20%20%0A%20%20%7D)%3B%0A%20%20%0A%20%20return%20total%3B%0A%7D%0A%0AsumFibs(4)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function sumFibs(num) {
  
  var counter = 0;
  var numArr  = [1,1];
  var total   = 0;
  
  for(var x = 0; x < 10; x++){
    counter = numArr[numArr.length -1] + numArr[numArr.length -2];
    
    numArr.push(counter);
    
    alert(numArr);
    
  }
  
  total = numArr.reduce(function(a,b){
    
    if(!b%2){
      return a + b;
    }
   
  });
  
  return total;
}

sumFibs(4);

```

**Comment by BKinahan** [comment]
@ChristianRosa It looks like your line `alert(numArr)` might be triggering the loop protection, since removing that line gets rid of the error.

You may have more luck logging debug values to the console instead of alerting them 😄

**Comment by BKinahan** [comment]
Yes, it has been confirmed for me that loop protection is based on time, and `alert` will trigger it because it will block the JavaScript execution for an indefinite amount of time while waiting for user input.

Please visit the [Help chat room](https://gitter.im/FreeCodeCamp/Help) if you have any trouble using `console.log()` for debugging in place of `alert()`.
