### ISSUE TITLE
Run tests not working and the validation checks below it aren't being displayed.

### ISSUE THREAD

**Issue by puneeth8994** [FreeCodeCamp/FreeCodeCamp#10081]
#### Challenge Name
Target the same element with multiple jQuery Selectors

#### Issue Description
The run tests button isn't working and the list of validation checks below it aren't visible.

#### Browser Information
Google chrome on windows 10

* Google Chrome, Version: 52.0.2743.116 m
* Operating System: Windows 10 
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
```
<script>
  $(document).ready(function() {
    
    $("button").addclass("animated");
    $(".btn").addclass("shake");
    $("#target1").addclass("btn-primary")
      
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```

#### Screenshot
![issue](https://cloud.githubusercontent.com/assets/20756601/17414810/96672d98-5aa4-11e6-8657-719ce1b60494.jpg)

**Comment by BKinahan** [comment]
@puneeth8994 This is a known bug and will be resolved soon, some jQuery syntax errors prevent tests from running correctly.

You have a capitalization error in your calls to `addClass()`, and fixing those lets the tests run and pass successfully..

Refer #9673

**Comment by TDSSSS** [comment]
addClass() ,  not  addclass    
true: "C"lass,   false: "c"lass
