### ISSUE TITLE
camel case is inconsistant 

### ISSUE THREAD

**Issue by corbinjensen** [FreeCodeCamp/FreeCodeCamp#10088]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22newline%20%5C%5C%20SecondLine%20ThirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "newline \\ SecondLine ThirdLine"; // Change this line



```

**Comment by Locheed** [comment]
You have a misunderstanding in your code. newline just tells You what escape You should use there. See below, bolded text. 
FirstLine**newline****backslash**SecondLine**backslash****carriage-return**ThirdLine

**Comment by BKinahan** [comment]
As @Locheed indicated, `newline` refers to one of the escaped characters that should be represented in your final string, and it is included in the table in the challenge instructions. You will notice that the case of `FirstLine` matches the case of `SecondLine` and `ThirdLine` as you correctly expect.

If you have any further questions about the challenge, please ask in the [HelpJavaScript](https://gitter.im/FreeCodeCamp/HelpJavaScript) chat room.

Happy coding!
