### ISSUE TITLE
Bug? Thanks!

### ISSUE THREAD

**Issue by JesterJinx** [FreeCodeCamp/FreeCodeCamp#10086]

**Comment by JesterJinx** [comment]
https://get.google.com/albumarchive/100392172461473720479/album/AF1QipMRWhXjg6zvc0OUetfPMFsJ_pqSHRUhvG0-EGl9/AF1QipM0XM8NHMUVoATqoLOzTaNKzaXxX6CQO5s3lmCz?source=pwa&authkey=Gv1sRgCJadn4npjpnGFQ

**Comment by dwd2010** [comment]
@JesterJinx, you posted link of something. This 
GitHub Issues are for reporting bugs on the FreeCodeCamp website only.

Happy Coding!

**Comment by JesterJinx** [comment]
Yes it was about a bug on the website, but I realised it was just me making an error, not the challenge's problem, so I closed this issue. Thanks! :)

**Comment by dwd2010** [comment]
@JesterJinx, oh ok. no problem. 

if you got stuck with challenge. you could go the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.
or other chat room for help. here is more information. https://github.com/freecodecamp/freecodecamp/wiki/official-free-code-camp-chat-rooms
Happy Coding!

**Comment by JesterJinx** [comment]
Precisely how I fixed my problem! Thanks again!
