### ISSUE TITLE
[beta] Add Animate.css to relevant challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#10087]

**Comment by BerkeleyTrue** [comment]
@FreeCodeCamp/issue-moderators Can someone add a list of challenges where animate.css is a required dependency?

Also, if you want to take a crack at adding it, take a look at https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10116/files#diff-83743a31096666f9b123fd17dee95e90R1225

It should look similar except without the `raw: true` bit.

Thanks!
