### ISSUE TITLE
Final video challenge redirects to nonexistent challenge

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#10089]
Steps to reproduce: 
If you complete this video challenge: http://beta.freecodecamp.com/en/challenges/chrome-developer-tools/chrome-dev-tools-summary beta will redirect you to the following nonexistent challenge: http://beta.freecodecamp.com/en/challenges/nonprofit-projects/greenfield-nonprofit-project-1

**Comment by Bouncey** [comment]
Update on this, final video challenge is now `Big O Notation: A Few Examples`, issue still exists.

@QuincyLarson where should the camper be directed once all the available video challenges are complete?

**Comment by QuincyLarson** [comment]
@Bouncey Since these aren't part of our curriculum, the most logical place would be to redirect them back to the map.
