### ISSUE TITLE
Teespring campaign should be in the shop

### ISSUE THREAD

**Issue by ArielLeslie** [FreeCodeCamp/FreeCodeCamp#10098]
Today's email has a link to a ["Future Coder" baby onesie campaign](https://teespring.com/future-coder-baby-onesies#pid=287&cid=6090&sid=front), but I don't see it at https://www.freecodecamp.com/shop

**Comment by raisedadead** [comment]
@QuincyLarson please check and guide? If pursuing this should go into the `backup/staging`.

**Comment by QuincyLarson** [comment]
@ArielLeslie yes - would you be interested in adding it to the shop? I haven't had time to do this yet.
