### ISSUE TITLE
Counting Cards: "0 Hold" won't accept?

### ISSUE THREAD

**Issue by ZVak18** [FreeCodeCamp/FreeCodeCamp#10099]
#### Challenge Name
https://www.freecodecamp.com/challenges/counting-cards

#### Issue Description
After finishing the code, all of my answers show up as correct except for the "0 Hold". However, in the viewer it shows "0 Hold". I'm not sure why this is not accepting my answer.

#### Browser Information
Chrome
Chrome OS Laptop

#### Your Code
```js
var count = 0;

function cc(card) {
  // Only change code below this line
  switch (card) {
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      count+=1;
      break;
    case 7:
    case 8:
    case 9:
      count = count + 0;
     break;
    case 10:
    case 'J':
    case 'Q':
    case 'K':
    case 'A':
      count-=1;
      break;
  }
  
  if (card > 0) {
    return count + " Bet";
  } else {
    return count + " Hold";
  }
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');
```

#### Screenshot
![screenshot 2016-08-05 at 9 14 33 am](https://cloud.githubusercontent.com/assets/20520435/17439441/bff99120-5aed-11e6-9cf7-3dc6cbf0ee49.png)

**Comment by dwd2010** [comment]
@ZVak18, did you ask a help at FCC chat room? if you didnt? 
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!

**Comment by raisedadead** [comment]
Your code is not correct. Try adding the test requirement i.e `cc(7); cc(8); cc(9);`

```js
// Add/remove calls to test your function.
// Note: Only the last will display
cc(7); cc(8); cc(9);
```

**Output:** `0 Bet`

Please reach out to the Help Chat as mentioned by @dwd2010. Happy coding!

**Comment by yplonggit** [comment]
why you use card > 0

**Comment by justinmdickey** [comment]
For anybody else wondering, you have to use:
 if (**count** > 0){
    return count + " Bet";
  } else {
    return count + " Hold";
  }

as opposed to:

if (**card** > 0){
    return count + " Bet";
  } else {
    return count + " Hold";
  }
