### ISSUE TITLE
http://www.freecodecamp.org/challenges/next-challenge results in 502 bad gateway

### ISSUE THREAD

**Issue by digitaldak** [FreeCodeCamp/freecodecamp#1009]
Finished (http://www.freecodecamp.org/challenges/waypoint-use-a-css-class-to-style-an-element)  and when it takes you to the next set of things it gives you that error message.

**Comment by dplomacy** [comment]
http://www.freecodecamp.org/challenges/next-challenge results in 502 bad gateway #1009

**Comment by BerkeleyTrue** [comment]
This should be fixed now
