### ISSUE TITLE
[beta] Challenge title tags are not displayed properly

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#10092]
[![https://gyazo.com/e2d4f6b5fa251a81b075ab354a0952b1](https://i.gyazo.com/e2d4f6b5fa251a81b075ab354a0952b1.png)](https://gyazo.com/e2d4f6b5fa251a81b075ab354a0952b1)

**Comment by BerkeleyTrue** [comment]
What is the issue with the title?

**Comment by atjonathan** [comment]
@BerkeleyTrue Should it not be **Create a GitHub account...** instead of **create-a-github-account**

**Comment by BerkeleyTrue** [comment]
Got it. It's using the dashed name instead of the title.
