### ISSUE TITLE
name not appearing on front and backend certficates

### ISSUE THREAD

**Issue by nbailey20** [FreeCodeCamp/FreeCodeCamp#10093]
#### Issue Description

I just claimed my backend certificate, and after viewing, I noticed that there is a blank space where my name should be. How can I get my name to appear? Additionally, the link to the certificate has my correct username at the bottom: "verify this certificate at ...".

#### Browser Information

The issue occurs in both Chrome and Safari so I would expect browser issues not to be the problem.

**Comment by qualitymanifest** [comment]
This is a common issue, see here:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8933

**Comment by raisedadead** [comment]
Hi Nick,

We need you Name on the portfolio to generate it, currently as I see on your profile page its not the case.
Possible reason being, you probably updated your name on GitHub after, joining Free Code Camp, here is  fix that should resolve this:

Visit : https://www.freecodecamp.com/settings

And click "Update my Portfolio from Github", this will update your FCC Profile with latest info including name.

This should start displaying your name on the certificate.

Let us know if you face any issues, or you can write to team@freecodecamp.com

**Comment by nbailey20** [comment]
thanks! going to settings worked perfectly.
