### ISSUE TITLE
[beta] Nested topics on map should show pointer on hover

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#10090]
If you hover your mouse over "getting started" or "join the Free Code Camp community" you should see a finger pointer cursor (currently you see a text selection cursor instead).

**Comment by alanbares** [comment]
I'll work on this.

**Comment by alanbares** [comment]
Well thought I could figure this out but now I'm not seeing the issue show up on the beta site and have no idea if I'm even doing anything when I'm editing what I think is the file to fix in map.less.

**Comment by BerkeleyTrue** [comment]
This is fixed
