### ISSUE TITLE
A problem when i run a challenge although i run it with correct output 

### ISSUE THREAD

**Issue by ShreefReda** [FreeCodeCamp/FreeCodeCamp#10095]
#### Challenge Name
[Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Afunction%20titleCase(str)%20%7B%0A%20%20var%20y%3D%20str.toLowerCase()%3B%0A%20%20var%20x%3D%20y.split('%20')%3B%0A%20%20var%20s%3D%22%22%3B%0A%20%20for(var%20i%3D0%3B%20i%3Cx.length%20%3B%20i%2B%2B)%7B%0A%20%20%20s%3Ds%2B(x%5Bi%5D.charAt(0).toUpperCase())%2B(x%5Bi%5D.slice(1))%2B%22%20%22%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20s%3B%0A%7D%0A%0AtitleCase(%22sHoRt%20AnD%20sToUt%22)%3B%0A)

#### Issue Description

I return  a correct output and it said error.

#### Browser Information

* Browser Name, Version: Google chrome
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: 

#### Your Code
```js
function titleCase(str) {
  var y= str.toLowerCase();
  var x= y.split(' ');
  var s="";
  for(var i=0; i<x.length ; i++){
   s=s+(x[i].charAt(0).toUpperCase())+(x[i].slice(1))+" ";
  }
  
  return s;
}

titleCase("sHoRt AnD sToUt");
 
```

#### Screenshot

![x](https://cloud.githubusercontent.com/assets/17913315/17433315/44df257e-5b04-11e6-8da9-29a6ffd5bb6c.PNG)

**Comment by raisedadead** [comment]
Have you reached out the [Help Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for assistance?

**Comment by raisedadead** [comment]
Closing as your code is incorrect. Please reach out to the chat and they will be able to help.

Happy coding!

**Comment by JBPereira** [comment]
raisedadead It would be helpful if you told what the error is, given that you identified it.

**Comment by texas2010** [comment]
@JBPereira, this is not place for ask help. that is why we have a chat room or forum. they could ask help at there.
this place is only GitHub Issues are for reporting bugs or typo on the website only.

Happy Coding.
