### ISSUE TITLE
Exact Change assumes campers are aware of US currency denominations 

### ISSUE THREAD

**Issue by JohnnyBizzel** [FreeCodeCamp/FreeCodeCamp#10097]
You assume people know the value of US currency.

#### Challenge Name
https://www.freecodecamp.com/challenges/exact-change

#### Issue Description
You just need to add this to the challenge helpful links

**Comment by raisedadead** [comment]
This is something which I myself had faced when I was doing the challenge and had to do through a quick wikipedia articles.

The US currency terminology is not same as many other countries for instance "Bills" can commonly be confused in some countries what "Checks" mean in US. In India for instance equivalent of Bills would be "Notes".

So the currency hierarchy should be clarified via an article or a lookup table linked from the forum, for campers.

**Comment by alistermada** [comment]
Seems to be related to #8719.

**Comment by Darksmurf** [comment]
I can try to find relevant links about US Currency.

**Comment by Darksmurf** [comment]
We could also write a wiki page about it.

**Comment by BerkeleyTrue** [comment]
Adding a list of term->value pairs to the description should be sufficient.

**Comment by mradzwilla** [comment]
After some Googling, this link seems okay http://www.path2usa.com/us-currency

But I also think that writing up something quickly is also a good option.

**Comment by Darksmurf** [comment]
How about this: https://www.universitylanguage.com/guides/us-currency/

Please do note, I tried to find something without half-dollars and dollar coins, so a camper would not get confused.

**Comment by Darksmurf** [comment]
We could paste this into the [wiki page for Exact Change](https://github.com/freecodecamp/freecodecamp/wiki/algorithm-exact-change):

Here is the list of relevant US currency units used in the challenge and their corresponding values. In parentheses is how they are referred to in the code :

* Penny -> $0.01 (PENNY)
* Nickel -> $0.05 (NICKEL)
* Dime -> $0.10 (DIME)
* Quarter -> $0.25 (QUARTER)
* Dollar -> $1.00 (ONE)
* 5 dollars -> $5.00 (FIVE)
* 10 dollars -> $10.00 (TEN)
* 20 dollars -> $20.00 (TWENTY)
* 100 dollars -> $100.00 (ONE HUNDRED)

**Comment by erictleung** [comment]
Here's HTML code for a table of the currency listed above https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10097#issuecomment-238053011

```html
<table class='table table-striped'><tr><th>Currency Unit</th><th>Amount</th></tr><tr><td>Penny</td><td>$0.01 (PENNY)</td></tr><tr><td>Nickel</td><td>$0.05 (NICKEL)</td></tr><tr><td>Dime</td><td>$0.10 (DIME)</td></tr><tr><td>Quarter</td><td>$0.25 (QUARTER)</td></tr><tr><td>Dollar</td><td>$1.00 (DOLLAR)</td></tr><tr><td>Five Dollars</td><td>$5.00 (FIVE)</td></tr><tr><td>Ten Dollars</td><td>$10.00 (TEN)</td></tr><tr><td>Twenty Dollars</td><td>$20.00 (TWENTY)</td></tr><tr><td>One-hundred Dollars</td><td>$100.00 (ONE HUNDRED)</td></tr></table>
```

It renders as

<table class='table table-striped'><tr><th>Currency Unit</th><th>Amount</th></tr><tr><td>Penny</td><td>$0.01 (PENNY)</td></tr><tr><td>Nickel</td><td>$0.05 (NICKEL)</td></tr><tr><td>Dime</td><td>$0.10 (DIME)</td></tr><tr><td>Quarter</td><td>$0.25 (QUARTER)</td></tr><tr><td>Dollar</td><td>$1.00 (DOLLAR)</td></tr><tr><td>Five Dollars</td><td>$5.00 (FIVE)</td></tr><tr><td>Ten Dollars</td><td>$10.00 (TEN)</td></tr><tr><td>Twenty Dollars</td><td>$20.00 (TWENTY)</td></tr><tr><td>One-hundred Dollars</td><td>$100.00 (ONE HUNDRED)</td></tr></table>

**Comment by Manish-Giri** [comment]
@erictleung looks like this has been idle for a few days. If this issue is still open, can I make the change?

**Comment by oalhait** [comment]
@Manish-Giri is it cool if i take this on? Sorry, just trying to get some experience with react.

**Comment by erictleung** [comment]
@Manish-Giri we've labeled the issue `first-timers-only` and I think you're a bit more than a first timer here 😃 

@oalhait same goes for you. The first timer's label means you've never contributed to this repository. You have, fortunately or unfortunately, have already contributed to this repository. If you're still interested in contributing, please look at the [`help wanted`](https://github.com/FreeCodeCamp/FreeCodeCamp/labels/help%20wanted) labeled issues.

**Comment by Manish-Giri** [comment]
@erictleung okay. I did see the first timers only label, but then I noticed this issue has been open for a week and no first-timers have taken it up, so I offered. Anyway, thanks.

**Comment by 03aliz** [comment]
@erictleung Hi is this issue still open? I would like to work on it as my first contribution.But is it possible to make a pull request for a wiki? how would I go about doing the workflow for this?thanks.

**Comment by raisedadead** [comment]
@03aliz yes this is still open.

This need not go into the wiki, and can be added in the description.

@erictleung mentioned the code:
```html
<table class='table table-striped'><tr><th>Currency Unit</th><th>Amount</th></tr><tr><td>Penny</td><td>$0.01 (PENNY)</td></tr><tr><td>Nickel</td><td>$0.05 (NICKEL)</td></tr><tr><td>Dime</td><td>$0.10 (DIME)</td></tr><tr><td>Quarter</td><td>$0.25 (QUARTER)</td></tr><tr><td>Dollar</td><td>$1.00 (DOLLAR)</td></tr><tr><td>Five Dollars</td><td>$5.00 (FIVE)</td></tr><tr><td>Ten Dollars</td><td>$10.00 (TEN)</td></tr><tr><td>Twenty Dollars</td><td>$20.00 (TWENTY)</td></tr><tr><td>One-hundred Dollars</td><td>$100.00 (ONE HUNDRED)</td></tr></table>
```

Add it to this challenge [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/advanced-bonfires.json#L144)
