### ISSUE TITLE
Performance issues should be handled when data is not ready.

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#10109]
![image](https://cloud.githubusercontent.com/assets/1884376/17458344/54d34c26-5c2b-11e6-9b6f-462a8b24a302.png)

When data is not completely loaded, actions should be prevented (preventive error handling). This will get partially addressed when we have a progress check via #9735 

Todo : Add screen caps from production site, to ascertain this is not a local setup problem (the bundle.js is way to heavy on a local setup right now).

**Comment by BerkeleyTrue** [comment]
Can you give more detail about what's happening here?

**Comment by raisedadead** [comment]
When I reload a page (on a throttled connection), there's a obvious delay before the user data is loaded, clicking on the navigation actions (logo, profile, points) throws these weird errors.

This same also happens on the settings page, if I reload and click the show profile (basically routes that have not loaded yet) this is thrown.

Very very rare under normal circumstances, but can be replicated with some stress testing, like clicking impatiently.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue should we use that spinner you implemented while loading challenges? Will this still be an issue on staging?
