### ISSUE TITLE
Help me out 

### ISSUE THREAD

**Issue by Dianarosee** [FreeCodeCamp/FreeCodeCamp#10101]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by dwd2010** [comment]
@Dianarosee, this place is not to get help. you could go  the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Unless, you need to report a bug on here.
GitHub Issues are for reporting bugs on the website only.

**Comment by erictleung** [comment]
@Dianarosee as @dwd2010 has mentioned, thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Please be patient with the Help Room if no one answers you immediately. Sometimes the rooms get pretty busy. But do reach out in those rooms, there are many people in there willing to help. Closing this issue as it isn't a bug on the site. Happy coding!
