### ISSUE TITLE
Inconsistent results for 'smallestCommons([23, 18])'

### ISSUE THREAD

**Issue by thoragio** [FreeCodeCamp/FreeCodeCamp#10118]
Challenge [Smallest Common Multiple](https://www.freecodecamp.com/challenges/smallest-common-multiple#?solution=%22use%20strict%22%0A%0Aconst%20smallestCommons%20%3D%20(arr)%20%3D%3E%20%7B%0A%0A%20%20let%20range%20%3D%20%5B%5D%0A%20%20let%20rangeSize%20%3D%20arr%5B1%5D%20%3E%20arr%5B0%5D%20%3F%20arr%5B1%5D%20-%20arr%5B0%5D%20%2B%201%20%3A%20arr%5B0%5D%20-%20arr%5B1%5D%20%2B%201%0A%20%20let%20rangeStart%20%3D%20arr%5B1%5D%20%3E%20arr%5B0%5D%20%3F%20arr%5B0%5D%20%3A%20arr%5B1%5D%0A%20%20for%20(let%20i%20%3D%200%3B%20i%20%3C%20rangeSize%3B%20i%2B%2B)%20%7B%0A%20%20%20%20range.push(rangeStart)%0A%20%20%20%20rangeStart%2B%2B%0A%20%20%7D%0A%20%20console.log(range)%0A%0A%20%20let%20checkSmallest%20%3D%20range%5Brange.length%20-%201%5D%0A%20%20console.log(checkSmallest)%0A%0A%20%20for%20(let%20j%20%3D%200%3B%20j%20%3C%20range.length%3B%20j%2B%2B)%20%7B%0A%20%20%20%20if%20(checkSmallest%20%25%20range%5Bj%5D%20%3D%3D%200)%20%7B%0A%20%20%20%20%7D%0A%20%20%20%20else%20%7B%0A%20%20%20%20%20%20j%20%3D%20-1%0A%20%20%20%20%20%20checkSmallest%2B%2B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20console.log(checkSmallest)%0A%20%20return%20checkSmallest%0A%7D%0A%0AsmallestCommons(%5B1%2C5%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I've tested my code using both Node 6.1.0 on my local machine and in CodePen and it returns the correct results (check the browser console log):
https://codepen.io/thoragio/pen/LkgKjA

However, when I run this same code against the test in the challenge, the last test ( smallestCommons([23, 18]) ) fails. When I look at the browser console log, I see that my return value is always a different number somewhere in the 4 million range (e.g., 4841427, 4701970, 4950014), but the correct answer is supposed to be 6056820.

My code:
```javascript
"use strict"

const smallestCommons = (arr) => {

  let range = []
  let rangeSize = arr[1] > arr[0] ? arr[1] - arr[0] + 1 : arr[0] - arr[1] + 1
  let rangeStart = arr[1] > arr[0] ? arr[0] : arr[1]
  for (let i = 0; i < rangeSize; i++) {
    range.push(rangeStart)
    rangeStart++
  }
  console.log(range)

  let checkSmallest = range[range.length - 1]
  console.log(checkSmallest)

  for (let j = 0; j < range.length; j++) {
    if (checkSmallest % range[j] == 0) {
    }
    else {
      j = -1
      checkSmallest++
    }
  }
  console.log(checkSmallest)
  return checkSmallest
}

smallestCommons([1,5]);

```

**Comment by erictleung** [comment]
@thoragio running your code gives this console output

```
Error: Potential infinite loop at line 18. To disable loop protection, write: 
// noprotect
as the first line. Beware that if you do have an infinite loop in your code this will crash your browser.
```

so you could add the `// no protect` to see it works.

**Comment by alistermada** [comment]
I just tried the code above with `// no protect`. I also get inconsistent results for `smallestCommons([23, 18])`. However, instead of getting numbers in the 4 millions I get number in the 1 millions like 1902775, 1892104, and 1915324. The other tests are consistently correct. Tested on Chrome.

On the latest Firefox, `smallestCommons([1, 13])` is also giving inconsistent results.

**Comment by BKinahan** [comment]
This code is technically correct in that it outputs the correct values given sufficient time, but it is quite inefficient and inconsistent results in the FCC environment are most likely due to this inefficiency.

For example, incrementing `checkSmallest` by `1` on each step through the loop when it is not divisible by one of the numbers in the range will make the code take about twenty times longer for the input `[23,18]` than incrementing by the larger of the two input numbers. (Because the number we are looking for as the smallest common multiple must be a multiple of `23`, incrementing by `23` rather than by `1` saves a lot of time.)

That simple change allows this code to pass all tests for this challenge. There are other inefficiencies but this is not the place for further discussion of those.

**Comment by thoragio** [comment]
@erictleung @alistermada @BKinahan Thanks for looking into this.

I appreciate that my code is pretty inefficient, but in my early stages of learning JS I am more focused on "getting it to work" than "getting it to work optimally". Given that, I am not sure if what I have observed is really worthy of being deemed a bug to fix in the FCC platform, but it was confusing for me because my code worked fine running with Node locally and on another hosted platform (CodePen).

I will leave it up to you guys whether you want to keep this issue open and address it somehow (perhaps just a mention somewhere in the challenge description that inefficient code might fail some of the tests?) or just close it. Thanks for your time considering it in any case.

And thank you for the great work on FCC. I really appreciate this great learning resource.

**Comment by raisedadead** [comment]
@thoragio thanks a lot for the appreciation, and while I agree that your code is correct and I 100% support the fact that as a beginner you are focused on "getting it to work"! Goodjob!

However, to incorporate a corner case like this, we would have to probably brainstorm and churn up a logic that can handle the inconsistent errors like this. 

Given the priorities I think this may not be taken up given the complexity it involves. Not to forget that every browser behaves differently. 

> address it somehow (perhaps just a mention somewhere in the challenge description that inefficient code might fail some of the tests?) 

Yes, we can mention that some code might break, but then that would have to do it with all challenges.


Leaving it open for other @FreeCodeCamp/issue-moderators to comment. But I think this can be closed as a `wontfix`.

**Comment by raisedadead** [comment]
Closing as this involved a complex approach than necessary.

**Comment by carlotapia** [comment]
Can anyone explain why this code doesn't work?

It fails on `smallestCommons([23, 18])` despite correctly returning 6056820

`function range(arr) {
  let rangeArr = [];
  arr.sort( (a, b) => a - b );
  let first = arr[0];
  let last = arr[1];
  for (let i = first; i <= last; i++) {
    rangeArr.push(i);
  }
  return rangeArr;
}

function checkDivisible(arr) {
  let largest = arr[arr.length-1];
  let divider = 0;
  let acc = 0;
  while (acc !== arr.length) {
    acc = 0;
    divider += largest;
    each(arr, function(element) {
      if (divider % element === 0) {
        acc += 1;
      }
    });
  }
  return divider;
}

function each(arr, func) {
  for (let i = 0; i < arr.length; i++) {
    func(arr[i], i, arr);
  }
}

function smallestCommons(arr) {
  let rangeArr = range(arr);
  return checkDivisible(rangeArr);
}

smallestCommons([23, 18])`

**Comment by RandellDawson** [comment]
@carlotapia This is not the place to ask coding questions related to challenges.  Please use [our forum](https://freecodecamp.org/forum/) for such questions.  Thank you.
