### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by BrendanBarth** [FreeCodeCamp/FreeCodeCamp#10110]
Challenge [Sort Arrays with sort](https://www.freecodecamp.com/challenges/sort-arrays-with-sort#?solution=%0Avar%20array%20%3D%20%5B1%2C%2012%2C%2021%2C%202%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Aarray.sort(function(a%2C%20b)%20%7B%0A%20%20return%20b%20-%20a%3B%0A%7D)%3B%0Aarray.sort()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var array = [1, 12, 21, 2];

// Only change code below this line.

array.sort(function(a, b) {
  return b - a;
});
array.sort();

```

**Comment by 123pips** [comment]
i dont think you are doing anything wrong, if you run this in a browser, it will sort the array in descending order correctly, but fcc doesnt like something, not sure what.

**Comment by jn01258** [comment]
Same here!
