### ISSUE TITLE
Challenges show green tick but test cases show Red crosses

### ISSUE THREAD

**Issue by kpbeng** [FreeCodeCamp/FreeCodeCamp#10129]
Hi ,
I am facing this issue all around. All the challenges i have completed show as green and faded ie completed. But when i go into the code, I see that the code i have written seems to be lost. also test cases which were passed are now red crosses or failed.

Where can i see my completed code. I need to urgently revisit the code for some project i am involved in.

**Comment by erictleung** [comment]
@kpbeng you can revisit your challenge solutions on your FreeCodeCamp profile at `https://www.freecodecamp.com/YOURUSERNAME` where `YOURUSERNAME` if whatever username you have chosen for FreeCodeCamp. I hope this helps.
