### ISSUE TITLE
The answer seems right and returns the perfect output ! Yet the code is non-acceptable on the website

### ISSUE THREAD

**Issue by zoro16** [FreeCodeCamp/FreeCodeCamp#10121]
Challenge [Return Largest Numbers in Arrays](https://www.freecodecamp.com/challenges/return-largest-numbers-in-arrays#?solution=%0Afunction%20largestOfFour(arr)%20%7B%0A%20%20%2F%2F%20You%20can%20do%20this!%0A%20%20var%20max%20%3D%200%3B%0A%20%20var%20maxArr%20%3D%20%5B%5D%3B%0A%20%20for(var%20i%3D0%3B%20i%3Carr.length%3B%20i%2B%2B)%7B%0A%20%20%20%20for(var%20j%3D0%3B%20j%3Carr%5Bi%5D.length%3B%20j%2B%2B)%7B%0A%20%20%20%20%20%20if(arr%5Bi%5D%5Bj%5D%20%3E%20max)%7B%0A%20%20%20%20%20%20%20%20max%20%3D%20arr%5Bi%5D%5Bj%5D%3B%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20maxArr.push(max)%3B%0A%2F%2F%20%20%20%20%20console.log(maxArr)%3B%0A%20%20%20%20%0A%20%20%7D%0A%20%20%20%20console.log(maxArr)%3B%0A%20%20%0A%20%20return%20maxArr%3B%0A%7D%0A%0AlargestOfFour(%5B%5B4%2C%205%2C%201%2C%203%5D%2C%20%5B13%2C%2027%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function largestOfFour(arr) {
  // You can do this!
  var max = 0;
  var maxArr = [];
  for(var i=0; i<arr.length; i++){
    for(var j=0; j<arr[i].length; j++){
      if(arr[i][j] > max){
        max = arr[i][j];        
      }
    }
    maxArr.push(max);
//     console.log(maxArr);
    
  }
    console.log(maxArr);
  
  return maxArr;
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

```

**Comment by roshancs89** [comment]
Max=0 should be initialized after first for loop.

**Comment by zoro16** [comment]
Thanks a lot mate :D
