### ISSUE TITLE
Clarify definition of "even" in Targeting Even Elements in jQuery

### ISSUE THREAD

**Issue by marienhof** [FreeCodeCamp/FreeCodeCamp#10127]
The explanations of what odd and even in jQuery are ok, but they don't make clear sense according with what is asked of a learner to do in this challenge. There's something not clear about this whole thing. It's confusing.

Challenge [Target Even Numbered Elements Using jQuery](https://www.freecodecamp.com/challenges/target-even-numbered-elements-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G34 Safari/601.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
    $("#right-well").children().css("color", "orange");
    $("#left-well").children().css("color", "green");
    $(".target:nth-child(2)").addClass("animated bounce");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by erictleung** [comment]
@marienhof thanks for the feedback. The instructions for what to do are

> Try selecting all the even-numbered elements and giving them the classes of `animated` and `shake`.

Is this instruction unclear in any way? If so, can you let us know how we can reword it or let us know how it is unclear? Thanks!

**Comment by marienhof** [comment]
"You should use the :even function to modify these elements"
But.. Mathematically even is jQuery odd and vice versa, isn't it?

**Comment by erictleung** [comment]
@marienhof ah I see the confusion. The note 

> Note that jQuery is zero-indexed, meaning that, counter-intuitively, `:odd` selects the second element, fourth element, and so on.

is included so that if you run the code using `:odd`, you'll see that the even elements are selected, if you start with a 1-index. So that chuck of text was included to clarify any confusion, if any. But I guess it may have introduced more confusion.

There should be some clarification with the last sentence then so that it could read

> Try selecting all the even-numbered elements and giving them the classes of `animated` and `shake`. **Even-numbered is defined here with a zero-index in mind.**

@FreeCodeCamp/issue-moderators

**Comment by marienhof** [comment]
Totally!
