### ISSUE TITLE
False solution working - js, Chunky Monkey

### ISSUE THREAD

**Issue by nayD93** [FreeCodeCamp/FreeCodeCamp#10122]
Challenge [Chunky Monkey](https://www.freecodecamp.com/challenges/chunky-monkey#?solution=%0Afunction%20chunkArrayInGroups(arr%2C%20size)%20%7B%0A%20%20%2F%2F%20Break%20it%20up.%0A%20%20var%20sizedArr%20%3D%20%5B%5D%3B%0A%20%20var%20partArr%20%3D%20%5B%5D%3B%0A%20%20var%20lengthRest%20%3D%200%3B%0A%20%20%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(i%20%25%20size%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20%20%20partArr%20%3D%20arr.slice(i%2C%20i%20%2B%20size)%3B%0A%20%20%20%20%20%20sizedArr.push(partArr)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20if%20(arr.length%20%25%20size%20!%3D%3D%200)%20%7B%0A%20%20%20%20lengthRest%20%3D%20arr.length%20%25%20size%3B%0A%20%20%20%20partArr%20%3D%20arr.slice(arr.length-lengthRest%2C%20arr.length)%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20sizedArr%3B%0A%7D%0A%0AchunkArrayInGroups(%5B0%2C%201%2C%202%2C%203%2C%204%2C%205%2C%206%5D%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript "Chunky Monkey"

function chunkArrayInGroups(arr, size) {
  // Break it up.
  var sizedArr = [];
  var partArr = [];
  var lengthRest = 0;
  
  for (var i = 0; i < arr.length; i++) {
    if (i % size === 0) {
      partArr = arr.slice(i, i + size);
      sizedArr.push(partArr);
    }
  }
  if (arr.length % size !== 0) {
    lengthRest = arr.length % size;
    partArr = arr.slice(arr.length-lengthRest, arr.length);
  //sizedArr.push(partArr);
  }
  
  return sizedArr;
}

chunkArrayInGroups([0, 1, 2, 3, 4, 5, 6], 3);

```

Hey, this challenge works like shown above.
But i should not. partArr gets push altrough its comented out.
I am fairly new to this, so maybe I did a mistake;

**Comment by BKinahan** [comment]
You have a `for` loop which also pushes to `sizedArr`, and in that loop it is not commented out.

Here is a simpler version of your code which works in exactly the same way. I'll leave it to you to think about why it works:
```js
function chunkArrayInGroups(arr, size) {
  // Break it up.
  var sizedArr = [];
  var partArr;

  for (var i = 0; i < arr.length; i++) {
    if (i % size === 0) {
      partArr = arr.slice(i, i + size);
      sizedArr.push(partArr);
    }
  }
  return sizedArr;
}
```

If you need any help with writing code for the algorithm challenges, remember to visit the [HelpJavaScript chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) to ask about it before deciding if raising an issue is needed.

Happy coding!

**Comment by nayD93** [comment]
Thank you, ran into the same issue again a few minutes ago ..and decided
for the chat. Sry for raising an issue there

Am 07.08.2016 3:17 nachm. schrieb "Brendan Kinahan" <
notifications@github.com>:

**Comment by ogora** [comment]
Here is another false solution that works.  I am getting an error message saying that  i = arr.length is wrong. However this  still passes
` var arr2 = [ ];
  for(var i = 0; i= arr.length; i++) {
    arr2.push(arr.slice(0, size));
    arr = arr.slice(size);
  }
  return arr2;
 `
