### ISSUE TITLE
Do not change the order of the h1 h2 or p in the code.  

### ISSUE THREAD

**Issue by firstcreatedbydesign** [FreeCodeCamp/FreeCodeCamp#10128]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3C!--%3EHello%20World%3C%2F--%3E%0A%3Ch2%3ECatPhotoShop%3C%2Fh2%3E%0A%3C!--%3EHello%20Pagragraph%3C%2F-%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!-->Hello World</-->
<h2>CatPhotoShop</h2>
<!-->Hello Pagragraph</->


```

**Comment by firstcreatedbydesign** [comment]
I cannot figure why that error message won't clear. What am I missing?

**Comment by erictleung** [comment]
@firstcreatedbydesign thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). GitHub issues are only for bugs on the site. 

Hint: 

> Comment out your `h1` element and your `p` element, but leave your `h2` element uncommented.

implies that you don't mess with the HTML elements. Just comment them out.

Happy coding!

**Comment by firstcreatedbydesign** [comment]
I did. No response from anyone 

Sent from Yahoo Mail on Android 
 
  On Sun, Aug 7, 2016 at 11:37 PM, Eric Leung<notifications@github.com> wrote:   
Closed #10128.

**Comment by erictleung** [comment]
@firstcreatedbydesign the rooms sometimes get really busy so you'll have to be patient. If you don't get any response in the future, you can tag me `@erictleung` in Gitter and I can try to help you out. There are many people in the help rooms willing to help, just gotta be persistent. Good luck!

**Comment by firstcreatedbydesign** [comment]
Thank you. I will. I will ask again tonight. Good day. 

Sent from Yahoo Mail on Android 
 
  On Mon, Aug 8, 2016 at 9:06 AM, Eric Leung<notifications@github.com> wrote:   
@firstcreatedbydesign the rooms sometimes get really busy so you'll have to be patient. If you don't get any response in the future, you can tag me @erictleung in Gitter and I can try to help you out. There are many people in the help rooms willing to help, just gotta be persistent. Good luck!

**Comment by firstcreatedbydesign** [comment]
I will thank you so much.

**Comment by ilerio** [comment]
You have to put your comments outside of the original html tags. Don't touch the original code put your comment tags around it.

**Comment by ademolaadebanji** [comment]
kindly tell me how to have try so many things thanks

**Comment by southpawg17** [comment]
It worked for me when I just added the comment tags without changing the original code. Hope it works!

**Comment by MudassirAli619** [comment]
above <p> write <!-->
