### ISSUE TITLE
"After updateRecords(2468, "tracks", "Free"), tracks should have "1999" as the first element." still failing even with output correct.

### ISSUE THREAD

**Issue by AeonBackflash** [FreeCodeCamp/FreeCodeCamp#10132]
Challenge [Record Collection](https://www.freecodecamp.com/challenges/record-collection#?solution=%0A%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%20%222548%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20%22artist%22%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%222468%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%221999%22%2C%0A%20%20%20%20%20%20%22artist%22%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%221245%22%3A%20%7B%0A%20%20%20%20%20%20%22artist%22%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%225439%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20updateRecords(id%2C%20prop%2C%20value)%20%7B%0A%20%20if%20(prop%20!%3D%3D%20%22tracks%22%20%26%26%20value%20!%3D%3D%20%22%22)%20%7B%0A%20%20%20%20%20%20%20%20collection%5Bid%5D%5Bprop%5D%20%3D%20value%3B%0A%20%20%20%20%7D%20else%20if%20(prop%20%3D%3D%20%22tracks%22%20%26%26%20value%20!%3D%3D%20%22%22)%20%7B%0A%20%20%20%20%20%20%20%20if%20(!collection.hasOwnProperty(%22tracks%22))%20%7B%20%2F%2F%20moved%20from%20outside%20loop%0A%20%20%20%20%20%20%20%20%20%20%20%20collection%5Bid%5D%5B%22tracks%22%5D%20%3D%20%5B%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20collection%5Bid%5D%5Bprop%5D.push(value)%3B%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20collection%5Bid%5D%5Bprop%5D.push(value)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%7D%20else%20%7B%20%2F%2F%20removed%20(value%20%3D%3D%3D%20%22%22)%0A%20%20%20%20%20%20%20%20delete%20collection%5Bid%5D%5Bprop%5D%3B%0A%20%20%20%20%7D%0A%20%20%0A%20%20return%20collection%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0AupdateRecords(5439%2C%20%22artist%22%2C%20%22ABBA%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  if (prop !== "tracks" && value !== "") {
        collection[id][prop] = value;
    } else if (prop == "tracks" && value !== "") {
        if (!collection.hasOwnProperty("tracks")) { // moved from outside loop
            collection[id]["tracks"] = [];
            collection[id][prop].push(value);
        } else {
          collection[id][prop].push(value);
        }
        
    } else { // removed (value === "")
        delete collection[id][prop];
    }
  
  return collection;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");


```

**Comment by dhcodes** [comment]
@AeonBackflash there is an error in your code, namely that your nested if statement starting with ` if (!collection.hasOwnProperty("tracks")) {` does not correctly filter out the results. Please consider asking for help in the [Gitter Help chat room](https://gitter.im/FreeCodeCamp/Help).

**Comment by BKinahan** [comment]
As @dhcodes says, you have an error in your code. Please use the help chat as linked above for assistance with writing code when necessary. Issues are for reporting bugs or problems with the challenges or website.

Happy coding!

**Comment by BeetleJuice-TO** [comment]
else if (prop == "tracks" && value !== "") {  // you said in this line my prop= "tracks" then let go inside the if
        if (!collection.hasOwnProperty("tracks")) {  // the you said if tracks does not inside collection but with wrong syntax you should write if(!collection[id].hasOwnProperty("tracks"))
            collection[id]["tracks"] = [];
            collection[id][prop].push(value);


but totally you think wrong somewhere because if your value = null, you have to delete the item inside the object, so your first statement should be if(value = "") {delete collection[id][prop];

**Comment by informmehemant** [comment]
if(!collection.hasOwnProperty(“tracks”))  { // this line has error  
   collection[id][prop]=[]; 
}
instead of this you can write 
if(!collection[id].hasOwnProperty(“tracks”))  { // we missed on which particular id's " tracks" we are updating
   collection[id][prop]=[]; 
}


this works for me :)

**Comment by Xelepam** [comment]
Can someone explain the "!" before collection and its function, ty

**Comment by svmarinez** [comment]
@Xelepam 
! is the logical NOT operator.
In this context, it would be the same as saying _if the ID of the collection does **not** have the property "tracks"_ in human speak.
