### ISSUE TITLE
Confusing instruction at first html challenge

### ISSUE THREAD

**Issue by skelic2** [FreeCodeCamp/FreeCodeCamp#10137]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello World</h1>

```

# The confusing instruction
> To pass the test on this challenge, change your h1 element's text to say "Hello World" instead of "Hello". Then click the "Run tests" button.

**The Problem**
Change your h1 element text to say Hello World instead of Hello? ***What***, I think it should be ***change your h1 element text to say Hello instead of Hello World.*** It's like reversed and confusing.

**Comment by erictleung** [comment]
@skelic2 thanks for the issue. The default code in the editor when you start the challenge is actually `<h1>Hello</h1>`. If you click on the Reset button, you should see this. Thus, the challenge instructions will make sense. Let us know if this clears up your confusion.

**Comment by skelic2** [comment]
Oh sorry. My bad. I viewed my solution instead of the fresh challenge.
