### ISSUE TITLE
replacing "href" with "#"

### ISSUE THREAD

**Issue by phoenixwarrior** [FreeCodeCamp/FreeCodeCamp#10135]
Challenge [Make Dead Links using the Hash Symbol](https://www.freecodecamp.com/challenges/make-dead-links-using-the-hash-symbol#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20%23%3D%22http%3A%2F%2Fwww.freecatphotoapp.com%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a #="http://www.freecatphotoapp.com">cat photos</a>.</p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

I replaced "href" with "#" as noted in the instructions for the line that reads:
"<p>Click here for <a #="http://www.freecatphotoapp.com">cat photos</a>.</p>"
and it does not register as me having done so.

**Comment by erictleung** [comment]
@phoenixwarrior thanks for the issue but GitHub issues are not for coding help. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). 

Here's a hint:

> **Replace the value of your `a`** element's `href` attribute with a `#`, also known as a hash symbol, to turn it into a dead link.

Happy coding!

**Comment by phoenixwarrior** [comment]
Yes someone in the help room was able to help after I sent this.

However, the instructions Spefically say to replace href. Obviously this is
incorrect and it is the link that is to be replaced. Perhaps that should be
corrected? Or at least better explained?
And since the issue transcends a mere coding help issue, but rather is an
issue with the lesson in and of itself, where else should it be noted to?

**Comment by erictleung** [comment]
@phoenixwarrior thanks for the feedback, but again I feel that the last sentence of the instructions are sufficient enough:

> Replace the value of your `a` element's `href` attribute with a `#`, also known as a hash symbol, to turn it into a dead link.

In addition, if you look at the challenge test, this should also further clarify that you need to replace the link and not the text `href` itself.

> Your `a` element should be a dead link with a `href` attribute set to "#".

If this is still not clear enough, feel free to reply back with a clearer modification of these instructions. We welcome feedback and suggestions that will improve users' experiences with Free Code Camp.

**Comment by phoenixwarrior** [comment]
@erictleung Yea for me it was the last sentence that I found to be the confusing and misleading part.
"Replace the value of your a element's href attribute with a #, also known as a hash symbol, to turn it into a dead link."
Here is how,as someone who is new to code, this sentence reads to me.
within my "a" element line of code, there is a "href attribute" And I need to replace that with a hash(#).
My first thought is not to replace the quoted  link url, but rather the letters href.(of the two which has the attributes of being href?) And secondly, the instruction says I am causing the link url to be dead,not delete the link all together. And so like commenting something out, one adds --><--around the code, so the code stays if one wish to un-comment it, And so I thought it would be so here to,replace href with # and that will cause the link to be dead, and if later I want to make it active again,I would replace # with href. Obviously deleting the link url, I cant do that unless I first find the url again. As a new coder I wouldn't have thought to do or risk that happening.

I think this is easy enough to clarify within the instructions though, it could read:
"A href attribute is the quoted link url itself within the "a" element. Replace the value of your a element's href attribute with a #, also known as a hash symbol, to turn it into a dead link."

Or, "Replace the value of your a element's [quoted link url] with a #, also known as a hash symbol, to turn it into a dead link. make sure not to replace the "".

**Comment by erictleung** [comment]
@phoenixwarrior thanks for your detailed feedback. I like your first suggestion.

> The `href` attribute is the quoted URL link within the `a` element. Replace the link value of your `a` element's `href` attribute with a `#`, also known as a hash symbol, to turn it into a dead link.

**Comment by Manish-Giri** [comment]
@erictleung I can give this a shot.

**Comment by oalhait** [comment]
@erictleung are you just looking for the sentence 

> "Replace the value of your a element's href attribute with a #, also known as a hash symbol, to turn it into a dead link."

to be replaced with 

> The href attribute is the quoted URL link within the a element. Replace the link value of your a element's href attribute with a #, also known as a hash symbol, to turn it into a dead link.

?

**Comment by erictleung** [comment]
@oalhait yes.

**Comment by Priya2895** [comment]
hi,
i replaced the link with # still it is not running..!!! 
what should i do?

**Comment by texas2010** [comment]
@Priya2895 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by LooseYounit** [comment]
I'm having the same problem and smarty pants answers don't cut it

**Comment by LooseYounit** [comment]
<p>Click here for <a href="x"> cat photos</a>.</p>

this did nothing

**Comment by dshokoofi** [comment]
they mean get rid of the "http://...." part and replace it with "#"

**Comment by SageGram** [comment]
This is what I Did and it was correct. <p>Click here for <a href="#">cat photos</a>.</p>

**Comment by SageGram** [comment]
![screenshot from 2016-12-14 20-24-47](https://cloud.githubusercontent.com/assets/8295123/21211804/80a08db6-c23b-11e6-9d3d-5fea5b6787c2.png)

**Comment by edyanez23** [comment]
i did that and doesn't do anything.

**Comment by sashamarie** [comment]
try refreshing the page

**Comment by mochalemon** [comment]
I encountered the same issue and was able to proceed after I click refresh.  Thanks.

**Comment by cptmacaroni** [comment]
Make sure you all are adding the hashtag to the appropriate string. You will have the first link at the top of the HTML document and an <p> at the bottom of the page. Change that href to equal the hashtag.

**Comment by abc173** [comment]
same here for this challenge, 
1.refresh the page
2.using delete , delete the link between " "
3.put # between " "
and my challenge is SOLVED.

**Comment by ogora** [comment]
Had the same problem. Sometimes the instrcutions on FCC are  quite vague. I have solved many issues but mainly by just gambling..lots of trial and error. W3 schools does a better job with instructions

**Comment by Petrovik1** [comment]
Poorly written and as we can see the web application has bugs that need to be fixed :)

**Comment by honourzxc** [comment]
non e of you answered the question, can someone do this for me, that would be awesome thank you

**Comment by ogora** [comment]
abc173 above answered the question about chnaging the href... unless you had another question. I did that and It worked for me.

**Comment by saegeullee** [comment]
I think more detailed explanation is needed here.

**Comment by gwapoJay** [comment]
Thank you "abc173" from above.........
It's works for me too....

**Comment by alicebalayan** [comment]
Like someone previously mentioned before, it needs another explanation..But oh, well haha

**Comment by sabthegreat** [comment]
<p>Click here for <a href="#">cat photos</a>.</p>

**Comment by Akbar090** [comment]
Code <a href=#> </a> for the below coding challege
Your a element should be a dead link with a href

**Comment by aaronandriod** [comment]
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
