### ISSUE TITLE
Test just accepts terminated a tag even if wrong area of code

### ISSUE THREAD

**Issue by digitaldak** [FreeCodeCamp/FreeCodeCamp#1013]
Please describe how to reproduce it, and include links to screen shots if possible.
Challenge http://www.freecodecamp.org/challenges/waypoint-turn-an-image-into-a-link has an issue. 

See image, the test is doing a global search for </a> so it will find it on the wrong line or anywhere in the source for that matter.

![waypoint-turn-an-image-into-a-link](https://cloud.githubusercontent.com/assets/3256176/8266222/e8fa55ca-16d6-11e5-9ae9-fd269c717da2.png)

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
