### ISSUE TITLE
Correct answer but still can't pass

### ISSUE THREAD

**Issue by A8236** [FreeCodeCamp/FreeCodeCamp#10139]
Challenge [Manipulating Complex Objects](https://www.freecodecamp.com/challenges/manipulating-complex-objects#?solution=%0Avar%20myMusic%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Billy%20Joel%22%2C%0A%20%20%20%20%22title%22%3A%20%22Piano%20Man%22%2C%0A%20%20%20%20%22release_year%22%3A%201973%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CS%22%2C%20%0A%20%20%20%20%20%20%228T%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%0A%20%20%20%20%22gold%22%3A%20true%0A%20%20%7D%2C%0A%20%20%20%7B%0A%20%20%20%20%20%20%20%22artist%22%3A%20%22Devo%22%2C%20%0A%20%20%20%20%20%20%20%22title%22%3A%20%22We%20are%20Devo%22%2C%20%0A%20%20%20%20%20%20%20%22release_year%22%3A%201984%2C%20%0A%20%20%20%20%20%20%20%22formats%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%22CD%22%2C%20%0A%20%20%20%20%20%20%20%20%20%20%22Cassette%22%2C%20%0A%20%20%20%20%20%20%20%20%20%20%22LP%22%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%5D%3B%2F%2F%20Add%20record%20here%0A%5D%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  },
   {
       "artist": "The 1975", 
       "title": "Robbers", 
       "release_year": 1975, 
       "formats": [
          "CD", 
          "Cassette", 
          "LP"
        ]
      }

    ];// Add record here
];


```

**Comment by BKinahan** [comment]
Unfortunately your code is not correct; you have a syntax error (an extra `];` at the end). Notice the red circle with an X inside next to the line number for line 25, which signifies this error.

Remember to use the [Help chat](https://gitter.im/FreeCodeCamp/Help) when you're stuck writing code, before raising an issue.

Happy coding!
