### ISSUE TITLE
Introducing Else Statements

### ISSUE THREAD

**Issue by m4sterbunny** [FreeCodeCamp/FreeCodeCamp#10148]
The instruction to " // Only change code below this line" must be contravened to pass the test.
To pass you need to re-name the function (and call to that function)

function testElse(val) {
  var result = "";
 

Challenge [Introducing Else Statements](https://www.freecodecamp.com/challenges/introducing-else-statements#?solution=function%20testElse(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20if%20(val%20%3E%205)%20%7B%0A%20%20%20%20result%20%3D%20%22Bigger%20than%205%22%3B%0A%20%20%7D%0A%20%20%0A%20%20else%20%7B%0A%20%20%20%20result%20%3D%20%225%20or%20Smaller%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestElse(4)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function testElse(val) {
  var result = "";
  // Only change code below this line
  
  if (val > 5) {
    result = "Bigger than 5";
  }
  
  else {
    result = "5 or Smaller";
  }
  
  // Only change code above this line
  return result;
}

// Change this value to test
testElse(4);


```

**Comment by raisedadead** [comment]
Can you clarify further?

> The instruction to " // Only change code below this line" must be contravened to pass the test.
To pass you need to re-name the function (and call to that function)

I can see that you did not rename the function? Did you want to? If so why at all?
P.S : Please reach out to [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript), if this is a coding assistance query.

**Comment by raisedadead** [comment]
Feel free to continue the discussion. Will re-open incase this is a bug.

**Comment by m4sterbunny** [comment]
Howdy- You are seeing the code I used to pass the test. Look rather at the start code provided in the challenge where the function has a different name (function myTest) - there is no reason to change the function name (it is not part of the instructions- it is however, part of the conditions for passing the challenge..

To pass you need to name/call the function - testElse (thereby forcing you to change code above the line what says do not change code above this line).

Did I make sense yet? I passed the challenge using this fiddle.

Cheers
H

**Comment by raisedadead** [comment]
Hi H!,

Okay now it's more clear, the name of the function was recently changes while updating the challenges a couple months ago.

Indeed earlier it was `myTest` and now in it has been updated to `testElse`. 

_Now coming to the point why did you see the older name `myTest`, instead of `testElse` as in the instructions and tests?_

This is possible in case you completed the challenge prior to us rolling out this upgrade. In that scenario it would have been stored locally on your computer, and as well on your profile as a solution. Also it can happen if you visit someone else's solution who solved it before we rolled out the change. 

With the above, the solutions would display old name `myTest`. Unfortunately there no workaround for this.

Hence it's best you can simply reset the code using the reset button which will remove your solution and add the correct name. Nevertheless, this doesn't affect your progress at all because we have captured your submission, which can be seen on your profile.

Hope this helps!
Happy coding.

**Comment by m4sterbunny** [comment]
Ah thanks- that makes sense.Cheers

On Wed, Aug 10, 2016 at 1:21 PM, Mrugesh Mohapatra <notifications@github.com

**Comment by frogshelp** [comment]
should of changed the 4 to the at the bottom as it does state change that value  as i have done so and i did same method you used in your code and all mine passed  so when i came looking for ideas on what i did wrong and why when i change the code in anyway with the else if statements supposed to me combined i notice u took out the if  and made it else but u never changed ur value at the bottom where it says testelse(4);   which  that should of gotten changed  and i do see an issue with it as it says to combine your else if statments into one  when actaully  as u see  just like in your code they are not combined into one the instructions and test need to be way more clearer about it.

**Comment by frogshelp** [comment]
my code passed all  
function testElse(val) {
  var result = "";
  // Only change code below this line
  
  if (val > 5) {
    result = "Bigger than 5";
  }
  
  else {
    result = "5 or Smaller";
  }
  
  // Only change code above this line
  return result;
}

// Change this value to test
testElse(7);


instructions :  
Combine the if statements into a single if/else statement.
so like i just explained  as u see in my passing code  we never actaully put the if/else statment combined into a single statement cause to me when explained i was taking it and i sure others did to that when u say combine into a single statment  ur thinking a code like this for example 

if (val >5 else val <5) {
}

not how u see it in our code split apart so for newbies whom truely dont understand the pc lingo but wanting to code and learn it  this would be frusterating just like i have noticed in many of the tests
