### ISSUE TITLE
Slack invite link not working

### ISSUE THREAD

**Issue by andreagoulet** [FreeCodeCamp/freecodecamp#1014]
Challenge http://www.freecodecamp.com/challenges/waypoint-join-our-chat-room has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

In the section called Waypoint: Join Our Chatroom on the 3rd item, there is a link to join the chatroom (http://www.freecodecamp.com/api/slack)

When I click, a box appears at the top confirming an email will be sent to my account. It's been over 20 minutes and the email has not arrived. I checked the spam folder and it wasn't there either. 

I'm on an iPhone 6 running iOS 8.3 using Chrome.

**Comment by BerkeleyTrue** [comment]
This is sent to the email listed in your account. This is usually populated by oauth. It may be sending your email to another account. Can you double check their and let me know if it hasn't shown up.

**Comment by BerkeleyTrue** [comment]
Looks like we are having issues with slack itself. Thanks for reporting. We will use this issue when we make progress on this.

**Comment by andreagoulet** [comment]
Sure thing. Was just about to let you know I checked all other email
accounts (including spam) and did not see an email.

Thanks for the update! :)

**Comment by BerkeleyTrue** [comment]
@andreagoulet Thanks for your patience. Definitely seems to be an issue on the Slack side of things. Still investigating.

**Comment by BerkeleyTrue** [comment]
We have found the issue and are looking for ways to resolve it. Thank you all for you patience.

**Comment by BerkeleyTrue** [comment]
We have moved away from Slack due to an undocumented hard limit on numbers of users. We are now on Gitter. 

Please see our [blog post](http://blog.freecodecamp.com/2015/06/so-yeah-we-tried-slack-and-we-deeply-regretted-it.html) on the subject.

We deeply apologies for the inconvenience and hope y'all have a great experience on Gitter!

Best,

-BerkeleyTrue

**Comment by BarryDeCicco** [comment]
As of March, 2016, I'm still having problems getting things through to my Yahoo! mail.  I've checked my spam, and the message is simply not showing up.  It works fine on my iCloud account.

This is an ongoing bug.

**Comment by BerkeleyTrue** [comment]
> We have moved away from Slack due to an undocumented hard limit on numbers of users. We are now on Gitter.
