### ISSUE TITLE
 Return a Value from a Function with Return

### ISSUE THREAD

**Issue by chandujstchandu** [FreeCodeCamp/FreeCodeCamp#10155]
Challenge [Return a Value from a Function with Return](https://www.freecodecamp.com/challenges/return-a-value-from-a-function-with-return#?solution=%0A%2F%2F%20Example%0Afunction%20minusSeven(num)%20%7B%0A%20%20return%20num%20-%207%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20timesFive(num)%20%7B%0A%20%20return%20num%20*%205%3B%0A%20%20%0A%7D%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function minusSeven(num) {
  return num - 7;
}

// Only change code below this line
function timesFive(num) {
  return num * 5;
  
}


```

**Comment by erictleung** [comment]
@chandujstchandu thanks for the issue but can you elaborate on what your issue is, if any? Your code is correct.

**Comment by pavisri** [comment]
+1

**Comment by pavisri** [comment]
The issue is console always shows the result as 25 no matter what number is changed as argument. Even timesFive(2) shows the result as 25.

**Comment by erictleung** [comment]
@pavisri please that issue has been brought up already in #9583. Please continue the conversation over there.

**Comment by fotonist** [comment]
+1
