### ISSUE TITLE
Animatedbounce Button Issue

### ISSUE THREAD

**Issue by Tayloror510** [FreeCodeCamp/FreeCodeCamp#10150]
Hi, I do not understand what I am doing wrong exactly. I am supposed to add animatedbounce inside the ready document and I think I did it right but it doesn't let me move on to the next challenge. Did I make an error somewhere? Thank you for the help. 

```
<script>
  $(document).ready(function() {
   $("button").addClass("animatedbounce");
  });
</script>
```

**Comment by Tayloror510** [comment]
<script>
  $(document).ready(function() {
   $("button").addClass("animatedbounce");
  });
</script>

**Comment by erictleung** [comment]
@Tayloror510 thanks for the issue but GitHub issues are for bug reports, not coding help. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). 

Hint on your issue: check the class name you're trying to add. Is it all one word or separate? Happy coding!

**Comment by pilarmireles22** [comment]
this is the solution <script>
  $(document).ready(function(){
 $("button").addClass("animated bounce");
    });
</script>
give space in the name of the class for that pass

**Comment by mohamedwahshey** [comment]
This is not a bug, you just have to write **.addClass** not **.addclass**

with a CAPITAL C, and it'll all work fine, that's why when you copy it it works.

It's a real troll i know but this is how it works :D 

like **.appendTo** not **.appendto** lol

You welcome :D
