### ISSUE TITLE
I can't continue

### ISSUE THREAD

**Issue by cetaphil** [FreeCodeCamp/FreeCodeCamp#10151]
#### Challenge Name

<a href="Use Bracket Notation to Find the NthtoLast Character in a String"> Use Bracket Notation to Find the NthtoLast Character in a String </a>

#### Issue Description

The screen doesn't return any kind of error message
Am I doing something wrong or is a issue on the website? 

#### Browser Information

Tried in Opera and Chrome.  

* Browser Name, Version:  Opera - 39.0.2256.48
* Operating System:  Windows 7 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
var secondToLastLetterOfLastName = lastName[lastName.lenght - 2];

```

**Comment by raisedadead** [comment]
Have you reached out to the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript)? Closing, but feel free to continue the discussion.
