### ISSUE TITLE
Change Text Inside an Element Using jQuery

### ISSUE THREAD

**Issue by dconner09** [FreeCodeCamp/FreeCodeCamp#10152]
I put the the right tags <em></em> but the system wont take syntax.

#### Challenge Name
Change Text Inside an Element Using jQuery

#### Issue Description
Emphasize the text in your target4 button by adding HTML tags.

#### Browser Information
.

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");

    $("#target4").html("<em>target4</em>");
    
  });
</script>

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

**Comment by dconner09** [comment]
HAHAHA what a silly mistake. man I need to take a break I been working for hours trying to finish these challenges.

**Comment by dwd2010** [comment]
@dconner09, no problem. you could ask for help at [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!

**Comment by Ojuolape** [comment]
The only thing you missed here is the #

**Comment by GokulManickam** [comment]
not working!!!!!!!!

**Comment by GokulManickam** [comment]
they have askd not to change the text of the button....

I hve included this code which solved but one error
[Emphasize the text in your target4 button by adding HTML tags.]
check my code.......................

 $(document).ready(function() {
    $("#target1").css("color", "red");
        $("#target4").html("<em>#target4</em>");
    $("#target4").text("#target4");
  });

**Comment by texas2010** [comment]
@GokulManickam 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.
or use forum. https://forum.freecodecamp.org/

These GitHub Issues are for reporting bugs on the freeCodeCamp website only.

Happy Coding.
