### ISSUE TITLE
Can't find solution and Github won't let me ask.

### ISSUE THREAD

**Issue by 15derekc** [FreeCodeCamp/FreeCodeCamp#10156]
Been on code camp for two months now,  been able to find most solutions either in my textbook or on google to help me through.

I figure my code is the right solution because the local scope is practically all written out all I had to write is var myOutfit.

Still says it's returning as T-shirt.

Tried asking chat, said I wasn't a GitHub user, asked me to log in with Twitter to use chat. Still won't let me use chat, and I can't find an explanation other than the wiki forums and all those are just the same explanations that the instructions in code camp give.

It's driving me up a wall.

Challenge [Global vs Local Scope in Functions](https://www.freecodecamp.com/challenges/global-vs-local-scope-in-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var outerWear = "T-Shirt";

function myOutfit() {
 var myOutfit = "sweater"; // Only change code below this line
  
  
  
  // Only change code above this line
  return outerWear;
}

myOutfit();

```

**Comment by dwd2010** [comment]
@15derekc, On Gitter site, you need to log off then log in with github account.

Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding!
