### ISSUE TITLE
i THINK IT SOME ISSUE IN CONSOLE

### ISSUE THREAD

**Issue by saikiranyadav1** [FreeCodeCamp/FreeCodeCamp#10164]
#
https://www.freecodecamp.com/challenges/concatenating-strings-with-the-plus-equals-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%3B%0AourStr%20%2B%3D%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%3D%22This%20is%20the%20first%20sentence.%22%3B%0AmyStr%20%2B%3D%20%22This%20is%20the%20second%20sentence.%22%3B%0A%0A%0A

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
```

**Comment by dhcodes** [comment]
@saikiranyadav1 there's an error in your code. Please consider asking in the [Help chat room](https://gitter.im/FreeCodeCamp/Help) to confirm it's an issue before posting it here. Thanks!

**Comment by raisedadead** [comment]
@saikiranyadav1 Thanks for reporting, but GitHub issues are for bugs in website only. Please connect with the chat room. 

You are very close with your code, almost there!

Happy coding!
