### ISSUE TITLE
problem with this tast

### ISSUE THREAD

**Issue by mwass** [FreeCodeCamp/FreeCodeCamp#10160]
Challenge [Storing Values with the Assignment Operator](https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator#?solution=%0A%2F%2F%20Setup%0Avar%20a%3B%0Avar%20b%20%3D%202%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20b%3D%207%3B%0Avar%20a%20%3D%20b%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var a;
var b = 2;

// Only change code below this line
var b= 7;
var a = b;

```

**Comment by Greenheart** [comment]
@mwass Hope you solved it! :blush:

For the next time: Please ask someone in the [chat rooms](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Official-Free-Code-Camp-Chat-Rooms) to verify that it's a problem with the challenge itself and not with your code before you open an issue.

Happy coding!
