### ISSUE TITLE
MDN and External tip links not displaying

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/freeCodeCamp#10163]
The MDN links and other help links do not show up on the beta site.
#### Screenshot

Regular site:
![](http://i.imgur.com/2s37LQS.png)

Beta site:
![](http://i.imgur.com/2qOF4kc.png)

**Comment by BerkeleyTrue** [comment]
@dhcodes Thanks for catching this. You don't have to use the issue template if it doesn't fit the issue, though.

**Comment by dhcodes** [comment]
I'll take a stab at this assuming we still plan to have MDN links on the site.

**Comment by systimotic** [comment]
@dhcodes Did you make any progress on this?

**Comment by raisedadead** [comment]
Refer : https://github.com/FreeCodeCamp/FreeCodeCamp/issues/12067#issuecomment-269818773

Opening up to the community.

**Comment by dhcodes** [comment]
I'd like to raise a few questions about this. Having looked at the hint structure, I think we should make some changes. 

1. The hint currently accepts only plain-text whereas most of the MDN resources are links.
2. The hint generates a toast to which we could add an action link, but I wonder if using a [dropdown on the hint button](http://getbootstrap.com/components/#btn-dropdowns) might not be a better approach.
3. Alternatively, if we could limit the number of hints on each exercise to 1 hint, we could do away with the toast and have a one-click hint button to open the resource in a new tab.

Thought on any of this?

**Comment by systimotic** [comment]
@dhcodes Good suggestions 👍 I'm not really sure what the hints are supposed to be like. I believe the idea is that they should be like the hints on the forum. Should we close this in favour of https://github.com/freeCodeCamp/freeCodeCamp/issues/13460?

**Comment by dhcodes** [comment]
Whoa. Hadn't seen that issue. Thanks @systimotic. Closing this is fine as long as we reference the MDN links needing to be added to staging in that other issue. 👍

**Comment by dhcodes** [comment]
Closing in favor of #13460
