### ISSUE TITLE
Code Editor problem

### ISSUE THREAD

**Issue by ElvisMac** [FreeCodeCamp/FreeCodeCamp#10167]
There seems to be a problem with the FCC code editor in chrome where the cursor position on a new challenge appears to be in the right place, but when I start to type it appears 2 lines below where it should be.  I've had the problem when the editor height becomes scroll-able on every exercise that pushes the height to start scrolling.

**Comment by oalhait** [comment]
Could we get your computer's information? Windows/Mac,

**Comment by ElvisMac** [comment]
Will a DXDIAG report suffice?

**Comment by ElvisMac** [comment]
Please forgive the potato formatting...
------------------
System Information
------------------
      Time of this report: 8/11/2016, 20:37:18
             Machine name: DESKTOP-V2UV8K7
               Machine Id: {FD36B6C9-F1A2-4396-97F9-DBC8A7BCDF0C}
         Operating System: Windows 10 Pro 64-bit (10.0, Build 14393) (14393.rs1_release.160715-1616)
                 Language: English (Regional Setting: English)
      System Manufacturer: To be filled by O.E.M.
             System Model: To be filled by O.E.M.
                     BIOS: BIOS Date: 04/07/14 17:59:34 Ver: 04.06.05
                Processor: AMD FX(tm)-8320 Eight-Core Processor            (8 CPUs), ~4.0GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16298MB RAM
                Page File: 6237MB used, 13004MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: Using System DPI
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.14393.0000 64bit Unicode

**Comment by dhcodes** [comment]
@ElvisMac This is a known issue that is difficult to fix because the editor is a third-party repo that is maintained by only one person (to my knowledge). Please read the comments here for possible ways to fix it: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7847 

I know it is annoying.

**Comment by ElvisMac** [comment]
Thanks for the help :)

**Comment by ctabary** [comment]
I'm seeing this is Chrome 53.0.2785.113 on Win 7 Enterprise.

Forum thread here: http://forum.freecodecamp.com/t/fcc-editor-issues/36754/4

**Comment by dhcodes** [comment]
@ctabary the original thread to read the development on this is: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7847

**Comment by ctabary** [comment]
Pardon me, and thanks!
