### ISSUE TITLE
CLear it

### ISSUE THREAD

**Issue by yeruvavijay** [FreeCodeCamp/FreeCodeCamp#10162]
Challenge [Accessing Nested Objects](https://www.freecodecamp.com/challenges/accessing-nested-objects#?solution=%0A%2F%2F%20Setup%0Avar%20myStorage%20%3D%20%7B%0A%20%20%22car%22%3A%20%7B%0A%20%20%20%20%22inside%22%3A%20%7B%0A%20%20%20%20%20%20%22glove_box%22%3A%20%22maps%22%2C%0A%20%20%20%20%20%20%22passenger%20seat%22%3A%20%22crumbs%22%0A%20%20%20%20%20%7D%2C%0A%20%20%20%20%22outside%22%3A%20%7B%0A%20%20%20%20%20%20%22trunk%22%3A%20%22jack%22%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20gloveBoxContents%20%3D%20myStorage.car%5B%22inside%22%5D.glove_box%3B%20%2F%2F%20Change%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStorage = {
  "car": {
    "inside": {
      "glove_box": "maps",
      "passenger seat": "crumbs"
     },
    "outside": {
      "trunk": "jack"
    }
  }
};

// Only change code below this line

var gloveBoxContents = myStorage.car["inside"].glove_box; // Change this line


```

**Comment by raisedadead** [comment]
Thanks for reporting, but GitHub issues are for bugs in website only. Please check below for help. [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript).
