### ISSUE TITLE
Test accepts undefined input type that's not even closed

### ISSUE THREAD

**Issue by digitaldak** [FreeCodeCamp/FreeCodeCamp#1016]
Challenge http://www.freecodecamp.org/challenges/waypoint-create-a-text-field has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Test literally accepts "<input" and passes without anything else. Test is checking for a that there is an input field, erm, sort of I guess? 

![waypoint-create-a-text-field](https://cloud.githubusercontent.com/assets/3256176/8266263/93c38ab0-16d9-11e5-901f-b13149690f07.png)

**Comment by BerkeleyTrue** [comment]
This is fixed now.

Happy Coding!
