### ISSUE TITLE
Tests pass with incorrect html layout

### ISSUE THREAD

**Issue by digitaldak** [FreeCodeCamp/FreeCodeCamp#1017]
Challenge http://www.freecodecamp.org/challenges/waypoint-create-a-set-of-radio-buttons has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The following will pass the tests:
```
  <label>
    <input type="radio" name="indoor-outdoor">indoor
  <input type="radio" name="indoor-outdoor">outdoor
    <label> </label></label> 
```
I think the test on this one need to be redone somehow differently perhaps?
![waypoint-create-a-set-of-radio-buttons](https://cloud.githubusercontent.com/assets/3256176/8266306/f5a47ade-16dc-11e5-9beb-47148cb388c9.png)

**Comment by digitaldak** [comment]
Found this assert on another page (issue #1018 if you want to look what page it is) that works better for the label issue mentioned: 
"assert($('label:has(input[type=\"checkbox\"])').length > 2, 'Each of your three checkbox elements should be wrapped in its own <code>label</code> element.')",

**Comment by benschenker** [comment]
Hey @digitaldak thanks for posting this.

Your code above wasn't formatted correctly so I edited it to use [Code Formatting](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/code-formatting).

I've replicated this.

**Comment by ScottRMcleod** [comment]
Update to this Challenge 
<label>
  <label> <input type="radio" name="indoor-outdoor"/></label>indoor
    <label><input type="radio" name="indoor-outdoor"></label>outdoor
  </label>
