### ISSUE TITLE
TypeError: Cannot set property 'wheels' of undefined

### ISSUE THREAD

**Issue by hyanying** [FreeCodeCamp/FreeCodeCamp#10177]
#### Challenge Name

Make Unique Objects by Passing Parameters to our Constructor
https://www.freecodecamp.com/challenges/make-unique-objects-by-passing-parameters-to-our-constructor

#### Issue Description

Test results shows the error ​"TypeError: Cannot set property 'wheels' of undefined". I checked on the internet and the code solution I entered appears to be correct. Not sure how to get around this error.

#### Browser Information

* Browser Name, Version: Chrome, 52.0.2743.116 m
* Operating System:  Windows
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code

var Car = function(wheels, seats, engines) {
  this.wheels = wheels;
  this.seats = seats;
  this.engines = engines;
};

//Try it out here
var myCar = Car(4,4,2);

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/4251682/17617511/28557850-60ad-11e6-8473-ee11255716c5.png)

**Comment by Locheed** [comment]
Have you asked help from Gitter help channel? Your code is just wrong and missing something from constructor call.

**Comment by hyanying** [comment]
I found the problem with my code! Thank you and my apologies for the false alarm!
