### ISSUE TITLE
Reword Sentence in Smallest Common Multiple

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#10187]
#### Challenge Name

https://www.freecodecamp.com/challenges/smallest-common-multiple

#### Issue Description

The third paragraph in the Smallest Common Multiple challenge needs to be rewritten for ease of reading. 

> e.g. for 1 and 3 - find the smallest common multiple of both 1 and 3 that is evenly divisible by all numbers between 1 and 3.

The `e.g.` abbreviation seems unnecessary and may be confusing for people unfamiliar with it.

#### To Contributors

Change [this sentence](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/e610f64ff93c525b646648ae7b536e413e7710d7/seed/challenges/01-front-end-development-certification/intermediate-bonfires.json#L805) to something like this.

> For example, for 1 and 3, you'll need to find the smallest common multiple of both 1 and 3 that is also evenly divisible by all numbers _between_ 1 and 3. The answer here would be 6.

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors](https://goo.gl/XNSD0U) chat room if you have any questions about contributing. We're there to assist.

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/2754821/17642010/997aacec-60eb-11e6-8922-15f2d349469b.png)

**Comment by Pat-Ayres** [comment]
Hello @erictleung I would like to submit a pull request for this issue.
