### ISSUE TITLE
Update Wiki link in Pig Latin to ES

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#10185]
#### Challenge Name

https://www.freecodecamp.com/challenges/pig-latin

#### Issue Description

The Wiki link to Pig Latin for the Spanish translation is directed towards the English version of the Wiki. It should instead point to the Spanish version.

#### To Fix

Change [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/intermediate-bonfires.json#L353) from 

```diff
- "<a href=\"http://en.wikipedia.org/wiki/Pig_Latin\" target=\"_blank\">Pig Latin</a> toma la...
+ "<a href=\"http://es.wikipedia.org/wiki/Pig_Latin\" target=\"_blank\">Pig Latin</a> toma la
```

#### To Contributors

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

This issue is labeled `first-timers-only` so only those who have never contributed to the FreeCodeCamp main repository (this one) may fix this issue. Thanks!

**Comment by Jonib3k** [comment]
Hello @erictleung, I can help.

**Comment by erictleung** [comment]
@Jonib3k go for it! Please consult the Contributing document and Contributors Help room if you have any questions.

**Comment by Jonib3k** [comment]
@erictleung  thanks I'm working on it.
