### ISSUE TITLE
Tests pass with name attribute only on one checkbox & wording change suggestion

### ISSUE THREAD

**Issue by digitaldak** [FreeCodeCamp/FreeCodeCamp#1018]
Challenge http://www.freecodecamp.org/challenges/waypoint-create-a-set-of-checkboxes has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

So this one could be more fun, maybe a count of all elements with the name would be a better check? Or all checkbox elements with the name set would be even better if you can do it.

Also, there is a wording suggestion, currently it says "checkboxes buttons" and it should read "checkbox buttons", otherwise it's really to read as it currently stands.

![waypoint-create-a-set-of-checkboxes](https://cloud.githubusercontent.com/assets/3256176/8266332/345ea7c6-16de-11e5-93f9-dbd57bb7252b.png)

**Comment by benschenker** [comment]
Hey @digitaldak, sorry it took so long to get to this!

It looks like the wording issues `checkboxes buttons` is still there, any beginners want to try an easy Pull Request?
