### ISSUE TITLE
i can not passe a test

### ISSUE THREAD

**Issue by 44552** [FreeCodeCamp/FreeCodeCamp#10192]
Challenge [Understanding Case Sensitivity in Variables](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables#?solution=%0A%2F%2F%20Declarations%0Avar%20cameLCase%3B%0Avar%20cameLCase%3B%0Avar%20cameLCase%3B%0A%0A%2F%2F%20Assignments%0AcamelCase%20%3D%2010%3B%0AcamelCase%20%3D%20%22A%20String%22%3B%0AcamelCase%20%3D%209000%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Declarations
var camelCase;
var camelCase;
var camelCase;

// Assignments
camelCase = 10;
camelCase = "A String";
camelCase = 9000;

```
i can not pass a test even though i wrote right declaration and assignment variables. please i need help with this.

**Comment by scaley29** [comment]
This is what I had to do and I passed it and was able to move on.


// Declarations
var studlyCapVar;
var properCamelCase;
var titleCaseOver;

// Assignments
studlyCapVar = 10;
properCamelCase = "A String";
titleCaseOver = 9000;

Most people have been rewritten it again so it adds double but all you have to do is follow the guidelines for "properCamelCase" once you do that and make sure each first word is lower case and any other words after that the first letter is CAPITAL then it will pass.
