### ISSUE TITLE
New endpoint for FCC cat API for posting data using AJAX.

### ISSUE THREAD

**Issue by MayankPratap** [FreeCodeCamp/FreeCodeCamp#10191]
I am planning to add a challenge in "JSON APIs and AJAX" challenges where campers can post data to server using AJAX. Currently FCC has no endpoint for POST.  Currently what I have thought is that if user clicks on a button named "Cats" then server should return a page containing image of cats, and if the user clicks on "Dogs" then server should return a page containing image of dogs. So if an endpoint  can be made to support this then this challenge can be added.   Challenge is simple and has been kept in theme with the existing challenges.

**Comment by raisedadead** [comment]
@MayankPratap thanks for reporting. 

I am moving the thread to Curriculum Expansion Repository, for discussion.
