### ISSUE TITLE
Find the Longest Word in a string

### ISSUE THREAD

**Issue by Eviaiva** [FreeCodeCamp/FreeCodeCamp#10206]
Challenge [Find the Longest Word in a String](https://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=%0Afunction%20findLongestWord(str)%20%7B%0A%20%20str%20%3D%20str.split('%20')%3B%0A%20%20%0A%20%20for%20(%20var%20i%20%3D%200%3B%20i%3Cstr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20str%5Bi%5D%20%3D%20str%5Bi%5D.replace(str%5Bi%5D%2C%20str%5Bi%5D.length)%3B%0A%20%20%7D%0A%20%20%0A%20%20str%20%3D%20str.sort(function(a%2Cb)%20%7B%0A%20%20%20%20return%20b-a%3B%0A%20%20%7D)%3B%0A%20%20%0A%20%20return%20str%5B0%5D%3B%0A%20%20%0A%7D%0A%0AfindLongestWord(%22May%20the%20force%20be%20with%20you.%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 9_3_3 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/52.0.2743.84 Mobile/13G34 Safari/601.1.46</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function findLongestWord(str) {
  str = str.split(' ');
  
  for ( var i = 0; i<str.length; i++) {
    str[i] = str[i].replace(str[i], str[i].length);
  }
  
  str = str.sort(function(a,b) {
    return b-a;
  });
  
  return str[0];
  
}

findLongestWord("May the force be with you.");
```

I looked for any global variables but couldn't find any, still it won't let me pass even though I had the right number.  Help!

**Comment by Eviaiva** [comment]
Im sorry, but I still think it's a bug.

**Comment by dhcodes** [comment]
Hi, @Eviaiva. I think the reason the tests aren't passing is that your value is a string and needs to be a number. Return your value converted to a number and you'll be good to go. In the future, consider confirming in the Help Chat room before opening an issue. Happy coding!

**Comment by Eviaiva** [comment]
I will, still, thank you so much for your time.
