### ISSUE TITLE
Challenge Accessing Nested Objects doesn't ignore spaces but JS does.

### ISSUE THREAD

**Issue by revisualize** [FreeCodeCamp/FreeCodeCamp#10202]
Challenge [Accessing Nested Objects](https://www.freecodecamp.com/challenges/accessing-nested-objects#?solution=%0A%2F%2F%20Setup%0Avar%20myStorage%20%3D%20%7B%0A%20%20%22car%22%3A%20%7B%0A%20%20%20%20%22inside%22%3A%20%7B%0A%20%20%20%20%20%20%22glove%20box%22%3A%20%22maps%22%2C%0A%20%20%20%20%20%20%22passenger%20seat%22%3A%20%22crumbs%22%0A%20%20%20%20%20%7D%2C%0A%20%20%20%20%22outside%22%3A%20%7B%0A%20%20%20%20%20%20%22trunk%22%3A%20%22jack%22%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20gloveBoxContents%20%3D%20myStorage.car.inside%5B%20'glove%20box'%20%5D%3B%20%2F%2F%20Change%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStorage = {
  "car": {
    "inside": {
      "glove box": "maps",
      "passenger seat": "crumbs"
     },
    "outside": {
      "trunk": "jack"
    }
  }
};

// Only change code below this line

var gloveBoxContents = myStorage.car.inside[ 'glove box' ]; // Change this line
```
When you do `myStorage.car.inside[ 'glove box' ];` the challenge doesn't pass the:
Use dot and bracket notation to access `myStorage`
However, JS ignores the spaces outside of the single quotes. and access a property with:
`[ 'name with a space' ]` is valid.

To pass the challenge you're required to do:
`var gloveBoxContents = myStorage.car.inside['glove box'];`

**Comment by dhcodes** [comment]
Probably could be fixed with an update to the Regex to allow an optional space character. I'll take this on tomorrow if others agree it should be fixed.

**Comment by atjonathan** [comment]
I think we could update the regex as @dhcodes said to allow a space.
cc/ @FreeCodeCamp/issue-moderators

**Comment by dhcodes** [comment]
I went ahead and made the update because I had the time. Feel free to block it if you decide it shouldn't accept spaces 👯

**Comment by Siloamn** [comment]
this still was not updated i tried it and still does not accept spaces

**Comment by dhcodes** [comment]
@Siloamn the change was made to the [beta](https://beta.freecodecamp.com) codebase so it may not show up on the current live site.

**Comment by Timmaaaa** [comment]
Hi
