### ISSUE TITLE
dont wok? what is wrong with class smaller-image

### ISSUE THREAD

**Issue by pegisu** [FreeCodeCamp/FreeCodeCamp#10201]
Challenge [Size your Images](https://www.freecodecamp.com/challenges/size-your-images#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%20%20%0A%20.smaller-image%20%7B%0A%20%20%20%20%0A%20%20%20%20width%3A100px%3B%0A%20%20%20%20%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fsr%2F1%2F1b%2FCreme_Puff_%2528cat%2529.jpg%22%20class%3D%22smaller-image%22%20alt%3D%22nista%22%3E%0A%20%20%20%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    
    font-size: 16px;
    font-family: Monospace;
  }
  
 .smaller-image {
    
    width:100px;
    
    
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://upload.wikimedia.org/wikipedia/sr/1/1b/Creme_Puff_%28cat%29.jpg" class="smaller-image" alt="nista">
   
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by qmikew1** [comment]
I'd clear code and explicitly reference the class in the img tag ```class="smaller-image"``` [help for more](https://gitter.im/FreeCodeCamp/Help) - But what's odd, and might be an actual bug is the default src
```<img src="https://upload.wikimedia.org/wikipedia/sr/1/1b/Creme_Puff_%28cat%29.jpg" class="smaller-image" alt="nista">``` 
in your code - which is different from what's in codebase and what I show in when I reset code (which is)
```<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">```
(unless you added your own source, which would be wrong) - But, again, resetting your code and referencing the class in img tag ... would solve this.

**Comment by BKinahan** [comment]
@pegisu You can add *additional* images if you like, but the test checks that you have added the correct class to the image provided (as this image is used in various challenges in this section to provide continuity between them).

Please do visit the [Help chat](https://gitter.im/FreeCodeCamp/Help) as @qmikew1 suggested if you need any further assistance.

**Comment by ThatoShell** [comment]
i still dont get the correct mark for the class...       
heres my code were did i go wrong


<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

<style>
.red-text {
color: red;
}

h2 {
font-family: Lobster, Monospace;
}

p {
font-size: 16px;
font-family: Monospace;
}

  .smaller-image {
    width: 100px;
  }

 </style>


<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image { width: 100px; }"; src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">


<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by coderred63** [comment]
You didn't make a style element and put your classes in separate classes.
(Example:)
<style>
     .red-text  {
              Color: red;
                  }
           h2  {
           font-family: lobster, monospace;
            }
</style>


On Aug 26, 2016 12:05 AM, "Thato Shell" <notifications@github.com> wrote:
>
> i still dont get the correct mark for the class...
>
> heres my code were did i go wrong
>
> .red-text { color: red; } h2 { font-family: Lobster, Monospace; } p {
font-size: 16px; font-family: Monospace; } .smaller-image { width: 100px; }
> CatPhotoApp
>
> Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching
attack your ankles chase the red dot, hairball run catnip eat the grass
sniff.
>
> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere
rip the couch sleep in the sink fluffy fur catnip scratched.

**Comment by ThatoShell** [comment]
i did as you said but still got an error for, "img element should have the class smaller-image."

can you go to your HTML5 and check the lesson on "size your images" maybe i missed a step or something...

**Comment by ThatoShell** [comment]
thanks got it :+1:
