### ISSUE TITLE
Challenge Drop It - Uses a recursive algorithm and fails tests, console logs correct

### ISSUE THREAD

**Issue by 149203** [FreeCodeCamp/FreeCodeCamp#10209]
Challenge [Drop it](https://www.freecodecamp.com/challenges/drop-it#?solution=%2F%2F%20jshint%20esversion%3A6%0A%2F%2F%20jshint%20-W033%0A%0A%2F%2F%20take%20the%20first%20val%20of%20an%20arr%0A%2F%2F%20if%20first%20val%20passes%20func%20test%0A%2F%2F%20return%20the%20arr%0A%2F%2F%20else%20drop%20the%20first%20val%0A%2F%2F%20repeat%0A%2F%2F%20if%20arr.length%20%3D%3D%3D%200%2C%20return%20%5B%5D%0A%0Aconsole.log(%22----------START----------%22)%0A%0Afunction%20dropElements(arr%2C%20func)%20%7B%0A%20%20if%20(!arr.length)%20%7B%0A%20%20%20%20console.log(%22Returned%3A%20%22%2C%20arr)%0A%20%20%20%20return%20arr%20%2F%2F%20this%20will%20be%20%5B%5D%20if%20we%20cut%20out%20all%20the%20arr%20vals%0A%20%20%7D%0A%20%20if%20(!func(arr%5B0%5D))%20%7B%0A%20%20%20%20let%20cut%20%3D%20arr.splice(0%2C1)%0A%20%20%20%20console.log(%22Cut%20out%3A%20%22%2C%20cut)%0A%20%20%20%20dropElements(arr%2C%20func)%0A%20%20%7D%0A%20%20else%20%7B%0A%20%20%20%20console.log(%22Returned%3A%20%22%2C%20arr)%0A%20%20%20%20return%20arr%0A%20%20%7D%20%20%0A%7D%0A%0AdropElements(%5B%5D%2C%20function(n)%20%7Breturn%20n%20%3E%3D%203%3B%7D)%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// jshint esversion:6
// jshint -W033

// take the first val of an arr
// if first val passes func test
// return the arr
// else drop the first val
// repeat
// if arr.length === 0, return []

console.log("----------START----------")

function dropElements(arr, func) {
  if (!arr.length) {
    console.log("Returned: ", arr)
    return arr // this will be [] if we cut out all the arr vals
  }
  if (!func(arr[0])) {
    let cut = arr.splice(0,1)
    console.log("Cut out: ", cut)
    dropElements(arr, func)
  }
  else {
    console.log("Returned: ", arr)
    return arr
  }  
}

dropElements([], function(n) {return n >= 3;})

```

SCREENSHOTS:
![drop-it-challenge](https://cloud.githubusercontent.com/assets/13108534/17652550/dd9724a2-6233-11e6-95cb-a8b68a744e10.JPG)

![drop-it-challenge-failure](https://cloud.githubusercontent.com/assets/13108534/17652554/0fcf4990-6234-11e6-9ea6-5cfa46fd8a18.JPG)

**Comment by BKinahan** [comment]
Hi @149203, thanks for reporting. That's an interesting solution, but unfortunately it's not quite correct!

I will leave it as an exercise for you to think about why this is the case, but your code will return the correct results only if the last line within your second `if` statement is changed from `dropElements(arr, func)` to `return dropElements(arr, func)`

Remember that the [HelpJavaScript chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) should be your first port of call when something isn't working quite right with your code, before raising an issue.

Happy coding!

**Comment by 149203** [comment]
@BKinahan thanks for the quick reply! Will do!
