### ISSUE TITLE
Tests pass before finished typing

### ISSUE THREAD

**Issue by digitaldak** [FreeCodeCamp/FreeCodeCamp#1021]
Challenge http://www.freecodecamp.org/challenges/waypoint-mobile-responsive-images has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The following will pass the test:
```html
<img class="img-responsive" src="http://bit.ly/fcc-kittens2"
```

Note: it's missing a `>` at the end of it

Im thinking this is a flaw with it rendering it on the fly creating the dom elements even if it's not complete? But it leads to a false sense of being done when you really aren't done with the element to pass it.  Subjective I guess depending on your view of it?

**Comment by BerkeleyTrue** [comment]
new url http://freecodecamp.com/challenges/waypoint-make-images-mobile-responsive

**Comment by awesomeaniruddh** [comment]
This is not passing for me. Has this been fixed?

**Comment by awesomeaniruddh** [comment]
```
<(?=[^>]*<)|>(?=[^<]*>)

**Comment by ptsurbeleu** [comment]
I can take a look into it.
