### ISSUE TITLE
stand in line

### ISSUE THREAD

**Issue by mwandama** [FreeCodeCamp/FreeCodeCamp#10217]
This is my code what wrong with it
function nextInLine(arr, item) {
  // Your code here
  testArr.push(item);
  item = testArr[0];
  testArr.shift();
  return item;  // Change this line
}

// Test Setup
var testArr = [5,6,7,8,9];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 7)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));
see below what they want done

nextInLine([], 1) should return 1
nextInLine([2], 1) should return 2
nextInLine([5,6,7,8,9], 1) should return 5(this is line is the only one not working
After nextInLine(testArr, 10), testArr[4] should be 10

see link below
https://www.freecodecamp.com/challenges/stand-in-line#?solution=function%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20testArr.push(item)%3B%0A%20%20item%20%3D%20testArr%5B0%5D%3B%0A%20%20testArr.shift()%3B%0A%20%20return%20item%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B5%2C6%2C7%2C8%2C9%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%207))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B

**Comment by BKinahan** [comment]
Hi @mwandama 

The issue tracker is for reporting bugs only. Please use the [HelpJavaScript chat room]([July 21, 2016 2:00 PM](https://gitter.im/FreeCodeCamp/HelpJavaScript) for help with writing code for the algorithm challenges.

Happy coding!
