### ISSUE TITLE
Use CSS Class to Style an Element - h2 is not red even though I have the other 3 requirements checked off. 

### ISSUE THREAD

**Issue by mnmlogan3** [FreeCodeCamp/FreeCodeCamp#10212]
Use CSS Class to Style an Element - h2 is not red even though I have the other 3 requirements checked off.

Red X - Your h2 element should be red.
Green Checkmark - Your h2 element should have the class red-text.
Green Checkmark - Your stylesheet should declare a red-text class and have its color set to red.
Green Checkmark - Do not use inline style declarations like style="color: red" in you

Challenge Name - Use CSS Class to Style an Element 

I'm using Chrome on an Android phone.

Here's my code:

```
 <style>
  h2 .red-text  {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

I have a programmer friend who entered exactly what I have entered in a computer and it was accepted and he got all green checkmarks.

**Comment by qmikew1** [comment]
You need to *replace* h2 with ```.red-text``` currently you have both (drop the h2) ```h2 .red-text``` - For more, [help room](https://gitter.im/FreeCodeCamp/Help) is good for stuff like this. Also, ```<br>``` shouldn't be added to your code (unless that's just some side effect of you posting from phone to issue)

**Comment by mnmlogan3** [comment]
I tried it that way too. It still had the same red x on h2 element should be red.

**Comment by mnmlogan3** [comment]
This is the code I just tried again without the h2.

<style>
  .red-text{
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by mnmlogan3** [comment]
This is the code I just tried again without the h2.

<style>
  .red-text{
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

**Comment by qmikew1** [comment]
You would also, then need to reference red-text in the element itself - But posting your *full* code in help room is probably best as this is for issues with the site itself and not as a help mechanism

**Comment by erictleung** [comment]
@mnmlogan3 thanks for the issue but as @qmikew1 has mentioned, if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Your issue may be related to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7753, which we have found that CSS gets messed up a little on Android phones. Please redo the challenge on a desktop/laptop computer to see if you have the same issues. Happy coding!

**Comment by Suloko** [comment]
<style>
  h2.red-text
  {
    color:red;
  }
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by Suloko** [comment]
Am also having the same issue

**Comment by mnmlogan3** [comment]
I think it's because I was on my phone (an Android). Once I switch to a
"computer" the same code worked. I've been using a Surface.

**Comment by Suloko** [comment]
Am also using my computer not phone.

**Comment by mnmlogan3** [comment]
Hmmmm.. then I would suggest just triple checking ever part of the code.
I've found sometimes it's just a little difference between what I typed and
what I was supposed to.. like 1 character or a space or something so small.

**Comment by BerkeleyTrue** [comment]
The issue tracker is for reporting bugs only. If this is a for help with a challenge, please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by trevorham92** [comment]
how do I apply red text class to my p element guys.. ? and  gals lol

**Comment by trevorham92** [comment]
disregard this.

**Comment by paintedlbird7** [comment]
What am I doing wrong?


<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p> class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by texas2010** [comment]
@paintedlbird7 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by singhnamita** [comment]
<html>
  
 
<style>
.red-text
  {
    color:red;
  }
    
  
</style>
 
  <h2 class="red-text">CatPhotoApp</h2>


<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  

</html>

**Comment by singhnamita** [comment]
<html>
  
 
<style>
.red-text
  {
    color:red;
  }
    
  
</style>
 
  <h2 class="red-text">CatPhotoApp</h2>


<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  

</html>

**Comment by dipsikharay** [comment]
<style>

.red-text { color: red ;}

</style>

<h2 class="red-text">CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

declare class in style-sheet but I think my code is right still can't run.
