### ISSUE TITLE
Counting Cards Example Output Misleading

### ISSUE THREAD

**Issue by AHead-SoftwareDev** [FreeCodeCamp/FreeCodeCamp#10219]
In the Basic JavaScript section of the Front End Development Certification, the directions for the Counting Cards challenge show the following Example Output:

     "-3 Hold"
     "5 Bet"

Since previous challenges deal with escaping characters such as the double quote, I thought the solution required double quotes around the result as depicted in the Example Output.  After spending some time troubleshooting my code, I discovered that the expected answer is one without quotes.  For example:

    -3 Hold
     5 Bet

In order to avoid confusion, I think the Example Output should not include double quotes around the output.  It misleads the coder into thinking that double quotes should be a part of the output when the accepted answer is not expecting them.

As an alternative, the system could accept results that include quotes in the output.

#### Sample Code
  if (count>0) return "\"" + count + " Bet\""; //This code fails because it includes escaped double quotes
  if (count<=0) return count + " Hold";  //This code passes because it doesn't include quotes

#### Challenge Name:  Counting Cards

https://www.freecodecamp.com/challenges/counting-cards#?solution=%0Avar%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch%20(card)%7B%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20case%204%3A%20%0A%20%20%20%20case%205%3A%20%0A%20%20%20%20case%206%3A%20%20%20%20%20%20%0A%20%20%20%20%20%20count%2B%2B%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%207%3A%0A%20%20%20%20case%208%3A%20%0A%20%20%20%20case%209%3A%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2010%3A%0A%20%20%20%20case%20%27J%27%3A%0A%20%20%20%20case%20%27Q%27%3A%20%0A%20%20%20%20case%20%27K%27%3A%20%0A%20%20%20%20case%20%27A%27%3A%0A%20%20%20%20%20%20count--%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%7D%0A%20%20%0A%2F%2F%20%20if%20(count%3E0)%20return%20%27%22%27%20%2B%20count%20%2B%20%27%20Bet%22%27%3B%0A%20%20if%20(count%3E0)%20return%20%22%5C%22%22%20%2B%20count%20%2B%20%22%20Bet%5C%22%22%3B%0A%20%20if%20(count%3C%3D0)%20return%20count%20%2B%20%22%20Hold%22%3B%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0A%2F%2Fcc(2)%3B%20cc(3)%3B%20cc(7)%3B%20cc(%27K%27)%3B%20cc(%27A%27)%3B%0Acc(2)%3B%20cc(3)%3B%20cc(4)%3B%20cc(5)%3B%20cc(6)%3B%20%2F%2Freturns%20%225%20Bet%22%0A%2F%2Fcc(7)%3B%20cc(8)%3B%20cc(9)%3B%20%2F%2Freturns%20%220%20Hold%22%0A%2F%2Fcc(10)%3B%20cc(%27J%27)%3B%20cc(%27Q%27)%3B%20cc(%27K%27)%3B%20cc(%27A%27)%3B%20%2F%2Freturns%20%22-5%20Hold%22%0A

**Comment by Greenheart** [comment]
@AHead-SoftwareDev Thanks for bringing this up for discussion! 

I can definitely understand your point and I agree - it's inconsistent to sometimes show the expected output with- and sometimes without quotes. It's possible to interpret the example output as both strings - that when run printed as output won't have quotes, or the literal strings where the output should have escaped quotes added.

I vote for removing the quotes from the example output.
@FreeCodeCamp/issue-moderators Thoughts?

Maybe this could be a first-timers contribution? **We just need to provide more detailed instructions**

**Comment by BKinahan** [comment]
I think the instructions are quite clear that `Bet` and `Hold` are themselves strings without needing the double quotes around them in the code format, so those can probably be removed. It would be useful to have some way of distinguishing different types in the instructions (eg without needing to use quotes to specify something is a string), but I'm not sure what form that would take.

There is some inconsistency about string format in instructions, output, and test messages between various challenges and it would be great to have some unified style there to prevent confusion as seen in other issues similar to this one.

**Comment by Greenheart** [comment]
@BKinahan Yeah we could probably find several inconsistencies like this one in other places.
It's a minor detail though so we may want to focus on other issues and solve these things first when people actually find them problematic enough to report them.

**Comment by AHead-SoftwareDev** [comment]
Here's my attempt at a solution to wording of this particular challenge.

**Current wording:**
. . .The function will then return a string with the current count and the string "Bet" if the count is positive, or "Hold" if the count is zero or negative. The current count and the player's decision ("Bet" or "Hold") should be separated by a single space.

Example Output
"-3 Hold"
"5 Bet"

Hint
Do NOT reset count to 0 when value is 7, 8, or 9.

**Suggested Wording:** 
. . .The function will then return a **string** with the current count and the word Bet if the count is positive.  If the count is zero or negative, the function will return a string with the current count and the word Hold.  The current count and the word Bet or Hold should be separated by a single space.

Example Output
-3 Hold
5 Bet

Hint
Do NOT reset count to 0 when value is 7, 8, or 9.
Do NOT return an array.
Do NOT include quotes (single or double) in the output.

**Comment by Greenheart** [comment]
@AHead-SoftwareDev Nice work! :blush: I like the hints you added! 

I can't however say anything about the rephrasing of the instruction (I'm too tired atm)

**Comment by oalhait** [comment]
@AHead-SoftwareDev your suggestions sound great! I'll make the changes if nobody objects.

**Comment by rungol** [comment]
Had the same issue.

The example shows outputs in quotes, when the answer requires output without quotes. 
It's confusing and easy to fix. Have the format of the example output match that required for the answer.

**Comment by Internetworld** [comment]
to solve quotation in answer just modify return statement to be like this

return ('"'+count + " "+'Hold"');

use single quotes to define it is as a string and combine it with double quotes as an output with the string result
