### ISSUE TITLE
Links to images are broken (again)

### ISSUE THREAD

**Issue by eXConf** [FreeCodeCamp/FreeCodeCamp#10211]
Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
---
So the links are broken again. With so many free images hosting services why use a private server?

**Comment by atjonathan** [comment]
@eXConf, please add more detail to your issue report. If you are referring to the images on the codepen, they work fine for me.

**Comment by eXConf** [comment]
@atjonathan, I've got ERR_CONNECTION_TIMED_OUT for images in portfolio hosted on http://qlip.in/. My friend, who lives in Ukraine too, but in different city and use different internet provider, reported the same problem.
Here are some screenshots: 
http://image.prntscr.com/image/98990d9f43e84202beb49143365227f0.jpeg
http://image.prntscr.com/image/93b1c962fa7740a6ad3eab35158df096.jpeg

**Comment by Locheed** [comment]
Works for me. Some geoblocking there?

**Comment by atjonathan** [comment]
@FreeCodeCamp/issue-moderators, anyone else got this issue?

**Comment by hallaathrad** [comment]
On it.

**Comment by hallaathrad** [comment]
Seems like it's been the server trying to protect my images from the constant hotlinking some people are submitting them to. Not sure I like others using them for their own portfolios (as they may claim property). Maybe I'll replace them with some others random images. 
I've tried setting the server up to avoiding hotlinking from other servers but we'll se if that works at all. Alternate ideas?

**Comment by oalhait** [comment]
I think it would just be ideal if we made the images hosted on imgur. However, I totally agree that we should use stock images instead.

**Comment by oalhait** [comment]
@hallaathrad how does [this](https://codepen.io/anon/pen/wWOvqE) look?

**Comment by QuincyLarson** [comment]
@oalhait @eXConf @hallaathrad Note - we are re-doing the example websites for the front end challenges to make them much simpler and less intimidating - in pure HTML and CSS. I've opened an issue for this if anyone wants to create a simple portfolio page: https://github.com/FreeCodeCamp/CurriculumExpansion/issues/36

I am closing this issue, as the current portfolio page challenge will be replaced with this new one ASAP.
