### ISSUE TITLE
Cant seem to get past this challange

### ISSUE THREAD

**Issue by kchibrown** [FreeCodeCamp/FreeCodeCamp#10218]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3C!--%0A%3Ch1%3EHello%20World%3C%2Fh1%3E--%3E%0A%0A%3Ch2%3E--%3E%3Cp%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 AOL/9.8 AOLBuild/4346.2019.US Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!--
<h1>Hello World</h1>-->

<h2>--><p>


```

**Comment by erictleung** [comment]
@kchibrown thanks for the issue but GitHub issues are not for coding help. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
