### ISSUE TITLE
what's wrong with code? I did everything right. anyone checck it out?

### ISSUE THREAD

**Issue by anishapooja** [FreeCodeCamp/FreeCodeCamp#10214]
Challenge [Storing Values with the Assignment Operator](https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator#?solution=%0A%2F%2F%20Setup%0Avar%20a%3B%0Avar%20b%20%3D%202%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20a%3D7%3B%0Avar%20a%3Db%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var a;
var b = 2;

// Only change code below this line

var a=7;
var a=b;
```

**Comment by BKinahan** [comment]
Hi @anishapooja

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) for help with writing code.

Happy coding!
