### ISSUE TITLE
why is it not working?

### ISSUE THREAD

**Issue by vuka92** [FreeCodeCamp/FreeCodeCamp#10215]
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=%0Afunction%20myLocalScope()%20%7B%0A%20%20'use%20strict'%3B%0A%20%20%0A%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0AmyLocalScope(myVar)%3B%0A%0A%2F%2F%20Run%20and%20check%20the%20console%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myLocalScope%0A%0A%2F%2F%20Now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function myLocalScope() {
  'use strict';
  
  
  console.log(myVar);
}
myLocalScope(myVar);

// Run and check the console
// myVar is not defined outside of myLocalScope

// Now remove the console log line to pass the test


```

**Comment by BKinahan** [comment]
Hi @vuka92 

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) for help with writing code.

Happy coding!

**Comment by zhanghao0371** [comment]
It maybe a bug. I have the same question. Otherwise the FCC.cn doesn't have this question
