### ISSUE TITLE
Add question to FAQ about fast tracking non-camper students

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#10221]
> Q:  I work for a school/bootcamp/MOOC. Can we fast track our certified students to work on your nonprofit projects?

> A: Our pro bono Code Grant program is designed for developers to gain real world experience by building projects for nonprofit organizations. We recognize the value of this opportunity for your students. However, at this time, only those who have completed the Front End, Back End, and Data Visualization certifications at Free Code Camp are eligible to participate. 

>We would encourage you to consider creating a skills-based volunteer initiative at your school/bootcamp/MOOC. For help getting started, contact Michael@freecodecamp.com. 

Updated with @CodeNonprofit input

**Comment by CodeNonprofit** [comment]
> Q:  I work for a school/bootcamp/MOOC. Can we fast track our certified students to work on your nonprofit projects?

> A: Our pro bono Code Grant program is designed for developers to gain real world experience by building projects for nonprofit organizations. We recognize the value of this opportunity for your students. However, at this time, only those who have completed the Front End, Back End, and Data Visualization certifications at Free Code Camp are eligible to participate. 

>We would encourage you to consider creating a skills-based volunteer initiative at your school/bootcamp/MOOC. For help getting started, contact Michael@freecodecamp.com.

**Comment by alanbares** [comment]
I'll work on this.
