### ISSUE TITLE
would create a bullet point-style list of "milk" and "cheese".

### ISSUE THREAD

**Issue by tblac864** [FreeCodeCamp/FreeCodeCamp#10227]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by oalhait** [comment]
Could you help us with what challenge you're talking about, and a more detailed description of what you think can be made better? Thanks!

**Comment by erictleung** [comment]
@tblac864 thanks for the issue but that "sentence fragment" in [Create a Bulleted Unordered List](https://www.freecodecamp.com/challenges/create-a-bulleted-unordered-list) tries to make a complete sentence with the code above it.

> For example:
> ```
> <ul>
>   <li>milk</li>
>   <li>cheese</li>
> </ul>
> ```
> would create a bullet point-style list of "milk" and "cheese".

It may look strange at first but it works. Happy coding!
