### ISSUE TITLE
Update Answer to "How did Free Code Camp get started?"

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#10229]
Currently in the FAQs in the ["About"](https://www.freecodecamp.com/about) section of FreeCodeCamp, we have a question and answer

> ### How did Free Code Camp get started?
> Quincy started our open source community in 2014. He is now just one of many active contributors.

Recently, @CodeNonprofit published a Medium article ["How I made My First Million Dollars in Pro Bono Code"](How I made my first million dollars (in pro bono code)). I feel like this exciting article chronicles part of Free Code Camp's beginnings that appropriately adds to the answer of how Free Code Camp started.

### Suggested Change

[This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/views/resources/about.jade#L158) would need to be edited to something like this.

> ### How did Free Code Camp get started?
> Quincy started our open source community in 2014. He is now just one of many active contributors. You can read more in [this Medium story](https://medium.freecodecamp.com/how-i-made-my-first-million-dollars-in-pro-bono-code-86f911040484#.pgftldy1b).

**Comment by alayek** [comment]
@erictleung awesome find! I am adding a first-timer label.

**Comment by Locheed** [comment]
Lemme try this. :)
