### ISSUE TITLE
My output is not been approved and submitted

### ISSUE THREAD

**Issue by Jamezslim90** [FreeCodeCamp/FreeCodeCamp#10234]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D%20%22FirstLine%5Cn%5C%5CSecondLine%5C%5C%5CrThirdline%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr= "FirstLine\n\\SecondLine\\\rThirdline";



```

**Comment by Jamezslim90** [comment]
I need help please, 
                 its tell to use encoded text with proper escape sequence and no spacing
  what do i do?

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by Jamezslim90** [comment]
I used the chat room but no answer

**Comment by kornelny** [comment]
Same issue. It's frustrating because I can't continue with course.
![capture](https://cloud.githubusercontent.com/assets/20116675/17820037/c0a7f22a-6618-11e6-8df9-bbdccc7cfb22.PNG)
