### ISSUE TITLE
Exact change test criteria

### ISSUE THREAD

**Issue by JohnnyBizzel** [FreeCodeCamp/FreeCodeCamp#10232]
[Exact Change](https://www.freecodecamp.com/challenges/exact-change)

**Issue Description**
This test
`checkCashRegister(19.50, 20.00, [["PENNY", 0.01], ["NICKEL", 0], ["DIME", 0], ["QUARTER", 0], ["ONE", 1.00], ["FIVE", 0], ["TEN", 0], ["TWENTY", 0], ["ONE HUNDRED", 0]]) should return "Insufficient Funds".`
is a fail.
The test in the description says ... 

> Return the string "Insufficient Funds" if cash-in-drawer is less than the change due.

The change in the register is $1.01 and the change needed is $0.50, therefore there is enough change in the register. The problem is there are not the correct denominations to give exact change.

**Comment by satyam22** [comment]
i'm facing the same problem and i'm in doubt that test case is correct or not.
please help me to go through this

**Comment by dhcodes** [comment]
So it looks like the test is written so it will return insufficient funds for this case so in essence, it's the instructions that need to be changed from:

>Return the string "Insufficient Funds" if cash-in-drawer is less than the change due.

to:

>Return the string "Insufficient Funds" if cash-in-drawer is less than the change due or the denominations in the drawer do not allow the correct change to be given.

Is that correct?

**Comment by satyam22** [comment]
thanks for help

**Comment by BKinahan** [comment]
See also #9580 and #9657. This challenge does need some adjustment.

**Comment by oalhait** [comment]
Yeah @dhcodes your sentence clarifies it more. How does

> Return the string "Insufficient Funds" if cash-in-drawer is less than the change due or if you cannot return exact change.

sound though? That way, the two conditions you need to satisfy are made both clear and succinct.

**Comment by JohnnyBizzel** [comment]
Another way to present it is that if the change available does not match the change needed, the status is "Correct change not available" instead of "Insufficient Funds".

**Comment by oalhait** [comment]
@JohnnyBizzel The thing is, I feel like that's oversimplifying it to the point where you have to think further than simply "you don't have enough money."

**Comment by JohnnyBizzel** [comment]
@oalhait I don't know what you mean but thanks for making the change to the wording of the test.

**Comment by jonataswalker** [comment]
The Exact Change challenge doesn't reflect the merged PR #10246, which is a bit confusing.

**Comment by atjonathan** [comment]
@jonataswalker, it's possible that because the current status of `https://freecodecamp.com` doesn't reflect the `staging` branch, the change hasn't been pushed to production yet. Hopefully we will have this up shortly 😃
