### ISSUE TITLE
Waypoint: Add Placeholder Text to a Text Field - Test Output Text

### ISSUE THREAD

**Issue by thecrimsonchin** [FreeCodeCamp/freecodecamp#1023]
![screen shot 2015-06-20 at 12 53 05 am](https://cloud.githubusercontent.com/assets/4744153/8266516/d703bc70-16e6-11e5-9da0-414b0e84a3c5.jpg)
Challenge http://www.freecodecamp.com/challenges/waypoint-add-placeholder-text-to-a-text-field has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

before I enter any html the test output reads " Cannot read property 'match' of undefined" after I enter "placeholder" it changes to "Set the value of your placeholder attribute to "cat photo URL"." , which is the correct text.

nothing major just something I noticed.

**Comment by digitaldak** [comment]
Quincy fixed this in #988 I believe, it was on stream fix on 2015/06/20 that I don think was pushed out yet.

**Comment by BerkeleyTrue** [comment]
fixed 

Happy coding!
