### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by marcellmar** [FreeCodeCamp/FreeCodeCamp#10238]
Challenge [Iterate Through an Array with a For Loop](https://www.freecodecamp.com/challenges/iterate-through-an-array-with-a-for-loop#?solution=%0A%2F%2F%20Example%0Avar%20ourArr%20%3D%20%5B%209%2C%2010%2C%2011%2C%2012%5D%3B%0Avar%20ourTotal%20%3D%200%3B%0A%0Afor%20(var%20i%20%3D%200%3B%20i%20%3C%20ourArr.length%3B%20i%2B%2B)%20%7B%0A%20%20ourTotal%20%2B%3D%20ourArr%5Bi%5D%3B%0A%7D%0A%0A%2F%2F%20Setup%0Avar%20myArr%20%3D%20%5B%202%2C%203%2C%204%2C%205%2C%206%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20total%20%3D%200%3B%0Afor%20(%20var%20i%20%3D%200%3B%20i%20%3C%20myArr.lentgh%3B%20i%2B%2B)%20%7B%0A%20%20total%20%3D%2B%20myArr%5Bi%5D%3B%0A%7D%0A%20%20%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArr = [ 9, 10, 11, 12];
var ourTotal = 0;

for (var i = 0; i < ourArr.length; i++) {
  ourTotal += ourArr[i];
}

// Setup
var myArr = [ 2, 3, 4, 5, 6];

// Only change code below this line

var total = 0;
for ( var i = 0; i < myArr.lentgh; i++) {
  total =+ myArr[i];
}
  



```

**Comment by erictleung** [comment]
@marcellmar thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). GitHub issues are not for coding help. Hint: check the spelling of your methods and functions. You have a typo somewhere. Happy coding!
