### ISSUE TITLE
Why hide not working - jquery?

### ISSUE THREAD

**Issue by mayursadhu** [FreeCodeCamp/FreeCodeCamp#10231]
<body>
  
<nav class="nav navbar-inverse navbar-fixed-top">
<div class="navbar-header">
<a class="navbar-brand" href="#"><img src="http://qlip.in/sites/default/files/qlip.png"> </a> 
</div>
<ul class="nav navbar-nav">
<li class="active"><a href="">ABOUT</a></li>
<li><a href="#">PORTFOLIO</a></li>
<li><a href="contact">CONTACT</a></li>
</ul>
</nav>
<div class="container">
<div class="well" id="well-1">
<div class="row">
<div class="col-md-8">
<p>The name is Justin and I'm an UX/UI designeveloper, with extensive practical experience in brand strategy, creative direction and project management; devoted to Functional Programming and Information Architecture. Also a huge fan of semantics and futuristic interfaces.</p><br><p id="summary">Web Developer - Graphic Artist - User Experience Designer
  </p>
</div>
<div class="col-md-4">
<img src="http://qlip.in/avatar.png" alt="Justin" class="img-circle">
</div>
</div>
</div>
<div class="well">
<p id="portfolio">PORTFOLIO</p>
<div class="row">
<div class="col-md-6">
<img src="http://qlip.in/sites/default/files/YMCA-Realtor-Donation-3.jpg" alt="image-1" height=350 width=550>
</div>
<div class="col-md-6">
<img src="http://qlip.in/sites/default/files/webcaballero.jpg" alt="image-2" height=350 width=533>
</div>
</div>
  <br> 
<div class="row">
<div class="col-md-6">
<img src="http://qlip.in/sites/default/files/webmarqas.jpg" alt="image-3" height=350 width=550>
</div>
<div class="col-md-6">
<img src="http://qlip.in/sites/default/files/webbrandaxis.jpg" alt="image-4" height=350 width=533>
</div>
</div>
  </div>
<div class="well">
  <p id="contact">CONTACT ME</p>
<div class="row">
<div class="col-md-6">
<div class="form-group">
  <br>
  <p id="name">Name</p><input type="text" class="form-control" id="guest" placeholder="Name"><br>
  <p>Email</p><input type="email" class="form-control" id="mailID" placeholder="E-mail"><br>
  <p>Phone Number</p><input type="text" class="form-control" id="phNo" placeholder="Phone Number"><br>
   <p>Message</p><textarea class="form-control" rows="5" id="message" placeholder="Message"></textarea>
</div>
</div>

<div class="col-md-6">
<p class="contact">Want to get in touch with me? Be it to request more info about myself or my experience, to ask for my resume, tips on how to solve your sudoku, random questions about the universe and the meaning of life, or even if only for some nice Fika here in stunning Toronto... just feel free to drop me a line anytime.
<br><br>
  I promise to reply A.S.A.P.</p>
</div>
</div>
</div>
</body>

This is my script
$(document).ready(function(){
    $("p#name").hide();
});

**Comment by Locheed** [comment]
This is only for bug reporting. Use FCC's Gitter help channel for help: https://gitter.im/FreeCodeCamp/Help

And You need to target right element, with Your Jquery. Ask help from help channel.

**Comment by erictleung** [comment]
@mayursadhu as @Locheed has mentioned, GitHub is not for coding help. You may want to check if you are loading jQuery correctly. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
