### ISSUE TITLE
I wish it provided the value of the variable 'arr'.  

### ISSUE THREAD

**Issue by JakeCorn** [FreeCodeCamp/FreeCodeCamp#10240]
not having the value of variable "arr" really hung me up and it makes it seem like a mixture of code and psuedocode

#### Challenge Name

nesting for loops in JavaScript

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by BKinahan** [comment]
Hi @JakeCorn. Could you elaborate on what you mean?

In the Nesting For Loops challenge, a value for a variable named `arr` is given in the example in the instructions (`[ [1,2], [3,4], [5,6] ]`), and values for the parameter `arr` used in the function `multiplyArr` in the editor are passed in for arguments during each test (with the second test's value of `[ [1,2], [3,4], [5,6,7] ]` used as a default at the bottom of the editor).

The topics of reusable functions and arguments are covered earlier in the same section of the course so I'm not sure where your confusion is arising from.

**Comment by oalhait** [comment]
I feel like using arr twice in the same challenge is a little bit confusing, since arr is the parameter in the function you're editing, and it's also used as an example array in the description. I'd suggest changing the name of the arr used as an example in the description to something like ex1 or exampleArray or something like that. @BKinahan thoughts?

**Comment by BKinahan** [comment]
@oalhait Several challenges use `arr` as both an example variable in the instructions and as the parameter name in the pre-defined function signature. It's a standard way to illustrate what can be done with arrays while being clear which variable refers to the array, similar to how `str` is used for string variables, and from what I have seen that format doesn't seem to cause confusion in any of those challenges.

Anyway, I'd like to know if that was the cause of the confusion in this case, or if it was something else, so let's give @JakeCorn some time to add further information 😄

**Comment by atjonathan** [comment]
Closing as stale.
