### ISSUE TITLE
i can not pass this challenge

### ISSUE THREAD

**Issue by 44552** [FreeCodeCamp/FreeCodeCamp#10244]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%20%3D%20%22I%20am%20a%5C%22double%20quoted%5C%22string%20inside%5C%22double%20quotes%5C%22.%22%3B%20%2F%2Fchange%20this%20line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "I am a\"double quoted\"string inside\"double quotes\"."; //change this line

```

i can not pass this challenge even though i put right answer. i do not know what is a problem

**Comment by oalhait** [comment]
Hello, 
Unfortunately, the issue section is not for coding help. Please head to the [gitter chat](https://gitter.im/FreeCodeCamp/FreeCodeCamp) for help on coding problems.

**Comment by atjonathan** [comment]
@oalhait is correct :+1: 
Thanks.
