### ISSUE TITLE
Update Contribution guidelines

### ISSUE THREAD

**Issue by karanjthakkar** [FreeCodeCamp/FreeCodeCamp#10247]
#### Challenge Name

Github PR commits can now be squashed

#### Issue Description

The Contributing.md file mentions the following:

```
Many Pull Requests, especially first Pull Requests, require correction or
updating. If you have used the GitHub interface to create your PR, you will need
to close your PR, create a new branch, and re-submit. This is because you cannot
squash your commits via the GitHub interface.
```

However, as of [April 2, 2016](https://github.com/blog/2141-squash-your-commits), Github PR commits can be squashed while merging them. So I think that the text needs to be update but not sure what to replace it with.

**Comment by atjonathan** [comment]
I believe we only squash commits in browser for first timers. It's good practice to learn it locally.  cc/ @Freecodecamp/issue-moderators

**Comment by raisedadead** [comment]
Hi @karanjthakkar.

Thanks for reporting, but we have an intention of getting the commits squashed by Contributors.

Sure, the feature is great. But its a practice that we follow, as a part of learning process for mostly new Contributors.

Also if you would have noticed, unless there is a special case, we insist on not mentioning any issue nos on the commit messages, which is not the case with other OSS repos.

Every OSS repo has its own policies.

Thanks again and hope this clarifies the point.
Happy Contributing!

**Comment by karanjthakkar** [comment]
@raisedadead @atjonathan I think there was a misunderstanding in what I was proposing. I get that it's a process that is followed for the purposes of learning. The only problem I have is with this line: `This is because you cannot squash your commits via the GitHub interface.` This is not true. And that is what the issue was about. Not about advocating the use of the Github interface. :) Anyway, if you think it's best to keep it as it is, sure.

**Comment by atjonathan** [comment]
@karanjthakkar, this is a good point. Sorry about missing that.

**To First Timer:**
```diff
- This is because you cannot squash your commits via the GitHub interface.
```
You will need to change [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#if-your-pr-is-rejected) section. Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

> **Note:** You can only submit a pull request for this issue if you are new and haven't submitted one before. Hence the issue label `first-timers-only` :stuck_out_tongue_winking_eye:

**Comment by karanjthakkar** [comment]
@atjonathan Great. I'll just remove that section and send across a PR, since I'm also a first timer.
