### ISSUE TITLE
Slack chat room invitation never received.

### ISSUE THREAD

**Issue by janbell** [FreeCodeCamp/freecodecamp#1024]
Challenge http://www.freecodecamp.com/challenges/waypoint-join-our-chat-room has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Clicking on the link in box 3 as directed creates a new copy of that screen with the message:
  We've successfully requested an invite for you. Please check your email and follow the instructions from Slack.

There is no such email in my inbox or Spam folder. I have triple-checked the correctness of the email address and even copy/pasted it. Nothing. If I click on "Chat" on the top bar, an error message pops up:
opps! Something went wrong. Please try again later

Cannot progress in chat without the email.

**Comment by DBaldwin107** [comment]
I'm having the exact same issue. I also have a problem where the profile form keeps telling me that I need to include my name (which I did multiple times trying combinations of initials + last name, etc. and finally full name... and it won't take any of them - but when I view the profile it is there.) So frustrating. 

I wish I had the answer, but maybe if this gets enough attention it will be fixed.

**Comment by janbell** [comment]
Can we proceed in the lessons without access to chat?

**Comment by DBaldwin107** [comment]
Yes, I did a bunch of lessons without it - but then I got stuck on one and that is where having Slack would have come in handy.

**Comment by janbell** [comment]
Cool, thanks.

**Comment by BerkeleyTrue** [comment]
Looks like we are having issues with Slack. We are going to use #1014 to track this problem.

**Comment by OhgeunJoy** [comment]
Hello,
I am having an exact problem.   My team leader sent invitation several time but I never received invitation.
I checked spam folder but nothing is there. 
How did you guys resolved this issue ?

**Comment by SaintPeter** [comment]
@OhgeunJoy We stopped using slack over 6 months ago.
