### ISSUE TITLE
Check For Palindromes Challenge-Issue.

### ISSUE THREAD

**Issue by stergi** [FreeCodeCamp/FreeCodeCamp#10241]
#### Challenge Name

https://www.freecodecamp.com/challenges/check-for-palindromes

#### Issue Description

Well,reverse() function does not seem to work and split() function reverses the array(randomly and not all the time/tested with console) for some reason.

#### Browser Information

* Browser Name, Version: Google Chrome,Version 52
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
function palindrome(str) {
  // Good luck!
    
  var s=str.replace(/[^A-Za-z0-9]/g, '');
  var l=s.toLowerCase();
  var r=l.split("");
  var n=r.reverse();
  
 if(r==n){
   return true;
 }
  else{
    return false;
  }
  
}



palindrome("five|\_/|four");
 
 
```

**Comment by stergi** [comment]
#Update:
For testing purposes:
Consider the following code:
```
function palindrome(str) {
  // Good luck!
    
  var s=str.replace(/[^A-Za-z0-9]/g, '');
  var l=s.toLowerCase();
  var r=l.split("");
  
return r;  
}

palindrome("five|\_/|four");
```
In the console it returns:  }
["f","i","v","e","f","o","u","r"]

But if I add the following line:
```
var n=r.reverse();
```
like this:
```
function palindrome(str) {
  // Good luck!
    
  var s=str.replace(/[^A-Za-z0-9]/g, '');
  var l=s.toLowerCase();
  var r=l.split("");
  var n=r.reverse();
return r;
}

palindrome("five|\_/|four");
```

Then the reverse array is returned.

**Comment by BKinahan** [comment]
Hi @stergi. Be sure to visit the [HelpJavaScript](https://gitter.im/FreeCodeCamp/HelpJavaScript) chat for any questions about the JavaScript algorithm challenges; the issue tracker is for bugs affecting the FreeCodeCamp challenges or website.

Happy coding!
