### ISSUE TITLE
Won't let me pass to the next challenge. Prompt says I haven't added the abbreiviated hex for Fuschia. 

### ISSUE THREAD

**Issue by lemonslol** [FreeCodeCamp/FreeCodeCamp#10252]
Challenge [Use Abbreviated Hex Code](https://www.freecodecamp.com/challenges/use-abbreviated-hex-code#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20%23F00%3B%0A%20%20%7D%0A%20%20.fuchsia-text%20%7B%0A%20%20%20%20color%3A%20%23F0F%0A%20%20%7D%0A%20%20.cyan-text%20%7B%0A%20%20%20%20color%3A%20%230FF%3B%0A%20%20%7D%0A%20%20.green-text%20%7B%0A%20%20%20%20color%3A%20%230F0%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22fuchsia-text%22%3EI%20am%20fuchsia!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22cyan-text%22%3EI%20am%20cyan!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22green-text%22%3EI%20am%20green!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: #F00;
  }
  .fuchsia-text {
    color: #F0F
  }
  .cyan-text {
    color: #0FF;
  }
  .green-text {
    color: #0F0;
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="fuchsia-text">I am fuchsia!</h1>

<h1 class="cyan-text">I am cyan!</h1>

<h1 class="green-text">I am green!</h1>

```

**Comment by atjonathan** [comment]
@lemonslol, you need a semi-colon (`;`) at the end of a line in CSS. 
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
