### ISSUE TITLE
I get error that i changed the global var

### ISSUE THREAD

**Issue by rololik** [FreeCodeCamp/FreeCodeCamp#10253]
The global var should be overwritten with the local and it does, but in the end I get the error that i changed the global var and does not let me complete the assignment. Here is the code:

// Setup
var outerWear = "T-Shirt";

function myOutfit() {
  // Only change code below this line
  
  outerWear = "sweater";
  
  // Only change code above this line
  return outerWear;
}

myOutfit();

**Comment by BKinahan** [comment]
Hi @rololik. Unfortunately your code is incorrect because you did not declare a local variable within the function. Have another look at the example in the instructions, and if you need further help please visit the [Help chat room](https://gitter.im/FreeCodeCamp/Help).

Happy coding!

**Comment by rololik** [comment]
thank you very much!
