### ISSUE TITLE
Bug in Nesting for Loops

### ISSUE THREAD

**Issue by cetaphil** [FreeCodeCamp/FreeCodeCamp#10254]
#### Challenge Name

Nesting for Loops

#### Issue Description

I was trying to solve the challenge when the tab freeze completely (My code was shit). I tried to do it again in another browser (Chrome) and had the same problem. Tried to refresh my code from the console but can´t open it, same thing with hard refresh. Does it mean I have future on QA? 

#### Browser Information

* Browser Name, Version: Opera 
* Operating System: 39.0.2256.48
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
```
#### Screenshot

![freze](https://cloud.githubusercontent.com/assets/18297239/17748405/9a3eea74-648f-11e6-8531-7038a4c24f34.jpg)

**Comment by raisedadead** [comment]
Have you reached out to the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript)? You can disable the code runner by following [the steps here](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Disable-Code-Autorun).

**Comment by cetaphil** [comment]
Sorry, non English speaker. By reach out you mean if I managed to enter or if I asked for help?. I'm going ask in the chat, but I though that was for code doubts. Also, I tried those steps, didn't work either : (

**Comment by cetaphil** [comment]
I tried disable the code runner again a worked. I'm closing this. 

Thanks dude!

**Comment by cetaphil** [comment]
Sorry. Didn't work lol

**Comment by raisedadead** [comment]
@cetaphil please share your code, here as seen in the screenshot.

**Comment by cetaphil** [comment]
@raisedadead  I can't disable the runner, change the code or clean it and run it again. I need the runner on to modify the code. When I turn it on, It load my early crappy code and crash everything
  
      function multiplyAll(arr) {
      var product = 1;
      // Only change code below this line
      for (i = 0; i < multiplyAll.length; i++)
          for (a = 0; i < multiplyAll.length; a++)
      product = multiplyAll[i*a];
      // Only change code above this line
      return product;
      }


    multiplyAll([[1,2],[3,4],[5,6,7]]);

**Comment by raisedadead** [comment]
@cetaphil try [this link](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Clear-Specific-Data-Local-Storage)

**Comment by cetaphil** [comment]
Worked : ) . Thanks @raisedadead
