### ISSUE TITLE
Use CSS Selectors to Style Elements

### ISSUE THREAD

**Issue by liqueta026** [FreeCodeCamp/FreeCodeCamp#10250]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%0A%0A%3Cstyle%3E%20h2%20%7Bcolor%3A%20blue%3B%7D%20%3C%2Fstyle%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html


<style> h2 {color: blue;} </style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```
Here's what the system now allowing me to pass: 
Your h2 element should be blue.

**Comment by raisedadead** [comment]
Thanks for reporting, but GitHub issues are for bugs in website only. Your code is not correct.

Please check below for help.
[Help Chat Room](https://gitter.im/FreeCodeCamp/Help).

**Comment by atjonathan** [comment]
@liqueta026 There is no `h2` tag present. Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by liqueta026** [comment]
I've tried the chat room for help and I'm still stuck at this same point since yesterday. You guys make it difficult to ask questions and get help.

**Comment by Amarillia** [comment]
```
<style>
  h2{
    color:blue;
  }
</style>
<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

My code working fine. I don't see any bug...

**Comment by dwd2010** [comment]
@Amarillia 
This place is not for put answer on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by ShannonFirst** [comment]
I AM STUCK ON THE SAME. I have also tried the camps and chat room. Why don't you just stinking tell us so we can move forward? FOR THE LOVE OF ALL THINGS NEW AND CODED!!
