### ISSUE TITLE
A question with a challenge named Title Case a Sentence

### ISSUE THREAD

**Issue by GODWJZ** [FreeCodeCamp/FreeCodeCamp#10264]
#### Challenge Name

https://www.freecodecamp.com/challenges/title-case-a-sentence

#### Browser Information

* Browser Name, Version: firefox
* Operating System: win10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
function titleCase(str) {
  var lower= str.toLowerCase();
  var string = lower.split(" ");
  var part2="";
  var arr = [];
  for(i=0;i<string.length;i++){
    var substring = string[i].split("");
    var part1;
    for(j=0;j<substring.length;j++){
      if(j===0){
        part1=substring[0].toUpperCase();
      }else{
        part1+=substring[j];
      }
    }
  arr = arr.push();
  }
  return arr.join(" ");
}

titleCase("I'm a little tea pot");

```
#### Screenshot

Why the system tell me arr.push is not a function ,and all the Circles with hook is green but can't pass.
I want to know why this happen ,thank you 

![_2016-08-18t12-35-52 030z](https://cloud.githubusercontent.com/assets/20476998/17773922/64a1eef8-6583-11e6-85c1-916bcac71763.png)

**Comment by erictleung** [comment]
@GODWJZ when I run your code, I only get one check mark. If you check your code, there is a little mistake you make near the end. Hint: think about why `arr.push()` might not be a function, it's only a method of arrays, right? If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
