### ISSUE TITLE
Challenge not passed, right output

### ISSUE THREAD

**Issue by nayD93** [FreeCodeCamp/FreeCodeCamp#10269]
Challenge [Smallest Common Multiple](https://www.freecodecamp.com/challenges/smallest-common-multiple#?solution=%0Afunction%20smallestCommons(arr)%20%7B%0A%20%20var%20max%20%3D%20Math.max(arr%5B0%5D%2C%20arr%5B1%5D)%3B%0A%20%20var%20min%20%3D%20Math.min(arr%5B0%5D%2C%20arr%5B1%5D)%3B%0A%20%20var%20count%20%3D%200%3B%0A%20%20%0A%20%20for(var%20i%20%3D%201%3B%20%3B%20i%2B%2B)%20%7B%0A%20%20%20%20for%20(var%20j%20%3D%20min%3B%20j%20%3C%3D%20max%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20if%20(i%20%25%20j%20%3D%3D%3D%200)%20count%2B%2B%3B%0A%20%20%20%20%20%20if%20(count%20%3D%3D%3D%20max)%20return%20i%3B%0A%20%20%20%20%7D%0A%20%20%20%20count%20%3D%200%3B%0A%20%20%7D%0A%20%20return%200%3B%0A%7D%0A%0AsmallestCommons(%5B1%2C%205%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function smallestCommons(arr) {
  var max = Math.max(arr[0], arr[1]);
  var min = Math.min(arr[0], arr[1]);
  var count = 0;
  
  for(var i = 1; ; i++) {
    for (var j = min; j <= max; j++) {
      if (i % j === 0) count++;
      if (count === max) return i;
    }
    count = 0;
  }
  return 0;
}

smallestCommons([1, 5]);
```
I tried this on arch linux with latest firefox.
the debugger shows, that the solution is correct.
Also doesn't work with // noprotect.

**Comment by oalhait** [comment]
> for(var i = 1; ; i++) {
I think you missed something here. Before you submit an issue, please make sure your code is good by asking for help on the [gitter chat](https://gitter.im/FreeCodeCamp/FreeCodeCamp). 
Happy Coding!

**Comment by AngeloRwanda** [comment]
I know have a similar issue, and given the fact that this is my first issue report, I am not sure if I should open a new one or no. Below is my code. It is working smoothly and within a very short amount of time in Safari. In Firefox or Chrome, the errors are different in both browsers. P.S: I am a beginner, I know my code is very very rusty. I'm learning, I will improve.
```

​/*START of SOLUTION */


function smallestCommons(arr) {

  /* STEP 1. Fill out arr with necessary 

  int (incrementing by 1 untill 

  it equals the largest of arr's max) */

   arr.sort(function(a,b) {return a-b;});

  var smallOfArr = arr[0];
       if(smallOfArr == 1){smallOfArr = 2;} /* in case the lowest is 1, 

                                             eliminate it as (n*1=n) */  

  

  var bigOfArr= arr[1], i, newArr=[];
  for (i=smallOfArr; i<=bigOfArr; i++){newArr.push(i); } 
  
  /*Completion of step 1.
   the new array is named newArr*/

  

  /*2.  Produce array of multiples of maximum of arr, 
		but lower to product of array1*/

  var productOfArr = newArr.reduce(function multiplier (a,b) {return a*b;});
  var multiplesArr =[];   
  for (var a =bigOfArr; a<=productOfArr; a=a+bigOfArr){

    multiplesArr.push(a);}  /* Completion of step2. 
                            The array is called multiplesArr */

 

  /* 3. If any member of multiplesArr can divide all members of newArr, filter it. Push it to finalArray*/ 
 
 var finalArray = [];  /*Initializing the array */
 
 function checkerFx(n){ 
    for( var z=0; z<newArr.length; z++){
		if((n % newArr[z])!== 0) {return false;} }
		return true; }

     
  finalArray = multiplesArr.filter(checkerFx);

 //if(arr[0]===18){return 6056820; }
  return finalArray[0];}

  smallestCommons([1,5]);
  /* END OF SOLUTION */
```

**Comment by BerkeleyTrue** [comment]
The issue tracker is for reporting bugs only. If this is an issue for help with a challenge, please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
