### ISSUE TITLE
Find the Longest Word in a String 

### ISSUE THREAD

**Issue by GODWJZ** [FreeCodeCamp/FreeCodeCamp#10261]
please tell me what's wrong with my code,thank you:
function findLongestWord(str) {
  str1 = str.split(" ");
  var max = str1[0];
  for (var i = 0; i <str1.length; i++){
    if (str1[i] > max) {
      max = str1[i];
    }
  }
  return max.length;
}

findLongestWord("The quick brown fox jumped over the lazy dog");

![_2016-08-18t02-44-29 259z](https://cloud.githubusercontent.com/assets/20476998/17760218/c523fe72-6530-11e6-9365-66644ca60052.png)

**Comment by MohammadZahrawi** [comment]
your code wrong ,because you write if (str1[i] > max) ,but str1[i] is not number ,other word  you  compare word with number , you must compare number with number

**Comment by MohammadZahrawi** [comment]
I write code but doesn't work , I am sure my code is right , but unfortunately doesn't work 

var L;
var word;
var count=0;

function findLongestWord(str) {
  var longest=str.split(" ");
  var num =longest.length;
  for (var i=0;i<=(num-1);i++)
  {
     word=longest[i];
    L=word.length;
    if(L>count)
      {
        count=L;
        
      }
  }
  return count;
}

findLongestWord("May the force be with you");

**Comment by texas2010** [comment]
@MohammadZahrawi 
This place is not for put answer on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
