### ISSUE TITLE
Target the Children of an Element Using jQuery

### ISSUE THREAD

**Issue by Gragoli** [FreeCodeCamp/FreeCodeCamp#10267]
Challenge [Target the Children of an Element Using jQuery](https://www.freecodecamp.com/challenges/target-the-children-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hello, could you explain me please, why do I have two of <h4>#target5</h4> on my left-well when i have only one line of <h4>$("#target5").clone().appendTo("#left-well");</h4> 

Thank you,

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

![screen shot 2016-08-18 at 19 32 17](https://cloud.githubusercontent.com/assets/21046765/17786011/e201a0cc-657a-11e6-842f-2390719d84e9.png)
![screen shot 2016-08-18 at 19 36 13](https://cloud.githubusercontent.com/assets/21046765/17786056/1c84c08a-657b-11e6-8743-891bcf1c8d89.png)

**Comment by BKinahan** [comment]
Hi @Gragoli. Thanks for reporting this, but it is already a known issue (#5072) and has been resolved (#7430) but the fix has not gone live on the website yet.

Happy coding!
