### ISSUE TITLE
Test case for HTTP JSON API Server error

### ISSUE THREAD

**Issue by reed7** [FreeCodeCamp/FreeCodeCamp#10265]
Challenge [Continue working with Nodejs Servers](https://www.freecodecamp.com/challenges/continue-working-with-nodejs-servers) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.

The URL is /api/parsetime?iso=2016-08-18T14:48:45.720Z
But the expected is set to: EXPECTED:  "{\"hour\":10,\"minute\":48,\"second\":45}"

Note the value of "hour".

**Comment by BKinahan** [comment]
Hi @reed7.

That URL you reference contains time information for approximately the same time as you posted your issue, so I'm guessing it was the current time when you were doing the exercise. However, `learnyounode`'s test cases don't take account of the current time, so it's likely that for the test a different URL is actually passed in to your code.

If there is an issue with `learnyounode` workshop, it actually belongs on the issue tracker for `learnyounode`, which you can find [here](https://github.com/workshopper/learnyounode/issues). You will probably get a similar answer there, though, so instead try a visit to the FreeCodeCamp [HelpBackEnd chat room](https://gitter.im/FreeCodeCamp/HelpBackEnd) to see if someone there can help answer your question 😄 

Happy coding!
