### ISSUE TITLE
SLACK!!!

### ISSUE THREAD

**Issue by DBaldwin107** [FreeCodeCamp/freecodecamp#1026]
Challenge http://www.freecodecamp.com/challenges/waypoint-join-our-chat-room has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I have followed the directions - but do not receive the email stated in this step:

1.Click this link, which will email you can invite to Free Code Camp's Slack chat rooms: http://freecodecamp.com/api/slack. <I did that I got  message that it was successful>

1.Now check your email and click the link in the email from Slack.<nearly a half hour - no email.>

ALSO, I keep getting an error on the profile page that indicates that I need to enter my name even though I have done that several times.

I tried to paste my screen clip into this page, but this form will not accept it. Argh!!

I guess I will go back to Codecademy at least for today. Not being able to get past these most simple tasks is beyond frustrating.

**Comment by andreiamlm** [comment]
I have experienced the same issue.

**Comment by DBaldwin107** [comment]
It's maddening. So for now, I am back to another class on Codecademy - "Make an Interactive Website" using Java Script and jQuery.

I like that Free Code Camp has a clear-cut path for learning and provides an opportunity to work on real-world projects at the end - but the help is more accessible on Codecademy. so that is what I'll be working on for the rest of the weekend.

**Comment by andreiamlm** [comment]
Yes it is.  I tried a lot of times and always received the confirmation info but never received the email. Codecademy is great I have been also doing some courses there. There are a lot of people complaining about this Slack issue.

**Comment by BerkeleyTrue** [comment]
Thanks for reporting. This is a common issue we are having today. Please see #1014 for updates.

also @DBaldwin107 If you can grab some snap shots of the `name` field issue you are having and create a new issue. Links to images works as well.

**Comment by DBaldwin107** [comment]
Actually, when I just accessed my profile, - my name is populated correctly
now - so maybe was some temporary glitchy thing.

Thanks for looking into it.

Will wait for progress on slack. I got stuck on a lesson and thought it
would be helpful to see if anyone else was dealing with the same Q.

Thanks again,
Diana

On Sat, Jun 20, 2015 at 1:15 PM, Berkeley Martinez <notifications@github.com

**Comment by BerkeleyTrue** [comment]
Sorry about that. Thanks for you patience. Definitely let us know if you see any other bugs.
