### ISSUE TITLE
Can't seem to get past lvl 16

### ISSUE THREAD

**Issue by shelleyfromyard** [FreeCodeCamp/FreeCodeCamp#10279]
![screen shot 2016-08-19 at 6 01 03 pm](https://cloud.githubusercontent.com/assets/16158359/17825566/4d9b858e-6637-11e6-8631-5c712a9e19ce.png)
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20h2%20%0A%20%20.red-text%20%7B%20color%3A%20red%3B%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
![image](https://cloud.githubusercontent.com/assets/16158359/17825548/2c018a4a-6637-11e6-82c4-21ed4eb39fb1.png)

My code:
```html

<style>
  h2 
  .red-text { color: red; }
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by BKinahan** [comment]
Hi @shelleyfromyard.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with specific challenges.

Happy coding!
