### ISSUE TITLE
Page does not load completely on MacBook 

### ISSUE THREAD

**Issue by shelleyfromyard** [FreeCodeCamp/FreeCodeCamp#10276]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by BKinahan** [comment]
Hi @shelleyfromyard. Could you please add some more information about your issue? What page is not loading correctly, and what browser and device are you using?

Thanks!

**Comment by shelleyfromyard** [comment]
Actually i just didn't realize there was a scroll bar to the side of the screen. Sorry. I'm such a neophyte.
