### ISSUE TITLE
Code was right but didn't work

### ISSUE THREAD

**Issue by laveda** [FreeCodeCamp/FreeCodeCamp#10275]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20blue%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {color: blue;}
</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by BKinahan** [comment]
Hi @laveda. Unfortunately your code is incorrect because you have deleted the entire `h2` element rather than just removing its style attribute.

If you need further assistance, please visit the [Help chat](https://gitter.im/FreeCodeCamp/Help).

Happy coding!

**Comment by potager32** [comment]
so take out the h2 all together this is tricky for beginners???!!!!

**Comment by potager32** [comment]
example  of style attributes pls

**Comment by texas2010** [comment]
@potager32, Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.
GitHub Issues are for reporting bugs on the website only.

Happy Coding.
