### ISSUE TITLE
It seems like test system is having problem! It gathered all test cases' results into output

### ISSUE THREAD

**Issue by KhanhNB** [FreeCodeCamp/FreeCodeCamp#10271]
Challenge [Steamroller](https://www.freecodecamp.com/challenges/steamroller#?solution=result%20%3D%20%5B%5D%3B%0Afunction%20pull(arr)%7B%0A%20%20for(var%20i%3D0%3B%20i%3Carr.length%3B%20i%2B%2B)%7B%0A%20%20%20%20if(!Array.isArray(arr%5Bi%5D))%20result.push(arr%5Bi%5D)%3B%0A%20%20%20%20else%20pull(arr%5Bi%5D)%3B%0A%20%20%7D%0A%7D%0Afunction%20steamrollArray(arr)%20%7B%0A%20%20%2F%2F%20I'm%20a%20steamroller%2C%20baby%0A%20%20pull(arr)%3B%0A%20%20return%20result%3B%0A%7D%0A%0AsteamrollArray(%5B1%2C%20%5B2%5D%2C%20%5B3%2C%20%5B%5B4%5D%5D%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
result = [];
function pull(arr){
  for(var i=0; i<arr.length; i++){
    if(!Array.isArray(arr[i])) result.push(arr[i]);
    else pull(arr[i]);
  }
}
function steamrollArray(arr) {
  // I'm a steamroller, baby
  pull(arr);
  return result;
}

steamrollArray([1, [2], [3, [[4]]]]);

```

**Comment by erictleung** [comment]
@KhanhNB each test is run consecutively right after each other. You have a global variable `result` that will be changed with each run of the test, thus, giving you all the results in one output. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
