### ISSUE TITLE
Add the instruction on the description, for ID

### ISSUE THREAD

**Issue by mejiaadonay** [FreeCodeCamp/FreeCodeCamp#10274]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```
#### Screenshot

It is not a big issue, technically there is no one, but I think there should be an example on how to declare an ID on the style section for those that they don't know.

**Comment by dhcodes** [comment]
@mejiaadonay there is this challenge in the HTML/CSS section: https://www.freecodecamp.com/challenges/set-the-id-of-an-element 

Is that what you mean?

**Comment by BKinahan** [comment]
@mejiaadonay I think the example you are looking for can be found in the challenge [Use an ID Attribute to Style an Element](https://www.freecodecamp.com/challenges/use-an-id-attribute-to-style-an-element).

If I am not understanding you correctly, feel free to re-open the issue and add more information.

Happy coding!
