### ISSUE TITLE
Incorrect error message:  Make sure your li element has a closing tag

### ISSUE THREAD

**Issue by breyn407** [FreeCodeCamp/freecodecamp#1027]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list has an issue:
<br>Started this simple exercise around 7am with <strong>no coffee</strong> yet.
<ul>
<li>Started replacing the the first p tag I saw (tunnel vision), which was the "Click here for cat photos" line.  I had made an error by using the /l instead of the /li  closing tag on the "Click here..." line.</li>
<li>Then the coffee kicked in and I realized I was on the wrong line (and using the wrong closing tag).
So I deleted the /l (without correcting it), then replaced it and the opening tag with p tags (restoring it to its original state).</li>
<li>Then I created the ul/li code block as seen in the screen shot.</li>
</ul>
I've stared at this for 20 minutes and reviewed it about a bazillion times.  I don't see the problem.  But the error checker (or whatever it's called) is telling me to add a closing </li> tag.  <strong>Add to where?</strong>

![screenshot 2015-06-20 08 07 08](https://cloud.githubusercontent.com/assets/12973744/8267865/018e6e52-1725-11e5-8bfe-f56617268c6d.png)

**Comment by nghong** [comment]
Maybe because of the <a> tag before <ul>, there's a splash / at the end of the opening tag.

**Comment by nghong** [comment]
Did you reload the page?

**Comment by nghong** [comment]
Weird, after I delete "class" attribute in &lt;li&gt;, the code works fine.

**Comment by breyn407** [comment]
I reloaded the page to start fresh.  This time I only replaced the two p elements with the required 3 li elements.  i.e. no "oops" moments this time
I get the <strong>same result.</strong>  It doesn't work.  Same error (see screenshot)
Thanks @nghong.  I will delete the "class" attribute so I can at least progress to the next Waypoint.  This still seems like a bug to me so I'm leaving this open.
![screenshot 2015-06-20 08 52 08](https://cloud.githubusercontent.com/assets/12973744/8267993/3e469ca2-172a-11e5-926a-e61a2df75ea2.png)

**Comment by breyn407** [comment]
@nghong, re your first comment:  firstly, it looks like your tags disappeared, probably because markup is allowed in the comments (I don't yet know how to escape those back into visibility - someone who has been on Github longer than my 5 minutes can help out there).
Second:  I think you were referring to the img tag embedded in an anchor "a" element.  If so, the / is for the img.

**Comment by Gusshi** [comment]
I had the same problem here, then I had to delete both class attribute on on <li> weird wasted 10 min of my times.

**Comment by BerkeleyTrue** [comment]
It is the class attribute that is causing the issue. If you remove them you should be fine.

Happy Coding!
