### ISSUE TITLE
Challenge: Confirm the Ending passes with .endsWith()

### ISSUE THREAD

**Issue by piq9117** [FreeCodeCamp/FreeCodeCamp#10282]
```
function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  return str.endsWith(target) // if I don't end with semi-colon it will pass.
}

confirmEnding("Bastian", "n");
```

**Comment by dhcodes** [comment]
I'm not sure this is a bug so much as a genuine solution for a user who finds it.

**Comment by BKinahan** [comment]
Actually there is a test which asks the user not to use endsWith, and the regex is probably a bit too specific:
`!/\\.endsWith\\(.*?\\)\\s*?;/.test(code)`
when it would be sufficient to test only for `.endsWith(` to determine the method is used.
Right now with the semi-colon included in the regex, it's more like the test is saying "Don't use endsWith, at least not with the correct syntax anyway" 😄

**Comment by erictleung** [comment]
[This line of code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/4ab8d1835070bc86131d60fdff8061f778abb716/seed/challenges/01-front-end-development-certification/basic-bonfires.json#L377) needs to be changed so the regex doesn't need the semi-colon or at least make it optional.

```diff
- !/\\.endsWith\\(.*?\\)\\s*?;/
+ !/\\.endsWith\\(.*?\\)\\s*?/
```

**Comment by AndrewGHC** [comment]
#10286
