### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by Aymanelsayed** [FreeCodeCamp/FreeCodeCamp#10281]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%0A%3C!..%3Ch1%3EHello%20World%3C%2Fh1%3E--%3E%0A%0A%3Ch2%3Ecatphotoapp%3C%2Fh2%3E%0A%0A%3C!..%3Cp%3EHello%20Paragraph%3C%2Fp%3E--%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html


<!..<h1>Hello World</h1>-->

<h2>catphotoapp</h2>

<!..<p>Hello Paragraph</p>-->


```

**Comment by qmikew1** [comment]
html comments take this form ```<!--Commented element-->``` - You have two periods vs. dashes. -[help](https://gitter.im/FreeCodeCamp/Help) is a great place for questions like this. (This is for issues with site codebase)

**Comment by BerkeleyTrue** [comment]
The issue tracker is for reporting bugs only. If this is a for help with a challenge, please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
