### ISSUE TITLE
theres a bug. The code is correct

### ISSUE THREAD

**Issue by Jonathancsanon** [FreeCodeCamp/FreeCodeCamp#10296]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7Bcolor%3A%20pink%3B%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3A%20%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {color: pink;}
</style>
<h1 class: "pink-text">Hello World!</h1>




```

**Comment by dhcodes** [comment]
@Jonathancsanon You have an error in your last line. If you run into something like this in the future, consider asking in the [FCC Help Chat](https://gitter.im/FreeCodeCamp/Help) to confirm the issue before posting it here.

**Comment by Jonathancsanon** [comment]
oh ok sorry about that.

**Comment by erictleung** [comment]
@Jonathancsanon thanks for the issue but as @dhcodes has pointed out, the last line of your code has an issue. You can also tell there is an error because your editor should outline part of your last line differently than the rest of your code. Please reach out to the chat rooms if you're still having issues. Happy coding!

**Comment by Jonathancsanon** [comment]
yea I miss the =. Lol that's embarrassing but I'm learning
