### ISSUE TITLE
Add Rounded Corners with a Border Radius

### ISSUE THREAD

**Issue by Aymanelsayed** [FreeCodeCamp/FreeCodeCamp#10291]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by dhcodes** [comment]
@Aymanelsayed please edit your post to give an indication of what the bug you are experiencing is.

**Comment by texas2010** [comment]
no respond for 2 days. we could reopen it if he fill it up.
