### ISSUE TITLE
im new

### ISSUE THREAD

**Issue by saidhamouda67** [FreeCodeCamp/FreeCodeCamp#10298]
Challenge [Inform with the Paragraph Element](https://www.freecodecamp.com/challenges/inform-with-the-paragraph-element#?solution=%3CP%3EHello%20Paragraph%3C%2Fp%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<P>Hello Paragraph</p>
<h1>Hello World</h1>
<h2>CatPhotoApp</h2>

```

**Comment by THalletProtech** [comment]
Read the directions carefully... your paragraph element is in the wrong place.

**Comment by saidhamouda67** [comment]
thank you i did it =D

**Comment by BKinahan** [comment]
Closing as resolved.

@saidhamouda67 Please use the [Help chat](https://gitter.im/FreeCodeCamp/Help) for help with writing code before raising an issue. The issue tracker is for reporting bugs in the challenges or website.

Happy coding!
