### ISSUE TITLE
Two items are tied together in the same test causing false failure until both are met

### ISSUE THREAD

**Issue by digitaldak** [FreeCodeCamp/FreeCodeCamp#1029]
Challenge http://www.freecodecamp.org/challenges/waypoint-warn-your-users-of-a-dangerous-action has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

So this one is an odd duck to look at via the test itself. The test is looking for the "delete" word after trying to look up the css class to identify the object that would have it via its text... Originally I thought it was another space around the word delete caused the issue, but it's not. Somehow there should be a way to identify if a button has the word delete in it, perhaps the delete check via the css class should be a completely different test to ensure they put delete on the correct button with that class, but as it stands now the test really isn't accurate for what its saying given that you can pass any step at anytime out of order.

Perhaps changing the wording of the test, err.. I'm not sure what to think on this one :\
![waypoint-warn-your-users-of-a-dangerous-action](https://cloud.githubusercontent.com/assets/3256176/8268137/adbb04d4-172e-11e5-992b-c66bb65e3198.png)

Possible file this one under nit-picky.. (i'll take that in all truth)

**Comment by benschenker** [comment]
Thanks again @digitaldak!

This one seems to have been fixed, I'll close it.
