### ISSUE TITLE
Not an issue but a suggestion

### ISSUE THREAD

**Issue by WRyan78** [FreeCodeCamp/FreeCodeCamp#10308]
#### Issue Description

 Not truly an issue but perhaps a good end User suggestion. 

When you click 'Run Tests' and you pass, the very large dialogue box pops up and covers all the code. 
Many times I was running the test as a 'Test', and though I passed I still want to review and go over the code. But I can't, I have to close the dialogue box and resubmit the info to complete and progress. 

This wastes both our bandwidth because the test has to be reprocessed and submitted again. 

Perhaps I'm the only one that wants to look over the code again after passing the test but I think it would be great if I could either move that large confirm/success box out of the way, or perhaps if it popped open further down the page beneath the code without obscuring it. 

Over and over again I find myself closing the Success box so I can review the code and review the lesson. This is because unless I'm 100% sure of what I'm doing, I'm _playing_ with the lesson and experimenting to see what variation of syntax is 'right'. I find out I'm right when the Success box opens up but again,..then it's blocking the code I wish to review and I have to close it and resubmit my answers to move on. 

Not a big issue at all since I can just close the Success box and re-submit. But it would be great if it didn't obscure the code and I didn't have to submit the same correct answer twice. 

Honestly it seems like it pops up in the worst possible spot on the page,..in my opinion. 
 
* Browser Name, Version: Chrome and Edge
* Operating System: Win10
* Mobile, Desktop, or Tablet: 17" Laptop 

 Thanks. I really love FCC and this is honestly the only thing that bugs me. Generally I find the site works really well.

**Comment by BKinahan** [comment]
Thank you @WRyan78 for the well-thought-out and carefully written report, please do write something like this for any problems you encounter with the site or challenges! 👍 

This issue has been resolved in the current beta version, where the pop up is a temporary message in the lower right corner of the page 😄 When the beta features go live the middle-of-the-page pop up will be no more.

For now it might help you to know that you can close the pop-up quickly with the `Escape` key, and this can even be done before the animation finishes. Also as the tests are run in your browser, it does not use up bandwidth to run them multiple times. I believe information is only transmitted when you submit the code to be saved to your profile (and your work-in-progress code is only saved locally, in your browser's local storage) 😄
