### ISSUE TITLE
Difficulty signing up for Slack

### ISSUE THREAD

**Issue by sarad1p1ty** [FreeCodeCamp/freecodecamp#1030]
Challenge http://www.freecodecamp.com/challenges/waypoint-join-our-chat-room has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

In Chrome, clicking on http://freecodecamp.com/api/slack link opens a new window, and I get an acknowledgment banner that says 'We've successfully requested an invite for you. Please check your email and follow the instructions from Slack.' but no email arrives.

My email address is correct in my profile.

**Comment by andreiamlm** [comment]
I am experiencing the same issue.

**Comment by BerkeleyTrue** [comment]
Thanks for reporting. This is a common issue we are having today. Please see #1014 for updates.
