### ISSUE TITLE
Confirm The Ending | Code works for all but one case. Pretty sure code is correct

### ISSUE THREAD

**Issue by shawnkauffman** [FreeCodeCamp/FreeCodeCamp#10305]
Challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=%0Afunction%20confirmEnding(str%2C%20target)%20%7B%0A%20%20var%20letter%20%3D%20str.substring(str.length%20-%201)%3B%0A%20%20var%20targetLetter%20%3D%20target.substring(target.length%20-%201)%3B%0A%20%20if%20(letter%20%3D%3D%3D%20targetLetter)%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%7D%0A%0AconfirmEnding(%22Walking%20on%20water%20and%20developing%20software%20from%20a%20specification%20are%20easy%20if%20both%20are%20frozen%22%2C%20%22specification%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function confirmEnding(str, target) {
  var letter = str.substring(str.length - 1);
  var targetLetter = target.substring(target.length - 1);
  if (letter === targetLetter) {
    return true;
  } else {
    return false;
  }
}

confirmEnding("Walking on water and developing software from a specification are easy if both are frozen", "specification");

```

**Comment by erictleung** [comment]
@shawnkauffman thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). 

It seems that you have misinterpreted the instructions. You want to check if the entire `target` string is at the end of the given`str` string. Hence, you want to "confirm the ending" of the `str`. I hope that helps. Closing as not an issue with the site. Happy coding!

**Comment by iMearner** [comment]
it think u did'nt get question properly

**Comment by pocahontas123** [comment]
function confirmEnding(str, target) {
				//Create a table to contain my String every words => [0] = "Open" [1] = "sesame"
				var table = []; table = str.split(" ");
				//Save the length of the table => 1 (-1 because it give 2 in this exemple ???)
				var tableLength = table.length-1;
				//Save my target length => 4
				var targetLength = target.length;
				//Save the last world from my array
				var content = table[tableLength];
				
				/*if "name" == "sename".substr(-3) => "name" == "name"
				//The key is to use my target by using his length to compare the right ammont of letters against the table last word
				//So if target = "name" and table give me "sesame" at first, i reduce 4 (name) from "sesame" in reverse(because '-') and it give name so it's equal
				*/
				if(target == content.substr(-targetLength)){
					return true;
				}
				return false;
			}

			confirmEnding("Open sesame", "same");

**Comment by texas2010** [comment]
@pocahontas123 
Please don't put your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
