### ISSUE TITLE
Title Case a Sentence

### ISSUE THREAD

**Issue by schoebli93** [FreeCodeCamp/FreeCodeCamp#10309]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Afunction%20titleCase(str)%20%7B%0A%20%20var%20lowerCase%20%3D%20str.toLowerCase()%3B%0A%20%20var%20ArrayOfStrings%20%3D%20lowerCase.split(%22%20%22)%3B%0A%20%20var%20ArrayOfSubstring%3B%0A%20%20var%20FirstElementOfSubstring%3B%0A%20%20var%20FinalString%20%3D%20%5B%5D%3B%0A%20%20console.log(lowerCase)%3B%0A%20%20console.log(ArrayOfStrings)%3B%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20(ArrayOfStrings.length)%3B%20i%2B%2B)%7B%0A%20%20%20%20ArrayOfSubstring%20%3D%20ArrayOfStrings%5Bi%5D.split(%22%22)%3B%0A%20%20%20%20ArrayOfSubstring.push(%22%20%22)%3B%0A%20%20%20%20FirstElementOfSubstring%20%3D%20ArrayOfSubstring.shift().toUpperCase()%3B%0A%20%20%20%20ArrayOfSubstring.unshift(FirstElementOfSubstring)%3B%0A%20%20%20%20console.log(ArrayOfSubstring)%3B%0A%20%20%20%20FinalString%20%2B%3D%20ArrayOfSubstring%3B%0A%20%20%20%20console.log(FinalString)%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20(FinalString.replace(%2F%2C%2Fgi%2C%20%22%22))%3B%0A%7D%0A%0AtitleCase(%22HERE%20IS%20MY%20HANDLE%20HERE%20IS%20MY%20SPOUT%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function titleCase(str) {
  var lowerCase = str.toLowerCase();
  var ArrayOfStrings = lowerCase.split(" ");
  var ArrayOfSubstring;
  var FirstElementOfSubstring;
  var FinalString = [];
  console.log(lowerCase);
  console.log(ArrayOfStrings);
  for(var i = 0; i < (ArrayOfStrings.length); i++){
    ArrayOfSubstring = ArrayOfStrings[i].split("");
    ArrayOfSubstring.push(" ");
    FirstElementOfSubstring = ArrayOfSubstring.shift().toUpperCase();
    ArrayOfSubstring.unshift(FirstElementOfSubstring);
    console.log(ArrayOfSubstring);
    FinalString += ArrayOfSubstring;
    console.log(FinalString);
  }
  
  return (FinalString.replace(/,/gi, ""));
}

titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");

```

**Comment by schoebli93** [comment]
Does anyone know why my code above wont let me pass the task?

**Comment by erictleung** [comment]
@schoebli93 thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: think about what this does to your final string -- `ArrayOfSubstring.push(" ");` Happy coding!

**Comment by sharadjob** [comment]
Can Someone suggest if there's a problem with this code 
I suppose it should be working perfectly fine?

` 
function titleCase(str){
var arr=str.split(" ");
  var str1="";
 //arr[1][0].toUpperCase();
for (var i=0;i<arr.length;i++){
  
  str1+=arr[i][0].toUpperCase()+arr[i].toLowerCase()+" ";
  
}
  arr=str1.split(" ");
  var r="";
  for(i=0;i<arr.length;i++){
    r=arr[i][1];
    arr[i]=arr[i].replace(r,"");
  }
  

return arr.join(" ");
}
titleCase("What eVer sTRNG gOeS hERe");
`
