### ISSUE TITLE
Test should ignore whitespace

### ISSUE THREAD

**Issue by BlauFeuer** [FreeCodeCamp/FreeCodeCamp#10318]
Challenge [Override All Other Styles by using Important](https://www.freecodecamp.com/challenges/override-all-other-styles-by-using-important#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%20%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20%23orange-text%20%7B%0A%20%20%20%20color%3A%20orange%20%3B%0A%20%20%7D%0A%20%20.pink-text%20%20%20%20%20%7B%0A%20%20%20%20color%3A%20pink%20!important%20%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20id%3D%22orange-text%22%20class%3D%22pink-text%20blue-text%22%20style%3D%22color%3A%20white%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace ;
    color: green;
  }
  #orange-text {
    color: orange ;
  }
  .pink-text     {
    color: pink !important ;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 id="orange-text" class="pink-text blue-text" style="color: white">Hello World!</h1>

```

Similar to #8511, test is not whitespace tolerant.

**Comment by erictleung** [comment]
@BlauFeuer thanks for the issue. Yes, the test should be able to accommodate for spaces.

[This line of code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/2574431fc26e8d7d669b2bc1102167d342b0f4c2/seed/challenges/01-front-end-development-certification/html5-and-css.json#L4670) needs to be changed so that the regex is changed so that it allows zero or more spaces between `!important` and the semicolon.

```diff
- /\\.pink-text\\s*?\\{[\\s\\S]*?color:.*pink.*!important;[^\\.]*\\}/g
+ /\\.pink-text\\s*?\\{[\\s\\S]*?color:.*pink.*!important\\s*;[^\\.]*\\}/g
```

**Comment by BlauFeuer** [comment]
This is my first attempt to request a pull for **FreeCodeCamp**, however I have previously done this 2 or 3 times since joining GitHUB a few months ago - if I do not qualify as a first-timer because of that experience, it was still good practice.  Thanks for taking a look at it.

**Comment by dhcodes** [comment]
@BlauFeuer just a heads up, your PR might get blocked because the branch name needs to start with fix/ or feature/ 

The contributing documentation is here: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md

**Comment by BlauFeuer** [comment]
@dhcodes To address guideline `#3`: Is there a way to rename a branch via GITHUB?  I'm somewhat aware that I don't know what I'm doing; I only successfully got to step `#2` of Contributing Guidelines. From there it all looks like jargon. I'm not sure how a "first-timer" could mange to follow all those guidelines.

**Comment by dhcodes** [comment]
@BlauFeuer You should be able to rename your current branch using:
`git branch -m new_branch` 
while on the branch you want to rename locally.

Then you can re-push your changes with a `git push -u origin fix/branch-name-here --force`.

As for the guidelines, I think they do a good job of providing a first-timer with a full git experience which can be helpful to someone just getting into contributing.
