### ISSUE TITLE
Off the Hook!

### ISSUE THREAD

**Issue by RoboMantis** [FreeCodeCamp/FreeCodeCamp#10310]
Off the hook message with broken button. im trying to get to the next challenge.
funny I completed this task went to next page. I came back to this page entered

```html
<style>
<h2 style="color:red">CatPhotoApp</h2>
<style>
```

because I thought I was on the next page challenge....
so clearly the question didnt need the `<style>` attributes.
so I deleted them and hit run to go to next  challenge. And off the hook message shows in green
with blank green button that is not clickable..

Observation button does not work, off the hook message.
so my hypothesis is because I entered extra code that was submitted I broke the button. 
Test by refreshing the page when extra code is submitted when original code is submitted if button does not work browser refresh with javascript. So after multiple times of not going forward should be automatic

#### Challenge Name

https://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%0A%3Ch2%20style%3D%22color%3Ared%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by oalhait** [comment]
This is a little bit hard to understand. Could you elaborate on what's happening without any html tags?

**Comment by erictleung** [comment]
@RoboMantis thanks for the issue. I've cleaned up your issue message to format correctly.

I was unable to reproduce your issue. The submit buttons and everything work fine for me. Can you add screenshots and more information, such as your browser type? That may help us diagnose the issue for you.

**Comment by texas2010** [comment]
@erictleung I think he talk about to click run button but his code is incorrect. that is why it wont accept to run.  it seem like this issue dont have a bug. since his code is incorrect.

I think he need to reset this challenge then take this challenge again.

**Comment by atjonathan** [comment]
Closing as stale.
