### ISSUE TITLE
indexOf() is not working properly in Mutations challenge

### ISSUE THREAD

**Issue by Sree-001** [FreeCodeCamp/FreeCodeCamp#10314]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```
#### Screenshot

`function mutation(arr) {
  var str=arr.join('');
  var teststr=str.toLowerCase();
  var len=arr[0].length;
  var tstr=arr[1].toLowerCase();
  var ans= teststr.indexOf(tstr,len);
  if(ans!==-1)
    return true;
  else 
    return false;
}

mutation(["Hello", "hey"]);`

**Comment by BKinahan** [comment]
Hi @Sree-001. Unfortunately your code is not correct, and will always return true for any valid input.

Please visit the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for help with the algorithm challenges before raising an issue related to specific code.

Thanks and happy coding!
