### ISSUE TITLE
"Target HTML Elements with Selectors Using jQuery" code does past test with single quotes

### ISSUE THREAD

**Issue by jdhines** [FreeCodeCamp/FreeCodeCamp#10315]
#### Challenge Name
[Target HTML Elements with Selectors Using jQuery](https://www.freecodecamp.com/challenges/target-html-elements-with-selectors-using-jquery)

#### Issue Description
The instructions say, "Additionally make sure to use $("button").addClass("animated bounce"); instead of $('button').addClass("animated bounce"); since single-quote selectors will not pass our tests."

However, this may be able to be removed since my tests passed using single quotes in the jQuery code.

#### Browser Information
* Browser Name, Version: Chrome, 52.0.2743.116
* Operating System: Mac OSX El Capitan

**Comment by dhcodes** [comment]
Confirmed.

**Comment by tertiaryidentifier** [comment]
Also confirmed.

**Comment by dhcodes** [comment]
I'll try to fix this up. Haven't done a PR in a bit.

**Comment by tertiaryidentifier** [comment]
@dhcodes , I don't particularly know why, but while jQuery might at points accept single quotes, best practice according to their documentation is to use double quotes for selectors. http://contribute.jquery.org/style-guide/js/#quotes

**Comment by oalhait** [comment]
I researched it a little bit, and it seems like using single quotes would cause an error in versions 1.6 and later of jQuery. Would it be a good idea to simply use a warning in the instructions saying "Don't use single quotes, they break your code under some situations"?

**Comment by dhcodes** [comment]
Based on the last two posts, I think we should update the test so it doesn't accept single quotes. I'm not sure what to do about the instructions but if the test is updated the current instructions would apply.

**Comment by sthodup1** [comment]
I believe some tests in later challenges fail if single-quotes are used so it may be better to keep all the tests consistent and not accept single-quotes in this case.

**Comment by oalhait** [comment]
Yep, I'm on it! Pull request in a few hrs.

**Comment by chakrihacker** [comment]
Hi where should the test to be written, I want to make a PR

**Comment by oalhait** [comment]
Sorry @chakrihacker , didn't see this. just finished mine!
