### ISSUE TITLE
Semicolon

### ISSUE THREAD

**Issue by aescaes** [FreeCodeCamp/FreeCodeCamp#10312]
Challenge [Condense arrays with reduce](https://www.freecodecamp.com/challenges/condense-arrays-with-reduce#?solution=%0Avar%20array%20%3D%20%5B4%2C5%2C6%2C7%2C8%5D%3B%0Avar%20singleVal%20%3D%200%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AsingleVal%20%3D%20array.reduce(function(previousVal%2C%20currentVal)%20%7B%0A%20%20return%20previousVal%20%2B%20currentVal%0A%7D%2C%200)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var array = [4,5,6,7,8];
var singleVal = 0;

// Only change code below this line.

singleVal = array.reduce(function(previousVal, currentVal) {
  return previousVal + currentVal
}, 0);

```

**Comment by haih** [comment]
hi @aescaes , what is your problem?

**Comment by erictleung** [comment]
@aescaes thanks for the issue. Yes, if you enter your code into the editor, it will flag is a syntax error but still run. JavaScript doesn't actually require semi-colons everywhere, only in certain places. However, for consistency and to help prevent errors, we strongly suggest that semi-colons be used. Thanks and happy coding!
