### ISSUE TITLE
incorrect html syntax will pass this waypoint

### ISSUE THREAD

**Issue by digitaldak** [FreeCodeCamp/FreeCodeCamp#1031]
Challenge http://www.freecodecamp.org/challenges/waypoint-add-font-awesome-icons-to-all-of-our-Buttons has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

So there are a few things at issue here:
1) incorrect syntax on the i's will pass, ie you never have to close them...
2)last test isn't checking correctly for the end of the i elements (```html </i>```) as it's checking for ```</i```
``` assert(editor.match(/<\\/i>/g) && editor.match(/<\\/i/g).length > 2 ```
should probably be ``` assert(editor.match(/<\\/i>/g) && editor.match(/<\\/i/g>).length > 2 ``` -- note last part now has a > in it

The first part, well, it needs some evaluation I think on how to fix it.

![waypoint-add-font-awesome-icons-to-all-of-our-buttons](https://cloud.githubusercontent.com/assets/3256176/8268210/e584954e-1731-11e5-934e-cf69f375d640.png)

**Comment by benschenker** [comment]
Thanks again @digitaldak!

Confirmed this is still an issue, I just reproduced it.
