### ISSUE TITLE
Can't get my code camp and github to connect

### ISSUE THREAD

**Issue by Brandon1982** [FreeCodeCamp/FreeCodeCamp#10313]
Can't get my code camp and github to connect and I've emailed free code camp since sunday and still waiting for the issue to get sorted pls could someone help

**Comment by SamAI-Software** [comment]
@Brandon1982 please, provide more details including your Free Code Camp account name.

**Comment by raisedadead** [comment]
@Brandon1982 
You have already connected GitHub to your account here:
https://www.freecodecamp.com/Brandon1982

By any chance did you sign up once again (using email)?

**Comment by atjonathan** [comment]
Closing as stale. Please email team at freecodecamp dot com
