### ISSUE TITLE
Adding description for form-controls

### ISSUE THREAD

**Issue by luongthomas** [FreeCodeCamp/FreeCodeCamp#10320]
#### Challenge Name

https://www.freecodecamp.com/challenges/style-text-inputs-as-form-controls

#### Issue Description

This challenge would be a lot more informative if a description of what adding the form-control class to the input field actually does.  Something along the lines of:

All textual [input], [textarea], and [select] elements with class [.form-control] have a width of 100%.

**Comment by atjonathan** [comment]
This challenge is currently quite short and it's defiantly worth adding an explanation here.

**To First Timer:**
You will need to add the sentence under [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/bootstrap.json#L1643) line. Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

> **Note:** You can only submit a pull request for this issue if you are new and haven't submitted one before. Hence the issue label `first-timers-only` :stuck_out_tongue_winking_eye:

**Comment by erictleung** [comment]
The code you'll need to add specifically is

```
"All textual <code>&lt;input&gt;</code>, <code>&lt;textarea&gt;</code>, and <code>&lt;select&gt;</code> elements with the class <code>.form-control</code> have a width of 100%."
```

It should render as

> All textual <code>&lt;input&gt;</code>, <code>&lt;textarea&gt;</code>, and <code>&lt;select&gt;</code> elements with the class <code>.form-control</code> have a width of 100%.

**Comment by n-white** [comment]
Hey there. I'm a first-timer interested in getting started with contributing to Free Code Camp. I will submit a PR for this issue. Thanks!

**Comment by chakrihacker** [comment]
Hey What about tests ??
Tests should be added for each input.

**Comment by usersaurabh** [comment]
having issue in style-text-inputs-as-form-controls
just give a class="form-control" to 
1)  <form action="/submit-cat-photo" class="form-control">
2)   <div class="row" class="form-control"> before your checkbox's 1st div i.e. <div class="col-xs-4">
and finally add here
3) <input type="text" placeholder="cat photo URL" class="form-control" required>

**Comment by usersaurabh** [comment]
having issue in style-text-inputs-as-form-controls
just give a class="form-control" to 

`1)  <form action="/submit-cat-photo" class="form-control">`

`2) <div class="row" class="form-control">`
before your checkbox's 1st div `i.e.  <div class="col-xs-4">`

and finally add here
3)`<input type="text" placeholder="cat photo URL" class="form-control" required>`
