### ISSUE TITLE
3rd Test text missing "/" on closing element causing test line to not highlight correctly

### ISSUE THREAD

**Issue by digitaldak** [FreeCodeCamp/FreeCodeCamp#1032]
Challenge http://www.freecodecamp.org/challenges/waypoint-style-text-inputs-as-form-controls has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Current test assert:
``` "assert($('input[type=\\'text\\']').hasClass('form-control'), 'Give the text <code>input<code> in your form the class \"form-control\".')",```
Should be:
``` "assert($('input[type=\\'text\\']').hasClass('form-control'), 'Give the text <code>input</code> in your form the class \"form-control\".')",```

![waypoint-style-text-inputs-as-form-controls](https://cloud.githubusercontent.com/assets/3256176/8268258/7ee3d46a-1733-11e5-92bc-96b741340392.png)

**Comment by bugron** [comment]
Seems this issue is solved and can be closed.
