### ISSUE TITLE
Mistake in challenge requirements

### ISSUE THREAD

**Issue by wunderkid94** [FreeCodeCamp/FreeCodeCamp#10326]
#Challenge  [Pig Latin](https://www.freecodecamp.com/challenges/pig-latin#?solution=%0Afunction%20translatePigLatin(str)%20%7B%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20var%20newStr%20%3D%20%22%22%3B%0A%20%20%0A%20%20arr%20%3D%20str.split(%22%22)%3B%0A%20%20%0A%20%20if(arr%5B0%5D%3D%3D%3D%22a%22%20%7C%7C%20arr%5B0%5D%3D%3D%3D%20%22e%22%20%7C%7C%20arr%5B0%5D%3D%3D%3D%20%22i%22%20%7C%7C%20arr%5B0%5D%3D%3D%3D%22o%22%20%7C%7C%20arr%5B0%5D%3D%3D%3D%22u%22)%7B%0A%20%20%20%20newStr%20%3D%20arr.join(%22%22)%20%2B%20%22way%22%3B%0A%20%20%7D%0A%20%20else%20%7B%0A%20%20%20%20arr.push(arr%5B0%5D)%3B%0A%20%20arr.shift()%3B%0A%20%20newStr%20%3D%20arr.join(%22%22)%20%2B%20%22ay%22%3B%0A%20%20%7D%0A%20%20%20%20return%20newStr%3B%20%20%0A%7D%0A%0AtranslatePigLatin(%22glove%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**translatePigLatin("glove") should return "oveglay".**

My code:
```javascript

function translatePigLatin(str) {
  var arr = [];
  var newStr = "";
  
  arr = str.split("");
  
  if(arr[0]==="a" || arr[0]=== "e" || arr[0]=== "i" || arr[0]==="o" || arr[0]==="u"){
    newStr = arr.join("") + "way";
  }
  else {
    arr.push(arr[0]);
  arr.shift();
  newStr = arr.join("") + "ay";
  }
    return newStr;  
}

translatePigLatin("glove");

```

**Comment by BKinahan** [comment]
Hi @wunderkid94. The mistake is in your code, not the test 😄 

Note that the instructions say
>Pig Latin takes the first consonant **(or consonant cluster)** of an English word, moves it to the end of the word and suffixes an "ay".

The first consonant cluster of `"glove"` is `"gl"`, so the correct output is `"oveglay"` as the test message suggests.

Remember to visit the [HelpJavaScript](https://gitter.im/FreeCodeCamp/HelpJavaScript) chat room if you're stuck on an algorithm challenge before raising an issue.

Happy coding!

**Comment by Aristekrat** [comment]
The instructions should be rewritten to say that when there is a consonant cluster the cluster should be moved back. It's confusing as it's written now.
