### ISSUE TITLE
Zoom Issue. My web Browser is 100% on Zoom. Still unable to complete the test.

### ISSUE THREAD

**Issue by cleancode888** [FreeCodeCamp/FreeCodeCamp#10327]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by BKinahan** [comment]
Hi @cleancode888, could you please provide more information about your issue, such as the challenge which you are having a problem with and the code you have so far?

Also remember to visit the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for assistance with writing code before raising an issue.

Happy coding!

**Comment by cleancode888** [comment]
Hi @BKinahan ,
Thanks for quick revert.

Please refer to the screenshot, I am unable to complete the test. My Image width is 100px and the Browser is at 100% but when I run my test, it shows the same error: **Your image should be 100 pixels wide. Browser zoom should be at 100%.**

**Comment by BKinahan** [comment]
I can't see any code or screenshot in your post, unfortunately. You can edit the original post to add them if you like; it's possible there is some other error in your code which prevents the test from passing.

**Comment by cleancode888** [comment]
<style>
  .smaller-large {
    width: 100px;
  }
 

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat"alt="A cute orange cat lying on its back">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by cleancode888** [comment]
I did it. You were right; there was an error in my code. Sorry for this. I am just a beginner :+1:
