### ISSUE TITLE
Blue

### ISSUE THREAD

**Issue by mrlazos** [FreeCodeCamp/FreeCodeCamp#10323]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20%3Ch2%7Bcolor%3A%20blue%3B%7D%3ECatPhotoApp%3C%2Fstyle%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-N930P Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.2 Chrome/44.0.2403.133 Mobile Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  <h2{color: blue;}>CatPhotoApp</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by erictleung** [comment]
@mrlazos as the @VarCI-bot has pointed out, GitHub is not the place for coding help. In your previous issue, you mentioned that you have tried the chat room and with no response. We realize this can be frustrating but you have to patient. The rooms do get crowded but there are way more people there willing to help that you might imagine. If no one responds, you can always tag me in your question with `@erictleung` at the beginning of your message and I can respond there.

A hint for you to solve this challenge would be to read the instructions again to see if you understand what the challenge is asking for. Happy coding!
