### ISSUE TITLE
Goals are contradictory 

### ISSUE THREAD

**Issue by marienhof** [FreeCodeCamp/FreeCodeCamp#10338]
Remove all the backslashes (\)
You should have two single quotes ' and four double quotes "
Only remove the backslashes \ used to escape quotes.

Challenge [Quoting Strings with Single Quotes](https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes#?solution=%0Avar%20myStr%20%3D%20%22%3Ca%20href%3D'http%3A%2F%2Fwww.example.com'%20target%3D%22_blank%22%3ELink%3C%2Fa%3E%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G34 Safari/601.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "<a href='http://www.example.com' target="_blank">Link</a>";



```

**Comment by erictleung** [comment]
@marienhof thanks for the issue. I think we've had issues with this in the past (e.g. https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8400). 

The last test message could be rewritten to something like this

> Change the string from double to single quotes but keep double quotes for the inner quotes.

**Comment by dhcodes** [comment]
@erictleung I think the third test should be combined with the first test if possible. The third test implies there are backslashes in the editor that don't escape quotes but there aren't. So if you remove all the backslashes (per the first test), you are fulfilling the third test.

**Comment by erictleung** [comment]
I like @dhcodes idea. Let's merge the first and third test into one into something like this.

```js
"assert(!/\\\\/g.test(code) && myStr === '<a href=\"http://www.example.com\" target=\"_blank\">Link</a>', 'message: Remove all the <code>backslashes</code> (<code>\\</code>)');",
```

I think that should still make it clear enough on what needs to be done to complete the challenge. If anyone finds a hole in the challenge, please comment. Otherwise, I'll mark this `Help Wanted`.

**Comment by dhcodes** [comment]
Updated via the PR above. Thanks for doing the hard part @erictleung

**Comment by BariqFitri** [comment]
i got it...
var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';

**Comment by BariqFitri** [comment]
![tuto](https://cloud.githubusercontent.com/assets/21375993/18336882/c9665f50-75bd-11e6-8d0b-b3f5c7a15d6f.PNG)

**Comment by BariqFitri** [comment]
Yeahhh i got it!!!
![tuto](https://cloud.githubusercontent.com/assets/21375993/18336890/e7781402-75bd-11e6-8ba4-e3198a054d1b.PNG)
