### ISSUE TITLE
Not clear what escaping is

### ISSUE THREAD

**Issue by marienhof** [FreeCodeCamp/FreeCodeCamp#10337]
Challenge [Quoting Strings with Single Quotes](https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G34 Safari/601.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "<a href=\'http://www.example.com\' target="_blank">Link</a>";



```

**Comment by erictleung** [comment]
@marienhof thanks for the issue. The need to escape is to invoke an alternative interpretation of the character immediately after the backslash. The next challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings) goes over more escape characters. Even this challenge doesn't explain *why* you escape characters.

We could add in another snippet in the "Escape Sequences in Strings" challenge along the lines of

> There are two reasons to escaping characters. First is to allow you to use characters you might not otherwise be able to type out, such as a backspace. Second is to allow you to represent multiple quotes in a string without JavaScript misinterpreting what you mean. We learned this in the previous challenge.

cc/ @FreeCodeCamp/issue-moderators non-issue or something to add?

**Comment by dhcodes** [comment]
@erictleung I think the [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings) challenge which is right before this one combined with the two above does a pretty good job already but your explanation does seem to fit well with Escape Sequences in Strings. I'm indifferent.

**Comment by marienhof** [comment]
I believe adding Eric's explanation will be beneficial.

**Comment by dhcodes** [comment]
Let's go ahead and add @erictleung's snippet.
