### ISSUE TITLE
Reverse the order of completed projects on users' page

### ISSUE THREAD

**Issue by valmassoi** [FreeCodeCamp/FreeCodeCamp#10335]
#### Issue Description

As someone who has completed the three certificates I would like to use my `fcc.com/username` in my portfolio, but I don't like sending people there because of the order of projects. I think it would be better to have the most recent at the top (reverse chronological), instead the weaker projects that were completed at the beginning. Anyone else feel this way?

**Comment by marhyorh** [comment]
@valmassoi Yeah, it would be a lot better having the latest projects at the top. I agree :raised_hands:

**Comment by Bouncey** [comment]
\cc @FreeCodeCamp/moderators Is this a change we wan to make?

**Comment by dhcodes** [comment]
I'm onboard. Might want to run it by Quincy though.

**Comment by atjonathan** [comment]
@QuincyLarson, tagging for approval.

**Comment by QuincyLarson** [comment]
@valmassoi yes - I agree with your reasoning this would be good, as @dhcodes and @marhyorh have. We plan to ship staging as soon as @BerkeleyTrue resolves a few key issues. So please make this change off of the staging branch. 

Thanks again for pointing out that this is indeed a more logical way to present these data.
