### ISSUE TITLE
Not getting Slack invite

### ISSUE THREAD

**Issue by gdinola** [FreeCodeCamp/freecodecamp#1033]
Challenge http://www.freecodecamp.com/challenges/waypoint-join-our-chat-room has an issue. Please describe how to reproduce it, and include links to screen shots if possible.
I use Chrome and I have been waiting on the email invitation to join Chat but have not received anything.  
I am at this URL:  http://www.freecodecamp.com/challenges/waypoint-join-our-chat-room.
When I click on link (http://freecodecamp.com/api/slack), I get this message (We've successfully requested an invite for you. Please check your email and follow the instructions from Slack.) but I have yet to receive an email since yesterday.
I am anxious to start learning and using FreeCodeCamp.
Thank you for your assistance.
Gina.

**Comment by gdinola** [comment]
PS:  I have checked my Junk folders and nothing is there.

**Comment by BerkeleyTrue** [comment]
Thanks for reporting. This is a common issue we are having today. Please see #1014 for updates.

**Comment by mcne65** [comment]
There is no Slack channel for FreeCodeCamp worldwide. Just Gitter?
