### ISSUE TITLE
Further clarify definition of "even" in Targeting Even Elements in jQuery

### ISSUE THREAD

**Issue by ayrenay** [FreeCodeCamp/FreeCodeCamp#10336]
The wording of the challenge is clearer than what it appears to have said previously (based on other issues), but it could be further improved with something like the following:

Either -
>Try selecting all the ```:even``` elements and giving them the classes of animated and shake.

Or -
> Try selecting all the odd-numbered elements and giving them the classes of animated and shake.

Or -
>Note that jQuery is zero-indexed. In a list of elements, like ```h1 h2 h3 h4 h5 h6```, ```h1``` is the 0th element, and the first, second, and third elements are ```h2 h4 h6```.

Even knowing what 'zero-indexed' means before beginning this challenge, I still managed to misinterpret this. Additionally, if this challenge was someone's first introduction to zero-based indexes, 
a short but concrete example could certainly be helpful.

Challenge [Target Even Numbered Elements Using jQuery](https://www.freecodecamp.com/challenges/target-even-numbered-elements-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
    $("#right-well").children().css("color", "orange");
    $("#left-well").children().css("color", "green");
    $(".target:nth-child(2)").addClass("animated bounce");
    $(".target:even").addClass("animated shake");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by dhcodes** [comment]
@ayrenay Thanks for submitting this. We have updated the instructions to read "Even-numbered is defined here with a zero-index in mind" but the change has not been pushed to the live site yet. It will be updated the next time the live site is rebased. Issue #10127 is where a user recommended a similar update if you want to read the discussion there.

**Comment by ayrenay** [comment]
Yes - I read through that one, but didn't catch that. Apologies!

**Comment by dhcodes** [comment]
@ayrenay No problem. It was something that needed improving for sure.
