### ISSUE TITLE
Correct spacing typo between "if" and "you"

### ISSUE THREAD

**Issue by jbsea** [FreeCodeCamp/FreeCodeCamp#10339]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%20%3D%20%22I%20am%20a%20%2F%22double%20quoted%2F%22%20string%20inside%20%2F%22double%20quotes%2F%22.%22%3B%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

In the instructions section, there appears to be no space between `if` and `you` in this text: 
"...so that *if*you were to print..."

Just need the space to render between these 2 words. 

<img width="347" alt="screen shot 2016-08-25 at 12 44 26 am" src="https://cloud.githubusercontent.com/assets/17692415/17960834/28e76620-6a5d-11e6-9dbd-bcaf87c8dbce.png">

**Comment by BKinahan** [comment]
I think this can be resolved by simply removing the emphasis on `if` (it is not used in a similar case earlier in the instructions), since the resulting string will likely be logged to the console for the user anyway in upcoming changes (see #9363).

**Comment by BlauFeuer** [comment]
That's not an uncommon problem with italics - typically that's where the use of an em-space (] [) is handy.

Just removing the the emphasis, which I find slightly distracting anyway, solves the visual problem.

**Comment by erictleung** [comment]
We can go ahead and remove the `<em>` tags on the "if". I add them there because this challenge had lots of confusion on interpreting what that last string printed to the console actually means.

**Comment by Manish-Giri** [comment]
I'll take this up.

**Comment by dpcleveland** [comment]
Haven't seen this one updated. I can implement this fix if you haven't already @Manish-Giri

**Comment by Manish-Giri** [comment]
@dpcleveland sorry, it's almost done. Just need to submit the PR.

**Comment by dpcleveland** [comment]
@Manish-Giri No worries! Sounds good

**Comment by BariqFitri** [comment]
var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; // Change this line

**Comment by texas2010** [comment]
@BariqFitri 
This place is not for put solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
