### ISSUE TITLE
The link to send Slack invitation not working

### ISSUE THREAD

**Issue by tsega** [FreeCodeCamp/freecodecamp#1034]
Challenge http://www.freecodecamp.com/challenges/waypoint-join-our-chat-room has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

After making sure that I have an email address set for my account I clicked on the link to send me the slack chat invitation email but I never got it. I use gmail and it's pretty much the most accessible email provider there is out there. I'm guessing the email is not being sent at all.

**Comment by BerkeleyTrue** [comment]
Thanks for reporting. This is a common issue we are having today. Please see #1014 for updates.
