### ISSUE TITLE
Duplicate Account Issues

### ISSUE THREAD

**Issue by Brandon1982** [FreeCodeCamp/FreeCodeCamp#10343]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by erictleung** [comment]
@Brandon1982 apologies for the account issues on FreeCodeCamp. Tagging @QuincyLarson and @BerkeleyTrue to help.

**Comment by BerkeleyTrue** [comment]
@Brandon1982 Please send a support email to team@freecodecamp.com for account issues.


Happy Coding
