### ISSUE TITLE
Escape Sequences Challenge Not Working.

### ISSUE THREAD

**Issue by ReadyDoMe** [FreeCodeCamp/FreeCodeCamp#10350]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D%22FirstLine%5Cn%5CSecondLine%5C%5CrThirdLine%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr="FirstLine\n\SecondLine\\rThirdLine";



```

**Comment by glc3344** [comment]
You have to escape the backslashes as well.  

code should read:
`var myStr="FirstLine\n\\SecondLine\\\rThirdLine";`
