### ISSUE TITLE
Code which must be changed is below the "do not change code below this line".

### ISSUE THREAD

**Issue by inhll** [FreeCodeCamp/FreeCodeCamp#10357]
Challenge [Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%0A%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20lookup%20%3D%20%7B%0A%20%20%20%20%22alpha%22%3A%22Adams%22%2C%0A%20%20%20%20%22bravo%22%3A%22Boston%22%2C%0A%20%20%20%20%22charlie%22%3A%22Chicago%22%2C%0A%20%20%20%20%22delta%22%3A%22Denver%22%2C%0A%20%20%20%20%22echo%22%3A%22Easy%22%2C%0A%20%20%20%20%22foxtrot%22%3A%22Frank%22%2C%0A%20%20%20%20%22%22%3Aundefined%0A%20%20%7D%3B%0A%20%20%0A%20%20return%20lookup%5Bval%5D%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22alpha%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function phoneticLookup(val) {
  var result = "";
  
  // Only change code below this line
  var lookup = {
    "alpha":"Adams",
    "bravo":"Boston",
    "charlie":"Chicago",
    "delta":"Denver",
    "echo":"Easy",
    "foxtrot":"Frank",
    "":undefined
  };
  
  return lookup[val]; //This code is originally found below as follows:

  // Only change code above this line
  return result;          // This is where the return is initially.
                                // Tests can only be passed if return is modified.
}

// Change this value to test
phoneticLookup("alpha");

```

**Comment by erictleung** [comment]
@inhll thanks for the issue. Yes, the challenge can be completed as your code describes but the instructions point to you on how to complete the challenge:

>  Use it to lookup `val` and assign the associated string to the `result` variable.

This makes for consistency based on the original seed code for the challenge and focusing more on using objects for lookups, rather than the function aspects of the code. I hope you understand. Closing as a non-issue. Happy coding!

**Comment by BariqFitri** [comment]
Check it out!!!
![toto7](https://cloud.githubusercontent.com/assets/21375993/18341885/bd44d582-75de-11e6-96c4-684cc30ae7a1.PNG)

**Comment by inhll** [comment]
Aw yeah! A+ @BariqFitri!
