### ISSUE TITLE
Seek and Destroy Bug

### ISSUE THREAD

**Issue by schoebli93** [FreeCodeCamp/FreeCodeCamp#10354]
Challenge [Seek and Destroy](https://www.freecodecamp.com/challenges/seek-and-destroy#?solution=%0Afunction%20destroyer(arr)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0A%20%20return%20arr%3B%0A%7D%0A%0Adestroyer(%5B1%2C%202%2C%203%2C%201%2C%202%2C%203%5D%2C%202%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function destroyer(arr) {
  // Remove all the values
  return arr;
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

```

My text:
Where are the arguments that should be passed to the function? In my opinion, it should have at least tree more variables besides arr

**Comment by erictleung** [comment]
@schoebli93 please take a look at the "helpful links" in the "Seek and Destroy" challenge page, especially the ["Arguments object"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) link. That should clear any confusion. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
