### ISSUE TITLE
Did not get any email invite

### ISSUE THREAD

**Issue by sandeesaripalli** [FreeCodeCamp/freecodecamp#1035]
Challenge http://www.freecodecamp.com/challenges/waypoint-join-our-chat-room has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I did not get any invite to my mail from slack to join the team.

please help

**Comment by BerkeleyTrue** [comment]
We hit an undocumented hard limit with Slack. Please see #1014 and the blog post explaining our move. http://blog.freecodecamp.com/2015/06/so-yeah-we-tried-slack-and-we-deeply-regretted-it.html

We will be updating the challenge shortly with new instruction on how to signup for Gitter, but you can see the video here https://vimeo.com/131321596

Again we are sorry for the inconvenience and hope you have an awesome time with our new Gitter room.
