### ISSUE TITLE
Russian Translation of Getting Started

### ISSUE THREAD

**Issue by rfprod** [FreeCodeCamp/FreeCodeCamp#10355]
- [x] Learn how Free Code Camp Works
- [x] Create a Github Account and Join our Chat Rooms
- [x] Configure your Code Portfolio
- [x] Join a Free Code Camp Group in Your City
- [x] Read Coding News on our Medium Publication
- [x] Learn What to Do If You Get Stuck

**Comment by texas2010** [comment]
this issue suppose to be on this repo https://github.com/FreeCodeCamp/TranslationExpansion/issues

**Comment by rfprod** [comment]
@texas2010 will keep this in mind for future
