### ISSUE TITLE
Code works locally but not in the code editor on freewebcode!

### ISSUE THREAD

**Issue by SushiWashi** [FreeCodeCamp/FreeCodeCamp#10359]
Challenge [Repeat a string repeat a string](https://www.freecodecamp.com/challenges/repeat-a-string-repeat-a-string#?solution=function%20repeatStringNumTimes(str%2C%20num)%20%7B%0A%0Aif(num%20%3E%3D%200)%20%7B%0A%20%20%0A%20%20for(var%20x%20%3D%200%3B%20x%20%3C%20num%3B%20x%2B%2B)%20%7B%0A%09console.log(str)%3B%0A%20%20%7D%20%0A%20%20%0A%20%20%7D%20else%20%7B%0A%20%20%20console.log(%22%22)%3B%0A%20%20%7D%0A%7D%0A%20%20%0ArepeatStringNumTimes(%22*%22%2C%203)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function repeatStringNumTimes(str, num) {

if(num >= 0) {
  
  for(var x = 0; x < num; x++) {
	console.log(str);
  } 
  
  } else {
   console.log("");
  }
}
  
repeatStringNumTimes("*", 3);
```

**Comment by magikid** [comment]
I don't believe the challenge it the issue.  I recommend looking for help with your code in the [chatroom](https://gitter.im/FreeCodeCamp/FreeCodeCamp).

**Comment by erictleung** [comment]
@SushiWashi you'll need to return a string of some sort, rather than output it to the console.

> Repeat a given string (first argument) num times (second argument). Return an empty string if num is not a positive number.

Please consult the help chatrooms before making an issue on GitHub. Happy coding!
