### ISSUE TITLE
Need to Clarify instructions

### ISSUE THREAD

**Issue by mejiaadonay** [FreeCodeCamp/FreeCodeCamp#10362]
Challenge [Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%0A%2F%2F%20Setup%0Afunction%20phoneticLookup%28val%29%20%7B%0A%20%20var%20result%20%3D%20%22%20%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20lookup%20%3D%20%7B%0A%20%20%22alpha%22%20%3A%20%22Adams%22%2C%0A%20%20%22bravo%22%20%3A%20%22Boston%22%2C%0A%20%20%22charlie%22%20%3A%20%22Chicago%22%2C%0A%20%20%22delta%22%20%3A%20%22Denver%22%2C%0A%20%20%22echo%22%20%3A%20%22Easy%22%2C%0A%20%20%22foxtrot%22%20%3A%20%22Frank%22%0A%7D%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20lookup%5Bval%5D%3B%20%2F%2F%20%3C---%20I%20had%20have%20to%20change%20this%20line%20of%20code%20after%20some%20search.%20There%20should%20be%20more%20instruction%20I%20think%20so.%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%20%20%20%0AphoneticLookup%28%22charlie%22%29%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript

// Setup
function phoneticLookup(val) {
  var result = " ";  // This var ended up useless

  // Only change code below this line
var lookup = {
  "alpha" : "Adams",
  "bravo" : "Boston",
  "charlie" : "Chicago",
  "delta" : "Denver",
  "echo" : "Easy",
  "foxtrot" : "Frank"
};
  // Only change code above this line
  return lookup[val]; // <--- I had have to change this line of code after some search. There should be more instruction I think so.
}

// Change this value to test   
phoneticLookup("charlie");

```

**Comment by erictleung** [comment]
@mejiaadonay thanks for the issue but I think the instructions sufficiently describe how to complete the challenge.

> Use it to lookup `val` and **assign the associated string to the `result` variable**.

That is why there is a `var result = "";` at the beginning. 

[Someone](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10357) has brought this exact same issue previously. This is my response to why there is nothing wrong with the challenge and that you shouldn't need to ignore the comments saying only change the code within certain boundaries.

> "This makes for consistency based on the original seed code for the challenge and focusing more on using objects for lookups, rather than the function aspects of the code."

cc/ @FreeCodeCamp/issue-moderators I'm willing to open discussion on the matter considering it has been brought up twice now. Second opinions on the matter?

**Comment by c-s-avage** [comment]
this is now fixed for me.

**Comment by raisedadead** [comment]
Nope, I agree that the instructions are sufficient. Closing.
