### ISSUE TITLE
The test case are incomplete and do not check rotation from 'F' to 'S'

### ISSUE THREAD

**Issue by mustafasiddiqui** [FreeCodeCamp/FreeCodeCamp#10365]
#### Challenge Name

https://www.freecodecamp.com/challenges/caesars-cipher

#### Issue Description

If the solution is complete except for the logic to rotate from 'F' to 'S'  the tests will still pass.

I suggest that instead of using "GUR DHVPX OEBJA QBT WHZCRQ BIRE GUR YNML SBK." for "THE QUICK BROWN DOG JUMPED OVER THE LAZY FOX."  we can use:

"GUR DHVPX OEBJA QBT WHZCF BIRE GUR YNML SBK." for "THE QUICK BROWN DOG JUMPS OVER THE LAZY FOX."

#### Your Code

```js
 
 function rot13(str) { // LBH QVQ VG!
  var result ="";
  var lookup = {
    "A":"N",
    "B":"O",
    "C":"P",
    "D":"Q",
    "E":"R",
    "F":"N",
    "G":"T",
    "H":"U",
    "I":"V",
    "J":"W",
    "K":"X",
    "L":"Y",
    "M":"Z",
    "N":"A",
    "O":"B",
    "P":"C",
    "Q":"D",
    "R":"E",
    "S":"F",
    "T":"G",
    "U":"H",
    "V":"I",
    "W":"J",
    "X":"K",
    "Y":"L",
    "Z":"M"
  };
  for (var i=0; i<str.length;i++){
    var currentVal=str[i];
    var newVal=currentVal;
    if (lookup[currentVal]!=undefined){
      newVal=lookup[currentVal];
    }
   
    result+=newVal;
  }
  
  console.log("result: "+result);
  return result;
}

// Change the inputs below to test
rot13("SERR PBQR PNZC");
rot13("THE QUICK BROWN DOG JUMPS OVER THE LAZY FOX.");
rot13("GUR DHVPX OEBJA QBT WHZCF BIRE GUR YNML SBK.");
 
```

**Comment by BKinahan** [comment]
It is a bit odd that the test case seems to have been added as a phrase that contains all 26 letters of the English alphabet, but doesn't.

The popular pangram is correctly written as
> The quick brown fox jumps over the lazy dog.

**Comment by erictleung** [comment]
@BKinahan that's fine by me to fix the pangram so as to cover all possible cases the cipher function must decode.

**Comment by wjhurley** [comment]
I'd like to work on this issue.

**Comment by jhuynh85** [comment]
Is someone working on this issue? If not I'd like to take a crack at it

**Comment by erictleung** [comment]
@jhuynh85 go for it!
