### ISSUE TITLE
Minor grammar mistake.

### ISSUE THREAD

**Issue by wcountiss** [FreeCodeCamp/freecodecamp#1036]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-text-field has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

![grammar](https://cloud.githubusercontent.com/assets/7219453/8270012/e4672916-1794-11e5-8f75-5bcb2e4fe6ce.png)

should read, ' Your app should have a text field input element. '   : not 'an'

**Comment by NatashaHaggard** [comment]
Fixed, created a pull request - https://github.com/NatashaHaggard/freecodecamp/tree/NatashaHaggard-1036

**Comment by NatashaHaggard** [comment]
Updating pull request link - https://github.com/FreeCodeCamp/freecodecamp/pull/1073
