### ISSUE TITLE
Infinite loop - cannot reset challenge

### ISSUE THREAD

**Issue by atabas** [FreeCodeCamp/FreeCodeCamp#10377]
#### Challenge Name
https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers

#### Issue Description
While trying out this challenge, I managed to create an infinite loop by mistake. However, the challenge is now frozen and I cannot reset it. I've tried disabling Javascript through Content Settings in Chrome and clicking Reset. When I re-enable Javascript again, the old code with the infinite loop is still there. How can I reset the challenge and re-attempt it?

**Comment by erictleung** [comment]
@atabas you can try disabling the auto-run by editing the URL shown here https://github.com/freecodecamp/freecodecamp/wiki/FreeCodeCamp-Disable-Code-Autorun. I hope that helps.
