### ISSUE TITLE
Increment a Number with ++

### ISSUE THREAD

**Issue by mujtabahs** [FreeCodeCamp/FreeCodeCamp#10376]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=%0Avar%20myVar%20%3D%2088%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%2B%2B%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
In the instructions, it says that the variable myVar should have value 88, but when I assign it a value of 88, it gives an error. When the variable is assigned a value of 87, it runs properly.
var myVar = 88;

// Only change code below this line
myVar++;


```

**Comment by BKinahan** [comment]
Hi @mujtabahs. If you take a look at the instructions you will see that the `++` operator will increment the variable, so in your code `myVar` ends up with the value `89`. If you have any further questions, please visit the [Help chat room](https://gitter.im/FreeCodeCamp/Help).

Happy coding!
