### ISSUE TITLE
Exact Change Challenge

### ISSUE THREAD

**Issue by interglobalmedia** [FreeCodeCamp/FreeCodeCamp#10375]
#### Challenge Name

https://www.freecodecamp.com/challenges/exact-change

#### Issue Description

Can't paste (or do anything else) because page is frozen. I think I created some kind of infinite loop when playing with the code, and would love it to be reset please. Thanks!
 

#### Browser Information

Chrome

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
```

**Comment by BKinahan** [comment]
Follow the steps [here on the forum](forum.freecodecamp.com/t/disable-code-auto-run-on-free-code-camp/19511) to disable code auto-run.

Please remember to visit the forum or [help chat room](https://gitter.im/FreeCodeCamp/Help) when you have a problem with your code; issues are for bugs with the challenges or website.

Happy coding!
