### ISSUE TITLE
Validation Fail

### ISSUE THREAD

**Issue by wcountiss** [FreeCodeCamp/FreeCodeCamp#1037]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-form-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

![validation-fail](https://cloud.githubusercontent.com/assets/7219453/8270023/befe3df8-1795-11e5-8391-8e606bb63601.png)

The challenge is to have your form element wrap around your input field. Having the input field outside of the form element slips through the validation check.

**Comment by benschenker** [comment]
Thanks @wcountiss!

This seems to be resolved, closing.
