### ISSUE TITLE
Incorrect Entry number after hitting dot, an operator and then a number

### ISSUE THREAD

**Issue by htphong24** [FreeCodeCamp/FreeCodeCamp#10373]
Challenge [Build a JavaScript Calculator](https://www.freecodecamp.com/challenges/build-a-javascript-calculator) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.

Hi FCC team,
I've just found a bug in Javascript Calculator challenge by chance. You can easily replicate the bug by following the steps below:
- step 1: after refreshing the page, press button "."
- step 2: press button "+" (or any other operator, e.g. "-", "*", "/")
- step 3: press button "1" (or any other number)
Now you can see the output is "1" on top and below is "0.1". This is not consistent though the calculation still can work fine after that.
I also attached a sreen-shot for your reference.
![javascript calculator bug - free code camp](https://cloud.githubusercontent.com/assets/16635184/18032565/d0b71bd4-6d32-11e6-9210-abd51269384c.PNG)

Just a small problem with the entry number I think. Please fix this.

Greetings,
Phong Ho

**Comment by erictleung** [comment]
@htphong24 thanks for the issue. We have started a discussion about improving the calculator here https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10158. Please take your feedback to that thread in case it has not already been addressed. Happy coding!
