### ISSUE TITLE
Geolocation JS - non-secure origin

### ISSUE THREAD

**Issue by bagi952** [FreeCodeCamp/FreeCodeCamp#10370]
Challenge [Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.

Okay so if i want to use user's location i need to have a website on secured hosting.

Codepen.io is on non-secure hosting. So how to do that in vanilla JS?
https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only?hl=en
http://prntscr.com/cb78ci

**Comment by erictleung** [comment]
@bagi952 thanks for the issue. This is a duplicate issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9145. Please continue the discussion there. Happy coding!
