### ISSUE TITLE
Record Collection Issue on Chrome

### ISSUE THREAD

**Issue by stoutpanda** [FreeCodeCamp/FreeCodeCamp#10379]
#### Record-Collection
https://www.freecodecamp.com/challenges/record-collection

#### Issue Description
When using chrome (version 52.0.2743.116) on mac osx (10.11.6) the automated test for Record Collection will not pass, even though the case actually passes. Tried my solution and 3 other working ones I found online and could not get After updateRecords(5439, "artist", "ABBA"), artist should be "ABBA" to pass. 

I went and ran the same code in safari and firefox and the issue passed.

#### Browser Information

* Browser Name, Version:  Chrome, 52.0.2743.116
* Operating System: OS X (10.11.6)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id,prop,value)
{
  if (prop !== "tracks" && value !== "")
   {
     collection[id][prop] = value;  
   }
  
  else if (value === "")
    {
       delete collection[id][prop];
    }
   else if (prop === "tracks")
    {
      if (collection[id].hasOwnProperty("tracks") === false)
        {
          collection[id].tracks = [];
          collection[id].tracks.push(value);
        }
       else 
       {
         collection[id].tracks.push(value);
       }
    }
         
   return collection;
  
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");


```
#### Screenshot
![screen shot 2016-08-28 at 7 25 22 pm](https://cloud.githubusercontent.com/assets/16127753/18037957/3500b808-6d55-11e6-9a87-e20f6bc03a43.png)

**Comment by atjonathan** [comment]
@stoutpanda your code passes for me fine. Have you tried resetting your code?

**Comment by DavidII** [comment]
I've see this question before and I believe this might help. I noticed in you code that you are missing a a comma    `  , ` also, there also bracket `[]`  . I hope this help you.

`` },
 "5439": {
 "album": "ABBA Gold",
 "tracks": [ "Take a Change on Me" 
]
 }
 } ``

Respectfully, 

Dave

**Comment by stoutpanda** [comment]
@atjonathan I was able to get the code to pass without issue on several browsers including chrome on Windows. Just not from the os / browser combo I happened to be working through the challenges with. I did try resetting the code as well as clearing the browsers cache and trying again. 

I will try again later today and report back.

**Comment by stoutpanda** [comment]
Issue persisted after trying clearing code again. In a last ditch effort I removed chrome and reinstalled it and it now works with no issues. I don't really understand why, but since the issue appears to have been with chrome or my computer I'm closing the issue.

**Comment by andreilepsch** [comment]
I have the same problem and the answer of "dhcodes" in other post (...ou will see that you can't do the .push() method because the array doesn't exist...) it made me think better. Then i create a property with empty array and next use .push() to append the value. And Voilá. Here my code below:

```
function updateRecords(id, prop, value) {
  
if (prop !== "tracks" && value !== "") {
    collection[id][prop] = value; 
  } else if (prop === "tracks" && value !== "") {
      if(!collection[id].hasOwnProperty(prop)) {
        collection[id][prop] = []; //Create a property with empty array
        collection[id][prop].push(value); //Append a value into the array 
      } else {
         collection[id][prop].push(value); //Append a value into the exist property array
      }
  } else if (value === "") {
     delete collection[id][prop];
  }
  return collection;
}
```
