### ISSUE TITLE
Record Collection not working

### ISSUE THREAD

**Issue by rujaraju** [FreeCodeCamp/FreeCodeCamp#10382]
Record Collection

https://www.freecodecamp.com/challenges/record-collection

My code is working just fine, still there's a red x on the description "After updateRecords(5439, "tracks", "Take a Chance on Me"), tracks should have "Take a Chance on Me" as the last element." - as you can see in the screenshot - exactly this is the case.

Chrome and IE

And the code:

function updateRecords(id, prop, value) {
if (prop == "tracks" && value.length === 0){
delete collection[id].tracks;
}

else if (prop == "tracks" && value.length > 0) {
if (collection[id].hasOwnProperty("tracks")) {
collection[id].tracks.push(value);
}
else {
collection[id].tracks = value;}
}

else if (prop == "artist" && value === "") {
delete collection[id].artist;
} 

else {collection[id][prop] = value;}
  return collection;
}

As you can see, it is functioning flawlessly:

![image](https://cloud.githubusercontent.com/assets/20854224/18052828/2b3564da-6e05-11e6-9131-c01f8999dc88.png)

**Comment by DavidII** [comment]
I not sure if this helps or helping at all. Also I am not good at the JAVA. But I noticed on all visible code that all have a uniform look. [ ] take a look at the brackets. I am not sure if this makes a differences. 
``},
"5439": {
"album": "ABBA Gold",
"tracks": [ "Take a Change on Me" 
]
}
}``

Respectfully, Dave

**Comment by andreilepsch** [comment]
I have the same problem and the answer of "dhcodes" in other post (...ou will see that you can't do the .push() method because the array doesn't exist...) it made me think better. Then i create a property with empty array and next use .push() to append the value. And Voilá. Here my code below:

```
function updateRecords(id, prop, value) {
  
if (prop !== "tracks" && value !== "") {
    collection[id][prop] = value; 
  } else if (prop === "tracks" && value !== "") {
      if(!collection[id].hasOwnProperty(prop)) {
        collection[id][prop] = []; //Create a property with empty array
        collection[id][prop].push(value); //Append a value into the array 
      } else {
         collection[id][prop].push(value); //Append a value into the exist property array
      }
  } else if (value === "") {
     delete collection[id][prop];
  }
  return collection;
}
```

**Comment by texas2010** [comment]
@andreilepsch 
Please don't put your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by thyairdrigh** [comment]
It's not a bug. You missed the empty-array-creating step (so did I :))
