### ISSUE TITLE
Override Class Declarations by Styling ID Attributes bug

### ISSUE THREAD

**Issue by snackserrday** [FreeCodeCamp/FreeCodeCamp#10388]
Override Class Declarations by Styling ID Attributes

one of the pre-reqs to move on to the next challenge is for the text "Hello World" to be overridden to the color orange. Finish the challenge with the code I posted below, and the text did not override to orange, but continued to let me pass. I'm not sure if I posted the correct code because the color did not override.

* Browser Name, Version: FireFox 48.0
* Operating System: LMDE
* Mobile, Desktop, or Tablet: Laptop

![codecampbug1](https://cloud.githubusercontent.com/assets/16868150/18073877/55a017c8-6e2e-11e6-90b9-413ba416d99f.png)
![codecampbug2](https://cloud.githubusercontent.com/assets/16868150/18073878/55a4ad60-6e2e-11e6-9be6-19fed90deb3d.png)

**Comment by texas2010** [comment]
@snackserrday 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by shayandamani** [comment]
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
    
    #orange-text {
      color: orange;
    }
</style>

<h1 id="orange-text">
<h1 class="pink-text blue-text"> Hello World!</h1>

This is how i have done still my h1 element did not change the color

**Comment by texas2010** [comment]
@shayandamani 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by navski89** [comment]
Could someone please enlighten on here, as i am unable to access the help chat room due to work IT access restrictions

**Comment by ElisabetK** [comment]
I had the same issue, using two h1 declarations and the text NOT being orange. (I've fixed it.)

This is a website bug - it passed me even though my code was incorrect, and it incorrectly told me my h1 text was orange, when it was not.
