### ISSUE TITLE
"Your h2 element should be blue." command does not work

### ISSUE THREAD

**Issue by jshinglam** [FreeCodeCamp/FreeCodeCamp#10386]
#### Challenge Name

https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20blue%3B%7D%0A%3C%2Fstyle%3E%0A
#### Issue Description

Question: "Your h2 element should be blue."
Code is correct but unable to submit and move on to the next problem

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Mac OS
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 <style>
  h2 {color: blue;}
</style>

 
 
```
#### Screenshot

<img width="1055" alt="screen shot 2016-08-29 at 4 53 52 pm" src="https://cloud.githubusercontent.com/assets/21319669/18071256/3b996854-6e09-11e6-820d-f6ddeba0dbb3.png">

**Comment by samanthakem** [comment]
I just checked it here. In fact, it is not working properly. If nobody else is going to work on fixing it, I would like to be assigned to this issue.

**Comment by dhcodes** [comment]
The test that isn't passing is `Your h2 element should be blue`, but likely the reason it isn't passing is because you have no h2 element. I just tested it and if you write an `h2` element and put some text in it, it will pass.

**Comment by texas2010** [comment]
@jshinglam, Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by CodingBegginer** [comment]
<style>
  h2 {color: blue;}
</style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by texas2010** [comment]
@CodingBegginer 
Please don't put your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
