### ISSUE TITLE
star appears for all completed challenges

### ISSUE THREAD

**Issue by harindu95** [FreeCodeCamp/FreeCodeCamp#10387]
#### Issue Description
Star appears for all completed challenges instead for only required challenges.

#### Browser Information

* Browser Name, Version:  Firefox 48.0
* Operating System:  Ubuntu 16.04
* Mobile, Desktop, or Tablet:  Desktop

#### Screenshot
![screenshot from 2016-08-29 18-13-06](https://cloud.githubusercontent.com/assets/15548633/18071582/44ed4ae6-6e14-11e6-9c03-586b6e961b39.png)

**Comment by atjonathan** [comment]
This issue was resolved by a recent PR. It will be merged in once we have finished `QA` on rectification :smiley:
