### ISSUE TITLE
Validation Fail

### ISSUE THREAD

**Issue by wcountiss** [FreeCodeCamp/FreeCodeCamp#1038]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-radio-buttons has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

![validation-fail-2](https://cloud.githubusercontent.com/assets/7219453/8270050/36e97444-1797-11e5-85fd-ce98259bb326.png)

Both radio inputs do not share the same name value, and should not pass the lesson's validation.

**Comment by digitaldak** [comment]
Yea you can also do that one with only one label before them and 1 ending label at the end. Reported it last night as well, but different way to do it. Probably needs to have the test do a label has input . text type check?

**Comment by benschenker** [comment]
Thanks @wcountiss!

I've confirmed this issue:

```
  <label>indoor<input type=radio name=indoor-outdoor></label>
  <label>outdoor<input type=radio></label>
```
in the form, passes all the tests when number 2 should fail.
