### ISSUE TITLE
Stand in Line: Test failing  nextInLine([], 1) should return 1  

### ISSUE THREAD

**Issue by dynelight** [FreeCodeCamp/FreeCodeCamp#10384]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20var%20poppedValue%20%3D%20arr.shift()%3B%0A%20%20arr.push(item)%3B%0A%20%20%0A%20%20return%20poppedValue%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B%5B%5D%2C%201%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%206))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hello. All my tests are passing but I cannot see why this test shouldn't pass.
If I am shifting the element of an array that has an empty array as the head, why would 1 be expected? 

My code:
```javascript

function nextInLine(arr, item) {
  var poppedValue = arr.shift();
  arr.push(item);
  
  return poppedValue;  // Change this line
}

// Test Setup
var testArr = [[], 1];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by internetbird** [comment]
The function is supposed to do 2 things:
1. Add the item to the end of the queue 
2. remove the first item of the queue and return it

So, if the queue is empty and you add '1' to it and remove the first item you should get your '1' back.

Change the order of your operations and it will pass all the tests:

 arr.push(item);  
 var poppedValue = arr.shift();

**Comment by dynelight** [comment]
My apologies.
