### ISSUE TITLE
Error in the Challenge Manipulate Arrays With unshift()

### ISSUE THREAD

**Issue by usmanghani5995** [FreeCodeCamp/FreeCodeCamp#10385]
#### Challenge Name

[https://www.freecodecamp.com/challenges/manipulate-arrays-with-unshift](url)

#### Issue Description

My answer is correct according to required answer. but it is not passing it. saying that it's not the required answer but i double checked it and it's the same and correct

#### Browser Information

* Firefox, 48.0.2: 
* Window 10: 
* Desktop,: 

#### Your Code

```js
 // Example
var ourArray = ["Stimpson", "J", "cat"];
ourArray.shift(); // ourArray now equals ["J", "cat"]
ourArray.unshift("Happy"); 
// ourArray now equals ["Happy", "J", "cat"]

// Setup
var myArray = [["John", 23], ["dog", 3]];
myArray.shift();

// Only change code below this line.
myArray.unshift(["paul", 35]);

// Required Answer: myArray should now have [["Paul", 35], ["dog", 3]]. 
// My Answer: myArray = [["paul",35],["dog", 3]]
 
 
```
#### Screenshot

![untitled](https://cloud.githubusercontent.com/assets/18269430/18067888/580717c6-6e58-11e6-9ae9-f6717208b827.png)

**Comment by usmanghani5995** [comment]
I'm closing it because I found the Problem by myself

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by nommanshaik18** [comment]
change the spelling of paul its given as upper case Paul you have given lower case paul @usmanghani5995
