### ISSUE TITLE
how-to-npm 13 Outdated

### ISSUE THREAD

**Issue by jrogatis** [FreeCodeCamp/FreeCodeCamp#10383]
#### Challenge Name

Manage Packages with npm

#### Issue Description

When i use the commadn npm outdated i got a error 

#### Browser Information

* Browser Name, Version: chrome Versão 52.0.2743.116 (64-bit)
* Operating System: Mac OS
* Mobile, Desktop, or Tablet: desktop 

#### Your Code

jrogatis:~/workspace $ npm outdated
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.5/bin/npm" "outdated"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.6
npm ERR! code E404

npm ERR! 404 missing : async
npm ERR! 404 
npm ERR! 404  'async' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log

 
 
 
```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by elimcjah** [comment]
So what was the problem?

**Comment by jrogatis** [comment]
Mybe I was using diferent email as login.
Thanks for your time!
De: "Elijah M." <notifications@github.com>
Responder para: FreeCodeCamp/FreeCodeCamp <reply@reply.github.com>
Data: segunda-feira, 14 de novembro de 2016 19:06
Para: FreeCodeCamp/FreeCodeCamp <FreeCodeCamp@noreply.github.com>
Cc: Jean Philip de Rogatis <jrogatis@conecta.net.br>, State change <state_change@noreply.github.com>
Assunto: Re: [FreeCodeCamp/FreeCodeCamp] how-to-npm 13 Outdated (#10383)


So what was the problem?
