### ISSUE TITLE
Remove obsolete packages

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#10395]
Remove the following packages from package.json

async
cheerio
url-regex
xss-filters
gulp-dest

**Comment by stancheta** [comment]
Mind if I take this one?

**Comment by BerkeleyTrue** [comment]
All yours ✨

**Comment by iprugb** [comment]
Guys I an absolutely new to this. freecodecamp site is just not loading on my macbook air. All other sites are working properly except this one. I am yet to take my first lesson. Apprently this site is loading normally on my android phone. Please Guide !!!!!

**Comment by stancheta** [comment]
[https://www.freecodecamp.com](https://www.freecodecamp.com) Does this link not work for you?

**Comment by iprugb** [comment]
No it takes a minute to execute every click :(

**Comment by stancheta** [comment]
Have you tried opening it in other browsers such as FireFox or Chrome?

**Comment by iprugb** [comment]
I tried with Safari and Chrome….dont have fire fox

**Comment by stancheta** [comment]
And the site is unresponsive on both... Unfortunately @iprugb, I don't have a macbook so I can't really help you out further. Would you mind asking on the FreeCodeCamp main chat: [here](https://gitter.im/FreeCodeCamp/FreeCodeCamp)?

**Comment by itsabear** [comment]
I really recommends to try firefox as @stancheta prefer.

-- You have a problem? Find the solution. Now you got two problems.
