### ISSUE TITLE
link to the discussion is not in the JSON

### ISSUE THREAD

**Issue by dwilbank68** [FreeCodeCamp/freecodecamp#1039]
There is no way to get the discussion link (item 8 - user story) unless there is another endpoint that accepts the post's id, or something like that.

![](https://dl.dropboxusercontent.com/spa/lkj2dewi3ofvkgc/p9yh2e_n.jpg)

**Comment by BerkeleyTrue** [comment]
The discussion lives in the comments field. This is also removed from beta.

Happy coding!
