### ISSUE TITLE
Smallest Common Multiple Test Cases are wrong

### ISSUE THREAD

**Issue by cicio** [FreeCodeCamp/FreeCodeCamp#10397]
Challenge [Smallest Common Multiple](https://www.freecodecamp.com/challenges/smallest-common-multiple#?solution=%0Afunction%20smallestCommons(arr)%20%7B%0A%20%20%2F%2F%20least%20common%20multiple%20of%20two%20numbers%20can%20be%20calculated%20as%20the%20ratio%20between%20the%20product%20of%20both%20numbers%20and%20their%20greates%20common%20denominator%20(gcd).%0A%20%20%2F%2FLet's%20use%20the%20Euclid's%20algorithm%20to%20calculate%20the%20gcd%3A%0A%20%20function%20gcd(a%2Cb)%20%7B%0A%20%20%20%20if%20(a%3C1%20%7C%7C%20b%3C1)%20%7B%20return%20%22Invalid%2C%20argument%20must%20be%20positive%20integers%22%3B%7D%0A%20%20%20%20while%20(b!%3D%3D0)%20%7B%0A%20%20%20%20%20%20var%20tmp%20%3D%20a%3B%0A%20%20%20%20%20%20a%20%3D%20b%3B%0A%20%20%20%20%20%20b%20%3D%20tmp%20%25%20a%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20a%3B%0A%20%20%7D%0A%20%20%0A%20%20var%20x%20%3D%20arr%5B0%5D%3B%0A%20%20var%20y%20%3D%20arr%5B1%5D%3B%0A%20%20return%20x%20*%20y%20%2F%20gcd(x%2Cy)%3B%0A%7D%0A%0A%0AsmallestCommons(%5B18%2C%2023%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function smallestCommons(arr) {
  // least common multiple of two numbers can be calculated as the ratio between the product of both numbers and their greates common denominator (gcd).
  //Let's use the Euclid's algorithm to calculate the gcd:
  function gcd(a,b) {
    if (a<1 || b<1) { return "Invalid, argument must be positive integers";}
    while (b!==0) {
      var tmp = a;
      a = b;
      b = tmp % a;
    }
    return a;
  }
  
  var x = arr[0];
  var y = arr[1];
  return x * y / gcd(x,y);
}


smallestCommons([18, 23]);

```
The Test Cases specify:
smallestCommons([1, 5]) should return 60. -
smallestCommons([5, 1]) should return 60.
smallestCommons([1, 13]) should return 360360.
smallestCommons([23, 18]) should return 6056820.

Test Cases should specify:
smallestCommons([1, 5]) should return 5.
smallestCommons([5, 1]) should return 5.
smallestCommons([1, 13]) should return 13.
smallestCommons([23, 18]) should return 414.

**Comment by BKinahan** [comment]
Hi @cicio. Unfortunately you have misread the instructions; you should find the smallest common multiple of all numbers in the range. Please read the instructions again and if you still need help, visit the HelpJavaScript chat room.

Happy coding!

**Comment by cicio** [comment]
Hi @BKinahan,
That is right. I apologize for not taking the time to review it properly.
Thank you
Regards
