### ISSUE TITLE
Returning Boolean Values from Functions

### ISSUE THREAD

**Issue by OstapKoverko** [FreeCodeCamp/FreeCodeCamp#10392]
#### Challenge Name

[Returning Boolean Values from Functions](https://www.freecodecamp.com/challenges/returning-boolean-values-from-functions#?solution=%0Afunction%20isLess(a%2C%20b)%20%7B%0A%20%20%20%20return%20a%20%3D%3D%3D%20b%3B%0A%20%20%7D%20%0A%0AisLess(10%2C%2015)%3B%0A)

#### Issue Description
function isLess(a, b) {
    return a === b;
  } 
isLess(10, 15);

This function return "false" and it is  OK, but unfortunately checkpoints say "isLess(10,15) should return true" and it is not OK, because  10  not  equal 15

#### Browser Information

* Google Chrome, Version: 52.0.2743.82 m 
* Operating System: Windows 8.1
* Desktop 

#### Your Code

```js
 
function isLess(a, b) {
    return a === b;
  } 

isLess(10, 15);
 
```
#### Screenshot

![2016-08-30_104905](https://cloud.githubusercontent.com/assets/19934926/18080934/353067b4-6ea0-11e6-9c63-726efc50608a.jpg)

**Comment by BKinahan** [comment]
Hi @OstapKoverko 

You have used the code from the example function, `isEqual`, instead of the code from the function in the editor, `isLess`. Reset your code, read the instructions again, and if you still have questions remember to visit the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) before raising an issue about code that fails a test.

Happy coding!

**Comment by OstapKoverko** [comment]
> You have used the code from the example function, isEqual, instead of the code from the function in the editor, isLess
No!  You can see on the screenshot I used isLess function like in Instructions, but I make mistake in another place.
Thank's!

**Comment by runner182** [comment]
i have the same issue,  pls if you resolve it tell me how pls  :)

**Comment by texas2010** [comment]
@runner182, Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by yccai** [comment]
Me too. But I do not know how to solve it.

**Comment by thaobktin** [comment]
function isLess(a, b){
  return a < b;
}

**Comment by craigpope** [comment]
"===" =! "<"

**Comment by saikatghosh1978** [comment]
function isLess(a, b) {
  // Fix this code
  return a < b;

}

// Change these values to test
isLess(10, 15);

**Comment by minime0310** [comment]
________________________________

**Comment by fagbolaoluwagbenga** [comment]
Returning Boolean Values from Functions
function isLess(a, b) {
return a < b;
}

// Change these values to test
isLess(10, 15);

**Comment by fagbolaoluwagbenga** [comment]
that should do

**Comment by texas2010** [comment]
@fagbolaoluwagbenga 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by nheljhoncap** [comment]
return a<b

**Comment by texas2010** [comment]
@nheljhoncap 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
