### ISSUE TITLE
Regarding this challenge

### ISSUE THREAD

**Issue by gabazine** [FreeCodeCamp/freecodecamp#1040]
Challenge http://www.freecodecamp.com/challenges/waypoint-say-hello-to-html-elements has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Basically Keep the text editor from moving when you scroll down the instructions.

**Comment by digitaldak** [comment]
So your saying if "more information" is clicked, you want the editor to stay put while the instruction window scrolls only?

**Comment by gabazine** [comment]
yes

**Comment by BerkeleyTrue** [comment]
@gabazine Thanks for filing. This is already a known issue. We will keep you updated at #716
