### ISSUE TITLE
Remove ability to create a new FCC account using GitHub

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#10407]
- [ ] As a user, the initial email address I used to create my account will remain my email address even if I have a different email address on GitHub.

- [ ] ~~As a user, when I visit the `/signin` path, I only see an option to sign up with email, or to click a link that says "click here if you already have an account" - which then takes me to a sign in view with both email and GitHub login options.~~
- [x] Disable the ability for GitHub OAuth to create a new account
- [ ] Add the original email validation as being discussed in #15205

edit(@berkeleytrue): Updated user stories
edit(@raisedadead): Updated user stories for email validation

**Comment by mrpatil007** [comment]
@QuincyLarson i think at the time of registration if we authenticate the user by sending a OTP to there register mobile number then it Increase the security level. Because it is easy to create lot's of fake email by using one single number.

**Comment by QuincyLarson** [comment]
@AkiraLaine asked in chat how these duplicate accounts are being created. 

1) A camper will create an FCC account with an email address. They will create a GitHub account, but fail to link it to their FCC account. Then when they return, they will click the "sign in with GitHub" button. This will create a brand new FCC account. They will get upset and blame us for losing all their user data.

2) A user will initially create their FCC account using GitHub. Their GitHub account will be configured so that we don't get their email address - or it will be associated with a completely different email address. But they won't know this, and on a subsequent visit to FCC, they will try to sign in with an email address. This will create a brand new FCC account. They will get upset and blame us for losing all their user data.

Again, both of these things happen many times a day, and I suspect most events are unreported. Instead of messaging us to tell us what happened, most campers just say "screw this" and quit using Free Code Camp. Even if they do email to explain what happened, it is still a negative user experience that is entirely avoidable.

**Comment by Em-Ant** [comment]
I agree. In the past I had 2 accounts because I signed in with the email first, then with github. I don't remember, but probably I had to send an email to @QuincyLarson to ask for help...

**Comment by raisedadead** [comment]
This can be taken up after passwordless has been integrated.

**Comment by QuincyLarson** [comment]
@raisedadead OK - sounds good.
