### ISSUE TITLE
Object constructor argument of spacing

### ISSUE THREAD

**Issue by babygoat** [FreeCodeCamp/FreeCodeCamp#10405]
#### Challenge Name

https://www.freecodecamp.com/challenges/get-json-with-the-jquery-getjson-method

#### Issue Description

Hello, I'm newbie to the javascript. I used to write C or C++ so I adapted several coding styles from them.  The issue I encountered was if I left space between the argument and the parenthesis, I would fail the last requirement ("Don't forget to ...") of the challenge.  I knew it might not be a good practice to adopt the style but I was wondering why it would fail the test. So far, I haven't found any related information. Thanks for your consideration.

#### Browser Information

* Browser Name, Version:  Chrome, 52.0.2743.116
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js
 
/* Incorrect */
       $.getJSON("/json/cats.json", function( json ) {
                $(".message").html( JSON.stringify(json) );
                });
/* Correct */
       $.getJSON("/json/cats.json", function(json) {
                $(".message").html( JSON.stringify(json) );
                }); 
```
#### Screenshot

![issue](https://cloud.githubusercontent.com/assets/1139696/18116147/d95e32da-6f77-11e6-9492-eb2e2a300708.jpg)

**Comment by dhcodes** [comment]
@babygoat Sorry for the delay. This has come up before in similar challenges (ex. #10021 and #8360). It's a matter of updating the Regex tests to accept optional spaces because as you've mentioned, it is acceptable. Thanks for the issue.
