### ISSUE TITLE
Sync of progress on multiple devices

### ISSUE THREAD

**Issue by oluwaseyiaduloju** [FreeCodeCamp/FreeCodeCamp#10406]
- Logging in from another device that has been used before does not take one to one's most recent challenge but the challenge the person was on the particular device one is using to log in; I think this behaviour should be changed even if it is not a bug.

#### Browser Information

* Browser Name, Version:  Chrome, 52.0.2743.116 m
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

**Comment by BerkeleyTrue** [comment]
Hey @oluwaseyiaduloju,

We do not store partial solutions in an effort to reduce server load. They are stored using localStorage. 

Happy Coding

**Comment by oluwaseyiaduloju** [comment]
Hi Berkeley,

Thanks for the reply, hope this meets you well.

If what you mean by partial solutions is "partial solutions to a
challenge", then I think I was misunderstood, I actually meant a scenario
like this:

Say I log in on a PC then do challenge 1-9, then I log in on another and do
challenge 10 -15, by the time I get to the former PC it would not continue
from 16 rather 10

Do you get?

Cheers
Oluwaseyi

**Comment by BerkeleyTrue** [comment]
This is expected behavior. Currently this information is stored locally. This will change with the new version of the site to be released shortly.

Happy Coding

**Comment by thanira** [comment]
Thanks. I've started the challenges in my laptop and when logging in on my desktop I can see the numbers of projects, but not the page where I actually stopped. :( Do you know when new version will be available?

**Comment by mini-gui** [comment]
> Two years later and I'm getting the same behaviour...as this been solved? Is there a "manual-sync" I can use?

I found out that it will sync if you log out and immediately log in again, cheers!

**Comment by lraubuch** [comment]
I think this issue should be reopened since it obviously was not fixed.
>
> This is expected behavior. Currently this information is stored locally. This will change with the new version of the site to be released shortly.
> 
> Happy Coding

It should be made clear if or when the version will be released.
