### ISSUE TITLE
The code doesn't check if the number is non-negative

### ISSUE THREAD

**Issue by ksu-b** [FreeCodeCamp/FreeCodeCamp#10409]
I think the code should check if the number is negative and give a notification if it is' Like this:
if (num < 0) {
   return "undefined";
}

**Comment by BKinahan** [comment]
Hi @ksu-b. What challenge are you referring to? 😄

**Comment by ksu-b** [comment]
Hello! Sorry, it's my 1st issue. I talked about Factorialize a Number.

**Comment by ksu-b** [comment]
Will you fix it? I don't understand what "blocked" label means.

**Comment by Greenheart** [comment]
Hey @ksu-b, thanks for taking the time to bring this up for discussion! :blush:

The `blocked`-label simply means that more information is needed before any of us issue moderators can do anything with the issue.

Just to make sure I understand you: Do you want to add your suggestion as a requirement for completing the challenge? This would mean adding a test case where the function `factorialize` is called with a negative `num` which should result in `undefined`?

**Comment by ksu-b** [comment]
Yes, exactly. I think it would make sense to check if the input number is not negative. I also want to check how issues work and if my suggestion will be accepted and done, and when.

**Comment by Greenheart** [comment]
@ksu-b Sorry for the late reply, I'm unfortunately really busy.

Ok! I agree that this challenge could be clarified. However, I think your proposed solution of adding an additional test stating something like "`factorialize(num) should `return `undefined` if `num` is negative" is the optimal way to accomplish this. How about if we simply updated the challenge instructions to clarify that **`factorialize` will always be called with positive values for the argument `num`**? That way, the additional test and the additional step to complete the challenge wouldn't be necessary while still solving the problem you brought up with this issue.

@BKinahan This could be another first-timers-only issue - do you have time to fix some instructions to guide someone who wants to implement it? (Maybe @ksu-b wants to fix this? :blush:)
Here's an outline:
Clarify the instructions for this challenge by adding something like **`factorialize` will always be called with positive values for the argument `num`**. To make this change, edit [Link to one of the challenge seed files] on line XYZ.

**Comment by erictleung** [comment]
@Greenheart but the last test is `0!`, which equals to `1` won't make sense anymore if we say it'll always be called with positive values.

Maybe we could change first sentence to

> Return the factorial of the provided integer. The given integer will be greater than or equal to zero.
