### ISSUE TITLE
Codepen window.open() works

### ISSUE THREAD

**Issue by MiloATH** [FreeCodeCamp/FreeCodeCamp#10419]
The Build a Personal Portfolio challenge says that window.open() won't work in codepen as task number 11. Proof that window.open works is [here ](http://codepen.io/Miloath/pen/JRPQKr). Simply remove task number 11.

#### Challenge Name

The Build a Personal Portfolio

#### Issue Description

This is more of a request to update the task. Reproduce by going to [here ](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage). Simple remove task 11 since it is out of date.

**Comment by atjonathan** [comment]
@MiloATH, it seems [codepen](https://www.codepen.io) has updated their editor to allow for `window.open()`.

**To First Timer:**
You will need to remove [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-ziplines.json#L208) line. Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

> **Note:** You can only submit a pull request for this issue if you are new and haven't submitted one before. Hence the issue label `first-timers-only` :stuck_out_tongue_winking_eye:

**Comment by BKinahan** [comment]
May as well remove the lines with references to Codepen and Window.open() in the translations at the same time; lines 233 and 251 😄
