### ISSUE TITLE
Code already correct if logging with different user.

### ISSUE THREAD

**Issue by devilicecream** [FreeCodeCamp/FreeCodeCamp#10413]
#### Challenge Name
All challenges

#### Issue Description
If I log out from my account (on which I have completed all the Front End challenges), and then I log in on the same tab with another account (my sister started her own account this week), all the challenges I have already completed on my account are shown with the code already completed, even if the challenges are not marked as "Completed".

#### Browser Information

* Browser Name, Version: Chrome 52.0.2743.116 (64-bit)
* Operating System: Mac OS X 10.11.6
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
 
 
```

**Comment by dhcodes** [comment]
@devilicecream Is the code that is in the code editor your solution to the challenge? If so, it may have to do with how the browser cache that stores the changes users make in the code editor. It may be associated with issue #9115.

**Comment by devilicecream** [comment]
@dhcodes Correct. I thought it would be something related to caching. Reading #9115 made me realize that solving point 1 of the issue would probably solve this one too.
Nevertheless, for "security" reasons I think that the incomplete code should be saved into the browser's local storage with a reference to the user id of the user who wrote it. Otherwise even solving #9115 would not solve the issue in the following use case:
1. I log in with user "Walter" on my browser.
2. I write some code on challenge number 10, but I do not submit it.
3. I log out from FCC.
4. I log in with user "Laura" on the same browser.
5. I go to challenge number 10, that "Laura" has not completed yet.
6. **BUG** I see the code written by "Walter" in the editor.

**Comment by dhcodes** [comment]
@devilicecream True true. I'm not sure what is possible with regard to storing attempts for each user with his/her username. Maybe others will have more insight.

**Comment by BerkeleyTrue** [comment]
This should be solved with the new version of the site. Once a solution is submitted we remove it from localStorage. Although, you will still have the issue for partial solutions (challenges in progress).

I don't think multi user browser sessions is a use case we will cover as it overly complicates code storage for an edge case.

**Comment by dhcodes** [comment]
@devilicecream sounds like the new version may help. Another idea might be to open an incognito window (if using chrome) when someone new is going to log in as the incognito window won't come with the cache of the past user. I'll close this as it seems to be addressed.
