### ISSUE TITLE
Disable an Element Using JQuery passes without JQuery

### ISSUE THREAD

**Issue by afable** [FreeCodeCamp/FreeCodeCamp#10410]
#### Challenge Name
https://www.freecodecamp.com/challenges/disable-an-element-using-jquery

#### Issue Description
Test passes with only HTML changes and no JQuery.

#### Browser Information
* Browser Name, Version: Chrome, Version 52.0.2743.116 m (64-bit)
* Operating System: Win 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
![jquery error1](https://cloud.githubusercontent.com/assets/1513169/18125893/7e710a0e-6f2d-11e6-9231-24e63c9c9d77.png)

![jquery error2](https://cloud.githubusercontent.com/assets/1513169/18125989/00ad5784-6f2e-11e6-8464-2e91b0153a85.png)

**Comment by BKinahan** [comment]
It seems the final test is not working the way it is supposed to.

**Comment by dhcodes** [comment]
I went ahead and submitted a PR for this. The current regex in the third test looks for `disabled>` whereas it should look for `disabled=`. Tested locally and seems to correct this issue.

Thanks for reporting.
