### ISSUE TITLE
Help roman converter

### ISSUE THREAD

**Issue by xavierartot** [FreeCodeCamp/FreeCodeCamp#10416]
I submit my code everything is correct, the answer is good, but still refuse for no reason?

#### Challenge Name

https://www.freecodecamp.com/challenges/roman-numeral-converter#?solution=%20%20var%20castStringParam%20%3D%20void%200%2C%0A%20%20%20%20%20%20obj%20%3D%20%7B%7D%2C%0A%20%20%20%20%20%20add%20%3D%20''%2C%0A%20%20%20%20%20%20result%20%3D%20%5B%5D%2C%0A%20%20%20%20%20%20arrRomanOne%20%3D%20%5B%7B%20key%3A%201%2C%20valeur%3A%20'I'%20%7D%2C%20%7B%20key%3A%202%2C%20valeur%3A%20'II'%20%7D%2C%20%7B%20key%3A%203%2C%20valeur%3A%20'III'%20%7D%2C%20%7B%20key%3A%204%2C%20valeur%3A%20'IV'%20%7D%2C%20%7B%20key%3A%205%2C%20valeur%3A%20'V'%20%7D%2C%20%7B%20key%3A%206%2C%20valeur%3A%20'VI'%20%7D%2C%20%7B%20key%3A%207%2C%20valeur%3A%20'VII'%20%7D%2C%20%7B%20key%3A%208%2C%20valeur%3A%20'VIII'%20%7D%2C%20%7B%20key%3A%209%2C%20valeur%3A%20'IX'%20%7D%5D%2C%0A%20%20%20%20%20%20arrRomanTwo%20%3D%20%5B%7B%20key%3A%201%2C%20valeur%3A%20'X'%20%7D%2C%20%7B%20key%3A%202%2C%20valeur%3A%20'XX'%20%7D%2C%20%7B%20key%3A%203%2C%20valeur%3A%20'XXX'%20%7D%2C%20%7B%20key%3A%204%2C%20valeur%3A%20'XL'%20%7D%2C%20%7B%20key%3A%205%2C%20valeur%3A%20'L'%20%7D%2C%20%7B%20key%3A%206%2C%20valeur%3A%20'LX'%20%7D%2C%20%7B%20key%3A%207%2C%20valeur%3A%20'LXX'%20%7D%2C%20%7B%20key%3A%208%2C%20valeur%3A%20'LXXX'%20%7D%2C%20%7B%20key%3A%209%2C%20valeur%3A%20'XC'%20%7D%5D%2C%0A%20%20%20%20%20%20arrRomanThree%20%3D%20%5B%7B%20key%3A%201%2C%20valeur%3A%20'C'%20%7D%2C%20%7B%20key%3A%202%2C%20valeur%3A%20'CC'%20%7D%2C%20%7B%20key%3A%203%2C%20valeur%3A%20'CCC'%20%7D%2C%20%7B%20key%3A%204%2C%20valeur%3A%20'CD'%20%7D%2C%20%7B%20key%3A%205%2C%20valeur%3A%20'D'%20%7D%2C%20%7B%20key%3A%206%2C%20valeur%3A%20'DD'%20%7D%2C%20%7B%20key%3A%207%2C%20valeur%3A%20'DDD'%20%7D%2C%20%7B%20key%3A%208%2C%20valeur%3A%20'DCCC'%20%7D%2C%20%7B%20key%3A%209%2C%20valeur%3A%20'CM'%20%7D%5D%2C%0A%20%20%20%20%20%20arrRomanFour%20%3D%20%5B%7B%20key%3A%201%2C%20valeur%3A%20'M'%20%7D%2C%20%7B%20key%3A%202%2C%20valeur%3A%20'MM'%20%7D%2C%20%7B%20key%3A%203%2C%20valeur%3A%20'MMM'%20%7D%2C%20%7B%20key%3A%204%2C%20valeur%3A%20'M'%20%7D%2C%20%7B%20key%3A%205%2C%20valeur%3A%20'M'%20%7D%2C%20%7B%20key%3A%206%2C%20valeur%3A%20'M'%20%7D%2C%20%7B%20key%3A%207%2C%20valeur%3A%20'M'%20%7D%2C%20%7B%20key%3A%208%2C%20valeur%3A%20'M'%20%7D%2C%20%7B%20key%3A%209%2C%20valeur%3A%20'M'%20%7D%5D%3B%0A%20%20%2F%2Fnum%2C%20arrRoman%5Bj%5D.key%2C%20arrRoman%5Bj%5D.valeur%0A%20%20function%20oneNumber(num%2C%20obj%2C%20whichArray)%20%7B%0A%20%20%20%20%2F%2Floop%20in%20the%20array%0A%20%20%20%20for%20(var%20j%20%3D%200%3B%20j%20%3C%20obj.length%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20%2F%2Fconsole.log(obj%5Bj%5D.key%20%2B'%20%3A%20'%2B%20obj%5Bj%5D.valeur%2B'%20%3A%20'%2Bj%2B'%20%3A%20'%2Bnum)%3B%0A%20%20%20%20%20%20if%20(obj%5Bj%5D.key%20%3D%3D%20num)%20%7B%0A%20%20%20%20%20%20%20%20add%20%3D%20obj%5Bj%5D.valeur%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20return%20result.push(add)%3B%0A%20%20%7D%0A%20%20function%20convertToRoman(num)%20%7B%0A%20%20%20%20castStringParam%20%3D%20num.toString()%3B%0A%20%20%20%20castStringParam.split('').map(function%20(a%2C%20i)%20%7B%0A%0A%20%20%20%20%20%20%2F%2Fconsole.log(a%2C%20i)%3B%0A%20%20%20%20%20%20%2F%2Ffor%20(var%20k%20%3D%200%3B%20k%20%3C%3D%20i%3B%20k%2B%2B)%20%7B%0A%20%20%20%20%20%20%2F%2Fconsole.log(%60%24%7Ba%7D%20%24%7BarrFun%5Bi%5D%7D%60)%3B%0A%20%20%20%20%20%20%2F%2Fconsole.log(i)%3B%0A%20%20%20%20%20%20%2F%2Fif%20(i%20%3D%3D%20arrFun%5Bi%5D)%20%7B%0A%20%20%20%20%20%20%2F%2F%2F%2Fconsole.log(arrFun%5Bi%5D)%3B%0A%20%20%20%20%20%20%2F%2FoneNumber(a%2C%20arrFun%5Bi%5D%20)%0A%20%20%20%20%20%20%2F%2F%7D%0A%20%20%20%20%20%20%2F%2F%7D%0A%0A%20%20%20%20%20%20if%20(i%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20%20%20%20%20oneNumber(a%2C%20arrRomanOne)%3B%0A%20%20%20%20%20%20%7D%20else%20if%20(i%20%3D%3D%3D%201)%20%7B%0A%20%20%20%20%20%20%20%20oneNumber(a%2C%20arrRomanTwo)%3B%0A%20%20%20%20%20%20%7D%20else%20if%20(i%20%3D%3D%3D%202)%20%7B%0A%20%20%20%20%20%20%20%20oneNumber(a%2C%20arrRomanThree)%3B%0A%20%20%20%20%20%20%7D%20else%20if%20(i%20%3D%3D%3D%203)%20%7B%0A%20%20%20%20%20%20%20%20oneNumber(a%2C%20arrRomanFour)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D)%3B%0A%20%20%20%20%2F%2Fconsole.log(result%20%3D%20result.reverse().join('').toString())%3B%0A%20%20%20%20result%20%3D%20result.reverse().join('').toString()%3B%0A%20%20%20%20%2F%2Fconsole.log(typeof%20result)%3B%0A%20%20%20%20%2F%2Fconsole.log(result)%3B%0A%20%20%20%20return%20result%3B%0A%20%20%7D%0A%20%20convertToRoman(3)%3B%0A

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
  var castStringParam = void 0,
      obj = {},
      add = '',
      result = [],
      arrRomanOne = [{ key: 1, valeur: 'I' }, { key: 2, valeur: 'II' }, { key: 3, valeur: 'III' }, { key: 4, valeur: 'IV' }, { key: 5, valeur: 'V' }, { key: 6, valeur: 'VI' }, { key: 7, valeur: 'VII' }, { key: 8, valeur: 'VIII' }, { key: 9, valeur: 'IX' }],
      arrRomanTwo = [{ key: 1, valeur: 'X' }, { key: 2, valeur: 'XX' }, { key: 3, valeur: 'XXX' }, { key: 4, valeur: 'XL' }, { key: 5, valeur: 'L' }, { key: 6, valeur: 'LX' }, { key: 7, valeur: 'LXX' }, { key: 8, valeur: 'LXXX' }, { key: 9, valeur: 'XC' }],
      arrRomanThree = [{ key: 1, valeur: 'C' }, { key: 2, valeur: 'CC' }, { key: 3, valeur: 'CCC' }, { key: 4, valeur: 'CD' }, { key: 5, valeur: 'D' }, { key: 6, valeur: 'DD' }, { key: 7, valeur: 'DDD' }, { key: 8, valeur: 'DCCC' }, { key: 9, valeur: 'CM' }],
      arrRomanFour = [{ key: 1, valeur: 'M' }, { key: 2, valeur: 'MM' }, { key: 3, valeur: 'MMM' }, { key: 4, valeur: 'M' }, { key: 5, valeur: 'M' }, { key: 6, valeur: 'M' }, { key: 7, valeur: 'M' }, { key: 8, valeur: 'M' }, { key: 9, valeur: 'M' }];
  //num, arrRoman[j].key, arrRoman[j].valeur
  function oneNumber(num, obj, whichArray) {
    //loop in the array
    for (var j = 0; j < obj.length; j++) {
      //console.log(obj[j].key +' : '+ obj[j].valeur+' : '+j+' : '+num);
      if (obj[j].key == num) {
        add = obj[j].valeur;
      }
    }
    return result.push(add);
  }
  function convertToRoman(num) {
    castStringParam = num.toString();
    castStringParam.split('').map(function (a, i) {

      //console.log(a, i);
      //for (var k = 0; k <= i; k++) {
      //console.log(`${a} ${arrFun[i]}`);
      //console.log(i);
      //if (i == arrFun[i]) {
      ////console.log(arrFun[i]);
      //oneNumber(a, arrFun[i] )
      //}
      //}

      if (i === 0) {
        oneNumber(a, arrRomanOne);
      } else if (i === 1) {
        oneNumber(a, arrRomanTwo);
      } else if (i === 2) {
        oneNumber(a, arrRomanThree);
      } else if (i === 3) {
        oneNumber(a, arrRomanFour);
      }
    });
    //console.log(result = result.reverse().join('').toString());
    result = result.reverse().join('').toString();
    //console.log(typeof result);
    //console.log(result);
    return result;
  }
  convertToRoman(3);
 
 
 
```

**Comment by BerkeleyTrue** [comment]
The issue tracker is for reporting bugs only. If this is an issue for help with a challenge, please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
