### ISSUE TITLE
Drop It fails on returning empty set

### ISSUE THREAD

**Issue by chadg1980** [FreeCodeCamp/FreeCodeCamp#10414]
Challenge [Drop it](https://www.freecodecamp.com/challenges/drop-it#?solution=%0Afunction%20dropElements(arr%2C%20func)%20%7B%0A%20%20%2F%2F%20Drop%20them%20elements.%0A%0A%20%20var%20emp%20%3D%20%5B%5D%3B%0A%20%20%2F%2Floop%20through%20elements%20seeking%20the%20true%20element%2C%20breaking%20when%20found.%20Shifting%20the%20elements%20when%20not%20found.%0A%20%20var%20end%20%3D%20arr.length%3B%0A%20%20if%20(end%20%3D%3D%3D%20arr.length)%7B%0A%20%20%20%20console.log(true)%3B%0A%20%20%7D%0A%20%20else%20%0A%20%20%20%20console.log(false)%3B%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%7B%0A%20%20%20%20if(func(arr%5B0%5D))%7B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%7B%0A%20%20%20%20%20%20%20%20arr.shift()%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20console.log(arr)%3B%0A%20%20return%20arr%3B%0A%7D%0A%0AdropElements(%5B1%2C%202%2C%203%2C%204%5D%2C%20function(n)%20%7Breturn%20n%20%3E%205%3B%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function dropElements(arr, func) {
  // Drop them elements.

  var emp = [];
  //loop through elements seeking the true element, breaking when found. Shifting the elements when not found.
  var end = arr.length;
  if (end === arr.length){
    console.log(true);
  }
  else 
    console.log(false);
//Change this line to for(var i = 0 ; i < end; i++) and it passes returning empty array 
//as is fails to return the empty array
  for(var i = 0; i < arr.length; i++){
    if(func(arr[0])){
        break;
    }
    else{
        arr.shift();
      
    }
  }
  console.log(arr);
  return arr;
}

dropElements([1, 2, 3, 4], function(n) {return n > 5; });

```

**Comment by erictleung** [comment]
@chadg1980 thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: when you run your code for that test, you get back `[3, 4]`; why do you think it stops prematurely? There is a small bug in your code. Happy coding!

**Comment by chadg1980** [comment]
My code returns empty array in my local environment. And the "Help Room" should be broken into sections, because it is pure chaos and I don't go in there anymore.
