### ISSUE TITLE
The example text is wrong in comparison to what's nesseccary to complete the challenge

### ISSUE THREAD

**Issue by Gatreh** [FreeCodeCamp/FreeCodeCamp#10411]
Challenge [Use Conditional Logic with If Statements](https://www.freecodecamp.com/challenges/use-conditional-logic-with-if-statements#?solution=%0A%2F%2F%20Example%0Afunction%20ourTrueOrFalse(isItTrue)%20%7B%0A%20%20if%20(isItTrue)%20%7B%20%0A%20%20%20%20return%20%22Yes%2C%20that%20was%20true%22%3B%0A%20%20%7D%0A%20%20return%20%22No%2C%20that%20was%20false%22%3B%0A%7D%0A%0A%2F%2F%20Setup%0Afunction%20trueOrFalse(wasThatTrue)%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20if(wasThatTrue)%20%7B%0A%20%20%20%20return%20%22Yes.%22%3B%0A%20%20%7D%0A%20%20return%20%22No.%22%3B%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtrueOrFalse(true)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourTrueOrFalse(isItTrue) {
  if (isItTrue) { 
    return "Yes, it's true";
  }
  return "No, it's false";
}

// Setup
function trueOrFalse(wasThatTrue) {

  // Only change code below this line.
  if(wasThatTrue) {
    return "Yes.";
  }
  return "No.";
  
  // Only change code above this line.

}

// Change this value to test
trueOrFalse(true);

```

It sais that it's nesseccary for the "ourTrueOrFalse" function to print "Yes, that was true" or "No, that was false" but this is the initial state of the example code (wich you specifically tell to not tamper with)

**Comment by Gatreh** [comment]
I'm a retard and didn't read what was written properly, ignore this!

**Comment by itsabear** [comment]
If you have problem with certain challenges, consider to ask in Freecodecamp chatroom first.
