### ISSUE TITLE
Strings in the array causes trouble.

### ISSUE THREAD

**Issue by jonasiw** [FreeCodeCamp/FreeCodeCamp#10427]
#### Challenge Name

https://www.freecodecamp.com/challenges/steamroller

#### Issue Description

When the array contains string(s), I get this error: "InternalError: Too much recursion." This does not happen when the array does not contain string(s). 

#### Browser Information

* Browser Name, Version: Firefox 48.0.2 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
 function recurs(heh){
  for(i=0;i<heh.length;i++){
    if(heh[i].length > 0){
      recurs(heh[i]);
    }
    else{
      if(!Array.isArray(heh[i])){
        array.push(heh[i]);
      }
    }
  }
}


function steamrollArray(arr) {
  array = [];
  //return ["a", "b"][1];
    recurs(arr);
  // I'm a steamroller, baby
  return array;
}

steamrollArray(["1", 2]);

 
```
#### Screenshot

![screenshot-www freecodecamp com-2016-09-01-16-31-12](https://cloud.githubusercontent.com/assets/16628166/18171315/d650ff56-7061-11e6-8ba3-d6938e174b76.png)

**Comment by MiloATH** [comment]
Strings have a length property. [See the MDN page.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length) Also you are likely going to run into a problem with global variable i. Message me on gitter or anyone in the [Freecodecamp chat](https://gitter.im/FreeCodeCamp/FreeCodeCamp) if you have more questions. There is no issue with the challenge.

**Comment by BKinahan** [comment]
As @MiloATH said above, your code is unfortunately causing the problem you are experiencing and there is no issue with the challenge.

Please remember to visit the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) when you are stuck with code for the algorithm challenges before raising an issue.

Happy coding!
