### ISSUE TITLE
Simple Workaround for Cursor Location Issues in Editor

### ISSUE THREAD

**Issue by mikeinsf** [FreeCodeCamp/FreeCodeCamp#10421]
The easy and quick workaround is the click the button labeled "Reset" when the challenge loads. For me this reloads the challenge with the code editor working properly.

#### Challenge Name
Global to all challenges

#### Issue Description
This is for the issue where cursor does not go where you place it in the code editor.

#### Browser Information
Chrome on Mac

#### Your Code

```js
 
 
 
```

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for giving advice! Happy Coding!
