### ISSUE TITLE
Have no idea why this example of mine didn't pass

### ISSUE THREAD

**Issue by victorwestmann** [FreeCodeCamp/FreeCodeCamp#10422]
Challenge [Concatenating Strings with the Plus Equals Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-the-plus-equals-operator#?solution=var%20myStr%20%3D%20%22This%20is%20the%20first%20sentence.%20%22%3B%0AmyStr%20%2B%3D%20%22This%20is%20the%20second%20sentence.%22%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStr = "This is the first sentence. ";
myStr += "This is the second sentence.";
```

**Comment by oalhait** [comment]
Confirmed. I'm getting the same issue.

**Comment by BKinahan** [comment]
If you reset the code in your editor you will see a comment line in the original code that looks like this:
`// Only change code below this line`

It's important to only change code where comments like that one instruct you to, or the tests can be interfered with, as has happened here.

Please remember to visit the [Help chat room](https://gitter.im/FreeCodeCamp/Help) before raising an issue when you have a problem with your code, as many errors can be resolved that way without being reported as a bug 😄 

Happy coding!

**Comment by BariqFitri** [comment]
How to solve it? Please help me.
![tuto3](https://cloud.githubusercontent.com/assets/21375993/18337321/150e83c0-75c2-11e6-8733-eabdc2605d1f.PNG)

**Comment by texas2010** [comment]
@BariqFitri, Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
