### ISSUE TITLE
Arrow to go back between way- point challenges

### ISSUE THREAD

**Issue by gabazine** [FreeCodeCamp/FreeCodeCamp#1042]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Should be a simple-fix
Right from the screen an arrow that allows a user to go back in order to check previous solution so that  one can understand why one method is superior to another

**Comment by benschenker** [comment]
Hey @gabazine, thanks for posting.

I'm not sure I understand the request here.  Since it is pretty stale I'm going to close it but feel free to reopen and clarify.
