### ISSUE TITLE
[UI] Entire challenge database page should be made easily accessible + easy map fix

### ISSUE THREAD

**Issue by oalhait** [freeCodeCamp/freeCodeCamp#10423]
As of now, clicking the FCC logo just leads to the next challenge, which is definitely a bit confusing. I think this can be improved by adding two buttons in the left sidebar that take you to the next/previous challenge. 
I also think it would make it easier to collapse the map when the user clicks away from the map itself, rather than having to close the map window by moving the mouse to the x button.

**Comment by atjonathan** [comment]
@oalhait, I mostly agree with all your points. However, I'm not sure about adding more items to the navbar. I'm defiantly up for when you click outside the map, it disappears.

cc/ @FreeCodeCamp/issue-moderators

**Comment by erictleung** [comment]
@oalhait quick navigating out of the map has been brought up already (https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9530).

But in terms of having a previous and next challenge button *somewhere* on the screen might be useful. I'm also hesitant to add more things to the navbar.

**Comment by oalhait** [comment]
@atjonathan @erictleung Yeah, I agree; adding next/back buttons would clutter the navbar a bit too much. However, I don't really see anywhere else to put them other than in the sidebar, maybe right under the title of the activity. Thoughts?

**Comment by QuincyLarson** [comment]
@oalhait @erictleung In the past, we have opted for hotkeys for these sorts of super-user type features. I think we should do the same here.

**Comment by systimotic** [comment]
The shortcut `g n n` is available to move to the next challenge. `g m` opens the map drawer, but it does not close it.
Should clicking outside of the map close it? The styling makes me feel like it shouldn't, for some reason 😕
This might not be relevant anymore when the redesign happens.
What should we do from here?

**Comment by raisedadead** [comment]
we should wait for the redesign, and take this post that.
