### ISSUE TITLE
Codepen Example has Broken Image Links

### ISSUE THREAD

**Issue by mikeinsf** [FreeCodeCamp/FreeCodeCamp#10425]
Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Codepen loads with broken images. 
![image](https://cloud.githubusercontent.com/assets/7199391/18164186/6dcbbff2-6ff3-11e6-9749-eed197cf7812.png)

**Comment by erictleung** [comment]
@mikeinsf thanks for bringing up the issue. I can confirm there's an issue with rendering the images.

cc/ @hallaathrad @raisedadead

**Comment by geeceeza** [comment]
Looks like the source of the images is being redone 
http://qlip.in/

"This whole website's functionality is broken and is thus being 86'd while I am rebuilding it from scratch (That's right Drupal, it's over between us! and it's definitely you, not me! *sigh*).
Dearest unexpected visitor, please bear with me while everything is ready."

**Comment by dhcodes** [comment]
@erictleung maybe we could ask the owner if we could move the image hosting to the AWS server where the cat photo app images are stored.

**Comment by hallaathrad** [comment]
Hey all! thanks for your patience. I've been playing with my server's hot-linking settings for I'd noticed some broadband leakage from people forking the page and linking directly to my server.
I've adjusted it now. Thanks for the report :) and please feel free to reopen if you still see have issues with this.
