### ISSUE TITLE
Right solution and not pass the FCC.

### ISSUE THREAD

**Issue by EssamAHamid** [FreeCodeCamp/FreeCodeCamp#10424]
Challenge [Diff Two Arrays](https://www.freecodecamp.com/challenges/diff-two-arrays#?solution=%0Afunction%20diff(arr1%2C%20arr2)%20%7B%0A%20%20var%20newArr%20%3D%20arr2.concat(arr1)%3B%0A%20%20diffArr%20%3D%20%5B%5D%3B%0A%09for(var%20i%20%3D%200%20%3B%20i%20%3C%20newArr.length%20%3B%20i%2B%2B)%7B%0A%09%09if(arr2.indexOf(newArr%5Bi%5D)%3D%3D%3D%20-1%20%7C%7C%20arr1.indexOf(newArr%5Bi%5D)%3D%3D%3D%20-1)%7B%0A%09%09%09diffArr.push(newArr%5Bi%5D)%3B%0A%09%09%7D%0A%09%7D%0A%0A%0A%20%20return%20diffArr%3B%0A%7D%0A%0Adiff(%5B%22andesite%22%2C%20%22grass%22%2C%20%22dirt%22%2C%20%22pink%20wool%22%2C%20%22dead%20shrub%22%5D%2C%20%5B%22diorite%22%2C%20%22andesite%22%2C%20%22grass%22%2C%20%22dirt%22%2C%20%22dead%20shrub%22%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function diff(arr1, arr2) {
  var newArr = arr2.concat(arr1);
  diffArr = [];
	for(var i = 0 ; i < newArr.length ; i++){
		if(arr2.indexOf(newArr[i])=== -1 || arr1.indexOf(newArr[i])=== -1){
			diffArr.push(newArr[i]);
		}
	}


  return diffArr;
}

diff(["andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"]);

```

**Comment by EssamAHamid** [comment]
I try all the check points . and it pass , but CTRL+ENTER didn't pass.

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
