### ISSUE TITLE
Correct code not working

### ISSUE THREAD

**Issue by ktajpuri** [FreeCodeCamp/FreeCodeCamp#10426]
#### Challenge Name
https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator

#### Issue Description

I am not able to figure out why the code that I am giving as solution is not working.

#### Browser Information
* Browser Name, Version: Google Chrome 52.0.2743.116 m
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

## Instructions

* Assign the value 7 to variable a.

* Assign the contents of a to variable b.
```js
 
// Setup
var a=7;
var b =a;
// Only change code below this line
 
 
```
#### Screenshot

![capture](https://cloud.githubusercontent.com/assets/10725893/18165739/ae4ffcb6-7064-11e6-9e31-7f56a7ffb00a.PNG)

**Comment by ktajpuri** [comment]
Applogies i didn't correctly read the comment. Working fine :+1:

**Comment by BariqFitri** [comment]
// Setup
var a;
var b = 2;

// Only change code below this line
var a = 7;
var b = a;
