### ISSUE TITLE
Remove sneaky console log

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#10434]
Looks like a sneaky little console log has been committed (it was me :sad:).

Can you remove it? 

The offender: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/boot/z-lang-redirect.js#L22

**Comment by suchendra** [comment]
I Fixed it. But the issue is still in open.

**Comment by atjonathan** [comment]
@suchendra, please make a pull request that targets `staging` and use the issue description template to help you :smile:

**Comment by dhcodes** [comment]
@suchendra this page of instructions may help: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md

**Comment by cameronpattisall** [comment]
I made a pull request for this issue fix/console-log

**Comment by dhcodes** [comment]
@cameronpattisall when making a pull request, please use the last selection in the pull request form to reference this issue so the request shows up in this thread.
