### ISSUE TITLE
Typo in the Sum All Primes solution

### ISSUE THREAD

**Issue by lpstandard** [FreeCodeCamp/FreeCodeCamp#10445]
There is a typo in the Sum All Primes solution. 

Sum All Primes

https://github.com/FreeCodeCamp/freecodecamp/wiki/Algorithm-sum-all-primes#sunflower-intermediate-code-solution

#### Issue Description
The typo is in the intermediate solution.  

if(number % i === 0 && number!= i){
          // return true if it is divisible by any number that is not itself. ==> true should be false
             return false;
          }

I would like to create a branch and make a PR, but I have two questions: 

1. I forked and cloned to my local. The guidance is a little confused to me. Should I do git pull --rebase upstream staging before I create a local branch and even if I am on staging branch?

2. Also, I use git checkout -b fix/xxx to create my local branch and got the error "Cannot update paths and switch to branch 'fix/sum' at the same time."

Thanks and please let me know if anything unclear.

**Comment by BKinahan** [comment]
Hi @lpstandard. The github wiki has been deprecated and moved to the [forum](http://forum.freecodecamp.com/).

There is no need for a pull request, you can simply edit the [forum post here](http://forum.freecodecamp.com/t/algorithm-sum-all-primes/16085/5) if you have spent enough time using the forum and gained the ability to edit wiki posts.

Please visit the [HelpContributors chat room](https://gitter.im/FreeCodeCamp/HelpContributors) if you have any further questions. We're here to help.

Happy coding!
