### ISSUE TITLE
Chat room challenge Slack link not sending slack invite to email.

### ISSUE THREAD

**Issue by CryptoGoro** [FreeCodeCamp/freecodecamp#1044]
Challenge http://www.freecodecamp.com/challenges/waypoint-join-our-chat-room has an issue:
Clicking on the circled link opens a new tab with a confirmation that an invite has been sent but an invite never arrives in my inbox. I've changed my freecodecamp email address, checked the spam and tried this is 3 different browsers.
![slack invite](https://cloud.githubusercontent.com/assets/12124684/8270658/f21cb830-17eb-11e5-8257-dfbf3d330cff.png)

**Comment by BerkeleyTrue** [comment]
We hit an undocumented hard limit with Slack and are now moving to Gitter. Please see #1014 and the blog post explaining our move. http://blog.freecodecamp.com/2015/06/so-yeah-we-tried-slack-and-we-deeply-regretted-it.html

We will be updating the challenge shortly with new instruction on how to signup for Gitter, but you can see the video here https://vimeo.com/131321596

Again we are sorry for the inconvenience and hope you have an awesome time with our new Gitter room.
