### ISSUE TITLE
wrong test although my solution is right

### ISSUE THREAD

**Issue by Mograbi** [FreeCodeCamp/FreeCodeCamp#10447]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20var%20filtered%20%3D%20str.split(%22%22).filter(function(val)%20%7B%0A%20%20%20%20return%20((val%20%3E%3D%20'a')%20%26%26%20(val%20%3C%3D%20'z'))%20%7C%7C%20((val%20%3E%3D%20'A')%20%26%26%20(val%20%3C%3D%20'Z'))%3B%0A%20%20%7D).join(%22%22)%3B%0A%20%20var%20reveresed%20%3D%20filtered.split(%22%22).reverse().join(%22%22)%3B%0A%20%20return%20filtered.toLowerCase()%20%3D%3D%3D%20reveresed.toLowerCase()%3B%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function palindrome(str) {
  var filtered = str.split("").filter(function(val) {
    return ((val >= 'a') && (val <= 'z')) || ((val >= 'A') && (val <= 'Z'));
  }).join("");
  var reveresed = filtered.split("").reverse().join("");
  return filtered.toLowerCase() === reveresed.toLowerCase();
}



palindrome("eye");

```

failed the:  palindrome("1 eye for of 1 eye.")
all other tests succeeded, there must not be an issue with that.

**Comment by BKinahan** [comment]
Hi @Mograbi. Unfortunately your solution is not correct, as the instructions specify that numbers should _not_ be removed from the string before checking if it is a palindrome.

Remember to visit the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) when your code does not pass the tests before considering raising an issue.

Happy coding!
