### ISSUE TITLE
193 - Selecting from many options with Switch Statements

### ISSUE THREAD

**Issue by StitchXtreme** [FreeCodeCamp/FreeCodeCamp#10448]
Challenge [Selecting from many options with Switch Statements](https://www.freecodecamp.com/challenges/selecting-from-many-options-with-switch-statements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  switch (val) {
    case 1:
      return "Alpha";
      break;
    case 2:
      return "Beta";
      break;
    case 3:
      return "Gamma";
      break;
    case 4:
      return "Delta";
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(2);


```

I skipped this exsersize because i was confident the code was working. After doing the next exsersize the code used was the same as above but a bit different but was proven right. So there is something wrong in the handling of the request.

**Comment by BKinahan** [comment]
Hi @StitchXtreme, unfortunately your code is incorrect (hint: capitalization).

Remember to visit the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) when your code does not pass the tests in an algorithm challenge before considering raising an issue.

Happy coding!

**Comment by drcharlie98** [comment]
Also, the "return" bits are not right either, but I am happy to have read this because I too was not using caps where none were required.

**Comment by drcharlie98** [comment]
oops, wrong comment. sorry
