### ISSUE TITLE
Smallest Common Multiple. My code work in my Chrome, but can not through FCC.

### ISSUE THREAD

**Issue by bellson0d** [FreeCodeCamp/FreeCodeCamp#10453]
#### Challenge Name

Smallest Common Multiple.

#### Issue Description

Code can get right result in my browser. But FCC feedback is wrong. 

#### Browser Information

* Browser Name, Version: Chrome 51.0.2704.106 m
* Operating System: window 7
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 function smallestCommons(arr) {
	  arr.sort(function(a,b){return a-b;});
	  var flag = 0;
	  for ( var j = arr[1] ; ; j++ ){
	    flag = 0;
	    for ( var i = arr[0] ; i < arr[1]+1 ; i++ ){
	      if ( j%i !== 0 ){
	        flag = 1;
	        break;
	      }
	    }
	    if ( flag === 0 )return j;
	  }
	}
 
 
```

**Comment by erictleung** [comment]
@bellson0d your code will work on FreeCodeCamp but with a little change. You'll need to add `// noprotect` to the first line of your editor to pass the challenge.

The loop protect is intended to prevent infinite loops to keep the browser from crashing and sometimes has false-positives. Happy coding!

**Comment by bellson0d** [comment]
Thank you very much!:) 






At 2016-09-04 03:21:29, "Eric Leung" <notifications@github.com> wrote:


@bellson0d your code will work on FreeCodeCamp but with a little change. You'll need to add // noprotect to the first line of your editor to pass the challenge.

The loop protect is intended to prevent infinite loops to keep the browser from crashing and sometimes has false-positives. Happy coding!
