### ISSUE TITLE
404: We couldn't find the challenge...

### ISSUE THREAD

**Issue by solo800** [FreeCodeCamp/FreeCodeCamp#1045]
I think this is relatively self explanatory.
![image](https://cloud.githubusercontent.com/assets/5925213/8271045/7708f870-182c-11e5-9106-34a77145d64c.png)

**Comment by BerkeleyTrue** [comment]
Not really. 

Which challenge where you trying to find?

**Comment by solo800** [comment]
On one of the very early challenges, "Waypoint: Size your Images" the page loads however at the top of the page (just below the header) there is a 404 error message saying there is no challenge with that name. 

Here's the issue though, I didn't go looking for any challenge. I had just completed the previous challenge and so it automatically loaded the next challenge.

**Comment by BerkeleyTrue** [comment]
This looks like it happen on the old site. Please reopen if you are still running into the issue.
