### ISSUE TITLE
Broken images on Wiki: "How to Start When Stuck II"

### ISSUE THREAD

**Issue by dropTheNon** [FreeCodeCamp/FreeCodeCamp#10450]
#### Wiki: How to Start When Stuck II"
[](https://github.com/FreeCodeCamp/freecodecamp/wiki/How-To-Start-When-Stuck-II)

#### Issue Description
Images aren't showing up.

#### Browser Information
* Found on Safari 9.1.1, replicated on Chrome 52.0.2743.116
* Operating System: OSX El Capitan v 10.11.5 
* Desktop

**Comment by erictleung** [comment]
@dropTheNon thanks for the issue. We've moved our Wiki to the [forum](http://forum.freecodecamp.com) so that page you're looking for is [here](http://forum.freecodecamp.com/t/how-to-start-when-you-are-stuck/19427). Happy coding!
