### ISSUE TITLE
"Big O Notation: A Few Examples" Transcript Typo

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/FreeCodeCamp#10457]
#### Challenge Name

https://www.freecodecamp.com/videos/big-o-notation-a-few-examples

#### Issue Description

There is a typo in the first line of the transcript. It currently is

> ...a fixed amount of time to **preform**) performed in the algorithm.

#### To Fix
[This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/666f9c83b66a53e16bf411ba3a367996afcc1d54/seed/challenges/04-video-challenges/bigonotation.json#L55) needs to be fixed to be

> ...a fixed amount of time to **perform**) performed in the algorithm.

#### Screenshot

![screenshot 2016-09-03 at 17 12 41](https://cloud.githubusercontent.com/assets/2754821/18228238/ac519870-71f9-11e6-81e7-41617719ce53.png)

**Comment by myang310** [comment]
Hi Eric. New to contributing, but can I work on this?

**Comment by erictleung** [comment]
@myang310 go for it! Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by myang310** [comment]
I submitted my pull request! #10461
