### ISSUE TITLE
Symmetric Differences - Incorrect Test Cases

### ISSUE THREAD

**Issue by kirakirakira** [FreeCodeCamp/FreeCodeCamp#10456]
#### Symmetric Differences
https://www.freecodecamp.com/challenges/symmetric-difference

#### Issue Description
Test 5, 7, 9 pass but 6, 8, and 10 do not.
![symdifftests](https://cloud.githubusercontent.com/assets/3029437/18227931/555128aa-7204-11e6-9f45-4e21e76a52b8.png)

It is impossible to return an array of the exact 3 elements the test was expecting and the array also not have a length of 3. I'm assuming there's something wrong in the test cases. Is there not a solution run against these tests to make sure they all pass together?

**Comment by erictleung** [comment]
@kirakirakira you should be returning an array. Those tests you are not passing do a `.length` on your "array" returned. So if you did not return an array, that might be the problem. 

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). 

I can't tell if your issue is an issue with your code or with the challenge tests. Can you post your code for us to verify where the error is coming from? Thanks!

**Comment by kirakirakira** [comment]
@erictleung I found the issue. The arrays I was returning were indeed not the correct length. However, tests 5, 7, and 9 are poorly worded because they are not checking that it returns that exact array listed. My code was not returning that array (I had not removed non-unique values), and it passed the test. If the tests are only checking that the array contains those values, then that is how the test description should be listed.

**Comment by BerkeleyTrue** [comment]
Hey @kirakirakira,

 Can you post your code?

**Comment by kirakirakira** [comment]
Here's the code that caused tests 6, 8, and 10 to not pass:
```javascript
let sym = (...sets) => sets.reduce((s1, s2) => {
  let result = [];
  s1.forEach(function(element) {
    if (s2.indexOf(element) === -1) {
      result.push(element);
    }
  });
  s2.forEach(function(element) {
    if (s1.indexOf(element) === -1) {
      result.push(element);
    }
  });
  return result;
}, []);
```

Here's updated code to remove duplicates:
```javascript
let sym = (...sets) => sets.reduce((s1, s2) => {
  let result = [];
  s1.forEach(function(element) {
    if (s2.indexOf(element) === -1) {
      if (result.indexOf(element) === -1) result.push(element);
    }
  });
  s2.forEach(function(element) {
    if (s1.indexOf(element) === -1) {
      if (result.indexOf(element) === -1) result.push(element);
    }
  });
  return result;
}, []);
```

To further prove, there's something wrong with the tests, if I just do this:
```javascript
function sym() {
  return [1,1,4,4,5,5];
}
```
I pass tests 3 and 5 even though [1,1,4,4,5,5] is not the same array as [1,4,5].
![symdiffsimpletest](https://cloud.githubusercontent.com/assets/3029437/18394059/16092f90-7686-11e6-9e9b-3171b2fed7fa.png)

**Comment by kirakirakira** [comment]
Sorry if this isn't the place, but I finally figured out where the code was that ran the tests. Does the 'assert.sameMembers' only check that members are in that array? So that does not solve the issue of the tests 3 and 5 passing as long as I return an array with only 1's, 4's, and 5's in it? I don't understand. If you aren't testing that it returns a specific array, then why is that listed as the test in the problem description. Why can't we just list the actual test code in the problem descriptions?
