### ISSUE TITLE
npm video

### ISSUE THREAD

**Issue by tspelle** [FreeCodeCamp/FreeCodeCamp#10452]
the npm video does not match what you get when you actually go to cloud9 and create account, etc... need to update!

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by atjonathan** [comment]
@tspelle, please provide more details on the issue.

**Comment by atjonathan** [comment]
Closing as stale. Please reopen if this issue is legitimate!

**Comment by tspelle** [comment]
Look at first npm video and execute actions, you'll see that screens, urls,
actions do not match... Ypu should update. A tutorial video is supposed to
help, but it confused me. Thanks.

**Comment by atjonathan** [comment]
@tspelle, we will be replacing that challenge with our own challenges very soon!
