### ISSUE TITLE
Less information given

### ISSUE THREAD

**Issue by Kshitij0000** [FreeCodeCamp/FreeCodeCamp#10454]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by texas2010** [comment]
@Kshitij0000, You need to fill it up. please

**Comment by atjonathan** [comment]
Closing as stale. Please reopen if this issue is legitimate!
