### ISSUE TITLE
Updating profile from GitHub should show a notification and redirect to FCC profile

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#10463]
#### Issue Description
Steps to reproduce:
- Make sure you've previously linked GitHub with your Free Code Camp account
- Go to https://www.freecodecamp.com/settings
- click "update my portfolio from GitHub"
- it will do so, then redirect you back to your current challenge, but it won't show any confirmation flash message.

Instead, it should show a success flash message that says "We've updated your profile based on your your GitHub account."

While we're at it, we should change the redirect to send campers to their profile so they can confirm themselves that their biographical information has been updated.

Finally, we should change the button from "update my portfolio from GitHub" to "update my profile from GitHub" since campers often mistakenly expect us to pull in data about their actual GitHub projects - which we do not yet do.

CC @BerkeleyTrue

**Comment by craigstroman** [comment]
Hi, 

I would be interested in working on this.

**Comment by craigstroman** [comment]
Is there any place I can go to get help with my local environment?  All the sudden it seems to have stopped working.

I'm on OS X 10.9.5, using Node 6.5.0, NPM 3.10.3, and Mongo 3.2.9.

Thank you.

**Comment by QuincyLarson** [comment]
@craigstroman did you follow this guide? http://forum.freecodecamp.com/t/how-to-fork-and-maintain-a-local-instance-of-free-code-camp/19116
