### ISSUE TITLE
Go to my next challenge button sometimes jumping me at random

### ISSUE THREAD

**Issue by arielleslie** [FreeCodeCamp/freecodecamp#1046]
Sometimes when I select "Go to my next challenge" I get sent to a random challenge far ahead of where I should be, apparently at random. After "Waypoint: Use Clockwise Notation to Specify the Margin of an Element" I was sent to "Bonfire: Roman Numeral Converter" and after "Waypoint: Mobile Responsive Images" I was sent to "Zipline: Build a Random Quote Machine".

**Comment by jbmartinez** [comment]
It sometimes jump to a previous challenge too. I get sent to "Waypoint: Add Rounded Corners with a Border Radius" after "Waypoint: Warn your Users of a Dangerous Action"

**Comment by LumenTeun** [comment]
I believe this is a duplicate of  #893.

**Comment by BerkeleyTrue** [comment]
This is a duplicate. @arielleslie we will update at #893 Thanks for reporting.
