### ISSUE TITLE
Not intuitive, the way the problem is explained you would expect the code to look like this $(".well:nth-child(2)").addClass("animated bounce");

### ISSUE THREAD

**Issue by Aldon2** [FreeCodeCamp/FreeCodeCamp#10465]
Challenge [Target a Specific Child of an Element Using jQuery](https://www.freecodecamp.com/challenges/target-a-specific-child-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
    $("#right-well").children().css("color", "orange");
    $(".target:nth-child(2)").addClass("animated bounce");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by Aldon2** [comment]
$(".well:nth-child(2)").addClass("animated bounce"

**Comment by dhcodes** [comment]
@Aldon2 I think the instructions are alright as is, particularly because they give an example directly above the challenge prompts that explains how to add `animated shake` to the third element. What exact wording would you want to use to improve the challenge?

**Comment by Aldon2** [comment]
Hi @dhcodes thanks for your reply for the sake of brevity I have copied and pasted a reply from @fuecisla 

He says


"If you follow their instructions you are NOT targeting a specific child (nth-child) of a single element you are targeting the nth-child of ALL the elements that have children of a given class (the class target). How can you target the nth child of a parent element?? No idea (my guess is by using the id).

I think that the example is to blame, but only partially. JS is not so intuitive because:

You would expect to find the children by a reference to who are their parents (their name or at least the parents class).
However, at least in this example, JS only uses the parents to identify find second child.
In other words, this example does not teach you to find the second boy of all the parents called "Smith" or of an specific family. It shows you to find the second blond boy of all the families that have blond boys."

Frankly, I don't understand the concept well enough to recommend any change in the instructional notes but I do feel it could be explained better. 

I struggled because I felt I should use .well:nth-child(2) to "target" the element I think the confounder here is the word "target" because its used often to describe how jQuery "targets" elements in the DOM and in this case .target is the "target'. 

I apologise if this is a frivolous issue it is not my intent to waste your time.

Thanks for looking into this anyhow.

**Comment by msanecki** [comment]
I would extend the instruction/explanation by this one sentence:
"The :nth-child(n) selector selects all elements that are the nth child, **regardless of type, of their parent**"

**Comment by jritxal** [comment]
From what I understand nth-child(n) has nothing to do with childs since it selects the nth element of its own class

**Comment by t0cc** [comment]
I agree with @msanecki , the instructions read like we are supposed to select the second **inside** of the ".well" class:

    $(".well:nth-child(2)").addClass("animated bounce");

instead of targeting the n-th element of the selected class within any parent element:

    $(".target:nth-child(2)").addClass("animated bounce");

**Comment by acinf** [comment]
I think there needs to be some kind of clearer wording indicating that you want to jQuery-target the 3rd element in a group made up of elements with 'target' class.

Somewhere, probably before this step, there could be something along the lines of "when you use a selector jQuery creates a group containing all the matching elements". Then in this example there could be a text stating something like " :nth-child(x) finds the nth-child in the group created by finding all the elements matching 'target'".

Also, having a class being "target" when the same word is used to describe a concept seems prone to failure
