### ISSUE TITLE
Free Code Camp - Challenge Escape Sequences in Strings has an issue.

### ISSUE THREAD

**Issue by danieladide** [FreeCodeCamp/FreeCodeCamp#10476]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 UBrowser/5.7.14488.1025 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr; // Change this line
myStr = "\nFirstLine\n\\SecondLine\\\rThirdLine";



```

**Comment by BKinahan** [comment]
Hi @danieladide. Unfortunately your code is incorrect; there should not be a newline character before `FirstLine`

Please remember to visit the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) when you have problems writing code for the JavaScript challenges before raising an issue about the challenge.

Happy coding!
