### ISSUE TITLE
Create a bootstrap row

### ISSUE THREAD

**Issue by smartbed786** [FreeCodeCamp/FreeCodeCamp#10474]
#### Challenge Name
  <Create a bootstrap row>

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```
<div class="container-fluid">
  <div class="row">
    <h3 class="text-primary text-center">jQuery Playground</h3>
     </div>
    <div class="row"></div>
</div>
``` 

#### Screenshot
 

<img width="960" alt="codecamps" src="https://cloud.githubusercontent.com/assets/21959449/18245380/8036300e-7382-11e6-94f3-3a5a618aa4b3.png">

**Comment by erictleung** [comment]
@smartbed786 thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). 

Hint: Reset your code and try again. You've added too many new `<div>` elements. You just need to add a `<div>` element below the `<h3>` element.

Happy coding!
