### ISSUE TITLE
Wrong expected results in Bonfire: Smallest Common Multiple

### ISSUE THREAD

**Issue by keepofone** [FreeCodeCamp/freecodecamp#1047]
![bonfire](https://cloud.githubusercontent.com/assets/7230306/8272485/7caad4d4-1844-11e5-8fb7-0377135de6b9.png)

Either expected results or input arrays are wrong:

<pre>
expect(smallestCommons([1,5])).to.equal(60);expected 5 to equal 60
expect(smallestCommons([5,1])).to.equal(60);expected 5 to equal 60
</pre>
The 60 is true for smallestCommons([12,5]) but for the [1,5] it's 5.

<pre>
expect(smallestCommons([1,13])).to.equal(360360);expected 13 to equal 360360
</pre>
Here, perhaps, it's smallestCommons([27720,13])

**Comment by terakilobyte** [comment]
Incorrect. The smallest number the range divides into is 60.

http://m.wolframalpha.com/input/?i=lcm%281%2C+2%2C3%2C4%2C5%29&x=0&y=0

**Comment by keepofone** [comment]
Oh.. the range. Sorry.

**Comment by keepofone** [comment]
Thanks!

**Comment by terakilobyte** [comment]
No worries, better to clarify! Enjoy

**Comment by resistancecanyon** [comment]
I also got confused the range with LCM. But why is the referral link given to https://www.mathsisfun.com/least-common-multiple.html ? which is basically LCM.
Maybe I'm wrong, better be more clear on the description?
