### ISSUE TITLE
I don't know how to resolve this///

### ISSUE THREAD

**Issue by vesa193** [FreeCodeCamp/FreeCodeCamp#10488]
Challenge [Make Object Properties Private](https://www.freecodecamp.com/challenges/make-object-properties-private#?solution=%0Avar%20Car%20%3D%20function()%20%7B%0A%20%20%2F%2F%20this%20is%20a%20private%20variable%0A%20%20var%20speed%20%3D%2010%3B%0A%0A%20%20%2F%2F%20these%20are%20public%20methods%0A%20%20this.accelerate%20%3D%20function(change)%20%7B%0A%20%20%20%20speed%20%2B%3D%20change%3B%0A%20%20%7D%3B%0A%0A%20%20this.decelerate%20%3D%20function()%20%7B%0A%20%20%20%20speed%20-%3D%205%3B%0A%20%20%7D%3B%0A%0A%20%20this.getSpeed%20%3D%20function()%20%7B%0A%20%20%20%20return%20speed%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20Bike%20%3D%20function()%20%7B%0A%20%20var%20gear%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20this.getGear%20%3D%20function(change)%7B%0A%20%20%20%20gear%20-%3D%20change%3B%20%20%0A%20%20%20%20change%20%3D%203%3B%0A%20%20%0A%20%20%7D%3B%0A%20%20this.setGear%20%3D%20function(num)%7B%0A%20%20%20%20return%20gear%3B%0A%20%20%7D%3B%0A%20%20%0A%7D%3B%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0A%0Avar%20myBike%20%3D%20new%20Bike()%3B%0AmyBike.getGear()%3B%0AmyBike.setGear(6)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {
  var gear;
  // Only change code below this line.
  this.getGear = function(change){
    gear -= change;  
    change = 3;
  
  };
  this.setGear = function(num){
    return gear;
  };
  
};

var myCar = new Car();

var myBike = new Bike();
myBike.getGear();
myBike.setGear(6);

```

**Comment by dhcodes** [comment]
@vesa193, there is an error in your code. Please check out the [Help Javascript](https://gitter.im/FreeCodeCamp/HelpJavaScript) chat room for Free Code Camp to get assistance. If you feel there is a bug in the challenge, please reply here. Happy coding!
