### ISSUE TITLE
issue with creating a bootstrap issue code, everything is right on the output but the program doesnt like my code

### ISSUE THREAD

**Issue by erikarntson** [FreeCodeCamp/FreeCodeCamp#10483]
Challenge [Create a Bootstrap Headline](https://www.freecodecamp.com/challenges/create-a-bootstrap-headline#?solution=%3Cdiv%20class%3D%22text-primary%20text-center%22%3E%3Ch3%3EjQuery%20Playground%20%0A%20%20%3C%2Fh3%3E%3C%2Fdiv%3E%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<div class="text-primary text-center"><h3>jQuery Playground 
  </h3></div>




```

**Comment by erictleung** [comment]
@erikarntson thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). 

Hint: the tests that are failing are 

`Your h3 element should be colored by applying the class text-primary` and

`Your h3 element should be centered by applying the class text-center`.

The new changes need to be applied to the `h3` element directly.
 
Closing as not an issue with the site. Happy coding!
