### ISSUE TITLE
Show the Local Weather: Change challenge since codepen.io is not HTTPS

### ISSUE THREAD

**Issue by miguel-orange** [FreeCodeCamp/FreeCodeCamp#10484]
_getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details._

Challenge [Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by miguel-orange** [comment]
moreover, I changed to https://codepen.io, now I get this error _Mixed Content: The page at 'https://codepen.io' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.openweathermap.org/data/2.5/weather?.... This request has been blocked; the content must be served over HTTPS._
and well openweathermap.org, doesn't work with https.

**Comment by erictleung** [comment]
@miguel-orange thanks for the issue. This is a known issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9145. Take a look at the discussion there for some ideas how to work around it.

Here are a proposed change and additional work around for this challenge https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10341.

Closing as duplicate issue. Happy coding!
