### ISSUE TITLE
BETA Site - Multiple Reset Buttons

### ISSUE THREAD

**Issue by timmyconnect** [FreeCodeCamp/freecodecamp#1048]
Challenge http://www.freecodecamp.org/challenges/bonfire-make-a-person has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Minor bug in layout.

You have multiple Reset Buttons showing. 
![screen shot 2015-06-21 at 7 42 01 pm](https://cloud.githubusercontent.com/assets/6411774/8272728/94ff3796-184e-11e5-9525-5466a55f8e06.png)

First small Reset button opens help modal.
Second small Reset button does nothing.
Third Button(Help) does nothing.
Pair and Bug button working correctly.

Regards

**Comment by terakilobyte** [comment]
It looks like this has been fixed, thanks for the report!
