### ISSUE TITLE
Spinal Tap Case wrong code passed the tests.

### ISSUE THREAD

**Issue by crumpx** [FreeCodeCamp/FreeCodeCamp#10481]
Challenge [Spinal Tap Case](https://www.freecodecamp.com/challenges/spinal-tap-case#?solution=function%20spinalCase(str)%20%7B%0A%20%20%2F%2F%20%22It's%20such%20a%20fine%20line%20between%20stupid%2C%20and%20clever.%22%0A%20%20%2F%2F%20--David%20St.%20Hubbins%0A%20%20str%20%3D%20str.replace(%2F(%5B%5E%5BA-Za-z-%5D)%7C%5Cw(%5BA-Z%5D)%2Fg%2C%20function%20(match%2C%20offset%2C%20string)%20%7B%0A%20%20%20%20%20%20if%20(string%20%3D%3D%3D%20undefined)%7B%0A%20%20%20%20%20%20return%20'-'%3B%0A%20%20%20%20%20%7D%20else%20%7Breturn%20match.substr(offset%2C1)%2B%20'-'%20%2B%20string%3B%7D%0A%20%20%7D).toLowerCase()%3B%0A%20%20return%20str%3B%0A%7D%0A%0AspinalCase(%22thisIsSpinalTap%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This code will pass the test. I wrote the callback parameter wrong and it still pass.

My code:
```javascript
function spinalCase(str) {
  // "It's such a fine line between stupid, and clever."
  // --David St. Hubbins
  str = str.replace(/([^[A-Za-z-])|\w([A-Z])/g, function (match, offset, string) {
      if (string === undefined){
      return '-';
     } else {return match.substr(offset,1)+ '-' + string;}
  }).toLowerCase();
  return str;
}

spinalCase("thisIsSpinalTap");
```

**Comment by abhisekp** [comment]
@crumpx The test checks if the **`spinalCase`** function returns the desired return value for given parameter value.

The test doesn't check if the callback params of `String#replace` method.
You may want to ask for review in [![**`FreeCodeCamp/CodeReview`**](https://img.shields.io/badge/Gitter_Chat_Room:-FreeCodeCamp/CodeReview_⮭-006400.svg?style=flat-square&maxAge=2592000 "FreeCodeCamp/CodeReview")](https://gitter.im/FreeCodeCamp/CodeReview)
