### ISSUE TITLE
Find the Longest Word in a String

### ISSUE THREAD

**Issue by thinkC** [FreeCodeCamp/FreeCodeCamp#10482]
#### Find the Longest Word in a String

https://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=var%20longest%20%3D%200%3B%0Afunction%20findLongestWord(str)%20%7B%0A%20%20x%20%3D%20str.split(%22%20%22)%3B%0A%0A%20%20%0A%20%20for(i%20%3D%200%3B%20i%20%3C%20x.length%3B%20i%2B%2B)%7B%0A%20%20%20%20if(x%5Bi%5D.length%20%3E%20longest)%7B%0A%20%20%20%20%20%20longest%20%3D%20x%5Bi%5D.length%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20longest%3B%0A%20%20%0A%7D%0A%0AfindLongestWord(%22May%20the%20force%20be%20with%20you%22)%3B%0A

#### Issue Description

My code is correct but this challenge will not mark it as correct
findLongestWord("May the force be with you") should return 5
Kindly assist

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop

#### Your Code
 var longest = 0;
function findLongestWord(str) {
  x = str.split(" ");

  
  for(i = 0; i < x.length; i++){
    if(x[i].length > longest){
      longest = x[i].length;
    }
  }
  return longest;
  
}

findLongestWord("May the force be with you");

```js
 
 
 
```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/10897252/18256780/ebb90728-73b1-11e6-8f26-264db6a1f156.png)
![image](https://cloud.githubusercontent.com/assets/10897252/18256809/37925212-73b2-11e6-81d4-0faae78c8d1c.png)

**Comment by BKinahan** [comment]
Your code doesn't work for the tests because they are run by calling the function multiple times, and since you use a global variable `longest` that is not reset for each function call, incorrect values are returned.

Please visit the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you have any other questions about this.

Happy coding!

**Comment by thinkC** [comment]
Thanks BKinahan. Figured it out now.

**Comment by BariqFitri** [comment]
Look at here.I got it
![tuto5](https://cloud.githubusercontent.com/assets/21375993/18341212/854a34f4-75db-11e6-8503-77485d769bab.PNG)

**Comment by pocahontas123** [comment]
function findLongestWord(str) {
				var tableau = [];
				tableau = str.split(" ");
				var tabLength = tableau.length;
				var longestStr = 0;
			  
				for(var k = 0; k < tabLength; k++) {
					if(tableau[k].length >= longestStr) {
					longestStr = tableau[k].length;
					}
				}		  
				return longestStr;
			}

			findLongestWord("The quick brown fox jumped over the lazy dog"));
		
			function findLongestWord(str) {

				var tableau = [];
				var tab2 = [];
				var newTab = [[], []];
				var longestStr = 0;
				tableau = str.split(" ");
				
				for(var k = 0; k < tableau.length; k++) {
					tab2[k] = tableau[k].length;
					newTab = [tableau[k], tab2[k]];
			
					if(newTab[[k],[1]] > longestStr){ 					
						longestStr = newTab[[k],[1]]; 			
					}
				}
				return longestStr;
			}			
			findLongestWord("What if we try a super-long word such as otorhinolaryngology"));``
