### ISSUE TITLE
Tumblr share button links to dead page

### ISSUE THREAD

**Issue by ampersamd** [FreeCodeCamp/FreeCodeCamp#10480]
#### Challenge Name

[Build A Random Quote Machine](https://www.freecodecamp.com/challenges/build-a-random-quote-machine)

#### Issue Description

The button to share a quote on Tumblr directs to dead page. Links below:

https://www.tumblr.com/widgets/share/tool?posttype=quote&tags=quotes,freecodecamp&caption=Galileo%20Galilei&content=I%20do%20not%20feel%20obliged%20to%20believe%20that%20the%20same%20God%20who%20has%20endowed%20us%20with%20sense%2C%20reason%2C%20and%20intellect%20has%20intended%20us%20to%20forgo%20their%20use.

https://www.tumblr.com/widgets/share/tool?posttype=quote&tags=quotes,freecodecamp&caption=Oscar%20Wilde&content=Some%20cause%20happiness%20wherever%20they%20go%3B%20others%2C%20whenever%20they%20go.

#### Browser Information

* Browser Name, Version: Safari 9.1.1
* Operating System: OS X 10.11.5
* Mobile, Desktop, or Tablet: MacBook Pro

#### Screenshot

<img width="1262" alt="screen shot 2016-09-05 at 1 18 23 pm" src="https://cloud.githubusercontent.com/assets/12129911/18254395/47d1b06a-736b-11e6-8a7b-a7262bc7b0e9.png">

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by ampersamd** [comment]
@atjonathan I'm not asking for help, as this isn't on my personal Random Quote Machine, but on the Free Code Camp's example site. Thought this was the right forum to alert the FreeCodeCamp team of issues...

**Comment by atjonathan** [comment]
@ampersamd, sorry I didn't understand the issue! Reopening as `confirmed`.

**Comment by chenriquez51** [comment]
@ampersamd @atjonathan Based on the [Tumblr documentation](https://www.tumblr.com/docs/en/share_button#canonical-url), it looks like a `canonicalUrl` query param is required when creating a custom share link.

I [created a fork](https://codepen.io/xiano51/full/qaEYbr/) of the CodePen with updated Tumblr share logic that works.

**Comment by atjonathan** [comment]
@chenriquez51 awesome!
Tagging @QuincyLarson to fork @chenriquez51's fork to the FreeCodeCamp account. Then we will need to update the links in the challenge seed.

**Comment by AnacletoGit** [comment]
Enviado de Samsung Mobile.

-------- Mensagem original --------
De : Jonathan <notifications@github.com> 
Data: 06/09/2016  09:21  (GMT+02:00) 
Para: FreeCodeCamp/FreeCodeCamp <FreeCodeCamp@noreply.github.com> 
Assunto: Re: [FreeCodeCamp/FreeCodeCamp] Tumblr share button links to dead
  page (#10480) 

@chenriquez51 awesome! Tagging @QuincyLarson to fork @chenriquez51's fork to the FreeCodeCamp account. Then we will need to update the links in the challenge seed. —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by QuincyLarson** [comment]
@chenriquez51 Thanks for pointing this out and looking into how to fix it. I didn't even realize there was a tumblr button on this project example. There shouldn't be. I've removed it from the template.
