### ISSUE TITLE
mv

### ISSUE THREAD

**Issue by mv4design** [FreeCodeCamp/FreeCodeCamp#10495]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%3Ci%3Eitalic%3C%2Fi%3E%0A%3C%2Fbr%3E%0A%3Cbold%3EBold%3C%2Fbold%3E%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch2%3EHello%3C%2Fh2%3E%0A%3Cp%3ELorem%20ipsum%20dolor%20sit%20amet%2C%20consectetur%20adipisicing%20elit%2C%20sed%20do%20eiusmod%20tempor%20incididunt%20ut%20labore%20et%20dolore%20magna%20aliqua.%3C%2Fp%3E%0A%0A%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<i>italic</i>
</br>
<bold>Bold</bold>
<h1>Hello</h1>
<h2>Hello</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>






```

**Comment by BerkeleyTrue** [comment]
The issue tracker is for reporting bugs only. If this is an issue for help with a challenge, please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
