### ISSUE TITLE
CSS Class to Style an Element challenge  bug

### ISSUE THREAD

**Issue by VAO11** [FreeCodeCamp/FreeCodeCamp#10497]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 5.0.2; SM-P900 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

The h2 element is not recognising the red-text class

**Comment by VAO11** [comment]
This works ok on my laptop.

**Comment by erictleung** [comment]
@VAO11 thanks for the issue. This is, unfortunately, a known issue (https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7753). Sometimes Android renders the CSS oddly and adds strange characters to your editor. Take a look at the discussion in the other issue if you're curious. Closing as a duplicate issue. Happy coding!
