### ISSUE TITLE
Branches aren't just for birds

### ISSUE THREAD

**Issue by eltnux** [FreeCodeCamp/FreeCodeCamp#10494]
#### Challenge Name
https://www.freecodecamp.com/challenges/save-your-code-revisions-forever-with-git

git-it - Branches aren't just for birds

#### Issue Description
I'm getting the following error message when i try and verify the following ch

```
"{ [Error: Command failed: /bin/sh -c git config user.username" != "Found branch as expected!"    
"]"                             != "Changes have been pushed!"    
"  killed: false,"              != "File in contributors folder!" 
"  code: 1,"                    != ""                             
"  signal: null,"               != null                           
"  cmd: '/bin/sh -c git config user.username' }" != null                           
""                              != null                           
# FAIL
```

I've looked at my github repository (patchwork) and in the branch (eltnux) for the repository and i can see my add-eltnux.txt file in the contributors folder but i'm failing.

#### Browser Information
* Browser Name, Version: Google Chrome, Version 52.0.2743.116 m
* Operating System: Windows 10 Aniversary
* Mobile, Desktop, or Tablet: Laptop

**Comment by BerkeleyTrue** [comment]
This issue is unrelated to FCC itself. Please open this issue against the git-it repo [here]( https://github.com/jlord/git-it)

Happy Coding

**Comment by Kalinaki** [comment]
I get something similar. I believe there is a contradiction between the 1st requirement and 2nd and 3rd requirements. The 1st requirement asks that your branch name is      add-"yournamehere"
At the same time your branch name should match your GitHub username.

Please verify.
