### ISSUE TITLE
Stand in Line JavaScript

### ISSUE THREAD

**Issue by raku1089** [FreeCodeCamp/FreeCodeCamp#10493]
#### Stand in Line JavaScript

nextInLine([5,6,7,8,9], 1) should return 5

and it returns but test case s failing

#### Browser Information
r 
* Browser Name, Version:   google chrome 
* Operating System:  windows 8
* Mobile, Desktop, or Tablet:  desktop

#### Your Code

```js
 
 
function nextInLine(arr, item) {
  // Your code here
  testArr.push(item);
  return testArr.shift();  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];
// Display Code
//testArr=[5,6,7,8,9];
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 1)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

 
```

**Comment by loccyone** [comment]
> "The nextInLine function should then return the element that was removed."
So, instead of an array returned from the function **.shift()**, nextInLine should return a number element.
