### ISSUE TITLE
I am able to pass this exercise with a wrong solution

### ISSUE THREAD

**Issue by mrehmansaeed** [FreeCodeCamp/FreeCodeCamp#10492]
Challenge [Add Elements within your Bootstrap Wells](https://www.freecodecamp.com/challenges/add-elements-within-your-bootstrap-wells)

The exercise asks you to nest three button elements in each div element containing the `.well` class. I wanted to report a bug I found. I was able to pass this test by nesting six button elements in only one div element containing the `.well` class,
My code:
```html

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">



      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <button></button>
        <button></button>
        <button></button>
        <button></button>
        <button></button>
        <button></button>
               




      </div>
    </div>
  </div>
</div>

```

**Comment by gregersen12** [comment]
Can you include a link to the particular challenge and a description of the expected input for the uninitiated?

**Comment by BKinahan** [comment]
The first test checks for at least 6 buttons within any `div` with the `well` class, when it should test that each of the two wells has 3 buttons.
