### ISSUE TITLE
A problem when i run a challenge -- help

### ISSUE THREAD

**Issue by MK4Tech** [FreeCodeCamp/FreeCodeCamp#10504]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Afunction%20titleCase(str)%20%7B%0A%20%20%0A%20%20var%20space%20%3D'%20'%3B%0A%20%20var%20wordsArr%20%3D%20str.split(space)%3B%0A%20%20var%20newStr%3D%22%22%3B%0A%20%0A%20%20for(var%20i%3D0%3B%20i%3CwordsArr.length%3B%20i%2B%2B)%0A%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20newStr%20%2B%3D%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wordsArr%5Bi%5D.charAt(0).toUpperCase()%20%2B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wordsArr%5Bi%5D.substr(1%2CwordsArr%5Bi%5D.lenght).toLowerCase()%20%2B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%20%22%3B%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%0A%20%20%20%20%20%7D%20%20%0A%20%20%0A%20%0A%20%20%0A%20%20return%20newStr%3B%0A%7D%0A%0AtitleCase(%22sHoRt%20AnD%20sToUt%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function titleCase(str) {
  
  var space =' ';
  var wordsArr = str.split(space);
  var newStr="";
 
  for(var i=0; i<wordsArr.length; i++)
     {
       
              newStr +=                                                                                             wordsArr[i].charAt(0).toUpperCase() +                                                     wordsArr[i].substr(1,wordsArr[i].lenght).toLowerCase() +  " ";                                                                                                                 
       
     }  
  
 
  
  return newStr;
}

titleCase("sHoRt AnD sToUt");

```

**Comment by dhcodes** [comment]
@MK4Tech Your code is mostly correct, but you have an error. Issues is not the arena for code help, but if you want to reach out to me on the [Help Chat](https://gitter.im/FreeCodeCamp/Help), using an @ mention, I will be happy to help. Happy coding!
