### ISSUE TITLE
wording for this step is off

### ISSUE THREAD

**Issue by borromeotlhs** [FreeCodeCamp/FreeCodeCamp#10507]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20p%20%7B%0A%20%20%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A%20%20) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
    
  }
  
  p {
      font-size: 16px;
    }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>


<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
  
```

> Inside the same <style> tag that contains your red-text class, create an entry for p elements and set the font-size to 16 pixels (16px).

should probably read:

> Inside the same <style> tag, below your red-text class, create an entry for p elements and set the font-size to 16 pixels (16px).

As I erroneously tried to add an entry for p elements within the .red-text class definition, which may or may not be what you all wanted.  This is also, I acknowledge, potentially a preference in wording that you all may not agree makes the situation clearer.

**Comment by borromeotlhs** [comment]
ps, my code is what you wanted ( and passed tests), so it is _not_ malfunctioning

**Comment by dhcodes** [comment]
@borromeotlhs the instructions say:
>Inside the same `<style>` tag that contains your red-text class, create an entry for p elements and set the font-size to 16 pixels (`16px`)

While I see your point, since it does say "inside the same `<style>` tag" I think it makes sense as is.

**Comment by hallaathrad** [comment]
The text is as @dhcodes describes. Closing, as I do agree the text should be self-explanatory enough this way. Please reopen if the wording should be changed.
