### ISSUE TITLE
Mutations. Instructions incomplete or missing precisions

### ISSUE THREAD

**Issue by iskode** [FreeCodeCamp/FreeCodeCamp#10502]
Hi everyone,
This pull request is not a bug,  it's a suggestion to improve instructions and make them clear for the next people on this challenge.
Instructions stated:

> Return true if the string in the **first** element of the array contains all of the letters of the string in the **second** element of the array.

However the test case:

> mutation(["zyxwvutsrqponmlkjihgfedcba", "qrstu"]) should return true. 

implies that it could be in the opposite direction: Return true if the string in the **second** element of the array contains all of the letters of the string in the **first** element of the array.

So I suggest instructions to be (so as to make it crystal clear):

> Return true if the string in one element of the array contains all of the letters of the string in the other element of the array. The array contains only two elements.

**Comment by abhisekp** [comment]
@iskode as per the instruction, 
> Return `true` if the `string` in the first element of the array

i.e. `"zyxwvutsrqponmlkjihgfedcba"` (_`zyxwv--u--t--s--r--q--ponmlkjihgfedcba`_)

> **contains all of the letters** of the `string` in the second element of the array.

i.e. `"qrstu"`

**Comment by iskode** [comment]
Wow! excuse me. I went to fast! Indeed you're right. But it's like I didn't get instructions in the first time.
Thank you so much.
