### ISSUE TITLE
Cannot go past a certain line in most of the challenges

### ISSUE THREAD

**Issue by HarleyGreaves** [FreeCodeCamp/FreeCodeCamp#10519]
I have been unable to get past a certain line in some of the challenges.
It will literally just stop my cursor and cannot go down further.

I had to spam refresh for it to work in 3 different browsers and have deleted my browser cache but still problem persists. 

Windows 10, chrome latest firefox latest and vivaldi latest.

**Comment by Margaret2** [comment]
Yes, I have had this issue too, i think in some of the Bootstrap challenges, where I can't select code to copy it somewhere else.

**Comment by texas2010** [comment]
Sorry about that.  Code editor have a problem.

**Comment by dhcodes** [comment]
@HarleyGreaves As @texas2010 has mentioned. This is an issue with the code editor the site uses as discussed in #7605 and #7528. Closing as a duplicate.
