### ISSUE TITLE
I think this challenge have a bug.

### ISSUE THREAD

**Issue by JamsonKwok** [FreeCodeCamp/FreeCodeCamp#10512]
Challenge [Return Early Pattern for Functions](https://www.freecodecamp.com/challenges/return-early-pattern-for-functions#?solution=%0A%2F%2F%20Setup%0Afunction%20abTest(a%2C%20b)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if(a%3C0%7C%7Cb%3C0)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20typeof(c)%3B%0A%20%20%20%20%7D%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%20%20return%20Math.round(Math.pow(Math.sqrt(a)%20%2B%20Math.sqrt(b)%2C%202))%3B%0A%7D%0A%0A%2F%2F%20Change%20values%20below%20to%20test%20your%20code%0AabTest(2%2C-2)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36 Core/1.47.933.400 QQBrowser/9.4.8699.400</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function abTest(a, b) {
  // Only change code below this line
  if(a<0||b<0)
    {
      return typeof(c);
    }
  
  
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,-2);

```
The Console return "undefined", but this challenge submit fail.

**Comment by dhcodes** [comment]
This does indeed return undefined. I looked at the test briefly and wonder if it's not the strict equality `===` that is not allowing this to pass. Could someone confirm?

**Comment by marhyorh** [comment]
@JamsonKwok It returns "undefined" not undefined. Your if statement should just return undefined not the typeof of some undefined variable which will result in a string.

Don't forget a typeof(typeof(undefined)) is a string.

**Comment by dhcodes** [comment]
@marhyorh good catch! @JamsonKwok as @marhyorh has said, the test requires that the return be the key word `undefined`.

**Comment by vectorhsi** [comment]
I am wondering it says return undefined, does it mean it will return undefined in the output area?

**Comment by dhcodes** [comment]
yes @vectorhsi Consider asking for help in the help chat room on Gitter instead of the issues here. Happy coding.
