### ISSUE TITLE
Concatenate with concat, more than one array

### ISSUE THREAD

**Issue by fuecisla** [FreeCodeCamp/FreeCodeCamp#10511]
#### Challenge Name

https://www.freecodecamp.com/challenges/concatenate-arrays-with-concat
#### Issue Description

The description says that the method can be used to concatenate two arrays. I bet most of us did wonder then how can you concatenate more than two.
I think it is worth mentioning that it can be used to concatenate as many arrays as you want by adding parameters to the method. In fact, the example would gain value by including more arrays. The method is so simple that a more complex example would be an improvement.
#### Browser Information

- Browser Name, Version: 
- Operating System: 
- Mobile, Desktop, or Tablet: 
#### Your Code

``` js



```

**Comment by dhcodes** [comment]
I could see the instructions:
>concat can be used to merge the contents of two arrays into one.

being changed to:
>concat can be used to merge the contents of two _or more_ arrays into one.

and then adding a second example to the existing one (such as below) to show that you can have more than one argument in your concat method.
Ex. `newArr = arr1.concat(arr2, arr3)`

What do others think?

**Comment by systimotic** [comment]
Sounds like a plan to me! 
My only concern is that it might be a bit confusing to new campers. If we do it as a step up, first showing concatenating a single array, then showing multiple, I think it should be fine.

**Comment by johnnyqbui** [comment]
I'd like to help out with this.
