### ISSUE TITLE
Does it`s bug?

### ISSUE THREAD

**Issue by H4lu** [FreeCodeCamp/FreeCodeCamp#10513]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.

So, I`m getting stuck with thist challenge

My code:

var myStr="FirstLine\n\\Secondline\\\rThirdLine"; 
Tried it in Mozilla console and it seems to work,except third line
![screen1](https://cloud.githubusercontent.com/assets/9824874/18358675/f6fa2f64-75fe-11e6-94be-c7732038f148.jpg)
But on the site I get:
![screen2](https://cloud.githubusercontent.com/assets/9824874/18358734/38f861a6-75ff-11e6-85be-6258c93f9fec.jpg)

Does it`s bug or my mistake?

**Comment by texas2010** [comment]
@H4lu 
Thanks for reporting this. But your code is incorrect. 
GitHub Issues are for reporting bugs on the website only
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding..
