### ISSUE TITLE
This exercise don't have the link to bootstrap -> <link rel='stylesheet' href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css'/>

### ISSUE THREAD

**Issue by robertcorreas** [FreeCodeCamp/FreeCodeCamp#1051]
Challenge http://www.freecodecamp.com/challenges/waypoint-mobile-responsive-images has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by JC713** [comment]
I am curious about this myself! It says they added it in already, but I am really curious about how to add it in myself for future reference.

**Comment by LumenTeun** [comment]
What I think they mean by "automatically added it" is that, since FreeCodeCamp uses Bootstrap, it's already loaded in your browser, and you don't need to add it to the editor. I do believe it would be good to show the campers how it's done, and it really wouldn't be that hard.

**Comment by benschenker** [comment]
Since the site overhaul, this is no longer an issue in http://www.freecodecamp.com/challenges/waypoint-make-images-mobile-responsive
