### ISSUE TITLE
Dodger blue bug?

### ISSUE THREAD

**Issue by FayeKittie** [FreeCodeCamp/FreeCodeCamp#10529]
Challenge [use-hex-code-to-mix-colors](https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
![ss 2016-09-09 at 05 25 59](https://cloud.githubusercontent.com/assets/19265565/18379344/56ea0d02-76b5-11e6-8518-296aedae441f.png)

Hello. I'm having issue passing this lesson.
I'm not sure if I'm doing it wrong or it's a bug?

The error is 'Give your h1 element with the text I am dodger blue! the color dodger blue.'
Which I have done but it's not accepting the code.

I would appreciate any help with this.
Thank you very much!

```html
    
    
<style>
.red-text {
  color: #FF0000;
}
.green-text {
  color: #00FF00;
}
.dodger-blue-text {
  color: #1E90FF;
}
.orange-text {
  color: #FFA500;
}
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>


    ```

**Comment by erictleung** [comment]
@FayeKittie thanks for the issue. This was brought up already in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10523. Closing this issue as duplicate. Happy coding!
