### ISSUE TITLE
Border-radius challenge done correctly , but freecodecamp will not pass test Help

### ISSUE THREAD

**Issue by maliekbr** [freeCodeCamp/freeCodeCamp#10539]
Challenge [add-rounded-corners-with-a-border-radius](https://www.freecodecamp.com/en/challenges/html5-and-css/add-rounded-corners-with-a-border-radius) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

``` html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
.red-text {
  color: red;
}

h2 {
  font-family: Lobster, Monospace;
}

p {
  font-size: 16px;
  font-family: Monospace;
}

.thick-green-border {
  border-color: green;
  border-width: 10px;
  border-style: solid;
}

.smaller-image {
  width: 100px; 
  border-radius: 10px;
}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by matty22** [comment]
Your code works for me in Chrome Version 53.0.2785.101 m (the most recent).

Your code does not work for me in Firefox Version 48.0.2.

**Comment by shikhar0507** [comment]
you need to add `border-radius:10px;` to .thick-green-border class
you have added it to .smaller-image class

`.thick-green-border {
  border-color: green;
  border-width: 10px;
  border-style: solid; 
  border-radius:10px;
}`

**Comment by systimotic** [comment]
Closing in favour of #10749
