### ISSUE TITLE
Challenge: Create a JavaScript slot machine

### ISSUE THREAD

**Issue by kfrn** [FreeCodeCamp/FreeCodeCamp#10531]
[Create a JavaScript slot machine](https://www.freecodecamp.com/en/challenges/basic-javascript/create-a-javascript-slot-machine)
     
There appears to be a bug in this. My code is passing the first three tests, but the last reads: 
> assert((function(){if(editor.match(/Math\.floor\(\s*Math\.random\(\)\s*\*\s*\(\s*3\s*\-\s*1\s*\+\s*1\s*\)\s*\)\s*\+\s*1/gi) !== null){return editor.match(/slot.*?=.*?\(.*?\).*?/gi).length >= 3;}else{return false;}})(), 'You should have used Math.floor(Math.random() * (3 - 1 + 1)) + 1; three times to generate your random numbers.')

This message, "You should have used `Math.floor(Math.random() * (3 - 1 + 1)) + 1;` three times to generate your random numbers", describes exactly what I did.
I've tried browser refresh and even cut and pasted from the error message to make sure there are no typos.

**Comment by erictleung** [comment]
@kfrn thanks for the issue. This was already brought up in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10528. Closing as duplicate issue. Happy coding!

**Comment by kfrn** [comment]
I think I opened the window to type before that was up! Apologies and thanks for your responsiveness.
