### ISSUE TITLE
youwenti 

### ISSUE THREAD

**Issue by jiaxiangwang** [FreeCodeCamp/FreeCodeCamp#10542]
Challenge [adjusting-the-padding-of-an-element](https://www.freecodecamp.com/en/challenges/html5-and-css/adjusting-the-padding-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<style>
.injected-text {
  margin-bottom: -25px;
  text-align: center;
}

.box {
  border-style: solid;
  border-color: black;
  border-width: 5px;
  text-align: center;
}

.yellow-box {
  background-color: yellow;
  padding: 10px;
}

.red-box {
  background-color: red;
  padding: 20px;
}

.green-box {
  background-color: green;
  padding: 20px;
}
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
<h5 class="box red-box">padding</h5>
<h5 class="box green-box">padding</h5>
</div>

    ```

**Comment by BerkeleyTrue** [comment]
> Please describe how to reproduce this issue, and include links to screenshots if possible.

Happy Coding
