### ISSUE TITLE
dodger-blue-text

### ISSUE THREAD

**Issue by Franciszek99** [FreeCodeCamp/FreeCodeCamp#10540]
Challenge [use-hex-code-to-mix-colors](https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 OPR/39.0.2256.71</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<style>
.red-text {
  color: #FF0000;
}
.green-text {
  color: #00FF00;
}
.dodger-blue-text {
  color: #1E90FF;
}
.orange-text {
  color: #FFA500;
}
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

    ```

**Comment by HarleyGreaves** [comment]
Same problem, keeps saying its not right when it is 
![screenshot 1](https://cloud.githubusercontent.com/assets/22088224/18382479/7ce5fcfa-76c4-11e6-92e5-67e3cb1c535e.png)

**Comment by hacker001** [comment]
I have same problem

**Comment by erictleung** [comment]
@Franciszek99 thanks for the issue. This is a known issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10523. Closing as duplicate issue. Happy coding!
