### ISSUE TITLE
bug in the img tag

### ISSUE THREAD

**Issue by tharejamudit** [FreeCodeCamp/FreeCodeCamp#1054]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue. 

unable to select the whole img tag by selecting it from one point to another and also cannot click inside the content of the img tag i guess this bug is in the other challenges also but i don't know how many

**Comment by benschenker** [comment]
Hey @tharejamudit thanks for posting.

I am unable to replicate this issue now.  Since it is pretty old, it may have been fixed already.

I'll close this issue but feel free to reopen if you still have any issues.
