### ISSUE TITLE
Slice and Splice not evaluating code

### ISSUE THREAD

**Issue by indianmartini** [FreeCodeCamp/FreeCodeCamp#10559]
Challenge [slice-and-splice](https://www.freecodecamp.com/en/challenges/basic-algorithm-scripting/slice-and-splice) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Although I've test my code in console and seems to work, the page is not evaluating it. It throws an error and reset to the original code. This is a serious problem if you didn't write your code on your own text editor. 

```html
    \ file: function frankenSplice(arr1, arr2, n) {
// It's alive. It's alive!
// At index n of arr2, insert in order values of arr1
var newArr2 = [];
for (i = arr1.length -1; i > -1; i--) {
  arr2.splice(n,0, arr1[i]);
}
console.log(arr1);
console.log(arr2);

return arr2;
}

frankenSplice([1, 2, 3], [4, 5, 6], 1);

    function frankenSplice(arr1, arr2, n) {
// It's alive. It's alive!
// At index n of arr2, insert in order values of arr1
var newArr2 = [];
for (i = arr1.length -1; i > -1; i--) {
  arr2.splice(n,0, arr1[i]);
}
console.log(arr1);
console.log(arr2);

return arr2;
}

frankenSplice([1, 2, 3], [4, 5, 6], 1);

    ```
    
```js
    \ file: 
function frankenSplice(arr1, arr2, n) {
// It's alive. It's alive!
return arr2;
}

frankenSplice([1, 2, 3], [4, 5, 6], 1);

    
function frankenSplice(arr1, arr2, n) {
// It's alive. It's alive!
return arr2;
}

frankenSplice([1, 2, 3], [4, 5, 6], 1);

    ``
![slice](https://cloud.githubusercontent.com/assets/16676175/18383003/1c20d238-768c-11e6-929b-b3b6e81747fe.png)
`

**Comment by indianmartini** [comment]
I made a full refresh of the page F5 and right now is running the code.

**Comment by anknits** [comment]
Although it was not resetting the code on the editor, it was not running the code for tests. I tried hard refresh, it then runs the code once per refresh but doesn't pass any test case. I tried it on an online editor. The code works fine online if I have understood the problem correctly.

**Comment by crossphd** [comment]
I'm having the exact same issue. It is not evaluating the code and never returns any output.

**Comment by elcortez** [comment]
same thing here. Besides it keeps returning an error telling me the second array should remain the same, but it is remaining the same.
It works locally on my terminal but not on the website. Not sure what's wrong.

My code is
function frankenSplice(arr1, arr2, n) {
  var stuff2 = arr2;
  for(i = 0; i < arr1.length; i++) {
    stuff2.splice(n, 0, arr1[arr1.length - 1 - i]);
  }
  return stuff2;
}


Thanks

**Comment by kalamnuri** [comment]
+1 for crossphd. I am having same problem. Seems like this test was added recently as it was not there yesterday (I think).
