### ISSUE TITLE
Challenge word-blanks has an issue.

### ISSUE THREAD

**Issue by AndreiConstantinesu** [FreeCodeCamp/FreeCodeCamp#10558]
Challenge [word-blanks](https://www.freecodecamp.com/en/challenges/basic-javascript/word-blanks) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js
    
    
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
var result = "";
// Your code below this line

result = myAdjective + " " + myNoun + " " + myVerb + " " + myAdverb;

// Your code above this line
return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

    ```
The error : 
wordBlanks("dog", "big", "ran", "quickly") should contain all of the passed in words separated by non-word characters (and any additional words in your madlib).
wordBlanks("cat", "little", "hit", "slowly") should contain all of the passed in words separated by non-word characters (and any additional words in your madlib).

**Comment by dhcodes** [comment]
@AndreiConstantinesu I think this may be an issue with the editor. Try copying your code, refreshing the browser page, and then pasting it back in. Then run the tests again. Let me know if it passes.

**Comment by erictleung** [comment]
@AndreiConstantinesu closing as stale. Feel free to comment if you're still having issues. Happy coding!

**Comment by ScottFrederickSchmidt** [comment]
I switched noun to the beginning so that dog = noun.
And it worked!

**Comment by dogomeodenzoy** [comment]
var result = myNoun +", " + myAdjective +", " + myVerb + ", " + myAdverb + ", " ;

**Comment by sandradelax** [comment]
> 
> 
> var result = myNoun +", " + myAdjective +", " + myVerb + ", " + myAdverb + ", " ;

Is the literal answer to "wordBlanks should contain all of the passed in words **separated by non-word characters**". And it works. This is stupid, 30 min trying to figure out.

**Comment by pmstyle123** [comment]
I think this is an editor issue.Change your browser or refresh it.Surely it will work.

**Comment by thpthang** [comment]
var result = "";
    // Your code below this line
    result+= "My "+myAdjective+" "+myNoun+" "+myVerb+" very "+myAdverb+".";

**Comment by thpthang** [comment]
Can you describe this issue more clearly?

**Comment by RandellDawson** [comment]
@thpthang Please use [our forum](https://www.freecodecamp.org/forum/) for questions related to why your code does not pass a challenge.  Thank you.
