### ISSUE TITLE
freecodecamp icon (top left) redirects to Challenge, not to main page

### ISSUE THREAD

**Issue by evaristoc** [FreeCodeCamp/FreeCodeCamp#10552]
I was using the freecodecamp icon (top left) to be brought to the main page but it landed in the following page instead:

https://www.freecodecamp.com/en/challenges/join-the-free-code-camp-community/learn-how-free-code-camp-works

**Comment by BerkeleyTrue** [comment]
This is as expected.

Happy Coding
