### ISSUE TITLE
Indicating why several translations missing in the Spanish pages

### ISSUE THREAD

**Issue by evaristoc** [FreeCodeCamp/FreeCodeCamp#10555]
Just to confirm that there are numerous translations that are missing in the Spanish translation. I think a message asking for help for translation or any indication of why some of them are not still completed should be considered?

**Comment by evaristoc** [comment]
Well done, varCI-bot!

**Comment by erictleung** [comment]
@evaristoc duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9697. Closing in favor of that issue. Thanks!
