### ISSUE TITLE
Javascript - Basic Algorithm - Slice and Splice : Run button resets the code

### ISSUE THREAD

**Issue by R0bonaut** [FreeCodeCamp/FreeCodeCamp#10553]
Challenge [slice-and-splice](https://www.freecodecamp.com/en/challenges/basic-algorithm-scripting/slice-and-splice) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.6.2000 Chrome/30.0.1599.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The issue is that after clicking on "Run tests (ctrl + enter)" button it reset the code, also console output window does not show the output.

```html
    \ file: 
function frankenSplice(arr1, arr2, n) {
// It's alive. It's alive!
return arr2;sadsad
}

frankenSplice([1, 2, 3], [4, 5, 6], 1);

    
function frankenSplice(arr1, arr2, n) {
// It's alive. It's alive!
return arr2;sadsad
}

frankenSplice([1, 2, 3], [4, 5, 6], 1);

    ```
    
```js
    \ file: 
function frankenSplice(arr1, arr2, n) {
// It's alive. It's alive!
return arr2;
}

frankenSplice([1, 2, 3], [4, 5, 6], 1);

    
function frankenSplice(arr1, arr2, n) {
// It's alive. It's alive!
return arr2;
}

frankenSplice([1, 2, 3], [4, 5, 6], 1);

    ```

**Comment by Burgi0101** [comment]
Page refresh fixed it for me!

**Comment by TimHandy** [comment]
Had the same issue. Ctrl+F5 hard refresh did it for me.

**Comment by anknits** [comment]
Although it was not resetting the code on the editor, it was not running the code for tests. I tried hard refresh, it then runs the code once per refresh but doesn't pass any test case. I tried it on an online editor. The code works fine online if I have understood the problem correctly.

**Comment by kalamnuri** [comment]
+1. I think I am having same problem. Output window just shows "running test" and then "tests completed" and shows all cases as failed (except second from bottom). Code runs fine and gives desired output when run from chrome. Seems like this test was added recently as it was not there yesterday (I think).

**Comment by BerkeleyTrue** [comment]
This challenge will be removed shortly. Apologies for the confusion.

Happy Coding
