### ISSUE TITLE
Dodger-blue hex code not accepted

### ISSUE THREAD

**Issue by miricvetq** [FreeCodeCamp/FreeCodeCamp#10567]
Challenge [use-hex-code-to-mix-colors](https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Dodger-blue hex code not accepted, although the same as in the description.
![image](https://cloud.githubusercontent.com/assets/22084965/18385932/c49e172a-7693-11e6-98e5-5968ccc22709.png)

![image](https://cloud.githubusercontent.com/assets/22084965/18385952/e5983b0e-7693-11e6-9beb-5ad049b0d445.png)

```html
    
    
<style>
.red-text {
  color: #FF0000;
}
.green-text {
  color: #00FF00;
}
.dodger-blue-text {
  color: #1E90FF;
}
.orange-text {
  color: #FFA500;
}
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

    ```

**Comment by mdharris08** [comment]
I am having the same problem, but the code looks correct. I look forward to reading any helpful responses.

**Comment by tp6060** [comment]
same here. #1E90FF is not accepted.

**Comment by erictleung** [comment]
@miricvetq thanks for the issue. This is a known issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10523. Closing as duplicate issue. Happy coding!
