### ISSUE TITLE
Does not accept correct answer

### ISSUE THREAD

**Issue by caseyiannone** [FreeCodeCamp/FreeCodeCamp#10564]
Challenge [quoting-strings-with-single-quotes](https://www.freecodecamp.com/en/challenges/basic-javascript/quoting-strings-with-single-quotes) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

After wrapping the entire string in single quotes and deleting the back slashes the application will not accept the correct answer. Of the three items on the checklist, "You should have two single quotes ' and four double quotes ", is still marked with a red X.

```js


var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';



```

**Comment by jardi123** [comment]
I have the same issue

**Comment by taipo1** [comment]
Have the same problem same thing happend on the previous challenge

**Comment by marcandre311** [comment]
I also have the same issue
var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';

**Comment by petrgazarov** [comment]
Hi the link in the PR description throws a 404 error. Is this issue still relevant?

**Comment by mattlindsey** [comment]
Appears the link in the description is just missing the 's' in 'https': 
https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes

The challenge works for me, so I believe this issue can be closed.

**Comment by MacPrawn** [comment]
The challenge also works for me - looks like this one is fixed already.

**Comment by atjonathan** [comment]
Thanks for letting us know @MacPrawn, @mattlindsey 😃

**Comment by emilze** [comment]
I am having the same issue.
