### ISSUE TITLE
Change h2 color issue

### ISSUE THREAD

**Issue by aliencharm** [FreeCodeCamp/FreeCodeCamp#10562]
Challenge [change-the-color-of-text](https://www.freecodecamp.com/en/challenges/html5-and-css/change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<h2 style="color:red">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by EssaAlshammri** [comment]
Challenge [change-the-color-of-text](https://www.freecodecamp.com/en/challenges/html5-and-css/change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.


```
I'm having this issue too

**Comment by aliencharm** [comment]
I discovered that in Chrome it's working. I used Firefox first, but now I'll use Chrome especially for freecodecamp.

**Comment by erictleung** [comment]
@aliencharm closing as duplicate issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10532. Happy coding!

**Comment by EssaAlshammri** [comment]
yup chromium worked for me :)
