### ISSUE TITLE
It looks like the beta code got pushed to production

### ISSUE THREAD

**Issue by P1xt** [FreeCodeCamp/FreeCodeCamp#10561]
@BerkeleyTrue @QuincyLarson  asked me to tag you on this.

#### Challenge Name
On a variety of challenges - many have been reported by others already

#### Issue Description
A variety of challenges are failing for various campers.

UX is wonky on challenges

Submitting a challenge for test is still done by Ctrl+Enter, but since yesterday, moving to the next challenge has changed -- I can no longer just press Ctrl+Enter but have to move on with the mouse. Ctrl+Enter, Ctrl+Enter is faster and more convenient than Ctrl+Enter, then move hand to mouse, then move cursor to Submit and press.

Also, since yesterday, I no longer see the results of the test in the black area - I have to add console.log() commands.

The new submit button is in a modal of some sort that slides in at the bottom of the screen. And then slides back out - thus disappearing and removing the ability to submit the solution

When you fail to pass tests on a challenge, then modify your code and try again, the system deletes all your modifications and resubmits the previously failed code.

There are now dual scrollbars on the map page.

The about page redirects to the map page.

#### Browser Information

* Browser Name, Version: Chrome / Firefox, latest
* Operating System: Mac / Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
 
 
```

**Comment by BerkeleyTrue** [comment]
Please use the search bar before opening new issues. Most of the things you are reporting are already issue's. 

In the future please open individual issues instead of providing a list of separate unrelated issues.

**Comment by P1xt** [comment]
I wasn't reporting the individual issues. I was reporting that an obviously bad build went live in case it needed to be reverted. Blame Quincy, he told me to.

**Comment by QuincyLarson** [comment]
@P1xt Sorry about the misunderstanding. 

Thank you for compiling this list of widely-reported issues. This is extremely helpful. 

I will use this to open individual issues where necessary and we will work to resolve them ASAP.
