### ISSUE TITLE
It says "Keep Trying" but the code is correct as far as I know 

### ISSUE THREAD

**Issue by antoniotrimaldi** [FreeCodeCamp/FreeCodeCamp#10563]
Challenge [use-hex-code-to-mix-colors](https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<style>
.red-text {
  color: 	#FF0000;
}
.green-text {
  color: #00FF00;
}
.dodger-blue-text {
  color: #1E90FF;
}
.orange-text {
  color: #FFA500;
}
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

    ```
It says "Keep Trying" but the code is correct as far as I know. It doesn't accept the dodger blue hexadecimal code as correct. 
![screenshot 27](https://cloud.githubusercontent.com/assets/20484432/18385017/45cabdf4-768e-11e6-840c-fac99cb05c11.png)

**Comment by Yerza10** [comment]
having same issue

**Comment by atjonathan** [comment]
This is a known issue (https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10523). Closing as duplicate. Happy coding!
