### ISSUE TITLE
Front end challenges

### ISSUE THREAD

**Issue by Jay-20** [FreeCodeCamp/FreeCodeCamp#10565]
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
I was performing the weather challenge in free code camp using chrome.Then i logged in to my account using firefox and then it just takes me back to the start even though it shows that i have completed challenges till random quote machine it just doesnt take me back to weather project. Here are some screenshots: also this is my account link: https://www.freecodecamp.com/en/jay-20
 
![screenshot 5](https://cloud.githubusercontent.com/assets/20420704/18385289/56a7294a-76ad-11e6-8643-207b474db618.png)
![screenshot 6](https://cloud.githubusercontent.com/assets/20420704/18385290/56a94414-76ad-11e6-87c8-0ff0f027c908.png)

**Comment by BerkeleyTrue** [comment]
We recently changed how the next challenges are loaded. It needs save your position on challenge complete before the next challenge logic will work correctly.

Sorry for the inconvenience. 

Happy Coding.
