### ISSUE TITLE
Can't get through

### ISSUE THREAD

**Issue by ricusricus** [FreeCodeCamp/FreeCodeCamp#10568]
Challenge [inherit-styles-from-the-body-element](https://www.freecodecamp.com/en/challenges/html5-and-css/inherit-styles-from-the-body-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    <style>
body {
  background-color: black;
  color:green;font-family:Monospace;
}</style> <h1>Hello World</h1>

    ```

**Comment by BerkeleyTrue** [comment]
> Please describe how to reproduce this issue, and include links to screenshots if possible.

Happy Coding
