### ISSUE TITLE
Use Hex Code to Mix Colors (https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors)

### ISSUE THREAD

**Issue by 20learncode16** [FreeCodeCamp/FreeCodeCamp#10571]
Hi,
Though I did everything required for this challenge when I click on 'run tests' it does not take me to the next challenge, instead, it keeps on saying 'keep trying'. Going on the help site, I have discovered another person having exactly the same problem. Please help us. 
Thank you.

![bug](https://cloud.githubusercontent.com/assets/20506860/18387782/0257d148-76e2-11e6-8fa3-b3ec7c73b5c1.jpg)

#### Challenge Name
Use Hex Code to Mix Colors

https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors
![bug](https://cloud.githubusercontent.com/assets/20506860/18387411/e45b7052-76df-11e6-84c1-165076f900c8.jpg)
![bug](https://cloud.githubusercontent.com/assets/20506860/18387430/fbfff7be-76df-11e6-872b-88121b5f475b.jpg)
![bug](https://cloud.githubusercontent.com/assets/20506860/18387439/0dc424e8-76e0-11e6-82f1-b8c7b6460207.jpg)

 
 
 
```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by erictleung** [comment]
@20learncode16 thanks for the issue. This is a known issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10523. Closing as duplicate. Happy coding!

**Comment by 20learncode16** [comment]
Hi Eric,
I noticed that the issue has been resolved, as I've tried the challenge
again and it worked this time. Thank you.
Regards,
Antonia
