### ISSUE TITLE
Code Cleared after running test

### ISSUE THREAD

**Issue by c-s-avage** [FreeCodeCamp/FreeCodeCamp#10574]
Challenge [manipulating-complex-objects](https://www.freecodecamp.com/en/challenges/basic-javascript/manipulating-complex-objects) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

`````` js


var myMusic = [
{
  "artist": "Billy Joel",
  "title": "Piano Man",
  "release_year": 1973,
  "formats": [ 
    "CS", 
    "8T", 
    "LP" ],
  "gold": true
}
// Add record here
];


    ```


This is a global bug affecting all challenges.  After running the test the code is cleared.  This makes it very time consuming if you need to constantly retype the code if you did not get the challenge correct.  IT was better before when your code was not automatically cleared so you could simply modify it and run the test again rather than starting from scratch every single time!
``````

**Comment by c-s-avage** [comment]
This is a global bug affecting all challenges.  After running the test the code is cleared.  This makes it very time consuming if you need to constantly retype the code if you did not get the challenge correct.  IT was better before when your code was not automatically cleared so you could simply modify it and run the test again rather than starting from scratch every single time!

**Comment by valeriaoshiro** [comment]
+1
Happened to me in Truncate a string challenge. Using Firefox 48.0.2 in Private Window mode.

**Comment by dhcodes** [comment]
Confirmed. I have seen this bug but have not been able to replicate it reliably.

**Comment by dhcodes** [comment]
As a follow-up I have experienced this most reliably in Firefox and Safari (less in Chrome) by writing the correct code, copying the code, then hitting `Reset` and then pasting it back in.

**Comment by chadg1980** [comment]
My code is getting removed after each test (Chrome n 53.0.2785.101) Also my chrome was updated last night,  so a chrome specific bug could pop up.

**Comment by dhcodes** [comment]
@chadg1980 for the time being, try a hard refresh of the page (Ctrl + F5) to see if it has any effect.

**Comment by c-s-avage** [comment]
this is now fixed
