### ISSUE TITLE
Your h1 element should be pink.

### ISSUE THREAD

**Issue by lodrick1210** [FreeCodeCamp/FreeCodeCamp#10573]
Challenge [override-all-other-styles-by-using-important](https://www.freecodecamp.com/en/challenges/html5-and-css/override-all-other-styles-by-using-important) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<style>
body {
  background-color: black;
  font-family: Monospace;
  color: green;
}
#orange-text {
  color: orange;
}
.pink-text {
  color: pink; color: red !important; 
}
.blue-text {
  color: blue;
}

</style>
<h1 id="orange-text" class="pink-text blue-text" style="color:white ">Hello World!</h1>

    ```

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
