### ISSUE TITLE
Better facebook opengraph picture when sharing

### ISSUE THREAD

**Issue by kevinsimper** [FreeCodeCamp/FreeCodeCamp#1057]
A better image when sharing to Facebook that is more appealing and tells why you should care, instead of showing the immense hours it will take to complete, that will exhaust even the most engaged person!

![image](https://cloud.githubusercontent.com/assets/1126497/8283375/54d2ce90-18f7-11e5-8b10-158b38e155d5.png)

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
