### ISSUE TITLE
change-the-color-of-text wont accept text

### ISSUE THREAD

**Issue by lydatech** [freeCodeCamp/freeCodeCamp#10588]
Challenge [change-the-color-of-text](https://www.freecodecamp.com/en/challenges/html5-and-css/change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

``` html

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>


<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

``` html

<h2 style="colr:red;">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>



<h2 style="colr:red;">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>


```

This had previously passed. Resubmitted now its failing. Cleared my code and tried to reenter now it doesnt accept the code at all. It resents and clears my text inputed when I click run code.

**Comment by atjonathan** [comment]
`colr` should be `color` :smiley:
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by dhcodes** [comment]
@lydatech @atjonathan beat me to it, but yeah, what he said. I copied/pasted your code and it did work on my end after changing `colr` to `color`.

**Comment by lydatech** [comment]
That is NOT THE ISSUE. what is being submitted ti this issue isnt the code thats put into the editor. Nor does it address the resetting of the code @atjonathan @dhcodes

**Comment by raisedadead** [comment]
This challenge has moved and has been updated
https://beta.freecodecamp.com/en/challenges/basic-css/change-the-color-of-text

Please retry and let us know if the issue persists.
