### ISSUE TITLE
Challenge (Use Clockwise Notation to Specify the Padding of an Element)

### ISSUE THREAD

**Issue by frankliiin** [FreeCodeCamp/FreeCodeCamp#10582]
#### Issue Description

I am working on this challenge ([Use Clockwise Notation to Specify the Padding of an Element](https://www.freecodecamp.com/en/challenges/html5-and-css/use-clockwise-notation-to-specify-the-padding-of-an-element)) but I can't seem to get past it, is it my code?

#### Browser Information

* Browser Name, Version: Mozilla/5.0 
* Operating System: Macintosh; Intel Mac OS X 10.11; rv:48.0

#### Your Code

```js
 <style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .yellow-box {
    background-color: yellow;
    padding: 20px 40px 20px 40px;
  }
  
  .red-box {
    background-color: red;
    padding: 20px 40px 20px 40px;
  }

  .green-box {
    background-color: green;
    padding: 40px 20px 20px 40px;
  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

 
 
```

**Comment by dhcodes** [comment]
@frankliiin Your code above worked for me. Try copying it to your clipboard, clicking Reset Code, and then pasting it back in. Then run the tests again.

**Comment by frankliiin** [comment]
Just did that, still didn't work. I took a screenshot.

![screen shot 2016-09-09 at 16 23 09](https://cloud.githubusercontent.com/assets/21330076/18392476/d01353ca-76a9-11e6-9910-ddbdc30b1384.png)

**Comment by dhcodes** [comment]
I think this is a browser issue @frankliiin I'm referencing it as I collect similar issues with Firefox. Thanks!
