### ISSUE TITLE
No visual indication for completed chapters in the map

### ISSUE THREAD

**Issue by hallaathrad** [FreeCodeCamp/FreeCodeCamp#10584]
<img width="466" alt="screen shot 2016-09-09 at 10 36 03" src="https://cloud.githubusercontent.com/assets/2107110/18390684/435b94e0-7679-11e6-82fd-112d0b922796.png">
When all the challenges/projects are completed in a chapter, there should be a visual indication of said chapter being complete. (e.g. dimmed text, greyed out, etc.)
Furthermore, when all the chapters in a section are completed, there should also be a visual indication for that. (e.g. a checkmark, dimmed text, different background, etc.)

It eases the navigation for someone seeking incomplete challenges to work on.

**Comment by ktajpuri** [comment]
It Appears it has already been fixed
Completed Challenges
================
![image](https://cloud.githubusercontent.com/assets/10725893/18786176/26b75b8e-81ba-11e6-95da-4896ae56298a.png)

Incomplete Challenges
===============
![image](https://cloud.githubusercontent.com/assets/10725893/18786193/4285e8e4-81ba-11e6-8ec0-12cd6cd78033.png)

I think this issue can be closed.

**Comment by hallaathrad** [comment]
You're absolutely right, @ktajpuri :) thanks
