### ISSUE TITLE
Does not recognize correct code

### ISSUE THREAD

**Issue by Wynda** [FreeCodeCamp/freecodecamp#1058]
Challenge http://www.freecodecamp.com/challenges/waypoint-fill-in-the-blank-with-placeholder-text has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I have done what the lesson requires but it will not accept the code and let me move forward to next lesson.
![capture](https://cloud.githubusercontent.com/assets/10391627/8288525/a39f84ae-18cb-11e5-96dd-fe418a6ed5d2.JPG)
![2capture](https://cloud.githubusercontent.com/assets/10391627/8288532/adaa28b4-18cb-11e5-9e78-93f6a52069ab.JPG)

**Comment by LumenTeun** [comment]
Have you tried refreshing the challenge? I can not reproduce this.

**Comment by Wynda** [comment]
Hi,

I put in less text in between the <p> tags and it worked.  With more text it doesnt work for some reason.

**Comment by BerkeleyTrue** [comment]
@Wynda Seems to be working correctly on my end. This challenge requires a direct copy of the kitty ipsum text in red at the bottom of the more info panel it the given `p` tag.

Also, have you checked out our help chat at https://gitter.im/freecodecamp/help we have an awesome community who love to help out when you get stuck. Good luck with the rest of the challenges!
