### ISSUE TITLE
Avatar should light up the brownie score on hover

### ISSUE THREAD

**Issue by hallaathrad** [FreeCodeCamp/FreeCodeCamp#10581]
Currently, if you hover over the user's avatar picture, it acts as if it was a different link than the brownie score. They both technically make part of the same button, therefor the behaviour should be the same.

<img width="197" alt="screen shot 2016-09-09 at 10 31 24" src="https://cloud.githubusercontent.com/assets/2107110/18390558/9c8978a8-7678-11e6-8950-ed4128b58340.png">

Easy win. Who's up for it?

**Comment by meetmangukiya** [comment]
I'm :up: :

**Comment by hallaathrad** [comment]
Hit it! :D I'll QA you.

**Comment by meetmangukiya** [comment]
The file to be changed is `/client/less/main.less`, right? And I need to add the hover state of the anchor with class `profile-picture`

**Comment by hallaathrad** [comment]
hm it can be a bit more complicated... What I'd do instead is changing the html, so that instead of it being
<img width="711" alt="screen shot 2016-09-10 at 15 57 50" src="https://cloud.githubusercontent.com/assets/2107110/18413213/69b50404-776f-11e6-86b6-67a60fa22aed.png">
where it shows the two as separate links inside of their own `li` elements. I'd make both the same anchor with class "brownie-points-nav" —which is the one already reacting on hover—, thus hovering over any of the two elements (i.e. text or image) will still trigger the anchor.

Also, I'd add the classes "hidden-xs hidden-sm avatar" to the image itself, so that it'll hide when the screens resolutions are smaller.

Makes sense? I could paste the code here, but I don't want to spoil the challenge for you ;)

**Comment by meetmangukiya** [comment]
Yes, it does. But I hardly see any html file in the repo :confused: There are only three 
+ favicons.html
+ sponsors.html
+ redirect-https.html

**Comment by meetmangukiya** [comment]
I see there are jade files, my bad.

**Comment by meetmangukiya** [comment]
My PR will be up in a minute! :D

**Comment by meetmangukiya** [comment]
The PR is up for review #10686

**Comment by marhyorh** [comment]
@hallaathrad I can make the PR anytime but why do we have the brownie points up there and why do we have to hide the user's pic on sm devices and not the brownie points then hide both the brownie points and user's pic on xs devices :smile:

**Comment by hallaathrad** [comment]
@marhyorh The "points and avatar" are merely an access to the user profile. The avatar is hidden on slightly smaller screen for the sake of real estate available.

And you've made me realise on smaller screens (where the nav becomes a hidden menu), that option should say the username and their points.
<img width="463" alt="screen shot 2016-09-13 at 12 00 30" src="https://cloud.githubusercontent.com/assets/2107110/18481300/b5340768-79a9-11e6-9b81-b3cdb6e18438.png">

**Comment by marhyorh** [comment]
@hallaathrad Just thinking, why should i have the points there?? I mean, they both point to the user's profile :thought_balloon:

**Comment by hallaathrad** [comment]
My best guess is there's no other visible place to see your own score, other than by going to your own profile? it does, however, give the newbs a misleading message of 1 point = 1 challenge. Very frequently you'll see people saying they're on challenge 35 or whatever. 

Though I agree with you in that the points MAY no longer be relevant (if they ever really were), but I'd say that'd be in the scope of a different issue. We would have to discuss whether to keep them or not, and this issue was meant only to improve UI behaviour on a split link to the same page —which is a current bug. Bad juju.

**Comment by marhyorh** [comment]
Haha Okay :smile:

**Comment by hallaathrad** [comment]
@marhyorh so you'll take care of this PR?

**Comment by marhyorh** [comment]
@hallaathrad Yeah, i'm going off for now. Will PR in two hours

**Comment by marhyorh** [comment]
@hallaathrad I've started working on this. Chrome ate up my computer memory, couldn't do much. I think i'll have to get another browser. Anyone up for this can PR :smile:

**Comment by marhyorh** [comment]
@hallaathrad I switched to mozilla and fixed that. Now, i noticed another ux issue. Check the pictures below: (When minimized to tablet and mobile devices)
![fcc-md-bug](https://cloud.githubusercontent.com/assets/11811904/18510519/66ad6896-7a76-11e6-87ba-c2079cef2d06.png)
![fcc-sm-bug](https://cloud.githubusercontent.com/assets/11811904/18510520/66b31db8-7a76-11e6-94b9-1f11f9d8b701.png)

**Comment by hallaathrad** [comment]
does the same happen on actual devices? the desktop browser mobile emulators are not always precise. However, if you feel like submitting an universal fix for that screen size, go for it :)

**Comment by hallaathrad** [comment]
Closed with #10899
