### ISSUE TITLE
Filter Arrays with .filter - can't pass

### ISSUE THREAD

**Issue by atflick** [FreeCodeCamp/FreeCodeCamp#10589]
Challenge [filter-arrays-with-filter](https://www.freecodecamp.com/en/challenges/object-oriented-and-functional-programming/filter-arrays-with-filter) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Using the code below and it should be working but getting error message: "You should only be using filter to make the new array."  I have searched and this is the correct code so I don't know what the problem is..

```js
    
    
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val) {
return val <= 5;
});

    ```

**Comment by atjonathan** [comment]
Confirmed. Similar to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10548

**Comment by atjonathan** [comment]
This has been fixed.
