### ISSUE TITLE
Not sure what's wrong...

### ISSUE THREAD

**Issue by glesle** [FreeCodeCamp/FreeCodeCamp#10585]
Challenge [style-multiple-elements-with-a-css-class](https://www.freecodecamp.com/en/challenges/html5-and-css/style-multiple-elements-with-a-css-class) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    <style>
.red-text {
  color: red;
}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
    ```

**Comment by glesle** [comment]
Everything appears correct and my text is all red. What am I missing???

**Comment by dhcodes** [comment]
@glesle In this case, there is an error in your code. Consider asking for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) room for FreeCodeCamp.
