### ISSUE TITLE
I think I wrote the code correctly but it throws an error

### ISSUE THREAD

**Issue by Saurabh2792** [FreeCodeCamp/FreeCodeCamp#10583]
Challenge [use-css-selectors-to-style-elements](https://www.freecodecamp.com/en/challenges/html5-and-css/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
     
     <style>
 h2 {color: blue; } CatPhotoApp

</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

     ```

**Comment by dhcodes** [comment]
@Saurabh2792 You have an error in your code. Consider asking for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) room for FreeCodeCamp.
