### ISSUE TITLE
Wording issue on instructions

### ISSUE THREAD

**Issue by fantigua** [FreeCodeCamp/freecodecamp#1059]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Second issue to solve states "Each of your Bootstrap buttons should be wrapped within its own a div element with the class "col-xs-4".  The word "a" should be removed.  It should read "wrapped within its own div"...

**Comment by NatashaHaggard** [comment]
Fixed, opened a pull request - https://github.com/FreeCodeCamp/freecodecamp/pull/1114
