### ISSUE TITLE
Reverse Array challenge - Last test will not pass

### ISSUE THREAD

**Issue by atflick** [FreeCodeCamp/FreeCodeCamp#10591]
Challenge [reverse-arrays-with-reverse](https://www.freecodecamp.com/en/challenges/object-oriented-and-functional-programming/reverse-arrays-with-reverse) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Can't pass this, seems bugged similar to my filter bug

```js


var array = [1,2,3,4,5,6,7];
var newArray = [];

// Only change code below this line.

var newArray = array.reverse();

```

**Comment by ArielLeslie** [comment]
![image](https://cloud.githubusercontent.com/assets/6234475/18393173/a6d637f8-7671-11e6-9095-5638c73ab109.png)
Reproduced.

**Comment by ZebraLan** [comment]
+1

**Comment by dhcodes** [comment]
@FreeCodeCamp/issue-moderators For both this, #10548 and #10589, it seems like the var defined above the area where users add their code is not being correctly recognized as being defined (usually denoted by light blue coloring).

**Comment by atjonathan** [comment]
This has been fixed.
