### ISSUE TITLE
Only has one "if statement" but won't let me pass.

### ISSUE THREAD

**Issue by bwarman** [FreeCodeCamp/FreeCodeCamp#10597]
![screen shot 2016-09-09 at 12 06 22 pm](https://cloud.githubusercontent.com/assets/867409/18394011/dcdabe50-7685-11e6-8169-ee0ad9aa204b.png)
Challenge [comparisons-with-the-logical-and-operator](https://www.freecodecamp.com/en/challenges/basic-javascript/comparisons-with-the-logical-and-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The issue is apparent in the screenshot. I have changed the code to only have one if statement but it's saying that I have two. I've tried resetting the code, clearing my cache, shutting down my browser and clearing my cache. Nothing has fixed it.

**Comment by bwarman** [comment]
It miraculously fixed itself after many cache clearings, browser shutdowns and time. Issue closed.

**Comment by marjanka3009** [comment]
I have exactly the same problem. The console shows the right output but the page won' t let me pass.
