### ISSUE TITLE
I cannot submit my correct answer -- even if the answer is correct but the system still thinks I am wrong

### ISSUE THREAD

**Issue by putin789** [FreeCodeCamp/FreeCodeCamp#10599]
![issue](https://cloud.githubusercontent.com/assets/22100807/18394244/2618a156-76e3-11e6-98a3-e70a7e1531e2.JPG)
Challenge [use-hex-code-to-mix-colors](https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<style>
.red-text {
  color: #FF0000;
}
.green-text {
  color: #00FF00;
}
.dodger-blue-text {
  color: #1E90FF;
}
.orange-text {
  color: #FFA500;
}
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

    ```

**Comment by ArielLeslie** [comment]
Copy of Issue #10523

**Comment by kelvin086** [comment]
i have this same problem
