### ISSUE TITLE
Tests too lenient

### ISSUE THREAD

**Issue by Gslaughl** [FreeCodeCamp/FreeCodeCamp#10592]
Challenge [change-the-font-size-of-an-element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 8350.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.

All of my tests are passing even though I didn't change the font size, which is the whole point of the challenge. All I did was make a new paragraph tag with the correct text, and it said all of my tests passed. I can see that there have been other issues with this challenge where it won't let people pass for different reasons, so this bug may be by design, but I thought I should bring it to someone's attention.

``` html


<style>
.red-text {
  color: red;
}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

> ---
> 
> Updated broken challenge link on 22nd October 2016 02:44 AM IST

**Comment by dhcodes** [comment]
Confirmed. Final test does not correctly check if paragraph font-size is added to `style` tags.

**Comment by brandonlee781** [comment]
I would like to try and solve this issue.

**Comment by JosephLivengood** [comment]
Pull requested to fix this issue: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10762

**Comment by sahilkhurana19** [comment]
@dhcodes I have been trying to fix it. Yes that paragraph font-size does gets added to the style tags. The tests works fine when the user enter incorrect font-size but if nothing is added, the challenge is accepted. Here's how I have been trying to deal with it but I can't seem to get it right. `(parseInt($(\"p\").css(\"font-size\"), 10) > 15)&&($(\"p\").css(\"font-size\") != undefined)`  Any help?

**Comment by dhcodes** [comment]
@sahilkhurana19 I think the issue may be that assert tests with .css don't seem to be working on the beta. You may need to convert this to a `code.match` style test with a Regex.

**Comment by Bouncey** [comment]
I've just tried to QA #11306, but I cannot replicate on the production site

**Comment by systimotic** [comment]
I can not reproduce this on both production and staging either.
I have a feeling that there may be some browser setting that thinks it's more important than the 14px font size set on the body (silly browsers 😜)
@Bouncey If the new test works as it should as well, maybe we should just go with that?
