### ISSUE TITLE
Can't pass concat challenge

### ISSUE THREAD

**Issue by atflick** [FreeCodeCamp/FreeCodeCamp#10596]
Challenge [concatenate-arrays-with-concat](https://www.freecodecamp.com/en/challenges/object-oriented-and-functional-programming/concatenate-arrays-with-concat) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Same issue with filter and reverse challenge

```js


var oldArray = [1,2,3];
var newArray = [];

var concatMe = [4,5,6];

// Only change code below this line.

newArray = oldArray.concat(concatMe);

```

**Comment by abhisekp** [comment]
What is the issue? @atflick

**Comment by abhisekp** [comment]
I guess the last test isn't passing

> You should only be using concat to modify the arrays.

**My Solution**
```js
var oldArray = [1,2,3];
var newArray = [];

var concatMe = [4,5,6];

// Only change code below this line.

newArray = oldArray.concat(concatMe);
```

**Comment by atflick** [comment]
![image](https://cloud.githubusercontent.com/assets/18269370/18393998/c9b29208-7685-11e6-90b6-5e93e55adfda.png)

**Comment by dhcodes** [comment]
Seems to possibly be a similar bug as #10548, #10591, and #10589

**Comment by atjonathan** [comment]
This has been fixed.
