### ISSUE TITLE
Escaping Literal Quotes in Strings Code Correct but not allowing to pass?

### ISSUE THREAD

**Issue by JeremiahLewis0710** [FreeCodeCamp/FreeCodeCamp#10601]
Challenge [escaping-literal-quotes-in-strings](https://www.freecodecamp.com/en/challenges/basic-javascript/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36</code>.
In this challenge there is a single quote given in a single string that they used the escape method for. The challenge states to do it with two quotes within a single string. The lay out of my code is the same as the one in the example. There is no output appearing to even tell me what the error is it is just telling me to keep trying. There is no error icons where my code window is either so I don't even know what I'm doing wrong so I feel very strongly this is a bug issue rather than input issue.

```js


var myStr=" I am a \"double quoted\" string inside \"double quotes\".";



```

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!
