### ISSUE TITLE
Can't pass filter challenge

### ISSUE THREAD

**Issue by ZebraLan** [FreeCodeCamp/FreeCodeCamp#10600]
Challenge [filter-arrays-with-filter](https://www.freecodecamp.com/en/challenges/object-oriented-and-functional-programming/filter-arrays-with-filter) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.    

My code is the following:
```js
var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val) {
    return val < 6;
});
```
Yet it fails to pass the fourth test:  
> You should only be using filter to make the new array.

**Comment by Hydrojaime** [comment]
Ive been having the same issue.

**Comment by jamiepyoung** [comment]
Me too....
