### ISSUE TITLE
Beta challanges are showing on prod site

### ISSUE THREAD

**Issue by ltegman** [FreeCodeCamp/FreeCodeCamp#10602]
Challenges such as the JavaScript Slot Machine are marked as beta and should not be showing up on the production site. They currently are showing up nonetheless.

**Comment by dhcodes** [comment]
The react update is live as of today. See the announcement from @BerkeleyTrue on Gitter.

**Comment by BerkeleyTrue** [comment]
That does not neglect this issue. Beta challenges should not show up in production
