### ISSUE TITLE
Why is this failing?

### ISSUE THREAD

**Issue by oneofmygithub** [FreeCodeCamp/FreeCodeCamp#10609]
Challenge [iterate-over-arrays-with-map]
   
    var oldArray = [1,2,3,4,5];
// Only change code below this line.
var newArray = oldArray.map(function(val){
return val+ 3;                            
});

**Comment by dhcodes** [comment]
@oneofmygithub I believe this is a duplicate of issue #10548 . Thanks for reporting. Closing as duplicate.

**Comment by oneofmygithub** [comment]
yes, thank you. I know it's a duplicate, but I can't find the answer in the duplicate issue.

**Comment by dhcodes** [comment]
@oneofmygithub that's because it's a bug in the challenge. It won't work correctly until the issue is fixed. I referenced that issue #10548 so you could follow up there as it is worked on.

**Comment by oneofmygithub** [comment]
i see. thanks
