### ISSUE TITLE
Last Test Not Passing for "Change Font Size of An Element" Challenge

### ISSUE THREAD

**Issue by Sakshi-75** [freeCodeCamp/freeCodeCamp#10603]
Challenge [change-the-font-size-of-an-element](https://www.freecodecamp.com/en/challenges/html5-and-css/change-the-font-size-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

`````` html


<style>
.red-text {
  color: red;
}
p {
  font-size: 16px;
}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
    ```

``````

**Comment by dhcodes** [comment]
@Sakshi-75 I believe this is a browser issue with Firefox. Thanks for reporting!

**Comment by ArielLeslie** [comment]
![image](https://cloud.githubusercontent.com/assets/6234475/18394924/7a8aeac4-7679-11e6-9eba-534a2e7d705a.png)

Your code appears to be passing in Chrome.  This may be related to a Firefox issue.

**Comment by Sakshi-75** [comment]
Thanks for the help!
I ran this program in chrome and it worked :)

**Comment by Irmaultra** [comment]
<style>
  .red-text {
    color: red;
  }
  p {
  font-size: 16px;
}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

Is I'm doing something wrong? No any chainges after i press "run tests"... Google hrome brouser.

**Comment by Irmaultra** [comment]
[fonts size.docx](https://github.com/FreeCodeCamp/FreeCodeCamp/files/465534/fonts.size.docx)

Is I doing something wrong? Is no any chainges after the press the "run tests"button.

**Comment by Irmaultra** [comment]
![image](https://cloud.githubusercontent.com/assets/22114502/18412393/63659352-778d-11e6-85a9-6cf97af48ddb.png)
is it wrong or any bug?

**Comment by P1xt** [comment]
@iamrudra It is a bug - it is being reported by others (where the phone on the right is blank and the tests won't run) here on this ticket: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10678

**Comment by Irmaultra** [comment]
Thanx for a help!

**Comment by iamrudra** [comment]
@P1xt - Did you mean to tag me? ;)

**Comment by P1xt** [comment]
@iamrudra Drat, no - autocomplete fail on my part 😄  

Most of the letters the same !== same name

**Comment by raisedadead** [comment]
Closing as this was probably from the earlier deployment of rectified version of the platform.
