### ISSUE TITLE
Slice and Splice - Confusing instructions

### ISSUE THREAD

**Issue by zelite** [FreeCodeCamp/FreeCodeCamp#10608]
Challenge [slice-and-splice](https://www.freecodecamp.com/en/challenges/basic-algorithm-scripting/slice-and-splice) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js
    
    
function frankenSplice(arr1, arr2, n) {
// It's alive. It's alive!

return arr2;
}

frankenSplice([1, 2, 3], [4, 5, 6], 1);

```

Language in the challenge is not clear. It says: 

>Use the array methods slice and splice to copy each element of the first array into the second array, in order.

However, two of the tests are: 
> The first array should remain the same after the function runs.
> The second array should remain the same after the function runs.

So, if the arrays should remain the same, I'm not really copying from one element into the other.

Proposed alternative text:
> Use the array methods slice and splice to create an array which contains the elements of the second array with the elements of the first array added to the position n in order.

**Comment by jeffrath504** [comment]
arr3.splice(n, 0, ...arr1);  Not sure what the "... " are for but if you splice the whole array it will add the whole array to 1 element.

Example arr1=[1,2] arr2=["a","b"]
arr3.splice(1,0,arr1) = 
"a"
1,2
"b"

**Comment by zelite** [comment]
Did not notice any code got included when creating the issue. The problem I am reporting is related with the wording of the challenge instructions. Gonna remove my code from the original post to not distract from my main point.

**Comment by indianmartini** [comment]
Yes zelite I think the same way, it would be a good idea to modify slightly the instructions...
The way that this challenge is explained is not clear but confusing, and I was struggling some time before to catch the idea of the third array because it clearly asks to copy each element of the first element into the second one.

**Comment by BerkeleyTrue** [comment]
This challenge will be removed shortly. Apologies for the confusion.
