### ISSUE TITLE
Size your Images Bug

### ISSUE THREAD

**Issue by Yrureta** [freeCodeCamp/freeCodeCamp#10614]
Challenge [size-your-images](https://www.freecodecamp.com/en/challenges/html5-and-css/size-your-images) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

`````` html


<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
.red-text {
  color: red;
}

h2 {
  font-family: Lobster, Monospace;
}

p {
  font-size: 16px;
  font-family: Monospace;
}
.smaller-image{
  width:100px;
}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

    ```

``````

**Comment by dhcodes** [comment]
@Yrureta I believe this is a browser-specific issue. Your code does pass in Chrome. Thanks for the issue.

**Comment by Yrureta** [comment]
Thanks, I switched to Chrome and now everything is fine!

**Comment by shikhar0507** [comment]
it worked for me in firefox. The browser zoom should be 100%.
Due to different implementation by various browsers, set your zoom % to 100%.

**Comment by systimotic** [comment]
Closing in favour of #10749
