### ISSUE TITLE
Random whole numbers within range will not pass test

### ISSUE THREAD

**Issue by jdbarras** [FreeCodeCamp/FreeCodeCamp#10613]
#### Challenge Name
Generate Random Whole Numbers within a Range

#### Issue Description
I think my code is correct. It meets the conditions if I log out the results to console but it will not pass the tests.

#### Your Code

```js
 // Example
function ourRandomRange(ourMin, ourMax) {

return Math.floor(Math.random() * (ourMax - ourMin + 1)) + ourMin;
}

ourRandomRange(1, 9);

// Only change code below this line.

function randomRange(myMin, myMax) {

return Math.floor( Math.random() * (myMax - myMin + 1)) + myMin; // Change this line

}

// Change these values to test your function
var myRandom = randomRange(5, 15);
 
 
```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/21320527/18397729/1c051cac-768f-11e6-9b58-8c470689492f.png)

**Comment by yesroh** [comment]
I have the same problem here

**Comment by anurag6** [comment]
+1. I seem to be facing the same issue. Running the code and testing it, I see the min and max being printed as well. But the testcases fail everytime for me.

**Comment by Gslaughl** [comment]
I and others in the Help JavaScript chat page are running into this issue as well, I hope it gets confirmed soon.

**Comment by dhcodes** [comment]
The code posted in OP works on my end in Chrome, Firefox, and Safari. This looks to be isolated to some users/devices similar to #10570

**Comment by rungol** [comment]
I have the same problem.

**Comment by rungol** [comment]
^I ended up copying my code, resetting it, and then pasting it back in and that solved the issue for me.

**Comment by anurag6** [comment]
Yup. Redoing the challenge after resetting the code seems to have done the trick for me.

**Comment by jdbarras** [comment]
I was going to try this out, but I'm on a different computer and it worked right off the bat anyway. No one has said that this workaround doesn't work so I'm going to close the issue. Still a bug, but there seems to be a reliable workaround.

**Comment by kingluddite** [comment]
resetting and re-typing code worked for me as well.
