### ISSUE TITLE
Error says you should have two double quotes 4 escaped quotes, which I have

### ISSUE THREAD

**Issue by luketoboot** [FreeCodeCamp/FreeCodeCamp#10616]
Challenge [escaping-literal-quotes-in-strings](https://www.freecodecamp.com/en/challenges/basic-javascript/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var myStr = "I am a \"double quoted\" string inside \"double quotes\".";


```

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!

**Comment by johnanthony797** [comment]
+1
