### ISSUE TITLE
Slice and Splice

### ISSUE THREAD

**Issue by mpettaw2** [FreeCodeCamp/FreeCodeCamp#10618]
#### Challenge Name

https://www.freecodecamp.com/en/challenges/basic-algorithm-scripting/slice-and-splice

#### Issue Description

the output section does not show my returned items. 

example: function hey(){
return "hey!";
}
hey();
the console box just gives me: //running test and //test completed. I would also like to see my output whether it is wrong or not. it helps with debugging. 

#### Browser Information

* Browser Name, Version: google chorme version Version 52.0.2743.116 m
* Operating System: windows 7
* Mobile, Desktop, or Tablet: desktop

#### Your Code

```js
 
 function frankenSplice(arr1, arr2, n) {
  // It's alive. It's alive!
  var arr=arr1.slice(0, arr1.length);
  var arrMore=arr2.splice(0,n+1);
  arrMore.push(arr);
  arr2.unshift(arrMore);
  
  return arr2;
}

frankenSplice([1, 2, 3], [4, 5, 6], 1);

 
```

**Comment by erictleung** [comment]
@mpettaw2 wrap your function call in `console.log()` and it should output.

```js
console.log(frankenSplice([1, 2, 3], [4, 5, 6], 1));
```

Happy coding!
