### ISSUE TITLE
Bonfire Sum All Primes - Correct output but no verification of completion

### ISSUE THREAD

**Issue by bryanle** [FreeCodeCamp/FreeCodeCamp#1061]
Challenge http://www.freecodecamp.com/challenges/bonfire-sum-all-primes has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Hello, I've completed this challenge and it is verified as correct after I submit it, but  no pop up notification appears and the map still shows the challenge as incomplete. I've attached my code in raw text and screenshots as well. Thanks for looking into this! 

```
var arr = [];
function sumPrimes(num) {
    
for (j = 2; j <= num; j++){
    count = 0;
    for (i = 2; i <= num; i++) {
        if (j % i === 0) {
            count = count + 1;
                if (count == 1 && i == j) {
                    //console.log("Pushed "+j,i);
                    arr.push(j);
                }
        }
    }
}

return (arr.reduce(function(a, b) {
  return a + b;
}));



}

sumPrimes(50);
```
![screen shot 2015-06-22 at 3 53 16 pm](https://cloud.githubusercontent.com/assets/8146707/8291337/e7f4f672-18f6-11e5-8758-d16620e33f12.png)
![screen shot 2015-06-22 at 3 53 21 pm](https://cloud.githubusercontent.com/assets/8146707/8291338/e7f73d92-18f6-11e5-937f-bf93af35170b.png)

**Comment by benschenker** [comment]
Hey @bryanle thanks for posting!

I've been unable to replicate this, so I'll close the issue.  Reopen if you notice it again.
