### ISSUE TITLE
Bug on the "Your h2 element should be red."

### ISSUE THREAD

**Issue by niconiahi** [FreeCodeCamp/FreeCodeCamp#10619]
Challenge [use-a-css-class-to-style-an-element](https://www.freecodecamp.com/en/challenges/html5-and-css/use-a-css-class-to-style-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<style>
.red-text {
  color: red;
}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

    ```

**Comment by erictleung** [comment]
@niconiahi closing this issue as it is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10617. Happy coding!
