### ISSUE TITLE
Slice and Spice not accepting answers

### ISSUE THREAD

**Issue by jeffrath504** [FreeCodeCamp/FreeCodeCamp#10615]
#### Challenge Name
Slice and Spice

#### Issue Description
Using the Chrome debugging tools I looked at the result, arr1 and arr2 and they seem to meet the expected output.  To clone the array I have tried arr2.slice() and Array.from(arr2), but the test results stay the same.
Expected results
1. Results say that response is not in the right order
frankenSplice([1, 2], ["a", "b"], 1) should return ["a", 1, 2, "b"]
2. The first array should remain the same after the function runs.
3. The second array should remain the same after the function runs.

#### Browser Information

* Browser Name, Version: Chrome Version 52.0.2743.116 m
* Operating System: windows 7 64 bit
* Mobile, Desktop, or Tablet: 

#### Your Code

function frankenSplice(arr1, arr2, n) {

  var result = Array.from(arr2); 
 for (var i=0;i<arr1.length;i++)
 {
     result.splice(n+i,0,arr1[i]);
 }

  return result;
}

frankenSplice([1, 2], ["a", "b"], 1);
```js
 
 
 
```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/20459783/18397886/388f0a82-7698-11e6-8002-6e078055c3bc.png)

**Comment by QuincyLarson** [comment]
@jeffrath504 we are removing this challenge completely in a few minutes. It was inadvertently added when we deployed our rectified staging branch. Please skip it for now.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!

**Comment by gitstud** [comment]
i have an identical answer except im using slice instead of from as the direction request.  When i check my work in another console I am getting the correct return value however when i submit my answer through fcc it is not accepted.
