### ISSUE TITLE
Free Code Camp does not moves on to the next Challange 

### ISSUE THREAD

**Issue by ashslash** [FreeCodeCamp/FreeCodeCamp#10610]
#### Browser Information

* Browser Name, Version: Edge
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop/Desktop

#### Your Code

```js
 
 
 
```

**Comment by ashslash** [comment]
Ok, no Clue why It didn't paste anything. Stuck on Challenge 159, here is the link : https://www.freecodecamp.com/en/challenges/basic-javascript/word-blanks
Stuck at running, is not going forward.

**Comment by texas2010** [comment]
@ashslash, Did you ask help first.  if not.  
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by atdheekurteshi** [comment]
I am having the same problem its a bug or the code is wrong:
https://www.freecodecamp.com/en/challenges/basic-javascript/word-blanks

**Comment by ltegman** [comment]
Closing as there are not provided repro steps or challenge code. Please open a new issue with more infromation if you are still experiencing this problem.

Thanks and happy coding!
