### ISSUE TITLE
Full screen map view should not scroll independently

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#10621]
The freecodecamp.com/map view has two independently scrolling sections. See screenshot below.

![](https://www.evernote.com/l/Ar8xomFYSOtK46k3wnqo7ZkhUb_F3IfxjhsB/image.png)

- As a user, when I scroll down - with mouse anywhere in the view - the map should scroll. Currently, I have to mouse over the central column.

- As a user, the top map navigation component should always remain fixed at the top (and not be scrollable like in the above picture).

**Comment by dhcodes** [comment]
I'll take a crack at this.

**Comment by ltegman** [comment]
I'm not sure why it's behaving differently for me, but in my case the full screen map will just not scroll at all. Looks like the container is sizing itself to fit within the parent, hiding most of the content and making it completely unscrollable.

**Comment by zelite** [comment]
If you remove the inline style height ( https://github.com/FreeCodeCamp/FreeCodeCamp/blob/b112753154a2dbd9f65b0272528a82ba859b6641/common/app/routes/challenges/components/map/Map.jsx#L70 ) the full screen map will work properly.   You can test it here http://beta.freecodecamp.com/en/map by using the browser developer tools to remove the inline style of the "map-accordion center-block". I just don't know how this will impact the map drawer.

**Comment by QuincyLarson** [comment]
@zelite awesome - could you make a pull request for this?

**Comment by zelite** [comment]
Unfortunately I don't have so much time for it. I posted here hoping to help some more seasoned contributor to track down the problem.

**Comment by dhcodes** [comment]
I've been working on this a bit, and one issue is that since the drawer and full-page map use the same module, I can't figure out how to modify one without negatively impacting the other. Would help if I knew React probably...
