### ISSUE TITLE
Control Enter no longer submits solution

### ISSUE THREAD

**Issue by P1xt** [FreeCodeCamp/FreeCodeCamp#10623]
#### Challenge Name

Any challenge

#### Issue Description

Yesterday, control enter could be used to test a solution, and then pressed again (if the solution passed) to submit the solution and proceed to the next challenge. That functionality is now missing.

Instead, to submit the solution one must click on the black "toast" that floats in on the lower right of the browser. To further complicate that lack of a keyboard only submit, even clicking the toast isn't always an option because it doesn't persist, eventually it fades, taking the submit button with it

#### Browser Information

* Browser Name, Version:  Chrome, Firefox, Palemoon (latest)
* Operating System: Mac / Ubuntu 16.04 / Manjaro i3
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
 
 
```

**Comment by QuincyLarson** [comment]
@P1xt I found a thread about this and just commented on it at the same exact time you did: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9850

 I'm closing this issue and will reference it in the old thread.
