### ISSUE TITLE
[Convert HTML Entities] Chai test never passes

### ISSUE THREAD

**Issue by violincounter** [FreeCodeCamp/freecodecamp#1062]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue.

The following chai test does not pass for a correct conversion:
`assert.strictEqual('<>', '<>', 'should escape characters');`

I think it should look like this:
`assert.strictEqual(convert('<>'), '<>', 'should escape characters');`

To reproduce, press "Run code".

My code:

    function convert(str) {
      re = new RegExp('(&|<|>|"|\')', 'g');
      str = str.replace(re, function(match) {
        switch (match) {
          case '&':
            return '&amp;';
          case '<':
            return '&lt;';
          case '>':
            return '&gt;';
          case '"':
            return '&quot;';
          case '\'':
            return '&apos;';
        }
      });

      return str;
    }

Really enjoying the course so far. Thank you!

**Comment by LumenTeun** [comment]
This, and all it's dupes (#1069, #1077, #1086, #1088, #1089), was fixed in fe1b3f4d2a3141326c7d8593d3e05e830b3e6cf1. It's currently in stagning but will probably be in production soon. This issue can probably be closed while we wait.

**Comment by BerkeleyTrue** [comment]
@violincounter Thanks for reporting.

@LumenTeun Thanks again for wrangling all those issues. I will close the other duplicates. Staging should be in production soon... hopefully...

**Comment by QuincyLarson** [comment]
Thank you for your help! We've now fixed this in production!
