### ISSUE TITLE
"I found previously solved solution, loading it now". Should be optional

### ISSUE THREAD

**Issue by milpool** [freeCodeCamp/freeCodeCamp#10622]
#### Browser Information

- Browser Name, Version: 
- Operating System: 
- Mobile, Desktop, or Tablet: 
#### Your Code

``` js



```

**Comment by dhcodes** [comment]
This might have unforeseen implications. If able to be added as a choice in the user settings, I think it would be fine.

As an option for each challenge, it would require the majority of users to click an extra time to load up their past work.

**Comment by raisedadead** [comment]
This can be less costlier by simply clearing your code with the reset option. I agree with @dhcodes that it adds to complexity!

Closing as decayed for now.
