### ISSUE TITLE
Should have worked..

### ISSUE THREAD

**Issue by AirCraftApprentice** [FreeCodeCamp/FreeCodeCamp#10637]
Challenge [global-scope-and-functions](https://www.freecodecamp.com/en/challenges/basic-javascript/global-scope-and-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:47.0) Gecko/20100101 Firefox/47.0</code>.

The assignment is to learn the difference between a var and a Global.
Basically anything that isn't defined as var is a Global.
So why do the console shows me it has a problem here?

```js
    
    // Declare your variable here
var myGlobal = 10;
function fun1() {
// Assign 5 to oopsGlobal Here
oopsGlobal = 5;
}
// Only change code above this line
function fun2() {
var output = "";
if (typeof myGlobal != "undefined") {
  output += "myGlobal: " + myGlobal;
}
if (typeof oopsGlobal != "undefined") {
  output += " oopsGlobal: " + oopsGlobal;
}
console.log(output);
}

    ```

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!

**Comment by wrhorne** [comment]
oopsGlobal is not a global variable but a local variable.  Put oopGlobal below the myGlobal and try it.
var myGlobal = 10;
oopsGlobal;
