### ISSUE TITLE
Unable to Finish Challenge

### ISSUE THREAD

**Issue by xenofei** [FreeCodeCamp/FreeCodeCamp#10634]
Challenge [target-the-parent-of-an-element-using-jquery](https://www.freecodecamp.com/en/challenges/jquery/target-the-parent-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Can't complete this challenge, and I had someone double check me in chat to make sure my code was correct. I'm not sure if it's due to the site update that is currently being rolled out. 

It seems the code also causes the "#target1" button to become red instead of just the parent declarative.

![ztjbpiy](https://cloud.githubusercontent.com/assets/15256880/18403730/2d3436e4-76ac-11e6-9b55-4fb4f6f2024a.png)

```html
    
    
<script>
$(document).ready(function() {
  $("#target1").css("color", "red");
  $("#target1").prop("disabled", true);
  $("#target4").remove();
  $("#target2").appendTo("#right-well");
  $("#target5").clone().appendTo("#left-well");
  $("#target1").parent().css("background-color","red");

});
</script>

<!-- Only change code above this line. -->

<body>
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
</body>

    ```

**Comment by xenofei** [comment]
Solved.

Saw another issue from another user who used Firefox and switched to Chrome and got their challenge to continue--switched clients and worked. Seems the new update is affecting certain browsers.

**Comment by xenofei** [comment]
Another issue came up in the Chrome client. Code is verified and completes the challenge and pops up the block to continue to the next challenge--but it doesn't and remains on the same page without advancing.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!
