### ISSUE TITLE
written values are deleted, you can not complete the challenge

### ISSUE THREAD

**Issue by Jfcorp** [FreeCodeCamp/FreeCodeCamp#10633]
Challenge [subtract-one-number-from-another-with-javascript](https://www.freecodecamp.com/es/challenges/basic-javascript/subtract-one-number-from-another-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js
\ file: 
var difference = 45 - 0;




var difference = 45 - 0;



```

```html
\ file: 
var difference = 45 - 33;




var difference = 45 - 33;



```

**Comment by BerkeleyTrue** [comment]
> Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by BerkeleyTrue** [comment]
Due to the high amount of noise due to the new release, I'm closing for now. Please provide details for this issue to be re-opened.

Happy Coding
