### ISSUE TITLE
Cancel doesn't work on Bug report modal

### ISSUE THREAD

**Issue by P1xt** [FreeCodeCamp/FreeCodeCamp#10632]
#### Challenge Name

All challenges

#### Issue Description

Click "bug" on any challenge. Neither the cancel or "x" will allow you to cancel the popup.
 Reported by manosziogou on the forums
#### Browser Information

* Browser Name, Version: Cross-browser
* Operating System: Mac, Ubuntu, Manjaro
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
 
 
```
#### Screenshot

![truncate a string free code camp](https://cloud.githubusercontent.com/assets/322175/18403329/ba9d6968-76a9-11e6-8276-6382c49e4d24.png)

**Comment by lacrx** [comment]
I added
`onClick={ closeBugModal }`
to the 'Close' and 'X' buttons, which solves the issue.
