### ISSUE TITLE
Challenge with double quotes seems in error.

### ISSUE THREAD

**Issue by penguin27** [FreeCodeCamp/FreeCodeCamp#10646]
Challenge [escaping-literal-quotes-in-strings](https://www.freecodecamp.com/en/challenges/basic-javascript/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var myStr; // Change this line
myStr = "I am a \"double quoted\" string inside \"double quotes\".";

```
This is my code above and after being reviewed, nobody seems to be able to find what the auto test says is wrong.  Any help is greatly appreciated.

**Comment by P1xt** [comment]
Ignore the bot @penguin27 - this is an actual bug.

**Comment by BerkeleyTrue** [comment]
@P1xt While it is an issue, it a duplicate issue that has been reported several times.

@penguin27 
Closing as duplicate

Please see http://forum.freecodecamp.com/t/creating-a-new-github-issue/18392

Happy Coding!

**Comment by penguin27** [comment]
Can you tell me how to go past it so I can complete the lesson?

**Comment by BerkeleyTrue** [comment]
The challenge is currently broken. Please move to the next one until it is fixed.

**Comment by penguin27** [comment]
How do I move past it?

**Comment by vectorhsi** [comment]
var myStr;
myStr= "I am a \"double quoted\" string inside \"double quotes\".";

My code is this and passed.
Make sure to use Spacebar to indent your code.Sometimes its just the indent problem.
If you wanna move past it just select Map to do another one

**Comment by texas2010** [comment]
@vectorhsi 
Please don't put your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by divined45** [comment]
C 18388 c c 8e 7 828x838e88w,8w8g



Sent from my Verizon, Samsung Galaxy smartphone

-------- Original message --------
