### ISSUE TITLE
Quoting strings with single quotes

### ISSUE THREAD

**Issue by kricketservis** [FreeCodeCamp/FreeCodeCamp#10641]
Challenge [quoting-strings-with-single-quotes](https://www.freecodecamp.com/en/challenges/basic-javascript/quoting-strings-with-single-quotes) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Follow steps below to decipher quoting string with single quotes: (It continues to tell me I do not have two single quotes and 4 double quotes.)
Remove all the backslashes (\)
You should have two single quotes ' and four double quotes "
Only remove the backslashes \ used to escape quotes.

```js


var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';




```

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see http://forum.freecodecamp.com/t/creating-a-new-github-issue/18392

Happy Coding!
