### ISSUE TITLE
Can't get a Check for Silver Background in Div

### ISSUE THREAD

**Issue by MissMyDad** [FreeCodeCamp/FreeCodeCamp#10645]
Same problem it seems as others. All I care about is that they clear it for the certificate.
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
  
 .silver-background {background-color: silver;}  
  
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<div class="silver-background">
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
</div>

**Comment by erictleung** [comment]
@MissMyDad closing as duplicate as https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10535. Happy coding!

**Comment by EfyourK** [comment]
.silver-background {background-color: silver;}  
  }

... seems like you got an extra }
