### ISSUE TITLE
Change the CSS of an Element Using jQuery

### ISSUE THREAD

**Issue by ayansug** [FreeCodeCamp/FreeCodeCamp#10647]
The text has turned red, but I'm still not allowed to proceed.
![screen shot 2016-09-09 at 8 15 41 pm](https://cloud.githubusercontent.com/assets/21963939/18406389/4519ea7e-76ca-11e6-9257-58b39c3b5309.png)

**Comment by dhcodes** [comment]
Thanks for the issue! Closing as duplicate of #10569
