### ISSUE TITLE
dodger-blue don't pass the test whit chromium

### ISSUE THREAD

**Issue by jpmti2016** [FreeCodeCamp/FreeCodeCamp#10649]
Challenge [use-hex-code-to-mix-colors](https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/52.0.2743.116 Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<style>
.red-text {
  color: #FF0000;
}
.green-text {
  color: #00FF00;
}
.dodger-blue-text {
  color: #1E90FF;
}
.orange-text {
  color: #FFA500;
}
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

    ```

**Comment by jpmti2016** [comment]
![dodger-blue-text-wrong](https://cloud.githubusercontent.com/assets/22106648/18406627/633f6b66-76cd-11e6-95df-1766465da22b.png)

**Comment by alanbares** [comment]
Just submitted a PR for this and it was mentioned in a previous issue #10523

**Comment by DylanMcGee** [comment]
I'm having the same issue.  will skip for now.  Using chrome on windows 10

**Comment by DylanMcGee** [comment]
+1

**Comment by chrisxtene** [comment]
I am currently having the same issue as well. Using chrome too.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate and already fixed.

Please see http://forum.freecodecamp.com/t/creating-a-new-github-issue/18392

Happy Coding!
