### ISSUE TITLE
"Use Hex Code to Mix Colors" Bug

### ISSUE THREAD

**Issue by ezana11** [FreeCodeCamp/FreeCodeCamp#10640]
Challenge [use-hex-code-to-mix-colors](https://www.freecodecamp.com/en/challenges/html5-and-css/use-hex-code-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I entered the correct hexidecimal values but the dodger blue hex value is still showing to be incorrect. Would appreciate some help with this so I can mark this challenge as complete. 

```html
    
    
<style>
.red-text {
  color: #FF0000;
}
.green-text {
  color: #00FF00;
}
.dodger-blue-text {
  color: #1E90FF;
}
.orange-text {
  color: #FFA500;
}
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

    ```

**Comment by erictleung** [comment]
@ezana11 thanks for the issue. This is a known issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10523. Closing this issue as a duplicate. Happy coding!
