### ISSUE TITLE
Bug Found

### ISSUE THREAD

**Issue by Adeelasq** [FreeCodeCamp/FreeCodeCamp#10652]
Challenge [escaping-literal-quotes-in-strings](https://www.freecodecamp.com/en/challenges/basic-javascript/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var myStr = "I am a \"double quoted\" string inside \"double quotes\".";


```

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see http://forum.freecodecamp.com/t/creating-a-new-github-issue/18392

Happy Coding!
