### ISSUE TITLE
Lessons shouldn't use domains which aren't controlled by freecodecamp

### ISSUE THREAD

**Issue by rtpHarry** [FreeCodeCamp/FreeCodeCamp#1065]
Several of the early waypoint lessons are using `catphotoapp.com`

I can see that clicking the link has been disabled in the lesson but you are basically encouraging people to visit it in their browser by using the domain.

Somebody has already registered this domain probably because of this lesson. 

They don't appear to be connected to the Free Code Camp organisation from looking in the whois details.

At the moment it is a generic landing page but could easily be replaced with inappropriate adverts or malware.

The solution is to either register domains you're going to use in lesson examples or use `www.example.com` which has been specifically reserved by ICANN for this kind of purpose.

**Comment by BerkeleyTrue** [comment]
see #2697
