### ISSUE TITLE
Same issue as #6019 - correct code does not validate, tried adding and removing lines

### ISSUE THREAD

**Issue by OliverGrimsley** [FreeCodeCamp/FreeCodeCamp#10658]
Challenge [use-comments-to-clarify-code](https://www.freecodecamp.com/en/challenges/responsive-design-with-bootstrap/use-comments-to-clarify-code) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36</code>.

Correct code shown below results in red X error "Start a comment with <!-- at the top of your HTML.":
![untitled](https://cloud.githubusercontent.com/assets/12251451/18407412/bf311acc-76dd-11e6-95f0-7ebbd58d8407.png)

Same Issue as here: [6019](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/6019) - I have *no lines above or below*, but tried adding them, no effect.

```html
<!-- Only change code above this line. -->
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```

**Comment by ltegman** [comment]
I'm not able to repro this error and it looks like it came during our rocky React launch that has been rolled back. I'm closing this as resolved, but please let us know if you're still experiencing the issue after doing a browser cache clear and refresh. Thanks and happy coding!
