### ISSUE TITLE
Escaping Literal Quotes in Strings Bug.. the neverending saga

### ISSUE THREAD

**Issue by ajdw** [FreeCodeCamp/FreeCodeCamp#10653]
Challenge [escaping-literal-quotes-in-strings](https://www.freecodecamp.com/en/challenges/basic-javascript/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; 
```

**Comment by wrhorne** [comment]
Having the same trouble on a win 10 PC.  Also running Firefox in fact had to use Firefox just to get this far with the JavaScript.

**Comment by ajdw** [comment]
@wrhorne I wonder what it is? I've looked into forums with previous submissions about this particular problem. Do you think it's a bug?

**Comment by ajdw** [comment]
@wrhorne It's a Firefox issue. I just tried doing it in Google Chrome and it passed. Tell me if it works for you?

**Comment by BerkeleyTrue** [comment]
Closing as duplicate. This challenge is known to be broken.

Please see http://forum.freecodecamp.com/t/creating-a-new-github-issue/18392

Happy Coding!

**Comment by fmd123** [comment]
It's not working in Chrome either... :-(

**Comment by XenoDelMoto** [comment]
Same issue
