### ISSUE TITLE
Bug Found in Challenge "Change the Color of Text"

### ISSUE THREAD

**Issue by ceciland62** [FreeCodeCamp/FreeCodeCamp#10664]
#
[Coding Bug.docx](https://github.com/FreeCodeCamp/FreeCodeCamp/files/465219/Coding.Bug.docx)
Hi! After completing a few challenges, I think I encountered a bug.  I followed the instructions on changing text color, and the text turned red, so I think I wrote this correctly.  But the system won't send me to the next challenge, claiming I didn't do this right.  See code input and the system response below.  Can someone from CodeCamp admin fix this so I can continue funfun coding? Thanks!

My Code:
<h2 style="color:red">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

Response: 
Your h2 element should be red.

**Comment by ceciland62** [comment]
<h2 style="color:red">CatPhotoApp</h2>

**Comment by ceciland62** [comment]
Hi. I skipped this one, and tried the CSS, plugged in the code, the iphone turned Blue, and the system is still saying that CatPhotoApp thing needs to be blue.  I think that one has a bug too.

**Comment by Marmiz** [comment]
Hello @ceciland62, there's a known issue on some challenges if you're using Firefox.
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10595

Are you experiencing the same issues?

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see http://forum.freecodecamp.com/t/creating-a-new-github-issue/18392

Happy Coding!

**Comment by ceciland62** [comment]
Thanks @Marmiz, I was using Firefox.  It all works now on Chrome.

**Comment by wbprkr** [comment]
I am having this problem in Chrome currently.
