### ISSUE TITLE
Problem with Change the Color of Text

### ISSUE THREAD

**Issue by AnimeHeart** [FreeCodeCamp/FreeCodeCamp#10663]
Challenge [change-the-color-of-text](https://www.freecodecamp.com/en/challenges/html5-and-css/change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html

<h2 style="color: red">CatPhotoApp</h2>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by erictleung** [comment]
@AnimeHeart thanks for the issue. This is a known issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10588. Closing this issue in favor of that issue. Happy coding!
