### ISSUE TITLE
"I am a \"double quoted\" string inside \"double quotes\"."

### ISSUE THREAD

**Issue by perfectine** [FreeCodeCamp/FreeCodeCamp#10665]
Challenge [escaping-literal-quotes-in-strings](https://www.freecodecamp.com/en/challenges/basic-javascript/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hello there. The code seem to be correct but I still can't pass the "use two double quotes (") and four escaped double quotes (\")" issue. Am I mistaken and there's something wrong with the code, or I got it right and it just doesn't want to go through?

Thanks

![screen shot 2016-09-10 at 12 17 31 am](https://cloud.githubusercontent.com/assets/21070029/18407945/eeb70090-76ec-11e6-8945-6e76c2ee8dcc.png)

```js



var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; // Change this line



```

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see http://forum.freecodecamp.com/t/creating-a-new-github-issue/18392

Happy Coding!

**Comment by Momus** [comment]
If you close the issue as a duplicate, could you please also link to the main bug report that this is an issue of?  There are, indeed several bug reports for this, all of them are closed, yet the issue still persists.
