### ISSUE TITLE
Adjusting the Padding of an Element

### ISSUE THREAD

**Issue by CodeNameTrent** [FreeCodeCamp/FreeCodeCamp#10669]
#### Challenge Name

https://www.freecodecamp.com/challenges/adjusting-the-padding-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.injected-text%20%7B%0A%20%20%20%20margin-bottom%3A%20-25px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.box%20%7B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-color%3A%20black%3B%0A%20%20%20%20border-width%3A%205px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.yellow-box%20%7B%0A%20%20%20%20background-color%3A%20yellow%3B%0A%20%20%20%20padding%3A%2010px%3B%0A%20%20%7D%0A%20%20%0A%20%20.red-box%20%7B%0A%20%20%20%20background-color%3A%20red%3B%0A%20%20%20%20padding%3A%2020px%3B%0A%20%20%7D%0A%0A%20%20.green-box%20%7B%0A%20%20%20%20background-color%3A%20green%3B%0A%20%C2%A0%20%20padding%3A%202px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch5%20class%3D%22injected-text%22%3Emargin%3C%2Fh5%3E%0A%0A%3Cdiv%20class%3D%22box%20yellow-box%22%3E%0A%20%20%3Ch5%20class%3D%22box%20red-box%22%3Epadding%3C%2Fh5%3E%0A%20%20%3Ch5%20class%3D%22box%20green-box%22%3Epadding%3C%2Fh5%3E%0A%3C%2Fdiv%3E%0A

#### Issue Description

The challenge saids "Your green-box class should give elements 20px of padding." When I change the padding of green-box in style element to 20px, I noticed the image of the green box on the bottom becomes smaller in size. I press Run Test and did not pass. I tried changing the px of the padding, but no matter if I increase the number or decrease the green box image stays small. I am operating on Chrome browser on my Samsung S6 phone. I then tried the challenge again on my Macbook, and it works. Weird. Definitely an issue with this challenge on my smart phone.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by CodeNameTrent** [comment]
I would like to provide a screenshot, but how do I post it?

**Comment by ltegman** [comment]
I don't know how they got there, but there are illegal whitespace characters in your CSS code (CSS is very particular about what whitespace characters are legal). If you reset your code and type the changes by hand you can be sure there will be no illegal characters.

Also, you can post screenshots by simply pasting or drag/dropping them into the Github text editor.

Closing as not an issue with the site. Thanks and happy coding!

**Comment by KrisAlaine** [comment]
Hi encountering almost similar. Green size is same with Red but won't pass.

**Comment by Nikkyra** [comment]
Am also having the same issue....even after changing my green box to 20px

**Comment by Nikkyra** [comment]
style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .yellow-box {
    background-color: yellow;
    padding: 10px;
  }
  
  .red-box {
    background-color: red;
    padding: 20px;
  }

  .green-box {
    background-color: green;
    padding: 20px;
  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>
