### ISSUE TITLE
Change the Color of Text challenge doesn't work on firefox while works fine in Google Chrome

### ISSUE THREAD

**Issue by muhamidelsayed** [FreeCodeCamp/FreeCodeCamp#10662]
Challenge [change-the-color-of-text](https://www.freecodecamp.com/en/challenges/html5-and-css/change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html

<h2 style="color: red">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by erictleung** [comment]
@muhamidelsayed thanks for the issue. This is a known issue on FireFox https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10595. Several other people have mentioned difficulties using the browser. The only thing I can recommend right now is trying a different browser to continue or to wait until we sort out the issue. Thanks for your patience and happy coding!
