### ISSUE TITLE
Entering invalid markup will affect the surrounding testcase list

### ISSUE THREAD

**Issue by rtpHarry** [FreeCodeCamp/freecodecamp#1066]
In this lesson: http://www.freecodecamp.com/challenges/waypoint-add-alt-text-to-an-image-for-accessibility

It instructs you to add an alt tag. I started typing the code like this:

    <a href='#'><img alt="  class='smaller-image thick-green-border' src='https://bit.ly/fcc-kittens'/></a>

Invalid code, yes but I'm still typing the answer in. As soon as I put the first `"` after the `alt=` the testcase list disappears:

![image](https://cloud.githubusercontent.com/assets/1038062/8293296/5ff8175a-192c-11e5-8695-e9619cae21db.png)

I haven't dug into it but I would expect my input to be sandboxed from affecting the rest of the site and the instructions shouldn't disappear while I'm typing them.

OS: Windows 8.1
Browser: Chrome Version 43.0.2357.124 m (64-bit)

**Comment by digitaldak** [comment]
Yea i reported the same thing via #1007, dont recall if its the same waypoint.

**Comment by BerkeleyTrue** [comment]
This is expected behavior. You code is run on every keystroke. This prevents the tests from crashing the browser.

Happy Coding!
