### ISSUE TITLE
Escape Sequences in Strings

### ISSUE THREAD

**Issue by ashishbelwal** [FreeCodeCamp/FreeCodeCamp#10677]
var myStr="FirstLine(2 backslash)n\SecondLine(3 backslash)rThirdLine"; // Change this line

is there any problem with this? 
Browser : Crome
Windows 10

**Comment by MiloATH** [comment]
The order of the backslashes between FirstLine and SecondLine is incorrect. Use `FirstLine\n\\SecondLine`. Please ask questions about your code first at [![Join the chat at https://gitter.im/freecodecamp/freecodecamp](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/freecodecamp/freecodecamp?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) before submitting an issue here.
