### ISSUE TITLE
 Escape Sequences in Strings

### ISSUE THREAD

**Issue by akshkshay** [FreeCodeCamp/FreeCodeCamp#10672]
#### Challenge Name

Escape Sequences in Strings 
https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D%22Firstline%5Cn%5C%5CSecondLine%5C%5C%20%5CrThirdline%22%3B%2F%2F%20Change%20this%20line%0A%0A%0A

#### Issue Description
i have tried all the variation of code  to meet the output still its not taking as correct code. in console its working fine.
var myStr="Firstline\n\\SecondLine\\\rThirdline";

#### Browser Information

* Browser chrome, Version: Version 52.0.2743.116 m

* Operating System: windows 10
* Desktop

#### Your Code
var myStr="Firstline\n\\SecondLine\\\rThirdline";
 
```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by MiloATH** [comment]
The l in Thirdline and Firstline needs to be capitalized, and make sure \ is the escape character \\. Please see the [![Join the chat at https://gitter.im/freecodecamp/freecodecamp](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/freecodecamp/freecodecamp?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for questions before submitting an issue.
