### ISSUE TITLE
Slot machine challenges 222-225 Tests pass but wrong validation errors

### ISSUE THREAD

**Issue by pradnyapen** [FreeCodeCamp/FreeCodeCamp#10673]
#### Challenge Name

https://www.freecodecamp.com/en/challenges/basic-javascript/give-your-javascript-slot-machine-some-stylish-images

#### Issue Description

1. Write the required code as instructed in the info.
2. click 'Go' on output window.
3. Run tests

#### Browser Information

* Browser Name, Version: Firefox 48.0.2
* Operating System: win 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
 
    $($('.slot')[0]).html('<img src="' + images[slotOne-1] +'">');
    $($('.slot')[1]).html('<img src="' + images[slotTwo-1] +'">');
    $($('.slot')[2]).html('<img src="' + images[slotThree-1]+'">');
 
```
#### Screenshot

<img width="960" alt="slotmachine" src="https://cloud.githubusercontent.com/assets/20934053/18410757/89e5c83c-7772-11e6-9993-de2996b5bcb0.png">

**Comment by ltegman** [comment]
These challenges are known to be broken and have been removed from the site. Please clear your browser cache and let us know if you are still able to visit them after that.

**Comment by pradnyapen** [comment]
Thanks they are no longer available.
