### ISSUE TITLE
Can't find a mistake. It doesn't accept my code.

### ISSUE THREAD

**Issue by simzzz** [FreeCodeCamp/FreeCodeCamp#10675]
Challenge [Create a Form Element](https://www.freecodecamp.com/challenges/create-a-form-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <input type="text" placeholder="cat photo URL">
</form>

```

**Comment by atjonathan** [comment]
When clicking `Run Tests`, I get this error:
[![https://gyazo.com/936a6a4d490d60396ac762f1e7b774ef](https://i.gyazo.com/936a6a4d490d60396ac762f1e7b774ef.png)](https://gyazo.com/936a6a4d490d60396ac762f1e7b774ef)

**Comment by ltegman** [comment]
I can't repro this issue. Could you clear your browser cache and let us know if the issue persists?

**Comment by dhcodes** [comment]
Same. Code above passed for me in Chrome.

**Comment by BKinahan** [comment]
This could've been a bug introduced while the beta was put into production temporarily the other day.. Has someone tested it on the beta?

**Comment by marhyorh** [comment]
Works on beta for me :smile:

**Comment by atjonathan** [comment]
Yeah, it's working for me now 😂
