### ISSUE TITLE
Whole progress is gone. mail verification process has reset my account. 

### ISSUE THREAD

**Issue by 333Yalindre** [FreeCodeCamp/FreeCodeCamp#10674]
my account : https://www.freecodecamp.com/333yalindre

My whole progress is gone now. I was at level 290.. Last night i've finished "diff two arrays" challenge and submit it successfully. then i went to my profile page. then **i saw a message that I have no mail address connected to fcc**. i'm sure its there before. but then i've added my email address. and verified it. 

just after that my whole progress is gone. **I think some how there is a issue with mail section. i think adding a mail address is making a whole new duplicate account (Quincy said that may be i've accidently make a duplicate and it may be the issue.). but the problem is my github is also linked to the account which is  reset.** 

I mailed the team@freecodecamp. but still no response. so please check this issue. otherwise people will loose there focus. no doubts this is the best code camp ever. i'd love to contribute also after i got more experience and knowledge. thanks...

**Comment by foalish** [comment]
I have exactly the SAME problem as you in all respects .. the github the  duplicate account.. the reseting of the challenges done. Im sure Quincy and the team will sort us all out  in a few days... 

my account is [ https://www.freecodecamp.com/foalish  ]

**Comment by QuincyLarson** [comment]
@foalish @333Yalindre Yes - this is almost certainly a problem with duplicate accounts. @foalish could you send an email to team@freecodecamp.com ? I can sort this out for you.

**Comment by michaelachrisco** [comment]
Might be related, but I got the duplicate account error and then this happened: 

<img width="1103" alt="screen shot 2016-09-10 at 1 37 20 pm" src="https://cloud.githubusercontent.com/assets/398491/18413394/dcb9d7fe-775b-11e6-882f-738fb6527e7d.png">

**Comment by QuincyLarson** [comment]
@BerkeleyTrue Is there a way we can change main.js to force a refresh? Thisis affecting a lot of people.

**Comment by QuincyLarson** [comment]
This issue has now been fixed. If you notice this problem again, please reopen it with an explanation of the problem. Thanks for reporting this.

**Comment by 333Yalindre** [comment]
@QuincyLarson Thank you ! but still my progress is missing.. hope you could do something about that too.. sent 2 mails to the team..
