### ISSUE TITLE
Misleading note in waypoint create a text field

### ISSUE THREAD

**Issue by rtpHarry** [FreeCodeCamp/FreeCodeCamp#1067]
I wasn't sure if this one was going too far but figured I would throw it open for discussion.

In lesson http://www.freecodecamp.com/challenges/waypoint-create-a-text-field it says:

    You can create one like this: <input type='text'>. Note that input elements are self-closing.

Thats not a self closing tag which would look like `<input type='text' />` but this isn't valid html5.

To be technically accurate the note should say input elements are void elements which don't have an end tag (or probably just keep it simple and say they don't have an end tag).

I did [some research](http://stackoverflow.com/a/5047150/156388) and it seems that the spec says web browsers should tolerate it content authors shouldn't use them.

**Comment by digitaldak** [comment]
I second this, the note should be changed to note the void part, it gave me heartburn when i saw it as well.

**Comment by benschenker** [comment]
Thanks @rtpHarry, it looks like this is still an issue.

I'd recommend that we just change it to actually have the self closing tag like you mentioned: `<input type='text' />`.

My guess is this may be too early in the curriculum to talk about void elements, but that stackoverflow post could be put in a further reading section.

**Comment by benschenker** [comment]
Closing as a wontfix. See: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3104#issuecomment-139357489
