### ISSUE TITLE
First page of "Get Set for our Front End Development Projects", nothing happens when I click "Go to my next step"

### ISSUE THREAD

**Issue by MaveyMa** [FreeCodeCamp/FreeCodeCamp#10688]
**Expected Behavior:** When I click "Go to my next step", I should go to my next step.
**Current Behavior:** When I click "Go to my next step", I stay on that page and nothing happens.

I have tried refreshing, clearing cache and history, re-logging in, but the current behavior has not changed.

#### Challenge Name
https://www.freecodecamp.com/challenges/get-set-for-our-front-end-development-projects

#### Issue Description

1. Click 'Map' in menu
2. When side map pops up, click 'basic-front-end-development-projects' under the Front End Dev
3. Click 'Get Set for our Front End Development Projects'
4. Click 'Go to my next step'
5. Nothing happens

#### Browser Information

* Browser Name, Version: Google Chrome, Version 52.0.2743.116 (64-bit)
* Operating System: Mac OS X El Capitan Version 10.11.6
* Desktop (Web)

#### Screenshot

<img width="866" alt="screen shot 2016-09-10 at 2 28 45 pm" src="https://cloud.githubusercontent.com/assets/14988593/18413659/f916f2ae-7762-11e6-8331-d7ef7265b1dd.png">

**Comment by P1xt** [comment]
Confirmed - the "Go to my next step" button doesn't work for me as well.

Google Chrome: Version 52.0.2743.116 (64-bit)
Mac OS X - fully updated

Confirmed - it didn't work in Firefox either.

**Comment by P1xt** [comment]
Additionally, if you go to the next challenge (by navigating to it on your map) here: https://www.freecodecamp.com/challenges/build-a-tribute-page, the submit button doesn't work there either.

**Comment by P1xt** [comment]
@QuincyLarson the cache reset you mentioned in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10678 may have fixed this issue as well. It should probably be confirmed by someone else, but this issue is no longer occurring for me in any browser.

**Comment by ltegman** [comment]
I am also unable to repro after a cache clear. @MaveyMa Could you let us know if that solves the problem for you?

**Comment by MaveyMa** [comment]
Works now!
