### ISSUE TITLE
"Size your Images" there doesn't seem to be a challenge at all

### ISSUE THREAD

**Issue by Tarrton** [FreeCodeCamp/FreeCodeCamp#10689]
Challenge [Size your Images](https://www.freecodecamp.com/challenges/size-your-images) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }
  
  .larger-image {
    width: 500px;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by P1xt** [comment]
This was reported earlier and there are a bunch of folks discussing possible workarounds while they wait for it to be fixed here - https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10678

**Comment by QuincyLarson** [comment]
This issue has now been fixed. If you notice this problem again, please reopen it with an explanation of the problem. Thanks for reporting this.
