### ISSUE TITLE
Selecting from many options with Switch Statements

### ISSUE THREAD

**Issue by chandujstchandu** [FreeCodeCamp/FreeCodeCamp#10680]
Challenge [Selecting from many options with Switch Statements](https://www.freecodecamp.com/challenges/selecting-from-many-options-with-switch-statements#?solution=%0Afunction%20caseInSwitch(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch%20(val)%20%7B%0A%20%20%20%20case%201%20%3A%0A%20%20%20%20%20%20return%20%22alpha%22%3B%0A%20%20%20%20%20%20break%20%3B%0A%20%20%20%20case%202%3A%0A%20%20%20%20%20%20return%20%22beta%22%3B%0A%20%20%20%20%20%20break%20%3B%0A%20%20%20%20case%203%3A%0A%20%20%20%20%20%20return%20%22gamma%22%3B%0A%20%20%20%20%20%20break%20%3B%0A%20%20%20%20case%204%20%3A%20%0A%20%20%20%20%20%20return%20%22delta%22%3B%0A%20%20%20%20%20%0A%20%20%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AcaseInSwitch(1)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```

function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  switch (val) {
    case 1 :
      return "alpha";
      break ;
    case 2:
      return "beta";
      break ;
    case 3:
      return "gamma";
      break ;
    case 4 : 
      return "delta";
     
      
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(1);


```

**Comment by ltegman** [comment]
Issue does not describe a problem. If you continue experiencing a bug please open a new issue with details of the problem and how to reproduce it. Thanks and happy coding!

**Comment by smartkiddo** [comment]
No bug. Instead of return, say answer="alpha" etc.
