### ISSUE TITLE
i have a problem with this challenge 

### ISSUE THREAD

**Issue by mrctc1982** [FreeCodeCamp/FreeCodeCamp#10697]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor.%3C%2Fp%3E%0A%3Cp%3EPurr%20ipsum%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%20%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor.</p>
<p>Purr ipsum eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. </p>
```
i don't know what the problem is here i have not only done what was asked i also resized my browser as asked and it still wont let me go to the next lesson so what exactly should i do now

**Comment by BKinahan** [comment]
Hi @mrctc1982, unfortunately your code is incorrect. Read through the instructions again and if you still need help, visit the [forum](http://forum.freecodecamp.com) or the [Help chat room](https://gitter.im/FreeCodeCamp/Help).

Remember that issues are for reporting bugs with the challenges and website, so when your code doesn't work you should ask for help in the forum or chat before raising an issue.

Happy coding!

**Comment by mrctc1982** [comment]
OK thank you I will review my code sorry I inappropriately opened a ticket
