### ISSUE TITLE
Keyboard

### ISSUE THREAD

**Issue by ryanmcclaran** [FreeCodeCamp/FreeCodeCamp#10698]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by BKinahan** [comment]
Hi @ryanmcclaran, could you please provide some information about the issue you are experiencing?

Thanks!

**Comment by ltegman** [comment]
Please file a new issue with details of your problem and how to reproduce if you are still having a problem. Thanks and happy coding!
