### ISSUE TITLE
Dodger Blue issue

### ISSUE THREAD

**Issue by Khepf** [FreeCodeCamp/FreeCodeCamp#10699]
Challenge [Use Hex Code to Mix Colors](https://www.freecodecamp.com/challenges/use-hex-code-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: #FF0000;
  }
  .green-text {
    color: #00FF00;
  }
  .dodger-blue-text {
    color: #1E90FF;
  }
  .orange-text {
    color: #FFA500;
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

```

**Comment by sf-jd** [comment]
What is the issue exactly Khepf? I do not see a problem with dodger blue on any of the browsers listed.

**Comment by Khepf** [comment]
Looks good now, it appears the hex for dodger blue was changed (it wasn't
working yesterday)

Thanks!

**Comment by ltegman** [comment]
Closing as resolved. Thanks and happy coding!
