### ISSUE TITLE
Convert HTML Entities 2nd Test issue

### ISSUE THREAD

**Issue by jdlam420** [FreeCodeCamp/freecodecamp#1069]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The second test this challenge runs is the following:

assert.strictEqual('<>', '<>', 'should escape characters');should escape characters: expected '<>' to equal '<>'

It's clear from the test that it does not call upon the function convert(), while the other tests do.  I can't get a complete on this challenge and save my code on the site because of this test.  Please fix it.

**Comment by ferrao** [comment]
+1 for this one.

**Comment by BerkeleyTrue** [comment]
@jdlam420 Thanks! We will be tracking this issue at #1062
