### ISSUE TITLE
Filter: Rewrite double negative

### ISSUE THREAD

**Issue by dogweather** [FreeCodeCamp/FreeCodeCamp#10695]
Challenge [Filter Arrays with filter](https://www.freecodecamp.com/challenges/filter-arrays-with-filter) has an issue.

The intro sentence uses a double negative:

> The filter method is used to iterate through an array and filter out elements where a given condition is not true.

I suggest re-writing in the positive because it's easier to read and understand. Also, it's how I happen to think of `filter`, and maybe others do too. Here I made that change, plus removed "filter" from its own definition, and changed it from passive to active voice:

_The filter method iterates through an array and selects elements where a given condition is true._

**Comment by erictleung** [comment]
@dogweather I would amenable to this change.

@FreeCodeCamp/issue-moderators second opinions?

**Comment by hallaathrad** [comment]
"And keep only the elements where a given condition returns true" or something along those lines, maybe?

**Comment by dhcodes** [comment]
"The filter method is used to create a new array by iterating through the array it is called upon and keeping only elements where a given condition returns true."

I think it's important to know that .filter() makes a new array.

**Comment by hallaathrad** [comment]
Oh yeah... I was merely referring to the double negative part of the whole thing.

**Comment by dogweather** [comment]
I like the addition of creating a new array. How about in active voice:

"`filter` creates a new array from an existing one by iterating over it and keeping only the elements where a given condition returns true."

cc: @risachi

**Comment by dhcodes** [comment]
Fine by me @dogweather. Let's not wordsmith this to death 👍

**Comment by shubham1996** [comment]
I am working on this issue. Will send a PR across :)
