### ISSUE TITLE
None of the chalenges work :-(

### ISSUE THREAD

**Issue by alfredoborrero** [FreeCodeCamp/FreeCodeCamp#10691]
None of the challenges work. I tried to press "Run Tests" and doesn't do anything. the console generates errors. I tried with Google Chrome, Opera, Internet Explorer, Firefox Mozilla and does not work and i tried in two computers and have the same issue. I used to work all the time ... but now it is not working.

Any help?
 
![console_errors](https://cloud.githubusercontent.com/assets/9356338/18413804/8d0daa80-7771-11e6-8697-7bb9b9b6467d.png)

Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 OPR/39.0.2256.71</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```

<h1>Hello World</h1>

```

**Comment by P1xt** [comment]
This was reported earlier and others are discussing possible workarounds until it get fixed down in this ticket: 
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10678

**Comment by QuincyLarson** [comment]
I believe this is now fixed. I'm closing it.
