### ISSUE TITLE
I am pretty sure I did this correctly?!?!

### ISSUE THREAD

**Issue by textporter** [FreeCodeCamp/FreeCodeCamp#10696]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3Dpink-text%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink
  }
</style>
<h1 class=pink-text>Hello World!</h1>

```

**Comment by P1xt** [comment]
@textporter I don't think this is an actual bug.

in your h1 tag, the class pink-text needs to have quotes around it `class="pink-text"`

**Comment by textporter** [comment]
Hello,
Thanks for the help. I just tried that and it didn't work?!?!


<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink
  }
</style>
<h1 class="pink-text">Hello World!</h1>

**Comment by P1xt** [comment]
@textporter Ah, there's one more issue in there. You absolute MUST put a semicolon at the end of each CSS rule. See how in the body block every declaration ends in a semicolon - like `color: green;`?

In the pink-text block, you need a semicolon after the color rule like `color: pink;`

**Comment by textporter** [comment]
Ahh..
Thanks.. That worked!!

**Comment by ltegman** [comment]
Closing as resolved. Thanks and happy coding!

**Comment by boolean-cube** [comment]
Getting an error for h1 class, yet seems right to me.

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
</style>
<h1 class:"pink-text">Hello World!</h1>
