### ISSUE TITLE
Broken link on homepage

### ISSUE THREAD

**Issue by sfrapoport** [FreeCodeCamp/freecodecamp#107]
The link to the info about screenhero being free is broken, it sends to http://freecodecamp.com/challenges/34

Happy to take this one on!

Thanks,
Sophie

**Comment by QuincyLarson** [comment]
Hi @sfrapoport, that is intentional. That said, it would probably be better to have a dedicated "install screen hero instructions" page. I'll create it in a moment and link to it. Thanks!

**Comment by sfrapoport** [comment]
Gotcha, thanks!


—
