### ISSUE TITLE
My results are being marked incorrect, despite the fact that I am getting the right answer

### ISSUE THREAD

**Issue by d-m-h** [FreeCodeCamp/FreeCodeCamp#10707]
So I tried to do something unconventional. That is, I chose to forgo the obvious (and perhaps more efficient route) of this:

```javascript
function obviousWay(sentence) {
    
    var _words = sentence.split(' ');
    var _long = 0, _numWords = _words.length;

    for (var i = 0; i < _numWords; i++) {
        if (_words[i].length > _long)
            _long = _words[i].length;
    }

    return _long;
}
```

for this:

```javascript
function longestWord(str) {
    
    var _words = str.split(' ');

    _words = _words.sort(function(a, b) {
        return a.length < b.length;
    });

    return _words[0].length;
}
```

And my result is getting marked incorrectly, despite the return values being correct.

Challenge [Find the Longest Word in a String](https://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=%0Afunction%20longestWord(str)%20%7B%0A%20%20%20%20%0A%20%20%20%20var%20_words%20%3D%20str.split('%20')%3B%0A%0A%20%20%20%20_words%20%3D%20_words.sort(function(a%2C%20b)%20%7B%0A%20%20%20%20%20%20%20%20return%20a.length%20%3C%20b.length%3B%0A%20%20%20%20%7D)%3B%0A%0A%20%20%20%20return%20_words%5B0%5D.length%3B%0A%7D%0A%0AlongestWord(%22What%20if%20we%20try%20a%20super-long%20word%20such%20as%20otorhinolaryngology%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.92 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function longestWord(str) {
    
    var _words = str.split(' ');

    _words = _words.sort(function(a, b) {
        return a.length < b.length;
    });

    return _words[0].length;
}

longestWord("What if we try a super-long word such as otorhinolaryngology");
```

**Comment by d-m-h** [comment]
I just tested with the obvious way as posted above, and I'm still getting the error.

**Comment by ivantedja** [comment]
The challenge is testing a method named `findLongestWord(...)` instead of `longestWord(...) `. Try to change your method's name

**Comment by d-m-h** [comment]
@ivantedja thanks for that.
