### ISSUE TITLE
Tests pass without requiring default case  - Adding a default option in switch statement

### ISSUE THREAD

**Issue by chandujstchandu** [FreeCodeCamp/FreeCodeCamp#10709]
Challenge [Adding a default option in Switch statements](https://www.freecodecamp.com/challenges/adding-a-default-option-in-switch-statements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.

.

My code:
```javascript

function switchOfStuff(val) {
  var answer = "val";
  // Only change code below this line
  switch (val) {
    case "a":
      answer="apple";
      break ;
    case "b":
      answer="bird";
      break ;
    case "c":
      answer="cat";
      break ;
   case "d":
      answer="stuff";
    case 4:
      answer="stuff";
    
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
switchOfStuff(1);


```

**Comment by raalejandre** [comment]
Just initialize the answer variable with the default option, if the value of the parameter is different from the ones in the switch structure then you won't alter the return variable

**Comment by dhcodes** [comment]
The issue here is that the test is not looking for a switch case for 'default'. So the OP's code which is written to the tests passes even though it doesn't include a default case.

**Comment by raalejandre** [comment]
Instead of specify a "d" case and a "4" case you should try this (default: answer="stuff") this way you would get the results you're looking for

**Comment by dhcodes** [comment]
@raalejandre The issue is that the tests pass without doing that. Also, please do not post answers in the issues area. You're welcome to discuss answers and provide help on the [Gitter Help Room](https://gitter.im/FreeCodeCamp/Help) for FreeCodeCamp. Thanks and happy coding!

**Comment by wjhurley** [comment]
I agree with @dhcodes, because the instructions state that you should be creating a switch statement with a default case. I would like to work on this. I can add checking for a default case as the final test.

**Comment by sirpauley** [comment]
Well there is 2 "Breaks" missing, but it would be better to replace both those cases with a default. it simpelfy everything

**Comment by raalejandre** [comment]
i'm going to try adding 
assert(!/default/g.test(code) 'message: You should use a<code>default</code> statement');",
that should fix it

**Comment by coursedian** [comment]
Thank you for sharing this.

**Comment by Trupal24** [comment]
function switchOfStuff(val) {
  var answer = "";
  // Only change code below this line
  switch (val) {
      case "a":
      return"apple";
      break;
     case "b":
      return"bird";
      break; 
      case "c":
      return "cat";
      break;
    default:
      return "stuff";
     
  }
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
switchOfStuff(1);

This is a right code

**Comment by texas2010** [comment]
@Trupal24 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
