### ISSUE TITLE
My Code Pen editor is not working. Its not Editable or saving work. 

### ISSUE THREAD

**Issue by ikechukwuhenry** [FreeCodeCamp/FreeCodeCamp#10704]
Challenge [Build a Random Quote Machine](https://www.freecodecamp.com/challenges/build-a-random-quote-machine) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by dhcodes** [comment]
@ikechukwuhenry Sorry to hear that. Unfortunately, codepen is a service independent of freecodecamp so we are unable to fix issues on that site. You can use their help page to report issues: http://codepen.io/support/

Hopefully it will get fixed soon.

**Comment by ikechukwuhenry** [comment]
thanks @dhcodes  , I fixed it be using safari browser. I guess there is a problem with google chrome
