### ISSUE TITLE
Test cases are no passing my code

### ISSUE THREAD

**Issue by devmurali6** [FreeCodeCamp/FreeCodeCamp#10716]
Challenge [No repeats please](https://www.freecodecamp.com/challenges/no-repeats-please#?solution=%0Avar%20nopermutations%3D%5B%5D%3B%0A%0A%0Afunction%20permAlone(str)%20%7B%0A%0A%20%20%20%20%20%20var%20count%3D0%3B%0A%20%20%20%20%20%20var%20regex1%20%3D%20%2F(.)%5C1%2B%2Fg%3B%0A%20%20%20%20%20%20var%20strarr%20%3D%20str.split('')%3B%0A%0A%20%20%20%20%20%20%20console.log(%22strarr---%22%20%2Bstrarr)%3B%0A%0A%20%20%20%20%20var%20n%3Dstrarr.length%3B%0A%0A%20%20%20%20%20%20var%20results%3DgeneratCombinations(n%2Cstrarr)%3B%0A%0A%20%20%20%20%20%20%20count%3D%20nopermutations.filter(function(str)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20return%20!str.match(regex1)%3B%0A%20%20%20%20%20%20%20%20%20%7D)%3B%0A%0A%20%20%20%20%20%20%20%20%20return%20count.length%3B%0A%0A%20%20%7D%0A%0A%0A%20%20%20%20Array.prototype.swap%20%3D%20function(a%2C%20b%2Cstrarr)%20%7B%0A%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20var%20temp%20%3D%20strarr%5Ba%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20strarr%5Ba%5D%20%3D%20strarr%5Bb%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20strarr%5Bb%5D%20%3D%20temp%3B%0A%20%20%20%20%7D%3B%0A%0A%0A%0Afunction%20generatCombinations(n%2Cstrarr)%7B%0A%20%20%20%0A%20%20%20%20%0A%20%20%20%20%20if(n%3D%3D%3D1)%7B%0A%20%20%20%20%20%20%20%20nopermutations.push(strarr.join(''))%3B%0A%20%20%20%20%20%7Delse%7B%0A%0A%20%20%20%20%20%20%20%20for(var%20i%3D0%3Bi%3Cn-1%3Bi%2B%2B)%7B%0A%20%20%20%20%20%20%20%20%20%20%20generatCombinations((n-1)%2Cstrarr)%3B%0A%20%20%20%20%20%20%20%20%20%20%20if(n%252%3D%3D%3D0)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20strarr.swap(i%2C%20n-1%2Cstrarr)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20else%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20strarr.swap(0%2Cn-1%2Cstrarr)%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20generatCombinations((n-1)%2Cstrarr)%3B%0A%0A%20%20%20%20%20%7D%0A%7D%0A%0A%0ApermAlone('aaab')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var nopermutations=[];
function permAlone(str) {

      var count=0;
      var regex1 = /(.)\1+/g;
      var strarr = str.split('');

       console.log("strarr---" +strarr);

     var n=strarr.length;

      var results=generatCombinations(n,strarr);

       count= nopermutations.filter(function(str){
               
             return !str.match(regex1);
         });

         return count.length;

  }


    Array.prototype.swap = function(a, b,strarr) {
       
            var temp = strarr[a];
            strarr[a] = strarr[b];
            strarr[b] = temp;
    };



function generatCombinations(n,strarr){
   
    
     if(n===1){
        nopermutations.push(strarr.join(''));
     }else{

        for(var i=0;i<n-1;i++){
           generatCombinations((n-1),strarr);
           if(n%2===0){
               strarr.swap(i, n-1,strarr);
           }
           else{
                strarr.swap(0,n-1,strarr);

           }

        }
         generatCombinations((n-1),strarr);

     }
}


permAlone('aaab');

```

If i run each individual test case my code show correct output in console.But when i execute on a whole is passing my code and cant move to next challenge .Can somebody help  please ,Is issue with my code or test cases?

**Comment by erictleung** [comment]
@devmurali6 GitHub is not for coding issues. One thing to check is to not have any global variables. Otherwise, if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by khier996** [comment]
I also had the same problem. I removed the global variable I used before and it worked! 
thanks @erictleung!
