### ISSUE TITLE
Escape Sequences in Strings

### ISSUE THREAD

**Issue by akhil123pp** [FreeCodeCamp/FreeCodeCamp#10713]
#### Challenge Name

    https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D'FirsLine%22%5Cn%22%20%5C%5C%20SecondLine%5Cr%20%5Cn%20%5C%5CThirdLine'%3B%0A%0A

#### Browser Information

* Browser Name, Version: google chrome.
* Operating System: Debian 8.
* Mobile, Desktop, or Tablet: Laptop.
```js
var myStr='FirsLine"\n" \\ SecondLine\r \n \\ThirdLine';
 
 
 
```
#### Screenshot

![screenshot from 2016-09-13 04-21-36](https://cloud.githubusercontent.com/assets/17548354/18455445/b0dd4098-7969-11e6-92e3-6aa1a9a046c4.png)

**Comment by sf-jd** [comment]
The acceptance criteria states there should be no spacing
It also says you should be using only one newline character

Finally, please verify that the text has no typos. 
You almost got it :)

**Comment by erictleung** [comment]
@akhil123pp you have some typos in your code along with spaces, which the instructions state should not be there. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by EpicBeard** [comment]
![capture](https://cloud.githubusercontent.com/assets/6901696/18500474/9dbca51a-79fc-11e6-9c46-ba0d8c24e654.PNG)

I have the same issue. I've used zero spaces, one new line escape and one return escape yet it's not accepting it.

**Comment by texas2010** [comment]
@EpicBeard 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by Roachk** [comment]
This challenge can be pretty confusing with out being able to see the output. Try running this code in a interpreter online like www.codecademy.com or codepen.io. Using the interpreters you can see your output and how it looks. 

![image](https://cloud.githubusercontent.com/assets/20018670/19273940/618999b2-8f9c-11e6-8267-0b9420d3b763.png)
