### ISSUE TITLE
Between style tags change font-size to 16px

### ISSUE THREAD

**Issue by knoahg** [FreeCodeCamp/FreeCodeCamp#10719]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3E%20Purr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%20%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. </p>

```

**Comment by robert-ferguson** [comment]
<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
p {
font-size:16px;
}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. </p>

**Comment by robert-ferguson** [comment]
Hi knoahg 
The challenge asked you to make a second <p> with content and then style that <p> tag between the <style></style> tags. All you have to do is give the font size to the <p> tag as i have done above (also you added a space after the full stop in the paragraph of text you added)

**Comment by robert-ferguson** [comment]
Just add the p {font-size:16px;} in between the style tags also you added a extra space after the full stop (the extra text that was added). I tested the code and it passes, any problems just let me know

**Comment by robert-ferguson** [comment]
![screen shot 2016-09-13 at 12 31 11](https://cloud.githubusercontent.com/assets/22168380/18472229/035b86f6-79ae-11e6-82dc-251ffc6fbaff.jpg)

**Comment by dhcodes** [comment]
@knoahg There is an error with your code. Please consider asking for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) room for FreeCodeCamp. If you are experiencing a bug with this challenge, please reopen this issue. Happy coding!

**Comment by mogwop** [comment]
<style>.red-text {color: red;}</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<style>p{font-size: 16px;}</style>
<p>Kitty ipsum dolor</p>

**Comment by mogwop** [comment]
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<style>p{font-size: 16px;}</style>
<p>Kitty ipsum dolor</p>
