### ISSUE TITLE
Typo in "Sort Arrays with sort" instructions demo code.

### ISSUE THREAD

**Issue by thinsoldier** [FreeCodeCamp/FreeCodeCamp#10715]
The demo code in the instructions should say `return a > b;` and not `return a - b;`
https://www.freecodecamp.com/challenges/sort-arrays-with-sort

**Comment by erictleung** [comment]
@thinsoldier both are valid ways to sort an array. Please read the [MDN page on `.sort`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) for more information on why. I would focus on the `compareFunction` input into the `.sort` method. Happy coding!
