### ISSUE TITLE
Javascript task:concatenating strings with plus operator

### ISSUE THREAD

**Issue by PrincessSarah123** [FreeCodeCamp/FreeCodeCamp#10717]
Javascript task:concatenating strings with plus operator is not allowing me to pass the test even after entering the right answer.

Link:
https://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20%22This%20is%20the%20start.%22%2B%22This%20is%20the%20end.%22%3B%0A%0A
#### Browser Information

* Browser Name, Version: Google chrome
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
 // Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr = "This is the start."+"This is the end.";

 
```

**Comment by PrincessSarah123** [comment]
Issue is solved.......!!it works now

**Comment by dhcodes** [comment]
Thanks for updating @PrincessSarah123. Happy coding!

**Comment by marhyorh** [comment]
@PrincessSarah123 Close the issue :+1:
