### ISSUE TITLE
Typo in text in exercise "Condense arrays with reduce"

### ISSUE THREAD

**Issue by victorwestmann** [FreeCodeCamp/FreeCodeCamp#10712]
Challenge [Condense arrays with reduce](https://www.freecodecamp.com/challenges/condense-arrays-with-reduce#?solution=%0Avar%20array%20%3D%20%5B4%2C5%2C6%2C7%2C8%5D%3B%0Avar%20singleVal%20%3D%200%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AsingleVal%20%3D%20array%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

In the 3rd paragraph it is written "iterating" instead of "iteraCting". With the C. Hope it helps! Thank you for the creator of this amazing tool and all of its amazing community for everything achieved so far! You guys rock.

**Comment by texas2010** [comment]
@victorwestmann, why did you close this issue?

**Comment by texas2010** [comment]
just ignore bot message......

**Comment by victorwestmann** [comment]
Closed it because the bot message told me that "The issue tracker is for reporting bugs only." It got me confused whether this a bug or not. It is definitely a typo in the text. But not sure it is a bug. Can you give me a hand?

**Comment by texas2010** [comment]
@victorwestmann, oh okay.   dont worry about bot message.  you could report for bug or typo.   Someone will check on your issue.  thanks

**Comment by dhcodes** [comment]
@victorwestmann I think the spelling is correct. Note that 'iterating' means to perform repeatedly so in this case iterating through an array means cycling through all the items in an array. Reopen this if I misunderstood.

Happy coding.
