### ISSUE TITLE
code produces correct sum but fails test

### ISSUE THREAD

**Issue by bugeyemonster** [FreeCodeCamp/FreeCodeCamp#10723]
code works and produces the correct result but tests except the first one fail regardless of the console displaying the correct output.

Challenge [Sum All Primes](https://www.freecodecamp.com/challenges/sum-all-primes#?solution=%2F%2F%20%0A%0Afunction%20isPrime(n)%20%7B%0A%20if%20(n%3C2)%20return%20false%3B%20%20%20%0A%20var%20m%3DMath.sqrt(n)%3B%0A%20for%20(var%20i%3D2%3Bi%3C%3Dm%3Bi%2B%2B)%20if%20(n%25i%3D%3D%3D0)%20return%20false%3B%0A%20return%20true%3B%0A%7D%0A%0Avar%20sumOfPrimes%20%3D%200%3B%0Afunction%20sumPrimes(num)%20%7B%0A%20%20for%20(var%20i%20%3D0%3B%20i%20%3C%3D%20num%3B%20i%2B%2B)%7B%0A%20%20%20%20if%20(isPrime(i))%7B%0A%20%20%20%20%20%20sumOfPrimes%2B%3D%20i%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20sumOfPrimes%3B%0A%7D%0A%0AsumPrimes(977)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// noprotect

function isPrime(n) {
 if (n<2) return false;   
 var m=Math.sqrt(n);
 for (var i=2;i<=m;i++) if (n%i===0) return false;
 return true;
}

var sumOfPrimes = 0;
function sumPrimes(num) {
  for (var i =0; i <= num; i++){
    if (isPrime(i)){
      sumOfPrimes+= i;
    }
  }
  return sumOfPrimes;
}

sumPrimes(977);

```

**Comment by augmt** [comment]
Take another look at your code; the issue lies there.

If I run sumPrimes(977) I should get 73156 and if I run sumPrimes(10) right after I should get 17. Instead I get 73156 and 73173.

**Comment by dhcodes** [comment]
@bugeyemonster You have an error in your code. Please consider asking for help in the [Help Javascript Chat](https://gitter.im/FreeCodeCamp/HelpJavaScript) for freeCodeCamp. Cheers!

**Comment by bugeyemonster** [comment]
the code always returns the correct sum for me. If i run sumPrimes(10) i get 17. I have checked a dozen other numbers and the code produces the correct result each time.

**Comment by dhcodes** [comment]
Github issues isn't the place for code help, but since this issue is closed, I believe the problem here is that since your `sumAllPrimes` variable is global, when two tests run back-to-back, the variable gets added together as @augmt has tried to point out. In other words, it would work in most cases but won't pass the tests because of the way the function is constructed (with a global var)

**Comment by bugeyemonster** [comment]
ah.. okay i see that now. thank you.
