### ISSUE TITLE
whats wrong with this code?not accepting correct answer

### ISSUE THREAD

**Issue by Axfinity** [FreeCodeCamp/FreeCodeCamp#10729]
#### Challenge Name

https://www.freecodecamp.com/challenges/reverse-a-string

#### Issue Description

   code is working how it should be but answer is not being accepted.
![bug-2](https://cloud.githubusercontent.com/assets/21281781/18503576/49df594a-7a7b-11e6-9454-1c9dd5104274.PNG)

#### Browser Information

* Browser Name, Version: Google Chrome 53.0.2785.101
* Operating System: win7,32bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
function reverseString(str) {
   var str_array = str.split('');
  var revrs_str = ' ';
   for(var i=str_array.length-1;i>=0;i--){
       revrs_str = revrs_str+str_array[i];
       }
  return revrs_str;
}

reverseString("hello");

 
 
```

**Comment by ivantedja** [comment]
`" olleh"` is not the same with `"olleh"`

your `revrs_str` should be initialized with empty string `''` instead of a space `' '`

**Comment by Axfinity** [comment]
whoops my bad.thank for pointing it out
