### ISSUE TITLE
Jumbotron space issue and blockquote styling issue

### ISSUE THREAD

**Issue by grantknaver** [FreeCodeCamp/FreeCodeCamp#10733]
#### Issue Description
I looking to address two different issues:
1. I cant seem to effectively remove the padding in the right and left of my Jumbotron.  Leaving me with a considerable amount of space on either side of my Jumbotron picture. 
2. Remove a styling hiccup when I use a blockquote after my link section.

#### Your Code
HMTL:

<div class="container ">
  <h1 class="text-center">H.P. Lovecraft</h1>
<div class="jumbotron center-block">
  <img src="http://static1.comicvine.com/uploads/original/11/111746/5015138-29.11.11.jpg" class="img-responsive center-block img-rounded" style="width: 800px">
  
  <blockquote class="text-center">
    <p>"The oldest and strongest emotion of mankind is fear. And the oldest and strongest kind of fear is fear of the unknown."
    </p>
    <footer> H.P Lovecraft</footer>
  </blockquote>
 </div>

<div class=" text-center page-header">
     <blockquote>
     “If I am mad, it is mercy! May the gods pity the man who in his callousness can remain sane to the hideous end!”
     </blockquote>
  </div>
    

CSS: 

.jumbotron {
  width: 80%;
  padding:5px; 
} 

```
![snip of issues](https://cloud.githubusercontent.com/assets/22123589/18513067/78561680-7a51-11e6-91b9-9b901f618513.PNG)

**Comment by dhcodes** [comment]
@grantknaver I'm assuming you are referencing a project you are working on. In that case, consider asking for help in the [HelpFrontEnd chat room](https://gitter.im/FreeCodeCamp/HelpFrontEnd) for fcc.
