### ISSUE TITLE
Back to JS, please. Substitute stringify in example.

### ISSUE THREAD

**Issue by fuecisla** [FreeCodeCamp/FreeCodeCamp#10731]
#### Challenge Name

263- Get JSON with the jQuery getJSON Method 
#### Issue Description

My issue is not a bug, so I apologize if this is not the right place for this.

Just wanted to say that I think it would be much much better not to mix the learning of json with that of JQuery. We should stick to Javascript, please! it makes things way more confusing. JQuery may be very useful and practical in production, but only once you know your JS and understand things. I find myself having to live FCC for a long time to investigate about JQuery and then having to go back to JS to learn what I should have learnt before, so I can go ahead. FCC has huge gaps in this sense. Please, please, get rid of JQuery till the end of JS, and then go for it!

Also I suggest changing the stringify method in the example. It nos obvious for a newbee why would you want to import a json object and then save it as a string with all its notation as opposed to saving it as readable text string. 

Thanks and keep up the good work!
#### Browser Information

- Browser Name, Version: 
- Operating System: 
- Mobile, Desktop, or Tablet: 
#### Your Code

``` js



```

**Comment by dhcodes** [comment]
@fuecisla jQuery is arguably easier than JS for a beginner to learn with regard to DOM manipulation. In the curriculum, it is currently before any of the JS algorithms, etc. so I believe the intent is for campers to explore using it in conjunction with bootstrap and HTML/CSS on their basic front-end projects. 

As to your point about 'stringify', I agree that it's odd that the challenge uses it but doesn't explain it. Perhaps a line should be added in the instructions about what `.stringify()` does in this case.

Thoughts? @FreeCodeCamp/issue-moderators

**Comment by ltegman** [comment]
The jQuery before JavaScript thing is something I've always been conflicted about. We're not the only people who think it is easier and should come first, but I know I personally could not grok jQuery until I knew JavaScript. However, that part is probably just up to how your brain works. 

On the stringify part, I agree that it kind of comes out of the blue. I personally think a note about it would be worth adding.

**Comment by HKuz** [comment]
@fuecisla thanks for noting this - your point about learning the fundamentals before the libraries and "convenience tools" (such as jQuery and Bootstrap) is actually a large part of the new curriculum expansion efforts. The front end sections are being re-ordered (and expanded upon) to focus on basic JS before the jQuery and API sections come up. (If you're interested, you can check out the [tentative challenge structure here](https://github.com/FreeCodeCamp/CurriculumExpansion/issues/46) - it's subject to change but you can get the overall picture). 

That said, there's likely to be issues like the one you pointed out, where challenges may reference things that haven't been covered yet, or the 'original' challenges don't flow perfectly with the new ones being added. As @dhcodes mentions, we can flag that for clarification and once the new curriculum goes live we'll certainly appreciate feedback from campers where lessons aren't self-contained.

**Comment by fuecisla** [comment]
The more I know (which is very little) the more I realise how hard it is for someone that knows a lot to think as someone that does not. It is a skill in itself. So much to learn and such a lack of time... we all skip steps. For me,  ****structure and order, a backbone, a learning path** are the things I appreciate the most of FCC. Thank you so much!!

**Comment by QuincyLarson** [comment]
Thanks for your feedback @fuecisla. We're switching to vanilla JS for API calls in our new JSON API section in our expanded curriculum.
