### ISSUE TITLE
getting X when its right 

### ISSUE THREAD

**Issue by LFD102** [FreeCodeCamp/FreeCodeCamp#10737]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%20%3D%20%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22.%22%3B%20%2F%2F%20Change%20this%20line%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript

var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; // Change this line";


```

Even though I have the correct code its telling me it's not in double quotes  see attached screen shot 
![screenshot 12](https://cloud.githubusercontent.com/assets/18484027/18522354/b8c1dbc4-7a7d-11e6-82c5-601b1e3e7942.png)

**Comment by BKinahan** [comment]
It seems you have added a double-quote (and a semi-colon) to the end of the comment, which is interfering with the test regex. That is, you use three double quotes and four escaped double quotes, rather than two and four.

Removing the double-quote from the comment allows the code to pass.

**Comment by texas2010** [comment]
@BKinahan, I was trying to figure it out but i couldn't.  I didnt realized that person add double quote and semi-colon in end. opps. I didnt see that first place.

**Comment by texas2010** [comment]
@erictleung, since his code is correct but problem is end the line. Do we need to fix it or ignore it?

I think run test suppose to ignore "; in the end.i guess?

**Comment by erictleung** [comment]
@texas2010 I don't have the knowledge to fix this without digging for a long time. However, I know we've had these kinds of issues before with the JS engine interpreting code that's within comments.

@FreeCodeCamp/issue-moderators any guess on how to fix this or if it can be fixed without going through a rabbit hole?

**Comment by texas2010** [comment]
@erictleung, no problem. I am just wondering about fix it or not. because it suppose to ignore javascript comment without affect on correct code.

**Comment by Bouncey** [comment]
you could do something like

```js
let quoteInComments = code.match(/*some regex to capture "'s in comments only*/);

code.match(/[^\\]\"/g).length === (10 - quoteInComments.length);
```

**Comment by atjonathan** [comment]
@Bouncey, update on this?

**Comment by atjonathan** [comment]
Closing as stale.
