### ISSUE TITLE
same results sending but testing still fails.

### ISSUE THREAD

**Issue by salihonder** [FreeCodeCamp/FreeCodeCamp#10742]
array return in alphabetic order still fails

Challenge [Inventory Update](https://www.freecodecamp.com/challenges/inventory-update#?solution=%0Afunction%20updateInventory(arr1%2C%20arr2)%20%7B%0A%20%20%20%20%2F%2F%20All%20inventory%20must%20be%20accounted%20for%20or%20you're%20fired!%0A%20%20var%20index%20%3D%200%3B%0A%20%20var%20newCur%20%3D%20%5B%5D%3B%0A%20%20%2F%2F%20remove%20values%20and%20keep%20item%20names%20only%0A%20%20var%20arrNames%3Darr1.map(function(val)%7B%0A%20%20%20%20return%20val%5B1%5D%3B%0A%20%20%7D)%3B%0A%20%20%0A%20for%20(var%20i%3D0%3Bi%3Carr2.length%3Bi%2B%2B)%20%7B%0A%0A%20%20%20%0A%20%20%20index%20%3D%20arrNames.indexOf(arr2%5Bi%5D%5B1%5D)%3B%0A%20%20%20%2F%2F%20item%20found%0A%20%20%20if%20(index%20%3E%20-1)%20%7B%0A%20%20%20%20%20curInv%5Bindex%5D%5B0%5D%20%2B%3D%20arr2%5Bi%5D%5B0%5D%3B%0A%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20curInv.push(arr2%5Bi%5D)%3B%0A%20%20%20%20%20arrNames.push(arr2%5Bi%5D%5B1%5D)%3B%0A%20%20%20%7D%0A%20%20%20%0A%20%20%20%20%20%0A%20%7D%0A%20%20%0A%20%20arrNames%20%3D%20arrNames.sort()%3B%0A%20%20%0A%20%20for%20(var%20j%3D0%3Bj%3CcurInv.length%3Bj%2B%2B)%20%7B%0A%20%20%20%20%20%2F%2F%20console.log(arrNames.indexOf(curInv%5Bj%5D%5B1%5D))%3B%0A%20%20%20%20newCur%5BarrNames.indexOf(curInv%5Bj%5D%5B1%5D)%5D%20%3D%20curInv%5Bj%5D%3B%0A%20%20%7D%0A%20%20%0A%20%2F%2F%20console.log(newCur)%3B%0A%20%20%0A%20%20%0A%20%20%20%20return%20newCur%3B%0A%7D%0A%0A%2F%2F%20Example%20inventory%20lists%0Avar%20curInv%20%3D%20%5B%0A%20%20%20%20%5B21%2C%20%22Bowling%20Ball%22%5D%2C%0A%20%20%20%20%5B2%2C%20%22Dirty%20Sock%22%5D%2C%0A%20%20%20%20%5B1%2C%20%22Hair%20Pin%22%5D%2C%0A%20%20%20%20%5B5%2C%20%22Microphone%22%5D%0A%5D%3B%0A%0Avar%20newInv%20%3D%20%5B%0A%20%20%20%20%5B2%2C%20%22Hair%20Pin%22%5D%2C%0A%20%20%20%20%5B3%2C%20%22Half-Eaten%20Apple%22%5D%2C%0A%20%20%20%20%5B67%2C%20%22Bowling%20Ball%22%5D%2C%0A%20%20%20%20%5B7%2C%20%22Toothpaste%22%5D%0A%5D%3B%0A%0AupdateInventory(%5B%5B21%2C%20%22Bowling%20Ball%22%5D%2C%20%5B2%2C%20%22Dirty%20Sock%22%5D%2C%20%5B1%2C%20%22Hair%20Pin%22%5D%2C%20%5B5%2C%20%22Microphone%22%5D%5D%2C%20%5B%5B2%2C%20%22Hair%20Pin%22%5D%2C%20%5B3%2C%20%22Half-Eaten%20Apple%22%5D%2C%20%5B67%2C%20%22Bowling%20Ball%22%5D%2C%20%5B7%2C%20%22Toothpaste%22%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.113 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function updateInventory(arr1, arr2) {
    // All inventory must be accounted for or you're fired!
  var index = 0;
  var newCur = [];
  // remove values and keep item names only
  var arrNames=arr1.map(function(val){
    return val[1];
  });
  
 for (var i=0;i<arr2.length;i++) {

   
   index = arrNames.indexOf(arr2[i][1]);
   // item found
   if (index > -1) {
     curInv[index][0] += arr2[i][0];
   } else {
     curInv.push(arr2[i]);
     arrNames.push(arr2[i][1]);
   }
   
     
 }
  
  arrNames = arrNames.sort();
  
  for (var j=0;j<curInv.length;j++) {
     // console.log(arrNames.indexOf(curInv[j][1]));
    newCur[arrNames.indexOf(curInv[j][1])] = curInv[j];
  }
  
 // console.log(newCur);
  
  
    return newCur;
}

// Example inventory lists
var curInv = [
    [21, "Bowling Ball"],
    [2, "Dirty Sock"],
    [1, "Hair Pin"],
    [5, "Microphone"]
];

var newInv = [
    [2, "Hair Pin"],
    [3, "Half-Eaten Apple"],
    [67, "Bowling Ball"],
    [7, "Toothpaste"]
];

updateInventory([[21, "Bowling Ball"], [2, "Dirty Sock"], [1, "Hair Pin"], [5, "Microphone"]], [[2, "Hair Pin"], [3, "Half-Eaten Apple"], [67, "Bowling Ball"], [7, "Toothpaste"]]);

```

**Comment by Bouncey** [comment]
@salihonder Sorry for the late reply.

I have run the test cases through your code and the last test case:
```js
updateInventory([[0, "Bowling Ball"], [0, "Dirty Sock"], [0, "Hair Pin"], [0, "Microphone"]], [[1, "Hair Pin"], [1, "Half-Eaten Apple"], [1, "Bowling Ball"], [1, "Toothpaste"]]);
```
 returns the wrong result for sure.

Maybe this will help you. I am labelling this issue as blocked unless I have not understood the issue. 

If you have managed to resolve the issue, please close this issue.

Thanks for contributing :tada:
