### ISSUE TITLE
Use a CSS Class to Style an Element; Run Test does not work

### ISSUE THREAD

**Issue by mefurqan123** [FreeCodeCamp/FreeCodeCamp#10748]
#### Issue Description

Use a CSS Class to Style an Element; Run Test does not work 

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Labtop

#### Your Code

```HTML
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-class">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

 
 
 
```

**Comment by Nonae** [comment]
I'm having the same problem now!

**Comment by texas2010** [comment]
@mefurqan123 @Nonae 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
