### ISSUE TITLE
Challenge Add image to website, Run Tests yields error if alt string contains Dash '-'

### ISSUE THREAD

**Issue by slspencer** [FreeCodeCamp/FreeCodeCamp#10754]
#### Add images to your website
[https://www.freecodecamp.com/challenges/add-images-to-your-website](https://www.freecodecamp.com/challenges/add-images-to-your-website)

#### Issue Description
Including a dash, or '-' in alt string will show image in phone display area, but 'Run tests' will fail
with an 'x' next to "Your image element must have an alt attribute" error message.

#### Browser Information
on 

* Browser Name, Version: Chrome Version 48.0.2564.103 (64-bit) 
* Operating System: Ubuntu 14.04
* Mobile, Desktop, or Tablet: System 76 Gazelle Pro gezp9

#### Your Code
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="Upside-down kitty">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```
 
 
Here is screenshot of result without the dash:

#### Screenshot
![freecodecamp_addimagestowebsite](https://cloud.githubusercontent.com/assets/578399/18571179/0d70b0d4-7b76-11e6-89b6-5734366dd77e.png)

Here is screenshot of result with the dash: 

![freecodecamp_addimagestowebsite_2]
(https://cloud.githubusercontent.com/assets/578399/18571234/77d24d16-7b76-11e6-891e-26dd2a1efce6.png)

**Comment by dhcodes** [comment]
Thanks for the issue @slspencer. This should be fixed by this PR on next update of the site: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9937 

Closing as such.
