### ISSUE TITLE
Why doesn't it work?

### ISSUE THREAD

**Issue by latheesh9796** [FreeCodeCamp/FreeCodeCamp#10750]
Add a div element below your h3 element.

Still it doesnt work?

```html
<div class="container-fluid">
  <div class="row">
    <h3 class="text-primary text-center">jQuery Playground</h3>
    <div><h2>Hello</h2></div>
  </div>
 </div>
```

**Comment by erictleung** [comment]
@latheesh9796 thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). I would reset your code and try again. You've added code that isn't required for the challenge. Happy coding!
