### ISSUE TITLE
anyone help why can't i get this  escape sequence string code to run?

### ISSUE THREAD

**Issue by jockeytcg** [FreeCodeCamp/FreeCodeCamp#10756]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr="FirstLine\n\\SecondLine\\\rThirdLine";
    myStr="\n\\\\\r";

 
 
```

**Comment by erictleung** [comment]
@jockeytcg thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
