### ISSUE TITLE
Can someone tell me what I'm doing wrong here? 

### ISSUE THREAD

**Issue by somekoreanguy** [FreeCodeCamp/FreeCodeCamp#10760]
Challenge [Create a Set of Checkboxes](https://www.freecodecamp.com/challenges/create-a-set-of-checkboxes#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%3Cul%3E%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%3Col%3E%0A%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%3C%2Fol%3E%0A%3Cform%20fccfaa%3D%22%2Fsubmit-cat-photo%22%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Indoor%3C%2Flabel%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Outdoor%3C%2Flabel%3E%0A%20%20%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%20required%3E%0A%20%20%3Clable%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E1%3C%2Flable%3E%0A%20%20%3Clable%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E2%3C%2Flable%3E%0A%20%20%3Clable%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E3%3C%2Flable%3E%0A%20%0A%20%20%3Cbutton%20type%3D%22submit%22%3ESubmit%3C%2Fbutton%3E%0A%3C%2Fform%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <label><input type="radio" name="indoor-outdoor"> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
  <input type="text" placeholder="cat photo URL" required>
  <lable><input type="checkbox" name="personality">1</lable>
  <lable><input type="checkbox" name="personality">2</lable>
  <lable><input type="checkbox" name="personality">3</lable>
 
  <button type="submit">Submit</button>
</form>

```

**Comment by somekoreanguy** [comment]
The things I need to do: 

1. Your page should have three checkbox elements.
2. Each of your three checkbox elements should be nested in its own label element.
3. Make sure each of your label elements has a closing tag.
4. Give your checkboxes the name attribute of personality.

But for some reason, the #2 and #4 is marked as red.. Not sure what I'm doing wrong here.. anyone?

**Comment by Manish-Giri** [comment]
@somekoreanguy For starters, shouldn't it be `label` instead of `lable`?

**Comment by ivantedja** [comment]
just about to post the comment, @Manish-Giri comment should solve it :)

**Comment by erictleung** [comment]
@somekoreanguy thanks for the issue but as @Manish-Giri has pointed out, checking spelling would be beneficial to passing the challenge. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by dribeiroferr** [comment]
Hey,
I already took that lesson and had searched almost everywhere, and I found a solution for this:

<label for="loving"><input type="checkbox" id="loving" name="personality">loving
</label>
    <label for="funny"><input type="checkbox" id="funny" name="personality">funny
</label>
    <label for="cuddly"><input type="checkbox" id="cuddly" name="personality">Cuddly
</label>
Hope that could be useful ;)

**Comment by dribeiroferr** [comment]
Hey,
I already took that lesson and had searched almost everywhere, and I found a solution for this:

<label for="loving"><input type="checkbox" id="loving" name="personality">loving
</label>
    <label for="funny"><input type="checkbox" id="funny" name="personality">funny
</label>
    <label for="cuddly"><input type="checkbox" id="cuddly" name="personality">Cuddly
</label>
Hope that could be useful ;)

**Comment by Mahmoud-Ostaz** [comment]
<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>

  <a href="#"><img src="https://www.bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>

  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="https://www.freecatphotoapp.com/submit-cat-photo">
    <label for="indoor"><input id="indoor" type="radio" name="indoor-outdoor"> Indoor</label>
    <label for="outdoor"><input id="outdoor" type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
  <form>

     <label>
        Loving
         <input name="personality" type="checkbox">
    </label>

    <label>
        Moody
        <input name="personality" type="checkbox">
    </label>
 
   <label>
Withdrawn
<input name="personality" type="checkbox">
</label>

</form>
</main>
