### ISSUE TITLE
Escape Sequences in Strings challeng #144 

### ISSUE THREAD

**Issue by michelemalagnini** [FreeCodeCamp/FreeCodeCamp#10764]
Escape Sequences in Strings

https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22FirstLine%5Cn%5C%20SecondLine%20%5C%20%5Cr%20ThirdLine%22%3B%0A%0A

#### Issue Description

this is my var : 

 var myStr = "FirstLine \n \ SecondLine \ \r ThirdLine";

it doesn't work HELP ME PLEASE

**Comment by texas2010** [comment]
@michelemalagnini 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by michelemalagnini** [comment]
i'm so sorry :-(
