### ISSUE TITLE
Typo in description of JS switch statement

### ISSUE THREAD

**Issue by 4rkz** [FreeCodeCamp/FreeCodeCamp#10768]
#### Challenge Name

https://www.freecodecamp.com/challenges/selecting-from-many-options-with-switch-statements

#### Issue Description

There is a typo in the description: 

> A switch statement tests a value and can have many case statements which **defines** various possible values.

**Comment by erictleung** [comment]
@4rkz thanks for the issue. Yes, this needs to be changed so that `defines` is changed to `define`.

> A `switch` statement tests a value and can have many `case` statements which define various possible values.

**Comment by 4rkz** [comment]
@erictleung you're welcome.

**Comment by TannerPlauche** [comment]
I'd like to fix this to start getting familiar with the code base and start contributing. I'll take care if this tomorrow 9/17/16

**Comment by ryzokuken** [comment]
why is this bug still in `help wanted`? IF @TannerPlauche isn't working on this, could I?
