### ISSUE TITLE
its an bug of my h1 tag is white its not giving right ans

### ISSUE THREAD

**Issue by jenilevil** [FreeCodeCamp/FreeCodeCamp#10761]
Challenge [Override Class Declarations with Inline Styles](https://www.freecodecamp.com/challenges/override-class-declarations-with-inline-styles#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20%20color%3A%20green%3B%20%7D%0A%20%20.pink-text%20%7Bcolor%3A%20pink%3B%7D%0A%20%20.blue-text%20%7Bcolor%3A%20blue%3B%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20id%3D%22orange-text%22%20class%3D%22pink-text%20blue-text%22%3E%0A%3Ch1%20style%3D%22color%3A%20white%3B%22%3E%0A%20%20Hello%20World!%0A%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
     color: green; }
  .pink-text {color: pink;}
  .blue-text {color: blue;}
</style>
<h1 id="orange-text" class="pink-text blue-text">
<h1 style="color: white;">
  Hello World!
</h1>

```

**Comment by qualitymanifest** [comment]
Not a bug. You have duplicate opening `h1` tags. This isn't valid HTML. Merge the `style` attribute of the second `h1` into your first `h1` and delete the second `h1` opening tag.

**Comment by dhcodes** [comment]
@jenilevil Consider asking for help in the [Help Chat room](https://gitter.im/FreeCodeCamp/Help) for freecodecamp.
