### ISSUE TITLE
Code Challenges should not load tests automatically on page load

### ISSUE THREAD

**Issue by crhain** [FreeCodeCamp/FreeCodeCamp#10765]
I was forced to delete my localStorage file for freecodecamp manually (losing all saved challenges!) in order to get the web page to load again.    The problem is that when you have bad code in a challenge that causes page freezes or browser lockups, there is no way to fix it because every time you reload the page, it runs the code!

**Comment by dhcodes** [comment]
@crhain Your code for completed challenges is stored in your profile, however, as you mentioned, if you clear your cache you will lose code for those challenges that you've started but not successfully submitted. In the future, you might try disabling auto-run via these instructions:
http://forum.freecodecamp.com/t/disable-code-auto-run-on-free-code-camp/19511

Happy coding!
