### ISSUE TITLE
Instruction incomplete in JS course

### ISSUE THREAD

**Issue by 4rkz** [FreeCodeCamp/FreeCodeCamp#10769]
#### Challenge Name

https://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables

#### Issue Description

The instruction:

> Use the playerNumber variable to lookup player 16 in testObj using bracket notation.

doesn't tell what to do with 

> var player

**Comment by erictleung** [comment]
@4rkz thanks for the feedback. The `var player` is used in the challenge tests to make sure you save the correct data that was requested. I feel that the instructions are descriptive enough. What do you propose as a change?

**Comment by 4rkz** [comment]
@erictleung thanks for your answer. As a change i propose something like:

> Using the playerNumber variable to lookup player 16 in testObj using bracket notation, assign his name to the player variable.

**Comment by erictleung** [comment]
@4rkz I can see your point. It is a bit vague.

> Use the `playerNumber` variable to lookup player `16` in `testObj` using bracket notation. Then assign that name to the `player` variable.

**Comment by dhcodes** [comment]
@therialdeal You need to submit a pull request. Please follow the guidelines here: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md

**Comment by vivekrawat1** [comment]
please turn off these emails

**Comment by texas2010** [comment]
@vivekrawat1, looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!
