### ISSUE TITLE
Validation problems with bonfire: convert html entities

### ISSUE THREAD

**Issue by DCAL12** [FreeCodeCamp/freecodecamp#1077]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. 

Issue: The code does not seem to properly validate the '<>' test:
    assert.strictEqual('<>', '<>', 'should escape characters');

The assert statement seems to be missing the convert() function surrounding the first parameter.
Following is the code which is passing all other tests:
```
function convert(str) {
  str = str.replace(/&/g, '&amp;');
  str = str.replace(/</g, '&lt;');
  str = str.replace(/>/g, '&gt;');
  str = str.replace(/"/g, '&quot;');
  str = str.replace(/'/g, '&apos;');
  return str;
}
```

**Comment by saadanerdetbare** [comment]
If changing the validation then charater codes should also be accepted as valid ie. &#62; for &gt;

**Comment by DCAL12** [comment]
the first parameter of the assert statement should still use the convert() function though, correct? Otherwise it's not really validating anything.

**Comment by BerkeleyTrue** [comment]
@DCAL12 Thanks for reporting. We will be tracking this issue at #1062
