### ISSUE TITLE
Three things cats like? Only two are given...

### ISSUE THREAD

**Issue by andysouthwell2** [FreeCodeCamp/FreeCodeCamp#10776]
The problem says add three li elements for the three things cats like, but the question text lists only two. Yes I'm being picky - I just added a third li called 'something else', and it accepted that, but the question ought to really have a third item (or ask for two).

#### Challenge Name

https://www.freecodecamp.com/challenges/create-a-bulleted-unordered-list

#### Issue Description

NA

#### Browser Information

Latest Safari on Mac

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 
NA

#### Your Code

```js
NA 
 
 
```
#### Screenshot

NA

**Comment by atjonathan** [comment]
@andysouthwell2, that is just an example. If i'm misinterpreting your issue, please reopen!

**Comment by andysouthwell2** [comment]
The point is the example should better match what the user is expected to write - it's a bit confusing. Only my opinion though - if you disagree, fine - not worried - just thought I'd raise it.

**Comment by atjonathan** [comment]
I personally think it's too easy to have the example practically identical to the real answer.
cc/ @FreeCodeCamp/issue-moderators

**Comment by BKinahan** [comment]
Right, the example is a shopping list, not a list of things cats love. Maybe some cats love cheese? I don't know.

The structure of the example is what should match the user-written code, not the content or number of items.

**Comment by atjonathan** [comment]
Exactly @BKinahan 👌. Closing.
