### ISSUE TITLE
Compound Assignment With Augmented Multiplication

### ISSUE THREAD

**Issue by dp03105** [FreeCodeCamp/FreeCodeCamp#10773]
Challenge [Compound Assignment With Augmented Multiplication](https://www.freecodecamp.com/challenges/compound-assignment-with-augmented-multiplication#?solution=%0Avar%20a%20%3D%205%3B%0Avar%20b%20%3D%2012%3B%0Avar%20c%20%3D%204.6%3B%0A%0A%2F%2F%20Only%20modify%20code%20below%20this%20line%0A%0Aa%20*%3D%20a%20*%201%3B%0Ab%20*%3D%200.25%20*%20b%3B%0Ac%20*%3D%20c%20*%202.18%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var a = 5;
var b = 12;
var c = 4.6;

// Only modify code below this line

a *= a * 1;
b *= 0.25 * b;
c *= c * 2.173913043478260869565;

It will not go into it evenly. Need help

```

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by faizsehal** [comment]
hi @dp03105  
correct your value this 
c *= c  * 2.173913043478261  

challenge will be passed

**Comment by jokerrapeu** [comment]
incorrect answer pls update. its just wrong

**Comment by arisss1** [comment]
var a = 5;
var b = 12;
var c = 4.6;

// Only modify code below this line

a *= a * 1;
b *= 0.25 * b;
c *= c * 2.173913043478260999565;

**Comment by Guyr989** [comment]
var a = 5;
var b = 12;
var c = 4.6;

function calc(){
console.log(a *= a * 1;);
console.log(b *= 0.25 * b;);
console.log(c *= c * 2.173913043478260999565;);
}

calc();
