### ISSUE TITLE
Local Scope and Functions

### ISSUE THREAD

**Issue by hacker001** [FreeCodeCamp/FreeCodeCamp#10780]
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=%0A%0A%0Afunction%20myLocalScope()%20%7B%0A%0Avar%20myVar%20%3D%20%22strict%22%3B%0A%0A%0A%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0AmyLocalScope()%3B%0A%0A%2F%2F%20Run%20and%20check%20the%20console%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myLocalScope%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript



function myLocalScope() {

var myVar = "strict";


  
  console.log(myVar);
}
myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope


```

**Comment by atjonathan** [comment]
Your code runs fine for me? Try resetting the editor, and running the tests again.
