### ISSUE TITLE
Problem in test Make a Person

### ISSUE THREAD

**Issue by Mograbi** [FreeCodeCamp/FreeCodeCamp#10784]
Challenge [Make a Person](https://www.freecodecamp.com/challenges/make-a-person#?solution=%0Avar%20Person%20%3D%20function(firstAndLast)%20%7B%0A%20%20this.getFirstName%20%3D%20function()%20%7B%0A%20%20%20%20return%20this.firstName%3B%0A%20%20%7D%3B%0A%20%20this.getLastName%20%3D%20function()%20%7B%0A%20%20%20%20return%20this.lastName%3B%0A%20%20%7D%3B%0A%20%20this.getFullName%20%3D%20function()%20%7B%0A%20%20%20%20return%20this.firstName%20%2B%20%22%20%22%20%2B%20this.lastName%3B%0A%20%20%7D%3B%0A%20%20this.setFirstName%20%3D%20function(name)%20%7B%0A%20%20%20%20this.firstName%20%3D%20name%3B%0A%20%20%7D%3B%0A%20%20this.setLastName%20%3D%20function(last)%20%7B%0A%20%20%20%20this.lastName%20%3D%20last%3B%0A%20%20%7D%3B%0A%20%20this.setFullName%20%3D%20function(firstLast)%20%7B%0A%20%20%20%20this.setFirstName(firstLast.split(%22%20%22)%5B0%5D)%3B%0A%20%20%20%20this.setLastName(firstLast.split(%22%20%22)%5B1%5D)%3B%0A%20%20%7D%3B%0A%20%20if%20(firstAndLast%20!%3D%3D%20undefined)%0A%20%20%20%20this.setFullName(firstAndLast)%3B%0A%7D%3B%0A%0Avar%20bob%20%3D%20new%20Person('Bob%20Ross')%3B%0Abob.getFullName()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
please look at the following img "https://www.dropbox.com/s/xstx0qqy01smvxd/Capture.JPG?dl=0"
the test says "Object.keys(bob).length should return 6."
but I think it's supposed to be 8, not 6.
because we already have 6 properties and we added 2 which is firstname and lastname in the line :
var bob = new Person('Bob Ross');

My code:
```javascript

var Person = function(firstAndLast) {
  this.getFirstName = function() {
    return this.firstName;
  };
  this.getLastName = function() {
    return this.lastName;
  };
  this.getFullName = function() {
    return this.firstName + " " + this.lastName;
  };
  this.setFirstName = function(name) {
    this.firstName = name;
  };
  this.setLastName = function(last) {
    this.lastName = last;
  };
  this.setFullName = function(firstLast) {
    this.setFirstName(firstLast.split(" ")[0]);
    this.setLastName(firstLast.split(" ")[1]);
  };
  if (firstAndLast !== undefined)
    this.setFullName(firstAndLast);
};

var bob = new Person('Bob Ross');
bob.getFullName();

```

**Comment by ryzokuken** [comment]
This is, infact the catch to the problem. The firstname and lastname variables do not need to be keys, but be what is called in languages like C++ and Java, a **private variable**.

Therefore, `Object.keys(bob).length` should return 6 as the keys attached remain 6 only, but firstname and lastname are stored in the object as **private variables**.

## This is evident from the two test cases (cases 3 and 4) that expect `bob.firstName` and `bob.lastName` to return `undefined`

**Comment by Mograbi** [comment]
I know what you are saying
But can't understand why my solution is wrong

**Comment by erictleung** [comment]
@Mograbi because you've defined `firstName` and `lastName` using `this`, those variables are accessible outside of the object and become properties of the object. As @ryzokuken has pointed out, the challenge tests imply that `firstName` and `lastName` should be private variables. Your solution isn't "wrong" per se but it is incorrect given the requirements for the challenge. This challenge is testing your knowledge of scope and object creation. You can read more about scope [here](http://web.archive.org/web/20110725013125/http://www.digital-web.com/articles/scope_in_javascript/). I hope that makes sense. Happy coding!

**Comment by Ukmandal** [comment]
var Person = function(firstAndLast) {
  this.getFirstName = function() {
    return this.firstName;
  };
  this.getLastName = function() {
    return this.lastName;
  };
  this.getFullName = function() {
    return this.firstName + " " + this.lastName;
  };
  this.setFirstName = function(name) {
    this.firstName = name;
  };
  this.setLastName = function(last) {
    this.lastName = last;
  };
  this.setFullName = function(firstLast) {
    this.setFirstName(firstLast.split(" ")[0]);
    this.setLastName(firstLast.split(" ")[1]);
  };
  if (firstAndLast !== undefined)
    this.setFullName(firstAndLast);
};

var bob = new Person('Bob Ross');
bob.getFullName();
