### ISSUE TITLE
Iterate Through an Array with a For Loop Has Bug

### ISSUE THREAD

**Issue by ac1982** [FreeCodeCamp/FreeCodeCamp#10788]
Challenge [Iterate Through an Array with a For Loop](https://www.freecodecamp.com/challenges/iterate-through-an-array-with-a-for-loop#?solution=%0A%2F%2F%20Example%0Avar%20ourArr%20%3D%20%5B%209%2C%2010%2C%2011%2C%2012%5D%3B%0Avar%20ourTotal%20%3D%200%3B%0A%0Afor%20(var%20i%20%3D%200%3B%20i%20%3C%20ourArr.length%3B%20i%2B%2B)%20%7B%0A%20%20ourTotal%20%2B%3D%20ourArr%5Bi%5D%3B%0A%7D%0A%0A%2F%2F%20Setup%0Avar%20myArr%20%3D%20%5B%202%2C%203%2C%204%2C%205%2C%206%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20%20total%3D0%3B%0Afor%20(var%20%20i%20%3D%200%3B%20i%20%3C%20myArr.length%3B%20i%2B%2B)%20%7B%0A%20%0A%20%20total%20%3Dtotal%20%2B%20myArr%5Bi%5D%3B%0A%20%20%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArr = [ 9, 10, 11, 12];
var ourTotal = 0;

for (var i = 0; i < ourArr.length; i++) {
  ourTotal += ourArr[i];
}

// Setup
var myArr = [ 2, 3, 4, 5, 6];

// Only change code below this line

var  total=0;
for (var  i = 0; i < myArr.length; i++) {
 
  total =total + myArr[i];   //even if by           total+=myArr[i];
  
}

//total=20;

```

**Comment by erictleung** [comment]
@ac1982 thanks for the issue. You code runs fine for me. Can you elaborate more on what the bug you are experiencing? Like what is the intended outcome and what are you experiencing? Thanks! The more and descriptive the bug, the easier it is for us to help.

**Comment by ac1982** [comment]
After restart my PC, it works well. I have no idea about the bug. 
The reference will be fail with:
`total should equal 20`

**Comment by RowingWolfe** [comment]
I too am experiencing this bug. Using the latest Firefox Developer Edition.

**Comment by graysage** [comment]
Having a problem with the same bug.  This is my code, there doesn't seem to have anything wrong with it.
// Example
var ourArr = [ 9, 10, 11, 12];
var ourTotal = 0;

for (var i = 0; i < ourArr.length; i++) {
  ourTotal += ourArr[i];
}

// Setup
var myArr = [ 2, 3, 4, 5, 6];

// Only change code below this line
var total = 0;
for ( var i = 0; i < myArr.length; i++) {
  total =+ myArr[i];
}

**Comment by texas2010** [comment]
@graysage 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by ar94952** [comment]
graysage:  your total is 6.  It's supposed to be 20.
