### ISSUE TITLE
Submitted Pen to Wrong Section

### ISSUE THREAD

**Issue by Hayden94** [FreeCodeCamp/FreeCodeCamp#10786]
Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
Hello I just finished my tribute page and I accidentally submitted it to the create your own personal portfolio webpage. Is it possible to get that submission removed as I haven't even started working on it yet? Also, I have sent my tribute page to the correct section as well and I do now want that submission removed. I only want my personal portfolio webpage submission removed.

Thank You
--Hayden

**Comment by ryzokuken** [comment]
I don't think there's a way to remove a previous submission, but if you resubmit to it it will update your portfolio with the newer pen. I'd suggest making the portfolio and then resubmitting it.

P.S: I just tried updating my own portfolio, and it worked.

**Comment by erictleung** [comment]
@Hayden94 I don't think there is a way to remove it. However, you could submit a web address pointing to just your GitHub or something as a placeholder instead. 

@FreeCodeCamp/issue-moderators should we have the option to remove submissions from your profile? It seems like a reasonable thing for an individual to be able to do.

**Comment by dhcodes** [comment]
@erictleung It's not a bad idea, but as @ryzokuken said, you can overwrite projects submissions by re-submitting.

**Comment by Hayden94** [comment]
Ok thanks for the response. I will just resubmit my portfolio once I have it completed.

**Comment by QuincyLarson** [comment]
@Hayden94 OK - sounds good. We don't check for academic dishonesty until a certificate is claimed so there's no risk here.

Thanks @dhcodes, @ryzokuken and @erictleung for your help.

**Comment by henry130621** [comment]
邮箱验证打开网页显示404
