### ISSUE TITLE
"Waypoint Mobile Responsive Images" lesson is badly broken

### ISSUE THREAD

**Issue by rtpHarry** [FreeCodeCamp/FreeCodeCamp#1078]
Lesson: http://www.freecodecamp.com/challenges/waypoint-mobile-responsive-images

  1. Instructions are the wrong way around, should assign the class after instructing you to make the new `img` tag
  1. Switches from `https://` to `http://` requirement for second `img`
  1. If you add `img-responsive` to the existing `img` tag you are then unable to complete the lesson even if you add another image below it with the correct `src` and `class`
  1. Lesson accepts itself as complete before you have to close the image tag eg: `<img class="img-responsive" src="http://bit.ly/fcc-kittens2"` is accepted (missing `>` on the end)
  1. Don't think the notes should have the words `responsive design` wrapped in a code tag, previously only seen it used to describe markup.
  1. Don't think this needs the caps either: `Fortunately, we have access to a Responsive CSS Framework called Bootstrap.` should just be `responsive CSS framework`

**Comment by benschenker** [comment]
Thanks @rtpHarry, It looks like the URL for this challenge has changed to: http://www.freecodecamp.com/challenges/waypoint-make-images-mobile-responsive

I was only able to replicate number 4.  I'll leave this issue open for that

**Comment by awesomeaniruddh** [comment]
I was able to replicate 3 and 4.

3 should be a non-issue, because the instructions do not ask you to add `img-responsive` to the first image. The tests have limited power :)

**Comment by awesomeaniruddh** [comment]
Also, 4 is a duplicated of #1021 
Not sure if 3 is going to be fixed so I'll keep the issue open

**Comment by QuincyLarson** [comment]
@rtpHarry thanks for reporting all these issues. Some of them have since been resolved, and I'm accepting @joel-bently's PR to close the remaining ones.
