### ISSUE TITLE
function not work in Chrome( I don't test other browsers)

### ISSUE THREAD

**Issue by ac1982** [FreeCodeCamp/FreeCodeCamp#10789]
Challenge [Iterate over Arrays with map](https://www.freecodecamp.com/challenges/iterate-over-arrays-with-map#?solution=%0Avar%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray%3B%0AnewArray.map(function(val)%7B%0A%20%20return%20val%2B3%3B%0A%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var oldArray = [1,2,3,4,5];

// Only change code below this line.

var newArray = oldArray;
newArray.map(function(val){
  return val+3;
});

// code above will be the result [4, 5, 6, 7, 8] in chrome console.
// but the run tests result will be [1,2,3,4,5], function does not work.

```

URL:https://www.freecodecamp.com/challenges/iterate-over-arrays-with-map#?solution=%0Avar%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray%3B%0AnewArray.map(function(x)%7B%0A%20%20return%20x%2B3%3B%0A%7D)%3B%0A

**Comment by marhyorh** [comment]
You need to assign newArray to your map function and log the result in the console. Pls make use of the [help room](https://gitter.im/FreeCodeCamp/Help) next time. Thank you n close the issue!
