### ISSUE TITLE
Not validation on the amount of nested buttons

### ISSUE THREAD

**Issue by slevin915** [FreeCodeCamp/FreeCodeCamp#10782]
#### Challenge Name
https://www.freecodecamp.com/challenges/add-elements-within-your-bootstrap-wells

#### Issue Description

1. Create the three nested elements within the well "div" elements
2. Run the test
3. Verify that no action happens

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: MacOS (capitan)
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```html
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
        <botton>button</botton>
        <botton>button</botton>
        <botton>button</botton>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <botton>button</botton>
        <botton>button</botton>
        <botton>button</botton>
      </div>
    </div>
  </div>
</div>
```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/21350113/18610038/173782ae-7cdf-11e6-9af4-ecad88036d16.png)

**Comment by texas2010** [comment]
@slevin915 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding..
