### ISSUE TITLE
change the colot text

### ISSUE THREAD

**Issue by faithcode80** [FreeCodeCamp/FreeCodeCamp#10785]
Challenge [Change the Color of Text](https://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (BB10; Kbd) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.3.2.2204 Mobile Safari/537.35+</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by texas2010** [comment]
@faithcode80 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding..
