### ISSUE TITLE
chaining if else statements

### ISSUE THREAD

**Issue by cpereversoff** [FreeCodeCamp/FreeCodeCamp#10790]
Challenge [Chaining If Else Statements](https://www.freecodecamp.com/challenges/chaining-if-else-statements#?solution=%0Afunction%20testSize(num)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if%20(num%3C5)%0A%20%20%20%20return%20%22Tiny%22%3B%0A%20%20else%20if(num%3C10)%0A%20%20%20%20return%20%22Small%22%3B%0A%20%20else%20if(num%3C15)%0A%20%20%20%20return%20%22Medium%22%3B%0A%20%20%20%20else%20if%20(num%3C20)%0A%20%20%20%20%20%20return%20%22Large%22%3B%0A%20%20%20%20%20else%20if(num%3E%3D20)%0A%20%20%20%20%20%20%20return%20%22huge%22%3B%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestSize(20)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testSize(num) {
  // Only change code below this line
  if (num<5)
    return "Tiny";
  else if(num<10)
    return "Small";
  else if(num<15)
    return "Medium";
    else if (num<20)
      return "Large";
     else if(num>=20)
       return "huge";
  
  
  // Only change code above this line
}

// Change this value to test
testSize(20);

```

**Comment by cpereversoff** [comment]
my test size 20 and 25 both = huge when i run them, but its not passing me on those two factors

**Comment by cpereversoff** [comment]
i figured it out, needed to capitalize "H" in huge

**Comment by ryzokuken** [comment]
@cpereversoff: Please close the issue when you figure out what's wrong.

**Comment by cpereversoff** [comment]
I intended to but I couldn't see how

**Comment by texas2010** [comment]
@cpereversoff 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by Preeetrockz** [comment]
just check your word's, what code you have written !!
Like : 
Tiny - tiny
Small - small 
WRIGHT CORRECTLY :)
