### ISSUE TITLE
Getting the correct results for all test cases, yet it won't pass!

### ISSUE THREAD

**Issue by MuhammadMotawe** [FreeCodeCamp/FreeCodeCamp#10796]
Hello,
I had this problem with a previous test but I, somehow, fixed it, then I got stuck on this one.
All test results are correct yet it shows "X" marks on some test cases (depending on the test I use in the code itself!!).

As you can see, I had to use "pop" to remove the last element, I wonder what's the reason that makes it add an extra item to the array, hope someone can clarify on that.

Also I had to "not" use array.prototype.reduce, and I don't know why it didn't work at all for me, it returned null for a lot of cases, but that's a different matter.

Challenge [Sum All Odd Fibonacci Numbers](https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers#?solution=var%20fibs%20%3D%20%5B1%2C%201%5D%3B%0Avar%20sum%20%3D%200%3B%0Afunction%20sumFibs(num)%20%7B%0A%20%20while%20(fibs%5Bfibs.length%20-%201%5D%20%3C%3D%20num)%20%20%7B%0A%20%20%20%20fibs.push(fibs%5Bfibs.length%20-%201%5D%20%2B%20fibs%5Bfibs.length%20-%202%5D)%3B%0A%20%20%7D%0A%20%20fibs.pop()%3B%0A%20%20%0A%20%20%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20fibs.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(fibs%5Bi%5D%20%25%202%20!%3D%3D%200)%20%7B%0A%20%20%20%20%20%20sum%20%2B%3D%20fibs%5Bi%5D%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20return%20sum%3B%0A%0A%7D%0A%0AsumFibs(1)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.8.1000 Chrome/30.0.1599.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var fibs = [1, 1];
var sum = 0;
function sumFibs(num) {
  while (fibs[fibs.length - 1] <= num)  {
    fibs.push(fibs[fibs.length - 1] + fibs[fibs.length - 2]);
  }
  fibs.pop();
  
  
  for (var i = 0; i < fibs.length; i++) {
    if (fibs[i] % 2 !== 0) {
      sum += fibs[i];
    }
  }
  
  return sum;

}

sumFibs(1);

```
Thank you,
Muhammad A. Motawe

**Comment by erictleung** [comment]
@MuhammadMotawe our tests are run one after each other so any global variables you declare are carried from one test execution to another. You have two global variables that are modified unintentionally by the tests. Place those variables (`fibs` and `sum`) within your function and your code will work. Happy coding!

**Comment by MuhammadMotawe** [comment]
that was the same solution to my previous issue, thanks a lot

**Comment by RichardNoob** [comment]
thanks that helped me solve two of my previous challenges
