### ISSUE TITLE
Always pass in Prefilter JSON

### ISSUE THREAD

**Issue by vuongggggg** [FreeCodeCamp/FreeCodeCamp#10794]
(Sorry, my English is not good.)

```js
        // Only change code below this line.
        json = json.filter(function(val) {
          return anything.id !== 1; 
        }); 
```

#### Challenge Name: Prefilter JSON
https://www.freecodecamp.com/challenges/prefilter-json

#### Issue Description
In prefilter, can use any name for variable in comparison `return anything.id !== 1`, and result always pass the challenge but var `anything` is not defined.

**Comment by erictleung** [comment]
@vuongggggg thanks for the issue. Yes, these challenges for JSON APIs and Ajax need work. These will be expanded upon with https://github.com/FreeCodeCamp/CurriculumExpansion/issues/27. So closing this issue as it should be fixed with the curriculum expansion. Happy coding!
