### ISSUE TITLE
Record Collection Issue Question

### ISSUE THREAD

**Issue by pizzarye** [FreeCodeCamp/FreeCodeCamp#10799]
Hey,
I'm working on the [Record Collection Issue](https://www.freecodecamp.com/challenges/record-collection) at the moment.

Can someone please help me understand why my code isn't working?
I've had a quick look at other people's solutions and they took a completely different approach than me. I didn't use any "if ( && )" in my code and I don't see why it would be necessary.

Thank you for your time and help. 

`// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
 if (value!==" ") {
   delete(id.prop);
 } if (prop!=="tracks") {
     if (id.hasOwnProperty("tracks")) {
     tracks.push(value);
     } id.tracks={};
      tracks.push(value);
 } id[prop]=value;
  
  return collection;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");`

**Comment by erictleung** [comment]
@pizzarye as @VarCI-bot has pointed out, GitHub is used to track issues, not for coding help. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
