### ISSUE TITLE
No introduction to Bootstrap section

### ISSUE THREAD

**Issue by rtpHarry** [FreeCodeCamp/freecodecamp#1079]
Just my opinion here but as you complete your first section of waypoints "Basic HTML5 and CSS" you just go straight into the next section "Responsive Design with Bootstrap".

Perhaps should be a bit more fanfare at this point as its your first real milestone in the training.

At least should be some kind of title page saying we are now doing this section as I didn't realise until I went back to the Map page to test something.

**Comment by jbmartinez** [comment]
:+1:

**Comment by BerkeleyTrue** [comment]
this is discussed in #604
