### ISSUE TITLE
Chat and Forum links no longer open glitter/forum

### ISSUE THREAD

**Issue by treiff** [FreeCodeCamp/freecodecamp#108]
Hi,
It's been a few days since I logged in.  I just logged in using the standard e-mail address.  However, now that I am logged in when I click "Chat" I get challenge one instead of opening a page with glitter.  I have already completed challenge one and it used to just open the "Chat".

Also, if I then click "Chat" again while on the challenge one page, glitter will then open.  

The function is the same with forum (except brings up challenge two, once on challenge two click again and forum opens).

I just wanted to mention it, in case it wasn't intended to operate this way. 
Thanks.

**Comment by terakilobyte** [comment]
I'm failing to reproduce this error. Additionally, checking the source the links appear to be valid. I'm closing this issue but feel free to comment and I'll reopen if you still experience it.
