### ISSUE TITLE
Button to unlink of Twitter and LinkedIn accounts

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#10809]
Often campers don't want to show their Twitter/LinkedIn information on their profile any more, or they want to change these to different Twitter/LinkedIn accounts.

Once a user has linked their Twitter account, we should update the button to say "Remove my Twitter from my profile"

The same with the LinkedIn button.

![an image of the settings page and these two buttons](https://www.evernote.com/l/Ar-NrBvk3m1J_4m7oNIpFQLIDKuuPGZ1tWgB/image.png)

**Comment by dhcodes** [comment]
I will take a crack at this and update in a bit if I can't get it working.

**Comment by QuincyLarson** [comment]
@dhcodes OK - great. Note that you'll need to create Twitter and LinkedIn keys o-auth keys for the purpose of testing.

**Comment by QuincyLarson** [comment]
@dhcodes we originally had this functionality (it was built into the Hackathon Starter): https://github.com/sahat/hackathon-starter/blob/master/controllers/user.js#L198

**Comment by dhcodes** [comment]
@QuincyLarson cool I'll check it out and modify as necessary. Thanks.

**Comment by dhcodes** [comment]
I'm opening this back up to anyone that wants it. I've spent a decent amount of time working on it but can't get it working.

**Comment by themaxsandelin** [comment]
Is this issues still up for grabs? I would love to take it on :)

**Comment by QuincyLarson** [comment]
@themaxsandelin I think it's pretty far along already: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10957

There are plenty of other issues in the meantime, though :) Thanks for your help.

**Comment by jmona789** [comment]
I'll take a look at this and see if I can get it working

**Comment by AurusEmir** [comment]
Julio ik o 79 pm pompom
