### ISSUE TITLE
Item requires '0' to return on "getIndexToIns([3, 10, 5], 3) should return 0." when inserting at index 1 would result in the same final array.

### ISSUE THREAD

**Issue by matteszk** [FreeCodeCamp/FreeCodeCamp#10808]
Challenge [Where do I belong](https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=%0Afunction%20getIndexToIns(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20arr.sort(function(a%2Cb)%7Breturn%20a-b%3B%7D)%3B%0A%20%20console.log(arr%2C%20num)%3B%0A%20for%20(var%20i%20%3D%200%3B%20i%3C%20arr.length%3B%20i%2B%2B%20)%7B%0A%20%20%20if%20(num%20%3E%3D%20arr%5Bi%5D%20%26%26%20%20num%3C%3D%20arr%5Bi%2B1%5D)%20%7B%0A%20%20%20%20%20console.log(i)%3B%0A%20%20%20%20%20if%20(num%20%3D%3D%20arr%5Bi%5D)%20return%20i%3B%0Aelse%20%20%20%20%20%20return%20i%2B1%3B%0A%20%20%20%7D%0A%20%20%7D%0A%20%20return%20arr.length%3B%0A%7D%0A%0AgetIndexToIns(%5B40%2C%2060%5D%2C%2050)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function getIndexToIns(arr, num) {
  // Find my place in this sorted array.
  arr.sort(function(a,b){return a-b;});
  console.log(arr, num);
 for (var i = 0; i< arr.length; i++ ){
   if (num >= arr[i] &&  num<= arr[i+1]) {
     console.log(i);
     if (num == arr[i]) return i;
else      return i+1;
   }
  }
  return arr.length;
}

getIndexToIns([40, 60], 50);

```

**Comment by Bouncey** [comment]
@matteszk I understand what you are saying, and yes inserting a index 1 would also be correct. But this would require you to code your for-loop to look from right to left (higher index to lower index). 

Normal convention for looping through arrays would be starting from index 0 and increment.

Personally I don't see the value in initialising `i` to `arr.length` then decreasing the value of `i` in the for loop to iterate through the array from right to left.

If we allow for this edge case of going against convention, then we should possibly allow for sorting the array from highest to lowest as well.

Whilst a valid issue, I feel it is very much an edge case.

If I am missing your point, please correct me.

@FreeCodeCamp/issue-moderators

**Comment by Bouncey** [comment]
Closing as stale, if you have any more to add, feel free to open this issue again
