### ISSUE TITLE
Add "Reset all my progress" button to settings

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#10806]
One of the most popular requests I receive is to reset a camper's progress. Often they come back after a long hiatus and just want to start from scratch. Even though I explain to them that they can just complete the challenges again, most campers still want to reset it. 

![the settings page with the added button](https://www.evernote.com/l/Ar8i13sX7V5LJLAZKkZenbfzlf1_UA777wwB/image.png)

We should add this button to the "danger zone" section. It should trigger a warning modal similar to the "delete my account" action. Here's what the copy should say:

![the modal with the confirmation text written below](https://www.evernote.com/l/Ar8i13sX7V5LJLAZKkZenbfzlf1_UA777wwB/image.png)

You don't really want to reset your progress, do you?
This will really delete all of your progress and brownie points.
We won't be able to recover any of it for you later, even if you change your mind.
[ Nevermind, I don't want to delete all of my progress and brownie points ]
[ I am 100% sure I want to reset all of my progress and brownie points ]

**Comment by dhcodes** [comment]
I'm working on this. Will update if it's above my abilities.

**Comment by P1xt** [comment]
@dhcodes drat, I should have called dibs before I started. I just finished this one in my fork. I'll back out the commit and move to another.

**Comment by dhcodes** [comment]
@P1xt sorry friend. :(

**Comment by P1xt** [comment]
@dhcodes No worries mate, at least I now have a fully functioning dev environment :)
