### ISSUE TITLE
Proposal: Use YAML for challenge seeds

### ISSUE THREAD

**Issue by jboxman** [FreeCodeCamp/FreeCodeCamp#10801]
Proposal
--------

Transition fCC challenges into YAML.

Background
----------

By profession I am an accidental technical writer. I have lately spent some time reviewing the curriculum expansion tickets. My first impuse in doing so is to extend the narrative set forth in, for example, the initial React challenges and backfill any missing unit tests for these.

Because these currently exist only as comments in a thread, it is exceedingly difficult to work with each proposed challenge text and associated code without copying each of these into a text file. Moreover, upon inspection the JSON files that seed the challenges are technical writer's worst nightmare. Each description is segmented into an array of strings, coupled with escaped quotations and markup.

Wins
--------

 * YAML is easier to work with in an editor
 * YAML is highly amenible to a git workflow where multiple editors and reviewers can work on curriculum material concurrently
 * YAML offers a lower barrier for new contributors
 * YAML offers a lower barrier for new translators
 * YAML is a superset of JSON and thus a YAML parser understands valid JSON

Challenges
----------

 * fCC is tooled to work with the JSON seed files
 
Mitigations
-----------

YAML is a superset of JSON. It may be worth exploring whether new content in YAML can exist alongside existing content in JSON.

Feedback
--------

For a better idea of the what the content of each file may look like, I have included an identical challenge below in both JSON and YAML formats. What are contributors' thought on this?

Thank you for your consideration.

https://gist.github.com/jboxman/30e03c1fe9665a9c26bcb8c276a170af

**Comment by erictleung** [comment]
@jboxman thanks for your proposal. I can agree that it is arguably more human readable compared to JSON. However, I think such a change may take quite a bit of work to find all the places where it parses as JSON or some corner cases that we might not find out. IMO, I don't think there's much to gain from changing it accounting for the work needed to change it.

For the arguments on lowering the barrier to contribution, someone's developed a tool just for that [here](https://github.com/FreeCodeCamp/COM1000). Once you get it set up, you don't have to worry about escaping things, questioning if this looks right, or other formatting questions.

JSON can also be natively parsed using core JavaScript. And from what I understand, parsing YAML would require an external package, which would be another dependency to worry about.

cc/ @FreeCodeCamp/issue-moderators

**Comment by QuincyLarson** [comment]
@jboxman Thanks for this suggestion. I agree with what @erictleung said. I've worked with YAML before and its whitespace sensitivity is tedious. We may gain some things from switching to it, but I don't believe it would be worth the costs. 

Note that proposing a challenge can be done entirely in GitHub issues, and upon acceptance, someone who is experienced with bulk-entering the challenges (me or @HKuz) can do so for you. This is how we're handling the Curriculum Expansion effort and so far it's working smoothly. We've had dozens of people contribute new challenges with little need for any project-specific onboarding.
