### ISSUE TITLE
Don't refer to Bootstrap as Twitter Bootstrap

### ISSUE THREAD

**Issue by rtpHarry** [FreeCodeCamp/freecodecamp#1080]
It used to be it's name but it's not any more. It's in their brand guidelines to not refer to it as Twitter Bootstrap any more:

  - http://getbootstrap.com/about/#name

Lessons affected:

  - http://www.freecodecamp.com/challenges/waypoint-mobile-responsive-images

I flipped through all other lessons in the Bootstrap section and they don't appear to have any other Twitter Bootstrap mentions.

**Comment by NatashaHaggard** [comment]
Updated, opened a pull request - https://github.com/FreeCodeCamp/freecodecamp/pull/1102

**Comment by BerkeleyTrue** [comment]
Done. @NatashaHaggard If you add `closes #1080` where 1080 is the issue your PR address, when your PR is merged in github willl automatically close this issue as well. Again, thanks for your help!
