### ISSUE TITLE
My code changes between challenges

### ISSUE THREAD

**Issue by cxclucas** [FreeCodeCamp/FreeCodeCamp#10800]
Hi
Ive notice the code Ive wrote changes between challenges and at every challenge I must review the whole code as is not the same I submit in previous steps. Is this normal or a bug?

Challenge [Specify How Fonts Should Degrade](https://www.freecodecamp.com/challenges/specify-how-fonts-should-degrade#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by cxclucas** [comment]
Ive just notice that the code that follows me each step beyond I change it is the are the class at the P elements. I change those at every step and they keep having the class when we solve it by using the style element at the beginning.

**Comment by dhcodes** [comment]
@cxclucas It depends what you mean. The code editor is often pre-populated with code that structures the challenge. In those cases, you need only add code per the instructions. I'm not sure if you mean other code is following you or what.

**Comment by cxclucas** [comment]
Thanks @dhcodes 
I got it now. What happens is that the exercises makes you create a p element on style at the begginign of the code, and asks you to erase the class on the p elements.  You do that, and following challenges still have the class element I erased previously. Do I explain myself? Looks like an error

**Comment by erictleung** [comment]
@cxclucas the code from challenge to challenge doesn't directly carry over from one challenge to another. The challenges you are working on right now happen to be designed so that you are working with some core code keep on adding to it in the next challenge. 

The beginning code you see when you start a challenge is hard coded and we've changed it to reflect the changes you should have made in the previous challenge. Thus, small changes you make that don't affect the next challenge will seem to be "ignored" when in fact your changes don't actually get passed onto the next challenge. I hope that helps.
