### ISSUE TITLE
Change all usernames not associated with GitHub accounts back to fcc########

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#10803]
Campers often encounter a situation where their GitHub username is already in use, which throws an error that must be manually fixed by support. 

This is always due to them (or someone else) having their username set by a Twitter account username (which we did very early on and quickly discontinued). Now, usernames are only derived from GitHub account usernames.

We need to run a one-time database migration where we revert the usernames of all accounts not associated with a GitHub account back to fcc######### (where # is a hexadecimal value) so that they're unique.

**Comment by BerkeleyTrue** [comment]
This isn't actionable in this repo. Anyone creating a script for this would also need to access to a copy of production db.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue yes - you and I should write this script. Let's leave this issue open (and associated with this milestone) until we get the chance to do this.

**Comment by BerkeleyTrue** [comment]
Since it is not actionable here I'm moving it here. https://github.com/FreeCodeCamp/DevOps/issues/2

This repo issue tracker should only be for issues directly actionable on this repo.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue I grouped it with these others because it was part of the same milestone. As far as I know, you can't have milestones that span across repos.
