### ISSUE TITLE
Welcome view for new users

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#10804]
Whenever a user signs in and has 0 or 1 brownie points, we should redirect them to a special /welcome path. This path should contain the following text:

# Welcome to Free Code Camp! 
## You've created a brand new account. If you already had an account, sign out and try to log into it again with a different email address.

Do you want to go through our introduction?  This helps you join our chat rooms, forum, and local study groups. It only takes 10 minutes.

[ Yes, I want to join the community ] (links to '/')

[ No, I just want to code ]  (links to '/map')

We also want to write whether a camper skipped our onboarding as an attribute on their user object. So if they skip it, we would set "skippedOnboarding" to true, and if they chose to start it, we'd set it to false. This gives us valuable data about whether people who skip our onboarding ultimately come back to it, and whether people who say they want to complete it actually complete it.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue any idea what caused @VarCI-bot to think my issue wasn't a valid issue?

**Comment by erictleung** [comment]
@QuincyLarson probably because your issue contains the word `help` in it.

> ...introduction? This **help**s you join our chat...

VarCI Source: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/.varci.yml#L7

**Comment by QuincyLarson** [comment]
@erictleung OK - mystery solved. Thanks for linking to the code :)

**Comment by P1xt** [comment]
@QuincyLarson Is someone already working on these new tasks you added for this milestone? I'm booked tomorrow but I have some time Tuesday when I could bang a couple of them out. I just don't want to step on someone if they're already being worked.

**Comment by QuincyLarson** [comment]
@P1xt Awesome! We could definitely use your help! I can answer questions if you have any. I'll Gitter you my Skype information.

**Comment by P1xt** [comment]
@QuincyLarson Only one question: what branch of the repo should they be applied to?

**Comment by QuincyLarson** [comment]
@P1xt first we'll merge it into staging. From there, we can also merge it into backup/master, but we'll cross that bridge when we get there :)

**Comment by QuincyLarson** [comment]
@P1xt I went ahead and took a crack at this: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10873
