### ISSUE TITLE
Doubt related to CSS Class to style an element.

### ISSUE THREAD

**Issue by mannya89** [FreeCodeCamp/FreeCodeCamp#10813]
#### Browser Information

* Browser Name, Version: Google chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: laptop

#### Your Code
```html
<h2 class="red-text">CatPhotoApp</h2>
```
This code is not working in my system.

**Comment by texas2010** [comment]
@mannya89 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by mannya89** [comment]
Hi
I am student who is learning HTML for the first time . All I want to ask
you is I just copied the code given on the study material. In such a
situation to whom I should ask. So it means the code given on the website
is also wrong. Anyways thanks for ur reply.

**Comment by hardeesarmiento** [comment]
<style>
  .red-text{
    color: red;
  }
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by hardeesarmiento** [comment]
Im stuck here.can someone help me?

**Comment by texas2010** [comment]
@hardeesarmiento, Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.
GitHub Issues are for reporting bugs on the website only.

Happy Coding.
