### ISSUE TITLE
Add emoji support for GitHub-imported data

### ISSUE THREAD

**Issue by zdroid** [FreeCodeCamp/FreeCodeCamp#10817]
I've just noticed emojis are displayed as text and not as images — [example](https://www.freecodecamp.com/zdroid). Emojis are becoming very popular, especially on GitHub and I think they should be supported on a site which is partly supported by GitHub.

Is it possible to edit profile description at least, if emoji support can't or won't be implemented?

**Comment by atjonathan** [comment]
Yeah I defiantly think this should be added, saying as GitHub allows it 🎉 

cc/ @FreeCodeCamp/issue-moderators

**Comment by Greenheart** [comment]
This is a good idea, it would add much value to user profiles :)

**Comment by Bouncey** [comment]
Gets a :+1: from me

**Comment by dhcodes** [comment]
💯

**Comment by Em-Ant** [comment]
Totally agree :+1:
