### ISSUE TITLE
Valid data does not pass the test.

### ISSUE THREAD

**Issue by sjames1958gm** [FreeCodeCamp/FreeCodeCamp#10819]
Challenge [Modify Array Data With Indexes](https://www.freecodecamp.com/challenges/modify-array-data-with-indexes#?solution=%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0AourArray%5B1%5D%20%3D%203%3B%20%2F%2F%20ourArray%20now%20equals%20%5B1%2C3%2C3%5D.%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B1%2C2%2C3%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyArray%5B0%5D%20%3D%203%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourArray = [1,2,3];
ourArray[1] = 3; // ourArray now equals [1,3,3].

// Setup
var myArray = [1,2,3];

// Only change code below this line.
myArray [0] = 3;


```
While `myArray [0]` is valid js syntax this code doesn't pass the tests because the test for use of brackets doesn't allow that space.

recommend /myArray\s+\[0\]\s+=.*/ as a better test that allows for the space but still doesn't allow for the reassignment of the array

**Comment by Bouncey** [comment]
@sjames1958gm Thanks for contributing!

This is for first-timers only.

Edit [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/549cfc305f75d8c6036a3cde65c47b518607b18c/seed/challenges/01-front-end-development-certification/basic-javascript.json#L1936) to allow for as many spaces as required between `myArray` and `[0]`.

**Comment by l-tong** [comment]
I will give it a try on fixing it as a first-timer.

**Comment by erictleung** [comment]
@Bouncey although this is "valid" JS, I don't see arrays being accessed like that with a space. I can't find the conversation we had about this on another challenge but I think we all agreed that we should enforce no spaces. If we change it for this one, we'll have to change it for all the other ones.

**Comment by Bouncey** [comment]
Ok, if that's what we agreed then no problem, we can close this issue.

**Comment by l-tong** [comment]
I agree with Eric on enforcing best practices on coding style since someone might think it is fun to have var myArray    [0]  = 1;  And this might become a bad habit on real world coding.

**Comment by sjames1958gm** [comment]
Since there is no indication what the error might be and no instruction or style guide saying no space is best practice, campers are going to get stumped on what the valid solution is, esp. if they go to get help and the people helping don't have any indication that this is a "best" practices issue.

**Comment by erictleung** [comment]
@sjames1958gm thanks for the feedback. What we can do is have a note in the lesson/challenge that explores [accessing array data with indexes](https://www.freecodecamp.com/challenges/access-array-data-with-indexes) and mention that there shouldn't be any spaces between the array name and the square brackets. 

Maybe add something like this to the end of the description and before the instructions.

> **Note**
> There shouldn't be any spaces between the array name and the square brackets, like `array [0]`. Although JavaScript is able to process this correctly, this may confuse other programmers reading your code.

**Comment by karuppiah7890** [comment]
I changed the "description" property (whose value is a string array) in [this file](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/backup/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json) which starts at line 1859. But the changes I made are not visible in the site, even if I restart the server. I am accessing the server at http://localhost:3001 . So, what am I doing wrong ? Can anyone help me ?

**Comment by karuppiah7890** [comment]
OK. Somehow I guessed that I have to run the 

`npm run only-once`

command again, even though it says "only-once". And the output said some files were parsed. The file names were related to the names of the JSON files in the seed/challenges/ folder. 

Is it like the JSON files are parsed and put in the mongo server ? And the site shows the data of the challenges from the server ?
