### ISSUE TITLE
Adding `</` to the end of the document breaks the testSuite list

### ISSUE THREAD

**Issue by rtpHarry** [FreeCodeCamp/FreeCodeCamp#1081]
I tested this out in several lessons and in several different places.

Most of the time if you type `</` it doesn't have any affect on the list of tasks down the left hand side.

If you put it at the end of the html editor then it breaks the `testSuite` sidebar.

Tested it on 15 randomly selected waypoint lessons and seems to affect all pages.

**Comment by benschenker** [comment]
Thanks @rtpHarry,  I was able to replicate this on http://freecodecamp.com/challenges/waypoint-label-bootstrap-wells

However, I'm not sure why you would need to put `</` at the end of a document, plus closing that end tag like `</>` makes the testSuite reappear.  I'll leave this open for now.

**Comment by BerkeleyTrue** [comment]
This is expected. The incorrect tag cannot be translated by the browser, so it does not render and therefore the test suite returns bad data. This results in the tests not displaying.

**Comment by benschenker** [comment]
Is there any way to detect this and give an error to the user?

**Comment by awesomeaniruddh** [comment]
@benschenker Now that the editor is not real time anymore, I don't see this being an issue: there is no reason the user would type that specific code and run the test. I can see this being an issue when the tests disappear as the user is typing HTML.

**Comment by BerkeleyTrue** [comment]
@awesomeaniruddh Is correct, we can close this now as it has shifted to user error now that a user must manual test.

Happy Coding!
