### ISSUE TITLE
global vs local scope in functions

### ISSUE THREAD

**Issue by robertkub** [FreeCodeCamp/FreeCodeCamp#10812]
Challenge [Global vs Local Scope in Functions](https://www.freecodecamp.com/challenges/global-vs-local-scope-in-functions#?solution=%0A%2F%2F%20Setup%0Avar%20outerWear%20%3D%20%22T-Shirt%22%3B%0A%0Afunction%20myOutfit()%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20outerWear%3B%0A%7D%0A%0AmyOutfit()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var outerWear = "T-Shirt";

function myOutfit() {
  // Only change code below this line
  
  var myOutfit = "Sweater";
  
  // Only change code above this line
  return outerWear;
}

myOutfit();

```

**Comment by robertkub** [comment]
I cannot get passed this

the global var is always taking priority

**Comment by texas2010** [comment]
@robertkub 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding..

**Comment by tokasravi9000** [comment]
// Setup
var outerWear = "T-Shirt";

function myOutfit() {
  // Only change code below this line
  var myOutfit = "sweater";
  var outerWear = myOutfit;
  
  // Only change code above this line
  return outerWear;
}

myOutfit();
