### ISSUE TITLE
the code are right with the direction, but don't get the result

### ISSUE THREAD

**Issue by voeung** [FreeCodeCamp/FreeCodeCamp#10821]
What are wrong with my code?

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```html
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6 well">

    </div>
    <div class="col-xs-6 well">

    </div>
  </div>
</div>
```

**Comment by texas2010** [comment]
@voeung, what challenge name?

**Comment by erictleung** [comment]
@voeung thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
