### ISSUE TITLE
HelloWorld

### ISSUE THREAD

**Issue by SchopenhauerZhang** [FreeCodeCamp/FreeCodeCamp#10825]
Challenge [Build a Tribute Page](https://www.freecodecamp.com/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by SchopenhauerZhang** [comment]
hello world  for test!

**Comment by texas2010** [comment]
@SchopenhauerZhang, Do you have a issue on freecodecamp?

**Comment by SchopenhauerZhang** [comment]
the codepen  said email is taken ,but i dont get it,so i cannt  sign up?but it say  i dont have account!

**Comment by texas2010** [comment]
@SchopenhauerZhang, oh ok. your codepen issue is nothing with this freecodecamp repo. sorry.

Happy Coding.

by the way, you could recover your password. maybe you forget about you did sign up on codepen.
