### ISSUE TITLE
Waypoint: Style Text Inputs as Form Controls Testsuite Markup Error

### ISSUE THREAD

**Issue by rtpHarry** [FreeCodeCamp/FreeCodeCamp#1082]
Lesson at http://www.freecodecamp.com/challenges/waypoint-style-text-inputs-as-form-controls

Test item 3 has incorrect markup in it:

    Give the text <code>input<code> in your form the class "form-control".</code></code>

Resulting in display errors:

![image](https://cloud.githubusercontent.com/assets/1038062/8305717/c3129752-19a9-11e5-88de-137b3016baa0.png)

**Comment by krisgesling** [comment]
Seems this has been reported a few times - bug #'s 1383, 1328, 1281, 1082
Looks like QuincyLarson fixed this on 20 June, so I'm assuming it just hasn't yet been pushed out.
