### ISSUE TITLE
Does not validate with correct code entered.

### ISSUE THREAD

**Issue by simplyd66** [FreeCodeCamp/FreeCodeCamp#10828]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```html
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
   .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by simplyd66** [comment]
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
   .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by simplyd66** [comment]
Challenge is size you Images

**Comment by Bouncey** [comment]
@simplyd66 There is an issue with your code.

Please review the instructions for the challenge you are having issues with. 

If you are still stuck, please click on the `Help` button underneath to challenge instructions, and you will be directed to a dedicated chat room for code help.

Happy codings!

**Comment by ozwald71** [comment]
You need to give the <img> a class

**Comment by texas2010** [comment]
@simplyd66 
Thanks for reporting this. I checked your code But your code is incorrect. 
GitHub Issues are for reporting bugs on the website only
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding..
