### ISSUE TITLE
Smallest Common Multiple

### ISSUE THREAD

**Issue by CostasDev** [FreeCodeCamp/FreeCodeCamp#10826]
#### Challenge Name
Smallest Common Multiple

#### Issue Description
// noprotect -- >> Only with that line is working...

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code
```js
// noprotect

function smallestCommons(arr) {
  
  var tableTwoDimension = [] ;
  
  var minNum = Math.min(arr[0],arr[1]);
  var maxNum = Math.max(arr[0],arr[1]);
  
  var isLooping = true;
  var pos = maxNum;
  
  while(isLooping){
    
    var isWorking = false;
    
    for(var i=minNum;i<=maxNum;i++){
      
       if(pos%i === 0)
         isWorking = true;
        else {
          isWorking = false;
          break;
        }
    }
        
   if(isWorking)
    break;
    else pos++;
        
  }
    
  return pos;

}
smallestCommons([23,18]);
 
```

**Comment by dhcodes** [comment]
@CostasDev I'm not sure this is a bug. I'd consider it more of a feature of the code editor. It does its best to prevent infinite loops by preventing the callstack from being overloaded. I think since it notifies you of how to override it, it's fine as-is.

**Comment by CostasDev** [comment]
hi @dhcodes  but the question is correct only if i add the first line, otherwise is incorrect

**Comment by dhcodes** [comment]
@CostasDev I don't think it's incorrect without that line; it's just that the tests don't run without that line to protect users from a possible infinite loop browser crash if they didn't break the while loop eventually.

**Comment by Bouncey** [comment]
@CostasDev @dhcodes IIRC the loop-protect library has always been cautious about `while` loops.

As @dhcodes says, it's not that there is an issue with your code, or with the challenge, it's more to do with a cautious approach towards protecting you and your browser from infinite loops.

This is something that the developers of loop-protect recognised and have added the ability to disable loop protection with `// no-protect`, all be it at your own risk.

**Comment by CostasDev** [comment]
ok thank you very much guys for your response !!

**Comment by dhcodes** [comment]
Closing this for now. @CostasDev please reopen if you have more to discuss.
