### ISSUE TITLE
Increment bug

### ISSUE THREAD

**Issue by markymarc009** [FreeCodeCamp/FreeCodeCamp#10835]
Challenge [Counting Cards](https://www.freecodecamp.com/challenges/counting-cards#?solution=%0Avar%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0Aswitch%20(card)%20%7B%0A%20%20case%202%3A%0A%20%20case%203%3A%0A%20%20case%204%3A%0A%20%20case%205%3A%0A%20%20case%206%3A%0A%20%20%20%20count%20%3D%20count%2B%3D1%3B%0A%20%20%20break%3B%20%0A%20%20%20%0A%20%20%20%20%0A%20%20case%207%3A%0A%20%20case%208%3A%0A%20%20case%209%3A%20%0A%20%20%20count%20%3D%20count%20%2B%200%3B%0Abreak%3B%0A%20%20%20%20%0A%20%20case%2010%3A%0A%20%20case%20'J'%3A%0A%20%20%20%20case'Q'%3A%0A%20%20%20%20case'K'%3A%0A%20%20%20%20case'A'%3A%0A%20%20%20%20count%20%3D%20count-%3D1%3B%0A%20%20%20%20break%3B%0A%7D%0A%20%20%20%20%20%0Aif%20(count%20%3C%3D%200)%0A%20%20%7B%20%0A%20%20return%20count%20%2B%20%22%20Hold%22%3B%0A%20%20%7D%0A%20%20%20%0A%20%20%20%20%20%20%0A%20%20%20%20else%20if%20(count%20%3E%200)%20%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%20return%20count%20%2B%20%22%20Bet%22%3B%20%0A%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%0A%20%20%0A%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(2)%3B%20cc(3)%3B%20cc(10)%3B%20cc(5)%3B%20cc(6)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
/*For the sake of not giving away the answer, which I was able to find, I will only include the snippet that shows issue.

For the part of the Card Counting Challenge where we need to make the card increment or decrement, the compiler will only accept "count = count+=1;" The compiler seems to have an issue trying to pass "count = count++;" 

This bug will cause campers time and frustration until they finally decide to make that little tweak to their code. */

**Comment by markymarc009** [comment]
Same goes for decrementing.

**Comment by Bouncey** [comment]
Please follow the issue report template instructions. This helps by gathering the data required for us to reproduce the issue, without which we would only be guessing. 

The solutions to the challenges are in the repo and in the forum, so please don't worry about giving the game away.

**Comment by dhcodes** [comment]
@markymarc009 While `count = count++` does seem to be acceptable code (per the console of my browser) I'm not sure it's a recommended practice as `count++` is self-assigning. In this case, `count++` works and is the preferred way to write the increment as `count=count++` has an unnecessary assignment. Likewise, `count+=1` is self-assigning so the assignment in `count = count+=1` is unnecessary (though this does pass the tests in this challenge).

**Comment by erictleung** [comment]
@markymarc009 the incrementing is incorrect.

```js
var count = 4;
// undefined
count++; // This is the correct way to increment using the `++`
// 4
count;
// 5
count = count++; // Incorrect way to increment
// 5
count
// 5
```

This `count = count+=1;` will only work because it does actually increment the `count`, albeit not the best way to. You should increment using `count++`.

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
