### ISSUE TITLE
Help on Change font size of an element stage please

### ISSUE THREAD

**Issue by Aenean** [FreeCodeCamp/FreeCodeCamp#10838]
My code:
```html

<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Kitty ipsum dolor</p>
```
It says, "Your p element should contain the first few words of the provided additional kitty ipsum text." but it does not accept whatever i type there..

**Comment by texas2010** [comment]
@Aenean 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding..

**Comment by Aenean** [comment]
I tried chat but did not get any answer, could you tell me what is incorrect in this code?

**Comment by kbeni** [comment]
your second <p> is wrong it should contain text :
Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.

**Comment by DesignerDude24** [comment]
The instructions specifically state: "Your p element should contain the first few words of the provided additional kitty ipsum text".

Where did you read it should contain "Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched".  That's  a lot more than a "few" words.  Also, to the person stating the OP's code was wrong.  It wasn't wrong.  The code is correct, the exact words in the paragraph tag were wrong, as pointed out by kbeni.

This is the same problem as other web-based code-learning sites.  The verification process is not flexible enough to process actual correct or incorrect coding.

**Comment by joshuaboulton** [comment]
I had the same problem. Kbeni's answer did fix the problem, but I have no idea where you got this text from. Is there meant to be some link here to some additional Kitty Ipsum text? That text is nowhere to be found on my screen.
