### ISSUE TITLE
Learn button points to last lesson visited not most advanced lesson completed

### ISSUE THREAD

**Issue by rtpHarry** [FreeCodeCamp/freecodecamp#1083]
1. Visit the map page
  2. Click on an older, already completed lesson
  3. Visit anywhere else in the site that isn't a lesson
  4. Click the learn button

You are taken to the old lesson not your most recent progress.

**Comment by terakilobyte** [comment]
This is by design. Whatever challenge you navigate to will become your most recent challenge.
