### ISSUE TITLE
Profile page reserves my own username / can't change case of your own username

### ISSUE THREAD

**Issue by rtpHarry** [FreeCodeCamp/freecodecamp#1084]
I noticed my username is `rtpharry` not `rtpHarry`.

If I visit the [account page](http://www.freecodecamp.com/account) and try to change it from `rtpharry` to `rtpHarry` the system thinks that username is already in use:

![image](https://cloud.githubusercontent.com/assets/1038062/8305945/96573540-19ab-11e5-84bb-9e4b4ed840b7.png)

Testing the url http://www.freecodecamp.com/rtpHarry serves up my profile page so it seems that it checks them case-insensitive (which is good) but doesn't check if its already owned by the current user.

**Comment by ahstro** [comment]
I'm not 100% sure, but from what I can gather of the source code, the usernames seem to be stored in lower-case.
If I recall correctly, the first username I registered was "LumenTeun", but on my profile it said "lumenteun", so I guess that strengthens my hypothesis as well.

**Comment by BerkeleyTrue** [comment]
Hello @rtpHarry 

usernames are stored and searched lowercased.

Happy Coding!

**Comment by Yerucham100** [comment]
hi
