### ISSUE TITLE
"override" in the description should not be formatted as code

### ISSUE THREAD

**Issue by zuphilip** [FreeCodeCamp/FreeCodeCamp#10844]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has a a small nit in the description:

While all code is formatted special, there is no need to this with the verb "override", i.e. I suggest to change

 * Will our class `override` the `body` element's `color: green;` CSS property?

into

 * Will our class <em>override</em> the `body` element's `color: green;` CSS property?

What do you think?

**Comment by Bouncey** [comment]
I agree that consistency is best.

First-timers:

On [this](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/c0d41e1e4451f09862f87b44b6c32cf326c4c717/seed/challenges/01-front-end-development-certification/html5-and-css.json#L4307) line, change the `<code></code>` tags for `<em></em>` tags.

Follow the [contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) guidelines to get started.

If you need help, reach out to the [Contribbutors Chat Room](https://gitter.im/FreeCodeCamp/Contributors) on gitter.

Happy coding and thanks for contributing :tada:

**Comment by codetweetie** [comment]
Hello everyone,
I would like to work on this issue and I'm a first timer too.

**Comment by codetweetie** [comment]
Hi @Bouncey 
I was wondering if I need to make the same change for other translations as well ?

**Comment by Bouncey** [comment]
@codetweetie it would be great if you could :+1:

**Comment by codetweetie** [comment]
Ok, I think I can.

**Comment by alexanderholman** [comment]
I hope I haven't stepped on anyones toes! I submitted a pull request as @codetweetie hadn't yet (as far as I can tell) and the last comment was 7 hours ago

**Comment by codetweetie** [comment]
@Bouncey @zuphilip Hi, I've submitted another PR, hopefully this time my PR looks ok. I'll be glad if you can let me know your comments on the PR so it'll help me to improve my future contributions. Thanks a mil in advance.

**Comment by codetweetie** [comment]
@Bouncey Thanks a mil for helping me to kick start my very first open source contribution, feeling proud of it!!
