### ISSUE TITLE
what's wrong with this? Anybody can help?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [FreeCodeCamp/FreeCodeCamp#10849]
Challenge [Convert JSON Data to HTML](https://www.freecodecamp.com/challenges/convert-json-data-to-html#?solution=%0A%0A%0A%0Afccss%0A%20%20%24(document).ready(function()%20%7B%0A%0A%20%20%20%20%24(%22%23getMessage%22).on(%22click%22%2C%20function()%20%7B%0A%E2%80%89%E2%80%89%20%20%20%20%24.getJSON(%22%2Fjson%2Fcats.json%22%2C%20function(json)%20%7B%0A%20%20%20%20%20%20%20var%20html%20%3D%20%22%22%3B%0A%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%20%20%20%20%20%20json.forEach(function(val)%20%7B%0A%09%09%20%20%20%20var%20keys%20%3D%20Object.keys(val)%3B%0A%09%09%20%20%20%20html%20%2B%3D%20%22%3Cdiv%20class%20%3D%20'cat'%3E%22%3B%0A%09%09%20%20%20%20keys.forEach(function(key)%20%7B%0A%09%09%20%20%20%20%20%20%20%20html%20%2B%3D%20%22%3Cstrong%3E%22%20%2B%20key%20%2B%20%22%3C%2Fstrong%3E%3A%20%22%20%2B%20val%5Bkey%5D%20%2B%20%22%3Cbr%3E%22%3B%0A%09%09%20%20%20%20%7D)%3B%0A%09%09%20%20%20%20html%20%2B%3D%20%22%3C%2Fdiv%3E%3Cbr%3E%22%3B%0A%09%09%7D)%3B%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%E2%80%89%E2%80%89%E2%80%89%E2%80%89%20%20%20%20%24(%22.message%22).html(html)%3B%0A%E2%80%89%E2%80%89%20%20%20%20%7D)%3B%0A%20%20%20%20%7D)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Ch2%3ECat%20Photo%20Finder%3C%2Fh2%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%20well%20message%22%3E%0A%20%20%20%20%20%20The%20message%20will%20go%20here%0A%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%22%3E%0A%20%20%20%20%20%20%3Cbutton%20id%20%3D%20%22getMessage%22%20class%20%3D%20%22btn%20btn-primary%22%3E%0A%20%20%20%20%20%20%20%20Get%20Message%0A%20%20%20%20%20%20%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html




<script>
  $(document).ready(function() {

    $("#getMessage").on("click", function() {
      $.getJSON("/json/cats.json", function(json) {
       var html = "";
        // Only change code below this line.
        json.forEach(function(val) {
		    var keys = Object.keys(val);
		    html += "<div class = 'cat'>";
		    keys.forEach(function(key) {
		        html += "<strong>" + key + "</strong>: " + val[key] + "<br>";
		    });
		    html += "</div><br>";
		});        
        // Only change code above this line.
        $(".message").html(html);
      });
    });
  });
</script>



<div class="container-fluid">
  <div class = "row text-center">
    <h2>Cat Photo Finder</h2>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12 well message">
      The message will go here
   </div>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12">
      <button id = "getMessage" class = "btn btn-primary">
        Get Message
      </button>
    </div>
  </div>
</div>

```
![jquery-no-error](https://cloud.githubusercontent.com/assets/18028768/18746370/8e75957c-80f9-11e6-912e-927f2d22f85a.PNG)
this is OK, what's wrong with this!
![jquery-error](https://cloud.githubusercontent.com/assets/18028768/18746385/a7bced46-80f9-11e6-96c6-18de89a8c294.PNG)

**Comment by xgqfrms-GitHub** [comment]
json.forEach is not a function ???
![jquery-error-json](https://cloud.githubusercontent.com/assets/18028768/18746438/f7f0dec6-80f9-11e6-84c8-e908733e2da1.PNG)
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="./libs/bootstrap.min.css">
	<!--<script src="./libs/jquery-3.1.0.min.js"></script>-->
</head>
<body>
	<div>
		<div class="container-fluid">
		  <div class = "row text-center">
		    <h2>Cat Photo Finder</h2>
		  </div>
		  <div class = "row text-center">
		    <div class = "col-xs-12 well message">
		      The message will go here
		   </div>
		  </div>
		  <div class = "row text-center">
		    <div class = "col-xs-12">
		      <button id = "getMessage" class = "btn btn-primary">
		        Get Message
		      </button>
		    </div>
		  </div>
		</div>
	</div>
<script src="./libs/jquery-3.1.0.js"></script>
<!---->
<script>
	// var $ = jQuery().noConflict();
	$(document).ready(function() {
		$("#getMessage").on("click", function() {
			$.getJSON("./json/cats.json", function(json) {
				var html = "";
				// Only change code below this line.
				json.forEach(function(val) {
					var keys = Object.keys(val);
					html += "<div class = 'cat'>";
					keys.forEach(function(key) {
						html += "<strong>" + key + "</strong>: " + val[key] + "<br>";
						//
					});
					html += "</div><br>";
				});
				// Only change code above this line.
				$(".message").html(html);
			});
		});
	});
</script>
</body>
</html>
```

**Comment by Bouncey** [comment]
@xgqfrms-GitHub I cannot recreate your issue inside of the freeCodeCamp editor using your code. I can see from your first screenshot that you have the data rendered on the mobile screen, so I imagine you have passed the challenge on freeCodeCamp.

And obviously we cannot provide support outside of this.

One issue you will have is the `$.getJSON` request points to a file held on freeCodeCamp servers, and is not accessible by third party sites, e.g. your github hosted page.

If you have passed this challenge on freeCodeCamp, please close this issue.

**Comment by xgqfrms-GitHub** [comment]
Ok!
