### ISSUE TITLE
Completing this challenge without changing return value

### ISSUE THREAD

**Issue by Agonn** [FreeCodeCamp/FreeCodeCamp#10845]
Challenge [Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%0A%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20var%20lookup%20%3D%20%7B%0A%20%20%20%20%20alpha%3A%22Adams%22%2C%0A%20%20%20%20%20bravo%3A%22Boston%22%2C%0A%20%20%20%20%20charlie%3A%20%22Chicago%22%2C%20%20%0A%20%20%20%20%20delta%3A%22Denver%22%2C%0A%20%20%20%20%20echo%3A%20%22Easy%22%2C%0A%20%20%20%20%20foxtrot%3A%20%22Frank%22%0A%20%7D%3B%0A%20%20%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20lookup%5Bval%5D%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22foxtrot%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
 var lookup = {
     alpha:"Adams",
     bravo:"Boston",
     charlie: "Chicago",  
     delta:"Denver",
     echo: "Easy",
     foxtrot: "Frank"
 };
  

  // Only change code above this line
  return lookup[val];
}

// Change this value to test
phoneticLookup("foxtrot");

```

How do you complete this without changing the return value to `lookup[val] ` ?

**Comment by Bouncey** [comment]
@Agonn the instructions are provided I feel are clear enough. Please read them again, if you are still having issues, click on the `Help` button in the challenge you are stuck on and you will be directed to a dedicated code help chat room.

GitHub issues are for reporting issues with freeCodeCamp and it's code base, not for help with challenges.

Like in this challenge, there is no test to check that `return answer;` hasn't been changed, which is a valid issue.

I will raise an issue to address this.

Thanks for contributing :tada:
