### ISSUE TITLE
beginner problem 

### ISSUE THREAD

**Issue by oswynl13l** [FreeCodeCamp/FreeCodeCamp#10843]
I cant run tests on my first challenge

**Comment by Bouncey** [comment]
@oswynl13l Please follow the issue report template instructions. This helps by gathering the data required for us to reproduce the issue, without which we would only be guessing.

Have you tried pressing the `Run Tests (ctrl + enter)` button?

**Comment by oswynl13l** [comment]
Yup , bt there is no progress in the page , i click run test , bt the page
just goes on reloading , tell me wht should i type, it says type
hello world in the h1 space , bt it doesnt run

**Comment by Bouncey** [comment]
@oswynl13l can you post the code you have for the challenge you are having issues with please

**Comment by texas2010** [comment]
@oswynl13l, which challenge you are on? 
Please post your code on here. thanks

**Comment by oswynl13l** [comment]
<h1>Hello</h1>
It says replace the h1 elemet by hello world
So o doing tht i cant get progress on the page its kinda hanged, wht should
i exactly type , nd where , plz help

**Comment by Bouncey** [comment]
Change <h1>Hello</h1> to <h1>Hello World</h1> and press the 'Run tests' button. 

This should give you an idea as to how the challenges work. 

If we are asking you to do something, it is to be done in the black area on screen, this is called the code editor. 

Hope this helps, happy coding :tada:

**Comment by Bouncey** [comment]
@oswynl13l can this issue now be closed?

**Comment by oswynl13l** [comment]
Yeah
