### ISSUE TITLE
Arguments Optional: Test case results are not being accepted

### ISSUE THREAD

**Issue by jeffrath504** [FreeCodeCamp/FreeCodeCamp#10855]
Challenge [Arguments Optional](https://www.freecodecamp.com/challenges/arguments-optional#?solution=%0Afunction%20addTogether()%20%7B%0A%20%20var%20holdNumber%3D0%3B%0A%0A%20%20%0A%20%20if%20(arguments.length%20%3D%3D%201)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20if%20(typeof%20arguments%5B0%5D%20!%3D%20%22number%22)%7B%0A%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20holdNumber%20%3D%20arguments%5B0%5D%3B%20%20%0A%20%20%20%20%20%20return%20function(a)%7B%20%0A%20%20%20%20%20%20var%20temp%20%3D%20holdNumber%20%2B%20a%3B%0A%20%20%20%20%20%20return%20temp%3B%7D%3B%0A%20%20%20%20%7D%0A%20%20%0A%20%20if%20(arguments.length%20%3D%3D2)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20if%20(typeof%20arguments%5B0%5D%20!%3D%20%22number%22)%7B%0A%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20if%20(typeof%20arguments%5B1%5D%20!%3D%20%22number%22)%7B%0A%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20return%20arguments%5B0%5D%20%2B%20arguments%5B1%5D%3B%0A%20%20%20%20%7D%0A%20%20return%20false%3B%0A%7D%0A%0A%0Afunction%20addTogether()%20%7B%0A%20%20var%20holdNumber%3D0%3B%0A%0A%20%20%0A%20%20if%20(arguments.length%20%3D%3D%201)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20if%20(typeof%20arguments%5B0%5D%20!%3D%20%22number%22)%7B%0A%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20holdNumber%20%3D%20arguments%5B0%5D%3B%20%20%0A%20%20%20%20%20%20return%20function(a)%7B%20%0A%20%20%20%20%20%20var%20temp%20%3D%20holdNumber%20%2B%20a%3B%0A%20%20%20%20%20%20return%20temp%3B%7D%3B%0A%20%20%20%20%7D%0A%20%20%0A%20%20if%20(arguments.length%20%3D%3D2)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20if%20(typeof%20arguments%5B0%5D%20!%3D%20%22number%22)%7B%0A%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20if%20(typeof%20arguments%5B1%5D%20!%3D%20%22number%22)%7B%0A%20%20%20%20%20%20%20return%20undefined%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20return%20arguments%5B0%5D%20%2B%20arguments%5B1%5D%3B%0A%20%20%20%20%7D%0A%20%20return%20undefined%3B%0A%7D%0A%0Aconsole.log(%22***1%22%20%2B%20addTogether(2%2C%5B3%5D))%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Test case:addTogether(2,[3] should return undefined.  Validating the return result in the console log verified that undefined was  being returned, but the  answer was not being accepted.

My code:
```javascript

function addTogether() {
  var holdNumber=0;

  
  if (arguments.length == 1)
    {
      if (typeof arguments[0] != "number"){
      return undefined;
      }
     holdNumber = arguments[0];  
      return function(a){ 
      var temp = holdNumber + a;
      return temp;};
    }
  
  if (arguments.length ==2)
    {
      if (typeof arguments[0] != "number"){
      return undefined;
        }
     if (typeof arguments[1] != "number"){
      return undefined;
        }
      
      return arguments[0] + arguments[1];
    }
  return false;
}


function addTogether() {
  var holdNumber=0;

  
  if (arguments.length == 1)
    {
      if (typeof arguments[0] != "number"){
      return undefined;
      }
     holdNumber = arguments[0];  
      return function(a){ 
      var temp = holdNumber + a;
      return temp;};
    }
  
  if (arguments.length ==2)
    {
      if (typeof arguments[0] != "number"){
      return undefined;
        }
     if (typeof arguments[1] != "number"){
       return undefined;
        }
      
      return arguments[0] + arguments[1];
    }
  return undefined;
}

console.log("***1" + addTogether(2,[3]));


```

**Comment by erictleung** [comment]
@jeffrath504 the output I get from your code running `addTogether(2)([3])` is `"23"`, not `undefined`.

Take a look at your line with `var temp = holdNumber + a;`

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by BleedingEnergy** [comment]
Hi together,

i have the same problem. My useragent is: 

Here is my code:

`

function addTogether() { 
  if(typeof arguments[0] === "number"){
    switch(arguments.length){
      case 1:
       var x = arguments[0];
       return function(y){
         return x + y;
       };
      case 2:
       if(typeof arguments[1] === "number"){       
          return arguments[0] + arguments[1];
       }
       else {
         return undefined;}   //if I insert "undefined" instead of undefined here, it shows the string as return
    }
  }
  else {
    return undefined;
  }
}

addTogether(2, [3]);
`

**Comment by shapir** [comment]
BleedingEnergy - any resolution for the above?
