### ISSUE TITLE
[beta] 500 TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by ivantedja** [FreeCodeCamp/FreeCodeCamp#10859]
Steps to reproduce:
- You need to be logged in
- Open new tab / window in your browser
- Visit homepage

You will see: `500 TypeError: Cannot read property 'indexOf' of undefined`

See snippets below:

```
// server/boot/home.js
// ...
module.exports = function(app) {
  // ...
  function index(req, res, next) {
    // ...
    const referer = req.headers.referer;
  
    if (req.user) {
      if ((referer.indexOf('/settings') >= 1) && (req.user.isGithubCool)) {
        // ...
      }
      // ...
    }
    // ...
  }
  // ...
}

```

`referer` header is not always exist so it's better to add conditional to check that

**Comment by dhcodes** [comment]
I have this issue when running the beta locally as well. I thought it was something I had done wrong on my install. Glad to know it can be fixed 👍

**Comment by ivantedja** [comment]
@dhcodes frankly, I thought the same thing! 😄
