### ISSUE TITLE
Doesn't see my element as being blue

### ISSUE THREAD

**Issue by razvanrujoiu** [FreeCodeCamp/FreeCodeCamp#10856]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3Ablue%3B%7D%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3C%2Fstyle%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {color:blue;}
<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
</style>
```

**Comment by Bouncey** [comment]
@razvanrujoiu There is an issue with your code.

Please review the instructions for the challenge you are having issues with.

If you are still stuck, please click on the Help button underneath to challenge instructions, and you will be directed to a dedicated chat room for code help.

If I have misunderstood your issue, please provide more information and open this issue again.

GitHub issues are for issues with freecodecamp itself, not for challenge help.

Happy codings!

**Comment by DTCopp** [comment]
I have the same problem - the code looks good but it is not recognized as "blue."

**Comment by Bouncey** [comment]
@DTCopp can you please provide the code you are having issues with. 

Have you tried seeking help in the [HelpFrontEnd](https://gitter.im/FreeCodeCamp/HelpFrontEnd) chat room?

**Comment by AlexArcanum** [comment]
You cannot stylize the <p> or <h2> like that. The paragraph should not be nested inside <style>

**Comment by djsirena** [comment]
I'm also having that problem.   
style>
  h2 {color: blue;} CatPhotoApp
</style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
