### ISSUE TITLE
Entering correct tested code but wrong output in this question.

### ISSUE THREAD

**Issue by faizal-saleem** [FreeCodeCamp/FreeCodeCamp#10852]
#### Search and Replace
https://www.freecodecamp.com/challenges/search-and-replace#?solution=%0Afunction%20myReplace(str%2C%20before%2C%20after)%20%7B%0A%20%20return%20str%3B%0A%7D%0A%0AmyReplace(%22A%20quick%20brown%20fox%20jumped%20over%20the%20lazy%20dog%22%2C%20%22jumped%22%2C%20%22leaped%22)%3B%0A

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

`
function replace(str, before, after) {
  var ind = str.indexOf(before);
  if (str[ind] === str[ind].toUpperCase()) {
   after = after.charAt(0).toUpperCase();
  }
  
  str = str.replace(before, after);

  return str;
}

myReplace("A quick brown fox Jumped over the lazy dog", "Jumped", "Leaped");
``js
 
 
 
```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by Bouncey** [comment]
@faizal-saleem There is an issue with your code.

Please review the instructions for the challenge you are having issues with.

If you are still stuck, please click on the Help button underneath to challenge instructions, and you will be directed to a dedicated chat room for code help.

If I have misunderstood your issue, please provide more information and open this issue again.

Happy codings!

**Comment by annunirmal** [comment]
you are suppose to add after.slice(1) in your code which is as folows:
function myReplace(str, before, after) {
  var ind = str.indexOf(before);
  if (str[ind] === str[ind].toUpperCase()) {
   after = after.charAt(0).toUpperCase() + after.slice(1);
  }

  str = str.replace(before, after);

  return str;
 }

**Comment by texas2010** [comment]
@annunirmal Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
