### ISSUE TITLE
No automatic scrolling

### ISSUE THREAD

**Issue by ssanduli** [FreeCodeCamp/FreeCodeCamp#10862]
Not sure if it is a bug. Sometimes you type something and the cursor is out of the screen. You don't see what you type unless you scroll down to the very bottom of the code input section. It would be great if you make it scroll down automatically when you type

**Comment by dhcodes** [comment]
@ssanduli This works correctly on my end. Do you have an example or challenge where I can try to replicate this?

**Comment by dhcodes** [comment]
Closing as stale.
