### ISSUE TITLE
Concatenating Strings with the Plus Equals Operator

### ISSUE THREAD

**Issue by Tess2016** [FreeCodeCamp/FreeCodeCamp#10861]
Challenge [Concatenating Strings with the Plus Equals Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-the-plus-equals-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%3B%0AourStr%20%2B%3D%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20myStr%20%3D%20%22This%20is%20the%20first%20sentence.%22%3B%0AmyStr%20%2B%3D%20%22This%20is%20the%20second%20sentence.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line
var myStr = "This is the first sentence.";
myStr += "This is the second sentence.";



```

**Comment by Bouncey** [comment]
@Tess2016 There is an issue with your code.

Please review the instructions for the challenge you are having issues with.

If you are still stuck, please click on the Help button underneath to challenge instructions, and you will be directed to a dedicated chat room for code help.

If I have misunderstood your issue, please provide more information and open this issue again.

GitHub issues are for issues with freecodecamp itself, not for challenge help.

Happy codings!
