### ISSUE TITLE
Missing convert function

### ISSUE THREAD

**Issue by annagaiel** [FreeCodeCamp/freecodecamp#1086]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The second test below did not call convert function.
assert.strictEqual('<>', '<>', 'should escape characters');should escape characters: expected '<>' to equal '<>'
![screen shot 2015-06-23 at 6 32 10 am](https://cloud.githubusercontent.com/assets/1946785/8307101/9fd69bf4-1971-11e5-98be-1d8772834237.png)

**Comment by BerkeleyTrue** [comment]
@annagaiel Thanks for reporting. We will be tracking this issue at #1062
