### ISSUE TITLE
WayPoint challenge contains links to Slack instead of Gitter

### ISSUE THREAD

**Issue by gregorymususa** [FreeCodeCamp/freecodecamp#1087]
On the WayPoint challenge "Get Help the Hacker Way with RSAP"
http://www.freecodecamp.com/challenges/waypoint-get-help-the-hacker-way-with-rsap

*There is a link to Slack instead of Gitter.*

![waypoint_slack_gitter](https://cloud.githubusercontent.com/assets/1223920/8307410/fac78de8-19c6-11e5-8a4f-5ac4ae504c73.png)

----------
Excerpt:
"We have a special chat room specifically for getting help with tools you learn through these Free Code Camp Challenges. Go to https://freecodecamp.slack.com/messages/help/"

**Comment by BerkeleyTrue** [comment]
fixed.

Happy Coding!
