### ISSUE TITLE
Assigned value should be uppercase for consistency?

### ISSUE THREAD

**Issue by GarySiu** [FreeCodeCamp/FreeCodeCamp#10877]
Minor nitpick

Challenge [Global vs Local Scope in Functions](https://www.freecodecamp.com/challenges/global-vs-local-scope-in-functions#?solution=%0A%2F%2F%20Setup%0Avar%20outerWear%20%3D%20%22T-Shirt%22%3B%0A%0Afunction%20myOutfit()%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20outerWear%20%3D%20%22sweater%22%3B%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20outerWear%3B%0A%7D%0A%0AmyOutfit()%3B%0A) has an issue.

Currently:
```javascript

// Setup
var outerWear = "T-Shirt";

function myOutfit() {
  // Only change code below this line
  var outerWear = "sweater";
 
```

Suggested:
```javascript

// Setup
var outerWear = "T-Shirt";

function myOutfit() {
  // Only change code below this line
  var outerWear = "Sweater";
 
```

**Comment by dhcodes** [comment]
Tagging as possibly bike-shedding. Others feel free to share your thoughts.

**Comment by Bouncey** [comment]
I'm :+1: for bike shedding
