### ISSUE TITLE
Why wont it summit?

### ISSUE THREAD

**Issue by raul5614** [FreeCodeCamp/FreeCodeCamp#10874]
Challenge [Change the Color of Text](https://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%0A%3Ch2%20style%3D%22color%3A%20blue%22%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h2 style="color: blue">CatPhotoApp</h2>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Manish-Giri** [comment]
@raul5614 the instruction asks you to change the color to `red`. 
>Change your h2 element's style so that its text color is red.

What you have in your code is just taken from the example given on the left.

**Comment by raul5614** [comment]
Yea i saw thanks

**Comment by texas2010** [comment]
@raul5614 Next time, Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.
GitHub Issues are for reporting bugs on the website only.

Happy Coding.
