### ISSUE TITLE
Escaping Literal Quotes in Strings

### ISSUE THREAD

**Issue by courtjester71** [FreeCodeCamp/FreeCodeCamp#10887]
#### Challenge Name

Escaping Literal Quotes in Strings

https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

var myStr= "I am a\"double quoted\"string inside\"double quotes\"."; // Change this line

I've witnessed this exact same code pass, work, go through, with a colleague of mine. watched it, same code verbatim and the damn thing isn't registering, also watched it work on a web posting, so something isn't right here, works for some and not others, so if its working on one computer/path/time frame and now its not working, something is up 
 
 
 
```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by dhcodes** [comment]
@courtjester71 You have an error in your code. I recommend asking for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) room on Gitter.

**Comment by courtjester71** [comment]
No im not using bs chats, waste of time working with a gagle who might know
somethimg, and why then has the exact same code worked just fine for
others? Ill look into it, but not on a chat. I want answers not rhetoric

**Comment by erictleung** [comment]
@courtjester71 your code is incorrect. The string you need to pass the challenge is case- and space-sensitive. Chat rooms can be messy but that is the environment we use for coding help. If you have a colleague to work through and they have a working example, I would double check their work with yours. GitHub issues are only for true issues after you've tried and debugged all you can. Remember, programming is very sensitive to the instructions you give it. Happy coding!

**Comment by courtjester71** [comment]
Lol.....my eyes are pretty messed up....yeah ill look into it but on the
forums and legit coding sites never in a chat. They are worthlesd
