### ISSUE TITLE
Need to add convert() function call to second test

### ISSUE THREAD

**Issue by ejhunt** [FreeCodeCamp/freecodecamp#1088]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I believe the second test is incorrect. Test should be:

assert.strictEqual(convert('<>'), '<>', 'should escape characters');should escape characters: expected '<>' to equal '<>'

instead of:

assert.strictEqual('<>', '<>', 'should escape characters');should escape characters: expected '<>' to equal '<>'

![bug](https://cloud.githubusercontent.com/assets/3194379/8307785/8ba8f6d2-198e-11e5-8ab7-2ec5b9fb3098.png)

**Comment by BerkeleyTrue** [comment]
@ejhunt Thanks for reporting. We will be tracking this issue at #1062
