### ISSUE TITLE
Correct code but failing tests

### ISSUE THREAD

**Issue by rockcoolsaint** [FreeCodeCamp/FreeCodeCamp#10882]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Afunction%20titleCase(str)%20%7B%0A%20%20var%20arr_str%20%3D%20str.split(%22%20%22)%3B%0A%20%20var%20arr_case%20%3D%20%5B%5D%3B%0A%20%20var%20new_str%20%3D%20%22%22%3B%0A%20%20%0A%20%20for%20(var%20i%20in%20arr_str)%20%7B%0A%20%20%20%20arr_case.push(arr_str%5Bi%5D.substring(0%2C1).toUpperCase()%20%2B%20arr_str%5Bi%5D.slice(1).toLowerCase())%3B%0A%20%20%7D%0A%20%20%0A%20%20for%20(var%20j%20in%20arr_case)%20%7B%0A%20%20%20%20new_str%20%2B%3D%20arr_case%5Bj%5D%20%2B%20%22%20%22%3B%0A%20%20%7D%0A%20%20return%20new_str%3B%0A%7D%0A%0AtitleCase(%22sHoRt%20AnD%20sToUt%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
The code I have written is returning the right string but is failing to pass. 

My code:
```javascript

function titleCase(str) {
  var arr_str = str.split(" ");
  var arr_case = [];
  var new_str = "";
  
  for (var i in arr_str) {
    arr_case.push(arr_str[i].substring(0,1).toUpperCase() + arr_str[i].slice(1).toLowerCase());
  }
  
  for (var j in arr_case) {
    new_str += arr_case[j] + " ";
  }
  return new_str;
}

titleCase("sHoRt AnD sToUt");

```

**Comment by dhcodes** [comment]
@rockcoolsaint While quite close, you do have an error in your code that is preventing the tests from passing. Please consider asking for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) Gitter chat room.
