### ISSUE TITLE
Adjusting the Padding of an Element]

### ISSUE THREAD

**Issue by abinayams1010** [FreeCodeCamp/FreeCodeCamp#10883]
@Challenge [Adjusting the Padding of an Element](https://www.freecodecamp.com/challenges/adjusting-the-padding-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.injected-text%20%7B%0A%20%20%20%20margin-bottom%3A%20-25px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.box%20%7B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-color%3A%20black%3B%0A%20%20%20%20border-width%3A%205px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.green-box%20%7B%0A%20%20%20%20background-color%3A%20green%3B%0A%20%20%20%20padding%3A%2010px%3B%0A%20%20%7D%0A%20%20%0A%20%20.green-box%20%7B%0A%20%20%20%20background-color%3Ared%3B%0A%20%20%20%20padding%3A%2010px%3B%0A%20%20%7D%0A%0A%20%20.green-box%20%7B%0A%20%20%20%20background-color%3A%20green%3B%0A%20%20%20%20padding%3A%2010px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch5%20class%3D%22injected-text%22%3Emargin%3C%2Fh5%3E%0A%0A%3Cdiv%20class%3D%22box%20green-box%22%3E%0A%20%20%3Ch5%20class%3D%22box%20green%20-box%22%3Epadding%3C%2Fh5%3E%0A%20%20%3Ch5%20class%3D%22box%20green-box%22%3Epadding%3C%2Fh5%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .green-box {
    background-color: green;
    padding: 10px;
  }
  
  .green-box {
    background-color:red;
    padding: 10px;
  }

  .green-box {
    background-color: green;
    padding: 10px;
  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box green-box">
  <h5 class="box green -box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

```

**Comment by dhcodes** [comment]
@abinayams1010 You have an error in your code. Please consider asking for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) Gitter room for FCC.
