### ISSUE TITLE
Not able to pass test case (convert('<>')) in bonfire "Convert HTML entities"

### ISSUE THREAD

**Issue by ahsannaveed007** [FreeCodeCamp/freecodecamp#1089]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

function convert(str) {
  // &colon;&rpar;
  
  var regEx =/[&><"']/g;
  var match = regEx.exec(str);
  
  if(!match){
    return str;
  }
  
  
  for (var i=0; i<match.length; i++){
    switch (match[i]){
      case '&':
        return str.replace('&','&amp;');
        
      case "'":
        return str.replace('\'','&apos;');
        
      case '"':
        return str.replace('"','&quot;');
        
      case '<':
        return str.replace('<','&lt;');
        
      case '>':
        return str.replace('>','&gt;');
        
      default:
        return str;
    }
  }
}

convert('<>');

**Comment by oab00** [comment]
Indeed this bug has been there for a few days. 

![capture32](https://cloud.githubusercontent.com/assets/3732268/8272795/471abc26-1849-11e5-81da-0bb597ddf019.PNG)

http://www.freecodecamp.com/challenges/bonfire-convert-html-entities

the test never passes because it's not calling the Convert() function

**Comment by BerkeleyTrue** [comment]
@ahsannaveed007 Thanks for reporting. We will be tracking this issue at #1062

**Comment by dsifford** [comment]
I'm still getting an error with this:

```javascript
function convert(str) {
  str = str
    .replace(/>/g, "&gt;")
    .replace(/</g, "&lt;")
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
  return str;
}
convert('Dolce & Gabbana');
```
