### ISSUE TITLE
100% zoom in browser 

### ISSUE THREAD

**Issue by samanparsi** [FreeCodeCamp/FreeCodeCamp#10893]
Challenge [Size your Images](https://www.freecodecamp.com/challenges/size-your-images#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.smaller-image%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D%22smaller-image%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .smaller-image{
    width: 100px;
  }
</style>
<style>
  .red-text {
    color: red;
  }
  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```
I have 100% zoom in my firefox browser in windows 8 and manjero linux but in but of them the site dont accept it and i cant go ahead .

**Comment by Bouncey** [comment]
Is it in both browser/OS combinations that you can't progress past this challenge?

**Comment by dhcodes** [comment]
@samanparsi you have an error in your code. I don't believe it has anything to do with the zoom. Please consider asking for help in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) room on Gitter.

**Comment by marhyorh** [comment]
@dhcodes have you tried this challenge on mozilla?

**Comment by dhcodes** [comment]
@marhyorh yes. The code above works on Chrome and Firefox once corrected. I'm not on Win 8 though, but I'm fairly certain it's a code error.

**Comment by Jiangmx** [comment]
![2e0eb548-91d3-4a49-ad7c-669b44163b81](https://cloud.githubusercontent.com/assets/4746814/18826436/fa74a4d0-83ff-11e6-9741-ac6d550fde68.png)
![542067c4-f4f3-4643-80d9-f87d0f74dc97](https://cloud.githubusercontent.com/assets/4746814/18826462/16cab11a-8400-11e6-91d2-5b944ecfc170.png)
@dhcodes tried many ways,Did I misunderstand the question?

**Comment by Marmiz** [comment]
@Jiangmx if you look more carefoully, there's a typo in your code.
Specifically there's a colon in the class declaration:
```
.smaller-image: {
  width: 100px;
}
```

My suggestion is to always turn to the [Help Chat](https://gitter.im/FreeCodeCamp/Help) before assuming there's a bug.
Happy coding :)

**Comment by Jiangmx** [comment]
orz!Thank you.
Coding without IDE makes typo anywhere.
