### ISSUE TITLE
Syntax Error - Challenge: Use the Twitchtv JSON API

### ISSUE THREAD

**Issue by RebusGlider** [FreeCodeCamp/FreeCodeCamp#10892]
Challenge [Use the Twitchtv JSON API](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
"UPDATE: Due to a change in conditions on API usage explained here, use the sample API response we provide at"

The link to the sample API response is missing.

**Comment by atjonathan** [comment]
@RebusGlider, thanks for catching this!
This is weird, I cannot find this sentence in the [correct file](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/intermediate-ziplines.json#L161).

cc/ @FreeCodeCamp/issue-moderators

**Comment by hallaathrad** [comment]
Thinking this may be related to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10740. Please reopen if we're dealing with a different issue.

**Comment by BKinahan** [comment]
@atjonathan The change, with link error, is here: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/backup/master/seed/challenges/01-front-end-development-certification/intermediate-ziplines.json#L175

Note the branch.

**Comment by atjonathan** [comment]
Reopening as `help wanted`. Note you will need to add the [line from master](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/backup/master/seed/challenges/01-front-end-development-certification/intermediate-ziplines.json#L175) to staging and fix the syntax errors.

**Comment by zarruk** [comment]
So this means that we have to complete this challenge not calling the json but using the sample API response they're giving? Did I understand fine?
