### ISSUE TITLE
i  think i may have found a bug in the test

### ISSUE THREAD

**Issue by frogshelp** [FreeCodeCamp/FreeCodeCamp#10905]
Challenge [Comparison with the Strict Inequality Operator](https://www.freecodecamp.com/challenges/comparison-with-the-strict-inequality-operator#?solution=var%20myval%3D%2010%3B%0A%2F%2F%20Setup%0Afunction%20testStrictNotEqual(val)%20%7B%0A%20%20%2F%2F%20Only%20Change%20Code%20Below%20this%20Line%0A%20%0A%20%20if%20(val%20!%3D%3D%2017)%20%7B%0A%0A%20%20%2F%2F%20Only%20Change%20Code%20Above%20this%20Line%0A%0A%20%20%20%20return%20%22Not%20Equal%22%3B%0A%20%20%7D%0A%20%20return%20%22Equal%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestStrictNotEqual(12)%3B%0AtestStrictNotEqual(17)%3B%0AtestStrictNotEqual(%2217%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myval= 10;
// Setup
function testStrictNotEqual(val) {
  // Only Change Code Below this Line
 
  if (val !== 17) {

  // Only Change Code Above this Line

    return "Not Equal";
  }
  return "Equal";
}

// Change this value to test
testStrictNotEqual(12);
testStrictNotEqual(17);
testStrictNotEqual("17");
```

where it says testStrictNotEqual("bob") should return "Not Equal" on the check mark area of  what ur to do  as u see i never wrote that up on my code and yet it all still passed

**Comment by erictleung** [comment]
@frogshelp the challenge test are tests that are run in the background, independent of the function calls you make. In other words, in the background, the function call `testStrictNotEqual("bob")` is run and the result is checked. It doesn't check that you have typed it out yourself. I hope that makes sense. Closing this issue as there's no error. Happy coding!
