### ISSUE TITLE
Back End challenge view that runs tests and saves project URL

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#10901]
- As a user, when I click on a backend challenge from the map, I see:
  - a challenge description
  - a stack of tests with instructions (just like the other challenges)
  - a text field where I can enter my project's URL
- As a user, when I input the URL for my project, and click the "run test" button
  - the stack of tests tell me which passed and which failed
  - if all the tests pass, I get a toast confirming this. My project URL is saved as part of the entry in my progress array.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue this is the top priority. What is the status of this?

**Comment by BerkeleyTrue** [comment]
I'm working on it

**Comment by QuincyLarson** [comment]
@berkeleytrue to be 100% unambiguous this issue is critical path for curriculum development. Please focus on this issue so we can keep moving forward with our back end development curriculum.

**Comment by goblinsa** [comment]
hi,nice to met you.

**Comment by systimotic** [comment]
@QuincyLarson Can this be closed since https://github.com/freeCodeCamp/freeCodeCamp/pull/11058 was merged?

**Comment by QuincyLarson** [comment]
@systimotic yes. Thanks!
