### ISSUE TITLE
Passing waypoint without effectively completing it

### ISSUE THREAD

**Issue by amoedoamorim** [FreeCodeCamp/FreeCodeCamp#1090]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue. Waypoint requires you to have a 10px border around the img element, but you can pass by with a 5px border.

Steps to reproduce:

1) Paste `.thin-red-border { border-color: red; border-width: 5px; border-style: solid; }` into your code, inside your style tag.

2) Add `thick-green-border` to your img tag classes

3) Change your `.thin-red-border` to `.thick-green-border` and `border-color: red;` to `border-color: green;` inside your style tag.

Then the Waypoint allows you to the next challenge even if you don't change your border-width to 10px;

![fcc-bug](https://cloud.githubusercontent.com/assets/766082/8312596/e4821430-19b3-11e5-9a1e-473c95294b4c.png)

**Comment by jbmartinez** [comment]
Looking at the code, it seems that there's not a test for `border-width`.

Also, `solid` property is tested with a RegExp and it yields true if the word 'solid' is written in any place in the editor, it might be better to check it with JQuery's .css function, as in the test for `border-color` which, by the way, looks for `border-left-color`
