### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by Jenny1985** [FreeCodeCamp/FreeCodeCamp#10909]
#### Challenge Name

https://www.freecodecamp.com/challenges/make-instances-of-objects-with-a-constructor-function#?solution=%0Avar%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%205%3B%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyCar%20%3D%20new%20Car()%3B%0AmyCar.topEngine%20%3D%20%22Sally%22%3B%0A

#### Issue Description

I cannot pass the last recommended bullet, saying "The property nickname of myCar should be a string." I swear I have it as a string, im not sure what I am doing wrong, I did all the read search and ask and im not getting anywhere, please help me I cannot pass this challenge. 

#### Browser Information

* Browser Name, Version: Chrome
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 5;
};

// Only change code below this line.
myCar = new Car();
myCar.topEngine = "Sally";
 
 
```

**Comment by Manish-Giri** [comment]
@Jenny1985 Look at this instruction
>Then give myCar a nickname property with a string value.

You're expected to make a property with the name `nickname`, while your code has the name `topEngine`

```
myCar.topEngine = "Sally";
```

Rewrite this line with the correct property name, and you should be good!

**Comment by Jenny1985** [comment]
well now im super pissed at myself, thank u so much, i literally wasted 2 hours trying to figure this out

**Comment by slavo7** [comment]
var myCar = new Car ();
myCar.turboType = "twin";

i have the same problem and its not working ... and test is showing me that everything is ok
