### ISSUE TITLE
Menu should show username on smaller screens

### ISSUE THREAD

**Issue by hallaathrad** [FreeCodeCamp/FreeCodeCamp#10900]
As discussed on #10581, on smaller screens (where the nav becomes a hidden menu), the user settings link should also display the username.

Like this:

<img width="463" alt="screen shot 2016-09-13 at 12 00 30" src="https://cloud.githubusercontent.com/assets/2107110/18481300/b5340768-79a9-11e6-9b81-b3cdb6e18438.png">

**Comment by hallaathrad** [comment]
@marhyorh All yours :)

**Comment by marhyorh** [comment]
@hallaathrad done :+1:
