### ISSUE TITLE
Finders Keepers Issue

### ISSUE THREAD

**Issue by ajimenezrosa** [FreeCodeCamp/FreeCodeCamp#10917]
Challenge [Finders Keepers](https://www.freecodecamp.com/challenges/finders-keepers#?solution=%0Afunction%20findElement(arr%2C%20func)%20%7B%0A%20%20%2F%2F%20Make%20num%20undefined%20by%20default%0A%20%20var%20num%3B%0A%0A%20%20%2F%2F%20Loop%20thorugh%20the%20array%20and%20use%20the%20function%20to%20check%0A%20%20for%20(var%20a%20%3D%200%3B%20a%20%3C%20arr.length%3B%20a%2B%2B)%20%7B%0A%20%20%20%20if%20(func(arr%5Ba%5D))%20%7B%0A%20%20%20%20%20%20%2F%2F%20Store%20the%20first%20case%20and%20break%20the%20loop%0A%20%20%20%20%20%20num%20%3D%20arr%5Ba%5D%3B%0A%20%20%20%20%20%20return%20num%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20%2F%2F%20otherwise%20return%20undefined%0A%20%20return%20num%3B%0A%7D%0A%0Afind(%5B1%2C%202%2C%203%2C%204%5D%2C%20function(num)%20%7B%0A%20%20return%20num%20%25%202%20%3D%3D%3D%200%3B%0A%7D)%3B%0A%2F%2F%20Using%20Arr.filter()%0A%0Afunction%20find(arr%2C%20func)%20%7B%0A%20%20%2F%2F%20filter%20the%20provide%20array%20by%20the%20function%20provided%20and%20return%20only%20the%20first%20element.%0A%20%20return%20arr.filter(func)%5B0%5D%3B%0A%7D%0AfindElement(%5B1%2C%202%2C%203%2C%204%5D%2C%20function(num)%7B%20return%20num%20%25%202%20%3D%3D%3D%200%3B%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function findElement(arr, func) {
  // Make num undefined by default
  var num;

  // Loop thorugh the array and use the function to check
  for (var a = 0; a < arr.length; a++) {
    if (func(arr[a])) {
      // Store the first case and break the loop
      num = arr[a];
      return num;
    }
  }

  // otherwise return undefined
  return num;
}

find([1, 2, 3, 4], function(num) {
  return num % 2 === 0;
});
// Using Arr.filter()

function find(arr, func) {
  // filter the provide array by the function provided and return only the first element.
  return arr.filter(func)[0];
}
findElement([1, 2, 3, 4], function(num){ return num % 2 === 0; });

```

**Comment by erictleung** [comment]
@ajimenezrosa your code works. Can you elaborate on what your issue is?

**Comment by atjonathan** [comment]
Closing as stale.
