### ISSUE TITLE
The description is wrog

### ISSUE THREAD

**Issue by yplonggit** [FreeCodeCamp/FreeCodeCamp#10912]
Challenge [Filter Arrays with filter](https://www.freecodecamp.com/challenges/filter-arrays-with-filter#?solution=%0Avar%20oldArray%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20newArray%20%3D%20oldArray.filter(function(val)%7B%0A%20%20return%20val%3C6%3B%0A%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter(function(val){
  return val<6;
});

```

---------------------
The right code he less than six but  the test case  said : You should have filtered out all values from the array that are greater than 5.

**Comment by ktajpuri** [comment]
I will like to fix this one please. I am a first timer. trying to describe the issue in a bit better.

The description for problem shows :
![image](https://cloud.githubusercontent.com/assets/10725893/18815042/f3a3f750-8341-11e6-935e-1e3d57fb1d2e.png)

Test Case shows :
![image](https://cloud.githubusercontent.com/assets/10725893/18815045/0bbaecf4-8342-11e6-8eb6-dc6699269754.png)

The text should have been 
```
You should have filtered out all values from the array that are less than 6.
```

**Comment by Bouncey** [comment]
I think there is a misunderstanding for non native English speakers. The instructions are asking to the same thing, but from different perspectives. 

What the filter callback is doing in the example from @yplonggit provided is basically saying

If val is less than 6, return it. Else do nothing. 

This will give us a new array where all values are less than 6, all values that are 6 or higher have been filtered out. 


If I have misunderstood the issue, please let me know. 

We could perhaps have consistency between the instructions and the test-suite, not changing perspective in between them to aid non-native English speakers. 

Cc @FreeCodeCamp/issue-moderators

**Comment by ktajpuri** [comment]
@Bouncey  You are correct. Do you think changing the description of the second test case as below to avoid confusion for non native English speakers?
* All the values of `newArray` should be less than 6.

**Comment by QuincyLarson** [comment]
@ktajpuri I think we should stick with the "you should" structure used with the other tests, but we can definitely make it easier to understand for non-native English speakers. We strive to be easily understood in all of our copy on FCC.

**Comment by Bouncey** [comment]
@ktajpuri seeing as you have a PR open for this issue, can you please change the test message from:

`You should have filtered out all values from the array that are greater than 5.`

to

`<code>newArray</code> should be an array containing only the values from <code>oldArray</code> that are less than 6.`

Use `git commit --amend` to update your PR.

Please follow the advice from [CONTRIBUTING.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md). If you get stuck, reach out for help in the [Contributors Chat Room](https://gitter.im/FreeCodeCamp/Contributors).

Good luck, 

Happy Coding and

Thanks for contributing :tada:

**Comment by ktajpuri** [comment]
Thanks @Bouncey @QuincyLarson  for considering my PR. I have made the changes suggested. Please review the PR.
