### ISSUE TITLE
I am having problems with using a CSS class to style an element. I'm lost and need help.

### ISSUE THREAD

**Issue by humbrod99** [FreeCodeCamp/FreeCodeCamp#10916]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20.red-text%7B%0A%20%20%20%20.color%3Ared%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
 .red-text{
    .color:red;
  }
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by humbrod99** [comment]
I did it but nobody help me there. I waited like 20 minutes and nobody said anything to my problem but thanks anyway

**Comment by Murdos67** [comment]
If you have not got it yet, you have to add the class to the h2 script line
