### ISSUE TITLE
I'm stuck

### ISSUE THREAD

**Issue by Noigallardo** [FreeCodeCamp/FreeCodeCamp#10913]
#### Browser Information

* Browser Name, Version: google chrome
* Operating System: windows 10
* Desktop

**Comment by ktajpuri** [comment]
Can you please elaborate? Where are you stuck ?
Please contact in gitter. Its almost always better.
https://gitter.im/FreeCodeCamp/HelpBackEnd

**Comment by erictleung** [comment]
@Noigallardo thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help) or [HelpFrontEnd](https://gitter.im/FreeCodeCamp/HelpFrontEnd). Happy coding!

**Comment by Noigallardo** [comment]
I used to open it in Internet Explorer, and its worked...
not working in Goggle Chrome
