### ISSUE TITLE
Waypoint: Mobile Responsive Images 

### ISSUE THREAD

**Issue by bencten** [FreeCodeCamp/FreeCodeCamp#1091]
Challenge http://www.freecodecamp.com/challenges/waypoint-mobile-responsive-images has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The second challenge does not validate:
Add a second image with the src of http://bit.ly/fcc-kittens2.

**Comment by benschenker** [comment]
Thanks @bencten!

This issue is stale and I wasn't able to replicate with the new URL: http://www.freecodecamp.com/challenges/waypoint-make-images-mobile-responsive

Closing for now, but reopen if you still have this issue
