### ISSUE TITLE
Back End Certificate slide shows Full Stack image

### ISSUE THREAD

**Issue by dhcodes** [FreeCodeCamp/FreeCodeCamp#10928]
#### Challenge Name

https://www.freecodecamp.com/challenges/claim-your-back-end-development-certificate 

#### Issue Description

Third slide says "Full Stack Development Certificate requirements". Should say "Back End Development Certificate requirements". This is true on `staging` and `backup/staging`. 

The img link that needs to be updated is here: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/03-back-end-development-certification/back-end-development-certificate.json#L23

#### Screenshot

http://i.imgur.com/qo3hoQx.png

**Comment by Bouncey** [comment]
Congrats on your backend cert :tada:!

**Comment by dhcodes** [comment]
Lol I haven't gotten it yet! Just saw this while testing a PR :+1

**Comment by jihdeh** [comment]
@dhcodes is help needed on this?

**Comment by dhcodes** [comment]
@jihdeh sure, but I'm not sure who has access to the imgur assets, but if we can figure it out, then yeah it's all yours.

**Comment by QuincyLarson** [comment]
@dhcodes @jihdeh you can't change the image - only add a new URL. So the new image could be uploaded anywhere and then that challenge (and its translations) would need to be updated. 

We are going to replace the certifications with @atjonathan's updated ones soon anyway.

**Comment by dhcodes** [comment]
@QuincyLarson Since this is a challenge slide, I'm not sure the @atjonathan's overhaul will affect this. I'm fine making the image and uploading it to imgur, but I thought FCC might have an account to promote reliability of assets.

**Comment by QuincyLarson** [comment]
@dhcodes I am replacing all of these certificate claiming challenges on Staging. So this challenge will cease to exist.
