### ISSUE TITLE
do belive i found a bug in this challenge

### ISSUE THREAD

**Issue by frogshelp** [FreeCodeCamp/FreeCodeCamp#10922]
Challenge [Comparisons with the Logical Or Operator](https://www.freecodecamp.com/challenges/comparisons-with-the-logical-or-operator#?solution=%0Avar%20myval%20%3D0%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20if%20(val%20%3E%3D%2019%20%7C%7C%20val%20%3C%3D%2020)%20%7B%0A%20%20%20%20return%20%22Outside%22%3B%0A%20%20%7D%0A%0A%20%20%20%7B%0A%20%20%20%20return%20%22Outside%22%3B%0A%20%20%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20%22Inside%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestLogicalOr(15)%3B%0AtestLogicalOr(%220%22)%3B%0AtestLogicalOr(%2210%22)%3B%0AtestLogicalOr(%2220%22)%3B%0AtestLogicalOr(%2221%22)%3B%0AtestLogicalOr(%2219%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
![image](https://cloud.githubusercontent.com/assets/19509837/18827235/c862f7cc-839f-11e6-8b54-b4089e6b28dc.png)

```


no matter what i do to the code the ones for should return inside fails every time and does not change no matter how u change the code and i have reset and refreshed my brower 3 times and no matter what i do those three for should return inside does not pass at all and i do believe its caused by having to remove the second if statment cause ive tried to add into one if statment and i can change the numbers from 0 to 100 to 25 whatever and it still only passes the outside but never the inside
syntex error scanned (58%) ive gotten that error three times now

**Comment by marhyorh** [comment]
You have some couple errors in your code, pls use this [Help Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) and close the issue :+1:

**Comment by ktajpuri** [comment]
I recommend reading this [if else] .(https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/if...else)

**Comment by erictleung** [comment]
@frogshelp as I and others have pointed out, there are errors in your code. Please take a look at the help room for more help. Again, I would recommend looking at the challenge tests that your code is failing and figuring out why. Closing this issue as GitHub issues are not for coding help. Happy coding!
