### ISSUE TITLE
there is a repetitive error 

### ISSUE THREAD

**Issue by 93vishnu** [FreeCodeCamp/FreeCodeCamp#10920]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by Bouncey** [comment]
@93vishnu sorry to hear you are having trouble with freeCodeCamp and thank you for reporting it. 

But we really do need more information. A challenge name would be good, a copy and paste of your code would be fantastic too. And if you could be more descriptive of the error, we might just be able to help you out!

In short, we need you to help us help you :smiley:

**Comment by Bouncey** [comment]
@93vishnu please reopen this issue if you have more information
