### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by asapuneha** [FreeCodeCamp/FreeCodeCamp#10923]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%20%3D%20%22%5C%20I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22%20%22%20%3B%20%0A%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
javascript
![error](https://cloud.githubusercontent.com/assets/22187486/18831316/b8347016-8402-11e6-8c65-822698ca9534.PNG)

var myStr = "\ I am a \"double quoted\" string inside \"double quotes\" " ; 
// Change this line

```

**Comment by dhcodes** [comment]
@asapuneha you have an error in your code. Please consider asking for help in the help chat room as directed by VarCI-bot above.
