### ISSUE TITLE
grammar error in field guide

### ISSUE THREAD

**Issue by benflinn** [FreeCodeCamp/freecodecamp#1092]
http://www.freecodecamp.com/field-guide/what-is-pair-programming-and-why-is-it-special

"By pair programming with other Free Code Camp students on our coding challenges." is not a complete sentence.

Don't mean to be picky, just want Code Camp to be the best it can be! :) What's the best way to deal with future grammatical errors?

**Comment by BerkeleyTrue** [comment]
Field guides are now in the wiki and are editable. If the grammar issue is still there please feel free to correct it.

Happy coding!
