### ISSUE TITLE
let ourName; why has ES 6 Warning ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [FreeCodeCamp/FreeCodeCamp#10924]
Challenge [Declare JavaScript Variables](https://www.freecodecamp.com/challenges/declare-javascript-variables#?solution=%0A%2F%2F%20Example%0Avar%20myName%3B%0A%2F%2F%20let%20ourName%3B%0A%2F%2FES6%20%3A%20undefined%2C%20null%2C%20boolean%2C%20string%2C%20symbol%2C%20number%2C%20object.%0A%2F%2F%20Define%20myName%20below%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var myName;
// let ourName;
//ES6 : undefined, null, boolean, string, symbol, number, object.
// Define myName below this line


```

**Comment by ktajpuri** [comment]
@xgqfrms-GitHub  Please use [help chat room] (https://gitter.im/FreeCodeCamp/Help) as your first place when you have any confusion in a challenge. 
In this challenge, you only have to edit lines below `// Define myName below this line` comment. You have declared it above. I guess this is the reason why the test is failing.

**Comment by texas2010** [comment]
I dont see any issue you have. so closed this issue since it dont have a problem

**Comment by texas2010** [comment]
@xgqfrms-GitHub, that challenge dont have a problem.  that challenge didnt ask you write let.  you suppose to write var.   this case is closed. 

happy coding!
