### ISSUE TITLE
what's wrong with this?  

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [FreeCodeCamp/FreeCodeCamp#10926]
Challenge [Quoting Strings with Single Quotes](https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes#?solution=%0Avar%20myStr%20%3D%20'%3Ca%20href%3D%22http%3A%2F%2Fwww.example.com%22%20target%3D%22_blank%22%3ELink%3C%2Fa%3E'%3B%0Aalert(myStr)%3B%0A%0A%2F%2F%20var%20myStr%20%3D%20'%3Ca%20href%3D%22http%3A%2F%2Fwww.example.com%22%20target%3D%22_blank%22%3ELink%3C%2Fa%3E'%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';
alert(myStr);

// var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';
```

**Comment by xgqfrms-GitHub** [comment]
I just understand why?
but , after some times try, I passed!

> 
var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';
alert(myStr);

**it seems that, you shoul put your code on line 1 ? I'm not sure that!**

**Comment by texas2010** [comment]
@xgqfrms-GitHub 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.
you cant use this issue for ask help.

Happy Coding.
