### ISSUE TITLE
do believe i found a bug in this challenge

### ISSUE THREAD

**Issue by frogshelp** [FreeCodeCamp/FreeCodeCamp#10921]
Challenge [Comparisons with the Logical Or Operator](https://www.freecodecamp.com/challenges/comparisons-with-the-logical-or-operator#?solution=%0Avar%20myval%20%3D0%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20if%20(val%20%3E%3D%2019%20%7C%7C%20val%20%3C%3D%2020)%20%7B%0A%20%20%20%20return%20%22Outside%22%3B%0A%20%20%7D%0A%0A%20%20%20%7B%0A%20%20%20%20return%20%22Outside%22%3B%0A%20%20%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20%22Inside%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestLogicalOr(15)%3B%0AtestLogicalOr(%220%22)%3B%0AtestLogicalOr(%2210%22)%3B%0AtestLogicalOr(%2220%22)%3B%0AtestLogicalOr(%2221%22)%3B%0AtestLogicalOr(%2219%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myval =0;
  // Only change code below this line

  if (val >= 19 || val <= 20) {
    return "Outside";
  }

   {
    return "Outside";
  }

  // Only change code above this line
  return "Inside";
}

// Change this value to test
testLogicalOr(15);
testLogicalOr("0");
testLogicalOr("10");
testLogicalOr("20");
testLogicalOr("21");
testLogicalOr("19");

```

no matter how i change it    it still fails on 3-4 of them  and if i change  any of the order the with wrong number on the if statment  it give's me a unrecoverable syntex error scanned (58%) yellow sign icon on the challenge i reset it  and refreshed page  and it goes back to normal but ive changed the if statment with the numbers twice even without the = sign  and ive gotten that error twice

**Comment by erictleung** [comment]
@frogshelp thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Reset your code will help because it appears you have deleted the function declaration for `testLogicalOr` at the beginning. So your code should have some structure like

```js
function testLogicalOr(val) {
  ...
}
```

Each of the challenge tests will run this test and according to the code you have above, the challenge will fail. Closing this issue as coding help. If you have a function name and code that you know should pass but doesn't, feel free to comment here. Happy coding!

**Comment by frogshelp** [comment]
no its not help its no matter what i do to the code the ones for should rrturn insde fails  every time and does not change  no matter how u change the code and i have reset  and refreshed my brower 3 times and no matter what i do those three for  should return inside does not pass at all and i do belive its caused by having to remove the second if statment  cause ive tried to add into one if statment and i can change the numbers from 0 to 100 to 25  whatever and it still only passes the outside but never the inside

**Comment by frogshelp** [comment]
![image](https://cloud.githubusercontent.com/assets/19509837/18826883/b46f87b4-839d-11e6-9200-4261e3045a82.png)
and this is even after reseting the code

**Comment by erictleung** [comment]
@frogshelp thanks for the clarification. However, your code is incorrect. Please check which challenge tests that are failing and think about why they are failing. 

Also, you have an isolated piece of code

```js
...
{
  return "Outside";
}
...
```

that isn't doing anything. Please consult the [Help Room](https://gitter.im/FreeCodeCamp/Help) if you have any more questions. Happy coding!
