### ISSUE TITLE
"Submit challenge" doesn't progress if page not active for more than 3 minutes

### ISSUE THREAD

**Issue by nileshbj** [FreeCodeCamp/FreeCodeCamp#10933]
Challenge [Inform with the Paragraph Element](https://www.freecodecamp.com/challenges/inform-with-the-paragraph-element#?solution=%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
<p>Hello Paragraph</p>


```

**Comment by nileshbj** [comment]
I have to refresh page to get it working.

**Comment by Bouncey** [comment]
Can you please tell me:

What your Operating System is? (Windows, Mac, Linux)
What browser you are having issues with? (ie/Edge, FireFox, Chrome, Safari)

Have you tried it on different browsers?

I can't reproduce this at the minute

Many thanks

**Comment by erictleung** [comment]
I can't reproduce this either. I'm on a Mac on Chrome.

**Comment by nileshbj** [comment]
Hey there, sorry for not being descriptive, I am on Win's 7 and my browser is Chrome Version 53.0.2785.116 m. 
Steps to reproduce is simple, once you are on the challenge page and for some reason not active for more than 3 mins (consider to roughly 5 mins) or so and then once you are back and try to submit the challenge the loading screen gets stuck.

**Comment by dhcodes** [comment]
@nileshbj I have a similar setup and cannot replicate. Could this be a setting on your browser? Are you sure the browser is focused when you click the button?
