### ISSUE TITLE
FCC doesn't accept answers with global variables. Whether FCC should mention on challenge rules that global variables are not allowed or add a mechanism that can test challenges with global variables so that users can save their time and efforts. 

### ISSUE THREAD

**Issue by HQuser** [FreeCodeCamp/FreeCodeCamp#10932]
Challenge [Steamroller](https://www.freecodecamp.com/challenges/steamroller#?solution=var%20result%20%3D%20%5B%5D%3B%0Afunction%20steamrollArray(arr)%20%7B%0A%20%20%2F%2F%20I'm%20a%20steamroller%2C%20baby%0A%20%20for(var%20i%20%3D%200%3B%20i%3Carr.length%3B%20i%2B%2B)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20if(Array.isArray(arr%5Bi%5D))%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20steamrollArray(arr%5Bi%5D)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20else%20if(!Array.isArray(arr%5Bi%5D)%20%26%26%20arr%5Bi%5D%20!%3D%3D%20null)%0A%20%20%20%20%20%20%20%20%7B%20%0A%20%20%20%20%20%20%20%20%20%20result.push(arr%5Bi%5D)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20return%20result%3B%0A%7D%0A%0AsteamrollArray(%5B1%2C%20%7B%7D%2C%20%5B3%2C%20%5B%5B4%5D%5D%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var result = [];
function steamrollArray(arr) {
  // I'm a steamroller, baby
  for(var i = 0; i<arr.length; i++)
    {
      if(Array.isArray(arr[i]))
        {
          steamrollArray(arr[i]);
        }
      else if(!Array.isArray(arr[i]) && arr[i] !== null)
        { 
          result.push(arr[i]);
        }
    }
  return result;
}

steamrollArray([1, {}, [3, [[4]]]]);

```

**Comment by erictleung** [comment]
@HQuser thanks for the issue. This is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9063. So closing this issue in favor of the already present issue. Happy coding!
