### ISSUE TITLE
manipulate array using unshift

### ISSUE THREAD

**Issue by c-restha** [FreeCodeCamp/FreeCodeCamp#10934]
Challenge [Manipulate Arrays With unshift](https://www.freecodecamp.com/challenges/manipulate-arrays-with-unshift#?solution=var%20ourArray%20%3D%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%5B%22cat%22%5D%5D%3B%0A%0AourArray.shift()%3B%20%2F%2F%20ourArray%20now%20equals%20%5B%22J%22%2C%20%5B%22cat%22%5D%5D%0A%0AourArray.unshift(%22happy%22)%3B%20%2F%2F%20ourArray%20now%20equals%20%5B%22happy%22%2C%20%22J%22%2C%20%5B%22cat%22%5D%5D%0A%0Avar%20myArray%20%3D%20%5B%22John%22%2C%2023%2C%20%5B%22dog%22%2C%203%5D%5D%3B%0A%0A%20myArray.shift()%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AmyArray.unshift(%5B%22paul%22%2C35%5D)%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A(function(y%2C%20z)%7Breturn%20%27myArray%20%3D%20%27%20%2B%20JSON.stringify(y)%3B%7D)(myArray)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var ourArray = ["Stimpson", "J", ["cat"]];

ourArray.shift(); // ourArray now equals ["J", ["cat"]]

ourArray.unshift("happy"); // ourArray now equals ["happy", "J", ["cat"]]

var myArray = ["John", 23, ["dog", 3]];

 myArray.shift();

// Only change code below this line.

myArray.unshift(["paul",35]);

// Only change code above this line.

(function(y, z){return 'myArray = ' + JSON.stringify(y);})(myArray);

```

**Comment by marhyorh** [comment]
Pls make use of the [help room](https://gitter.im/FreeCodeCamp/HelpJavaScript) next time. In your code you changed the restricted code. You were asked not to change the code above myArray.shift() but you replaced `var myArray = ["John", 23], ["dog", 3]];` with `var myArray = ["John", 23, ["dog", 3]];`. I suggest you reset the code the pass in the appropriate code where you are supppose to place it. You almost got it right :+1: Don't forget that, "paul" is not "Paul". Make amendments, close the issue and use the [help room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for further issues. 
Thank you.

**Comment by Bouncey** [comment]
@c-restha You have change the initial value of `myArray`, this is one reason the tests are not passing.

Click the `Reset` button to amend this.

As @marhyorh said, github issues are not for code help, we have dedicated chatrooms for that on gitter. Click the `Help` button to be taken there.

Please re-read the instructions and remeber that javaScript is case sensitive, and so are our tests.

Closing because it is for code help.

If I have misunderstood your issue, please feel free to open this issue again and provide more information.

**Comment by nazmulhooque** [comment]
// Example
var ourArray = ["Stimpson", "J", "cat"];
ourArray.shift(); // ourArray now equals ["J", "cat"]
ourArray.unshift("Happy"); 
// ourArray now equals ["Happy", "J", "cat"]

// Setup
var myArray = [["John", 23], ["dog", 3]];
myArray.shift();

// Only change code below this line.
myArray.unshift(["Paul",35]);

**Comment by texas2010** [comment]
@nazmulhooque if you want to help people. please use forum or chat room. but please don't give solution code to people. thanks
