### ISSUE TITLE
Comparisons with the Logical And Operator

### ISSUE THREAD

**Issue by courtjester71** [FreeCodeCamp/FreeCodeCamp#10947]
#### Challenge Name

https://www.freecodecamp.com/challenges/comparisons-with-the-logical-and-operator#?solution

#### Issue Description

once again this is bullshit, its all on your end

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 function testLogicalAnd(val) {
  // Only change code below this line

  if (val<=50 && val>=25) {
   return "yes";
  }

  // Only change code above this line
  return "No";
}

// Change this value to test
testLogicalAnd(10);

 
```

**Comment by erictleung** [comment]
@courtjester71 thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: your code is slightly incorrect. Please take note of capitalization of letters that is required to pass the challenge. Please seek answers in chat rooms if you still have questions. Happy coding!
