### ISSUE TITLE
Challenge Concatenating Strings with the Plus Equals Operator More Info

### ISSUE THREAD

**Issue by afable** [FreeCodeCamp/FreeCodeCamp#10944]
#### Challenge: Concatenating Strings with the Plus Equals Operator
https://www.freecodecamp.com/challenges/concatenating-strings-with-the-plus-equals-operator

#### Issue Description
In the instructions given, I provided the following code:
```
var myStr;
myStr += "This is the first sentence. ";
myStr += "This is the second sentence.";
```

Resulting in...
```
myStr = "undefinedThis is the first sentence. This is the second sentence."
```

Which is as expected but I think new coders may not understand (or have forgotten) why myStr begins with "undefined". I suggest a hint to remind campers that myStr should first be initialized to the first sentence and then they can use the += operator.

#### Browser Information
Win10 Desktop Chrome, Version 53.0.2785.116 m (64-bit)

**Comment by afable** [comment]
I just noticed that the example ourStr already shows this procedure, so maybe the challenge is fine as is (I tend to overlook the examples which I assume is NOT what a new coder would do).

I've also seen from other challenges that string literals are generally initialized to "" instead of being just declared and not initialized, so I suppose it boils down to whether FCC wants campers to  deal with an uninitialized string literal in the first place.

**Comment by erictleung** [comment]
@afable thanks for the feedback. I want to say the challenges are built so that there is some guidance but not too much. There should be bits of critical thinking involved in solving the challenges.

In this case with the code you have where you initialize the variable first, the resulting string produces an unexpected `undefined` at the beginning of the string. This may (and probably should) raise some flags in the coder's head.

So I don't think there is too much alarm for this challenge. The key and I think flow of the challenges is to see the example and modify it slightly to complete the challenge. But I'm open for discussion on the topic if others feel additional comments are needed about the challenge.

**Comment by afable** [comment]
Closing since challenge seems fine as is.

**Comment by Drizzt91AJ** [comment]
Right but on the first example you used at the top of the page it says undefined, but if you take the first + sign out it comes back as correct. as such:

var myStr;
myStr = "This is the first sentence. ";
myStr += "This is the second sentence.";

When i run it like this, it green lights it and doesnt spit back the "undefined" part.
Thanks

**Comment by Fernando-Marquardt** [comment]
But if you did:

var myStr = "";
myStr += "This is the first sentence. ";
myStr += "This is the second sentence.";

It would also work.

**Comment by meamay07** [comment]
var myStr="This is the first sentence.";
myStr += "This is the second sentence.";
 
what did I do wrong?

**Comment by texas2010** [comment]
@meamay07 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by JSWesterfield** [comment]
@texas2010 You had time to comment to not help? smh. @meamay07  If you would look at the above examples, these guys initialized the variable(var) first, so there should be 3 sentences here:

var myStr=" ";
myStr+="This is the first sentence.";
myStr+=" This is the second sentence.";

Good Luck!

**Comment by texas2010** [comment]
@JSWesterfield, GitHub Issues are for reporting bugs on the website only.

**Comment by JSWesterfield** [comment]
My apologies this might be a incorrect button press.

**Comment by texas2010** [comment]
@JSWesterfield, it is fine. people have to go to Chat room or forum for ask help. but not this issue thread.  that is why I gave a link to that person.

**Comment by wizardMonkie** [comment]
@erictleung
General feedback: As a beginner this lesson threw me off. I been writing everything down and "undefined" slipped by real good lol. Gotta watch out for information flooding. Holding someones hand is damaging but quick reminders about random past lessons would go a long way in a forward moving environment, background nagging keeps old info as fresh as new. Other than this one, all is well so far. But most likely my own fault lol.

**Comment by codenamecobra** [comment]
i'm stuck on this one too
here's my code 
var myStr = "This is the first sentence."; myStr += "This is the second sentence";
heres what im missing

myStr should have a value of This is the first sentence. This is the second sentence.

**Comment by texas2010** [comment]
@codenamecobra 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by MesutOzil2807** [comment]
var myStr = "";
myStr += "This is the first sentence. This is the second sentence.";

It would also work.
