### ISSUE TITLE
[ Feature Request ] Provide transcript for videos or alternative options

### ISSUE THREAD

**Issue by ktajpuri** [FreeCodeCamp/FreeCodeCamp#10942]
#### Challenge Name
All the video instructions

#### Issue Description
In some places access to youtube is blocked, e.g. colleges, schools or behind corporate proxy firewall. It would be really nice to have a transcript of the video with key screenshots. This would also help people with slow internet connection or costly mobile data plans to better understand the instructions.

#### Browser Information
All browsers

#### Your Code
NA
 
 
 
```
#### Screenshot
NA

**Comment by erictleung** [comment]
@ktajpuri thanks for the request. Can you give an example of an instruction video? I'm assuming its not one of the video challenges. But I thought the video instructions usually have a small transcript summary below them.

**Comment by ktajpuri** [comment]
@erictleung  I am talking about all the videos in freecodecamp curriculum. [Example 1](https://www.freecodecamp.com/challenges/save-your-code-revisions-forever-with-git) , [Example 2](https://www.freecodecamp.com/challenges/start-a-nodejs-server). I understand that there are instructions on the left as checkboxes, but it would be better to have a complete transcript like coursera provides. It is a word by word transcript of the video.

**Comment by atjonathan** [comment]
We will probably be removing these challenges with the new curriculum update. Close as `bike shedding`?

**Comment by ktajpuri** [comment]
Where can I see the new curriculam structure?

**Comment by ktajpuri** [comment]
I think it would also be good if we could organise live coding competitions open to all campers. What say? @atjonathan

**Comment by atjonathan** [comment]
@ktajpuri, https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10724 and feel free to open a new issue :smiley:
