### ISSUE TITLE
code is right, but it won't pass???

### ISSUE THREAD

**Issue by Joyfisher** [FreeCodeCamp/FreeCodeCamp#10943]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%20%3D%20%22I%20am%20a%20%5C%22double%20quoated%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22.%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "I am a \"double quoated\" string inside \"double quotes\"."; // Change this line



```

**Comment by texas2010** [comment]
@Joyfisher, Yes your code is correct. but you got typo in the word. that is why it wont passed.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
