### ISSUE TITLE
Word Blanks challenge difficult for ESL campers (and a bit obtuse for people who have never heard of madlibs)

### ISSUE THREAD

**Issue by maz-net-au** [FreeCodeCamp/FreeCodeCamp#10945]
Challenge [Word Blanks](https://www.freecodecamp.com/challenges/word-blanks) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I wonder if this challenge is suitable for the large number of campers who speak english as a second language or if it could be re-worded so that understanding english sentence structure or the game "madlibs" is no longer required. I see a disproportionate number of campers unable to even begin this challenge, asking questions in the gitter chat rooms. If we could distill this challenge to its programming essence, I believe it would be good.
- Maz

**Comment by tsalexey544** [comment]
English is not my first. I can tell what I did: I just added random words =)

But I agree. If it was simpler would be more fun

**Comment by Fernando-Marquardt** [comment]
English is my second language and I didn't find this challange difficult at all. A quick search explained what "madlibs" is and there is even a link to the Wikepedia.

But, I do agree that maybe there is a better way to explain the challange, without the use of the "madlibs" reference.

**Comment by vxm007** [comment]
English is my first language and I still thought the exercise was a bit weird. A lot of these exercises I don't feel are very clearly laid out. The instructions are often worded in a weird way.. To me anyways.

**Comment by dhcodes** [comment]
Perhaps we should remove the MadLibs reference and use the Wikipedia entry for Phrasal Template? https://en.wikipedia.org/wiki/Phrasal_template

**Comment by erictleung** [comment]
There has been discussion about this earlier https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10100 and changes being merged https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10172. I guess they just haven't been pushed up to production yet.

The changes made are something like this.

> We will now use our knowledge of strings to build a "Mad Libs" style word game we're calling "Word Blanks". You will create an (optionally humorous) "Fill in the Blanks" style sentence. Here's an example incomplete sentence.
> 
> ```
> "The ______ ______ looked around ______ then ______ into the house"
> ```
>
> These four blanks would be filled in this order: (adjective) (noun) (adverb) (verb)
>
> You will need to use string concatenation to build a new string, `result`, using the variables `myNoun`, `myAdjective`, `myVerb`, and `myAdverb`. These variables are passed to the function as parameters.  Don't change these parameter names in the function.
>
> Include additional strings and spaces (which will not change) in between the provided variables to make a complete sentence.

Any changes to be made to this?

**Comment by systimotic** [comment]
Hi all! It seems this issue is very similar to #10100, so I'm closing it as a duplicate.
As Eric said above, if any changes should be made, or the new changes make things more confusing, please feel free to let us know what we should change into what and reopen the issue.
Happy coding!
