### ISSUE TITLE
Valid answer is not recognized

### ISSUE THREAD

**Issue by martin-simonini** [FreeCodeCamp/FreeCodeCamp#10941]
Challenge [Missing letters](https://www.freecodecamp.com/challenges/missing-letters#?solution=%0Afunction%20fearNotLetter(str)%20%7B%0A%20%20%2F%2Fconsole.log(str)%3B%0A%20%20var%20alpha%20%3D%20(%22abcdefghijklmnopqrstuvwxyz%22)%3B%0A%20%20strArr%20%3D%20str.split(%22%22)%3B%0A%20%20var%20start%20%3D%20alpha.indexOf(strArr%5B0%5D)%20%3B%0A%20%20for(i%20%3D%20alpha.indexOf(strArr%5B0%5D)%3Bi%20%3C%3D%20strArr.length%3Bi%2B%2B)%7B%0A%20%20%20%20%2F%2Fconsole.log(strArr%5Bi-start%5D)%3B%0A%20%20%20%2F%2F%20console.log(alpha%5Bi%5D)%3B%0A%20%20%20%20%2F%2Fconsole.log(strArr%5Bi-start%5D%20!%3D%20alpha%5Bi%5D)%3B%0A%20%20%20%20if(strArr%5Bi-start%5D%20!%3D%20alpha%5Bi%5D)%7B%0A%20%20%20%20%20%20return%20alpha%5Bi%5D%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20%22undefined%22%3B%0A%7D%0A%0AfearNotLetter(%22yz%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function fearNotLetter(str) {
  //console.log(str);
  var alpha = ("abcdefghijklmnopqrstuvwxyz");
  strArr = str.split("");
  var start = alpha.indexOf(strArr[0]) ;
  for(i = alpha.indexOf(strArr[0]);i <= strArr.length;i++){
    //console.log(strArr[i-start]);
   // console.log(alpha[i]);
    //console.log(strArr[i-start] != alpha[i]);
    if(strArr[i-start] != alpha[i]){
      return alpha[i];
    }
  }
  return "undefined";
}

fearNotLetter("yz");

```

**Comment by erictleung** [comment]
@martin-simonini thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help) to check if your code is correct first. Hint: `undefined` is a special reserved word, not just a string. Happy coding!
