### ISSUE TITLE
Escape Sequences in Strings

### ISSUE THREAD

**Issue by imanaibolat** [FreeCodeCamp/FreeCodeCamp#10954]
![ice_screenshot_20160928-130456](https://cloud.githubusercontent.com/assets/19527886/18903675/36c4878e-857c-11e6-9194-1444e576cfb5.png)
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22FirstLine%2Fn%2F%2FSecondLine%2F%2F%2FrThirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%20%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "FirstLine/n//SecondLine///rThirdLine"; // Change this line

 I can't run my code, please help! What's wrong with my browser or with my code

```

**Comment by texas2010** [comment]
@imanaibolat, I checked your code. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding..

**Comment by shadowofbaraddun** [comment]
Escape sequences are written with backslashes not forward slashes.
