### ISSUE TITLE
what's wrong with this ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [FreeCodeCamp/FreeCodeCamp#10959]
Challenge [Counting Cards](https://www.freecodecamp.com/challenges/counting-cards#?solution=%0Avar%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20a%3B%0A%20%20%20%20switch(card)%7B%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20case%204%3A%0A%20%20%20%20case%205%3A%0A%20%20%20%20case%206%3A%20%0A%20%20%20%20%20%20%20%20count%20%2B%2B%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%207%3A%0A%20%20%20%20case%208%3A%0A%20%20%20%20case%209%3A%0A%20%20%20%20%20%20%20%20count%20%3D%200%3B%0A%20%20%20%20%20break%3B%0A%20%20%20%20case%2010%3A%0A%20%20%20%20case%20%20'J'%3A%0A%20%20%20%20case%20%20'Q'%3A%0A%20%20%20%20case%20%20'K'%3A%0A%20%20%20%20case%20%20'A'%3A%0A%20%20%20%20%20%20%20%20count%20--%3B%0A%20%20%20%20%20break%3B%0A%20%20%7D%0A%20%20if(count%20%3E%200)%7B%0A%20%20%20%20a%20%3D%20count%20%2B%20%22%20Bet%22%3B%0A%20%20%7Delse%7B%0A%20%20%20%20a%20%3D%20count%20%2B%20%22%20Hold%22%3B%0A%20%20%7D%0A%20%20return%20a%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(2)%3B%20cc(3)%3B%20cc(7)%3B%20cc('K')%3B%20cc('A')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var count = 0;

function cc(card) {
  // Only change code below this line
  var a;
    switch(card){
    case 2:
    case 3:
    case 4:
    case 5:
    case 6: 
        count ++;
      break;
    case 7:
    case 8:
    case 9:
        count = 0;
     break;
    case 10:
    case  'J':
    case  'Q':
    case  'K':
    case  'A':
        count --;
     break;
  }
  if(count > 0){
    a = count + " Bet";
  }else{
    a = count + " Hold";
  }
  return a;
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

```

**Comment by xgqfrms-GitHub** [comment]
var count = 0;

function cc(card) {
  // Only change code below this line
    var a;
    switch(card){
    case 2:
    case 3:
    case 4:
    case 5:
    case 6: 
//         count ++;
        a = 1;
      break;
    case 7:
    case 8:
    case 9:
//         count = 0;
         a = 0;
     break;
    case 10:
    case  'J':
    case  'Q':
    case  'K':
    case  'A':
//         count --;
         a = -1;
     break;
  }
  count += a;
  if(count > 0){
    a = count + " Bet";
  }else{
    a = count + " Hold";
  }
  return a;
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

**Comment by TheGr8Lemmoncawl** [comment]
After case 9, you are setting the count to 0.  Try count += 0;
