### ISSUE TITLE
Beta Site - Javascript challenges tests accept everything

### ISSUE THREAD

**Issue by zelite** [FreeCodeCamp/FreeCodeCamp#10958]
Challenge [comment-your-javascript-code](http://beta.freecodecamp.com/en/challenges/basic-javascript/comment-your-javascript-code) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js




```

![image](https://cloud.githubusercontent.com/assets/9040070/18919584/0b06461e-859f-11e6-95b0-5664e24f0f0d.png)

On the beta site, when trying to solve a javascript challenge, I can submit anything, and all tests always pass. Additionally, for example, on this first challenge, there are three tests, but there is no text describing what they do. The same happens for the remaining javascript challenges.

**Comment by dhcodes** [comment]
Closing in favor of #10966 as there is more dialogue there. Thanks for the issue @zelite
