### ISSUE TITLE
Record Collection URLs open in current window

### ISSUE THREAD

**Issue by afable** [FreeCodeCamp/FreeCodeCamp#10969]
#### Challenge Name
https://www.freecodecamp.com/challenges/record-collection

#### Issue Description
`Mozilla Developer Network` and `Manipulating Complex Objects` URLs do not open in a new tab. I assume opening in a new tab is the desired behaviour based on previous challenges I have encountered. Also, I always assumed the icon that appears after the URL name suggested this behaviour.

* Browser Name, Version:  Chrome, Version 53.0.2785.116 m (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

**Comment by erictleung** [comment]
@afable thanks for the issue. You're right. They should open up in a new tab like all the other links.

[These two lines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/6ce5f14e779673ae117de41c664fea6989750bc9/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4914-L4915) need to be edited so they have `target=\"_blank\"` within those links..

**Comment by alexanderholman** [comment]
A pull request with a fix for this has been made

**Comment by alexanderholman** [comment]
Created a new PR ([#10978](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10978)) without the issue number in the branch name.
