### ISSUE TITLE
Clicking Links in gitter containing the "#?solution=" parameter overwrites correct code and replaces it with the incorrect code.

### ISSUE THREAD

**Issue by hippybear** [FreeCodeCamp/FreeCodeCamp#10963]
#### Challenge Name
All challenges tested so far

#### Issue Description
UserA: Shares link containing the #?solution= with their incorrect solution
UserB: clicks link

![linkclicked__wrong__freecodecamp helpjavascript gitter](https://cloud.githubusercontent.com/assets/14003326/18925865/75212a26-856a-11e6-9f20-8bafec3d7359.png)

UserB[BeforeClick]
![before_free code camp](https://cloud.githubusercontent.com/assets/14003326/18925886/82a88522-856a-11e6-8283-a7eaeca53328.png)

UserB[AfterClick]
![after_free code camp](https://cloud.githubusercontent.com/assets/14003326/18925901/8d0f1b3e-856a-11e6-9fc5-6dae8afb7240.png)

#### Browser Information
* Browser Name, Version: Chrome Version 53.0.2785.116 (64-bit)
* Operating System:  Linux
* Mobile, Desktop, or Tablet: Desktop

**Comment by dhcodes** [comment]
@hippybear If you go into your profile and look at the challenge, is it still your old code? I think your code is only overridden if the code in the challenge you clicked is correct, the tests pass, and you click Submit to go to the next challenge.

**Comment by hippybear** [comment]
@dhcodes no, I have done it a few times while helping people in the gitter rooms and I revisit some of my old challenges and its all wrong

**Comment by dhcodes** [comment]
I cannot confirm. I tested this with a link in Gitter. The code was incorrect and I ran the tests. I then went to my profile and loaded my accepted solution and it was still my own from months ago. Also, I think this will be remedied by the new site update.

**Comment by hippybear** [comment]
Example link with Wrong code

https://www.freecodecamp.com/challenges/generate-random-whole-numbers-within-a-range#?solution=%2F%2F%20Example%0Afunction%20ourRandomRange(ourMin%2C%20ourMax)%20%7B%0A%0A%20%20return%20Math.floor(Math.random()%20*%20(ourMax%20-%20ourMin%20%2B%201))%20%2B%20ourMin%3B%0A%7D%0A%0AourRandomRange(1%2C%209)%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afunction%20randomRange(myMin%2C%20myMax)%20%7B%0A%20%20var%20max_min%20%3D%20Math.floor(Math.random()%20*%20(myMin%20-%20myMax%20%2B%201))%20%2B%20myMin%3B%0A%0A%20%20return%20max_min%3B%20%2F%2F%20Change%20this%20line%0A%0A%7D%0A%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0Avar%20myRandom%20%3D%20randomRange(5%2C%2015)%3B%0A

**Comment by hippybear** [comment]
Clicking on the "View Solution" from my profile does show my code. But clicking on Map and clicking the link in the map to go to that challenge still has the wrong code. My solution must be stored? Im not usually going into my profile and clicking to view my solution when trying to help people in chat. I usually go to my map or click their link.

**Comment by dhcodes** [comment]
@hippybear Your solution is stored in the database and that's what you see when you click "View Solution". What you see from the map links is stored in your browser cache. As a workaround, you could right-click and open links from Gitter in an incognito window and they would not change what's in your cache.

**Comment by Bouncey** [comment]
Or try and encourage markdown code blocks in gitter

**Comment by hippybear** [comment]
Of course we encourage people to use markdown and share their code but let's be honest some of these people are struggling to make a simple string variable and getting them to master markdown is a bit of a challenge. Maybe there is a way to trim those URLs so that the solution parameter never shows up and all we can share as a user is the /challenges/name-of-challenge and the rest gets trimmed off?

**Comment by dhcodes** [comment]
@hippybear that is the way URLs will be in the react update. I'm not sure it's worth correcting on the current site.

**Comment by hippybear** [comment]
@dhcodes Right on, I will close it out
