### ISSUE TITLE
Tail randomly outputs stale data

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#10965]
The tail will randomly output content from previous challenges in the output box. I'll try to add a gif soon. This will prevent us from being able to QA the challenges.

**Comment by BerkeleyTrue** [comment]
You'll need to reset the challenge if the tail/head/tests are changed. There is already an issue to change this.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue I've tried that. It doesn't fix the issue.

**Comment by BerkeleyTrue** [comment]
> There is already an issue to change this.

**Comment by BerkeleyTrue** [comment]
I'm closing not because I don't believe you, I'm closing this as a duplicate

See: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10517

**Comment by QuincyLarson** [comment]
OK - thanks for clarifying.
