### ISSUE TITLE
what's wrong with this ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [FreeCodeCamp/FreeCodeCamp#10962]
Challenge [Profile Lookup](https://www.freecodecamp.com/challenges/profile-lookup#?solution=%0A%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intriguing%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%0A%5D%3B%0Afunction%20lookUpProfile(firstName%2C%20prop)%7B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20a%3Dfalse%2Cb%3Dfalse%2Cx%3B%0A%20%20for(var%20i%3D0%3Bi%20%3C%20contacts.length%3Bi%2B%2B)%7B%0A%20%20%20%20if(firstName%20%3D%3D%3D%20contacts%5Bi%5D.firstName)%7B%0A%20%20%20%20%20%20a%20%3D%20true%3B%0A%20%20%20%20%7Delse%20if(contacts%5Bi%5D.hasOwnProperty(prop))%7B%0A%20%20%20%20%20%20b%20%3D%20true%3B%0A%20%20%20%20%20%20x%20%3D%20contacts%5Bi%5D%5Bprop%5D%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20if(%20a%20%3D%3D%3D%20true%20%20%26%26%20b%20%3D%3D%3D%20true)%7B%0A%20%20%20%20return%20x%3B%0A%20%20%20%20%2F%2Freturn%20the%20%22value%22%20of%20that%20property.%0A%20%20%7Delse%20if(a%20%3D%3D%3D%20true%20%26%26%20b%20%3D%3D%3D%20false)%7B%0A%20%20%20%20return%20%22No%20such%20property%22%3B%0A%20%20%7Delse%20if(a%20%3D%3D%3D%20false%20%26%26b%20%3D%3D%3D%20true)%7B%0A%20%20%20%20return%20%22No%20such%20contact%22%3B%0A%20%20%7Delse%7B%0A%20%20%20%20return%3B%0A%20%20%7D%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0AlookUpProfile(%22Akira%22%2C%20%22likes%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];
function lookUpProfile(firstName, prop){
// Only change code below this line
  var a=false,b=false,x;
  for(var i=0;i < contacts.length;i++){
    if(firstName === contacts[i].firstName){
      a = true;
    }else if(contacts[i].hasOwnProperty(prop)){
      b = true;
      x = contacts[i][prop];
    }
  }
  if( a === true  && b === true){
    return x;
    //return the "value" of that property.
  }else if(a === true && b === false){
    return "No such property";
  }else if(a === false &&b === true){
    return "No such contact";
  }else{
    return;
  }
// Only change code above this line
}
// Change these values to test your function
lookUpProfile("Akira", "likes");

```

**Comment by xgqfrms-GitHub** [comment]
I just confused of the test cases 2 & 3!

There should be the same result?

> 
"Sherlock", "likes" should return ["Intriguing Cases", "Violin"]
"Harry","likes" should return an array

```js
    
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];
function lookUpProfile(firstName, prop){
// Only change code below this line
  var a=false,b=false,x;
  for(var i=0;i < contacts.length;i++){
    if(firstName === contacts[i].firstName){
      a = true;
    }
    if(contacts[i].hasOwnProperty(prop) === true){
      b = true;
      x = contacts[i][prop];
    }
  }
  if( a === true  && b === true){
    return x;
    //return the "value" of that property.
  }else if(a === true && b === false){
    return "No such property";
  }else if(a === false &&b === true){
    return "No such contact";
  }else{
    return;
  }
// Only change code above this line
}
// Change these values to test your function
lookUpProfile("Akira", "likes");

```
![a](https://cloud.githubusercontent.com/assets/18028768/18926680/58f3678e-85eb-11e6-9d07-eb23a326ccbe.PNG)

**Comment by xgqfrms-GitHub** [comment]
After testing on Chrome, I found that here some bugs of my code!
![likes-error](https://cloud.githubusercontent.com/assets/18028768/18927241/abf4c336-85ed-11e6-8f24-d6eded638fa1.PNG)

**Comment by xgqfrms-GitHub** [comment]
This is the passed code!
```js
    
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];
function lookUpProfile(firstName, prop){
// Only change code below this line
  var a=false,b=false,x;
  for(var i=0;i < contacts.length;i++){
    if(firstName === contacts[i].firstName && contacts[i].hasOwnProperty(prop) === true)     {
      a = true;
      b = true;
      x = contacts[i][prop];
    }
    if(firstName === contacts[i].firstName){
      a = true;
    }
    if(contacts[i].hasOwnProperty(prop) === true)     {
      b = true;
    }
  }
  if( a === true  && b === true){
    return x;
    //return the "value" of that property.
  }
  if(a === true && b === false){
    return "No such property";
  }else if(a === false &&b === true){
    return "No such contact";
  }else{
    return;
  }
// Only change code above this line
}
// Change these values to test your function
lookUpProfile("Akira", "likes");

```

**Comment by xgqfrms-GitHub** [comment]
OK, just coding!

**Comment by xgqfrms-GitHub** [comment]
error of get  JSON nested JSON?
```js
var collection = {
			    "2548": {
			      "album": "Slippery When Wet",
			      "artist": "Bon Jovi",
			      "tracks": [ 
			        "Let It Rock", 
			        "You Give Love a Bad Name" 
			      ]
			    },
			    "2468": {
			      "album": "1999",
			      "artist": "Prince",
			      "tracks": [ 
			        "1999", 
			        "Little Red Corvette" 
			      ]
			    },
			    "1245": {
			      "artist": "Robert Palmer",
			      "tracks": [ ]
			    },
			    "5439": {
			      "album": "ABBA Gold"
			    }
			};

			// get JSON length
			var count = Object.keys(collection).length;
```

**Comment by xgqfrms-GitHub** [comment]
coming soon...

**Comment by xgqfrms-GitHub** [comment]
![Uploading JSON-dot && JSON  bracket notation(string).PNG…]()

**Comment by texas2010** [comment]
@xgqfrms-GitHub, Did you go to Help javascript chat room first?

**Comment by xgqfrms-GitHub** [comment]
**what's wrong with this?**
![xx](https://cloud.githubusercontent.com/assets/18028768/18973524/82ce1d02-86d0-11e6-8c76-929cc1dc0482.PNG)

**Comment by BerkeleyTrue** [comment]
@xgqfrms-GitHub 

The issue tracker is for reporting bugs only. If this is an issue for help with a challenge, please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
