### ISSUE TITLE
Waypoint: Turn an Image into a Link Bug

### ISSUE THREAD

**Issue by JC713** [FreeCodeCamp/freecodecamp#1097]
Challenge http://www.freecodecamp.com/challenges/waypoint-turn-an-image-into-a-link has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I am not sure if this is a bug, but I thought it was very odd so decided to report it just in case.

Literally all I did for this challenge was turn this line of code:
![screen shot 1](https://cloud.githubusercontent.com/assets/7388203/8317669/4918a86e-19cd-11e5-919d-911c7f47e225.png)

into this: ![screen shot 3](https://cloud.githubusercontent.com/assets/7388203/8317674/5003e698-19cd-11e5-8a5a-9c6a89bcbd29.png)

It did not look at all like the example code where I had to define and image with a link. Instead, all I had to do was add the < after ![screen shot 4](https://cloud.githubusercontent.com/assets/7388203/8317696/6d9a5e4e-19cd-11e5-8787-ebd3ca5d3525.png). I am pretty sure this is a bug. Plus, the ![screen shot 1](https://cloud.githubusercontent.com/assets/7388203/8317706/814019f2-19cd-11e5-9ac0-d7aa789eebc2.png) tags were highlighted after I accomplished this: 
![screen shot 2](https://cloud.githubusercontent.com/assets/7388203/8317591/bad30cf2-19cc-11e5-9672-55ab45b65aea.png)

Sorry if this isn't a bug. I just thought it was very bizarre and did not follow the directions I read. Thanks.

-JC

**Comment by alexlincoln** [comment]
Can confirm adding a single `<` character to the beginning of `cat photos` does pass the challenge and replicates the bug

![2015-07-05-224406_1097x867_scrot](https://cloud.githubusercontent.com/assets/6338358/8516923/66924d86-236f-11e5-98b3-9d68112354ce.png)

**Comment by benmcmahon100** [comment]
If just thrown up a fix for this and hopefully it will be included in staging before in is deployed

**Comment by jundc1006** [comment]
I think It's actually a bug because it needs a closing > after the catphotos. But instead it will accept it as correct when you remove the closing > .

**Comment by sasory21** [comment]
very strange , but it works
