### ISSUE TITLE
FreeCodeCamp : Build a Tribute Page

### ISSUE THREAD

**Issue by TuanAnhVu** [FreeCodeCamp/FreeCodeCamp#10971]
Challenge [Build a Tribute Page](https://www.freecodecamp.com/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by erictleung** [comment]
@TuanAnhVu can you give us more information about your issue? If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help).

**Comment by atjonathan** [comment]
Closing as stale.
