### ISSUE TITLE
Test cases not working

### ISSUE THREAD

**Issue by VitaminVolcano** [FreeCodeCamp/FreeCodeCamp#10970]
Challenge [Drop it](https://www.freecodecamp.com/challenges/drop-it#?solution=function%20dropElements(arr%2C%20func)%20%7B%0A%20%20%2F%2F%20Drop%20them%20elements.%0A%20%20return%20arr.filter(func)%3B%0A%7D%0A%0AdropElements(%5B1%2C%202%2C%203%5D%2C%20function(n)%20%7Breturn%20n%20%3C%203%3B%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.90 Safari/537.36 Vivaldi/1.4.589.11</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function dropElements(arr, func) {
  // Drop them elements.
  return arr.filter(func);
}

dropElements([1, 2, 3], function(n) {return n < 3; });

```
![bug](https://cloud.githubusercontent.com/assets/11861629/18943708/9d038270-8621-11e6-9ffd-b049b3fbe7d3.PNG)

Cases 2 & 5 not producing expected results. 
- Case 2 should produce [1,1] as n === 1 can't produce true for 0.
- Case 5 should produce [3,9] as n > 2 can't produce true for 2.

Thanks you very much for the great interactive course so far! I'm certainly learning a lot!

**Comment by VitaminVolcano** [comment]
Misunderstood the instructions.

**Comment by texas2010** [comment]
@VitaminVolcano, no problem.  you could go to [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need a help.

Happy Coding.
