### ISSUE TITLE
Bonfire: Drop it - correct solution but wrong answer?

### ISSUE THREAD

**Issue by bryanle** [FreeCodeCamp/FreeCodeCamp#1098]
After I submit my code, the bonfire gives me 2 different outputs as the solution. In the pictures I've attached, the actual output matches the answer that the bonfire expects, however the bonfire interprets it differently.

```
var arr1 = [];
var merged = [];
function drop(arr, func) {
for (ar = 0; ar < arr.length; ar++) {
    arr1.push(new Array());
}
for (j = 0; j < arr.length; j++) {
    arr1[j].push(arr[j]);
}
    for (i = 0; i < arr.length; i++) {
        if (arr.some(func) === false) {
            return [];
        }
        if (arr1[i].some(func) === true) {
        merged = merged.concat.apply(merged, arr1);
            return merged;
        }
        while (arr1[i].some(func) === false) {
            arr1.shift();
        }
    }
}
drop([1, 2, 3], function(n) {return n > 0; });
```
![screen shot 2015-06-23 at 6 52 25 pm](https://cloud.githubusercontent.com/assets/8146707/8319100/106e5cc8-19d9-11e5-854d-6df066f001a2.png)
![screen shot 2015-06-23 at 6 51 40 pm 1](https://cloud.githubusercontent.com/assets/8146707/8319102/18c97290-19d9-11e5-9550-b9ad0a09bee0.png)
![screen shot 2015-06-23 at 6 52 13 pm](https://cloud.githubusercontent.com/assets/8146707/8319105/1d804ade-19d9-11e5-9bc1-7b689a84df7c.png)

**Comment by benschenker** [comment]
Thanks @bryanle!

It looks like you need to bring those array declaration:
```
var arr1 = [];
var merged = [];
```
inside the function body

I'm going to close this, but feel free to reopen if you have any questions
