### ISSUE TITLE
Typo in Say Hello to HTML Elements

### ISSUE THREAD

**Issue by computerluca** [FreeCodeCamp/FreeCodeCamp#10980]
Challenge [say-hello-to-html-elements](http://beta.freecodecamp.com/en/challenges/html5-and-css/say-hello-to-html-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

In the description of the test case there is a typo 
Your h1 element should have the text "Hello World".');
should be
Your h1 element should have the text "Hello World".

**Comment by erictleung** [comment]
@computerluca thanks for the issue. Yes, that is a small typo.

[This line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/4e893aaf088cd0d4c1814a7df293d5bd09e076c7/seed/challenges/01-front-end-development-certification/html5-and-css.json#L28) needs to be changed.

**Comment by Deadpool37** [comment]
#8ed74570eaca2db6a8076fcc65de1b164628a14b
