### ISSUE TITLE
Javascript: Sift through Text with Regular Expressions -- not accepting actual word pattern expression

### ISSUE THREAD

**Issue by decksterr** [FreeCodeCamp/FreeCodeCamp#10989]
#### Challenge Name
Sift through Text with Regular Expressions
https://www.freecodecamp.com/challenges/sift-through-text-with-regular-expressions

#### Issue Description
The instructions clearly state 
> Select all the occurrences of the **word** _and_ in _testString_.

Hence i think the following regex ```/\band\b/gi``` or ```/(?:\b)and(?:\b)/gi``` where one actually considers the word boundaries in the expression should also be a valid answer, not just ```/and/gi```.

Sorry if this a duplicate (and it probably is), but definitely should be fixed IMHO. Could turn down some dedicated beginners.

#### Code
```js
var expression = /\band\b/gi;
var andCount = testString.match(expression).length;
```

**Comment by erictleung** [comment]
@decksterr thanks for the issue. I agree that the tests should be better at allowing other regular expression patterns that solve the challenge.

**Comment by newyork-anthonyng** [comment]
@erictleung If nobody else has worked on this yet, I'd like to make work on it and make a PR.

**Comment by texas2010** [comment]
@newyork-anthonyng, you can work on that.
