### ISSUE TITLE
Having trouble with <li> tags </li>

### ISSUE THREAD

**Issue by princessdianna1989** [FreeCodeCamp/freecodecamp#1099]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-font-awesome-icons-all-of-our-buttons has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I am having trouble with closing </li> tags. I have entered them right and double checked but it keeps saying I haven't closed the <li> tags. Heres the screenshot: 

![image](https://cloud.githubusercontent.com/assets/13025326/8320128/7984af16-19dc-11e5-8e07-706f9a7d860f.png)

**Comment by LumenTeun** [comment]
Sorry, but it doesn't say to close your `<li>` tags, it says to close your `<i>` tags ;)
Remember to close this issue.

**Comment by rtpHarry** [comment]
And also you missed the `>` of the opening `<i>` tag.

**Comment by princessdianna1989** [comment]
Thanks! I fixed it. :)

**Comment by LumenTeun** [comment]
Great to hear @princessdianna1989 :) Remember to close this issue.

**Comment by ahstro** [comment]
Could someone close this? Or could GitHub just update their permissions so I can close things..
