### ISSUE TITLE
Problem in Description. Challenge "Compound Assignment With Augmented Addition"

### ISSUE THREAD

**Issue by riteshtiwari** [FreeCodeCamp/FreeCodeCamp#10998]
#### Challenge Name

https://www.freecodecamp.com/challenges/compound-assignment-with-augmented-addition

#### Issue Description

The description isn't correct. Currently, its
myVar += 5; will add 5 to myVar.
It should be 
myVar += 5; will add 5 to myVar and assign it back to myVar

**Comment by dhcodes** [comment]
While true, I actually think this explanation might be more confusing to a camper new to JS.

**Comment by erictleung** [comment]
I agree with @dhcodes on the matter. We can try to improve the wording as much as we can but I think a code example is best. Maybe we can add this into the description.

```js
var myVar = 1;
myVar += 5;
myVar; // Returns 6
```

**Comment by Manish-Giri** [comment]
Can I take this up?

**Comment by erictleung** [comment]
@Manish-Giri go for it!

**Comment by andmckvr13** [comment]
if @Manish-Giri is no longer interested in the fix I would be

**Comment by Manish-Giri** [comment]
@andmckvr13 it's in progress

**Comment by sahilkhurana19** [comment]
It has been six days since the PR and the issue has not been resolved. Can i take it up and make a PR?

**Comment by Manish-Giri** [comment]
@sahilkhurana19 I've been a bit busy over the last week, but I'm still doing it.

**Comment by sahilkhurana19** [comment]
@Manish-Giri  No worries, I'll look for other issues. :smile:

**Comment by Manish-Giri** [comment]
I submitted a new PR for this challenge, please disregard the previous PR #11093.

**Comment by RomingArt** [comment]
I wrote this code and it passed, but I am not sure about my syntax of it makes sense. 
`var a = 3;
var b = 17;
var c = 12;

// Only modify code below this line

a = a += 12;
b = b += 9;
c = c += 7;
`

**Comment by Orsina** [comment]
as a newbie, was loving the html ect then came to this chapter and OMG im ready to chuck the whole thing in i cant understand any of it totally confusing hunting for answers on google is not good as i dont understand how to atain the answer for myself argg

**Comment by Radlerz1** [comment]
Of coarse its confusing at first it takes time and determination

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
