### ISSUE TITLE
Camperbot fails to give points if there is a bracket before a "thanks"

### ISSUE THREAD

**Issue by tf2manu994** [FreeCodeCamp/FreeCodeCamp#10992]
https://gitter.im/FreeCodeCamp/FreeCodeCamp?at=57edcc09d56b91170dfc75cd

**Comment by rafid059** [comment]
I think this issue should be opened here:  https://github.com/FreeCodeCamp/camperbot/issues

**Comment by tf2manu994** [comment]
Correct.
