### ISSUE TITLE
issue joining forum

### ISSUE THREAD

**Issue by vdash2** [FreeCodeCamp/FreeCodeCamp#10990]
Regardless if I choose sign up or sign in, and I have tried on OS X 10.12 and Windows 10, I get the same error.  I Have tested in Safari, Chrome, Microsoft Edge. 

<img width="906" alt="screen shot 2016-09-29 at 9 15 31 pm" src="https://cloud.githubusercontent.com/assets/22217542/18977929/b19b06de-868c-11e6-83dd-d0d4c1a6a6bc.png">
<img width="1075" alt="screen shot 2016-09-29 at 9 15 49 pm" src="https://cloud.githubusercontent.com/assets/22217542/18977930/b1ad0d02-868c-11e6-8eb9-b89c774e7b3e.png">

I'm am not sure what else can I do to over come the problem.

**Comment by xelab1090** [comment]
I opened with Mozilla Firefox, and it worked for me.

**Comment by texas2010** [comment]
@vdash2, please use this. here link is forum issue. https://github.com/FreeCodeCamp/discourse/issues.
