### ISSUE TITLE
 $("#target4").html("<em> target4 </em>"); don't work ?

### ISSUE THREAD

**Issue by dev13579** [FreeCodeCamp/FreeCodeCamp#10997]
Challenge [Change Text Inside an Element Using jQuery](https://www.freecodecamp.com/challenges/change-text-inside-an-element-using-jquery#?solution=%0Afccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22%23target1%22).css(%22color%22%2C%20%22red%22)%3B%0A%20%20%20%20%24(%22%23target4%22).html(%22%3Cem%3E%20target4%20%3C%2Fem%3E%22)%3B%0A%20%20%20%20%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").html("<em> target4 </em>");
    
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

correct me if i am wrong
tks a lot!

**Comment by Deadpool37** [comment]
Hey @dev13579 tell me if this works
`$("#target4").html("<em>#target4</em>");`
Make sure you are sending the correct text to the screen and that there are no whitespaces between the tags and the text

**Comment by Dayfiri** [comment]
![screenshot at 2016-09-30 13 51 58](https://cloud.githubusercontent.com/assets/16082563/18990862/36c8d90c-8715-11e6-916c-e1e7834d7620.png)

This works. Like @Deadpool37 said above me, write it without the whitespaces -> $("#target4").html("<em>#target4</em>");

**Comment by dhcodes** [comment]
@dev13579 You have an error in your code. Please consider clicking the help button to get feedback on your code in the chat room. Happy coding!

**Comment by texas2010** [comment]
@Deadpool37, please stop give answer to them on any issues.  this place is not for help them

**Comment by Deadpool37** [comment]
@texas2010 The guy had already completed the code and was almost correct except for the fact that he didn't know that whitespaces in between tags are counted.

**Comment by dhcodes** [comment]
@Deadpool37 it's not that we are discouraging your helpfulness, it's just that this venue is for legitimate bugs/problems with the site, not code errors. Had OP asked in the chat room, someone likely would've been able to point OP in the right direction as well. The [Gitter Help Chat](https://gitter.im/FreeCodeCamp/Help) or one of the other corresponding rooms is the best place to help other campers with code.

**Comment by aphilsmith** [comment]
As stated, the exercise is confusing. It gives the example:
$("h3").html("<em>jQuery Playground</em>");
But asks to change the button text, using the function ,text(). However, the checklist says to use the function .html and NOT ,text to change the text. If so, what should be selected instead of the h3 element from the example? I tried $("#target4"") but to no avail, Stuck,

**Comment by KaeKay** [comment]
I found it really confusing as well. Thankfully I've passed that stage. I tried $("#button").html("<em>#target4</em>");  also because of the example
