### ISSUE TITLE
Grab larger Twitter image?

### ISSUE THREAD

**Issue by brndnb** [FreeCodeCamp/freecodecamp#11]
The new bio's page needs a larger image than is currently being pulled during sign-up with Twitter. Right now, the default image is blurry. Not sure if this is also happening with other authorization methods. It is an easy fix by changing it on the form, but I'm assuming this could be a easier user experience.

For example, the image from my original Twitter sign-up pulled this image "normal" image:
https://pbs.twimg.com/profile_images/539515557184167936/JqJXzV9x_normal.jpeg

But it would be better to go with the original:
https://pbs.twimg.com/profile_images/539515557184167936/JqJXzV9x.jpeg

Here is a link to the twitter documentation specific to these image sizes: https://dev.twitter.com/overview/general/user-profile-images-and-banners

**Comment by brndnb** [comment]
Submitted PR if you're interested.

**Comment by terakilobyte** [comment]
Recommend closing this issue.
