### ISSUE TITLE
Bug with FreeCodeCamp and Safari 8

### ISSUE THREAD

**Issue by JC713** [FreeCodeCamp/FreeCodeCamp#1100]
Hello, this bug has been bothering me for a while and I wanted to report it. Basically the bug goes as follows: randomly, as I am typing text, the objectives disappear and reappear. I have attached a video below to exemplify it. The bug may be associated with Safari.

Link to video exemplifying the bug: https://www.dropbox.com/s/ycw5xqv073tnmiz/Bug%20report.mp4?dl=0

Sorry for the horrible quality. Dropbox compressed the video a ton and I cannot upload videos straight to Github. The issue is highly visible so it should not be an issue :). Thanks.

System specs: iMac (21.5-inch, Mid 2010), OS X Yosemite 10.10.3, Safari 8.0.6 (Installed extensions: uBlock, 1Password, and Pushbullet).

Thanks for the help. I hope this bug can be solved because it is quite distracting.

**Comment by benschenker** [comment]
Thanks @JC713.

This issue is stale, sorry we never go to it!  That video is no longer available too.

I'm going to close this for now but if it is still a problem please reopen it.
