### ISSUE TITLE
Test cases allow for erroneous code to pass through.

### ISSUE THREAD

**Issue by jadczakd** [FreeCodeCamp/FreeCodeCamp#11009]
Challenge [Smallest Common Multiple](https://www.freecodecamp.com/challenges/smallest-common-multiple#?)

I hope that my comments in the code are enough. What's going on is basically what is described here - > https://youtu.be/Kl9gt33Hyg0 -> you can witness me finding the error as well. 
the code looking for the smallest common multuple of a range of numbers using prime factorization

My code:
```javascript
function smallestCommons(arr) {
  //makes sure they are in ascending order
  arr.sort();
  // establishes the range of numbers
  let allDividers =[];
  for(let k=arr[0];k<=arr[1];k++){
    allDividers.push(k);
  };
  //spreads the range
 let numsToCheck = [...allDividers];
  //
 let arrayToUse =[];

  // compares two arrays and returns one array with the highest occurance of each elements
  
  let compareTwoArrays = function(one, two){
  let count = new Map,
    result = [];
    [one, two].forEach(function (a, i, aa) {
    a.forEach(function (b) {
        var item = count.get(b);
        if (!item) {
            item = Array.apply(null, { length: aa.length }).fill(0);
            count.set(b, item);
        }
        item[i]++;
    });
  });

  count.forEach(function (v, k) {
    var l = Math.max.apply(null, v);
    while (l--) {
        result.push(k);
      }
  });
    return result;
  };
    
  //finds prime factors- whoah really? 
  function findPrimeFactors(num){
   let arrayProduced = [];
   for(let i = 2;i <= num/2;i++){
     while(num%i===0){
       num=num/i;
       arrayProduced.push(i);
     }}
      if(num>1){
     arrayProduced.push(num);
   }
  let answer2= compareTwoArrays(arrayToUse, arrayProduced);
  arrayToUse = answer2;
  answer2=[];
 }; 
    
  for(let i = 0 ; i<allDividers.length;i++){
   findPrimeFactors(allDividers[i]);
   }

  return arrayToUse.reduce((x,y)=>x*y);
}
  
smallestCommons([252,312]);
```
here's a corrected version, pay attention to the first couople of lines only.

```javascript
function smallestCommons(arr) {
  //make sure the array is in ascending order.
  let maxNum = Math.max(...arr);
  let minNum = Math.min(...arr);
  arr=[minNum,maxNum];

  let allDividers =[];
  for(let k=arr[0];k<=arr[1];k++){
    allDividers.push(k);
  };
  //spreads the range
 let numsToCheck = [...allDividers];
  //
 let arrayToUse =[];

  // compares two arrays and returns one array with the highest occurance of each elements
  
  let compareTwoArrays = function(one, two){
  let count = new Map,
    result = [];
    [one, two].forEach(function (a, i, aa) {
    a.forEach(function (b) {
        var item = count.get(b);
        if (!item) {
            item = Array.apply(null, { length: aa.length }).fill(0);
            count.set(b, item);
        }
        item[i]++;
    });
  });

  count.forEach(function (v, k) {
    var l = Math.max.apply(null, v);
    while (l--) {
        result.push(k);
      }
  });
    return result;
  };
    
  //finds prime factors- whoah really? 
  function findPrimeFactors(num){
   let arrayProduced = [];
   for(let i = 2;i <= num/2;i++){
     while(num%i===0){
       num=num/i;
       arrayProduced.push(i);
     }}
      if(num>1){
     arrayProduced.push(num);
   }
  let answer2= compareTwoArrays(arrayToUse, arrayProduced);
  arrayToUse = answer2;
  answer2=[];
 }; 
    
  for(let i = 0 ; i<allDividers.length;i++){
   findPrimeFactors(allDividers[i]);
   }
// returns the reduced array of filtered prime factors
  return arrayToUse.reduce((x,y)=>x*y);
}
  
smallestCommons([5,1]);
```
Now to recreate the error try typing try calling the first supplied code with arguments that wouldn't get sorted in ascending order. eg. 
```javascript
smallestCommons([2,15]);
```
I know this is the hard and not so common way to solve this challange, it leaves room for error nevertheless. I have realised that I made a mistake there 8 hours after submitting and passing all the test cases. 

Solution suggestion : Include smallestCommons([2,15]); or any other with array of arguments that wouldn't get sorted into ascending order with arr.sort(); into the the test cases.

**Comment by karuppiah7890** [comment]
I think it's fair enough to add an extra test case to check if the camper has used arr.sort() for sorting the two numbers in the given array; which is wrong as arr.sort() sorts in alphabetical order if no comparison function is provided. @dhcodes @Bouncey Your comments ?

**Comment by Bouncey** [comment]
Sounds good to me. Let's add a test for smallestCommons([2, 10]), which should equal 2520.

**Comment by karuppiah7890** [comment]
I will take this up ?

**Comment by karuppiah7890** [comment]
I have taken this up and solved the issue. But I couldn't test this at localhost:3001 due to this #11007. I checked the working at localhost:3000. It works fine. Should I make the pull request @Bouncey ? Or wait for the #11007 bug fix to test how it works even at localhost:3001 ?

**Comment by Bouncey** [comment]
@karuppiah7890 We would be better waiting so you can test locally

**Comment by karuppiah7890** [comment]
@Bouncey Okay! :+1:

**Comment by karuppiah7890** [comment]
@Bouncey Shall I make a PR after testing this at `localhost:3000` as discussed in #11007 . Or is #11007 gonna be reopened ?
