### ISSUE TITLE
Bug in "Convert HTML Entities" challenge

### ISSUE THREAD

**Issue by anischyros** [FreeCodeCamp/FreeCodeCamp#11005]
Challenge [Convert HTML Entities](https://www.freecodecamp.com/challenges/convert-html-entities#?solution=function%20convertHTML(str)%20%0A%7B%0A%20%20%20%20return%20str.replace(%2F%26%2Fg%2C%20%22%26amp%3B%22).replace(%2F%3C%2Fg%2C%20%22%26lt%3B%22).replace(%2F%3E%2Fg%2C%20%22%26gt%3B%22).replace(%2F%22%2Fg%2C%20%22%20%26quot%3B%22).replace(%2F%27%2Fg%2C%20%22%26apos%3B%22)%3B%0A%0A%7D%0A%0AconvertHTML(%22Dolce%20%26%20Gabbana%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function convertHTML(str) 
{
    return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, " &quot;").replace(/'/g, "&apos;");

}

convertHTML("Dolce & Gabbana");

```

My JavaScript code most definitely will return "Stuff in  &quot;quotation marks &quot;" when
convertHTML('Stuff in "quotation marks"') is called, and this is demonstrated in the Firefox Scratchpad tool, but the test does not seem to detect this.

**Comment by dhcodes** [comment]
@anischyros you have a small error in your code. Please consider asking for help in the [HelpJavascript room](https://gitter.im/FreeCodeCamp/HelpJavaScript) on Gitter. It also might be helpful to put the test case into the editor to see the output.
