### ISSUE TITLE
The order sisn't changed for h1 h2 or p still not working

### ISSUE THREAD

**Issue by Callmemaci** [FreeCodeCamp/FreeCodeCamp#11004]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%0A%3C!--h1%3EHello%20World%3C%2Fh1--%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3C!--p%3EHello%20Paragraph%3C%2Fp--%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html


<!--h1>Hello World</h1-->

<h2>CatPhotoApp</h2>

<!--p>Hello Paragraph</p-->

```

**Comment by texas2010** [comment]
@Callmemaci, Thanks for reporting this. I checked your code. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding..
