### ISSUE TITLE
Merge Wiki Contributing article into Contributing.md

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#11006]
We want a single source of truth that reflects all the steps involved in setting up Free Code Camp locally and contributing to it. That single document should be Contributing.md

Currently, we also have http://forum.freecodecamp.com/t/how-to-fork-and-maintain-a-local-instance-of-free-code-camp/19116, which is a much more comprehensive article. 

We should do the following:
- [ ] work all the points from the wiki article into this repo's Contributing.md
- [ ] update the wiki article, clearing its instructions and instead referring readers to this repo's Contributing.md

**Comment by adamisntdead** [comment]
I'm up for this?

**Comment by QuincyLarson** [comment]
@adamisntdead great! Take a crack at it :) Happy Hacktoberfest!

**Comment by RakshithNM** [comment]
Is the work on this complete?

**Comment by Web-Dev-Rich** [comment]
@adamisntdead is this still in progress because I would _love_ to do it?

**Comment by adamisntdead** [comment]
I am actually still working on this, done about half way
