### ISSUE TITLE
How do I change the font-size of the p element to 16px?

### ISSUE THREAD

**Issue by foreverifilm** [FreeCodeCamp/FreeCodeCamp#11000]
<style>
  .red-text {
    color: red;
    font-size:16px;
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p class>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by dhcodes** [comment]
@foreverifilm Please use the help button to ask for help from fellow campers in the Gitter chat room. They'll be able to point you in the right direction.

**Comment by foreverifilm** [comment]
Where is the help button at? thank you.

**Comment by dhcodes** [comment]
On the challenge, it should be below the "Run Tests" button.
