### ISSUE TITLE
Code Editor Not Rendering (Local instance)

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#11007]
After pulling down the latest staging, The code editor will not render.

In my console I have:
`Refused to execute script from 'http://localhost:3001/js/bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

![screenshot from 2016-09-30 23-31-36](https://cloud.githubusercontent.com/assets/18572518/19008933/ea3c07b0-8766-11e6-8568-24b9fcb6604c.png)

Ubuntu 16.04
Chrome version 53.0.2785.113
node 6.4.0
npm 3.10.3
mongod 3.2.9

**Comment by dhcodes** [comment]
@Bouncey Are you on > Node 6 and NPM 3? Also, you might need to run `rm -rf node_modules` and then `npm install` since some stuff has been changed over the past week.

**Comment by Bouncey** [comment]
I just tried that and no change

**Comment by karuppiah7890** [comment]
Same bug over here!

**Comment by karuppiah7890** [comment]
But the editor at localhost:3000 works!

**Comment by hristijankiko** [comment]
I also have this issue but i just installed freecodecamp on my local machine few hours ago. When i try to load a challenge on localhost:3001 i get this error in console http://image.prntscr.com/image/5006c694534a468eb7301836f4067604.png

**Comment by ltegman** [comment]
I can't repro this specific issue, but I get an infinitely refreshing page if I use 3001.

@karuppiah7890 If I understand correctly it should be that `3000` is the webpack dev server version and `3001` is the vanilla node server version.

**Comment by karuppiah7890** [comment]
@ltegman Thanks ! I guess I gotta check on how Webpack works and also see the overall working of FreeCodeCamp to know how stuff works, to start solving issues! 

Actually, it would be good to have a "Code Overview" page for new contributors. Think on it. I guess I will raise an issue and start a discussion.

**Comment by marhyorh** [comment]
@Bouncey @karuppiah7890 i had this issue some while ago, so i made this [pull request](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10183) which temporary solves that. Then, i Berkeley made me to understand that, they're served on different ports. What i did was to:
[x] Clear the node_modules
[x] Reinstall npm dependencies
[x] Install bower deps
[x] Run npm run only-once
[x] Run gulp

Then it finally worked!

**Comment by karuppiah7890** [comment]
@marhyorh I reinstalled npm dependencies like @dhcodes advised. But I didn't install the bower deps. 

And yeah, bower stuff makes sense. Our code editor is actually Code Mirror right ? A bower component. Probably some issues with that part. I will try this and get back.

**Comment by BerkeleyTrue** [comment]
@Bouncey Sounds like dev server is not intercepting the request for the bundle. Make sure you have the latest and you use `gulp` or `npm start` to run it.

**Comment by karuppiah7890** [comment]
@BerkeleyTrue Hey, I have the latest modules. I still get the error when I use `gulp` . I see that `localhost:3001/js/bundle.js` gets redirected to `localhost:3001/en/bundle.js` and gives a 404 HTML page. I don't know why the interception is not happening. It happens at localhost:3000 though, which is actually the web pack dev server version from what @ltegman says.

**Comment by marhyorh** [comment]
@karuppiah7890 Don't run any other command asides gulp. Then navigate to http://localhost:3000 and you're good to go!

**Comment by karuppiah7890** [comment]
@marhyorh `http://localhost:300` works fine! I am talking about `http://localhost:3001`. I heard I should check the working of the site at port 3001.

**Comment by Bouncey** [comment]
@BerkeleyTrue 

`webpack-dev-middleware @ 1.8.3`
`browser-sync @ 2.9.12`

I noticed during the gulp build:
```sh
[BS] Proxying: http://localhost:3001
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.0.23:3000
 -------------------------------------
          UI: http://localhost:3002
 UI External: http://192.168.0.23:3002
 -------------------------------------
```

Could the proxy be throwing everything out?

Would it be worth removing `3001` and updating `CONTRIBUTING.md` to point people to `3000`, which seems to be working?

**Comment by marhyorh** [comment]
Webpack dev middleware is served through http://localhost:3001. The docs should be updated to use http://localhost:3000 instead of the proxy :+1:

**Comment by karuppiah7890** [comment]
@Bouncey  @ltegman @dhcodes So, we just create PRs if the code works fine in `localhost:3000` ? And by the way, a lot of stuff don't work in `localhost:3001`, like the map page - `localhost:3001/en/map`, the search didn't work properly in it. Some react problems I guess, I don't know. And even clicking on the Map link while solving challenges, lead me to a new page instead of showing a sidebar on the right, like it happens in the production site and in `localhost:3000`.

**Comment by BerkeleyTrue** [comment]
Wow, didn't realize 3001 was used in the docs. Yes 3000 should always be the default now.

**Comment by karuppiah7890** [comment]
@BerkeleyTrue Thanks for confirming!
