### ISSUE TITLE
Use the Twitchtv JSON API: missing link

### ISSUE THREAD

**Issue by janschreiber** [FreeCodeCamp/FreeCodeCamp#11011]
Challenge [Use the Twitchtv JSON API](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api) has an issue.
Instruction no. 11 reads "UPDATE: Due to a change in conditions on API usage explained here, use the sample API response we provide at" Apparently a link to said sample response is missing.

**Comment by atjonathan** [comment]
@janschreiber, this has already been fixed 😄
We should be pushing this change to production shortly!
