### ISSUE TITLE
Calculation Bug in "Return a Value from a Function with Return"

### ISSUE THREAD

**Issue by lovelylion** [FreeCodeCamp/FreeCodeCamp#11019]
Challenge [Return a Value from a Function with Return](https://www.freecodecamp.com/challenges/return-a-value-from-a-function-with-return#?solution=%0A%2F%2F%20Example%0Afunction%20minusSeven(num)%20%7B%0A%20%20return%20num%20-%207%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Afunction%20timesFive(lol)%7B%0A%20%20return%20lol%20*%205%3B%0A%7D%0A%0AtimesFive(1000)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function minusSeven(num) {
  return num - 7;
}

// Only change code below this line

function timesFive(lol){
  return lol * 5;
}

timesFive(1000);

```
Whatever value I pass in function "timeFive()", it always return 25, regardless of either i give 2,5 or 1000.

**Comment by karuppiah7890** [comment]
The solution is correct. You sure you are not able to pass the challenge after submitting results ?

**Comment by Deadpool37** [comment]
I guess @lovelylion is able to pass the challenge but the console always returns 25. The error seems to be in [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/f529067c046d74718a701788756c77100bd4d095/seed/challenges/01-front-end-development-certification/basic-javascript.json#L2658).

**Comment by karuppiah7890** [comment]
what tests are you talking about @Deadpool37 ?

**Comment by Deadpool37** [comment]
Like I changed a .json file but I don't know how to run FCC locally to test if the error is removed.

**Comment by karuppiah7890** [comment]
Oh. Is this your first time ? Have you tried looking at the [Contribution Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#contribution-guidelines) ? That should help you to get started. And look at the sections "Prerequisites" and "Getting Started" too.

**Comment by karuppiah7890** [comment]
And @Deadpool37 that's not an error actually. It's just that there's a static test for timesFive(5) and that shows up in the output. I don't think this is an error. But may be we could change the tail to show output based on the function argument used by the camper in the code editor. But that's not easy. And also, we need to capture the arguments and the timesFive() function call in the code editor for this. @dhcodes Your comments ?

**Comment by lovelylion** [comment]
@karuppiah7890 I have read all the guides and prereq,,,
you have a function which gets input and multiply it with 5, and it is returning a static value of 25 regardless whatever the input i give...how do you think it is correct?



function timesFive(lol){
  return lol * 5;
}

correct behvaior should be if I pass 5 to function, then it return 25 but if I'm passing 1000, it should return 5000.
but actually it is still returning 25

**Comment by karuppiah7890** [comment]
@lovelylion The output you see is a static test. It says " timesFive(5) == 25 ". And it doesn't simply say "25". It's just a test. But yes, we will try to get the arguments in the code editor and show it up in the output. I am waiting for @dhcodes comments. 
And @Bouncey your comments on this please.

**Comment by erictleung** [comment]
@lovelylion thanks for the issue. This is a known issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9583. Please take the conversation over to the pre-existing issue. Also, fwiw here's a PR that was made for the issue but went stale https://github.com/FreeCodeCamp/FreeCodeCamp/pull/9651. Happy coding!
