### ISSUE TITLE
code is correct,but it won't pass

### ISSUE THREAD

**Issue by kumarkamesh** [FreeCodeCamp/FreeCodeCamp#11012]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr="I am a \"double quoted\"string inside \"double quotes\". "; // Change this line



```

**Comment by 149203** [comment]
@kumarkamesh your code doesn't have a space before the word **string**

In the future, please post in the appropriate gitter channel first. If the consensus there is that it is a bug, then you should post here.

**Comment by texas2010** [comment]
@kumarkamesh 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding..
