### ISSUE TITLE
Small bug in the instruction / explanation of the challenge

### ISSUE THREAD

**Issue by msanecki** [FreeCodeCamp/FreeCodeCamp#11025]
Challenge [Style Multiple Elements with a CSS Class](https://www.freecodecamp.com/challenges/style-multiple-elements-with-a-css-class) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

It's not about the code, it's about the instruction of the challenge.
There is a sentence: "But also remember that class declarations don't use a period, like this:"
Especially this is a little bit confused: "class declaration".
The thing is that this is not a declaration of a class.

In my opinion this sentence would be better:
"But remember that pointing a class that is used to affect an html element don't use a period, like this: "
Based on this definition of class selector:
http://www.w3schools.com/cssref/sel_class.asp
http://www.w3schools.com/tags/att_global_class.asp

**Comment by elizabethfinedev** [comment]
I think youre right, its not as accurate as it could be given that what its referring to is class attributes.  

Maybe change it to something like: "But also remember that HTML class attributes don't use a period" ?

**Comment by erictleung** [comment]
Mmm I agree that this could be misinterpreted differently. Maybe we could change it to this.

> But remember that using classes in HTML elements don't need periods.

Nonetheless, something to that effect should be used to replace the text.
