### ISSUE TITLE
i don't understand this issue. I've tried every angle to this issue but still unable to uncomment h1

### ISSUE THREAD

**Issue by elle747** [FreeCodeCamp/FreeCodeCamp#11020]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%20%0A%0A%3C!--hide%20tis%20bitch..%3E%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%3C!--why..%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello World</h1>


<h2>CatPhotoApp</h2> 

<!--hide tis bitch..>
<p>Hello Paragraph</p>
<!--why..>


```

**Comment by Deadpool37** [comment]
@elle747 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only
Please use the Gitter chat room for getting challenge related help and if the concensus there is that this is a bug, then raise an issue here

**Comment by texas2010** [comment]
@elle747 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding..
