### ISSUE TITLE
the code isn't running despite several attempts

### ISSUE THREAD

**Issue by Abhishek-21** [FreeCodeCamp/FreeCodeCamp#11024]
<a href="http://freecodecamp.com"> link to Free Code Camp</a>
![image](https://cloud.githubusercontent.com/assets/22566343/19023192/8e998b1c-8905-11e6-85d9-5bd77219d27d.png)

**Comment by Bouncey** [comment]
@Abhishek-21 please follow the issue template, it helps gather information we use to help you.

Please return to the challenge you have issues with and copy the address in the address bar to this issue.

Along with that, can you please copy the code in the editor and paste it here also.

Without these we will just be guessing.

Please, help us help you.
