### ISSUE TITLE
Learnyounode gives an error of __ is not a function

### ISSUE THREAD

**Issue by aurelkurtula** [FreeCodeCamp/FreeCodeCamp#11031]
#### Challenge Name

https://www.freecodecamp.com/challenges/start-a-nodejs-server

#### Issue Description

I installed `learnyounode` in cloud9 also in my own terminal and in both cases I get the error of 

`TypeError: __ is not a function`

Research shows that I could change all instances of `done()` to `exec()` but the problem still remains. Is there a work around?

**Comment by dhcodes** [comment]
@aurelkurtula unfortunately, learnyounode is not a repo managed by freecodecamp so there's not much we can do if there is indeed a problem with the tutorial. Also, the issues isn't the best place for getting code help. Instead, jump over to the [HelpBackend Chat Room](https://gitter.im/FreeCodeCamp/HelpBackEnd) on Gitter and someone will surely be able to help.
