### ISSUE TITLE
tests work incorrectly

### ISSUE THREAD

**Issue by aliaksandr-s** [FreeCodeCamp/FreeCodeCamp#11037]
Challenge [Use Hex Code to Mix Colors](https://www.freecodecamp.com/challenges/use-hex-code-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20%23FF0000%0A%20%20%7D%0A%20%20.green-text%20%7B%0A%20%20%20%20color%3A%20%2300FF00%0A%20%20%7D%0A%20%20.dodger-blue-text%20%7B%0A%20%20%20%20color%3A%20%232998E4%0A%20%20%7D%0A%20%20.orange-text%20%7B%0A%20%20%20%20color%3A%20%23FFA500%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22green-text%22%3EI%20am%20green!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22dodger-blue-text%22%3EI%20am%20dodger%20blue!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orange-text%22%3EI%20am%20orange!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: #FF0000
  }
  .green-text {
    color: #00FF00
  }
  .dodger-blue-text {
    color: #2998E4
  }
  .orange-text {
    color: #FFA500
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

```

![screenshot](https://cloud.githubusercontent.com/assets/12185469/19044294/56b9cfc6-899c-11e6-9f34-dda9a64b3fe5.png)

**Comment by texas2010** [comment]
@aliaksandr-s 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding..
