### ISSUE TITLE
"More Information" and "Go to Next Challenge" buttons do not work when window is sized for tablet or phone

### ISSUE THREAD

**Issue by andreagoulet** [FreeCodeCamp/FreeCodeCamp#1103]
Challenge http://www.freecodecamp.com/challenges/waypoint-say-hello-to-html-elements has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I was unable to access the instructions for this module because the button labeled "More Information" was unresponsive on my mobile devices (both iPhone & iPad). For both, I'm running iOS v 8.3. 

The editor and display both seem to be working fine. It would be extremely useful to be able to use my mobile devices in addition to my laptop because it's easier to integrate into my daily routine.

**Comment by orrwil** [comment]
I am encountering the same problem on android. The "go to next challenge button" also doesn't work after a waypoint is complete. Actually, this appears to be caused by the mobile responsive view of the site as the more information button stops working if the page is resized down on the desktop, this occurs on both chrome & IE11 has been confirmed on several way points in the Basic HTML and CSS section.

**Comment by orrwil** [comment]
@andreagoulet If you can confirm my comment above, could you possibly amend the title of this issue?
Thanks,

**Comment by andreagoulet** [comment]
@orrwil yes, that's what's happening on my end as well. Good catch. I'll update the title of the issue.

**Comment by joboyx** [comment]
Also happens with me for the same page:

http://www.freecodecamp.com/challenges/waypoint-say-hello-to-html-elements

Next Challenge button is unresponsive.

I'm using Android 5.1 - Chrome Browser.

**Comment by eclectic-matt** [comment]
Having same issues with Chrome 43.0 on Android 5.0. Buttons worked on all waypoints BEFORE this one, but when a coding challenge and More Information button is used these elements are totally unresponsive. Code editor works and detects challenge completion.

**Comment by samlorimer** [comment]
Confirming I'm also experiencing this on iOS 8.4 on iPhone 6.  Doesn't appear to be browser-dependent, occurs on both Chrome and Safari for iOS.  

Unable to click the 'more information' button, and once the code is correctly supplied and the 'Go to next challenge' button is enabled, it is not able to be clicked either.

Thanks

**Comment by darnet** [comment]
So, has anyone found a workaround fo doing exercises on mobile devices (Samsung Android Tablet)? Or will we be forced to do the exercises with a desktop/laptop. I also cannot click the "go to next challenge" or "more information" buttons in codecamp

**Comment by benschenker** [comment]
Closing as stale, please reopen this issue if the problem still exists.

**Comment by GadgetAddict** [comment]
So not stale. Still occurring in iOS 8.2 iPhone 6 in safari

**Comment by BerkeleyTrue** [comment]
fixed. This was a bootstrap issue.

Happy Coding!
