### ISSUE TITLE
Fix typo on "How our Nonprofit Projects Work" page

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#11034]
#### Challenge Name
https://www.freecodecamp.com/how-nonprofit-projects-work

#### Issue Description
There's a typo. "your them"

#### Screenshot
![](https://www.evernote.com/l/Ar_z50zHTUVEi72V5blbjwqTrub3we0rYOAB/image.png)

**Comment by shlomif** [comment]
I'm working on it.

**Comment by ltegman** [comment]
Closed by #11035
