### ISSUE TITLE
Chrome Dev Tools Challenges are broken

### ISSUE THREAD

**Issue by wanyamaman** [FreeCodeCamp/FreeCodeCamp#11041]
#### Challenge Name
Chrome Dev Tools: Network

#### Issue Description
External [link](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/network-performance/resource-loading) to google developers page at the bottom of the challenge is broken, returns 404 error.
Looks like the content moved to a new [page](https://developers.google.com/web/tools/chrome-devtools/network-performance/resource-loading)

#### Browser Information

* Browser Name, Version: Chromium, 52.0.2743.116
* Operating System: Ubuntu 14.04 LTS
* Mobile, Desktop, or Tablet: Desktop

**Comment by alanbares** [comment]
Just checked https://www.freecodecamp.com/videos/chrome-dev-tools-network and I can confirm the link is broken. I can go ahead and make a PR to fix it. And looking through thre seems to be broken links in other chrome challenges.

**Comment by tommasobertagnin** [comment]
@alanbares @ltegman: I found another broken link at https://www.freecodecamp.com/videos/chrome-dev-tools-sources
and I guess the correct link is this one: https://developers.google.com/web/tools/chrome-devtools/javascript/add-breakpoints

Are you still working on it, or should I go on and make the changes?
Cheers
