### ISSUE TITLE
why is the calender not synced to the streak graph?

### ISSUE THREAD

**Issue by richa-coder** [FreeCodeCamp/FreeCodeCamp#11040]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by marhyorh** [comment]
Can you shed more light on your issue. Maybe an image, a link or something.

**Comment by richa-coder** [comment]
I am attaching the screenshot, have a look.Its not syncing for sept and Oct.

On Oct 4, 2016 1:12 AM, "Adegbuyi Ademola" <notifications@github.com> wrote:

Can you shed more light on your issue. Maybe an image, a link or something.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11040#issuecomment-251204654>,
or mute the thread

**Comment by atjonathan** [comment]
@richa-coder, please fill in the issue description with the appropriate details. I can't see a screenshot.
