### ISSUE TITLE
String immutability

### ISSUE THREAD

**Issue by MiltonRoemer** [FreeCodeCamp/FreeCodeCamp#11048]
Challenge [Understand String Immutability](https://www.freecodecamp.com/challenges/understand-string-immutability#?solution=%0A%2F%2F%20Setup%0Avar%20myStr%20%3D%20%22Jello%20World%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20%22Jello%20World%22%3B%20%0AmyStr%20%3D%20%22Hello%20World%22%3B%0AmyStr%5B0%5D%20%3D%20%22H%22%3B%20%2F%2F%20Fix%20Me%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStr = "Jello World";

// Only change code below this line

var myStr = "Jello World"; 
myStr = "Hello World";
myStr[0] = "H"; // Fix Me



```

**Comment by Deadpool37** [comment]
@MiltonRoemer 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only
Please use the HelpJavaScript chat room for getting challenge related help.

Happy Coding.

**Comment by Bouncey** [comment]
Closing as it is for code help.

As directed by @Deadpool37 please use the `Help` button in the challenge you have an issue with, this will take you to a dedicated chat room for help with your code.

Happy coding :+1:
