### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Valdrinit** [FreeCodeCamp/freecodecamp#1104]
Challenge http://www.freecodecamp.com/challenges/bonfire-mutations has an issue.
This is the code that should work
function mutation(arr) {
  for (var i = 0; i < arr[1].lenght; i++)
    if (arr[0].indexOf(arr[1][i]) == -1)
      return false;
  return true;
}
yet it doesn't for the first test case mutation(['hello', 'hey']);

**Comment by LumenTeun** [comment]
Sorry, but I think your code is incorrect.

**Comment by Valdrinit** [comment]
Well, an explaination as to why it doesn't work would be great.

**Comment by BerkeleyTrue** [comment]
@Valdrinit Looks like you have a typo. `arr[i].lenght` should be `arr[i].length`. That is atleast one error I see. There may be more. Good luck with the rest of the bonfires. Also, you will often find a quicker responses using the help chat room https://gitter.im/freecodecamp/help

**Comment by LumenTeun** [comment]
@Valdrinit Sorry for being so brief, I should've at least directed you to the help chatroom. A very common but major error that I've fallen for a few times myself is to put the else part of the if statement inside the for loop. This way, the for loop doesn't loop all the way through, but returns a value after checking the first value only. This is easier to see if you use curly braces `{}` around your if statements.

**Comment by Valdrinit** [comment]
Sorry, but that's not it. My function returns false as soon as it finds a letter in the second argument that can't be found in the first one; when the loop is done, meaning the first argument contains all the letters of the second one, it returns true.
It seems that the typo was the true problem.
