### ISSUE TITLE
SASS documentation

### ISSUE THREAD

**Issue by hallaathrad** [FreeCodeCamp/FreeCodeCamp#11043]
So... today I've been at the FITC Web Unleashed 2016 conference, where I've met amazing @bpainter (Those who don't know of him, shame on you! jk)... and this rockstar of a guy thinks he may get us in touch with the SASS people so we can improve their documentation, and maybe reshape it a bit more newbie friendly. This would help us teach campers so much better, and in the process help us shape our own sass contents. Right? no? Comment!

Thus, I humbly bequest this community with the task of helping me figure out what needs to be changed or added. Maybe we could ask the general population for hints and requests?
Any and all —constructive— input shall be welcome and considered. Let's make it happen!

@QuincyLarson @FreeCodeCamp/issue-moderators Thoughts on how to lead this?

**Comment by P1xt** [comment]
Sass shouldn't be all caps. Which parts of the Sass documentation do you not find newbie friendly? 

It's been a while but I recall the documentation for Sass was intuitive and reasonably easy to use pretty much across the board.

**Comment by hallaathrad** [comment]
Hmm I take it there's no interest in pursuing this issue. closing
