### ISSUE TITLE
Travis not recognizing eslint command

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#11056]
As seen on [this line](https://travis-ci.org/FreeCodeCamp/FreeCodeCamp/jobs/165018923#L1271), the eslint command isn't being picked up by Travis CI.

**Comment by BerkeleyTrue** [comment]
This looks like it must be a bug in travis.

**Comment by BerkeleyTrue** [comment]
I've just restarted the travis job and got a different issue

**Comment by BerkeleyTrue** [comment]
Yup, looks like this was a temporary glitch https://travis-ci.org/FreeCodeCamp/FreeCodeCamp/builds/165026793#L335
