### ISSUE TITLE
SyntaxError: Missing while after do-loop body

### ISSUE THREAD

**Issue by Dayfiri** [freeCodeCamp/freeCodeCamp#11068]
#### Challenge Name

https://www.freecodecamp.com/challenges/roman-numeral-converter
#### Issue Description

SyntaxError: Missing while after do-loop body
![screenshot at 2016-10-05 20 55 03](https://cloud.githubusercontent.com/assets/16082563/19127160/2996f534-8b3e-11e6-8196-96780df9c4ef.png)
- Browser Name, Version: Firefox Dev edition,  version 51
- Operating System: Ubuntu Mate 16.04 
- Mobile, Desktop, or Tablet: Desktop
#### Your Code

``` js

 function convertToRoman(num) {
var library = {
  1: "I",
  4: "IV",
  5: "V",
  9: "IX",
  10: "X",
  40: "XL",
  50: "L",
  90: "XC",
  100: "C",
  400: "CD",
  500: "D",
  900: "CM",
  1000: "M"
};

var numbers = [1,4,5,9,10,40,50,90,100,400,500,900,1000];


var signs = [];

  //starting do-while

do{
  var max = 0;
  for(var i = 0; i < numbers.length; i++){
      if( numbers[i] > max && numbers[i] <= num){
      maxNmb = Math.max(numbers[i]);
      }
  }

  signs.push(library["" + maxNmb + ""]);
  console.log(signs);

  num = num - maxNmb;
  console.log(max);

} while(num !== 0); // here is Syntax error

var stringer = signs.join("");

return stringer;


} //closed function

convertToRoman(36); //function call

```
#### Screenshot

Works on Codepen without a problem!
![screenshot at 2016-10-05 21 02 51](https://cloud.githubusercontent.com/assets/16082563/19127433/396c09a8-8b3f-11e6-8ad5-a16c86266d21.png)

**Comment by Bouncey** [comment]
It is strange. With the `;` there, the code will not run and the output shows there is a syntax error.

Without the `;`, the editor highlights a syntax error, but the code runs and the challenge is passed.

There is no head or tail code in this challenge I think this might be an issue with codemirror linting.

**Comment by Dayfiri** [comment]
Ok, thanks for fast reply :)

**Comment by systimotic** [comment]
I've spent some time investigating this issue, messing with the provided code sample. I found that this issue didn't only disappear when removing the semi-colon, but also by removing the newlines inside of the `do` body. Adding any content to those lines also seems to fix the issue (at first I though indenting the line fixed it, but I guess that's just because I'm adding spaces to the line). There's definitely something weird going on in some of the code that's running the tests. Good news though, things seem to work fine in the beta!

**Comment by ltegman** [comment]
Hmmm, is loopProtect not running in the react site or being used differently? The issue is loopProtect mangling the code. You can bypass loopProtect for now by placing `//noprotect` at the top of the editor.

For anyone wanting to look into this you can view the loopProtect output by going into your browser console while using Free Code Camp and entering
```
loopProtect(`code block to test`)
```

Here is the mangled loopProtect output:

```javascript
function convertToRoman(num) {
var library = {
  1: "I",
  4: "IV",
  5: "V",
  9: "IX",
  10: "X",
  40: "XL",
  50: "L",
  90: "XC",
  100: "C",
  400: "CD",
  500: "D",
  900: "CM",
  1000: "M"
};

var numbers = [1,4,5,9,10,40,50,90,100,400,500,900,1000];


var signs = [];

  //starting do-while

;loopProtect.protect({ line: 25, reset: true }); do{;
if (loopProtect.protect({ line: 25 })) break;

  var max = 0;
  ;loopProtect.protect({ line: 27, reset: true }); for(var i = 0; i < numbers.length; i++){;
if (loopProtect.protect({ line: 27 })) break;

      if( numbers[i] > max && numbers[i] <= num){
      maxNmb = Math.max(numbers[i]);
      }
  }

  signs.push(library["" + maxNmb + ""]);
  console.log(signs);

  num = num - maxNmb;
  console.log(max);

} ;loopProtect.protect({ line: 39, reset: true }); while(num !== 0){
if (loopProtect.protect({ line: 39 })) break;
; // here is Syntax error
}


var stringer = signs.join("");

return stringer;


} //closed function

convertToRoman(36);
```

**Comment by techstonia** [comment]
Strange. I can't reproduce the issue locally, but it definitely is present in the production.

**Comment by jaeckel** [comment]
I just encountered the Problem at https://www.freecodecamp.com/challenges/seek-and-destroy
Removing the semicolon after "while()" solved the error. 

```
function destroyer(){
    //Loop through all the arguments

    for (var i in arguments){
        //The Array is the first argument
        if (i == 0){var arr = arguments[i];}
        
        //Go through the other arguments
        else {
                      
            do{
                index = arr.indexOf(arguments[i]);
                if(index > -1){arr.splice(index, 1);}

            }while(index > -1);
            //Loop through the first array until the value can't be found
        }
    }
    return arr;
}
console.log(  destroyer([1, 2, 3, 1, 2, 3], 2, 3));
```

**Comment by GeneralFailer** [comment]
Why has this been closed? I'm still reproducing this just fine on Firefox and Chromium.

**Comment by QuincyLarson** [comment]
@GeneralFailer We can re-open it again. Since you can reproduce this would you be interested in attempting to fix it?

**Comment by GeneralFailer** [comment]
No, sorry.
