### ISSUE TITLE
Update machine-readable sitemap

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#11062]
Our sitemap is out of date: https://www.freecodecamp.com/sitemap.xml

**Comment by ltegman** [comment]
About to put up a PR for this. Should it include subdomain pages like Medium and the Forum?

**Comment by QuincyLarson** [comment]
@ltegman Awesome! This should only include www.freecodecamp.com paths. One thing the old sitemap did, which may have hurt us, was index all of the user profiles - and there are literally 500k of those, most of which have nothing more than a username. We might not want to index all of these on our sitemap, and rather let Google crawl these on its own.
