### ISSUE TITLE
Add challenge names and potentially breadcrumbs

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#11061]
We can improve the searchability of our challenges by including additional text and links in the descriptions of these challenges.

We could add the following to the top of a challenge lesson description.

(these breadcrumbs would be clickable and lead to cert/topic landing pages)
Responsive Web Design > HTML5 and CSS > Say Hello to HTML Elements

Then: "Learn to Code with HTML and Say Hello to HTML Elements"

**Comment by atjonathan** [comment]
@QuincyLarson, is something like the below what you are looking for?
[![https://gyazo.com/c539757d2ffc5ddb644bc132fddf4945](https://i.gyazo.com/c539757d2ffc5ddb644bc132fddf4945.png)](https://gyazo.com/c539757d2ffc5ddb644bc132fddf4945)

**Comment by marhyorh** [comment]
@atjonathan Since we're on "Say Hello to HTML Elements", i suggest we make only that highlighted in the breadcrumb, the rest should be a grayish color or sort of. But there's some other issue here, we have "Say Hello to HTML Elements" repeated, don't know if it's nice that way.

**Comment by atjonathan** [comment]
@marhyorh, thanks yeah I agree!

**Comment by QuincyLarson** [comment]
@atjonathan Actually, I forgot I'd opened this issue and opened a duplicate one (which I've closed: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11142). 

Here's what I think we should do (we don't need breadcrumbs):

For SEO purposes, we should include the challenge category (JavaScript, HTML, Node.js, etc.) both in the `<title>` element and in the `<h1>` element before the challenge's name.

For example:

![](http://i.imgur.com/WhegItY.png)

**Comment by andmckvr13** [comment]
@atjonathan I've updated the titles for the front-end and back-end challenges. However, I'm receiving this error when running npm run test-challenges 'failed: babel-node seed/test-challenges.js

**Comment by atjonathan** [comment]
@andmckvr13, can you send me the error log in a pm?

**Comment by andmckvr13** [comment]
@atjonathan sent on gitter

**Comment by minodorag** [comment]
hello world!  I am Minodora .I found freecode from web.I want to learn to program so i get a job as frontend
