### ISSUE TITLE
Stand In Line challenge: Here's my code: But system won't allow me to proceed I don't know why?

### ISSUE THREAD

**Issue by ahmedghandour** [FreeCodeCamp/FreeCodeCamp#11073]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20%0A%20%20testArr.push(item)%3B%0A%20%20return%20testArr.shift()%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%205))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function nextInLine(arr, item) {
  // Your code here
  
  testArr.push(item);
  return testArr.shift();  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 5)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by Dayfiri** [comment]
Challenge works fine and here is an example of that. Problem is in your code, so check it again and tell me how it goes ;)

![screenshot at 2016-10-06 11 41 02](https://cloud.githubusercontent.com/assets/16082563/19147749/dc2435ce-8bb9-11e6-8569-b30390635197.png)

**Comment by Deadpool37** [comment]
@ahmedghandour you have a small error in your code. In the future, please post in the [HelpJavascript](https://gitter.im/FreeCodeCamp/HelpJavaScript) Gitter channel first. If the consensus there is that it is a bug, then you should post here.

**Comment by erictleung** [comment]
@ahmedghandour thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: please review your knowledge of function scope. You can only use variables that are scoped by your function. Happy coding!

**Comment by ahmedghandour** [comment]
Thanks guys, I'll try again and again until it is Ok, and I'll post in the help it was my mistake

**Comment by ahmedghandour** [comment]
Thanks a lot erictleung, you've been of great help. Thanks again.
I passed the challenge.
