### ISSUE TITLE
Typo in an article

### ISSUE THREAD

**Issue by MysteriousManfred** [FreeCodeCamp/freecodecamp#1107]
http://www.freecodecamp.com/field-guide/what-is-pair-programming-and-why-is-it-special

"By pair programming with other Free Code Camp students on our coding challenges."

Sentence is missing a main verb.

**Comment by NatashaHaggard** [comment]
What would a correct sentence look like?

**Comment by MysteriousManfred** [comment]
'You can pair program with other students.', or 'By pair programming with other Free Code Camp students on our coding challenges, you'll learn to cooperate.' It wouldn't quite work to fit it into the next sentence, so you'd need to decide what pair programming teaches you.

**Comment by ahstro** [comment]
Was fixed, please close.
