### ISSUE TITLE
Code is correct but won't pass

### ISSUE THREAD

**Issue by MeHigh777** [FreeCodeCamp/FreeCodeCamp#11075]
I've completed the first 2 stepts but i can't get pass the third one...if i change wordBlanks acordingly to the 3rd step it says that the 2nd one is not completed.

Challenge [Word Blanks](https://www.freecodecamp.com/challenges/word-blanks#?solution=%0Afunction%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20myNoun%20%3D%20%22dog%22%3B%0A%20%20myAdjective%20%3D%20%22big%22%3B%0A%20%20myVerb%20%3D%20%22ran%22%3B%0A%20%20myAdverb%20%3D%20%22quickly%22%3B%0A%20%20%0A%20%20result%20%2B%3D%20%22My%20%22%2B%20myAdjective%20%2B%22%20%22%2B%20myNoun%20%2B%22%20%22%20%2B%20myVerb%20%2B%20%22%20very%20%22%20%2B%20myAdverb%3B%0A%0A%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22dog%22%2C%20%22big%22%2C%20%22ran%22%2C%20%22quickly%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
https://postimg.org/image/cws0yldg5/
My code:
```javascript

function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  myNoun = "dog";
  myAdjective = "big";
  myVerb = "ran";
  myAdverb = "quickly";
  
  result += "My "+ myAdjective +" "+ myNoun +" " + myVerb + " very " + myAdverb;

  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```

**Comment by erictleung** [comment]
@MeHigh777 thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: do not reassign your variables within the function. Make use of the function parameters being passed in. Happy coding!

**Comment by MeHigh777** [comment]
Ooohhhh...haha...i get it now.
Thanks! 
Much apreciated
