### ISSUE TITLE
Completely frozen, cannot reset Steamroller Challenge, even on reload

### ISSUE THREAD

**Issue by Tattomoosa** [FreeCodeCamp/FreeCodeCamp#11078]
#### Challenge Name

https://www.freecodecamp.com/challenges/steamroller

#### Issue Description

Not sure why this is happening - the page freezes before even running my code on refresh. I cannot reset the challenge because none of the buttons on the page work. I am assuming some infinite loop issue in my code but I can't understand why it would freeze before running.

I want to reset the challenge so I can complete it! But it seems like the only way to do that is on the page itself...

#### Browser Information

* Browser Name, Version: chrome, v53.0.2785.143
* Operating System: OS X 10.11.16
* Mobile, Desktop, or Tablet: Desktop, Mac

#### Your Code

transcribed from image - sorry if there's any mistakes
```js
function steamrollArray(arr) {
  var flatArr=[];
  for (i=0;i<arr.length;i++) {
    if (Array.isArray(arr[i])) {
      flatArr = flatArr.concat(steamrollArray(arr[i]));
    } else {
      flatArr.push(arr[i]);
    }
  }
  return arr;
}

```
#### Screenshot

![screen shot 2016-10-06 at 12 16 25](https://cloud.githubusercontent.com/assets/16693238/19160707/ea62c664-8bbe-11e6-8c2f-c528d08b5e7e.png)

**Comment by dhcodes** [comment]
@Tattomoosa you likely wrote an infinite loop that wasn't caught by loop-protect. Try this: http://forum.freecodecamp.com/t/disable-code-auto-run-on-free-code-camp/19511

**Comment by Tattomoosa** [comment]
Ah! Thank you, that worked!

**Comment by Tattomoosa** [comment]
Well, it looked like it worked -- I can press reset and it clears. But if I reload the page with code running enabled it loads the old code and locks up again.

**Comment by dhcodes** [comment]
Well the most recent submission is what is stored in the cache. So if you copy your code, reset the code and then push sumbit, and then paste it back in, it should work.

Alternatively, you could copy your code, clear your history, and then re-log in, etc.

**Comment by Deadpool37** [comment]
@Tattomoosa I changed your code that made it work for me. The changes I made have been written in bold
function steamrollArray(arr) {
  var flatArr=[];
  for (**var** i=0;i<arr.length;i++) {
    if (Array.isArray(arr[i])) {
      flatArr = flatArr.concat(steamrollArray(arr[i]));
    } else {
      flatArr.push(arr[i]);
    }
  }
  return **str**;
}

**Comment by Deadpool37** [comment]
@Tattomoosa also incase of an infinte loop I prefer using `auto-run` insted of `run`

**Comment by Tattomoosa** [comment]
Thanks Deadpool37!!

Returning 'arr' instead of 'flatArr' was by mistake, and I thought that was the root of the problem, but I'm so glad you pointed out the issue with the scope of 'i' -- that would have really messed me up!

**Comment by Deadpool37** [comment]
👍
