### ISSUE TITLE
Understanding Uninitialized Variables bug?

### ISSUE THREAD

**Issue by burpi** [FreeCodeCamp/FreeCodeCamp#11074]
Challenge [Understanding Uninitialized Variables](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables#?solution=%0A%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%20%3D%205%3B%0Avar%20b%20%3D%2010%3B%0Avar%20c%20%3D%20%22i%20am%20a%22%3B%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Initialize these three variables
var a = 5;
var b = 10;
var c = "i am a";

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";


```

![bug](https://cloud.githubusercontent.com/assets/22492055/19155787/0d6e7cc2-8be0-11e6-9982-a4528d3e9513.jpg)

The code looks good but it wont accept the outcome.

**Comment by hristijankiko** [comment]
The problem is that the first " i " should be upper case so "i am a" => "I am a" it looks like the string is case sensitive I'm not sure if it is a bug or it should be like that tho.

**Comment by burpi** [comment]
ooh offcourse sorry :) now i feel stupid

**Comment by texas2010** [comment]
@burpi, you almost got it right. but you wrote `var c = "i am a";`.
It suppose to be `var c = "I am a";`

this issue dont have a bug.
Next time, please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.
GitHub Issues are for reporting bugs on the website only.

Happy Coding.
