### ISSUE TITLE
Counting cards 

### ISSUE THREAD

**Issue by milesaylward** [FreeCodeCamp/FreeCodeCamp#11070]
Not so much an issue just noticed that on your Counting Card challenge the instructions tell you that if the count is greater than or equal to 0 you should bet but the code allows you to pass the challenge even if you don't set the greater than or equal to operator. The preview screen showed me 0 Hold, when it should have said 0 Bet. And I still passed the challenge. 

#### Challenge Name
https://www.freecodecamp.com/challenges/counting-cards

#### Issue Description
complete the challenge using if else statements and only use greater than not equal to. 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 var count = 0;

function cc(card) {
  // Only change code below this line
  var answer = "";
  if(card <= 6){
    count+=1;
    if(count > 0){
      answer = " Bet";
    }
    else{
      answer =" Hold";
    }
    return count + answer;
  } 
  else if(card > 6 && card < 10){
    if(count > 0){
      answer = " Bet";
    }
    else{
      answer =" Hold";
    }
    return count + answer;
  }
  else{
    count-=1;
    if(count > 0){
      answer = " Bet";
    }
    else{
      answer =" Hold";
    }
    return count + answer;
  }
  
  return count + answer;
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

 
 
```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/20111431/19130458/399bc628-8b19-11e6-8dcc-08015927836e.png)

**Comment by hristijankiko** [comment]
I don't think you should Bet when the count is 0 based on these sentences, or i missed something?
http://image.prntscr.com/image/5b5ec74b2db74e98836df0e7a3b69ab5.png

**Comment by Deadpool37** [comment]
@milesaylward as @hristijankiko said the instructions and the second test-case tell you that if the count is `0`, then the output should be `0 Hold`. So your code passed because it was correct. 
In the future, please post in the [HelpJavascript](https://gitter.im/FreeCodeCamp/HelpJavaScript) Gitter channel first. If the consensus there is that it is a bug, then you should post here.

**Comment by milesaylward** [comment]
I apologize I misread the instructions, I will refer to the help JavaScript
in the future.

**Comment by Deadpool37** [comment]
Cool :)

**Comment by erictleung** [comment]
Closing as it seems the issue has resolved itself. Happy coding!
