### ISSUE TITLE
Sorted Union not accepting correct function returns?

### ISSUE THREAD

**Issue by edsonmendieta** [FreeCodeCamp/FreeCodeCamp#11072]
Challenge [Sorted Union](https://www.freecodecamp.com/challenges/sorted-union#?solution=%0Afunction%20uniteUnique(arr)%20%7B%0A%20%20%0A%20%20%0A%20%20var%20joinedArray%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20var%20newArray%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20var%20finalArray%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%20arguments.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%0A%20%20%20%20%20%20var%20joined%20%3D%20arguments%5Bi%5D.join(%22%22)%3B%0A%20%20%20%20%20%20joinedArray.push(joined)%3B%0A%20%20%7D%0A%20%20%0A%20%20joinedArray%20%3D%20joinedArray.join(%22%22)%3B%0A%20%20joinedArray%20%3D%20joinedArray.split(%22%22)%3B%0A%20%20%0A%20%20%0A%20%20for%20(z%20%3D%200%3B%20z%20%3C%20joinedArray.length%3B%20z%2B%2B)%20%7B%0A%20%20%20%20%0A%20%20%20%20%20%20if%20(z%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20newArray.push(joinedArray%5Bz%5D)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%20%20else%20%7B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20var%20match%20%3D%20%22no%22%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20for%20(h%20%3D%200%3B%20h%20%3C%20newArray.length%3B%20h%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(joinedArray%5Bz%5D%20%3D%3D%20newArray%5Bh%5D)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20match%20%3D%20%22yes%22%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20if%20(match%20%3D%3D%20%22no%22)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20newArray.push(joinedArray%5Bz%5D)%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20%20%0A%20%20for%20(q%20%3D%200%3B%20q%20%3C%20newArray.length%3B%20q%2B%2B)%20%7B%0A%20%20%20%20%0A%20%20%20%20%20%20var%20numberized%20%3D%20Number(newArray%5Bq%5D)%3B%0A%20%20%20%20%0A%20%20%20%20%20%20finalArray.push(numberized)%3B%0A%20%20%7D%0A%20%20%0A%0A%20%20%0A%20%20%0A%20%20return%20finalArray%3B%0A%7D%0A%0A%0A%0AuniteUnique(%5B1%2C%203%2C%202%5D%2C%20%5B1%2C%20%5B5%5D%5D%2C%20%5B2%2C%20%5B4%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// So my code passes 3 of 4 assertion tests but not one of them. 

// Here it is: uniteUnique([1, 3, 2], [1, [5]], [2, [4]]) should return [1, 3, 2, [5], [4]].

// My code returns: [1,3,2,5,4]. It's the same but without the numbers 5 and 4 in an array.

// This is what it says in the instructions: 

//"Write a function that takes two or more arrays and returns 
//a new array of unique values in the order of the original provided arrays."

//"In other words, all values present from all arrays should
 //be included in their original order, but with no duplicates in the final array."

//"The unique numbers should be sorted by their original order, 
//but the final array should not be sorted in numerical order."

// My code returns what the instructions says it should return 
//and does away with the array surrounding some of the values. 

// Also, given that: 

//var word;
  
 // if ([5] == 5) {
    
  // word = "bird";
  //}

//...evaluates to true, meaning 5 is the same as [5], shouldn't my
//code's output for the assertion test in //question be accepted? 

// **Thank you for your time and help in advance!**




function uniteUnique(arr) {
  
  
  var joinedArray = [];
  
  var newArray = [];
  
  var finalArray = [];
  
  
  for (i = 0; i < arguments.length; i++) {
    
      var joined = arguments[i].join("");
      joinedArray.push(joined);
  }
  
  joinedArray = joinedArray.join("");
  joinedArray = joinedArray.split("");
  
  
  for (z = 0; z < joinedArray.length; z++) {
    
      if (z === 0) {
        
          newArray.push(joinedArray[z]);
      }
    
      else {
        
          var match = "no";
        
          for (h = 0; h < newArray.length; h++) {
            
              if (joinedArray[z] == newArray[h]) {
                
                  match = "yes";
              }
          }
        
          if (match == "no") {
            
              newArray.push(joinedArray[z]);
          }
      }
  }
  
   
  for (q = 0; q < newArray.length; q++) {
    
      var numberized = Number(newArray[q]);
    
      finalArray.push(numberized);
  }
  

  
  
  return finalArray;
}



uniteUnique([1, 3, 2], [1, [5]], [2, [4]]);

```

**Comment by Bouncey** [comment]
>In other words, *all values present from all arrays should be included* in their original order, but with no duplicates in the final array.

The array value of [5] would be different to the array value of 5. 

For instance if myArray = [1, [5]];
And yourArray = [1, 5];

To access the integer of 5 in both arrays would require two approaches. 

Mine would be myArray[1][0]; 
And yours would be yourArray[1]; 

So in fact, the arrays do not have the same value in the index of one. 

I hope this clears up your issue. 

Happy coding

**Comment by edsonmendieta** [comment]
Ah, that makes sense. Thank for clearing that up!
