### ISSUE TITLE
Bonfire: Convert HTML Entities

### ISSUE THREAD

**Issue by destino92** [FreeCodeCamp/freecodecamp#1108]
```javascript
function convert(str) {
  // &colon;&rpar;
  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g,'&apos');
}
convert('Dolce & Gabbana');
```
assert.strictEqual(convert('Dolce & Gabbana'), 'Dolce & Gabbana', 'should escape characters');
assert.strictEqual('<>', '<>', 'should escape characters');
should escape characters: expected '<>' to equal '<>'
assert.strictEqual(convert('abc'), 'abc', 'should handle strings with nothing to escape');

**Comment by BerkeleyTrue** [comment]
@destino92  Thanks for reporting. We will be tracking this issue at #1062

**Comment by Navankur94** [comment]
function convertHTML(str) {
 var temp = str.split('');

  // Since we are only checking for a few HTML elements I used a switch
  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g,'&apos;');
}


convertHTML("Shindler's List");

**Comment by Navankur94** [comment]
function convertHTML(str) {
 var temp = str.split('');

  // Since we are only checking for a few HTML elements I used a switch
  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g,'&apos;');
}


convertHTML("Shindler's List");

**Comment by Navankur94** [comment]
function convertHTML(str) {
 var temp = str.split('');

  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g,'&apos;');
}


convertHTML("Shindler's List");

**Comment by danesh4545** [comment]
Dani_anzali@yahoo.com
در تاریخ ۲۱ مهٔ ۲۰۱۶ ۲۲:۱۴، "Navankur Srivastava" <notifications@github.com>
نوشت:
