### ISSUE TITLE
Clarify what the `.pop()` method does

### ISSUE THREAD

**Issue by marienhof** [FreeCodeCamp/FreeCodeCamp#11092]
Maybe you should add "The pop() method removes the last element from an array and returns that element".

Challenge [Manipulate Arrays With pop](https://www.freecodecamp.com/challenges/manipulate-arrays-with-pop) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A456 Safari/602.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArray = [1,2,3];
var removedFromOurArray = ourArray.pop(); 
// removedFromOurArray now equals 3, and ourArray now equals [1,2]

// Setup
var myArray = [["John", 23], ["cat", 2]];

// Only change code below this line.
var removedFromMyArray = myArray.pop();



```

**Comment by Deadpool37** [comment]
@marienhof thanks for the sugestions. What you have suggested here is already there in the challenge description, it's example, the instruction and the code setup. So, I don't think it is required.

Happy Coding

**Comment by erictleung** [comment]
>`.pop()` is used to "pop" a value off of the end of an array. We can store this "popped off" value by assigning it to a variable. 

@marienhof are you suggesting this addition because this statement may be as clear to some people? The text later on in the text explains what `.pop()` does with a mini-code example.

> For example, for the code `var oneDown = [1, 4, 6].pop();` the variable `oneDown` now holds the value `6` and the array becomes `[1, 4]`.

**Comment by marienhof** [comment]
Yep, it'll be clearer

**Comment by energizerpiggy** [comment]
Can you please just get someone to me and help me

**Comment by energizerpiggy** [comment]
I am a dirty gay sub sleazy open minded fist/piss pig that likes being used
by guys 18-30 .  Do you think I have a career of secret personal shows? Lol

**Comment by texas2010** [comment]
@energizerpiggy Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by erictleung** [comment]
@marienhof thanks for the suggestion. We can change the instructions to the following.

> Another way to change the data in an array is with the `.pop()` function.
>
> `.pop()` is used to "pop" a value off of the end of an array. We can store this "popped off" value by assigning it to a variable. In other words, `.pop()` removes the last element from an array and returns that element".
>
> Any type of entry can be "popped" off of an array - numbers, strings, even nested arrays.
>
>  ```js
> var threeArr = [1, 4, 6]
> var oneDown = threeArr.pop();
> console.log(oneDown); // Returns 6
> console.log(threeArr);  // Returns [1, 4]
> ````
>
> ### Instructions
> Use the `.pop()` function to remove the last item from `myArray`, assigning the "popped off" value to `removedFromMyArray`.

**Comment by hristijankiko** [comment]
I will work on this.

**Comment by javaGirl0311** [comment]
![image](https://cloud.githubusercontent.com/assets/18656900/20625668/c55fec80-b34f-11e6-8ebe-6d0d6ecd4a85.png)

**Comment by butisitcode** [comment]
In the description text: 
> For example, for the code var oneDown = [1, 4, 6].pop(); the variable oneDown now holds the value 6 and the array becomes [1, 4].

I'd be grateful if someone could clarify for me whether the array still exists after this statement is executed. If it does, how can the remaining values be accessed? Thanks!
