### ISSUE TITLE
Convert HTML Entities Evaluation Issue

### ISSUE THREAD

**Issue by akgold** [FreeCodeCamp/freecodecamp#1109]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. 

There is a function call missing in the assert command here. For example, the first and third assert commands for checking call the user-created function on the input. The second assert command does not call the user-created function at all.

It currently reads, "assert.strictEqual('<>', '<>', 'should escape characters');", which does not call the user-created function at all. It should read "assert.strictEqual(convert('<>'), '<>', 'should escape characters');" (similarly to the first and third checking codes).

Love the site. Thanks!

![image](https://cloud.githubusercontent.com/assets/394930/8340231/30439bc8-1a8b-11e5-8579-e66ddf0122f8.png)

**Comment by BerkeleyTrue** [comment]
@akgold Thanks for reporting. We will be tracking this issue at #1062
