### ISSUE TITLE
how to add dist-tag

### ISSUE THREAD

**Issue by gsr3568** [FreeCodeCamp/FreeCodeCamp#11098]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by erictleung** [comment]
@gsr3568 if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Closing as a non-issue. Please comment back or make a new issue if you have an issue with the site itself. Happy coding!
