### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by marienhof** [FreeCodeCamp/FreeCodeCamp#11095]
I'd add "It's important that you push an item, and not an array that contains only that item, because those are two different things".

Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0Aarr.push(item)%3B%0A%20%20var%20miss%20%3D%20arr.shift()%3B%0A%0A%20%20return%20miss%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%2010))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A456 Safari/602.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function nextInLine(arr, item) {
  // Your code here
arr.push(item);
  var miss = arr.shift();

  return miss;  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 10)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by Dayfiri** [comment]
This assignment is under "Basic Javascript" and I think that assignments should be the same way "basic" like they actually are. It is true that that item !== array_item but that's not the point here. The point here is to teach people a new method from JS and how to implement it. Everything in depth would probably confuse people even more than it would actually teach them.

**Comment by dhcodes** [comment]
I think this adds a jump in thought not necessarily experienced by all campers.

**Comment by erictleung** [comment]
The instructions say

> Write a function `nextInLine` which takes an array (`arr`) and a number (`item`) as arguments.

where it says you've given a number, not an array. The challenge tests also indicate this as well. Campers can take a look at the MDN or `.push()` reference to find more. As others have pointed out, this may give campers unnecessary information at this point. Closing as the challenge instructions as sufficient. Happy coding!
