### ISSUE TITLE
Basic Algorithm Scripting - Check for Palindromes Incomplete   *

### ISSUE THREAD

**Issue by rolljee** [FreeCodeCamp/FreeCodeCamp#11094]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20var%20e1%20%3D%20%2F%5CS%2Fg%3B%0A%20%20var%20e2%20%3D%20%2F%5CD%2Fg%3B%0A%20%20var%20e3%20%3D%20%2F%5Cw%2Fg%3B%0A%20%20var%20e4%20%3D%20%2F%5E_%2Fg%3B%0A%20%20console.log(str.match(e1).join(%22%22).match(e2).join('').match(e3).join('').toLowerCase().replace(%22_%22%2C'')%2C%20str.match(e1).join(%22%22).match(e2).join('').match(e3).reverse().join('').toLowerCase().replace(%22_%22%2C''))%3B%0A%20%20return%20str.match(e1).join(%22%22).match(e2).join('').match(e3).join('').toLowerCase().replace(%22_%22%2C'')%20%3D%3D%3D%20str.match(e1).join(%22%22).match(e2).join('').match(e3).reverse().join('').toLowerCase().replace(%22_%22%2C'')%3B%0A%7D%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function palindrome(str) {
  var e1 = /\S/g;
  var e2 = /\D/g;
  var e3 = /\w/g;
  var e4 = /^_/g;
  console.log(str.match(e1).join("").match(e2).join('').match(e3).join('').toLowerCase().replace("_",''), str.match(e1).join("").match(e2).join('').match(e3).reverse().join('').toLowerCase().replace("_",''));
  return str.match(e1).join("").match(e2).join('').match(e3).join('').toLowerCase().replace("_",'') === str.match(e1).join("").match(e2).join('').match(e3).reverse().join('').toLowerCase().replace("_",'');
}

palindrome("eye");

```
palindrome("1 eye for of 1 eye.")
My output is : firstStr : eyeforofeye  Reverse : eyeforofeye

Seem's to be a Palindromes, but it always show false in the result box.

I report this as i think this is a little bug.

**Comment by Deadpool37** [comment]
@rolljee thanks for the issue. Read the challenge again it says you need to remove all the **non-alphanumeric characters**. That means `"1 eye for of 1 eye."` should be read as `"1eyeforof1eye"`

**Comment by erictleung** [comment]
@rolljee thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Please reread the instructions and look up the definition of "non-alphanumeric characters."

> You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes.
 
Happy coding!
