### ISSUE TITLE
Babel dependency

### ISSUE THREAD

**Issue by hristijankiko** [FreeCodeCamp/FreeCodeCamp#11109]
We currently have the babel dependencies listed in the production dependencies, but based on this article: https://www.codecademy.com/articles/react-setup-ii  they are not needed for the production app. I think we should move them to dev-dependencies.

![](http://image.prntscr.com/image/c1acd903d2c646de9e0ed75e08c44580.png)

**Comment by erictleung** [comment]
cc/ @BerkeleyTrue

**Comment by BerkeleyTrue** [comment]
We use babel-register throughout the app which depends on babel. That is why they are in dependents. Although this is not ideal I have not found a solution that I am willing to invest in yet.

Happy Coding
