### ISSUE TITLE
Maybe a mistake 

### ISSUE THREAD

**Issue by marienhof** [FreeCodeCamp/FreeCodeCamp#11102]
If you have many options to choose from, use a switch statement. A switch statement tests a value and can have many case statements **which defines** various possible values. Statements are executed from the first matched case value until a break is encountered.

Isn't it "which define"?

Challenge [Selecting from many options with Switch Statements](https://www.freecodecamp.com/challenges/selecting-from-many-options-with-switch-statements) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A456 Safari/602.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(1);


```

**Comment by erictleung** [comment]
@marienhof nice catch! Yes, it should be "...which define..." instead of "...which defines..."

```diff
- ... statements which defines various possible values.
+ ... statements which define various possible values.
```

**Comment by chakrihacker** [comment]
I will take this

**Comment by ryzokuken** [comment]
@chakrihacker are you working on this?

**Comment by ryzokuken** [comment]
@erictleung looks like @rheupler already fixed this in the seeds https://github.com/FreeCodeCamp/FreeCodeCamp/commit/8fb284d5d1fa01a7a647eed046c8245f38e2d9e5

**Comment by erictleung** [comment]
@ryzokuken thanks for checking that out. I neglected to check the code base. Thanks! This issue appears to be resolved so I'll be closing this issue. Happy coding!
