### ISSUE TITLE
Add a "How to use GitHub"-waypoint

### ISSUE THREAD

**Issue by ahstro** [FreeCodeCamp/FreeCodeCamp#1110]
There needs to be a waypoint or a series of waypoints that explain how to properly use GitHub in general, and how to search for and report issues in particular, since people are posting a lot of duplicate issues (see #1062, and it's 7 duplicates, about a bug that was already fixed in `staging`).

I think I have seen this mentioned already, but my inability to find a relevant issue, if there is one, sort of just strengthens my point.

**Comment by jniles** [comment]
+1

**Comment by orrwil** [comment]
Agreed, this would be very helpful

**Comment by AkiraLaine** [comment]
Plus, maybe add a "How to use Git" Waypoint.

**Comment by LumenTeun** [comment]
Would one of the @FreeCodeCamp/owners join this discussion? I can do the actual compiling of information and write it up, but I need to know whether I should add it as a single waypoint, maybe at the end of 'Get Set for Free Code Camp', or as a category of it's own, with separate waypoints for Git, GitHub searching, reporting a bug, submitting a pull request, etc.? Full on Git stuff can be pretty complicated, and it's technically not directly related to programming, so it feels a bit mean to add it early on in the curriculum, but on the other hand, knowing how to search through the existing issues and report new bugs is relevant from the start.

**Comment by BerkeleyTrue** [comment]
This is something on our roadmap. @QuincyLarson would know more about where this should go.

**Comment by benschenker** [comment]
I almost posted a duplicate issue for this!
My detailed requests (I have no problem helping to make this too!):

I propose that instead of seeing below
```
Did you find a bug?
This will open our GitHub Issues page.
Please tell us how to reproduce the bug and link us to screenshots if possible.
```
when they click on `bug`, they should be brought to a waypoint that has video and clear steps that a user should take to file a bug on Github.

At the minimum this should include:
* Refresh the page/clear browser cache
* Ask for help in gitter first
* Search for relevant issues that have already been filed
* Create replication steps and a screenshot of the issue

I don't think it needs to explain the pull request process, just what issues are and what steps to do before filing one.

**Comment by BerkeleyTrue** [comment]
@benschenker Could you create an article in the wiki with this information?

**Comment by benschenker** [comment]
Sure, I'm on it!

**Comment by benschenker** [comment]
Thoughts? https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help!-I've-Found-a-Bug

Do you think we could change the link from the challenges to go straight there?

**Comment by BerkeleyTrue** [comment]
![best-memes-star-trek](https://cloud.githubusercontent.com/assets/6775919/9420956/7411ee96-4820-11e5-89ce-25005e9b66d3.jpg)

**Comment by BerkeleyTrue** [comment]
We'll keep this open as this needs to also be a waypoint after sign up with github.

**Comment by BerkeleyTrue** [comment]
We also need a wiki on creating PRs that include proper titles and adding `closes #1337` and such.

**Comment by benschenker** [comment]
Thanks!  My main concern is removing the link on the challenges that brings them directly to posting a new issue on Github, as that is probably where 90% of the issues come from.   It should link directly to that wiki post

**Comment by benschenker** [comment]
I can try to work on that but clearly I have not mastered the PR formatting and whatnot :stuck_out_tongue_winking_eye:

**Comment by BerkeleyTrue** [comment]
I can edit as well. I'm particular on these things.

**Comment by ahstro** [comment]
I've taken down some notes for a future Git/GitHub waypoint. If someone's writing a wiki page, none, one, some or all of the following might be of interest:

* When opening an issue by clicking `Bug` on FCC, remove the pre-generated comment text, but keep the first sentence with the link to the challenge.
* Write a meaningful title that describes the issue. Some good examples are `Logging in from the News and Field Guide pages doesn't redirect properly (using e-mail)` and `Typo: "for" instead of "while" loop`; bad examples include `A bug`, `HELP!!!11` and `I found this bug in a waypoint`.
* Keep the title relatively short, the description is for further information. One example is to shorten long waypoint names, so instead of writing `Test case bug in 'Waypoint: Check Radio Buttons and Checkboxes by Default'`, you might want to write `Test case bug in 'Radio Buttons'-waypoint`.
* Use line breaks for readability.
* Before posting your bug report, open the `Preview` panel and make sure everything looks good, pasted code is visible, images are of a proper size, etc.
* When including code in your bug report, don't just screenshot it, always copy and paste the code and wrap it in ``` so that everyone can see it.
* Don't reference challenges by number, as they might change at any time. Include names and links.
* When referencing other issues or pull requests, simply write #issue/pr-number.
* When submitting a PR or commit that fixes an issue, use one of the [keywords](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) along with the #issue-number to automatically close it on merge.


Resources
======
* https://try.github.io/
* http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by benschenker** [comment]
@ahstro some of that should definitely be in https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue, feel free to edit it!

**Comment by ahstro** [comment]
I haven't had the chance to pour over the wiki yet, still a bit overwhelming. I'll check it out when I have time and will edit if I feel like I can add something, but if you have the time, please add whatever you want from the above list :)

**Comment by benschenker** [comment]
Sure, I just made that one 2 days ago.  I'll try to incorporate some of those points (I like your example titles better than mine!),  but do check it out and edit as you see fit

**Comment by benschenker** [comment]
@ahstro I just updated it with some of your comments

**Comment by BerkeleyTrue** [comment]
Looks like this is done!

Happy Coding!
