### ISSUE TITLE
Use the abbreviated hex code for the color green Issue

### ISSUE THREAD

**Issue by chammock** [FreeCodeCamp/FreeCodeCamp#11105]
Challenge [Use Abbreviated Hex Code](https://www.freecodecamp.com/challenges/use-abbreviated-hex-code#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20%23F00%3B%0A%20%20%7D%0A%20%20.fuchsia-text%20%7B%0A%20%20%20%20color%3A%20%23F0F%3B%0A%20%20%7D%0A%20%20.cyan-text%20%7B%0A%20%20%20%20color%3A%20%230FF%3B%0A%20%20%7D%0A%20%20.green-text%20%7B%0A%20%20%20%20color%3A%20%230F0%3B%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22fuchsia-text%22%3EI%20am%20fuchsia!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22cyan-text%22%3EI%20am%20cyan!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22green-text%22%3EI%20am%20green!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Will not allow me to pass level. Gives me red X on "Use the abbreviated hex code for the color green instead of the hex code #00FF00." 
![error](https://cloud.githubusercontent.com/assets/16484278/19211112/969ef8f8-8cfa-11e6-8c68-9d2d77dede8f.png)

My code:
```html

<style>
  .red-text {
    color: #F00;
  }
  .fuchsia-text {
    color: #F0F;
  }
  .cyan-text {
    color: #0FF;
  }
  .green-text {
    color: #0F0;
  
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="fuchsia-text">I am fuchsia!</h1>

<h1 class="cyan-text">I am cyan!</h1>

<h1 class="green-text">I am green!</h1>

```

**Comment by vladas1987** [comment]
I have the same problem :(

**Comment by vladas1987** [comment]
I found problem
need change from 

 .fuchsia-text {
    color: 	#0F0;
  }

to

 .fuchsia-text {
    color: 	#F0F;
  }

**Comment by Razorsharpy** [comment]
you have to close the .green-text {
                                           color: #0F0;
                                   }

**Comment by Razorsharpy** [comment]
.green-text {
color: #0F0;
}
