### ISSUE TITLE
A big bug!

### ISSUE THREAD

**Issue by stringlady** [FreeCodeCamp/freecodecamp#1111]
Challenge http://www.freecodecamp.com/challenges/waypoint-override-styles-with-important has an issue. The tags are not working and is making the rest of the style tag a paragraph

**Comment by LumenTeun** [comment]
You are going to have to provide more information than this. How does your code look? Which tags are not working, and how?

**Comment by mongui** [comment]
Just tested and the challenge works perfectly.
