### ISSUE TITLE
Bug under Understanding Case Sensitivity in Variables

### ISSUE THREAD

**Issue by talluri-crm** [FreeCodeCamp/FreeCodeCamp#11117]
![bug](https://cloud.githubusercontent.com/assets/22477309/19217674/89b4b860-8da6-11e6-8fa7-eb544769f0cf.jpg)
Challenge [Understanding Case Sensitivity in Variables](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables#?solution=%0A%2F%2F%20Declarations%0Avar%20StudlyCapVar%3B%0Avar%20properCamelCase%3B%0Avar%20TitleCaseOver%3B%0A%0A%2F%2F%20Assignments%0AStudlyCapVar%20%3D%2010%3B%0AProperCamelCase%20%3D%20%22A%20String%22%3B%0ATitleCaseOver%20%3D%209000%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Declarations
var StudlyCapVar;
var properCamelCase;
var TitleCaseOver;

// Assignments
StudlyCapVar = 10;
ProperCamelCase = "A String";
TitleCaseOver = 9000;

```

**Comment by mfzz** [comment]
This is not a bug. Check your first character of assignments variables and compare it with the instructions.

**Comment by dhcodes** [comment]
Case matters as @mfzz has pointed out. Happy coding.

**Comment by talluri-crm** [comment]
Yeah my bad. Thank you though.
Varun

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 8, 2016 at 10:35 PM, mfzz<notifications@github.com> wrote:   
This is not a bug. Check your first character of assignments variables and compare it with the instructions.

**Comment by IEPTECH** [comment]
Porque am I in this email group? Porque why?

Pablo Rodriguez

**Comment by texas2010** [comment]
@IEPTECH, looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!
