### ISSUE TITLE
Passed the challenge by multiplying by 100

### ISSUE THREAD

**Issue by zaidfaridi** [FreeCodeCamp/FreeCodeCamp#11110]
Challenge [Generate Random Whole Numbers with JavaScript](https://www.freecodecamp.com/challenges/generate-random-whole-numbers-with-javascript#?solution=%0Avar%20randomNumberBetween0and19%20%3D%20Math.floor(Math.random()%20*%2020)%3B%0A%0Afunction%20randomWholeNum()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20var%20math%20%3D%20%20Math.floor(Math.random()%20*%20100)%3B%0A%20%20return%20math%3B%0A%20%20%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function randomWholeNum() {

  // Only change code below this line.
 var math =  Math.floor(Math.random() * 100);
  return math;
  
}
 
If we multiply by 100 , the challenge accepts the answer although the whole number is beyond 9.
```

**Comment by petrgazarov** [comment]
I'm able to reproduce this and I would like to work on it.

**Comment by taigar4** [comment]
pleasse i need smtp login and username for send test for my site plezz hellp
