### ISSUE TITLE
Margins: Re-Order Tests to run in Top-Right-Bottom-Left order

### ISSUE THREAD

**Issue by SherylHohman** [FreeCodeCamp/FreeCodeCamp#11111]
Challenge [Add Different Margins to Each Side of an Element](https://www.freecodecamp.com/challenges/add-different-margins-to-each-side-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Currently tests are run in Top, Left, Right, Bottom order.
Similar to issue #11059, it would be better if they were run in order of Top-Right-Bottom-Left.

I would like to work on this one, if OK.
I believe I found the correct file and location for the edit..
I am busy rest of today, but could have it done tomorrow.

Thanks :-)
-Sheryl

**Comment by Bouncey** [comment]
In your own time @ :+1:
