### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by stringlady** [FreeCodeCamp/freecodecamp#1112]
Challenge http://www.freecodecamp.com/challenges/waypoint-override-styles-with-important has an issue. I did what the directions said but the text is not red!

**Comment by LumenTeun** [comment]
Same as with #1111, we need more information. Start by posting the code you used wrapped in ``` so we can make sure it's actually a problem with FreeCodeCamp.

**Comment by BerkeleyTrue** [comment]
@stringlady You might try the help chat room first at https://gitter.im/freecodecamp/help and see if you can get help there when you are stuck. We have an awesome community that loves to help out.
