### ISSUE TITLE
montenegro

### ISSUE THREAD

**Issue by Newpostlogger** [FreeCodeCamp/FreeCodeCamp#11123]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by atjonathan** [comment]
@newpostlogger, if this issue is valid, please reopen and correctly fill in the issue description.

**Comment by Newpostlogger** [comment]
@whije a
