### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by callumrichards1886** [FreeCodeCamp/FreeCodeCamp#11132]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%3Cstyle%3E%0A%C2%A0.red-text%20%7Bcolor%3Ared%3B%7D%0A%3C%2Fstyle%3E%0A%0A%20%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
 .red-text {color:red;}
</style>

 <h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>


```

**Comment by ananaymital** [comment]
@callumrichards1886 you code works fine according to me. Please try again or explain error the error you face. 
In the future, please post in the [HelpJavascript](https://gitter.im/FreeCodeCamp/HelpJavaScript) Gitter channel first. If the consensus there is that it is a bug, then you should post here.

**Comment by ivantedja** [comment]
@callumrichards1886  There is a weird character before your ` .red-text {color:red;}`. Try to remove that

**Comment by texas2010** [comment]
@callumrichards1886, were you working on this challenge on your phone or tablet?  let me know about that.  there have issue with android would cause challenge wont pass.

**Comment by lucasoliv** [comment]
I am having problems as well with this challenge, maybe it's because I am doing it through my android smartphone :/

**Comment by iamalio** [comment]
Same here...I really thought I was just not getting it but now I see I am not the only one. Also on Android.
