### ISSUE TITLE
aa

### ISSUE THREAD

**Issue by aakashali444** [FreeCodeCamp/FreeCodeCamp#11133]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%20%20font-size%3A16px%3B%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3E%0APurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%0A%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
    font-size:16px; }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>
Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.
</p>
```

**Comment by ananaymital** [comment]
@aakashali444 you have a small error in your code. In the future, please post in the [HelpJavascript](https://gitter.im/FreeCodeCamp/HelpJavaScript) Gitter channel first. If the consensus there is that it is a bug, then you should post here. 
Hint: `p` tags should have font-size 16px

**Comment by texas2010** [comment]
sorry about @ananaymital give you wrong link. this correct link is [Help chat room](https://gitter.im/FreeCodeCamp/Help) for html and css.

Happy Coding.

**Comment by ananaymital** [comment]
Sorry didn't realize that

**Comment by atjonathan** [comment]
@ananaymital, no problem! Thanks for helping out!
