### ISSUE TITLE
Tests adding 2 to expected results

### ISSUE THREAD

**Issue by jeremiahbiard** [FreeCodeCamp/FreeCodeCamp#1113]
Challenge http://www.freecodecamp.com/challenges/bonfire-no-repeats-please has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The tests for this bonfire are adding two to the expected results. This somehow causes the bonfire checker to hang a bit and the tests to fail.

![screenshot 1](https://cloud.githubusercontent.com/assets/7762303/8343900/9bea40f8-1aa8-11e5-8d8c-c650f0f5021a.png)

**Comment by benschenker** [comment]
Hey @jeremiahbiard 

Is this still not working for you?  Can you post all the code so we can try to replicate?

**Comment by su6a12** [comment]
I'm still seeing the issue where all the solutions are +2 of my outputs.

var result = [], usedCharsSoFar = [];
function permAlone(str) {
 
  var currentChar, inputArr = str.split('');
  
  for(var i = 0; i < inputArr.length; i++) {
    
    currentChar = inputArr.splice(i, 1);
    
    usedCharsSoFar.push(currentChar);
    
    if (inputArr.length === 0) {
      if (usedCharsSoFar.join('').search(/(.)\1/) === -1) {
          result.push(usedCharsSoFar.join(''));
      }
    }
    permAlone(inputArr.join(''));
    
    inputArr.splice(i, 0, currentChar);
    
    usedCharsSoFar.pop();
  }
  return result.length;
}

**Comment by benschenker** [comment]
Hey @su6a12 thanks for posting your code.

There are various reasons why that may not be working, the first of which is that you declare
```
var result = [], usedCharsSoFar = [];

**Comment by su6a12** [comment]
@benschenker I realized the issue.  The first call to perAlone doesn't get erased and the result there is 2, which explains the 2+ for all of the test scenarios.
