### ISSUE TITLE
not running chalenge

### ISSUE THREAD

**Issue by MuhammadHanzala** [FreeCodeCamp/FreeCodeCamp#11146]
Challenge [Declare String Variables](https://www.freecodecamp.com/challenges/declare-string-variables#?solution=%0A%2F%2F%20Example%0Avar%20firstName%20%3D%20%22Alan%22%3B%0Avar%20lastName%20%3D%20%22Turing%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%0Avar%20firstName%20%3D%20%22Al%22%3B%0Avar%20lastName%20%3D%20%22Tur%22%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var firstName = "Alan";
var lastName = "Turing";

// Only change code below this line


var firstName = "Al";
var lastName = "Tur";
```

**Comment by ananaymital** [comment]
@MuhammadHanzala you have a small (very small) error in your code. In the future, please post in the [HelpJavascript](https://gitter.im/FreeCodeCamp/HelpJavaScript) Gitter channel first. If the consensus there is that it is a bug, then you should post here. Hint: Look at the required variable names.

**Comment by erictleung** [comment]
@MuhammadHanzala please check out the instructions once more. You need to properly name your variables asked for in the challenge.

> Create two new string variables: `myFirstName` and `myLastName` and assign them the values of your first and last name, respectively.

Please check out the Gitter chat rooms as well. Happy coding!
