### ISSUE TITLE
Remove challenges from URL slug

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#11141]
We can shorten the URL slug by removing the word "challenges." This will make URLs easier to read and will improve our SEO
![](https://www.evernote.com/l/Ar_n4_pesR1GRpJ4LU_lzAdijYUCbNMehyoB/image.png)

**Comment by Bouncey** [comment]
Favouring the second instance of this issue for detail

**Comment by QuincyLarson** [comment]
@Bouncey that is a different issue. This involves removing the word "challenges" from our path.

**Comment by tmpvnunes** [comment]
Can I solve this issue?

**Comment by QuincyLarson** [comment]
@tmpvnunes yes. You're welcome to take a crack at it. Do you have Free Code Camp running locally?

**Comment by tmpvnunes** [comment]
Yes, I have a copy on my desktop. I am a newbie on Github at the moment I really want to understand free code camp project and a bit more of GitHub.

**Comment by Bouncey** [comment]
@BerkeleyTrue @QuincyLarson Is this even possible without a big refactor of `./server/boot/react.js`, amongst others?

**Comment by QuincyLarson** [comment]
@Bouncey it will require a heavy refactor but it will be worth it in terms of simplifying our URL structure.

**Comment by BerkeleyTrue** [comment]
@QuincyLarson We cannot remove challenges completely. This makes the backend logic incredibly difficult. How does this improve SEO? Is it really a huge benefit that we should add so much complexity to our routes?

**Comment by QuincyLarson** [comment]
@BerkeleyTrue shorter URLs are believed to be better for SEO than longer ones, and less subfolders is better than more subfolders: https://moz.com/blog/15-seo-best-practices-for-structuring-urls

**Comment by QuincyLarson** [comment]
@BerkeleyTrue this isn't a high priority - if you'll note the SEO project is stacked behind shipping react. But it is something we should do eventually.

**Comment by BerkeleyTrue** [comment]
> There's no hard and fast requirement—this is another one where it's important to use your best judgement.

This is definitely something we should NOT do if this is not a hard rule. The amount of overload on the first and second subpath by removing challenges would add a lot of complexity (reduce performance, increase redirects, slow res times) that I don't want to see. 

I can see us shorting `challenges` to something else, but we cannot remove the subpath for a perceived minor benefit.

**Comment by Bouncey** [comment]
@BerkeleyTrue @QuincyLarson could we set up routes for each block then get the challenge dashed name only from params? 

This would also give us a place for these landing pages you are after @QuincyLarson 

So the routes would be setup like: 
`app.get('/html(/:dashedName)', (req, res) => ...`
`app.get('/css(/:dashedName)', (req, res) => ...`
`app.get('/nodejs(/:dashedName)', (req, res) => ...`

**Comment by QuincyLarson** [comment]
@BerkeleyTrue with SEO, everything is "perceived" as you said. SEO is a black box. I was thinking something like what @Bouncey just proposed. Either way, as I said, this is not a priority so we can discuss this further after shipping react. This is the top priority right now: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10901
