### ISSUE TITLE
Issue in javascript challenge

### ISSUE THREAD

**Issue by kkn1234** [FreeCodeCamp/FreeCodeCamp#11143]
Challenge is not completed but i can see the output is getting update in console properly as per the challenge.

#### Challenge Name

https://www.freecodecamp.com/challenges/record-collection#?solution=%0A%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%20%222548%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20%22artist%22%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%222468%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%221999%22%2C%0A%20%20%20%20%20%20%22artist%22%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%221245%22%3A%20%7B%0A%20%20%20%20%20%20%22artist%22%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%225439%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20updateRecords(id%2C%20prop%2C%20value)%20%7B%0A%20%20switch(prop)%7B%0A%20%20%20%20case%20%22tracks%22%3A%0A%20%20%20%20%20%20var%20%20res%3Dcollection%5Bid%5D.hasOwnProperty('tracks')%3B%0A%20%20%20%20%20%20if(res)%7B%20%0A%20%20%20%20%20%20%20%20%20if(value%20!%3D%3D%22%22)%0A%20%20%20%20%20%20%20%20%20%20%20%20collection%5Bid%5D.tracks.push(value)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%7Delse%7B%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20collection%5Bid%5D.tracks%20%3D%20value%3B%0A%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20case%20%22artist%22%3A%0A%20%20%20%20%20%0A%20%20%20%20%20%20if(collection%5Bid%5D.hasOwnProperty('artist'))%7B%0A%20%20%20%20%20%20%20%20%20if(value%20!%3D%3D%22%22)%7B%0A%20%20%20%20%20%20%20%20%20%20%20collection%5Bid%5D.artist%3Dvalue%3B%20%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20else%20%7B%0A%20%20%20%20%20%20%20%20if(value%20!%3D%3D%20%22%22)%0A%20%20%20%20%20%20%20%20%20%20collection%5Bid%5D.artist%3Dvalue%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20break%3B%0A%20%20%7D%0A%2F%2F%20%20collection%5Bid%5D.prop%3D%20value%3B%0A%20%20return%20collection%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0AupdateRecords(2468%2C%20%22tracks%22%2C%20%22Free%22)%3B%0A%0A

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 8.0
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
 
// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  switch(prop){
    case "tracks":
      var  res=collection[id].hasOwnProperty('tracks');
      if(res){ 
         if(value !=="")
            collection[id].tracks.push(value);
           }else{  
            collection[id].tracks = value;
         }
      break;
      
      case "artist":
     
      if(collection[id].hasOwnProperty('artist')){
         if(value !==""){
           collection[id].artist=value; 
          }
      }
      else {
        if(value !== "")
          collection[id].artist=value;
      }
      break;
  }
//  collection[id].prop= value;
  return collection;
}

// Alter values below to test your code

updateRecords(5439, "artist", "ABBA");
updateRecords(5439, "tracks", "Take a Chance on ME");
updateRecords(2548, "artist", "");
updateRecords(1245, "tracks", "Addicted to Love");
updateRecords(2468, "tracks", "Free");
updateRecords(2548, "tracks", "");
[Freecodecamp_snapshot.docx](https://github.com/FreeCodeCamp/FreeCodeCamp/files/519090/Freecodecamp_snapshot.docx)

 
```

**Comment by Bouncey** [comment]
@kkn1234 There multiple issues with your code, including syntax errors. 

GitHub issues are not for code help, please read the instructions again and try and see where you are going wrong. Also, read your code again, there are `{`&`}` missing in a few places. If you are still stuck, click the `Help` button and you will be taken to a dedicated chat room where there are plenty of people willing to help.

One tip before you go, you cannot push an item to an `undefined` value

Happy Coding
