### ISSUE TITLE
Add category to challenge view title element and h1 element 

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#11142]
For SEO purposes, we should include the challenge category (JavaScript, HTML, Node.js, etc.) both in the `<title>` element and in the `<h1>` element before the challenge's name.

For example:

![](http://i.imgur.com/WhegItY.png)

**Comment by andmckvr13** [comment]
I would like to try and solve this issue

**Comment by atjonathan** [comment]
@QuincyLarson, @andmckvr13: This doesn't need changed before the challenges name. I will be doing this in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11061 😉

**Comment by andmckvr13** [comment]
@atjonathan bummer, next time then. okay thanks anyways

**Comment by atjonathan** [comment]
@andmckvr13, np! You can still work on the title tag tho!

**Comment by andmckvr13** [comment]
@atjonathan great!! On it :)

**Comment by andmckvr13** [comment]
@QuincyLarson @atjonathan should the "get set for our basic algorithm challenges" be labeled with the JavaScript tag? I figured that it should be, but don't want to make assumptions

**Comment by andmckvr13** [comment]
@QuincyLarson @atjonathan shall I also update the Spanish titles too?

**Comment by atjonathan** [comment]
@andmckvr13, yes please for other languages! Tagging @QuincyLarson for the other question

**Comment by tmpvnunes** [comment]
What about Portuguese? I can contribute :)

**Comment by QuincyLarson** [comment]
@tmpvnunes yes - we would welcome your contributions! Many of our challenges have already been translated into Portuguese. Join gitter.im/freecodecamp/contributors and ask @vtamara to help you get started :)

**Comment by QuincyLarson** [comment]
I'm closing this in favor of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11061 which is very similar.
