### ISSUE TITLE
Using Objects for Lookups - Dot notation does not work

### ISSUE THREAD

**Issue by braxtonfair** [FreeCodeCamp/FreeCodeCamp#11152]
#### Challenge Name
Using Objects for Lookups
[https://www.freecodecamp.com/challenges/using-objects-for-lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups)

#### Issue Description
Dot notation would not work on line 16. Since .val is a reserved keyword by Javascript/jQuery, and the argument name is **val**, only bracket notation would satisfy the tests.
```js
// Both of these should work, and is taught to us
result = lookup[val]; # Works
result = lookup.val;  #Does not work
```
Since we are taught both notations, some campers might like dot notation(personally, I do) over bracket notation, so they would use that. They would come to find that method wouldn't work.

As far as my knowledge, this should work, maybe change the argument name?

#### Browser Information
User agent:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
```

#### Your Code
```js

// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  var lookup = {
    alpha: "Adams",
    bravo: "Boston",
    charlie: "Chicago",
    delta: "Denver",
    echo: "Easy",
    foxtrot: "Frank"
  };
  
  result = lookup[val]; // This is line 16 as talked about above
  
  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");
```

**Comment by erictleung** [comment]
@braxtonfair thanks for the issue. However, this is more of a coding error than a bug. Please review the [dot notation](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-the-dot-operator) challenge on how to use correctly use dot notation. Here's an example that might help.

```js
var val = "alpha";
var lookup = {
    alpha: "Adams",
    bravo: "Boston",
    charlie: "Chicago",
    delta: "Denver",
    echo: "Easy",
    foxtrot: "Frank"
  };
console.log(lookup[val]); // Returns "Adams"
console.log(lookup.val);  // Returns undefined
```

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
