### ISSUE TITLE
Profie Lookup Issuue

### ISSUE THREAD

**Issue by Shivank98** [FreeCodeCamp/FreeCodeCamp#11155]
//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];

function lookUp( firstName, prop ){
  for( var i = 0; i < contacts.length; i++ ){
    if( firstName == contacts[i].firstName ) {
      if( contacts[i].hasOwnProperty( prop ) ) {
        return contacts[i][prop];
      } else {
        return "No such property";
      }
    }
  }
  return "No such contact";
}                                       
// Change these values to test your function
lookUp("Akira", "address");

#### Challenge Name
profile lookup issue

#### Issue Description
my program is running showing desired value bt no showing tick mark ......

#### Browser Information
google chrome
widows 7 ult.

#### Your Code
216
 
 
```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by dhcodes** [comment]
@Shivank98 This is an issue with the name of the function. I believe it may have simply been `lookUp` in the past and was updated at some point to `lookUpProfile`. You would only see this if you reset your code or opened the challenge in incognito.

Change the function name and call to `lookUpProfile` and it should pass.

**Comment by scvasquez19901024** [comment]
I have the same issue, there is something curious with  this challenge when I comment the if else and else statement the compiler get good results with the test that relation with if statement.

Here is my code:

var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];


function lookUpProfile(firstName, prop){
// Only change code below this line
  
  for(var i=0;i<contacts.length;i++){
    
        if(contacts[i].firstName==firstName &&       contacts[i].hasOwnProperty(prop)){
      
      return contacts[i][prop];
       
        }else if (contacts[i].firstName!=firstName){
          return "No such contact";
        }else{
            return "No such property";      
        }
    
  }

// Only change code above this line
}

// Change these values to test your function

lookUpProfile("Kristian", "lastName");

**Comment by Sega-Patidar** [comment]
This code is working
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];

function lookUpProfile(firstName, prop){
// Only change code below this line
  for( var i=0; i<contacts.length; i++){
   if(firstName == contacts[i].firstName)
   {
     if(contacts[i].hasOwnProperty(prop))
       {
         return contacts[i][prop];
       }
     else if(contacts[i].hasOwnProperty(prop)!=prop)
       {
        return "No such property";
       }
     else if (contacts[i].firstName!=firstName){
      if(contacts[i].hasOwnProperty(prop)!=prop){
         return "No such contact";
      }
    }
    }}
 return "No such contact";
// Only change code above this line
}
// Change these values to test your function
lookUpProfile("Bob", "number");
