### ISSUE TITLE
Lesson Find the Length of a String

### ISSUE THREAD

**Issue by josh2123** [FreeCodeCamp/FreeCodeCamp#11150]
Challenge [Find the Length of a String](https://www.freecodecamp.com/challenges/find-the-length-of-a-string#?solution=%0A%2F%2F%20Example%0Avar%20firstNameLength%20%3D%200%3B%0Avar%20firstName%20%3D%20%22Ada%22%3B%0A%0AfirstNameLength%20%3D%20firstName.length%3B%0A%0A%2F%2F%20Setup%0Avar%20lastNameLength%20%3D%200%3B%0Avar%20lastName%20%3D%20%22Lovelace%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20lastNameLength%20%3D8%3B%0Avar%20lastName%20%3D%20%22Lovelace%22%3B%0A%0AlastNameLengt%20%3D%20lastName.length%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var firstNameLength = 0;
var firstName = "Ada";

firstNameLength = firstName.length;

// Setup
var lastNameLength = 0;
var lastName = "Lovelace";

// Only change code below this line.
var lastNameLength =8;
var lastName = "Lovelace";

lastNameLengt = lastName.length;



```

**Comment by ananaymital** [comment]
@josh2123 you have a small error in your code. Please re-read the instruction and the tests to be passed. In the future, please post in the [HelpJavascript](https://gitter.im/FreeCodeCamp/HelpJavaScript) Gitter channel first. If the consensus there is that it is a bug, then you should post here.

**Comment by josh2123** [comment]
the error that you saw was required in order to pass the test, so i posted it.

**Comment by ananaymital** [comment]
@josh2123 You should've posted on the channel first. This platform is for bugs. I am online may be I can help

**Comment by aovsne** [comment]
lmao.. this convo is kinna funny though!
