### ISSUE TITLE
Note Due to browser implementation differences, you may need to be at 100% zoom to pass the tests on this challenge.

### ISSUE THREAD

**Issue by lydatech** [FreeCodeCamp/FreeCodeCamp#11153]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```
Can we please remove the text in the instructions:

>Note
>Due to browser implementation differences, you may need to be at 100% zoom to pass the tests on >this challenge.

It is extremely confusing for new campers. They keep trying to figure out what they should do. We field 3-4 questions about this text every day. It would be way easier to fix the issue if they have it because of the setting in the browser than having them ask when there is no issue to begin with.
Thank you

**Comment by dhcodes** [comment]
I tend to agree. I would hazard a guess that most users don't mess with their zoom settings for it to be an issue.

**Comment by tadake** [comment]
Do you guys need someone to remove the text in the instructions? if so I'd love to help.

**Comment by dhcodes** [comment]
@tadake We'll let a few more people weigh in, but if so, it's yours.

**Comment by dhcodes** [comment]
cc @FreeCodeCamp/issue-moderators

**Comment by Bouncey** [comment]
:+1:

**Comment by atjonathan** [comment]
:+1:
@tadake, you have the go ahead!

**Comment by diomed** [comment]
this needs to be removed ASAP

**Comment by tadake** [comment]
woo hoo!

**Comment by conoh** [comment]
i've inputed the correct code for this challenge and still can't get past it.

**Comment by enviso** [comment]
So how do we get past this step?

**Comment by miank** [comment]
Still facing the issue with this step.

**Comment by miank** [comment]
Separating the the paragraph style will fix it up.
