### ISSUE TITLE
What Is Happening.....?

### ISSUE THREAD

**Issue by Shivank98** [FreeCodeCamp/FreeCodeCamp#11158]
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#?solution=var%20result%3D1%3B%0Afunction%20factorialize(num)%20%0A%0A%7B%0A%20%20for(num%3B%20num%3E0%3B%20num--)%7B%0A%20%20result%3Dresult*num%3B%0A%20%20%20%20%0A%7D%0Areturn%20result%3B%0A%7D%0A%0Afactorialize(10)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var result=1;
function factorialize(num) 

{
  for(num; num>0; num--){
  result=result*num;
    
}
return result;
}

factorialize(10);

```

THE CODE I WROTE IS CORRECT,ITS SHOWING THE DESIRED RESULT BUT ITS NOT GETTING IT CORRECT

**Comment by dhcodes** [comment]
@Shivank98 Please consider using the chat room for help or to confirm an issue before posting it here. In this case, the issue is that some challenges have issues with global vars. Move `var result=1;` into the function and it should pass.
