### ISSUE TITLE
Code not running and I don't see any errors

### ISSUE THREAD

**Issue by knoahg** [FreeCodeCamp/FreeCodeCamp#11156]
Challenge [Understanding Case Sensitivity in Variables](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables#?solution=%2F%2F%20Declarations%0Avar%20studlyCapVaR%3B%0Avar%20properCamelCase%3B%0Avar%20titleCaseOver%3B%0A%0A%2F%2F%20Assignments%0AstudlyCapVar%20%3D%2010%3B%0AproperCamelCase%20%3D%20%22A%20String%22%3B%0AtitleCaseOver%20%3D%209000%3B%0A%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Declarations
var studlyCapVaR;
var properCamelCase;
var titleCaseOver;

// Assignments
studlyCapVar = 10;
properCamelCase = "A String";
titleCaseOver = 9000;





```

**Comment by ananaymital** [comment]
@knoahg you have a small error in the declaration of `studlycapVar`. 
In the future, please post in the [HelpJavascript](https://gitter.im/FreeCodeCamp/HelpJavaScript) Gitter channel first. If the consensus there is that it is a bug, then you should post here.
