### ISSUE TITLE
Test function call passes but challenge remains incomplete - RESOLVED

### ISSUE THREAD

**Issue by KyeBuff** [FreeCodeCamp/FreeCodeCamp#11165]
Challenge [Multiple Identical Options in Switch Statements](https://www.freecodecamp.com/challenges/multiple-identical-options-in-switch-statements#?solution=%0Afunction%20sequentialSizes(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20switch(val)%20%7B%0A%20%20%20%20%20%20%0A%20%20%20%20case%201%3A%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20%20%20answer%3D%22low%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%204%3A%0A%20%20%20%20case%205%3A%0A%20%20%20%20case%206%3A%0A%20%20%20%20%20%20answer%3D%22mid%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%207%3A%0A%20%20%20%20case%208%3A%0A%20%20%20%20case%209%3A%20%0A%20%20%20%20%20%20answer%3D%22high%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AsequentialSizes(1)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Complete challenge using a valid solution and run tests, page scrolls slightly and console updates but challenge incomplete. 

My code:
```javascript

function sequentialSizes(val) {
  var answer = "";
  // Only change code below this line
  
  switch(val) {
      
    case 1:
    case 2:
    case 3:
      answer="low";
      break;
    case 4:
    case 5:
    case 6:
      answer="mid";
      break;
    case 7:
    case 8:
    case 9: 
      answer="high";
      break;
  }
  
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
sequentialSizes(1);


```

**Comment by BhaveshSGupta** [comment]
You need to make the first letter capital for each answer, i.e. Low, Mid and High

**Comment by KyeBuff** [comment]
Thanks, that was silly of me!
