### ISSUE TITLE
Check for Palindromes Issue

### ISSUE THREAD

**Issue by dennisthadathil** [FreeCodeCamp/FreeCodeCamp#11161]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20string%20%3D%20str.toLowerCase()%3B%0A%20%20string%20%3D%20string.replace(%2F%5B%5Ea-z%5D%2Fg%2C%22%22)%3B%0A%0Avar%20array%20%3D%20string.split(%22%22)%3B%0Aarray.reverse()%3B%0Avar%20pstring%20%3D%20array.join(%22%22)%3B%0Aif%20(pstring%20%3D%3D%3D%20string)%7B%0A%20%20return%20true%3B%20%0A%7Delse%7B%0A%20%20return%20false%3B%0A%7D%0A%0A%7D%0A%0A%0A%0Apalindrome(%221%20eye%20for%20of%201%20eye.%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
![unbenannt](https://cloud.githubusercontent.com/assets/20542781/19284814/b4db5eec-8ff7-11e6-9329-a9155305a35b.PNG)

My code:
```javascript

function palindrome(str) {
  // Good luck!
  var string = str.toLowerCase();
  string = string.replace(/[^a-z]/g,"");

var array = string.split("");
array.reverse();
var pstring = array.join("");
if (pstring === string){
  return true; 
}else{
  return false;
}

}



palindrome("1 eye for of 1 eye.");

```

**Comment by erictleung** [comment]
@dennisthadathil thanks for the issue but the challenge is correct as specified in the instructions.

> You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes.

In other words, keep all alpha**numeric** characters. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
