### ISSUE TITLE
Alleged syntax error in correct Js code

### ISSUE THREAD

**Issue by bilgiprog** [FreeCodeCamp/FreeCodeCamp#11162]
Challenge [Profile Lookup](https://www.freecodecamp.com/challenges/profile-lookup) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.

The code below displays "Syntax Error: expected expression..." and does not run the tests. However it is correct Javascript code, and it executes and displays result in Firefox Scratchpad and Node 0.12

My code:
```javascript

//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];


function lookUpProfile(firstName, prop){
// Only change code below this line
for (var i=0; i<contacts.length; ++i)
    if (contacts[i].firstName == firstName)
      if (contacts[i].hasOwnProperty(prop))
        return contacts[i][prop];
      else 
        return "No such property";
  
  return "No such contact";
// Only change code above this line
}

// Change these values to test your function
lookUpProfile("Akira", "likes");

```

**Comment by dhcodes** [comment]
@bilgiprog your code has a syntax error. While it may pass in other editors and environments, the editor used by fcc has strict syntactic requirements regarding curly braces. Please consider asking for help in the Gitter chat room for JavascriptHelp by clicking the Help button on the challenge.

**Comment by bilgiprog** [comment]
My code does not have a syntax error. It is your own non-standard way of processing Javascript.

**Comment by dhcodes** [comment]
Your for loop doesn't have opening and closing brackets, nor do your if/else statements. I'm not sure what you mean by non-standard.

**Comment by Shiv-Shakti** [comment]
for (var i=0; i<contacts.length; ++i)
    if (contacts[i].firstName == firstName)
     {if (contacts[i].hasOwnProperty(prop))
        return contacts[i][prop];
      else 
        return "No such property";
     }
  return "No such contact";

This is it.....

**Comment by texas2010** [comment]
@Shiv-Shakti 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
