### ISSUE TITLE
Typeof of array is object - how to pass this test

### ISSUE THREAD

**Issue by ShahPriyankah** [FreeCodeCamp/FreeCodeCamp#11168]
Challenge [Using typeof](https://www.freecodecamp.com/challenges/using-typeof#?solution=%0Aconsole.log(typeof%20%22string%22)%3B%0A%0Aconsole.log(typeof%2010)%3B%0A%0Aconsole.log(typeof%20%5B%22Saab%22%2C%20%22Volvo%22%2C%20%22BMW%22%5D)%3B%0A%0Aconsole.log(typeof%20%7B%221%22%3A%222%22%2C%223%22%3A%224%22%7D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

console.log(typeof "string");

console.log(typeof 10);

console.log(typeof ["Saab", "Volvo", "BMW"]);

console.log(typeof {"1":"2","3":"4"});
```

**Comment by patrickk93** [comment]
The instructions state that you should 

> Try using typeof on each of the following to see which types they have.

It gives you examples of a string, number, array, and object. 

You could just type in the examples given on the side.

**Comment by ShahPriyankah** [comment]
How silly!! :):) Thanks!

**Comment by dhcodes** [comment]
Closing as resolved.
