### ISSUE TITLE
Add an example 

### ISSUE THREAD

**Issue by jinz2014** [FreeCodeCamp/FreeCodeCamp#11177]
Challenge [Pairwise](https://www.freecodecamp.com/challenges/pairwise) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function pairwise(arr, arg) {
  return arg;
}

pairwise([1,4,2,3,0,5], 7);

```
As an improvement, can you add an example to clarify the following ? 
If multiple pairs are possible that have the same numeric elements but different indices, return the smallest sum of indices. 

Thanks

**Comment by erictleung** [comment]
@jinz2014 thanks for the feedback. There's another issue suggesting a similar addition to the Pairwise challenge https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9037. Please take any additional comments over there. Happy coding!

**Comment by jinz2014** [comment]
A few suggestions:

1 Is there a next/previous button to go to the next/previous question ?
2 Are the solutions to questions stored somewhere when you sign in again ?

Thanks

**Comment by erictleung** [comment]
@jinz2014 

1. There is no previous or next button. There is a discussion on improving challenge navigation here https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10423.
2. If you visit your FreeCodeCamp profile page, you can see your coding solutions for each challenge https://www.freecodecamp.com/jinz2014

**Comment by jinz2014** [comment]
Thank you for your email!

________________________________
