### ISSUE TITLE
Not accepting Math.floor(Math.random(0.0,1) * 10).

### ISSUE THREAD

**Issue by GianmarcoSalerno** [FreeCodeCamp/FreeCodeCamp#11176]
Challenge [Generate Random Whole Numbers with JavaScript](https://www.freecodecamp.com/challenges/generate-random-whole-numbers-with-javascript#?solution=%0Avar%20randomNumberBetween0and19%20%3D%20Math.floor(Math.random()%20*%2020)%3B%0A%0Afunction%20randomWholeNum()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%0A%20%20return%20Math.floor(Math.random(0.0%2C1)%20*%2010)%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function randomWholeNum() {

  // Only change code below this line.
  
  return Math.floor(Math.random(0.0,1) * 10);
}

```

**Comment by ananaymital** [comment]
@GianmarcoSalerno you have a small error in your code. `Math.random()` returns a number between 0 and 1. It does not have take any arguments. [This documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random) might help.
In the future, please post in the [HelpJavascript](https://gitter.im/FreeCodeCamp/HelpJavaScript) Gitter channel first. If the consensus there is that it is a bug, then you should post here

**Comment by GianmarcoSalerno** [comment]
Ty

**Comment by erictleung** [comment]
Sounds like the issue has been resolved. Closing as resolved. Happy coding!
