### ISSUE TITLE
Waypoint Bug

### ISSUE THREAD

**Issue by jadchaar** [FreeCodeCamp/FreeCodeCamp#1117]
On the waypoint, "Waypoint: Add Font Awesome Icons to our Buttons", the challenge is to add the code, 
![screen shot](https://cloud.githubusercontent.com/assets/7388203/8347322/30d160d0-1ad5-11e5-80f1-3dc5b442d632.png), to the "Like" button element. If you copy or write that code in the "Delete" or "Info" button element, the challenge is accepted. The challenge should reject the code when it is placed in button code other than that of the "Like" button.

Thanks. This bug is small but still important.

**Comment by jniles** [comment]
I've also noticed this type of bug with which `<div>` or `<input>` element gets a class.  It would make things a lot clearer for those just getting into coding to have precise checks.

**Comment by benschenker** [comment]
Thanks @JC713 

It looks like this has been fixed as I can't replicate on http://www.freecodecamp.com/challenges/waypoint-add-font-awesome-icons-to-all-of-our-buttons

**Comment by a1rr0wh3ad** [comment]
I am able to replicate a similar issue on the same page.

![fireshot screen capture 004 - waypoint_ add font awesome icons to all of our buttons i free code camp - www_freecodecamp_com_challenges_waypoint-ad](https://cloud.githubusercontent.com/assets/812919/9485353/d122f4ea-4bea-11e5-88b5-e2ed16604acf.png)

![fireshot screen capture 005 - waypoint_ add font awesome icons to all of our buttons i free code camp - www_freecodecamp_com_challenges_waypoint-ad](https://cloud.githubusercontent.com/assets/812919/9485441/a97d6686-4beb-11e5-93a9-2eda732e9f52.png)


First picture has the circle icon within the delete button while the trash icon is within the info button.

Second picture has both icons within the info button.
