### ISSUE TITLE
Not showing next challenge even if i did as i were told to do(Topic: using .addclass to target id selector using #).

### ISSUE THREAD

**Issue by goyalritesh21** [FreeCodeCamp/FreeCodeCamp#11174]
![2016-10-12 2](https://cloud.githubusercontent.com/assets/22390990/19314942/84cc8240-90b9-11e6-88ac-c3e164c7a502.png)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by ananaymital** [comment]
@goyalritesh21 you have a small error in your code. In the future, please post in the [HelpJavascript](https://gitter.im/FreeCodeCamp/HelpJavaScript) Gitter channel first. If the consensus there is that it is a bug, then you should post here. Hint: use `fadeOut` instead of `animated fadeOut`

**Comment by erictleung** [comment]
@goyalritesh21 thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Hint: please check your method names. Capitalization is important e.g. `addClass()` vs `addclass()`. Happy coding!
