### ISSUE TITLE
html escape codes are not registering properly

### ISSUE THREAD

**Issue by MitchDoogle** [FreeCodeCamp/freecodecamp#1118]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The tests for this unit do not support the codes using unicode numbers such as &#38; 
Also,  the following code, when tested, does not register the "<" and ">" symbols as being html entities, though it does for the ampersand.

```
function convert(str) {
  // &colon;&rpar;
  str = str.replace(/[<>&'"]/gi, function(i) {
      switch (i){
        case '<' : return "&lt;";
        case '>' : return "&gt;";
        case '\"': return "&QUOT;";
        case '\'': return "&apos;";
        case '&' : return "&amp;";
        default  : return i;
      }
  });
  return str;
}

convert('<>&\'\"');
```

**Comment by BerkeleyTrue** [comment]
@MitchDoogle Thanks for reporting. We will be tracking this issue at #1062
