### ISSUE TITLE
HTTPS for Geo Location and Open Weather API Conflicts

### ISSUE THREAD

**Issue by helloitsian** [FreeCodeCamp/FreeCodeCamp#11180]
Challenge [Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Chrome has deprecated Geolocation in JavaScript unless it's being ran in a secure enviroment (localhost, or HTTPS). However, Open Weather API requires you to pay for HTTPS access. Basically, the conflict is to use Open Weather API AND Geolocation, you need payed access to the Open Weather API.

**Comment by erictleung** [comment]
@helloitsian thanks for the issue. This is a known issue in #8988 and #9079. I think https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10341 fixes both issues. Take a look at the changes and discussion on those pages for some possible solutions. Happy coding!
