### ISSUE TITLE
Dev Request: Test User

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/freeCodeCamp#11186]
I think it would be helpful for testing if there were a way to either:

a) load in a complete/mostly complete test user 

OR

 b) load my own user data 

into the local instance. I know that I could build such a user from scratch and inject it into the database, but I think it might be worth considering a shared test user that comes with the fork install.

**Comment by Bouncey** [comment]
Can you not sign in with github? You would have to register an [OAuth application](https://github.com/settings/developers) for it.

**Comment by dhcodes** [comment]
@Bouncey I've done that but it doesn't pull in my timestamps and completed challenges. This is mostly to test for user-specific errors like the cal-heatmap, certificate completions, language settings, etc.

**Comment by erictleung** [comment]
@dhcodes I can't verify this works but looking at the Chinese FreeCodeCamp fork, it looks like they created what looks to be a test user script https://github.com/FreeCodeCampChina/freecodecamp.cn/blob/dev/full-test-data.js. Maybe take a look at it?

**Comment by dhcodes** [comment]
thanks @erictleung I'll try injecting that user or a modified version of it to see how well it works. Will report back.

**Comment by systimotic** [comment]
@dhcodes Did you make any progress on this?
I think this would be a useful addition, especially to test certificate completion, as that's hard to test otherwise.

**Comment by dhcodes** [comment]
nope, been too busy. You're welcome to check it out if you have the time @systimotic

**Comment by raisedadead** [comment]
> If we do add in a script to create a test user, we can maybe put it into the test/ directory.

Nope, Berkley recently moved server side testing to server/utils
Refer : https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10889

We should keep them at the above location.

**Comment by dhcodes** [comment]
Against my best interest, I'm going to assign this to myself because I've made a little progress. Hope to update soon.

**Comment by dhcodes** [comment]
I've done only the superficial aspects of this. You can see the resulting file here: https://github.com/dhcodes/FreeCodeCamp/blob/feature/dev-test-user/make-test-user.js

I'd be happy to have anyone test it out. You can download the file to the root of your local instance and then (with mongod running), run `node make-test-user.js <yourusername>`. 

This will complete all of the challenges at random dates over the past two years (since freeCodeCamp's existence) and complete the certs for your local user.

I understand others seem to want to add test-passing functionality to this and I'm all for it, I'm just not sure I have the skills to do it yet.

**Comment by dhcodes** [comment]
Closing as wontfix
