### ISSUE TITLE
JSBin-like tab management system

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#11194]

**Comment by atjonathan** [comment]
Has this not been in the workings for a few months with regards to the multi tab editor? It surely shouldn't be that hard to implement. If @Berkeleytrue is busy I can take this one on!

**Comment by QuincyLarson** [comment]
@atjonathan it will be a huge part of our upcoming UI overhaul. Perhaps we can get you on the phone and show you what we're thinking.
