### ISSUE TITLE
New Map based on DevDocs.io sidenav

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#11193]

**Comment by Bouncey** [comment]
Do we not already have a drill-down menu? 

Or are you talking more about bringing the sidnav back for `React Release`?

**Comment by QuincyLarson** [comment]
@Bouncey this would be a much more compact on-by-default, collapsed-by-default style sidenav with a lot more content, like this:
![](https://www.evernote.com/l/Ar8D5QkpjGpH_638mKkms6Bnf4AIu6LaQZ0B/image.png)
