### ISSUE TITLE
Style guide for bonfire challenges

### ISSUE THREAD

**Issue by terakilobyte** [FreeCodeCamp/freecodecamp#112]
It would be really really helpful if there was a style guide for writing bonfires.

**Comment by brndnb** [comment]
I should have a rough draft by next week. If anyone else has suggestions or contributions (either because you've written challenges yourself, or you have come across reoccurring issues in current bonfires), please send them our way.

**Comment by terakilobyte** [comment]
I'd like to see all tests written in the expect style. Assert is too verbose in my opinion. If the user wants to use them that's fine, but we need to have a consistent style on the back end.

**Comment by cshutchinson** [comment]
I will be happy to help in any way I can. I am going to start looking at it hard tonight.

**Comment by brndnb** [comment]
Here is the very beginning of a rough draft: https://github.com/FreeCodeCamp/freecodecamp/wiki/Bonfire-Style-Guide

**Comment by terakilobyte** [comment]
I like it so far. I'll spiffy the generator page up so that there isn't a json generator and challenge generator. It will all be on the same page, which will be a bonfire instance itself.

**Comment by QuincyLarson** [comment]
This is definitely a work in progress, but I think we should include it in our codebase anyway. We can have a global styleguide and just link to it from our README.md file. I'll do this and then close this ticket.

**Comment by QuincyLarson** [comment]
I went ahead and made an actual view on FCC. freecodecamp.com/styleguide Please feel free to expand this with future pull requests.
