### ISSUE TITLE
💪 Use yarn instead of NPM in Contributing Guide

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#11208]
[Yarn](https://yarnpkg.com/) is said to be quicker and more reliable, fixing some of the common errors with NPM. We should refer to this instead of NPM in the [Contributing Guide](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by Bouncey** [comment]
I looks promising, have you tried it out?

**Comment by atjonathan** [comment]
@Bouncey, yeah; it works well!

**Comment by ltegman** [comment]
It's still a bit rough around the edges for anything but the most standard use cases. I'm getting the following error when I try to install FreeCodeCamp with it: 
```
error Couldn't find match for "feature/noop-server" in "feature,firefox-2-and-3-support,gh-pages,master,v1.0.3,v1.1.0,v1.1.1,v1.2.0,v1.3.0,v1.3.1,v1.3.10,v1.3.11,v1.3.12,v1.3.13,v1.3.14,v1.3.15,v1.3.16,v1.3.17,v1.3.2,v1.3.3,v1.3.4,v1.3.5,v1.3.5-firefox-2-and-3-support,v1.3.6,v1.3.7,v1.3.8,v1.3.9" for "https://github.com/berkeleytrue/store.js.git".
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by atjonathan** [comment]
Good Point. We should revisit this once Yarn is more stable!
