### ISSUE TITLE
Sizing image 

### ISSUE THREAD

**Issue by mikhail2882** [FreeCodeCamp/FreeCodeCamp#11205]
Please help What am i doing wrong sizing the image?  
Size your Images

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }
  .smaller-image{width:100px;}
  
  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

 
 
 
```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by dhcodes** [comment]
@mikhail2882 Are you experiencing an issue with the challenge? If you have a coding question, please consider asking for help in the Gitter chat room by clicking the Help button on the challenge.
