### ISSUE TITLE
Syntax error with link

### ISSUE THREAD

**Issue by sunsplat** [FreeCodeCamp/FreeCodeCamp#11200]
Challenge [Use the Twitchtv JSON API](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

![Image of Issue](http://i.imgur.com/pdYknvu.png)
11. - The sentence is not finished and the link is not provided
12. - The link that is supposed to end the sentence in #11 is located here as 'Remember to use'

**Comment by atjonathan** [comment]
Thanks for catching this, however this has already been fixed. It will be pushed to production soon!
