### ISSUE TITLE
Site cannot detect other p element

### ISSUE THREAD

**Issue by rags4developer** [FreeCodeCamp/freecodecamp#1121]
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

![image](https://cloud.githubusercontent.com/assets/13057064/8368319/8b059c1e-1b5d-11e5-87ee-56a747a88590.png)

To pass this test:
1. You need 2 p elements with Kitty Ipsum text.
2. Your p element should contain the first few words of the provided additional "Kitty Ipsum" text.
and more.

My code meets the conditions, but fails the 2nd check.

**Comment by digitaldak** [comment]
You need to click more information and read the instructions.

**Comment by BerkeleyTrue** [comment]
@rags4developer Looks like you have not met all the requirements of this challenge. Please open the more info panel to get further instructions.

Also, have you heard about our fantastic help chat? Its at https://gitter.im/freecodecamp/help . we have an awesome community that loves to help out.

**Comment by rags4developer** [comment]
oh doh ! It was not the text provided in code. Thanks.

**Comment by CreateInnovateProduce** [comment]
really... you couldn't simply share with a newbie, "remove the class in the second p tag... jikes.

**Comment by CreateInnovateProduce** [comment]
And change the text in the second p tag... Look guys... the instructions are nebulous... coding is fun... help out these kids, especially when instructions can be read differently and you have a large audience.

**Comment by dwd2010** [comment]
@CreateInnovateProduce, We dont give answer to them on here. but we could help them at gitter chat room without give them answer. we could give them a hint. hint will be helpful to them

**Comment by CreateInnovateProduce** [comment]
Cool, Got it.  Btw this program is awesome.
