### ISSUE TITLE
Comparison with logic and operator still not working, im not loosing money on this bs

### ISSUE THREAD

**Issue by courtjester71** [FreeCodeCamp/FreeCodeCamp#11210]
#### Challenge Name

https://www.freecodecamp.com/challenges/comparisons-with-the-logical-and-operator

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 function testLogicalAnd(val) {
  // Only change code below this line

  if (val<=50 && val>=25) {
  return "yes";
  }

  // Only change code above this line
  return "No";
}

// Change this value to test
testLogicalAnd(10);

 
 
```

**Comment by courtjester71** [comment]
Look, this is simple, Ive watched another do this exact same code and have it go right through, and Im growing impatient as Im not going to loose $200 on this one bs code section

**Comment by Bouncey** [comment]
@courtjester71 I don't know who you are loosing $200 to, but freeCodeCamp is totally free, no ads, no subscriptions, no membership fees, nothing. Ever.

As for your code, the devil is in the detail, I'm guessing you have at some point deleted `"Yes"` and typed in `"yes"` in it's place. I do this thing all the time.

Our tests for this challenge are quite picky about capitalisation. Compare the expected output in the test cases to what your code is going to return.

Happy Coding

And seriously, we never have and never will ask you for money.

**Comment by courtjester71** [comment]
I kmow your free, Im on a veterans program which is none of your business,
but you like to give run around answeres to direct questions

**Comment by courtjester71** [comment]
Omg, so reset and rewrite, seems quirky, but ok

**Comment by courtjester71** [comment]
So lomg as its not a bug, one of two out of all the comtent wont work im
any comfig, and found a whol lot of others experiencing the same issue,
same challenges. So Im sayimg Bug?........

**Comment by Bouncey** [comment]
@courtjester71 are we still talking about the same challenge? 

The `Comparison with logic and operator` challenge expected `"Yes"` for some of the test cases, your code was returning `"yes"`, which caused them to fail.

By resetting the challenge, `"yes"` was changed back to `"Yes"` and the tests passed.

Please let me know if I have cleared this up for you

**Comment by courtjester71** [comment]
That and one other, Im thinking though there may be some glitch somewhere,
as ive consulted online with many, compared codimg closely, to the poimt of
exhanging code that has worked just fine for some but wont for others, as I
said I watched the code I had submotted work first time for a collegue

**Comment by Dayfiri** [comment]
Assignment works fine.
![screenshot from 2016-10-15 11-18-58](https://cloud.githubusercontent.com/assets/16082563/19408955/5e43d2a6-92c9-11e6-8d96-f68a734c433b.png)

**Comment by texas2010** [comment]
close issue since this challenge dont have a bug or issue.
