### ISSUE TITLE
Chunky Monkey has an issue

### ISSUE THREAD

**Issue by KeyurRamoliya** [FreeCodeCamp/FreeCodeCamp#11218]
#### Challenge Name
Chunky - Monkey

https://www.freecodecamp.com/challenges/chunky-monkey

#### Issue Description

When I am trying to solve the challenge I wrote the following code and browser is just crashed.
```js
function chunkArrayInGroups(arr, size){
    //Break it up
    var result = [];
    var temp = [];
    for (var i = 0; i < arr.length / size; i++) {
        temp = arr.slice(i,size);
        i = 3;
        result.push(temp);
    }
    return result;
}
chunkArrayInGroups(["a","b","c","d"], 2);
```
After writing this code I ran the test and browser is crashed. I reload the page but my previous code is already saved and free code camp site run the code when page is reload, it breaks the browser every time. (I know it is wrong solution for the challenge.) Specifically, main problem is occurs after I write "i = 3" in the middle of the for loop(Accidently).

#### Browser Information

* Browser Name, Version: Microsoft Edge 38.14393.0.0, Microsoft EdgeHTML 14.14393
* Operating System: Windows 10, Version 1607, OS Build 14393.321
* Mobile, Desktop, or Tablet: Desktop

**Comment by andmckvr13** [comment]
Perhaps it's an infinite loop you've written. Try this https://github.com/FreeCodeCamp/FreeCodeCamp/wiki

**Comment by Dayfiri** [comment]
@KeyurRamoliya

Your code is a mess at the moment. I see you need help for your code and best place for that is:
FreeCodeCamp [Help](https://gitter.im/FreeCodeCamp/Help)

**Comment by ogora** [comment]
why does this code work in the challenged yet there is a faulty lien??

`function chunkArrayInGroups(arr, size){
   var arr2 = [];
  //arr =  arr.length;
  for(i=0; i=arr.length; i++){
    arr2.push(arr.slice(0, size));
    arr = arr.slice(size);
  }
  return arr2;
}

chunkArrayInGroups(["a", "b", "c", "d"], 2);`
