### ISSUE TITLE
Chaining If Else Statements - issue with else & else if 

### ISSUE THREAD

**Issue by Nashaatfarrag** [FreeCodeCamp/FreeCodeCamp#11215]
Challenge [Chaining If Else Statements]
Please describe how to reproduce this issue, and include links to screenshots if possible.
The Code was accepted only when i used Else if at the final condition
why its not accepted when i used only else ? 
whats missing ? 

My code : JavaScript

function testSize(num) {
  // Only change code below this line

 if ( num <   5 ) return "Tiny" ;
else if ( num <  10 ) return "Small" ;
else if ( num < 15)  return "Medium" ; 
else if ( num < 20)  return "Large" ;
else if  ( num >= 20) return "Huge" ; 

  // Only change code above this line
}
// Change this value to test
testSize(7);
![capture](https://cloud.githubusercontent.com/assets/18016377/19409014/2aec0566-92cb-11e6-8cf2-eafe7d313fd0.PNG)

**Comment by marhyorh** [comment]
@Nashaatfarrag else statements don't take an argument. Next time use the [Help Room](https://gitter.im/FreeCodeCamp/HelpJavaScript)

**Comment by Nashaatfarrag** [comment]
Thnx it works
