### ISSUE TITLE
Golf Code - why cannt i pass this challenge ?

### ISSUE THREAD

**Issue by Nashaatfarrag** [FreeCodeCamp/FreeCodeCamp#11216]
Challenge [Golf Code](https://www.freecodecamp.com/challenges/golf-code#?solution=%0Afunction%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20if%20(%20strokes%20%3C2)%20%0A%20%20%20%20return%20%22Hole-in-one%22%3B%0A%20%20else%20if(strokes%20%3C%3D%20par%20-2)%0A%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%20else%20if(strokes%20%3D%3D%20par%20-1)%0A%20%20%20%20return%20%22Birdie%22%3B%0A%20%20%20else%20if%20(strokes%20%3D%3D%20par)%0A%20%20%20%20return%20%22Par%22%3B%0A%20%20%20else%20if%20(strokes%20%3D%3D%20par%20%2B1)%0A%20%20%20%20return%20%22Bogey%22%3B%0A%20%20%20else%20if%20(strokes%20%3D%3D%20par%2B2)%0A%20%20%20return%20%22Double%20Bogey%22%3B%0A%20%20%20else%7B%0A%20%20%20%20return%20%22Go%20Home!%22%3B%0A%20%20%7D%0A%0A%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(1%2C%201)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
i keep pressing CRTL+Enter And every time shows this error
i also tried  if ( strokes ==1 )  it shows the same problem 
My code:
```javascript

function golfScore(par, strokes) {
  // Only change code below this line
  
 if ( strokes <2) 
    return "Hole-in-one";
  else if(strokes <= par -2)
    return "Eagle";
   else if(strokes == par -1)
    return "Birdie";
   else if (strokes == par)
    return "Par";
   else if (strokes == par +1)
    return "Bogey";
   else if (strokes == par+2)
   return "Double Bogey";
   else{
    return "Go Home!";
  }

 
  // Only change code above this line
}

// Change these values to test
golfScore(1, 1);

```

![capture](https://cloud.githubusercontent.com/assets/18016377/19409721/b1711cf2-92da-11e6-9c50-5d09f28f54d5.PNG)

**Comment by armvas** [comment]
You're missing an exclamation mark (!)

Should be Hole-in-one! not Hole-in-one

**Comment by atjonathan** [comment]
@armvas is correct. Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by coursedian** [comment]
Thanks to your post i was able to understand what i did wrong. Thank you for sharing this.
