### ISSUE TITLE
saying that I did not "Apply the btn-default class to each of your button elements."

### ISSUE THREAD

**Issue by kdcamp11** [FreeCodeCamp/FreeCodeCamp#11220]
Challenge [Apply the Default Bootstrap Button Style](https://www.freecodecamp.com/challenges/apply-the-default-bootstrap-button-style#?solution=%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%20%22btn%20btn-default%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%20%22btn%20btn-default%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%20%22btn%20btn-default%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%20%22btn%20btn-defualt%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%20%22btn%20btn-default%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%20%22btn%20btn-default%22%3E%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
        <button class= "btn btn-default"></button>
        <button class= "btn btn-default"></button>
        <button class= "btn btn-default"></button>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <button class= "btn btn-defualt"></button>
        <button class= "btn btn-default"></button>
        <button class= "btn btn-default"></button>
      </div>
    </div>
  </div>
</div>

```

**Comment by Dayfiri** [comment]
In your 4. button, you have a typo. 
`btn-defualt` , when you change that, the assignment will work.

**Comment by Bouncey** [comment]
@kdcamp11 I am assuming that this has been resolved and as such I am closing this issue.

If you still have a problem, try the `Help` button for code help :+1: 

Happy coding!
