### ISSUE TITLE
I had inline style color as green and the test, Give your h1 element the inline style of color: white, passed.

### ISSUE THREAD

**Issue by nwolisa** [freeCodeCamp/freeCodeCamp#11226]
Challenge [Override Class Declarations with Inline Styles](https://www.freecodecamp.com/challenges/override-class-declarations-with-inline-styles#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20%23orange-text%20%7B%0A%20%20%20%20color%3A%20orange%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20id%3D%22orange-text%22%20class%3D%22pink-text%20blue-text%22%20style%3D%22color%3Agreen%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text {
    color: orange;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 id="orange-text" class="pink-text blue-text" style="color:green">Hello World!</h1>

```

**Comment by Bouncey** [comment]
@nwolisa Thanks for the report. It seems that the test in question is checking that the `h1` element has a style attribute and the style attribute has a property of color.

This test need to be more specific.

**Comment by Bouncey** [comment]
## First-timers Only

Familiarise yourself with [CONTRIBUTING.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), this will help you test up a test environment.

If you have any issues, please get in touch with the folks in the [Contributor Chat Room](https://gitter.im/FreeCodeCamp/Contributors).

Happy Coding :+1:

**Comment by Dayfiri** [comment]
` Use an in-line style to try to make our h1 element white. Remember, in line styles look like this:

<h1 style="color: green">

Leave the blue-text and pink-text classes on your h1 element. `

This was the assignment and when I changed in-line style to white it worked right away.
![screenshot from 2016-10-16 10-45-04](https://cloud.githubusercontent.com/assets/16082563/19416314/0106ac42-938e-11e6-8c72-d0fcddc69256.png)

**Comment by jarrydfillmore** [comment]
nice

**Comment by yasserhussain1110** [comment]
Hey if this issue is still open can I work on this one??

**Comment by dcgit** [comment]
I have submitted a pull request to fix this issue. The change allows common valid characters such as extra spaces while also validating exact keyword color as well as allowing the value white and it's hex version #ffffff

**Comment by kodackoder** [comment]
#cat-photo-form {
  background-color: green;
}
</style>
<form action="/submit-cat-photo" id#="cat-photo-form">
  <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
  <label><input type="checkbox" name="personality" checked> Loving</label>
  <label><input type="checkbox" name="personality"> Lazy</label>
  <label><input type="checkbox" name="personality"> Energetic</label>
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>

**Comment by kodackoder** [comment]
IDK why its not turning green :(

**Comment by kodackoder** [comment]
I applied the Id#

**Comment by Dayfiri** [comment]
@kodackoder Try to read the assignment again. 
Your job is to change color of `inline-style`, **not** of `class` or `id`. Change from original code, color from `green` to `white` in your **style** of `h1` element at the bottom

**Comment by mridulnagpal** [comment]
Can I help with this Issue?

**Comment by AJMorrisClark** [comment]
I'm a first timer. Can I do it?

**Comment by AkshayIyer12** [comment]
Just check my screenshot. I changed my inline style to white and worked flawlessly. 
![screenshot from 2016-12-15 11-05-51](https://cloud.githubusercontent.com/assets/5500080/21212885/9d10a6cc-c2b6-11e6-8422-96de41a5a2ff.png)

**Comment by RishuK** [comment]
If this issue is not closed, Can I take it up - First timer here

**Comment by AkshayIyer12** [comment]
Done

**Comment by RishuK** [comment]
You mean you did it?

**Comment by AkshayIyer12** [comment]
Yeah I had solved the issue and posted the screenshot.

Regards
Akshay Iyer

**Comment by getoutb1** [comment]
Stop

**Comment by systimotic** [comment]
@RishuK You can still work on this issue! Akshay knows how to work around it now, but this challenge can still use the improvement. Be sure to check out https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11318, there's some talk about how to solve it there.

@getoutb1 You may be getting notifications because you watched Free Code Camp. There should be a button to unsubscribe in the email. There's also a button to unwatch at the top right of this page.

**Comment by RishuK** [comment]
Thanks @systimotic. I just want to understand if this has been solved, why is this still open?

**Comment by RishuK** [comment]
I guess I am missing something but I do not see any issue with the code. When you set style="white", the test passes with the right message. Then, what exactly is the issue?

**Comment by Bouncey** [comment]
@RishuK see [comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11226#issuecomment-254015474)

Happy Coding!

**Comment by systimotic** [comment]
@RishuK To clarify, with the example code in the original report, the second to last test is passing, but it shouldn't be.

**Comment by AkshayIyer12** [comment]
@systimotic @Bouncey @RishuK I'm confused right now. Did i solve the issue or not? I mean like was my solution correct?

**Comment by systimotic** [comment]
@AkshayIyer12 You passed the challenge, so you're good 🙂 
This issue is about something else. When the value you set is wrong (for example: `style="color: nonsensetext"`), this test:
> Give your `h1` element the inline style of `color: white`

Still gets a green checkmark, while it shouldn't.
That still needs to be resolved, so the issue is not solved. I hope that clears things up.

**Comment by AkshayIyer12** [comment]
Okay cool Thanks Timo

Regards
Akshay Iyer

**Comment by systimotic** [comment]
@RishuK How's your progress on this?

**Comment by RishuK** [comment]
Hey @systimotic - I will work on this by this weekend and post here.

**Comment by sayedafif** [comment]
If its still open. Can I work on this?

**Comment by RishuK** [comment]
I have started working on this. Sorry I got late.

**Comment by RishuK** [comment]
I am seeing that this issue is also present in this test - override-all-other-styles-by-using-important

**Comment by RishuK** [comment]
This is what I am trying but doesn't seem to work - 

assert(code.match(/<h1[\\s\\S]*?style[\\s\\S]*?color[\\s]*:[\\s]*white[\\s\\S]*)

**Comment by RishuK** [comment]
`assert(code.match(/<h1[\\s\\S]*?style[\\s\\S]*?color[\\s]*:[\\s]*white[\\s\\S]*)`

This is what I am trying but does not seem to work. Any inputs?

**Comment by systimotic** [comment]
@RishuK Take a look at https://github.com/freeCodeCamp/freeCodeCamp/pull/11318, especially at the review comments. There's a lot of work already done there. You're headed in the right direction!

**Comment by hay-dee** [comment]
Hi all, is this issue still open? Can i work on it?

**Comment by hay-dee** [comment]
Should the answer allow for other style changes that will not affect the text color? E.g.: will the answer style="background-color:green;color:white;margin-left:40px" be allowed?
