### ISSUE TITLE
Cloud9 LYN Time Server Cant Connect

### ISSUE THREAD

**Issue by Lemony-Andrew** [FreeCodeCamp/FreeCodeCamp#1122]
Challenge http://www.freecodecamp.com/challenges/waypoint-continue-working-with-node.js-servers has an issue.

I had a solution of my own before, but I wanted to make sure the error wasn't on my side; I'm sure it wasn't.

Using this javascript:
````
var net = require('net');

function zero(i) {
  return (i < 10 ? '0' : '') + i;
}
function now () {
  var d = new Date();
  return d.getFullYear() + '-' + zero(d.getMonth()) + '-'
    + zero(d.getDate()) + ' ' + zero(d.getHours()) + ':'
    + zero(d.getMinutes());
}

var server = net.createServer(function (socket) {
  socket.end(now() + '\n');
}).listen(8000);
```
I tried solving **Time Server**. The problem is, nothing is going through. I continuously get connection errors follow similar structure: 
>✗ Error connecting to localhost:17722: connect ECONNREFUSED
>...
>Your submission results compared to the expected:

**Comment by LumenTeun** [comment]
learnyounode is not a product of FCC, so if there's an error with it, it should be reported to the developers, not here. Try the chat room for help, I've seen a lot of people discussing learnyounode over there. Remember to close this issue.

**Comment by Lemony-Andrew** [comment]
LumenTeun I was making the error apparent so that Quincy would know that even though this tutorial can be done on a virtual cloud computer like C9's Ubuntu terminal, it still can have errors. 

I was just hoping maybe in the mean time someone could find something that works a bit differently.

**Comment by benschenker** [comment]
Closing as stale
