### ISSUE TITLE
Not able to use Global variables 

### ISSUE THREAD

**Issue by gandhirahul** [FreeCodeCamp/FreeCodeCamp#11227]
Challenge [Steamroller](https://www.freecodecamp.com/challenges/steamroller has an issue.

**User Agent is**:
 <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.

**Issue Description** : 
Global Variables value is not getting flushed.

My code:
```javascript
var tempArr = [];
function steamrollArray(arr) {
  // I'm a steamroller, baby
  tempArr = []; // To fix the global var issue , we need to reset that global var
  arr = arr.map(function(val,index){
     return checkForArray(val);
  });
  console.log('tempArr',tempArr);
  return tempArr;
}
function checkForArray(val_arr){
  if(!Array.isArray(val_arr)) {tempArr.push(val_arr);return val_arr;}
  val_arr.map(function(val,index){
      if(Array.isArray(val)){
        return checkForArray(val);
      }
      else {
        tempArr.push(val);
        return val;
      }
  });
}
steamrollArray([1, {}, [3, [[4]]]]);
```

**Comment by Bouncey** [comment]
Marking as duplicate. This issue is already being discussed in #9199 

@gandhirahul you could move the `tempArr` declaration inside of `steamrollArray` as well

**Comment by gandhirahul** [comment]
@Bouncey  Yes, I have done that in the above-mentioned code too :P 
Just wanted FCC to be aware of this issue.
