### ISSUE TITLE
they wont recognize buds in their system, they are frauds basically, its all bs

### ISSUE THREAD

**Issue by courtjester71** [FreeCodeCamp/FreeCodeCamp#11239]
#### Issue Description

system hangs and wont pass to next challenge though coding is correct as verrified with tutorials and many other coders on this bs site, no matter haw many variants are attempted , or possible correct solutions applied; this has been done on three separate computers, clean browsers, newly installed systems, chrome and firefox. Running Linux Ubuntu 16.4 lts. Ive watched the cosing in this challenge and Comparrison with Logic and operator, work flawlessly, and attempted other solutions offered in these chats online, there is a bug somewhere

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

Already sent screen shots of variouse, coding, how about I send a whole GD tutorial as proof

**Comment by ltegman** [comment]
We can't help you if you don't provide us with information like what the bug is and what code or actions are required to reproduce the bug. Feel free to open a new issue if you're willing to provide those details and act in a civil manner.

**Comment by courtjester71** [comment]
Thought, I sent all the coding limes and screen shots, well not all as Ive
used every conciievable combination of possibles. So Ive just moved on. But
I earn money for doing this, onlu reason Im not learning on a real tutorial
sight that actually teaches, and where I can receive solid knowlegable
feedback and not some lame chatroom. Pluss you constantly add fluff and
alter the content. So chats are a total waste of time. In closing Ill send
the screenshots shortly once I complete the next little section. I think
your scammers, and if not busy with bigher fish, this Imell pro would begin
to dig into you org.

**Comment by kittenfuud** [comment]
(I think the "buds" are in HIS system! 😉)
