### ISSUE TITLE
Incorrect or failing assertion for string check

### ISSUE THREAD

**Issue by FFX01** [FreeCodeCamp/FreeCodeCamp#1123]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. 

Assertion for string "<>" is converted by user function to "&lt&gt". This should pass the test and allow users to move on. However, when examined in the debugger it shows the variable allTestsPassed to be returned as false and the assertion returns "<>" as the output from the user function.

See imgur link for screenshots of issue: http://imgur.com/a/sqEBW

**Comment by benschenker** [comment]
Hey @FFX01 it looks like this exercise has changed, can you try to see if your problem is fixed?
I'm having trouble replicating it.

I'll close this but reopen if you still have the issue
