### ISSUE TITLE
Switch order of 'Basic Javascript' for- and while-loop lessons

### ISSUE THREAD

**Issue by mattlayton1986** [FreeCodeCamp/FreeCodeCamp#11231]
#### Challenge Name

[Iterate with JavaScript For Loops](https://www.freecodecamp.com/challenges/iterate-with-javascript-for-loops)
[Iterate with JavaScript While Loops](https://www.freecodecamp.com/challenges/iterate-with-javascript-while-loops)

#### Issue Description

Consider moving the lesson "Iterate with JavaScript While Loops" to a position before the series of lessons on for-loops, starting at "Iterate with JavaScript For Loops". Currently the single while-loop lesson is placed after the for-loop lessons, but it may be advantageous for students if its made clear that a for-loop is a condensed form of a while loop (especially since the example code in the lessons are synonymous: 
```javascript
var ourArray = [];
var i = 0;
while(i < 5) {
    ourArray.push(i);
    i++;
}
```
and: 
```javascript
var ourArray = [];
for (var i = 0; i < 5; i++) {
    ourArray.push(i);
}
```
Lesson text in the for-loop lessons could then be updated to make the relationship to while-loops more explicit. It could also be stated that while-loops are used for more than just iterating but __if you find yourself iterating with a while-loop, that's a good opportunity to use a for-loop instead.__

#### Screenshot

![for-while_fcc](https://cloud.githubusercontent.com/assets/10576656/19414759/6985f71c-931d-11e6-8bd6-681ca8718124.png)
![while-lesson](https://cloud.githubusercontent.com/assets/10576656/19414760/6f54b20a-931d-11e6-8655-79ea542363c1.png)
![for-lesson-1](https://cloud.githubusercontent.com/assets/10576656/19414762/757e50aa-931d-11e6-920e-fc7fbc3b71ee.png)
![for-lesson-2](https://cloud.githubusercontent.com/assets/10576656/19414763/783b15a8-931d-11e6-87d4-89f5f108ce5b.png)

**Comment by Bouncey** [comment]
Sounds reasonable to me

cc @FreeCodeCamp/issue-moderators

**Comment by Bouncey** [comment]
Lets move these challenges around :+1: 

Remember to take the translations with you :smiley:

**Comment by broldak** [comment]
I can take care of this. (This is my first contribution, please let me know if I'm doing anything wrong.)

**Comment by recurza** [comment]
Working on it 😁

**Comment by recurza** [comment]
It took much, much longer to setup than to finish coding this...

**Comment by boneyfantaseas** [comment]
one other thing - maybe in the wrong place here (please be kind, I'm new around here :) ) - I wonder about the pros and especially the cons of using while at all. It might be wise to note that a misuse of while could result in an endless loop, leaving your page/app broken and eventually kill the whole browser. 
If this is the only place where while is explained, I'd appreciate a note on that.

**Comment by erictleung** [comment]
@boneyfantaseas feel free to head over to the [Contributors](https://gitter.im/FreeCodeCamp/Contributors) Gitter chat room for a sounding board for curriculum discussions.

**Comment by boneyfantaseas** [comment]
thx!
