### ISSUE TITLE
The Twitchtv JSON API passthrough is down

### ISSUE THREAD

**Issue by Lillian-wang** [FreeCodeCamp/FreeCodeCamp#11242]
#### Challenge Name
https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api

#### Issue Description
Can't access  https://wind-bow.hyperdev.space/twitch-api
This is also causing the following codepen to not load: https://codepen.io/FreeCodeCamp/full/Myvqmo/

#### Browser Information

* Browser Name, Version:  Chrome
* Operating System: Mac OSX
* Mobile, Desktop, or Tablet: Macbook Pro

#### Screenshot

<img width="1274" alt="screen shot 2016-10-16 at 5 20 41 pm" src="https://cloud.githubusercontent.com/assets/17482573/19422206/559a0740-93c5-11e6-9700-06354b2c6343.png">
<img width="1274" alt="screen shot 2016-10-16 at 5 24 14 pm" src="https://cloud.githubusercontent.com/assets/17482573/19422207/63bf56e0-93c5-11e6-9186-fdc139d23cca.png">

**Comment by annunirmal** [comment]
Same here, need urgent attention!

**Comment by Em-Ant** [comment]
I am afraid that we are beyond the HyperDev traffic limits, or their system marks the server as malicious. I sent an help request to the HyperDev team. Let's wait for ther response. 

@QuincyLarson should We try to move the pass-through to heroku or some other service ?

**Comment by Em-Ant** [comment]
...back to life :tada:
