### ISSUE TITLE
Roman converter

### ISSUE THREAD

**Issue by tanyildiz** [FreeCodeCamp/FreeCodeCamp#11246]
```
function convertToRoman(num) {
 return num;
}

convertToRoman(36);
```

despite of running on every number till 3999 on codepen.io, challenge window doesn't accept and shows nothing. i thought, it may require global functions, and i wrote it again with .splice() and .join(). but it doesn't work again.

it may be a issue..

#### Challenge Name

https://www.freecodecamp.com/challenges/roman-numeral-converter#?solution=%0Afunction%20convertToRoman(num)%20%7B%0A%20return%20num%3B%0A%7D%0A%0AconvertToRoman(36)%3B%0A

#### Browser Information

* Browser Name, Version: Safari 10.0 (12602.1.50.0.10)
* Operating System: Mac Os Sierra
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 function convertToRoman(num) {
  var result = "";
  result = num.toString().split("");
  
  //result = result.join();
  var x = result.length;
  var roman = "";
  var binler = ["", "M", "MM", "MMM"];
  var yuzler = ["", "C", "CC", "CCC", "CD", "D", "DC", "DCC", "DCCC", "CM"];
  var onlar = ["", "X", "XX", "XXX", "XL", "L", "LX", "LXX", "LXXX", "XC"];
  var birler = ["", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX"];

  function sum(arr) {
  if (x === 4) {
     var y = arr.splice(0, 1,binler[arr[0]]);
    console.log(binler[y] + yuzler[arr[1]] + onlar[arr[2]] + birler[arr[3]]);
   } else if (x === 3) {
     var z = arr.splice(0, 1,yuzler[arr[0]]);
     console.log(yuzler[z] + onlar[arr[1]] + birler[arr[2]]);
    }  else if (x === 2) {
     var k = arr.splice(0, 1,onlar[arr[0]]);
     console.log(onlar[k] + birler[arr[1]]);
    } else if (x === 1) {
     var i = arr.splice(0, 1, birler[arr[1]]);
     console.log(birler[i]);
    }
    result = result.join();
  } return sum(result);
}

convertToRoman(500);
convertToRoman(2);
convertToRoman(2);
 
 
```
#### Screenshot

![screen shot 2016-10-17 at 14 57 41](https://cloud.githubusercontent.com/assets/20441961/19436674/3928f606-947a-11e6-8755-2d762834a7ab.png)
![screen shot 2016-10-17 at 14 58 14](https://cloud.githubusercontent.com/assets/20441961/19436676/3a8c2c34-947a-11e6-8400-a948bbed030b.png)

**Comment by ltegman** [comment]
You are returning the result of `sum(result)` from the `convertToRoman` function, but the `sum` function does not have a return value, so you always return `undefined`.

Closing as not a site issue. Thanks and happy coding!

**Comment by tanyildiz** [comment]
thank you :-)

Niyazi Tanyıldız
0532 263 36 64
