### ISSUE TITLE
second kitty ipsum won't accept after completed

### ISSUE THREAD

**Issue by TrongT** [FreeCodeCamp/FreeCodeCamp#11243]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%20%7Bfont-size%3A16px%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%3EKitty%20ipsum%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  p {font-size:16px}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Kitty ipsum</p>

```

**Comment by pkinopk** [comment]
Same issue here, my code:
`<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>


<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>`

**Comment by TrongT** [comment]
you have to write the second half of it a new paragraph starting with Purr

**Comment by beth-johnstone** [comment]
I'm having the same issue, and I have put the second half of it into a new paragraph: 

<style>
  .red-text {
    color: red;
  }
  p {font-size: 16px;}
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p Purr jump eat the grass </p>

**Comment by beth-johnstone** [comment]
I'm having the same issue

**Comment by ParadiseArtist** [comment]
Do you want to paste in your code I'll see if I can fix it for you? @beth-johnstone

**Comment by Sidtharthan** [comment]
p
{
font-size:16px; 
}
you've missed semi-colon @TrongT

**Comment by texas2010** [comment]
@beth-johnstone, 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by beth-johnstone** [comment]
Fixed it guys! Thanks everyone for your help :)

**Comment by pinkbow** [comment]
It's still not working.

**Comment by matthewshirley** [comment]
Hey @pinkbow, could you share the code you're using?

**Comment by pinkbow** [comment]
Hello Matthew,

Here's the html:

<!DOCTYPE html>
<html lang="en">
	<head>
  	<meta charset="utf-8">
  	<meta name="description" content="Your description goes here">
  	<meta name="keywords" content="one, two, three">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Responsive Design!</title>
		
		
		<link rel="stylesheet" href="css/reset.css">
		<link rel="stylesheet" href="css/styles.css">
		
	</head>
	<body>
		<header>
			<nav>		
				<h1>The Kitty Blog</h1>		
				<ul>
					<li>
						<div class="line"></div>
						<div class="line"></div>
						<div class="line"></div>
					</li>
					<li>About Me</li>
					<li>Photos</li>
					<li>My Blog</li>
					<li>Adorable Videos</li>
				</ul>
			</nav>
		</header>
		<img src="images/kitty.jpg" id="cat" alt="Adorable Kitty" />
		<main>
			<div id="intro">
				<h2>Welcome to my site</h2>
				<div id="toybox">
					<img src="images/toy.png" id="toy" alt="Pink Mouse Toy"/>
				</div>
				<p>Slap owner's face at 5am until human fills food dish chase imaginary bugs chase red laser dot sleep nap. Sun bathe. Kick up litter. My left donut is missing, as is my right kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff. Put toy mouse in food bowl run out of litter box at full speed hunt by meowing loudly at 5am next to human slave food dispenser attack the dog then pretend like nothing happened chase the pig around the house so spot something, big eyes, big eyes, crouch, shake butt, prepare to pounce or lick yarn hanging out of own butt. Kitty scratches couch bad kitty kick up litter sleep in the bathroom sink. Slap owner's face at 5am until human fills food dish chase imaginary bugs chase red laser dot sleep nap. Sun bathe. Kick up litter. My left donut is missing, as is my right kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff. Put toy mouse in food bowl run out of litter box at full speed hunt by meowing loudly at 5am next to human slave food dispenser attack the dog then pretend like nothing happened chase the pig around the house so spot something, big eyes, big eyes, crouch, shake butt, prepare to pounce or lick yarn hanging out of own butt. Kitty scratches couch bad kitty kick up litter sleep in the bathroom sink.</p>
			</div>
			<div>
				<div class="column">
					<h2>My Story</h2>
					<p>Gnaw the corn cob attack feet. Who's the baby if it smells like fish eat as much as you wish so play riveting piece on synthesizer keyboard so instantly break out into full speed gallop across the house for no reason.</p>
					</div>
				<div class="column">
					<h2>All About Me</h2>
					<p>Sleep on keyboard scratch at the door then walk away. Stand in front of the computer screen wake up wander around the house making large amounts of noise jump on top of your human's bed.</p>
				</div>
				<div class="column">
					<h2>Where's My Catnip?</h2>
					<p>Put toy mouse in food bowl run out of litter box at full speed loves cheeseburgers give attitude meow loudly just to annoy owners so meow to be let in yet climb a tree, wait for a fireman.</p>
				</div>
			</div>
		</main>
		<footer>
			<p>A Great Blog About a Fabulous Kitty</p>
			<p>Follow Me on Instagram</p>
		</footer>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.js"></script>
		<script src="js/script.js"></script>
	</body>
</html>

**Comment by pinkbow** [comment]
And here's the js:

$(document).ready(function() {



$("#menu").on("click",function(e){
     e.preventDefault();
     $("#bigMenu").slideToggle();
     console.log("clicked");
 });





});

**Comment by matthewshirley** [comment]
@pinkbow which challenge are you trying to do? This is thread is for "Change Font Size Of An Element". I couldn't find out which one.

Check out the [help chat room](https://gitter.im/FreeCodeCamp/Help) if you still need a hand.
