### ISSUE TITLE
concat()

### ISSUE THREAD

**Issue by Ammulubaipaneni** [FreeCodeCamp/FreeCodeCamp#11259]
Challenge [Concatenating Strings with Plus Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20%22This%20is%20the%20start.%22%20%2B%20%22This%20is%20the%20end.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr = "This is the start." + "This is the end.";



```

**Comment by luongthomas** [comment]
When concatenating two strings, they will be combined just as such.

For example, when myStr is evaluated, the resulting string will be:

`"This is the start.This is the end."`

I hope this helps.

**Comment by Dayfiri** [comment]
@Ammulubaipaneni Assignments are strict about many things and one of them are `spaces`. 
You need to put a `space` after `start.` like this `start. `. That is how you get a space when you concate 2 strings. 

If you put `"hey" + "you"` you will get output of `heyyou`. But if you put space before the end of 1.sentence or the beginning of 2. one you will have a normal space, like this:
`"hey " + "you"` or `"hey" + " you"` will get you an output of `hey you`.

**Comment by jacobjzhang** [comment]
Yeah it should be:

`var myStr = "This is the start. " + "This is the end.";`

**Comment by texas2010** [comment]
@Ammulubaipaneni 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
