### ISSUE TITLE
Issue about Increment a Number with JavaScript 

### ISSUE THREAD

**Issue by Yuki0916** [FreeCodeCamp/FreeCodeCamp#11258]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myVar = 87;

// Only change code below this line
myVar = ++myVar;


```
In next chanllenge "Decrement a Number with JavaScript" can pass by use "myVar = --myVar; "

**Comment by Marmiz** [comment]
Hello @Yuki0916,

The challenge states:
> myVar = myVar should be changed

So I guess it's ok that you won't pass that challenge.
I think the whole point is to make you use the `++` notation.

Happy coding!

**Comment by Dayfiri** [comment]
`You can easily increment or add one to a variable with the ++ operator.

i++;

is the equivalent of

i = i + 1;

Note
The entire line becomes i++;, eliminating the need for the equal sign.
Instructions

Change the code to use the ++ operator on myVar.
`

This is the explanation in assignment. Increment the `value` stored in `myVar`.
You can see that `i = i + 1` is incrementing value stored in variable `i` by 1. But to write less code and do the same thing you can just write `i++` .

**Comment by Yuki0916** [comment]
@Marmiz  @Dayfiri  Thank your support, I pass this chanllenge.

**Comment by Marmiz** [comment]
@Yuki0916 next time, consider going to [Gitter chat](https://gitter.im/FreeCodeCamp/Help) first;
you'll find tons of people happy to help there.

**Comment by Shubhamkumarsingh** [comment]
![untitled](https://cloud.githubusercontent.com/assets/24203776/21274138/acdbd216-c3ec-11e6-9641-315eb27f9dd3.png)
this was my problem. how would i change myVar =myVar it will be kidding me and dosen't allow me to pass the challenge.
So, on  a humble request please help me out.

**Comment by Yuki0916** [comment]
Hi @Shubhamkumarsingh  
The challenge notice
> myVar = myVar should be changed

You can try to use the ++ operator.
> i++ ;

is equal

> i = i+1 ;
