### ISSUE TITLE
More rooms!

### ISSUE THREAD

**Issue by ericdouglas** [FreeCodeCamp/FreeCodeCamp#1125]
To simulate other rooms that we had on Slack, we could create the respective repositories in the FreeCodeCamp org.

**Comment by benschenker** [comment]
Hey @ericdouglas,

I'm not sure exactly what you mean by this.  Right now we use Gitter instead of Slack, with various channels/rooms.

I'm going to close this but if you still feel like there is a feature that is missing reopen this issue
