### ISSUE TITLE
Only verified users can create shared bin URLS

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#11264]

**Comment by evalsocket** [comment]
@BerkeleyFalse  can you explain that issue

**Comment by BerkeleyTrue** [comment]
This is related to our move to redis to store challenges

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
