### ISSUE TITLE
From HTML Images to JS Tomatoes - Next Challenge Button Broken

### ISSUE THREAD

**Issue by qubodup** [FreeCodeCamp/FreeCodeCamp#1126]
Hi,

When I finish http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website it takes me to http://www.freecodecamp.com/challenges/Zipline:%20Build%20a%20Pomodoro%20Clock

I tried reproducing the bug but then it took me to http://www.freecodecamp.com/challenges/Zipline:%20Build%20a%20Tic%20Tac%20Toe%20Game instead.

Here's a video:
http://youtu.be/3enryIeqW2U

In the chat, I was told "Sometimes the "next" button will take you after where it last saw you, it's a bit weird, but normally it works."

**Comment by qubodup** [comment]
This seems to be hard to reproduce. Here's an attempt: http://youtu.be/ET6STeb-inE

Reproduction steps:
1. As a new user, work on item 1 in the /map. Do not finish it yet.
2. Open the map in a new tab and visit item 50. Do not finish it, just look at it.
3. Go back to the item 1 tab and finish it. Press the green button

Expected result:
4. item 2 opens in the current tab.

Actual result:
4. item 51 opens in the current tab.

The problem appears to be that the last visited item gets memorized and overrides the relation of the green button to the item page on which it gets clicked.

Instead, the green button should take you to the item following the item on which page it is clicked, no matter what you do in other tabs.

If you're worried that people might confuse themselves into repeating challenges by accident, I'd recommend a non-critical warning at the top saying "you completed this task ["waypoint", "bonfire" etc] in the past. You can SKIP TO THE NEXT INCOMPLETE TASK." where uppercase is a link to the the next incomplete task that has a higher index number than the item of the page on which the link is pressed. It should not jump to the earliest incomplete task in general, because that might reduce the index number if the user had skipped an item earlier.

Note that this issue might not appear as critical on pages where the green button says "I've completed this challenge (ctrl + enter)". It clearly is confusing on item pages where it says "Go to my next challenge (ctrl + enter)".

**Comment by LumenTeun** [comment]
This is already being discussed over in #893, and, according to @BerkeleyTrue "[t]his should be fixed when we switch over to loopback."
