### ISSUE TITLE
Remove Code URI's

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#11261]
They are unsafe and, due to some browser limitations, unreliable.

**Comment by andmckvr13** [comment]
Is there an example of a URI that you'd like to remove? Seems like to this could be a good Junior contribution

**Comment by mridulnagpal** [comment]
I would like to work on this issue can someone tell me what to do?

**Comment by Bouncey** [comment]
@BerkeleyTrue My understanding was that there is no code in the URI's now anyway?

**Comment by BerkeleyTrue** [comment]
> My understanding was that there is no code in the URI's now anyway?

Code URI is still there.

**Comment by Bouncey** [comment]
@BerkeleyTrue do we want to extract the code from the URI and pass it to the editor or just remove it completely and present the challenge as it is in the `seed`?

**Comment by BobDokubo2016** [comment]
hello Fellows, where can i see c# project please?

**Comment by Bouncey** [comment]
@BobDokubo2016 Currently we only have challenges in HTML, CSS and javaScript

**Comment by systimotic** [comment]
@BerkeleyTrue Code URI's aren't added anywhere anymore, and trying to add them doesn't put the URI text into the editor in the latest beta. Can this be closed?

**Comment by BerkeleyTrue** [comment]
Yes they have been removed from beta. Shortly after beta launch we will add the ability to save code to a redis storage. This will be our replacement for code uri's and a much more reliable way to share code between campers.
