### ISSUE TITLE
Prevent challenges with `hypderdev.com` from running

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#11265]
Any code with the URL `hyperdev.com` within the user generated text should not be allowed to run.

This will involve creating a new thrower here.

The purpose of this thrower would be to prevent ajax requests to the hyperdev domain

**Comment by yasserhussain1110** [comment]
@BerkeleyFalse I would like to work on it. But I'll probably need some help getting started.

**Comment by chiptus** [comment]
I don't really understood what the issue is. Can you please elaborate?

**Comment by kytwb** [comment]
@yasserhussain1110 @chiptus I think the following is clear:

> Any code with the URL hyperdev.com within the user generated text should not be allowed to run.

In the following issue description:

> This will involve creating a new **thrower** here.

You could have use the search bar to look for [what is here refered as a `thrower`](https://github.com/FreeCodeCamp/FreeCodeCamp/search?utf8=%E2%9C%93&q=thrower).

I'm taking this issue if no answer from both of you within the coming days. 
Good luck from there :smile:

**Comment by chiptus** [comment]
@kytwb so we should a new thrower to the the file you referenced that checks if hyperdev.com is in the text? I'll do it

**Comment by kytwb** [comment]
@chiptus I guess so :smile:

**Comment by yasserhussain1110** [comment]
@kytwb okay. Thanks. I'll work on this one.

**Comment by kytwb** [comment]
@yasserhussain1110 this issue was already claimed by @chiptus

**Comment by yasserhussain1110** [comment]
@kytwb I claimed it before.

**Comment by kytwb** [comment]
@yasserhussain1110 you're right, my mistake

**Comment by chiptus** [comment]
@yasserhussain1110 @kytwb Np, let Yasser have it

**Comment by kytwb** [comment]
@yasserhussain1110 congrats! :champagne:
