### ISSUE TITLE
Results of code sems to be correct, but does not pass tests.

### ISSUE THREAD

**Issue by mantinone** [FreeCodeCamp/FreeCodeCamp#11266]
Challenge [Record Collection](https://www.freecodecamp.com/challenges/record-collection#?solution=%0A%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%20%222548%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20%22artist%22%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%222468%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%221999%22%2C%0A%20%20%20%20%20%20%22artist%22%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%221245%22%3A%20%7B%0A%20%20%20%20%20%20%22artist%22%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%225439%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20updateRecords(id%2C%20prop%2C%20value)%20%7B%0A%20%20var%20theAlbum%20%3D%20collection%5Bid%5D%3B%0A%20%20if%20(prop%20%3D%3D%20%22tracks%22)%20%7B%0A%20%20%20%20if%20(!theAlbum.hasOwnProperty(%22tracks%22))%7B%0A%20%20%20%20%20%20theAlbum.tracks%20%3D%20%5B%5D%3B%0A%20%20%20%20%7D%20%0A%20%20%20%20theAlbum.tracks.push(value)%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20theAlbum%5Bprop%5D%20%3D%20value%3B%0A%20%20%7D%0A%20%20%0A%20%20if%20(value%20%3D%3D%3D%20%22%22)%7B%0A%20%20%20%20delete%20theAlbum%5Bprop%5D%3B%0A%20%20%7D%20%0A%20%20%0A%20%20return%20theAlbum%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0AupdateRecords(5439%2C%20%22artist%22%2C%20%22ABBA%22)%3B%0AupdateRecords(5439%2C%20%22tracks%22%2C%20%22Take%20a%20Chance%20on%20Me%22)%3B%0AupdateRecords(2548%2C%20%22artist%22%2C%20%22%22)%3B%0AupdateRecords(1245%2C%20%22tracks%22%2C%20%22Addicted%20to%20Love%22)%3B%0AupdateRecords(2468%2C%20%22tracks%22%2C%20%22Free%22)%3B%0AupdateRecords(2548%2C%20%22tracks%22%2C%20%22%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I've been fiddling with this problem for a while, trying different things, and I can never get more than two tests to pass at once.  The code below only passes the third and sixth tests, but if I look at the results, I can see that all of the expected, correct modifications have been made to the collection.

I note that I have to click the "Run Tests" button twice to get the full Object to show in the log.  On the first click, it does not show 5439, the ABBA album.

What's more, while trying to figure out what was wrong, I tried having the function simply say 
```javascript
var theAlbum = collection[id];
theAlbum[prop] = value;
```
And none of the tests passed, though, again, I could see in the log that the "artist" property had been added to 5439 with a value of "ABBA".

My code:
```javascript

// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  var theAlbum = collection[id];
  if (prop == "tracks") {
    if (!theAlbum.hasOwnProperty("tracks")){
      theAlbum.tracks = [];
    } 
    theAlbum.tracks.push(value);
  } else {
    theAlbum[prop] = value;
  }
  
  if (value === ""){
    delete theAlbum[prop];
  } 
  
  return theAlbum;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");
updateRecords(5439, "tracks", "Take a Chance on Me");
updateRecords(2548, "artist", "");
updateRecords(1245, "tracks", "Addicted to Love");
updateRecords(2468, "tracks", "Free");
updateRecords(2548, "tracks", "");

```

My results log looks like this.
```javascript
collection = 
{
  "1245": {
    "artist": "Robert Palmer",
    "tracks": [
      "Addicted to Love"
    ]
  },
  "2468": {
    "album": "1999",
    "artist": "Prince",
    "tracks": [
      "1999",
      "Little Red Corvette",
      "Free"
    ]
  },
  "2548": {
    "album": "Slippery When Wet"
  },
  "5439": {
    "album": "ABBA Gold",
    "artist": "ABBA",
    "tracks": [
      "Take a Chance on Me"
    ]
  }
}
```

**Comment by dhcodes** [comment]
@mantinone you have an error in your code based on what you are returning. I think the issue here is that the return statement doesn't seem to function correctly in the output box.

**Comment by mantinone** [comment]
Oh, geeze.  I changed that at the beginning, then forgot that it was there.

Thanks!  Sorry for the false bug.

**Comment by Bouncey** [comment]
@dhcodes the output window on staging acts as expected, but only with `console.log()`'s, I don't think there is an output otherwise.
