### ISSUE TITLE
Save bins instead of solutions

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#11263]
Instead of storing solutions directly on the user object we first create a Redis item for the solution and then store that id into the user challenge. This will make challenge storage uniform on the user object

**Comment by doughtz** [comment]
How about creating Solution objects and add that Solution object ID to the user?

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
