### ISSUE TITLE
Add Redis storage for bins

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#11262]

**Comment by evalsocket** [comment]
Can You explain me what is the requirement ?

**Comment by raisedadead** [comment]
@evalsocket Thanks for your interest.

This issue relates to some upcoming features for our backend (which needs storing some keys), and Berkeley is already working on it. 

If you would like I suggest you go through the "help wanted" issues on the tracker.
Thanks and happy fixing!

**Comment by evalsocket** [comment]
can i help  you @BerkeleyTrue

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
