### ISSUE TITLE
"click here", realurlasexample.com

### ISSUE THREAD

**Issue by qubodup** [FreeCodeCamp/FreeCodeCamp#1127]
http://www.freecodecamp.com/challenges/waypoint-wrap-an-anchor-element-within-a-paragraph tells us to write "click here" in front of a link, which according to http://www.w3.org/QA/Tips/noClickHere is problematic because "click" is a mechanic and not descriptive. Instead the text to be added could be "View more "

Also real-world URLs should probably not be used. Perhaps example.com/catapp instead of catphotoapp.com?

**Comment by awesomeaniruddh** [comment]
This seems to be the new URL:
http://www.freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph

I'll fix this to be in accordance with the W3C recommendation :)
