### ISSUE TITLE
My code seems to be correct but not passing

### ISSUE THREAD

**Issue by praveenoswal17** [FreeCodeCamp/FreeCodeCamp#11279]
Challenge [Record Collection](https://www.freecodecamp.com/challenges/record-collection) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line

  function updateRecords(id, prop, value) {
   if(value === undefined) 
     delete collection[id][prop];
  else {
    if (prop !== "tracks")
      collection[id].artist = value;
    else if(collection[id].tracks.HasOwnProperty === False )
     collection[id].tracks = value;
     else 
       collection[id].tracks = [];
    collection[id].tracks.push(value);
  }
      
  
  return collection;
}

// Alter values below to test your code
updateRecords(5439, "artist", "");


```

**Comment by erictleung** [comment]
@praveenoswal17 thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). 

Briefly looking at your code, there are a few errors. Also, this snippet from the instructions may help.

> If `prop` is `"tracks"` but the album doesn't have a `"tracks"` property, create an empty array before adding the new value to the album's corresponding property.

Your lack of brackets for your control statements are valid but you'll need them for code blocks.

Happy coding!
