### ISSUE TITLE
code gives 

### ISSUE THREAD

**Issue by praveenoswal17** [FreeCodeCamp/FreeCodeCamp#11283]
![github issue](https://cloud.githubusercontent.com/assets/20150659/19533048/d219781c-965b-11e6-9180-46677b9c2432.png)
Challenge [Generate Random Whole Numbers with JavaScript](https://www.freecodecamp.com/challenges/generate-random-whole-numbers-with-javascript#?solution=%0Avar%20randomNumberBetween0and19%20%3D%20Math.floor(Math.random()%20*%2020)%3B%0A%0Afunction%20randomWholeNum()%20%7B%0A%20%20%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%20%20return%20Math.floor(Math.random()*10000)%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function randomWholeNum() {
  

  // Only change code below this line.

  return Math.floor(Math.random()*10000);
}

```

**Comment by dhcodes** [comment]
@praveenoswal17 thanks for the issue. This has been caught in issue #11110 and fixed in the development codebase. Closing as duplicate.
