### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jonatan-castaneda** [FreeCodeCamp/FreeCodeCamp#11281]
#### Challenge Name

Create a Form Element (It also happens in other Challenges)
https://www.freecodecamp.com/challenges/create-a-form-element
#### Issue Description

If I click on some line in the code editor, the cursor starts one line down. Example, if I click on line 22, when I start writing my code it appears on line 23 not in 22. It just happens in the first click, after this I'm able to click on other line and it's right again. Notice I don't have other problems like passing the challenge or errors about my code. 

#### Browser Information

* Browser Name, Version: Chrome 53.0.2785.143
* Operating System: Windows 10 64 bits
* Desktop

#### Your Code

```js
 
 
 
```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/22920249/19531307/d7135e5a-95fc-11e6-878b-cbe8a27da94b.png)

**Comment by erictleung** [comment]
@jonatan-castaneda thanks for the issue but this is a known issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7847. Closing this issue in favor of the pre-existing issue. Read some posts in that issue thread for some quick solutions/workarounds. Happy coding!
