### ISSUE TITLE
Issue in Waypoint: Meet Other Campers in your City

### ISSUE THREAD

**Issue by nischalsamji** [FreeCodeCamp/FreeCodeCamp#1128]
Challenge http://www.freecodecamp.org/challenges/waypoint-meet-other-campers-in-your-city has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Clicking on "I've Completed this challenge" causes an error.
![capture](https://cloud.githubusercontent.com/assets/887091/8386407/e60ce9e4-1c04-11e5-981b-14e1075895f1.PNG)

**Comment by benschenker** [comment]
Hey @nischalsamji 
It looks like that wyapoint no longer exists.  Fo more info see: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/August-2015-Improvements
