### ISSUE TITLE
**SOLVED** Challenge: Title Case a Sentence

### ISSUE THREAD

**Issue by yaseenagag** [FreeCodeCamp/FreeCodeCamp#11288]
function titleCase(str) {
  var result = "";
  var splitArray = str.toLowerCase().split(" ");
  for ( var i = 0; i < splitArray.length; i++ ) {
  result += splitArray[i].charAt().toUpperCase() + splitArray[i].slice(1) + " ";   
  }
  return result.slice(0, -1);
}

titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");

**Comment by yaseenagag** [comment]
```function titleCase(str) {
  var result = "";
  var splitArray = str.toLowerCase().split(" ");
  for ( var i = 0; i < splitArray.length; i++ ) {
  result += splitArray[i].charAt().toUpperCase() + splitArray[i].slice(1) + " ";   
  }
  return result.slice(0, -1);
}

titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");```

**Comment by yaseenagag** [comment]
ANSWER = Here is My Handle Here Is My Spout

I decided to use result.slice(0, -1) to remove the extra space at the end of the string.

**Comment by papajon0s1** [comment]
Ah... thanks for this.  Missed the trailing space....
