### ISSUE TITLE
Can anyone help me

### ISSUE THREAD

**Issue by Christopher37** [FreeCodeCamp/FreeCodeCamp#11289]
Challenge [Understand String Immutability](https://www.freecodecamp.com/challenges/understand-string-immutability#?solution=%0A%2F%2F%20Setup%0Avar%20myStr%20%3D%20%22Jello%20World%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0AmyStr%5B0%5D%20%3D%20%22H%22%3B%20%2F%2F%20Fix%20Me%0Avar%20myStr%20%3D%20%22Hello%20World%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStr = "Jello World";

// Only change code below this line

myStr[0] = "H"; // Fix Me
var myStr = "Hello World";


```

**Comment by Viltaria** [comment]
In the challenge, it specifies why you cannot change the value of myStr through myStr[0].
It also tells you the correct way to change a string.

```
var myStr = "Bob";
myStr = "Job";
```
