### ISSUE TITLE
the bootstrap MaxCDN link is not right

### ISSUE THREAD

**Issue by the94air** [FreeCodeCamp/FreeCodeCamp#11299]
#### Challenge Name
Use Responsive Design with Bootstrap Fluid Containers
https://www.freecodecamp.com/challenges/use-responsive-design-with-bootstrap-fluid-containers

#### Issue Description
the bootstrap MaxCDN link is not right

#### Browser Information

* Browser Name, Version: chrome V51.0.2704.79
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
it should be:
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
 
```

**Comment by erictleung** [comment]
@the94air thanks for the issue. This is a common way to tell the browser to just use whatever hypertext protocol is has. See more here http://stackoverflow.com/a/9646435/6873133. Happy coding!

**Comment by the94air** [comment]
I didn't know that before.Thanks
