### ISSUE TITLE
Change instructions in "Make Dead Links using the Hash Symbol"

### ISSUE THREAD

**Issue by Manish-Giri** [FreeCodeCamp/FreeCodeCamp#11297]
#### Make Dead Links using the Hash Symbol

https://www.freecodecamp.com/challenges/make-dead-links-using-the-hash-symbol

#### Issue Description
Having spent some time in the help room, I frequently see many new campers trip on this challenge. Although the current instructions are not in any way vague or difficult to understand, there is something about it that leads most campers to come up with this incorrect code instead - 

`
<p>Click here for <a #="http://www.freecatphotoapp.com">cat photos</a>.</p>`

Along with not reading the instructions carefully, I think this also stems, in part, from the way this instruction is worded 

> 
Replace the value of your a element's href attribute with a #, also known as a hash symbol, to turn it into a dead link.

I feel perhaps the wording (`element`, `attribute`, `value`) comes across as too technical for some new campers, which leads them to think that the `href` attribute itself should be replaced with a `#`. Maybe it could be replaced with something like this 

> The current value of the href attribute is a link that points to "http://www.freecatphotoapp.com". Change the value of href attribute such that it is a hash (#) instead.

Also, in a previous challenge, there is a [diagram](https://i.imgur.com/hviuZwe.png) that depicts the various parts of a `p` element and an anchor tag. 

![hviuzwe](https://cloud.githubusercontent.com/assets/11348778/19581844/222a2d0e-96fe-11e6-8bf7-0da80800544c.png)

While this may or may not be related to the issue here, the last arrow is somewhat incorrect - it actually points to the **value** of the **href attribute**, while the label reads **anchor tag's href attribute**.  Maybe a change in the label could be helpful for this issue? Thanks to @dhcodes for pointing this out!

Just putting in my two cents here! I think this is something we could look into. If the mods feel so too, I would be happy to work on a PR.

Cheers!

**Comment by dhcodes** [comment]
I'm in favor of the text change. I'm not sure how to change the diagram or if it's worth the effort once we change the text.

**Comment by systimotic** [comment]
I agree with @dhcodes. The text change can make a major difference. I think changing the diagram probably won't make all that much of a difference. I'd say it's a go @Manish-Giri!

**Comment by dhcodes** [comment]
go forth and PR @Manish-Giri

**Comment by Manish-Giri** [comment]
Okay, on it. Thanks.

**Comment by LooseYounit** [comment]
I have replaced the "anchor tag's href attribute" - "http://www.freecatphotoapp.com" with "#" and nothing happens. The instructions don't seem to make sense

**Comment by iysha** [comment]
@LooseYounit did u ever get an answer to your question. I'm having the same issue

**Comment by MinnaMonnet** [comment]
Oh dear, thank you. I was one of those who misunderstood the description! But google brought me here and it did the trick!

**Comment by YuriiCherniak** [comment]
I understood the description, but it just wouldn't go through, as if the browser wasn't "seeing" the change. Its the second challenge where i had to F5 refresh the page and do it again and only then it went through. P.S. Using chrome

**Comment by greenagain1** [comment]
After nearly pounding my head off the wall. I found this page. My frustration only grew as I read through the comments knowing I had been doing it correctly but still wasn't working. Then the very last comment.... F5 to refresh the Chrome page worked.
