### ISSUE TITLE
Article says 'Web site' not 'Website'

### ISSUE THREAD

**Issue by MysteriousManfred** [FreeCodeCamp/FreeCodeCamp#1129]
http://www.freecodecamp.com/field-guide/what-is-the-free-code-camp-privacy-policy

Specifically, the subheading 'Links to other Web sites' has an unnecessary and incorrect space.

**Comment by benschenker** [comment]
Thanks @MysteriousManfred, 

I'm not sure this is an issue, but the privacy policy is now a [github wiki page](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Free-Code-Camp's-Privacy-Policy) so you may edit it if you feel like it is still incorrect.
