### ISSUE TITLE
I cant resolve it

### ISSUE THREAD

**Issue by Madsander** [FreeCodeCamp/FreeCodeCamp#11295]
Challenge [Storing Values with the Assignment Operator](https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator#?solution=%0A%2F%2F%20Setup%0Avar%20a%20%3D%207%3B%0Avar%20b%20%3D%20a%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var a = 7;
var b = a;

// Only change code below this line


```

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by Viniciogj** [comment]
// Setup
var a;
var b = 2;

// Only change code below this line

var a = 7;
b = a;
