### ISSUE TITLE
Not letting me edit my code !

### ISSUE THREAD

**Issue by iamelmo1** [FreeCodeCamp/FreeCodeCamp#11292]
Challenge [Add Font Awesome Icons to all of our Buttons](https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-all-of-our-buttons) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>
    </div>
  </div>
  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info">Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger">Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```
I'm at the challenge where I'm adding font awesome icons to my buttons but it won't allow me to edit those buttons it just won't allow it. I refreshed several times.

**Comment by iamelmo1** [comment]
</div>
<div class="col-xs-4">
<button class"btn btn-block btn-info"><i class="fa-fa-circle-info"></i></button> </div>
<div class="col-xs-4">
<button class"btn btn-block btn-danger"><i class="fa-fa-thrash"></i></button> </div>

its the correct code but i can't apply it, i even tried copy and pasting walls of code but it only lets me delete a certain amount of code.

**Comment by Manish-Giri** [comment]
@iamelmo1 just type any key in the editor, it should "reset". Then proceed as normal.

**Comment by erictleung** [comment]
@iamelmo1 can you give more information on your issue? I understand you're unable to add your code but can you be more specific? I think the issue you're having is that when you try to edit code, you are adding the code in different lines that you intended. Please verify the issue you are having so that we can assist and/or fix your issue. Thanks!

**Comment by iamelmo1** [comment]
It's resolved thank you for your response. I'm new to coding so the
adjustment period is still there, it worked by typing a single symbol or
letter.
