### ISSUE TITLE
FCC Challenge tweet appears as spam by Twitter

### ISSUE THREAD

**Issue by Chris2Brooks** [FreeCodeCamp/freecodecamp#113]
When completing a challenge the option is given to tweet about it.
For the past week Twitter did not want to accept these Tweets because it looked like spam.

I verified this with @brianamarie as being an issue on Twitter's side and not user account.

Upon further testing, removing the website link from the tweet and keeping the @ FreeCodeCamp username and #learntocode #javascript hashtags, Twitter accepts the tweet.

Failed via FCC Tweet link:
![screenshot - 22022015 - 15 21 53](https://cloud.githubusercontent.com/assets/2293301/6318698/600d8860-baa9-11e4-9d7a-709463f119f4.png)

Failed directly on Twitter:
![screenshot - 22022015 - 15 21 36](https://cloud.githubusercontent.com/assets/2293301/6318699/6747fd54-baa9-11e4-8928-8dabea714c92.png)

Succesful - removing FCC link:
![screenshot - 22022015 - 15 43 34](https://cloud.githubusercontent.com/assets/2293301/6318707/b5ed3f82-baa9-11e4-864b-0c3d5042ead1.png)

**Comment by Chris2Brooks** [comment]
I tested this further and using Bit.ly to shorten the link, makes Twitter happy.
It's definitely the link that's causing the problem.

**Success - using Bit.ly** (will probably work with other link shortners as well)

![screenshot - 22022015 - 16 00 33](https://cloud.githubusercontent.com/assets/2293301/6318773/0c9bbe60-baac-11e4-82ee-6af88b8ca830.png)

**Comment by terakilobyte** [comment]
Thanks, I'll look into integrating with bitly's api automatically shorten the url

**Comment by terakilobyte** [comment]
This is solved in commit 0674466f5fc4e1390a612c94599d9bce8d0d14cb. Thanks for the report!
