### ISSUE TITLE
my tribute page

### ISSUE THREAD

**Issue by SweetLearner** [FreeCodeCamp/FreeCodeCamp#11302]
Challenge [Build a Tribute Page](https://www.freecodecamp.com/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by dhcodes** [comment]
Closing for now. Reopen if the site has an issue.
