### ISSUE TITLE
Bitly Shorten links

### ISSUE THREAD

**Issue by the94air** [FreeCodeCamp/FreeCodeCamp#11300]
#### Challenge Name
https://www.freecodecamp.com/challenges/make-images-mobile-responsive

#### Issue Description
bitly links isn't working in my country

```html
<img src="https://bit.ly/fcc-running-cats">
 
```

#### Screenshot
![bitly images](https://cloud.githubusercontent.com/assets/18303390/19588042/b0bb18fe-976b-11e6-9da8-121076fcecad.PNG)

**Comment by dhcodes** [comment]
@the94air sorry to hear that bitly links don't work where you live. When the site gets its next update, the challenge will accept either the bitly link or the actual src of the file `https://s3.amazonaws.com/freecodecamp/running-cats.jpg` per #10306. The latter should work internationally. Thanks for notifying us of the issue, though.
