### ISSUE TITLE
Challenge was doable (by copy/paste) but did not explain the code enough.

### ISSUE THREAD

**Issue by chemicalrush** [FreeCodeCamp/FreeCodeCamp#11303]
Edit: Figured it out, but decided to leave it up here so that people can see the "newb" thought process,

Solution: I overlooked .target in this code:

button class="btn btn-default target" id="target1"

Right after btn btn-default is the class target, followed by the id target. I just missed the first target.

Derp.

So for making the site more friendly to people being brain dead, like myself, I would add a simple reminder about the .target class and its location.
---
## newb thought process beyond this point

Challenge text:

Make the second child in each of your well elements bounce. You must target the children of element with the target class.

Final Code: 

$(".target:nth-child(2)").addClass("animated bounce");

The parts that seem confusing:

Why does the code only apply to the #target ids for the buttons? Where's the .well div, since it is the parent for the buttons? or the div that holds the columns? There are other "2nd children" within the code (some of them containing children themselves). So then I look at .target:nth-child, which looks like the previous example of selecting an actual class named target:nth-child(2), which obviously there is not one. So it's not a class, it doesn't select all 2nd children, it doesn't use #target to look at all of the ids named target, those ids don't have children, and the parent (one of the divs) is no where to be seen.  So I really didn't learn how it worked; it was just an exercise in copy/pasting and changing a word or number.

I am guessing that the reason it works only on those children is that they the most-nested of childen in the code, and then (by default) it doesn't apply to all children, only the most-nested?

I was guessing the code would have looked like $(".well").target:nthchild(2).addClass("animated bounce");

Because .well is the parent, we wanted to change  the children within that element (it would have applied to both wells on the page still), and we wanted to select the 2nd childen in the .well class elements.

So why 

$(".target:nth-child(2)").addClass("animated bounce");

and not 

$(".well").target:nthchild(2).addClass("animated bounce");

??

**Comment by systimotic** [comment]
Hi @chemicalrush! Thanks for sharing your though process. That's something that I also found confusing about `:nth-child(2)`. `.target:nth-child(2)` doesn't mean "the second child of target", it means "the element with that target class that is the second child". In reality, this seems to be useful in more cases, but it needed to 'click' inside my brain first. 
This is just a bit of a weird case. I think the description does a good job of explaining it with the example, I'm not sure how we could improve it.
What do you suggest we should do from here on out? Can this issue be closed?
