### ISSUE TITLE
Twitter linking functionality broken on Staging

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#11301]
#### Issue Description
Run staging locally and attempt to click "link my account with Twitter" on /settings

Twitter will attempt to send you back, but you'll arrive at http://localhost:3000/en/account instead of http://localhost:3000/account

Should /settings be under the /en/ subpath?

**Comment by BerkeleyTrue** [comment]
> Twitter will attempt to send you back, but you'll arrive at http://localhost:3000/en/account instead of http://localhost:3000/account

I'm not sure what this has to do with twitter linking.

The redirects from twitter should be /link/twitter/callback. These are not language subdomained.

Has this ever worked for you?
Does the account you are trying to link already linked to twitter?

**Comment by QuincyLarson** [comment]
@BerkeleyTrue this works in production, but I've never tried it on staging. My local database's account has not yet been linked with Twitter. I suspect that if this path were correct it would work.

**Comment by dhcodes** [comment]
@QuincyLarson fwiw, it's working on staging on my end. I made an fcc testing app at https://apps.twitter.com and then used http://www.freecodecamp.com as the Website and Callback url. After linking Github, I successfully linked Twitter with this method and it sent me to the correct place.

**Comment by BerkeleyTrue** [comment]
@dhcodes Thanks for confirming that.
