### ISSUE TITLE
Increment a Number with JavaScript Not Working

### ISSUE THREAD

**Issue by 0319** [FreeCodeCamp/FreeCodeCamp#11305]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=%0Avar%20myVar%20%3D%2087%3B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%20%3D%20%2B%2BmyVar%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 8530.96.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.154 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible. I think it is correct but it won't let me pass

My code:
```javascript

var myVar = 87;
// Only change code below this line
myVar = ++myVar;

```

**Comment by dhcodes** [comment]
@0319 this issue has come up before in #11258 and other issues. Ultimately, the goal of the exercise is to show incrementing without an `=` as seen in the Note on the challenge page instructions. In other words, it's not that your code doesn't work, it's that it isn't meeting the goals of what the challenge is trying to teach. Closing as duplicate.

**Comment by egossick** [comment]
Here is the correct solution:
var myVar = 87;

// Only change code below this line
myVar++;

**Comment by 401djslogan** [comment]
Thank a lot realize was doing this wrong also.
