### ISSUE TITLE
50% or 50px ???

### ISSUE THREAD

**Issue by patricia-grace** [FreeCodeCamp/freecodecamp#1130]
Challenge http://www.freecodecamp.com/challenges/waypoint-make-circular-images-with-a-border-radius has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

**Comment by treece** [comment]
Hi @patricia-grace ,

The challenge is wanting you to make the image circular. To make the image circular the `border-radius` would have to be `50%` If you ever need help or have questions, swing by the Help Chatroom: https://gitter.im/FreeCodeCamp/Help and someone would be glad to assist you :-)

Thanks,
Charles
