### ISSUE TITLE
Correct answer prints but is not being recognized

### ISSUE THREAD

**Issue by chocolatechimpcookie** [FreeCodeCamp/FreeCodeCamp#11313]
# Golf Code under JavaScript course

**The test requests:**

```
Strokes	         Return
1	                 "Hole-in-one!"
<= par - 2  	"Eagle"
par - 1	        "Birdie"
par	                "Par"
par + 1	        "Bogey"
par + 2	         "Double Bogey"
>= par + 3	"Go Home!"
```

**My code:**
**javascript**

```
function golfScore(par, strokes) {
  // Only change code below this line

  if (strokes == 1)
    {
      return "Hole-in-one!";
    }
  
  else if (strokes <= (par -2))
    {
      return "Eagle";
    }
  
  else if (strokes == (par -1))
    {
      return "Birdie";
    }
  else if (strokes == par)
    {
      return "Par";
    }
  
  else if (strokes == (par + 1))
    {
      return "Bogey";
    }

  else if (strokes == (par + 2))
  {
    return "Double Bogey";
  }
  else if (strokes >= (par + 3))
  {
    return "Go Home";
  }

  else
  {
  return "Change Me";
    
  }  
  // Only change code above this line
}

// Change these values to test
golfScore(5, 4);

```

**It says the following is not done:**

```
golfScore(4, 7) should return "Go Home!"
golfScore(5, 9) should return "Go Home!"
```

**Comment by erictleung** [comment]
@chocolatechimpcookie thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). **Hint**: look at the two tests you have pointed out and double check whether the strings it returns is *exactly* the same as what it requires. You have a missing character in the returned string. Happy coding!

**Comment by mymohame** [comment]
you forget the "!" in in "Go Home!"
and  to remove the  following section:
 else
  {
  return "Change Me"; ]

**Comment by lorduwahz** [comment]
Exactly the same with me. Forgot the ! after "Go Home!"

**Comment by OlegEf** [comment]
function golfScore(par, strokes) {
  // Only change code below this line
  if (strokes == 1){return "Hole-in-one!";}
  else if(strokes <= (par-2)){return "Eagle";}
  else if(strokes == (par-1)){return "Birdie";}
  else if(strokes == (par)){return "Par";}
  else if(strokes == (par+1)){return "Bogey";}
  else if(strokes == (par+2)){return "Double Bogey";}
  else if(strokes >= (par+3)){return "Go Home!";}
  
  else {return "Change Me";}
  // Only change code above this line
}

// Change these values to test
golfScore(5, 4);

**Comment by OlegEf** [comment]
Thank's for help!   You must change (=)   (==).
