### ISSUE TITLE
Roman Letters Testing Bug.

### ISSUE THREAD

**Issue by asiparsi930** [FreeCodeCamp/FreeCodeCamp#11319]
so i have been doing this challenge for the last 1-2 hours and i thought i finally got it.
the problem is that when i test numbers that are 1000 and above the results shows me the infinite loop massage.

this is my code:

![mycde](https://cloud.githubusercontent.com/assets/19238395/19618208/4755e196-984c-11e6-9f47-120a312ca229.jpg)

please help me here :)

**Comment by Dayfiri** [comment]
@asiparsi930 
You need more work on it. 
Your code is producing `infinite loop` and that is no good.
Check for help with code in the future here -> [help chat room](https://gitter.im/FreeCodeCamp/Help).
