### ISSUE TITLE
Stand in line

### ISSUE THREAD

**Issue by Muliro1** [FreeCodeCamp/FreeCodeCamp#11315]
#### Challenge Name

https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine%28arr%2C%20item%29%20{%0A%20arr.push%28item%29%3B%0A%20%20arr.shift%28%29%3B%0A%20%20%0A%20%20%0A%20%20return%20item%3B%20%20%2F%2F%20Change%20this%20line%0A}%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20[1%2C2%2C3%2C4%2C5]%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log%28%22Before%3A%20%22%20%2B%20JSON.stringify%28testArr%29%29%3B%0Aconsole.log%28nextInLine%28testArr%2C%206%29%29%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log%28%22After%3A%20%22%20%2B%20JSON.stringify%28testArr%29%29%3B%0A

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by PedroCSSilva** [comment]
Please be more specific.

**Comment by Manish-Giri** [comment]
@Muliro1 you're still missing a step of the challenge, look at this instruction -
> The nextInLine function should then return the element that was removed

and look at what you're returning. 

If you're still stuck, visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) for further help.

**Comment by dhcodes** [comment]
@Muliro1 you have an error in your code. Please consider asking for help in the chat room by clicking the Help button on the challenge or using the link posted by @Manish-Giri. Thanks.
