### ISSUE TITLE
React-Bootstrap CDN not working

### ISSUE THREAD

**Issue by Harry97** [FreeCodeCamp/FreeCodeCamp#11314]
#### Challenge Name

https://www.freecodecamp.com/challenges/build-a-recipe-box

#### Issue Description

While working on the recipe box challenge I decided to use react-bootstrap, but I kept getting errors in the console. So, I decided to try to build things locally and figure out the problem. I found that react-bootstrap didn't load in the first place. So, I think it would be nice to notify campers that the CDN doesn't work, so they don't waste their time. 

#### Screenshot

![404](https://cloud.githubusercontent.com/assets/6644545/19609769/59903c8a-97d9-11e6-94f7-6b2a1c0b497b.png)

**Comment by texas2010** [comment]
@Harry97, your issue is nothing with the fcc site.  if you need a help. you could go to chat room. okay

**Comment by Harry97** [comment]
I understand, but it does affect FCC one way or another. And, I've found out that the problem is solved by using non-minified version of both React and React-dom libraries, so I terminated the issue. You do have a point and I'mma keep it in my mind next time, thanks!
