### ISSUE TITLE
Help with Target the same element with multiple jQuery Selectors

### ISSUE THREAD

**Issue by NoirTyto** [FreeCodeCamp/FreeCodeCamp#11312]
Target the same element with multiple jQuery Selectors
Wont let me pass.
Ive read the other issues found in the forum and went to Glitter and tried to get help but no luck. I also youtubed the problem and found a video of someone doing the exact same challenged and my code looked identical to his but mine dosent let me pass. ive reset my code and retired it a few times and refreshed my browser. I honestly cannot tell what I am doing wrong. Any help would be very appreciated.

I am using windows 10 and the latest version of chrome

```js
 
<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn.primary");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

 
```

**Comment by NoirTyto** [comment]
Oh ok sorry

**Comment by kdelagram** [comment]
yea the code seems to be correct but doesn't pass the challenge...think there is an issue because if I copy and paste some code from the previous challenge and edit it to look just it does there, then it will pass...but if I write out the code instead of pasting it in then it won't pass...

**Comment by 401djslogan** [comment]
In case any one still need help or looking to be assisted with solving this challenges you have to enter the following:

<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn.primary");
$("#target1").addClass("animated")
$("#target1").addClass("shake")
  });
</script>

you are been ask to provide individual Jquery .addclass()
