### ISSUE TITLE
header issue 

### ISSUE THREAD

**Issue by RomaKushnir** [FreeCodeCamp/FreeCodeCamp#11316]
Hey everybody.  [Here is my portfolio](https://codepen.io/RomaKushnir/details/QKJxJE/) Scrolling below were portfolio pictures cross header is my problem yet. Header is transparent over that pictures. I also tried to embed background-size:cover to that pictures but failed. Don't mind to help me to fix my issue.
Thanks.

**Comment by erictleung** [comment]
@RomaKushnir GitHub is not the place for code and project feedback. I would use one of the Gitter rooms as that is a better and suggested way to get feedback. [Here](https://gitter.im/FreeCodeCamp/HelpFrontEnd) is one of the rooms where you can feedback. Closing as not an issue with the FreeCodeCamp website. Happy coding!

**Comment by RomaKushnir** [comment]
Thanks

2016-10-22 4:26 GMT+03:00 Eric Leung <notifications@github.com>:
