### ISSUE TITLE
Snyk error on Windows

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/freeCodeCamp#11323]
Hello good humans!
There's a problem with Snyk on Windows. `snyk protect` requires the Unix `patch` utility. This issue is related to #11145, which includes the error log. `snyk protect` runs automatically after `npm install` because of the `prepublish` script. A possible solution is to install this tool manually on Windows, or use the [git command line tools](https://git-for-windows.github.io/), which comes with most Unix tools. You could also just ignore the error, and everything will still work fine. 
I have found that it confuses and worries new contributors. I think it would be best to try to take away the problem completely. As far as I'm aware, there's no benefit in running this command in a development environment, it's only essential in production. I think we could remove the `prepublish` script, and move it to the `prestart-production` script.
The only potential problem I can see with this approach is that we could be creating a difference between the development environment and the production environment here, which is never ideal. Snyk patches are never meant to change any existing functionality (apart from the vulnerabilities) and they're used by many people, but it's still a slight risk. 
I'd love to hear your thoughts on this. I'd also be happy to work on a fix if/when we agree on something. As far as I'm aware, @BerkeleyTrue is the DevOps person, so I'm tagging you here.

_I took a few breaks while creating this issue, and had the tab open for a while. Just as I was about to start typing again to finish it up, I got a message asking me about this error on Gitter 😄_

**Comment by raisedadead** [comment]
Yeah that sounds about right, but this is probably just limited to Windows Dev Environment. Which means this is more specific to the Snyk integration itself and not free code camp's code base.

While I really like the idea, cause new contributors often get frightened with the complexity of setting up the env as such, I do suggest that this should be followed up with the Snyk team as well, for better Windows support, maybe in a separate issue? 

P.S : This is something why I recently moved to OSX from Windows.

**Comment by chiptus** [comment]
So you mean if I do npm install and get the error, i'm still good?
Can we add this to the notes for new contributors?
Also, using git bash worked.

**Comment by systimotic** [comment]
@chiptus Yep, it should all be fine. Adding this as a note is definitely an option. I think the best option would be to completely remove the source of the error, which is what we're talking about here. Thanks for confirming that git bash works!

**Comment by BerkeleyTrue** [comment]
Has anyone opened an issue with Snyk?

**Comment by nagesh-srivastava** [comment]
I get the error while npm install on windows 10. please find the log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\nages\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'snyk-protect' ]
2 info using npm@4.0.1
3 info using node@v4.6.1
4 verbose run-script [ 'presnyk-protect', 'snyk-protect', 'postsnyk-protect' ]
5 info lifecycle mean@0.7.0~presnyk-protect: mean@0.7.0
6 silly lifecycle mean@0.7.0~presnyk-protect: no script for presnyk-protect, continuing
7 info lifecycle mean@0.7.0~snyk-protect: mean@0.7.0
8 verbose lifecycle mean@0.7.0~snyk-protect: unsafe-perm in lifecycle true
9 verbose lifecycle mean@0.7.0~snyk-protect: PATH: C:\Users\nages\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\Projects\mean_project\\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Users\nages\AppData\Local\Microsoft\WindowsApps;C:\Users\nages\AppData\Roaming\npm
10 verbose lifecycle mean@0.7.0~snyk-protect: CWD: D:\Projects\mean_project\
11 silly lifecycle mean@0.7.0~snyk-protect: Args: [ '/d /s /c', 'snyk protect' ]
12 silly lifecycle mean@0.7.0~snyk-protect: Returned: code: 1  signal: null
13 info lifecycle mean@0.7.0~snyk-protect: Failed to exec snyk-protect script
14 verbose stack Error: mean@0.7.0 snyk-protect: `snyk protect`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\nages\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\nages\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:829:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid mean@0.7.0
16 verbose cwd D:\Projects\mean_project\
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nages\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "snyk-protect"
19 error node v4.6.1
20 error npm  v4.0.1
21 error code ELIFECYCLE
22 error mean@0.7.0 snyk-protect: `snyk protect`
22 error Exit status 1
23 error Failed at the mean@0.7.0 snyk-protect script 'snyk protect'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the mean package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     snyk protect
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs mean
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls mean
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

as i new for mean, please help me

**Comment by BerkeleyTrue** [comment]
> So you mean if I do npm install and get the error, i'm still good?

> @chiptus Yep, it should all be fine. 

You are fine. Please continue on and ignore this error

**Comment by BerkeleyTrue** [comment]
> Has anyone opened an issue with Snyk?

**Comment by raisedadead** [comment]
@nagesh-srivastava not related to issue but you need to bump to node 6 now.
@BerkeleyTrue on it.

**Comment by raisedadead** [comment]
### Possible solution for now unless they have a fix:

>The best workaround right now is to use patch.exe from https://git-scm.com/download/win

>We will add a feature request to bundle the patch binary with our installation so we don't have to rely on this existing externally.

~ Snyk Team

**Comment by dhcodes** [comment]
@raisedadead worth adding to the contributing.md documentation?

**Comment by BerkeleyTrue** [comment]
Is it possible to detect a windows environment and not run?

```json
"snyk-protect": "is-windows && snyk protect || echo \"Not running snyk on windows\""
```

**Comment by BerkeleyTrue** [comment]
@systimotic What does `echo $(OSTYPE)` print?

**Comment by systimotic** [comment]
![command tests](https://cloud.githubusercontent.com/assets/7262039/19801512/cdf7f290-9cff-11e6-8090-a6f43387d941.png)
Any variation of the top two commands doesn't work either (different quotes, no quotes, no echo, different capitalization, etc.).
The `ver` command doesn't work on Git Bash, which leads me to believe it probably won't work on Unix systems either. That's not great though, as a command not found will probably error out on Unix systems and work on Windows, which is not what we want. I've looked around for a few minutes, but I haven't been able to find a simple solution yet. If those two commands you suggested do log useful output on Unix systems, we could probably use those though. Seeing as Windows does log something, that makes it a bit more complicated, because there's also no grep.

**Comment by raisedadead** [comment]
Just chiming in.
On Windows echo doesn't work the way we are trying above. Commands are evaluated as they are. 

```
C:\Users\M>uname
Windows_NT

C:\Users\M>
```

**Comment by raisedadead** [comment]
You may use the output with pipe the output using `>`
Refer: http://stackoverflow.com/a/14574661/1932901
