### ISSUE TITLE
Wrong return values on side panel

### ISSUE THREAD

**Issue by melkisedek** [FreeCodeCamp/FreeCodeCamp#11320]
Challenge [Smallest Common Multiple](https://www.freecodecamp.com/challenges/smallest-common-multiple#?solution=function%20gcd(a%2C%20b)%7B%0A%20%20if(a%20%3D%3D%20b)%7B%0A%20%20%20%20return%20a%3B%0A%20%20%7D%20else%20if(a%20%3E%20b)%7B%0A%20%20%20%20a%20%3D%20a%20-%20b%3B%0A%20%20%20%20return%20gcd(a%2C%20b)%3B%0A%20%20%7D%20else%20if(b%20%3E%20a)%7B%0A%20%20%20%20b%20%3D%20b%20-%20a%3B%0A%20%20%20%20return%20gcd(a%2C%20b)%3B%0A%20%20%7D%0A%7D%0Afunction%20smallestCommons(arr)%20%7B%0A%20%20var%20num1%20%3D%20arr%5B0%5D%3B%0A%20%20var%20num2%20%3D%20arr%5B1%5D%3B%0A%20%20var%20lcm%20%3D%200%3B%0A%20%20lcm%20%3D%20(num1%20*%20num2)%20%2F%20gcd(num1%2C%20num2)%3B%0A%20%20console.log(num1)%3B%0A%20%20console.log(num2)%3B%0A%20%20console.log(gcd(num1%2C%20num2))%3B%0A%20%20console.log(lcm)%3B%0A%20%20return%20lcm%3B%0A%7D%0A%0A%0AsmallestCommons(%5B1%2C5%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function gcd(a, b){
  if(a == b){
    return a;
  } else if(a > b){
    a = a - b;
    return gcd(a, b);
  } else if(b > a){
    b = b - a;
    return gcd(a, b);
  }
}
function smallestCommons(arr) {
  var num1 = arr[0];
  var num2 = arr[1];
  var lcm = 0;
  lcm = (num1 * num2) / gcd(num1, num2);
  console.log(num1);
  console.log(num2);
  console.log(gcd(num1, num2));
  console.log(lcm);
  return lcm;
}


smallestCommons([1,5]);

```

Side panel:

>  smallestCommons([1, 5]) should return a number.
> smallestCommons([1, 5]) should return 60.
> smallestCommons([5, 1]) should return 60.
> smallestCommons([1, 13]) should return 360360.
> smallestCommons([23, 18]) should return 6056820.

**Comment by Bouncey** [comment]
@melkisedek can you expand on what you mean by 'wrong return values on side panel'?

To you mean the wrong value is displayed on the little black 'output' window, or the return values are wrong for the test cases?

**Comment by melkisedek** [comment]
The code above return lcm for the two numbers in the array. Someone in the forum informed me that it should have been for the **range** between and including the two numbers in the array.  I fixed it.
