### ISSUE TITLE
Your <style> should have a pink-text CSS class with its color set to pink.

### ISSUE THREAD

**Issue by welcometan** [FreeCodeCamp/FreeCodeCamp#11330]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
.pink-text {
    color: pink
  }
</style>
<h1 class="pink-text">Hello World!</h1>

```

**Comment by erictleung** [comment]
@welcometan although that color property for `.pink-text` only have one CSS property, we require that you have semi-colons at the end of each property. Yes, they aren't required but as you add more properties, these semi-colons will be needed. I hope that clears things up. Happy coding!

**Comment by ISolovieva** [comment]
Thank you, Actually ">" in different places confuses me a lot. :)

**Comment by PaulWalt74** [comment]
Thanks the H1 i thought was suppose to be in the style I had the right Idea with .pink-text and of course the class thing being a noob throws me off.

**Comment by Hugo97** [comment]
your forgot to put the ";" in the end of your code, after the word "pink"

**Comment by BraxtonD** [comment]
<h1>Thank You</h1>
<i>My friend</i>
