### ISSUE TITLE
Incorrect Challenge Test Case result on Chrome

### ISSUE THREAD

**Issue by zairmubashar** [FreeCodeCamp/FreeCodeCamp#11331]
#### Challenge Name

FEDC -> Basic Javascript -> Nest one Array within Another Array
https://www.freecodecamp.com/challenges/nest-one-array-within-another-array
FEDC -> Basic Javascript -> Store Multiple Values in one Variable using JavaScript Arrays
https://www.freecodecamp.com/challenges/store-multiple-values-in-one-variable-using-javascript-arrays
Probably more

#### Issue Description

After getting the solution correct, running tests, closing the "You Got It" popup by not continuing to the next challenge, modifying the declaration of the test variable by assigning it to itself, and running the tests again, we get treated to the same "You Got It" popup. See the code for more details.

#### Browser Information

* Browser Name, Google Chrome - Version 54.0.2840.59 (64-bit)
* Operating System: Linux Mint 17.3 Xfce 64-bit
* Mobile, Desktop, or Tablet: Laptop on a desk top.

I did try this bug on a Windows machine with Firefox. It isn't present. It _is_ present on Chrome however. I've used incognito mode in all cases. Windows Chrome version: 54.0.2840.71 m (64-bit)

#### Your Code

Code for a single challenge is sufficient here. I'm using code for the challenge "Nest one Array within Another Array".

The correct code. After running the tests "esc" out of the pop up.
```js
// Example
var ourArray = [["the universe", 42], ["everything", 101010]];

// Only change code below this line.
var myArray = [["a"]];
```

The following code will now be treated as correct:
```js
// Example
var ourArray = [["the universe", 42], ["everything", 101010]];

// Only change code below this line.
var myArray = myArray;
```

**Comment by dhcodes** [comment]
@zairmubashar I don't think this is an issue. The `myArray` variable is actually storing your nested array. This can be seen by opening the Dev Tools console in chrome and entering this code into the editor
```
var myArray = [["a"]];
console.log(myArray);
```

You'll see that myArray is storing `[["a"]]`. Therefore, if you replace `myArray = [["a"]]` with `myArray = myArray` then it will still pass because myArray has already been set to a nested array and therefore passes the tests.
