### ISSUE TITLE
Add Borders Around your Elements

### ISSUE THREAD

**Issue by MikeDisheng-Wang** [FreeCodeCamp/FreeCodeCamp#11339]
#### Challenge Name
Add Borders Around your Elements

#### Issue Description
this challenge must follow in order to finish: 
<style>
  .thin-red-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
  }
</style>

if I switch border-color/width/style in different order, for example:
<style>
  .thin-red-border {
    border-width: 10px;
    border-color: green;
    border-style: solid;
  }
</style>

it doesn't let me pass the challenge.  Doest the order really matter in this challenge? 
other codes are fine.

* Browser Name, Version: google 
* Operating System: chrome-os

**Comment by erictleung** [comment]
@MikeDisheng-Wang no, the order shouldn't matter. However, the class name does matter. At least in your code example here, you have the class `thin-red-border` but the challenge requires `thick-green-border`. That will prevent you from passing.

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
