### ISSUE TITLE
Stand in line has an issue

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#11348]
#### Challenge Name

localhost:3000/en/challenges/basic-javascript/stand-in-line
#### Issue Description

When running multiple tests, the `console.log()`'s stack up in the `output` window, even after a hard reload and reset of my code.

``` js
// running test
Before: [1,2,3,4,5]
Before: [1,2,3,4,5]
Before: [1,2,3,4,5]
Before: [1,2,3,4,5]
Before: [1,2,3,4,5]
Before: [1,2,3,4,5]
Before: [1,2,3,4,5]
Before: [1,2,3,4,5]
Before: [1,2,3,4,5]
Before: [1,2,3,4,5]
Before: [1,2,3,4,5]
Before: [1,2,3,4,5]
1
1
1
1
1
1
1
1
1
1
1
1
After: [2,3,4,5,6]
After: [2,3,4,5,6]
After: [2,3,4,5,6]
After: [2,3,4,5,6]
After: [2,3,4,5,6]
After: [2,3,4,5,6]
After: [2,3,4,5,6]
After: [2,3,4,5,6]
After: [2,3,4,5,6]
After: [2,3,4,5,6]
After: [2,3,4,5,6]
After: [2,3,4,5,6]
// tests completed
```
#### Browser Information

- Browser Name, Version: Chrome latest
- Operating System: Ubuntu 16.04
- Mobile, Desktop, or Tablet: Desktyop
#### Your Code

``` js
 function nextInLine(arr, item) {
  // Your code here
  arr.push(item);
  var removed = arr.shift();
  return removed;  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));
```

**Comment by dhcodes** [comment]
Confirmed. I wonder if this has to do with how this challenge is constructed. Most don't console.log the tests in the editor.

**Comment by Bouncey** [comment]
The reason for the console.log's is to demonstrate to the what these array methods are doing. 

Removing all the console.log's clears the issue with the challenge, but the chances of seeing the bug again are high when campers start using the output for console.logs instead of the dev console

**Comment by BerkeleyTrue** [comment]
@Bouncey no need to qualify your issues with `staging` in the title.

**Comment by ktajpuri** [comment]
Can I work on this? I can reproduce the issue in my local setup. @BerkeleyTrue @Bouncey

**Comment by raisedadead** [comment]
@ktajpuri sure, all `help wanted` issues are open to all for pull requests, unless they already have one. Please make sure you follow the contributing guidelines.

**Comment by ktajpuri** [comment]
Yup. Will do.

**Comment by ktajpuri** [comment]
This is strange. When I intentionally put error in console we have no output in console but all tests pass !
![image](https://cloud.githubusercontent.com/assets/10725893/20740174/0b604172-b6e7-11e6-92c3-6a386ad34cda.png)

**Comment by ktajpuri** [comment]
What is the intened behaviour here? Shall the console show the same output as the browser console? Or it should clear and just display the results once?
