### ISSUE TITLE
Test fails for correct code.

### ISSUE THREAD

**Issue by othwald** [FreeCodeCamp/FreeCodeCamp#11344]
I took the code directly from github that freecodecamp posted, and it still didn't work. Of the questions is this...smallestCommons([1, 5]) should return 60." It actually should be 5. 

Challenge [Smallest Common Multiple](https://www.freecodecamp.com/challenges/smallest-common-multiple#?solution=%0Afunction%20smallestCommons(arr)%20%7B%0A%20%20%2F%2F%20Sort%20array%20from%20greater%20to%20lowest%0A%20%20%2F%2F%20This%20line%20of%20code%20was%20from%20Adam%20Doyle%20(http%3A%2F%2Fgithub.com%2FAdoyle2014)%0A%20%20arr.sort(function(a%2C%20b)%20%7B%0A%20%20%20%20return%20b%20-%20a%3B%0A%20%20%7D)%3B%0A%0A%20%20%2F%2F%20Create%20new%20array%20and%20add%20all%20values%20from%20greater%20to%20smaller%20from%20the%0A%20%20%2F%2F%20original%20array.%0A%20%20var%20newArr%20%3D%20%5B%5D%3B%0A%20%20for%20(var%20i%20%3D%20arr%5B0%5D%3B%20i%20%3E%3D%20arr%5B1%5D%3B%20i--)%20%7B%0A%20%20%20%20newArr.push(i)%3B%0A%20%20%7D%0A%0A%20%20%2F%2F%20Variables%20needed%20declared%20outside%20the%20loops.%0A%20%20var%20quot%20%3D%200%3B%0A%20%20var%20loop%20%3D%201%3B%0A%20%20var%20n%3B%0A%0A%20%20%2F%2F%20Run%20code%20while%20n%20is%20not%20the%20same%20as%20the%20array%20length.%0A%20%20do%20%7B%0A%20%20%20%20quot%20%3D%20newArr%5B0%5D%20*%20loop%20*%20newArr%5B1%5D%3B%0A%20%20%20%20for%20(n%20%3D%202%3B%20n%20%3C%20newArr.length%3B%20n%2B%2B)%20%7B%0A%20%20%20%20%20%20if%20(quot%20%25%20newArr%5Bn%5D%20!%3D%3D%200)%20%7B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%0A%20%20%20%20loop%2B%2B%3B%0A%20%20%7D%20while%20(n%20!%3D%3D%20newArr.length)%3B%0A%0A%20%20return%20quot%3B%0A%7D%0A%0A%2F%2F%20test%20here%0AsmallestCommons(%5B1%2C5%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function smallestCommons(arr) {
  // Sort array from greater to lowest
  // This line of code was from Adam Doyle (http://github.com/Adoyle2014)
  arr.sort(function(a, b) {
    return b - a;
  });

  // Create new array and add all values from greater to smaller from the
  // original array.
  var newArr = [];
  for (var i = arr[0]; i >= arr[1]; i--) {
    newArr.push(i);
  }

  // Variables needed declared outside the loops.
  var quot = 0;
  var loop = 1;
  var n;

  // Run code while n is not the same as the array length.
  do {
    quot = newArr[0] * loop * newArr[1];
    for (n = 2; n < newArr.length; n++) {
      if (quot % newArr[n] !== 0) {
        break;
      }
    }

    loop++;
  } while (n !== newArr.length);

  return quot;
}

// test here
smallestCommons([1,5]);
```

**Comment by JTKnox91** [comment]
@othwald I found this prompt a bit confusing too. `smallestCommons([1,5])` is not asking for the smallest common multiple of `1` and `5` (which would be just `5`). Its asking for the smallest common multiple of `1`, `2`, `3`, `4`, and `5`. Which is in fact `60`. Does that answer your question?

**Comment by dhcodes** [comment]
@othwald remove the semi-colon from this line `while (n !== newArr.length);` and it will work with the code even though the editor will put an X by that line requesting a semi-colon. The editor doesn't do this on the staging branch so when the new version of the site goes live, it will work without removing the semi-colon.

**Comment by othwald** [comment]
Hi John,

  Yes it does! A new personal rule for me, no more late night programming.
Sorry for the brain freeze!

Thank you,
Kevin
