### ISSUE TITLE
Code lets pass user even if code is wrong because of inadequate number of  cases

### ISSUE THREAD

**Issue by praveenoswal17** [FreeCodeCamp/FreeCodeCamp#11341]
Challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=%0Afunction%20confirmEnding(str%2C%20target)%20%7B%0A%20%20%2F%2F%20%22Never%20give%20up%20and%20good%20luck%20will%20find%20you.%22%0A%20%20%2F%2F%20--%20Falcor%0A%20%20var%20b%3D3%3B%0A%20%20str%20%3D%20str.split('')%3B%0A%20%20target%20%3D%20target.split('')%3B%0A%20%20if(target.length%20%3D%3D1%20%26%26%20target%5B0%5D%20!%3D%20str%5Bstr.length-1%5D)%0A%20%20%20%20return%20false%3B%0A%20%20%20if(target.length%20%3D%3D1%20%26%26%20target%5B0%5D%20%3D%3D%20str%5Bstr.length-1%5D)%0A%20%20%20%20return%20true%3B%0A%20%20for(i%3D0%3Bi%3Ctarget.length%3Bi%2B%2B)%20%7B%0A%20%20if%20(target%5Btarget.lenghth-i%5D%20%3D%3D%20str%5Bstr.length-i%5D)%0A%20%20%20%20b%2B%2B%3B%0A%20%20%7D%0A%20%20if(i%3D%3Db%20)%0A%20%20%20%20return%20true%3B%0A%20%20else%20%0A%20%20%20%20return%20false%3B%0A%20%0A%7D%0A%0AconfirmEnding(%22dename%22%2C%20%22game%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  var b=3;
  str = str.split('');
  target = target.split('');
  if(target.length ==1 && target[0] != str[str.length-1])
    return false;
   if(target.length ==1 && target[0] == str[str.length-1])
    return true;
  for(i=0;i<target.length;i++) {
  if (target[target.lenghth-i] == str[str.length-i])
    b++;
  }
  if(i==b )
    return true;
  else 
    return false;
 
}

confirmEnding("dename", "game");

```

**Comment by praveenoswal17** [comment]
![new issue](https://cloud.githubusercontent.com/assets/20150659/19628672/da312d9c-9980-11e6-841c-481033b5c5c1.jpg)

**Comment by praveenoswal17** [comment]
one of 4th or 5th case word should have more characters

**Comment by systimotic** [comment]
This confused me at first. I didn't understand why the things that were happening were happening. I took a dive into your code, and I believe I understand it now. For anyone else, here is my commented out, console.log-ed upped version: [debugging confirm the ending](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=function%20confirmEnding(str%2C%20target)%20%7B%0A%20%20var%20b%20%3D%203%3B%0A%0A%20%20str%20%3D%20str.split(%27%27)%3B%0A%20%20target%20%3D%20target.split(%27%27)%3B%0A%0A%20%20if(target.length%20%3D%3D%3D%201%20%26%26%20target%5B0%5D%20!%3D%3D%20str%5Bstr.length%20-%201%5D)%20%7B%0A%20%20%20%20console.log(%27case%201%27)%3B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%0A%20%20if(target.length%20%3D%3D%3D%201%20%26%26%20target%5B0%5D%20%3D%3D%3D%20str%5Bstr.length%20-%201%5D)%20%7B%0A%20%20%20%20console.log(%27case%202%27)%3B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%0A%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20target.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(target%5Btarget.lenghth%20-%20i%5D%20%3D%3D%3D%20str%5Bstr.length%20-%20i%5D)%20%7B%20%0A%20%20%20%20%20%20%2F%2F%20lenghth%20is%20essential.%20%0A%20%20%20%20%20%20%2F%2F%20It%20eveluates%20to%20NaN%2C%20which%20is%20not%20an%20existing%20index%2C%20so%20we%20get%20undefined.%20%0A%20%20%20%20%20%20%2F%2F%20i%20starts%20at%20zero.%20str%5Bstr.length%20-%200%5D%20is%20out%20of%20range%2C%20thus%20we%20also%20get%20undefined.%20b%20*always*%20equals%20four.%0A%20%20%20%20%20%20%2F%2F%20i%20always%20ends%20at%20target.length%0A%20%20%20%20%20%20%2F%2F%20Coincidentally%2C%20all%20of%20the%20four%20letter%20checks%20are%20equal%20to%20true%2C%20and%20all%20of%20the%20other%20checks%20are%20false.%20%0A%20%20%20%20%20%20%2F%2F%20This%20doesn%27t%20go%20for%20the%20one%20letter%20cases%2C%20but%20those%20are%20handled%20above.%0A%20%20%20%20%20%20console.log(%27increment.%20cause%27%2C%20target%2C%20str%2C%20i)%3B%0A%20%20%20%20%20%20b%2B%2B%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20if(i%20%3D%3D%3D%20b)%20%7B%0A%20%20%20%20console.log(%27case%203%27%2C%20i%2C%20b)%3B%20%2F%2F%20always%20i%20%3D%204%2C%20b%20%3D%204%0A%20%20%20%20return%20true%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20console.log(%27case%204%27%2C%20i%2C%20b)%3B%20%2F%2F%20always%20i%20%3D%20target.length%2C%20target.length%20!%3D%3D%204%2C%20b%20%3D%204%0A%20%20%20%20return%20false%3B%20%20%0A%20%20%7D%0A%7D%0A%0AconfirmEnding(%22dename%22%2C%20%22game%22)%3B%0A)
Effectively, it's the same as this: [simplifying the debug](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=function%20confirmEnding(str%2C%20target)%20%7B%0A%20%20if(target.length%20%3D%3D%3D%201%20%26%26%20target%5B0%5D%20%3D%3D%3D%20str%5Bstr.length%20-%201%5D)%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%0A%0A%20%20if(target.length%20%3D%3D%3D%204)%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%0A%0A%20%20return%20false%3B%20%20%0A%7D%0A%0AconfirmEnding(%22dename%22%2C%20%22game%22)%3B%0A)
A solution like my second one shouldn't pass, of course.
This is almost like a plane crash, there are multiple factors that are causing this problem. If only one of them wasn't there, it wouldn't have happened. In this case, I believe it's a very good idea to take away one of the causes by modifying the test cases slightly. I think adding a test similar to your own, plus modifying an existing truthy test to test for more than four matching characters would be a fine solution.
Thanks for reporting this issue! I'd love to hear if anybody else has any input on this. I'd also be happy to work on a fix.

**Comment by Bouncey** [comment]
Oh wow! @praveenoswal17 thanks for finding this bug, it seems so obvious when looking at it now. 

But what an edge case to highlight it :+1: :smile: 

-

## First-timers only!

Add another test that should return true, but with a  `target.length > 4`.

The code for this challenge lies [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/52990dd1aa4542b0c5fa2ae4212da2b6f4e70c42/seed/challenges/01-front-end-development-certification/basic-bonfires.json#L355).

Following [CONTRIBUTING.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) will help you get set up with a local development environment, so you can test your changes.

If you have any issues whilst working on this, checkout the [Contibutors Chat Room](https://gitter.im/FreeCodeCamp/Contributors). Everyone here has been through the process of setting up and submitting their first PR to freeCodeCamp and can help with many issues you may come across.

Good luck and Happy Coding! :+1:

**Comment by systimotic** [comment]
@Bouncey I'd be in favor of also adding a test that has the last three or four characters equal, but only the very first character doesn't match. Something like `confirmEnding('Open sesame', 'game')`

**Comment by praveenoswal17** [comment]
As @Bouncey pointed out, one more case where target.length>4 case should be added.

**Comment by PedroCSSilva** [comment]
@Bouncey, can I be assigned for this issue? I'm a first-timer

**Comment by systimotic** [comment]
@praveenoswal17 I should clarify. Currently, checking the one length targets, returning true for the 4 length answers and returning false for everything else. Another passing solution would be to only check if the last two characters match. Adding a test that should return true with a target length larger than four fixes the first issue, but it doesn't help the second issue. A test like I suggested in my previous comment should help with that.
