### ISSUE TITLE
CSS style

### ISSUE THREAD

**Issue by flourmills** [FreeCodeCamp/FreeCodeCamp#11349]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20red%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {color: red;}
</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by systimotic** [comment]
Hi @flourmills! There's an issue with your code. For coding help, please go to [the Gitter help room](https://gitter.im/freecodecamp/Help). The 'help' button on the challenge also takes you there. Here's a hint: the color should be blue, and the h2 element should still be there. You only need to remove the `style` attribute of the h2 element.

**Comment by Bouncey** [comment]
@flourmills as @systimotic says:
