### ISSUE TITLE
Sum All Odd Fibonacci Numbers

### ISSUE THREAD

**Issue by serdartkm** [FreeCodeCamp/FreeCodeCamp#11345]
Page failed to respond after clicking the test button at https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers  link.
Clearing my browser's local storage and hard refreshing did not help. I could not finish this test and had to move to the next.

**Comment by erictleung** [comment]
@serdartkm it sounds like you may have introduced an infinite loop into your code. Please read this for more information on how to make it un-stuck http://forum.freecodecamp.com/t/disable-code-auto-run-on-free-code-camp/19511. If you are not experiencing this infinite loop, then please give us more information about the issue you're experiencing and maybe some screenshots. Thanks!

**Comment by serdartkm** [comment]
Hi everybody, thank you for your help. Finally I found the problem. I cleared the browser data and it seems to work.
