### ISSUE TITLE
Challenge "Prioritize One Style Over Another" at freecodecamp (HTML/CSS)

### ISSUE THREAD

**Issue by jorgemonte** [FreeCodeCamp/FreeCodeCamp#11346]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20%0A%20%20.pink-test%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22pink-test%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  
  .pink-test{
    color: pink;
  }

</style>

<h1 class="pink-test">Hello World!</h1>

```

**Comment by jorgemonte** [comment]
I'm quite sure I did everything that was requested but I can't still advance... I receive an "X" mark for those items: 
(X) Your h1 element should have the class pink-text.
(X) Your <style> should have a pink-text CSS class with its color set to pink.

**Comment by Manish-Giri** [comment]
@jorgemonte looks like you did everything requested except spelling `pink-text` correctly.

**Comment by jorgemonte** [comment]
Thank you @Manish-Giri ! This is a typical "time-to-sleep" mistake hahah, thanks!

**Comment by dudebrohellasick** [comment]
Ya i just got done reading another github convo about this and i just passed it with your help @jorgemonte 
I saw that period " . " and i slipped that into my code, it worked perfectly and now i can move on with my learning thanks aton bro

**Comment by jdimetric12** [comment]
The simplest err will cause our code not to run........
