### ISSUE TITLE
Can we also check if the user uses unshift instead of push

### ISSUE THREAD

**Issue by Coderoe** [FreeCodeCamp/FreeCodeCamp#11352]
Challenge [Count Backwards With a For Loop](https://www.freecodecamp.com/challenges/count-backwards-with-a-for-loop#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B%5D%3B%0A%0Afor%20(var%20i%20%3D%2010%3B%20i%20%3E%200%3B%20i%20-%3D%202)%20%7B%0A%20%20ourArray.push(i)%3B%0A%7D%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Afor(i%3D1%3B%20i%3C10%3B%20i%2B%3D2)%7B%0A%20%20myArray.unshift(i)%3B%0A%7D%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArray = [];

for (var i = 10; i > 0; i -= 2) {
  ourArray.push(i);
}

// Setup
var myArray = [];

// Only change code below this line.
for(i=1; i<10; i+=2){
  myArray.unshift(i);
}

As you can see, the challenge is to push and decrement by 2. I can very easily go around this with unshift and incrementing like in the last challenge. That gives us the same result, but not how the tutorial asked.


```

**Comment by sepiropht** [comment]
this issue is still free ? , can i work on that ?

**Comment by systimotic** [comment]
@sepiropht There's already an open Pull Request for this one. There are lots of other open issues though, your contribution is more than welcome!
