### ISSUE TITLE
Prior Bootstrap Classes Taught not showing up in subsequent code windows, in Lessons

### ISSUE THREAD

**Issue by TrinNicole** [FreeCodeCamp/FreeCodeCamp#11357]
Hiya,

Prior Bootstrap Classes Taught not showing up in subsequent code windows, specfically the `<btn>,`  `<btn-block>'  <btn-info>, <btn-primary>,<btn-danger>, `for` the Bootstrap CSS lessons,, in Lessons. I thought at first that this was done on purpose so that we memorize the bootstrap classes but it is blatantly obvious in the first lesson on the list, and it bugs me a lot haha.

#### Challenge Name
-** https://www.freecodecamp.com/challenges/use-the-bootstrap-grid-to-put-elements-side-by-side

- https://www.freecodecamp.com/challenges/taste-the-bootstrap-button-color-rainbow
- https://www.freecodecamp.com/challenges/call-out-optional-actions-with-button-info
- https://www.freecodecamp.com/challenges/warn-your-users-of-a-dangerous----   
- https://www.freecodecamp.com/challenges/create-a-block-element-bootstrap-button

-

#### Issue Description
When you load lesson asterisked on top, you see that the lesson is on the Bootstrap Grid. All past lessons are related to the bootstrap button. Each one of the previous lessons did not have the important **btn** and **btn-block** classes already filled in, and this one also did not have it filled in. I found it odd, as in previous lessons, the previous code that is used is almost always included (unless we're segueing purposely)

The first lesson on top, for the rendered code on the right  in the fake CatPhotoApp to work, the buttons should have been coded in the code preview already. However while the Bootstrap code was rendered in the fake app, the code preview window does not show the code...and the lesson is not even about putting that actual code in! Normally it's already put in for you, if it was covered in a previous lesson. 

#### Browser Information

* Browser Name, Version: Chrome Version 52.0.2743.82 
* Operating System:  Windows 7 Enterprise
* Mobile, Desktop, or Tablet:  Desktop
 
 
 

#### Screenshot
![image](https://cloud.githubusercontent.com/assets/22685766/19660193/c90b6aba-99fc-11e6-8528-609043fb1b92.png)

**Comment by Dayfiri** [comment]
Most of the exercises above that you mentioned have `btn` and `btn-default` class on `<button></button>` element. If not, then the assignment is to give them one.
Example of [Call out Optional Actions with Button Info](https://www.freecodecamp.com/challenges/call-out-optional-actions-with-button-info)
![screenshot from 2016-10-25 10-40-21](https://cloud.githubusercontent.com/assets/16082563/19678794/8c704b54-9a9f-11e6-947e-288f77129987.png)

This picture shows where the code is, that is responsible for rendering buttons on main page. 
![screenshot from 2016-10-25 10-42-29](https://cloud.githubusercontent.com/assets/16082563/19678918/0c5a4c52-9aa0-11e6-8eba-a6978dc8f3b1.png)

If I missed a point, feel free to correct me.

**Comment by dhcodes** [comment]
As @Dayfiri said, they are there, they are just moved down the page to make room for the style section. Please reopen if we're mistaken about the issue.

**Comment by TrinNicole** [comment]
Hiya,

Unfortunately not what I meant....most of what's listed in my bug form
already is past those lessons. Particulars the first one.

Thanks,:)

Katrina

**Comment by TrinNicole** [comment]
Hi,

Please re-open. Maybe I am missing something, and I'll post a screenshot as
soon as I can to illustrate,  but for most of the examples I posted, the
bootstrap code is in the HTML and not in the stylesheet.

 The classes are not defined, even though it is rendered in the fake app.
And, as I said, the lessons are no longer about doing those bootstrap
classes, have progressed beyond that.

That's why it's bugging me...because, if I understand correctly, any CSS,
Bootstrap or not, has to be defined first before being called within the
HTML

**Comment by dhcodes** [comment]
@TrinNicole I see what you mean. In this case, the CSS is being added via an external style sheet (not within style tags within the code). This is communicated via the following excerpt from the first challenge in the Bootstrap section.
>You can add Bootstrap to any app by adding the following code to the top of your HTML:

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>

In this case, we've already added it for you to this page behind the scenes.
