### ISSUE TITLE
Curly bracket problem with style sheets

### ISSUE THREAD

**Issue by mmcgabhann1955** [FreeCodeCamp/FreeCodeCamp#11350]
HI,
I'm working on style sheets for the first time. You can see the correct code below but when I enter the curly brackets {} a small dash appears automatically before the first bracket and after the second bracket, like this 
-{   }- . Can anyone offer a suggestion as to how to get rid of these dashes as I think they are interfering with my code. When I go to delete them, then the brackets disappear!
Thanks,
Michael

Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20blue%3B%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {color: blue;}
</style>

```

**Comment by Bouncey** [comment]
@mmcgabhann1955 Please reset the challenge and try again. You have deleted all elements from your code.

If you are still having problems passing the challenge, try the `Help` button, this will take you to a dedicated code help chat room.

GitHub issues are for problems/bugs with freeCodeCamp itself, not for help with challenges.

Happy Coding :+1:
