### ISSUE TITLE
Overring Styles in Subsequent CSS typographical error.

### ISSUE THREAD

**Issue by eXo5** [FreeCodeCamp/FreeCodeCamp#11356]
If you're reading this, just know that I'm a fucking moron. Thanks for your time, but disregard ENTIRELY lol

There's just a typo or an oversight.

#### Challenge Name

https://www.freecodecamp.com/challenges/override-styles-in-subsequent-css#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3Ablue%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%2C%20blue-text%22%3EHello%20World!%3C%2Fh1%3E%0A

#### Issue Description

The code won't work as described in the screen shot. It's missing a comma. I thought I was doing something wrong, and then had a brain fart and recognized the error. Kind of unimportant, but I can't imagine it was put in there intentionally. 

#### Browser Information

* Browser Name, Version: Google Chrome
* Operating System: Win7ult
* Mobile, Desktop, or Tablet: desktop

#### Your Code

```js
 
 
 
```

**Comment by erictleung** [comment]
@eXo5 thanks for the issue but commas aren't necessary when you add multiple classes to HTML elements. Your code is incorrect and that is why it is not passing the challenge. Please reread the instructions for how to complete the challenge, namely this snippet will help.

> Create an additional CSS class called `blue-text` that gives an element the color blue. Make sure it's below your `pink-text` class declaration.

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by eXo5** [comment]
So so sorry to have wasted your time, I had hoped you would have seen my
edit to my comment. I figured it out shortly after posting. Thanks for
taking a look at it though.

**Comment by sh6sha** [comment]
![image](https://cloud.githubusercontent.com/assets/5287070/19892218/da3f61ec-a069-11e6-9f82-0b8d6dbc77b2.png)

here in the screenshot I have declared two classes in the style. But the second class is not overriding the first class. Can Some reply this ? 

Thanks

**Comment by erictleung** [comment]
@sh6sha if you get stuck or have questions with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
