### ISSUE TITLE
my code will give roman for 400 as CCCC but it still passess the test.

### ISSUE THREAD

**Issue by harshtomar6** [FreeCodeCamp/FreeCodeCamp#11351]
Challenge [Roman Numeral Converter](https://www.freecodecamp.com/challenges/roman-numeral-converter#?solution=%0Afunction%20convertToRoman(num)%20%7B%0A%20%20var%20roman%2CromanNumber%3D''%2Ci%2Cflag%3D0%2Cn%3Dnum%3B%0A%20%20var%20r%20%3D%20%5B1%2C4%2C5%2C9%2C10%2C40%2C50%2C90%2C100%2C500%2C900%2C1000%2C15000%5D%3B%0A%20%20%0A%20%20while(n%3E0)%7B%0A%20%20for(i%3D0%3Bi%3Cr.length%3Bi%2B%2B)%7B%0A%20%20%20%20if(n%3Cr%5Bi%5D)%7B%0A%20%20%20%20%20%20flag%20%3D%20r%5Bi-1%5D%3B%0A%20%20%20%20%20%20n%20%3D%20n-flag%3B%0A%20%20%20%20%20%20switch(flag)%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20case%201%3A%0A%20%20%20%20%20%20%20%20roman%20%3D%20'I'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%204%3A%0A%20%20%20%20%20%20%20%20roman%20%3D%20'IV'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%205%3A%0A%20%20%20%20%20%20%20%20roman%20%3D%20'V'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%209%3A%0A%20%20%20%20%20%20%20%20roman%20%3D%20'IX'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%2010%3A%0A%20%20%20%20%20%20%20%20roman%20%3D%20'X'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%2040%3A%0A%20%20%20%20%20%20%20%20roman%20%3D%20'XL'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%2050%3A%0A%20%20%20%20%20%20%20%20roman%20%3D%20'L'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%2090%3A%0A%20%20%20%20%20%20%20%20roman%20%3D%20'XC'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%20100%3A%0A%20%20%20%20%20%20%20%20roman%20%3D%20'C'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%20500%3A%0A%20%20%20%20%20%20%20%20roman%20%3D%20'D'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%20900%3A%0A%20%20%20%20%20%20%20%20roman%20%3D%20'CM'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%201000%3A%0A%20%20%20%20%20%20%20%20roman%20%3D%20'M'%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%20%20romanNumber%20%3D%20romanNumber%2Broman%3B%0A%20%20%7D%0A%20return%20romanNumber%3B%0A%7D%0A%0AconvertToRoman(400)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function convertToRoman(num) {
  var roman,romanNumber='',i,flag=0,n=num;
  var r = [1,4,5,9,10,40,50,90,100,500,900,1000,15000];
  
  while(n>0){
  for(i=0;i<r.length;i++){
    if(n<r[i]){
      flag = r[i-1];
      n = n-flag;
      switch(flag)
      {
      case 1:
        roman = 'I';
        break;
      case 4:
        roman = 'IV';
        break;
      case 5:
        roman = 'V';
        break;
      case 9:
        roman = 'IX';
        break;
      case 10:
        roman = 'X';
        break;
      case 40:
        roman = 'XL';
        break;
      case 50:
        roman = 'L';
        break;
      case 90:
        roman = 'XC';
        break;
      case 100:
        roman = 'C';
        break;
      case 500:
        roman = 'D';
        break;
      case 900:
        roman = 'CM';
        break;
      case 1000:
        roman = 'M';
        break;
      }
      break;
      
    }
  }
    romanNumber = romanNumber+roman;
  }
 return romanNumber;
}

convertToRoman(400);

```

**Comment by Bouncey** [comment]
A test is needed for
```js
 convertToRoman(400); // CD
```

**Comment by Manish-Giri** [comment]
@Bouncey Can I take this up?

**Comment by Bouncey** [comment]
Sure @Manish-Giri go for it 👍

**Comment by Dayfiri** [comment]
@harshtomar6 
I just don't get it when you made roman numeral for 4 and 40, why didn't you make it for 400 as well ?

**Comment by harshtomar6** [comment]
@dayfiri
Thats the bug. The algorithm checks for 4 and 40 but it dont checks for 400

**Comment by Bouncey** [comment]
@Dayfiri the PR for this issue will force the camper to provide for the case of 400 :+1:

**Comment by Dayfiri** [comment]
@Bouncey that's nice and easy task to do. Good for new contributors :thumbsup

**Comment by jwebking** [comment]
@harshtomar6 could you please explain how the **if statemen**t works in your while statement? I'm having trouble understanding how the **if statement** works in the while loop. Specifically, how the (n<r[i]) works. If I input 0, is n becoming 1, or -1? What happens if n is 11 to start with?

```
  while(n>0){
  for(i=0;i<r.length;i++){
    if(n<r[i]){    **<--- this part**
      flag = r[i-1];
      n = n-flag;
      switch(flag)
      {
      case 1:
        roman = 'I';
        break;
      case 4:
        roman = 'IV';
        break;
      case 5:
        roman = 'V';
        break;
      case 9:
        roman = 'IX';
        break;
      case 10:
        roman = 'X';
        break;
      case 40:
        roman = 'XL';
        break;
      case 50:
        roman = 'L';
        break;
      case 90:
        roman = 'XC';
        break;
      case 100:
        roman = 'C';
        break;
      case 500:
        roman = 'D';
        break;
      case 900:
        roman = 'CM';
        break;
      case 1000:
        roman = 'M';
        break;
      }
      break;

    }
  }
    romanNumber = romanNumber+roman;
  }
```



Thank you in advance.

**Comment by Dayfiri** [comment]
@jwebking 
Hey man. For the logic behind converting number -> roman numeral, check [this](http://www.rapidtables.com/convert/number/how-number-to-roman-numerals.htm) link. I used this example as a logic which I later implemented in the code.

**Comment by jwebking** [comment]
@Dayfiri Thanks for the link, I appreciate it!
