### ISSUE TITLE
text should be zoom to 100%

### ISSUE THREAD

**Issue by Sbusiey** [FreeCodeCamp/FreeCodeCamp#11364]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20%0A%20%20.p%7Bfont-size%3A16%20pixels%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%20class%3D%22p%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  
  .p{font-size:16 pixels}
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p class="p">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by Dayfiri** [comment]
@Sbusiey 
There are few mistakes in your code. 
1. Create a new `<p></p>` element with Kitty ipsum text. No need to put any class name on that paragraph
2. In `<style>` tags use a `p` indicator for a paragraph. `dot(.)` is used on classes and you don't need class as I mentioned in example above
3. size is measured in `pixels` in this case. So if you wanna put a specific size, you will write:
`font-size: 16px` and **not** `font-size: 16 pixels`.
Note that `16` and `px` need to be put together without a `spacing`.

**Comment by Sbusiey** [comment]
@Dayfiri 
thanks for help :+1:

**Comment by Jatasya11** [comment]
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<style>
  .p {
    font-size: 16px;
  }
</style>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>



how to solve this query ?
Between the style tags, give the p elements font-size of 16px. Browser and Text zoom should be at 100%.

**Comment by texas2010** [comment]
@Jatasya11 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
