### ISSUE TITLE
freecatphotoapp.com is now a link farm site. We need to use a different URL that we control

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#11365]
Some of our challenges refer to "freecatphotoapp.com" which I came up with as a joke domain. Well, apparently enough people were clicking on it that someone registered the domain and put up a link farm site. 

Someone mentioned the site might have some NSFW content, as well, so we should definitely replace this sooner rather than later. We might want to change it for "freecodecamp.com/catphotoapp" and create an end point with some sort of placeholder - perhaps a polished-looking static HTML cat photo app.

**Comment by Dayfiri** [comment]
Hi Quincy, 
I would like to help with this one just I'm interested in more info about it if possible.
1. Is making "freecodecamp.com/catphotoapp" reference for creating new directory in FreeCodeCamp github repository ?
2. What would "polished-looking static HTML cat photo app" look like exactly ? Like static html page with a grid made of cat pictures or something similar to it ?

**Comment by atjonathan** [comment]
@QuincyLarson, me and @Bouncey created a catphotoapp for this purpose. github.com/atjonathan/catphotoapp :smiley: We can use this and host it on freecodecamp.com/catphotoapp?

**Comment by Dayfiri** [comment]
@atjonathan That looks nice. You should definitely use it. 👍

**Comment by atjonathan** [comment]
@Dayfiri thanks!

**Comment by Bouncey** [comment]
The idea behind [our CatPhotoApp](https://github.com/atjonathan/catphotoapp) was that it was interactive to the user, uploading cats and what-have-you, but isolated aswell. 

So that if a user uploaded NSFW content, it would only be on their device. This removes the need for constant moderation from the freeCodeCamp team :+1:

**Comment by raisedadead** [comment]
I own the https://fcc.rocks domain, and I was planning it as a "unofficial" showcase of some stuff, but would be happy to donate it (by pointing its NS records to whatever location need be) to the community if it suites and is acceptable.

/cc @QuincyLarson

**Comment by QuincyLarson** [comment]
@raisedadead actually, fcc.rocks would be good place to host it because it's much shorter that freecatphotoapp.com, and we won't have to worry about the CSS and everything else associated with the cat photo app. 

@Bouncey so to be clear, other than the images already there, people will only see images they themselves upload to it?

**Comment by atjonathan** [comment]
@QuincyLarson, correct. We use local storage to store the images they upload. Only the default ones will be shown on everyone's.

**Comment by Bouncey** [comment]
All images and likes are stored in localStorage. There is no database for this app.

**Comment by QuincyLarson** [comment]
@atjonathan @Bouncey ok - great! That's a solid approach to subtly solving the troll problem.

**Comment by BerkeleyTrue** [comment]
This is extremely strange as I still own the domain. I'm looking into it

**Comment by BerkeleyTrue** [comment]
I've changed the name servers and parked as well. These are propagating now.

**Comment by raisedadead** [comment]
Ah cool. thanks @BerkeleyTrue, BTW fcc.rocks is still up for grabs, we could do something with it... 😜 !!!

**Comment by BerkeleyTrue** [comment]
Ok, looks like that is working. 

@Bouncey Can we move the app under the freecodecamp org?

**Comment by atjonathan** [comment]
@BerkeleyTrue, I currently own the repository. Should FCC just make a fork?

**Comment by QuincyLarson** [comment]
@atjonathan there's the issue of contributions to forks not counting toward GitHub's tracking of open source contributions. This is one reason why none of the repos on Free Code Camp's organization are forks. We want campers to get credit if they put in the time to improve something. So we should transfer the repo over to Free Code Camp if it's OK with you.

**Comment by atjonathan** [comment]
@QuincyLarson, I'm unable to transfer the repository due to not having admin rights.

**Comment by BerkeleyTrue** [comment]
Thanks @atjonathan. Let's switch to gitter chat

**Comment by atjonathan** [comment]
Update: We have moved the repository over to FreeCodeCamp/catphotoapp 😃

**Comment by QuincyLarson** [comment]
@atjonathan awesome! Great work.

@raisedadead rather than purchase a special domain, we could just use something like bit.ly/catphotoapp and redirect to a GitHub pages site. Then we don't have to pay for another domain or host it anywhere.

**Comment by BerkeleyTrue** [comment]
@QuincyLarson If we are going that far, does that challenge even need a domain?

**Comment by QuincyLarson** [comment]
@BerkeleyTrue You're right - we could simply use example.com, which is designated for example usage. This would also teach campers indirectly that they should use this instead of random domains. 

It would be simpler than having to bother with building and maintaining another app, and as far as I can tell there's nothing in the challenge that requires it to be a valid domain.

It's not as fun, but it is practical, and I think we should be taking our curricula in a practical direction.

**Comment by raisedadead** [comment]
Sounds good to me.

**Comment by Bouncey** [comment]
I might be bias 🙄, but I like the 'easter egg' value it adds. 

We built CatPhotoApp due to many issues of camper clicking on the link in the preview and raising an issue that it didn't work properly. I think for a long time there was a php server error displayed, not sure. 

As for maintenance, there are not that many moving parts, it's a SPA without a sniff of a router.

**Comment by QuincyLarson** [comment]
@Bouncey what URL will it be up at? I can update the challenges accordingly. I am making a general copy update PR for production anyway and can make this change as well.

**Comment by atjonathan** [comment]
@QuincyLarson, freecodecamp.github.io/catphotoapp :wink:

**Comment by Bouncey** [comment]
Are we using a CNAME for freecatphotoapp.com?

**Comment by atjonathan** [comment]
That's usually the best way for setting it up. Tagging @BerkeleyTrue

**Comment by Bouncey** [comment]
Haha - nice holding image @BerkeleyTrue 

How is the cname generated? Does it come from the DNS?

**Comment by Bouncey** [comment]
Nevermind, got it :+1:
