### ISSUE TITLE
Unclear why the squared brackets from the previous challenge aren't present in this one

### ISSUE THREAD

**Issue by marienhof** [FreeCodeCamp/FreeCodeCamp#11378]
Challenge [Accessing Nested Objects](https://www.freecodecamp.com/challenges/accessing-nested-objects) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A456 Safari/602.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStorage = {
  "car": {
    "inside": {
      "glove box": "maps",
      "passenger seat": "crumbs"
     },
    "outside": {
      "trunk": "jack"
    }
  }
};

// Only change code below this line

var gloveBoxContents = ""; // Change this line


```

**Comment by dhcodes** [comment]
@marienhof could you elaborate? The challenge before has a nested array and this has a nested object. The instructions on the previous challenge say: 

>A JavaScript object is one way to handle flexible data. They allow for arbitrary combinations of strings, numbers, booleans, arrays, functions, and objects.

so I'm not sure more explanation about the change is necessary.

**Comment by dhcodes** [comment]
Closing as resolved. Please reopen if you want to discuss.
