### ISSUE TITLE
Additional waypoint suggestion: Intro to creating tests using popular test suites

### ISSUE THREAD

**Issue by dexrualo** [FreeCodeCamp/FreeCodeCamp#1137]
Since developers should know how to test their own code, maybe it is a good idea to include at least an intro to testing?

This I found in Udacity: https://www.udacity.com/course/javascript-testing--ud549

**Comment by LumenTeun** [comment]
+1

**Comment by alexlincoln** [comment]
+1

**Comment by metasean** [comment]
:+1:

**Comment by FFX01** [comment]
+1

**Comment by BerkeleyTrue** [comment]
This is coming, but we need to change the way we currently run test in order to run test on test. 
![xzbitsad](https://cloud.githubusercontent.com/assets/6775919/9482839/3b7d1d0a-4b4d-11e5-99d5-c9d9d5e0264f.png)

**Comment by RandomlyKnighted** [comment]
:+1:

**Comment by ltegman** [comment]
Closing in favor #5847. Please continue any discussion in that thread.
