### ISSUE TITLE
Code Formatting wiki link redirects to FreeCodeCamp Codebase Page

### ISSUE THREAD

**Issue by Dave1089** [FreeCodeCamp/FreeCodeCamp#11372]
### How I generated the issue:

I found it while giving proper code formatting link to a camper in Gitter Help Chatroom today
#### Issue Description

Link : [Code Format Wiki](https://github.com/freecodecamp/freecodecamp/wiki/code-formatting) redirects to 
https://github.com/FreeCodeCamp/FreeCodeCamp codebase page
#### Browser Information

Chrome v 54.0 (64 bit)

Mac OS X

**Comment by sludge256** [comment]
@QuincyLarson has hidden the repo wiki as it is no longer maintained. All links to wiki articles will redirect to the repo page now.

**Comment by Dave1089** [comment]
well.. then Camper Bot shouldn't give this link when typed short command `'''` to give a camper suggestion to understand how one can format the code in gitter, many people often use this method. So it can be considered issue with camperbot I guess

**Comment by erictleung** [comment]
Looks like [this line of code](https://github.com/FreeCodeCamp/camperbot/blob/6013edabcb34159501270cce4fec5b2f64f76133/data/rooms/RoomMessages.js#L38) needs to be updated in the Camperbot codebase.

**Comment by Manish-Giri** [comment]
@erictleung [This](http://forum.freecodecamp.com/t/markdown-code-formatting/18391) looks like it could be an ideal replacement.

**Comment by Dave1089** [comment]
@Manish-Giri Agree

**Comment by Bouncey** [comment]
Freecodecamp/camperbot#103 refers to this

**Comment by Manish-Giri** [comment]
I can do this change, if it needs to be done.

**Comment by Bouncey** [comment]
@Manish-Giri If you want to have a crack at it, head on over to the [camperbot repo](https://github.com/FreeCodeCamp/camperbot) :+1:

**Comment by QuincyLarson** [comment]
@Dave1089 thanks for catching this issue. Yes, I agree with everyone on this thread - we should move forward with the fix. 

@Manish-Giri here is the new wiki article: http://forum.freecodecamp.com/t/markdown-code-formatting/18391.json (in .json form, with its contents converted to HTML)

You may need to modify CamperBot to be able to pull the HTML out and render it properly. Gitter does not seem to render HTML properly. One alternative would be for you to hard-code Camperbot's response to this since as far as I can tell, this wiki article hasn't changed in a year.

**Comment by pnahratow** [comment]
Also affects the link to the Heroku+MongoDB integration article on https://www.freecodecamp.com/challenges/url-shortener-microservice

**Comment by Dave1089** [comment]
I agree with @pnahratow

**Comment by QuincyLarson** [comment]
@Dave1089 @pnahratow would one of you like to fix this? It should now point to http://forum.freecodecamp.com/t/guide-for-using-mongodb-and-deploying-to-heroku/19347

**Comment by pnahratow** [comment]
@QuincyLarson 
Seem to already be in staging since July see a45b0a56

**Comment by QuincyLarson** [comment]
@pnahratow ok - thanks for the heads-up.

@BerkeleyTrue do you know the easiest way to apply an accepted PR to a second branch - in this case, backup/master?
