### ISSUE TITLE
 Resource Link down from google documentation

### ISSUE THREAD

**Issue by Luiko** [FreeCodeCamp/FreeCodeCamp#11375]
#### Challenge Name
[Chrome Dev Tools: Elements](https://www.freecodecamp.com/videos/chrome-dev-tools-elements)

#### Issue Description
Only this [link](https://developers.google.com/web/tools/chrome-devtools/inspect-styles/basics
) is down, there are [another](http://developers.google.com/web/tools/chrome-devtools) without problems

**Comment by Luiko** [comment]
There is another [link down](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/network-performance/resource-loading) on the [next ](https://www.freecodecamp.com/videos/chrome-dev-tools-network) video challenge, and probably in all the Chrome Developer Tools section.

**Comment by dhcodes** [comment]
Thanks for the issue @Luiko. It's been fixed by this pull request https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11042 so it will eventually go live on the main site when the next update is pushed. Closing as duplicate.
