### ISSUE TITLE
Update UX on reset progress and delete account buttons

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#11382]
Refer https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10824

**Comment by johnnyqbui** [comment]
@atjonathan was wondering if I can help out with this?

**Comment by atjonathan** [comment]
@johnnyqbui, sure, we are hoping to remove the animations on the "are you sure?" routes. Sorry, I didn't get round to this myself 😖

**Comment by johnnyqbui** [comment]
No worries, I'll try my best! Thanks!

**Comment by johnnyqbui** [comment]
@atjonathan I removed the crazy wobble animation, did you also want to center it and change the color to something else?

**Comment by atjonathan** [comment]
@johnnyqbui, awesome! Yeah if it could be centered horizontally and vertically, and adjust the design to be a little more modern, that would be great 😃

**Comment by johnnyqbui** [comment]
![deleteaccount](https://cloud.githubusercontent.com/assets/17282870/20770543/bb886862-b70b-11e6-985e-1719258320fc.JPG)
![deleteaccount2](https://cloud.githubusercontent.com/assets/17282870/20770544/bb9948a8-b70b-11e6-8fa1-52dd13b8ce3a.JPG)

I just gave it a lighter grey background color and added more px to the top margins to center it. What do you think?

**Comment by johnnyqbui** [comment]
I wasn't sure what other colors to use

**Comment by johnnyqbui** [comment]
![deleteaccount](https://cloud.githubusercontent.com/assets/17282870/20771306/80c37890-b70e-11e6-835d-0b9c24f04b2f.JPG)
![deleteaccount2](https://cloud.githubusercontent.com/assets/17282870/20771305/80bf97a2-b70e-11e6-9aa7-1e04538a26db.JPG)

Gave the success button a green color

**Comment by atjonathan** [comment]
@johnnyqbui, sorry to be picky! I think if the title, "You don't really...", and the "x" button should be on the same line. The buttons shouldn't have as much spacing vertically either. Thanks again!

**Comment by johnnyqbui** [comment]
@atjonathan ok no problem!

**Comment by johnnyqbui** [comment]
@atjonathan 
![deleteaccount](https://cloud.githubusercontent.com/assets/17282870/20772846/d29fa2be-b714-11e6-8ca2-fd3bff908b2a.JPG)

Like this? I also increased button size a little bit for easier tap target. Let me know what you think.

**Comment by atjonathan** [comment]
@johnnyqbui, looks great! Thanks so much for taking the time to do this, feel free to open a pull request 😄
