### ISSUE TITLE
Cnvert to html not working for <>

### ISSUE THREAD

**Issue by silverwedding** [FreeCodeCamp/freecodecamp#1138]
function convert(str) {  
  var str_arr = str.split('');
  for(var i = 0; i < str_arr.length;i++) {
    console.log(str_arr[i]);
    switch (str_arr[i]) {
      case '&': str_arr[i] = '&amp;'; break;  
      case '<': str_arr[i] = '&lt;'; break;
      case '>': str_arr[i] = '&gt;'; break;
      case '"': str_arr[i] = '&quot;'; break;
      case '\'': str_arr[i] = '&apos;'; break;
    }
  }  
  str = str_arr.join('');
  return str;
}

convert('<>');

**Comment by QuincyLarson** [comment]
Thank you for your help! We've now fixed this in production!
