### ISSUE TITLE
Issue report : Using Objects for Lookups 

### ISSUE THREAD

**Issue by karlchvojka** [FreeCodeCamp/FreeCodeCamp#11388]
#### Challenge Name

[Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups)

#### Issue Description

Nothing major. Need to move line 20 into the editable comments because line 20 needs to be changed to look through the object for the code to run. 

#### Browser Information

* Browser Name, Version: Chrome latest
* Operating System: MSW 10
* Mobile, Desktop, or Tablet: Desktop 1920x1080

#### Your Code

```js
// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  
  var lookup = {
   alpha: "Adams",
    bravo: "Boston",
    charlie: "Chicago",
    delta: "Denver",
    echo: "Easy",
    foxtrot: "Frank"
  };
 
  // Only change code above this line
  return result = lookup[val];
}

// Change this value to test
phoneticLookup("charlie");
```

**Comment by sludge256** [comment]
It's not necessary because you can perform a variable assignment in the "// Only change code above this line" section.
