### ISSUE TITLE
Possible error

### ISSUE THREAD

**Issue by millennialtraveller** [FreeCodeCamp/FreeCodeCamp#11393]
#### Challenge Name

Use CSS Selectors to Style Elements

https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0Ah2%20%7BColorado%3A%20blue%3B%7D%20%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%20%20%3C%2Fstyle%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
<style>
h2 {color: blue;} 
</style> 
```
#### Screenshot

The blue text isn't registering as blue. Not working at all after copying the example to change h2 element text to blue using CSS. I think there is an error because I am using the exact code in the example. Plus, the blue text doesn't turn blue ince the open { is added - only without it .

**Comment by raisedadead** [comment]
Your code is incorrect, remember you gotta delete something and add something.

Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by homedefense** [comment]
Finally, I got it right here, the instruction is seemed confusing
<style>
  h2  {color: green;}  CatPhotoApp  
</style>



<style>
  h2  {color: green;} 
</style>

<h2>CatPhotoApp</h2>
