### ISSUE TITLE
Selecting from many options with Switch Statements

### ISSUE THREAD

**Issue by TatjanaBezsazna** [FreeCodeCamp/FreeCodeCamp#11399]
#### Challenge Name

https://www.freecodecamp.com/challenges/selecting-from-many-options-with-switch-statements

#### Issue Description
I am quite sure I did it correctly, and still it does not work... 

#### Your Code

function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  case 1:
    answer = "alpha";
    break;
  case 2:
    answer = "beta";
    break;
  case 3:
    answer = "gamma";
    break;
  case 4:
    answer = "delta";
    break;
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(1);

```js
 
 
 
```

**Comment by Bouncey** [comment]
@TatjanaBezsazna There is an error in your code, please read the instructions again (take note of the example code in the instructions)

If you are still stuck, please use the `Help` button. This will take you to a dedicated chat room for code help.

GitHub issues are for issues with freeCodeCamp as a service, not for help passing challenges

Many thanks :+1: 


Closing: code help

**Comment by Neralizer** [comment]
Default function name is myTest, but FCC tests for caseInSwitch()

**Comment by Bouncey** [comment]
@Neralizer

I have tested this on both freeCodeCamp.com and beta.freeCodeCamp.com and the default `function` declaration is `caseInSwitch` please check your code. You may need to click the reset button

Happy coding!
