### ISSUE TITLE
Stand in Line Challenge - State the format the result should be returned in [Copy]

### ISSUE THREAD

**Issue by tombarton** [FreeCodeCamp/FreeCodeCamp#11398]
#### Challenge Name
Stand in Line (https://www.freecodecamp.com/challenges/stand-in-line)

#### Issue Description
The exercise instructions do not state how the first element of the array should be returned:

>The `nextInLine` function should then return the element that was removed.

This could lead to confusion as there are multiple ways to extract the first element of the array. For example, if you used `spice(0,1)`, the output appears perfect but fails the unit tests as it is returned as an array rather than an integer.

#### Browser Information

* Browser Name, Version: Chrome, 54
* Operating System: Windows 8.1
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
![standinline](https://cloud.githubusercontent.com/assets/6222711/19770499/66dadb16-9c57-11e6-958a-0162e2a79210.PNG)
![standinline2](https://cloud.githubusercontent.com/assets/6222711/19770500/66dceb7c-9c57-11e6-8795-1c8b31b68421.PNG)

**Comment by Bouncey** [comment]
@tombarton Thanks for the issue.

[The return value of Array.prototype.splice()](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/splice#Return_value) is an array containing the element(s) removed from the original array. Not the element itself.

> ### Return value
>
> An array containing the deleted elements. If only one element is removed, an array of one element is returned. If no elements are removed, an empty array is returned.

The challenge instructions ask you to return the element that was removed, not an array containing the element that was removed.

If you want to use the `Array.prototype.splice()` method ofr this challenge, you would then need to extract the element inside of the new array created by the `splice` method.

I hope this clears things up for you.

If you think the challenge instructions could be improved, I am open to suggestions :+1:

**Comment by tombarton** [comment]
Thanks @Bouncey. It's probably my comprehension skills that need to improve!

I think it was the output box that threw me more than anything. It wasn't until I checked the console log that I realised my mistake.
