### ISSUE TITLE
C9 and GitHub connecting issues

### ISSUE THREAD

**Issue by gatewayJay** [FreeCodeCamp/FreeCodeCamp#11390]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by erictleung** [comment]
@gatewayJay thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). GitHub issues is not a place for coding help. Happy coding!
