### ISSUE TITLE
Video Updates - Outdated vimeo videos

### ISSUE THREAD

**Issue by mikemimik** [FreeCodeCamp/FreeCodeCamp#1139]
#### Waypoint: Meet Other Campers in your City
 - The corresponding video for this waypoint mentions Slack as a way to "hang out with other campers".

#### Waypoint: Get Help the Hacker Way with RSAP
 - The link in the video to the chat, directions the viewers attention to slack, rather than gitter

**Comment by benschenker** [comment]
Thanks @mikemimik,

It looks like this has been fixed as those waypoints no longer exist (they have been replaced with the instructions/gifs on the home page)
