### ISSUE TITLE
How could this work...?

### ISSUE THREAD

**Issue by ligun89** [FreeCodeCamp/FreeCodeCamp#11392]
function multiplyAll(arr) {
var product = 1;
// Only change code below this line
for (var i=0; i < arr.length; i++) {

for (var j=0; j < arr[i].length; j++) {
  product = (arr[i][j] * product);
}
}
// Only change code above this line
return product;
}

I thought understand how this logic works...

but, i can't understand how this command works... :'(

multiplyAll([[5,1],[0.2, 4, 0.5],[3, 9]]);)  ---->  54

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by raisedadead** [comment]
The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
