### ISSUE TITLE
Coded everything but then also it is not running.

### ISSUE THREAD

**Issue by arlworker** [FreeCodeCamp/FreeCodeCamp#11400]
Using from my mobile
Using Google browser
Here is my code...

``` html
<style>
  .red-text {
    color: red;
  }
  p{
    font-size:16px;
  }

</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by arlworker** [comment]
My code
<style>
  .red-text {
    color: red;
  }
  p{
    font-size:16px;
  }
 
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by raisedadead** [comment]
Hi this challenge is known to have issues when visiting from a mobile browser, with white spacing characters.

If you can delete your code an write it from scratch, it should probably work.
Copy pasting from some other place will also break the code on mobile devices.

Let us know if it works.

**Comment by Bouncey** [comment]
I'm going to try [this solution](http://stackoverflow.com/questions/1495822/replacing-nbsp-from-javascript-dom-text-node) out tonight to see if it removes `&nbsp;` from the campers code. 

@arlworker can you please copy and paste the address bar from this challenge in here and please. It holds your code from the challenge and will give me something to test on 👍

**Comment by Bouncey** [comment]
#7753 refers

**Comment by Eclipseparadox** [comment]
Code runs, browser is set to 100%. Will not pass the 100% browser check mark. How do i advance?

**Comment by systimotic** [comment]
@Bouncey That looks like a really good fix. This is quite a common issue, hopefully it works.
@Eclipseparadox If you're still having this issue, try removing the spaces. If you need coding help, please click the help button in the challenge.
