### ISSUE TITLE
Bonfire Seek and Destroy Bug???

### ISSUE THREAD

**Issue by Concretechris** [FreeCodeCamp/freecodecamp#1140]
Challenge http://www.freecodecamp.com/challenges/bonfire-seek-and-destroy has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Shouldn't the function include the array and two variables i.e. function destroyer(arr, x, y)????

**Comment by treece** [comment]
Hi @Concretechris ,

It looks like the author of this bonfire wanted to introduce you to the arguments object. So with that in mind, the function isn't really missing anything. Checkout arguments here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments

Thanks for submitting an issue. Don't hesitate to submit any other issues that you may find. Have fun coding :-)

**Comment by LumenTeun** [comment]
Thank you for the answer @treece.
@Concretechris, remember to close this issue.

**Comment by vancovver** [comment]
![screen shot 2015-08-04 at 6 26 54 pm](https://cloud.githubusercontent.com/assets/13059946/9076393/95437dde-3ad6-11e5-9369-7e32ee1386dd.jpg)
