### ISSUE TITLE
Java Objects

### ISSUE THREAD

**Issue by lionelpelap** [FreeCodeCamp/FreeCodeCamp#11408]
Challenge [Declare JavaScript Objects as Variables](https://www.freecodecamp.com/challenges/declare-javascript-objects-as-variables#?solution=%0Avar%20car%20%3D%20%7B%0A%20%20%22wheels%22%3A4%2C%0A%20%20%22engines%22%3A1%2C%0A%20%20%22seats%22%3A5%0A%7D%3B%0A%0Avar%20motorBike%20%3D%20%7B%0A%20%20%22wheels%22%3A4%2C%0A%20%20%22engines%22%3A1%2C%0A%20%20%22seats%22%3A5%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%7D%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var car = {
  "wheels":4,
  "engines":1,
  "seats":5
};

var motorBike = {
  "wheels":4,
  "engines":1,
  "seats":5

  // Only change code below this line.

};

```

**Comment by texas2010** [comment]
@lionelpelap, Do you have an issue with this challenge?
