### ISSUE TITLE
Console Logging makes function fail

### ISSUE THREAD

**Issue by Compsight** [FreeCodeCamp/FreeCodeCamp#11401]
Challenge [Sum All Primes](https://www.freecodecamp.com/challenges/sum-all-primes#?solution=%0Afunction%20sumPrimes(num)%20%7B%0A%20%20var%20i%20%3D%202%3B%0A%20%20var%20sum%20%3D%200%3B%0A%20%20%0A%20%20while%20(i%3C%3Dnum)%20%7B%0A%20%20%20%20var%20numOfDiv%20%3D%201%3B%0A%20%20%20%20%20%20%20console.log(%22i%3D%3A%22%2Ci)%3B%0A%2F%2F%20%20%20%20%20if%20(i%20%3D%3D%3D%202)%20%7B%0A%2F%2F%20%20%20%20%20%20%20sum%20%2B%3Di%3B%0A%2F%2F%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20while%20(numOfDiv%20%3C%3D%201)%20%7B%0A%20%20%20%20%20%20%20%20for%20(var%20x%20%3D%202%3B%20numOfDiv%20%3C%203%20%26%26%20x%20%3C%3D%20i%3B%20x%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20%20%20if%20(i%20%25%20x%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20numOfDiv%20%2B%2B%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20console.log(%22numOfDiv%20is%20%22%2CnumOfDiv%2C%22%20for%20loop%22)%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20if%20(numOfDiv%20%3D%3D%3D%202)%20%7B%0A%20%20%20%20%20%20%20%20%20%20sum%20%2B%3D%20i%3B%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20console.log(%22add%3A%22%2Ci)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%2F%2F%20%20%20%20%20%7D%0A%20%20%20%20i%2B%2B%3B%0A%20%20%7D%0A%20%20console.log(%22sum%3D%22%2Csum)%3B%0A%20%20num%20%3D%20sum%3B%0A%20%20return%20num%3B%0A%7D%0A%2F%2F%20(i%20%3E%205%20%26%26%20i%20%25%202%20!%3D%3D%200%20%26%26%20i%20%25%203%20!%3D%3D%200%20%26%26%20i%20%25%205%20!%3D%3D%200)%20%7B%0AsumPrimes(10)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function sumPrimes(num) {
  var i = 2;
  var sum = 0;
  
  while (i<=num) {
    var numOfDiv = 1;
       console.log("i=:",i);
//     if (i === 2) {
//       sum +=i;
//     } else {
      while (numOfDiv <= 1) {
        for (var x = 2; numOfDiv < 3 && x <= i; x++) {
          if (i % x === 0) {
            numOfDiv ++;
             console.log("numOfDiv is ",numOfDiv," for loop");
          }
        }
        if (numOfDiv === 2) {
          sum += i;    
          console.log("add:",i);
        }
      }
//     }
    i++;
  }
  console.log("sum=",sum);
  num = sum;
  return num;
}
// (i > 5 && i % 2 !== 0 && i % 3 !== 0 && i % 5 !== 0) {
sumPrimes(10);

```

When console logs on Line 8 and Line 17 are NOT commented out, the solution will fail.
Upon commenting these 2 lines out with "//" the test will pass.
Also, changing the string within Line 17 (e.g. "for loop" --> " for loop") will change the sum answer in the console from the console.log on Line 27.

**Comment by Bouncey** [comment]
@Compsight My guess is that your code plain overloads your browser and something steps in to terminate your code.

Your code passes on my machine, but I have over **_5000_** `console.log`'s in my console!!

The reason your code passes with the `consloe.log`'s commented out is because you are not eating up memory with the thousands up thousands of `console.log`'s.

I hope I have explained it well enough for you. Yes, 'console.log''s are an aid to development, but please be careful to not put them in long running loops :+1: 

Happy coding!

**Comment by Dayfiri** [comment]
@Compsight 
And it is not best practice as you can see on your example to do many loops inside another loop.
You have `while` inside another `while` and inside of it you have one more `for loop` and two `if`s. 
You see what I think ?

**Comment by Bouncey** [comment]
@Compsight Have these comments resolved your issue?

If not can you please provide more information?

**Comment by Bouncey** [comment]
Please re-open this issue if you are still having trouble

Happy Coding!

**Comment by Compsight** [comment]
I guess that will work to keep in mind.
There should be plenty of memory with 8GB RAM on my MacBook Pro.
