### ISSUE TITLE
Fix jsx typo in map header

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#11404]
[autocompleted](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/common/app/routes/challenges/components/map/Header.jsx#L100) here is misspelled and should be campelCase to conform with jsx property naming conventions.

This fixes a React warning in development.

autocompleted => autoComplete

**Comment by spot1000** [comment]
I wouldn't mind giving this a go as a first timer!

**Comment by BerkeleyTrue** [comment]
Sorry looks like there are already two PR's

**Comment by spot1000** [comment]
womp womp, oh well, I'll keep looking around. Thanks!

**Comment by BerkeleyTrue** [comment]
Looks like this issue is still open.

Please read the [Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) guidelines first. Then claim this issue. Any PR that does not conform to the guideline will be closed.

**Comment by Manish-Giri** [comment]
@BerkeleyTrue I'm not a first-timer, but I can take this up, since it's open, and no one seems to be on it.

**Comment by vinhhv** [comment]
I'll claim it as a first-timer, if it already hasn't been taking!

**Comment by BerkeleyTrue** [comment]
@vinhhv Please follow the [guide](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) to ensure speedy acceptance.
