### ISSUE TITLE
Specify How Fonts Should Degrade. Platform issue? Please help!

### ISSUE THREAD

**Issue by menlog** [FreeCodeCamp/FreeCodeCamp#11402]
#### Specify How Fonts Should Degrade

https://www.freecodecamp.com/challenges/specify-how-fonts-should-degrade
#### I'm Unable to proceed to the next step !!

After commenting out the call for Lobster font, all checks are green but when pressing submit the page keeps loading!

Tried a hard refresh, as well as logging out and deleting cache data from the browser in addition to confirming that the issues occurs on other browsers.  
#### I tried using the latest Chrome version, as well as doing a check on the latest firefox and IE browsers

Win 7
#### My Code
```
<!--
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
-->

<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>


<h2 class="red-text">CatPhotoApp</h2>


<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
 

```
#### Screenshot
![image](https://cloud.githubusercontent.com/assets/23100772/19780061/6deeffc4-9c8c-11e6-8387-e71b787657cd.png)

![image](https://cloud.githubusercontent.com/assets/23100772/19780065/741a489a-9c8c-11e6-9e26-a6b76b007c52.png)

![image](https://cloud.githubusercontent.com/assets/23100772/19780069/7b08dbf8-9c8c-11e6-8eb5-ed5580a6cae0.png)

**Comment by menlog** [comment]
The issue was solved by disabling addons.

**Comment by Looserof7** [comment]
Even, I disabled all my add-ons, but there doesn't seem to be any change.
Even I'm struggling from the same problem, please re-open this issue.
@menlog , @VarCI-bot 
![screenshot_20161031_065433](https://cloud.githubusercontent.com/assets/19215729/19841965/7112bc40-9f39-11e6-92b1-29bd71b306bd.png)

**Comment by menlog** [comment]
@Looserof7  As per your request, I have reopened this issue. 
Assuming that you tried a hard refresh, deleting browsing history and cache, try using firefox/IE. 
also , what kind of OS are you using? which version of firefox?
did you try to open it on chrome?

Finally, if you are using VPN, disable it.

**Comment by raisedadead** [comment]
@Looserof7 you could check that if the fonts are natively installed on your PC then you would still get the errors.

Let us know if still persists.

**Comment by Looserof7** [comment]
Sorry for the delay, I have disabled all add-ons and tried but it didn't
work for me.
I was using manjaro, firefox 49.02 rolling version.
Desktop Environment: Kde
I was using Ubuntu Mono as my default font in firefox and in my system.
Yes, I have installed Ubnutu fonts natively into my Operating System.

I did find where it went wrong,
I de-selected the checkbox,  allow any website to override font.

Since, websites can't override my font.

There could be warning to disable such type of activities,

or else some other way of finding whether user have done it right or wrong.

I 'm suggesting that because, I did spend nearly 2 hours on that one
question, asking several people for help and reading some books on html5,

After allowing sites to override my font, it went well.

Thank you...

**Comment by raisedadead** [comment]
@Looserof7 this is a common problem that has been addressed several times in the issue tracker, how ever I am not in favour of adding any link or hint as such.

Often these confuse people more. They are not relevant to the challenge and are mostly config issues of user's systems.

More importantly they can vary from a various types, like in your case a browser setting, or a installed font, or more.

Closing as resolved. Feel free to continue the discussion if you have any queries or alternate ideas.

Happy coding! 😃
