### ISSUE TITLE
challenge N60.

### ISSUE THREAD

**Issue by rocnogu** [FreeCodeCamp/FreeCodeCamp#11411]
Challenge [Responsively Style Radio Buttons](https://www.freecodecamp.com/challenges/responsively-style-radio-buttons#?solution=%20%20%0A%20%20%0A%20%20%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-primary%22%3E%3Ci%20class%3D%22fa%20fa-thumbs-up%22%3E%3C%2Fi%3E%20Like%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-info%22%3E%3Ci%20class%3D%22fa%20fa-info-circle%22%3E%3C%2Fi%3E%20Info%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-block%20btn-danger%22%3E%3Ci%20class%3D%22fa%20fa-trash%22%3E%3C%2Fi%3E%20Delete%3C%2Fbutton%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%0A%20%20%3C%2Fdiv%3E%0A%20%20%0A%20%20%0A%20%20) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Nest all of your radio buttons inside one div with the class row.
Nest each of your radio buttons inside its own div with the class col-xs-6.

My code:
```html
  
  
  
  <div class="row">
    
    <div class="col-xs-6">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    
    <div class="col-xs-6">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    
    <div class="col-xs-6">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
    
  </div>
  
  
  
```

i cant see do i missing something . i try to reset and do it again . i try the help chat. now im here .

**Comment by texas2010** [comment]
@rocnogu 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by Manish-Giri** [comment]
@rocnogu Your code is incorrect. You're nesting `button` elements, while you actually need to nest `radio` buttons - they are `input` elements of the `type` `radio`. 

Not just that, you seem to have deleted most of the code from your link, and the challenge won't pass without it. Reset and start over.

**Comment by texas2010** [comment]
@Manish-Giri, Remind you. this place is not for help people.  only report bug or typo on fcc site.  okay.

**Comment by Manish-Giri** [comment]
@texas2010 Excuse me? The person just said he was in the help chat and didn't get any help. What is the big deal in letting him know where the problem with his code is? You already closed the issue before even telling him how to proceed, so I don't see what you're having a problem with.

**Comment by rocnogu** [comment]
ok . ok . wait  a sec .
1  i have no idea what is difference between "button" and "radio button"
2 . WTF connection have with the whole text . the system delete part of the text all the time .AND it does not have a requirement" use the full code" . i read and write it literally  as should be . 
3 . if i write the code right, it is a bug . see "2" for more info and fix it .

@Manish-Giri . that actually help . i got back to see what exactly is the radio button . thanks for the hint !

**Comment by texas2010** [comment]
@Manish-Giri, because this issue is not for ask help. they have to use chat room or forum.
if you want to help someone. you have to use chat room or forum. okay.
GitHub Issues are for reporting bugs on the website only.

**Comment by rocnogu** [comment]
the people from the  FCC does not help at all  . i m looking for new better place to learn .
not helping to people is just an asshole thing . you are not obligated to do it . but you can .

**Comment by 61seconds** [comment]
Instead of this ` <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>`
try this
` <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up">Like</i> </button>`

**Comment by TurtleWolf** [comment]
@rocnogu, I think it is a matter of discipline.. this particular 'bug' is slightly intentional to make sure a student doesn't just copy paste their way to a certificate, but actually reads and comprehends what they are doing.. It's an ingenious form of social engineering, it's like watching a crack in the matrix, This thread is art!
