### ISSUE TITLE
Waypoint link error

### ISSUE THREAD

**Issue by mikemimik** [FreeCodeCamp/FreeCodeCamp#1141]
If you navigate to the page http://freecodecamp.com/map and look at the *Basic HTML5 and CSS* section, waypoint number 15. The url link is `http://www.freecodecamp.com/challenges/Waypoint:%20Import%20a%20Google%20Font` which is incorrect. The actual link is `http://www.freecodecamp.com/challenges/waypoint-import-a-google-font`. The page displays a 404 error notification.

**Comment by NatashaHaggard** [comment]
Wasn't able to replicate the bug, the link works for me.

**Comment by LumenTeun** [comment]
+1 @NatashaHaggard  I'm not getting a 404 error either.

All waypoint anchors seem to point towards a URL with spaces, and I've seen functions in the FCC codebase that turns challenges from undashed to dashed versions of themselves and vice versa, so I don't think this is an issue.

**Comment by benschenker** [comment]
Closing as stale, reopen if you see this issue still
