### ISSUE TITLE
My Code matches the example, yet I'm not getting a pass.

### ISSUE THREAD

**Issue by wlawler** [FreeCodeCamp/FreeCodeCamp#11416]
Challenge [Accessing Objects Properties with Bracket Notation](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-bracket-notation#?solution=%0A%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%20%22an%20entree%22%3A%20%22hamburger%22%2C%0A%20%20%22my%20side%22%3A%20%22veggies%22%2C%0A%20%20%22the%20drink%22%3A%20%22water%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0AtestObj%5B%22an%20entree%22%5D%3B%20%20%20%2F%2F%20Change%20this%20line%0AtestObj%5B%22the%20drink%22%5D%3B%20%20%20%20%2F%2F%20Change%20this%20line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var testObj = {
  "an entree": "hamburger",
  "my side": "veggies",
  "the drink": "water"
};

// Only change code below this line

testObj["an entree"];   // Change this line
testObj["the drink"];    // Change this line

```

**Comment by Bouncey** [comment]
@wlawler Please read the instructions and try again. If this does not help, try resetting the challenge, you might see something that will help you out. :+1: 

If you are still stuck, please try the `Help` button just under the `Run tests` button, or our [forum](forum.freecodecamp.com).

GitHub issues are for issues with freecodecamp as a service, not for help with your code.

Closing this issue as it is for code help

Happy coding :+1:
