### ISSUE TITLE
Core team status on user profiles

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#11418]
We plan to move archive our [core team Gitter chat room](https://gitter.im/freecodecamp/coreteam) and move our core team over to our new [contributor chat room](https://gitter.im/freecodecamp/contributors) - which is open to anyone who wants to contribute to our open source community through:
- open source codebase contributions
- YouTube videos
- Medium or Wiki articles
- Events through our Campsites
- curriculum development, and more

Instead of communicating core team status through presence in our core team room, core team members will instead have a special text on their Free Code Camp profile, sort of like this:
![](https://www.evernote.com/l/Ar-MltaI9b9GmIW3RFRRhxjV5jo7xophCvwB/image.png)

Core team membership will be on a year-by-year basis, so core team contributors who get busy and don't have time to contribute any more will automatically be recognized as past core team members, while ones who stay on will continue to accumulate annual core team distinctions.

Here is what we need to do:
- [ ] create an array attribute coreTeam on the User model, defaulting to []
- [ ] update the profile view to show the text "Core Team N" where N is the year for each year that a camper is on the core team. For example:

```
coreTeam: ["2015","2016"]
```

would show the text:
Core Team 2016
Core Team 2015

in reverse chronological order, below earned certificates.

Once this pull request has been accepted, I will manually go into the production database and set this status to true for core team members.

**Comment by atjonathan** [comment]
@QuincyLarson, would it not be better to use badges?

**Comment by ivantedja** [comment]
I think badge looks more beautiful. I'd like to work on this one. I'll use "text" for now, waiting for @QuincyLarson 's reply.
