### ISSUE TITLE
What is wrong with this code

### ISSUE THREAD

**Issue by arshaukat** [FreeCodeCamp/FreeCodeCamp#11427]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20blue%3B%7D%20CatPhotoApp%20%3C%2Fstyle%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {color: blue;} CatPhotoApp </style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Marmiz** [comment]
@arshaukat You have a syntax error inside your code.

In the specific you have `CatPhotoApp` inside your `<style>` sections.
That's not supposed to happen.

Try to follow the instructions more carefully next time.
For instance the instruction start with:

>At the top of your code, create a style element like this:
<style>
</style>

So after the first step your code should look like:
```
<style>
</style>

<h2 style="color: red">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

You can proceed from here :)

I also suggest you to ask in the [Help chat room](https://gitter.im/FreeCodeCamp/Help) next time you have some insecurities, before assuming there's a bug.

Happy coding 👍
