### ISSUE TITLE
Plz find errors in my code

### ISSUE THREAD

**Issue by ligun89** [FreeCodeCamp/FreeCodeCamp#11422]
function titleCase(str) {
  var temp;

  
  temp=str.split(' ');
  
  for(var i=0 ; i<temp.length ; i++)
    {
      temp[i][0].toUpperCase();
    }  
  return temp.join(' ');
}

titleCase("I'm a little tea pot");

I don't know why this return value doesn't change to "I'm A Little Tea Pot".

#### Challenge Name
Title Case a Sentence

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by erictleung** [comment]
@ligun89 thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
