### ISSUE TITLE
New certificates that include number of hours

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#11424]
One common request is for our certificates to feature the number of hours associated with completing them. So for the current certificates, this would be 400 hours, and for the new ones, it would be 200 hours.

@atjonathan did you end up creating these certificate templates yet? Or a way that dynamically generates them with a single view, based on their type?

The 6 new certificates will be:
- Responsive Web Design
- JavaScript Algorithms and Data Structures
- Front End Libraries
- Data Visualization (note that even though this shares a name with the old certificate, it will be a new 200 hour cert)
- APIs and Microservices
- Quality Assurance and Information Security

**Comment by atjonathan** [comment]
@QuincyLarson, they have to be manually created. Are these all 200 hour certs?

**Comment by QuincyLarson** [comment]
@atjonathan yes - all 6 new certs are 200 hour certs. We can use the same template for the old certs, but those will be 400 hour certs. Can you figure out a graceful way to show both?

**Comment by QuincyLarson** [comment]
@atjonathan yes - all 6 new certs are 200 hour certs. We can use the same template for the old certs, but those will be 400 hour certs. Can you figure out a graceful way to show both?
