### ISSUE TITLE
the .push method in Record Collection challenge doesn't seem to bring the desired result

### ISSUE THREAD

**Issue by akolybelnikov** [FreeCodeCamp/FreeCodeCamp#11426]
My function passes all other tests but repeatedly throws error on the same one, even after I have reset my code twice and emptied the cache. Here is my function code:
```
    function updateRecords(id, prop, value) {
      if (prop !== "tracks" && value !== "") {
        collection[id][prop] = value;
      }
      else if (prop === "tracks" && value !== "") {
        if (!collection.hasOwnProperty("tracks")) {
          collection[id][prop] = [];
        }
        collection[id][prop].push(value);
       }
      else {
        delete collection[id][prop];
      }
      return collection;
    }
```
and here is the error I've been getting:

![image](https://cloud.githubusercontent.com/assets/18685675/19802977/a846cf2e-9d06-11e6-9bd6-b852465d9971.png)

Could someone please test this? thanks.

**Comment by akolybelnikov** [comment]
the issue was with my code, apologies for the false bug

**Comment by Dayfiri** [comment]
When I enter:
`updateRecords(2468, "tracks", "Free")` in callback function, I don't get `"1999"` as an element of `tracks`. There is only 1 element and that is `"Free"`

**Comment by akolybelnikov** [comment]
Thank you for confirming the issue @Dayfiri , it's exactly the case with me too. The question is if that's a bug.

**Comment by Dayfiri** [comment]
@akolybelnikov I don't think it is a bug. It's just a problem in if/else statements because it makes difference which statement you give in a test at 1., 2. or 3. place for example. That matters a lot. Because code may be satisfied at 1. test and it won't go through other 2 or 3 tests that you made after. That becomes a problem in this kind of code.

**Comment by akolybelnikov** [comment]
thank you @Dayfiri . I'm not sure if I learned something from this challenge, but your code works.

**Comment by Dayfiri** [comment]
@akolybelnikov For more help come to [FCC help chat](https://gitter.im/FreeCodeCamp/Help). There is always people willing to help and explain the problems you might have. 
Cheers !

**Comment by akolybelnikov** [comment]
yes, thanks. apologies for starting the thread under bugs. i flasely believed this to be a bug.

**Comment by Dayfiri** [comment]
@akolybelnikov No problems. There are many cases like this on daily base. Thanks for trying to help anyway 👍

**Comment by roddrec23** [comment]
recgwyn@gmail.com

**Comment by roddrec23** [comment]
---------- Forwarded message ----------
