### ISSUE TITLE
Waypoint inconsistency in text

### ISSUE THREAD

**Issue by mikemimik** [FreeCodeCamp/FreeCodeCamp#1142]
### Waypoint: Make Dead Links using the Has Symbol
In every lesson up until now in the curriculum the anchor tags have been referred to as "`a` element". In this waypoint it's referred to as "`anchor` element" which grammatically doesn't make sense.

Either 
> Anchor Tag 

or

> `a` Element

Consistency is best for beginners.

**Comment by NatashaHaggard** [comment]
Not sure if this is a bug, in the basic-html5-and-css.json file, there are three instances where it refers to it as "Anchor Element":
Line 998:       "name": "Waypoint: Link to External Pages with Anchor Elements",
Line 1002:         "Create an <code>a</code> element, or \"anchor element\", that links to http://catphotoapp.com and has \"cat photos\" as its link text, or \"anchor text\".",
	Line 1061:       "name": "Waypoint: Wrap an Anchor Element within a Paragraph"

**Comment by LumenTeun** [comment]
Any input on what is preferred or recommended? I suppose "anchor tag" is easier to read/speak, but "`a` element" is easier to relate to the actual code.

**Comment by davemofosho** [comment]
I would say if you are talking specifically about something then use the name such as anchor if you talking generally about html say element.

**Comment by benschenker** [comment]
This has been fixed
