### ISSUE TITLE
Personality attribute isn't showing...

### ISSUE THREAD

**Issue by millennialtraveller** [FreeCodeCamp/FreeCodeCamp#11437]
#### Challenge Name

https://www.freecodecamp.com/challenges/create-a-set-of-checkboxes#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%3Cul%3E%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%3Col%3E%0A%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%3C%2Fol%3E%0A%3Cform%20fccfaa%3D%22%2Fsubmit-cat-photo%22%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Indoor%3C%2Flabel%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Outdoor%3C%2Flabel%3E%0A%20%20%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%20required%3E%0A%20%20%3Cbutton%20type%3D%22submit%22%3ESubmit%3C%2Fbutton%3E%0A%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%3C%2Flabel%3E%0A%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22name%3D%20%C2%A0%22personality%22%3Ecool%3C%2Flabel%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%0Aname%3D%22personality%22%3Ecool%3C%2Flabel%3E%0A%3C%2Fform%3E%0A

Create a set of checkboxes 

#### Issue Description

I am finding a lot of incomplete instructions in these challenges so far. When I follow the example exactly - nothing works and I always wind up having to do more research than necessary. Like now with the personality attributes not appearing...

#### Browser Information

Google chrome mobile 

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
<label><input type="checkbox" name="personality"></label>
 <label><input type="checkbox"name=  "personality"></label>
  <label><input type="checkbox"
name="personality"></label>
</form>

 
 
```

**Comment by millennialtraveller** [comment]
There is also the opening form tag as well above the code. Didn't write that part...

**Comment by erictleung** [comment]
@millennialtraveller sorry to hear you're running into issues. Your code is correct. However, sometimes mobile browsers inject some invisible characters that mess up our tests. If I delete what looks to be two "spaces" in your second input checkbox, the challenge passes. Probably related to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7753.

I guess all I can suggest is to finish the challenge on a desktop browser if possible.

**Comment by systimotic** [comment]
Hi @millennialtraveller! This is a really pesky issue. As @erictleung suspected, this issue is the same as #7753. The second space of the two he suggested to delete is a non-breaking space, which messes up the tests. I believe @Bouncey was trying to fix for this. Let's hope he can make it work, because this is a really annoying issue. 
I'm closing this as duplicate for now. If removing those spaces between `name=` and `"personality"` in the second input doesn't work for you, please let us know! Happy coding!

**Comment by millennialtraveller** [comment]
Thanks @erictleung and @systimotic! After I corrected the spacing a rewrote the code, it finally went through. I am finding the spacing is an issue on many of the challenges as well. 

Even now, with the Negative Margin Element challenge it happens... I added the -15px to the CSS code and it wont process!

**Comment by systimotic** [comment]
So sorry about that @millennialtraveller. Let's hope we can fix this issue soon! As Eric suggested previously, you might have to hop onto a desktop for now in order to finish it. 😞
