### ISSUE TITLE
Code passes but not correct output

### ISSUE THREAD

**Issue by rlegare** [FreeCodeCamp/FreeCodeCamp#11434]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22FirstLine%5Cn%5C%5CSecondLine%5C%5C%5CrThirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line



```

![image](https://cloud.githubusercontent.com/assets/19785034/19824138/db3b39a4-9d21-11e6-9f3a-2d2163678d9b.png)

**Comment by Dayfiri** [comment]
@rlegare 
I'm not shure what might be your issue but in my case, your code works.
![screenshot from 2016-10-29 01-02-48](https://cloud.githubusercontent.com/assets/16082563/19824900/a1188c2a-9d73-11e6-8f9c-be43e580e5b4.png)

**Comment by KonSal** [comment]
@rlegare Chrome 54.0 and your code is working for me as well.

**Comment by erictleung** [comment]
@rlegare I think that [this PR](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11206) fixes your issue if your issue is what @KonSal points out it to be. Closing this issue as it appears to be resolved when the updates are pushed live. If this is not what you were referring to, feel free to reopen this issue. Happy coding!

**Comment by vikasnegi13** [comment]
Thanks rlegare for pointing this. 
I am doing this exercise and can confirm it still exists.
