### ISSUE TITLE
keeps saying h2 element is not red

### ISSUE THREAD

**Issue by sarahgobind** [FreeCodeCamp/FreeCodeCamp#11435]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20h2%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  h2 .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by KonSal** [comment]
When declaring styles in CSS, you have to either use an HTML tag, like the `h2` element, or a class, like `.red-text`.

So, by changing your CSS to:
```
<style>
  .red-text {
    color: red;
  {
</style>
```

will make you pass the challenge.

**Comment by erictleung** [comment]
@sarahgobind thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by texas2010** [comment]
@KonSal 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by KonSal** [comment]
@texas2010 Alright! Sorry for that. I guess if I ever bump into an Issue like that again, will do just like what @erictleung said.

**Comment by texas2010** [comment]
@KonSal, all good.

**Comment by hydrocronic** [comment]
Same issue but the chat room tells me its my browser.
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">
CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
