### ISSUE TITLE
IS THERE ANY FAULT WITH MY ORDER OF CODES

### ISSUE THREAD

**Issue by oburay** [FreeCodeCamp/FreeCodeCamp#11436]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%3C!%0A%0A%3C!Hello%20World--%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3C!Hello%20Paragraph--%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!

<!Hello World-->

<h2>CatPhotoApp</h2>

<!Hello Paragraph-->

```

**Comment by texas2010** [comment]
@oburay 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
