### ISSUE TITLE
Hi.  I created a freeCodeCamp about 6 months ago and decided to revisit my account only to discover my account appears to have been deleted?  Is there a time limit to holding an account?  Its been maybe 3 months since I had last signed on.

### ISSUE THREAD

**Issue by KerryRuddock** [FreeCodeCamp/FreeCodeCamp#11449]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by systimotic** [comment]
Hi @KerryRuddock. That's no good. I personally don't know about limits or deleted accounts. I think your best bet is to email support at team@freecodecamp.com They have the tools to help you out with this.
I don't believe there's anything we can do about this on GitHub, unless support finds that there was indeed an error in the application. For that reason, I'm closing this issue.
Hopefully this will be resolved. Happy coding!
