### ISSUE TITLE
Title of the webpage not changing

### ISSUE THREAD

**Issue by computerluca** [FreeCodeCamp/FreeCodeCamp#11442]
In computer Basics series when you complete a quiz correctly it bring you to the correct page but the title of web page (displaying on the tab of the browser) doesn't change.

**Comment by Bouncey** [comment]
Confirmed for the production site.

Resolved in `staging`

@computerluca Thank you for pointing out this issue. It has been resolved in an upcoming release for freeCodeCamp though. 

Many thanks & please keep contributing :+1:
