### ISSUE TITLE
Entering Username on Sign up before Sign in

### ISSUE THREAD

**Issue by Powiee** [FreeCodeCamp/FreeCodeCamp#1144]
On the Signin page (http://www.freecodecamp.com/signin)
Click on sign up using your email address then enter a username
Go back to Signin page
Try sign in with existing account
It would redirect you to http://www.freecodecamp.com/api/checkUniqueUsername/someusername

**Comment by QuincyLarson** [comment]
I was unable to reproduce this issue using the steps you gave me. Just to confirm:
1) I should create an account
2) I should sign out
3) I should sign back in
Is this correct? 
Thank you for your patience and help!

**Comment by Powiee** [comment]
1) Attempt to create an account (using email) with just the username entered (stop there)
2) Go to sign in page for email address
3) Sign in with existing account.

**Comment by Powiee** [comment]
This issue happens when you enter only the email on the account creation page before heading to sign in page too.

**Comment by BerkeleyTrue** [comment]
Signup should be working now.
