### ISSUE TITLE
need more lesson

### ISSUE THREAD

**Issue by dreamdone** [FreeCodeCamp/FreeCodeCamp#11447]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by systimotic** [comment]
Hi @dreamdone! Can you please add more info to your issue? I'm afraid we can't help if we don't know what's wrong 😀
If you're looking for coding help, please click the help button on the issue.

**Comment by roddrec23** [comment]
recgwyn@gmail.com
