### ISSUE TITLE
yahoo my account

### ISSUE THREAD

**Issue by justintre** [FreeCodeCamp/FreeCodeCamp#11448]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by systimotic** [comment]
Hey @justintre! Can you elaborate on your issue please? Without more information, I'm afraid we can't help you 😅 
If you're looking for coding help, please click the "Help" button in the challenge.
