### ISSUE TITLE
Bonfire: Convert HTML Entities

### ISSUE THREAD

**Issue by miatribe** [FreeCodeCamp/freecodecamp#1145]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The 2nd test assert.strictEqual('<>', '<>', 'should escape characters'); does not even call my convert method.

**Comment by QuincyLarson** [comment]
Thank you for your help! We've now fixed this in production!

**Comment by dsifford** [comment]
I'm still getting an error with this:

```javascript
function convert(str) {
  str = str
    .replace(/>/g, "&gt;")
    .replace(/</g, "&lt;")
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
  return str;
}
convert('Dolce & Gabbana');
```

**Comment by magicLamp76** [comment]
Yes. I get the same errors for this code:

function convert(str) {
  return str.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("'", "&apos;").replace('"', "&quot;");
}
