### ISSUE TITLE
codepen issues with https

### ISSUE THREAD

**Issue by wbrennan899** [FreeCodeCamp/FreeCodeCamp#11450]
Challenge [Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

If you are using a secure connection (https) to the codepen.io page, API calls to open weather will not work. Really should have this on the assignment page. I spent 5+ hours to realize there was nothing wrong with my code. You need to delete the 's' for it to work.

https://codepen.io/... --> http://codepen.io/...

https://www.reddit.com/r/FreeCodeCamp/comments/413p2u/issues_making_api_calls_with_codepen/

**Comment by Dayfiri** [comment]
Yep, same thing happened to me when I worked on weather API.

**Comment by erictleung** [comment]
@wbrennan899 thanks for the issue. This appears to be duplicates of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9079 and https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8988. Please continue the discussion over on those issues. Closing this issue in favor of those. Happy coding!
