### ISSUE TITLE
I support that there is a bug in "Return Largest Numbers in Arrays"

### ISSUE THREAD

**Issue by seiferthan** [FreeCodeCamp/FreeCodeCamp#11455]
I tried to solve this quiz, and my code definitely works while I put any kind of arrays in the function **largestOfFour**. However, the website doesn't let me pass. Would you please tell me where is wrong with my code? Thank you so much.

Challenge [Return Largest Numbers in Arrays](https://www.freecodecamp.com/challenges/return-largest-numbers-in-arrays#?solution=var%20sortNum%20%3D%20%5B%5D%3B%0A%0Avar%20largestNumArray%20%3D%20%5B%5D%3B%0A%0Afunction%20largestOfFour(arr)%20%7B%0A%09%0A%09%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%20%2B%2B)%0A%7B%0A%09%0A%09sortNum%5Bi%5D%20%3D%20arr%5Bi%5D.sort(function(a%2C%20b)%7Breturn%20a%20-%20b%3B%7D)%3B%0A%09%0A%09largestNumArray.push(sortNum%5Bi%5D%5BsortNum%5Bi%5D.length-1%5D)%3B%0A%0A%7D%0A%0Areturn%20largestNumArray%3B%0A%0A%09%0A%7D%0A%0AlargestOfFour(%5B%5B4%2C%209%2C%201%2C%203%5D%2C%20%5B13%2C%2035%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2097%2C%2039%5D%2C%20%5B1000000%2C%201001%2C%20857%2C%201%5D%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var sortNum = [];

var largestNumArray = [];

function largestOfFour(arr) {
	
	
  for (var i = 0; i < arr.length; i ++)
{
	
	sortNum[i] = arr[i].sort(function(a, b){return a - b;});
	
	largestNumArray.push(sortNum[i][sortNum[i].length-1]);

}

return largestNumArray;

	
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);
```

**Comment by erictleung** [comment]
@seiferthan our tests run your code sequentially after each other. So global variables are a no-no. Put your variable declarations within your code and your code will pass. Happy coding!

**Comment by syedbaji** [comment]
hi
