### ISSUE TITLE
stuck at "Record Collection"

### ISSUE THREAD

**Issue by BahaaZidan** [FreeCodeCamp/FreeCodeCamp#11459]
#### Issue Description

it's two days now that ive been tweaking with this challenge but i can't seem to find a correct solution .. ive googled but the answers seem rather outdated and missing a requirement in the challenge which is (If prop is "tracks" but the album doesn't have a "tracks" property, create an empty array before adding the new value to the album's corresponding property.) 
i think that i'm misunderstanding the issue but ive been working on it for two days now so please help me or at least give me a hint of where is my mistake.

#### Browser Information

* Browser Name, Version: chromium, 53.0.2785
* Operating System: ubuntu 16.04
* Mobile, Desktop, or Tablet: desktop

#### Your Code

```js

// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  if (prop != "tracks" && value !== "") {
    collection[id][prop] = value; 
  } else if (prop == "tracks" && collection[id][prop] === undefined) {
    collection[id][prop] = [];
    collection[id][prop] = value;
  }else if (prop == "tracks" && value !== "") {
    collection[id][prop].push(value);
  } else if (value === "") {
    delete collection[id][prop];
  }

  return collection;
}

// Alter values below to test your code
updateRecords(5439, "tracks", "Take a Chance on Me");


 
 
 
```
#### Screenshot

![screenshot from 2016-10-30](https://cloud.githubusercontent.com/assets/22656046/19835749/bec28bde-9e97-11e6-8ce6-ec9a90fc0d36.png)

**Comment by BahaaZidan** [comment]
i think there's some issue with the challenge itself

**Comment by systimotic** [comment]
Hey @BahaaZidan! Thank you for the detailed report. As VarCI-bot reported, the issue tracker is only for bugs. You can use the "Help" button in the challenge for coding help. For this challenge, it will take you to the HelpJavascript chatroom. Don't worry, you're really close. This isn't an issue with the challenge itself, there's a small issue in your code.
Happy coding!

**Comment by AndreiLuca99** [comment]
I'm also suck in that problem!!!

**Comment by systimotic** [comment]
Hi @AndreiLuca99! As I said in my comment above, please use the "help" button to get help 🙂 
I know for a fact that Bahaa got things working, and that his issue was an issue in his code, not with the challenge.
Good luck, and happy coding!
