### ISSUE TITLE
Use AST traversal for challenge tests involving javascript

### ISSUE THREAD

**Issue by sammoorhouse** [FreeCodeCamp/FreeCodeCamp#11456]
#### Challenge Name

e.g. [Comparisons with the logical AND operator](https://www.freecodecamp.com/challenges/comparisons-with-the-logical-and-operator)
#### Issue Description

Some challenge tests rely on Regular Expressions to make assertions about client-submitted code.

For example, in basic-javascript.json:3389 - 

`"assert(code.match(/if/g).length === 1, 'message: You should only have one <code>if</code> statement');",`

This will match the characters "if" anywhere in the code - in single and multiline comments, strings,  variable names etc. 

Instead of using Regular Expressions, we should instead parse the Javascript using tools like [Esprima](http://esprima.org/) and [Estraverse](https://github.com/estools/estraverse).

**Comment by sammoorhouse** [comment]
@QuincyLarson Could you take a glance at this checkin please?

https://github.com/sammoorhouse/FreeCodeCamp/commit/d91245b3e0e1ede73bcfd320433ba12a389cb535

I don't want to issue a PR yet because linting, but also because I need a better way to get at the actual code submitted by the user (https://github.com/sammoorhouse/FreeCodeCamp/commit/d91245b3e0e1ede73bcfd320433ba12a389cb535#diff-5bd2251576ea80e2350aa0736557c907R43). In client/frame-runner.js it looks like I only have access to the modified code inside a \<script\> tag, rather than the javascript. Any ideas?

As for speed, it turns out that esprima and estraverse are already bundled because they're dependencies of CodeMirror. If you're concerned about parsing I can add a switch to the challenge json and selectively parse for those tests that need it.

**Comment by Bouncey** [comment]
@sammoorhouse this looks really promising!

The campers code can be got to [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/sagas/execute-challenge-saga.js#L106) also, it is held at `file.contents`.

**Comment by QuincyLarson** [comment]
@sammoorhouse OK - @BerkeleyTrue has a much deeper understanding of how our test runner is currently implemented. He's definitely the best person to look at this. Can you create a WIP PR so @BerkeleyTrue can check out your code and give you feedback?

**Comment by BerkeleyTrue** [comment]
Yes, this is planned but I don't want to introduce more tech while we are transitioning to the new site.

**Comment by sammoorhouse** [comment]
@BerkeleyTrue do you want me to hold off? Willing to help on something new in any case.

**Comment by BerkeleyTrue** [comment]
Yes, this isn't something we are going to do any time soon.

**Comment by QuincyLarson** [comment]
@sammoorhouse yes - we could use help with expanding our curriculum, if this is something that would interest you. Specifically, we could use help designing our last few ES6 challenges: https://github.com/FreeCodeCamp/CurriculumExpansion/issues/34

**Comment by sammoorhouse** [comment]
Right! I'll close this and take a look at the curriculum. Cheers :)
