### ISSUE TITLE
Cannot search for asterisk

### ISSUE THREAD

**Issue by Kwpolska** [FreeCodeCamp/FreeCodeCamp#11466]
> Challenges required for certifications are marked with a *

The search field does not accept `*` so I can’t get a list of mandatory challenges.

**Comment by erictleung** [comment]
@Kwpolska thanks for the issue. The asterisk is more of a marker (i.e. "..are marked with..") rather than part of the challenge name itself.

However, it *might* be worth it to toggle on only the required challenges. But if you scroll through the challenge map, the bottom half is where the required challenges generally are.

cc/ @FreeCodeCamp/moderators

**Comment by systimotic** [comment]
I could see that it would be very nice to be able to see all of the required challenges. I'm not sure whether this would be easy to integrate into the UI though. As it's not so much about required challenges, but moreso about required blocks, I think this could be solved best if we saved which blocks are opened and which are closed. I'm not sure whether @Kwpolska agrees, and I also don't know whether this has been discussed before, but I personally would love to have a feature like that. As a user that doesn't do every challenge, this would make my life a lot easier.

**Comment by Bouncey** [comment]
it could be implemented through react with some tweaking to the search filter, or a toggle like @erictleung suggested.

At the minute though, the only required challenges are the three algorithm blocks and the projects.

**Comment by QuincyLarson** [comment]
@Bouncey let's hold off on making any changes to this since we're about to completely redesign the map anyway with the redesign. 

@Kwpolska thank you for opening this issue. I am closing it as this may not even be an issue after our redesign.
