### ISSUE TITLE
CDN all the things

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#11461]
We would like to see if it is possible to move the bower dependencies to either a CDN or npm, where appropriate.

**Comment by petrgazarov** [comment]
I would like to work on this 🚀 
From a brief look, all dependencies required through `bower`, are also available on `npm`. I'm going to attempt to transfer those to `npm`.

**Comment by Bouncey** [comment]
@petrgazarov Can you add CDN's for the likes of codemirror and fontawesome?

**Comment by petrgazarov** [comment]
@Bouncey pushed PR.

**Comment by BerkeleyTrue** [comment]
@Bouncey We do not need to move everything to a CDN.

**Comment by dhcodes** [comment]
Closing as resolved?
