### ISSUE TITLE
Last div

### ISSUE THREAD

**Issue by pjayfrank** [FreeCodeCamp/freecodecamp#1146]
Challenge http://www.freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I think I wrapped the input and submit parts of my code correctly because they are lined up but the program doesn't recognize it and g
![capture 1](https://cloud.githubusercontent.com/assets/11798399/8397103/0c661dec-1d8e-11e5-8d01-c2a482558f6d.PNG)
ive me credit for it.

**Comment by terakilobyte** [comment]
You've done the steps out of order and wrapped your submit button with col-xs-7 and your text input area with col-xs-5

**Comment by pjayfrank** [comment]
thanks for showing me my error.

On 6/28/2015 2:10 PM, Nathan wrote:
>
> Closed #1146 <https://github.com/FreeCodeCamp/freecodecamp/issues/1146>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/FreeCodeCamp/freecodecamp/issues/1146#event-342355189>.
>

-- 
Paul J. Frank
79 Oak Street
Foxboro, MA 02035
pjfrank@masshomefinders.com
508-942-8555



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
