### ISSUE TITLE
Read-Search-Ask links broken all over the place

### ISSUE THREAD

**Issue by Kwpolska** [freeCodeCamp/freeCodeCamp#11465]
#### Challenge Name

any algorithm challenge, eg. Roman Numeral Converter
#### Issue Description

> Remember to use [Read-Search-Ask](https://github.com/FreeCodeCamp/freecodecamp/wiki/FreeCodeCamp-Get-Help) if you get stuck. Try to pair program. Write your own code.

_Read-Search-Ask_ points to a Wiki page, and it looks like your Wiki does not exist anymore. Thus, users are sent to your GitHub page without any help.

**Comment by Bouncey** [comment]
@Kwpolska Thanks for the issue, VarCI got excited because it picked up on some keywords in your post that could indicate a code help request.

We need to change this link (which links to a wiki that isn't there anymore) to the forum with [this link](http://forum.freecodecamp.com/t/how-to-get-help-when-you-are-stuck/19514)

Many thanks and Happy Coding! :+1:

**Comment by alanbares** [comment]
I'll work on this.

**Comment by raisedadead** [comment]
@BerkeleyTrue this is weird the master branch has the links updated:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/master/seed/challenges/01-front-end-development-certification/basic-bonfires.json#L275

But the challenge in production doesn't reflect the same:
https://www.freecodecamp.com/challenges/title-case-a-sentence

Could you have a look?

**Comment by Bouncey** [comment]
I bugs that are fixed in staging are still reoccurring in production. Is it possible to have a partial release for the seed?

**Comment by Manish-Giri** [comment]
Speaking about broken links, I'd also like to add that the [link](http://forum.freecodecamp.com/clicks/track?url=https%3A%2F%2Fgithub.com%2Ffreecodecamp%2Ffreecodecamp%2Fwiki%2FFreeCodeCamp-Disable-Code-Autorun&post_id=32480&topic_id=19550)  mentioned in the "Recovering Unresponsive Code" section in the [forum](http://forum.freecodecamp.com/t/free-code-camp-infinite-loop-protection/19550), now just redirects to the FCC repo.

Not sure if this is already a known issue.

**Comment by raisedadead** [comment]
@Manish-Giri thanks for confirming

**Comment by QuincyLarson** [comment]
Quick note - I have temporarily turned the GitHub wiki back on until we can update these. 

Depending on how long it will be before we push staging to production, it may not be worth the effort of tracking these down and updating them, since they are already fixed on staging, as @Bouncey and @raisedadead pointed out.

**Comment by systimotic** [comment]
What should our next step be in this?
Can this be closed as it is fixed in staging and currently also working in production?

**Comment by raisedadead** [comment]
nope we are keeping this blocked for releasing staging. keeping the issue open until then.

**Comment by QuincyLarson** [comment]
This should be resolved. I've completely switched off the GitHub wiki.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (120/100 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60354 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dnx7E-0004ef-KA
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:20:52 -0400
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:46189 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1dnx6x-00024L-3E
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:20:35 -0400
Date: Fri, 01 Sep 2017 18:20:29 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1504315229;
	bh=ujOOAEAYbeDGGHZnJsb+GUlzK9Iwh2BMXmjJ/ngHPfY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=KpUED3TeNb0XnRvrxGPbuq2jnRlO2gfWiE0MRtF/F2sGi+/qukN1w07cZRoe/DUui
	 AT+XwZ0R78n+gj7swBgL5+v0LBQfHg5zAwZ8e5wmyW1vi9Bn2WZb7VuQAVWSYxo8z0
	 FYlIQvJhlThBCexazST8Cqs7pHQ7MXqrjIF/0PMw=
