### ISSUE TITLE
Progress gone after clicking activation link twice

### ISSUE THREAD

**Issue by RichStone** [freeCodeCamp/freeCodeCamp#11462]
When I mistakenly clicked on the activation link a second time, my progress in Maps menu was gone (basically all the steps from the Join The Community Challenge).

**Comment by erictleung** [comment]
@RichStone thanks for the issue. Can you be more specific on where this activation link shows up? It isn't clear to me which button you're referring to. I'm assuming that this button is somewhere within the "Join the Community" part.

**Comment by RichStone** [comment]
aah, sorry, I meant the activation link from the registration mail I got from you.


________________________________
Von: Eric Leung <notifications@github.com>
Gesendet: Sonntag, 30. Oktober 2016 18:32
An: FreeCodeCamp/FreeCodeCamp
Cc: Rich Stone; Mention
Betreff: Re: [FreeCodeCamp/FreeCodeCamp] Progress gone after clicking activation link twice (#11462)


@RichStone<https://github.com/RichStone> thanks for the issue. Can you be more specific on where this activation link shows up? It isn't clear to me which button you're referring to. I'm assuming that this button is somewhere within the "Join the Community" part.

-

**Comment by raisedadead** [comment]
Has anyone been able to reproduce this? @RichStone could you give us the exact steps?
/cc @FreeCodeCamp/moderators

**Comment by RichStone** [comment]
1. register
2. do some exercises (e.g. finish Join the Free Code Camp Community challenge)
3. go to your email account and click the activation link from your registration mail
-> all progress lost (finished challenges are no longer marked as finished; points gone)

**Comment by raisedadead** [comment]
thanks @RichStone ! looking into it.
