### ISSUE TITLE
Global vs Local Scope in Functions - It should be working

### ISSUE THREAD

**Issue by ludobourgoin** [FreeCodeCamp/FreeCodeCamp#11460]
Challenge [Global vs Local Scope in Functions](https://www.freecodecamp.com/challenges/global-vs-local-scope-in-functions#?solution=%0A%2F%2F%20Setup%0Avar%20outerWear%20%3D%20%22T-Shirt%22%3B%0A%0Afunction%20myOutfit()%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20outerWear%20%3D%20%22Sweater%22%3B%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20outerWear%3B%0A%7D%0A%0AmyOutfit()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var outerWear = "T-Shirt";

function myOutfit() {
  // Only change code below this line
  var outerWear = "Sweater";
  
  
  // Only change code above this line
  return outerWear;
}

myOutfit();

```

<img width="1010" alt="capture d ecran 2016-10-30 a 14 16 32" src="https://cloud.githubusercontent.com/assets/1445404/19836789/aa366c76-9eab-11e6-8ea4-cd52fb46d84b.png">

**Comment by servika** [comment]
As i see in code we have "Sweater" ( with uppercase first letter ) and on check "sweater" with lower case.

**Comment by ludobourgoin** [comment]
Oh God. Thanks for pointing this out to me. This was ridiculous 🤕

**Comment by Jellie2625** [comment]
// Setup
var outerWear = "T-Shirt";

function myOutfit() {
  // Only change code below this line

  var outerWear = "sweater";

  // Only change code above this line
  return outerWear;
}
 TRY THIS ONE :)

**Comment by tokasravi9000** [comment]
HERE BELOW IS THE SOLUTION

// Setup
var outerWear = "T-Shirt";

function myOutfit() {
  // Only change code below this line
  var myOutfit = "sweater";
  var outerWear = myOutfit;
  
  // Only change code above this line
  return outerWear;
}

myOutfit();

**Comment by texas2010** [comment]
@tokasravi9000 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by ramamrajdev** [comment]
we have to declare the local variable with name outerWear, so it can be done....
![screenshot 611](https://user-images.githubusercontent.com/29159645/27000649-a8e8c066-4dd4-11e7-85e1-32d5dc9cc833.png)

**Comment by LogicBlows** [comment]
function myOutfit() {
  // Only change code below this line
  
  var outerWear = "sweater";  //outWear not outwear;
  
  // Only change code above this line
  return outerWear;
}
