### ISSUE TITLE
Possible  typo

### ISSUE THREAD

**Issue by xodus899** [FreeCodeCamp/FreeCodeCamp#11471]
Challenge [Invert Regular Expression Matches with JavaScript](https://www.freecodecamp.com/challenges/invert-regular-expression-matches-with-javascript#?solution=%0A%2F%2F%20Setup%0Avar%20testString%20%3D%20%22How%20many%20non-space%20characters%20are%20there%20in%20this%20sentence%3F%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20expression%20%3D%20%2F.%2B%2Fg%3B%20%20%2F%2F%20Change%20this%20line%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%2F%2F%20This%20code%20counts%20the%20matches%20of%20expression%20in%20testString%0Avar%20nonSpaceCount%20%3D%20testString.match%28expression%29.length%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

``` javascript

// Setup
var testString = "How many non-space characters are there in this sentence?";

// Only change code below this line.

var expression = /.+/g;  // Change this line

// Only change code above this line

// This code counts the matches of expression in testString
var nonSpaceCount = testString.match(expression).length;

```

In this challenge you are give the code. With var expression the + symbol should be removed so someone new doesnt try to submit /\S+/g; vs /\S+\g;

**Comment by erictleung** [comment]
@xodus899 thanks for the issue. I can see the concern of incorrectly submitting `/\S+\g` but I'm not sure how that is related to the plus sign `+` being there. Can you elaborate?

Overall, I don't think that plus sign is too much of a concern. The instructions are pretty clear.

> Use `/\S/g` to count the number of non-whitespace characters in `testString`.

Additionally, the new curriculum expansion will have an entire section dedicated to regular expressions.

**Comment by Bouncey** [comment]
I cannot see how removing the `+` will stop an inadvertent `/\S+\g` submission.

The camper must make an attempt to debug the code for themselves, I would suggest it is a huge part of the learning process. 

If there was a submission of `/\S+\g` and the camper correctly found that the regExp was not constructed properly, I would guess the camper would have greater success using regExps next time.

Closing as, in my opinion, this is not an issue.

I would welcome the issue reopening with more information on the issue
