### ISSUE TITLE
Question about challenge: Label Bootstrap Buttons.

### ISSUE THREAD

**Issue by zhouxiang19910319** [freeCodeCamp/freeCodeCamp#11477]
#### Challenge Name

Label Bootstrap Buttons.
#### Issue Description

Here are my codes for the challenge. My question is this: why do we need to label the bootstrap buttons? I thought we already id'ed them? Is using span the correct way/only way to do it??? 

#### Browser Information

* Browser Name, Version: Chrome. Latest version.
* Operating System: OS X.
* Mobile, Desktop, or Tablet: Macbook pro.

#### Your Code

```js
 

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1"><span class="label">#target1</span></button>
        <button class="btn btn-default target" id="target2"><span class="label">#target2</span></button>
        <button class="btn btn-default target" id="target3"><span class="label">#target3</span></button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4"><span class="label">#target4</span></button>
          <button class="btn btn-default target" id="target5"><span class="label">#target5</span></button>
        <button class="btn btn-default target" id="target6"><span class="label">#target6</span></button>
      </div>
    </div>
  </div>
</div>

 
 
```

**Comment by raisedadead** [comment]
Hey @zhouxiang19910319 labels are text that you will want to add to the button elements, which will be visible on the buttons on the web page:

`<button class="btn btn-default target" id="target6">`**#target 6**`</button>`

will look something like the below on a webpage:

<kbd>#target 6</kbd>

The bold part in the code above is known as a label.

I understand the confusion you would have felt when going thru the challenge, this may need additional clarification.

/cc @FreeCodeCamp/moderators This challenge assumes that a camper knows the meaning of labels and has completed the previous challenge (where also there is no clarity).

Some might assume that labels are attributes like id's are in the previous challenges, we should probably refactor the challenges to reflect the correct meaning.

**Comment by zhouxiang19910319** [comment]
@raisedadead Hey I just found it out by myself when I was doing other challenges inside jQuery sections. Thank you for the reply though. More methodical and explanatory than the note I just wrote! haha.  XD Thanks!!! great help!!!

**Comment by raisedadead** [comment]
@zhouxiang19910319 the challenges perhaps need the clarification, please do not close the issue. 😅

**Comment by raisedadead** [comment]
Yeah but even on the wells challenge it's not defined what a "label" is. 

> Some might assume that labels are attributes like id's

hence maybe we should add some clarification to both/all affected challenges.

**Comment by hallaathrad** [comment]
While I may be wrong, a good way to explain it could be by introducing the labels themselves.
We can explain that a form element (e.g. input field) by itself has no way to show what sort of information it expects from the user. A label is meant to help you know you need to type your name.

**Comment by raisedadead** [comment]
I agree. I surely was inclined towards an interim challenge as well.

**Comment by QuincyLarson** [comment]
@raisedadead Are you still interested in creating this interim challenge?
