### ISSUE TITLE
Manage Packages with npm- Unclear instructions

### ISSUE THREAD

**Issue by TheGr8Lemmoncawl** [FreeCodeCamp/FreeCodeCamp#11481]
#### Challenge Name

https://www.freecodecamp.com/challenges/manage-packages-with-npm

#### Issue Description

After running how-to-npm and selecting option 7, 'package niceties' I am given the following instructions:

So, we've created a package.json file, but it's missing a few things
that people usually expect.  If you type `npm install`, you'll see
something like this:

    npm WARN package.json project1@1.0.0 No description
    npm WARN package.json project1@1.0.0 No repository field.
    npm WARN package.json project1@1.0.0 No README data

Before we can share this work of art with the world, we need to make
it a bit more polished so that people know how to use it.

First, create a README.md file, with a bit of words in it._---- There is already a file by this name. Do we create a duplicate(this isn't allowed without deleting or renaming the existing file) or edit this file?_

Then, add a "repository" field in your package.json file, with a url
where people can access the code.---- _Where and how do I add the "repository" field? I have no prior education or training in backend development, so I don't even know where to begin. Also, what URL would we be using? This information is needed to complete the challenge, but it not included._

#### Browser Information

C9 workspace

**Comment by Dayfiri** [comment]
This exercise would be much easier if you searched google for npm install and do it on your local machine. Something as [this](https://docs.npmjs.com/cli/install).

**Comment by dhcodes** [comment]
@TheGr8Lemmoncawl as @Dayfiri suggests, please consider asking for help in the [Gitter chat room for Backend Help](https://gitter.im/FreeCodeCamp/HelpBackEnd). As FCC does not oversee the workshopper challenges such as this one, we are unable to fix issues with these challenges should they arise. In the near future, we will have Backend challenges provided by FCC.

**Comment by niketanmoon** [comment]
type command npm init
then follow the instructions. when they ask you for git repository type git://github.com/yourgithubusername/repository.git
