### ISSUE TITLE
Show the Local Weather: Return value of inner function from outer function?

### ISSUE THREAD

**Issue by PardoR** [FreeCodeCamp/FreeCodeCamp#11487]
Hi guys, this is the first time I'm REALLY stucked. Thing is I have this code:

`function getLon(){
  var lon;
  $.getJSON("http://ip-api.com/json", function(pos){
    lon = (pos.lon).toString();
  });
  return lon;
};`

And (of course) lon isn't in the scope of the outer function, so it doesn't return anything. My question is, how could I return the lon value using the $.getSJON?

Thanks.

**Comment by raisedadead** [comment]
The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
