### ISSUE TITLE
Testing Objects for Properties

### ISSUE THREAD

**Issue by saitejs** [FreeCodeCamp/FreeCodeCamp#11488]
Challenge [Testing Objects for Properties](https://www.freecodecamp.com/challenges/testing-objects-for-properties#?solution=%0A%2F%2F%20Setup%0Avar%20myObj%20%3D%20%7B%0A%20%20gift%3A%20%22pony%22%2C%0A%20%20pet%3A%20%22kitten%22%2C%0A%20%20bed%3A%20%22sleigh%22%0A%7D%3B%0A%0Afunction%20checkObj(checkProp)%20%7B%0A%20%20%2F%2F%20Your%20Code%20Here%0A%20%20%2F%2Fvar%20checkProp%20%3D%22%22%3B%0A%20%20if%20(myObj.hasOwnProperty(%22checkProp%22))%7B%0A%20%20%20%20%20return%20myObj%5BcheckProp%5D%3B%7D%0A%20%20%0A%20%20else%0A%20%20%20%20return%20%22Not%20Found%22%3B%0A%7D%0A%0A%2F%2F%20Test%20your%20code%20by%20modifying%20these%20values%0AcheckObj(%22gift%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  //var checkProp ="";
  if (myObj.hasOwnProperty("checkProp")){
     return myObj[checkProp];}
  
  else
    return "Not Found";
}

// Test your code by modifying these values
checkObj("gift");

```

**Comment by dhcodes** [comment]
@saitejs you have a small error in your code. Please consider asking for help in the chat room by clicking the Help button on the challenge.

**Comment by saitejs** [comment]
@dhcodes ya i got that mistake .Thank you for your Time . I appreciate your work
