### ISSUE TITLE
Override Styles

### ISSUE THREAD

**Issue by ioanamunteanu** [FreeCodeCamp/FreeCodeCamp#11480]
Challenge [Override Styles in Subsequent CSS](https://www.freecodecamp.com/challenges/override-styles-in-subsequent-css#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%20%20%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%20blue-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .blue-text {
    color: blue;
  }
  .pink-text {
    color: pink;
    
  }
</style>
<h1 class="pink-text blue-text">Hello World!</h1>

```

**Comment by Dave1089** [comment]
I think you already got the answer in the Help Chatroom which is great. Happy Coding!
