### ISSUE TITLE
typo on last field guide article

### ISSUE THREAD

**Issue by JonSonesen** [FreeCodeCamp/freecodecamp#1148]
http://www.freecodecamp.com/field-guide/what-is-the-free-code-camp-front-end-development-certificate
I believe the sentence should not have the word 'be' in the sentence 
<code>All campers who have already completed these challenges are retroactively be eligible for the certificate!</code>

It should look something like this:
<code>All campers who have already completed these challenges are retroactively eligible for the certificate!</code>
 or this:
<code>All campers who have already completed these challenges will retroactively be eligible for the certificate!</code>

I have submitted a pull with a version of a fix #1135
I would be glad to amend the commit to accommodate whichever version you prefer. 
Also, previously I had submitted the pull prior to opening an issue in the future I will do the proper flow.

**Comment by QuincyLarson** [comment]
Thank you for fixing this. We've merged your fix!

**Comment by JonSonesen** [comment]
That's great! I'm happy to help.
:+1:
