### ISSUE TITLE
Overring Styles in Subsequent CSS

### ISSUE THREAD

**Issue by sh6sha** [FreeCodeCamp/FreeCodeCamp#11486]
#### Issue Description
Here in the below screen shot I have declared two classes pink-text and blue-text in the style. when I have called the class from h1 the class is not overriding . Can some one clarify it ?

Thanks

* Browser Name, Version: chrome 54.0
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

![image](https://cloud.githubusercontent.com/assets/5287070/19892419/d0152566-a06a-11e6-9ab7-3c741ce38301.png)

**Comment by molatO** [comment]
You have to be sure what color you want the text to be. If you need blue then remove the pink-text class from the h1 element, and vice versa.

**Comment by raisedadead** [comment]
@sh6sha Please refer instructions once again.

> Note: It doesn't matter which order the classes are listed in the HTML element.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by sh6sha** [comment]
hey thanks for the Quick reply

here's the syntax
<h1 class="class1 class2". here class 2 over rides class 1 . Please correct me If I am wrong. So its not happening in my scenario

I am a new bie not sure where to ask so created a new issue thread :)
