### ISSUE TITLE
Which test case is wrong when value equals number in array?

### ISSUE THREAD

**Issue by kerrykimrusso** [FreeCodeCamp/FreeCodeCamp#11498]
Where Do I Belong?
https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=%0Afunction%20getIndexToIns(arr%2C%20num)%20%7B%0A%20%20arr.sort()%3B%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20%2B%2Bi)%20%7B%0A%20%20%20%20if(num%20%3C%3D%20arr%5Bi%5D)%20%7B%0A%20%20%20%20%20%20return%20i%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20return%20arr.length%3B%0A%7D%0A%0AgetIndexToIns(%5B40%2C%2060%5D%2C%2050)%3B%0A

#### Issue Description
Test cases seem contradictory:
> getIndexToIns([10, 20, 30, 40, 50], 30) should return 2.
> getIndexToIns([5, 3, 20, 3], 5) should return 2.

My code checks if two numbers are less than or equal:

if(num <= arr[i]) {
  return i;
}

and if that's true, I return i. It passes for the first test but not for the second. 
The first test seems to want the index before the number it's equal to, while the second test seems to want the index after the number it's equal to.

#### Browser Information
* Chrome, Version 53.0.2785.116 (64-bit)
* OSX 10.11.6
* MacBook Air (Mid-2012)

#### Your Code
```js
 function getIndexToIns(arr, num) {
  arr.sort();
  for(var i = 0; i < arr.length; ++i) {
    if(num <= arr[i]) {
      return i;
    }
  }
  
  return arr.length;
}

getIndexToIns([40, 60], 50);
```

**Comment by erictleung** [comment]
@kerrykimrusso thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). GitHub issues are not for coding help. Happy coding!

**Comment by kerrykimrusso** [comment]
So this isn't an issue with the test cases being wrong? That's why I posted it here, because the test cases where the number to insert is equal to a number in the array have two different ideas about where to insert, one is before the equal number and one is after. Or am I reading that totally wrong?

**Comment by erictleung** [comment]
@kerrykimrusso correct, the tests work just fine and are consistent. There is an error in your code that is preventing you from passing the challenge. Please use the Help Rooms for more help and tag me if you're not getting a response. Otherwise, be patient, there are many people in the rooms willing to help. Good luck and happy coding!
