### ISSUE TITLE
Cat app

### ISSUE THREAD

**Issue by vijaymadiri** [FreeCodeCamp/FreeCodeCamp#11492]
Challenge [Headline with the h2 Element](https://www.freecodecamp.com/challenges/headline-with-the-h2-element#?solution=%0A%3Cdiv%20style%3D%22color%3ABlue%3Bfloat%3Aleft%3Bfont-size%3A35px%3B%22%3ECatPhotoApp%3C%2Fdiv%3E%0A%3Cimg%20src%3D%22http%3A%2F%2F3.bp.blogspot.com%2F-_xO_K-MCDS0%2FUGT2QyazFbI%2FAAAAAAAAGIw%2F00JcyiEhHVg%2Fs1600%2FBaby_Cat_Wallpaper_1.jpg%22Class%3D%22img-circle%22%20style%3D%22width%3A20%25%3Bheight%3A50px%3Bmargin-top%3A5px%3Bborder-style%3Asolid%3Bborder-color%3Agreen%3B%22%3E%0A%3Cdiv%20class%3D%22container%22%3E%0A%20%20%3Cimg%20src%3D%22http%3A%2F%2Fcdn.wallpapersafari.com%2F91%2F68%2FGMqnoD.jpg%22style%3D%22width%3A240px%3B%22%3E%0A%20%20%0A%20%20%0A%20%3Cbutton%20type%3D%22button%22%20class%3D%22btn%20btn-primary%22%3E%3Ci%20class%3D%22fa%20fa-thumbs-up%22%20aria-hidden%3D%22true%22%3E%3C%2Fi%3ELike%3C%2Fbutton%3E%0A%20%20%3Cbutton%20type%3D%22button%22%20class%3D%22btn%20btn-info%22%20style%3D%22margin-left%3A13px%22%3E%3Ci%20class%3D%22fa%20fa-info-circle%22%20aria-hidden%3D%22true%22%3E%3C%2Fi%3EInfo%3C%2Fbutton%3E%0A%20%20%3Cbutton%20type%3D%22button%22%20class%3D%22btn%20btn-danger%22%20style%3D%22margin-left%3A13px%22%3E%3Ci%20class%3D%22fa%20fa-trash-o%22%20aria-hidden%3D%22true%22%3E%3C%2Fi%3EDelete%3C%2Fbutton%3E%0A%20%20%0A%20%20%3Cform%20fccfaa%3D%22%22%3E%0A%20%20%3Cinput%20type%3D%22radio%22%20name%3D%22gender%22%20value%3D%22male%22%3E%20Indoor%0A%20%20%20%20%3Cinput%20type%3D%22radio%22%20name%3D%22gender%22%20value%3D%22female%22%20style%3D%22margin-left%3A90px%22%3E%20Outdoor%3Cbr%3E%0A%20%20%0A%3C%2Fform%3E%0A%20%20%3Cdiv%20class%3D%22checkbox%22%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20value%3D%22%22%3ELoving%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20value%3D%22%22%3ELazy%3C%2Flabel%3E%0A%20%20%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20value%3D%22%22%3ECrazy%3C%2Flabel%3E%0A%3C%2Fdiv%3E%0A%20%20%3Cform%3E%0A%20%20%3Cdiv%20class%3D%22form-group%22%3E%0A%20%20%20%0A%20%20%20%20%3Cinput%20type%3D%22email%22%20class%3D%22form-control%22%20id%3D%22email%22%20%20placeholder%3D%22Cat%20photo%20URL%22%20style%3D%22padding%3A12px%22%3E%0A%20%20%20%20%0A%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fform%3E%0A%20%20%3Cbutton%20type%3D%22button%22%20class%3D%22btn%20btn-primary%22%3E%3Ci%20class%3D%22fa%20fa-paper-plane%22%20aria-hidden%3D%22true%22%3E%3C%2Fi%3ELike%3C%2Fbutton%3E%0A%3C%2Fdiv%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<div style="color:Blue;float:left;font-size:35px;">CatPhotoApp</div>
<img src="http://3.bp.blogspot.com/-_xO_K-MCDS0/UGT2QyazFbI/AAAAAAAAGIw/00JcyiEhHVg/s1600/Baby_Cat_Wallpaper_1.jpg"Class="img-circle" style="width:20%;height:50px;margin-top:5px;border-style:solid;border-color:green;">
<div class="container">
  <img src="http://cdn.wallpapersafari.com/91/68/GMqnoD.jpg"style="width:240px;">
  
  
 <button type="button" class="btn btn-primary"><i class="fa fa-thumbs-up" aria-hidden="true"></i>Like</button>
  <button type="button" class="btn btn-info" style="margin-left:13px"><i class="fa fa-info-circle" aria-hidden="true"></i>Info</button>
  <button type="button" class="btn btn-danger" style="margin-left:13px"><i class="fa fa-trash-o" aria-hidden="true"></i>Delete</button>
  
  <form action="">
  <input type="radio" name="gender" value="male"> Indoor
    <input type="radio" name="gender" value="female" style="margin-left:90px"> Outdoor<br>
  
</form>
  <div class="checkbox">
  <label><input type="checkbox" value="">Loving</label>
    <label><input type="checkbox" value="">Lazy</label>
    <label><input type="checkbox" value="">Crazy</label>
</div>
  <form>
  <div class="form-group">
   
    <input type="email" class="form-control" id="email"  placeholder="Cat photo URL" style="padding:12px">
    
  </div>
  </form>
  <button type="button" class="btn btn-primary"><i class="fa fa-paper-plane" aria-hidden="true"></i>Like</button>
</div>
```

**Comment by raisedadead** [comment]
Hi @vijaymadiri :

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by teeleek** [comment]
puttasak insee

เมื่อ 2 พ.ย. 2016 02:05 "Mrugesh Mohapatra" <notifications@github.com>
เขียนว่า

**Comment by teeleek** [comment]
Teelek201460@gmail.com

puttasak insee

เมื่อ 22 พ.ย. 2016 01:39 "Puttasak Insee" <teelek201460@gmail.com> เขียนว่า
