### ISSUE TITLE
add-a-submit-button-to-a-form section don't let me go forward

### ISSUE THREAD

**Issue by reoxb** [FreeCodeCamp/FreeCodeCamp#11496]
#### Challenge Name
add-a-submit-button-to-a-form 

#### Issue Description
don't let me go forward
 OK Your form should have a button inside it.
 OK Your submit button should have the attribute type set to submit.
 OK Your submit button should only have the text "Submit".
 OK Make sure your button element has a closing tag. 

#### Browser Information

* Browser Name, Version: Mozilla Firefox 49
* Operating System:  Linux Mint Rosa 17
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <input type="text" placeholder="cat photo URL">
  <button type="submit">Submit</button>
</form>
 
 
 
```
#### Screenshot
[Image](http://dl.dropbox.com/u/50651770/Selecci%C3%B3n_003.png)

**Comment by erictleung** [comment]
@reoxb that's odd. I've never seen that happen before. Your code does pass and I'm unable to reproduce your issue. I would guess this is just a chance happening and would just refresh the page and see if that fixes it.

**Comment by texas2010** [comment]
This is so odd. I could pass this challenge with his code on chrome and firefox on mac. it is fine to me. I didn't realized he used firefox on the Linux Mint Rosa.

**Comment by Bouncey** [comment]
closing as stale, @reoxb if you have any other information, please reopen this issue and share with us :+1:
