### ISSUE TITLE
FCC points and achievement dates wrongfully reset upon clicking challenge completion

### ISSUE THREAD

**Issue by crosscris** [FreeCodeCamp/freecodecamp#115]
Action Performed:
1: Passed a bonfire challenge and changed point total from 55 to 56.
2. Went to profile and click on challenge 3.
3. Marked challenge 3 as completed. - Challenge 3 has already been completed.
4. Saw point total go back to 55 and saw challenge 3 finish date set to 2/23/2015.
Expected Result:
Point total should remain at 56 and challenge 3 finish date should remain at the original date.
Actual Result:
Point total reverted to 55 and challenge 3 finish date set to erroneous date.

Notes
Thankfully, bonfire completion is not reset. 

Further detail:
Firefox 35.0.1, Windows 7 32 bit

https://drive.google.com/file/d/0B-94cRSEUQu_OWtObHc4Q3Eyamc/view?usp=sharing
https://drive.google.com/file/d/0B-94cRSEUQu_NjFXQlNySWh0Uzg/view?usp=sharing

**Comment by terakilobyte** [comment]
This is very much known, sadly. The good news is this isn't an issue under the new challenge system Quincy and I have been building. This will remain open until the next major feature release which is imminent.

**Comment by BerkeleyTrue** [comment]
Sorry about the label confusion above, we were testing out waffle.io and didn't realise that it adds labels on issues, which is an awesome feature.
