### ISSUE TITLE
I've tested my code in JSBin for the following error: "After updateRecords(2548, "artist", ""), artist should not be set"  and it worked in JSBIN. The property 'artist' has been deleted and for the hasOwnProperty("artist") it gives false in JSBIN, but it still gives me the error message in the excercise.

### ISSUE THREAD

**Issue by rkornel75** [FreeCodeCamp/FreeCodeCamp#11504]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by dhcodes** [comment]
@rkornel75 please post your code so we can take a look. Also bear in mind that different editors have varying levels of stringency and linting.

**Comment by marhyorh** [comment]
@rkornel75 This is one long title, consider changing it. Let the description be in the body instead.

**Comment by dhcodes** [comment]
Closing for now. Please reopen if you are still having an issue with the site.
