### ISSUE TITLE
Replace npm with yarn as a package manager

### ISSUE THREAD

**Issue by petrgazarov** [FreeCodeCamp/FreeCodeCamp#11501]
It would be good to replace npm with yarn in the app.

Benefits it'll bring:
- Faster downloads
- Keeps track of specific version in `yarn.lock`
- Emojis when running commands (obviously this is the main reason 😄  )

I've been using yarn for a couple weeks now and haven't had any problems.

Transition was seamless for us.
- it uses the same `package.json`
- very similar cli commands

If anyone has had problems with it, honestly would be interested to hear.

**Comment by erictleung** [comment]
@petrgazarov thanks for the issue. Looks like this has been brought up before and someone had problems https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11208. Have you tested `yarn` with the FreeCodeCamp repository yet?

**Comment by petrgazarov** [comment]
Works fine for me locally!

Steps I did:
- recloned repo
- `yarn install`
- installed gulp and bower globally with yarn
- setup database, as per instructions
- `yarn run only-once`

Then ran all scripts in `package.json`, substituting `npm` with `yarn`

Everything worked as expected. 

My env details for reference:
```
node -v
v6.0.0

yarn version v0.16.1

npm -v
3.10.8

Mac OS Yosemite
10.10.5
```

**Comment by BerkeleyTrue** [comment]
@petrgazarov Thanks but we will be sticking with npm for the foreseeable future. I don't see Yarn taking over just yet.
