### ISSUE TITLE
Tests fail on Chunky Monkey but with correct output(recursive but with global variable)

### ISSUE THREAD

**Issue by AlexanderPoet** [FreeCodeCamp/FreeCodeCamp#11505]
#### Challenge Name

Chunky Monkey

#### Issue Description

I know the tests fail because of the globally scoped variable. But I'm not quite sure how to make it local without declaring the array empty each time.

#### Browser Information

* Browser Name, Version: Firefox
* Operating System: OSX
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js
//jshint esversion:6

let boo = [];
function chunkArrayInGroups(arr, size) {
  // Break it up. 
    if (arr.length === 0) {
      return boo;
    }
    else if (arr.length < size) {
        boo.push(arr.slice(0,size));
      return boo;
    }
 boo.push(arr.slice(0,size));
  
 return chunkArrayInGroups(arr.splice(size),size);
}
 
 
```

**Comment by erictleung** [comment]
@AlexanderPoet a bit of a round-a-bout way but you could create another function as your recursive function and just have `chunkArrayInGroups()` to be a wrapper and `boo` to be a local variable within `chunkArrayInGroups()`. Nonetheless, congrats on finishing the algorithm! Please ask questions in the future to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
