### ISSUE TITLE
Correct Output but User Case still RED

### ISSUE THREAD

**Issue by SaujanUprety** [FreeCodeCamp/FreeCodeCamp#11500]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Afunction%20titleCase(str)%20%7B%0A%20%20%0A%20%20var%20word%20%3D%20%22%22%3B%0A%20%20var%20sentence%20%3D%20%22%22%3B%0A%20%20var%20j%20%3D%200%3B%0A%20%20%0A%20%20%0A%20%20str%20%3D%20str.charAt(0)%20%2Bstr%3B%0A%20%20str%20%2B%3D%20%27%20%20%27%3B%0A%20%20%20for(var%20i%20%3D%200%3B%20i%3Cstr.length-1%20%3Bi%2B%2B)%7B%0A%20%20%20%20%0A%20%20%20%20if(str.charAt(i)%20%3D%3D%3D%20%27%20%27)%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20word%20%3D%20str.substring(j%2Ci)%3B%0A%20%20%20%20%20%20j%20%3D%20i%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20word%20%3D%20word.charAt(1).toUpperCase()%20%2B%20word.substring(2%2Cword.length).toLowerCase()%3B%0A%20%20%20%20%20%20sentence%20%2B%3D%20word%20%2B%20%22%20%22%20%3B%0A%20%20%20%20%0A%20%20%20%20%20%7D%0A%20%20%20%20%20%0A%20%20%20%20%20%0A%20%20%20%7D%0A%20%20%0A%20%20return%20sentence%3B%0A%7D%0A%0AtitleCase(%22HERE%20IS%20MY%20HANDLE%20HERE%20IS%20MY%20SPOUT%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function titleCase(str) {
  
  var word = "";
  var sentence = "";
  var j = 0;
  
  
  str = str.charAt(0) +str;
  str += '  ';
   for(var i = 0; i<str.length-1 ;i++){
    
    if(str.charAt(i) === ' '){
      
      word = str.substring(j,i);
      j = i;
      
      word = word.charAt(1).toUpperCase() + word.substring(2,word.length).toLowerCase();
      sentence += word + " " ;
    
     }
     
     
   }
  
  return sentence;
}

titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");
```

**Comment by BhaveshSGupta** [comment]
Hey @SaujanUprety, the problem is the extra space at the end of each statement. Your code is returning "Here Is My Handle Here Is My Spout " instead of "Here Is My Handle Here Is My Spout"

**Comment by erictleung** [comment]
@SaujanUprety what @BhaveshSGupta mentions is right. Please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help) if you get stuck or have questions with a challenge in the future. Happy coding!

**Comment by SaujanUprety** [comment]
Thank you, I fixed it later on. I will do a better revision before posting
as a bug.

**Comment by SaujanUprety** [comment]
s
has invited you to Wikibuy.

While you shop on Amazon, Wikibuy automatically
finds better offers from other sellers in 10 seconds.

SAVE WITH WIKIBUY ( http://wbuy.me/6XZLGB6?utm_campaign=referral&utm_source=referral_email&utm_medium=email )

( https://www.facebook.com/wikibuy )

( https://twitter.com/wikibuy )

ABOUT US ( https://wikibuy.com/ )

|

LEGAL TERMS ( https://wikibuy.com/our-terms/terms-of-service )

|

UNSUBSCRIBE ( http://track.customer.io/unsubscribe/NDE2Nzg6FwFRngJkAAJzABgBDOAHGgFfcB-IaRU1GFn34-YBZTowMUJYUjU0RU0xSk5WRkZaSFExTkdSOVRLWjozNjQ4NDUA )

Need help? Send us a message: HELP@WIKIBUY.COM (
mailto:help@wikibuy.com )
Wikibuy. 3939 Bee Cave Rd, Austin, TX 78746
