### ISSUE TITLE
What's wrong with this code?

### ISSUE THREAD

**Issue by fuzzbomber** [FreeCodeCamp/FreeCodeCamp#11512]
<div id="object" class="wow  bounceInLeft animated"> <a href="#icons"> <i class="fa fa-angle-down fa-5x wow pulse infinite animated"></a></i>

**Comment by fuzzbomber** [comment]
<div id="object" class="wow  bounceInLeft animated"> <a href="#icons"> <i class="fa fa-angle-down fa-5x wow pulse infinite animated"></a></i>

**Comment by invinciblemuffi** [comment]
Where's the code?

**Comment by raisedadead** [comment]
@fuzzbomber 
The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

@invinciblemuffi thanks.
