### ISSUE TITLE
Use Comments to Clarify Code challenge terminates lessons

### ISSUE THREAD

**Issue by billyjim** [FreeCodeCamp/FreeCodeCamp#11516]
Challenge [Use Comments to Clarify Code](https://www.freecodecamp.com/challenges/use-comments-to-clarify-code#?solution=%3C!--Only%20change%20code%20above%20this%20line.--%3E%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.

For challenge "Use Comments to Clarify Code":

After the "Run tests ..." button is clicked the challenge is marked correct on the pop-up.
Clicking "Submit and go to my next challenge" terminates the challenge sequence and returns the the Free Code Camp sign-up page.

My code:
```html
<!--Only change code above this line.-->
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by atjonathan** [comment]
Cannot reproduce.
cc/ @FreeCodeCamp/moderators

**Comment by abhisekp** [comment]
For me, after the "Run tests ..." button is clicked the challenge is marked correct on the pop-up.
Clicking "Submit and go to my next challenge" terminates the challenge sequence and shows  https://www.freecodecamp.com/challenges/join-our-forum page

**Comment by atjonathan** [comment]
@abhisekp, same. I don't redirect to the signup page either though.

**Comment by billyjim** [comment]
I agree with @abhisekp: it redirects to the page that @abhisekp provided the link to. Sorry for the misinformation, the page seemed to be one in the sign-up sequence.
Sorry, but I don't understand @atjonathan's reply. Seems to agree with @abhisekp that the challenge sequence terminates, which is the issue I was reporting -- I can't continue to the next challenge.

**Comment by atjonathan** [comment]
@billyjim, sorry for the confusion. This behavior is expected. The "Join Our Forum" challenge is after "Use comments to clarify code".

[![https://gyazo.com/633e7464dd84909796708640db096b36](https://i.gyazo.com/633e7464dd84909796708640db096b36.png)](https://gyazo.com/633e7464dd84909796708640db096b36)

Happy Coding!

**Comment by Kaykwanu** [comment]
I am in your shoes right now....how did you guys get past this stage?

**Comment by abhisekp** [comment]
@Kaykwanu You may join the Forum as per the challenge and proceed to the next challenge.
