### ISSUE TITLE
Find the Longest Word in a String Challenge 

### ISSUE THREAD

**Issue by Dave1089** [FreeCodeCamp/FreeCodeCamp#11519]
Challenge [Find the Longest Word in a String](https://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=%0Avar%20bigWord%3D0%3B%0A%0Afunction%20findLongestWord(str)%20%7B%0A%20%0A%20%20var%20strArray%3Dstr.split(%22%20%22)%3B%0A%20%20var%20wordLength%3D0%3B%0A%20%20for%20(var%20i%3D0%3B%20i%3CstrArray.length%3B%20i%2B%2B)%7B%0A%20%20%20%20wordLength%3DstrArray%5Bi%5D.length%3B%0A%20%20%20%20if%20(wordLength%20%3E%20bigWord)%7B%0A%20%20%20%20%20%20%20%20bigWord%3DwordLength%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20bigWord%3B%0A%7D%0A%0A%0A%0A%0AfindLongestWord(%22May%20the%20force%20be%20with%20you%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.

When you define variable outside function , it returns correct output but doesn't pass the challenge, so it makes this confusing. I know that for the challenges, it is expected to write code inside function and not use `global` variables , but it will restrict the thinking of a camper who wants to experiment with the below code which I got question in the Help room

Code:
```javascript

var bigWord=0;

function findLongestWord(str) {
 
  var strArray=str.split(" ");
  var wordLength=0;
  for (var i=0; i<strArray.length; i++){
    wordLength=strArray[i].length;
    if (wordLength > bigWord){
        bigWord=wordLength;
        }
  }
  return bigWord;
}

findLongestWord("May the force be with you");
```

**Comment by erictleung** [comment]
@Dave1089 thanks for the issue. There's already a discussion on making global variables work here https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9199. Please continue the discussion over there. Happy coding!
