### ISSUE TITLE
Add Git & GitHub Challenges

### ISSUE THREAD

**Issue by atjonathan** [freeCodeCamp/freeCodeCamp#11515]
https://www.youtube.com/playlist?list=PLWKjhJtqVAbkFiqHnNaxpOPhh9tSWMXIF

**Comment by raisedadead** [comment]
Wrong repo? 
[FreeCodeCamp/CurriculumExpansion](https://github.com/FreeCodeCamp/CurriculumExpansion)

**Comment by atjonathan** [comment]
@raisedadead, I don't think so. I will be making a PR adding these video challenges. Unless we are keeping all curriculum updates on that repository? This is not directly with the "curriculum expansion".

**Comment by raisedadead** [comment]
Cool, I was just asking. It's okay however it suits lol!

**Comment by atjonathan** [comment]
@raisedadead, not a problem 😜

**Comment by QuincyLarson** [comment]
@atjonathan @raisedadead we will be pulling these videos and their descriptions directly from YouTube - no seed file presence needed.

**Comment by atjonathan** [comment]
@QuincyLarson 👍
