### ISSUE TITLE
A missing coma that may confuse new coders who come to the site

### ISSUE THREAD

**Issue by Ramanusasango** [FreeCodeCamp/FreeCodeCamp#11511]
Challenge [Manipulating Complex Objects](https://www.freecodecamp.com/challenges/manipulating-complex-objects#?solution=%0Avar%20myMusic%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Billy%20Joel%22%2C%0A%20%20%20%20%22title%22%3A%20%22Piano%20Man%22%2C%0A%20%20%20%20%22release_year%22%3A%201973%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CS%22%2C%20%0A%20%20%20%20%20%20%228T%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%0A%20%20%20%20%22gold%22%3A%20true%0A%20%20%7D%2C%0A%20%20%2F%2F%20Add%20record%20here%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Michael%20W.%20Smith%22%2C%0A%20%20%20%20%22title%22%3A%20%22Worship%22%2C%0A%20%20%20%20%22release_year%22%3A%202001%2C%0A%20%20%20%20%22formats%22%3A%20%5B%0A%20%20%20%20%20%20%22mp3%22%2C%0A%20%20%20%20%20%20%22CD%22%2C%0A%20%20%20%20%20%20%22Cassette%22%0A%20%20%20%20%5D%0A%20%20%7D%0A%5D%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  }, _**this coma is missing and it may really confuse people especially since they are being told to add the record below**_
  // Add record here
  {
    "artist": "Michael W. Smith",
    "title": "Worship",
    "release_year": 2001,
    "formats": [
      "mp3",
      "CD",
      "Cassette"
    ]
  }
];


```

**Comment by Manish-Giri** [comment]
@Ramanusasango There is only one element in the array by default, so I don't see why would there be a comma? Once you add another object as the second element, then you add the comma. Besides, there's also a note - 
> Note
You will need to place a comma after every object in the array, unless it is the last object in the array.

**Comment by AustinOverholt** [comment]
I had the same issue. I assumed that everything above the "// Add record here" could be left alone. I couldn't get it to take my solution until I saw that missing comma.

**Comment by invinciblemuffi** [comment]
While in the JavaScript community some prefer to keep trailing commas after objects and properties, while others do not agree upon it. Also note that when you lint your code and you have a trailing comma in your code, the linter will throw a warning as: `Expected an identifier ...`, unless you explicitly manage the linter properties file and make the trailing comma's check as false.

**Comment by raisedadead** [comment]
This confusion has been seen before in the past related to this challenge:

Campers often just see and add the code after the `// Add record here` and overlook the NOTE in the instructions.

Unfortunately, this is something that can't be managed perfectly. We have deliberately left this, to make a reminder the instructions should be read carefully. Closing as done earlier in past.

**Comment by Ramanusasango** [comment]
Well I know that but alot of people are just following the instructions for change code below this line and are running into errors, remember most people using this are not seasoned and it is worth mentioning. thank you for your response though
