### ISSUE TITLE
font-family order is not checked

### ISSUE THREAD

**Issue by EmadMokhtar** [FreeCodeCamp/freecodecamp#1151]
Challenge http://www.freecodecamp.com/challenges/waypoint-specify-how-fonts-should-degrade has an issue. Please describe how to reproduce it, and include links to screen shots if possible.
In the Challenge it ask that "use "Lobster" as their font family, but degrade to the "Monospace" font when the "Lobster" font isn't available" but if you write the other way in the CSS you can pass the challenge.
![screenshot 2015-06-29 12 51 51](https://cloud.githubusercontent.com/assets/311636/8405530/d39dcb1a-1e5d-11e5-9dd7-5c9b097a797c.png)

**Comment by qubodup** [comment]
I found the corresponding line https://github.com/FreeCodeCamp/freecodecamp/blob/staging/seed/challenges/basic-html5-and-css.json#L738 but I don't know what `assert()` does and why `match()` has such strange input, so I'm not sure how to fix this ticket. Perhaps split the css value string by into an array and make sure the item with "monospace" has a higher index than the item with "lobster".

**Comment by benmcmahon100** [comment]
@qubodup assert is part of the test library fcc uses. So in this case the tests like you were saying should be for example:
assert($('h2').css('font-family').toLowerCase().replace(' ', '').split(',')[0].match(/lobster/i)
assert($('h2').css('font-family').toLowerCase().replace(' ', '').split(',')[1].match(/monospace/i)

**Comment by qubodup** [comment]
Please note that both `FONTNAME,FONTNAME` and `FONTNAME, FONTNAME` are legal, so one should probably first split with `,` only and then `.trim()`.

**Comment by benmcmahon100** [comment]
it doesn't really change the result but sure!
