### ISSUE TITLE
Remove rules from projects

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#11513]
Currently each of our project challenges has rules like these: 
```
        "<strong>Rule #1:</strong> Don't look at the example project's code. Figure it out for yourself.",
        "<strong>Rule #2:</strong> Fulfill the below <a href='https://en.wikipedia.org/wiki/User_story' target='_blank'>user stories</a>. Use whichever libraries or APIs you need. Give it your own personal style.",
        "<strong>Rule #3:</strong> You must use both Sass and React to build this project.",
```

I have already replaced all three of these rules on our curriculum expansion branch with the following line, which is the same for every single project challenge:

```
        "Fulfill the below <a href='https://en.wikipedia.org/wiki/User_story' target='_blank'>user stories</a>. Use whichever libraries or APIs you need. Give it your own personal style.",
```

Note that this means there are no "rules" in these challenge descriptions. 

For this issue, note that you should start this pull request by branching off of backup/master. 

Then go in and change these lines in the seed/challenges directory for each of the -projects.json seed files.

To be clear, yes, we are getting rid of the React/D3 requirements for the data visualization certificate. (This has been planned for a long time, and we would have done this on production a long time ago if we had realized how ambitious our  curriculum expansion effort would become.)

Then you'll need to submit two pull requests - one against backup/master and one against staging.

**Comment by Manish-Giri** [comment]
@QuincyLarson Can I try this?

**Comment by raisedadead** [comment]
@Manish-Giri Awesome! Help Wanted issues are open to everyone, so you needn't ask, just go ahead! 

Just remember:
> you'll need to submit two pull requests - one against backup/master and one against staging

Thanks and happy fixing. Hit us in chat if you need any assistance.

**Comment by Manish-Giri** [comment]
@raisedadead okay, I'm on it. Thanks!

**Comment by QuincyLarson** [comment]
@Manish-Giri awesome - thank you for your help with this 😄

**Comment by Manish-Giri** [comment]
@raisedadead @QuincyLarson I made a first PR against `backup/staging`. However, I also included the "front end projects" in this PR, even though they were not in the `-project.json` seed files. I'm not sure if this was intended originally, but I thought it's better to be consistent if we are removing "rules" from projects.

Please let me know if this is okay. If this PR looks fine, I can make the next one against `staging`.

**Comment by BerkeleyTrue** [comment]
@Manish-Giri The pr should be against backup/master.

**Comment by Manish-Giri** [comment]
@BerkeleyTrue I did make the PR against `backup/master`. My earlier comment about `backup/staging` was a typo, fixed it.
