### ISSUE TITLE
Escaping Literal Quotes in Strings

### ISSUE THREAD

**Issue by ikeuzo57** [FreeCodeCamp/FreeCodeCamp#11520]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3B%20%2F%2F%20Change%20this%20line%0AmyStr%20%3D%20%22FirstLine%5Cn%5C%5CSecondLine%5C%5C%5CrThirdLine%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr; // Change this line
myStr = "FirstLine\n\\SecondLine\\\rThirdLine";


```

**Comment by atjonathan** [comment]
@ikeuzo57, your code passes fine for me. Can you expand on what the issue is?

**Comment by ikeuzo57** [comment]
Ok it works now I guess it's browser issue
