### ISSUE TITLE
Concatenating Strings with the Plus Equals Operator

### ISSUE THREAD

**Issue by ikeuzo57** [FreeCodeCamp/FreeCodeCamp#11521]
Challenge [Concatenating Strings with the Plus Equals Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-the-plus-equals-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%3B%0AourStr%20%2B%3D%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%3B%0AmyStr%20%3D%20%22This%20is%20the%20first%20sentence.%20%22%3B%0AmyStr%20%2B%3D%20%22This%20is%20the%20second%20sentence.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line

var myStr;
myStr = "This is the first sentence. ";
myStr += "This is the second sentence.";



```

**Comment by atjonathan** [comment]
@ikeuzo57, your code passes for me fine. Can you explain what the issue is?

**Comment by Tylercarissa** [comment]
I'm having the same issue. It's saying the myStr value is incorrect and not letting us pass the challenge.

**Comment by priyasharmab** [comment]
I'm having the same issue. It's saying the myStr value is incorrect and not letting us pass the challenge.
error "myStr should have a value of This is the first sentence. This is the second sentence."

my code:
// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line

var myStr= "This is the first sentence.";
myStr+="This is the second sentence.";

**Comment by Naudeep** [comment]
I don't know exactly but once try myStr and + with a space

**Comment by priyasharmab** [comment]
I tried doing it still is not working.
My Code:
// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line

var myStr = "This is the first sentence.";
myStr += "This is the second sentence.";

**Comment by ikeuzo57** [comment]
var myStr = "This is the first sentence. ";
notice the space between the full stop and semi-colon on both lines. Create a space it will work fine

**Comment by ar94952** [comment]
There is something wrong with the page.  It doesn't seem to accept the right answer.


// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line

var ourStr = "This is the first sentence. ";
ourStr += "This is the second sentence.";

**Comment by jason1135** [comment]
having same issue i get
myStr = "This is the first
sentence.This is the second
sentence."
as a result it appears the " are still displaying how do i make them not appear on the outcome?

**Comment by barkinet** [comment]
There is no spoon
