### ISSUE TITLE
new challenge not coming

### ISSUE THREAD

**Issue by prabhudatta1995** [FreeCodeCamp/FreeCodeCamp#11535]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by dhcodes** [comment]
Could you please use the issue template to provide some more context (browser, behavior, etc)?

**Comment by Bouncey** [comment]
If you have more information, please reopen the issue
