### ISSUE TITLE
there is no challenge, all the answer is already done

### ISSUE THREAD

**Issue by manitu2420** [FreeCodeCamp/FreeCodeCamp#11532]
Challenge [Target the Children of an Element Using jQuery](https://www.freecodecamp.com/challenges/target-the-children-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
    $("#right-well").children().css("color", "orange")

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by mohessaid** [comment]
The question or the challenge here is to make all the element in the right well with an orange color which you already did using the last line in your script tag. If you find the answer already there, then perhaps you already solved the challenge and accidentally repeating it.
![image](https://cloud.githubusercontent.com/assets/3033171/20028289/c8985ac2-a32d-11e6-8547-66927aece78e.png)

**Comment by erictleung** [comment]
@manitu2420 what I speculate the issue to be is that you are sharing your computer with other people going through FreeCodeCamp. Challenge answers are temporarily stored in cache so if someone before you finished the challenge and then you logged on, you'd find their answer there. Please verify if this is your situation or not.

**Comment by manitu2420** [comment]
@erictleung HI. No, nobody has access to m pc besides me. It was three questions in a row already answered before i did anything. Thanks for useful information.

**Comment by systimotic** [comment]
Hi @manitu2420! I just checked the [source code for this challenge](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/jquery.json#L1202) as well as tried the live version myself. I can not reproduce your issue, things work as expected for me.
I can only come to the same conclusion as Eric came before, and I think I have proof... 😛 
We save solutions to challenges you have done before. Looking at [your profile](https://www.freecodecamp.com/manitu2420), I can see that you have indeed completed the challenges you are reporting this issue on twice. That means that when you did them the second time, your solution from the first time would already be there. 😄 

I'm fairly confident that this is what happened, so I'm closing this issue. If you believe what I found is not right, however, please add additional information and reopen this issue.
Happy coding! 🎉
