### ISSUE TITLE
Whats wrong with my java code

### ISSUE THREAD

**Issue by omar52ramo** [FreeCodeCamp/FreeCodeCamp#11537]
import java.util.Scanner
        public class Userinput2 {
            public static void main(String[]args ){
                Scanner scan1 = new Scanner(System.in);
                Scanner scan2 = new Scanner(System.in);
                System.out.println("What is your name? ");
                String user_input_name = scan1.next();
                System.out.println("What is your favourite fruit?(Write as plural e.g. apples) ");
                String user_input_fruit = scan2.next();
                System.out.println("Your name is ");
                System.out.print(user_input_name);
                System.out.print(",and your favourite is ");
                System.out.print(user_input_fruit);
                }

        }

**Comment by omar52ramo** [comment]
help please

**Comment by Rafaelj** [comment]
What's happening?

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. You might want to use our [forum](http://forum.freecodecamp.com) for a language like Java 😄  Happy Coding!

**Comment by aolyf** [comment]
lol this isn't javascript
but anyway one of String variables is lowercase
