### ISSUE TITLE
Wording change for fibonacci numbers problem.

### ISSUE THREAD

**Issue by raphey** [FreeCodeCamp/FreeCodeCamp#11530]
I apologize if this in an incorrect venue for this suggestion--I'm new at this.

I believe the example should be changed to read as follows (change **bolded**):

> For example, sumFibs(10) should return 10 because all odd Fibonacci numbers less than **or equal to** 10 are 1, 1, 3, and 5.

As it stands, the example incorrectly implies that the target numbers are <num.

**Comment by erictleung** [comment]
@raphey thanks for the issue. Yes, you are correct about the change, as it is mentioned to be "less than or equal to" in the first sentence of the challenge.

**Comment by alkuhar** [comment]
If the issue is still open, can I work on it?

**Comment by erictleung** [comment]
@alkuhar go for it! Feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/Contributors) chat room if you have any questions about contributing.
