### ISSUE TITLE
Code Editor Cursor Offset Problem

### ISSUE THREAD

**Issue by desttinghim** [FreeCodeCamp/FreeCodeCamp#11536]
#### Challenge Name
Pretty much any of the challenges.

#### Issue Description
While going through the challenges, I'm having an issue with the code editor. Basically, if a line wraps at the start of a challenge, it will make it so that where the cursor appears to be and where the cursor actually is no longer match. However, this bug only lasts until something is typed.

#### Browser Information

* Browser Name, Version: Chromium 53.0.2785.143 (Developer Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
* Operating System: Linux, Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

**Comment by erictleung** [comment]
@desttinghim thanks for the issue. This is, unfortunately, a known issue here https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7847. Take a look at the discussion there for some ideas on how to overcome this inconvenience. Closing in favor of that issue. Happy coding!
