### ISSUE TITLE
The actual result is different from expected, but test still pass.

### ISSUE THREAD

**Issue by guanzhou-zhao** [FreeCodeCamp/FreeCodeCamp#11541]
Challenge [Diff Two Arrays](https://www.freecodecamp.com/challenges/diff-two-arrays#?solution=%0Afunction%20diffArray(arr1%2C%20arr2)%20%7B%0A%20%20var%20newArr%20%3D%20%5B%5D%3B%0A%20%20var%20set%20%3D%20new%20Set(%5B...arr1%2C%20...arr2%5D)%3B%0A%0A%20%20set.forEach(function%20(item)%20%7B%0A%20%20%20%20if%20(arr1.indexOf(item)%20%3D%3D%3D%20-1%20%7C%7C%20arr2.indexOf(item)%20%3D%3D%3D%20-1)%20%7B%0A%20%20%20%20%20%20newArr.push(item)%3B%0A%20%20%20%20%7D%0A%20%20%7D)%3B%0A%20%20%0A%0A%20%20return%20newArr%3B%0A%7D%0A%0AdiffArray(%5B%22andesite%22%2C%20%22grass%22%2C%20%22dirt%22%2C%20%22pink%20wool%22%2C%20%22dead%20shrub%22%5D%2C%20%5B%22diorite%22%2C%20%22andesite%22%2C%20%22grass%22%2C%20%22dirt%22%2C%20%22dead%20shrub%22%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

## The actual result is different from expected, but test still pass.
```
Actual : expected
["pink wool", "diorite"] : ["diorite", "pink wool"]
```

![actual <=> expected](https://guanzhou-zhao.github.io/cdn/image/diff_two_arrays.png)
My code:
```javascript

function diffArray(arr1, arr2) {
  var newArr = [];
  var set = new Set([...arr1, ...arr2]);

  set.forEach(function (item) {
    if (arr1.indexOf(item) === -1 || arr2.indexOf(item) === -1) {
      newArr.push(item);
    }
  });
  

  return newArr;
}

diffArray(["andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"]);

```

**Comment by erictleung** [comment]
@guanzhou-zhao thanks for the issue. Yes, the arrays are different and the order of arrays does matter. But for this challenge, the order doesn't matter. I think the instructions could be modified to mention that the order of the output doesn't matter.

**Comment by Manish-Giri** [comment]
@erictleung I'll work on this. I will PM you the change I made before submitting a PR.

**Comment by Bouncey** [comment]
@Manish-Giri Can we please discuss the changes in the issue?

That way if someone other than @erictleung is QA'ing the PR, they will know what the requested changes were

Many Thanks :+1:

**Comment by Manish-Giri** [comment]
@Bouncey Ah, of course. Sorry, my bad!

**Comment by erictleung** [comment]
A possible edit for the challenge would be (changes are in bold): 

> Compare two arrays and return a new array with any items only found in one of the two given arrays, but not both. In other words, return the symmetric difference of the two arrays.
>
> **Note
> You can return the array with its elements in any order.**
>
> ...

**Comment by Manish-Giri** [comment]
Should I proceed with this change, then?

**Comment by erictleung** [comment]
@Manish-Giri go for it! The "Note" part should be in `<strong>` tags by the way.
