### ISSUE TITLE
Free Code Camp - CS101

### ISSUE THREAD

**Issue by genevieve314** [FreeCodeCamp/freecodecamp#1154]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-basic-computer-science has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Hello, I just went to the Stanford online learning platform and CS101 is no longer available. If there are other available resources I would love to learn about them.
Thanks!
Genevieve

**Comment by rcw271828** [comment]
I can still see the course on my Standford account. Try this link: https://lagunita.stanford.edu/courses/Engineering/CS101/Summer2014/about

**Comment by LumenTeun** [comment]
I'm also able to access the courses. Make sure that you have an account at Stanford Online and that you're logged in, @genevieve314
