### ISSUE TITLE
Language selection not persisting correctly between sessions

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#11546]
After selecting Spanish in `/settings`, all translated challenges show correctly. 

If I open a new window/tab, Spanish remains selected in `/settings`, but translated challenges are shown in English on the `Map` and in the challenge `View`

I can see the `update-my-lang` api request in my terminal, with no errors in the console.

@BerkeleyTrue

**Comment by Bouncey** [comment]
To expand on this, if my selected language is Spanish and I navigate to `/en/challenges/...` the challenge and map are shown in English, but my selected language remains as Spanish (`entities.user[username].languageTag`)

**Comment by BerkeleyTrue** [comment]
Works fine on my end. 

> if my selected language is Spanish and I navigate to /en/challenges/...

This is because you have selected the English version. The url lang takes precedent.

Are you sure you are not opening new tabs with the `/en` lang?

**Comment by Bouncey** [comment]
Yes I am navigating to a challenge using my address bar history, which holds `en` paths. 

Shouldn't `entities.user[username].languageTag` take precedent over the path lang, seeing as it is the users selected language?

**Comment by BerkeleyTrue** [comment]
If a user is entering the lang in the url we assume that is the lang they want.

Happy Coding

**Comment by Bouncey** [comment]
@BerkeleyTrue I have just managed to confirm the issue without selecting a language in the URI

![anim](https://cloud.githubusercontent.com/assets/18572518/20225410/10587dc6-a83b-11e6-906e-a46e021090ff.gif)

**Comment by Bouncey** [comment]
If I select a language, the routing is all correct for that session, but not the next.

**Comment by Bouncey** [comment]
PR #11545 relies on this issue being resloved

**Comment by BerkeleyTrue** [comment]
You clicked on a challenge that was not translated. Does the same behavior happen when you click on a translated challenge?

**Comment by Bouncey** [comment]
Yes.

The challenge remains translated, but the route is `en`

**Comment by BerkeleyTrue** [comment]
Ok. Seeing as this is not the same behavior described in the original issue, do you mind closing this one and opening up a new one describing this new behavior?

**Comment by Bouncey** [comment]
Closed in favour of #11627
