### ISSUE TITLE
Confusing jQuery waypoint instructions

### ISSUE THREAD

**Issue by kanadgodse** [FreeCodeCamp/freecodecamp#1155]
On the jQuery Waypoint's last instructions, the wordings might confuse users as codeacademy's UI does not have any "sections".

For Eg: on "Waypoint: Harness Dynamic HTML" (http://www.freecodecamp.com/challenges/waypoint-harness-dynamic-html) The last instruction reads:
Go to http://www.codecademy.com/courses/web-beginner-en-v6phg/0/1 and complete the third section.

But after visiting the link to Codeacademy, there is no mention of the word section anywhere and the number of steps in the lesson are 14.

Even I struggled to understand if I was to complete till 3/14 or 3rd Section meant completing till "Mastering Manipulations" which occurs only after clicking the lesson number.

Just thought to update the waypoint instructions to be clear like "Complete all lessons".

Thanks,

Kanad Godse

**Comment by BerkeleyTrue** [comment]
Closing as all codecademy courses will be removed in next iteration of curriculum.

Happy Coding!
