### ISSUE TITLE
i have done all but cant move on

### ISSUE THREAD

**Issue by assanfulp** [FreeCodeCamp/FreeCodeCamp#11558]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```
#### Screenshot

i have arranged my code in order but cant run test successfully to move on

**Comment by erictleung** [comment]
@assanfulp thanks for the issue but if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help) before making an issue here. Next time, please fill out the issue template for us to help you. If you still think this isn't a coding error, please reopen this issue and fill out the issue template. Thanks and happy coding!

**Comment by assanfulp** [comment]
i have asked in the help room several times and everyone who tried to help seems not to understand what is going on. this is my code..

<h2>uncommented</h2>

please, if this is my mistake kindly help.

**Comment by erictleung** [comment]
@assanfulp sorry to hear you're still having issues. Tag me in a help room or message me on Gitter and we can work it out there. GitHub isn't for coding help. Thanks!
