### ISSUE TITLE
Should we move from TravisCI to SemaphoreCI?

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#11550]
Increases build time with caching, something we have been looking for with TravisCI.

### youtube :point_down: 
[![SemaphoreCI](https://i.ytimg.com/vi/OQAifaOEmVo/hqdefault.jpg?custom=true&w=196&h=110&stc=true&jpg444=true&jpgq=90&sp=68&sigh=XBWL7SUosBBxCrnkcROW94LtT2I)](https://www.youtube.com/watch?v=OQAifaOEmVo)

**Comment by erictleung** [comment]
I like speed when possible. However, for FreeCodeCamp, (from my experience) it's built/coded asynchronously so IMO, this kind of speed isn't as important. I may consider SemaphoreCI for my own projects now, though, because I like instant gratification 😄  My two cents on the matter.

**Comment by BerkeleyTrue** [comment]
While Semaphore looks interesting, it is not a huge improvement over travis. 

Happy Coding
