### ISSUE TITLE
A to N and B to O is 11 and not 13

### ISSUE THREAD

**Issue by chocobuoy** [FreeCodeCamp/FreeCodeCamp#11554]
Challenge [Caesars Cipher](https://www.freecodecamp.com/challenges/caesars-cipher) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function rot13(str) { // LBH QVQ VG!
  
  return str;
}

// Change the inputs below to test
rot13("SERR PBQR PNZC");

```

**Comment by erictleung** [comment]
@chocobuoy thanks for the issue but ROT13 is a shift of 13, not 11. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
