### ISSUE TITLE
No repeats please and Heap's algorithm

### ISSUE THREAD

**Issue by fhdhsni** [FreeCodeCamp/FreeCodeCamp#11553]
#### No repeats please
https://www.freecodecamp.com/challenges/no-repeats-please

#### Issue Description
I'm going nuts. Could someone please walk me through [Heap's algorithm](https://en.wikipedia.org/wiki/Heap%27s_algorithm)? Why do we check `int` to see if it's odd or even and why do we determine which elements to swap based on that? Where does this odd or even idea come from? Assuming that I don't know this algorithm, how can I solve this challenge?

```js
 function perm(str) {

  // Split the string into an array of characters.
  var arr = str.split('');
  var permutations = [];
  var tmp;

  // Function to swap variables' content.
  function swap(index1, index2) {
    tmp = arr[index1];
    arr[index1] = arr[index2];
    arr[index2] = tmp;
  }

  //Generate arrays of permutations using the algorithm.
  function generate(int) {      // int is length of array
    if (int === 1) {
      // Make sure to join the characters as we create  the permutation arrays
      permutations.push(arr.join(''));
    } else {
      for (var i = 0; i != int; ++i) {
        generate(int - 1);
        if (int % 2 === 0) {
          swap(i, int - 1);
        } else {
          swap(0, int - 1);
        }
      }
    }
  }

  generate(arr.length);

  return permutations;
}

console.log(perm("abcd"));

 
```

**Comment by dhcodes** [comment]
@fhdhsni please use the help button on the challenge to ask for help in the HelpJavascript chat room for freecodecamp. The github issues area is for reporting problems with the site.

Happy coding.

**Comment by fhdhsni** [comment]
I did so and got not answer!

**Comment by Mongues** [comment]
Thanks for your email friend input channel number and more options to did
follow

**Comment by texas2010** [comment]
@Mongues 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!

**Comment by dhcodes** [comment]
@fhdhsni maybe try again today?
