### ISSUE TITLE
Change the Font Size of an Element

### ISSUE THREAD

**Issue by arisoftware** [FreeCodeCamp/FreeCodeCamp#11559]
```html
<style>
  .red-text {
    color: red;
  }p
  {
    font-size: 16px; 
  }
</style>
<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by Bouncey** [comment]
@arisoftware please use the template provided, it is helpfully gives us plenty of information to help diagnose your issue.

Please return to the challenge and copy the full address in the address bar, this holds information on the challenge you are on and what code you have entered

Many thanks :+1:

**Comment by erictleung** [comment]
@arisoftware your code works for the challenge ["Change the Font Size of an Element"](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element). Please give us more information about the issue you're having, if any.

**Comment by Bouncey** [comment]
Please reopen this issue if you have any more information :+1:
