### ISSUE TITLE
Concatenating strings with plus operator help.

### ISSUE THREAD

**Issue by Tylercarissa** [FreeCodeCamp/FreeCodeCamp#11568]
Challenge [Concatenating Strings with Plus Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20%22This%20is%20the%20start.%22%20%2B%20%22This%20is%20the%20end.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr = "This is the start." + "This is the end.";

It's saying the value of my string is incorrect. ^^^

```

**Comment by Tylercarissa** [comment]
Hi,

This is a bug because my code is fine, but it's not letting me move on to the next challenge. I typed the exact value specified in the correct format and for some reason it is not recognizing it.

**Comment by Manish-Giri** [comment]
@Tylercarissa you're missing a space when you're building `myStr`. Take a look at this note too - 

> Note
Watch out for spaces. Concatenation does not add spaces between concatenated strings, so you'll need to add them yourself.

Please visit the [help room](https://gitter.im/FreeCodeCamp/Help) for assistance on this, if you're still stuck.

**Comment by dhcodes** [comment]
Thanks @Manish-Giri. Closing as resolved.

**Comment by Tylercarissa** [comment]
Here is my code: var myStr = "This is the start." + "This is the end.";

Where is the missing space? Thanks for your help.

**Comment by celinelp** [comment]
"This is the start." + " This is the end.";

**Comment by chetanpatole** [comment]
thanx @celinelp
