### ISSUE TITLE
One month apart should say Two months apart.

### ISSUE THREAD

**Issue by 1hella** [FreeCodeCamp/FreeCodeCamp#1156]
Challenge http://www.freecodecamp.com/challenges/bonfire-friendly-date-ranges has an issue.

December 1st to February 3rd is two months not one month. The test is pretty wordy regardless.
![screen shot 2015-06-29 at 2 34 24 pm](https://cloud.githubusercontent.com/assets/6580703/8420787/8a21badc-1e7b-11e5-9b16-a6ddf0d70237.png)

**Comment by davemofosho** [comment]
I believe it needs to be used in numbers not the name of the month.

**Comment by 1hella** [comment]
The numbers and everything in the test are right, it's just the message. The output for `friendly(['2015-12-01', '2016-02-03'])` is `['December 1st','February 3rd']`.

**Comment by davemofosho** [comment]
Oh because nothing is one month apart look the number format for the year one is 2015 and one is 2016.

**Comment by 1hella** [comment]
This is not a problem with the logic of the test or based on my input – it's just a typo. 

Yes the years are different but the two dates are only two months apart, therefore the year of the second argument doesn't need to be outputted because it can be inferred.

The test should say something along the lines of, "two months apart can be inferred, even if it is the next year".

**Comment by benschenker** [comment]
Closing as fixed in #1197
