### ISSUE TITLE
h2 element is not changing color. I am using mobile android chrome browser. Once you start the code h2 element will not change color again.

### ISSUE THREAD

**Issue by hydrocronic** [FreeCodeCamp/FreeCodeCamp#11566]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">
CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

 
 
 
```

**Comment by dhcodes** [comment]
Closing as duplicate

**Comment by hydrocronic** [comment]
This one has the code close the first one...

**Comment by hydrocronic** [comment]
Have I got something wrong everyone that answered my question said the code is working for them.

**Comment by dhcodes** [comment]
@hydrocronic I think this is similar to recent issue with a non-breaking space causing the tests not to pass. I can't find it right now, but I believe it's device specific, being that you're on mobile Chrome. I can confirm this on my android device so we'll look into it.

**Comment by atjonathan** [comment]
Fixed in https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11472. We will have this live soon hopefully! Until then, just reset your code and rewrite it making sure there are no non breaking spaces :smile:

**Comment by dhcodes** [comment]
@hydrocronic Reset the code so you start afresh and then do something like:
```
<style>
 .red-text {color:red;}
</style>
<h2 class="red-text">
CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

 ```
