### ISSUE TITLE
Remove stampit

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#11571]
We use to use Stampit throughout the codebase, but since our move from Thundercats to Redux, we have only one location where we use Stampit to create a factory. We can replace this stampit factory with a plain factory and remove stampit all together.

Here is the only place we use it. We need to convert this into a plain factory function and remove stampit from the package.json
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/549cfc305f75d8c6036a3cde65c47b518607b18c/common/utils/services-creator.js#L3

**Comment by ChristianLapinig** [comment]
@BerkeleyTrue I can take a crack at it

**Comment by BerkeleyTrue** [comment]
@ChristianLapinig 👍

**Comment by Bouncey** [comment]
@ChristianLapinig How are you getting on with this?
