### ISSUE TITLE
one exercise in expressworks missing - another broken

### ISSUE THREAD

**Issue by dwilbank68** [FreeCodeCamp/FreeCodeCamp#1157]
Challenge http://www.freecodecamp.com/challenges/waypoint-build-web-apps-with-express.js has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Hi. There is no longer a 'session and cookies' exercise in expressworks.
And the final expressworks problem seems to be broken.
Even their solution from the repository won't pass.
![](https://dl.dropboxusercontent.com/spa/lkj2dewi3ofvkgc/so4ticcc.jpg)

**Comment by benschenker** [comment]
Similar to #1449, I'm going to close this as stale, reopen if this still is an issue for you

**Comment by CharlesMilam** [comment]
I am having the same issue with the last exercise "JSON Me". It will not pass the verify test, and same as @dwilbank68 can confirm that their own solution fails verification.

**Comment by benschenker** [comment]
Hey @CharlesMilam,

Can you open a new issue for this?

**Comment by CharlesMilam** [comment]
Done

see issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2995
