### ISSUE TITLE
Challenge Escape Issues

### ISSUE THREAD

**Issue by angelogianopulos** [FreeCodeCamp/FreeCodeCamp#11577]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=var%20myStrr%3B%0AmyStr%20%3D%20%22FirstLine%5Cn%5C%5CSecondLine%5C%5C%5CrThirdline%22%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var myStrr;
myStr = "FirstLine\n\\SecondLine\\\rThirdline";
```

**Comment by angelogianopulos** [comment]
Solved.

**Comment by erictleung** [comment]
@angelogianopulos sounds like your issue is resolved. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
