### ISSUE TITLE
Return Early Pattern for Functions

### ISSUE THREAD

**Issue by beanbing** [FreeCodeCamp/FreeCodeCamp#11583]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by raisedadead** [comment]
What exactly is the issue? Please share more information.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
