### ISSUE TITLE
Test case bug in 'Decimal Numbers in JS' challenge

### ISSUE THREAD

**Issue by MatthewDiana** [FreeCodeCamp/FreeCodeCamp#11589]
#### Create Decimal Numbers with JavaScript

https://www.freecodecamp.com/challenges/create-decimal-numbers-with-javascript

#### Issue Description

Defining `myDecimal` without the `var` keyword passes the test. The variable is not previously defined in this code snippet, so it should fail (even though the `var` keyword is not required to get expected output when using my browser's devtools).

#### Your Code

```js
var ourDecimal = 5.7;

// Only change code below this line

myDecimal = 5.7;
```

**Comment by sepiropht** [comment]
This is not a bug , it just the usual beahavior of Javascript. 
That why es6 come with 'const' and 'let' , so var is not used anymore in serious project.

**Comment by Bouncey** [comment]
@MatthewDiana this is not a bug.

In javaScript, if a variable is assigned a value before being declared, it is declared in the global scope of the window/app by default.

Whilst it is bad practice, it is also a feature of the language
