### ISSUE TITLE
#9 Version instructions misleading

### ISSUE THREAD

**Issue by jondan1986** [FreeCodeCamp/FreeCodeCamp#11587]
#### Challenge Name
Manage Packages with npm
https://www.freecodecamp.com/challenges/manage-packages-with-npm

#### Issue Description
The "09 Version" section says to update your version with the command "npm version". The actual command is "npm version patch" which you find by running "npm help version" but otherwise impossible to figure out with just the tutorial. Just thought an easy text update would fix the confusion.

**Comment by dhcodes** [comment]
@jondan1986 unfortunately, freecodecamp does not manage the learn-you-npm and other similarly named workshoppers. Feel free to report the issue on their repo here:
https://github.com/workshopper/how-to-npm/issues
