### ISSUE TITLE
http://wind-bow.hyperdev.space/ is DOWN!

### ISSUE THREAD

**Issue by arctelix** [FreeCodeCamp/FreeCodeCamp#11592]
Challenge [Use the Twitchtv JSON API](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by dhcodes** [comment]
cc @Em-Ant

**Comment by Em-Ant** [comment]
Hyperdev is not reliable h24 as a 'real' server. Sometimes it just happens...

**Comment by dhcodes** [comment]
Looks like it's back now. Closing as known issue.
