### ISSUE TITLE
complaining of spaces when spaces not given

### ISSUE THREAD

**Issue by rajyak1984** [FreeCodeCamp/FreeCodeCamp#11597]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%27FirstLinen%5C%5C%5CSecondLine%5C%5C%5CnThirdLine%5Cr%27%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr ='FirstLinen\\\SecondLine\\\nThirdLine\r';



```

**Comment by dhcodes** [comment]
@rajyak1984 you have an error in your code; it's not related to the spacing, it's related to escaping. Please consider asking for help in the chat room by clicking the Help button on the challenge.
