### ISSUE TITLE
Will not accept code, keeps saying that a semicolon is missing.

### ISSUE THREAD

**Issue by Mr-Baker** [FreeCodeCamp/FreeCodeCamp#11590]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 8530.96.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.154 Safari/537.36</code>.
I was simply running my test and the shell would say, "Syntax error: Unexpected Number." Additionally the content checks for the test disappeared.
![screenshot 2016-11-08 at 2 15 06 pm](https://cloud.githubusercontent.com/assets/22153804/20119621/1db71164-a5be-11e6-82b5-1d07425f3be9.png)
![screenshot 2016-11-08 at 2 15 13 pm](https://cloud.githubusercontent.com/assets/22153804/20119632/2d0c6344-a5be-11e6-9a06-c6498550aebc.png)

My code:
```javascript

var myVar = 87;

// Only change code below this line

myVar++1;


```

**Comment by ImOrientalFlavored** [comment]
Try changing myVar++1 to myVar++

**Comment by Mr-Baker** [comment]
Thank you, it works 👍

**Comment by sludge256** [comment]
Please use the help button on the challenge page or the forum for these types of issues in the future. Thanks.

**Comment by Diesirae91** [comment]
you dont need the "1" after it.  the "++" operator adds 1 automatically.
