### ISSUE TITLE
class "fa-trash"in lesson "Add Font Awesome Icons to all of our Buttons" adds extra trash icons

### ISSUE THREAD

**Issue by Marigold2** [FreeCodeCamp/FreeCodeCamp#11604]
Adding class "fa-trash" to challenge "Add Font Awesome Icons to all our Buttons" produces extra trash can icons throughout the screen.
1. Add the class fa-trash to the `<i>` element as in:
<div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"</i>Delete</button>
 </div>
2. Run the challenge
Result: You will be congratulated on doing the challenge correctly but extra trash can icons will appear 

<img width="364" alt="trash icon screenshot" src="https://cloud.githubusercontent.com/assets/19824250/20165397/b2f3c4f8-a6c1-11e6-85a0-fc0f3b3428e1.png">

**Comment by erictleung** [comment]
@Marigold2 thanks for the issue. I'm unable to replicate your issue. Can you give us information about what browser you're using? I'm using Chrome and I'm unable to get multiple trash icons. There doesn't seem to be anything wrong with the code you've shared.

**Comment by Marigold2** [comment]
Using chrome also,Version 54.0.2840.71 (64-bit) with macOS Sierra. Don't know if you were able to see my screen shot to see the multiple trash can icons. Not a big deal if you can't reproduce this as it's not getting in my way of learning. Thanks anyways.
