### ISSUE TITLE
cloud9 asks for credit card verification

### ISSUE THREAD

**Issue by sunilma** [FreeCodeCamp/FreeCodeCamp#11601]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by erictleung** [comment]
@sunilma thanks for the issue. This is a duplicate issue of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9826. Closing this issue in favor of that one. Happy coding!
