### ISSUE TITLE
Strange Cursor Positioning

### ISSUE THREAD

**Issue by drguildo** [FreeCodeCamp/FreeCodeCamp#11609]
#### Issue Description
The embedded code editor has strange cursor positioning behaviour. If the cursor is on a line and I hit the `End` key, sometimes the cursor will move to some point in the middle of a line and sometimes it won't move at all. If I click at a point in the editor that is past the end of a line, sometimes the cursor will move there while other times it won't move to a point even if it's in the middle of a piece of text.

It seems that my cursor positioning ability is based on the line that is immediately below the current line.

#### Browser Information

* Browser Name, Version: Chrome 54.0.2840.87
* Operating System: Windows 7 64-bit
* Mobile, Desktop, or Tablet: Desktop

**Comment by Bouncey** [comment]
@drguildo  thanks for the issue. This is, unfortunately, a known issue here #7847. Take a look at the discussion there for some ideas on how to overcome this inconvenience. Closing in favour of that issue. Happy coding!
