### ISSUE TITLE
The API Key workaround has went down

### ISSUE THREAD

**Issue by IJACOBS** [FreeCodeCamp/FreeCodeCamp#11600]
Challenge [Use the Twitchtv JSON API](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.27 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The API key workaround using https://wind-bow.hyperdev.space/twitch-api has went down. While this is down, there is no way to test or complete the challenge. I have been trying to implement the Twitch API key, but it is quite advanced and I have not been successful yet.

**Comment by Manish-Giri** [comment]
See #11592

**Comment by dhcodes** [comment]
Closing as duplicate
