### ISSUE TITLE
Dodger-blue-text not working

### ISSUE THREAD

**Issue by APersonWithNothing** [FreeCodeCamp/FreeCodeCamp#11602]
Challenge [Use Hex Code to Mix Colors](https://www.freecodecamp.com/challenges/use-hex-code-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20FF0000%3B%0A%20%20%7D%0A%20%20.green-text%20%7B%0A%20%20%20%20color%3A%2000FF00%3B%0A%20%20%7D%0A%20%20.dodger-blue-text%20%7B%0A%20%20%20%20color%3A%202998E4%3B%0A%20%20%7D%0A%20%20.orange-text%20%7B%0A%20%20%20%20color%3A%20%23FFA500%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22green-text%22%3EI%20am%20green!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22dodger-blue-text%22%3EI%20am%20dodger%20blue!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orange-text%22%3EI%20am%20orange!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: FF0000;
  }
  .green-text {
    color: 00FF00;
  }
  .dodger-blue-text {
    color: 2998E4;
  }
  .orange-text {
    color: #FFA500;
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodger-blue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

```

**Comment by 0x0936** [comment]
Hi @APersonWithNothing 

Hex values in CSS must begin with a hash mark `#`. Look at `.orange-text` for a working example, in your code.

**Comment by erictleung** [comment]
@APersonWithNothing as @0x0936 has pointed out, hex values start with an ampersand sign (`#`). If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
