### ISSUE TITLE
Correct result returned but could not pass.

### ISSUE THREAD

**Issue by gude432** [FreeCodeCamp/FreeCodeCamp#11610]
Challenge [Roman Numeral Converter](https://www.freecodecamp.com/challenges/roman-numeral-converter#?solution=%2F%2Fnocheck%0Avar%20symbols%20%3D%20%5B'I'%2C'V'%2C'X'%2C'L'%2C'C'%2C'D'%2C'M'%5D%3B%0Avar%20nums%20%3D%20%5B1%2C5%2C10%2C50%2C100%2C500%2C1000%5D%3B%0Avar%20rom%3B%20var%20count%20%3D%200%3B%20%20%0Afunction%20convertToRoman(num)%20%7B%0A%09%09rom%20%3D%20''%3B%0A%09%09chk(num-num%251000)%3B%0A%09%09chk(num%251000-num%25100)%3B%0A%09%09chk(num%25100-num%2510)%3B%0A%09%09chk(num%2510-num%251)%3B%20%0A%20%20return%20rom%3B%0A%7D%0A%09%0Afunction%20chk%20(num)%7B%0A%20%20%20for%20(var%20i%3D0%3Bi%3C%3Dnums.length%20%26%26%20num%20%3E%3D1%20%3Bi%2B%2B)%7B%0A%20%20%20%09if(num%3D%3Dnums%5Bi%5D-1%7C%7Cnum%3D%3Dnums%5Bi%5D-10%7C%7Cnum%3D%3Dnums%5Bi%5D-100%7C%7Cnum%3D%3Dnums%5Bi%5D-1000%20)%7B%0A%20%20%20%09%09rom%2B%3Dsymbols%5Bnums.indexOf(nums%5Bi%5D-num)%5D%3B%0A%20%20%20%09%09rom%2B%3Dsymbols%5Bi%5D%3B%0A%20%20%20%09%09num-%3Dnums%5Bi-1%5D%3B%20%20%20%09%0A%20%20%20%09%7D%0A%20%20%20%09else%20if(num%3Cnums%5Bi%5D)%7B%0A%20%20%20%20%20%20num-%3Dnums%5Bi-1%5D%3B%0A%20%20%20%20%20%20if(num%3E-1%20%26%26%20count%3C3)%20%7B%0A%20%20%20%20%20%20%09rom%2B%3D(symbols%5Bi-1%5D)%3B%0A%20%20%20%20%20%20%09%20chk(num)%3B%0A%20%20%20%20%20%20%7D%20%20%20%20%20%0A%20%20%20%09%7D%0A%20%20%20%09else%20if%20(num%3E%3Dnums%5Bnums.length-1%5D)%7B%0A%20%20%20%09%09count%2B%2B%3B%20%20%20%09%09%0A%20%20%20%09%09num-%3D1000%3B%0A%20%20%20%09%09if(num%3E-1%20%26%26%20count%3C3)%20%7B%0A%20%20%20%09%09rom%2B%3Dsymbols%5Bnums.length-1%5D%3B%0A%20%20%20%09%09chk(num)%3B%0A%20%20%20%09%09%7D%0A%20%20%20%09%7D%0A%20%20%7D%0A%7D%0A%2F%2FconvertToRoman(1000)%3B%0AconvertToRoman(1006)%3B%0A%0A%09%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var symbols = ["I","V","X","L","C","D","M"];
var nums = [1,5,10,50,100,500,1000];
var rom; var count = 0;  
function convertToRoman(num) {
		rom = '';
		chk(num-num%1000);
		chk(num%1000-num%100);
		chk(num%100-num%10);
		chk(num%10-num%1); 
  return rom;
}
	
function chk (num){
   for (var i=0;i<=nums.length && num >=1 ;i++){
   	if(num==nums[i]-1||num==nums[i]-10||num==nums[i]-100||num==nums[i]-1000 ){
   		rom+=symbols[nums.indexOf(nums[i]-num)];
   		rom+=symbols[i];
   		num-=nums[i-1];   	
   	}
   	else if(num<nums[i]){
      num-=nums[i-1];
      if(num>-1) {
      	rom+=(symbols[i-1]);
      	 chk(num);
      }
     
   	}
   	else if (num>=nums[nums.length-1]){
   		count++;   		
   		num-=nums[nums.length-1];
   		if(num>-1 && count<3) {
   		rom+=symbols[nums.length-1];
   		chk(num);
   		}
   	}
  }
}
convertToRoman(2014);

	



```

**Comment by raisedadead** [comment]
<img width="741" alt="screen shot 2016-11-11 at 2 06 20 am" src="https://cloud.githubusercontent.com/assets/1884376/20193427/f219f3ee-a7b3-11e6-9b34-8987bb423bce.png">


I can get the challenge to pass with your code, there are test cases which are not passing.

**Comment by gude432** [comment]
@raisedadead, thanks I'll recheck.

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room @gude432 for getting help with challenges. Happy Coding!
