### ISSUE TITLE
Title case challenge: Output is correct but user case stil show red

### ISSUE THREAD

**Issue by Ogih001** [FreeCodeCamp/FreeCodeCamp#11619]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Afunction%20titleCase(str)%20%7B%0A%20%20str%3Dstr.toLowerCase().replace(%2F%5Cb%5Cw%2Fgi%2Cfunction(val)%7B%0A%20%20%20%20return%20val.toUpperCase()%3B%0A%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20)%3B%0A%20%20return%20str%3B%0A%7D%0A%0AtitleCase(%22john%20buLL%20mY%20sOn%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
function titleCase(str) {
  str=str.toLowerCase().replace(/\b\w/gi,function(val){
    return val.toUpperCase();
  }
                 );
  return str;
}

titleCase("john buLL mY sOn");

```

**Comment by raisedadead** [comment]
With your code:
> titleCase("I'm a little tea pot");

returns:
> I'**M** A Little Tea Pot

Please get in touch with the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for futher assistance.
