### ISSUE TITLE
Marquee not letting scroll to middle of the line.

### ISSUE THREAD

**Issue by mheck21** [FreeCodeCamp/FreeCodeCamp#11612]
Responsively Style Radio Buttons
https://www.freecodecamp.com/challenges/responsively-style-radio-buttons

#### Issue Description
I have been having issues getting my marquee to scroll to the middle of certain lines of code. If I use the arrow keys and go to the right, it will only go a few spaces, and then drop down to the next line.

#### Browser Information

* Browser Name, Version: Google Chrome Version 54.0.2840.87 (64-bit)
* Operating System: OSX El Capitan 10.11.6
* Mobile, Desktop, or Tablet: Desk

#### Your Code

```js
 
 
 
```

**Comment by raisedadead** [comment]
Hi @mheck21 can you confirm if this same as #7847 ? Or you are facing something completely different?
If the later, then please guide with the specific steps for reproducing.

Thanks!

**Comment by mheck21** [comment]
Actually you are correct, that is the same issue as #7847. Is there a
resolution? I haven't gotten all the way through the thread yet.

On Fri, Nov 11, 2016 at 5:59 AM, Mrugesh Mohapatra <notifications@github.com

**Comment by raisedadead** [comment]
Not a clean one so far, but some have been doing this: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7847#issuecomment-245764638

We have fixed this in a different branch which will be having a completely different editor. So untill then we request you to try the above workaround.

**Comment by raisedadead** [comment]
Hey @mheck21 I am closing this, please feel free to continue on the original thread.

**Comment by anamorell** [comment]
make sure view is in default 100%
