### ISSUE TITLE
Concatenating Strings with Plus Operator

### ISSUE THREAD

**Issue by Belle-Lau** [FreeCodeCamp/FreeCodeCamp#11616]
Challenge [Concatenating Strings with Plus Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%3D%22This%20is%20the%20start.%22%2B%22This%20is%20the%20end.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr="This is the start."+"This is the end.";



```

**Comment by Gotly** [comment]
I think it's because you didn't space before and after the "+"
You did:
`var myStr="This is the start."+"This is the end.";`
when it should be:
`var myStr="This is the start." + "This is the end.";`
try it again with ^ and see if that works.

**Comment by Belle-Lau** [comment]
liuzzly@foxmail.com
 
From: Gotly
Date: 2016-11-11 11:26
To: FreeCodeCamp/FreeCodeCamp
CC: Belle Lau; Author
Subject: Re: [FreeCodeCamp/FreeCodeCamp] Concatenating Strings with Plus Operator (#11616)
I think it's because you didn't space before and after the "+"
You did:
var myStr="This is the start."+"This is the end.";
when it should be:
var myStr="This is the start." + "This is the end.";
try it again with ^ and see if that works.

**Comment by raisedadead** [comment]
The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
