### ISSUE TITLE
Discrepancy with local weather

### ISSUE THREAD

**Issue by bcardozo** [FreeCodeCamp/FreeCodeCamp#11628]
Challenge [Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

It appears that there are conflicting problems with this challenge. In order to get the local location, https needs to be used. However, when the call to the localweatherapi is called it appears that another bug was submitted suggesting a workaround to not use https. I cannot get both the location and the weather call to work simultaneously.

**Comment by dhcodes** [comment]
@bcardozo thanks for reporting. This is a known issue in #8988 and #9079. I think #10341 fixes both issues. Take a look at the changes and discussion on those pages for some possible solutions. Happy coding!
