### ISSUE TITLE
Inventory Update correct code not working.

### ISSUE THREAD

**Issue by TasmaniaKrama** [FreeCodeCamp/FreeCodeCamp#11623]
#### Challenge Name

https://www.freecodecamp.com/challenges/inventory-update

#### Issue Description

For some reason it doesn't want to accept it as correct solution.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Win 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

function updateInventory(arr1, arr2) {
   var current = {};
   for (var i=0;i<arr1.length;i++) {
   	current[arr1[i][1]] = arr1[i][0];
   }
   for (i=0;i<arr2.length;i++){
   if (current.hasOwnProperty(arr2[i][1])) {
   	current[arr2[i][1]] = current[arr2[i][1]] + arr2[i][0];
   }
   else {
   	current[arr2[i][1]] = arr2[i][0];
   }
   }
return Object.keys(current).map(function(val) { return [current[val],val];  });

 
  
}




updateInventory([[0, "Bowling Ball"], [0, "Dirty Sock"], [0, "Hair Pin"], [0, "Microphone"]], [[1, "Hair Pin"], [1, "Half-Eaten Apple"], [1, "Bowling Ball"], [1, "Toothpaste"]]);

 
 
 
```
#### Screenshot

http://imgur.com/a/0EWzi

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
