### ISSUE TITLE
Falsey Bouncer Test Issue

### ISSUE THREAD

**Issue by jrandallhansen** [FreeCodeCamp/FreeCodeCamp#1162]
Challenge http://www.freecodecamp.com/challenges/bonfire-falsey-bouncer has an issue. Please describe how to reproduce it, and include links to screen shots if possible.  Using the code I wrote using the suggested call-back function I am able to pass all test cases but not move forward as having completed the bonfire challenge. 
![screen shot 2015-06-29 at 8 58 07 pm](https://cloud.githubusercontent.com/assets/12438039/8423668/d2402d46-1ea1-11e5-9028-22f0524bd990.png)

**Comment by LumenTeun** [comment]
I'm not sure why it says that your code passed the test cases, because it shouldn't with the way it's ordered now. Does it pass every time, even if you refresh the page?

**Comment by FFX01** [comment]
Asa far as I can tell, the first test should not pass as you have returned an empty string in the 2 index of your output array.

**Comment by benschenker** [comment]
Closing as stale, please reopen if this is still an issue
