### ISSUE TITLE
Creating a color for your h2 element.

### ISSUE THREAD

**Issue by lRedJohn** [FreeCodeCamp/FreeCodeCamp#11622]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by lRedJohn** [comment]
The color code help is missing a ; . It wrote .... Style="color: blue" .

**Comment by lRedJohn** [comment]
I remember using it on the computer and it was there but when I use it on my moible and took the challenge again it didn't show.

**Comment by dhcodes** [comment]
@lRedJohn are you talking about [this challenge](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element)?

Do you mean that your code changed or there is something incorrect about the instructions?

**Comment by Bouncey** [comment]
@lRedJohn your code for the challenge is only stored on the device you entered it on. So if you tried to complete the challenge on a PC, that is where your code will be, I doesn't not transfer between devices.

**Comment by teeleek** [comment]
puttasak insee

เมื่อ 12 พ.ย. 2016 01:32 "Stuart Taylor" <notifications@github.com> เขียนว่า
