### ISSUE TITLE
"Seek an Destroy" code works, but no pass

### ISSUE THREAD

**Issue by parisclinkscales** [FreeCodeCamp/FreeCodeCamp#11626]
Challenge [Seek and Destroy](https://www.freecodecamp.com/challenges/seek-and-destroy#?solution=function%20seeker%20(value)%7B%0A%20%20return%20value%20!%3D%3D%20this%3B%0A%7D%0A%0Afunction%20destroyer(arr)%20%7B%0A%20%20var%20filtered%20%3D%20arguments%5B0%5D%3B%0A%20%20for%20(var%20i%20%3D%201%3Bi%20%3C%20arr.length%3Bi%2B%2B)%7B%0A%20%20%20%20filtered%20%3D%20filtered.filter(seeker%2Carguments%5Bi%5D)%3B%0A%20%20%20%20%7D%0A%20%20return%20filtered%3B%0A%20%20%7D%0A%0Adestroyer(%5B%22tree%22%2C%20%22hamburger%22%2C%2053%5D%2C%20%22tree%22%2C%2053)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function seeker (value){
  return value !== this;
}

function destroyer(arr) {
  var filtered = arguments[0];
  for (var i = 1;i < arr.length;i++){
    filtered = filtered.filter(seeker,arguments[i]);
    }
  return filtered;
  }

destroyer(["tree", "hamburger", 53], "tree", 53);

```

**Comment by Bouncey** [comment]
@parisclinkscales Please see #9851, there is quite an in depth explanation from @systimotic as to why this is a (hard to detect) code issue.

Happy coding!
