### ISSUE TITLE
Commenting Issue

### ISSUE THREAD

**Issue by dennisorina** [FreeCodeCamp/FreeCodeCamp#11620]
<p> Even if i write it correctly, i dont get it <p>Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3C!--%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A--%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; TECNO S9S Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!--
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
-->

```

**Comment by raisedadead** [comment]
@dennisorina Your code is incorrect.

> Leave your h2 element uncommented so that it is visible on your page.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by Ashishk21** [comment]
same problem with me
tell me if you already figure this out how to solve
