### ISSUE TITLE
Correct code doesn't work

### ISSUE THREAD

**Issue by mikeyen123** [FreeCodeCamp/FreeCodeCamp#11624]
Challenge [Understanding Case Sensitivity in Variables](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables#?solution=%0A%2F%2F%20Declarations%0Avar%20studlyCapVaR%3B%0Avar%20properCamelCase%3B%0Avar%20titleCaseOver%3B%0A%0A%2F%2F%20Assignments%0AstudlyCapVaR%20%3D%2010%3B%0AproperCamelCase%20%3D%20%22A%20String%22%3B%0AtitleCaseOver%20%3D%209000%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Declarations
var studlyCapVaR;
var properCamelCase;
var titleCaseOver;

// Assignments
studlyCapVaR = 10;
properCamelCase = "A String";
titleCaseOver = 9000;

```

**Comment by raisedadead** [comment]
Hi @mikeyen123 

Your code is not correct, there is a typo.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
