### ISSUE TITLE
.unshift() removes ["John", 23]..

### ISSUE THREAD

**Issue by Mutasem-Halawani** [FreeCodeCamp/FreeCodeCamp#11632]
Challenge [Manipulate Arrays With unshift](https://www.freecodecamp.com/challenges/manipulate-arrays-with-unshift#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%22cat%22%5D%3B%0AourArray.shift()%3B%20%2F%2F%20ourArray%20now%20equals%20%5B%22J%22%2C%20%22cat%22%5D%0AourArray.unshift(%22Happy%22)%3B%20%0A%2F%2F%20ourArray%20now%20equals%20%5B%22Happy%22%2C%20%22J%22%2C%20%22cat%22%5D%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B%22John%22%2C%2023%5D%2C%20%5B%22dog%22%2C%203%5D%5D%3B%0AmyArray.shift()%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AmyArray.unshift(%5B%22Paul%22%20%2C%2035%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArray = ["Stimpson", "J", "cat"];
ourArray.shift(); // ourArray now equals ["J", "cat"]
ourArray.unshift("Happy"); 
// ourArray now equals ["Happy", "J", "cat"]

// Setup
var myArray = [["John", 23], ["dog", 3]];
myArray.shift();

// Only change code below this line.

myArray.unshift(["Paul" , 35]);

```

**Comment by Manish-Giri** [comment]
@Mutasem-Halawani `.unshift()` does not remove anything. `["John", 23]` is the first element in the array `myArray`, and so is removed by this line of code 
```
myArray.shift();
```
After that, you just insert `["Paul" , 35]` to the beginning of the array using `.unshift()`.

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) if you still have questions about this.

**Comment by Mutasem-Halawani** [comment]
Thank you, didn't notice the .shift () function..

**Comment by dhcodes** [comment]
Closing as resolved.
