### ISSUE TITLE
Норм. предложение разработчикам

### ISSUE THREAD

**Issue by Maladez** [FreeCodeCamp/FreeCodeCamp#11630]
При нажатии ctrl+enter выпадает фраза "well done", "good job" и т.д. Так вот - ниже допишите перевод на Украинский язык например (на другие языки) т.е. переведите эти сумасшедшие фразочки И вообще вместо них можно писать часто встречающийся (IT сленг).
Таким образом можно будет и Иностранный язык изучать. 
P.S. Могу заняться))

**Comment by atjonathan** [comment]
@Maladez, please submit an issue in English on our [TranslationExpansion](https://github.com/FreeCodeCamp/TranslationExpansion) Repository! Happy Coding!
