### ISSUE TITLE
Comment in existing code should be altered:

### ISSUE THREAD

**Issue by JeffGreenlee42** [FreeCodeCamp/FreeCodeCamp#11647]
Challenge [Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%0A%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20result%20%3D%20%7B%0A%20%20%20%20%22alpha%22%3A%20%22Adams%22%2C%0A%20%20%20%20%22bravo%22%3A%20%22Boston%22%2C%0A%20%20%20%20%22charlie%22%3A%20%22Chicago%22%2C%0A%20%20%20%20%22delta%22%3A%20%22Denver%22%2C%0A%20%20%20%20%22echo%22%3A%20%22Easy%22%2C%0A%20%20%20%20%22foxtrot%22%3A%20%22Frank%22%0A%20%20%7D%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%5Bval%5D%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22charlie%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  result = {
    "alpha": "Adams",
    "bravo": "Boston",
    "charlie": "Chicago",
    "delta": "Denver",
    "echo": "Easy",
    "foxtrot": "Frank"
  };

  // Only change code above this line
  return result[val];
}

// Change this value to test
phoneticLookup("charlie");

```

This Challenge requires that "[val]"  be added to the statement "return result;"      However the comment above it states "Only change code above this line."   ...   the comment should say something like, "change this line".

**Comment by erictleung** [comment]
@JeffGreenlee42 thanks for the issue and feedback. Yes, you can write the code that way, but we've asked that you assign the value to `result` rather than returning directly from the object.

> Convert the switch statement into a lookup table called `lookup`. Use it to lookup `val` and assign the associated string to the `result` variable.

There are many different ways of solving programming challenges. Your answer is perfectly acceptable but for the way the challenge is set up, changing `switch` statements to objects, this way works. Closing as the code and instructions are consistent. Happy coding!
