### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by bstonesifer** [FreeCodeCamp/FreeCodeCamp#11643]
#### Browser Information

cant get the my test to pass.
i have compared my code to others and ask for help in chat.. 
* Browser Name, Version: firefox newest... 
* Operating System:  win 10
* Mobile, Desktop, or Tablet: 
laptop
#### Your Code

```js
 
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  
.smaller-image {
width: 100px;
}
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

 
 
```

**Comment by Manish-Giri** [comment]
@bstonesifer Your code is incomplete. At the very least, you haven't applied the `smaller-image` class to the `img` element, which is why your image isn't resizing.

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) if you need assistance on this.

**Comment by bstonesifer** [comment]
been to the help room.. its not helpful..

**Comment by Manish-Giri** [comment]
@bstonesifer Feel free to PM me on gitter if you're still stuck.
