### ISSUE TITLE
No Codes..! Its abt boot sectors.....

### ISSUE THREAD

**Issue by saurabhsuman1206** [FreeCodeCamp/FreeCodeCamp#11641]
i have used various versions of linux on dual boot with windows..previously it used grub..! Currently with fedora i was unable to do it on same hard drive(some gpt partition issue).but i ws able to install it on ext hdd such that it boots into fedora with ext hdd connected and windows with hdd disconnected.No boot options available for either os...pls tell me how it happened and whats managing its boot sector priority.And can i hope to get an option if i install kali too on same ext hdd as fedora....(fedora is currently on full hdd). Thanks2 all.

**Comment by atjonathan** [comment]
@saurabhsuman1206, this repository is not for asking questions. Try asking this in our
[forum](http://forum.freecodecamp.com/) or [chat rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 😄 Good Luck!
