### ISSUE TITLE
Caesars Cipher: Correct Values are shown in console.log but still i cannot pass

### ISSUE THREAD

**Issue by hanhoah** [FreeCodeCamp/FreeCodeCamp#11659]
Challenge [Caesars Cipher](https://www.freecodecamp.com/challenges/caesars-cipher#?solution=%0Afunction%20rot13(str)%20%7B%20%2F%2F%20LBH%20QVQ%20VG!%0Avar%20res%3D%22%22%3B%09%0A%20%20for(var%20i%3D0%3Bi%3C%3Dstr.length%3Bi%2B%2B)%7B%0A%20%20%09if((str.charCodeAt(i)%3D%3D32)%7C%7C(str.charCodeAt(i)%3C%3D64))%0A%20%20%09%09delta%3Dstr.charCodeAt(i)%3B%0A%20%20%09else%20if((str.charCodeAt(i))%3E77)%0A%20%20%09%09delta%3Dstr.charCodeAt(i)-13%3B%0A%20%20%09else%20%0A%20%20%09%09delta%3Dstr.charCodeAt(i)%2B13%3B%0A%20%20%09res%2B%3DString.fromCharCode(delta)%3B%0A%20%20%7D%0A%20%20return%20res%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%0A%2F%2Frot13(%22SERR%22)%3B%0Aconsole.log(rot13(%22SERR%20PBQR%20PNZC%22))%3B%0Aconsole.log(rot13(%22SERR%20CVMMN!%22))%3B%0Aconsole.log(rot13(%22SERR%20YBIR%3F%22))%3B%0Aconsole.log(rot13(%22GUR%20DHVPX%20OEBJA%20QBT%20WHZCRQ%20BIRE%20GUR%20YNML%20SBK.%22))%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function rot13(str) { // LBH QVQ VG!
var res="";	
  for(var i=0;i<=str.length;i++){
  	if((str.charCodeAt(i)==32)||(str.charCodeAt(i)<=64))
  		delta=str.charCodeAt(i);
  	else if((str.charCodeAt(i))>77)
  		delta=str.charCodeAt(i)-13;
  	else 
  		delta=str.charCodeAt(i)+13;
  	res+=String.fromCharCode(delta);
  }
  return res;
}

// Change the inputs below to test
//rot13("SERR");
console.log(rot13("SERR PBQR PNZC"));
console.log(rot13("SERR CVMMN!"));
console.log(rot13("SERR YBIR?"));
console.log(rot13("GUR DHVPX OEBJA QBT WHZCRQ BIRE GUR YNML SBK."));


```

I made a test in my browser, and it delivers all the correct values, but still i don't pass.

**Comment by atjonathan** [comment]
@hanhoah, thanks for catching this, you are right, you code seems to be correct. This must be an issue with our tests. Tagging as `help wanted`.

**Comment by parisclinkscales** [comment]
This is a coding error. You are missing braces and there are too many parentheses for your if/else statements, and delta need to be a variable in your function. Also 77 should be 78.

**Comment by atjonathan** [comment]
@parisclinkscales, if I'm correct, you shouldn't need the missing braces. I don't see anything wrong with the parentheses either.

cc @FreeCodeCamp/moderators, this could be something I'm missing.

**Comment by rawgni** [comment]
`  for(var i=0;i<=str.length;i++){` should be `i < str.length`

**Comment by Bouncey** [comment]
What @rawgni said.

@hanhoah please ensure you have asked for help, or that someone could confirm the issue in the `Help` chatrooms before posting an issue on github. You can access the correct chatrrom for your challenge by clicking on the `Help` button in the side panel.

Closing as coding error.
