### ISSUE TITLE
size your images

### ISSUE THREAD

**Issue by aacheema** [FreeCodeCamp/FreeCodeCamp#1165]
Challenge http://www.freecodecamp.com/challenges/waypoint-size-your-images has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I set the width to 100px but there is still an X next to the objectives under "Go to my next challenge" (see bottom left of screenshot attached). 

![screen shot 2015-06-30 at 12 53 57 pm](https://cloud.githubusercontent.com/assets/9489610/8440463/295568aa-1f27-11e5-9f3a-206e46766ac9.png)

**Comment by aliaslam7163** [comment]
You have extra bracket

**Comment by aacheema** [comment]
I took it out but it still won't work

![screen shot 2015-06-30 at 1 36 22 pm](https://cloud.githubusercontent.com/assets/9489610/8441447/1d184926-1f2d-11e5-8df7-2ebd989afb0b.png)

**Comment by aacheema** [comment]
Thanks for helping me btw!

**Comment by 1hella** [comment]
Your browser looks like it's zoomed out. Try going back to normal size and try again. That's probably making the image less than 100 pixels.

**Comment by benschenker** [comment]
Closing as stale, please reopen if the issue is still present

**Comment by kmbgolf** [comment]
does it have to be tabbed in also?

**Comment by Martinbugayong** [comment]
Missing a semi-colon on line 24

**Comment by BrendonGS** [comment]
you don't need the backslash on line 24

**Comment by AliGrlk** [comment]
I have changed the order in style part as
`<style>
  .smaller-image {
      width:100px;
    
    
  .red-text {
    color: red;
   
    }
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>`

and it solved the problem for me.

**Comment by KaliiiIT** [comment]
It fixed for me to. But thats soo stupid why does it have to be in that order.It fucked up alot of shit for me.  I didnt know what to do

**Comment by SomBoy21** [comment]
Its really confusing

**Comment by spinderella360** [comment]
I'm having the same challenge right now. I'm stumped.

**Comment by septimius72** [comment]
same here.... code is fixed but it won't let me through.

**Comment by hmchaina** [comment]
``
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
 img {
    width: 100px;  
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class='smaller-image' src= "https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by hmchaina** [comment]
``
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
 img {
    width: 100px;  
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class='smaller-image' src= "https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by hmchaina** [comment]
[https://www.freecodecamp.com/challenges/size-your-images#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%20img%20%7B%0A%20%20%20%20width%3A%20100px%3B%20%20%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D'smaller-image'%20src%3D%20%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A](url)

**Comment by msj2** [comment]
I too struggled with this.

Later, I realised, img tag has class attribute
I placed
img class = "smaller-image"  


This solved the issue.
