### ISSUE TITLE
Run button missing on Say Hello to Elements challenge.

### ISSUE THREAD

**Issue by techdude619** [FreeCodeCamp/FreeCodeCamp#11658]
I am using Google Chrome Version 54.0.2840.71 (64-bit), Mac OSX Yosemite 10.10.4.

#### Challenge Name
Say Hello to Elements challenge

https://www.freecodecamp.com/challenges/say-hello-to-html-elements

#### Issue Description

I click on the Say Hello to Elements challenge and after scrolling to the bottom, the full instructions are missing and there lacks a submit button.

#### Browser Information

I am using Google Chrome Version 54.0.2840.71 (64-bit),
Mac OSX Yosemite 10.10.4.
Laptop

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```
#### Screenshot

http://i1255.photobucket.com/albums/hh631/techdude619/Screen%20Shot%202016-11-14%20at%2010.38.25%20AM_zps2e8yffdc.png

**Comment by systimotic** [comment]
Hi @techdude619! 
I can not reproduce this. Can you click the text from the description on the left, and then scroll down? There should be more text and a submit button below it. If the button is not there when you scroll down, can you please send another screenshot of what you do see?

_GitHub automatically uploads files if you drag and drop them into the textbox. If you're going to send a next screenshot, it would be wonderful if you could use that, as photobucket is overloaded with ads._

**Comment by techdude619** [comment]
I sent you a screenshot of what the bottom of the page looks like already.

**Comment by systimotic** [comment]
@techdude619 I saw that. I was asking:
> Can you click the text from the description on the left, and then scroll down? There should be more text and a submit button below it. If the button is not there when you scroll down, can you please send another screenshot of what you do see?
If that doesn't work, I'd love to hear that as well. The important part to note is that the description on the left should be scrollable separately from the main window.

**Comment by techdude619** [comment]
Yup. I can scroll it and see the submit button. 

Thank you for your help!

**Comment by systimotic** [comment]
Awesome, happy coding! 🎉 
I'm closing this issue as resolved.
