### ISSUE TITLE
Udacity Object Oriented Javascript

### ISSUE THREAD

**Issue by davisec52** [FreeCodeCamp/FreeCodeCamp#1166]
Challenge http://www.freecodecamp.com/challenges/waypoint-build-objects-with-functional-classes has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

This is essentially feedback. The Udacity videos selected for the Object Oriented Javascript section cover the material too quickly and too abstractly to be easily grasped by those--in my opinion--who do not already have a firm understanding of the material. The moderator sounds as if he is on speed, and the examples used are too abstract to be easily duplicatable by the viewer.

Speaking for myself, the positive side of the Udacity (appropriate expletive forsaken) is that I know what FCC wants me to cover. I can now buy the books and/or relevant courses from Udemy or Frontend Masters that cover the same material in a humane fashion.

**Comment by FFX01** [comment]
I agree with you. Luckily, I already know most of what the Udacity courses go over. However, if I didn't I would have a very difficult time trying to understand what the video is trying to explain. I feel like there may be a better alternative available. I'll update this post if I find one.

**Comment by davisec52** [comment]
As an addendum, the following links to Aadit Shah's page and the MDN documentation on Object.prototype have helped me: http://aaditmshah.github.io/why-prototypal-inheritance-matters/#constructors_vs_prototypes, and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/prototype.  These are difficult, but working through the examples with repl.it or Chrome dev tools has been helpful.

**Comment by FFX01** [comment]
@davisec52 Those are very informative articles. They really help explain how object inheritance can work in a lot of different ways.

**Comment by BerkeleyTrue** [comment]
Udacity has been removed!

Happy Coding!
