### ISSUE TITLE
Console is showing correct answer , But the challenge is not accepting 

### ISSUE THREAD

**Issue by harsha-kumar** [FreeCodeCamp/FreeCodeCamp#11667]
Challenge [Chaining If Else Statements](https://www.freecodecamp.com/challenges/chaining-if-else-statements#?solution=%0Afunction%20testSize(num)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20if(num%3C5)%7B%0A%20%20%20%20return%20%22Tiny%22%3B%0A%20%20%7D%0A%20%20%20%20else%20if(num%3C10)%7B%0A%20%20%20%20%20%20return%22Small%22%3B%0A%20%20%20%20%7D%0A%20%20%20%20%20%20else%20if(num%3C15)%7B%0A%20%20%20%20%20%20%20%20return%22medium%22%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20else%20if(num%3C20)%7B%0A%20%20%20%20%20%20%20%20return%22Large%22%3B%0A%20%20%20%20%20%20%7D%0A%20%20else%20if(num%3E%3D20)%7B%0A%20%20%20%20%20%20%20%20return%22Huge%22%3B%0A%20%20%20%20%20%20%7D%7D%0AtestSize(14)%3B%0A%20%20%0A%20%20%2F%2Freturn%20%22nothing%22%3B%0A%20%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testSize(num) {
  // Only change code below this line
  
  if(num<5){
    return "Tiny";
  }
    else if(num<10){
      return"Small";
    }
      else if(num<15){
        return"medium";
      }
    else if(num<20){
        return"Large";
      }
  else if(num>=20){
        return"Huge";
      }}
testSize(14);
  
  //return "nothing";
 

// Change this value to test


```

**Comment by harsha-kumar** [comment]
Sorry For wrong Post i Got it its a Cookies issue Thanks @FreeCodeCamp love u lots ... because of people i am learning and enjoying .

**Comment by raisedadead** [comment]
thanks @harsha-kumar happy coding.
