### ISSUE TITLE
Modify instruction in Challenge Comparison with the Greater Than Or Equal To Operator

### ISSUE THREAD

**Issue by 1810msr** [FreeCodeCamp/FreeCodeCamp#11662]
Challenge [Comparison with the Greater Than Or Equal To Operator](https://www.freecodecamp.com/challenges/comparison-with-the-greater-than-or-equal-to-operator#?solution=%0Afunction%20testGreaterOrEqual(val)%20%7B%0A%20%20if%20(val%20%3E%3D%20'20')%20%7B%20%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%2220%20or%20Over%22%3B%0A%20%20%7D%0A%20%20%0A%20%20if%20(val%20%3E%3D%2010)%20%7B%20%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%2210%20or%20Over%22%3B%0A%20%20%7D%0A%0A%20%20return%20%229%20or%20Under%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestGreaterOrEqual(9.999999999999999)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testGreaterOrEqual(val) {
  if (val >= '20') {  // Change this line
    return "20 or Over";
  }
  
  if (val >= 10) {  // Change this line
    return "10 or Over";
  }

  return "9 or Under";
}

// Change this value to test
testGreaterOrEqual(9.999999999999999);

```
![image](https://cloud.githubusercontent.com/assets/23392198/20287623/3ee7af28-ab19-11e6-969d-45d13d90648f.png)

ISSUE:
the above code returns "9 or under" string as the result which is misleading or does not sound right when we use testGreaterOrEqual(9.999999999999999); as the input.

**Comment by IsaacAbrahamson** [comment]
It should be "Less than 10"

**Comment by erictleung** [comment]
Using "Less than 10" *may* confuse some people to think it includes 10. Another (arguably simpler) workaround is to mention that the function assumes the input to be integers. That way you only have to add text rather than change two test texts and the seed code. Either way, works for me.

**Comment by Manish-Giri** [comment]
I'd be interested in making this change, if it needs to be done. I also think that adding an assumption about integer inputs would be better, just my two cents.

**Comment by abhisekp** [comment]
@erictleung how about adding these type of documentation?

```js
/*
 * @name testGreaterOrEqual
 * @param {number} val Integer number
 */
function testGreaterOrEqual(val) {
```

**Comment by erictleung** [comment]
@abhisekp I like it but I don't think this would be the place to introduce that. We'd have to introduce them way earlier and change all of the challenges. So I don't think there would be too much to gain from adding them. But I'm up for discussion on it.

Maybe for the intermediate and advanced algorithms that would be a clean and nice way to specify the parameters.

**Comment by abhisekp** [comment]
Considering the challenge https://www.freecodecamp.com/challenges/comparison-with-the-less-than-or-equal-to-operator with issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11663 and the current issue, I think it is better to just modify the challenge seed. 

i.e. the challenge seed should read `"Less than 10"`.

**Comment by billywaite** [comment]
I'd like to take a crack at this, i've never contributed before.

**Comment by MFogleman** [comment]
I don't want to steal anyone's thunder, but its been a few days since @billywaite said he was gonna attempt it.  I'm going to throw my hat into the ring as well and attempt it.
