### ISSUE TITLE
playerNumber should be a number___You should be using the variable playerNumber in your bracket notation

### ISSUE THREAD

**Issue by dashark69** [FreeCodeCamp/FreeCodeCamp#11661]
Challenge [Accessing Objects Properties with Variables](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables#?solution=%0A%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%2012%3A%20%22Namath%22%2C%0A%20%2016%3A%20%22Montana%22%2C%0A%20%2019%3A%20%22Unitas%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%3B%0A%0Avar%20playerNumber%20%3DtestObj%5B16%5D%3B%20%20%2F%2F%20Change%20this%20Line%0Avar%20player%20%3D%20testObj%5B16%5D%3B%20%20%20%2F%2F%20Change%20this%20Line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};

// Only change code below this line;

var playerNumber = testObj[16];  // Change this Line
var player = testObj[16];   // Change this Line

```

Hello Freecode camp team.  I tried to get help on  the help forum and I believe this is what they are asking.. I  think this part has a bug? 

var playerNumber=testObj[16];

whilre var  " player" works great.  The issue is with  var playerNumber .

Please advise ?

**Comment by Dave1089** [comment]
@dashark69 , there is not bug in the challenge, please read instruction example carefully to understand what challenge wants you to do 

```
var myDog = "Hunter";
var dogs = {
  Fido: "Mutt",
  Hunter: "Doberman",
  Snoopie: "Beagle"
}
var breed = dogs[myDog];
console.log(breed);// "Doberman"
```

If you don't understand the challenge, please ask for help in the [chatroom](https://gitter.im/FreeCodeCamp/Help)

**Comment by dashark69** [comment]
Thanks Dave for checking.. the old Light Bulb just worked in my head..  what I mean to say.. you are correct.. i just learned to think again.. thanks for your time.. I got it.. :-) !! :-)..
