### ISSUE TITLE
Concatenating Strings with Plus Operator

### ISSUE THREAD

**Issue by chengnmee** [FreeCodeCamp/FreeCodeCamp#11671]
#### Challenge Name

Concatenating Strings with Plus Operator

#### Issue Description

"Watch out for spaces. Concatenation does not add spaces between concatenated strings, so you'll need to add them yourself."

This notice is good to understand but according to the example given and the instruction there is a difference in spacing between the comma or period inside the quotations and the quotation mark.  However I am unsure because the example uses the single quotation while the instruction uses the double quotations.  But I did the challenge by trying out the single and double quotations and the problem I face is still the spacing between the comma and the quotation.  Maybe fix the instructions to show that you have to space the period and the quotations to work or either the challenge is bugged.

Example:
'My name is Alan,(no space here)' + ' I concatenate.'

Instruction:
"This is the start.(spacing here)" + "This is the end." 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
<-- The Example and Instructions -->
'My name is Alan,<-- no spacing here -->' + ' I concatenate.'

"This is the start.<-- spacing here --> " + "This is the end." 

<-- The Challenge That Works -->
 // Example
var ourStr = "I come first.<--spacing here -->" + "I come second.";

// Only change code below this line

var myStr = 'This is the start.<-- spacing here -->' + 'This is the end.';

 
 
```

**Comment by dhcodes** [comment]
@chengnmee The key statement is:
> Concatenation does not add spaces between concatenated strings.

Also, there is an example in the exercise of a string that has a space at the end within the quotation marks (").

I'm open to suggestions on how to make it more understandable but I think it is pretty clear as it is.

**Comment by avirajkhare00** [comment]
Still I am unable to get difference between using single quote and double quote.
Here is SO question that discusses the same - http://stackoverflow.com/questions/242813/when-to-use-double-or-single-quotes-in-javascript
Double quotes is preferred specially in JSON.

**Comment by dhcodes** [comment]
@avirajkhare00 the first post in the thread you posted correctly says it only matters based on consistency through your program. A string can be made with " or ' and a string is a string regardless of which you use. Closing this. Please reopen @chengnmee if you have a suggestion for improving the wording.
