### ISSUE TITLE
Bonfire: Inventory Update will not mark as complete

### ISSUE THREAD

**Issue by webdevdave** [FreeCodeCamp/freecodecamp#1167]
Challenge http://www.freecodecamp.com/challenges/bonfire-inventory-update has an issue.

The code I submitted passes every test, but the completion popup never appears, and the bonfire is never marked completed on my map.  Here is the code:
```
function inventory(arr1, arr2) {
  // All inventory must be accounted for or you're fired!
  function arrToObj(arr) {
    var obj = {};
    arr.forEach(function(x) {
      obj[x[1]] = x[0];
    });
    return obj;
  }
  function objToArr(obj) {
    arr = [];
    for (var key in obj) {
      arr.push([obj[key], key]);
    }
    return arr;
  }
  var obj1 = arrToObj(arr1),
      obj2 = arrToObj(arr2);
  for (var key in obj2)
    obj1[key] = obj2[key];
  return objToArr(obj1).sort(function(a, b) { return a[1] > b[1]; });
}
```

Here is a screenshot:
![bonfirebug](https://cloud.githubusercontent.com/assets/1404344/8445122/b5ccfc58-1f5e-11e5-94e7-7c7b9d7f7a71.png)

I have tried completing the challenge in a new incognito tab with no extensions enabled, but the problem persists.  Someone from the Help chat got the same bug when they tried using my code.

**Comment by 1hella** [comment]
Yeah you're right. Everything is showing up passing with that code.

However, when I run it with the default code:
```
// Example inventory lists
var curInv = [
    [21, 'Bowling Ball'],
    [2, 'Dirty Sock'],
    [1, 'Hair Pin'],
    [5, 'Microphone']
];

var newInv = [
    [2, 'Hair Pin'],
    [3, 'Half-Eaten Apple'],
    [67, 'Bowling Ball'],
    [7, 'Toothpaste']
];

inventory(curInv, newInv);
```

Your output is this: 
![image](https://cloud.githubusercontent.com/assets/6580703/8448794/25c70cf8-1f80-11e5-864a-642f339576e3.png)

When it should be this: 
![image](https://cloud.githubusercontent.com/assets/6580703/8448869/fed63d2a-1f80-11e5-987e-78d5def38a68.png)

Your value for bowling ball is 67 when it should be 88. For some reason, it's not failing the test when it should be.

I get the same result when I print each item of the resulting array out to the console. Inventory is the result of running your code, while inventory1 is from mine: 
![image](https://cloud.githubusercontent.com/assets/6580703/8448948/b4586042-1f81-11e5-9006-4bc3ae0b0369.png)

So for some reason, the test is passing when it should be failing. It's not clear why, but that should at least help you pass the bonfire now that you know what's wrong.

**Comment by gmcclure** [comment]
Testing is wonky on the Bonfire: https://github.com/FreeCodeCamp/freecodecamp/issues/1327

**Comment by zerodot** [comment]
I'm having the same issue with the following code. All tests pass, but the bonfire is never marked completed.

```
function inventory(arr1, arr2) {
  return arr2.reduce(update,arr1.reduce(update,{})).toArray().sort(invSort);
}

function update(acc,e){
  var ans=acc;
  if (ans[e[1]]===undefined) ans[e[1]]=e[0];
  else ans[e[1]]+=e[0];
  return ans;
}

Object.prototype.toArray = function(){
  var ans=[];
  for (var key in this){
    ans.push([this[key],key]);
  }
  return ans.slice(0,-1);
};

function invSort(a,b){
  if (a[1]<b[1]) return -1;
  if (a[1]===b[1]) return 0;
  return 1;
}

// Example inventory lists
var curInv = [
    [21, 'Bowling Ball'],
    [2, 'Dirty Sock'],
    [1, 'Hair Pin'],
    [5, 'Microphone']
];

var newInv = [
    [2, 'Hair Pin'],
    [3, 'Half-Eaten Apple'],
    [67, 'Bowling Ball'],
    [7, 'Toothpaste']
];

inventory(curInv, newInv);
```

**Comment by BerkeleyTrue** [comment]
Hello @webdevdave 

You code is incorrect and currently does not pass all the test. Please try the 'help' chat when you stuck. 

@zerodot This is a good example of why you should never... ever... modify primitive prototypes. Modifying object prototype is having some side effect that breaks things. In functional programming it is most important that your code not have side effects. Modifying the prototype is a side effect.


Happy Coding!

**Comment by asm-jaime** [comment]
```
function inventory(arr1, arr2) {
    var trigger = 0;
    arr2.forEach(function(e2){
        arr1.forEach(function(e1){
            if(e1[1]==e2[1]){
                trigger = 1;
                e1[0] = e2[0]+e1[0];
            }
        });
        if(trigger == 0){
            arr1.push(e2);
        }else{
            trigger = 0;
        }
        //console.log(e1);
    });
    arr1.sort(function(e11,e12){
        if(e11[1] < e12[1])return false;
        return true;
    })
    // All inventory must be accounted for or you're fired!
    return arr1;
}
// Example inventory lists
var curInv = [
    [21, 'Bowling Ball'],
    [2, 'Dirty Sock'],
    [1, 'Hair Pin'],
    [5, 'Microphone']
];

var newInv = [
    [2, 'Hair Pin'],
    [3, 'Half-Eaten Apple'],
    [67, 'Bowling Ball'],
    [7, 'Toothpaste']
];

console.log(inventory([[21, 'Bowling Ball'], [2, 'Dirty Sock'], [1, 'Hair Pin'], [5, 'Microphone']], [[2, 'Hair Pin'], [3, 'Half-Eaten Apple'], [67, 'Bowling Ball'], [7, 'Toothpaste']]));
```
correct example?

**Comment by tamerMarzouk** [comment]
I had my code running correctly and returning the correct results, yet it was not marked as success. I just changed the name of the object to be a global variable and cleared to make sure it is empty in the first line of the updateInventory function, the code just succeeded.

**Comment by tamerMarzouk** [comment]
I had my code running correctly and returning the correct results, yet it was not marked as success. I just changed the name of the object to be a global variable and cleared to make sure it is empty in the first line of the updateInventory function, the code just succeeded.
