### ISSUE TITLE
DNA Pairing - Correct, but incorrect.

### ISSUE THREAD

**Issue by zombat** [FreeCodeCamp/FreeCodeCamp#11677]
Challenge [DNA Pairing](https://www.freecodecamp.com/challenges/dna-pairing#?solution=%0Afunction%20pairElement(str)%20%7B%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20%20%20str.split('').forEach(function(element)%7B%0A%20%20%20%20%20%20switch%20(element)%7B%0A%20%20%20%20%20%20%20%20case%20%22A%22%3A%0A%20%20%20%20%20%20%20%20%20%20arr.push(%5B%22A%2CT%22%5D)%3B%0A%09%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20case%20%22T%22%3A%0A%20%20%20%20%20%20%20%20%20%20arr.push(%5B%22T%2CA%22%5D)%3B%0A%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20case%20%22C%22%3A%0A%20%20%20%20%20%20%20%20%20%20arr.push(%5B%22C%2CG%22%5D)%3B%0A%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20case%20%22G%22%3A%0A%20%20%20%20%20%20%20%20%20%20arr.push(%5B%22G%2CC%22%5D)%3B%0A%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D)%3B%0A%20%20return%20arr%3B%0A%7D%0A%0ApairElement(%22CTCTA%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

pairElement("ATCGA") does return [["A","T"],["T","A"],["C","G"],["G","C"],["A","T"]].
pairElement("TTGAG") does  return [["T","A"],["T","A"],["G","C"],["A","T"],["G","C"]].
pairElement("CTCTA") does return [["C","G"],["T","A"],["C","G"],["T","A"],["A","T"]].

My code:
```javascript

function pairElement(str) {
  var arr = [];
    str.split('').forEach(function(element){
      switch (element){
        case "A":
          arr.push(["A,T"]);
	      break;
        case "T":
          arr.push(["T,A"]);
          break;
        case "C":
          arr.push(["C,G"]);
          break;
        case "G":
          arr.push(["G,C"]);
          break;
      }
    });
  return arr;
}

pairElement("CTCTA");

```

**Comment by robbawebba** [comment]
There is an issue with your code submission. Pay careful attention to the items you are pushing onto the array `arr` in the switch statement, and how thye differ from the array items in the expected results for the tests. Feel free to ask [this chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need help!

**Comment by zombat** [comment]
This has been a coffee and glasses moment...
