### ISSUE TITLE
Factorialize a Number

### ISSUE THREAD

**Issue by jdavis4989** [FreeCodeCamp/FreeCodeCamp#11679]
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#?solution=%20%20var%20poop%20%3D%201%3B%0Afunction%20factorialize(num)%20%7B%0A%0A%20%20for%20(var%20i%3D1%3B%20i%20%3C%3D%20num%3B%20i%2B%2B)%7B%0A%20%20%20%20%20poop*%3Di%3B%0A%20%20%7Dreturn%20poop%3B%7D%0A%20%20%0A%0Afactorialize(20)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Can someone please explain why this won't let me pass?  All of the scenarios are correct when I check them.

My code:
```javascript
  var poop = 1;
function factorialize(num) {

  for (var i=1; i <= num; i++){
     poop*=i;
  }return poop;}
  

factorialize(20);

```

**Comment by erictleung** [comment]
@jdavis4989 thanks for the issue. The tests are run sequentially right after each other so any global variables changed will change with each test run. Put your global variable within your function and it should pass. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by jdavis4989** [comment]
That did it!

Thanks Eric!
