### ISSUE TITLE
Back End layout issue with Cat Photo App

### ISSUE THREAD

**Issue by gViro** [FreeCodeCamp/FreeCodeCamp#11678]
#### Responsive Design With Bootstrap

[Link to challenge](https://www.freecodecamp.com/challenges/responsively-style-checkboxes)

#### Issue Description

The first checkbox's label, "Loving", drops down to a new line. To me, it looks odd and appears as though the assignment is incorrect or that something is wrong with the student's code. 

A student may hack this by removing the leading space before "Loving", but then it won't visually match the other two checkbox labels, both of which have spaces to separate them from the actual checkbox itelf. 

Perhaps shortening the actual word from "Loving" to "Kind" or "Calm" would be an easy fix?

#### Browser Information

Appears in current versions of Chrome and Firefox. Not tested in any other browsers. Only tested on desktop. 

 #### Screenshot

![overflow](https://cloud.githubusercontent.com/assets/2657301/20356052/6c881b74-abf1-11e6-848a-dc3933295b8c.jpg)

![nospace](https://cloud.githubusercontent.com/assets/2657301/20356060/72e610e8-abf1-11e6-84d0-365c89c0f01b.jpg)

![newword](https://cloud.githubusercontent.com/assets/2657301/20356070/77239004-abf1-11e6-90ac-5c4de57c88fa.jpg)

**Comment by CEREBR4L** [comment]
@gViro Should be an easy fix but I am not seeing it happen on my end (chrome/macbook). Can you post the code you have put in to get this as well.

**Comment by erictleung** [comment]
@gViro thanks for the issue. This is related to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7842 and is also exactly like this comment here https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7842#issuecomment-219094672. Closing as duplicate. Feel free to continue the conversation over there. Happy coding!

**Comment by gViro** [comment]
thanks @erictleung , I've edited my FCC forum post to reflect this. 
Apologies for not checking in this repo first.
Glad to hear FCC repo is in the top FIVE!!!
