### ISSUE TITLE
ERROR! ERROR! ERROR! **Learning To Code. Please Help**

### ISSUE THREAD

**Issue by amhemesh** [FreeCodeCamp/FreeCodeCamp#11676]
Challenge [Use RGB values to Color Elements](https://www.freecodecamp.com/challenges/use-rgb-values-to-color-elements#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20rgb(255%2C%20165%2C%200)%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: rgb(255, 165, 0);
  }
</style>

```
![screenshot](https://cloud.githubusercontent.com/assets/23469822/20342741/a3780a5c-ac11-11e6-977a-85ff0592ae11.png)

**In the above mentioned code and picture you can see that i've done exactly what was said, yet the background of the Body remained yellow! Which was to be changed to black. Please fix this issue as soon as possible.**
_**Thank You**_

**Comment by Jeff-Shapiro** [comment]
The instructions stat what is required. The code you have put is as an example for you to learn off. Please use the forum or chat if you require help.

**Comment by amhemesh** [comment]
**Is this an answer to my question?** 
If yes, then am sorry I didn't get you answer!

**Comment by yaditya** [comment]
**black** should be `rgb(0, 0, 0)`
