### ISSUE TITLE
haha..simplest ad dummest but not woking

### ISSUE THREAD

**Issue by cppmember95** [FreeCodeCamp/FreeCodeCamp#11672]
Challenge [Returning Boolean Values from Functions](https://www.freecodecamp.com/challenges/returning-boolean-values-from-functions#?solution=%0Afunction%20isLess(a%2C%20b)%20%7B%0A%20%20%2F%2F%20Fix%20this%20code%0A%20return%20(a%3D%3D%3Db)%3B%0A%20%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AisLess(10%2C%2015)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.9.3.1000 Chrome/39.0.2146.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function isLess(a, b) {
  // Fix this code
 return (a===b);
 
}

// Change these values to test
isLess(10, 15);

```

**Comment by Manish-Giri** [comment]
@cppmember95 Your code is incorrect - you're supposed to test if the first number is lesser than the second number. Using the `===` operator just checks if the two numbers are equal (instead), and returns `true` or `false` accordingly.

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) if you need assistance with this.

**Comment by IsaacAbrahamson** [comment]
I am closing this issue. If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by NZY1337** [comment]
function isLess(a, b) {
  // Fix this code
 return a < b;
 
}

// Change these values to test
isLess(10, 15);
