### ISSUE TITLE
Test crowdin localization on a local copy of FCC

### ISSUE THREAD

**Issue by CodeNonprofit** [freeCodeCamp/freeCodeCamp#11674]
https://crowdin.com/

This product seems to offer free open source licenses. We are curious how this localization management tool would work on Free Code Camp. 

There's a free trial. Instead of a pull request, we are looking for someone to create a short screencast that shows the functionality running on localhost.

**Comment by omps** [comment]
I am interested to pick this up, but I am not really sure about the exact requirement, can you pass me some sample info or any link like which you want to use the above case.

**Comment by leonfeng** [comment]
Is this still up for grabs? I signed up for a free CrowdIn account and played with some of the features. Should be able to put together a video to show the basic workflow in a couple of hours.
