### ISSUE TITLE
Code running but task won't complete [Testing Objects for Properties]

### ISSUE THREAD

**Issue by Janox85** [FreeCodeCamp/FreeCodeCamp#11685]
Challenge [Testing Objects for Properties](https://www.freecodecamp.com/challenges/testing-objects-for-properties) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  if (myObj.hasOwnProperty(checkProp)){
  return myObj[checkProp];
  } else{
  return "Not found";
  }
}

// Test your code by modifying these values
checkObj("gift");

```
As you can see, the code will run and return appropriately but the task "_checkObj("house") should return "Not Found"_" won't change from red to green and therefore will show as uncompleted.

**Comment by systimotic** [comment]
Hi @Janox85! Thank you for reporting this issue.
This is not an issue with Free Code Camp, rather an issue in your code. The capitalization in your error is wrong.
If you need coding help, please click the "Help" button on the challenge. The issue tracker is not for coding help.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. 
Happy coding!
