### ISSUE TITLE
CSS issue with 13" (1280 x 659) viewports.

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#11687]
Device:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36`

Viewport : 1280 x 659

Issue :
![image](https://cloud.githubusercontent.com/assets/1884376/20395163/ffea3098-ad07-11e6-810e-44f1529a6a71.png)

This almost made be believe that the url is actually `.co` instead of a `.com`

**Comment by raisedadead** [comment]
this must go against the `backup/master` and `staging` branches

**Comment by erictleung** [comment]
We could use either `<wbr>` (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) or an `overflow-wrap` (https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap). Previously for this kind of issue, we used the `<wbr>`. I haven't used `overflow-wrap`, but the example on MDN could make for a more long-term solution without having to manually add in `<wbr>` breaks in long word.

![image](https://cloud.githubusercontent.com/assets/2754821/20413583/910f2da6-ace2-11e6-9605-7998615f558b.png)

**Comment by chiptus** [comment]
I'm on it. 
I'm adding this rule to the .test-output class. It's working on the staging branch, should I do the change to master branch as well?

**Comment by raisedadead** [comment]
@chiptus thanks a lot for looking into this.
>  should I do the change to master branch as well?

Yes.
> this must go against the `backup/master` and `staging` branches
