### ISSUE TITLE
ternary operator allowed to solve this where switch statement should be used

### ISSUE THREAD

**Issue by darkflikk** [FreeCodeCamp/FreeCodeCamp#11688]
It tests for if statements to prevent me from using those.
But it does not prevent me from using ternary operator as i did in this challenge.

Challenge [Multiple Identical Options in Switch Statements](https://www.freecodecamp.com/challenges/multiple-identical-options-in-switch-statements#?solution=%0Afunction%20sequentialSizes(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20answer%20%3D%20(val%20%3E%3D%201%20%26%26%20val%20%3C%3D%203)%20%3F%20%22Low%22%20%3A%20answer%3B%0A%20%20answer%20%3D%20(val%20%3E%3D%204%20%26%26%20val%20%3C%3D%206)%20%3F%20%22Mid%22%20%3A%20answer%3B%0A%20%20answer%20%3D%20(val%20%3E%3D%207%20%26%26%20val%20%3C%3D%209)%20%3F%20%22High%22%20%3A%20answer%3B%0A%20%20switch%20(null)%20%7B%0A%20%20%20%20case%20''%3Acase%20''%3Acase%20''%3Acase%20''%3Acase%20''%3Acase%20''%3Acase%20''%3Acase%20''%3Acase%20''%3A%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AsequentialSizes(1)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function sequentialSizes(val) {
  var answer = "";
  // Only change code below this line
  
  answer = (val >= 1 && val <= 3) ? "Low" : answer;
  answer = (val >= 4 && val <= 6) ? "Mid" : answer;
  answer = (val >= 7 && val <= 9) ? "High" : answer;
  switch (null) {
    case '':case '':case '':case '':case '':case '':case '':case '':case '':
  }
  
  // Only change code above this line  
  return answer;
}

// Change this value to test
sequentialSizes(1);


```

**Comment by systimotic** [comment]
Nice work @darkflikk! 😄 Thanks for reporting this issue.
I'm not sure if we should fix this, as we don't talk about ternary operators before this challenge. 
Adding tests for ternary operators could potentially break other things. I think the easiest way to check it would be to simply look for question marks, possibly also for a colon after it separated by some spaces and word characters, but that could mess things up with text in comments again.
@FreeCodeCamp/moderators Any input?

**Comment by erictleung** [comment]
@darkflikk kudos on your efficient solution! For the intended audience and what the challenge is teaching, I don't think there should be any changes. The challenge here is to teach the concept of `switch` statements versus using `if` statements. Although I don't like the idea of a challenge hindering an individual's creativity in coding up a solution, I think this challenge is sufficient to just teach `switch` statements and there's no need to account for ternary solutions.

**Comment by Bouncey** [comment]
Just to add on the comments made by @erictleung and @systimotic, a lot of effort has gone in to navigating the tests so that the challenge passes with a ternary instead.

**Comment by systimotic** [comment]
Thanks again for reporting the issue @darkflikk! It is very much appreciated.
Happy coding!
