### ISSUE TITLE
Link to jQuery's $.getJSON() leads to jQuery.each()

### ISSUE THREAD

**Issue by 1hella** [FreeCodeCamp/freecodecamp#1169]
Challenge http://www.freecodecamp.com/challenges/zipline-use-the-twitch.tv-json-api has an issue.

Link is to http://api.jquery.com/jquery.each/ where it should be http://api.jquery.com/jquery.getjson/ like in the previous waypoint.

Screenshot of the source code:
![image](https://cloud.githubusercontent.com/assets/6580703/8449982/2ac5773e-1f8b-11e5-92d2-92c816608f0b.png)

Screenshot from Waypoint: Get Set for Ziplines:
![image](https://cloud.githubusercontent.com/assets/6580703/8450001/4e28de0a-1f8b-11e5-847a-c0922fdfd793.png)

**Comment by LumenTeun** [comment]
This was fixed in #937, but thank you for reporting.

**Comment by 1hella** [comment]
Great, thanks. I'll close this issue in that case.
