### ISSUE TITLE
Link in the instructions doesn't open in new tab

### ISSUE THREAD

**Issue by tomosuto** [FreeCodeCamp/FreeCodeCamp#11693]
#### Challenge Name

[Record Collection](https://www.freecodecamp.com/challenges/record-collection)

#### Issue Description

The External links to "Mozilla Developer Network" and  "Manipulating Complex Objects" in the instructions opens in the same tab instead of new tab.

**Comment by erictleung** [comment]
@tomosuto thanks for the issue. I can confirm for both links. [Here is the code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/91f7ea6dca5bf3df98a9f0598f303e781e3f3f30/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4915-L4917) for those links. What odd is that all three links on that page have `target="_blank"`, but only the first opens in a new tab.

@FreeCodeCamp/moderators any ideas?

**Comment by tomosuto** [comment]
@erictleung Thanks. I looked through it and thought the same thing I don't know what the issue is...

**Comment by abhisekp** [comment]
The `master` branch doesn't have `target="_blank"`. But it has been fixed in `staging` branch.
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/master/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4910-L4912
