### ISSUE TITLE
Not passing on "release year"

### ISSUE THREAD

**Issue by jdice226** [FreeCodeCamp/FreeCodeCamp#11697]
Challenge [Manipulating Complex Objects](https://www.freecodecamp.com/challenges/manipulating-complex-objects#?solution=%0Avar%20myMusic%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Billy%20Joel%22%2C%0A%20%20%20%20%22title%22%3A%20%22Piano%20Man%22%2C%0A%20%20%20%20%22release_year%22%3A%201973%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CS%22%2C%20%0A%20%20%20%20%20%20%228T%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%0A%20%20%20%20%22gold%22%3A%20true%0A%20%20%7D%20%2C%0A%20%7B%0A%20%20%20%22artist%22%3A%20%22Lee%20Brice%22%2C%0A%20%20%20%22title%22%20%3A%20%22I%20Don't%20Dance%22%2C%0A%20%20%20%22release%20year%22%20%3A%202015%2C%0A%20%20%20%22formats%22%20%3A%20%5B%0A%20%20%20%20%20%22Groove%22%2C%0A%20%20%20%20%20%22Amazon%20MP3%22%2C%0A%20%20%20%20%20%22iTunes%22%2C%0A%20%20%20%20%20%22CD%22%5D%2C%0A%20%7D%20%2F%2F%20Add%20record%20here%0A%20%5D%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

"myMusic[1] should contain a release_year property which is a number" This requirement is not passing. In my code I have "release year" : 2015, so I have a number. Not sure what the problem is. 

My code:
```javascript

var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  } ,
 {
   "artist": "Lee Brice",
   "title" : "I Don't Dance",
   "release year" : 2015,
   "formats" : [
     "Groove",
     "Amazon MP3",
     "iTunes",
     "CD"],
 } // Add record here
 ];


```

**Comment by jdice226** [comment]
I did try to take away the last comma after "CD"] but it still didn't pass.

**Comment by Manish-Giri** [comment]
@JacksonBates Look at the instruction - 

> Add artist and title strings, release_year number, and a formats array of strings

`release_year` should have underscore in between, while you have a space in your code.

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) for help with issues in your code. Happy Coding!

**Comment by erictleung** [comment]
@jdice226 Thank you for reporting this issue. Your code is incorrect. Please note the underscore in the `release_year`.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by jdice226** [comment]
It worked thank you for pointing that out. I will have to be more careful and double check things like that. Thank you!
