### ISSUE TITLE
 this coding

### ISSUE THREAD

**Issue by cnrgng** [FreeCodeCamp/FreeCodeCamp#11691]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20%0A%20%20return%20item%3B%20%20%2F%2F%20Change%20this%20line%0A%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20arr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(arr))%3B%0Aconsole.log(nextInLine(testArr%2C%206))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(arr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function nextInLine(arr, item) {
  // Your code here
  
  return item;  // Change this line

}

// Test Setup
var arr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(arr));
console.log(nextInLine(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(arr));

```

**Comment by cnrgng** [comment]
this coding

**Comment by Manish-Giri** [comment]
@cnrgng If you need help in completing the challenge, please visit the [Help](https://gitter.im/FreeCodeCamp/Help) room or the [HelpJavaScript](https://gitter.im/FreeCodeCamp/HelpJavaScript) room.

**Comment by systimotic** [comment]
Hi @cnrgng!
As Manish said, the Help rooms are the place to get coding help. To make sure you end up in the right place, please use the "Help" button in the challenge.
The issue tracker is meant for bugs, things that are wrong with Free Code Camp.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. 
Happy coding!
