### ISSUE TITLE
I'm unable to move on to the next challenge and I've uncommented . 

### ISSUE THREAD

**Issue by Dionne97** [FreeCodeCamp/FreeCodeCamp#11700]
#### Issue Description

I'm failing to move on to the next challenge

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 
I'm using my mobile phone it's an Iphone5
#### Your Code

```js
 <!--
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
-->
 
 
```

**Comment by systimotic** [comment]
Hi @Dionne97! Thanks for reporting this issue.
In order for us to be able to help you, we need to know the challenge name.

If you're looking for coding help, try pressing the "Help" button on the challenge instead. You'll be taken to a chatroom where there will be people ready to help you.

**Comment by systimotic** [comment]
If you think I'm wrong in closing this issue, please reopen it and add further clarification.
Happy coding!
