### ISSUE TITLE
Move "Uncomment HTML" challenge past the "Comment out HTML" challenge

### ISSUE THREAD

**Issue by BrewCoffeeSplash** [FreeCodeCamp/FreeCodeCamp#11701]
Challenge  [Uncomment HTML](https://www.freecodecamp.com/challenges/uncomment-html) has an issue. 
User Agent is: 
<code>Mozilla/5.0  Windows NT 6.1; WOW64; rv:49.0  Gecko/20100101 Firefox/49.0 </code>

Please describe how to reproduce this issue, and include links to screenshots if possible. 
My code:   
 
html h1>Hello World /h1> h2>CatPhotoApp /h2> p>Hello Paragraph /p>     

Had someone confused as to why the challenge teaches you to add comments, but then asks you to uncomment.  Had some people confused thinking they need to comment out something.  The next challenge then wants to to comment out parts of the code.

**Comment by avirajkhare00** [comment]
@BrewCoffeeSplash Uncommenting code is much easier then commenting it out. I don't think so that users may be facing any problems regarding it.

**Comment by raisedadead** [comment]
@BrewCoffeeSplash i am not sure if i understand your code or the issue correctly. Can you please explain a bit further. 

I formatted your issue description a bit, but would be great if you could add the code that you actually used once again with proper formatting as well.

**Comment by Rashidow** [comment]
hi, how do Uncomment this <h1>Hello World</h1> Please.

**Comment by texas2010** [comment]
@Rashidow 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by IlonaF** [comment]
I did get a bit confused too, as to why we are being asked to uncomment elements, rather than comment them out first, but I guess @avirajkhare00 post make sense... Maybe it confused me because I am already familiar with comments.
