### ISSUE TITLE
Confirm The Ending. confirmEnding("Open sesame", "same"); should return false instead of true.

### ISSUE THREAD

**Issue by mtyrio** [FreeCodeCamp/FreeCodeCamp#11702]
Challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=%0Afunction%20confirmEnding(str%2C%20target)%20%7B%0A%20%20%2F%2F%20%22Never%20give%20up%20and%20good%20luck%20will%20find%20you.%22%0A%20%20%2F%2F%20--%20Falcor%0A%20%20var%20arr%20%3D%20str.split(%22%20%22)%3B%0A%20%20if%20(arr%5Barr.length%20-%201%5D%20%3D%3D%20target)%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%0A%20%20else%20%7B%0A%20%20%20%20arr%20%3D%20str.split(%22%22)%3B%0A%20%20%20%20if(arr%5Barr.length%20-%201%5D%20%3D%3D%20target)%7B%0A%20%20%20%20%20%20return%20true%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%7D%0A%0AconfirmEnding(%22Open%20sesame%22%2C%20%22same%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  var arr = str.split(" ");
  if (arr[arr.length - 1] == target){
    return true;
  }
  else {
    arr = str.split("");
    if(arr[arr.length - 1] == target){
      return true;
    }
    return false;
  }
}

confirmEnding("Open sesame", "same");

```
confirmEnding("Open sesame", "same"); should return false instead of true.
Please fix it.

**Comment by systimotic** [comment]
Hi @mtyrio! Thank you for reporting this issue.
The challenge here is to check whether _all_ of the letters in the target equal _all_ of the last letters of the string. You're only checking the last letter.
The letters to check in this test case are "same". The last four letters of "Open sesame" are "same". As you can see, the ending matches, so the result should be true.

If you need coding help, please click the "Help" button on the challenge.

If you think I'm wrong in closing this issue, please reopen it and add further clarification.
Happy coding!

**Comment by jags8386** [comment]
`function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  //var arr = str.split(' ');
  //str = arr[arr.length-1];
  str = str.substring(str.length-target.length);
  return str == target ;
}

confirmEnding("He has to give me a new name", "name");`
