### ISSUE TITLE
Instruction improvement in "Responsively Style Radio Buttons" challenge

### ISSUE THREAD

**Issue by Manish-Giri** [FreeCodeCamp/FreeCodeCamp#11710]
#### Challenge Name

https://www.freecodecamp.com/challenges/responsively-style-radio-buttons

#### Issue Description

This challenge trips up a lot of new campers, possibly because of this instruction - 

> Nest all of your radio buttons within a `<div class="row">` element.

Most campers coming to the help room about this challenge end up with this code - 

```
<div class="col-xs-6">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button></div>
    
    <div class="col-xs-6">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button></div>
    
    <div class="col-xs-6">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button></div>
```
I think this happens due to the word "buttons" in the instruction, they tend to relate this with the `button` element. 

While the instruction isn't incorrect, maybe a note could be added, something like - 

> As a reminder, `radio buttons` are `input` elements of type `radio`.

**Comment by Jeff-Shapiro** [comment]
I think another point that comes out of this is the lack of people learning terminology. Maybe some short quizzes placed throughout thats able to identify when people need to redo a certain section of modules would help get around this and confirm the status of someones knowledge.

**Comment by Manish-Giri** [comment]
@Jeff-Shapiro :+1: Coursera has similar mid way quizzes, which one needs to pass to proceed to the following challenges.

**Comment by VikrantSingh13** [comment]
We can add pop quizzes to help internalize the various terminology used. For example, we can add pop quizzes,  after every 10 challenges or so, to check whether the new comers have understood the material or not. If they can't pass the quiz fully, they can manually go back to the challenges, or we can point out the challenges they need to revisit.

**Comment by yaditya** [comment]
Agree with adding some additional notes so it becomes something like:
`Nest all of your radio buttons (<input> element with type 'radio')`

**Comment by raisedadead** [comment]
> We can add pop quizzes [...] need to revisit.

@VikrantSingh13 yes, but IMHO they should in that case go into the video challenges section, which is specifically designed for this. Feel free to discuss that on https://github.com/FreeCodeCamp/hikes

For updating the instructions @Jeff-Shapiro 's suggestion is clean IMHO:
> As a reminder, radio buttons are input elements of type radio.

Opening up for pull requests.

**Comment by Manish-Giri** [comment]
@raisedadead I can work on it.

**Comment by LawDawg79** [comment]
thats exactly the code I ended up with....seems like every time I get tripped up on here its due poorly worded or hard to understand instructions.
