### ISSUE TITLE
Answer is wrong/calculation is wrong

### ISSUE THREAD

**Issue by Desentso** [FreeCodeCamp/FreeCodeCamp#1171]
Challenge http://www.freecodecamp.com/challenges/bonfire-map-the-debris has an issue. The orbital Period in the answer is calculated wrong. T = 2 * PI * (sqrt(a^3 / GM)) that is the formula it should be using. **a** is **semi-major axis** but in the answer its calculated like  **a** would be radius.

**Comment by LumenTeun** [comment]
I believe @brandenbyers and @terakilobyte are guilty/to thank for bringing this Bonfire into existence; after having tried to figure out what a semi-major axis is for the second time in my life, I call upon them to take over from here.

In the mean time, would you, @Desentso, mind explaining why the current calculation is wrong and how it could be corrected?

**Comment by juanpastas** [comment]
@Desentso Thanks. I was stuck on that `a` value. Even when I don't understand much about physics.

**Comment by segmentationfaulter** [comment]
I've tried all the formulas given in the wikipedia entry for orbital period but none of them are giving me a result passing the test. I don't think such Physics heavy challenges should be posed to campers, our campers are mostly new to programming/cs and they should be focusing on programming and cs rather than on Physics and stuff.

**Comment by juanpastas** [comment]
Makes sense. Even when a simpler exercise about using Math functions and constants is good to have.

**Comment by ahstro** [comment]
@segmentationfaulter I think the Bonfire is of value because it makes people really thing about the order of operation, either by calculating things with variables first or using parentheses, as well as using the Math object, but I see your point, it could be simplified.

**Comment by segmentationfaulter** [comment]
@ahstro you are right, but the correct formula should be provided, so that a beginner in CS may not have to dive into Physics.

**Comment by bugron** [comment]
Hi all!
Some explanation about this bonfire. Hope the pic below will clarify things a little bit.
![](http://i.imgur.com/nCrzPeX.png?2)
Remember the "a" value from [wikipedia](https://en.wikipedia.org/wiki/Orbital_period#Two_bodies_orbiting_each_other)? "sum of the semi-major axes of the ellipses...". So "a" is just ```avgAlt + earthRadus``` or the distance between the object which spins around the Earth and the Earth's center. And the [formula](https://en.wikipedia.org/wiki/Orbital_period#Two_bodies_orbiting_each_other) is a kind of a representation of Newton's second law.
And all this in JavaScript will be as follows:
```var period = Math.round(2 * Math.PI * Math.sqrt(Math.pow((earthRadius + avgAlt), 3)/GM));```
That's it!
