### ISSUE TITLE
Front-end Certificate not showing owner's name, date of issue and url

### ISSUE THREAD

**Issue by ankitgaurav** [freeCodeCamp/freeCodeCamp#11716]
#### Challenge Name
[front-end-certification](https://www.freecodecamp.com/ankitgaurav/front-end-certification)

#### Issue Description
I am having the same problem with my front-end-certification image.
I have followed all the steps mentioned by @raisedadead in #8238. (My profile info updated from Github and FCC)
Still, the problem persists. &#9785;

As I can see from inspecting the view, the certificate image is just the template of the certificate with no name, certificate date or link in it.
And these are being shown using a small script that calculates the window width and positions the mentioned texts over the image.

As such, when downloading the certificate or sharing the page on twitter etc, the certificate snippet is just a blank template, and also an embarrassment. 
Screenshots attached below.

#### Browser Information
Chrome, Firefox for Windows 10 (Latest versions)
Chrome Android app (Latest)
 
#### Screenshot
![The certificate link](https://cloud.githubusercontent.com/assets/9376908/20454577/bf0e1c38-ae6a-11e6-92a5-55cd8194cfd6.JPG)
![The actual certificate image being rendered](https://cloud.githubusercontent.com/assets/9376908/20454584/f4dce7a4-ae6a-11e6-94c3-ef20bb0ea7e6.JPG)
![facebook_snippet](https://cloud.githubusercontent.com/assets/9376908/20454599/912302d8-ae6b-11e6-9fba-111efbde10f7.JPG)

**Comment by atjonathan** [comment]
@ankitaggarwal011, this has been fixed to a fully static based layout in `staging`. It should be merged into production soon!

**Comment by ankitgaurav** [comment]
I guess you talking about PR 'Overhauled Certificates' #9469
Okay then. But this present certificate is way better that the new one. :grinning:

**Comment by atjonathan** [comment]
@ankitgaurav, have you tested out locally? This is the style we are going for.

**Comment by alchermd** [comment]
Has this issue been fixed? I have finished the Front End Certification as well, and I'm getting a template image when I try to download it.

**Comment by raisedadead** [comment]
Opening and blocking it until release.
