### ISSUE TITLE
unclosed tags difficult to find

### ISSUE THREAD

**Issue by suaibme** [FreeCodeCamp/FreeCodeCamp#11724]
I find it so difficult to detect unclosed tages in my html code. is there any help? like a platform that helps you detect unclosed tags? would really appreciate any help. thanks in advance.

**Comment by aduggal** [comment]
@suaibme you could always try using other IDEs (like WebStorm or any one that provides HTML validation) if you frequently face this issue. I usually create the pair tags together which helps avoid any missing tags.

**Comment by raisedadead** [comment]
> I find it so difficult to detect unclosed tages in my html code. is there any help? like a platform that helps you detect unclosed tags?

@suaibme 

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
