### ISSUE TITLE
I cannot post in freecodecamp chat room 

### ISSUE THREAD

**Issue by dileep1415** [FreeCodeCamp/FreeCodeCamp#11731]
Challenge [Comment your JavaScript Code](https://www.freecodecamp.com/challenges/comment-your-javascript-code) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by erictleung** [comment]
@dileep1415 sorry to hear about your issue. Can you give us more information on your issue? I understand you aren't able to post in the chat room, but is it within the FreeCodeCamp website? Are you on Gitter on a separate window? Does the chat room open up? The most information on how to reproduce your issue the better. Thanks!

**Comment by abhisekp** [comment]
@dileep1415 Please see if you're able to post here in [![**`FreeCodeCamp/HelpJavaScript`**](https://img.shields.io/badge/Gitter_Chat_Room:-FreeCodeCamp/HelpJavaScript_⮭-006400.svg?style=flat-square&maxAge=2592000 "FreeCodeCamp/HelpJavaScript")](https://gitter.im/FreeCodeCamp/HelpJavaScript) room.
