### ISSUE TITLE
waypoint-use-a-css-class-to-style-an-element can be cheated on using inline styles

### ISSUE THREAD

**Issue by benmcmahon100** [FreeCodeCamp/freecodecamp#1173]
I will go and create a fix for this now just reporting it to make it official!
http://www.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element
![image](https://cloud.githubusercontent.com/assets/10749142/8456206/c1bcccde-2001-11e5-979d-1ba599af0a01.png)

**Comment by benmcmahon100** [comment]
Fix in #1174

**Comment by LumenTeun** [comment]
Great, but in the future you don't need to make a bug report of something if you're going to fix it yourself, at least not if it's a simple bug like this. ;)
