### ISSUE TITLE
Responsively Style Radio Buttons

### ISSUE THREAD

**Issue by deepakloyola** [FreeCodeCamp/FreeCodeCamp#11743]
Hello Team,

I believe this lesson is only for Nesting radio button within <div>

However i am able to nest the check boxes as well within the <div>

Please check and confirm if this is expected.

**Comment by Jeff-Shapiro** [comment]
Please supply the code you used.

**Comment by atjonathan** [comment]
Going above and beyond in a challenge shouldn't fail the tests necessarily. Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
