### ISSUE TITLE
converting C to F in javascript (#139)

### ISSUE THREAD

**Issue by GitGarza** [FreeCodeCamp/FreeCodeCamp#11744]
Challenge [Convert Celsius to Fahrenheit](https://www.freecodecamp.com/challenges/convert-celsius-to-fahrenheit#?solution=%0Afunction%20convertToF(celsius)%20%7B%0A%20%20var%20fahrenheit%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20celcius%3B%0A%20%20fahrenheit%20%3D%20celcius%20*%209%2F5%20%2B%2032%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20fahrenheit%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%20your%20code%0AconvertToF(-30)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function convertToF(celsius) {
  var fahrenheit;
  // Only change code below this line
  var celcius;
  fahrenheit = celcius * 9/5 + 32;
  // Only change code above this line
  return fahrenheit;
}

// Change the inputs below to test your code
convertToF(-30);
```

code does not produce any of the correct results except that it will convertToF(0) returns a number.

**Comment by raisedadead** [comment]
The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by elskaan** [comment]
function convertToF(celsius) {
  var fahrenheit;

  // Only change code below this line
  fahrenheit = celsius * (9 / 5) + 32;
  
  // Only change code above this line
  return fahrenheit;
}

// Change the inputs below to test your code
convertToF(20);
