### ISSUE TITLE
you are here  header looks like its better placed above the div id = data tag as it actually shows on the screen... 

### ISSUE THREAD

**Issue by cd-Zero** [FreeCodeCamp/FreeCodeCamp#11755]
Challenge [Get Geolocation Data](https://www.freecodecamp.com/challenges/get-geolocation-data#?solution=%0Afccss%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%0A%20%20if%20(navigator.geolocation)%20%7B%0A%20%20navigator.geolocation.getCurrentPosition(function(position)%20%7B%0A%20%20%20%20%24(%22%23data%22).html(%22latitude%3A%20%22%20%2B%20position.coords.latitude%20%2B%20%22%3Cbr%3Elongitude%3A%20%22%20%2B%20position.coords.longitude)%3B%0A%20%20%7D)%3B%0A%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0Afcces%0A%3Ch4%3EYou%20are%20here%3A%3C%2Fh4%3E%0A%3Cdiv%20id%20%3D%20%22data%22%3E%0A%20%20%0A%20%20%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  // Only change code below this line.
  
  if (navigator.geolocation) {
  navigator.geolocation.getCurrentPosition(function(position) {
    $("#data").html("latitude: " + position.coords.latitude + "<br>longitude: " + position.coords.longitude);
  });
}
  
  // Only change code above this line.
</script>
<h4>You are here:</h4>
<div id = "data">
  
  
</div>

```

**Comment by systimotic** [comment]
Hi @cd-Zero! Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #11741, so I am closing it as a duplicate.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. 
Happy coding!

**Comment by cd-Zero** [comment]
you are correct!
