### ISSUE TITLE
It still sends you to Slack

### ISSUE THREAD

**Issue by shcolligan** [FreeCodeCamp/FreeCodeCamp#1175]
Challenge http://www.freecodecamp.com/challenges/waypoint-pair-program-on-bonfires has an issue. 

It still sends you to Slack here...

"6. We have a special chat room for people ready to pair program. Go to our http://freecodecamp.slack.com/messages/letspair and type "Hello Pair Programmers!" "

**Comment by LumenTeun** [comment]
Thank you for reporting this, but it has already been fixed in a recent pull request that I can't find because I'm on mobile.

**Comment by shcolligan** [comment]
If it's fixed, it's not deployed. I'm not seeing it. (The "Pair" buttons on the all Bonfire pages do point to Gitter, but not instruction #6 on this page.)

**Comment by LumenTeun** [comment]
You're right, it's not in `production` yet. From what I understand, all development is done on the `staging` branch and systematically pushed to `production` from there. This specific issue was fixed in 7004e81b4a29b196a659bcb5cdcef30253b71d6f

**Comment by shcolligan** [comment]
Nine days ago...

**Comment by benmcmahon100** [comment]
it hasn't been merged yet. expect merging of fixes to happen early next week possibly sooner

**Comment by ahstro** [comment]
Should be fixed in prod now, right?

**Comment by shcolligan** [comment]
I don't know if "fixed" is the right word. The entire section seems to be deleted. Not sure where it went.

The original URL now gives an error "404: We couldn't find a challenge with the name `waypoint-pair-program-on-bonfires` Please double check the name."

And then it redirects, somewhat weirdly, to "http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work"
