### ISSUE TITLE
Build a Tribute Page - grammar error.

### ISSUE THREAD

**Issue by gViro** [FreeCodeCamp/FreeCodeCamp#11750]
#### Build a Tribute Page

https://www.freecodecamp.com/challenges/build-a-tribute-page

#### Minor grammar error in the instructions. 

FCC copy reads as follows ( emphasis is mine ): 

> Rule #2: Fulfill the _below_ user stories.

Consider moving "below" to the end of the sentence. "Fulfill the user stories _below_." 

It could also be replaced with a noun.  "Fulfill the _following_ user stories."

**Comment by ubershibs** [comment]
This isn't limited to that one challenge. It seem like we used that language throughout the Front End section, as well as the React portion of Data Viz, then nothing at all for D3, and then this sentence for the Back End projects: "Here are the specific user stories you should implement for this project:"

I would propose running through and changing the wording of all projects to the sentence currently found on Back End projects. I'm willing and happy to take it on and make all projects consistent, whichever wording people think is best.

**Comment by systimotic** [comment]
I'm not a native English speaker. My knowledge of English grammar is not good enough to judge whether the current phrasing is technically correct. 
What I can say is that, to me, the current phrasing sounds very "complicated". I'm all for keeping the writing as simple as possible. I'm in favor of "Fulfill the following user stories," as "Fulfill the user stories below" could be interpreted as having to do the action of fulfilling the user stories in a place that is below.
I don't think this is a massive issue, but I guess it can't hurt to try to make things better!

**Comment by raisedadead** [comment]
@ubershibs yup. thanks, please feel free to make a pull request!
