### ISSUE TITLE
Web Design examples for some challenges

### ISSUE THREAD

**Issue by gepetobio** [FreeCodeCamp/FreeCodeCamp#11769]
#### Challenge Name

https://www.freecodecamp.com/challenges/build-a-tribute-page
https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage

#### Issue Description

I've been helping some people who have reached these 2 challenges and have not progressed because they didn't have a `Design` idea to build them. Some students are too worried about Design while they are still learning basic HTML and CSS. Although they have the capability to build those pages, they want them to look really nice. But they lack knowledge on Design Principles (which is not the goal for those challenges) and end up not building those pages or taking several days to build something they don't like (or are not proud of).

I would like to suggest that we add some sort of possible designs for those challenges. They can be simple JPGs or PNGs that someone can pick and follow, without having to think and come up with their own designs. I know there are several Web Designers doing the FCC challenges who would be glad to share some design options to those that lack those really-nice-to-have design skills.

That doesn't mean one cannot come up with his/her own designs for those challenges but giving the option to the others who hit a wall just because they are not good at web design.

I would like to hear someone else's opinions on this. I know it's not crucial but I strongly believe it would help some people...

**Comment by atjonathan** [comment]
@gepetobio, sorry our bot closes this issue if you have the word "help" in your issue description 😂
I recommend you open a new issue over at our [CurriculumExpansion](https://github.com/FreeCodeCamp/CurriculumExpansion/issues) repository!

**Comment by gepetobio** [comment]
Thank you @atjonathan I wasn't sure where to discuss this... but will reopen it on the CurriculumExpansion then ;-)

**Comment by sludge256** [comment]
For reference: https://github.com/FreeCodeCamp/CurriculumExpansion/issues/85
