### ISSUE TITLE
Not sure why my code is incorrect - 

### ISSUE THREAD

**Issue by jdavis1990** [FreeCodeCamp/FreeCodeCamp#11766]
Challenge [Convert Celsius to Fahrenheit](https://www.freecodecamp.com/challenges/convert-celsius-to-fahrenheit#?solution=function%20convert(celsius)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20var%20fahrenheit%20%3D%20celsius%20*%209%20%2F%205%20%2B%2032%3B%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20if%20(%20typeof%20fahrenheit%20!%3D%3D%20'undefined'%20)%20%7B%0A%20%20return%20fahrenheit%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20'fahrenheit%20not%20defined'%3B%0A%20%20%7D%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%20your%20code%0Aconvert(0)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function convert(celsius) {
  // Only change code below this line
  
  var fahrenheit = celsius * 9 / 5 + 32;
  
  // Only change code above this line
  if ( typeof fahrenheit !== 'undefined' ) {
  return fahrenheit;
  } else {
    return 'fahrenheit not defined';
  }
}

// Change the inputs below to test your code
convert(0);
```

**Comment by dhcodes** [comment]
@jdavis1990 your code works, but it looks like the function name got modified from `convertToF` to `convert`. If you change it back, it will pass. This could have been a result of the challenge being updated and you returning to visit it as it would have loaded the code editor from localStorage. If something like this happens in the future, make sure the function name in the tests (`convertToF`) matches your function name to ensure the tests run correctly.
