### ISSUE TITLE
will not let the program move forward.

### ISSUE THREAD

**Issue by tbikhram** [FreeCodeCamp/FreeCodeCamp#11771]
Challenge [Finding a Remainder in JavaScript](https://www.freecodecamp.com/challenges/finding-a-remainder-in-javascript#?solution=%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20remainder%3D%2011%20%25%203%0A%0A%0A%0A%0A%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Only change code below this line

var remainder= 11 % 3









```

**Comment by Azayzel** [comment]
I immediately see no semi-colon. Try adding that and re-running your test. These questions though, should really be asked on the [FCC Gitter Channel](https://gitter.im/FreeCodeCamp/HelpJavaScript).

**Comment by erictleung** [comment]
@tbikhram as @Azayzel has pointed out, you're missing a semi-colon at the end. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by Bouncey** [comment]
@erictleung @Azayzel This should work without the `;`

**Comment by Bouncey** [comment]
@tbikhram Thank you for the issue. You are correct that this is a bug, however, this is resolved in our latest update.

As stated above, try adding a `;` at the end of the assignment to pass this challenge for now.

Happy coding :+1:
