### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by seasalt** [FreeCodeCamp/freecodecamp#1177]
![image](https://cloud.githubusercontent.com/assets/11064329/8464149/ffeaac72-200d-11e5-8ea3-5e1eebcd35b0.png)

**Comment by benmcmahon100** [comment]
you've left some of the html out of the screen shot so it's hard to resolve this issue but I'm 100% confident that this is not a bug but rather that you've left something out
e.g. if you have $('a').length in the challenge tests and you have no a tags the $('a') is null/undefined. 
So it saying "Cannot get length of null" is correct

**Comment by LumenTeun** [comment]
@benmcmahon100 is right in how this operates and that the waypoint should be completable. This is a sort of bug with how the test cases work though; because the error message replaces the objective, it's necessary to reload the page to see what you need to accomplish.

**Comment by seasalt** [comment]
![image](https://cloud.githubusercontent.com/assets/11064329/8464101/c31ac700-200d-11e5-9a1e-39515fbc099a.png)

**Comment by seasalt** [comment]
I updated the screen. Is it too small to see?

**Comment by benmcmahon100** [comment]
You need<p>click here for 
```
<a href = "somelink"> cat photos </a></p>
```

**Comment by seasalt** [comment]
Thank you all !
