### ISSUE TITLE
"studlyCapVar" not being accepted 

### ISSUE THREAD

**Issue by dano707** [FreeCodeCamp/FreeCodeCamp#11773]
Challenge [Understanding Case Sensitivity in Variables](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables#?solution=%2F%2F%20Declarations%0Avar%20studlyCapvar%3B%0Avar%20properCamelCase%3B%0Avar%20titleCaseOver%3B%0A%0A%2F%2F%20Assignments%0AstudlyCapVar%20%3D%2010%3B%0AproperCamelCase%20%3D%20%22A%20String%22%3B%0AtitleCaseOver%20%3D%209000%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Declarations
var studlyCapvar;
var properCamelCase;
var titleCaseOver;

// Assignments
studlyCapVar = 10;
properCamelCase = "A String";
titleCaseOver = 9000;



```

**Comment by Manish-Giri** [comment]
@dano707 Your code is incomplete, because you haven't used camelCase in the declaration for `studlyCapVar` - 
> studlyCapVar should use camelCase in both declaration and assignment sections

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) first for help with issues like these, in future. Happy Coding!

**Comment by erictleung** [comment]
@dano707 as @Manish-Giri has pointed out, your code is still incorrect. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by AndreyAzimov** [comment]
**stydlyCapVar** var should be studlyCapVar

but it should be

**Comment by luzmuller** [comment]
Hi,
I had the same issue and I delete the declaration and assignment given to do the test, and then it worked well

**Comment by ritikkamboj** [comment]
// Declarations
var studlyCapVar
var properCamelCase;
var titleCaseOver;

// Assignments
studlyCapVar = 10;
properCamelCase = "A String";
titleCaseOver = 9000;
