### ISSUE TITLE
browser freeze when do the Sum All Odd Fibonacci Numbers

### ISSUE THREAD

**Issue by theabytheriver** [FreeCodeCamp/FreeCodeCamp#11778]
#### Sum All Odd Fibonacci Numbers
https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers

#### Issue Description

Browser freeze when I attempted to run and test my code and refresh, reload, reopen browser doesn't solve the problem afterward.  I really want to continue my challenges so please help! 

#### Browser Information
* Browser Name, Version:  Chrome Version 54.0.2840.87 (64-bit)
* Operating System: OS X El Captain version 10.11.6
* Mobile, Desktop, or Tablet: MacBook Pro

#### Your Code

```js
 
 
 
```
#### Screenshot

<img width="670" alt="screen shot 2016-11-23 at 9 59 57 pm" src="https://cloud.githubusercontent.com/assets/19896683/20562686/3cb3303c-b1c8-11e6-8494-f8442ca195e2.png">

<img width="1128" alt="screen shot 2016-11-23 at 9 58 52 pm" src="https://cloud.githubusercontent.com/assets/19896683/20562667/1c5829dc-b1c8-11e6-966e-6e031f09a000.png">

**Comment by dhcodes** [comment]
@theabytheriver your code likely has an infinite loop that crashes the browser by exceeding the callstack limit. You can read here on how to prevent the code from running on page load. https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/FreeCodeCamp-Disable-Code-Autorun

Alternatively, you can also clear your cookies, but this would remove the code you currently have in the editor so you would want to copy/paste it to a different text editor if you go this route.

Closing as resolved.
