### ISSUE TITLE
My output (0 Hold) is correct but didnt passed test case 

### ISSUE THREAD

**Issue by ficastle5** [FreeCodeCamp/FreeCodeCamp#11785]
![capture](https://cloud.githubusercontent.com/assets/6858023/20582256/891e1b74-b21a-11e6-93e2-4fe82e4df4ba.JPG)
Challenge [Counting Cards](https://www.freecodecamp.com/challenges/counting-cards#?solution=%0Avar%20count%20%3D%200%3B%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch(card)%7B%0A%20%20%20%20case%202%3A%0A%20%20%20%20%20%20count%2B%2B%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%203%3A%0A%20%20%20%20%20%20count%2B%2B%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%204%3A%0A%20%20%20%20%20%20count%2B%2B%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%205%3A%0A%20%20%20%20%20%20count%2B%2B%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%206%3A%0A%20%20%20%20%20%20count%2B%2B%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2010%3A%0A%20%20%20%20%20%20count--%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22J%22%3A%0A%20%20%20%20%20%20count--%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22Q%22%3A%0A%20%20%20%20%20%20count--%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22K%22%3A%0A%20%20%20%20%20%20count--%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22A%22%3A%0A%20%20%20%20%20%20count--%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%7D%0A%20%20if(card%3E1)%7B%0A%20%20%20%20return%20count%2B%22%20Bet%22%3B%20%20%0A%20%20%7D%0A%20%20else%7B%0A%20%20return%20count%2B%22%20Hold%22%3B%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(2)%3B%20cc(3)%3B%20cc(7)%3B%20cc(%27K%27)%3B%20cc(%27A%27)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var count = 0;
function cc(card) {
  // Only change code below this line
  switch(card){
    case 2:
      count++;
      break;
    case 3:
      count++;
      break;
    case 4:
      count++;
      break;
    case 5:
      count++;
      break;
    case 6:
      count++;
      break;
    case 10:
      count--;
      break;
    case "J":
      count--;
      break;
    case "Q":
      count--;
      break;
    case "K":
      count--;
      break;
    case "A":
      count--;
      break;
  }
  if(card>1){
    return count+" Bet";  
  }
  else{
  return count+" Hold";}
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

```
Cards sequence 789 should return "0 Hold"

My output was correct based on the output comment. 
confused

**Comment by erictleung** [comment]
@ficastle5 Thank you for reporting this issue. Your code is incorrect. The test runs the following commands

```js
cc(7); cc(8); cc(9);
```

And your code outputs `0 Bet`, but that particular test should be `0 Hold`.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
