### ISSUE TITLE
guys i've tried this bout it does'nt runn  out correctly!

### ISSUE THREAD

**Issue by kellykevin** [FreeCodeCamp/FreeCodeCamp#11783]
Challenge [Word Blanks](https://www.freecodecamp.com/challenges/word-blanks#?solution=%0Afunction%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20%0Aresult%3D%20myNoun%20%2B%20myAdjective%20%2B%20myVerb%20%2B%20myAdverb%3B%0A%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22dog%22%2C%20%22big%22%2C%20%22ran%22%2C%20%22quickly%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  
result= myNoun + myAdjective + myVerb + myAdverb;
  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```

**Comment by no-stack-dub-sack** [comment]
Hi @kellykevin, I've taken a look at your code and the challenge and determined that there is no bug. I would suggest going back and taking a closer look at the challenge instructions 😄 

For help with coding challenges, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our `[full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390)`.
