### ISSUE TITLE
Code corect but isn't working

### ISSUE THREAD

**Issue by victormanoliu97** [FreeCodeCamp/FreeCodeCamp#11786]
Challenge [Storing Values with the Assignment Operator](https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator#?solution=%0A%2F%2F%20Setup%0Avar%20a%20%3D%207%3B%0Avar%20b%20%3D%202%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Ab%3Da%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var a = 7;
var b = 2;

// Only change code below this line

b=a;

```

**Comment by raisedadead** [comment]
Please read the instructions once again, you are almost there.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by Viniciogj** [comment]
// Setup
var a;
var b = 2;

// Only change code below this line

var a = 7;
b = a;

**Comment by raisedadead** [comment]
@Viniciogj please provide assistance on help chat instead, GitHub issues are for reporting bugs with code base only.

**Comment by eliteclientele** [comment]
Code doesn't seem to work
```
// Setup
var a = 5;
var b = 2;

// Only change code below this line
a = 7;
b = a;
```
