### ISSUE TITLE
Two asserts wrong in bonfire symmetric difference

### ISSUE THREAD

**Issue by Joe-Balsamo** [FreeCodeCamp/freecodecamp#1178]
![screen shot 2015-07-01 at 6 12 33 pm](https://cloud.githubusercontent.com/assets/1594462/8468174/b015f2be-201d-11e5-9985-64de2e8cea24.png)
Challenge http://www.freecodecamp.com/challenges/bonfire-symmetric-difference has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Unless I'm misunderstanding symmetric differences, I believe that the two tests showing my code not passing are wrong. All three arrays contain 5, which should be excluded as they are an intersection of the sets (arrays) and therefore not a symmetric difference.

**Comment by SaintPeter** [comment]
Watch the video that accompanies the challenge:
https://www.youtube.com/watch?v=PxffSUQRkG4

You'll see that you need to take the difference of A and B, and then take the result of that difference and compare it with C.  A and B both have 5, so it does not appear in A&#x00394;B, but C does, so A&#x00394;B&#x00394;C does not have it.  It's not exactly intuitive, but it's how it works.

Order matters, too:  A&#x00394;B&#x00394;C  does not equal C&#x00394;B&#x00394;A

**Comment by Joe-Balsamo** [comment]
Ahh, thank you. OK, I see how it works now. My code actually isn't buggy, my algorithm is wrong! Thank you SaintPeter.

**Comment by Joe-Balsamo** [comment]
Rex,

I don't think that video does accompany the challenge, at least I couldn't find a link on the bonfire page. It most definitely should as seeing the demonstration really clarified it for me. I knew either there was a bug in the asserts, or I wasn't completely clear on how symmetric differences work.

**Comment by SaintPeter** [comment]
It may still be in staging.

It does really clarify the problem right?  I know that I started out with
the same solution as you because I had the same concern.  I then went
searching the web to find more info and ran across that video.

**Comment by Joe-Balsamo** [comment]
Yes, it's a great video. Glad it will be included.

Thanks again for your help.
