### ISSUE TITLE
Confusing error message.

### ISSUE THREAD

**Issue by dave-tree-uk** [freeCodeCamp/freeCodeCamp#11792]
Challenge: https://www.freecodecamp.com/challenges/escape-sequences-in-strings

Correct Answer
`var myStr = "FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line`

WrongAnswer -- Gives error message "myStr should have encoded text with the proper escape sequences and no spacing"" which is confusing to students as they have only missed capitalizing one letter"

`var myStr = "FirstLine\n\\SecondLine\\\rThirdline"; // Change this line`

----
**Edited by @abhisekp on 25th Nov. 2016 (Friday) at 07:27 AM (IST - GMT+5:30)**

**Comment by abhisekp** [comment]
@dave-tree-uk Please provide the challenge link.

**Comment by dave-tree-uk** [comment]
https://www.freecodecamp.com/challenges/escape-sequences-in-strings


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by atjonathan** [comment]
Your code is incorrect. Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by Bouncey** [comment]
@dave-tree-uk unfortunately the devil is in the detail.

I am open to suggestions as to how we could improve the wording of the instructions and/or the test case

Happy Coding!

**Comment by Bouncey** [comment]
@atjonathan the issue being raised is with the test case/instructions

**Comment by atjonathan** [comment]
> /Correct Answer/
var myStr = "FirstLine\n\SecondLine\\rThirdLine"; // Change this line

That is not the correct answer. However, I'm all up for improving the instructions! The test cases, `myStr should have encoded text with the proper escape sequences and no spacing.`, seems fine to me. The reason the test is failing is for that very fact.

**Comment by Bouncey** [comment]
> That is not the correct answer

There are backslashes missing because they need to be escaped in this comment box. On the next line I will type 4 back slashes so you can see @atjonathan 

\\\\

**Comment by Bouncey** [comment]
If you try to edit the OP, you will see the correct escaping

**Comment by Dayfiri** [comment]
@dave-tree-uk 
I can see it is a bit confusing at first to understand that sentence but in the end, it's just an unknown word that has a pretty simple meaning. 
You get an error message: `"myStr should have encoded text with the proper escape sequences and no spacing"` that means:

1. [Encoded text](https://en.wikipedia.org/wiki/Character_encoding) You need to have strictly written words ( case-sensitive)
2. Proper escape sequence ( proper written escaping sequence which is explained in assignment)
3. No spacing ( I think this one speaks to itself )

So all in all, at first it seems difficult but it actually isn't as you can see. It is good to have this kind of things in your assignment that teaches you the programming vocabulary which if you don't understand at first, you can always get help at FCC [help page](https://gitter.im/FreeCodeCamp/Help) or by [google](https://google.com)-ing your problem.

I hope this help sort things a little bit.
Happy coding 👍

**Comment by sh6sha** [comment]
I am facing the similar issue

**Comment by systimotic** [comment]
This issue was fixed in #13105 🎉

**Comment by dltuscupstate** [comment]
I got caught up with this error message because I didn't know if I should follow basic order of operation. I know it sounds dumb, but I just was getting particular from the instruction that parentheses, brackets, and quotes meant something to the code. Felt like I would have gotten told by the instruction that parentheses should be noted as the basic math and not something specific to javascript.

**Comment by mustafabdikani** [comment]
Thank you pro it is correct

**Comment by andrevieiraexbyte** [comment]
correct answer
var myStr = "FirstLine\n\\SecondLine\\\rThirdLine";

**Comment by MIFind** [comment]
Hey , here my answer 
var myStr="FirstLine\n\\SecondLine\\\rThirdLine";
