### ISSUE TITLE
Multiple bonfire completions show up in your profile upon multiple completions. 

### ISSUE THREAD

**Issue by nickpalmer789** [FreeCodeCamp/FreeCodeCamp#1179]
When I complete the code that I have been working on for a bonfire there is sometimes something that I will want to change after I have already submitted and run my code. I then noticed that there will be multiple bonfire completions under your profile when you run the code more than once. This occurs even when you run the same code twice. Across the ~40,000 users that are signed up right now, it might save some significant drive space to only show one of these.

**Comment by LumenTeun** [comment]
The feature of saving all Bonfire solutions was added not long ago because people wanted to be able to solve a Bonfire in different ways as well as see how they had improved over time, going back and redoing Bonfires and comparing the new with the old. The possibility of a user deleting their own Bonfires, so they could clear out duplicates and ones with only minor changes, would probably be a good idea however.

**Comment by 1hella** [comment]
I like the idea of have a 'run' button and a 'submit' button that will only work once all the tests pass. It'll give you a chance to remove all your `console.log`'s and everything before it actually get's saved to your profile.

**Comment by LumenTeun** [comment]
+1 @1hella

**Comment by nickpalmer789** [comment]
I think that it would be really great if there were a short of history for each bonfire that you complete where it will expand to show all of your bonfire completions. A sort of folder for each of your bonfires if you will.

**Comment by nxiety** [comment]
Would really like the ability to delete certain submissions as well. I basically did a bunch of (really) ugly and dirty submissions with the plan on refactoring them later, being completely unaware that multiple submissions would show up.

**Comment by Arthaey** [comment]
+1, for exactly the same reasons as @nxiety states

**Comment by thejonathangraham** [comment]
![image](https://cloud.githubusercontent.com/assets/11198912/9746806/eabefffc-5671-11e5-8211-c1ba79a70a2a.png)

**Comment by BerkeleyTrue** [comment]
We will be removing duplicates. Only the latest challenge will be kept. This also allows for editing of bonfire solutions when combined with Shareable Challenges® :)

**Comment by thejonathangraham** [comment]
Nice!

On Mon, 12 Oct 2015 08:22 Berkeley Martinez <notifications@github.com>
wrote:

> We will be removing duplicates. Only the latest challenge will be kept.
> This also allows for editing of bonfire solutions when combined with
> Shareable Challenges® :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1179#issuecomment-147310266>
> .
>
-- 

Jonathan Graham

**Comment by ahstro** [comment]
@BerkeleyTrue I assume this won't allow multiple solutions to be saved? Say, if I find out two ways to solve a bonfire and I'm unsure of which is best or if they're good in different ways?

**Comment by BerkeleyTrue** [comment]
Yes that is correct. Finding the best way or multiple ways to solve things seems to be a recurring theme as I closed a ton of issue last night. Campers are focusing on the wrong aspects of learning to code. What will get you hired is the practical side of coding. Building real world projects.

**Comment by bugron** [comment]
@BerkeleyTrue is this still an issue?
