### ISSUE TITLE
Center Floated image

### ISSUE THREAD

**Issue by SimeonGK** [FreeCodeCamp/FreeCodeCamp#11799]
#### Challenge Name

https://www.freecodecamp.com/challenges/build-a-tribute-page

#### Issue Description
I would like to center an image wich is floated: left; and shaped-outside: circle();
but when i try to center it it just wont do it.

Here is the code:
html
img class="enzo" src="http://silodrome.com/wp-content/uploads/2013/01/Enzo-Ferrari.jpeg"
style 
.enzo{
  border: 2px solid #000;
  height: 500px;
  width: 500px;
  border-radius: 500px;
  float: left; 
  shape-outside: circle();

Here is a screenshot 
![image](https://cloud.githubusercontent.com/assets/20865916/20609176/7e0bdf36-b289-11e6-8c98-cbdfe2c034fb.png)

**Comment by ilyawzrd** [comment]
You can use flexbox,it's much faster and easier than bootstrap.
Make a wrapper div with:
display:flex;
flex-flow: column;
align-items: center;
margin:auto;

**Comment by SimeonGK** [comment]
![image](https://cloud.githubusercontent.com/assets/20865916/20609467/37503a34-b28d-11e6-96d1-05bcf728a9f3.png)

![image](https://cloud.githubusercontent.com/assets/20865916/20609477/54ad7d94-b28d-11e6-943a-5b0ec4854713.png)

**Comment by SimeonGK** [comment]
what went wrong ?@ilyawzrd

**Comment by ilyawzrd** [comment]
No,i mean wrap all elements,not only image.
