### ISSUE TITLE
Positioning of Camper News posts when searched

### ISSUE THREAD

**Issue by duttakapil** [FreeCodeCamp/FreeCodeCamp#1180]
![FCC Camper News Posts Positioning](http://i.imgur.com/YYDwuJY.png)

As you can see, the position of the first result if a little off. Shows like this only when something is searched, so that should narrow it down maybe?

**Comment by benschenker** [comment]
Thanks @duttakapil,

I'm unable to replicate this so it looks like it must have been fixed.

Feel free to reopen if you still see this issue.
