### ISSUE TITLE
Jade has been renamed to pug

### ISSUE THREAD

**Issue by sw-yx** [FreeCodeCamp/FreeCodeCamp#11806]
Challenge [Build Web Apps with Expressjs](https://www.freecodecamp.com/challenges/build-web-apps-with-expressjs) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

hi folks, i get these warnings when starting the express tutorial

npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

it seems from the article (http://evanhahn.com/understanding-express/) that pug is the way to go so just wondering how i can upgrade to pug?

thanks very much! really appreciate you guys helping us newbies out!

**Comment by raisedadead** [comment]
@sw-yx 

Pug was formerly known as Jade. Refer: https://github.com/pugjs/pug#rename-from-jade. 
It has some breaking changes too, like syntax changes. 
Such changes are documented in `https://github.com/pugjs/pug/issues/2305`

Pug is currently in Beta, and at some point, the node school article will be updated (when its actually goes out of beta, maybe).

Until then, you can ignore the warning and continue with Jade, if you are a complete beginner to  it. Transitioning later should be easier, because you would have had the concepts clear.

Leaving this open for further suggested articles, from the community.

**Comment by dhcodes** [comment]
@raisedadead since the backend challenges are being overhauled, I think the workshoppers will replaced with something else. Or am I mistaken?

**Comment by raisedadead** [comment]
@dhcodes I am afraid, I have not been up to date with the expansion lately, but yeah that sounds like a good idea though.

**Comment by sw-yx** [comment]
backend challenges being overhauled?? ooh! whats coming? I’m like halfway through the current set of challenges now...

Sw yx

Sent from
https://polymail.io/?utm_source=polymail&utm_medium=referral&utm_campaign=signature

On Sat, Nov 26, 2016 at 4:29 AM Dylan

<
mailto:Dylan <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/raisedadead
since the backend challenges are being overhauled, I think the workshoppers will replaced with something else. Or am I mistaken?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11806#issuecomment-263024209
, or

**Comment by raisedadead** [comment]
@sw-yx 
Apologies but can you please discuss on the chat, keeping the thread for issue-specific discussions only. That said, challenges would mostly be same, with a new twist making them more flexible.

And do not worry your progress is still counted, as always. You can also should you want to do them again per your interest, hang tight... 😉

**Comment by erictleung** [comment]
Somewhat distantly related to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8743 in terms of jade-to-pug transition.

**Comment by Bouncey** [comment]
This is more of an issue for workshoppers, not us as we do not maintain it. 

@sw-yx using jade will not do you any harm, currently freeCodeCamp is using jade to render almost everything on the production site. You can use pug where the workshopper says to use jade, I'm sure it wont break anything.

Happy coding
