### ISSUE TITLE
Improve instructions for 'Counting Cards'

### ISSUE THREAD

**Issue by VAggrippino** [FreeCodeCamp/FreeCodeCamp#11819]
In this challenge, we're using the face values of cards which can't all be numerical. e.g. "J", "Q", "K", "A". We're not performing calculations in this challenge and we haven't learned string to integer conversion at this point. We have learned that `case` statements use strict equality. We should only be testing string values.  The automated tests use a mixture of string and integer values. The only version of the code that will pass uses integers for the numbered cards and strings for the *face* cards. Alternatively, a single line about the [parseInt()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseInt) function would ease confusion.

Challenge [Counting Cards](https://www.freecodecamp.com/challenges/counting-cards#?solution=%0Avar%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch(card)%20%7B%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20case%204%3A%0A%20%20%20%20case%205%3A%0A%20%20%20%20case%206%3A%0A%20%20%20%20%20%20count%2B%2B%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2010%3A%0A%20%20%20%20case%20%22J%22%3A%0A%20%20%20%20case%20%22Q%22%3A%0A%20%20%20%20case%20%22K%22%3A%0A%20%20%20%20case%20%22A%22%3A%0A%20%20%20%20%20%20count--%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20default%3A%0A%20%20%20%20%20%20break%3B%0A%20%20%7D%0A%20%20%0A%20%20var%20decision%3B%0A%20%20%0A%20%20if%20(count%20%3E%200)%20%7B%0A%20%20%20%20decision%20%3D%20count%20%2B%20%22%20Bet%22%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20decision%20%3D%20count%20%2B%20%22%20Hold%22%3B%0A%20%20%7D%0A%20%20return%20decision%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(10)%3B%20cc(%22J%22)%3B%20cc(%22Q%22)%3B%20cc(%22K%22)%3B%20cc(%22A%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var count = 0;

function cc(card) {
  // Only change code below this line
  switch(card) {
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      count++;
      break;
    case 10:
    case "J":
    case "Q":
    case "K":
    case "A":
      count--;
      break;
    default:
      break;
  }
  
  var decision;
  
  if (count > 0) {
    decision = count + " Bet";
  } else {
    decision = count + " Hold";
  }
  return decision;
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(10); cc("J"); cc("Q"); cc("K"); cc("A");
```

**Comment by erictleung** [comment]
@VAggrippino thanks for the issue. 

> ...we haven't learned string to integer conversion at this point.

This isn't too much of an issue because JavaScript is dynamically untyped language. That is why you can code `3 + " Bet"` and the interpreter will not yell at you for putting together different types (i.e. numeric plus string).

I understand your concern for consistency in dealing with just strings, rather than two data types, but I don't think it is too much of a concern for this challenge.

The only clarifying change to the instructions could be to add in that the input parameter `card` can be a numeric or string.

cc/ @FreeCodeCamp/moderators

**Comment by Bouncey** [comment]
## First-timers only

The code for this challenge is [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/a2bd7893444a682351becfe88f97a22d3d52bb2d/seed/challenges/01-front-end-development-certification/basic-javascript.json#L4109).

The changes needs are:

You will write a card counting function. It will receive a card parameter __*, which can be a number or a string,*__ and increment or decrement the global count variable according to the card's value (see table).

Following [CONTRIBUTING.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) will help you get set up and make your first PR to FreeCodeCamp :+1: 

If you get stuck, reach out to us in [Contributors chat room](https://gitter.im/FreeCodeCamp/Contributors)

Good Luck!

**Comment by VAggrippino** [comment]
I initially quoted all my case values and didn't understand why I didn't pass until I looked more closely at the test function calls. I thought I should mention it just in case someone else approached the challenge from the same perspective as me.

Thank you for your response and your time. I haven't had many positive experiences with either support or bug reporting on the Internet and I wasn't really expecting any response. I'm pleasantly surprised.

@Bouncey Thank you for the encouragement, but I can't risk a pull request. Due to severe mental health / memory issues and occasional seizures I may not be able to be accountable for any changes I make because I'm likely to forget everything. For me, FCC isn't a means to learning skills for a career. It's just exercise for my failing mind.

**Comment by Bouncey** [comment]
@VAggrippino I was opening this issue up for anyone to create a PR. We would be grateful for any attempt to fix this, but if you are not up to it, someone else will create a PR. No pressure :+1: 

Happy Coding!
