### ISSUE TITLE
Bug on challenge "Style the HTML Body Element"

### ISSUE THREAD

**Issue by ABEDABUN** [FreeCodeCamp/FreeCodeCamp#11810]
The challenge does not want to complete. It leaves "Give your body element the background-color of black." unchecked. I've tried different refresh methods and clearing/resetting the code. On Gitter people say the code is right.
Challenge [Style the HTML Body Element](https://www.freecodecamp.com/challenges/style-the-html-body-element#?solution=%0A%3Cstyle%3E%0Abody%20%7B%0A%C2%A0%C2%A0background-color%3A%20black%3B%0A%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
body {
  background-color: black;
}
</style>

```

**Comment by kazzacarrot** [comment]
@ABEDABUN 
Oddly enough, my solution still works - even though its near identical to yours.
I clicked on your link, copied in my code over yours and passed the test.
It's as if you have some hidden characters in the text editor.

```html

<style>
  body{
    background-color:black;
  }
</style>
```

**Comment by ABEDABUN** [comment]
Thank you. I refreshed and started from line 1. Typed it manually and it worked. Thanks again

**Comment by erictleung** [comment]
@ABEDABUN sounds like the issue has been resolved. Yes, unfortunately, sometimes some invisible characters interfere with our tests. Closing issue as resolved. Happy coding!

**Comment by Brazyl** [comment]
Yeah that one was super buggy!

Reset code
moved style to line one
typed body statement on line 2 
worked great
