### ISSUE TITLE
Sign in Error

### ISSUE THREAD

**Issue by fega** [FreeCodeCamp/FreeCodeCamp#11817]
#### I cannot log in or change the password
And all that I get is "oops something went wrong" 😢 

#### Browser Information

*Chrome Latest
* Windows 10 latest
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by systimotic** [comment]
Hi @fega. I'm sorry for the issues.
What sign in method are you using? (GitHub, email, or something else)
I can't reproduce this issue, both email and GitHub sign in seem to work fine for me.
Are you behind any proxies, firewalls or VPN's?

**Comment by fega** [comment]
Hello @systimotic, No I'm not using proxies,firewalls or VPN, I cannot remember how I created the account, There is a way delete it? I don't have any kind of progress in it. I can created by myself after that. thanks

**Comment by systimotic** [comment]
@fega Mmm, weird. Could it be that you have to confirm your email address?
I don't believe that should prevent you from being able to log in though... 😕 

This error is not the error returned if an account doesn't exist, so your account does indeed exist. I can also find your profile https://www.freecodecamp.com/fega This means you should be able to log in with GitHub as well as email, can you try both?
Could you also please try a different browser to see if that changes anything?

**Comment by fega** [comment]
with email:
"The fega.hg@gmail.com email address is already associated with an account. Try signing in with it here instead."
with GitHub
 "Oops! Something went wrong. Please try again later"
I also tried to change the password but I get the same error.

**Comment by systimotic** [comment]
@fega The error with GitHub is really weird, I don't know why that's happening.
For email sign in, I think you clicked sign up instead of sign in. Could you try signing in with your email?

**Comment by fega** [comment]
I tried with both xD and in chrome and firefox 😆

**Comment by systimotic** [comment]
😞 Well, I guess the error message is correct, something must've gone wrong. 😅 
I'm all out of ideas. Your best bet at this point might be to send an email to team@freecodecamp.com with all of the information (you can link this issue as well). We'll try to figure out the cause, but they'll be able to help you get into your account (or create a new one).

@QuincyLarson Do you have any idea what could've happened here?

**Comment by fega** [comment]
Ok, thanks @systimotic  😄

**Comment by raisedadead** [comment]
Looks like a case of duplicate account. Quincy should be able to help on this, @fega apologies for the inconvenience we are looking into it.

**Comment by QuincyLarson** [comment]
@fega OK - I found two accounts associated with the email address you provided - neither of which had any progress. You should be able to create a new account using your email address, then link your GitHub account to it. 

Please let me know if I can be of further help with this.

Happy coding!

**Comment by fega** [comment]
thanks so much, Quincy!
