### ISSUE TITLE
Lost all progress but solutions are saved?

### ISSUE THREAD

**Issue by HamienSmells** [FreeCodeCamp/FreeCodeCamp#11812]
#### Issue Description
I came back to my account today to find all progress had been wiped, as in my (about) 90 checkmarks had been cleared. However all my solutions are in tack. I haven't been here for long, sorry if I am missing out a lot of info here. I sign in through GitHub if that helps.

* Browser Name, Version: Chrome 54.0.2840.99 m
* Operating System: Windows 10 Anniversary Pro 64bit
* Mobile, Desktop, or Tablet: Desktop

```js
 
 
 
```

**Comment by systimotic** [comment]
Hi @HamienSmells.
Looking at your public profile, it tells me you completed 118 challenges yesterday. Can you confirm whether this is the case or not?
Can you also please check whether you logged in with GitHub previously? If you attempt to sign in with email, what happens?

**Comment by HamienSmells** [comment]
I did as the solutions from the tasks I did previously were still saved, so
I went back. This is no longer an issue for me as I just redid my progress.

**Comment by raisedadead** [comment]
Thanks for confirming @HamienSmells, let us know if you face this in future again. Apologies for your inconvenience, though.

**Comment by maher17** [comment]
i have the same issue i have completed nearly 185 tasks last summer.

**Comment by fmd123** [comment]
I also cannot see the previous progress I made. I don't see anything under my profile either.

**Comment by raisedadead** [comment]
Please send an email to `team@freecodecamp.org`. Thanks.
