### ISSUE TITLE
Code passes tests yet does not pass the bonfire

### ISSUE THREAD

**Issue by davisec52** [FreeCodeCamp/freecodecamp#1181]
Challenge http://www.freecodecamp.com/challenges/bonfire-make-a-person has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Hi. my code for the this bonfire appears to pass all tests, yet the bonfire will not let me advance. It appears that bob.getFullName() is coming back as undefined. However, in repl.it and chrome dev tools it returns bob ross.  My code follows:

```
var Person = function(firstAndLast) {
    var first = firstAndLast.split(" ")[0];
    var last = firstAndLast.split(" ")[1];

    this.setFirstName = function(firstName){
        first = firstName;
    };

    this.setLastName = function(lastName){
        last = lastName;
    };

    this.setFullName = function(firstLast){
        firstAndLast = firstLast;
    };

    this.getFirstName = function(){
        return first;
    };

    this.getLastName = function(){
        return last;
    };
    this.getFullName = function(){
        return firstAndLast;
        };
    };

var bob = new Person('Bob Ross');

bob.getFullName();  // Bob Ross
console.log(bob instanceof Person);  // true
Object.keys(bob).length; //  6

```

**Comment by davisec52** [comment]
Problem solved.  I refreshed the page and ran it again and this time it passed.

**Comment by LumenTeun** [comment]
If it's no longer a problem, remember to close this issue. :)
