### ISSUE TITLE
it wont work

### ISSUE THREAD

**Issue by IFBDesign** [FreeCodeCamp/FreeCodeCamp#11816]
Challenge [Use RGB to Mix Colors](https://www.freecodecamp.com/challenges/use-rgb-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20rgb(225%2C%200%2C%200)%3B%0A%20%20%7D%0A%20%20.orchid-text%20%7B%0A%20%20%20%20color%3A%20rgb(218%2C%20112%2C%20214)%3B%0A%20%20%7D%0A%20%20.sienna-text%20%7B%0A%20%20%20%20color%3A%20rgb(160%2C%2082%2C%2045)%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20rgb(0%2C%200%2C%20225)%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%0A%3Ch1%20class%3D%22orchid-text%22%3EI%20am%20orchid!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22sienna-text%22%3EI%20am%20sienna!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22blue-text%22%3EI%20am%20blue!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: rgb(225, 0, 0);
  }
  .orchid-text {
    color: rgb(218, 112, 214);
  }
  .sienna-text {
    color: rgb(160, 82, 45);
  }
  .blue-text {
    color: rgb(0, 0, 225);
  }
</style>


<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>

<h1 class="red-text">I am red!</h1>

```

**Comment by IFBDesign** [comment]
im doing everything it says and it wont work

**Comment by Manish-Giri** [comment]
@IFBDesign Your code is incorrect. Please look at the color values on the left, you've used `225` instead of `255` for both red and blue, which is wrong.

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) first if you need help with issues like these, in future. Happy Coding!

**Comment by systimotic** [comment]
Thanks @Manish-Giri!

@IFBDesign Manish's suggestions should resolve your issue. As he said, please go the the Help rooms for help. You can get there by clicking the "Help" button on the challenge as well.

If you think I'm wrong in closing this issue, please reopen it and add further clarification.
Happy coding!
