### ISSUE TITLE
code editor does not work in chrome in linux

### ISSUE THREAD

**Issue by znllnz** [FreeCodeCamp/FreeCodeCamp#11815]
The code editor does not work in linux mint in chrome browser. 

the cursor does not line up with the text

#### Issue Description

when I try to edit code in chrome in linux mint

#### Browser Information

google chrome
* Browser Name, Version: 
google chrome Version 54.0.2840.59 (64-bit)
* Operating System: 
linux mint 18 xfce edition 64 bit
* Mobile, Desktop, or Tablet: 
desktop
#### Your Code

```js
 
 
 
```
#### Screenshot

it's not really visible in the screenshot

![image](https://cloud.githubusercontent.com/assets/20784472/20634730/90f9d2ca-b319-11e6-80f0-c6a046dacd88.png)

**Comment by znllnz** [comment]
please try to run freecodecamp in google chrome in linux mint, thanks

**Comment by erictleung** [comment]
@znllnz this may be related to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7847. If you press enter or start typing somewhere, does the issue resolve itself?

**Comment by Bouncey** [comment]
Closing as stale, @znllnz if you have any more info, please reopen this issue
