### ISSUE TITLE
Use Hex Code to Mix Colors

### ISSUE THREAD

**Issue by arimarkeci** [FreeCodeCamp/FreeCodeCamp#11825]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by systimotic** [comment]
Hi @arimarkeci!
Could you please tell us what your issue is?
If you're looking for coding help, please click the ['Help'](https://gitter.im/FreeCodeCamp/Help) button on the challenge.

**Comment by dhcodes** [comment]
Closing. Please reopen if you are still having an issue.
