### ISSUE TITLE
Searching for translated challenge names not working

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#11828]
After setting my language to Spanish, if I search for the challenge `Búsqueda de perfiles` The map is empty, with no hint that my search returned no results.

With my language still set to Spanish, if I search for the challenge `Profile Lookup` I see the translated name (Búsqueda de perfiles) in the map.

**Comment by raisedadead** [comment]
Removed bug, because its not a show stopper issue. Yes search needs some love though.

**Comment by flipsyde606** [comment]
I am taking this
