### ISSUE TITLE
No tests do not tick, even though all requirements are met 

### ISSUE THREAD

**Issue by itsbillyy** [FreeCodeCamp/FreeCodeCamp#11832]
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#?solution=var%20numberValue%20%3D%201%3B%0Afunction%20factorialize(num)%20%7B%0A%20%20for%20(i%3D1%3B%20i%3C%3D%20num%3B%20i%2B%2B)%20%7B%0A%20%20%20%20numberValue%20*%3D%20i%3B%0A%20%20%7D%0A%20%20return%20Number(numberValue)%3B%0A%7D%0Afactorialize(0)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
After manually testing all the requirements, the tests do not tick.

My code:
```javascript
var numberValue = 1;
function factorialize(num) {
  for (i=1; i<= num; i++) {
    numberValue *= i;
  }
  return Number(numberValue);
}
factorialize(0);

```

**Comment by erictleung** [comment]
@itsbillyy our tests run your function `factorialize()` sequentially, one after each other. So global variables are changed with each run. Move your `numberValue` global variable within your function and you should pass the challenge. Happy coding!

**Comment by JohnnyBizzel** [comment]
I'm not sure you should close this issue. It is clearly valid to have global variables.

**Comment by erictleung** [comment]
@JohnnyBizzel yes, global variables are perfectly valid to use in code. Nonetheless, this is a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9199 and this would've been closed in favor of that one. Feel free to continue the discussion over in the other issue. Happy coding!
