### ISSUE TITLE
Test is not working, even though requirement is fulfilled

### ISSUE THREAD

**Issue by itsbillyy** [FreeCodeCamp/FreeCodeCamp#11831]
Challenge [Find the Longest Word in a String](https://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=var%20array%20%3D%20%5B%5D%3B%0Avar%20z%20%3D%200%3B%0Afunction%20findLongestWord(str)%20%7B%0A%20%20array%20%3D%20str.split('%20')%3B%0A%20%20var%20newArray%20%3D%20array.map(function(val)%7B%0A%20%20%20%20return%20val.length%3B%0A%20%20%7D)%3B%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%3D%20newArray.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(newArray%5Bi%5D%20%3E%20z)%20%7B%0A%20%20%20%20%20%20z%20%3D%20newArray%5Bi%5D%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20z%3B%0A%7D%0A%0AfindLongestWord(%22May%20the%20force%20be%20with%20you%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
Test for the third dot point (findLongestWord("May the force be with you") should return 5.) does not tick even though the output satisfies the requirement.

My code:
```javascript
var array = [];
var z = 0;
function findLongestWord(str) {
  array = str.split(' ');
  var newArray = array.map(function(val){
    return val.length;
  });
  for (i = 0; i <= newArray.length; i++) {
    if (newArray[i] > z) {
      z = newArray[i];
    }
  }
  return z;
}

findLongestWord("May the force be with you");

```

**Comment by erictleung** [comment]
@itsbillyy same issue as https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11832. Move your global variables within your function and you should pass the challenge. Happy coding!
