### ISSUE TITLE
Will not accept answer for: myStr should have encoded text with the proper escape sequences and no spacing.

### ISSUE THREAD

**Issue by statesof** [FreeCodeCamp/FreeCodeCamp#11849]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D%22Firstline%5Cn%5C%5CSecondLine%5C%5C%5CrThirdLine%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr="Firstline\n\\SecondLine\\\rThirdLine";


```

**Comment by raisedadead** [comment]
The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
