### ISSUE TITLE
Note For when implementing planet proto's OOP lesson

### ISSUE THREAD

**Issue by benmcmahon100** [FreeCodeCamp/FreeCodeCamp#1184]
When the planeproto command is ran during the lesson it offers
```
 » To execute your program in a test environment, run: planetproto run program.js
```
This does not seem to work in c9 and possibly in general.
Instruction should be worded in such a way as to either (a) avoid mentioning run and stress verify or (b) to directly instruct campers that run does not work as intended

**Comment by benschenker** [comment]
Closing as stale, please reopen if this is still an issue
