### ISSUE TITLE
Bonfire: No Repeats Please, has an issue. The test call at the end of the code is making tests fail. Tests pass when it's removed.

### ISSUE THREAD

**Issue by MadOgre** [FreeCodeCamp/freecodecamp#1185]
Challenge http://www.freecodecamp.com/challenges/bonfire-no-repeats-please seems to have an issue.

It is of course possible that my code is somehow responsible for the problem, but I can't see how.

It appears that my code works correctly and passes all the tests, but only if I remove the last line (test call) With the call, all returned values are reported by the test to be 2 higher that the actual values.

I have used console.log to verify this. The function returns correct values, and the output field of the assignment shows correct values, but in all the tests, the values are shown increased by two.

I previously managed to complete this assignment by simply subtracting 2 from the result before returning it, but it seemed like a hack so I explored further.

I realized the the last line (the test call to the function) is what was affecting the test results somehow

When the line 

```
permAlone("baa");
```
was removed,
All tests passed.

As I experimented with a different test strings, it seems that different letter combinations produce different discrepancies for the tests, for example making the line

```
permAlone("abc");
```

Increases all test results by 6

There seems to be no reason why this test call should in any way affect the results of the assignments' tests.

Here is my complete code (Sorry for the lengthy description)

```
var permutations = [];

function permute(head, tail) {
  if (tail.length === 1) {
    permutations.push(head+tail);
  } else {
    for (var i = 0; i < tail.length; ++i) {
      permute(head + tail[i], tail.slice(0, i) + tail.slice(i+1));
    }
  }
}

function permAlone(str) {
  permute("", str);
  var regex = new RegExp(/(\w)\1/);
  var perms = permutations.filter(function(perm){
    return !regex.test(perm);
  });
  console.log("Return: " + perms.length);
  return perms.length;
}


//This line makes all but the first test fail, but all tests pass when it's removed
permAlone("baa");
```

**Comment by timtouch** [comment]
Your permutations[] is persistent so every time you call the permAlone() function, you are still pushing into an already filled array. To see for yourself, try calling permAlone() multiple times and see how the permutations.length increases.

**Comment by MadOgre** [comment]
Wow I feel really embarrassed now! Yes that was exactly the problem. Sorry for this oversight. Everything works as it should.

**Comment by hando1818as** [comment]
Hi how r u can i get a pic

**Comment by hando1818as** [comment]
If i can ur number

**Comment by LumenTeun** [comment]
@hando1818as You seem to have misunderstood GitHub.
