### ISSUE TITLE
Change the Font Size of an Element 

### ISSUE THREAD

**Issue by axiomteck** [FreeCodeCamp/FreeCodeCamp#11850]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%3Ekitty%20ipsum%20text%20Purr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .p {
    font-size: 16px;
  }
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>kitty ipsum text Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by Marcelosilva10** [comment]
<style>
  p {
    font-size: 16px;
  }
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by Manish-Giri** [comment]
@axiomteck Your code is incorrect. `p` elements are HTML elements, so they don't need the `.` in CSS, which are required for classes.

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) first for help with issues like these, in future. Happy Coding!

**Comment by axiomteck** [comment]
Yes thank you I fix it
--
Sent from www.axiomteck.com Monday, 28 November 2016, 11:55AM -08:00 from Marcelo Henrique de Souza e Silva  notifications@github.com :

><style>
  p {
    font-size: 16px;
  }
  .red-text {
    color: red;
  }
</style>

**Comment by axiomteck** [comment]
Yes thank you I fix it
--
Sent from www.axiomteck.com Monday, 28 November 2016, 11:58AM -08:00 from Manish Giri  notifications@github.com :

**Comment by erictleung** [comment]
@axiomteck sounds like your issue is resolved. I'll be closing the issue as it appears resolved. Happy coding, all!
