### ISSUE TITLE
Bug in the editor for Concatenate Arrays with concat

### ISSUE THREAD

**Issue by prashish14** [FreeCodeCamp/FreeCodeCamp#11868]
Challenge [Concatenate Arrays with concat](https://www.freecodecamp.com/challenges/concatenate-arrays-with-concat#?solution=%0Avar%20oldArray%20%3D%20%5B1%2C2%2C3%5D%3B%0Avar%20newArray%20%3D%20%5B%5D%3B%0A%0Avar%20concatMe%20%3D%20%5B4%2C5%2C6%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20newArray%20%3D%20oldArray.concat(concatMe)%3B%0Aconsole.log(newArray)%3B%0AnewArray%20%3D%20oldArray%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var oldArray = [1,2,3];
var newArray = [];

var concatMe = [4,5,6];

// Only change code below this line.
var newArray = oldArray.concat(concatMe);
console.log(newArray);
newArray = oldArray;

```

**Comment by atjonathan** [comment]
@prashish14, your code is incorrect. After setting `newArray` correctly, you set the value back to `oldArray`. 
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
