### ISSUE TITLE
Bug: Added the required challenge text but nothing happens it says i havent done it.

### ISSUE THREAD

**Issue by jdc20181** [FreeCodeCamp/FreeCodeCamp#11866]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%7B%0A%20%20%20%20font-size%3A16px%0A%20%20%20%20%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%20%3C%2Fp%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  p{
    font-size:16px
    
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot </p>


```

**Comment by dhcodes** [comment]
@jdc20181 you have an error in your code. Please consider asking for help in the chat room by clicking the Help button on the challenge.

**Comment by jdc20181** [comment]
An error? I think I know what it could be but I've been coding for over a
year this is just a side project essentially to improve my skills and get
to know clients.

**Comment by dhcodes** [comment]
Your CSS attribute does not have a `;` at the end. While not strictly required for a single CSS attribute, the tests enforce it here because it's an assumed best practice and beginners should get in the habit of using semicolons at the end of CSS attributes as there are usually more than one being applied.

We try to refrain from offering code help here in Github issues as that is the purpose of the chat room. Happy coding.

**Comment by jdc20181** [comment]
I figured it out asking for help.

It wasn't any error in my CSS. I even checked for errors.

Further more- it was the text in the <p> element that caused the issue but
no where on my screen said what o was told to place there.

Thanks

**Comment by jdc20181** [comment]
Not a beginner added it up and with what I said earlier I have around 2.5
years coding experience under my belt.
About 1.5 years web and 2.5 years Non web.
