### ISSUE TITLE
Code outputs the sentence in Title Case for all tests, but tests show as failed. 

### ISSUE THREAD

**Issue by AaravGupta** [FreeCodeCamp/FreeCodeCamp#11875]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%20%20%0A%20%20var%20y%20%20%3D%20%20%20str.toLowerCase()%3B%0A%20%20var%20x%20%20%3D%20%20%20y.split(%22%20%22)%3B%0A%20%20var%20z%20%20%3D%20%20%20%22%22%3B%0A%20%20for(var%20i%3D0%3Bi%3Cx.length%3Bi%2B%2B)%7B%0A%20%20%20%20%20%20z%20%2B%3D%20%20%20x%5Bi%5D%5B0%5D.toUpperCase()%20%2B%20x%5Bi%5D.substring(1%2C%20x%5Bi%5D.length)%3B%0A%20%20%20%20%20%20z%20%2B%3D%20%20%20%22%20%22%3B%0A%20%20%7D%0A%20return%20z%3B%0A%7D%0AtitleCase(%22I'm%20a%20little%20tea%20pot%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function titleCase(str) {  
  var y  =   str.toLowerCase();
  var x  =   y.split(" ");
  var z  =   "";
  for(var i=0;i<x.length;i++){
      z +=   x[i][0].toUpperCase() + x[i].substring(1, x[i].length);
      z +=   " ";
  }
 return z;
}
titleCase("I'm a little tea pot");

```

**Comment by raisedadead** [comment]
You are almost there!

![image](https://cloud.githubusercontent.com/assets/1884376/20752689/9adbfe40-b728-11e6-8b26-4f9615c0ebcb.png)

There is an extra space which you do not want. Happy Coding.

Please search for issues and use the help chat before reporting. 
Thanks.
