### ISSUE TITLE
Correct solution

### ISSUE THREAD

**Issue by Viniciogj** [FreeCodeCamp/FreeCodeCamp#11889]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
// Initialize these three variables
var a;
var b;
var c;

a = 5;
b = 10;
c = "I am a";

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";
 
```

**Comment by texas2010** [comment]
@Viniciogj 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
