### ISSUE TITLE
I cant complete the challenge, even after pass the github and heroku urls

### ISSUE THREAD

**Issue by zr0n** [FreeCodeCamp/FreeCodeCamp#11885]
Challenge [Timestamp Microservice](https://www.freecodecamp.com/challenges/timestamp-microservice) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by systimotic** [comment]
Hi @zr0n! Thank you for reporting this issue.

I'm sorry to hear this isn't working for you. Can you please give us more details?
If you reload the page and try again, does it work? How about a different browser?
Are you seeing any errors? Can you describe what happens after you click the submit button, or send a screencapture of what is going on?

**Comment by zr0n** [comment]
I've tried in chrome and firefox. Even after logout and relogin it is not working :C 
If someone of the main staff read this, my user is zr0n (as the github)

**Comment by dhcodes** [comment]
@zr0n can you paste your urls here?

**Comment by Bouncey** [comment]
@zr0n Are you still having issues submitting this challenge?

**Comment by zr0n** [comment]
@dhcodes  Urls: 
http://timestampmservice.herokuapp.com/January%201,%202016  
https://github.com/zr0n/timestampservice

@Bouncey  Yes, still having issues

**Comment by raisedadead** [comment]
@zr0n 

So, just to confirm you aren't able to submit the above URLs to your repo and the app on the challenge page?

Can you take some screenshots of whats happening?
Can you also take screenshots of the console (Developer Tools) for your browser and let us know if there are any errors?

**Comment by raisedadead** [comment]
@zr0n do you have any updates? We could use your help in reproducing this.
