### ISSUE TITLE
Doesn't change to blue

### ISSUE THREAD

**Issue by Commandojs1** [FreeCodeCamp/FreeCodeCamp#11886]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%7D%20blue%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 10_0_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A403 Safari/602.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {color:} blue;}
</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>


```

**Comment by texas2010** [comment]
@Commandojs1 
Thanks for reporting this. But your code is incorrect.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by Codewarr18** [comment]
it's not blue

**Comment by manunited4** [comment]
This is my code
<style>
 h1 {color:blue;}
</style>
However its not blue
