### ISSUE TITLE
Random Quote Generator - Scaffolding Needed

### ISSUE THREAD

**Issue by abigailbeets** [FreeCodeCamp/FreeCodeCamp#11887]
I'm very disappointed with this project - and I'm not new to programming. In the section before, there are very few challenges dealing with APIs, and worse, they are essentially "copy and paste this code into the html" and incredibly simple. We then make a huge leap to connecting to a website and generating random quotes, with no guidance on how we should approach the problem or how we could solve it. I know this is online coursework, but a better explanation of the requirements and more guidance concerning how to approach the problem would be helpful. It doesn't need to be paint by numbers as the challenges before it are, but there should be some scaffolding to get people where they need to be. Even if we were given a few resources such as a link to an API it would be better than what is currently on the site.

While I find the challenge to be somewhat daunting, I know I will eventually figure it out - but someone who is new to programming might be turned off.

**Comment by systimotic** [comment]
Hi @abigailbeets! Thank you for reporting this issue.

I understand what you're saying, and I agree that this is somewhat throwing the campers into the deep end while still learning to swim.
This challenge is also being discussed here https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8841, which also mentions that using an API is not a requirement. For the next project, and API is required, and there's a suggested API mentioned.
We're currently working on the curriculum expansion. It will include an update of this challenge, which is being discussed in https://github.com/FreeCodeCamp/CurriculumExpansion/issues/59

Thank you again for your comments. I'm closing this issue, as I believe it's better to continue the discussion in the issues mentioned earlier. If you think I'm wrong in closing this issue, please reopen it and add further clarification. 
Happy coding!
