### ISSUE TITLE
a good result, but does not approve of tasks

### ISSUE THREAD

**Issue by Robson3991** [FreeCodeCamp/FreeCodeCamp#11898]
Challenge [Where do I belong](https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=%0Afunction%20getIndexToIns(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20var%20index%3B%0A%20%20function%20compare(a%2C%20b)%7B%0A%20%20%20%20return%20a%20-%20b%3B%0A%20%20%7D%0A%20%20var%20sort%20%3D%20arr.sort(compare)%3B%0A%20%20for%20(var%20i%20in%20sort)%7B%0A%20%20%20%20if(num%20%3C%3D%20sort%5Bi%5D)%7B%0A%20%20%20%20%20%20%20%20index%20%3D%20i%3B%0A%20%20%20%20%20%20%20%20return%20index%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0AgetIndexToIns(%5B3%2C%2010%2C%205%5D%2C%203)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function getIndexToIns(arr, num) {
  // Find my place in this sorted array.
  var index;
  function compare(a, b){
    return a - b;
  }
  var sort = arr.sort(compare);
  for (var i in sort){
    if(num <= sort[i]){
        index = i;
        return index;
    }
  }
}

getIndexToIns([3, 10, 5], 3);

**Comment by dhcodes** [comment]
@Robson3991 I believe the last test is not being met as nothing is returned. As for the other tests, the issue has to do with your return being a string and not a number. Please consider asking for help in the chat room by clicking the Help button on the challenge.
