### ISSUE TITLE
Cursor won't go where I need it to

### ISSUE THREAD

**Issue by MelissaLynneD81** [FreeCodeCamp/FreeCodeCamp#11895]
I'm having trouble getting the cursor to go where I need it to. I click the spot and it doesn't go there.

I'm using MacOS Sierra 10.12.1 on a laptop. 

Challenge link:
https://www.freecodecamp.com/challenges/style-text-inputs-as-form-controls

That's all I know. The problem didn't happen previous to this lesson.

Thanks.

**Comment by MelissaLynneD81** [comment]
of course after I post this....it goes back to normal. Not sure what it was but it isn't doing it anymore.

**Comment by erictleung** [comment]
@MelissaLynneD81 it is probably this issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7847. If it is, please close this issue and read some suggestions on how to get around this issue over there. This is unfortunately a known issue.

**Comment by anamorell** [comment]
keep the screen on default 100% and you will be able to get the cursor anywhere
