### ISSUE TITLE
Mini project after every topic

### ISSUE THREAD

**Issue by rags4developer** [FreeCodeCamp/FreeCodeCamp#1189]
It would be great and very useful to have a mini project after each topic, even if it is not a fully functional website. This will help us to remember and apply concepts early on, instead of waiting long to reach the bonfires. It will be even better if could have multiple such projects. For now, FCC can simply suggest ideas for such projects and maybe provide the code and instructions later.

Here is an example of a course which does this - 
The Complete Web Developer Course - Build 14 Websites
https://www.udemy.com/complete-web-developer-course/

Sample mini-project for html n css topic - Build the navigation in BBC uk homepage.

![](http://www.currybet.net/images/blog2010/07/bbc_news_redesign_homepage.png)

**Comment by hgpatel16** [comment]
Also, a help button after several attempts at trying to figure out how certain thing works.

**Comment by BerkeleyTrue** [comment]
This request is not gaining any traction. Closing as stale.

Happy Coding!
