### ISSUE TITLE
Cursor fails to align at the beginning of challenge

### ISSUE THREAD

**Issue by Takashihakase** [FreeCodeCamp/FreeCodeCamp#11900]
This is a recurring issue in every challenge. At the beginning of a challenge, I would click on an area on the code. The flashing cursor is usually a row or two above or below the actual location. I always had to type something/enter to find out the actual location of the cursor. From then on, I can click anywhere on the code, and it would be the exact location where it's supposed to be. This does not hinder progress but very annoying.

**Comment by atjonathan** [comment]
@Takashihakase, this is a known issue (https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7847). Thank you for reporting!
