### ISSUE TITLE
Setup Line is missing a line

### ISSUE THREAD

**Issue by slawr1805** [FreeCodeCamp/FreeCodeCamp#11908]
Challenge [Iterate Through an Array with a For Loop](https://www.freecodecamp.com/challenges/iterate-through-an-array-with-a-for-loop#?solution=%0A%2F%2F%20Example%0Avar%20ourArr%20%3D%20%5B%209%2C%2010%2C%2011%2C%2012%5D%3B%0Avar%20ourTotal%20%3D%200%3B%0A%0Afor%20(var%20i%20%3D%200%3B%20i%20%3C%20ourArr.length%3B%20i%2B%2B)%20%7B%0A%20%20ourTotal%20%2B%3D%20ourArr%5Bi%5D%3B%0A%7D%0A%0A%2F%2F%20Setup%0Avar%20myArr%20%3D%20%5B%202%2C%203%2C%204%2C%205%2C%206%5D%3B%0Avar%20total%20%3D%200%3B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afor%20(var%20i%20%3D0%3B%20i%20%3C%20myArr.length%3B%20i%2B%2B)%20%7B%0A%20%20total%20%2B%3D%20myArr%5Bi%5D%3B%0A%7D%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

When I cleared my code, the //Setup line does not include var total = 0; which I believe is necessary for the "for loop" to run properly. After I created this line, the code ran. Since the example says to only change code below this line, other users may get confused like I did.

My code:
```javascript

// Example
var ourArr = [ 9, 10, 11, 12];
var ourTotal = 0;

for (var i = 0; i < ourArr.length; i++) {
  ourTotal += ourArr[i];
}

// Setup
var myArr = [ 2, 3, 4, 5, 6];
var total = 0;
// Only change code below this line
for (var i =0; i < myArr.length; i++) {
  total += myArr[i];
}


```

**Comment by johnnyqbui** [comment]
@slawr1805 The instructions states to declare `total` and initialize it to 0. You can declare it below the "Only change the code below this line" to make it work as well.

**Comment by dhcodes** [comment]
Yeah, it works in both places and the instructions say to declare it so I'm not sure this is a problem per se.

**Comment by slawr1805** [comment]
Thank you both for clarifying that! Is there a way to delete this post then?

**Comment by Bouncey** [comment]
We could adjust the seed to remove white space between `myArr` and the comment `Only change the code below this line`

**Comment by raisedadead** [comment]
It's stated to declare the necessary additional variable/s. Removing the white space doesn't have any significant effect unless the campers follow the instruction. IMHO this is a bikeshedding issue and may be closed.

**Comment by dhcodes** [comment]
Closing as wontfix. Will reconsider if this issue crops up again.
