### ISSUE TITLE
Waypoint: Pair Programs - LetsPair chatroom needs to be updated to Gitter

### ISSUE THREAD

**Issue by NatashaHaggard** [FreeCodeCamp/freecodecamp#1190]
Challenge http://www.freecodecamp.com/challenges/waypoint-pair-program-on-bonfires has an issue. 

http://freecodecamp.slack.com/messages/letspair - needs to be updated to Gitter (not Slack)

**Comment by benmcmahon100** [comment]
This has already been fix but has not yet been deployed. It will be deployed soon
