### ISSUE TITLE
i found a bug here and i need help as i cannot submit the challenge!! 

### ISSUE THREAD

**Issue by Clipso** [FreeCodeCamp/FreeCodeCamp#11906]
Challenge [Split your Bootstrap Row](https://www.freecodecamp.com/challenges/split-your-bootstrap-row#?solution=%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%0A%20%20%20%20%20%3Cdiv%20col-xs-6%3E%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20col-xs-6%3E%20%3C%2Fdiv%3E%0A%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
   
     <div col-xs-6> </div>
    <div col-xs-6> </div>

  </div>
</div>

```

**Comment by Clipso** [comment]
this is a a bug issue.

**Comment by dhcodes** [comment]
@clipso You have an error in your code. Please consider asking for help in the chat room by clicking the Help button on the challenge page.

**Comment by Clipso** [comment]
Hi Dylan,

Thank you for the prompt response. Yes, you are right. I found the error
and I have rectified it. already :)


Reagrds,

**Comment by fireandready** [comment]
Error code showed up not sure what is going on 
jQuery Playground
=0||Object.prototype.hasOwnProperty.call(e,s)&&(r[s]=e[s]);return r}var _extends=Object.assign||function(e){for(var t=1;t

**Comment by texas2010** [comment]
@fireandready 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by Doppies6631** [comment]
my code won't submit
