### ISSUE TITLE
I've done everything correctly but for some strange reason I can't submit and go on (it's loading and loading and loading).

### ISSUE THREAD

**Issue by Kluki11** [FreeCodeCamp/FreeCodeCamp#11903]
Challenge [Shopping List](https://www.freecodecamp.com/challenges/shopping-list#?solution=%0Avar%20myList%20%3D%20%5B%5B%22Chocolate%20Bar%22%2C%2015%5D%2C%20%5B%22Chip%22%2C%202%5D%2C%20%5B%22Book%22%2C%2010%5D%2C%20%5B%22Suit%22%2C%202%5D%2C%20%5B%22Waterbottle%22%2C%2020%5D%5D%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myList = [["Chocolate Bar", 15], ["Chip", 2], ["Book", 10], ["Suit", 2], ["Waterbottle", 20]];



```

**Comment by dhcodes** [comment]
@Kluki11 your code worked for me in both Safari and Chrome. Maybe try copying your code and then reloading your browser or resetting the code area and then paste your code back in.

**Comment by Kluki11** [comment]
Ok thanks. will try it in the evening. (y)

Gesendet mit meinem iPhone

Am 03.12.16 um 15:33 schrieb Dylan

**Comment by raisedadead** [comment]
Closing. Please comment if issue still persists.
