### ISSUE TITLE
small syntax error

### ISSUE THREAD

**Issue by cuteman100** [FreeCodeCamp/FreeCodeCamp#11915]
Challenge [Use Hex Code for Specific Colors](https://www.freecodecamp.com/challenges/use-hex-code-for-specific-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Thre is a small syntax error in a sentence:  "the symbols 0-9 represents values zero to nine. "  :
"Represent" word should be withous ending "s", as preceding words are in plural.

**Comment by Bouncey** [comment]
@cuteman100 Thanks for the issue. I would welcome a PR for this :+1:

**Comment by glynnw** [comment]
I'd like to do it if @cuteman100 isn't going to.
