### ISSUE TITLE
Return Early Pattern for Functions

### ISSUE THREAD

**Issue by sassanuv** [FreeCodeCamp/FreeCodeCamp#11913]
Challenge [Return Early Pattern for Functions](https://www.freecodecamp.com/challenges/return-early-pattern-for-functions#?solution=a%3D0%3B%0Ab%3D0%3B%0A%2F%2F%20Setup%0Afunction%20abTest(a%2C%20b)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%20%20if%20(a%3C0%20%7C%7C%20b%3C0)%7B%0A%20%20%20%20return%20%22undefined%22%3B%0A%20%20%7D%0A%20%20%20%20%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%20%20return%20Math.round(Math.pow(Math.sqrt(a)%20%2B%20Math.sqrt(b)%2C%202))%3B%0A%7D%0A%0A%2F%2F%20Change%20values%20below%20to%20test%20your%20code%0AabTest(-2%2C2)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
a=0;
b=0;
// Setup
function abTest(a, b) {
  // Only change code below this line
    if (a<0 || b<0){
    return "undefined";
  }
    
  
  
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(-2,2);

```

**Comment by Manish-Giri** [comment]
@sassanuv Please read the instructions carefully, and look at this line 
> Hint
Remember that undefined is a keyword, not a string.

**Comment by tokasravi9000** [comment]
The Solution is below: 
// Only change code below this line
   if (a < 0 || b < 0) {
    return undefined;
  }

**Comment by texas2010** [comment]
@tokasravi9000 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by obamaanakbsi** [comment]
thx.. you help me so much with this... i think undefined is a string... and i back to the leason back then... TY

**Comment by BolbotAndrii** [comment]
// Setup
function abTest(a, b) {
  // Only change code below this line
  
  if(a < 0 || b < 0)
  {
    return console.log("undefined");
  }

  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));

}

// Change values below to test your code
abTest(2,2);
