### ISSUE TITLE
Unsupported on Mac Google chrome using bootstrap:

### ISSUE THREAD

**Issue by Tech11** [FreeCodeCamp/FreeCodeCamp#11917]
Challenge [Add Font Awesome Icons to our Buttons](https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-our-buttons) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>
    </div>
  </div>
  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary">Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info">Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger">Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

Hello Team,

The bug I am facing here is that my Google Chrome doesn't imply the changes as per the code on the phone screen. 

Here's the screenshot for your reference:

![screen shot 2016-12-04 at 8 38 46 pm](https://cloud.githubusercontent.com/assets/16895842/20867040/5828e4f0-ba61-11e6-85f7-ab4953e9e6b4.png)

As you might notice, the code is correct, I am moving up the challenges, however, there is no change on the screen. When I opened the link using Safari on my Mac, it works perfect. Generally, I use Chrome more oftenly. Seems like a bootstrap waypoint challenge. Any guidance here? Is anyone else facing the same issues?

**Comment by Bouncey** [comment]
@Tech11 thanks for the issue. 

That is strange considering it looks like bootstrap is working everywhere else for you. Can you visit the challenge again, when the issue presents itself again press `F12` make a note of anything in the `console` and post it here please.

**Comment by Tech11** [comment]
@Bouncey Thank you for getting back.

Here's the sc of the console, I hope got the right thing you asked for. 

![screen shot 2016-12-05 at 6 58 39 am](https://cloud.githubusercontent.com/assets/16895842/20871125/f5ac6728-bab7-11e6-90a1-875d55964584.png)

I see a few errors which the script is making to run on my Chrome, however, as mentioned earlier it works perfectly on the Safari page. 

Let me know if we have a way I could fix it. Is it an issue generally faced by other Mac users using Chrome for the code camp?

**Comment by Bouncey** [comment]
@BerkeleyTrue would merging #11371 into production help this?

**Comment by BerkeleyTrue** [comment]
arg, yeah I have a patch in production but it involves me stashing the patch and pulling the new commits everytime there is an update. Would you mind creating a pr against backup/master that adds optimizely to the csp?

**Comment by Tech11** [comment]
Hey guys, 

Any update on the error? I have been even trying to practice Bootstrap lately using the source code or CDN from the official website using brackets, but no luck so far. Could you please guide me from here?

Thank you again for looking into it and bearing with me. :)

**Comment by systimotic** [comment]
@raisedadead The description of your PR says it closes this issue, but for some reason this issue wasn't closed. Can it be closed?
@Tech11 Sorry for the trouble. Are you still seeing the same errors? It seems like the fix was merged, but I'm not sure if it was deployed yet.

**Comment by raisedadead** [comment]
Dunno why the tag didn't work.
