### ISSUE TITLE
Challenge passes with incorrect markup

### ISSUE THREAD

**Issue by alexlincoln** [FreeCodeCamp/freecodecamp#1191]
Challenge: http://www.freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list

![2015-07-04-005151_1184x872_scrot](https://cloud.githubusercontent.com/assets/6338358/8507260/593f37ec-21ef-11e5-89cd-525a60425413.png)

Result: The challenge passes without closing my first `li` tag, which appears as three valid `li` elements
Expected: 4th condition (Make sure your li element has a closing tag) should fail.

**Comment by benmcmahon100** [comment]
this is most likely due to html's forgiving nature where it's auto generating the missing tags and therefore passing the test

**Comment by benmcmahon100** [comment]
The best example of this i can give is this
```html
<html>
    <p>Paragraph</p>
</html>
```
will be fixed by most browsers to look like this
```html
<html>
    <head>
        
    </head>
    <body>
        <p>Paragraph</p>
    </body>
</html>
```

**Comment by alexlincoln** [comment]
@benmcmahon100 yes that was my first assumption and after testing out the regex seen [here](https://github.com/FreeCodeCamp/freecodecamp/blob/staging/seed/challenges/basic-html5-and-css.json#L1465) it seems that it should work as intended - [See here](https://gist.github.com/alexlincoln/433f61f7cef4a4455ea6).

My only other issue here which I neglected to mention in my original post would be to add another assertion test for removal of all `p` elements since the instructions state to do that.

**Comment by benmcmahon100** [comment]
I can add that as a pull request if you want or you can have a go at making one! Just make sure to use http://jsonlint.com/ to validate the new data after a test is put in but if you'd prefer I can do that for you!
