### ISSUE TITLE
(ctrl + enter) does not work.

### ISSUE THREAD

**Issue by helluvalazyass** [FreeCodeCamp/freecodecamp#1192]
(ctrl + enter) does not work.

**Comment by benmcmahon100** [comment]
Can you elaborate? Is there any errors in the console? Is there a particular series of challenges?

**Comment by helluvalazyass** [comment]
No, its just in the main website while passing through the waypoints it says ""I have completed this challenge (ctrl + enter)"" . So I pressed ctrl + enter and nothing happened.

**Comment by benmcmahon100** [comment]
Were there in your browsers dev tools?
It's impossible to fix without being able to re-create or know the error that's happening

**Comment by benmcmahon100** [comment]
Out of interest what browser + OS combination are you using? I'll see if i can sort the issue

**Comment by helluvalazyass** [comment]
It was just that it takes some time after I press (ctrl+enter) , so I thought its not working, (Just slow internet connection issues). BTW thanks for quick reply. 
-Chrome on Win8

**Comment by benmcmahon100** [comment]
Ah that's cool just don't want to leave and issue! :blush:
