### ISSUE TITLE
Update Redirect when cancelling to remove account

### ISSUE THREAD

**Issue by atjonathan** [FreeCodeCamp/FreeCodeCamp#11922]
Currently when clicking cancel on the remove account modal, user is redirected to `/about`. This should be updated to redirect to `/settings`.

**Comment by ajain17** [comment]
I will take a look at it.

**Comment by atjonathan** [comment]
@ajain17, thanks! Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

**Comment by ajain17** [comment]
@atjonathan Just to be sure, you mean when we currently click on the cross button, it takes us to the about page where as it should remain on settings page. Is that right?

**Comment by atjonathan** [comment]
@ajain17, checkout @dhcodes's comment on the PR 😄

**Comment by hb237** [comment]
I will look into it..

**Comment by dhcodes** [comment]
Closed via #11923
