### ISSUE TITLE
Feature request: The ability to pin a single bonfire to the top of my profile

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#1193]
I'd like to feature my best work. This mechanism could be similar to Twitter's pinned tweet functionality.

**Comment by 1hella** [comment]
Nice idea. I like it.

**Comment by carl-parrish** [comment]
Upvoted!

**Comment by awesomeaniruddh** [comment]
Closing this because bonfires are not public anymore.

**Comment by atjonathan** [comment]
@awesomeaniruddh, portfolios can be public or private. And if a campers portfolio is public, we can implement this issue.
