### ISSUE TITLE
Seek and Destroy code solution overly difficult?

### ISSUE THREAD

**Issue by macloo** [FreeCodeCamp/FreeCodeCamp#11935]
This was the first time I looked something up in the FCC wiki. I was happy to find the hints. I had not thought to use `indexOf()`, and that enabled me to solve the problem. **However,** when I went back to the wiki and looked at the "Basic Code Solution," I thought it was too complex to be called "basic." 

#### Seek and Destroy
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Algorithm-Seek-And-Destroy 

#### Issue Description
In the wiki, the "Basic Code Solution" is not "basic." The reason I say this is because it's got a double return in the filter() callback, which is very un-basic. 

Also, the splice() is unnecessary. This is the solution code: 

```
function destroyer(arr) {
  var args = Array.prototype.slice.call(arguments);
  args.splice(0, 1);
  return arr.filter(function(element) {
    return args.indexOf(element) === -1;
  });
}
``` 

#### My Code

My code is not elegant, but it seems a lot more basic that the above. 

```
 function destroyer(arr) {
  var args = Array.prototype.slice.call(arguments, 1);
  newArray = arr.filter(function(val) {
    if ( args.indexOf( val ) >= 0 ) {
      return false;
    } else {
      return true;
    }
  });
  return newArray;
} 
```

**Comment by raisedadead** [comment]
@macloo our wiki has moved to [Forum](https://forum.freecodecamp.com), here you can search for latest articles and hints to the solutions if you find them not satisfactory please proceed with suggestions there.

Thanks for reporting.
