### ISSUE TITLE
FCC Twitch API Pass-through not returning JSON

### ISSUE THREAD

**Issue by ampersamd** [FreeCodeCamp/FreeCodeCamp#11934]
#### Challenge Name

[Twitch JSON API Challenge](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api)

#### Issue Description

The link for the FCC Twitch Pass Through API no longer returns valid JSON (regardless if callback request is passed). Returns a web page containing a note about the usage (screenshot below). Multiple users have reported similar issue.

https://wind-bow.hyperdev.space/twitch-api/streams/freecodecamp?callback=?
https://wind-bow.hyperdev.space/twitch-api/streams/freecodecamp

#### Browser Information

* Browser Name, Version: Safari 9.1.3; Chrome 54.0.2840
* Operating System: OS X El Capitan

#### Screenshot

![screen shot 2016-12-05 at 4 41 39 pm](https://cloud.githubusercontent.com/assets/12129911/20905091/685ea0a8-bb10-11e6-88e6-8ab9e6dca360.png)

**Comment by ampersamd** [comment]
Got it working. Looks like the URL was changed to "https://wind-bow.gomix.me" and the documentation just needs to be updated. Happy coding!

**Comment by dhcodes** [comment]
Tagging @Em-Ant. Looks like hyperdev changed its domain.

**Comment by Em-Ant** [comment]
@QuincyLarson should I submit a PR targeting `backup/master` too ?
