### ISSUE TITLE
k firts things first ,1. i dont understand the functionlaity of uncomment , 2. am i commenting or uncommenting 

### ISSUE THREAD

**Issue by vivek7860** [FreeCodeCamp/FreeCodeCamp#11946]
Challenge [Uncomment HTML](https://www.freecodecamp.com/challenges/uncomment-html#?solution=%0A%3C!--hello%20world...%3E%0A%3C!--h1%3EHello%20World%3C%2Fh1--%3E%0A%0A%3C!--h2%3ECatPhotoApp%3C%2Fh2--%3E%0A%0A%3C!--p%3EHello%20Paragraph%3C%2Fp--%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!--hello world...>
<!--h1>Hello World</h1-->

<!--h2>CatPhotoApp</h2-->

<!--p>Hello Paragraph</p-->


```

**Comment by williamein** [comment]
<hello world>
<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
<p>Hello Paragraph</p>

**Comment by williamein** [comment]
Be sure to delete <b>all</b> trailing comment tags, i.e. -->

**Comment by dhcodes** [comment]
@vivek7860 you have an error in your code. Please consider asking for help in the chat room by clicking the Help button on the challenge page.
