### ISSUE TITLE
Feature requet: Scheduling pair programming (especially for Ziplines and other complicated exercises)

### ISSUE THREAD

**Issue by pdsoper** [FreeCodeCamp/FreeCodeCamp#1194]
Pairing on demand seems to work fairly well for Bonfires, but I have not had any luck finding a partner to pair program a Zipline (where I think it would be even more helpful).  

Would it be possible to save requests somewhere so we could see who is working on the same Zipline and the dates / times they are available?

**Comment by 1hella** [comment]
Something like this would be nice. Especially for Ziplines where it can't necessarily be finished in one session.

**Comment by dshgna** [comment]
This would be a really great feature!

**Comment by metasean** [comment]
:+1:

**Comment by LumenTeun** [comment]
I'm not very familiar with it, but FCC has a Google Calendar set up for Twitch streams. Would it be possible to have a collaborative calendar where people could add their future coding sessions for others to "apply" to? E.g. I add an event saying I'll work on the the Random Quote Zipline on Saturday between 8 and 9, and anyone could add some sort of comment saying they'd like to pair.

**Comment by dshgna** [comment]
@LumenTeun: That sounds perfect!

Not sure how well this will fit the scenario but a quick Google search gave me Zapier and Cloudpipes which seem promising for Github and Google Calendar merging.

**Comment by Lemony-Andrew** [comment]
If I could work with the server-side of FCC I could make it so the button "Pair Programming" would send a message to the server which would hold that user's FCC ID in a list of people who want pair programming on a challenge. Anyone else on that challenge or joining that challenge would notice that the pair programming button is lit up meaning "someone is looking for pairing". Anyone who clicks on the pair programming button when someone hasn't been paired will be able to view this list. 
If someone sends a request back to that person and they accept it they will be removed from the list and their Screen Hero ID will be displayed to each other for further work.

If someone completes it before getting a friend then they will be removed from the list. If they don't have an active connection with the server they will be removed from the list.

**Comment by LumenTeun** [comment]
@dshgna I'm confused, what would the role of Zapier or Cloudpipes be?

@Lemony-Andrew That sounds pretty great. What do you mean by "If I could work"? Just clone the Git repo and get hacking :)

**Comment by Lemony-Andrew** [comment]
@LumenTeun No idea how their server is setup or how to integrate such an advanced functionality with their current setup. Never mind if they have the processing and data to support such a feature. And besides that, their would need to be a database with a password and key I could log data too.
