### ISSUE TITLE
Understand String Immutability 

### ISSUE THREAD

**Issue by LoveRoseGoddess** [FreeCodeCamp/FreeCodeCamp#11943]
Challenge [Understand String Immutability](https://www.freecodecamp.com/challenges/understand-string-immutability#?solution=%0A%2F%2F%20Setup%0Avar%20myStr%20%3D%20%22Jello%20World%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0AmyStr%5B0%5D%20%3D%20%22J%22%3B%20%2F%2F%20Fix%20Me%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 10_1_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/54.0.2840.91 Mobile/14B100 Safari/602.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStr = "Jello World";

// Only change code below this line

myStr[0] = "J"; // Fix Me



```
This challenge won't let me submit the answer even if it's wrong. It reads a "TypeError: Attempted to assign to readonly property." On the JavaScript console where my answer should be when I submit. Is this broken?
![img_0002](https://cloud.githubusercontent.com/assets/24352409/20920965/f39bbb74-bb56-11e6-84fb-4e823df9879b.PNG)

**Comment by raisedadead** [comment]
Can anyone reproduce/debug this on a native device? The OP is using Google Chrome on an iPad.

**Comment by erictleung** [comment]
While trying to simulate this with a device emulator in Chrome, I got a similar error but not the same one.

![image](https://cloud.githubusercontent.com/assets/2754821/20957514/2706bb18-bc05-11e6-9561-648dd42a40ba.png)

The challenge tests don't show up because of this type error in general. If you remove the `// Fix me` line, you at least get the challenge tests to show up and something in the console window.

**Comment by Manish-Giri** [comment]
I can try to reproduce this on my iPad. Will report on the results.

**Comment by ambatshri** [comment]
Well the challenge is documented properly. And the information says that the individual character cannot be changed in the variable. So you've to rewrite the whole string instead of rewriting the character. So its not a bug.

**Comment by raisedadead** [comment]
@ambatshri thanks, but none the less the test cases should still display. Needs more looking into.

**Comment by LoveRoseGoddess** [comment]
This wasn't very clear but after @ambatshri  commented, I rewrote the the code and got the answer correct. The "TypeError" threw me off so bad. Thanks for your help guys!

**Comment by Sean-Can** [comment]
HI i am stuck on this challenge as well. I rewrote the string as "Hello World" and still no luck.
this is my code 
// Setup
var myStr = "Hello World";

// Only change code below this line
myStr = "Hello World";
myStr[0] = "H";

**Comment by mustafizrahman8807** [comment]
// Setup
var myStr = "Hello World";

// Only change code below this line
var myStr = "Hello World";
myStr = "Hello World";

This will work I think. Good luck.
