### ISSUE TITLE
Twitch.tv API challenge is buggy as hell

### ISSUE THREAD

**Issue by kolyambo** [FreeCodeCamp/FreeCodeCamp#11940]
Challenge [Use the Twitchtv JSON API](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 YaBrowser/16.11.1.228 (beta) Yowser/2.5 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hello, please, think about this challenge one more time. Do we really need it? It's buggy as hell, there's no API for Twitch. Also, your "fix" on "https://wind-bow.hyperdev.space/twitch-api" has troubles & changing links of API. Also it doesn't support crossdomain requiests, it takes a lot of times to solve this issue.
Even first item says "1. Objective: Build a CodePen.io app that is functionally similar to this: https://codepen.io/FreeCodeCamp/full/Myvqmo/.", but link doesn't work at all !

**Comment by Manish-Giri** [comment]
@kolyambo "No API for Twitch"? Did you read through the [Twitch API](https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#get-streamschannel) docs? I've used the API, along with the API key, and it works 100% for me.

**Comment by Em-Ant** [comment]
@kolyambo we are updating the links. 
The whole Hyperdev has been suddenly renamed yesterday. It's not something that we can control. 

Regarding cross-domain requests, you should use **jsonp**, like the original API. I implemented it this way on purpose (no pain, no gain... ). 

The "fix" is a compromise of course. We built it to not force people to get their own api keys, and make the old projects work again with the minimum effort. If you think that it's not good enough, you can simply get your key and use the original API (I'd recommend this approach).

**Comment by drguildo** [comment]
> The whole Hyperdev has been suddenly renamed yesterday. It's not something that we can control.

If it's not something you can control then you probably shouldn't be depending on it.

**Comment by Em-Ant** [comment]
PR: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11937 - update twitch api link

**Comment by raisedadead** [comment]
@drguildo 

> If it's not something you can control then you probably shouldn't be depending on it.

Thanks for  your valuable suggestion, no offense, but we are a non-profit, for the community organization, so YES, we will continue to depend on resources that are best available to the community in the most economically feasible  way. Having said that we are helping 300000+ students to learn to code.

We are NOT would love to explore alternates if you have in mind. Until that happens please bear with what currently is presented by a community of hard working voluntary contributors.

Cheers! and Happy Coding.

@Em-Ant I have updated the pen, it should be working let me know for changes if any. Closing as resolved.

**Comment by drguildo** [comment]
@raisedadead I'm sorry if I upset you, I wasn't trying to. 😞

I was thinking along the lines of hosting a Twitch API pass-through on FCC controlled servers.

**Comment by raisedadead** [comment]
@drguildo Please accept my apologies, I didn't mean to direct my comment towards you, although it sounds like it. I sincerely regret saying that.
This is something generic that we often get from many campers/users in general.

I agree it would be more controllable to have our own infrastructure, but you as you probably understand that having the backend to handle micro VM's per user is highly unfeasible with the priorities that we have.

Sincere thanks for all the hard work, and contributions that you do, please keep up the good work! Thanks and Happy Coding!
