### ISSUE TITLE
recursion cause crash

### ISSUE THREAD

**Issue by jhonny-me** [FreeCodeCamp/FreeCodeCamp#11947]
#### Challenge Name

https://www.freecodecamp.com/challenges/symmetric-difference

#### Issue Description

I created a recursion function and after run test, browser dead. And i can never enter freecodecamp, cause every time i enter, it will run the function automatically, so i dead again.

#### Browser Information

* Chrome, Version: Version 54.0.2840.98 (64-bit)
* Operating System: macOS 10.12.1
* Mobile, Desktop, or Tablet: Mac Pro

#### Your Code

```js
 
 Im dead!!!!
 
```

**Comment by purpledrumsticks** [comment]
Did you try adding &run=disabled to the website url?

**Comment by jhonny-me** [comment]
https://www.freecodecamp.com/challenges/symmetric-difference&run=disabled dosent work.

**Comment by raisedadead** [comment]
@johnny-me, sad to know that you are having trouble with a recursive function. As you mentoined that run disabled code doesnt work. 

You can clear your browser cache and cookies for free code camp. This will delete all of your local code, solutions that are already submitted to your profile will still be available on your profile page.

Re-attempt the challenge and let us know how it goes.

**Comment by carlos1ready** [comment]
Can you please unsubscribe me to these emails please

**Comment by erictleung** [comment]
@carlos1ready Looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

**Comment by jhonny-me** [comment]
@raisedadead actually, the `https://www.freecodecamp.com/challenges/symmetric-difference&run=disabled` gives me a `We couldn't find a challenge with the name symmetric-difference&run=disabled. Please double check the name.` error. Am i connect the `&run=disabled` wrong?

**Comment by erictleung** [comment]
@jhonny-me try `https://www.freecodecamp.com/challenges/symmetric-difference?run=disabled`

**Comment by jhonny-me** [comment]
Great! This url works. Thx a lot. @erictleung
