### ISSUE TITLE
List of what to do does not appear before completing the test succesfully.

### ISSUE THREAD

**Issue by ppatel1604** [FreeCodeCamp/FreeCodeCamp#11955]
![capture](https://cloud.githubusercontent.com/assets/11170715/20965818/66ff6f76-bcdc-11e6-9566-f5f27e969683.PNG)
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=%0Afunction%20myLocalScope()%20%7B%0A%20%20'use%20strict'%3B%0A%20%20var%20myVar%20%3D%20%22Something%22%3B%0A%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0AmyLocalScope()%3B%0A%0A%2F%2F%20Run%20and%20check%20the%20console%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myLocalScope%0A%2F%2Fconsole.log(myVar)%3B%0A%0A%2F%2F%20Now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function myLocalScope() {
  'use strict';
  var myVar = "Something";
  
  console.log(myVar);
}
myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope
//console.log(myVar);

// Now remove the console log line to pass the test


```

**Comment by DCady02** [comment]
refresh the page, worked for me

**Comment by ajain17** [comment]
Try clearing your cookies and then reload the page. It works perfectly for me.
<img width="1417" alt="screen shot 2016-12-07 at 9 23 49 pm" src="https://cloud.githubusercontent.com/assets/5581487/20995209/7a42d564-bcc3-11e6-9246-eed1c69afc2d.png">

**Comment by ppatel1604** [comment]
@ajain17 I did that. It didn't work for me. As soon as I complete it, List appears itself.

**Comment by ajain17** [comment]
@ppatel1604  I cannot replicate your error in firefox/chrome/safari on the live site. Can anyone else confirm this?

**Comment by raisedadead** [comment]
Yes, sometimes these behaviors can be seen. Browsers can stop rendering the page correctly at times when exceptions are thrown.

It's best to try reset/refresh at those times.
