### ISSUE TITLE
Sign in Issue with Gitter chat room

### ISSUE THREAD

**Issue by wrannikko** [FreeCodeCamp/FreeCodeCamp#11958]
Challenge [Use an ID Attribute to Style an Element](https://www.freecodecamp.com/challenges/use-an-id-attribute-to-style-an-element]

the challenge isnt an issue. i ran into a problem i am trying to fix and i requested help. it brought up the chat box. i clicked sign in. i signed in, but it doesnt allow me to start chatting. it assumes i didnt even sign in. i tried multiple times to sign in, even signing in with twitter. still nothing

**Comment by Manish-Giri** [comment]
@wrannikko Did you click on "join room"?

**Comment by raisedadead** [comment]
@wrannikko You cannot sign in to Free Code Camp's chat room with Twitter. Since you have a Github account, try sign in with the GitHub account instead. 

Please share screenshots of your issue.

**Comment by wrannikko** [comment]
Thank but I figured it out
