### ISSUE TITLE
It is red

### ISSUE THREAD

**Issue by maxerd** [FreeCodeCamp/FreeCodeCamp#11960]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by raisedadead** [comment]
The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by maxerd** [comment]
Sorry I sent it before I filled it in.

**Comment by raisedadead** [comment]
No problem, you can still mention the issue in the comments here and we will reopen it for you.
