### ISSUE TITLE
Challenge not passing in chrome, firefox

### ISSUE THREAD

**Issue by khushboo13** [FreeCodeCamp/FreeCodeCamp#11963]
#### Challenge Name

https://www.freecodecamp.com/challenges/write-reusable-javascript-with-functions

#### Browser Information

* Browser Name, Version: Chrome, firefox
* Operating System: Ubuntu
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 // Example
function ourReusableFunction() {
  console.log("Heyya, World");
}

ourReusableFunction();

// Only change code below this line
function reusableFunction(myStr) {
  console.log(myStr);
}

reusableFunction("Hi World");
 
 
```

**Comment by Manish-Giri** [comment]
@khushboo13 Your code is slightly incorrect. You need to `console.log("Hi World");` from within the function definition, and it follows that you don't need to pass `myStr` or any parameters to `reusableFunction()` while calling it.
