### ISSUE TITLE
Error installing dependencies when forking the repo

### ISSUE THREAD

**Issue by alexlincoln** [FreeCodeCamp/freecodecamp#1196]
The following occurs when trying to run `npm install` as stated in the `Getting Started` section of the README

```
npm ERR! fetch failed https://github.com/FreeCodeCamp/loopback.git#fix/no-password
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
npm ERR! fetch failed https://github.com/FreeCodeCamp/loopback.git#fix/no-password
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
npm ERR! fetch failed https://github.com/FreeCodeCamp/loopback.git#fix/no-password
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! fetch failed with status code 406
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
```

This seems to be caused by [pointing to the repository directly](https://github.com/FreeCodeCamp/freecodecamp/blob/staging/package.json#L61) when it should be defining the package tarball url. Changing it to `FreeCodeCamp/loopback#fix/no-password` seems to proceed with normal installation.

Referencing: https://github.com/npm/npm/issues/7708#issuecomment-84640042

**Comment by benmcmahon100** [comment]
Yes I have had this issue also. The fix i found is to npm install again then do bower install and the npm install again.This (for me at least) fixes the problem.

**Comment by benmcmahon100** [comment]
@alexlincoln I you're happy that your fix works you can go ahead and close this issue and leave the pull request! Nice work by the way :+1:
