### ISSUE TITLE
Issue with dist-tag command and poor instruction. 

### ISSUE THREAD

**Issue by SanjeetSk** [FreeCodeCamp/FreeCodeCamp#11969]
Challenge [Manage Packages with npm](https://www.freecodecamp.com/challenges/manage-packages-with-npm) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I have following information in package.json file
```
{
  "name": "myproject1",
  "version": "1.0.1",
  "description": "my first npm project",
  "main": "index.js",
  "scripts": {
    "test": "node test.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/SanjeetSk/how-to-npm.git"
  },
  "keywords": [
    "abc"
  ],
  "author": "sanjeet",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/SanjeetSk/how-to-npm/issues"
  },
  "homepage": "https://github.com/SanjeetSk/how-to-npm#readme",
  "dependencies": {
    "@linclark/pkg": "^1.0.2"
  },
  "devDependencies": {}
}
```

my username is `sanjeet` and my command is **npm dist-tag add @sanjeet/myproject1@1.0.1 ["dev2"]**
This command is failing and I have lost hours of my time on this ####### question and its instruciton.
This is driving me away from the course.
If anybody can give me a one line solution that will be appreciated.

**Comment by raisedadead** [comment]
@SanjeetSk I understand the frustration, can you head over to https://github.com/workshopper/how-to-npm and check any workarounds exist?

**Comment by dhcodes** [comment]
@SanjeetSk this thread should help https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9558. 

Closing this issue as FCC does not manage the 'learnyou...' exercises and therefore cannot manage improvements.

**Comment by raisedadead** [comment]
Thanks @dhcodes !
