### ISSUE TITLE
Use Responsive Design with Bootstrap Fluid Containers needs Rewording

### ISSUE THREAD

**Issue by tnharvey** [freeCodeCamp/freeCodeCamp#11961]
Challenge [Use Responsive Design with Bootstrap Fluid Containers](https://www.freecodecamp.com/challenges/use-responsive-design-with-bootstrap-fluid-containers#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%3E%3C%2Fa%3E%0A%0A%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%3Cul%3E%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%3Col%3E%0A%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%3C%2Fol%3E%0A%3Cform%20fccfaa%3D%22%2Fsubmit-cat-photo%22%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Indoor%3C%2Flabel%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22radio%22%20name%3D%22indoor-outdoor%22%3E%20Outdoor%3C%2Flabel%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Loving%3C%2Flabel%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Lazy%3C%2Flabel%3E%0A%20%20%3Clabel%3E%3Cinput%20type%3D%22checkbox%22%20name%3D%22personality%22%3E%20Crazy%3C%2Flabel%3E%0A%20%20%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%20required%3E%0A%20%20%3Cbutton%20type%3D%22submit%22%3ESubmit%3C%2Fbutton%3E%0A%3C%2Fform%3E%0A%3C%2Fdiv%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>
<div class="container-fluid">
<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <label><input type="radio" name="indoor-outdoor"> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
  <label><input type="checkbox" name="personality"> Loving</label>
  <label><input type="checkbox" name="personality"> Lazy</label>
  <label><input type="checkbox" name="personality"> Crazy</label>
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>
</div>
```

Just a suggestion to change how you phrase things in this item.

The item asks the learner to wrap all HTML in the `<div class=container-fluid></div>`. When I read this, I read that to mean everything, including <style> elements, rather than the elements that would normally be wrapped in the <body> element. I've done a little with bootstrap, so I realized what you meant, but I think this might be confusing for some people. Maybe something with an example, like:

>To get started, we should nest all of the main content HTML in a `div` element with the class `container-fluid`:
```
...
</style>
<div class="container-fluid">
...
</div>
```

That's just my suggestion. Hope it helps!

**Comment by Manish-Giri** [comment]
To me, `nest all of the main content HTML` sounds a bit vague, especially the `main content HTML` bit.

**Comment by ajain17** [comment]
I'll take a look at this.

**Comment by ayoisaiah** [comment]
Here's my suggestion:

> To get started, nest all the HTML elements after the closing `</style>` tag within a `<div>` element with the class `container-fluid`. Like this:

```
...
<style>
...
</style>
<div class="container-fluid">
...
</div>
```

**Comment by tnharvey** [comment]
@ayoisaiah I like it! I think clarifies it better than my suggestion.

**Comment by ElisabetK** [comment]
The instructions appear to be incorrect: 
> To get started, we should nest **all of our HTML** in a div element with the class container-fluid.

This is the last check to pass the challenge:
> Make sure you have nested **all HTML elements** in .container-fluid. 

The wording does clearly state that all html should be wrapped in the div element, and that includes the style portion. The lesson "Use CSS Selectors to Style Elements" clearly refers to "style elements", so there is no ambiguity about including them. That is what I did, and that passed the test.

However, the next challenge shows the div wrapper excluding the style element. As someone new to Bootstrap, I did find that difference puzzling. If the standard is to not include the <style> portion, the instructions should not explicitly say that it should, with the implication that it is critical to do so.

**Comment by Manish-Giri** [comment]
@systimotic I see this has been open for a while. I'll do this..

**Comment by systimotic** [comment]
@Manish-Giri Awesome! Ping me when you have a PR 🙂

**Comment by Manish-Giri** [comment]
@systimotic How do you feel about adding a `note` after the last instruction? Something like - 
> Note
> As a reminder, HTML elements are the ones after the closing `</style>` tag. 

I think this might be better than a code example like 
```
<style>
...
</style>
<div class="container-fluid">
...
</div>
```
which might make things too easy.

**Comment by systimotic** [comment]
@Manish-Giri I don't think we ever mentioned this before, so it's not really a reminder. I like the idea of changing the description and tests to say something like "all HTML after the closing style tag" or "... after the style element"

**Comment by systimotic** [comment]
@Manish-Giri Hi! Are you still working on this?

**Comment by Manish-Giri** [comment]
@systimotic Hi! Yes, I'm just getting to this, and the other PRs, been a little help up lately.

**Comment by systimotic** [comment]
@Manish-Giri Awesome! Yeah, I've managed to build up a large backlog myself as well 😅

**Comment by Manish-Giri** [comment]
@systimotic Done! Please review 👍

**Comment by osbornhaz** [comment]
Never would've figured this out w/o help, thx!

**Comment by danava0056** [comment]
It appears the instructions are still confusing. I needed help to understand what the instructions meant.  Thanks

**Comment by Mattd1234** [comment]
`</style>
<div class= "container-fluid" </div>
`
This worked for me

**Comment by Mirvax** [comment]
if u still trying to figure out u need to put container-fluid like this
<style>
.container-fluid
......
....
...
</style>

**Comment by gwapoJay** [comment]
Thank you guys for helping...:)

**Comment by Obscureether1** [comment]
Thanks for all of the help, from reading all post was able to confirm what needed to be done. Now that being said see that there is a discussion as how to re-word this, I would like to put in my "two-cents".... should be word something like this.......

To get started, we should nest all of our MAIN  HTML in a div element with the class container-fluid.

So ending like this 

<style>
............
. Container-fluid
.........
<\style>
<div class= "container-fluid" >
........
......
<\div>
