### ISSUE TITLE
This is already blue

### ISSUE THREAD

**Issue by tyra134** [FreeCodeCamp/FreeCodeCamp#11973]
Challenge [Use RGB to Mix Colors](https://www.freecodecamp.com/challenges/use-rgb-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20rgb(255%2C0%2C0)%3B%0A%20%20%7D%0A%20%20.orchid-text%20%7B%0A%20%20%20%20color%3A%20rgb(218%2C112%2C214)%3B%0A%20%20%7D%0A%20%20.sienna-text%20%7B%0A%20%20%20%20color%3A%20rgb(160%2C82%2C45)%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20color%3A%20rgb(0%2C0%2C225)%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orchid-text%22%3EI%20am%20orchid!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22sienna-text%22%3EI%20am%20sienna!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22blue-text%22%3EI%20am%20blue!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
   .red-text {
    color: rgb(255,0,0);
  }
  .orchid-text {
    color: rgb(218,112,214);
  }
  .sienna-text {
    color: rgb(160,82,45);
  }
  .blue-text {
   color: rgb(0,0,225);
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>

```

**Comment by raisedadead** [comment]
@tyra134 thanks for the issue, but your code is not correct. It's blue but not the correct one.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by tyra134** [comment]
Thanks I copied and pasted it, and then it worked.

**Comment by guillegn** [comment]
I have the same problem. What do you mean you copy paste and the worked?

**Comment by guillegn** [comment]
And what's then the correct blue? @raisedadead. In the chat nobody answer

**Comment by raisedadead** [comment]
@guillegn Apologies, yeah chat rooms can get busy sometimes, you can look thru the forums for any specific challenge, I am sure this challenge has been visited before.
