### ISSUE TITLE
Run Test Does Not Work

### ISSUE THREAD

**Issue by hamrasalim** [FreeCodeCamp/FreeCodeCamp#11971]
Challenge [Make Dead Links using the Hash Symbol](https://www.freecodecamp.com/challenges/make-dead-links-using-the-hash-symbol) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a #="http://www.freecatphotoapp.com">cat photos</a>.</p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by raisedadead** [comment]
@hamrasalim Thanks for the issue, but your code is not correct! 

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by hamrasalim** [comment]
Yes, sorry about that. Its the first time that i made a coding error so i assumed that id get an error message if it was wrong.
Best,Salim


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: mrugesh <notifications@github.com> Date: 12/8/16  8:44 PM  (GMT+04:00) To: FreeCodeCamp/FreeCodeCamp <FreeCodeCamp@noreply.github.com> Cc: Salim Hamra <hamrasalim@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [FreeCodeCamp/FreeCodeCamp] Run Test Does Not Work (#11971) 
@hamrasalim Thanks for the issue, but your code is not correct!
The issue tracker is for reporting bugs only. Please use the help chat room or try looking through the forum for help with a specific challenge.
Happy Coding.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeCodeCamp/FreeCodeCamp","title":"FreeCodeCamp/FreeCodeCamp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FreeCodeCamp/FreeCodeCamp"}},"updates":{"snippets":[{"icon":"PERSON","message":"@raisedadead in #11971: @hamrasalim Thanks for the issue, but your code is not correct! \r\n\r\nThe issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.\r\n\r\nHappy Coding."}],"action":{"name":"View Issue","url":"https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11971#issuecomment-265788572"}}}
