### ISSUE TITLE
You must target the children of element with the target class. (Needs re-wording)

### ISSUE THREAD

**Issue by szrharrison** [FreeCodeCamp/FreeCodeCamp#11984]
#### Challenge Name

Target a Specific Child of an Element Using jQuery
https://www.freecodecamp.com/challenges/target-a-specific-child-of-an-element-using-jquery

#### Issue Description

Wording in the instructions is extremely misleading&mdash;and not grammatically correct.

This has been mentioned several times but it hasn't been changed and there doesn't seem to be any alternative wording suggested, so, here goes:

 > _**You must select the elements' children with the target class.**_

Issues with the old wording:
 > Make the second child in each of your well elements bounce. 
 > _**You must target the children of element with the target class.**_
 * I don't know why this uses the word "target" to describe what we're doing when working with CSS selectors. Select is the more obvious and less confusing verb to use.
   * You must **select** the children of element with the target class.
 * As mentioned in the previous sentence, there are multiple elements we are referring to.
    * You must select the children of element**s** with the target class.
 * Let's please keep using articles! There are a lot of non-native English speakers that use FCC and it doesn't do them any favors when they see improper grammar used on the site. 😛 
    * You must select the children of **the** elements with the target class.
 * Placing 2 or more prepositional phrases side by side is often confusing. E.g.: The Venusians swam | _for two hours_ | _after lunch_ | _in my pool_. could imply that lunch was eaten in the pool, followed by two hours of swimming. That's why people are thinking that _of element_ | _with the target class_ means that the element has the class of target, instead of the children.
    * | _With the target class_ |, you must select the children | _of the elements_ |. would be a better way to write it, but it's even clearer to avoid using 2 prepositional phrases. By just changing one of them to an adjective: You must select the **elements'** children | _**with the target class**_ |. it becomes obvious that | _with the target class_ | is not describing elements. 🎉 

Sorry if this is too long. I can get somewhat weird when it comes to explaining things! 👽

**Comment by ajain17** [comment]
The OP is correct. I'd agree with making these changes for more clarity. If anybody else approves this change, I'll push the fix.

**Comment by raisedadead** [comment]
@szrharrison Thanks Scott. You absolutely rock! Would you interested in helping us out more by logging such grammar issues? 

@ajain17 please make a pull request, whenever you are ready, and thanks for taking the interest in fixing these.

**Comment by szrharrison** [comment]
@raisedadead Absolutely! I'll keep mentioning things as I go through the program. Is submitting issues the best way for me to bring them to attention or is there some other way that would be preferable?

**Comment by ajain17** [comment]
As you see issues/enhancements, you can create an issue and someone will fix it asap. Any outstanding issues are picked up by contributors sooner or later.
