### ISSUE TITLE
Check for Palindromes Challenge

### ISSUE THREAD

**Issue by victorhugorch** [FreeCodeCamp/FreeCodeCamp#11988]
#### Check for Palindromes
https://www.freecodecamp.com/challenges/check-for-palindromes

#### Issue Description

This function returns false in my browser but in the FreeCodeCamp interpreter it is returning true.

#### My Code

```
function palindrome(str) {
  if(str == str.split("").reverse().join("")){
    return true;
  }
  return false;
}
palindrome("not a palindrome");
```

#### Browser Information

* Browser Name, Version: Chrome 54.0.2, Firefox. Desktop.

**Comment by raisedadead** [comment]
<img width="1060" alt="screen shot 2016-12-10 at 10 28 56 pm" src="https://cloud.githubusercontent.com/assets/1884376/21074810/155759c4-bf28-11e6-89a1-076f22c65a08.png">

I am getting a false. Mind sharing a screenshot, and any errors that you are getting on your browser console (Dev tools).
