### ISSUE TITLE
The desired output is not being shown on most Javascript Challenges

### ISSUE THREAD

**Issue by NatashaRocha** [FreeCodeCamp/FreeCodeCamp#11982]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22FirstLine%5Cn%5C%5CSecondLine%5C%5C%5CrThirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "FirstLine\n\\SecondLine\\\rThirdLine";

```

**Output:**

`myStr = "FirstLine\n\\SecondLine\\\rThirdLine"`

**Should be:**
```
FirstLine
\SecondLine\
ThirdLine
```

Most javascript challenges don't show the desired output, they show us what we wrote. This one, for example, is for teaching us how escaping characters work, so it should show the escaped characters.

**Comment by ajain17** [comment]
I can replicate the issue at my end.

**Comment by raisedadead** [comment]
@NatashaRocha thanks a lot for the issue. 

JavaScript Challenges currently show the console.log of the last statement of the Seed (Editor) code that is executed by the code runner.

In case of a function, as seen in some challenges it is the output of function's return statement.

This is usually parsed via a console.log

Yes, I agree in some cases like this challenge we need/expect an output different that.
This needs a bit of an overhaul to the way outputs are generated, for specifically such challenges.

Looking forward to inputs from others before going forth.

**Comment by systimotic** [comment]
@raisedadead This has been resolved in Beta. Can this be closed?

**Comment by raisedadead** [comment]
@systimotic thanks for confirm. I realized this a bit late.
