### ISSUE TITLE
Typo in challenge text

### ISSUE THREAD

**Issue by mikeiscoding** [FreeCodeCamp/FreeCodeCamp#11992]
Challenge [Target Elements by ID Using jQuery](https://www.freecodecamp.com/challenges/target-elements-by-id-using-jquery#?solution=%0Afccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22button%22).addClass(%22animated%20bounce%22)%3B%0A%20%20%20%20%24(%22.well%22).addClass(%22animated%20shake%22)%3B%0A%20%20%20%20%24(%22%23target3%22).addClass(%22animated%20fadeout%22)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("button").addClass("animated bounce");
    $(".well").addClass("animated shake");
    $("#target3").addClass("animated fadeout");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

There's a typo in the challenge text: 'fade0ut' instead of 'fadeout' ..

I assume most people will see this is a typo, but I guess there will be some people who won't be able to pass the challenge because they think they should type 'fade0ut'.

If there is a better way to report typos and such, please let me know.

![screen shot 2016-12-10 at 22 32 02](https://cloud.githubusercontent.com/assets/24467398/21076318/887ef632-bf28-11e6-9557-0dce4a658d73.png)

**Comment by Manish-Giri** [comment]
@mikeiscoding Isn't the class name `fadeOut`?

**Comment by raisedadead** [comment]
This is a `camelCase` class name, and not an typo IMHO.

**Comment by erictleung** [comment]
Yeah, this doesn't look like a typo http://api.jquery.com/fadeOut/. It looks to be case-insensitive so I also don't see an error here.

**Comment by mikeiscoding** [comment]
It's fade0ut with a zero, not fadeOut with a capital 'O.'

**Comment by mikeiscoding** [comment]
Thanks for the swift replies, everyone and thanks for linking the jQuery documentation. I'm new so I'm glad such a resource exists.. however, as I noted in my previous comment, it's fade0ut with a zero, not a capital 'O.' 

Is this the best place to report typos?

(Also closed the issue on accident, misclicked.)

**Comment by mikeiscoding** [comment]
I just copy-pasted the original text and it turns out to be a capital 'O' after all. I should've done that before my previous comment. Sorry guys. 

Closing the issue.
