### ISSUE TITLE
Code editor cursor issue

### ISSUE THREAD

**Issue by OMAsphyxiate** [FreeCodeCamp/FreeCodeCamp#11993]
Throughout my progressions of the HTML5 & CSS challenges, each time I am asked to add/edit any code within the code editor the cursor within the editor does not show up where intended. I have to begin typing or editing the code via keyboard before the cursor will fix itself and allow me to select the desired location in order to edit or add in the correct spot. While this doesn't prevent users from completing the challenge, it is very stressful constantly having to play "Hide & Seek" with the text cursor when attempting to edit code.

**Comment by kevcomedia** [comment]
Hi. This is a known issue. See #7847 
Closing this as duplicate.
