### ISSUE TITLE
You should only be targeting one element and adding only one class at a time. Altogether, your three individual selectors will end up adding the three classes shake, animated, and btn-primary to #target1.

### ISSUE THREAD

**Issue by educrvz** [FreeCodeCamp/FreeCodeCamp#11996]
#### Challenge Name: Target the same element with multiple jQuery Selectors

www.freecodecamp.com/challenges/target-the-same-element-with-multiple-jquery-selectors

#### Issue Description: Note message incorrect.

In the descriptions is states:
Note: You should only be targeting one element and adding only one class at a time. Altogether, your three individual selectors will end up adding the three classes shake, animated, and btn-primary to #target1.

This is not correct, as from this msg above one understands that all 3 classes (shake, animated, and btn-primary) will be applied (only) to #target1... and that is not true.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by erictleung** [comment]
@educrvz can you elaborate a bit on your concern? I don't see any inconsistencies in the text. Each of the instructions is consistent with the statement

> You should only be targeting one element and adding only one class at a time. 

And then text following that will also be true after applying the three classes. The parenthetical you added of `(only)` does make that statement not true. Meaning that those three classes added all do not apply to *just* `#target1`. However, there is no `only` in the text.

Also, if you could give a suggested change in the instructions, that'll help clarify your concern for the wording of in this challenge. Thanks!

**Comment by kevcomedia** [comment]
How about
> You should only be targeting **one element/class/id** and adding only one class at a time.

Maybe "one element" can easily be mistaken to mean "one HTML element".

**Comment by educrvz** [comment]
Thank you for taking the time to read my issue. After reading it through a few times I understand the instructions and they are correct.

I believe it would help the user if you could:

Change the instructions, so that target1 shakes. This would make it visually clear to the user, that all buttons and btn have classes animated and btn-primary, but on #target1 has all 3 (animated, btn-primary and shake).

Either way, thanx again!
