### ISSUE TITLE
"Build a wikipedia viewer" link doesn't work correctly

### ISSUE THREAD

**Issue by Madmanden** [FreeCodeCamp/FreeCodeCamp#11995]
#### Challenge Name
https://www.freecodecamp.com/challenges/build-a-wikipedia-viewer

#### Issue Description

The pen in the challenge link doesn't work, so campers can't use it to see the functionality example.

https://codepen.io/FreeCodeCamp/full/wGqEga/

#### Code
The follow just shows:
```main(ng-app='WikiApp' ng-controller='MainCtrl') #search.wrapper.fullHeight a.white-text(href='https://en.wikipedia.org/wiki/Special:Random' target='_blank') Click here for a random article br form(ng-submit='search()') input(type='text' ng-model='searchTxt') .eks p.white-text#help Click icon to search .wrapper ul a(ng-href='{{result.page}}' target='_blank' ng-repeat='result in results') li h1 {{result.title}} p {{result.body}}```

**Comment by erictleung** [comment]
@Madmanden thanks for catching this! It looks like there is an extra space that shouldn't be there in the `.jade` HTML on Line 8. There needs to be one less space in front of this line.

```html
    p.white-text#help Click icon to search
```

@FreeCodeCamp/moderators can someone confirm and/or make changes to this CodePen whoever has privileges to it?

**Comment by raisedadead** [comment]
Issue fixed.
