### ISSUE TITLE
Unable to update Twitter/LinkedIn accounts 

### ISSUE THREAD

**Issue by majlind** [FreeCodeCamp/FreeCodeCamp#11991]
In Dec 2015 I updated my account with a twitter handle and a linkedin account but since then I've changed my username on both sites. As of Dec 2016 I'm unable to update either in the settings. When I hover over either the twitter/linkedin logos it displays the old username but offers no choice for updating to a new one.

It's not a huge issue, moreso one for the few of us who've changed their twitter/linkedin handles.

**Comment by raisedadead** [comment]
@majlind please email the same to team@freecodecamp.com, we are currently in the process of having a feature to update the usernames for twitter and LinkedIn shortly.

This is being discussed on a separate thread.
Refer : https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10807#issuecomment-257653781
