### ISSUE TITLE
I am not able to do the task of Escape sequences in strings

### ISSUE THREAD

**Issue by ajitkumarsahu** [FreeCodeCamp/FreeCodeCamp#11994]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D%22FirstLine%5Cn%5C%5CsecondLine%5C%5C%5CrThirdLine%22%3B%0A%0A%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 UBrowser/5.7.16817.1002 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr="FirstLine\n\\secondLine\\\rThirdLine";

// Change this line



```

**Comment by Manish-Giri** [comment]
@ajitkumarsahu `SecondLine` - `s` should be capital. 

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) first for help with challenges like these, in future. Happy Coding!

**Comment by raisedadead** [comment]
Thanks @Manish-Giri, Closing at not an issue with the codebase.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by ajitkumarsahu** [comment]
hey giri thanx yar .
It's great you helped me .
and by the way It worked...........😀😀😀😀😀😀
