### ISSUE TITLE
i have tried this js code on my browser and it 100% works, but when i try it on the site , it doesn't

### ISSUE THREAD

**Issue by anasibrahimgm** [FreeCodeCamp/FreeCodeCamp#11999]
Challenge [Make Object Properties Private](https://www.freecodecamp.com/challenges/make-object-properties-private#?solution=var%20Car%20%3D%20function()%20%7B%0A%09%09%20%20%2F%2F%20this%20is%20a%20private%20variable%0A%09%09%20%20var%20speed%20%3D%2010%3B%0A%0A%09%09%20%20%2F%2F%20these%20are%20public%20methods%0A%09%09%20%20this.accelerate%20%3D%20function(change)%20%7B%0A%09%09%20%20%20%20speed%20%2B%3D%20change%3B%0A%09%09%20%20%7D%3B%0A%0A%09%09%20%20this.decelerate%20%3D%20function()%20%7B%0A%09%09%20%20%20%20speed%20-%3D%205%3B%0A%09%09%20%20%7D%3B%0A%0A%09%09%20%20this.getSpeed%20%3D%20function()%20%7B%0A%09%09%20%20%20%20return%20speed%3B%0A%09%09%20%20%7D%3B%0A%09%09%7D%3B%0A%0A%09%09var%20Bike%20%3D%20function()%20%7B%0A%0A%09%09%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%09%09%20%20var%20gear%3B%0A%09%09%20%20this.getGear%20%3D%20function(x)%7B%0A%09%09%20%20%20%20return%20x%3B%0A%09%09%20%20%7D%3B%0A%09%09%20%20this.setGear%20%3D%20function(y)%7B%0A%09%09%20%20%20%20return%20this.getGear(y)%3B%0A%09%09%20%20%7D%3B%0A%09%09%20%20%0A%0A%09%09%7D%3B%0A%0A%09%09var%20myCar%20%3D%20new%20Car()%3B%0A%0A%09%09var%20myBike%20%3D%20new%20Bike()%3B%0A%0A%20%20%20%20%20%20%20%20myBike.setGear(4)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Car = function() {
		  // this is a private variable
		  var speed = 10;

		  // these are public methods
		  this.accelerate = function(change) {
		    speed += change;
		  };

		  this.decelerate = function() {
		    speed -= 5;
		  };

		  this.getSpeed = function() {
		    return speed;
		  };
		};

		var Bike = function() {

		  // Only change code below this line.
		  var gear;
		  this.getGear = function(x){
		    return x;
		  };
		  this.setGear = function(y){
		    return this.getGear(y);
		  };
		  

		};

		var myCar = new Car();

		var myBike = new Bike();

        myBike.setGear(4);

```

**Comment by systimotic** [comment]
Hi @anasibrahimgm! Thank you for reporting this issue.

This is not an issue with Free Code Camp, it is an issue with your code.
If I run `myBike.setGear(2)` it returns the number I passed it, but if I call `myBike.getGear()` without any arguments it returns `undefined`.

If you need coding help, please click the "Help" button on the challenge instead.

If you think I'm wrong in closing this issue, please reopen it and add further clarification.
Happy coding!
