### ISSUE TITLE
hello <h1>

### ISSUE THREAD

**Issue by Sidar123** [FreeCodeCamp/FreeCodeCamp#12003]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3E%20my%20name%20is%20sidar%3C%2Fh1%3E%20%0A%3Ch2%3E%20I%20have%20no%20idea%20what%20to%20do%20now%20%3A)%20%3C%2Fh2%3E%0A%0A%3Ch3%3E%20how%20can%20I%20go%20to%20the%20next%20level%3C%2Fh3%3E%0A%3Ch4%3E%20I%20am%20still%20bussy%20with%20writing%20%3C%2Fh4%3E%0A%3Ch5%3E%20omg%20what%20is%20the%20next%20step%20now%3C%2Fh5%3E%0A%3Ch6%3E%20I%20dont%20see%20any%20button%20to%20ga%20another%20exercises%3C%2Fh6%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello</h1>
<h1> my name is sidar</h1> 
<h2> I have no idea what to do now :) </h2>

<h3> how can I go to the next level</h3>
<h4> I am still bussy with writing </h4>
<h5> omg what is the next step now</h5>
<h6> I dont see any button to ga another exercises</h6>

```

**Comment by Manish-Giri** [comment]
@Sidar123 You're supposed to write `Hello World` between your `h1` tags. Once you do that, click on "run tests" on the left!

This is the pattern for all the challenges here on FreeCodeCamp. Write your code according to the instructions on the left, then click on "Run Tests" to proceed to the next challenge. Happy Coding!

**Comment by Sidar123** [comment]
@Manish-Giri  I am new here :) I try to find my way. I think githup is not the place to set the questions :) thank you for your quick answer!

**Comment by Manish-Giri** [comment]
@Sidar123 Yes, there is a [Help Room](https://gitter.im/FreeCodeCamp/Help) which you can visit for any help with these challenges! Github is more of a place to report issues with the FCC website itself.

**Comment by raisedadead** [comment]
Thanks @Manish-Giri and @Sidar123 

Happy coding!
