### ISSUE TITLE
No repeats please. 

### ISSUE THREAD

**Issue by andy2577** [freeCodeCamp/freeCodeCamp#12000]
Unresponsive script warning. 
When I run this script my browser hangs-up. When I try same script running on https://repl.it/languages/javascript   I get expected results. However not on FreeCodeCamp site. It might be only an Ubuntu issue, however I thought that is worth it to submit just in case someone else has the same issue.

If you change" i < n"; to "i < n-1" in generate function for permutations script will run however it doesn't generate right amount of permutations.

Challenge [No repeats please](https://www.freecodecamp.com/challenges/no-repeats-please#?solution=%0Afunction%20permAlone(str)%20%7B%0A%20%20%0A%20%20%0A%20%20str%20%3D%20generate(str)%3B%0A%20%20function%20generate(string)%7B%0A%20%20%20%20var%20arr%20%3D%20string.split(%27%27)%3B%0A%20%20%20%20var%20permutations%20%3D%20%5B%5D%3B%0A%20%20%20%20%0A%20%20%20%20function%20swap(a%2C%20b)%7B%0A%20%20%20%20%20%20var%20tmp%20%3D%20arr%5Ba%5D%3B%0A%20%20%20%20%20%20arr%5Ba%5D%20%3D%20arr%5Bb%5D%3B%0A%20%20%20%20%20%20arr%5Bb%5D%20%3D%20tmp%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20function%20generate(n)%7B%0A%20%20%20%20%20%20if(n%3D%3D%3D1)%7B%0A%20%20%20%20%20%20%20%20permutations.push(arr.join(%27%27))%3B%0A%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20n%3B%20%2B%2Bi)%7B%0A%20%20%20%20%20%20%20%20%20%20generate(n-1)%3B%0A%20%20%20%20%20%20%20%20%20%20swap(n%20%25%202%20%3F%200%20%3A%20i%2C%20n-1)%3B%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%2F%2Fgenerate(n-1)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%0A%0A%20%20%20%20%0A%20%20%20%20generate(arr.length)%3B%0A%20%20%20%20return%20permutations%3B%0A%20%20%7D%0A%20%20return%20str%3B%0A%7D%0A%0ApermAlone(%27abc%27)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function permAlone(str) {
  
  
  str = generate(str);
  function generate(string){
    var arr = string.split('');
    var permutations = [];
    
    function swap(a, b){
      var tmp = arr[a];
      arr[a] = arr[b];
      arr[b] = tmp;
    }
    
    function generate(n){
      if(n===1){
        permutations.push(arr.join(''));
      } else {
        for (var i = 0; i < n; ++i){
          generate(n-1);
          swap(n % 2 ? 0 : i, n-1);
          
        }
        //generate(n-1);
      }
    }
    
    

    
    generate(arr.length);
    return permutations;
  }
  return str;
}

permAlone('abc');

```

**Comment by ajain17** [comment]
@raisedadead Can we add help wanted label to this. Its a valid issue and I can replicate it.

**Comment by raisedadead** [comment]
The problem is repl.it runs the JavaScript on a dedicated container on server side. We do it in browser. So there is a bit of a limitation.

@ajain17 do you have any suggested fixes in mind?

**Comment by ajain17** [comment]
Hi,

I don't, at the moment. I can try and work on this over the weekend if we do not find help till then. Too swamped with work and trying to triage quick issues for now.

**Comment by klanmiko** [comment]
The algorithm at hand is O(n!) and does not in fact pass any of the test cases. The unresponsive script arises especially within the test for large strings as the browser is trying to compute. I don't think this is something that is worth looking into.
