### ISSUE TITLE
Markup generated is different on the client or server

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#12006]
When `gulp` is running:

* I open a window and navigate to `localhost:3000` then close this window,
* without stopping `gulp`,
* I open a new tab and navigate to `localhost:3000` I get this warning in my console

> bundle.js:2644 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:...(different sections of markup)

This can happen when `makeToast` is dispatched on mount.

**Comment by BerkeleyTrue** [comment]
From what you are describing, this is what happens due to a device I added to make hot-reloading save the state of the redux store before forcing refresh. If this is correct, this does not happen in production.
