### ISSUE TITLE
One test which should pass fails - beats me

### ISSUE THREAD

**Issue by shapir** [FreeCodeCamp/FreeCodeCamp#12004]
<strong>getIndexToIns([5, 3, 20, 3], 5) should return 2. fails - not sure why</strong>

Also not sure why console.log does not work for me, so I can't debug effecively.

Challenge [Where do I belong](https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=%22use%20strict()%22%3B%0A%0Afunction%20getIndexToIns(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20arr.sort()%3B%0A%20%20for%20(var%20i%3D0%3Bi%3Carr.length%3B%2B%2Bi)%20%7B%0A%20%20%20%20if%20(arr%5Bi%5D%20%3E%3D%20num)%0A%20%20%20%20%20%20return%20i%3B%0A%20%20%7D%0A%20%20return%20arr.length%3B%0A%7D%0Avar%20z%20%3D%20getIndexToIns(%5B5%2C%203%2C%2020%2C%203%5D%2C%205)%3B%0Aconsole.log(%22Returned%20z%3A%20%22%20%2B%20z)%3B%0AgetIndexToIns(%5B40%2C%2060%5D%2C%2050)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
"use strict()";

function getIndexToIns(arr, num) {
  // Find my place in this sorted array.
  arr.sort();
  for (var i=0;i<arr.length;++i) {
    if (arr[i] >= num)
      return i;
  }
  return arr.length;
}
var z = getIndexToIns([5, 3, 20, 3], 5);
console.log("Returned z: " + z);
getIndexToIns([40, 60], 50);

```

**Comment by Manish-Giri** [comment]
@shapir If you study the documentation on `.sort()` linked in the challenge, you'll find - 
> The default sort order is according to string Unicode code points.

**Comment by shapir** [comment]
Thanks, @Manish-Giri that was it - I've surely learned something new today!
Changed code as below - worked fine :-)

arr.sort(compareNumbers);

function compareNumbers(a, b) {
  return a - b;
}
