### ISSUE TITLE
Upgrade JQuery major version

### ISSUE THREAD

**Issue by petrgazarov** [freeCodeCamp/freeCodeCamp#12015]
As reported by [Snyk](https://snyk.io/test/npm/jquery/2.1.4), JQuery 2 has a Cross-site Scripting vulnerability, which is fixed in JQuery 3.0.0 and higher.

From [JQuery website](https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/):

"Despite the 3.0 version number, we anticipate that these releases shouldn’t be too much trouble when it comes to upgrading existing code. Yes, there are a few “breaking changes” that justified the major version bump, but we’re hopeful the breakage doesn’t actually affect that many people."

So hopefully it won't be very difficult to upgrade!

**Comment by raisedadead** [comment]
We need help in upgrading the same to major version, which would include extensive testing with the jQuery challenges, and the sections of code that use jQuery.
