### ISSUE TITLE
Show completed code in editor

### ISSUE THREAD

**Issue by dshgna** [FreeCodeCamp/FreeCodeCamp#1201]
Currently, when a challenge is completed, and we go to the next task and then come back, the editor displays the starting code fragment of an unattempted challenge. 

If it displayed the completed code, we can just go back, see how we solved something and refactor it. An added advantage would be that in the case we don't have anyone to pair program with, we can do a quick peer review when a pair programmer is available.

**Comment by metasean** [comment]
It would also be nice if we could see other campers' solutions (ala http://www.codewars.com).

**Comment by dshgna** [comment]
@metasean: Ditto. I think this can be added as a feature of its own. I really enjoy the structure of CodeWars.

**Comment by LumenTeun** [comment]
This shouldn't be very hard to implement; I'll check see if I can do something.

@metasean We can see other campers' solutions, just go to their profile and you'll find every Bonfire and Zipline solution they have. (Possibly the Basejumps as well, although I'm not sure)

**Comment by metasean** [comment]
@LumenTeun - While codewars does identify the individual users who submitted a given category of solution (I have mixed feelings about that), what it does really well is show you grouped solutions for a kata that you have completed, with higher ranked solutions at the top of the list.  In other words, I don't care what *username*'s solution is, I care about seeing solutions that are higher quality than my own.  Does that distinction make sense?

**Comment by LumenTeun** [comment]
@metasean It makes sense, yes. If you want to discuss it, please create a separate issue, so we're not crowding this one with unrelated discussion :)

**Comment by benschenker** [comment]
I believe this is actually done as part of the [August Improvements](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/August-2015-Improvements).
