### ISSUE TITLE
https://codepen.io/charan1922/pen/Mbqzba

### ISSUE THREAD

**Issue by charan1922** [FreeCodeCamp/FreeCodeCamp#12017]
what is  problem in my code , it is nt showing any output?

Challengellenge [Build a Random Quote Machine](https://www.freecodecamp.com/challenges/build-a-random-quote-machine) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36 OPR/41.0.2353.69</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by Manish-Giri** [comment]
@charan1922 What's the problem? Could you give some more details?

If you need help with your code for the random quote machine, please consider visiting the [Help JS](https://gitter.im/FreeCodeCamp/HelpJavaScript) room.

**Comment by dhcodes** [comment]
Closing for now. Please reopen if you've found an issue with a challenge on the site.
