### ISSUE TITLE
HTML5, CSS & Bootstrap challenges impossible if screen width too small

### ISSUE THREAD

**Issue by KrisVos130** [FreeCodeCamp/freecodecamp#1202]
When your screen width is so small that the page content goes vertical, you can't click on anything other than the footer, the navbar and the code itself. You can't click on the More Information, help and bug buttons. Being logged in or not does not matter for this issue, it happens either way.

Tested on
Windows 7:
  - Mozilla Firefox has this issue
  - Google Chrome has this issue
  - Internet Explorer does not have this issue

**Comment by benmcmahon100** [comment]
This is how the site is meant to work but you are correct in saying that there is an issue and I'll create a fix for that now.

**Comment by benmcmahon100** [comment]
Sorry for the delayed response but i can confirm that there is a fix for this incoming and will hopefully be live within a week! If there's anything else you need help with or want to ask about please do not hesitate! Otherwise you can close this issue! :relaxed:

**Comment by LumenTeun** [comment]
@benmcmahon100 could you link to the PR or commit that fixes this?

**Comment by benmcmahon100** [comment]
@LumenTeun It's already in staging so I'm not sure when exactly but I tested to confirm the bug then checked my local build of staging and the issue had appeared to have been fixed! Unless you have a local copy that still has this behavior I'd say we're good but we wont know for sure until staging goes live within the week.

**Comment by KrisVos130** [comment]
@benmcmahon100 @LumenTeun Since it has been fixed, I'll close this issue. Thanks :smile:
