### ISSUE TITLE
JavaScript - StringEscapeCarater

### ISSUE THREAD

**Issue by wanted70a** [FreeCodeCamp/FreeCodeCamp#12027]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%3B%20myStr%3D%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quotes%5C%22%22%3B%0A%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr; myStr="I am a \"double quoted\" string inside \"double quotes\"";





```

**Comment by Manish-Giri** [comment]
@wanted70a Your code is incomplete. You're missing the `.` required at the end, after `double quotes`.

Please visit the [Help JS](https://gitter.im/FreeCodeCamp/HelpJavaScript) room if you need help with challenges like these, in future.

**Comment by wanted70a** [comment]
Thanks, I thought it's a bug :).
