### ISSUE TITLE
Golf Code Challenge

### ISSUE THREAD

**Issue by tonystaark** [freeCodeCamp/freeCodeCamp#12022]
Golf Code

For this challenge, I have no problem passing it. However I did find a logic issue here. Suppose I put any figure for par, but put a zero for scores. How could that be an "Eagle"? It does not make sense in real life. Can't believe no one has ever found out this so far. LOL

**Comment by dhcodes** [comment]
This is true. One option may be to change the Eagle to be `= par - 2` and add a return for an albatross that is `= par - 3`. 

Another option may be to add a case for `0` that returns `"didn't play this hole?"` or something to that effect.

**Comment by JosephLivengood** [comment]
I like the idea of making the user account for common things that could go wrong such as a score of `0`

**Comment by erictleung** [comment]
To combat these logical issues with zero strokes and such, I think this line was added to the bottom of the instructions.

> `par` and `strokes` will always be numeric and positive.

Thus, there won't be any logical inconsistencies within the table.

Adding in this one more option of zero strokes doesn't add too much to this challenge. And this challenge is within the Basic JavaScript section so I think this challenge is sufficient given where it is. My two cents on the matter.

**Comment by akthehobbyist** [comment]
For some reason, I am not able to move to next challenge even though my code is right. I think there is a bug with the golf challenge. All my test cases turns out fine but still does not let me finish this challenge.

**Comment by erictleung** [comment]
@akthehobbyist if you get stuck or have questions with a challenge, please ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by akthehobbyist** [comment]
Sorry, I am new here. Thanks for your suggestion!

**Comment by jkb-1019** [comment]
I have a new issue. No one has mentioned, though they talked about this particular test, that if Par = 5 and Score = 2, it's not an eagle. It's an albatross or double eagle. I think this test should be removed.

**Comment by erictleung** [comment]
@jkb-1019 thanks for the comments. This has been brought up [before](https://github.com/freeCodeCamp/freeCodeCamp/issues/6326) and [again](https://github.com/freeCodeCamp/freeCodeCamp/issues/5690).

**Comment by erictleung** [comment]
Closing as stale and possibly fixed by https://github.com/freeCodeCamp/freeCodeCamp/pull/15678. I think both concerns that were brought up have been addressed as a not an issue or has been already covered in the instructions. Feel free to comment if the issue still exists. Happy coding!
