### ISSUE TITLE
'var' is a keyword for declaration, is it suitable here for variable name?

### ISSUE THREAD

**Issue by zhaobaiyu** [FreeCodeCamp/FreeCodeCamp#12026]
Challenge [Comparisons with the Logical Or Operator](https://www.freecodecamp.com/challenges/comparisons-with-the-logical-or-operator#?solution=%0Afunction%20testLogicalOr(val)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20if%20(val)%20%7B%0A%20%20%20%20return%20%22Outside%22%3B%0A%20%20%7D%0A%0A%20%20if%20(val)%20%7B%0A%20%20%20%20return%20%22Outside%22%3B%0A%20%20%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20%22Inside%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestLogicalOr(15)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testLogicalOr(val) {
  // Only change code below this line

  if (val) {
    return "Outside";
  }

  if (val) {
    return "Outside";
  }

  // Only change code above this line
  return "Inside";
}

// Change this value to test
testLogicalOr(15);

```

**'var' is a keyword for declaration, is it suitable here for variable name?**

**Comment by raisedadead** [comment]
@zhaobaiyu its `val` with a **l** and not **r** 😅 . Closing. Please comment if you wanted to state something else about the challenge.

Happy coding!

P.S: Confirm bugs with others in [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript), prior reporting.

**Comment by zhaobaiyu** [comment]
@raisedadead I feel sorry, my rookie mistake...

**Comment by raisedadead** [comment]
@zhaobaiyu sure thing not a problem at all. Happy coding!
