### ISSUE TITLE
background

### ISSUE THREAD

**Issue by bilancostel** [FreeCodeCamp/FreeCodeCamp#12039]
![grey-white-background](https://cloud.githubusercontent.com/assets/23318346/21182060/bc5cc2e8-c209-11e6-8f4b-81f353672c62.jpg)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by raisedadead** [comment]
@bilancostel do not spam the issue tracker.
