### ISSUE TITLE
I upload a photo

### ISSUE THREAD

**Issue by bilancostel** [FreeCodeCamp/FreeCodeCamp#12035]
![11902243_171758346489694_770692010094795411_n](https://cloud.githubusercontent.com/assets/23318346/21177548/53f1eb1c-c1f4-11e6-89e2-e5f368467d5d.jpg)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by diomed** [comment]
![-](http://1.static.upcoming.nl/static/images/3564fe6391_1401109240_Maar-ze-zijn-er-wel.gif)

**Comment by raisedadead** [comment]
@bilancostel do not spam the issue tracker.
