### ISSUE TITLE
sa

### ISSUE THREAD

**Issue by bilancostel** [FreeCodeCamp/FreeCodeCamp#12036]
![mor-renk](https://cloud.githubusercontent.com/assets/23318346/21178888/3811a5da-c1fa-11e6-96d4-f531a0ce6a34.jpg)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by raisedadead** [comment]
@bilancostel do not spam the issue tracker.
