### ISSUE TITLE
I need another photo

### ISSUE THREAD

**Issue by bilancostel** [FreeCodeCamp/FreeCodeCamp#12038]
![12313706_216441475354714_933995048861588530_n](https://cloud.githubusercontent.com/assets/23318346/21181541/213ec164-c207-11e6-94ce-ae6a8a1a626d.jpg)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by raisedadead** [comment]
@bilancostel do not spam the issue tracker.
