### ISSUE TITLE
comment bug

### ISSUE THREAD

**Issue by hackcode007** [FreeCodeCamp/FreeCodeCamp#12033]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3C!--%3Ch1%3EHello%20World%3C%2Fh1%3E--%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3C!--p%3EHello%20Paragraph%3C%2Fp%3E--%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!--<h1>Hello World</h1>-->

<h2>CatPhotoApp</h2>

<!--p>Hello Paragraph</p>-->


```

**Comment by Manish-Giri** [comment]
@hackcode007 Your code is incorrect, you're missing the `<` for the opening `p` tag.

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) for help with challenges like these, in future. Happy Coding!
