### ISSUE TITLE
dude where's my code ?

### ISSUE THREAD

**Issue by zenman14** [FreeCodeCamp/FreeCodeCamp#12049]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```
#### Screenshot

Create a p element.
Your p element should have the text "Hello Paragraph".
Make sure your p element has a closing tag.

```
1
<h1>"Hello World"</h1>
2
<h2>"CatPhotoApp"</h2>
3
<p>"Hello Paragragh"</p>
```
​
so whats wrong with that ?

**Comment by Manish-Giri** [comment]
@zenman14 Could you either post the challenge URL with your code, or paste your code here? Can't say for sure without it, but it looks like you don't have the `p` tags.

**Comment by zenman14** [comment]
Ok

**Comment by texas2010** [comment]
@zenman14 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by zenman14** [comment]
Inform with the Paragraph Element
------------------------------

p elements are the preferred element for normal-sized paragraph text on
websites. P is short for "paragraph".

You can create a p element like this:

<p>I'm a p tag!</p>

Create a p element below your h2 element, and give it the text "Hello
Paragraph".
Run tests (ctrl + enter)
Reset
Help
Bug
Create a p element.
Your p element should have the text "Hello Paragraph".
Make sure your p element has a closing tag.

1

<h1>"Hello World"</h1>

2

<h2>"CatPhotoApp"</h2>

3

<p>"Hello Paragragh"</p>

4

​
