### ISSUE TITLE
Convert Celsius to Fahrenheit

### ISSUE THREAD

**Issue by EULARIAN** [FreeCodeCamp/FreeCodeCamp#12040]
#### Challenge Name

https://www.freecodecamp.com/challenges/convert-celsius-to-fahrenheit#?solution=%0Afunction%20convertToF(celsius)%20%7B%0A%20%20var%20fahrenheit%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20fahrenheit%3D(celsius%20*(9%2F5))%2B32%3B%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20fahrenheit%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%20your%20code%0AconvertToF(0)%3B%0AconvertToF(-30)%3B%0AconvertToF(-10)%3B%0AconvetToF(0)%3B%0AconvertToF(20)%3B%0AconvertToF(30)%3B%0A

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js

 
 
 
```

**Comment by raisedadead** [comment]
Please provide details of the issue that you are facing.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by raisedadead** [comment]
@EULARIAN Your code is not correct, there is a typo.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
