### ISSUE TITLE
There's a bug here

### ISSUE THREAD

**Issue by fer408** [FreeCodeCamp/FreeCodeCamp#12053]
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  if(prop === "tracks" && value !== "") {
    if (collection[id][prop]){
      collection[id][prop].push(value);
    }
    else{
      collection[id][prop] = value;
    }
  }
    else if(value !== "") { 
      collection[id][prop] = value;
    }
    else {
      delete collection[id][prop];
    }
  
  return collection;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");


```

**Comment by Marmiz** [comment]
@fer408 If you read carefully the exercise requirement you'll see that:

>If prop is "tracks" but the album doesn't have a "tracks" property, **create an empty array before adding the new value** to the album's corresponding property.

While running your code, you'll see a checkmark failing, related to that you'll see on the console:
```
"5349": {
    "album": "ABBA Gold",
    "tracks": "Take a Chance on Me"
}
```

------------
Next time you have some i encourage you to turn to the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help?at=58510b28f666c5a1380f11db) first! 😄 


Also please note for future reference that for reporting a bug some description is always needed to fully understand your issue.

Cheers! 👍

**Comment by raisedadead** [comment]
thanks @Marmiz
