### ISSUE TITLE
twitch.tv issue , no output

### ISSUE THREAD

**Issue by charan1922** [FreeCodeCamp/FreeCodeCamp#12059]
even i have entered my client id, but it is showing no output

#### Challenge Name

http://codepen.io/charan1922/pen/NbEMWQ?editors=0010

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by raisedadead** [comment]
The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
