### ISSUE TITLE
Code returned correct answer but should not have

### ISSUE THREAD

**Issue by mountwe** [FreeCodeCamp/freecodecamp#1205]
Challenge http://www.freecodecamp.com/challenges/bonfire-where-do-i-belong has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Hello,

My code passed Bonfire 18: Where do I belong, but I believe it should not have.

This is the lesson requirement:
`Return the lowest index at which a value (second argument) should be inserted into a sorted array (first argument).`

Here is my solution:

``` javascript
    function where(arr, num) {
	    arr = arr.sort();
	    for (i = 0; i < arr.length; i++) {
	       if (num > arr[i]) {
		      continue;
	       }
              else {
               return i;
          }
    }
	// return i;
    }

    where([40, 60], 50);
```

When my code was marked completed successfully, I was happy. However, as I reflect on it, I believe it should not have passed. The way it is written, I believe it would always return 0. That is not the answer unless, indeed, number should be placed in the first location in the array.

**Comment by benmcmahon100** [comment]
No this code functions perfectly as it is! In future you should check this kind of stuff in the http://gitter.im/freecodecamp/help or even in the main chat. There will almost always be someone there who can help with these kinds of issues. Github is more reserved for bugs and feature requests rather than issues with people's code.

**Comment by mountwe** [comment]
benmcmahon100, thank you for the suggestion. I was reporting what I thought was a bug. That brought me here. And, crap, as I was answering your response, I figured out why it works. I suppose that comes from looking at your own code too long without a break.

**Comment by benmcmahon100** [comment]
Ha Ha no problem! Just trying to keep things in order! :relaxed: Also don't forget to close this issue if there's nothing else I can help you with!

**Comment by mountwe** [comment]
Doing so now. Thank you again!
