### ISSUE TITLE
DeprecationWarning - Backend Section

### ISSUE THREAD

**Issue by victorhugorch** [FreeCodeCamp/FreeCodeCamp#12052]
#### Start a Nodejs Server 

https://www.freecodecamp.com/challenges/start-a-nodejs-server

#### Issue Description

When I use any command from the `learnyounode` I have this alert.

`(node:11382) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.`

#### Browser Information

`npm -v 4.0.3`
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
 
#### Screenshot

http://i66.tinypic.com/2agrn9j.png

**Comment by raisedadead** [comment]
Hi @victorhugorch 

Please follow the discussion on https://github.com/workshopper/learnyounode/issues/492

Thanks.
