### ISSUE TITLE
Request for more challenges in CSS with Grids and Columns

### ISSUE THREAD

**Issue by jamescodernewbie** [FreeCodeCamp/FreeCodeCamp#12062]
Request for more challenges in CSS with Grids and Columns

**Description**: 
I wold like to have more challenges with just the basic design of a website from scratch. What currently is offered with focuses on more on buttons and such, I am interested in learning how to create divs, sections like header, body, footer and adjust their size with CSS grids and columns.

Currently, I am doing the "Build a Tribute Page" challenge and I feel that I do not have the basic understanding of concepts of aligning such elements in the page.
<sub> - description edited by mod. </sub>

> Original Description by OP: 
> i Would like to have more **challenges with just basic sketching of a site from scratch. This part fokuses to much on buttens and such. More with how to make the headder body and footer size and some divs inside and the sizes. im doing the tribuute challenge and down´+t feel like i have the basic understading of that.

**Comment by raisedadead** [comment]
Thanks for the report @jamescodernewbie 

@FreeCodeCamp/moderators Do we have this in mind with the new curriculum expansion? Sorry I haven't on top of the progress there?

**Comment by QuincyLarson** [comment]
@raisedadead @jamescodernewbie yes - we have a whole new section about responsive design that will cover this and media queries. We also have a Flexbox section. I recommend in the meantime you keep going and look things up as necessary. We'll push these new challenges as soon as we can 🙂
