### ISSUE TITLE
For everyone thinking it's a bug or being frustrated with not changing to BLUE!!

### ISSUE THREAD

**Issue by TH3ORY** [FreeCodeCamp/FreeCodeCamp#12069]
Hint Hint it's not a bug as i thought it was a error no it's not.. Read it carefully you need to style <h2> </h2> To blue i think ive said enough to get you moving to next chapter!

**Comment by raisedadead** [comment]
The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
