### ISSUE TITLE
ES6 Support for JavaScript Challenges

### ISSUE THREAD

**Issue by robbiemu** [freeCodeCamp/freeCodeCamp#12063]
Challenge [Make a Person](https://www.freecodecamp.com/challenges/make-a-person#?solution=/*jshint%20esversion%3A%206%20*/%0A%0Aclass%20Person%20%7B%0A%20%20constructor%28full%29%7B%0A%20%20%20%20this.tercero%20%3D%200%3B%0A%20%20%20%20this.quarto%20%3D%200%3B%0A%20%20%20%20this.quinto%20%3D%200%3B%0A%20%20%20%20this.sexto%20%3D%200%3B%0A%20%20%20%20%5Bthis.first%2C%20this.last%5D%20%3D%20full.split%28%27%20%27%29%0A%20%20%7D%0A%20%20getFirstName%28%29%20%7B%20return%20this.first%20%7D%0A%20%20getLastName%28%29%20%7B%20return%20this.last%20%7D%0A%20%20getFullName%28%29%20%7B%20return%20%60%24%7Bthis.first%7D%20%24%7Bthis.last%7D%60%20%7D%0A%20%20setFirstName%28first%29%20%7B%20this.first%20%3D%20first%20%7D%0A%20%20setLastName%28last%29%20%7B%20this.last%20%3D%20last%20%7D%0A%20%20setFullName%28full%29%20%7B%20%5Bthis.first%2C%20this.last%5D%20%3D%20full.split%28%27%20%27%29%20%7D%0A%7D%0A%0A%0Avar%20bob%20%3D%20new%20Person%28%27Bob%20Ross%27%29%3B%0AObject.keys%28bob%29.length%0Abob.getFullName%28%29%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

So, the problem is, the Class keyword is supported by the linter but not by the problem checker.

My code:
```javascript
/*jshint esversion: 6 */

class Person {
  constructor(full){
// attemped fudge for old-school classes:
    this.tercero = 0;
    this.quarto = 0;
    this.quinto = 0;
    this.sexto = 0;
//
    [this.first, this.last] = full.split(' ')
  }
  getFirstName() { return this.first }
  getLastName() { return this.last }
  getFullName() { return `${this.first} ${this.last}` }
  setFirstName(first) { this.first = first }
  setLastName(last) { this.last = last }
  setFullName(full) { [this.first, this.last] = full.split(' ') }
}


var bob = new Person('Bob Ross');
Object.keys(bob).length
bob.getFullName();
```

**Comment by raisedadead** [comment]
Hi @robbiemu 

Thanks for the report, yes we do not have a native support for the ES6. We actually execute all of the code from the code editor directly in the browser. So if the browser has the support for ES6 syntax, it should mostly work.

But, yes we do not explicitly check anything else for ES6.

Tagging as a feature request but, I am not sure when we can get into this.

Happy coding!

**Comment by systimotic** [comment]
Hi! I found #8096, which is an older and more detailed issue on the same topic, so I'm closing this as a duplicate.

Happy coding!
