### ISSUE TITLE
Update instructions for Stand in Line Challenge

### ISSUE THREAD

**Issue by ajitkumarsahu** [FreeCodeCamp/FreeCodeCamp#12067]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20%0A%20%20return%20item%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%206))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 UBrowser/5.6.12860.7 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function nextInLine(arr, item) {
  // Your code here
  
  return item;  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by raisedadead** [comment]
@ajitkumarsahu The instructions are pretty simple. 

If you read through it step by step:
> Write a function `nextInLine` which takes an array (`arr`) and a number (`item`) as arguments. 
>
> Add the number to the end of the array, then remove the first element of **the** array. 
>
> The `nextInLine` function should then return the element that was removed. 


Can anyone update this challenge to break the paragraph into individual sentences? Also, fix the grammar in the second sentence adding a "the" before "array", I have highlighted it in bold above.

Thanks.

**Comment by raisedadead** [comment]
For first timers:

This is the line of code that you have to break into individual sentences:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L2747

```js
"Write a function <code>nextInLine</code> which takes an array (<code>arr</code>) and a number (<code>item</code>) as arguments.", 
"Add the number to the end of the array, then remove the first element of the array.", 
"The <code>nextInLine</code> function should then return the element that was removed."
```

**Comment by DarrenfJ** [comment]
Easy enough I think I can take a crack at it

**Comment by spieg** [comment]
Is this the reason that there are no longer links to push pop shift unshift in the hints for the "stand in line" challenge?

**Comment by raisedadead** [comment]
> Is this the reason that there are no longer links to push pop shift unshift in the hints for the "stand in line" challenge?

This supposed to be moved to a new way as discussed in  https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8290

/cc @BerkeleyTrue I can't see it on latest staging. Do you have an idea?

**Comment by BerkeleyTrue** [comment]
Are you talking about hints?

**Comment by raisedadead** [comment]
Yes. I am not sure why the MDN links aren't available any longer in staging.

**Comment by BerkeleyTrue** [comment]
MDN links are no longer available in favor of hints. They need to be converted over to hints.
