### ISSUE TITLE
Override All Other Styles by using Important:bug 

### ISSUE THREAD

**Issue by IonZero1** [FreeCodeCamp/FreeCodeCamp#12074]
Challenge [Override All Other Styles by using Important](https://www.freecodecamp.com/challenges/override-all-other-styles-by-using-important#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20%23orange-text%20%7B%0A%20%20%20%20color%3A%20orange%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%20!important%20%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20id%3D%22orange-text%22%20class%3D%22pink-text%20blue-text%22%20style%3D%22color%3A%20white%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text {
    color: orange;
  }
  .pink-text {
    color: pink !important ;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 id="orange-text" class="pink-text blue-text" style="color: white">Hello World!</h1>

```

i dont pass the:Your pink-text class declaration should have the !important keyword to override all other declarations.

**Comment by raisedadead** [comment]
@IonZero1 Thanks for the report

The above 
```css
color: pink !important ;
```
has a space between `!important` and `;`.

Removing it like below fixes the challenge, and lets it pass:
```css
color: pink !important;
```

This is a valid bug, maybe the tests are killing it. Needs fixing and allowing space in between.

**Comment by Manish-Giri** [comment]
I'll work on it..

**Comment by dhcodes** [comment]
@Manish-Giri you have all the fun :)

**Comment by Manish-Giri** [comment]
@dhcodes all the fun goes away the minute I hit "gulp" 😟

**Comment by Manish-Giri** [comment]
@raisedadead I tested the code locally, it looks like the bug doesn't exist in `staging`. If you look at [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/1a7db665b9f76e70065c1507d584681ecad20b81/seed/challenges/01-front-end-development-certification/html5-and-css.json#L4672), the regex does account for possible spaces between `!important` and `;`
```
code.match(/\\.pink-text\\s*?\\{[\\s\\S]*?color:.*pink.*!important\\s*;?[^\\.]*\\}/g)
```

Here is the result on my local instance - 

![screenshot 2016-12-19 18 44 46](https://cloud.githubusercontent.com/assets/11348778/21334213/a17dbe14-c623-11e6-8604-fff34566612f.png)

![screenshot 2016-12-19 18 46 19](https://cloud.githubusercontent.com/assets/11348778/21334220/a79ecd4c-c623-11e6-91f8-e7ec0075a45c.png)

**Comment by raisedadead** [comment]
@Manish-Giri thanks it looks like the code on [`backup/master`](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/backup/master/seed/challenges/01-front-end-development-certification/html5-and-css.json#L4345) is old.

@IonZero1 this issue is fixed and will be available when we release our website soon. Sorry for the inconvenience. Until then please proceed by removing the space as suggested in the comments above.

Thanks and happy coding!

**Comment by lourcastillo** [comment]
`<h1 id="orange-text" class="pink-text blue-text" style="color: white">Hello World!</h1>`
