### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by AgentAkeo** [FreeCodeCamp/FreeCodeCamp#12079]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  h2 {
    color: blue;
  }
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by raisedadead** [comment]
Why is 😆😆😆 an issue?  

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
