### ISSUE TITLE
[staging] /settings - Cannot read property 'block' of undefined

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/FreeCodeCamp#12072]
There is a TypeError on the /settings route from the non-react user's portfolio page.

Error Stack: https://gist.github.com/raisedadead/273440b8ff316af86ab46e7d5714a70a

![2016-12-16 20 53 36](https://cloud.githubusercontent.com/assets/1884376/21268140/8406f8fc-c3d3-11e6-8c87-a6ba9e612df1.gif)

**Comment by Manish-Giri** [comment]
I got this error too, yesterday, when setting up a fresh instance of FCC on a Ubuntu 16.04 64-bit machine, while clicking on "Map".

**Comment by BerkeleyTrue** [comment]
cc @Bouncey 

Looks like this is related to your recent PR.
