### ISSUE TITLE
Increment Number with Java Script

### ISSUE THREAD

**Issue by Shubhamkumarsingh** [FreeCodeCamp/FreeCodeCamp#12078]
#### Issue Description

This was my problem. how would i change myVar =myVar it will be kidding me and dosen't allow me to pass the challenge.
So, on  a humble request please help me out.

#### Browser Information

Java Script Increment Number with Java Script chalenge .
* Browser Name Firefox, Version 52.2: 
* Operating System Windows 7: 
* Mobile 8871135429, Desktop 

#### Your Code

```js
 
var myVar = 87;


// Only change code below this line
myVar = ++myVar;


 
 
```
#### Screenshot

![untitled](https://cloud.githubusercontent.com/assets/24203776/21274268/5265c278-c3ed-11e6-94fc-f4939f744ad8.png)

**Comment by Shubhamkumarsingh** [comment]
No it is a bug. And i am unable to resolve it.

**Comment by KickButtowski80** [comment]
I agree with Shubhamkumarsingh .
how can we resolve this issue?

**Comment by texas2010** [comment]
@KickButtowski80, It is not the bug.  their code is incorrect. that is why it won't passed first place.

**Comment by KickButtowski80** [comment]
how can we pass it through?

**Comment by aquasaurious** [comment]
I thought it was a bug at first, but then I re-read the text to the left.  OP's code would work IRL, but there is another way to answer the question, and you'll see it when you read the explanation.
