### ISSUE TITLE
[feature request] linking login session through email and github 

### ISSUE THREAD

**Issue by dristybutola** [FreeCodeCamp/FreeCodeCamp#12076]
#### Issue Description

When a user uses email and GitHub alternately the activity and successful challenges are not linked for both although the user is same.

**Comment by raisedadead** [comment]
Do you have different email id on your GitHub account than the one you used when you signed up to Free Code Camp?

If yes, is the feature you are requesting should merge both profiles?

**Comment by dristybutola** [comment]
The email id are same for both GitHub and Free Code Camp accounts .

**Comment by raisedadead** [comment]
Correct, we are following this in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10802
Closing as a duplicate. We should have a fix by the time we release the new platform.

Meanwhile, I request you to either delete one account, whichever has less progress and submit the challenges on the other.

Or you could report to Team@FreeCodeCamp.com, requesting a merge (there might be a delay).
