### ISSUE TITLE
Misleading / Wrong instructions

### ISSUE THREAD

**Issue by laura-barluzzi** [FreeCodeCamp/FreeCodeCamp#12080]
Challenge [Join Strings with join](https://www.freecodecamp.com/challenges/join-strings-with-join#?solution=%0Avar%20joinMe%20%3D%20%5B%22Split%22%2C%22me%22%2C%22into%22%2C%22an%22%2C%22array%22%5D%3B%0Avar%20joinedString%20%3D%20'%20'%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AjoinedString%20%3D%20joinMe.join(joinedString)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var joinMe = ["Split","me","into","an","array"];
var joinedString = ' ';

// Only change code below this line.

joinedString = joinMe.join(joinedString);

```
***** the exercise required not to change the code above the comment, but the var joinedString = "" needs to be changed to joinedString = " " for making it possible.

**Comment by raisedadead** [comment]
I think you are confused a bit with the instructions and the code that you see in the editor.
Hints: This can be solved without the `.join(joinedString)`

Please reach out to [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript), for further help.

Happy coding!
