### ISSUE TITLE
bug Search and Replace

### ISSUE THREAD

**Issue by kostaschaidoulis** [FreeCodeCamp/FreeCodeCamp#12082]
Challenge [Search and Replace](https://www.freecodecamp.com/challenges/search-and-replace#?solution=%0Afunction%20myReplace(str%2C%20before%2C%20after)%20%7B%0A%20%20var%20newStr%20%3D%20%5B%5D%3B%0A%20%20newStr%20%3D%20str.split(%22%20%22)%3B%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20newStr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20if(newStr%5Bi%5D%20%3D%3D%3D%20before)%20%7B%0A%20%20%20%20%20%20%20%20%20%20newStr.splice(i%2C%201%2C%20after)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%7D%0A%20%20newStr%20%3D%20newStr.join(%22%20%22)%3B%0A%20%20return%20newStr%3B%0A%7D%0A%0AmyReplace(%22A%20quick%20brown%20fox%20jumped%20over%20the%20lazy%20dog%22%2C%20%22jumped%22%2C%20%22leaped%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function myReplace(str, before, after) {
  var newStr = [];
  newStr = str.split(" ");
  for(var i = 0; i < newStr.length; i++) {
      if(newStr[i] === before) {
          newStr.splice(i, 1, after);
      }
  }
  newStr = newStr.join(" ");
  return newStr;
}

myReplace("A quick brown fox jumped over the lazy dog", "jumped", "leaped");

```
Working fine

**Comment by raisedadead** [comment]
Hi @kostaschaidoulis 

Thanks for the report. Your code does not:
> Preserve the case of the original word when you are replacing it.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
