### ISSUE TITLE
how can i soilve it

### ISSUE THREAD

**Issue by silenteye** [FreeCodeCamp/FreeCodeCamp#12088]

**Comment by spieg** [comment]
The chatrooms are for solving problems with your code. Bug reporting is for problems with the freecodecamp workings.
It so happens that your code is wrong. You need to remove all the parts of what once were comment tags ie 
Please close this issue, and if this is not enough help, check one of the chatrooms.

**Comment by raisedadead** [comment]
Hi @silenteye, 

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

@spieg thanks for commenting!

Happy Coding.
