### ISSUE TITLE
Bug detected for Repeat a string (Free Code Camp)

### ISSUE THREAD

**Issue by emilyheng** [FreeCodeCamp/FreeCodeCamp#12084]
<img width="1248" alt="screen shot 2016-12-17 at 11 07 11 am" src="https://cloud.githubusercontent.com/assets/23717772/21283994/1c091714-c449-11e6-89cd-a3888cb5e721.png">
Challenge [Repeat a string repeat a string](https://www.freecodecamp.com/challenges/repeat-a-string-repeat-a-string#?solution=%0Afunction%20repeatStringNumTimes(str%2C%20num)%20%7B%0A%20%20%0Aif%20(num%3C0)%7B%0A%20%20return%20%22%22%3B%0A%7D%20return%20str.repeat(num)%3B%0A%0A%7D%0A%0ArepeatStringNumTimes(%22abc%22%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

See attached picture- it says my repeat function is undefined when it should work. I tried refreshing my page, still got the same problem. I asked someone on Gitter and they said my code works on their page.

My code:
```javascript

function repeatStringNumTimes(str, num) {
  
if (num<0){
  return "";
} return str.repeat(num);

}

repeatStringNumTimes("abc", 3);

```

**Comment by erictleung** [comment]
@emilyheng thanks for the issue. Yes, your code passes for me too. Can you confirm what browser and version you're on? The automated user agent generated from your issue says you're using Safari version 8.0.8. According to MDN, the `.repeat()` method is only available on Safari version 9. So your issue might be that you need to use a compatible browser.

![image](https://cloud.githubusercontent.com/assets/2754821/21284418/51822afe-c3cf-11e6-929d-cd7909e72716.png)

Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

**Comment by emilyheng** [comment]
@erictleung Yes you're right! Thanks man(:

**Comment by raisedadead** [comment]
Thanks @emilyheng @erictleung .

Closing as resolved.
