### ISSUE TITLE
Sorted Union is not allowing access to all of the initial parameters

### ISSUE THREAD

**Issue by William-Charles** [FreeCodeCamp/FreeCodeCamp#12081]
Challenge [Sorted Union](https://www.freecodecamp.com/challenges/sorted-union#?solution=function%20uniteUnique(arr)%20%7B%0A%20%20%0A%20%20var%20flatArr%20%3D%20arr.reduce(function(a%2C%20b)%20%7B%20%0A%20%20%20%20return%20a.concat(b)%3B%0A%20%20%7D%2C%20%5B%5D)%3B%0A%0A%20%20%0A%20%20%0A%20%20return%20flatArr%3B%0A%7D%0A%0AuniteUnique(%5B1%2C%203%2C%202%5D%2C%20%5B5%2C%202%2C%201%2C%204%5D%2C%20%5B2%2C%201%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function uniteUnique(arr) {
  
  var flatArr = arr.reduce(function(a, b) { 
    return a.concat(b);
  }, []);

  
  
  return flatArr;
}

uniteUnique([1, 3, 2], [5, 2, 1, 4], [2, 1]);
```

**Comment by raisedadead** [comment]
Hi @William-Charles 

Thanks for the report. Please look at the helpful links given in the challenge:
> Arguments object

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
