### ISSUE TITLE
Run Tests button not working in challenge Responsive Design with Bootstrap ->Lable Bootstrap Buttons ?

### ISSUE THREAD

**Issue by Fadeoc** [FreeCodeCamp/FreeCodeCamp#12087]
#### Challenge Name
Responsive Design with Bootstrap ->Lable Bootstrap Buttons ?

#### Issue Description

Run tests button not working after click, no pop test result came out.

#### Browser Information

* Browser Name, Version: Firefox Developer 52.0a2, Chrome 55.0.2883.87 m
* Operating System: Windows 10 1607
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```
 
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">target1</button>
        <button class="btn btn-default target" id="target2">target2</button>
        <button class="btn btn-default target" id="target3">target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">target4</button>
        <button class="btn btn-default target" id="target5">target5</button>
        <button class="btn btn-default target" id="target6">target6</button>
      </div>
    </div>
  </div>
</div>

 
 
```
#### Screenshot

![2](https://cloud.githubusercontent.com/assets/8510013/21285713/7440ef60-c47b-11e6-85a4-615e83bb92bf.PNG)

**Comment by spieg** [comment]
The challenge states
"Give your button element with the id target1 the text #target1."
Your code says
```
<button class="btn btn-default target" id="target1">target1</button>
```
I do hope you can see why your code is wrong. target1 != #target1.
Bugs are there for errors in CodeCamp, not in your code. Please check with people in the chatrooms before opening a bug.

**Comment by Fadeoc** [comment]
sorry for this, I have checked with ppl in chatrooms and one of the ppl asked me to paste my code, I did, but he did not answer me more.

Thank you.

**Comment by raisedadead** [comment]
@Fadeoc Yup, sometimes chat rooms get busy, but the community is great and will help you with the learning, please check out the forum as well.

@spieg thanks, and please provide all assistance to coding in the chat rooms and forum. 

Happy coding!
