### ISSUE TITLE
Reverse a String

### ISSUE THREAD

**Issue by mohsinz** [FreeCodeCamp/FreeCodeCamp#12095]
Challenge [Reverse a String](https://www.freecodecamp.com/challenges/reverse-a-string#?solution=%0Afunction%20reverseString(str)%20%7B%0A%20%20return%20str%3B%0A%7D%0A%0Ax%20%3D%20reverseString(%22Howdy%22)%3B%0Aarray%20%3D%20reverseString(x).split(%27%27).reverse().join(%27%27)%3B%0Afinal%20%3D%20%22%5C%22%22%20%2B%20array%20%2B%20%22%5C%22%22%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function reverseString(str) {
  return str;
}

x = reverseString("Howdy");
array = reverseString(x).split('').reverse().join('');
final = "\"" + array + "\"";
```

Not sure where I went wrong but the outcome is correct.

**Comment by Manish-Giri** [comment]
@mohsinz You are supposed to write your code inside the body of the `reverseString` function.

**Comment by mohsinz** [comment]
got it! I always complicate things lol
