### ISSUE TITLE
Give a Background Color to a Div Element

### ISSUE THREAD

**Issue by queenly111** [FreeCodeCamp/FreeCodeCamp#12090]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by queenly111** [comment]
I did eveything they said not go thought

**Comment by raisedadead** [comment]
Hi @queenly111 

Thanks for the report.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
