### ISSUE TITLE
please send me the code of the task of stand in line

### ISSUE THREAD

**Issue by ajitkumarsahu** [FreeCodeCamp/FreeCodeCamp#12096]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20testArr.push(item)%3B%0A%20%20var%20removed%3DtestArr.shift()%3B%0A%20%20return%20removed%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B5%2C6%2C7%2C8%2C9%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%205))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 UBrowser/5.7.16817.1002 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function nextInLine(arr, item) {
  // Your code here
 testArr.push(item);
  var removed=testArr.shift();
  return removed;  // Change this line
}

// Test Setup
var testArr = [5,6,7,8,9];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 5)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by Manish-Giri** [comment]
@ajitkumarsahu Your code is incorrect, you should be using the array passed in to your function as an argument - `arr` instead of `testArr`.

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) or the [HelpJS Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need help with the challenge. Happy Coding!

**Comment by raisedadead** [comment]
@ajitkumarsahu Sincere requests to not report issues seeking code assistance on the issue tracker. Please proceed to the chat rooms as suggested by @Manish-Giri !

Thanks and happy coding!
