### ISSUE TITLE
Map the Debris - altitude and orbital velocity values not matching for Moon 

### ISSUE THREAD

**Issue by srini5** [FreeCodeCamp/FreeCodeCamp#12102]
#### Challenge Name
https://www.freecodecamp.com/challenges/map-the-debris

#### Issue Description
Hi,

This is regarding the "map the debris" challenge. 
In this, I have used the formula as per wikipedia, to calculate the orbital period given the semi major axis (radius of the earth + altitude of the object) and the GM value (as O = 2*PI*SQRT(R^3/GM)). 

This computes correctly for the test values given for sputnik, iss and hubble. However, it if off by 6 metres from the value given as the answer for moon. 
I tried to tweak the input value, and found that about 0.5 metres less  specified as the height of the moon will match the expected answer.

It looks like either the given input data, or the expected results for moon are not in sync. 
Can you please check, and advise ?

#### Browser Information
* Browser Name, Version: Chrome, latest
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

function orbitalPeriod(arr) {
  var GM = 398600.4418;
  var earthRadius = 6367.4447;
  
  arr = arr.map(function(val){
    var alt = val.avgAlt;
    delete val.avgAlt;
    var orb = Math.round( 2 * 3.1416 * Math.sqrt (Math.pow( (earthRadius + alt ), 3)/GM));  
    // As per wikipedia, the formula is ORB = 2*PI*SQRT(R^3/GM);
    val.orbitalPeriod = orb;
    return val;
  });
  return arr;
}

//orbitalPeriod([{name : "sputnik", avgAlt : 35873.5553}]);
orbitalPeriod([{name: "iss", avgAlt: 413.6}, {name: "hubble", avgAlt: 556.7}, {name: "moon", avgAlt: 378632.553}]);

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/22535130/21296461/37a606a4-c592-11e6-8853-21a90b65f484.png)

**Comment by dhcodes** [comment]
@srini5 This is caused by your approximation of pi. Instead, used `Math.PI` that is provided as part of the Javascript math functions. In the future, consider asking for help in the HelpJavascript chat room by clicking the help button on the challenge. Happy coding!

**Comment by srini5** [comment]
Thanks @dhcodes. 

As directed, will ask for help in the future. Sorry for raising this directly here, this time.
Thank you for helping.
