### ISSUE TITLE
Says test passed but when submitting a blank message the " Required Field Notification" does not activate. 

### ISSUE THREAD

**Issue by JJthe1st** [FreeCodeCamp/FreeCodeCamp#12105]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by erictleung** [comment]
@JJthe1st thanks for the issue. Can you first give us more information about your issue so that we can help? Which challenge do you have this issue one and can you share your code with which you used to submit in the challenge? Thanks!

**Comment by JJthe1st** [comment]
Hi Eric,
   I appreciate your rapid response. However, I have been doing/done all of
the FreeCodeCamp challenges via PS4 as my computer is currently either beng
fixed or being determined if it should just be replaced. That being said, I
do  not have some of the normal typing luxeries. One of them being the
ability to copy and paste.  When i make a mistake in a challenge it seems
to take an eternity deleting and retyping, However, I am determined to get
as far as I can with what I have to work with. Thanks again, I wish that I
could have been of better help.

Best Wishes,
       J.J.

**Comment by raisedadead** [comment]
@JJthe1st thanks for letting us know, and sorry to hear that you have been trying to work on Free Code Camp from a non-standard device. While we understand the frustration, we sincerely regret that it would be difficult to debug and understand the issue in this case. 

Also, we may not be able to support if the website is broken on the PS4. 

We suggest when you get a chance, please re-check on a device that you can copy paste your code from, the challenge you are on, etc.. Until then I am closing this. Will reopen as soon as you can comment and report back.

And I personally am in awe that you are determined to learn on a PS4! Keep rocking!
