### ISSUE TITLE
Normalizr 2.3.0 has breaking changes

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#12103]
Seems like a recent package update has broken challenges services.

**Comment by Manish-Giri** [comment]
Just reposting from the earlier issue - I've been coming across this when clicking on "map" - 

![untitled](https://cloud.githubusercontent.com/assets/11348778/21302014/d45b33fa-c580-11e6-9647-2e91f7fb1cef.png)

This is the error in the browser if you navigate to the path that throws the 500 error in the console- 
`{"output":{"message":"Cannot read property 'order' of undefined"},"meta":{}}`

**Comment by ShrawanLakhe** [comment]
I too have same error.  I did fixed this issue but there are many other issues with the repo. It has to do with Object.keys in utils/map.js. 

So, if you want to fix this issue,  replace the code having map.result with following code.

`const result = map.result.reduce((result, supName) => {

        const index = map.entities['superBlock'][supName].order;
        result[index] = supName;
        return result;
      }, []);
      return {
        ...map,
        result
      };`

**Comment by BerkeleyTrue** [comment]
Looks like it is a breaking change in how results are returned by normalizr. See: https://github.com/paularmstrong/normalizr/issues/186

We will be pegging to 2.2.1 until we receive a response. This will allow development to proceed as normal.

**Comment by fizzvr** [comment]
Working with the latest changes.
