### ISSUE TITLE
Tests now include tails

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/freeCodeCamp#12104]
I'm working on a PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11987 but the third test I'm adding (using `code.match()` to test for the number of times `quotient` is used in the editor will not work because the tests now incorporate the tail as referenced in #10258 . 

If I write the test to include the tails (`length === 3` instead of `length === 1`) then `npm run test-challenges` won't work because the solution only uses `quotient` once. So it would appear the only option is to remove the solution provided in the JSON and account for the tail. 

@BerkeleyTrue is that the right approach given tails are now included in the tests?

**Comment by systimotic** [comment]
@dhcodes Do you have an update on this? I saw you said in the PR that it was fine to remove the solution.

**Comment by dhcodes** [comment]
@systimotic I'm not sure. @BerkeleyTrue said it was fine to remove the solution for that one but I'm still a bit unclear on the path forward as any `.length` test on a challenge with a solution will fail the `npm run test-challenges` and Travis-CI. For the time-being, depending on the case, `.length` tests may now need to account for matches in the tail.

**Comment by systimotic** [comment]
Maybe it would be a good idea to look at why tails are now included in the tests. If it doesn't have any advantages, it would probably be best to exclude them from the tests. That would make the most sense to me, but I don't know why the tails were included in the tests in the first place, so it may not be possible.

**Comment by BerkeleyTrue** [comment]
@dhcodes the plan is to scrap the current testing framework for one that uses the same challenge framework and runs them in the browser.

It's not just matches in the tail that need to be accounted for but also additions made by babel (such as adding `"use strict";`)

We should avoid trying to test for these things as much as possible if at all possible.
