### ISSUE TITLE
Manipulating Complex Objects

### ISSUE THREAD

**Issue by DarthDavorin** [FreeCodeCamp/FreeCodeCamp#12113]
Challenge [Manipulating Complex Objects](https://www.freecodecamp.com/challenges/manipulating-complex-objects#?solution=%0Avar%20myMusic%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Billy%20Joel%22%2C%0A%20%20%20%20%22title%22%3A%20%22Piano%20Man%22%2C%0A%20%20%20%20%22release_year%22%3A%201973%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CS%22%2C%20%0A%20%20%20%20%20%20%228T%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%0A%20%20%20%20%22gold%22%3A%20true%0A%20%20%7D%0A%20%20%2F%2F%20Add%20record%20here%0A%20%20%7B%20%0A%22artist%22%3A%20%22Pharrell%22%2C%0A%22title%22%3A%20%22Happy%22%2C%0A%22release_year%22%3A%202015%2C%0A%22formats%22%3A%20%5B%0A%22mp3%22%2C%0A%22cd%22%0A%22tape%22%0A%5D%0A%7D%0A%5D%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  }
  // Add record here
  { 
"artist": "Pharrell",
"title": "Happy",
"release_year": 2015,
"formats": [
"mp3",
"cd"
"tape"
]
}
];



```

**Comment by forkerino** [comment]
You are missing a comma between the two records.

**Comment by raisedadead** [comment]
Thanks a lot for commenting @forkerino.

Hi @DarthDavorin. 

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
