### ISSUE TITLE
RecordCollection

### ISSUE THREAD

**Issue by theman0123** [FreeCodeCamp/FreeCodeCamp#12119]
Record Collection: 
//my code here//
function updateRecords(id, prop, value) {
if(prop === "tracks" && value !== "") {
collection[id][prop] = value;
}else if(value !== "") {
collection[id][prop]=value;
}//delete
else {
delete collection[id][prop];
}
  return collection;
}

#### Issue Description

should pass all tests... but doesn't.
the console is displaying all the information requested to pass the given tests. 

#### Browser Information

this is a Chrome browser on a linux system
* Browser Name, Version: 
* Operating System:
* Mobile, Desktop, or Tablet: 
5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36

 

![record-collection](https://cloud.githubusercontent.com/assets/22644182/21328534/aa7a2214-c5f1-11e6-99e7-707a1daf452e.png)

**Comment by ooade** [comment]
record 5439 tracks should be an array.. Pls use the [help room](https://gitter.im/FreeCodeCamp/HelpJavaScript) next time you have this kinda issue.

**Comment by raisedadead** [comment]
Hi @theman0123 

Thanks for the report.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
