### ISSUE TITLE
Issue with Callback while registering with email - Callback already called and server disconnects 

### ISSUE THREAD

**Issue by ShrawanLakhe** [FreeCodeCamp/FreeCodeCamp#12118]
#### Issue Description
I am trying to signup with email but when i click the Signup button, process exits complaining about Callback. Error is Callback was already called and process from the terminal exits. However, user is saving in the database.

#### Browser Information

* Browser Name, Version: Chrome v55
* Operating System: Ubuntu
* Mobile, Desktop, or Tablet:  Desktop
 
#### Screenshot
![freecodecamp-user-signup](https://cloud.githubusercontent.com/assets/5616157/21328079/5415b910-c65a-11e6-8ea0-5db8733bc8b1.png)
![user-signup-critical-error](https://cloud.githubusercontent.com/assets/5616157/21328105/73c3bf32-c65a-11e6-93ed-0c8f9aa249e8.png)

**Comment by dhcodes** [comment]
@ShrawanLakhe this does happen, but I believe if you reload and choose Sign In you will be able to sign in with the credentials you used when signing up.

**Comment by ShrawanLakhe** [comment]
@dhcodes Yeah that's right. If i reload and click on signIn button it does work. Shouldn't it after successfull registration redirects to welcome page as in the freecodecamp.com website. I am trying to deploy the application to the production server and  I did try to fix the issue but couldn't figure out where the callback is returned twice. Somewhere along the way, callback is returned twice i think. Can you give me some hints that i can use to fix the issue. Thank You very for prompt response sir

**Comment by dhcodes** [comment]
@ShrawanLakhe I think you need to add some values to the .env file. See this: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#setup-freecodecamp

**Comment by ShrawanLakhe** [comment]
@dhcodes Thank you. I will see if i can fix the issue by following the guidelines.

**Comment by raisedadead** [comment]
@ShrawanLakhe you need to AWS keys to get email registration working. It's a long  process to get Signed up, mostly such a setup is required for production applications.

Alternatively, for some temporary testing you can modify the [`server/datasources.json`](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/datasources.json) to use loopback's email config.

Check this link:
http://loopback.io/doc/en/lb2/Email-connector.html#using-gmail

It's bit tricky:
1. You should NOT use your own email account (create a throwaway email account). The config requires email id and password to be exposed in plain text.
2. You will have to enable a security setting in gmail, for allowing insecure apps (google this one).
3. Do not commit these temporary changes in git.

Hope this helps, reach out on [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), for more details, you can `@mention` me.

Happy fixing!

**Comment by raisedadead** [comment]
Or else if you are just interested in creating users, you can just simply type `rs` in the console where `gulp` is running. This will restart the server after it crashes when you see the error in the screenshot in the opening description you posted.

Simply visit `http://localhost:3000`, and login with the user, you should be good to go.

**Comment by ShrawanLakhe** [comment]
@raisedadead Thank You very very much. It solved the issue. I didn't see that mentioned anywhere. I think when there is some error while registration process, the application code somewhere is returning multiple callacks. Once again Thank you.

**Comment by raisedadead** [comment]
> I didn't see that mentioned anywhere.

I agree, we have left it deliberately because most contributors to this repo do not need this setup. Login and auth are rarely touched when fixing issues.

/cc @dhcodes this brings in the need for the test users we were talking about the other day

**Comment by ShrawanLakhe** [comment]
@dhcodes @raisedadead I think the application crashing while registering new users with email address has nothing  to do with wrong email setup configuration or no configuration at all. I tried everything but couldn't solve the crashing of application while new registrations with email. Then at last, I changed the version of **loopback to 2.23.0 from 2.22.0** and that solved the issue. Can you please verify that?

**Comment by raisedadead** [comment]
Just to confirm, before downgrading loopback, you configured the email provider in the datasources.json 

Can you dump a crash log? Is it exactly same as the opening post?

**Comment by ShrawanLakhe** [comment]
I upgraded loopback package from 2.22.0 to 2.23.0. Now even when there is no email configurations at all, application did not crashed. It just outputs the json message to the browser window.When there is valid email configuration, then it is working fine.

![Uploading email-output-missing-config.png…]()

**Comment by raisedadead** [comment]
> Now even when there is no email configurations at all, application did not crashed. It just outputs the json message to the browser window.

This is expected, and if you look at the console running `gulp`, it should have been showing the server has stopped

> When there is valid email configuration, then it is working fine.

 Isn't this a good case.

I am not sure if I understand your last comments, correctly as an argument of this should be working or otherway. Please clarify further the exact issue you are facing, with the `console logs` of the `gulp`

The ones above do not help in debug.

**Comment by ShrawanLakhe** [comment]
@raisedadead I have cloned the repository from staging branch couple of days back and with that repo code, whether i have email configurations or not, when registering new users with email, application crashed with the error stating that callback was already called. Even though application crashed, the user with that email is saved  in the database. I cannot do anything unless i restart the server. So I need to again start the server to use that application.

**Comment by ShrawanLakhe** [comment]
@raisedadead @dhcodes Thanks for your quick response.

**Comment by raisedadead** [comment]
Okay, let's take this step by step:

1. Server crashes without email config.
This is expected and is at the same time invalid case because the email config is not present.

2. Server crashes with email config.
This is unexpected, and we need the console log when the `gulp` command is running like below:

![image](https://cloud.githubusercontent.com/assets/1884376/21413105/13e6ffc6-c81b-11e6-8a65-da8d2f42e872.png)


Please share a similar log, so that we can debug. 
Also share the email configuration that you have done (removing or replacing sensitive data with arbitary values, just a sample format will do)
