### ISSUE TITLE
Target the Parent of an Element Using jQuery Bug

### ISSUE THREAD

**Issue by AaronMathew** [FreeCodeCamp/FreeCodeCamp#12111]
In the page, it only says Undefined
What should i do
![jj](https://cloud.githubusercontent.com/assets/24622715/21304543/4ff8f7fa-c5df-11e6-8728-f57bca711830.png)

**Comment by raisedadead** [comment]
Click Reset.

![image](https://cloud.githubusercontent.com/assets/1884376/21307127/2f802d48-c5fa-11e6-9b91-03cd972ef807.png)

Happy Coding.
