### ISSUE TITLE
Suggestion for site: add explanations

### ISSUE THREAD

**Issue by EphemeralArchitect** [FreeCodeCamp/FreeCodeCamp#1211]
I would like to make a suggestion. It would be nice if old terms/key concepts were able to, when scrolled over, show a definition and maybe a short example of that term/concept. I have moved through some of these lessons pretty quickly, but some have taken me longer because I forgot some of the terminology and how it's applied in/from previous lessons. Then it takes even longer to go back and figure out what the term referred to as the titles of the previous lessons don't have which terms were used, listed. The terminology is the greatest trouble I've had with learning coding as I am a visual learner: I can understand what the terms are by seeing an example of the code in context. I have been through CodeAcademy, CodeAvengers, and now freeCodeCamp; and the only one that partly helped in this matter was CodeAvengers. One thing they did that was also helpful was to have the instructions able to be scrolled down on without moving the code editor. This made it easy to move back and forth between reading the instructions and doing the code without having to constantly readjust my mouse position. I think these suggestions would greatly improve the quality of your site for absolute beginners.

**Comment by BerkeleyTrue** [comment]
We know scroll editor independently. We also have a great community driven Wiki with lots of additional information.

Happy Coding
