### ISSUE TITLE
Instructions sentence/grammar issue

### ISSUE THREAD

**Issue by discotechne** [FreeCodeCamp/FreeCodeCamp#12121]
Challenge [Use HTML5 to Require a Field](https://www.freecodecamp.com/challenges/use-html5-to-require-a-field) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The following paragraph from the instructions is ungrammatical:

"For example, if you wanted to make a text input field required, you can just add the word required within your input element, you would use: <input type="text" required>"

I suggest changing to the following:

"For example, if you wanted to make a text input field required, you can just add the word required within your input element, like this: <input type="text" required>"

**Comment by dhcodes** [comment]
Confirmed. First-timers only:

Change this line:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/1a7db665b9f76e70065c1507d584681ecad20b81/seed/challenges/01-front-end-development-certification/html5-and-css.json#L2568

per @discotechne's recommendation above.

**Comment by GramParallelo** [comment]
I'll take care of this, if I may?

**Comment by GramParallelo** [comment]
woop woop :100:

**Comment by Kartikkh** [comment]
is this issue fixed ?

**Comment by raisedadead** [comment]
@Kartikkh yes, when a pull request is opened referencing an issue it's shown in the thread, as you can see #12123 is opened as a fix.

Please feel free to browse through the lots of help wanted issues that we have open for contribution on the issues tab.

Thanks and happy fixing!
