### ISSUE TITLE
TypeError: str.split(...).toLowerCase is not a function

### ISSUE THREAD

**Issue by yorgos-dimitriadis** [FreeCodeCamp/FreeCodeCamp#12128]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Afunction%20titleCase(str)%20%7B%0A%20%20%0A%20%20var%20i%20%3D%200%3B%0A%20%20var%20s%20%3D%20str.split(%27%20%27).toLowerCase()%3B%0A%20%20%0A%20%20while(i%20%3C%3D%20s.length)%20%7B%0A%20%20%20%20%0A%20%20%20%20s%5Bi%5D%5B0%5D.toUpperCase()%3B%0A%20%20%20%20i%2B%2B%3B%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%0A%20%20return%20s.join(%27%20%27)%3B%0A%7D%0A%0AtitleCase(%22I%27m%20a%20little%20tea%20pot%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function titleCase(str) {
  
  var i = 0;
  var s = str.split(' ').toLowerCase();
  
  while(i <= s.length) {
    
    s[i][0].toUpperCase();
    i++;
  }
  
  
  
  return s.join(' ');
}

titleCase("I'm a little tea pot");

```

**Comment by raisedadead** [comment]
Thanks @yorgos-dimitriadis 

From the helpful link provided in the challenge for `String.prototype.split`:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split

>Return value
>
> An array of strings split at each point where the separator occurs in the given string.

Please reach out to the Help Chat for further assistance.

**Comment by ThadeusAjayi** [comment]
This could help:
[str.split() alternative](https://gist.github.com/ThadeusAjayi/1b87f9ed52822081cd199b952ce8ca29)
