### ISSUE TITLE
Improvement - Change the names of the properties to be without "" so it is less cofusing

### ISSUE THREAD

**Issue by lh15** [FreeCodeCamp/FreeCodeCamp#12125]
Challenge [Accessing Objects Properties with the Dot Operator](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-the-dot-operator#?solution=%0A%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%20hat%3A%20%22ballcap%22%2C%0A%20%20shirt%3A%20%22jersey%22%2C%0A%20%20shoes%3A%20%22cleats%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20hatValue%20%3D%20testObj.hat%3B%20%20%20%20%20%20%2F%2F%20Change%20this%20line%0Avar%20shirtValue%20%3D%20testObj.shirt%3B%20%20%20%20%2F%2F%20Change%20this%20line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var testObj = {
  hat: "ballcap",
  shirt: "jersey",
  shoes: "cleats"
};

// Only change code below this line

var hatValue = testObj.hat;      // Change this line
var shirtValue = testObj.shirt;    // Change this line

```

**Comment by raisedadead** [comment]
@lh15 Can you please explain more about what's confusing about the instructions? Thanks.

**Comment by lh15** [comment]
In the original broken code, hat, shirt and shoes are in ""(strings), however when accessing via a dot, strings dont work.
`// Setup
var testObj = {
  "hat": "ballcap",
  "shirt": "jersey",
  "shoes": "cleats"
};

// Only change code below this line

var hatValue = testObj;      // Change this line
var shirtValue = testObj;    // Change this line`

**Comment by raisedadead** [comment]
I can pass the challenge with:

```js
var testObj = {
  "hat": "ballcap",
...
...
};

var hatValue = testObj.hat;      
...
```

That is with the original code.

Can you post a few Screenshots of the issue, with the tests not working in your case?

**Comment by lh15** [comment]
So it works and passes the test. I just think that for a newbie, the fact the in the object then names are "strings" and when you access it in var hatValue = testObj.hat;, can be very confusing. Strings dont work when accessing the object. That was the trouble i had.

**Comment by raisedadead** [comment]
Hmm, I can see how the seed code and the examples are creating a confusion, need to revisit this challenge, and the other object access challenges a bit more.

/cc @FreeCodeCamp/moderators thoughts?

**Comment by systimotic** [comment]
@raisedadead I agree. I've seen quite a few issues about dot notation vs. bracket notation. They show that the way we teach this isn't clear to many people. I'm not aware of whether the curriculum expansion takes care of this or not.
Some issues that I have recently come across that might be (somewhat) related:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/12141 
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8207
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/11882

I think removing the quotes in this exercise would be a good change, as it makes it more consistent with the description. Overall, I think we may need to revisit how we teach objects. It's not something that's easy to explain or understand, so I'm not sure if we could do better, but it's probably worth taking another look at it.

**Comment by raisedadead** [comment]
thanks, @systimotic let's continue the discussion on #12141
