### ISSUE TITLE
Add completed bonfire comparisons

### ISSUE THREAD

**Issue by metasean** [FreeCodeCamp/FreeCodeCamp#1212]
After a camper completes a bonfire, it would be nice to see alternative solutions, preferably ranked by quality of code - ala CodeWars.

Related to #1182 & #1201

**Comment by BerkeleyTrue** [comment]
Solutions can now be found in the wiki and using camper bot. This really isn't Ideal to compare your solutions against someone else's code, in fact it is a form of premature optimization. Free Code Camp isn't about competition but about learning. What is important is that you complete the challenge. Once you get to the point of building your own projects outside of challenges, that is where the fun begins.

Happy Coding!

**Comment by metasean** [comment]
> This really isn't Ideal to compare your solutions

Actually, from a learner's perspective, being able to compare their own solution against the ideal solution is absolutely ideal. In fact, "***If feedback is not appropriate (either from an instructor or from self-reference to an information source), then the practice tends to be ineffective or even detrimental to learning.***" [1]. It isn't about competition with others, but self-reflection.

One of the biggest challenges becomes identifying "the ideal solution". But interestingly, reviewing peers' work can be, *in and of itself*, an effective pedagogical method if certain conditions are met [2, 3, 4], and FCC is a poster-child for these conditions!

The current approach means:

 - Having to go search for feedback (e.g. go look it up on the wiki), which means many learners simply won't get that feedback.
 - Lack of comparison between alternative answers (e.g. comparing and rating multiple working solutions) means learners aren't exposed to other solution paradigms, and therefore aren't developing relevant critical thinking skills.

And to be very clear, providing alternative solutions does not necessitate competition. Reviewing multiple alternative solutions (including non-optimal solutions), and comparing peers' ratings of solutions, is the goal. There is no need for names, affiliations, or anything else that breeds competition with anyone else. However, it should encourage self-reflection.

[1] https://en.wikipedia.org/wiki/Practice_%28learning_method%29#Deliberate_practice

[2] https://onlinelearninginsights.wordpress.com/2013/03/09/why-and-when-peer-grading-is-effective-for-open-and-online-learning/ , particularly:

>Listed below are a list of conditions needed to ensure that peer grading is effective:
1) When learners are at a similar skill level.
2) When assignments are low stakes [i.e. when a course is taken for professional development of personal interest as was the Digital Cultures course].
3) Where credit is not granted.
4) When learners are mature, self-directed and motivated.
5) When learners have experience in learning and navigating within a networked setting [if the review is completed in an open and online setting].
6) Learners have a developed set of communication skills.

[3] http://www.lrdc.pitt.edu/schunn/research/peers.html

[4] http://eric.ed.gov/?id=EJ938586
