### ISSUE TITLE
Night Mode Inactive Button Colour

### ISSUE THREAD

**Issue by breatheloud** [freeCodeCamp/freeCodeCamp#12127]
#### Issue Description

In Night Mode: whether the buttons in settings are active or inactive ("On" or "Off"), they are always the same colour, Green, which is somewhat misleading.  I tested on three different desktop browsers and all seem to be doing the same thing.

#### Browser Information

* Browser Name, Version: Chrome, 55.0.2883.95 (64-bit) | Safari, Version 10.0.1 | Firefox, 50.1.0
* Operating System: OS X El Capitan 10.11.6
* Desktop

#### Screenshot

<img width="619" alt="screen shot 2016-12-20 at 9 21 11 am" src="https://cloud.githubusercontent.com/assets/17322622/21341532/afdca25a-c695-11e6-9a4d-252df4555c59.png">

**Comment by MarkusToe** [comment]
@breatheloud would you consider giving the "Off" button a red background color? 

If no one else is working on this issue I would like to apply for it.

**Comment by raisedadead** [comment]
@MarkusToe awesome! Please open a pull request when you are ready.

In the normal mode the off state renders like this:
![image](https://cloud.githubusercontent.com/assets/1884376/21365399/3878dfea-c71b-11e6-8dab-c83790142be0.png)

We do not want a red in night mode I think just, removing the green background and defaulting it to the background gray should suffice, as it is for the normal mode.

**Comment by MarkusToe** [comment]
Is there a way to access the account page in my local dev environment?
