### ISSUE TITLE
TypeError: arr[i][y] is undefined

### ISSUE THREAD

**Issue by yorgos-dimitriadis** [FreeCodeCamp/FreeCodeCamp#12131]
Challenge [Return Largest Numbers in Arrays](https://www.freecodecamp.com/challenges/return-largest-numbers-in-arrays#?solution=%0Afunction%20largestOfFour(arr)%20%7B%0A%20%20%0A%20%20var%20lg%20%3D%200%3B%20%20%0A%20%20%0A%20%20for(i%3D0%3B%20i%20%3C%3D%204%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%0A%20%20%20%20for(y%3D0%3B%20y%20%3C%3D%204%3B%20y%2B%2B)%20%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20if(arr%5Bi%5D%5By%5D.length%20%3C%20lg.length)%20%7B%20lg%20%3D%20arr%5Bi%5D%5By%5D%3B%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20return%20lg.length%3B%0A%7D%0A%0AlargestOfFour(%5B%5B4%2C%205%2C%201%2C%203%5D%2C%20%5B13%2C%2027%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function largestOfFour(arr) {
  
  var lg = 0;  
  
  for(i=0; i <= 4; i++) {
    
    for(y=0; y <= 4; y++) {
      
      if(arr[i][y].length < lg.length) { lg = arr[i][y]; }
      
    }
    
    
  }
  
  return lg.length;
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

```

**Comment by spieg** [comment]
Sorry to say, but your code is off. You should review how to use for loops to go through arrays.
This place is for reporting bugs in freecodecamp, not for repoprting bugs in your code.
The best place to get help for problems with your code is one of the freecodecamp chatrooms.

Please close this issue.

Happy Coding.
