### ISSUE TITLE
Bug in "Create a Form Element"

### ISSUE THREAD

**Issue by Manish-Giri** [FreeCodeCamp/FreeCodeCamp#12138]
#### Challenge Name
Create a Form Element

[Challenge Link](https://www.freecodecamp.com/challenges/create-a-form-element#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%3Cul%3E%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%3Col%3E%0A%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%3C%2Fol%3E%0A%3Cform%20fccfaa%3D%22%2Fsubmit-cat-photo%22%3C%2Fform%3E%0A%3Cinput%20type%3D%22text%22%20placeholder%3D%22%2Fcat%20photo%20URL%22%3E%0A%0A%0A)

#### Issue Description

Challenge passes with incorrect code - incomplete opening `<form>` tag, and without nesting of `input` in `form`.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 55.0.2883.87 m
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```
<form action="/submit-cat-photo"</form>
<input type="text" placeholder="/cat photo URL"> 
```
#### Screenshot

![untitled](https://cloud.githubusercontent.com/assets/11348778/21369205/d80dc824-c6d3-11e6-9eba-ab740f780a4e.png)

**Comment by MrFreudJS** [comment]
I'm also pretty new, but I remember having to type this for it to work: <form action="/submit-cat-photo"><input type="text" placeholder="/cat photo URL"></form>

So basically close your form tag after the input in order to nest it within. Don't forget ">" to end your opening tag before you begin nesting. Good luck, & I hope this helped!

**Comment by dhcodes** [comment]
Interesting... must be something with the tests.

**Comment by xtatanx** [comment]
Hello,

I would like to work on this issue, however I am not sure how can I debug on the test. COuld someone please provide some guidance?

Regards

**Comment by Cwoodyard** [comment]
type this in:  </form action="/submit-cat-photo"> <input type="text" placeholder="cat photo URL">
</form>
and it should work. it took me a few tries although it worked

**Comment by HBelmont** [comment]
This is the only way that worked for me. `</form>` had to be underneath!
![bug1 2](https://cloud.githubusercontent.com/assets/26345392/23854768/872d6afe-07fb-11e7-8044-c694a2d9b027.png)
