### ISSUE TITLE
Scroll bar visible in mobile preview (and throws off layout)

### ISSUE THREAD

**Issue by Julix91** [freeCodeCamp/freeCodeCamp#12139]
#### Issue Description
I have a scroll bar on the mobile preview iframe, which throws off how the content is aligned.

#### Challenge Name

Happens in all the problems with mobile preview, for [example](https://www.freecodecamp.com/challenges/responsively-style-checkboxes)

#### Browser Information

* Browser Name, Version: Chrome (Canary)
* Operating System: Win 10
* Mobile, Desktop, or Tablet: Desktop (laptop) 

#### Screenshot

![error](https://cloud.githubusercontent.com/assets/12877287/21373754/1e99089c-c6d6-11e6-8c98-b2e833bdb6f8.jpg)

**Comment by Julix91** [comment]
I tried doing 'overflow: hidden' - on the html and body of the iframe, but that prevents scrolling entirely. - Also I'm not opposed to a scrollbar for a desktop user like me, but the frame should be just a tiny bit wider, so the bar fits.

**Comment by raisedadead** [comment]
@Julix91 thanks for reporting, yup the CSS needs more love on the HTML and jQuery Challenges.
While a perfect solution that we may have some time in future would be a multi-tab editor, and in the process make more space for the editor and the output (the iFrame in this case).

We have had some changes in the react version of the site, we will have a beta soon.

**Comment by systimotic** [comment]
We now have a new layout in the beta, so this issue has been resolved.

Happy coding!
