### ISSUE TITLE
Wrong parameter name in the challange "adding-a-default-option-in-switch-statements"

### ISSUE THREAD

**Issue by devforrose** [FreeCodeCamp/FreeCodeCamp#12136]
#### Challenge Name

https://www.freecodecamp.com/challenges/adding-a-default-option-in-switch-statements

#### Issue Description

The instructions say "Write a switch statement to set answer for the following conditions:" however the parameter in the function is "val", why the excessive doesn't work if you follow the instructions using "answer" in the switch statement. It does work if you use "val" in the switch statement.

UPDATE: 
I just realised that you are supposed to set the "answer" variable in each switch case, instead of returning a value. Please ignore this issue.

**Comment by erictleung** [comment]
Closing as resolved. Happy coding!
