### ISSUE TITLE
Updating Object Properties instruction issue

### ISSUE THREAD

**Issue by ChrisKissoon** [FreeCodeCamp/FreeCodeCamp#12143]
#### Challenge Name

[Updating Object Properties](https://www.freecodecamp.com/challenges/updating-object-properties#?solution=%0A%2F%2F%20Example%0Avar%20ourDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Camper%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22everything!%22%5D%0A%7D%3B%0A%0AourDog.name%20%3D%20%22Happy%20Camper%22%3B%0A%0A%2F%2F%20Setup%0Avar%20myDog%20%3D%20%7B%0A%20%20%22name%22%3A%20%22Coder%22%2C%0A%20%20%22legs%22%3A%204%2C%0A%20%20%22tails%22%3A%201%2C%0A%20%20%22friends%22%3A%20%5B%22Free%20Code%20Camp%20Campers%22%5D%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyDog%5B'name'%5D%20%3D%20%22Happy%20Camper%22%3B%0A%0A)

#### Issue Description

The instructions clearly states that i can use dot notation or bracket notation but when i use bracket  notation i get the error ["name"] is better written in dot notation. The challenge submits but i feel like that shouldn't happen. 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
myDog['name'] = "Happy Coder";
 
 
 
```

**Comment by raisedadead** [comment]
Related issue #12141

**Comment by raisedadead** [comment]
Closing in favor of issue #12141

**Comment by siguniang** [comment]
![image](https://cloud.githubusercontent.com/assets/24384921/21679895/670fef34-d381-11e6-90ca-4da21377affa.png)

**Comment by siguniang** [comment]
why miss?
![image](https://cloud.githubusercontent.com/assets/24384921/21679921/8c456612-d381-11e6-9bac-4423c9bd6e40.png)
