### ISSUE TITLE
Dot and Bracket

### ISSUE THREAD

**Issue by tencerw** [FreeCodeCamp/FreeCodeCamp#12149]
Challenge [Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%0A%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20var%20lookup%20%3D%7B%0A%20%20%20%20%22alpha%22%3A%22Adams%22%2C%0A%20%20%20%20%22bravo%22%3A%22Boston%22%2C%0A%20%20%20%20%22charlie%22%3A%22Chicago%22%2C%0A%20%20%20%20%22delta%22%3A%22Denver%22%2C%0A%20%20%20%20%22echo%22%3A%22Easy%22%2C%0A%20%20%20%20%22foxtrot%22%3A%22Frank%22%0A%20%20%20%20%0A%20%20%7D%3B%0A%20result%20%3D%20lookup%5Bval%5D%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22charlie%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line

  var lookup ={
    "alpha":"Adams",
    "bravo":"Boston",
    "charlie":"Chicago",
    "delta":"Denver",
    "echo":"Easy",
    "foxtrot":"Frank"
    
  };
 result = lookup[val];
  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");

```
The problem here is when i change

result = lookup[val] to result = lookup.val it doesn't work anymore. I thought the dot and brackets had identical meanings

**Comment by FlameFractal** [comment]
Dot notation wouldn't work when the property is stored in a variable.
This is one of the benefits of bracket notation that it could use a variable and not just string literal.

**Comment by dhcodes** [comment]
Thanks @FlameFractal . Closing as resolved.
