### ISSUE TITLE
Update the Contributing doc regarding commit message

### ISSUE THREAD

**Issue by dhcodes** [FreeCodeCamp/FreeCodeCamp#12140]
We should probably update the contributing doc to read:

>Do not add the issue number in the PR title or commit message.

instead of its current:

>Do not add the issue number in the PR title

The document is located here: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md under "Common Steps"

**Comment by aravindputrevu** [comment]
Can i work on this ?

**Comment by FlameFractal** [comment]
Is this assigned?

**Comment by dhcodes** [comment]
@aravindputrevu looks like @FlameFractal has already submitted a PR. @FlameFractal, in the future, if another user comments on the issue thread, he/she should have a chance to make the PR before jumping on it. 👍

**Comment by FlameFractal** [comment]
Oh. Apologies! @aravindputrevu

**Comment by aravindputrevu** [comment]
No problem. Thank you @FlameFractal, @dhcodes
