### ISSUE TITLE
problem with instructions

### ISSUE THREAD

**Issue by lbederov** [FreeCodeCamp/FreeCodeCamp#1215]
Challenge http://www.freecodecamp.com/challenges/waypoint-pair-program-on-bonfires has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The #6 in instructions links to a SLACK chat room:
"We have a special chat room for people ready to pair program. Go to our http://freecodecamp.slack.com/messages/letspair and type "Hello Pair Programmers!" "

It didn't look right to me that it asked to sign up, so I found a blog item about ditching Slack. I guess, I'll head to Gitter instead, but wanted you to know about the problem of the wrong link.

**Comment by alexlincoln** [comment]
Duplicate of https://github.com/FreeCodeCamp/freecodecamp/issues/1175

**Comment by ahstro** [comment]
Was fixed at some point and is probably defunct since the link isn't even active anymore. Close?
