### ISSUE TITLE
Mobile issue

### ISSUE THREAD

**Issue by Israel-87** [FreeCodeCamp/FreeCodeCamp#12154]
I get the error code: 
Your h2 element should be red. What am I doing wrong. It worked fine in the next phase?

```
<h2 class="red-text">CatPhotoApp</h2>
```

#### Challenge Name

[Use a CSS class to style an element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%C2%A0.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A)

#### Browser Information
 

I'm not sure

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: Mobile

**Comment by dhcodes** [comment]
@Israel-87 this is a known issue that will be resolved next time the site is updated. It has to do with how mobile chrome handles nbsp; For more info and the fix see Bouncey's comment in this issue #11625

Closing as duplicate.

**Comment by Israel-87** [comment]
Thank you
