### ISSUE TITLE
This is not reading my 2nd <p></p> tags, it says I still need to add them.

### ISSUE THREAD

**Issue by stutzro** [FreeCodeCamp/FreeCodeCamp#12157]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A16px%3B%20%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  p {
    font-size:16px; 
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>


```

**Comment by stutzro** [comment]
This is not recognizing my 2nd <p> and is saying I still need to add the Kitty ipsum dolor...content.  I tried a hard refresh, I tried cutting some of the text out so it was not exactly like the first paragraph, I tried switching the paragraphs, nothing worked.

**Comment by Manish-Giri** [comment]
@stutzro As the instruction says - 
> Create a second p element after the existing p element with the following kitty ipsum text: Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.

The content of your second `p` element is wrong. Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) if you need help with this challenge.

Happy Coding!

**Comment by raisedadead** [comment]
Thanks @stutzro for reporting, please proceed as suggested by @Manish-Giri !
@Manish-Giri thanks for commenting.

**Comment by stutzro** [comment]
But the instructions don’t say this, they say to just use some of the content already there.  I tried altering the text as well and it did not work.
Thanks,
Ronnett Stutz
UVU Student Affairs
Web Developer
Phone: 801.863.7976
Email: stutzro@uvu.edu
Office: LC 228
