### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by FlameFractal** [FreeCodeCamp/FreeCodeCamp#12166]
Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage) has an issue.

The grammar is a little off, in one of the User Story lines.

Change to: 
> I can navigate

instead of

> I navigate

![image](https://cloud.githubusercontent.com/assets/9962648/21428073/2d6ea288-c87e-11e6-8bfe-a615ce305a4b.png)

**Comment by raisedadead** [comment]
Thanks @FlameFractal .

#### First timer issue!

Change this line of code to reflect the suggestion as mentioned above:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-ziplines.json#L202

**Please follow the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).**

**Comment by xtatanx** [comment]
I can work on this if posible :)

**Comment by raisedadead** [comment]
@xtatanx Thanks a lot for your interest but you already have a PR open, let's keep this for first timers. Please look into the open help wanted issues instead.

Thanks once again, and happy fixing!

**Comment by xtatanx** [comment]
Ohhh ok sure no problem :) thanks to you guys!
