### ISSUE TITLE
Result is a blank?

### ISSUE THREAD

**Issue by tonystaark** [FreeCodeCamp/FreeCodeCamp#12162]
I was testing the instruction code given and expected that "this outputs each sub-element in arr one at a time. " (as suggested by the instruction). However, there is nothing showing on console. Is this a bug?

Challenge [Nesting For Loops](https://www.freecodecamp.com/challenges/nesting-for-loops#?solution=%0Afunction%20multiplyAll(arr)%20%7B%0A%20%20var%20product%20%3D%201%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20product%3B%0A%7D%0A%0A%2F%2F%20Modify%20values%20below%20to%20test%20your%20code%0AmultiplyAll(%5B%5B1%2C2%5D%2C%5B3%2C4%5D%2C%5B5%2C6%2C7%5D%5D)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var arr = [
[1,2], [3,4], [5,6]
];
for (var i=0; i < arr.length; i++) {
for (var j=0; j < arr[i].length; j++) {
console.log(arr[i][j]);
}
}

```
Note: This has nothing to do with the challenge needed to pass.

**Comment by raisedadead** [comment]
@tonystaark thanks for reporting.

The standard `console.log` will show up in the Developer Console of your browser (F12) in your case. They will not show up in the console for the challenge editor.

We are upgrading this to the challenge editors console view in a future release.
