### ISSUE TITLE
Escaping is not happening

### ISSUE THREAD

**Issue by Umesh8Joshi** [FreeCodeCamp/FreeCodeCamp#12165]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D%22Firstline%5Cn%5C%5CSecondLine%5C%5C%5CrThirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr="Firstline\n\\SecondLine\\\rThirdLine"; // Change this line

```

**Comment by Dayfiri** [comment]
Hi @Umesh8Joshi
For help with the assignments please refer to [HELP](https://gitter.im/FreeCodeCamp/Help) room of FreeCodeCamp. There you will be provided with all the help you need in the future.

Happy coding ;)

**Comment by raisedadead** [comment]
@Umesh8Joshi thanks for reporting.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

**Comment by AsadTuruu** [comment]
var myStr ="FirstLine\n\\SecondLine\\\rThirdLine";// Change this line
thats work

**Comment by AsadTuruu** [comment]
var myStr ="FirstLine\n\\SecondLine\\\rThirdLine";// Change this line

**Comment by AsadTuruu** [comment]
var myStr ="FirstLine\n\\SecondLine\\\rThirdLine";// Change this line

**Comment by AsadTuruu** [comment]
\\\r

**Comment by AsadTuruu** [comment]
three backslash \r

**Comment by AsadTuruu** [comment]
\\SecondL:ine
