### ISSUE TITLE
Challenge not accepting my Right Solution.

### ISSUE THREAD

**Issue by FahadYousafMahar** [FreeCodeCamp/FreeCodeCamp#12172]
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#?solution=%20var%20product%3D1%3B%0A%0Afunction%20factorialize(num)%20%7B%0A%20%20for%20(var%20i%3D1%3B%20i%3C%3Dnum%3B%20i%2B%2B)%7B%0A%20%20%20product%20%3D%20product%20*%20i%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20product%3B%0A%7D%0A%0Afactorialize(5)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
I wrote the code below and tested it with factorialize(20); & factorialize(10); & factorialize(5); .
It gives the right output but it is not accepted as a solution by Challenge. I tried removing cookies and performing on other browsers.

My code:
```javascript
 var product=1;

function factorialize(num) {
  for (var i=1; i<=num; i++){
   product = product * i;
  }
  
  return product;
}

factorialize(5);

```
![image](https://cloud.githubusercontent.com/assets/20330772/21436019/578f13fc-c89e-11e6-969e-5918eeb6c759.png)

**Comment by erictleung** [comment]
@FahadYousafMahar the tests run your function each time. Any global variables are changed accordingly. Put your `product` variable inside your function and your function should pass. Happy coding!

Related: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/9063

**Comment by leonardocaltei** [comment]
@FahadYousafMahar Hello, I've finished this challenge and I've the same problem, your post here helped a lot! Can you explain your code? My code its a lot more big hahahaha I'm curious with your logic, here's my code:

`<div class="well">
function factorialize(num) {
  var estoque = [];
  var resultado;
  var i;
  var bat = i;
  if (num === 0){
    return 1;
  } else if (num == 1) {
    return 1;
  } else if (num > 1) {
    
  for (i = 1; i <= num; i++) { 
    estoque.push(i);
    //código para realizar multiplicação do estoque
    resultado = estoque.reduce(function(a,b){return a*b;});
}
    return resultado;
}

}

factorialize(20);
</div>`
