### ISSUE TITLE
Code from other's profiles should not be stored in browser

### ISSUE THREAD

**Issue by sahilsunny** [freeCodeCamp/freeCodeCamp#12173]
Challenge [Accessing Nested Arrays](https://www.freecodecamp.com/challenges/accessing-nested-arrays#?solution=%0A%2F%2F%20Setup%0Avar%20myPlants%20%3D%20%5B%0A%20%20%7B%20%0A%20%20%20%20type%3A%20%22flowers%22%2C%0A%20%20%20%20list%3A%20%5B%0A%20%20%20%20%20%20%22rose%22%2C%0A%20%20%20%20%20%20%22tulip%22%2C%0A%20%20%20%20%20%20%22dandelion%22%0A%20%20%20%20%5D%0A%20%20%7D%2C%0A%20%20%7B%0A%20%20%20%20type%3A%20%22trees%22%2C%0A%20%20%20%20list%3A%20%5B%0A%20%20%20%20%20%20%22fir%22%2C%0A%20%20%20%20%20%20%22pine%22%2C%0A%20%20%20%20%20%20%22birch%22%0A%20%20%20%20%5D%0A%20%20%7D%20%20%0A%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20secondTree%20%3D%20%22myPlant%5B0%5D.%22%3B%20%2F%2F%20Change%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myPlants = [
  { 
    type: "flowers",
    list: [
      "rose",
      "tulip",
      "dandelion"
    ]
  },
  {
    type: "trees",
    list: [
      "fir",
      "pine",
      "birch"
    ]
  }  
];

// Only change code below this line

var secondTree = " "; // Change this line


```
We all know that sharing free code camp's challenge link will allow others to check on the problem. But there is a problem. If someone opens the link the problematic code will be saved to their account. If a new user who hasn't completed the challenge opened that link in his past, he may face issues due to missing codes. It happened to me. Instead of var secondTree = " "; // Change this line | I got myPlant[1].list[1]; which made me confused and was giving me a reference error. The problem was solved with code reset. But those users who don't know about code reset might face some problem.

**Comment by erictleung** [comment]
@sahilsunny thanks for the issue. Yes, this has been brought up before. I too have been aware of this and whenever I open someone else's code, I open it up into an incognito mode so that it doesn't affect my own progress. I think there's an issue somewhere that addresses this, but I can't find it. Anyways, I'm not sure or can't remember exact how the rest of the community feels about this. I'll leave this open for discussion.

cc/ @FreeCodeCamp/moderators

**Comment by systimotic** [comment]
I think this will be resolved with [https://github.com/FreeCodeCamp/FreeCodeCamp/projects/4](the code sharing overhaul). Not sure though. Would be great if someone could confirm.

**Comment by raisedadead** [comment]
@systimotic that project aims to target for backend challenges only. 
@BerkeleyTrue do we have any plans to remove the storing code from visiting someone's solution in the cache?

**Comment by BerkeleyTrue** [comment]
The code sharing overhaul would effect all challenges with solutions. The idea is to store code in redis and use ids to find that code instead of encoding them in the uri.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
