### ISSUE TITLE
Output is all right but Solution is not accepted.

### ISSUE THREAD

**Issue by FahadYousafMahar** [FreeCodeCamp/FreeCodeCamp#12171]
Challenge [Reverse a String](https://www.freecodecamp.com/challenges/reverse-a-string#?solution=var%20array%3D%5B%5D%3B%0Avar%20string%3D%22%22%3B%0A%0Afunction%20reverseString(str)%20%7B%0A%2F*%20var%20splitStr%3D%20str.split(%22%22)%3B%0A%20%20var%20Reversed%3D%20splitStr.reverse()%3B%0A%20%20var%20Concated%3DReversed.join(%22%22)%3B%0A%20%20%20%20return%20Concated%3B%0A%0A%20%20*%2F%0A%20%20%0A%20%20%0A%20%20for%20(%20i%3D0%20%3B%20i%20%3C%20str.length%3B%20i%2B%2B%20)%7B%0A%20%20array.unshift(str%5Bi%5D)%3B%0A%20%20%7D%0A%20%20var%20joined%3Darray.join(%22%22)%3B%20%0A%20%20return%20joined%3B%0A%7D%0A%0AreverseString(%22Howdy%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
I made a solution by reverse-input the contents into Array by using "unshift" and then joined them back.
Hence on test the output was as needed.The string was reversed but it was not accepted as solution.Please Check into This. I have written two ways to perform this. The one in written as comment passed the solution and reversed the string but the one written earlier (the actual code)also did the required job however could not pass the challenge.The output for both ways is same.Please look into it.
![image](https://cloud.githubusercontent.com/assets/20330772/21434948/cf1e7d82-c898-11e6-83a2-ac9faf09e848.png)

My code:

```javascript
var array=[];
var string="";

function reverseString(str) {

 // Code Below gives the perfect output but is not accepted.
  for ( i=0 ; i < str.length; i++ ){
  array.unshift(str[i]);
  }
  var joined=array.join(""); 
  return joined;
}

reverseString("Howdy");

```

**Comment by Manish-Giri** [comment]
@FahadYousafMahar Try to make the two global variables at the top as local instead, and then test it again.

**Comment by erictleung** [comment]
@FahadYousafMahar same as your other issue. You have global variables. Put those within your function as @Manish-Giri has pointed out and your code should pass. Happy coding!

**Comment by FahadYousafMahar** [comment]
@Manish-Giri @erictleung  Thnx. My Bad .
