### ISSUE TITLE
Cannot Run Tests

### ISSUE THREAD

**Issue by nhuthuynh** [FreeCodeCamp/FreeCodeCamp#12177]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3Ekitty%20ipsum%20%3C%2Fp%3E%0A%3Cp%20%3Ekitty%20ipsum%20text%20kitty%20%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">kitty ipsum </p>
<p >kitty ipsum text kitty </p>

```

**Comment by Manish-Giri** [comment]
@nhuthuynh Your code is incomplete. Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) for help with the challenge. Happy Coding!
