### ISSUE TITLE
.length and .length +2 are not num, Right?

### ISSUE THREAD

**Issue by kolu99** [FreeCodeCamp/FreeCodeCamp#12174]
![not numbers](https://cloud.githubusercontent.com/assets/24615534/21443168/02aac5c0-c871-11e6-9676-c8b63877451e.jpg)
Challenge [Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string#?solution=%0Afunction%20truncateString(str%2C%20num)%20%7B%0A%20%20var%20diffA%20%3D%20str.length%20-%20num%3B%0A%20%20var%20arrayOne%20%3D%20str.split(%27%27)%3B%0A%20%20%20%20%20%20if(num%20%3C%3D%203)%20%7B%0A%20%20%20%20%20%20%20%20%20%20var%20a%20%3D%200%3B%0A%20%20%20%20%20%20%20%20%20%20arrayTwo%20%3D%20%5B%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20while(a%20%3C%20num)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20arrayTwo%20%2B%3D%20arrayOne.shift()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20a%2B%2B%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20var%20strOne%20%3D%20arrayTwo.toString()%3B%0A%20%20%20%20%20%20%20%20%20%20var%20strTwo%20%3D%20%22...%22%3B%0A%20%20%20%20%20%20%20%20%20%20var%20combineOne%20%3D%20strOne.concat(strTwo)%3B%0A%20%20%20%20%20%20%20%20%20%20return%20combineOne%3B%20%20%20%0A%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20var%20b%20%3D%200%3B%0A%20%20%20%20%20%20%20%20%20%20arrayThree%20%3D%20%5B%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20while(b%20%3C%20num-3)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20arrayThree%20%2B%3D%20arrayOne.shift()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20b%2B%2B%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20var%20strThree%20%3D%20arrayThree.toString()%3B%0A%20%20%20%20%20%20%20%20%20%20var%20strFour%20%3D%20%22...%22%3B%0A%20%20%20%20%20%20%20%20%20%20var%20combineTwo%20%3D%20strThree.concat(strFour)%3B%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20return%20combineTwo%3B%0A%20%20%20%20%20%20%7D%0A%7D%0A%0AtruncateString(%22Absolutely%20Longer%22%2C%202)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function truncateString(str, num) {
  var diffA = str.length - num;
  var arrayOne = str.split('');
      if(num <= 3) {
          var a = 0;
          arrayTwo = [];
              while(a < num) {
              arrayTwo += arrayOne.shift();
              a++;
              }
          var strOne = arrayTwo.toString();
          var strTwo = "...";
          var combineOne = strOne.concat(strTwo);
          return combineOne;   
      } else {
          var b = 0;
          arrayThree = [];
              while(b < num-3) {
              arrayThree += arrayOne.shift();
              b++;
              }
          var strThree = arrayThree.toString();
          var strFour = "...";
          var combineTwo = strThree.concat(strFour);            
          return combineTwo;
      }
}

truncateString("Absolutely Longer", 2);

```

**Comment by erictleung** [comment]
@kolu99 the `.length` is a method of strings. One of the tests is `"A-tisket a-tasket A green and yellow basket".length` and this does evaluate to a number, namely `43`.  Closing as not a bug with the site. Please use the help rooms first with any coding questions. Happy coding!

**Comment by kolu99** [comment]
it's not getting imput into a function though as a number.
