### ISSUE TITLE
Bonfire passes tests but does not mark as complete

### ISSUE THREAD

**Issue by michael-krebs** [FreeCodeCamp/FreeCodeCamp#1217]
I've passed all the test cases, but I don't get the "good job" modal, nor does it mark as complete on the map or save my code on my profile. The bonfire in question is http://www.freecodecamp.com/challenges/bonfire-binary-agents.

Here is my passing and yet not passing code:
```javascript
function binaryAgent(str) {
  var newStr = "";
  arr = str.split(" ");
  arr.forEach(function(current) {
    newStr += String.fromCharCode(current);
  });
  return newStr;
}
```

**Comment by michael-krebs** [comment]
OK, so the code is incorrect. I suppose the bug is that it marks all of the test cases as correct when it they are not.

**Comment by benschenker** [comment]
Hey @michael-krebs I've been unable to replicate this.

Closing for now but feel free to open if this is still an issue for you
