### ISSUE TITLE
Stuck on Change the color text, my code is correct 

### ISSUE THREAD

**Issue by hazideux** [FreeCodeCamp/FreeCodeCamp#12183]
What they asked me to do:

<style>
  h2 {color: red;}
</style>

Note that it's important to have both opening and closing curly braces ({ and }) around each element's style. You also need to make sure your element's style is between the opening and closing style tags. Finally, be sure to add the semicolon to the end of each of your element's styles.

My code:
```html

<style>
  h2 {color: blue;}
</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

Clearly there's no error what I code, but somehow I can't get through this stage.. Why? 
```

**Comment by dhcodes** [comment]
@hazideux you have an error in your code; please consider asking for help in the chat room by clicking the Help button on the challenge page. Happy coding!

**Comment by akkuraten** [comment]
+1
