### ISSUE TITLE
My answers seem to have disappeared from the editor??? Not just this one.

### ISSUE THREAD

**Issue by interglobalmedia** [FreeCodeCamp/FreeCodeCamp#12189]
Challenge [Caesars Cipher](https://www.freecodecamp.com/challenges/caesars-cipher) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function rot13(str) { // LBH QVQ VG!
  
  return str;
}

// Change the inputs below to test
rot13("SERR PBQR PNZC");

```
Hi,

Apparently all my answers have disapeared from the editor. Good thing I have had backups. I'm looking through everything right now to see if it happened with ALL my algorithms. Why is this happening?!

**Comment by erictleung** [comment]
@interglobalmedia sorry to hear about your issue. Challenges are saved within the browser's cache. If that was cleaned out or you're using a different computer, your "saved" challenge code will not be there. Your answers are saved in a database, which you can access your answers on your FreeCodeCamp profile https://www.freecodecamp.com/interglobalmedia. Let us know if that clears things up or if you're experiencing a different issue. Thanks!

**Comment by interglobalmedia** [comment]
Hi Eric,

You are right. They were saved to the database. I found where they are stored in my profile. I have cleared my cache many a time, so that's I guess why nothing appeared there. Thanks!

**Comment by erictleung** [comment]
@interglobalmedia no problem! Closing this as issue appears resolved. Happy coding!
