### ISSUE TITLE
Spelling error 

### ISSUE THREAD

**Issue by GRALTOS** [FreeCodeCamp/freecodecamp#1218]
I'm on the exercise: "Waypoint: Add a submit button to a form", and the second of four bullets in the lower left says: "Your submit button should have be of input type "submit".

It should read: Your submit button should be of input type "submit"

At least I think it should say that.

![image](https://cloud.githubusercontent.com/assets/9011185/8534503/204d30ee-23fa-11e5-8563-0e64b17bfc35.png)

**Comment by benmcmahon100** [comment]
There's a fix for this that is ready to be merged so this issue can now be closed.
