### ISSUE TITLE
TypeErrors in 'Use jQuery to Modify the Entire Page' Challenge are displayed after fixing the error and the animation completes (before running tests)

### ISSUE THREAD

**Issue by rholinshead** [FreeCodeCamp/FreeCodeCamp#12190]
#### Challenge Name
https://www.freecodecamp.com/challenges/use-jquery-to-modify-the-entire-page

#### Issue Description
Create a TypeError such as typing 'addClas' instead of 'addClass' for adding the animated and hinge classes to the body:

$("body").addClas("animated hinge");

Then click "Run tests" and note that no errors are displayed, just a red 'x' beside the requirement "Add the classes animated and hinge to your body element. "

Then add the second 's' to addClass and watch the hinge animation complete in the phone screen, without clicking "Run tests". The animation succeeds but then a TypeError is displayed in the phone screen:

"TypeError: $(...).addClas is not a function"

#### Browser Information

* Browser Name, Version: Firefox v50.1.0
* Operating System: Ubuntu 16.04 LTS
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
![image](https://cloud.githubusercontent.com/assets/5060851/21462924/f9e9b274-c92f-11e6-80ef-ea79e0af4352.png)

**Comment by raisedadead** [comment]
This is due to the automatic code execution on the jQuery challenges. Can anyone confirm if this is resolved  in the staging.

I will do so as well, but may be delayed in getting back.

**Comment by systimotic** [comment]
@raisedadead Sorry, I should have checked in staging right away. In staging, the error never shows up, neither when it's supposed to, or after it. Not sure if that means this issue can be closed 😕

**Comment by raisedadead** [comment]
@systimotic thanks for confirming, I was doubtful and now I confirmed as well. Closing as resolved.
