### ISSUE TITLE
wrong code passed challenge for me 

### ISSUE THREAD

**Issue by Bene2dict** [FreeCodeCamp/FreeCodeCamp#12197]
Challenge [Remove an Element Using jQuery](https://www.freecodecamp.com/challenges/remove-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
     $(.remove("target4")
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```
That was the code i used to pass the challenge 
the wrong code is the ```$(.remove("target4");```
the correct code is ```$("#target4").remove(); ```
Thanks in advance

**Comment by texas2010** [comment]
I can't pass it with that incorrect code. it seems it is not bug to me.

**Comment by erictleung** [comment]
@Bene2dict I'm also unable to pass the challenge with the incorrect code. I get a `SyntaxError: Unexpected token .`. Do you have a screenshot of you passing the challenge with the incorrect code? Thanks!

**Comment by texas2010** [comment]
@erictleung, I got `SyntaxError: Unexpected token ..` too.

**Comment by dbess1** [comment]
@Bene2dict Kindly show a screen shot of the challenge with the wrong code passing through. The challenge doesn't seem to go on because of the syntax error.

**Comment by raisedadead** [comment]
Please comment below if this is still an issue.
