### ISSUE TITLE
Your p elements should use the font Monospace. Why it doesn't work

### ISSUE THREAD

**Issue by shubh28494** [FreeCodeCamp/FreeCodeCamp#12205]
```html
<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
    font-family : monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by texas2010** [comment]
@shubh28494, which challenge name?

**Comment by erictleung** [comment]
@shubh28494 your code passes for me. Can you give more information about your issue? What browser are you using? What device are you on? Monospace should be built into your browser, which allows it to be rendered, but if you're using an older browser or not one of the mature browsers such as Chrome/Firefox/Safari, then you'll run into issues.

FYI [Challenge: Set the Font Family of an Element](https://www.freecodecamp.com/challenges/set-the-font-family-of-an-element)

**Comment by raisedadead** [comment]
Please comment with the requirement stated above, and we can re-open.

**Comment by rishabjn** [comment]
I also can't complete this challenge. I am using chrome browser.
