### ISSUE TITLE
its saying im not using rgb to change the color. from what i can tell, i am. i even copied and pasted to make sure of no typo. i get check marks for changing the color , but it thinks im not using rgb

### ISSUE THREAD

**Issue by ShiveringCode** [FreeCodeCamp/FreeCodeCamp#12209]
Challenge [Use RGB to Mix Colors](https://www.freecodecamp.com/challenges/use-rgb-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20rgb(255%2C%200%2C%200)%0A%20%20%7D%0A%20%20.orchid-text%20%7B%0A%20%20%20%20color%3A%20rgb(218%2C%20112%2C%20214)%0A%20%20%7D%0A%20%20.sienna-text%20%7B%0A%20%20%20%20color%3A%20rgb(160%2C%2082%2C%2045)%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20rgb(0%2C%200%2C%20255)%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orchid-text%22%3EI%20am%20orchid!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22sienna-text%22%3EI%20am%20sienna!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22blue-text%22%3EI%20am%20blue!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: rgb(255, 0, 0)
  }
  .orchid-text {
    color: rgb(218, 112, 214)
  }
  .sienna-text {
    color: rgb(160, 82, 45)
  }
  .blue-text {
    color: rgb(0, 0, 255)
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>

```

**Comment by Manish-Giri** [comment]
@ShiveringCode CSS statements must end must `;`, which is missing on all four of your statements.

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) first for help with issues like these, in future. Happy Coding!

**Comment by texas2010** [comment]
@Manish-Giri is right about that.

closed this issue as don't have a bug.
