### ISSUE TITLE
Won't let me continue  because of no p tag cling tag

### ISSUE THREAD

**Issue by monzamatt12** [FreeCodeCamp/FreeCodeCamp#12207]
My challenge is makes sure all p elements have closing tag 
```html
<style>
  .red-text {
    color: red;
  } 
</style>

<h2 class="red-text">CatPhotoApp </h2>

<p class="red-text"> Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<P style="FONT-SIZE: 16PX;"> Purr jump eat the grass rip the couch scratched sunbathe, </p>

```

**Comment by texas2010** [comment]
@monzamatt12 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
