### ISSUE TITLE
Factorialize a number

### ISSUE THREAD

**Issue by Tejos16** [FreeCodeCamp/FreeCodeCamp#12215]
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#?solution=%0Afunction%20factorialize(num)%20%7B%0A%20%20if%20(num%20%3C%200)%20%0A%20%20%20%20return%20-1%3B%0A%20%20%0A%20%20else%20if(num%20%3D%3D%3D%200)%3B%20%0A%20%20%20%20return%201%3B%0Aelse%20%20%0A%20%20%7B%20%20%0A%20%20return%20(num%20*%20factorialize(num-1))%3B%0A%20%20%20%20%7D%0A%7D%0A%0Afactorialize(5)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function factorialize(num) {
  if (num < 0) 
    return -1;
  
  else if(num === 0); 
    return 1;
else  
  {  
  return (num * factorialize(num-1));
    }
}

factorialize(5);

```

**Comment by raisedadead** [comment]
Hi @Tejos16 

Thanks for the report.

Your code is incorrect, the linter in the editor is giving you warnings, and error. Please re-check.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
