### ISSUE TITLE
Inconsistent Spelling

### ISSUE THREAD

**Issue by AaronTakizad** [FreeCodeCamp/FreeCodeCamp#12214]
Challenge [Override Class Declarations with Inline Styles](https://www.freecodecamp.com/challenges/override-class-declarations-with-inline-styles#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20%23orange-text%20%7B%0A%20%20%20%20color%3A%20orange%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20id%3D%22orange-text%22%20class%3D%22pink-text%20blue-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

There is inconsistent spelling in the instructions. Is it "inline" or "in-line"?

**Comment by erictleung** [comment]
@AaronTakizad thanks for the issue. They should all be `inline`.
