### ISSUE TITLE
Bonfires :: Specific exercises keep showing up in the "Learn" rotation and never get marked as 'done' 

### ISSUE THREAD

**Issue by philsco** [FreeCodeCamp/FreeCodeCamp#1222]
Challenge http://www.freecodecamp.com/challenges/bonfire-spinal-tap-case has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The first 40 or so Bonfires keep coming back in the rotation ("Learn" section) as new, even though they were completed (some multiple times) a while ago (as reflected under the user profile section and the Map section).
![spinal_map](https://cloud.githubusercontent.com/assets/1385781/8535962/bd70339e-23ff-11e5-8a35-c98a08fb69b2.png)
![spinal_learn](https://cloud.githubusercontent.com/assets/1385781/8535963/bd750e5a-23ff-11e5-8a4d-2221461f3d73.png)
![spinal_profile](https://cloud.githubusercontent.com/assets/1385781/8535964/bd782950-23ff-11e5-9732-fa3a0b53d0bb.png)

**Comment by benschenker** [comment]
Closing as stale, please reopen if this issue is still present for you
