### ISSUE TITLE
Insert-Pointer-Issue in Chrome macOS fullscreen 

### ISSUE THREAD

**Issue by yeazes** [FreeCodeCamp/FreeCodeCamp#12239]
#### Challenge Name

https://www.freecodecamp.com/challenges/style-text-inputs-as-form-controls
But its the same with all other challenges.

#### Issue Description

Happens when using Chrome in macOS fullscreen and while hiding the toolbars (2nd in "Views" tab).
Then it often happens that when I try to click on certain spots on the code (for example the word personality in this challenge) then the insert line appears far away from where I clicked (mostly left of it or even above). Clicking again doesn't help. Then I do something (hard-refresh the page, show and hide the toolbar or even change font-size) and it will work again for some minutes and finally the same problem will return.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 55.0.2883.95 (64-bit
* Operating System: macOS Sierra, Version 10.12.2 (16C67)
* Mobile, Desktop, or Tablet: MacBook Pro (Retina, 13-inch, Late 2012)

**Comment by raisedadead** [comment]
@yeazes can you confirm this is the same as #7847? And most certainly this is not related to the toolbar at all.

**Comment by yeazes** [comment]
Yes that is the same problem! Could be thats its not related to the toolbar and its hard to reliably reproduce it too.

**Comment by raisedadead** [comment]
@yeazes thanks for confirming, please follow along that other thread for work around, and we have fixed this in a new upcoming release. Please bear with us until its out.

Closing in favor of #7847 as a duplicate.

**Comment by girlboss558** [comment]
I am having this same problem with a lot of challenges, but am stuck on challenge 80. When does the new release come out?
