### ISSUE TITLE
failed to connect the local repository

### ISSUE THREAD

**Issue by kosmasdamianos** [FreeCodeCamp/FreeCodeCamp#12235]
Hello,
I am trying  to connect my local repository with the remote repository, but it fails to do so. Instead I get the message " fatal: remote origin already exists " , afterwards it asks for my username which I provided and my password, which I couldn't type it in . When I click return, I get the following message " remote: anonymous access to kosmasdamianos/iTipper.git denied. fatal: Authentication failed for ' https:// github.com/kosmasdamianos/iTipper.git/. "﻿

**Comment by texas2010** [comment]
@kosmasdamianos, it seems your problem is nothing with FreeCodeCamp site.  sorry. this issue thread is only FreeCodeCamp repo.
