### ISSUE TITLE
I couldn't able to figure out the issue.so please help me to findout.

### ISSUE THREAD

**Issue by Indhumathivishalini** [FreeCodeCamp/FreeCodeCamp#12238]
Challenge [Nesting For Loops](https://www.freecodecamp.com/challenges/nesting-for-loops#?solution=%0Afunction%20multiplyAll(arr)%20%7B%0A%20%20var%20product%20%3D%201%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20for%20(var%20i%20%3D0%20%3B%20i%3C%20arr.length%3Bi%2B%2B)%20%7B%0A%20%20%20for(var%20j%3D0%20%3B%20j%3Carr%5Bi%5D.length%3B%20j%2B%2B)%0A%20%20%20product*%3Darr%5Bi%5D%5Bj%5D%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20product%3B%0A%7D%0A%7D%0A%2F%2F%20Modify%20values%20below%20to%20test%20your%20code%0A%2F%2FmultiplyAll(%5B%5B1%2C2%5D%2C%5B3%2C4%5D%2C%5B5%2C6%2C7%5D%5D)%3B%0AmultiplyAll(%5B%5B1%5D%2C%5B2%5D%2C%5B3%5D%5D)%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function multiplyAll(arr) {
  var product = 1;
  // Only change code below this line
  for (var i =0 ; i< arr.length;i++) {
   for(var j=0 ; j<arr[i].length; j++)
   product*=arr[i][j];
  // Only change code above this line
  return product;
}
}
// Modify values below to test your code
//multiplyAll([[1,2],[3,4],[5,6,7]]);
multiplyAll([[1],[2],[3]]);



```

**Comment by bazita** [comment]
the problem is 
 if change multiplyAll by arr the problem solved
