### ISSUE TITLE
Allow hosting of project code on Services other than Github

### ISSUE THREAD

**Issue by yunnysunny** [FreeCodeCamp/FreeCodeCamp#12230]
Challenge [URL Shortener Microservice](https://www.freecodecamp.com/challenges/url-shortener-microservice) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I finished the code for this challenge , but I have to create a new github project. I only want to host my code on github for open source project. And I don't want to show some test code for my followers.

**Comment by raisedadead** [comment]
@yunnysunny thanks we request hosting code on GitHub so that it's available to the reviewers. 

If you have any test code that you do not want to be part of the repository you create on the GitHub, then you can isolate the code from the project and host only the parts that are necessary for the user stories of the challenge. But all the code that is the part of the solution for the challenge should be on GitHub for reviewing.

You may remove the test code (and keep it separately, anywhere you prefer).

Thanks and happy coding.

**Comment by yunnysunny** [comment]
Could I host the code for freecodecamp on another site, such as [Bitbucket](https://bitbucket.org) or [gitlab](https://gitlab.com). I correct what I have said. I don't want to host my practice projects on github, I only want to use it to show my open source projects.

**Comment by raisedadead** [comment]
Oh surely. Unless it's a solution for reviewing, you could host your code anywhere...!

**Comment by yunnysunny** [comment]
But you can not input the url of  project that not host on github. For example , after I submit a url from gitlab , https://gitlab.com/yunnysunny/time-parser, an error will show that : **You haven't supplied the necessary URLs for us to inspect your work.**

**Comment by raisedadead** [comment]
@yunnysunny 

Thanks. Let me confirm this need from others in the team. But please keep in mind that **whichever service you host your code for Free Code Camp's solution, your code has to be public for reviewing**. 

@QuincyLarson @Em-Ant 
The OP wants to host their challenge on services other than GitHub, to separate their contribution profile and the personal profile.

I think we should allow hosting on any service like GitLab or BitBucket, for allowing open acceptance.

But is this change worthwhile, considering we are moving to Gomix soon for the projects? Will there still be any requirement of campers submitting the VCS controlled repo URLs?

And finally the baseline remains the same that we need publicly accessible code for reviewing.

**Comment by genrbr** [comment]
> 

> 

> 

> 

> 

> __

**Comment by QuincyLarson** [comment]
@raisedadead @yunnysunny  Even after we move to GoMix, we still want campers to have the option of hosting their apps other places. The code just has to be publicly accessible. GitLab and BitBucket are fine.
