### ISSUE TITLE
JavaScript Help

### ISSUE THREAD

**Issue by c0d0er2** [FreeCodeCamp/FreeCodeCamp#12246]
Challenge [Understanding Case Sensitivity in Variables](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables#?solution=%0A%2F%2F%20Declarations%0Avar%20camelCase%20%3D%2010%3B%0Avar%20camelCase%20%3D%20%22A%20String%22%3B%0Avar%20camelCase%20%3D%209000%3B%0A%0A%2F%2F%20Assignments%0AcamelCase%20%3D%2010%3B%0AcamelCase%20%3D%20%22A%20String%22%3B%0AcamelCase%20%3D%209000%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Declarations
var camelCase = 10;
var camelCase = "A String";
var camelCase = 9000;

// Assignments
camelCase = 10;
camelCase = "A String";
camelCase = 9000;

```

**Comment by texas2010** [comment]
@c0d0er2 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
