### ISSUE TITLE
Ask about: Make Object Properties Private

### ISSUE THREAD

**Issue by hoanluannguyen** [FreeCodeCamp/FreeCodeCamp#12242]
Challenge [Make Object Properties Private](https://www.freecodecamp.com/challenges/make-object-properties-private#?solution=%0Avar%20Car%20%3D%20function()%20%7B%0A%20%20%2F%2F%20this%20is%20a%20private%20variable%0A%20%20var%20speed%20%3D%2010%3B%0A%0A%20%20%2F%2F%20these%20are%20public%20methods%0A%20%20this.accelerate%20%3D%20function(change)%20%7B%0A%20%20%20%20speed%20%2B%3D%20change%3B%0A%20%20%7D%3B%0A%0A%20%20this.decelerate%20%3D%20function()%20%7B%0A%20%20%20%20speed%20-%3D%205%3B%0A%20%20%7D%3B%0A%0A%20%20this.getSpeed%20%3D%20function()%20%7B%0A%20%20%20%20return%20speed%3B%0A%20%20%7D%3B%0A%7D%3B%0A%0Avar%20Bike%20%3D%20function()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%20var%20gear%20%3D%202%3B%0A%20%20%20this.setGear%20%3D%20function()%20%7B%0A%20%20%20%20gear%20%2B%3D%204%3B%0A%20%20%7D%3B%0A%0A%20%20this.setGear%20%3D%20function()%20%7B%0A%20%20%0A%20%20%7D%3B%0A%20%0A%7D%3B%0A%0Avar%20myCar%20%3D%20new%20Car()%3B%0A%0Avar%20myBike%20%3D%20new%20Bike()%3B%20%0A%20%20%0A%0A%0A%20%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // Only change code below this line.
   var gear = 2;
   this.setGear = function() {
    gear += 4;
  };

  this.setGear = function() {
  
  };
 
};

var myCar = new Car();

var myBike = new Bike(); 
  


 

```

**Comment by hoanluannguyen** [comment]
Can you please help me out with it, I totally no glue with the instruction talking about

**Comment by Dayfiri** [comment]
Hey @hoanluannguyen, 
This forum is only for submitting bugs. For problems with solving the assignments you can find find help [here](https://gitter.im/FreeCodeCamp/Help). There is enough people every day to give you a hand in your learning journey. 
Wish you all the best in future learning and happy coding ;)

**Comment by erictleung** [comment]
@hoanluannguyen Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
