### ISSUE TITLE
Wrong h2 elements

### ISSUE THREAD

**Issue by santhu342** [FreeCodeCamp/FreeCodeCamp#12240]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by erictleung** [comment]
@santhu342 thanks for the issue, but can you be more specific on what your issue is? Please fill out the missing information in the issue template, such as challenge name and what your code is. This will help us help you. Thanks!

**Comment by raisedadead** [comment]
Please comment with the requirement stated above, and we can re-open.
