### ISSUE TITLE
Still linking to Slack

### ISSUE THREAD

**Issue by LimeBlast** [FreeCodeCamp/freecodecamp#1224]
Challenge http://www.freecodecamp.com/challenges/waypoint-pair-program-on-bonfires has an issue.

Step 6 is linking to a Slack chat room, rather than the gitter one.

**Comment by benmcmahon100** [comment]
This has already been fixed and awaiting deployment within the week.

**Comment by LumenTeun** [comment]
I'm not sure what the official stance is on this, but I like to include a link to the relevant commit or PR when referencing a fix, so for logging purposes, this was fixed in 7004e81b4a29b196a659bcb5cdcef30253b71d6f

**Comment by BerkeleyTrue** [comment]
The fix for this should be coming out soon. Fingers crossed if everything goes well it will be out by tomorrow.
