### ISSUE TITLE
When Submitting the variable var c="I am  "; it wont continue.  

### ISSUE THREAD

**Issue by BacksSlash092** [FreeCodeCamp/FreeCodeCamp#12248]
Challenge [Understanding Uninitialized Variables](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables#?solution=%0A%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%3D5%3B%0Avar%20b%3D10%3B%0Avar%20c%3D%22I%20am%20%20%22%3B%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Initialize these three variables
var a=5;
var b=10;
var c="I am  ";

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";


```

**Comment by texas2010** [comment]
@BacksSlash092 
Thanks for reporting this. But your code is incorrect. 
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by pkeesey** [comment]
I would just say that the chat room is hard to use when looking for a solution. even when I';m able to find the issue I'm looking for I'm not able to click into it
