### ISSUE TITLE
Concat Issue

### ISSUE THREAD

**Issue by snehashisc** [FreeCodeCamp/FreeCodeCamp#12259]
Challenge [Concatenating Strings with Plus Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20'This%20is%20the%20start.'%20%2B%20'This%20is%20the%20end.'%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr = 'This is the start.' + 'This is the end.';



```

**Comment by snehashisc** [comment]
Looks like there is a bug. Even after displaying the right value it doesn't show the task to be completed.

**Comment by dhcodes** [comment]
@snehashisc You have a small error in your code. Please consider asking for help in the chat room by clicking the Help button on the challenge. Also, reading the Note on the challenge may help.
