### ISSUE TITLE
Bonfire drop it -- unclear specification

### ISSUE THREAD

**Issue by rozisaacson** [FreeCodeCamp/FreeCodeCamp#1225]
Challenge http://www.freecodecamp.com/challenges/bonfire-drop-it has an issue. 

It's unclear from the wording whether you're supposed to drop, then immediately stop,  in which case

the output of drop([1, 2, 3, 4, 1, 2], function(n) {return n >= 3; }) 

would be [3, 4, 1, 2]

or do you mean drop all that don't meet the criteria which would return [3, 4].

**Comment by rcw271828** [comment]
> Drop the elements of an array (first argument), starting from the front, until the predicate (second argument) returns true.

The bonfire is asking you to return the array after the first true condition is met (if there is a match). It is not asking you to remove all elements that do not match. I hope this helps! :)

**Comment by rozisaacson** [comment]
None of the test cases actually test for that. A simple arr.filter(func) will pass all test cases. arr.filter(func) removes ALL elements that do not match so the test cases do not test for an array after the first true condition is met. I hope that make sense. I give an example above.

**Comment by benmcmahon100** [comment]
When you run the code of a bonfire it errors what that bonfire excepts. In this case the it requires that all the values that meet the test provided should be returned ([3, 4])(https://github.com/FreeCodeCamp/freecodecamp/blob/master/seed_data/challenges/basic-bonfires.json#L1311)
Please check these kinds of problems in http://gitter.im/freecodecamp/help before posting issues here. As for the wording if you have any suggestions please do not hesitate to put them here and I will submit a pull request fixing the issue! :blush:

**Comment by rozisaacson** [comment]
I think I'm just not making myself clear since I agree with what you're
saying

My understanding is that if you pass  [1,2,3,4,1,2,3,4]  with a function(x)
{
return x >=3; } you should get [3,4,1,2,3,4] returned.  Right now you can
pass the bonfire by doing a simple arr.filter that returns [3,4,3,4] which
does meet the specification of the bonfire. So you may mean drop then stop,
but the tests don't actually test if you are indeed stopping after the
first returned true.

I didn't have any problems "passing" the bonfire, but I thought the
intention was to meet the criteria. In the future, I will check the gitter
link as you suggested..

Thanks.

**Comment by benschenker** [comment]
Closing as stale.

**Comment by amigo9876** [comment]
function dropElements(arr, func) {
  var val = arr.findIndex(func);
  var newarr = [];
  if(val >= 0) {newarr = arr.slice(val, arr.length);}
  else {}
  return newarr;
  
  // Drop them elements.
}

dropElements([1, 2, 3, 4], function(n) {return n >= 3;});
