### ISSUE TITLE
Title Case a Sentence 

### ISSUE THREAD

**Issue by chiksl** [FreeCodeCamp/FreeCodeCamp#12257]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Afunction%20titleCase(str)%20%7B%0A%20%20var%20strArr%3D%5B%5D%3B%0A%20%20var%20newStr%3D%22%22%3B%0A%20%20strArr%3Dstr.split('%20')%3B%0A%20%20for(var%20i%3D0%3Bi%3CstrArr.length%3Bi%2B%2B)%7B%0A%20%20%20%20newStr%20%2B%3D%20strArr%5Bi%5D%5B0%5D.toUpperCase()%20%2B%20strArr%5Bi%5D.slice(1%2CstrArr%5Bi%5D.length).toLowerCase()%20%2B%20%22%20%22%3B%0A%20%20%7D%0A%20%20return%20newStr%3B%0A%7D%0A%0AtitleCase(%22I'm%20a%20little%20tea%20pot%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function titleCase(str) {
  var strArr=[];
  var newStr="";
  strArr=str.split(' ');
  for(var i=0;i<strArr.length;i++){
    newStr = newStr + strArr[i][0].toUpperCase() + strArr[i].slice(1,strArr[i].length).toLowerCase() + " ";
  }
  return newStr;
}

titleCase("I'm a little tea pot");

```
Hi. I've tested it by using http://www.w3schools.com/js/tryit.asp?filename=tryjs_output_dom
Here is my HTML code:
```
<!DOCTYPE html>
<html>
<body>
<p id="test1"></p>
<p id="test2"></p>
<p id="test3"></p>

<script>
function titleCase(str) {
  var strArr=[];
  var newStr="";
  strArr=str.split(' ');
  for(var i=0;i<strArr.length;i++){
    newStr = newStr + strArr[i][0].toUpperCase() + strArr[i].slice(1,strArr[i].length).toLowerCase() + " ";
  }
  return newStr;
}

document.getElementById("test1").innerHTML = titleCase("I'm a little tea pot");
document.getElementById("test2").innerHTML = titleCase("sHoRt AnD sToUt");
document.getElementById("test3").innerHTML = titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");
</script>

</body>
</html> 
```
Here is the output:
```
I'm A Little Tea Pot

Short And Stout

Here Is My Handle Here Is My Spout
```
But I can't run the test successfully.

**Comment by Marmiz** [comment]
That's because you are adding a space ( ` + "  "`) even at the end of the string.
In fact I have tested your code here: [repl.it](https://repl.it/Exzr/0)
And you see the output to be:
`'I\'m A Little Tea Pot '`

While the program expect: ``'I\'m A Little Tea Pot'` (no space at the end).
I know it's tiny but it's a difference :)

**Comment by chiksl** [comment]
Thank you!

**Comment by chiksl** [comment]
,,,
function titleCase(str) {
  var strArr=[];
  var newStr="";
  strArr=str.split(' ');
  for(var i=0;i<strArr.length;i++){
    newStr += strArr[i][0].toUpperCase() + strArr[i].slice(1,strArr[i].length).toLowerCase() + " ";
  }
  return newStr.slice(0,newStr.length-1);
}
,,,
Solved!

**Comment by raisedadead** [comment]
@Marmiz 
Thanks a lot for helping out, we sincerely request you to redirect help issues to chat and provide guidance there, any code guidance on the tracker is discouraged.
