### ISSUE TITLE
Escape Sequences in Strings

### ISSUE THREAD

**Issue by Arzani07** [FreeCodeCamp/FreeCodeCamp#12261]
the code doesn't work 

#### Escape Sequences in Strings

https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D%22FirsLine%20%5Cn%20%5C%5CSecondLine%5C%5C%20%5Cr%20ThirdLine%22%3B%20%0A%0A%0A

#### Your Code

```js
var myStr="FirsLine \n \\SecondLine\\ \r ThirdLine"; 
 
 
 #

**Comment by raisedadead** [comment]
Hi @Arzani07 

Thanks for the report.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
