### ISSUE TITLE
b= 9+ b;  is bugged when changed to 9+=b; 

### ISSUE THREAD

**Issue by CodeHawks** [FreeCodeCamp/FreeCodeCamp#12262]
Challenge [Compound Assignment With Augmented Addition](https://www.freecodecamp.com/challenges/compound-assignment-with-augmented-addition#?solution=%0Avar%20a%20%3D%203%3B%0Avar%20b%20%3D%2017%3B%0Avar%20c%20%3D%2012%3B%0A%0A%2F%2F%20Only%20modify%20code%20below%20this%20line%0A%0A%20a%20%2B%3D%2012%3B%0A%209%20%2B%3D%20b%3B%0Ac%20%2B%3D%207%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var a = 3;
var b = 17;
var c = 12;

// Only modify code below this line

 a += 12;
 9 += b;
c += 7;


```

**Comment by raisedadead** [comment]
Hi @CodeHawks 

Thanks for the report. Your code is incorrect.

The issue tracker is for reporting bugs only. Please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
