### ISSUE TITLE
Says propers Escape Sequences, I am not sure what's wrong with it. 

### ISSUE THREAD

**Issue by KamalHunzai** [FreeCodeCamp/FreeCodeCamp#12265]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D'%5C%5Chello%20%5Cn%20Hello%20I%20am%20going%20do%20it%20%5Cr%20What%20is%20going%20on%20%5C%5C'%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr ='\\hello \n Hello I am going do it \r What is going on \\'; // Change this line



```

**Comment by texas2010** [comment]
@KamalHunzai 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
