### ISSUE TITLE
im stop in this test 15 :(

### ISSUE THREAD

**Issue by abdelrahmansobhy** [FreeCodeCamp/FreeCodeCamp#12269]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%0A%3Cstyle%3E%0A%3Ccss%3E%0A%20%20%3Ch2%20style%3D%7Bcolor%3A%20blue%3B%7D%3ECatPhotoApp%3C%2Fh2%20style%3D%7Bcolor%3A%20blue%7D%3E%0A%3C%2Fcss%3E%0A%20%20%3C%2Fstyle%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
<css>
  <h2 style={color: blue;}>CatPhotoApp</h2 style={color: blue}>
</css>
  </style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by AkiraLaine** [comment]
Hey! If you need help, please go to our [main](https://gitter.im/FreeCodeCamp/FreeCodeCamp) room or [help](https://gitter.im/FreeCodeCamp/Help) room. GitHub is for issues only. Happy Coding :smile:

**Comment by deaninous** [comment]
He might be trying to address a twofold problem here :)
There does seem to be an issue with the tests.
