### ISSUE TITLE
Falsy Bouncer has JSON.stringify() incorrectly change NaN to null

### ISSUE THREAD

**Issue by widal001** [FreeCodeCamp/FreeCodeCamp#12271]
Challenge [Falsy Bouncer](https://www.freecodecamp.com/challenges/falsy-bouncer#?solution=function%20bouncer(arr)%20%7B%0A%0A%20%20function%20notFalse(item)%20%7B%0A%20%20%20%20if(item%20%3D%3D%3D%20false)%20%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D%20else%20if%20(item%20%3D%3D%3D%20%22%22)%20%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D%20else%20if%20(item%20%3D%3D%3D%20null)%20%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D%20else%20if%20(item%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D%20else%20if%20(item%20%3D%3D%3D%20undefined)%20%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D%20else%20if%20(item%20%3D%3D%3D%20%22NaN%22)%20%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20return%20true%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20var%20newArr%20%3D%20arr.filter(notFalse)%3B%0A%20%20return%20newArr%3B%0A%7D%0A%0Abouncer(%5B8%2C%20null%2C%200%2C%20NaN%2C%20undefined%2C%20%22%22%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function bouncer(arr) {

  function notFalse(item) {
    if(item === false) {
      return false;
    } else if (item === "") {
      return false;
    } else if (item === null) {
      return false;
    } else if (item === 0) {
      return false;
    } else if (item === undefined) {
      return false;
    } else if (item === "NaN") {
      return false;
    } else {
      return true;
    }
  }

  var newArr = arr.filter(notFalse);
  return newArr;
}

bouncer([8, null, 0, NaN, undefined, ""]);

```
While I eventually found a simpler solution to this challenge, when I used the above code the filter wasn't catching null, i.e. it was returning [8, null]. I even changed it to return newArr[1] === null to make sure it wasn't just a problem with the notFalse function. When I copied the same script into atom and ran it, it returned the expected newArr, i.e. [8]. If I'm just missing something, please let me know!

**Comment by erictleung** [comment]
@widal001 thanks for the issue. Your issue isn't actually that it can't handle `null`, your code can't handle `NaN`. 

```js
bouncer([8, null, 0, NaN, NaN, undefined, ""]);
// Returns [8, NaN, NaN]
```

cc/ @FreeCodeCamp/moderators what's weird, though, is that the page renders the `NaN` as `null`. Any ideas why this is? I'm sure it is some edge case or some initial code parsing I'm unfamiliar with.

**Comment by systimotic** [comment]
Good catch @erictleung!
The `NaN` is displayed as `null` because the output is put through `JSON.stringify()`. JSON does not have `NaN` or `undefined` types, so they are converted to `null`.

I think showing the correct type in the output is important in this challenge. It could be fixed with a custom tail that converts the returned array into a string, adding quotes to the strings inside.
Would you agree with that as a fix for this issue?

---
Unrelated to what Eric asked:
The reason the `NaN` comparison in the code shared in this issue did not work is because `NaN` is weird, and is not equal to itself:
```js
NaN === NaN // false
```

**Comment by erictleung** [comment]
@systimotic ah thanks! I missed the `.stringify()` part. I agree that the type should be correct. I think that should work, adding some code to modify the returned object just right should work.

Side note: man, JS is weird 😆

**Comment by systimotic** [comment]
JS is weird, but I secretly love the weird things. 😄
To add to the weirdness of Not a Number (`NaN`):
```js
typeof NaN; // "number"
```

I'm working on a PR to improve the logging output in general.

**Comment by widal001** [comment]
You guys have been the best! Thanks for triaging this and for inadvertently cluing me into some pretty cool quirks of JS along the way!

**Comment by Manish-Giri** [comment]
These lines from the YDKJS series sums up the "weirdness" quite accurately - 

> typeof null is an interesting case, because it errantly returns "object", when you'd expect it to return "null".

> Warning: This is a long-standing bug in JS, but one that is likely never going to be fixed. Too much code on the Web relies on the bug and thus fixing it would cause a lot more bugs!
