### ISSUE TITLE
Real time display of how many campers are using Free Code Camp

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#12275]
We can hit Google Analytics realtime and show how many campers are using Free Code Camp at a given time. The plan is to replace the landing page with a simple call to action at the top of the page when a camper isn't logged in. My current copy is:

"Sign up to save your progress and hang out with the 502 campers who are coding here right now."

The number would change ever second based on the Google Analytics realtime user count.

**Comment by smileytechguy** [comment]
I like this!! Great idea!
