### ISSUE TITLE
Class won't change text color.

### ISSUE THREAD

**Issue by smiley5396** [FreeCodeCamp/FreeCodeCamp#12279]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%C2%A0%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 7.0; Nexus 5X Build/N5D91L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by smiley5396** [comment]
[](u
![screenshot_20161230-101410](https://cloud.githubusercontent.com/assets/24832980/21567409/f2bed89a-ce79-11e6-8cd6-686032921100.png)

**Comment by ajain17** [comment]
I just copy pasted your code and it works fine for me. 


The issue tracker is for reporting bugs only. Please use the help [chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](https://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.

This issue can be closed.

**Comment by dhcodes** [comment]
@smiley5396 this likely has to do with being on a mobile device. It's an issue with the non-breaking spaces generated by Chrome on Android. Remove the spacing and it will pass. See here: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7753

Closing as duplicate. Issue will be fixed on next site update.
