### ISSUE TITLE
GitHub sign-in is not working on staging and beta

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#12276]

**Comment by BerkeleyTrue** [comment]
This is working fine on both ends for me. Can someone else confirm?

**Comment by raisedadead** [comment]
Yup, it works fine for both ends for me too. When I initially saw the issue, I got confused as well. 
@QuincyLarson Can you specify some details, of the exact issue you might be facing?

**Comment by BerkeleyTrue** [comment]
@QuincyLarson I'll hit you up on skype to help you resolve the issue.
