### ISSUE TITLE
Projects progressing but not updating in Phone View

### ISSUE THREAD

**Issue by artabstraction** [FreeCodeCamp/FreeCodeCamp#12281]
#### Challenge Name

This has happened for projects 9-12+ of the Responsive Design with Bootstrap section. I'm assuming it will continue as it's been.

#### Issue Description

I've been completing the Bootstrap projects with no problems, but the code does not update in the phone view. I'm progressing, and the code is correct, but it's not showing the changes I'm making in the simulated phone view. I've not tried to replicate in another browser, but it persists in this browser despite logging out and back in, refreshing, or going back to previous projects to attempt to redo them.

As you can see below, the project I'm on should have the first img in a row with the h2. But it's not. 

#### Browser Information

* Browser Name, Version: Chrome 54.0.2840.71 m
* Operating System: Win 7 Pro
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
 
 
```
#### Screenshot

![capture](https://cloud.githubusercontent.com/assets/24725250/21570732/89689e8e-ce8e-11e6-9409-4562d59889fb.PNG)

**Comment by raisedadead** [comment]
Hi @artabstraction! Apologies for the issue that you are experiencing.
Can you try and post the logs, from the Dev tools (Press <kbd>F12</kbd> --> Console Tab) for your browser? If there are any errors in red you could post them here for us to look into.

**Comment by artabstraction** [comment]
There were a few errors, but unfortunately I'm on another computer now and
can't seem to replicate the problem here. It's showing perfectly well on my
home desktop, but seems to be displaying oddly on Chrome on my work
desktop. I can post the logs on Tuesday, but unfortunately my office is
closed for New Years and won't be open till then. Is that a problem?

Thank you for all your help!
Sincerely,
Alexis Richard

On Fri, Dec 30, 2016 at 4:56 PM, mrugesh mohapatra <notifications@github.com

**Comment by raisedadead** [comment]
Oh! not a problem at all, I'll block this issue, and we can continue once again. BTW, I think as you mention it's at your workplace/office, there could be some firewall restrictions that may be a factor to your issue. 

Logs will definitely help. 

Let us know in the comments below.

**Comment by raisedadead** [comment]
@artabstraction closing this for now. please report back and we can re-open. happy coding!

**Comment by systimotic** [comment]
Hi @artabstraction! Did you get a chance to look a the logs? Don't worry, there's no hurry, just making sure you didn't forget about it 🙂

**Comment by artabstraction** [comment]
Hello!

I did today actually, and the problem is no longer happening on that
computer! But it turns out IT had a look at our systems over the weekend,
so they may have updated the browser without telling us. So the issue is no
longer an issue I suppose. I wonder what caused other people's computers to
do that.
Thank you for all of your help either way! I'm sorry it ended so
anticlimactically.

--Alexis

**Comment by systimotic** [comment]
I'm glad it works now! If you do get the problem again, feel free to reopen with the logs!

**Comment by artabstraction** [comment]
Thank you very much, I certainly shall!!
