### ISSUE TITLE
Challenge Complete But The Loading Keeps On Going...

### ISSUE THREAD

**Issue by xerokiryuu** [FreeCodeCamp/FreeCodeCamp#12283]
#### Challenge Name
'Create a Set of Checkboxes'

#### Issue Description
I completed the challenge and It (the browser) gave a compliment as it (the browser) always does and I clicked on "Submit and go to my next challenge" button, but the problem that I'm facing is that, the loading keeps going on and on, I've waited for a significant amount of time just to rule out the "slow connection" thing. I've also tried skipping the "above given" challenge and the next one does the same thing. Hope to get an answer ASAP. 
Thanks.

#### Browser Information
* Browser Name, Version: Google Chrome Version 55.0.2883.87 (64-bit)
* Operating System: Kali Linux 2016.2 (4.8.0-kali2-amd64)
* Mobile, Desktop, or Tablet: Dell Workstation T5400 (Desktop)

#### Your Code
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <label><input type="radio" name="indoor-outdoor"> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label> <br />
  <label><input type="checkbox" name="personality">Cute</label>
  <label><input type="checkbox" name="personality">Sturdy</label>
  <label><input type="checkbox" name="personality">Handsome</label>
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>



```
 
 
#### Screenshot
![screenshot](https://cloud.githubusercontent.com/assets/24625528/21571113/c8df28da-ceed-11e6-8c11-b6d25b711e9b.png)

**Comment by raisedadead** [comment]
This is most probably related to your browser extensions, can you test by opening the challenge in a new incognito window with all the add-ons disabled, in the recent past we have seen LastPass and Adblock-plus might be the conflicting ones mostly.

If it works in the incognito mode, then you could start by disabling your add-ons one by one, to confirm the one causing trouble.

**Comment by raisedadead** [comment]
Closing this for now. Please report back after you get a chance to re-visit the issue with the troubleshooting mentioned above, happy coding!

**Comment by justxqz** [comment]
Thanks! Disabled Adblocker and it works fine!
