### ISSUE TITLE
Expand dropdown on hover

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#12290]
The navbar dropdown should expand on hover. Here is the updated links JSON: https://gist.github.com/QuincyLarson/e5739f334bc72daf7cf77005099c2156

**Comment by BerkeleyTrue** [comment]
Why are you including a gist of the links?

**Comment by QuincyLarson** [comment]
@BerkeleyTrue I thought you mentioned you could add these when you went in and created the PR. I can do this myself, though.

**Comment by BerkeleyTrue** [comment]
I thought you mentioned that you where going to add these :)

In any case, that should be two issues. Adding links to a json list can be an FTO or a "help wanted" tag.
