### ISSUE TITLE
Finders Keepers: Passed the tests but I think either the tests were wrong or the rules set

### ISSUE THREAD

**Issue by entrptaher** [FreeCodeCamp/FreeCodeCamp#12294]
#### Challenge Name

https://www.freecodecamp.com/challenges/finders-keepers#?solution=%0Afunction%20findElement(arr%2C%20func)%20%7B%0A%20%20return%20arr.filter(func)%5B0%5D%3B%0A%7D%0A%0AfindElement(%5B1%2C%202%2C%203%2C%204%5D%2C%20function(num)%7B%20return%20num%20%25%202%20%3D%3D%3D%200%3B%20%7D)%3B

#### Issue Description

The rules says, 
`findElement([1, 3, 5, 8, 9, 10], function(num) { return num % 2 === 0; }) should return 8.`
But my tests passed when I just returned some random things. It returned *2 instead of 8*, but the test passed.

*Either the rules specified are wrong or the tests are wrong.*

#### Browser Information

* Browser Name, Version: Chrome 54.0.2840.99 m
* Operating System:  Windows 7 64bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
function findElement(arr, func) {
  return arr.filter(func)[0];
}
```

#### Screenshot

![](http://i.imgur.com/9Mc6Jcx.png)

**Comment by dhcodes** [comment]
@entrptaher the tests use your function with against the preset criteria. Therefore, while you may have modified the test in the console, the tests on the challenge are still using the same function which yields the correct results with the preset array.
