### ISSUE TITLE
Bonfire Roman Numeral Converter issue

### ISSUE THREAD

**Issue by CandiW** [FreeCodeCamp/freecodecamp#1229]
Hi - I passed the challenge with this code below, but without using any of the suggested methods (such as arr.indexOf(), arr.splice(), and arr.join())....not sure if it's a bug or a misunderstanding on my part of how to use these methods.  Seems to be that no matter what I tried to use these methods, I couldn't get my code to work.  Any ideas?  Thanks in advance for your help.

```
function convert(num) {
  var roman = ['M','D','C','L','X','IX','V','I'];
  var decimal = [1000,500,100,50,10,9,5,1];
  var romanNumeral = '';
  
  for(var i = 0; i < roman.length; i++){
    while(num >= decimal[i]){
      num -= decimal[i];
      romanNumeral += roman[i];
    }
  }
 return romanNumeral;
}

convert(36);
```

**Comment by CandiW** [comment]
Tried again today to see if I could figure out the code....noticed that especially on .indexOf(), the error consistently says '.indexOf().... is not a function', even though I'm not putting it in a function!

**Comment by LumenTeun** [comment]
The GitHub issues are not for support, please close this and refer to the [RSAP field guide](http://www.freecodecamp.com/field-guide/how-do-i-get-help-when-i-get-stuck) for help.
