### ISSUE TITLE
Instructions above and below RUN button mis-matching, challenge passing with above one

### ISSUE THREAD

**Issue by havefuncoding** [FreeCodeCamp/FreeCodeCamp#12299]
**Challenge**: https://www.freecodecamp.com/challenges/understanding-uninitialized-variables
**Client**: Chrom 55.0.2883.95 (64-bit)
**Type**: Data Issue

**Actual**:  Instructions below the "Run..." button is -

1. a should be defined and have a value of **6**
2. b should be defined and have a value of **15**
3. c should not contain undefined and should have a value of **"I am a String!"**
4. Do not change code below the line

**Expected**: Instructions below the "Run..." button should be -

1. a should be defined and have a value of **5**
2. b should be defined and have a value of **10**
3. c should not contain undefined and should have a value of **"I am a"**
4. Do not change code below the line

**Pre-populated**: 
```
Challenge [Understanding Uninitialized Variables](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables#?solution=%0A%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%20%3D%205%3B%0Avar%20b%20%3D%2010%3B%0Avar%20c%20%3D%20%22I%20am%20a%22%3B%0A%0A%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Initialize these three variables
var a = 5;
var b = 10;
var c = "I am a";

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";
```

**Screenshot**:

<img width="849" alt="screen shot 2016-12-31 at 1 09 47 pm" src="https://cloud.githubusercontent.com/assets/10410748/21579252/71216c12-cf5a-11e6-8279-299867153a2f.png">

**Comment by dhcodes** [comment]
@havefuncoding I see what you mean, but the tests do ensure that the assignments of a, b, and c are correct. Opening for discussion. cc @FreeCodeCamp/moderators

**Comment by havefuncoding** [comment]
@dhcodes I see what you mean, I had glossed over the lines 9-13. It makes sense now, closing, thank you
