### ISSUE TITLE
Challenge Caesars Cipher has an issue.

### ISSUE THREAD

**Issue by john-d-pelingo** [FreeCodeCamp/FreeCodeCamp#12296]
Challenge [Caesars Cipher](https://www.freecodecamp.com/challenges/caesars-cipher#?solution=%0Afunction%20rot13(str)%20%7B%20%2F%2F%20LBH%20QVQ%20VG!%0A%20%20return%20str%0A%20%20%20%20.split('')%0A%20%20%20%20.map(letter%20%3D%3E%20%7B%0A%20%20%20%20%20%20var%20letterCharCode%20%3D%20letter.charCodeAt(0)%3B%0A%20%20%20%20%0A%20%20%20%20%20%20if%20(!(letterCharCode%20%3E%3D%2065%20%26%26%20letterCharCode%20%3C%3D%2090))%20return%20String.fromCharCode(letterCharCode)%3B%0A%20%20%20%20%0A%20%20%20%20%20%20var%20res%20%3D%20String.fromCharCode(%0A%20%20%20%20%20%20%20%20(letterCharCode%20-%2065%20-%2013)%20%25%2026%20%2B%2065%0A%20%20%20%20%20%20)%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20console.log(letterCharCode%2C%20(letterCharCode%20-%2065%20-%2013)%20%25%2026%20%2B%2065%2C%20res)%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20return%20res%3B%0A%20%20%20%20%7D)%0A%20%20%20%20.join('')%3B%0A%7D%0A%0Aconsole.clear()%3B%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%0Arot13(%22SERR%20PBQR%20PNZC%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.

### Description
For some reason the runtime environment of the site translates `(letterCharCode - 65 - 13) % 26 + 65` into `letterCharCode - 65 - 13 % 26 + 65` rendering the loop formula useless. 

My code:
```javascript

function rot13(str) { // LBH QVQ VG!
  return str
    .split('')
    .map(letter => {
      var letterCharCode = letter.charCodeAt(0);
    
      if (!(letterCharCode >= 65 && letterCharCode <= 90)) return String.fromCharCode(letterCharCode);
    
      var res = String.fromCharCode(
        (letterCharCode - 65 - 13) % 26 + 65
      );
      
      console.log(letterCharCode, (letterCharCode - 65 - 13) % 26 + 65, res);
      
      return res;
    })
    .join('');
}

console.clear();
// Change the inputs below to test
rot13("SERR PBQR PNZC");

```

My screenshot of the runtime: 
<img width="1667" alt="screen shot 2016-12-31 at 20 49 17" src="https://cloud.githubusercontent.com/assets/9418096/21578877/b4f4262e-cf9a-11e6-8c06-7de46f6cc8db.png">

**Comment by dhcodes** [comment]
@john-d-pelingo I believe this is a coding error. Some letters may need to be shifted 13 places one way, while others may need to be shifted 13 places the other way. Closing for now as I was able to get your code to work with a small change.

**Comment by romeepraj** [comment]
I solved this problem with different approach just want to know you guys(@dhcodes, @john-d-pelingo ) views on it.

function rot13(str) { // LBH QVQ VG!
  var oldArray = str.split("");
  var newArray = oldArray.map(function(val){
    var charCode = val.charCodeAt(0);
    if(charCode<65){
       charCode = String.fromCharCode(charCode);
    }
    else if(charCode>=65 && charCode<=90){
         charCode+=13;
        if(charCode >90){
          var a = charCode -90;
         charCode = String.fromCharCode(64 + a);
        }
        else
        {
            charCode = String.fromCharCode(charCode);
        }
    }else if(charCode>90){
       charCode = String.fromCharCode(charCode);
    }
    return charCode;
   
  
  });
  return newArray.join("");
}

// Change the inputs below to test
rot13("SERR YBIR?");
