### ISSUE TITLE
Tribute page issue

### ISSUE THREAD

**Issue by Kremr** [FreeCodeCamp/FreeCodeCamp#12293]
Challenge [Build a Tribute Page](https://www.freecodecamp.com/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The tribute page has an issue, in the caption stands "Dr. Norman Borlaug, second from left,", but he is the third one on the picture. :)

**Comment by raisedadead** [comment]
Thanks @Kremr fixed, good catch!
