### ISSUE TITLE
Grammatical

### ISSUE THREAD

**Issue by greenfreq** [freeCodeCamp/freeCodeCamp#12300]
This is not really a bug, but I don't know where else to point it out.

The motorBike checklist should read "an engines attribute"  not "a engines attribute"

Challenge [Declare JavaScript Objects as Variables](https://www.freecodecamp.com/challenges/declare-javascript-objects-as-variables#?solution=%0Avar%20car%20%3D%20%7B%0A%20%20%22wheels%22%3A4%2C%0A%20%20%22engines%22%3A1%2C%0A%20%20%22seats%22%3A5%0A%7D%3B%0A%0Avar%20motorBike%20%3D%20%7B%0A%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%22wheels%22%3A2%2C%0A%20%20%22engines%22%3A1%2C%0A%20%20%22seats%22%3A1%0A%7D%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var car = {
  "wheels":4,
  "engines":1,
  "seats":5
};

var motorBike = {


  // Only change code below this line.
  "wheels":2,
  "engines":1,
  "seats":1
};

```

**Comment by dhcodes** [comment]
While we're putting our grammatical hats on, I believe the line:
>Give your motorBike object a `wheels`, `engines` and `seats` attribute and set them to numbers.

should read:
>Give your motorBike object `wheels`, `engines`, and `seats` attributes and set each to a number.

**Comment by ryzokuken** [comment]
@dhcodes I would like to work on this. Could you point me to where the challenge messages are stored?

**Comment by dhcodes** [comment]
@ryzokuken

https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json

**Comment by bharg** [comment]
Is the fix done? Else, I'd like to take it up.

**Comment by RishuK** [comment]
Can I take this up please? A free-timer who has been trying to find an issue in this project.
