### ISSUE TITLE
Refactor for react-redux-form

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#12309]
Please refer to [this comment](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/12032#issuecomment-269728337)

`react-redux` have released a much improved module with greatly increase performance.

Unfortunately, we need to refactor all instances of `redux-form` into `react-redux-form` to be able to update `react-redux`

Please be sure to follow [CONTRIBUTING.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md)

Happy Coding!

**Comment by craigstroman** [comment]
Hi, 

I would be interested in taking this on.

**Comment by Bouncey** [comment]
:+1:

**Comment by Bouncey** [comment]
This is still up for grabs :tada:

**Comment by PortableStick** [comment]
I'm looking into this right now.

**Comment by PortableStick** [comment]
So, it seems like react-redux-form and react-bootstrap are mutually exclusive.  [react-redux-form](http://davidkpiano.github.io/react-redux-form/docs/api/Control.html) makes use of connected form components which would replace the Bootstrap components.  Am I reading this right?  I'm not sure how to proceed with this.

**Comment by Bouncey** [comment]
@PortableStick I've just had a quick look there and that's the idea I got from it.

If that is what's required then no problem, as long as we can carry the CSS over without too much pain

**Comment by PortableStick** [comment]
Sorry for the silence here, I had some person/professional stuff come up.  I've found that it's actually quite simple to keep the react-bootstrap components as react-redux-form takes a component prop.  

I've got much of the forms changed from redux-form to react-redux-form, and created a simple decorator function in `common/app/utils/form.js` (still a WIP) that creates the inputs in much the same way redux-form did.  Where I'm stalled right now is connecting the react-redux-form elements to the app's store.  Of course, it seems simple in [the docs](http://davidkpiano.github.io/react-redux-form/docs/guides/models.html), but FreeCodeCamp is _significantly_ larger than the example and I can't figure out at all where the models should go.  I think the rest will be easy, if anyone has any help for me here, but if it's easier to do it than to explain the codebase, I'd understand.

**Comment by nesterone** [comment]
Hi, @PortableStick 

Any progress in `react-redux-form` refactoring ?

**Comment by Bouncey** [comment]
@PortableStick 

Sorry, I'm only just seeing this now. So the store is created [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/7e8aad7505b13334b9decadbc4ea87e7f9ba7639/common/app/create-app.jsx#L72)

From my quick glance at those docs, the models look like initial state declarations to me, these can be held in `common/app/routes/settings/reducer.js`, take a look at other routes so see how we implement our reducers.
[Here](https://github.com/freeCodeCamp/freeCodeCamp/blob/549cfc305f75d8c6036a3cde65c47b518607b18c/common/app/create-reducer.js) is where we create our combined reducer.

I hope I'm not too late in helping you out, it sounds like you made plenty of progress.

**Comment by Ethan-Arrowood** [comment]
How is this going? I'd be down to clean this up tonight if no one is still working on it.

**Comment by Ethan-Arrowood** [comment]
Alright I'm going to take this on 😄

**Comment by Ethan-Arrowood** [comment]
Here are all the current instances of redux-form
<img width="517" alt="screen shot 2017-05-04 at 10 40 29 am" src="https://cloud.githubusercontent.com/assets/16144158/25709025/22f44c04-30b6-11e7-9798-63ef998dfb4d.png">

**Comment by Ethan-Arrowood** [comment]
I think I bit off more than I can chew. . . similar to what @PortableStick was saying above: refactoring this requires rebuilding the entire forms (and replacing the bootstrap ones with react-redux-form fields. Wish I could've been of more help but I'm not familiar enough with redux-form or react-redux-form to be able to solve this. Sorry!
