### ISSUE TITLE
Challenge - Friendly Date Ranges: Solution breaks build

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#12305]
The current solution for `Friendly Date Ranges` currently breaks the build.

A PR is needed to update the solution in the seed files to be more robust.

The code for the challenge can be found [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/4598f5b42141a1d72e3f727059302e6eefb50f72/seed/challenges/01-front-end-development-certification/advanced-bonfires.json#L383)

**Comment by Bouncey** [comment]
It also seems the tests and instructions are out-dated. This challenge currently needs a full refactor.

cc\ @FreeCodeCamp/moderators this challenge has the potential to cause a headache every year.

If there is an alternative in the Curriculum Expension, can this challenge be retired?

**Comment by BerkeleyTrue** [comment]
I vote for removal.

**Comment by QuincyLarson** [comment]
I second @BerkeleyTrue's recommendation of removal. I'm making a PR now.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue is there a way we can set this to "isBeta" to remove it for now until we can overhaul the challenge?  If we do, will CI still pass?

If there isn't a better way, could you just remove the challenge completely then push to production?
