### ISSUE TITLE
Bonfire: Symmetric Difference has a test case passing one array

### ISSUE THREAD

**Issue by Damon-Myers** [FreeCodeCamp/FreeCodeCamp#1230]
Challenge http://www.freecodecamp.com/challenges/bonfire-symmetric-difference has an issue. 

In the description of the bonfire, it states that the sym method will be passed two or more arrays and return the symmetric difference of the arrays; however, the final test case on the page passes it one array and expects valid output.

**Comment by SabbaKilam** [comment]
@Damon-Myers:
That single array argument (parameter) doesn't bother me as much as the fact that the middle two unit tests seem to expect the wrong array as a return value of sym function. Why is a 5 included in the supposed correct answer when ALL of the arrays passed as arguments contain 5 as an element?

**Comment by Damon-Myers** [comment]
@SabbaKilam 
Whenever all of the sets contain the same number, the resulting set will contain that number if there is an odd number of sets. I found [this](https://www.youtube.com/watch?v=PxffSUQRkG4) video helpful whenever I was working through this one. Hope that helps!

**Comment by SabbaKilam** [comment]
@Damon-Myers: Okay, this makes sense if the symmetric difference of the first two sets is found and the resulting set worked against each remaining set in turn.
Thanks again.

**Comment by terakilobyte** [comment]
Yes, this is the mathematical definition. Please remember to close this
issue.

**Comment by catapixel** [comment]
@terakilobyte The issue that @Damon-Myers replied to @SabbaKilam about was not the issue that opened this ticket. The ticket issue is that the instructions say to create a function that will take two or more arrays but the final test only submits a single array and thus appears to be a faulty test. It seems either the instructions should be changed to "one or more arrays" or the final test eliminated. Hope that helps to clarify the issue/question...

**Comment by Damon-Myers** [comment]
@catapixel Thank you, I had not received a notification for terakilobyte's comment.

**Comment by benschenker** [comment]
Closing as stale, please reopen if you still experience issues regarding this
