### ISSUE TITLE
Error in instructions on Use an ID Attribute to Style an Element challenge.

### ISSUE THREAD

**Issue by KLRmarkie** [FreeCodeCamp/FreeCodeCamp#12313]
I was working through the following instructions and noticed that the id attribute changed from "#cat-photo-element" to "cat-photo-form" later in the instructions.  I thought this might be an unnecessary stumbling block for someone else.

Here's an example of how you can take your element with the id attribute of **cat-photo-element** and give it the background color of green. In your style element:

    #**cat-photo-element** {
      background-color: green;
    }

Note that inside your style element, you always reference classes by putting a . in front of their names. You always reference ids by putting a # in front of their names.

Try giving your form, which now has the id attribute of **cat-photo-form**, a green background.

**Comment by MiloATH** [comment]
I believe this was done on purpose in order to eliminate people from copying the example code.

**Comment by erictleung** [comment]
@KLRmarkie thanks for the issue. What @MiloATH has mentioned is correct. The code in the challenge description is just example code. Learning to code will require you to read and follow directions and apply some critical thinking to complete the challenges. Thanks for the feedback, but I believe the instructions are sufficient. Happy coding!

**Comment by KLRmarkie** [comment]
To each their own.
