### ISSUE TITLE
[Solved] Add Placeholder Text to a Text Field

### ISSUE THREAD

**Issue by esaky** [FreeCodeCamp/FreeCodeCamp#12312]
Om Shakthi
Hi guys,
The error came for me too. I just tried and changed the cat url ".jpg"
Now the "The finished input element should have valid syntax." is good.

but the second one "add cat url" is showing error !
![freecodecamp](https://cloud.githubusercontent.com/assets/10112128/21584015/948ca6bc-d0bd-11e6-8810-45af3e523094.PNG)

if we added the default code: "<input type="text" placeholder="https://bit.ly/fcc-relaxing-cat">"

it shows the same error you guys mentioned !

**Comment by esaky** [comment]
The code is working now.
![freecodecamp1](https://cloud.githubusercontent.com/assets/10112128/21584059/41f53462-d0bf-11e6-87de-f6425ec2d3cb.PNG)

We thought to add the cat url in that placeholder, but then i added the text"cat photo url". and it shows good in all three.

am i right - or still it's a buggy.

Advise me !

**Comment by yuyubeanz** [comment]
i'm having this same issue, I"m putting the code, as it states and it still isn't moving onto the next challenge, this is so frustrating,

**Comment by akinolajohn** [comment]
Tried this too still isn't working
