### ISSUE TITLE
i really don't know what is wrong down there ? can someone help me ?

### ISSUE THREAD

**Issue by eXe201990** [FreeCodeCamp/FreeCodeCamp#12319]
Challenge [Replacing If Else Chains with Switch](https://www.freecodecamp.com/challenges/replacing-if-else-chains-with-switch#?solution=%0Afunction%20chainToSwitch(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20switch(val)%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%0A%20%20%20%20case(val%20%3D%3D%3D%20%22bob%22)%3A%20%0A%20%20%20%20answer%20%3D%20%22Marley%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20(val%20%3D%3D%3D%2042)%3A%0A%20%20%20%20%20%20%0A%20%20%20%20answer%20%3D%20%22The%20Answer%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20(val%20%3D%3D%3D%201)%3A%0A%20%20%20%20answer%20%3D%20%22There%20is%20no%20%231%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20case(val%20%3D%3D%3D%2099)%3A%20%0A%20%20%20%20answer%20%3D%20%22Missed%20me%20by%20this%20much!%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%0A%20%20%20case%20(val%20%3D%3D%3D%207)%3A%0A%20%20%20answer%20%3D%20%22Ate%20Nine%22%3B%0A%20%20%20%20%20break%3B%0A%20%20%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AchainToSwitch(7)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 OPR/42.0.2393.94</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function chainToSwitch(val) {
  var answer = "";
  // Only change code below this line
  
  switch(val){
      
    
    case(val === "bob"): 
    answer = "Marley";
      break;
    case (val === 42):
      
    answer = "The Answer";
      break;
    case (val === 1):
    answer = "There is no #1";
      break;
   case(val === 99): 
    answer = "Missed me by this much!";
      break;
      
   case (val === 7):
   answer = "Ate Nine";
     break;
  
  }
  // Only change code above this line  
  
}

// Change this value to test
chainToSwitch(7);


```

**Comment by Srivastava-Sandeep** [comment]
Hi @eXe201990 

This is not a bug.
Here is the correct code.

function chainToSwitch(val) {
  var answer = "";
  // Only change code below this line
  
  switch(val){
      
    
    case("bob"): 
    answer = "Marley";
      break;
    case (42):
      
    answer = "The Answer";
      break;
    case (1):
    answer = "There is no #1";
      break;
   case(99): 
    answer = "Missed me by this much!";
      break;
      
   case (7):
   answer = "Ate Nine";
     break;
      
    default:
      answer = "empty string";
  
  }
  // Only change code above this line  
  return answer;  
}

// Change this value to test
chainToSwitch(7);

**Comment by raisedadead** [comment]
Hi @eXe201990 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

@ceejayoz thanks for your comment, please redirect help issues to above and provide any coding assistance there.

Happy Coding!
