### ISSUE TITLE
code is not running in FCC but works with node in the commandline

### ISSUE THREAD

**Issue by ulf1** [FreeCodeCamp/FreeCodeCamp#12323]
## my comment
the code runs with node, e.g.
```
node test.js
```

in FCC it doesn't work. 
I'm using two while loops (outer and inner) what might be the cause.

## auto generated text
Challenge [Sorted Union](https://www.freecodecamp.com/challenges/sorted-union#?solution=%0Afunction%20mergeArrays(x)%20%7B%0A%20%20%2F%2F%20empty%20array%20as%20initial%20value.%20Combine%20two%20arrays%20several%20times.%0A%20%20return%20x.reduce(function(a%2Cb)%7Breturn%20a.concat(b)%3B%7D%2C%5B%5D)%3B%0A%7D%0A%0Afunction%20uniteUnique()%7B%0A%20%20%2F%2F%20convert%20JSON%20(the%20arguments%20variable)%20to%20an%20Array%0A%20%20var%20arr%20%3D%20%5B%5D.slice.call(arguments)%3B%20%2F%2Fconsole.log(arr)%3B%0A%20%20%2F%2F%20merge%20initially%0A%20%20arr%20%3D%20mergeArrays(arr)%3B%0A%20%20%2F%2F%20start%20outer%20while%20loop%0A%20%20var%20flag%20%3D%20true%3B%0A%20%20while(flag)%7B%0A%20%20%20%20%2F%2F%20check%20if%20one%20element%20is%20an%20array%0A%20%20%20%20var%20stopped%3Dfalse%3B%0A%20%20%20%20var%20i%3D0%3B%0A%20%20%20%20while(i%3Carr.length%20%26%26%20!stopped)%7B%0A%20%20%20%20%20%20%2F%2F%20stop%20if%20one%20element%20is%20an%20Array%0A%20%20%20%20%20%20if(Array.isArray(arr%5Bi%5D))%7Bstopped%3Dtrue%3B%7D%0A%20%20%20%20%20%20i%2B%2B%3B%0A%20%20%20%20%7D%0A%20%20%20%20if(stopped)%7B%0A%20%20%20%20%20%20%2F%2F%20merge%20elements%20that%20are%20numbers%2Fstrings%20and%20Arrays.%0A%20%20%20%20%20%20arr%20%3D%20mergeArrays(arr)%3B%0A%20%20%20%20%7Delse%7B%0A%20%20%20%20%20%20%2F%2F%20abort%20outer%20while%20loop%0A%20%20%20%20%20%20flag%20%3D%20false%3B%0A%20%20%20%20%7D%0A%20%20%20%20%2F%2Fconsole.log(arr)%3B%0A%20%20%7D%0A%20%20return%20arr%3B%0A%7D%0A%0A%0Aconsole.log(uniteUnique(%5B1%2C%203%2C%202%5D%2C%20%5B5%2C%202%2C%201%2C%204%5D%2C%20%5B2%2C%201%5D))%3B%0Aconsole.log(uniteUnique(%5B1%2C%203%2C%202%5D%2C%20%5B1%2C%20%5B5%5D%5D%2C%20%5B2%2C%20%5B4%5D%5D))%3B%0Aconsole.log(uniteUnique(%5B1%2C%202%2C%203%5D%2C%20%5B5%2C%202%2C%201%5D))%3B%0Aconsole.log(uniteUnique(%5B1%2C%202%2C%203%5D%2C%20%5B5%2C%202%2C%201%2C%204%5D%2C%20%5B2%2C%201%5D%2C%20%5B6%2C%207%2C%208%5D))%3B%0Aconsole.log(uniteUnique(%5B1%2C%203%2C%202%5D%2C%20%5B3%2C%20%5B1%2C%20%5B5%5D%5D%5D%2C%20%5B2%2C%20%5B4%5D%5D))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function mergeArrays(x) {
  // empty array as initial value. Combine two arrays several times.
  return x.reduce(function(a,b){return a.concat(b);},[]);
}

function uniteUnique(){
  // convert JSON (the arguments variable) to an Array
  var arr = [].slice.call(arguments); //console.log(arr);
  // merge initially
  arr = mergeArrays(arr);
  // start outer while loop
  var flag = true;
  while(flag){
    // check if one element is an array
    var stopped=false;
    var i=0;
    while(i<arr.length && !stopped){
      // stop if one element is an Array
      if(Array.isArray(arr[i])){stopped=true;}
      i++;
    }
    if(stopped){
      // merge elements that are numbers/strings and Arrays.
      arr = mergeArrays(arr);
    }else{
      // abort outer while loop
      flag = false;
    }
    //console.log(arr);
  }
  return arr;
}


console.log(uniteUnique([1, 3, 2], [5, 2, 1, 4], [2, 1]));
console.log(uniteUnique([1, 3, 2], [1, [5]], [2, [4]]));
console.log(uniteUnique([1, 2, 3], [5, 2, 1]));
console.log(uniteUnique([1, 2, 3], [5, 2, 1, 4], [2, 1], [6, 7, 8]));
console.log(uniteUnique([1, 3, 2], [3, [1, [5]]], [2, [4]]));

```

**Comment by ulf1** [comment]
i substituted the inner while loop with a filter function but it still not work in FCC. no problem to execute with node in the command line.


```

function mergeArrays(x) {
  // empty array as initial value. Combine two arrays several times.
  return x.reduce(function(a,b){return a.concat(b);},[]);
}

function hasArrayAsElement(x){
  return (x.filter(function(a){return Array.isArray(a);})).length>0;
}

function uniteUnique(){
  // convert JSON (the arguments variable) to an Array
  var arr = [].slice.call(arguments); //console.log(arr);
  // merge initially
  arr = mergeArrays(arr);
  // start outer while loop
  var flag = true;
  while(flag){
    //console.log(hasArrayAsElement(arr), arr);
    if(hasArrayAsElement(arr)){
      // merge elements that are numbers/strings and Arrays.
      arr = mergeArrays(arr);
    }else{
      // abort outer while loop
      flag = false;
    }
  }
  return arr;
}
```

**Comment by ulf1** [comment]
this is not working at FCC too. However it runs in node ...

```
function mergeArrays(x) {
  return x.reduce(function(a,b){return a.concat(b);},[]);
}
function uniteUnique(){
  //var arr = [].slice.call(arguments);
  var arr = Array.prototype.slice.call(arguments);
  arr = mergeArrays(arr);
  return mergeArrays(arr);
}
```

**Comment by ulf1** [comment]
nope ...
```
function uniteUnique(){
  var arr = Array.prototype.slice.call(arguments);
  arr = arr.reduce(function(a,b){return a.concat(b);},[]);
  return arr.reduce(function(a,b){return a.concat(b);},[]);
}
```

**Comment by systimotic** [comment]
Hi @ulf1!

This seems to run on FCC for me, it just doesn't give the right output. When I run this in Node, I get the same output as when I run it on the website. 
```js
console.log(uniteUnique([1, 3, 2], [5, 2, 1, 4], [2, 1])); // [ 1, 3, 2, 5, 2, 1, 4, 2, 1 ]
```
This is what I get in both, but the requested output is
```js
[1, 3, 2, 5, 4]
```
Can you share the output you get in Node?

The reason you're not seeing any output in the window on the website is because you have wrapped your function call in a console.log statement.

Remember that this challenge asks to remove duplicates. If you do this, and leave the numbers in the original order, the tests will pass.

I'd love to hear what you get as the output from Node.
Happy coding!

**Comment by ulf1** [comment]
Sorry. Delete the issue. I forgot to remove the duplicates, and it is not necessary to read arrays of arrays.

**Comment by ulf1** [comment]
Sorry. Delete the issue. I forgot to remove the duplicates, and it is not necessary to read arrays of arrays.
