### ISSUE TITLE
Passing Values to Functions with Arguments

### ISSUE THREAD

**Issue by krcurry** [FreeCodeCamp/FreeCodeCamp#12320]
functionWithArgs should be a function
functionWithArgs(1,2) should output 3
functionWithArgs(7,9) should output 16
Call functionWithArgs after you define it.

1It is accepting all my functions except 1 + 2 = 3, https://www.freecodecamp.com/challenges/passing-values-to-functions-with-arguments#?

 // Example
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.

function functionWithArgs(a, b) {
  console.log(1 + 2);
  
}

functionWithArgs(1, 2); // outputs 3

function functionWithArgs(c, d) {
  console.log(7 + 9);
}

functionWithArgs(7, 9); // outputs 16

I have asked for help but no one has offered to help me, I need to know how to fix this so I can move on 
 
```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by raisedadead** [comment]
Hi @krcurry 

Thanks for the report. The issue tracker is for reporting bugs only. 
I understand your frustration and are sincerely sorry for the same, but chat rooms do get busy at times, please be patient, and someone will surely help out.

You can also post on the forum.

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding!

**Comment by blackkingafrica** [comment]
@raisedadead 
I am also having the same issue and i think it is a bug because the error message given was  "TypeError: nativeLog is not a function". I did not declare any function called nativeLog, please look into this so that i can move forward with the tasks.

**Comment by raisedadead** [comment]
@blackkingafrica please raise a separate issue, with the screenshots of the error that you are getting.

**Comment by Axeex** [comment]
// Example
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.
function functionWithArgs (a, b) {
  console.log(a + b);
}
functionWithArgs(1,2);
functionWithArgs(7,9);

**Comment by OgunniyiOwamamwen** [comment]
// Example
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.

function functionWithArgs (c,d){
  console.log(c+d);
}
functionWithArgs(7,9);

**Comment by HassanAli321** [comment]
this is not work please help i am new student in java script help me

**Comment by HassanAli321** [comment]
erroe is again and again

**Comment by bridgetsarah** [comment]
Hello, I urge @raisedadead to double check this as there's a clear issue. Check my attached screenshots, I tested the code on another website, and sure enough, it worked... I changed the calculations exactly, even tried copying and pasting back into Freecodecamp and nill. Can you please look into this ASAP and don't dismiss it as not a bug,`

`
// Example
// Example
function ourFunctionWithArgs(one, two) {
  console.log(1 + 2 );
}
ourFunctionWithArgs(1, 2); // Outputs 3

// Only change code below this line.
function functionWithArgs(one, two) {
  console.log(1 + 2);
}
function functionWithArgs(seven, nine) {
  console.log(7 + 9);
}
functionWithArgs(1 + 2); // Outputs 3

`
![gh-hub](https://user-images.githubusercontent.com/37039357/46232118-08694f80-c366-11e8-88cb-a1505ed5f20c.PNG)
![rpl](https://user-images.githubusercontent.com/37039357/46232119-0901e600-c366-11e8-90ce-b5078196d1c6.PNG)


`

I think we would all appreciate someone looking into this as I have already scoured the internet for a result and there's no result how to get past this. For one I was actually enjoying learning..



----- Again

// Example
function ourFunctionWithArgs(one, two) {
  console.log(1 + 2 );
}
ourFunctionWithArgs(1, 2); // Outputs 3

// Only change code below this line.
function functionWithArgs(one, two) {
  console.log(1 + 2 );
}
function functionWithArgs(seven, nine) {
  console.log(7 + 9);
}
functionWithArgs(1,2); // Outputs 3
functionWithArgs(7,9); // Outputs 16

**Comment by mariacappon** [comment]
function functionWithArgs(a, b) {
  console.log(a + b);
}

functionWithArgs(7, 9);
functionWithArgs(1, 2);
