### ISSUE TITLE
Challenge [Accessing Nested Objects]

### ISSUE THREAD

**Issue by sashastark** [FreeCodeCamp/FreeCodeCamp#12321]
Challenge [Accessing Nested Objects]
Hello, please help me, I don't know what else to do, I've already restarted it several times, nothing happened.

My code:
```javascript

// Setup
var myStorage = {
  "car": {
    "inside": {
      "glove box": "maps",
      "passenger seat": "crumbs"
     },
    "outside": {
      "trunk": "jack"
    }
  }
};

// Only change code below this line

var glowBoxContents = myStorage.car.inside["glove box"]; 


```

**Comment by sashastark** [comment]
I don't know whether it is a bug or not, I think I changed the code correctly, but it doesn't work

**Comment by raisedadead** [comment]
Hi @sashastark 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding!

**Comment by markring** [comment]
I have the same issue, but your chat room does not function I cannot ask there.

**Comment by ellsee** [comment]
You wrote glowBoxContents, not gloveBoxContents
