### ISSUE TITLE
Visa

### ISSUE THREAD

**Issue by ramiksa11** [FreeCodeCamp/FreeCodeCamp#12332]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by erictleung** [comment]
@ramiksa11 please fill out the issue template if there is an issue with the site. Closing issue as there is not enough information to help. Please comment back if you have more information. Happy coding!
