### ISSUE TITLE
Escape Sequences in Strings Issue

### ISSUE THREAD

**Issue by RishabhAggarwal028** [FreeCodeCamp/FreeCodeCamp#12339]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D%22FristLine%5Cn%5C%5CSecondLine%5C%5C%5CrThirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr="FristLine\n\\SecondLine\\\rThirdLine"; // Change this line



```
Output:

myStr = "FristLine\n\\SecondLine\\\rThirdLine"

**Comment by Lapz** [comment]
You solution is not correct that is why you are seeing an error. If you need help check out the gitter chatroom.[https://gitter.im/FreeCodeCamp/HelpJavaScript](url)

**Comment by raisedadead** [comment]
Hi @RishabhAggarwal028 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding!
