### ISSUE TITLE
Sorted Union Issue the Result is correct but it cant pass the examine

### ISSUE THREAD

**Issue by williamstar** [FreeCodeCamp/FreeCodeCamp#12335]
the Result is correct but it cant pass the examine

here is the link for this problem

https://www.freecodecamp.com/challenges/sorted-union

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
```javascript
function uniteUnique(arr) {
    arr = arguments;
    var size = arr.length;
    var narr = [];
    for (var i = 0; i < size; i++) {
        for (var j = 0; j < arr[i].length; j++) {
            if (narr.indexOf(arr[i][j]) === -1) {
                narr.push(arr[i][j]);
            }
        }
    }
    return narr;
}

uniteUnique([1, 3, 2], [5, 2, 1, 4], [2, 1]);
```

**Comment by Dayfiri** [comment]
@williamstar 
Can you please provide a link to a given exercise so others can easier see what exactly needs to be done. By the way, I copy/pasted your code and got this result:
![screenshot from 2017-01-03 11-30-41](https://cloud.githubusercontent.com/assets/16082563/21605257/2f5594f2-d1a8-11e6-9bbc-fef4bb056905.png)
For help with code and assignment please visit [Help](https://gitter.im/FreeCodeCamp/Help) page.
This page is for reporting bugs only.
Happy coding ;)

**Comment by williamstar** [comment]
@Dayfiri i edit the issue and add the problem link above the code.

**Comment by Dayfiri** [comment]
@williamstar 
Thanks for the link. I tried running your code in the FCC editor and it `return`s a good result on a naked eye. But if you dig a little bit more, you can see that it is not the only thing coming out.
![screenshot from 2017-01-03 12-31-19](https://cloud.githubusercontent.com/assets/16082563/21606581/ca8552d4-d1b0-11e6-87bc-c2b5bf580976.png)
As I console log the result, you can see many other results in the output, next to the original one.
I'll leave an example here for moderators to see. So they can check it more thoroughly.

**Comment by williamstar** [comment]
@Dayfiri Thanks. I didn't notice that FCC output will write to the dev-tool.It seems that I can't **assign the arguments to other variables**.when i try to modify the code below it pass the examine.

```javascript
function uniteUnique(arr) {
    var size = arguments.length;
    var narr = [];
    for (var i = 0; i < size; i++) {
        for (var j = 0; j < arguments[i].length; j++) {
            if (narr.indexOf(arguments[i][j]) === -1) {
                narr.push(arguments[i][j]);
            }
        }
    }

    return narr;
}
```
