### ISSUE TITLE
Comment out HTML Problem

### ISSUE THREAD

**Issue by dhb55** [FreeCodeCamp/FreeCodeCamp#12333]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%3C!--%0A%0A%3C--Hello%20World--%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3C!--Hello%20Paragraph--%3E%0A--%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--
<!--

<--Hello World-->

<h2>CatPhotoApp</h2>

<!--Hello Paragraph-->
-->

<--Hello World-->

<h2>CatPhotoApp</h2>

<!--Hello Paragraph-->
-->

```

**Comment by dhb55** [comment]
i have followed the steps correctly, why is the very last part of the command not letting me complete the challenge, which says: Do not change the order of the h1,h2 or p in the code?

**Comment by felipeklafke** [comment]
close comment

you opened comments more times that closed and order is wrong too...

you need comment <h1> tag and <p> tag

like this


<h2>CatPhotoApp</h2>
