### ISSUE TITLE
Size Your Images Challenge

### ISSUE THREAD

**Issue by Hieuhuule** [FreeCodeCamp/FreeCodeCamp#12340]
The code looks correct, but the editor won't register the success.

Challenge [Size your Images](https://www.freecodecamp.com/challenges/size-your-images#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3Dsmaller-image%0A%20%20%20%20%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20%0A%20%20%20%20%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%0A%20%20%20%20%20%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .smaller-image {
    width: 100px;
  }
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class=smaller-image
     src="https://bit.ly/fcc-relaxing-cat" 
     alt="A cute orange cat lying on its back. "
     >

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by Hieuhuule** [comment]
When I link another image of a cat, the pixel width becomes a success, but the image element becomes a failure.
![image width](https://cloud.githubusercontent.com/assets/24836277/21616331/a50f5702-d1a6-11e6-9dc8-0288b00892d9.jpg)

**Comment by dhcodes** [comment]
@Hieuhuule your code worked for me. Try copying your code, refreshing the browser, and then submitting again.

**Comment by Hieuhuule** [comment]
@dhcodes Just tried it again, still no luck getting it going.  I'll have to try it on another computer when I get home.

**Comment by Manish-Giri** [comment]
@Hieuhuule Well in your first code, you were missing the quotes around the class name - 
```
<img class=smaller-image
     src="https://bit.ly/fcc-relaxing-cat" 
     alt="A cute orange cat lying on its back. "
     >
```

**Comment by Hieuhuule** [comment]
@Manish-Giri Attached is what my code is now.  The quotes around the class name doesn't seem to affect it.

![image width](https://cloud.githubusercontent.com/assets/24836277/21623992/9a14705c-d1ca-11e6-9a62-c3bba4a4996a.jpg)

**Comment by dhcodes** [comment]
@Hieuhuule what browser are you on?

**Comment by Hieuhuule** [comment]
@dhcodes I'm on Mozilla Firefox, exact details are Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by raisedadead** [comment]
@Hieuhuule do you mind copy-pasting your code in here? 
resources: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by abroham** [comment]
I'm having the same exact problem! Also using Mozilla Firefox. I'll switch over to Chrome and see what's up.

**Comment by abroham** [comment]
I've tried it again and it went through. The error I kept having was that apparently I didn't have smaller-image ("smaller-image") in my img element. This was untrue. However, my pixel width was approved and accounted for. 
Here is what I have:
![capture](https://cloud.githubusercontent.com/assets/24896108/21634037/c902c59a-d219-11e6-899d-9ec1e6a1eef4.JPG)

**Comment by abroham** [comment]
I'm going to reset it and try again

**Comment by abroham** [comment]
It worked again. Just drop   class="smaller-image"   right into the img Element you already have. 
![capture](https://cloud.githubusercontent.com/assets/24896108/21634124/5b48929a-d21a-11e6-9bca-5cd7cc36f50c.JPG)

**Comment by getoutb1** [comment]
Stop

**Comment by Hieuhuule** [comment]
The same code worked once I switched over to Chrome so thats what I suggest others who have the same problem do.

**Comment by LucasVenancio** [comment]
the problem and I am working with safari
