### ISSUE TITLE
Code will not import lobster font 

### ISSUE THREAD

**Issue by Kennneth** [FreeCodeCamp/FreeCodeCamp#12343]
Challenge [Import a Google Font](https://www.freecodecamp.com/challenges/import-a-google-font) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
    font-family:  Monospace; 
    }
  h2{
    font-family:Lobster;
  }
</style>


<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">


<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by DevSealTeam** [comment]
I do not See Lobster Font Import code?

**Comment by Kennneth** [comment]
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
@DevSealTeam

**Comment by Kennneth** [comment]
snippet code provided didn't work
 https://www.freecodecamp.com/challenges/import-a-google-font 
@DevSealTeam

**Comment by dhcodes** [comment]
@Kennneth your code works for me. Maybe try copying your code and then refreshing the browser. Also if you're on a mobile device, chrome sometimes has a non-breaking space issue so it may have to remove new lines.

**Comment by raisedadead** [comment]
@Kennneth if you are still facing the issue, please let us know. Closing for now.

**Comment by jorgecrespoboca** [comment]
h was missing h2

although it's late I hope it can help someone else in the future
