### ISSUE TITLE
Getting an error for testing the true value.

### ISSUE THREAD

**Issue by aymohamed** [FreeCodeCamp/FreeCodeCamp#12341]
Challenge [Use Conditional Logic with If Statements](https://www.freecodecamp.com/challenges/use-conditional-logic-with-if-statements#?solution=%0A%2F%2F%20Example%0Afunction%20ourTrueOrFalse(isItTrue)%20%7B%0A%20%20if%20(isItTrue)%20%7B%20%0A%20%20%20%20return%20%22Yes%2C%20it's%20true%22%3B%0A%20%20%7D%0A%20%20return%20%22No%2C%20it's%20false%22%3B%0A%7D%0A%0A%2F%2F%20Setup%0Avar%20num%3B%0Afunction%20trueOrFalse(wasThatTrue)%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20if(num%3E1)%20%7B%0A%20%20%20%20return%20%22Yes%2C%20that%20was%20true%22%3B%0A%20%20%20%20%0A%20%20%7D%0A%20%20return%20%22No%2C%20that%20was%20false%22%3B%0A%20%20%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtrueOrFalse(10)%3B%0AtrueOrFalse(0)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourTrueOrFalse(isItTrue) {
  if (isItTrue) { 
    return "Yes, it's true";
  }
  return "No, it's false";
}

// Setup
var num;
function trueOrFalse(wasThatTrue) {

  // Only change code below this line.
  if(num>1) {
    return "Yes, that was true";
    
  }
  return "No, that was false";
  
  
  
  // Only change code above this line.

}

// Change this value to test
trueOrFalse(10);      //This throws an error! Why?
trueOrFalse(0);

```

**Comment by aymohamed** [comment]
This works:


// Example
function ourTrueOrFalse(isItTrue) {
  if (isItTrue) { 
    return "Yes, it's true";
  }
  return "No, it's false";
}

// Setup
function trueOrFalse(myCondition) {

  // Only change code below this line.
  if(myCondition) {
    return "Yes, that was true";
  }
    return "No, that was false";

  
  
  
  // Only change code above this line.

}

// Change this value to test
trueOrFalse(5>2);
trueOrFalse(5<2);

**Comment by Lapz** [comment]
I think that the starting code and the wording of the exercise is very confusing and should be changed to something more like this:
 `
function trueOrFalse(wasThatTrue) {

  // Only change `code` below this line.
  if(wasThatTrue === true ) {
    return "Yes, that was true";
    
  }
  return "No, that was false";
  
  
  
  // Only change code above this line.

}
`

**Comment by Manish-Giri** [comment]
@aymohamed Why're you setting up a `num` variable again?

**Comment by aymohamed** [comment]
@Manish-Giri , I was trying to create a global variable that works for the test case. But everything works now. Thanks though.

**Comment by Bouncey** [comment]
@aymohamed I'm glad you managed to squash your bug!

Happy Coding!
