### ISSUE TITLE
Bug with challenge: Target the same element with multiple jQuery Selectors 

### ISSUE THREAD

**Issue by sevenok** [FreeCodeCamp/FreeCodeCamp#12346]
It doesn't let me advance and for what I've checked my code is correct. Anyone knows how to solve this issue?

<script>
  $(document).ready(function() {
    $("button").addClass(animated);
    $(".btn").addClass(shake); 
    $("#target1").addClass(btn-primary);
  });
</script>

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

**Comment by Manish-Giri** [comment]
@sevenok Your code is incorrect, you're missing the quotes around the class names.

If you need help with a challenge, please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) first, in future. This place is for reporting issues with the website itself. Happy Coding!

**Comment by sevenok** [comment]
Sorry dude, my bad.

**Comment by Manish-Giri** [comment]
@sevenok It's cool, not a problem :+1:
