### ISSUE TITLE
Waypoint: Try Camper News - Task 7 Incorrect

### ISSUE THREAD

**Issue by mabogunje** [FreeCodeCamp/freecodecamp#1235]
Task no. 7, says: "You can view the portfolio pages of any camper who has posted links or comments on Camper News. Just click on their photo." However, clicking a photo simply licks back to the homepage. Clicking their username links to their profile. So the instruction needs to be updated.

**Comment by LumenTeun** [comment]
Thank you for finding and reporting this! I went the other way and fixed the bug instead of the instructions, seemed more appropriate ;)

**Comment by mabogunje** [comment]
No problem. Glad I could help.
