### ISSUE TITLE
Amswer Matches, but it Still shows i'm wrong 

### ISSUE THREAD

**Issue by What-The-feu** [FreeCodeCamp/FreeCodeCamp#12358]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0A%0Afunction%20titleCase(str)%20%7B%0A%20%20var%20yo%3D%22%22%3B%0A%20%20var%20arrayOfStrings%3Dstr.split(%22%20%22)%3B%0A%20%20for(i%3D0%3Bi%3CarrayOfStrings.length%3Bi%2B%2B)%7B%0A%20%20%20arrayOfStrings%5Bi%5D%3DarrayOfStrings%5Bi%5D.toLowerCase()%3B%0A%20%20%20%20yo%2B%3DarrayOfStrings%5Bi%5D.charAt(0).toUpperCase()%2BarrayOfStrings%5Bi%5D.slice(1)%3B%0A%20if(i!%3DarrayOfStrings.length-1)%7B%0A%20%20%20%20yo%2B%3D%22%20%22%3B%0A%20%7D%0A%20%20%20%20%0A%20%20%7D%0A%20%20return%20%22%5C%22%22%2Byo%2B%22%5C%22.%22%3B%0A%7D%0A%0AtitleCase(%22HERE%20IS%20MY%20HANDLE%20HERE%20IS%20MY%20SPOUT%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript


function titleCase(str) {
  var yo="";
  var arrayOfStrings=str.split(" ");
  for(i=0;i<arrayOfStrings.length;i++){
   arrayOfStrings[i]=arrayOfStrings[i].toLowerCase();
    yo+=arrayOfStrings[i].charAt(0).toUpperCase()+arrayOfStrings[i].slice(1);
 if(i!=arrayOfStrings.length-1){
    yo+=" ";
 }
    
  }
  return "\""+yo+"\".";
}

titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");


```

**Comment by dhcodes** [comment]
@What-The-feu you have an error in your code. Consider asking for help in the chat room by clicking the help button on the challenge page.

**Comment by dhcodes** [comment]
@What-The-feu in this case, it's because you are adding quotes to the string at the end. You don't need to add those as it is already a string when it is returned. The quotes in the test are just to indicate the expected result.
