### ISSUE TITLE
logical OR operator question

### ISSUE THREAD

**Issue by aymohamed** [FreeCodeCamp/FreeCodeCamp#12359]
Challenge [Comparisons with the Logical Or Operator](https://www.freecodecamp.com/challenges/comparisons-with-the-logical-or-operator#?solution=%0Afunction%20testLogicalOr(val)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20if%20(val%3E%3D10%20%7C%7C%20val%3C%3D20)%20%7B%0A%20%20%20%20return%20%22Inside%22%3B%0A%20%20%7D%0A%20%20%20return%20%22Outside%22%3B%0A%20%20%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestLogicalOr(11)%3B%20%20%20%2F%2Fshould%20return%20Inside%0AtestLogicalOr(30)%3B%20%20%20%2F%2F%20should%20return%20Outside%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testLogicalOr(val) {
  // Only change code below this line

  if (val>=10 || val<=20) {
    return "Inside";
  }
   return "Outside";
  

  // Only change code above this line
  
}

// Change this value to test
testLogicalOr(11);   //should return Inside
testLogicalOr(30);   // should return Outside
/* I wonder why this does not work. How does one say not greater than?? */


```

**Comment by dhcodes** [comment]
@aymohamed you have an error in your code. You can get code help by clicking the help button on the challenge and asking for help in the chat room.
