### ISSUE TITLE
Profile Lookup confuses with same param name and attribute name

### ISSUE THREAD

**Issue by spoonhonda** [freeCodeCamp/freeCodeCamp#12355]
Challenge [Profile Lookup](https://www.freecodecamp.com/challenges/profile-lookup#?solution=%0A%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intriguing%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%0A%5D%3B%0A%0A%0Afunction%20lookUpProfile(prop1%2C%20prop2)%7B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20i%20%3D%200%3B%0A%20%20while(i%20!%3D%20contacts.length)%20%7B%0A%20%20%20%20if(contacts%5Bi%5D.firstName%20%3D%3D%20prop1)%7B%0A%20%20%20%20%20%20console.log(%22got%20it%22)%3B%0A%20%20%20%20%20%20if(contacts%5Bi%5D%5Bprop2%5D)%7B%0A%20%20%20%20%20%20%20%20return%20contacts%5Bi%5D%5Bprop2%5D%3B%0A%20%20%20%20%20%20%7Delse%7B%0A%20%20%20%20%20%20%20%20return%20%22No%20such%20property%22%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20i%2B%2B%3B%0A%20%20%7D%0A%20%20return%20%22No%20such%20contact%22%3B%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0AlookUpProfile(%22Akira%22%2C%20%22likes%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];


function lookUpProfile(prop1, prop2){
// Only change code below this line
  var i = 0;
  while(i != contacts.length) {
    if(contacts[i].firstName == prop1){
      if(contacts[i][prop2]){
        return contacts[i][prop2];
      }else{
        return "No such property";
      }
    }
    i++;
  }
  return "No such contact";
// Only change code above this line
}

// Change these values to test your function
lookUpProfile("Akira", "likes");

```

In the Profile Lookup challenge code, the lookUpProfile function's first parameter name is "firstName" which is the same as the array objects "firstName" properties.

The problem is that a novice learner like myself can pass the test without even realizing that the lookUpProfile function's first parameter "firstName" is not at all the same thing as the array objects "firstName" properties.  It's really easy to assume they are one and the same.  

I propose we change the lookUpProfile function's parameter "firstName" to something like "prop1" (for example like I have it posted here in the code above).  Honestly, while I was solving this challenge it was very confusing at first until I realized that "firstName" was used for two different things (function parameter and the array objects properties)  in the code.

Any thoughts or other suggestions.

**Comment by joaofreires** [comment]
Hello!
Well, your argumentation is good, but i think that it's good to learn how the language works. It's like scopes. 
Another point is about logic, you want find "firstName" then you'll find it in "firstName" propety, this make sense. It's just how i think.

**Comment by spoonhonda** [comment]
I considered your point of argument before I posted this.  I don't agree that this is a good way to teach a student about scopes since it was never clarified in the instructions.  It just fosters confusion and/or wrong assumptions that "firstName" is the same thing throughout the code. A student can actually pass the challenge without even realizing there's a difference.  So the student is not learning about scopes in that case but left to assume that there is no boundary in the scopes.  That somehow its all the same.  Clarity in stead of trickery/obscurity is a much better way to teach something in my opinion.

**Comment by systimotic** [comment]
@raisedadead
I think changing this could take away confusion for some people, and I don't think changing it will confuse anybody, so I think this change is worth it.
Would `name` be a good balance between meaningful and different?

**Comment by raisedadead** [comment]
Agreed @systimotic

**Comment by systimotic** [comment]
# First-timers only
Check out [CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) to get your local development environment set up.

The seed for this challenge is [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L5378). Change the `firstName` parameter to `name`.

If you need help, please go to our [contributors chatroom](https://gitter.im/FreeCodeCamp/Contributors).

Happy coding! 🎉

**Comment by db001** [comment]
Hi, just sent a pull request with the fix for this
