### ISSUE TITLE
Unsubscribing to emails should unsubscribe duplicate accounts as well

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#12352]
#### Issue Description
Campers will often accidentally create duplicate accounts (most of this is because we made the mistake of offering multiple authentication options). 

When they unsubscribe from emails, we want to make sure they are unsubscribed from all emails for all accounts with that email address, including duplicate accounts. 

The unsubscribe code just needs to be refactored to get all accounts with that email address. Currently it's a `findOne` query.

It's located in the RandomAPIs.js and the relevant function is called 

To test your code, you'll want to create multiple accounts that have the same email address. You'll then want to test the unsubscribe functionality (`https://www.freecodecamp.com/unsubscribe/[email]`) and verify that both accounts are unsubscribed. This means all three of these attributes should be set to false:
"sendMonthlyEmail"
"sendNotificationEmail"
"sendQuincyEmail"

**Comment by suhussai** [comment]
I'd like to work on this. Just wondering about the tests though. You mentioned how one could manually test it, but what about codifying the test?

**Comment by Bouncey** [comment]
@suhussai If you can find a graceful way to use a unit test for this then by all means submit a PR, but it is not a prerequisite for the PR itself :+1:
