### ISSUE TITLE
Issue with JS: Modify Array Data Challenge 

### ISSUE THREAD

**Issue by djokester** [FreeCodeCamp/FreeCodeCamp#12366]
#### Challenge Name: Javascript: Modify Array Data With Indexes 

https://www.freecodecamp.com/challenges/modify-array-data-with-indexes

#### Issue Description

Minor Bug. Usually when the semicolon ";" is missing in the code a TypeError is displayed. However in this challenge, 
myArray[0] = 3
does not raise this error and we are able to pass on to the next challenge.
#### Browser Information

 
* Browser Name, Version: Google Chrome,Version 55.0.2883.87 (64-bit)
* Operating System: Ubuntu 16.10.
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
// Example
var ourArray = [1,2,3];
ourArray[1] = 3; // ourArray now equals [1,3,3].

// Setup
var myArray = [1,2,3];

// Only change code below this line.
myArray[0] = 3
```

**Comment by Bouncey** [comment]
@djokester I am closing this issue now.

If you have more to add, please feel free to open this issue again :+1: 

Happy Coding!
