### ISSUE TITLE
Sample Code is hidden due to failed text wrapping.

### ISSUE THREAD

**Issue by iBrooks** [FreeCodeCamp/FreeCodeCamp#12362]
Challenge [Condense arrays with reduce](https://www.freecodecamp.com/challenges/condense-arrays-with-reduce#?solution=%0Avar%20array%20%3D%20%5B4%2C5%2C6%2C7%2C8%5D%3B%0Avar%20singleVal%20%3D%200%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AsingleVal%20%3D%20array%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var array = [4,5,6,7,8];
var singleVal = 0;

// Only change code below this line.

singleVal = array;


```
The Sample code element isn't wrapping the text so it is hidden.
![screen shot 2017-01-04 at 11 49 58 am](https://cloud.githubusercontent.com/assets/7727330/21650716/e6be12d8-d273-11e6-8c10-1f4d870d12f6.png)

**Comment by raisedadead** [comment]
Can you please share your viewport size?

**Comment by Bouncey** [comment]
Confirmed on `staging` at view-port width > 1742px (with horizontal scroll bar)

I would suggest either/and:
- shortening variable/param names to decrease the line length
- try adding in some `<wbr>` elements to allow the text to wrap i.e. `array.reduce(<wbr>function....`
