### ISSUE TITLE
Cannot start coding task one!

### ISSUE THREAD

**Issue by eclectic-matt** [FreeCodeCamp/freecodecamp#1236]
Page(s) affected: http://www.freecodecamp.com/challenges/Waypoint:%20Say%20Hello%20to%20HTML%20Elements

The buttons for "More information" from the very first coding task onwards ("Hello World" in h1 tags) do not work and completing the tasks required does not allow progression to the next task. The buttons and page elements worked perfectly in previous tasks but cannot progress in the coding tasks.

Using Up-to-date Chrome on Android smartphone.

**Comment by faizanmobh** [comment]
I am facing the same problem. Then i tried different web browsers but problem doesn't solve.hope they will solve this asap

**Comment by FFX01** [comment]
As far I understand this is a problem people have been having specifically on mobile devices.

**Comment by eclectic-matt** [comment]
I checked on desktop - no issues with button elements ("More Information" or "Move on to Next Challenge").

On Chrome Android, cannot use any such buttons for future challenges as well as the waypoint linked above.

**Comment by LumenTeun** [comment]
Thank you for reporting, but this seems like a duplicate of #1103, please close this issue and keep relevant discussion in there.

**Comment by eclectic-matt** [comment]
Found to be duplicated issue. Closing this to feed into:

https://github.com/FreeCodeCamp/freecodecamp/issues/1103
