### ISSUE TITLE
MongoDB Runnning Problem using the instruction

### ISSUE THREAD

**Issue by arsho** [FreeCodeCamp/FreeCodeCamp#12379]
Challenge [Store Data in MongoDB](https://www.freecodecamp.com/challenges/store-data-in-mongodb) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.

When we try to run mongodb in c9 using the command: mongod --port 27017 , we get error "ERROR: Insufficient free space for journal files". The screenshot is included:
![mongo](https://cloud.githubusercontent.com/assets/5465070/21674376/abcb5c6e-d357-11e6-9326-16bc05743820.png)

To run mongodb successfully in c9 within the provided memory we should run mongodb using the following command: mongod --port 27017 --smallfiles

**Comment by aguyinmontreal** [comment]
I type:

$ ./mongod --port 27017
$ learnyoumongo verify
And I get:

✗ Error connecting to mongo. failed to connect to server [localhost:27017] on first connect

Thanks!
