### ISSUE TITLE
Editor doesn't place cursor properly

### ISSUE THREAD

**Issue by ChadBailey** [FreeCodeCamp/FreeCodeCamp#12374]
#### Challenge Name
All challenges are impacted (at least all beginning challenges)

#### Issue Description
Editor does not place cursor correctly. Highlighting text is offset by 1-2 rows until an event occurs which corrects the editor. Events that correct the editor 1) Begin typing anywhere. 2) click on one of the curly-brackets in the CSS section.

#### Browser Information
* Google Chrome Version 55.0.2883.87 m (64-bit) 
* Operating System: Windows 10 Professional
* Desktop

#### Screenshot
https://www.youtube.com/watch?v=6ILdTCoAMSs
Note: at 0:31 I hit the key "f" which makes it appear 2 lines below where my cursor was at, this happened automatically and also shows that doing this resolves the issue.

**Comment by erictleung** [comment]
@ChadBailey sounds like you're going through this issue https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7847. Please take a look at the issue thread for some work-arounds for this issue and report back here if that is your issue. Thanks!

**Comment by ChadBailey** [comment]
@erictleung thank you for your quick response. I didn't know what search terms to use (actually struggled coming up with a topic name). Can confirm this appears to be related to text wrapping. I would imagine the resolution will work once it is released.
