### ISSUE TITLE
Returns correct value but it does not pass

### ISSUE THREAD

**Issue by way3edgyentertainment** [FreeCodeCamp/FreeCodeCamp#12384]
Challenge [Find the Longest Word in a String](https://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=var%20curlength%3D0%3B%0Avar%20maxlength%3D0%3B%0Avar%20arr%3D%5B%5D%3B%0Afunction%20findLongestWord(str)%20%7B%0A%20%20arr%3Dstr.split('')%3B%0A%20%20for(i%3D0%3Bi%3Carr.length%3Bi%2B%2B)%7B%0A%20%20%20%20if(arr%5Bi%5D!%3D'%20')%7B%0A%20%20%20%20%20%20curlength%2B%3D1%3B%0A%20%20%20%20%20%20if(curlength%3Emaxlength)%7B%0A%20%20%20%20%20%20%20%20maxlength%3Dcurlength%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7Delse%7B%0A%20%20%20%20curlength%3D0%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20maxlength%3B%0A%7D%0A%0AfindLongestWord(%22What%20is%20the%20average%20airspeed%20velocity%20of%20an%20unladen%20swallow%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var curlength=0;
var maxlength=0;
var arr=[];
function findLongestWord(str) {
  arr=str.split('');
  for(i=0;i<arr.length;i++){
    if(arr[i]!=' '){
      curlength+=1;
      if(curlength>maxlength){
        maxlength=curlength;
      }
    }else{
    curlength=0;
    }
  }
  return maxlength;
}

findLongestWord("What is the average airspeed velocity of an unladen swallow");

```

**Comment by raisedadead** [comment]
Hi @way3edgyentertainment 

In your code you have:

```
  var curlength=0;
  var maxlength=0;
  var arr=[];
```

These are declared as globals and our challenge testing code currently, doesn't support having global declarations (except for some challenges).

There is an ongoing discussion in #9199 

Until we have a mechanism to figure out more about this, please refactor your code to use declarations within a scope.

For example, in your case just by moving them within the function.
