### ISSUE TITLE
Share current progress with others

### ISSUE THREAD

**Issue by FlameFractal** [FreeCodeCamp/FreeCodeCamp#12388]
Sorry if it exists, I couldn't find it!

I think there should be a way to be able to share a link with someone so that they can verify our current progress as a camper. As the hours of work to complete a certification are quite a lot, we might want to share intermediary progress with others.

**Comment by systimotic** [comment]
Hi @FlameFractal! If you click your profile picture on the top right, you get redirected to your profile page, which shows your progress. It also shows your certificates, if you have them. For you, this page is at https://www.freecodecamp.com/FlameFractal
Is this what you were looking for?

**Comment by FlameFractal** [comment]
Okay I wasn't aware other people could view this! Thanks!

Apologies.

**Comment by systimotic** [comment]
No worries, happy coding!
