### ISSUE TITLE
Challenge Target the same element with multiple jQuery Selectors has an issue.

### ISSUE THREAD

**Issue by ty88523476** [FreeCodeCamp/FreeCodeCamp#12395]
Challenge Target the same element with multiple jQuery Selectors has an issue.
User Agent is: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

<script>
  $(document).ready(function() {
    $("button").addclass("animated");
    $(".btn").addclass("shake");
    $("#target1").addclass("btn-primary")

  });
</script>

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

**Comment by raisedadead** [comment]
Duplicate https://github.com/FreeCodeCamp/FreeCodeCamp/issues/12394

**Comment by chun835644887** [comment]
hello

**Comment by CapnRichard** [comment]
I have the same issue
