### ISSUE TITLE
Brownie points with chat integration

### ISSUE THREAD

**Issue by smileytechguy** [freeCodeCamp/freeCodeCamp#12398]
#### Issue Description

Not sure if this should be a feature request of camperbot

The "streak" on profile page should show thanks received in chats as well as challenges

**Comment by robbawebba** [comment]
@smileytechguy I like that feature idea! So you're saying that brownie points from gitter chats should be saved and kept track of on user's profiles?

**Comment by dhcodes** [comment]
@smileytechguy the streak does include the camperbot "thanks". So to clarify, are you requesting that when you hover over a square on the streak, it show how many points are from each type: challenges vs. thanks? Or would this be displayed in some other way?

**Comment by smileytechguy** [comment]
Yes, that is what i mean.

What would also be cool is to maybe show the amount from challenges and amount from gitter on profile

**Comment by raisedadead** [comment]
BROWNIE POINTS! Did we forget about them?
This is an interesting idea, and maybe something for the Open API project.

@smileytechguy thanks for bringing this up.
