### ISSUE TITLE
BUG:Target the same element with multiple jQuery Selectors

### ISSUE THREAD

**Issue by ty88523476** [FreeCodeCamp/FreeCodeCamp#12394]
Target the same element with multiple jQuery Selectors
Here is my code:
<script>
  $(document).ready(function() {
    $("button").addclass("animated");
    $(".btn").addclass("shake");
    $("#target1").addclass("btn-primary")

  });
</script>
Pls tell me how to correct it

**Comment by raisedadead** [comment]
The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding!
