### ISSUE TITLE
Use new /link routes for linking accounts

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/freecodecamp#124]
Loopback.js differentiates between linking and login for passport strategies.
Current linking needs to have links updated

**Comment by terakilobyte** [comment]
Links have been updated. I've also added a providers.json file as per the loopback-example-passport application.

It's successfully reaching out to twitter and the callback is being fired, but it's not actually creating a new user or authenticating them.

**Comment by BerkeleyTrue** [comment]
@QuincyLarson do we have a stagging server to test out the other third party logins and linking process?
