### ISSUE TITLE
Reword "Sum All Odd Fibonacci Numbers" question

### ISSUE THREAD

**Issue by neighbor983** [FreeCodeCamp/FreeCodeCamp#12412]
The question should be reworded. 
Instead of
"For example, sumFibs(10) should return 10 because all odd Fibonacci numbers less than 10 are 1, 1, 3, and 5."

It should be
"For example, sumFibs(10) should return 10 because all odd Fibonacci numbers less than _**or equal to**_ 10 are 1, 1, 3, and 5."

The **_or equal to_** matters for the last check. (sumFibs(75025) should return 135721.)

#### Challenge Name

Sum All Odd Fibonacci Numbers
https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers

**Comment by erictleung** [comment]
@neighbor983 thanks for your keen eye. This has actually been fixed in https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11542. The changes will be pushed up soon with the next update. Closing as resolved in staging. Happy coding!
