### ISSUE TITLE
truncate a string function expects str and num, some of the tests pass str and str

### ISSUE THREAD

**Issue by m4sterbunny** [FreeCodeCamp/FreeCodeCamp#12418]
Challenge [Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string#?solution=function%20truncateString(str%2C%20num)%20%7B%0A%20%20%2F%2F%20Clear%20out%20that%20junk%20in%20your%20trunk%0A%20%20if%20(str.length%20%3E%20num%20%26%26%20num%20%3E%203)%20%7B%0A%20%20%20%20return%20str.slice(0%2C%20(num%20-%203))%20%2B%20'...'%3B%0A%20%20%7D%20else%20if%20(str.length%20%3E%20num%20%26%26%20num%20%3C%3D%203)%20%7B%0A%20%20%20%20return%20str.slice(0%2C%20num)%20%2B%20'...'%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20str%3B%0A%20%20%7D%0A%0A%7D%0AtruncateString(%22A-tisket%20a-tasket%20A%20green%20and%20yellow%20basket%22%2C%2011)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function truncateString(str, num) {
  // Clear out that junk in your trunk
  if (str.length > num && num > 3) {
    return str.slice(0, (num - 3)) + '...';
  } else if (str.length > num && num <= 3) {
    return str.slice(0, num) + '...';
  } else {
    return str;
  }

}
truncateString("A-tisket a-tasket A green and yellow basket", 11);

```

**Comment by systimotic** [comment]
Hi @m4sterbunny! Thank you for reporting this issue.

As far as I can tell, all of the tests pass a number as the second argument. The last two tests use `"Text here".length`, which does include a string, but it is turned into a number that is the length of the string. You can see this if you `console.log(num)` inside your function. It is always a number.

Your code does pass for me. Was there anything else causing trouble?

**Comment by m4sterbunny** [comment]
wiki code- not mine- does pass yes. Thanks for clearing that up. I found this challenge rather obtuse- something about the description. I will mull over the challenge again.

**Comment by systimotic** [comment]
You got this! If you get stuck, try the help button.
If you have suggestions on how to improve the description, please let us know!
Happy coding! 🙂

**Comment by m4sterbunny** [comment]
Systimotic- see if you can make something from this:

Long strings must be truncated; if your string (first argument) is longer than a given length (second argument) it must be truncated and given a ... ending.

Medium strings must be truncated but note that inserting the three dots to the end adds to the string length. If the given length (second argument) is less than or equal to 3, then the addition of the three dots should not be included in length count.

Tiny strings do not need to be truncated.

**Comment by systimotic** [comment]
@m4sterbunny Thank you for your suggestions. After reviewing the description, I do agree that it is quite confusing. I'll open an issue to discuss changing this to something less confusing.

Thanks again for your input, and more happy coding!
