### ISSUE TITLE
Wrong solution is accepted when submitted

### ISSUE THREAD

**Issue by guyziv2110** [freeCodeCamp/freeCodeCamp#12419]
Challenge [Return Largest Numbers in Arrays](https://www.freecodecamp.com/challenges/return-largest-numbers-in-arrays#?solution=%0Afunction%20largestOfFour(arr)%20%7B%0A%20%20return%20arr.map(function(subArray)%20%7B%0A%20%20%20%20return%20subArray.reduce(function(prev%2C%20curr)%20%7B%0A%20%20%20%20%20%20return%20(curr%20%3E%20prev%20%3F%20curr%20%3A%20prev)%3B%0A%20%20%20%20%7D%2C%200)%3B%0A%20%20%7D)%3B%0A%7D%0A%0AlargestOfFour(%5B%5B4%2C%205%2C%201%2C%203%5D%2C%20%5B13%2C%2027%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
The code below uses map/reduce as suggested in the medium forum (I've reviewed the solutions over there) and is accepted when submitted.

The problem is that there is an assumption that in every subarray not all of the values are negatives and it is not shown in the description of the problem. That is, if one of the subarray contains only negatives values, the accepted solution below isn't correct.

My code:
```javascript

function largestOfFour(arr) {
  return arr.map(function(subArray) {
    return subArray.reduce(function(prev, curr) {
      return (curr > prev ? curr : prev);
    }, 0);
  });
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

```

**Comment by Dayfiri** [comment]
@guyziv2110 
So if I get you right, your problem is that when 1 array is full of only negative numbers the output is not correct.
![screenshot from 2017-01-07 23-18-00](https://cloud.githubusercontent.com/assets/16082563/21745598/c2f507d0-d52f-11e6-8946-7df271115c8b.png)
I tried that and as for others to see, the output should be `-13` as a highest number, but the output shows `0` is the highest one.

**Comment by Bouncey** [comment]
@guyziv2110 Thank you for reporting this. Indeed the second argument for reduce should be  `Number.NEGATIVE_INFINITY` or some other extremely low number to counter this case.

Are the solution examples you found owned by us? I mean, are they on our forum/wiki?

\cc @FreeCodeCamp/moderators Is this worthy of a new test case? I would say yes, but we would possibly need to update to wiki also.

**Comment by guyziv2110** [comment]
@Bouncey Yes. After I solved the problem by myself I walked through the solution for this problem posted in medium (https://medium.freecodecamp.com/three-ways-to-return-largest-numbers-in-arrays-in-javascript-5d977baa80a1) and found this issue.

**Comment by Bouncey** [comment]
Although that article is on the FreeCodeCamp medium blog, I would think it is owned by @SonyaMoisset. 

@QuincyLarson would it be Sonya that needs to make the edit if she agreed to it?

**Comment by ooade** [comment]
@Bouncey We should add a test case that includes negative numbers in a sub array to make that solution fail :sweat_smile:

**Comment by Bouncey** [comment]
## First-timers!!

Add a new test with an array containing only negative numbers i.e `-24`

The code for this challenge is [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/fee1db74e0e4a9a30add78ac7c11a50086f1b6fd/seed/challenges/01-front-end-development-certification/basic-bonfires.json#L389)

Be sure to follow [CONTRIBUTING.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md)

And hit us up in [Contributor Chat](https://gitter.im/freecodecamp/contributors) if you have any problems!

Good luck and Happy Coding!

**Comment by ooade** [comment]
@Bouncey :+1:

**Comment by rajpatel507** [comment]
@Bouncey  can I take this one?

**Comment by Bouncey** [comment]
:+1:

Happy Coding!

**Comment by 91aman** [comment]
@Bouncey I have added a test case for negative values in the array. Please do review the above PR.

**Comment by dhcodes** [comment]
@91aman in the future, please comment on the thread before working on the PR. @rajpatel507 looks like there is a PR in process at this point. I'm sure we'll have more first-timer issues soon, or feel welcome to look at our issue backlog.

**Comment by 91aman** [comment]
@dhcodes Duly noted. will Inform in the thread before working on any issues.

**Comment by systimotic** [comment]
I'd like that to fix this in the code you don't need `Number.NEGATIVE_INFINITY`, removing the `, 0` is enough.
`prev` will then be `undefined` on the first run. Nothing is larger than undefined, therefore it will always return false and use `curr` on the firsts run.

**Comment by 91aman** [comment]
@systimotic I agree with you, not giving initial value `0` will work. The explanation is not correct. 

If `0` is not given, `prev` would not be `undefined`, In the first run, `prev` would be the first value of the array, and the `curr` would be the second value of the array. The comparison would be between the first 2 values of the array.

**Comment by systimotic** [comment]
@91aman That was a stupid mistake, sorry. 😳 You're absolutely right, thanks for reminding me! ❤️

**Comment by dhcodes** [comment]
Just to be clear before I merge this in, making this change will nullify the basic and intermediate solutions on the wiki page for this challenge; only the advanced solution passes the added "all negatives" test. https://forum.freecodecamp.com/t/algorithm-return-largest-numbers-in-arrays/16042

Seems if we make this change, we should also change the solutions on the wiki article.

**Comment by 91aman** [comment]
@dhcodes  I agree, we will need to change both the basic and intermediate solutions. Can you give me some pointers as to where we have the source code of the wiki article?  I can fix it.

**Comment by raisedadead** [comment]
@91aman it's in his comments above yours:

> https://forum.freecodecamp.com/t/algorithm-return-largest-numbers-in-arrays/16042

**Comment by systimotic** [comment]
@91aman I made the edit on the forum 🙂

**Comment by 91aman** [comment]
@systimotic Thanks, I see that you have changed the intermediate solutions. We will also need to change the basic solution where we are still doing `var largestNumber = 0;`.

**Comment by systimotic** [comment]
Wow, I'm really slacking on this issue! Thanks @91aman, I updated and tested that as well.

**Comment by 91aman** [comment]
@systimotic Awesome, Thanks :)
