### ISSUE TITLE
Escape Sequences in Strings. This code worked on the youtube channel so must be a Bug.

### ISSUE THREAD

**Issue by M1L2** [FreeCodeCamp/FreeCodeCamp#12411]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22FirstLine%5Cn%5C%5CSecondline%5C%5C%5CrThirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; AskTbORJ/5.15.9.29495; BRI/2; GWX:QUALIFIED; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

```javascript

var myStr = "FirstLine\n\\Secondline\\\rThirdLine"; // Change this line



```

**Comment by dhcodes** [comment]
@M1L2 the tests may have changed since the video was made and there's an error in your string. Click the help button on the challenge to get some feedback in the chat room.

**Comment by M1L2** [comment]
Any reason for not identifying the error ?

**Comment by dhcodes** [comment]
We want to encourage use of the chat room for code help so the issues area is not overrun with code help requests.

**Comment by dhcodes** [comment]
In this case, the word 'line' in Secondline needs capitalization.

**Comment by M1L2** [comment]
Much appreciated.  Interesting how I can sometimes look and look but not see.
