### ISSUE TITLE
css challenge +1 bug.  challenge will not accept the correct imput as blue.

### ISSUE THREAD

**Issue by lulalulu** [FreeCodeCamp/FreeCodeCamp#12415]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by ooade** [comment]
Your issue is not clear.  __Follow the guide__

**Comment by raisedadead** [comment]
Hi @lulalulu 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding!
