### ISSUE TITLE
#30 goes to next level before user enters the correct tag!

### ISSUE THREAD

**Issue by vishukamble** [FreeCodeCamp/freecodecamp#1241]
In level 30, it says Your app should have a text field input element.
The 'go to next challenge' button is enabled as soon as user enters <input and not <input type='text>
So user can go to next level only by typing <input>
The button should be enabled only when user writes <input type='text>!
![code](https://cloud.githubusercontent.com/assets/7107166/8614522/f7c29720-2707-11e5-993a-8c9b9c44a21b.png)

**Comment by LumenTeun** [comment]
Thank you for catching this. I've created a PR with a fix.

**Comment by ahstro** [comment]
PR was unconventionally merged so the auto-close didn't work. Owners, if you'll do me the honor?
