### ISSUE TITLE
Advanced Algorithm Challenge - Friendly Date Ranges: Update for 2017

### ISSUE THREAD

**Issue by rickMcGavin** [freeCodeCamp/freeCodeCamp#12425]
#### Friendly Date Ranges

[Friendly Date Ranges](https://www.freecodecamp.com/challenges/friendly-date-ranges)

#### Issue Description

The challenge is designed to have the user check and return data based on using the current year. The challenge as it is written will only work when done correctly when the year is 2016. To pass the challenge properly, you have to write your code in a way that makes it seem as if it's 2016. My code below will pass the challenge, but it shouldn't require altering. I have placed comments above the piece I altered to make it pass despite that it is not 2016 still. Simply put: this challenge needs to be updated for 2017.

#### Browser Information

Browser information is most likely not relevant to the issue, but I will include in case.

* Google Chrome, Version: 55.0.2883.95
* Operating System: Mac OS X
* Mobile, Desktop, or Tablet: Desktop, but this issue would impact all. 

#### Your Code

```js
 function makeOrdinal(num) {
  if (num === 1  || num === 21 || num === 31) {
      return num.toString() + "st";
    } else if (num === 2 || num === 22) {
      return num.toString() + "nd";
    } else if (num === 3 || num === 23) {
      return num.toString() + "rd";
    } else {
      return num.toString() + "th";
    }
}

function makeFriendlyDates(arr) {

  var year = new Date().getFullYear();
  var first = new Date(Date.parse((arr[0]).replace("-", "/")));
  var second = new Date(Date.parse((arr[1]).replace("-", "/")));
  var yearMilliseconds = 31536000000;

  var firstMonth = first.getMonth();
  var firstDate = first.getDate();
  var firstYear = first.getFullYear();
  var secondMonth = second.getMonth();
  var secondDate = second.getDate();
  var secondYear = second.getFullYear();
  var result = [];


  if (second - first === 0) {
    return [month[firstMonth]+ " " + makeOrdinal(firstDate) + ", " + firstYear.toString()];
  }

  if ((firstMonth === secondMonth) && (firstYear === secondYear)) {
  return [month[firstMonth].toString() + " " + makeOrdinal(firstDate), makeOrdinal(secondDate)];
  }

  /*In the below check, you will see that I subtracted 1 from the year variable (current year).
  This is because I took the challenge early in 2017, and the challenge seems to still be set up for 2016. In order to pass, I had to make it seem as if it was 2016. */
  if ((second - first < yearMilliseconds) && firstYear === year - 1) {
    return [month[firstMonth] + " " + makeOrdinal(firstDate), month[secondMonth] + " " + makeOrdinal(secondDate)];
  }

  if (second - first < yearMilliseconds) {
    return [month[firstMonth] + " " + makeOrdinal(firstDate) + ", " + firstYear.toString(), month[secondMonth] + " " + makeOrdinal(secondDate)];
  }

  return [month[firstMonth] + " " + makeOrdinal(firstDate) + ", " + firstYear.toString(), month[secondMonth] + " " + makeOrdinal(secondDate) + ", " + secondYear.toString()];
}

 
 
```

**Comment by Bouncey** [comment]
@rickMcGavin Thank you for reporting this issue, we have already had a PR raised and merged to remove this challenge because of the headache it would cause each new year. Unfortunately the patch is only in our react version for FreeCodeCamp at the minute.

@BerkeleyTrue can we push #12317 to production?

**Comment by raisedadead** [comment]
I will quickly make a PR for production as well, kind of a show stopper apparently.

**Comment by raisedadead** [comment]
This has been removed from or production branch as well. Please request your patience, while we update the website.
