### ISSUE TITLE
Goals completed, however not allowed to pass

### ISSUE THREAD

**Issue by GiacomoLaw** [FreeCodeCamp/FreeCodeCamp#12429]
Challenge [Create a Bootstrap Headline](https://www.freecodecamp.com/challenges/create-a-bootstrap-headline#?solution=%3Cdiv%20class%3D%22text-primary%20text-center%22%3E%0A%3Ch3%3EjQuery%20Playground%3C%2Fh3%3E%0A%3C%2Fdiv%3E%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<div class="text-primary text-center">
<h3>jQuery Playground</h3>
</div>




```
I've added the appropriate classes, however two goals are not completed:

- Your h3 element should be colored by applying the class text-primary
- Your h3 element should be centered by applying the class text-center

The preview shows to me it is correct, so I have no idea what is going on. 😕

**Comment by Dayfiri** [comment]
@GiacomoLaw 
You're not reading the assignment right. That is a common mistake made by many of us.
![mhnm](https://cloud.githubusercontent.com/assets/16082563/21750959/56046a86-d5bf-11e6-94c7-57d510bf5f41.png)
While this forum is for reporting bugs only, for future help with assignments please refer to ->[Help](https://gitter.im/FreeCodeCamp/Help) FCC channel.
Thanks and happy coding ;)

**Comment by GiacomoLaw** [comment]
Okay, sorry!
