### ISSUE TITLE
Mobile 

### ISSUE THREAD

**Issue by Che89** [FreeCodeCamp/FreeCodeCamp#12422]
It won't allow me to submit my html code and continue- I am using a mobile phone 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by ooade** [comment]
Not clear. Elaborate more on your **issue..**

**Comment by raisedadead** [comment]
Hi @Che89 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding!

**Comment by Che89** [comment]
While completing the exercise ut wouldn't allow me to submit & move
forward. I'll try with a laptop. I was using my mobile phone. Not sure what
could've been the issue.










On Jan 7, 2017 2:14 PM, "mrugesh mohapatra" <notifications@github.com>
wrote:

Closed #12422 <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/12422>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/FreeCodeCamp/FreeCodeCamp/issues/12422#event-915027608>,
or mute the thread

**Comment by raisedadead** [comment]
@Che89 apologies for the inconvenience, please report back if you are still facing this on a mobile device with the challenge details, code screenshots, the device you are on.

We will definitely help you out with your query and reopen this.

Thanks and happy coding!
