### ISSUE TITLE
Linting issue with chained functions in "Return Largest Numbers"?

### ISSUE THREAD

**Issue by RNCTX** [freeCodeCamp/freeCodeCamp#12427]
Challenge [Return Largest Numbers in Arrays](https://www.freecodecamp.com/challenges/return-largest-numbers-in-arrays#?solution=%0Afunction%20largestOfFour(arr)%20%7B%0A%20%20var%20array0%20%3D%20arr%5B0%5D.sort(function(a%2C%20b)%7Breturn%20a-b%7D).pop()%3B%0A%20%20var%20array1%20%3D%20arr%5B1%5D.sort(function(a%2C%20b)%7Breturn%20a-b%7D).pop()%3B%0A%20%20var%20array2%20%3D%20arr%5B2%5D.sort(function(a%2C%20b)%7Breturn%20a-b%7D).pop()%3B%0A%20%20var%20array3%20%3D%20arr%5B3%5D.sort(function(a%2C%20b)%7Breturn%20a-b%7D).pop()%3B%0A%20%20return%20%5Barray0%2C%20array1%2C%20array2%2C%20array3%5D%3B%0A%20%20%0A%20%20%7D%0A%20%20%0A%0AlargestOfFour(%5B%5B13%2C%2027%2C%2018%2C%2026%5D%2C%20%5B4%2C%205%2C%201%2C%203%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function largestOfFour(arr) {
  var array0 = arr[0].sort(function(a, b){return a-b}).pop();
  ...so forth and so on...
  return [array0, ...];
  
  }
```

The above code works fine, and passes the challenge, but the IDE X's out the chaining of pop from sort using the above method, complaining about "missing semicolon."

If I remove the sort condition and just chain pop from sort(), the IDE doesn't seem to mind but of course that doesn't work out the correct solution in arrays with numbers containing only 1s and 0s.

**Comment by JosephLivengood** [comment]
It looks like it is expecting a semi-colon on the following to not give a syntax error in the editor.
```
return a-b;
```

**Comment by RNCTX** [comment]
Yep, that's what it underlines.  So the question is, is chaining pop() after that bad for some reason or is it an ide error?  The code works (in Chrome, at least).

**Comment by JosephLivengood** [comment]
Come join us in https://gitter.im/FreeCodeCamp/Help for some help and discussion as this is for issues with the site :)

However, to answer- It's just very strict sometimes with ; placement, but it is perfectly acceptable to chain the methods like that (and inline) and I would encourage it in this circumstance for code readability!

**Comment by raisedadead** [comment]
By the looks of it could be a way we are parsing the code. Is this the full code that you have shared in the description?

Also, can you help with the console logs in the DevTools if any errors can be seen?
Pro tip: add `//# sourceURL=myCode.js` on the top of the code, and check in the DevTools sources window, there should be a file myCode.js 

What are its contents?

**Comment by RNCTX** [comment]
No, this is a synopsis.

console log...
;


function largestOfFour(arr) {
  var array = [];
  ;loopProtect.protect({ line: 7, reset: true }); for (var i = 0; i < arr.length; i++) {;
if (loopProtect.protect({ line: 7 })) break;

    array[i] = arr[i].sort(function(a, b){return a-b}).pop();
  }
  
  return array;
  
  }
  

largestOfFour([[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]);
/**/

**Comment by raisedadead** [comment]
@RNCTX thanks, I have updated your comment for some formatting, we will look into this and get back soon.

/cc @FreeCodeCamp/moderators

**Comment by raisedadead** [comment]
![image](https://cloud.githubusercontent.com/assets/1884376/21751744/2fe41774-d5f2-11e6-9ac5-581b481eeb36.png)

**Comment by Bouncey** [comment]
Please refer to [this](
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/12366#issuecomment-270502495)
comment.

Perhaps we could have a wiki article about disabling rules for the linter?

**Comment by RNCTX** [comment]
In light of the fact that it technically was an error in my code, I would say a wiki article on the tolerance for missing semicolons in relation to the error would be more applicable.

I can see the logic for errors in the IDE not preventing submission of the code, since every little IDE error would then halt progress for everyone, but a link to some further context on the error would be nice.

**Comment by systimotic** [comment]
I created a wiki post for this https://forum.freecodecamp.com/t/semicolons-in-javascript/80595
Edits are welcome! Every user on the forum that has been around for a few minutes gets "Basic" status and should be able to edit the wiki article.

I'm closing this issue as resolved. Thanks for reporting and investigating everybody!
