### ISSUE TITLE
CSS selector exercise

### ISSUE THREAD

**Issue by Knotttieboy** [FreeCodeCamp/FreeCodeCamp#12432]
#### Challenge Name
CSS selector ti style elements

#### Issue Description
I can not get my h2 element to turn blue, all the rest of the exercise works fine, I have followed the instructions

#### Browser Information

* Browser Name, Version: Google Chrome
* Operating System: Windows 8.0, I can't get version 10 to work on PC
* Mobile, Desktop, or Tablet: /Desktop PC

#### Your Code

```js
 
 
 
```
#### Screenshot
Remove the style attribute from your h2 element.
Create a style element.
Your h2 element should be blue.
Ensure that your stylesheet h2 declaration is valid with a semicolon and closing brace.
Make sure all your style elements are valid and have a closing tag.

1
​
2
<h2 style="color: red">CatPhotoApp</h2>
3
​
4
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
5
​Can someone please help me?

**Comment by raisedadead** [comment]
Hi @Knotttieboy 

Closing as a coding help issue, as noted by our bot. Please proceed to the chat room.
Happy Coding!
