### ISSUE TITLE
Test passing but should not.

### ISSUE THREAD

**Issue by timmyconnect** [FreeCodeCamp/FreeCodeCamp#1243]
Challenge http://www.freecodecamp.com/challenges/bonfire-no-repeats-please has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

As per screenshot. The test fails from the get go. It marks correct with string and numbers.

<img width="479" alt="screen shot 2015-07-10 at 11 59 48 am" src="https://cloud.githubusercontent.com/assets/6411774/8616398/4d19edf2-26fb-11e5-8083-79637cbdbec6.png">

**Comment by LumenTeun** [comment]
This was fixed in #958 and, from what I gather, will be in `production` soon.
