### ISSUE TITLE
Manipulating Complex Objects

### ISSUE THREAD

**Issue by clewman** [FreeCodeCamp/FreeCodeCamp#12434]
#### Manipulating Complex Objects
https://www.freecodecamp.com/challenges/manipulating-complex-objects#?solution=%0Avar%20myMusic%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Billy%20Joel%22%2C%0A%20%20%20%20%22title%22%3A%20%22Piano%20Man%22%2C%0A%20%20%20%20%22release_year%22%3A%201973%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CS%22%2C%20%0A%20%20%20%20%20%20%228T%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%0A%20%20%20%20%22gold%22%3A%20true%0A%20%20%7D%0A%20%20%2F%2F%20Add%20record%20here%0A%5D%3B%0A%0A
#### Issue Description
In the original code, there is no comma on line 12. Without this comma, the code doesn't run. You are not supposed to manipulate any code above line 13, so it took me quite a while to figure out why my code wasn't working. I found another "issue" someone posted, but one of the moderators misunderstood and said that you don't really need the comma. That's not the point, you can't move on unless you put it in, regardless of JS etiquette. 

* Browser Name, Version: Chrome
* Operating System:  WIN 10
* Mobile, Desktop, or Tablet:  Laptop

#### Your Code

var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  },           **(NOTE: this is line 12 and in the original, there is no comma)**
  // Add record here
{
  artist: "David Bowie",
  title: "Blackstar",
  release_year: 2016,
  formats: [
    "CD",
    "LP"
  ]
}
];
```js
 
 
 
```

**Comment by raisedadead** [comment]
Hi @clewman please double check the instructions.

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding!

**Comment by clewman** [comment]
Please recheck, this IS a bug! It says not to put code before line 13, the
comma is on line 12. I don't have an issue with my code, it worked and I
got passed it, but I had to enter a comma on line 12 -- WHERE I'M NOT
SUPPOSED TO PUT CODE! Or, the note on line 13 shouldn't say to start
putting code there, if you want folks to manipulate line 12.

Best,
Cheryl


"*A dreamer is one who can only find his way by moonlight, and his
punishment is that he sees the dawn before the rest of the world." -Oscar
Wilde*

**Comment by raisedadead** [comment]
@clewman once again, please double check the instructions and proceed to help chat, confirm from others if this is a bug.

If you look the instruction:

> **Note**
> You will need to place a comma after every object in the array, unless it is the last object in the array.

And in the editor it says:
```js
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  }
  // Add record here
];
```

It does not say, you can edit the code only after that comment `// Add record here`
If you **carefully** read the instructions once again, hopefully, you will get this easily.

Once again, before reporting any issue, confirm that others are facing this as well, and it's actually a bug, in this case, it's just a bit of misunderstanding the instructions. 

Happy coding!

**Comment by clewman** [comment]
Well, considering that most of the examples are very clear about only
entering code in certain places, it seems "tricky" to say, "Add record
here" and then assume that we're going to go against what we've been doing
for the last 100 exercises and go above that to make changes. There must be
a more clear way of putting it. Sorry, I've been teaching (college level)
for the last 15 years, so I'm big on education and very clear instructions.
You should never make assumptions when it comes to education.

Best,
Cheryl


"*A dreamer is one who can only find his way by moonlight, and his
punishment is that he sees the dawn before the rest of the world." -Oscar
Wilde*

On Sun, Jan 8, 2017 at 11:05 PM, mrugesh mohapatra <notifications@github.com

**Comment by clewman** [comment]
And I realize that I sound very argumentative, it's just that I would never
intentionally try to trick my students like this, and it seemed to me like
it was a mistake not intentional. If it's intentional, then, well, you and
I have different teaching philosophies and I guess we need to leave it at
that.

Best,
Cheryl


"*A dreamer is one who can only find his way by moonlight, and his
punishment is that he sees the dawn before the rest of the world." -Oscar
Wilde*

**Comment by raisedadead** [comment]
Hey Cheryl, 

Please accept my sincere apologies if I was misunderstood. We are open to adapting to changes, but just clarify, my closing the issue, this tracker is for taking bug reports objectively, we do not intend to mislead in any way. 

Hence have added the note in the instructions because of similar reports in the past.

We would love to hear your feedback and improvement to the challenge given your experience 😅 in teaching!

Can you help us with any specific changes that you would like to see?
You can reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), or [hit me up](https://gitter.im/raisedadead) as well.

Cheers, and Happy Coding!
