### ISSUE TITLE
GLOBAL SCOPE AND FUNCTIONS (BUG)

### ISSUE THREAD

**Issue by RomingArt** [FreeCodeCamp/FreeCodeCamp#12435]
Challenge [Global Scope and Functions](https://www.freecodecamp.com/challenges/global-scope-and-functions#?solution=%0Avar%20myGlobal%20%3D%2010%3B%20%2F%2F%20Declare%20your%20variable%20here%0A%0A%0Afunction%20fun1()%20%7B%0A%20%20oppsGlobal%20%3D5%3B%20%2F%2F%20Assign%205%20to%20oopsGlobal%20Here%0A%20%20%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0Afunction%20fun2()%20%7B%0A%20%20var%20output%20%3D%20%22%22%3B%0A%20%20if%20(typeof%20myGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22myGlobal%3A%20%22%20%2B%20myGlobal%3B%0A%20%20%7D%0A%20%20if%20(typeof%20oopsGlobal%20!%3D%20%22undefined%22)%20%7B%0A%20%20%20%20output%20%2B%3D%20%22%20oopsGlobal%3A%20%22%20%2B%20oopsGlobal%3B%0A%20%20%7D%0A%20%20console.log(output)%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myGlobal = 10; // Declare your variable here


function fun1() {
  oppsGlobal =5; // Assign 5 to oopsGlobal Here
  
}

// Only change code above this line
function fun2() {
  var output = "";
  if (typeof myGlobal != "undefined") {
    output += "myGlobal: " + myGlobal;
  }
  if (typeof oopsGlobal != "undefined") {
    output += " oopsGlobal: " + oopsGlobal;
  }
  console.log(output);
}

```
This code should be correct or am I writing the code wrong it could also be an issue of space in the code can someone check it out please.

**Comment by Manish-Giri** [comment]
@RomingArt The instruction says -
> Inside function fun1, assign 5 to oopsGlobal without using the var keyword

And your variable name is -
`oppsGlobal =5; `

See the mistake?

Pls visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) if you need help with challenges like these. Happy Coding!

**Comment by RomingArt** [comment]
@Manish-Giri  thank you very much I just seen my issue as well thank you again.

**Comment by erictleung** [comment]
Closing as resolved. Happy coding!
