### ISSUE TITLE
No global variables, pass all the tests and not working.

### ISSUE THREAD

**Issue by GabrielAmazonas** [FreeCodeCamp/FreeCodeCamp#12448]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Afunction%20titleCase(str)%20%7B%0A%20%20var%20oldArrayLetters%20%3D%20str.split('')%3B%0A%20%20var%20oldArrayWords%20%3D%20str.split('%20')%3B%0A%20%20var%20newArray%20%3D%20%5B%5D%3B%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20oldArrayWords.length%3B%20i%2B%2B)%7B%0A%20%20%20%20newArray.push(oldArrayWords%5Bi%5D.split('')%5B0%5D.toUpperCase())%3B%0A%20%20%20%0A%20%20%20%20for(var%20j%20%3D%201%3B%20j%3ColdArrayWords%5Bi%5D.split('').length%3B%20j%2B%2B)%7B%0A%20%20%20%20%20%20newArray.push(oldArrayWords%5Bi%5D.split('')%5Bj%5D.toLowerCase())%3B%0A%20%20%20%20%7D%0A%20%20%20%20newArray.push('%20')%3B%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20return%20newArray.join(%22%22)%3B%0A%7D%0A%0AtitleCase(%22sHoRt%20AnD%20sToUt%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function titleCase(str) {
  var oldArrayLetters = str.split('');
  var oldArrayWords = str.split(' ');
  var newArray = [];
  for(var i = 0; i < oldArrayWords.length; i++){
    newArray.push(oldArrayWords[i].split('')[0].toUpperCase());
   
    for(var j = 1; j<oldArrayWords[i].split('').length; j++){
      newArray.push(oldArrayWords[i].split('')[j].toLowerCase());
    }
    newArray.push(' ');
    
  }
  
  
  return newArray.join("");
}

titleCase("sHoRt AnD sToUt");

```

**Comment by suhussai** [comment]
Hey @GabrielAmazonas, there seems to be an issue with your code. It's a bit subtle. 

Look at this test for example: 
```
titleCase("sHoRt AnD sToUt")
```
which expects 
```
"Short And Stout"
```
Your implementation returns something similar, but not exactly the same. If you highlight the output of your code, it looks something like this:
```
"Short And Stout " // <--- Notice the extra space.
```
That extra space character originates from this line: `newArray.push(' ');`.

**Comment by GabrielAmazonas** [comment]
@suhussai Thanks for the fast reply! 

Sorry for the opened issue without needing.


Spoiler Alert:
Here's the entire solution :


```
function titleCase(str) {
  var oldArrayLetters = str.split('');
  var oldArrayWords = str.split(' ');
  var newArray = [];
  for(var i = 0; i < oldArrayWords.length; i++){
    newArray.push(oldArrayWords[i].split('')[0].toUpperCase());
   
    for(var j = 1; j<oldArrayWords[i].split('').length; j++){
      newArray.push(oldArrayWords[i].split('')[j].toLowerCase());
    }
    
    if((oldArrayWords.length - 1) !== i)
    newArray.push(' ');
    
  }
  
  
  return newArray.join("");
}

titleCase("I'm a little tea pot");

```
