### ISSUE TITLE
Codepen's Portfolio images are missing

### ISSUE THREAD

**Issue by hallaathrad** [freeCodeCamp/freeCodeCamp#12447]
There's been a new set of issues with the images on the portfolio pen @ codepen.
The problem roots in the hotlink protection I've implemented in my server to avoid broadband overcharge for the images I sometimes update on the portfolio. 

The current htaccess file allows for the appropriate user accounts to get access to the images, but it seems codepen has implemented some sort of buffer or safety feature that masks the user name while making external requests, and this is resulting in conflict with the specific hotlink allowance.

I've already reached out to codepen, trying to get some assistance from them to solve this issue.
Will update as soon as I get an answer. Else, I'll host the images on a different server (github?) and have them be linked from there.

**Comment by raisedadead** [comment]
> I'll host the images on a different server (github?)

This should be a good idea in my opinion, instead of having a bandwidth usage on your personal server.

**Comment by texas2010** [comment]
@hallaathrad, it is good idea to use github pages. 

I agree with @raisedadead.

**Comment by hallaathrad** [comment]
After putting some thought into this, I've remembered why I'd blocked hotlinking to begin with: Last year I've found some dude using my images as part of their actual portfolio (not FCC related).

The current setting lets any codepen user (mostly learners); that should be good enough. I do want FCC people to have them available for their learning process.
