### ISSUE TITLE
Escaping Literal Quotes in Strings

### ISSUE THREAD

**Issue by beyflow** [FreeCodeCamp/FreeCodeCamp#12445]
This is my code. It is correct. Reporting a bug 

`var myStr = "I am a \"double quoted \"string inside \"double quotes\".";`
`

Escaping Literal Quotes in Strings
[](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%20%3D%20%22I%20am%20a%20%5C%22double%20quoted%20%5C%22string%20inside%20%5C%22double%20quotes%5C%22.%22%3B%2F%2F%20Change%20this%20line%0A%0A%0A)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by raisedadead** [comment]
@beyflow I am afraid the code is not completely correct. You are very very close though.

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding!
