### ISSUE TITLE
Add 'use strict' in the instructions

### ISSUE THREAD

**Issue by forkerino** [freeCodeCamp/freeCodeCamp#12441]
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions) 

I suggest to include a brief description of the 'use strict' in the instructions. There are regularly people coming into the gitter /helpJavascript room that assign 'use strict' to myVar. There are even people suggesting others to use this as a solution, furthering the confusion.

**Comment by dhcodes** [comment]
I agree 👍
