### ISSUE TITLE
Pig Latin bug "glove" should return love + g + ay  it says it's not correct expects oveglay

### ISSUE THREAD

**Issue by dumitriucristian** [FreeCodeCamp/freeCodeCamp#12457]
Challenge [Pig Latin](https://www.freecodecamp.com/challenges/pig-latin#?solution=function%20translatePigLatin(str)%20%7B%0A%20%20var%20vowel%20%3D%20%5B'a'%2C'e'%2C'i'%2C'o'%2C'u'%5D%3B%0A%20%20var%20firstLetter%20%3D%20str%5B0%5D%3B%0A%20%20%0A%20%20if(%20vowel.indexOf(firstLetter)%20%3E%20-1%20)%7B%0A%20%20%20%20%2F%2Fit's%20a%20vowel%0A%20%20%20%20var%20word%20%3D%20str%20%2B%20%22way%22%3B%0A%0A%20%20%7Delse%7B%0A%20%20%20%20%2F%2Fit's%20a%20consonant%0A%20%20%20%20var%20word%20%3D%20str.split('')%3B%0A%20%20%20%20word.shift()%3B%0A%20%20%20%20word%20%3D%20word.join('')%3B%0A%20%20%20%20word%20%3D%20word%2BfirstLetter%2B%22ay%22%3B%0A%20%20%20%20console.log(word)%3B%0A%0A%20%20%7D%0A%0A%20%2F%2F%20console.log(firstLetter)%3B%0A%20%20return%20word%3B%0A%7D%0A%0AtranslatePigLatin(%22glove%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function translatePigLatin(str) {
  var vowel = ['a','e','i','o','u'];
  var firstLetter = str[0];
  
  if( vowel.indexOf(firstLetter) > -1 ){
    //it's a vowel
    var word = str + "way";

  }else{
    //it's a consonant
    var word = str.split('');
    word.shift();
    word = word.join('');
    word = word+firstLetter+"ay";
    console.log(word);

  }

 // console.log(firstLetter);
  return word;
}

translatePigLatin("glove");
```

**Comment by dumitriucristian** [comment]
The request is: translatePigLatin("glove") should return "oveglay".
To return oveglay it should be loveg.

**Comment by raisedadead** [comment]
@dumitriucristian Thanks for the report.

Okay, just to clarify, I think the instructions are saying:
> takes the first consonant **(or consonant cluster)** of an English word, moves it to the end of the word and suffixes an "ay".

Here the in test case *gl* is a cluster:
> translatePigLatin("glove") should return "oveglay".

and hence would be moved to the end, making it `ove + gl + ay`.

Happy coding!

**Comment by 5ubz3r0** [comment]
Hi
I'd like to know whether there is a smarter way other than just listing all constant clusters to do this- there're about 100 (http://www.enchantedlearning.com/consonantblends/)
thanks
