### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by SarahMarie73** [FreeCodeCamp/freecodecamp#1245]
I'm stuck on Varialble in jQuery
http://www.codecademy.com/courses/web-beginner-en-GfjC6/0/3

How do I assign it to the selector that represents number 4?

**Comment by LumenTeun** [comment]
The GitHub issues are not for support, please use [RSAP](http://www.freecodecamp.com/field-guide/how-do-i-get-help-when-i-get-stuck) when you need help. Good luck and remember to close this.
