### ISSUE TITLE
Do not change the order of the h1 h2 or p in the code. I need an explaination.

### ISSUE THREAD

**Issue by L05tArT** [freeCodeCamp/freeCodeCamp#12454]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by erictleung** [comment]
@L05tArT thanks for the issue. Can you give more information about your issue? Which challenge are you working on? If you need coding help, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help).

**Comment by raisedadead** [comment]
Please share more information.
