### ISSUE TITLE
Bonfire #16 Will pass all criteria without testing full objects /w values

### ISSUE THREAD

**Issue by JohnSeabourn** [FreeCodeCamp/FreeCodeCamp#1246]
I initially wrote some code that passed all of the tests but was technically incorrect.  If you just test the values of source keys against collection keys, it will pass and move on.  The test needs to change to ensure that the key values are also being tested. 

i.e.  If I have [ [{ first: 'John', last: 'Smith' }, { first: 'Jane', last: 'Doe' }], { last: 'Doe' } ] and test the value of 'Doe' against everything it will push the second object to an array.

The test can be fooled if i change the key value of source to anything else because it is just checking for a key value i.e:

[ [{ first: 'John', last: 'Smith' }, { first: 'Jane', last: 'Doe' }], { whatever: 'Doe' } ]

The test itself should have changed values to make sure that the user does not just test key values but also key names as well.

**Comment by LumenTeun** [comment]
Would you post the incorrect code that passes the tests?

**Comment by JohnSeabourn** [comment]
Took me a second to recreate the code.  Here is one that is incorrect but can pass both tests.

```javascript
function where(collection, source) {
  var arr = [];
  // What's in a name?
  for(i=0, cLength = collection.length; i < cLength; i++) {
    for(var keys in collection[i]) {
      if(collection[i][keys] == source[keys]) {
        arr.push(collection[i]);
      }
    }  
  }
  return arr;
}

where([{ first: 'Romeo', last: 'Montague' }, { first: 'Mercutio', last: null }, { first: 'Tybalt', last: 'Capulet' }], { last: 'Capulet' });
```

**Comment by LumenTeun** [comment]
This is the first time saying this, but I'm sorry, I think your code is correct.
I tried it against a few different custom tests, your `[{ first: 'John', last: 'Smith' }, { first: 'Jane', last: 'Doe' }], { whatever: 'Doe' }` being one of them, and it returned an empty array, which I think is the correct output.

How did you find the error, if there is one?

**Comment by JohnSeabourn** [comment]
Change the key name in the source to anything you want.  It will still push the object to the array.

**Comment by JohnSeabourn** [comment]
One sec.  I know it isn't correct but I have to remember how I tested to learn this lol.

**Comment by JohnSeabourn** [comment]
Okay.  I remember how I tested and knew the code was wrong.  Here is the code that will pass but shouldn't because the test key has the same last name but a different first name.  Give me a sec to write the correct code so you can see the difference.
```
function where(collection, source) {
  var arr = [];
  // What's in a name?
  for(i=0, cLength = collection.length; i < cLength; i++)
    for(var keys in collection[i]) {
      if(collection[i][keys] == source[keys])
        arr.push(collection[i]);
    }
  return arr;
}

where([{ first: 'Romeo', last: 'Montague' }, { first: 'Mercutio', last: null }, { first: 'Tybalt', last: 'Capulet' }], { last: 'Capulet', first: 'Joesmoe' });
```

**Comment by JohnSeabourn** [comment]
Here is the correct code that tests all values to ensure that the source object is in fact a match.  I'm pretty sure this is not the most efficient but you should be able to get the correct answer everytime.

```javascript
function where(collection, source) {
  var arr = [];
  var keyArray = Object.keys(source);
  var flag = true;
  // What's in a name?
  for(i=0, cLength = collection.length; i < cLength; i++) {
    flag = true;
    for(var keys in keyArray)
      if(collection[i][keyArray[keys]] != source[keyArray[keys]])
        flag = false;

    if(flag)
      arr.push(collection[i]);
  }
  return arr;
}

where([{ first: 'Romeo', last: 'Montague' }, 
       { first: 'Mercutio', last: null }, 
       { first: 'Tybalt', last: 'Capulet' }], 
      
       { first: 'Tybalt', last: 'Capulet' });
```

You can change the source value to whatever you want and you should get the correct object push in arr.  This ensures that the object in it's entirety is a match and not just one value.

**Comment by JohnSeabourn** [comment]
Here is the example using the numbers.  I commented what the different tests I ran came to.
```javascript
function where(collection, source) {
  var arr = [];
  var keyArray = Object.keys(source);
  var flag = true;
  // What's in a name?
  for(i=0, cLength = collection.length; i < cLength; i++) {
    flag = true;
    for(var keys in keyArray)
      if(collection[i][keyArray[keys]] != source[keyArray[keys]])
        flag = false;

    if(flag)
      arr.push(collection[i]);
  }
  return arr;
}

// This will return all three objects because they match what the source is.

where([{ 'a': 1 }, 
       { 'a': 1 }, 
       { 'a': 1, 'b': 2 }], 
      
       { 'a': 1 });

/* This will return a [] because the source object is different with c key
where([{ 'a': 1 }, 
       { 'a': 1 }, 
       { 'a': 1, 'b': 2 }], 
      
       { 'a': 1, 'c': 3 });
*/
```

**Comment by JohnSeabourn** [comment]
I changed the title to better match the bug.

**Comment by benschenker** [comment]
Hey @JohnSeabourn, thanks for posting this issue with so much detail! Sorry that it slipped through the cracks.

With the recent updates to the site, the bonfires don't have numbers anymore, can you post the updated URL to the challenge?

**Comment by benschenker** [comment]
It looks like this is for http://www.freecodecamp.com/challenges/bonfire-where-art-thou

**Comment by ltegman** [comment]
A test has been added that solves this issue.

Thanks and happy coding!
