### ISSUE TITLE
Inventory update passes tests but does not show that they are passed

### ISSUE THREAD

**Issue by bhad1** [FreeCodeCamp/freeCodeCamp#12461]
Challenge [Inventory Update](https://www.freecodecamp.com/challenges/inventory-update#?solution=%0Afunction%20updateInventory(arr1%2C%20arr2)%20%7B%0A%20%20var%20updatedInv%20%3D%5B%5D%3B%0A%20%20function%20checkExistance(element%2C%20index%2C%20array)%7B%0A%20%20%20%20for(i%3D0%3Bi%3Carr2.length%3Bi%2B%2B)%7B%0A%20%20%20%20%20%20%2F%2Ffor%20each%20item%20in%20first%20array%20check%20if%0A%20%20%20%20%20%20%2F%2Fit%20matches%20in%20second%20array.%20If%20it%0A%20%20%20%20%20%20%2F%2Fdoes%20then%20add%20the%20quantities%20up%2C%0A%20%20%20%20%20%20%2F%2Fchange%20them%20to%20correct%20value%20in%20first%20array%0A%20%20%20%20%20%20%2F%2Fthen%20push%20to%20new%20array%0A%20%20%20%20%20%20if(array%5Bindex%5D%5B1%5D%20%3D%3D%20arr2%5Bi%5D%5B1%5D)%7B%0A%20%20%20%20%20%20%20%20%2F%2Fupdate%20curInv%20if%20it%20matches%0A%20%20%20%20%20%20%20%20curInv%5Bindex%5D%5B0%5D%20%3D%20curInv%5Bindex%5D%5B0%5D%20%2B%20arr2%5Bi%5D%5B0%5D%3B%0A%20%20%20%20%20%20%20%20%2F%2Fif%20it%20matches%20delete%20from%20newInv%20array%0A%20%20%20%20%20%20%20%20%2F%2Fbecause%20we%20will%20push%20entire%20array%20into%20curInv%0A%20%20%20%20%20%20%20%20%2F%2Fafterward%20to%20add%20new%20items%20to%20curInv%0A%20%20%20%20%20%20%20%20arr2.splice(i%2C1)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%0A%20%20%7D%0A%20%20%20%20curInv.forEach(checkExistance)%3B%0A%20%20%20%20%2F%2Fadd%20entire%20newInv%20array%20into%20curInv%0A%20%20%20%20updatedInv%20%3D%20curInv.concat(newInv)%3B%0A%20%20%20%20%2F%2Fsort%20alphabetically%0A%20%20%20%20updatedInv.sort(compareFunction)%3B%0A%20%20%20%20%20%20function%20compareFunction(a%2Cb)%7B%0A%20%20%20%20%20%20%20%20if(a%5B1%5D%3D%3D%3Db%5B1%5D)%7B%0A%20%20%20%20%20%20%20%20%20%20return%200%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20else%7B%0A%20%20%20%20%20%20%20%20%20%20return%20(a%5B1%5D%20%3C%20b%5B1%5D)%20%3F%20-1%3A1%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%0A%20%20%20%20return%20updatedInv%3B%0A%7D%0A%0A%2F%2F%20Example%20inventory%20lists%0Avar%20curInv%20%3D%20%5B%0A%20%20%20%20%5B21%2C%20%22Bowling%20Ball%22%5D%2C%0A%20%20%20%20%5B2%2C%20%22Dirty%20Sock%22%5D%2C%0A%20%20%20%20%5B1%2C%20%22Hair%20Pin%22%5D%2C%0A%20%20%20%20%5B5%2C%20%22Microphone%22%5D%0A%5D%3B%0A%0Avar%20newInv%20%3D%20%5B%0A%20%20%20%20%5B2%2C%20%22Hair%20Pin%22%5D%2C%0A%20%20%20%20%5B3%2C%20%22Half-Eaten%20Apple%22%5D%2C%0A%20%20%20%20%5B67%2C%20%22Bowling%20Ball%22%5D%2C%0A%20%20%20%20%5B7%2C%20%22Toothpaste%22%5D%0A%5D%3B%0A%0AupdateInventory(curInv%2C%20newInv)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function updateInventory(arr1, arr2) {
  var updatedInv =[];
  function checkExistance(element, index, array){
    for(i=0;i<arr2.length;i++){
      //for each item in first array check if
      //it matches in second array. If it
      //does then add the quantities up,
      //change them to correct value in first array
      //then push to new array
      if(array[index][1] == arr2[i][1]){
        //update curInv if it matches
        curInv[index][0] = curInv[index][0] + arr2[i][0];
        //if it matches delete from newInv array
        //because we will push entire array into curInv
        //afterward to add new items to curInv
        arr2.splice(i,1);
      }
    }

  }
    curInv.forEach(checkExistance);
    //add entire newInv array into curInv
    updatedInv = curInv.concat(newInv);
    //sort alphabetically
    updatedInv.sort(compareFunction);
      function compareFunction(a,b){
        if(a[1]===b[1]){
          return 0;
        }
        else{
          return (a[1] < b[1]) ? -1:1;
        }
      }

    return updatedInv;
}

// Example inventory lists
var curInv = [
    [21, "Bowling Ball"],
    [2, "Dirty Sock"],
    [1, "Hair Pin"],
    [5, "Microphone"]
];

var newInv = [
    [2, "Hair Pin"],
    [3, "Half-Eaten Apple"],
    [67, "Bowling Ball"],
    [7, "Toothpaste"]
];

updateInventory(curInv, newInv);

```
I am not even getting a checkmark but I have double checked multiple times and my output passes every test. Could anyone explain?

**Comment by erictleung** [comment]
@bhad1 Thank you for reporting this issue. Your code is almost there. You reference some global variables in the `updateInventory` function that will change with every challenge test. The logic is correct, just replace some variable names and it'll pass.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on Free Code Camp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
