### ISSUE TITLE
Bootstrap challenge passed with wrong answer

### ISSUE THREAD

**Issue by alexr101** [freeCodeCamp/freeCodeCamp#12467]
Similar to issue #12426 I just fixed

Challenge ["Responsively Style Checkboxes"](https://www.freecodecamp.com/challenges/responsively-style-checkboxes ) requires to wrap exactly 3 checkboxes inside of a div.row. It passes if you wrap 1 or more checkboxes.

I can also apply this fix if you want. I just don't know how this works, so I figured I should open an issue rather than sending it with the other pull request. Is that how it's supposed to be?

Thanks!

**Comment by dhcodes** [comment]
@alexr101 yep, usually the best bet to open a new issue. In this case, since the issue is similar, you could've added a comment in the other issue thread that you found another similar case and fixed both at once, but this is fine too.

You're welcome to fix this one as well.

**Comment by alexr101** [comment]
@dhcodes thanks for your help!! I went ahead and did that for this one since i found yet another challenge with the same problem
