### ISSUE TITLE
I can no longer access Symmetric Difference to edit it

### ISSUE THREAD

**Issue by breyana** [freeCodeCamp/freeCodeCamp#12478]
Challenge [Symmetric Difference](https://www.freecodecamp.com/challenges/symmetric-difference) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Every time I attempt to open Symmetric Difference, Chrome crashes. Here is the link with the extra data

https://www.freecodecamp.com/challenges/symmetric-difference#?solution=%0Afunction%20sym(args)%20%7B%0A%20%20%2F%2Ftake%20args%2C%20make%20an%20array%0A%20%20var%20argsArray%20%3D%20%5B%5D.slice.call(arguments)%3B%0A%20%20var%20uniqueArray%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20%2F%2Fmake%20a%20function%20that%20compares%20two%20of%20the%20arrays%2C%20takes%20individual%20values%20%0A%20%20%2F%2Fand%20stores%20it%20into%20a%20new%20array%0A%20%20function%20findDiff(array1%2C%20array2)%20%7B%0A%20%20%2F%2Finside%20the%20function%3A%20compare%20array1%20to%20array2%20then%20array2%20to%20array1%20%20%0A%20%20%20%20for%20(i%3D0%3B%20i%20%3C%20array1.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20if%20(array2.indexOf(array1%5Bi%5D)%20%3C%200)%20%7B%0A%20%20%20%20%20%20%20%20uniqueArray.push(array1%5Bi%5D)%3B%0A%20%20%20%20%20%20%7D%20%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20for%20(i%3D0%3B%20i%20%3C%20array2.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20if%20(array1.indexOf(array2%5Bi%5D)%20%3C%200)%20%7B%0A%20%20%20%20%20%20%20%20uniqueArray.push(array2%5Bi%5D)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20return%20uniqueArray%3B%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%0A%20%20%2F%2Fin%20the%20end%2C%20use%20the%20reduce%20method%20to%20run%20the%20function%20through%20all%20of%20the%20elements%0A%20%20return%20args%3B%0A%7D%0A%0Asym(%5B1%2C%202%2C%203%5D%2C%20%5B5%2C%202%2C%201%2C%204%5D)%3B%0A

**Comment by erictleung** [comment]
@breyana thanks for the issue. I'm able to access your code. Try adding `run=disabled` to the end of the URL to stop a possible infinite loop. So the URL you'll want to try is

```
https://www.freecodecamp.com/challenges/symmetric-difference#?run=disabled
```

Otherwise, another suggestion would be to clear your cache. Let us know if that helps.

Source: https://forum.freecodecamp.com/t/free-code-camp-infinite-loop-protection/19550/2

**Comment by raisedadead** [comment]
Closing, let us know if you are still having an issue.
