### ISSUE TITLE
[Target HTML Elements with Selectors Using jQuery]

### ISSUE THREAD

**Issue by kyo99** [freeCodeCamp/freeCodeCamp#12471]
Challenge [Target HTML Elements with Selectors Using jQuery]

![image](https://cloud.githubusercontent.com/assets/24714529/21838624/e9358cb8-d7f4-11e6-80af-49bb9effb250.png)

Use the jQuery addClass() function to give the classes animated and bounce to your button elements.

I am using this code as you can see on image above .But still it won't pass.  
My code:
```html

<script>
  $(document).ready(function() {
  $("button").addclass("animated bounce");
  });
</script>

**Comment by Manish-Giri** [comment]
@kyo99 Your code is incorrect, `addClass` should have capital `C`.

For help with issues like these, please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) first, in future. Happy Coding!
