### ISSUE TITLE
all test Cases are trues 

### ISSUE THREAD

**Issue by Gamal9** [freeCodeCamp/freeCodeCamp#12474]
Challenge [Counting Cards](https://www.freecodecamp.com/challenges/counting-cards#?solution=%0Avar%20count%20%3D%20'0'%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%20if(card%3D%3D2%7C%7Ccard%3D%3D3%7C%7Ccard%3D%3D4%7C%7Ccard%3D%3D5%7C%7Ccard%3D%3D6)%0A%20%20%20%20%7B%0A%20%20%20%20%20return%20count%2B%2B%3B%0A%20%20%20%20%7D%20else%20if(card%3D%3D10%7C%7Ccard%3D%3D'J'%7C%7Ccard%3D%3D'Q'%7C%7Ccard%3D%3D'K'%7C%7Ccard%3D%3D'A')%0A%20%20%20%20%7B%0A%20%20%20%20%20return%20count--%3B%0A%20%20%20%20%7D%0A%20%20else%20if(card%3D%3D7%7C%7Ccard%3D%3D8%7C%7Ccard%3D%3D9)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20count%3B%0A%20%20%20%20%7D%0A%20%20%7D%0Acc(10)%3B%20cc('J')%3B%20cc('Q')%3B%20cc('K')%3B%20cc('A')%3B%0Aif(count%3E'0')%0A%20%20%7B%0A%20%20%20%20count%20%2B%3D%22%20Bet%22%3B%0A%20%20%7D%0Aelse%20if(count%3C%3D'0')%0A%20%20%7B%0A%20%20%20%20count%20%2B%3D%22%20Hold%22%3B%0A%20%20%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var count = 0;

function cc(card) {
   if(card==2||card==3||card==4||card==5||card==6)
    {
     return count++;
    } else if(card==10||card=='J'||card=='Q'||card=='K'||card=='A')
    {
     return count--;
    }
  else if(card==7||card==8||card==9)
    {
      return count;
    }
  }
cc(10); cc('J'); cc('Q'); cc('K'); cc('A');
if(count>0)
  {
    count +=" Bet";
  }
else if(count<=0)
  {
    count +=" Hold";
  }

```

**Comment by erictleung** [comment]
@Gamal9 thanks for the issue. The challenge tests run your function over and over again. Please put all the necessary functionality of your code in the `cc()` function. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
