### ISSUE TITLE
Footer Isn't Clean

### ISSUE THREAD

**Issue by ericturnerit** [FreeCodeCamp/FreeCodeCamp#1247]
When you hover over a footer item, it adds a pixel or two of background length which, on some monitors, will add a scroll bar when you're in the learn zone, typing code. Just looks messy. I may be able to fix.

**Comment by LumenTeun** [comment]
Could you link a page to where this is visible?

**Comment by ericturnerit** [comment]
http://www.freecodecamp.com/

Hover over any of the footer links, for example the "Blog" link, then scroll down and you'll see the extra bit of page that appears.

**Comment by LumenTeun** [comment]
Oh, I see what you mean now. Would you like to take a crack at it, or should I start working?

**Comment by ericturnerit** [comment]
If you don't mind, I'd like to. Just to get something goin on my github account, you know? ;)

**Comment by LumenTeun** [comment]
Sure, go ahead :) Let me know if you get stuck

**Comment by FFX01** [comment]
Went ahead and added commit #bbe5cae to remove extra padding on link hover.

**Comment by LumenTeun** [comment]
@FFX01 Putting a # in front of commits removes the link functionality.

**Comment by FFX01** [comment]
@LumenTeun Thanks for that. I'm fairly new to Github.

**Comment by ericturnerit** [comment]
Ah man, I almost had it. Thanks for fixing, though.

**Comment by LumenTeun** [comment]
Like I said in #1249, I don't think removing the padding completely is a good solution. If you can figure out how to still change the background but remove the pixel error, please try it out @ericturnerit, you still get GitHub-contributions for pull requests ;)

**Comment by ericturnerit** [comment]
I changed the footer padding size to 10px. Did I do the pull request correctly?

**Comment by FFX01** [comment]
@LumenTeun Please see my second commit: dbc4b86 . I changed the height property of the footer to a max-height property and made it 55px instead of 50. This has stopped the scroll bar from appearing and maintained the full background on hover.

**Comment by LumenTeun** [comment]
@ericturnerit I don't think you did the pull request correctly, because I'm not seeing any new ones. @ me on Gitter if you need a walkthrough :)

@FFX01 Looks like a better solution although it feels strange to have to change the {max-,}height value from `50px` to `55px`. I can't see any real negatives from it though.

**Comment by ericturnerit** [comment]
@LumenTeun I closed it since it wasn't right.

**Comment by LumenTeun** [comment]
Okay :)

**Comment by ericturnerit** [comment]
Thanks, though! I'm gonna call it quits on this. Have to go get my wisdom teeth removed. Thanks both of you!

**Comment by LumenTeun** [comment]
Haha okay, good luck!

**Comment by BerkeleyTrue** [comment]
fixed
