### ISSUE TITLE
Project view submission doesn't work

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#12487]
Steps to reproduce: try submitting a URL here: http://beta.freecodecamp.com/en/challenges/intermediate-front-end-development-projects/build-a-random-quote-machine

![](https://www.evernote.com/l/Ar8ynIfwLKJC26iEqMsyzxeZgctasJF2SB0B/image.png)

**Comment by BerkeleyTrue** [comment]
You must use a proper url. You are missing a slash after the colon.
