### ISSUE TITLE
Waypoint: Create an Ordered List Create an ordered list of the top 3 things cats hate the most.

### ISSUE THREAD

**Issue by LincT** [FreeCodeCamp/FreeCodeCamp#1248]
I didn't see anything open on this.
basically the lesson description was as follows:

"Waypoint: Create an Ordered List
Create an ordered list of the top 3 things cats hate the most."

It doesn't say to add another p class to label the second list as something cats hate, instead it looks like one is appending a numbered list to a bullet point list of things cats love

<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<p>Click here for <a href='#'>cat photos</a>.</p>

<a href='#'><img class='smaller-image thick-green-border' src='https://bit.ly/fcc-kittens'/></a>

<p>Things cats love:</p>

<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Things cats hate:</p>
<ol>
  <li>Dogs</li>
  <li>Water</li>
  <li>Fireworks</li>
  
</ol>

There's a little extra in my code to match what it sounded like the lesson wanted.

**Comment by LumenTeun** [comment]
Please wrap your code in ``` so it doesn't get interpreted as actual code.

**Comment by Sazumo** [comment]
Probably better to just add the <p>Things cats hate:</p> to the challenge seed so that campers can focus on the task relevant to the challenge -> adding a <ol> with 3 <li>

**Comment by charleswhchan** [comment]
Created PR #1385

**Comment by benschenker** [comment]
Closing this as the PR (#1385) was rejected.  Feel free to reopen if this is still an issue for you
