### ISSUE TITLE
Removed ES-Lint Rules Throwing errors during npm test

### ISSUE THREAD

**Issue by jk47** [freeCodeCamp/freeCodeCamp#12488]
#### Issue Description
I forked the repo, following the contributing.md instructions and was able to successfully start the app. When I run `npm test` I get a lot of es-lint errors. They seem to be related to eslint versioning. Do other people experience this?
 
#### Screenshot
<img width="709" alt="screen shot 2017-01-11 at 9 58 35 pm" src="https://cloud.githubusercontent.com/assets/2525359/21876487/03d3ca36-d849-11e6-9965-9cf46e899a67.png">

**Comment by raisedadead** [comment]
I can't seem to reproduce. Can you confirm, all other steps of the guide went good for you without errors?

**Comment by jk47** [comment]
Yes. This is the only spot I had trouble.

**Comment by jk47** [comment]
I also get this message when running `npm test`

`npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run" "lint-js"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! freecodecamp@0.1.0 lint-js: `eslint --ext=.js,.jsx server/ common/ config/ client/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freecodecamp@0.1.0 lint-js script 'eslint --ext=.js,.jsx server/ common/ config/ client/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the freecodecamp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint --ext=.js,.jsx server/ common/ config/ client/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freecodecamp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls freecodecamp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/johnkotz/freecodecamp/freeCodeCamp/client/sagas/npm-debug.log`

**Comment by Bouncey** [comment]
@jk47 the only thing I can suggest is deleting the `node_modules` directory and running `npm install` again

**Comment by jk47** [comment]
ended up wiping my entire local repo and re clonging to get this to work. Thanks for the help!
