### ISSUE TITLE
The code is correct and the output too, but it isn't detecting.

### ISSUE THREAD

**Issue by greenutkarsh** [freeCodeCamp/freeCodeCamp#12491]
Challenge [Repeat a string repeat a string](https://www.freecodecamp.com/challenges/repeat-a-string-repeat-a-string#?solution=%0Avar%20st%3D''%3B%0Afunction%20repeatStringNumTimes(str%2C%20num)%20%7B%0A%20%20%2F%2F%20repeat%20after%20me%0A%20%20if(num%3C0)%0A%20%20%20%20st%3D%22%22%3B%0A%20%20else%0A%20%20%20%20%7B%0A%20%20for(var%20i%3D0%3Bi%3Cnum%3Bi%2B%2B)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20st%2B%3Dstr%3B%0A%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20return%20st%3B%0A%7D%0A%0ArepeatStringNumTimes(%22abc%22%2C%204)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var st='';
function repeatStringNumTimes(str, num) {
  // repeat after me
  if(num<0)
    st="";
  else
    {
  for(var i=0;i<num;i++)
    {
      st+=str;
    }
    }
  return st;
}

repeatStringNumTimes("abc", 4);

```

**Comment by OFFLlNE** [comment]
Just your code is a little bit wrong.
Since you define var st OUTSIDE of the function, then when the function runs it has no idea what `st` is.
If you would throw that variable inside the function everything should be fine ;)

**Comment by raisedadead** [comment]
@greenutkarsh this is a known issue with global variables, refer #9199 and follow along if you wish, work around is to do all declarations in the scope of your challenge's function, unless stated explicitly.

Happy Coding!
