### ISSUE TITLE
Mismatched values 

### ISSUE THREAD

**Issue by ssiperko** [freeCodeCamp/freeCodeCamp#12493]
Challenge [Assignment with a Returned Value](https://www.freecodecamp.com/challenges/assignment-with-a-returned-value#?solution=%0A%2F%2F%20Example%0Avar%20changed%20%3D%200%3B%0A%0Afunction%20change(num)%20%7B%0A%20%20return%20(num%20%2B%205)%20%2F%203%3B%0A%7D%0A%0Achanged%20%3D%20change(10)%3B%0A%0A%2F%2F%20Setup%0Avar%20processed%20%3D%200%3B%0A%0Afunction%20processArg(num)%20%7B%0A%20%20return%20(num%20%2B%202)%20%2F%205%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Aprocessed%20%3D%20processArg(8)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var changed = 0;

function change(num) {
  return (num + 5) / 3;
}

changed = change(10);

// Setup
var processed = 0;

function processArg(num) {
  return (num + 2) / 5;
}

// Only change code below this line

processed = processArg(8);

```
The assignment asks to assign the function to processed with an argument of 7, but only an argument of 8 will return the value of 2. Am I correct?

**Comment by Manish-Giri** [comment]
@ssiperko Did you change the `return` statement in the `processArg` function? Because when I hit "reset", I find this - 
```
function processArg(num) {
  return (num + 3) / 5;
}
```
so passing in `7` as `num` would return `2`, as is stated in the requirement.

**Comment by ssiperko** [comment]
Right you are. I refreshed my page but forgot to reset the code. 

Thank you, Manish-Giri.
