### ISSUE TITLE
Italian translation of Getting Started

### ISSUE THREAD

**Issue by jlouiss** [freeCodeCamp/freeCodeCamp#12498]
- [x] Configure your Code Portfolio (update)
- [x] Read Coding News on our Medium Publication

**Comment by Marmiz** [comment]
Hi @jlouiss can you please tell me the context (or where to find) the first string?

"configure" in italian can be translated into different ways regarding of the context.
Anyway here's a translation for those:

- [ ] Configura il tuo portfolio da programmatore (aggiornato)

- [ ] Leggi novità sul mondo della programmazione sulle nostre Pubblicazioni Medium

**Comment by raisedadead** [comment]
@jlouiss @Marmiz We have moved our translation issues to a tracker here:
https://github.com/FreeCodeCamp/translationexpansion

Please re-open or work on existing issues on that tracker. Pull requests are still to be made to this repo.
