### ISSUE TITLE
There should be certain rules for the chat room.

### ISSUE THREAD

**Issue by abdulhannanali** [FreeCodeCamp/freecodecamp#125]
The chat room sometimes go way out of the major CS topics. I am just suggesting that The FCC Administration should design an honor code or some rules to keep the discussion within the limitations of certain topics such as CS, Web dev etc. 
It'll be great and will make us more progressive.

**Comment by terakilobyte** [comment]
Limiting conversation is tantamount to censorship. If someone is repeatably offensive we can take action, but it can be educational for someone to either participate in or witness a conversation on what could be a sensitive topic.

**Comment by abdulhannanali** [comment]
@terakilobyte You're totally right. Sorry my bad.
