### ISSUE TITLE
Tribute page(div container content overflows)-need help !!

### ISSUE THREAD

**Issue by nehapevekar** [freeCodeCamp/freeCodeCamp#12504]
i've added 2 elements side by side using bootstrap grid i've added a table to my page...on right side. Table content goes out of its div container when i resize my screen
 Left side element contains unordered list
 right side element contains table  

https://forum.freecodecamp.com/t/tribute-page-div-conatiner-content-overflows-need-help/75877?u=nehapevekar

https://codepen.io/nehapevekar/pen/MJymRb

**Comment by Marmiz** [comment]
Hello @nehapevekar , Sorry but this tracker is for bugs only.
For help there are the official channels that, by the look of thing you already tried to use without much success.

Sometimes when the forum get busy some questions can be overlooked.
but don't give up! Someone will come into your rescue :)

---
For the time being I just gave a quick look at your page and noticed right away that you haven't implemented the Grid system correctly:

```
<div class="container-fluid thumbnail col-xs-4 well sidebar">
```

According to Bootstrap doc:
> Rows must be placed within a .container (fixed-width) or .container-fluid (full-width) for proper alignment and padding.
Use rows to create horizontal groups of columns.
Content should be placed within columns, and only columns may be immediate children of rows.

I strongly suggest you to read Bootstrap's [official documentations](http://getbootstrap.com/css/#grid)to have a better understanding.

Happy coding ✨  and don't give up!

**Comment by nehapevekar** [comment]
thankyou @Marmiz
