### ISSUE TITLE
Add more Free Code Camp places in README.md

### ISSUE THREAD

**Issue by IsaacAbrahamson** [freeCodeCamp/freeCodeCamp#12502]
#### Proposed addition to README.md

Free Code Camp also has an awesome forum and wiki which are not mentioned with our other places (Gitter, Youtube, Medium, etc.). I propose we add links to these places in the relevant section as people viewing the repository may be interested in viewing them.

P.S. my first attempt at issue and contribution. Please instruct me in the right process if I need to change anything.

**Comment by IsaacAbrahamson** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/pull/12503

**Comment by raisedadead** [comment]
@IsaacAbrahamson thanks for pointing this out, makes sense. Can you make a PR once again, I have left you comments on the earlier one.

**Comment by IsaacAbrahamson** [comment]
@raisedadead working on it now. Still trying to learn everything, but saw an easy way to start contributing :)

**Comment by IsaacAbrahamson** [comment]
@raisedadead should I add a new pull request or reopen?

**Comment by erictleung** [comment]
@IsaacAbrahamson I don't think you'll be able to reopen the issue because it is set to pulling with your `staging` branch. So I would say make a new pull request.

**Comment by IsaacAbrahamson** [comment]
@raisedadead @erictleung new pull request submitted, how does it look?
https://github.com/freeCodeCamp/freeCodeCamp/pull/12516

**Comment by raisedadead** [comment]
Closing.
