### ISSUE TITLE
Tool report Class is not defined even after its declared and output is obtained 

### ISSUE THREAD

**Issue by chandrachood** [freeCodeCamp/freeCodeCamp#12505]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%20%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red ;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

It Reports class is not there even after its defined in the code and reflecting in the output 

" Your stylesheet should declare a red-text class and have its color set to red. "

**Comment by Manish-Giri** [comment]
@chandrachood Try removing the space between `red` and `;`.

**Comment by chandrachood** [comment]
@Manish-Giri  , Thank You Very Much It fixed the issue . Appreciate your help

**Comment by dhcodes** [comment]
Closing as resolved
