### ISSUE TITLE
Next challenge

### ISSUE THREAD

**Issue by Esetessy** [freeCodeCamp/freeCodeCamp#12511]
Has completed the challenge of adding a color red to the h2 element but it has refuse to go to the next challenge.

**Comment by erictleung** [comment]
@Esetessy thanks for the issue. Can you give us more information about your issue? Like challenge name and your code? Please fill out the issue template next time. This provides us important information to be able to help.

**Comment by samsidx** [comment]
Please refer to this issue: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/12376#issuecomment-270673036

**Comment by raisedadead** [comment]
Closing, please help us with more clarification on the issue you are facing.
