### ISSUE TITLE
Fix last paragraph (editing) and feel productive today. Pair Programming Definition in Guide.

### ISSUE THREAD

**Issue by angiecan** [FreeCodeCamp/freecodecamp#1251]
Incomplete first sentence or punctuation and typos in: 

http://www.freecodecamp.com/field-guide/what-is-pair-programming-and-why-is-it-special

"By pair programming with other Free Code Camp students on our coding challenges. Eventually, you'll work with people at nonprofits to build real-life software solutions."

**Comment by LumenTeun** [comment]
I fixed/changed this in [this pull request](https://github.com/FreeCodeCamp/freecodecamp/pull/1161/files#diff-e2c0e529d37f17759118a2aeb7444b1aR207). If you think the new wording could be improved upon, keep this issue open, otherwise it's safe to close it while waiting for `staging` to be merged.

**Comment by angiecan** [comment]
Perfecto!
