### ISSUE TITLE
I tested all the numbers and it gives the right answer and doesn't complete the challenge

### ISSUE THREAD

**Issue by amrelbialy** [freeCodeCamp/freeCodeCamp#12527]
Challenge [Comparisons with the Logical Or Operator](https://www.freecodecamp.com/challenges/comparisons-with-the-logical-or-operator#?solution=%0Afunction%20testLogicalOr(val)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%0A%0A%20%20if%20(%20val%20%3C10%20%7C%7C%20val%20%3E%2020%20)%20%7B%0A%20%20%20%20return%20%22outside%22%3B%0A%20%20%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20%22inside%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestLogicalOr(25)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testLogicalOr(val) {
  // Only change code below this line



  if ( val <10 || val > 20 ) {
    return "outside";
  }

  // Only change code above this line
  return "inside";
}

// Change this value to test
testLogicalOr(25);

```

**Comment by OFFLlNE** [comment]
The issue tracker is for reporting bugs only.
Please check out JS help chatroom  [HelpJavaScript gitter](https://gitter.im/FreeCodeCamp/HelpJavaScript) 

Currently you need to return `Inside` and `Outside` instead of lowercased returns

**Comment by raisedadead** [comment]
@amrelbialy While your logic is correct, there is a typo with what the output should be.

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
