### ISSUE TITLE
Api doesn't "support" one of the user stories

### ISSUE THREAD

**Issue by Desentso** [FreeCodeCamp/freecodecamp#1252]
Challenge http://www.freecodecamp.com/challenges/zipline-stylize-stories-on-camper-news has an issue. 

So one of the user stories states that, "8. User Story: As a user, I can click a link to go directly to the post's discussion page." But the http://www.freecodecamp.com/stories/hotStories API doesn't support it. I mean that it doesn't provide any link to the discussion. So I think it's quite hard to get the discussion link if the API doesn't give any link to the discussion. 

How to reproduce:
1. Go to http://www.freecodecamp.com/stories/hotStories
2. Check for any links to discussion
3. Find nothing

**Comment by LumenTeun** [comment]
Close this issue and take a look at the `storyLink` key ;)

**Comment by Desentso** [comment]
Atleast for me the storyLink key only has the headline stored again. How that helps me to get to the discussion page?

**Comment by LumenTeun** [comment]
If you look at how the discussion page is reached, you can probably figure out how the `storyLink` value can be used to access the relevant page.
