### ISSUE TITLE
Make Object Properties Private

### ISSUE THREAD

**Issue by Prateekmedy** [freeCodeCamp/freeCodeCamp#12524]
#### Challenge Name

Make Object Properties Private

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
var Car = function() {
  // this is a private variable
  var speed = 10;

  // these are public methods
  this.accelerate = function(change) {
    speed += change;
  };

  this.decelerate = function() {
    speed -= 5;
  };

  this.getSpeed = function() {
    return speed;
  };
};

var Bike = function() {

  // Only change code below this line.
  var gear=0;
  
  this.setGear = function(set){
    gear += set;
  };
  
  this.getGear = function(){
    return gear;
  };
};

var myCar = new Car();

var myBike = new Bike(); 
```
#### Screenshot

![screenshot 11](https://cloud.githubusercontent.com/assets/22986515/21955478/e8dccbd8-da91-11e6-8dc1-2097a591389b.png)

**Comment by OFFLlNE** [comment]
I would say this goes into HelpJavaScript gitter helproom.
When you console.log(gear) at setGeat function then I can see that it keeps adding your gear up and it does not reset it.

Not an issue of FCC

**Comment by raisedadead** [comment]
@Prateekmedy Why are you incrementing the gear? Request you to reach out to the chat rooms.

**Comment by mrmourad** [comment]
gear = set

**Comment by jowelhakim** [comment]
Yes
