### ISSUE TITLE
Please help with this. Between the style tags, give the p elements font-size of 16px. Browser and Text zoom should be at 100%.

### ISSUE THREAD

**Issue by Igys** [freeCodeCamp/freeCodeCamp#12525]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by Igys** [comment]
@VarCI-bot. Many thanks. Still learning, How do  I close  the issue?

**Comment by OFFLlNE** [comment]
At the bottom next to "comment" it should have "Close issue"

**Comment by Igys** [comment]
Thank you
