### ISSUE TITLE
Escape sequences in strings don't work

### ISSUE THREAD

**Issue by johnnydemol** [freeCodeCamp/freeCodeCamp#12526]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22Firstline%5Cn%5C%5CSecondline%5C%5C%5CrThirdline%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "Firstline\n\\Secondline\\\rThirdline";

Output: myStr = "Firstline\n\\Secondline\\\rThirdline";

```

It's not escaping, pretty annoying since I can't pass now. I tested this code in a different challenge (Escaping literal quotes in strings) and it worked.

**Comment by OFFLlNE** [comment]
The issue tracker is for reporting bugs only.
Please check out JS help chatroom  [HelpJavaScript gitter](https://gitter.im/FreeCodeCamp/HelpJavaScript) 

But to help you out is that you need upperCase L in your code.
something like that `"FirstLine\n\\SecondLine\\\rThirdLine"`

**Comment by ooade** [comment]
You only have issues with the cases, `Firstline` should be `FirstLine` and so...
The issue tracker is for reporting bugs only.
Please check out the [HelpJavaScript](https://gitter.im/FreeCodeCamp/HelpJavaScript) gitter room next time.

**Comment by raisedadead** [comment]
Hi @johnnydemol You are almost there.

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!

**Comment by Rachoor** [comment]
myStr= "firstline'\n''\\'secondline'\\''\r''\n'ThirdLine"; it is working on the browser but showing error on the and it has bug
