### ISSUE TITLE
Issue: Target the same element with multiple jQuery selectors - won't RUN

### ISSUE THREAD

**Issue by CapnRichard** [freeCodeCamp/freeCodeCamp#12529]
#### Challenge Name

https://www.freecodecamp.com/challenges/target-the-same-element-with-multiple-jquery-selectors

#### Issue Description

I've refreshed the browser, cleared the code and every time I try to RUN it - nothing happens. I'm fairly certain my code is correct, but it just won't RUN and so I cannot get credit for completion.

#### Browser Information

* Browser Name, Version: Chrome Version 55.0.2883.87 m
* Operating System: Windows 7 Home Premium SP1
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js
 
 
 
```

**Comment by CapnRichard** [comment]
No error messages. When I try to clear the code, the error messages appear
but then my code is gone. I retype it, same thing. When I click run, no
error messages. I will post my code later. I'm on my phone right now.

Aloha,

Richard Ingalls, BSEd.

**Comment by CapnRichard** [comment]
Here is my code:


<script>
  $(document).ready(function() {
     $("#target1").AddClass("animated");
     $("#target1").AddClass("shake");
     $("#target1").AddClass("btn-primary");
  });
</script>



<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target"
id="target1">#target1</button>
        <button class="btn btn-default target"
id="target2">#target2</button>
        <button class="btn btn-default target"
id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target"
id="target4">#target4</button>
        <button class="btn btn-default target"
id="target5">#target5</button>
        <button class="btn btn-default target"
id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

**Comment by OFFLlNE** [comment]
Yeap, more of a false code thing, NOT a bug.

You should try to use helprooms if your code seems correct and is not running, people there usually know what might be up.
[CSS/HTML Help](https://gitter.im/FreeCodeCamp/Help)
[JS Help](https://gitter.im/FreeCodeCamp/HelpJavaScript)

Currently your instructions tell you to:
Add the animated class to all elements with type button.
Add the shake class to all the buttons with class \.btn.
Add the btn-primary class to the button with id \#target1.
You are adding all to \#target1

**Comment by systimotic** [comment]
Hi @CapnRichard!
As @OFFLlNE mentioned, there are some issues with your code that prevent it from running.
@OFFLlNE gave some good hints on how to pass the tests. Another thing to keep in mind is that Javascript is case-sensitive, meaning that contrary to HTML, where you put upper and lower case letters matters.

As also mentioned before, if you have trouble passing a challenge, the help rooms linked above is where you want to go. You can also get there by clicking the "Help" button on the challenge.

Happy coding!

**Comment by CapnRichard** [comment]
It doesn't matter what I put in for my targets, when I click RUN nothing
happens. There is NO text underneath with red or green to indicate what is
correct or incorrect about my code. See the attached screen shot.

[image: Inline image 1]

**Comment by CapnRichard** [comment]
Sorry - the ATTACHED screen shot, not the one that I accidentally copied
into the email

**Comment by CapnRichard** [comment]
so its the Case Sensitive issue with my .AddClass Sorry. Thanks

**Comment by CapnRichard** [comment]
Case SeNsiTivE - DOH! thanks

**Comment by Johnishaya** [comment]
here is the code:
<script>
  $(document).ready(function() {

  $("button").addClass("animated");
     $(".btn").addClass("shake");
     $("#target1").addClass("btn-primary");
  });
</script>

**Comment by texas2010** [comment]
@Johnishaya 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
