### ISSUE TITLE
What did I do wrong? 

### ISSUE THREAD

**Issue by bubashpara** [freeCodeCamp/freeCodeCamp#12539]
Challenge [Size your Images](https://www.freecodecamp.com/challenges/size-your-images) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .smaller-image {
    width: 100px;
  }
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by bubashpara** [comment]
CSS has a property called width that controls an element's width. Just like with fonts, we'll use px (pixels) to specify the image's width.

For example, if we wanted to create a CSS class called larger-image that gave HTML elements a width of 500 pixels, we'd use:

<style>
  .larger-image {
    width: 500px;
  }
</style>
Create a class called smaller-image and use it to resize the image so that it's only 100 pixels wide.

Note
Due to browser implementation differences, you may need to be at 100% zoom to pass the tests on this challenge.

Run tests (ctrl + enter)
Reset	Help	Bug
Your img element should have the class smaller-image.
Your image should be 100 pixels wide. Browser zoom should be at 100%.

**Comment by OFFLlNE** [comment]
Issue tracker is for reporting bugs.
Use a [CSS/HTML helproom](https://gitter.im/FreeCodeCamp/Help)
You are not applying smaller-image class to you image

**Comment by raisedadead** [comment]
Hi @bubashpara 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!

**Comment by bubashpara** [comment]
Thank you.

**Comment by naga-socks** [comment]
Forum help - freeCodeCamp solution
HTML5 and CSS - Size your Image
Front End Development Certification 

Explanation: You need to create class in "styles" and "img", as shown in lines 27 and 34

FYI, Rafase282 has a great forum with all the solutions, site below in comments
"https://github.com/Rafase282/My-FreeCodeCamp-Code/wiki/HTML-&-CSS"

![image](https://user-images.githubusercontent.com/29176808/27386798-e471838c-5664-11e7-9b73-8ca0a40b68d8.png)

Happy coding!

**Comment by dhcodes** [comment]
@naga-socks please don't post code help on the issues threads.

**Comment by naga-socks** [comment]
@dhcodes Got it, sorry about that! I'm new and still learning how to contribute effectively to these forums.

**Comment by texas2010** [comment]
@naga-socks, if you want to help people. please go to freeCodeCamp chat rooms or freeCodeCamp forum.
You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

These GitHub Issues are for reporting bugs on the freeCodeCamp website only.

happy coding.
