### ISSUE TITLE
Nest an Anchor Element within a Paragraph

### ISSUE THREAD

**Issue by kmq177** [freeCodeCamp/freeCodeCamp#12536]
#### Challenge Name

Nest an Anchor Element within a Paragraph

#### Browser Information

* Browser Name, Version: crome
* Operating System: 
 Desktop: windos-7

 
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p>View more &nbsp; 
<a href="http://www.freecatphotoapp.com"> cat photos </a>
</p>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by kmq177** [comment]
i could not pass the challenge. please help me out!

**Comment by kmq177** [comment]
![image](https://cloud.githubusercontent.com/assets/25130308/21962103/34604390-db47-11e6-8c45-cf91ca5103f3.png)

**Comment by OFFLlNE** [comment]
Issue tracker is for reporting bugs.
Use a [CSS/HTML helproom](https://gitter.im/FreeCodeCamp/Help)
Where I have tried to help you last 20 minutes
that &nbsp is definitely not needed there

**Comment by kmq177** [comment]
as they told me to keep blank space ,so i used it .

**Comment by systimotic** [comment]
Hi @kmq177! Thank you for reporting this issue.

Your code seems to work fine for me, both with and without the `&nbsp;`. As @OFFLlNE mentioned, the `&nbsp;` is not required.

Here are a couple suggestions:
1. Reload the page and run the tests again. A script may have crashed, preventing the tests from running.
2. Try the challenge in incognito mode. A plugin might be interfering with the tests.
3. Try the challenge in a different browser. There may be an issue with your version of Chrome.

Please try these things in order and let us know what did and didn't work. I can't reproduce your issue right now, so any extra information will be helpful in finding out what's causing your issue.

**Comment by kmq177** [comment]
I solve it just using <br> tag.
Thanks a lot for helping me.

**Comment by systimotic** [comment]
@kmq177 I'm glad you figured it out! Happy coding!

**Comment by no0bmustdie** [comment]
where did u put the <br> ? im having the same problem

**Comment by OFFLlNE** [comment]
@no0bmustdie 
Use a [CSS/HTML helproom](https://gitter.im/FreeCodeCamp/Help) to ask for help
