### ISSUE TITLE
Community dropdown styling in night mode

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/freeCodeCamp#12538]
#### Issue Description
In https://github.com/freeCodeCamp/freeCodeCamp/pull/12288, a dropdown was added to the navigation. While checking out https://github.com/freeCodeCamp/freeCodeCamp/pull/12532, I noticed that this dropdown is very bright in night mode. I think it can use some styling updates.

I believe the changes should be made [somewhere around here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/client/less/main.less#L1068).

Does anybody have any ideas on what it should look like, specifically what colours it should use?
/cc @QuincyLarson @freeCodeCamp/moderators 

#### Screenshot
![firefox_2017-01-15_15-14-22](https://cloud.githubusercontent.com/assets/7262039/21963144/582c8c6e-db35-11e6-8782-bf5c881b5c40.png)
![firefox_2017-01-15_15-14-31](https://cloud.githubusercontent.com/assets/7262039/21963143/582c268e-db35-11e6-8943-1756b71ba872.png)

**Comment by hallaathrad** [comment]
Hmm How about we try the opposite? keep the dark grey, using the light one for the text itself?

**Comment by raisedadead** [comment]
Agreed with Justin, and the specific color codes can be taken from here
https://www.freecodecamp.com/design-style-guide/

**Comment by no-stack-dub-sack** [comment]
Hey guys also, what about this:
![image](https://cloud.githubusercontent.com/assets/18563015/21965286/a87fcba0-db2a-11e6-9b6c-64cef5fbe1d3.png)

**Comment by raisedadead** [comment]
Yup.. I agreed both should be fixed. But keep in mind that this modal is not available on staging anymore.

**Comment by systimotic** [comment]
@no-stack-dub-sack You can go ahead with fixing the dropdown 👍
Might be best to leave the modal, as it's being removed anyway.

**Comment by systimotic** [comment]
😕 I just checked, and the modal is available on staging. I guess this was reverted. I'm not sure what the status on that is, whether it's back temporarily or permanently.
It was reverted in https://github.com/freeCodeCamp/freeCodeCamp/pull/11253. From what I can tell it's back permanently, but I'm not certain.

**Comment by no-stack-dub-sack** [comment]
@systimotic Ok, so I can go ahead and fix both - and if it ends up being removed - no biggie!

**Comment by no-stack-dub-sack** [comment]
@raisedadead 
> Agreed with Justin, and the specific color codes can be taken from here
https://www.freecodecamp.com/design-style-guide/

This actually raises two good points:
1. Many of the night mode colors are definitely NOT in this style guide, and
2. There are several instances of "Free Code Camp" in this style guide, which should be changed per issue #12472 

However, I cannot find this in the codebase, does anyone know where this lives?

**Comment by no-stack-dub-sack** [comment]
Ok, so I got something cooked up that I think looks nice and uses nightmode/brand colors, including fixing the [focus style issue](#issuecomment-272775791) of the buttons in the navbar:
![image](https://cloud.githubusercontent.com/assets/18563015/21976272/17032242-db9f-11e6-8181-1ea5476becae.png)

And here's the dropdown:
![image](https://cloud.githubusercontent.com/assets/18563015/21976367/720cc63e-db9f-11e6-800f-60da9d77fc94.png)
![image](https://cloud.githubusercontent.com/assets/18563015/21976398/9a6d5a9e-db9f-11e6-874e-a8b4f760f137.png)

BUT, when I started clicking around, for instance, going to the shop, then coming back to the map, the styling reverts back to the light colors. The page momentarily goes back to "day mode", then when it settles back to night mode, the dropdown styles have reverted. Any ideas as to why this might be? 

Here's my code, insert at line 1073 of main.less: 
```css
.hamburger-dropdown {
    .dropdown .dropdown-menu,
    .open a {
      background-color: @gray;
      a {
        color: @night-text-color;
        &:hover {
          background-color: #666;
          color: @brand-primary;
        }
      }
    }
    a:focus,
    a:active {
      background-color: #666 !important;
      color: @brand-primary !important;
    }
  }
```
The modals - I worked on this a bit, but they come with a whole slew of other problems that I'm too tired to get into now. Because there's also the "Bug" modal...

**Comment by raisedadead** [comment]
> There are several instances of "Free Code Camp" in this style guide

I have PR pending merge. Ref https://github.com/freeCodeCamp/design-style-guide/pull/7

I like what you have done with the drop down, maybe the text needs more contrast (more whiter), but looks coool!

**Comment by Bouncey** [comment]
That's sound to me like a react/static page issue. The shop page has not
been converted to react yet, and your preference for night mode is not
stored locally, I don't think.

Night mode selection not persisting across the site is a separate issue and
will need one raised, if someone could raise it I would be most obliged. I
don't have access to GitHub right now

**Comment by hallaathrad** [comment]
@no-stack-dub-sack not sure I'm digging the green text over the grey when hovering/active. Doesn't seem to have enough contrast to be readable. How about light grey background with dark grey text?

**Comment by no-stack-dub-sack** [comment]
@systimotic @raisedadead @hallaathrad So I think this looks a little better per Justin & Mrugesh's  comment regarding more contrast, I used the `@link-hover-color` var which is `@brand-primary` darkened by 15%, so it still keeps a hint of the brand green, but offers substantially better contrast. This is within the dropdown, and for hover, active, focus of the nav links.
![image](https://cloud.githubusercontent.com/assets/18563015/21995125/2fa9ab5c-dbf1-11e6-9009-1c2098f4f551.png)

And I think I will open a separate issue regarding the modal and will explain the difficulty with those there.

**Comment by hallaathrad** [comment]
This looks good to me.

**Comment by raisedadead** [comment]
Awesomeness!!! Lets have a Pull request already! 😉

**Comment by no-stack-dub-sack** [comment]
On it!
