### ISSUE TITLE
issue with: Condense arrays with reduce

### ISSUE THREAD

**Issue by Adubiaro** [freeCodeCamp/freeCodeCamp#12530]
Challenge [Condense arrays with reduce](https://www.freecodecamp.com/challenges/condense-arrays-with-reduce#?solution=%0Avar%20array%20%3D%20%5B4%2C5%2C6%2C7%2C8%5D%3B%0Avar%20singleVal%20%3D%200%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AsingleVal%20%3D%20array.reduce(function(a%2Cb)%20%7B%0A%20%20return%20a%20-%20b%3B%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var array = [4,5,6,7,8];
var singleVal = 0;

// Only change code below this line.

singleVal = array.reduce(function(a,b) {
  return a - b;});

```
**though i was able to get through with the challenge**.. i think there is a bug within...or i might not be understanding enough how it work.. 
altering the sign between my previousval and currentval i.e a and b. gives contradicting result...
putting the minus sign gives -22 which i think is wrong..
while a plus sign give 30 which is a correct value that passes the test
![freee](https://cloud.githubusercontent.com/assets/23186199/21958280/387e20a6-daab-11e6-8c7f-8bc7967a5650.JPG)

**Comment by OFFLlNE** [comment]
No bug here.
With `-` it is 4 - 5 - 6 - 7 - 8 = -22

**Comment by Adubiaro** [comment]
okay... thanks alot @OFFLlNE 
figured that already
