### ISSUE TITLE
color is not turning blue and code appears to be correct

### ISSUE THREAD

**Issue by gotbassoon** [freeCodeCamp/freeCodeCamp#12548]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%0A%3Cstyle%3E%0Ah2%7B%0Acolor%3A%20blue%3B%0A%7D%0A%3C%2Fstyle%3E%0A%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
h2{
color: blue;
}
</style>


<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by gotbassoon** [comment]
When I write the code in the challenge color does not turn blue, even though the code appears to be correct. Please observe attachment
![screenshot 4](https://cloud.githubusercontent.com/assets/25142554/21971952/8dd5b360-db6a-11e6-8c20-07ee55639d97.png)

**Comment by alexanderkopke** [comment]
in style you can only select what exists. So far you only have a p element but no h2. You have selected h2 in style but it should be p.

**Comment by gotbassoon** [comment]
Thanks so much!

**Comment by Teemhay** [comment]
How do i do that?.....i have also been trying to do this same element code but my text doesn't turn blue....please what code do i use to do that...thanks
