### ISSUE TITLE
Use ES6 imports consistently

### ISSUE THREAD

**Issue by dandv** [freeCodeCamp/freeCodeCamp#12544]
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/server/server.js and ssl-config.js use `require`, while https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/server/component-passport.js uses `import`.

**Comment by raisedadead** [comment]
Do we need this @BerkeleyTrue ?

**Comment by BerkeleyTrue** [comment]
`server` specifically uses require as that file is not transpiled in all situations. 

`ssl-config` is no longer used.

**Comment by raisedadead** [comment]
Howdy new contributors!

Remove https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/server/ssl-config.js
Please ensure that you have gone through our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), please reach out to for any clarifications [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by 0212n** [comment]
@raisedadead :I'm on it !!

**Comment by raisedadead** [comment]
@0212n Sure thing, Goodluck!
