### ISSUE TITLE
Cannot move to the next challenge 

### ISSUE THREAD

**Issue by Nikkyra** [freeCodeCamp/freeCodeCamp#12546]
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .smaller-image {
    width: 100px;
   }
  
  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;}
 
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="thick-green-border smaller-image" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by OFFLlNE** [comment]
Issue tracker is for reporting bugs.
Use a [CSS/HTML helproom](https://gitter.im/FreeCodeCamp/Help)
+ I gave you the code you had to submit for it to work. If still not working,

1. Reload the page and run the tests again. A script may have crashed, preventing the tests from running.
2. Try the challenge in incognito mode. A plugin might be interfering with the tests.
3. Try the challenge in a different browser. There may be an issue with your version of Chrome.
