### ISSUE TITLE
Manipulating Complex Objects - Missing Code

### ISSUE THREAD

**Issue by HeroslasherX** [freeCodeCamp/freeCodeCamp#12542]
#### Challenge Name

<a href="https://www.freecodecamp.com/challenges/manipulating-complex-objects#?solution=%0Avar%20myMusic%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Billy%20Joel%22%2C%0A%20%20%20%20%22title%22%3A%20%22Piano%20Man%22%2C%0A%20%20%20%20%22release_year%22%3A%201973%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CS%22%2C%20%0A%20%20%20%20%20%20%228T%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%0A%20%20%20%20%22gold%22%3A%20true%0A%20%20%7D%20%2F%2FMissing%20Comma%0A%20%20%2F%2F%20Add%20record%20here%0A%5D%3B%0A%0A%0Avar%20myMusic%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Billy%20Joel%22%2C%0A%20%20%20%20%22title%22%3A%20%22Piano%20Man%22%2C%0A%20%20%20%20%22release_year%22%3A%201973%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CS%22%2C%20%0A%20%20%20%20%20%20%228T%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%0A%20%20%20%20%22gold%22%3A%20true%0A%20%20%7D%2C%0A%20%20%2F%2F%20Add%20record%20here%0A%7B%0A%20%20%22artist%22%3A%20%22Jay%20Chou%22%2C%0A%20%20%22title%22%3A%20%22Long%20Time%20No%20See%22%2C%0A%20%20%22release_year%22%3A%202010%2C%0A%20%20%22formats%22%3A%20%5B%0A%20%20%22MP3%22%2C%0A%20%20%22MP4%22%0A%20%20%5D%0A%7D%5D%3B%0A">Manipulating Complex Objects</a>

#### Issue Description

Missing comma at the start of the challenge.
Noticed missing after referencing from forums.
Screenshot reference is a picture of unedited code.
The "Your Code" reference marks the place of a missing comma.

#### Browser Information

* Browser Name, Version: Chrome 55.0.2883.87 m
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  } //Missing Comma
  // Add record here
];
 
```
#### Screenshot

![screencapture-freecodecamp-challenges-manipulating-complex-objects-1484505192073](https://cloud.githubusercontent.com/assets/22015372/21965126/168d7218-db0e-11e6-88a3-fbb9d8b07524.png)

**Comment by raisedadead** [comment]
> Note
> You will need to place a comma after every object in the array, unless it is the last object in the array.

Double check the instructions.
