### ISSUE TITLE
Misspelling in convertHtml Challenge

### ISSUE THREAD

**Issue by ed42311** [freeCodeCamp/freeCodeCamp#12541]
Challenge [Convert HTML Entities](https://www.freecodecamp.com/challenges/convert-html-entities#?solution=%0Afunction%20convertHTML(str)%20%7B%0A%20%20%20var%20run%20%3D%20str.split(%22%22)%3B%0A%20%20%20var%20match%20%3D%20%5B'%26'%2C%20'%3C'%2C%20'%3E'%2C%20'%22'%0A%20%20%20var%20ret%20%3D%20%5B%22%26amp%3B%22%2C%20%22%26lt%3B%22%2C%20%22%26gt%3B%22%2C%20%22%26quot%3B%22%2C%20%22%26apos%3B%22%2C%20%22%26lt%3B%22%2C%20%22%26gt%3B%22%5D%0A%20%0A%20%20%20%20%20return%20str.replace(%22)%3B%0A%20%20%20%7D%20else%20if%20(str.includes(%22'%22))%20%7B%0A%20%20%20%20%20return%20str.replace(%2F'%2Fg)%3B%0A%20%20%20%7D%20else%20if%20(str.includes(%22%3C%3E%22))%20%7B%0A%20%20%20%20%20var%20newstr%20%3D%20str.replace('%3C')%3B%0A%20%20%20%20%20return%20newstr.replace('%3E')%3B%0A%20%20%20%7D%0A%7D%0A%0AconvertHTML(%22%3C%3E%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2981.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

``` convertHTML("Shindler's List")``` should return ```Shindler&​apos;s List```.

should be:

```convertHTML("Schindler's List")```  should return ```Schindler&​apos;s List```.

*Below is a screenshot of the html in the page*
******
<img width="307" alt="screen shot 2017-01-15 at 11 28 29 am" src="https://cloud.githubusercontent.com/assets/14878694/21965096/c9cee102-db15-11e6-944a-7471a405ed63.png">

**Comment by ed42311** [comment]
I'd be happy to fix this, but it might take me a minute to figure out where the code is for the one line of the challenges...

**Comment by ed42311** [comment]
Sorry, missed the part about third party confirmation.  Will check in with the community.

**Comment by systimotic** [comment]
Hi @ed42311! Thank you for reporting this issue.

Normally I don't notice closed issues, but I happened to stumble upon this one and thought I'd let you know that this is indeed an issue, but has already been fixed in https://github.com/FreeCodeCamp/freeCodeCamp/issues/12433

Thanks again for making us aware of this issue, and also for your efforts to ask around first. That's a great help to us.

Happy coding!

**Comment by ed42311** [comment]
Hey @systimotic,

   Thanks for letting me know.  Interested int getting into the open source communtiy at FCC.  Should I just look for help wanted tags and try to grab one before they get swooped up or is there a better way to connect into the world...

Thanks
Ed

**Comment by systimotic** [comment]
@ed42311 Awesome! You should definitely join our [contributors chatroom](https://gitter.im/FreeCodeCamp/Contributors). You can check out the [CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) to get your local version set up.
Looking for your first issue to contribute to can be difficult. If you dig through help wanted issues I'm sure you'll find something you can help out with. There are some older issues that new contributors can help out with, but that have been missed.
