### ISSUE TITLE
Incorrectly passing task when the major requirement not met

### ISSUE THREAD

**Issue by ElisabetK** [freeCodeCamp/freeCodeCamp#12540]
```
> <h1 id="orange-text">
> <h1 class="pink-text blue-text">Hello World!</h1>
```
Code passes the test, including the last item "Your h1 element should be orange." That element is obviously still blue, yet that item is incorrectly checked and the challenge is marked as passed.

A check that there is only one h1 declaration, or that the id and class declarations are in the same tag, or (and I don't know if this is possible) checking the actual color displayed could fix this issue.

I believe that indicating to the student that the id and class attributes are in the same tag might be useful information. 
 

#### Screenshot

![capture](https://cloud.githubusercontent.com/assets/24898384/21964132/e7a53532-db0b-11e6-94b2-2e6e2cb25fc5.PNG)

#### Challenge Name
https://www.freecodecamp.com/challenges/override-class-declarations-by-styling-id-attributes

#### Browser Information

* Browser Name, Version: Windows Edge
* Operating System: Windows 10
* Mobile, Desktop, or Tablet:  Mobile

#### Your Code

```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text {
    color: orange;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 id="orange-text">
<h1 class="pink-text blue-text">Hello World!</h1>
```

**Comment by Manish-Giri** [comment]
There does exist a test that [checks for orange](https://github.com/freeCodeCamp/freeCodeCamp/blob/ae5b78a9a00c272ad822cea2fb21da57b49fc1e0/seed/challenges/01-front-end-development-certification/html5-and-css.json#L4494), but interestingly, it doesn't seem to working here. 
```
 "assert($(\"h1\").css(\"color\") === \"rgb(255, 165, 0)\", 'message: Your <code>h1</code> element should be orange.');"
```
This seems to be because of the incomplete `h1` element - `<h1 id="orange-text">`

This is rendered in the browser as an `h1` element with no text, but including the `orange-text` ID, which is why the tests pass - 

![screenshot 2017-01-15 16 09 50](https://cloud.githubusercontent.com/assets/11348778/21966220/8f06283c-db3d-11e6-96cb-6a00428afd6c.png)

Maybe the tests could be amended to assert for presence of a single `h1` element?

**Comment by ElisabetK** [comment]
Not closing the h1 tag was a copy/paste error on my part. The issue however is the same.

Thank you for looking at this; I think the solution of looking for a single h1 element would work.

I believe several other bug reports here have been for the same error, but it is sometimes hard to tell.

**Comment by Manish-Giri** [comment]
@raisedadead I'd like to work on this, if that's okay..

**Comment by raisedadead** [comment]
@Manish-Giri sure go ahead! 😉

**Comment by Manish-Giri** [comment]
@raisedadead I added a new test that checks for the presence of a single `h1` element. Now with the same code as OP, the challenge does not pass. 

![screenshot from 2017-01-16 14-39-33](https://cloud.githubusercontent.com/assets/11348778/21996872/46715908-dbfa-11e6-9c29-d2a25c1ce283.png)

This code fails against the test I added - 

> Do not create a new `h1` element

Is this all right for submitting the PR?

**Comment by franxious** [comment]
This is my first post to anything related to FCC, so please inform me if I miss something. My code just passed incorrectly (passed but text is not orange)


<h1 id="orange-text">
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
  #orange-text {
    color:orange;
  }
</style>

<h1 class="pink-text blue-text">Hello World!</h1>
![image](https://cloud.githubusercontent.com/assets/25202267/22202556/a5d7519a-e136-11e6-99ae-26fd189523d5.png)
 (I can't figure out how to paste the image here, but the text is blue).

**Comment by franxious** [comment]
I didn't mean for the code to run together like that. :(
