### ISSUE TITLE
Night mode modal styling

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#12558]
#### Issue Description

Both the "Bug" and "Challenge Success" modals still have mostly "day mode" styling when in night mode.
 <img src="https://cloud.githubusercontent.com/assets/18563015/21996226/256fcf12-dbf7-11e6-8ece-f6bc6dfde3fb.png" width="500px">
<img src="https://cloud.githubusercontent.com/assets/18563015/21996245/3ca72f36-dbf7-11e6-8f3d-e9ff5720963f.png" width="500px">

I've already attempted messing around with this a bit, but it's not so straightforward, since the two modals are set up differently. Here's what happens by adding a new color to `.night .modal-body`:

Success Modal, ok, not perfect with the white lines, but not terrible
<img src="https://cloud.githubusercontent.com/assets/18563015/21996592/fcf1c46c-dbf8-11e6-94db-b6c2e0005eb7.png" width="500px">

Now same styling on the Bug modal:
<img src="https://cloud.githubusercontent.com/assets/18563015/21996625/2e54b8c0-dbf9-11e6-884c-a80722cb6cd9.png" width="500px">

After inspecting, it would appear that in both day mode and night mode, the `.modal-bodal` body is always extending over `.modal-header`, its just that in day mode, `.modal-body` has no fill. If you attempt to accommodate this by adding a top-margin to the modal content, it looks ok for the bug modal, but leaves giant white spaces in the success modal. And I couldn't figure out how to style those spaces without affecting other things.

Since you guys were on the dropdown thread, do any of you have any ideas @raisedadead, @hallaathrad, @systimotic?

**Comment by systimotic** [comment]
@no-stack-dub-sack It seems their background colour is set from their parent [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/075476f15fbacda35dffd36176e0d42311438754/client/less/main.less#L1153).
Changing the background colour of the parent seems to do the trick, although the problem with the white lines persists. I'm not sure how that's happening yet.

**Comment by no-stack-dub-sack** [comment]
@systimotic, funny, I thought I tried that and did not get the right results, I will have another look. So you just added the background color in the `.night` class of `main.less` right?

**Comment by hallaathrad** [comment]
Those lines are caused by the other elements having a border line. Change the colour on those, or remove them and you'll be good to go

**Comment by systimotic** [comment]
@no-stack-dub-sack Yeah, that should work, as long as you put the `.modal-content` in there. Keep in mind that the original colour is set later in the file than the night colour, so with equal specificity the default colour will stay visible. I believe putting `.model-dialog .modal-content` inside of `.night` should do the trick for more specificity.

As @hallaathrad mentioned, the lines are caused by a border, which is set by Bootstrap. The top border is on `.modal-header`, the bottom border is on `.modal-footer`.

**Comment by no-stack-dub-sack** [comment]
@systimotic Ok, cool - the specificity is what I was missing. Thanks! I'll fix both issues and make a PR a bit later
