### ISSUE TITLE
The word Loving on my checkbox is below the checkbox, while the other words on the check boxes are beside them.

### ISSUE THREAD

**Issue by trustyaxe** [freeCodeCamp/freeCodeCamp#12568]
#### Browser Information

* Browser Name, Version: Google Chrome 55.0.2883.87 m
* Operating System: Windows 8.1
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
```html
<form action="/submit-cat-photo">
    <div class="row">
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor">Indoor</label>
      </div>
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor">Outdoor</label>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality">Loving</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality">Lazy</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality">Crazy</label>
      </div>
    </div>
    <input class="form-control" type="text" placeholder="cat photo URL" required>
    <button class="btn btn-primary" type="submit"><i class="fa fa-paper-plane"></i>Submit</button>
  </form> 
</div>
```

#### Screenshot

![screenshot 653](https://cloud.githubusercontent.com/assets/14169239/22007405/0ff06e4e-dc38-11e6-9bb5-ed2948bc0af4.png)

*Edited by moderator*

**Comment by raisedadead** [comment]
What is the challenge you are on? Can you provide some screenshots ?

**Comment by erictleung** [comment]
@raisedadead the code and screenshots were commented out in the template so that is why they didn't show up. I edited the post to show the code and screenshot. I think this is a non-issue because the text "loving" is just wider than the columns in mobile view. Not sure what we can do about this.

**Comment by raisedadead** [comment]
Ah... thanks @erictleung ! Yup, I think this maybe just isolated to the OP's environment as well, also I am not sure if this is worth fixing.

**Comment by erictleung** [comment]
@raisedadead agreed. This is somewhat related to https://github.com/freeCodeCamp/freeCodeCamp/issues/7842 as well. I'll close this issue as a duplicate. Happy coding!

**Comment by trustyaxe** [comment]
Thanks for the info. If it's not an issue with my code, then I'm not concerned.
