### ISSUE TITLE
#6 - Choose "Blank" in the template section.

### ISSUE THREAD

**Issue by WesDowney** [freeCodeCamp/freeCodeCamp#12563]
Challenge [Manage Packages with npm](https://www.freecodecamp.com/challenges/manage-packages-with-npm) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Step #6 says "Choose "Blank" in the template section." but Blank isn't an option on Cloud 9 anymore for a template. I tried HTML5 and it worked fine so I think that replaced Blank?

**Comment by no-stack-dub-sack** [comment]
Hey @WesDowney, I just double checked and it would appear that "Blank" is still an option 😄
![image](https://cloud.githubusercontent.com/assets/18563015/22004823/b9335b58-dc2c-11e6-9f08-11742f94c0f2.png)

So I'm going to go ahead and close the issue, however, if for some reason it really isn't there for you, please take a screen shot and maybe we can help figure out what's going on.

Thanks!

**Comment by WesDowney** [comment]
Hi @no-stack-dub-sack. You are right! Thanks! I must have seen Blank but read Ubuntu looking at the logo.

**Comment by vrabcak** [comment]
I had exactly the same problem, maybe including small ubuntu logo to the tutorial text would help :-)
