### ISSUE TITLE
Declare String Variables

### ISSUE THREAD

**Issue by trg2015** [freeCodeCamp/freeCodeCamp#12569]
Challenge [Declare String Variables](https://www.freecodecamp.com/challenges/declare-string-variables#?solution=%0A%2F%2F%20Example%0Avar%20firstName%20%3D%20%22Alan%22%3B%0Avar%20lastName%20%3D%20%22Turing%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20myFirstName%20%3D%20'Tammy'%3B%0Avar%20mylastName%20%3D%20'Grayned'%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
First line of code accepted but not the second line.
My code:
```javascript

// Example
var firstName = "Alan";
var lastName = "Turing";

// Only change code below this line
var myFirstName = 'Tammy';
var mylastName = 'Grayned';


```

**Comment by Manish-Giri** [comment]
@trg2015 in the variable `myLastName`, `L` should be capitalized. Like how you've written `myFirstName`.

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) first, if you need help with challenges like these, in future. Happy Coding!

**Comment by trg2015** [comment]
Thanks

**Comment by raisedadead** [comment]
Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!

**Comment by trg2015** [comment]
Thanks
