### ISSUE TITLE
Correct answer but fails to pass

### ISSUE THREAD

**Issue by Bart369** [freeCodeCamp/freeCodeCamp#12571]
Any help will be greatly appreciated. Thanks.

Challenge [Return Largest Numbers in Arrays](https://www.freecodecamp.com/challenges/return-largest-numbers-in-arrays#?solution=function%20largestNumber(arr)%7B%0A%20%20var%20array%20%3D%20%5B%5D%3B%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%7B%0A%20%20%20%20arr%5Bi%5D.sort(function%20(a%2Cb)%7B%0A%20%20%20%20%20%20%20return%20b%20-%20a%3B%0A%20%20%20%20%7D)%3B%0A%20%20%7D%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%7B%0A%20%20%20%20%20%20array.push(arr%5Bi%5D%5B0%5D)%3B%0A%20%20%7D%20%0A%0A%20%20return%20array%3B%0A%7D%0A%0A%0AlargestNumber(%5B%5B13%2C%2027%2C%2018%2C%2026%5D%2C%20%5B4%2C%205%2C%201%2C%203%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function largestNumber(arr){
  var array = [];
  for (i = 0; i < arr.length; i++){
    arr[i].sort(function (a,b){
       return b - a;
    });
  }
  for (i = 0; i < arr.length; i++){
      array.push(arr[i][0]);
  } 

  return array;
}


largestNumber([[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

```

**Comment by Bart369** [comment]
Not asking for help, i got the correct answer but it's not being accepted.

**Comment by Marmiz** [comment]
@Bart369 the challenge expect a return from a function called `largestOfFour`

I suggest you to rename the function as in original, and for the future to not rename any given code (unless explicitly told so)

Happy coding 👍

**Comment by erictleung** [comment]
@Bart369 thanks for the issue but what @Marmiz has mentioned is correct. Please change your function to `largestOfFour` and your code should pass. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by Bart369** [comment]
@Marmiz Thank you that worked! I didn't notice i had changed it while messing around trying different stuff.
