### ISSUE TITLE
Typo in the instruction

### ISSUE THREAD

**Issue by arvind00** [freeCodeCamp/freeCodeCamp#12576]
#### Issue Description
There is a spelling mistake in the instruction given.

* Here is the extract of the **Instruction:**

>Set myName to a string equal to your name and build myStr with myName between the strings "My name is " and " and I am swell!"

- Expected last word in the instruction: well
- Actual last word in the instruction: swell

Here _**well**_ is expected instead of _**swell**_ because, the context is set in the starting of the code as:
```// Example
var ourName = "Free Code Camp";
var ourStr = "Hello, our name is " + ourName + ", how are you?";

// Only change code below this line
var myName;
var myStr;
```

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by OFFLlNE** [comment]
Thanks for reporting that.

I think they meant it to be "swell" not well.
Urban Dictionary : swell => adj. Fantastic, great, wonderful, et.

Google:
adjective (NORTH AMERICAN) `informal`
excellent; very good.
"you're looking swell"

**Comment by raisedadead** [comment]
Thanks @arvind00. 

@OFFLlNE agreed. 

Although I believe a lot of campers are non-native English speakers. We might as well change this, while this is not a huge issue with the challenge itself.

/cc @freeCodeCamp/moderators worth changing? If yes, let's tag it first timers?

**Comment by arvind00** [comment]
Thanks @OFFLlNE and @raisedadead .
I should have referred a dictionary, before posting it.
So, shall I keep the issue open or close it?

**Comment by dhcodes** [comment]
Feels like bike-shedding to me, but if it looks like a typo to a lot of people, then I'm fine with a first-timer PR for it.

**Comment by hallaathrad** [comment]
If not for the sake of promoting easy contributions, then just so that non-natives won't be confused (which increases friction and makes their learning more difficult).

**Comment by TheeMattOliver** [comment]
I'll take it. 'Swell' is fine (I am kind of an American English Usage buff, and this is an important field in pedagogy!), but I'd like to claim this just so I can get the practice with contributing.

**Comment by hallaathrad** [comment]
@TheeMattOliver that's swell! PR away 😃

**Comment by arvind00** [comment]
Thanks @everyone. Closing the issue.

**Comment by raisedadead** [comment]
@arvind00 do not close the issue, this will be closed with a pull request (PR).

**Comment by arvind00** [comment]
@raisedadead ok
