### ISSUE TITLE
Math error of 0.01 in challenge Exact Change

### ISSUE THREAD

**Issue by oyeuva** [freeCodeCamp/freeCodeCamp#12572]
#### Challenge Name
https://www.freecodecamp.com/challenges/exact-change

#### Issue Description

I think the code is right but it is not producing exact answer. For given parameters checkCashRegister(3.26, 100.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]]);
I'm getting an result [["TWENTY", 60.00], ["TEN", 20.00], ["FIVE", 15.00], ["ONE", 1.00], ["QUARTER", 0.50], ["DIME", 0.20], ["PENNY", 0.03]] instead of with ["PENNY", 0.04] and remaining change is coming as 0.009999999999994874 instead of 0.01.
Please help me solve this math error.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Win10
* Mobile, Desktop, or Tablet: 

#### Your Code

```
function checkCashRegister(price, cash, cid) {
  var change = cash - price;
  var curr = 0;
  var currency = [100.00, 20.00, 10.00, 5.00, 1.00, 0.25, 0.10, 0.05, 0.01];
  var back = [];
  
  cid.reverse();
  // Calculating current cash in drawer
  cid.forEach(function(e,i){
    curr+= cid[i][1];
  });
  
  if(change > curr){
    return "Insufficient Funds";
  } else if (change == curr){
    return "Closed";
  } else {    //change
    cid.forEach(function(e,i){
      if(change > currency[i]){
        
        if(change <= cid[i][1]){
          var temp = Math.floor(change/currency[i]);
          change -= temp*currency[i];      //subtracting available amount
          back.push([cid[i][0], temp*currency[i]]);
        } 
        else if(change > cid[i][1] && cid[i][1] !== 0){
          change -= cid[i][1];
          back.push([cid[i][0], cid[i][1]]);
        }
        
      }
    });
    //if(change>0){ return "Insufficient Funds";}     //commented for now
    return back;
  }
}

checkCashRegister(3.26, 100.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]]);
```
```js
 
 
 
```

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!
