### ISSUE TITLE
Size your Image

### ISSUE THREAD

**Issue by Joerell** [freeCodeCamp/freeCodeCamp#12574]
I cant proceed to the next challenge
![q](https://cloud.githubusercontent.com/assets/20026338/22018949/4a269b24-dcec-11e6-90cb-940db3ac3b87.png)

lenght the 100 pixels zoom task cant be correct

**Comment by raisedadead** [comment]
The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!

**Comment by LucasVenancio** [comment]
I have the same problem I have checked the code many times couldn't´t get any help from the chat, people just wasn't answering, and a actually found a link from another person doing the same challenge but with a few steps ahead and I checked my code and it was exactly the same

**Comment by WaheedRehman** [comment]
I have the same issue. Coding is fine and browser is at 100%. Still couldn't proceed.

**Comment by WaheedRehman** [comment]
Using chrome on android.
In the font-size challenge the 100% browser option worked fine but in image resize challenge it isn't working.

**Comment by raisedadead** [comment]
On mobile browsers, we have had issues earlier with some characters. Can you try a reset and see if it works?

**Comment by WaheedRehman** [comment]
The issue is with spaces, remove the spaces and it works.
