### ISSUE TITLE
well

### ISSUE THREAD

**Issue by pouyapeyravi** [freeCodeCamp/freeCodeCamp#12579]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

Iphone se
09123108576

#### Your Code 6336

```js
 
 
 
```

**Comment by raisedadead** [comment]
Hi @pouyapeyravi 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
