### ISSUE TITLE
Bonfire sum all primes

### ISSUE THREAD

**Issue by kurtr** [FreeCodeCamp/freecodecamp#1257]
Im having an issue with a bonfire challenge. The brief is to "Sum all the prime numbers up to and including the provided number.", When I run my code i get they following error:"expect(sumPrimes(10)).to.equal(17);expected 27 to equal 17". Now i may be mistaken but the prime numbers up to ten are [2, 3, 5, 7] totaling to 17, 17 +10 = 27 right? 
This is the only test it fails on.

**Comment by kurtr** [comment]
here is my code
 function sumPrimes(num) {
                var primes = [];
                for (i = 2; i < num; i++) {
                    if (isPrime(i) == true) {
                        primes.push(i);
                    }
                }
            function isPrime(num) {
                var prime = true;
                for (i = 2; i < num; i++) {
                    if (num % i === 0) {
                        prime = false;
                    }
                }
                return prime;
            }
  var a = primes.reduce(function(prev,curr){return prev+curr;});
  return a + num;
}

sumPrimes(10);

**Comment by LumenTeun** [comment]
By "including the provided number" they still mean only if it's a prime. In the future, please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) for questions like this. :)

**Comment by kurtr** [comment]
Hi Thanks I did, the chatroom agreed that it didnt make sense and sent me here

**Comment by LumenTeun** [comment]
Well, the sentence is a bit advanced, I agree, but it is grammatically correct. Remember to close this issue
