### ISSUE TITLE
Return Largest Numbers in Arrays has a little typo

### ISSUE THREAD

**Issue by logol** [freeCodeCamp/freeCodeCamp#12575]
Challenge [Return Largest Numbers in Arrays](https://www.freecodecamp.com/challenges/return-largest-numbers-in-arrays) has an issue.

There is a little typo in the frontend at the tests section (div#testSuite):

`largestOfFour([[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]) should return [27,5,39,1001]`

The order of the last array is wrong and should be `[ 5, 27, 39, 1001 ]`

The tests behind are fine.

**Comment by OFFLlNE** [comment]
Thank you for reporting this issue.

If you `return [5,27,39,1001];` then it does not let pass the test because it wants it in order `[27,5,39,1001]`
The first test result is also not sorted :)

Your code should return  `[27,5,39,1001]` on 2nd test.

**Comment by logol** [comment]
You're right, the first and second test differ

> largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]) should return an array.

> largestOfFour([[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]) should return [27,5,39,1001]

That's what was confusing me. In that case everything is correct and the issue can be closed.
