### ISSUE TITLE
Symmetric Difference unit test expects wrong array?

### ISSUE THREAD

**Issue by SabbaKilam** [FreeCodeCamp/freecodecamp#1258]
Challenge http://www.freecodecamp.com/challenges/bonfire-symmetric-difference has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Here is the challenge statement:
"Create a function that takes two or more arrays and returns an array of the symmetric difference of the provided arrays"

Here is the reported error:

"assert.deepEqual(sym([1, 2, 5], [2, 3, 5], [3, 4, 5]), [1, 4, 5], 'should return the symmetric difference of the given arrays');should return the symmetric difference of the given arrays: expected [ 1, 4 ] to deeply equal [ 1, 4, 5 ]"

My sym() function yields the array [1, 4] that does not include the element "5," which according to the definition for symmetric difference*, shouldn't be included. ALL the arrays passed to sym() have  5 as an element, and thus the 5 should be excluded from the symmetrical difference. But the test incorrectly expects the 5 to be included.

Is my reasoning not correct?

*"The mathematical term symmetric difference refers to the elements in two sets that are in either the first or second set, but not in both."

**Comment by Damon-Myers** [comment]
I think this is more of an issue of improper explanation of symmetric difference on more than two sets. Whenever you take the symmetric difference of more than two sets, you must first find the symmetric difference of the first two sets, then find the symmetric difference of the following set and the result of the first symmetric difference. It is a recursive algorithm.

**Comment by SabbaKilam** [comment]
@Damon-Myers: Thanks.
I think you're right: An "explanation of symmetric difference on more than two sets" is not given.
I should have known, though, since this challenge is under functional programming. I'll try again using "pure" lambda functions if I can.
Thanks again.

**Comment by nxiety** [comment]
Been scratching my head on this one for an hour before giving up and searching. I was comparing all the sets at once. A better explanation is definitely needed in regards to more than two sets.
