### ISSUE TITLE
Semantics of Greater Than Challenge

### ISSUE THREAD

**Issue by cmhall42** [freeCodeCamp/freeCodeCamp#12581]
#### Challenge Name
Comparison with the Greater Than Operator

#### Issue Description
Semantics of this challenge need to be amended. Would be better to say '100 or over'. This test only passes when you put val > 100 but I think it should only pass (assuming use of integers only) with 101. 

#### Your Code

```js
function testGreaterThan(val) {
  if (val > 100) {  // Change this line
    return "Over 100";
  }
  
  if (val > 10) {  // Change this line
    return "Over 10";
  }

  return "10 or Under";
}

// Change this value to test
testGreaterThan(10);
```

**Comment by cmhall42** [comment]
Ah, I suspect this is a bit of a challenge given the >= exercise which follows.

**Comment by erictleung** [comment]
@cmhall42 thanks for the issue. Can you elaborate on why you want this change? I'm not understanding the issue. Which "test" are you referring to in "This test only passes..."? 

I think the challenge is clear enough and uses the correct comparison operators. If `101` is passed into the function for this challenge, it should return `Over 100`. And as you mentioned, the next challenge uses `## or over` to indicate the value passed in is equal to that number or greater.

**Comment by raisedadead** [comment]
Please provide clarification as requested
