### ISSUE TITLE
ReferenceError ("...not defined") vs "undefined" in example

### ISSUE THREAD

**Issue by nomicos** [freeCodeCamp/freeCodeCamp#12585]
#### Challenge Name
[Local Scopes and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions)

#### Issue Description
The example (see the screenshot below) states that `console.log(loc)` called outside the body of `myTest()` will result in `"undefined"`, i.e. a string. That is not accurate, as that will actually throw a ReferenceError (`loc is not defined`) exception instead of outputting the `"undefined"` string.

#### Screenshot
![image](https://cloud.githubusercontent.com/assets/11248671/22043490/179ff6ae-dd10-11e6-98d2-3650b48e6111.png)

**Comment by no-stack-dub-sack** [comment]
@nomicos Hmmm... well the reference error is being thrown _because_ `loc` has a value of `undefined`, but you are correct in saying that the console would not output the _string_ `"undefined"`.

This could be changed to:
```js
function myTest() {
  var loc = "foo";
  console.log(loc);
}
myTest(); // logs "foo"
console.log(loc); // loc is not defined 
```
This would be a clearer and more accurate example, however, the example does not explicitly say that `"undefined"` will be logged, it is just providing it's value. IMHO, I think the current example gets the point across though, and this may be considered an example of bikeshedding.

**Comment by raisedadead** [comment]
@no-stack-dub-sack  Well, just for absolute beginners I can see that this can be a point of confusion. Let's update the comment line in the example as suggested by you.

**Comment by ooade** [comment]
@no-stack-dub-sack the example uses `// "undefined"` instead of `// loc is not defined`

**Comment by raisedadead** [comment]
Yes @ooade, and we are discussing to update that as suggested by @no-stack-dub-sack

**Comment by ooade** [comment]
@nomicos will you like to take this on? Just change it [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L2512)

**Comment by ooade** [comment]
@raisedadead Okay :+1:

**Comment by no-stack-dub-sack** [comment]
@raisedadead @ooade Do you think maybe instead we could open it up to first-timers only? If someone is looking to get their feet wet, this is a super easy way to do it. Unless you've already started @ooade

**Comment by no-stack-dub-sack** [comment]
@nomicos if you've never contributed to FCC before it's a great and easy way to get started! Nice catch

**Comment by Manish-Giri** [comment]
Sorry to spam here, but I have to ask this - 
> well the reference error is being thrown because loc has a value of undefined

I couldn't really get this part. I thought the `ReferenceError` was thrown because `loc` was [scoped](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_defined) only to the `myTest` function. So, when you try to access it outside `myTest()`, you get the error. 

Or did you mean that since technically `loc` doesn't exist outside `myTest`, it is "undefined" outside `myTest`,  hence it has a value of `undefined`?

**Comment by IanTeo** [comment]
Hi. If @nomicos is not doing this issue, can I try it out?

**Comment by nomicos** [comment]
@ooade @no-stack-dub-sack Sure, I'll do it.
