### ISSUE TITLE
Cant able to Sign in C9.io.com for Node.js Tutourial 

### ISSUE THREAD

**Issue by seenu511-hcl** [freeCodeCamp/freeCodeCamp#12592]
tried spteps provideing in Video

**Comment by raisedadead** [comment]
Hi @seenu511-hcl 

Can you explain the exact issue that you faced? Which step was a problem? Have you reached out to the chat rooms for help?

- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

Happy Coding!
