### ISSUE TITLE
Ok, I get it.

### ISSUE THREAD

**Issue by attributeofextension** [freeCodeCamp/freeCodeCamp#12591]
Ok, I see what you're trying to make me do now.

Challenge [Make a Person](https://www.freecodecamp.com/challenges/make-a-person#?solution=%0Avar%20Person%20%3D%20function(firstAndLast)%20%7B%0A%20%20this.getFirstName%20%3D%20function()%20%7B%0A%20%20%20%20return%20firstAndLast.split(%22%20%22)%5B0%5D%3B%20%20%0A%20%20%7D%3B%20%20%0A%20%20this.getLastName%20%3D%20function()%20%7B%0A%20%20%20%20return%20firstAndLast.split(%22%20%22)%5B1%5D%3B%0A%20%20%7D%3B%0A%20%20this.getFullName%20%3D%20function%20()%20%7B%0A%20%20%20%20return%20firstAndLast%3B%0A%20%20%7D%3B%0A%20%20this.setFirstName%20%3D%20function%20(first)%20%7B%0A%20%20%20%20this.getFullName%20%3D%20function()%20%7B%0A%20%20%20%20%20%20return%20first%20%2B%20%22%20%22%20%2B%20this.getLastName()%3B%0A%20%20%20%20%7D%3B%0A%20%20%20this.getFirstName%20%3D%20function%20()%20%7B%0A%20%20%20%20%20%20return%20first%3B%0A%20%20%20%20%7D%3B%0A%20%20%7D%3B%0A%20%20this.setLastName%20%3D%20function(last)%20%7B%0A%20%20%20%20%20this.getFullName%20%3D%20function()%20%7B%0A%20%20%20%20%20%20return%20this.getFirsttName()%20%2B%20%22%20%22%20%2B%20last%3B%0A%20%20%20%20%7D%3B%0A%20%20%20this.getFirstName%20%3D%20function%20()%20%7B%0A%20%20%20%20%20%20return%20last%3B%0A%20%20%20%20%7D%3B%0A%20%20%7D%3B%0A%20%20this.setFullName%20%3D%20function(firstAndLast)%20%7B%0A%20%20%20%20this.getLastName%20%3D%20function()%20%7B%0A%20%20%20%20%20%20return%20firstAndLast.split(%22%20%22)%5B1%5D%3B%0A%20%20%20%20%7D%3B%0A%20%20%20this.getFirstName%20%3D%20function%20()%20%7B%0A%20%20%20%20%20%20return%20firstAndLast.split(%22%20%22)%5B0%5D%3B%0A%20%20%20%20%7D%3B%0A%20%20%7D%3B%0A%20%20%0A%20%20%0A%20%20%0A%20%20%0A%20%20%0A%20%20return%20firstAndLast%3B%0A%7D%3B%0A%0Avar%20bob%20%3D%20new%20Person('Bob%20Ross')%3B%0Abob.getFullName()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var Person = function(firstAndLast) {
  this.getFirstName = function() {
    return firstAndLast.split(" ")[0];  
  };  
  this.getLastName = function() {
    return firstAndLast.split(" ")[1];
  };
  this.getFullName = function () {
    return firstAndLast;
  };
  this.setFirstName = function (first) {
    this.getFullName = function() {
      return first + " " + this.getLastName();
    };
   this.getFirstName = function () {
      return first;
    };
  };
  this.setLastName = function(last) {
     this.getFullName = function() {
      return this.getFirsttName() + " " + last;
    };
   this.getFirstName = function () {
      return last;
    };
  };
  this.setFullName = function(firstAndLast) {
    this.getLastName = function() {
      return firstAndLast.split(" ")[1];
    };
   this.getFirstName = function () {
      return firstAndLast.split(" ")[0];
    };
  };
  
  
  
  
  
  return firstAndLast;
};

var bob = new Person('Bob Ross');
bob.getFullName();

```

**Comment by raisedadead** [comment]
Hi @attributeofextension 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
