### ISSUE TITLE
should Diff Two Arrays' tests consider the order?

### ISSUE THREAD

**Issue by logol** [freeCodeCamp/freeCodeCamp#12599]
Challenge [Diff Two Arrays](https://www.freecodecamp.com/challenges/diff-two-arrays) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.

It seems that the tests are not considering the order of elements in the returned array au contraire to the given "should return ..." causing a false-positive pass for test:
* 3 _(should return ["diorite", "pink wool"])_
* 6 _(should return ["piglet", 4])_
* 7 _(should return ["snuffleupagus", "cookie monster", "elmo"])_
* 8 _(should return [1, "calf", 3, "piglet", 7, "filly"])_

The following code will return an array with random order, however the tests will always pass:
```javascript
/* jshint esversion: 6 */
/* jshint asi: true */

function shuffle (a) {
  for (let i = a.length; i; i--) {
    let j = Math.floor(Math.random() * i)
    ;[a[i - 1], a[j]] = [a[j], a[i - 1]]
  }
  return a
}

function diffArray (arr1, arr2) {
  return shuffle(arr1.filter(e => !arr2.includes(e)).concat(arr2.filter(e => !arr1.includes(e))))
}

diffArray([1, "calf", 3, "piglet"], [7, "filly"])
```

Apart from test 3 _(which then should return ["pink wool", "diorite"])_, the required results make me feel like one should use a solution that first returns the overall unique elements of arr1 and then those of arr2 (in occurring order).
If that is inteded the tests are wrong, if not maybe it should be mentioned in the instructions?

**Comment by no-stack-dub-sack** [comment]
@logol the tests look like they use Chai's `sameMembers` assertion, which only tests that two arrays share the same members, and does not account for order. You bring up a good point, the test case messages indicate the arrays should be in a particular order, and your example does get around that.

I think we could fix this by saying `should return an array containing...` and list the elements, OR, we could use the `deepEqual` assertion to account for order, however, if we do that, I agree that it should go in the instructions. 

I think the first option is probably better.
