### ISSUE TITLE
Increment a Number with JavaScript has a misleading test case

### ISSUE THREAD

**Issue by ankush2604** [freeCodeCamp/freeCodeCamp#12593]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=%0Avar%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0AmyVar%2B%2B%3B%0AmyVar%20%3D%20myVar%3B%0AmyVar%20%3D%20myVar%20%2B%200%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myVar = 87;

// Only change code below this line
myVar++;
myVar = myVar;
myVar = myVar + 0;


```

**Comment by VaneSuky89** [comment]
var myVar = 87;

// Only change code below this line
myVar++;

my code.

**Comment by OFFLlNE** [comment]
@ankush2604 Thank you for reporting the issue.
Your task is just to do that "Change the code to use the ++ operator on myVar."

I think that the test "myVar = myVar should be changed" might be little misleading, this is why you have something like that in your code. Some mod might take a look and maybe explain IF we need this test-description there at all?

**Comment by VaneSuky89** [comment]
I ++; Is the equivalent of I = i + 1; That is to say + is = a myVar = myVar
= add the number 87 if anyadimos another + this vale 1 ie ... If we add
myVar = ++; We are adding the variable q we currently have q is 87 + + 1
which is the equivalence of i. Or at least something like this I
understood, that is better than some mod advise you better

2017-01-18 11:24 GMT+01:00 Lauri <notifications@github.com>:

**Comment by raisedadead** [comment]
Thanks @OFFLlNE 

Yes, this test case can be misleading and should be updated to 
> `myVar = myVar + 1;` should be changed.

**Comment by AngShiYa** [comment]
Hi can I try to do this?

**Comment by dhcodes** [comment]
@AngShiYa Sure thing! Follow the guide for contributing at: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md

If you run into any problems, feel free to ask for help in the [Contributors Gitter chat](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by no-stack-dub-sack** [comment]
Whoops - accidentally clicked the assign button!

**Comment by riturajpandey93** [comment]
var myVar = 87;

// Only change code below this line
ourVar = myVar++;
ourVar = ourVar + 0;

**Comment by texas2010** [comment]
@riturajpandey93 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by rahuls-19** [comment]
Just use 
myVar++;
