### ISSUE TITLE
Disagreement about design

### ISSUE THREAD

**Issue by attributeofextension** [freeCodeCamp/freeCodeCamp#12590]
I can tell right now that to finish this challenge, I need to store a third private member - fullName - so that firstName and lastName remain undefined. But this doesn't seem like good OO practice to me. getFullname() should only ever be a method that aggregates firstName and lastName. I will tweak my class appropriately, but I felt strongly enough (not too strongly, because obviously it only takes 2 minutes to register this disagreement) to drop a message about it.

Challenge [Make a Person](https://www.freecodecamp.com/challenges/make-a-person#?solution=class%20Person%20%7B%0A%20%20constructor()%20%7B%0A%20%20%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20%20%20if(arguments.length%20%3D%3D%3D%201)%20%7B%0A%20%20%20%20%20%20arr%20%3D%20arguments%5B0%5D.split(%22%20%22)%3B%0A%20%20%20%20%20%20this.firstName%20%3D%20arr%5B0%5D%3B%0A%20%20%20%20%20%20this.lastName%20%3D%20arr%5B1%5D%3B%0A%20%20%20%20%7D%20else%20if%20(arguments.length%20%3D%3D%3D%202)%20%7B%0A%20%20%20%20%20%20this.firstName%20%3D%20arguments%5B0%5D%3B%0A%20%20%20%20%20%20this.lastName%20%3D%20arguments%5B1%5D%3B%20%20%20%20%20%20%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20this.firstName%20%3D%20undefined%3B%0A%20%20%20%20%20%20this.lastName%20%3D%20undefined%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20setFirstName(first)%20%7B%0A%20%20%20%20this.firstName%20%3D%20first%3B%0A%20%20%7D%0A%20%20setLastName(last)%20%7B%0A%20%20%20%20this.lastName%20%3D%20last%3B%0A%20%20%7D%0A%20%20setFullName(firstAndLast)%20%7B%0A%20%20%20%20var%20arr%20%3D%20firstAndLast.split(%22%20%22)%3B%0A%20%20%20%20this.firstName%20%3D%20arr%5B0%5D%3B%0A%20%20%20%20this.lastName%20%3D%20arr%5B1%5D%3B%0A%20%20%7D%0A%20%20getFirstName()%20%7B%0A%20%20%20%20var%20str%20%3D%20this.firstName%3B%20%0A%20%20%20%20return%20str%3B%0A%20%20%7D%0A%20%20getLastName()%20%7B%0A%20%20%20%20return%20this.lastName%3B%0A%20%20%7D%0A%20%20getFullName()%20%7B%0A%20%20%20%20return%20this.firstName%20%2B%20%22%20%22%20%2B%20this.lastName%3B%0A%20%20%7D%0A%20%20%0A%20%20%0A%7D%0A%0Avar%20bob%20%3D%20new%20Person('Bob%20Ross')%3B%0Abob.getFirstName()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
class Person {
  constructor() {
    var arr = [];
    if(arguments.length === 1) {
      arr = arguments[0].split(" ");
      this.firstName = arr[0];
      this.lastName = arr[1];
    } else if (arguments.length === 2) {
      this.firstName = arguments[0];
      this.lastName = arguments[1];      
    } else {
      this.firstName = undefined;
      this.lastName = undefined;
    }
  }
  setFirstName(first) {
    this.firstName = first;
  }
  setLastName(last) {
    this.lastName = last;
  }
  setFullName(firstAndLast) {
    var arr = firstAndLast.split(" ");
    this.firstName = arr[0];
    this.lastName = arr[1];
  }
  getFirstName() {
    var str = this.firstName; 
    return str;
  }
  getLastName() {
    return this.lastName;
  }
  getFullName() {
    return this.firstName + " " + this.lastName;
  }
  
  
}

var bob = new Person('Bob Ross');
bob.getFirstName();

```

**Comment by raisedadead** [comment]
@attributeofextension I am not sure, is this a bug report for a issue with the challenge, or you are looking for feedback on your code?

Please clarify further about the exact issue?

**Comment by raisedadead** [comment]
Hi @attributeofextension 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
