### ISSUE TITLE
Unable to click on "More Information" Button to expand on Vertical monitor

### ISSUE THREAD

**Issue by JRodDynamite** [FreeCodeCamp/freecodecamp#1260]
Can't click on the button to expand information. I guess, it does not work on mobile devices too (tested in chrome dev tools emulator).

![screenshot from 2015-07-11 16 01 22](https://cloud.githubusercontent.com/assets/4744582/8633446/4446b67e-27e6-11e5-809b-3a2886abd130.png)

**Comment by LumenTeun** [comment]
Thank you for reporting this, but this is a duplicate of #1103 and should be closed in favor of that one.

**Comment by JRodDynamite** [comment]
@LumenTeun - Thanks! Will close this! Duplicate: #1103
