### ISSUE TITLE
Remove word Free

### ISSUE THREAD

**Issue by Shubham-invent** [freeCodeCamp/freeCodeCamp#12609]
Anything if we mention free will loose it charm,write Free in subtext .I think We can rename it simply like CodeCamp - for the coders,by the coders Free Forever.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by OFFLlNE** [comment]
I like the word free there :) Actually I wonder if there has been a poll if people would prefer FCC to CC.
Just out of curiosity to know what people think

**Comment by raisedadead** [comment]
Please take up the discussion on the forum, the tracker is not a place for such debates.
