### ISSUE TITLE
Missing Letter Test Examples Not Thorough Enough

### ISSUE THREAD

**Issue by breatheloud** [freeCodeCamp/freeCodeCamp#12610]
#### Missing Letters

https://www.freecodecamp.com/challenges/missing-letters

#### Issue Description

This is not a problem, per se, but the test cases/examples are not rigorous enough to test for what the exercise asks for.  Namely, the test cases should use a letter besides `"a"` as its `str[0]` and miss a letter, I recommend changing the third or fourth case to be something like `"bcdf"` or `"wxz"` respectively.

I suggest this to be changed as the solution can merely return an `undefined` if the `str[0]` is not an `"a"`.

**Comment by Greenheart** [comment]
@breatheloud Thanks for reporting this! :smile:

I like your suggestions - The instructions don't say that all ranges will be starting with the letter "a", so this challenge needs better test cases.

I'll create a PR with the test cases you suggested and get this fixed shortly :blush:

**Comment by breatheloud** [comment]
Yeah, exactly! Thanks @Greenheart
