### ISSUE TITLE
My soultion works in Netbeans. I cannot make it work in CodePen.

### ISSUE THREAD

**Issue by humpfj** [freeCodeCamp/freeCodeCamp#12613]
I have a solution to the Random Quote Machine assignment. It works in Netbeans, my usual IDE. but I cannot port the solution to CodePen. What am I doing wrong?

#### Challenge Name

Here is my pen https://codepen.io/humpfj/pen/qRNwMB

#### Issue Description

It does not replace the initial quote and author information with data from the external source.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

 
I attached a copy of my HTML file from Netbeans in a PDF file.
[index_html.pdf](https://github.com/freeCodeCamp/freeCodeCamp/files/716451/index_html.pdf)

**Comment by OFFLlNE** [comment]
@humpfj thanks for reporting that issue.
Issue tracker is for reporting bugs.

You should check Helprooms
[CSS/HTML Help](https://gitter.im/FreeCodeCamp/Help)
[JS Help](https://gitter.im/FreeCodeCamp/HelpJavaScript)

You have 0 JS, maybe this is why it is not working

**Comment by Manish-Giri** [comment]
@humpfj Try to have your JavaScript code in the JS window of Codepen, instead of the `<head>` tags. Visit the help rooms linked above if you've got questions with how Codepen works.

**Comment by raisedadead** [comment]
The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
