### ISSUE TITLE
Pig latin does not let me pass, any ideas why?

### ISSUE THREAD

**Issue by Zsiguli** [freeCodeCamp/freeCodeCamp#12618]
Challenge [Pig Latin](https://www.freecodecamp.com/challenges/pig-latin#?solution=%0Avar%20englishWordArray%20%3D%20%5B%5D%3B%0Avar%20lastPart%20%3D%20%22%22%3B%0Avar%20cutCounter%20%3D%200%3B%0A%0Afunction%20vowelOrNot%20(letterToDecide)%7B%0A%20%20switch%20(letterToDecide)%20%7B%0A%20%20%20%20case%20%22a%22%3A%0A%20%20%20%20case%20%22e%22%3A%0A%20%20%20%20case%20%22i%22%3A%0A%20%20%20%20case%20%22o%22%3A%0A%20%20%20%20case%20%22u%22%3A%0A%20%20%20%20%20%20return%20true%3B%0A%20%20%20default%20%3A%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%7D%0A%7D%0A%0Afunction%20splitStringToArray%20(stringToSplit)%20%7B%0A%20%20englishWordArray%20%3D%20stringToSplit.split('')%3B%20%0A%7D%0A%0Afunction%20whereToCut%20(arrayToCut)%20%7B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%3CarrayToCut.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(vowelOrNot(arrayToCut%5Bi%5D))%20%7B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20cutCounter%2B%2B%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Afunction%20lastPartMaker%20()%20%7B%0A%20%20if%20(cutCounter%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20return%20%22way%22%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20%22ay%22%3B%0A%20%20%7D%0A%7D%0A%0Afunction%20translatePigLatin(str)%20%7B%0A%20%20splitStringToArray%20(str)%3B%0A%20%20whereToCut%20(englishWordArray)%3B%0A%20%20if%20(cutCounter%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20return%20str%20%2B%20lastPartMaker%20(cutCounter)%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20str.substr(cutCounter)%20%2B%20str.substr(0%2CcutCounter)%20%2B%20lastPartMaker%20(cutCounter)%3B%0A%20%20%7D%0A%7D%0A%0AtranslatePigLatin(%22eight%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36</code>.
I tested all the values and they returned correctly. I can't find where the problem is.

My code:
```javascript

var englishWordArray = [];
var lastPart = "";
var cutCounter = 0;

function vowelOrNot (letterToDecide){
  switch (letterToDecide) {
    case "a":
    case "e":
    case "i":
    case "o":
    case "u":
      return true;
   default :
      return false;
  }
}

function splitStringToArray (stringToSplit) {
  englishWordArray = stringToSplit.split(''); 
}

function whereToCut (arrayToCut) {
  for (var i = 0; i<arrayToCut.length; i++) {
    if (vowelOrNot(arrayToCut[i])) {
      break;
    } else {
      cutCounter++;
    }
  }
}

function lastPartMaker () {
  if (cutCounter === 0) {
    return "way";
  } else {
    return "ay";
  }
}

function translatePigLatin(str) {
  splitStringToArray (str);
  whereToCut (englishWordArray);
  if (cutCounter === 0) {
    return str + lastPartMaker (cutCounter);
  } else {
    return str.substr(cutCounter) + str.substr(0,cutCounter) + lastPartMaker (cutCounter);
  }
}

translatePigLatin("eight");

```

**Comment by OFFLlNE** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

Thank you, and happy coding.
