### ISSUE TITLE
Inform with the Paragraph Element

### ISSUE THREAD

**Issue by Nosisa** [freeCodeCamp/freeCodeCamp#12615]
#### Challenge Name

https://www.freecodecamp.com/challenges/inform-with-the-paragraph-element#?solution=%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cp%3EHello%20Paragragh%3C%2Fp%3E%0A

#### Issue Description

After I have created a p element below your h2 element, and give it the text "Hello Paragraph". It gives me an error when i run tests.

#### Browser Information

* Browser Name, Version:  Google chrome Version 55.0.2883.95 (64-bit)
* Operating System: macOS Sierra 10.12.2
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
<p>Hello Paragragh</p>
 
 
 
```
#### Screenshot

<img width="1376" alt="screen shot 2017-01-19 at 3 47 02 pm" src="https://cloud.githubusercontent.com/assets/8721664/22109116/06d2a8da-de5f-11e6-8305-c6d2a353b021.png">

**Comment by dhcodes** [comment]
@Nosisa you have a small typo. "Paragragh" should be Paragraph". The chat room is a wonderful place to double-check an issue. You can ask a question in the chat by clicking the Help button on the challenge page.

**Comment by Nosisa** [comment]
Oh my bad, Thank you
