### ISSUE TITLE
Basic Javascript -->Multiple Identical Options in Switch Statements. The evaluation is wrong whereas the code is correct.

### ISSUE THREAD

**Issue by glgeorgiou** [freeCodeCamp/freeCodeCamp#12617]
Challenge [Multiple Identical Options in Switch Statements](https://www.freecodecamp.com/challenges/multiple-identical-options-in-switch-statements#?solution=%0Afunction%20sequentialSizes(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20function%20sequentialSizes(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%20%20switch(val)%20%7B%0A%20%20%20%20%20%20case%201%3A%0A%20%20%20%20%20%20case%202%3A%0A%20%20%20%20%20%20case%203%3A%0A%20%20%20%20%20%20%20%20%20answer%3D%22Low%22%3B%0A%20%20%20%20%20%20%20%20return%20answer%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20case%204%3A%0A%20%20%20%20%20%20case%205%3A%0A%20%20%20%20%20%20case%206%3A%0A%20%20%20%20%20%20%20%20%20answer%3D%22Mid%22%3B%0A%20%20%20%20%20%20%20%20return%20answer%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%20case%207%3A%0A%20%20%20%20%20%20case%208%3A%0A%20%20%20%20%20%20case%209%3A%0A%20%20%20%20%20%20%20%20%20answer%3D%22High%22%3B%0A%20%20%20%20%20%20%20%20return%20answer%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%7D%0A%7D%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AsequentialSizes(1)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function sequentialSizes(val) {
  var answer = "";
  // Only change code below this line
  function sequentialSizes(val) {
  var answer = "";
  // Only change code below this line
    switch(val) {
      case 1:
      case 2:
      case 3:
         answer="Low";
        return answer;
        break;
      case 4:
      case 5:
      case 6:
         answer="Mid";
        return answer;
        break;
         case 7:
      case 8:
      case 9:
         answer="High";
        return answer;
        break;
  }
}
  
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
sequentialSizes(1);


```

**Comment by OFFLlNE** [comment]
@glgeorgiou thanks for reporting the issue.
I would not say that the code is correct, you call out `sequentialSizes(1);`
which does this part 
```
function sequentialSizes(val) {
  var answer = "";
```
and nothing else

**Comment by glgeorgiou** [comment]
@OFFLlNE thank you for your responce. It was my mistake. I evaluated and corrected my code and operates fine.
Please close this issue. 
Thank you
