### ISSUE TITLE
Basic CSS Section Not Displaying in Map

### ISSUE THREAD

**Issue by HKuz** [freeCodeCamp/freeCodeCamp#12623]
#### Challenge Name

Applies to entire "Basic CSS" section on the Beta site. The map jumps from "Basic HTML and HTML5" to "Applied Visual Design"

#### Issue Description

The `name` field in the `seed/challenges/01-responsive-web-design/basic-css.json` file is "Basic HTML and HTML5", (the same as the Basic HTML and HTML5 section), so the CSS section doesn't display on the map. This can be fixed by updating the `basic-css.json` name field to say "Basic CSS".

#### Browser Information

* Browser Name, Version: Happens on both Firefox and Chrome
* Operating System: Mac OS X El Capitan, 10.11.3 (someone needs to do a software update...)
* Mobile, Desktop, or Tablet: Desktop

**Comment by HKuz** [comment]
I can make this fix now if anyone else needs to confirm 😄

**Comment by no-stack-dub-sack** [comment]
@HKuz Is all of this going to be in staging now though once #12570 is merged? I don't know if that changes the necessity of doing this or not...

**Comment by HKuz** [comment]
@no-stack-dub-sack - it just went live! This issue is for the Beta site, the split CSS section isn't showing right now 😄

**Comment by HKuz** [comment]
Looks like we have the same issue for the new "Basic Data Structures" section (the `name` field has "Debugging"). Also the intro is still the Debugging one...

**Comment by HKuz** [comment]
Wow, @BerkeleyTrue already fixed these - closing!

**Comment by ChrisD1986** [comment]
#Fixaspace!!!
