### ISSUE TITLE
Introduction missing for Basic HTML and HTML5 section

### ISSUE THREAD

**Issue by HKuz** [freeCodeCamp/freeCodeCamp#12624]
#### Section Name

The Beta site Basic HTML and HTML5 section

#### Issue Description

This section currently lacks a landing page with introductory text.

**Comment by HKuz** [comment]
Self-assigning this one since I already have the text written.

**Comment by dhcodes** [comment]
You may have already noticed, but the Introduction to HTML5 page looks a bit wonky. Figured you might want to fix that one along with this.

**Comment by ChrisD1986** [comment]
#This?

**Comment by dhcodes** [comment]
@ChrisD1986 I suspect something is amiss with your notifications. If you visit your Settings on Github, then click Notifications, you should be able to turn off notifications for repos (freeCodeCamp?) you are watching.

**Comment by HKuz** [comment]
@dhcodes - yup - I just submitted a PR for this issue before I saw your comment. The 4 new challenges in this section have some formatting issues, and some of the tests aren't working. I'll open a separate issue for the "QA" stuff for those 👍
