### ISSUE TITLE
Adding issue: Exact Change Challenge

### ISSUE THREAD

**Issue by samsmith453** [freeCodeCamp/freeCodeCamp#12625]
Adding inside a for loop is providing the wrong answer. Where an addition provides 335.41 outside of the for loop, inside it returns 335.4099999999997. I have tested this with other sums too, with the same effect.

Exact Change

https://www.freecodecamp.com/challenges/exact-change

#### Browser Information

* Browser Safari, Version 10.0.1 : 
* Operating System: Mac OS Sierra 10.12.1 

#### Your Code

```js
 
 var cidtotal = 0;
  
  
  for(var a=0; a<cid.length; a++){
    cidtotal+= cid[a][1];
  }
  
  return cidtotal;
 
```

**Comment by raisedadead** [comment]
Please share screenshots and your full code.

**Comment by AaizAhmed** [comment]
@samsmith453 This is a very easy fix, I initially had the same issue. This is just the rounding error. 

Use:  **sum =  Number((sum).toFixed(2));**       OR   **sum = Number(Math.round(sum +'e2')+'e-2');**

after the For loop and it should fix the problem.

**Comment by Rpad-NS** [comment]
I circumvented this issue by converting all values to integers, by multiplying each of them with 100 on the beginning of the function. After the calculations with integers were done, the numeric values in returned array are simply divided by 100.
