### ISSUE TITLE
Introduction missing for Basic CSS section (Beta site)

### ISSUE THREAD

**Issue by HKuz** [freeCodeCamp/freeCodeCamp#12626]
#### Section Name

Beta site Basic CSS

#### Issue Description

The Basic CSS section needs a landing page with introductory text to start the section. The text was already written [in this comment](https://github.com/freeCodeCamp/CurriculumExpansion/issues/45#issuecomment-259490772). It needs to be put into a slide challenge at the front of the section.

**Comment by HKuz** [comment]
@dhcodes - as the author of the intro text, would you like to work on this? Figured you should get PR credit 😄

**Comment by dhcodes** [comment]
Sure thing, but I'll follow someone else's lead on adding the landing page :)

**Comment by HKuz** [comment]
Sure - I can put a placeholder in for CSS when I drop the HTML section in, or you can copy how it's done for some of the other sections. For example, if you look at the `applied-visual-design.json` file, you can copy that first challenge into the `basic-css.json`. It's a challenge type 7 where you just click "Finish" to move on. Then replace the title and text, and pick a few of the digits in the "id" and change them. Unfortunately, to get the paragraph and list formatting, you have to manually add `br` tags and the `ul` and `li` tags, respectively. Let me know!

**Comment by ChrisD1986** [comment]
Indeed!   Bring that shit!!

**Comment by dhcodes** [comment]
@HKuz Ah, didn't realize there were some already in the wild. I can hack that, but it will probably be tomorrow. Thanks for the help.

**Comment by ChrisD1986** [comment]
#TomorrowFace... #WakeStateYou!!!!

**Comment by HKuz** [comment]
@dhcodes - no problem. One minor comment on the text - since this section uses the `style` tag to hold CSS, should we mention that as a method to apply CSS? Maybe add it in to that paragraph right after the bullets that starts "CSS can be applied both as inline styles..."? Not critical, just a thought.

**Comment by HKuz** [comment]
I'm closing this issue because PR #12676 with the intro slide and text was merged.
