### ISSUE TITLE
Waypoint: Add Font Awesome Icons all of our Buttons

### ISSUE THREAD

**Issue by janschreiber** [FreeCodeCamp/freecodecamp#1262]
I think the title should have a 'to' after 'Icons'.

**Comment by LumenTeun** [comment]
Yes, that seems about right. Great chance to get some experience wth pull requests, hint hint. ;)

**Comment by janschreiber** [comment]
Hm, I had a look at what I believe is the [most recent version of the source code](https://github.com/FreeCodeCamp/freecodecamp/blob/612de6911e08bee18d3fbd412151415d50ca2d62/seed/challenges/bootstrap.json), and apparently it's already fixed. Thanks for the hint, btw.
