### ISSUE TITLE
Replace build a JavaScript Calculator to updated pen

### ISSUE THREAD

**Issue by arebai** [freeCodeCamp/freeCodeCamp#12622]
Challenge [Build a JavaScript Calculator](https://www.freecodecamp.com/challenges/build-a-javascript-calculator) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by arebai** [comment]
every body can test it with 2+2*5 it must show 12 but the calculator show 14

**Comment by Manish-Giri** [comment]
Yes, it looks like the operator precedence is buggy.

**Comment by raisedadead** [comment]
Oops... thanks for pointing out. The official working pen should be https://codepen.io/freeCodeCamp/full/PNKdjo/

But the challenge, is linking to an older pen. 

Thanks working on replacing the it.

**Comment by ChrisD1986** [comment]
operators,  thanks mrughesh

**Comment by no-stack-dub-sack** [comment]
@Manish-Giri @raisedadead @arebai This issue has been raised a bunch of times actually, AND is the very reason I ended up becoming a FCC contributor and started work on the [Testable Projects](https://github.com/freeCodeCamp/testable-projects-fcc) project. I reported the same issue in #10158, and it's not that the operator precedence is wrong, it's just using _immediate execution_ logic vs. _expression_ logic. That thread takes a seriously deep dive into the issue. 

What this ended up sparking is this: https://codepen.io/freeCodeCamp/full/wgGVVX/

When we go to the new curriculum, this will be the new example project, and as you can see, there is a new list of test cases, each with its own automated test. Test case 9 accounts for both logic types, and in the project intro - we will be pointing out to campers that there are 2 common kinds of calc logic, and that either can be used and the tests will still pass.

**Comment by raisedadead** [comment]
Hey @no-stack-dub-sack thanks for pointing that out, I will update the official collection with yours. Thanks.

Can you confirm that this is already in staging, and hence we can close as resolved.

**Comment by raisedadead** [comment]
I would be renaming the title as well to the challenge name, can you guide me to the current challenge name?

**Comment by no-stack-dub-sack** [comment]
@raisedadead It looks like this was just brought into staging when #12570's cousin was merged. @QuincyLarson should have included all the new pens in his PR and updated all the copy for those challenges. That particular project can be found [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/03-front-end-libraries/front-end-libraries-projects.json#L94). 

Actually, I think we decided on not adding a lot of copy to the challenge landing pages, so the note on calc logic needs to be added to the user story itself which I can do in the [Testable Projects](https://github.com/freeCodeCamp/testable-projects-fcc) repo.

**Comment by arebai** [comment]
Build a JavaScript Calculator Incomplete This the name of the challenge


Le 20 janv. 2017 17:27, "mrugesh mohapatra" <notifications@github.com> a
écrit :

**Comment by no-stack-dub-sack** [comment]
Also @raisedadead I think we should leave the old collection on FCC as is (aside from maybe changing the name) to preserve all the legacy projects. No reason why not I guess, right? The collection I shared is already on FCC official CP

**Comment by raisedadead** [comment]
Yup, that does work for me. Then I think we should switch the naming, convention in the collections?

**Comment by no-stack-dub-sack** [comment]
@raisedadead Sure, that works. Maybe change the Test Suites one to **Challenge Pens**, and change the old Challenge Pens collection to **Legacy Challenge Pens**
