### ISSUE TITLE
Introduction missing for Advanced Node and Express section (Beta site)

### ISSUE THREAD

**Issue by HKuz** [freeCodeCamp/freeCodeCamp#12637]
#### Section Name

Beta site Advanced Node and Express section

#### Issue Description

The Advanced Node and Express section needs a landing page with introductory text to start the section. It should go in the slide format (challenge type 7) at the front of the section and give a high-level overview of what's covered in the section.

**Comment by raghavraman** [comment]
Is there a specific way I could help? This is my first attempt for open source contribution

**Comment by marigerr** [comment]
@raisedadead  @raghavraman  

It looks like the Intro was already added Feb 6 and is live on beta site here:
https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/advanced-nodeexpress-introduction

Commit that added the intro : 
https://github.com/freeCodeCamp/freeCodeCamp/commit/8219ed4213f477a4c7c170f45cb69b0b246625fa

```
{
  "name": "Advanced Node and Express",
  "order": 3,
  "time": "5 hours",
  "helpRoom": "Help",
  "challenges": [
    {
      "id": "5895f6fff9fc0f352b528e62",
        "title": "Advanced Node/Express Introduction",
        "description": [
          [
            "",
            "",
            "<em>Authentication</em> is the process or action of verifying the identity of a user or process. Up to this point you have not been able to create an app utilizing this key concept.<br>The most common and easiest to use authentication middleware for Node.js is <a href='http://passportjs.org/'>Passport</a>. It is easy to learn, light-weight, and extremely flexible allowing for many <em>strategies</em>,
```

**Comment by codejockie** [comment]
Can I help? My first attempt at Open Source Contribution.

**Comment by sw-yx** [comment]
im unclear, is it already fixed? what is still lacking please?

**Comment by rcohane** [comment]
A landing page with introductory text has been added for the section and the issue should be closed.
![screen shot 2017-11-12 at 6 25 51 pm](https://user-images.githubusercontent.com/21317235/32704686-f5aeed86-c7d6-11e7-85f2-cf5921084338.png)

**Comment by rcohane** [comment]
@BerkeleyTrue Why was this added to "Deferred" even though the missing introduction was added?

**Comment by raisedadead** [comment]
Thanks @rcohane
