### ISSUE TITLE
Introduction missing for Information Security with HelmetJS

### ISSUE THREAD

**Issue by HKuz** [freeCodeCamp/freeCodeCamp#12634]
#### Section Name

Beta site Information Security with HelmetJS section

#### Issue Description

The Information Security with HelmetJS section needs a landing page with introductory text to start the section. It should go in the slide format (challenge type 7) at the front of the section and give a high-level overview of what it is.

**Comment by saqibnaveed** [comment]
Hello. I am new to open source contribution. I'd like to help

**Comment by erictleung** [comment]
@saqibnaveed if you're still interested in contributing and working on this issue, please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by saqibnaveed** [comment]
Okay Thanks :) :+1:
