### ISSUE TITLE
Introduction missing for jQuery section (Beta site)

### ISSUE THREAD

**Issue by HKuz** [freeCodeCamp/freeCodeCamp#12631]
#### Section Name

Beta site jQuery section

#### Issue Description

The jQuery section needs a landing page with introductory text to start the section. It should go in the slide format (challenge type 7) at the front of the section and give a high-level overview of what jQuery is.

**Comment by saqibnaveed** [comment]
Hello, I'd like to take on this issue.
Kindly guide me

**Comment by erictleung** [comment]
@saqibnaveed please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by saqibnaveed** [comment]
@erictleung Okay thank you :)
