### ISSUE TITLE
Ceasars Cipher Exercise Issue

### ISSUE THREAD

**Issue by icarobrandao** [freeCodeCamp/freeCodeCamp#12638]
Challenge [Caesars Cipher](https://www.freecodecamp.com/challenges/caesars-cipher#?solution=var%20arr%3D%20%5B%5D%3B%0Avar%20s%3D%22%22%3B%0Afunction%20rot13(str)%20%7B%20%2F%2F%20LBH%20QVQ%20VG!%0A%20%20for%20(var%20i%20in%20str)%7B%0A%20%20%20%20arr%5Bi%5D%20%3D%20str.charCodeAt(i)%3B%0A%20%20%7D%0A%20%20for%20(var%20j%20in%20arr)%7B%0A%20%20%20%20if(arr%5Bj%5D%3E%3D65%20%26%26%20arr%5Bj%5D%3C%3D77)%7B%0A%20%20%20%20%20%20arr%5Bj%5D%2B%3D13%3B%0A%20%20%20%20%7Delse%20if(arr%5Bj%5D%3E%3D78%20%26%26%20arr%5Bj%5D%3C%3D90)%7B%0A%20%20%20%20%20%20arr%5Bj%5D-%3D13%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20for%20(var%20k%20in%20arr)%7B%0A%20%20%20%20s%20%3D%20s%20%2B%20String.fromCharCode(arr%5Bk%5D)%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20s.toUpperCase()%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%0Arot13(%22SERR%20YBIR%3F%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

![captura de tela 2017-01-19 as 23 24 42](https://cloud.githubusercontent.com/assets/15710129/22133349/9191707a-de9e-11e6-9d42-681ca57e1b7a.png)

the return is right but the console don't admit it so I can't continue my journey.

My code:
```javascript
var arr= [];
var s="";
function rot13(str) { // LBH QVQ VG!
  for (var i in str){
    arr[i] = str.charCodeAt(i);
  }
  for (var j in arr){
    if(arr[j]>=65 && arr[j]<=77){
      arr[j]+=13;
    }else if(arr[j]>=78 && arr[j]<=90){
      arr[j]-=13;
    }
  }
  
  for (var k in arr){
    s = s + String.fromCharCode(arr[k]);
  }
  
  return s.toUpperCase();
}

// Change the inputs below to test
rot13("SERR YBIR?");

```

**Comment by erictleung** [comment]
@icarobrandao you have global variables in your code. Put them within your function and your code will pass. Our tests run the tests right after each other so global variables will change. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by ChrisD1986** [comment]
12 Happy coding # Drunk Face

**Comment by icarobrandao** [comment]
it worked now, thanks!
