### ISSUE TITLE
Introduction missing for Quality Assurance and Testing with Chai section (Beta)

### ISSUE THREAD

**Issue by HKuz** [freeCodeCamp/freeCodeCamp#12635]
#### Section Name

Beta site Quality Assurance and Testing with Chai section

#### Issue Description

The Quality Assurance and Testing with Chai section needs a landing page with introductory text to start the section. It should go in the slide format (challenge type 7) at the front of the section and give a high-level overview of what QA and testing is.

**Comment by padulam** [comment]
@raisedadead Is this one still up for grabs?

**Comment by dhcodes** [comment]
@padulam yes, all yours if you want it. Here's one I did for Redux recently if you want an example: https://github.com/freeCodeCamp/freeCodeCamp/pull/15605/files

**Comment by vkWeb** [comment]
@systimotic I think this should be closed.

**Comment by systimotic** [comment]
@vkWeb There is a challenge there now (https://beta.freecodecamp.org/en/challenges/quality-assurance-and-testing-with-chai/quality-assurance-introduction), but it still needs to be filled out with a proper introduction to the upcoming section 🙂

**Comment by vkWeb** [comment]
@systimotic  Sorry for that. 😞

**Comment by systimotic** [comment]
@vkWeb No worries! I'd rather check an issue twice that can stay open than leave an issue open that could be closed.

**Comment by ahmadabdolsaheb** [comment]
@moT01 Great fit. 
@HKuz How about the following draft?
When programs become more complex, you need to test them often to avoid breaking older functionalities as the new code is added. Chai is a testing library that could easily test the expected behaviors your programs. Using Chai you can write tests that describe your program's requirements and see if your program meets them.

**Comment by HKuz** [comment]
@ahmadabdolsaheb - looks good! I made some minor re-writes directly in your comment, feel free to make any other changes 👍

**Comment by ahmadabdolsaheb** [comment]
@HKuz PR made. 👍
