### ISSUE TITLE
Chrome can scroll horizontally in the challenge description.

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#12645]
#### Challenge Name

Any challenge, [for example this one](http://beta.freecodecamp.com/en/challenges/basic-css/change-the-font-size-of-an-element)

#### Issue Description

This is only noticeable when using **a laptop with a touch pad that can scroll horizontally**.
When using latest Chrome, I can scroll horizontally in the challenge description and this feels weird.
Using latest Firefox, I can only scroll vertically, as probably was intended.

##### Steps to reproduce
1. Visit any challenge in chrome.
2. Using a touch pad on a laptop, scroll horizontally in the description area.

##### Likely cause
* Some rouge CSS for the description-area.

#### Browser Information

* Browser Name, Version: Chrome 55.0.2883.87 (64-bit)
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

**Comment by systimotic** [comment]
This can be reproduced on most devices by pressing the middle mouse button inside the description area.

**Comment by dhcodes** [comment]
@systimotic this seems to be fixed. Can you confirm and close?
