### ISSUE TITLE
Exact Change 

### ISSUE THREAD

**Issue by Joe2718** [freeCodeCamp/freeCodeCamp#12640]
![argh](https://cloud.githubusercontent.com/assets/24241167/22134591/dd645578-de8d-11e6-9a49-d312a80faff9.jpg)

This is the third time looking at this and coming to the same dead end.  The only difference I'm seeing between my answer and the answer to pass it is empty decimals.  When I go to add them via precision or tofixed; I end up with it popping into a string type.  No one in help knew how to convert 0.5 to 0.50 without making it to a string so I'm thinking that what I've been focused on solving with this challenge isn't even relevant to the intent of the challenge.  My code has a ton of frustration written into it, Type jumping and floating point..  I'm not exactly proud of this code, I'm just in desperate need to figure out why this isn't passing?  I have no clue.  

Challenge [Exact Change](https://www.freecodecamp.com/challenges/exact-change#?solution=) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript


var values=[["PENNY", 0.01], ["NICKEL", 0.05], ["DIME", 0.10], ["QUARTER", 0.25], ["ONE", 1.00], ["FIVE", 5.00], ["TEN", 10.00], ["TWENTY", 20.00], ["ONE HUNDRED", 100.00]];
function checkCashRegister(price, cash, cid) {
	// console.log(cid);
  	var changeNum = (cash - price).toFixed(2);  // Alright, finally something small and works even though I'm using a string.  
  	// console.log(changeNum + " = cash - price      "+ cash + "<----cash   price---->"+ price);
 	var myCid = cid.reverse(); 
 	values.reverse();
 	var coins;
 	var change=[];
 	myCid.forEach(function (bill, index) {
 		// console.log(bill[0]+ "   "+ bill[1]);
 		// starting to go thru drawer
 		if (changeNum >= values[index][1]){
 			// going to try to give customer this denomination
 			// how many of these might I need?
 			coins = coinNum=Math.floor(changeNum/values[index][1]);
 			//console.log('I need ' +coins + " "+ bill[0]);
 			if(bill[1] >= coins * values[index][1]){
 				// I can do max here.
 				// console.log([bill[0],(coins * values[index][1]).toFixed(2)]);
 				var jspita = (coins * values[index][1]).toFixed(2);
 				change.push([bill[0],jspita]); // adding to bill report
 				changeNum =  (changeNum -(coins * values[index][1])).toFixed(2); // paying customer
 				bill[1]= (bill[1] -  (coins * values[index][1])).toFixed(2); // removing from drawing
 			} else {
 				// empty the drawer  in this denomination
 				if (bill[1] !== 0){ // if drawer doesn't have any of these, can't pay customer
 					change.push([bill[0],bill[1]]); // adding to bill report
	 				changeNum -= bill[1]; // paying customer
	 				bill[1] = 0; //  removing from drawer
 				}
 			}
 		}
 	// console.log(changeNum, bill[0],bill[1],values[index][1]);
	});
	cash = 0;  // need to total money left in drawer
	myCid.forEach(function (bill, index) { // clid = cash left in drawer
		if (typeof (bill[1]) == 'number' ){ // not sure how number with numbers end up with strings.
			cash += Number(bill[1].toFixed(2));
		} else {  
			cash += Number(Number(bill[1]).toFixed(2)); // This is freaking horrible!   toFixed changes crap to a string.. 

		}
	});

	// console.log(changeNum, cash);
	if (changeNum == 0 && cash == 0){
		change = "Closed";
	}
	// console.log(changeNum + " " + cash);
 	if (changeNum > 0){
		change="Insufficient Funds";
	}

	if (Array.isArray(change)){  // alright this is a crappy solution but I'm just tired of this challenge and fighting 'type'
		change.forEach(function (bill, index) {  
			// console.log(bill[1]);
			let t=  (Number(bill[1])*100).toFixed(0);
			let l = t.length; // precision is this plus 2 for the decimal places.
			// console.log(t);
			t = Number((Number(bill[1]).toPrecision(l)));
			// console.log(t);
	            // or 
	            bill[1]= Number(bill[1]);
		});
	}
  // Here is your change, ma'am.
  return change;
}

var blah =checkCashRegister(3.26, 100.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]]);
console.log(blah);


```

**Comment by Joe2718** [comment]
I changed var blah on the end to a testing loop that compares the array values with a copy/pasted array and it passes:

var test = checkCashRegister(3.26, 100.00, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.10], ["QUARTER", 4.25], ["ONE", 90.00], ["FIVE", 55.00], ["TEN", 20.00], ["TWENTY", 60.00], ["ONE HUNDRED", 100.00]]);

var answer = [["TWENTY", 60.00], ["TEN", 20.00], ["FIVE", 15.00], ["ONE", 1.00], ["QUARTER", 0.50], ["DIME", 0.20], ["PENNY", 0.04]];

var correct = true;
test.forEach((arr,index)=> {
	if (arr[1] !=  answer[index][1] || arr[0] != answer[index][0] ){
		correct=false;
		console.log(arr[1], answer[index][1]);
	}
});
console.log(correct);

**Comment by raisedadead** [comment]
@Joe2718 : 

Hi Joseph, sorry to hear and we share the frustration. 

We have recently modified this challenge and removed the precision after the decimals
It's currently live on our beta website [here](https://beta.freecodecamp.com/en/challenges/advanced-algorithm-scripting/exact-change) and will be soon moved to production website that you are on.

Meanwhile, you should continue with the other challenges.

ProTip: Add the below on top most line of your code:
```js
//# sourceURL=myCode.js
function checkCashRegister(price, cash, cid) {
...
...
...
}
```

Open the developer tools in Chrome (<kbd>F12</kbd>) and go to the sources tab, press <kbd>Ctrl</kbd> + <kbd>P</kbd>, type in the name that you assigned above : `myCode.js`

Now you can add breakpoints, and live debug your test case.
Hit us in the chat room if you still have issues figuring it out.

Closing it for the moment, as help with code issue, but if you do find that this could be a faulty test case, we will re-open.

Thanks for your patience, and Happy coding!

**Comment by Joe2718** [comment]
I posted it here because my answer is CORRECT and I am not receiving an answer of Correct.  
That means it IS a BUG.  

Why would you post this if it is horrible?  -- This is a bug, correct answer doesn't pass test for correct answer and yet is the correct answer.  Whether I like my code or not is irrelevant; my emotions during coding are also irrelevant.  I should have edited out my comments and probably should have gone back to the first version before I started trying to make 0.5 into 0.50 and still keep it a number.  Everything seems to make it a string and that's the ONLY difference that I can find at all in between my answer and the posted answer.  A number process to get a number with fixed decimals and I got a string really thru me a curve.  I still can't format ainto the 0.50 and have it remain a number.  
I had pictures showing my answer and the correct answer being equal.  Why would focus on a comment which has nothing to do with the code, the answer or the answer checker?

**Comment by raisedadead** [comment]
@Joe2718 please ignore the comments from other posters.

**Comment by Rpad-NS** [comment]
I got around the issue caused by floating point numbers by multiplying each entry with 100 on the very beginning of the function, so I had to work with integers only. After the calculations were made, the numbers in the final array were divided by 100, to get them back to floating point values.

**Comment by Joe2718** [comment]
I thought it was due to my answer lacking the .00 after the decimal point.  It actually turned out to be that I was using the same variable in global namespace and didn't expect a conflict there at all.
I'm pretty sure it was my values variable.  I just moved it inside the function and it passed.  
I was frustrated because I was looking for my issue in the wrong location which led to type frustration because I'm convinced it's impossible to have a value be 1.00 and be a value.  Value would immediately shorten to 1.  The answer shows the Value having the .00 and that had me chasing windmills.
I took it as a lesson to avoid using global variables when interacting with other code.  They're just so darn handy for debugging and holding all the options or ... checking your answers.
I never posted my final resolution because I had thought this was closed.  

Summary:
The code above should pass just by moving the global variable variable inside the function.  
I also should have removed my comments, venting as I code doesn't need to be public.

**Comment by Joe2718** [comment]
I just gotta share this because this code is so ridiculous.   Most of this code and comments is me trying to chase down something that never existed.  Moving the variable inside was something I did just to follow better coding practices and completely unrelated to me searching for my bug; I was quite shocked when it passed.
