### ISSUE TITLE
[beta] Section order - Should Basic HTML come before Basic CSS?

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#12646]
#### Challenge Name

N/A - this can be seen [in the map](https://beta.freecodecamp.com/en/map)

#### Issue Description

Right now, Basic CSS is the first section of the curriculum. I think Basic HTML should be first instead. The first HTML challenge even states "Welcome to Free Code Camp's first coding challenge".

#### Screenshot

![challenge-order](https://cloud.githubusercontent.com/assets/6125097/22143382/22708080-defa-11e6-8545-ac80e6de718d.png)

**Comment by HKuz** [comment]
Indeed @Greenheart - looks like the order needs to be adjusted in the seed files for that section. Both HTML and CSS have order 0, and Applied Visual Design is 1. Those three need to be HTML (0), CSS (1), and Applied Visual Design (2).

**Comment by HKuz** [comment]
I have to jump into the seed files for these sections to clean up some formatting on the new challenges. I can make this order change at the same time.

**Comment by Greenheart** [comment]
@HKuz Thanks, that would be great! :smile:
