### ISSUE TITLE
AurelioJuarezCortez.

### ISSUE THREAD

**Issue by aureliojuarezcortez** [freeCodeCamp/freeCodeCamp#12647]
Content Hidden - by mod [raisedadead]

**Comment by aureliojuarezcortez** [comment]
wowbeachesfackall

**Comment by raisedadead** [comment]
@aureliojuarezcortez please stop spamming the issue tracker. If you have accidentally subscribed to emails from the tracker:

Visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select **"Not watching"**.
