### ISSUE TITLE
[beta] Basic HTML - challenge "Add Images to your Website" feels out of place

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#12659]
#### Challenge Name

[Add Images to your Website](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/add-images-to-your-website)

#### Issue Description

After completing [Basic HTML - Fill in the blank with placeholder text](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/fill-in-the-blank-with-placeholder-text), I get redirected to the challenge linked above.

This challenge feels out of place since this is one of the first 10 coding challenges that a camper will see. The code changes too much from the last challenge. Additionally, the template code contains things not yet mentioned.

Will the content of this image-challgenge be changed to just teach how to add an image (and skip the CatPhotoApp example)?
Or, should this be moved to a later point?

I like the idea of separating the HTML-course from the CSS-course. The problem is just that the challenges right now follow the format of the previous CatPhotoApp example, where both technologies were taught at once.

#### Browser Information

* Browser Name, Version: Chrome 55
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

**Comment by raisedadead** [comment]
More info in the description?

**Comment by Greenheart** [comment]
@raisedadead Sorry, dropped my keyboard ;)

**Comment by HKuz** [comment]
@Greenheart - right on about having CSS in the HTML challenges. After splitting the HTML and CSS sections, the plan is to go through and remove CSS from the HTML ones. (Plus fix any other sequencing issues with the addition of a few challenges, so they flow better). I'm going through this section now and listing all the things I catch. I also agree that the image challenge does seem out of place. Even with the CSS stripped out, I'd say we could move it after the Uncomment / Comment HTML challenges.

**Comment by Greenheart** [comment]
> Even with the CSS stripped out, I'd say we could move it after the Uncomment / Comment HTML challenges.

@HKuz Sounds like a good idea :blush:

**Comment by HKuz** [comment]
Great, @Greenheart - I'm working on a PR for this section and am making the re-order change now.
