### ISSUE TITLE
[beta] : Different items in react and non-react pages for Community drop down

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#12651]
Non-react profile page:

![image](https://cloud.githubusercontent.com/assets/1884376/22150228/eb2a8690-df3d-11e6-82c6-3f75aacdd09a.png)

React settings page:
![image](https://cloud.githubusercontent.com/assets/1884376/22150253/0885e266-df3e-11e6-9086-e41b0bab4e28.png)

**Comment by GiacomoLaw** [comment]
Any links to the files involved? I can't seem to find them :confused:
