### ISSUE TITLE
[beta] "HTML" spelled "Html" - Basic HTML Challenges

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#12657]
### Challenge Name

Most, if not all, of the basic HTML challenges.

#### Issue Description
The challenge title displayed in the top left corner as well as the page title in the browser are using "Html" instead of "HTML".

I think all occurances of "Html" should be changed to "HTML" for consistency. Since HTML is an abbreviation, it feels natural to use all caps.

This is similar to #12643 

#### Browser Information

* Browser Name, Version: N/A
* Operating System: N/A
* Mobile, Desktop, or Tablet: N/A

**Comment by Greenheart** [comment]
@HKuz Would you mind fixing this as well?

If you want to pair on this, message me on Gitter :blush:

**Comment by HKuz** [comment]
@Greenheart - yes, good point on both Css and Html. It looks like @dhcodes has a PR open to fix the names in #12639 it just hasn't been QA'd/merged yet. Let's see if that does the trick and revisit if it's still an issue...

**Comment by Greenheart** [comment]
@HKuz Good idea, let's do that!
