### ISSUE TITLE
[beta] Minified React Error #32 in Basic HTML Challenge

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#12656]
#### Challenge Name
[Basic Html and Html5: Introduction to HTML5 Elements](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/introduction-to-html5-elements)

#### Issue Description
The challenge page is stuck in loading since the challenge framework code throws the following error:
![react-error-basic-html](https://cloud.githubusercontent.com/assets/6125097/22155822/24cbce34-df31-11e6-8456-5c656eb47075.png)
The console shows the same error 44 times.

Neither reloading, emptying of cache or disabling browser extensions helps.
This affects Chrome as well as Firefox.

#### Browser Information
* Browser Name, Version: Firefox 50.1.0 and Chrome 55.0.2883.87 (64-bit)
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

**Comment by Greenheart** [comment]
@VarCI-bot Thanks but no thanks.

**Comment by systimotic** [comment]
I can reproduce, but not in my local dev environment 😕

**Comment by raisedadead** [comment]
@Greenheart when you have a moment can you please check and close, I think this is resolved.

**Comment by Greenheart** [comment]
@raisedadead This challenge now works as expected! :blush:

Closing.
