### ISSUE TITLE
chrome-dev-tools-sources uses vague determiner 'these'

### ISSUE THREAD

**Issue by pleabargain** [freeCodeCamp/freeCodeCamp#12658]
#### Challenge Name

https://www.freecodecamp.com/videos/chrome-dev-tools-sources
#### Issue Description

from page 
"These breakpoints are already established, but you can edit where they are in the code."

"These" is vague as there is no previous mention of breakpoints from prev. question.

#### Browser Information

* Browser Name, Version: 
chrome 
Google Chrome	55.0.2883.87 (Official Build) m (64-bit)
Revision	ad0be09aa3ca814168d079b52825f6f80e22f0e8-refs/branch-heads/2883@{#723}
OS	Windows 
JavaScript	V8 5.5.372.32
* Operating System: OS	Windows 

* Desktop: 

#### Your Code

```js
 
 
 
```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/640846/22156425/37b33736-df44-11e6-832c-a5ffa6a1ae9d.png)

**Comment by Greenheart** [comment]
@pleabargain Thanks for reporting!

I agree, this phrasing is somewhat unclear.

I suggest we change this statement to "Breakpoints are already established, but you can change where they are in the code". What do you think?

This could be a good issue for someone who want to get started contributing to open source.

**Comment by Syntactual** [comment]
I can work on this one; this is my first time contributing

**Comment by pleabargain** [comment]
I would have submitted an edit myself but I couldn't find the page in question on github! :(

**Comment by Syntactual** [comment]
yeah i am having an issue finding it myself

**Comment by Greenheart** [comment]
@pleabargain @Syntactual Sorry for the inconvenience, I can't find the seed files myself :sweat_smile: 

There will be many issues like this one in the coming weeks so if you want to contribute, just keep your eyes open! :blush:

@freeCodeCamp/moderators Could anyone please tell us where the video challenges can be found?

**Comment by systimotic** [comment]
@Greenheart They were removed in staging, because there are plans of dynamically pulling them in through the YouTube API. I'm not sure what the best way to do this now is.

/cc @atjonathan

**Comment by Syntactual** [comment]
Should I pick a different issue?

**Comment by systimotic** [comment]
@Syntactual Yeah, that's probably a good idea. There probably won't be anything to commit for this challenge. I think we'll have someone who has the permission on the YouTube channel update the description.

**Comment by Syntactual** [comment]
ok cool

**Comment by pleabargain** [comment]
@Syntactual 
Where is the seed though? I've looked here: https://github.com/pleabargain/freeCodeCamp/tree/staging/seed/challenges
but no joy... 
thanks

**Comment by systimotic** [comment]
@pleabargain See https://github.com/freeCodeCamp/freeCodeCamp/issues/12658#issuecomment-274271477

**Comment by pleabargain** [comment]
ok, thanks...
