### ISSUE TITLE
The correct solution is not recognized by the tests

### ISSUE THREAD

**Issue by doxanthropos** [freeCodeCamp/freeCodeCamp#12668]
Challenge [change-the-color-of-text](http://beta.freecodecamp.com/en/challenges/basic-css/change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
The challenge says that to pass, the h2-element has to be red. As you see further down, it is. The preview shows the h2 to be red. But the tests fail with the message: "Your h2 element should be red."

```html


<h2 style="color: red">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

Maybe related to [issue 12644](https://github.com/freeCodeCamp/freeCodeCamp/issues/12644)

**Comment by getoutb1** [comment]
Stop

**Comment by raisedadead** [comment]
@getoutb1 

Hello!

Looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) or click on the image below and select **"Not watching"**.

[![image](https://cloud.githubusercontent.com/assets/1884376/15005313/9ba8a14a-11e0-11e6-81cb-d7cfe6b66a30.png)](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription)


We are sorry for your inconvenience!

**Comment by systimotic** [comment]
Hi @doxanthropos! Thanks for reporting this issue.

I think this is probably related to https://github.com/freeCodeCamp/freeCodeCamp/issues/12677 / https://github.com/freeCodeCamp/freeCodeCamp/issues/10595

Could you please check that?

**Comment by doxanthropos** [comment]
Same problem, but especially #10595 is more complete in the bug description. So I will close this one as a duplicate.
