### ISSUE TITLE
"npm dist-add" instead of "npm dist-tag add"

### ISSUE THREAD

**Issue by NicksIdeaEngine** [freeCodeCamp/freeCodeCamp#12662]
Challenge [Manage Packages with npm](https://www.freecodecamp.com/challenges/manage-packages-with-npm) has an issue.

User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.

In part 11 of the NPM challenge, the description asks us to use `npm dist-add user@1.0.1 beta`.  Running `npm help dist-add` comes up with no results.

I think it should say `npm dist-tag add user@1.0.1 beta`.

**Comment by dhcodes** [comment]
@NicksIdeaEngine freeCodeCamp does not oversee the how-to-npm project and it will soon be replaced with challenges that are controlled by freeCodeCamp. You're welcome to open an issue on their repo: https://github.com/workshopper/how-to-npm
