### ISSUE TITLE
JSON APIs and AJAX "Convert JSON Data to HTML" no json data provided 

### ISSUE THREAD

**Issue by Zoorken** [freeCodeCamp/freeCodeCamp#12660]
#### Challenge Name

https://www.freecodecamp.com/challenges/convert-json-data-to-html

#### Issue Description

It would be good if the JSON-data we are going to transform into html is provide in the side. As it is now i can't try myself but depends on the solution provided. If this JSON-data/snippet would be provided it would be easier to understand what we are doing and not just following blindley.

**Comment by Zoorken** [comment]
```
[  
   {  
      "id":0,
      "imageLink":"https://s3.amazonaws.com/freecodecamp/funny-cat.jpg",
      "altText":"A white cat wearing a green helmet shaped melon on it's head. ",
      "codeNames":[  
         "Juggernaut",
         "Mrs. Wallace",
         "Buttercup"
      ]
   }
```

**Comment by raisedadead** [comment]
Thanks @Zoorken, looks valid concern to me.

/cc @HKuz

**Comment by codeman869** [comment]
@raisedadead What about something like this?

![screen shot 2017-01-21 at 1 20 42 pm](https://cloud.githubusercontent.com/assets/10450602/22177890/b577b280-dfdc-11e6-8d26-3a4567bb290d.png)

**Comment by raisedadead** [comment]
@codeman869 yes. but would like views from others.

**Comment by HKuz** [comment]
Apologies for the delayed response - I agree @Zoorken and @raisedadead that adding this info would better help folks see what they're doing in the challenge.

@codeman869 - that's an elegant solution, I'm on board with adding the example snippet 👍

**Comment by codeman869** [comment]
@HKuz Great, I'll send a pull request when I get home tonight. :+1:
