### ISSUE TITLE
[beta] project landing pages need CDN link and link to test suite pen

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#12661]
The following files need to be updated with the correct URL for the blank pen which houses the test suites (right now it links to the same pen on an un-official codepen account which I was using to test these) and the correct CDN link (it currently reflects my repo, but have a new CDN since the repo transferred ownership):

`freeCodeCamp/seed/challenges/01-responsive-web-design/responsive-web-design-projects.json`
`freeCodeCamp/seed/challenges/03-front-end-libraries/front-end-libraries-projects.json`
`freeCodeCamp/seed/challenges/04-data-visualization/data-visualization-projects.json`

I'm happy to take this one on since I know what needs to be changed where.

Also @QuincyLarson - 1 thing:
- I know we were trying not to have a lot of copy for these, but I think for the calc project, the landing page is a good place to make a note about the 2 different types of calc logic, since this issue has been raised so many times. (including one just today :smile: ) It is a bit long to include in the user stories themselves. 

Here is the note:

> Note On Calculator Logic: It should be noted that there are two main schools of thought on calculator input logic: immediate execution and formula logic (our example utilizes formula logic and observes order of operation precedence, immediate execution does not). Either is acceptable, but please note that depending on which you choose, your calculator may yield different results than ours for certain equations (see below example). As long as your math can be verified by another production calculator, please do not consider this a bug.
>
>EXAMPLE: 
> - 3 + 5 x 6 - 2 / 4 =
    - Immediate Execution Logic: 11.5
    - Formula/Expression Logic: 32.5

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack Thanks for creating this issue, and for the additional details on the calculator app. I agree with your recommended changes, and that you're the ideal person to do this since you're familiar with these projects.
