### ISSUE TITLE
[beta] Missing challenge in Basic Algorithm Scripting

### ISSUE THREAD

**Issue by leonfeng** [freeCodeCamp/freeCodeCamp#12673]
#### Issue Description

There is an empty list item with no challenge name under the Basic Algorithm Scripting section.

#### Browser Information

* Browser Name, Version: Google Chrome v55.0.2883.95
* Operating System: macOS 10.12.2
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![screen shot 2017-01-21 at 07 05 34](https://cloud.githubusercontent.com/assets/241553/22171564/2c493e16-dfaa-11e6-9a0b-8a29b2350e45.png)

**Comment by no-stack-dub-sack** [comment]
closing as duplicate ☝️
