### ISSUE TITLE
[beta] Introduction to HTML5 Elements : Fails test case

### ISSUE THREAD

**Issue by Bakermg** [freeCodeCamp/freeCodeCamp#12671]
Challenge [introduction-to-html5-elements](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/introduction-to-html5-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html 
<h2>CatPhotoApp</h2>
<main>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.
</p>
</main>
```

**Comment by HKuz** [comment]
@Bakermg  again, thank you for reporting this issue! The open PR (#12633) has a fix for this challenge's failing test as well. I'm going to close this issue since it should be resolved soon. Thank you for the help QA'ing the new challenges!
