### ISSUE TITLE
[Beta] : Define the Head and Body of an HTML Document : Fails test case

### ISSUE THREAD

**Issue by Bakermg** [freeCodeCamp/freeCodeCamp#12670]
Challenge [define-the-head-and-body-of-an-html-document](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/define-the-head-and-body-of-an-html-document) has an issue.

User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.

**Please describe how to reproduce this issue, and include links to screenshots if possible.**

fails test and says the head should wrap the title element also the example of page layout is not showing, I am using chrome canary browser

```html
<!DOCTYPE html>
<html>
<head>
<title>The best page ever</title>
</head>
<body>
<h1>The best page ever</h1>
<p>Cat ipsum dolor sit amet, jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed. Go into a room to decide you didn't want to be in there anyway. I like big cats and i can not lie kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff. Meow i could pee on this if i had the energy for slap owner's face at 5am until human fills food dish yet scamper. Knock dish off table head butt cant eat out of my own dish scratch the furniture. Make meme, make cute face. Sleep in the bathroom sink chase laser but pee in the shoe. Paw at your fat belly licks your face and eat grass, throw it back up kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
</body>
</html>  
```

**Comment by HKuz** [comment]
@Bakermg thanks for reporting this issue! There's an open PR (#12633) that has a fix for the failing test in this challenge. I'm going to close this issue since it should be resolved soon. Thanks so much for the help QA'ing the new challenges!
