### ISSUE TITLE
Returning Boolean values from functions

### ISSUE THREAD

**Issue by sureshp1994** [freeCodeCamp/freeCodeCamp#12678]
Challenge [Returning Boolean Values from Functions]
solutions:

My code:
```javascript

function isLess(a, b) {
  // Fix this code
  return a < b;
}

// Change these values to test
isLess(10, 15);

```

**Comment by raisedadead** [comment]
@sureshp1994 I can pass the challenge with your code. Can you reset and retry? And also clear your cookies if that doesn't work.
