### ISSUE TITLE
CSS Styles applied but I can't get past the challenge

### ISSUE THREAD

**Issue by Kimkykie** [freeCodeCamp/freeCodeCamp#12679]
Challenge [create-visual-balance-using-the-textalign-property](http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-visual-balance-using-the-textalign-property) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<style>
h4 {
  text-align: center;
}
p {
  text-align: justify;
}
.links {
  margin-right: 20px;
  text-align: left;
}
.fullCard {
  border: 1px solid #ccc;
  border-radius: 5px;
  margin: 10px 5px;
  padding: 4px;
}
.cardContent {
  padding: 10px;
}
</style>
<div class="fullCard">
<div class="cardContent">
  <div class="cardText">
    <h4>Google</h4>
    <p>Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University.</p>
  </div>
  <div class="cardLinks">
    <a href="https://en.wikipedia.org/wiki/Larry_Page" class="links">Larry Page</a>
    <a href="https://en.wikipedia.org/wiki/Sergey_Brin" class="links">Sergey Brin</a>
  </div>
</div>
</div>

    ```

**Comment by systimotic** [comment]
Hi @jamesbcn! Thanks you for reporting this issue.

It looks like you're having the same issue as #12677 / #10595 / #12668 / #12684, so I'm closing this as a duplicate.
To clarify, your code is correct, and you should be able to pass this challenge in a different browser.
If I got that wrong, please reopen this issue with more information.

Happy coding!
