### ISSUE TITLE
errors in compiler

### ISSUE THREAD

**Issue by WaheedRehman** [freeCodeCamp/freeCodeCamp#12675]
#### Challenge Name

https://www.freecodecamp.com/challenges/add-images-to-your-website#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22Kitten%22%3E%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20

#### Issue Description

I have coded well the image tag src and alt attributes but when i tap the run the tests button only the question about alt attribute is green and the above two i.e. img tag and src attribute are still red.

#### Browser Information

* UC Browser, 11.0.5.850: 
* Android 5.0: 
* Mobile: 

#### Your Code

```js
 <img src="https://bit.ly/fcc-relaxing-cat" alt="Kitten">
 
 
```

**Comment by WaheedRehman** [comment]
I can't add screenshot from my mobile.

**Comment by raisedadead** [comment]
Your code passes for me on a desktop, and on chrome on android. Can you check if that helps.

**Comment by ppresby91** [comment]
how do I make it to where I stop getting millions of emails everytime someone comments

**Comment by raisedadead** [comment]
Hello!

Looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) or click on the image below and select **"Not watching"**.

[![image](https://cloud.githubusercontent.com/assets/1884376/15005313/9ba8a14a-11e0-11e6-81cb-d7cfe6b66a30.png)](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription)


We are sorry for your inconvenience!

**Comment by WaheedRehman** [comment]
Yes it worked. Google chrome on android worked perfectly.
Thanks

**Comment by raisedadead** [comment]
Thanks for letting us know, happy coding!
