### ISSUE TITLE
[beta] After trying to create an user with associated email, am redirected to a blank page

### ISSUE THREAD

**Issue by OFFLlNE** [freeCodeCamp/freeCodeCamp#12681]
After creating an user in beta(tried the same email I have FCC associated with). I was redirected to [http://beta.freecodecamp.com/api/users](http://beta.freecodecamp.com/api/users)

And all I see, is `{}`

After refreshing this page, I am getting the error displayed: `The xxxxxxxxxx@gmail.com email address is already associated with an account. Try signing in with it here instead.` With what I did log in afterwards

* Browser Name, Version: Chrome Version 55.0.2883.87
* Operating System: Windows 7 64bit

**Comment by dhcodes** [comment]
This is how it has been on staging for awhile. I suspect it has something to do with the database not being connected.

**Comment by systimotic** [comment]
Sign in and sign up are no longer separate now that passwordless has been implemented, so I'm closing this issue. If something like this does come up again, please comment and we'll reopen.

Happy coding!
