### ISSUE TITLE
Your h2 element should be red.

### ISSUE THREAD

**Issue by jamesbcn** [freeCodeCamp/freeCodeCamp#12684]
Challenge [change-the-color-of-text](http://beta.freecodecamp.com/en/challenges/basic-css/change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html

<h2 style="color: red">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by systimotic** [comment]
Hi @jamesbcn! Thanks you for reporting this issue.

It looks like you're having the same issue as #12677 / #10595 / #12668, so I'm closing this as a duplicate.
If I got that wrong, please reopen this issue with more information.

Happy coding!

**Comment by systimotic** [comment]
To clarify, you should be able to pass this challenge with the same code in a different browser.
