### ISSUE TITLE
[Beta] Code on a new challenge with wrong syntax

### ISSUE THREAD

**Issue by OFFLlNE** [freeCodeCamp/freeCodeCamp#12685]
#### Challenge Name
[Basic Css: Understand Absolute versus Relative Units](http://beta.freecodecamp.com/en/challenges/basic-css/understand-absolute-versus-relative-units)

#### Issue Description
Just got to this challenge and the code in it is displayed with wrong syntax

#### Browser Information

* Browser Name, Version: Chrome Version 55.0.2883.87
* Operating System:  Win 7 64bit

#### Screenshot
![image](https://cloud.githubusercontent.com/assets/8721312/22173794/d0a4cde2-dfd5-11e6-9aa0-7c640c49b1d7.png)

**Comment by OFFLlNE** [comment]
Not sure if this is the same issue described in #12653

**Comment by HKuz** [comment]
@OFFLlNE - great catch! I hadn't seen that in #12653, but I just amended the open PR (#12663) for those other changes to make this fix. I'm going to close this issue because the edit is pending. Thanks so much for the help QA'ing Beta!
