### ISSUE TITLE
Bug with HTML Convert Entities Bonfire

### ISSUE THREAD

**Issue by padulam** [FreeCodeCamp/freecodecamp#1268]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. Please describe how to reproduce it, and include links to screen shots if possible. 

I continue to have issues with this bonfire. I believe the following code should pass:

<pre>function convert(str) {
 
  var charCodes = {
      39: "&#39;", //'
      38: "&amp;",//&
      60: "&lt;",//<
      62: "&gt;",//>
      34: "&quot;"//"
  };
    
  str = str.replace(/['<>"&]/g, function(code){
      return charCodes[code.charCodeAt(0)]; 
  });
  
  return str;
}

convert('Dolce & Gabbana');
</pre>

However, it continues to fail on the same line: 

assert.strictEqual(convert("Shindler's List"), 'Shindler's List', 'should escape characters');should escape characters: expected 'Shindler's List' to equal 'Shindler's List'

I have tried variations of this algorithm, but they all fail on this same test and from what I can tell there is no issue with the code.

**Comment by magicLamp76** [comment]
Yes. I get the same errors for this code:

```javascript
function convert(str) {
  return str.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("'", "&apos;").replace('"', "&quot;");
}
```

**Comment by kennethmath** [comment]
I thought I was starting to learn something but ended up list again

**Comment by cristianvnica** [comment]
This code was passing: 
```
function convert(str) {
  // &colon;&rpar;
  return str.replace(/&/g, '&amp;')
            .replace(/'/g, '&apos;')
            .replace(/"/g, '&quot;')
            .replace(/>/g, '&gt;')
            .replace(/</g, '&lt;');
}

convert('Dolce & Gabbana');
```
It's easier to discuss these issues first here: https://gitter.im/FreeCodeCamp/HelpBonfires

**Comment by BerkeleyTrue** [comment]
@cristianvnica Thanks for your help.

@padulam Please Remember [RSA](https://github.com/FreeCodeCamp/freecodecamp/wiki/How-to-get-help-when-you-get-stuck) in the future.

Happy Coding!
