### ISSUE TITLE
Typo - Waypoint: Ditch Custom CSS for Bootstrap

### ISSUE THREAD

**Issue by poolemark** [FreeCodeCamp/freecodecamp#1269]
In the steps for completing the challenge there are typos on the first and second steps:

      You h2 element should no longer have the class "red-text".
      You h2 element should now have the class "text-primary".

"You" needs to be changed to "Your" on each line.

**Comment by poolemark** [comment]
I see that ticket #1213 shows this as fixed, but I am still seeing it.

**Comment by CoeusCC** [comment]
Came here to say the same. I don't know what their release cycle is, but good to see that it's been addressed. 

https://github.com/FreeCodeCamp/freecodecamp/commit/628bf976d501c662e4a471aa5c1f686eff06b7d2

**Comment by alexlincoln** [comment]
@poolemark @CoeusCC The issue was addressed but not merged/fixed, feel free to submit a new PR

**Comment by benmcmahon100** [comment]
No new things will be deployed until the beta goes live
