### ISSUE TITLE
[BETA] Applied Visual Design: Create Visual Balance Using the Text-align Property

### ISSUE THREAD

**Issue by computerluca** [freeCodeCamp/freeCodeCamp#12697]
Challenge [create-visual-balance-using-the-textalign-property](http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-visual-balance-using-the-textalign-property) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
This is my HTML Code. I followed the instruction in the challenge, but it keeps saying Keep trying.

```html
    
    
<style>
h4 {
  text-align:center;
}
p {
  text-align:justify;
}
.links {
  margin-right: 20px;
  text-align:left;
}
.fullCard {
  border: 1px solid #ccc;
  border-radius: 5px;
  margin: 10px 5px;
  padding: 4px;
}
.cardContent {
  padding: 10px;
}
</style>
<div class="fullCard">
<div class="cardContent">
  <div class="cardText">
    <h4>Google</h4>
    <p>Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University.</p>
  </div>
  <div class="cardLinks">
    <a href="https://en.wikipedia.org/wiki/Larry_Page" class="links">Larry Page</a>
    <a href="https://en.wikipedia.org/wiki/Sergey_Brin" class="links">Sergey Brin</a>
  </div>
</div>
</div>

    ```

**Comment by systimotic** [comment]
Hi @jamesbcn! Thanks you for reporting this issue.

It looks like you're having the same issue as #12677 / #10595 / #12668 / #12684 / #12679, so I'm closing this as a duplicate.
To clarify, your code is almost correct, and you should be able to pass this challenge in a Chrome (it's the only browser I have found that is working right now 😅).

Happy coding!
