### ISSUE TITLE
[beta] final QA of basic DS section

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#12693]
The formatting in this section could use some work. Challenge instructions need key words wrapped in `<code>`, code examples should go in `<blockquote>`s like the rest of the challenges, and the test cases are not displaying correctly, they are displaying the asserts as well as the message (I think this is because `message: ....` was left out). This should be fixed in the seed code. As partially responsible for this section, I can fix this. 

![image](https://cloud.githubusercontent.com/assets/18563015/22176115/eb02a8f8-dfd0-11e6-9601-8438c188561f.png)
Needs `<blockquote>` for example code ☝️ 

![image](https://cloud.githubusercontent.com/assets/18563015/22176121/12a1bb56-dfd1-11e6-8955-9b906cdbd630.png)
Test cases need to display correctly ☝️ 

![image](https://cloud.githubusercontent.com/assets/18563015/22176138/54cf1ed8-dfd1-11e6-944f-d9c9388e2388.png)
Challenge instructions need `<code>` tags ☝️

**Comment by HKuz** [comment]
This is great @no-stack-dub-sack!! Also, I think your hunch about the missing "message: " in the `assert` tests is right. I ran into that in a challenge in the HTML section. 

For general formatting, you nailed the `code` and `blockquote` examples. Also, if there are any notes, we generally put them in the form `<strong>Note</strong><br>Rest of note text...`. And if we decide to keep the "Instructions", those go in `h4` tags. (discussion pending in issue #12688 )

**Comment by no-stack-dub-sack** [comment]
@HKuz Perfect! Thanks for the tips, yeah, I just noticed the `h4` thing as well when comparing other challenges as well. I will keep an eye on that issue and go from there

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack Thanks for the PR. is this resolved?

**Comment by no-stack-dub-sack** [comment]
All the formatting and refactoring for these is now done, and I would say this section is pretty well QAd at this point. I've worked through all challenges several times and feel pretty good about them. Leaving this open for now though as it wouldn't hurt to get one more set of eyes on them at some point. And interested to see if @bonham000 has any additional Data Structure wisdom to add to the array section.

**Comment by raisedadead** [comment]
Just a thought, do we plan to use, ES6 as seen in some challenge seed in this section, or that is a different issue?

**Comment by no-stack-dub-sack** [comment]
@raisedadead so, since this section came after ES6, we thought it would be ok to use `let` and `const` in these challenges

However, if we want to remove it, that is fine too. The only reason it's really issue now is because of the linter settings. Which I believe we are working on in another issue?

**Comment by HKuz** [comment]
@no-stack-dub-sack @raisedadead - I'd say using ES6 in a section is fair game if it comes after the ES6 one. I think we just need to be consistent within that section to use it or not (otherwise, it may be confusing to people just getting a handle on ES6). For example, in the Functional Programming section, the first 3 challenges use ES6 `const`, but the rest of the challenges use `var`. Certainly an area we can keep in mind as we QA beta 😄

**Comment by raisedadead** [comment]
Yup, I think we should just proceed this way. Thanks for the feedback @no-stack-dub-sack @HKuz! 
Cheers!
