### ISSUE TITLE
Typo in Data Visualization with D3: Change Styles Based on Data

### ISSUE THREAD

**Issue by petercollingridge** [freeCodeCamp/freeCodeCamp#12692]
Challenge [change-styles-based-on-data](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/change-styles-based-on-data) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.

The instructions say:

> Add the style() method to the code in the editor to set the color of the h1 elements conditionally.

It should say h2 instead of h1.

**Comment by HKuz** [comment]
I can confirm this - thanks for the catch @petercollingridge! Post a comment here if you'd like to create a PR to fix this, otherwise I'll put a `Help Wanted` tag up. I think this is a good issue for a first timer.

**Comment by petercollingridge** [comment]
I'd like to submit a fix if I can. Should be easy enough.
