### ISSUE TITLE
Chrome Dev Tools: Console page should include mention of Console.table()

### ISSUE THREAD

**Issue by pleabargain** [freeCodeCamp/freeCodeCamp#12690]
#### Challenge Name

https://www.freecodecamp.com/videos/chrome-dev-tools-console
#### Issue Description

Chrome Dev Tools: Console page should include mention of Console.table()

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### page says
There are different commands that will log differently, like console.log() for basic logging, console.error() & console.warn() for 'eye catching stuff'.
#### page should say
There are different commands that will log differently, like console.log() for basic logging, console.error(), console.table() & console.warn() for 'eye catching stuff'.

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/640846/22175523/5cf739e8-e007-11e6-8c7c-351ddba541db.png)

**Comment by systimotic** [comment]
Hi @pleabargain! Thanks for reporting this issue.

I see where you are coming from. However, there still more console methods than that.
I think this part description aims to talk about some of the different levels of severity, as elaborated on in the link.

As Briana does talk about console.table in the video, I agree that it would make sense to mention it somewhere in the description. Perhaps linking to the [MDN page about Console](https://developer.mozilla.org/en-US/docs/Web/API/Console) is a good solution?

**Comment by pleabargain** [comment]
@systimotic YES! I was thinking similar: linking to the MDN page about Console is a good solution

**Comment by dhcodes** [comment]
@systimotic and then getting the MDN links to work on staging... 😉
