### ISSUE TITLE
Check queries for empty arrays since Loopback may return an empty array for find

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/freecodecamp#127]

**Comment by BerkeleyTrue** [comment]
To clafiry, using Model.find will allways return an array, whether it finds matching documents or not. In some cases the logic checks if the return from find is truey. As empty arrays are considered true by javascript, these conditionals will be satisfied and often cause errors. 

Use findOne where a single document is expected, use Model.find when an array of documents is required.

**Comment by terakilobyte** [comment]
Have we decided on findone or using data.length ?

**Comment by BerkeleyTrue** [comment]
If find is faster than findOne, then lets just stick to that and check for empty arrays. Will need to make sure future contributors are aware of this as well.

**Comment by terakilobyte** [comment]
Sounds reasonable. Since we're using Ramda I can also write some generic normal english functions like `foundOne`
