### ISSUE TITLE
[beta] challenge output container does not show challenge output

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#12701]
On beta, this container (which still has a message which says "output will go here"), no longer shows the challenges' output:
![image](https://cloud.githubusercontent.com/assets/18563015/22176754/0ea4bbc6-dfdf-11e6-828d-6fbc001ecb8f.png)

Instead, we only see the notification that the tests are running or have completed:
![image](https://cloud.githubusercontent.com/assets/18563015/22176770/4c7ee796-dfdf-11e6-84ca-98ce2f42a891.png)

Are we doing away with showing the challenge output or is this unintentional? If we are, we need to change that default message. But I think we should still show it, it's nice to have that tangible feedback. 

cc/ @freeCodeCamp/moderators Anyone know anything about this? I might have missed a previous issue.

**Comment by raisedadead** [comment]
@no-stack-dub-sack https://github.com/freeCodeCamp/freeCodeCamp/issues/9363

**Comment by no-stack-dub-sack** [comment]
@raisedadead thanks! Has this been looks like that was closed but this still needs to be done for a lot of sections - should we re-open and assign out specific sections? Maybe to newcomers since it's a relatively easy task? Or maybe now is not the best time for it since there will be so many PRs coming in things might get a little confusing

**Comment by raisedadead** [comment]
@no-stack-dub-sack this is actually a duplicate because the other thread that I mentioned will be done for all challenges, we need to wrap the output in challenge seed or tail.
