### ISSUE TITLE
[beta] Video doesn't load on Applied Responsive Web Design Projects

### ISSUE THREAD

**Issue by Bakermg** [freeCodeCamp/freeCodeCamp#12708]
Challenge [build-a-survey-form](http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-survey-form) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by dhcodes** [comment]
Minified React error in console shows:
>Unable to find element with ID 52.

**Comment by systimotic** [comment]
I'm guessing this is related to #12656? Doesn't have to be though!
I can't reproduce this locally either, but I do get an https/http error.

**Comment by QuincyLarson** [comment]
We're removing all project videos from our platform and implementing a multi-file editor so campers don't have to use CodePen any more. Please see https://github.com/freeCodeCamp/freeCodeCamp/issues/12753
