### ISSUE TITLE
[Beta] Images on Section Intros are not centered on large displays

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/freeCodeCamp#12705]
#### Challenge Name

Ex. [Intro to Data Visualization with D3](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/introduction-to-the-data-visualization-with-d3-challenges)

#### Issue Description

The images (usually XKCD comics) on the section intro pages are centered/responsive on smaller displays but are offset (not centered) on larger displays.

#### Browser Information

* Browser Name, Version: Chrome 55.0.2+
* Operating System: macOS Sierra
* Mobile, Desktop, or Tablet: Desktop

 
 
```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by systimotic** [comment]
@dhcodes This was on my ToDo list to report 😄 
I'm glad you reported it, because it probably would've taken me too long. I'm working on a fix.

**Comment by systimotic** [comment]
This is probably the fastest I have ever seen an issue be fixed 😄 Thanks for merging Dylan!

**Comment by dhcodes** [comment]
Lol what do I win?

**Comment by systimotic** [comment]
**You win a brand new refrigrator!**
![refrigerator](http://i.giphy.com/3oz8xRTwtQl2gKBAju.gif)

_Disclaimer: Your refrigerator may look different from the one pictured. It may also not be new. It may also never actually arrive._ 😜
