### ISSUE TITLE
Confusing instructions in truncate a string

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/freeCodeCamp#12712]
#### Challenge Name

[Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string)

#### Issue Description

_Inspired by https://github.com/FreeCodeCamp/freeCodeCamp/issues/12418_
Let's talk about why I think this is confusing. Here are the instructions:
>Truncate a string (first argument) if it is longer than the given maximum string length (second argument). Return the truncated string with a ... ending.
>
>Note that inserting the three dots to the end will add to the string length.
>
>However, if the given maximum string length num is less than or equal to 3, then the addition of the three dots does not add to the string length in determining the truncated string.

1. If the string is longer than three characters, the string should be truncated at `num - 3`
2. If it's three characters or shorted, it should be truncated at `num`

This doesn't really make sense to me.
Now, I don't want to talk about real world cases too much, but I'll do it a for a little bit.
I think the point of a truncate function is to get an output of a predictable length. With this function, regardless of the input, the output should be `num` or `num + 3`.

I suggest we simplify this challenge to _always_ shorten the string to the amount of characters passed in as the second argument (`num`), making the output string always `num + 3`.

I thought a bit about it being more complicated intentionally to make the camper dissect the requirements and use if statements, but I think it's a bad idea to intentionally make things more complicated than they would be for the sake of having them practice something.

**Comment by raisedadead** [comment]
@systimotic Yes, I agree we should make the objective of this challenge simple. We should update the instructions and the test cases to reflect `num + 3`.

**Comment by codeGeek3** [comment]
I agree with you, the instruction are confusing. and The problem seems very simple
