### ISSUE TITLE
Waypoint: Build an Adventure Game

### ISSUE THREAD

**Issue by monty7r7** [FreeCodeCamp/freecodecamp#1271]
The link in Waypoint: Build an Adventure Game takes you to, what Codeacademy says, is an unsupported curriculum.  <http://www.codecademy.com/courses/getting-started-v2/0/1>
<img width="1432" alt="screen shot 2015-07-12 at 11 15 36" src="https://cloud.githubusercontent.com/assets/13263147/8638652/9b537ba4-2887-11e5-9e27-6fe933e7d08d.png">

It may be a small issue of completeness of the address in the link, but this link appears to function as expected, though the only difference is the end of the address.  <http://www.codecademy.com/courses/getting-started-v2/0/1?curriculum_id=506324b3a7dffd00020bf661>
<img width="1427" alt="screen shot 2015-07-12 at 11 16 58" src="https://cloud.githubusercontent.com/assets/13263147/8638654/a11d9c18-2887-11e5-9106-dd1e6701bdc2.png">

Just wanted to pass it along in case someone else runs into this or in case the link should be updated (the courses in each link appear to be exactly the same).

**Comment by deesto** [comment]
I think this is still an issue and should be fixed in the waypoint.

**Comment by BerkeleyTrue** [comment]
Closing as all codecademy courses will be removed in next iteration of curriculum.

Happy Coding!
