### ISSUE TITLE
THIS PROBLEM IS MESSED UP

### ISSUE THREAD

**Issue by sianid** [freeCodeCamp/freeCodeCamp#12713]
I've seen all of the suggestions about deleting the commented in text, deleting the last console.log() and tried all variations possible to pass this waypoint. The challenge still tells me that I haven't defined a global var and won't let me go on. HELP PLEASE.

My code:

function myLocalScope() {
  var myVar = "local";
 
  console.log(myVar);
}
myLocalScope();

var myVar = "global";

```

**Comment by mccugh** [comment]
Prosecute how and where
