### ISSUE TITLE
issue with this challenge in beta.freecodecamp

### ISSUE THREAD

**Issue by stephenkit** [freeCodeCamp/freeCodeCamp#12715]
**Will not pass, even though you ifll in the content.  Also, the instructions don't seem to be displayed

Challenge [introduction-to-html5-elements](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/introduction-to-html5-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 OPR/42.0.2393.137</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<h2>CatPhotoApp</h2>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by systimotic** [comment]
@stephenkit Thank you for reporting this issue! 👍 

It looks like you're having the same issue as #12656, so I'm closing this issue as a duplicate.

Happy coding!
