### ISSUE TITLE
Description broken for Introduction to HTML5 Elements

### ISSUE THREAD

**Issue by YacYac** [freeCodeCamp/freeCodeCamp#12719]
#### Challenge Name
Introduction to HTML5 Elements

#### Issue Description
The challenge description indicates that HTML 5 introduces more descriptive tags and then goes on to seemingly list several examples. Only the example list is broken and does not show any tages

#### Browser Information
Chrome, Version 55.0.2883.95
macOS 10.12.2

#### Screenshot
![screen shot 2017-01-22 at 2 43 04 am](https://cloud.githubusercontent.com/assets/3401542/22181242/513118e0-e04d-11e6-95d3-2be62e53d78e.png)

**Comment by ChrisD1986** [comment]
please subjectivity integrate your SEO!?

**Comment by systimotic** [comment]
Hi @YacYac, Thank you for reporting this issue! 👍

It looks like you're having the same issue as #12656, so I'm closing this issue as a duplicate.

Happy coding!
