### ISSUE TITLE
No image in the "phone" screen upon initial load.

### ISSUE THREAD

**Issue by kprenesti** [freeCodeCamp/freeCodeCamp#12725]
Challenge [create-visual-balance-using-the-textalign-property](http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-visual-balance-using-the-textalign-property) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

There is no visual in the right-hand, "phone" view upon initial load.  Upon completion of the challenge, the h2, p, and links become visible.

```html
    
    
<style>
h4 {
  text-align: center;
}
p {
  text-align: justify;
}
.links {
  margin-right: 20px;
  text-align: left;
}
.fullCard {
  border: 1px solid #ccc;
  border-radius: 5px;
  margin: 10px 5px;
  padding: 4px;
}
.cardContent {
  padding: 10px;
}
</style>
<div class="fullCard">
<div class="cardContent">
  <div class="cardText">
    <h4>Google</h4>
    <p>Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University.</p>
  </div>
  <div class="cardLinks">
    <a href="https://en.wikipedia.org/wiki/Larry_Page" class="links">Larry Page</a>
    <a href="https://en.wikipedia.org/wiki/Sergey_Brin" class="links">Sergey Brin</a>
  </div>
</div>
</div>

    ```

**Comment by dhcodes** [comment]
While they are different challenges, I'm closing this is favor of your other issue thread on the same topic.
