### ISSUE TITLE
Formatting issue in "Return Largest Numbers in Arrays"

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/freeCodeCamp#12724]
#### Challenge Name
[Return Largest Numbers in Arrays](https://www.freecodecamp.com/challenges/return-largest-numbers-in-arrays)

#### Issue Description
Usually, we put spaces between a comma and the next element in an array. This challenge is missing the spaces in one array in one of the tests.

#### Screenshot
![2017-01-22_12-55-35](https://cloud.githubusercontent.com/assets/7262039/22182295/21f142b2-e0a2-11e6-993b-281914592533.png)

# First-timers only
Check out [CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) to get your local development environment set up.

The test that needs to be changed is [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-algorithm-scripting.json#L285). Add spaces after the commas to make it look like the other tests.

If you need help, please go to our [contributors chatroom](https://gitter.im/FreeCodeCamp/Contributors).

Happy coding! 🎉

**Comment by rajpatel507** [comment]
@systimotic  can i work on this?

**Comment by dhcodes** [comment]
@rajpatel507 absolutely!

**Comment by AnnekeCr** [comment]
Has this been fixed already?

**Comment by rajpatel507** [comment]
@systimotic @dhcodes  I have created PR for this isssue.
