### ISSUE TITLE
[beta] Phone view not rendering on initial load of challenge.

### ISSUE THREAD

**Issue by kprenesti** [freeCodeCamp/freeCodeCamp#12726]
Challenge [use-the-css-transform-scale-property-to-change-the-size-of-an-element](http://beta.freecodecamp.com/en/challenges/applied-visual-design/use-the-css-transform-scale-property-to-change-the-size-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

No image in the phone view upon initial load when not following the map linearly.  (I selected a lesson based on what I could use a refresher on.  I know the surrounding material.)

```html
    
    
<style>
.ball { 
  width: 40px;
  height: 40px;
  margin: 50 auto;
  position: fixed;
  background: linear-gradient(
  35deg,
  #ccffff,
  #ffcccc
);       
  border-radius: 50%;
}
#ball1 {
  left:20%;
}
#ball2 {
  left:65%;
  
  
}


</style>

<div class="ball" id= "ball1"></div>
<div class="ball" id= "ball2"></div>

    ```

**Comment by dhcodes** [comment]
I'm confirming this for the D3 challenges.

**Comment by BerkeleyTrue** [comment]
This is fixed in beta
