### ISSUE TITLE
JamesBond test never fired.

### ISSUE THREAD

**Issue by kprenesti** [freeCodeCamp/freeCodeCamp#12729]
Challenge [use-the-parseint-function](http://beta.freecodecamp.com/en/challenges/basic-javascript/use-the-parseint-function) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The JamesBond test never fires, so this challenge is unpassable.  Here's the result of the console.log.

56
56
56
56
 77

```js
    
    
function convertToInteger(str) {
console.log(parseInt(str));
}
convertToInteger("56");

    ```

**Comment by systimotic** [comment]
@kprenesti Thanks for reporting! I commented on this on your other issue, before I saw this. I'll merge them both into the other issue.
