### ISSUE TITLE
Waypoint: Preview our Challenge Map

### ISSUE THREAD

**Issue by DaforLynx** [FreeCodeCamp/FreeCodeCamp#1272]
Only 3 lessons in!
Something went wrong with the audio in the second half of the video.
It could be anything, but just to elaborate: the audio stopped around 0:33. When I tried to replay it it made mad clicking sounds, and now when I play it the whole video's audio is lowered by a lot. It's creepy.

It did it again when I reloaded it! I'm using FF39 browser, Windows 8.1.
It could be a problem with only my computer, but someone should look into it.

**Comment by benschenker** [comment]
Closing as stale
