### ISSUE TITLE
[beta] Use the parseInt function has no instructions

### ISSUE THREAD

**Issue by kprenesti** [freeCodeCamp/freeCodeCamp#12727]
Challenge [use-the-parseint-function](http://beta.freecodecamp.com/en/challenges/basic-javascript/use-the-parseint-function) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

No actual task instructions.  I inferred that you're supposed to take the str and make it an integer, but a sentence stating it would be helpful. 
```js
    
    
function convertToInteger(str) {
return parseInt(str);
}
convertToInteger("56");

    ```

**Comment by HKuz** [comment]
@kprenesti - thanks for raising this issue, I agree with you completely. The challenge seems to end abruptly as it's written, and I think adding a little more direction would improve it.

I would suggest something like the following challenge text:

The `parseInt()` function parses a string and returns an integer. Here's an example:

`var a = parseInt("007");`

The above function converts the string "007" to an integer 7.

[Put an `<hr>` tag here in the seed code]

Use `parseInt()` in the `convertToInteger` function so it returns an integer value from the input string `str`.

Also, the third test message needs a minor edit so it reads: `convertToInteger("77")` should return 77.


As the one who opened the issue, any interest in making these changes? You can post here either way. If you can't, no worries, I can open it up as `Help Wanted` for any other contributor. Thanks again!

**Comment by HKuz** [comment]
I'm working on formatting clean-up for these new JS challenges and will make this fix.
