### ISSUE TITLE
Camper News won't accept URLs with long trailing queries

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/freecodecamp#1273]
For example, http://blog.scottlogic.com/2015/07/02/surprising-things-about-js.html?utm_source=javascriptweekly&utm_medium=email

**Comment by pmbenjamin** [comment]
I don't think this has to do with the length of the trailing queries. 
I tried encoding the ampersand with %26 and it worked on Camper News, so I believe it has something to do with special characters.
