### ISSUE TITLE
[beta] es6 challenge: import-vs-require-whats-the-difference test not working

### ISSUE THREAD

**Issue by mikeale03** [freeCodeCamp/freeCodeCamp#12739]
#### Challenge Name

https://beta.freecodecamp.com/en/challenges/es6/import-vs-require-whats-the-difference

#### Issue Description

the challenge don't accept my answer as correct. i think its a bug.

#### Browser Information

Chrome: Version 55.0.2883.87
windows 7
desktop

#### Your Code

 import { capitalizeString } from "string_functions";
capitalizeString("hello!");

**Comment by shubham1996** [comment]
I have identified the issue. Will send a pull request in a while

**Comment by Greenheart** [comment]
Another thing worth fixing for these tests are that they right now require explicit `"` for the import statement. 

I think the regex should allow for either `"` or `'`, since the latter kind of string literals are very common.

This could be achieved by replacing `"` with `["']` in the regex.

**Comment by forkerino** [comment]
I'm getting a "require is not defined" error on submitting the correct solution.

**Comment by Greenheart** [comment]
@forkerino Thanks for telling us! All ES6 code is transpiled before the tests gets executed but as we currently can't run our RegEx tests on the original ES6 code, this whole section is unreliable at the moment.

We're working on a fix, and this will definitely get resolved before it's released :blush:

**Comment by davisec52** [comment]
Also getting the error, "require is not defined" upon submitting the correct solution.

**Comment by systimotic** [comment]
Hi! Thanks for reporting and looking into this issue. We're tackling fixing the ES6 challenges in #12698. I'm closing this in favor of that issue.

Happy coding!
