### ISSUE TITLE
[beta] Tests not working correctly - parseInt challenge

### ISSUE THREAD

**Issue by kprenesti** [freeCodeCamp/freeCodeCamp#12730]
Challenge [use-the-parseint-function-with-a-radix](http://beta.freecodecamp.com/en/challenges/basic-javascript/use-the-parseint-function-with-a-radix) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The JamesBond test never fires, and I believe the test return 19 fires too many times.  Here's the result of my console.log.

10011 19
10011 19
10011 19
10011 19
111001 57

```js
    
    
function convertToInteger(str) {
console.log(str, parseInt(str, 2));
}
convertToInteger("10011");

    ```

**Comment by dhcodes** [comment]
Thanks @kprenesti your code is correct and console.logging the function yields the correct results so I'm guessing it has something to do with how the 1st and 4th test are written. Will investigate...
