### ISSUE TITLE
[beta] SyntaxError shows wrong error message

### ISSUE THREAD

**Issue by kprenesti** [freeCodeCamp/freeCodeCamp#12733]
Challenge [use-multiple-conditional-ternary-operators](http://beta.freecodecamp.com/en/challenges/basic-javascript/use-multiple-conditional-ternary-operators) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The syntax was wrong, but gave a "Something went wrong" error message instead of a "Try again" error message.  The wrong error would make me think there was a bug with the program rather than my code was wrong.  

```js
    
    
function checkSign(num) {

return (num > 0)?"positive":(num === 0):"zero":"negative";

}
checkSign(10);

    ```

**Comment by systimotic** [comment]
@kprenesti Thank you for reporting this issue! I can confirm that this is indeed a problem.
SyntaxErrors are not handled properly. I've had errors crash the page before, which means that something actually went wrong and I had to reload the page before being able to run the challenge again.

We should look at how to handle those errors properly.

**Comment by systimotic** [comment]
Possibly related: #11198
