### ISSUE TITLE
It accepts any number and always returns timesFive(5) === 25

### ISSUE THREAD

**Issue by ChristyHrd** [freeCodeCamp/freeCodeCamp#12741]
Challenge [Return a Value from a Function with Return](https://www.freecodecamp.com/challenges/return-a-value-from-a-function-with-return#?solution=%0A%2F%2F%20Example%0Afunction%20minusSeven(num)%20%7B%0A%20%20return%20num%20-%207%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Afunction%20timesFive(num)%20%7B%0A%20%20return%20num%20*%205%3B%0A%7D%0A%0Aconsole.log(timesFive(0))%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function minusSeven(num) {
  return num - 7;
}

// Only change code below this line

function timesFive(num) {
  return num * 5;
}

console.log(timesFive(0));
```

- if you delete the functions, it will still accept the challenge as correct
- any number will return -> timesFive(5) === 25

**Comment by OFFLlNE** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #9583, so I am closing it as a duplicate.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
