### ISSUE TITLE
Video not working

### ISSUE THREAD

**Issue by coderHook** [freeCodeCamp/freeCodeCamp#12743]
Challenge [build-a-drum-machine](https://beta.freecodecamp.com/en/challenges/front-end-frameworks-projects/build-a-drum-machine) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by QuincyLarson** [comment]
@coderHook we are removing these demo videos and overhauling these views. I've closed this issue and opened #12753
