### ISSUE TITLE
function was created and called properly and showing output correctly but still says out put isn't showing right 

### ISSUE THREAD

**Issue by robelte** [freeCodeCamp/freeCodeCamp#12748]
Challenge [Write Reusable JavaScript with Functions](https://www.freecodecamp.com/challenges/write-reusable-javascript-with-functions#?solution=%0A%2F%2F%20Example%0Afunction%20ourReusableFunction()%20%7B%0A%20%20console.log(%22Heyya%2C%20World%22)%3B%0A%7D%0A%0AourReusableFunction()%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20reusableFunction()%7B%0A%20%20console.log(%22Hi%2C%20World%22)%3B%0A%7D%0A%0AreusableFunction()%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourReusableFunction() {
  console.log("Heyya, World");
}

ourReusableFunction();

// Only change code below this line
function reusableFunction(){
  console.log("Hi, World");
}

reusableFunction();


```

**Comment by OFFLlNE** [comment]
@robelte Thank you for reporting your issue.

Your code is wrong.
Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification.
Thank you, and happy coding.

**Comment by robelte** [comment]
i was not asking for help,just thought i would report a bug ...that's all,and code wasn't wrong it was the "Hi, World"

**Comment by OFFLlNE** [comment]
After I told that your code is wrong, I would've expected you to the help chat and ask us there why does it not let you pass the challenge ;)
You need "Hi World"
Good luck Coding!

**Comment by robelte** [comment]
thank you, i didn't mean to sound like the way my text did,i was just in a hurry when i sent it i deeply apologize for my arrogance , i know you have a lot to do !and i appreciate it

**Comment by rmdawson71** [comment]
BETA edition of challenge:

Same problem I have reported on 5-6 other challenges.  

Coming into the challenge from successfully completing the previous challenge, I type my correct code and submit and some tests fail.  If I exit the challenge and go back into the challenge via the Map, I can click submit and the tests pass and the dialogue box pops up for me to continue to the next challenge.

If you look at the console error message, it says logOutput is not defined.  My code does not even have that anywhere, so something is buggy in the tester app ONLY when coming fresh into a new challenge and not directly from the Map.
 
![image](https://cloud.githubusercontent.com/assets/5313213/22449545/bba86948-e715-11e6-805a-6ddaad5f9e76.png)
