### ISSUE TITLE
no confirmation bug: Waypoint: Mobile Responsive Images - freecodecamp

### ISSUE THREAD

**Issue by alex26aly** [FreeCodeCamp/FreeCodeCamp#1274]
checked my waypoint without confirmation, definitely a bug
![fireshot capture - a map of all free code camp s challenges i fre_ - http___www freecodecamp com_map](https://cloud.githubusercontent.com/assets/13079733/8640190/6e21a11c-28f8-11e5-89e7-f7cdf096bfb8.png)

Challenge http://www.freecodecamp.com/challenges/waypoint-mobile-responsive-images has an issue. 
![fireshot capture - waypoint_ mobile responsive images i fr_ - http___www freecodecamp com_challeng](https://cloud.githubusercontent.com/assets/13079733/8640155/55eb902c-28f7-11e5-97a8-f623d96f411c.png)

I did both but no confirmation, tried a couple of times
![fireshot capture - waypoint_ mobile responsive images i fr_ - http___www freecodecamp com_challeng](https://cloud.githubusercontent.com/assets/13079733/8640143/ead10a74-28f6-11e5-9293-f3b30a55d0ca.png)

**Comment by kellyexton** [comment]
HI, I've hit the same problem, did you find a fix?

**Comment by esq-willis** [comment]
<img width="578" alt="screen shot 2015-07-18 at 7 46 41 am" src="https://cloud.githubusercontent.com/assets/8811109/8761477/3371ee64-2d21-11e5-913c-78a696ab4a01.png">
You're missing the "/></a>" part of the code at the end right after the file image name.

**Comment by kellyexton** [comment]
Thanks, its still not working for me though unfortunately.

**Comment by kumareshroy** [comment]
Nope..

-----Original Message-----

**Comment by alex26aly** [comment]
I tried a couple of times, refreshing the web page did the trick for me

**Comment by kellyexton** [comment]
I finally managed to get past that screen! Definately very buggy, it only worked once i took the e off 'img-responsive' from the first image. If i added the 'e', neither would be ticked! Thanks for you're help guys!

**Comment by esq-willis** [comment]
Try copying and pasting the the kitty2 link from the directions on the left panel. That did the trick for me when I attempted it again when the screen wouldn't let me get past it the first time around.

**Comment by kyokahn** [comment]
@kellyexton " it only worked once i took the e off 'img-responsive' from the first image. If i added the 'e', neither would be ticked! Thanks for you're help guys!"

Dude how did you find that? Worked like a charm. Absurdly so IMO.

**Comment by benschenker** [comment]
You are actually experiencing the same issue as in #1300.

Closing this as a duplicate.
