### ISSUE TITLE
Bug: We really dont need 9 "case" here

### ISSUE THREAD

**Issue by Shubham-invent** [freeCodeCamp/freeCodeCamp#12742]
#### Challenge Name

https://www.freecodecamp.com/challenges/multiple-identical-options-in-switch-statements

#### Issue Description

Please see for passing test it is asking for 9 "Cases" which is not actually needed.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
function sequentialSizes(val) {
  var answer = "";
  // Only change code below this line
  switch(true){   
      case val<=3 :answer="Low";break;
      case val<=6:answer="Mid";break;
      case val<=9:answer="High";break;
  }

  // Only change code above this line  
  return answer;  
}

// Change this value to test
sequentialSizes(1);

```

**Comment by dhcodes** [comment]
@Shubham-invent I think the goal here is to show how to write a switch with multiple inputs. Even though the challenge can be solved in a different way, it's still an important concept. I'll leave this open for now for other @freeCodeCamp/moderators to chime in.

**Comment by Shubham-invent** [comment]
@dhcodes I agree with you let both the Answer be excepted or lets change the question.Because if a question can be solved with 3 cases we really don't need 8 cases.That wont be a good part in grooming a Coder.

**Comment by systimotic** [comment]
@Shubham-invent This challenge is indeed solvable in this way. Do you have any suggestions on a different example to teach multiple identical options in a switch statement?

**Comment by raisedadead** [comment]
Please revert back if this is still an issue.
