### ISSUE TITLE
"Working example" link has no href in Treemap Diagram Project page

### ISSUE THREAD

**Issue by matty22** [freeCodeCamp/freeCodeCamp#12744]
#### Visualize Data with a Treemap Diagram

https://beta.freecodecamp.com/en/challenges/data-visualization-projects/visualize-data-with-a-treemap-diagram

#### Issue Description

The "working example" link has no href, so when you click that link, it opens a new tab of the challenge page rather than opening the working example.

#### Browser Information

* Browser Name, Version: Chrome v.55
* Operating System: OSx
* Mobile, Desktop, or Tablet: Desktop

**Comment by ananaymital** [comment]
@OFFLlNE @QuincyLarson I think this issue has somehow been resolved. The link seems to work alright. Please confirm.

**Comment by QuincyLarson** [comment]
@ananaymital Yes - agreed. This seems to have been fixed. Thanks!
