### ISSUE TITLE
Basic Html and Html5: Declare the Doctype of an HTML Document-Beta

### ISSUE THREAD

**Issue by jowaynejosephs** [freeCodeCamp/freeCodeCamp#12747]
Challenge [declare-the-doctype-of-an-html-document](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/declare-the-doctype-of-an-html-document) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
//As far as I can tell, this is wrapped and declared properly.

```html
    
    <!DOCTYPE html>
<html>
<h1>Hello World</h1>
</html>




    ```

**Comment by systimotic** [comment]
Hi @jowaynejosephs! Thank you for reporting this issue.

This is indeed an issue in the beta. It has been fixed in staging though, so you should see it be updated the next time staging is deployed to beta.

Happy coding!
