### ISSUE TITLE
[Beta] CSS section has sequencing issues after split from HTML

### ISSUE THREAD

**Issue by HKuz** [freeCodeCamp/freeCodeCamp#12759]
#### Challenge Name

This applies to the first ~1/3 of challenges in the Basic CSS section. (The ones styling the CatPhotoApp)

#### Issue Description

After splitting the HTML and CSS challenges into separate sections, some of the challenge seed doesn't flow well. Basically, the HTML for the CatPhotoApp from where it ends in the HTML section needs to carry into the CSS section.

**Comment by artityod** [comment]
#12759
