### ISSUE TITLE
[beta] edge browser does not work on tests

### ISSUE THREAD

**Issue by pachecot** [freeCodeCamp/freeCodeCamp#12751]
Challenge [using-display-flex-with-two-boxes](http://beta.freecodecamp.com/en/challenges/css-flexbox/using-display-flex-with-two-boxes) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

seems to be an Edge browser issue. tried a few challenges and none of them worked in the edge browser, works in chrome. old code camp works with edge.

```html
    
    
<style>
#box-1 {
  background-color: dodgerblue;
  width: 500px;
  height: 500px;
  display: flex;
}

#box-2 {
  background-color: orangered;
  width: 500px;
  height: 500px;
  display: flex;    
}
</style>
<div id="box-1"></div>
<div id="box-2"></div>

    ```

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
