### ISSUE TITLE
Create a placeholder project view until multi-tab editor is ready

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#12753]
Currently @benmcmahon100 is working on updating our UI and creating a multi-file editor. This will enable campers to build non-backend projects right on freeCodeCamp instead of having to use CodePen.

We are eliminating videos from our projects views and replacing them with static images. I've added imgur links already as the challenge seed for each of the non-backend projects: 
```
      "challengeSeed": [
        "G6iPE6W"
      ],
```

This should translate to http://i.imgur.com/G6iPE6W.png as the image source.

Currently the project views look pretty terrible:

![](https://www.evernote.com/l/Ar80IzaMP_BF6Kg8SwiVfI_Ga84IVZqnWlQB/image.png)

**Comment by Bamcrab** [comment]
On a semi-related note, it appears the tests for these challenges specifically require you to ignore the best practices taught up until this point. Will there be updated tests soon/eventually?

(In the mean time, do we just follow what the tests need to get by?)

**Comment by KoniKodes** [comment]
I cannot view the video either, and there is no image. What exactly am I supposed to create with this survey? Is it supposed to go somewhere specific, or are you simply looking at the design?

**Comment by QuincyLarson** [comment]
@berkeleytrue is almost done with the new project UI so I'm going to go ahead and close this issue.

**Comment by raisedadead** [comment]
We have open PR for this which implements this. Let's keep this open, while the PR is accepted.
