### ISSUE TITLE
Manually add recent PR changes to new curriculum seed files

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#12755]
The following pull requests have been applied to backup/master (our production branch) but not to staging (our beta branch). 

- [x] https://github.com/freeCodeCamp/freeCodeCamp/commit/54c11a0de9436935cb26f74324354d76d5f20939
- [x] https://github.com/freeCodeCamp/freeCodeCamp/commit/78e86f514f90dc3fd392a52fa52feb180a91f3af
- [x] https://github.com/freeCodeCamp/freeCodeCamp/commit/aefcf9c2acf9def066947ce5c55196fab1ab3e00
- [x] https://github.com/freeCodeCamp/freeCodeCamp/commit/52edcedb61ab57d9201d4b4bcf865caf80d894de
- [x] https://github.com/freeCodeCamp/freeCodeCamp/commit/a02fd05922a382c970814d7afdc7fd258a7ca2fa
- [x] https://github.com/freeCodeCamp/freeCodeCamp/commit/1947a1631a82674ba645873b9f3dcf7b1df1296f
- [x] https://github.com/freeCodeCamp/freeCodeCamp/commit/1e831cb02c788168ade514ffb85d9b4f83e3bf0e
- [x] https://github.com/freeCodeCamp/freeCodeCamp/commit/c9d4da3146e64391e72489edc9a0c255d91af969
- [x] https://github.com/freeCodeCamp/freeCodeCamp/commit/8fe1a5d5a98d780a5cbeb2860945c97cf11a8244
- [x] https://github.com/freeCodeCamp/freeCodeCamp/commit/a29a928f49ef0c0153ea1c8e25a5f40fa46a3190
- [x] https://github.com/freeCodeCamp/freeCodeCamp/commit/a96f926058522b9c0b30c2b40ca32ed169be344d
- [x] https://github.com/freeCodeCamp/freeCodeCamp/commit/23efc0510a4ea2bca82d7a3e83e004e4252c927d
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/commit/9142aec8ad118fa4881a82a731e5d5c3ffc9752f
- [ ] https://github.com/freeCodeCamp/freeCodeCamp/commit/505778acbf4b6ecf4b79941590714c854b2cf78c
- [x] https://github.com/freeCodeCamp/freeCodeCamp/commit/dcdd1162209028d2e9f3ae6bf0721e652e6f9732
- [x] https://github.com/freeCodeCamp/freeCodeCamp/commit/76938237abac51ef5de7af787fa2aeb8e8202ca0

Our goal is to review each one of these PRs and, if it still makes sense, make its changes to staging. Then we can check off that PR. Once we've done this to each of these PRs, we can close this issue.

**Comment by no-stack-dub-sack** [comment]
Here's one #12519 - pretty simple one, but it was a bit more than the title implies. My only PR I think that would be affected by this so figured I'd add it.

**Comment by systimotic** [comment]
So this is quite a bit more than I expected. I expected to be able to find out when the changes were no longer retained, then log out all commits between then and now.
What I found out is that not all seed files were affected by this. Here's my plan of action
- [ ] Find out which files were affected
- [ ] Find out since when they were affected
- [ ] Use `git log` to get the changes between the dates in the affected files. I have already figured out the command to do this

**Comment by QuincyLarson** [comment]
@systimotic sounds like a good plan. Please let me know if I can be of help with this.

**Comment by thmsdnnr** [comment]
Hey @systimotic are you still working on this? If not I'd be happy to take it over for this week.

**Comment by littledago22** [comment]
Itsvhotts

**Comment by QuincyLarson** [comment]
@systimotic I've started this process by updating the seed files. Here's the PR if you want to take a look and merge: https://github.com/freeCodeCamp/freeCodeCamp/pull/16116

**Comment by mpontus** [comment]
I'm going to take four commits from the top:
- [ ] [`54c11a0`](https://github.com/freeCodeCamp/freeCodeCamp/commit/54c11a0de9436935cb26f74324354d76d5f20939)
- [ ] [`78e86f5`](https://github.com/freeCodeCamp/freeCodeCamp/commit/78e86f514f90dc3fd392a52fa52feb180a91f3af)
- [ ] [`aefcf9c`](https://github.com/freeCodeCamp/freeCodeCamp/commit/aefcf9c2acf9def066947ce5c55196fab1ab3e00)
- [ ] [`52edced`](https://github.com/freeCodeCamp/freeCodeCamp/commit/52edcedb61ab57d9201d4b4bcf865caf80d894de)

**Comment by mpontus** [comment]
@QuincyLarson PR is out 

I also looked through the rest of the commits and here's what I found:

 https://github.com/freeCodeCamp/freeCodeCamp/commit/a02fd05922a382c970814d7afdc7fd258a7ca2fa - already implemented
 https://github.com/freeCodeCamp/freeCodeCamp/commit/1947a1631a82674ba645873b9f3dcf7b1df1296f - already implemented
 https://github.com/freeCodeCamp/freeCodeCamp/commit/1e831cb02c788168ade514ffb85d9b4f83e3bf0e - already implemented
 https://github.com/freeCodeCamp/freeCodeCamp/commit/c9d4da3146e64391e72489edc9a0c255d91af969 - already implemented
 https://github.com/freeCodeCamp/freeCodeCamp/commit/8fe1a5d5a98d780a5cbeb2860945c97cf11a8244 - already implemented
 https://github.com/freeCodeCamp/freeCodeCamp/commit/a29a928f49ef0c0153ea1c8e25a5f40fa46a3190 - valid
 https://github.com/freeCodeCamp/freeCodeCamp/commit/a96f926058522b9c0b30c2b40ca32ed169be344d - already implemented
 https://github.com/freeCodeCamp/freeCodeCamp/commit/23efc0510a4ea2bca82d7a3e83e004e4252c927d - already implemented
 https://github.com/freeCodeCamp/freeCodeCamp/commit/9142aec8ad118fa4881a82a731e5d5c3ffc9752f - maybe valid
 https://github.com/freeCodeCamp/freeCodeCamp/commit/505778acbf4b6ecf4b79941590714c854b2cf78c - maybe valid
 https://github.com/freeCodeCamp/freeCodeCamp/commit/dcdd1162209028d2e9f3ae6bf0721e652e6f9732 - already implemented
 https://github.com/freeCodeCamp/freeCodeCamp/commit/76938237abac51ef5de7af787fa2aeb8e8202ca0 - invalid (code is not serialized in url in new release)

Perhaps someone else can confirm my observations and then you can update the topic.

**Comment by QuincyLarson** [comment]
@mpontus Awesome! Thank you for researching these! I've double checked and I agree. So you're saying that there are only about 3 left to tackle, right?

**Comment by mpontus** [comment]
@QuincyLarson Thanks Quincy!

I have also PR incomming for https://github.com/freeCodeCamp/freeCodeCamp/commit/a29a928f49ef0c0153ea1c8e25a5f40fa46a3190 and I will see what I can do about https://github.com/freeCodeCamp/freeCodeCamp/commit/9142aec8ad118fa4881a82a731e5d5c3ffc9752f tomorrow.

I would try to tackle the resubscription changes: https://github.com/freeCodeCamp/freeCodeCamp/commit/505778acbf4b6ecf4b79941590714c854b2cf78c but I'm not sure how to go about testing it. 

If it involves creating an account in the local copy it may take me a while to get accustomed to the backend code.

**Comment by QuincyLarson** [comment]
@mpontus Awesome! Thank you so much for jumping on these! 

I'm not sure about the #505778a myself, the codebase has changed so much. You could ask @BerkeleyTrue for help QAing that.

We just updated the contributor guide a few days ago, so it should make it clearer how to create accounts on your locally-running version of freeCodeCamp: https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md

**Comment by mpontus** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/commit/a29a928f49ef0c0153ea1c8e25a5f40fa46a3190 can be checked off.

Sadly, I will not be able to address the two remaining commits before weekend. If anyone wants to help out, please feel free to.

**Comment by QuincyLarson** [comment]
@mpontus Awesome! Thanks for confirming this. 

I'm creating individual issues for the two remaining commits. Neither of these is mission critical - I think we can ship beta without them. But we'll see what we can do. Thanks again for all your hard work on this!

**Comment by systimotic** [comment]
Thanks a lot for picking up my slack @mpontus! ❤️
