### ISSUE TITLE
Empty editor and empty device preview

### ISSUE THREAD

**Issue by claudiocoding** [freeCodeCamp/freeCodeCamp#12769]
Challenge [make-typography-responsive](https://beta.freecodecamp.com/en/challenges/responsive-web-design/make-typography-responsive) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:50.0) Gecko/20100101 Firefox/50.0</code>.

I'ts impossible to procede with this (Firefox, Chrome, Safari), i get a empty editor with a 'scan' white line and empty device preview

![noway](https://cloud.githubusercontent.com/assets/22070843/22198577/6548093c-e157-11e6-9006-d3f52c146e63.jpg)

```html
    
    
<style>

</style>

<h2>Importantus Ipsum</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus quis tempus massa. Aenean erat nisl, gravida vel vestibulum cursus, interdum sit amet lectus. Sed sit amet quam nibh. Suspendisse quis tincidunt nulla. In hac habitasse platea dictumst. Ut sit amet pretium nisl. Vivamus vel mi sem. Aenean sit amet consectetur sem. Suspendisse pretium, purus et gravida consequat, nunc ligula ultricies diam, at aliquet velit libero a dui.</p>

    ```

**Comment by claudiocoding** [comment]
if i procede from Map > Use a Retina Image for Higher Resolution Displays > Run test > Submit and go to next... I get the editor but in the style section i get the property with a strange background and also with correct code (?) i can't procede.. (cache cleaned)

![bg](https://cloud.githubusercontent.com/assets/22070843/22199333/ba04e136-e15a-11e6-8966-1e7cc249cfef.jpg)

**Comment by claudiocoding** [comment]
today's update 

`<style>
  h2{ width: 80vw}
  p{ width: 75vmin}
</style>`


response 
`
// running test
"message: Your h2</code> tag should have a <code>
width of 80vw."
"message: Your p</code> tag should have a <code>
width of 75vmin."
// tests completed
`

**Comment by BhaveshSGupta** [comment]
I would like to work on this
