### ISSUE TITLE
In "check for Palindrome Algo", 3rd from last condition should retrun true.

### ISSUE THREAD

**Issue by AbhishekKumar92** [freeCodeCamp/freeCodeCamp#12764]
#### Challenge Name

https://www.freecodecamp.com/challenges/check-for-palindromes/

#### Issue Description

1. 3rd condition from last should return true rather than false.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```
function palindrome(str) {
  // Good luck!
  var expression = /[(\W)(\d+)(\_)]/g;
  var newStr = str.replace(expression,'');
  var normalizedStr = newStr.toLowerCase();
  var splitStr = normalizedStr.split("");
  var reverseStr = splitStr.reverse();
  var palindrmeString = reverseStr.join('');
  return normalizedStr === palindrmeString;
}
palindrome("1 eye for of 1 eye,,,.");

```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/24841681/22192885/c960b26a-e15d-11e6-9a49-814dc3690e9f.png)

**Comment by JosephLivengood** [comment]
It seems to be an issue with your solution removing digits causing your string to actually be a palindrome for that one (_eyeforofeye_)

**Comment by AbhishekKumar92** [comment]
Yes you are right.
I forgot that the condition is  ignoring punctuation, case, and spacing not a digit.
Thanks Josepeh

**Comment by erictleung** [comment]
Closing as resolved. Happy coding!
