### ISSUE TITLE
Reset Code on Account?

### ISSUE THREAD

**Issue by Willow606** [freeCodeCamp/freeCodeCamp#12766]
#### Issue Description

I can't return to my free code camp challenge because something in the code is broken and it causes my browser to freak out. I have tried this on both my laptop and my desktop and nothing doing. I'm wondering if there is a way for the powers that be to reset the code for that challenge on my account so that I can keep working away.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 7(Laptop), Windows 10(Desktop)
* Mobile, Desktop, or Tablet: Laptop, Desktop

**Comment by systimotic** [comment]
@Willow606 Check [this forum article on disabling autorun](https://forum.freecodecamp.com/t/disable-code-auto-run-on-free-code-camp/19511). That should do the trick. Be sure to remove the code that's freaking out your browser before running again 🙂 

I'm closing this as resolved. If you can't get it to work, please reopen.
Happy coding!
