### ISSUE TITLE
iPhone frame doesn't disappear on narrow widths like it should

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#12763]
![](https://www.evernote.com/l/Ar-NrpMZzHpFh6MnXIt811sdb-hnAS4FOj4B/image.png)

Steps to reproduce: 
1. open any challenge with an HTML component
2. reduce the viewport and scroll to the bottom of the page. 
3. The iPhone frame will still be there when it shouldn't be.

**Comment by dhcodes** [comment]
I believe this can be fixed by adding:
`display: none;` after [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/0a6024769bb7d7c0625309ab23f9d6a25c7a8064/client/less/challenge.less#L192)

Tagging as first-timers.

**Comment by dhcodes** [comment]
Never mind. Was mistaken.

**Comment by nawazishali** [comment]
Is this issue open to everyone? I would be interested in it.

**Comment by dhcodes** [comment]
@nawazishali yes, go forth! Follow the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) when submitting your PR. You can ask for help in the Contributors chat room on gitter if you have questions or run into errors.

**Comment by nawazishali** [comment]
Great will start working on this by tomorrow.

**Comment by QuincyLarson** [comment]
@nawazishali Awesome! Thanks for jumping on this.

**Comment by nawazishali** [comment]
@QuincyLarson  I am just trying to give back to the Community. You are my teacher Quincy & Thank You so much for making this awesome site for self learners. 

I have a question about this issue, the questions is if iPhone Frame gets removed then where the result will get displayed? Currently If frame is removed result shows on a blank white area. Is this how it should be?

**Comment by dhcodes** [comment]
@nawazishali yep that is fine; as long as the results show; that's the important part.
