### ISSUE TITLE
Const can't be redeclared in challenges

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#12762]

**Comment by raisedadead** [comment]
Why are we blocked on this?

**Comment by QuincyLarson** [comment]
@raisedadead I talked with @BerkeleyTrue about this a few days ago and he said could tackle it himself, and we set it to blocked.

**Comment by systimotic** [comment]
@QuincyLarson @BerkeleyTrue Can we get an update on this?

**Comment by BerkeleyTrue** [comment]
Updates will be posted here.

**Comment by BerkeleyTrue** [comment]
Possible solution to this are:

Wrap user code in an anon function. `const` are block scoped so wrapping them a function prevents them from polluting the namespace of the iframe.

Pass the user code through babel so that the `const`'s are transpiled to `var`'s

**Comment by ZZhaoTireless** [comment]
Those are two approaches, right? Witch one you would prefer to take?

**Comment by BerkeleyTrue** [comment]
@ZZhaoTireless The second one would be best of the two

**Comment by ZZhaoTireless** [comment]
@BerkeleyTrue So I guess I need to start from the file [transformers.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/client/rechallenge/transformers.js)right?

**Comment by AryanJ-NYC** [comment]
Hey @BerkeleyTrue.  Is there anything we can do to help?

**Comment by utomic** [comment]
This issue seems to still be around, is anyone working on this currently?

**Comment by coconutattitude** [comment]
Still having this issue :(

**Comment by BerkeleyTrue** [comment]
iframes are now immutable
