### ISSUE TITLE
Ability to solve challenges by viewing other camper profiles.

### ISSUE THREAD

**Issue by AwuorMarvin** [freeCodeCamp/freeCodeCamp#12772]
#### Challenge Name

Reverse a string 
https://www.freecodecamp.com/challenges/reverse-a-string#?solution=function%20reverseString(str)%20%7B%0A%20%20%0A%20%20var%20newStr%20%3D%20str.split(%27%27)%3B%0A%20%20console.log(newStr)%3B%0A%20%20var%20rtn%20%3D%20newStr.reverse()%3B%0A%20%20console.log(rtn)%3B%0A%20%20var%20joined%20%3D%20rtn.join(%27%27)%3B%0A%20%20return%20joined%3B%0A%7D%0A%0AreverseString(%22hello%22)%3B%0A

#### Issue Description

I viewed the leaderboard challenge (Build a Camper Leaderboard challenge) and randomly selected a profile. I went ahead and viewed that profile and chose to look at one of their solutions to a challenge (Reverse a string). Upon running the tests, the challenge was marked as complete on my own profile yet the solution was from another camper.

#### Browser Information

* Browser Name, Version: Chrome, Version 55.0.2883.87 m
* Operating System: Windows 10 Enterprise
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js
 
 
 
```

**Comment by dhcodes** [comment]
@AwuorMarvin Thanks for reporting. This is a known issue, but I'm not sure it will be remedied. Please see discussion here: #8369
