### ISSUE TITLE
BETA - URL don't route to the latest/next challenge

### ISSUE THREAD

**Issue by ulf1** [freeCodeCamp/freeCodeCamp#12778]
#### Challenge Name: Latest

http://beta.freecodecamp.com/en/challenges/

#### Issue Description

1. I finished one challenge
2. I tried to call the address http://beta.freecodecamp.com/en/challenges/
3. An `Happy Coding` page pops up
4. The map is empty when i click on `Map`

Expected behavior: Go to the latest/next challenge when routing to the generic page http://beta.freecodecamp.com/en/challenges/

#### Browser Information

* Browser Name, Version: Version 55.0.2883.87 Built on Ubuntu
* Operating System: Ubuntu 16.04 (64-bit) 
* Mobile, Desktop, or Tablet: Laptop

#### Screenshot

![screenshot_2017-01-23_16-41-08](https://cloud.githubusercontent.com/assets/8018044/22210653/d8302820-e18a-11e6-974f-2b4104db2500.png)
![screenshot_2017-01-23_16-41-26](https://cloud.githubusercontent.com/assets/8018044/22210667/e394178a-e18a-11e6-9a50-93e0d167b12a.png)

**Comment by dhcodes** [comment]
@ulf1 Thanks for reporting. This is indeed interesting.

**Comment by texas2010** [comment]
wow. I test it too. yeah i confirmed too.

**Comment by raisedadead** [comment]
This has gone stale, because the behaviour is now a 404. We have a more updated issue discussing the implementation.

Closing
