### ISSUE TITLE
Waypoint: Use the Bootstrap Grid...

### ISSUE THREAD

**Issue by DaforLynx** [FreeCodeCamp/FreeCodeCamp#1277]
The diagram of the Grid or whatever isn't showing. In fact, I pressed F12 and it wasn't even there! Again, it could be FF or something. Reloaded, same.
![capture](https://cloud.githubusercontent.com/assets/13303368/8641295/072a5e94-28c7-11e5-8933-8cd6dbbe513b.PNG)
![capture2](https://cloud.githubusercontent.com/assets/13303368/8641294/0729de10-28c7-11e5-8984-f81e5487c65b.PNG)

**Comment by benschenker** [comment]
This seems to be fixed.
