### ISSUE TITLE
Works in Atom Editor - I tried ES6 and ES5

### ISSUE THREAD

**Issue by Docwali777** [freeCodeCamp/freeCodeCamp#12782]
Challenge [work-with-dynamic-data-in-d3](https://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/work-with-dynamic-data-in-d3) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<body>
<script >
  const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
  
  d3.select("body").selectAll("h2")
    .data(dataset)
    .enter()
    .append("h2")
    // Add your code below this line
       .text(function(d){return d + " USD"})
    
    
    // Add your code above this line
</script>
</body>

    ```

**Comment by dhcodes** [comment]
@Docwali777 the D3 challenges have some issues. Please see #12680. Closing in favor of #12762
