### ISSUE TITLE
Even if i have the correct answer, I need to reload the page for it to be accepted. 

### ISSUE THREAD

**Issue by ANewModern** [freeCodeCamp/freeCodeCamp#12789]
Challenge [change-styles-based-on-data](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/change-styles-based-on-data) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.98 Safari/537.36 Vivaldi/1.6.689.46</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<body>
<script>
  const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
  
  d3.select("body").selectAll("h2")
    .data(dataset)
    .enter()
    .append("h2")
    .text((d) => (d + " USD"))
    // Add your code below this line
    .style("color", (d) => {
    if (d < 20) {
      return red;
    } else {
      return green;
    }
  })
    
    
    // Add your code above this line
</script>
</body>

    ```

**Comment by dhcodes** [comment]
@ANewModern thanks for the issue. This is related to #12762 so I'm closing this to prevent duplicate issues.
