### ISSUE TITLE
[beta] Completing all of the items for a certificate does not award the certificate

### ISSUE THREAD

**Issue by P1xt** [freeCodeCamp/freeCodeCamp#12786]
#### Issue Description
Completing all the items for the Responsive Web Design Certificate does not cause the corresponding certificate to show up on the user's profile.

#### Browser Information
User Agent is: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36.

#### Screenshot
![camper p1xt s code portfolio freecodecamp](https://cloud.githubusercontent.com/assets/322175/22224959/3b46b1ea-e186-11e6-8372-5fdb8d38504a.png)

**Comment by P1xt** [comment]
I've actually now completed all starred items required for the Responsive Web Design and the JavaScript Algorithms and Data Structures Certificates and neither shows up on my profile.

Also, this time I payed attention to the text associated with claiming the certificate and they're referencing the old frontend cert requirements.

**Comment by systimotic** [comment]
@P1xt Thanks for checking out the beta and reporting this issue! (and for your amazing contributions to the forum as well!)

I believe the new certificates haven't been implemented yet 😅 https://github.com/freeCodeCamp/freeCodeCamp/issues/12794 is aimed at solving that. Should we close this issue in favour of that?

**Comment by P1xt** [comment]
@systimotic Yes, https://github.com/freeCodeCamp/freeCodeCamp/issues/12794 is more detailed in that it lists out specifics about what needs to happen in order to solve this completely.
