### ISSUE TITLE
[build] Update loopback components and migrations for gulp warnings in build.

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/freeCodeCamp#12780]
As of today, there is a verbose error in the gulp log as below:
```
The user model "User" is attached to an application that does not specify
whether other sessions should be invalidated when a password or
an email has changed. Session invalidation is important for security
reasons as it allows users to recover from various account breach
situations.

We recommend turning this feature on by setting
"logoutSessionsOnSensitiveChanges" to true in
server/config.json (unless you have implemented your own solution
for token invalidation).

We also recommend enabling "injectOptionsFromRemoteContext" in
User's settings (typically via common/models/*.json file).
This setting is required for the invalidation algorithm to keep 
the current session valid.


The user model "user" is attached to an application that does not specify
whether other sessions should be invalidated when a password or
an email has changed. Session invalidation is important for security
reasons as it allows users to recover from various account breach
situations.

We recommend turning this feature on by setting
"logoutSessionsOnSensitiveChanges" to true in
server/config.json (unless you have implemented your own solution
for token invalidation).

We also recommend enabling "injectOptionsFromRemoteContext" in
user's settings (typically via common/models/*.json file).
This setting is required for the invalidation algorithm to keep 
the current session valid.
```

**Comment by raisedadead** [comment]
The dependencies on some of the loopback components have to be upgraded and probably we would have to migrate to the recommendations.

I'll just put this on road map for now.

/cc @BerkeleyTrue

**Comment by BerkeleyTrue** [comment]
@raisedadead What loopback components have been updated?

**Comment by raisedadead** [comment]
I just took a second look at the warnings and the deprecations are not related to the warnings in the OP.

<blockquote>

**strong-remoting** deprecated The built-in CORS middleware provided by REST adapter was deprecated. See https://docs.strongloop.com/display/public/LB/Security+considerations for more details. node_modules/strong-remoting/lib/remote-objects.js:97:25

**loopback-explorer** deprecated The built-in CORS middleware provided by loopback-component-explorer was deprecated. See https://docs.strongloop.com/display/public/LB/Security+considerations for more details. server/boot/explorer.js:22:3
</blockquote>

Nevertheless its not mission critical right now I think, may be we should just skip ahead to Loopback 3 in future, when we can?

**Comment by BerkeleyTrue** [comment]
Yeah, I don't plan on moving to 3 until after beta is stable and in production.

I've yet to see those warnings. Is that the message in its entirety?

**Comment by raisedadead** [comment]
> Yeah, I don't plan on moving to 3 until after beta is stable and in production.

Agreed.

> Is that the message in its entirety?

For loopback warnings : Its the OP's block + what I have above.
