### ISSUE TITLE
Data Visualization with D3: Work with Data in D3

### ISSUE THREAD

**Issue by Docwali777** [freeCodeCamp/freeCodeCamp#12781]
Challenge [work-with-data-in-d3](https://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/work-with-data-in-d3) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Works in Atom Text Editor - does not pas test in FCC

```html
    
    
<body>
<script>
  const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
  
  // Add your code below this line
  
const data =  d3.select("body").selectAll("h2").data(dataset).enter().append("h2").text("New Title")
  
  // Add your code above this line
</script>
</body>

    ```

**Comment by dhcodes** [comment]
Closing in favor of #12762
