### ISSUE TITLE
Waypoint #58

### ISSUE THREAD

**Issue by 1genuinejd** [FreeCodeCamp/FreeCodeCamp#1279]
I am sorry if this is a stupid question but I don't understand what Waypoint wants on number 58. I am totally new to coding so am sorry if this is a dumb question.

**Comment by sidneygijzen** [comment]
Just to clarify; what is the title of the Waypoint? 

If I count correctly, you're working somewhere in the 'Responsive Design with Bootstrap' section?

**Comment by 1genuinejd** [comment]
Sorry for the delay I am on the Waypoint: Create a Set of Radio Buttons and the quick article shows this:
Add to your form a pair of radio buttons. Each radio button should be wrapped within its own label element. They should share a common name attribute. One should have the option of "indoor" and the other should have the option of "outdoor".

You can use radio buttons for questions where you want the user to only give you one answer.

Radio buttons are a type of input.

Each of your radio buttons should be wrapped within its own label elements.

All related radio buttons should have the same name attribute.

Here's an example of a radio button: <label><input type='radio' name='indoor-outdoor'> Indoor</label>.

So I guess my problem is that I dont know where to put it and how to assign it because I have tryed alot of different ways and have had no luck.

**Comment by benschenker** [comment]
Closing as stale, please reopen if this is still an issue for you
