### ISSUE TITLE
Unable to link account

### ISSUE THREAD

**Issue by ghost** [freeCodeCamp/freeCodeCamp#12790]
#### Issue Description

Unable to link github account in order to enable public profile. Seems similar to issue #6429

#### Your Code

```js
 The `user` instance is not valid. Details: `username` is not unique (value: "kyleek"); `username` User already exists (value: "kyleek").
```

**Comment by macgyver18e** [comment]
Do you have an account at github already? if so - don't setup new - just login; if not it seems that someone else is already using username kyleek so you'll need to create a new one

**Comment by kyleek** [comment]
Yes this is my github account 'kyleek'. It will not let me sign in via github I just get an oops something went wrong error.

**Comment by raisedadead** [comment]
Closing because OP has deleted their account.
