### ISSUE TITLE
Get new certificates working with new curriculum

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#12794]
Jonathan recently created the code and layout for the new certificates.

- [x] going through the "claim your ____ certificate" challenges grants camper the appropriate certificate
- [x] certificates have proper verbiage and all 9 have a different color that corresponds to one of the colors in our [design style guide](https://www.freecodecamp.com/design-style-guide/)
- [x] 3 old certificates and 6 new certificates all show up on profile if claimed

**Comment by P1xt** [comment]
Note: the "claim your ____ certificate" challenges need to have their verbiage checked as well. 

For instance: http://beta.freecodecamp.com/en/challenges/claim-your-responsive-web-design-certificate/claim-your-responsive-web-design-certificate lists:

> This challenge will give you your verified Responsive Web Design Certificate. Before we issue your certificate, **we must verify that you have completed all of our basic and intermediate algorithm scripting challenges, and all our basic, intermediate, and advanced front end development projects.**

which does NOT correspond to the actual requirements for attaining that certificate. The actual requirement is completion of the Responsive Web Design projects.

**Comment by atjonathan** [comment]
@P1xt, yeah, these certificates were created without direct knowledge of the new curriculum.

**Comment by P1xt** [comment]
@atjonathan makes sense, there's so much new content and certificate design doesn't really depend on how everything landed in terms of divvying up into certificates. I'm just noting that in addition to granting the appropriate certificate, the challenge verbiage should be modified to reflect what content is required for granting that particular certificate. Right now the challenge verbiage seems to be a cut and paste of the old frontend challenge verbiage.

**Comment by QuincyLarson** [comment]
@atjonathan thanks for tackling this. Please let me know if I can be of any help. I'm happy to pair on this with you if necessary.

**Comment by systimotic** [comment]
Referencing #11424 as it seems to related, perhaps even a duplicate.

**Comment by spieg** [comment]
You'll probably know, but the text for the "Javascript algorithms and data structures" certificate needs editing.
![image](https://cloud.githubusercontent.com/assets/24204953/26250623/ecace6aa-3caa-11e7-9ac7-3935c1444400.png)

**Comment by saschamonteiro** [comment]
the text for the "Claim Your APIs and Microservices Certificate" is incorrect too,
is it correct that the whole certificate claiming doesn't work yet in beta?

**Comment by systimotic** [comment]
@saschamonteiro That is correct. The purpose of this issue is to resolve that.

**Comment by SekethThoth** [comment]
I'm not able to access my profile since yesterday and today as well, and since I'm not able to access the profile I cannot see if I have been granted the Responsive Web Design certificate. Hope the issues is fixed soon.

**Comment by paweltar** [comment]
Yes, I'm unable to access my profile on beta FCC too, I am being redirected to `http://beta.freecodecamp.com/en/map`.
