### ISSUE TITLE
[beta] ES6 Intro link goes to middle of document rather than top

### ISSUE THREAD

**Issue by wildlifehexagon** [freeCodeCamp/freeCodeCamp#12796]
#### Challenge Name

Introduction to the ES6 Challenges

#### Issue Description

When you click "Introduction to the ES6 Challenges" on the map page, it loads to the middle of the document rather than the top.

#### Browser Information

* Browser Name, Version: Chrome Version 55.0.2883.87 m (64-bit)
* Operating System: Win10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 n/a
 
 
```
#### Screenshot

http://imgur.com/a/0kqgE

**Comment by systimotic** [comment]
Hi @wildlifehexagon, thank you for reporting this issue!

This seems somewhat related to https://github.com/freeCodeCamp/freeCodeCamp/issues/12710, although not entirely the same. I think they have the same cause, but solving one might not solve the other.

@dhcodes Should we have two separate issues for these, or should we merge them into a single issue about the scrolling not resetting?

**Comment by dhcodes** [comment]
I'm not sure. I think this may be unique to this challengeType. One easy fix could be to bump some of the content to a new frame as some of the other intros have done ([Example](http://beta.freecodecamp.com/en/challenges/applied-accessibility/introduction-to-the-applied-accessibility-challenges)). For now, let's leave it open as a separate issue.

**Comment by dhcodes** [comment]
Closing as resolved? Seems to work fine now.

**Comment by wildlifehexagon** [comment]
Yeah looks good, thanks for closing!
