### ISSUE TITLE
[beta] changes in the editor pane not reflected in the phone view

### ISSUE THREAD

**Issue by P1xt** [freeCodeCamp/freeCodeCamp#12802]
#### Challenge Name
All challenges.

#### Issue Description
On the live/production site, if I'm making changes in the editor pane (for instance, modifying the color of some text) that change is immediately reflected in the display / phone view. On beta, I have to click the "run tests" button before my changes are rendered to the display / phone view.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
![basic css change the color of text freecodecamp](https://cloud.githubusercontent.com/assets/322175/22244999/6a4485f4-e1f3-11e6-91a9-08ab36c96a8d.png)

**Comment by systimotic** [comment]
Hi @P1xt, thanks for reporting this issue!

There is so much going on with the beta that nobody picked up on this issue. A few issues later somebody reported the same thing. I'm closing this in favour of that, as more progress has been made there.
https://github.com/freeCodeCamp/freeCodeCamp/issues/12807
