### ISSUE TITLE
[Manipulating Complex Objects] Example is unsatisfactory as a guide

### ISSUE THREAD

**Issue by Undigon** [freeCodeCamp/freeCodeCamp#12806]
Challenge [Manipulating Complex Objects](https://www.freecodecamp.com/challenges/manipulating-complex-objects) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.

I think that it should stress the fact that you are looking at an array. This way, maybe new coders may recall that arrays need commas between... indexes, and pass the test with less effort.
Also, mentioning JSON is useless here and detracts from the exercise.

My code:
```javascript

var myMusic = [
  { 
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  }
  ]
  ]}// Add record here /*many attempts in many places including ".unshift()" and ".push()" species all because the example does not show a n-objects array making me wonder into the realms of the uncanny code.*/
];


```

**Comment by no-stack-dub-sack** [comment]
@Undigon Unless I am misunderstanding your meaning &mdash; the challenge pretty clearly states, twice, that this is an object on an array.

Once in the intro:
>This is an array which contains one object inside. The object has various pieces of metadata about an album. It also has a nested "formats" array. If you want to add more album records, you can do this by adding records to the top level array.

and once in the instructions:
> Add a new album to the myMusic array. Add artist and title strings, release_year number, and a formats array of strings.

**Comment by erictleung** [comment]
@Undigon I agree with @no-stack-dub-sack. If you read the text that accompanies the challenge, it mentions you are looking at an array. JSON is mentioned because of the similarities between JavaScript objects. But I can see an argument of how it could be distracting.

**Comment by TheIncorrigible1** [comment]
Until I read your issue, I didn't understand what syntax the interpreter was expecting, either.  The mention of JSON additionally was distracting if we are not learning/using it in the exercise.  It may be common sense to people who are coming from a programming background, but with only hobbyist experience, it was unclear.

**Comment by btken88** [comment]
The problem is that there is no comma after the pre-built entry (line 12 of the code). So if, like me, you're operating under the assumption that you're not to change code above the comment, you're screwed. I would suggest that the exercise already have the comma after the }
