### ISSUE TITLE
'Basic HTML5 and CSS' Waypoint 28 auto-skipped

### ISSUE THREAD

**Issue by justinrroth** [FreeCodeCamp/FreeCodeCamp#1280]
I didn't realize it until I reviewed my "Map" progress, but Waypoint 28 "Create a Bulleted Unordered List" was auto-skipped. I noticed, in retrospect, that I jumped from Waypoint 27 to 29 without ever seeing 28. I had to click on Waypoint 28 in my "Map" to complete the task (as it curiously wasn't marked as complete), rather than it showing up linearly during the tutorial process. Perhaps it is a browser issue on my end, though--just thought I'd mention it. Keep up the good work!

**Comment by benschenker** [comment]
Closing as stale. If you still encounter this issue please reopen it
