### ISSUE TITLE
Campers can pass challenge without submitting any code to style. 

### ISSUE THREAD

**Issue by daulis809** [freeCodeCamp/freeCodeCamp#12803]
#### Challenge Name

[Css Flexbox: Applying the Flex-direction Property to Create Rows in the Tweet Embed](http://beta.freecodecamp.com/en/challenges/css-flexbox/applying-the-flexdirection-property-to-create-rows-in-the-tweet-embed)

#### Issue Description

Since flex-direction is set to row by default, the campers can pass the challenge without submitting any code to the styling of the page.

#### Browser Information

*  **Browser Name, Version:**  Google Chrome Version 55.0.2883.87 m (64-bit)
*  **Operating System:**   W10
*  **Mobile, Desktop, or Tablet:**   Desktop

#### Screenshot

![fcc-github-issue](https://cloud.githubusercontent.com/assets/20654951/22250574/6b4f614a-e215-11e6-9395-b1c20fd4e990.PNG)

**Comment by ananaymital** [comment]
@daulis809 Thanks for reporting this issue. You see `flex-direction` has a default value of `row`, so if the code doesn't change it's value or specify the property it would mean that `flex-direction` is still set to `row`.

What I would suggest is changing the `flex-direction` property of header to **`row-reverse`** (I checked and it is not present anywhere in the course). That way students can learn a new possible (and cool) value for this property and they'll have to change the default value which we can check easily.

@systimotic @dhcodes What say?

**Comment by HKuz** [comment]
@daulis809 thanks for the issue, indeed, the tests are passing without any changes given the default value. There are actually several open issues right now related to the Flexbox section, so I'm going to consolidate the discussion on fixing them here.

@ananaymital - I liked your idea about mixing the challenge up to use `row-reverse`, the only problem is that it makes the tweet embed look a little weird by changing the order of the `header` and `footer` items:

Normal:

![screen shot 2017-01-26 at 2 01 51 pm](https://cloud.githubusercontent.com/assets/9591826/22346547/854f5816-e3d2-11e6-93d6-cc82f426ffcd.png)


Reversed:

![screen shot 2017-01-26 at 1 59 06 pm](https://cloud.githubusercontent.com/assets/9591826/22346558/8ce7c072-e3d2-11e6-9227-48ced17b9f6e.png)


I think for now we can just add a test using regex for this challenge.

@ajain17, I know you've already started working on a PR - if you could make the following changes as well, it can address a number of open items in this section:

- Using display: flex with Two boxes
  - Change the size of the `divs` in the seed code to `width: 200px;` and `height: 200px;` (Addresses #12866)
- Adding Flex Superpowers to the Tweet Embed
  - Works okay, no change for this PR. There is an open discussion in #12867 on whether it's necessary
- Using the Flex-direction Property to Make a Row
  - The tests pass without any code, and needs regex test(s) similar to this issue added (Addresses #12814)
  - Change the size of the `divs` in the seed code to `width: 200px;` and `height: 200px;` 
- Applying the Flex-direction Property to Create Rows in the Tweet Embed
  - The tests pass without any code (Addresses this issue #12803)
- Using the Flex-direction Property to Make a Column
  - Change the size of the `divs` in the seed code to `width: 200px;` and `height: 200px;` (Addresses #12870)

When you open a PR, make sure to reference that it closes: #12803, #12814, #12866, and #12870 

Let me know if anything is unclear, thanks so much!

**Comment by ajain17** [comment]
@HKuz  Great thanks for compiling everything. I'll start working on it.

**Comment by ananaymital** [comment]
@HKuz @ajain17 actually I meant changing just the header so that it won't look very much different from the previous case.
![image](https://cloud.githubusercontent.com/assets/12645471/22352591/d5c34904-e442-11e6-8311-605aa3065161.png)
But if you think otherwise, it's fine.
Happy to help.

**Comment by ajain17** [comment]
^^ I like @ananaymital's idea of changing only the header.
