### ISSUE TITLE
[beta] example screen content not visible until code is run

### ISSUE THREAD

**Issue by JesiMarie** [freeCodeCamp/freeCodeCamp#12807]
Challenge [adjusting-the-padding-of-an-element](http://beta.freecodecamp.com/en/challenges/basic-css/adjusting-the-padding-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html
    
    
<style>
.injected-text {
  margin-bottom: -25px;
  text-align: center;
}

.box {
  border-style: solid;
  border-color: black;
  border-width: 5px;
  text-align: center;
}

.yellow-box {
  background-color: yellow;
  padding: 10px;
}

.red-box {
  background-color: red;
  padding: 20px;
}

.green-box {
  background-color: green;
  padding: 10px;
}
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
<h5 class="box red-box">padding</h5>
<h5 class="box green-box">padding</h5>
</div>

```
    
The "phone screen" where the code is shown doesn't update until after the run test button is pressed. Has been this way since I began the CSS section of the beta. It makes it awkward when working on the cat photo app, but when it gets to showing the margins, it gives me the picture of the cat photo app instead of the yellow, red, and green boxes.

![bug](https://cloud.githubusercontent.com/assets/11278237/22262333/604d3186-e225-11e6-8fe0-dd1478d99dc6.png)

**Comment by Greenheart** [comment]
I can confirm this for the Applied Visual Design challenges as well. It wouldn't surprise me if this affects all basic HTML/CSS challenges.

To fix this, we basically need to make sure the challenge framework updates the results view (the `fcc-main-frame` iframe) around the time when it displays "Your next challenge has arrived".

### The updated flow:
1. Challenge completed, user want to progress to next one.
2. Load the next challenge into the editor.
3. **When new challenge is ready, update the results view** (`fcc-main-frame`), If possible, without running the tests
4. Display "Your next challenge has arrived".

**Comment by no-stack-dub-sack** [comment]
@Greenheart also see #12859 - closing that one as duplicate, but this is def an issue in other areas as well like you hypothesized, I can confirm it as well for the Flexbox challenges.

**Comment by Greenheart** [comment]
@no-stack-dub-sack Nice detective work! 

I'll see if I can find the code that could be used to fix this.

**Comment by Greenheart** [comment]
I've most likely found where we need to update the results-view - [it's around this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/routes/challenges/redux/next-challenge-saga.js#L78)

The question now is how to trigger the challenge framework to execute the code without also executing the tests. I'll continue by looking how the regular execution of challenges works.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson Do you think as we get closer to shipping beta, we should start to collect issues like this in a more organized way as a TODO list of things that should def be done before that actually happens?

This particular issue has been open for a while, and I think will have a serious impact on User Experience. Also, another difference in the current production app, is that changes to CSS and HTML code are reflected instantly in the preview pane, this def makes solving challenges easier and I think could also affect UX for the new curriculum.

OR... will all of this be completely moot once Berkeley's new app layout PR is ready?

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack Yes - once we ship @berkeleytrue's layout, we can see whether these are still relevant and then tackle them. I'll leave this issue open for now.
