### ISSUE TITLE
[beta] login state on subsequent visits

### ISSUE THREAD

**Issue by P1xt** [freeCodeCamp/freeCodeCamp#12801]
#### Issue Description
Twice now I've been working through challenges on the beta site (logged in just fine) and closed out my browser at the end of the day. When I next returned to the site, the app redirected me to the last challenge I was working on but the editing and display panes were empty, and rather than my avatar and profile link in the nav, there is a link to "sign up".

No amount of clicking on "sign up" will get me back to a state where I can sign up or sign back in.

Clicking on map shows me all challenges on the map. However, I would surmise that I am not logged in as none of the challenges I've completed are marked as complete.

Oddly though, clicking on the shop updates my state to signed in, the challenges have content again, my avatar reappears, and everything goes back to normal.

#### To reproduce
* Login on the beta site.
* Complete any item on the map.
* Close the browser.
* Open the browser and navigate back to the beta site.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet:  Desktop

#### Screenshot
![freecodecamp](https://cloud.githubusercontent.com/assets/322175/22243857/c3b733fc-e1ee-11e6-96c2-51d8945301b1.png)

**Comment by OFFLlNE** [comment]
Yea, happened to me ALOT.
Also I just can't get off this redirected page in any easy way.
Almost none of the menu links redirect me(only shop). (Map) gives me map URL but I have to refresh this url for it actually to redirect me to there.
Waiting for big PR that would fix it and make it usable

**Comment by P1xt** [comment]
The following error is thrown to the console:

Uncaught Error: Minified React error #32; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=32&args[]=52 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at n (http://beta.freecodecamp.com/js/bundle-0f6b2dba787d716232ef.js:1:24586)
    at s (http://beta.freecodecamp.com/js/bundle-0f6b2dba787d716232ef.js:6:15069)
    at c (http://beta.freecodecamp.com/js/bundle-0f6b2dba787d716232ef.js:6:15540)
    at h.getPublicInstance (http://beta.freecodecamp.com/js/bundle-0f6b2dba787d716232ef.js:48:10501)
    at r (http://beta.freecodecamp.com/js/bundle-0f6b2dba787d716232ef.js:48:25701)
    at Object.a.attachRefs (http://beta.freecodecamp.com/js/bundle-0f6b2dba787d716232ef.js:48:25932)
    at h.r (http://beta.freecodecamp.com/js/bundle-0f6b2dba787d716232ef.js:8:15787)
    at e.notifyAll (http://beta.freecodecamp.com/js/bundle-0f6b2dba787d716232ef.js:23:23222)
    at r.close (http://beta.freecodecamp.com/js/bundle-0f6b2dba787d716232ef.js:48:25212)
    at r.closeAll (http://beta.freecodecamp.com/js/bundle-0f6b2dba787d716232ef.js:10:26791)

**Comment by raisedadead** [comment]
Can't reproduce on local.
/cc @BerkeleyTrue

**Comment by P1xt** [comment]
@raisedadead I just double-checked to confirm. Browsed back to the beta site (having not yet been there today) and I experienced the same issue I originally reported.

**Comment by raisedadead** [comment]
We are aware of the issue and investigating, we just haven been able to reproduce it on local.

**Comment by systimotic** [comment]
Adding the description of #12674 to this:
>Upon login, the user is brought back to the next challenge. If the challenge happens to be a project, the page layout is broken and clicking on Map has no effect.
>
>Steps to reproduce: log out of the beta site, close browser window, and log in again using email and password.

**Comment by leonfeng** [comment]
@raisedadead I just reproduced it on local. Please note that the issue only occurs if the current challenge is a project (at least in my experience).

**Comment by raisedadead** [comment]
@systimotic @leonfeng Thanks a ton, I have been running around the bushes for the root cause. 
Also I am tagging this as help wanted.

**Comment by leonfeng** [comment]
Root cause isolated: missing `</a>` from seed JSON files. Working on a fix.

**Comment by systimotic** [comment]
Great catch @leonfeng!
