### ISSUE TITLE
[beta]Es6: Problems with the var keyword

### ISSUE THREAD

**Issue by KenzoM** [freeCodeCamp/freeCodeCamp#12818]
#### Challenge Name
https://beta.freecodecamp.com/en/challenges/es6/problems-with-the-var-keyword

#### Issue Description

I'm not sure if it is a bug or just me, but I can't seem to pass this challenge, even my simply commenting out `let redNosedReindeer = "Comet";` and re-ordering the code so the hoisting is done correctly to assign `redNosedReindeer` before `favorite`

#### Your Code

```js
 `let redNosedReindeer = "Rudolph";
// let redNosedReindeer = "Comet";
let favorite = redNosedReindeer + " is Santa's favorite reindeer."; 
`
 
 
```

**Comment by SergiOca87** [comment]
Same issue, if it doesn't have a bug then it's not explained properly, I have tried every possible combination. 

Also "favorite should return Santa's favorite reindeer.");" So we should delete the  "= redNosedReindeer +" from favorite as well? It's just overall confusing really.

**Comment by pyrosomida** [comment]
"camper is loged" - typo - should be "logged".

**Comment by rodrigo-fontes** [comment]
Same issue here. Don't know what to do.

**Comment by mordmaman** [comment]
I just attempted this. Any time I tried to change the var to let and run the test it said "something went wrong" only time it worked was when I removed the "comet" line completely

**Comment by raiden357** [comment]
> I just attempted this. Any time I tried to change the var to let and run the test it said "something went wrong" only time it worked was when I removed the "comet" line completely

I had to do the same thing. Also it keeps saying "use the function form of use strict". I'm using Chrome

**Comment by telepylus** [comment]
Yeah, this task is really annoying me, not explained properly... is incorrect, using wrong answers etc.

**Comment by abigailbeets** [comment]
Hi, newbie helper here. I think the directions should be re-written. "Use strict" is not required to pass the test and there is no function (so you can't really use the function form of 'is strict'); furthermore, wrapping the code in a function either fails all of the tests or says 'something went wrong, try again later'. I would be happy to rewrite the directions to be more clear, or the tests to accommodate a function.

**Comment by profoundhub** [comment]
Getting error: 
`// running test`
`"missing ) after argument list"`
`// tests completed`
