### ISSUE TITLE
[beta] Test passes without conditions being met

### ISSUE THREAD

**Issue by gt6089** [freeCodeCamp/freeCodeCamp#12814]
CHALLENGE:
http://beta.freecodecamp.com/en/challenges/css-flexbox/using-the-flexdirection-property-to-make-a-row

ISSUE:
Clicking 'Run tests' button passes the tests without the test conditions being met. I did not add the CSS property flex-direction to the #box-container element, and give it a value of row.

BROWSER INFO:
* Chrome 55.0.2883.87 m
* Windows 7
* Desktop

SCREENSHOT:
![image](https://cloud.githubusercontent.com/assets/16689321/22271736/02667804-e24b-11e6-803c-c60f00637c91.png)

**Comment by gt6089** [comment]
In fact, it looks like changing the code to meet the test conditions has no effect on the screen preview. The container elements continue to show as columns. This also seems to be true of the next challenge at least, Css Flexbox: Applying the Flex-direction Property to Create Rows in the Tweet Embed.

Incidentally, I need to click 'run tests' to see what I'm working with as the screen preview is blank on initial page load. Clicking 'run tests' populates the preview.

**Comment by RUTHVERTUDAZOPAYOT** [comment]
[](url)www.ruthvertudazopayot.com [](url)

**Comment by RUTHVERTUDAZOPAYOT** [comment]
[@#[](url)]( #12481 )

**Comment by dhcodes** [comment]
@gt6089 Thanks for the issue. I believe this is very similar to #12803 where @ananaymital has pointed out that flex-direction defaults to `row`. We should work on a fix for both of these.

**Comment by HKuz** [comment]
@gt6089 @dhcodes - I've consolidated a number of the related Flexbox issues over in #12803. We have someone working on a fix (including this issue), and hopefully resolve this soon.
