### ISSUE TITLE
Rendering or wording is strange for "Waypoint: Style Text Inputs as Form Controls"

### ISSUE THREAD

**Issue by kotp** [FreeCodeCamp/FreeCodeCamp#1281]
In [this Waypoint](http://www.freecodecamp.com/challenges/waypoint-style-text-inputs-as-form-controls) the wording "Give the text input in your form the class "form-control"." or perhaps the highlighting is hard to understand.

If I understood my misgivings better, I would correct it in [this line of code](https://github.com/FreeCodeCamp/freecodecamp/blob/612de6911e08bee18d3fbd412151415d50ca2d62/seed/challenges/bootstrap.json#L1231)...  but unsure how or why it seems strange.

![badhighlightng](https://cloud.githubusercontent.com/assets/16747/8644687/2850104e-290f-11e5-80f9-4f739e493823.png)

**Comment by krisgesling** [comment]
Seems this has been reported a few times - bug #'s 1383, 1328, 1281, 1082
Looks like QuincyLarson fixed this on 20 June, so I'm assuming it just hasn't yet been pushed out.
