### ISSUE TITLE
I got the solution, yet the site will not let me proceed.

### ISSUE THREAD

**Issue by joshyu2009** [freeCodeCamp/freeCodeCamp#12822]
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#_=_#?solution=var%20array%20%3D%20%5B%5D%3B%0Avar%20x%20%3D%201%3B%0Afunction%20factorialize(num)%20%7B%0A%20%20for(var%20i%20%3D%201%3B%20i%20%3C%3D%20num%3B%20i%2B%2B)%3B%7B%0A%20%20%20%20array.push(i)%3B%0A%20%20%7D%0A%20%20for(var%20j%20%3D%200%3B%20j%20%3C%20array.length%3B%20j%2B%2B)%20%7B%0A%20%20%20%20x%20%3D%20x%20*%20array%5Bj%5D%3B%0A%20%20%7D%20return%20x%3B%0A%7D%0A%0Afactorialize(9)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [];
var x = 1;
function factorialize(num) {
  for(var i = 1; i <= num; i++);{
    array.push(i);
  }
  for(var j = 0; j < array.length; j++) {
    x = x * array[j];
  } return x;
}

factorialize(9);
```

**Comment by erictleung** [comment]
@joshyu2009 thanks for the issue. You have global variables in your code. Our challenge tests run your function over and over and if you have any global variables, they will change with each test. So move your global variables to within your function and your code will pass. Happy coding!

**Comment by rquattros** [comment]
I came across the exact same solution and exact same error. Moved the variables to inside the function and it's now recognized as correct answer! Thanks!
