### ISSUE TITLE
Storing Values with the Assignment Operator

### ISSUE THREAD

**Issue by sanjayk722** [freeCodeCamp/freeCodeCamp#12826]
#### Challenge Name
Storing Values with the Assignment Operator

#### Issue Description
Do not change code above the line
a should have a value of 7
b should have a value of 7
a should be assigned to b with =

#### Browser Information
In JavaScript, you can store a value in a variable with the assignment operator.

myVariable = 5;

Assigns the Number value 5 to myVariable.

Assignment always goes from right to left. Everything to the right of the = operator is resolved before the value is assigned to the variable to the left of the operator.

myVar = 5;
myNum = myVar;
Assigns 5 to myVar and then resolves myVar to 5 again and assigns it to myNum.

Instructions
Assign the value 7 to variable a.

Assign the contents of a to variable b.

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code
```
// Setup
var a;
var b = 2;

// Only change code below this line

```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/25341944/22285107/4b10d5f2-e310-11e6-9f61-9c2890e933c0.png)

**Comment by raisedadead** [comment]
What is the issue that you are facing?

The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!

**Comment by ajain17** [comment]
What's the issue here? As I see in the screenshot, you need to follow the instructions and then run tests.

**Comment by vaibhavdaren** [comment]
@sanjayk722 Please read the question carefully and code accordingly.The question is correct.

**Comment by tommygebru** [comment]
This challenge works, although i can understand the confusion...

Also returning the answer does not pass the challenge, because it is not specific to the instructions

for example
```js
return c;
/*does not pass the challenge*/
```

**Comment by benjaminspak** [comment]
If you're teaching someone to code, telling them how to assign a variable in one exercise, and then later in the exercise presenting unclear terms telling them to assign a set of variables that makes no logical sense to a newbie your teaching style is at fault, not the newbie's understanding of the instructions. Please rethink the instructions.

**Comment by RobertWSON** [comment]
I had a problem with this question from https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/storing-values-with-the-assignment-operator

They want you to
Assign the value 7 to variable a.
Assign the contents of a to variable b.

I have tried 
var a =7;
var b=7;
var a = var b;      and also a = b;

It has across on: 
     Do not change code above the line 
     a should be assigned to b with =

I wonder why it doesn't like what I have put, how can I work out this trick question?
