### ISSUE TITLE
Bonfire #32: Smallest Common Multiple - Suggestion for a minor improvement of the description

### ISSUE THREAD

**Issue by jrtmns** [FreeCodeCamp/FreeCodeCamp#1282]
Having experienced some issues in correctly understanding what is actually requested in the instructions of Bonfire #32, I'd like to suggest a minor update to its description as follows:

>Find the smallest common multiple of the provided parameters that can evenly be divided by both, as well as by all sequential numbers in the range between these parameters.

>The range will be an array of two numbers that will not necessarily be in numerical order.

>e.g. for 1 and 3 - find the smallest common multiple of both 1 and 3 that is evenly divisible by 1,2 and 3.  

>Here are some helpful links:

>[Smallest common multiple] (https://www.mathsisfun.com/least-common-multiple.html)
>[Remainder] (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Remainder_())

Do note that not understanding the current instructions may be language barrier related, and once you actually understand what is being asked the current instructions do seem clear. However, searching the Gitter chat logs does reveal that other people seem to be struggling with the aforementioned as well.

**Comment by rainywoods** [comment]
I did not understand the directions either. This makes more sense.
