### ISSUE TITLE
[beta] Bug reporting issue

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/freeCodeCamp#12838]
When you use the "Bug" button on a challenge, in a lot of cases, the closing backticks are indented, which causes them to be displayed as code. This is particularly annoying when there is content (especially images) beneath the code in the bug report, as it then also displays as code.

This does not seem to happen consistently for all challenges, but it seems to be happening for a large amount of them. Out of 5 randomly picked challenges, only one did not have this problem.

**Comment by Greenheart** [comment]
Haha this sure must be annoying!

Confirmed on a few random challenges. If someone finds a bug button that behaves correctly, please post it here for reference.

Without knowing how the UI is implemented or where it can be found in the code, it seems like the GitHub page for the new issue is opened based on a dynamic link, populated with URL-formatted content from the current challenge.

To fix this issue, there probably is a tab or a few spaces too much at the end of the issue-template. If we can find the code that generates the link, this should be pretty easy to fix!

**Comment by dhcodes** [comment]
I believe this is the file but the opening backticks look the same as the closing ones: https://github.com/freeCodeCamp/freeCodeCamp/blob/549cfc305f75d8c6036a3cde65c47b518607b18c/common/app/routes/challenges/redux/bug-saga.js

**Comment by Greenheart** [comment]
@dhcodes Nice catch!

Without knowing dedent too well, but after [reading about it](https://www.npmjs.com/package/dedent), it says that "Leading and trailing lines will be trimmed".

If we look at the resulting string sent to new GitHub issues, the dedent `dedent` package successfully removes the leading linebreak at the end of [line 15](https://github.com/freeCodeCamp/freeCodeCamp/blob/549cfc305f75d8c6036a3cde65c47b518607b18c/common/app/routes/challenges/redux/bug-saga.js#L15) and the whitespace before the opening backticks.

But somehow `dedent` misses the whitespace before the closing backticks.

I can't see what would cause this after looking at either the [dedent source](https://github.com/dmnd/dedent/blob/master/dedent.js) or the [bug-saga source](https://github.com/freeCodeCamp/freeCodeCamp/blob/549cfc305f75d8c6036a3cde65c47b518607b18c/common/app/routes/challenges/redux/bug-saga.js)

**Comment by systimotic** [comment]
Thanks for helping with the hunt @Greenheart @dhcodes! I created a PR to fix this.
