### ISSUE TITLE
Return Early Pattern for Functions

### ISSUE THREAD

**Issue by brahms101** [freeCodeCamp/freeCodeCamp#12835]
missing } under  // Only change code above this line

reads

 // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

should read

// Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}
}

**Comment by OFFLlNE** [comment]
@brahms101 Thank you for reporting the issue.

The code has only 1 opening curly brace, so it needs only 1 closing curly brace.
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by ryander** [comment]
It does say don't change code below this line, but you have to with the closing curly brace of the else statement. 

I don't think you should add one in like suggested, but definitely be more clear if you are giving directions.
