### ISSUE TITLE
This test needs a better explanation There are multiple times it says these colors and to switch them wihththe hex code.. i've gone through all of them and it still says its wrong 

### ISSUE THREAD

**Issue by KabbaKreek3** [freeCodeCamp/freeCodeCamp#12839]
Challenge [Use Hex Code to Mix Colors](https://www.freecodecamp.com/challenges/use-hex-code-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20%23FF0000%0A%20%20%7D%0A%20%20.green-text%20%7B%0A%20%20%20%20color%3A%20%2300FF00%0A%20%20%7D%0A%20%20.dodger-blue-text%20%7B%0A%20%20%20%20color%3A%20%232998E4%0A%20%20%7D%0A%20%20.orange-text%20%7B%0A%20%20%20%20color%3A%20%23FFA500%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20FF0000!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22green-text%22%3EI%20am%2000FF00!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22dodger-blue-text%22%3EI%20am%2022998E4!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orange-text%22%3EI%20am%20FFA500!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: #FF0000
  }
  .green-text {
    color: #00FF00
  }
  .dodger-blue-text {
    color: #2998E4
  }
  .orange-text {
    color: #FFA500
  }
</style>

<h1 class="red-text">I am FF0000!</h1>

<h1 class="green-text">I am 00FF00!</h1>

<h1 class="dodger-blue-text">I am 22998E4!</h1>

<h1 class="orange-text">I am FFA500!</h1>

```

**Comment by dhcodes** [comment]
@KabbaKreek3 your code is indeed correct, but you are missing semicolons on each style. While this is not a pure requirement for CSS, it has been discussed before (see: https://github.com/freeCodeCamp/freeCodeCamp/issues/8274) and it's been decided that the tests should require a semicolon for single attributes too as this is a best-practice.
