### ISSUE TITLE
reopen 12811

### ISSUE THREAD

**Issue by Brittanyw58** [freeCodeCamp/freeCodeCamp#12840]
I know what a div tag is and I know how to close them! I have been to the help chatrooms and they are not helpful at all!!! They just tell me to do my coding like I did, and then say confusing things that don't answer my question. I have trying reopening my browser like they tell me to in the chat cuz that is the only thing that they can think of. I really want to move on, but it keeps saying my div tag  does not have a closing one. If that is the case can someone please point out where??? because up until now they give me some random answer that has nothing to do with my question.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by dhcodes** [comment]
@Brittanyw58 can you edit your post to include the challenge name and your code?

**Comment by raisedadead** [comment]
@dhcodes #12811

**Comment by raisedadead** [comment]
@Brittanyw58 sorry to here that you havent gotten help in the chat room, but this issue tracker is not for coding assistance. 

You can either use the chat rooms or the forum. And someone will surely help out! Apologies, will have to close this.

The chat rooms do get a bit noisy at times, but trust me they and the forum are the best place to seek coding assistance.

**Comment by Brittanyw58** [comment]
Responsively Style Radio Buttons

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>
    </div>
  </div>
  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo"> </form>
    <div class="row"><div class="col-xs-6">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label></div><div class="row"><div class="col-xs-6">
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label></div>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>

**Comment by Brittanyw58** [comment]
Responsively Style Radio Buttons

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>
    </div>
  </div>
  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo"> </form>
    <div class="row"><div class="col-xs-6">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label></div><div class="row"><div class="col-xs-6">
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label></div>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button



________________________________

**Comment by TurtleWolf** [comment]
looking into the same thing right now.. did you ever get an answer? Is it a bug?

**Comment by Brittanyw58** [comment]
I looked through the bugs page and found someone who had the right coding and it worked.
I think it was closer to the bottom or on page 2.

**Comment by TurtleWolf** [comment]
I think we get focused on the buttons we were just working with.. I was ignoring the 'radio' buttons further down.. but i think it's neat to see so many people making the same assumption.. it's like duh.
