### ISSUE TITLE
[beta][UI] iframe change for each project's youtube tutorial

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12848]
Projects that include a youtube video has a set width which is 40% smaller than the parent div.

There should be a change in width for the iframe to have a `width:100%`

**Comment by QuincyLarson** [comment]
We're removing all project videos from our platform and implementing a multi-file editor so campers don't have to use CodePen any more. Please see https://github.com/freeCodeCamp/freeCodeCamp/issues/12753
