### ISSUE TITLE
Waypoint: Harness Dynamic HTML > Acronym "DOM" used before it is explained

### ISSUE THREAD

**Issue by angiecan** [FreeCodeCamp/freecodecamp#1284]
In "Waypoint: Harness Dynamic HTML" step 2, "Let's learn some more advanced ways to use jQuery to manipulate the DOM," the acronym DOM is used before user knows what it is. It distracted me so much, I looked around the map and other previous lessons to see if I had missed it. Then I Googled to find out that it means "Document Object Model."

Maybe once I dig into step 3 ("Go to http://www.codecademy.com/courses/web-beginner-en-v6phg/0/1 and complete the third section."), I'll see "DOM" is introduced there, but FCC may want to consider adding a step between 1 and 2 that introduces and explains DOM.

**Comment by Bumcus** [comment]
I had this same issue at first. But then I found, if you go back to the first lesson and video on "Getting started with JQuery" and click the link at the link to go do the firsts module. After completing it don't exit out or click back on your browser. Click the "Start next lesson" button at bottom of screen. That takes you to the next part where they explain what DOM is and how you use it. It is a bit confusing but once you get used to it it gets easier. Good Luck and have fun!

**Comment by angiecan** [comment]
Thank you, @Bumcus! I started wondering about this a couple Waypoints into jQuery. 

What's confusing is that Step 5 of "Waypoint: Get Started with jQuery" says, "Go to http://www.codecademy.com/courses/web-beginner-en-bay3D/0/1 and complete the first section." 

The definition of "first section" is not clear to the user. As a result, user clicks the code academy link, goes to "Introduction to jQuery" step 1/13, but you don't know if step 1 is the "first section" or if some subset of 13 steps is the first section, or if all 13 steps are the first section.

My suggestion is that FreeCodeCamp makes the instructions in Waypoints less ambiguous where the code academy "sections" are indicated.

I'll create a separate ticket for this suggestion and close this one.
