### ISSUE TITLE
[beta][UI] projects found in Map with asterisk

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12845]
Projects found in Map with an asterisk 
for example
`Visualize Data with a Bar Chart*`
Dont actually have a footnote or explanation for the asterisk either:

-on the project webpage, 
-the bottom of the Data Visualization curriculum on the Map page itself
-the absolute bottom of the Map page itself

**Comment by dhcodes** [comment]
@tommygebru closing because this will be resolved by https://github.com/freeCodeCamp/freeCodeCamp/issues/12721
