### ISSUE TITLE
[beta] Curriculum hours and certification

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12841]
The hours and certification have changed and should be reflected on this page
http://beta.freecodecamp.com/en/challenges/join-the-free-code-camp-community/learn-how-free-code-camp-works

Front end certification
now includes 3 prerequisite curriculums (and certifications): 
-responsive
-javascript algo.
-frontend libraries
Total hours is 490 roughly 500 hours

**Comment by erictleung** [comment]
My rendition of the new hours and certifications page. I couldn't figure out what the original font was so I used the Roboto font. 

![update-hours-fcc](https://cloud.githubusercontent.com/assets/2754821/22403654/04e18174-e5d3-11e6-89ca-228db1462feb.png)

**Comment by tommygebru** [comment]
@erictleung the freeCodeCamp Style Guide https://freecodecamp.github.io/design-style-guide/
It shows that Lato is the de facto font-style for FCC

**Comment by raisedadead** [comment]
This page was removed from the landing challenge. Going ahead and closing.
