### ISSUE TITLE
[beta][UI] a quick link to each of the 6 curriculums

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12847]
There is a lot to scroll on the Map page and it quickly becomes uncomfortable.

Proposing quick links for the Maps page if opened in full on desktop.

**Comment by Greenheart** [comment]
@tommygebru Could you explain this further? :blush:

**Comment by tommygebru** [comment]
Of course -  basically a table of contents, which will enable page jumps with `anchor tags`

**Comment by Greenheart** [comment]
@tommygebru The **"Hide all challenges"** button offers this kind of quick-navigation. But I agree it could be further improved. Maybe by hiding all challenges by default?

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (101/100 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60167 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dnx2n-0003PO-Oq
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:17 -0400
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:54204 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1dnx2X-0001ZL-3m
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:01 -0400
Date: Fri, 01 Sep 2017 18:16:00 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1504314960;
	bh=0qs0BTWQ5JR37SAIOC/G8Mv2X5RHAnbFRNY/Zq8dCF4=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=QFrQTIXRTVunoknDBftZz7Jno8Nn3/uvsxCplamsGnKI3Vzga65HWYIGWqs4wPhhk
	 Bp52/e6cxpyTXQkx5BJ5fDbUE68LqTNA2k9T4Ma5vpvL1V/2CBSZDY7LHS5RwwRIBY
	 jNpwjxdExNdKjgQ/TNCciCeIa5hsbsTnoi6v2dew=
