### ISSUE TITLE
The text won't turn blue.

### ISSUE THREAD

**Issue by LotusBlossom3** [freeCodeCamp/freeCodeCamp#12857]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20blue%3B%7D%0A%3C%2Fstyle%3E%20%20%0A%20%20%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {color: blue;}
</style>  
  
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by tommygebru** [comment]
@LotusBlossom3 

Your solution actually removed the h2 element tag for html.

This challenge works correctly, for more help please join the Freecodecamp chatrooms.
https://gitter.im/FreeCodeCamp/home

**Comment by tommygebru** [comment]
How do I close an Issue?

**Comment by raisedadead** [comment]
Hi @LotusBlossom3 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!

**Comment by tommygebru** [comment]
@raisedadead how can I close issues and become a Member or core contributor?

**Comment by fahadullah786** [comment]
First delete the privious h2 attributes and write the style element.
<style> </style>
second, write the code with bracket enclosed and semicolon.
<style> h2 {color:blue;} </style>
third, write the state of h2 that you wanted in that particular style and color.
<style> h2 {color:blue;} </style>
<h2> cat photo app </h2>
TEST RUN

**Comment by masters-george** [comment]
<style>
    h2 {
      color: blue;
    }
  </style>

<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

I was able to reproduce this error using Chrome, Firefox, and Opera using both Windows and Linux machines. This code works properly in the production course. What changed in the beta?
