### ISSUE TITLE
[beta] D3: Learn About SVG in D3 Constants and instructions

### ISSUE THREAD

**Issue by becausealice2** [freeCodeCamp/freeCodeCamp#12853]
Challenge [learn-about-svg-in-d3](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/learn-about-svg-in-d3) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The provided code for this challenge includes constants that, I assume, are to be used for the width and height attributes, but the instructions don't mention them anywhere:
```
Add an svg node to the body using append(). Give it a width attribute of 500 and a height
attribute of 100 using the attr() method for each. You'll see it in the output because
there's a background-color of pink applied to it in the style tag.
```

I strongly recommend rewording to instruct campers to set the width/height attributes to the values in the `w` and `h` constants instead of hard-coding the values into the D3 code:

```html
<style>
svg {
  background-color: pink;
}
</style>
<body>
<script>
  const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
  
  const w = 500;
  const h = 100;
  
  const svg = d3.select("body")
                // Add your code below this line
                
                .append("svg")
                .attr("width", w)
                .attr("height", h)
                
                // Add your code above this line
</script>
</body>
```

**Comment by HKuz** [comment]
@becausealice2 - I think this is a great suggestion, it removes any ambiguity from the instructions. As you noted, we can rephrase the instructions to say something like:

"Add an `svg` node to the `body` using `append()`. Give it a `width` attribute set to the `w` constant and a `height` attribute set to the `h` constant using the `attr()` method for each..."

As the person that opened the issue, would you like to make this fix? Let us know here either way. No worries if not, we'll open it up to other contributors. Thanks for QA'ing the new challenges!

**Comment by becausealice2** [comment]
D3 is basically the only thing I can contribute to here, so I had to take the opportunity while I could ;)

I'll go ahead and make the fix :)

**Comment by HKuz** [comment]
Great, thanks so much @becausealice2 🎉 👍 ! If you haven't contributed to fCC before, check out the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) to get set up, and ask any questions in the [Contributor's chat room](https://gitter.im/FreeCodeCamp/Contributors). And having folks work through challenges in any area and providing feedback is a huge help, so cheers for going through beta 😄
