### ISSUE TITLE
[beta][UX] notification-bar color choice suggestion

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12852]
The tooltip or small modal window that appears with each new challenge **and** with each test run, has a` background:black` and `color:white`

Please consider changing to ` background:yellow` and `color:black`

**Comment by no-stack-dub-sack** [comment]
@tommygebru hmmm... I was about to say that I think everything looks fine as is, but I tried it out, and I don't think it's an altogether bad suggestion. Looks nice in both modes and I think is a bit more visible:

![image](https://cloud.githubusercontent.com/assets/18563015/22320649/190ec112-e35c-11e6-9959-d75407cbc6f1.png)

![image](https://cloud.githubusercontent.com/assets/18563015/22320670/4b417756-e35c-11e6-8c1d-e590cf8b8f7d.png)

**Comment by tommygebru** [comment]
@no-stack-dub-sack 
Actually I misspoke, the color should represent Freecodecamp to the fullest and should be a recommended color 

https://www.freecodecamp.com/design-style-guide/

I think this is a great choice `#FF9C2A` with a text of  `#333333`

**Comment by no-stack-dub-sack** [comment]
@tommygebru I actually consulted the styleguide before testing this out. and both are recommended colors!

**Comment by dhcodes** [comment]
Should this change be made across the site or as a part of a 'high-contrast' mode as discussed in: https://github.com/freeCodeCamp/freeCodeCamp/issues/8845 ?

**Comment by no-stack-dub-sack** [comment]
@dhcodes Not sure, what do you think about the current white on black? I mean, it's pretty visible, but the yellow/black does stand out a bit more

**Comment by systimotic** [comment]
Can't get a lot more contrast than black and white! 😛 

I like the yellow background for the attention grabbing, but I'm afraid it may be too much for the bigger toasts, like the reset code one.

**Comment by no-stack-dub-sack** [comment]
@systimotic I agree that for now we should just leave this as is. Seems minor to me and I think the current design works ok.

**Comment by systimotic** [comment]
@tommygebru What do you think?

**Comment by tommygebru** [comment]
I would still prefer a Primary color over Secondary for the tooltip when considering a choice that will compliment the Night Mode theme. 

https://github.com/freeCodeCamp/freeCodeCamp/issues/12953

Keep in mind my example for a Night Mode refresh is to remove Freecodecamp from a monotone state and preserve a dark theme that is more engaging like the Freecodecamp Community.

![screen shot 2017-01-30 at 1 07 52 pm](https://cloud.githubusercontent.com/assets/7606025/22441716/6d8f7012-e6ed-11e6-9533-72ab021bb286.png)
