### ISSUE TITLE
This appears to meet all of the guidelines, but fails the first test

### ISSUE THREAD

**Issue by strongdan** [freeCodeCamp/freeCodeCamp#12863]
Challenge [escaping-literal-quotes-in-strings](http://beta.freecodecamp.com/en/challenges/basic-javascript/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 8872.76.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.105 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js




var myStr = "I am a \"double quoted\" string inside \"double quotes\".";

```

**Comment by tommygebru** [comment]
[closed][blocked] This is actually an incorrect solution...

**Comment by ajain17** [comment]
@strongdan  The code you have posted here seems to be working for me. What issue are you having?

**Comment by strongdan** [comment]
@ajain17 This is working now for me too. I'm not sure what the problem was.

**Comment by rmdawson71** [comment]
I am also experiencing the same issue.
![image](https://cloud.githubusercontent.com/assets/5313213/22447795/7a472b44-e709-11e6-8288-4f3480859f3a.png)

**Comment by ichthub** [comment]
The same problem for me. My code is code is correct but does not want to pass
![ucscreenshot20170208080912](https://cloud.githubusercontent.com/assets/18748390/22728468/fac377a0-edd5-11e6-9e57-83b9689ac98d.png)

![ucscreenshot20170208081243](https://cloud.githubusercontent.com/assets/18748390/22728549/6b3e9212-edd6-11e6-8823-d6ffc3b7a7de.png)

**Comment by ajain17** [comment]
@ichthub It works for me. Your code is incorrect. It doesn't generate expected output. Check it again, it will work.

**Comment by pamela113** [comment]
I'm having the same issue.  My code is the exact same:

var myStr = "I am a \"double quoted\"string inside\"double quotes\"."; 

am I missing something? Thanks!

**Comment by ajain17** [comment]
@pamela113 Your code is incorrect. It doesn't generate expected output. Check it again, it will work.

**Comment by pamela113** [comment]
@ajain17 I see what you are talking about.  Thanks!

**Comment by ogora** [comment]
I found that while I had written the code correctly, the spacing  between words and punctuation marks should be accurate to the dot. if Spacing is off a bit , I had problems.

Var myStr = "I am a \"double quoted \" string inside\"double quotes \".";
