### ISSUE TITLE
[beta] the second flexbox challenge also has an issue

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12867]
I just completed the second flexbox challenge

Css Flexbox: Adding Flex Superpowers to the Tweet Embed
http://beta.freecodecamp.com/en/challenges/css-flexbox/adding-flex-superpowers-to-the-tweet-embed

However it doesnt make any sense as to what the lesson is exactly...

I guess what I am saying is it should have been a different or simple demonstration on the phone

**Comment by HKuz** [comment]
@tommygebru - I think the original point of this challenge was partly to introduce the 'real world' tweet embed example (which has a lot of code), and partly to apply the `display: flex` concept introduced in the prior 'box' challenge. (You probably noticed the alternating pattern of these first challenges.) The change campers make here would be more obvious if the code loaded with the challenge, and updated when they added their changes. Right now, the mobile phone output only loads when the tests are run (this is a known issue tracked over in #12807). 

If you reset your code, run tests (to show the initial view of the tweet embed), make changes, and run tests again, it's a bit more clear what's happening. It's not an ideal workflow, but hopefully the code loading issue is addressed soon 👍
