### ISSUE TITLE
[beta] Flexbox challenge 4 issue

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12869]
Css Flexbox: Applying the Flex-direction Property to Create Rows in the Tweet Embed
http://beta.freecodecamp.com/en/challenges/css-flexbox/applying-the-flexdirection-property-to-create-rows-in-the-tweet-embed

After progressing from the previous challenge page, the Visual Display (phone) does not wipe away the previous challenges solution on the phone.

![screen shot 2017-01-25 at 10 13 57 pm](https://cloud.githubusercontent.com/assets/7606025/22321682/a3e3abb0-e34b-11e6-87e3-03fc5e9ccbe8.png)

**Comment by tommygebru** [comment]
Ok after glancing over the map, i understand that there is a pattern between, a lesson with colored divs (red & blue) and a tweet embed of Ossia

I am going to assume that the issue I presented in this challenge is also repeating, and it might actually be intentional

**Comment by no-stack-dub-sack** [comment]
@tommygebru Yeah, I noticed this too, but I think the repetition was intentional (see first challenge instructions) - if this was the only issue with this one, I think it's safe to close this.

**Comment by tommygebru** [comment]
LOL if only I could @no-stack-dub-sack thanks for confirming
