### ISSUE TITLE
[beta] Clicking to next challenge does not update display

### ISSUE THREAD

**Issue by wildlifehexagon** [freeCodeCamp/freeCodeCamp#12872]
#### Challenge Name

Noticing this in the Applied Visual Design track, probably elsewhere too

#### Issue Description

When you complete a challenge, the next one loads but the right-hand display remains the same. It's not possible to see the initial display of the new challenge unless you manually hit "run code." This isn't an issue when subsequent challenges build off of each other, but it's noticeable in the Applied Visual Design track since most of the challenges are quite different from each other.

#### Browser Information

* Browser Name, Version: Version 55.0.2883.87 m (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

**Comment by tommygebru** [comment]
Please try and share a screenshot accompanied with your issue

**Comment by Ramona-Eikelenboom** [comment]
Same issue here for all challenges in the Applied visual design track and the Applied accessibility track (probably also in other tracks). 

The right-hand display doesn't update when I complete a challenge and go to the next challenge. The display continues to show the output from the previous challenge. The correct display only shows after I click the reset button or the run tests button. 

![error](https://cloud.githubusercontent.com/assets/20818277/22325013/883abfdc-e3ac-11e6-90d7-6618496bda99.png)

**Comment by no-stack-dub-sack** [comment]
closing this as duplicate - please see #12807
