### ISSUE TITLE
[beta] Link to LinkedIn account doesn't work

### ISSUE THREAD

**Issue by soulchainer** [freeCodeCamp/freeCodeCamp#12879]
#### Issue Description

Trying to link to the user LinkedIn account doesn't work, it returns an error page (see below, in **Screenshot**). Plus, when hitting back in the browser, the button text is now «Remove my LinkedIn from my portfolio» and you can't also remove it, because you hit the same error everytime.

#### Browser Information

* Browser Name, Version: Firefox Developer Edition, 52.0a2
* Operating System: Arch Linux
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![2017-01-26-135326_1920x1080_scrot](https://cloud.githubusercontent.com/assets/169524/22333019/223314d2-e3d4-11e6-8394-b4106b23428a.png)

**Comment by raisedadead** [comment]
Thanks for reporting.
/cc @BerkeleyTrue

**Comment by flippynipz** [comment]
If this is still open, can I get assigned it?
