### ISSUE TITLE
[beta] Progress and brownie points reset on first login. Is it normal? Temporal?

### ISSUE THREAD

**Issue by soulchainer** [freeCodeCamp/freeCodeCamp#12877]
#### Issue Description
When you log into the beta, the progress and brownie points are all gone, reset. Shouldn't it be preserved? Or it will be added later or what? Because I believe that's kinda important.
And, if not, the new profile button **Reset all of my progress and brownie points** it's kinda funny :þ.

#### Browser Information
I don't believe this could be related with the browser, but here the details:

* Browser Name, Version: Firefox Developer Edition, 52.0a2
* Operating System: Arch Linux
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![2017-01-26-141618_1920x1080_scrot](https://cloud.githubusercontent.com/assets/169524/22332637/2a198584-e3d2-11e6-8299-bc5c91d14cab.png)

**Comment by Greenheart** [comment]
@soulchainer https://beta.freecodecamp.com runs on a different server, with a different database that gets reset once in a while. This exists to make it easier to test the site.

If your profile still exists at https://freecodecamp.com, there should be nothing to worry about.

Thanks for your help with testing the new curriculum! :smile: :sparkles:

**Comment by soulchainer** [comment]
I guessed that would be the case, but you know: it's a beta, isn't stated anywhere (that I could see), so issue to get a confirmation (and, if not the case, warn about it). Thanks for the info and the kind reply, @Greenheart :D. Closing this then ñ_ñ.

**Comment by Greenheart** [comment]
@soulchainer No problem, happy coding! :relaxed: :man_technologist:
