### ISSUE TITLE
"Size Your Images" challenge missing critical instruction

### ISSUE THREAD

**Issue by zeyergit** [freeCodeCamp/freeCodeCamp#12874]
Hi.
I could not find instructions on how to add the "smaller-image" class to an image link.
I understood the challenge but there is no actual example of how to add that to <img src...
In the end I asked someone in the chatroom and got the following: <img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat" but I never would have known to put "class" next to "img" and move "src" on its own.

Challenge [Size your Images](https://www.freecodecamp.com/challenges/size-your-images#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D%22smaller-image%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }
  .smaller-image {
    width: 100px;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

**<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">**

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by OFFLlNE** [comment]
@zeyergit Thank you for reporting this issue.

I see MANY people come everyday with the same problem, that they do not know that they need to apply that created class to their image element. 
If people would analyze what test is failing they should see that you need to use that class on image
`Your img element should have the class smaller-image.`

But I would agree, that extra line in the instructions to say: `you need to apply created class to your existing image element` would help out a little bit.

**Comment by zeyergit** [comment]
Hi Lauri,
I don’t think the issue is just telling people that the “img element” should have “class smaller-image”
The issue is that people don’t know HOW to break up the traditional “img src…” tag and modify it to accommodate the class.
They need to see an example. There’s no other way of knowing how to do this.

**Comment by ajain17** [comment]
I don't think we should add "you need to apply created class to your existing image element". That coupled with existing instructions is like handing over the solution directly. We may change`Your img element should have the class smaller-image.` to `The img element should have..` because your makes it seem like you should be creating one.  Another change I'd suggest is to change `Create a class called smaller-image` to `Add a class called smaller-image to the image tag`.

What do others suggest? I can work on this if needed.

**Comment by zeyergit** [comment]
Hi. I’m new to FCC and don’t want to overthink this but I just want to make sure I’m being clear.
What I’m saying is that I did not know how to break up an img ref and add this other element.
<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

In my opinion, the simplest way to make sure students know how to do this would be to show an example in the left margin just like you do for so many other things.

Really enjoying this program.
Thank you.

**Comment by jdubbz1113** [comment]
I've just completed this challenge. Although I had no issue I agree with @ajain17 for those that do.     
  You wouldn't want to just give the answer away but maybe make it more clear on what you are supposed to be doing.

**Comment by NealSavage** [comment]
Yeah, I agree with the person. I could tell that I needed to get the class in, but was confused because I already had the SRC in there. I managed to get it, but only after spending 15 minutes trying various ways and then finally finding this thread and implementing what they did. It should really tell us how to break it apart so that I can have both an SRC and a class because I had no clue.
