### ISSUE TITLE
Wrong Behavior with "Specify How Fonts Should Degrade"

### ISSUE THREAD

**Issue by srir4m** [freeCodeCamp/freeCodeCamp#12878]
Challenge Link : 
[click](https://www.freecodecamp.com/challenges/specify-how-fonts-should-degrade#?solution=%3C!--%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A--%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A)

Issue Description : 

The problem is whenever i comment out the link....the output still uses the Lobster font and not degrading to the Monospace font

Browser Information : 
* Browser Name, Version: Firefox v50.1.0
* Operating System: Antergos Linux
* Mobile, Desktop, or Tablet: Desktop

 Screenshot : 
![screenshot_20170126_190135](https://cloud.githubusercontent.com/assets/20870625/22333023/e061a1ce-e3f9-11e6-9532-0c93656fd3ad.png)

**Comment by dhcodes** [comment]
@srir4m does the challenge still pass? The reason I ask is that on beta this challenge says "if you have the Lobster font installed on your computer, the font may not degrade". Do you have Lobster installed in your system fonts?

**Comment by raisedadead** [comment]
Please  check the above comment and confirm.

**Comment by TangZiff** [comment]
Similar problem and here is the confirmation: I can see 'Lobster' font installed, by checking Win10 -> Setting --> Font.
