### ISSUE TITLE
Unable to remove twitter account

### ISSUE THREAD

**Issue by 0xcrypto** [freeCodeCamp/freeCodeCamp#12881]
#### Issue Description
I mistakenly linked wrong twitter account. Now I want to remove that account and link my twitter account. But there is no option to do so. Even after I have revoked access from twitter, there is no effect.

**Comment by raisedadead** [comment]
@0xcrypto here is forum post that would help
https://forum.freecodecamp.com/t/how-to-delete-twitter-account-from-free-code-camp/14991
