### ISSUE TITLE
Passing Values to Functions with Arguments

### ISSUE THREAD

**Issue by tgitari** [freeCodeCamp/freeCodeCamp#12884]
![functionwithargs](https://cloud.githubusercontent.com/assets/23182966/22345860/6e4c2140-e3c7-11e6-9151-e352427b87dd.PNG)
Challenge [Passing Values to Functions with Arguments](https://www.freecodecamp.com/challenges/passing-values-to-functions-with-arguments#?solution=%0A%2F%2F%20Example%0Afunction%20ourFunctionWithArgs(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunctionWithArgs(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afunction%20functionWithArgs(a%2C%20b)%20%7B%0A%20%20console.log(1%20%2B%202)%3B%0A%7D%0AmyfunctionWithArgs(1%2C%202)%3B%20%2F%2F%20Outputs%203%0A%0Afunction%20functionWithArgs(b%2C%20c)%20%7B%0A%20%20console.log(7%20%2B%209)%3B%0A%7D%0AmyfunctionWithArgs(7%2C%209)%3B%20%2F%2F%20Outputs%2016%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; MS-RTC LM 8; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.

function functionWithArgs(a, b) {
  console.log(1 + 2);
}
myfunctionWithArgs(1, 2); // Outputs 3

function functionWithArgs(b, c) {
  console.log(7 + 9);
}
myfunctionWithArgs(7, 9); // Outputs 16

```

**Comment by tgitari** [comment]
Could someone please tell me what it is that I am missing here.

**Comment by tgitari** [comment]
No one is helping me on the chat, that's why I posted here.

**Comment by tgitari** [comment]
I keep getting "ReferenceError: 'myfunctionWithArgs' is undefined"

**Comment by tgitari** [comment]
Problem solved.

**Comment by Greenheart** [comment]
@tgitari Glad to hear that :blush:

Next time, please use the chatrooms (which you did), or [the forum](https://forum.freecodecamp.com) to get help. These issues are only for reporting bugs or discussing improvements.

**Comment by tgitari** [comment]
@Greenheart I never get help from the chatroom anymore everytime I post something.

**Comment by Greenheart** [comment]
Do you post in the main chatroom? It's pretty crowded these days so it's hard to get noticed there.

Have you tried using the "Help"-button on challenge-pages? It will redirect you to the help chat room for the section you're currently on.

Otherwise, the [forum](https://forum.freecodecamp.com) or [our subreddit](https://www.reddit.com/r/FreeCodeCamp/) offer a more relaxed environment for getting help, since posts will be more visible.

**Comment by tgitari** [comment]
Okay then that is probably why I don't get answers.​

Titus M Gitari
(913) 284-8915 Cell
(913) 484-1486 Home


*Strengths Finder Top 5 Themes:*

*Input* Futuristic * Includer * Developer * Restorative *
