### ISSUE TITLE
Escape Sequences in Strings Section Error

### ISSUE THREAD

**Issue by renevilla** [freeCodeCamp/freeCodeCamp#12893]
#### Challenge Name
Escape Sequences in Strings Section
https://www.freecodecamp.com/challenges/escape-sequences-in-strings

#### Issue Description
The error is with the solution. the assignment is asking to give this soultion: 
FirstLine
\SecondLine\
ThirdLine

the accepted solution for the escape sequence is incorrect because it accepts this solution:
var myStr = "FirstLine\n\\SecondLine\\\rThirdLine"; 
console.log(myStr);

versus accepting this one: 
var myStr = "FirstLine\n\\SecondLine\\\n\rThirdLine"; 
console.log(myStr);

which actually prints out correctly when you do console.log(myStr);

im learning, but im pretty sure this is a bug. thanks, i hope i submitted the ticket correctly!

#### Browser Information

Google Chrome, Version 55.0.2883.95
Macbook Pro / macOS Sierra
Laptop 

#### Your Code

```js
var myStr = "FirstLine\n\\SecondLine\\\n\rThirdLine"; 
console.log(myStr);
```
#### Screenshot
<img width="331" alt="screen shot 2017-01-26 at 3 31 30 pm" src="https://cloud.githubusercontent.com/assets/3697056/22354949/959286da-e3dc-11e6-89f9-5743d58708b7.png">

**Comment by ajain17** [comment]
It does not accept this solution `var myStr = "FirstLine\n\SecondLine\\rThirdLine";`. Also, your other solution `var myStr = "FirstLine\n\SecondLine\\n\rThirdLine";` is also incorrect.

Please check the desired output and your code. It doesn't match at all.

**Comment by no-stack-dub-sack** [comment]
@renevilla yeah, there is no bug here, but the challenge instructions are a little confusing. Have you been able to solve it yet? At the very least, you have successfully brought a typo to light that needs to be fixed!

![image](https://cloud.githubusercontent.com/assets/18563015/22361568/0b8c1544-e429-11e6-9671-12e93bde2d2c.png)

**Comment by renevilla** [comment]
Thank you for the responses, i was confused by the instructions of the exercise. Thank you for helping, and yes the typo is cut off. thanks for the help!

**Comment by ajain17** [comment]
@no-stack-dub-sack  I dont see any typo. 
<img width="425" alt="screen shot 2017-01-27 at 9 39 49 am" src="https://cloud.githubusercontent.com/assets/5581487/22374534/914931a8-e474-11e6-926b-ce3bb9801dbc.png">

**Comment by no-stack-dub-sack** [comment]
@ajain17 interesting, I didn't verify it in the code, but I refreshed the page of bunch of times and still got what my screenshot shows in m above post.
