### ISSUE TITLE
[beta] Clicking challenges links in the map page...

### ISSUE THREAD

**Issue by marvellousdesign** [freeCodeCamp/freeCodeCamp#12898]
#### Issue Description
So when you scroll anywhere in the [map](http://beta.freecodecamp.com/en/map) besides the top, and click a link to the challenges. The position of the challenges page are focus on bottom rather than the top, so part of the content is covered when you first go to the challenges.
Chrome is just barely on the edge of the content.
The positions also depends if you have a bookmark bar/addon bar/status bar, etc.
Not sure if it's something to do with bootstrap..
#### Browser Information
* Browser Name, Version: Firefox 51.0 & Chrome 56.0.2924.76
* Operating System: OSX 9.5

#### Screenshot (Firefox)

![screen shot 2017-01-26 at 5 13 50 pm](https://cloud.githubusercontent.com/assets/24817921/22357388/807ff088-e3ec-11e6-848e-0bff10e5cb36.png)

#### Screenshot (Chrome)

![screen shot 2017-01-26 at 7 43 42 pm](https://cloud.githubusercontent.com/assets/24817921/22359854/cbef06ea-e3ff-11e6-8c27-921d948a8c47.png)

**Comment by ajain17** [comment]
I can confirm this is a valid issue. Needs to be fixed.

**Comment by no-stack-dub-sack** [comment]
@marvellousdesign Interesting, I'm unable to reproduce this on Chrome / OSX 10.11.6

@freeCodeCamp/moderators can anyone else confirm this as well?

**Comment by raisedadead** [comment]
@marvellousdesign thanks. 

And I must admit sheepishly that this is a known issue from the last time we pushed react.
I can't find the old issue no, or even if there was one earlier reported.

But here is some insight:

1. The pages that use our react infrastructure are generated and rendered on the client side.
2. This means they are within the same container as any react page, and we just simply update the DOM, which renders the new content.
3. This container sadly is currently taking the scroll from the whole page. 
4. Hence think of this as a behaviour where you have scrolled somewhere in the page, that would be to some point in the map, and then replace it with the challenge's view.
5. The browser is fooled, and technically this being the same page it doesn't auto scroll.
6. A fix would be to subscribe to the loading finished state and reset the scroll.

You will notice that this wont happen with the static pages.

**Comment by QuincyLarson** [comment]
@raisedadead thanks for the analysis. Are you able to reproduce this issue? Do you have any ideas how we might go about fixing this?

**Comment by raisedadead** [comment]
@QuincyLarson yes, I can reproduce the issue, as for the fix, I am unfortunately not the expert. Maybe @BerkeleyTrue , @Bouncey and others are more suited to guide on a fix.

**Comment by BerkeleyTrue** [comment]
This looks to be a css issue, maybe? 

@QuincyLarson We've talk about making the navbar non-sticky. That might fix this issue (if it is indeed a css issue)

**Comment by Bouncey** [comment]
CSS gets my vote too. Sticky navbars need something like 60px of padding-top on the body to move content from under it.

**Comment by texas2010** [comment]
yeah, I think navbar non-sticky is good idea.

**Comment by QuincyLarson** [comment]
A non-sticky navbar would not affect desktop users significantly, and would make the mobile experience much better imho. I'm for trying out a non-sticky navbar.

**Comment by nesterone** [comment]
I also able to reproduce it, however looks like I didn't got the idea with non-sticky navbar. Is it about moving navbar out of scrollable viewport (content of the challenge) ?
