### ISSUE TITLE
[Beta]Word Blanks

### ISSUE THREAD

**Issue by marvellousdesign** [freeCodeCamp/freeCodeCamp#12895]
Challenge [word-blanks](http://beta.freecodecamp.com/en/challenges/basic-javascript/word-blanks) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:51.0) Gecko/20100101 Firefox/51.0</code>.

My solution doesn't pass some how.

```js
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
 var result = "";
 // Your code below this line
 
result = "The " + myAdjective + myNoun + " looked around " + myAdverb + " then " + myVerb + " into the house.";
 // Your code above this line
 return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```

![screen shot 2017-01-26 at 5 21 27 pm](https://cloud.githubusercontent.com/assets/24817921/22357307/efc5bf0a-e3eb-11e6-9a96-f7c6cef6776a.png)

**Comment by erictleung** [comment]
@marvellousdesign thanks for the issue but your code is incorrect.

> Include additional strings and spaces (which will not change) in between the provided variables to make a complete sentence.

Happy coding!

**Comment by rmdawson71** [comment]
This is the 4th beta challenge with the same issue.  I come into the challenge after passing the previous one.  I enter my code and click submit and then can not pass the tests.  I exit the challenge and the come back in using the Map and then click Submit without changing my code at all and then it passes and allows me to go to the next challenge.  I finished the all the javascript (basic,intermediate, advanced) on the FCC, but I thought I would go through the Beta to see what it had different, but so far the challenges are almost identical, but will not pass without exiting and coming back in via the Map to submit.

CLICKING SUBMIT WHEN COMING FROM THE PREVIOUS SOLVED CHALLENGE
![image](https://cloud.githubusercontent.com/assets/5313213/22448411/0f33d5fa-e70e-11e6-8551-a941688f9380.png)

AFTER COMING BACK IN FROM MAP
![image](https://cloud.githubusercontent.com/assets/5313213/22448431/3650e8a8-e70e-11e6-8862-cf966669f05c.png)

**Comment by w96k** [comment]
@rmdawson71 Ye, it helped. Need to fix this bug.
