### ISSUE TITLE
Remove all empty translations

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#12899]
Some of the challenges in the seed files have translations with no text. These will cause errors when campers have selected these languages. These look like:

```
      "translations": {
        "de": {
          "description": [],
          "title": ""
        }
      }
```

In this case, we would need to delete
```
        "de": {
          "description": [],
          "title": ""
        }
```
We need to go through and delete all of these empty translations from seed files, and leave the empty `"translation": {}`

**Comment by tmashuang** [comment]
@QuincyLarson I would like to take on this task.

**Comment by envy7** [comment]
Can I help this seems easy, I'm a beginner.

**Comment by tmashuang** [comment]
@envy7 Sure, be sure to follow the [CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md). Happy coding.

**Comment by envy7** [comment]
@tmashuang thanks a lot, I'll get to work on it right away.

**Comment by envy7** [comment]
@QuincyLarson there are a lot of seed files should I do all the changes in a single commit, or in multiple commits and then squash them? Does it make a difference.

**Comment by raisedadead** [comment]
@envy7 you can do it in anyway as it suits you, but make sure when you have opened the pull request it has one commit. 

Also, refer the contributing guide, most things have been answered there to guide you!

Thanks and happy fixing!
