### ISSUE TITLE
[beta] ES6: Arrow Functions. Tests pass with any input.

### ISSUE THREAD

**Issue by BrendanSweeny** [freeCodeCamp/freeCodeCamp#12902]
Challenge [arrow-functions](http://beta.freecodecamp.com/en/challenges/es6/arrow-functions) passes tests with any or no input.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.

It seems that the tests will pass without changing any code (as pictured). All tests passed with a blank code editor and when gibberish was entered into the code editor as well. I've tried a hard refresh and incognito and the problem persists.

![arrow-functions](https://cloud.githubusercontent.com/assets/3643243/22361549/1813f8a6-e418-11e6-9905-49a8c261c2cb.jpg)

**Comment by Greenheart** [comment]
I can confirm this with 
* <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36</code>
* <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0</code>.

Looking into the seed-files, I found that the tests just were placeholders.
```json
"tests": [
  "// Test user did replace var keyword",
  "// Test magic is const",
   "// Test magic is a function",
  "// Test magic() returns the correct date",
  "// Test function keyword was not used",
  "// Test arrow => was used"
]
```

**Comment by Greenheart** [comment]
I'm working on tests for this challenge.

**Comment by HKuz** [comment]
@BrendanSweeny - thanks for raising this issue, there are quite a few missing/placeholder tests in this section that need to be written. We've consolidated the list over in #12698 if you're interested in working on any of these 😄 

@Greenheart - can you coordinate with @robbawebba for the arrow function tests? He was working on cleaning those challenges up and I saw the discussion in the Contributors room about some problems running the tests. Maybe you two could tackle that together?

**Comment by Greenheart** [comment]
@HKuz Thanks for the heads up! I didn't notice the comments of that issue.

@robbawebba You can fix this if you want. I can find something else to work on :smile:

**Comment by BrendanSweeny** [comment]
Thanks for confirming the issue, @Greenheart, and for consolidating them all, @HKuz. I missed that thread. Let me get my local clone ready and perhaps I can help with some of those issues this weekend. First-timer here.

**Comment by HKuz** [comment]
Sounds great @BrendanSweeny - if you'd like to help re-title and re-format some of the challenges in the ES6 section, it would be most welcome! Just post over in that issue what you're working on so others know 👍

**Comment by systimotic** [comment]
I'm closing this in favor of the aforementioned #12698. This issue hasn't been resolved, but we'll handle fixing this over there. Your contributions to this are still most welcome!

Happy coding!
