### ISSUE TITLE
Caesars Cipher Unclear Instructions

### ISSUE THREAD

**Issue by mh453Uol** [freeCodeCamp/freeCodeCamp#12907]
Challenge [Caesars Cipher](https://www.freecodecamp.com/challenges/caesars-cipher) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function isValid(str){
  var regex = /[.,\/?#!$%\^&\*;:{}=\-_`~()\s]/;
  return !regex.test(str);
}

function rot13(str) { // LBH QVQ VG!
  var to_return = "";

  while(true){
    if(str.length === 0) { return to_return; }
    var head = str[0];

    if(isValid(head)){
      var value = decryption(head);
      to_return += value;
    } else {
      to_return += head;
    }
   //Remove head to shorten string
   str = str.substring(1);
  }
  return str;
}

function decryption(str){
  var ROT13 = 13;
  //Get Ascii code for str
  var ascii = str.charCodeAt(0) - ROT13;
  //Get Ascii charectar
  var converted = String.fromCharCode(ascii);

  if(isDecrytionValid(converted)){
    return converted;
  } else {
    //+13 to decrypt since encoding was not using -13 
    ascii = str.charCodeAt(0) + ROT13;
    return String.fromCharCode(ascii);
  }
}

function isDecrytionValid(str){
  //Decryption is only valid if its in alphabet not numbers
  var regex = /[A-Za-z]+/g;
  return regex.test(str);
}
// Change the inputs below to test
rot13("SERR PBQR PNZC");

```

I have passed this challenge however the instructions are not correct. Write a function which takes a **ROT13** encoded string as input and returns a decoded string.

Since we are working with **ROT13 encoded string** we need to get the ascii and - 13. 

So using the test cases : 
rot13("SERR PBQR PNZC") should decode to "FREE CODE CAMP"
So 
S -> F (-13)
E -> 8 (-13) When we -13 from the ascii value we get 8. However it seems this is not a encoded string so we + 13. However it says the string are encoded with ROT13. 

Maybe instructions saying some string might not be encoded. 
 
Thanks

**Comment by raisedadead** [comment]
The instructions do state the below:
> All letters will be uppercase. Do not transform any non-alphabetic character (i.e. spaces, punctuation), but do pass them on.

So the effective range is not what you are doing in your code above.

Please reach out to the [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript), for further assistance.
