### ISSUE TITLE
Local Scope and Functions

### ISSUE THREAD

**Issue by Quentin-jeon** [freeCodeCamp/freeCodeCamp#12900]
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=%0Afunction%20myLocalScope()%20%7B%0A%20%20%20%0A%20%2F%2F'usestrict'%0A%20%20var%20myVar%3B%0A%20%20%0A%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0A%0AmyLocalScope()%3B%0A%0A%2F%2F%20Run%20and%20check%20the%20console%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myLocalScope%0Aconsole.log(myVar)%3B%0A%0A%2F%2F%20Now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function myLocalScope() {
   
 //'usestrict'
  var myVar;
  
  
  console.log(myVar);
}

myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope
console.log(myVar);

// Now remove the console log line to pass the test


```

**Comment by raisedadead** [comment]
Please provide more information of the issue that you are facing? 

The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
