### ISSUE TITLE
Feature Request: "Favorites" section in Camper News

### ISSUE THREAD

**Issue by bugron** [FreeCodeCamp/FreeCodeCamp#1290]
It would be nice to create a "Favorites" section for news which are marked by the user somehow (with a star for example) or upvoted.

**Comment by carl-parrish** [comment]
I would upvote this if I could. Also what happened to the "Hot" section for Camper News?

**Comment by BerkeleyTrue** [comment]
We won't be adding this. Bookmarks work infinitely better then anything we could implement. We removed the Hot section because it was underutilized.

Happy Coding!
