### ISSUE TITLE
Border around texts

### ISSUE THREAD

**Issue by KenzoM** [freeCodeCamp/freeCodeCamp#12901]
#### Challenge Name
ES6: Arrow functions with higher order functions

#### Issue Description
Not sure if it is intended, but I see borders around the texts in the description for the challenge, as shown in the screenshot I've posted.

It looks like it is caused when using the `template literals`.
 
![screen shot 2017-01-26 at 9 25 19 pm](https://cloud.githubusercontent.com/assets/10217112/22361457/aa77f472-e40e-11e6-89e5-20be0873bb34.png)

**Comment by systimotic** [comment]
Thanks for reporting @KenzoM!

For some reason it's being wrapped in an image tag 😄 😕.
Happens in both Firefox and Chrome, but it's most visible in Chrome.

**Comment by HKuz** [comment]
Hi @KenzoM - thanks for noticing this! Pull request #12963 re-formatted all the text in this challenge, and the weird boxes are gone. (I think the `<img>` tags @systimotic found were supposed to be part of the example, not actually in the code, and they weren't escaped properly). I'm going to close this issue as resolved on `staging`, and it should be up on the Beta site in the next few days. Thanks for your help with QA on the new challenges! 👍 🎉
