### ISSUE TITLE
[beta] ES6: Export: One of Import's siblings - Tests not passing

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#12913]
Challenge [export-one-of-imports-siblings](http://beta.freecodecamp.com/en/challenges/es6/export-one-of-imports-siblings) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36</code>.

```js
export const foo = "bar";
export const boo = 'far';
```

I'm unable to make the tests pass for this challenge, even though the code is correct.

The strange thing is that the tests seem to work when `eval()`ed in a normal browser console.
![failing_regex](https://cloud.githubusercontent.com/assets/6125097/22370891/244b33ce-e494-11e6-9865-20af23ad011f.png)
However, they don't work in the freeCodeCamp environment.

I initially assumed this was a regex error but since they work in the console, I'm not sure anymore.

Another thing worth noting is that these tests have the same problem as i pointed out in [#12739 (comment)](https://github.com/freeCodeCamp/freeCodeCamp/issues/12739#issuecomment-275650578)

**Comment by Greenheart** [comment]
I am pretty sure this issue is caused by our transpilation of the code from ES6 to ES5. Since the code we're running tests against doesn't have the ES6 code, they can never pass for the regex-tests checking for ES6 syntax.

**Comment by robbawebba** [comment]
Do we know if there some sort of variable besides `code` that's accessible during testing and has the pre-transpiled code to test against in the ES6 challenges?

**Comment by Greenheart** [comment]
@robbawebba I peeked inside `fcc-test-frame`, the `iframe` context where tests are run on the challenge pages yesterday. I didn't find anything but I surely can have missed something.

I think we need @BerkeleyTrue's thoughts on this

**Comment by BerkeleyTrue** [comment]
While `export` is valid es.next syntax, it is currently unsupported by all browsers. The reason for this is that while the syntax has entered the spec, the actual importing of those files has not been defined yet. 

In order to teach the syntax we will need to encode those instances of syntax into something that is currently valid javascript (probably a coded comment) and then test for the existence of that comment.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (113/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60223 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx3T-0003U2-IM
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:59 -0400
Received: from o7.sgmail.github.com ([167.89.101.198]:55736)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx3P-0001tW-Gp
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:55 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=B2NisSP/X18wR6Svs2Q9nOoUV7Q=; b=QIDfI5fcKuVleUvo
	ff0AIrDUQExIOZONFjNur1r+HX4SCrNw6jjpXB/sAJEbEdiuyoGVzn/IIi+JAkDQ
	RUkyTv452JkWTv1YWb+fWq6g/jCwL2TEfsgcngBzsdNFi2/2+oWidnB3D7dMaOod
	4FVQty3rsLi5HQzB9N4XCgz5aok=
Received: by filter0936p1mdw1.sendgrid.net with SMTP id filter0936p1mdw1-1590-59AA0687-8
        2017-09-02 01:16:55.163401554 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0026p1mdw1.sendgrid.net (SG) with ESMTP id Y0mtFDauRyuj4_aWPniAPw
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:16:55.183 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:55 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (113/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f46.google.com ([209.85.218.46]:34444)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx4L-003ndU-2p
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:48:12 +0530
Received: by mail-oi0-f46.google.com with SMTP id w10so13900144oie.1
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:17:32 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=HSKbaDw2PlMxKy17B6UJ04aJr5CgvWXyKpcuwNXkWzA=;
        b=mzoks7AOLTK2aV46SqVKritBqFo4Y1gW8tMI25Yk/ATariEaW2CISl5hAcOksbsHqi
         5w0US+dkgqQOrIfiVmxJCVlN7FEV0Z10gpQU/q1pBUynIgy9w/Za+7t5SyLCFJemXltL
         CmXIMTZTd8u33MPU3btO4kQ/BbnxdBMI9TtTPMur81G3mNEax2RprPbJQRwBDXECiUAB
         lUyFCcnbxhyedkCqu6mqeYOIpTOTDP5hSG5c9Vlt/5CB4f67aeKyd4GjQi06oVRsi0wY
         jxoG6lBQ7exp0vWDEW/aSl6h9zAMFsGrvN27RMGv3gWJA5j62Q/M1YWBSieuptS90Lgg
         XTfg==
X-Gm-Message-State: AHPjjUijrT4SoH/gGvpyWdKl6lcOvAQtDI9KRXxQx0obos7ZiwL30Ah1
	iVEyIcRhseH7n9ZUHu9v0/a59XxU+W+bVLlOZIqkyQ==
X-Received: by 10.202.117.129 with SMTP id q123mr3396550oic.16.1504315030559;
        Fri, 01 Sep 2017 18:17:10 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1353135ofe;
        Fri, 1 Sep 2017 18:17:09 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb4CVb94OKj/xyj1u6s0nvmGxIeODi5gKAJlKR+Q7jQhSTt6BDFaXpwqswIdpqTigWvDs2tO
X-Received: by 10.107.20.67 with SMTP id 64mr132237iou.356.1504315029918;
        Fri, 01 Sep 2017 18:17:09 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504315029; cv=none;
        d=google.com; s=arc-20160816;
        b=oETYlhWgpvDvfiH4QTbfLSwjSAwAdG149RM5rolKoD0XqRuLCcA+LMn3PxnE7bGZg5
         Z7X2/Lgil2UljSQzfDxFZT8RNeyZqXmMecuXrmj9f4DmZKt4ZmttAVtKGdylN7jRg88G
         6Apyl5MLu7PsmYjxar4FmJHRnLy2vhfWTvt8WMeAr4mxokjUsDS9rAwMMGneogHvXKYO
         Oo1DkVRqg3bPD+oU+ahGptuWxXj6YJyacceerYczI2YUDaSuDpuTy2vzQWj9MGnwKir0
         leZ7JURs9i2W1PzVXuA7pJmn8d1M84BAqJDDCgabqgCbqQGA/qp+J9CI3jxl+8TIpK4Q
         3AbQ==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=HSKbaDw2PlMxKy17B6UJ04aJr5CgvWXyKpcuwNXkWzA=;
        b=NyN1M+h6isyNoM+/aOIyresib5+kXXeihle8TNIfDeQvXiVMr2LglBNFZ+wVDFK/KI
         e+hB0hl6YtwfYFJn57twGmlTbjEkTwmSrwFSdbFh+8ayJEvHg+yDs+byRMkLx1vtmtqW
         SoFXyBtJGKmajQ4MU/0lTKRTgR4MO2Xa4fMadCdhbW0fKIhR3BPQZK/2+VtTYnvdrh6p
         rI+smQH9pzuk4pxhPygf4ZTzCLH+s/KoX+MwBRzfJ66XPBTfGoL0ylyOZN9OejAaX0eV
         CYYIv9cob1oXP4vSmCe2tCC3mrFrTvitxxyYii3RPyqmsITJzrt4hloT00e8fXJCGJ8u
         RlFg==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=wltTMof8;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=j3OXFhav;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.99 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o4.sgmail.github.com (o4.sgmail.github.com. [192.254.112.99])
        by mx.google.com with ESMTPS id s13si1227741ite.153.2017.09.01.18.17.09
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:17:09 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.99 as permitted sender) client-ip=192.254.112.99;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=wltTMof8;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=j3OXFhav;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.99 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=A4rIUUD6xKdyINGsfe7s54mcLYI=; b=wltTMof8ShKEfobJ
	v5EHHPx0s/QVrxUOUeIiE0ceHnpCgs7qDrbYiQ1nFHKgCZZwtON/QYHuCZrXTOp1
	5HODJBuZJX2UmGW9GFj6Njv5tVWGqNzYCL3GMZyfG+9gdwhfvcLZYwfI/dc6abki
	ryUI+Jmi2DzzMTZ0fMRbNoghu+o=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=A4rIUUD6xKdyINGsfe7s54mcLYI=; b=j3OXFhavlfAPbjYQfg
	hstWFXASOlvDObu++TNfOcLpOPID+TjUOWjACeshWpKX+43Z52lSS38nX5pw3MrM
	9e0oaCe5C1G/pdEzWvHfep5n5FEmjd4I8UtuYDkNYPh4HO04IXvI24SBMrwX9GkO
	4ZNLccVtdtZFG6LW5w3F5mtLY=
Received: by filter0436p1mdw1.sendgrid.net with SMTP id filter0436p1mdw1-31421-59AA0695-13
        2017-09-02 01:17:09.621969128 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0037p1mdw1.sendgrid.net (SG) with ESMTP id zirv2oSwSDaS-2zZ1rL9OA
	for <pawan.ossindia@gmail.com>; Sat, 02 Sep 2017 01:17:09.580 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:17:09 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (124/100 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 24975 characters long; only the first
------ 5000 or so are included here.
Received: from mail-oi0-f48.google.com ([209.85.218.48]:33558)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx6m-003vgv-GH
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:50:45 +0530
Received: by mail-oi0-f48.google.com with SMTP id r203so13994632oih.0
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:20:03 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=iMqRKfv6NRsy1AZfXBKKQsKBRbxXf1PKatcXGvzadgs=;
        b=N9nBt0f/or5XdQTzzqyrhcFEvAvQjcH37j9mKAPL/sWD7JKUVpWIB0FdHNkzzguSHh
         hZF3VJs8rsFisqDMtOk0O9mlatyd8bHZ4yx2LmL8SxzSSw2jfBIv0LayKJuYLPs9DcWM
         g2bw8KwS3laYxv4F4al58LntOiwDs55DgDfBTfr+MVwLayZedqy5fYnDOk/q1MuCgfiB
         Eawjsyd6WALXFBaGwp1yvxvDjRrmLquD9oiTAnky8+qFB1TNqucx4frF0FBnuYQaMdOF
         qNSuh8UcjIJbdJ0uTaOb4XU2uZZ7XZOwhkJaunzCRad8TBDH9Z+Y0X+KvxOGg2Ur3tHU
         hoNg==
X-Gm-Message-State: AHPjjUiBnuym/Is+jg0TikiyFIaDv9sydO64ZTvmWYIVXHOgKFzkZ9P7
	KWrcRpEyHo1RpLiOYqIxt8mGwY5R1yMAi3xtEDqTwA==
X-Received: by 10.202.4.130 with SMTP id 124mr4149639oie.246.1504315181803;
        Fri, 01 Sep 2017 18:19:41 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1354520ofe;
        Fri, 1 Sep 2017 18:19:40 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb56e9t8GnTHlwBh2FIXLMRR46AwVKEpSpCm+3gVUCGxlMHM5LfVTcUNmpydGybhD5pTsMe4
X-Received: by 10.107.41.206 with SMTP id p197mr3451539iop.142.1504315180753;
        Fri, 01 Sep 2017 18:19:40 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504315180; cv=none;
        d=google.com; s=arc-20160816;
        b=AiBvvFMS01XTaI/pnjub1PJYSI5geTtOl5FLL2BmAXaX7kw/nfLFhIWC7ylyYaK6AE
         7TESZ9J1EABAzORsUeeMad1W0abQ8Eq9sLowdfzmyjWHd1LZJlGQ0r/Zp2z5g1Lwgxg6
         5c+kxSABGx83kT23a9QWZ8lL1CfUOXr2qL/56MPAL1yuwtAqhJy9EQomu7g0sHoano1d
         sKdPSvXaz1J5vM3Gno8jLWFsTUgK9KccbOEH5GOs8EiLh3AxCJt5LgGkIL4+9bbLsjt4
         2A8lNUx/aAdvXRd5e1DZ64okkDaLpfpw7G/vaG8O4eAfUddl4/B0EpHHwXGes2wbiz8G
         nDpg==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=iMqRKfv6NRsy1AZfXBKKQsKBRbxXf1PKatcXGvzadgs=;
        b=CSXjgBJmvYOElfprFOe2ivm2Jr9MrTR3cD+TtWbRe0VtuWWAtHf6UaesuFZESPuuB4
         Y955yQmAqDCiCceoGXCM0CvlDfqBX7+igadJrFfo8IG1+uhjmB20CwiWtC6eh1a25u6G
         f3PJNsPPqMKFFZptoJoUxx0N7xBqpbxdhM1TEWqvRWAOTtFNHJDCjiiTdOuZL1PMVKCR
         ip0rZIEQB//0n8/TxLZAgCbl2QC+8MaFoZwMj5uwDeXxBhS+GDkFDEkL2aKwC6Yk/qiw
         HioWoQC5NWlp3sjI7lIhykSAo4UQMlF8AvwRCRyckXOySuUnFCvaMBcR3Txdcqkb3rzH
         neXw==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=ezzvPOPZ;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=BrvT9AWK;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o3.sgmail.github.com (o3.sgmail.github.com. [192.254.112.98])
        by mx.google.com with ESMTPS id m66si1264785iom.130.2017.09.01.18.19.40
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:19:40 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) client-ip=192.254.112.98;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=ezzvPOPZ;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=BrvT9AWK;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=nH2lNHOv8EK7xG+LgBYZOEgkhHs=; b=ezzvPOPZ3MVmawUC
	LEzjEnNCKlh0/3rQtUdJpFONFHH0rSBhbhSkGZd0LErDSkfXq/wRv30z2v3WNRzm
	D176GsodCUBRf5dEZZlxsigyMkAQu/kIVZx0F9PQqejJQ+GFqrqcZlipDqkXKlBw
	ZDUZz8XZEOjEkiXxel0eIGuBB9w=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=nH2lNHOv8EK7xG+LgBYZOEgkhHs=; b=BrvT9AWK1TCbjayjIe
	CdD2drzrLKUvHgcBultCBQj3y7zoVazQarrgCEqD3Y6j9ZRVbF83xpWmwkfKAuDo
	OaTWMgR9Uy52i+pb+wfu9vWi2LR3WRRNl2pZbu2okhc33L5K60UXCBKbPC/xtw4H
	3HpHIJm6aj35adPkokF1Mhe3g=
Received: by filter0690p1mdw1.sendgrid.net with SMTP id filter0690p1mdw1-5746-59AA072C-12
        2017-09-02 01:19:40.20521245 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0036p1mdw1.sendgrid.net (SG) with ESMTP id hy87LfdETLyeM7omJqZA2Q
	for <pawan.ossindia@gmail.com>; Sat, 02 Sep 2017 01:19:40.101 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:19:40 +0000 (UTC)
