### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by atulsingh378** [freeCodeCamp/freeCodeCamp#12912]
cloud 9 is asking for credit card for signup please tell me alternative of this because i don't have credit card...and i want to make a full stack project in one month becoz i have to submit it as a major project in college plz help me..and my project topic is placement portal based on html css js as afront end and node.js as a back end..i need help plz fix this issue

**Comment by texas2010** [comment]
@atulsingh378, sorry, we can't help with your issue.  your issue is nothing with fcc repo.   FCC site and cloud 9 is separate. if you have an issue with cloud 9. you need to talk to cloud 9 support.

have a nice day.
