### ISSUE TITLE
This should work...

### ISSUE THREAD

**Issue by jlucas42** [freeCodeCamp/freeCodeCamp#12928]
Challenge [Chunky Monkey](https://www.freecodecamp.com/challenges/chunky-monkey#?solution=function%20chunkArrayInGroups(arr%2C%20size)%20%7B%0A%20%20var%20subArr%20%3D%20%5B%5D%3B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%20%3D%20i%20%2B%20size)%20%7B%0A%20%20%20%20subArr.push(arr.slice(i%2C%20i%20%2B%20size))%3B%0A%20%20%7D%0A%20%20return%20subArr%3B%0A%7D%0A%0AchunkArrayInGroups(%5B0%2C%201%2C%202%2C%203%2C%204%2C%205%2C%206%2C%207%2C%208%5D%2C%202)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var subArr = [];
var count = 0;

function chunkArrayInGroups(arr, size) {

  while (count < arr.length) {
    var slice = arr.slice(count, count + size);
    subArr.push(slice);
    count += size;
  }
  return subArr;
}

chunkArrayInGroups([0, 1, 2, 3, 4, 5, 6, 7, 8], 2);
```

I came up with this code to solve this challenge; When calling the function with the individual test arguments, the individual tests were returned as "correct", but the other tests returned "incorrect" unless tested explicitly in the chunkArrayInGroups() function. I'm not sure why this isn't working.

**Comment by OFFLlNE** [comment]
@jlucas42 Thank you for reporting the issue.

Since you declare variables outside the function, the tests run always on the previously edited variables.
So if you would throw your variables inside the function you should be good to go.

Next time try to use ***Help*** button to see maybe someone in help chat might see the problem you had.

Good luck coding!
