### ISSUE TITLE
Possible Bug in Exercise 26 of Practice Functional Programming

### ISSUE THREAD

**Issue by davisec52** [FreeCodeCamp/FreeCodeCamp#1292]
Challenge http://www.freecodecamp.com/challenges/waypoint-practice-functional-programming has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

This issue probably comes under the category of "quasi bug". 

For new programmers, this is a difficult tutorial but doable, for the most, part with a basic understanding of the native Java Script reduce(), map(), filter(), and concat() methods. The problem, or bug, is this: Some of the solutions to the exercises appear not to work when verified independently (using Chrome dev tools or repl.it, for example). For example, exercise 26 may appear to produce empty arrays. 

The reason is bound to the author's use of custom functions. In the tutorial, the author demonstrates implementing custom concatAll(), concatMap() and zip() methods. The exercise solutions, as well as the author's custom implementations, rely on slightly tweaked versions of the native filter(), reduce(), map() methods. Thus, the exercises run in the author's UI but may not be replicable independently without the author's tweaked versions of map(), reduce(), and filter().

This issue is explored in the stackoverflow thread at http://stackoverflow.com/questions/31348805/mapping-data-from-multiple-arrays-of-objects-to-a-new-object-in-javascript-using/31365090#31365090. Jeremy Larter explains the problem and provides a full example of the solution for exercise 26 plus the working custom functions at http://jsbin.com/tolupe/edit?js,console.

I would suggest that this waypoint set the expectation that the author uses custom implementations of native JS methods to drive the exercises and the custom implementations of concatAll() and concatMap().

**Comment by webdevjeffus** [comment]
On my system (fully-updated Windows 7, using Chrome), none of the exercises which require .concatAll() will pass, even when running the author's solution accessed by the Show Answer button.

**Comment by awesomeaniruddh** [comment]
Closing this because that specific external resource has been removed from the curriculum.
