### ISSUE TITLE
How to merge to jumbotron using css and html

### ISSUE THREAD

**Issue by killerkaran** [freeCodeCamp/freeCodeCamp#12922]
#### Challenge Name

https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage
#### Issue Description
I can't merge two jumbotron using one container having one jumbotron and another container haaving another jumbotron  just below one another  

#### Browser Information
google chrome

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code
HTML PART
<html>
  <head>
    <title>
      Portfolio Page
    </title>
    
  </head>
  <body>
    <div class="container ">
         <div class="jumbotron">
           <div class="row">
           <div class="col-md-6 col-sm-12">
             <div class="intro-part">
               <p>I'am a web devloper having a littele bit knowledge in the web devlopment part ,and wanted to learn as much as i can .</p>
               <hr class="line">
               <hr>
               <p>I actually specialised in some programming anguages like c++,c,and in devlopment side i used to work on the html,javascript,css,bootstrap</p>
             </div>
             </div>
             <img class="img-circle"  src="http://img3.rnkr-static.com/user_node_img/50013/1000242480/C350/david-beckham-all-people-photo-u2.jpg">
           </div>
     
    <div class="container">
    <div class="jumbotron">
      <section class=
     </div> 
    </div>
      </div>
    </div>
  </body>
</html> 
 

CSS PART
.line {
      border-color: #fff;
      border-top: solid 5px;
      }

}
.img-circle {
  border-radius:50%;
  padding-left:40px;
  margin-bottom:50px;
  
}
h2 {
  margin-top:20px;
  text-align:center;
}
#portfolio {
  padding:40px 0px;
  margin-top:20px;
}
.green {
  background-color: #9f9;
 
}```

**Comment by raisedadead** [comment]
Hi @killerkaran 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
