### ISSUE TITLE
Sorted Union Challenge not accepting results

### ISSUE THREAD

**Issue by DIZAD87** [freeCodeCamp/freeCodeCamp#12926]
Challenge [Sorted Union](https://www.freecodecamp.com/challenges/sorted-union#?solution=%2F%2FSolved%2C%20but%20system%20won't%20take%20it%3A%20In%20process%0A%2F%2FVariable%20declaration%0A%20%20var%20arrCombine%20%3D%20%5B%5D%3B%0A%20%20var%20countInputDuplicates%20%3D%200%3B%0A%20%20var%20arrResult%20%3D%20%5B%5D%3B%0A%20%20var%20storeUnique%20%3D%20%5B%5D%3B%0A%20%20var%20countResultDuplicates%20%3D%200%3B%0A%0A%2F%2FMain%20function%20that%20returns%20the%20challenge%20results%0Afunction%20uniteUnique(arr)%0A%20%20%7B%0A%20%20%20%20%2F%2FThis%20concatinates%20all%20the%20array%20arguments%0A%20%20%20%20%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20arguments.length%3B%20i%2B%2B)%0A%20%20%20%20%20%20%20%20%7BarrCombine%20%3D%20arrCombine.concat(arguments%5Bi%5D)%3B%7D%0A%0A%20%20%20%20%2F%2FThis%20removes%20the%20duplicates%0A%20%20%20%20%20%20for%20(var%20j%20%3D%200%3B%20j%20%3C%20arrCombine.length%3B%20j%2B%2B)%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%2F%2FThis%20counts%20the%20duplicates%20inside%20the%20arrCombine%0A%20%20%20%20%20%20%20%20%20%20%20%20for%20(var%20k%20%3D%200%3B%20k%20%3C%20arrCombine.length%3B%20k%2B%2B)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if(arrCombine%5Bj%5D%20%3D%3D%20arrCombine%5Bk%5D)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20countInputDuplicates%20%2B%2B%3B%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20%0A%20%20%20%20%20%20%20%20%20%20%2F%2FIf%20the%20count%20is%201%2C%20the%20value%20will%20be%20pushed%20to%20the%20result%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(countInputDuplicates%20%3C%202%20%7C%7C%20(countInputDuplicates%20%3E%3D%202%20%26%26%20scanResultArray(arrCombine%5Bj%5D)%20%3D%3D%3D%20true))%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%7BarrResult.push(arrCombine%5Bj%5D)%3B%7D%0A%20%20%20%20%20%20%20%20%20%20countInputDuplicates%20%3D%200%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20return%20arrResult%3B%0A%20%20%7D%0A%0A%2F%2FSub-function%20used%20to%20scan%20the%20result%20array%20to%20make%20sure%20there%20are%20no%20duplicates%0Afunction%20scanResultArray(num)%0A%20%20%7B%0A%20%20%20%20for%20(var%20l%20%3D%200%3B%20l%20%3C%20arrResult.length%3B%20l%2B%2B)%0A%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20if%20(num%20%3D%3D%20arrResult%5Bl%5D)%0A%20%20%20%20%20%20%20%20%20%20%20%20%7BcountResultDuplicates%2B%2B%3B%7D%0A%20%20%20%20%20%20%7D%20%20%0A%20%20%20%20if%20(countResultDuplicates%20%3E%200)%0A%20%20%20%20%20%20%7Breturn%20false%3B%7D%0A%20%20%20%20else%20%0A%20%20%20%20%20%20%7Breturn%20true%3B%7D%20%0A%20%20%7D%0A%2F%2FTest%0AuniteUnique(%5B1%2C%203%2C%202%5D%2C%20%5B5%2C%202%2C%201%2C%204%5D%2C%20%5B2%2C%201%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I created this code that returns the required results but for some reason it is not giving the green light, I believe it has something to do with my 2nd function and how I am using it to return values to the main function but this technically shouldn't be an issue on the final value that is returned.  Anyhow, any help would be great.

My code:
```javascript
//Solved, but system won't take it: In process
//Variable declaration
  var arrCombine = [];
  var countInputDuplicates = 0;
  var arrResult = [];
  var storeUnique = [];
  var countResultDuplicates = 0;

//Main function that returns the challenge results
function uniteUnique(arr)
  {
    //This concatinates all the array arguments
      for (var i = 0; i < arguments.length; i++)
        {arrCombine = arrCombine.concat(arguments[i]);}

    //This removes the duplicates
      for (var j = 0; j < arrCombine.length; j++)
        {
          //This counts the duplicates inside the arrCombine
            for (var k = 0; k < arrCombine.length; k++)
              {
                if(arrCombine[j] == arrCombine[k])
                  { countInputDuplicates ++; }
              } 
          //If the count is 1, the value will be pushed to the result
            if (countInputDuplicates < 2 || (countInputDuplicates >= 2 && scanResultArray(arrCombine[j]) === true))
             {arrResult.push(arrCombine[j]);}
          countInputDuplicates = 0;
        }
    return arrResult;
  }

//Sub-function used to scan the result array to make sure there are no duplicates
function scanResultArray(num)
  {
    for (var l = 0; l < arrResult.length; l++)
      {
        if (num == arrResult[l])
            {countResultDuplicates++;}
      }  
    if (countResultDuplicates > 0)
      {return false;}
    else 
      {return true;} 
  }
//Test
uniteUnique([1, 3, 2], [5, 2, 1, 4], [2, 1]);
```

**Comment by raisedadead** [comment]
Hi @DIZAD87 

Thanks for reporting, the code is valid, but the challenges fail because you have used global variables.

That said, I understand that you want to re-use and modularise, you could just refactor the code to something like this:

```js
//Main function that returns the challenge results
function uniteUnique(arr) {
  //Variable declaration
  var arrCombine = [];
  ...
  ...

  //Sub-function used to scan the result array to make sure there are no duplicates
  function scanResultArray(num) {
    ...
    ...
  }
    
  ...
  ...
  return arrResult;
}


//Test
uniteUnique([1, 3, 2], [5, 2, 1, 4], [2, 1]);
```

But if you absolutely want to use global variables, here is the relevant thread discussing the same
#9199
