### ISSUE TITLE
Instructions for "Object Oriented Programming: Change the Prototype to a New Object"

### ISSUE THREAD

**Issue by nhebb** [freeCodeCamp/freeCodeCamp#12933]
Challenge [change-the-prototype-to-a-new-object](http://beta.freecodecamp.com/en/challenges/object-oriented-programming/change-the-prototype-to-a-new-object) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js
    
    // In the instructions sidebar:
    describe = function() {
        console.log("My name is " + this.name);
    }

    // ... should be :
    describe: function() {
        console.log("My name is " + this.name);
    }

```

**Comment by HKuz** [comment]
@nhebb - good catch! Would you like to make this fix? Post here either way and no worries if not, I'll open it up to a first timer.

**Comment by HKuz** [comment]
For anyone wanting to make this fix, please check out the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) to get set up. Feel free to ask any questions in the [Contributors chat room](https://gitter.im/FreeCodeCamp/Contributors). You can find the code to make this edit [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/object-oriented-programming.json#L651). 

Thank you! 🎉

**Comment by padulam** [comment]
@HKuz I'd like to take this one on.

**Comment by HKuz** [comment]
Great, thanks @padulam!! 👍 💯
