### ISSUE TITLE
Exercise 27 ignores 'if' clauses

### ISSUE THREAD

**Issue by carl-hamlin** [FreeCodeCamp/FreeCodeCamp#1294]
'if' clauses are ignored in exercise 27.

I first noticed this issue while crafting a solution to the exercise; regardless of the conditional in my 'if clauses, the code would fall through.

To test the theory, I coded 'if' clauses specifically tailored to the tests in the exercise, and saw the same behaviour. Please see attached image - code returns undefined instead of value dictated by conditionals.

I tested the behaviour in Chrome, Firefox, and Internet Explorer, on two different machines, and saw the same behaviour.

When I reported this behaviour in the chat room, at least one other person reported that they were not able to replicate my results. Issue may be intermittent; will try again later this evening.

![image](https://cloud.githubusercontent.com/assets/1123094/8679733/a836dbde-2a19-11e5-9886-4906221ee0cd.png)

**Comment by DhruvPrakash** [comment]
Hi,
This does not seem like an issue. The result of both your if statements is false.

Try this:
1) Open your chrome developer console.
2) Type:
 var a = [5,4]

**Comment by benschenker** [comment]
Closing as stale
