### ISSUE TITLE
Inline styling is not different than CSS

### ISSUE THREAD

**Issue by Hapoofesgeli** [freeCodeCamp/freeCodeCamp#12942]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements) has an issue.

> 
> When you entered `<h2 style="color: red">CatPhotoApp</h2>`, you were giving that individual h2 element an inline style.
> That's one way to add style to an element, but a better way is by using CSS, which stands for Cascading Style Sheets.

According to the description, inline styling is defined as a separate thing than CSS. But in reality inline styling is actually a source of CSS having the second priority.

**Comment by Greenheart** [comment]
@Hapoofesgeli Good point! I agree that this instruction could be further improved.

We're currently in the process of revamping and expanding the curriculum over at https://beta.freecodecamp.com and I know that this challenge has been updated. I'm just unsure of how.

@HKuz Do you know if this improvement have been considered for the new update? :blush:

**Comment by HKuz** [comment]
@Hapoofesgeli that is a good point. There have been some recent changes in this section over on the Beta site since the CSS challenges were split from the HTML ones, but the text you point out wasn't modified. There's also a new introduction slide, that makes the point that CSS is applied with both inline styles or external style sheets.

I think this can be changed slightly:

> That's one way to add style to an element, but there's a better way to use CSS, which stands for Cascading Style Sheets.

What do folks think about that?

**Comment by Greenheart** [comment]
@HKuz I like the suggestion!

**Comment by Hapoofesgeli** [comment]
@HKuz The change sounds totally fine.

I've actually started to follow the beta site to both use the new materials and help testing if possible, tough I couldn't find much info about it, whether it's just a playground or an actual beta release.

**Comment by Greenheart** [comment]
@Hapoofesgeli It's a beta version of freeCodeCamp, running on similar infrastructure as the production-site to help us test new features and curriculum-updates.

Feel free to hunt some bugs and report them here as usual! You can also drop by https://gitter.im/FreeCodeCamp/Contributors if you want to hang out with other contributors :blush:

**Comment by HKuz** [comment]
@Hapoofesgeli - here's a link to the [Forum post about the beta release](https://forum.freecodecamp.com/t/our-expanded-curriculum-is-now-live-on-beta-freecodecamp-com-and-we-need-your-help-qaing-it/78844) if you're interested. And any help with QA and testing is hugely appreciated! 

As for contributing, would you like to make the change we suggested above on `staging`?

@Greenheart - what should we do about translations for this challenge? This re-wording doesn't materially change the meaning of the challenge, but it does make it more clear.

**Comment by Greenheart** [comment]
@HKuz This is exactly why I generally don't like translations, but prefer to stick to English (even for projects with Swedes like myself... :smile) - they get outdated so easily and doubles or triples the efforts required to do "full / proper" updates to the content.

I'd say we focus on the languages we know. If there's a need for translations, I think contributors will help out.

**Comment by Hapoofesgeli** [comment]
@HKuz Just tried to quickly do so, pardon me if anything is done wrong, barely familiar with the project's structure.

**Comment by HKuz** [comment]
@Hapoofesgeli - check out the [Contributor's guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) - there's a lot in there, but it walks through all the steps to get set up locally, name your branch, and open a PR. If you have questions, check out the [Contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) that @Greenheart posted above. Thank you! 🎉 

@Greenheart - sounds like a plan on translations, I agree that it's tough to make material changes without creating work for someone.

**Comment by Hapoofesgeli** [comment]
@HKuz I surely have checked that :)
Though not enough time for setting things up locally, just made a change and PR via GitHub targeting staging, anything specific that isn't done correctly?
