### ISSUE TITLE
Solution for High-Contrast mode request

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12955]
I am using a brilliant Chrome extension, offered by Google Accessibility

High-Contrast:
https://chrome.google.com/webstore/detail/high-contrast/djcfdncoelnlbldjfhinnjlhdjlikmph?hl=en

It offers many native color schemes, and even helps with designing a color pallete for freeCodeCamps Night Mode to maximize visibility of the pages contents, windows, tooltips, and editor.

The following images are taken from #12953

Night Mode:
![screen shot 2017-01-29 at 10 37 19 am](https://cloud.githubusercontent.com/assets/7606025/22406842/63d561f0-e60f-11e6-9816-d9ac9df5f42f.png)

High-Contrast on Night Mode:
![screen shot 2017-01-29 at 10 40 22 am](https://cloud.githubusercontent.com/assets/7606025/22406849/8e932fc6-e60f-11e6-9041-a71e954b463b.png)

**Comment by raisedadead** [comment]
Please follow our issue template while reporting issues. If this is a suggestion for use of a tool we would love to know more about it in the forum and not on the issue tracker.

**Comment by raisedadead** [comment]
Feel free to create an article on the forum, (maybe in the meta section) where this will get more traction. The issue tracker is strictly limited to the codebase and bugs associated with it.
