### ISSUE TITLE
It says it's correct when it's not

### ISSUE THREAD

**Issue by Jae888** [FreeCodeCamp/FreeCodeCamp#1295]
Challenge http://www.freecodecamp.com/challenges/bonfire-repeat-a-string-repeat-a-string has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

There is an issue with the tests this challenge runs to determine if you have the right answer or not.  Because the tests only the number 3 for n, It's possible to pass the challenge with the following code even though this is not the correct solution (because it will not work if n is anything other than three):
```
function repeat(str, num) {
  // repeat after me
 str = str += str += str;
    
  if (num < 0) {
    return "";
  }
  else {
    return str;
  }
}

repeat('abc', 4);
```

**Comment by tanhauhau** [comment]
Tried and it works
<img width="497" alt="screen shot 2015-07-15 at 10 40 23 am" src="https://cloud.githubusercontent.com/assets/2338632/8689707/f40867fc-2add-11e5-8065-3eb3633c514a.png">
<img width="474" alt="screen shot 2015-07-15 at 10 40 29 am" src="https://cloud.githubusercontent.com/assets/2338632/8689708/f4538228-2add-11e5-9d54-13fe1f85de66.png">

**Comment by Jae888** [comment]
Thank you!

**Comment by benschenker** [comment]
Closing as stale
