### ISSUE TITLE
[beta][UI][UX] the modal for "completed challenges"

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12952]
[beta] the modal for "completed challenges"

Also needs a Night Mode "refresh", should be more vibrant, the pop-up window needs to differentiate itself form the html page

Without Modal:
![screen shot 2017-01-29 at 9 06 10 am](https://cloud.githubusercontent.com/assets/7606025/22406152/3bc57130-e602-11e6-9a3b-e8bd8a2d9065.png)

With Modal:
![screen shot 2017-01-29 at 9 05 56 am](https://cloud.githubusercontent.com/assets/7606025/22406153/4354a2d6-e602-11e6-9333-652ae658eeac.png)

**Comment by tommygebru** [comment]
Example for a refreshed Night Mode version for the modal:
![screen shot 2017-01-29 at 10 03 54 am](https://cloud.githubusercontent.com/assets/7606025/22406594/61bef1d8-e60a-11e6-8d38-cae25bf9367e.png)

**Comment by no-stack-dub-sack** [comment]
@tommygebru Not sure exactly what you mean... are you suggesting the night mode modal should look like the photo directly above? ☝️ 

The issue with that, is it is too bright, and does not really fit with the night mode theme. In fact, this was very recently changed from exactly this to what it is now: #12558 / #12556

**Comment by tommygebru** [comment]
@no-stack-dub-sack Here is one that looks nice i think 👍 

![screen shot 2017-01-29 at 3 40 49 pm](https://cloud.githubusercontent.com/assets/7606025/22409224/25d72498-e63b-11e6-8ab2-72a940c91def.png)

**Comment by no-stack-dub-sack** [comment]
@tommygebru hmmm, let's ask some other folks what they think. I'm ok with going with whatever everyone seems to think is the right move. I think the white check looks nice, but the purpley-grey does not seem to match any of the other nightmode colors... 

@systimotic you were one of the reviewers for the above mentioned PR that changed the style of the  nightmode modal to what it currently is - what do you think?

**Comment by tommygebru** [comment]
@no-stack-dub-sack 

If you are curious about the background change, it would make more sense if you checkout #12953 

also I put in a PR for the design-style-guide here to reflect the more "vibrant" night mode 
https://github.com/freeCodeCamp/design-style-guide/pull/14

I think that this night mode will be more engaging to the campers

as far as a high-contrast color pallete, I believe the best solution comes in the form of a chrome extension and i also made an issue for that as well #12955

**Comment by no-stack-dub-sack** [comment]
@tommygebru Cool, yeah, I just checked out #12953 and I'm not sure I would prefer these colors. However, I'm not a designer or a pro UX guy by any means, so once some other opinions get registered, we can see where it goes!

**Comment by dhcodes** [comment]
I (personally) like the proposed modal provided by @tommygebru above but I would change the white check to a very light grey since night mode is supposed to be "less bright" overall. Also, I would recommend we connect any of the recent issues related to high-contrast to https://github.com/freeCodeCamp/freeCodeCamp/issues/8845 for use in a high-contrast mode for all of freeCodeCamp, not just the editor. There would then be two modes: high-contrast and night-mode. Thoughts on this @tommygebru ?

**Comment by tommygebru** [comment]
@dhcodes thanks for sharing, I think its great that FCC is willing to design a high-contrast mode, however I found a greater solution with a `Google Accessibility extension` that will change any webpage on a browser to a custom color scheme to help all visually impaired or sensitive users.

`High Contrast` - https://chrome.google.com/webstore/detail/high-contrast/djcfdncoelnlbldjfhinnjlhdjlikmph?hl=en

Perhaps we should include this as a button next to Night Mode's button on Freecodecamp?

**Comment by tommygebru** [comment]
@raisedadead If there is a concern that the colors do not deserve a branch or pagination on Freecodecamp's `design-style-guide`. Then I purpose at the very least we should expand on either Freecodecamps Primary or Secondary color palette to include `Thunder`. 

Also - I have not seen Freecodecamp utilize all of Freecodecamps colors in Primary nor Secondary and I am curious if we will remove some colors from both pages.

As for the white icon on the modal, I think it should stay, it is a very minimal amount of white color, and matches the rest of the Night Mode color scheme, `white is for fonts and characters`.

**Comment by raisedadead** [comment]
I think we can discuss more about adding the existing colors to the site's UI in ways that it enhances the UX which I can see this issue aims to address beautifully.

Sorry if I missed it, what is `Thunder` again?

**Comment by tommygebru** [comment]
Yes- Thunder is a new color proposal

I will make a new pull request to add it as a primary color to the design style guide

Also - Thunder shares a familiar color pathway to Freecodecamps gitter community

**Comment by no-stack-dub-sack** [comment]
@tommygebru @dhcodes @raisedadead I think what all of these discussions (#12953, #12852, #8845, etc.) really suggest, is that we desperately need a standardization of night mode colors somewhere, whether it be a part of the style guide or not. And to decide on high-contrast mode.

My only issue would with the above proposed modal would be that the `Thunder` color doesn't match any of the other current night mode colors, so if we did adopt it, perhaps we should adopt it in other places as well as in @tommygebru's suggestion from [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/12953), which adopts it in the background as well.

<img src="https://cloud.githubusercontent.com/assets/7606025/22406350/b005bec0-e606-11e6-9ef0-89ee7f36c82c.png" width="400px"/>

Even though I've gotten used to and really like the current night mode color palette, I can see how it might also be seen as monotone. So if it does get changed, I think it's important that it remains distinguishably freeCodeCamp. 

As for high contrast mode, I really like the idea of the of the Chrome Extension because it is so customizable, but I believe (and I could be wrong) that we are trying to do all of this as independent of things like browser extensions as possible in order to really keep with accessibility principles, because then any users who need high contrast mode that don't prefer Chrome would be out of luck. So in this case, while I love the extension, I think a built in mode is ultimately the better solution. Perhaps a wiki mention for this particular extension so that campers are aware of it's existence?

All in all I see three major points here, and perhaps we can come up with some way to get a larger discussion going to decide on what should be decided and how:
- Nightmode color palette changes and standardization
- 3rd mode - high contrast mode
- How and where to dictate and standardize both for future contributors 

Again, thanks @tommygebru for your critical thinking on all of this! Looking forward to seeing what we can all come up with!

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (115/100 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60274 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx5P-0003ec-Te
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:19:00 -0400
Received: from o10.sgmail.github.com ([167.89.101.201]:44718)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx5H-0001z4-FS
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:18:51 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=/eHgkkwlHH8xqAcBkfWR5rt9zHU=; b=Iag6re5moJFnm1Px
	7qgQatBkWg6MdASzJ5Y564SZZTCUrqDcH20vLoFJ7ZqR08qFdV/EKkopkmcX+Jv/
	5O0J0Ap+kbAVOD5f9uEcDCK/Jt0jXCxrV+toEcASZlWgmg3ykMIGdCpkg77rQrOF
	qM6ksUdGi3uqnu5ctAgGnRORpzE=
Received: by filter0464p1las1.sendgrid.net with SMTP id filter0464p1las1-1653-59AA06FA-1
        2017-09-02 01:18:50.207497109 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id ulj8JjCUR1K5evb7yVGVLA
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:18:50.181 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:18:50 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (117/100 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f42.google.com ([209.85.218.42]:33836)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx62-003t9x-Vv
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:49:50 +0530
Received: by mail-oi0-f42.google.com with SMTP id w10so13913875oie.1
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:19:18 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=NetV9NJQRstMKtkD1TRoAFxIuYyyqvYy15DUrlVV1pM=;
        b=D1duW5uF0Od4VcAyTG3Mc5Rh0AlbobB/nH1tqE+C2SKucv6kdP/VYVzji/HWKTL1M0
         XIjWJ82OAEAf8CDs4dSPJp8fBGVU7uH8EIOeo9gikCaPaBMJh70udT7GXltjM14o1YaD
         wsvGSVNxFyyHweujDaPdmlTJSCq8icStJdXr4DSLeEFTRXLOyeHjBUy9qBIuPKT3r/OI
         2DtxeLHupxEI6C7uahCRfiTzNuH4iK40qemNdXVwLU08/Vy09fOy5Lti9y7JId0i341E
         uuW577X4Rzg5VPc/1IyVGLwLvLftYzIDyBWgtRxvD9aVpICu9B4o1nvl0oU9gD/a53ZZ
         t4ow==
X-Gm-Message-State: AHPjjUjscCgx+oEOyAd+CV7rycPACiHeeAVvKwcbBeq8aVOvA4JlrbmM
	6mxtQZYMUPGgxTsZ3WO8euRhqNz0pWqI2HlXkRjnCQ==
X-Received: by 10.202.117.129 with SMTP id q123mr3398924oic.16.1504315136452;
        Fri, 01 Sep 2017 18:18:56 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1354135ofe;
        Fri, 1 Sep 2017 18:18:55 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb7uJRFvJOB1TLWz/vrbmZSoMt9cZ6XsAVTLRtvExKQL4R4F9gSmVAmNqfGdpcKIMN6lYWKj
X-Received: by 10.107.145.130 with SMTP id t124mr3423194iod.158.1504315135748;
        Fri, 01 Sep 2017 18:18:55 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504315135; cv=none;
        d=google.com; s=arc-20160816;
        b=Z7qkw45Y4RlDiYrO4DsRfOBk49W6xSPJbnEc2IFvoG2VwVWoAxOKJtOW3wx2vG1LkF
         JHkqm2KUdZGVLoUWF9gnhnxVh37Q+YrBE3zBE51SSFI6QU/cq62rvSpi9bqG/96MjKT6
         evN8ZtoWujf6qQ0WYMCkuJwMvd2UZZJQAb+pXoGRAv1xhkdKuHdw6wd+BTuBWT+e9ZSL
         j6ULSF23/vgtsVRpI+yLL+dy1FYpIQZitoXtMZw/vkfS4D2gvMjdXt8YCCm8rWsiSSNt
         5PUm55UJp8fC6KPmVkpRibztzXgLGY/sC3VmeHeFCwT249zBNszpBp9YxmqJI8e9unH3
         D80A==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=NetV9NJQRstMKtkD1TRoAFxIuYyyqvYy15DUrlVV1pM=;
        b=t/mmy7KAfMsOzDi/IaPKOJnqvoxVVeMzp2lGYg1REGn8pA2qcJEqnxu/H7LBWVMzcc
         wkhlIg1rXRPxFPuXt0pHI9/PJ8VGrACelkcC+p3dYyvqe7tmTKhBqkdZHzVlhuYM79Ls
         mQMuDTAFF4NvwjorYER21o5gZZ05Az9OU8CKMUOq1fN2YTxJ9cSM2g/+zYqJyHAMauJr
         juQ3l09zZHYMBH7cPgMDwCyF7aU7mHV5gWZu7nYXRMrL0SRCev7qAWe0FImsQnuAvSpp
         XuVoLs/LzLGnHv8kuhIPR8ymxb4vy/hLJ/pKqQzfrBepOuUy5Tj/kkqedBhq77j2m0U4
         yVBw==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=i8mRY98X;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=hTrEhJBH;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.114.176 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o1.sgmail.github.com (o1.sgmail.github.com. [192.254.114.176])
        by mx.google.com with ESMTPS id c6si1385324ite.56.2017.09.01.18.18.55
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:18:55 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.114.176 as permitted sender) client-ip=192.254.114.176;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=i8mRY98X;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=hTrEhJBH;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.114.176 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=wGusbfb5vkUS2H44Ad0vMGtCivo=; b=i8mRY98X0eG4IYT/
	GUIkJfKj741+tnYZ8do/ERl0V4ruxs8AfW55w9129I1qTa5XxL+d9m4lv7Vk3tt3
	NXIiKUYR0BaMl7ouDxr7xlb6ZJ9uNpHtyATXUt/IUlCX4O6/cgeVC+URrC6H/RZF
	rs7Da6soiAkzQzfttlTSR+uVawA=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=wGusbfb5vkUS2H44Ad0vMGtCivo=; b=hTrEhJBHH7hwaSh/yv
	jKq9qgz0qri2OlZdOYJyumT6kCSUV9FeN5RY1rw4534btQBDx0yK37x4PU+hOTOG
	SWzES5Un/KhhxYdNUq8kwDgDXi12mV/NhNpwYY9pqqSPJQFXIkt2Hv3Dpfqpm7nq
	0zb8smoetatBVHdGi1A6G32Is=
Received: by filter0968p1mdw1.sendgrid.net with SMTP id filter0968p1mdw1-30823-59AA06FF-28
        2017-09-02 01:18:55.646307324 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0025p1mdw1.sendgrid.net (SG) with ESMTP id rcQGIpQoRkygaji4qzFR7A
	for <pawan.ossindia@gmail.com>; Sat, 02 Sep 2017 01:18:55.673 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:18:55 +0000 (UTC)
