### ISSUE TITLE
[beta][UI][UX] Night Mode example

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#12953]
Current:
![screen shot 2017-01-29 at 9 19 16 am](https://cloud.githubusercontent.com/assets/7606025/22406334/7c35ed54-e606-11e6-9be2-819c35d05949.png)
Night Mode refresh:
![screen shot 2017-01-29 at 9 24 44 am](https://cloud.githubusercontent.com/assets/7606025/22406340/917ec69a-e606-11e6-924d-beff806ad9e5.png)

Current:
![screen shot 2017-01-29 at 9 06 10 am](https://cloud.githubusercontent.com/assets/7606025/22406346/9e873656-e606-11e6-9a2a-416523927998.png)
Night Mode refresh:
![screen shot 2017-01-29 at 9 32 56 am](https://cloud.githubusercontent.com/assets/7606025/22406350/b005bec0-e606-11e6-9ef0-89ee7f36c82c.png)

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (105/100 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60191 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx2x-0003Qs-Fd
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:27 -0400
Received: from o3.sgmail.github.com ([192.254.112.98]:55842)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx2r-0001rv-7R
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:22 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=VoS+4hUSuc+G23ThaOdo6gI2bm8=; b=BrmQ+KejT/1bq2CA
	a+3OwV+0rPZaFazzeFNvWReypeIol8mSXHXfKBJzcX10104T8PTOjMnCgGpzEiZQ
	CDsA0Qkmpv65cJqIQKbuc/Qf5Wz5MQK2S+AlRMVnIKXmpE+u3sIhYMwnxHhB9/M4
	GFMhlHvaTc+M1vLEirQOHHVwMzs=
Received: by filter0073p1las1.sendgrid.net with SMTP id filter0073p1las1-21877-59AA0663-9A
        2017-09-02 01:16:19.976673877 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id T7xzJWFhTP-RmnEyYImhug
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:16:19.924 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:20 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (106/100 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f46.google.com ([209.85.218.46]:34300)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx3j-003lVz-OP
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:47:32 +0530
Received: by mail-oi0-f46.google.com with SMTP id w10so13895133oie.1
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:16:55 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=bSwEiVR5t6WkxguY8D+EdDa5FxfA+uZCba/ChKbgFvs=;
        b=Tf63/TO9HCV9oDBHbU+j7sbIIYXVeacV8oBsGVMfyDwfnxdh5O1QLXtqQFTzERG9wj
         5kNlpQTYCc3nx/ajpAE4K+dN9DaLFHCit2Vaa2qRubLJCLze7lbrG14LjretMjtZw22U
         7l96JQxrOSrnQyq9gMSoAZ6NbuwDzA6VYg8P9+Xt6opW9CAQHn8xoLYHlMxlNUvyQl77
         JRcB4hbu4IctvTeCPkMZPAlB1TgNqBRY9wk0Txi+t6MVUkiDjcifu2k5k8p2a4ZgeblP
         WvaIF1ftrIBlCUyVz++FTEX8smlF792f0zFyFdakMqfZFur+/M0tvD1ant6k7zYjBsgl
         SQYQ==
X-Gm-Message-State: AHPjjUgRW+CruseZd0EC2m+14lwQk3B+mbe8lEn0yes/ByFUui3y9nZa
	+xZVAM39mnEKLOowBmryav/dSov/kHJPI/LzvJUkIg==
X-Received: by 10.202.0.208 with SMTP id 199mr4453980oia.40.1504314993065;
        Fri, 01 Sep 2017 18:16:33 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1352764ofe;
        Fri, 1 Sep 2017 18:16:32 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb646ezXA5YSgdWtcVzpq/e6q8H4yofPXRpstPhfwQKSSeD8zesTMBv8ya0wFYBs8JZRHO1J
X-Received: by 10.107.15.205 with SMTP id 74mr3110761iop.203.1504314992411;
        Fri, 01 Sep 2017 18:16:32 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504314992; cv=none;
        d=google.com; s=arc-20160816;
        b=NRG/hRvByAPO4VNLuPPjnecnPCyyJI8X+ElqQBg0GLV1+BkgViRYFlRJO6FkiGB50g
         v+xmHPvNqyzq3scj92XOrPyXC5flhPlyKWYmuE7MgzFNQmzIT0QBX4DDsJ/bXjS6lWV4
         crcp9HiKuBpSDnvhxS37eq7bPSBj8RNwnJ3/gBnH9KsWGdjKvA1/0ZsKz0RXHP+I3iA9
         zoVNIUT0nWbQT9hHL6im+0R+g1EoK1V8fftoIywKZtPStwYXRHYPTPty2oDBF5bGE9Xo
         u8QMfsgqMV9Dp4KSODjeZORfxOZd+4u6/nQb6phD5yqh8uwXp0baeR+MRO23q87za4uZ
         9L2w==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=bSwEiVR5t6WkxguY8D+EdDa5FxfA+uZCba/ChKbgFvs=;
        b=e9RerQd+hboP3CMtu8QarfyrzS/nvFCQ1xNGVlFd1bAdd3pol3On8QUkld+qVi5wHI
         3Iukf2a11E5Dx6eI6cNOKMNfDUyLUqOOTs1Y/URKRhL5Hyeb+36/VK2Z2vDVgXc20yQ5
         Ny6wJUvTNkbACon9AFzYk4kUy5iZTXZ1yVh7IzccEaDfMZb51oMrUJH3Ya9kynkT2cZM
         R0gJzuFPd2O0HCnnDyt70Fq/EU+jp1Hz2C0HnYI0s/ThQ3aO4PHRwzYY0obUnNevAlSL
         UbEgA/k/r/4N98Hk2U9WpSF2NZjqyzvhQVnnikqGVhTBrkt3EEYVleHcEoxjFB14PTR4
         LqxA==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=LZeRwXvc;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=A9tgesiF;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.101 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o6.sgmail.github.com (o6.sgmail.github.com. [192.254.113.101])
        by mx.google.com with ESMTPS id k186si1258463itk.50.2017.09.01.18.16.32
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:16:32 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.101 as permitted sender) client-ip=192.254.113.101;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=LZeRwXvc;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=A9tgesiF;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.101 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=KOKGBe9jH8tdLB35Y3H4D+89I9M=; b=LZeRwXvcYiQJ0+UL
	+rFB6z8qyEbzWnkLtKZb5vcXVgyVFPeVRj04KfYXs9QMhOX7rPKzHTPzz9+WIriJ
	w1/ijK+X36LcUD7b92mkrQCCnkFp58rO12hMWIuwrYgTvCTXo+nylWrVU94YNdNw
	cy/28/J1UpLStOKifZmWbLRwNIw=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=KOKGBe9jH8tdLB35Y3H4D+89I9M=; b=A9tgesiFgVgC+Vd0gO
	nbHIK25VrmnskGi0ajrmB8mwkrPXdjY+yNwc+GHBxFTihRz+xv6iNOEnf3FWXPZq
	8fh5qAMpR9GNYppVbhPG+1KVjcyqLkm907zpxQVaQkOM19uiTPyE1F50Z4ibQFq5
	jaUCBsHK0DC0xBS3Qm6gfwrSw=
Received: by filter0474p1mdw1.sendgrid.net with SMTP id filter0474p1mdw1-13117-59AA0670-E
        2017-09-02 01:16:32.244514348 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0036p1mdw1.sendgrid.net (SG) with ESMTP id r2AHrDhmQfSVn0aussLExQ
	for <pawan.ossindia@gmail.com>; Sat, 02 Sep 2017 01:16:32.170 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:32 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (122/100 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 24905 characters long; only the first
------ 5000 or so are included here.
Received: from mail-oi0-f45.google.com ([209.85.218.45]:33949)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx6X-003v2X-Ci
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:50:24 +0530
Received: by mail-oi0-f45.google.com with SMTP id w10so13917666oie.1
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:19:48 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:date:dkim-signature:from:reply-to
         :to:cc:message-id:in-reply-to:references:subject:mime-version
         :content-transfer-encoding:precedence:list-id:list-archive:list-post
         :list-unsubscribe;
        bh=2tOWpjY8t4kP8Wn3Bme5fOgEb0/edIanLzLZOfqOoRY=;
        b=M9F6EfQSx9dQPTcKsDaAVrM+Pb3N2NvUqvopT8LFdjFhCzry4fHn4HkJcR+nbk1ZE/
         Ve8/uL/9JZLZElEX7G3XxEQt4c3Pj6gC/v7YfRhafo1My74mpzxpkw0Ahp8DRhNJRN1P
         6CyNMZqg7wdKM0HvtIopSV6cVtTmMx8Tz+lR+n+40TZPSmMyd4nbU9yW7tHjTpK8oeAT
         uQyf/r2dlLwItUNGlxV9PGrCBxwU+4l4ydxH2jp/0TjIO6SWBY/qZ+5+yHHt+ZP3EDmQ
         Fb2WctjG9W7pvGpuAyUuJv1QLtfUU6Cd8njYs283bSut9+ill7cwUi8gpZWuEJXVPgh9
         f/aA==
X-Gm-Message-State: AHPjjUi6dmk7ECOe6YeeD5UZlqZe8cTsq29zWYTf7UDAWpRSd252BVNm
	MFWc3mkju6Ut9a9tvq0B1AyKHy1uhGIvsrb+XJJCMQ==
X-Received: by 10.202.79.7 with SMTP id d7mr3287491oib.71.1504315166834;
        Fri, 01 Sep 2017 18:19:26 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1354412ofe;
        Fri, 1 Sep 2017 18:19:25 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb7V2anww1OrDF8VOHyvUl2N7BVZUuBfLvD4Dy8IDMbCloxFkLm4VdYt7pxvABqZLoYaqWBH
X-Received: by 10.237.32.175 with SMTP id 44mr5480975qtb.39.1504315165835;
        Fri, 01 Sep 2017 18:19:25 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504315165; cv=none;
        d=google.com; s=arc-20160816;
        b=ReAgfFGxACqyA/JZkRe42I4XkwySTjvk0IiI6GeLeyRdsRS/FmDoaDT0e/U4KXZRBl
         zw3zCO2Ym/gOgDqjNKVtu6qr3fP8LL4xphTlX2+wDZFBDq/Yq0QNwNE0slks07H1oNkL
         RhEl+nPkA/VVru2v8mQEi0qPjJYfr+WEhE3laAc6aV645qRelPHp1GL+msrDURoTw4jv
         oEUXRqLKv0IimB5hfr3bC3hrjAEjl2P+DcUzy9biPizsXCaOPqLDTEk7xeAeg8503R36
         0z6PpZSujV3qiavD+NL1HW91fZs6TaBjixn3Lz56geLXeJK/aM90GhQrdN4MYGY6e4CQ
         hEdA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:dkim-signature:date
         :arc-authentication-results;
        bh=2tOWpjY8t4kP8Wn3Bme5fOgEb0/edIanLzLZOfqOoRY=;
        b=ES+l21NCZi8Q3pFTKciyhh8EbcYx24HOR0AUQqMWXng/n3TTFYvM+gSOzv+nCbIp7A
         ZjSjvRZ4/to2QgfGgJqX+1zzm4zvr3HOlrQYiUxd6XBfw/qi2CsCYYKvC3wP0UYJAvhP
         jSbXH53vmXvznJ4ju9l2mkfJsRhtYYdAVgO+V4z4VIgMy/YqDW22xLl7n5KeLJzQZ5XZ
         WggK8+mgivzPXwna7TxeXsZ+Mv4dwRz7aG+IPXqfZv89yrfphzwAOmKtVAcStucT4vFa
         3aFV5BRDUWxucw8AAugKSRKclFqJkAj/Q6OAuQi3IR187UPtp4BbgqsA3zS1JNm8w/ui
         bqAA==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=tiosd2Wq;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.199 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2-ext8.iad.github.net. [192.30.252.199])
        by mx.google.com with ESMTPS id x124si127487qka.233.2017.09.01.18.19.25
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:19:25 -0700 (PDT)
Received-SPF: pass (google.com: domain of noreply@github.com designates 192.30.252.199 as permitted sender) client-ip=192.30.252.199;
Authentication-Results: mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=tiosd2Wq;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.199 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Date: Fri, 01 Sep 2017 18:19:10 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1504315165;
	bh=2tOWpjY8t4kP8Wn3Bme5fOgEb0/edIanLzLZOfqOoRY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=tiosd2Wqv9Q8MP5mc8xmGZqGALWcUvrZ8R/DbzEwCgCiYWvSrY0vQ2Brk19JG4TsJ
	 7IKZIodc0Mm6k1UIYRVG5H2umY7wLPMgSlcabM1ambX/OnJUNx347tJaO8IEG1MNP1
	 Bam5whBWtAJDlI4TvbWj9DUwX+oHB7FcD7C/p9vk=
