### ISSUE TITLE
Feature Request: Mozilla's  Open Backpack

### ISSUE THREAD

**Issue by carl-parrish** [FreeCodeCamp/freecodecamp#1296]
Would love to be able to share my certificate / badges (http://openbadges.org/) from FCC on Mozilla's  Backpack. (https://backpack.openbadges.org/backpack/)

**Comment by FFX01** [comment]
I didn't even know about this openbadge thing. Seems really really cool.

**Comment by Jaweishampel** [comment]
Agreed

**Comment by onebree** [comment]
:+1: I recommended this over a month ago!

**Comment by carl-parrish** [comment]
Sorry onebree, I just became aware of FCC a few days ago. I'm still getting caught up.

**Comment by onebree** [comment]
@carl-parrish I did not mean to sound upset. I simply tweeted FCC about it. I am glad someone put a request in on github!

https://twitter.com/twobree/status/607229167063724032

**Comment by johnapaz** [comment]
Can someone link to the issue requesting it so we can upvote it?

Cheers,

John A. Paz

johnApaz@gmail.com

**Comment by carl-parrish** [comment]
done!

**Comment by carl-parrish** [comment]
Please upvote it - sounds like a lot of decisions about certification are being made now and I'd like open badges to be part of it.

**Comment by johnapaz** [comment]
Upvoted.

**Comment by BerkeleyTrue** [comment]
closing in favor of #604
