### ISSUE TITLE
myFreeCode

### ISSUE THREAD

**Issue by Ririnrinasty** [freeCodeCamp/freeCodeCamp#12961]
Challenge [Build a Tribute Page](https://www.freecodecamp.com/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by no-stack-dub-sack** [comment]
Hi @Ririnrinasty, I'm not seeing any description here, can you please explain what the issue you are having is? Thanks!

**Comment by OFFLlNE** [comment]
Closing for now.

@Ririnrinasty ReOpen if you can add further details of the Issue you are having
