### ISSUE TITLE
[beta] More of a pedagogical issue.

### ISSUE THREAD

**Issue by masters-george** [freeCodeCamp/freeCodeCamp#12964]
The hover state should be introduced (typically when discussing how to style links) then extend to other elements such as paragraphs, ids, and classes. Doing so is pedagogically more sound and makes the course easier to follow.

**Comment by HKuz** [comment]
@masters-george - are you referencing the challenge `Add a Box-shadow to a Card-like Element`, and that it comes before the `Adjust the Hover State of an Anchor Tag` in the Applied Visual Design section? If so, we just had an issue come up that's similar ( #12979 ). I think taking your point and that issue, we can make the material flow better by removing the `hover` requirement on the box-shadow challenge. 

Thanks for taking the time to review the new challenges!

**Comment by masters-george** [comment]
Hi Heather K.

Thanks for getting back to me. I would agree with you. When we cover the
hover state with anchors (the most common use case), then it would make
sense to follow it with another module that says essentially by the way you
can use the hover state with other tags (such as the paragraph tag).

George Masters
instructional Designer /Trainer
408.242.4632
