### ISSUE TITLE
beta-course Intro to CSS not marked complete on map (no dimming of text in map)

### ISSUE THREAD

**Issue by masters-george** [freeCodeCamp/freeCodeCamp#12960]
The beta version of the course does not mark the Introduction to Basic CSS complete after going through it. I can reproduce this behavior on Linus and Windows systems using Chrome, Firefox, and Opera. I am on current versions of all three of these browsers.

![clipboard01](https://cloud.githubusercontent.com/assets/24727860/22408253/426da63c-e62b-11e6-8815-9cf4c82b30b5.jpg)

**Comment by HKuz** [comment]
Hi @masters-george - thanks so much for the help with QA on the Beta site! Looks like this issue has been raised over in #12927 so I'm going to close this as a duplicate. Feel free to join the discussion over on that issue - it looks like another contributor narrowed down the problem, hopefully a fix coming soon. Thanks 🎉

**Comment by masters-george** [comment]
Glad I could help. The courselves content has more detail and the content
is pedagogically improved which newbies should hopefully find easier to
learn.
