### ISSUE TITLE
Shop link is broken on staging

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/freeCodeCamp#12968]
I get a 500 "Loopback Error" when trying to access the shop when running freeCodeCamp locally. Looks like it may have been removed as part of this commit: https://github.com/freeCodeCamp/freeCodeCamp/commit/86d4b5e841996b5f9f4a95a43e08943eab838287

**Comment by kyrom8** [comment]
i don't know that!

**Comment by raisedadead** [comment]
@dhcodes 
This is expected, and if you check it will be the case for about page, these pages are now statically hosted over GitHub pages in their own repositories.

On our production websites, these redirects are managed at the NGNIX level I believe, which is even before hitting the freeCodeCamp server code.

You can choose to ignore this error, unless anything specific that you might feel is out of the place.

**Comment by raisedadead** [comment]
Hello @kyrom8 !

Looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) or click on the image below and select **"Not watching"**.

[![image](https://cloud.githubusercontent.com/assets/1884376/15005313/9ba8a14a-11e0-11e6-81cb-d7cfe6b66a30.png)](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription)


We are sorry for your inconvenience!

**Comment by dhcodes** [comment]
Thanks. I thought it may have been intentional. My bad.

**Comment by raisedadead** [comment]
No worries, happy to help!
