### ISSUE TITLE
es6 arrow function example is misleading

### ISSUE THREAD

**Issue by kalunlee136** [freeCodeCamp/freeCodeCamp#12978]
Challenge [arrow-functions](https://beta.freecodecamp.com/en/challenges/es6/arrow-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The example for the beta FCC arrow function challenge says you can make an arrow function like this:
```js
 () => ( // function body
    return ;
 )
 ```
however after reading according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) the correct way seems to be: 
```js 
 ()=> {return;}
```

**Comment by hisener** [comment]
You're right!

Arrow functions' description should be changed in [seed/challenges/02-javascript-algorithms-and-data-structures/es6.json](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/es6.json)

**Comment by HKuz** [comment]
Hi @kalunlee136 - thanks for pointing this out 👍 There's actually an open pull request (#12963) that refactors this challenge, and it fixes the example to use curly braces. I'll ask them to update the PR description so it closes this issue when it's accepted. Thanks for your help with QA working through the new challenges!

**Comment by Greenheart** [comment]
@kalunlee136 @hisener Technically, parenthesis `()` in JavaScript tells the runtime that there's an expression coming, much like parenthesis are used in maths. `()` can be used to split a long expression into several lines and make it more readable.

Consider the following long expression...
```js
(obj, min, max) => obj !== undefined &&  obj.prop > min && obj.prop < max
```

...that thanks to the `()` could be turned into

```js
(obj, min, max) => (
  obj !== undefined &&
  obj.prop > min &&
  obj.prop < max
)
```

Arrow functions can either consist of a *single expression* (`(a, b) => a === b`, that also could be written as a `(a, b) => (a === b)`), or *multiple expressions and **statements*** by using regular curly braces (`{}`) like
```js
() => {
  expression1;
  statement1;
  const result = expression2();

  return result;
}
```

With that said, I agree that the curly braces should be used for a multiline example :relaxed:
