### ISSUE TITLE
It appears that this challenge is not properly accessing the test methods

### ISSUE THREAD

**Issue by strongdan** [freeCodeCamp/freeCodeCamp#12972]
![screenshot 2017-01-29 at 20 00 39](https://cloud.githubusercontent.com/assets/3577434/22412696/b6bde862-e65d-11e6-8a31-853e6488bddd.png)
![screenshot 2017-01-29 at 20 00 21](https://cloud.githubusercontent.com/assets/3577434/22412698/ba4e9058-e65d-11e6-8e10-1bf94582c9e5.png)

Challenge [shopping-list](http://beta.freecodecamp.com/en/challenges/basic-javascript/shopping-list) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 8872.76.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.105 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var myList = [["Chocolate Bar", 15],["Pretzels", 10],["Bananas", 8],["Bread", 2],["Milk", 15]];



```

**Comment by erictleung** [comment]
@strongdan thanks for the issue. What browser are you using? I was unable to reproduce this error in both Chrome and Firebox.

**Comment by hisener** [comment]
@erictleung The user agent looks like Chrome 55 on Chrome OS. Also, I couldn't reproduce neither.

**Comment by strongdan** [comment]
I was able to get this to pass on Chrome Canary on Windows 7. Previously failed on Chrome on a Chromebook. Not sure what the problem was.
