### ISSUE TITLE
Bonfire: Spinal Tap Case doesn't display challenge completed modal even after passing all the tests

### ISSUE THREAD

**Issue by royshouvik** [FreeCodeCamp/FreeCodeCamp#1297]
Challenge http://www.freecodecamp.com/challenges/bonfire-spinal-tap-case has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Solution Code
```
function spinalCase(str) {
  // "It's such a fine line between stupid, and clever."
  // --David St. Hubbins
  var reg1 =/\B[A-Z][a-z]*|[a-z]+/g;
  var reg2 =/\b[A-Z][a-z]*|[a-z]+/g;
  var reg3 = /\s/g;
  
  if(reg3.test(str)){
      //string has spaces
      arr = str.match(reg2);
  }
  else{
      arr.str.match(reg1);
  }
  arr.forEach(toLow);
  
  return arr.join("-");
}

spinalCase('This Is Spinal Tap');


function toLow(element, index, array){
    
    array[index] = element.toLowerCase();
}
```

Screenshot
![image](https://cloud.githubusercontent.com/assets/5521768/8687643/1d26e466-2ab0-11e5-8a16-32ac47e3c4e3.png)

**Comment by royshouvik** [comment]
Google Chrome  43.0.2357.132 m on Windows 7 64 bit.

**Comment by reverseskydiver** [comment]
Same story to me.

Firefox 39.0 Windows 7 64 bit.

**Comment by jqkwest** [comment]
Having similiar issue...

**Comment by rajvansia** [comment]
i had this issue today my fix was that you need to "return num;" num is the given value that your were provided from the start. There is an issue when you return your own variable.

**Comment by royshouvik** [comment]
@rajvansia Thanks! I haven't checked your workaround but I would suggest that this needs to be fixed.

**Comment by jqkwest** [comment]
Indeed. It's still not passing for me. I am returning a string variable assigned the value of a joined array. It is passing the tests but not the challenge. I'll check back later.

**Comment by reverseskydiver** [comment]
Can anyone post the correct code?

**Comment by BerkeleyTrue** [comment]
@royshouvik Is this still an issue?

**Comment by royshouvik** [comment]
This is not an issue anymore. I was able to successfully complete the challenge. Closing this one.

**Comment by albertrubis17** [comment]
function spinalCase(str) {
  // "It's such a fine line between stupid, and clever."
  // --David St. Hubbins
  return str.replace(/\B([A-Z]+\w)/g,' $1').toLowerCase().replace(/\s/g, "-").replace(/\_/g, "");
}

**Comment by hLeePage** [comment]
I added one part to albertrubis17's answer to account for something like the following:

function spinalCase(str) {
  return str.replace(/\B([A-Z]+\w)/g,' $1').replace(/([IA])([A-Z])/g, '$1 $2').toLowerCase().replace(/\s/g, "-").replace(/_/g, "");
}

spinalCase("ThisIsASpinalTapAndIThinkYouKnowIt")
