### ISSUE TITLE
[beta] Improve example for "Applied Visual Design: Use the u Tag to Underline Text"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#12986]
Challenge [use-the-u-tag-to-underline-text](http://beta.freecodecamp.com/en/challenges/applied-visual-design/use-the-u-tag-to-underline-text) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36</code>.

```html
<style>
h4 {
  text-align: center;
  height: 25px;
}
p {
  text-align: justify;
}
.links {
  text-align: left;
  color: black;
}
.fullCard {
  width: 245px;
  border: 1px solid #ccc;
  border-radius: 5px;
  margin: 10px 5px;
  padding: 4px;
}
.cardContent {
  padding: 10px;
}
.cardText {
  margin-bottom: 30px;
}
</style>
<div class="fullCard">
<div class="cardContent">
  <div class="cardText">
    <strong><h4>Google</h4></strong>
    <p>Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University.</p>
  </div>
  <div class="cardLinks">
    <u><a href="https://en.wikipedia.org/wiki/Larry_Page" class="links">Larry Page</a><br><br>
      <a href="https://en.wikipedia.org/wiki/Sergey_Brin" class="links">Sergey Brin</a></u>
  </div>
</div>
</div>
```

Much like #12831, I think the example used in this challenge could be improved. Since the `<a>` tags already have a underline, there's no clear change from adding the `<u>` tags.

What do you think about changing this challenge to ask campers to wrap the words "Ph.D. students" like `<u>Ph.D. students</u>`?

This text formatting makes no sense practically - **but it makes a better example.**

### To make this change:
* Update the instructions.
* Update the tests.
* Update the `challengeSeed` for the following challenges.

This PR #12860 demonstrates what this update could look like.

**Comment by official4code** [comment]
hello

**Comment by kevinleeleeedds** [comment]
stiffness Chan industry Bhutan Ellen it and hairy and some other parts

**Comment by HKuz** [comment]
@Greenheart - agreed, I think putting the tag on text to show the formatting helps show what it does better than placing it on the (already underlined) links. 👍  We can open this up as Help Wanted, or I could tackle it tomorrow morning 😄

**Comment by Greenheart** [comment]
I could fix this now, I've got nothing else to do :smile:

**Comment by HKuz** [comment]
Awesome 🎉

**Comment by Greenheart** [comment]
@HKuz Should I add `solutions` while I'm at it? I suppose they are used when running `npm test` to verify that all challenges in the seed works properly?

**Comment by HKuz** [comment]
You can add solutions 👍

**Comment by Greenheart** [comment]
@HKuz Nice, I'll fix that when I'm done with my current PR
