### ISSUE TITLE
Efficiency concern with Smallest Common Multiple

### ISSUE THREAD

**Issue by DIZAD87** [freeCodeCamp/freeCodeCamp#12985]
Challenge [Smallest Common Multiple](https://www.freecodecamp.com/challenges/smallest-common-multiple) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Hi, my code for the smallest common multiple challenge works but if I input numbers larger than 5, it gives me the infinite loop notification and the //noprotect takes too long.  If it isn't a bug, could it have something to do with the efficiency of my algorithm and how I am pushing and scanning an increasingly larger array?  I tried using more efficient methods like modulus or poping old values but I have only been able to max at an input of 7, as opposed to the 13 and beyond per the test cases.

My code:
```javascript
//In progress: It works but has problem with efficiency
function smallestCommons(arr) 
  {
    //Variable declarations
      var arr1 = []; //Values inside boundaries of arr
      var arr2 = []; //Multipliers of arr1
      var countDuplicates = 0; //Used to find match in arr2
      var result = 0; //Result dump

    //Sort and collect input values and dump to arr1
      arr.sort(function(a,b){return a - b;});
      for (i = arr[0]; i <= arr[1]; i++)
        {
          arr1.push(i);
        }
    //Increment multiplier and dump into arr2
      var j = 1;
      while(true)//
        {  //Multiply the values of arr1 and dump to arr2
             for (var k = 0;  k < arr1.length; k++)
              { 
                arr2.push(arr1[k] * j);
              }
          //Check for internal duplicates
            for (var l = 0; l < arr2.length; l++)
              {
                for (var m = 0; m < arr2.length; m++)
                  {
                    if (arr2[l] == arr2[m])
                      {
                        countDuplicates++;
                      }
                  }
              //Collect the result if there is a match equal to arr1.length
                if (countDuplicates >= arr1.length)
                  {
                    return arr2[l];
                  }                
                countDuplicates = 0;
              }
          j++;
        }
  }
smallestCommons([1, 3]);

**Comment by raisedadead** [comment]
@DIZAD87  Thanks a lot for the report. 

Have you tried confirming this as an issue on the forum or the chat rooms?
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [forum](http://forum.freecodecamp.com)

Happy Coding!
