### ISSUE TITLE
[beta] Improve instruction and formatting for "Applied Visual Design: Use the Text-transform Property to Make Text Uppercase"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#12987]
Challenge [use-the-texttransform-property-to-make-text-uppercase](http://beta.freecodecamp.com/en/challenges/applied-visual-design/use-the-texttransform-property-to-make-text-uppercase) has an issue.

Firstly, I suggest we change the first instruction sentence to
> The `text-transform` property in CSS is used to change the appearance of text. It's a convenient way to make sure text on a webpage appears consistently, without having to change the text content of the actual HTML elements.

Secondly, the **"Note"**-section is essentially a collection of definitions. I suggest we replace the current text with either a table of two columns (value - description), or format the css-values with `<code>` tags. Either way could work.

And finally: Maybe the word "uppercase" in the last paragraph should be formatted as `<code>`? Should this change also be done to "uppercase" in the message of the test case?

**Comment by HKuz** [comment]
@Greenheart - good points! For putting a `code` tag around "uppercase" - when I originally went through this section, I generally put `code` tags around CSS property names, and didn't around the values. (However, I'm sure there's some inconsistency throughout the section). I don't have a preference either way, it was just a convention I followed to keep my head straight during my QA 😃

**Comment by Greenheart** [comment]
@HKuz I generally use `<code></code>` or ```` as a way to highlight that something should be read as code, as long as it's related to syntax. I think this makes it clear what you actually can add to your software :blush:

**Comment by Greenheart** [comment]
I'll create a PR for this, and we can continue the discussion there.

**Comment by HKuz** [comment]
Fair points @Greenheart - and sounds good about the PR 👍
