### ISSUE TITLE
Arrow function description

### ISSUE THREAD

**Issue by Vozf** [freeCodeCamp/freeCodeCamp#12980]
Challenge [arrow-functions](http://beta.freecodecamp.com/en/challenges/es6/arrow-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

arrow functions are described as ()=>( return ... ) when actually they are ()=>{return ...}

```js
    
    
// change code below this line
var magic = function() {
return new Date()
}
// change code above this line
// test your code
console.log(magic());

```

**Comment by bigkatspence** [comment]
your code is not correct if you need help there is a help button that will take you to the correct chat for assistance also there is a full listing of chats available for help

**Comment by Vozf** [comment]
It is auto creation the code doesn't matter what matters is the description of a task
You describe them as 
```
() => (

// function body

return ;

)
```
which is wrong

**Comment by bigkatspence** [comment]
please take this to the proper chat room

**Comment by HKuz** [comment]
@Vozf - thanks for pointing this out 👍 . The example syntax was just raised over in issue #12978 so I'm going to close this as a duplicate (and as I noted over there, there's an open PR #12963 that will make this fix when it's accepted). Thanks for your help with QA on the new challenges!
