### ISSUE TITLE
Built-in higher order functions used (way) before their tutorial

### ISSUE THREAD

**Issue by DonaldCameron77** [freeCodeCamp/freeCodeCamp#12983]
#### Challenge Name: ES6: Arrow functions with higher order functions

https://beta.freecodecamp.com/en/challenges/es6/arrow-functions-with-higher-order-functions

#### Issue Description

In the descriptive text and example code for this challenge, the built-in higher order functions filter and reduce are used.  Then in the challenge, the camper is supposed to use map and reduce.

The problem is that, in the JavaScript tutorial sequence (map), the ES6 section is 5 sections before the functional programming section.  The motivated camper who has not been introduced to these built-in function will likely go off and read enough about filter, reduce, and map to understand what they have to do, but others may just get derailed at this point.  I suggest re-ordering sections to remove this "forward reference" and the attendant unnecessary friction in the learning process.

A possible fix: does any of the intervening material (up through the functional programming section) rely on ES6 features?

  If not, you could just move the ES6 section to after the functional programming section.

#### Browser Information

* Browser Name, Version: Google Chrome Version 55.0.2883.95 (64-bit)
* Operating System: Mac OS Sierra v. 10.12
* Mobile, Desktop, or Tablet: Macbook Air (13 in, mid-2011)

![screen shot 2017-01-30 at 8 58 40 am](https://cloud.githubusercontent.com/assets/6333249/22430157/65087754-e6ca-11e6-8430-e349738d8149.png)

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (100/100 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60166 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dnx2n-0003PD-5z
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:17 -0400
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:53892 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1dnx2W-0001ZJ-Cm
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:00 -0400
Date: Fri, 01 Sep 2017 18:15:59 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1504314959;
	bh=aAk3G4/Rrm6ZzN03F1KVEr3Dq/c3yLzo5pn5ZPs/fso=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=JLg04QxQqhbtwLNtJ5jU5gYkTdtrd/mMCGzh1GM2nrV5v9HsL7Xq/LdIr1EeCV0Ih
	 DIWpxIC5H3uFEBVM+7XfHP0H3hdraIU2jRAObdmM3TqNQUAh8+EqPejJ4HfPNalnfP
	 PfLBcpcz5a+8y8+VX39VDHaO4cA7qsBLfhNLDIdM=

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (120/100 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 22419 characters long; only the first
------ 5000 or so are included here.
Received: from mail-oi0-f53.google.com ([209.85.218.53]:36402)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx6L-003uHa-Ho
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:50:19 +0530
Received: by mail-oi0-f53.google.com with SMTP id t75so13925190oie.3
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:19:37 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=zluRBDZZ6DqwAzjmG9d+WZ6rgwo8LQp6VkUDQtZrDGY=;
        b=lcUiNESV8ppBioMwO+RWZXqxOJwnNYljmBSjC/ASktG4raSAYwSUELn5zpq26RKJr3
         gWRYmj429sjPC05Ftl7Ato9kAMnNjqrq82TUJ3wkGcYejRJOWiGZOtjdGxFQ2+ndIza5
         bIOAUAA/9OEo9l4KC8P5Qkf1OlYYI+NgIeJXySULZe+Mau2lYFtkjNE2qPyyy/7B6X/O
         HUb0rz4U0jqK+NjcBpJfRydqOyY3beC6d8xTQrnfrwbzEAvgEaA+2w+ZHOCsUdddtD49
         7SgQOA0taT9N8StE7+6DgS4UbukEkDbGLIe2udiJBBy2ZR3suMarEFY09EKpUlbOWaA+
         2Qdg==
X-Gm-Message-State: AHPjjUhVKs82s0tpTPauvjCfV88rPiI5zeTuPg2wtSFaoPzIDQnEkL50
	oVGhK+l99nNPT2aPOUcSwdvG0EmjjQmXWJL8clZgCg==
X-Received: by 10.202.245.67 with SMTP id t64mr3345971oih.19.1504315154867;
        Fri, 01 Sep 2017 18:19:14 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1354293ofe;
        Fri, 1 Sep 2017 18:19:13 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb6X4vacqAe4toffLWXNOknRY15/mqiVcRZe68RIBkdKPsUxXlBc3riab3So2LCKKaQSzyZp
X-Received: by 10.98.9.210 with SMTP id 79mr828619pfj.48.1504315153744;
        Fri, 01 Sep 2017 18:19:13 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504315153; cv=none;
        d=google.com; s=arc-20160816;
        b=LCSGe7aOU23qJTr8mIhw6SPVfJi2YqCbjjRsekX3QBBNdPohVapEnSHUsag/q7ofy9
         Sm6/KVpuvUUBawKfTerYWCwmTgehlME+DaTwlxcMoh8sR17m27suY77CJo25HIGV/FcV
         WykE+922BpM0Qj9Qd9zwEonidK1trq1tW/5yTPRup8r99nZ7QU/hkYLRAaZIzQxIE0Zk
         o8XpyzbYxWkr4SAQjavHLtg92Yi51VzG0CEi4jaicjhQXOwYX9omf8qc5f/NhkQVZ6df
         Kj01BAiQzrOc7U+7MqU0vO0+7+ooA/Sl8Hi340IX4tOale4hNODR5vSAPY6l1hzU9A42
         WxfQ==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=zluRBDZZ6DqwAzjmG9d+WZ6rgwo8LQp6VkUDQtZrDGY=;
        b=LewVV01e6KcaE7g0C2RRd/xHXDwkNbSS7VbaKg1/i/2nNPCyBFsG1NCqitjWpavUDD
         avyGYxEfwyG7q6kOFurcAeE2TC27S9yhZ1uOPfJ3MQDaE1kbgV6QqkAmT5rB+Bkot/tR
         krSeYlM9FvJqBb1JsgxBV5FHDYyzkh1cRoWV2ROmvuA4Y5KFgjzyvumuGhK248Q9H7RH
         3Dme0UNC3Eu703C8Iixc8u3hW1CCAO1bvTM1lUAUm9M3U2llc9YSo9hVEG7tltN9hOCr
         szOjm73GybE/fGzvZ6zgvWqoR3fjZQq+Z0N3cCUAJ3UYJeRrbTB0Ep9tyCJoopHBt6AN
         eoQg==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=nPPe63PQ;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=ZwV3tesU;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.10 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o5.sgmail.github.com (o5.sgmail.github.com. [192.254.113.10])
        by mx.google.com with ESMTPS id i5si1118105plk.97.2017.09.01.18.19.13
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:19:13 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.10 as permitted sender) client-ip=192.254.113.10;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=nPPe63PQ;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=ZwV3tesU;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.10 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=lYjHUA3kkHoCP3v/uQR1f1SRhOU=; b=nPPe63PQtXAq0bVP
	uoi6jjJ92raW/lvS/G1evB0s/ENMYVndjkXQL3ClcV1Obl/T1+St374ZTuIZZ5eF
	jhlaCuiODgzTiwfGWx7xLSpWqcvpE9NM5OI3SbZX2Fy+ydmYCY/lNcSnEsvqfkGe
	ojxJr29EOLU64GErMmnccBzYRGM=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=lYjHUA3kkHoCP3v/uQR1f1SRhOU=; b=ZwV3tesUUdSVv5c8Hs
	IyExpFdaZTJQA6fNKtSEWFeGjNa22v2NZv7NDDQ8Xt8SAHE+9V6cRs0+7rXdKgdQ
	zaSbCAlKFikD7cKnP9p9S64/L4BAriteRiPbqcXUqOEU3zbJf4hSs+6JcvLzo/f5
	C9B/PAo+LcgpJLEYI2L+1QETM=
Received: by filter0498p1las1.sendgrid.net with SMTP id filter0498p1las1-2982-59AA0710-B
        2017-09-02 01:19:12.446068936 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id jEUp7K6MSa-18xkFHUdbRQ
	for <pawan.ossindia@gmail.com>; Sat, 02 Sep 2017 01:19:12.374 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:19:12 +0000 (UTC)
