### ISSUE TITLE
Recent jQuery update

### ISSUE THREAD

**Issue by cdrainxv** [freeCodeCamp/freeCodeCamp#12984]
#### Issue Description

In attempting to clone a local instance of the fcc repo on my machine, I am prompted to choose
a version of jquery to list as a dependency when installing bower. I assume I am to choose the second option, but this would result in modifying the bower.json file. Later on, if I were to commit this change, would there be any issues stemming from this operation on subsequent PRs?
#### Browser Information

* Operating System: macOS Sierra

#### My Code

```
 Unable to find a suitable version for jquery, please choose one by typing one of the numbers below:
    1) jquery#~2 which resolved to 2.2.4 and is required by lightbox2#2.8.2
    2) jquery#~3.1.1 which resolved to 3.1.1 and is required by freecodecamp
    3) jquery#1.9.1 - 3 which resolved to 3.1.1 and is required by bootstrap#3.3.7

Prefix the choice with ! to persist it to bower.json
```

**Comment by dhcodes** [comment]
Confirmed. I saw this when setting up a local instance earlier this week. I believe it has to do with this recent PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/12605. Looks like we should update the `bower.json` file to add a resolutions section as below:
```
"devDependencies": {},
"resolutions": {
    "jquery": "3.1.1"
  }
```

Thoughts on this @BerkeleyTrue ?

**Comment by BerkeleyTrue** [comment]
LGTM
