### ISSUE TITLE
[beta] Responsive Web Site Challenge Videos not playing

### ISSUE THREAD

**Issue by masters-george** [freeCodeCamp/freeCodeCamp#12999]
I have tried to play the videos for the first two challenges to get the user stories to no avail. Getting error messages within the HTML5 player. 

#### Issue Description
clicking red Play button pops up the error immediately. The player id changes each time the user attempts to play the video.

#### Browser Information
Appears in both chrome and opera under Ubuntu Linux 16.10

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 N/A
 
```
#### Screenshot

![screenshot from 2017-01-30 22-27-05](https://cloud.githubusercontent.com/assets/24727860/22454535/5c673092-e73b-11e6-998c-dc2e8d91e9a7.png)

**Comment by raisedadead** [comment]
@masters-george thanks for the report, yes this is a known issue with beta site right now and the videos are pretty much work in progress.

What you see above are place holders, we should have them soon. Thanks for your patience meanwhile.

Happy coding!
/cc @QuincyLarson

**Comment by QuincyLarson** [comment]
@masters-george @raisedadead we are actually completely removing the videos and need to overhaul our challenge UIs accordingly. I will close this issue and create a new issue for this specific fix.
