### ISSUE TITLE
Friendly Date Ranges -- 4th Test Incorrectly Requiring Year in Second Element (while Requiring its Absence in the First)

### ISSUE THREAD

**Issue by bapinney** [FreeCodeCamp/FreeCodeCamp#1299]
Challenge http://www.freecodecamp.com/challenges/bonfire-friendly-date-ranges has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

According to the instructions, all parameters should be omitted in the 2nd returned element if those parameters have not changed compared the first returned element.

The first test that is run by the solution validator shows this:
assert.deepEqual(friendly(['2015-07-01', '2015-07-04']), ['July 1st','4th'], 'ending month should be omitted since it is already mentioned');
July is omitted in the 2nd element, because it is redundant (i.e., it has not changed and has already been mentioned).

However, in the forth test run by the solution validator, it is requiring the 2nd result to be exactly contrary to the instructions and contrary to what the first solution validator does:
assert.deepEqual(friendly(['2016-03-01', '2016-05-05']), ['March 1st','May 5th, 2016']);expected [ '2016-03-01', '2016-05-05' ] to deeply equal [ 'March 1st', 'May 5th, 2016' ]

While the first aforementioned test required the 2nd element to not have date parameters that are unchanged when compared to the 1st element, this test is requiring the 2nd element to have date parameters that it required be absent in the 1st element.

It seems the fix for this is to have the 4th test match for "May 5th" in the second element, rather than "May 5th, 2016".  This way, it would be in conformance with the instructions and the first test.

**Comment by Fantast** [comment]
Stumbled upon this myself. I agree with @bapinney that it should be just "May 5th" or maybe the problem text should be changed to clarify this...

**Comment by Gornstats** [comment]
Also ran into this problem, this test seems to be at odds with the others.
`expected [ code ] to deeply equal [ 'March 1st', 'May 5th, 2016' ]` should really be testing for a match against `[ 'March 1st, 2016', 'May 5th' ]`

Only workaround at present seems to be to hardcode this solution.

**Comment by benschenker** [comment]
It looks like this has been resolved. Please reopen if this is still an issue for you
