### ISSUE TITLE
"Run tests" button doesn't respond

### ISSUE THREAD

**Issue by Aleksey3107** [freeCodeCamp/freeCodeCamp#12991]
After task finishing and pressing "Run tests" the page doesn't show pop-up and doesn't unblock next level (task completed correctly + copy-paste method was used)
#### Challenge Name

https://www.freecodecamp.com/challenges/use-rgb-values-to-color-elements#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20rgb(255%2C%20165%2C%200)%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A

#### Issue Description

Change background-color from "#F00" to  rgb(255, 165, 0) and press "Run tests" button.

#### Browser Information

Opera Version:	42.0.2393.517
OS: Windows 8.1
Desktop
* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
<style>
  body {
    background-color: rgb(255, 165, 0);
  }
</style>


 
 
```

**Comment by erictleung** [comment]
@Aleksey3107 thanks for the issue, but your code is incorrect. That color was given as an example. Please read the test and instructions again to figure out which is the correct color to change it to. Happy coding!
