### ISSUE TITLE
Basic CSS: Intro - will no show complete on Beta site

### ISSUE THREAD

**Issue by rmdawson71** [freeCodeCamp/freeCodeCamp#12994]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/basic-css/introduction-to-basic-css

#### Issue Description

When I first click into the the challenge, I see an error message at the right bottom and also on the following 3 screens.  Also, once I have finished the challenge, it does not show on my map as completed.

#### Browser Information

* Browser Name, Chrome: 
* Operating System: Windows 8.1
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

![image](https://cloud.githubusercontent.com/assets/5313213/22447854/fdb8107e-e709-11e6-9212-349e2b331ac3.png)

 
 
 

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/5313213/22447840/e86f183e-e709-11e6-8a12-fb706c758eeb.png)

**Comment by dhcodes** [comment]
@rmdawson71 this has been fixed by a recent merged pull request and will be fixed when the beta site is next updated. Thanks for reporting!
