### ISSUE TITLE
Passing multiple ES6 challenges with errors

### ISSUE THREAD

**Issue by OFFLlNE** [freeCodeCamp/freeCodeCamp#12992]
#### Challenge Name
[ES6: An Immutable Object a const does not make](http://beta.freecodecamp.com/en/challenges/es6/an-immutable-object-a-const-does-not-make)

#### Issue Description
Tried random code if that works. It does give me tons of errors but did let me pass the challenge.

#### Browser Information

* Browser Name, Version: Chrome Version 52.0.2743.116 (64-bit)
* Operating System: OS X 10.10
* Mobile, Desktop, or Tablet: MacBook

#### Your Code
```
 const s = [ 5, 7, 2 ];
s[0,1,2] = [2, 5, 7] 
```
#### Screenshot
![image](https://cloud.githubusercontent.com/assets/8721312/22444545/0f1b6338-e74c-11e6-81a1-97e25b099a02.png)

**Comment by OFFLlNE** [comment]
Tried submitting my code w/o doing anything
[ES6: Arrow functions](http://beta.freecodecamp.com/en/challenges/es6/arrow-functions)
![image](https://cloud.githubusercontent.com/assets/8721312/22444615/5f90897e-e74c-11e6-8530-5f156bc5835c.png)

**Comment by OFFLlNE** [comment]
Aaand another. Starting to smell like a duplicate issue
[ES6: Arrow functions with input parameters](http://beta.freecodecamp.com/en/challenges/es6/arrow-functions-with-input-parameters)
![image](https://cloud.githubusercontent.com/assets/8721312/22444730/e83ebff2-e74c-11e6-8039-aaddd99df5e5.png)

**Comment by OFFLlNE** [comment]
[ES6: Arrow functions with higher order functions](http://beta.freecodecamp.com/en/challenges/es6/arrow-functions-with-higher-order-functions)
![image](https://cloud.githubusercontent.com/assets/8721312/22444841/5a1b8d44-e74d-11e6-9c45-89a4eedfb0b0.png)

**Comment by Greenheart** [comment]
@OFFLlNE The current tests mostly rely on RegEx ran against the camper's source code, but since the code is transpiled to ES5 before it's sent to the `fcc-test-frame` where the tests are run, the actual `code` variable that tests use always contain ES5 code. 

And as you can imagine, this causes some interesting behaviors with tests :smile:

Some of these could be related to the transpiling, but there's still a chance you've found some new bug here. Too tired to tell right now.

**Comment by OFFLlNE** [comment]
@Greenheart I will just keep posting those I find just in case :D
Some did work only after solving
[ES6: Spread Operator](http://beta.freecodecamp.com/en/challenges/es6/spread-operator)
![image](https://cloud.githubusercontent.com/assets/8721312/22445291/6f296196-e74f-11e6-90e2-0ab60de0e6b5.png)

**Comment by OFFLlNE** [comment]
[ES6: No Title Two](http://beta.freecodecamp.com/en/challenges/es6/no-title-two)

![image](https://cloud.githubusercontent.com/assets/8721312/22445387/dd39f5c4-e74f-11e6-98f1-24cf3a8becc3.png)

**Comment by OFFLlNE** [comment]
[ES6: Nested Object Destructuring](http://beta.freecodecamp.com/en/challenges/es6/nested-object-destructuring)

![image](https://cloud.githubusercontent.com/assets/8721312/22445934/b0e05e48-e752-11e6-991a-515f1a285f7a.png)

**Comment by OFFLlNE** [comment]
[ES6: Array Destructuring](http://beta.freecodecamp.com/en/challenges/es6/array-destructuring)

![image](https://cloud.githubusercontent.com/assets/8721312/22473503/d730029e-e7e1-11e6-93d2-b900d7ddf825.png)

**Comment by OFFLlNE** [comment]
[ES6: Array Destructuring with Rest Operator](http://beta.freecodecamp.com/en/challenges/es6/array-destructuring-with-rest-operator)

![image](https://cloud.githubusercontent.com/assets/8721312/22473597/11cac42a-e7e2-11e6-8c4f-e4d2e12c3878.png)

**Comment by OFFLlNE** [comment]
[ES6: Destructuring Function Parameters](http://beta.freecodecamp.com/en/challenges/es6/destructuring-function-parameters)

![image](https://cloud.githubusercontent.com/assets/8721312/22473710/6476e01e-e7e2-11e6-8317-656fbd8984b6.png)

**Comment by OFFLlNE** [comment]
[ES6: String Interpolation using Backquotes](http://beta.freecodecamp.com/en/challenges/es6/string-interpolation-using-backquotes)

![image](https://cloud.githubusercontent.com/assets/8721312/22473873/e3ad06f6-e7e2-11e6-995b-708b0e06179c.png)

**Comment by OFFLlNE** [comment]
[ES6: Enhanced Object Literals : Simple Fields](http://beta.freecodecamp.com/en/challenges/es6/enhanced-object-literals--simple-fields)

![image](https://cloud.githubusercontent.com/assets/8721312/22474806/b1e4677e-e7e5-11e6-852f-a07759777746.png)

**Comment by OFFLlNE** [comment]
@Greenheart

Seems that this bug still exists despite the new Live version.

**Comment by Greenheart** [comment]
@OFFLlNE I don't think we can do much about this at the moment though.

1. Tests are run against the transpiled code --> we can't test es6 specific things
2. Many tests are just placeholders - comments explaining what should be tested, which allows passing challenges without more than pressing the button

Looking forward to fix this issue! :blush:

**Comment by ladeyemi** [comment]
Has there been any movement on this, I'm having similar issue whereby no code inputted and tests are passing happened for the first few so far
