### ISSUE TITLE
Beta d3 SelectAll

### ISSUE THREAD

**Issue by benschac** [freeCodeCamp/freeCodeCamp#13006]
#### Data Visualization with D3: Select a Group of Elements with D3

http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/select-a-group-of-elements-with-d3

#### Issue Description

Code to solution doesn't show on screen until user clicks submit. This functionality is different from previous exercises where the output from your code appears before submit.
#### Browser Information

* Browser Name, Version: Chrome.
* Operating System: Mac
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 
 
 
```

**Comment by kevinleeleeedds** [comment]
Untitled

Ellieedds was born with me know thanks to work at five people that want
your phone number

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (110/100 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60214 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx3G-0003TA-1G
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:46 -0400
Received: from o1.sgmail.github.com ([192.254.114.176]:28686)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx38-0001sz-QQ
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:39 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=T5E4KIs1VEu5J03IVWrxyY9eJbc=; b=qJRGWgccp3ZITf2h
	iiIUbFV8t/iByZajafCjved7XK0y7U0tqpasEBBL7P2hwfWkF/x5LjCOxw2lFCsi
	XfMA00+7RO3KNgT5Ujddu1FBX+rZ4n18U4lM8Zlc/qcUr+RfmRYnB3DO7r8m/p6b
	YKZ8viKd0HFsIgfcwBA9koJpoEo=
Received: by filter0102p1las1.sendgrid.net with SMTP id filter0102p1las1-20807-59AA0675-2F
        2017-09-02 01:16:37.832084994 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id fHvWEvYyQBqxlpIXOHcnxA
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:16:37.725 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:37 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (110/100 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f52.google.com ([209.85.218.52]:32890)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx41-003myF-Id
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:48:04 +0530
Received: by mail-oi0-f52.google.com with SMTP id r203so13972357oih.0
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:17:13 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=reNpybDYNJNYav8f2pMA+AlXy7j93ZFq5u8BAWcKLyc=;
        b=j7spEKpQV1v/bBbIwWvVOvCA+OeAKialEGZMdAS3IIKxwFY0COJueVA81M70xsUtmS
         fYVixxNzBsUm82HuV8vHN2+7WvCjRiUnNlTuhViVcQj3n2fpbJOaFs7ia3i99iuJaYm2
         AkvqMXOHbogO043mDURwStVHXOc3/lNwB5uN0P4edavSxfePoyDBAEVrwS74ZZ7C99yc
         BHDg7Jmlv9Omi4PcrJ/f76PyhzrQeyVb9zkp0Db2TjNErVizx6OxEs/7xtJ6dOmlCH5f
         ZeO5VxmL2zUdjuddBiX9cWJtjHPv0AhKlLQaTMAGIFdpqeoaOWcvGUixWS5Qso1g/x7a
         qRgg==
X-Gm-Message-State: AHPjjUjfRLWh6mFQUBEWiMlIeUyPoLL04YKXyp/CXr8tCSANGK+KIVNT
	ADDxHqDR5cq8CrIH/9qfCkxQtXf/rOjlD1r9erxVuQ==
X-Received: by 10.202.83.12 with SMTP id h12mr4144347oib.35.1504315011293;
        Fri, 01 Sep 2017 18:16:51 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1352945ofe;
        Fri, 1 Sep 2017 18:16:50 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb5sQap9h1Ir0e9tESsJOpFoxq2JXOGkvgcqdPZE5Ynz8X1H9aYA5Sv0GzPZep3Y9IUaiQIA
X-Received: by 10.84.131.99 with SMTP id 90mr2806391pld.195.1504315010559;
        Fri, 01 Sep 2017 18:16:50 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504315010; cv=none;
        d=google.com; s=arc-20160816;
        b=E12L25MYOqH+nr0jcTuGVyDaFkmLKV5vn5dpe/47QfiMmXz/NdPrPwEJMYSv6s0Z+H
         hX5nnlVWButQGJ6I3K8SvIvElImkruwU9vvznVUW0MwNgbx2Sr3S+E7P/y/IqSsmGYHr
         bMJl4yrSCEkFfFS/C/l3mX0hFf6/+puM+hHE7DxsMvRc7oEWvCDNTKiW23bzgnPVY04M
         YbtorfYYeIZa91dJWRelxniVwrL7z0M/J4LoZZ8ZQUiRz6TZYmKvLJ7+VDwz87qeYCja
         Jf4wYbqMUKlpKWI8B0BD3Z30giFKeMfbq2EvDqMH4xKfClEcLUQ+vGNi+v6XZyn4na1H
         l5iA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=reNpybDYNJNYav8f2pMA+AlXy7j93ZFq5u8BAWcKLyc=;
        b=Y9WW2Z6pKjNFtKxvIm645qogrwCJvJ3BpiXWCyV020fmYkqmwFi6zk/KhACC3cnFAd
         NwT5YjvysAZ8rdwAwjuCumNbbbsgR6MQT8GK0nguc+wjMEpURTRU3gKTyqY1NpxLMl5q
         qEsfuh3G+L3LDbt4iHmYuOi5b1h9lgGGDU9enW1dUV3Cy1QjaQowSztdkDGnscmRqzm1
         2hTmCG2yNeaqaOgQFaZRleApdfznOPX+yOCsXWCaKOssAjLmCda2rmcVGz3xlFjzm7+l
         IaaKlm9oGG6ZypMMOtKt7SKwCC05STutk5AYLn/rhYiJfaVPc/QlzZSWxQ54cNK6Kkcj
         oiQA==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=ktCzhN9O;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=xgjljjz7;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.101 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o6.sgmail.github.com (o6.sgmail.github.com. [192.254.113.101])
        by mx.google.com with ESMTPS id 4si1053461pgc.347.2017.09.01.18.16.50
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:16:50 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.101 as permitted sender) client-ip=192.254.113.101;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=ktCzhN9O;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=xgjljjz7;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.101 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=BzD77mt7sqMcZdgGEsUFwTbF23Y=; b=ktCzhN9O3JEnENF7
	+Rxi1XmwrCtfYmZZZ4gMWrDRvA5o8w0nWhdcN4fRJkkv3jsfigTI9ol9FQrEDacd
	pxf257oRSJTqa9sW4dircwNpJ0UVFKGI2Zt4DR5Ps/6b+bTSuz2eydL2OiY05WsL
	06711p33abTudj294c9VSZRBMcE=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=BzD77mt7sqMcZdgGEsUFwTbF23Y=; b=xgjljjz7u3amhMqHer
	FCZNoUh/ks+2GtpnKxA2WSIaRK0J6g2KdtbFcQ5pJU01x/oQBiLpqrWF2cr1PRcj
	hKX8IkAIt5+flpApy53ZqwJ2EqQVwKGGRp97gE+salzeLBaAeCJGkdD+FaGLIaff
	s31/ADaOvchpMK5ggSnEdAaxM=
Received: by filter0493p1las1.sendgrid.net with SMTP id filter0493p1las1-9260-59AA0681-6F
        2017-09-02 01:16:49.999844787 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id b8zyS6bTQ06L_eXs0WzyQg
	for <pawan.ossindia@gmail.com>; Sat, 02 Sep 2017 01:16:49.958 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:50 +0000 (UTC)
