### ISSUE TITLE
Code runs without having to change anything

### ISSUE THREAD

**Issue by kalunlee136** [freeCodeCamp/freeCodeCamp#13000]
Challenge [spread-operator](https://beta.freecodecamp.com/en/challenges/es6/spread-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This is for the beta ES6: Spread  Operator challenge. All the tests pass if you click the 'Run tests' button with the given code. 

```js
const arr1 = ['JAN', 'FEB', 'MAR', 'APR', 'MAY'];
/* Alter code below this line */
const arr2 = undefined; // change this
/* Alter code above this line */
arr1.push('JUN');
console.log(arr2); // should not be affected

```

**Comment by OFFLlNE** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #12992, so I am closing it as a duplicate.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
