### ISSUE TITLE
Target the Parent of an Element Using jQuery

### ISSUE THREAD

**Issue by Cowwy** [freeCodeCamp/freeCodeCamp#13009]
#### Challenge Name
Target the Parent of an Element Using jQuery

#### Issue Description
Was not able to pass this challenge due to spacing issue with the correct syntax.
.parent( ) // with space inside the parenthesis causes incorrect answer.
incorrect response: $("#target1").parent( ).css( "background-color", "red" );
correct response: $("#target1").parent().css("background-color", "red")

**Comment by ajain17** [comment]
I can verify it on live site. I will work on this issue.

**Comment by Greenheart** [comment]
@Cowwy Thanks for reporting this! :blush:

This looks like it could be an issue with the test cases for this challenge. Was this on the [beta site](https://beta.freecodecamp.com) or on the [main site](https://freecodecamp.com)?

**Comment by Greenheart** [comment]
@ajain17 You're fast! I'll check the main site :smile:

**Comment by Greenheart** [comment]
I can confirm this for the beta site as well.
