### ISSUE TITLE
[FCC Beta]: Challenge is not passed even by providing the solution (Inline Style, Color-White).

### ISSUE THREAD

**Issue by shashank7200** [freeCodeCamp/freeCodeCamp#13005]
Challenge [override-class-declarations-with-inline-styles](http://beta.freecodecamp.com/en/challenges/basic-css/override-class-declarations-with-inline-styles) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

#My Code: 

```html


<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text {
    color: orange;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 id="orange-text" class="pink-text blue-text" style="color: white">Hello World!</h1>

```

![Bug Screenshot](http://i.imgur.com/9x1yA27.png)

**Comment by Greenheart** [comment]
@shashank7200 Thanks for reporting this!

I can reproduce this in FIrefox 51.0.1 (64-bit), but not in latest Chrome. This seems to be related to #12644

**Comment by shikhar0507** [comment]
I cannot reproduce in firefox 50.1.0 (64 bit) nor in Chrome 55.0.2883.87. Working for me in both the browsrs

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (106/100 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60193 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dnx2y-0003RF-Ed
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:28 -0400
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:41928 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1dnx2m-0001re-TO
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:17 -0400
Date: Fri, 01 Sep 2017 18:16:14 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1504314974;
	bh=Q4yv5g6Mj/nS948Jo+rYJYzx+84D0uJoAsFMBohTo2U=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=aU807HZQqgzO6UrD1j0j7Ys63xhEitZLwOG1aRyd3Fc6kWA0GONPyTOjyKXq/Oaj3
	 WEMo8Ng4cmlwptJMCVggPqL+B2D1sdkPt1rkJIjteNwjXmlGRCGyI07b8AJ/QRdr3X
	 Dln4cLghkP8QLlySQLNFjnvZItceOCwHib3FPsgM=

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (102/100 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f52.google.com ([209.85.218.52]:32797)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx3e-003kaj-36
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:47:20 +0530
Received: by mail-oi0-f52.google.com with SMTP id r203so13969113oih.0
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:16:49 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:date:dkim-signature:from:reply-to
         :to:cc:message-id:in-reply-to:references:subject:mime-version
         :content-transfer-encoding:precedence:list-id:list-archive:list-post
         :list-unsubscribe;
        bh=jQwOw59Du+QT1DznABbtTurIRSfbxxZQOtejCker1ys=;
        b=JM9YUx/kuu/OOrLkQvx/hC4C3V+E8yrkfm7ocXQF3C1MIBxv5KsrL6qjSKF5+RTxKf
         JlP+n/bp3iM4N4XjwVd5R4flhXfA6zlm7ZWDNX8R9oKFI9oR+jaDRWgUyDSiPcZv9J93
         eLRJwteV7kBOe6M95ds/Mvyhf7Vo8svw7Ont+yVdllBBLEizhJwVoQG7Wis7LrZmxjDZ
         aJmaDq1XvHbMWfQtAL6uGWIHDPkxczOsPhtq84smdD85duf8tEyrSSLFnu2Bvn3fehRR
         4h07+ohzBcghfUn17V0LbMTK5SWyJS5IV0pAUPgR1HROnJZL0aKyVsHmKTI01WgXKFJO
         8h/Q==
X-Gm-Message-State: AHPjjUhaBn1XwY/Mm53z05y9orZ6PW3SsiCh1NBK123eBitigdwRTUWz
	6CKThh3gjVNQoov9F/kTUMJM/1G2bSMMengrny8Kkw==
X-Received: by 10.202.179.137 with SMTP id c131mr3494695oif.298.1504314987598;
        Fri, 01 Sep 2017 18:16:27 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1352709ofe;
        Fri, 1 Sep 2017 18:16:27 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb4hD15TcFf/wICwvOxwCVLlEurPrAHKLaafBcrkNbhqsHhHygJIi3y2TyxRUvQPHi5fR59P
X-Received: by 10.200.56.1 with SMTP id q1mr5246425qtb.16.1504314986966;
        Fri, 01 Sep 2017 18:16:26 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504314986; cv=none;
        d=google.com; s=arc-20160816;
        b=uJsxeifD3XKJw5zfKB7IAWcwsEru1yjQGIgqYVYs9WkGvwxBpUARxxLX4yfk5fmABp
         vmlFEHE8IcoVDe8jYr+C58Nxr5Fi4MyhXMvhW8EVZkqyDCvk4uQ1McOL3Pf5ISyz7DY7
         DB0KTzV+bwTPydM71Ea2+gmnFKPOUXZnG2WNWDdJ7hXRQccu4CQmLoGM6WWN0nCHddtQ
         PBj922XW6kPDR6Tua4tX6iVTGUhyX62rKzouOnjZbj0dAxf0yE6d24eZnXmF+TmGHtXX
         QDitTrpiVkPN0ribM5Spq7vnOGsXKS2SSQ9BVEcTagE83/3LHIWKwDETIdRcKHl1Mc+p
         VVbA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:dkim-signature:date
         :arc-authentication-results;
        bh=jQwOw59Du+QT1DznABbtTurIRSfbxxZQOtejCker1ys=;
        b=wiegi3CMgdvFv5kbEVTAZOA7ep0IrvA+Ok66mvc+B9tsASfSsu70TVNGtRTm8VLsFE
         VzovMK4ZVIxOcDEuP0wEKsNz/FY9uSZdZ3ZKsaqJYzWx7+keg+RMt+2ThD9hIMYdU1y6
         ke/ZcowxkA8dRfKrqjCYK8ilAbPPyAuYIZEpUp1gFCyWOf2ab1x8p+OTJ4WqkH3fGDqi
         P1HgH9hRBLZqY8rhUEJ83rl/DzBsyo46A861MJu3VlmpFD7K8ee3rB8+Vk52Up2GQsKF
         eYtpt94Dt8Vwo9NaZMJSkoby7MPlsaOWnQREu4O6elZVbW9uP9QF5Rnr1ZG4bhnKBMRs
         l4rQ==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=Auit/Ggh;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.198 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2-ext7.iad.github.net. [192.30.252.198])
        by mx.google.com with ESMTPS id p87si145260qkp.36.2017.09.01.18.16.26
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:16:26 -0700 (PDT)
Received-SPF: pass (google.com: domain of noreply@github.com designates 192.30.252.198 as permitted sender) client-ip=192.30.252.198;
Authentication-Results: mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=Auit/Ggh;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.198 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Date: Fri, 01 Sep 2017 18:16:25 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1504314985;
	bh=jQwOw59Du+QT1DznABbtTurIRSfbxxZQOtejCker1ys=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Auit/Ggh2HLdH/eoCAv46uByOr1LdcpG9nbL86Zf459wl3K8295A9pL+LXo59JU00
	 rGU5b4h/ertvCOH+b583bwRyTUTvtbYZojEP/F8zWk0xKbD/qLNWey06fxDA9sHcG2
	 MMtnLhPtDDrwbrB2VNUdLI/jtsu8t0tSszwnhXYc=

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (118/100 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 22612 characters long; only the first
------ 5000 or so are included here.
Received: from mail-oi0-f51.google.com ([209.85.218.51]:33398)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx67-003tYb-Uo
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:50:04 +0530
Received: by mail-oi0-f51.google.com with SMTP id r203so13989287oih.0
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:19:23 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=30c5UfnaPxdXve0BZZ9it2QHMYjrURg8OpoWb6OZuXM=;
        b=KAIIRM3i0HrEY20r/0c429r7g6E1nwtimswpj2trpYHQH724NYKS64VqB6zq5N9XSC
         itfy6l4/38Sn5+NtjFc5UnlfLFQ/L8t6PuE5sbDMcbBgUoNtyPCvd6D8swubdzKtM6Pn
         PdyNyY2XjVP0w6B9OrJxQg1aCkyup6HUV5fDsEtQMvuFuRM9oOkKgVEK2ncZcjxgJbv8
         1mGdTrM38PiuVK01bImQgeymYAt+piFYK4deVZ+oW3RmoOUnx3p5EkAr+FZGJcYsMfYp
         bRBstT9HVfY1d1FBxDYCsu+MN7EwGz0DVbDPy6Nf+9nQByPbcXsK8xe5KdCRJW2nM8C2
         QJZg==
X-Gm-Message-State: AHPjjUh3Ksyf2aTpdKOuGFNx9uok9GOBpHtqz1LemmW9stKyn8JS3Lf7
	RG7UZPxdSCEwBh220WuLOhPfnv5YGxwqGSAbNCMsqw==
X-Received: by 10.202.213.68 with SMTP id m65mr4700436oig.25.1504315141204;
        Fri, 01 Sep 2017 18:19:01 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1354176ofe;
        Fri, 1 Sep 2017 18:19:00 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb6auKkTRnqEFNJEL3MUrxpuORa/8HX0s/ztLJQesEvBObt3mQxgxJS5xHPFnNpIaoeDt+7M
X-Received: by 10.107.131.215 with SMTP id n84mr2748594ioi.269.1504315140154;
        Fri, 01 Sep 2017 18:19:00 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504315140; cv=none;
        d=google.com; s=arc-20160816;
        b=C0hZ1pylMAC+Vfo0UcRMf8pd0ZHOEzD+xluzDU2J7Bebo+/uPHENlyiHo6toKaBZEe
         AGxZcJlUWzgy9vCceb6grZNAw4B9giSjmHZaTQM+zx6r9h7ExVNkIaG8vnJgmQIsXCay
         5rvh5bPgU6yAoHM7lcKR0xf4uot7eEuoe4OgZSYd1t1NysGoNrUX4OOCKOiX1TWcHZX3
         tVklhvTYhE7AMzZmo2UeUhhr4AddOEhwdqFbaHkQCvzpMPg9yYmMKzwWOM9ygi5zy2Oq
         IPby2PYZyhdvdeGpKe4K3P1GP8DYX90sC2N0FnBb1IzdWGy8tIZsXd/8+6cmvQjI0osr
         y+1Q==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=30c5UfnaPxdXve0BZZ9it2QHMYjrURg8OpoWb6OZuXM=;
        b=p8YsrRKvbqOuhto3QND8Q/97Gau50h82Javax9epjMlHYDo+qIQsMf41GEPhY/G4lz
         RQeOhqz9LlP3t5aiLuqA5oCw2NJrCP+L9KdnDoooL9zlsjSJabhs6tyuVajqQLQQh9ed
         YE41LHCf+pr6w9lWlGDva++U6+5hNJugXq1//tPsSB3AZ/Ky/CI+u47dx8BH5eO+ghf9
         KNDqwhk8AymwzSq8BonhZPpbIkKGEawK/H0boG/fwN9X+ni/DrgFw9SA+52N381O9eqH
         8j90oqB7y4n7hnR0GuipCu2lRdZdYfGnyHk1xGvNmSGj73CZPDwyqB/TcdssJ6lXTBBI
         0WPA==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=jCY6bcER;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=hOnHiQUu;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.199 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o8.sgmail.github.com (o8.sgmail.github.com. [167.89.101.199])
        by mx.google.com with ESMTPS id y19si1247686ita.148.2017.09.01.18.19.00
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:19:00 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.199 as permitted sender) client-ip=167.89.101.199;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=jCY6bcER;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=hOnHiQUu;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.199 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=bscfRs7WN5p78CUuK0QhsopNrd4=; b=jCY6bcERZLn0kAta
	K6vhKKCZa5YmKYdtAduzD5lolI81jhGledrT5xBd4K6Y5TbPBqyE3jcEgLGm4rSv
	kGOOiJg4x99v4OWM6Xjol5ucdE195s1s6dhIPzlaY0Ix810Mt4VW0PyFcDbugRld
	KxulHY5P7PVkg46qYGz7BQ4pNcI=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=bscfRs7WN5p78CUuK0QhsopNrd4=; b=hOnHiQUunGkcTKDlqQ
	CKRfO9QqcoH09wJOcClFMBHJ+Ii84ezLWXDEjqy1ffPYIxkJpMhZ5nDGc2A6mf/U
	pgCO3IEz/EN63HbMcD3IVzEyG9LbW5OrTYT9IDmmWUTs06HgFzSCMb+NoCKmwHy4
	rm5XMLzNP/4toT8W5YzUy/70Y=
Received: by filter1081p1mdw1.sendgrid.net with SMTP id filter1081p1mdw1-18590-59AA0704-3
        2017-09-02 01:19:00.02193343 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0040p1mdw1.sendgrid.net (SG) with ESMTP id oihNMPruQ-KsiCvwebA7Xg
	for <pawan.ossindia@gmail.com>; Sat, 02 Sep 2017 01:18:59.900 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:19:00 +0000 (UTC)

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (121/100 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 39744 characters long; only the first
------ 5000 or so are included here.
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60355 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx7E-0004eo-RK
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:20:53 -0400
Received: from o6.sgmail.github.com ([192.254.113.101]:5531)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx6t-00024M-2Q
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:20:32 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=uvyKSoDMsVHo0k82HDEz67qV+4s=; b=ZXyB8xh8v6cTjx1+
	OIB+PV0ZKun0QrMWcd42FdSBB2I/w7lXxJ8imBNtrbGsnw+BjaXjMcXB4n8qp7aE
	ghvj80ZX+FIxEMaWGGzIOpKuVsknrq294yWbHOuBNOSLdESs2iHajMjCq2dTXPg5
	fxkm4D1AlzVoyjfc2ae27wlR8go=
Received: by filter0212p1las1.sendgrid.net with SMTP id filter0212p1las1-31605-59AA075D-E
        2017-09-02 01:20:29.960647144 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id zLNXDBxCQNOcHnVziPrYdw
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:20:29.868 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:20:30 +0000 (UTC)
