### ISSUE TITLE
Beta: Default HTML/CSS output is not rendered on the right

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/freeCodeCamp#13015]
#### Challenge Name
Applied Visual Design: Adjust the Width of an Element Using the Width Property
[Challenge Link](http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-width-of-an-element-using-the-width-property)

#### Issue Description

I just started doing some of the newer additions in beta, and it seems like when you begin a new challenge, none of the current HTML/CSS code is rendered on the right, by default.

For instance, for this particular challenge - without seeing what a "card" actually is, this instruction doesn't make much sense - 

> Add a width property to the entire card and set it to an absolute value of 245px. Use the fullCard class to select the element.

I need to click "run tests" to first see the current output, then go back and read the instructions again. Then click "run tests" again with my own code. This seems counter-intuitive. 

I'm not sure if this is a bug, or this is the intended behavior, but this is not the default setting in the current production site.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 55.0.2883.87 m
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![122](https://cloud.githubusercontent.com/assets/11348778/22487523/bd0a7030-e7db-11e6-8be8-bf9d369939e7.png)

**Comment by OFFLlNE** [comment]
@Manish-Giri Thanks for reporting the issue.
This look similar to #12807. So I am closing this issue as a duplicate.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
