### ISSUE TITLE
Mention Linux screen sharing alternative in WayPoint 'Pair program on bonfires'

### ISSUE THREAD

**Issue by sidneygijzen** [FreeCodeCamp/FreeCodeCamp#1301]
The description states to use Screenhero. This is, as mentioned in the description, only available for Mac and Windows. As an avid Linux user, I was looking for an alternative and I found [this Tweet](https://twitter.com/freecodecamp/status/527307756773314560) from @QuincyLarson which says that "*...our Linux users are screensharing with Skype*". However in the chat rooms I see a lot of people mentioning TeamViewer (and there's also now an official Gitter chat room for that!).

It appears that TeamViewer is the FCC standard for Linux, as Screenhero is for Mac and Windows, so I would like to propose to mention this in the waypoint description. This way other campers know to expect either Screenhero or TeamViewer.

It is unfortunate though that Screenhero doesn't have Linux support. They're working on it, but [postponed it since they're moving their client into Slack](https://twitter.com/screenhero/status/423209856061804544).

**Comment by benschenker** [comment]
Closing as stale, I don't believe there is a `pair program on bonfires` waypoint anymore.  Feel free to reopen if this is not the case
