### ISSUE TITLE
How do I start?

### ISSUE THREAD

**Issue by light-house** [freeCodeCamp/freeCodeCamp#13019]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by dhcodes** [comment]
@light-house make an account on [www.freecodecamp.com](www.freecodecamp.com) and then click on Map. Closing this unless you want to reopen it and add details.

**Comment by no-stack-dub-sack** [comment]
@light-house When reporting an issue, please provide some level of detail so we know how to help you. If you have a general question, please visit the [forum](www.forum.freeCodeCamp.com) or our [Gitter chatrooms](https://gitter.im/FreeCodeCamp/home).

If you are looking to get started with the freeCodeCamp curriculum, please visit https://www.freecodecamp.com/email-signup
