### ISSUE TITLE
Cant pass due to zoom

### ISSUE THREAD

**Issue by glennbennett** [freeCodeCamp/freeCodeCamp#13018]
Im on an android phone and the challenge is telling me to change the font size but its not letting me pass and telling me that i have to change my zoom to 100% and i have it as far out as i can

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
 
 
 
```

**Comment by dhcodes** [comment]
@glennbennett since you're on android, it's more likely that there is a non-breaking space issue. Try removing all the spaces from the css you add. See https://github.com/freeCodeCamp/freeCodeCamp/issues/12574
