### ISSUE TITLE
Unable to Setup the Cloud9 account for NODE JS Tutorial

### ISSUE THREAD

**Issue by seenu511-hcl** [freeCodeCamp/freeCodeCamp#13024]
Hi Team ,

I have started the tutorial for Node.js when tried to setup the Cloud9 IDE i am facing the payment issue for this do  we have any workaround for this .(see an attachment)..  please do needfull asap.

![ccard](https://cloud.githubusercontent.com/assets/21247881/22500551/e6ae3782-e88a-11e6-82f2-302166ce7a8f.PNG)
 
Thanks,
Srinivas.

**Comment by hisener** [comment]
Actually, you should be able to create one private workspace and unlimited public workspaces in c9.io free plan. So, you do not have to upgrade. Check your dashboard, maybe you have already a private workspace.

https://c9.io/pricing

**Comment by seenu511-hcl** [comment]
i can't able to setup for free its my first time registration don't no why i cant signup freely to use that IDE what might be the rootcause for it..?

Need Help..

**Comment by raisedadead** [comment]
Please check #12071
