### ISSUE TITLE
[beta] Improve challengeSeed for "ES6: Scopes and the var keyword"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13025]
#### Issue Description
The editor shows an error for line 6 of the initial `challengeSeed`, stating that we shouldn't create functions within loops. We can avoid this by moving this function definition out of the loop and only reference it in the loop.

Updated `challengeSeed`:
```js
var newCampers = [{camper: "Wil"}, {camper: "Sam"}, {camper: "Dav"}];

function roleCall (i) {
  return "Camper # " + (i + 1) + " has arrived.";
} 

// only change code below this line
for (var i = 0; i < newCampers.length; i++) {
// only change code above this line
  newCampers[i].roleCall = roleCall.bind(null, i);
}

console.log(newCampers[0].roleCall());
console.log(newCampers[1].roleCall());
console.log(newCampers[2].roleCall());
```

However, this also means we lose the closure that gives us access to `i`. Since code isn't supposed to be written like this anyway, I think we're better of by using `roleCall.bind(null, i)`, despite the increased complexity. The code above works just like the previous example, but uses better (if not best) practices.

Even better, @BrendanSweeny suggested this could further be improved:
```js
var newCampers = [{camper: "Wil"}, {camper: "Sam"}, {camper: "Dav"}];

function roleCall (i) {
  return "Camper # " + (i + 1) + " has arrived.";
} 

// only change code below this line
for (var i = 0; i < newCampers.length; i++) {
// only change code above this line
  newCampers[i].roleCall = roleCall.bind(null, i);
}

console.log(newCampers[0].roleCall());
console.log(newCampers[1].roleCall());
console.log(newCampers[2].roleCall());
console.log(typeof i);
```

By adding a `console.log()`, the camper **can see** that using `let` will cause `typeof i` on the last line to be `"undefined"`.

@BrendanSweeny also had an idea about adding an extra test to verify that `i ===`. I think this is a good idea.

Building upon Brendan's test case from https://github.com/freeCodeCamp/freeCodeCamp/pull/12956#discussion_r98820528, this could be what we're looking for.
```js
assert.isUndefined(i, 'message: <code>i</code> should not be available outside of the <code>for</code> loop.');
```

**Comment by BrendanSweeny** [comment]
Hey @Greenheart . I played around with this a bit more. With this code:

```
'use strict';
var newCampers = [{camper: "Wil"}, {camper: "Sam"}, {camper: "Dav"}];
function roleCall(i) {
  return "Camper # " + (i + 1) + " has arrived.";
}
// only change code below this line
for (var i = 0; i < newCampers.length; i++) {
// only change code above this line
  newCampers[i].roleCall = roleCall.bind(null, i);
}
// test your code
console.log(newCampers[0].roleCall());
console.log(newCampers[1].roleCall());
console.log(newCampers[2].roleCall());
console.log(typeof i);

// Tests from es6.json
"tests": [
        "assert.isUndefined(i, 'message: <code>i</code> should not be available outside of the <code>for</code> loop.');",
        "assert(newCampers[0].roleCall() === \"Camper # 1 has arrived.\", 'message: <code>newCampers[0].call()</code> should call the index of the first camper');",
        "assert(newCampers[1].roleCall() === \"Camper # 2 has arrived.\", 'message: <code>newCampers[1].call()</code> should call the index of the second camper');",
        "assert(newCampers[2].roleCall() === \"Camper # 3 has arrived.\", 'message: <code>newCampers[2].call()</code> should call the index of the third camper');"
      ]
```

While I believe the test you shared should work, I can't ever get that test to pass. When I change `var i = 0;` to `let i = 0;`, `i` is still a number according to the chrome devtools console, which makes me wonder if there is a transpiling issue here (babel transpiles `let` to `var` possibly?). However, if `let i = 0;` is included in the code on page load, devtools console will log `i` as undefined, but that test still won't pass...

A completely different idea is something I adapted from an example using let on MDN:

```
// Instructions: Fix the code so that i declared in the if statement is a separate variable than i declared in the first line of the function

function checkScope() {
  var i = "function scope";
  if (true) {
    var i = "if statement scope";
    console.log(i);
  }
  console.log (i);
}
// Only change code above this line
checkScope();
```

**Comment by Greenheart** [comment]
@BrendanSweeny There are transpilation issues at the moment. We can't run tests against the original ES6 code yet, we only get the transpiled output.

I like the your example, it's a lot cleaner since it focuses on `let` vs `var` rather than adding complexity around. This is definitely worth thinking more about! :smile:

@freeCodeCamp/moderators Should we simplify this challenge by using the example @BrendanSweeny suggested in the comment above?

**Comment by HKuz** [comment]
@Greenheart and @BrendanSweeny  - my two cents is I'm a fan of the simpler example. It shows scope in a very clear way. The drawback of the earlier example using `.bind` is that seeing it would probably confuse the folks who are working through fCC as their first introduction to JS. (I don't think it's introduced in the Basic JavaScript section before the ES6 one). 👍

**Comment by Greenheart** [comment]
@HKuz It's not introduced anywhere (AFAIK) :cry: It's a really nice language feature.

If we want to use the simpler example, we'd need to update both the seed as well as the instructions.
@BrendanSweeny Would you like to create the PR for this, as you came up with the solution? :relaxed:

**Comment by BrendanSweeny** [comment]
Absolutely! I'll create a PR sometime this weekend.
