### ISSUE TITLE
[beta] OOP Section - some challenges will solve with NO code (if solved once first)

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#13021]
I'm curious if anyone can reproduce this... Take this challenge for example:

http://beta.freecodecamp.com/en/challenges/object-oriented-programming/create-a-basic-javascript-object

If I solve this challenge, but then 'X' out of the modal and stay on the page, I can then change or even completely clear the code and the challenge will still pass. This is not locally, this is on the beta site. I can then even navigate away to a new challenge, come back (saved work of no code is loaded), and the challenge will still pass.

Most of the challenges in this section seem to exhibit this behavior. I can see this causing problems if someone solves something, then wants to try another way to solve it, sees that is passes and mistakenly thinks that their second solution is also correct.

#### Browser Information

* Browser Name, Version: Chrome, latest
* Operating System: Mac OSX 10.11.6
* Mobile, Desktop, or Tablet: Desktop

![image](https://cloud.githubusercontent.com/assets/18563015/22494430/6e7b246c-e805-11e6-9142-1d459f853c92.png)

**Comment by Greenheart** [comment]
I can confirm this for `Chrome 56.0.2924.76 (64-bit)` but not in `Firefox 51.0.1 (64-bit)`.

Nothing appearing in the console.

**Comment by no-stack-dub-sack** [comment]
@Greenheart any idea what the issue might be? Nothing looks terribly different in the seed code to me except no `tail` - could that have something to do with it?

**Comment by Greenheart** [comment]
@no-stack-dub-sack No idea ^^

**Comment by no-stack-dub-sack** [comment]
cc / @freeCodeCamp/moderators anyone else have any insight on this one?

**Comment by QuincyLarson** [comment]
@BerkeleyTrue do you have any idea what could be causing this?

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson 
cc / @freeCodeCamp/moderators 

Has anyone else come across this? Noticed this issue was still open and I just confirmed that it still exists, but I'm wondering if no one else has encountered this, maybe not a big deal for now?

But if we are getting closer to shipping Beta, and we do want to work through issues like these, good time to bring up old ones that may have gotten away from us.

**Comment by erictleung** [comment]
@no-stack-dub-sack I can confirm this bug still exists for this challenge and I'm on `Chrome Version 58.0.3029.110 (64-bit)`. But I can't reproduce it on `Firefox 53.0.3 (64-bit)`. 

This seems like an odd edge case that people might stumble upon accidentally. Not sure how many times I would erase all my code and just submit anyways. But nonetheless, this isn't something that should be expected. I wish I could assist on this issue, but I don't think I have enough know-how to fix it.

**Comment by raisedadead** [comment]
This is now resolved, thanks.
