### ISSUE TITLE
Pig Latin Challenge - tests do not cover edge cases

### ISSUE THREAD

**Issue by delbertlegg** [freeCodeCamp/freeCodeCamp#13027]
@Greenheart I was reviewing old submissions and noticed that my implementation did not correctly return words that are all consonants (such as "my") or where the first vowel appears at index > 2 (such as "phrase"), but did pass all the tests provided. Recommend adding these edge cases to the test suite (can get crazy like adding "schwartz" or something like that).

Offending solution (no judgement...I was learning JS at the time :) ):

```
function translatePigLatin(str) {
  var vowels = ['a', 'e', 'i', 'o', 'u'];
  for (var i = 0; i < vowels.length; i++) {
    if (str.charAt(0) == vowels[i]) {
      str+= "way";
      break;
    }
    else if (str.charAt(1) == vowels[i]) {
      str = str.slice(1) + str.charAt(0) + "ay";
      break;
    }
    else if (str.charAt(2) == vowels[i]) {
      str = str.slice(2) + str.substr(0, 2) + "ay";
      break;
    }
  }
  return str;
}

translatePigLatin("phrase");
```

**Comment by Greenheart** [comment]
@delbertlegg Thanks! Could you edit your post and include the solution that causes the faulty behavior? I need it to reproduce :blush:

**Comment by delbertlegg** [comment]
@Greenheart Done!

**Comment by Greenheart** [comment]
I can confirm that the test cases don't handle all edge cases yet.
* `"schwartz"` would be a good test case for handling vowels with index > 2.
* `"rhythm"` would be a good test case for handling words with only consonants.

I think the following test cases could solve this:
```js
assert(translatePigLatin('schwartz') === 'artzschway', 'message: Should handle words where the first vowel comes in the end of the word.');
assert(translatePigLatin('rhythm') === 'rhythmay', 'message: Should handle words without consonants.');
```

@delbertlegg Do you want to fix this and submit a PR? If so, [this guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) could help you set up a local environment and get started.

To fix this issue you just reported, you need to add the test cases from above to the [`tests` array of this challenge](https://github.com/freeCodeCamp/freeCodeCamp/blob/b92d3cc62585afb0a6457d81849c27c7ff8a5e6b/seed/challenges/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting.json#L515-L521). See the existing test cases for reference.

To see test your changes in the local instance of freeCodeCamp, stop the `gulp` command (if you have it running), run `node seed` (to tell FCC to use your updated version of the challenges), refresh the challenge in `localhost:3000` and press the **"Reset"** button to clear browser storage. After that, you can verify that the solution below passes all tests...
```js
function translatePigLatin (str) {
  if (isVowel(str.charAt(0))) return str + "way";
  var front = [];
  str = str.split('');

  while (str.length && !isVowel(str[0])) {
    front.push(str.shift());
  }

  return [].concat(str, front).join('') + 'ay';
}
  
function isVowel(c) {
  return ['a', 'e', 'i', 'o', 'u'].indexOf(c.toLowerCase()) !== -1;
}
```

...and that your solution from the first post of this issue fails.

If you need any help, feel free to leave a message in the [Contributors room (Gitter)](https://gitter.im/FreeCodeCamp/Contributors) :blush:

**Comment by delbertlegg** [comment]
I'd be happy to fix it. I'll work on it this evening...thanks!

**Comment by masters-george** [comment]
The instructions for the beta version  of the challenge also need to tell the camper how to handle words that have no vowels (e.g. merely append "ay" at the end of the word).
