### ISSUE TITLE
[Beta] Spanish Translation Error

### ISSUE THREAD

**Issue by hudsontaylor** [freeCodeCamp/freeCodeCamp#13037]
#### Challenge Name

Not applicable.

#### Issue Description

In my account settings, if I switch my account language to Spanish, an alert pops up saying, "Your language has been updated to 'Spanish'". It seems like an oxymoron to tell someone in English that the language has been switched to Spanish. Shouldn't it be "Su idioma se ha actualizado a 'Español'" instead?

#### Browser Information

* Browser Name, Version: Version 55.0.2883.95 (64-bit)
* Operating System: OS X El Capitan
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js
 
 
 
```

**Comment by erictleung** [comment]
@hudsontaylor thanks for the issue. Agreed, switching to a different language should have all the notifications also in that language.

[This area of the codebase](https://github.com/freeCodeCamp/freeCodeCamp/blob/9581beb05ea467332187725e4e6d37282a8c07f6/server/boot/settings.js#L47) is where that change needs to go.

**Comment by raisedadead** [comment]
@erictleung IMHO we should be adding a json resource, starting with keys for the notification like this, and could be further expanded to the translation efforts of the other "message" strings, etc.

**Comment by erictleung** [comment]
@raisedadead even better! :+1:

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (109/100 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60213 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx3F-0003Sq-2u
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:45 -0400
Received: from o8.sgmail.github.com ([167.89.101.199]:64843)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx36-0001sx-QR
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:37 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=KPmXodriahVA7VQyV7kxi0B6bxc=; b=mnJCoRGwwfYda5le
	3yrlvq3ZorotJIx1LQKEm+LhLn0b7p0JuXluoz5JTAtgCG+ua/pnNmxlkNKHmtBg
	gXOsvOJVpIFyzcQXCf6+4K6mZJW6kZrwIGc8+1CQE+m5xJ6wcp11dW23BPhCL5LX
	8XyLwFNKgzhMz0M603/o3Ty1l5Y=
Received: by filter0040p1las1.sendgrid.net with SMTP id filter0040p1las1-14386-59AA0673-2F
        2017-09-02 01:16:35.947935163 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id GVIcpj9YSe-RS-FXbbDSjQ
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:16:35.778 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:35 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (109/100 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f45.google.com ([209.85.218.45]:36854)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx40-003mut-Da
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:48:01 +0530
Received: by mail-oi0-f45.google.com with SMTP id t75so13905956oie.3
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:17:11 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=1Qf5kl3czUV6M7o96LN+jCYM9ex/KaKPeM+2Qk2p214=;
        b=pmlAp30jWyuLZfKhqmsRk48t0xKwJrmCqd6hOv9RSqyKkmpdzRaAhztwgXk4VgHvyK
         J1mKMOjb8H4DkdnHq6kxqzo2voMaCWXU4qWvZ7kevGQ0LCFFGRt8cAtUQEtLSqsGrjXG
         e9bmMF5kiD3ZEI0ISV03O+T7rTkb4rmLggXU3vHW0ZRQ8T4yBUrall9o87AA9DtAPoty
         94Z7RXPxZiVrLg7fbzchS/IoOPNEjhHMbbVwPe0NRA1TcevwcDvD4kT4dhBuhgogdjn6
         jbEMsVeD1clLFrk4M5tu8woB8708YAuWrBFdC3UxEiD3DmcjRXSnyoyzDz4gCZ5/ESp6
         vjpA==
X-Gm-Message-State: AHPjjUgQHZZwt/7qVOh6XO/tY3YhD/tYYU3ai/QQmG9B9Ms7KM2mx/Ty
	Mg9NuOI6uWFburpGGWnqeWwyqJVyAk9w54xU860/Cw==
X-Received: by 10.202.72.17 with SMTP id v17mr3395200oia.127.1504315009951;
        Fri, 01 Sep 2017 18:16:49 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1352931ofe;
        Fri, 1 Sep 2017 18:16:49 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb4VPsXTO3AKsHvoRWkva8u2O5VjEeSispCNndOFpJ0OKvn4tVyJPDIZCnbT4rG9Lzzo2Lv+
X-Received: by 10.36.181.77 with SMTP id j13mr1180083iti.163.1504315009197;
        Fri, 01 Sep 2017 18:16:49 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504315009; cv=none;
        d=google.com; s=arc-20160816;
        b=gwEQaYQ5fwY4ziKdObzmSx+H4T+2qQHeSG/Y4ylxdMfGgqLpir+3VO+QEyJb8O0SGc
         EWITs27rOV6f3ssuLGEm8zgkiE3xepxwlSKpVbw0OdRQSxNprWovsfBRuLxsEUtoGfm5
         pYpj49nz1RufL8bt2RQcWWMRWtxe5rh34hlx21lZuU8QTZXO/3xSI1v79b2ScWohUII1
         JaLoNowhxfM2GIhCDgfHXtk04J879w9ewROWIam76NgaXeCTbo3KNgYFjozYqh/uQaU5
         +84m/YHlujWdq1EjfX3YjDFlNXU83s6l+Ei2Uew6cPbDIqSnPX0nHf5TX9Xiah24ONS+
         1L1w==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=1Qf5kl3czUV6M7o96LN+jCYM9ex/KaKPeM+2Qk2p214=;
        b=Gy8CHXwnTXejLkSYZ/JDITtnKtoigzEGn9mAa3k2GqTA/tM4TklwV4JXaUKDLFmx+n
         jIPPOiwZYENdmohjgBdsFAtyva1JBV24nJuvOF6cVi0b1tm76ICA8ySPHllbNXUjO1D3
         iOUvW96gwBjVz+xvnLjDWcWgSXJVPd6BzS59n9aYmBIDfLBo2MrkK6nWntSuWFYHK+0F
         82itVUJmDKmxoBVyL9x5RhhuBsxI1sxonRQzYUWI95jmOswAjPu9EzLzM/Jap38uWWGV
         pQahQALjki8Ouhh7xNIbUck/8O7pl58xijnwaAGfjtTa8X3mW4+iOb7MbbvBj2W8DsgP
         up7A==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=wK07lEgD;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=lsnyB9GN;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o3.sgmail.github.com (o3.sgmail.github.com. [192.254.112.98])
        by mx.google.com with ESMTPS id f12si1272398itc.144.2017.09.01.18.16.49
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:16:49 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) client-ip=192.254.112.98;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=wK07lEgD;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=lsnyB9GN;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=S/ysnb5AP6AKgTXJO10oUUR5mMc=; b=wK07lEgDB/b5CONI
	Pwy2Hlk3zW7WdhrbQ7vsbk/nGaJi5EE8/V5RAuYAqu4TPvZXOX3ABwt6wHzHG+ZV
	TS0CSaht88sGGzRxqOBb58qOtoBceFpcpU0ruLJYXns330735Y8JFhOROvykYdjg
	Se1/+k1l3sLOO1rEIvsADtBJx7c=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=S/ysnb5AP6AKgTXJO10oUUR5mMc=; b=lsnyB9GNHLxc4wQCKB
	sK+NPFTa1uD6CwyJGk0iSwBTTvuamwqDxV8jJCa2PkYjOjrOYCPiDY3Z9OnJUH1X
	dSexj0YwkZtnUiO4IM05kNNyp/ry6X5GDlEowNdKificdQE+xp3aF4KWUzsJTdFy
	EEG3zkqgYTiBGDu2Us/bs/wMk=
Received: by filter0916p1mdw1.sendgrid.net with SMTP id filter0916p1mdw1-20768-59AA0681-4
        2017-09-02 01:16:49.070654342 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0025p1mdw1.sendgrid.net (SG) with ESMTP id 2fwcTRwgSo6jP8DaGnINGg
	for <pawan.ossindia@gmail.com>; Sat, 02 Sep 2017 01:16:49.115 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:49 +0000 (UTC)
