### ISSUE TITLE
[Beta] Challenge Editor/Result Conflict

### ISSUE THREAD

**Issue by hudsontaylor** [freeCodeCamp/freeCodeCamp#13036]
#### Challenge Name

http://beta.freecodecamp.com/en/map

#### Issue Description

I have noticed that each time I move onto a new challenge the old code still displays on the iPhone screen even thought the code in the text editor is completely new. For instance, if my previous challenge displays a blue box on the iPhone, but my new challenge starts off with code for a red triangle (or something), the iPhone still displays the blue box. I think this may be as simple as refreshing the iPhone result screen each time a new challenge is loaded.

#### Browser Information

* Browser Name, Version: Chrome Version 55.0.2883.95 (64-bit)
* Operating System: OS X El Capitan
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js
 
 
 
```

**Comment by Greenheart** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #12807 and #12859, so I am closing it as a duplicate.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
