### ISSUE TITLE
ref site doesnt work for almost a month

### ISSUE THREAD

**Issue by tsalexey544** [freeCodeCamp/freeCodeCamp#13038]
Challenge [No repeats please](https://www.freecodecamp.com/challenges/no-repeats-please) has an issue.

The ref site doesnt work for almost a month
https://www.mathsisfun.com/combinatorics/combinations-permutations.html

I advise changing it to khanacademy video tut and wikipedia

**Comment by ajain17** [comment]
Hi @tsalexey544 , are you unable to load the site https://www.mathsisfun.com/combinatorics/combinations-permutations.html ? Its loading fine for me.

**Comment by tsalexey544** [comment]
hi @ajain17, yes. I am located in russia. When I open it I get 

> Error 522. The initial connection between Cloudflare's network and the origin web server timed out. As a result, the web page can not be displayed.

**Comment by ajain17** [comment]
I am able to access it. Try deleting your cookies and clearing your cache and see if that helps.

**Comment by Greenheart** [comment]
@tsalexey544 I'd recomend you to search for the terms "Permutation" and "Combination" - there might be other resources that could help you. If not, feel free to ask in any of our [chat rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or in [our forum](https://forum.freecodecamp.com).

Good luck, and happy coding! :blush:

Closing this as not related to FCC. Thanks @ajain17 for the triage :ok_hand:
