### ISSUE TITLE
Tutorial keeps getting killed in Cloud9

### ISSUE THREAD

**Issue by txsrangers** [freeCodeCamp/freeCodeCamp#13033]
Challenge [Manage Packages with npm](https://www.freecodecamp.com/challenges/manage-packages-with-npm) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

When you get to the 8th tutorial in Cloud9, "Publish", when you press enter, all that happens is that "Killed" displays on the screen. I assumed that it was because they removed that tutorial from the program because I was able to run the 9th tutorial, BUT that was the only one I could run after #8. I was able to successfully complete 1-7, but 8 and 10-13 all just display "Killed" when you click on them.
![screen shot 2017-02-01 at 10 48 19 am](https://cloud.githubusercontent.com/assets/20232282/22516841/bf09e834-e86c-11e6-8f5b-ba46fdcd9a4d.png)
![screen shot 2017-02-01 at 10 48 42 am](https://cloud.githubusercontent.com/assets/20232282/22516842/c14bca7c-e86c-11e6-8711-3793d7387a51.png)

**Comment by dhcodes** [comment]
This is a duplicate issue.

**Comment by dhcodes** [comment]
@txsrangers Unfortunately, freecodecamp does not manage the 'how-to-npm' series and these exercises will be replaced with some that freecodecamp contributors have created. If you want to open an issue regarding this, the best place would be the [how-to-npm repo](https://github.com/workshopper/how-to-npm/issues).
