### ISSUE TITLE
[beta] Clarify Instruction for "Regular Expressions: Match Characters that Occur One or More Times"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13045]
Challenge [match-characters-that-occur-one-or-more-times](http://beta.freecodecamp.com/en/challenges/regular-expressions/match-characters-that-occur-one-or-more-times) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36</code>.

This is not a bug, but something I suspect could confuse people.

I think the second sentence of the following example
![clarify](https://cloud.githubusercontent.com/assets/6125097/22531599/4da374a0-e8e2-11e6-817e-d6bdaac9a518.png)

could be clearer if it was changed to
> **Because of the `+`, it would also find a single match** (...)

Also, the next sentence could be slightly changed, and moved to it's own paragraph to make it easier to read.
> If it **instead** were checking the (...)

**Comment by Manish-Giri** [comment]
ooh, missed this. Will do this too!
