### ISSUE TITLE
[beta] Improve Instruction for "Regular Expressions: Match Single Character with Multiple Possibilities"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13044]
Challenge [match-single-character-with-multiple-possibilities](http://beta.freecodecamp.com/en/challenges/regular-expressions/match-single-character-with-multiple-possibilities) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36</code>.

```js


let quoteSample = "Beware of bugs in the above code; I have only proved it correct, not tried it.";
let vowelRegex = /[aeiou]/ig; // Change this line
let result = quoteSample.match(vowelRegex); // Change this line

```

This challenge asks me to "count the number of vowels". This made me think I should add `.length` to the expression evaluating to my `result` variable. Adding `.length` fails the tests, while leaving it out lets me complete the challenge.

Since the challenge isn't testing for a numerical value in the result variable, I suggest that we change the instruction and first test case to only ask campers to **find all vowels**.

To fix this, update the final sentence to 
> ...to find all vowels in the string `quoteSample`.

and update the message of the first test case:
`assert(result.length == 25, 'message: You should find all 25 vowels.);`

**Comment by erictleung** [comment]
@Greenheart ah I must have been a little lazy to mislead people in the instructions 😆  This change sounds good to me.

**Comment by Greenheart** [comment]
@erictleung It happens to the best of us! :wink:

**Comment by Manish-Giri** [comment]
I'll do this too, since the change sounds similar to the other two..
