### ISSUE TITLE
[beta] Missing semicolons in challengeSeed for "Regular Expressions: Find One or More Criminals in a Hunt"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13049]
Challenge [find-one-or-more-criminals-in-a-hunt](http://beta.freecodecamp.com/en/challenges/regular-expressions/find-one-or-more-criminals-in-a-hunt) has an issue.

```js

// example crowd gathering
let crowd = 'P1P2P3P4P5P6CCCP7P8P9'

let reCriminals = /./ // Change this line

let matchedCriminals = crowd.match(reCriminals)
console.log(matchedCriminals)

```

**Hey, contributor!**
* See #13047 for more detailed instructions on how to contribute

* Add semicolons to [each line with code](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/regular-expressions.json#L451-L456)

Happy coding! :smile:

**Comment by mohit122** [comment]
// example crowd gathering
let crowd = 'P1P2P3P4P5P6CCCP7P8P9';

let reCriminals = /C+/ // Change this line

let matchedCriminals = crowd.match(reCriminals)
console.log(matchedCriminals)
