### ISSUE TITLE
[beta] Missing semicolon in challengeSeed for "Regular Expressions: Find Characters with Lazy Matching"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13047]
Challenge [find-characters-with-lazy-matching](http://beta.freecodecamp.com/en/challenges/regular-expressions/find-characters-with-lazy-matching) has an issue.

```js

let text = "<h1>Winter is coming</h1>"
let myRegex = /<.*>/; // Change this line
let result = text.match(myRegex);

```

The first line of the `challengeSeed` for this challenge needs a semicolon to prevent the editor from showing a warning when the challenge loads.

If you want to fix this, please read [CONTRIBUTING.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) to get started.

When you're all set, add a semicolon to [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/regular-expressions.json#L423) and make your commit.

If you have any questions, please come chat with us in the [Contributors Chat Room](https://gitter.im/FreeCodeCamp/Contributors).

Happy Coding :smile:

**Comment by ankitdwivedi23** [comment]
Hi, I would like to fix this issue.
