### ISSUE TITLE
[beta] Fix <code> formatting for "Regular Expressions: Find Characters with Lazy Matching"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13048]
Challenge [find-characters-with-lazy-matching](http://beta.freecodecamp.com/en/challenges/regular-expressions/find-characters-with-lazy-matching) has an issue.

As shown in the image below, the final sentence is formatted as `<code>`.
![code-format](https://cloud.githubusercontent.com/assets/6125097/22532336/d5097206-e8e6-11e6-812e-5926ac928c81.png)

Fix this by moving the `<code>` tag to come just after `["titani"]` and before the `.`
This should be updated to something like this:
`<code>["titani"]</code>. It finds the (...)`

**Comment by Manish-Giri** [comment]
@Greenheart I'll do this..
