### ISSUE TITLE
[beta] Improve Instructions for "Regular Expressions: Ignore Case While Matching"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13043]
Challenge [ignore-case-while-matching](http://beta.freecodecamp.com/en/challenges/regular-expressions/ignore-case-while-matching) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36</code>.

It feels like these two sentences could be combined into a shorter alternative.

> There are other flags but here you'll focus on the flag that ignores case.
> 
> The flag that ignores case is the i flag.

I suggest we replace the sentences above with
> There are other flags, but here you'll focus on the one that ignores case - the `i` flag.

**Comment by erictleung** [comment]
Sounds good to me. I wrote these instructions and thought it would be nice to preface the introduction with some motivation. But I also like conciseness 👍  

So the third paragraph should now read

> You can match both cases using what is called a flag. There are other flags, but here you'll focus on the flag that ignores case - the `i` flag. You can use it by appending it to the regex. An example of using this flag is `/ignorecase/i`. This regex can match the strings `"ignorecase"`, `"igNoreCase"`, and `"IgnoreCase"`.

**Comment by Manish-Giri** [comment]
I'll take this up..
