### ISSUE TITLE
[beta] Clarify instruction for "Basic Data Structures: Access an Array's Contents Using Bracket Notation"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13056]
Challenge [access-an-arrays-contents-using-bracket-notation](http://beta.freecodecamp.com/en/challenges/basic-data-structures/access-an-arrays-contents-using-bracket-notation) has an issue.

### Hey, Contributor!
In the final paragraph of the instruction, I think the contents of the parenthesis could be slightly clarified.

I suggest we change "(1st index)" to `(index 1)`, as "1st index" could be interpreted as the first index of an array - **index 0**.

If you want to fix this, please read [CONTRIBUTING.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) to get started.

When you're all set, replace [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json#L91) with the following, and make your commit.

`"In order to complete this challenge, set the 2nd position (index <code>1</code>) of <code>myArray</code> to anything you want, besides <code>\"b\"</code>."`

If you have any questions, please come chat with us in the [Contributors Chat Room](https://gitter.im/FreeCodeCamp/Contributors).

Happy Coding :smile:

**Comment by no-stack-dub-sack** [comment]
@Greenheart agreed! Looks like we're on a first-timers-only roll tonight!

**Comment by Greenheart** [comment]
@no-stack-dub-sack Indeed! More to come in the coming days :smile: 

This should probably be a first-timers-only as well, if we add better instructions.

**Comment by phapp88** [comment]
I would like to fix this issue.

**Comment by rudolphh** [comment]
It isn't showing as completed, with a green check mark.  though all tests do pass.

**Comment by Greenheart** [comment]
@rudolphh Could you post your code here, to help us reproduce? :blush:

**Comment by rudolphh** [comment]
let myArray = ["a", "b", "c", "d"];
// change code below this line
myArray[1] = "h";
//change code above this line
console.log(myArray);

**Comment by Greenheart** [comment]
@rudolphh Thanks!

I can get this code to pass in both Firefox 51 and Chrome 56. Can try if it works after doing a hard refresh of the challenge page (CRTL+SHIFT+R) and then pressing the "Reset"-button? :blush:

However I noticed another issue - the messages for the test cases needs to be updated (I'll submit a quick PR for this right away).

**Comment by rudolphh** [comment]
did the hard refresh and reset. still the same.  using chrome 56

**Comment by Greenheart** [comment]
@rudolphh Hmm... That's weird :smile:
