### ISSUE TITLE
[beta] Missing semicolon in challengeSeed for "Regular Expressions: Match Beginning String Patterns"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13050]
Challenge [match-beginning-string-patterns](http://beta.freecodecamp.com/en/challenges/regular-expressions/match-beginning-string-patterns) has an issue.

```js

let rickyAndCal = "Cal and Ricky both like racing."
let calRegex = /change/; // Change this line
let result = calRegex.test(rickyAndCal);

```

**Hey, Contributor!**
* See #13047 for a more detailed instruction on how to get started.
* Add a semicolon to [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/regular-expressions.json#L484)

Happy coding! :smile:

**Comment by dnahol** [comment]
I'm taking this
