### ISSUE TITLE
[beta] Consider splitting "Regular Expressions: Positive and Negative Lookahead" into two challenges

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13051]
Challenge [positive-and-negative-lookahead](http://beta.freecodecamp.com/en/challenges/regular-expressions/positive-and-negative-lookahead) has an issue.

Since this challenge has a pretty long instruction and covers two topics (positive and negative lookahead), I think we should consider splitting this into two separate challenges.

**Comment by HKuz** [comment]
@Greenheart - I can get behind splitting this challenge into two. It's one of the harder topics in Regex to wrap the head around, and may be easier to digest as two smaller challenges. 👍

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (102/100 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60171 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx2t-0003Q7-RK
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:23 -0400
Received: from o1.sgmail.github.com ([192.254.114.176]:22273)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx2m-0001rc-EQ
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:16 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=gvqrp2csIu73ctTH/PmoXBdl5uY=; b=OCaI8605ZybPKCkW
	LbQEXuktGrR4kqIl3gYARdlbtKjSl4h/geI9aKwouESmIHmUJOGK5gFvPb4yPtoC
	7V+Q5Kz/5y5jb3mlGlgde80nWDifwtPIgBTLaBkt9mM76pEu9ziZUvThjWVdauKp
	5+7uPEgHJTIo4NGrjI1MipUVLnI=
Received: by filter0546p1mdw1.sendgrid.net with SMTP id filter0546p1mdw1-27260-59AA065F-1F
        2017-09-02 01:16:15.421359025 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0037p1mdw1.sendgrid.net (SG) with ESMTP id wmxa7Nw-SzKRo6HdNqcKYw
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:16:15.431 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:15 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (103/100 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f46.google.com ([209.85.218.46]:35838)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx3f-003kjW-1X
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:47:24 +0530
Received: by mail-oi0-f46.google.com with SMTP id n18so13974206oig.2
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:16:50 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=W3zwrRHT91aSazq7fL+Y0kj33O89tjOyZ2J+BHrml84=;
        b=e1ZtuFSdhKR9PK1wM91HTJFr+EdieDlbbHL2mtczrLRReif1/cEqQ7BQfZroR+T2U4
         bviaRUharSLU4QmiQJeI9W48J7vGA3l2rt2rLs0zkPLjdGJExVWoToJ7VI2EoYE7A1wA
         PhVuQJoCCqGdUGrkU3RUQ46hF+HEAHUsV3qgf8ILavhlNgKlA2uEa/0XkSo4oX6+7Gs6
         mvFiPSP3wiZ9B1prVGhDvCH1lpKYVh17bBBy2S1TKfS6POBjpAwk40+MtZ1y2eOeoRmP
         6Dt3s+ImgiJLZO0IJ5ymIfXQXxrH/B5vZ/njQBQtTBAZ9w3+HvZmfKlC9O7O1ZEKNqpT
         EQkg==
X-Gm-Message-State: AHPjjUjkqlrLeA59xgDrtfr6y6Y7AYwjtahW1HlcM2Mqylvb9ODFxlQc
	LPctOOF0wAjuK9iiXmHDadQswPV5Olzrch6OGg/ouA==
X-Received: by 10.202.213.69 with SMTP id m66mr4174778oig.274.1504314988787;
        Fri, 01 Sep 2017 18:16:28 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1352723ofe;
        Fri, 1 Sep 2017 18:16:28 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb76qVXzBP6g7T2EdFAvpEKFfPeqomeI4TCUlpVXntUd4iGuj52HXWoY6nqkegvd29g3NhUD
X-Received: by 10.98.214.145 with SMTP id a17mr541483pfl.14.1504314988012;
        Fri, 01 Sep 2017 18:16:28 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504314988; cv=none;
        d=google.com; s=arc-20160816;
        b=YUtUJB0cvGQw5TlYl5LmZLh27v+Y0a6pfhCKWlP1xBGDRB/eQl43SezBejGC8tCBsX
         o3c33UKwZ8ho248w1mpa6CY5fx+xw71H3lvLgk6izd+TbdsDaSJ1/5eZ6lIsg00if6DC
         9B9Eeq5AcT77LwlWdV8HC6f3CG7K3Zu3tPTj1H4D6oCnIJ2cieHsVSz15N3OxXdz0Imy
         YW/wPOu05HBsG9GqEhx41uIEkqX/QFDqSHTNtKp+ofn6QI/eNuXuCwNGwhTTQRzHb7z9
         KB4O6/Y59t8BrQ8p2XO6gZF0XxWYs/1Cwl6eaYyP5W1QrnKL8o7Cyf5E/X2F8XZZIKLB
         fjlg==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=W3zwrRHT91aSazq7fL+Y0kj33O89tjOyZ2J+BHrml84=;
        b=uHK3rRxgtwTJppWl8yUx2toFPNRU1XsR/zbhfe6rTUmB+VDHPmAQ3ZOpPmcv/q+nlj
         bkgYnrlFvu4GuOuxfHrW3JbJvL8lL8R+DfNiAABSM4I2haM9niV6V1P0on6av0xJXdj6
         bVXDHcjhsYdpaCrcYHrJrpa4GTu18XgA6I1u8YbXWaj0DUdJ5I9gG6pFyonrkj8eM9Oc
         c6Q2/f+KUYenhNdQRib3p6y7FFX+a9ZO04jeRvirkGCnq8r3Xnpsz4JJr2hrmmKj2EIN
         MqX0MHChcGaWMSJpJjg+02CdF/Y4s65oQ8vMB4Q+LC9JDiYYarPtr+ca4G4DH3APObbD
         YDVQ==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=tFkeEoyW;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=h7TU6Tue;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.202 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o11.sgmail.github.com (o11.sgmail.github.com. [167.89.101.202])
        by mx.google.com with ESMTPS id 74si1017772pfa.476.2017.09.01.18.16.27
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:16:27 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.202 as permitted sender) client-ip=167.89.101.202;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=tFkeEoyW;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=h7TU6Tue;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.202 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=OMOKLHMJ5Qu+dLxDRyoJH8f9r/o=; b=tFkeEoyWUqXUE0BU
	9kaFRK7FRlm+EeW7N78juzJGY6IPDFs7rLHCWHKInt4300WORU3qwiHFbY6K4o4h
	lgqgUdFzrPezDCDJGioilSPORnOvO9uZW9wRUglhBNnQ3N5rbXHndFYnzO6zCOGz
	gHfwn1mlHxqH+i42JavmgeYH6gY=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=OMOKLHMJ5Qu+dLxDRyoJH8f9r/o=; b=h7TU6TuepDeWRN1tNY
	IxDw0D5SLT34HG/M3i8oo4TGfuM0au7IG3sZGa95PIwJABQ44JK+jiGeHTNLLupB
	22e8F09S+4M5NEpaEpQGHSPH/UaYMLzbHG8SKKLalE1YcXu2m06d9BlzLg7HZe5W
	Elplm/b9qxLZ/gmkdEslbxiuE=
Received: by filter0300p1las1.sendgrid.net with SMTP id filter0300p1las1-20194-59AA066A-3D
        2017-09-02 01:16:26.894268109 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id 0IFJqiWzSIy-sL4yMxJaEQ
	for <pawan.ossindia@gmail.com>; Sat, 02 Sep 2017 01:16:26.714 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:26 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (116/100 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 25104 characters long; only the first
------ 5000 or so are included here.
Received: from mail-oi0-f42.google.com ([209.85.218.42]:33361)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx5y-003syf-DY
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:49:49 +0530
Received: by mail-oi0-f42.google.com with SMTP id r203so13988091oih.0
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:19:14 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=oFRKWQwN4q76hDHailLOixDFK/r9ktEGeHhR5agaQug=;
        b=eA28vBRfTf4asMk5WDdeC2W/d1hpMqut1BK/2+Nelnd2EdqgOoMsgwL+/m1z1MCePo
         2rGDUZkEEvD+U8WBsJt+A9UslM9F8tHur1RJzb+5IOBaVlEKtWgNtyG4p+Eqgj4oJ7rf
         132wlRGM0D+4Fl16ae7cREv689f9G9WbhA6Hv/znk4MrpCRcodkJmXr2161ouDvbjf+F
         0mJ3H0wYpqggWmQIzoeTdo8Usd0lVU1B8Jl2GSmpiwldgiB8X/1IBNE/6K2bRdwizqvn
         5zJoElqPEdthtlCE9FlDRejQtoRiWKUKxP9mmMayyiyHgiU5svZxWZs9owrNBcuT5D2B
         COIQ==
X-Gm-Message-State: AHPjjUjqTBCGrmw0swpgUCxGoaYQj0mPHxQUdBowDKlVxCuN08AJegGJ
	TxJCNc/72PPH4Bi9ViKhpYocE0jL3oraKEw2m2bxCw==
X-Received: by 10.202.72.17 with SMTP id v17mr3300365oia.129.1504315131941;
        Fri, 01 Sep 2017 18:18:51 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1354097ofe;
        Fri, 1 Sep 2017 18:18:50 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb71PqR40K/Cg4YOy8pn41a/SrDTxqBhS+vOSaqtarfDDOTwG3awwPMES+l7lSfdWGUjfE0y
X-Received: by 10.98.58.73 with SMTP id h70mr4269042pfa.27.1504315130868;
        Fri, 01 Sep 2017 18:18:50 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504315130; cv=none;
        d=google.com; s=arc-20160816;
        b=RSkt/ALIOGW9JXajraHK8NOe/Q4YVIopPtYaWkJA/jUk5l9wYaxV3FTmhqnt5KRHaP
         2+eLuC9CKKNjksOgd86XUltL0BPZyum7d8XnimgQfTtHR657WBLHvJQMrrkkpUr3wqNE
         /7cazDva/vN7gtSEMVbj21hIbMrsdDqOVWPl/lKbR5MEWvS2fnE7q/6spDpWabpeOVLp
         VGLwrIoHr4yvlX1pXhYT+yOS26sWDUT4aaDOHl663EagRfBCFoGikPRqurKpsfB0pNRJ
         Ie+cJZTFlHQRc30NET8LBb/JqpZ5L+w/xUHaUP01+iD1R2f08G49PnUk6S8mVCn678ju
         0vYg==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=oFRKWQwN4q76hDHailLOixDFK/r9ktEGeHhR5agaQug=;
        b=YGt6/B/CKf9CLch2bTjS9G3PvCx7S/05HC7rjuVXNb54c/1NCLVDdNGPWn89EeJr4w
         LcKAaEOTH+G4kPf86eDaJIZYSowBge8ehCGDfmVNrkPcsFv5e0118W9UKpth4Z+rNheC
         S2VWb1t46ioZIxB7/ei8ROGQQq3vixGl9q0jRVR31bEpCZW3C+7ILFJ+WulKwEun+9AG
         VUlHtZnWfQSvq4z+BGeP5aL6iJEK9NIPVd8ludftaDAcGbootz+Hk9UD2ZhNDNdXwGCj
         SsNDBAn6GSSg9kYtCUY+14j33L1yF++xFUqPCshOCHvbQXpdKZi5wy73SQGgvpnQMGUt
         fpMQ==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=IQlRTGvs;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=O/62Ezh6;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.10 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o5.sgmail.github.com (o5.sgmail.github.com. [192.254.113.10])
        by mx.google.com with ESMTPS id s126si1069196pgc.656.2017.09.01.18.18.50
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:18:50 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.10 as permitted sender) client-ip=192.254.113.10;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=IQlRTGvs;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=O/62Ezh6;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.10 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=77qMR57qIz2nvGZa4Q03vcWSBVM=; b=IQlRTGvsNO/PudRc
	RFO4RviXz8i/UX7bxs3UN5UAJfS6CbsDgMN0KjUWl+SPJLxBvcKg+R+gy8xFw7qw
	v9RAuvWIzCZ85I53HElDF3IrmUjqQCPSY7q48MZSCcvlRdLHQ5zJ3nTpVktmztHU
	MvEvSIl56e7ogmEkUzGdv/meZho=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=77qMR57qIz2nvGZa4Q03vcWSBVM=; b=O/62Ezh6FYsxGZtsxC
	3tpo0dtBPrxVY91pSsHQKSb3L1yDnpDNpRWoUSsu15Lsjr+yLO/1pqBMtvOLmwx7
	cpevRLJEMeax3qri87MCQviJZcTD4IZG61q3r58emcdDaQgMaXzrHgzupPMkc0Sb
	Io9WQvWl0mzh3ZWWRYNBzgGxY=
Received: by filter0206p1las1.sendgrid.net with SMTP id filter0206p1las1-8332-59AA06FA-C
        2017-09-02 01:18:50.279657138 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id ApEpDWfFQzKrz4wKSzk8_A
	for <pawan.ossindia@gmail.com>; Sat, 02 Sep 2017 01:18:50.143 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:18:50 +0000 (UTC)

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (117/100 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 45495 characters long; only the first
------ 5000 or so are included here.
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60344 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx77-0004dp-Ky
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:20:45 -0400
Received: from o1.sgmail.github.com ([192.254.114.176]:10701)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx6f-00023Z-1b
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:20:17 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=1msr4aDFyoT2HHh6bgJ2sUjz8xk=; b=bH4lC/swNT3fvxDP
	bNUon/3Q+OusIlLbSx3kGKJQUdmy0S3aNDscBLbNUFE/macutfNWWmcQJ75fndG5
	fc+6w6TZRzAVkUvmiQpVoodoLMFDImScL12E3EC+YR35FMFUZNh0MbeKDa6QoYrI
	nMsrg1+bz5y0s5jaMomgQNYBrXo=
Received: by filter0467p1mdw1.sendgrid.net with SMTP id filter0467p1mdw1-22588-59AA0750-1
        2017-09-02 01:20:16.192445203 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0029p1mdw1.sendgrid.net (SG) with ESMTP id wRA1VEypQ8mHeQ_8pS1yxQ
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:20:16.138 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:20:16 +0000 (UTC)
