### ISSUE TITLE
[beta] Fix formatting for "Regular Expressions: Reuse Patterns Using Capture Groups"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13053]
Challenge [reuse-patterns-using-capture-groups](http://beta.freecodecamp.com/en/challenges/regular-expressions/reuse-patterns-using-capture-groups) has an issue.

### Hey, Contributor!
In the third paragraph of the challenge, there is a backslash `\` and a backslash with number one `\1` that needs `<code></code>` to get proper formatting.
![format](https://cloud.githubusercontent.com/assets/6125097/22533728/07dd7f02-e8f0-11e6-82e8-019e2bee605f.png)

If you want to fix this, please read [CONTRIBUTING.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) to get started.

When you're all set, replace [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/regular-expressions.json#L890) with the following:
`"To specify where that repeat string will appear, you use a backslash (<code>\\</code>) and then a number. This number starts at 1 and increases with each additional capture group you use. An example would be <code>\\1</code> to match the first group.",`

If you have any questions, please come chat with us in the [Contributors Chat Room](https://gitter.im/FreeCodeCamp/Contributors).

Happy Coding! :smile:

**Comment by JosephLivengood** [comment]
I can take this and create the pr in the next 24 hours!
