### ISSUE TITLE
The H1 element text "I am blue!" changed color on the screen, but the check list says that it is not changing color

### ISSUE THREAD

**Issue by ShelbyF73** [freeCodeCamp/freeCodeCamp#13052]
![rgb to mix colors](https://cloud.githubusercontent.com/assets/25463300/22533444/debcf058-e8b3-11e6-8b67-474abab74ce5.png)
Challenge [Use RGB to Mix Colors](https://www.freecodecamp.com/challenges/use-rgb-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20rgb(255%2C%200%2C%200)%3B%0A%20%20%7D%0A%20%20.orchid-text%20%7B%0A%20%20%20%20color%3A%20rgb(218%2C%20112%2C%20214)%3B%0A%20%20%7D%0A%20%20.sienna-text%20%7B%0A%20%20%20%20color%3A%20rgb(160%2C%2082%2C%2045)%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20rgb(0%2C%200%2C%20225)%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orchid-text%22%3EI%20am%20orchid!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22sienna-text%22%3EI%20am%20sienna!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22blue-text%22%3EI%20am%20blue!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The color of the font changed like it should on the screen, but the tasks are saying that it hasn't yet.

My code:
```html

<style>
  .red-text {
    color: rgb(255, 0, 0);
  }
  .orchid-text {
    color: rgb(218, 112, 214);
  }
  .sienna-text {
    color: rgb(160, 82, 45);
  }
  .blue-text {
    color: rgb(0, 0, 225);
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>

```

**Comment by Manish-Giri** [comment]
@ShelbyF73 The color for `blue` is `255`, not `225`, if you refer the table on the left. 

If you need help with challenges like these, please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) first. Happy Coding!

**Comment by Greenheart** [comment]
@ShelbyF73 Or, if you want a more relaxed help environment - check out [the forum](https://forum.freecodecamp.com).

Good luck! :blush:

**Comment by ShelbyF73** [comment]
@Manish-Giri I didn't even see that typo lol! Thanks for pointing that out. It's still weird that 225 changed the same text to same shade of blue as 255.
