### ISSUE TITLE
It says it's correct when it's not

### ISSUE THREAD

**Issue by Jae888** [FreeCodeCamp/FreeCodeCamp#1305]
Challenge http://www.freecodecamp.com/challenges/bonfire-mutations has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The following code passes all the tests even though it is not the correct answer.  The reason for this is because there is only 1 test that tests for when the condition is false and it happens to look only at the character in the second string at the index of 2.  If you ensure to only look at the index of 2 of the 2nd string in your code (   var findMatch = arr[0].indexOf(arr[1][2])   ), it will give you the correct answer when you actually should be looping through each character in the second string to see if it matches any characters of the first string.

Here's the code that works when it shouldn't:
```
function mutation(arr) {
  arr[0] = arr[0].toLowerCase();
  arr[1] = arr[1].toLowerCase();
  var containsAnyNeg = [];
  var findMatch = arr[0].indexOf(arr[1][2]);
  if (findMatch < 0) {
    containsAnyNeg.push(findMatch);
  }
  if (containsAnyNeg < 0) {
    return false;
  }
    else {
      return true;
    }
  
}

mutation(['hello', 'yellow']);
```

**Comment by jtrnoobe** [comment]
I don't know whether it has been solved or not and if you know the reason why u have posted such error so please consider me as a newbie

function mutation(arr) {

  var i =0,temp;

    arr[0]=arr[0].toLower();

      arr[1]=arr[1].toLower();

      while(i<arr[1].length()){

          temp = arr[0].indexOf(arr[1][i]);

        if(temp<0)

          return false;
      }

  return true;
}

**Comment by benschenker** [comment]
I'm unable to reproduce this issue.  Please reopen if this is still a problem for you.
