### ISSUE TITLE
Bonfire Mutations passing test when specific code is incorrect

### ISSUE THREAD

**Issue by osazemeu** [FreeCodeCamp/freecodecamp#1306]
Challenge http://www.freecodecamp.com/challenges/bonfire-mutations has an issue. 

Attempting to solve this challenge using this code 
```
function mutation(arr) {
  source = arr[0].toLowerCase();
  query = arr[1].toLowerCase();

  for (i = 0; i < query.length; i++) {

    if (source.indexOf(query[i]) < 0) {

      return false;


    }
  }
  return true;
}
```
![mutations](https://cloud.githubusercontent.com/assets/7466259/8711160/8069de2e-2b47-11e5-86d9-62712794735a.JPG)

Using another IDE
![mutations](https://cloud.githubusercontent.com/assets/7466259/8711275/5d13490a-2b48-11e5-899e-b71e14eac5f9.JPG)

**Comment by benmcmahon100** [comment]
Just tested your code and it passed. Just a small hiccup that's all

**Comment by kridicule** [comment]
![1436948786535](https://cloud.githubusercontent.com/assets/13342768/8711422/538dc756-2b17-11e5-8918-d9c898f22603.png)

**Comment by benmcmahon100** [comment]
If this problem every occurs again a quick hard-refresh should fix the issue(Don't forget to copy your code) This will hopefully be eliminated by the new in-comming update

**Comment by osazemeu** [comment]
OKAY, I will
