### ISSUE TITLE
Tribute Page beta challenge id="img-div" and child id's "image" and "img-caption"

### ISSUE THREAD

**Issue by DarrenfJ** [freeCodeCamp/freeCodeCamp#13065]
Challenge [build-a-tribute-page](http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Not sure if it's my code or the test, but thought I'd tag this as an issue just in case. Seems to not recognize my id="image" and id="img-caption" inside the div with id="img-div".

I'm sure I'm just missing or overlooking something but thought I'd pass this along for whoever is troubleshooting the beta...

my page: http://codepen.io/DarrenfJ/pen/jAxadd

**Comment by DarrenfJ** [comment]
feel free to fork and destroy the CodePen if you need to for testing

**Comment by OFFLlNE** [comment]
Thank you for reporting this issue.
I tried and seems that the tests want the <img> withid="image" right after <div id="img-div"> (w/o having any other elements after div there)
So the tests would have to go deeper than the first element they come up with :D

**Comment by DarrenfJ** [comment]
Confirmed myself.. If I comment out the link to a video and the div for text-center it passed all 9 tests.



between id="img-div" and id="image" and id="img-caption"

**Comment by DarrenfJ** [comment]
reverting it back to failed state and submitting using the test suite 'report issue' link for @no-stack-dub-sack

**Comment by no-stack-dub-sack** [comment]
Closing this issue as it is now open on the correct testable-projects-fcc repo [here](https://github.com/freeCodeCamp/testable-projects-fcc/issues/34)
