### ISSUE TITLE
[challenge display] Wrong Numbers of Buttons on Display

### ISSUE THREAD

**Issue by ChenxingZhang** [freeCodeCamp/freeCodeCamp#13060]
#### Challenge Name

https://www.freecodecamp.com/challenges/target-the-children-of-an-element-using-jquery

#### Issue Description

The button 4 should've deleted from the jQuery, and button 5 should have only one clone. But it seems that there're 3 "target 5" buttons the right-hand display.

#### Browser Information

* Browser Name, Version: Chrome  55.0.2883.87 m
* Operating System:  Windows 7
* Mobile, Desktop, or Tablet: msi laptop

#### Your Code

```js
 
 //Default - No change at all.
 
```

**Comment by raisedadead** [comment]
new seed code:
```html
$("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
    $("#target4").remove();
```

**Comment by raisedadead** [comment]
Duplicate #13031
