### ISSUE TITLE
[beta] Improve formatting for "Basic Data Structures: Add Items Using splice()"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13069]
Challenge [add-items-using-splice](http://beta.freecodecamp.com/en/challenges/basic-data-structures/add-items-using-splice) has an issue.

The term `html` needs to be changed to `HTML` with all caps.

If you want to fix this, please read [CONTRIBUTING.md](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) to get started.

When you're all set, replace [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json#L215) with the following, and make your commit.

`"We have defined a function, <code>htmlColorNames</code>, which takes an array of HTML colors as an argument. Modify the function using <code>splice()</code> to remove the first two elements of the array and add <code>'DarkSalmon'</code> and <code>'BlanchedAlmond'</code> in their respective places."`

If you have any questions, please come chat with us in the [Contributors Chat Room](https://gitter.im/FreeCodeCamp/Contributors).

Happy Coding! :smile:

**Comment by ajain17** [comment]
@dhcodes can we please combine this issue with 13070?

**Comment by vcapretz** [comment]
@Greenheart I'm working on it!

**Comment by vcapretz** [comment]
The PR is here: https://github.com/freeCodeCamp/freeCodeCamp/pull/13079

**Comment by Greenheart** [comment]
@ajain17 I don't think this should be combined as this is a good issue for someone who want to contribute for the first time :blush:

@vcapretz Thanks for helping out! Tell us if we can help you in any way :smile:

**Comment by ajain17** [comment]
@Greenheart I saw 3 issues on same challenge that's why suggested combining. I do agree its a good issue for first timers.

**Comment by Greenheart** [comment]
That's a good idea. In this case, If I don't remember incorrectly (there
have been quite a few issues the last few days :sweat_smile:), there are
two issues on the same challenge, one of which is for new contributors,
while the other is for a related challenge. Because of this, I thought they
should be separate :blush:

torsdag 2 februari 2017 skrev Ayushi Jain <notifications@github.com>:

**Comment by saumya-2005** [comment]
I'd like to work on this issue.
