### ISSUE TITLE
[beta] Change order of array methods in "Basic Data Structures: Remove Items Using splice()" 

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13067]
Challenge [remove-items-using-splice](http://beta.freecodecamp.com/en/challenges/basic-data-structures/remove-items-using-splice) has an issue.

I think `pop()` and `shift()` should swap places in the following sentence, so they come in the same order as their functionality gets described.
![order](https://cloud.githubusercontent.com/assets/6125097/22544970/378d201c-e937-11e6-9f71-3503bd247d5f.png)

**Edit:** The last line of the first paragraph also needs a small fix:
Change "from anywhere on an array" to `from anywhere in an array`.

**Edit 2:** [This line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json#L190) could be replaced with `"  ",` (two spaces), to improve formatting of the initial `challengeSeed`.

**Comment by ajain17** [comment]
@dhcodes  Please combine this issue with #13070

**Comment by ajain17** [comment]
I'm working on this along with #13070

**Comment by Greenheart** [comment]
I'm sorry for any inconvenience, I didn't write a comment that I was fixing
the other issue - I merely assigned myself to it.

However, the PR should have been referenced in the other issue. For the
next time, please verify that the issue isn't assigned to anyone and no PR
have been opened for it yet.

Thanks :blush:

torsdag 2 februari 2017 skrev Ayushi Jain <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:

**Comment by ajain17** [comment]
@Greenheart no problem.
