### ISSUE TITLE
[beta] Improve test cases for "Basic Data Structures: Add Items Using splice()"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13070]
Challenge [add-items-using-splice](http://beta.freecodecamp.com/en/challenges/basic-data-structures/add-items-using-splice) has an issue.

The following should be a valid solution, since the challenge wants campers to use the splice method's replacement-functionality.
```js
function htmlColorNames(arr) {
  // change code below this line
  arr.splice(0, 2, 'DarkSalmon', 'BlanchedAlmond');

  // change code above this line
  return arr;
} 
 
// do not change code below this line
console.log(htmlColorNames(['DarkGoldenRod', 'WhiteSmoke', 'LavenderBlush', 'PaleTurqoise', 'FireBrick']));

```

However, the tests allow a solution like below to pass.
```js

function htmlColorNames(arr) {
  // change code below this line
  arr.splice(0, 2);
  arr.unshift('BlanchedAlmond');
  arr.unshift('DarkSalmon');
  // change code above this line
  return arr;
} 
 
// do not change code below this line
console.log(htmlColorNames(['DarkGoldenRod', 'WhiteSmoke', 'LavenderBlush', 'PaleTurqoise', 'FireBrick']));

```

I think the tests should be stricter to prevent use of `.unshift()`, or `arr[0] = X; arr[1] = Y`.

**Comment by ajain17** [comment]
I'm working on this along with #13067

**Comment by Greenheart** [comment]
I think I already opened a PR for this one, but feel free to take the other
one :)

torsdag 2 februari 2017 skrev Ayushi Jain <notifications@github.com>:

**Comment by no-stack-dub-sack** [comment]
@Greenheart nice catch! One of the few in this section I did not use a regex of some sort for
