### ISSUE TITLE
[beta ] Match Literal Strings - Change wording to reflect examples

### ISSUE THREAD

**Issue by rmdawson71** [freeCodeCamp/freeCodeCamp#13086]
Challenge [match-literal-strings](http://beta.freecodecamp.com/en/challenges/regular-expressions/match-literal-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The example at the top is trying to match "Kevin" but the wording refers to the word "the".  Same thing in the 2nd paragraph.

![image](https://cloud.githubusercontent.com/assets/5313213/22562192/63b0aa6c-e930-11e6-8cde-aa76b6f1c7f9.png)

```js


let waldoIsHiding = "Somewhere Waldo is hiding in this text.";
let waldoRegex = /search/; // Change this line
let result = waldoRegex.test(waldoIsHiding);

```

**Comment by Greenheart** [comment]
@rmdawson71 I agree that this can be confusing. Do you have any suggestions for how this could be improved? :blush:
