### ISSUE TITLE
Regex test bug?

### ISSUE THREAD

**Issue by rmdawson71** [freeCodeCamp/freeCodeCamp#13087]
Challenge [match-single-characters-not-specified](http://beta.freecodecamp.com/en/challenges/regular-expressions/match-single-characters-not-specified) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Not sure what the test string has 9 characters that are not a number or letter, but I believe my code is correct. Usually the tests will say "xyz" should result in "123".  When this test is ran, you can not see what was used in the test.

![image](https://cloud.githubusercontent.com/assets/5313213/22563199/76322c84-e934-11e6-94a8-68c41c466b21.png)

```js


let quoteSample = "3 blind mice.";
let myRegex = /[^a-z0-9]/gi; // Change this line
let result = quoteSample.match(myRegex); // Change this line

```

**Comment by Greenheart** [comment]
@rmdawson71 I believe there's an issue in your code - your matching "anything not a letter and not a number", while the instructions ask for "all characters not a number or **a vowel**".

With that said, keep it up! It seems like you've QA:ed quite a bit! :smile: :star2:

**Comment by erictleung** [comment]
@rmdawson71 thanks for taking the time to review the beta challenges. However, your code is incorrect. 

> Create a single regex that matches all characters that are **not a number or a vowel**. Remember to include the appropriate flags in the regex.

The first test could be better worded and specific like

> Your regex `myRegex` should match 9 items in `quoteSample`

**Comment by Greenheart** [comment]
I'm closing this as I don't think this is a bug. Feel free to reopen if you don't agree and have more to add :blush:

**Comment by Greenheart** [comment]
Although I do like @erictleung's suggestion!

**Comment by rmdawson71** [comment]
I have been juggling too many things lately.  I kept reading vowels, but thinking letters (any).  Sorry for reporting a bug on a perfectly fine challenge.

**Comment by Greenheart** [comment]
@rmdawson71 Don't worry, it happens to all of us! :blush:

**Comment by Greenheart** [comment]
@erictleung Do you think we should improve the instructions for this challenge? If so, should we create a separate issue for that?

**Comment by erictleung** [comment]
@Greenheart yeah, I can create issues for them for first timers. I think the change I've suggested affects more than just this one :smile:

**Comment by Greenheart** [comment]
@erictleung Sounds like a good idea! We need more of those - the ones I opened yesterday melt away in a few hours :smile:
