### ISSUE TITLE
Change Text Color

### ISSUE THREAD

**Issue by mmarler07** [freeCodeCamp/freeCodeCamp#13089]
Challenge [Change the Color of Text](https://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%0A%3Ch2%20style%3D%22color%3A%0A%20%20%20%20%20%20%20%20%20%20%20red%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:32.0) Gecko/20100101 Firefox/32.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My Code looks correct? But the Text won't change color or work?
My code:
```html

<h2 style="color:red">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by OFFLlNE** [comment]
1. Reload the page and run the tests again. A script may have crashed, preventing the tests from running.
2. Try the challenge in incognito mode. A plugin might be interfering with the tests.
3. Try the challenge in a different browser.

**Comment by grim93** [comment]
@mmarler07  I have run this is Firefox, Chrome and Edge all seems to be in order try @OFFLlNE 's suggestions.
