### ISSUE TITLE
Should the 3rd test be passing?

### ISSUE THREAD

**Issue by rmdawson71** [freeCodeCamp/freeCodeCamp#13085]
Challenge [using-the-const-keyword](http://beta.freecodecamp.com/en/challenges/es6/using-the-const-keyword) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

After making changes to the code, the 3rd test was supposed to be testing if **calculateCircumference** is a "const", then it fails, because I left it as a "var", but shows passed on the tests.

In fact, if I just leave all the vars in place without changing the code at all, it still passes all the tests, so I definitely think there is a bug in the testing for this one.

![image](https://cloud.githubusercontent.com/assets/5313213/22561517/6d50ba4c-e92d-11e6-9e83-35969114f1aa.png)

```js

'use strict';
// change 'var' to 'let' or 'const'
// rename constant variables
const pi = 3.14;
let radius = 10;
var calulateCircumference = function(r){
    var diameter = 2 * r;
    var result = pi * diameter;
    return result;
};
// Test your code
console.log(calulateCircumference(radius));

```

**Comment by dhcodes** [comment]
@rmdawson71 thanks for the issue. We've catalogued these over at https://github.com/freeCodeCamp/freeCodeCamp/issues/12698. Closing this one as a duplicate. Thanks and happy coding!
