### ISSUE TITLE
"Challenge not found" now that Standford CS waypoint is deprecated

### ISSUE THREAD

**Issue by onebree** [FreeCodeCamp/FreeCodeCamp#1308]
After the page hangs, I navigate back to home and receive the following error at the top. I am pretty sure this is because the Standford CS waypoint has been removed, and my account is still linked to Week 3 being my "next" lesson.

**404: We couldn't find a challenge with that name. Please double check the name.**

**SUGGESTION** - For deprecated lessons, store those paths in an array. If the array contains the currently visited path, show the enduser an appropriate 404 (error) page, with a link back to "map"

**Comment by awesomeaniruddh** [comment]
Is this still relevant?

**Comment by awesomeaniruddh** [comment]
Closing this because there is already an issue for 404 pages.
