### ISSUE TITLE
Challenge #28 Unable to escape a backslash in a string, not working correctly 

### ISSUE THREAD

**Issue by actualchandler** [freeCodeCamp/freeCodeCamp#13083]
The instructions are to "Encode the following sequence, separated by spaces:
backslash tab tab carriage-return new-line and assign it to myStr", however when I write the code:
var myStr = "\\"; it returns the answer: myStr = "\\" instead of printing one backslash it prints two.

I've tried typing it several different ways with several different combinations with different words and none of them work.

Escape Sequences in Strings

http://precourse.devmountain.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22First%20Line%5C%5C%20%5Cn%20Second%20Line%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A

#### Issue Description
Whenever I try to escape backslashes

#### Browser Information

Google Chrome

* Browser Name, Version: Google Crome
* Operating System: Windows
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
 my Str = " \\ ";
 
 
```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/25497553/22561043/e711c8fc-e933-11e6-838d-e174ca7b7e31.png)

**Comment by dhcodes** [comment]
@actualchandler freeCodeCamp does not support issues for devmountain. Also, you have an error in your code.
