### ISSUE TITLE
Skew Challenge not accepting answer on Safari.

### ISSUE THREAD

**Issue by Marvive** [freeCodeCamp/freeCodeCamp#13097]
Challenge [use-the-css-transform-property-skewx](http://beta.freecodecamp.com/en/challenges/applied-visual-design/use-the-css-transform-property-skewx) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  div { 
    width: 70%;
    height: 100px;
    margin:  50px auto;
  }
  #top {
    background-color: red;
  }
  #bottom {
    background-color: blue;
    transform: skew(24deg);
    
  }
</style>

<div id="top"></div>
<div id="bottom"></div>

```

**Comment by HosfordDotMe** [comment]
When changed from <code>transform: skew(24deg);</code> to <code>transform: skewX(24deg);</code>. This passes. Revising your code will correct the issue.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (107/100 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60195 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx32-0003Rj-2m
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:32 -0400
Received: from o10.sgmail.github.com ([167.89.101.201]:4492)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx2s-0001rw-J5
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:22 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=FxKOV0HKLq0dt7BdPcMZhtVZPRs=; b=XhOtn5f1LP7++anH
	NlRLtB6D4SLYiRUr75pa7a6h2AvwpESdnbhSrNh7zAamR2NQH/dX/aBPugq1ri7r
	t5UtksQG0n/pMvyUUQntcK2/kfwjweCeeuadm37PSUyuENlW1wIjjLbTGwW4MJib
	QaZl9rCyqKScFlZjAs3r7NYRV/U=
Received: by filter0668p1mdw1.sendgrid.net with SMTP id filter0668p1mdw1-7793-59AA0664-21
        2017-09-02 01:16:20.751689406 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0040p1mdw1.sendgrid.net (SG) with ESMTP id XoMXXDHpTdi-MJ0N4DKrFw
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:16:20.712 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:21 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (107/100 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f54.google.com ([209.85.218.54]:34301)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx3j-003lZV-QS
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:47:32 +0530
Received: by mail-oi0-f54.google.com with SMTP id w10so13895179oie.1
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:16:55 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=cUT+y3q+jDLvYaW6cdI4JY7Ppngq2mbIhy1wCUcMutI=;
        b=J+NmMyouOxXPT6kJnScs9TnU3Wi+IpOKtctCwupUq5Ue47bzf16M8QoF0JgyNVWp/D
         sa6kCSNlsxuz7pzW9YMW0kDY8yfa8mekderleF32BOsL+g0ho0kVIHXfMMe7H7c5JE0T
         l+2lXvVAuYmY0i/td9Dfwlp2I4cNNtJxdxWSTYQAsALCmNy4oJk/EUKHJzgqvSisDx5y
         0KXgYcYhIVdBPf+OA2thv5Www9SE1T3X1NAYtZAeqQxXV+elAxv5IIAZVXU2niNQbNWK
         tCdCf8BCTkcs8FBVJKUErs0j5gJhmgWZQn0Yh2f00UZW0fg3ULU0+G4ovck7/AyVgide
         JwrQ==
X-Gm-Message-State: AHPjjUh9XMWAdM/YddkLENbn5oYKDPrJ52Iumg/VuRBekpoYqcxpAOki
	LtUJNC/Y9ASht2Gfu9KJuzFdBUHASm8hw30PQGi6OQ==
X-Received: by 10.202.213.68 with SMTP id m65mr4694896oig.25.1504314993433;
        Fri, 01 Sep 2017 18:16:33 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1352768ofe;
        Fri, 1 Sep 2017 18:16:32 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb4fVTvLmFblXBFRdiY3eYf8VdViu76hNpGKFYFfWgHmEr0U0cf0gOYVmPyfjJrELagwQJGv
X-Received: by 10.36.216.68 with SMTP id b65mr1198486itg.172.1504314992644;
        Fri, 01 Sep 2017 18:16:32 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504314992; cv=none;
        d=google.com; s=arc-20160816;
        b=HYCiiJgk8Nzlee3aE0qcrR7/aoKR6TMIkoSYhrS+oW7ZpKX2pWlwMuOBb22gcUa4vh
         ODs7brVg904K4bTke4ZyiP4/Z+S7Hgo/Kh+Ey+4eMEY4tQxeqAowXGqC1kd010A2p0+e
         2IZ3Jq3De7Yru1NvP5/NDU4pR21LsdS0vIa7X4UmRmsb8vlSRyuAb755V1PZfyWCA3th
         RPF8F+w3j4B+EZtINuHuBbyQ1AxDIrFbQ+U8c+N+WtgVUN9ei9gaIaoFq+bqU56bivjs
         Tgr/l/7uRex8v79yaC4TnekZkfbZkTw4g1sZZlqeB819LdozPt0XeJrzu7MWR7BvAvw2
         m7gg==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=cUT+y3q+jDLvYaW6cdI4JY7Ppngq2mbIhy1wCUcMutI=;
        b=coz5WUQK3Wse9HPtXcy0ecOTRnKcba11P8r3YktbZc6KG4Wm6ASYmmhbvc5zUJQoe4
         q3LPJHrj/8763tEWfgqcW4sD4+iuRnCdfmEMwfREqsfanXXjs+Ue12aaifiLWjWuPowm
         WbpTTkp8GtBG3Mo6XhHnBxXw53R3a6vWBHprX5gjzlmMLYdEZKGDLiAv/0Iypw7iBYwD
         pdsT8ITgEDkzFr5P9CZtnAFYkH2omZBHXue0NkHXoPkEQiHkTIqOdPb5NlfkOsbAdEKR
         bEJEj9ZFKLl2F7ET8p8vqP78+FYPhrsnwYFrRByKZ1GBkw4qbnigvJYaV4MS6ZQY5I7v
         c1Jg==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=tcwxps3S;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=E2IzPmFr;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.101 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o6.sgmail.github.com (o6.sgmail.github.com. [192.254.113.101])
        by mx.google.com with ESMTPS id j15si1244726itf.169.2017.09.01.18.16.32
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:16:32 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.101 as permitted sender) client-ip=192.254.113.101;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=tcwxps3S;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=E2IzPmFr;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.113.101 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=rUio7zcRsBihha8n/GdOMKg5KPk=; b=tcwxps3SBBV7B3Y6
	1fFj3Z94spKmRw7YhHOMpn7LRdSql1OI9NqhWs2PBWWCf7VwyVph/U1EPTb8Up6q
	2oagGHz5979N0m3UljN1M1xtL4QcOuyptMZtLz2sCe7tXphLVtuyfQhhX3Y9fzep
	fCarh6QkvLQXPj+2m5RaXZi74HY=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=rUio7zcRsBihha8n/GdOMKg5KPk=; b=E2IzPmFrtt+9F0CEvM
	2oCqE5jllqXb2eCQXDwI5UmDaC+MFk8xR6JFRvC+dbL9gkMg89CD5ikyoxwCa+G5
	BlZ8qAhwKghre4ibQbVgRtYO9BjP3qj2R5EmB/T7Tutuedl2M+OFGLMHCmlaNI+2
	rDLrzxNtujp0ZBvuKW1P2Cp84=
Received: by filter0504p1mdw1.sendgrid.net with SMTP id filter0504p1mdw1-17586-59AA0670-26
        2017-09-02 01:16:32.272332875 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0038p1mdw1.sendgrid.net (SG) with ESMTP id kcDI-PIeS0SV8mc93cqSXw
	for <pawan.ossindia@gmail.com>; Sat, 02 Sep 2017 01:16:32.208 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:32 +0000 (UTC)

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (119/100 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 44325 characters long; only the first
------ 5000 or so are included here.
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60353 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx7E-0004eY-0g
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:20:52 -0400
Received: from o10.sgmail.github.com ([167.89.101.201]:35550)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx6g-00023k-5V
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:20:19 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=swSRR1I0OXdVvPqACIzq+YXwW6c=; b=wbA4R3lSDi3Mgyv4
	SBhNQIyQ14f/D19wJHq1+PV3kmg500OUkiGfA5fTEiW+CHu9t2NrCQTfbSJgyLNi
	5YmdUdBTOWjgobk/7GiSOQZANUlDb4MfnrBw5xQ4el9aKnUoeDxJixw7U324eGQJ
	bt5GzV9vCDbYVS6lVtQ8vlvYpTo=
Received: by filter0621p1mdw1.sendgrid.net with SMTP id filter0621p1mdw1-31103-59AA0751-21
        2017-09-02 01:20:17.43679923 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0036p1mdw1.sendgrid.net (SG) with ESMTP id fJVOpYJyR0q9vb_RMlQ6Eg
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:20:17.315 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:20:17 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (123/100 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 24814 characters long; only the first
------ 5000 or so are included here.
Received: from mail-oi0-f54.google.com ([209.85.218.54]:33505)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx6Y-003v6Q-KD
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:50:31 +0530
Received: by mail-oi0-f54.google.com with SMTP id r203so13992941oih.0
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:19:50 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:date:dkim-signature:from:reply-to
         :to:cc:message-id:in-reply-to:references:subject:mime-version
         :content-transfer-encoding:precedence:list-id:list-archive:list-post
         :list-unsubscribe;
        bh=eBEaALIOWhD+QDt6sHVYZEdkO4rjtXeeGE9rAkYXljw=;
        b=KSe+QUTzCeKBS+G0s81ENDLQC7wNveikdYIg4ivaXEEzVNbL0Ws1GHnc5A527Hdk9h
         LyABEH6Z/sHl62I47uMcbpfiMlXP8+kxTjpYWOkVKFEpyaG/OM0M8p/s9aH7JCElKccO
         KG/I0JfBBUdUpLbMUc74qjLAMR7Yq7o0P9slZuiPkE8skGgPD6wH9w8w1GWLGl4ECPck
         eVByI2rKKjX7yGPnNFO4OCXVmBkwnYauIoMZK/AgARrQ/hbu4mMK1cBy6AP25XOqzlBY
         ncpzxFoQ8G018cP2noFUNNMp2bIjDU6RExBF/UHLNoSAWy4weCMaTa/7bYWiIM/NDbeT
         h8/g==
X-Gm-Message-State: AHPjjUjIQMVS+zYeYxEBe3PbyIN+mkZ3B4fzXbyF/pOBs8lM2YTAut5c
	oc0EfFS0flpGm4Xhr6YCjy3o6wAIFIVjNu4zb1iuuw==
X-Received: by 10.202.72.17 with SMTP id v17mr3398836oia.127.1504315168351;
        Fri, 01 Sep 2017 18:19:28 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1354423ofe;
        Fri, 1 Sep 2017 18:19:27 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb4MySwebloMzpncKzw/+KZkCNhpckj6fmNoRV8bKT75RStlcLdd1hiLwOy3OXigaXW38fhl
X-Received: by 10.55.165.199 with SMTP id o190mr4916112qke.105.1504315167109;
        Fri, 01 Sep 2017 18:19:27 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504315167; cv=none;
        d=google.com; s=arc-20160816;
        b=CPhf0Gdr4acizX51BoFUMagHUP9WdYGwxz5WeCmGLB9MjznRw7qnO3oy18MDSIx9Pn
         78Gi4R6It7PpR9Ov86CpywOCWMGR2Uea6D49ydD5baec5E+Ac1Bwweru+auh1fw3gAXD
         /+NW0J84YOCNL+BLHtxIVwux71Uo7E2323X1pKPJX15PyKaMCuKsD1HKA+9vojCzPgZH
         96CIRzyH7qRnBElbIfhriWrm9t3p9PcLf4/e2qgfwvv5etSYQY+5NEEqt1oFFuzDG34a
         XrKmgZe/S+TXeYVPItzIE54ZpIPMIokhiZ+cBpEjzB+ObRr82fjO7u7oivmio4qepmv1
         wPIA==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:dkim-signature:date
         :arc-authentication-results;
        bh=eBEaALIOWhD+QDt6sHVYZEdkO4rjtXeeGE9rAkYXljw=;
        b=fVqCQ/gpwQj7I27vL6e9c4bndMVX3eUlwQafwRw+U9OEBnJ/Rys8XmSEq6zWKNfq8G
         QHZeE5zja2Ytb3IaF2XLRrwhppqEw0F6npP5mknRXchP/LKfcB4RlNC09EFY+VlX0DTJ
         FB4VkyHByzouIC4Oc0O7wVtu0nR9/oOLGmSy9DlTEO8lsq0Glf/O16vbNLkDxtLG/zTn
         HKsIU0zDcvU43S0JdGMHKHERFj3sIZxYEoif6hRAov9LqLPeDi4mSHV/G+SRZu6j6m93
         dAFRz3FizZOy6rKDuywWZtGL6Xk5Id2H5eSV7TtswYxa088l5xiOFaOMvaUFgIHHkzFD
         HnQw==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=soxKuL+b;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.193 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2-ext2.iad.github.net. [192.30.252.193])
        by mx.google.com with ESMTPS id p21si1430573qta.220.2017.09.01.18.19.26
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:19:27 -0700 (PDT)
Received-SPF: pass (google.com: domain of noreply@github.com designates 192.30.252.193 as permitted sender) client-ip=192.30.252.193;
Authentication-Results: mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=soxKuL+b;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.193 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Date: Fri, 01 Sep 2017 18:19:07 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1504315166;
	bh=eBEaALIOWhD+QDt6sHVYZEdkO4rjtXeeGE9rAkYXljw=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=soxKuL+bMmteXcFGkWf/cPujB1R5cDMfukQM5THi5vLrnvdlqrDF9uEUXF24EP9Hy
	 HjP3+Skbj9f5mONcxH0U2WHVcDXt5QnmAM1x3eC/TypAOWw9/Pc50xdyLx/u384XIh
	 +Y4o4EA4yMhXrB1KXvSOtXkST5OFwW4q+xktWi+o=
