### ISSUE TITLE
[beta] first npm challenge failing test - unclear instructions 

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#13093]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/managing-packages-with-npm/using-packagejson-the-core-of-any-nodejs-project-or-npm-package

#### Issue Description

This challenge asks that you add your name to the author field of the package.json file - however no such field seems to exist by default in a new gomix/hyperdev project. We should update the challenge instructions to reflect this: "add an author field and..."

__EDIT:__ @Greenheart mentioned below that there might be a default project set up for this, but apart from that, starting your own project and adding an author key and value does not pass the test

**Comment by Greenheart** [comment]
@no-stack-dub-sack Did you use the boilerplate project? I don't know the link for it, but it's possible to "remix" it to get your own copy which should be set up and ready for these challenges.

**Comment by no-stack-dub-sack** [comment]
@Greenheart No, I didn't - other issue is, there's does not seem to be a link to it in the challenges (you've probably seen my other issue). Any idea where I might be able to access it? 

I guess I'm the first person to try these challenges since beta went live? Otherwise this would have already come to light.

\#first!

**Comment by no-stack-dub-sack** [comment]
@Greenheart Ok, ditching this and starting new, more relevant issue #13095
