### ISSUE TITLE
Error highlighting is unreadable within <style>

### ISSUE THREAD

**Issue by HosfordDotMe** [freeCodeCamp/freeCodeCamp#13099]
#### Challenge Name

All challenges in Applied Visual Design

#### Issue Description

Type within the style section of code.  

<code>.cm-s-monokai span.cm-error {
    background: #f92672;
    color: #f8f8f0;
} </code> is not overriding <code>.night .CodeMirror .cm-property, .night .CodeMirror .cm-string {
    color: #B5753A;
}</code>

#### Browser Information

User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.

#### Screenshot

<img width="200" alt="screen shot 2017-02-02 at 10 26 10 pm" src="https://cloud.githubusercontent.com/assets/555977/22578432/bec36a96-e996-11e6-9e93-217cd3ae1cdd.png">

<img width="306" alt="screen shot 2017-02-02 at 10 34 24 pm" src="https://cloud.githubusercontent.com/assets/555977/22578590/d878415e-e997-11e6-9d5d-d1730fceb095.png">

**Comment by HosfordDotMe** [comment]
Issue only happens when in NightMode.

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (100/100 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f42.google.com ([209.85.218.42]:34242)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx3U-003jh0-4f
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:47:18 +0530
Received: by mail-oi0-f42.google.com with SMTP id w10so13893173oie.1
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:16:39 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=vMY2/oUl6oE8PUH0Of8v0NoAvFeZv92PlYKTb8gARPg=;
        b=go+qASaxBV5bDPY1+49i7Q8x0nC/6WBA+il9HEzgl+J+Y2geUDPtFzBq8rXYI1Qhe0
         0DSayqynEgbsYaHNjNdxt8t2kkI18APAaph0uspM6cusjype1BF5DrCynULL0Wysbw2J
         ufZoUKSHn9gil4L3hEZl0teET9CGz4Cg26MC8N+l9HfUovMzpJUk5mi98PVqc30aPTyB
         FIc1E/oN+Wl1983BPoERPjac6UjgHevqiGAapHOROPtTT/SqbDKyY7BFhOZWIm4uEqrD
         KIbQOrq6WyetJDhSfxYpQB8MB0ttldJ/YSozeOYvBayZr8iX18vKM6dO/p9DE9c0XljZ
         Kzvw==
X-Gm-Message-State: AHPjjUiKfeNPrl22ghy5UdYDD79bAM7WPlrXR2eMFJ62YDZnD5SLqNrt
	sllcZj2O7q9H2mveJc3+kRCI0ZKAIJFOlI2BDd7q0g==
X-Received: by 10.202.4.130 with SMTP id 124mr4143239oie.246.1504314977562;
        Fri, 01 Sep 2017 18:16:17 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1352617ofe;
        Fri, 1 Sep 2017 18:16:16 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb4+3HHEgiphuuJfMni18tGGmfQpD3J41Fpe6oY4LjfTu/m/KplFyDGCgntbg1RIQZXtgfUX
X-Received: by 10.36.71.68 with SMTP id t65mr1123451itb.173.1504314976657;
        Fri, 01 Sep 2017 18:16:16 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504314976; cv=none;
        d=google.com; s=arc-20160816;
        b=fVSFvT5S0CFvGY0y1AZCNFtAXYUjou7Cf1VSsKuqddiEipXXcW04sSpjuoMjmP0F/S
         m6dz2U5+TTl/zmMmpEIg4BpfLgAI2/tr4b3nD+zoI6crYf+sAlmaj/vv+x0xekjHNU2Y
         e6fJhzI2wNycqjM/VgN89/Q6h2ZC1a5BrKH9e3YOuZXSmVg7hJWsNfXqC/yX2glrvG8d
         0YJBPHHcUsr1fngyyl1sJMvD0VZuAmH94NLCglM/8Zs5Jd5vna542WsNL3gY6ABSVFvc
         hZd3B3O7tAAtd6ou+0kd51LGdRYr2mrOkB/cvRh9Bcqz3qBWP65+AgxNTGyWAms7DBh0
         Z67A==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=vMY2/oUl6oE8PUH0Of8v0NoAvFeZv92PlYKTb8gARPg=;
        b=PvEKOEPFXlWjhlcF17Asj/GJGAxivuoJ+zdVixePCPjkPH+ioFnuPXX78TsHQxx83G
         nd0dBkRpRTjfjNVSUvGE76H/Gm0j28SUZ3avv/jJY5FWOjrGQrL1QHOvvzoXES8k3sPD
         GImpg0+lZSKr0ahbXvMlw6CNXlSuhZ87sTf53ioSzODshFaJi6r9+0UzdS5bGgs/On2x
         QVrBvIUp2DXEBV7N+EdJYmRQUvf6MckbiXlLM1CGRTbGc/vbn1WvYISRjOmtOyEfVdPb
         ivUFLwUGMyIG1R+nzVV2KaJFmfsGrPMHYd0SLd8IIMPO74EptHoOylRjLBW6sYkWrial
         SmsA==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=sGcA8GNR;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=kAXvEUtC;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o3.sgmail.github.com (o3.sgmail.github.com. [192.254.112.98])
        by mx.google.com with ESMTPS id z69si1271016ita.97.2017.09.01.18.16.15
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:16:16 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) client-ip=192.254.112.98;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=sGcA8GNR;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=kAXvEUtC;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.112.98 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=bGNuibBBvbJw5wmFDUwivAsy9Fw=; b=sGcA8GNRI2BiMpeK
	ZX4TwAjVtSa3qhaZZA7bzJs9mhzbKfBScGhFcw0UACRDn1/FcCyfXeyWJa+tiLYb
	yJXUUR3MWJ5nkx2V6EIXaqY7zU2vwkcaN2EiSUz+uqjiwuGLQehEaqv5ns3qZnca
	aZVqH39RrHVnhITKLe0zHZrgixw=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=bGNuibBBvbJw5wmFDUwivAsy9Fw=; b=kAXvEUtCMIF/mKkMVH
	5W0SlmZpuns4cems7fPVtwFvnemOi1SjRm5ePALLBXVQI6EMi86lq141Ek1Ap0a3
	iCNDy6JiHi8QD1YAp/GsRqytRERWXFJ8CAJ1g88s35b3pQ3Z6mhV6ERLYLOWo+4I
	aKaEuV6oXu2+1pa3WDn9X1hNg=
Received: by filter0956p1mdw1.sendgrid.net with SMTP id filter0956p1mdw1-18561-59AA065F-2B
        2017-09-02 01:16:15.902255009 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0037p1mdw1.sendgrid.net (SG) with ESMTP id A2qsIWiZTwONI6vgYjBntw
	for <pawan.ossindia@gmail.com>; Sat, 02 Sep 2017 01:16:15.936 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:15 +0000 (UTC)

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (118/100 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 44372 characters long; only the first
------ 5000 or so are included here.
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60349 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx7C-0004eM-PN
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:20:51 -0400
Received: from o7.sgmail.github.com ([167.89.101.198]:15030)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx6m-00023l-Gs
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:20:25 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=IH/nAflat7PNyallIzjHvrgsk14=; b=t4FoGuxygnhKQlpr
	d9iPajIeeiLEq6EmpfHoXZvZBLoOEZGZE7tBauht1QGujy2qjuq920B36i+HD/KP
	mU5tuDfV6Nyvw5Da4rV3hLTJRYEiF56W8fqcRHZeRBpGtVKmacrFXhiXY63sRMCd
	rCqq8xs47gWspO/3gbqwsrnPVXw=
Received: by filter0325p1las1.sendgrid.net with SMTP id filter0325p1las1-13026-59AA0752-20
        2017-09-02 01:20:18.340039464 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id n9W1m5w-TqmQJEKABmKvYA
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:20:18.169 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:20:18 +0000 (UTC)
