### ISSUE TITLE
[beta] missing hyperdev setup instructions in first npm challenge

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#13091]
#### Challenge Name
http://beta.freecodecamp.com/en/challenges/managing-packages-with-npm/using-packagejson-the-core-of-any-nodejs-project-or-npm-package

#### Issue Description

Unless I'm totally missing something, and I suppose that's possible 😄 , there do not seem to be any instructions here or in the section intro for setting up a hyperdev account / project.

It just says: 

> If you go to the HyperDev-project that you set up previously...

But there does not seem to be anywhere before this where a hyperdev project would have been set up.

**Comment by Greenheart** [comment]
@no-stack-dub-sack I don't remember what we thought about the initial setup when we created these challenges, but if it's not present at the moment, we need to add this to the introduction-challenge of this section.

Introduction challenges can open links, so we could use it to help campers set up their projects properly, similarly to how the "intro to freeCodeCamp"-challenges work

**Comment by no-stack-dub-sack** [comment]
@Greenheart Looks like the content from [here](https://github.com/freeCodeCamp/CurriculumExpansion/issues/44#issuecomment-240259994) is missing

**Comment by Greenheart** [comment]
I didn't do the import myself, but since all work should be saved in GH issues, it shouldn't be too hard to add the missing pieces :+1:

**Comment by no-stack-dub-sack** [comment]
@Greenheart Okay, here's the boilerplate gomix project: https://hyperdev.com/#!/project/red-moose

**Comment by JosephLivengood** [comment]
@Greenheart Hey, that is an outdated boilerplate! Use https://gomix.com/#!/project/storm-leopard instead please for the NPM projects!

**Comment by no-stack-dub-sack** [comment]
@JosephLivengood, @Greenheart  If this ☝️ is the boilerplate project that is being used for the NPM challenges, than a lot of the challenge instructions are off:

![image](https://cloud.githubusercontent.com/assets/18563015/22622622/40b1ddea-eb0d-11e6-8ad7-37241f424d17.png)

In this boilerplate, there is no author-field (which I think makes more sense - have campers add the whole thing), so we would have to change the challenge instructions to say something like:

"Add an author key to the package.json file, and set it equal to a value of your name."

The same would go for the next few challenges as well (description, keywords, license, version).

**Comment by Greenheart** [comment]
@no-stack-dub-sack That was my intention when I initially wrote the challenges - add one field at a time to demonstrate what it means.
