### ISSUE TITLE
Map the Debris - Drive

### ISSUE THREAD

**Issue by alexalexson143** [freeCodeCamp/freeCodeCamp#13107]
Challenge [Map the Debris](https://www.freecodecamp.com/challenges/map-the-debris#?solution=%0Afunction%20orbitalPeriod(arr)%20%7B%0A%20%20var%20GM%20%3D%20398600.4418%3B%0A%20%20var%20earthRadius%20%3D%206367.4447%3B%0A%20%20%0A%20%20arr%20%3D%20arr.map((obj)%20%3D%3E%20%7B%0A%20%20%20%20let%20r%20%3D%20obj.avgAlt%20%2B%20earthRadius%0A%20%20%20%20obj.orbitalPeriod%20%3D%20Math.round((2%20*%20Math.PI%20*%20Math.pow(Math.pow(r%2C%203)%20%2F%20GM%2C%201%2F2)))%0A%20%20%20%20console.log(r%2C%20Math.pow(r%2C%203))%0A%20%20%20%20delete%20obj.avgAlt%0A%20%20%20%20return%20obj%0A%20%20%7D)%3B%0A%20%20%0A%20%20return%20arr%3B%0A%7D%0A%0AorbitalPeriod(%5B%7Bname%20%3A%20%22sputnik%22%2C%20avgAlt%20%3A%2035873.5553%7D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function orbitalPeriod(arr) {
  var GM = 398600.4418;
  var earthRadius = 6367.4447;
  
  arr = arr.map((obj) => {
    let r = obj.avgAlt + earthRadius
    obj.orbitalPeriod = Math.round((2 * Math.PI * Math.pow(Math.pow(r, 3) / GM, 1/2)))
    console.log(r, Math.pow(r, 3))
    delete obj.avgAlt
    return obj
  });
  
  return arr;
}

orbitalPeriod([{name : "sputnik", avgAlt : 35873.5553}]);

```

Hello, this isn't a bug technically speaking, but the avgAlt for sputnik seem to be misleading:

```
orbitalPeriod([{name : "sputnik", **avgAlt : 35873.5553**}]) should return [{name: "sputnik", orbitalPeriod: 86400}].

orbitalPeriod([{name: "iss", avgAlt: 413.6}, {name: "hubble", avgAlt: 556.7}, {name: "moon", avgAlt: 378632.553}]) should return [{name : "iss", orbitalPeriod: 5557}, {name: "hubble", orbitalPeriod: 5734}, {name: "moon", orbitalPeriod: 2377399}].
```

Per google, avgAlt of the following:
1. iss - 400km (vs 413.6)
2. hubble - 568km (vs 556.7)
3. moon - 384400km (vs 378632.553)
4. sputnik - 577km or 359mi (vs 35873.5553 !!)

The first three examples were close enough. However, sputnik's value was way off, relative to the first three. I thought I had to convert the value first to km, (35873 / 100, to get the distance in miles, then multiple by 1.60934 to get the distance in kilometers).

I apologize if this is the wrong place to post this issue, but I don't know who to contact about these things. I do hope this gets changed though.

**Comment by raisedadead** [comment]
@alexalexson143 thanks for the report. Can you please cite the sources for reference? We would update this challenge based on that.

**Comment by alexalexson143** [comment]
@raisedadead Hi, please see below:

Google should show kilometers equivalent at front page.
[iss](https://www.google.com.ph/?gfe_rd=cr&ei=g8CaWPzbJKrf8AeSgbzABw#q=iss+altitude+km)
[hubble](https://www.google.com.ph/?gfe_rd=cr&ei=g8CaWPzbJKrf8AeSgbzABw#q=hubble+altitude)
[moon](https://www.google.com.ph/?gfe_rd=cr&ei=g8CaWPzbJKrf8AeSgbzABw#q=moon+distance+km)
[sputnik](https://www.google.com.ph/?gfe_rd=cr&ei=g8CaWPzbJKrf8AeSgbzABw#q=sputnik+altitude+km)

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (108/100 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60197 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dnx33-0003Ry-Gt
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:33 -0400
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:32960 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1dnx2u-0001s5-Cy
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:24 -0400
Date: Fri, 01 Sep 2017 18:16:24 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1504314984;
	bh=gYOR0l2g5TMI6QRPcYuG0PE04F6O4tzgveRycv4//3Y=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=XZlRszlWJnZRrdSwpHG4/hlRmFyQs82XO0g4FJWWYA9KVJXuEVMAurxO1q2RiWYU/
	 jORfNaF+mvL7VTc3fJomf8O/FLEsl7HkrBmChkTroXuxumc2zwbAvhwUHUsgJ7YLIH
	 a8sWiNBrJV3ZqUAqN6ajABVHsFyowCNrsaJ7+gws=

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (108/100 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f48.google.com ([209.85.218.48]:34842)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx3m-003lv0-Ew
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:47:35 +0530
Received: by mail-oi0-f48.google.com with SMTP id n18so13975174oig.2
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:16:58 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:date:dkim-signature:from:reply-to
         :to:cc:message-id:in-reply-to:references:subject:mime-version
         :content-transfer-encoding:precedence:list-id:list-archive:list-post
         :list-unsubscribe;
        bh=X5AWxrwdt71fpkb7nbL3MTRRzk9dxuMeZZcmh2Gp0D0=;
        b=qa5CYwhMxP8GF14wrO4+U08d9XfIRH8hov3Q29zT3idjDWbN1qQdeiXKRBTDjCFWae
         l9hG7pJnM1BqvZ/y6m5wVz3/CCVA9UAQDwVaaFBGn27Fvv3I1IOHdES+s3aTilBCuD13
         nbPw3xvGy4CmZnnXvxWKtvZ1tPtPkWMgf7fiL2UB42RPoPZU/6BpN7gzaofqW/YfFBRa
         NfmJmvCAMm3Tbv6Z/S2BXUPYZ4nbacLpCebEosB5HNPCV5/b6Z5EeSdn3/YxQKVPr0Ua
         6pxT5yfKoUzNdch8XBqYXylGNyHDGHTUSC6Pz+oN27+agNNzhIQtH6ABdTrqfYTkq3EI
         1Hgw==
X-Gm-Message-State: AHPjjUjhIX4G8aPvIuPWfo1LiRlo5rOOYQXCOgJ9YK8jbIpDWXlB2VGy
	tK2YUwCNIJhww7rYJtLgQvcXNEEYC0Rj3GHBFS90Qw==
X-Received: by 10.202.245.67 with SMTP id t64mr3342226oih.19.1504314996086;
        Fri, 01 Sep 2017 18:16:36 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1352795ofe;
        Fri, 1 Sep 2017 18:16:35 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb4DNB8nJkgFr36sV8UmgKdVXA1JVHMlXcD181SsuXXK+ZW7CRsSpXvGU8sJaTEguKn3AE9G
X-Received: by 10.200.50.3 with SMTP id x3mr5824669qta.129.1504314995455;
        Fri, 01 Sep 2017 18:16:35 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504314995; cv=none;
        d=google.com; s=arc-20160816;
        b=khaJ+KrbuIohl9nsI+AfhhGzjvsJ76+8xw6I/WD20dIYaGfi4Wv9xTBJRYNPWZgc6c
         4QSpG0WOpx1Fm8iCzRRckwOoatn8gjk5FlaT3avRT/ZrtM/c0NCTVEMcg14rVhrM8yuo
         Xf8nBrtB1EdqHlQCRQKchodVeJqj2vUcuHEWxDq26tZo4Fsp4S4QdZwPhf4WMLoWVWP9
         kHe3XYlih99NlIpDv/b126hE9RzvNZscmGSp6HfXsROBfX2tG1I0RPtulNzFjVYIXtFo
         wB10uIP1TIFanEHgv52RLpK5mJZoGSobuhuUqmAl03y8tdtd3lN9MAo0Vdz7VnRsE6Lh
         OvEQ==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:dkim-signature:date
         :arc-authentication-results;
        bh=X5AWxrwdt71fpkb7nbL3MTRRzk9dxuMeZZcmh2Gp0D0=;
        b=P45cUHkygAmcVeBUUmyt+NMXjgbUjXuyKWJYXaORkCT4igQ04kjZBUSenTFeELm+5f
         S9MYrq1Cr8FzwVlTZS5dqNnmq9cVYrlHoRc459D/PLYgdt+cYKSv/ohZx3ewIzEcwMBK
         l0OEIE9qs9Vn5RcnUJpaNHDBPrjxF90ciGMXe+k8/CbCT+ntecisONfYwndIc/8v7m0P
         4kQ/NvJUcgNmUvUqQ6gmTfhUM/ge3VpVXuBELanFt1rRlagLDtuuqW5LNgKeACQVXtoU
         SEFSEW9WvsLPoodkUC8fKvLJPpHFiR8MdoLEjqbv6qirdRUjGDzySfLJgftPKej2UM/8
         DXeA==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=ieL2KqSN;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.194 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2-ext3.iad.github.net. [192.30.252.194])
        by mx.google.com with ESMTPS id v203si121402qka.264.2017.09.01.18.16.35
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:16:35 -0700 (PDT)
Received-SPF: pass (google.com: domain of noreply@github.com designates 192.30.252.194 as permitted sender) client-ip=192.30.252.194;
Authentication-Results: mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=ieL2KqSN;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.194 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Date: Fri, 01 Sep 2017 18:16:35 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1504314995;
	bh=X5AWxrwdt71fpkb7nbL3MTRRzk9dxuMeZZcmh2Gp0D0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ieL2KqSNMG42cvKKheOki/Rc1bGUFLLZxDy7cdBKCz8TXd5IRjXWqCb59DeI+cK0W
	 bFd1T3JaDI/mmOXoVZXm7Fgi2wchx3WGIlZ5iny1nu6ac2e502eN5wbSPujQedwYT0
	 PDEzUy/gNOFppQX01nzAEG7Dtx/M1VoChwSNiv0g=
