### ISSUE TITLE
Could not switch to Night Mode - Authorization Required

### ISSUE THREAD

**Issue by omalinov1994** [freeCodeCamp/freeCodeCamp#13106]
Hello,

I was trying to switch to Night mode last night and was not able to do it op Opera Stable 42.0.2393.51. I kept getting a message saying Authorization required. When I opened Chrome I was able to do it just by clicking the button in my account settings page, no Authorization message popped up.
I am not sure if that is something related to my Opera settings but just wanted to let you know.

Browser: Opera Stable 42.0.2393.51
OS: Windows 10 Education
PC: Acer Aspire V5-591G

Kind regards,
Ognyan

**Comment by raisedadead** [comment]
@omalinov1994 thanks for reporting, can you confirm if this happens on the beta website or on the live website.

You can simply copy paste the link in the address bar to know.

Thanks.

**Comment by omalinov1994** [comment]
https://www.freecodecamp.com/settings <- Link from adress bar

**Comment by raisedadead** [comment]
This is a known issue for some on the main website, we have fixed this in the beta and will be available in out next release.

As a work around, please use an alternate browser like Firefox.
