### ISSUE TITLE
[beta] remaining backend challenges - no boilerplate gomix project to remix

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#13100]
@Greenheart @Em-Ant It looks like the remaining backend challenges (everything after managing packages with npm) requires a boilerplate project for campers to remix (also missing from npm challenges intro - #13091) that is to be used throughout and continually built upon all the way through the end of the infosec section. Is this right?

Either first challenge or intro should have a link. I was able to find the boilerplate link for the npm section in the CurriculumExpansion branch, but not for this section. 

If this is the case, maybe we should also make a clear note in the first landing page (or on each landing page) that these are supposed to be cumulative, so if campers attempt to jump in at a later section, they know they'll need to go back and start from basic node and express?

**Comment by no-stack-dub-sack** [comment]
Ok, so it looks like each section has it's own boilerplate. These need to be added to the landing pages for each section so that others can start working on them as well Thanks for posting this link @Em-Ant!

https://hackmd.io/GYVgTBIIxgtAzATgCYCNYBYCGZ2oBwbqLCJSKIj4DG1y8QA=

**Comment by no-stack-dub-sack** [comment]
@Em-Ant Also, none of these boilerplates will work until the CORS settings are updated as @JosephLivengood pointed out for the NPM challenges in #13095 

I forked [your repo](https://github.com/Em-Ant/fcc-express-bground-pkg) for the Basic Node and Express challenges and changed [this line](https://github.com/Em-Ant/fcc-express-bground-pkg/blob/master/index.js#L38) of index.js and updated the package.json of the GoMix project to reflect my repo, and that all did the trick. I'm assuming this is an issue that is consistent throughout.

**Comment by JosephLivengood** [comment]
@no-stack-dub-sack It turns out he had it fixed, we were using outdated boilerplates.

I can confirm the boilerplate works as intended without edits or fixes on the hackmd.io, however the solution to it is using the outdated version.

@Em-Ant @no-stack-dub-sack I'll edit the solution as soon as I can to share the same working code as the updated boilerplates 👍

**Comment by no-stack-dub-sack** [comment]
@JosephLivengood perhaps only for the NPM boilerplate? The Node and Express boilerplate from hackmd.io pulls from @Em-Ant's repo that I linked to above (in which the CORS error still seems to be an issue)

**Comment by JosephLivengood** [comment]
@no-stack-dub-sack Possible, I only have checked NPM since I'm working in the advanced section right now. Is it all of the boilerplates apart from npm needing that fix?

**Comment by no-stack-dub-sack** [comment]
@JosephLivengood Not sure, I've only moved on to the Node and Express one, but that one for sure does not work as is

**Comment by JosephLivengood** [comment]
@no-stack-dub-sack I'll make that fix real fast

**Comment by JosephLivengood** [comment]
@no-stack-dub-sack Looks like it was just that one missing it, I added it into the boilerplate but I do not have access to Em's solutions!

**Comment by no-stack-dub-sack** [comment]
Oh, ok, great! What did you have to do to fix it, if it wasn't changing the URL to beta.freecodecamp.com in the CORS setting like you did the other day?

**Comment by JosephLivengood** [comment]
@no-stack-dub-sack Just updated the code from by default _restricting_ to just those, to not restricting any request (by default at least) as Em did

**Comment by no-stack-dub-sack** [comment]
@JosephLivengood I don't see that in the boilerplate's code - did you change it in the dependency package? "https://github.com/em-ant/fcc-express-bground-pkg.git"

**Comment by JosephLivengood** [comment]
@no-stack-dub-sack Haha no problem, made me double check 👍 

Want to hop on gitter to communicate about these? I'll be there pretty late in the night working on some stuff!

**Comment by no-stack-dub-sack** [comment]
@JosephLivengood Yup! Just IMd you
