### ISSUE TITLE
[beta] node - Use the tilde-character - not passing test 

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#13102]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/managing-packages-with-npm/use-the-tildecharacter-to-always-use-the-latest-patch-version-of-a-dependency

#### Issue Description

Challenge does not pass with below code. First test fails. (see #13095 about getting tests to run with remixed project)

#### Browser Information

* Browser Name, Version: Chrome, latest
* Operating System: Mac OSX 10.11.7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
{
	"name": "fcc-learn-npm-package-json",
	"version": "0.0.1",
	"description" : "a boilerplate",
	"author" : "john",
	"dependencies": {
		"express": "^4.14.0",
		"moment": "~2.10.2"
	},
	"keywords": [
	  "freecodecampz"
	],
	"main": "server.js",
	"scripts": {
		"start": "node server.js"
	},
	"engines": {
		"node": "4.4.5"
	},
	"repository": {
		"type": "git",
		"url": "https://idontknow/todo.git"
	},
        "license" : "MIT"
}
```

**Comment by JosephLivengood** [comment]
Looks like the assert doesn't have a comma splitting the error string and regex its matching and has a potentially messed up regex. I'll take this, I made my changes but I'm going to test it a little harder later to make sure it'll work correctly in the future as intended. 👍
