### ISSUE TITLE
[beta] Map link anchored where you left off

### ISSUE THREAD

**Issue by KenzoM** [freeCodeCamp/freeCodeCamp#13104]
#### Issue Description
More of a suggestion versus an issue, but I found it a bit hassle that if I am working on a certain challenge and I want to see what challenges I will be facing next, the Map link will redirect me to the top of the list, rather than where I am currently in.

Since we do have a larger set of problems, it would be a nicer experience to automatically anchor where you are currently in the map course.

I am not sure if that is do-able in this case.

**Comment by Greenheart** [comment]
@KenzoM I like this idea. Maybe this could be saved locally in the user's browser? 

For example, we could use `localStorage` to keep 
```js
{
  anchor: '#Responsive Web Design',
  expandedChallenges: true
}
```

To handle cases where sections change name, we could allow this feature to fail gracefully if the anchor can't be found on the page. Challenges are not affected, as they have direct links rather than anchors.

**Comment by no-stack-dub-sack** [comment]
@Greenheart @KenzoM This would be huge, and something that's been mentioned before I believe in other issues, but it keeps going by the wayside. I personally think navigating around the current map is a major issue (with the loss of the foldaway map especially) and I think we should make exploring this more of a priority,

Great suggestion @KenzoM!

**Comment by HKuz** [comment]
That is a really useful feature, especially your point @KenzoM about there being so many more topics and challenges. I know there's a feature discussion about the map being placed to the left of the screen, showing where you are and giving more info (maybe including Wiki links). (See the screen shot in #11193). It's a different concept, but I figured I'd link the issues so we're aware that's in the works.

**Comment by KenzoM** [comment]
@HKuz That may be a better solution I would say then. Instead of going to the next page, I can still work on the code and not worry about restarting from scratch.

Awesome!
