### ISSUE TITLE
[beta] Clarify title for "Basic Data Structures: Copy an Array with slice()"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13110]
### Welcome first-time open source contributors! :trophy: 
Challenge [copy-an-array-with-slice](http://beta.freecodecamp.com/en/challenges/basic-data-structures/copy-an-array-with-slice) has an issue.

The title says "Copy an Array with slice()", but the challenge could be better described as "Copy Array items using slice()" as `Array.slice()` not only can copy whole arrays, but can copy individual items as well.

If you want to help fixing this, the [contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) can help you get started.

[This is the line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json#L235) where you can make this change.

Feel free to come chat with us in the [Contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) if you have any questions - or just want to say hi!

Good luck & Happy coding! :smile: :+1:

---

### Already resolved:
:white_check_mark: <strike>1. The test for this challenge does not run properly. The console gives me plenty of "Minified React Error #32", Similar to the message reported in #12656.</strike>

:white_check_mark: <strike>2. I originally thought the second test case just had a problem with formatting, but since there's nothing wrong with it, I suspect it has to do with the React error. However, I noticed that the second test could be improved with a cleaner assertion.
I suggest [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json#L259) gets replaced with 
`"assert(/\\.slice\\(/.test(code), 'message: The <code>forecast</code> function should utilize the <code>slice()</code> method');"`</strike>

**Comment by Greenheart** [comment]
I can fix the test case for now, but have no idea about the React error at this time.

**Comment by no-stack-dub-sack** [comment]
@Greenheart There's actually a lot of challenges in this section that use the `function().tostring()` format, because I wrote these before I knew about accessing user code through the `code` variable.  So there's several more that could be simplified in this way

**Comment by Greenheart** [comment]
@no-stack-dub-sack I'd say that we fix them once they break things. Then we can focus on other issues first :blush:

**Comment by no-stack-dub-sack** [comment]
@Greenheart Agreed!

**Comment by AlastairTaft** [comment]
Encase anyone else finds this issue. I hit this problem because I was missing a `<tbody />` tag inside my `<table /> element.

**Comment by systimotic** [comment]
@Greenheart 1 and 2 are now fixed, only three is left. It seems like a good idea to me. Do you want to do this, or should we mark this first-timers-only? Maybe open a new issue for 3 alone?

**Comment by Greenheart** [comment]
@systimotic This would be a good case for first-timers-only :blush:

I don't think we need a new issue - I'll just edit the original post and clarify what is left to be done.

**Comment by systimotic** [comment]
# First-timers only
Check out [CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) to get your local development environment set up.

Change the title of the "Copy an Array with slice()" challenge to "Copy Array items using slice()"
The code for this challenge can be found [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/d424b7331ded350e297387b134f5ab8e85631839/seed/challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json#L235). The file is `/seed/challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json`, line 235.

If you need help, please go to our [contributors chatroom](https://gitter.im/FreeCodeCamp/Contributors).

Happy coding!

**Comment by Greenheart** [comment]
@systimotic Haha looks like you're faster than me! :wink:

**Comment by systimotic** [comment]
Removed `first-timers-only` and `help-wanted` to avoid getting duplicate PR's, as we often do with `first-timers-only`
