### ISSUE TITLE
[beta] Update instruction for "Basic Data Structures: Iterate Through All an Array's Items Using For Loops"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13118]
Challenge [iterate-through-all-an-arrays-items-using-for-loops](http://beta.freecodecamp.com/en/challenges/basic-data-structures/iterate-through-all-an-arrays-items-using-for-loops) has an issue.

1. Remove the words "a simple", or possibly replace it with "the regular". [Reference](https://medium.freecodecamp.com/one-does-not-simply-learn-to-code-f25bacdc5b62#.cczgzdhyu)

2. The second sentence of the first paragraph can be misleading.

![misleading](https://cloud.githubusercontent.com/assets/6125097/22604634/cb9987ee-ea4c-11e6-8348-13f2f6bbb29f.png)

I think we need to highlight that it's array-methods, rather than just "built in methods" since the functions could be interpreted as if they were usable as they are, globally in JavaScript (similar to Python's global `map()` for example). 

I think something like the following could solve these issues:
> JavaScript arrays offer several built in methods that each iterate over the items to achieve slightly different results. `.forEach()`, `.every()` and `.map()` are some examples that makes common array-tasks easy. However, as each of these methods have been desinged with a specific purpose in mind, they don't work in all cases. When you need full flexibility and control, the best solution often is a regular `for`-loop

**Edit:** Should the highlighted "on" be changed to "in"?
![on-in](https://cloud.githubusercontent.com/assets/6125097/22607143/dd2b80b6-ea56-11e6-986c-c8730080c079.png)

**Comment by Manish-Giri** [comment]
I'd be interested in making this change, if it's confirmed..

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (114/100 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60260 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dnx4j-0003bV-2d
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:18:17 -0400
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:52329 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1dnx4f-0001yY-Ap
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:18:13 -0400
Date: Fri, 01 Sep 2017 18:15:55 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1504315092;
	bh=WqiC6AI6BdhGpZcJDPChRY1UneKkTSwL2YonlpOhssg=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=tSBIYBvwWJqQMbGCfuPl8LhFe/4TniCr1HtKLHd4vTHof+LBufyKAA2o4PFxxKQte
	 QJb0R/8U2BIpbu+pJo6Ma13uPC0wUIi/v3GZqZfgR5GGaPuniH/Q3+Q5Hlgzlr2Uv9
	 frUIi8MpmKYReZSZIWddCuACjqSaOk1CHE+wDznc=

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (115/100 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f48.google.com ([209.85.218.48]:35259)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx5V-003qxs-C5
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:49:16 +0530
Received: by mail-oi0-f48.google.com with SMTP id n18so13989147oig.2
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:18:44 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:date:dkim-signature:from:reply-to
         :to:cc:message-id:in-reply-to:references:subject:mime-version
         :content-transfer-encoding:precedence:list-id:list-archive:list-post
         :list-unsubscribe;
        bh=Besq7WIdgjHUOsEGBE5Xhoo79VrE6m9b8uc5K7fe5Aw=;
        b=R1qFGR96zbxLhnMgl6FWbN0rUN0682ljCf7O74aTnSVIscxs2y0oXsY7YqThU3opty
         tszGCja2pGWCdgu/UFKumySpgaMdakx16RViqS4vUIEo5ZWXqtqo4dGqghvQ8yCP+nya
         5g9C4ZhoPMlnwzjzaF3yySYXz9beXt5vdIITiatZRR8De6+UrL0mGOpf53+6sJ4KPkQn
         exxjglTjBGIGLKZaoIVZsbGDdgOWhL/s8zHoi+z+XDcqaA2peayfhAKKuiV9sIRMtzju
         7IerGsNq6BRKUrys3F+/yC2TjfW1W08iLuGta2N6+t12PdN3YxqHqhm8hrGgo8FS4owc
         bifw==
X-Gm-Message-State: AHPjjUiPuX6hfkKZLKOcmVMExnj3kc6ttUBvh82dFj6BS2bT3OZ+XunQ
	FverHz4ok/rIdiCvErOyEqrWZjE8BWwwHEp+9HjXGA==
X-Received: by 10.202.95.213 with SMTP id t204mr2374428oib.287.1504315102849;
        Fri, 01 Sep 2017 18:18:22 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1353848ofe;
        Fri, 1 Sep 2017 18:18:22 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb4gfGAkdGnuzkFtrM6Q1wj64qkNvtUl+m6qBgHPPr8gA+rRCDOUQbVONfoA17tDIY1xlyKK
X-Received: by 10.200.25.9 with SMTP id t9mr5147093qtj.220.1504315102016;
        Fri, 01 Sep 2017 18:18:22 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504315102; cv=none;
        d=google.com; s=arc-20160816;
        b=MRwANegwuV74UpDDxfmuA/HnahKRJ9xn3rLnKhtH3pSFTV4o2hTR+SPr+4tvEYINQj
         Qby1erqXpfVC41IrfraQovjdHXSnlIPD58xgQzR6OWjSfZEhrfd1d+dJ0KJs+rV68R4/
         Uxx/KMaM7AgIZihW/s0raLODEkI5a/o4Nc/5qW8i96GayXjfrx1FpWpVTotgrrckZEzX
         QrZE8Bgwmi00h61qYv6c7N5FlEfkGm0b/F5S4Fhc2In6rP05GYA86TtqJUh94NPr5zmG
         eTgGsM1mZ6VhMEU6gXYdsRyrdFePulBhxfxMC/gshMCytouq3k8wT/cSnj2a6SHHae4D
         J8+w==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:dkim-signature:date
         :arc-authentication-results;
        bh=Besq7WIdgjHUOsEGBE5Xhoo79VrE6m9b8uc5K7fe5Aw=;
        b=dorGHcQM3hPv6E8ZoSy2HKJsmErmTysIqutJufUHmH5YY7CbM8Ftm8yGYlAHpVPYGr
         VYdSUzd6s1Cynu5yWqBs4U9DDmMMfX81aqXf3bGctZFWyhkWU1Wh7hHqMj5xc4yUgaBH
         c4vWRJYSpQjseXzHaffzx1Oh2z59gFwnbKFAnndDyf3uFyaRUQud9bpOaJZblIZ0oFPe
         nj5i5oEhMqsun4qc3exQZz3izGjUE1TXtQDZ9lPjgNuxHJOt+BNQXlcQtnbmyDDVJtjy
         Wks4j9kP5LGnfjjhd/ZJuzkvXLgH+cOkIIgT3ycylMxizjgkWnbzEao7JNzPaLltAjgb
         ZzJA==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=Rik5agvd;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.194 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2-ext3.iad.github.net. [192.30.252.194])
        by mx.google.com with ESMTPS id v68si103957qkl.516.2017.09.01.18.18.21
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:18:22 -0700 (PDT)
Received-SPF: pass (google.com: domain of noreply@github.com designates 192.30.252.194 as permitted sender) client-ip=192.30.252.194;
Authentication-Results: mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=Rik5agvd;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.194 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Date: Fri, 01 Sep 2017 18:16:07 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1504315101;
	bh=Besq7WIdgjHUOsEGBE5Xhoo79VrE6m9b8uc5K7fe5Aw=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Rik5agvdvna5JvbmE1gvngqOD10uGmcSLldeVoSDD0D0gDRPy6iyxnxnSlJEhS6I2
	 /zLrw6g0eg+nRo9qaPYsS+KbM/8nzRmfhLtTRI52DzSj97+eUH4BkG4sBlIAUXx/D5
	 OjflgHe0/YLai1903nC0QqDMJRAzo24iuOUezqQw=
