### ISSUE TITLE
Basic JavaScript: Write Reusable JavaScript with Functions

### ISSUE THREAD

**Issue by Cyclokitty** [freeCodeCamp/freeCodeCamp#13112]
The challenge is referring to the previous myList variable from the Shopping List question that came before it. 

Challenge [write-reusable-javascript-with-functions](https://beta.freecodecamp.com/en/challenges/basic-javascript/write-reusable-javascript-with-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:48.0) Gecko/20100101 Firefox/48.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


// Example
function ourReusableFunction() {
  console.log("Heyya, World");
}

ourReusableFunction();

// Only change code below this line
function reusableFunction() {
  console.log("Hi World");
}

reusableFunction();

```

**Comment by JoubertBlanche** [comment]
I had the same problem. Delete the return reusableFunction();
And then press run. It will mark the first challenge green. Rewrite it again and it will go through.

**Comment by calluna** [comment]
I'm having issues with this one as well. The previous suggestion does not work for me. It keeps refusing to see it as correct.

`// Example
function ourReusableFunction() {
  console.log("Heyya, World");
}

ourReusableFunction();

// Only change code below this line

function reusableFunction() {
  console.log("Hi world");
}

reusableFunction();
`
![screen shot 2017-04-29 at 9 58 01 pm](https://cloud.githubusercontent.com/assets/844214/25561720/fbae6cca-2d26-11e7-8c95-e5fd856a9c82.png)

**Comment by AllstonS** [comment]
//The following worked for me:

// Example
function ourReusableFunction() {
  console.log("Heyya, World");
}

ourReusableFunction();

// Only change code below this line

function reusableFunction(){
  console.log("Hi World");
}

//This is calling the function after it has been defined

reusableFunction();

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
