### ISSUE TITLE
[beta] Consider changing the intent of "Basic Data Structures: Check For The Presence of an Element With indexOf()"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13115]
Challenge [check-for-the-presence-of-an-element-with-indexof](http://beta.freecodecamp.com/en/challenges/basic-data-structures/check-for-the-presence-of-an-element-with-indexof) has an issue.

```js
function quickCheck(arr, elem) {
  // change code below this line
  return arr.indexOf(elem) > -1;
  // change code above this line
}

// change code here to test different cases:
console.log(quickCheck(['squash', 'onions', 'shallots'], 'mushrooms'));
```

ES6 introduces the new method `Array.includes(element)` which is a much cleaner solution than `Array.indexOf(element) > -1`.

I suggest we create a new challenge to teach how to use `Array.indexOf(element)` to do what it's created for - finding the index. Here's an idea for such a challenge:
```js
// find the index of the 'rhino'
const animals = ['dog', 'shark', 'rhino', 'horse'];
const rhinoIndex = animals.indexOf('rhino') // 2
```

Then, we re-purpose this challenge to teach how to check if an item is present in an Array, using `Array.includes(element)`. Some parts of the instruction are ready to be used, and the tests probably won't need to change much.

These two challenges could be called
#### Get The Index of an Element With indexOf()

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (112/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60222 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dnx3T-0003Ty-72
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:59 -0400
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:56581 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1dnx3F-0001tG-HO
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:45 -0400
Date: Fri, 01 Sep 2017 18:16:39 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1504315004;
	bh=Q9d2DjJx5/16JweTOBcy8xwT8QSiAVp8Gb3lJnJ8YFY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=r+qms5SOGZDM0hfuJ/MfIXhWfxBcbQnQmBsa3PpTvq7ma/+RTepjFAS9bKND3Ir2h
	 2OUCd1pZIUB5M8yYzjvS+ZOWbYqENl60f8fgUPiBBjz/K4u7VimW7zCUQQ+2b7lLbt
	 R/9Xva/luBjEJYJR2/Ag2vzVAn9YBJs+979FWtUs=

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (112/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f43.google.com ([209.85.218.43]:34920)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx4B-003n8f-Pa
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:48:11 +0530
Received: by mail-oi0-f43.google.com with SMTP id n18so13977875oig.2
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:17:18 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:date:dkim-signature:from:reply-to
         :to:cc:message-id:in-reply-to:references:subject:mime-version
         :content-transfer-encoding:precedence:list-id:list-archive:list-post
         :list-unsubscribe;
        bh=3Y/i9DC87ZFfO+jGHZ10s4or2iSeZOKZnDbcLxoTLYs=;
        b=rzB/nV95bJGTNJOLZGZsNOF0oo01uI2nTJ3tc9lmlElpMaIUas7jxDCw2aTTwI/6i5
         elOvF+KBoW3FzYCgq4BFNe1vVyA1BqeT/smoHu+8RX69S2QueJeC5x4GJqQVcEDrh7Ps
         1IN7nQIMWa9rhXuI1x45ZDj2DF6UzyR7xvllyArR102hrgS5eye6bMDSWVPViuGgMWnj
         ri9D5cRJfdxuvoQe9fG29PawajWJOVtdifjEcAu1L6QrII/MeYCT+tJyy9YVkd5Zu/+W
         0JKQjQn6bMFNGWqh2vVWqDLc/pjVdo8SCQpTxlHdSnD8PgajbIK/14HlpfXj3R89PxTN
         UcKQ==
X-Gm-Message-State: AHPjjUiPefwweYbV1KFsIi85x2nGgl4ZtIaSVzqQ5rMOdUDT2SYdQWBX
	J92Cg3yfVdqukZNgLV6iUHKRkHsTuNMzHrySslZOjQ==
X-Received: by 10.202.179.137 with SMTP id c131mr3495452oif.298.1504315016577;
        Fri, 01 Sep 2017 18:16:56 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1352988ofe;
        Fri, 1 Sep 2017 18:16:55 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb7v3fUEovkQRryRxl/Q4zNByi9giK3GAU7gtuzY2iSVARhjMvUDfl/LjF0bYOKpdkChuoHE
X-Received: by 10.55.74.88 with SMTP id x85mr4961272qka.294.1504315015915;
        Fri, 01 Sep 2017 18:16:55 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504315015; cv=none;
        d=google.com; s=arc-20160816;
        b=RW7jIn3CpkBKJnu4wbcFy/d67UwivSjuTLSV8dfsRvy6t4iqvnZl8YiIjK6GdVJhvo
         XEwtlMG3pVNTQ7Yr1epcMf6FUbSIJE2t2Tp9YtDwY51cr8jD+Kq3Zpdo0Yb/6jOVZBC1
         iA3FJi0lGonbNqCHat8UOYKZ55UAZJgMipG52PpHLin+j0ae7OttJiWPK3C4jc9ABCkB
         j1YEK6qtVj9x+/x5B/NbMPRmf5W4Av1tWxiJqgjunDtkwpYUJ3/37xURFEfsxf5JPLFb
         vStKb6ZjP17gsrpb30pv16GHInE4mzqbM4e2PuR+/db3geG33/IlDlHFG9mPTft4MmTb
         /BWQ==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:dkim-signature:date
         :arc-authentication-results;
        bh=3Y/i9DC87ZFfO+jGHZ10s4or2iSeZOKZnDbcLxoTLYs=;
        b=gw9urX/n0qrG7FwN8azzcvHt/lutq3ShV5jBDIvX+b0nCW/Me8zvug0KvuHaMruxup
         1DZNYNSzY6yBFoS3jp5vFboWF0QZ9Val0lNuBBy1gQOh9Ik3mz1ljp7r4OKTsCmC0aKf
         i1Gc+zx0zHRWJArhJU22j6VGbphQaRxqKYFIWaWPs7Isw8R29WhG8zLD/OGq18mt6NQj
         rcWQQROxV8SXHdqNCdeJSTZMWId5CnAGiRA1RWX6g7uNUJeiIMmEavzwSJhMYGIH+AgU
         fjeXvQktHZrFY377ZDz6PDDBweJlfkbifu6e/V3HTB8IWLvKK3GJ8OJKNHLi0c4GFmrm
         blxA==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=oI6+I77O;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.192 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2-ext1.iad.github.net. [192.30.252.192])
        by mx.google.com with ESMTPS id r71si131649qka.117.2017.09.01.18.16.55
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:16:55 -0700 (PDT)
Received-SPF: pass (google.com: domain of noreply@github.com designates 192.30.252.192 as permitted sender) client-ip=192.30.252.192;
Authentication-Results: mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=oI6+I77O;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.192 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Date: Fri, 01 Sep 2017 18:16:51 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1504315015;
	bh=3Y/i9DC87ZFfO+jGHZ10s4or2iSeZOKZnDbcLxoTLYs=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=oI6+I77OgvmF6g8vetIxWbt748Y3zmDLLK2Vfma3U8uuPyYJcXQbrAuca4ArfrQw6
	 dopWpQtbgrhOhaGjW/yfNvAmGHTJZWEPf6oH6tLGU88iTPtm8ym8GnqeCS5S/mFKBL
	 v5QN4Rceh8+FAygWHlWichbBlxyatVmiCg3QTQA4=
