### ISSUE TITLE
[beta][UI][UX] Seeing multiple challenges with scrollbars for each parent div

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13121]
Parent divs have scrollbars
![screen shot 2017-02-03 at 3 36 14 pm](https://cloud.githubusercontent.com/assets/7606025/22612596/8c9848d0-ea26-11e6-9aeb-5356bdd5cdbc.png)
![screen shot 2017-02-03 at 3 36 24 pm](https://cloud.githubusercontent.com/assets/7606025/22612595/8c51fee8-ea26-11e6-96fc-57acd5db95c9.png)

**Comment by jburtiv** [comment]
Please remove me from the thread

**Comment by texas2010** [comment]
@jburtiv 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!
