### ISSUE TITLE
Commitments and Dedication

### ISSUE THREAD

**Issue by hangway** [FreeCodeCamp/FreeCodeCamp#1313]
The chat room is a good resource for code campers. We need to focus more on learning and sharing tips/resources to become competitive developers. This should be clear to all campers when they join.

**Comment by benschenker** [comment]
Closing as stale.  Take a look at the [wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki), if this sentiment is not there then edit it :smile:
