### ISSUE TITLE
Page Getting Unresponsive

### ISSUE THREAD

**Issue by Shubham-invent** [freeCodeCamp/freeCodeCamp#13134]
https://www.freecodecamp.com/challenges/sum-all-primes

This page is not reponding.Please have a look.
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by OFFLlNE** [comment]
@Shubham-invent Thank you for reporting your issue.

Try refreshing the page or restarting your browser. And if that solves your problem, just close the issue.
If not, then try to add some additional information about the issue you are having exactly

**Comment by vikramnr** [comment]
Page loaded pretty well

**Comment by Shubham-invent** [comment]
It gets alright by clearing cookies.
