### ISSUE TITLE
Night mode does not work on Firefox

### ISSUE THREAD

**Issue by vercellinoc** [freeCodeCamp/freeCodeCamp#13133]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
This is not a code issue. It is when night view is on, the left panel with the example lesson, some examples are all white-out. White on white. Can't see the text unless highlighted.

**Comment by raisedadead** [comment]
Can you please provide a screenshot?

**Comment by vercellinoc** [comment]
False alarm. I forgot that the night mode option in settings doesn't work on Firefox so I installed a dark themed script for the page. Why doesn't night mode work on Firefox?
Thanks

**Comment by systimotic** [comment]
Night mode works fine for me on Firefox 51.0.1 on Windows 10. Never had any issues with night mode as a regular Firefox user. 
@vercellinoc Does night mode work for you in other browsers? Are you logged in on Firefox?

**Comment by vercellinoc** [comment]
MS Edge works fine, no big deal. It may be ad-blocker interfering. Stylish plugin is awesome and works fine when its fine-tuned.
Thanks
