### ISSUE TITLE
Videos for Applied Challenges give error

### ISSUE THREAD

**Issue by DarrenfJ** [freeCodeCamp/freeCodeCamp#13138]
Challenge [build-a-tribute-page](http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-survey-form) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Not sure this is a problem, but three of three of the vids don;t play just give me errors. I am assuming here they just haven;t been created yet?

**Comment by raisedadead** [comment]
We are replacing videos with static images, refer: https://github.com/freeCodeCamp/freeCodeCamp/issues/12753

Closing as these would be removed per the other thread.
