### ISSUE TITLE
Correct solution but I still fail all the tests

### ISSUE THREAD

**Issue by tsalexey544** [freeCodeCamp/freeCodeCamp#13140]
Challenge [No repeats please](https://www.freecodecamp.com/challenges/no-repeats-please) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.

All my answers are correct, but I still fail all the tests. 

My code:
```javascript
function permutationArr(num) {
  var arr = (num + '').split(''),
    permutations = [];

  function swap(a, b) {
    var tmp = arr[a];
    arr[a] = arr[b];
    arr[b] = tmp;
  }

  function generate(n) {
    if (n == 1) {
      permutations.push(arr.join(""));
    } else {
      for (var i = 0; i != n; ++i) {
        generate(n - 1);
        swap(n % 2 ? 0 : i, n - 1);
      }
    }
  }

  generate(arr.length);
  
  return permutations.filter(a => {
    var arr = a.split("")
    for (let i = 1; i <= arr.length; ++i) {
      if (arr[i] == arr[i - 1]) {
        return false;
      }
    }
    return true;
  }).length;
}

permutationArr('abfdefa');
```

**Comment by tsalexey544** [comment]
Got it

**Comment by ronaldblanco** [comment]
Hello;

I am having that same problem, all the test give the right number but the page does not get it as pass.
Did you find were was the problem?

This is my code and I have tried in firefox an internet explorer:

var permArr = [], usedChars = [];
function permute(input) {
  var i, ch, chars = input.split("");
  for (i = 0; i < chars.length; i++) {
    ch = chars.splice(i, 1);
    usedChars.push(ch);
    if (chars.length === 0)
      permArr[permArr.length] = usedChars.join("");
    permute(chars.join(""));
    chars.splice(i, 0, ch);
    usedChars.pop();
  }
  return permArr;
}



function factorial(num)
{
    // If the number is less than 0, reject it.
    if (num < 0) {
        return -1;
    }
    // If the number is 0, its factorial is 1.
    else if (num === 0) {
        return 1;
    }
    var tmp = num;
    while (num-- > 2) {
        tmp *= num;
    }
    return tmp;
}


function repet(myarr){
  var cant = 0;
  for(var i = 0; i < myarr.length;i++){
    for(var j = 0; j < myarr[i].length - 1;j++){
      if(myarr[i][j] == myarr[i][j + 1]){
        cant++;
        j = myarr[i].length;
        
      } 
    }
  }
  return cant;
}


function permAlone(str) {
  var cant = factorial(str.length);
  return cant - repet(permute(str));
}

permAlone('aaab');
