### ISSUE TITLE
Understanding Uninitialized Variables - Instruction and Checklist values do not match

### ISSUE THREAD

**Issue by ayaqubi** [freeCodeCamp/freeCodeCamp#13147]
#### Understanding Unitialized Variables
https://www.freecodecamp.com/challenges/understanding-uninitialized-variables

#### Issue Description
The values in the instruction do not match the values in the checklist at the bottom.

#### Browser Information
Google Chrome

![github screenshot](https://cloud.githubusercontent.com/assets/23462067/22622364/815cb7a8-eafd-11e6-9e7b-9b1fc35602a8.PNG)

**Comment by Manish-Giri** [comment]
@ayaqubi The values at the bottom depict the values of the variables after these operations are executed on them - 
```
a = a + 1;
b = b + 5;
c = c + " String!";
```
For instance, if you initialize `a` with `5`, as the instructions asks you to - then after `a = a + 1;`, value of `a` will be `6`, which is what the checklist at the bottom says.

**Comment by ayaqubi** [comment]
Oh. That makes sense now.  I didn't understand that originally.  Thank you for clearing that up for me.

**Comment by naphelge** [comment]
@ Manish-Girl I ran to the exact same problem, unfortunately your explanation does not resolve the issue. Instructions read:

> Initialize the three variables **a**, **b**, and **c** with **5**, **10**, and "**I am a**" respectively so that they will not be undefined.

and Result warning reads:

> **a** should be defined and have a value of **6**
> **b** should be defined and have a value of **15**
> **c** should not contain undefined and should have a value of "**I am a String!**"

There is no mention of "executing" any "operations... on them" at this step, so this would definitely seem to be a bug that needs to be addressed.

**Comment by Johnishaya** [comment]
a=5 ; b = 10 ; c ="I am a";
