### ISSUE TITLE
Accessing Nested Objects

### ISSUE THREAD

**Issue by rahul-1903** [freeCodeCamp/freeCodeCamp#13142]
Challenge [Accessing Nested Objects](https://www.freecodecamp.com/challenges/accessing-nested-objects#?solution=%0A%2F%2F%20Setup%0Avar%20myStorage%20%3D%20%7B%0A%20%20%22car%22%3A%20%7B%0A%20%20%20%20%22inside%22%3A%20%7B%0A%20%20%20%20%20%20%22glove%20box%22%3A%20%22maps%22%2C%0A%20%20%20%20%20%20%22passenger%20seat%22%3A%20%22crumbs%22%0A%20%20%20%20%20%7D%2C%0A%20%20%20%20%22outside%22%3A%20%7B%0A%20%20%20%20%20%20%22trunk%22%3A%20%22jack%22%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20gloveBoxContents%20%3D%20myStorage.car.inside%5B%22globe%20box%22%5D%3B%20%2F%2F%20Change%20this%20line%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStorage = {
  "car": {
    "inside": {
      "glove box": "maps",
      "passenger seat": "crumbs"
     },
    "outside": {
      "trunk": "jack"
    }
  }
};

// Only change code below this line

var gloveBoxContents = myStorage.car.inside["glove box"]; // Change this line


```

**Comment by Manish-Giri** [comment]
@rahul-1903 Your code has a typo - `["globe box"]`.

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) first if you need help with issues like these, in future. Happy Coding!

**Comment by raisedadead** [comment]
Hi @rahul-1903 

Looks like you have edited the thread above to fix the typo that was in the original code.
Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
