### ISSUE TITLE
[beta] Serve an HTML File (basic node) - solution not passing test

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#13148]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/basic-node-and-express/serve-an-html-file

#### Issue Description

cc / @JosephLivengood @Greenheart @Em-Ant 
Have the correct solution (shown below), compared to the solutions boilerplate, but test does not pass for this challenge. I seem to be serving the right file, so not sure what's up - getting the error "unexpected string" in the embedded FCC console and no errors in the real console. 

#### Browser Information

* Browser Name, Version: Chrome, latest
* Operating System: OSX 10.11.7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
Project Link: https://gomix.com/#!/project/penitent-shield

```js
/** 2) A first working Express Server */
// app.get("/", function(req, res) {
//   res.send("Hello Express")
// });

/** 3) Serve an HTML file */
app.get("/", function(req, res) {
  res.sendFile(__dirname + "/views/index.html")
});
```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/18563015/22623117/4ca03e2a-eb1d-11e6-9eb6-ade07a09664b.png)

**Comment by JosephLivengood** [comment]
I found the error in the testing code, I'll submit a PR in a moment
