### ISSUE TITLE
Waypoint: Create a Form Element - showing correct even when opening form is not closed

### ISSUE THREAD

**Issue by rbtmarshall** [FreeCodeCamp/FreeCodeCamp#1314]
32. Waypoint: Create a Form Element

When working on this challenge I was prompted to move onto the next challenge. Then I noticed that the text input box disappeared from the app.

So I looked back at what I input and noticed that I forgot to close the opening form tag
http://i.imgur.com/s5r5Zoq.png

I'm glad I didn't move along thinking I did it correctly, but also wondered how many others may have made the same mistake thinking they were correct.

**Comment by benschenker** [comment]
Closing as duplicate of #1081
