### ISSUE TITLE
There are more (common) ways of using CSS

### ISSUE THREAD

**Issue by Hapoofesgeli** [freeCodeCamp/freeCodeCamp#13145]
Challenge [introduction-to-basic-css](http://beta.freecodecamp.com/en/challenges/basic-css/introduction-to-basic-css) has an issue.

> CSS can be applied both as inline styles—typed directly within HTML style tags—or external style sheets—typed in a separate file that is referenced from your HTML file. 

The text implies there are two ways of using CSS, and ignores using CSS via `style` attribute.

As [W3 describes](https://www.w3.org/TR/CSS2/intro.html#design-principles):

> Flexibility. CSS can be applied to content in several ways. The key feature is the ability to cascade style information specified in the default (user agent) style sheet, user style sheets, linked style sheets, the document head, and in attributes for the elements forming the document body.

_This bug is targeted for the beta version._

**Comment by Greenheart** [comment]
@Hapoofesgeli Thanks for reporting this!

This sentence could be clarified. I've left some ideas below.
> CSS can be applied in many different ways. Either as inline styles, typed directly within HTML `<style>` tags, or through external style sheets. (...)

> There are three main ways to apply CSS. Inline styles, typed directly in the `style` attribute on elements, CSS typed within HTML `<style>` tags and external style sheets. Even though the first two have their use cases, most developers prefer external style sheets. This is because they keep the styles separate from the HTML elements, therefore improving the readability and reusability of your code.

/cc @HKuz

**Comment by HKuz** [comment]
@Hapoofesgeli - thanks for pointing this out, we can clarify this sentence 👍 

@Greenheart - I can open a quick PR for this, I'm going to take your 3rd option and tweak it a little bit 😄 stay tuned...

**Comment by Greenheart** [comment]
@HKuz Thanks, ping me and I can review it!

**Comment by HKuz** [comment]
Will do @Greenheart - you've been a machine on the issues/PRs lately! 🔥 :1st_place_medal:

**Comment by Greenheart** [comment]
@HKuz Haha thanks! I figured the fastest way to get these challenges ready is to help finish them :smile: :+1:
