### ISSUE TITLE
i am unable to perform this operation can u provide solution please

### ISSUE THREAD

**Issue by Nagabhairavanitish** [freeCodeCamp/freeCodeCamp#13154]
Challenge [Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%0A%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20phoneticLookup(val)%20%3D%20%7B%0A%0A%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22charlie%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
var phoneticLookup(val) = {

}
  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");

```

**Comment by raisedadead** [comment]
Hi @Nagabhairavanitish 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
