### ISSUE TITLE
[beta] Bug in seed code for "Functional Programming: Refactor Global Variables Out of Functions"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13157]
Challenge [refactor-global-variables-out-of-functions](http://beta.freecodecamp.com/en/challenges/functional-programming/refactor-global-variables-out-of-functions) has an issue.

According to the instructions, the goal of this challenge is to 
> Refactor (rewrite) the code so the global array `bookList` is not changed inside either function.

Another requirement (which doesn't seem to be be tested for) is that
> Both functions should return an array

The problem is that the initial `challengeSeed` doesn't meet the second requirement since neither `Array.push()` nor `Array.splice()` returns the updated array. Since the challenge's intention seems to be to "Refactor Global Variables Out of Functions", I think this needs to be fixed, so campers can focus on removing global variables rather than making the code work.

To resolve these issues, I think we should
* Make sure the functions in the `challengeSeed` returns the updated array, as their doc strings says.
* Possibly add tests to verify that the functions do return an array. 

```js

// the global variable
var bookList = ["The Hound of the Baskervilles", "On The Electrodynamics of Moving Bodies", "Philosophiæ Naturalis Principia Mathematica", "Disquisitiones Arithmeticae"];

/* This function should add a book to the list and return the list */
// New parameters should come before the bookName one

// Add your code below this line
function add (bookName) {
  
  return bookList.push(bookName);
  
  // Add your code above this line
}

/* This function should remove a book from the list and return the list */
// New parameters should come before the bookName one

// Add your code below this line
function remove (bookName) {
  if (bookList.indexOf(bookName) >= 0) {
    
    return bookList.splice(0, 1, bookName);
    
    // Add your code above this line
    }
}

var newBookList = add(bookList, 'A Brief History of Time');
var newerBookList = remove(bookList, 'On The Electrodynamics of Moving Bodies');
var newestBookList = remove(add(bookList, 'A Brief History of Time'), 'On The Electrodynamics of Moving Bodies');

console.log(bookList);

```

**Comment by fonsecapontes** [comment]
@Greenheart Can I solve this issue? If no one are working in this.

**Comment by Greenheart** [comment]
@fonsecapontes Sure! Refer to [the contributing guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) and come chat with us in [/Contributors](https://gitter.im/FreeCodeCamp/Contributors) if you need help with anything :smile:

**Comment by Greenheart** [comment]
I really like the idea of only using local variables in functions, but it feels like this challenge is trying to do too much at one time.

Maybe we could split the concepts into two smaller challenges:
### 1. Refactor Global Variables out of Functions
* Use similar `challengeSeed` to what we have now.
* The goal is to replace the global variable `bookList` with a function-parameter (that campers decide the name for).

### 2. Avoid Mutating External Variables
* Builds upon the `challengeSeed` from the previous challenge.
* The goal is to teach why and how to avoid modifying variables you get passed to your functions.
* In this case, this could be about using `Array.prototype.slice()` to create a copy before changing any data in the array with books.

What do you think? :blush:

**Comment by shashank7200** [comment]
Reconfirming the Bug. 
Browser: Chrome 58.0.3029.81 (64 bit)

**Comment by ffahd** [comment]
Ff

**Comment by ffahd** [comment]
Fffd

**Comment by QuincyLarson** [comment]
@Greenheart We just launched the new learning platform and expanded curriculum here: https://learn.freecodecamp.org - take a look at it and let me know what you think :)

Would you be interested in helping fix this challenge?

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (121/100 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:40464)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPURR-00006G-7J
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:57:09 -0400
Received: from out-2.smtp.github.com ([192.30.252.193])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUQm-0006RU-Fz
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:56:28 -0400
Date: Sun, 03 Jun 2018 07:56:27 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037787;
	bh=5iq/uRIXdS/uL9i+07UrHX7EXStU+hZ7J30ZhIRKwuM=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=TDl+Q5A1SDSVrciXyWPxKsiOEoq6vDAWjny68voQyF2EYvRR4rTgVKSh8226vcyqs
	 O1sOtvxLanCEbGIwcs85ydXaRx7QEZc2JNKe+1Lvr9mXtIixcTkmlhfakQpH6w0lS3
	 PSJIa1UKQik9X2iTFUiE53K+QsrKGeFIXGpqn5Dw=

**Comment by zberwaldt** [comment]
@QuincyLarson can I take a crack at it?

**Comment by MilanAjtic** [comment]
@QuincyLarson Please, someone fix this, it's been like that for sooooo long...

**Comment by rabindranathfv** [comment]
any advance with this i try 2 solutions using local variables inside off function and does't work, and when i try to use slice or indexOf method for arrays the console told me "this xxxx is not a function"

**Comment by BurnhamG** [comment]
Apologies for the multiple commits; I made a mistake and accidentally changed the commit hash a few times. Anything else going forward will be a commit to fix build issues.

**Comment by nikrb** [comment]
this challenge is [here](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/refactor-global-variables-out-of-functions) now and seems to work. master seems to work locally.
The [pr](https://github.com/freeCodeCamp/freeCodeCamp/pull/32355) adds two tests checking array is returned and also works locally.

**Comment by BurnhamG** [comment]
@patricktownley Great catch! That was an actual mistake that I missed with past commits. I've made the appropriate changes in my pull request to take care of that issue as well.
