### ISSUE TITLE
Issue with Profile Lookup Challenge

### ISSUE THREAD

**Issue by nwrightdesign** [freeCodeCamp/freeCodeCamp#13150]
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Okay, so I got all the correct responses for the various test cases except when I use "Akira"  "address" it is marked as incorrect though the output is right. See link to screenshots below...

Mozilla Firefox
https://drive.google.com/file/d/0B-X9hr9vzhXQckk5LW1McXlaOVk/view?usp=sharing

Google Chrome
https://drive.google.com/file/d/0B-X9hr9vzhXQaVhHM3g4bnVYcGc/view?usp=sharing

My code:
```javascript

//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];

function lookUpProfile(firstName, prop){
// Only change code below this line
  var value = "";
  
  for (var i = 0; i < contacts.length; i++){
    
    if (contacts[i].firstName === firstName){
      return (contacts[i].hasOwnProperty(prop) ? contacts[i][prop] : "No such propertry");
    } else {
      value = "No such contact";
    }
  }
  
  return value;
  
// Only change code above this line
}

// Change these values to test your function
lookUpProfile("Akira", "address");

```

**Comment by cdrainxv** [comment]
@nwrightdesign: Consider the following:
 1. `property` not `propertry`
 2. You can only confirm that a contact doesn't exist ***after*** looping through the entire contacts array and not finding the contact. Currently outside of the loop you are returning an empty string.


Please visit the [Help JS room](https://gitter.im/FreeCodeCamp/HelpJavaScript) first if you need help with issues like these in the future. Happy Coding!

**Comment by nwrightdesign** [comment]
@cdrainxv cdrainxv: Thanks for pointing out the typo. Did you take a look at the screen shot?

**Comment by nwrightdesign** [comment]
@cdrainxv: Thanks for pointing out the typo.
