### ISSUE TITLE
Bonfire #38, Arguments Optional

### ISSUE THREAD

**Issue by Phadion** [FreeCodeCamp/freecodecamp#1315]
Challenge http://www.freecodecamp.com/challenges/bonfire-arguments-optional has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

After running my code, it doesn't pass a few tests. For example: 

It is running the following test: 'add(2)(3))' and 'add(2)([3])'. I do not know whether '2)(3)' and '2)([3]'  are  valid arguments. 

Maybe the tests are supposed to be written differently? 

<img width="440" alt="screen shot 2015-07-16 at 3 36 45 pm" src="https://cloud.githubusercontent.com/assets/6315700/8736793/93f2b946-2bd0-11e5-8c38-e1f8de022d8c.png">

**Comment by benmcmahon100** [comment]
Sorry about that this is and issue that has been fixed but not yet deployed to the production enviroment. We hope to have it out soon!

**Comment by abbynormative** [comment]
Hi, has this fix been deployed yet? I have coded a solution that I think should work, but fails on "expect(add(2)(3)).to.equal(5);expected 6 to equal 5."

**Comment by benmcmahon100** [comment]
No the fix has not yet been deployed but there is no issue with that check your code is wrong. How can 2 + 3 be 6?

**Comment by royshouvik** [comment]
Hi @Phadion , I would recommend you review the topic of JavaScript closures before attempting this bonfire. The challenge doesn't have any problem. Please consider closing this issue and discuss on chat room about how to solve this bonfire. Thanks.
