### ISSUE TITLE
Bonfire: Search and Replace

### ISSUE THREAD

**Issue by KevinHenrick** [FreeCodeCamp/FreeCodeCamp#1316]
The code below completes all of the checks for the Search and Replace Bonfire, but it's not giving an overall pass (see image of all completed checks at the bottom).
```
function replace(str, before, after) {
  arr=str.split(" ");
  for(i=0;i<arr.length;i++){
    if(arr[i]==before){
      arr[i]=after;
      str = arr.join(" ");  
    }
    else {
      return str;
    }
    
  }
 return str;
}

replace("A quick brown fox jumped over the lazy dog", "jumped", "leaped");
  }
 return str;
}
```
![screen shot 2015-07-16 at 4 55 51 pm](https://cloud.githubusercontent.com/assets/2448491/8737855/d7e19d92-2bdb-11e5-830d-242d7ff0dfe7.png)

**Comment by benschenker** [comment]
This code does not work for http://www.freecodecamp.com/challenges/bonfire-search-and-replace

Closing, reopen if you are still having issues with this
