### ISSUE TITLE
Waypoint: Manage Packages with NPM instructions unclear

### ISSUE THREAD

**Issue by 1hella** [FreeCodeCamp/FreeCodeCamp#1317]
Challenge http://www.freecodecamp.com/challenges/waypoint-manage-packages-with-npm has an issue.

To install the package, the instructions say `Run this command: npm install how-to-npm -g`, which works fine. Then it says `Now start this tutorial by running npm install how-to-npm@2.0.0.`, which does not start the tutorial. It installs the package a second time but not globally. In the video it says you can run the tutorial using `how-to-npm`. 

Maybe the first line should say install it using `sudo npm install how-to-npm@2.0.0 -g`, and you can start the tutorial using `how-to-npm`. I believe you need to use `sudo` to install how-to-npm globally anyways.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/6580703/8740760/ec86a120-2c03-11e5-9b88-00a851f010a7.png)

**Comment by SaintPeter** [comment]
I experienced this issue as well.  I farted around until I made it work.

The instructions need to be updated.

**Comment by 1hella** [comment]
Yeah exactly. You can figure it out if you watch the video but the instructions are pretty unclear.

**Comment by benschenker** [comment]
This seems to be fixed.
