### ISSUE TITLE
2月1日台灣國內交通事故報導

### ISSUE THREAD

**Issue by Az613Lee** [freeCodeCamp/freeCodeCamp#13180]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by OFFLlNE** [comment]
@Az613Lee Thank you for reporting the issue.
I don't see any information about your issue that you are having. Only the chinese letters in header
Could you provide more information on the issue you are having

**Comment by raisedadead** [comment]
Spam. Refer [this](https://translate.google.com/#auto/en/2%E6%9C%881%E6%97%A5%E5%8F%B0%E7%81%A3%E5%9C%8B%E5%85%A7%E4%BA%A4%E9%80%9A%E4%BA%8B%E6%95%85%E5%A0%B1%E5%B0%8E)
