### ISSUE TITLE
Zipline Using Package.json issue [beta]

### ISSUE THREAD

**Issue by forkerino** [freeCodeCamp/freeCodeCamp#13184]
Using Package.json, The Core of Any Node.js Project or npm Package
http://beta.freecodecamp.com/en/challenges/managing-packages-with-npm/using-packagejson-the-core-of-any-nodejs-project-or-npm-package

The zipline mentions the following: 
>If you go to the HyperDev-project that you set up previously

There is only one exercise before this in this certificate and this doesn't mention HyperDev at all.

**Comment by Greenheart** [comment]
@forkerino Thanks for helping QA the backend section! We really need more people like you :smile:

This is already being discussed in #13091 so I'm closing this.
