### ISSUE TITLE
Challenge is not suitable for Intermediate Algorithm Scripting

### ISSUE THREAD

**Issue by quantummechanist** [freeCodeCamp/freeCodeCamp#13186]
#### Challenge Name
https://www.freecodecamp.com/challenges/finders-keepers 

#### Issue Description
Challenge is definitely not suitable for Intermediate Algorithm Scripting. As per issue #8161, and should be moved to basic algorithmic scripting.

This is an issue despite the discussion in #8161, because the solution is not only a one-liner, but a one-function one-liner that requires one lookup in the Javascript docs. It's less than elementary, it's trivial, and a waste of time at this stage. At intermediate algorithm level it should be evident that simply redefining basic JavaScript API names in one's application is not only wasteful, but bad in team coding environments. Functions should have a purpose of their own, extending functionality, not simply redefining terms.

It is so apparently out of place that it immediately raises questions of whether the question is defined properly (that slightly off-API functionality was actually desired), or the tests are insufficient, or both. This is a bug issue for that very reason, and not a curriculum issue, since it is very liable to be perceived as a bug.

**Comment by raisedadead** [comment]
Hi, thanks for your feedback.

This has been moved to basic algorithm scripting on out staging website (https://beta.freeCodeCamp.com), we will have this on the main website in the next release.

Closing, happy coding!
