### ISSUE TITLE
[beta] Consider adding additional test case for "Basic Algorithm Scripting: Finders Keepers"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13183]
Challenge [finders-keepers](http://beta.freecodecamp.com/en/challenges/basic-algorithm-scripting/finders-keepers) has an issue.

```js
function findElement(arr, func) {
  return arr.find(func);
}

findElement([1, 2, 3, 4], function(num){ return num % 2 === 0; });
```

Thanks to ES6, this algorithm is completely solved by the built in `Array.prototype.find()` method.
Maybe we should add a test case that ensures campers don't use this, but rather write their own code?

**Comment by Manish-Giri** [comment]
I'm on it..
