### ISSUE TITLE
remove <code> tags

### ISSUE THREAD

**Issue by forkerino** [freeCodeCamp/freeCodeCamp#13181]
Challenge [enhanced-object-literals--functions](http://beta.freecodecamp.com/en/challenges/es6/enhanced-object-literals--functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

There are some \<code\> tags in the tests at the bottom. Prevents one to pass the test. Works fine if removed. 

```js
/* Alter code above this line */
<code>const zod = Person("Zodiac Hasbro", 56, 'male');</code>
<code>const yan = Person("Yanoshi Mimoto", 55, 'male');</code>
<code>zod.sendFriendRequest(yan);</code>

```

**Comment by yzhbankov** [comment]
this is a bug
the <code> tag should be removed

**Comment by nesterone** [comment]
Hi, guys 

In which branch development of 'beta' taking place ?

**Comment by yzhbankov** [comment]
What you think about removing `<code>` tags from  https://github.com/yzhbankov/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/es6.json ?
lines 686-688
        "<code>const zod = Person(\"Zodiac Hasbro\", 56, 'male');</code>",
        "<code>const yan = Person(\"Yanoshi Mimoto\", 55, 'male');</code>",
        "<code>zod.sendFriendRequest(yan);</code>"
I think so because I didn't found usage of 'code' tag in 'challengeSeed' for other challenges, it looks like mistype for me

**Comment by raisedadead** [comment]
@nesterone thanks a lot for your interest, please have a look at our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by nesterone** [comment]
@raisedadead 
Thanks, gonna read it

**Comment by fonsecapontes** [comment]
@raisedadead can I remove this tag from code? If no one are working in this issue.

**Comment by raisedadead** [comment]
Hi thanks for your interest but we already have open pull request for this, please check the tracked for issues tagged help wanted.
