### ISSUE TITLE
Missing Semicolon

### ISSUE THREAD

**Issue by MaximilianJugendForscht** [freeCodeCamp/freeCodeCamp#13191]
Challenge [Multiply Two Decimals with JavaScript](https://www.freecodecamp.com/challenges/multiply-two-decimals-with-javascript#?solution=%3B%0Avar%20product%20%3D%202.0%20*%20(5.0%2F2.0)%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
; //I get an error without this
var product = 2.0 * (5.0/2.0); 



```

I am assuming that there is some code before the needed segment. 

Interestingly enough there is a missing semicolon I had to put in for myself in order to make it work (see my code). I think, someone missed the hide and seek master

**Comment by raisedadead** [comment]
I could pass the challenge with the above code and without the additional semicolon. Please try a reset and retry. Can you share some screenshots as well?

**Comment by MaximilianJugendForscht** [comment]
Ok,  appearently it got fixed...  Or its only on my workspace... Firefox got weird ever time -.-

**Comment by MaximilianJugendForscht** [comment]
Ok,  appearently it got fixed...  Or its only on my workspace... Firefox got weird ever time -.-

**Comment by raisedadead** [comment]
Possibly related https://github.com/freeCodeCamp/freeCodeCamp/issues/12644. 
Can you check if you were able to work without issues on Chrome, if you are able.

Thanks.
