### ISSUE TITLE
Rename all coursewares 'challenges' and ensure old challenge infrastructure is removed

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/freecodecamp#132]

**Comment by RonakR** [comment]
Hey Quincy, could I get more info on this? 
Thanks!

**Comment by terakilobyte** [comment]
@RonakR on this specific issue? 

Every mention of courseware needs to be renamed to challenge and we're yanking the entire legacy challenge system out.

**Comment by BerkeleyTrue** [comment]
Should this be on the reactify milestone or is this for master?

**Comment by terakilobyte** [comment]
I think reactify as that's where we're making the massive changes to the challenge framework since UX design has been morphed into reactify.

**Comment by RonakR** [comment]
Coolio, thanks for the update terakilobyte. 
I'll get started on this if that's okay.

**Comment by terakilobyte** [comment]
Awesome. If you have screenhero add us and shout out if you have any questions.

**Comment by RonakR** [comment]
I do not have a screenhero ( didn't even know what it was until I googled it ). It looks like I can not sign up for a new account. 

Chances are I'll have a bunch of question, haven't contributed to open source before but I've completed all the challenges and I thought I'd give this a shot.

**Comment by terakilobyte** [comment]
I've just sent you an invite for screenhero. I also suggest hopping into our gitter! The badge with a link is in the readme.

**Comment by RonakR** [comment]
Got it! Thanks! 
And I'll get on Gitter right now.

**Comment by BerkeleyTrue** [comment]
@QuincyLarson How far is this from completion? Are link titles to be changed as well?

**Comment by RonakR** [comment]
Hey @BerkeleyTrue, I've been working on this and I'm digging through all the changes I have to make. 

I've got one question for either of you though, there are a couple files named courseware, i.e. controllers/courseware, models/courseware etc. But in the same folders there are files named challenges.  
My question is should I delete the files named courseware, or rename those files and others mentions in those files to challenges and delete the challenges file? 

If this is confusion let me know and I can try to word it better.

Thanks,
Ron.

**Comment by BerkeleyTrue** [comment]
@RonakR Have you been committing changes? I think @QuincyLarson and @terakilobyte have made a lot of progress on this today.

@QuincyLarson / @terakilobyte  Can you comment?

**Comment by RonakR** [comment]
Whoops, I was not aware there were other people working on this too. My bad.
No I haven't committed anything yet because I haven't made any changes. I didn't want to start gutting this w/out making sure I was on the correct path.

**Comment by BerkeleyTrue** [comment]
You might want to pull latest changes and see where we are at. This branch is moving fast and we will start building React components soon so we need all these issues resolved.

**Comment by RonakR** [comment]
Coolio. What branch are the changes in? I just made my own (but I haven't pushed it yet, since there were no changes).

**Comment by BerkeleyTrue** [comment]
reactify

**Comment by RonakR** [comment]
Thanks!

**Comment by BerkeleyTrue** [comment]
:+1:

**Comment by RonakR** [comment]
I just ran a diff between reactify and master to comprehend the changes being made and I realized I'll just slow you all down. XD
I'm gonna get off this issue, but I'll look for another one that I can work on that wouldn't be a huge roadblock if I took some time. :)

**Comment by terakilobyte** [comment]
You are welcome to help, we love contributions. If this issue isn't as
appealing to you, let us know and we can definitely dish out some
additional ones.

**Comment by RonakR** [comment]
Don't get me wrong, I want to contribute. I'm working on my own project in MEAN and learning React on the side. But, I'm afraid I'll only slow you all down. If there are smaller task that I could look at I'd be more than glad to.

I just set myself up for the linting task. Got everything installed and was running through some of the errors and I realized I didn't know how to solve most of them. XD

**Comment by QuincyLarson** [comment]
Hi everyone, sorry for the delyed response here. I just want to clarify that @berkeleytrue and @terakilobyte decided we're going to leave these as "coursewares" in the system and just call them challenges in the routes and other user facing places.
