### ISSUE TITLE
[beta][curriculum] Rewrite instructions for challenge: Add Images to your Website

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13204]
**Link to challenge:** http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/add-images-to-your-website

**Current instructions:** 
Basic HTML and HTML5: Add Images to your Website
`<hr>`
You can add images to your website by using the img element, and point to a specific image's URL using the src attribute.

An example of this would be:

<img src="https://www.your-image-source.com/your-image.jpg">

All img elements must have an alt attribute. The text inside an alt attribute is used for screen readers to improve accessibility and is displayed if the image fails to load.

Let's add an alt attribute to our img example above:

<img src="https://www.your-image-source.com/your-image.jpg" alt="Author standing on a beach with two thumbs up.">

Note that in most cases, img elements are self-closing.

`<hr>`
Try it with this image:

https://bit.ly/fcc-relaxing-cat
`<hr>`

**Rewritten instructions:**
Basic HTML and HTML5: Add Images to your Website
`<hr>`
You can add images to your website by using the img element, and point to a specific image's URL using the src attribute.

An example of this would be:

<img src="https://www.your-image-source.com/your-image.jpg">

All img elements must have an alt attribute. The text inside an alt attribute is used for screen readers to improve accessibility and is displayed if the image fails to load.

Note that in most cases, img elements are self-closing.

`<hr>`
Let's add an alt attribute to our img example above:

<img src="https://www.your-image-source.com/your-image.jpg" alt="Author standing on a beach with two thumbs up.">

Try it with this image:

https://bit.ly/fcc-relaxing-cat

`<hr>`

**Comment by HKuz** [comment]
@tommygebru - thanks for going through this challenge! I like the idea to move the sentence "Note that in most cases, `img` elements are self-closing" up. I'd actually put it right after the `<img>` code example, and before the paragraph about the `alt` attribute ("All `img` elements must have an `alt` attribute...). That said, I don't think the `<hr>` should be moved. They're used to visually separate the challenge text from the instructions for the camper, and the "Let's add an alt attribute to our `img`... and the pink code below it are part of the example showing campers how to add the attribute. They shouldn't be part of the instructions. I think the instructions part could be re-worded to be a bit clearer "Try it with this image:" to "Add an `img` element to your code and use the following source:".

CONTRIBUTORS:
If you'd like to help make these changes, please check out the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md), and ask any questions in the [Contributor's chat room](https://gitter.im/FreeCodeCamp/Contributors). The code for this challenge can be found [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/basic-html-and-html5.json#L563).

The two changes are:
1) move the line "Note that in most cases, `img` elements are self-closing." so it's before the paragraph "All `img` elements must have an `alt` attribute..."
2) change the line "Try it with this image:" to "Add an `img` element to your code and use the following source:" (make sure to put the word "img" inside `<code>` tags).

Thank you!!  🎉 💯

**Comment by Manish-Giri** [comment]
@HKuz I'd like to take this up.

**Comment by HKuz** [comment]
@Manish-Giri - all yours, thank you! You're a PR machine lately 🔥 🤖 👍

**Comment by Manish-Giri** [comment]
@HKuz Thank You ⚡️ 😛

**Comment by carlilejs** [comment]
@Manish-Giri I'd love to help with this! I've forked it at I'm looking at refactoring the... text.

I'm thinking:
1. As @HKuz mentioned, move the line "Note that in most cases, img elements are self-closing." so it's before the paragraph "All img elements must have an alt attribute..."
2. Change the moved text to:  "Note: In most cases, <code>img</code> elements are self-closing (they don't require a closing backslash)." to clarify the meaning.
3. Change "<strong>must</strong>" to "<span style=\"font-size: 1.2em\"><strong>must</strong></span> *Could also be 120% depending on the preferred method. This is just to strengthen the emphasis on must. It appeared rather weak to me.
4. Finally, I think the instruction at the end should read: "Create an image tag using this url:"

That's it! I'd love suggestions.

**Comment by carlilejs** [comment]
Actually, I think @HKuz had a better idea for the instructions at the end. I'd go with that edit:

"Add an <code>img</code> element to your code and use the following source:"
