### ISSUE TITLE
expressworks update

### ISSUE THREAD

**Issue by Mathieu-Roy** [FreeCodeCamp/FreeCodeCamp#1320]
The directives of challenge http://www.freecodecamp.com/challenges/waypoint-build-web-apps-with-express.js needs to be updated because the expressworks course has been updated. The "Complete 'Session and Cookie'" section has now became the sections "Param Pam Pam" and "What's in Query".

**Comment by benschenker** [comment]
Closed as stale, please reopen if this is still an issue for you
