### ISSUE TITLE
[beta][UX][Enhancement] Remove animation for tab refresh on Night Mode

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13203]
Having a flashing white page accompanied with the animation, whenever a tab is refreshed on Night Mode is contradictory.

This is Night Mode with animation:![screen shot 2017-02-06 at 7 21 40 pm](https://cloud.githubusercontent.com/assets/7606025/22676709/f01e0804-eca1-11e6-9f57-f1ee5049efcd.png)

**Comment by tommygebru** [comment]
Added tags [Enhancement][UX]

**Comment by Bouncey** [comment]
Closing as duplicate of #12560
