### ISSUE TITLE
[beta] Label text should be synonymous with date picker format

### ISSUE THREAD

**Issue by cdrainxv** [freeCodeCamp/freeCodeCamp#13207]
Challenge [add-an-accessible-date-picker](http://beta.freecodecamp.com/en/challenges/applied-accessibility/add-an-accessible-date-picker) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.

Just wondering if the example shown:
```html
<label for="input1">Enter a date (MM-DD-YYYY):</label>
<input type="date" id="input1" name="input1">
```
and the challenge code:
```html
<p>Tell us the best date for the competition</p>
<label for="pickdate">Preferred Date (MM-DD-YYYY):</label>
```
should be revised so that the format for the date picker (`YYYY-MM-DD`) is synonymous with the label texts (currently `MM-DD-YYYY`).

Suggested revisions: 
1. `Enter a date (MM-DD-YYYY):` to `Enter a date (YYYY-MM-DD):`
2. `Preferred Date (MM-DD-YYYY):` to `Preferred Date (YYYY-MM-DD):`

**Comment by HKuz** [comment]
@cdrainxv - thanks for the issue! Would you mind posting a screen shot of what you see when you use the date picker in the challenge? When I add the `<input>` field per the instructions, and run the code, this is what I see on the phone - it recognizes the MM-DD-YYYY format and allows me to edit it by typing/hitting tab, or clicking the calendar:

![screen shot 2017-02-08 at 8 55 04 pm](https://cloud.githubusercontent.com/assets/9591826/22766020/3989e346-ee41-11e6-87d7-408d7ae0fba5.png)



![screen shot 2017-02-08 at 8 55 23 pm](https://cloud.githubusercontent.com/assets/9591826/22766026/3edd7fb0-ee41-11e6-9369-7e485fe32e1d.png)


I'm using Chrome, but I wonder if browser settings have anything to do with displaying it differently (i.e., maybe I have US formats specified somewhere, which tend to use the MM-DD-YYYY style).

**Comment by cdrainxv** [comment]
@HKuz: Thanks for responding. I also was using chrome for testing this challenge. This was the date format for the input:

![screen shot 2017-02-08 at 21 35 28](https://cloud.githubusercontent.com/assets/18746599/22770008/12302298-ee4a-11e6-8a01-cdd008d45852.png)




I tested it using browser settings as well, but that doesn't appear to be the culprit in my case as I use US settings for the browser as well. It seems in my case the date formatting is based on the Language & Region section of my System Preferences. Notice the format is year-month-day:




![screen shot 2017-02-08 at 22 06 21](https://cloud.githubusercontent.com/assets/18746599/22770181/bc46da96-ee4b-11e6-8d15-7432fabd4fa7.png)




After I changed it to a region (like US) that formatted their dates month-day-year:  


![screen shot 2017-02-08 at 10 21 41 pm](https://cloud.githubusercontent.com/assets/18746599/22770352/0dc6f3a0-ee4d-11e6-953e-e3fe8c2cb451.png)


then the date picker format was formatted similar to the label text's:


![screen shot 2017-02-08 at 10 29 51 pm](https://cloud.githubusercontent.com/assets/18746599/22770536/74cf73dc-ee4e-11e6-8943-decaeb8a7a8f.png)

**Comment by HKuz** [comment]
@cdrainxv - great, thanks for looking into this more and figuring out the culprit! It sounds like the format will be different for any user depending on their system settings. I think we should remove the format reference (the "MM-DD-YYYY" part) in both the example and seed code to avoid confusion.

Contributors: check out the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) to get set up and feel free to ask any questions in the [Contributor's Chat Room](https://gitter.im/FreeCodeCamp/Contributors). The code for this challenge can be found [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/applied-accessibility.json#L611) - you're removing the " (MM-DD-YYYY)" text from the labels in both the example and the seed code. So the example `label` reads "Enter a date:", and the seed code `label` reads "Preferred Date:". Thank you! 🍰 👍

**Comment by teeleek** [comment]
Okay

Puttasak insee

เมื่อ 12 ก.พ. 2017 10:51 "Dylan" <notifications@github.com> เขียนว่า
