### ISSUE TITLE
[beta][curriculum] Remove excess paragraph (Note)

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13208]
Remove this paragraph, from the challenge Link to Internal Sections of a Page with Anchor Elements
http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/link-to-internal-sections-of-a-page-with-anchor-elements

> Note
Additional kitty ipsum text has been added to the paragraphs to better show the effect of clicking the internal anchor link to jump to the bottom of the page. Also, this change will only apply to this challenge. The next challenge goes back to showing your external link.

**Comment by erictleung** [comment]
I personally like the paragraph for clarity and enforces what the challenge is about, which is to show that the internal links are working to move you to different sections. Additionally, the HTML challenges are designed (IMO) to be incrementally built, where each subsequent challenge adds a little more to built the CatPhotoApp. So in this context, the extra paragraph makes sense.

I can see the argument for its removal, though. So I'm indifferent to removing it or not.

**Comment by tommygebru** [comment]
No worries @erictleung I am just running through the course and giving my 2-cents 💯 

I do notice though that the width of the instructions is nearly 20% of the page, i am on my laptop so i believe the media query has forced it at `min-width(1200px)`

The problem i am seeing though is readability, as instructions and new material to students, the instructions is very important and should make sense without over-explaining, especially because it is so narrow there involves a lot of scrolling.

Here is an issue with visual aide for the same problem #13209
