### ISSUE TITLE
[beta][UI][UX] Change the instructions panel width

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13209]
Changing the instructions panel width will improve readability, understanding of new concepts and overall challenge, it is currently much too narrow!

Currently Narrow:
![screen shot 2017-02-06 at 8 22 31 pm](https://cloud.githubusercontent.com/assets/7606025/22677987/b48870c2-ecab-11e6-9cda-2c38022e1d6d.png)
![screen shot 2017-02-06 at 8 22 36 pm](https://cloud.githubusercontent.com/assets/7606025/22677988/b48ad006-ecab-11e6-8de1-f6d59bad184f.png)

Change in width:
![screen shot 2017-02-06 at 8 22 03 pm](https://cloud.githubusercontent.com/assets/7606025/22678022/e623befc-ecab-11e6-9817-c0a16a6e8f48.png)
![screen shot 2017-02-06 at 8 22 07 pm](https://cloud.githubusercontent.com/assets/7606025/22678021/e62204b8-ecab-11e6-96b5-4f7929039b58.png)

**Comment by tommygebru** [comment]
Also I suggest that the scrollbar for the instructions panel is also hidden to help widen the instruction material.
This can be done with `::-webkit-scrollbar{display:none;}`
In its place we can provide a border for the parent div `border-right: solid 1 px aliceblue`

**Comment by SanjayPatel16** [comment]
Can i work on it?

**Comment by tommygebru** [comment]
you can try @SanjayPatel16

**Comment by Bouncey** [comment]
@tommygebru how would I scroll the instruction panel without the scroll bars?

**Comment by raisedadead** [comment]
@SanjayPatel16 Thanks for your interest. This issue is not yet confirmed to be needing a change.
I recommend you have a look at the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), and look for issues with help wanted tag to contribute.

**Comment by raisedadead** [comment]
@Bouncey I think what @tommygebru is trying to suggest is that we have a scroll only on on the main body, and rest all "could" be having separators.

I am not sure on that.

But, that said, the instruction panel is narrow, and we have a multi tab editor in plan. That might give us a better UX.

**Comment by tommygebru** [comment]
@Bouncey I dont mean to remove it, just replace 😉 

@raisedadead its nice to hear about a new layout in plan, I think a fairly simple layout can be having a collapsible instructions panel, and with that change have the ouptut + test case  section below the editor 🤔 

Also I did mention in this issue #13224 that there needs to be better sizing solutions, because if there are **4 scrollbars** to a challenge page that means there are 1 to many

**Comment by no-stack-dub-sack** [comment]
@raisedadead @Bouncey I think what he's saying with the scroll bar, is not to remove it, just to hide it so that you don't actually see it when you're scrolling. I actually think this part of it is a good suggestion, as it often gets in the way when scrolling through the narrow instructions pane

**Comment by tommygebru** [comment]
@no-stack-dub-sack do you have a sketch or mockup for the multi-tab UI, I think i understand what it is but I am not sure what the end result will be...
