### ISSUE TITLE
Padding definition

### ISSUE THREAD

**Issue by korkmaz** [freeCodeCamp/freeCodeCamp#13205]
Challenge [Adjusting the Padding of an Element](https://www.freecodecamp.com/challenges/adjusting-the-padding-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.injected-text%20%7B%0A%20%20%20%20margin-bottom%3A%20-25px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.box%20%7B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-color%3A%20black%3B%0A%20%20%20%20border-width%3A%205px%3B%0A%20%20%20%20text-align%3A%20center%3B%0A%20%20%7D%0A%0A%20%20.yellow-box%20%7B%0A%20%20%20%20background-color%3A%20yellow%3B%0A%20%20%20%20padding%3A%2010px%3B%0A%20%20%7D%0A%20%20%0A%20%20.red-box%20%7B%0A%20%20%20%20background-color%3A%20red%3B%0A%20%20%20%20padding%3A%2020px%3B%0A%20%20%7D%0A%0A%20%20.green-box%20%7B%0A%20%20%20%20background-color%3A%20green%3B%0A%20%20%20%20padding%3A%2020px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch5%20class%3D%22injected-text%22%3Emargin%3C%2Fh5%3E%0A%0A%3Cdiv%20class%3D%22box%20yellow-box%22%3E%0A%20%20%3Ch5%20class%3D%22box%20red-box%22%3Epadding%3C%2Fh5%3E%0A%20%20%3Ch5%20class%3D%22box%20green-box%22%3Epadding%3C%2Fh5%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Description of padding is a bit misleading, I think. It says `An element's padding controls the amount of space between the element and its border.` Should it have been something like `... space between the content of element and its border.`?

https://developer.mozilla.org/tr/docs/Web/CSS/padding
https://www.w3.org/TR/CSS2/box.html#box-dimensions

**Comment by HKuz** [comment]
Hi @korkmaz - thanks for raising this issue! I see what you're referencing on the production site, and agree your description is more clear. In good news, when I checked on the latest Beta site, it looks like that change was already incorporated! It currently reads: 

> An element's `padding` controls the amount of space between the element's content and its `border`.

I'm going to close this issue as resolved on `staging` (that's where we'd make the fix). Thanks and happy coding 👍

**Comment by giacecco** [comment]
@HKuz @korkmaz I believe the new text is better than the previous but still far from ideal. There are two issues in my opinion.

1. The definition "An element's padding controls the amount of space between the element and its border." sounds like a contradiction to me. The border defines the element, so there should be nothing between the border and the element. The padding must be something else! So I suggest changing to:

        An element's padding controls the amount of space between its contents (the "padding" word) and its border.

2. Depending on the user's visual perception, they may, for example, notice the *horizontal* padding more than the vertical padding, and say of the picture below "Gosh, the padding looks identical to me!". This is what happened to me the first time, and I know HTML already!

    ![screenshot from 2017-05-07 08-38-26](https://cloud.githubusercontent.com/assets/303693/25778801/a6ce2a58-3300-11e7-83c8-be1f92627ccc.png)

    So I suggest changing to:

        An element's padding controls the amount of space between its contents (the "padding" word) and its border, in all directions.

What do you reckon?
