### ISSUE TITLE
Closing tag

### ISSUE THREAD

**Issue by andrewwiley** [freeCodeCamp/freeCodeCamp#13201]
"Create a bootstrap headline"

I'm having trouble with what seems should be the easiest part: closing my h3 element.  </h3> seems like it should work but alas, it isn't.  What am I missing here?  Thanks!

**Comment by fonsecapontes** [comment]
@andrewwiley post your code for us to analyze.

**Comment by andrewwiley** [comment]
@fonsecapontes <h3> jQuery Playground
  <h3 class="text-primary text-center">
    
  </h3>

**Comment by andrewwiley** [comment]
![screenshot 2017-02-06 19 30 09](https://cloud.githubusercontent.com/assets/25592634/22672597/f7b302f8-eca2-11e6-9f32-a8036d6886c1.png)

@fonsecapontes

**Comment by Manish-Giri** [comment]
@andrewwiley Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) for help with issues on these challenges. Happy Coding!

**Comment by andrewwiley** [comment]
@Manish-Giri i posted the issue multiple times in there and haven't received any assistance.

**Comment by andrewwiley** [comment]
@Manish-Giri i figured it out.  Only took an hour for the simplest thing ever.

**Comment by erictleung** [comment]
Closing as resolved. Happy coding!
