### ISSUE TITLE
Inconsistent Tests for Bonfire: Exact Change

### ISSUE THREAD

**Issue by hell316** [FreeCodeCamp/FreeCodeCamp#1321]
The "Exact Change" bonfire uses different numbers of decimals in various tests. Below is an example where QUARTER has both 1 and 2 decimals but in different tests:

    assert.deepEqual(drawer(19.50, 20.00, [['PENNY', 1.01], ['NICKEL', 2.05], ['DIME', 3.10], ['QUARTER', 4.25], ['ONE', 90.00], ['FIVE', 55.00], ['TEN', 20.00], ['TWENTY', 60.00], ['ONE HUNDRED', 100.00]]), [['QUARTER', 0.50]], 'return correct change');

versus:

    assert.deepEqual(drawer(3.26, 100.00, [['PENNY', 1.01], ['NICKEL', 2.05], ['DIME', 3.10], ['QUARTER', 4.25], ['ONE', 90.00], ['FIVE', 55.00], ['TEN', 20.00], ['TWENTY', 60.00], ['ONE HUNDRED', 100.00]]), [['TWENTY', 60.00], ['TEN', 20.00], ['FIVE', 15], ['ONE', 1], ['QUARTER', 0.50], ['DIME', 0.20], ['PENNY', 0.04] ], 'return correct change with multiple coins and bills');

This makes correct code fail, simply because the number of decimals does not match. As you can see from the last assertion, large denominations have two decimals (e.g. TWENTY) but FIVE and ONE have none, irrespective of the number of decimals provided in the function arguments. 

I suggest all values be with two decimals as is common for currencies.

**Comment by benschenker** [comment]
Thanks @hell316,

I'm having trouble understanding exactly what the issue is, can you try to explain this again?

**Comment by hell316** [comment]
The number of decimals for the *same* denominations are not the same across tests. Since my code returns the same number of decimals (2 as per usual) my code fails the tests.

**Comment by benschenker** [comment]
Thanks for the clarification, can you post your code so I can try to replicate this?

**Comment by hell316** [comment]
// Taken from http://jhusain.github.io/learnrx/
Array.zip = function(left, right, combinerFunction) {
            var counter,
                        results = [];

            for(counter = 0; counter < Math.min(left.length, right.length);
counter++) {

results.push(combinerFunction(left[counter],right[counter]));
            }

            return results;
};

// Return an array of change, assuming there is enough in the drawer
// It returns the amount for each non-zero denomination even though
// how many of each would need to be returned seems more useful.
function returnChange(change, cid) {
  // Available denominations from low to high
  var denom = [0.01, 0.05, 0.10, 0.25, 1, 5, 10, 20, 100];
  var numNotesAvailable = Array.zip(denom, cid, function(d, c) { return
parseInt(c[1]/d); });

  // Loop backwards in accordance with spec
  var i = cid.length - 1;
  var numNotesRequired; // number of notes/coins of a certain denomination
  var denomReturned;
  var money = [];
  while (change.toFixed(2) > 0) {
    if(change >= denom[i]) {
      numNotesRequired = Math.floor(change.toFixed(2)/denom[i]);
      numNotesReturned = Math.min(numNotesRequired, numNotesAvailable[i]);
      denomReturned = (numNotesReturned * denom[i]).toFixed(2);
      change -= denomReturned;
      console.log(denomReturned);
      money.push( [ cid[i][0], denomReturned ]);
    }
    i--;
  }
  return money;
}

function drawer(price, cash, cid) {
  var change = cash - price;

  var total = 0;
  for (var i in cid) {
    total += cid[i][1];
  }

  if (change > total) {
    return 'Insufficient Funds';
  }
  else if (change === total) {
    return 'Closed';
  }
  else {
    var money = returnChange(change, cid);
    return money;
  }
}


drawer(3.26, 100.00, [['PENNY', 1.01], ['NICKEL', 2.05], ['DIME', 3.10],
['QUARTER', 4.25], ['ONE', 90.00], ['FIVE', 55.00], ['TEN', 20.00],
['TWENTY', 60.00], ['ONE HUNDRED', 100.00]]);

**Comment by benschenker** [comment]
I finally see what you mean but it should not make a difference in the challenge.

`15===15.00` is `true` in javascript

My guess is that code is flawed somehow, I was able to make mine work.  We can try to help you figure out why your solution isn't working...

**Comment by BerkeleyTrue** [comment]
@benschenker  is correct.

Please see: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-help-when-you-get-stuck

Happy Coding!
