### ISSUE TITLE
[beta] Rewrite instructions for challenge: Nest an Anchor Element within a Paragraph

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13211]
Nest an Anchor Element within a Paragraph
http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph
current:
>Now nest your existing a element within a new p element (just after the existing main element) so that the surrounding paragraph says "View more cat photos", but where only "cat photos" is a link, and the rest of the text is plain text.

rewritten:
>Create a new ` p ` element after the ` main ` element, with the text "View more". Nest the existing anchor element inside the paragraph so that it reads "View more cat photos".

**Comment by tommygebru** [comment]
**ACTUALLY JUST CHANGE THE ENTIRE THING**

Current:
Basic HTML and HTML5: Nest an Anchor Element within a Paragraph
`<hr>`
Again, here's a diagram of an a element for your reference:
`<img>`
a diagram of how anchor tags are composed with the same text as on the following line

Here's an example:

<p>Here's a <a href="https://freeCodeCamp.com"> link to freeCodeCamp</a> for you to follow.</p>

Nesting just means putting one element inside of another element.
`<hr>`
Now nest your existing a element within a new p element (just after the existing main element) so that the surrounding paragraph says "View more cat photos", but where only "cat photos" is a link, and the rest of the text is plain text.


Rewritten:
Basic HTML and HTML5: Nest an Anchor Element within a Paragraph
`<hr>`
Again, here's a diagram of an a element for your reference:

a diagram of how anchor tags are composed with the same text as on the following line

Here's an example:

<p>Here's a <a href="https://freeCodeCamp.com"> link to freeCodeCamp</a> for you to follow.</p>

Nesting just means putting one element inside of another element.
`<hr>`
Create a new p element after the main element, with the text "View more". Nest the existing anchor element inside the paragraph so that it reads "View more cat photos".
`<hr>`

**Comment by raisedadead** [comment]
I find the rewritten text to be bit confusing, because it assumes, that the camper will keep the plain text and link text separate as expected by the challenge.

Do you have any suggestion, that clearly states the expectation of this challenge?

**Comment by tommygebru** [comment]
@raisedadead umm.. its possible that the new language can be confusing but maybe if we have more volunteers/contributors we can assume if it is understandable.

Here is a link to the challenge: https://beta.freecodecamp.com/en/challenges/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph

Just to be clear the changes in the  Rewrite include 
- removing the image
-adding an hr tag
-and changing the details of the instructions (not the introduction)

Thanks for sharing 👍
