### ISSUE TITLE
Site Freezes 

### ISSUE THREAD

**Issue by tjsiledar** [freeCodeCamp/freeCodeCamp#13214]
#### Challenge Name

https://www.freecodecamp.com/challenges/steamroller

#### Issue Description

The problem is I accidentally wrote a never ending recursion to the above mentioned challenge. Now I cant even reset my code because every time I open the site it just freezes. I tried disabling javascript from my browser to reset the code but its not working. Please help!

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by tjsiledar** [comment]
Here is the screenshot of the code

![screenshot 17](https://cloud.githubusercontent.com/assets/25153728/22691590/2d30a8ea-ed61-11e6-840b-848d577a88ed.png)

**Comment by cdrainxv** [comment]
@tjsiledar: Refer to this: https://forum.freecodecamp.com/t/free-code-camp-infinite-loop-protection/19550

**Comment by tjsiledar** [comment]
@cdrainxv Thanks man that worked!!
