### ISSUE TITLE
[beta][UX] Change the image to open in new tab

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13210]
Nest an Anchor Element within a Paragraph
http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph

The image in the instruction panel opens on the same tab.
To change the destination of the link add `target="_blank"` to the anchor tag.

![screen shot 2017-02-06 at 8 46 18 pm](https://cloud.githubusercontent.com/assets/7606025/22678224/57bd6530-ecad-11e6-9128-98da11df0d2e.png)

**Comment by rarmatei** [comment]
Mind if I pick this up?
