### ISSUE TITLE
[beta][UI][UX] Should we remove the modal altogether?

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13222]
A recurring issue is the results of a challenge after a running the "run tests" button, actually makes the results inaccessible... the modal window pops up, obscures the view of the page, and even darkens the html page so that it becomes ignored....

The results of a challenge do appear but are never truly experimented with or fully understood because of the omnipresent modal...

I think that the solution may come from the smaller tooltip which usually appears on the bottom right screen with the following messages
"Found some old work"
or
"Your next challenge has arrived"
![screen shot 2017-02-07 at 9 35 11 am](https://cloud.githubusercontent.com/assets/7606025/22703385/d76fad90-ed18-11e6-9b6f-af531b035ce1.png)

The new message should be "proceed to next challenge" and it should be a vibrant color and remain in its position until clicked.
After playing with the editor and output, after students feel confident they should move on to the next challenge at their own pace.

**Comment by tommygebru** [comment]
**EDIT:**
I have found that the tooltips can pile up and reach 3 maybe even 4 messages?

There should really be only 2 messages on the tooltip that appears

1) Keep Trying - a message of positivity reinforcement to remain in a state of "flow"
2) Proceed to next challenge -  continue a streak of productivity also encourages "flow"

**Comment by Bouncey** [comment]
@tommygebru we had a challenge completed toast in the early stages of beta, I myself experimented with different solutions, but we settled on the modal. The discussion is [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/10628)

**Comment by Bouncey** [comment]
One issue I can see is that the toast it lost in night mode due to the low contrast with the background

**Comment by tommygebru** [comment]
@Bouncey Many thanks! 💯 

You are definitely on the right path with the notification.

I think the best solution would be something like this

http://s.codepen.io/gebrutommy/debug/KaxVvE/RBMOJyKxLJEk

**Comment by Bouncey** [comment]
@tommygebru as per the issue I referenced earlier, we had a toast for challenge completion, we decided to remove it and keep the modal instead.

**Comment by tommygebru** [comment]
I was attempting to address the corner case that Quincy shared on that issue. I agree with him and I dont see the benefit of having both a modal system in place as well as a notification system.

**Comment by dhcodes** [comment]
Closing as resolved per Bouncey's comments?
