### ISSUE TITLE
problem in submetting the result

### ISSUE THREAD

**Issue by Dadirabah** [freeCodeCamp/freeCodeCamp#13223]
Challenge [change-the-color-of-text](http://beta.freecodecamp.com/en/challenges/basic-css/change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
i have added the style and changed the color to red however when submitted is steel prompting a wrong answer. Please check this issue. thanks and best regards
![screenshot from 2017-02-07 19-05-52](https://cloud.githubusercontent.com/assets/24811021/22704597/8894cad4-ed68-11e6-89e4-d81865f59f8c.png)

```html


<h2 **style="color: red"**>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

**Comment by atjonathan** [comment]
Cannot reproduce. Can you @raisedadead ?

**Comment by raisedadead** [comment]
@Dadirabah 

> `<h2 **style="color: red"**>CatPhotoApp</h2>`

This is incorrect code. Your screenshot is different than your code above. 
Please retry.

**Comment by Dadirabah** [comment]
Dear thanks
I have switched to chrome and its working fine no problem
Thanks
