### ISSUE TITLE
[beta][UI][UX] Rewrite introduction to CSS

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13226]
http://beta.freecodecamp.com/en/challenges/basic-css/introduction-to-basic-css

This can be written or provided visual aid with images

also apply same height/width to each of the four pages in the introduction

**Comment by HKuz** [comment]
Hi @tommygebru - these introduction pages are placeholder 'works in progress'. There's currently a call to help to the community to re-design them in issue #11060. I'm going to close this issue, and ask that you give visual aid / image examples and any other suggestions for the re-design over there 😄. That way we can keep track of everything in one place 👍
