### ISSUE TITLE
Box highlighted without a Tick mark.

### ISSUE THREAD

**Issue by kshitij10496** [FreeCodeCamp/FreeCodeCamp#1322]
![freecodecamp](https://cloud.githubusercontent.com/assets/12427142/8745064/a65e7ec0-2c99-11e5-9515-dc5e850d1d89.JPG)

I checked the first box and then clicked on "Guide" tab.
After going through the Guide, I pressed Back arrow and got this screen.

**Comment by benschenker** [comment]
Closing as stale
