### ISSUE TITLE
Video playback not working

### ISSUE THREAD

**Issue by manwithgills** [freeCodeCamp/freeCodeCamp#13239]
Challenge [build-a-tribute-page](http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

When you click on the video it shows an error:
![image](https://cloud.githubusercontent.com/assets/13177446/22738881/4fa5e25c-edd7-11e6-96eb-44cb25dd208d.png)

**Comment by raisedadead** [comment]
We are replacing videos with static images, refer: #12753
Closing as these would be removed per the other thread.
