### ISSUE TITLE
Challenge successful but button not responding when I hover over it.

### ISSUE THREAD

**Issue by CharlesHOV** [freeCodeCamp/freeCodeCamp#13236]
Challenge [use-css-animation-to-change-the-hover-state-of-a-button](http://beta.freecodecamp.com/en/challenges/applied-visual-design/use-css-animation-to-change-the-hover-state-of-a-button) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  button {
    border-radius: 5px;
    color: white;
    background-color: #0F5897;
    padding: 5px 10px 8px 10px;
  }
  button:hover {
    animation-name: background-color;
    animation-duration: 4s;
  }
  @keyframes background-color {
    100% {
      background-color: #4791d0;
    }
  }
</style>
<button>Register</button>

```

I like to test what I do on the sample phone to the right. When I submitted this challenge with the above code, I was told I did it correctly and could move on, yet when I hovered over the button to see the color change nothing happened. I am assuming I did the code correctly since I can move on, so I'm not sure if this is a bug with the simulator.

**Comment by HKuz** [comment]
@CharlesHOV - I get it to work on Chrome. The animation is set to 4 seconds (which seems kinda long for a hover), and the blue it changes to is not very different than the button's start color. When you run your code successfully and exit out of the 'congrats' modal, can you try and hold your cursor over it for the full 4s? 

I tried to catch the color change in a couple screen shots:

Start:

![screen shot 2017-02-08 at 9 07 53 pm](https://cloud.githubusercontent.com/assets/9591826/22766367/18825fd2-ee43-11e6-9e1e-22c1273804bb.png)


Hover:
![screen shot 2017-02-08 at 9 08 58 pm](https://cloud.githubusercontent.com/assets/9591826/22766366/1881417e-ee43-11e6-848c-4faec1667dee.png)

Let me know if it was the duration/color change - or if you still don't see a difference. In any event, we should probably shorten the duration, and make the color change more obvious 👍

**Comment by Bouncey** [comment]
:+1: for reducing the animation duration. `500ms` would be better

**Comment by HKuz** [comment]
Good call @Bouncey - I'm opening this up as help wanted to get that change in 👍 

Contributors: see the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) to get set up, and feel free to ask any questions in the [Contributor's chat room](https://gitter.im/FreeCodeCamp/Contributors). The code for this challenge can be found [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/applied-visual-design.json#L2173). Thank you! 💯 🌮 🎉

**Comment by jamos-tay** [comment]
Hi, could I work on this?
