### ISSUE TITLE
Waypoint 36: Need stricter check for name field inside inputs

### ISSUE THREAD

**Issue by junhaoyap** [FreeCodeCamp/FreeCodeCamp#1323]
![screen shot 2015-07-17 at 6 22 10 pm](https://cloud.githubusercontent.com/assets/6291947/8745277/c808b132-2cb0-11e5-8d72-83ff06503bcd.png)

As per above screenshot, it declares that I'm all ready to go to the next waypoint despite having had only one of the input field's "name" attribute set to "personality.

However, I believe this is a low priority issue, perhaps I can look into it some other time.

**Comment by benschenker** [comment]
Thanks @junhaoyap this seems to still be an issue
