### ISSUE TITLE
Not Found does not return

### ISSUE THREAD

**Issue by Znallman** [freeCodeCamp/freeCodeCamp#13233]
Challenge [Testing Objects for Properties](https://www.freecodecamp.com/challenges/testing-objects-for-properties#?solution=%0A%2F%2F%20Setup%0Avar%20myObj%20%3D%20%7B%0A%20%20gift%3A%20%22pony%22%2C%0A%20%20pet%3A%20%22kitten%22%2C%0A%20%20bed%3A%20%22sleigh%22%0A%7D%3B%0A%0Afunction%20checkObj(checkProp)%20%7B%0A%20if%20(myObj.hasOwnProperty(%22gift%22))%0A%20%7Breturn%20myObj%5BcheckProp%5D%3B%0A%20%7Delse%7B%0A%20%20%20return%20%22Not%20Found%22%3B%7D%0A%7D%0A%0A%0A%2F%2F%20Test%20your%20code%20by%20modifying%20these%20values%0AcheckObj(%22gift%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
I have been trying this for an hour and Not Found will not return is this a problem with my code or a bug?

My code:
```javascript

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
 if (myObj.hasOwnProperty("gift"))
 {return myObj[checkProp];
 }else{
   return "Not Found";}
}


// Test your code by modifying these values
checkObj("gift");

```

**Comment by Znallman** [comment]
Never mind i found the problem

**Comment by erictleung** [comment]
Closing as resolved. Happy coding!
