### ISSUE TITLE
It says that I haven't changed the text size, but I have definitely changed the text size

### ISSUE THREAD

**Issue by Russellmania91** [freeCodeCamp/freeCodeCamp#13238]
I have checked to make sure my browser is at 100 percent zoom and it is.  Text is also at 100 percent.  My code appears to be working fine, I can change the text to anything I want, but no matter what I do, it says that the font is not at 16px.

Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7Bcolor%3Ared%3Bfont-size%3A%2016px%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {color:red; font-size: 16px;}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by JosephLivengood** [comment]
Its look like the challenge is asking you to create a _new_ style entry for _p_ elements and not add to the existing class red-text: _"create an entry for p elements and set the font-size to 16 pixels (16px)."_

```
p {
  font-size: 16px;
}
```

**Comment by Russellmania91** [comment]
Oh I see, that fixed it. Thank you for your help!
