### ISSUE TITLE
Waypoint: Manage Source Code with Git

### ISSUE THREAD

**Issue by saadanerdetbare** [FreeCodeCamp/FreeCodeCamp#1324]
I would like to suggest this tutorial to the waypoint manage sourcecode with  Git
http://rypress.com/tutorials/git/index in addition to the existing one or maybe to replace it
After doing the steps here i suddenly realised what all the fuss was about :)

**Comment by ltegman** [comment]
This doesn't seem to be getting any traction. Closing as stale.
