### ISSUE TITLE
Basic JavaScript Arrays topic order

### ISSUE THREAD

**Issue by Drallas** [freeCodeCamp/freeCodeCamp#13248]
## Basic JavaScript Arrays topic order

This is a minor issue, but it can confuse people like me. 

Starting [at](https://www.freecodecamp.com/challenges/manipulate-arrays-with-push) 

**Current order is**

- Manipulate Arrays With push()
- Manipulate Arrays With pop()
- Manipulate Arrays With shift()
- _Manipulate Arrays With unshift()_

**Order should be**

- Manipulate Arrays With push()
- _Manipulate Arrays With unshift()_
- Manipulate Arrays With pop()
- Manipulate Arrays With shift()

Why because 

- unshift() works like Push() but at the front of an Array, it's a pair that logically belongs together. 
- shift() works like pop() but at the front af an Array, same reason.

**Comment by atjonathan** [comment]
I guess this makes more sense.
cc / @freeCodeCamp/moderators

**Comment by cdrainxv** [comment]
The current order makes just as much sense for the reason you stated above - logic. I would believe most people would also tend to think along the lines of, "Oh, I can now add/remove an element to/from the front/back of an array.", followed almost immediately with "What about if I want to do the equivalent opposite of the operation I just performed?". This is a gross generalization, but I would like to think that people would retain these array methods better if a method was introduced and then followed up by its immediate opposite, i.e push() then pop(), and unshift() then shift(), acting on the same end of the array as the previously learned method. 

Even as I say this, the current challenge order could be also revised so it is logical in that you add an element, remove an element, add an element, remove an element, or vise-versa:

- Manipulate Arrays With push()
- Manipulate Arrays With pop()
- Manipulate Arrays With unshift()
- Manipulate Arrays With shift()


Just my two cents. Thanks!

**Comment by billy-reilly** [comment]
@raisedadead I'm up for submitting a pull request for this change if it is confirmed?

Is there any documentation on how the ID strings are generated for each challenge? (I'm guessing they need to stay in the same order whilst the other properties of each challenge object are swapped around?)

**Comment by QuincyLarson** [comment]
@Drallas I see what you're saying, but I think the current order is fine and how these are usually introduced. Push and Pop are seen as reciprocal actions - same with shift/unshift. Thanks for looking out for the details, though. If you spot any others you think are counter-intuitive, please let us know.

**Comment by Drallas** [comment]
@QuincyLarson i understand, if it's usually introduced as is done on FCC perhaps this only would add to the confusion. :)
