### ISSUE TITLE
Array.prototype.includes() not supported by IE

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#13241]
When visiting beta through IE, the site is unusable. There are two instances of `includes` in the code base outside of the gulp file, and two solutions for fixing this.

1. Add a polyfill for `Array.prototype.includes()`
or
2. Refactor to remove `Array.prototype.includes()`

**Comment by carlilejs** [comment]
@Bouncey I'm not finding any instances of .includes() in the code. Sorry if I'm missing something, but could you give me a bit more information? Are you on a branch other than staging?

**Comment by Bouncey** [comment]
[A search for includes](https://github.com/freeCodeCamp/freeCodeCamp/search?l=JavaScript&q=includes&utf8=✓)

If you can follow the contributing guidelines, that would be great!

The gulp file doesn't need refactoring.

**Comment by carlilejs** [comment]
Not sure how I missed that! Thank you. I've been researching this and I'll see what I can do tonight or tomorrow.

**Comment by no-stack-dub-sack** [comment]
@Bouncey This may be thinking a bit too far down the line, but I've been aware of this for some time since @bonham000 and I ran into this issue when we were developing the React curriculum. Several of those challenges err... include `includes()` 😄 

So I guess my point is, maybe a polyfill is the best solution?

**Comment by carlilejs** [comment]
@no-stack-dub-stack Thanks for the tip! Do you have any resources off the top of your head for writing polyfills? In the meantime, I'm reading as much as I can on them

**Comment by Bouncey** [comment]
@carlilejs there is a polyfill available on MDN [here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

**Comment by teeleek** [comment]
Okay

Puttasak insee

**Comment by teeleek** [comment]
Okay

Puttasak insee

เมื่อ 11 ก.พ. 2017 14:39 "Stuart Taylor" <notifications@github.com> เขียนว่า

**Comment by carlilejs** [comment]
Hey everyone, I just don't know enough about the freeCodeCamp app yet to put this in. If someone wants to take this that'd be great. Sorry, but I'm still very new to freeCodeCamp contributing.

**Comment by boyinstruggle** [comment]
Hi all, first timer here. I will take a look at the code to see if i can do anything to help.

**Comment by rghossi** [comment]
Is it a good solution to refactor `includes(x)` to `indexOf(x) > -1`? I could make a PR for that...

**Comment by Bouncey** [comment]
@rghossi with regards to @no-stack-dub-stack and the issue with some ES6 challenges that `babel-polyfill` would be bettter.

**Comment by Bouncey** [comment]
Just as a note of interest, `.some()` is a better replacement for `.includes()`

**Comment by manur1984** [comment]
Hi guys, can anyone tell me how to stop getting messages on email from this chat and else on here, it's really getting annoying!

**Comment by texas2010** [comment]
@manur1984 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!

**Comment by fortMaximus** [comment]
I would like to contribute.

**Comment by BerkeleyTrue** [comment]
It looks like there are only a few instances of 'includes'. Replacing these with  indexOf  would be a better option instead of adding a large pollyfill for a small convenience.

**Comment by carlilejs** [comment]
@BerkeleyTrue No-stack-dub-sack mentioned that the React curriculum uses .includes, and thus a polyfill is better since the app needs to be supported on every browser.

**Comment by BerkeleyTrue** [comment]
@carlilejs Understood, but those can also be refactored. I don't see the need add babel-polyfil to fix a minor issue.

**Comment by QuentinGibson** [comment]
@BerkeleyTrue I can work on refactoring this.
