### ISSUE TITLE
Using Objects for Lookups - Need to Modify Code Setup

### ISSUE THREAD

**Issue by jjprevite** [freeCodeCamp/freeCodeCamp#13252]
I noticed a [similar issue](https://goo.gl/E2BFFG) was opened on Feb. 1st, 2016 but has been closed. The problem is that a line of code that needs to be modified by the user in order is **above** the line that says _"Only change code below this line"_

SPOILER ALERT!! Solution below. 

#### Challenge Name- Using Objects for Lookups

[](https://goo.gl/uF0HQf)

#### Issue Description

The directions within the text editor are misleading because it says to only modify code in between the two comments ("Only change code above/below this line").

#### Screenshot

Problem: line of code needs to be moved down below the comment that says "Only change code below this line"
![code_problem](https://cloud.githubusercontent.com/assets/3806031/22758529/ec34f078-ee03-11e6-8c34-bfd41f04f7cb.png)

As you see in the screenshot below, I had to move and modify that line `var result=''` 
![code_with_solution](https://cloud.githubusercontent.com/assets/3806031/22758534/ee9225a2-ee03-11e6-872b-b47aad01fa0a.png)

**Comment by raisedadead** [comment]
Thanks  for your report, but :

```
var result = "";
...
...
...
...
result = lookup[val];
```

Something like above should work, don't you think?
Please confirm your issues in the help chat room before reporting.
