### ISSUE TITLE
Obvious answer not passing final test

### ISSUE THREAD

**Issue by EdwardHeath** [freeCodeCamp/freeCodeCamp#13253]
Challenge [divide-one-decimal-by-another-with-javascript](http://beta.freecodecamp.com/en/challenges/basic-javascript/divide-one-decimal-by-another-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js

var quotient = 4.4 / 2.0;
```
This solution does not pass the last test: The quotient variable should only be assigned once

**Comment by erictleung** [comment]
@EdwardHeath this passes for me on beta. 

![image](https://cloud.githubusercontent.com/assets/2754821/22764483/d5bfe7fa-ee1f-11e6-9519-54dc8f36e211.png)

Maybe reset your code and try again? I'm also using Chrome, so that might also be a difference if you're using Firefox.

**Comment by EdwardHeath** [comment]
I reset my code multiple times. Refreshing the page finally fixed it. Still a weird bug.
