### ISSUE TITLE
I think the result is good, but not passed.

### ISSUE THREAD

**Issue by AndreiLuca99** [freeCodeCamp/freeCodeCamp#13257]
Challenge [Missing letters](https://www.freecodecamp.com/challenges/missing-letters) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function fearNotLetter(str) {
  return str;
}

fearNotLetter("abce");

```

**Comment by cdrainxv** [comment]
@AndreiLuca99: The alphabet goes a, b, c, ___d___, e. In your current code, the missing letter would be `"d"` (which is what should be returned), but your return statement is returning str, which is `"abce"`.

Please seek challenge related guidance/help in the [Help JavaSript](https://gitter.im/FreeCodeCamp/HelpJavaScript) room. Thanks!

**Comment by raisedadead** [comment]
Hi @AndreiLuca99 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
