### ISSUE TITLE
Change the Font Size of an Element issue

### ISSUE THREAD

**Issue by Lkhdkn** [freeCodeCamp/freeCodeCamp#13251]
Change the Font Size of an Element issue

Can't pass this challenge. Set zoom to 100% but still not working.
![snikt](https://cloud.githubusercontent.com/assets/25251015/22758630/2f0a667c-ee58-11e6-8ca0-557170d35565.jpg)

* Browser Name, Version: Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet:  desktop

Here's my code.

<style>
  .red-text {
    color: red; 
  }
  p { 
    font size: 16px;
  }
  </style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by chhotu3** [comment]
thank you....
