### ISSUE TITLE
Use RGB to Mix Colors

### ISSUE THREAD

**Issue by 0-0-Zero** [freeCodeCamp/freeCodeCamp#13250]
Challenge [Use RGB to Mix Colors](https://www.freecodecamp.com/challenges/use-rgb-to-mix-colors#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20rgb(255%2C0%2C0)%3B%0A%20%20%7D%0A%20%20.orchid-text%20%7B%0A%20%20%20%20color%3A%20rgb(218%2C112%2C214)%3B%0A%20%20%7D%0A%20%20.sienna-text%20%7B%0A%20%20%20%20color%3A%20rgb(160%2C82%2C45)%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20rgb(0%2C0%2C225)%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22orchid-text%22%3EI%20am%20orchid!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22sienna-text%22%3EI%20am%20sienna!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22blue-text%22%3EI%20am%20blue!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

It says that i don't have the blue-text class set to blue/rgb(0,0,225) or that i don't use rgb to make it blue.

When i use: .blue-text{ background-color: blue;}   ,,, It will say i did change it to blue but that i didnt use rgb.

I did this just to make sure i was getting the right blue from the rgb value.

My code:
```html

<style>
  .red-text {
    color: rgb(255,0,0);
  }
  .orchid-text {
    color: rgb(218,112,214);
  }
  .sienna-text {
    color: rgb(160,82,45);
  }
  .blue-text {
    color: rgb(0,0,225);
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>

```

**Comment by 0-0-Zero** [comment]
![rgb_issue](https://cloud.githubusercontent.com/assets/25592658/22757236/0feba2dc-ee18-11e6-8b36-da7ff0ffde58.png)

**Comment by raisedadead** [comment]
Double check the RGB code you are adding for blue, its not correct.

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!

**Comment by 0-0-Zero** [comment]
i used the code they gave me

**Comment by raisedadead** [comment]
> i used the code they gave me

Apologies, I am not clear, do you mean you used the code from some one else?

**Comment by raisedadead** [comment]
Please follow the challenge instructions, there is a table which lists the color and the RBG code you need to use.

**Comment by 0-0-Zero** [comment]
No, the code from freecodecamp, I did follow instructions. i used the
table, that is what i am referrign to. You can see all that in the
screenshot i sent.

**Comment by 0-0-Zero** [comment]
Hey I'm sorry, i kept reading that second 5 as a 2. I'm so sorry about
that, thanks for the help though.
