### ISSUE TITLE
Add Borders Around your Elements

### ISSUE THREAD

**Issue by peteredw** [FreeCodeCamp/freecodecamp#1325]
I am having trouble with the code being accepted, I have tried for 2 hours trying to figure this out, and have tried a google search all to no avail.

There is no link to request help.

<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .smaller-image {
    width: 100px;
  }
    .thick-green-border {
 width: 100px;    
 border-color: green;
 border-width: 10px;
 border-style: solid;
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<img class='smaller-image' src='https://bit.ly/fcc-kittens'/>

<p class='red-text'>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class='red-text'>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by moguzman** [comment]
Hi, if the code you posted is giving you trouble,it seems that it's due to a missing curly bracket to close the element: 
.thick-green-border{}

**Comment by peteredw** [comment]
I tried that and it still is not working thanks for the feed back.
