### ISSUE TITLE
[beta] Array Destructuring has bad tests

### ISSUE THREAD

**Issue by reddock** [freeCodeCamp/freeCodeCamp#13268]
Challenge [array-destructuring](http://beta.freecodecamp.com/en/challenges/es6/array-destructuring) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This test just passed if you run it without touching anything. 

Also there is a typo "Destruring"

```js


let a = 8, b = 6;
/* Alter code below this line */
a = b;
b = a;
/* Alter code above this line */
console.log(a); // should be 6
console.log(b); // should be 8

```

**Comment by erictleung** [comment]
@reddock thanks for the issue. Yes, the challenge isn't "working" because currently, the tests are just comments, so anything will pass the tests. This challenge also needs some formatting work.

**Comment by Manish-Giri** [comment]
@erictleung I think I could do this...aside from the tests, what challenge formatting are you looking for? Perhaps a `<blockquote>` to contain the code example?
```
const [a, b] = [1, 2, 3, 4, 5, 7];

console.log(a, b); // 1, 2
```

**Comment by erictleung** [comment]
@Manish-Giri yes, `<blockquote>` tags would be great for those two lines. There shouldn't be an extra line break between the two lines of code. It should look like

```js
const [a, b] = [1, 2, 3, 4, 5, 7];
console.log(a, b); // 1, 2
```

**Comment by carlilejs** [comment]
Hmm, if anyone with more experience with Regular Expressions wants to tackle the tests, please let me know. I'd love to work with them on refactoring

**Comment by Manish-Giri** [comment]
@carlilejs If you're looking to contribute, please look for open "Help Wanted" issues, where no one is currently working on them. This might be a good start - https://github.com/freeCodeCamp/freeCodeCamp/issues/13241

**Comment by carlilejs** [comment]
@Manish-Giri Alright, cool. Sorry if I stepped on your toes. I'm just getting used to how contributing works.

**Comment by Manish-Giri** [comment]
@carlilejs You're fine! Good luck 🎉 

Feel free to ask questions [here](https://gitter.im/FreeCodeCamp/Contributors) if you have any, while working on issues.
