### ISSUE TITLE
Waypoint - Manage Packages with NPM - Step 10, npm publish breaks 'how-to-npm verify' command

### ISSUE THREAD

**Issue by ggc100** [FreeCodeCamp/FreeCodeCamp#1326]
Challenge http://www.freecodecamp.com/challenges/waypoint-manage-packages-with-npm has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

For step 10 in the how-to-npm adventure, after entering the command 'npm publish' I get the following error 
![error1](https://cloud.githubusercontent.com/assets/12610148/8749156/941de3f6-2c97-11e5-902b-5c4db9b953cd.JPG)

Then when I try to 'how-to-npm verify', it neither passes or fails but produces the following output:
![error2](https://cloud.githubusercontent.com/assets/12610148/8749181/c441dcf4-2c97-11e5-9193-2ecf5707de5f.JPG)

I then try to skip that step via 'how-to-npm verify skip' command, and the same error occurs. 'how-to-npm' still works fine, but issuing the verify command has broken something.

Can't continue on with the tutorial with it being in this state.

**Comment by saadanerdetbare** [comment]
I get the exact samme error. It is possible to continue issueing the 'how-to-npm' command again and skipping the parts about publishing but it is not possible to finish the tutorial

**Comment by SaintPeter** [comment]
I am having exactly the same problem.  It's not possible to continue.

**Comment by benschenker** [comment]
Is this still an issue?

**Comment by BerkeleyTrue** [comment]
This issue should be filed here: https://github.com/npm/how-to-npm

Happy Coding!

**Comment by supasheva** [comment]
Yes is still an issue

**Comment by zakrr** [comment]
Same issue

**Comment by nachiketnaik89** [comment]
same issue.

**Comment by mNov** [comment]
i'm getting the same problem too.

**Comment by BerkeleyTrue** [comment]
This conversion should be moved to https://github.com/npm/how-to-npm/issues/46
