### ISSUE TITLE
Add Images to your Website - Clarification needed in instruction

### ISSUE THREAD

**Issue by fwzmhmd** [freeCodeCamp/freeCodeCamp#13261]
Challenge [Add Images to your Website](https://www.freecodecamp.com/challenges/add-images-to-your-website) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

*This challenge does not give instructions on if the user should put a img tag and where it should be positioned. My reason for this issue is because in the previous challenges it would give a specific instruction on what to do.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by Jack-Pincombe** [comment]
It does not really matter where it goes as it shows you how to do it

**Comment by raisedadead** [comment]
The challenge need to be reworded a bit to give step by step instructions

**Comment by Marmiz** [comment]
@raisedadead I can take care of this if none step forward :)

**Comment by raisedadead** [comment]
@Marmiz yes sure.

**Comment by Marmiz** [comment]
PR submitted:
https://github.com/freeCodeCamp/freeCodeCamp/pull/13272
