### ISSUE TITLE
[beta][UI][UX][enhancement] Introduce collapsible codeblocks within the editor

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13262]
Collapsible codeblocks can prevent this newly created overflow in the editor:
![screen shot 2017-02-09 at 10 04 30 am](https://cloud.githubusercontent.com/assets/7606025/22796532/8791009c-eeaf-11e6-9fe1-4a082d72addd.png)

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (103/100 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60185 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx2w-0003QU-N7
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:26 -0400
Received: from o8.sgmail.github.com ([167.89.101.199]:56768)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx2r-0001rp-1j
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:21 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Nj4Ad0tpAu3vmytNWqjlB9Uk5w0=; b=vNMbr0HetrjV5Kqu
	EgUjpN0QhAI8Jy804UiiXtdh1y2nJtrTVeGDlffJdbt5ubTwrY180paCzeTe1SCV
	DLMJSP3CZh+tU2Qrbf3YUe++2Tzex42/zUdM91fJjXwTTOlUNYswxmMyhPDwd2W0
	dYgF/pyMowSCSMbZxHL/fKp6WKg=
Received: by filter0066p1las1.sendgrid.net with SMTP id filter0066p1las1-25776-59AA0661-33
        2017-09-02 01:16:17.859849828 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id FJaFl6h0Qn6lM-M-QAGTow
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:16:17.731 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:17 +0000 (UTC)

**Comment by pawan-mehta** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (105/100 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f45.google.com ([209.85.218.45]:34818)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx3g-003kvk-BD
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:47:30 +0530
Received: by mail-oi0-f45.google.com with SMTP id n18so13974336oig.2
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:16:51 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=+H13xaj8yGmCfbOJ90DYC8J+erwn1d88yEKko4EdZGs=;
        b=CfXuRT0sFTCH8kMNY1O/Sh84CsPwpwAs246WzoD22OPdMswZtzlAbOFrPINcyW46vY
         euB1+k8DMHXOTNAHVeGE16MqJxMdoRymWQ2rwOVMZISk98cV3cBPkX/NDR6Xs96RJxG3
         gfYeC08GH4BTxw7dsYsTwXLbnpKJOqzq3erhG/kC3eFhUFv0ha5KMZJ3D6TH69VjM6sv
         4BXjG8yOu/HOSWCr5Z9GU0bvWQvRcgsY0MFHAguyNFZA9nRGRqR6nit3Vt5ilJQvjK+w
         jUNsd6CtMLarkyhJcwdS8VCq9t3ljqdx+nPar1JDp2zd4CG4kNe/ZfZY0bZc8+KLZoub
         zcOw==
X-Gm-Message-State: AHPjjUjm9yBPX0lbwMb14Kc9ZYEcDc2VvRd5lqOeT6IHrtOyZUA0wOD2
	KlC1Povw1vrDbfzzQJAVhiHt2L+LpyveJiAchCUoXg==
X-Received: by 10.202.117.129 with SMTP id q123mr3395568oic.16.1504314989787;
        Fri, 01 Sep 2017 18:16:29 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1352743ofe;
        Fri, 1 Sep 2017 18:16:29 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb4YTop2WuTLSh5YlQ5cjctXAmn6i96n15p/Nl8GGCgoBNnMginNTeldzF87cydA4f4iZyrG
X-Received: by 10.36.66.68 with SMTP id i65mr1341293itb.170.1504314989196;
        Fri, 01 Sep 2017 18:16:29 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504314989; cv=none;
        d=google.com; s=arc-20160816;
        b=quiRDsCHv0sbu/EYJxPyK7xcP6Oc3lWD8bhYPawKEBwidBCLBsIgSAQ4IMkeCVR+Ye
         3DuvmVGdAuHA3rwaBx8rOvmA6QxmKRU1jOw3Cwmce67WfhKA/91kUwxBL3Zb0vHDgFa/
         c0CzMDwnhzzu1K0YMMpgvRm+xHYCj+KWUfjf5WZ5KO8Ff4k+qtwQUUToQcwD8nzf52J8
         lIQQWEBDpW5GqMcnRTSJFhph8Jco8kc9GU/uoFelLUl//KYJeXLJscYamt9Wamv4f9Kw
         IMo6pYf8tSIT6Ao3UpgRG7TPjDucOSF2styQ7uuBIVu7Sss2PcjPxsODbXtUYI3W1Vby
         ohXQ==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=+H13xaj8yGmCfbOJ90DYC8J+erwn1d88yEKko4EdZGs=;
        b=AnUafOIuAJicMD++heE73KeE8k2Z8twvZxwbzeKCkUOu6y9ll3Ffu4YlKhR21uiHd/
         UGanPzS3Q2+3jfRH+y1tsVXkVZu9RKOaQ9vDVFlWYMWIsus6/x3q20zPXjKQatCge4Dk
         HjAZ6KAki693Kf1nV3/V1jrhhV0K8Ej6dCXME6W3rTwXPTQAEO1o4v/7ysVfEsAFpvPQ
         eR/Ecg5IkGm8mrKryeTRZrwKn1Jomgd/cU1jUyd2hGes91Or3vNxun8W7QoXyFMJwNUu
         9lJjfX/X1NGlsWIVoqkYSZLmk0MbGDWPa7aGsff+Ra1nRZlUpG3vpzUesFDm7nywoIo2
         GQBw==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=cBdiumuv;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=CbURdkmq;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.114.176 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o1.sgmail.github.com (o1.sgmail.github.com. [192.254.114.176])
        by mx.google.com with ESMTPS id i76si1258245ioi.222.2017.09.01.18.16.29
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:16:29 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.114.176 as permitted sender) client-ip=192.254.114.176;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=cBdiumuv;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=CbURdkmq;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 192.254.114.176 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=tSRPlMpOkiGCfHET0QMepJrZ8Wk=; b=cBdiumuvGp0YTkZF
	LclCQ0P/6EM4dbI/HHU8qMOzZyRCQjDDNeFvuN+JxO28eiJFeN1AGzhkLGhQn65E
	wWcyYUHV3zIS/0UYBEO4aH0ayUAAd5iFhrlPxZcF+oX4yyPhq21OJOkWYlQgPOMU
	Lp9ueWkMBwnFBskFQb5LBUIfvC4=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=tSRPlMpOkiGCfHET0QMepJrZ8Wk=; b=CbURdkmqrvtEXR9Eqp
	FJhnrhSFg2khZYIitMOdVM69IwA5vP7j6Xy/voHR0QmAlAO0TZbKZPq85ndVvdEW
	2Xg0tPM4o2FgN/Gcf2FN32vYEHRYlQ/shbQjVhwd4f2T8GG2MHp+41a9GRScXVDC
	IeS5mWneb3uMKnSBd5g+EMBXc=
Received: by filter0617p1mdw1.sendgrid.net with SMTP id filter0617p1mdw1-28569-59AA066D-5
        2017-09-02 01:16:29.026740427 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0031p1mdw1.sendgrid.net (SG) with ESMTP id EcFBbxqLQGGTwwZFpygOLA
	for <pawan.ossindia@gmail.com>; Sat, 02 Sep 2017 01:16:28.949 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:29 +0000 (UTC)
