### ISSUE TITLE
This code runs but I think it misuses the return function

### ISSUE THREAD

**Issue by tmusimbi** [freeCodeCamp/freeCodeCamp#13276]
Challenge [Profile Lookup](https://www.freecodecamp.com/challenges/profile-lookup#?solution=%0A%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intriguing%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%0A%5D%3B%0A%0A%0Afunction%20lookUpProfile(firstName%2C%20prop)%7B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20value%3B%0Afor(var%20i%20%3D%200%3B%20i%3C%20contacts.length%3B%20i%2B%2B)%7B%0A%20if(%20contacts%5Bi%5D.firstName%20%3D%3D%3D%20firstName%20%26%26%20contacts%5Bi%5D.hasOwnProperty(prop)%20)%7B%0A%20%20%20%20%20return%20contacts%5Bi%5D%5Bprop%5D%3B%0A%20%20%20%20%7D%0A%20%20%20%20if(firstName%20!%3D%3D%20contacts%5Bi%5D.firstName)%7B%0A%20%20%20%20%20%20value%20%3D%20%22No%20such%20contact%22%3B%0A%20%20%20%20%7D%0A%20%20%20if%20(contacts%5Bi%5D.hasOwnProperty(prop)%20%3D%3D%3D%20false)%7B%0A%20%20%20%20%20%20value%20%3D%22No%20such%20property%22%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%7D%0A%20return%20value%3B%20%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0AlookUpProfile(%22Akira%22%2C%20%22likes%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];


function lookUpProfile(firstName, prop){
// Only change code below this line
  var value;
for(var i = 0; i< contacts.length; i++){
 if( contacts[i].firstName === firstName && contacts[i].hasOwnProperty(prop) ){
     return contacts[i][prop];
    }
    if(firstName !== contacts[i].firstName){
      value = "No such contact";
    }
   if (contacts[i].hasOwnProperty(prop) === false){
      value ="No such property";
    }
    
  }
 return value; 
// Only change code above this line
}

// Change these values to test your function
lookUpProfile("Akira", "likes");

```

**Comment by raisedadead** [comment]
@tmusimbi are you reporting a bug in the challenge? If not please discuss coding assistance and code review in the forum or the chat rooms.

- [Forum](https://forum.freecodecamp.com).
- [JavaScript Chat Room](https://gitter.im/FreeCodeCamp/HelpJavaScript).

**Comment by tmusimbi** [comment]
I am not discussing or looking for coding assistance. Try reviewing it

**Comment by raisedadead** [comment]
As I mentioned earlier, if you need a review of your code, please use the forum and the chat rooms, the issue tracker is for reporting bugs only.
