### ISSUE TITLE
Count from 0.

### ISSUE THREAD

**Issue by DizzysContent** [freeCodeCamp/freeCodeCamp#13273]
Challenge [Use Bracket Notation to Find the Nth Character in a String](https://www.freecodecamp.com/challenges/use-bracket-notation-to-find-the-nth-character-in-a-string#?solution=%0A%2F%2F%20Example%0Avar%20firstName%20%3D%20%22Ada%22%3B%0Avar%20secondLetterOfFirstName%20%3D%20firstName%5B1%5D%3B%0A%0A%2F%2F%20Setup%0Avar%20lastName%20%3D%20%22Lovelace%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20thirdLetterOfLastName%20%3D%20lastName%5B2%5D%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var firstName = "Ada";
var secondLetterOfFirstName = firstName[1];

// Setup
var lastName = "Lovelace";

// Only change code below this line.
var thirdLetterOfLastName = lastName[2];



```
"Let's try to set thirdLetterOfLastName to equal the third letter of the lastName variable using bracket notation. Remember that computers start counting at 0, so the first character is actually the zeroth character." --- But the way you made us count is by starting with 1? if i counted with 0 it would've come up to 'e', which was said to be incorrect? think there's a problem?

**Comment by Matt-Webb** [comment]
> if i counted with 0 it would've come up to 'e', which was said to be incorrect? think there's a problem?

I'm not entirely sure what you mean here...

```
var lastName = "Lovelace";
console.log(lastName[0] === "L"); // true
console.log(lastName[2] === "e"); // false
console.log(lastName[2] === "v"); // true
```

**Comment by raisedadead** [comment]
@DizzysContent 

> But the way you made us count is by starting with 1? if i counted with 0 it would've come up to 'e', which was said to be incorrect? think there's a problem?

I guess, you are have a confusion that in real world the count starts from 1 and in coding it starts from 0.
Leading you to think that by going from the coding convention we should have got the third letter as `e` in the `Lovelace`.

So, trying to clear your confusion, this challenge aims to address the relation between the real world and the way it is counted in coding, with reasoning behind it.

Hence the challenge expects you to get the third letter, as if  you are reading it in real, which would be `v` and the way you have to get in code is by using a index that's counted upwards of `0`.

Do you think this is not clear enough in the challenge?

**Comment by raisedadead** [comment]
Please report back as requested, to re-open.
