### ISSUE TITLE
Bonfire: Inventory Update Test Issue

### ISSUE THREAD

**Issue by gmcclure** [FreeCodeCamp/freecodecamp#1327]
I keep getting array length errors on code that seems correct, if long-winded.

Here's an example of an error:

> assert.equal(inventory([[21, 'Bowling Ball'], [2, 'Dirty Sock'], [1, 'Hair Pin'], [5, 'Microphone']], 
> [[2, 'Hair Pin'], [3, 'Half-Eaten Apple'], [67, 'Bowling Ball'], [7, 'Toothpaste']]).length, 6);
> expected 4 to equal 6

But this is the code's output (taken from node cl):

[ [ 88, 'Bowling Ball' ],
  [ 2, 'Dirty Sock' ],
  [ 3, 'Hair Pin' ],
  [ 3, 'Half-Eaten Apple' ],
  [ 5, 'Microphone' ],
  [ 7, 'Toothpaste' ] ]

This is the code:

```javascript
function inventory(curi, newi) {
  // find really new items
  var brandNew = [], bnIndexes = [];
  newInv.forEach(function(item, idx) {
    var found = false;
    curInv.forEach(function(i) {
      if (item[1] === i[1]) found = true;
    });
    
    if (!found) {
      brandNew.push(item);
      bnIndexes.push(idx);
    }
  });
  
  curi = curi.concat(brandNew);
  
  // get rid of brand new items
  bnIndexes.reverse();
  bnIndexes.forEach(function (x) {
    newi.splice(x, 1);
  });
  
  // increment existing inventory
  newi.forEach(function (item) {
    for (var i = 0; i < curi.length; i++) {
      if (curi[i][1] === item[1]) { 
        curi[i][0] += item[0]; 
        continue;
      }
    }
  });
  
  // sort
  return curi.sort(function(a, b) { return a[1] > b[1]; });
}

// Example inventory lists
var curInv = [
    [21, 'Bowling Ball'],
    [2, 'Dirty Sock'],
    [1, 'Hair Pin'],
    [5, 'Microphone']
];

var newInv = [
    [2, 'Hair Pin'],
    [3, 'Half-Eaten Apple'],
    [67, 'Bowling Ball'],
    [7, 'Toothpaste']
];

inventory(curInv, newInv);
```

**Comment by BerkeleyTrue** [comment]
Your code is incorrect. You are referencing `newInv`, an external variable, within your function.

Remember to use [RASP](https://github.com/FreeCodeCamp/freecodecamp/wiki/How-to-get-help-when-you-get-stuck) before filing an issue

Happy Coding!
