### ISSUE TITLE
[beta] Create a Gradual CSS Linear Gradient

### ISSUE THREAD

**Issue by JHenderson219** [freeCodeCamp/freeCodeCamp#13282]
#### Challenge Name
http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-a-gradual-css-linear-gradient

#### Issue Description

When attempting to submit this challenge with the given <code> background</code> applied to the <code> div </code>, the challenge does not complete successfully. I have copied and pasted the correct values to ensure I am not mistyping.

#### Browser Information

* Browser Name, Version: Google Chrome Version 56.0.2924.87 (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

<style>

  div{ 
    border-radius: 20px;
    width: 70%;
    height: 400px;
    margin:  50 auto;
    background: linear-gradient(35deg,#CCFFFF,#FFCCCC)
  }

</style>

<div></div>
#### Screenshot

![bug1](https://cloud.githubusercontent.com/assets/13026589/22840484/943029b2-ef82-11e6-9c96-c4d7feb1e698.png)

**Comment by JHenderson219** [comment]
Note: Issue disappeared after a second browser refresh. Closing the issue, but will reopen if problem recurs.

**Comment by kuklinistvan** [comment]
![kepernyokep_2018-08-10_14-01-03](https://user-images.githubusercontent.com/19473224/43956830-e6bc1188-9ca5-11e8-8c2b-a724326a9f57.png)
Maybe I'm simply wrong but I'm experiencing something similar with the deployed version.

**Comment by rassamshareef** [comment]
It's an issue with the non-existent semi colon at the end of it. Just add it and you'll get through. :)
