### ISSUE TITLE
Waypoint 15: Style Text Inputs as Form Controls; Possible visual error

### ISSUE THREAD

**Issue by greatsquiggy** [FreeCodeCamp/FreeCodeCamp#1328]
Responsive Design with Bootstrap
15. Waypoint: Style Text Inputs as Form Controls
Third Check mark down
![way 15](https://cloud.githubusercontent.com/assets/13384093/8756111/b577877c-2c9d-11e5-945f-77626e4b44dc.png)
I am pretty sure just the "form-control" part is supposed to be in pink

**Comment by arxene** [comment]
I noticed that too.

**Comment by fabricionoda** [comment]
Anyone knows how check this item?

**Comment by krisgesling** [comment]
Seems this has been reported a few times - bug #'s 1383, 1328, 1281, 1082
Looks like QuincyLarson fixed this on 20 June, so I'm assuming it just hasn't yet been pushed out.
