### ISSUE TITLE
[beta][UI][UX][enhancement] Regular Expressions issues

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13289]
I jumped to Regular expressions section of the curriculum, below are my notes

**The introduction** to the section is very nice!
http://beta.freecodecamp.com/en/challenges/regular-expressions/introduction-to-the-regular-expression-challenges
![screen shot 2017-02-11 at 9 28 26 am](https://cloud.githubusercontent.com/assets/7606025/22855893/790de92a-f03c-11e6-8c34-a11c60f35848.png)

**The first challenge** The first thing i recognize is the notification system it pops up in a corner away from all other buttons in the User Interface, its dark, small and I almost miss it. The message reads "Your next challenge has arrived". It relays no new information and it does so poorly especially in night mode. 👎 

I noticed the layout is different, there is a much wider instructions panel, it is amazing!

The instructions panel has one problem its height is cut off too soon, it looks like a 100 pixels...

![screen shot 2017-02-11 at 9 33 11 am](https://cloud.githubusercontent.com/assets/7606025/22855967/79f4d780-f03d-11e6-8c9e-846c43a7d580.png)

**I find the solution...**
The modal window forces me to move on to the next challenge. I never appreciate this. 
The whole point of FreeCodeCamp is to work at your own pace. The modal is aggressive .

![screen shot 2017-02-11 at 9 42 39 am](https://cloud.githubusercontent.com/assets/7606025/22856016/7588dcc2-f03e-11e6-8122-02e29479ece5.png)

The Second Challenge 
- the notification repeats and I am confused. Because the layout did not change.
![screen shot 2017-02-11 at 9 42 43 am](https://cloud.githubusercontent.com/assets/7606025/22856017/7acd05be-f03e-11e6-8527-53033e354943.png)

But the message is there I guess to help me realize that I have loaded a new page?

**Comment by QuincyLarson** [comment]
@tommygebru yes - the congratulations modal looks wrong in night mode - the top bar should definitely be green.

Also, we have tinkered with the idea of not having independently scrolling sections and instead just letting people scroll up and down, or with putting the preview output below the code editor instead of to the side (a 2-column layout) or even a 1-column layout. What are your thoughts on these?

**Comment by tommygebru** [comment]
I think that you have the right idea, while this section of the curriculum does not have a Phone embedded into the page layout, it definitely benefits from having a wide area for both columns.
The text editor has enough room beneath it to have a more accessible and thoughtful output section. 
This will perhaps also remove the need for too many scrollbars when the viewport supports multiple columns :thumbsup:

**Comment by QuincyLarson** [comment]
@tommygebru thanks for your feedback. We are going to stick with the current UI for now so we can focus on shipping this branch to production. Then we can make further incremental changes from there.
