### ISSUE TITLE
Bug: tests pass without arguments in the function call. 

### ISSUE THREAD

**Issue by forkerino** [freeCodeCamp/freeCodeCamp#13280]
Challenge [Passing Values to Functions with Arguments](https://www.freecodecamp.com/challenges/passing-values-to-functions-with-arguments#?solution=%0A%2F%2F%20Example%0Afunction%20ourFunctionWithArgs(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunctionWithArgs(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Afunction%20functionWithArgs(a%2C%20b)%7B%0A%20%20console.log(a%20%2B%20b)%3B%0A%7D%0A%0AfunctionWithArgs(1%2C0)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Someone came into the help room on gitter asking why he didn't pass the challenge with `functionWithArgs();` (which is correct), but did pass with `functionWithArgs( );` (note the extra space). I tested it and the second indeed passes all tests. Seems necessary to test for passing proper arguments.

**Comment by OFFLlNE** [comment]
When I reset the code and wrote only `functionWithArgs( );` it allows me to pass the challenge. The tests have correct answers default (3 tests already correct after resetting code)

**Comment by Manish-Giri** [comment]
I'll try to do this...

**Comment by teeleek** [comment]
Okay

Puttasak insee

เมื่อ 11 ก.พ. 2017 00:28 "Pieter Stokkink" <notifications@github.com>
เขียนว่า

**Comment by Manish-Giri** [comment]
I'll investigate this...

**Comment by forkerino** [comment]
Thanks @Manish-Giri
