### ISSUE TITLE
Waypoint: Join Our Chat Room

### ISSUE THREAD

**Issue by saadanerdetbare** [FreeCodeCamp/FreeCodeCamp#1329]
In the intro to the chatroom it would be nice to also mention the possibility of code markup. Especially in the help chat it is much eayser to help people if they post with markup instead of just posting their code as text

**Comment by carl-parrish** [comment]
So this is a request to update the video? Or perhaps to create a Field Guild regarding Github Flavored Markdown (GFM) and adding a link to it on this Waypoint?

**Comment by saadanerdetbare** [comment]
Both would be the best solution - a fieldguide with the details and then the video mentioning the filed guide. The video does not have to go into the details about 'backticks has to be on seperate lines' etc.

**Comment by benschenker** [comment]
Closing as stale, please reopen if this is still an issue
