### ISSUE TITLE
Waypoint 31 :Add Placeholder Text to a Text Field

### ISSUE THREAD

**Issue by nbc0711** [FreeCodeCamp/freecodecamp#1330]
The second objective in this Waypoint has bugged text until the objective is met, then it appears normally.
<img width="350" alt="screen shot 2015-07-18 at 3 25 58 am" src="https://cloud.githubusercontent.com/assets/13278254/8761107/15c9e4aa-2d05-11e5-8e60-9532a6cb70f2.png">
I believe I may have found the offending line of code:
https://github.com/FreeCodeCamp/freecodecamp/blob/91d6520817b9ebe4d9851181fe39a18fc4534db4/seed/challenges/basic-html5-and-css.json#L1641
although I dont know what I'm looking at yet to attempt an edit

I'd love to learn what was wrong and how to fix it if at all possible
Thanks
Nathan

**Comment by keodren** [comment]
Similar issue here. I´m using Firefox 39.0
![waypoint31](https://cloud.githubusercontent.com/assets/2314644/8895932/249859a0-33b1-11e5-863b-4abaaad0e743.png)

When I add the *placeholder* attribute it changes to: 'Set the value of your placeholder attribute to "cat photo URL".'

**Comment by BerkeleyTrue** [comment]
fixed 

Happy coding!
