### ISSUE TITLE
Multiple Errors after refreshing

### ISSUE THREAD

**Issue by gelbelle** [freeCodeCamp/freeCodeCamp#13306]
Challenge [global-scope-and-functions](http://beta.freecodecamp.com/en/challenges/basic-javascript/global-scope-and-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


// Declare your variable here
var myGlobal = 10;

function fun1() {
  // Assign 5 to oopsGlobal Here
  oopsGlobal = 5;
}

// Only change code above this line
function fun2() {
  var output = "";
  if (typeof myGlobal != "undefined") {
    output += "myGlobal: " + myGlobal;
  }
  if (typeof oopsGlobal != "undefined") {
    output += " oopsGlobal: " + oopsGlobal;
  }
  console.log(output);
}

```

The first time I attempted to submit my code it said I had not assigned 5 to oopsGlobal. After a refresh it said that I had used var oopsGlobal =5; Neither of these is the case.

**Comment by OFFLlNE** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #12706, so I am closing it as a duplicate.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
