### ISSUE TITLE
JS Shopping List

### ISSUE THREAD

**Issue by gelbelle** [freeCodeCamp/freeCodeCamp#13304]
Challenge [shopping-list](http://beta.freecodecamp.com/en/challenges/basic-javascript/shopping-list) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var myList = [];

myList.push(["Chocolate Bar", 15], ["Chicken", 8], ["Carrots", 3], ["Milk", 2], ["Chinese Food", 12]);


```

To get my code to be accepted I had to refresh my browser. It wasn't even marking any of the criteria as passed. This has happened on nearly half of the JS tutorials.

**Comment by rifkegribenes** [comment]
I had same issue with this lesson, Chrome Version 56.0.2924.87 (64-bit), Mac OS X Yosemite 10.10.5 (14F2109)

**Comment by dhcodes** [comment]
Closing as resolved. Seems to be working now; please reopen if it's still not working on your end.
