### ISSUE TITLE
Didn't recognize "Hi World"

### ISSUE THREAD

**Issue by gelbelle** [freeCodeCamp/freeCodeCamp#13305]
Challenge [write-reusable-javascript-with-functions](http://beta.freecodecamp.com/en/challenges/basic-javascript/write-reusable-javascript-with-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


// Example
function ourReusableFunction() {
  console.log("Heyya, World");
}

ourReusableFunction();

// Only change code below this line
function reusableFunction () {
  console.log("Hi World");
}

reusableFunction();

```

It would not pass my "Hi World". There was a red X beside this criteria even though it was identical. Again, refreshing fixed it.

**Comment by OFFLlNE** [comment]
@gelbelle Thank you for reporting the issue

Sometimes the tests crash and the page is needed to be refreshed.
Seems that you have solved the issue yourself

Good luck coding
