### ISSUE TITLE
[beta] Improve tests for "Coding Interview Data Structure Questions: How to Create a Circular Queue"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13303]
Challenge [how-to-create-a-circular-queue](http://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/how-to-create-a-circular-queue) has an issue.

[These lines](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json#L217-L218) misspell `CircularQueue` as `CircularQueuee`, which breaks tests.

I'll submit a quick PR for this right away.

**Comment by Greenheart** [comment]
Turns out that neither of the tests work because they don't execute `printCollection`.

Example:
```js
return (test.printCollection === ['f', 'b', 'c', 'd', 'e'])
return (test.printCollection === ['', 'b', 'c', 'd', 'e'])
```

should be 

```js
return (test.printCollection() === ['f', 'b', 'c', 'd', 'e'])
return (test.printCollection() === ['', 'b', 'c', 'd', 'e'])
```

I'll fix this as well.

**Comment by teeleek** [comment]
Okay

Puttasak insee

เมื่อ 13 ก.พ. 2017 04:23 "Samuel Plumppu" <notifications@github.com>
เขียนว่า
