### ISSUE TITLE
Wrong text in the description area (code example)

### ISSUE THREAD

**Issue by vstrelianyi** [freeCodeCamp/freeCodeCamp#13310]
It seems that there is a wrong code in the description area: 

--------------------------------------------------------------
Let's filter out the cat whose "id" key has a value of 1.
Here's the code to do this:

json = json.filter(function(val) {
  **return (val.id !== 1);**
});
--------------------------------------------------------------
The correct code should be without "!":
**return (val.id == 1);**

#### Prefilter JSON
https://www.freecodecamp.com/challenges/prefilter-json

#### Issue Description
issue in the description text

#### Browser Information
* Browser Name, Version: Chrome 55
* Operating System:  Win 10
* Mobile, Desktop, or Tablet: Desktop

**Comment by OFFLlNE** [comment]
@vstrelianyi Thank you for reporting the issue.

It does not have to be == 1, because then it would filter out all the ones that HAVE id of 1
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by vstrelianyi** [comment]
ok, got it. Just misunderstood the meaning of the phrase "filter out". 
Thx,
Viktor
