### ISSUE TITLE
[beta] Challenge won't pass test despite body font changing to Open Sans and sans-serif

### ISSUE THREAD

**Issue by cecilebertin** [freeCodeCamp/freeCodeCamp#13314]
Challenge [use-a-google-font](http://beta.freecodecamp.com/en/challenges/applied-visual-design/use-a-google-font) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html

<style>
  body {
    font-family: 'Open Sans', sans-serif;
  }
  h4 {
    text-align: center;
    background-color: rgba(45, 45, 45, 0.1);
    padding: 10px;
    font-size: 27px;
    text-transform: uppercase;
  }
  p {
    text-align: justify;
  }
  .links {
    text-align: left;
    color: black;
    opacity: 0.7;
  }
  #thumbnail:hover {
    box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);
  }
  .fullCard {
    width: 245px;
    border: 1px solid #ccc;
    border-radius: 5px;
    margin: 10px 5px;
    padding: 4px;
  }
  .cardContent {
    padding: 10px;
  }
  .cardText {
    margin-bottom: 30px;
  }
</style>
<div class="fullCard" id="thumbnail">
  <div class="cardContent">
    <div class="cardText">
      <h4>Alphabet</h4>
      <hr>
      <em><p>Google was founded by Larry Page and Sergey Brin while they were <u>Ph.D. students</u> at <strong>Stanford University</strong>.</p></em>
    </div>
    <div class="cardLinks">
      <a href="https://en.wikipedia.org/wiki/Larry_Page" class="links">Larry Page</a><br><br>
      <a href="https://en.wikipedia.org/wiki/Sergey_Brin" class="links">Sergey Brin</a>
    </div>
  </div>
</div>

```

**Comment by OFFLlNE** [comment]
Here are a couple suggestions:
Reload the page and run the tests again. A script may have crashed, preventing the tests from running.
Try the challenge in incognito mode. A plugin might be interfering with the tests.
Try the challenge in a different browser. There may be an issue with your version of Chrome.

**Comment by alibonbon** [comment]
[challenge ](https://fagken.com)

**Comment by cecilebertin** [comment]
Hi Lauri,

I tried all of your suggestions. I tried it in Safari and Firefox. I tried it using a new profil on Firefox too. 
It does not work :(
BTW: I don't use Chrome :)

**Comment by carlosvigil** [comment]
Same issue, running latest safari
