### ISSUE TITLE
Waypoint: More information and Go to my next Challenge(ctrl + enter) does not function in mobile layout

### ISSUE THREAD

**Issue by jetstone** [FreeCodeCamp/FreeCodeCamp#1331]
When trying to complete a lesson from my andriod phone in mobile or destkop version of the page the
More information and Go to my next Challenge(ctrl + enter) does not function.
I tried multiple lessons and in firefox and in the chrome browser from my andriod phone but no luck these two buttons are unclickable.

**Comment by benschenker** [comment]
Closing as stale, please reopen if this is still an issue for you
