### ISSUE TITLE
[beta] Unclear instructions/tests for "Coding Interview Data Structure Questions: Create a Set Class"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13311]
Challenge [create-a-set-class](http://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/create-a-set-class) has an issue.

It's unclear whether or not the `add()` method should return a boolean indicating whether or not it added the item to the set. 

This challenge passes without returning a boolean, but the `challengeSeed` of the next challenge returns booleans. This could cause confusion.

If we want to return a boolean status from `add()`, I think we need additional tests for it and possibly mention something in the instructions.

**Comment by jamos-tay** [comment]
Hi, could I work on this?

**Comment by jamos-tay** [comment]
@Greenheart Hi, could I work on this?

**Comment by Greenheart** [comment]
@jamos-tay Sure! :smile:
