### ISSUE TITLE
Don't work one point. All checked everything works except one

### ISSUE THREAD

**Issue by vittorioVT** [freeCodeCamp/freeCodeCamp#13324]
#### Challenge Name

https://www.freecodecamp.com/challenges/counting-cards#?solution=%0Avar%20count%20%3D%200%3B%0A%0A%20function%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20%20%20if%20(card%20%3E%3D%202%20%26%26%20card%20%3C%3D6)%20%7B%0A%20%20%20%20%20%20count%20%2B%2B%3B%0A%20%20%20%20%0A%20%20%7D%20else%20if%20(card%20%3E%3D%207%20%26%26%20card%20%3C%3D9)%20%7B%0A%20%20%20%20%20%20count%20%3D%2B%200%3B%0A%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%7D%20else%20if%20(card%20%3D%3D%2010%20%7C%7C%20card%20%3D%3D%20%22J%22%20%7C%7C%20card%20%3D%3D%20%22Q%22%20%7C%7C%20card%20%3D%3D%20%22K%22%20%7C%7C%20card%20%3D%3D%20%22A%22)%20%7B%0A%20%20%20%20%20%20count%20--%3B%0A%20%20%20%20%20%20%20%0A%20%20%7D%0A%20%20%20%20%0A%20%20%20if%20(count%20%3E%200)%20%7B%0A%20%20%20%20%20%0A%20%20%20%20%20return%20count%20%2B%20%22%20%22%20%2B%20%22Bet%22%3B%0A%20%20%20%20%20%0A%20%20%20%7D%20else%20if%20(count%20%3C%3D%200)%20%7B%0A%20%20%20%20%20%0A%20%20%20%20%20return%20count%20%2B%20%22%20%22%20%2B%20%22Hold%22%3B%20%20%0A%20%20%20%7D%0A%20%20%0A%20%20%20%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0A%0A%20cc(2)%3B%20cc(%22J%22)%3B%20cc(9)%3B%20cc(2)%3B%20cc(7)%3B%20%20%20%0A%20%0A

#### Browser Information

Chrome

#### Your Code

```js
// Counting Cards

var count = 0;
 function cc(card) {
  // Only change code below this line
    if (card >= 2 && card <=6) {
      count ++;
     } 
  else if (card >= 7 && card <=9) {
      count =+ 0;
    } 
 else if (card == 10 || card == "J" || card == "Q" || card == "K" || card == "A") {
      count --;
   }
     if (count > 0) {
     return count + " " + "Bet";
   } 
   else if (count <= 0) {
     return count + " " + "Hold";  
   }
     // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display

 cc(2); cc("J"); cc(9); cc(2); cc(7);   
```

#### Screenshot

![counting_card](https://cloud.githubusercontent.com/assets/25430289/22900583/85b43196-f237-11e6-9c6b-a5abf879afb6.png)

**Comment by Manish-Giri** [comment]
@vittorioVT The problem is in this line - `count =+ 0;`.  In that `else-if`, you're supposed to leave `count` as is, so you probably want `count +=  0`, not `count =+0`. Do that, you'll pass the challenge.

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) or the [HelpJS Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) if you need help with challenges like these in future. Happy Coding!

**Comment by erictleung** [comment]
@vittorioVT take the advice the above. Please use the help rooms for coding questions. Happy coding!

**Comment by vittorioVT** [comment]
Thanks!

2017-02-14 2:27 GMT+02:00 Manish Giri <notifications@github.com>:
