### ISSUE TITLE
All progress lost within certification

### ISSUE THREAD

**Issue by SimplySpoons** [freeCodeCamp/freeCodeCamp#13320]
I’m currently working my way through the Back End Development Certification. I logged out of my account on FreeCodeCamp, and after logging back in, I’ve lost all of my progress within the Map, and it’s saying that I haven’t completed any of the Back End Development Certification work, however, as of a few days ago, I had completed all the way up to the “Request Header Parser Microservice” section of the API Projects. I've posted on the FreeCodeCamp forum and emailed team@freecodecamp.com, but I haven't heard anything back. Is there any way to restore my progress? Thank you so much!

#### Browser Information

* Both Firefox (Version 50.1.0) and Chrome (Version 56.0.2924.87)
* Operating System: OS X El Captain (Version 10.11.6)
* Mobile, Desktop, or Tablet: Desktop

**Comment by raisedadead** [comment]
@SimplySpoons sorry to here about your issue, we are looking into this.
/cc @BerkeleyTrue @QuincyLarson

**Comment by SimplySpoons** [comment]
@raisedadead Thank you so much! Please let me know if you need any further information from me. Thanks again!

**Comment by BerkeleyTrue** [comment]
@SimplySpoons Please send a support email to @QuincyLarson at team@freecodecamp.com.

Hope we can get this worked out for you soon.

Happy Coding

**Comment by SimplySpoons** [comment]
@BerkeleyTrue I emailed team@freecodecamp.com last Thursday (2/9/2017,) and I didn't hear back. I'll send along another email. Thanks again! :)

**Comment by QuincyLarson** [comment]
@SimplySpoons that's my fault. I'm behind. I'll get back to you ASAP and help you figure this out :)

**Comment by SimplySpoons** [comment]
@QuincyLarson No worries! Sounds good! Thank you so much :)

**Comment by SimplySpoons** [comment]
@QuincyLarson Did you have a chance to take a look at this? :) Thanks again!
