### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Jelailah** [freeCodeCamp/freeCodeCamp#13329]
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

I can't see any error in the above code. But, I can't go to the next level. It claims there is an issue.

**Comment by tommygebru** [comment]
Have you tried the chatroom already? @Jelailah

**Comment by tommygebru** [comment]
https://gitter.im/FreeCodeCamp/Help?source=orgpage

**Comment by texas2010** [comment]
@Jelailah it seem you use phone. but it is better to use computer.   code editor have an issue with phone. sorry about that!
