### ISSUE TITLE
Challenge is not accepting correct code.

### ISSUE THREAD

**Issue by dthiberville** [freeCodeCamp/freeCodeCamp#13322]
Challenge [adjust-the-width-of-an-element-using-the-width-property](http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-width-of-an-element-using-the-width-property) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible:

In this Challenge, I put width: 245px; under the .fullCard class element in the CSS portion of the code but when I run it, it continues to tell me: Keep Trying.  Either the instructions are not very clear or there is an issue with reading the code. 

Thanks

```html


<style>
  h4 {
    text-align: center;
  }
  p {
    text-align: justify;
  }
  .links {
    margin-right: 20px;
    text-align: left;
  }
  .fullCard {
    
    border: 1px solid #ccc;
    border-radius: 5px;
    margin: 10px 5px;
    padding: 4px;
    width: 245px;
   
  }
  .cardContent {
    padding: 10px;
  }
</style>
<div class="fullCard">
  <div class="cardContent">
    <div class="cardText">
      <h4>Google</h4>
      <p>Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University.</p>
    </div>
    <div class="cardLinks">
      <a href="https://en.wikipedia.org/wiki/Larry_Page" class="links">Larry Page</a>
      <a href="https://en.wikipedia.org/wiki/Sergey_Brin" class="links">Sergey Brin</a>
    </div>
  </div>
</div>

```

**Comment by dhcodes** [comment]
@dthiberville what browser?

**Comment by dthiberville** [comment]
This is using chrome.



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by manur1984** [comment]
How can i opt out from the notifications that keep coming to my email plz

**Comment by Manish-Giri** [comment]
Works for me, on chrome.

**Comment by jecmstudios** [comment]
I am experiening the same issues with Chrome.

**Comment by jecmstudios** [comment]
And none of the challenges are even loading up on my internet explorer and Avast Safe Browser (yeah, no one's heard of it) is experiencing the same issue.

**Comment by tommygebru** [comment]
@manur1984 to opt out of github notifications unsubscribe from each thread you have contributed to or you can go to https://github.com/settings/notifications and manage them all there 👍
