### ISSUE TITLE
Linux Firefox bonfire 1 problem

### ISSUE THREAD

**Issue by BoDonkey** [FreeCodeCamp/FreeCodeCamp#1333]
Challenge http://www.freecodecamp.com/challenges/bonfire-meet-bonfire has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I was in the gitter help chat and a user mentioned that this bonfire was not working. In the output under the run button it states "console not defined". I used Ubuntu and an older version of firefox on Parallels and was able to reproduce the error. The subsequent Bonfires (or at least the next 2) don't have this same error.

My virtual Ubuntu is a little kludgy, so I'm not able to easily update to a newer firefox and retest.

**Comment by benschenker** [comment]
Hey @BoDonkey thanks for reporting this.

Can you retest this?  I can't replicate this issue.
