### ISSUE TITLE
Linking issue

### ISSUE THREAD

**Issue by dht0my** [FreeCodeCamp/FreeCodeCamp#1334]
Challenge http://www.freecodecamp.com/challenges/waypoint-mobile-responsive-images has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Hello

After I complete this challenge and I click "go to my next challenge" I am redirected here: http://www.freecodecamp.com/challenges/zipline-build-a-pomodoro-clock

**Comment by BerkeleyTrue** [comment]
Hello @dht0my 

Are you still having this issue?

**Comment by dht0my** [comment]
No. It is fixed now.

**Comment by BerkeleyTrue** [comment]
Ok, in the future please closes issue when they have resolved.
