### ISSUE TITLE
Challenge is not accepting the correct code

### ISSUE THREAD

**Issue by Jelailah** [freeCodeCamp/freeCodeCamp#13345]
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by Jelailah** [comment]
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

**Comment by teeleek** [comment]
Okay

Puttasak insee

เมื่อ 14 ก.พ. 2017 16:03 "Jelailah" <notifications@github.com> เขียนว่า
