### ISSUE TITLE
Anchor Links Do Not Work on Mobile Phones

### ISSUE THREAD

**Issue by JTMKoenig** [freeCodeCamp/freeCodeCamp#13355]
Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The project specifies that you must be able to"navigate to different sections of the webpage by clicking buttons in the navigation."

This is not possible when using Codepen on a browser on a mobile phone.

I have created links to the various sections of my page as specified in the project objectives. 

```
<ul>
      <li><a href="#bio">BIO</a></li>
      <li><a href="#work">WORK</a></li>
      <li><a href="#contact">CONTACT</a></li>
    </ul>
```
I then created anchor points using IDs in my page 
`<div class="bio" id="bio">`

Unfortunately, the `<a href="#bio">Bio</a>` link does not work when I test the page on my mobile phone. I believe this has to do with the Codepen application and its limits. I have not seen any information on Free Code Camp about how to work around this issue. I have tried using the `target="_self"` and that does not work either. 

For now I will simply move on, knowing that my links will only work on the desktop and hoping that were I to actually build a site not on CodePen, that the anchor links would work.

It would be nice to specify this "hiccup" on the project information page.

**Comment by pratickjha** [comment]
I too faced same problem. It's best to work on a computer Mobile browser doesn't support all symbols so thes problems happen. Try it on chrome in your computer it will be fine

**Comment by noecaseres** [comment]
I'm facing the same issue. How have you fixed it?
