### ISSUE TITLE
[Applied Visual Design - FCC(Beta)]: Tests are Failing While having Correct Code.

### ISSUE THREAD

**Issue by shashank7200** [freeCodeCamp/freeCodeCamp#13353]
Challenge [create-movement-using-css-animation](http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-movement-using-css-animation) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  div{
    height:40px;
    width: 70%;
    background:black;
    margin: 50 auto;
    border-radius: 5px;
    position: relative;
  }

#rect {
  animation-name: rainbow;
  animation-duration: 4s;
}

@keyframes rainbow {
  0% {
    background-color: blue;
    left:0px;
  }
  
  50% {
    background-color: green;
    left:25px; 
  }
  
  100% {
    background-color: yellow;
    left:-25px;
  }
  
}
</style>

<div id="rect"></div>

```

![Bug Screenshot](http://i.imgur.com/rBTHwLn.png)

**Comment by cdrainxv** [comment]
@shashank7200: You are missing some of the challenge code. Where is your `top` css properties at all the keyframes? Reset the code and reattempt.

Note: There are a handful of [Help rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) to help with non-issue related questions such as above.

**Comment by shashank7200** [comment]
Issue is not reproducing after some changes, All tests are passing! @raisedadead Please Close the Issue. @cdrainxv Thanks for your Suggestion.
