### ISSUE TITLE
Inventory Update test issues.

### ISSUE THREAD

**Issue by P4ndemic** [freeCodeCamp/freeCodeCamp#13361]
Challenge [Inventory Update](https://www.freecodecamp.com/challenges/inventory-update) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function updateInventory(arr1, arr2) {
  var flattened = arr1.reduce(function(a, b) {
    return a.concat(b);
  });  
    for (var x = 0; x < arr2.length; x++) {
      if (flattened.indexOf(arr2[x][1]) >= 0) {
        var index = flattened.indexOf(arr2[x][1]);
        switch (index) {
          case 1:
            index = 0;
            break;
          case 3:
            index = 1;
            break;
          case 5:
            index = 2;
            break;
          case 7:
            index = 3;
            break;
        }
        arr1[index][0] += arr2[x][0];     
      
      }
//       else if (arr1[0].length === 0){ 
//         console.log(arr1[0]);
//         arr1.push(arr2[x]);
//         arr1.splice(0, 1);
//       }
      else {
        arr1.push(arr2[x]);
      }      
    }
    arr1.sort(function (a, b) {
      if (a[1] > b[1]) {
        return 1;
      }
      if (a[1] < b[1]) {
        return -1;
      }
      return 0;
    });
  
    
    return arr1;
}

// Example inventory lists
var curInv = [
    []
];

var newInv = [
    [2, "Hair Pin"], [3, "Half-Eaten Apple"], [67, "Bowling Ball"], [7, "Toothpaste"]
];

updateInventory(curInv, newInv);



```
Now for the 5th testcase first of all I checked solutions on the internet and it seems they past the test even when they return the empty array at arr[0] like so: 
[[], [67, "Bowling Ball"], [2, "Hair Pin"], [3, "Half-Eaten Apple"], [7, "Toothpaste"]] 
But in the testcase "should return" the empty string does not appear.
That's why at first I removed it but even if I don't remove it, this code doesn't seem to pass the test even though it displays the exact same resultArray as far as I can tell.

Would be great to find out if this is a bug, my code somewhere or maybe something browser-related, using chrome, but I tried it on other browsers and firefox as well and in incognito just to make sure it's not the extensions.

**Comment by jamos-tay** [comment]
Hi @P4ndemic,

The code fails test case 5 because it's calling `reduce` on an empty array which throws an error. `reduce` cannot be called on an empty array unless an `initialValue` is provided as a second parameter. Try replacing your second line with this:
```
  var flattened = arr1.reduce(function(a, b) {
    return a.concat(b);
  }, []);  
```

**Comment by P4ndemic** [comment]
Ah yea thank you, didn't know I couldn't call reduce on empty array.
