### ISSUE TITLE
Issue with Freecodecamp Palindrome challenge

### ISSUE THREAD

**Issue by shravan4000** [freeCodeCamp/freeCodeCamp#13364]
#### Challenge Name
https://www.freecodecamp.com/challenges/check-for-palindromes

#### Issue Description
The issue occurs with one of the tests which fails when you actually execute the program. The failing test is palindrome("1 eye for of 1 eye.") should return false. This test fails even though my logic is correct as per the requirement of the challenge i.e. to remove all the spaces and special characters and convert to lower case and reverse and compare. 

#### Browser Information

* Browser Name, Version:  Chrome  56.0.2924.87 (Official Build) (64-bit)
* Operating System: Mac OS X  JavaScript	V8 5.6.326.50
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code

```
function palindrome(str) {
  // Good luck!
![screen shot 2017-02-15 at 10 35 50 pm](https://cloud.githubusercontent.com/assets/24992493/22985716/41e19820-f3cf-11e6-9397-b4ad046cc1f7.png)
  str = str.replace(/\d+|\s+|[_,\|\\\/-:\(\).]+/g,'');
  str = str.toLowerCase();
  console.log(str);
  var Arr = str.split('');
  var revArr = Arr.reverse();
  var newVal = revArr.join('');
  if(str == newVal){
  return true;
  }
  else{
    return false;
  }
}


palindrome("1 eye for of 1 eye.");


```
#### Screenshot

![screen shot 2017-02-15 at 10 35 50 pm](https://cloud.githubusercontent.com/assets/24992493/22985747/61409694-f3cf-11e6-812c-b49c7a511318.png)

**Comment by sgurnoor** [comment]
You're also removing digits when you're not supposed to.
![screen shot 2017-02-15 at 5 56 31 pm](https://cloud.githubusercontent.com/assets/14129624/22999180/338eac6c-f3a8-11e6-88ca-62b119b5adc4.jpg)

**Comment by no-stack-dub-sack** [comment]
@shravan4000 it looks like @sgurnoor is correct. To simplify things, try using a regex character that matches several things at once, for instance check out what this regex does [here](http://www.myezapp.com/apps/dev/regexp/show.ws) `/[^\w]|_/` (select Javascript and don't include the first or last slash). Also, chaining your methods will save you several lines, e.g. 
```js
var reverse = newStr.split('').reverse().join('');
```

Keep in mind for the future though, the issue tracker is only for reporting bugs - if you are not sure something is a bug, the [gitter chatrooms](https://gitter.im/FreeCodeCamp/Help) are a great place to start. If someone can confirm that its not an issue with your solution, then here would be the right place to raise an issue. Closing this for now, if you feel I am wrong in closing it, please re-open and provide additional detail.

Good luck and happy coding! 😄

**Comment by shravan4000** [comment]
@sgurnoor  @no-stack-dub-sack  Thank You for your help
