### ISSUE TITLE
Create a Bootstrap Headline

### ISSUE THREAD

**Issue by mattmm41286** [freeCodeCamp/freeCodeCamp#13362]
![h3 element free code camp](https://cloud.githubusercontent.com/assets/25679003/22979668/85faa1a4-f3da-11e6-8d70-7e5a462409fd.png)
Not really sure what I am doing wrong.  I saw another post on this.  I closed off the H3 tag.  Any suggestions?

**Comment by raisedadead** [comment]
I can see that you have used, capitalizes `h` in the tags as in `<H3></H3>` and our tests are looking for `h3`.

The former may not be a standard practice is perfectly valid code. Keeping in tune with freeCodeCamp philosophy we focus on teaching concepts and not best/practice in the regular challenges, hence this valid code should be allowed.

I think we should allow the tests to accept this, but this would mean a change to all of the challenges. I am okay to open this up for a fix, but will wait for @freeCodeCamp/moderators to have a view as well.

**Comment by amandacsim** [comment]
Stop

**Comment by mattmm41286** [comment]
Okay that was simple.  Brand new to coding.  Thanks for the correction.

**Comment by raisedadead** [comment]
Hello @amandacsim !

Looks like you may have accidentally subscribed to all notifications for the freeCodeCamp repository. To stop receiving notifications please visit the 

https://github.com/FreeCodeCamp/FreeCodeCamp/subscription

We are sorry for your inconvenience!
