### ISSUE TITLE
Change the Font Size of an Element

### ISSUE THREAD

**Issue by cosmonaut98** [freeCodeCamp/freeCodeCamp#13367]
Change the Font Size of an Element

<style>
  .red-text {
    color: red;
    font-size: 16px
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

the task, Between the style tags, give the p elements font-size of 16px. Browser and Text zoom should be at 100% is not ticked. and shows:
Error: Can't execute code from a freed script

**Comment by cdrainxv** [comment]
Note: This page is for only reporting issues related to the functionality, maintenance, or improvement of the site. Questions regarding challenges should be posted in one of the various [Help Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) fcc has to offer. I suggest the [Help](https://gitter.im/FreeCodeCamp/Help) room or even the forum itself. Thanks!

**Comment by texas2010** [comment]
@cosmonaut98 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
