### ISSUE TITLE
What does one need for FCC? (Suggestion for improving the Field Guide)

### ISSUE THREAD

**Issue by redlk** [FreeCodeCamp/FreeCodeCamp#1336]
After reading the field guide there was only one question that I didn't get answer for **what do I need**? What *knowledge* do I need to start FCC? I kinda suspect that none, but this should be included in Field Guide. (I am really sorry for confusion guys)

**Comment by ckent20** [comment]
Basically nothing, you will learn anything you need to know when you start the program. So, yeah, nothing.

**Comment by ahstro** [comment]
Like @ckent20 said. FreeCodeCamp is supposed to allow people with no knowledge of programming to get up and running, whether you do that by just tackling the challenges or if you need more help from the chatroom.

**Comment by paulacolburm** [comment]
Mmb tMf x%mfMdmkf x xbxfTaFf@MfAfafa dwfF dmhfFfMfFf zmffafFM DFtatatata
sfFMtafagz ffff ztafF xtaFBdfTabs "% \√¢°€

**Comment by BerkeleyTrue** [comment]
@paulacolburm Whats going on with that comment?

**Comment by redlk** [comment]
Ok, guys, sorry for not expressing myself clearly. This question was supposed to be a suggestion to improve the Field Guide by adding this question as an article.

**Comment by redlk** [comment]
@BerkeleyTrue what is that label for?

**Comment by benmcmahon100** [comment]
the label just means It'll be dealt with but no one is assigned to it yet

**Comment by BerkeleyTrue** [comment]
When blocked, it means there are no actions to be taken on an issue to progress it along. Until you clarified, it seemed like you where asking the question, "What do I need to get started", which @ckent20 and @ahstro answered. If you hadn't responded in some amount of time this issue would have been closed.

Now, with clarification, we know there is an action to be taken, mainly to discuss with the community if a new field guide is needed.

**Comment by benschenker** [comment]
Closing as stale, you can add a page on the [wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki) for this if it doesn't exist yet
