### ISSUE TITLE
please adding i18n & L10n support ?

### ISSUE THREAD

**Issue by xgqfrms** [freeCodeCamp/freeCodeCamp#13377]
# please adding **i18n & L10n** support ?

**Comment by erictleung** [comment]
Closing as related to https://github.com/freeCodeCamp/freeCodeCamp/issues/11057, https://github.com/freeCodeCamp/freeCodeCamp/issues/13037, https://github.com/freeCodeCamp/freeCodeCamp/issues/7195, and https://github.com/freeCodeCamp/freeCodeCamp/issues/13037. If you'd like to help out with translation efforts, please head over to the [TranslationExpansion](https://github.com/freeCodeCamp/TranslationExpansion) repository. Happy coding!
