### ISSUE TITLE
Manipulate Arrays With pop

### ISSUE THREAD

**Issue by sanjayk722** [freeCodeCamp/freeCodeCamp#13378]
Challenge [Manipulate Arrays With pop](https://www.freecodecamp.com/challenges/manipulate-arrays-with-pop#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0Avar%20removedFromOurArray%20%3D%20ourArray.pop()%3B%20%0A%2F%2F%20removedFromOurArray%20now%20equals%203%2C%20and%20ourArray%20now%20equals%20%5B1%2C2%5D%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B%22John%22%2C%2023%5D%2C%20%5B%22cat%22%2C%202%5D%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20removedFromMyArray%20%3D%20myArray%5B1%5D%3B%0AmyArray.pop(1)%3B%0A%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArray = [1,2,3];
var removedFromOurArray = ourArray.pop(); 
// removedFromOurArray now equals 3, and ourArray now equals [1,2]

// Setup
var myArray = [["John", 23], ["cat", 2]];

// Only change code below this line.
var removedFromMyArray = myArray[1];
myArray.pop(1);




```

**Comment by atjonathan** [comment]
Please use the [Help](https://gitter.im/FreeCodeCamp/Help) chat room for getting challenge related help. Happy Coding!

**Comment by OgunniyiOwamamwen** [comment]
THE CODE ANSWER
Manipulate Arrays With pop


// Example
var ourArray = [1,2,3];
var removedFromOurArray = ourArray.pop(); 
// removedFromOurArray now equals 3, and ourArray now equals [1,2]

// Setup
var myArray = [["John", 23], ["cat", 2]];

// Only change code below this line.
var removedFromMyArray = myArray.pop();
