### ISSUE TITLE
Check for Palindromes Algorithm issue

### ISSUE THREAD

**Issue by MrCookiez** [freeCodeCamp/freeCodeCamp#13370]

**Comment by cdrainxv** [comment]
@MrCookiez: The error is in the logic of your code. How can you compare the strict equality of a string that has undergone lowering its case, removing its non-alphanumeric characters, and reversing its characters in place with the original unchanged str?

This is essentially what you are comparing:

`temp = "myageis00siegaym"` and  ` str = "My age is 0, 0 si ega ym"`

Does `"myageis00siegaym" === "My age is 0, 0 si ega ym"` ? NO. This will always be false.

`temp = "amanaplanacanalpanama"` and  `str = "A man, a plan, a canal. Panama"`

Does `"amanaplanacanalpanama" === "A man, a plan, a canal. Panama"` ? No. This will always be false.

The only difference between the value of your `temp` and `str` variables should be that only the `temp` variable is reversed.

Note: This page is for only reporting issues related to the functionality, maintenance, or improvement of the site. Questions regarding challenges should be posted in one of the various [Help Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) fcc has to offer. I suggest the [HelpJavaScript](https://gitter.im/FreeCodeCamp/HelpJavaScript) room or even the forum itself. Thanks!

**Comment by MrCookiez** [comment]
Thanks

**Comment by no-stack-dub-sack** [comment]
@MrCookiez The issue tracker is for reporting bugs only, in the future, best places for help are out [gitter chatrooms](https://gitter.im/FreeCodeCamp/Help) and the [forum](www.forum.freecodecamp.com). Good luck and happy coding! 

I'm closing this for now, if you feel I'm wring in closing it, please re-open and provide additional detail.
