### ISSUE TITLE
[beta] Basic CSS: "Change the Color of Text" Challenge Issue

### ISSUE THREAD

**Issue by TheRealChrisEdwards** [freeCodeCamp/freeCodeCamp#13376]
Challenge [change-the-color-of-text](http://beta.freecodecamp.com/en/challenges/basic-css/change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

>After fulfilling the user story/challenge & adding the correct inline style attribute to the h2 tag, the console returns:
"message: your h2 element should be red."
Does not return a successful confirmation.
Here is my syntax from the editor window:
```html

<h2 style="color:red">CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

**Comment by abhijeetthecode** [comment]
I'll sort it out. Please assign me this issue before I can begin working. Thanks

**Comment by nickademas943** [comment]
this challenge is also not working for me.

**Comment by cdrainxv** [comment]
@nickademas943 @TheRealChrisEdwards: Use `rgb(255, 0, 0)` instead of `red` for now. I submitted a PR to fix this issue.

**Comment by al3tte** [comment]
It is returning the same error for me including the rgb. Here is my syntax: `<h2 style="color: rgb(255, 0, 0)">CatPhotoApp</h2>` Tried hex and using a semicolon at the end before the last quote as well.

**Comment by Dipanshu27** [comment]
It is working i have compile the code and found no error and able to change the colour

**Comment by al3tte** [comment]
@Dipanshu27 Perhaps I'm missing something else? Here is a screenshot, it isn't registering that the correct answer has been given: it still keeps saying that I need to try again after the color of the element has clearly changed. 

![image](https://cloud.githubusercontent.com/assets/25273475/23066953/0c01fbba-f4eb-11e6-9ade-c16d2503acfe.png)

**Comment by Dipanshu27** [comment]
You can compile that code in different compiler, you should probably get
the error free code

**Comment by al3tte** [comment]
Yep, that was it. Switched to Chrome and it worked. Must be an issue with Firefox. Thank you :relieved:

**Comment by Dipanshu27** [comment]
Your welcome😃

**Comment by lydatech** [comment]
Same issue found in FireFox. Works in Chrome. Please fix. Asking the end user to swap browsers isn't a fix

**Comment by Barterr** [comment]
Same problem, doesn't register as correct in Firefox but works in Chrome.
