### ISSUE TITLE
Clickable "Next article" button in field guide.

### ISSUE THREAD

**Issue by redlk** [FreeCodeCamp/FreeCodeCamp#1337]
Sometimes you want to leave an article to come back to and want to open the next article in a new tab, but the next button doesn't work that way, at least for now.

**Comment by BerkeleyTrue** [comment]
unrelated: '1337' hacks

**Comment by benschenker** [comment]
Closing as stale, see the new [wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki) which has replaced the field guide
