### ISSUE TITLE
oopsGlobal variable

### ISSUE THREAD

**Issue by Sirjustin** [freeCodeCamp/freeCodeCamp#13372]
Without the oopsGlobalVariable the test will pass all but the last test. 
myGlobal should be defined
myGlobal should have a value of 10
myGlobal should be declared using the var keyword
oopsGlobal should have a value of 5
**Do not declare oopsGlobal using the var keyword**

#### Issue Description

It happened on the first try that the test seemed to treat the code as having the var keyword before oopsglobal
#### Browser Information

* Browser Name, Version:  Chrome
* Operating System: Chromebook,
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// Declare your variable here
var myGlobal=10;

function fun1() {
  // Assign 5 to oopsGlobal Here
  oopsGlobal=5;
}


// Only change code above this line
function fun2() {
  var output = "";
  if (typeof myGlobal != "undefined") {
    output += "myGlobal: " + myGlobal;
  }
  if (typeof oopsGlobal != "undefined") {
    output += " oopsGlobal: " + oopsGlobal;
  }
  console.log(output);
}
```

**Comment by raisedadead** [comment]
The below code should fail at the last test case:

```js
// Declare your variable here
var myGlobal = 10;

function fun1() {
  // Assign 5 to oopsGlobal Here
  
}

// Only change code above this line
function fun2() {
  var output = "";
  if (typeof myGlobal != "undefined") {
    output += "myGlobal: " + myGlobal;
  }
  if (typeof oopsGlobal != "undefined") {
    output += " oopsGlobal: " + oopsGlobal;
  }
  console.log(output);
}
```

**Comment by raisedadead** [comment]
Need to update the tests to check if the `oopsGlobal is assigned 5 or not`

**Comment by Manish-Giri** [comment]
I'll try to fix this...

**Comment by XXiphias** [comment]
I believe the initial issue here has not been fixed. The code in the first post should complete all checks but it fails on the last one (Do not declare oopsGlobal using the var keyword).
