### ISSUE TITLE
bug seen

### ISSUE THREAD

**Issue by Geei** [freeCodeCamp/freeCodeCamp#13375]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%0A%3Ch1%3EHello%3C%2Fh1%3E%0A%3Ch1%3Ehello-word%3C%2Fh1%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello</h1>
<h1>hello-word</h1>
```

**Comment by Geei** [comment]
typo error

**Comment by erictleung** [comment]
Closing as resolved. Happy coding!
