### ISSUE TITLE
[beta] Unclear instructions and tests for "Coding Interview Data Structure Questions: Create a Hash Table"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13382]
Challenge [create-a-hash-table](http://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/create-a-hash-table)

1. It's unclear that the `remove()` method should override the key with `null`. It's tested for but not written anywhere except in the test cases.
2. It might be unclear how collisions should be handled efficiently. I think the following sentences suggest an array of arrays with key-value pairs to be stored for each hashed key. 
> One way to handle collisions is to just store both key-value pairs at that index. Then, upon lookup of either, you would have to iterate through the bucket of items to find the key you are looking for. 

This solves the collision problem, but costs performance when multiple items collide as it's expensive to iterate and compare all collisions' keys against what you want. A better solution might be to use an object for each hashed key, where the object's keys in turn are the original unhashed keys. But is this method considered cheating?

Here's my example solution, which currently passes the tests.

```js
let called = 0;
function hash (string) {
  called++;
  return string.split('')
          .reduce((hash, char) => hash + char.charCodeAt(), 0);
}

class HashTable {
  constructor () {
    this.collection = {};
  }
  
  add (key, value) {
    const hashed = hash(key);
    if (this.collection[hashed] === undefined) {
      this.collection[hashed] = {};
    }

    this.collection[hashed][key] = value;
  }
  
  remove (key) {
    this.collection[hash(key)][key] = null;
  }
  
  lookup (key) {
    return this.collection[hash(key)] && this.collection[hash(key)][key];
  }
}

```

**Comment by abhijeetthecode** [comment]
I'll work on this. Please assign me this issue. Thanks

**Comment by Greenheart** [comment]
@abhijeetthecode Thanks for contributing! :+1:

Come chat with us in the [Contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) if you need any help :smile:
