### ISSUE TITLE
[beta] Minor improvements for "Coding Interview Data Structure Questions: Work with Nodes in a Linked List"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13383]
Challenge [work-with-nodes-in-a-linked-list](http://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/work-with-nodes-in-a-linked-list) has an issue.

1. "Instructions" should be replaced with a `<hr>`.
2. Missing semicolon on the last line of the `challengeSeed`.

```js


var Node = function(element){
    this.element = element; 
    this.next = null; 
};
var Kitten = new Node("Kitten");
var Puppy = new Node("Puppy");

Kitten.next = Puppy;
// only add code below this line

// test your code
console.log(Kitten.next)  // missing semicolon

```

**Comment by Manish-Giri** [comment]
@Greenheart I'll do this!
