### ISSUE TITLE
Make buttons for links in WayPoint 'Pair program on bonfires'

### ISSUE THREAD

**Issue by Cylocation** [FreeCodeCamp/FreeCodeCamp#1338]
Way too many people are coming into the LetsPair chatroom not knowing how to get signed up for Screen Hero. They ask for an invite even though they don't need one. The problem seems to me to be related to the visibility of the downloads for Screen Hero in number 5 in the WayPoint 'Pair program on bonfires'. Below is a typical exchange (the first one of the sort that I've participated in) illustrating the problem and my proposed solution which is to:

Make the links more visible by turning them into buttons.

nunya01 21:40
Is an invite the only way to get on Screen Hero? If so, can somebody invite me?
Cylocation 21:44
My gorsh, everyone is asking that. Follow the directions on the http://www.freecodecamp.com/challenges/Waypoint:%20Pair%20Program%20on%20Bonfires page, download it and sign in from inside the app.

b-a-chua 21:44
@Cylocation is there any way to make that message into a sticky?
That way, people can just see it easily.
Cylocation 21:47
@b-a-chua I don't think Gitter has that sort of functionality.
What would be better is to make the Mac and Windows links in number 5 more visibly clickable, perhaps make them buttons.

**Comment by benschenker** [comment]
Closing as stale, please reopen if this is still an issue.
