### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by vberrios** [freeCodeCamp/freeCodeCamp#13394]
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36</code>.

This challenge sucks 

My code:
```javascript

function myLocalScope() {
  'use strict';
  
  
  console.log(myVar);
}
myLocalScope('use strict');

// Run and check the console
// myVar is not defined outside of myLocalScope
console.log(myVar);

// Now remove the console log line to pass the test


```

**Comment by erictleung** [comment]
@vberrios thanks for the constructive criticism. Can you elaborate on your concern over this challenge? I'm not sure what your pain point for this challenge is as there wasn't much feedback on why you're having issues.

**Comment by raisedadead** [comment]
Please clarify as requested.
