### ISSUE TITLE
[beta] Unclear instructions for "Coding Interview Data Structure Questions: Create a Doubly Linked List"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13390]
Challenge [create-a-doubly-linked-list](http://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/create-a-doubly-linked-list) has some minor issues with the instructions:

1. Some paragraphs are split in the middle of sentences.
2. "Instructions" needs to be replaced with a `<hr>` (see other sections for examples)
3. `<code></code>` tags to highlight key words like method names.
4. `<dfn></dfn>` tag around the first occurrence of "Doubly Linked List".
5. **Unclear description of what the input to the methods will be**:

> The add method should accept integers or strings and add them to the list and remove should accept an integer or string and remove all copies of this integer or string that exist in the list.

I think the above could be changed to something like:

> The <code>add</code> method should add an element to the list, while the <code>remove</code> method removes all occurrences of a given element.

**Comment by Manish-Giri** [comment]
@Greenheart I can take this up too...

**Comment by Greenheart** [comment]
@Manish-Giri Thanks!

I just found some issues with the tests that prevents the challenge from being completed at all. I'll fix this right away, but feel free to fix the points of the original post! :blush:

**Comment by Manish-Giri** [comment]
@Greenheart Ah okay, understood!

**Comment by Greenheart** [comment]
@Manish-Giri Seems like I missed [these lines](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json#L1259-L1287).

My solution uses ES6 `class`es, which explains why the ES5-way of adding these hidden utility methods doesn't work.

@Manish-Giri Should we rewrite the tail to make sure people with modern browsers who want to use modern JavaScript can do so and still pass the challenge?

I think one approach would be to simplify the existing `print()` and `printReverse()` to a singel method called `values()` that is visible in the `challengeSeed`. That way, people who want to use classes can do so and see what they need to rewrite to make the challenge work. What do you think? :smile:

**Comment by Manish-Giri** [comment]
@Greenheart 
> Should we rewrite the tail to make sure people with modern browsers who want to use modern JavaScript can do so and still pass the challenge?

Couldn't agree more. Always good to have the option of being able to use the latest versions. 

As for simplifying the `print()` and `printReverse()` methods to `values()`, were you thinking of something on the lines of iterating the linked list both ways and storing the node values in two different arrays in `values()` itself, and then printing it? Or, iterate in one direction and just use `.reverse()` on the list? Either way, I second the idea of simplification!

And lastly, for making `values()` visible in `challengeSeed`, I just have the feeling that it might simplify the challenge a bit too much! 

But you're the best judge! 💯

**Comment by Greenheart** [comment]
@Manish-Giri 
> iterate in one direction and just use `.reverse()` on the array

Exactly :blush:

> And lastly, for making `values()` visible in `challengeSeed`, I just have the feeling that it might simplify the challenge a bit too much! 

The `values()` method would replace `print()` and `printReverse()`, two utility functions that only are used in the tests. The challenge still asks campers to implement `add()` and `remove()` so I don't think the difficulty would be affected. Rather, this would make it easier to use an ES6 class as campers can see what code they need to rewrite to allow their new methods `add()` and `remove()` to be tested.

> But you're the best judge!
No, I'm not! The more that give their opinions, the better :blush:

**Comment by Greenheart** [comment]
@Manish-Giri I created a solution that meets the requirements of this challenge.

```js
class Node {
  constructor (data, prev) {
    this.data = data
    this.prev = prev
    this.next = null
  }
}

class DoublyLinkedList {
  constructor () {
    this.head = null
    this.tail = null
    this._length = 0
  }
  
  values () {
    const result = []
    
    let node = this.head
    
    while (node !== null) {
      result.push(node.data)
      node = node.next
    }
    
    return result
  }

  add (element) {
    if (this.head === null) {
      const node = new Node(element, null)
      this.head = node
      this.tail = node
    } else {
      const node = new Node(element, this.tail)
      this.tail.next = node
      this.tail = node
      ++this._length
    }
  }
  
  remove (element) {
    if (this.head === null) return null
    
    let current = this.head
    const removed = []
    
    while (current !== null) {
      if (current.data === element) {
        removed.push(current.data)
        --this.length
        
        if (current.prev === null) {
          this.head = current.next
        } else {
          current.prev.next = current.next
        }
        
        if (current.next === null) {
          this.tail = current.prev
        } else {
          current.next.prev = current.prev
        }
      }
      
      current = current.next
    }
    
    return removed
  }
}
```

If this `values()` method is used with `.reverse()`, it can effectively replace the `print()` and `printReverse()` methods. 

If we see value in traversing the list from the other way around, I also experimented with combining both use cases into a single method that has a parameter.

```js
values (reverse = false) {
  const start = reverse ? 'tail' : 'head'
  const next = reverse ? 'prev' : 'next'
  const result = []
  
  let node = this[start]
    
  while (node !== null) {
    result.push(node.data)
    node = node[next]
  }
    
  return result
}
```
