### ISSUE TITLE
Challenge "No repeats please" do not process the correct numbers

### ISSUE THREAD

**Issue by ronaldblanco** [freeCodeCamp/freeCodeCamp#13405]
The code is giving the right numbers but the page does not process the tests or is doing it incorrectly, the only correct test is 'returning a number' even that all the others numbers a have tried are OK.
First time I have a problem like this in freecodecamp tests.

Challenge [No repeats please](https://www.freecodecamp.com/challenges/no-repeats-please#?solution=var%20permArr%20%3D%20%5B%5D%2C%20usedChars%20%3D%20%5B%5D%3B%0Afunction%20permute(input)%20%7B%0A%20%20var%20i%2C%20ch%2C%20chars%20%3D%20input.split(%22%22)%3B%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%20chars.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20ch%20%3D%20chars.splice(i%2C%201)%3B%0A%20%20%20%20usedChars.push(ch)%3B%0A%20%20%20%20if%20(chars.length%20%3D%3D%3D%200)%0A%20%20%20%20%20%20permArr%5BpermArr.length%5D%20%3D%20usedChars.join(%22%22)%3B%0A%20%20%20%20permute(chars.join(%22%22))%3B%0A%20%20%20%20chars.splice(i%2C%200%2C%20ch)%3B%0A%20%20%20%20usedChars.pop()%3B%0A%20%20%7D%0A%20%20return%20permArr%3B%0A%7D%0A%0A%0A%0Afunction%20factorial(num)%0A%7B%0A%20%20%20%20%2F%2F%20If%20the%20number%20is%20less%20than%200%2C%20reject%20it.%0A%20%20%20%20if%20(num%20%3C%200)%20%7B%0A%20%20%20%20%20%20%20%20return%20-1%3B%0A%20%20%20%20%7D%0A%20%20%20%20%2F%2F%20If%20the%20number%20is%200%2C%20its%20factorial%20is%201.%0A%20%20%20%20else%20if%20(num%20%3D%3D%3D%200)%20%7B%0A%20%20%20%20%20%20%20%20return%201%3B%0A%20%20%20%20%7D%0A%20%20%20%20var%20tmp%20%3D%20num%3B%0A%20%20%20%20while%20(num--%20%3E%202)%20%7B%0A%20%20%20%20%20%20%20%20tmp%20*%3D%20num%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20tmp%3B%0A%7D%0A%0A%0Afunction%20repet(myarr)%7B%0A%20%20var%20cant%20%3D%200%3B%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20myarr.length%3Bi%2B%2B)%7B%0A%20%20%20%20for(var%20j%20%3D%200%3B%20j%20%3C%20myarr%5Bi%5D.length%20-%201%3Bj%2B%2B)%7B%0A%20%20%20%20%20%20if(myarr%5Bi%5D%5Bj%5D%20%3D%3D%20myarr%5Bi%5D%5Bj%20%2B%201%5D)%7B%0A%20%20%20%20%20%20%20%20cant%2B%2B%3B%0A%20%20%20%20%20%20%20%20j%20%3D%20myarr%5Bi%5D.length%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%7D%20%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20cant%3B%0A%7D%0A%0A%0Afunction%20permAlone(str)%20%7B%0A%20%20var%20cant%20%3D%20factorial(str.length)%3B%0A%20%20var%20final%20%3D%20cant%20-%20repet(permute(str))%3B%0A%20%20return%20final%3B%0A%20%20%2F%2Fif(final%20%3D%3D%3D%2012)%20return%2012%3B%0A%7D%0A%0ApermAlone(%27aaabb%27)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var permArr = [], usedChars = [];
function permute(input) {
  var i, ch, chars = input.split("");
  for (i = 0; i < chars.length; i++) {
    ch = chars.splice(i, 1);
    usedChars.push(ch);
    if (chars.length === 0)
      permArr[permArr.length] = usedChars.join("");
    permute(chars.join(""));
    chars.splice(i, 0, ch);
    usedChars.pop();
  }
  return permArr;
}



function factorial(num)
{
    // If the number is less than 0, reject it.
    if (num < 0) {
        return -1;
    }
    // If the number is 0, its factorial is 1.
    else if (num === 0) {
        return 1;
    }
    var tmp = num;
    while (num-- > 2) {
        tmp *= num;
    }
    return tmp;
}


function repet(myarr){
  var cant = 0;
  for(var i = 0; i < myarr.length;i++){
    for(var j = 0; j < myarr[i].length - 1;j++){
      if(myarr[i][j] == myarr[i][j + 1]){
        cant++;
        j = myarr[i].length;
        
      } 
    }
  }
  return cant;
}


function permAlone(str) {
  var cant = factorial(str.length);
  var final = cant - repet(permute(str));
  return final;
  //if(final === 12) return 12;
}

permAlone('aaabb');

```

**Comment by erictleung** [comment]
@ronaldblanco you have global variables in your code. The tests run the function `permAlone` over and over so any global variables in your code will change with each test, which will have undesirable results. Move your global variables into your function and you should be able to debug more effectively. Your code is incorrect as `permAlone('aab')` returns 6 and not 2, as specified in the challenge.

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by ronaldblanco** [comment]
Thanks erictleung, the global variable was important for the correct result, I could eliminate it but having your comment in mind I close it in another function and it worked OK.
So, thank you very much.
