### ISSUE TITLE
Issue in Convert Html Entities: Unable to pass this bonfire even after desired results on the console

### ISSUE THREAD

**Issue by pratikr1593** [freeCodeCamp/freeCodeCamp#13407]
Challenge [Convert HTML Entities](https://www.freecodecamp.com/challenges/convert-html-entities#?solution=%0Afunction%20convertHTML(str)%20%7B%0A%20%20%2F%2F%20%26colon%3B%26rpar%3B%0A%20%20%0A%20%20var%20placeHolder%3Dstr.split(%22%22)%3B%0A%20%20%0A%20%20for(var%20i%3D0%3Bi%3CplaceHolder.length%3Bi%2B%2B)%7B%0A%20%20%20%20%0A%20%20%20%20switch(placeHolder%5Bi%5D)%7B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20case%20'%26'%3A%0A%20%20%20%20%20%20%20%20placeHolder%5Bi%5D%3D'%26amp%3B'%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20case%20'%3C'%3A%0A%20%20%20%20%20%20%20%20placeHolder%5Bi%5D%3D'%26lt%3B'%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20case%20'%3E'%3A%0A%20%20%20%20%20%20%20%20placeHolder%5Bi%5D%3D'%26gt%3B'%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20case%20'%22'%3A%0A%20%20%20%20%20%20%20%20placeHolder%5Bi%5D%3D'%26quot%3B'%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20case%20%22'%22%3A%0A%20%20%20%20%20%20%20%20placeHolder%5Bi%5D%3D'%26apos'%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20str%3DplaceHolder.join(%22%22)%3B%0A%20%20%0A%20%20%0A%20%20return%20str%3B%0A%7D%0A%0AconvertHTML(%22Shindler's%20List%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function convertHTML(str) {
  // &colon;&rpar;
  
  var placeHolder=str.split("");
  
  for(var i=0;i<placeHolder.length;i++){
    
    switch(placeHolder[i]){
        
      case '&':
        placeHolder[i]='&amp;';
        
        break;
        
        case '<':
        placeHolder[i]='&lt;';
        
        break;
        
        case '>':
        placeHolder[i]='&gt;';
        
        break;
        
        case '"':
        placeHolder[i]='&quot;';
        
        break;
        
        case "'":
        placeHolder[i]='&apos';
        
        break;
        
        
        
    }
    
  }
  
  str=placeHolder.join("");
  
  
  return str;
}

convertHTML("Shindler's List");

```

**Comment by cdrainxv** [comment]
@pratikr1593: Your HTML entity for apostrophes (`'`) is missing an `;`.

Note: This page is only for reporting issues. This seemed like a request for help. Please click on the 'help' button for help with challenge related questions in the chat room for that specific challenge.

**Comment by Greenheart** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
