### ISSUE TITLE
Update URLs for example app

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#13408]
We need to update the links in the challenges from `https://atjonathan.github.io/catphotoapp/` to `http://freecatphotoapp.com/`

Changes are to be made here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/applied-visual-design.json#L1140

and here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/applied-visual-design.json#L1169

**Comment by nellarro** [comment]
I can take it! @raisedadead :)

**Comment by raisedadead** [comment]
@nellarro please go ahead! Good luck. Here are the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by nellarro** [comment]
Donezo :). Thanks!
