### ISSUE TITLE
Issues with linking to Twitch from CodePen IFrame

### ISSUE THREAD

**Issue by Damon-Myers** [FreeCodeCamp/FreeCodeCamp#1340]
Challenge http://www.freecodecamp.com/challenges/zipline-use-the-twitch.tv-json-api has an issue. 

Whenever using Chrome or Firefox to link to user's streams on Twitch from CodePen, the resulting Twitch page will not load properly as it tries to change the 'domain' property of the CodePen IFrame, rather than legitimately opening in a new window or tab.

Screenshot of console:
![twitchlinkerr](https://cloud.githubusercontent.com/assets/6657122/8777489/e3717760-2ebd-11e5-9b64-6ab7ab941eba.png)

**Comment by benschenker** [comment]
Hey @Damon-Myers, this issue has been stale for a while, is it still problematic for you?

**Comment by Damon-Myers** [comment]
@benschenker, it's not problematic for me as I've since moved on from that Zipline, but it's not a desired behavior, so it's still problematic. If you'd like to close it, I can work on finding a solution later when I have more time to contribute.

**Comment by benschenker** [comment]
What I mean, is can you reproduce this issue?

**Comment by Damon-Myers** [comment]
Yes, anytime a link to a Twitch stream is opened from the CodePen IFrame the issue occurs.

**Comment by awesomeaniruddh** [comment]
@Damon-Myers I don't remember being able to reproduce this issue? I used Chrome for my Zipline. Can you reproduce the issue when you try the app from the Fullscreen window that CodePen provides?

**Comment by Damon-Myers** [comment]
@awesomeaniruddh It is still happening for me with Chrome Version 45.0.2454.99 m on Windows 7. I will test it in other OS's and get back to you with what I find out.

**Comment by awesomeaniruddh** [comment]
Thanks for helping out! Can you also link your Twitch zipline? I'll see if
I can reproduce the issue on my end.

**Comment by Damon-Myers** [comment]
Sure thing! It's http://codepen.io/Damon-Myers/full/BNPjoy/

I had also reproduced the issue using another camper's zipline, but I don't remember whose it was. I'll try to find another example.

**Comment by Damon-Myers** [comment]
Apparently my implementation doesn't work in Firefox on Ubuntu at all, but I found that the example project, http://codepen.io/GeoffStorbeck/full/GJKRxZ/, has the same problem in Firefox on Ubuntu. The problem also occurs with both mine and Geoff's pens when using Chrome on Ubuntu.

**Comment by mientje** [comment]
I have the same issue with the twitch codepen. It works in IE but not in Firefox or Chrome. I'm using windows 8.1. I don't know much about API's and HTTP and this situation confuses me. Can I build the app with Ajax and Javascript ? Sifting through all the info that's out there is quite time consuming so I would appreciate a hint. Thank you.

**Comment by mientje** [comment]
The EM I'm getting in Twitch is : Uncaught SecurityError: Failed to set the 'domain' property on 'Document': Assignment is forbidden for sandboxed iframes. and in the codepen  I get : Uncaught TypeError: Cannot read property 'channel' of undefined

**Comment by BerkeleyTrue** [comment]
Is this still an issue?

**Comment by ltegman** [comment]
This is still happening. I don't know that there's much we can do about it on our end besides putting a note in the instructions that twitch links will only work correctly when testing in debug mode (since that doesn't have an iFrame).

**Comment by SaintPeter** [comment]
The workaround that I have been giving users for a long time is to add `target="_blank"` to their URLs.  This is actually true for all of the ziplines, including the Portfolio.  It might make sense to add this to the instructions specifically.

**Comment by Damon-Myers** [comment]
@ltegman I agree. That is most likely the best solution, aside from moving away from using codepen for Ziplines, but that will require more effort than this is worth. 

@SaintPeter I have the issue even when I use target="_blank". The Twitch page for the stream will open, however, it will not load the stream.

**Comment by SaintPeter** [comment]
@Damon-Myers Please confirm that you are using fully qualified domain names, IE: that you have an `http://` or `http://` in front of the URL. 

I suggest that you take your question and CodePen URL to the [HelpZiplines](https://gitter.im/FreeCodeCamp/HelpZiplines) chat room. There may be some other more subtle error that only be identified by inspecting the code.

**Comment by ltegman** [comment]
@SaintPeter This is actually an issue with twitch itself, regardless of what you do in your codepen. When a twitch page is linked to from an iFrame the twitch page it links to will throw a bunch of errors in the console and never load the stream of the user. So the link as far as codepen is concerned "worked" as expected, but the twitch page will not work correctly without a refresh.

**Comment by Damon-Myers** [comment]
@SaintPeter: As stated in several comments above, I have tested this issue with several other campers' Ziplines to verify that it wasn't something I was doing incorrectly in my code.

@ltegman: Thanks again for a great explanation. 

I'm simply going to close this issue for the time being. I'm having to reiterate myself each time a new contributor attempts to solve this bug, and the bug itself isn't large enough to warrant such thorough investigation.

**Comment by mientje** [comment]
Yep, it still is. I get this EM: Uncaught SecurityError: Failed to set the 'domain' property on 'Document': Assignment is forbidden for sandboxed iframes.

I am able to create the links in my own codepen so I don't worry about it too much.
Thanks for trying and greets,
Karin Meersman(Mientje)
Date: Tue, 10 Nov 2015 22:29:35 -0800

**Comment by nvnehi** [comment]
This is still occurring. The only work around when using the created site via codepen is to right click the link and click "open in new tab or window".

As others have stated it's related to how codepen uses an iframe for safety reasons and twitch refusing to allow its content to be contained within an iframe apparently.

I'm fairly sure the staff can tell if a link opens to twitch(since it opens and just doesn't load all the content), regardless if the opened link loads the stream or not is not the fault of the user in this case.

Tried with http, https, and different browsers under linux.

**Comment by SaintPeter** [comment]
You can also add `target="_blank"` to your anchor tag.

**Comment by Damon-Myers** [comment]
@SaintPeter: You've had that exact comment on this issue before and it was shown to be false. The beauty of codepen is that you can see the code alongside the result, if you take a look at my code for the zipline [here](http://codepen.io/Damon-Myers/pen/BNPjoy) you can see on line 100 of the JS I append an anchor with the target attribute set to "_blank". It is not a solution to the issue.

**Comment by nvnehi** [comment]
@SaintPeter Appending target="_blank" does not work, neither do any of the other targets. Confirmed on chrome/firefox under both linux/windows. Twitch doesn't allow an iframe(I think is the issue, the error in console is a bit cryptic) to link to stream.

**Comment by SaintPeter** [comment]
Then I stand corrected . . . again.

**Comment by mientje** [comment]
Dear All,




Maybe you already know this but I didn't : I do not have the problem linking to Twitch when I open the codepen in debug mode. The problem  is there when I open it with full page. 

The same is true for my Simon game by the way. There's a big fat bug in full page mode and in debug mode  my game is buggyish, I starts much later when the it is running on full speed. 

Is that also true for mr Myers and mr nvnehi? 




Greets, 

Karin Meersman





Van: Rex Schrader
Verzonden: ‎zaterdag‎ ‎23‎ ‎januari‎ ‎2016 ‎07‎:‎28
Aan: FreeCodeCamp/FreeCodeCamp
CC: meersmankarin@hotmail.com





Then I stand corrected . . . again.

**Comment by codelogicws** [comment]
I also have Chrome Version 49.0.2623.75 (64-bit) and Ubuntu 14.04 and this issue happens to me as well with multiple CodePen projects including the link provided.

**Comment by mones-cse** [comment]
Oh dear God 
I am not the only one who have faced that same issue and from what I read above , there is not much that  can I do now,

**Comment by LarryMary** [comment]
This just started happening to me yesterday after obtaining a Client ID and updating my twitch.tv app (http://codepen.io/LarryMary/pen/NRNAay). I'm on Windows 8.1 in both Firefox and Chrome. I had no problems when initially creating the app a few weeks ago. Seems like my computer has been flagged as a security risk or something.

**Comment by benjaminboruff** [comment]
This is still happening. I have heard that the twitchtv project will soon be dropped. I don't think this is a browser issue per se; I use Cloud9IDE for my development (a web ide, in the same chrome browser that I also use for codepen) and I have no problems when using Cloud9. The issue only occurs when using codepen's sandboxed environment.

**Comment by Lancemaker** [comment]
I found a behavior that if  we can mimic programatically we can fix this problem. if you click on the link with "open link in a new tab" (assuming that everyone is using <a href="link">) by using the right button of the mouse the link opens properly. so we need to know if its possible to do exacly that.

**Comment by nibewiahn** [comment]
I wonder if its possible do the right click suggestion using JS

**Comment by beowulfskin** [comment]
Glad I found this page. This is still a problem as of July 2017.

**Comment by joshmorel** [comment]
After much tinkering and reading I just decided to add the tooltip: ```title="In CodePen: right-click -> open link in new tab"``` and move on.

Not the best user experience but that's not the point here, right?

**Comment by joshcronkhite** [comment]
@joshmorel My sense is that your solution should be acceptable given the codepen.io environment works the way it does, and Twitch blocks frame-sourced links. I'm implementing your solution as well. Thanks for providing a sensible concession so we can all move on.

**Comment by Medlinator** [comment]
Still an issue 29 Aug 2017.
