### ISSUE TITLE
Project Landing page

### ISSUE THREAD

**Issue by RoniqueRicketts** [freeCodeCamp/freeCodeCamp#13403]
Challenge [build-a-product-landing-page](http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-product-landing-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I am making a suggestion  with the URL for the product landing page. It is currently showing the code for the project so it is not consistent like the other project. Could you guys make it out to be http://codepen.io/freeCodeCamp/full/RKRbwL/ instead of http://codepen.io/freeCodeCamp/pen/RKRbwL

**Comment by erictleung** [comment]
@RoniqueRicketts thanks for catching this. Yes, the URL should have `/full/` not `pen`.

[This line of code](https://github.com/freeCodeCamp/freeCodeCamp/blob/32e3210352ac21590646605f497b43406fafd3c0/seed/challenges/01-responsive-web-design/responsive-web-design-projects.json#L250) needs to be edited.

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by amandaporto** [comment]
I'd like to pick up this issue and make the change :)
