### ISSUE TITLE
Bonfire: Mutations error 

### ISSUE THREAD

**Issue by wabray17** [FreeCodeCamp/FreeCodeCamp#1341]
Challenge http://www.freecodecamp.com/challenges/bonfire-mutations has an issue. 

Every time I run the code, it fails because it says the result was 'undefined.' 
![image](https://cloud.githubusercontent.com/assets/13302428/8781176/8c9426f4-2edb-11e5-9726-4ade92c65714.png)

I ran this same code through the console over at codeacademy.com, and it worked properly. I then just tried to log 'hello' to the console, and it still says that the test returned 'undefined.' 
![image](https://cloud.githubusercontent.com/assets/13302428/8781226/c7164154-2edb-11e5-9d69-bcfcf591318f.png)

Thanks,

**Comment by ABuske** [comment]
Kinda silly, but you want the code to "return", not "console.log"

**Comment by wabray17** [comment]
Yep that did it! Thanks for the quick response.

**Comment by carl-parrish** [comment]
Should this be marked closed then?

**Comment by wabray17** [comment]
Yes, human error was the only issue.
