### ISSUE TITLE
Missing Semicolon in example code

### ISSUE THREAD

**Issue by Sirjustin** [freeCodeCamp/freeCodeCamp#13411]
#### Object Oriented Programming: Understand the Immediately Invoked Function Expression 

http://beta.freecodecamp.com/en/challenges/object-oriented-programming/understand-the-immediately-invoked-function-expression-iife

#### Missing Semicolon in example code

When you follow the example text you are missing a semicolon so I assume that it is a mistake. Please let me know if this isn't an appropriate issue since it isn't technically a bug I guess. 

#### Browser Information

* Browser Name, Version: chrome
* Operating System: chromebook
* Mobile, Desktop, or Tablet: 

#### Your Code

This is the example code. I believe that a semicolon should be present after console.log

```html
(function () {
  console.log("Chirp, chirp!")
})(); // this is an anonymous function expression that executes right away
// Outputs "Chirp, chirp!" immediately
```

**Comment by rarmatei** [comment]
Even if you copy the example into the main work area, you get a warning about a missing semicolon, so I assume you are correct. I'll pick this up for a PR. Thanks for submitting the issue!
