### ISSUE TITLE
Filter method fails in "Diff Two Arrays" challenge

### ISSUE THREAD

**Issue by griffinf3** [freeCodeCamp/freeCodeCamp#13429]
#### Challenge Name
Diff Two Arrays 

#### Issue Description
Results the same with two different methods (filter and index); index method passes the challenge and filter method does not.

#### Browser Information
* Browser Name, Version:  IE 11
* Operating System:  Windows 10
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code
```js
function isEqual(value) {
  return value === this;
}
function diffArray(arr1, arr2) {
  var newArr = [];
...

//Looping through arr1 to find elements that do not exist in arr2  

//my code -- this code does not pass:
    var arr3 = arr2.filter(isEqual, arr1[i]);
  if (arr3.length === 0)
{ newArr.push(arr1[i]);}

//this code published on Internet acceptable for challenge:
    if (arr2.indexOf(arr1[i]) === -1)
 { newArr.push(arr1[i]);}   

...




```

**Comment by raisedadead** [comment]
@griffinf3 thanks for the issue, can you please share the link to the challenge and the complete code with the screen shots of the page.

**Comment by griffinf3** [comment]
link to challenge: https://www.freecodecamp.com/challenges/diff-two-arrays

code:
function isEqual(value) {
  return value === this;
}

function diffArray(arr1, arr2) {
  var newArr = [];
  // Looping through arr1 to find elements that do not exist in arr2  
  for (var i = 0; i < arr1.length; i++) {
    
   
   var arr3 = arr2.filter(isEqual, arr1[i]);
  if (arr3.length === 0)
 //   if (arr2.indexOf(arr1[i]) === -1)
    
   {
      // Pushing the unique to arr1 elements to the newArr
      newArr.push(arr1[i]);
    }
  }
  // Looping through arr2 to find elements that do not exist in arr1
  for (var j = 0; j < arr2.length; j++) {
   
    var arr4 = arr1.filter(isEqual, arr2[j]);
   if (arr4.length === 0)
   // if (arr1.indexOf(arr2[j]) === -1)
    
    {
    
   
      // Pushing the unique to arr2 elements to the newArr    
      newArr.push(arr2[j]);
    }
  }

  return newArr;
}

diffArray([1, "calf", 3, "piglet"], [1, "calf", 3, 4]); 

![code](https://cloud.githubusercontent.com/assets/4950314/23096998/2627e056-f5f7-11e6-8112-93879cde2bd6.png)

**Comment by donofriov** [comment]
Quick note here, if `value === this` is updated to `value == this` everything passes.

![image](https://cloud.githubusercontent.com/assets/4457953/23183440/0b1bd0e2-f84a-11e6-93d1-8ae957dc2e20.png)

**Comment by raisedadead** [comment]
@donofriov thanks a lot for looking into this issue,

@griffinf3 apologies for the delay in getting back. Here is some debug code that will help you understand the problem:

```
function isEqual(value) {
  console.log(typeof value);
  console.log(typeof this);
  return value === this;
}
```

You can then open up the dev tools of your browser (should be <kbd>F12</kbd> on Windows), and switch to the console tab to check the output.

I highly recommend using chrome if you can, but IE should work just fine.

**Comment by raisedadead** [comment]
Let us know if you need any more help in understanding this.
