### ISSUE TITLE
[beta] How to Create a Circular Queue : Instructions need to be clearer

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#13428]
Refers changes from : https://github.com/freeCodeCamp/freeCodeCamp/pull/13308

The instructions sections ned to be more clear, step by step as the tests are currently. The introduction part is clear. But the instructions need to be step to step.

**Comment by bonham000** [comment]
I'd be happy to help with this if needed — in addition, I've been watching for that other PR on the adv. data structures and algorithms to be merged before continuing with some other revisions I'd like to see in this section.

**Comment by Greenheart** [comment]
@bonham000 Glad to hear that! You can take this if you want, I've got plenty of tasks already :smile:

What PR? I'll see i  I can find it.

**Comment by bonham000** [comment]
[This one](https://github.com/freeCodeCamp/freeCodeCamp/pull/13219), it's only on the singly linked list so I could go ahead with the circular queue here. I was planning on revising that after originally working on these challenges.

**Comment by Greenheart** [comment]
@bonham000 Sounds good, tell me if you need anything!

**Comment by bonham000** [comment]
Submitted fix: https://github.com/freeCodeCamp/freeCodeCamp/pull/13453

**Comment by raisedadead** [comment]
Thanks @bonham000 !
