### ISSUE TITLE
Feature Request: In profile ability to edit / remove bonfire results

### ISSUE THREAD

**Issue by carl-parrish** [FreeCodeCamp/FreeCodeCamp#1342]
If there are multiple solutions posted to a bonfire I'd like the ability to remove older versions (though I'd also like to be *able* to keep older versions too). Perhaps the ability to edit the solution on my profile.

**Comment by Arthaey** [comment]
+1, I'd like to see this too.

**Comment by awesomeaniruddh** [comment]
+1

**Comment by bugron** [comment]
+1 That would be a great feature.

**Comment by zngit** [comment]
+1 
I'd like to see this too.

**Comment by bugron** [comment]
@BerkeleyTrue can we close this issue or something like this will be implemented in future?

**Comment by BerkeleyTrue** [comment]
We will be implementing deleting solutions.

**Comment by SaintPeter** [comment]
@BerkeleyTrue - Will this be tied to a particular release?

**Comment by BerkeleyTrue** [comment]
@SaintPeter Nope. Anyone who wants to take a crack at it?

**Comment by ltegman** [comment]
Definitely something I'd enjoy looking into but I don't know when I'll have the time, so if anyone else has the time or interest before I do they should go for it :smile:

**Comment by ChristianLapinig** [comment]
This would be great

**Comment by ltegman** [comment]
@BerkeleyTrue Are will still planning to implement this as something a user can choose to do? I know for a time there was talk about deleting all but the most recent solution from an given camper.

**Comment by carl-parrish** [comment]
It seems that Now I in Chrome I can save a new submission over the last one. But It doesn't seem to work in Firefox.

**Comment by ltegman** [comment]
Closing this as we no longer save multiple versions of a solution, only the most recent one.
