### ISSUE TITLE
Feature Request: Push Bonfire solutions to Gist

### ISSUE THREAD

**Issue by carl-parrish** [FreeCodeCamp/FreeCodeCamp#1343]
I'd like to be able to save a Bonfire solution as a Gist on github.

**Comment by BerkeleyTrue** [comment]
+1

Anyone want to tackle this?

@bugron Maybe?

**Comment by bugron** [comment]
Currently I haven't time due to my exams but I would love to give a try later if no one tackles this.

**Comment by BerkeleyTrue** [comment]
@bugron No worries. It's open for anyone who want it.

**Comment by tombarton** [comment]
Should have time in the next two weeks to take a look at this.

**Comment by BerkeleyTrue** [comment]
There is a PR open on this thanks to @bugron . Unfortunately, we can only create anonymous gist due to how the gist API works. What does the community think? Does this satisfy this issue?

**Comment by carl-parrish** [comment]
Even with oAuth? that seems odd.

**Comment by BerkeleyTrue** [comment]
@carl-parrish You are free to see the code and try your hand at it. This is an open source community, after all.

**Comment by carl-parrish** [comment]
Will do @BerkeleyTrue not saying it's not the case just it would be weird for github to do so.
