### ISSUE TITLE
Cursor/position issue.

### ISSUE THREAD

**Issue by rkdnc** [freeCodeCamp/freeCodeCamp#13434]
Not challenge specific, but when you start a new challenge, where you click in the text interpreter doesn't align where the cursor appears. You may click in one spot to begin typing, but end up a few rows down and mess up your code until you click again.

**Comment by raisedadead** [comment]
Duplicate of #7847
Workaround is mentioned here https://github.com/freeCodeCamp/freeCodeCamp/issues/7847#issuecomment-270299746
