### ISSUE TITLE
Error to try solve challenges in Microsoft Edge Mobile

### ISSUE THREAD

**Issue by glauberfc** [freeCodeCamp/freeCodeCamp#13438]
#### Increment a Number with JavaScript

https://www.freecodecamp.com/challenges/increment-a-number-with-javascript

#### Issue Description

I trying to solve challenges in my smartphone, but always that I click on backspace, for to correct a error of typing, occurs a problem, appear little red circles on the terminal and I can't to continue solving the challenge.

#### Browser Information

* Browser Name, Version: Microsoft Edge
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Mobile

**Comment by raisedadead** [comment]
We need help in reproducing and confirming the root cause of this issue. Screenshots and logs of the browser console would help.

**Comment by glauberfc** [comment]
**1 - I access the challenge and I type something on terminal.**

<img src="https://cloud.githubusercontent.com/assets/15311858/23104152/276042aa-f6a7-11e6-86a0-7d6d3de13418.png" width="300">

**2 - I delete the character that I had typed and a little red circle appear.**

<img src="https://cloud.githubusercontent.com/assets/15311858/23104169/5b7931be-f6a7-11e6-9c79-f2320766bdff.png" width="300">

**3 - I try to typing more characters and I click on backspace again and more little red circles appear.**

<img src="https://cloud.githubusercontent.com/assets/15311858/23104183/91766066-f6a7-11e6-90a6-4cc7ae59bc2f.png" width="300">

**Comment by raisedadead** [comment]
@glauberfc thanks, can you check if this is isolated to edge browser or others as well on your device?

**Comment by glauberfc** [comment]
@raisedadead, I guess that the only browser there is in Windows 10 mobile is the Edge.

**Comment by texas2010** [comment]
it seems that edge browser has an issue with code editor? but I am not sure.

**Comment by glauberfc** [comment]
The problem is only on Edge mobile.
