### ISSUE TITLE
[beta] Can't load code for challenge "Applied Visual Design: Set the Font-size for Multiple Heading Elements"

### ISSUE THREAD

**Issue by Atomk** [freeCodeCamp/freeCodeCamp#13430]
#### Challenge Name

[Applied Visual Design: Set the Font-size for Multiple Heading Elements](http://beta.freecodecamp.com/en/challenges/applied-visual-design/set-the-fontsize-for-multiple-heading-elements)

#### Issue Description

The page loads the challenge description and tests but the code editor and the small "console output" box under the buttons show an infinite loading animation. The Developer Console shows some errors, which you can see in the screenshot below.

The other challenges seems to be loaded without problems.

#### Browser Information

* Browser Name, Version: Chrome 56.0.2924.87 (64-bit)
* Operating System: Windows 7 x64
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![error](https://cloud.githubusercontent.com/assets/6122017/23096374/78380fa0-f61b-11e6-8df3-edb2926facf4.PNG)

**Comment by raisedadead** [comment]
Confirmed

![2017-02-19 01 42 56](https://cloud.githubusercontent.com/assets/1884376/23096539/f7a423e0-f644-11e6-988f-434733fa35b1.gif)

/cc @BerkeleyTrue

**Comment by Greenheart** [comment]
I've seen this exact error several times the last month.

**Comment by BerkeleyTrue** [comment]
Including the link shown in the error would be extremely helpful in debugging this.

Does moving from the previous challenge to this challenge also show the same errors?

**Comment by Atomk** [comment]
@BerkeleyTrue No, moving from the previous challenge the code in the editor is shown correctly, but the error in the console is still there. Also, reloading the page shows the same error reported in this issue.
What kind of link do you need? Is this okay?

![error](https://cloud.githubusercontent.com/assets/6122017/23107855/03ebec6c-f705-11e6-9dd1-3e1d711d0d2a.PNG)

**Comment by BerkeleyTrue** [comment]
Can anyone replicate this error in development?

**Comment by Greenheart** [comment]
@BerkeleyTrue I can reproduce with Firefox 51.0.1 (64-bit) on Ubuntu 16.04.

![1](https://cloud.githubusercontent.com/assets/6125097/23114484/9e7a4f5a-f73f-11e6-91b7-30ff5f608df1.png)
![2](https://cloud.githubusercontent.com/assets/6125097/23114485/9e801c46-f73f-11e6-87c2-83351e6c70bb.png)
![3](https://cloud.githubusercontent.com/assets/6125097/23114486/9e8259ac-f73f-11e6-8c03-3f5d4cc35298.png)
![10](https://cloud.githubusercontent.com/assets/6125097/23114487/9e83035c-f73f-11e6-9efe-c12942d29816.png)
![12](https://cloud.githubusercontent.com/assets/6125097/23114488/9e8a3686-f73f-11e6-9b3d-a3257d322d45.png)

**Comment by BerkeleyTrue** [comment]
@Greenheart is this error specific to FF?

**Comment by Greenheart** [comment]
@BerkeleyTrue I've seen this in both Chrome 55 & 56 as well as FF 50 & 51. It seems to only occur on some specific challenges. I don't see any pattern yet, but maybe these challenges are special in some way - or maybe campers load them/submit solutions in a special way that causes the bundle crash.

**Comment by Bouncey** [comment]
So a little bit of digging around whilst having a coffee at work points to the `<li>` element for the `Sign Up` nav link.

Could this be caused by the server/client markup mismatch issues we get in development? i.e. react diffs that part of the DOM and finds it isn't there, but it's still expected so it throws an error?

**Comment by Atomk** [comment]
Going from this challenge to the map page, the map "list" is not shown.
![map](https://cloud.githubusercontent.com/assets/6122017/23253363/83ecdf82-f9b4-11e6-87b5-04fcbaee3b10.PNG)

The console shows almost the same error.
![error](https://cloud.githubusercontent.com/assets/6122017/23253370/88395c96-f9b4-11e6-8739-87f29ba11070.PNG)

**Comment by Bouncey** [comment]
This was caught by the error Observable also

```
SCRIPT5022: Minified React error #32; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=32&args[]=47 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
File: bundle-42504ef8f715698a3c10.js, Line: 786, Column: 21
Error: XMLHttpRequest timeout
   {
      [functions]: ,
      @@hasInstance: undefined,
      @@isConcatSpreadable: undefined,
      @@iterator: undefined,
      @@match: undefined,
      @@replace: undefined,
      @@search: undefined,
      @@species: undefined,
      @@split: undefined,
      @@toPrimitive: undefined,
      @@toStringTag: undefined,
      @@unscopables: undefined,
      __proto__: { },
      code: "ETIMEDOUT",
      description: "XMLHttpRequest timeout",
      message: "XMLHttpRequest timeout",
      name: "Error",
      rawRequest: {
         [functions]: ,
         @@hasInstance: undefined,
         @@isConcatSpreadable: undefined,
         @@iterator: undefined,
         @@match: undefined,
         @@replace: undefined,
         @@search: undefined,
         @@species: undefined,
         @@split: undefined,
         @@toPrimitive: undefined,
         @@toStringTag: undefined,
         @@unscopables: undefined,
         __proto__: { },
         DONE: 4,
         headers: { },
         HEADERS_RECEIVED: 2,
         LOADING: 3,
         method: "GET",
         msCaching: "auto",
         onloadend: null,
         onloadstart: null,
         OPENED: 1,
         readyState: 0,
         response: "",
         responseBody: <String expected>,
         responseText: "",
         responseType: "",
         responseXML: null,
         status: 0,
         statusText: "",
         Symbol()_j.qbardueevt2: undefined,
         Symbol()_l.qbardueevt2: undefined,
         Symbol(should not be considered a local binding)_i.qbardueevt2: undefined,
         Symbol(super this bound)_k.qbardueevt2: undefined,
         Symbol(var used to be block scoped)_h.qbardueevt2: undefined,
         timeout: 0,
         UNSENT: 0,
         upload: { },
         url: "/services/user?_csrf=ska1j4NM-GPMeQBJIR24T7mxpD213t4n6a_U&returnMeta=true",
         withCredentials: false
      },
      statusCode: 0,
      Symbol()_j.qbardueevt2: undefined,
      Symbol()_l.qbardueevt2: undefined,
      Symbol(should not be considered a local binding)_i.qbardueevt2: undefined,
      Symbol(super this bound)_k.qbardueevt2: undefined,
      Symbol(var used to be block scoped)_h.qbardueevt2: undefined,
      url: "/services/user?_csrf=ska1j4NM-GPMeQBJIR24T7mxpD213t4n6a_U&returnMeta=true"
   }
```

**Comment by BerkeleyTrue** [comment]
> react diffs that part of the DOM and finds it isn't there, but it's still expected so it throws an error?


In this case react just throws away the DOM and rebuilds it. It does not throw a nebulous error.

**Comment by systimotic** [comment]
Reason for this error seems to be that the seed file was like the following:
```
"<ul>",
"<li>content</li>",
"<li>content</li>",
"</ul>"
```
React wants to put everything that is between quotes inside a paragraph, so it becomes something like
```
<ul>
  <p></p>
  <p class="wrappable" data-reactid="id"></p>
  <li>content</li>
  <p></p>
  <p class="wrappable" data-reactid="id"></p>
  <li>content</li>
</ul>
```
which it seems to thoroughly dislike.
#13618 should take care of this

**Comment by systimotic** [comment]
This should be resolved on the latest staging. Can anybody confirm?

**Comment by Greenheart** [comment]
This loads properly for me in Firefox 51 and Chrome 56.

Now the problem is that Firefox can't pass the tests since they rely on `jQuery.css()` - a known problem handled in another issue.

I think this is ready to be closed though. Thanks to everyone involved! :smile:
