### ISSUE TITLE
Feature Request: Don't auto submit Bonfires when they've passed all tests. 

### ISSUE THREAD

**Issue by carl-parrish** [FreeCodeCamp/FreeCodeCamp#1344]
Since submitted Bonfires automatically are shown on my profile (I like this btw). Perhaps adding an extra step to submit it would allow me to clean up my code before it's posted.

**Comment by webdevjeffus** [comment]
I agree. Often, the first version of my code that passes the test is NOT the version I want put on permanent display. Giving folks a chance to clean up and comment their code before saving it to their profile would be very desirable.

**Comment by BerkeleyTrue** [comment]
We are no longer displaying bonfires so this is mute.

Happy Coding.
