### ISSUE TITLE
Hex colors Orange and Raspberry not registering 

### ISSUE THREAD

**Issue by noone396** [freeCodeCamp/freeCodeCamp#13440]
Challenge [learn-about-tertiary-colors](http://beta.freecodecamp.com/en/challenges/applied-visual-design/learn-about-tertiary-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  body {
    background-color: #FFFFFF;
  }
  .orange {
    background-color: #ffa500;
  }
  .cyan {
    background-color: #00FFFF;
  }
  .raspberry {
    background-color: #E30B5D;
  }  
  div {
    height: 100px;
    width: 100px;
    margin-bottom: 5px;
  }
</style>
<div class="orange"></div>
<div class="cyan"></div>
<div class="raspberry"></div>

```

**Comment by Greenheart** [comment]
@noone396 I don't think this is an issue, you're just using other colors than what's tested for.

Try using the colors from the instructions :blush:
