### ISSUE TITLE
Your p element should contain the first few words of the provided additional kitty ipsum text.

### ISSUE THREAD

**Issue by KhalifKahin** [freeCodeCamp/freeCodeCamp#13447]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/25877762/23101197/b8f99b5c-f69e-11e6-8e75-59b04a0e5c80.png)
![freecode camp](https://cloud.githubusercontent.com/assets/25877762/23101207/e0c1d258-f69e-11e6-8740-218ef2c73178.png)

please help

**Comment by Manish-Giri** [comment]
@KhalifKahin The text was this - 
> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.

You have `Putt` instead.

For help with issues like these in future, please visit the help room (linked above).

**Comment by KhalifKahin** [comment]
thank u very much

On 19 Feb 2017 13:34, "mrugesh mohapatra" <notifications@github.com> wrote:

Closed #13447 <https://github.com/freeCodeCamp/freeCodeCamp/issues/13447>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/13447#event-968277526>,
or mute the thread
