### ISSUE TITLE
[beta] Small-Medium Breakpoint, Dropdown Menu UI issue on hover

### ISSUE THREAD

**Issue by carlosvigil** [freeCodeCamp/freeCodeCamp#13450]
#### Issue Description
Setting window to half my screen size creates a UI/UX issue when using the Menu. Essentially, it's only useable if you click and move your mouse up from underneath the menu; adding a gif for a better representation.

#### Latest 

- Safari Version 10.0.3 (12602.4.8)
- Firefox 51.0.1 (64-bit)
- Chrome Version 56.0.2924.87 (64-bit)

macOS Sierra 10.12.3 (16D32)

#### Screenshot
![fccbug](https://cloud.githubusercontent.com/assets/18217279/23105042/bd4ab940-f6a6-11e6-9875-892bae66a04e.gif)

**Comment by carlosvigil** [comment]
+ Chrome, originally only found it in the other two browsers, but it appeared after leaving the home page on chrome (when in a challenge page). Will check IEdge for consistency.

**Comment by sanatauqir** [comment]
Thank you for submitting this issue @carlosvigil. I have been able to replicate this issue on my end and will look into it.

**Comment by carlosvigil** [comment]
Thanks, I think better wording would be that the Community list snaps shut when mouse isn't hovering. A solution would be for the styling to be dependent on a tap/click to open and shut the menu items. I'd dive in the code but CSS isn't a strength yet and I'm assuming it's a style shared somewhere else too.

**Comment by cassiesouza** [comment]
If this issue has not been fixed yet I would love to help at fixing it!

**Comment by sanatauqir** [comment]
Hi Cassie,
That would be great I really have not had the opportunity to delve into it. Thanks!
Sana

**Comment by 09JDPhil** [comment]
@sanatauqir @cassiesouza  Did this issue ever get fixed? If not I'll look into it but I don't want to duplicate efforts

**Comment by antyang** [comment]
@QuincyLarson @carlosvigil Has this issue been fixed? Can't seem to duplicate this issue on my end.

**Comment by carlosvigil** [comment]
@antyang Can't reproduce either, I assume it's safe to close.
