### ISSUE TITLE
Bonfire Find the Longest String in a Word not accepting correct answer

### ISSUE THREAD

**Issue by SojournerOctocat** [FreeCodeCamp/freecodecamp#1345]
The following code doesn't pass the `May the force be with you` test. Result says `expect(findLongestWord('May the force be with you')).to.equal(5);expected 6 to equal 5`

```
var numLongestWord = 0;

function findLongestWord(str) {
  var strArray = str.split(' ');
  for (var word in strArray){
      if (numLongestWord < strArray[word].length) {
          numLongestWord = strArray[word].length;
      }
  }
  return numLongestWord;
}

findLongestWord('The quick brown fox jumped over the lazy dog');
```

**Comment by davidkwan95** [comment]
The code doesn't pass the test because `var numLongestWord = 0` is outside the function.

**Comment by SojournerOctocat** [comment]
Oh. I didn't know that everything had to be inside the function. Thanks for the tip. I moved the line inside the function and that worked.

**Comment by davidkwan95** [comment]
Have you read about variable scope already? Your mistake occurred because the var is in global scope and doesn't reset back to 0 every time the function is called. So it's not about having to put all of your code inside the function

**Comment by royshouvik** [comment]
Hi @SojournerOctocat Consider closing this issue, if it's resolved. Thanks.

**Comment by SojournerOctocat** [comment]
Thanks for the explanation. I thought that the global var would reset each time the code was called.
