### ISSUE TITLE
myVar++; is not accepted, is my code correct?

### ISSUE THREAD

**Issue by AdannaGithub** [freeCodeCamp/freeCodeCamp#13451]
Challenge [increment-a-number-with-javascript](https://beta.freecodecamp.com/en/challenges/basic-javascript/increment-a-number-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var myVar = 87;

// Only change code below this line
myVar++;


```

**Comment by raisedadead** [comment]
The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!

**Comment by X-T-G** [comment]
this is my code,and i have passed this course,just like this :
var myVar = 87;

// Only change code below this line
myVar ++;
var myVar;
