### ISSUE TITLE
How Fonts Should Degrade Instructions Unclear

### ISSUE THREAD

**Issue by CyanCool** [freeCodeCamp/freeCodeCamp#13457]
#### Challenge Name

[Specify How Fonts Should Degrade](https://www.freecodecamp.com/challenges/specify-how-fonts-should-degrade#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20%3C!--font-family%3A%20Lobster%2C%20Monospace%3B--%3E%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by cdrainxv** [comment]
@CyanCool: The instructions say to comment out your call to the google web font. You made that call by including the `<link>` element at the top of your code in the previous challenge. Now comment out the google web font **link**.

Note: This page is for only posting issues. Challenge related questions should be asked in the [help](https://gitter.im/FreeCodeCamp/Help) room. Thanks!

**Comment by wanderlust22** [comment]
Hey, I had the same problem as you. I think the test is just wrong. When you comment out the google font LINK, as the directions tell you, it doesn't pass. 

After looking through another post, I did what they did and commented out the h2. So -- 
 

Again, I'm brand new to this but it doesn't make sense to me. I think it's a bug. Anyway, do what I did and you can move on to the next lesson!

**Comment by erictleung** [comment]
@CyanCool thanks for the issue. I think the instructions are sufficient, but I can see why you wrote your code as you did.

Just strictly looking at the example code, you might think to just mess around with the CSS rules, which is incorrect for this challenge.

What we might want to do is to reword the last sentence of the challenge to something like this:

 > In the last challenge, you've imported the `Lobster` font family using the `<link>` tag. Now comment out that import of the `Lobster` font from Google Fonts so that it isn't available anymore. Notice how your `<h2>` element degrades to the `Monospace` font.

**Comment by Manish-Giri** [comment]
@erictleung I'll take this up...

**Comment by Greenheart** [comment]
@erictleung @Manish-Giri Note that this description was recently [changed in staging](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/basic-css.json#L809-L817) (this issue refers to the main site)

**Comment by erictleung** [comment]
@Greenheart thanks for pointing that out! I think my suggestion still applies. The confusion stems a little because of the example code and maybe the potentially vague instruction of "your call to Google Fonts". So specifying that your "call to Google Fonts" was the `<link>` tag, I think that will help clear up some confusion.

**Comment by Greenheart** [comment]
@erictleung @Manish-Giri Let's combine them and see what's best :blush:
