### ISSUE TITLE
Learn How a Stack Works Insufficient Tests

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/freeCodeCamp#13459]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/learn-how-a-stack-works

#### Issue Description

The challenge tests are insufficient and can be passed with incorrect code. The code shown below can pass the challenge but it doesn't use any of the JavaScript methods to complete the challenge.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: macOS
* Mobile, Desktop, or Tablet: Laptop 

#### Code

```js
var homeworkStack = ['BIO12','HIS80','MAT122','PSY44'];
// Only change code below this line
homeworkStack = ['BIO12', 'HIS80','MAT122', 'CS50'];
```

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/2754821/23110029/d8bab6c2-f6d2-11e6-8802-cc1c4268747a.png)

**Comment by Manish-Giri** [comment]
I'll take this up...

**Comment by erictleung** [comment]
@Manish-Giri just fyi, I've made some changes with the stack challenge with [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/13343), which might affect changes necessary in this issue. So you might want to wait until my PR is merged before working on this.

**Comment by Manish-Giri** [comment]
@erictleung sure thing, I'll work on other PRs until then! Thx for the heads up!

**Comment by Greenheart** [comment]
**Originally from a comment on #13343:**

This still allows the challenge to be passed

```js
var homeworkStack = ["BIO12","HIS80","MAT122","PSY44"];
// Only change code below this line

homeworkStack = ['BIO12', 'HIS80', 'MAT122', 'CS50'];
```

I see two approaches to making the tests more robust:
1. Use a regex to verify that the first line of the challengeSeed is intact, and that the `code` only contains one instance of the `=` character. **This is probably the best method**.
2. Alternatively we can verify that the array methods have actually been used.

**Comment by Greenheart** [comment]
@erictleung @Manish-Giri I could submit a fix for this right away.
