### ISSUE TITLE
[beta] Progress lost on beta.freeCodeCamp.com

### ISSUE THREAD

**Issue by kujjwal02** [freeCodeCamp/freeCodeCamp#13462]
##### in beta.freecodecamp.com
completed the Basic HTML and HTML5 section
but when I came back again all the progress was lost and browny points was set to 1

#### Browser Information

* Google chrome, Version: 56.0.2924.87 (64-bit)
* Operating System: Windows 10 
* Mobile, Desktop, or Tablet:

**Comment by raisedadead** [comment]
@kujjwal02 

- Were you logged in to freeCodeCamp when you solved the challenges earlier?
- If yes, then was it the same account that you are logged in?

I can see that you have 273 points in your profile, as of this comment.
https://www.freecodecamp.com/kujjwal02

![screenshot-www freecodecamp com-2017-02-20-18-55-28](https://cloud.githubusercontent.com/assets/1884376/23126755/451872de-f79e-11e6-944a-bbf52d92323b.png)

Can you double check?

**Comment by kujjwal02** [comment]
@raisedadead 
The main website of freecodecamp is fine

i was reporting the issue about 
### beta.freecodecamp.com

**Comment by raisedadead** [comment]
>- Were you logged in to freeCodeCamp when you solved the challenges earlier?
>- If yes, then was it the same account that you are logged in?

**Comment by kujjwal02** [comment]
- yes I was logged in to freeCodecamp when I was solving the challenges
- and it was the same account

**Comment by raisedadead** [comment]
Okay, can you guide a bit more on the exact steps to reproduce this? You completed the  Basic HTML and HTML5 section, and moving on to the next challenge caused this, or this happened after a few days, etc?

When did you complete the last challenge?
Any additional information that you have to reproduce this would be appreciated.

Thanks.

**Comment by kujjwal02** [comment]
@raisedadead 
Okay,
1. After completing the  Basic HTML and HTML5 section I decided to check my account settings
2. In settings,  Email section was saying that my email address in not linked
3. So I decided to link my email.
4. After submitting the form I got an email from freecodecamp for verification
5. On clicking the verification link I was redirected to the main site of freecodecamp ie [https://www.freecodecamp.com](https://www.freecodecamp.com) instead  of the beta site [http://beta.freecodecamp.com](http://beta.freecodecamp.com)
6. and I got an error message "Oops, something went wrong, please try again later" on [https://www.freecodecamp.com](https://www.freecodecamp.com)
7. When I came back to the beta site i.e [http://beta.freecodecamp.com](http://beta.freecodecamp.com) there the email setting section of the setting page my email address was already linked
8. And I noticed that I had only 1 brownie point
9. When I checked my public profile I found out that all my solved challenges were wiped out completely.

**Comment by raisedadead** [comment]
@kujjwal02 Thanks. 

This greatly helps me understand the issue.

Apologies, that I cannot guarantee a recovery of your account's progress on the beta website, because, as you know its a unstable branch.

Will try my best, and update you on this as soon as we can.

**Comment by Cheayo** [comment]
I just had something similar happen, except I didn't get the email until after, so I don't think it's caused by following the link per se.

After submitting the form, I saw that it still said I didn't have an email address linked, so I tried the process again, except this time instead of a "we'll email you" message, I got "something went wrong". At that point my brownie points were erased.

**Comment by freecodecampns** [comment]
I have the same problem. Actually I cannot even log in to beta.freecodecamp.com. Therefore all my progress is gone. Can anyone help? it seems to have been a waste of time doing all these challenges. Thank you .

**Comment by raisedadead** [comment]
This is probably something that's known and should be determined once we have the uniqueness checks in place that #15205 aims to resolve along with some of the refactoring that @BerkeleyTrue is currently working on.
