### ISSUE TITLE
Typo in challenge code: calulateCircumference 

### ISSUE THREAD

**Issue by gogolab** [freeCodeCamp/freeCodeCamp#13464]
Challenge [use-the-const-keyword](http://beta.freecodecamp.com/en/challenges/es6/use-the-const-keyword) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

There is typo in "calulateCircumference" - should be "calculateCircumference".

```js


// change 'var' to 'let' or 'const'
// rename constant variables
var pi = 3.14;
var radius = 10;
var calulateCircumference = function(r) {
  var diameter = 2 * r;
  var result = pi * diameter;
  return result;
};
// Test your code
console.log(calulateCircumference(radius));

```

**Comment by JosephLivengood** [comment]
Do you want to take this fix?

**Comment by OFFLlNE** [comment]
@gogolab Thank you for reporting the issue.
I did not find any duplicates on this.

Guess up for grabs ;)

**Comment by OFFLlNE** [comment]
@JosephLivengood I think you can take this if you want or let some1 else take it

**Comment by JosephLivengood** [comment]
@OFFLlNE I'm all for a first-timers-only, we both were labeling and commenting at once it seems like! :+1:

**Comment by griffste** [comment]
Hello, I am a student looking to make my first contribution to an open source project. Is this issue available to fix still? Would someone be able to walk me through what I need to do to resolve the issue?

Thank you,
Steve

**Comment by JosephLivengood** [comment]
@griffste All yours! You can look at how to contribute [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md). If you run into trouble feel free to join us on [gitter for help](https://gitter.im/FreeCodeCamp/Contributors)!

Happy Coding! :1st_place_medal:
