### ISSUE TITLE
Design the hint button and functionality

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#13460]
We've talked about creating a hint button that will pop up a hint.

There are a few questions we must first answer:
- do we want to allow for several hints? Where each time a button is clicked, a progressively more explicit hint is revealed? Or do we just want one good hint per challenge?
- do we want to use the toast system, or just reveal the hint below the challenge description, where it can be more conveniently studied, kind of like this: http://codepen.io/oloman/pen/odnqy
- keep in mind that these hints may be long or large blocks of code, so it would be nice to be able to style them with HTML like we can the challenge description.

**Comment by Greenheart** [comment]
I think we should leave the basic challenge framework so open as possible to allow different kinds of challenges to teach in slightly different ways (while of course still using a similar format).

I suggest we allow multiple hints, by using an array of JSON-strings similar to how the challenge `description` is stored. I like the idea of having formatting options for the hints as formatted names or code examples sometimes could convey more value than a toaster. If we want to display formatted hints it would probably make sense to add them just below the instructions.

A bonus for this solutions would be that the rendering code for this basically could be the same as what's rendering the description. So it wouldn't be too hard to implement either.

**Comment by Atomk** [comment]
Have you also discussed about how to make the hint feature not-so-tempting? I understand sometimes it is easy to get discouraged in front of a challenging problem, but an abuse of the hint feature kills the learning that happens when you try your best to solve a problem.

**Comment by OFFLlNE** [comment]
Maybe it would be possible to add a cooldown to hint button? If an user presses it, then the user has a cooldown to ALL hint buttons for like 10-30 minutes

**Comment by nawazishali** [comment]
I think some thing similar to Codeacademy.com can be done, They show the hint just below the problem description/Detail. But I like the current style of FCC much more then Codeacademy cause it forces me to learn on my own. There should be some kind of penalty system if a user uses a Hint in a problem, i.e one hint per day should be allowed or something like @OFFLlNE  suggested. Users should be discouraged to use the hint. 

Or alternatively hint can be a link to some other resource explaining how the problem should be approached.

**Comment by QuincyLarson** [comment]
@nawazishali Thanks for your feedback. Instead of penalizing the user, we could fire a JavaScript notification that a hint was used, and track which challenges people need to use the hints on the most, and see if we can refine those challenges. I don't think we should penalize campers. Alternatively, we could make the hint time-unlocked. 

If the camper spends more than 2 minutes working on a challenge, the hint button could become enabled. Of course, if they're clever they could just dig into the console and get the hint immediately. We wouldn't consider that cheating, but the additional effort would sort of automatically discourage this :)

The reason I say this is we want for all the interactions to be as positive as possible - carrots instead of sticks. So we don't want to penalize or discourage campers in any way.

What do you think?

**Comment by Marmiz** [comment]
If I can spare my two cents, I don't really like the "timing" approach.

It reminds me of those free-to-play pay-to-win games, where you have to wait for a certain time to have an important item to be available again... unless you pay to have it now.

I'm sure that, as an open source, we don't want to give the impression that we hold information.
Moreover, let's be honest, if a camper would want a straight answer it could just ask for it in chat or Google it.


So in my humble opinion the best kind of hint would be something that helps the camper in getting started in the right direction.
Which is something that, honestly, we do at work as well.
If stuck I often ask some coworker/senior how they would proceed to tackle the problem, to have at least a starting point; which I believe sometimes is the hardest part to do: starting.

So for example in a JS challenge a hint could be:
> HINT 1:why don't you start by looping into the array and extract the value into a new variable scoped into the function?
HINT2: have you checked *insert useful methods here*, it may help you *example:* dividing the string into single character

In doing so we can also have a common method on writing those hint as consistent as possible,
and still leaving the camper the possibility to ask in chat if those guidance haven't been helpful.

**Comment by nawazishali** [comment]
@QuincyLarson I agree that penalizing could have a negative impact on the user but instead of time limitation we can have a quiz type of question related to the exercise so that the user first needs to search out on internet to get the knowledge required to unlock the Hint/Solution, This way we can push the user to get at least some knowledge about that particular exercise before he gets to the solution. 

But I think it's gonna take lots of time to build such type of system as we will need to first decide what questions need to be asked that are relevant to the exercise. And yeah with this quiz system we can allow the user to directly see the solution instead of just providing a hint.

What do you Say?

**Comment by QuincyLarson** [comment]
@nawazishali that is a novel idea, and I like the fact that it pushes the learner to seek out information to unlock the hint. This said, you are right - this would be difficult to execute properly, and may just end up making the user experience frustrating.

I agree with @Marmiz that the timed unlock thing could become frustrating. We've made every other aspect of fCC completely accessible. People can jump around between challenges. They don't even need an account. They can even get working solutions from our wiki. Why should we hold back the hints from them? 

So I propose we have a hint button, and when clicked, it gives the first hint. As simple as that. The question remaining is, how should we display that hint? Should we have it appear below the lesson?

This is a crude drawing, but basically at the bottom of the challenge instructions, a regular looking link that when clicked pushes everything below it down to make room for the hint.

https://www.evernote.com/l/Ar_CDadzMpJG7anyJtbnTjdsPM0Yw-HG4CQB/image.png

**Comment by Marmiz** [comment]
@QuincyLarson just came home and started working on a simple demo on my local copy; at least to have some initial screenshot/visuals on how it may looks like.

Hope to have it ready soon<sup>tm</sup>!

**Comment by QuincyLarson** [comment]
@MAF27 Awesome - I'll look forward to seeing it :)

**Comment by Marmiz** [comment]
Sorry that took me so long, a cold found me with my guard down 😄 

I started with the easiest approach here:
I've designed a new component for the `Hint` button, so far it toggles the visibility of a child component that handle the rendering of the hint text.

My idea was to split the concern so that: we can add any features to the button (eg: open in a modal / add analytics ..) and let the Children handle fetching the data from the `seeds` and rendering on the page like the rest of the test: here's how it looks:
![fcc-hint 2017-03-03 22 49 13](https://cloud.githubusercontent.com/assets/16669241/23557761/b024390a-0063-11e7-9cbf-e076109ff104.png)

**Comment by Greenheart** [comment]
@Marmiz Nice work! I like the separation of concerns.

Perhaps the `HintButton` could allow multiple triggers (Analytics, modal and more) by accepting a callback function fired `onClick` where the consumer can decide what to do? :blush:

**Comment by dhcodes** [comment]
Adding to this issue thread that as part of the hint redesign, MDN links need to be migrated from backup/staging to staging.

**Comment by QuincyLarson** [comment]
Instead of building a hint system and adding hints for every challenge, it would be easier to link people the the Guide article that corresponds to the challenge (if there is one). Currently these are up on https://forum.freecodecamp.com/c/guide and we'll soon have them up on freecodecamp.com/guide/[guide URL]

Once these are live, we can go through and add a "guide" link to each of the challenges in the seed file, or better yet come up with a way of parsing the challenge name so we don't have to hard code these links.
