### ISSUE TITLE
[beta] Color property already covered in another challenge

### ISSUE THREAD

**Issue by Atomk** [freeCodeCamp/freeCodeCamp#13463]
Challenge [adjust-the-color-of-an-anchor-tag](http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-color-of-an-anchor-tag) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.

The color property was already covered in [this challenge](http://beta.freecodecamp.com/en/challenges/basic-css/change-the-color-of-text) in the Basic CSS section. The description specifies that the property can be applied to every element, we could say that's what you learn from the challenge but it looks too little. I'd suggest adding more information or delete the challenge.

**Comment by Greenheart** [comment]
@Atomk Thanks for reporting this!

/cc @HKuz

**Comment by HKuz** [comment]
@Greenheart thanks for tagging me on this, I'm slowly working through my backlog of issues 😅 

As @Atomk pointed out, this challenge isn't really introducing a new concept (`color` was taught in the CSS section), and it's not adding much more info. I think we can safely remove it after editing the following challenge "Adjust the Hover State of an Anchor Tag". Here are some suggestions for the changes in that challenge:

The second paragraph:

>For example, the styling of an anchor tag can be changed for its hover state using the `:hover` pseudo-class selector. Here's the CSS to change the color of the anchor tag to red during its hover state:

And the instructions part:

>The code editor has a CSS rule to style all `a` tags black. Add a rule so that when the user hovers over the `a` tag, the `color` is blue.

For fellow contributors who want to work on this, please refer to the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) and ask any questions in the [Contributors Chat Room](https://gitter.im/FreeCodeCamp/Contributors). Thank you!  💻 ⌨️ :1st_place_medal:

**Comment by Manish-Giri** [comment]
I'll take this up!

**Comment by HKuz** [comment]
All yours, @Manish-Giri - thank you!!
