### ISSUE TITLE
[beta] Improve challenge "Applied Visual Design: Adjust the Hover State of an Anchor Tag"

### ISSUE THREAD

**Issue by Atomk** [freeCodeCamp/freeCodeCamp#13468]
Challenge [adjust-the-hover-state-of-an-anchor-tag](http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-hover-state-of-an-anchor-tag) has an issue.

I think this challenge should be changed, I'll list some reasons:
- Right now the challenge shows two new concepts, hover and text-decoration: none, when the overall teaching style is one concept per challenge
- Here pseudo-classes are introduced for the first time in the curriculum, I think the description is too concise and could leave a beginner with a lot of doubts.
- There is not an example showing how to use :hover with a selector.

My suggestion:
- Split the challenge in two, one for hover, one for text-transform: none.
- Enhance the description, including a practical example.

**Comment by Greenheart** [comment]
@Atomk I agree. These concepts could use more thorough explanations and examples.

Would you like to make these changes and make a contribution? :blush:

**Comment by Atomk** [comment]
I'll try as soon as I manage to run FCC locally to test another contribution I'm working on, which with some patience and luck should happen today :+1:

**Comment by Greenheart** [comment]
@Atomk Thanks, that would be awesome! As always, leave a message in the contributors chat room if you have any trouble :blush:

**Comment by hay-dee** [comment]
hi @Atomk can i work on this issue with you? I can make the below changes to the hover challenge:

- remove text-decoration concept
- Add description on pseudo-classes
- Insert example with :hover selector

**Comment by Atomk** [comment]
@hay-dee Sorry for the delay in my response, of course you can work on it. To be honest these days I'm very busy so I don't know how much I can contribute.

**Comment by hay-dee** [comment]
@Atomk hey no worries, thanks for your understanding. I can try to work on the remaining pointers raised in order to close this issue.

@Greenheart Is there a guide/reference available on how to add a new challenge page (for text-decoration) to the freeCodeCamp client?

**Comment by Atomk** [comment]
Little proposal for the text-decoration challenge:
"By default, the links created with the `<a>` tag are underlined. You can remove all the text decorations from of an element using `text-decoration: none;`."
The goal would be to remove the underline from the link. I don't think my choice of words is the best so feel free to improve!

**Comment by Greenheart** [comment]
@Atomk Thanks for your help with this! A big part of contributing is actually about discussing ideas here on GitHub. I like to think of it as a big forum of interesting people whom I can learn from :smile:

@hay-dee Actually, there is a document about how we aim to structure challenges! [freeCodeCamp's Challenge Style Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenge-style-guide.md)

To add a new challenge, add a JSON-formatted object to the seed file of the section. Each section is basically an array of JSON-objects - one for each challenge. [This is the challenge](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/applied-visual-design.json#L1160-L1191) in this case.

However, I'm not sure what specific fields that should be added. I think you can look at how other challenges are formatted and base yours on them. Ask in the [contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) for specific details.

Good luck and happy coding! :blush:

**Comment by hay-dee** [comment]
@Greenheart many thanks for the guide! I did not realise that it was linked in the contributing file at the end.
