### ISSUE TITLE
isn't this the way to write in html??

### ISSUE THREAD

**Issue by bappyasif** [freeCodeCamp/freeCodeCamp#13465]
Each of your two radio button elements should be nested in its own label element...
isn't this the way to write??

`<form action="/submit-cat-photo">
  <input type="text" placeholder="cat photo URL" required>
  <label><input type="radio" name="indoor-outdoor"> Indoor <input type="radio" name="indoor-outdoor"> Outdoor </label>`
```

**Comment by texas2010** [comment]
@bappyasif 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
