### ISSUE TITLE
Accessing Nested Objects Suggestion

### ISSUE THREAD

**Issue by Kalinaki** [freeCodeCamp/freeCodeCamp#13472]
```// Setup
var myStorage = {
  "car": {
    "inside": {
      "glove box": "maps",
      "passenger seat": "crumbs"
     },
    "outside": {
      "trunk": "jack"
    }
  }
};

// Only change code below this line

var gloveBoxContents = "" ; // Change this line
```

Hello, I'm quite new to programming but I thought it's a good idea to grow a pair and learn go to give feedback(and receive as well).

I completed this challenge but my issue with it is that it can be confusing.
The element that is a bit confusing and misleading is the "" notation after var gloveBoxContents =.
Although if a camper remembers the previous lessons when searching through objects i'm sure there won't be much of an issue.
My overall impression was that I had to write a completely new line above the var gloveBoxContents.

My issue is more in regards to clarity.

I hope I was helpful.

One peace.

**Comment by Kalinaki** [comment]
Hi,

Sorry for the missunderstanding.

**Comment by Greenheart** [comment]
@Kalinaki Thanks for reporting this!

Don't worry about the bot, we haven't teached it good manners yet... :smile:

Do you have any suggestions for how the line could be clearer?
Perhaps any of the following examples?

(Imagine the comment after as well)
```js
var gloveBox = undefined;

var gloveBox;
```

**Comment by Kalinaki** [comment]
The line 
// Only change code below this line. 
could be removed.
Also, your suggestion
var gloveBox = undefined;
appears better.
To finish this exact  challenge you need to use the .notation and []notation so having the '''' can be confusing.
But then again...I suppose you wouldn't want to oversimplify things.
I take it the purpose of the challenge is to teach the camper basic concepts.
Anyways, that's pretty much my input on the matter.

One peace.

**Comment by Greenheart** [comment]
@Kalinaki Thanks for your feedback! How about removing the comment `// Change this line` instead? It could make the code cleaner.

I agree, `undefined` is a better value than `""`. 

As you reported this, would you like to make an open source contribution and fix this? Me and other contributors would be happy to guide you through the process! :blush:

[CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) could help you set up your local environment.

Once you're ready, [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L4759) is what would need an update:

* Let's set the default value to `undefined`
* Let's remove the comment at the end of it.

If you have any questions, feel free to to come chat with us in the [Contributors](https://gitter.im/FreeCodeCamp/Contributors) chat room. We're here to help!

Happy coding! :smile:

**Comment by Kalinaki** [comment]
I will be happy to.

**Comment by Kalinaki** [comment]
I checked all the requirements and I think I'm a bit green for such task at
this point in time. However, I'm working on improving my knowledge and I
hope there is no time frame for applying the code changes.

One peace.

**Comment by Greenheart** [comment]
@Kalinaki It's a pretty complicated process. I know exactly what you're talking about!
 
We would be happy to help you through every step if you want to give it a try!

But if you really want to, I could open this to other contributors.

Two pieces :wink:

**Comment by Kalinaki** [comment]
I will go to the contributions forums and try to figure it out.
I will inform if I wont be able to do it at this point in time.

**Comment by Kalinaki** [comment]
Nope, I don't think I can handle it. Better to assign it to someone else.

Sorry. :(

**Comment by Greenheart** [comment]
@Kalinaki Ok, no problem! Feel free to reach out if you'd like to help out in the future - as you may see, there's a lot of activity in this project and plenty of room to make first contributions :)

Good luck, and happy coding!

**Comment by Manish-Giri** [comment]
@Greenheart May I do this? 😄

**Comment by Greenheart** [comment]
@Manish-Giri Sure! :blush:
