### ISSUE TITLE
Bonfire Make a person - test case leading to bad practice/solution

### ISSUE THREAD

**Issue by ericdouglas** [FreeCodeCamp/freecodecamp#1347]
The first assertion `'should return 6 keys'` lead us to have to create all methods of `Person` using `this.method` inside the Person constructor, but this is a bad practice because whenever we create an instance of Person, all those function will be recreated.

The correct thing in that case is to attach the methods to `Person.prototype`.

You should consider remove just that assertion.

:smile:

**Comment by BerkeleyTrue** [comment]
yes, this bonfire has given us issues in the past. https://github.com/FreeCodeCamp/freecodecamp/issues/877

The main problem is not really that assertion. It's that the original intent of that bonfire was to teach closures, not prototype methods and instantiation. That assertion is there to ensure the camper has assigned the instance methods to the object but not the instance properties.

But there is confusion around this bonfire. Some changes need to be made.

**Comment by PWAckerman** [comment]
From an instructional design standpoint, it is very confusing, as the constructor paradigm in this Bonfire seems to be different than what is espoused in the immediately preceding Udacity course.

**Comment by royshouvik** [comment]
Same issue

**Comment by BerkeleyTrue** [comment]
closing in favor of #881
