### ISSUE TITLE
[beta] Duplicated Google Font challenge

### ISSUE THREAD

**Issue by Atomk** [freeCodeCamp/freeCodeCamp#13471]
Challenge [use-a-google-font](http://beta.freecodecamp.com/en/challenges/applied-visual-design/use-a-google-font) has an issue.

Similarly to #13463, there are two versions of this challenge, one in [Basic CSS](http://beta.freecodecamp.com/en/challenges/basic-css/import-a-google-font) (the original one) and one in [Applied visual design](http://beta.freecodecamp.com/en/challenges/applied-visual-design/use-a-google-font) (this one was added with the new curriculum).

Actually both have a good description, I think the best thing would be to merge the two challenges to have only one on the subject, rather than just deleting one.

**Comment by Greenheart** [comment]
@Atomk Nice catch!

This is likely an artifact from the curriculum expansion.

/cc @HKuz

**Comment by HKuz** [comment]
Thanks for flagging this for me @Greenheart. @Atomk - yes, there will be some overlap with the new curriculum and the original challenges, and we welcome folks pointing out where we can clean this up. I think your idea to blend the two Google Font ones so we only cover the concept once, in one challenge, is a good idea. We can combine the points from both so no info is lost. I can take a crack at editing the original to include info covered in the new one 👍
