### ISSUE TITLE
Mutations (Basic Algorithms) - Incorrect test case

### ISSUE THREAD

**Issue by gminovska** [freeCodeCamp/freeCodeCamp#13482]
The challenge description states: Return true if the string in the first element of the array contains **all** of the letters of the string in the second element of the array.

According to that the case: `mutation(["Mary",` `"Aarmy"])` should return **false** because the first string has only one a character, therefore does not contain all of the characters of the second string.
Currently that test case returns **true**.

**Comment by donofriov** [comment]
That's a good point, the first string does not contain a second "a". Should the challenge be updated to work with duplicate characters or should the description be updated to note to ignore duplicates?

**Comment by gminovska** [comment]
Ignoring duplicates makes the challenge easier, which might be the right thing to do since it is a basic algorithm challenge.

**Comment by donofriov** [comment]
I agree! If updating instructions is the route the members want us to go then I think it would make the most sense to just remove `mutation(["Mary", "Aarmy"])` from the acceptance criteria. This way there won't be any confusion. If it's left in, then I would assume I would have to solve for this use case. As you said it's more a beginner challenge so may add some unwanted complexity to deal with duplicates at this level.

**Comment by gminovska** [comment]
I think you are right, that is the best and easiest solution!

**Comment by erictleung** [comment]
@gminovska @donofriov I would argue that this test is okay. This challenge could also be rephrased to "check if the second string is a subset of the characters in the first string," in which case "Aarmy" has all the letters found in "Mary". Thus, this returns true. 

This insight comes from the last example in the description

> Lastly, `["Alien", "line"]`, should return true because all of the letters in "line" are present in "Alien".

At the very least, there can be some clarification in the instructions.

**Comment by gminovska** [comment]
@erictleung [A,a,r,m,y] is **not** a subset of [M,a,r,y] because it has one "a" character that is not present in the superset . However, [M,a,r,y] **is** a subset of [A,a,r,m,y] because it has all the characters that are in the superset. As it is, the test case is incorrect. If you think it should not be removed, then it should have the string 1 and string 2 switched, so ["Aarmy", "Mary"] returns true.

**Comment by donofriov** [comment]
@erictleung well I do agree that the test is okay, I don't necessarily think that phrasing clarifies it. A subset generally means that all of the second string would be in the first one, which brings us back to Aarmy not fitting into Mary but line still working for Alien.
