### ISSUE TITLE
I am stuck :<

### ISSUE THREAD

**Issue by brandonevansmgmt** [freeCodeCamp/freeCodeCamp#13485]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%3C%2Fstyle%3E%0A%20%3Ch2%3E%20%7Bcolor%3A%20blue%3B%20CatPhotoApp%7D%0A%20%20%20%20%20%20%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
</style>
 <h2> {color: blue; CatPhotoApp}
      



```

**Comment by texas2010** [comment]
@brandonevansmgmt 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help. 
GitHub Issues are for reporting bugs on the website only. 

Happy Coding.
