### ISSUE TITLE
Bonfire: Find the longest word, not working for 'May the force be with you'

### ISSUE THREAD

**Issue by sclobo** [FreeCodeCamp/freecodecamp#1348]
![image](https://cloud.githubusercontent.com/assets/13368369/8803586/a3f4a20a-2f95-11e5-8858-3a5d10b7bd4b.png)

**Comment by sclobo** [comment]
My test case was just checking, for the 3rd word it seems like it never picks it as the longest. I tried 'the poe browntest chick' and it selected 'chick' as the longest word and not 'browntest'

**Comment by royshouvik** [comment]
Hi, would it be possible for you to paste your code as text rather than images. Try using Markdown syntax for code. You have to use \`\`\` and add a new line before your code, then add a new line and another \`\`\`.
```
your code
```
Thank you!

**Comment by sclobo** [comment]
```
function findLongestWord(str) {
  var arrayStr = str.split(/\s/);
  console.log(arrayStr.length);
  var maxStr;
  var num = 0;
  for(var i=0; i < arrayStr.length; i++)
    {
      console.log(i);
      if(arrayStr[i].length > num)
        {
          maxStr = arrayStr[i];
          num = arrayStr[i].length;
          
        }
      else
        {
          i++;
          
        }
    }
  return num;
}

findLongestWord('ther poe brownt');
```

**Comment by sclobo** [comment]
```
function findLongestWord(str) {
  var arrayStr = str.split(/\s/);
  var maxStr;
  var num = 0;
  for(var i=0; i < arrayStr.length; i++)
    {
      if(arrayStr[i].length > num)
        {
          maxStr = arrayStr[i];
          num = arrayStr[i].length;
          
        }
      else
        {
          i++;
          
        }
    }
  return num;
}

findLongestWord('ther poe brownt');
```

**Comment by royshouvik** [comment]
No need to increment ```i``` on the ```else``` clause, as ```for``` loop will automatically increment ```i``` after each iteration.

**Comment by sclobo** [comment]
oh lol silly me :+1: Thanks for the help!

**Comment by royshouvik** [comment]
Consider closing this issue if it's working fine for you.
