### ISSUE TITLE
Cursor placement bug

### ISSUE THREAD

**Issue by Tony-Thomas** [freeCodeCamp/freeCodeCamp#13488]
Hi, I am having issued placing my cursor in desired location within the embedded text editor. I am using google chrome, and the only way this seems to fix itself is if i restart my entire computer. Shutting down browser and reopening does not resolve the issue. 

Challenge [Create a Text Field](https://www.freecodecamp.com/challenges/create-a-text-field) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>

```

**Comment by Tony-Thomas** [comment]
Resetting my code just worked. I will keep you posted on this bug as i progress through the tutorials.

**Comment by Tony-Thomas** [comment]
Resetting my code appears to be working, but every time i advance to the next lesson the cursor bug resurfaces.

**Comment by erictleung** [comment]
@Tony-Thomas thanks for the issue. This is unfortunately a known bug https://github.com/freeCodeCamp/freeCodeCamp/issues/7847. Take a look at the thread of comments for some solutions for this bug. So closing as duplicate. Happy coding!
