### ISSUE TITLE
"Refused to load the font" errors populates console

### ISSUE THREAD

**Issue by donniereese** [FreeCodeCamp/FreeCodeCamp#1349]
When using the Chrome console to debug bonfires with console.log, I noticed that 4 or 5 large errors populated the console at page load about refusing to load fonts from various sources:

* bonfire-inventory-update:1 ( x6 )
* frame.html:1 ( x3 )

These errors also reappear every time you click "Run Code".

### Example
```
Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAIt0ABEAAAABQDwAAQABAAAAAAAAAAAAAAAAAAAAA
CwKGBmIIpVWLACJWGwAUVjI2KwAiNEswkKAwIrswsQAwIrsxEWAwIrWbIEKA
ZFUkSzCxAEAisA' because it violates the following Content Security 
Policy directive: "font-src *.googleapis.com 'self' blob: 
*.freecodecamp.com http://www.freecodecamp.com 
ws://freecodecamp.com/ ws://www.freecodecamp.com/ *.gstatic.com 
*.google-analytics.com *.googleapis.com *.google.com *.gstatic.com 
*.doubleclick.net *.twitter.com *.twitch.tv *.twimg.com 
'unsafe-eval' 'unsafe-inline' *.bootstrapcdn.com *.cloudflare.com https://*.cloudflare.com localhost:3001 ws://localhost:3001/ 
http://localhost:3001 localhost:3000 ws://localhost:3000/ 
http://localhost:3000 *.ionicframework.com 
https://syndication.twitter.com *.youtube.com *.jsdelivr.net 
https://*.jsdelivr.net *.ytimg.com *.bitly.com http://cdn.inspectlet.com/ wss://inspectletws.herokuapp.com/ http://hn.inspectlet.com/".
```

#### Additionally:

I get another error that may or may not be related: 
```
Uncaught TypeError: Cannot read property 'type' of undefined
pluginWeb.js:20
```

**Comment by benschenker** [comment]
Closing as stale, if this is still an issue for you please reopen

**Comment by shroudedcode** [comment]
@donniereese @benschenker I just wanted to open another issue about this, because I experience exactly the same thing. My console gets flooded with errors like this:

![image](https://user-images.githubusercontent.com/29176678/32979245-cd57d33c-cc51-11e7-810a-2a0ebbf3319e.png)

**Comment by kunalbrainium** [comment]
I have the same issue as @shroudedcode
