### ISSUE TITLE
[Beta] ES6 Write Arrow Functions const test should fail.

### ISSUE THREAD

**Issue by benschac** [freeCodeCamp/freeCodeCamp#13495]
#### Write Arrow Functions
http://beta.freecodecamp.com/en/challenges/es6/write-arrow-functions

#### Issue Description

```

// change code below this line
var magic = () => {
  return new Date();
};
// change code above this line
// test your code
console.log(magic());
```
should fail
`Test magic is const`

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Mac
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```

**Comment by benschac** [comment]
I'm looking at the code now:
```
      "tests": [
        "// Test user did replace var keyword",
        "// Test magic is const",
        "// Test magic is a function",
        "// Test magic() returns the correct date",
        "// Test function keyword was not used",
        "// Test arrow => was used"
      ],
```
I'm assuming there aren't tests for this section yet?

**Comment by JosephLivengood** [comment]
Currently the es6 challenges are not functioning and the tests don't actually test anything. They are working on this!

Looks like the challengeSeed is missing the `;` at the end of defining magic though

**Comment by benschac** [comment]
how can I see what's being worked on?
