### ISSUE TITLE
[Where do I belong] Right results but not pass the test

### ISSUE THREAD

**Issue by or-halimi** [freeCodeCamp/freeCodeCamp#13493]
Challenge [Where do I belong](https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=%0Afunction%20getIndexToIns(arr%2C%20num)%20%7B%0A%20%20arr%20%3D%20arr%3B%0A%20%20for%20(var%20i%20in%20arr.sort(function(a%2Cb)%7Breturn%20a-b%3B%7D))%7B%0A%20%20%20%20if%20(arr%5Bi%5D%20%3E%3D%20num)%20%7Breturn%20i%3B%7D%0A%20%20%7D%0A%20%20return%20arr.length%3B%0A%7D%0A%0AgetIndexToIns(%5B3%2C%2010%2C%205%5D%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function getIndexToIns(arr, num) {
  arr = arr;
  for (var i in arr.sort(function(a,b){return a-b;})){
    if (arr[i] >= num) {return i;}
  }
  return arr.length;
}

getIndexToIns([3, 10, 5], 3);

```

I got in the return all the right value from the test, it just don't get it right.

**Comment by raisedadead** [comment]
[These tests evaluate to `string`](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-algorithm-scripting.json#L788-L794) and the `===` check fails to capture this even though result from the function is resolved as a `number`

**Comment by xpdavid** [comment]
@or-halimi @JosephLivengood @raisedadead 
I would say it's is not actually a bug.

As described [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in), the `for-in` loop actually will iterate through all properties in Object (Yes, Array is also a Object in Javascript).

In this case, `for in` loop is used, Javascript would regard the index as a property and thus return a string type to represent the property.

Technically, it not the fault of `freeCodeCamp`, but what we can do it to provide more user friendly error prompt when the answers are different.

**Comment by JosephLivengood** [comment]
Should we provide leniency or keep expectations and add a clarifying line to make them aware the result must be an int?

**Comment by xpdavid** [comment]
Hmm, the user(beginner? learner?) may not aware of the types in JavaScript (This is actually something bad in JS). So maybe I prefer more on leniency.

But what I am thinking is to provide an error message like `Expect 2 but got "2"`. This would help the user to find the type difference by theirselves.

**Comment by JosephLivengood** [comment]
I agree with leaving the tests as strictly equaling and clarifying better the error or the challenge needs to return a `number` type.

**Comment by ajain17** [comment]
I'll work on this. Will add error message of the format Expected Value, Returned Value. Is that okay?

**Comment by raisedadead** [comment]
@ajain17 I would wait a bit on this for being confirmed. Please feel free to look at other issues.

@xpdavid @JosephLivengood Thanks for the comments, I think there is a confusion in the analysis.

The OP's last return statement is `return arr.length;` which irrespective of the contents (properties) of the Object (array in this case), will return a `number` and is returning a `number`

Hence while technically they may have used `for...in`, the last return is what the tests are getting.

But, I have a reason to believe that in the below check 
`assert(getIndexToIns([10, 20, 30, 40, 50], 35) === 3, ...)`

Somehow its evaluating to `string` ?

I will have to dig deeper to confirm though.

**Comment by xpdavid** [comment]
@raisedadead Yes, the last statement `return arr.length` return a `number`, that's why several test cases passed as the programme hits the last statement.

However, in most cases, the programme will return in the middle because of `if (arr[i] >= num) {return i;}`. Here, `i` is the properties of the `Object`(`Array`), which is a string.

**Comment by raisedadead** [comment]
Oh darn! I completely missed it. Thanks and good catch @xpdavid ! Let's add the error message with type checking as suggested by @xpdavid !

**Comment by BhaveshSGupta** [comment]
I would like to try this, but I am still trying to figure how to do that..

**Comment by ajain17** [comment]
@BhaveshSGupta  go ahead, I havent started work on it.
