### ISSUE TITLE
"Where do I belong" Insufficient Test Cases

### ISSUE THREAD

**Issue by xpdavid** [freeCodeCamp/freeCodeCamp#13498]
#### Challenge Name
http://beta.freecodecamp.com/en/challenges/basic-algorithm-scripting/where-do-i-belong

#### Issue Description
The test cases are insufficient and fail to cover a edge case. It doesn't test the behaviour of the programme when the input array is empty.
``` js
getIndexToIns([], 1); // should return 0
```

#### Screenshot
Current test cases:
![screen shot 2017-02-21 at 11 50 38 pm](https://cloud.githubusercontent.com/assets/13977235/23172384/9342f61c-f890-11e6-9f41-b490a452d045.png)

If possible, I would like to fix this :)

**Comment by JosephLivengood** [comment]
@xpdavid  Great! Do you also want to take a crack at #13493 while you're there? :+1: 

[CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) can help you get started.

If you have any questions, please come chat with us in the [Contributors Chat Room](https://gitter.im/FreeCodeCamp/Contributors).

**Happy Coding!** :1st_place_medal:
