### ISSUE TITLE
Applied Visual Design: Learn about Tertiary Colors - not verifying bg color is set

### ISSUE THREAD

**Issue by sue888** [freeCodeCamp/freeCodeCamp#13490]
#### Challenge Name
Applied Visual Design: Learn about Tertiary Colors

#### Issue Description

Receiving the following error, although background set correctly (screenshot included). It accepts hex color code.

**Error: The div element with class orange should have a background-color of orange.**

#### Browser Information
Chrome Version 56.0.2924.87 (64-bit)

iMac, Mac OS Sierra 10.12.3

#### Your Code
<style>
  body {
    background-color: #FFFFFF;
  }
  .orange {
    background-color: orange;
  }
  .cyan {
    background-color: cyan;
  }
  .raspberry {
    background-color: #FF007D;
  }  
  div {
    height: 100px;
    width: 100px;
    margin-bottom: 5px;
  }
</style>
<div class="orange"></div>
<div class="cyan"></div>
<div class="raspberry"></div>

#### Screenshot
![screen shot 2017-02-20 at 7 12 30 pm](https://cloud.githubusercontent.com/assets/11083357/23149421/9c81b01a-f7a0-11e6-9c31-cbc27d480ba4.png)

**Comment by Marmiz** [comment]
@sue888 you are supposed to change from the 'string' value to the hex.
So the error is thrown since 
```
.orange { background-color: orange; }
```
you are not passing the hex.

---
Now the real question is why `cyan` is accepted since you are not passing the hex there too.
Probably worth to look at the test cases.

**Comment by sue888** [comment]
Ah - must have missed that instruction -  have been using strings successfully throughout this section (where I knew it to be an option).

**Comment by JosephLivengood** [comment]
Closing as solved! 👍

**Comment by Marmiz** [comment]
@JosephLivengood actually I think this is worth a look.

OP said she had trouble with `orange` but, as a matter of fact in her original code also `cyan` was wrong but the checkmarks didn't reflected that.

It's probably worth looking into it. no?

**Comment by sithsupersu** [comment]
? The question is what did he modify?
