### ISSUE TITLE
Current Streak is not accurate

### ISSUE THREAD

**Issue by donofriov** [freeCodeCamp/freeCodeCamp#13506]
#### Issue Description
The Current Streak on the User Stats Page is reset to 1 even though there is still an active streak. In the screenshots below, Current Streak should have a value of 7 days and so should Longest Streak. This is possibly caused by the fact that it is counting current streaks of Challenges and not the other activities (Projects or Algorithms) 

This slide (https://www.freecodecamp.com/challenges/configure-your-profile) does specifically state you need to complete challenges to get a streak, but I think Project and Algorithms should count towards this as well because it could take a couple days to get through an entire Algorithm or Project section before getting back to Challenges.

![image](https://cloud.githubusercontent.com/assets/4457953/23196927/c1e7603a-f88a-11e6-895c-d1cc1261c452.png)
![image](https://cloud.githubusercontent.com/assets/4457953/23196931/c8261892-f88a-11e6-8535-6f6e235e08fb.png)

**Comment by raisedadead** [comment]
Closing in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/7925

**Comment by donofriov** [comment]
Yikes sorry @raisedadead , I even did an issue search before opening :man_facepalming:

**Comment by raisedadead** [comment]
@donofriov Sure thing, not a problem.
