### ISSUE TITLE
FCC Forum - shutdown?

### ISSUE THREAD

**Issue by KenzoM** [freeCodeCamp/freeCodeCamp#13504]
Sorry if this is the wrong place to ask, but I can't seem to connect FCC forum. It looks like it's down. Any ideas?

**Comment by donofriov** [comment]
@KenzoM it looks like it is down right now, will need to be fixed on the hosting side of things. Maybe someone was working on a deploy or something? 

![image](https://cloud.githubusercontent.com/assets/4457953/23193522/67ff398e-f877-11e6-9b3c-ee2a245ec048.png)

**Comment by texas2010** [comment]
freeCodeCamp team are aware of the forum is down.

**Comment by donofriov** [comment]
@texas2010 How do you know the team is aware? Is there somewhere outside of GitHub that is good to look for more information?

**Comment by texas2010** [comment]
@donofriov, I am the member of the freeCodeCamp team.  I did inform someone. someone know about it.

What do you mean you want to know more information?  sorry, I don't understand that question.

**Comment by donofriov** [comment]
I was just wondering if there was another site that had more info about forum status or if this information was shared on social media or somewhere else. 

It now makes sense knowing that you are a member of the team 😄

**Comment by texas2010** [comment]
@donofriov Oh. we don't have a status for the forum.

**Comment by hamo225** [comment]
Is FCC down again?
