### ISSUE TITLE
Bonfire: Finders Keepers Array.some() suggestion link

### ISSUE THREAD

**Issue by jamesyp** [FreeCodeCamp/FreeCodeCamp#1350]
I was able to solve this bonfire with a for loop and just calling the passed function directly on each item of the array, but the problem description suggests using Array.some(). I couldn't figure out how to solve it with that and turn the boolean result of Array.some() into the specific array index that passed the test function.

Is there a way to solve this bonfire with the suggested array method? Is it meant to link to Array.some() at all? This feels like a misleading and/or convoluted suggestion for solving this problem.

**Comment by markwright174** [comment]
jamesyp,

I used .some(), but the way I did it still required a for loop. I created a new array that had 1 element of the original array, then ran that new array through the function with .some(), using a for loop to change which element was in the new array. Make sense? 

I'm not sure it was necessarily the best way to go, but I wanted to use the .some suggestion.

**Comment by jamesyp** [comment]
That's a solution, but it's definitely not the best one as I see it. The reason for that is you're creating a new single-element array through each loop iteration, which is pretty inefficient, and I'm not sure what the teaching value of that is for Array.some(). 

For the record, here's the solution I had, which is straightforward and more efficient than the one you're proposing.
```
function find(arr, func) {
  for (var i = 0; i < arr.length; i++) {
    if (func(arr[i])) {
      return arr[i];
    }
  }
  return undefined;
}
```
As far as I can see, using Array.some() will make the solution more complicated and/or more difficult to see, which is why I'm wondering why it's being suggested in the bonfire.

**Comment by thenasfarce** [comment]
I ran into the same problem as you. unless there's some way of extracting the element of the array that causes the some(func) to return true; it seems like there's no good reason to use some() at all. I read through the documentation like 5 times to try and figure out how to do this and found no clues.

**Comment by fateshaper** [comment]
Hey guys, in the midst of doing this bonfire right now - based on the documentation of .some , some can actually return the index of the array it first finds true - via the following syntax  : 

function isBiggerThan10(element, index, array) {
  return element > 10;
}
[2, 5, 8, 1, 4].some(isBiggerThan10);  // false
[12, 5, 8, 1, 4].some(isBiggerThan10); // true <---- index passed in is 0.

Should be some help :)

**Comment by Karnblack** [comment]
I just did this and my code is almost verbatim to jamesyp. Using the some() method would seem to increase the complexity of the code. There are many times I don't use the helpful hints in these bonfires, but sometimes I'll use them and sometimes they'll trigger me exploring other methods.

**Comment by benschenker** [comment]
Closing this as stale/fixed

**Comment by michaelkebe** [comment]
The suggested function `Array.some()` is misleading, because it does not help with the solution. I would recommend to remove it.

Though, with ES6 a suggestion of `Array.find()` is useful.
