### ISSUE TITLE
function minusSeven(num) {   return num - 7; }

### ISSUE THREAD

**Issue by sitaramakrishnach** [freeCodeCamp/freeCodeCamp#13511]
Challenge [Return a Value from a Function with Return](https://www.freecodecamp.com/challenges/return-a-value-from-a-function-with-return#?solution=%0A%2F%2F%20Example%0Afunction%20minusSeven(num)%20%7B%0A%20%20return%20num%20-%207%3B%0A%7D%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Afunction%20timeFive(num)%7B%0A%20%20return%20num%20*%205%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function minusSeven(num) {
  return num - 7;
}

// Only change code below this line

function timeFive(num){
  return num * 5;
}

```

**Comment by BhaveshSGupta** [comment]
hey @sitaramakrishnach, Check the instructions once again, you have a small typo in your code, for this type of help please use gitter group at https://gitter.im/FreeCodeCamp/FreeCodeCamp

**Comment by raisedadead** [comment]
@sitaramakrishnach Thanks for reporting.

As @BhaveshSGupta there is a typo in your code, the issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
