### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-set-the-font-family-of-an-element Issue

### ISSUE THREAD

**Issue by NickHillebran** [FreeCodeCamp/FreeCodeCamp#1351]
When I was doing this challenge, I noticed that the "Go to my next challenge" button is enabled even before completing the line of code.  On line 8, I had to following code:

font-family: Monospace

This is an issue as the CSS line hadn't been closed out yet with a semicolon.  As soon as I typed the last letter of Monospace, the button was enabled.

**Comment by benschenker** [comment]
Closing, see: #2465 for a similar issue
