### ISSUE TITLE
Getting 'Only GitHub users can join this room.' when trying to access the chat

### ISSUE THREAD

**Issue by VeryKnave** [freeCodeCamp/freeCodeCamp#13517]
#### Issue Description

I noticed the issue happened yesterday. I don't know how to reproduce it. I tried to log in and out, to add my Twitter account but without success.

#### Browser Information

* Browser Name, Version: Google Chrome (latest)
* Operating System:  Windows 7 Ultimate (64-bit)
* Mobile, Desktop, or Tablet: ---

#### Screenshot

![untitled](https://cloud.githubusercontent.com/assets/23298862/23214963/4eb5282e-f919-11e6-9f8e-55cc68795185.png)

**Comment by raisedadead** [comment]
freeCodeCamp's chat room's do not have support for twitter logins on GitHub, you need to login via GitHub only, and the same should be linked to your freeCodeCamp account as well.
