### ISSUE TITLE
Use Responsive Design with Bootstrap Fluid Containers. Issue with wrong link example.

### ISSUE THREAD

**Issue by RAYDENFilipp** [freeCodeCamp/freeCodeCamp#13513]
#### Challenge Name

Use Responsive Design with Bootstrap Fluid Containers

#### Issue Description

There is a wrong link given as an example in challenge description:
`<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>`
The correct link should be without "/" after "min.css":
`<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">`

#### Browser Information

* Browser Name, Version: IE 11
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![capture](https://cloud.githubusercontent.com/assets/24476415/23209008/07d14fa0-f900-11e6-9cff-f62f0fe25dab.JPG)

**Comment by raisedadead** [comment]
I think this is bikeshedding? 
Using link tags as self closing is completely fine in HTML5.

Will leave others to comment and close, or proceed in case they think otherwise.
/cc @freeCodeCamp/moderators

**Comment by Greenheart** [comment]
It's an interesting detail, and since both technically are valid - maybe we should show the cleaner way to use a link tag?

**Comment by RAYDENFilipp** [comment]
@raisedadead The problem is that before opening the issue, I read the Bootstrap Blog, and there was a link that made me think of a mistake. Anyway, if it is not the mistake, they probably should place the comment in the frecodecamp lesson to clarify this for others who will see it as a problem.

**Comment by raisedadead** [comment]
@Greenheart @RAYDENFilipp cool, we can add a note about this.

**Comment by AngShiYa** [comment]
I can take this up. Will a note like this be clear enough?
"Using either of both `>` or `/>` to close the link tag are acceptable."

**Comment by RAYDENFilipp** [comment]
@AngShiYa Fantastic! Seems easy to get the message.

**Comment by raisedadead** [comment]
@AngShiYa Sure, please go ahead. Thanks.

**Comment by cdrainxv** [comment]
Should the above link also be updated to v3.3.7 considering that v3.3.7 is required and included in the seed code for these challenges? I only mention this to maintain uniform consistency.

**Comment by raisedadead** [comment]
Yup, thanks @cdrainxv.

@AngShiYa if your taking a crack at this, could you please update the link as well, as noted above?

**Comment by AngShiYa** [comment]
Sure :)

**Comment by Greenheart** [comment]
Thanks to everyone involved! This is the beauty of OSS collaboration at it's best! :smile:
