### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website show task as invalid

### ISSUE THREAD

**Issue by NickHillebran** [FreeCodeCamp/FreeCodeCamp#1352]
I'm on the "Waypoint: Add Images to your Website"challenge.  Of the two tasks, it only puts a check mark by the first one, "Your page should have an image element."  My coding has both tasks completed.

It seems to be valid as when I look at the cell phone on the page, it shows the cat image.  I've attached a copy of the code I have.  The code I typed is at the bottom of the image.

![image-to-website-code](https://cloud.githubusercontent.com/assets/13283387/8814420/ea15ca16-2fd1-11e5-8404-17d1dcb275f9.png)

**Comment by benschenker** [comment]
Hi @NickHillebran,

It wants your image src to point to `https://bit.ly/fcc-relaxing-cat`.

Closing, but feel free to reopen if you still have any issues
