### ISSUE TITLE
Recommended Weather API requires paid for service to use HTTPS

### ISSUE THREAD

**Issue by greenfreq** [freeCodeCamp/freeCodeCamp#13523]
Challenge [Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

CodePen does not like to access http resources.

 `Mixed Content: The page at 'https://codepen.io/greenfreq/pen/GrVezj' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.apixu.com/v1/current.json?key=<censored>&q=<censored>,<censored>'. This request has been blocked; the content must be served over HTTPS.`

 The recommended API OpenWeatherMap only supports HTTPS for certain paid subscribers.  
Consider suggesting (https://www.apixu.com/api.aspx) instead as it supports HTTPS without cost.

**Comment by erictleung** [comment]
@greenfreq thanks for the issue. This is closely related and generalizable to this issue https://github.com/freeCodeCamp/freeCodeCamp/issues/9079. Closing as duplicate. Please feel free to add to the discussion over there. Happy coding!

**Comment by eladonline** [comment]
this is the answer i got 
Q: API calls return an error 401
A: Starting from 9 October 2015 our API requires a valid APPID for access. Note that this does not mean that our API is subscription-only now - please take a minute to register a free account to receive a key.

We are sorry for inconvenience but this is a necessary measure that will help us deliver our services to you faster and more reliably.

For FOSS developers: we welcome free and open source software and are willing to help you. If you want to use OWM data in your free software application please register an API key and file a ticket describing your application and API key registered. OWM will review your request lift access limits for your key if used in open source application.
