### ISSUE TITLE
Problem with stand-in-line

### ISSUE THREAD

**Issue by devking1118** [freeCodeCamp/freeCodeCamp#13524]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function nextInLine(arr, item) {
  // Your code here
  
  return item;  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

**Comment by erictleung** [comment]
@devking1118 thanks for the issue. Can you elaborate on what the problem you're facing with this issue? It isn't clear from the description you've given.

**Comment by atjonathan** [comment]
@devking1118, please reopen if this is a legitimate issue.

**Comment by cjpoy** [comment]
![image](https://cloud.githubusercontent.com/assets/18303895/23616211/6fc7b918-02a2-11e7-86d9-fc5da890ed20.png)

Can't move forward because of error # 1, please help what's wrong, Thanks

**Comment by cjpoy** [comment]
![image](https://cloud.githubusercontent.com/assets/18303895/23616487/524e5c2e-02a3-11e7-9909-f91b892cfc8e.png)

I got it now, maybe about on order how it was presented or the variable name . Anyways the fun continues !
