### ISSUE TITLE
Real-world examples?

### ISSUE THREAD

**Issue by TimHandy** [freeCodeCamp/freeCodeCamp#13520]
Hi, I think this needs some simple real-world examples of when it would be useful. I've done the challenge, but maybe it's too contrived an example to make sense? I am non the wiser on when I would use this feature.

I'm a relative noob, so can't give any input I'm afraid.

**Comment by raisedadead** [comment]
@TimHandy thanks for the feedback. But which challenge are we talking about?

**Comment by erictleung** [comment]
@TimHandy the "world examples" I think come when you start the projects. That's where you're really just thrown into figuring out and thinking more on how to work on projects. There's a balance between having learning enough of the basics to tackle "real projects" even though some of the basic information you won't need anymore. But as @raisedadead has asked, let us know which challenges you are referring to.

**Comment by Greenheart** [comment]
@TimHandy Seems like you're referring to an extra example in a challenge description? :blush:

**Comment by raisedadead** [comment]
Closing, please clarify as requested.

**Comment by TimHandy** [comment]
Oh, sorry, I didn't see a notification of an update to this... I believe it was "Functional Programming: Introduction to Currying and Partial Application".
