### ISSUE TITLE
Can't pass Profile Lookup Challenge with correct answers

### ISSUE THREAD

**Issue by charliez** [freeCodeCamp/freeCodeCamp#13526]
Challenge [Profile Lookup](https://www.freecodecamp.com/challenges/profile-lookup#?solution=%0A%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intriguing%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%0A%5D%3B%0A%0Avar%20nameExists%20%3D%200%3B%0A%0Afunction%20lookUpProfile(Name%2C%20prop)%20%7B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afor%20(var%20i%20%3D%200%3B%20i%20%3C%20contacts.length%3B%20i%2B%2B)%20%7B%0A%20%20if%20(contacts%5Bi%5D.firstName%20%3D%3D%20Name)%20%7B%20%0A%20%20%20%20nameExists%20%3D%201%3B%0A%20%20%20%20if%20(Object.keys(contacts%5Bi%5D).indexOf(prop)%20%3E%200)%20%7B%0A%20%20%20%20%20%20%20%20return%20contacts%5Bi%5D%5Bprop%5D%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20return%20%22No%20such%20property%22%3B%0A%20%20%20%20%7D%20%20%20%20%0A%20%20%7D%0A%7D%0Aif%20(nameExists%20%3D%3D%3D%200)%20%7B%20return%20%22No%20such%20contact%22%3B%20%7D%0A%20%20%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0AlookUpProfile(%22Bob%22%2C%20%22number%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];

var nameExists = 0;

function lookUpProfile(Name, prop) {
// Only change code below this line
for (var i = 0; i < contacts.length; i++) {
  if (contacts[i].firstName == Name) { 
    nameExists = 1;
    if (Object.keys(contacts[i]).indexOf(prop) > 0) {
        return contacts[i][prop];
    } else {
      return "No such property";
    }    
  }
}
if (nameExists === 0) { return "No such contact"; }
  
// Only change code above this line
}

// Change these values to test your function
lookUpProfile("Bob", "number");

```
My code works on JSBIN (see screen) and also on freeCodeCamp editor (see screen) but I cannot pass the challenge to continue...

JSBIN Screen
https://drive.google.com/open?id=0B4Vi7Y8ouAiATkVEVkpGR05RZkE

freeCodeCamp Screen
https://drive.google.com/open?id=0B4Vi7Y8ouAiAaDNlMDQwc3Y3eGM

**Comment by erictleung** [comment]
@charliez thanks for the issue. You have global variables in your code. Our challenge tests run your function over and over and if you have any global variables (`nameExists`), they will change with each test. So move your global variables to within your function and your code will pass. Happy coding!

**Comment by charliez** [comment]
@erictleung thanks for the info.  I knew you tested all the cases but thought that each test would start from scratch.  It works now...
