### ISSUE TITLE
[BETA] can pass test but does not reflect in map

### ISSUE THREAD

**Issue by rmdawson71** [freeCodeCamp/freeCodeCamp#13528]
Challenge [access-an-arrays-contents-using-bracket-notation](http://beta.freecodecamp.com/en/challenges/basic-data-structures/access-an-arrays-contents-using-bracket-notation) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I pass the tests and get the "success" dialogue, but when I click "Submit" and go to the next challenge, I get a message that says "something went wrong"  When I go back to look at the map, the challenge is not grayed out even though the challenge was passed successfully.

![image](https://cloud.githubusercontent.com/assets/5313213/23231432/9de2561e-f8fc-11e6-82b3-9c705e59eb6e.png)

```js


let myArray = ["a", "b", "c", "d"];
// change code below this line
myArray[1] = "z";
//change code above this line
console.log(myArray);

```

**Comment by raisedadead** [comment]
Hi @rmdawson71 thanks a lot for the report, I am closing this in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/13537, although yours was first, the other thread has gotten more discussion.

Feel free to follow along there. Thanks once again.

**Comment by traanhn** [comment]
I got the same problem. 
I completed the code and passed the test as well but it doesnt show in the map
