### ISSUE TITLE
[beta] Applied Visual Design: Tertiary Colors Throwing Errors with Correct Hex 

### ISSUE THREAD

**Issue by al3tte** [freeCodeCamp/freeCodeCamp#13535]
See screenshot below for clarification. Correct (given) hex codes are still throwing errors. Have refreshed, restarted, and cleared cache. Please advise as it will not allow me to continue without passing this challenge. 

Thank you! 

Challenge [learn-about-tertiary-colors](http://beta.freecodecamp.com/en/challenges/applied-visual-design/learn-about-tertiary-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  body {
    background-color: #FFFFFF;
  }
  
  .orange {
    background-color: #ff7d00;
  }
  
  .cyan {
    background-color: #00ffff;
  }
  
  .raspberry {
    background-color: #ff007d;
  }
  
  div {
    height: 100px;
    width: 100px;
    margin-bottom: 5px;
  }
</style>
  
<div class="orange"></div>
<div class="cyan"></div>
<div class="raspberry"></div>

```

![image](https://cloud.githubusercontent.com/assets/25273475/23242252/c803867c-f945-11e6-9a71-751a8136bddf.png)

**Comment by Manish-Giri** [comment]
@al3tte It's because you're using lowercase hex code values. 

While the (general) convention is uppercase values, I think we should amend the [tests](https://github.com/freeCodeCamp/freeCodeCamp/blob/0e4f07a197b994a7f8369fc4bdb0793cdc0a6998/seed/challenges/01-responsive-web-design/applied-visual-design.json#L1569-L1571) to allow lowercase values too, as they're not incorrect. 

*Side Note* - I can work on this, if we decide to proceed.

**Comment by cdrainxv** [comment]
@Manish-Giri: Yeah... sorry... I should have accounted for this in my recent PR. 😄 .(I assumed people would just copy and paste the hex code values into the editor). I agree that ***you*** should go ahead with amending the tests to allow for the lowercase hex code option. (Although including tests for every possible permutation of a solution could become egregious, considering that the table provides the exact hex code values to use).

Note: Does this now mean that there should be an inclusion in the description field that hex code values can either be all lowercase or uppercase? If not, was this mentioned in an earlier challenge in the Applied Visual Design section?

**Comment by al3tte** [comment]
@Manish-Giri Doh! I used lowercase values on the other hex tests so I didn't even think to try that! 

@cdrainxv On the other challenges the lowercase values were accepted, so you may want to consider changing one or the other, for consistency's sake, if nothing else. 

Thank you both for the quick responses though! :grinning:
