### ISSUE TITLE
[beta] add items to an array with push and unshift tests not working.

### ISSUE THREAD

**Issue by masters-george** [freeCodeCamp/freeCodeCamp#13538]
Challenge [add-items-to-an-array-with-push-and-unshift](http://beta.freecodecamp.com/en/challenges/basic-data-structures/add-items-to-an-array-with-push-and-unshift) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I pasted the code below into replit.com -- the console log is correct though it gives an undefined error. The error may be a replit limitation. I also tried reversing the order of the lines and the code still works.

```js


function mixedNumbers(arr) {
  // change code below this line
  arr.push(7, 'VIII', 9);
  arr.unshift('I', 2, 'three');

  // change code above this line
  return arr;
}

// do not change code below this line
console.log(mixedNumbers(['IV', 5, 'six']));

```
![image](https://cloud.githubusercontent.com/assets/24727860/23245389/e56c956e-f940-11e6-98b5-bb8a44bd6404.png)

**Comment by karuppiah7890** [comment]
Hey @masters-george, your code looks quite fine. You just missed the quotes around the number 9. If you see the instructions, the funnction should return `["I", 2, "three", "IV", 5, "six", 7, "VIII", "9"]` , but your function returns `["I", 2, "three", "IV", 5, "six", 7, "VIII", 9]` . See the quotes missing around 9 ? Just change that and you should be good! :smile:

**Comment by karuppiah7890** [comment]
@raisedadead This is not an issue. This is a bug in the OP's code.

**Comment by raisedadead** [comment]
Will close, post confirmation. The label is a intial triage.

**Comment by raisedadead** [comment]
@masters-george thanks for the report, for what its worth I can see that the '9' is needed as a string for this challenge to pass the test, but that would lead to a pain point of unintentional typos as in your submission.

This is not a requirement for the challenge's scope about teaching array shift and unshift operations.

We should just update the seed and the test to accept `9` as a number instead.

**Comment by Manish-Giri** [comment]
@raisedadead I'll do this!

**Comment by masters-george** [comment]
Thanks! That's an easy one to miss.

George Masters
instructional Designer /Trainer
408.242.4632

**Comment by raisedadead** [comment]
@Manish-Giri all yours.! 😉

**Comment by Ethan-Arrowood** [comment]
@Manish-Giri How are you doing on this? Let me know if you'd like any help or want to pass it on to me.
