### ISSUE TITLE
border

### ISSUE THREAD

**Issue by AdamANDAdam** [freeCodeCamp/freeCodeCamp#13539]
Hi,

I do not know what am I doing wrong, it does not draw border around image.

Thank You 

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  
  .thick-green-border{
    
    border-color: green;
    border-width: 10px
    border-style: solid;
    
  }
  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its ack. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by raisedadead** [comment]
@AdamANDAdam thanks for reporting,

But the issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
