### ISSUE TITLE
[beta] Error - loopProtect is not defined

### ISSUE THREAD

**Issue by gelbelle** [freeCodeCamp/freeCodeCamp#13533]
Challenge [catch-off-by-one-errors-when-using-indexing](http://beta.freecodecamp.com/en/challenges/debugging/catch-off-by-one-errors-when-using-indexing) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


function countToFive() {
  let firstFive = "12345";
  let len = firstFive.length;
  // Fix the line below
  for (let i = 0; i < len; i++) {
  // Do not alter code below this line
    console.log(firstFive[i]);
  }
}

countToFive();

```

This matches the example code. The error I'm getting is the "loopProtect is not defined" error message I received on the last challenge. This time it is repeated 4 times.

**Comment by cdrainxv** [comment]
This seems to be a firefox issue as Safari and Chrome didn't seem to have this error. The current fix is just refreshing the page, although a proper fix would be welcome.

**Comment by raisedadead** [comment]
Closing in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/13532
