### ISSUE TITLE
Escape quotes not working 

### ISSUE THREAD

**Issue by pamela113** [freeCodeCamp/freeCodeCamp#13531]
Challenge [Quoting Strings with Single Quotes](https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes#?solution=%0Avar%20myStr%20%3D'%3Ca%20href%3D%22http%3A%2F%2Fwww.example.com%22%20%20target%3D%20%22_blank%22%3ELink%3C%2Fa%3E'%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr ='<a href="http://www.example.com"  target= "_blank">Link</a>';



```

**Comment by Marmiz** [comment]
I was not able to reproduce this issue, my challenge pass.
Can you be more explicit on the steps to reproduce?

In the meantime I believe a refresh will let you continue.
Happy coding 👍

**Comment by cdrainxv** [comment]
@pamela113 @Marmiz: The test is quite strict. It won't accept a space between `target=` and `"_blank"` or two spaces between attributes, like there are between `href="http://www.example.com"` and `target` (which it shouldn't so as to conform to accepted standards).

**Comment by Marmiz** [comment]
@cdrainxv good catch! didn't even noticed it in the original code 👍

**Comment by raisedadead** [comment]
@cdrainxv yup, thanks for debugging this. And while you are right about having no space between values and one space between attributes, I think this is still valid code.

We should probably relax the tests, given the fact that we are focusing not to involve standard practice in challenges, we have videos for those.

/cc @freeCodeCamp/moderators I am up for tagging this `help wanted`.

**Comment by Greenheart** [comment]
@raisedadead Adding a couple of `\s*` (0 or more whitespace characters) to the regex could probably solve this issue. I agree, this is ready to be fixed :blush:

@Marmiz @cdrainxv Thanks for the excellent triaging!

**Comment by pamela113** [comment]
The exercise says to remove all \. 
 Then you should have two single quotes and four double quotes. 
The last part , 3 of 3 says you should remove all \ that are used to escape quotes.
I have a pass on part one and part two the third one is not passing. 
Thanks for your prompt response!
Pamela

**Comment by jdeprey** [comment]
@pamela113 Did you get get it working?  After removing the extra spaces the final code should look like this:  
`var myStr ='<a href="http://www.example.com" target="_blank">Link</a>';`

**Comment by texas2010** [comment]
@jdeprey 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by IanTeo** [comment]
Hi, can I do this?

**Comment by raisedadead** [comment]
@IanTeo sure, please go ahead.

Here are the [Guidelines for Contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by jdeprey** [comment]
If extra whitespace is allowed where and how much should be acceptable?  As in, should spaces be allowed before and after the assignment operator as well as between `href` and `target`?

**Comment by raisedadead** [comment]
If extra whitespace is allowed where and how much should be acceptable?

Any no. It does not matter, the browser will strip away anything that's not needed.

**Comment by pamela113** [comment]
Hi,
Thanks Joseph!!  I logged out and logged back in and it worked.
Pam
