### ISSUE TITLE
[beta] Challenge does not update map when correct code is submitted

### ISSUE THREAD

**Issue by masters-george** [freeCodeCamp/freeCodeCamp#13537]
Challenge [access-an-arrays-contents-using-bracket-notation](http://beta.freecodecamp.com/en/challenges/basic-data-structures/access-an-arrays-contents-using-bracket-notation) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


let myArray = ["a", "b", "c", "d"];
// change code below this line
myArray[1] = 20;
//change code above this line
console.log(myArray);

```
![image](https://cloud.githubusercontent.com/assets/24727860/23245129/244008ae-f93f-11e6-9b60-6122f466c785.png)

**Comment by chemok78** [comment]
hi, works fine with the following user agent:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0

and the code below:

~~~
[let myArray = ["a", "b", "c", "d"];
// change code below this line
myArray[1] = "z;
//change code above this line
console.log(myArray);](url)
~~~

**Comment by masters-george** [comment]
I am using Chrome on Ubuntu Linux. I'll test again tomorrow since I got a
kernel and browser update tonight after the bug.

**Comment by jake-steele** [comment]
I can confirm this happened to me as well. (User Agent: Chrome Version 56.0.2924.87 (64-bit), Windows 10 Home (x64))

The same happened to me with the "Introduction to Arrays" challenge at the beginning of this section. I have tried refreshing or going to beta.freecodecamp.com and neither fixed the issue.

**Comment by shashank7200** [comment]
Happening with me also Browsers Tested on Chrome Version 57.0.2987.110 (64-bit)/ Firefox 53.0a2 (2017-03-07) (64-bit)

**Comment by RainierXS** [comment]
Same issue, console says I'm getting Error 500 on page load and then when submitting the answer I get error 403. Same issues on the Introduction to Array challenge.

**User Agent**
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Errors are 
**On page load:**
bundle-aef2645….js:9 POST http://beta.freecodecamp.com/update-my-current-challenge 500 (Internal Server Error)

**On answer submission:**
bundle-aef2645….js:9 POST http://beta.freecodecamp.com/modern-challenge-completed 403 (Forbidden)

**Comment by systimotic** [comment]
This appears to have been fixed. If anybody runs into this issue again, please add additional information and we'll reopen this issue. Happy coding!
