### ISSUE TITLE
[beta] Map: 'Getting Started' hidden by map header on mobile

### ISSUE THREAD

**Issue by billy-reilly** [freeCodeCamp/freeCodeCamp#13544]
http://beta.freecodecamp.com/en/map

The first map-accordion-panel-heading called 'Getting Started' is hidden by the map-fixed-header on mobile

iPhone 5 (safari) : 
![16930978_10212033363526400_1970075049_o](https://cloud.githubusercontent.com/assets/22368483/23260454/d4b7f036-f9c9-11e6-9c06-b47aac8a74d5.jpg)

**Comment by BerkeleyTrue** [comment]
map header is gone now. Does this resolve the issue?
