### ISSUE TITLE
Diff Two Arrays Challenge passed using wrong results.

### ISSUE THREAD

**Issue by achudoz** [freeCodeCamp/freeCodeCamp#13556]
#### Diff Two Arrays

https://www.freecodecamp.com/challenges/diff-two-arrays

#### Issue Description

Wrong array consisting of excessive numbers of correct solution values being accepted as right.
Upon entering a wrong combination of .filter() and a for loop methods, which returns incorrect array (code below), all the tests and the challenge as a whole are considered successfully passed. 
e.g. the first set of test arrays should return [4] and returns [4,4,4,4,4], which is of course something completely different, but still is accepted as a correct solution.

#### Browser Information

* Browser Name, Version: Firefox51.0.1 (32-bit)
* Operating System: Ubuntu 14.04
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code

```js
function diffArray(arr1, arr2) {
  var newArr = [];
  arr1.filter(function(x) {
    for (var i=0; i<arr1.length; i++) {
      if (arr2.indexOf(arr1[i]) < 0) {
        newArr.push(arr1[i]);
      }
    }
  });
  
  arr2.filter(function(x) {
    for (var i=0; i<arr2.length; i++) {
      if (arr1.indexOf(arr2[i]) < 0) {
        newArr.push(arr2[i]);
      }
    }
  });
  
  console.log(newArr);
  return newArr;
  
}

diffArray([1, 2, 3, 5], [1, 2, 3, 4, 5]);
```

**Comment by erictleung** [comment]
@achudoz thanks for the issue. This challenge's tests have been [updated recently](https://github.com/freeCodeCamp/freeCodeCamp/pull/11912), which solve the issue you've brought up. You can check them out on [the beta site](http://beta.freecodecamp.com/en/challenges/intermediate-algorithm-scripting/diff-two-arrays) for yourself. Closing as resolved in staging. Happy coding!
