### ISSUE TITLE
[beta] Bug adding email to account

### ISSUE THREAD

**Issue by loopliagiba** [freeCodeCamp/freeCodeCamp#13550]
#### Issue Description

I signed up with Github and then went to add my email and it said "Something went wrong please try again later".

#### Browser Information

* Browser Name, Version: Chrome, 56.0.2924.87 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

```js



```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/16135183/23273915/d67a80a0-f9ce-11e6-8bd3-5ca6bd4f77de.png)

![image](https://cloud.githubusercontent.com/assets/16135183/23273904/ca6b451a-f9ce-11e6-9ec7-7281c3d320f8.png)

**Comment by raisedadead** [comment]
Thanks for the report.
