### ISSUE TITLE
[beta] Various Challenges. Cursor Jumping to Top of Page

### ISSUE THREAD

**Issue by lydatech** [freeCodeCamp/freeCodeCamp#13561]
#### Challenge Name
Various

#### Issue Description
When entering code into the challenge, the cursor will randomly jump to the top of the page mid-word while typing. Tested in 2 Browser and on 2 systems.
This is a random issue and doesn't happen on every challenge

#### Browser Information

* Browser Name, Version: FireFox, Chrome (Latest and Greatest)
* Operating System: Windows 7, Windows 10
* Desktop

#### Your Code

```js



```

**Comment by gogolab** [comment]
I confirm. I noticed the same weird cursor jumps in many challenges.

**Comment by raisedadead** [comment]
@lydatech @gogolab thanks for the report. 

We have had this in the older infrastructure as well. We though this was resolved.
Sad to hear that this is back again.

Will look into it.

**Comment by raisedadead** [comment]
Refer #7847

**Comment by Lexis9784** [comment]
Confirmed. Tested on Chrome with Windows 7. Cursor jumps to top of the page when hitting enter for a new line. First noticed on "Nest Many Elements within a Single Div Element" in Basic HTML.

**Comment by augmt** [comment]
This happens to me when I stop typing and then immediately type any one character (immediately meaning some small time after the [editor's debounce time](https://github.com/freeCodeCamp/freeCodeCamp/blob/ee8ac7b4538473504fa9f1153f03ebb81be9f45e/common/app/routes/challenges/views/classic/Editor.jsx#L13)). Could this be an issue with `react-codemirror`?

**Comment by BerkeleyTrue** [comment]
@raisedadead how is this issue different from #7847 ?

**Comment by raisedadead** [comment]
@BerkeleyTrue I haven't been able to confirm the cause on this. 

But looks like the bug continues to stay between the original code mirror to `react-codemirror` as per comments from above?

I haven't been able to reproduce this either.

We could close this, in favour of the other, but I believe this is on different infrastructure than the previous.

**Comment by Jax05** [comment]
This keeps happening to me usually when I'm on the last line of my code. I'm using Chrome on Windows 7.

**Comment by sogen** [comment]
For everyone having the mouse cursor problem, try Chrome Canary, works fine

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
