### ISSUE TITLE
[beta] "ES6: Use Destructuring Assignment with Arrays": challenge seed contains part of description

### ISSUE THREAD

**Issue by gogolab** [freeCodeCamp/freeCodeCamp#13569]
Challenge  use-destructuring-assignment-with-arrays  http://beta.freecodecamp.com/en/challenges/es6/use-destructuring-assignment-with-arrays  has an issue. User Agent is: <code>Mozilla/5.0  X11; Ubuntu; Linux x86_64; rv:51.0  Gecko/20100101 Firefox/51.0 </code>.

Challenge seed contains part of challenge description, possibly instead of the proper part of code:

`let a   8, b   6; // change code below this line // change code above this line blockquote>const  a, b     1, 2, 3, 4, 5, 7 ; br>console.log a, b ; // 1, 2 /blockquote> The variable a assumes first value, and b takes the second value from the array. You can also destructure in a way, that you can pick up values from any other array index position. You simply have to use commas  , . Instructions. Use destructuring to swap the variables a, b. Swapping is an operation, after which, a gets the value stored in b, and b receives the value stored in a `

**Comment by AngShiYa** [comment]
I'll fix this.
