### ISSUE TITLE
Bug report for Commenting Out segment

### ISSUE THREAD

**Issue by pendragon8** [freeCodeCamp/freeCodeCamp#13562]
#### Challenge Name

After completing task of Commenting Out, I still get blocked with a message, Do not change the order, which I have not done and reset this a few times unsuccessfully. Is this a bug?

#### Issue Description

Commenting out `<h1>` and `<p>` doesn't complete this step, it gives error message of changing the order. I tried several times to change it to some desireable lineup, but no good. Reset and still not advancing after completing tasks.

#### Browser Information

* Browser Name, Version: Firefox(64)v. 51.0.1
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Dell Latitude laptop

#### Your Code

```js



```
#### Screenshot

![screenshot-www freecodecamp com-2017-02-23-22-10-04](https://cloud.githubusercontent.com/assets/24770582/23290236/f1f9976c-fa14-11e6-840e-b5c118dd9b3f.png)

![screenshot-www freecodecamp com-2017-02-23-22-10-04](https://cloud.githubusercontent.com/assets/24770582/23290270/207d7900-fa15-11e6-9fee-4c91860e7b59.png)

**Comment by pendragon8** [comment]
After following the directions, why am I still getting an error message about changing the order? Please help so I can continue!

**Comment by Marmiz** [comment]
@pendragon8  there's a typo in how you commented your `p`; that's why your challenge is not passing.

Please also mind that this is a place of reporting issue, to ask help it's better to go on Gitter or post/search on the forum:
[Gitter Help Chat](https://gitter.im/FreeCodeCamp/Help)
[Forum](https://forum.freecodecamp.com/)

Happy coding 👍

**Comment by raisedadead** [comment]
@pendragon8 your code is incorrect. Please proceed to the chat room or the forum.
