### ISSUE TITLE
Escape Sequences in Strings

### ISSUE THREAD

**Issue by dshelton2007** [freeCodeCamp/freeCodeCamp#13568]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22Firstline%5Cn%5C%5CSecondLine%5C%5C%5CrThirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "Firstline\n\\SecondLine\\\rThirdLine"; // Change this line

```

![image](https://cloud.githubusercontent.com/assets/11427069/23308852/235e0e52-fa72-11e6-8d91-828acf8ad066.png)

**Comment by texas2010** [comment]
@dshelton2007 
Thanks for reporting this. But your code is incorrect and you got typo. 
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by isseygino911** [comment]
![screen shot 2017-03-07 at 2 03 57 pm](https://cloud.githubusercontent.com/assets/25338767/23680168/10e9ed38-033f-11e7-8e98-b16bb8d6a2d6.png)
