### ISSUE TITLE
[beta] Bug in Creating and Adding to Sets in ES6

### ISSUE THREAD

**Issue by Kenneth-LJS** [freeCodeCamp/freeCodeCamp#13565]
#### Challenge Name

[Creating and Adding to Sets in ES6](https://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/creating-and-adding-to-sets-in-es6)

#### Issue Description

I can't get the test to pass no matter what I write in the editor, it keeps giving this error:

![image](https://cloud.githubusercontent.com/assets/21071217/23303809/2f431078-fad1-11e6-97ad-5c4b2adffffd.png)

#### Browser Information

* Browser Name, Version: Chrome v56.0.2924.87
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```
function checkSet(){
   var set = new Set([1,2,3,3,2,1,2,3,1]);
   // change code below this line
   set.add("Taco");
   set.add("Cat");
   set.add("Awesome");
   // change code above this line
   console.log(set);
   return set;
}
checkSet();
```

**Comment by Kenneth-LJS** [comment]
Looking at the challenge code, it seems like the test has syntax errors and won't compile:

![image](https://cloud.githubusercontent.com/assets/21071217/23303867/87343ec4-fad1-11e6-98cf-e36bde2a4cb4.png)

Can I try and fix this?

**Comment by raisedadead** [comment]
@Kenneth-LJS Sure, please go ahead and make a pull request. And while you are at this can you update the challenge seed code for the `;` being on the wrong line in [these lines](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json#L696-L697)

Here are our [Guidelines for Contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md), and you can reach us on the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), for any assistance.

Thanks for your contributions.
