### ISSUE TITLE
Chrome tab crashing whilst doing bonfires

### ISSUE THREAD

**Issue by Ikucuk** [FreeCodeCamp/freecodecamp#1356]
I haven't been able to make entirely sure this isn't caused by the user's environment, but it seems I'm not the only one experiencing crashes whilst doing bonfires, perhaps this is an issue within FCC's code?

**Comment by benmcmahon100** [comment]
Your code contains an infinite loop and that is why your tab is crashing

**Comment by Ikucuk** [comment]
I've written infinite loops on purpose to test this, and every time I do, it catches it and prevents a crash.

**Comment by benmcmahon100** [comment]
So when have you experienced this issue? There is a know problem with recursion but other than that it's down to computer power. If your browser runs out of local resources before the editor catches it then the browser crashing makes sense. There's no real way to compensate for this as well as to make it "Safe" on every device will really bottleneck performance for others. All the bofires that aren't bugged can be passed it's just that if you lack local power your code needs to be more efficient than the code of someone who has a lot of power in their computer.

**Comment by Ikucuk** [comment]
I've figured out one cause, I ran an if comparing values with var1 != var2, this causes a crash, using !== works.

**Comment by benmcmahon100** [comment]
What specs, os and browser are you using? This is an issue I've never heard of so I'm curious to see if there's any connection to any local influences

**Comment by Ikucuk** [comment]
My laptop is running W8.1 64bit with the latest chrome browser.
Specs:
Core i7 2.20Ghz (8 core)
16GB RAM

**Comment by benmcmahon100** [comment]
Okay so that's that ruled out. What challenge are you testing that on?

**Comment by Ikucuk** [comment]
Bonfire: Diff Two Arrays is the one that's been crashing for me all day, with all kinds of different code. So it's hard to pin it on something specifically.

**Comment by benmcmahon100** [comment]
That doesn't cause any issues for my Diff Two Arrays is solid for me! Do you have any extensions running?

**Comment by Ikucuk** [comment]
None that should really interfere, I'll work in an incognito window from now on, see if the issue returns, if not it will have been an extension. completely forgot about that.

**Comment by benmcmahon100** [comment]
Please do and if you had time to investigate if it's a certain extension we'd love to hear if there is an extension that may interfere with our code

**Comment by Ikucuk** [comment]
I'll certainly do some more in depth research on what plugin could cause it once I've established I experience no unexplained crashes in incognito.

**Comment by benmcmahon100** [comment]
Thanks for the help that's awesome!

**Comment by Ikucuk** [comment]
So far I have experienced no crashes in either incognito or normal mode. I'll have some time the coming two days to properly stress  test this a bit further.

**Comment by Ikucuk** [comment]
Ok, report time.
So far so good, no crashes whatsoever in incognito mode, which points to a plugin/extension issue.
I've started with disabling adblock on FCC, I haven't seen any ads being blocked to begin with, but it was first on the list. As of yet (48 hours) I have yet to experience ANY crashes. Whereas before I disabled adblock I'd have at least 2 every day or so.
