### ISSUE TITLE
Smallest common multiple is correct but returns incorrect

### ISSUE THREAD

**Issue by vickiemitchell** [freeCodeCamp/freeCodeCamp#13579]
Challenge [Smallest Common Multiple](https://www.freecodecamp.com/challenges/smallest-common-multiple#?solution=) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//nonprotect
function smallestCommons(arr) {
  //create a sorted array of values
  //set LCM and flag
  //LCM++ and check answer
  //if yes, throw flag return LCM
  
  var start = Math.min(arr[0],arr[1]),
      end = Math.max(arr[0],arr[1]),
      range = [];
  
  for (var i = start; i <= end; i++){
    range.push(i);
  }
  
  var LCM = 0,
      flag = true;
  
  while(flag){
    
    LCM++;
    
    for (var j = start; j <= end; j++){
      
      if (LCM % j !==0){
        break;
      }
      else if (j===end){
        flag = false;
      }
      
    }
    
  }
  
 return LCM;
  
}

smallestCommons([1,5]);

```

**Comment by JosephLivengood** [comment]
`//nonprotect` at the top should be `//noprotect` and then it works. 

Possibly we need to way to show this is the error when this happens? I was only able to tell when i plugged that test case into the code itself!

**Comment by raisedadead** [comment]
We do throw off an error when loopProtect catches and breaks the execution. But this is logged in console. 

Not sure, how we would move this to a notification.
