### ISSUE TITLE
[beta] Convert strings to url slugs failing 1 test?

### ISSUE THREAD

**Issue by rifkegribenes** [freeCodeCamp/freeCodeCamp#13578]
Challenge [apply-functional-programming-to-convert-strings-to-url-slugs](http://beta.freecodecamp.com/en/challenges/functional-programming/apply-functional-programming-to-convert-strings-to-url-slugs) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


// the global variable
var globalTitle = "Winter Is Coming";

// Add your code below this line
function urlSlug(title) {
  let slug = title.toLowerCase().split(/\s/).filter(function(i) {
             return i !== "";
             }).join("-");
  console.log(globalTitle);
  return slug;
  
}
// Add your code above this line

var winterComing = urlSlug(globalTitle); // Should be "winter-is-coming"

```
I'm getting a message that this is failing the first test ("The `globalTitle` variable should not change.") but when i print globalTitle to the console it looks unchanged to me?

**Comment by Ethan-Arrowood** [comment]
I'll be happy to give this a shot! Will comment soon after investigating 👍

**Comment by Ethan-Arrowood** [comment]
Please reset this challenge and try it again. I was able to get all tests to pass using your exact code.

**Comment by rifkegribenes** [comment]
that worked thanks! sorry i should have tried that first.
