### ISSUE TITLE
Test 2 on "Trigger Click Events with JavaScript" keeps failing

### ISSUE THREAD

**Issue by stephanmax** [freeCodeCamp/freeCodeCamp#13571]
Challenge [trigger-click-events-with-javascript](https://beta.freecodecamp.com/en/challenges/json-apis-and-ajax/trigger-click-events-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.

Please find my solution code attached. The second test `Your code should add an onclick event handler.` keeps failing although I can clearly see the debug text `Test` in the JS console.

```html
<script>
  document.addEventListener('DOMContentLoaded',function(){
    // Add your code below this line
    document.getElementById('getMessage').onclick = function() {
      console.log('Test');
    };
    // Add your code above this line
  });
</script>
…
```

**Comment by Ethan-Arrowood** [comment]
I'll look into this after class

**Comment by Ethan-Arrowood** [comment]
Issue is the test is expecting no space between the onclick and function keywords. I'll fix this tonight!

**Comment by Greenheart** [comment]
@Ethan-Arrowood Great work with the triaging!

May I suggest that you replace the second test with one checking for `typeof document.getElementById('getMessage').onclick === 'function'` rather than the regex-based one?

This way, we could allow arrow functions to be used as event handlers as well.

**Comment by Ethan-Arrowood** [comment]
Ooh I like that! Okay I'll give it a shot :)
