### ISSUE TITLE
Clicking on links when learning should open up a new tab

### ISSUE THREAD

**Issue by huangv22** [FreeCodeCamp/FreeCodeCamp#1357]
Current
* I am currently in the LEARN section
* As I go through it, I see links for me to click on.
* I click on it. I am directed to the page in the same tab

Expected
* change the href so that it opens a new tab target="_blank"

Reason
This enables me to save my place while being able to dive deeper into the content. Also, when I press back to go back, the checks that I've compelted weren't saved, so I had to recheck.

**Comment by ahstro** [comment]
Not using `target="_blank"` lets the user decide if they want to open the link in a new tab or not, where as, from what I understand, using it will cause the link to always open in a new tab. Letting the user decide how they want to open a link is seems to be the better option, in my opinion.

**Comment by BerkeleyTrue** [comment]
Which section is the learn section?

**Comment by benschenker** [comment]
Closing as stale, please reopen if you still have this issue.
