### ISSUE TITLE
Applied Responsive Web Design Projects: Build a Tribute Page youtube video not playing

### ISSUE THREAD

**Issue by AdannaGithub** [freeCodeCamp/freeCodeCamp#13575]
<img width="1095" alt="screen shot 2017-02-24 at 23 13 11" src="https://cloud.githubusercontent.com/assets/18629431/23324688/38e426a6-fae7-11e6-88e6-503e2dda242a.png">
Challenge [build-a-tribute-page](https://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The Youtube video does not play for this project and for all the other projects under "Applied Responsive Web Design Projects"

**Comment by vikramnr** [comment]
I also facing this issue. I have tried clearing cache memory and it still persists.

**Comment by raisedadead** [comment]
We are removing videos, these will be updated soon with images. Refer #12753
