### ISSUE TITLE
Typo in "HTML5 and CSS: Use Hex Code for Specific Colors"

### ISSUE THREAD

**Issue by eti8** [freeCodeCamp/freeCodeCamp#13581]
https://www.freecodecamp.com/challenges/use-hex-code-for-specific-colors

"Like decimals, the symbols 0-9 **represents** values zero to nine."

It should be "...symbols 0-9 **represent** values...", right?

Otherwise, congratulations for the tremendous work on the site.
This is very helpful.

**Comment by Greenheart** [comment]
@eti8 Thanks for reporting this!

Don't worry about the bot - we haven't taught it proper manners yet... :smile:

I think an alternative might be "...symbols 0-9 **represent the** values...". What do you think?

**Comment by eti8** [comment]
@Greenheart You're welcome.
It's the least I can do to show some gratefulness.

Yes, your alternative sounds even better.

**Comment by dhcodes** [comment]
First-timers only:
Here's the line to change per @Greenheart's recommendation: https://github.com/freeCodeCamp/freeCodeCamp/blob/c73bb44be92abaacb80deb327ff615b67c5b7317/seed/challenges/01-responsive-web-design/basic-css.json#L3124

**Comment by Greenheart** [comment]
@eti8 As you reported it, would you like to make an open source contribution and fix this? Me and other contributors would be happy to guide you through the process! :smile:

See the links @dhcodes posted above for more info.

**Comment by orvi2014** [comment]
Can I contribute on this ?

**Comment by Greenheart** [comment]
@orvi2014 Thanks for asking! :blush: If @eti8 doesn't want it, I'll ping you.

Meanwhile, see if you can find any issue you find interesting and mention me (`@Greenheart`) and I will help you get started :blush:

**Comment by eti8** [comment]
@Greenheart Yes, sure I'd be delighted to.

I'll go over the [free series](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github):
then the [contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md)
and come back to you when I'm ready.

Thanks for being available for guidance, I really appreciate it.

**Comment by bagzy** [comment]
Hi Guys, I am not seeing that issue. Has this one been resolved?

**Comment by eti8** [comment]
@Greenheart I went through the videos and over some of the guidelines.
I won't be able to contribute to this issue and fix it anytime soon.
Please feel free to assign/ping it to someone else (@orvi2014 or @bagzy or others).

Once trained and ready, I'll get back later this year to contribute to another issue/typo, I might spot as I'll progress through the tutorials.

Meanwhile, my best wishes to all, for their work and efforts.

**Comment by XXiphias** [comment]
It looks like someone has fixed this, changing `represents` to `represent` as was initially suggested.

**Comment by erictleung** [comment]
@XXiphias the change now incorporates the change with "the" to make it "represents **the** values..."

Whoever picks this might as well change the proceeding sentence as it is very similar to this issue.

```diff
- Then A,B,C,D,E,F represent values ten to fifteen.
+ Then A,B,C,D,E,F represent the values ten to fifteen.
```

**Comment by Greenheart** [comment]
@eti8 You're welcome when you're ready! We'll be around in the [Contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) if you want to get in touch in the future.

Thanks, and happy coding! :)

**Comment by homerrowsky** [comment]
Hi. Is this still open? It's my first time. I'm trying to get the modification @erictleung suggested (line 3124) done.

Saludos!!

**Comment by erictleung** [comment]
@homerrowsky yes, this is still open. Someone worked on it but referenced their own fork of the project rather than this main repository.

**Comment by oraikus** [comment]
If this isn't done by later tonight I'll go ahead and work on this if that's alright.
