### ISSUE TITLE
basic html

### ISSUE THREAD

**Issue by vignesh005** [freeCodeCamp/freeCodeCamp#13582]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%3Chtml%3E%0A%3Chead%3E%20%20%0A%3Cmarque%3E%3Ch1%3Etitle%3C%2Fh1%3E%3C%2Fmarque%3E%0A%3C%2Fhead%3E%0A%3Cbody%3E%20%20%0A%3Cbackground%3D%22name.%20extension%22%3E%0A%3Cp%3E%0Aany%20%0A%3Cp%3E%0A%3Cimgsrc%3D%22name.%20extension%22%3E%0A%20%20%3C%2Fbody%3E%0A%3C%2Fhtml%3E%20%20%0A%20%20%20%0A%20%20%20%0A%20%20%20%20%20%20%0A%0A%20%20%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<html>
<head>  
<marque><h1>title</h1></marque>
</head>
<body>  
<background="name. extension">
<p>
any 
<p>
<imgsrc="name. extension">
  </body>
</html>  
   
   
      

  

```

**Comment by cdrainxv** [comment]
@vignesh005: Your editor should not look like that. Please reset your code.

**Comment by texas2010** [comment]
@vignesh005 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
