### ISSUE TITLE
sumPrimes(10) shouldn't return 17.

### ISSUE THREAD

**Issue by avotg** [freeCodeCamp/freeCodeCamp#13585]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by donofriov** [comment]
Yes it should. This should be closed.

2 + 3 + 5 + 7 = 17

![image](https://cloud.githubusercontent.com/assets/4457953/23332975/2d7f657c-fb51-11e6-8fc5-8ce1f8786d26.png)

**Comment by avotg** [comment]
Sum all the prime numbers up to and* including the provided number*.

17 + 10 = 27

**Comment by donofriov** [comment]
10 is not a prime, 10 can be divided by 1, 2, 5, and 10.

**Comment by avotg** [comment]
The provided number may not be a prime.

**Comment by avotg** [comment]
doesn't that mean that we should sum up no matter what?

**Comment by dhcodes** [comment]
Sum all the **prime** numbers up to and* including...
