### ISSUE TITLE
[beta] Consider changing title for "JSON APIs and Ajax: Trigger Click Events with JavaScript"

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#13586]
Challenge [trigger-click-events-with-javascript](http://beta.freecodecamp.com/en/challenges/json-apis-and-ajax/trigger-click-events-with-javascript) has an issue.

As this challenge is about adding an `onclick` handler for a DOM element, I think the title of this challenge should be changed to "Handle Click Events with JavaScript with the onclick Property".

If this challenge were to cover the topic of triggering click events, it should cover `someDOMElement.click()` instead.

The challenge description could also further explain that the `onclick` property only is one way to handle click events in JS.

```html
<script>
  document.addEventListener('DOMContentLoaded',function(){
    // Add your code below this line
    document.getElementById('getMessage').onclick = event => {};
    
    // Add your code above this line
  });
</script>
<style>
  body {
    text-align: center;
    font-family: "Helvetica", sans-serif;
  }
  h1 {
    font-size: 2em;
    font-weight: bold;
  }
  .box {
    border-radius: 5px;
    background-color: #eee;
    padding: 20px 5px;
  }
  button {
    color: white;
    background-color: #4791d0;
    border-radius: 5px;
    border: 1px solid #4791d0;
    padding: 5px 10px 8px 10px;
  }
  button:hover {
    background-color: #0F5897;
    border: 1px solid #0F5897;
  }
</style>
<h1>Cat Photo Finder</h1> 
<p class="message box">
  The message will go here
</p>
<p>
  <button id="getMessage">
    Get Message
  </button>
</p>

```

**Comment by hay-dee** [comment]
@Greenheart can i propose the below changes to the description? I rephrased the portion on event handlers to hint that the "onclick" event handler is one of many. For the deletions, my intention is to reduce the information that the camper does not need to complete this particular challenge. This will help to prevent confusing the camper and allowing him to focus on learning one concept per challenge, as per the style guide. Any suggestions to help me improve the description is welcomed 😄 

**Challenge Description**:

~~This section covers how to get data from APIs. APIs - or Application Programming Interfaces - are tools that computers use to communicate with one another.~~ <-- mentioned in introduction. Also to prevent lengthy descriptions.

~~You'll learn how to update HTML with the data we get from these APIs using a technology called AJAX.~~ <-- shift to the Get JSON with the Javascript XMLHttpRequest Method challenge, where the camper constructs his first AJAX request.

You want your code to execute only once your page has finished loading. For that purpose, you can attach a JavaScript event to the document called DOMContentLoaded. Here's the code that does this:
<blockquote>
document.addEventListener('DOMContentLoaded',function() {
<br></br>
});
</blockquote>
You can implement event handlers that goes inside of the DOMContentLoaded function. You can implement the <code>onclick</code> event handler, which triggers when the user clicks on the element, by adding the following code:
<br></br>
<blockquote>
document.getElementById('getMessage').onclick=function(){};
</blockquote>

**Comment by Greenheart** [comment]
@hay-dee I'm so sorry for the delayed response, I've been pretty busy (starting a new job).

I like your suggestions, thanks for taking the time! Feel free to open a pull request, or talk to others about it in the chat rooms :blush:

**Comment by hay-dee** [comment]
@Greenheart Wow congratulations on your new job! No problems with the delay, i have submitted a PR to address the issue raised. You can review the PR when you have the time 😄
