### ISSUE TITLE
[beta][UX][enhancement] Issue with challenge

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13597]
http://beta.freecodecamp.com/en/challenges/basic-css/use-clockwise-notation-to-specify-the-padding-of-an-element
Basic CSS: Use Clockwise Notation to Specify the Padding of an Element

When the challenge begins there is a snippet of code `0px;`
That is not supposed to be in the "results" viewport of the phone template....
I cannot screenshot at the moment but a quick look at the page will show what I mean

**Comment by no-stack-dub-sack** [comment]
@tommygebru this is all I see in the phone at the start of the challenge:
![image](https://cloud.githubusercontent.com/assets/18563015/23343300/f99d4c06-fc36-11e6-9a85-38d152bd31e1.png)

**Comment by tommygebru** [comment]
it was outside (and above the yellow box) of the structured code also it showed up in dev tools 👍

**Comment by tommygebru** [comment]
@no-stack-dub-sack same issue with
Applied Accessibility: Standardize Times with the HTML5 Datetime Attribute
http://beta.freecodecamp.com/en/challenges/applied-accessibility/standardize-times-with-the-html5-datetime-attribute

**Comment by raisedadead** [comment]
Please provide screenshots to assist us better with your query.

**Comment by tommygebru** [comment]
@no-stack-dub-sack Is it possible I am seeing these issues because I have completed the preceding challenges?

**Comment by raisedadead** [comment]
Closing, as stale.
