### ISSUE TITLE
[beta] Minor code errors in many coding interview challenges

### ISSUE THREAD

**Issue by Kenneth-LJS** [freeCodeCamp/freeCodeCamp#13590]
#### Challenge Name

https://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/remove-from-a-set
https://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/perform-a-union-on-two-sets
https://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/perform-an-intersection-on-two-sets-of-data
https://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/perform-a-difference-on-two-sets-of-data
https://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/perform-a-subset-check-on-two-sets-of-data
https://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/removing-items-from-a-set-in-es6
https://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/using-has-and-size-on-an-es6-set
https://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/using-spread-and-notes-for-es5-set-integration
Many others...

#### Issue Description

Many of the challenges under Coding Interview Data Structure Questions have seed code with minor syntax errors, like missing/additional semicolons. These show up as warnings in the editor and don't look very nice:

![image](https://cloud.githubusercontent.com/assets/21071217/23331724/7f0a69fa-fba6-11e6-8e0f-36778e46cab3.png)

**Comment by vanessa-bell** [comment]
Typo in tests: http://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/perform-a-subset-check-on-two-sets-of-data the test should read 'Your Set class should have a *subset* method.' instead of union
