### ISSUE TITLE
YouTube video on Drum Machine project error

### ISSUE THREAD

**Issue by KenzoM** [freeCodeCamp/freeCodeCamp#13593]
Looks like there's an error on the YouTube video for the Drum Machine Challenge

#### Challenge Name
Front End Frameworks Projects: Build a Drum Machine

#### Browser Information

* Browser Name, Version:  Chrome 56
* Operating System: Macintosh; Intel Mac OS X 10_12_3
* Mobile, Desktop, or Tablet:  Desktop

#### Screenshot
<img width="1256" alt="screen shot 2017-02-25 at 9 17 29 am" src="https://cloud.githubusercontent.com/assets/10217112/23333163/b867bf74-fb3b-11e6-9e2e-3f2ae49f5774.png">

**Comment by dhcodes** [comment]
@KenzoM thanks for the issue. The project videos will be removed soon per https://github.com/freeCodeCamp/freeCodeCamp/issues/12753

Closing this a result.

**Comment by BhaveshSGupta** [comment]
@dhcodes As per #13730 I think the view of this needs to be changed too

**Comment by systimotic** [comment]
@BhaveshSGupta We're not changing the front end projects, the issue you linked is about the back end projects only.
