### ISSUE TITLE
doesn't pass test

### ISSUE THREAD

**Issue by dawpes** [freeCodeCamp/freeCodeCamp#13608]
Challenge [use-css-selectors-to-style-elements](http://beta.freecodecamp.com/en/challenges/basic-css/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html

<style>
h2  {color: blue;}
</style>
<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

**Comment by BhaveshSGupta** [comment]
This is a browser specific issue.

**Comment by OFFLlNE** [comment]
Thank you for reporting the issue.

Here are a couple suggestions:
1.Reload the page and run the tests again. A script may have crashed, preventing the tests from running.
2.Try the challenge in incognito mode. A plugin might be interfering with the tests.
3.Try the challenge in a different browser. There may be an issue with your version.
Please try these things in order and let us know what did and didn't work. I can't reproduce your issue right now, so any extra information will be helpful in finding out what's causing your issue.

**Comment by systimotic** [comment]
Hi @dawpes! Thank you for reporting this issue.

This is an issue with CSS tests in Firefox. The main issue is https://github.com/freeCodeCamp/freeCodeCamp/issues/10749 This is a big issue that affects a lot of people, so we are looking to resolve it soon. For now, you'll have to switch to Chrome for any challenges with CSS tests in the beta.

Thanks you for trying out the beta, and happy coding!

**Comment by heatherdhaz** [comment]
I am experiencing this issue as well. Is there a fix being worked on?
Here is the info....
Challenge [use-css-selectors-to-style-elements](http://beta.freecodecamp.com/en/challenges/basic-css/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.

**Comment by systimotic** [comment]
@heatherdhaz Hi! As mentioned, we're working on this in #10749
