### ISSUE TITLE
Error after completing all challenges.

### ISSUE THREAD

**Issue by dting** [FreeCodeCamp/FreeCodeCamp#1360]
I got this error 

![fccbug](https://cloud.githubusercontent.com/assets/394393/8849768/2a3e6276-30f7-11e5-9e1c-2893d34daa40.png)

after I submitted the last basejump. I submitted it again after some time and the error popped up again. The message is generic so I'm not sure what the cause could be. I did skip some of the waypoints. Could that be the problem?

These also remained locked.

![fccnonprofit](https://cloud.githubusercontent.com/assets/394393/8849861/db6396d4-30f7-11e5-8a79-161028925b19.png)

**Comment by dting** [comment]
Looking at the code this is intentional and not really an error. 

https://github.com/FreeCodeCamp/freecodecamp/blob/staging/server/boot/challenge.js#L142

**Comment by benschenker** [comment]
Closing as stale, please reopen if this is still an issue for you
