### ISSUE TITLE
[beta] Many code warnings in default challenge code

### ISSUE THREAD

**Issue by Kenneth-LJS** [freeCodeCamp/freeCodeCamp#13602]
#### Challenge Name

[Delete a Node with One Child in a Binary Search Tree](https://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/delete-a-node-with-one-child-in-a-binary-search-tree)
[Delete a Node with Two Children in a Binary Search Tree](https://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/delete-a-node-with-two-children-in-a-binary-search-tree)

#### Issue Description

These two challenges could use a clean up, as they have a lot of minor errors causing many editor warnings:

![image](https://cloud.githubusercontent.com/assets/21071217/23337020/f45a24f0-fc1b-11e6-9fda-93a3305567f2.png)

**Comment by QuincyLarson** [comment]
@Kenneth-LJS Wow - awesome work! QA'd and merged!

Would you be interested auditing the rest of the challenges and seeing whether there are any more style issues like these that can be fixed? I totally agree that these are something we should resolve before pushing these live.
