### ISSUE TITLE
BootstrapCDN link typo & Best Practice

### ISSUE THREAD

**Issue by dragancajic** [freeCodeCamp/freeCodeCamp#13610]
Challenge [Use Responsive Design with Bootstrap Fluid Containers](https://www.freecodecamp.com/challenges/use-responsive-design-with-bootstrap-fluid-containers) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:45.0) Gecko/20100101 Firefox/45.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

link with an issue is:
`<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>`

My code:
```html

<!DOCTYPE html>

<div class="container-fluid">

<title>Cat Photo App</title>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>

<!--
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
-->
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <label><input type="radio" name="indoor-outdoor"> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
  <br />
  <label><input type="checkbox" name="personality"> Loving</label>
  <label><input type="checkbox" name="personality"> Lazy</label>
  <label><input type="checkbox" name="personality"> Crazy</label>
  <br />
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>

</div>

```
<br />

01-bootstrapcdnLinkTypo.png
![01-bootstrapcdnlinktypo](https://cloud.githubusercontent.com/assets/24639417/23342075/13c59788-fc54-11e6-8b23-548e13d8c857.png)
<br />
02-catPhotoApp1.png
![02-catphotoapp1](https://cloud.githubusercontent.com/assets/24639417/23342076/13d2aea0-fc54-11e6-86df-0ae7eec0ae5f.png)
<br />
03-BootstrapCDNLink(s).png
![03-bootstrapcdnlink s](https://cloud.githubusercontent.com/assets/24639417/23342077/13deb2fe-fc54-11e6-8ffa-4616415cf093.png)
[Quick Start · BootstrapCDN by MaxCDN](https://www.bootstrapcdn.com/)
<br />
04a-linkTypoCorrected!.png
![04a-linktypocorrected](https://cloud.githubusercontent.com/assets/24639417/23342078/13ed279e-fc54-11e6-94fc-cffa001b4a56.png)
<br />
04b-linkTypoCorrected!.png
![04b-linktypocorrected](https://cloud.githubusercontent.com/assets/24639417/23342079/13fd30f8-fc54-11e6-976e-3cd803f9820a.png)
<br />
05-catPhotoApp2.png
![05-catphotoapp2](https://cloud.githubusercontent.com/assets/24639417/23342080/140f50da-fc54-11e6-90c6-8f54cfff4d18.png)
<br />
06-Subresource Integrity (SRI).png
![06-subresource integrity sri](https://cloud.githubusercontent.com/assets/24639417/23342081/14222fca-fc54-11e6-8364-3f92257b1566.png)
[Announcing SRI Hash Support for BootstrapCDN | MaxCDN](https://www.maxcdn.com/blog/bootstrapcdn-subresource-integrity/)
<br />
07-bestPractice.png
![07-bestpractice](https://cloud.githubusercontent.com/assets/24639417/23342082/14378172-fc54-11e6-83f2-f1e368f55e68.png)

**Comment by erictleung** [comment]
@dragancajic thanks for the issue! Two points for your issue.

> BootstrapCDN link typo...

The bootstrap CDN link was updated in the codebase recently with this merged PR https://github.com/freeCodeCamp/freeCodeCamp/pull/13570. It'll only some time until an update is pushed to the production site.

> ... & Best Practice 

Our curriculum, especially early on in the bootstrap section, doesn't teach best practices. It focuses on getting learners up and running with basic web development topics. Not very many beginners will know what a hash is, SHA256, or other specific jargon. This might be better for the new "Responsive Web Design Principles" section, in a forum wiki page, or within the new "Information Security" section.

cc/ @freeCodeCamp/moderators
