### ISSUE TITLE
[beta] possibly a change in instruction is needed for challenge

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13611]
http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-visual-balance-using-the-textalign-property
Applied Visual Design: Create Visual Balance Using the Text-align Property

The challenge works fine, its just that the instructions are a bit unclear, the challenge `requires the value "justify" but this is a new terminology `and it is not addressed in the instructions, this can be troublesome to new students...

**Comment by erictleung** [comment]
@tommygebru agreed. This section needs some love and describe what "justify" means in the context of paragraphs. This could include information on centering, left, and right justification. [This page](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align) might help in crafting a sufficient description of what you can do with `text-align`.

**Comment by donniereese** [comment]
I agree with @tommygebru. However, I also think that the handholding needs to be kept to a minimum and encourage research.  With that, MDN already has such a good catalog of information.  Could we leverage that in some way?  For instance, anytime an element is mentions, simply include a link where it is mentioned to the appropriate page in MDN?

Also, visual aids work well, too.

**Comment by adetime** [comment]
Hi @tommygebru, @erictleung, and @donniereese, 

I agree about the lack of information on justify. I see that @brennemo PR is fixing it.

However, I think that there is one more thing missed in that challenge. The final note says:

> When you align the two anchor tags, you will see no difference. This is `because text is aligned to the left by default`.

But, to be honest you are unable to see any change, even if you use text-align with other values as center, right, start, end...

So, I think that portion of the challenge needs to be changed. If we are unable to give any visual feedback in these anchor tags they need to be changed.

**Comment by systimotic** [comment]
@adetime Good catch! The aligning on the anchor tags should probably removed. As this is a different issue from the one originally reported here, can you open a new issue about this?
