### ISSUE TITLE
Profile Lookup issue

### ISSUE THREAD

**Issue by BigCCP** [freeCodeCamp/freeCodeCamp#13628]
Each if statement works on its own, but when I put them all together the function does not work anymore. Spent a bit of time squeezing my brain to find out what the problem is, so any advice would be very much appreciated. 

//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];

function lookUpProfile(firstName, prop){
// Only change code below this line
 for(var i = 0; i <= contacts.length; i++)
 {   
   if((contacts[i].firstName == firstName) && contacts[i].hasOwnProperty(prop))
     {
     return contacts[i][prop];   
     }
   else if (contacts[i].firstName != firstName)
   {
      return "No such contact";
   }
   else if((contacts[i].firstName == firstName) && !(contacts[i].hasOwnProperty(prop))) 
   {
     return "No such property"; 
   }   
   }
 
// Only change code above this line
}

// Change these values to test your
<img width="698" alt="capture" src="https://cloud.githubusercontent.com/assets/25615696/23377887/d839329a-fd31-11e6-97da-3975b8f34a2f.PNG">
 function
lookUpProfile("Akira", "likes");

**Comment by donofriov** [comment]
Hey @BigCCP -- GitHub is used for raising issues with freeCodeCamp, like if there are bugs in the challenges. Gitter is the best place to get help from fellow campers! I see you have an account over there already, so I'll send you a message with some help working through this. 

@members This can be closed.

**Comment by BlueLB84** [comment]
I am having a similar issue with this challenge.  Any suggestions to help with working through it?  Thank you.

**Comment by BigCCP** [comment]
Feel free to write to me on Gitter, and I will take a look at your code.

**Comment by BlueLB84** [comment]
Thank you for following up!  I was able to figure it out finally.  Just had to move a few things around.  I'll check out Gitter, haven't heard of it before now.
