### ISSUE TITLE
100% zoom issue

### ISSUE THREAD

**Issue by Xantherr** [freeCodeCamp/freeCodeCamp#13621]
![screenshot 76](https://cloud.githubusercontent.com/assets/26056758/23357339/68ad92e6-fd03-11e6-9f49-cd42f0cb44d2.png)

#### Challenge Name
https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%7B%0A%20%20%20%20font-size%3D16px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3E%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E

#### Issue Description
100% zoom issue even though it is on 100% zoom.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

<style>
  .red-text {
    color: red;
  }
  p{
    font-size=16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text"> class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```js



```

**Comment by Marmiz** [comment]
@Xantherr there's an error in your `p` style declaration.
Nothing to do with zoom at 100%.

Next time before assuming it's a bug, please consider asking for help in the official [help chat room](https://gitter.im/FreeCodeCamp/Help)

Happy coding 👍

**Comment by texas2010** [comment]
@Xantherr you got typo in code.

Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
