### ISSUE TITLE
JSON code has no effect (the call fails?)

### ISSUE THREAD

**Issue by marekjedlinski** [freeCodeCamp/freeCodeCamp#13622]
Challenge [Get JSON with the jQuery getJSON Method](https://www.freecodecamp.com/challenges/get-json-with-the-jquery-getjson-method) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Clicking the "Get message" button does nothing (the message doesn't change).** 

The button's onclick event is working, e.g this does execute:
` $(".message").html('Hi!');`
But the json code isn't, as if the call were not succeeding.

I can pass the challenge (ctrl+enter runs and accepts it), but if I then move on to the next challenge (Convert JSON Data to HTML), the same thing happens - the json code produces no efffect at all. 

Same results with Firefox 47 and Chrome 56.

My code:
```html

<script>
  $(document).ready(function() {

    $("#getMessage").on("click", function(){
      // Only change code below this line.
            $.getJSON("/json/cats.json", function(json) {
                 $(".message").html(JSON.stringify(json));
          });
      
      // Only change code above this line.
    });

  });
</script>

<div class="container-fluid">
  <div class = "row text-center">
    <h2>Cat Photo Finder</h2>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12 well message">
      The message will go here
    </div>
  </div>
  <div class = "row text-center">
    <div class = "col-xs-12">
      <button id = "getMessage" class = "btn btn-primary">
        Get Message
      </button>
    </div>
  </div>
</div>

```

**Comment by Ethan-Arrowood** [comment]
@marekjedlinski this is not a github issue. If you have questions regarding completing a challenge please ask in: https://gitter.im/FreeCodeCamp/Help 
Anyways, your issue is you have spaces between the keywords 'class' & 'id' and then the '=' sign and then the appropriate string.

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by marekjedlinski** [comment]
@Ethan-Arrowood The spaces around the equal sign are placed there by FCC. They may be ugly, and I do not use them myself, but they are _not_ invalid: 

- xhtml 1.0 strict: http://www.tranglos.com/files/validatethis.html
- html 4.01 strict: http://www.tranglos.com/files/validatethis401.html

Anyway, to clarify: the task provides a code snippet to be pasted. As-is, the code does not work (clicking the button has no effect). **But,** when you run the test, it checks out and the task is accepted. These two things contradict each other. If the code doesn't work in the "preview phone" app, then the tests should  fail., too. It seems that either the preview app is wrong, or the tests are wrong.

(@texas2010 No, I am not asking for help with my code. I am pointing out an inconsistency between the validation tests - which succeed - and the preview app, which fails).
