### ISSUE TITLE
Bonfile solutions on profile page should be private

### ISSUE THREAD

**Issue by Arthaey** [FreeCodeCamp/FreeCodeCamp#1362]
I was very surprised to see that my completed bonfire solutions show up for everyone to see on my profile page. Please make them private, or else make it *very* clear when you sign up and when you complete the first bonfire that your code will be publicly shown on your profile page.

**Comment by FFX01** [comment]
Why is this a bad thing? FreeCodeCamp is open source. Your code is supposed to be publicly viewable.

**Comment by Arthaey** [comment]
Several thoughts:

1. Just because FCC itself is open source, doesn't mean that every student wants their own solutions posted publicly.

2. There was no explanation of the fact that it would be public, so it was a surprise. Surprises that touch on privacy or personal content are not usually a good thing. ;)

3. There's also related issue #1179, where, as @nxiety also comments, the first pass solution gets saved, even if we later clean up or improve our solutions. If there's going to be a "permanent public record", I'm going to want to test my solution outside of FCC before running it now.

**Comment by CodeNonprofit** [comment]
There are plans to give you more control over this page in the very near future. Thanks for the feedback!

**Comment by Arthaey** [comment]
Excellent, glad to hear that! When it comes to user data, more control is always better. ;)

**Comment by rags4developer** [comment]
why do you want to make your solution private ?

**Comment by Arthaey** [comment]
Why do you want to force it to be public? :) 

I would feel a lot less strongly about this if there were more controls — deleting, editing, or updating with the latest passing solution (instead of the crappy first pass, as it is now). But @CodeNonprofit says that more control is coming, so I'm hoping that will settle things to everyone's satisfaction.

**Comment by saadanerdetbare** [comment]
maybe a bit OT in this thread but still  - a 'run tests' button next to a 'save solution' button would also be a step in the right way on this. I have several solutions saved where maybe only one line of code is changed because i was refactoring to try to make the code a bit better

**Comment by cristianvnica** [comment]
I believe it is interesting to see different pieces of code from different people, before they are being polished. It's our evolution.

**Comment by BerkeleyTrue** [comment]
Fixed. Challenges only display for the logged in user.

**Comment by Arthaey** [comment]
Thank you!
