### ISSUE TITLE
Codepen sign up link for other languages needs updating

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/freeCodeCamp#13638]
#### Challenge Name

"Get Set for our Responsive Web Design Projects" (but for other languages)

#### Issue Description

Similar to an [earlier issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/13630), Codepen's sign up page has changed and the sign-up link needs to be updated for the other languages.

#### Changes Proposed

[This line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/responsive-web-design-projects.json#L85), [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/responsive-web-design-projects.json#L126), and [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/responsive-web-design-projects.json#L173) need to be changed to

```
https://codepen.io/accounts/signup/user/free
```

**Comment by Marmiz** [comment]
I can take care of this if none steps forward :)

**Comment by sid-doshi** [comment]
I can handle this if @Marmiz  dosent mind.

**Comment by Marmiz** [comment]
At all! :)
Good luck and happy coding!

**Comment by sid-doshi** [comment]
thanks @Marmiz

**Comment by systimotic** [comment]
Closed in #13675
