### ISSUE TITLE
Simple Oauth solution

### ISSUE THREAD

**Issue by adi-ads** [FreeCodeCamp/freecodecamp#1363]
Hi all,

Oauth is hard using separate passports plugins for different providers doesn't seem like the best solution.
Looking at issues #973 & #133 amongst other FSS had faced these issues as well.

So we have build a auth server in node from ground up which works well with passport - Its called [connect](https://github.com/anvilresearch/connect).

FSS users will be able to use a lot many more providers by adding very simple configurations and without the need of any additional packages.

I would like to invite you guys to have a look at connect and ask me any questions you may have. Connect is open source as well and thus there is synergy there.

If you feel connect is something that can be used with FSS will be happy to submit a PR.

Cheers
Adi

**Comment by BerkeleyTrue** [comment]
@adi-ads Thanks for letting me know about this. 

While it looks like a cool project, we will not be moving away from passport anytime soon.

I would also suggest changing the name as `connect` is a well established node module that has been around longer then express.

P.S. Not sure what FSS is? Did you mean FCC(Free Code Camp)?

**Comment by adi-ads** [comment]
m real bad with abbreviations, meant FCC. 

We are looking into other names as well :)

Connect works with passport only underneath, just adds a layer on top for consistent and easy Oauth support.

Let us know if you guys ever want to chat about authentication in general have quite a few experts in the organisation. And we are always looking at opensource projects that help the community.
