### ISSUE TITLE
"Diff Two Arrays" Should Test Multiple Identical Values

### ISSUE THREAD

**Issue by dwrz** [freeCodeCamp/freeCodeCamp#13636]
I think I managed to kludge my way through this challenge, because the tests are too lax. 

I've tested this on the Beta site, and the bug seems to exist there, too. This is despite the beta site's recent update (see: https://github.com/freeCodeCamp/freeCodeCamp/issues/13556).

The following program passes all the current tests on the challenge. However, if multiple identical values are included in the array, the program fails to return an accurate symmetric difference.

There should be a test that includes an identical value multiple times in an array.

This test breaks my program:
diffArray([1, 2, 3, 5], [**1, 1,** 2, 3, 4, 5]);

None of the current tests do, however.

Challenge [Diff Two Arrays](https://www.freecodecamp.com/challenges/diff-two-arrays#?solution=%0Afunction%20diffArray(arr1%2C%20arr2)%20%7B%0A%20%20%0Avar%20testArr%20%3D%20arr1.concat(arr2)%3B%0Avar%20finalArr%20%3D%20%5B%5D%3B%0A%20%20%0AtestArr.sort()%3B%0A%20%20%0Afor%20(i%20%3D%200%3B%20i%20%3C%20testArr.length%3B%20i%2B%2B)%20%7B%0A%20%20%0A%20%20if%20(testArr%5Bi%5D%20!%3D%20testArr%5Bi%20%2B%201%5D)%20%7B%0A%20%20%20%20%0A%20%20%20%20finalArr.push(testArr%5Bi%5D)%3B%0A%20%20%20%20%0A%20%20%7D%20else%20if%20(testArr%5Bi%5D%20%3D%3D%3D%20testArr%5Bi%20%2B%201%5D)%20%7B%0A%20%20%20%20%0A%20%20%20%20i%2B%2B%3B%0A%20%20%20%20%0A%20%20%7D%0A%7D%0A%20%20console.log(finalArr)%3B%0A%20%20return%20finalArr%3B%0A%7D%0A%0AdiffArray(%5B1%2C%202%2C%202%2C%203%2C%205%5D%2C%20%5B1%2C%201%2C%201%2C%202%2C%203%2C%204%2C%205%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function diffArray(arr1, arr2) {
  
var testArr = arr1.concat(arr2);
var finalArr = [];
  
testArr.sort();
  
for (i = 0; i < testArr.length; i++) {
  
  if (testArr[i] !== testArr[i + 1]) {
    
    finalArr.push(testArr[i]);
    
  } else {
    
    i++;
    
  }
}
  console.log(finalArr);
  return finalArr;
}

diffArray([1, 2, 3, 5], [1, 1, 2, 3, 4, 5]);

```

**Comment by dwrz** [comment]
I still don't feel very comfortable with my solution, but perhaps I'm wrong here.

http://math.stackexchange.com/questions/934378/why-cant-a-set-have-two-elements-of-the-same-value

Seems to suggest that a set with multiple items of the same element would condense to just one item for that element.

Maybe my math is not up to par -- apologies if that's the case.

**Comment by erictleung** [comment]
@dwrz thanks for the issue. So in the strictest sense, `[1, 1, 2, 3]` is not a set because a set only contains unique values, unless a multiset, as you have pointed out. So having to check multiple values would not really be doing a symmetric difference between two "sets". 

For this challenge, I think it's sufficient for what it is currently asking for. It is pretty defined and requires quite a bit of critical thinking. I'm all for adding more tests to better cover edge cases, but in case, I think asking to account for multiple values is unnecessary for this challenge.

I'll leave this open for others to chime in.

**Comment by dwrz** [comment]
Sorry for the late reply, and thanks for looking into this.

I think if I'm the only one who wasn't sure about this, then perhaps it might be more sensible not to mention anything, as it might just become a source of confusion. Standard set is probably the sensible default. 

For anyone looking for further reference, this might also be useful: http://pythonhosted.org/multiset/.

**Comment by DougLefelhocz** [comment]
I wrote a similar sort of solution in that it two elements come from the same array, neither would appear in the return value:

`function countNum(arr, elem) /* Counts the number of times an element appears in an array */ {
  var counter = 0;
  for (var i = 0; i < arr.length; i++) {
       if (arr[i] === elem) {
    counter += 1;
  }
       }
  return counter
}
/*

*/
function diffArray(arr1, arr2) /* Returns the symmetric difference of two arrays. */ {
  var union = arr1.concat(arr2);
  var diffArr = []
  for (var i = 0; i < union.length; i++) {
    if (countNum(union, union[i]) < 2) {
      diffArr.push(union[i])
    }
  }
  return diffArr
  }`

If the arrays work like sets for this problem, then [1, 1, 2, 3] collapses to [1, 2, 3] (and there's no sense in counting how many times an element appears in a set), so diffArray([1, 1, 2, 3], [3, 4]) should yield [1, 2, 4] according to the problem description.  But, my code would yield [2, 4].  I wrote a few tests of my own, but didn't realize it as an edge case, and I've only realized such an edge case after writing the code.
