### ISSUE TITLE
[beta][ui][enhancement] remove hint button

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13633]
some challenges have a hint button.. I constantly hit the hint button instead of submit and spend too much time reviewing correct code for possible errors...

If I recall correctly javascript challenges have external links to MDN to explain new coding concepts and terminology....

We should consider doing the same with the basic HTML and CSS sections of the FCC curriculum, I dont think hints are a great use of the notification system and interrupt the _normal_ user interface

Perhaps some challenges can be redirected to W3Schools?

**Comment by no-stack-dub-sack** [comment]
@tommygebru If I'm not mistaken, in beta, we are trying to eliminate outside links as much as possible, and so the hints are a good alternative. The general idea here is not to distract campers from the curriculum and at the same time, enforce the good habit of researching things on your own - a must have habit for every developer. So not sure that adding extra external links will be the best solution. 

Also, the information on W3Schools is often incorrect or out of date, and while they are often the top search result, they are not the most reputable.

**Comment by raisedadead** [comment]
We have a separate issue for implementation of Hint mechanism. I am closing this because we are not doing away with the hints for foreseeable future.

Thanks and happy coding!
