### ISSUE TITLE
Codepen signup link leads to 404 error

### ISSUE THREAD

**Issue by Lexis9784** [freeCodeCamp/freeCodeCamp#13630]
#### Challenge Name
Applied Responsive Web Design Projects --> Get set for our responsive web design projects

#### Issue Description

Link to codepen free signup page leads to a 404 (page not found) error. Should be linked to "https://codepen.io/accounts/signup/user/free"

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```

**Comment by donofriov** [comment]
@Lexis9784 Looks like CodePen updated their URL so the old one was in FCC. I have an open fix for it now, just waiting on sign off. Good find!
