### ISSUE TITLE
Waypoint 9 - regular expressions - buggy tutorial

### ISSUE THREAD

**Issue by rags4developer** [FreeCodeCamp/FreeCodeCamp#1364]
Waypoint 9 - regular expressions
RegexOne - The lessons are so buggy
http://regexone.com/lesson/5?
wrong answer to pass the test - [A-C]
correct answer - All the characters are sequential, so you can use the different ranges in the expression '[A-c][n-p][a-c]' to match only the first three lines.

Also, the question does not tell you what you are expected to do -
There is a pattern in each of the letters below, so try and write a regular expression using the range notation above to match and skip any of the string as necessary. Be aware that patterns are case sensitive and a-z differs from A-Z in terms of the characters it matches (lower vs upper case).

What pattern ???

**Comment by benschenker** [comment]
Thanks @rags4developer for reporting this. We don't actually use regexone anymore so this should be all fixed!

Closing
