### ISSUE TITLE
[beta] create-texture-by-adding-a-subtle-pattern-as-a-background-image

### ISSUE THREAD

**Issue by Barterr** [freeCodeCamp/freeCodeCamp#13646]
The tests are not recognizing it as right in either Firefox or Chrome, the code is below. I can see the pattern being applied in the preview so it should be right. Am I doing something wrong? If not it's a bug.

Challenge [create-texture-by-adding-a-subtle-pattern-as-a-background-image](http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-texture-by-adding-a-subtle-pattern-as-a-background-image) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  body {
    background: url(https://i.imgur.com/MJAkxbh.png)
  }
</style>

```

**Comment by Ethan-Arrowood** [comment]
Looking into this now. Will get back to you shortly :)

**Comment by Ethan-Arrowood** [comment]
No issue here, the url function requires you enter the url as a string. 
background: url('https://i.imgur.com/MJAkxbh.png')
Will solve the problem and complete the tests.

**Comment by erictleung** [comment]
@Barterr thanks for the issue, but as @Ethan-Arrowood has pointed out, you need quotes around the URL. This is also mentioned in the instructions

> The link address is wrapped in quotes inside the parentheses.

Closing as non-issue. Happy coding!

**Comment by Barterr** [comment]
Ohh of course, my bad, sorry about that :)

**Comment by marekjedlinski** [comment]
Still, there is a problem. If there is a space character between the paren and the quote (on either side), the test fails. It shouldn't fail. because having a space there is not an error:

this works (in Chrome):
`background: url('https://i.imgur.com/MJAkxbh.png');`

this fails  (in Chrome):
`background: url( 'https://i.imgur.com/MJAkxbh.png' );`
