### ISSUE TITLE
The cat picture links are not rendering in either Firefox or Safari even if I specify the URL in my address bar.

### ISSUE THREAD

**Issue by RufusVS** [freeCodeCamp/freeCodeCamp#13655]
The cat picture links are not rendering in either Firefox or Safari even if I specify the URL in my address bar.

From my current lesson: challenges/use-the-bootstrap-grid-to-put-elements-side-by-side
```
 <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>

  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">

```

**Comment by cameren75** [comment]
I'm having the same problem.

**Comment by BhaveshSGupta** [comment]
@RufusVS actually this bit.ly link expands to https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg, If you might be not aware amazon s3 server are down due to some glitch. website http://www.isitdownrightnow.com/ is also down right now :D please wait for some time as soon as amazon is up this would be up.

**Comment by systimotic** [comment]
Thanks for reporting this issue! We're aware of this. See https://github.com/freeCodeCamp/freeCodeCamp/issues/13653#issuecomment-283146682 for more details. I'm closing this as a duplicate.

**Comment by systimotic** [comment]
**Update at 1:12 PM PST** from the AWS status page. Everything should be back to normal for us!
After refreshing your browser, images should load again. If not, please clear your cache and try again.

**Comment by systimotic** [comment]
Update at 1:12 PM PST from the AWS status page. Everything should be back to normal for us!
After refreshing your browser, images should load again. If not, please clear your cache and try again.
