### ISSUE TITLE
Instructions unclear or expected answer incorrect

### ISSUE THREAD

**Issue by Philosophist** [FreeCodeCamp/FreeCodeCamp#1365]
Challenge http://www.freecodecamp.com/challenges/bonfire-truncate-a-string has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The instructions say to truncate a string, but the test example expects "A-tisket a-tasket..." with num = 11 to be cut off "deeply equal to" "A-tisket..." when the exact cut off at 11 would give the string "A-tisket a-...". Either the latter should be the correct solution or the expectation of the former should be explained more clearly in the instructions.

**Comment by benschenker** [comment]
this is fixed, the description now says: `Note that the three dots at the end add to the string length.`
