### ISSUE TITLE
Unused npm package "clipboard" should be removed.

### ISSUE THREAD

**Issue by atjonathan** [freeCodeCamp/freeCodeCamp#13659]
**To First Timer:**
You will need to remove [this](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/package.json#L44) line. Please, check our [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and if you need any assistance reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/HelpContributors).

> **Note:** You can only submit a pull request for this issue if you are new and haven't submitted one before. Hence the issue label `first-timers-only` :stuck_out_tongue_winking_eye:

**Comment by fonsecapontes** [comment]
Ok, I do this.
