### ISSUE TITLE
[beta] 404 error for external link

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13662]
http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/get-set-for-our-responsive-web-design-projects

The button "Open link in new tab(this unlocks the next step)"
has a 404 destination

**Comment by erictleung** [comment]
@tommygebru thanks for the issue. This has been fixed in `staging` with this recent PR https://github.com/freeCodeCamp/freeCodeCamp/pull/13634. Closing as resolved in staging. Happy coding!
