### ISSUE TITLE
Codepen sign-up URL 404 error

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#13668]
#### Issue Description

The link to Codepen sign-up form (https://codepen.io/signup/free) leads to a 404 (both in live and beta). The actual URL to the sign-up form is https://codepen.io/accounts/signup/user/free

**Comment by Manish-Giri** [comment]
@kevcomedia It's already been [taken care of](https://github.com/freeCodeCamp/freeCodeCamp/pull/13634)!

**Comment by kevcomedia** [comment]
Oh, I forgot to look up closed PRs. I guess this issue can now be closed.

**Comment by erictleung** [comment]
Closing as resolved. Happy coding!
