### ISSUE TITLE
[beta][UI][UX][enhancement] new bonus section in the instructions panel of Css flexbox lessons

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13661]
Im sorry to bring up this issue again but it seems that freecodecamp is encouraging students to become familar with flexbox on Freecodecamp's website...

The problem with that is that I would have to Run the challenge over 5 times and close the Toast Modal Window the same amount of times....

Seems like a poor UX choice and a confusing one as well, I think the notification needs to be revised or we can provide external links...

If the Toast Modal was removed this would provide an easier way for all students of all skill levels in all lessons and challenges that freecodecamp offers, to appreciate and "play" with lessons.

Lets revise the notification system to incorporate the job of the Toast Modal, which it technically already does with this message...
"Your Next Challenge Has Arrived"

**Comment by Greenheart** [comment]
@tommygebru Interesting thoughts, this could certainly be discussed as it's a big part of how campers experience working through the challenges.

Where did you discuss this earlier? Any issue? Forum? Gitter? Could be useful as a reference.

The current modal is a great way to show that the challenge is completed - but at the same time it might be disturbing as it doesn't exactly encourage experimentation **and deeper learning**

**Comment by tommygebru** [comment]
exactly @Greenheart its entirely confusing and not a great experience as i rework the curriculum
another thing I would like to bring up is the codepen test suite, while the intention and innovation is absolutely amazing... the codepen experience is not great, the refresh rate is separate from the codepen, and it feels slower on my older computer

**Comment by Greenheart** [comment]
@tommygebru I think your other point would be well suited in https://github.com/freeCodeCamp/testable-projects-fcc
