### ISSUE TITLE
Manipulating Complex Objects - Confused/Bug

### ISSUE THREAD

**Issue by Barterr** [freeCodeCamp/freeCodeCamp#13670]
I don't understand why my code isn't passing.
The only test that isn't passing is: After updateRecords(2548, "artist", ""), artist should not be set
I tried it locally and the collection returned is exactly the same as the collectionCopy, the artist of 2548 (Bon Jovi) was not set to "", it is still the same value after running. Isn't this what was asked for?

Challenge [Record Collection](https://www.freecodecamp.com/challenges/record-collection#?solution=%0A%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%20%222548%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20%22artist%22%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%222468%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%221999%22%2C%0A%20%20%20%20%20%20%22artist%22%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%221245%22%3A%20%7B%0A%20%20%20%20%20%20%22artist%22%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%225439%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20updateRecords(id%2C%20prop%2C%20value)%20%7B%0A%20%20var%20col%20%3D%20collection%5Bid%5D%3B%0A%20%20if%20(prop%20%3D%3D%20%22tracks%22)%20%7B%0A%20%20%20%20if%20(value%20%3D%3D%3D%20%22%22)%20%7B%0A%20%20%20%20%20%20delete%20col%5Bprop%5D%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20if%20(col.hasOwnProperty(prop))%20%7B%0A%20%20%20%20%20%20%20%20col%5Bprop%5D.push(value)%3B%0A%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20var%20tracks%20%3D%20%5B%5D%3B%0A%20%20%20%20%20%20%20%20col%5Bprop%5D%20%3D%20tracks%3B%0A%20%20%20%20%20%20%20%20col%5Bprop%5D.push(value)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%20else%20%7B%0A%20%20%20%20if%20(value%20!%3D%3D%20%22%22)%20%7B%0A%20%20%20%20%20%20collection%5Bid%5D%5Bprop%5D%20%3D%20value%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20collection%3B%0A%7D%0A%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0AupdateRecords(5439%2C%20%22artist%22%2C%20%22ABBA%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  var col = collection[id];
  if (prop == "tracks") {
    if (value === "") {
      delete col[prop];
    } else {
      if (col.hasOwnProperty(prop)) {
        col[prop].push(value);
      } else {
        var tracks = [];
        col[prop] = tracks;
        col[prop].push(value);
      }
    }
  } else {
    if (value !== "") {
      collection[id][prop] = value;
    }
  }
  return collection;
}


// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");


```

**Comment by XXiphias** [comment]
I believe this is a new check that was added recently. Your code does not meet that test. 

As per your code:
```
if (prop == "tracks") {
    ...
} else {
    if (value !== "") {
      collection[id][prop] = value;
    }
}
```
If the prop is `artist` and the `value == ""` your code does not do anything. Try adding an else to that if statement and you should be able to fix it.

**Comment by Barterr** [comment]
But isn't that what the test is asking for? To not do anything if it's artist and blank?

**Comment by Barterr** [comment]
Oh ok I got it now. I misunderstood this line:
If value is empty (""), delete the given prop property from the album.

Thought it was only when prop is "tracks" because of it being right after tracks stuff I guess, but it's supposed to be in all cases.

Thanks
