### ISSUE TITLE
[beta] Basic JavaScript: Passing Values to Functions with Arguments

### ISSUE THREAD

**Issue by manwithgills** [freeCodeCamp/freeCodeCamp#13677]
Challenge [passing-values-to-functions-with-arguments](http://beta.freecodecamp.com/en/challenges/basic-javascript/passing-values-to-functions-with-arguments) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


// Example
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.

function functionWithArgs(x, y){
  console.log(x + y);
}
functionWithArgs(7, 9);

```

The console in the browser logs the correct answer but the test in the dev console is not recognizing the function even if I change the params in the newly written and called function.

**Comment by Ethan-Arrowood** [comment]
I'll look into this and get back to you.

**Comment by Ethan-Arrowood** [comment]
Similar to your last issue. Everything works fine when I copy and paste your code into my browser. I'd recommend clearing cache & cookies and doing a hard refresh. Thank you!

**Comment by Greenheart** [comment]
@manwithgills Thanks for reporting this!

Do you mean that the freeCodeCamp console doesn't show info correctly, like in the screenshot below?
![console](https://cloud.githubusercontent.com/assets/6125097/23465294/1e2ba578-fe98-11e6-9e90-cdd65cdd77ba.png)

I think I've seen this issue before somewhere, but I don't know the status on fixing it.

**Comment by manwithgills** [comment]
I will hard reset when I get back home and see if this corrects the issue.

Thanks,
Chris

**Comment by ThomasBergman1987** [comment]
```
// Example
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.

functionWithArgs (a, b) {
  console.log(a + b);
};
functionWithArgs(3, 5);
```

What's wrong with my solution?

Thank you in advance for any response.
