### ISSUE TITLE
Use TogetherJS for in-browser pair program.

### ISSUE THREAD

**Issue by ahstro** [FreeCodeCamp/freecodecamp#1367]
I remember reading somewhere that freeCodeCamp wanted to eventually leave Screenhero and similar alternatives behind and create an in-browser pair programming experience. Well, I just found [Mozilla's TogetherJS](https://togetherjs.com/) library, which honestly seems like a perfect fit.

It's as simple as adding `<script src="https://togetherjs.com/togetherjs-min.js"></script>` to the relevant pages (I assume everything in `view/coursewares`) and add `TogetherJS(this);` to the `i-want-to-pair` button's on-click code. When clicking "Pair", the user will get a link to send to whoever they want to pair with, and they'll open up a WebRTC connection which allows for multi-user input as well as text and audio chat.

I'm in a new environment, and I'm having trouble setting up MongoDB, so I can't test any code right now, but if no one beats me to it, I will submit a PR when my dev environment is working properly.

P.S. Mozilla made a few [cute](https://www.youtube.com/watch?v=hJEq4W0FZQ0) [videos](https://www.youtube.com/watch?v=4cqyEhhL15Q) explaining how TogtherJS works.

P.P.S. The UI doesn't really fit with freeCodeCamp's style, but since TogetherJS is [open source](https://github.com/mozilla/togetherjs), we could (probably) easily rectify that.

**Comment by BerkeleyTrue** [comment]
@ahstro TogetherJS is something we evaluated early on. Unfortunately, it is no longer in active development by Mozilla. (see: http://www.i-programmer.info/news/81-web-general/7768-mozilla-labs-closed-and-nobody-noticed.html) There where other reasons that I cannot recall at the moment. It did inspire us.

We do have plans in the works that depends on other things getting implemented first. The first is fully reactifying FCC (Will happen in stages). 

Then it goes > creating in browser live chat per bonfire (requires us to implement socket servers and some sort of replication algorithm to be figured out). After that we will start finding an appropriate editor that can handle live editing over the wire. There are a lot of steps but rest assured we will get there.

**Comment by ahstro** [comment]
Oh, that's a bummer, it seemed like it was created for FCC. I guess I'll close this then.
