### ISSUE TITLE
Tribute Page Challenge Issue

### ISSUE THREAD

**Issue by Russellmania91** [freeCodeCamp/freeCodeCamp#13674]
In the Pen settings under CSS, when I try to add Bootstrap the link given in the example Tribute Page made by Quincy Larson is significantly different from the link that appears when I click "bootstrap" under Quick-add.  Is this just an updated version? I've noted there are some small differences in how it affects the final product.

![screen shot 2017-02-28 at 10 31 40 pm](https://cloud.githubusercontent.com/assets/25317008/23448570/a6a504d6-fe06-11e6-8fd9-4388f873bcbf.png)

**Comment by XXiphias** [comment]
Yes, codepen recently updated their Bootstrap quick add to include the new beta of Bootstrap, v4.0.0. I have noticed in the help channels that some users have had issues using the new version of Bootstrap so I suggest you manually use the link to the old version, 3.3.5.

**Comment by Ethan-Arrowood** [comment]
This isn't really an github issue. This would be better discussed in the Gitter help channel or on the forums. @Russellmania91 if you could close this issue it would be much appreciated! I'll also let the mods know so they can close this as well.

**Comment by texas2010** [comment]
Codepen issue has nothing with freeCodeCamp site.

Happy Coding.

**Comment by Russellmania91** [comment]
Thank you for your help guys.  Sorry for asking in the wrong place. Will ask in Gutter help channel or forum next time.

**Comment by texas2010** [comment]
@Russellmania91 No problem.
