### ISSUE TITLE
[beta] Information Security & Quality Assurance section -not working

### ISSUE THREAD

**Issue by KenzoM** [freeCodeCamp/freeCodeCamp#13683]
Not sure if this has been issued already, but looking at the `Information Security & Quality Assurance section`, nothing seems to be working.

Perhaps someone is already working on adding the tests for this section?

**Comment by raisedadead** [comment]
@Greenheart FYI

**Comment by Greenheart** [comment]
@raisedadead It was a while since I worked on this section. I think @Em-Ant or @JosephLivengood knows this better :blush:

**Comment by raisedadead** [comment]
Thanks for guiding.

**Comment by Em-Ant** [comment]
I'll check it this evening  (CET time) or tomorrow, and I'll let you know...

**Comment by Em-Ant** [comment]
I tried the first challenge and it's working. @KenzoM what url did you put in the input form ?
You have to put there not the boilerplate url (e.g. https://gomix.com/#!/project/your-project/) but the 'show live' url , i.e. https://your-project.gomix.me/. 

@Greenheart  maybe we need to explain this better...
