### ISSUE TITLE
Deadlink needs to be updated 3/1/2017 PST @ 4:39PM PST

### ISSUE THREAD

**Issue by chrisscotthall** [freeCodeCamp/freeCodeCamp#13686]
#### Challenge Name
https://www.freecodecamp.com/challenges/get-set-for-our-front-end-development-projects

#### Issue Description
Link: https://www.freecodecamp.com/challenges/get-set-for-our-front-end-development-projects on (4/7) needs to updated to https://codepen.io/accounts/signup/user/free

#### Browser Information

* Browser Name, Version: Firefox 
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
N/A

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/18416204/23487629/2d9ec6f8-fe9c-11e6-8234-0f81bac4a550.png)
![image](https://cloud.githubusercontent.com/assets/18416204/23487634/382dfbc0-fe9c-11e6-9269-fedbf5138fe5.png)

**Comment by erictleung** [comment]
@chrisscotthall thanks for the issue. I'm making a PR to fix this now.

**Comment by schas002** [comment]
^^^ Hmm, shouldn't the issue be closed...?
