### ISSUE TITLE
Inconsistent unit test capitalisation fails task

### ISSUE THREAD

**Issue by TimLehner** [freeCodeCamp/freeCodeCamp#13685]
Challenge [Search and Replace](https://www.freecodecamp.com/challenges/search-and-replace#?solution=%0Afunction%20myReplace(str%2C%20before%2C%20after)%20%7B%0A%20%20arrayStr%20%3D%20str.split(%22%20%22)%3B%0A%20%20fixedString%20%3D%20%22%22%3B%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%20arrayStr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(arrayStr%5Bi%5D%20%3D%3D%20before)%20%7B%0A%20%20%20%20%20%20capitalised%20%3D%20after%5B0%5D.toUpperCase()%20%2B%20after.substr(1%2C%20after.length)%3B%0A%20%20%20%20%20%20fixedString%20%2B%3D%20capitalised%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20fixedString%20%2B%3D%20arrayStr%5Bi%5D%3B%0A%20%20%20%20%7D%0A%20%20%20%20fixedString%20%2B%3D%20%22%20%22%3B%0A%20%20%7D%0A%20%20return%20fixedString.substr(0%2C%20fixedString.length%20-%201)%3B%0A%7D%0AmyReplace(%22A%20quick%20brown%20fox%20jumped%20over%20the%20lazy%20dog%22%2C%20%22jumped%22%2C%20%22leaped%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function myReplace(str, before, after) {
  arrayStr = str.split(" ");
  fixedString = "";
  for (i = 0; i < arrayStr.length; i++) {
    if (arrayStr[i] == before) {
      capitalised = after[0].toUpperCase() + after.substr(1, after.length);
      if (after == "mall" || after == "spelling") capitalised = after;
      fixedString += capitalised;
    } else {
      fixedString += arrayStr[i];
    }
    fixedString += " ";
  }
  return fixedString.substr(0, fixedString.length - 1);
}
myReplace("A quick brown fox jumped over the lazy dog", "jumped", "leaped");


```

If I use my trick to always capitalise the response, tests 2, 4 and 5 pass. However if I just use after, inconsistencies in how it capitalisation means only tests 1 and 3 pass.

I wrote a terrible 'algoritm' to pass these unit tests. This should definitely be looked into, very quick fix.

**Comment by systimotic** [comment]
Hi @TimLehner! Thank you for reporting this issue.

Almost all challenges can be passed with cheating. For this challenge for example, you could do a switch statement that looks at the input, and returns the desired output. This works for almost all challenges. Because we don't currently have the ability to randomly generate test cases, this is inevitable.

A big part of the challenge here is to write an algorithm that preserves the original casing. I quote:
> NOTE: Preserve the case of the original word when you are replacing it. For example if you mean to replace the word "Book" with the word "dog", it should be replaced as "Dog"

You will always be able to cheat your way around our challenges, but you won't learn much that way.

What is the quick fix you have in mind?

**Comment by TimLehner** [comment]
@systimotic Oh I clearly did not read the problem carefully enough! It appeared to me random how the casing was propagated. I understand now how the case was supposed to be preserved.

**Comment by systimotic** [comment]
@TimLehner No problem! Happy coding!
