### ISSUE TITLE
I had to escape the escape on the brackets

### ISSUE THREAD

**Issue by Semisuperman** [freeCodeCamp/freeCodeCamp#13693]
Challenge [Validate US Telephone Numbers](https://www.freecodecamp.com/challenges/validate-us-telephone-numbers#?solution=%0Afunction%20telephoneCheck(str)%20%7B%0A%20%20%0A%20%20%2F%2F%20Good%20luck!%0A%20%20var%20rex%20%3D%20new%20RegExp(%22%5E(1%20%7C1)%3F(%5C%5C((%5B0-9%5D)%7B3%7D%5C%5C)%7C(%5B0-9%5D)%7B3%7D)%7B1%7D(-%7C%20)%3F(%5B0-9%5D)%7B3%7D(-%7C%20)%3F(%5B0-9%5D)%7B4%7D%24%22)%3B%0A%0A%20%20%2F%2Fconsole.log(str.match(rex))%3B%0A%20%20return%20rex.test(str)%3B%0A%20%20%0A%7D%0A%0A%0A%0AtelephoneCheck(%221%20(555)%20555-5555%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function telephoneCheck(str) {
  
  // Good luck!
  var rex = new RegExp("^(1 |1)?(\\(([0-9]){3}\\)|([0-9]){3}){1}(-| )?([0-9]){3}(-| )?([0-9]){4}$");

  //console.log(str.match(rex));
  return rex.test(str);
  
}



telephoneCheck("1 (555) 555-5555");

```

**Comment by harvinderathwal** [comment]
If you're having issues with your code please discuss in the forum or Gitter. This challenge works fine on my end so try hard refreshing your browser (or switching browsers entirely).

**Comment by raisedadead** [comment]
@Semisuperman thanks for the report, but that's too little information for us to proceed. Can you clarify what exactly is your issue.

**Comment by raisedadead** [comment]
Please clarify as requested
