### ISSUE TITLE
[beta] Client and server rendering difference

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/freeCodeCamp#13698]
While reviewing #13618, I noticed a weird inconsistency between how the client and server render the challenge description.

### Client rendered
![chrome_2017-03-02_20-01-29](https://cloud.githubusercontent.com/assets/7262039/23522493/7ee404dc-ff83-11e6-8d5b-9be41477f843.png)
![chrome_2017-03-02_20-02-22](https://cloud.githubusercontent.com/assets/7262039/23522494/7ee54c84-ff83-11e6-9718-94dc3af37a6d.png)

### Server rendered
![chrome_2017-03-02_19-59-15](https://cloud.githubusercontent.com/assets/7262039/23522491/7ee20830-ff83-11e6-8945-f4d5314ceca1.png)
![chrome_2017-03-02_20-01-53](https://cloud.githubusercontent.com/assets/7262039/23522492/7ee3ac30-ff83-11e6-98f2-929930089ce0.png)

It seems to me that the client does a much better job.

**Comment by Bouncey** [comment]
@systimotic Is it the font size for the `<li>`'s that you are pointing out?

**Comment by Bouncey** [comment]
I see it now #14181 should help with this

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
