### ISSUE TITLE
Codepen Signup Link is Broken

### ISSUE THREAD

**Issue by Margaret2** [freeCodeCamp/freeCodeCamp#13697]
#### Challenge Name
[Get Set For Our Front End Development Projects](https://www.freecodecamp.com/challenges/get-set-for-our-front-end-development-projects), step 4/7

#### Issue Description
FCC's link to sign up to Codepen appears to be broken. 

Currently it is https://codepen.io/signup/free which returns a 404.

I suggest updating the link to https://codepen.io/accounts/signup or https://codepen.io/accounts/signup/user/free

**Comment by texas2010** [comment]
eric did fix this in fcc site. you can check this. https://github.com/freeCodeCamp/freeCodeCamp/pull/13689

thanks.

**Comment by Margaret2** [comment]
haha, yeah just realized that, thanks @texas2010
