### ISSUE TITLE
Please PLEASE add, in the text, a reminder to use nulls for social media links

### ISSUE THREAD

**Issue by ArleneAndrews** [freeCodeCamp/freeCodeCamp#13718]
Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I had an attempted hack on my accounts that I live-linked there: let's avoid the easy data mining issue, hmm?

**Comment by raisedadead** [comment]
Hey @ArleneAndrews Can you reach me on gitter to discuss this and understand your issue? I am on  the team for freeCodeCamp.

You can reach me here : https://gitter.im/raisedadead
