### ISSUE TITLE
Suggestions for improving challenge style guide

### ISSUE THREAD

**Issue by hay-dee** [freeCodeCamp/freeCodeCamp#13715]
#### Issue Description

Currently, the <a href="https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md" target="_blank">Contributing Style Guide</a> does not include information on obtaining a unique challenge ID. The appropriate way to obtain the ID would be to run the MongoDB <code>ObjectId()</code> method. In addition, the style guide could have an example/description on how to format the seed files. Having such information in the style guide would be beneficial for campers editing challenges for the first time.

**Comment by raisedadead** [comment]
Yup, good idea. Could we not use a generator for this? I mean we have had an editor in the past, but it is now deprecated.

But a generator should be fairly good and a handly tool to implement that will generate an id and check that its unique among all of the available challenges.
