### ISSUE TITLE
Construct JavaScript Objects with Functions needs clarification

### ISSUE THREAD

**Issue by only1dallas** [freeCodeCamp/freeCodeCamp#13711]
#### Construct JavaScript Objects with Functions

[Construct JavaScript Objects with Functions](https://www.freecodecamp.com/challenges/construct-javascript-objects-with-functions#?solution=%0Avar%20Car%20%3D%20function()%20%7B%0A%20%20this.wheels%20%3D%204%3B%0A%20%20this.engines%20%3D%201%3B%0A%20%20this.seats%20%3D%205%3B%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20MotorBike%20%3D%20function()%20%7B%0Athis.wheels%20%3D%204%3B%0Athis.engines%20%3D%201%3B%0Athis.seats%20%3D%206%3B%0A%7D%3B%0A)

#### Issue Description

Haven't found a bug, however, it would be nice if you explained why we are using semi-colon now vs colon. thanks.

**Comment by rjkmurray** [comment]
The code is getting more  complex each day. It is constantly making improvements and modification to adjust for new beta projects . pretty exciting

**Comment by rjkmurray** [comment]
The code is getting more  complex each day. It is constantly making improvements and modification to adjust for new beta projects . pretty exciting

**Comment by rjkmurray** [comment]
The code is getting more  complex each day. It is constantly making improvements and modification to adjust for new beta projects . pretty exciting

**Comment by rjkmurray** [comment]
The code is getting more  complex each day. It is constantly making improvements and modification to adjust for new beta projects . pretty exciting

**Comment by raisedadead** [comment]
Hi @only1dallas thanks for your issue.

Can you guide, does your confusion about semicolons and colons are specific to this challenge?
Do you feel that this is misleading our daunting?

Apologies, I am trying to determine what could be creating this confusion.

If possible can you share code snippets here to differentiate what you mean?

Thanks.

**Comment by raisedadead** [comment]
Please clarify as requested

**Comment by ogora** [comment]
@raisedadead 
Well I agree with first comment from @only1dallas above. Given that most of us are clueless learners I think FCC can improve its learning platform  by explaining why one thing worked and another did  not. Even though I have passed most challenges without asking for help. I am a little concerned that I am just gambling my way thorugh and making lucky guesses without udernstading the " logic behind the correct answer".
