### ISSUE TITLE
[FCC - Beta] Youtube Playback Error

### ISSUE THREAD

**Issue by shashank7200** [freeCodeCamp/freeCodeCamp#13710]
Challenge [build-a-survey-form](http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-survey-form) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.

## The error can be reproduced in Firefox & Google Chrome. Here's the Screenshot of the issue:

![Imgur](http://i.imgur.com/QhAI0QK.png)

**Comment by raisedadead** [comment]
Refer https://github.com/freeCodeCamp/freeCodeCamp/issues/12753
