### ISSUE TITLE
If you access your solved bonfire from map page, it shows you have done nothing.

### ISSUE THREAD

**Issue by segmentationfaulter** [FreeCodeCamp/FreeCodeCamp#1371]
I am attempting bonfires, I needed to view the solution of a previous bonfire. I clicked on the 'Map' link and when clicked on the bonfire challenge which I had already attempted successfully, I was surprised to see that there was nothing as saved solution. Then I visited my public profile link, the solutions were saved there though. I suppose it is a bug, it should have shown me the saved solutions in both of the cased, whereas it showed only on my profile page.

**Comment by arya45** [comment]
I have the same issue and another camper as well. I don't know if it is a generalized issue though.

**Comment by benschenker** [comment]
Closing this issue as stale.  I believe that the bonfires as displayed in the challenges themselves are now stored in the browser via localstorage, but the bonfires in your profile are stored in the freecodecamp DB.
