### ISSUE TITLE
Bonfire: Repeat a string repeat a string reporting incorrect when correct.

### ISSUE THREAD

**Issue by Ikucuk** [FreeCodeCamp/FreeCodeCamp#1372]
When running the following code:
```
var empty = '';

function repeat(str, num) {
  for (var i=0; i < num; i++) {
    empty += str;
  }
  return empty; 
}

repeat('abc', 3);
```

It doesn't pass any test case.

If you replace repeat('abc', 3); with repeat('abc', -2);

It succeeds and passes all 3 test cases

**Comment by Ikucuk** [comment]
It seems to output the actual output + what it expects, instead of checking simply against what it expects:

assert.strictEqual(repeat('\*', 3), '\*\*\*', 'should repeat a string n times');should repeat a string n times: expected '\*\*\*\*\*\*' to equal '\*\*\*'

assert.strictEqual(repeat('abc', 3), 'abcabcabc', 'should repeat a string n times');should repeat a string n times: expected ***\'*\*\*\abcabcabc' to equal 'abcabcabc'

This would explain why when running it with -x works, as it simply puts an empty string before what it expects.

**Comment by benschenker** [comment]
@Ikucuk it looks like you initialize the string `empty` outside of the function body. 

You really want this inside the function body so that every time the function is called it reinitializes to `""`
