### ISSUE TITLE
Problem while commiting the task. Some of issues are wrong marked even if they are correct.

### ISSUE THREAD

**Issue by Yevhenii-Kushvid** [freeCodeCamp/freeCodeCamp#13724]
Challenge [Sum All Odd Fibonacci Numbers](https://www.freecodecamp.com/challenges/sum-all-odd-fibonacci-numbers#?solution=var%20fiboNumbers%20%3D%20%5B1%2C%201%5D%3B%0A%0Afunction%20sumFibs(num)%20%7B%0A%20%20var%20number%20%3D%20num%3B%0A%20%20if%20(fiboNumbers.find(function(fibo_number)%7B%0A%20%20%20%20return%20fibo_number%20%3E%20number%3B%0A%20%20%7D))%20%7B%0A%20%20%20%20var%20sum_of_odd_elements%20%3D%200%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20var%20counter%20%3D%200%3B%0A%20%20%20%20while((fiboNumbers.length%20-%201)%20%3E%20counter)%7B%0A%20%20%20%20%20%20if%20(fiboNumbers%5Bcounter%5D%20%25%202%20%3D%3D%201)%7B%0A%20%20%20%20%20%20%20%20sum_of_odd_elements%20%2B%3D%20fiboNumbers%5Bcounter%5D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20counter%2B%2B%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20sum_of_odd_elements%3B%0A%20%20%7D%20else%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20past_two_elements_in_fibo_row%20%3D%20%7B%0A%20%20%20%20%20%20first%3A%20fiboNumbers%5BfiboNumbers.length%20-%202%5D%2C%0A%20%20%20%20%20%20second%3A%20fiboNumbers%5BfiboNumbers.length%20-%201%5D%0A%20%20%20%20%7D%3B%0A%20%20%20%20var%20new_fibo_element%20%3D%20past_two_elements_in_fibo_row.first%20%2B%20past_two_elements_in_fibo_row.second%3B%0A%20%20%20%20fiboNumbers.push(new_fibo_element)%3B%0A%20%20%20%20return%20sumFibs(number)%3B%0A%20%20%7D%0A%7D%0A%0AsumFibs(4)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var fiboNumbers = [1, 1];

function sumFibs(num) {
  var number = num;
  if (fiboNumbers.find(function(fibo_number){
    return fibo_number > number;
  })) {
    var sum_of_odd_elements = 0;
                  
    var counter = 0;
    while((fiboNumbers.length - 1) > counter){
      if (fiboNumbers[counter] % 2 == 1){
        sum_of_odd_elements += fiboNumbers[counter];
      }
      counter++;
    }
    return sum_of_odd_elements;
  } else {              
    past_two_elements_in_fibo_row = {
      first: fiboNumbers[fiboNumbers.length - 2],
      second: fiboNumbers[fiboNumbers.length - 1]
    };
    var new_fibo_element = past_two_elements_in_fibo_row.first + past_two_elements_in_fibo_row.second;
    fiboNumbers.push(new_fibo_element);
    return sumFibs(number);
  }
}

sumFibs(4);
```

**Comment by systimotic** [comment]
@Yevhenii-Kushvid Thank you for reporting this issue.

There is an issue with your code. The tests run your function multiple times, but they do not reset your global variable `fiboNumbers`. The `fiboNumbers` array is what's causing trouble here. We're resolving this in #9063

I'm closing this as an issue with your code. For coding help, please click the "Help" button on the challenge. Happy coding!
