### ISSUE TITLE
Revoke certifications?

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/freeCodeCamp#13723]
This camper has "completed" the Front End and Back End Certifications, but all of his projects are either bogus links or link to FCC projects on codepen.

Not sure what the general course of action is, in cases like these, but just decided to mention it here so as to inform everyone (and the mods).

https://www.freecodecamp.com/KoalaPears

**Comment by texas2010** [comment]
@BerkeleyTrue, this issue for you.
someone cheat on fcc challenges.

**Comment by BerkeleyTrue** [comment]
@Manish-Giri Thanks. In the future please PM me instead of posting their username here.


Happy Coding.
