### ISSUE TITLE
Suggest Non-Equality Operator Challenges

### ISSUE THREAD

**Issue by 126Andy** [freeCodeCamp/freeCodeCamp#13728]
Challenge [Comparison with the Strict Equality Operator](https://www.freecodecamp.com/challenges/comparison-with-the-strict-equality-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function testStrict(val) {
  if (val === 7) { // Change this line
    return "Equal";
  }
  return "Not Equal";
}

// Change this value to test
testStrict(7);

```

**Comment by erictleung** [comment]
@126Andy thanks for the suggestion. Not sure if we need an extra challenge for this. In my opinion, it might be okay to just mention and show that you can also use a not equals (or not strict equals) as well. But then keep the challenge the same. I know this goes against the "teach one concept per challenge" we've set out for the challenges, but I think it should be okay to introduce the equality and not equality at the same time. But if others feel there needs to be redundancy as a benefit for learning, I'm okay with that too.

cc/ @freeCodeCamp/moderators
