### ISSUE TITLE
[Beta] Basic HTML and HTML5: Bad Scroll behavior on insctrucions

### ISSUE THREAD

**Issue by nativedone** [freeCodeCamp/freeCodeCamp#13726]
#### Challenge Name

Basic HTML and HTML5: Create a Bulleted Unordered List (But occurs in any challenge on HTML course)

#### Issue Description

Every time that you submit a challenge, the next challenge appear with the instructions scrolled. The link below points to the exact situation. So, you need to scroll up every time.

#### Browser Information

* Browser Name, Version: Chrome Version 56.0.2924.87
* Operating System: Windows 8
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```
#### Screenshot

https://snag.gy/4tzmCe.jpg

**Comment by systimotic** [comment]
@adetime Thanks for reporting this issue!

I can't reproduce this issue. It's always at the top for me, regardless of how far down I had scrolled on the previous challenge. Can you share more details on how to reproduce?

**Comment by adetime** [comment]
Hi @systimotic,

Basically, after submitting a challenge:

1. The notification that a new challenge just arrived appear at the bottom-right corner

2. But, the page itself is not reloaded. As a result, `neither the scroll` is reset, nor the _`new HTML/CSS`_ of this challenge is shown on the simulator's screen.

I had seen one issue that was trying to address this problem. But, I'm not finding this issue again. I remember that the person says something like:

> I'm reloading the page after a challenge is submitted. But, the problem is that all tests are re-running. Then, I need to figure out how update the page content without re-running all tests.

The closer information that I found now is here on [13225](https://github.com/freeCodeCamp/freeCodeCamp/issues/13225). 

You can see that there is a comment of @Bouncey [saying](https://github.com/freeCodeCamp/freeCodeCamp/issues/13225#issuecomment-278109617):

> there is not enough of an indication that the next challenge has arrived. In a previous version of beta, the instruction panel (`<SidePanel />`) scrolled to the top when the challenge instructions changed. This functionality seems to have been removed. I would welcome it back.

**Comment by lindakatcodes** [comment]
I'm just getting started with the HTML challenges, but I've noticed this problem as well. Only a few of the challenges seem to be doing it for me, not all of them. I made a gif of my screen showing the scrollbar not resetting: 

![2017-03-16_21-51-45](https://cloud.githubusercontent.com/assets/16214572/24027103/15da9b70-0a93-11e7-8a5f-51a6888bcba1.gif)

I'm using Chrome v. 56.0.2924.87 - Windows 10 - on a desktop

My text editor code always updates, and the new instruction information changes as well - only the scroll bar doesn't seem to reset/adjust back to the top.

**Comment by adetime** [comment]
Yeah @lindakatcodes! It's the exact behavior 👍 

In my experience it always happens. Perhaps, I have a good result only when the content fits my screen's height 😢 .

**Comment by Marmiz** [comment]
Am I correct in assuming that we are using React Router on the beta version?

If so, that was an infamous behavior that was fix by doing:
```javascript
window.scrollTo(0, 0);
```
Perhaps in our page layout the left sidebar is not seen by that function.
I suggest to start investigating the `submitChallenge` function and/or our React Router behavior.

I'll give it a show whenever I can, but I encourage others to do so as well :)

**Comment by dhcodes** [comment]
This appears to be fixed for me on beta on Chrome. Anyone confirm?

**Comment by lindakatcodes** [comment]
It's still happening for me in the Applied Visual Design section. I'll have to double check the HTML and Basic CSS sections again tomorrow to see if it's changed there at all.
