### ISSUE TITLE
Back end projects aren't using the correct view

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#13730]
Our back end projects are still using the old project view ([like this](http://beta.freecodecamp.com/en/challenges/api-and-microservice-projects/timestamp-microservice)). They should instead use the new back end challenge view ([like this](http://beta.freecodecamp.com/en/challenges/managing-packages-with-npm/how-to-use-packagejson-the-core-of-any-nodejs-project-or-npm-package)).

I suspect this can be fixed by giving these projects the same combination of type and challengeType as the Node challenges.

@JosephLivengood would you be interested in tackling this one?

**Comment by JosephLivengood** [comment]
I can get it within 24 hours. Was originally going to include it with the pr for adding tests but I agree this needs to be viewed properly asap!

**Comment by BhaveshSGupta** [comment]
@QuincyLarson I can help with this tonight, I tried this on few challenges on my local and changing type worked.

**Comment by BerkeleyTrue** [comment]
@QuincyLarson back end challenges should not have `challengeType` properties. These are legacy and should not be added to new challenges.

Also, most of those challenges do not have proper tests.
