### ISSUE TITLE
[Beta] Instructions on Create a Set of Radio Buttons are not so clear

### ISSUE THREAD

**Issue by adetime** [freeCodeCamp/freeCodeCamp#13731]
#### Challenge Name

Basic HTML and HTML5: Create a Set of Radio Buttons

#### Issue Description

The instructions say:

> Add a pair of radio buttons to your form. One should have the option of `indoor `and the other should have the option of `outdoor`.

I think it should be:

Add a pair of radio buttons to your form. One should have the option of `indoor `and the other should have the option of `outdoor`. Both should have ` indoor-outdoor ` as name attribute. 

Because the test fails if you try to use a different name, as shown below. But, on the introduction of the challenge we only have:

> All related radio buttons should have the same `name` attribute.

And I know that on the example provided we have:

` <label><input type="radio" name="indoor-outdoor"> Indoor</label>`

But, the reality is the task asked in this challenge **doesn't limit the choice** of the name attribute. 

 

#### Browser Information

* Browser Name, Version: Chrome, 56.0.2924.87
* Operating System: Window 8
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <input type="text" placeholder="cat photo URL" required>
    <label>
      <input type="radio" name="in-out">
      indoor
    </label>
    <label>
      <input type="radio" name="in-out">
      outdoor
    </label>
    
    <button type="submit">Submit</button>
  </form>
</main>



```

**Comment by adetime** [comment]
If you look the next challenge, that uses the same principles to checkbox, it has:

> All three should share the `name `attribute of `personality`.

which highlights the inconsistency on the task's description of the challenge in discussion.

**Comment by systimotic** [comment]
Good catch @adetime, this is indeed a bit weird. Do you want to fix this? The [CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) will guide you through getting your local development environment set up. The changes can be made [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/d424b7331ded350e297387b134f5ab8e85631839/seed/challenges/01-responsive-web-design/basic-html-and-html5.json#L1591), in the `/seed/challenges/01-responsive-web-design/basic-html-and-html5.json` file around line 1591.
If you need help, please go to our [contributors chatroom](https://gitter.im/FreeCodeCamp/Contributors).

If you don't want to make this change, that's OK too! Please let me know, and I'll make sure this is taken care of.

**Comment by SebastianPetak** [comment]
@systimotic I'd like to fix this as my first contribution if someone else isn't working on it.

**Comment by adetime** [comment]
Hi @systimotic, 

I started to configure my forked repo and I will take care of this issue.

@SebastianPetak `If I have any trouble`, I will let this one for you.

**Comment by adetime** [comment]
It will be fixed by this [PF](https://github.com/freeCodeCamp/freeCodeCamp/pull/13811).
