### ISSUE TITLE
Not passing the test cases when it actually does

### ISSUE THREAD

**Issue by adgebana** [freeCodeCamp/freeCodeCamp#13732]
Challenge [Seek and Destroy](https://www.freecodecamp.com/challenges/seek-and-destroy#?solution=function%20filterOut(currentValue)%20%7B%0A%20%20return%20currentValue%20!%3D%3D%20this%3B%0A%7D%0A%0A%0Afunction%20destroyer(arr)%20%7B%0A%20%20%2F%2F%20store%20the%20arguments%20into%20a%20variable%20for%20easier%20readability%0A%20%20var%20args%20%3D%20Array.from(arguments)%3B%0A%20%20for%20(var%20i%20%3D%201%3B%20i%20%3C%3D%20args.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20arr%20%3D%20arr.filter(filterOut%2C%20args%5Bi%5D)%3B%0A%20%20%7D%0A%20%20return%20arr%3B%0A%7D%0A%0Adestroyer(%5B3%2C%205%2C%201%2C%202%2C%202%5D%2C%202%2C%203%2C%205)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function filterOut(currentValue) {
  return currentValue !== this;
}


function destroyer(arr) {
  // store the arguments into a variable for easier readability
  var args = Array.from(arguments);
  for (var i = 1; i <= args.length; i++) {
    arr = arr.filter(filterOut, args[i]);
  }
  return arr;
}

destroyer([3, 5, 1, 2, 2], 2, 3, 5);

```
## To reproduce: simply copy and paste my code.

Case 1:
destroyer([1, 2, 3, 1, 2, 3], 2, 3);
should return [1, 1]
![screenshot1](https://cloud.githubusercontent.com/assets/25548418/23576225/4ee9af90-00da-11e7-95cd-adde19326a60.png)
- Using my code, the console outputs [1, 1] BUT DOES NOT PASS the test case.
![screenshot2](https://cloud.githubusercontent.com/assets/25548418/23576226/5e23d026-00da-11e7-84f9-32859a5cb513.png)
- If I replace the last line of the function
 "return arr;" with "return [1, 1];", the console outputs [1, 1] and passes the test case.

**Comment by ramir141974** [comment]
No still on this way...

**Comment by Ethan-Arrowood** [comment]
Interesting. I'm getting a similar issue; however, I completed this challenge a while back and was able to solve it. Will update shortly.

**Comment by saksoy** [comment]
function destroyer(arr) {
  // Remove all the values  
  for(var i = 1; i < arguments.length; i++){
    arr = arr.filter(function(val){return val != this;}, arguments[i]);
  }
  console.log(arr);
  return arr;
}
passed test

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

**Comment by saksoy** [comment]
```
function destroyer(arr) {
  // Remove all the values  
  for(var i = 1; i < arguments.length; i++){
    arr = arr.filter(function(val){return val != this;}, arguments[i]);
  }
  console.log(arr);
  return arr;
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

```
passe test

**Comment by saksoy** [comment]
```
function destroyer(arr) {
  // Remove all the values  
  for(var i = 1; i < arguments.length; i++){
    arr = arr.filter(function(val){return val != this;}, arguments[i]);
  }
  console.log(arr);
  return arr;
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

```
passed test

**Comment by texas2010** [comment]
@saksoy 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
