### ISSUE TITLE
Feature Request: Collapse & search feature for completed exercises on profile pages

### ISSUE THREAD

**Issue by AlexWulkan** [FreeCodeCamp/FreeCodeCamp#1374]
After completing an exercise I usually try a few different solutions just to test my knowledge. The problem is that all of the solutions are being diplayed in one super long list of code snippets on my profile page. It would be nice if each exercise was collapsed, so that it takes up less space. Within each collapsed exercise you could have all the snippets of code for that specific one.

It would also be nice to have an instantly updated search feature so that you can easily find which exercise you're looking for in the list, or just list them in the same order as on the [map](http://www.freecodecamp.com/map) page for consistency.

This is just to make the site easier to navigate, but I understand if there's more important things to fix first. :)

**Comment by BerkeleyTrue** [comment]
Challenge solutions on profile page are now Shareable Challenges® links. Soon we will be removing duplicates from profiles as well.

Happy Coding!

**Comment by AlexWulkan** [comment]
@BerkeleyTrue 
When you say that you are going to remove duplicates, what do you mean exactly? I have a lot of duplicates. Some are really bad and some are good examples of how I solved the bonfires. Will I get to choose which ones to keep myself, or will you just delete everything randomly? I don't want my list to only include all the bad examples I generated while trying things out.

**Comment by BerkeleyTrue** [comment]
The last one will be kept. This is done as part of an ongoing move to reduce our server and database load so we can keep running on minimal hardware as we expand.

**Comment by AlexWulkan** [comment]
@BerkeleyTrue
That means that all of my good solutions will be deleted. I think itwill affect a lot of people negatively. My last solutions are my worst, because in those I was just trying out random stuff.

Why not let people delete them individually? So that we can keep the ones we like. I don't want to be judged based on bad code, and so does no one else.
