### ISSUE TITLE
[Suggestion] Create a Set of Radio Buttons OR create-a-set-of-radio-buttons 

### ISSUE THREAD

**Issue by t0cc** [freeCodeCamp/freeCodeCamp#13747]
This exercise https://www.freecodecamp.com/challenges/create-a-set-of-radio-buttons is introducing the **label** tag without explaining it beforehand.  Please, add a separate exercise for it before.

**Comment by iansibindi** [comment]
Create a Set of Radio Buttons

**Comment by systimotic** [comment]
Thanks for reporting this issue @t0cc!

I agree that the label element should be properly introduced. The beta does have [a challenge introducing the label element](https://beta.freecodecamp.com/en/challenges/applied-accessibility/improve-form-field-accessibility-with-the-label-element), but it comes after the radio buttons challenge.
