### ISSUE TITLE
Waypoint: Line up Form Elements Responsively with Bootstrap

### ISSUE THREAD

**Issue by alagram** [FreeCodeCamp/FreeCodeCamp#1375]
Challenge http://www.freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

Not really a but, but the wording in the exercise is a bit confusing. I believe the 3rd tip should read:
Wrap your form **text input** in a div with the class "col-xs-7".

**Comment by benschenker** [comment]
I believe this has been fixed as the language has changed.

I'm going to close this issue but reopen it if you don't think the language is proper
