### ISSUE TITLE
[beta] Expand tests for different styling formats

### ISSUE THREAD

**Issue by shubham-thinkbridge** [freeCodeCamp/freeCodeCamp#13754]
Challenge [change-the-color-of-text](http://beta.freecodecamp.com/en/challenges/basic-css/change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

<style>
  h2
  {
    color : red
  }
</style>
```

**Comment by Ethan-Arrowood** [comment]
A few things
1. Don't put your issue in the title. That should be included in the issue body.
2. If you're having issues passing a test please discuss your code in the Gitter [help channel](https://gitter.im/FreeCodeCamp/Help)
3. This challenge states to include your style code inline with your html, not add a `<style>` block.

**Comment by shubham-thinkbridge** [comment]
Could please suggest a title for this issue? I am new to this, sorry.

I understood how to pass the challenge, however I feel that it should make explicit the way with which a user is expected to write the code. Just before this section, we are provided a few overview notes on CSS which state that there are 3 ways to insert CSS rules.

In the "challenge-test-suite" div, I feel there should be a test case which checks if the user has indeed written an inline-style rather than just "The h2 text must be red.". Because the text is indeed red, I have technically passed the test yet it prevents me from going forward.

**Comment by Ethan-Arrowood** [comment]
An appropriate title would be:
  [beta] Expand tests for different styling formats

You are right, your code is correct, but the purpose of this challenge is to show the user they can edit code directly inline. By accepting other results (such as the one you proposed) we are essentially validating the wrong use-cases for the given challenge.

**Comment by shubham-thinkbridge** [comment]
Maybe I am just overthinking this, but I feel that the test case wording should be more clear on the intent by including a message that the style should be inline.

**Comment by Ethan-Arrowood** [comment]
<img width="272" alt="screen shot 2017-03-05 at 1 50 04 am" src="https://cloud.githubusercontent.com/assets/16144158/23585195/17efef6a-0146-11e7-97ba-7440733b4db1.png">
I don't know how you could make it any more explicit than this without straight up giving the use the code.

**Comment by shubham-thinkbridge** [comment]
I meant the test case. I did mention in an above comment that a helpful guide is present in the comments. Nevermind, I am overthinking here.

**Comment by Ethan-Arrowood** [comment]
Hmm I see. I feel like that is a reasonable request. Do you want to give a crack at making the fix? Check out [this](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) if you are interested.

**Comment by shubham-thinkbridge** [comment]
Ok, I will try.

**Comment by systimotic** [comment]
I think the best solution would be to switch to a CSS test (`$('h2').css('color') === 'rgb(255, 0, 0)'` or something like that) instead of a regex test.

**Comment by cdrainxv** [comment]
I believe it was that originally, but was changed due to it failing on firefox browsers due to the jquery-based tests issue. The regex test is asserting that the code used is inline styling, but I can see the merit in changing the test message to tell campers to actually use inline styling, instead of just saying that the color must be red. 

Maybe the current test should be split into two, with one to verify that the styling is inline, and the other to confirm that the h2 element's text color is indeed red. It isn't mentioned that inline styling must be used, but based on the example and the fact that the style element has not been introduced yet, forcing the use of inline styling wouldn't be much of a leap.

**Comment by ResamVi** [comment]
If you check the current code this has already been implemented:

```js
"tests": [
        "assert(code.match(/<h2\\s+style\\s*=\\s*(\\'|\")\\s*color\\s*:\\s*(?:rgb\\(\\s*255\\s*,\\s*0\\s*,\\s*0\\s*\\)|rgb\\(\\s*100%\\s*,\\s*0%\\s*,\\s*0%\\s*\\)|red|#ff0000|#f00|hsl\\(\\s*0\\s*,\\s*100%\\s*,\\s*50%\\s*\\))\\s*\\;?(\\'|\")>\\s*CatPhotoApp\\s*<\\/h2>/), 'message: Your <code>h2</code> element should be red.');",
        "assert(code.match(/<h2\\s+style\\s*=\\s*(\\'|\")\\s*color\\s*:\\s*(?:rgb\\(\\s*255\\s*,\\s*0\\s*,\\s*0\\s*\\)|rgb\\(\\s*100%\\s*,\\s*0%\\s*,\\s*0%\\s*\\)|red|#ff0000|#f00|hsl\\(\\s*0\\s*,\\s*100%\\s*,\\s*50%\\s*\\))\\s*\\;(\\'|\")>\\s*CatPhotoApp\\s*<\\/h2>/),' message: Your <code>style</code> declaration should end with a <code>;</code> .');"
      ],
```

Commit: 19e4c0fccd4385c2063e555fdafbeae879fe3b1b

So this could be closed

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
