### ISSUE TITLE
video needs update

### ISSUE THREAD

**Issue by s989uk** [freeCodeCamp/freeCodeCamp#13755]
just a little inconsistent, sorry it confused me i felt like i was cheating.

if i had a book that told me how to do something id flick back through that book if i was stuck same principal?

video not matching page rule#2 i was trying to do while not looking back at the examples,
i believe you need to look back at the example projects (i can see it has been removed from the page)
but its a little confusing for some.

#### Challenge Name

https://www.freecodecamp.com/challenges/build-a-tribute-page

**Comment by systimotic** [comment]
Hi @s989uk! Thank you for reporting this issue.

You are right, there are some inconsistencies here. We have noticed that it's difficult to keep these videos up to date. We have decided to get rid of them. The videos are not there anymore in the beta.

I'm closing this issue as it has been resolved in the beta. Happy coding!
