### ISSUE TITLE
Moving on issue

### ISSUE THREAD

**Issue by slow-learner** [freeCodeCamp/freeCodeCamp#13762]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js

<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>

```
#### Screenshot

The code is fine and is running as correct. I don't know if it is your issue or mine but the link button for me to move on does not fully load therefore i am stuck.

**Comment by OFFLlNE** [comment]
Thank you for reporting the issue @slow-learner 
Could you provide more information.. for example, what challenge you are trying to pass?

**Comment by OFFLlNE** [comment]
Closing this, because so response in 24 hours
