### ISSUE TITLE
[beta] Missing challenges for display: block and display: inline

### ISSUE THREAD

**Issue by Atomk** [freeCodeCamp/freeCodeCamp#13761]
Challenge [change-an-elements-relative-position](http://beta.freecodecamp.com/en/challenges/applied-visual-design/change-an-elements-relative-position) has an issue.

This challenge introduces the difference between block elements and inline elements AND relative positioning. In my opinion there should be one or more challenges to practice the "display" property of elements before diving into positioning.
In the "old" curriculum this concept was first introduced in the Bootstrap section: http://beta.freecodecamp.com/en/challenges/bootstrap/create-a-block-element-bootstrap-button

[This challenge](http://beta.freecodecamp.com/en/challenges/applied-visual-design/learn-about-complementary-colors) uses inline-block, so that has to be introduced too.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
