### ISSUE TITLE
[beta] Better locate the map in the first HTML challenge

### ISSUE THREAD

**Issue by Atomk** [freeCodeCamp/freeCodeCamp#13763]
Challenge [say-hello-to-html-elements](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/say-hello-to-html-elements) has an issue.

The description says "feel free to skip around by clicking the map on the left", but the map does not appear anymore from the left and also on mobile the map can be found in the menu.

I'd change that statement with something like "feel free to skip around by clicking the map (you can find it in the menu)".
If not "menu", I think "navigation bar" is another valid option.

**Comment by eyelesbarrow** [comment]
hi, i'd like to work on this.

**Comment by doninphnx** [comment]
I am actually quite the novice but open and willing to take any and all of your support

**Comment by Atomk** [comment]
@jdeprey Maybe next time write a comment to tell you're working on an issue, so others don't get frustrated if someone else got the job done.
@eyelesbarrow @doninphnx Thank you for your interest, I was hoping for a little discussion on this to be honest, I'm sure you can find other easy issues to work on!

**Comment by jdeprey** [comment]
@Atomk My bad.  I hadn't seen any comments when I first read the issue.
