### ISSUE TITLE
Mari Berbagi

### ISSUE THREAD

**Issue by Myscript2010** [freeCodeCamp/freeCodeCamp#13760]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%0A%3Ch3%3EHello%3C%2Fh3%3E%0A%0A%3Cdiv%20class%3D%22social-net%22%3E%0A%3Ca%20href%3D%22%23%22%3E%3Ci%20class%3D%22fa%20fa-twitter%22%20aria-hidden%3D%22true%22%3E%3C%2Fi%3E%3C%2Fa%3E%0A%3Ca%20href%3D%22%23%22%3E%3Ci%20class%3D%22fa%20fa-facebook%22%20aria-hidden%3D%22true%22%3E%3C%2Fi%3E%3C%2Fa%3E%0A%3Ca%20href%3D%22%23%22%3E%3Ci%20class%3D%22fa%20fa-google-plus%22%20aria-hidden%3D%22true%22%3E%3C%2Fi%3E%3C%2Fa%3E%0A%3Ca%20href%3D%22%23%22%3E%3Ci%20class%3D%22fa%20fa-pinterest%22%20aria-hidden%3D%22true%22%3E%3C%2Fi%3E%3C%2Fa%3E%0A%20%20%20%20%20%20%20%20%20%20%20%3C%2Fdiv%3E%0A%3Ch1%3EMari%20Berbagi%20%3C%2Fh1%3E%0A%3C!DOCTYPE%20html%3E%0A%20%0A%3Chtml%3E%0A%3Chead%3E%0A%3Ctitle%3EFont%20Awesome%20Icons%3C%2Ftitle%3E%0A%3Cmeta%20name%3D%22viewport%22%20content%3D%22width%3Ddevice-width%2C%20initial-scale%3D1%22%3E%0A%3Clink%20rel%3D%22stylesheet%22%20href%3D%22https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Ffont-awesome%2F4.7.0%2Fcss%2Ffont-awesome.min.css%22%3E%0A%3C%2Fhead%3E%0A%3Cbody%3E%0A%3Cscript%20src%3D%27%2F%2Fproduction-assets.codepen.io%2Fassets%2Fcommon%2FstopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js%27%3E%0Afcces%0A%3Cscript%20src%3D%27%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fjquery%2F2.1.3%2Fjquery.min.js%27%3E%0Afcces%0A%3C%2Fbody%3E%0A%3C%2Fhtml%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h3>Hello</h3>

<div class="social-net">
<a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
<a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
<a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
<a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
           </div>
<h1>Mari Berbagi </h1>
<!DOCTYPE html>
 
<html>
<head>
<title>Font Awesome Icons</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<script src='//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'>
</script>
<script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'>
</script>
</body>
</html>
```

**Comment by texas2010** [comment]
Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
