### ISSUE TITLE
The "challenge completed" dialog could use a better overlay effect

### ISSUE THREAD

**Issue by Atomk** [freeCodeCamp/freeCodeCamp#13764]
#### Issue Description

The "challenge completed" dialog seems to just change the background color, which does not loook pretty at all, even suggesting you can still interact with some elements like `inputs` and `buttons` (see screenshot below)
The best thing would be using a proper overlay that darkens the whole page, not just the background. A solution could be a full page div with a bit of transparency.
The screenshot was taken on the beta website but it applies also to the public curriculum, with some variations (the overlay effect is not applied to the code editor and the phone browser output).

#### Browser Information

* Browser Name, Version: Chrome 56.0.2924.87 (64-bit)
* Operating System: Windows 7 64bit
* Mobile, Desktop, or Tablet: desktop

#### Screenshot

![overlay](https://cloud.githubusercontent.com/assets/6122017/23591782/5311bb18-01f6-11e7-9700-ae8a143684c9.PNG)

**Comment by systimotic** [comment]
The backdrop is a proper overlay, but the z-index is not high enough to display in front of these other elements. Thanks for reporting @Atomk

**Comment by SlyTy7** [comment]
Hey guys I would love to take a crack at this, if it's something easy.  You already take care of it? @systimotic

**Comment by Atomk** [comment]
@SlyTy7 I think you merged the change in your repository, you should have targeted the freeCodeCamp's one. Quoting the first point of the pre-submission checklist:

```
Your pull request targets the staging branch of freeCodeCamp.
```

**Comment by SlyTy7** [comment]
Thanks @Atomk.  Think I got it figured out now.  Sorry, still pretty new!

**Comment by Atomk** [comment]
@SlyTy7 No problem, we're all here to learn :)
