### ISSUE TITLE
sorted-union

### ISSUE THREAD

**Issue by GoingAllTheWayUp** [freeCodeCamp/freeCodeCamp#13778]
#### Challenge Name

https://www.freecodecamp.com/challenges/sorted-union

#### Issue Description

uniqueArray: 1,2,1,0,3,2,1,0
VM1235:10 element: 1, index: 0, array: 1,2,1,0
VM1235:10 element: 2, index: 1, array: 1,2,1,0
VM1235:10 element: 1,0, index: 2, array: 1,2,1,0
VM1235:10 element: 1, index: 0, array: 1,2,1,0,3,2,1,0
VM1235:10 element: 2, index: 1, array: 1,2,1,0,3,2,1,0
VM1235:10 element: 1,0, index: 2, array: 1,2,1,0,3,2,1,0
VM1235:10 element: 3, index: 3, array: 1,2,1,0,3,2,1,0
VM1235:10 element: 2, index: 4, array: 1,2,1,0,3,2,1,0
VM1235:10 element: 1,0, index: 5, array: 1,2,1,0,3,2,1,0
VM1237:4 uniqueArray: 1,2,1,0,3,2,1,0
VM1237:10 element: 1, index: 0, array: 1,2,1,0
VM1237:10 element: 2, index: 1, array: 1,2,1,0
VM1237:10 element: 1,0, index: 2, array: 1,2,1,0
VM1237:10 element: 1, index: 0, array: 1,2,1,0,3,2,1,0
VM1237:10 element: 2, index: 1, array: 1,2,1,0,3,2,1,0
VM1237:10 element: 1,0, index: 2, array: 1,2,1,0,3,2,1,0
VM1237:10 element: 3, index: 3, array: 1,2,1,0,3,2,1,0
VM1237:10 element: 2, index: 4, array: 1,2,1,0,3,2,1,0
VM1237:10 element: 1,0, index: 5, array: 1,2,1,0,3,2,1,0

basicly I belive that this these arguments [1], [2,[1,0]], [3, 2,[1,0]] are not passing this test. but these are [1], [2,[1]], [3, 2,[1]] do and i don't know what is wrong my co, but for this test to pass should these arguments [1], [2,[1,0]], [3, 2,[1,0]] need to pass also?

#### Browser Information

* Browser Name, Version: chrome
* Operating System: windows 10
* Mobile, Desktop, or Tablet: desktop

#### Your Code

```js

function uniteUnique(...uniqueArray) {
// spreads 
  console.log("uniqueArray: " + uniqueArray);
  
            // .reduce() with .concat()
            return uniqueArray.reduce(function(accumulator,currentValue){
              //
              return accumulator.concat(currentValue).filter(function(element,index,array){
               console.log("element: " + element + ", index: " + index + ", array: " +array);
                // return the element only if it exists at its own index position
                return index == array.indexOf(element);
                
            });
           });
          }
uniteUnique([1], [2,[1,0]], [3, 2,[1,0]]);


```

**Comment by systimotic** [comment]
Hi @GoingAllTheWayUp!

Nice job on your solution! For the purposes of this challenge, your solution is fine. It does indeed not deal with nested arrays with the same values, but that's not required here. If you do want to take the challenge of figuring this out, here's a hint:
```js
[0, 1] === [0, 1]; // false
```
This issue tracker is for issues with the challenges, so I'm closing this issue. Happy coding!
