### ISSUE TITLE
COLOR RED #F00 OR #FF0000..STILL NO

### ISSUE THREAD

**Issue by aviationmechanic** [freeCodeCamp/freeCodeCamp#13771]
Challenge [Use Abbreviated Hex Code](https://www.freecodecamp.com/challenges/use-abbreviated-hex-code#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20%23f00%0A%20%20%7D%0A%20%20.fuchsia-text%20%7B%0A%20%20%20%20color%3A%20%23f0f%3B%0A%20%20%7D%0A%20%20.cyan-text%20%7B%0A%20%20%20%20color%3A%20%230ff%3B%0A%20%20%7D%0A%20%20.green-text%20%7B%0A%20%20%20%20color%3A%20%230f0%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22fuchsia-text%22%3EI%20am%20fuchsia!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22cyan-text%22%3EI%20am%20cyan!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22green-text%22%3EI%20am%20green!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: #f00
  }
  .fuchsia-text {
    color: #f0f;
  }
  .cyan-text {
    color: #0ff;
  }
  .green-text {
    color: #0f0;
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="fuchsia-text">I am fuchsia!</h1>

<h1 class="cyan-text">I am cyan!</h1>

<h1 class="green-text">I am green!</h1>

```

**Comment by Manish-Giri** [comment]
@aviationmechanic You forgot the closing `;` for the first value. Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) for help with challenges.

**Comment by aviationmechanic** [comment]
wow, cant believe it, still new at this, first time to post too, i thought it was a bug, thanks for the fast response, i always google the waypoints when im stuck but this time i couldnt see my own mistake, thank you.
