### ISSUE TITLE
Cloud 9 is bad

### ISSUE THREAD

**Issue by Kermet24** [freeCodeCamp/freeCodeCamp#13777]
Challenge [Manage Packages with npm](https://www.freecodecamp.com/challenges/manage-packages-with-npm) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 9000.91.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
I dudb't use cloud nine becuase it asks me about my credit card information people said that cload 9 takes money and it is not free use codeanywhere

**Comment by Kermet24** [comment]
I meant dont

**Comment by Kermet24** [comment]
Also In the Video it shows that cload 9 is free but it is not

**Comment by Kermet24** [comment]
cloud

**Comment by texas2010** [comment]
video is out of date.

this fcc site have nothing with cloud issue.

have a nice day/

**Comment by schas002** [comment]
Yes, sadly Cloud9 *does* require a credit card, but it's not charged unless you get a paid plan. Also we're switching to Gomix. :)

**Comment by Kermet24** [comment]
Thank you :)
