### ISSUE TITLE
[beta] CSS Parsing Issue on certain Challenges

### ISSUE THREAD

**Issue by ParaBolt** [freeCodeCamp/freeCodeCamp#13774]
## The Issue

In certain challenges (listed below), if there is a space between property and colon, the tests will fail to validate even though code has been written correctly.

Meaning, This code fails :-
```
selector {
 property : value;
}
```
and this code passes :-
```
selector {
 property:value;
}
```

## Examples

There are more, I'll update here as I find them.

- [Applied Visual Design: Adjust the background-color Property of Text](http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-backgroundcolor-property-of-text)
- [Applied Visual Design: Add a box-shadow to a Card-like Element](http://beta.freecodecamp.com/en/challenges/applied-visual-design/add-a-boxshadow-to-a-cardlike-element)
- [Applied Visual Design: Create a Gradual CSS Linear Gradient](http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-a-gradual-css-linear-gradient)
- [Applied Visual Design: Adjust the Hover State of an Anchor Tag](http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-hover-state-of-an-anchor-tag)
- [Applied Visual Design: Learn about Tertiary Colors](http://beta.freecodecamp.com/en/challenges/applied-visual-design/learn-about-tertiary-colors)
- [Applied Visual Design: Adjust the Hue of a Color](http://beta.freecodecamp.com/en/challenges/applied-visual-design/adjust-the-hue-of-a-color)
- [CSS Flexbox: Apply the flex-direction Property to Create Rows in the Tweet Embed](http://beta.freecodecamp.com/en/challenges/css-flexbox/apply-the-flexdirection-property-to-create-rows-in-the-tweet-embed)

**Comment by texas2010** [comment]
that dont have an issue?  you wrote wrong code.  it suppose to be `property: value;`

it will be failed if you add space before : .  `property : value;`

**Comment by shubham-thinkbridge** [comment]
No, property : value is correct and the result is rendered correctly by the browser. You can try writing such code by yourself, I've been writing it this way for years.

**Comment by ParaBolt** [comment]
It is correct syntax, parsed and rendered by the browser correctly.

**Comment by cdrainxv** [comment]
@ParaBolt:
Hmmm... on one hand the examples provided alongside the challenge use the standard conventions for css markup and campers will most likely try to format their code based on the example code, therefore unknowingly adhering to industry style guides. However, I see the point in that campers should not have to worry about following a style guide during the early learning process, but instead focus on using correct syntax.

There's really only two options at this point, the first one being to rewrite the tests so they aren't as strict, although it would be to the benefit of campers if they are nudged towards writing code that conforms to the accepted conventions, even at the early stages of learning CSS.  The other option, and the better one, is to wait for issue #10749 to be resolved, which will then clear up these and the other challenges waiting on this fix.

I believe the consensus is on option two.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Comment by T1mL3arn** [comment]
Issue is still present for [Add a box-shadow to a Card-like Element](https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/add-a-box-shadow-to-a-card-like-element).

While both of these are correct

```css
/* first */
#thumbnail {
    box-shadow: 0 10px 20px rgba(0,0,0,0.19)
              , 0 6px 6px rgba(0,0,0,0.23);
  }

/* second */
#thumbnail {
    box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);
  }
```

only the second passes the test.

Win7 Firefox 63.0.1
