### ISSUE TITLE
Issue with Link click counter in Forums

### ISSUE THREAD

**Issue by FarooqAR** [freeCodeCamp/freeCodeCamp#13788]
#### Issue Description
On the forums, when I just right click on a link and not actually open the link, it still updates the clicks' counter. However, the counter gets reset when I refresh the page.

#### Screenshot

![](http://i.imgur.com/L66nFPG.gif)

**Comment by systimotic** [comment]
@FarooqAR Great catch, thank you for reporting this issue! We use discourse as our forum software. Can you report this bug there instead? https://meta.discourse.org/c/bug
That would be awesome!

**Comment by FarooqAR** [comment]
Done!
