### ISSUE TITLE
[beta] Unable to give any visual feedback in these anchor tags with text-align property

### ISSUE THREAD

**Issue by adetime** [freeCodeCamp/freeCodeCamp#13789]
Challenge [create-visual-balance-using-the-textalign-property](http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-visual-balance-using-the-textalign-property) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I think that there is one more thing missed in that challenge. The final **note** says:

> When you align the two anchor tags, you will see no difference. This is `because text is aligned to the left` by default.

But, to be honest you are **unable** to see any change, even if you use **text-align** with other values as center, right, start, end...

So, I think that portion of the challenge needs to be changed. If we are unable to give any visual feedback in these anchor tags they need to be changed.

```html


<style>
  h4 {
    text-align: center;
    
  }
  p {
    text-align: justify;
    
  }
  .links {
    margin-right: 20px;
    text-align: left;   
    
  }
  .fullCard {
    border: 1px solid #ccc;
    border-radius: 5px;
    margin: 10px 5px;
    padding: 4px;
  }
  .cardContent {
    padding: 10px;
  }
</style>
<div class="fullCard">
  <div class="cardContent">
    <div class="cardText">
      <h4>Google</h4>
      <p>Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University.</p>
    </div>
    <div class="cardLinks">
      <a href="https://en.wikipedia.org/wiki/Larry_Page" target="_blank" class="links">Larry Page</a>
      <a href="https://en.wikipedia.org/wiki/Sergey_Brin" target="_blank" class="links">Sergey Brin</a>
    </div>
  </div>
</div>

```

**Comment by systimotic** [comment]
Source: https://github.com/freeCodeCamp/freeCodeCamp/issues/13611#issuecomment-284264331
Thanks for reporting @adetime!
I agree, it is weird that we're setting `text-align` if you can't see the result anyway. I think we should remove it from the links completely.

**Comment by adetime** [comment]
I agree @systimotic. Removing it solves the issue.

**Comment by vinayarkasali** [comment]
Hi Adeildo,

i have done solution for that, hope your looking like this kind of solution...



<style>
  h4 {
    
  }
  p {
    
  }
  .links {
    margin-right: 20px;
    
  }
  .fullCard {
    border: 1px solid #ccc;
    border-radius: 5px;
    margin: 10px 5px;
    padding: 4px;
  }
  .cardContent {
    padding: 10px;
  }
  .cardText > h4
  {
    text-align:center;
  }
  .cardText > p
  {
    text-align:justify;
  }
  .cardLinks > a
  {
    float:left;
  }
</style>
<div class="fullCard">
  <div class="cardContent">
    <div class="cardText">
      <h4>Google</h4>
      <p>Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University.</p>
    </div>
    <div class="cardLinks">
      <a href="https://en.wikipedia.org/wiki/Larry_Page" target="_blank" class="links">Larry Page</a>
      <a href="https://en.wikipedia.org/wiki/Sergey_Brin" target="_blank" class="links">Sergey Brin</a>
    </div>
  </div>
</div>


Thank you..

**Comment by vinayarkasali** [comment]
![screen shot 2017-03-07 at 2 54 57 pm](https://cloud.githubusercontent.com/assets/26214856/23649873/127a9de4-0346-11e7-8b3a-c0ac5a524b00.png)

**Comment by vinayarkasali** [comment]
![screen shot 2017-03-07 at 2 55 50 pm](https://cloud.githubusercontent.com/assets/26214856/23649911/33e9923c-0346-11e7-9947-bdd8afb8ab2c.png)

**Comment by adetime** [comment]
Hi Vinay,

Thanks for sharing your solution.

Yeah! I think your solution moves the anchor tag to left, and is also able to move to right.

However, the goal of this particular challenge is teaches about ` text-align` property. 

The float property is **another level of knowledge** and that takes the HTML element `out of the normal flow` of a document, as explained in the next section of **Applied Visual Design**.

**Comment by adetime** [comment]
I will submit a PR to address this issue.
