### ISSUE TITLE
[beta] Clicking on "About" in the menu opens the map

### ISSUE THREAD

**Issue by Atomk** [freeCodeCamp/freeCodeCamp#13780]
#### Issue Description

In any page, clicking Community > About in the navigation bar opens the map page instead. After a few seconds a message "Oops! Something went wrong" appears, but no message is shown in the console.

#### Browser Information

* Browser Name, Version: 56.0.2924.87 (64-bit)
* Operating System: Windows 7, 64bit
* Mobile, Desktop, or Tablet: Desktop

**Comment by systimotic** [comment]
Thanks for reporting @Atomk!

Redirecting to the map is default behaviour upon error.

I believe the static pages only work on the live site. They are in their own separate repositories. I'm not sure whether this is something that should be changed.

**Comment by ooade** [comment]
@systimotic i think /about should open the current [about](freecodecamp.com/about). I looked it up on Chrome devtools, it gave a 302 status code with response type of text/html

**Comment by QuincyLarson** [comment]
@ooade @systimotic yes - thanks for spotting this. Would either of you be interested in fixing this?

**Comment by ooade** [comment]
@QuincyLarson I'd like to take this. `about.jade` don't currently exist in `server/views/resources`. So, i'll have to add it.

**Comment by ooade** [comment]
I'll make use of the master's about page

**Comment by BerkeleyTrue** [comment]
About page was intentionally removed. Adding it back in will only add more things to maintain.  

Instead we should have a generic redirect with a message indicating that the static page is not set up appropriately.

**Comment by ooade** [comment]
@BerkeleyTrue Oh! That's true :sweat_smile:
So going to a non-existing route should show a `page not found` page??

**Comment by BerkeleyTrue** [comment]
No I think a simple toast saying something like `static page not found` with a redirect to map.

**Comment by ooade** [comment]
Okay. Cool... I'll take it.
