### ISSUE TITLE
Editor not expecting ternary expression

### ISSUE THREAD

**Issue by erik-ernst** [freeCodeCamp/freeCodeCamp#13796]
![2017-03-07 15_08_26-testing objects for properties _ free code camp](https://cloud.githubusercontent.com/assets/25354301/23678043/155d5680-0348-11e7-8029-eba0e9858884.png)
Challenge [Testing Objects for Properties](https://www.freecodecamp.com/challenges/testing-objects-for-properties#?solution=%0A%2F%2F%20Setup%0Avar%20myObj%20%3D%20%7B%0A%20%20gift%3A%20%22pony%22%2C%0A%20%20pet%3A%20%22kitten%22%2C%0A%20%20bed%3A%20%22sleigh%22%0A%7D%3B%0A%0Afunction%20checkObj(checkProp)%20%7B%0A%20%20%2F%2F%20Your%20Code%20Here%0A%20%20myObj.hasOwnProperty(checkProp)%20%3F%20checkProp%20%3D%20myObj%5BcheckProp%5D%20%3A%20checkProp%20%3D%20%22Not%20Found%22%3B%0A%20%20return%20checkProp%3B%0A%7D%0A%0A%2F%2F%20Test%20your%20code%20by%20modifying%20these%20values%0AcheckObj(%22gift%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Just use the same code as appears below in "My Code" and see that the editor doesn't like the ternary expression. Upon mouse hover, the red x displays the message, "Expected an assignment or function call and instead saw an expression." 

My code:
```javascript

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  myObj.hasOwnProperty(checkProp) ? checkProp = myObj[checkProp] : checkProp = "Not Found";
  return checkProp;
}

// Test your code by modifying these values
checkObj("gift");

```

**Comment by Manish-Giri** [comment]
@erik-ernst You probably need to review ternary operators, because this works for me - 
`return myObj.hasOwnProperty(checkProp) ? myObj[checkProp] : "Not Found";`

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) first for help with challenges like these.

**Comment by erik-ernst** [comment]
Thank you, that is even simpler. I should have mentioned the test ran successfully, it is just the editor that didn't like it.

**Comment by systimotic** [comment]
Hi @erik-ernst!

This is an interesting way of using ternary operators. I've never seen it being used like this before. In a similar use case, I would usually do something more like the following:
```js
checkProp = myObj.hasOwnProperty(checkProp) ? myObj[checkProp] : "Not Found";
```

Thanks for reporting this issue, it does seem like it's not quite right.
We don't control the linting ourselves, we're dependent on CodeMirror's built-in linting, which uses JSHint.

I'm closing this, as this is not an issue with freeCodeCamp, but with a dependency.
Happy coding!
