### ISSUE TITLE
Not ignoring comments

### ISSUE THREAD

**Issue by erik-ernst** [freeCodeCamp/freeCodeCamp#13797]
Challenge [Replacing If Else Chains with Switch](https://www.freecodecamp.com/challenges/replacing-if-else-chains-with-switch#?solution=%0Afunction%20chainToSwitch(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%2F*%0A%20%20if%20(val%20%3D%3D%3D%20%22bob%22)%20%7B%0A%20%20%20%20answer%20%3D%20%22Marley%22%3B%0A%20%20%7D%20else%20if%20(val%20%3D%3D%3D%2042)%20%7B%0A%20%20%20%20answer%20%3D%20%22The%20Answer%22%3B%0A%20%20%7D%20else%20if%20(val%20%3D%3D%3D%201)%20%7B%0A%20%20%20%20answer%20%3D%20%22There%20is%20no%20%231%22%3B%0A%20%20%7D%20else%20if%20(val%20%3D%3D%3D%2099)%20%7B%0A%20%20%20%20answer%20%3D%20%22Missed%20me%20by%20this%20much!%22%3B%0A%20%20%7D%20else%20if%20(val%20%3D%3D%3D%207%20%7B%0A%20%20%20%20answer%20%3D%20%22Ate%20Nine%22%3B%0A%20%20%7D%0A%20%20*%2F%0A%20%20%0A%20%20switch%20(val)%20%7B%0A%20%20%20%20case%20%22bob%22%3A%0A%20%20%20%20%20%20answer%20%3D%20%22Marley%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2042%3A%0A%20%20%20%20%20%20answer%20%3D%20%22The%20Answer%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%201%3A%0A%20%20%20%20%20%20answer%20%3D%20%22There%20is%20no%20%231%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2099%3A%0A%20%20%20%20%20%20answer%20%3D%20%22Missed%20me%20by%20this%20much!%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%207%3A%0A%20%20%20%20%20%20answer%20%3D%20%22Ate%20Nine%22%3B%0A%20%20%20%20%20%20break%3B%20%20%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AchainToSwitch(7)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

To reproduce, use the code in "my code" and then click Run tests. Notice that it is not passing the test because of the commented if/else statements. 

![2017-03-07 15_17_03-replacing if else chains with switch _ free code camp](https://cloud.githubusercontent.com/assets/25354301/23678347/60d3797c-0349-11e7-8246-ae95c6e56eae.png)

My code:
```javascript

function chainToSwitch(val) {
  var answer = "";
  // Only change code below this line
/*
  if (val === "bob") {
    answer = "Marley";
  } else if (val === 42) {
    answer = "The Answer";
  } else if (val === 1) {
    answer = "There is no #1";
  } else if (val === 99) {
    answer = "Missed me by this much!";
  } else if (val === 7 {
    answer = "Ate Nine";
  }
  */
  
  switch (val) {
    case "bob":
      answer = "Marley";
      break;
    case 42:
      answer = "The Answer";
      break;
    case 1:
      answer = "There is no #1";
      break;
    case 99:
      answer = "Missed me by this much!";
      break;
    case 7:
      answer = "Ate Nine";
      break;      
  }
  
  // Only change code above this line  
  return answer;  
}

// Change this value to test
chainToSwitch(7);


```

**Comment by cdrainxv** [comment]
@erik-ernst: The tests are only checking if the keywords `if` and `else` are present in the editor, not if they are parsed by the interpreter. I would suggest removing the if/else if/else statements from the editor altogether as mentioned in the  test messages:

> You should not use any else statements anywhere in the editor
> You should not use any if statements anywhere in the editor

**Comment by Ethan-Arrowood** [comment]
If you're having trouble understanding a challenge or you have an issue with your code please ask for help in the official Gitter channel [here](https://gitter.im/FreeCodeCamp/Help). Furthermore, you can search in the [public forums](https://forum.freecodecamp.com/) to see if someone has had a similar problem with this challenge. 

If you believe something is wrong with the challenge itself please elaborate so we can begin to solve it. 

Thank you!

**Comment by erictleung** [comment]
Closing as duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/11360. Happy coding!
