### ISSUE TITLE
Wont pass Concatenating Strings with Plus Operator for some Reason 

### ISSUE THREAD

**Issue by Code3824379** [freeCodeCamp/freeCodeCamp#13792]
Challenge [Concatenating Strings with Plus Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator#?solution=%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%3B%0AourStr%20%2B%3D%20%22I%20come%20second.%22%3B%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20myStr%20%3D%20%22This%20is%20the%20start.%22%20%2B%20%22%20This%20is%20the%20end.%22%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourStr = "I come first. ";
ourStr += "I come second.";
// Only change code below this line
var myStr = "This is the start." + " This is the end.";

```

**Comment by cdrainxv** [comment]
@Code3824379: This is probably due to you changing the challenge code. Only change code below this line: `// Only change code below this line`.

**Comment by Code3824379** [comment]
oh.....yea:(

**Comment by OFFLlNE** [comment]
@Code3824379 as I understand you managed to fix the problem yourself. I will close this issue for now and if you need help then try to use gitter helprooms [One for javascript for example](https://gitter.im/FreeCodeCamp/HelpJavaScript)
