### ISSUE TITLE
Third test for Bonfire 9: Confirm the Ending

### ISSUE THREAD

**Issue by Adoyle2014** [FreeCodeCamp/FreeCodeCamp#1379]
The third test ends with a period allowing us to pass this test using `substr(-1, 1);`. I don't think this is the intended way to pass this Bonfire since we are only testing the last item in the string and not the whole word.

**Comment by benschenker** [comment]
It looks like the tests for http://www.freecodecamp.com/challenges/bonfire-confirm-the-ending have changed.

Marking this as closed but feel free to reopen if the tests are still found to be lackign
