### ISSUE TITLE
Add Placeholder Text to a Text Field

### ISSUE THREAD

**Issue by eixan** [freeCodeCamp/freeCodeCamp#13802]
#### Challenge Name
http://bit.ly/2n4oOrg

#### Issue Description
The place where you enter html is blank. Works on chrome though.Edit: Intially I couldn't type anything on the bottom of the page in chrome. I selected the cursor from higher on the page and used arrow keys to type on the bottom
![untitled](https://cloud.githubusercontent.com/assets/26262465/23693005/a80044b2-0397-11e7-80ed-b4f6376d9cf3.png)

#### Browser Information

* Browser Name, Version:  Pale Moon 27.1.2 (64-bit)
* Operating System: windows 10 
* Mobile, Desktop, or Tablet:  deaktop
![untitled](https://cloud.githubusercontent.com/assets/26262465/23692984/8590ad0e-0397-11e7-958a-f14c5d8cade0.png)

#### Your Code

```js



```

**Comment by erictleung** [comment]
@eixan thanks for the issue. As you've pointed out, this does work on Chrome. We, unfortunately, don't have the bandwidth to test on non-major browsers. The other issue you may have faced is this one https://github.com/freeCodeCamp/freeCodeCamp/issues/7847. Please take a look at the thread for some workarounds. Closing as we don't have the resources to test for non-major browsers. Happy coding!
