### ISSUE TITLE
Program does not work well on netbooks

### ISSUE THREAD

**Issue by NoreenAhm** [FreeCodeCamp/FreeCodeCamp#1380]
Hi, I just started using Free Code Camp. It's been great, but it took me a while to realize that the only way to make the "More Information" and "Go to My Next Challenge" buttons work was by making the browser full screen. 

Additionally, the phone in which your work is being displayed on the right-hand side of the screen cuts off at the bottom and I can't scroll down to see what I did there. 

Just wanted to pass that on. It's a great site, however. Thank you!

**Comment by Gmrpr7** [comment]
This is an issue on mobile devices too. Anything with a small screen or when window is at half screen.

**Comment by BerkeleyTrue** [comment]
@NoreenAhm Sorry to hear about your experiences. Can you give us some more specs on your machine? Resolution? Browser?

**Comment by NoreenAhm** [comment]
Thanks so much for following up!

I have an Asus eee PC (
https://www.asus.com/media/global/products/BtksJTDENqfsnuyf/P_500.jpg) and
use Ubuntu with Google Chrome. Not sure about the resolution.

Thank you again!

**Comment by awesomeaniruddh** [comment]
Everything looks good to me: both when resizing the browser window on my laptop, and on my phone's screen.

The only issue I see is that the editor window shows up *below* the tests when the window width is low.

**Comment by BerkeleyTrue** [comment]
This was a bootstrap issue and has been resolved.

Happy Coding!
