### ISSUE TITLE
[beta] Code editor not loading in challenge

### ISSUE THREAD

**Issue by hay-dee** [freeCodeCamp/freeCodeCamp#13803]
Challenge [make-elements-only-visible-to-a-screen-reader-by-using-custom-css](http://beta.freecodecamp.com/en/challenges/applied-accessibility/make-elements-only-visible-to-a-screen-reader-by-using-custom-css) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The code editor in this particular challenge is not loading properly.

<img width="949" alt="capture" src="https://cloud.githubusercontent.com/assets/20010384/23705459/e45e9348-0444-11e7-8e9f-1b9efdffc6ae.PNG">

**Comment by mitron6** [comment]
Work around: Go to map and select the challenge again. 

To Duplicate: Go to map. Select the challenge. Close the browser window or tab. Open a new window or tab. Go to beta.freecodecamp.com The challenge will open with the above problem.
 
Tested with Chrome 56.0.2924.87 (64 bit) and Firefox 47.0.

**Comment by systimotic** [comment]
Thanks for reporting! I'm closing this as a part of #13698. Happy coding!
