### ISSUE TITLE
This challenge does not pass in Firefox but does in Chrome.

### ISSUE THREAD

**Issue by mitron6** [freeCodeCamp/freeCodeCamp#13806]
Challenge [make-elements-only-visible-to-a-screen-reader-by-using-custom-css](http://beta.freecodecamp.com/en/challenges/applied-accessibility/make-elements-only-visible-to-a-screen-reader-by-using-custom-css) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:47.0) Gecko/20100101 Firefox/47.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Using Firefox 47.0 enter the below code and click run tests.  It will not pass.  Open Chrome and click tests. It passes.

```html


<head>
  <style>
  .sr-only {
    position: absolute;
    left: -10000px;
    width: 1px;
    height: 1px;
    top: auto;
    overflow: hidden;
  }
  </style>
</head>
<body>
  <header>
    <h1>Training</h1>
    <nav>
      <ul>
        <li><a href="#stealth">Stealth &amp; Agility</a></li>
        <li><a href="#combat">Combat</a></li>
        <li><a href="#weapons">Weapons</a></li>
      </ul>
    </nav>
  </header>
  <section>
    <h2>Master Camper Cat's Beginner Three Week Training Program</h2>
    <figure>
      <!-- Stacked bar chart of weekly training-->
      <p>[Stacked bar chart]</p>
      <br />
      <figcaption>Breakdown per week of time to spend training in stealth, combat, and weapons.</figcaption>
    </figure>
    <table class="sr-only">
      <caption>Hours of Weekly Training in Stealth, Combat, and Weapons</caption>
      <thead>
        <tr>
          <th></th>
          <th scope="col">Stealth &amp; Agility</th>
          <th scope="col">Combat</th>
          <th scope="col">Weapons</th>
          <th scope="col">Total</th>                                        
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Week One</th>
          <td>3</td>
          <td>5</td>
          <td>2</td>
          <td>10</td>
        </tr>
        <tr>
          <th scope="row">Week Two</th>
          <td>4</td>
          <td>5</td>
          <td>3</td>
          <td>12</td>
        </tr>
        <tr>
          <th scope="row">Week Three</th>
          <td>4</td>
          <td>6</td>
          <td>3</td>
          <td>13</td>
        </tr>
      </tbody>
    </table>
  </section>
  <section id="stealth">
    <h2>Stealth &amp; Agility Training</h2>
    <article><h3>Climb foliage quickly using a minimum spanning tree approach</h3></article>
    <article><h3>No training is NP-complete without parkour</h3></article>
  </section>
  <section id="combat">
    <h2>Combat Training</h2>
    <article><h3>Dispatch multiple enemies with multithreaded tactics</h3></article>
    <article><h3>Goodbye, world: 5 proven ways to knock out an opponent</h3></article>
  </section>
  <section id="weapons">
    <h2>Weapons Training</h2>
    <article><h3>Swords: the best tool to literally divide and conquer</h3></article>
    <article><h3>Breadth-first or depth-first in multi-weapon training?</h3></article>
  </section>
  <footer>&copy; 2016 Camper Cat</footer>
</body>

```

**Comment by mitron6** [comment]
Tested with Firefox 50.1.0 and it still does not pass.

**Comment by erictleung** [comment]
@mitron6 thanks for the issue. Currently, I'm having issues just loading the challenge in both browsers. I'll have to try testing this later to see if that fixes at least the loading of the challenges. Maybe someone else will have better luck in at least loading the challenge in the meantime.

**Comment by juliterlegis** [comment]
I am also having issues with FCC in Firefox browser...

1. Submit haphazardly displays passing animated gif; inconsistent.
(Could this have something to do with the new phrases suggested by campers, that may possibly be uploaded?)
2. "Responsive Design w/ Bootstrap": skipped over my incorrect placement of `<div>` tag.
3. When I log in to FCC, I get redirected to "JavaScript Arrays" ???

Not that a big a deal for me, just a shout out to FCC devs. I would guess that a lot of people may have been thinking of the challenges as too difficult and rigid at first, not leaving room for human error...

I went through FCC in November of 2017 and got to JavaScript, I just started over with a new account to commit to #100DaysofCode and it just seems a bit more unstable.

Truth be told, that is the nature of computing and complex systems in general...
I would advise "small input:small changes" because the FCC community has amassed exponentially.

**Comment by JacksonBates** [comment]
I just tested this in Firefox 57 and it no longer seems to be a problem:

![image](https://user-images.githubusercontent.com/4337740/33297116-75b7878c-d433-11e7-89fd-9e974678a4dd.png)

Or am I missing something? Do we want it to work in older versions of FF too?

**Comment by anhtran1906** [comment]
I aslo tested this in Firefox 57.0.1 and all the tests passed. Should we just mention what version of Firefox will work well with fCC on Beta release?
<img width="1280" alt="screen shot 2017-12-09 at 2 50 59 pm" src="https://user-images.githubusercontent.com/20694114/33798962-6d51824e-dcf0-11e7-9786-b7de43bf6dff.png">

**Comment by Bouncey** [comment]
Closing as resolved in staging. If this is still an issue, please reopen and provide more information

Happy Coding!
