### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Missposhtee** [freeCodeCamp/freeCodeCamp#13807]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3BFirstline%0A%20%20%20%20%20%20%20%20%20%20%20%5CSecondLine%5C%0A%20%20%20%20%20%20%20%20%20%20Thirdline%5C%5C%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr;Firstline
           \SecondLine\
          Thirdline\\



```

**Comment by Ethan-Arrowood** [comment]
Hi @Missposhtee 

If you're having trouble understanding a challenge or you have an issue with your code please ask for help in the official Gitter channel [here](https://gitter.im/FreeCodeCamp/Help). Furthermore, you can search in the [public forums](https://forum.freecodecamp.com/) to see if someone has had a similar problem with this challenge.

**Comment by Bouncey** [comment]
Closing because this issue is asking for code help.

**Comment by fatbacker** [comment]
The forum is useless most of the time.
