### ISSUE TITLE
[beta] [enhancement] change instructions to a js challenge

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13808]
Basic JavaScript: Using Objects for Lookups
http://beta.freecodecamp.com/en/challenges/basic-javascript/using-objects-for-lookups

Current: 
Convert the switch statement into **a lookup table** called lookup. Use it to lookup val and assign the associated string to the result variable.

Changes:
Convert the switch statement into **an object** called lookup. Use it to lookup val and assign the associated string to the result variable.

**Comment by erictleung** [comment]
@tommygebru thanks for the issue! This seems like a reasonable change.
