### ISSUE TITLE
the line that needs to be edited will not click and seems to be protected. I've refreshed restated and cleared to no avail. I thnk its a bug

### ISSUE THREAD

**Issue by reever33** [freeCodeCamp/freeCodeCamp#13813]
Challenge [Add Font Awesome Icons to all of our Buttons](https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-all-of-our-buttons) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>
    </div>
  </div>
  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info">Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger">Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

**Comment by Ethan-Arrowood** [comment]
If you're having trouble understanding a challenge or you have an issue with your code please ask for help in the official Gitter channel [here](https://gitter.im/FreeCodeCamp/Help). Furthermore, you can search in the [public forums](https://forum.freecodecamp.com/) to see if someone has had a similar problem with this challenge. 

If you believe something is wrong with the challenge itself please elaborate so we can begin to solve the potential bug.

Thank you!

**Comment by Manish-Giri** [comment]
@reever33 If you're still stuck on this, try pressing any key on the editor first. That should "unfreeze" the lines where you need to write your code at.

**Comment by erictleung** [comment]
@reever33 you might be experiencing the "bug" in this issue https://github.com/freeCodeCamp/freeCodeCamp/issues/7847. Please reply if you are experiencing this bug or another.

**Comment by erictleung** [comment]
Closing as stale. Please reply if you're experiencing this bug or the one I referenced previously. Happy coding!
