### ISSUE TITLE
Getting correct results but not passing final test

### ISSUE THREAD

**Issue by Vi5tar** [freeCodeCamp/freeCodeCamp#13815]
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#?solution=function%20factorialize(num)%20%7B%0A%20%20var%20factor%20%3D%20%221%22%3B%0A%20%20for(i%20%3D%201%3B%20i%20%3C%3D%20num%3B%20i%2B%2B)%20%7B%0A%20%20%20%20factor%20*%3D%20i%3B%0A%20%20%7D%0A%20%20return%20factor%3B%0A%7D%0A%0Afactorialize(0)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function factorialize(num) {
  var factor = "1";
  for(i = 1; i <= num; i++) {
    factor *= i;
  }
  return factor;
}

factorialize(0);

```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong. You are returning 1 as a string, but you need to return it as an int
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by deshawnminnis** [comment]
Hello,

I am new to the family. I am trying to follow emails here and there, but it
has been mad crazy and fun at the same time. I am a coding beginner and I
have a quick question regarding this function using for loop.

In this scenario would we need to convert the variable from string to int??
I recall there is a parseInt function to do this, is that correct?



Thanks,

De'Shawn

**Comment by Ken212** [comment]
Okay, so I think I found a bug.  Here's my code for Factorialize A Number.  I've tried various input and am getting the correct answer.  But for some reason, it's not passing me.  Any ideas?  Thanks in advance! Ken

var finaltotal = 1;

function factorialize(num) {


for (var i = 1; i < num+1; i++) {
  finaltotal *= i;
} 
  num = finaltotal;  
  return num;
}

factorialize(5);

**Comment by captainCodeKirk** [comment]
I am having the same problem as you Ken. Below is the code I entered, and I am getting all the right answers, but not passing the test...

var x = 1;

function factorialize(num) {
  for (var i = 1; i <= num; i++) {
    x *= i;
  }
  return x;
}

factorialize(0);

**Comment by captainCodeKirk** [comment]
For some reason, when I declare the variable, x, inside the function like so:

function factorialize(num) {
  var x = 1;
  for (var i = 1; i <= num; i++) {
  x *= i;
  }
  return x;
}

factorialize(0);

...it works perfectly fine. I do not understand why this is.

**Comment by amberbranson3** [comment]
So listen I need a answer to this question either answer it or I will use
every resource I have to find out who this is but why and how long have you
known me

**Comment by Mrprofessor** [comment]
lol

**Comment by amberbranson3** [comment]
Thank you so much and I'm sorry for that attitude i had i was getting into
trouble by my girl wondering why I was hiding things I will defiantly check
this out thank you

**Comment by texas2010** [comment]
@amberbranson3 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!

**Comment by kaxiwaki** [comment]
it's fine,china is 22:43 now.




发自网易邮箱大师
On 04/16/2017 22:41, Lance wrote:

@amberbranson3
looks like you may have accidentally subscribed to all notifications for the FreeCodeCamp repository. To stop receiving notifications please visit the subscriptions page and select "Not watching". Additionally, you can visit the GitHub Help page on managing notification delivery methods for more help.

We are sorry for your inconvenience!
