### ISSUE TITLE
Use class Syntax to Define a Constructor Function

### ISSUE THREAD

**Issue by RoniqueRicketts** [freeCodeCamp/freeCodeCamp#13812]
Challenge [use-class-syntax-to-define-a-constructor-function](http://beta.freecodecamp.com/en/challenges/es6/use-class-syntax-to-define-a-constructor-function) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
Open the challenge and take a look at the object name if I should copy and paste the code in another environment the code will throw a syntax error. The example codes are not consistent eg

var SpaceShuttle = function(targetPlanet){
  this.targetPlanet = targetPlanet;
}
var zeus = new spaceShuttle('Jupiter');

If I am to console.log zeus I will get an error becasue spaceShuttle is not the same as SpaceShuttle.
```js


/* Alter code below this line */
const Vegetable = undefined;
/* Alter code above this line */
const carrot = new Vegetable('carrot');
console.log(carrot.name); // => should be 'carrot'

```

**Comment by Ethan-Arrowood** [comment]
Nice catch! Would you like to try and fix this bug yourself?

**Comment by RoniqueRicketts** [comment]
Sure. How would I do so

**Comment by Ethan-Arrowood** [comment]
Great!
Give [this](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) a read through and if you have any questions you can ask in the Contributing Gitter [here](https://gitter.im/FreeCodeCamp/Contributors).
