### ISSUE TITLE
Default case issue

### ISSUE THREAD

**Issue by solankivir** [freeCodeCamp/freeCodeCamp#13814]
Challenge [Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20switch(val)%20%7B%0A%20%20%20%20case%20%22alpha%22%3A%20%0A%20%20%20%20%20%20result%20%3D%20%22Adams%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22bravo%22%3A%20%0A%20%20%20%20%20%20result%20%3D%20%22Boston%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22charlie%22%3A%20%0A%20%20%20%20%20%20result%20%3D%20%22Chicago%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22delta%22%3A%20%0A%20%20%20%20%20%20result%20%3D%20%22Denver%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22echo%22%3A%20%0A%20%20%20%20%20%20result%20%3D%20%22Easy%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%20%22foxtrot%22%3A%20%0A%20%20%20%20%20%20result%20%3D%20%22Frank%22%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20default%3A%0A%20%20%20%20%20%20result%20%3D%20%22undefined%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22charlie%22)%3B%0AphoneticLookup(%22%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  switch(val) {
    case "alpha": 
      result = "Adams";
      break;
    case "bravo": 
      result = "Boston";
      break;
    case "charlie": 
      result = "Chicago";
      break;
    case "delta": 
      result = "Denver";
      break;
    case "echo": 
      result = "Easy";
      break;
    case "foxtrot": 
      result = "Frank";
      break;
    default:
      result = "undefined";
  }
  
  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");
phoneticLookup("");

```

**Comment by Manish-Giri** [comment]
@solankivir Can you describe what's the problem? The challenge requires you to use a lookup table (an `object`), and I see that you still have a `switch/case` construct, to begin with.

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
