### ISSUE TITLE
Headline with h2 element has broke IMG link

### ISSUE THREAD

**Issue by haunja** [freeCodeCamp/freeCodeCamp#13827]
#### Challenge Name

https://www.freecodecamp.com/challenges/headline-with-the-h2-element

#### Issue Description
IMG link to Cat's Photo App is broken

#### Browser Information

* Browser Name, Version: Chrome Version 56.0.2924.87 (64-bit) and Firefox  52.0 32bit
* Operating System: Windows 7 64bit
* Mobile, Desktop, or Tablet: Dell E7470 Laptop

#### Your Code
NA

#### Screenshot

![capture](https://cloud.githubusercontent.com/assets/5329973/23767497/c224677a-04d6-11e7-9425-0c6bb533684c.PNG)

**Comment by raisedadead** [comment]
Hey, it renders fine for me. Looks like [imgur](http://imgur.com/) is blocked in your case? Are you behind a firewall or something?

Can you check on a alternate network?

**Comment by haunja** [comment]
Very possible.  I'll check when I'm off the domain.

**Comment by raisedadead** [comment]
Closing. We strongly believe this has to do with your network and not the code base. Please feel free to continue on the thread should you need any assistance.
