### ISSUE TITLE
[enhancement] change in instructions for record collection challenge

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#13826]
Basic JavaScript: Record Collection
http://beta.freecodecamp.com/en/challenges/basic-javascript/record-collection

We should try to make it more clear where the challenge instructions begin for this challenge using a horizontal line or using strong tag like the hint section.

Further more the hint section should be above the actual instructions, within the introduction of the challenge.

I also think we can make the language easier to understand by incorporating the "argument" terminology

Changes:

**Basic JavaScript: Record Collection**
`</hr>`
You are given a JSON object representing a part of your musical album collection. Each album has several properties and a unique id number as its key. Not all albums have complete information.

Write a function which takes an album's id (like 2548), a property prop (like "artist" or "tracks"), and a value (like "Addicted to Love") to modify the data in this collection.

If the function argument prop isn't "tracks" and argument value isn't empty (""), update or set the value for that record album's property.

Your function must always return the entire collection object.

**Hints**
Use bracket notation when accessing object properties with variables.

Push is an array method you can read about on Mozilla Developer Network.

You may refer back to Manipulating Complex Objects Introducing JavaScript Object Notation (JSON) for a refresher.

`</hr>`

**Instructions**
If the argument prop is "tracks" and the collection doesn't have a "tracks" property, create an empty array before adding the new value to the collection's corresponding property.

If the argument prop is "tracks" and the argument value isn't empty (""), push the value onto the end of the collection's existing tracks array.

If the argument value is empty (""), delete the given prop property from the collection.

**Comment by tommygebru** [comment]
This is one of the largest bottlenecks for the section Basic Javascript, we should try to make it as organized and readable as possible 👍

**Comment by systimotic** [comment]
@tommygebru To me, the entire description contains solely instructions. The part you separated aren't the instructions, they're exceptions, or rules for handling data that's different from the default. I don't think they need to be separated into a different section.

**Comment by tommygebru** [comment]
I thought about that too, the thing is that the instructions are very long on these bottlenecks/checkpoints and it should be more readable, I only made small changes, but I think it makes a difference, especially side by side comparison screenshots which I cannot do currently LOL

**Comment by erictleung** [comment]
I agree with @systimotic that the whole description is pretty much instructions. Only the first paragraph is an actual description while the rest explains all the rules and exceptions you'll need to write into your function.

**Comment by systimotic** [comment]
I'm open to improvements, I definitely think that this challenge could be better. I'm closing this specific issue because as the entire description is an instruction, putting only the exception underneath the header will cause confusion.

If there are new ideas, feel free to add them here and reopen this issue. Happy coding!
