### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by arsubbu** [freeCodeCamp/freeCodeCamp#13828]
I am unable to proceed eventhough i do not have a code issue.

Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3C!--%0A%3Ch1%3EHello%20World%3C%2Fh1--%3E%0A%3C!--p%3EHello%20Paragraph%3C%2Fp%3E%0A--%3E%0A%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!--
<h1>Hello World</h1-->
<!--p>Hello Paragraph</p>
-->


<h2>CatPhotoApp</h2>


```

**Comment by Manish-Giri** [comment]
@arsubbu The failing test case on the left should tell you what the problem is -
> Do not change the order of the h1 h2 or p in the code.

Please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help) if you need assistance with the challenge. Happy Coding!
