### ISSUE TITLE
"Hello World" is not mentioned in instructions.

### ISSUE THREAD

**Issue by Harendra1993** [freeCodeCamp/freeCodeCamp#13824]
Challenge [Understand String Immutability](https://www.freecodecamp.com/challenges/understand-string-immutability#?solution=%0A%2F%2F%20Setup%0Avar%20myStr%20%3D%20%22Jello%20World%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0AmyStr%20%3D%20%22H%22%3B%20%2F%2F%20Fix%20Me%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStr = "Jello World";

// Only change code below this line

myStr = "H"; // Fix Me



```

**Comment by erictleung** [comment]
@Harendra1993 thanks for the issue. I agree that the challenge is a bit vague but there are two points about this challenge. First, the challenge tests show you that you'll need "Hello World" in the string. Second, recently, this challenge has been updated to be more clear. You can check it out in [the beta site](http://beta.freecodecamp.com/en/challenges/basic-javascript/understand-string-immutability). Happy coding!
