### ISSUE TITLE
Code passes while one of the tests should clearly fail. 

### ISSUE THREAD

**Issue by forkerino** [freeCodeCamp/freeCodeCamp#13831]
Challenge [copy-an-array-with-the-spread-operator](http://beta.freecodecamp.com/en/challenges/basic-data-structures/copy-an-array-with-the-spread-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I didn't use the spread operator as required.
```js


function copyMachine(arr, num) {
  let newArr = [];
  while (num >= 1) {
    // change code below this line
    newArr.push(arr);
    // change code above this line
    num--;
  }
  return newArr;
}

// change code here to test different cases:
console.log(copyMachine([true, false, true], 2));

```

**Comment by dhcodes** [comment]
Confirmed. Seems [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/d424b7331ded350e297387b134f5ab8e85631839/seed/challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json#L293) is not working correctly. Might be easier to change it to a `code.match` Regex test.

**Comment by Manish-Giri** [comment]
@dhcodes I can do this...
