### ISSUE TITLE
Instruction is not clear in "Waypoint: Style Text Input as Form Control

### ISSUE THREAD

**Issue by iamprakashom** [FreeCodeCamp/freecodecamp#1383]
http://www.freecodecamp.com/challenges/waypoint-style-text-inputs-as-form-controls
Third instruction "Give the text input in your form the class 'form-control' " is not clear.  Since, code to be written in editor is always in pink colour. But ".....input in your form the class" is in pink. And this sentence also sounds confusing.
Screenshot:

![freecodecamp1](https://cloud.githubusercontent.com/assets/4259587/8893987/d22ac03c-33c3-11e5-8f22-8a3245449af8.jpeg)

**Comment by krisgesling** [comment]
I just looked at /seed/challenges/bootstrap.json in Github and line 1231 has:
<code>"assert($('input[type=\\'text\\']').hasClass('form-control'), 'Give the text <code>input</code> in your form the class \"form-control\".')",</code>

Seems that QuincyLarson fixed this on 20 June, so I'm assuming it just hasn't yet been pushed out.

**Comment by krisgesling** [comment]
Seems this has been reported a few times - bug #'s 1383, 1328, 1281, 1082

**Comment by iamprakashom** [comment]
hoping @QuincyLarson  will push the changes out soon.

**Comment by rohit44x** [comment]
![freecodecamp_issue](https://cloud.githubusercontent.com/assets/15889350/11246053/07c61138-8e3c-11e5-9c5f-0b61738bde75.png)

says"Give the text input in your form the class form-control."..what to do..

**Comment by SaintPeter** [comment]
@rohit44x - For assistance with code, please use the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help?utm_source=share-link&utm_medium=link&utm_campaign=share-link).  There are plenty of helpful folks there who can answer your questions.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by rohit44x** [comment]
@SaintPeter - Thanks for your guidance, I will surely put it across in 'Help Chat Room'.

**Comment by renderbull** [comment]
Hello Fellow Coders

That issue has been resolved by freecodecamp team. If anybody is still finding it difficult to solve, then please check attached image for solution.

Happy Coding

![screenshot_2016-06-24_12-39-14](https://cloud.githubusercontent.com/assets/19991461/16330746/323cd4c8-3a09-11e6-8146-7b4e4a61acf1.png)

**Comment by WaqasEhmed** [comment]
Solved.
`<input type="text" class="form-control" placeholder="cat photo URL" required>
    <button type="submit" class="btn btn-primary"><i class="fa fa-paper-plane"></i> Submit</button>`

**Comment by dwd2010** [comment]
@WaqasEhmed this place is not for put answer on here. You could help people at FreeCodeCamp chat room. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by WaqasEhmed** [comment]
Oh I'm really sorry. Thanks for informing me. Takecare

**Comment by QuincyLarson** [comment]
No need to apologize. I just want to make sure you get good help quickly :)

- Quincy Larson
teacher at FreeCodeCamp.com

Follow my writing about technology:
medium.com/@quincylarson
quora.com/profile/Quincy-Larson
<http://quora.com/profile/Quincy-Larson/answers?sort=views>

**Comment by WaqasEhmed** [comment]
I got it :+1:

**Comment by hwjoshi** [comment]
> 
Solved.
<input type="text" class="form-control" placeholder="cat photo URL" required> <button type="submit" class="btn btn-primary"><i class="fa fa-paper-plane"></i> Submit</button>
