### ISSUE TITLE
Target Even Numbered Elements' Test Typo

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/freeCodeCamp#13836]
#### Challenge Name

https://www.freecodecamp.com/challenges/target-even-numbered-elements-using-jquery

#### Issue Description

[This](https://github.com/freeCodeCamp/freeCodeCamp/blob/d424b7331ded350e297387b134f5ab8e85631839/seed/challenges/03-front-end-libraries/jquery.json#L1416) line needs to be changed so it sounds more natural.

```diff
- All the <code>target</code> elements that computer considers even should shake.
+ All the <code>target</code> elements that the computer considers even should shake.
```

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Chrome OS
* Mobile, Desktop, or Tablet: Laptop

#### Screenshot

![screenshot 2017-03-09 at 23 14 52](https://cloud.githubusercontent.com/assets/2754821/23785799/47c82cb2-051e-11e7-8215-6a4a16f61982.png)

**Comment by austinthiel** [comment]
I'll pick this one up if that's alright :)
