### ISSUE TITLE
I can't get into my account.  It is in an endless loop.

### ISSUE THREAD

**Issue by jfitz524** [freeCodeCamp/freeCodeCamp#13839]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by Bouncey** [comment]
Hi @jfitz524, sorry to hear you are having trouble signing in. Can you please explain in more detail and perhaps include screenshots if appropriate.

We will try to get this resolved for you

cc\ @QuincyLarson @BerkeleyTrue

**Comment by jfitz524** [comment]
Thanks! All I know is that when I go to freecodecamp.com, the screen is frozen.  I was doing the "seek and destroy" challenge and I got a message saying something about an endless loop and then the screen froze and I can't do anything.  It has been this way for about 24 hours now.

**Comment by Manish-Giri** [comment]
@jfitz524 Try the instructions in [this link](https://forum.freecodecamp.com/t/free-code-camp-infinite-loop-protection/19550). It should fix the loop.

**Comment by jfitz524** [comment]
Thank you!

**Comment by OFFLlNE** [comment]
@jfitz524 did that fix it for you?

**Comment by jfitz524** [comment]
Yes, it did.  Thanks!

**Comment by jfitz524** [comment]
Well, maybe not.  I finished the Seek and Destroy challenge, but it is not grayed out.

**Comment by raisedadead** [comment]
@jfitz524 Were you able to continue your progress? Is this still an issue? 
Please comment back to re-open. Thanks.
