### ISSUE TITLE
Issue getting completion on Waypoint: Change the Font Size of an Element

### ISSUE THREAD

**Issue by EricaLFHernandez** [FreeCodeCamp/FreeCodeCamp#1384]
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue.

![screen shot 2015-07-26 at 10 36 11 am](https://cloud.githubusercontent.com/assets/13508610/8894379/460175ec-3382-11e5-9c9c-9a26d24c43d0.png)

I can't seem to get the site to register that my p elements contain the first words of Kitty Ipsum, no matter what I try.

**Comment by YannyRamz** [comment]
The second paragraph should say "Purr jump eat...."

**Comment by EricaLFHernandez** [comment]
Oh! Thanks for your help!
