### ISSUE TITLE
[beta] Claim your responsive design web design certificate - text needs editing 

### ISSUE THREAD

**Issue by sue888** [freeCodeCamp/freeCodeCamp#13843]
[Claim your responsive design web design certificate](https://beta.freecodecamp.com/en/challenges/claim-your-responsive-web-design-certificate/claim-your-responsive-web-design-certificate) needs a little editing - two of the steps mention beginning and intermediate algorithm scripting.  

![image](https://cloud.githubusercontent.com/assets/11083357/23812433/5d759998-058f-11e7-89b0-c0b7ec10a268.png)

User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.

**Comment by wilsonja-osu** [comment]
It would probably read better if the first page (1/4) only stated verification of requirements in general. While stating requirements up front can be useful, it does introduce some redundancy. I can update the text if that is desired.

**Comment by vkings1** [comment]
This is so  great.

**Comment by systimotic** [comment]
Thanks for reporting this issue @sue888!

The new certificates in the beta have not yet been created. What you're seeing the old copy from the original Front End Certificate. We're working on resolving this in #12794. I'm closing this as a duplicate.

Happy coding!
