### ISSUE TITLE
the bootstrap button doesn't need a-type="Submit"

### ISSUE THREAD

**Issue by eixan** [freeCodeCamp/freeCodeCamp#13848]
#### Challenge Name

http://bit.ly/2neOzFF

#### Issue Description

copying this part -type="Submit"- of the lesson's previous code for  making buttons isn't necessary. All you have to do is use the button tag and reference class 'btn"

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by austinthiel** [comment]
`type="Submit"` is only required when submitting a form. Since the challenge doesn't ask you to wrap the button in a form, the `Submit` type doesn't need to be enforced. It is just a plain old button.

(I could be completely wrong, still new here ;))

**Comment by systimotic** [comment]
Hi @eixan! Thank you for reporting this issue.

The statement in your description is correct. The `type` attribute is not required for this challenge. The challenge works both with or without this attribute.

Can you please elaborate on what appears to be the bug with this challenge?

**Comment by erictleung** [comment]
Closing as stale. Feel free to comment back if you're still having an issue with this challenge or you can elaborate on what the bug is. Happy coding!
