### ISSUE TITLE
Problem with "Add Font Awesome Icons to our Buttons" lesson

### ISSUE THREAD

**Issue by eixan** [freeCodeCamp/freeCodeCamp#13849]
#### Challenge Name
https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-our-buttons

#### Issue Description
Can't add icon

#### Browser Information

Version 56.0.2924.87 (64-bit)
Windows 10 64bit
Laptop

#### Your Code

```js

<button class="btn btn-block btn-primary"><i class="fa fa-into-circle"></i>Like</button>




```
#### Screenshot

![sadf](https://cloud.githubusercontent.com/assets/26262465/23819886/cbacde4c-05d2-11e7-93c9-875725551ddf.png)

**Comment by Manish-Giri** [comment]
@eixan Please read the instructions - 
> Use Font Awesome to add a thumbs-up icon to your like button by giving it an i element with the classes fa and fa-thumbs-up.

You need to use the `fa fa-thumbs-up` classes, while you're using the example code, which is `fa-info-circle`, not `fa-into-circle`.

If you need assistance with this challenge, please visit the [Help Room](https://gitter.im/FreeCodeCamp/Help). The issue tracker is for reporting bugs with the website itself. Happy Coding!

**Comment by eixan** [comment]
thanks  for the help.
