### ISSUE TITLE
Interestesting... what's going on here?

### ISSUE THREAD

**Issue by ar94952** [freeCodeCamp/freeCodeCamp#13857]
Challenge [Concatenating Strings with the Plus Equals Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-the-plus-equals-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%3B%0AourStr%20%2B%3D%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20%22This%20is%20the%20first%20sentence.%20%22%3B%0AoutStr%20%2B%3D%20%22This%20is%20the%20second%20sentence.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The preview box states, "referenceError"... like okay?

My code:
```javascript

// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line

var myStr = "This is the first sentence. ";
ourStr += "This is the second sentence.";



```

**Comment by ar94952** [comment]
update:  the instruction was vague so I tried:

var myStr = "This is the first sentence. ";
myStr += "This is the second sentence.";

lol.

**Comment by systimotic** [comment]
The reason for the error was that your code said `outStr +=` instead of `ourStr +=`, and `outStr` is not defined.

We're working on clarifying this challenge in https://github.com/freeCodeCamp/freeCodeCamp/pull/13612

Before reporting an issue, please check whether this is really an issue with freeCodeCamp, and not your code, in the [chatroom](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

Will the updates in #13612 take away the confusion you had?

**Comment by texas2010** [comment]
it is very clear Instructions
Build myStr over several lines by concatenating these two strings:
"This is the first sentence. " and "This is the second sentence." using the += operator.

it said myStr.   Sorry challenge didnt asked you write ourStr.

I could understand this Instructions myself.

**Comment by texas2010** [comment]
but we could change variables name. so it will be less misunderstand?

**Comment by ar94952** [comment]
You don't need to change anything.  I understand that some challenges need to be vague to encourage learner to do a little research.  Part of problem-solving...

Thanks guys!

**Comment by systimotic** [comment]
@texas2010 Keep in mind that it's easier to understand if you already know how it works. 🙂 I can see how one may have gotten confused here, but I don't think we can do more to prevent it than what we're currently working on.

**Comment by texas2010** [comment]
@systimotic no problem.
