### ISSUE TITLE
Success modal needs min-height for Safari

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/freeCodeCamp#13851]
As said in the title, without a `min-height` property on the `div.modal-content` success modal, the modal shrinks with the size of the window.

Screenshot:
![Modal](http://i.imgur.com/gYlA4bp.png)

**Comment by Douglasdc3** [comment]
Tested on Safari 10.0.2 and the modal looks fine 
<img width="713" alt="screen shot 2017-03-11 at 23 56 48" src="https://cloud.githubusercontent.com/assets/5066883/23827554/9f858884-06b6-11e7-9908-40eea427db4d.png">

What version of Safari does this bug happen?

**Comment by dhcodes** [comment]
You're right. Must have been some localhost anomaly. Thanks @Douglasdc3
