### ISSUE TITLE
Curious bug with Adjust Margin challenge Beta

### ISSUE THREAD

**Issue by Skarrix** [freeCodeCamp/freeCodeCamp#13860]
Challenge [adjust-the-margin-of-an-element](http://beta.freecodecamp.com/en/challenges/basic-css/adjust-the-margin-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Challenge requires camper to change `margin: 10px;` to `margin: 20px;` for
`  .green-box {
    background-color: green;
    padding: 20px;
    margin: 10px;
  }` 

When running it initially the test processes it fine and accepts the answer. However, if I close the pop-up message instead of continuing to the next challenge and then Clear my Code using the Reset button (in order to play with the code before moving on, for example), the bug occurs. When repeating the challenge (changing 10px to 20px for green box, all other code left alone) and submitting Run Test, the code will automatically revert to 10px every time. 

I've gotten it to stop the behaviour both by refreshing the page or by typing and then backspacing a space elsewhere, then Running Test again. The bug also does not appear if I type or alter code elsewhere in the editor. 

It is repeatable in Incognito mode for Chrome, but when trying to repeat the issue for Firefox I could not get it to accept the solution of 20px *whatsoever*.

```html


<style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .yellow-box {
    background-color: yellow;
    padding: 10px;
  }
  
  .red-box {
    background-color: red;
    padding: 20px;
    margin: 20px;
  }

  .green-box {
    background-color: green;
    padding: 20px;
    margin: 20px;
  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

```

**Comment by systimotic** [comment]
Hi @Skarrix! Thank you for reporting this issue.

Things not working in Firefox is a known issue, see #10749 

A step by step on how to reproduce:
1. Change the `1` on line 29 to a `2`
2. Run the tests
3. Close the success modal
4. Click the "Reset" button
5. Click "CLEAR MY CODE"
  The `2` will go back to a `1`.
6. Change the `1` to a `2` again.
7. Run the tests.

The `2` will go back to a `1` again.

This is a very weird issue 😕

**Comment by Douglasdc3** [comment]
Confirmed bug is not browser depended both Chrome & Safari (latest versions) on Mac OSx have this issue.

**Comment by mpontus** [comment]
Can't reproduce the issue as per [these instructions](https://github.com/freeCodeCamp/freeCodeCamp/issues/13860#issuecomment-285906489). The end result is tests passing.

Tested in Firefox and Chrome: 
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0`
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36`

**Comment by nicksavov** [comment]
I also can't reproduce the issue. I'm using Firefox 57 on Mac.

We need a Windows user to test it in Firefox

**Comment by nicksavov** [comment]
I tested on a Windows computer with Firefox 57 and I couldn't reproduce the issue.

@Skarrix @systimotic @Douglasdc3 , could you check the issue one more time? Looks like it's resolved.

**Comment by systimotic** [comment]
Thanks for checking this @mpontus @nicksavov! Some recent changes to the beta fixed this issue.

Happy coding!
