### ISSUE TITLE
[beta] Add images to help visualize concepts

### ISSUE THREAD

**Issue by Atomk** [freeCodeCamp/freeCodeCamp#13861]
Challenge [learn-how-bezier-curves-work](http://beta.freecodecamp.com/en/challenges/applied-visual-design/learn-how-bezier-curves-work) has an issue.

I think the "Applied Visual Design" makes a lot of assumptions on the user's background knowledge, and this is evident in the challenge linked above. I know what an X-axis is and what Bezier curves are and how they work, but I still find the description of the challenge unnecessarily detailed and confusing. Who wrote it probably put a lot of effort trying to explain the concept with words, but wouldn't be easier to use images? Or at least provide a link to a video or something more practical/visual. It would make life easier to non-English people too.

I took this challenge as an example but it's just one of many, in my opinion of course.
I can only talk about this section of the curriculum but probably a lot of other challenges could benefit from visual hints too.

**Comment by systimotic** [comment]
I like the idea 👍 We do have to keep accessibility in mind. The images should supplement the text, not replace it.

Do you have any sketches or links of good examples?

**Comment by Atomk** [comment]
@systimotic [This website](http://cubic-bezier.com) is pretty much what I was thinking about, but it could be made even simpler in my opinion.

**Comment by HKuz** [comment]
@Atomk thanks for bringing this up - I agree that a number of challenges (especially the animation ones you mention) were rather hard to explain using text only. Generally, we tried to avoid using images in the new curriculum but there are a few places where they'd be helpful. The site you linked to shows the differences well, only thing to be aware of is that any image we link to/use is under a Creative Commons license.

Also, definitely feel free to suggest any re-writes of the text, especially if you think it will be more clear for non-native English speakers 👍

**Comment by systimotic** [comment]
@Atomk That site is really nice!

As Heather said, specific suggestions on how to improve these challenges are welcome! 👍

**Comment by carpben** [comment]
I was reading the lesson and instruction, and found it difficult to understand as well. I agree AtomK. http://cubic-bezier.com/ makes it very easy to understand. Even more. 
The example given (0.25, 0.25, 0.75, 0.75) is a somewhat unique case in which the curve (in this case linear line) goes through both points. I find it misleading, as one might expect this to be a general role.
