### ISSUE TITLE
Build a Product Landing Page -- YouTube Video Playback Error

### ISSUE THREAD

**Issue by zakyrie** [freeCodeCamp/freeCodeCamp#13868]
#### Challenge Name
_Applied Responsive Web Design Projects: Build a Product Landing Page_

#### Challenge Link
http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-product-landing-page

#### Issue Description
Embedded YouTube Video fails to load and instead displays error when clicked on, even when the browser is refreshed. See screenshot below.

#### Browser Information
* Browser Name, Version:  **Google Chrome, Version 56.0.2924.87 (64-bit)**
* Operating System: **Windows 10 Pro 64Bit**
* Mobile, Desktop, or Tablet: **Desktop**

#### Screenshot
![image](https://cloud.githubusercontent.com/assets/16407117/23829074/6cf4e8d8-06f7-11e7-8c31-4c701d9caca4.png)

**Comment by erictleung** [comment]
Closing as duplicate https://github.com/freeCodeCamp/freeCodeCamp/issues/12753. Feel free to continue the discussion over there. Happy coding!
