### ISSUE TITLE
[Map the Debris] Units of Period Should be Specified as seconds

### ISSUE THREAD

**Issue by RadDog25** [freeCodeCamp/freeCodeCamp#13864]
#### Challenge Name
Map the Debris

#### Issue Description
Not exactly a bug, but I think that the question could be improved. Although it can be assumed, it would be a bit better if the units of the expected orbital period was specified to be seconds. Even changing the first sentence to something like this would be good:

Return a new array that transforms the element's average altitude into their orbital periods(seconds).

**Comment by erictleung** [comment]
@RadDog25 thanks for the issue. I like the specificity of the change. So let's change it to be something like this

> Return a new array that transforms the element's average altitude into their orbital periods (in seconds).
