### ISSUE TITLE
Won't move on to next Waypoint

### ISSUE THREAD

**Issue by mal8811** [FreeCodeCamp/FreeCodeCamp#1386]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element won't move on to next Waypoint. After changing the code as indicated and clicking the "Go to my next challenge" button, it goes to a 502 Bad Gateway page instead of going to the next Waypoint.

The Waypoint (Waypoint 10) is checked off on the map though, so it does know that the challenge has been completed, but it doesn't link to the next challenge.

**Comment by haunja** [comment]
I got the same behavior
![capture](https://cloud.githubusercontent.com/assets/5329973/9051146/a6e2d65a-3a24-11e5-9f24-52c89490631a.PNG)

**Comment by BerkeleyTrue** [comment]
I'll take a look at the logs and see what is going on.

**Comment by BerkeleyTrue** [comment]
Seems NGINX is complaining about bad headers. The good thing is it seems to be just that url. I'll try to tackle this later tonight.

**Comment by mistamadd001** [comment]
I am still having this issue, as at 4.10am Tuesday 4 Aug

**Comment by QuincyLarson** [comment]
This seems to be resolved. I'm opening a ticket for another issue related to sending campers to the wrong page.
