### ISSUE TITLE
Commented code evaluated in tests

### ISSUE THREAD

**Issue by lachlan-eagling** [freeCodeCamp/freeCodeCamp#13865]
#### Challenge Name

Replacing If Else Chains with Switch

#### Issue Description

Tests are evaluating commented out code. In cases where existing if/else block is left in place and commented rather than deleted the tests fail.

Looks to be similar if not the same issue affecting a different challenge reported in #11360

#### Browser Information

* Chrome, Version: 56.0.2924.87
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

![untitled](https://cloud.githubusercontent.com/assets/8456105/23828563/07185c06-072a-11e7-9f2b-e19014eecc39.jpg)
function chainToSwitch(val) {
  var answer = "";
  // Only change code below this line
  
//   if (val === "bob") {
//     answer = "Marley";
//   } else if (val === 42) {
//     answer = "The Answer";
//   } else if (val === 1) {
//     answer = "There is no #1";
//   } else if (val === 99) {
//     answer = "Missed me by this much!";
//   } else if (val === 7) {
//     answer = "Ate Nine";
//   }
  switch(val){
    case "bob":
      answer = "Marley";
      break;
    case 42:
      answer = "The Answer";
      break;
    case 1:
      answer = "There is no #1";
      break;
    case 99:
      answer = "Missed me by this much!";
      break;
    case 7:
      answer = "Ate Nine";
      break;
  }
  // Only change code above this line  
  return answer;  
}

// Change this value to test
chainToSwitch(7);

```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/8456105/23828565/17f8d0fa-072a-11e7-9df9-f48c008737fd.png)

**Comment by erictleung** [comment]
@lachlan-eagling thanks for the issue. This seems to be a more systemic problem than just changing the one or two challenge tests. The other issue you've linked to is more general and has been opened before yours. I'll be closing this issue as a duplicate. Thanks again for bringing up the issue. Feel free to continue the discussion on #11360. Happy coding!
