### ISSUE TITLE
Perhaps change the example

### ISSUE THREAD

**Issue by ar94952** [freeCodeCamp/freeCodeCamp#13870]
Challenge [Accessing Objects Properties with Bracket Notation](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-bracket-notation#?solution=%0A%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%20%22an%20entree%22%3A%20%22hamburger%22%2C%0A%20%20%22my%20side%22%3A%20%22veggies%22%2C%0A%20%20%22the%20drink%22%3A%20%22water%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20entreeValue%20%3D%20testObj%5B%22hamburger%22%5D%3B%20%20%20%2F%2F%20Change%20this%20line%0Avar%20drinkValue%20%3D%20testObj%5B%22water%22%5D%3B%20%20%20%20%2F%2F%20Change%20this%20line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript


// Setup
var testObj = {
  "an entree": "hamburger",
  "my side": "veggies",
  "the drink": "water"
};

// Only change code below this line

var entreeValue = testObj["an entree"];   // Change this line
var drinkValue = testObj["the drink"];    // Change this line

```
EXAMPLE:  
var myObj = {
  "Space Name": "Kirk",
  "More Space": "Spock"
};
myObj["Space Name"]; // Kirk
myObj['More Space']; // Spock

ISSUE:
the example doesn't match the exercise causing confusion.

**Comment by erictleung** [comment]
@ar94952 thanks for the issue. Can you elaborate on how the example doesn't match the exercise and causing confusion? I think the example shows that you can use the property names (e.g. `Space Name`) to access its value (e.g. `Kirk`) as shown in the example as `myObj["Space Name"]` and its value is `Kirk`.

Using the same logic, you should be able to find the corresponding value of, say, the property `an entree` using the same bracket notation.

In general, if you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). But please let us know how it is confusing. We strive to make the challenges as clear as possible.

**Comment by ar94952** [comment]
the following was not included in the example:

var someValue =
var somValue =

including only the other side of the equation had me confused for a few seconds.

**Comment by erictleung** [comment]
@ar94952 thanks for the clarification. This seems to be more of a coding question, so instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390). Thank you, and happy coding!

**Comment by ar94952** [comment]
Thanks for your help.    // Setup
var testObj = {
  "an entree": "hamburger",
  "my side": "veggies",
  "the drink": "water"
};

// Only change code below this line

var entreeValue = testObj ["an entree"];   // Change this line
var drinkValue = testObj ["the drink"];    // Change this line
