### ISSUE TITLE
Beta: Challenge won't accept shorthand hex code values

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/freeCodeCamp#13871]
#### Challenge Name
Applied Visual Design: Create a Gradual CSS Linear Gradient

[Challenge Link](http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-a-gradual-css-linear-gradient)

#### Issue Description

Shorthand values `#CFF` and `#FCC` aren't accepted as the linear gradient values. Only `#CCFFFF` and `#FFCCCC` are accepted. 

Here's a [fiddle](https://jsfiddle.net/gvoohrv4/1/) which has two `div`s with both types of values. They show the same gradient.

Another point is that the default code has the `margin` value as `margin:  50 auto;`.  We should probably have `50px` in there, showing best practices. JSFiddle doesn't seem to accept `50` as a valid margin value ( try removing `px` in the linked fiddle).

The test for the challenge is [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/f7928b79fda210bd6d544c910021269104a3942f/seed/challenges/01-responsive-web-design/applied-visual-design.json#L1765). I can make a PR for this.
#### Browser Information

* Browser Name, Version: Google Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![untitled](https://cloud.githubusercontent.com/assets/11348778/23830007/410efc52-06d6-11e7-8e88-2d362bf8c169.png)

**Comment by erictleung** [comment]
You might need to specify in the instructions to use hex codes. As it was [pointed out](https://github.com/freeCodeCamp/freeCodeCamp/pull/13615#issuecomment-282646363), there are many ways to specify a color.

**Comment by MiloATH** [comment]
This should test for both:
`code.match(/background:\\s*?linear-gradient\\(35deg,\\s*?(#CCFFFF|#CFF),\\s*?(#FFCCCC|#FCC)\\);/gi)`
Also, we could update the message to say only use hex colors.
@Manish-Giri have you got this?

**Comment by Manish-Giri** [comment]
@MiloATH Yeah, I'll look at this.
