### ISSUE TITLE
Fading an Element from Left to Right allows incorrect solution (BETA)

### ISSUE THREAD

**Issue by Skarrix** [freeCodeCamp/freeCodeCamp#13875]
Challenge [create-visual-direction-by-fading-an-element-from-left-to-right](http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-visual-direction-by-fading-an-element-from-left-to-right) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Test completes if the opacity function is set in the wrong place, rather than only when it is set under @Keyframes. Linked code passed successfully. 

```html


<style>

  #ball {
    width: 70px;
    height: 70px;
    margin: 50 auto;
    position: fixed;
    left:20%;
    border-radius: 50%;
    background: linear-gradient(
      35deg,
      #ccffff,
      #ffcccc
    );
    opacity: 0.1;
  animation-name: fade;
  animation-duration: 3s;
  }

  @keyframes fade {
    50% {
      left:60%;
      
    }
  }

</style>

<div id="ball"></div>

```

**Comment by HKuz** [comment]
@Skarrix - thanks for pointing this out! Yes, looks like the current test for this challenge is only using a simple regex to check for the presence of the `opacity` property in the code somewhere. I think the test can be refined to make sure it's in the `@keyframes` rule.

Anyone looking to level up their regex skills and help out, please refer to the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) and ask any questions in the [Contributors Chat Room](https://gitter.im/FreeCodeCamp/Contributors). You can find the code for this test [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/applied-visual-design.json#L2281). Thank you! 🚀 🤖 🔩

**Comment by Manish-Giri** [comment]
@HKuz I'll take this! Always up for a regex challenge 😛

**Comment by HKuz** [comment]
Ha! A worthy quest, good luck!
