### ISSUE TITLE
Bonfire: Roman Numeral Converter accepts IIII instead of IV as 4

### ISSUE THREAD

**Issue by hlminh2000** [FreeCodeCamp/freecodecamp#1387]

**Comment by royshouvik** [comment]
Hi @hlminh2000  , Please provide more details about the issue like the code you are using and the snapshot of the problem. Thank you.

**Comment by henkekm** [comment]
IIII is an appropriate Roman Numeral for four according to Benjamin Hall Kennedy: https://archive.org/stream/revisedlatinprim00kenniala#page/46/mode/2up

**Comment by hlminh2000** [comment]
Thank you for the clarification, I should have done further research before
reporting the issue.

Best,
Minh

On Sun, Jul 26, 2015 at 10:21 PM, Kevin Henke <notifications@github.com>
wrote:

> IIII is an appropriate Roman Numeral for four according to Benjamin Hall
> Kennedy:
> https://archive.org/stream/revisedlatinprim00kenniala#page/46/mode/2up
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/freecodecamp/issues/1387#issuecomment-125064444>
> .
>



-- 
*Ha Le Minh*

**Comment by royshouvik** [comment]
@hlminh2000 Please consider closing this issue if your problem has been resolved. Thank you.
