### ISSUE TITLE
My answer is wrong but I passed my test

### ISSUE THREAD

**Issue by kuanhsuh** [freeCodeCamp/freeCodeCamp#13886]
Challenge [use-destructuring-assignment-with-the-rest-operator-to-reassign-array-elements](http://beta.freecodecamp.com/en/challenges/es6/use-destructuring-assignment-with-the-rest-operator-to-reassign-array-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


const source = [1,2,3,4,5,6,7,8,9,10];
// change code below this line
const [,,,arr] = source; // change this
// change code below this line
console.log(arr); // should be [3,4,5,6,7,8,9,10]
console.log(source); // should be [1,2,3,4,5,6,7,8,9,10];

```

I double check my answer in my console. And arr is 4 not  [3,4,5,6,7,8,9,10]

**Comment by wilsonja-osu** [comment]
Yes, looking at the ([code for this challenge](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/es6.json#L490-L493)), those test have yet to be written.

**Comment by Manish-Giri** [comment]
I'll try to do this...

**Comment by uandrew** [comment]
I actually just pressed enter without writing code and it passes
