### ISSUE TITLE
I got this problem right, but test not passing

### ISSUE THREAD

**Issue by kuanhsuh** [freeCodeCamp/freeCodeCamp#13889]
Challenge [understand-the-differences-between-import-and-require](http://beta.freecodecamp.com/en/challenges/es6/understand-the-differences-between-import-and-require) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js

import { capitalizeString } from "string_functions"

capitalizeString("hello!");

```

**Comment by crama1990** [comment]
Yeah

**Comment by Manish-Giri** [comment]
Same problem as #12739. Can be closed for now.
