### ISSUE TITLE
Bug (Can't go to next challenge)

### ISSUE THREAD

**Issue by gjokomm** [FreeCodeCamp/freecodecamp#1388]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue.  Here are the 2 criteria for going to the next challenge "1.Your page should have an image element. 2. Your image should have have a src attribute that points to the kitten image."

![](http://i.imgur.com/upFsnE3.png)

![](http://i.imgur.com/keJe8HK.png)

It show that only the first goal is fulfilled, but booth are met.

**Comment by royshouvik** [comment]
Hi @gjokomm , you need use the short url provided on the challenge, instead of the long one. Please check if this resolves your issue.

**Comment by gjokomm** [comment]
After I logged in and clicked on the "Learn" button on the menu, that challenge was skipped and I've got the next one (adding border around an image).

**Comment by orvi2014** [comment]
Can anyone explain me why do I need to short URL instead of original link ?

**Comment by royshouvik** [comment]
@orvi2014 On a real html page, both the short and long URL would give identical result (the longer one would a bit faster too). But in this case, there is a test (the second one) which explicitly matches against the short URL(since that is what mentioned on the instruction). I hope this answers your question.

**Comment by NyanSuslik2002** [comment]
stupid

**Comment by Joephet** [comment]
copy the provide link bellow..

**Comment by amruthcharan** [comment]
I used the long url and still shows the same error!

**Comment by belatrixi** [comment]
I get the same error. :(
