### ISSUE TITLE
My profile is not showing all my work

### ISSUE THREAD

**Issue by pdotsani** [FreeCodeCamp/FreeCodeCamp#1389]
My profile is not showing all my progress with bonfires, ziplines, and basejumps as I have completed them all.

**Comment by benschenker** [comment]
Is this still an issue for you?

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.

**Comment by shiwasreet** [comment]
my progress in freecodecamp has disappeared :(
