### ISSUE TITLE
Clean all lint errors

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/freecodecamp#139]
Current state of app is horribly inconsistent. An eslint file and task has been added. 

All files created by this repository needed to be linted and corrected.

To run lint task in the command line run `npm run lint`

This should be done in the Reactify branch

**Comment by BerkeleyTrue** [comment]
Anyone want to help out with this? There are a ton of files that are not complying.

**Comment by terakilobyte** [comment]
I've gone ahead and enabled eslint in webstorm as well as downloaded the
package, so I'm seeing the errors.

Aside from unifying spacing (2 or 4, I prefer 2), I think we need to
normalize on code structure.

As I go through I'll modify files to comply to our current eslint file.

**Comment by terakilobyte** [comment]
Quincy your thoughts on universal spacing and code styling?

**Comment by terakilobyte** [comment]
I've brought our gulpfile in line with the linter.

**Comment by terakilobyte** [comment]
Closing this issue as we're almost entirely done. As we move the views over to react the rest will be snuffed out anyway.
