### ISSUE TITLE
Misleading Instructions in 'ES6: Set Default Parameters' Challenge

### ISSUE THREAD

**Issue by SebastianPetak** [freeCodeCamp/freeCodeCamp#13903]
#### Challenge Name

[ES6: Set Default Parameter for Your Functions](http://beta.freecodecamp.com/en/challenges/es6/set-default-parameters-for-your-functions)

#### Issue Description

The current instructions are misleading. They currently read:
* Modify the function `increment` by adding default parameters so it will always return a valid number and it will add 1 to `number` if `value` is not specified.

The modification made to the function `increment` in the code below do not cause the function to always return a valid number, for instance:
* `increment('foo') // returns "foo1"`

#### Browser Information

* Browser Name, Version: Chromium 55.02883.87 (64-bit)
* Operating System: Ubuntu 16.04, 64 bit-OS
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
'use strict';
function increment(number, value = 1) {
    return number + value;
}
console.log(increment(5, 2)); // returns 7
console.log(increment(5)); // returns NaN
```

#### Suggested Change
Rewrite the instructions to read:
* Modify the function `increment` by adding default parameters so that it will add 1 to `number` if `value` is not specified.

#### Screenshot

![defaultparameterspass](https://cloud.githubusercontent.com/assets/18408781/23878875/e3ebdc8c-0817-11e7-9399-24d5ed39e5bc.png)

**Comment by raisedadead** [comment]
@SebastianPetak Thanks for the report. I agree what you are suggesting is valid, sorry about the delay in getting back.

Potential contributors, the modified instructions should read:

> Modify the function `increment` by adding default parameters so that it will add 1 to `number` if `value` is not specified.

Refer [Guidelines for Contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by jiakim** [comment]
Hello! This is my first time contributing to open source and I'd like to give it a shot, is that alright?

**Comment by SebastianPetak** [comment]
@jiamkim Awesome!

**Comment by eberrios** [comment]
`const increment = ((number, value = 1) => {  return number + value;});`
