### ISSUE TITLE
Solution is correct in Google Chrome but not working in Safari

### ISSUE THREAD

**Issue by obogorr** [freeCodeCamp/freeCodeCamp#13906]
Challenge [Set the Font Family of an Element](https://www.freecodecamp.com/challenges/set-the-font-family-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by Manish-Giri** [comment]
Seems to be working fine for me, on Safari - 

![screenshot 2017-03-13 20 59 37](https://cloud.githubusercontent.com/assets/11348778/23881355/6d64b494-0830-11e7-8397-5497afda6711.png)

**Comment by obogorr** [comment]
This one and the next one continue to fail the step in recognizing the Monotype font
<img width="1427" alt="screen shot 2017-03-13 at 8 28 18 pm" src="https://cloud.githubusercontent.com/assets/26394800/23881423/b8e9f64a-0830-11e7-9f3c-972a51218e85.png">
<img width="1423" alt="screen shot 2017-03-13 at 9 03 59 pm" src="https://cloud.githubusercontent.com/assets/26394800/23881425/c17fcabe-0830-11e7-8a7a-0ad39b1c50e8.png">

**Comment by obogorr** [comment]
<img width="1427" alt="screen shot 2017-03-13 at 9 06 46 pm" src="https://cloud.githubusercontent.com/assets/26394800/23881480/0fccb57e-0831-11e7-9248-3247d228d886.png">
But then it works fine in Google Chrome.

**Comment by obogorr** [comment]
After some messing around, I figured it out.  I have dyslexia and utilize open dyslexic extension to assist with reading in Safari but this was conflicting with the Monospace.  I dialed temporarily and it submitted normally.

**Comment by erictleung** [comment]
Closing as not an issue anymore. Happy coding!
