### ISSUE TITLE
[Beta] Get Set for our Responsive Web Design Projects step 6/7

### ISSUE THREAD

**Issue by Skarrix** [freeCodeCamp/freeCodeCamp#13905]
#### Challenge Name

Applied Responsive Web Design Projects: Get Set for our Responsive Web Design Projects

#### Issue Description

Not sure if intentional or not, but step 6/7 still goes into loading Bootstrap into Codepen even though the curriculum no longer teaches Bootstrap?

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by erictleung** [comment]
@Skarrix thanks for the issue. Bootstrap is still taught in the curriculum. You can see [here](http://beta.freecodecamp.com/en/challenges/bootstrap/use-responsive-design-with-bootstrap-fluid-containers) is the first challenge. It is in the Front End Libraries section. So I think the instructions are still a relevant start to the challenges.

**Comment by erictleung** [comment]
Closing as stale. Happy coding!
