### ISSUE TITLE
Repeated code line has confused me.

### ISSUE THREAD

**Issue by Dannyboi93** [freeCodeCamp/freeCodeCamp#13909]
Challenge [Target the Children of an Element Using jQuery](https://www.freecodecamp.com/challenges/target-the-children-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```
For some reason, target5 has been cloned twice. Anybody know why?

![image](https://cloud.githubusercontent.com/assets/25937833/23890172/767b7ad8-0888-11e7-98b7-8c3ddf4e2c41.png)

**Comment by kot91** [comment]
Looks like this question was answered previously!

https://github.com/freeCodeCamp/freeCodeCamp/issues/5072
augmt's comment:

> Both common.updatePreview$ and common.getJsOutput are called within common.executeChallenge$. They both evaluate JavaScript and that leads to scripts being run twice on resets, test runs, and page load.

**Comment by acinf** [comment]
I also found this bug.

I don't know how the fcc-site interacts with github, but it would be nice to at least be able to connect the 'bug' button to known issues on github so that the user is told that it is a known issue that can't be solved atm.

**Comment by dhcodes** [comment]
This has been fixed on beta. Closing as resolved.
