### ISSUE TITLE
"BETA" ES6: Use the Spread Operator to Evaluate Arrays In-Place

### ISSUE THREAD

**Issue by rhinoted** [freeCodeCamp/freeCodeCamp#13913]
#### ES6: Use the Spread Operator to Evaluate Arrays In-Place

https://beta.freecodecamp.com/en/challenges/es6/use-the-spread-operator-to-evaluate-arrays-inplace

#### Issue Description

Test passes without any modification to the default code.. I just started the challenge and pressed Test.. and it passes...

#### Browser Information

* Browser Name, Version: Firefox 52.0 
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

**Comment by yzhbankov** [comment]
It is because tests not written yet.

**Comment by rhinoted** [comment]
Ah ok.. I noticed that many other challenges makes the same, but not all of them.. Thanks

**Comment by erictleung** [comment]
Closing as related and is sub-issue to https://github.com/freeCodeCamp/freeCodeCamp/issues/12698. Happy coding!
