### ISSUE TITLE
Title Case a Sentence: Unclear what the tests want as output of the function

### ISSUE THREAD

**Issue by arsubbu** [freeCodeCamp/freeCodeCamp#13927]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function titleCase(str) {
  var newString=str.split(" ");
  var newString1="";
  var newString2="\"";
  for(var i=0; i<newString.length;i++)
  {
    
    for(var j=0;j<newString[i].length;j++)
      {
        
        if(j>0)
        {
          
          newString1+=newString[i].charAt(j).toLowerCase();  
          
        }
        else
        {
          newString1=newString[i].charAt(j).toUpperCase();  
          
        }
      }
    newString2+=newString1 + " ";
  }
  newString2=newString2.trim()+ "\""+".";
  return newString2;
}

titleCase("sHoRt AnD sToUt");

```

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

You are doing a little too much.
With the `titleCase("I'm a little tea pot")` you actually need to output in the console `I'm A Little Tea Pot` without the "" and .

I think the tests would use some small tweak to make it more understandable what it should output.
So this is up for first-timer grabs to make the tests look more like that:
`titleCase("I'm a little tea pot")` should return `I'm A Little Tea Pot`.


Thank you, and happy coding.

**Comment by SebastianPetak** [comment]
@OFFLlNE I'd like to make this change.

**Comment by OFFLlNE** [comment]
@SebastianPetak great!
Good luck ;)
