### ISSUE TITLE
[beta] Problem with tests passing

### ISSUE THREAD

**Issue by yzhbankov** [freeCodeCamp/freeCodeCamp#13921]
#### Issue Description

I have a problems with tests passing in such exercises as:
- ES6: Use the Spread Operator to Evaluate Arrays In-Place
- ES6: Write Higher Order Arrow Functions
- ES6: Use the Spread Operator to Evaluate Arrays In-Place
- ES6: Use Destructuring Assignment to Assign Variables from Objects
and others

I think the tests for these exercises are not written yet. I can take this on me.

**Comment by robbawebba** [comment]
@yzhbankov Thanks for submitting this issue! Check out the discussion on ES6 challenges here: 12698. There are some other spin-off issues that reference the ES6 test situation as well: #12902 and #12913.

Unfortunately, the tests are unusable at the moment. By the time the tests are executed, the user's code has already been transpiled to ES5 syntax, making it impossible to test for ES6 syntax 🙁

**Comment by QuincyLarson** [comment]
@yzhbankov @robbawebba these ES6 challenges may be usable now. I think @BerkeleyTrue has gotten them working. We still need tests for these challenges. Would either of you be interested in helping out with this?

**Comment by stephukiwe** [comment]
sure

**Comment by robbawebba** [comment]
@QuincyLarson Absolutely! Should I move this discussion back over to #12698 while working on these tests?

**Comment by QuincyLarson** [comment]
@robbawebba Awesome! We would welcome your help with these! 

And thanks - I'd forgotten about that thread. Agreed - let's move the discussion back over there.
