### ISSUE TITLE
API  Application error

### ISSUE THREAD

**Issue by ChaosPredictor** [freeCodeCamp/freeCodeCamp#13931]
Heroku API link doesn't work.

the page open with: "An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details."

Challenge [Build a Camper Leaderboard](https://www.freecodecamp.com/challenges/build-a-camper-leaderboard) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by erictleung** [comment]
@ChaosPredictor thanks for the issue. Which API was not working for you? They both work for me.

**Comment by ChaosPredictor** [comment]
It was a problem with:
https://fcctop100.herokuapp.com/api/fccusers/top/recent
&
https://fcctop100.herokuapp.com/api/fccusers/top/alltime
links.

**Comment by raisedadead** [comment]
@ChaosPredictor 
Can you re-check if its still the case? These APIs are hosted on Heroku and may have had outage when you accessed them. Also its possible, if you are behind a firewall or network that's blocking them?

Please comment back back if this is still not working for you.
