### ISSUE TITLE
Suggest we remove the example in the test description

### ISSUE THREAD

**Issue by ldwoolley** [freeCodeCamp/freeCodeCamp#13938]
#### Challenge Name
https://www.freecodecamp.com/challenges/use-rgb-values-to-color-elements

#### Issue Description
Before this point in the training, I believe we have consistently used the test descriptions in the bottom left to list the required test, only.  This time, we give an example that is not the test condition in the test description.  So the test says make it black, for example make it orange.  I believe the test should simply state the test condition and let the description in the upper left show the examples.  As it is, the user, has to question, do they want it to be black or do they want it to be orange.
 
#### Browser Information
Chrome Version 56.0.2924.87 (64-bit)
Windows 10 1607 Desktop

#### Screenshot
![2017-03-15](https://cloud.githubusercontent.com/assets/19174921/23961293/ba0108e2-0967-11e7-8dbf-71b9f3a6af86.png)

**Comment by erictleung** [comment]
@ldwoolley yes, this has tripped up some people just copying the code they see in the challenge tests. The example code in the challenge test was a reminder, but I agree, it is in an odd position. 

Let's move that example code

```css
body {
  background-color: rgb(255, 165, 0);
}
```

from the challenge test and into the challenge description with the text like, `"Here's an example of how you'd change the body background to orange using its RGB code."`

**Comment by ldwoolley** [comment]
I can take this one, as long as there is patience with the NOOB in freeCodeCamp.  I have helped several other projects, I think I can sort this out.

**Comment by ldwoolley** [comment]
This code has descriptions in English, German, Spanish, Portuguese, and Russian.  I can do the English, Spanish, and Portuguese, but with German, I don't know the language well enough, and I don't know where to begin with Russian.  Is anyone out there willing to do the German and Russian, or want to do the Spanish?

**Comment by ldwoolley** [comment]
Here is the proposed English changes: https://github.com/freeCodeCamp/freeCodeCamp/compare/staging...ldwoolley:Move-example-out-of-test-2?diff=unified&name=Move-example-out-of-test-2

**Comment by erictleung** [comment]
@ldwoolley thanks for working on this. No worries on having to cover all the languages. Also, I would make the extra code example a bit formatted so it'll look nicer. Now that we're moving the example code to the description, we can make it nicer. So you'll need to create a new line with this code,

```
...
"<blockquote>body {<br>  background-color: rgb(255, 165, 0);<br>}</blockquote>",
...
```

so it'll look like this

```css
body {
  background-color: rgb(255, 165, 0);
}
```

Also, please follow the branch naming convention and name is something like `fix/move-example-out-of-test`

**Comment by ldwoolley** [comment]
Agreed.  I will use the naming convention in the instructions.  The instructions also ask for a complete run on the code to test it out.  It will take me a couple of days to work through that setup.

**Comment by erictleung** [comment]
@ldwoolley thanks again for your interest in working on this! :+1: Let us know in the contributors room if you run into any troubles. First time setting up the project can be intimidating.
