### ISSUE TITLE
Test actually applies to check-boxes and radio buttons

### ISSUE THREAD

**Issue by ldwoolley** [freeCodeCamp/freeCodeCamp#13939]
#### Challenge Name
https://www.freecodecamp.com/challenges/responsively-style-radio-buttons 

#### Issue Description
The current test states: 
> Nest each of your radio buttons inside its own div with the class col-xs-6.

When the actual items tests for:
> Nest each of your radio and checkbox buttons inside their own div with the class col-xs-6. 

I recommend we modify the text to match the test.  Maybe we should also change the directions to state:
> Nest all of your radio and checkbox buttons within a `<div class="row">` element. Then nest each of them within a `<div class="col-xs-6">` element.

That way following the directions passes the test.  I had to just guess that the system also meant the other buttons.

#### Browser Information
Chrome Version 56.0.2924.87 (64-bit)
Windows 10 1607 Desktop

#### Screenshot
![2017-03-15 1](https://cloud.githubusercontent.com/assets/19174921/23963626/1c0b4442-096f-11e7-952a-7572a7dfea0a.png)

**Comment by cdrainxv** [comment]
@ldwoolley: It appears you have nested your radio buttons **and** your checkbox buttons in the same row. The instructions only want your radio buttons (of which you have two) to be on the same line, each taking up half of the row, thus each individual radio button must be nested inside of a col-xs-6 div.

In a following challenge, `Bootstrap: Responsively Style Checkboxes
`, you will be asked to place your checkbox buttons in a row with each individual checkbox button taking up a third of the row (col-xs-4). Then the visual output at that point would be the radio buttons and checkbox buttons on separate rows, much like this:

![screen shot 2017-03-16 at 02 19 29](https://cloud.githubusercontent.com/assets/18746599/23987401/14b3097a-09ef-11e7-8a93-60d4094f4340.png)


I've seen people come across this as well in the Help room and I would like to suggest a fix as well.

For the description text:

```diff
- Nest all of your radio buttons within a <div class="row"> element. Then nest each of them within a <div class="col-xs-6"> element.
+ Nest all of your radio buttons within a <div class="row"> element. Then nest each individual radio button within a <div class="col-xs-6"> element. Keep in mind you only have two radio buttons.
```

For the test message:

```diff
- Nest each of your radio buttons inside its own div with the class col-xs-6.
+ Nest each individual radio button inside its own div with the class col-xs-6.
```

This, hopefully, reinforces in their mind that each **individual** radio button should be inside of a col-xs-6 div and that they only have two radio buttons to place in a row.

Thanks for looking into this by the way. 😄 

Note: If these changes or any others are going to be implemented in this challenge, they should also be reproduced for the `Responsively Style Checkboxes` challenge as well to maintain consistency.

**Comment by ldwoolley** [comment]
@cdrainxv I like the proposed improvement.  I was actually trying to point out a problem with the test.  The first time I did just the radio button and it didn't pass. Then I added the check-boxes and it passed, so I thought there was a problem with the test.  I just went back and tried the activity again, and this time it only required the radio buttons.  I must have swapped a `<div>` and `</div>`  or something else the first time.  Either way, I think the problem I noted is not real and the issue can be closed, but I vote for the improved wording.  Should we close this, or wait for the improved wording to process?

**Comment by fireandready** [comment]
Having the same issue with this however when applied to the check boxes as well wont check mark the closed tags as completed. Not sure what to do since this is a known issue

**Comment by dhcodes** [comment]
@fireandready looks like a possible fix has recently been made. Give it a few days for the mods to update the beta site and check it again.

**Comment by iamnickpommells** [comment]
I am having this issue where I nest all my check boxes but wont get a check mark for it. Is this a bug I ran the code from atom and it seems to work fine I got no errors should I just bypass this section and return later.

**Comment by iamnickpommells** [comment]
also I believe this challenge has been updated but not fixed. there is still a bug.
