### ISSUE TITLE
Manipulate Arrays With unshift

### ISSUE THREAD

**Issue by clemy84** [freeCodeCamp/freeCodeCamp#13937]
Challenge [Manipulate Arrays With unshift](https://www.freecodecamp.com/challenges/manipulate-arrays-with-unshift#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%22cat%22%5D%3B%0AourArray.shift()%3B%20%2F%2F%20ourArray%20now%20equals%20%5B%22J%22%2C%20%22cat%22%5D%0AourArray.unshift(%22Happy%22)%3B%20%0A%2F%2F%20ourArray%20now%20equals%20%5B%22Happy%22%2C%20%22J%22%2C%20%22cat%22%5D%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B%22John%22%2C%2023%5D%2C%20%5B%22dog%22%2C%203%5D%5D%3B%0AmyArray.shift()%3B%2F%2F%20myArray%20now%20equals%20%5B%22dog%2C3%22%5D%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyArray.unshift(%5B%22paul%22%2C35%5D)%3B%20%2F%2F%20my%20Array%20now%20equals%20%5B%22paul%2C35%22%20%2C%20%22dog%22%2C3%5D%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArray = ["Stimpson", "J", "cat"];
ourArray.shift(); // ourArray now equals ["J", "cat"]
ourArray.unshift("Happy"); 
// ourArray now equals ["Happy", "J", "cat"]

// Setup
var myArray = [["John", 23], ["dog", 3]];
myArray.shift();// myArray now equals ["dog,3"]

// Only change code below this line.
myArray.unshift(["paul",35]); // my Array now equals ["paul,35" , "dog",3]

// Only change code below this line.
myArray.unshift(["paul",35]); // my Array now equals ["paul,35" , "dog",3]
```
![image](https://cloud.githubusercontent.com/assets/24882338/23953445/79768106-098c-11e7-89e9-a07832d283ea.png)

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong. Names usually have an upperCase letter
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by clemy84** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Sorry I will check it again thanks 


Sent from Yahoo Mail for iPhone


On Wednesday, March 15, 2017, 2:48 pm, Lauri <notifications@github.com> wrote:


Thank you for reporting your issue.

Your code is wrong. Names usually have an upperCase letter
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our full list of official chatrooms.
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
