### ISSUE TITLE
Inaccuracy in _Computer Basics: Intro to Binary Code_

### ISSUE THREAD

**Issue by lionel-rowe** [freeCodeCamp/freeCodeCamp#13935]
#### Challenge Name

https://www.freecodecamp.com/videos/computer-basics-intro-to-binary-code

#### Issue Description

Question 3 "There are some things which cannot be translated into binary." Gives the correct answer as `false`, when in fact it should be `true`. In quantum computing, one qubit cannot be fully expressed in an arbitrarily large number of bits.

**Comment by erictleung** [comment]
@lionel-rowe thanks for the issue. I can't find these video challenges in the beta version. I agree that the question should be changed.

cc/ @freeCodeCamp/moderators I might have missed something, but where are these challenges in `beta`? Or did we remove them?

**Comment by lionel-rowe** [comment]
Sorry, these are on the main site (not beta), so I guess they won't be included once the new material is fully rolled out. Actually, having gone through a few more of them, I've noticed there are a number of inaccuracies in the videos and questions... some representative samples:

- Bits vs. bytes makes more of a difference when talking "exponentially" (actually, the difference is x8 whether we're talking about b vs. B or Pb vs. PB)
- A VPN is "basically the same" as a WAN (it's not)
- Packets can be broken up into frames, which are "smaller little packets" (actually, a frame is a packet encapsulated in a Layer 2 header, so it's typically larger than a packet)

The content is good for getting a "big picture" overview of some of the concepts, but it breaks down once you get to the details.

**Comment by scshepard** [comment]
Adding my binary '10' cents to this discussion; if you are talking at very simple level, it can be helpful to note several ideas: generally a byte is 8 bits (but not always), the least significant bit depends on the computer architecture you are using, but will always be converted properly when the sequence is transmitted on the web, and the electrical value of the "on" and "off" can be generalized, but depends on the hardware. I think it's ok to generalize and say big endian, binary '1' is a switch "on", and bytes are 8 bit.

Phew!

Steve

________________________________

**Comment by raisedadead** [comment]
@erictleung 
I believe, we are removing the video challenges in favor of having them on the YouTube channel it self. I am not very sure.

**Comment by dhcodes** [comment]
@raisedadead is correct. See: https://github.com/freeCodeCamp/freeCodeCamp/issues/12753
