### ISSUE TITLE
API link has been changed

### ISSUE THREAD

**Issue by DamChtlv** [freeCodeCamp/freeCodeCamp#13930]
Challenge [Use the Twitchtv JSON API](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The API link is no longer : https://wind-bow.gomix.me
The new API link is : https://wind-bow.glitch.me

**Comment by erictleung** [comment]
@DamienChantelouve thanks for catching this. Luckily, it still redirects correctly. Nonetheless, we should update this link.

**Comment by cdrainxv** [comment]
I can take this up, unless @DamienChantelouve claimed it.

**Comment by fortMaximus** [comment]
I will take this issue but I can't find the file that has the 10th point, which has this API link, in the checklist on the challenge page. I found [this](https://github.com/freeCodeCamp/freeCodeCamp/blob/d04a6d34845db7178394bafac568593d12c47b30/seed/challenges/08-coding-interview-questions-and-take-home-assignments/take-home-interview-projects.json) file but it doesn't have this point.

**Comment by ZZhaoTireless** [comment]
@erictleung Hi, I guess you haven't release all the challenges on github right? I cannot find the seed of this challenge.

**Comment by erictleung** [comment]
@ZZhaoTireless this challenge has changed between the production and [beta version](http://beta.freecodecamp.com/en/challenges/coding-interview-take-home-projects/use-the-twitchtv-json-api).

cc/ @freeCodeCamp/moderators the production and beta sites are different, with the production adding an update on using a Twitch API. I'm not too familiar with this part so asking for guidance on whether we should be updating the production website with the new gomix/glitch URL, so make the production site match the beta website.

**Comment by QuincyLarson** [comment]
The old production link redirects properly and should continue to do so indefinitely. We are close to shipping beta, so let's leave production for now.
