### ISSUE TITLE
Add Font Awesome Icons to our Buttons - HTML not added in the editor

### ISSUE THREAD

**Issue by bja09** [freeCodeCamp/freeCodeCamp#13933]
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
</style>

<div class="container-fluid">
  <div class="row">
    
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>
    </div>
  </div>
  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary">Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info">Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger">Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    
    <button type="submit">Submit</button>
  </form>
</div>

#### Challenge Name

Add Font Awesome Icons to our Buttons

#### Issue Description

The HTML which is rendered in the view is not present in the editor.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/25434699/23949763/396eacd2-0991-11e7-8685-a033e29ef857.png)

**Comment by mikah13** [comment]
I assume that it is because you didn't add this:
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"/>
on the top of your work

**Comment by cdrainxv** [comment]
@mikah13: The font-awesome library has already been included behind the scenes so there is no need to include it here. Thanks for helping!

@bja09: From your screenshot it looks like you haven't added the the icon elements at all, much less the font-awesome classes. You can readily receive help/guidance on these challenges in the [Help](https://gitter.im/FreeCodeCamp/Help) room. Happy coding!

**Comment by bja09** [comment]
@cdrainxv  Yes, indeed, but look at the html and check if I have a Like, Info or Delete button as HTML tags  + text , if you see  in the right of the screenshot what is rendered is a different thing than what's in the HTML. I don't have a place where to add he i tag for the icon element.

**Comment by hector57** [comment]
<button class="btn btn-block btn-primary fa fa-thumbs-up"><i class="fa fa-thumbs-up"></i>Like</button>
