### ISSUE TITLE
The opening comment tag '<!--' comments 'testSuite' tasks list as well

### ISSUE THREAD

**Issue by MallickGabriel** [FreeCodeCamp/FreeCodeCamp#1393]
Hi everybody, it's a pleasure to join your camp. 

Whenever you type the comment opening tag in the code editor at the challenges page, you'll end up with a deleted tasks list. I think the effect of the comment tag exceeds the code editor boundaries.
 
Best regards ...

![bug](https://cloud.githubusercontent.com/assets/13380120/8914957/9c5b0cac-34d4-11e5-8a5b-a492811b03c9.png)

**Comment by benschenker** [comment]
Hey @MallickGabriel thanks for posting this issue!

This is really similar to #1081, so follow the discussion there.
