### ISSUE TITLE
Wrong link in Zipline: Show the Local Weather

### ISSUE THREAD

**Issue by labiej** [FreeCodeCamp/FreeCodeCamp#1394]
A simple issue here, in the 10th item there should be a link to the $.getJSON() documentation.
Instead the link points to http://api.jquery.com/jquery.each/

This shouldn't be an issue once you reach the ziplines but it can be confusing to some.

-J

**Comment by benschenker** [comment]
It looks like this has been rewritten and this issue has been solved
