### ISSUE TITLE
ConfirmEnding code is wrong, yet it passes

### ISSUE THREAD

**Issue by vongdarakia** [freeCodeCamp/freeCodeCamp#13944]
#### Basic Algorithm Scripting: Confirm the Ending
http://beta.freecodecamp.com/en/challenges/basic-algorithm-scripting/confirm-the-ending

#### Not enough effective test cases
There should be a test case for a target ending that appears anywhere else other than the end of the string. 

The purpose of the function is to determine whether the 'target' string appears at the end of the given string (str).

The issue is that the code below will pass when it shouldn't. It looks for the first appearance of the target in the string (str), creates a substring from that to the end, and returns if it's equal to the target string. There are no test cases for the case when the target appears anywhere else than the end.

```js

function confirmEnding(str, target) {
  return str.substr(str.indexOf(target)) == target;
}

```

#### This should still return true for both cases, but it doesn't

<img width="286" alt="screen shot 2017-03-15 at 4 12 49 pm" src="https://cloud.githubusercontent.com/assets/4285261/23974772/49343e62-099a-11e7-8ad1-a0cbaacdb2a2.png">

#### Yet it still passes

<img width="1376" alt="screen shot 2017-03-15 at 4 08 45 pm" src="https://cloud.githubusercontent.com/assets/4285261/23974690/c959b6ea-0999-11e7-9451-fddda5ae168e.png">

**Comment by JoolsMcFly** [comment]
You're right, nice find!
I'll give it a go and make a PR.

**Comment by vongdarakia** [comment]
Awesome! Thanks a lot! :)

**Comment by JoolsMcFly** [comment]
Np, let's just hope it gets accepted! :)
