### ISSUE TITLE
Passing Values to Functions with Arguments?

### ISSUE THREAD

**Issue by YoungLeo14** [freeCodeCamp/freeCodeCamp#13951]
Challenge [Passing Values to Functions with Arguments](https://www.freecodecamp.com/challenges/passing-values-to-functions-with-arguments#?solution=%0A%2F%2F%20Example%0Afunction%20ourFunctionWithArgs(a%2C%20b)%20%7B%0A%20%20console.log(a%20-%20b)%3B%0A%7D%0AourFunctionWithArgs(10%2C%205)%3B%20%2F%2F%20Outputs%205%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Afunction%20functionWithArgs(a%2C%20b)%20%7B%0A%20%20console.log(a%20%2B%20b)%3B%0A%7D%0AfunctionWithArgs(1%2C%202)%3B%20%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.

function functionWithArgs(a, b) {
  console.log(a + b);
}
functionWithArgs(1, 2); 


```

I ran this code in this challenge and it sais that both of the challenges (1 to result in 3 and the other to result in 16) and without passing a second function for 16, it still passed - any chance of a clarification on instructions a bit, these ones are nasty

**Comment by codehakase** [comment]
I don't see anything wrong with this code, @YoungLeo14

**Comment by YoungLeo14** [comment]
The point is that its not the code thats the problem, rather the code "completes" outputting 3 AND 16 @codehakase

**Comment by codehakase** [comment]
You mean it only returns `3` and `16` ?

**Comment by codehakase** [comment]
I just changed the arguments passed, and it logs the correct values

**Comment by Marmiz** [comment]
@YoungLeo14  
>without passing a second function for 16, it still passed

If you mean that with the code you wrote you still complete the `functionWithArgs(7,9)`, well... that's normal.

Our test run some function with the code you wrote and look for the output.
That's the standard behavior.

In this case the page will run a function `functionWithArgs` and will assign two arguments: `7,9` when you click the `run` button without the need for you to specify that.
writing in your code:
```
functionWithArgs(7, 9);
```
Is a way for you to test it and see the output in the console; useful in later and more complex functions :)
