### ISSUE TITLE
Challenge [specify-exact-number-of-matches] The last test is wrong 

### ISSUE THREAD

**Issue by kedarguy** [freeCodeCamp/freeCodeCamp#13952]
Challenge [specify-exact-number-of-matches](http://beta.freecodecamp.com/en/challenges/regular-expressions/specify-exact-number-of-matches) has an issue.
 
The last test is: Your regex should match "Timber" with 30 m\'s in it.

It should be NOT match Timber with 30 m's in it because the assignment is:

Change the regex timRegex to match the word "Timber" only when it has four letter m's.

The last test causes a fail when writing the following code:

let timStr = "Timmmmber";
let timRegex = /m{4}/; // 
let result = timRegex.test(timStr);

The tests are:
Your regex should use curly brackets.
Your regex should not match "Timber"
Your regex should not match "Timmber"
Your regex should not match "Timmmber"
Your regex should match "Timmmmber"
Your regex should match "Timber" with 30 m\'s in it.

**Comment by erictleung** [comment]
@kedarguy thanks for the issue. Yes, that needs to be changed. [This line of code](https://github.com/freeCodeCamp/freeCodeCamp/blob/c125c385467fcd7a911eab89806a176ced0c6b05/seed/challenges/02-javascript-algorithms-and-data-structures/regular-expressions.json#L828) needs to be changed.

The message should be changed to

```diff
- Your regex should match <code>\"Timber\"</code> with 30 <code>m</code>\\'s in it.
+ Your regex should not match <code>\"Timber\"</code> with 30 <code>m</code>\\'s in it.
```

**Comment by imshashwataggarwal** [comment]
Hi! Can I contribute to this issue?

**Comment by makkBit** [comment]
I am already working on this as my first contribution to open source world.

**Comment by erictleung** [comment]
@imshashwataggarwal go for it! Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by makkBit** [comment]
Submitted a pull request https://github.com/freeCodeCamp/freeCodeCamp/pull/13967 :)

**Comment by suzon-ahmmed** [comment]
let timStr = "Timmmmber";
let timRegex = /Tim{4}ber/; 
let result = timRegex.test(timStr);
