### ISSUE TITLE
Night Mode Poor Contrast

### ISSUE THREAD

**Issue by digilou** [freeCodeCamp/freeCodeCamp#13959]
#### Issue Description

I love Night Mode when doing the challenges. However, I noticed that the contrast seemed a bit low. Running the WCAG Contrast Checker extension confirmed my belief. See screenshot below. Lightening up the foreground color would be beneficial to everyone. Thanks!

#### Browser Information

* Browser Name, Version: Mozilla 52.0
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/8865558/24020135/c3384ca2-0a4f-11e7-977c-b658f4a5c2df.png)

**Comment by digilou** [comment]
I'm happy to tackle this, if it's open! I just need to finish setting up my dev environment according to the contribution guidelines.

**Comment by Venkateshwaran** [comment]
I have set up local FCC. I will be able to give it a shot by tonight unless @digilou hasn't done it already.

**Comment by Venkateshwaran** [comment]
Hi, i have committed a [fix here](https://github.com/freeCodeCamp/freeCodeCamp/pull/14037/commits/3e416a69d3813a3e377e1134dc8f94bc40f29ca4). 

It passed WCAG luminosity as shown in the below screenshot. 
<img width="838" alt="screen shot 2017-03-21 at 10 41 47 pm" src="https://cloud.githubusercontent.com/assets/2083617/24161498/951deca2-0e8a-11e7-9588-5c322a027502.png">

**Comment by digilou** [comment]
You beat me to it! This is an improvement, though. Thanks @Venkateshwaran for making the site better.
