### ISSUE TITLE
Suggested Change: Change the word blocks to groups

### ISSUE THREAD

**Issue by kprenesti** [freeCodeCamp/freeCodeCamp#13957]
Challenge [wrap-content-in-the-article-element](http://beta.freecodecamp.com/en/challenges/applied-accessibility/wrap-content-in-the-article-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<h1>Deep Thoughts with Master Camper Cat</h1>
<main>
  <div>
    <h2>The Garfield Files: Lasagna as Training Fuel?</h2>
    <p>The internet is littered with varying opinions on nutritional paradigms, from catnip paleo to hairball cleanses. But let's turn our attention to an often overlooked fitness fuel, and examine the protein-carb-NOM trifecta that is lasagna...</p>
  </div>

  <img src="samuraiSwords.jpeg" alt="">

  <article>
    <h2>Defeating your Foe: the Red Dot is Ours!</h2>
    <p>Felines the world over have been waging war on the most persistent of foes. This red nemesis combines both cunning stealth and lightening speed. But chin up, fellow fighters, our time for victory may soon be near...</p>
  </article>

  <img src="samuraiSwords.jpeg" alt="">

  <article>
    <h2>Is Chuck Norris a Cat Person?</h2>
    <p>Chuck Norris is widely regarded as the premier martial artist on the planet, and it's a complete coincidence anyone who disagrees with this fact mysteriously disappears soon after. But the real question is, is he a cat person?...</p>
  </article>
</main>

```
In the description, where you have a yellow rectangle that says, 
```
<pre>
<div> - blocks content
<section> - blocks related content
<article> - blocks independent, self-contained content
</pre>
```
I'll recommend changing the word blocks to the word groups.  Blocks typically means STOPS or PREVENTS in code.

**Comment by HKuz** [comment]
@kprenesti - this is a good suggestion, and I think it'll help avoid confusion, particularly with non-native English speakers.

For anyone that would like to make this change (the word "blocks" should be changed to "groups" in the blockquote), please refer to the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) and ask any questions in the [Contributor's Chat Room](https://gitter.im/FreeCodeCamp/Contributors). You can find the code for this challenge [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/applied-accessibility.json#L180). Thank you 🎉 👍 🍹

**Comment by ZZhaoTireless** [comment]
I will take this. Thanks.

**Comment by ZZhaoTireless** [comment]
I will take this. Thanks.

**Comment by QuincyLarson** [comment]
@kprenesti Excellent point.

@ZZhaoTireless thanks for the fast turnaround on this!
