### ISSUE TITLE
"Something went wrong error" primarily affecting campers around South Africa

### ISSUE THREAD

**Issue by overmelo** [freeCodeCamp/freeCodeCamp#13953]
I am trying to log in to my account at beta.freecodecamp.com and start the HTML challenges, but while i am always receiving this message: **SOMETHING WENT WRONG, PLEASE TRY AGAIN LATER**
i have tried many times, but it has not changed. 

on this page, while clicking to "Finish Challenge", i am still getting that same "SOMETHING WENT WRONG, PLEASE TRY AGAIN LATER"

how can i fix it?
![beta issue](https://cloud.githubusercontent.com/assets/17744075/24008806/107d175e-0a73-11e7-8daf-af0e235e90d9.jpg)

**Comment by pchiarato** [comment]
It looks like you're using "Opera" try using Chrome or Firefox.

**Comment by overmelo** [comment]
Actually, i'm using Chrome. tried Firefox but problem persist!!!

**Comment by QuincyLarson** [comment]
@BerkeleyTrue do you have any idea what could be causing this? Do you think it's specific to @overmelo's account on beta being in a strange state?

**Comment by overmelo** [comment]
sometimes (since last week) when i log in via my github's account, my profile doesn't appear. same thing when i tried to log in with my twitter or gmail account. don't really know how to do.

**Comment by BerkeleyTrue** [comment]
@QuincyLarson Without further information, no I do not.

@overmelo That message pops up when the app encounters an error. Can you open up the devtools console and report any errors you may see?

**Comment by overmelo** [comment]
@BerkeleyTrue  this is the printScreen of what i had
![new pb](https://cloud.githubusercontent.com/assets/17744075/24225400/8965ea0a-0f60-11e7-96c5-fe9d14579a25.jpg)

**Comment by BerkeleyTrue** [comment]
@overmelo Looks like a fetch for data is timing out. Where are you located?

**Comment by overmelo** [comment]
@BerkeleyTrue  Actually, im in Cameroon. this is only happening in beta. how can i fix it?

**Comment by Emmanx** [comment]
I'm in Nigeria and i am also having issues with the beta version of FreeCodeCamp and its very frustrating ..please fix.

**Comment by overmelo** [comment]
i don't know, this issue has not been solved yet by them, seems like it is only happening in beta maybe it is coming from they database system.

**Comment by Emmanx** [comment]
And I want to use the beta because the curriculum is structured more properly

**Comment by aadisnell** [comment]
I am in Ghana and i am also encountering  the same problem ......

**Comment by krishnaa208** [comment]
it was working perfectly fine this morning on Chrome but Showing Error Message "Something went wrong, please Try again" when i am trying to Click on Finish OR clicking on any challenges . I also tried using Firefox but Same Problem

**Comment by hijazi** [comment]
I'm facing a couple problems too.
![screenshot from 2018-01-27 16-33-07](https://user-images.githubusercontent.com/733890/35472868-d3a907a0-037f-11e8-8a93-158f3779fbc7.png)
I'm in Amman-Jordan

**Comment by hijazi** [comment]
I tried incognito after facing the "SOMETHING WENT WRONG, PLEASE TRY AGAIN LATER" issue on ordinary mode.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue It seems to be mostly affecting campers in the Middle East and Africa: Amman-Jordan, Nigeria, Cameroon, and Ghana. Any idea what could be causing this?

**Comment by chethanbhat** [comment]
I am from India, and facing similar issue.  https://github.com/freeCodeCamp/freeCodeCamp/issues/16468

I had a doubt. Does slow internet connection cause this? Looks like most the country mentioned here have slower internet than north america or europe.

**Comment by LiteSoul** [comment]
I'm in South America and this exact issue started appearing a couple of weeks ago. I would say this bug is quite big since you are literally stuck and can't do anything.
In my case is when I complete a challenge, run the test, passes, and can't go to next one (Ctrl+Enter). And the drop-down map menu is not working (can't manually click on some other challenge)


![beta](https://user-images.githubusercontent.com/22918889/35706543-e501ca38-0784-11e8-8cbc-0788ea9e4e34.png)

**Comment by kdesCode** [comment]
Good Day
Have similar issues. From South Africa.
Interestingly when on a 4Mbps connection i have the issue. When using 3G around 10Mbps dont have the issue.
Needs to work on lower bandwidth to reach areas that dont have the bandwidth. These areas are the ones that need free education like freecodecamp.
Must getting working for Africa please.
Thanks

**Comment by DubaniWarrior** [comment]
I can confirm the same issue in South Africa.

**Comment by BerkeleyTrue** [comment]
This issue has been confirmed. Please do not comment unless you have additional information that has not already been stated. 

Happy Coding

**Comment by Bouncey** [comment]
Cross-posting so that you can still keep working on the challenges until we get this fixed

>What you could do to keep the challenges coming is navigate directly to the challenges themselves. Hovering over the challenge in the map will show you the address of the next challenge.

![hover for url](https://user-images.githubusercontent.com/18572518/36533311-1200926c-17bb-11e8-8b88-513b546df09e.png)

>I know this is not ideal, I should have a PR ready today.

**Comment by LiteSoul** [comment]
That's not possible to do, since this bug prevents the map from working, the drop down doesn't work, the left column (map section) freezes and doesn't open sub-menus on click.
