### ISSUE TITLE
challenges

### ISSUE THREAD

**Issue by Aminhimat** [freeCodeCamp/freeCodeCamp#13955]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3Ared%3B%7D%0A.red-text%3Dcolor%3Ared%0A%3C%2Fstyle%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html


<style>
  .red-text {
    color:red;}
.red-text=color:red
</style>
<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by dhcodes** [comment]
@Aminhimat you have an error in your code. Please consider asking for help in the [help chat room](https://gitter.im/FreeCodeCamp/Help) on Gitter
