### ISSUE TITLE
Search And Replace (Issue with the expected result)

### ISSUE THREAD

**Issue by ssinghal1989** [freeCodeCamp/freeCodeCamp#13966]
Below is my Code for string search and replace.

function myReplace(str, before, after) {
  var strArr = str.split(' ');
  var index = strArr.indexOf(before);
  var arr1 = strArr.slice(0,index);
  arr1.push(after);
  var arr2 = strArr.slice(index + 1, strArr.length);
  return arr1.concat(arr2).join(' ');
}

myReplace("He is Sleeping on the couch", "Sleeping", "sitting");

Its working fine for some test cases but having issue in some test cases. I think the expected result for some test cases are wrong.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by dhcodes** [comment]
@ssinghal1989 you have an error in your code. Please consider asking for help in the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help)

Be sure to read the instructions carefully too, ex.
>NOTE: Preserve the case of the original word when you are replacing it. For example if you mean to replace the word "Book" with the word "dog", it should be replaced as "Dog"
