### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by ninjatron** [FreeCodeCamp/FreeCodeCamp#1396]
This is not really an issue, but I think the site could benefit from a better designed profile page. For example, there is no reason to show all solutions as it makes the page harder to navigate. Also, instead of just writing "Bonfire: Bonfire Name" on solutions listed, enumeration can be used, it would make it easier to navigate. Each of solutions can be accordion links, like:

Bonfire 16: Finding Nemo
Bonfire 20: Roman Numerals 
       <code here Bonfire 20 is clicked>
Bonfire 21: Superrouters
Bonfire 23: Butter Bean

**Comment by BerkeleyTrue** [comment]
Done!

Happy Coding!
