### ISSUE TITLE
he problem is that the code that ive written to clone target5 clones it and copies it to the left-well but since i cloned target5 the name of the elements are same and that ends up transfering double target 5 boxes. and its like on and off in some moment it shows only 1 box and other it shows both target5 box'es

### ISSUE THREAD

**Issue by varunmistry** [freeCodeCamp/freeCodeCamp#13977]
Challenge [Use jQuery to Modify the Entire Page](https://www.freecodecamp.com/challenges/use-jquery-to-modify-the-entire-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
    $("#right-well").children().css("color", "orange");
    $("#left-well").children().css("color", "green");
    $(".target:nth-child(2)").addClass("animated bounce");
    $(".target:even").addClass("animated shake");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by Manish-Giri** [comment]
@varunmistry The title of the issue should ideally be succinct and only a few words long, to describe the issue briefly. You can use the body of the issue to fill in all the details.

**Comment by Gardemarin** [comment]
It's  not issue. It's normal .clone() behaviour.

**Comment by dhcodes** [comment]
@varunmistry as @Gardemarin has said, `.clone()` will copy the target it's applied to. I think this is functioning as intended.

**Comment by rss81** [comment]
if you use removeAttr('id') then the test doesn't run.  so either way, it's a bug

**Comment by Gardemarin** [comment]
So don't remove it ;) Task don't ask to do that ;)

**Comment by rss81** [comment]
target5 is not a class so removing it won't help.  It is a known bug on the freecodeacademy site.  One solution is to use  $(document).bind("ready",function(e) {...   that seems to fix the problem without removing the id.

**Comment by Gardemarin** [comment]
Did you inspect my all code ? :) I add ```target5``` class to button with ```id="target5"```

**Comment by Gardemarin** [comment]
What I want to say, it's not an issue. It's normal .clone() behaviour and if You still don't believe me try that code on localhost  inside your computer ;)

**Comment by Gardemarin** [comment]
Funny ! :D I tried this code in codepen :) so .. rss81 You was right! :) it is an issue :) my apologies!

**Comment by dhcodes** [comment]
This is likely an issue with the jQuery running for each test. Regardless, it has been resolved on the beta. http://beta.freecodecamp.com/en/challenges/jquery/clone-an-element-using-jquery

**Comment by gordwelling** [comment]
This may be fixed in the beta, but it is still occurring in production.

![image](https://cloud.githubusercontent.com/assets/28510186/26338434/25b38a14-3f3d-11e7-8be5-804ed2e06013.png)

**Comment by wangjenny** [comment]
Issue is still occurring. Happens after running the tests.

**Comment by wangjenny** [comment]
+1
