### ISSUE TITLE
Pedagogical Point About Teacher Arrays

### ISSUE THREAD

**Issue by johnrayworth** [freeCodeCamp/freeCodeCamp#13971]
Challenge [Modify Array Data With Indexes](https://www.freecodecamp.com/challenges/modify-array-data-with-indexes) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArray = [1,2,3];
ourArray[1] = 3; // ourArray now equals [1,3,3].

// Setup
var myArray = [1,2,3];

// Only change code below this line.


//I hope you do not mind the occasional comment about the way things are being taught, 
//but having taught arrays for twenty or so years, a small point here is it is always a good 
//idea to not use numbers 1 - 10 and other low numbers which could be confused with 
//the element numbers.  So much better is an array like:

var myArray = [18, 64, 99];

//than 

var myArray = [1, 2, 3];     //-     in which case element 1 is 2 and element 2 is 3...
```

**Comment by OFFLlNE** [comment]
I personally agree with @johnrayworth. Seems like a fairly simple thing to do and might cause less confusion for people

**Comment by dhcodes** [comment]
This makes sense. I'm in favor of making the change.
