### ISSUE TITLE
Fadeinup and down not working

### ISSUE THREAD

**Issue by raipriya** [freeCodeCamp/freeCodeCamp#13970]
Hei All,

 Actually i'm doing the 1st challenge that is Tribute page but now i have problem as i wanted to have text on the background image to be animated and fadein up and down but its not working.Please give me your valuable advice. I'm greatful to you all.  
![problem](https://cloud.githubusercontent.com/assets/26298161/24037451/853182d6-0b06-11e7-9925-8d1fb19ca1a0.PNG)

Thanks in Advance

**Comment by Marmiz** [comment]
@raipriya Github issue is a place for bug tracking only.

If you are in need of help or assistance please use one of the [official chat room](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or the [forum](https://forum.freecodecamp.com/) where you can have better assistance.


----
That said, have you imported `animate.css` into the page?
In the same section where you add CSS library make sure you have this link included:
`https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css`
