### ISSUE TITLE
Does not accept even though it's correct

### ISSUE THREAD

**Issue by Petrovik1** [freeCodeCamp/freeCodeCamp#13976]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3EKitty%20ipsum%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Kitty ipsum</p>

```

**Comment by psingl** [comment]
My code is also not being accepted can you help me out please.
![image](https://cloud.githubusercontent.com/assets/13885706/24070669/f168b37a-0be7-11e7-847d-e69b68da7a9e.png)
Error being 
![image](https://cloud.githubusercontent.com/assets/13885706/24070671/078fef10-0be8-11e7-89b8-9e912291988e.png)

**Comment by erfe1** [comment]
كس امك

بتاريخ ٢٠١٧/٠٣‏/١٨ ١٢:٠٥ م، كتب "Paras Singla" <notifications@github.com>:

**Comment by muhammedIbrahim265857** [comment]
![capture11](https://cloud.githubusercontent.com/assets/26529798/24098001/158c575e-0d71-11e7-8207-892f87648e78.PNG)
any help please , I do not know what is wrong ?

**Comment by ssajuraj** [comment]
<h2> style="**color:red**">CatPhotoApp</h2>

**Comment by ssajuraj** [comment]
`<h2 style="color:red">CatPhotoApp</h2>`

**Comment by muhammedIbrahim265857** [comment]
thank you , i missed it :)

**Comment by texas2010** [comment]
@ssajuraj 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
