### ISSUE TITLE
Target Even Numbered Elements Using jQuery

### ISSUE THREAD

**Issue by j113203** [freeCodeCamp/freeCodeCamp#13975]
> https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/03-front-end-libraries/jquery.json#L1416

should change to 
`$(\".target:even\").hasClass(\"animated\") && $(\".target:even\").hasClass(\"shake\")`
![image](https://cloud.githubusercontent.com/assets/5006280/24049270/7965c970-0b66-11e7-8acd-a1565e60a428.png)

as json parser encode the quote

![image](https://cloud.githubusercontent.com/assets/5006280/24049193/40a24fbe-0b66-11e7-99e0-5e7621db4066.png)

**Comment by JoolsMcFly** [comment]
Nah, it's fine. You would need to escape `"` but `'` is fine:

![image](https://cloud.githubusercontent.com/assets/4972399/24269750/c35699dc-1012-11e7-927f-fcca1b72a507.png)

Can close this issue if you agree? Thanks.
