### ISSUE TITLE
truncateString("Absolutely Longer", 2) should return "Ab...". //this test is failing 

### ISSUE THREAD

**Issue by karanjariwala** [freeCodeCamp/freeCodeCamp#13987]
Challenge [Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string#?solution=%0Afunction%20truncateString(str%2C%20num)%20%7B%0A%20%20%2F%2F%20Clear%20out%20that%20junk%20in%20your%20trunk%0A%20%20%20%20if(str.length%3Enum)%0A%20%20%20%20%7B%0A%20%20if(str.length%3E3)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20str.slice(0%2Cnum-3)%2B'...'%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20else%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20str.slice(0%2Cnum)%2B'...'%3B%0A%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20else%0A%20%20%20%20%7Breturn%20str%3B%7D%0A%20%0A%7D%0A%0AtruncateString(%22A-tisket%20a-tasket%20A%20green%20and%20yellow%20basket%22%2C%2011)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function truncateString(str, num) {
  // Clear out that junk in your trunk
    if(str.length>num)
    {
  if(str.length>3)
    {
      return str.slice(0,num-3)+'...';
      
    }
  else
    {
      return str.slice(0,num)+'...';
    }
    }
  else
    {return str;}
 
}


truncateString("Absolutely Longer", 2) should return "Ab...". //this test is failing 
However,
truncateString("A-", 1) should return "A...".//This test is passing 
I don't see any logic error in my code. Please help.

**Comment by karanjariwala** [comment]
No I believe this is a bug!  :)
Correct me if I'm wrong.

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong. you are slicing (0,-1)
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by codeGeek3** [comment]
`
function truncateString(str, num) {
  // Clear out that junk in your trunk
  if(num >= str.length) return str;
   
  var arr1 = str.split(' ');

  var arr2 = str.slice(0,num).split(' ');
 
  var result = '';
  var len = arr2.length;
    for(var i = 0; i < len; i++)
        if(arr1[i] == arr2[i] || num <= 3) result += (i >0? ' ':'') + arr2[i];
  
  return result + '...';
  
}

truncateString("A-", 1);
`

**Comment by texas2010** [comment]
@codeGeek3 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by maximilientoumi** [comment]
forget the text over the image just look at the code and correct your error
![truncatechal](https://cloud.githubusercontent.com/assets/22794420/25878141/0688ee14-3546-11e7-8766-d62bcc0314e7.png)
