### ISSUE TITLE
Css background images not working

### ISSUE THREAD

**Issue by rocifier** [freeCodeCamp/freeCodeCamp#13983]
#### Issue Description

I've tried a number of external image providers such as postimage.org and cloudinary.com but when I use the following css code, there is no background property added to the html output, seen when I inspect the element in chrome. 

Example Pen:
http://codepen.io/rocifier/pen/pepjaK

#### Browser Information

Chrome 56.0.2924.87 (64-bit)
Windows 10 and Windows 7

#### Your Code

```
#banner{
  width:300px;
  height:300px;
  background：url("http://res.cloudinary.com/dxvvzbawu/image/upload/v1489794718/star--background-seamless-repeating5_p28xxy.jpg");
}
```

```
<div id="banner"></div>
```

#### Screenshot

[Capture.png](https://postimg.org/image/xudzeincn/)

**Comment by OFFLlNE** [comment]
Thank you for reporting the issue.

This is not a freeCodeCamp issue, so this is why I am closing this one.

Good luck and happy coding!
