### ISSUE TITLE
Local Scope and Functions has bug

### ISSUE THREAD

**Issue by WwupengP** [freeCodeCamp/freeCodeCamp#13998]
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=%0Afunction%20myLocalScope()%20%7B%0A%20%20'use%20strict'%3B%0A%20%20%0A%20%20var%20myVar%3B%0A%20%20%0A%20%20myVar%20%3D%20'hello'%3B%0A%20%20console.log(myVar)%3B%0A%7D%0AmyLocalScope()%3B%0A%0A%2F%2F%20Run%20and%20check%20the%20console%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myLocalScope%0A%2F%2F%20console.log(myVar)%3B%0A%0A%2F%2F%20Now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function myLocalScope() {
  'use strict';
  
  var myVar;
  
  myVar = 'hello';
  console.log(myVar);
}
myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope
// console.log(myVar);

// Now remove the console log line to pass the test


```

**Comment by WwupengP** [comment]
after I hard refresh my browser, the test past.

**Comment by marclundgren** [comment]
There is a bug with this challenge. Hard refreshing the browser fixed this for me as well. Trust me, this is a bug

**Comment by obamaanakbsi** [comment]
i can't past anyway... how to fix it?? because this is my assignment from my lecture to finish freecodecamp sertivication... and next month i must finish it...
