### ISSUE TITLE
The instructions are not very clear for this challenge.

### ISSUE THREAD

**Issue by haydennorthcott** [freeCodeCamp/freeCodeCamp#13993]
Challenge [Convert Celsius to Fahrenheit](https://www.freecodecamp.com/challenges/convert-celsius-to-fahrenheit#?solution=%0Afunction%20convertToF(celsius)%20%7B%0A%20%20var%20fahrenheit%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20fahrenheit%20%3D%20celsius%20*%20(9%2F5)%20%2B%2032%3B%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20fahrenheit%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%20your%20code%0AconvertToF(-30)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function convertToF(celsius) {
  var fahrenheit;
  // Only change code below this line
  
  fahrenheit = celsius * (9/5) + 32;
  
  
  // Only change code above this line
  return fahrenheit;
}

// Change the inputs below to test your code
convertToF(-30);

```

**Comment by Manish-Giri** [comment]
@haydennorthcott I think this is quite specific - 
> The algorithm to convert from Celsius to Fahrenheit is the temperature in Celsius times 9/5, plus 32.

> You are given a variable celsius representing a temperature in Celsius. Use the variable fahrenheit already defined and apply the algorithm to assign it the corresponding temperature in Fahrenheit.

What do you think could be improved?

**Comment by haydennorthcott** [comment]
It feels like this task is quite a step up from the previous tasks. Maybe
having some steps in between.
I've given this one a second go & still struggled with it.

Hayden

**Comment by QuincyLarson** [comment]
@haydennorthcott You're right - we are actually moving this to a later section since it is a big jump in difficulty. 

I agree with @Manish-Giri that the directions are pretty clear, so I'm going to close this issue.
