### ISSUE TITLE
Clockwise padding not provided, still passes all tests

### ISSUE THREAD

**Issue by prateekgoel** [freeCodeCamp/freeCodeCamp#13997]
#### Challenge Name

https://www.freecodecamp.com/challenges/use-clockwise-notation-to-specify-the-padding-of-an-element

#### Issue Description

It has been asked to use clockwise notation to have padding on green-box class. However, even if I do not use clockwise notation, it passes all the tests correctly. Is there any way this could be corrected?

Same is the issue with Challenge 51 for margin instead of padding.

#### Browser Information

* Google Chrome, Version: 56.0.2924.87 
* Operating System: Windows
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

...
 .green-box {
    background-color: green;
    padding-top:40px;
    padding-right:20px;
    padding-bottom:20px;
    padding-left:40px;
  }

...

```

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/8016566/24078886/cdedadac-0c9f-11e7-948f-be921cda6b50.png)

**Comment by Manish-Giri** [comment]
This should be straightforward. I'll give it a shot.
