### ISSUE TITLE
Unclear Explanation of Important Topic: <divs> in CSS

### ISSUE THREAD

**Issue by stevenyeager** [freeCodeCamp/freeCodeCamp#14003]
#### Nest Many Elements Within a Single Div Element
https://www.freecodecamp.com/challenges/nest-many-elements-within-a-single-div-element

#### Issue Description
As a beginner, divs are something I'm still getting a handle on. I spent a few minutes trying to understand this explanation of divs but found it more confusing than helpful:

"The div element is probably the most commonly used HTML element of all. **It's useful for passing the CSS of its own class declarations down to all the elements that it contains.**" 

I believe it should be rewritten in terms more likely to be understood by beginning coders.

#### Screenshot

![screen shot 2017-03-19 at 1 51 13 pm](https://cloud.githubusercontent.com/assets/25139506/24083318/35ec83be-0cab-11e7-8dd2-6b8632873820.png)

**Comment by gitasong** [comment]
I'm with @stevenyeager on this one (and I'm not asking for help). It took me several years to get a handle on what a div is and what it's used for. The lightbulb only went on after observing that web pages tended to group elements with a specific function in different parts of the page—for instance, header, nav bar, sidebar, footer. Then the lightbulb went on.

@stevenyeager is correct about the bolded text above: It's jargonese, and contains terms ("passing," "class declarations") and concepts (inheritance) that have not yet been taught or defined.

I would suggest the following edit, or something similar, for the bolded text:
"It's useful for grouping similar elements that all share a common function—for instance, the links in a menu, the items in a sidebar, or the elements in a footer."
