### ISSUE TITLE
Change Color of Text doesn't allow uppercase inline style

### ISSUE THREAD

**Issue by kishoreiyer1412** [freeCodeCamp/freeCodeCamp#14006]
Challenge [change-the-color-of-text](http://beta.freecodecamp.com/en/challenges/basic-css/change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<h2 STYLE ="COLOR:RED;">CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

**Comment by Marmiz** [comment]
@kishoreiyer1412 thanks for reporting the issue.

Despite writing the inline style declaration in capital is not an error per-se, it's however considered bad practice among programmer.

So I believe the challenge is correct in not letting the above code pass.

**Comment by erictleung** [comment]
@kishoreiyer1412 thanks for the issue. Your code is *correct*, but if you compare your code with the example, you can see that the style and CSS information is lowercase, rather than uppercase as in your code.

cc/ @freeCodeCamp/moderators I feel like this has come up before. Should we just mention somewhere that CSS is generally in lowercase? Or change the test to include uppercase? [Here's](https://github.com/freeCodeCamp/freeCodeCamp/blob/c94f5e34c308697c3c582814c7f5834b0cf752e9/seed/challenges/01-responsive-web-design/basic-css.json#L90) the line of code for the test.

**Comment by Marmiz** [comment]
@erictleung 
>Or change the test to include uppercase?

In my opinion, no.
As a learning platform we should teach campers also the best practice in coding, and writing CSS in capital is certainly not.

So I'm fine that the challenge fail to pass the given code.

What we can do, and I agree with you, is be explicit about it, maybe by adding a few line in the challenge where we inform the camper about capitalization.
Maybe something like this:

>The style that is responsible for the color of an element's text is the "color" style.
Here's how you would set your h2 element's text color to blue:
`<h2 style="color: blue;">CatPhotoApp</h2>`
When writing styles please also mind capitalization. 
Despite not being an error per-se, writing CSS in capital letters is considered bad practice among programmers and often flagged as bad example of code.

**Comment by QuincyLarson** [comment]
@Marmiz @erictleung we need to be careful not to weight down the instructions too much. 

We could add a simple statement like "Note that CSS is case-sensitive so be careful with your capitalization." shortly after we introduce CSS. Would either of you be interested in doing this?

**Comment by Marmiz** [comment]
@QuincyLarson I'll be happy to help 👍
