### ISSUE TITLE
Issue with <h2 class="red-text"CatPhotoApp</h2>

### ISSUE THREAD

**Issue by iamsamcode** [freeCodeCamp/freeCodeCamp#14007]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%0A%20%20.red-text%20%20%7Bcolor%3Ared%7D%0A%20%20%0A%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
 
  .red-text  {color:red}
  

</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Marmiz** [comment]
@iammangod96 thanks for reporting this issue.

In your code however you're forgetting about a tiny, yet crucial detail: the closing semicolon `;` at the end of the declaration.

If you need assistance with a challenge next time please consider asking for help in one of the [official chat rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or into the [forum](https://forum.freecodecamp.com)

Happy coding 👍

**Comment by erictleung** [comment]
@iamsamcode Thank you for reporting this issue. But as @Marmiz has mentioned, you're missing a semicolon.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!

**Comment by tung776** [comment]
But in my case this error still happened. Here is my code
<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>


It is not working

**Comment by Marmiz** [comment]
@tung776 Thanks for replying.

This portion of your code worked for me:
```
<style> .red-text {   color: red; } </style>
```
What you can do is try to refresh the page and see if that works.

If it doesn't please reply with more details: operating system, browser, device... and the full formatted code you're trying to test.

Thanks 👍

**Comment by tung776** [comment]
It worked on my window 10 chrome browser but it is not working on chrome
for android

CÔNG TY CỔ PHẦN KIM KHÍ HÓA CHẤT CÁT TƯỜNG
Đ/C: 35 Diên Hồng phường Quang Trung Nam Định

Vào 22-03-2017 1:48 CH, "Claudio Restifo" <notifications@github.com> đã
viết:

**Comment by Charlie2006** [comment]
Type <h2 class='red-text'>CatPhotoApp</h2>

**Comment by Charlie2006** [comment]
It won't let me type code in the comments

**Comment by Charlie2006** [comment]
`<h2 class='red-text'>CatPhotoApp</h2>`

**Comment by Charlie2006** [comment]
In-between the triangle bracket and the equals you put " but you need to put ' instead

**Comment by texas2010** [comment]
@Charlie2006 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
