### ISSUE TITLE
Check for Palindromes Bonfire won't pass

### ISSUE THREAD

**Issue by Butter1484** [FreeCodeCamp/FreeCodeCamp#1401]
I have met all conditions of the Check for Palindromes Bonfire but it will not mark it as passed
![bonfire](https://cloud.githubusercontent.com/assets/5353136/8922358/cc34fd0e-34af-11e5-8940-b0c5a2f42365.PNG)

**Comment by benschenker** [comment]
Hey @Butter1484,

Is this still an issue? If so please check out our [Bug Reporting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) and paste some code samples so that we can replicate this issue.
