### ISSUE TITLE
[beta] NPM introduction page rendering

### ISSUE THREAD

**Issue by Atomk** [freeCodeCamp/freeCodeCamp#14017]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/managing-packages-with-npm/introduction-to-the-managing-packages-with-npm-challenges

#### Issue Description

In the first "page" of the introduction for the NPM challenges (there's two pages) the list is rendered with a smaller font. Looking in the HTMl, everything below the `<ol>` opening tag is put outside the `<p>` the rest of the test is put in. (see first screenshot)
But there's more. If you press "go to my next step", the list I mentioned stays there, below the second part of the introduction (see second screenshot).
Now, pressing "go to my previous step", the page is rendered correctly but the list is still there (see third screenshot). I tried to look for errors in the seed file but everything looks fine, could it be an issue with React?

#### Browser Information

* Browser Name, Version: Chrome 57.0.2987.98 (64-bit)
* Operating System: Windows 7 x64
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

1)
![image](https://cloud.githubusercontent.com/assets/6122017/24104108/a1823d90-0d81-11e7-95c4-c99019c62efa.png)

2)
![image](https://cloud.githubusercontent.com/assets/6122017/24104249/062d6f76-0d82-11e7-9698-e8c4fb3eeba6.png)

3)
![image](https://cloud.githubusercontent.com/assets/6122017/24104359/53e374cc-0d82-11e7-8f5a-f24540161c6f.png)

**Comment by QuincyLarson** [comment]
@Atomk nice find! Since you've already done a lot of the investigative work, would you be interested in refactoring the CSS to fix this?

**Comment by Atomk** [comment]
@QuincyLarson I think it's a problem with how introduction text is rendered, because when all the text is inside the `<p class="challenge-step-description">...</p>` everything is fine, but it seems that for some reason React puts part of the description outside that element (see first screenshot), so it is styled in a different way and React can't replace it when loading the second part of the introduction. It seems that the text is split when a list element `ul` or `ol` is encountered. I tried to look at the code that handles this, but it looks a bit too complex for me at the moment to figure this out by myself.
