### ISSUE TITLE
Where to Find Pipe Symbol

### ISSUE THREAD

**Issue by johnrayworth** [freeCodeCamp/freeCodeCamp#14018]
Challenge [Comparisons with the Logical Or Operator](https://www.freecodecamp.com/challenges/comparisons-with-the-logical-or-operator#?solution=%0Afunction%20testLogicalOr(val)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0A%20%20if%20(val%20%3C%2010%20%7C%7C%20val%20%3E%2020)%20%7B%0A%20%20%20%20return%20%22Outside%22%3B%0A%20%20%7D%0A%0A%20%20%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20%22Inside%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestLogicalOr(15)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testLogicalOr(val) {
  // Only change code below this line

  if (val < 10 || val > 20) {
    return "Outside";
  }

  

  // Only change code above this line
  return "Inside";
}

// Change this value to test
testLogicalOr(15);

```
//You should probably mention the name of the | symbol as "pipe" or "vertical bar", and indicate //where to find it on the keyboard. (The same is probably unnecessary for the "ampersand" & //symbol, though for consistency you might want to consider that addition too.)

**Comment by ZZhaoTireless** [comment]
I will take this.
