### ISSUE TITLE
[beta] Replace GoMix with Glitch

### ISSUE THREAD

**Issue by Atomk** [freeCodeCamp/freeCodeCamp#14015]
Recently, GoMix was renamed to Glitch. The "old" URLs are not working anymore, and this breaks some challenges, like [this one](https://medium.com/glitch/welcome-to-glitch-fe161d0fc39b#.suxl68eol). We should change all the appearances of "Gomix" to "Glitch" and fix all the broken links. It looks like in most cases the users are redirected to the right URL (glitch.com), but not always (e.g. the first link in the NPM introduction).

---

You can find more information about this name change [in this article](https://medium.com/glitch/welcome-to-glitch-fe161d0fc39b#.suxl68eol).

I'm aware of #13095 but I think this is a different problem.

**Comment by ZZhaoTireless** [comment]
I would like to take this. Could I know if the **beta** version has been in `staging` branch, or it in another `branch` or `repo`?

**Comment by dhcodes** [comment]
Beta is on staging. Rebase with the latest updates and you should be good to go

**Comment by ZZhaoTireless** [comment]
@dhcodes Thanks!

**Comment by Atomk** [comment]
Just an additional note, the tests should be updated too, since they expect to retrieve data from gomix.com:

![00](https://cloud.githubusercontent.com/assets/6122017/24137574/a8dac826-0e14-11e7-947a-eb7d34d386fb.PNG)

**Comment by ZZhaoTireless** [comment]
@Atomk Will update the tests after fixing. Thanks.

**Comment by QuincyLarson** [comment]
Awesome - thanks for fixing this @ZZhaoTireless.

I've talked with Glitch's CEO and he seems confident this is their final name change.

**Comment by ZZhaoTireless** [comment]
Hi, I updated all "GoMix" to "Glitch" and pulled request.

**Comment by breakpoint25** [comment]
I was looking to try beta, but it is not working as this has not updated yet. When is it expected to be updated to the website?

**Comment by QuincyLarson** [comment]
@breakpoint25 we're actively working on some major fixes. We'll push them as frequently as we can. I think currently most of the challenges should work fine right now - only certain sections are non-functional.
