### ISSUE TITLE
Symmetric Difference Independent of Order

### ISSUE THREAD

**Issue by alf808** [FreeCodeCamp/freecodecamp#1402]
Here's a clear definition of set equality. One sees that order is not explicit at all.
https://proofwiki.org/wiki/Definition:Set_Equality
Two sets are equal iff they contain the same elements:
∀x:(x∈A⟺x∈B)⟺A=B
The order of the elements in the sets is immaterial.

Is there a way to reopen this topic?
(Edited note: I eliminated the reference to commutativity and associativity of symmetric difference since it is irrelevant to set equality)

the youtube video presented in case #1358 does not demonstrate at all that ordering matters.

I think the equality of sets is independent of order. {1,2,3} = {3,2,1}
see more here: http://www.cs.odu.edu/~toida/nerzic/content/set/basics.html

Please also note that according to the site above that is also true that:
{1, 2, 3} = {3, 2, 1, 1}, that is duplications do NOT make any difference for sets.

**Comment by SaintPeter** [comment]
I've replied on the other issue, and I agree, order is not important.

However, you correctly note that:
(AΔB)ΔC = AΔ(BΔC).

Are you attempting to argue that the Bonfire is not correct?  Because I believe it is easily demonstrable that it is.

**Comment by alf808** [comment]
just based on this ∀x:(x∈A⟺x∈B)⟺A=B , it's clear to me that order is NOT important. Bonfire testing is NOT correct

**Comment by alf808** [comment]
Prescribing the order of the elements defeats the purpose of doing set theory at all. FCC either does set theory concept with symmetric difference or not at all. FCC can redefine and redesign the challenge without calling it symmetric difference. Set equality is fundamental in set theory. Why do set theory and not do set theory? it's contradictory.

**Comment by alf808** [comment]
I can "solve" the problem too. I've been doing this for a week now. Some of my code has been hacky so I can "solve" the problem or pass the test cases. But it's not my point. Why go through the pretense of doing a set theory concept? why bother with this symmetric difference corollary S∗T=(S∪T)∖(S∩T) and not bother with a set equality axiom ∀x:(x∈A⟺x∈B)⟺A=B ? If symmetric difference is not the point of the problem, then I think it should be redesigned and it not be labelled symmetric difference. If symmetric difference is the point, then set equality is fundamental and axiomatic.

**Comment by KMAN9959** [comment]
Please take me off of your emails I am getting a 100 a day

**Comment by alf808** [comment]
I don't know who you are. I don't know how freecodecamp works. I couldn't
possibly have sent you 100 emails.

**Comment by KMAN9959** [comment]
No you didn't everybody in the free code camp universe has I am being copied on every email every one sends. Can't you post s global email saying there is something wrong here

**Comment by aliaslam7163** [comment]
You can stop it by changing the setting from github

**Comment by alf808** [comment]
I am absolutely confounded. I don't know who you are. Why would I post a
global email? Do you mean in a planetary scale?  That sounds insane. Why? I
have very little knowledge of this organization as I've been doing this
only a week!

**Comment by KMAN9959** [comment]
It was a bit of a tongue and check comment because of your comment that I couldn't have received 100emails. I have received one hundred since you spammed me an hour ago

**Comment by KennethFax** [comment]
S                                                                                                                                                                                                   N

**Comment by KennethFax** [comment]
Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: KMAN9959Sent: Tuesday, July 28, 2015 17:32To: FreeCodeCamp/freecodecampReply To: FreeCodeCamp/freecodecampSubject: Re: [freecodecamp] Symmetric Difference Independent of Order (#1402)Please take me off of your emails I am getting a 100 a day

Sent from my iPhone

> On Jul 28, 2015, at 6:12 PM, alf <notifications@github.com> wrote:
> 
> I can "solve" the problem too. I've been doing this for a week now. Some of my code has been hacky so I can "solve" the problem or pass the test cases. But it's not my point. Why go through the pretense of doing a set theory concept? why bother with this symmetric difference corollary S∗T=(S∪T)∖(S∩T) and not bother with a set equality axiom ∀x:(x∈A⟺x∈B)⟺A=B ? If symmetric difference is not the point of the problem, then I think it should be redesigned and it not be labelled symmetric difference. If symmetric difference is the point, then set equality is fundamental and axiomatic.
> 
> —
> Reply to this email directly or view it on GitHub.
> 


—Reply to this email directly or view it on GitHub.

**Comment by alf808** [comment]
So I spammed you! I still don't know who you are; and you accuse me of
spamming. You must have some inside knowledge of freecodecamp's operations
to have gotten my email address. As I said I've been taking the class only
a week and posted an issue only yesterday. How could I possibly have
spammed you? This is so trivial.

**Comment by royshouvik** [comment]
Hi @KMAN9959 Have you figured out yet that you have to stop watching the Github repository of FreeCodeCamp. I hope this solves your issue with too many emails on your inbox. Thanks.

**Comment by jhnpckr** [comment]
I think either the tests are wrong or the description of the challenge is unclear. Who gets to decide which?

**Comment by alf808** [comment]
I think to be consistent with the whole set theory challenge the tests should allow for this:
 ∀x:(x∈A⟺x∈B)⟺A=B , i.e. without any precribed or explicit ordering. Please I'm sorry in advanced if this is deemed a spam.

**Comment by SaintPeter** [comment]
I have submitted a pull request to resolve this issue (#1426).

My solution is to sort the user's results and then compare against a pre-sorted expected value.  This ensures that any order of user generated results will always equal the test case.

Thanks to @alf808 for banging my head against this one until I understood the issue.  I hope that this solution is acceptable to you.

**Comment by alf808** [comment]
@SaintPeter extremely grateful!! I will close this issue since you have a new one that's more specific. thank you again.

**Comment by SaintPeter** [comment]
I would leave it open until the Pull Request is accepted.

**Comment by alf808** [comment]
I'm still getting this error:
![screen shot 2015-08-11 at 15 46 26](https://cloud.githubusercontent.com/assets/79753/9214998/92d0c074-4040-11e5-9ff2-6674b6c238d0.png)
