### ISSUE TITLE
[Beta] Prompt says to change a line of code that has been changed. 

### ISSUE THREAD

**Issue by CollinPerkins** [freeCodeCamp/freeCodeCamp#14026]
Challenge [increment-a-number-with-javascript](https://beta.freecodecamp.com/en/challenges/basic-javascript/increment-a-number-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var myVar = 87;

// Only change code below this line
myVar++;


```

Says to change a line of code which has been changed. 
It has been changed, it is a miss leading error message to say the least.

![image](https://cloud.githubusercontent.com/assets/18583609/24123922/80e589ee-0d8f-11e7-8962-cb4b21fdd5fa.png)

**Comment by kev0587** [comment]
@CollinPerkins it seems like we're having the same issue, but with different challenges.  I did not get this error when running through my testing for this challenge specifically, but did run into a similar issue for other challenges.

Can you try duplicating the tab and re-running the tests?  If it passes using the same code, then I believe it's the same issue as #14025.

**Comment by no-stack-dub-sack** [comment]
@CollinPerkins Thanks for reporting this issue, I can confirm this also on my end. @kev0587 does not seem to be the same issue you are having, this is likely code specific to this test that is causing the issue. I will have a closer look now...

**Comment by no-stack-dub-sack** [comment]
@CollinPerkins This error is becuase of a RegExp in the test... I had hunch this was the issue as we've been dealing with similar issues ever since we implemented something. The RegExp is/was valid, but the problem is, now there is more than one piece of code on the page for it to match. Even though you cannot see it, this code is also on the page:
```js
;/*fcc*/
"use strict";

var myVar = 87;

// Only change code below this line
myVar++;
;/*fcc*/

(function(z){return 'myVar = ' + z;})(myVar);

;/*fcc*/
```
and this line: `(function(z){return 'myVar = ' + z;})(myVar);` is causing the test to fail. I think we should be able to fix this by making the regexp more strict or testing the failing test case with a different approach. 

Here is the test as it currently exists:
```js
"assert(/myVar\\s*\\=.*myVar/.test(code) === false; console.log(code), 'message: <code>myVar = myVar + 1;</code> should be changed');",
```
We're testing to make sure there is nothing that loosely matches `myVar = myVar` problem being that `IIFE` has similar code, and it is matching that.

**Comment by Manish-Giri** [comment]
@no-stack-dub-sack I made a very small change to test this out, it seems to be working after it. Can I send in a PR which you can then test out?

**Comment by no-stack-dub-sack** [comment]
Ahh, I should have said I was working on it, as I was just getting ready to send in a pr myself. It's been a bit too long! Umm, should we compare solutions and see whose is better and go with that? I'm sure they're both very small changes

**Comment by no-stack-dub-sack** [comment]
Here's mine: 
```js
"assert(/myVar\\s*\\=.*myVar\\s*\\+\\s*1/.test(code) === false, 'message: <code>myVar = myVar + 1;</code> should be changed');",
```

**Comment by Manish-Giri** [comment]
Ah, all right! Go for it 👍 

Mine was 
```
"assert(/myVar\\s*\\=\\s*myVar/.test(code) === false, 'message: <code>myVar = myVar + 1;</code> should be changed');",
```
Although, not completely sure, why this works, anyway.

**Comment by no-stack-dub-sack** [comment]
@Manish-Giri Yeah, that's odd! It doesn't look like it should work, that should still match the tail... strange. This one I think is a bit more strict so probably a safer bet in the end

**Comment by no-stack-dub-sack** [comment]
@Manish-Giri just opened the PR if you'd like to test and review!

**Comment by Manish-Giri** [comment]
@no-stack-dub-sack Tested it, works! 👍 💯
