### ISSUE TITLE
Target Even Numbered Elements Using jQuery UX

### ISSUE THREAD

**Issue by sgaweda** [freeCodeCamp/freeCodeCamp#14020]
#### Challenge Name

<a href="https://www.freecodecamp.com/challenges/target-even-numbered-elements-using-jquery">Target Even Numbered Elements Using jQuery</a>

#### Issue Description

I've read some of the feedback with this problem and how it deals with the even/odd issue and while I was able to understand what the code does, visually it doesn't make much sense to me. We label these buttons with text and numbers, but the elements that shake (please correct me if I'm wrong) are numbered by their ordering in the wells at the point the code executes. This for me was target1, target5, and target6, hardly a set of even (or odd) numbers. Furthermore, without having done the JavaScript problems (I did them because I skipped ahead), the concept of indexes that start from zero could be confusing to someone encountering them for the first time.

From a UX standpoint I found this problem confusing even though I think I understand what's happening. I can't imagine how confusing it would be for someone who doesn't understand.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop (is this Desktop?)

**Comment by JoolsMcFly** [comment]
Is it the fact that final _shake_ elements have numbers that are odd that's troubling you?

I agree it would be simpler if elements were 
```
Target 0
Target 1
Target 2
Target 3
```

So running your code would _shake_ Target 1 and 3, making it easier to visually see the consequence of arrays being zero based.

What do you think?

**Comment by sgaweda** [comment]
I apologize for the late follow up. Yes, that seems like a good way to make it clearer that things are zero based. I think perhaps additionally it might be a good idea to mention what it means for something to be zero indexed, or link to an external article that explains it. For those without experience developing, this could be a confusing new concept.

I was hesitant to make a suggestion in my original post because I wasn't sure what would be appropriate.

**Comment by TMorgan99** [comment]
Note that jQuery is zero-indexed, meaning that, counter-intuitively, :odd selects the second element, fourth element, and so on.

OK, but we just did :nth-child(n), where we were one-indexed .... 
Please clarify.

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/freeCodeCamp/pull/14549.
