### ISSUE TITLE
Escape Sequences in Strings challenge not accepting escape sequences

### ISSUE THREAD

**Issue by baotrum** [freeCodeCamp/freeCodeCamp#14036]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D%20%22FirstLine%5Cn%5C%5C%5C%22SecondLine%5C%22%5C%5C%5CrThirdLine%22%3B%20%0A%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr= "FirstLine\n\\\"SecondLine\"\\\rThirdLine"; 
// Change this line



```
![untitled](https://cloud.githubusercontent.com/assets/22302982/24157830/1bcca5d4-0e8d-11e7-83f8-470c92024446.png)
my code doesn't have any space but it's still error, somebody please explain to me !!!

**Comment by fortMaximus** [comment]
@baotrum The challenge didn't ask you to put (escape) double quotes ( `\"`) around `SecondLine`.

This is not a bug, and Github issues are for reporting bugs.

If you need help with a challenge, you should ask in one of the help rooms first.

Thank you.

**Comment by baotrum** [comment]
i'm try ask at help rooms but not reply, i'm try new code but it's still wrong
my code 
`var myStr = "Thisis\n\\thefirst\\\rsentence.";`

**Comment by fortMaximus** [comment]
@baotrum sorry about the misunderstanding. Sometimes no one knows the answer or the other campers are busy helping other campers. Next time try to ask the question again at another time.

Now about your solution, the text you were using in the screenshot above was correct, the error was only that you were using the escape code for double quotes when you're not asked to.

**Comment by suchith892** [comment]
var myStr = "FirstLine\n\\SecondLine\\\rThirdLine";
 
note:Note that the backslash itself must be escaped in order to display as a backslash.(this point helped me to get solution for this.

**Comment by lisa13** [comment]
This one worked perfectly fine for me! var myStr = "FirstLine\n\\SecondLine\\\rThirdLine";

**Comment by texas2010** [comment]
@lisa13 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by lisa13** [comment]
@texas2010 Roger that! I apologize! :D If anyone's still having problem with this task and needs help PM me ;)

**Comment by texas2010** [comment]
@lisa13 no problem.

**Comment by AurelianSpodarec** [comment]
![image](https://user-images.githubusercontent.com/10155855/33631266-5e374048-da0a-11e7-8475-7a5a8aacfca1.png)

It doesn't work - this is bugged.

**Comment by dania2007** [comment]
i dont no how to do this "myStr should have encoded text with the proper escape sequences and no spacing." im ten
