### ISSUE TITLE
[beta] .env is not a default feature in Node

### ISSUE THREAD

**Issue by Atomk** [freeCodeCamp/freeCodeCamp#14033]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/basic-node-and-express/use-the-env-file

#### Issue Description

I'm writing the code for the Node challenges locally, and I had a hard time trying to figure out why I could not access the variables I put in my `.env` file using `process.env`. I discovered that to use `.env` files outside gomix/glitch you have to include the `dotenv` package, which is not included in the repo for the Node/Express challenges. This is not mentioned anywhere in the challenge instructions, I thought it was a default feature in Node but it is not. I suggest the following changes to avoid confusion:

- Add a dependency to `dotenv` in the downloadable repo
- Add a `.env` file to the downloadable repo
- Edit the description to explain that Node does not use `.env` files by default

I can do this but I'd like to have an opinion about it before changing anything.

**Comment by IsaacAbrahamson** [comment]
:+1:

**Comment by QuincyLarson** [comment]
@JosephLivengood what are your thoughts on this? Is there any problem with Glitch (formerly Gomix) if we include dotenv in the package.json? If not, would you be interested in updating the necessary repos/boilerplates?

**Comment by JosephLivengood** [comment]
@QuincyLarson I don't believe it will create any issues on HyperMixGlitch, but I'll do some testing to ensure.

If we add that to the repos, where should it be explained why/what it does? Maybe we need an early slide in the curriculum explains enviromental variables and how to set them in the console and using a file (with dotenv)?

If that sounds good I can write somethings up and share what I write here and seed it with approval and work on committing(or PR'ing) to the 20 repos that switch
