### ISSUE TITLE
Spaces seemingly not allowed

### ISSUE THREAD

**Issue by aksnowman** [freeCodeCamp/freeCodeCamp#14031]
Challenge [create-reusable-css-with-mixins](https://beta.freecodecamp.com/en/challenges/sass/create-reusable-css-with-mixins) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  
  @mixin border-radius($radius){
    -webkit-border-radius: $radius;
    -moz-border-radius: $radius;
    -ms-border-radius: $radius;
    border-radius: $radius;
  }
  
  #awesome {
    width: 150px;
    height: 150px;
    background-color: green;
    @include border-radius(15px);
  }
</style>

<div id="awesome"></div>
  

```

This challenge took me a few extra minutes to figure out as it seems to want *exact* lines. I had originally started with:
  @mixin border-radius( $radius ){
and
    @include border-radius( 15px );
respectively (note the spaces around the arguments). Is this a limitation of Sass, or of FCC/the level? If it is a hard requirement, would it be worth documenting somewhere? I just know this is the type of thing that has frustrated me a lot in prior years with similar challenges, and I can imagine it driving away people less familiar.

**Comment by ooade** [comment]
@aksnowman Sass allows it. Wanna fix this?

**Comment by aksnowman** [comment]
Actually, I suppose I can fix it! I'll poke around with it sometime in the next few days.

**Comment by ooade** [comment]
Okay :+1:
