### ISSUE TITLE
D3 challenges "Identifier 'dataset' has already been declared"

### ISSUE THREAD

**Issue by IsaacAbrahamson** [freeCodeCamp/freeCodeCamp#14042]
Challenges 4, 5, etc., not logged in.

User Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

**Steps to reproduce:**
1. Pass challenge 4, Work with Data in D3.
My passing code was:
```
<body>
  <script>
    const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
    
    // Add your code below this line
    
    d3.select('body').selectAll('h2')
      .data(dataset)
      .enter()
      .append('h2')
      .text('New Title');
    
    // Add your code above this line
  </script>
</body>
```

2. Do not go on to next challenge.
3. Resubmit and get this error:
```
// running test
"Identifier 'dataset' has already been declared"
"Identifier 'dataset' has already been declared"
"Identifier 'dataset' has already been declared"
"Identifier 'dataset' has already been declared"
// finished test
```

You can also get this error by:
1. Completing and passing challenge 4.
2. Moving on to challenge 5.
3. Submitting challenge 5, even with correct code.
4. Get the error, and your code will not show on phone.
5. Refresh page, it will pass.

**Comment by IsaacAbrahamson** [comment]
cc/ @freeCodeCamp/moderators 

Plz help me out if I did not make this issue right. ;)

**Comment by lin4rd** [comment]
I've never done any of this before, I'm trying to get an idea of the basic
stuff

**Comment by erictleung** [comment]
@IsaacAbrahamson this might be a duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/13936, which links to a deeper issue of https://github.com/freeCodeCamp/freeCodeCamp/issues/12762.

**Comment by IsaacAbrahamson** [comment]
@erictleung, looks like you're right! Thanks for helping out.
