### ISSUE TITLE
One palindrome test pattern should return true result.

### ISSUE THREAD

**Issue by shorebird2016** [freeCodeCamp/freeCodeCamp#14045]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes#?solution=%0Afunction%20palindrome(str)%20%7B%0A%20%20%20%20var%20replaced_result%20%3D%20str.replace(%2F%5B%5Ea-zA-Z%5D%2Fg%2C%20'').toLowerCase()%3B%0A%0A%20%20%20%20%2F%2Fa%20loop%20to%20detect%20palindrome%0A%20%20%20%20var%20ret%20%3D%20false%3B%0A%20%20%20%20for%20(var%20idx1%20%3D%200%3B%20idx1%20%3C%20replaced_result.length%2F2%3B%20idx1%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20if%20(replaced_result%5Bidx1%5D%20!%3D%20replaced_result%5Breplaced_result.length%20-%20idx1%20-%201%5D)%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D%0A%20%20return%20true%3B%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function palindrome(str) {
    var replaced_result = str.replace(/[^a-zA-Z]/g, '').toLowerCase();

    //a loop to detect palindrome
    var ret = false;
    for (var idx1 = 0; idx1 < replaced_result.length/2; idx1++) {
        if (replaced_result[idx1] != replaced_result[replaced_result.length - idx1 - 1])
            return false;
    }
  return true;
}



palindrome("1 eye for of 1 eye.");

```
This code returns true because after removing non-alpha characters, string looks like "eyeforofeye" which is a palindrome.

However the test insists on result to be false.  Please see the screen shot below.
![run test](https://cloud.githubusercontent.com/assets/19984312/24195549/707d2fde-0eb7-11e7-90ce-62f04c34fb45.png)

**Comment by sshepanski7** [comment]
It's been way to long this way I just got out of a cell with no moving air
no running water a camera faceing the toilet for 12 hours for another sum
afence with proof I didn't do it I had my hands smashed by a cop with a
clip board and threaten to have my face smashed in this is the 5th time I
got tons more !!!

Spanky
Show quoted text


Spanky

**Comment by Marmiz** [comment]
I'm afraid the challenge is asking you to remove all non-alphanumerical value:

>A nonalphanumeric character is a character, or symbol, that appears on a keyboard that is not a number or a letter, including punctuation and mathematical symbols.

Or in other words: numbers are alphanumeric.

So the test is correct in stating that `palindrome("1 eye for of 1 eye.");` should return false since it's not a palindrome.

If you believe that the challenge explanation:
>You'll need to remove all non-alphanumeric characters (punctuation, spaces and symbols)

Is not clear/sufficient enough we can discuss an enhancement to the text to make clear we want letters and numbers.

Happy coding 👍

**Comment by JoolsMcFly** [comment]
It's not an issue because instructions say to
> remove all non-alphanumeric characters (punctuation, spaces and symbols)

Alphanumeric includes digits so you should not be removing `1`

**Comment by srikanthkanjarla** [comment]
You'll need to remove all non-alphanumeric characters ( combination of alphabetic and numeric characters ) so Add 0-9 in your regular expression

function palindrome(str) {
    var replaced_result = str.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();

    //a loop to detect palindrome
    var ret = false;
    for (var idx1 = 0; idx1 < replaced_result.length/2; idx1++) {
        if (replaced_result[idx1] != replaced_result[replaced_result.length - idx1 - 1])
            return false;
    }
  return true;
}



palindrome("1 eye for of 1 eye.");

**Comment by erictleung** [comment]
@shorebird2016 thanks for the issue, but as others have noted, numbers are alphanumeric and do not need to removed. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
