### ISSUE TITLE
Challenge Seed is passing as the correct solution for an ES6 challenge

### ISSUE THREAD

**Issue by kev0587** [freeCodeCamp/freeCodeCamp#14043]
Challenge [use-destructuring-assignment-to-pass-an-object-as-a-functions-parameters](http://beta.freecodecamp.com/en/challenges/es6/use-destructuring-assignment-to-pass-an-object-as-a-functions-parameters) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Run the tests without editing the code.

```js


const stats = {
  max: 56.78,
  standard_deviation: 4.34,
  median: 34.54,
  mode: 23.87,
  min: -0.75,
  average: 35.85
};
// change code below this line
const half = (stats) => ((stats.max + stats.min) / 2.0); // use function argument destructurung
// change code above this line
console.log(stats); // should be object
console.log(half(stats)); // should be 28.015

```

The code that is pre-populated in the Editor for you (as shown above) is passing as the solution for the challenge.  The following solution should be used in order for this challenge to pass:

```js
const stats = {
    max: 56.78,
    standard_deviation: 4.34,
    median: 34.54,
    mode: 23.87,
    min: -0.75,
    average: 35.85
}

/* Alter code below this line */
const half = ({max, min}) => ((max + min) / 2.0); // use function argument destructurung
/* Alter code above this line */

console.log(stats); // should be object
console.log(half(stats)); // should be 28.015
```

**Comment by JoolsMcFly** [comment]
_destructurung_ should also be changed to _destructuring_ in the function's comment.

**Comment by robbawebba** [comment]
@kev0587 Thanks for the heads up! Most tests in the ES6 section of the beta curriculum are either not written or unusable. There's some work in progress to get the tests working for the ES6 challenges, but for now we won't be able to verify solutions 😕 Feel free to continue with the curriculum in the meantime though!

also nice find @JoolsMcFly!
