### ISSUE TITLE
Description missing for a required function, needs minor clarification

### ISSUE THREAD

**Issue by ayersg** [freeCodeCamp/freeCodeCamp#14058]
#### Challenge Name: Create a Priority Queue Class
http://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/create-a-priority-queue-class

#### Issue Description
This isn't a major issue, but for this challenge the directions are:
"You will need to add an **enqueue method** for adding items with a priority, a **dequeue method** for popping off the front item, a **size method** to return the number of items in the queue, and finally an **isEmpty method** that will return true or false if the queue is empty."
(bold text is my own added emphasis)
These directions are pretty specific.  However, if you go to complete this challenge using these functions, you won't pass, because there is actually an additional required **front function**.  I just think, since the directions include all the other required functions, that they should also include mentioning the front function as well. 

#### Browser Information
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

#### Screenshot
(you can see that there are actually five required functions, not four)
![screen shot 2017-03-22 at 10 23 21 pm](https://cloud.githubusercontent.com/assets/10101616/24233249/38673d00-0f4e-11e7-8622-4e33775e41ae.png)

**Comment by Manish-Giri** [comment]
I'll take a shot at this.
