### ISSUE TITLE
Text in Add Font Awesome Icons to our Buttons challenge needs a minor edit

### ISSUE THREAD

**Issue by Ellyria** [freeCodeCamp/freeCodeCamp#14051]
#### Challenge Name

https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-our-buttons

#### Issue Description

This section has unnecessary text in it:

You can add Font Awesome to any app **just by including it** by adding the following code to the top of your HTML:

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![screenshot](https://cloud.githubusercontent.com/assets/26424000/24208594/5596b21a-0efa-11e7-8120-4751fd72868e.png)

**Comment by solankivir** [comment]
<button ***** > <i class="fa fa-thumbs-up"> like </i> </button>

so we are basically adding <i> inside button

**Comment by solankivir** [comment]
insert <i class = "****" > like </i> inside button tag

**Comment by OFFLlNE** [comment]
I agree with  @Ellyria , that it would be better without that bolded out text in the first post.
@Ellyria would you like do the edit yourself?

**Comment by Ellyria** [comment]
We might want to discuss it some more and see if solankivir agrees with a compromise.

My original edit suggestion was to remove **just by including it** from the sentence. That left it slightly awkward with **add** in the sentence twice:

`You can add Font Awesome to any app by adding the following code to the top of your HTML:`

Instead, I'd like to suggest changing it this way, replacing the first **add** with **include** and removing **just by including it** for a much smoother read that hopefully captures the full intent:

`You can include Font Awesome in any app by adding the following code to the top of your HTML:`

I'm still a complete newbie with Git, so you might want to handle the actual edit.

**Comment by erictleung** [comment]
[This line](https://github.com/freeCodeCamp/freeCodeCamp/blob/d5db2803ad0214e43f2d4ddc12f8a1b1976ac853/seed/challenges/03-front-end-libraries/bootstrap.json#L1260) of code needs to be changed to be:

> You can include Font Awesome in any app by adding the following code to the top of your HTML:

To whoever takes this up, please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/Contributors) chat room if you have any questions about helping. We're there to help.

**Comment by cch5ng** [comment]
hi, I can work on this

**Comment by hector57** [comment]
<button class="btn btn-block btn-primary fa fa-thumbs-up"><i class="fa fa-thumbs-up"></i>Like</button>

**Comment by AlonaGo2** [comment]
<button class="btn btn-block btn-primary">< i class="fa fa-thumbs-up">Like</button></i>

**Comment by AlonaGo2** [comment]
<button class="btn btn-block btn-primary"> <i class="fa fa-thumbs-up">Like</button></i>

**Comment by Annastaciahubbard** [comment]
F
