### ISSUE TITLE
Wherefore art thou could use more test cases.

### ISSUE THREAD

**Issue by skylarjhdownes** [freeCodeCamp/freeCodeCamp#14057]
Challenge [Wherefore art thou](https://www.freecodecamp.com/challenges/wherefore-art-thou#?solution=%2F%2F%20jshint%20esversion%3A6%0A%0Afunction%20whatIsInAName(collection%2C%20source)%20%7B%0A%20%20%2F%2F%20What's%20in%20a%20name%3F%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20%2F%2Fsearch%20through%20an%20array%20of%20objects%2C%20and%20return%20objects%20that%0A%20%20%2F%2Fcontain%20key%3Avalue%20pairs%20that%20are%20in%20the%20source%20object%0A%0A%20%20%0A%20%20collection.forEach(%0A%20%20%20%20(objectInCollection)%20%3D%3E%20%7Blet%20go%20%3D%20false%3B%20Object.keys(source).forEach(%0A%20%20%20%20%20%20(sourceObjectKey)%20%3D%3E%20%7B%20%0A%20%20%20%20%20%20%20%20if%20(objectInCollection.hasOwnProperty(sourceObjectKey)%20%26%26%20%0A%20%20%20%20%20%20%20%20%20%20%20%20source%5BsourceObjectKey%5D%20%3D%3D%20objectInCollection%5BsourceObjectKey%5D)%20%7B%0A%20%20%20%20%20%20%20%20%20%20go%20%3D%20true%3B%0A%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%20%20go%20%3D%20false%3B%0A%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%20%20if%20(go%20%3D%3D%3D%20true)%0A%20%20%20%20%20%20%20%20arr.push(objectInCollection)%3B%0A%20%20%20%20%7D)%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20arr%3B%0A%7D%0A%0Aconsole.log(whatIsInAName(%5B%7B%20first%3A%20%22Romeo%22%2C%20last%3A%20%22Montague%22%20%7D%2C%20%7B%20first%3A%20%22Mercutio%22%2C%20last%3A%20null%20%7D%2C%20%7B%20first%3A%20%22Tybalt%22%2C%20last%3A%20%22Capulet%22%7D%2C%20%7B%20%22a%22%3A%201%2C%20%22b%22%3A%202%2C%20%20%22c%22%3A%203%7D%5D%2C%20%7B%20%22a%22%3A%201%2C%20%22b%22%3A%209999%2C%20%20%22c%22%3A%203%7D))%3B%0A) seems lacking in test cases for invalid input.  I would think that 

```whatIsInAName([{ "a": 1, "b": 2,  "c": 3}], { "a": 1, "b": 9999,  "c": 3})```

ought to return an empty array, for instance.  There is currently no check for this, so my code which returns 

```{ "a": 1, "b": 2,  "c": 3}``` 

passes all test cases.

**Comment by JoolsMcFly** [comment]
Good catch. Your code doesn't pass the beta version though: https://beta.freecodecamp.com/en/challenges/intermediate-algorithm-scripting/wherefore-art-thou
so that's an improvement.

I'll investigate to see if we can make a PR against master branch.

**Comment by erictleung** [comment]
@skylarjhdownes sounds like a valid addition to the tests. But we'll also need to add that additional requirement into the instructions.

@JoolsMcFly if changes are made, they can just go to `staging`.

cc/ @freeCodeCamp/moderators second thoughts? If the input for `source` is invalid, just return an empty array?

**Comment by HKuz** [comment]
I'm on board with that 👍

**Comment by CodingPower472** [comment]
I can help with this issue.  I will make a pull request shortly.
