### ISSUE TITLE
broken link in the article: http://evanhahn.com/understanding-express/

### ISSUE THREAD

**Issue by reubinoff** [freeCodeCamp/freeCodeCamp#14060]
Challenge [Build Web Apps with Expressjs](https://www.freecodecamp.com/challenges/build-web-apps-with-expressjs) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

in the article: http://evanhahn.com/understanding-express/ which routed from the training page in the line: "You could clean this up and make it pretty, or you could be hardcore..."
there is a broken link:
https://github.com/isaacs/npm-www#design-philosophy

**Comment by JoolsMcFly** [comment]
I'm afraid a broken link on someone's blog has nothing to with FCC. You should report broken links directly to the author, me@evanhahn.com

Can you close this issue then? Thanks.
