### ISSUE TITLE
Can't scroll down to see challenges on left of screen

### ISSUE THREAD

**Issue by waynegardener** [freeCodeCamp/freeCodeCamp#14066]
Challenge [Learn how Script Tags and Document Ready Work](https://www.freecodecamp.com/challenges/learn-how-script-tags-and-document-ready-work) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html



<!-- Only change code above this line. -->
<script 
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by waynegardener** [comment]
<img width="1280" alt="screen shot 2017-03-23 at 6 57 58 am" src="https://cloud.githubusercontent.com/assets/25894835/24259818/1e30b5b8-0f96-11e7-9800-f22485b8a03a.png">

**Comment by raisedadead** [comment]
Hi @waynegardener , thanks for the reporting.

The issue, here is that your script tag is not completed yet `<script` should be `<script>`.
The code runner executes the code from the editor as you type and live updated the iPhone preview.

Unfortunately, this has UX issues like you have pointed, where the page fails to scroll the instructions area.

We have disabled this in our beta version of the site. And you will see them in the next release.
Until, then I think you should just complete the tag, and I am sure this will work.

Sorry for the inconvenience.

**Comment by waynegardener** [comment]
Thank you.
