### ISSUE TITLE
Sum All Prime , I have the good results, but the test don't succeed

### ISSUE THREAD

**Issue by kaloudiyi** [freeCodeCamp/freeCodeCamp#14067]
Challenge [Sum All Primes](https://www.freecodecamp.com/challenges/sum-all-primes#?solution=%0Afunction%20isPrime(n)%20%7B%0A%20%20%20%20for(var%20j%3D2%3Bj%3Cn%3Bj%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20if((n%20%25%20j)%20%3D%3D%3D%200)%0A%20%20%20%20%20%20%20%20return(false)%3B%0A%20%20%20%20%7D%0A%20%20%20%20return(true)%3B%0A%7D%0A%0Avar%20sum%3D0%3B%0Afunction%20sumPrimes(num)%20%7B%0A%20%20for(var%20i%3D2%3B%20i%3C%3Dnum%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20if(isPrime(i))%20sum%2B%3Di%3B%20%20%20%20%20%20%0A%20%20%7D%0A%20%20return%20sum%3B%0A%7D%0A%0AsumPrimes(10)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function isPrime(n) {
    for(var j=2;j<n;j++) {
        if((n % j) === 0)
        return(false);
    }
    return(true);
}

var sum=0;
function sumPrimes(num) {
  for(var i=2; i<=num; i++) {
      if(isPrime(i)) sum+=i;      
  }
  return sum;
}

sumPrimes(10);

```
I tried that code outside the free code camp editor and checked the results. The results are correct.

**Comment by eb88** [comment]
Your function is actually not clean. The variable sum is outside of the function and is never resettet. So calling the function will result in wrong/not expected results.

Try to move the var sum inside of the sumPrimes Function.

**Comment by kaloudiyi** [comment]
Your absolutely right. I forgot to declare and misplaced the reset of sum which should be inside the function. Thank you very much :-)
