### ISSUE TITLE
Usernames can be reserved URLs

### ISSUE THREAD

**Issue by strman** [FreeCodeCamp/freecodecamp#1406]
From the `Update my portfolio` page, users can request certain usernames that create a conflicting `path to public profile`.

For example, I was able to request the username `account`, even though the resulting `path to public profile` conflicts with `http://www.freecodecamp.com/account` (the page used to update or manage an account). 

Similarly, I was able to request the username `challenges`, which conflicts with `http://www.freecodecamp.com/challenges`, and breaks the user's avatar link. 

Known usernames I've found that conflict with certain URLs:
 * Username `account` conflicts with `http://www.freecodecamp.com/account`
 * Username `challenges` conflicts with `http://www.freecodecamp.com/challenges`
 * Username `signout` conflicts with `http://www.freecodecamp.com/signout`

This could be fixed by reserving usernames that match directory names.

**Comment by benmcmahon100** [comment]
Hi @strman this issue has gotten fixed in staging so hopefully no more funny accounts!
