### ISSUE TITLE
Option for White Background

### ISSUE THREAD

**Issue by johnrayworth** [freeCodeCamp/freeCodeCamp#14065]
Challenge [Golf Code](https://www.freecodecamp.com/challenges/golf-code#?solution=%0Afunction%20golfScore(par%2C%20strokes)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if(strokes%20%3D%3D%201)%7B%0A%20%20%20%20return%20%22Hole-in-one!%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3C%3D%20par%20-2)%7B%0A%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3D%3D%20par%20-%201)%7B%0A%20%20%20%20return%20%22Birdie%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3D%3D%20par)%7B%0A%20%20%20%20return%20%22Par%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3D%3D%20par%20%2B%201)%7B%0A%20%20%20%20return%20%22Bogey%22%3B%0A%20%20%7D%0A%20%20else%20if(strokes%20%3D%3D%20par%20%2B%202)%7B%0A%20%20%20%20return%20%22Double%20Bogey%22%3B%0A%20%20%7D%0A%20%20else%7B%0A%20%20%20%20return%20%22Go%20Home!%22%3B%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(5%2C%204)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function golfScore(par, strokes) {
  // Only change code below this line
  if(strokes == 1){
    return "Hole-in-one!";
  }
  else if(strokes <= par -2){
    return "Eagle";
  }
  else if(strokes == par - 1){
    return "Birdie";
  }
  else if(strokes == par){
    return "Par";
  }
  else if(strokes == par + 1){
    return "Bogey";
  }
  else if(strokes == par + 2){
    return "Double Bogey";
  }
  else{
    return "Go Home!";
  }
  // Only change code above this line
}

// Change these values to test
golfScore(5, 4);

```

This is not a bug, but a request about the UI of FreeCodeCamp. I am a school teacher using this as part of a web class, and I'm projecting the code to a white board. It is very difficult for students to see the code on a black background.

And anyway, a key preferences that people as coders have is the color background they code with (fully acknowledging that that dark is ergonomically better).

Could you implement a choice of UI to be dark/black or light/white?

**Comment by erictleung** [comment]
@johnrayworth thanks for the issue and sorry to taking so long to get back to you about this. Have you tried night mode? If you go to Settings, you can turn on night mode, which might be helpful when projecting on a white board.

![image](https://user-images.githubusercontent.com/2754821/28345103-b8b92122-6bdc-11e7-92a3-0270e4c17625.png)

There is also a hotkey combination of `g t n` that will also toggle night mode. Let us know if this solves your problem.
