### ISSUE TITLE
endsWith() is letting you go through, though it shouldn't

### ISSUE THREAD

**Issue by cherno1985** [freeCodeCamp/freeCodeCamp#14077]
#### Challenge Name
Confirm the Ending

#### Issue Description
One of the clauses forbids you from using the endsWith method:
"Do not use the built-in method .endsWith() to solve the challenge."

However, this code let's you pass to the next stage:

function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  if (str.endsWith(target)){
  return true;
  } else {
    return false;
  }
}

confirmEnding("Bastian", "n");

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by JoolsMcFly** [comment]
regexp used to check code is indeed incorrect:
`!/\\.endsWith\\(.*?\\)\\s*?;/.test(code)`

I'll see if I can make a PR for it.

Thanks.

**Comment by raisedadead** [comment]
This issue is already resolved in staging.
