### ISSUE TITLE
It's not accepting my code. can anyone help me?

### ISSUE THREAD

**Issue by Ankit-a** [freeCodeCamp/freeCodeCamp#14076]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20style%3D%22font-size%3A16px%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p style="font-size:16px">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by Ankit-a** [comment]
![2017-03-24](https://cloud.githubusercontent.com/assets/26455945/24293708/291e99e4-10b9-11e7-856e-c54bb2c61eef.png)


I am not able to submit my code.

**Comment by JoolsMcFly** [comment]
Instructions and expectations contradict themselves. I'll make a PR to fix it.

In the mean time, if you want o move to the next challenge, do as said here:
> Create a second `p` element after the existing `p` element with the following kitty ipsum text: `Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.`

Happy coding. :)

**Comment by Beegos88** [comment]
![freecodecamp ex 18](https://cloud.githubusercontent.com/assets/26626297/24298183/9c1f8c2a-107b-11e7-86c5-b5568c7c5f8e.png)
Hello I believe I found a bug with this exercise due to the fact that I've done this exercise over and over again I did exactly as the instructions stated. Please help, thank you. I have attached a screen shot to demonstrate my efforts.

**Comment by Gardemarin** [comment]
fifth line remove dash.

**Comment by texas2010** [comment]
@Ankit-a 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by Beegos88** [comment]
Thank you. It worked.
