### ISSUE TITLE
[#Issue#  target-the-parent-of-an-element-using-jquery

### ISSUE THREAD

**Issue by binduharitha** [freeCodeCamp/freeCodeCamp#14073]
#### Challenge Name

https://www.freecodecamp.com/challenges/target-the-parent-of-an-element-using-jquery

[#Issue#  target-the-parent-of-an-element-using-jquery.pdf](https://github.com/freeCodeCamp/freeCodeCamp/files/867189/Issue.target-the-parent-of-an-element-using-jquery.pdf)

#### Issue Description

When I click on Run Tests one additional #target5 button gets appended to the left-well.Its populating in next challenge as well. Is it intentionally added ?

#### Browser Information

* Browser Name, Version: Chrome 56.0.2924.87
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

 $("#target5").clone().appendTo("#left-well");

```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by JoolsMcFly** [comment]
I guess it is, to show you how to use jQuery methods. Since it's not stopping you moving on to the next challenge, can you close this issue?

Questions should be asked in forums, not here.

Thanks.

**Comment by binduharitha** [comment]
OK Thanks.
