### ISSUE TITLE
Autoscrolling in Editor please

### ISSUE THREAD

**Issue by Groxic** [freeCodeCamp/freeCodeCamp#14072]
#### Issue Description
This isn't a major issue but I feel it would be nice if the editor auto scrolled when you started typing text below the visible portion. On Windows 10 with Chrome Version 57.0.2987.110 it does not do this.

**Comment by raisedadead** [comment]
Hi @Groxic this looks like a issue, to me. By default the editor should autoscroll. Can you provide some more information if this is on the main website or the beta website?

Also it would be nice if you can take any screen shots and paste the images in here.
