### ISSUE TITLE
Incorrect instructions on how to run how-to-npm

### ISSUE THREAD

**Issue by pdsoper** [FreeCodeCamp/freecodecamp#1407]
Challenge http://www.freecodecamp.com/challenges/waypoint-manage-packages-with-npm has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The README.md file for how-to-npm says to run "how-to-npm" at the command line (after installing it, of course.)  That works. The current instructions in step 12, "Now start this tutorial by running npm install how-to-npm@2.0.0.", do not.

The cloud9 interface has changed somewhat, but that is not a show-stopper.

**Comment by pdsoper** [comment]
I've tried running how-to-npm twice on Cloud9 and once on OS X.  In both cases, it fails at some point in the process, although the exact point of failure varies.  Before I give it another shot, could you reassure me that someone has completed the process recently?

**Comment by royshouvik** [comment]
@pdsoper  This is a bug on FCC. You can start the tutorial by typing
```
how-to-npm
```
on terminal. Hope this helps.

**Comment by BerkeleyTrue** [comment]
This is fixed. Release to come soon.

Happy Coding!
