### ISSUE TITLE
Can't login via github any more

### ISSUE THREAD

**Issue by lynxlynxlynx** [freeCodeCamp/freeCodeCamp#14088]
It seems something similar to #12101, but basically choosing github just redirects to the map, with the "Oops! Something went wrong. Please try again later" error.

The firefox console only shows:
- a mixed content warning (before an https redirect),
- a getPreventDefault deprecation warning and
- "Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead."

There was some discussion about the last point in other bugs, but nothing that seemed immediately relevant.

Tried in FF 52 on linux and chromium 56 with empty caches. I think it happened with an older version as well, but I haven't tried logging in in a while. It works fine for the forum.

**Comment by erictleung** [comment]
cc/ @QuincyLarson @BerkeleyTrue

**Comment by lynxlynxlynx** [comment]
Is there anything I can do to speed this along?

**Comment by lynxlynxlynx** [comment]
Still 100% reproducable, now also with FF 52.0.2 and Chromium 57.

**Comment by erictleung** [comment]
@lynxlynxlynx sorry to hear you're still having issues. You can email team@freecodecamp.com for support help. I'll also try to ping Quincy and/or Berkeley again.

**Comment by QuincyLarson** [comment]
@lynxlynxlynx hm... this may be an issue with your account. Are you able to sign in using GitHub?
What about your email address?

**Comment by lynxlynxlynx** [comment]
What is the difference between a sign in and a log in? I can log in to github just fine and on clear (FCC) sessions the initial redirect to github to first login for auth works. The end result is the same though.

My email is also working; are you saying I could try with the same combination that is used for github?

**Comment by lynxlynxlynx** [comment]
I don't know if you did anything, but now I was able to log in. Closing ...

**Comment by QuincyLarson** [comment]
@lynxlynxlynx thanks for confirming this is now working :)
