### ISSUE TITLE
Correct output for Capitalize not being accepted.

### ISSUE THREAD

**Issue by Ashniu123** [freeCodeCamp/freeCodeCamp#14080]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=function%20titleCase(str)%20%7B%0A%20%20%20%20var%20words%20%3D%20str.split('%20')%2C%0A%20%20%20%20%20%20%20%20newWords%20%3D%20%22%22%2C%0A%20%20%20%20%20%20%20%20newWord%20%3D%20%5B%5D%2C%0A%20%20%20%20%20%20%20%20k%20%3D%200%3B%0A%20%20%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20words.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20for%20(var%20j%20%3D%200%3B%20j%20%3C%20words%5Bi%5D.length%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(j%20%3D%3D%3D%200)%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20newWord%5Bk%2B%2B%5D%20%3D%20words%5Bi%5D.charAt(j).toUpperCase()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20else%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20newWord%5Bk%2B%2B%5D%20%3D%20words%5Bi%5D.charAt(j).toLowerCase()%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20k%20%3D%200%3B%0A%20%20%20%20%20%20%20%20newWords%20%3D%20newWords%20%2B%20newWord.join(%22%22)%20%2B%20%22%20%22%3B%0A%20%20%20%20%20%20%20%20newWord%20%3D%20%5B%5D%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20newWords%3B%0A%7D%0A%0AtitleCase(%22I'm%20a%20little%20tea%20pot%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function titleCase(str) {
    var words = str.split(' '),
        newWords = "",
        newWord = [],
        k = 0;
    for (var i = 0; i < words.length; i++) {
        for (var j = 0; j < words[i].length; j++) {
            if (j == 0) newWord[k++] = words[i].charAt(j).toUpperCase();
            else newWord[k++] = words[i].charAt(j).toLowerCase();
        }
        k = 0;
        newWords = newWords + newWord.join("") + " ";
        newWord = [];
    }
    return newWords;
}

console.log(titleCase("HERE IS MY HANDLE HERE IS MY SPOUT"));
console.log(titleCase("sHoRt AnD sToUt"));
console.log(titleCase("I'm a little tea pot"));

```
![image](https://cloud.githubusercontent.com/assets/17933667/24305367/ba2d5564-10e2-11e7-9c66-f9dd6dd8e144.png)

This is exactly how I did it and the output also comes right for all cases but still my answer is not accepted. What did I do wrong?

**Comment by JoolsMcFly** [comment]
Although it looks like your output is correct, it is not! You're adding an extra space at the end of newWords when joining array elements.

Problem is with your code. Please close this issue. Thanks.

Ps: you are over complicating things, think of a simpler solution. :)

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by ParardhaKumar** [comment]
@Ashniu123  Do a simple pop();
