### ISSUE TITLE
Mouse cursor (flashing "I") not staying put when typing code at first

### ISSUE THREAD

**Issue by jjaimelopezz** [freeCodeCamp/freeCodeCamp#14081]
After finishing a challenge and jumping to the next, I find that 9/10 times when I click where I want to start typing my code the cursor (flashing "I"?) doesn't stick to where I want to be. I'll start typing and it'll go a line or two below, which I have to erase, click somewhere else, then finally be able to type where I want.

Anyone else experiencing this??

**Comment by raisedadead** [comment]
Duplicate of #7847
