### ISSUE TITLE
Spelling and grammatical errors

### ISSUE THREAD

**Issue by jpdevpro** [freeCodeCamp/freeCodeCamp#14099]
#### Challenge Name

https://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables

#### Issue Description

In the heading, "Objects" should be "Objects’” (with an apostrophe, i.e. right single quotation mark). And “to lookup” at the end should be “to look up”.

#### Your Code

```js



```

**Comment by JoolsMcFly** [comment]
You're right about the apostrophe but _lookup_ is a valid word.
https://en.oxforddictionaries.com/definition/lookup

I also found occurrences of `it's` being used instead of `its`. A PR is on its way!

**Comment by jpdevpro** [comment]
> You're right about the apostrophe but lookup is a valid word.
> https://en.oxforddictionaries.com/definition/lookup

Yes, it’s a word: a noun. It isn’t a verb. But in the location I cited it’s used as a verb.

**Comment by JoolsMcFly** [comment]
Right, gotcha now. Will change that.
