### ISSUE TITLE
Code mirror position is off by one row

### ISSUE THREAD

**Issue by FTreat** [freeCodeCamp/freeCodeCamp#14092]
Whenever you start a new challenge, the first time you click on the **CodeMirror-code** section the line of code selected is off by one row from the cursor position. Once you start typing it seems to fix itself.

This can be extremely frustrating when you're going through multiple challenges relatively quickly.

**Comment by OFFLlNE** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #7847 , so I am closing it as a duplicate.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
