### ISSUE TITLE
How to stop infinity Loop

### ISSUE THREAD

**Issue by dmkav** [freeCodeCamp/freeCodeCamp#14097]
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Issues is that freeCodeCamp lauch script evry time page are loaded. I don't have time press reset button or clear code.

What I suppose to do?

**Comment by Marmiz** [comment]
Hello @dmkav thanks for reporting this issue.

Can you please tell us which challenge/section are you having this issues?
Does this loop leaves any error message on screen? If so can you please take a screenshot and paste it.
Lastly, can you please open the browser's developer console and see there which kind of error you see?

Thanks for your cooperation.

**Comment by dmkav** [comment]
Hi @marmiz! This is simple Js algorithms, challenge - factorization. I wrote recurcy, but didn't put condition. It doesn't write any mistake in  freecodecamp's console and does not show any error, after few minutes it ask kill or wait process. I can't stop JS launches. 
But I have just realize I could turn off JS and try to clear window code. How do you think?

**Comment by Marmiz** [comment]
By the way you've described the issue @dmkav, seems like you have wrote a broken function causing an infinity loop in the on-line editor.

If this is the case, simply reset the page and try again.
Also from now on please refer to the [official forum](https://forum.freecodecamp.com) or ask for help in one of the [official chat rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

**Comment by dmkav** [comment]
@marmiz, simple I can't reset the page. That's why I wrote here. If it was only about refresh and clear page I wouldn't write here.

**Comment by Marmiz** [comment]
@dmkav In case a simply close and opening the tab again don't work, in chrome you can open the developer console and pause the current function execution in the debugging area.

Then proceed to clean the code.

Regardless I feel that this is not a FCC related issue, since handling loops is the browser's job.

**Comment by erictleung** [comment]
@dmkav sorry to hear you've run into an infinite loop. Please take a look at this forum post on dealing with infinite loops https://forum.freecodecamp.com/t/free-code-camp-infinite-loop-protection/19550. Happy coding!
