### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by paulostradioti** [freeCodeCamp/freeCodeCamp#14094]
Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

When we access the link in the challange https://codepen.io/FreeCodeCamp/full/YqLyXB/ we see a completely different page then it's shown in the video. It seems that someone overwrote the original code?

Which one should we reproduce, the one on the video? The one on the link? None of them (should we create our own)?

Thanks

**Comment by shashank7200** [comment]
@paulostradioti Hey, you can use this link [http://codepen.io/ThiagoFerreir4/full/eNMxEp](http://codepen.io/ThiagoFerreir4/full/eNMxEp) to go to the pen discussed in the video. And for the new version of Portfolio sample you can use this link released in freeCodeCamp Beta [http://codepen.io/freeCodeCamp/full/zNBOYG](http://codepen.io/freeCodeCamp/full/zNBOYG).

Hope this helps!
:crocodile: Shashank Shekhar

**Comment by QuincyLarson** [comment]
@paulostradioti the videos are deprecated and will be soon removed. So I recommend following the CodePen that @shashank7200 mentioned.
