### ISSUE TITLE
"Bonfire: Exact Change" needs additional tests 

### ISSUE THREAD

**Issue by clintoncampbell** [FreeCodeCamp/FreeCodeCamp#1409]
The instinct on this bonfire is to total up all the change in the drawer to determine whether this is greater than the amount required. This will, however, miss the case where you don't have sufficient lower denominations to make change.
```
drawer(17.50, 20.00, [['FIVE', 25.00], ['TEN', 20.00], ['TWENTY', 60.00], ['ONE HUNDRED', 100.00]]);
```
In this case, we have a total of $205.00 available, but we can't make correct change for $2.50. A test should be written to check for a return value of 'Insufficient Funds' in this case.

**Comment by booshay** [comment]
I agree, I notice this today so it's still hasn't been resolved.  I tested one where I was short two pennies... should I just give the customer back a nickel? ha!
