### ISSUE TITLE
Browserify in gulpfile.js

### ISSUE THREAD

**Issue by terakilobyte** [FreeCodeCamp/freecodecamp#141]
I've found the offending code that was causing it not to load. I've no idea why it's throwing the error it is.

It's marked with a TODO

**Comment by BerkeleyTrue** [comment]
Why was watchify removed? Also, without piping it anywhere the gulp file would run but browserify essentially was doing nothing.

**Comment by terakilobyte** [comment]
I did nothing to watchify. Re without the pipe, I actually was just
isolating the bug.

**Comment by terakilobyte** [comment]
Ok, not sure why the watchify was removed, it's added back in.

**Comment by terakilobyte** [comment]
I've narrowed this down to the b.add() call.
