### ISSUE TITLE
Type Error: arr.push is not a function

### ISSUE THREAD

**Issue by shikkaba** [freeCodeCamp/freeCodeCamp#14109]
#### Challenge Name

Stand in Line

#### Issue Description

Getting an error of Type Error: arr.push is not a function when the solution is the same as other solutions.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: OSX 10.11.6
* Mobile, Desktop, or Tablet: Macbook Pro

#### Your Code

This was my code:
```
function nextInLine(arr, item) {
  // Your code here
  arr.push(item);
  return arr.shift();  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(10, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));
```

This code came up as correct:
```
function nextInLine(arr, item) {
  arr.push(item);
  return arr.shift();
}

var testArr = [1,2,3,4,5];

console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));
```

```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by JoolsMcFly** [comment]
You're getting an error call your initial call does not use `testArr` sample code provided but scalar 10:
`console.log(nextInLine(10, 6));`

So code is trying to push 6 to 10 and fails.
Second example you posted uses `testArr` and works.

Next time please ask in forums. Can you close this issue please? Thanks

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

As @JoolsMcFly pointed out ;)

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.

**Comment by shikkaba** [comment]
I was NOT asking for help. I had searched the forums first for answers and there were none. It is not obvious what to change in that question for someone who is new to this. In the instructions on the page, it says to modify the line to test. It does not say that you have to change the code, only to do so if you want to test.

 Is there any way we can change the directions to make this question more clear? I was not the only person to have this issue.

**Comment by JoolsMcFly** [comment]
Hi,

I understand your frustration but there's one skill that's really important in programming is to be able to debug. For that, you need to understand error messages and what to do with them.

Example of what you should train your brain to do when debugging:

What does `arr.push is not a function` tell me? That I am trying to call `push` on a type that has no such function. 
Where does that `arr` comes from? It's an argument of `nextInLine`.
OK, where is `nextInLine` called from then?
Here: `console.log(nextInLine(10, 6)); // Modify this line to test`
Oh! It's trying to do `10.push(6)` then but we can't do that, can we?
OK, if I cannot change the first argument, maybe I can change the second one.
And bang, you have it.

You can also use `debugger` to stop execution of the script and let you investigate, look at variables, their values etc.

So change your code to
```
function nextInLine(arr, item) {
  // Your code here
  debugger;
  return item;  // Change this line
}
```

Open DevTools and run your code.
Your browser should automaticall stop on the `debugger` line. Have fun from there.

Hope this helps.
