### ISSUE TITLE
Code don't work as it supposed to, another server-side Sass->CSS problem.

### ISSUE THREAD

**Issue by Zooll8** [freeCodeCamp/freeCodeCamp#14107]
Challenge [use-for-to-create-a-sass-loop](http://beta.freecodecamp.com/en/challenges/sass/use-for-to-create-a-sass-loop) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36</code>.
To reproduce just copy/paste listed below code and run it on the challenge page.
![image](https://dl.dropboxusercontent.com/s/vebfml7095titml/2017-03-26_18-25-32.png?dl=0)

Here is same code, but on jsfiddle:
![image](https://dl.dropboxusercontent.com/s/5rzhcga8u4s1vcj/2017-03-26_18-28-02.png?dl=0)

```html


<style>
  @for $j from 1 to 6 {
    .text-#{$j} {font-size: 10px * $j}
  }
  
  
</style>

<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>

```

**Comment by HKuz** [comment]
@Zooll8 - this looks like the same root issue you brought up in your other issue (code is fine, but Sass isn't working properly on the Beta site yet). I'm going to close this as similar to #12699 - but hang tight, hopefully we work out a fix soon  👍

**Comment by KoniKodes** [comment]
In CodePen it works with SCSS but not with SASS.
