### ISSUE TITLE
will not turn blue

### ISSUE THREAD

**Issue by ShariefBrown** [freeCodeCamp/freeCodeCamp#14106]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20%3C%2Fstyle%3E%0A%3Ch2%20%7Bcolor%3A%20blue%3B%7D%20%3ECatPhotoApp%3C%2Fh2%3E%20%3C%2Fstyle%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  </style>
<h2 {color: blue;} >CatPhotoApp</h2> </style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Goldolo** [comment]
is for the code is wrong, should be like this
<style>
 h2 {
color:blue;
}
<h2> CatPhotApp</h2>

**Comment by Goldolo** [comment]
`<style>
h2 {
color:blue;
}
<h2> CatPhotoApp </h2>`

**Comment by ShariefBrown** [comment]
still didn't work

**Comment by texas2010** [comment]
@Goldolo 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by texas2010** [comment]
@ShariefBrown 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
