### ISSUE TITLE
please help guys

### ISSUE THREAD

**Issue by virag369** [freeCodeCamp/freeCodeCamp#14101]
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=function%20myFunction()%20%7B%0A%20%20%0Avar%20myVar%20%3D%20%22strict%22%3B%0Aconsole.log(myVar)%3B%0A%0A%7D%0A%0AmyFunction()%3B%0A%2F%2F%20Now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0Aconsole.log(myVar)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myFunction() {
  
var myVar = "strict";
console.log(myVar);

}

myFunction();
// Now remove the console log line to pass the test
console.log(myVar);

```

**Comment by Dayfiri** [comment]
Can you elaborate what you exactly have problem with ?
The assignment asks you to remove the last line in your code and you're good to go.
As the @VarCI-bot said, this is for reporting bugs only. For any help check the links above me, in bot reply.

**Comment by texas2010** [comment]
@virag369 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
