### ISSUE TITLE
Practice Functional Programming waypoint needs serious attention

### ISSUE THREAD

**Issue by webdevjeffus** [FreeCodeCamp/freecodecamp#1410]
I desperately hope that the external tutorial for functional programming (http://jhusain.github.io/learnrx/) will be replaced by a module designed and created in-house. The Husain tutorial is completely overwhelming for programming novices, and is much less friendly and accessible than the modules that precede it. My frustration with it drove me away from FCC for two full weeks, and came close to making me quit the program entirely, despite having been happy and successful with the program up to that point. Here are my thoughts on how this situation could be improved.

1. Break it up into several waypoints on the map.
The tutorial is broken up into several sections of 5-10 exercises each ("Working with Arrays", "Filtering Arrays", "Querying Trees", "Reducing Arrays", etc.). Each of these sections should be listed as a separate waypoint on the FCC map, so that learners will have some sense of progress and accomplishment on the way to completing all 42 exercises. I've worked two full, frustrating days (16 hours or more in total) on this tutorial, and haven't been able to click a single waypoint on the FCC map. This is very discouraging, especially considering that in previous modules, I was knocking off several waypoints a day.

2. Try to get Husain to fix known bugs with the exercises and tests.
There is at least one other open issue about the problems with Husain's custom .concatAll(), which apparently doesn't pass his own tests in some browsers or on some systems. I won't dwell on this issue, except to say that when you're already struggling, it's very discouraging to discover that even the solutions provided by the author of the tutorial don't pass the tutorial's verification tests.

3. Replace this module with an in-house module with lots more explanation and (especially) examples.
I'm sure that this tutorial makes sense to someone who already understands functional programming, and presents the material in an order that seems logical to such a person. But as a learner for whom this is the most advanced and challenging topic I've encountered so far in learning to program, I find this tutorial almost impossible to follow. The sequence of the topics may make sense, but the explanations are brief, and in most cases, no examples are provided at all, aside from the correct solution. In most cases, I had no choice but to make my best (but incomplete or incorrect) guess at a solution, then look at the correct answer and attempt to reverse-engineer it to understand it. Then the tutorial would move on to the next concept, without providing any additional examples or illustrations.

There is a much better (clearer, more practical, and more accessible) tutorial on functional programming, from tuts+ and available on YouTube (https://www.youtube.com/watch?v=ubueiy6kVUg). I am not qualified to judge whether this tutorial teaches everything you want your functional programming module to teach, nor can I say whether there is a good way to include and verify the completion of a series of YouTube videos in your curriculum, but I can say, as a novice programmer, that the tuts+ videos by Jason Rhodes taught me more in a couple of hours than I learned in two days of banging my head against the Husain tutorial. You might consider using the tuts+ videos as an introduction to the topic, and then follow it up with some bonfires to provide practice with functional programming.

Where I am now:
I've gotten to the early portions of the Observables section of the Husain tutorial, and found that on exercise 32, there was no button to show the correct solution. In frustration and desperation, I eventually clicked the Show All Answers button at the top of the page -- which obliterated all my work in the previous exercises, as well as clearing the template code in several of the later exercises. I suppose I could reset my progress on the entire tutorial and begin again, but the process has been so painful and felt so unproductive that I can't see repeating it.

If passing this particular functional programming tutorial is really essential to moving on in the program, then it borders on a complete roadblock for myself and other participants like myself, with only limited prior experience. I'll try to find other resources to learn these concepts, and then come back to FCC's map, but I fear that other learners might be stopped by this tutorial and never return. I don't know what follows this tutorial in the program, but in comparison to what preceded it -- both outside resources and FCC-created modules -- it is not nearly as effective.

**Comment by abbynormative** [comment]
Thank you. I'm also finding this waypoint frustrating and buggy.

**Comment by ltegman** [comment]
I completely agree with all these critiques. I learned more about functional programming just messing around with lodash for a couple hours than dealing with the frustration of this tutorial. Thankfully no functional programming is required after that point, so it can effectively be skipped, but I would highly recommend doing what you did and looking for other resources on functional programming since it is really powerful and can definitely simplify your work on some later challenges.

**Comment by dcsan** [comment]
good points, but i think the FCC style is more interactive than tuts+ videos. 
original content would be better. lodash/underscore walkthrough is a great idea, tho its an external library its pretty much essential and FCC does cover jquery anway.

**Comment by dcsan** [comment]
are there any other good JS func programming interactive tuts out there? i'd really like to try some myself.

**Comment by benmcmahon100** [comment]
This can be done but it will not be in the next deploy to the main site as it hasn't even been started. That said once the beta is deployed i think this is a common and annoying enough issue to warrant it being the next set of Challenges to be made in house ones as the tutorials that are currently in use have always been unpopular.

**Comment by ahstro** [comment]
@Greenheart introduced me to a quite new YouTuber that is currently creating a video series on functional programming in JavaScript which, so far, I have found to be great. So far, there are videos on higher-order functions, .map(), .reduce() and closures, but new videos seem to be added every week.
I think this video series could be a great addition to a revised functional programming section, maybe coupling each video with some bonfiresque challenge where the material discussed in the video is used to solve a problem.
I have not checked the license of the videos, so I'm not sure we can use them, but I'm sure a quick tweet to [the author](https://twitter.com/mpjme) would fix that.
The video series can be found [here](https://www.youtube.com/playlist?list=PL0zVEGEvSaeEd9hlmCXrk5yUyqUag-n84) for those interested.

**Comment by Greenheart** [comment]
@webdevjeffus Very well put critique! I definitely agree.

Like @ahstro wrote, those functional programming tutorials cover some of the most useful methods, but isn't yet a complete tutorial on the topic. However I think that the creator just has gotten started with his series so he migh be interested in continuing the series and at the same time make a big and important contribution to our community!

Now, let's contact him and try to convince him to help us with course material for a functional programming!

**Comment by dcsan** [comment]
@benmcmahon100 how would you plan to test the functional original content?

my understanding of the test runner you have is that it's just checking the results. if someone wrote code with a for loop vs using Array.filter() there's  no way the current setup could tell this, unless we do much deeper code analysis?

**Comment by ahstro** [comment]
@dcsan The test cases could look for the presence of for loops with something like `editor.match(/^for\s*(/)`, but I suppose there has to be some level of trust, as with every challenge.

**Comment by dcsan** [comment]
yeah regex is one way, we could also even use something like these AST parser projects for a more lexical analysis:
http://esprima.org/demo/validate.html
http://jointjs.com/demos/javascript-ast

**Comment by ahstro** [comment]
The regex method I mentioned above is how things that can't be caught with regular test cases gets checked right now, but I guess those AST parser projects are valid ways as well, probably a bit more reliable as well, but I'm not sure how they'd be integrated with the current test system.

**Comment by benmcmahon100** [comment]
An update on this. Jhussain's material will be replaced soon. I'm currently starting to make the challenges that will eventually replaced his stuff. @dcsan with regards to the issue you have pointed out what @ahstro said is 100% correct we have always used RegEx to stop people cheating at challenges that said that only makes them harder to cheat but in no way impossible. In fact if someone wanted and they were familiar with the code base they could potentially find a way to pass all the tests without writing any code. That said if someone is caught cheating to get past challenges that aren't broken this will porpoise their placement on the non-profit projects. Even if they did get on a project it should become clear that they aren't up to standard it will be clear they cheated. At any rate I'm sure people will be happy to know that these challenges will be phased out in the near to mid future

**Comment by ahstro** [comment]
>near to mid future

Soon™

Looking forward to the new ones. :)
