### ISSUE TITLE
this is BUG

### ISSUE THREAD

**Issue by virag369** [freeCodeCamp/freeCodeCamp#14111]
Challenge [Selecting from many options with Switch Statements](https://www.freecodecamp.com/challenges/selecting-from-many-options-with-switch-statements#?solution=%0Afunction%20caseInSwitch(val)%20%7B%0A%20%20var%20answer%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20%0A%20%20switch%20(val)%20%7B%0A%20%20case%201%3A%0A%20%20%20%20console.log('alpha')%3B%0A%20%20%20%20break%3B%0A%20%20case%202%3A%0A%20%20%20%20console.log('beta')%3B%0A%20%20%20%20break%3B%0A%20%20case%203%3A%0A%20%20%20%20console.log('gamma')%3B%0A%20%20%20%20break%3B%0A%20%20case%204%3A%0A%20%20%20%20console.log('delta')%3B%0A%20%20%20%20break%3B%0A%20%0A%20%20default%3A%0A%20%20%20%20console.log('Sorry%2C%20we%20are%20out%20of%20'%20%2B%20val%20%2B%20'.')%3B%0A%7D%0A%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%20%20%0A%20%20return%20answer%3B%20%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AcaseInSwitch(1)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function caseInSwitch(val) {
  var answer = "";
  // Only change code below this line
  
  
  switch (val) {
  case 1:
    console.log('alpha');
    break;
  case 2:
    console.log('beta');
    break;
  case 3:
    console.log('gamma');
    break;
  case 4:
    console.log('delta');
    break;
 
  default:
    console.log('Sorry, we are out of ' + val + '.');
}
 
  // Only change code above this line  
  return answer;  
}

// Change this value to test
caseInSwitch(1);


```

**Comment by texas2010** [comment]
@virag369 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
