### ISSUE TITLE
Build a Tribute Page - no user stories shown

### ISSUE THREAD

**Issue by MMAgeek** [freeCodeCamp/freeCodeCamp#14114]
Challenge [build-a-tribute-page](http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.

The text in the challenge says "Fulfill the user stories by getting all of the tests to pass. Use whichever libraries you need. Give it your own personal style."

However there are no user stories listed? Should these not be shown on the page?

**Comment by Marmiz** [comment]
Looks like the user stories were left behind.
We can simply look at the live version and add them back.

@MMAgeek fancy taking care of this issue? It should be an easy first-time contributing 👍

**Comment by mitron6** [comment]
For the moment, you need to make sure you are using the Chrome browse. Then you clone the CodePen using the link in the instructions for the challenge. You should see a yellow box. Using the drop down under "Select Test Suite" choose "Tribute Page." Then click Run Tests.  Next click the Tests button and you will see all the failing tests. You can use these tests to guide your solution to this challenge.

THIS IS NOT AT ALL OBVIOUS.

We at least need to give our students some sort of instructions like the above to see what the need to do.

**Comment by alarsyo** [comment]
The embedded YouTube vid doesn't work. Is this where we should be seeing the user stories ?
