### ISSUE TITLE
Test user did not replace const keyword

### ISSUE THREAD

**Issue by jamesbcn** [freeCodeCamp/freeCodeCamp#14118]
Challenge [mutate-an-array-declared-with-const](http://beta.freecodecamp.com/en/challenges/es6/mutate-an-array-declared-with-const) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


let s = [ 5, 7, 2 ];
// change code below this line
s = [2, 5, 7];
// change code above this line
// Test your code
console.log(s);

```

I replaced const with let and passed the test...

**Comment by JoolsMcFly** [comment]
Yep, assertions are not implemented. I'll see what I can do.
