### ISSUE TITLE
Enable deletion of solutions from Portfolio

### ISSUE THREAD

**Issue by clintoncampbell** [FreeCodeCamp/FreeCodeCamp#1411]
I've completed a couple of Bonfire's successfully and realized there was an issue that floated past the test. I'd love to be able to remove these solutions from my portfolio page.

**Comment by kurzninja** [comment]
+1

**Comment by benschenker** [comment]
Thanks for the suggestion!

This is a duplicate of #1342, keep track of that for updates on this request.
