### ISSUE TITLE
Challenge #26: Link to External Pages with Anchor Elements. CatPhotoApp "a" tag issue.

### ISSUE THREAD

**Issue by fcobo95** [freeCodeCamp/freeCodeCamp#14119]
#### Challenge Name: Link to External Pages with Anchor Elements

https://www.freecodecamp.com/challenges/link-to-external-pages-with-anchor-elements#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3E%3Ca%20href%3D%22http%3A%2F%2Ffreecatphotoapp.com%22%3ECatPhotoApp%3C%2Fa%3E%3C%2Fh2%3E%0A%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A%0A

#### Issue Description
If you put an "a" tag or anchor tag in the CatPhotoApp and the press it, you are unable to submit your results. Whenever you click the "Run tests" button, it will just sit there, not being able to do or submit anything. 

#### Browser Information
I am working with the current online text editor provided by FreeCodeCamp

* Browser Name, Version: Google Chrome v.56.0.2924.87 (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: None

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/17036338/24374904/c6132918-12f3-11e7-9a8b-11c2d6e457b4.png)

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code on the screenshot is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding.
