### ISSUE TITLE
Test condition is marked correct with no ".target"

### ISSUE THREAD

**Issue by dongreer** [freeCodeCamp/freeCodeCamp#14129]
The test condition with no ".target" is accepted as correct.

#### Challenge Name

Target a Specific Child of an Element Using jQuery

#### Issue Description

If you leave off the ".target" portion of the jQuery statement, you pass the challenge, even though it's incorrect.  Specifically, condition 1 of the list of conditions is not met but you pass anyway.

#### Browser Information

* Browser Name, Version:  Chrome  57.0.2987.98
* Operating System: Windows 10
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code

```js

$(":nth-child(2)").addClass("animated bounce");

```

**Comment by techstonia** [comment]
I'll take a look into it. ;-)

**Comment by D3V4N5H** [comment]
That happened with me too. Thanks for posting this, so I could go ahead

I used id selectors #left-well and #right-well but it didn't work
Then i tried class selectors .well

but only .target worked
it is not intuitive to understand the the work 'target' is a placeholder for a selector and not a keyword

ALSO PLEASE GIVE AN EXAMPLE IN THE EXPLANATION
