### ISSUE TITLE
Setting Different Margins Bug

### ISSUE THREAD

**Issue by Silverjayw** [freeCodeCamp/freeCodeCamp#14124]
I had an issue with the free code camp mission above for a bit resetting my code worked to fix it but every time i load the page the first time that mission wont let me put in more than 3 sides of the margin.  It didnt stop me from finishing it but i just wanted to report the bug.

**Comment by erictleung** [comment]
@Silverjayw thanks for the issue. Can you give us more information about the challenge you've talking about? It isn't clear from the post above what challenge you're referring to.
