### ISSUE TITLE
opening the chrome in Emulator 

### ISSUE THREAD

**Issue by manishtiwary8987** [FreeCodeCamp/FreeCodeCamp#1412]
i have installed the chrome and firefox in the Emulator . But both are crashed after opening.please provide me appropriate solution.also provide the code for invoking chrome in eclipse .

**Comment by manishtiwary8987** [comment]
please respond quickly. it's urgent.

**Comment by royshouvik** [comment]
@manishtiwary8987 Can you please describe your problem in more detail. Also, please attach snapshot/code snippets on the issue. Thanks.

**Comment by benschenker** [comment]
Closing this as stale, Please reopen if you still have this issue
