### ISSUE TITLE
 Get Geolocation Data

### ISSUE THREAD

**Issue by sylarxinxu** [freeCodeCamp/freeCodeCamp#14122]
Challenge [Get Geolocation Data](https://www.freecodecamp.com/challenges/get-geolocation-data#?solution=%0Afccss%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20if%20(navigator.geolocation)%20%7B%0Anavigator.geolocation.getCurrentPosition(function(position)%20%7B%0A%24(%22%23data%22).html(%22latitude%3A%20%22%20%2B%20position.coords.latitude%20%2B%20%22%3Cbr%3Elongitude%3A%20%22%20%2B%20position.coords.longitude)%3B%0A%7D)%3B%0A%7D%0A%20%20%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0Afcces%0A%3Ch4%3EYou%20are%20here%3A%3C%2Fh4%3E%0A%3Cdiv%20id%20%3D%20%22data%22%3E%0A%20%20%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  // Only change code below this line.
  if (navigator.geolocation) {
navigator.geolocation.getCurrentPosition(function(position) {
$("#data").html("latitude: " + position.coords.latitude + "<br>longitude: " + position.coords.longitude);
});
}
  
  
  // Only change code above this line.
</script>
<h4>You are here:</h4>
<div id = "data">
  
</div>

```
There is nothing when i run the test 
Is there any other ways to get latitude and longitude?

**Comment by dhcodes** [comment]
@sylarxinxu You would need to allow the browser to use your location to see an output. As for other ways, ask in the Help Chat room. There are sure to be others to foster the discussion there.
