### ISSUE TITLE
Can't advance to the next task

### ISSUE THREAD

**Issue by scriptingbear** [freeCodeCamp/freeCodeCamp#14137]
Challenge [Compound Assignment With Augmented Subtraction](https://www.freecodecamp.com/challenges/compound-assignment-with-augmented-subtraction#?solution=%0Avar%20a%20%3D%2011%3B%0Avar%20b%20%3D%209%3B%0Avar%20c%20%3D%203%3B%0A%0A%2F%2F%20Only%20modify%20code%20below%20this%20line%0A%0Aa%20-%3D%206%3B%0Ab%20-%3D%2015%3B%0Ac%20-%3D%201%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var a = 11;
var b = 9;
var c = 3;

// Only modify code below this line

a -= 6;
b -= 15;
c -= 1;



```
I am getting the following error:

Error 504 Ray ID: 346d5b5b486c716d • 2017-03-28 20:32:06 UTC

**Comment by scriptingbear** [comment]
I refreshed the page and am now able to continue to the next task

**Comment by systimotic** [comment]
@scriptingbear I'm glad you figured it out, I was just about to ask you to do that 😄
Happy coding!
