### ISSUE TITLE
Typo in challenge description

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#14132]
Challenge [storing-values-with-the-assignment-operator](http://localhost:3000/en/challenges/basic-javascript/storing-values-with-the-assignment-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This is located in the seeds/challenges directory.

![](https://www.evernote.com/l/Ar_2sktrQKdLw6vUE0fsb_cvSCUKRIn5n0wB/image.png)

**Comment by mbrien12** [comment]
I'm taking a look at this one 👍
