### ISSUE TITLE
optional semi colon 

### ISSUE THREAD

**Issue by juanpastas** [FreeCodeCamp/FreeCodeCamp#1414]
Could you put semi colon as optional in editor?

A lot of people like that:

https://github.com/feross/standard
https://www.youtube.com/watch?v=gsfbh17Ax9I
http://inimino.org/~inimino/blog/javascript_semicolons
http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding

**Comment by awesomeaniruddh** [comment]
@FreeCodeCamp/owners Any thoughts on this?

**Comment by BerkeleyTrue** [comment]
semicolons will always be required. It is always better to be explicit than to be implicit and leave it up to the next coder to interpret. Happy Coding.
