### ISSUE TITLE
understanding-case-sensitivity-in-variables

### ISSUE THREAD

**Issue by hasmukhgagal** [freeCodeCamp/freeCodeCamp#14144]
Challenge [Understanding Case Sensitivity in Variables](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables#?

 properCamelCase should use camelCase in both declaration and assignment sections.
 has an issue.

User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:50.0) Gecko/20100101 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Declarations
var studlyCapvar;
var properCamelCase;
var TitleCaseOver;

// Assignments
studlyCapVar = 10;
properCamelCase = "A String";
titleCaseOver = 9000;


var studlyCapvar;
var properCamelCase;
var TitleCaseOver;


studlyCapVar = 10;
properCamelCase = "A String";
titleCaseOver = 9000;


```
so what i do?

**Comment by OFFLlNE** [comment]
Thank you for reporting your issue.

Your code is wrong.
This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "Help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Thank you, and happy coding

**Comment by hasmukhgagal** [comment]
Challenge [Understanding Case Sensitivity in Variables](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables#?

properCamelCase should use camelCase in both declaration and assignment sections.
has an issue.

User Agent is: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:50.0) Gecko/20100101 Firefox/50.0.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

// Declarations
var StUdLyCapVaR;
var properCamelCase;
var TitleCaseOver;

// Assignments
STUDLYCAPVAR = 10;
PRoperCAmelCAse = "A String";
tITLEcASEoVER = 9000;


var studlyCapVar;
var properCamelCase;
var titleCaseOver;


studlyCapVar = 10;
properCamelCase = "A String";
titleCaseOver = 9000;
  
how can i solve this

**Comment by apealunited** [comment]
Solution:

// Declarations
var StUdLyCapVaR;
var properCamelCase;
var TitleCaseOver;

// Assignments
STUDLYCAPVAR = 10;
properCamelCase = "A String";
tITLEcASEoVER = 9000;

var studlyCapVar;
var propercamelCase;
var titleCaseOver;

studlyCapVar = 10;
propercamelCase = "A String";
titleCaseOver = 9000;

**Comment by baiqpratiwi** [comment]
solution:

// Declarations
var studlyCapVar;
var properCamelCase;
var titleCaseOver;

// Assignments
studlyCapVar = 10;
properCamelCase = "A String";
titleCaseOver = 9000;

**Comment by marquise1345** [comment]
I tried both of those and none of them worked

**Comment by RandellDawson** [comment]
@marquise1345 I suggest using the `Ask for Help` button located on the challenge, which will create a forum topic with your specific code, so that someone can help you with your code.

**Comment by SainiKhushi** [comment]
I do have the same problem
My code is:
// Variable declarations
var StUdLyCapVaR;
var properCamelCase;
var TitleCaseOver;

// Variable assignments
StUdLycapVaR = 10;
properCamelCase = "A String";
TitleCaseOver = 9000;

what should I do?

**Comment by SainiKhushi** [comment]
Answer to this challenge:
// Variable declarations
var StUdLyCapVaR;
var properCamelCase;
var TitleCaseOver;

// Variable assignments
STUDLYCAPVAR = 10;
PRoperCAmelCAse = "A String";
tITLEcASEoVER = 9000;

**Comment by SainiKhushi** [comment]
answer to this challenge:
// Variable declarations
var studlyCapVar ;
var properCamelCase ;
var titleCaseOver ;

// Variable assignments
studlyCapVar  = 10;
properCamelCase  = "A String";
titleCaseOver  = 9000;
