### ISSUE TITLE
Beta D3 challenges

### ISSUE THREAD

**Issue by rudolphh** [freeCodeCamp/freeCodeCamp#14154]
Challenge [change-styles-based-on-data](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/change-styles-based-on-data) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

It isn't the particular challenge but more so with how these challenges' tests evaluate the solutions. If you change the name of the variable, in this case dataset, to anything else (that you haven't already used in previous d3 challenges) the solution works. 

Even if you go back to the previous challenge (that passed), and submit again, it will respond that the variable has already been declared.  I had the same issue with mobile on android 6.0 using chrome 56.  

```html


<body>
  <script>
    const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
    
    d3.select("body").selectAll("h2")
      .data(dataset)
      .enter()
      .append("h2")
      .text((d) => (d + " USD"))
      // Add your code below this line
      
      
      
      // Add your code above this line
  </script>
</body>

```

**Comment by HKuz** [comment]
@rudolphh thanks for raising this issue, you're right there's a problem with the tests running the code with the same `const` variable each challenge. There's more detail over in issue #13936 and the underlying problem noted in issue #12762. I'm going to mark this as a duplicate, but feel free to join in the conversation on either of those issues. Thanks!
