### ISSUE TITLE
Prioritize One style over another

### ISSUE THREAD

**Issue by kidposeidon** [freeCodeCamp/freeCodeCamp#14156]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text{color: Pink;}
</style>
<h1 class="pink-text">Hello World!</h1>

```
The three things are
1. H1 element should be Pink-text (done)
2.Your <style> should have a pink-text CSS class with its color set to pink. (?)
3. Your h1 element should be pink (done)

Sorry if I'm wasting your time I'm new to HTML. Please tell me whats wrong!

**Comment by texas2010** [comment]
Thanks for reporting this. But you got typo.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
