### ISSUE TITLE
Misleading instructions in Learn how a Stack Works

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/freeCodeCamp#14163]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/learn-how-a-stack-works

#### Issue Description

A Stack is a Last-In-First-Out data structure, so the most recent item inserted would be at the top, while the first item would be at the very end. In the challenge, the "stack" is setup this way - 
`var homeworkStack = ["BIO12","HIS80","MAT122","PSY44"];`

The top of the stack is `PSY44`, as is also stated in the description - 
> Here we have a stack of homework assignments represented as an array: "BIO12" is at the base, and "PSY44" is at the top of the stack.

However, the instructions seem to indicate that element `BI012` is the top - 
> Modify the given array and treat it like a stack using the JavaScript methods mentioned above. Remove the top element "BIO12" from the stack. Then add "CS50" to be the new top element of the stack.

If you run `pop()` on the array, similar to a stack's `pop()` operation, the element at the end `PSY44` is removed, not `BI012` - 

![2](https://cloud.githubusercontent.com/assets/11348778/24531909/74442210-158a-11e7-8c02-bf33c5093010.png)

#### Browser Information

* Browser Name, Version: Chrome, 56
* Operating System: Windows
* Mobile, Desktop, or Tablet: Desktop

<hr>

I'll make a quick PR to fix this.

**Comment by Ethan-Arrowood** [comment]
@Manish-Giri glad to see I'm not the only one working on these. Check out this issue https://github.com/freeCodeCamp/freeCodeCamp/issues/12757 its kinda the hub for reviewing the advanced data structures and algorithms section.
