### ISSUE TITLE
Stand in Line - really challenging.

### ISSUE THREAD

**Issue by haydennorthcott** [freeCodeCamp/freeCodeCamp#14168]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20%0A%20%20%0Aarr.push(item)%3B%0Avar%20nextInLine%20%3D%20arr.shift()%3B%20%0A%20%20return%20nextInLine%3B%0A%20%20%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%206))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function nextInLine(arr, item) {
  // Your code here
  
  
arr.push(item);
var nextInLine = arr.shift(); 
  return nextInLine;
    // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

I believe that this challenge may need some additional steps to explain more of what to do, or explain it a bit better. Another option would be to have some other challenges before this one to help not make this challenge such a big step up. I've really struggled with this one.

**Comment by hassangamal** [comment]
var item = arr.shift(); 
return item;

**Comment by whebz** [comment]
why arr.splice(0,1); fails in this challenge?

**Comment by bazita** [comment]
yes  toke my an hour. to find out

**Comment by PatrickMoumiet** [comment]
It is pretty simple in fact, but the exercise do not specify enough the details, i did right on the logic ( the function worked) but it was not the good name ( next Inline) i created a var ( lastvar) for assigned the value taken by , .shift .  They should explain better that we have to use the same name for the global function and the arguments of the local function too.
