### ISSUE TITLE
Waypoint: Manage Packages with NPM checklist error

### ISSUE THREAD

**Issue by Damon-Myers** [FreeCodeCamp/FreeCodeCamp#1416]
Challenge http://www.freecodecamp.com/challenges/waypoint-manage-packages-with-npm has an issue. 

This waypoint should be updated to match cloud9's updates, however, there is a legitimate issue that could confuse a beginner on item 12. The command listed in item 12 should be changed to 'how-to-npm' in order to run the tutorial program.

**Comment by benschenker** [comment]
Hey @Damon-Myers thanks for posting.

Your first issue is a duplicate of #1318, keep an eye there for updates.

Your second issue seems to have been fixed
