### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by barkinet** [freeCodeCamp/freeCodeCamp#14179]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%7Bcolor%3Ared%3B%7D%0A%20%20p%7Bfont-size%3A16x%3B%7D%0A%3C%2Fstyle%3E%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20snip%20the%20couch%20scratched%20sunbathe%2C%20she%20everywhere%20rip%20the%20couche%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text{color:red;}
  p{font-size:16x;}
</style>
<h2 class="red-text">CatPhotoApp</h2>
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass snip the couch scratched sunbathe, she everywhere rip the couche sleep in the sink fluffy fur catnip scratched.</p>

``<style>
2
  .red-text{color:red;}
3
  p{font-size:16x;}
4
</style>
5
<h2 class="red-text">CatPhotoApp</h2>
6
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
7
<p>Purr jump eat the grass snip the couch scratched sunbathe, she everywhere rip the couche sleep in the sink fluffy fur catnip scratched.</p>`

**Comment by barkinet** [comment]
`<style>
2
  .red-text{color:red;}
3
  p{font-size:16x;}
4
</style>
5
<h2 class="red-text">CatPhotoApp</h2>
6
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
7
<p>Purr jump eat the grass snip the couch scratched sunbathe, she everywhere rip the couche sleep in the sink fluffy fur catnip scratched.</p>![img_2278](https://cloud.githubusercontent.com/assets/2127162/24563279/afcbf4c8-1645-11e7-80de-70e71451f433.PNG)`
![img_2279](https://cloud.githubusercontent.com/assets/2127162/24563281/b020c2b4-1645-11e7-9bd3-33572a2615fc.PNG)

**Comment by barkinet** [comment]
![img_2278](https://cloud.githubusercontent.com/assets/2127162/24563329/d963b924-1645-11e7-9b88-b3becfbddd67.PNG)
![img_2279](https://cloud.githubusercontent.com/assets/2127162/24563332/db4471b6-1645-11e7-98e3-ad5eb23ca7ab.PNG)

**Comment by texas2010** [comment]
@barkinet 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
