### ISSUE TITLE
Incorrect Hex code for Dodger Blue

### ISSUE THREAD

**Issue by UnwireMe** [freeCodeCamp/freeCodeCamp#14174]
#

#### Challenge Name

https://www.freecodecamp.com/challenges/use-hex-code-to-mix-colors

#### Issue Description

Hex color listed for Dodger Blue is currently listed is 2998E4.

Hex code for true Dodger Blue is 1E90FF.

#### Browser Information

* Browser Name, Version: Chrome 57
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

**Comment by erictleung** [comment]
@UnwireMe this has been fixed in the [beta site](http://beta.freecodecamp.com/en/challenges/basic-css/use-hex-code-to-mix-colors). For now, please use the code in the table to complete the challenge. Happy coding!
