### ISSUE TITLE
Caesars Cipher bug

### ISSUE THREAD

**Issue by mateuszk969** [freeCodeCamp/freeCodeCamp#14172]
Challenge [Caesars Cipher](https://www.freecodecamp.com/challenges/caesars-cipher#?solution=%0Afunction%20rot13(str)%20%7B%20%2F%2F%20LBH%20QVQ%20VG!%0A%20%20var%20a%3Dstr.split(%22%22)%3B%0A%20%20var%20v%3D%5B%5D%3B%0A%20%20for(i%3D0%3Bi%3Ca.length%3Bi%2B%2B)%7B%0A%20v.push(a%5Bi%5D.charCodeAt())%3B%0A%20%20if(v%5Bi%5D%3E64%20%26%26%20v%5Bi%5D%3C78)%7B%0A%20%20%20%20v%5Bi%5D%2B%3D13%3B%0A%20%20%7D%0A%20%20%20%20else%20if%20(v%5Bi%5D%3E77%20%26%26%20v%5Bi%5D%3C90)%7B%0A%20%20%20%20%20%20v%5Bi%5D-%3D13%3B%0A%20%20%20%20%7D%0A%20%20%20%20else%7B%0A%20%20%20%20%20%20v%5Bi%5D%3Da%5Bi%5D%3B%0A%20%20%20%20%7D%0A%20%20%20%20%20%0A%20%20%7D%0A%20%20for(j%3D0%3Bj%3Cv.length%3Bj%2B%2B)%7B%0A%20%20%20%20if(!isNaN(v%5Bj%5D))%7B%0A%20%20%20v%5Bj%5D%3DString.fromCharCode(v%5Bj%5D)%3B%7D%0A%20%20%7D%0A%20%20return%20v%3B%0A%20%20%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%0Arot13(%22SERR%20CVMMN!%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function rot13(str) { // LBH QVQ VG!
  var a=str.split("");
  var v=[];
  for(i=0;i<a.length;i++){
 v.push(a[i].charCodeAt());
  if(v[i]>64 && v[i]<78){
    v[i]+=13;
  }
    else if (v[i]>77 && v[i]<90){
      v[i]-=13;
    }
    else{
      v[i]=a[i];
    }
     
  }
  for(j=0;j<v.length;j++){
    if(!isNaN(v[j])){
   v[j]=String.fromCharCode(v[j]);}
  }
  return v;
  }

// Change the inputs below to test
rot13("SERR CVMMN!");

```

**Comment by AllanJeremy** [comment]
I agree, my code decodes correctly as well but I cannot complete the challenge either. Any luck @mateuszk969 ?

```
var OFFSET = 13;
var A_VAL = 65;
var Z_VAL = 90;

function rot13(str) { // LBH QVQ VG!
  
   str = str.split("").map(function(char){
    var newVal = char.charCodeAt(0);
    //If the character is a valid character between A-Z
    if(char.charCodeAt(0)>=A_VAL && char.charCodeAt(0)<=Z_VAL)
    {
       newVal = char.charCodeAt(0)+OFFSET;
       if(newVal>Z_VAL)
       {
         newVal = char.charCodeAt(0)-OFFSET;
       }
    } 
    return String.fromCharCode(newVal);
  }).join("");
  
  return str;
}

// Change the inputs below to test
rot13("GUR DHVPX OEBJA QBT WHZCRQ BIRE GUR YNML SBK.");

```
