### ISSUE TITLE
 is this a bug? notice "--> in the simulator.."

### ISSUE THREAD

**Issue by abe312** [freeCodeCamp/freeCodeCamp#14173]
![screen shot 2017-03-31 at 8 26 57 pm](https://cloud.githubusercontent.com/assets/7970296/24556170/2565a340-1651-11e7-8832-852e3a8b24c0.png)

Challenge [Specify How Fonts Should Degrade](https://www.freecodecamp.com/challenges/specify-how-fonts-should-degrade) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--><link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
-->

<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by erictleung** [comment]
@abe312 thanks for the issue. The `-->` is from your comment. Your code didn't start the comment correctly so the ending of the comment got shown. You have an extra `>` at the beginning of your comment. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
