### ISSUE TITLE
regexp might not bo working

### ISSUE THREAD

**Issue by eugenioclrc** [FreeCodeCamp/freecodecamp#1417]
Try to resolve this http://www.freecodecamp.com/challenges/bonfire-confirm-the-ending

With this code;
```javascript
function end(str, target) {
  return RegExp(str + '$', '').test(str);
}

```

**Comment by LouisMilotte** [comment]
It doesn't appear that the exercise is asking you to use regular expression. While that certainly *should* work it could be the case that the program is requiring the use of its suggested Javascript function. However, when using the suggested function I'm still receiving a "Red X" and a err != null message from the console.

```javascript
function end(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  if(str.substr(-Math.abs(target.length)) == target){
    console.log(true);
  }else{
    console.log(false);
  }
}

end('Bastian', 'n');

````

**Comment by royshouvik** [comment]
@eugenioclrc I hope you meant 
```
function end(str, target) {
  return RegExp(target+ '$', '').test(str);
}
```

**Comment by royshouvik** [comment]
@LouisMilotte I hope you meant 
```
function end(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
  if(str.substr(-1) === target){
    return true;
  }else{
    return false;
  }
}

end('Bastian', 'n');
```

**Comment by eugenioclrc** [comment]
My bad... it was a typo in my function.

Thanks @royshouvik
