### ISSUE TITLE
Font size p element 

### ISSUE THREAD

**Issue by barkinet** [freeCodeCamp/freeCodeCamp#14177]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by barkinet** [comment]
![img_2278](https://cloud.githubusercontent.com/assets/2127162/24562525/f32dc104-1642-11e7-946a-bd8fd8d84e10.PNG)
![img_2279](https://cloud.githubusercontent.com/assets/2127162/24562527/f3991e18-1642-11e7-805e-c511f5545156.PNG)

**Comment by barkinet** [comment]
`<style>
2
  .red-text{color:red;}
3
  p{font-size:16x;}
4
</style>
5
<h2 class="red-text">CatPhotoApp</h2>
6
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
7
<p>Purr jump eat the grass snip the couch scratched sunbathe, she everywhere rip the couche sleep in the sink fluffy fur catnip scratched.</p>`

**Comment by texas2010** [comment]
@barkinet 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by barkinet** [comment]
Thank you
