### ISSUE TITLE
condition check won't work

### ISSUE THREAD

**Issue by Moringer** [freeCodeCamp/freeCodeCamp#14187]
Challenge [Accessing Nested Objects](https://www.freecodecamp.com/challenges/accessing-nested-objects#?solution=%0A%2F%2F%20Setup%0Avar%20myStorage%20%3D%20%7B%0A%20%20%22car%22%3A%20%7B%0A%20%20%20%20%22inside%22%3A%20%7B%0A%20%20%20%20%20%20%22glove%20box%22%3A%20%22maps%22%2C%0A%20%20%20%20%20%20%22passenger%20seat%22%3A%20%22crumbs%22%0A%20%20%20%20%20%7D%2C%0A%20%20%20%20%22outside%22%3A%20%7B%0A%20%20%20%20%20%20%22trunk%22%3A%20%22jack%22%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20gloveBoxContents%20%3D%20%22maps%22%3B%20%2F%2F%20Change%20this%20line%0AmyStorage.car%5B%22inside%22%5D%5B%22glove%20box%22%5D%20%3D%20gloveBoxContents%3B%0AmyStorage.car.inside%5B%22glove%20box%22%5D%20%3D%20gloveBoxContents%3B%0AmyStorage%5B%22car%22%5D.inside%5B%22glove%20box%22%5D%20%3D%20gloveBoxContents%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStorage = {
  "car": {
    "inside": {
      "glove box": "maps",
      "passenger seat": "crumbs"
     },
    "outside": {
      "trunk": "jack"
    }
  }
};

// Only change code below this line

var gloveBoxContents = "maps"; // Change this line
myStorage.car["inside"]["glove box"] = gloveBoxContents;
myStorage.car.inside["glove box"] = gloveBoxContents;
myStorage["car"].inside["glove box"] = gloveBoxContents;


```
all of examples above wont' pass the condition: Use dot and bracket notation to access myStorage

**Comment by texas2010** [comment]
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
