### ISSUE TITLE
Unable to move past this lesson. Page does not change after pressing "Run Tests".

### ISSUE THREAD

**Issue by user7791** [freeCodeCamp/freeCodeCamp#14194]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 .red-text {
    color: red;
  }

  <h2 class="red-text">CatPhotoApp</h2>

  <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by user7791** [comment]
Even the progress checklist is missing in lower left corner. I have hard refreshed the page 2 times (CTRL+F5)

**Comment by user512** [comment]
You can use multiple classes in the same selector.
To do this, all classes must be written directly after each another – with **no** white space.

**Comment by texas2010** [comment]
@user7791 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding..
