### ISSUE TITLE
Pierwszy html

### ISSUE THREAD

**Issue by mafer1** [freeCodeCamp/freeCodeCamp#14190]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%0A%3Ch1%3ESiema%3C%2Fh1%3E%0A%3Ch1%3EAle%20osohodzi%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Siema</h1>
<h1>Ale osohodzi</h1>

```

**Comment by techstonia** [comment]
That's not a bug. You have to write your code in english for this challenge to pass.

**Comment by mafer1** [comment]
@techstonia Ok, thank you :)
