### ISSUE TITLE
I can not use the (+=) Operator this this challenge.

### ISSUE THREAD

**Issue by geocolon** [freeCodeCamp/freeCodeCamp#14197]
Challenge [Concatenating Strings with the Plus Equals Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-the-plus-equals-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%3B%0AourStr%20%2B%3D%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20'This%20is%20the%20first%20sentence.%20'%20%2B%3D%20'This%20is%20the%20second%20sentence.'%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line

var myStr = 'This is the first sentence. ' += 'This is the second sentence.';



```

**Comment by geocolon** [comment]
After using (+=) I was not able to concatenate myStr value.

**Comment by user512** [comment]
`+=` is an addition assignment operator and you can only use it on a variable.
https://www.w3schools.com/js/js_operators.asp

You were trying to use it on a `string`.

**Comment by geocolon** [comment]
Hey Tom,
On Free Code Camp's Website an It states. "We can also use the += operator to concatenate a string onto the end of an existing string variable. This can be very helpful to break a long string over several lines." 

Am I am using += incorrectly for Strings or is Free Code Camp's wrong?

Please let me know.

**Comment by texas2010** [comment]
@geocolon 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
