### ISSUE TITLE
Add "Opening an issue on Github" waypoint/step on a waypoint for beginners

### ISSUE THREAD

**Issue by royshouvik** [FreeCodeCamp/FreeCodeCamp#1419]
I have been observing that a lot of issues are being created with simply incorrect code. This adds to the bug triaging effort and also doesn't push the newcomer to do analysis and research. It is assumed that FCC is buggy and the code is fine when it is not. There are certainly number of valid bugs but even then duplicate (valid) bugs is commonplace. Here is what I suggest-

1. Create a new waypoint or add these as steps in a waypoint.
2. Have the bug button display on challenges conditional ,for example only user with > 50 points would be able to see it. I am not sure  if it already works this way. Also, mention this to the user, something like "You will be able to open issues on Github once you have 50 points by  clicking this button".
3. Mention that user should search with the bonfire challenge title to find out if similar issue has already been reported.
4. If not found then he/she should go ahead and open a bug but add the complete title of the challenge on the bug title followed by the problem , so the next set of users can find this issue easily.
5. As a best practice of opening bugs, users should be encouraged to add screenshot of the problem, add the problamatic code *(in proper markdown formatting, this might also be an opportunity to briefly describe github markdown syntax for code, since this is very frequently asked on the chat room)* and describe the problem as verbosely as possible.

I hope I was able to explain clearly and you find this suggestion helpful.

**Comment by benschenker** [comment]
Thanks @royshouvik!
This has been done using the wiki and the contributing.md file.
