### ISSUE TITLE
Curriculum enhancements

### ISSUE THREAD

**Issue by masters-george** [freeCodeCamp/freeCodeCamp#14199]
As I worked through the JavaScript language module, I noted that the following areas are missing:
* Event handling

  Handling mouse and keyboard events -- this is often used with forms and other interactive 
  elements on a page

* Document Object Model

  The DOM is especially important when using AJAX so knowing how to manipulate it is critical. 
  Challenges could include things like changing the document in response to an event like clicking
  a button.

* Window Management

  Even though many may look down on opening windows, a case in point may be a read-only 
  search form that requires the user to click a button to open an edit form where changes can be
  made.

Even though much of this can be done with frameworks, part of learning the principles of the language includes learning to do this in JavaScript using effective best practices. I gave a couple of obvious examples of challenges, however, the wisdom of the whole group will result in better more realistic challenges for these areas. They could be in an intermediate language module so we don't have to hold up the beginning features in the currently debugged beginning JS module.

**Comment by erictleung** [comment]
Event handling and window management might be topics we could add. This interactivity might not be possible with our current tests? I'm not sure. Information on the DOM can be described in a forum wiki. If I remember @QuincyLarson saying that a coding challenge for learning about the DOM isn't interactive enough and a forum wiki post is sufficient. Although not ideal as it is separating curriculum material, for the sake of interactivity, that might be the best. If I misunderstood your suggested DOM challenges, please clarify.

cc/ @QuincyLarson @HKuz

**Comment by masters-george** [comment]
A simple interactive DOM exercise would be to have a form with two fields.
If a field on the form is blank update the DOM to show an error msg next to
the field. A different error msg can used for the second field. I can
certainly agree with Quincy that anything more realistic would require more
effort to develop.

**Comment by HKuz** [comment]
@masters-george and @erictleung - I don't recall any specific conversations about event handling and window management during the curriculum expansion work (that I was part of, at least), so I'll defer on that point 😄. I know the new JavaScript material generally focused on 'fundamentals' of the language, and the `JSON APIs and AJAX` section was rewritten to use only JS methods (vs. jQuery). Assuming we can make these challenges interactive and testable, I think it would be valuable to cover event listeners/window management within the challenges. It would help bridge between campers learning about JS as a language in `JavaScript Algorithms and Data Structures`, and seeing event handling done with React or jQuery (using JS in the browser) in the next section `Front End Libraries`.
