### ISSUE TITLE
First "Hello World" lesson does not work on Microsoft Edge.

### ISSUE THREAD

**Issue by FaalVedtuz** [freeCodeCamp/freeCodeCamp#14193]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#!) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello World</h1>

```

Hi guys, I've noticed that the lesson "Hello World" does not work on MS Edge. At first I thought my solution was wrong, but trying it in Firefox  seems to work. I haven't tried to troubleshoot any further since my initial conclusion was incompatibility. I can't provide any screenshot for this since there we're no errors or something.

Keep up the good work and kudos!

**Comment by erictleung** [comment]
@FaalVedtuz thanks for the issue. I'm sorry to hear it doesn't work on Edge. From my understanding, I think we're only supporting more established browsers such as Safari, Firefox, and Chrome. I don't think it is a priority to encompass Edge into our preferred browsers unless it gains more usage.

cc/ @QuincyLarson @BerkeleyTrue

**Comment by erictleung** [comment]
@FaalVedtuz so I'll be closing this issue as I've been informed that freeCodeCamp isn't going to support Edge just yet because the browser itself doesn't support many features we depend on to run our challenges. I hope you understand. In the meantime, please use Firefox or other popular browsers to work on freeCodeCamp. Happy coding!
