### ISSUE TITLE
Page won't proceed.

### ISSUE THREAD

**Issue by BobM1960** [freeCodeCamp/freeCodeCamp#14198]
#### Challenge Name; "Constructing Strings with Variable"

'https://www.freecodecamp.com/challenges/constructing-strings-with-variables#?solution=%0A%2F%2F%20Example%0Avar%20ourName%20%3D%20%22Free%20Code%20Camp%22%3B%0Avar%20ourStr%20%3D%20%22Hello%2C%20our%20name%20is%20%22%20%2B%20ourName%20%2B%20%22%2C%20how%20are%20you%3F%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20myName%20%3D%20%22Bob%22%3B%0Avar%20myStr%20%3D%20%22My%20name%20is%20%22%20%2B%20myName%20%2B%20%22%20and%20I%20am%20swell!%22%3B%0A%0A%0A'

#### Issue Description

Click "Run Tests", "Submit and go to my next challenge" comes up already orange. Page won't proceed to next challenge.

#### Browser Information

* Browser Name, Version: FireFox
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js
var ourName = "Free Code Camp";
var ourStr = "Hello, our name is " + ourName + ", how are you?";

// Only change code below this line
var myName = "Bob";
var myStr = "My name is " + myName + " and I am swell!";



```
#### Screenshot

https://i.gyazo.com/37a8e3e2e503961cfb9533b8be35df8b.png

**Comment by erictleung** [comment]
@BobM1960 thanks for the issue. I was unfortunately unable to reproduce your issue using both Firefox and Chrome. In my experience of going through issues, usually it has to do with various plugins being on that are interfering with that progressing button. So I'd recommend turning off some plugins or trying in a different browser to see if that clears the issue. I'll leave this issue open in case others are able to reproduce your issue.

**Comment by barkinet** [comment]
She is looking to me ,code

**Comment by erictleung** [comment]
Closing as stale. If you're still having an issue, please comment back with most information based on what I've suggest. Otherwise, happy coding!
