### ISSUE TITLE
Wrong answer?

### ISSUE THREAD

**Issue by antariprince** [freeCodeCamp/freeCodeCamp#14206]
Challenge [Use Clockwise Notation to Specify the Margin of an Element](https://www.freecodecamp.com/challenges/use-clockwise-notation-to-specify-the-margin-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.

I think the answer is wrong it should be clockwise but the correct answer checks for counter clockwise

**Comment by prateekgoel** [comment]
I don't think there's any issue.

I tried giving margin to green-box class as:

```

.green-box {
    background-color: green;
    margin: 40px 20px 20px 40px;
  }

```

An this works perfectly fine.

It has been asked:
Use Clockwise Notation to give the element with the green-box class a margin of 40px on its top and left side, but only 20px on its bottom and right side.

So basically, margin: 40px 20px 20px 40px; refers to margin: top40px right20px bottompx left40px;

Hope this helps.

**Comment by erictleung** [comment]
@antariprince thanks for the issue, but I don't think there is any issue as @prateekgoel has also pointed out. In this challenge, clockwise and counter-clockwise happen to be the same values. However, I think you're getting confused in the last sentence of the challenge where the directional words are top, left, bottom, and right. These are just describing the values easier, rather the actual order of the margin values. Closing as not an issue. If I'm wrong or misunderstood your issue, please comment and clarify your issue. Happy coding!
