### ISSUE TITLE
Browser size 100 % but not progressing

### ISSUE THREAD

**Issue by Vardo823** [freeCodeCamp/freeCodeCamp#14208]
Challenge [Size your Images](https://www.freecodecamp.com/challenges/size-your-images) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
I have set my browser zoom at 100 % and still cannot progress to the next step. It seems that the code is right.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
    .smaller-image{
      width:100px;
    }
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by Vardo823** [comment]
Sorry,
I realized I had a mistake in my code

**Comment by texas2010** [comment]
@Vardo823   no problem.  next time, use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
