### ISSUE TITLE
Sum All Odd Fibonacci Number - last test doesn't pass given correct output

### ISSUE THREAD

**Issue by RookieWookiee** [freeCodeCamp/freeCodeCamp#14201]
Intermediate Algorithm Scripting -- Sum All Odd Fibonacci Numbers

The last test case does not pass, also I get a weird syntax error in the dev console.
Since I relogged I'm not able to reproduce the bug and the test passes, only
the syntax error persists but I suppose that's on me.

[link to solution](http://tinyurl.com/lwargen)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```javascript
let fibNums = [1, 1];
function calcFibUntilNum(num) {
  let calc = function(n){
    if(n == 0) return fibNums[0];
    else {
      if(fibNums[n] == undefined) {
        fibNums.push(calc(n-1) + calc(n-2));
      }
      return fibNums[n];
    }
  };
  while(fibNums[fibNums.length-1] < num) 
    calc(fibNums.length);
}
function sumFibs(num) {
  calcFibUntilNum(num);
  return fibNums
    .filter((value) => value % 2 != 0 && value <= num )
      .reduce((prev, curr) => prev + curr , 0);
}
console.log(sumFibs(75025));
```
![Image](http://i.imgur.com/0P108Ah.png)

**Comment by MikeForde** [comment]
I initially made the same error - note the text says "return the sum of all odd Fibonacci numbers that are less than or **equal** to num"
