### ISSUE TITLE
Title tag on freecodecamp.com/twitch is incorrect.

### ISSUE THREAD

**Issue by 1hella** [FreeCodeCamp/freecodecamp#1420]
The title of the page is `<title>Enter Free Code Camp's Chat Rooms | Free Code Camp</title>`, when it could be something like `<title>Watch Free Code Camp Live on Twich.tv | Free Code Camp</title>`. It would make a lot more sense since this is not the chatroom page.

This might have been an issue of copy/pasting code from the chatroom page when making this one.

**Comment by QuincyLarson** [comment]
@1hella thanks for opening this issue. This page is going away.
