### ISSUE TITLE
removing comment tags.

### ISSUE THREAD

**Issue by Soviet777** [freeCodeCamp/freeCodeCamp#14203]
Challenge [Uncomment HTML](https://www.freecodecamp.com/challenges/uncomment-html) has an issue.
User Agent is: <code>Mozilla/5.0 (Android 5.1; Tablet; rv:50.0) Gecko/50.0 Firefox/50.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
Good day. When I do the mentioned lesson, nothing is happening. Could you please check into this.
<!--
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
-->

```

**Comment by texas2010** [comment]
@Soviet777 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by vtorres88** [comment]
how do I uncomment it? been trying for an hr and its wrong

**Comment by texas2010** [comment]
@vtorres88 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
