### ISSUE TITLE
The answer is wrong

### ISSUE THREAD

**Issue by antariprince** [freeCodeCamp/freeCodeCamp#14205]
Challenge [Use Clockwise Notation to Specify the Padding of an Element](https://www.freecodecamp.com/challenges/use-clockwise-notation-to-specify-the-padding-of-an-element) has an issue.

I think the answer is in counter clockwise instead of clockwise, its a bit confusing.

**Comment by prateekgoel** [comment]
I don't think there's any issue.

I tried giving margin to green-box class as:

```

.green-box {
    background-color: green;
    margin: 40px 20px 20px 40px;
  }

```

An this works perfectly fine.

It has been asked:
Use Clockwise Notation to give the element with the green-box class a margin of 40px on its top and left side, but only 20px on its bottom and right side.

So basically, margin: 40px 20px 20px 40px; refers to margin: top40px right20px bottompx left40px;

Hope this helps.

**Comment by erictleung** [comment]
@antariprince thanks for the issue, but my answer is similar to why I closed https://github.com/freeCodeCamp/freeCodeCamp/issues/14206. Please comment here or there if I misunderstood. But I don't think there's an issue. Happy coding!
