### ISSUE TITLE
Test on commenting should accept commented tags.

### ISSUE THREAD

**Issue by dagatsoin** [freeCodeCamp/freeCodeCamp#14213]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3C!--h1%3EHello%20World%3C%2Fh1--%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3C!--p%3EHello%20Paragraph%3C%2Fp--%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!--h1>Hello World</h1-->

<h2>CatPhotoApp</h2>

<!--p>Hello Paragraph</p-->

```
Should pass the test as only the H2 is displayed.

**Comment by texas2010** [comment]
@dagatsoin 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
