### ISSUE TITLE
My code seems right but still creating error.

### ISSUE THREAD

**Issue by designerhimanshu** [freeCodeCamp/freeCodeCamp#14216]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22Firstline%5Cn%5C%5CSecondLine%5C%5C%5CrThirdLine%22%3B%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "Firstline\n\\SecondLine\\\rThirdLine";// Change this line



```

**Comment by Mrprofessor** [comment]
Working fine dude..!!
var myStr = "FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line

**Comment by Mrprofessor** [comment]
Nope..Did you copied that text from somewhere..??

**Comment by texas2010** [comment]
@Mrprofessor 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by texas2010** [comment]
@designerhimanshu 
Thanks for reporting this. But you got typo.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
