### ISSUE TITLE
will not complete test, says I did everything correct but will not advance

### ISSUE THREAD

**Issue by phoenix1177** [freeCodeCamp/freeCodeCamp#14217]
Challenge [Build JavaScript Objects](https://www.freecodecamp.com/challenges/build-javascript-objects) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourDog = {
  "name": "Camper",
  "legs": 4,
  "tails": 1,
  "friends": ["everything!"]
};

// Only change code below this line.

var myDog = {
  "name": "Tanooki",
  "legs": 4,
  "tails": 1,
  "friends": ["me"]
  
  
  
};

```

**Comment by erictleung** [comment]
@phoenix1177 thanks for the issue. Sorry to hear you're having issue. Can you be more specific on how you're unable to advance after the challenge? Like are you able to get the success modal pop-up? Are all the challenge tests turning green? I am able to pass and advance the challenge using your code here.

**Comment by phoenix1177** [comment]
I got green check marks after refreshing but I could never get the success
alert to advance.

**Comment by JoolsMcFly** [comment]
Can you open the console (F12) and report any error message pls?

**Comment by phoenix1177** [comment]
![capture](https://cloud.githubusercontent.com/assets/25872753/24707225/cc5431ca-19e0-11e7-96d8-039373961435.JPG)

**Comment by ogora** [comment]
if left the array empty and it worked . So basically I tried to put something in earlier then it falied

**Comment by augmt** [comment]
@phoenix1177 Can you try with a different browser? I believe this might be an issue with Edge.

**Comment by raisedadead** [comment]
Looks like @phoenix1177 you are behind a network that is blocking some of the URL from being accessed. Also its possible that some browser plugins, like ad-blockers etc. can do this too.

Can you please check on a different browser like Google Chrome?

**Comment by raisedadead** [comment]
Please let us know in the comments if this does not work for you.
