### ISSUE TITLE
My code does not pass the challenge even though h1 is blue on the console

### ISSUE THREAD

**Issue by ComfortCodes** [freeCodeCamp/freeCodeCamp#14210]
Challenge [Override Styles in Subsequent CSS](https://www.freecodecamp.com/challenges/override-styles-in-subsequent-css#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3Ablack%3B%0A%20%20%20%20font-family%3AMonospace%3B%0A%20%20%20%20color%3Agreen%3B%0A%20%20%7D%0A%20%20%0A%20%20.pink-text%7B%0A%20%20%20%20color%3Apink%3B%0A%20%20%7D%0A%20%20%20.blue-text%7B%0A%20%20%20%20color%3Ablue%3B%0A%20%20%7D%20%20%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22blue-text%22%20%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color:black;
    font-family:Monospace;
    color:green;
  }
  
  .pink-text{
    color:pink;
  }
   .blue-text{
    color:blue;
  }  
</style>
<h1 class="blue-text" "pink-text">Hello World!</h1>

```

**Comment by techstonia** [comment]
Your code is not correct. If you have multiple classes they all should be inside one string (separated by space).

**Comment by texas2010** [comment]
@ComfortCodes 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by ComfortCodes** [comment]
Thanks a lot finally passed the challenge. Again thanks techstonia
