### ISSUE TITLE
smth wrong in 1st case?

### ISSUE THREAD

**Issue by elmapaul** [freeCodeCamp/freeCodeCamp#14229]
Challenge [Everything Be True](https://www.freecodecamp.com/challenges/everything-be-true#?solution=%0Afunction%20truthCheck(collection%2C%20pre)%20%7B%0A%20%20%2F%2F%20Is%20everyone%20being%20true%3F%0A%20%20var%20a%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20var%20b%20%3D%20collection%5B0%5D%5Bpre%5D%3B%0A%20%20%0A%20%20for%20(var%20t%20%3D%200%3B%20t%20%3C%20collection.length-1%3B%20t%2B%2B)%7B%0A%20%20%20%20%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20if%20(collection%5Bt%5D%5Bpre%5D%20!%3D%3D%20collection%5Bt%2B1%5D%5Bpre%5D)%20return%20false%3B%0A%20%20%20%20%20%20%20%20%0A%0A%20%20%7D%0A%20%20%0A%20%20return%20true%3B%0A%20%20%0A%20%20%2F%2Freturn%20collection%5B1%5D%5Bpre%5D%20%3D%3D%3D%20collection%5B2%5D%5Bpre%5D%3B%0A%7D%0A%0AtruthCheck(%5B%7B%22user%22%3A%20%22Tinky-Winky%22%2C%20%22sex%22%3A%20%22male%22%7D%2C%20%7B%22user%22%3A%20%22Dipsy%22%2C%20%22sex%22%3A%20%22male%22%7D%2C%20%7B%22user%22%3A%20%22Laa-Laa%22%2C%20%22sex%22%3A%20%22female%22%7D%2C%20%7B%22user%22%3A%20%22Po%22%2C%20%22sex%22%3A%20%22female%22%7D%5D%2C%20%22sex%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function truthCheck(collection, pre) {
  // Is everyone being true?
  var a = [];
  
  for (var t = 0; t < collection.length-1; t++){    
      
      if (collection[t][pre] !== collection[t+1][pre]) return false;       

  }
  
  return true;
}

truthCheck([{"user": "Tinky-Winky", "sex": "male"}, {"user": "Dipsy", "sex": "male"}, {"user": "Laa-Laa", "sex": "female"}, {"user": "Po", "sex": "female"}], "sex");

```

**Comment by JoolsMcFly** [comment]
There's nothing wrong with the challenge.

What your code does is:
```
for each item in collection
  if current item "pre" property is different then next element's "pre" property then return false

return true
```

What you should be doing is make sure each element's "pre" property evaluates to a `truthy` value (e.g. not `null` nor `undefined` nor `false` nor `0`).

Here's [my solution](https://www.freecodecamp.com/challenges/everything-be-true#?solution=%0Afunction%20truthCheck(collection%2C%20pre)%20%7B%0A%20%20%2F%2F%20Is%20everyone%20being%20true%3F%0A%20%20return%20collection.every(function%20(item)%20%7B%0A%20%20%20%20return%20item%5Bpre%5D%3B%0A%20%20%7D)%3B%0A%7D%0A) to the challenge.

Can you close this issue please?

Thanks.

**Comment by elmapaul** [comment]
sure, many thanks!

2017-04-04 0:02 GMT-07:00 Jools <notifications@github.com>:
