### ISSUE TITLE
freeCodeCamp Beta Bug on variable memory

### ISSUE THREAD

**Issue by DIZAD87** [freeCodeCamp/freeCodeCamp#14220]
Challenge [update-the-height-of-an-element-dynamically](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/update-the-height-of-an-element-dynamically) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

One key bug I am noticing on the beta is that it doesnt reset variables for every iteration you test so it faults every time unless you define a new variable for each iteration.

```html


<style>
  .bar {
    width: 25px;
    height: 100px;
    display: inline-block;
    background-color: blue;
  }
</style>
<body>
  <script>
    const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
    
    d3.select("body").selectAll("div")
      .data(dataset)
      .enter()
      .append("div")
      .attr("class", "bar")
      // Add your code below this line
      
      
      
      // Add your code above this line
  </script>
</body>

```

**Comment by Bouncey** [comment]
Running tests for a second time throws an error about creating duplicate variables, tested with `let` and `var`

**Comment by van100j** [comment]
It's not just this challenge, but it seems that most of the challenges in __Data Visualization with D3__ have this very same issue — [invert-svg-elements](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/invert-svg-elements) for example, or [change-styles-based-on-data](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/change-styles-based-on-data), also throw an error when running tests for the second (or third, fourth etc.) time. 

The issue arises from declaring `dataset` (and few more in some other challenges) as constant `const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];`, so when running the tests in the code editor `dataset` is being redeclared and reassigned, hence the error `Identifier 'dataset' has already been declared` (declaring with `let` will also throw the same error.) However, if declared with `var` it would work fine, as declarations with `var` are allowed to be reassigned and redeclared. 

Another workaround would be to have the entire JS code within an anonymous function (and keep `const` declarations):
```javascript
(function() {

  const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];

  d3.select("body").selectAll("div")
    .data(dataset)
    .enter()
    .append("div")
    .attr("class", "bar")
    // Add your code below this line

    // Add your code above this line
})()
```

But [currently, some of the tests](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/04-data-visualization/data-visualization-with-d3.json#L819) rely on the variables being decalred and accessible globally, and in such case all tests would need to be rewritten:
```javascript
{
  ...
  "tests": [
    "assert($('rect').eq(0).attr('y') == h - (dataset[0] * 3), 'message: The first <code>rect</code> should have a <code>y</code> value of 64.');",
    "assert($('rect').eq(1).attr('y') == h - (dataset[1] * 3), 'message: The second <code>rect</code> should have a <code>y</code> value of 7.');",
    "assert($('rect').eq(2).attr('y') == h - (dataset[2] * 3), 'message: The third <code>rect</code> should have a <code>y</code> value of 34.');",
    "assert($('rect').eq(3).attr('y') == h - (dataset[3] * 3), 'message: The fourth <code>rect</code> should have a <code>y</code> value of 49.');",
    "assert($('rect').eq(4).attr('y') == h - (dataset[4] * 3), 'message: The fifth <code>rect</code> should have a <code>y</code> value of 25.');",
    "assert($('rect').eq(5).attr('y') == h - (dataset[5] * 3), 'message: The sixth <code>rect</code> should have a <code>y</code> value of 46.');",
    "assert($('rect').eq(6).attr('y') == h - (dataset[6] * 3), 'message: The seventh <code>rect</code> should have a <code>y</code> value of 13.');",
    "assert($('rect').eq(7).attr('y') == h - (dataset[7] * 3), 'message: The eighth <code>rect</code> should have a <code>y</code> value of 58.');",
    "assert($('rect').eq(8).attr('y') == h - (dataset[8] * 3), 'message: The ninth <code>rect</code> should have a <code>y</code> value of 73.');"
  ],
  ...
}
```

I'd be happy to go [through all of these challenges](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/04-data-visualization/data-visualization-with-d3.json) and replace `const` with `var` (which would solve this issue), unless any suggestions or objections?

**Comment by HKuz** [comment]
@DIZAD87 thanks for bringing this up, and @van100j for offering to make a change. This is a D3 section issue that's being worked on over in #12762 - I'm going to close this one, but feel free to carry on the conversation for suggestions to fix it over there 👍  Also, thanks for your help with the QA efforts on the Beta site! 🎉 💯
