### ISSUE TITLE
Suggestion: Add social sharing of completed bonfires on profile page

### ISSUE THREAD

**Issue by kurzninja** [FreeCodeCamp/FreeCodeCamp#1422]
I just completed a Bonfire and before I could share it, I moved on to the next one. If I go back to the previous page, I'd have to copy/paste my code back into the editor and submit it again to get the option to share it again, creating another entry in the profile page with the same solution.

If there were buttons to share solving a bonfire from the profile page's solution entry, I wouldn't have to redo the bonfire, creating another profile "solution" entry. 

I doubt this is a common occurrence, but if it is, this might cut down on duplicate database entries.

**Comment by BerkeleyTrue** [comment]
Done!

Happy Coding!
