### ISSUE TITLE
Need additional test case

### ISSUE THREAD

**Issue by JayWIlsonJr** [FreeCodeCamp/FreeCodeCamp#1423]
Challenge http://www.freecodecamp.com/challenges/bonfire-where-art-thou has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I was able to hardcode the value to make the test pass. I think there should be a test written to test against this possible scenario. See my code below:

```js 
function where(collection, source) {
  var arr = [];
  // What's in a name?
  arr = collection.filter(function(item) {
    return item.last === source.last;
  });
  return arr;
}

where([{ first: 'Romeo', last: 'Montague' }, { first: 'Mercutio', last: null }, { first: 'Tybalt', last: 'Capulet' }], { last: 'Capulet' });
```

**Comment by kurzninja** [comment]
I'm not sure if there is a way to test against this scenario. The test cases are only checking for the proper output in ALL of the bonfires, they aren't testing how you got to that output.

As for your code, I'm not sure how you consider that "hardcoding" the answer, you're just generating the answer using functional programming technique. This isn't the intended way of solving this bonfire, but it's certainly a valid method, especially once you pass the Functional Programming waypoint and go back and redo the bonfires using those techniques like some of us have.

Please correct me if I'm wrong.

**Comment by benschenker** [comment]
Closing this issue as stale, please reopen if you deem it unresolved
