### ISSUE TITLE
Repeat a string repeat a string

### ISSUE THREAD

**Issue by sousadgaspar** [freeCodeCamp/freeCodeCamp#14235]
Challenge [Repeat a string repeat a string](https://www.freecodecamp.com/challenges/repeat-a-string-repeat-a-string) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
I'm not sure if it is a bug or is your intention, but I noticed that the title of the exercice is repited twoice "Repeat a string **repeat a string**"

I hope I helped!



```

**Comment by sousadgaspar** [comment]
Hi bot! that was not a help request. :)

**Comment by OFFLlNE** [comment]
Pretty sure it is intentional. To show the repeat :D
Will close this because not really an issue :)
