### ISSUE TITLE
Challenge test regex doesn't recognize dash

### ISSUE THREAD

**Issue by austinHeisleyCook** [freeCodeCamp/freeCodeCamp#14246]
Challenge [Add Images to your Website](https://www.freecodecamp.com/challenges/add-images-to-your-website#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%20%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22relaxing-cat%22%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
 </style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
<img src="https://bit.ly/fcc-relaxing-cat" alt="relaxing-cat">

```

does not recognize the alt tag even tho user typed it in the image tag

**Comment by erictleung** [comment]
@austinHeisleyCook thanks for the issue. The real issue is that it doesn't recognize the dash `-` within your `alt` tag. I'm not sure why isn't not. I don't see anything wrong with the [challenge test regex](https://github.com/freeCodeCamp/freeCodeCamp/blob/3351c1ea954d0d183fcc16643008616ca4c3d422/seed/challenges/01-responsive-web-design/basic-html-and-html5.json#L580).

Regex101: https://regex101.com/r/0LCoJt/2

cc/ @freeCodeCamp/moderators

**Comment by Dayfiri** [comment]
If you remove one letter from your image `src` , you can see that your `alt` value will be shown on the screen. You can write `cat` or `kit-kat`, both will be shown on the screen but it won't let you pass if you use `-` anywhere in the *alt* tags.

Tested on : Firefox - version 52
                   Chromium - version 57

By the way, `alt = "this.that"` and `alt="this_that"` works.

**Comment by hay-dee** [comment]
@erictleung I dig a little digging into the source code and found that the challenge is currently using the old test regex, which is <code>alt\\s*?=\\s*?(\\\"|\\')[\\s\\w\\.\\,\\!]+?(\\\"|\\')</code>. It is evident that the regex does not capture dashes within the square brackets. 

Here is the regex test: https://regex101.com/r/0LCoJt/2

Seems like an easy enough fix, maybe we can open this up to first-timers? 😄

**Comment by dhcodes** [comment]
The regex has already been improved on staging (beta) to account for any character except line terminators. You can test it here: http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/add-images-to-your-website

Since updates to the production site are now limited to "critical issues", I vote we mark this as resolved in staging.

**Comment by erictleung** [comment]
@dhcodes thanks for checking on beta! I forgot to check there :sweat_smile: I'll close this then and leave the `resolved in staging` label.
