### ISSUE TITLE
Cannot find module 'babel/register'

### ISSUE THREAD

**Issue by dandan86** [FreeCodeCamp/FreeCodeCamp#1424]
Hi guys,
I cloned the freecodecamp repo in cloud9. The virtual machine is equipped with node.js and mongodb.
I followed the "getting started" guide in the README but when I reached the step "node seed/" I get this error:
``` 
nico@freecodecamp:~/workspace (staging) $ node seed/

module.js:340
    throw err;
          ^
Error: Cannot find module 'babel/register'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/workspace/seed/index.js:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```
 
Do you have any idea about this problem?

**Comment by BerkeleyTrue** [comment]
Error stems from not having babel module in node_modules directory
Did you do npm install?

**Comment by dandan86** [comment]
Yes I did npm install. If it can be useful I can run it again just to look at the log.

**Comment by BerkeleyTrue** [comment]
Are you on windows?

**Comment by dandan86** [comment]
No I'm on cloud9 (https://ide.c9.io/nicolimo86/freecodecamp). It's a linux virtual machine.

**Comment by BerkeleyTrue** [comment]
Can you try latest from staging with 'rm -rf node_modules/; npm install'

**Comment by dandan86** [comment]
this is the result:
nicolimo86@freecodecamp:~/workspace (staging) $ npm install
npm ERR! not a package /tmp/npm-844-49wSRehH/github.com/BerkeleyTrue/react-router
npm WARN deprecated gulp-webpack@1.5.0: Renamed to https://www.npmjs.com/package/webpack-stream
npm ERR! not a package /tmp/npm-844-49wSRehH/github.com/FreeCodeCamp/loopback.git
npm ERR! Error: ENOENT, open '/tmp/npm-844-49wSRehH/github.com/BerkeleyTrue/react-router-unpack/package.json'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.14.13-c9
npm ERR! command "/home/ubuntu/.nvm/v0.10.35/bin/node" "/home/ubuntu/.nvm/v0.10.35/bin/npm" "install"
npm ERR! cwd /home/ubuntu/workspace
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! path /tmp/npm-844-49wSRehH/github.com/BerkeleyTrue/react-router-unpack/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/workspace/npm-debug.log
npm ERR! not ok code 0

I think something on C9 is not working well...

**Comment by dandan86** [comment]
this is the result:
nicolimo86@frecodecamp2:~/workspace (master) $ npm install
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
 
> utf-8-validate@1.1.0 install /home/ubuntu/workspace/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/home/ubuntu/workspace/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/ubuntu/workspace/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
 
> bufferutil@1.1.0 install /home/ubuntu/workspace/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/home/ubuntu/workspace/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory `/home/ubuntu/workspace/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
 
> kerberos@0.0.11 install /home/ubuntu/workspace/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/ubuntu/workspace/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  SOLINK_MODULE(target) Release/obj.target/kerberos.node: Finished
  COPY Release/kerberos.node
make: Leaving directory `/home/ubuntu/workspace/node_modules/mongodb/node_modules/kerberos/build'
 
> bufferutil@1.1.0 install /home/ubuntu/workspace/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/home/ubuntu/workspace/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory `/home/ubuntu/workspace/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
 
> utf-8-validate@1.1.0 install /home/ubuntu/workspace/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/home/ubuntu/workspace/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/ubuntu/workspace/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'

> bson@0.2.22 install /home/ubuntu/workspace/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/ubuntu/workspace/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
  COPY Release/bson.node
make: Leaving directory `/home/ubuntu/workspace/node_modules/mongodb/node_modules/bson/build'

> kerberos@0.0.12 install /home/ubuntu/workspace/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/ubuntu/workspace/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  SOLINK_MODULE(target) Release/obj.target/kerberos.node: Finished
  COPY Release/kerberos.node
make: Leaving directory `/home/ubuntu/workspace/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'

> bson-ext@0.1.12 install /home/ubuntu/workspace/node_modules/mongoose/node_modules/bson/node_modules/bson-ext
> (node-pre-gyp install --fallback-to-build) || (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/ubuntu/workspace/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
  COPY Release/bson.node
make: Leaving directory `/home/ubuntu/workspace/node_modules/mongoose/node_modules/bson/node_modules/bson-ext/build'
npm ERR! EEXIST, open '/home/ubuntu/.npm/6bbc2d07-ntu-npm-oauth-0-9-13-package-tgz.lock'
File exists: /home/ubuntu/.npm/6bbc2d07-ntu-npm-oauth-0-9-13-package-tgz.lock
Move it away, and try again. 

npm ERR! System Linux 3.14.13-c9



I tried to remove the file /home/ubuntu/.npm/6bbc2d07-ntu-npm-oauth-0-9-13-package-tgz.lock but it doesn't exists.

**Comment by BerkeleyTrue** [comment]
Try `npm cache clean`

**Comment by dandan86** [comment]
that's the output now:

nicolimo86@frecodecamp2:~/workspace (master) $ npm cache clean
nicolimo86@frecodecamp2:~/workspace (master) $ npm install
passport-facebook@1.0.3 node_modules/passport-facebook
└── passport-oauth2@1.1.2 (uid2@0.0.3, passport-strategy@1.0.0, oauth@0.9.13)

**Comment by BerkeleyTrue** [comment]
@dandan86 Are you stilll having issues with NPM?

**Comment by benschenker** [comment]
I was having that exact same issue on c9, I can try to see if the steps here fix it

**Comment by BerkeleyTrue** [comment]
I'm closing this as stale. @dandan86 Please PM me directly and we can trouble shoot in real time.

**Comment by dandan86** [comment]
@BerkeleyTrue I wrote you on gitter.

**Comment by BerkeleyTrue** [comment]
I haven't received any messages from you @dandan86

**Comment by dandan86** [comment]
@BerkeleyTrue it's impossible to say if everything is ok after the steps you suggested me because when I try to start the mongodb server I get this error:
nicolimo86@frecodecamp2:~/workspace (master) $ mongod
mongod --help for help and startup options
2015-08-23T08:18:56.165+0000 [initandlisten] MongoDB starting : pid=1676 port=27017 dbpath=/data/db 64-bit host=nicolimo86-frecodecamp2-1781819
2015-08-23T08:18:56.165+0000 [initandlisten] db version v2.6.9
2015-08-23T08:18:56.165+0000 [initandlisten] git version: df313bc75aa94d192330cb92756fc486ea604e64
2015-08-23T08:18:56.165+0000 [initandlisten] build info: Linux build20.nj1.10gen.cc 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64 BOOST_LIB_VERSION=1_49
2015-08-23T08:18:56.165+0000 [initandlisten] allocator: tcmalloc
2015-08-23T08:18:56.165+0000 [initandlisten] options: {}
2015-08-23T08:18:56.179+0000 [initandlisten] journal dir=/data/db/journal
2015-08-23T08:18:56.179+0000 [initandlisten] recover : no journal files present, no recovery needed
2015-08-23T08:18:56.179+0000 [initandlisten] 
2015-08-23T08:18:56.179+0000 [initandlisten] ERROR: Insufficient free space for journal files
2015-08-23T08:18:56.179+0000 [initandlisten] Please make at least 3379MB available in /data/db/journal or use --smallfiles
2015-08-23T08:18:56.179+0000 [initandlisten] 
2015-08-23T08:18:56.188+0000 [initandlisten] exception in initAndListen: 15926 Insufficient free space for journals, terminating
2015-08-23T08:18:56.188+0000 [initandlisten] dbexit: 
2015-08-23T08:18:56.188+0000 [initandlisten] shutdown: going to close listening sockets...
2015-08-23T08:18:56.188+0000 [initandlisten] shutdown: going to flush diaglog...
2015-08-23T08:18:56.188+0000 [initandlisten] shutdown: going to close sockets...
2015-08-23T08:18:56.188+0000 [initandlisten] shutdown: waiting for fs preallocator...
2015-08-23T08:18:56.188+0000 [initandlisten] shutdown: lock for final commit...
2015-08-23T08:18:56.188+0000 [initandlisten] shutdown: final commit...
2015-08-23T08:18:56.188+0000 [initandlisten] shutdown: closing all files...
2015-08-23T08:18:56.188+0000 [initandlisten] closeAllFiles() finished
2015-08-23T08:18:56.188+0000 [initandlisten] journalCleanup...
2015-08-23T08:18:56.188+0000 [initandlisten] removeJournalFiles
2015-08-23T08:18:56.198+0000 [initandlisten] shutdown: removing fs lock...
2015-08-23T08:18:56.198+0000 [initandlisten] dbexit: really exiting now

It seems that the c9 VM doesn't have enough resources to run the project. Maybe your suggestions solved the NPM problem but I can't confirm it with certainty. Anyway I abondoned the idea to run the project on c9, I'm not sure it's possible. If nobody cares we can close the issue. Thank you for the help!

**Comment by benschenker** [comment]
@dandan86, did you try adding `--smallfiles` like it suggests?

**Comment by dandan86** [comment]
@benschenker No! I've just tried and it works!:-) thank you!

**Comment by benschenker** [comment]
Awesome! I still haven't figured out how to get `node seed` to work though, have you?

@dandan86, would you mind writing a wiki page explaining how to get FreeCodeCamp running on c9 specifically?

**Comment by dandan86** [comment]
@benschenker with your advice and I made mongodb working. Anyway I got stuck again with `node seed`.

**Comment by benschenker** [comment]
Yeah that wasn't working for me too...
