### ISSUE TITLE
bug :(

### ISSUE THREAD

**Issue by KruszynaPaulina** [freeCodeCamp/freeCodeCamp#14240]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%7D%0A%20%20pink-class%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
 }
  pink-class {
    color: pink;
  }
</style>
<h1 class="pink-text">Hello World!</h1>


```

**Comment by texas2010** [comment]
@KruszynaPaulina 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only. 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
