### ISSUE TITLE
am i doing something wrong here, looked at a few examples and they all seem to be doing the same stuff and getting the same error. I tried the class="class1 class2" code, it didnt work. 

### ISSUE THREAD

**Issue by DV1988** [freeCodeCamp/freeCodeCamp#14247]
Challenge [Override Styles in Subsequent CSS](https://www.freecodecamp.com/challenges/override-styles-in-subsequent-css#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blue-text%20%7Bcolor%3Ablue%3B%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22blue-text%22%20class%3D%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {color:blue;}
</style>
<h1 class="blue-text" class="pink-text">Hello World!</h1>

```

**Comment by JoolsMcFly** [comment]
Hi,

as per instructions:
> Applying multiple class attributes to a HTML element is done with a space between them like this:
> `class="class1 class2"`

So instead of `class="class1" class="class2"`  you need to write `class="class1 class2"`

Can you close this issue as this is just for reporting bugs. For questions, pls use the forums.
Thanks.

**Comment by erictleung** [comment]
@DV1988 thanks for the issue, but as @JoolsMcFly has pointed out, your code is incorrect. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by DV1988** [comment]
Ill close it, but my other issues is that when i get to log in with github
it dosent do it, i click it and it just disapeers.
