### ISSUE TITLE
[BETA] Can't continue to next challenge after opening the Medium link.

### ISSUE THREAD

**Issue by mike1136** [freeCodeCamp/freeCodeCamp#14259]
#### Challenge Name
Join The FreeCodeCamp community 

https://beta.freecodecamp.com/en/challenges/join-the-freecodecamp-community/read-coding-news-on-our-medium-publication

#### Issue Description

After opening the  link for the freeCodeCamp medium page and hitting finish challenge I get a "Something went wrong,Please try again" message

#### Browser Information

* Browser Name, Version: Firefox for ArchLinux 52.0.1 (64-bit)
* Operating System: OS: Arch Linux x86_64  Kernel: 4.10.5-1-ARCH 
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

<a href="http://imgur.com/uzN2gSi"><img src="http://i.imgur.com/uzN2gSi.png" title="source: imgur.com" /></a>

**Comment by mike1136** [comment]
Update: It shows progress on the map

**Comment by ooade** [comment]
@mike1136 Can't reproduce.
P.S: Beta is pretty unstable now, you'd have that popping up once a while :(

**Comment by QuincyLarson** [comment]
We're removing this challenge completely.
