### ISSUE TITLE
Comment out your p element so that it is not visible on your page.

### ISSUE THREAD

**Issue by oalharbi1** [freeCodeCamp/freeCodeCamp#14250]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%3Chtml%3E%0A%3C!--%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3C!--welcome--%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%20%20%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%20%20%3C!--This%20my%20job--%3E%0A--%3E%0A%3Chtml%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<html>
<!--
<h1>Hello World</h1>
<!--welcome-->
<h2>CatPhotoApp</h2>
  
<p>Hello Paragraph</p>
  <!--This my job-->
-->
<html>
```

**Comment by JoolsMcFly** [comment]
Please use forums to ask questions.
There is nothing wrong with this challenge.

Just make sure you surround elements you want to comment with `<!--` and `-->`.

So to comment
`hello world`
you do this:
`<!-- hello world -->`

Initial code is entirely commented:
```
<!--
all
of
this 
is
commented
-->
```

Just make sure you end the leading comment before the `h2` tag.

> Here you'll need to end the comment before your h2 element begins.

Can you close this issue please?

Thanks.

**Comment by texas2010** [comment]
@oalharbi1 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by Theicedoge** [comment]
<h2>CatPhotoApp</h2>

**Comment by Theicedoge** [comment]
<h2>CatPhotoApp</h2>
