### ISSUE TITLE
submiting on compliting

### ISSUE THREAD

**Issue by Asalehusman** [freeCodeCamp/freeCodeCamp#14251]
Challenge [Use appendTo to Move Elements with jQuery](https://www.freecodecamp.com/challenges/use-appendto-to-move-elements-with-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by JoolsMcFly** [comment]
Your code does not do what instructions say:
> Move your `target2` element from your `left-well` to your `right-well`.

When you do that, hit Ctrl+Enter or click the Run button and you should get green.

**Comment by Nurlyssultan** [comment]
I believe you did not get the task. You have to use appendTo() function to move the element $(#target2) to the "left-well" side.
