### ISSUE TITLE
Title Case a Sentence: Correct Result (but obviously wrong)

### ISSUE THREAD

**Issue by tc-seiko** [freeCodeCamp/freeCodeCamp#14255]
#### Challenge Name

Title Case a Sentence

#### Issue Description

I've been working on this challenge since yesterday. The first solution I found was wrong (discovered the mistake thanks to the forums here: I had added an extra space at the end).

Below is my second solution, which gives me the right answers but isn't correct according to freeCodecamp. I'd really appreciate it, if someone could tell me where I made a mistake.

I'm still new to Javascript (started the JS lessons three days ago) and would really need to find some extra resources to study it in depth. 

My solution:

#### Browser Information

* Browser Name, Version: Chrome Version 56.0.2924.87
* Operating System: Windows 8.1
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

var joinArray = [];

function titleCase(str) {
var array = str.toLowerCase().split(" ");
for (var i = 0; i < array.length; i++){
array[i] = array[i].replace(array[i][0], array[i][0].toUpperCase());
joinArray.push(array[i]);
}

return joinArray.join(" ");
}

titleCase("sHoRt AnD sToUt");

**Comment by JoolsMcFly** [comment]
Hi,

your code is indeed correct when called once but has a flow if you call it several times.
You have declared `var joinArray = []` outside of your function so when tests are run, they call `titleCase` several times and new elements get added to joinArray.
If you add `console.log(joinArray.join(""));` right before the `return` statement and click Run you will see this in console:
```
Short And Stout
Short And Stout
Short And Stout I'm A Little Tea Pot
Short And Stout I'm A Little Tea Pot I'm A Little Tea Pot
Short And Stout I'm A Little Tea Pot I'm A Little Tea Pot Short And Stout
Short And Stout I'm A Little Tea Pot I'm A Little Tea Pot Short And Stout Here Is My Handle Here Is My Spout
```

So to fix this, just move `var joinArray = [];` into your function and close this issue.

Thanks!
