### ISSUE TITLE
Bonfire: Symmetric Difference: assertion

### ISSUE THREAD

**Issue by fallrisk** [FreeCodeCamp/freecodecamp#1425]
The Symmetric Difference problem has the following test.
```javascript
assert.deepEqual(sym([1, 2, 5], [2, 3, 5], [3, 4, 5]), [1, 4, 5], 'should return the symmetric difference of the given arrays');
```
The number 5 is in all three of the arrays. I don't think it should be in the result.

**Comment by roderickjoseph** [comment]
I agree, the test underneath it has a 5 in each array and is included in the answer as well.

**Comment by SaintPeter** [comment]
The tests are correct.
See commentary here: #1402 and #1358 

Also, this video is helpful:
https://www.youtube.com/watch?v=PxffSUQRkG4

**Comment by ahstro** [comment]
Can probably be closed, right?

**Comment by alf808** [comment]
i'm still getting this test error:
![screen shot 2015-08-11 at 15 46 26](https://cloud.githubusercontent.com/assets/79753/9214992/69edd1ce-4040-11e5-80be-f4124cb2f268.png)
