### ISSUE TITLE
page is still not responding correctly

### ISSUE THREAD

**Issue by phoenix1177** [freeCodeCamp/freeCodeCamp#14256]
Challenge [Accessing Objects Properties with Variables](https://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables#?solution=%0A%2F%2F%20Setup%0Avar%20testObj%20%3D%20%7B%0A%20%2012%3A%20%22Namath%22%2C%0A%20%2016%3A%20%22Montana%22%2C%0A%20%2019%3A%20%22Unitas%22%0A%7D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%3B%0A%0Avar%20playerNumber%20%3D%2016%20%3B%20%20%20%20%20%20%20%2F%2F%20Change%20this%20Line%0Avar%20player%20%3D%20testObj%5BplayerNumber%5D%3B%20%20%20%2F%2F%20Change%20this%20Line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};

// Only change code below this line;

var playerNumber = 16 ;       // Change this Line
var player = testObj[playerNumber];   // Change this Line

```

I know I have the correct code but when I test the code it doesn't advance anymore it does not send a success alert, and I have to refresh the screen to change the x's to green checks on the page and it still does not prompt the alert to advance.
this is the error messages in the console after refreshing the page and trying to test the code twice.

![capture](https://cloud.githubusercontent.com/assets/25872753/24709852/49b4f0fc-19e9-11e7-9c26-a3b9609640ca.JPG)

**Comment by phoenix1177** [comment]
this is the only thing that happens when I test the challenge it goes no further.
![capture](https://cloud.githubusercontent.com/assets/25872753/24710884/71783f74-19ec-11e7-8999-29111d0bf2f3.JPG)

**Comment by ooade** [comment]
@phoenix1177 You shared two different challenges??

**Comment by phoenix1177** [comment]
Yes because all of the challenges are like that and I haven't gotten a
solution

**Comment by ooade** [comment]
@phoenix1177 It seems an extension or plugin is messing up your experience... @BerkeleyTrue Something seem wrong with the sourcemaps but don't think that should cause this. WDYT?
