### ISSUE TITLE
javascript

### ISSUE THREAD

**Issue by shruti1305** [freeCodeCamp/freeCodeCamp#14254]
Challenge [Storing Values with the Assignment Operator](https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator#?solution=%0A%2F%2F%20Setup%0Avar%20a%3B%0Avar%20b%20%3D%202%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Ab%2B%3D5%3B%0Ab%3Da%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var a;
var b = 2;

// Only change code below this line
b+=5;
b=a;
```

**Comment by JoolsMcFly** [comment]
Nothing wrong with the challenge. Double check your code.

Instructions:
>Assign the value 7 to variable `a`.

> Assign the contents of `a` to variable `b`.

What you did:

increment `b` by 5
assign `a` to `b`

Can you close this issue pls?

**Comment by Dayfiri** [comment]
@shruti1305 Hi, 
this forum is for reporting bugs only. If you have problems with solving the problems in the assignment, you can always check [HELP](https://gitter.im/FreeCodeCamp/Help?source=all-rooms-list) room for further problems in your coding journey. 
Happy coding ;)

**Comment by shruti1305** [comment]
i did the code according to the instructions.yet its not showing positive answer.

**Comment by Dayfiri** [comment]
@shruti1305 
No, you didn't do it right. If you were, then the assignment would let you pass.
Here is the picture of assignment working, if written correct.
![screenshot from 2017-04-05 12-41-25](https://cloud.githubusercontent.com/assets/16082563/24702475/2b7d6130-19ff-11e7-9cbc-41d3e71b27a5.png)

**Comment by shruti1305** [comment]
one last time @Dayfiri can you show me the code please.i have tried everything

**Comment by Dayfiri** [comment]
@shruti1305 
No, because for your own good. Goal of programming is to learn on mistakes and not copy/paste other solutions. Programming is hard and there is no doubt about it but if you try and keep trying, you will succeed. Like I said above, if you have question about the assignment you're on, check [THIS](https://gitter.im/FreeCodeCamp/Help?source=all-rooms-list) link for help. There is nice community of people wiling to help. This forum is for reporting bugs only. 

Happy coding !

**Comment by shruti1305** [comment]
ok i got it@Matko Hromin.thank you for helping.ill try it by myself :)
