### ISSUE TITLE
the phone on the right keeps crashing

### ISSUE THREAD

**Issue by coolwolf21** [freeCodeCamp/freeCodeCamp#14267]
The create a form element keeps crashing on me. I cant type past line 48 and the phone on the left keeps crashing. I have cleared my browser and re-started my computer, but it keeps crashing. help please?

**Comment by coolwolf21** [comment]
Hi @VarCI-bot 
The phone on the right  keeps saying 
Chrome detected unusual code on this page and blocked it to protect your personal information (for example, passwords, phone numbers, and credit cards).
and no one on the help chat room knows why either.

**Comment by weed777** [comment]
i have the same problem

**Comment by barkinet** [comment]
Opera isn't supported here

**Comment by coolwolf21** [comment]
i'm not using Opera i am using chrome @barkinet

**Comment by Manish-Giri** [comment]
@coolwolf21 It's a known issue with Chrome, switch to another browser for now.

**Comment by gurjindermassan** [comment]
Hi, I had the same problem and resolved it by clearing my recent browser history. :)

**Comment by texas2010** [comment]
thanks for the report, and we confirm that this is a known issue, check #13727 

Closing as a duplicate.
