### ISSUE TITLE
[Beta]: Can't see any certificates issued to my profile

### ISSUE THREAD

**Issue by shashank7200** [freeCodeCamp/freeCodeCamp#14272]
#### Screenshot

![alt-tag](https://i.imgur.com/EL5BJe5.png)

**Comment by dhcodes** [comment]
@shashank7200 can you post a screenshot of your public portfolio page?

**Comment by shashank7200** [comment]
@dhcodes  I can't access it as [https://beta.freecodecamp.com/shashank7200](https://beta.freecodecamp.com/shashank7200) redirects me to [https://beta.freecodecamp.com/en/map](https://beta.freecodecamp.com/en/map)!

**Comment by shashank7200** [comment]
@quincylarson When will I/others will get this certificate?
