### ISSUE TITLE
Bonfire: SteamRoller

### ISSUE THREAD

**Issue by MrHormonas** [FreeCodeCamp/FreeCodeCamp#1427]
```
ar ar=[];

function steamroller(arr) {
  // I'm a steamroller, baby

  for(var i=0; i<arr.length; i++)
  {
    if(!Array.isArray(arr[i]))
      ar.push(arr[i]);
    else
      steamroller(arr[i]);
  }
  return ar;
}
steamroller([1, [], [3, [[4]]]]);
```
i think it's a bug

**Comment by benschenker** [comment]
Hey @MrHormonas, I'm not really sure what you are looking for here, can you clarify?  Is this still an issue for you?

**Comment by lonerz** [comment]
Hi, I have the same issue currently. What MrHormonas means by bug, is that the output is exactly the same, but is counted as incorrect.

**Comment by ltegman** [comment]
This code is using a global variable which means that it only works as expected on the first run. Initializing `ar` outside of the function body means that on the second run of the function you're not starting fresh and you're pushing onto an `ar` variable that still has values in it from the last time the function was run.

**Comment by lonerz** [comment]
Oh, I see. Thanks. Changed my code to run local.
