### ISSUE TITLE
Diff Two Arrays (Task 266) - Works in browser console though fails in FCC

### ISSUE THREAD

**Issue by macjsnow** [freeCodeCamp/freeCodeCamp#14274]
#### Challenge Name
Diff Two Arrays (Task 266)

#### Issue Description
All tests pass OK except for the following:
[], ["snuffleupagus", "cookie monster", "elmo"] should return ["snuffleupagus", "cookie monster", "elmo"]

Tested in the below browsers though results match the expected.

![1](https://cloud.githubusercontent.com/assets/1658943/24769623/d0152898-1b0f-11e7-8c37-c9cbce84a34a.png)
![2](https://cloud.githubusercontent.com/assets/1658943/24769621/d00f694e-1b0f-11e7-96b1-6eb5bf71425e.png)
![3](https://cloud.githubusercontent.com/assets/1658943/24769622/d00fdd34-1b0f-11e7-89a7-d62276e36a1c.png)

#### Browser Information
* Browser Name, Version:  Chrome 57.0.2987.133, Firefox 52.0.2 (32-bit)
* Operating System: Windows 8.3
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
function diffArray(arr1, arr2) {
	var i = l = 0,
	newArr = [],
	arr1Len = arr1.length,
	arr2Len = arr2.length;

	if(arr1Len === 0){
		newArr.push(arr2);
	}else if(arr2Len === 0){
		newArr.push(arr1);
	}else{
		for(i; i < arr1Len; i++){
			if(arr2.indexOf(arr1[i]) === -1){
				newArr.push(arr1[i]);
				}
			}
		
		for(l; l < arr2Len; l++){
			if(arr1.indexOf(arr2[l]) === -1 && newArr.indexOf(arr2[l] === -1)){
				newArr.push(arr2[l]);
				}
			}
		}
	return newArr;
}

**Comment by Manish-Giri** [comment]
@macjsnow Your code returns a nested array when an empty array is present as one of the arguments - `[["snuffleupagus", "cookie monster", "elmo"]]`.

https://jsbin.com/kabeme/edit?js,console

**Comment by macjsnow** [comment]
Oh, indeed. thank you for the quick reply!
