### ISSUE TITLE
Pig latin test case not specified in problem statement. 

### ISSUE THREAD

**Issue by DataNick** [freeCodeCamp/freeCodeCamp#14278]
#### Challenge Name
Pig Latin

#### Issue Description
The challenge description doesn't include all the test cases to write the algorithm for. I wrote my solution according to the problem. An error occurred on this test case:
"Should handle words where the first vowel comes in the end of the word."
No where in the description is this a requirement. Nor does it explain what it expects as a result.

#### Your Code

```js

function translatePigLatin(str) {
  if ((/^[aeiou]/).test(str[0])){
    return str.concat('way');
  } else {
    var cons = str.match(/^[bcdefghjklmnpqrstvxzy]{1,}/)[0];
    var newStr = str.slice(cons.length);
    return newStr.concat(cons).concat('ay');

  }
}

translatePigLatin("consonant");



```

**Comment by hallaathrad** [comment]
Hmmm I don't see what the student needs to do in that case (at least not in the description).
Marking as confirmed unless someone points out where the instruction is for this.

**Comment by hallaathrad** [comment]
On further analysis, the test case itself doesn't make sense to me either... Please someone explain this one for me?

"assert.deepEqual(translatePigLatin(\"schwartz\"), \"artzschway\", 'message: Should handle words where the first vowel comes in the end of the word.');"

In "schwartz" the vowel (i.e. "a") is not at the end of the word... I'm confooosed 🙃

**Comment by fredygil** [comment]
Hi,

You can read more about Pig Latin [in this Wikipedia entry](https://en.wikipedia.org/wiki/Pig_Latin). According to it, **schwartz** in Pig Latin is: **artz** (start with the first vowel until the end of the word) + **schw** (first part of the word before the first vowel) + **ay** = **artzschway**.

Now, if the input word start with a vowel, as is the case with **algorithm**, you just add **way** to the end, so it becomes **algorithmway** in Pig Latin.

I hope this helps.

**Comment by hallaathrad** [comment]
But that's the thing... Schwartz starts with "schw", not with a. Also, that doesn't explain the test's phrasing (i.e. The word ends with the first vowel)

The example I'm thinking of would be "ski" and in that case it would be "iskay", which is covered by the other tests. If this specific test is a fringe case, ot should be explained what the result should be for it in the description, or thw test needs be rephrased. I'd be glad to do either but I simply don't even get what it aims toward.

**Comment by ScottHutchinson** [comment]
@QuincyLarson The description of the test "Should handle words where the first vowel comes in the end of the word" is still incorrect. Maybe it should be "Should handle words where there are more than two consonants at the beginning of the word (e.g., 'Schwartz ')."

Also the test description "Should handle words without vowels" should be "Words without vowels should be returned as the unchanged word followed by 'ay'."
