### ISSUE TITLE
problem finishing the case sensitivity challenge

### ISSUE THREAD

**Issue by kimoz1994** [freeCodeCamp/freeCodeCamp#14270]
Challenge [Understanding Case Sensitivity in Variables](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables#?solution=%0A%2F%2F%20Declarations%0Avar%20studlyCapVaR%3B%0Avar%20properCamelCase%3B%0Avar%20titleCaseOver%3B%0A%0A%2F%2F%20Assignments%0AstudlyCapVar%20%3D%2010%3B%0AproperCamelCase%20%3D%20%22A%20String%22%3B%0AtitleCaseOver%20%3D%209000%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Declarations
var studlyCapVaR;
var properCamelCase;
var titleCaseOver;

// Assignments
studlyCapVar = 10;
properCamelCase = "A String";
titleCaseOver = 9000;

```

**Comment by JoolsMcFly** [comment]
Hi, challenge is fine.

Check the declaration of `studlyCapVar` and make sure it's in lower case except for each word's first letter.

You can close this issue. Thanks.

**Comment by texas2010** [comment]
@kimoz1994 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
