### ISSUE TITLE
none of the tests are defined

### ISSUE THREAD

**Issue by stevenbarash** [freeCodeCamp/freeCodeCamp#14280]
Challenge [shopping-list](http://beta.freecodecamp.com/en/challenges/basic-javascript/shopping-list) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var myList = [["Canned Beans", 3],["Milk Galon", 1],["Cereal", 2],["Toilet Paper", 12],["Sack of Rice", 1]];



```

**Comment by JoolsMcFly** [comment]
What do you mean b "none of the tests are defined"?

I see this on the left hand side:

>myList should be an array
>
>The first elements in each of your sub-arrays must all be strings
>
>The second elements in each of your sub-arrays must all be numbers
>
>You must have at least 5 items in your list

And I get green with your code.

**Comment by mapedersen** [comment]
Same happens for me. I tried the provided code. I do not get green. Says `var myList = [["Canned Beans", 3],["Milk Galon", 1],["Cereal", 2],["Toilet Paper", 12],["Sack of Rice", 1]];
`
