### ISSUE TITLE
What is wrong ?

### ISSUE THREAD

**Issue by RWaniewski93** [freeCodeCamp/freeCodeCamp#14284]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%20%3D%22I%20am%20a%20%5C%22double%20quoted%5C%22%20string%20inside%20%5C%22double%20quoted%5C%22.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr ="I am a \"double quoted\" string inside \"double quoted\".";



```

**Comment by paramoshkinandrew** [comment]
You should change your text to "I am a \"double quoted\" string inside \"double quote**s**\"."

**Comment by RWaniewski93** [comment]
Thanks dude.

**Comment by fatbacker** [comment]
In your process of teaching you should at least tell people that spacing between quotes is important. It gives us something to look for when we get an error.
