### ISSUE TITLE
This code passes, but I don't think it should.

### ISSUE THREAD

**Issue by dennis-wolfers** [freeCodeCamp/freeCodeCamp#14289]
Challenge [Map the Debris](https://www.freecodecamp.com/challenges/map-the-debris#?solution=function%20findPeriod(avgAlt)%20%7B%0A%20%20var%20GM%20%3D%20398600.4418%2C%0A%20%20%20%20%20%20earthRadius%20%3D%206367.4447%2C%0A%20%20%20%20%20%20distFromMiddleEarth%20%3D%20earthRadius%20%2B%20avgAlt%2C%0A%20%20%20%20%20%20dme3%20%3D%20Math.pow(distFromMiddleEarth%2C3)%2C%0A%20%20%20%20%20%20dme3overGM%20%3D%20dme3%20%2F%20GM%3B%0A%20%20%0A%20%20return%202%20*%20Math.PI%20*%20Math.sqrt(dme3overGM)%3B%0A%7D%0Afunction%20orbitalPeriod(arr)%20%7B%0A%20%20var%20i%2C%20arrLen%20%3D%20arr.length%3B%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%20arrLen%3B%20i%2B%2B)%20%7B%0A%20%20%20%20arr%5Bi%5D.orbitalPeriod%20%3D%20Math.round(findPeriod(arr%5Bi%5D.avgAlt))%3B%0A%20%20%20%20delete%20arr%5Bi%5D.avgAlt%3B%0A%20%20%7D%0A%20%20return%20arr%3B%0A%7D%0A%0AorbitalPeriod(%5B%7Bname%20%3A%20%22sputnik%22%2C%20avgAlt%20%3A%2035873.5553%7D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36 OPR/44.0.2510.857</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Perhaps I am being pedantic, but the instructions say to 'return a new array', yet my code mutates the passed-in array, and returns it. Shouldn't the tests disallow this?

BTW, this is my first-ever issue report, so be kind to me if it's inappropriate.

My code:
```javascript
function findPeriod(avgAlt) {
  var GM = 398600.4418,
      earthRadius = 6367.4447,
      distFromMiddleEarth = earthRadius + avgAlt,
      dme3 = Math.pow(distFromMiddleEarth,3),
      dme3overGM = dme3 / GM;
  
  return 2 * Math.PI * Math.sqrt(dme3overGM);
}
function orbitalPeriod(arr) {
  var i, arrLen = arr.length;
  for (i = 0; i < arrLen; i++) {
    arr[i].orbitalPeriod = Math.round(findPeriod(arr[i].avgAlt));
    delete arr[i].avgAlt;
  }
  return arr;
}

orbitalPeriod([{name : "sputnik", avgAlt : 35873.5553}]);

```

**Comment by erictleung** [comment]
@dennis-wolfers thanks for the issue and feedback! Our challenges are to teach concepts and how to program. Whether it is good practice or not to modify your input parameters is another discussion :smile:  So I don't think there are any issues with mutating the passed-in array for this particular challenge, especially when the purpose of this challenge is to combine a lot of mathematical concepts you've learned. Happy coding!
