### ISSUE TITLE
Find the Length Issue

### ISSUE THREAD

**Issue by YuriiPuzikov** [freeCodeCamp/freeCodeCamp#14296]
Challenge [Find the Length of a String](https://www.freecodecamp.com/challenges/find-the-length-of-a-string) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var firstNameLength = 0;
var firstName = "Ada";

firstNameLength = firstName.length;

// Setup
var lastNameLength;
var lastName = "Lovelace";

// Only change code below this line.

lastNameLength = lastName.length;





```

**Comment by Manish-Giri** [comment]
@YuriiPuzikov Your code passes for me, can you post a screenshot of the issue at your end?

**Comment by YuriiPuzikov** [comment]
@Manish-Giri Sure
![length issue](https://cloud.githubusercontent.com/assets/25731856/24827628/24c24122-1c56-11e7-9569-eef8e43ac78b.png)

**Comment by Dayfiri** [comment]
@YuriiPuzikov 
Works for me too.
![screenshot from 2017-04-08 17-20-12](https://cloud.githubusercontent.com/assets/16082563/24830113/cd7a9890-1c7f-11e7-9167-c41d57f57ad4.png)

**Comment by texas2010** [comment]
I could see he did change code after write code.  
you are not supposed to touch this line. `var lastNameLength = 0;`

i could see it is `var lastNameLength;` now

so this issue is not valid. because you touch that code.

you need to reset it. then do it again.
