### ISSUE TITLE
Stand in Line poorly written,unespecific.

### ISSUE THREAD

**Issue by dryo98** [freeCodeCamp/freeCodeCamp#14299]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=var%20arr%3D%5B1%2C2%2C3%2C4%2C5%5D%3B%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0Aarr.push(item)%3B%0A%0A%0A%0A%20%20return%20arr.shift()%3B%20%20%2F%2F%20Change%20this%20line%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%206))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var arr=[1,2,3,4,5];
function nextInLine(arr, item) {
  // Your code here
arr.push(item);



  return arr.shift();  // Change this line
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```
the challenge explanation needs to be a tad especific on the lines "Add the number to the end of the array, then remove the first element of array." it's not specifying wether it's talking about the array of "arr" or the arguments , it was extremely hard to understand what exactly the challenge asksed me to do, i had to reach the help chat until someone explained me what array was the challenge referring to.

the way that i approached this was going straight to arr first element, and sent it to the back and then remove the first element of array, WHAT ARRAY? The only array specified here is arr...so i had to ask inside the function to pop(); the first element , but that wasn't the challenge objective, i had to ask and they were telling me that i had to move AN ARGUMENT inside the other, which is a completely different thing and its a completely different objective.

**Comment by Manish-Giri** [comment]
I think the instruction is pretty specific - 
> Write a function nextInLine which takes an array (arr) and a number (item) as arguments. Add the number to the end of the array, then remove the first element of array. 

If we break it down into smaller chunks - 

1. Your function `nextInLine` takes two arguments - `arr` and `item`, the first is an array and the second is a number, as is clearly stated - 
    > which takes an array (arr) and a number (item) as arguments.

2. The first step - 
    > Add the number to the end of the array

     refers to the number `item` being added to the end of the array `arr`, again, both `number` and `arr` 
     are passed as arguments to the function.

3. The second step 
    > then remove the first element of array. 

     again refers to the first element of the array `arr`. 

If you read the [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/pop) for `.pop()` - 
> The pop() method removes the last element from an array and returns that element.

it is the opposite of what the challenge asks (**then remove the first element of array.**).

Personally, if I get stuck on a challenge, I try to re-read the instructions several times and then go through the documentation, eventually, it does click.

**Comment by erictleung** [comment]
I also think the challenge is clear enough, especially when you take a look at the challenge tests. You get a chance to see what is expected and that you get to see what this "array" that is talked about so much. I'll leave this open for others to comment on the perceived imprecision in the instructions.

@dryo98 if you have suggestions on what specific changes to the instructions that would make it more clear, feel free to post your changes and we can consider it.

**Comment by just1witness** [comment]
I think the whole javascript basics section is too obscure so far. The HTML, CSS and Jquery showed results, that really helped conceptualize the functions that are being taught. This section doesn't, so even if I get the solution, I don't understand what it's doing or why. Is it possible to have a dynamic example like the previous lessons?

**Comment by erictleung** [comment]
@just1witness thanks for the feedback. Can you elaborate on what you mean by "have a dynamic example like the previous lessons"? Is there are example dynamic lesson you can point to? Thanks!

**Comment by just1witness** [comment]
Well, for instance in the first, second and third set of lessons there was a smart phone template, and you could see the changes the code you were writing would make in the "website" displayed on the smart phone template. 

For JavaScript it could be like a game that you manipulate or something similar. (one idea I had come to mind is when learning variable, arrays, parameters and such you could have a chicken coop with different colored chickens and numbered nests with varying amounts of eggs in each one. Then you could have people change the chickens colors or the amount of eggs in each nest or other changes to the scene, ext ext.) 

It's just easier to understand if you can see the application of what your doing.
