### ISSUE TITLE
Awful grammatical diction makes this task incoherent as to require task. 

### ISSUE THREAD

**Issue by robobertk** [freeCodeCamp/freeCodeCamp#14306]
Challenge [Quoting Strings with Single Quotes](https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes#?solution=%0Avar%20myStr%20%3D%20%22%3Ca%20href%3D'http%3A%2F%2Fwww.example.com'%20target%3D%22_blank%22%3ELink%3C%2Fa%3E%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
I am trying to decipher what is the intention of this task, thought the grammatical errors within the instruction set make it impossible to determine the correct course of action. 

Further the examples are driven to correctin g a string literal and the task is displaying an a tag, this is not the smartest way to present editing quotations by having students edit web link in practicum. 

My code:
```javascript

var myStr = "<a href='http://www.example.com' target="_blank">Link</a>";



```

**Comment by erictleung** [comment]
@robobertk thanks for the feedback. Yes, we've had many criticisms of this challenge and are trying to make it better. Can you suggest a better way to write out the challenge that makes sense to you? The examples are really different because otherwise, the challenge will require minimal critical thinking, while we strive to give a balance for people to think a little in challenge.

The instructions could be rewritten to be something like

> Change the provided string from using only double quotes and escaped quotes to a string that uses single quotes, without the need to escape any quotes.

**Comment by robobertk** [comment]
While I sympathize with trying to fulfill the need to induce critical
thinking, there is no allusion up to the moment that this is a process
applicable to <a> tag editing or enhancement. Understood that this is what
the course as a whole is about. If not an example worked out ahead of how
this can improve the content, at least more coverage of the syntax. In
truth, I find it more beneficial to work a bit in your course and to refer
back to a similar course I am enrolled in on Udemy where actually learning
the code and proper application of its syntax. Your course seems to cover
features, and a nickel tour of its meaning but very little by means of
detailed instruction. Of course it is a free course and I know that you
operate on donations and that limits the budget for what content can be
brought in to each lesson.
I also know that you get out of lessons what you put in to them, so unless
I apply myself more I will b=not truly benefit from the material.
Just a thought.

**Comment by Bouncey** [comment]
@robobertk 

> I find it more beneficial to work a bit in your course and to refer back to a similar course I am enrolled in on Udemy where actually learning the code and proper application of its syntax. 

We all have our own ways of learning. I myself completed many other courses in a bid to learn JavaScript. I found the coverage of syntax on one hand was more detailed but on the other, very dry fair. The codecademy course I remember, for example, taking me many attempts over many months to complete. Maybe in some part through novice difficulty, but mainly I couldn't stomach the repetitive nature of it all.
freeCodeCamp has never enforced a single path of learning, quite the opposite. In its early days, freeCodeCamp encouraged campers to go to `xyz.com` and complete their course on `foobarbaz`. 

> Your course seems to cover features, and a nickel tour of its meaning but very little by means of
detailed instruction. 

At freeCodeCamp we foster the spirit of `read, search, ask`. Read the instructions again to establish what you need to do to pass the challenge. If nothing comes to mind, Search (google, bing, MDN, W3Schools et al) to find a method/pattern than can help you solve the challenge. And finally if you are still stuck, Ask in one of our `gitter.im` chat rooms. I personally have found this pattern to be very useful in getting a grasp of HTML, CSS and JavaScript, and I have found it very reliable in my own problem solving. 
The reason it is encouraged is, in the 'real world', you are not going to have a 1/3 screen width column with the exact instructions of what to do. Read, search, ask will nearly always get you to where you need to be. I still refer to W3Schools for HTML and CSS. 

> Of course it is a free course and I know that you operate on donations 

freeCodeCamp receives monies through the shop, but that is the extent of 'donations' as such. There is no other way to give money to freeCodeCamp. There is no funding/pledge/sponsorship program in place, and the non-profits that receive bespoke software from 'full stack' campers certainly to not offer a reward, nor are they encouraged to. 
The curriculum and the platform around it has been created, built and edited by people voulenteering their time and hard work, maybe just to 'give something back' to a resource that has enabled them to do so much.

Just to reiterate @erictleung, thank you for raising your concern over the instructions for this challenge. If you have any suggestions for edits, that would be great. If you could raise a PR, that would be amazing! If not then that is no problem at all :+1:

I hope you continue to find value in what we as a community have here and that we can help you on to your goal, whatever it may be.

**Comment by robobertk** [comment]
@Bouncey As a Systems Admin in a small alarm company 911 call center, I do truly get the pains of 'real world' problem solving. My industry, (Alarms and security) is already very small industry with it comes typically small business budget and a small business mindset. I spend the majority of my day researching antiquated 90's telecommunications technology because the advent of VoIP ruining the old days of POTS based alarm delivery. And I do typically reach out to my older or more experienced technicians or counterparts when stumped on something so I admit that the process does work, though you do lose quite a bit of time. 

I found the answer to my question, but it wasn't from any of the reference material cited in this course I think was where the bulk of my agitation came from, seeing as though I came to FCC to learn this. But JavaScript is a pain to many people as I have to understand, so eh whatever.

If anything a link to a common repository for reference in these obscure tasks would be better than nothing. Just my 2 cents.

**Comment by karengeerts** [comment]
I agree that the instructions are really confusing - but once you know the solution, it's hard to come up with a better description. For me it was unclear that what was asked to change the complete string to single quotes, so that the double quotes within the string could remain as they were (and you had to remove the escaping). 

I get the point about critical thinking, but adding a few more lines clarification and/or examples would drastically reduce frustration levels (which is also helpful in trying to learn a new language).

**Comment by systimotic** [comment]
@erictleung Are you still working on this?

**Comment by erictleung** [comment]
@systimotic apparently I got a bit busy the past couple months :sweat_smile: I was planning on trying to reword it and then label this a `first-timers` issue so people can have a go at it. Give me the weekend to look at this again. If I'm unable to make time this weekend, you're free to work on it or anyone else. Thanks for checking in, though!

**Comment by systimotic** [comment]
@erictleung No worries! I know all about getting busy for a couple of months 😅

**Comment by erictleung** [comment]
Here's my rewrite

> `String` values in JavaScript may be written with single or double quotes, as long as you start and end it with the same type of quote. Unlike some other programming languages, single and double quotes work the same in JavaScript.
>
> ```js
> doubleQuoteStr = "This is a string";
> singleQuoteStr = 'This is also a string';
> ```
>
> The reason why you might want to use one type of quote over another is if you want to use both in a string. This might happen if you want to save a conversation in a string and have the conversation in quotes. Another use for it would be saving a `<a>` tag with various attributes in quotes, all within a string.
>
> ```js
> conversation = 'Finn exclaims to Jake, "Algebraic!"';
> ```
>
> However, this becomes a problem if you need to use the outermost quotes within it. Remember, a string has the same kind of quote at the beginning and end. But if you have that same quote somewhere in the middle, the string will stop early and throw an error.
>
> ```
> goodStr = 'Jake asks Finn, "Hey, let\'s go on an adventure?"';
> badStr = 'Finn responds, "Let's go!"'; // Throws an error
> ```
>
> In the `goodStr` above, you can use both quotes safely by using the backslash `\` as an `escape` character.
>
> **Note**
> The backslash `\` should not be be confused with the forward slash `/`. They do not do the same thing.
>
> ### Instructions
> 
> Change the provided string to a string with single quotes at the beginning and end and no escape characters.
>
> Right now, the `<a>` tag in the string uses double quotes everywhere. You will need to change the outer quotes to single quotes so you can remove the escape characters.

The last test can also be changed to say, "Remove the backslashes `\` used to escape quotes.` The "Only" I think makes it confusing. I think this was added because people were removing the forward slashes as well. Hopefully, my addition in the instructions makes it clear these characters are different.

**Comment by shubhshrma** [comment]
Is this up for grabs?If it is,I'd love to work on it.

**Comment by erictleung** [comment]
@shubhshrma yep, it's up for grabs. Feel free to go at it. Let us know if you have any comments or questions on the changes :+1:
