### ISSUE TITLE
Enhancement: Select a previous solution and load the code into the program area on the Bonfire page

### ISSUE THREAD

**Issue by clintoncampbell** [FreeCodeCamp/FreeCodeCamp#1430]
Currently, you go to the portfolio page to copy code. Click the bonfire link. Paste the code and run. 

How about a dropdown that will let you select from your previous solutions to this problem? Bonus if we can get the ability to label multiple versions for easy identification.

**Comment by BerkeleyTrue** [comment]
Done! We will be removing duplicates soon so there will only be one solution for each challenge.

Happy Coding!

**Comment by clintoncampbell** [comment]
Berkeley,
Do we get to choose which solution to keep or is it the last one?
Thanks,
Clinton

**Comment by BerkeleyTrue** [comment]
It will be the last one.

**Comment by clintoncampbell** [comment]
Thanks. In the future, it'd be awesome to choose. Some of my better
solutions are probably going to get wiped out since I'll sometimes
demonstrate various solutions at our Seattle meetup. Either way, it's great
to see the interface continue to evolve.
