### ISSUE TITLE
Example for Javascript calculator is wrong

### ISSUE THREAD

**Issue by hernanmendez** [freeCodeCamp/freeCodeCamp#14309]
Hello, thanks for entering, and i realized that https://codepen.io/freeCodeCamp/full/rLJZrA is wrong, when i 
say 7-9*6 it displays -12 when it should be -47, basic arithmetic... i was trying to solve this when i was doing the challenge but it just seems to be wrong on the example you gave us.

**Comment by hellawindy** [comment]
It's not wrong.
It calculates as you typing, so when you write 7-9 it shows -2 then you write * 6 then the solution is -12 not -47.
Most of the electric calculators used in offices are using the same method.

**Comment by no-stack-dub-sack** [comment]
@hernanmendez thanks for reporting this - I think this issue can be closed for now. It has been raised several times in the past (including by your truly!) and the new example project for the beta curriculum addresses this issue and explains both evaluation types: immediate execution and formula. The new example pen uses formula logic as that seems to be the more common modern calc evaluation logic. 

See the new page with explanation and pen here: http://beta.freecodecamp.com/en/challenges/front-end-frameworks-projects/build-a-javascript-calculator
