### ISSUE TITLE
I cant console.log, neither could see any output whatsoever

### ISSUE THREAD

**Issue by Shantam44** [freeCodeCamp/freeCodeCamp#14316]
Challenge [Find the Longest Word in a String](https://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string#?solution=%0Afunction%20findLongestWord(str)%20%7B%0A%20%20console.log(str)%3B%0A%20%20return%20str.length%3B%0A%7D%0A%0AfindLongestWord(%22The%20quick%20brown%20fox%20jumped%20over%20the%20lazy%20dog%22)%3B%0Aconsole.log(%22no%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function findLongestWord(str) {
  console.log(str);
  return str.length;
}

findLongestWord("The quick brown fox jumped over the lazy dog");
console.log("no");
```

**Comment by Dayfiri** [comment]
@Shantam44 
You can either `reset` your code or you can just remove everything after a function call
```
findLongestWord("The quick brown fox jumped over the lazy dog");
```
should be a last line in code.

**Comment by kartickey** [comment]
press F12 and got to `console` to see the console.log output.
Remove the console.log line after the function is called as when the function is called the return statement is executed which stops the execution process.
" https://i.gyazo.com/e669c2e6ab986d568f8939f0217ce6d2.png " you can see here the code is working fine for me.
