### ISSUE TITLE
Insufficient tests for Sorted Union bonfire

### ISSUE THREAD

**Issue by clintoncampbell** [FreeCodeCamp/FreeCodeCamp#1431]
While reviewing my solution to sorted union, I discovered that it passed even though I had solved for exactly 3 arrays and the problem is a generic 2 or more.

**Comment by SaintPeter** [comment]
Can you provide a code sample?
Can you propose a test to catch your example?

**Comment by clintoncampbell** [comment]
Original solution:

```
function unite(arr1, arr2, arr3) {
  var arr = arr1.concat(arr2, arr3);
  return arr.reduce(function(a,b) {
    if (a.indexOf(b) < 0) {
      a.push(b);
    }
    return a;
  }, []);
}
```

**Comment by clintoncampbell** [comment]
Tests:

```
assert.deepEqual(unite([1, 2, 3], [5, 2, 1]), [1, 2, 3, 5], 'should correctly handle exactly two arguments');

assert.deepEqual(unite([1, 2, 3], [5, 2, 1, 4], [2, 1], [6, 7, 8]), [ 1, 2, 3, 5, 4, 6, 7, 8 ], 'should correctly handle higher numbers of arguments');
```



```

**Comment by SaintPeter** [comment]
Ok, looks good.  I'll see about getting a Pull Request going.

**Comment by clintoncampbell** [comment]
Thanks. I wouldn't necessarily worry about the 4 argument case, but the template code has 3 arguments hardcoded. I just built off of it originally and didn't read the instructions closely.

I'll try to get a dev environment set up so that I can submit my own pull requests soon! ;)

**Comment by SaintPeter** [comment]
Added a pull request with these two tests, see #1432.

Thanks, @clintoncampbell!

BTW, you don't need a full dev environment to test.  Just clone the repo and make your changes.  You can easily submit a Pull Request.  Just be sure to mention in your Pull Request that your change is untested against live.

**Comment by clintoncampbell** [comment]
Thanks for the tip!
