### ISSUE TITLE
Testing Objects for Properties  Test the code is ok 

### ISSUE THREAD

**Issue by bazita** [freeCodeCamp/freeCodeCamp#14328]
Challenge [Testing Objects for Properties](https://www.freecodecamp.com/challenges/testing-objects-for-properties#?solution=%0A%2F%2F%20Setup%0Avar%20myObj%20%3D%20%7B%0A%20%20gift%3A%20%22pony%22%2C%0A%20%20pet%3A%20%22kitten%22%2C%0A%20%20bed%3A%20%22sleigh%22%0A%7D%3B%0A%0Afunction%20checkObj(checkProp)%20%7B%0A%20%20%2F%2F%20Your%20Code%20Here%0A%20%0Aif%20(%20myObj.hasOwnProperty(checkProp))%0A%20%20%20%20%20%20%7Breturn%20myObj%5BcheckProp%5D%20%3B%0A%20%20%20%20%20%20%7D%20else%7B%0A%20%20%20%20%20%20%20%20return%20%22Not%20Found!%22%20%3B%7D%0A%20%0A%20%20%0A%7D%0A%0A%2F%2F%20Test%20your%20code%20by%20modifying%20these%20values%0AcheckObj(%22house%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/57.0.2987.98 Chrome/57.0.2987.98 Safari/537.36</code>.
 i Test my code is ok working , but i can't move up

My code:
```javascript

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
 
if ( myObj.hasOwnProperty(checkProp))
      {return myObj[checkProp] ;
      } else{
        return "Not Found!" ;}
 
  
}

// Test your code by modifying these values
checkObj("house");

```

**Comment by Marmiz** [comment]
@bazita thanks for reporting this issue, however you overshadowed a tiny detail:

the system expect, in case a prop is not found a returned value of:
```
Not Found
```
While you return:
```
Not Found!
```

As you can see the two strings are not identical, yours has an extra `!`, that makes them in fact different thus the test failing.

You could have it easily spotted by the failing checkmark on the following test case:
`checkObj("house") should return "Not Found".`

Next time I suggest you asking for help in one of the [Official Chat Room](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390)

Happy coding 👍

**Comment by dhcodes** [comment]
Thanks @Marmiz Closing as resolved
