### ISSUE TITLE
beta fcc (Basic CSS: Use CSS Selectors to Style Elements)

### ISSUE THREAD

**Issue by indefinite0212** [freeCodeCamp/freeCodeCamp#14325]
Challenge [use-css-selectors-to-style-elements](https://beta.freecodecamp.com/en/challenges/basic-css/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
it keeps telling me that "your h2 element should be blue" , but as you look in the screenshot it is color blue :) 

```html

<style>
  h2{color:blue;}
</style>
<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

![bug](https://cloud.githubusercontent.com/assets/26141499/24843265/c405174a-1dd3-11e7-85b5-684ca0a25692.png)

**Comment by Margaret2** [comment]
It works for me on Vivaldi: 
![working](https://files.gitter.im/FreeCodeCamp/Help/6tig/1dee5a2d-7670-438e-9fbd-61861beb8f38.png)

but he also showed this one of it not working on Firefox: 
![](https://files.gitter.im/FreeCodeCamp/Help/k0Mr/pic.png)

**Comment by systimotic** [comment]
Hi! Thank you for reporting this issue.

This is a known issue with CSS tests in Firefox and is being discussed in #10749
I'm closing this as a duplicate. Happy coding!

**Comment by m0n411111** [comment]
HI. I just had this issue and the solution was to remove my uBlock Origin extension from the browser. Hope this helps anyone else.
