### ISSUE TITLE
Identifier dataset has already been declared

### ISSUE THREAD

**Issue by Rushyendher** [freeCodeCamp/freeCodeCamp#14329]
Challenge [change-styles-based-on-data](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/change-styles-based-on-data) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**When I run the test cases after I wrote the code, It says "identifier dataset has already been declared". When I comment the dataset variable in script tag it worked.**

```html


<body>
  <script>
    const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
    
    d3.select("body").selectAll("h2")
      .data(dataset)
      .enter()
      .append("h2")
      .text((d) => (d + " USD"))
      // Add your code below this line
      
      
      
      // Add your code above this line
  </script>
</body>

```

**Comment by AbsoluteZero273** [comment]
I add this same issue on chrome. But after refreshing, it worked.

**Comment by systimotic** [comment]
Hi! Thanks for reporting and looking into this issue.

This is a known issue. We're working on resolving it through #12762. I'm closing this as a duplicate.

Happy coding!
