### ISSUE TITLE
Progress lost on beta.freeCodeCamp.com when I link my email

### ISSUE THREAD

**Issue by mboultoureau** [freeCodeCamp/freeCodeCamp#14336]
#### Issue Description

It's exactly the same [problem at this issue.](https://github.com/freeCodeCamp/freeCodeCamp/issues/13462)

1. I decided to link my email in settings. (I login with my Github account)
2. After submitting the form I got an email from freecodecamp for verification.
3. On clicking the verification link I was redirected to the main site of freecodecamp ie https://www.freecodecamp.com instead of the beta site http://beta.freecodecamp.com
and I got an error message "Oops, something went wrong, please try again later" on https://www.freecodecamp.com.
4. When I came back to the beta site i.e http://beta.freecodecamp.com there the email setting section of the setting page my email address was already linked
5. And I noticed that I had only 1 brownie point. When I checked my public profile I found out that all my solved challenges were wiped out completely.

My FreeCodeCamp's account (freecodecamp.com not beta.freecodecamp.com) has not affected.

May I get back my progress?

**Comment by erictleung** [comment]
@mboultoureau thanks for the issue and sorry to hear you're having issues. If you're having the exact same issue as the other, I'll close this one as a duplicate. As it was mentioned there, the beta site is unstable so bugs like this are inevitable. Please continue the discussion in https://github.com/freeCodeCamp/freeCodeCamp/issues/13462. Happy coding!
