### ISSUE TITLE
Complain about challange(fill in the blank with placeholder text)

### ISSUE THREAD

**Issue by Emmanx** [freeCodeCamp/freeCodeCamp#14332]
Did everything right but i'm failing the tests ...didn't have this issue with the standard version just in the beta
Challenge [fill-in-the-blank-with-placeholder-text](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/fill-in-the-blank-with-placeholder-text) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p> Kitty ipsum dolor sit amet, shed everywhere </p>

```

**Comment by dhcodes** [comment]
@Emmanx your code seems to work on my end. I suspect this may be an issue with the test in Firefox. Could you try it in Chrome and report back?

**Comment by Emmanx** [comment]
OK yes I'm using Firefox let me try Chrome. Mr Quincy recommended the new updated beta curriculum.. Is the beta ready for use please.

**Comment by Emmanx** [comment]
I'm having issues using the beta I keep getting this message : Something Went Wrong Please Try Again Later
