### ISSUE TITLE
Scrolling Issue

### ISSUE THREAD

**Issue by stueycidegh** [freeCodeCamp/freeCodeCamp#14333]
Challenge [Add Placeholder Text to a Text Field](https://www.freecodecamp.com/challenges/add-placeholder-text-to-a-text-field) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/57.0.2987.98 Chrome/57.0.2987.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<input type="text">

```

When trying to scroll past <li>Other cats</li> the cursor doesn't progress, I cannot click on the lines after it nor use the arrow keys.

If I hit reset and continue it works for that challenge then the issue reappears.

**Comment by williampmills** [comment]
I have often had issues with the cursor not 'working' right. It seems like it's moving through the line 2 lines above where it show. Makes editing very difficult at times.

I just refresh the page, and it goes away. Only happens every 10 or so pages.

**Comment by OFFLlNE** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #7847, so I am closing it as a duplicate.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
