### ISSUE TITLE
Pass any Bonfire with malformed code.

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/freecodecamp#1433]
User @david-romnski pointed out that if you add the following line of code to the end of any bonfire, all tests pass:
```javascript
if (null) console.log(1);
```

I was able to reproduce this behavior on a bunch of different Bonfires.  I can't figure out what specifically is going on.  It appears to have something to do with the if(null), but it only fails if there is a console.log statement after it.  If you use curly braces it doesn't do it.

Very odd.

![image](https://cloud.githubusercontent.com/assets/553494/9020310/87370b86-37b9-11e5-90d7-523223063207.png)

**Comment by BerkeleyTrue** [comment]
hmmm... a very specific behavior. Not sure it's worth fixing. 

Bonfires will be updated to use react in near future(its low on the list...) and hopefully it will take care of any oddities due to the use of eval and polluting global namespace.

**Comment by SaintPeter** [comment]
I'm just concerned that there is some sort of "leak" that could cause other issues.  It's possible that there are other symptoms tied to this same issue and if it could be understood we might fix other less esoteric issues.  That it is easily repeatable makes it potentially fixable.

**Comment by misterrorypond** [comment]
The major feature of this site is the work-at-your-own-pace schedule and accountability seems to be an essential part of that - if people use that section of code to just plow through bonfires if they don't understand, I feel people won't learn as well.

**Comment by michael-krebs** [comment]
Even if this issue were fixed, it would still be very easy to cheat at bonfires by copying other campers' solutions.

**Comment by benmcmahon100** [comment]
Just added a script to block this issue but like @michael-krebs pointed out cheating can never really be eliminated but it can and will mar people's chances on non-profits if it's discovered that they have no idea what they are doing from copying other people's work
