### ISSUE TITLE
Accepting wrong output

### ISSUE THREAD

**Issue by arunvkumr** [freeCodeCamp/freeCodeCamp#14334]
Challenge [Wherefore art thou](https://www.freecodecamp.com/challenges/wherefore-art-thou) has an issue.

User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.

Please describe how to reproduce this issue, and include links to screenshots if possible.

This is the code i wrote, the correct output should be `[{ "a": 1, "b": 2, "c": 2 }]`, but my code produces output `[ { b: 2 }, { a: 1, b: 2, c: 2 } ]` which is being accepted.

My code:
```javascript

function whatIsInAName(collection, source) {
  var keys = Object.keys(source);
  var arr = collection.filter(function(obj){
      for(var i = 0; i < keys.length; ++i)
        if(obj.hasOwnProperty(keys[i]) && obj[keys[i]] === source[keys[i]] && i == keys.length - 1)
        return true;
  });
  return arr;
}

whatIsInAName([{"b": 2 }, { "a": 1 }, { "a": 1, "b": 2, "c": 2 }], { "a": 1, "b": 2 });

```

**Comment by augmt** [comment]
Similar to #14057.

Tests for this challenge are too lenient on the main site but they're more robust in the beta.

**Comment by erictleung** [comment]
@arunvkumr thanks for the issue and apologies it's taken so long to get to your issue. This does pass in the production live site, but it doesn't on the beta site (http://beta.freecodecamp.com/en/challenges/intermediate-algorithm-scripting/wherefore-art-thou). So this doesn't seem to be an issue anymore so I'll be closing this issue. If you still think it's an issue, feel free to comment back. Happy coding!
