### ISSUE TITLE
Error with Instructions for Counting Cards - 196

### ISSUE THREAD

**Issue by Diglio** [freeCodeCamp/freeCodeCamp#14343]
Challenge [Counting Cards](https://www.freecodecamp.com/challenges/counting-cards#?solution=%0Avar%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0Aswitch(card)%7B%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20case%204%3A%0A%20%20%20%20case%205%3A%0A%20%20%20%20case%206%3A%0A%20%20%20%20%20%20count%2B%2B%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%207%3A%0A%20%20%20%20case%208%3A%0A%20%20%20%20case%209%3A%0A%20%20%20%20%20%20count%20%3D%20count%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2010%3A%0A%20%20%20%20case%20%22J%22%3A%0A%20%20%20%20case%20%22Q%22%3A%0A%20%20%20%20case%20%22K%22%3A%0A%20%20%20%20case%20%22A%22%3A%0A%20%20%20%20%20%20count--%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%7D%0A%20%20%0A%20%20if%20(count%20%3E%200)%7B%0A%20%20%20%20return%20%22%5C%22%22%20%2B%20count%20%2B%20%22%20Bet%5C%22%22%3B%0A%20%20%7Delse%0A%20%20%20%20return%20%22%5C%22%22%20%2B%20count%20%2B%20%22%20Hold%5C%22%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(10)%3B%20cc('J')%3B%20cc('Q')%3B%20cc('K')%3B%20cc('A')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The issue isn't so much with getting the proper code, but more-so with the wording of the task. The task tells you that they want a specific output with a "Space" in-between the Count and "Belt" or "Hold" and then they give you the following Example:

Example Output
"-3 Hold"
"5 Bet"

So, when making this (and you can see my code below) I added the "" around my output, thinking that this is what was needed (since I followed the Example). However, after about 30 minutes of re-doing my code and changing methods, I found it was the "" surrounding my answer. 

I might be nitpicking here, but I believe if you show an Example Output, it should be of the actual output, not the output being quoted (throws people like myself off, especially when I thought they were testing to make sure we remember how to use "escapes")

My code:
```javascript

var count = 0;

function cc(card) {
  // Only change code below this line
switch(card){
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      count++;
      break;
    case 7:
    case 8:
    case 9:
      count = count;
      break;
    case 10:
    case "J":
    case "Q":
    case "K":
    case "A":
      count--;
      break;
  }
  
  if (count > 0){
    return "\"" + count + " Bet\"";
  }else
    return "\"" + count + " Hold\"";
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(10); cc('J'); cc('Q'); cc('K'); cc('A');

```

**Comment by erictleung** [comment]
@Diglio thanks for the issue. Your suggestion has been implemented in [the beta site](http://beta.freecodecamp.com/en/challenges/basic-javascript/counting-cards). So I'll be closing this as resolved in the development branch. The update will be pushed to production in the future. Happy coding!
