### ISSUE TITLE
Cant move on after a passing submission.

### ISSUE THREAD

**Issue by bobo-branden** [freeCodeCamp/freeCodeCamp#14349]
Challenge [add-a-submit-button-to-a-form](https://beta.freecodecamp.com/en/challenges/basic-html-and-html5/add-a-submit-button-to-a-form) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.138 Safari/537.36 Vivaldi/1.8.770.56</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
I've had this same issue on multiple challenges in multiple browsers. in dev console it show the following error
<code>
bundle-6def69127e7c8a9d57c0.js:34 TypeError: Cannot read property 'challenges' of undefined
    at h (bundle-6def69127e7c8a9d57c0.js:7)
    at bundle-6def69127e7c8a9d57c0.js:37
    at bundle-6def69127e7c8a9d57c0.js:11
    at n.Ye.FlatMapObservable.n.next (bundle-6def69127e7c8a9d57c0.js:12)
    at n.Ye.internals.AbstractObserver.t.onNext (bundle-6def69127e7c8a9d57c0.js:12)
    at n.<anonymous> (bundle-6def69127e7c8a9d57c0.js:11)
    at t.n.next (bundle-6def69127e7c8a9d57c0.js:15)
    at t.Ye.internals.AbstractObserver.t.onNext (bundle-6def69127e7c8a9d57c0.js:12)
    at r.next (bundle-6def69127e7c8a9d57c0.js:13)
    at r.Ye.internals.AbstractObserver.t.onNext (bundle-6def69127e7c8a9d57c0.js:12)
</code>

This is the first issue i've ever reported. I hope it is helpful. If there is more i should do please let me know.

```html


<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <input type="text" placeholder="cat photo URL">
    <button type="submit">Submit</button>
  </form>
</main>

```

**Comment by bobo-branden** [comment]
Btw. I was told I passed the the challenge. the bug is some between notifying me of passing and sending me to the next challange.

**Comment by erictleung** [comment]
@bobo-branden thanks for the issue. I can't reproduce your error. Your code works for me. I opened the challenge directly with the link in your issue and copy-pasted your code and it passes for me. 

Can you elaborate on "the bug is some between notifying me of passing and sending me to the next challenge? Does it freeze? Is there a message that pops up? Did you just check your dev console? Thanks!

**Comment by raisedadead** [comment]
This could be a issue with build deployed on beta at the time they accessed the challenge.

@bobo-branden Can you report back if you are getting this still? If this is not resolved please let us know in the comments.
