### ISSUE TITLE
Pre-format copied text in code editor for Markdown code display

### ISSUE THREAD

**Issue by noahkiss** [freeCodeCamp/freeCodeCamp#14348]
#### Issue Description

Currently, the Gitter chatrooms have a bunch of unformatted snippets being posted by users who aren't aware/CBA to correctly format their text. This leads to decreased readability and a longer wait time to receive help, and stops questions that involve snippets from standing out.

---

Instead of seeing this:

    function repeatStringNumTimes(str, num) {
      if (num < 0) return '';
      return str.repeat(num);
    }
    
    repeatStringNumTimes("abc", 3);

We see a lot of this:

function repeatStringNumTimes(str, num) {
    if (num < 0) return '';
    return str.repeat(num);
}

repeatStringNumTimes("abc", 3);

---

#### Suggestion

Instead of placing the onus on less experienced users, FCC can do the heavy lifting, leading to an all-around better experience.

Here are some ways I can see doing this:

- Add 4 spaces before every line in the code editor. While this might be the easiest approach, it is, IMO, also error-prone and could make it harder for users to understand how to correctly space/format text for readability.

- Add ` ```\n ` and ` \n``` ` to the beginning and end of the copied text, stripping out any newlines at the front or back of copied text first. This *should* have the most success in correctly formatting the text without affecting the user's experience in the code editor, but I'm sure there are plenty of edge cases where this may not be possible to apply to a user's copied selection. Same goes for adding 4 spaces to the beginning of every line in the copied text, which would probably be even more difficult to handle without errors.

- Add a "copy code" button, utilizing one of the aforementioned methods of adding proper formatting, which might be easier to serve up compared to interacting with a user's clipboard.

- The super fast and easy way which I'm sure alludes me but sticks out to you. (Suggest it below!)

**Comment by erictleung** [comment]
@noahkiss thanks for the suggestion. This would be very convenient to have, but this would probably be a fairly low priority given the current projects fCC is working on right now. Also, another solution *is* to be put the onus on beginners to know how to format their code. You can find the discussion [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/12479). I'll leave this open for others to comment as well.
