### ISSUE TITLE
Inventory update - unexpected token ILLEGAL

### ISSUE THREAD

**Issue by juanpastas** [FreeCodeCamp/freecodecamp#1434]
Challenge http://www.freecodecamp.com/challenges/bonfire-inventory-update has an issue.

I am getting unexpected token ILLEGAL in this challenge with [this code](https://gist.github.com/juanpastas/5e694465eb624f0b9fde).

When I run that on node console I don't get any error.

It's working [here](https://jsbin.com/bozifu/edit?js,console) too.

**Comment by secretofmana** [comment]
https://gist.github.com/juanpastas/5e694465eb624f0b9fde#file-inv-js-L19
https://gist.github.com/juanpastas/5e694465eb624f0b9fde#file-inv-js-L21

those two lines are being mangled to be comments, it's the result of a quick and lazy interpreter i'm guessing

**Comment by juanpastas** [comment]
I also removed c(x) at the end, thanks @secretofmana.

**Comment by juanpastas** [comment]
Here are some tests passing https://jsbin.com/fayezajihi/edit?js,console
