### ISSUE TITLE
For all Challenges,  nothing should appear as output until you run the challenge

### ISSUE THREAD

**Issue by leonardpfs** [freeCodeCamp/freeCodeCamp#14345]
Challenge [Inform with the Paragraph Element](https://www.freecodecamp.com/challenges/inform-with-the-paragraph-element#?solution=%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
<p>Hello Paragraph</p>
```

**Comment by erictleung** [comment]
@leonardpfs thanks for the issue, although I'm not sure this is really a bug on the site. This is more of a suggestion. Nonetheless, you'll be happy to hear that this is how the [beta site works](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/inform-with-the-paragraph-element). I'll close this as resolved in staging. Happy coding!
