### ISSUE TITLE
Escaping Literal Quotes in Strings

### ISSUE THREAD

**Issue by kgatto** [freeCodeCamp/freeCodeCamp#14358]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
 var myStr = "I am a \"double quoted\" string inside \"double quotes\"";

Output on console shows as: 

 var myStr = "I am a \"double quoted\" string inside \"double quotes\"";
 
and error is in grader that shows:


Variable myStr should contain the string: I am a "double quoted" string inside "double quotes".

```

**Comment by texas2010** [comment]
@kgatto 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by fatbacker** [comment]
In your process of teaching you should at least tell people that spacing between quotes is important. It gives us something to look for when we get an error.
