### ISSUE TITLE
Looks like this is a bug

### ISSUE THREAD

**Issue by mrbrackins** [freeCodeCamp/freeCodeCamp#14351]
Challenge [escaping-literal-quotes-in-strings](http://beta.freecodecamp.com/en/challenges/basic-javascript/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js

var myStr = "I am a \"double quoted\" string inside \"double quotes\".";

```

**Comment by mrbrackins** [comment]
Navigated away to create this bug, navigated back and it worked FYI

**Comment by jeremiahlukus** [comment]
So this is fixed? If so please close issue. Thank you

**Comment by vincentpace** [comment]
Same thing happened to me; the answer didn't work, and then I navigated away, navigated back, used the same answer, and then it worked.

**Comment by augmt** [comment]
This is because of #14252: the application is appending a stale tail to the camper's code, causing one of the tests to fail until the camper refreshes the page.

**Comment by fatbacker** [comment]
In your process of teaching you should at least tell people that spacing between quotes is important. It gives us something to look for when we get an error.

**Comment by tanya53** [comment]
this was the same issue as the division with real numbers, the code failed when just nexting from challenge to challenge but passed when I entered the page from the map option, the challenges between these two worked and passed as nexted thru.
