### ISSUE TITLE
[Beta] Animations don't show up in the display screen

### ISSUE THREAD

**Issue by carpben** [freeCodeCamp/freeCodeCamp#14367]
Animation challenges, I get a V, but when hovering over it the animation doesn't show on the display screen. Here are links to both challenges: 

I tried to create in in Codepen, and the animation doesn't show there either when hovering: http://codepen.io/bencarp/pen/GmKVwz

#### Challenge Name

http://beta.freecodecamp.com/en/challenges/applied-visual-design/use-css-animation-to-change-the-hover-state-of-a-button
and also: http://beta.freecodecamp.com/en/challenges/applied-visual-design/learn-how-the-css-keyframes-and-animation-properties-work

#### Browser Information

* Browser Name, Version: latest chrome
* Operating System: windows 10
* Mobile, Desktop, or Tablet: laptop

#### Your Code

I got a V. Here is the code: 
```html

<style>
  button {
    border-radius: 5px;
    color: white;
    background-color: #0F5897;
    padding: 5px 10px 8px 10px;
  }
  button:hover {
    animation-name: background-color;
    animation-duration: 500ms;
    @keyframes background-color{
      100%{
        background-color: #4791d0;
      }
    }
  }
  
  
</style>
<button>Register</button>




```
#### Screenshot
![image](https://cloud.githubusercontent.com/assets/13496178/24946742/2189869c-1f8e-11e7-83ed-0ac8bad79bad.png)

**Comment by augmt** [comment]
@carpben In this case the `keyframes` rule shouldn't be nested in another block as that's an error in regular CSS. Instead `keyframes` should be defined at root level, just like in the example given in the left-hand column.

**Comment by carpben** [comment]
Ok, I understand. However the application did not detect my error, and 'gave' me a 'V'.

**Comment by augmt** [comment]
The application only uses regex to check the code for this challenge. So long as the code string matches what the tests are looking for, the tests will pass.

I just mentioned this issue in the [contributors room](https://gitter.im/FreeCodeCamp/Contributors) to see what others think.
