### ISSUE TITLE
http://catphotoapp.com is a domain-squatting landing page

### ISSUE THREAD

**Issue by ChessyPig** [FreeCodeCamp/FreeCodeCamp#1436]
http://www.freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements instructs you to create a link to http://catphotoapp.com - which is one of those obnoxious 'sit on a domain and fill it with vaguely relevant ads' pages.

It would be better to use a link to a site FreeCodeCamp controls - while this has a fairly innocuous set of cat ads at the moment, it could change at any time to something even less pleasant.

**Comment by ahstro** [comment]
This was already sort of brought up in #1127, but yes, great idea.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
