### ISSUE TITLE
last sentence of explanation should be changed to " For example  body {     background-color: #000000;   } ".

### ISSUE THREAD

**Issue by kcsali** [freeCodeCamp/freeCodeCamp#14369]
Challenge [Use Hex Code for Specific Colors](https://www.freecodecamp.com/challenges/use-hex-code-for-specific-colors#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20%23000000%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: #000000;
  }
</style>

```
instead of 

"For example 
body { color: #000000; }"

in last paragraph

**Comment by Manish-Giri** [comment]
@kcsali Do you mean the last test?
> Use the hex code for the color black instead of the word black. For example body { color: #000000; }

This test is using the `color` property to show the usage of hex values. If we change that to `background-color`, that would just give away the answer.

**Comment by texas2010** [comment]
I agreed with @Manish-Giri.
> This test is using the `color` property to show the usage of hex values. If we change that to `background-color`, that would just give away the answer.


That challenge talking about hex code.  So we don't need to change example code. they show you how to use hex code in color or background-color.
