### ISSUE TITLE
Code Editor - Can't type at first / random cursor

### ISSUE THREAD

**Issue by CalebBassham** [freeCodeCamp/freeCodeCamp#14363]
#### Challenge Name
All of them

#### Issue Description
When you first load the editor you can't type on some lines and when you do start typing it moves the cursor somewhere different. This only happens once for every time you load a page.

#### Browser Information
I am using the latest version of chrome

* Browser Name, Version: Chrome
* Operating System: Windows 8
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```

**Comment by hugocueva** [comment]
Hi, I have the same problem, you have to put the cursor there and then press Enter, it moves one line and then you can write on the right place.

**Comment by CalebBassham** [comment]
I know it it just very annoying every time @hugocueva

**Comment by paswift** [comment]
I'm having the same problem.  I'm currently working on the HTML5 challenges.  I find that each time I move to the next challenge, I have to use "Reset" before I can accurately place the cursor in the HTML code, using either the mouse or the arrow keys. It's really annoying.

Browser:  Chrome (latest)
Operating System: MAC OS 10.11.6
Laptop

**Comment by KLAYZEN** [comment]
Same issue here.  Clicking Reset is the best way to do get around this initially, but it certainly slows the whole process down.

Mozilla Firefox 52.0.2
Windows 10 Pro 1607

**Comment by OFFLlNE** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #7847, so I am closing it as a duplicate.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by paswift** [comment]
@OFFLlNE Hi. I checked Issue #7847. The last comment made on that issue is dated 1/3/2017 and indicates that the issue has been fixed in your staging environment and will be live "soon".  So that was more than 4 months ago. Comments are now closed for issue #7847.  Do you know when the fix for issue #7847 will appear in production? Thanks.
