### ISSUE TITLE
Weather API blocked by browser same site policy Cross Origin Requests are blocked 

### ISSUE THREAD

**Issue by TinCan-Assassin** [freeCodeCamp/freeCodeCamp#14368]
Challenge [Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

When attempting to get api data from the Dark Sky api, my console gave me the error:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.darksky.net/forecast/4e89410595440da20734ab1c6355896f/undefined,-undefined. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

'undefined, - undefined' is the latitude and longitude I attempted to capture in an array for varying location purposes.

![screenshot from 2017-04-12 07-00-10](https://cloud.githubusercontent.com/assets/19189392/24954524/ca52d94a-1f4d-11e7-9cfd-848177b5db64.png)

**Comment by dhcodes** [comment]
@TinCan-Assassin try some of the solutions here: https://forum.freecodecamp.com/t/having-trouble-getting-response-from-dark-sky-api/100653/5 and see if one works for you. Also, try asking in the chat room as there are some who have had similar issues who would be happy to help.

**Comment by Pominaus** [comment]
Could you add the https://cors-anywhere.herokuapp.com/ workaround to the zipline instructions, or remove the recommendation to use dark sky with codepen please? I just lost 3 hours googling this problem only to find it's already been reported and ignored.
