### ISSUE TITLE
Turning h2 blue is not letting me pass the challenge even though I have turned h2 element blue

### ISSUE THREAD

**Issue by ryanmaddox** [freeCodeCamp/freeCodeCamp#14371]
Challenge [use-css-selectors-to-style-elements](http://beta.freecodecamp.com/en/challenges/basic-css/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html

<style>
  h2 {
    color: blue;
  }
</style>
<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

**Comment by erictleung** [comment]
@ryanmaddox thanks for the issue. Using the code you've provided above, I am able to pass the challenge and continue on to the next challenge. Can you explain more how you're unable to move on? Do you get green check marks for the challenge tests?

**Comment by ryanmaddox** [comment]
I was using Firefox and thought I was in chrome.  I'm going through the
beta fcc and once I complete I would like to get involved more with fcc
maybe doing videos or something anything fcc needs.  Fcc has helped me
focus my knowledge and applying technology

**Comment by darrylmorley** [comment]
Snap, using Firefox and have the same issue.

**Comment by systimotic** [comment]
Hi! Thank you for reporting this issue.

This is a known issue with CSS tests in Firefox, only in the beta. We're discussing this problem in #10749
I'm closing this as a duplicate. Happy coding!
