### ISSUE TITLE
Can't move 

### ISSUE THREAD

**Issue by barkinet** [freeCodeCamp/freeCodeCamp#14375]
Challenge [Store Multiple Values in one Variable using JavaScript Arrays](https://www.freecodecamp.com/challenges/store-multiple-values-in-one-variable-using-javascript-arrays#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B%22John%22%2C%2023%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20myArray%20%3D%20%5B%22BARKI%22%2C%20%2241%22%5D%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.2 (KHTML, like Gecko) Mobile/14F5075a</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArray = ["John", 23];

// Only change code below this line.
var myArray = ["BARKI", "41"];


```

**Comment by barkinet** [comment]
Done

**Comment by texas2010** [comment]
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.
