### ISSUE TITLE
Screenhero Link

### ISSUE THREAD

**Issue by seanr707** [FreeCodeCamp/FreeCodeCamp#1437]
ScreenHero link takes new users to their site, which is closed, causing confusion. Needs to be changed to Free Code Camps's ScreenHero link.

**Comment by BerkeleyTrue** [comment]
Which link are you referring to? Can you paste the url here?

**Comment by seanr707** [comment]
It was on

/challenges/waypoint-pair-program-on-bonfires

But the link now directs me directly to the executable. Before it was
taking the user to Screen hero's websites, telling users that they needed
an invite to download, causing a flood of messages on gitter.

Thanks,
Sean
