### ISSUE TITLE
[BETA] : Tests are not passing for the last 5 challenges in ES6.

### ISSUE THREAD

**Issue by shashank7200** [freeCodeCamp/freeCodeCamp#14372]
Challenge [understand-the-differences-between-import-and-require](http://beta.freecodecamp.com/en/challenges/es6/understand-the-differences-between-import-and-require) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36</code>.

**Last 5** challenges including this of **ES6** topic are not **passing** tests.

```js

import { capitalizeString } from "string_functions";

capitalizeString("hello!");
```

**Comment by augmt** [comment]
Similar to #12913.

From that same issue:

> While `export` is valid es.next syntax, it is currently unsupported by all browsers. The reason for this is that while the syntax has entered the spec, the actual importing of those files has not been defined yet.

**Comment by terakilobyte** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/es6.json#L736

This test is brittle and needs to be fixed.

**Comment by carpben** [comment]
I faced the same problem in the http://beta.freecodecamp.com/en/challenges/es6/understand-the-differences-between-import-and-require. 
Here is my JS: 
```js

import { capitalizeString } from "string_functions"
capitalizeString("hello!");

```
My JS did not pass. Interestingly I was instructed to use the import syntax, but the error message was about the 'require' function: 
![image](https://cloud.githubusercontent.com/assets/13496178/25417456/74e681ec-2a6e-11e7-9dfb-2fb0e15429f9.png)

**Comment by rodrigo-fontes** [comment]
Same thing here. 

`import { capitalizeString } from "string_functions";
capitalizeString("hello!");`

**Comment by traanhn** [comment]
I've got the same problem 
import { capitalizeString } from "string_functions"
capitalizeString("hello!");

The test showed errors

**Comment by porcoespinho** [comment]
Same here. My JS did not pass. Interestingly I was instructed to use the import syntax, but the error message was about the 'require' function:

**Comment by geomoetric** [comment]
These 5 questions remain broken as of July 1st 2017, hoping for any updates as a mere camper

**Comment by shashank7200** [comment]
I would love to fix these, but currently don't know where to start from.

**Comment by systimotic** [comment]
Hi everybody! Thanks for reporting and looking into this issue.

We're working on fixing the ES6 challenges in #12698. I'm closing this issue in favor of that.

Happy coding!
