### ISSUE TITLE
4 4

### ISSUE THREAD

**Issue by barkinet** [freeCodeCamp/freeCodeCamp#14376]
Challenge [Access MultiDimensional Arrays With Indexes](https://www.freecodecamp.com/challenges/access-multidimensional-arrays-with-indexes#?solution=%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B1%2C2%2C3%5D%2C%20%5B4%2C5%2C6%5D%2C%20%5B7%2C8%2C9%5D%2C%20%5B%5B10%2C11%2C12%5D%2C%2013%2C%2014%5D%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20myData%20%3D%20myArray%5B0%5D%5B0%5D%3B%0AmyData%20%3D%204%20%2B%204%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.2 (KHTML, like Gecko) Mobile/14F5075a</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myArray = [[1,2,3], [4,5,6], [7,8,9], [[10,11,12], 13, 14]];

// Only change code below this line.
var myData = myArray[0][0];
myData = 4 + 4;
```

**Comment by barkinet** [comment]
Well done

**Comment by texas2010** [comment]
@barkinet, Please stop show solution to people on this issue.  and Please stop open issue for ask help.
GitHub Issues are for reporting bugs on the website only.
