### ISSUE TITLE
Change Text Inside an Element Using jQuery not working with variable.

### ISSUE THREAD

**Issue by TobiasBreuer** [freeCodeCamp/freeCodeCamp#14370]
Challenge [Change Text Inside an Element Using jQuery](https://www.freecodecamp.com/challenges/change-text-inside-an-element-using-jquery#?solution=%0Afccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22%23target1%22).css(%22color%22%2C%20%22red%22)%3B%0A%20%20%20%20var%20targetBtn%20%3D%20%24(%22%23target4%22)%3B%0A%20%20%20%20targetBtn.html(%22%3Cem%3E%22%20%2B%20targetBtn.text()%20%2B%20%22%3C%2Fem%3E%22)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.

When it is said, to emphasize the text of a target, and in the description it is said how to get the text, I would assume that something like below would work. I assumed what happens if I don't know the text or maybe somewhere else the text is changed so I avoid hardcoding the text \#target4 into the script but rather get it from the element. In order to avoid retrieving the element twice via the query selector I save the button and use the jQuery methods html() and text().

The outcome of the solution is correct but it is not accepted. Actually every check passes except for the last one: Make sure to select button id="target4" with jQuery.

When not using a variable but instead writing

```html
$("#target4").html("<em>" + $("#target4").text() + "</em>");
```
everything works.

My code:
```html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    var targetBtn = $("#target4");
    targetBtn.html("<em>" + targetBtn.text() + "</em>");
  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by JoolsMcFly** [comment]
Behind the scenes FCC checks if you are calling `$('#target4').html()` or `$("#target4").html()` so
```js
$('#target4').html("<em>" + targetBtn.text() + "</em>");
```
works.

I agree your solution should work though.

Based on regexp in use this is valid in `staging` branch too:
```js
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").html("<em>" + $("#target4").text() + "</i>"); // <em></i>!
    $('h4:first').text("FAIL"); //test "Do not alter any other text." still passes
    $('h4:eq(1)').text("SECOND FAIL");
  });
</script>
```

I can make a PR to fix `<em></i>' and `Do not alter any other text` tests in `staging` branch.
However, allowing caching like OP did could be trickier but doable I guess.

What do you think @freeCodeCamp/moderators ?

**Comment by ninsiimagerald** [comment]
+1
