### ISSUE TITLE
Waypoint 39 - Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by imwithsam** [FreeCodeCamp/freecodecamp#1438]
Waypoint: Add Placeholder Text to a Text Field (39) displays "Cannot read property 'match' of undefined" for the second goal until the placeholder attribute is added to the input element.

Instead, it should display "Set the value of your placeholder attribute to 'cat photo URL'." from the beginning.

**Comment by ahstro** [comment]
This seems to have been fixed in [beta](http://beta.freecodecamp.com/challenges/waypoint-add-placeholder-text-to-a-text-field). Please close :)
