### ISSUE TITLE
Update Gitter challenge copy to make it clear campers should sign in with GitHub (and not Twitter)

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#14383]
#### Challenge Name
https://www.freecodecamp.com/challenges/create-a-github-account-and-join-our-chat-rooms

#### Issue Description
Gitter recently introduced Twitter authentication. In our Gitter rooms, we force campers to be signed into Gitter with GitHub (and not Twitter). So we need to update the copy in this challenge to clarify that they should use GitHub - and not Twitter - to create their Gitter account.

Here's the current copy:

![create_a_github_account_and_join_our_chat_rooms___free_code_camp](https://cloud.githubusercontent.com/assets/985197/24990820/32f4676e-1fdc-11e7-8b42-39e93b981587.png)

This challenge is located within a JSON file within /seed/challenges

**Comment by gionaufal** [comment]
I would like to do this one!

**Comment by dhcodes** [comment]
@gionaufal checkout https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md

and if you have any questions, ask them in the [Gitter Contributors chat room](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by gionaufal** [comment]
Do you think this is clear enough? 
"Now you can join our main chat room by loggin in with your GitHub account. Please do not use Twitter to sign in. Introduce yourself by saying \"Hello world!\" Tell your fellow campers how you found freeCodeCamp. Also tell us why you want to learn to code."

**Comment by Survivor75** [comment]
Hey, guys I am new here to FCC. I have forked the project and installed it locally.
I wouldlike to contribute to this issue.

**Comment by Survivor75** [comment]
I have added the new information as a note :
"Now that you have a GitHub account, you can join our main chat room by logging in with GitHub. Introduce yourself by saying \"Hello world!\" Tell your fellow campers how you found Free Code Camp. Also tell us why you want to learn to code.
Note : Gitter offers Sign in using both Github and Twitter. It is recommended to campers to use Github as the sign in option.",

**Comment by dhcodes** [comment]
@Survivor75 @gionaufal Looks like this has an open PR now so it can likely be considered as taken up. You can sort issues for the tag "Help Wanted" to look for other issues that need resolution.

@MeamonB In the future, please communicate in the issue thread before taking up an issue. @gionaufal was already working on this and was simply waiting for feedback from a mod.

**Comment by MeamonB** [comment]
My apologies. I will remember to communicate in the issue thread for the future!

**Comment by gionaufal** [comment]
Guys, just FYI, not that my opinion matters a lot: I was really frustrated to see this PR approved, exactly with my proposed change. I will be faster in the future, but this was a bad first experience trying to contribute to FCC.

**Comment by dhcodes** [comment]
@gionaufal I understand that; My apologies. I'll pass along your feedback to the rest of the team.
