### ISSUE TITLE
After entering the code as the lesson describes I receive a dead page symbol; once i run tests it is non responsive

### ISSUE THREAD

**Issue by Marlod1** [freeCodeCamp/freeCodeCamp#14382]
Challenge [Learn how Script Tags and Document Ready Work](https://www.freecodecamp.com/challenges/learn-how-script-tags-and-document-ready-work#?solution=fccss%20%24(document).ready(function()%7B%0A%20%20%20%20%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20Only%20change%20code%20above%20this%20line.%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20btn-default%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script> $(document).ready(function(){
});
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by BeeMcGee** [comment]
I am having this same issue, or something similar.  Although I enter the code, as prompted, it doesn't accept it.  Here's a screenshot of what I get after I press "Run Tests": 
![image](https://cloud.githubusercontent.com/assets/26370422/24987871/1e617a6e-1fb7-11e7-8901-d043aff98667.png)

**Comment by Nickofthewoods** [comment]
I'm getting the same issue as @BeeMcGee

**Comment by BeeMcGee** [comment]
Marlod1 and Nick, glad to know I'm not the only one! Was going crazy trying to figure out what I did wrong...

**Comment by Nickofthewoods** [comment]
@BeeMcGee - You aren't crazy!

**Comment by BeeMcGee** [comment]
@Nickofthewoods - Thank you!  Hopefully, at least not because of this, anyways.  :-)

**Comment by g30v** [comment]
I had this problem - [a hard refresh cleared the issue](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache)

**Comment by BeeMcGee** [comment]
thanks @g30v , that worked!

**Comment by AyaanM** [comment]
I'm having the same problem.

**Comment by nanutza** [comment]
This issue only happens with Chrome. Using Safari was working fine. @g30v hard refresh solution fixed the problem.

<img width="851" alt="screen shot 2017-04-17 at 1 09 00 am" src="https://cloud.githubusercontent.com/assets/19164798/25080079/defd79d4-230f-11e7-9207-b4d1cb2d701e.png">

**Comment by nitreg** [comment]
thanks @g30v that worked for me! ctr+r refreshed the page, then put the code back in. the preview said i had a syntax error for some reason but it still accepted my code to complete the challenge

**Comment by SamIsRad** [comment]
CTRL + F5  to refresh worked for me.

**Comment by Ziron99** [comment]
Had same problem, CTRL + F5 also worked for me.
