### ISSUE TITLE
Falsy Bouncer - Possible bug

### ISSUE THREAD

**Issue by esclavosoy** [freeCodeCamp/freeCodeCamp#14389]
Challenge [Falsy Bouncer](https://www.freecodecamp.com/challenges/falsy-bouncer#?solution=var%20trueArray%20%3D%20%5B%5D%3B%0A%0Afunction%20bouncer(arr)%20%7B%0A%20%20%2F%2F%20Don't%20show%20a%20false%20ID%20to%20this%20bouncer.%0A%20%20for%20(x%20%3D%200%3B%20x%20%3C%20arr.length%3B%20x%2B%2B)%7B%0A%20%20%20%20if%20(Boolean(arr%5Bx%5D)%20%3D%3D%3D%20true)%7B%0A%20%20%20%20%20%20trueArray.push(arr%5Bx%5D)%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20return%20trueArray%3B%0A%7D%0A%0Abouncer(%5B1%2C%20null%2C%20NaN%2C%202%2C%20undefined%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 9202.60.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.137 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
My code returns what it is expected to return but it still doesn't pass.

My code:
```javascript
var trueArray = [];

function bouncer(arr) {
  // Don't show a false ID to this bouncer.
  for (x = 0; x < arr.length; x++){
    if (Boolean(arr[x]) === true){
      trueArray.push(arr[x]);
    }
  }

  return trueArray;
}

bouncer([1, null, NaN, 2, undefined]);

```

**Comment by erictleung** [comment]
@esclavosoy thanks for the issue. Move your global variable into your function and it'll pass. Challenge tests run your function each time. Global variables will change with each call of your function. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
