### ISSUE TITLE
Correct output but not recognized by the Website\

### ISSUE THREAD

**Issue by TilakMaddy** [freeCodeCamp/freeCodeCamp#14384]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Afunction%20titleCase(str)%20%7B%0A%20%20%0A%20%20str%20%3D%20str.toLowerCase()%3B%0A%20%20var%20words%20%3D%20str.split(%22%20%22)%3B%0A%20%20var%20sentence%20%3D%20%22%22%3B%0A%20%20%0A%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20words.length%3Bi%2B%2B)%7B%0A%20%20%20%20%0A%20%20%20%20var%20word%20%3D%20words%5Bi%5D%3B%0A%20%20%20%20word%20%3D%20String(word.charAt(0)).toUpperCase()%20%2B%20word.substring(1)%3B%0A%20%20%20%20sentence%20%2B%3D%20word%20%2B%20%22%20%22%3B%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20return%20(%20sentence%20)%3B%0A%20%20%0A%7D%0A%0AtitleCase(%22I'm%20a%20little%20tea%20pot%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function titleCase(str) {
  
  str = str.toLowerCase();
  var words = str.split(" ");
  var sentence = "";
  
  for(var i = 0; i < words.length;i++){
    
    var word = words[i];
    word = String(word.charAt(0)).toUpperCase() + word.substring(1);
    sentence += word + " ";
    
  }
  
  return ( sentence );
  
}

titleCase("I'm a little tea pot");

```

**Comment by dhcodes** [comment]
@TilakMaddy please consider asking for help in the chat room on Gitter. You have an error in your code.
