### ISSUE TITLE
Look at the jpeg

### ISSUE THREAD

**Issue by ThoresenPride** [freeCodeCamp/freeCodeCamp#14387]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

HOW CAN THIS POSSIBLY BE WRONG??
![problemm](https://cloud.githubusercontent.com/assets/26748813/25012354/8a3a23a8-2070-11e7-82d8-9eee56182a77.jpg)

**Comment by augmt** [comment]
@ThoresenPride You spelled `length` wrong on line 33.

For future reference, you can ask other campers for help on [Gitter](https://gitter.im/FreeCodeCamp/Help) and likely get a quicker response.

**Comment by dhcodes** [comment]
Thanks @augmt Closing as resolved.
