### ISSUE TITLE
Beta site: express waypoint links result in 404

### ISSUE THREAD

**Issue by segmentationfaulter** [FreeCodeCamp/freecodecamp#1439]
The page for waypoint mentioned in the subject is broken on the beta site.

**Comment by ahstro** [comment]
Is this still relevant? The page doesn't seem broken to me.

**Comment by segmentationfaulter** [comment]
for me it opens the page Store data in MongoDB and issue is still relevant.

**Comment by ahstro** [comment]
Nevermind my last comment, I'm being redirected to the wrong page as well, although [Learn how Free Code Camp Works](http://beta.freecodecamp.com/challenges/waypoint-learn-how-free-code-camp-works) in my case.

**Comment by ahstro** [comment]
I'm looking at how to fix this, but I'm not making any promises.

**Comment by BerkeleyTrue** [comment]
Not sure what is going on here. I'll hop into the servers re-seed. Hopefully that should fix the issue.

**Comment by ahstro** [comment]
@BerkeleyTrue It has something to do with there being periods (.) in the challenge names. I'm trying to figure out where the issue is right now.

**Comment by BerkeleyTrue** [comment]
@ahstro That may be it as the first one still works.

**Comment by ahstro** [comment]
None of the challenges with periods in the name work, but removing the period in the seed/challenge/*.json fixes the 404, so I'm pretty sure that it's the issue. Now to the fun part, figuring out why that's an issue ;)
Should I keep looking, or do you want to take over?

**Comment by BerkeleyTrue** [comment]
@ahstro I'm assigning you to this. The issue is the regex is unable to find the waypoints because the non-alphanumerics through it off. The regex needs to change to ignore non-alphanumerics. It is in the `server/boot/challenges.js` file.

**Comment by ahstro** [comment]
Okay, I'll keep trying to figure out all this node stuff. Thanks :)

**Comment by BerkeleyTrue** [comment]
This issue has since evolved. 

The issue is the `.` in the challenge name throws off the regex we are using.

The solution is to change name fields of of challenges to `title` and auto-generate `name`/`dashedName` during `node seed`. `name` field will be the title field with all the non-alphanumeric characters stripped and lowercased. `dashedName` will be the dasherized version of `name`.
