### ISSUE TITLE
Create a Form Element

### ISSUE THREAD

**Issue by rougesatya** [freeCodeCamp/freeCodeCamp#14394]
Challenge [Create a Form Element](https://www.freecodecamp.com/challenges/create-a-form-element#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fp%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cp%3EThings%20cats%20love%3A%3C%2Fp%3E%0A%3Cul%3E%0A%20%20%3Cli%3Ecat%20nip%3C%2Fli%3E%0A%20%20%3Cli%3Elaser%20pointers%3C%2Fli%3E%0A%20%20%3Cli%3Elasagna%3C%2Fli%3E%0A%3C%2Ful%3E%0A%3Cp%3ETop%203%20things%20cats%20hate%3A%3C%2Fp%3E%0A%3Col%3E%0A%20%20%3Cli%3Eflea%20treatment%3C%2Fli%3E%0A%20%20%3Cli%3Ethunder%3C%2Fli%3E%0A%20%20%3Cli%3Eother%20cats%3C%2Fli%3E%0A%3C%2Fol%3E%0A%3Cform%20action%3E%3Cinput%20type%3D%22text%22%20placeholder%3D%22cat%20photo%20URL%22%3E%3C%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo"><input type="text" placeholder="cat photo URL"></form>

```

**Comment by rougesatya** [comment]
When i enter the form element, the page then fails to load.
Can someone tell me the reason for this?

**Comment by zupa10** [comment]
Your code is correct. There should be no problem.

**Comment by LarrisUK** [comment]
Same error happening to me and refreshing/ resetting code doesn't work. 
The code seems to work fine when I use it separately in a text editor then view as a page in Chrome. 

Link to the most up to date page containing the same advice:
https://forum.freecodecamp.com/t/removing-all-locally-stored-challenges/19129

Note that 'Resources' was not visible in my Chrome console but instead was replaced(?) with 'Application'. 
Here I found the specific challenge and deleted it but the problem remained. 
And when I refreshed my web page, the challenge appeared again in the list of 'Locally Stored Challenges'.

**Comment by fatbacker** [comment]
This site is riddle with stuff that doesn't work and gives you ridiculous explanations that have nothing to do with the code itself.

**Comment by fatbacker** [comment]
This site is riddle with ridiculous issues that beginners are not going to be able to figure out because they are trying to trouble shoot stuff they don't know. You people in this site need to fix this if you really want to teach people.

**Comment by fatbacker** [comment]
But I fixed my issue by copying the link and then closing the browser and opening a new one and pasting in the link and re-doing the problem.

**Comment by D34nsF1n3st** [comment]
If you have Chrome, try the following:
- Press: Ctrl + Shift + J
- Console opens up
- Go to "Application" Tab (two bolt symbol, to the right of Profiles)
- Go to Left Tab "Local Storage"
- Go to "https://www.freecodedamp.com"
- Go to the right Tab "Key"
- Search for "Create a Form Element"
- Rightclick -> Delete
- Refresh your browser

**Comment by LarrisUK** [comment]
The advice about deleting the page in local storage/ hard resetting the browser doesn't work for me. 
I think this is the same as issue #14310. 
It seems to be an issue specifically with Chrome. I think that's kind of embarrassing on the part of FCC, since we are learning to develop web pages and [Chrome is the most commonly used web browser in the world by a long shot](https://www.w3schools.com/browsers/).  

That other issue is still open and older than this one so I'm reverting to that to make further posts about the problem.

**Comment by texas2010** [comment]
thanks for the report, and we confirm that this is a known issue, check #13727 

Closing as a duplicate.
