### ISSUE TITLE
Missing "to" from "less than or equal the"

### ISSUE THREAD

**Issue by Ellyria** [freeCodeCamp/freeCodeCamp#14403]
Challenge [Comparison with the Less Than Or Equal To Operator](https://www.freecodecamp.com/challenges/comparison-with-the-less-than-or-equal-to-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This line is missing "to":
If the number to the left is less than or equal the number to the right, it returns true.

It should be worded like this:
If the number to the left is less than or equal to the number to the right, it returns true.

Screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/26424000/25053539/d29e957e-2125-11e7-890c-6b6bc03a016f.png)

**Comment by Ellyria** [comment]
I would like to do this edit myself, but am not confident enough in my GIT skills to be able to find my way to the exact spot in the code and change it. I also don't know how to assign a bug to myself in this interface. There doesn't seem to be a way to edit Assignees. I would appreciate any assistance anyone can offer me in learning how this process works.

**Comment by Manish-Giri** [comment]
@Ellyria Don't worry about the "assignee", I think only core team members can be assigned. 

[This](https://github.com/freeCodeCamp/freeCodeCamp/blob/533e496f9b7bea21bbb3f77acba5923743ded280/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L3256) is the line you need to modify. [This](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md#getting-started) document has the necessary steps to help you setup your local environment.

Hit us up in the [contributor's chat](https://gitter.im/FreeCodeCamp/Contributors) if you have questions.

Good luck!

**Comment by Ellyria** [comment]
Thank you. I will work my way through that Contributor's Guide and see how far I get. So, can I just go ahead and do the edit without it being assigned to me once I'm finished reading through that guide?

**Comment by Manish-Giri** [comment]
Yes, since you've commented here that you're working on it, you can proceed.

**Comment by dhcodes** [comment]
Thanks for the assist @Manish-Giri

**Comment by Ellyria** [comment]
I've finished the SSH part of the Contributor's Guide and have been authenticated. So far, so good. Onward with the guide. Thanks again. I feel like I'm getting somewhere.

**Comment by Ellyria** [comment]
I'm sorry, but this isn't going to work right now. I'm apparently using an outdated enough operating system (Linux Mint Rebecca) that I'm getting all kinds of warnings when attempting to follow the npm portion of the instructions. I think my contributions to freeCodeCamp will have to wait until I update my operating system.

**Comment by Ellyria** [comment]
I decided to do it in the GUI interface on https://github.com instead of on my computer and have managed to edit the file and save it to my staging area: https://github.com/Ellyria/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json

**Comment by dhcodes** [comment]
@Ellyria At the top of your repo there should be the option to open a Pull Request against the staging branch. You would need to do that.

**Comment by Ellyria** [comment]
Thanks. I think I've managed to do it. The challenge still looks the same, though, so I'm leaving this open for now.
