### ISSUE TITLE
Make a Person Javascript Algorithms

### ISSUE THREAD

**Issue by anjildhamala** [freeCodeCamp/freeCodeCamp#14410]
Make a person Javascript advance algorithm issue

Code works in a fiddle. Yet, i can't seem to pass the `bob.getFullName() should return "Haskell Ross" after bob.setFirstName("Haskell")` test. Everything else goes through smoothly.

Make a Person
https://www.freecodecamp.com/challenges/make-a-person
* Google Chrome Version 57.0.2987.133 (64-bit)
* OSX
* Laptop

Here's the fiddle.
https://jsfiddle.net/op0eqbk8/

**Comment by augmt** [comment]
@anjildhamala Your code doesn't update `fullName` properly. [This new fiddle](https://jsfiddle.net/op0eqbk8/1/) shows that `getFullName` will not update the value of `fullName` if you've already defined `fullName`.

**Comment by anjildhamala** [comment]
@augmt Thank you!
