### ISSUE TITLE
login with facebook broken on beta site

### ISSUE THREAD

**Issue by misterrorypond** [FreeCodeCamp/FreeCodeCamp#1441]
error text: Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

**Comment by benschenker** [comment]
Hey @misterrorypond,

It looks like this issue fell through the cracks, is this still a problem for you?

**Comment by benschenker** [comment]
I'm going to close this as stale as it is associated with the beta site which has since been pushed to production.  Please reopen if this is still a problem
