### ISSUE TITLE
Cursor Issue

### ISSUE THREAD

**Issue by fatbacker** [freeCodeCamp/freeCodeCamp#14421]
When ever I get to a new challenge my cursor refuses to go to the end of a closing tag. I do that so I can start a new line for my code. Instead it will start in the middle of my code and then jump down two lines in the middle of other code. Seriously needs fixing.

**Comment by OFFLlNE** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #7847, so I am closing it as a duplicate.

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by fatbacker** [comment]
So you don't address things, you just shut them down?
