### ISSUE TITLE
Cursor jumps around were I don't want it to go.

### ISSUE THREAD

**Issue by fatbacker** [freeCodeCamp/freeCodeCamp#14424]
So I checked the other # I was given to find a fix and there is none. Maybe someone after a year can fix the problem so they don't have to keep moderating the same issue after a year. there is no fix that I saw after I went back and checked where I was told to go.

**Comment by texas2010** [comment]
@fatbacker 

Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #7847, so I am closing it as a duplicate.
