### ISSUE TITLE
The video is not working

### ISSUE THREAD

**Issue by KudratP** [freeCodeCamp/freeCodeCamp#14420]
Challenge [build-a-tribute-page](https://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by shashank7200** [comment]
@KudratP **Videos** are now deprecated for the updated version of **freeCodeCamp** and will be removed soon. So, please use the **Codepen** links provided to see what you have to built and try to include the **test** file in your submission and check if your project passes the test or not!

Please close the issue, and go for your project :+1:

**Comment by dhcodes** [comment]
The videos are going away. See: https://github.com/freeCodeCamp/freeCodeCamp/issues/12753
