### ISSUE TITLE
My cursor bounces all over the place.

### ISSUE THREAD

**Issue by fatbacker** [freeCodeCamp/freeCodeCamp#14423]
Is there anything that can fix this cursor problem from bouncing all over the place?

**Comment by OFFLlNE** [comment]
This is already a known bug and if you would've red my comment then you would've seen that this issue has already adressed in issue #7847

Please use chatrooms if you want tips how to tackle this problem. You can also view our full list of official chatrooms.

**Comment by fatbacker** [comment]
So it was a year ago and it obviously won't get fixed.



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by OFFLlNE** [comment]
@fatbacker feel free to make a Pull-request for it with a fix..
