### ISSUE TITLE
My Cursor does not work properly

### ISSUE THREAD

**Issue by fatbacker** [freeCodeCamp/freeCodeCamp#14422]
I just reported the issue and instead of seeing what fixes there may be, you just shut down the thread?

**Comment by OFFLlNE** [comment]
This is already a known bug and if you would've red my comment then you would've seen that this issue has already adressed in issue #7847

Please use chatrooms if you want tips how to tackle this problem. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
