### ISSUE TITLE
Check the Length Property of a String Variable

### ISSUE THREAD

**Issue by stacybanks514** [FreeCodeCamp/FreeCodeCamp#1443]
Challenge http://beta.freecodecamp.com/challenges/check-the-length-property-of-a-string-variable has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Hello, I love FreeCodeCamp, you guys do an amazing job!
I just noticed that on this question there is a closing } at the end of the 'if' statement. It wont let me pass unless I delete that }, just thought you should know. Thanks!

**Comment by benschenker** [comment]
Hey @stacybanks514 is this still an issue for you?

I'm having issues replicating this.
