### ISSUE TITLE
what should I do with this? no instruction on what should I do...

### ISSUE THREAD

**Issue by danpaodc** [freeCodeCamp/freeCodeCamp#14432]
![untitledproblem](https://cloud.githubusercontent.com/assets/27296299/25069973/20dc9bf2-22c3-11e7-8307-96f475624372.png)
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=%0Afunction%20myLocalScope()%20%7B%0A%20%20'use%20strict'%3B%0A%20%20%0A%20%20%0A%20%20console.log(myVar)%3B%0A%7D%0AmyLocalScope()%3B%0A%0A%2F%2F%20Run%20and%20check%20the%20console%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myLocalScope%0Aconsole.log(myVar)%3B%2F%2F%20%22undefined%22%0A%0A%2F%2F%20Now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function myLocalScope() {
  'use strict';
  
  
  console.log(myVar);
}
myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope
console.log(myVar);// "undefined"

// Now remove the console log line to pass the test


```

**Comment by dhcodes** [comment]
@danpaodc please ask for code help in the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help) on Gitter.
