### ISSUE TITLE
Margin auto syntax is not recognized as correct answer

### ISSUE THREAD

**Issue by roxroy** [freeCodeCamp/freeCodeCamp#14437]
Challenge [center-an-element-horizontally-using-the-margin-property](http://beta.freecodecamp.com/en/challenges/applied-visual-design/center-an-element-horizontally-using-the-margin-property) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
Add "margin: 0 auto;" to the styles, shows expected results in the preview window. However, test does not pass.

```html
<style>
  div {
    background-color: blue;
    height: 100px;
    width: 100px;
    margin: 0 auto;
  }
</style>
<div></div>
```

**Comment by DeepMonk** [comment]
Thes task: "Center an Element Horizontally", so `margin: auto;` is correct solution.

**Comment by dhcodes** [comment]
@roxroy the instructions read "Center the div on the page by adding a margin property with a value of auto." Please consider asking for help in the Gitter Chat room.
