### ISSUE TITLE
Not running change the font size challenge

### ISSUE THREAD

**Issue by sebin234** [freeCodeCamp/freeCodeCamp#14434]
#### Challenge Name

Change the font size of an element

#### Browser Information

* Browser Name, Version: chrome 57.0.2987
.132
* Operating System: Android 6.0.1
* Mobile, Desktop, or Tablet: mobile

#### Your Code

<style>
  .red-text {
    color: red;
    }
    p {
      font-size: 16px;
      }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your a snf.</p>
<p> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fl.</p>

#### Screenshot

https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%C2%A0%20%20%7D%0A%20%C2%A0%20%20p%20%7B%0A%20%C2%A0%20%C2%A0%20%20font-size%3A%2016px%3B%0A%20%C2%A0%20%C2%A0%20%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20a%20snf.%3C%2Fp%3E%0A%3Cp%3E%20Purr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fl.%3C%2Fp%3E

**Comment by sebin234** [comment]
Please  help me

**Comment by texas2010** [comment]
@sebin234, it is better to use the computer. so you could pass this challenge.  sorry.  phone have a problem with the code editor.

**Comment by Napoleonsolo51** [comment]
Did you solve this problem, as I have the same problem?
