### ISSUE TITLE
Rarely occurring bug: Newly-created user accounts with null emails

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#14441]
We seem to have a very rare bug where a camper will create a new account and that account won't have an email address associated with it. Here's what I know about it:

- I have found some recently-created accounts where the user has a GitHub ID but a null email address. That would seem to be impossible, since the only way to create an account is with an email address (GitHub userIdentities are latter attached to existing accounts)

- We have higher than normal reports of campers' progress being completely erased by the system. In the past, these have been attributable to duplicate accounts (a user accidentally signs up with a different email address) but recently there have been several cases where we've been unable to find the original account. I think there is a bug that is causing this.

Unfortunately, I have no idea what's causing this, so I can't reproduce it. Again, it only seems to be affecting about 1 in 10,000 campers or so (I've had maybe 20 or 30 reports of this happening).

We need a contributor to dig into our authentication code and GitHub-linking code to figure out what could be causing progress to be erased (or accounts to be entirely deleted and re-instantiated then re-instantiated as brand new accounts).

**Comment by augmt** [comment]
freeCodeCamp doesn't disallow new users from signing in with their GitHub account. This is true for beta.freecodecamp.com as well. I don't know why yet.

For good measure I also tried signing in with Facebook but wasn't allowed and was told: "Accounts can only be created using GitHub or though email."

**Comment by QuincyLarson** [comment]
@augmt wow - you're right. I didn't think that was possible. I will create an issue and we'll fix this ASAP.
