### ISSUE TITLE
// Add record here in incorrect place.

### ISSUE THREAD

**Issue by haydennorthcott** [freeCodeCamp/freeCodeCamp#14445]
Challenge [Manipulating Complex Objects](https://www.freecodecamp.com/challenges/manipulating-complex-objects#?solution=%0Avar%20myMusic%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Billy%20Joel%22%2C%0A%20%20%20%20%22title%22%3A%20%22Piano%20Man%22%2C%0A%20%20%20%20%22release_year%22%3A%201973%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CS%22%2C%20%0A%20%20%20%20%20%20%228T%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%0A%20%20%20%20%22gold%22%3A%20true%0A%20%20%7D%0A%20%20%2F%2F%20Add%20record%20here%0A%5D%3B%0A%0AmyMusic.push(%0A%20%20%20%20%7B%22artist%22%3A%20%22Coldplay%22%2C%0A%20%20%20%20%22title%22%3A%20%22Parachutes%22%2C%0A%20%20%20%20%22release_year%22%3A%202000%2C%0A%20%20%20%20%22formats%22%3A%20%5B%20%0A%20%20%20%20%20%20%22CS%22%2C%20%0A%20%20%20%20%20%20%228T%22%2C%20%0A%20%20%20%20%20%20%22LP%22%20%5D%2C%7D%0A%20%20%20%20%20)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  }
  // Add record here
];

myMusic.push(
    {"artist": "Coldplay",
    "title": "Parachutes",
    "release_year": 2000,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],}
     );

```

lines 13 and 14 should be swapped around.

**Comment by JoolsMcFly** [comment]
Nope, they should not be swapped around.

You chose to use `array.push` but the aim of the exercise is to manipulate arrays of objects.

So if you were to add another record (i.e. a new object), you'd place it inside the array like so:
```js
var myMusic = [
  {
    "artist": "Billy Joel",
    "title": "Piano Man",
    "release_year": 1973,
    "formats": [ 
      "CS", 
      "8T", 
      "LP" ],
    "gold": true
  },
  {
  "artist": "Daft Punk",
  "title": "Homework",
  "release_year": 1997,
  "formats": [ 
    "CD",
    "Cassette",
    "LP"
  ],
  "gold": true
}
];
```

I suppose tests should make sure campers do not use `array.push` for this exercise. What do mods think?
