### ISSUE TITLE
Bootstrap container-fluid div challenge error

### ISSUE THREAD

**Issue by jdr972** [FreeCodeCamp/FreeCodeCamp#1444]
Challenge http://beta.freecodecamp.com/challenges/waypoint-house-our-page-within-a-bootstrap-container-fluid-div has an issue.  
The challenge is to add a div with a 'container-fluid' class (btw there is a typo), but the editor is waiting for a 'row' class.

**Comment by misterrorypond** [comment]
I've tried using both row and container-fluid and it doesn't work for me either!
can't get this exercise to pass

**Comment by benschenker** [comment]
I believe this has been fixed as I cannot replicate your issue.  I'll close this for now, but please reopen if you still have issues with this.
