### ISSUE TITLE
H2 not turning blue

### ISSUE THREAD

**Issue by dovidys** [freeCodeCamp/freeCodeCamp#14459]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by shashank7200** [comment]
@dovidys Please close one of the two issues, because they are for the same challenge. #14460 

Thanks,
Shashank Shekhar

**Comment by erictleung** [comment]
@dovidys closing in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/14460 because it has more information.
