### ISSUE TITLE
Title Case a Sentence

### ISSUE THREAD

**Issue by IsaakNazar** [freeCodeCamp/freeCodeCamp#14451]
Well, I opened the "Title Case a Sentence" task, what interesting part of this task was that  the task has already solved( resolved code) I've never done before .  WTF is that, I was extremely upset.
So I just passed that code without challenge. WTF??? 
ps. Nobody knows my sign in passsword on FCC, so I think its a Bug,

```
`function titleCase(str) {
  var newStr = str.split(' ');

  for (i=0; i < newStr.length; i++){
   newStr[i]=newStr[i].charAt(0).toUpperCase() + newStr[i].slice(1).toLowerCase();
  }
  return newStr.join(' ');
 
}

titleCase("I'm a little tea pot");`

```

**Comment by dhcodes** [comment]
@IsaakNazar if you've ever opened another user's code via a URL in the chat, it will place their answer into your challenge. I believe that is probably what happened but feel free to re-open if I'm mistaken.
