### ISSUE TITLE
Generate Whole Numbers in JS Test Doesn't Accept Corner Case

### ISSUE THREAD

**Issue by IsaakGroepT** [freeCodeCamp/freeCodeCamp#14454]
Challenge [Generate Random Whole Numbers with JavaScript](https://www.freecodecamp.com/challenges/generate-random-whole-numbers-with-javascript#?solution=%0Avar%20randomNumberBetween0and19%20%3D%20Math.floor(Math.random()%20*%2020)%3B%0A%0Afunction%20randomWholeNum()%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0Avar%20dec%20%3D%20Math.random()%20*%2010%3B%0A%20%20dec%20%3D%20Math.floor(dec)%3B%0A%20%20%0A%20%20return%20dec%3B%0A%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var randomNumberBetween0and19 = Math.floor(Math.random() * 20);

function randomWholeNum() {

  // Only change code below this line.
var dec = Math.random();
dec *= 10; // This causes faulty detection
  dec = Math.floor(dec);
  
  return dec;
}

```

**Comment by erictleung** [comment]
@IsaakGroepT thanks for the issue. Yes, that is a valid solution. Our tests haven't covered this corner case of having that extra line of code. 

[This line](https://github.com/freeCodeCamp/freeCodeCamp/blob/533e496f9b7bea21bbb3f77acba5923743ded280/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L5443) needs to be changed to accommodate this.

**Comment by KSerrania** [comment]
Hello,
This is my first time contributing to a GitHub project, I would like to try fixing this issue :smile:

**Comment by codersc** [comment]
So, I made a little function that seems like it would do the job.
Here's what it would like stringified in the test:
```javascript
'(function(){var varName = /\\s*?var\\s+?(\\w+?)\\s*?=\\s*?Math\\s*?\\.\\s*?random\\s*?\\(\\s*?\\)/.exec(code);return varName && new RegExp(\'\\s*?\' + varName[1] + \'\\s*?\\*=\\s*?10\').test(code);})()'
```
Not exactly the most readable code :smiley: . Because it'll all be on one line, I'm not sure there's much that can be done to make it more readable. Although, maybe someone else could come up with a way more elegant solution.

Here's what my solution looks like in a slightly more readable format:

```javascript
function() {
	var varName = /\s*?var\s+?(\w+?)\s*?=\s*?Math\s*?\.\s*?random\s*?\(\s*?\)/.exec(code);

	return varName && new RegExp('\\s*?' + varName[1] + '\\s*?\\*=\\s*?10').test(code);
}
```

If anyone thinks it looks ok, lemme know, and I'll test it on a local FCC branch and do a PR.
