### ISSUE TITLE
Formatting Very Off, Test Params not Valid Beta Site for all RGB HTML exercises 

### ISSUE THREAD

**Issue by misterrorypond** [FreeCodeCamp/FreeCodeCamp#1445]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-rgb-values-to-color-elements(as well as all the rgb exercises) has an issue. I cannot progress even though my code is correct! Theses test cases are odd. Also the formatting seems to be off
![error1](https://cloud.githubusercontent.com/assets/11319764/9023076/6398edae-3852-11e5-9475-838c627ca4de.png)
![error2](https://cloud.githubusercontent.com/assets/11319764/9023077/63a8f88e-3852-11e5-86ea-f1ffe9830e1e.png)
![error3](https://cloud.githubusercontent.com/assets/11319764/9023078/63aa6d2c-3852-11e5-8c4f-a3611a5548dc.png)

**Comment by benschenker** [comment]
Closing as stale
