### ISSUE TITLE
[BETA] Code is not dynamically rendered in virtual phone

### ISSUE THREAD

**Issue by bulrich** [freeCodeCamp/freeCodeCamp#14457]
#### Issue Description
On the beta site, the virtual phone is not rendering text entered in the code editor in real time. The display is updated only when clicking  _Run tests_.

#### Browser Information
* Browser Name, Version: Chrome 57.0.2987.133, Safari 10.1 (12603.1.30.0.34) 
* Operating System: OS X
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
<img width="924" alt="screen shot 2017-04-17 at 17 52 19" src="https://cloud.githubusercontent.com/assets/1296279/25094286/b8a75b24-2396-11e7-810c-fe09e7882009.png">

**Comment by shashank7200** [comment]
@bulrich  Please refer to this issue #12923  for the information about browser rendering of the code at Beta site . Please close this issue.

**Comment by bulrich** [comment]
Closing as dupe of #12923
