### ISSUE TITLE
H2 not turning blue

### ISSUE THREAD

**Issue by dovidys** [freeCodeCamp/freeCodeCamp#14460]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
<style>
   h2 { color: blue; } 
</style>
<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>




```

**Comment by shashank7200** [comment]
@dovidys Please post the Screenshot of the same and the link of the challenge you are facing problem with.

**Comment by erictleung** [comment]
@dovidys thanks for the issue, but can you give us more information about your issue? Based on your code, I'm assuming you're on the ["Use CSS Selectors to Style Elements"](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements) challenge. Are you using a mobile device? What browser are you using? Please let us know this information and anything else you found odd that might help us out. Your code passes the challenge.

**Comment by dovidys** [comment]
Im using a samsung galaxy s5 mobile device with chrome


Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by mitch-medalen** [comment]
im having the same problem I have typed the code in many time, quit my browser, and refreshed my browser and nothing Is working please fix this asap

**Comment by lauraenria** [comment]
I am having the same problem too. Can someone help us? Thanks please could you fix it asap?

**Comment by erictleung** [comment]
@mitch-medalen which browser are you using and what version of it do you have?

@lauraenria similar question as well. What versions of them are you using?

Thanks for the feedback everyone! We'll try to figure out what's wrong as soon as we can.

**Comment by shajilphilip** [comment]
<style> 
  h2 {color: blue;}
</style>

not turning blue .....

**Comment by jtaptso** [comment]
I am having the same issue on FireFox (Windows 7)

**Comment by yergi** [comment]
I am having the same issue, here's my user agent info, screenshot, and supplied code:

Challenge [use-css-selectors-to-style-elements](http://beta.freecodecamp.com/en/challenges/basic-css/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This exercise is failing with the message, "message: Your h2 element should be blue." Despite, as you can see in the code below, the h2 element being styled to blue, and being displayed as blue in the preview pane, as you can see here: [css error](https://ndp.box.com/s/zb3jei4zaim256e1uhskiwhq253glog6)

```html

<style>
  h2 {color: blue;}
</style>
<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

**Comment by raisedadead** [comment]
Yes, this is a known issue with mobile browsers injecting different characters than that expected, sometimes.

The only solutions is you should always try and attempt the challenge on a desktop browser when possible.

If that cannot be done, then you could try and delete the code in the editor. Type it again (COPY PASTE will NOT work). 

This is a `wontfix` issue for reasons beyond our control. We recommend using desktop browsers.

**Comment by systimotic** [comment]
I would like to add that this issue has been fixed in the beta 🙌
