### ISSUE TITLE
codepen uses bootstrap version 4, not 3!

### ISSUE THREAD

**Issue by CobusThee** [freeCodeCamp/freeCodeCamp#14461]
#### Challenge Name
https://www.freecodecamp.com/challenges/build-a-tribute-page

#### Issue Description

I had to find out why the class img-responsive didn't work in codepen. After trying a lot of things and searching on google, I found out that codepen is using bootstrap version 4, not 3. 
In version 4 you need to use img-fluid , not img-responsive.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by shashank7200** [comment]
@CobusThee You can add external css in Codepen, in your case , it is bootstrap@3 CDN https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css . Please follow the same and your code will work normally and Kindly close this issue, if you find the solution.

Thanks,
Shashank Shekhar
