### ISSUE TITLE
bootstrap not automatically included/ or bootstrap not working

### ISSUE THREAD

**Issue by misterrorypond** [FreeCodeCamp/FreeCodeCamp#1446]
Challenge http://beta.freecodecamp.com/challenges/waypoint-make-images-mobile-responsive has an issue.

bootstrap is not included in the file and/or it is simply not working, it doesn't carry over from the previous exercise, and I can't copy and paste it in without opening a new window

**Comment by jdr972** [comment]
Works fine for me 
http://i.imgur.com/aSrzejO.png

**Comment by benschenker** [comment]
Closing as stale
