### ISSUE TITLE
my browser say it is set to 100% and it is still not giving me a green check mark.

### ISSUE THREAD

**Issue by ericcstone** [freeCodeCamp/freeCodeCamp#14469]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20%0A%20%0A%20%20.p%20%7B%0A%20%20%20%20%20font-size%3A%2016px%3B%20%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  
 
  .p {
     font-size: 16px; 
    
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by ericcstone** [comment]
figured it out. sorry

**Comment by dhcodes** [comment]
Closing as resolved.

**Comment by LarryGee** [comment]
having same issue, how did you resolve ericstone?

**Comment by Luticiaf** [comment]
I'm also having the same issue.  zoom reset, browser refreshed, won't go away...

**Comment by ericcstone** [comment]
I wish I would have made a note of what fixed the issue. I just kept messing with it and it worked finnally. 
I will keep better notes the next time I report an issue.

I have gotten stuck several times after that and if I just keep fiddling with it there is always a reason the code doesn’t work.

It’s a really great way to learn code. I think when the stuff doesn’t work it really pulls my attention into why. And that is when I really learn.

**Comment by jalaj001** [comment]
this thing doesnt work

**Comment by dhcodes** [comment]
@jalaj001 You have an error in your code. Please ask for help in the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help).

For anyone else who is still having an issue, I recommend visiting the chat room. If, after that, you still believe there is an issue with the challenge itself, please reopen this issue and post your code.

**Comment by Ocharo** [comment]
<style>
  .red-text {
    color: red;
  }
  
  .p {
     font-size: 16px; 
    
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
