### ISSUE TITLE
Improve bootstrap loading instruction

### ISSUE THREAD

**Issue by gvm289** [freeCodeCamp/freeCodeCamp#14465]
Challenge [Build a Tribute Page](https://www.freecodecamp.com/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Quick adding bootstrap does not load it. You need to add the following Bootstrap to work

1. "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css   ---- To the CSS page

2. https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js  ------ To the JS page

3. https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js    ---------- To the JS page

**Comment by shashank7200** [comment]
@gvm289 The curriculum has been updated which you can find it here https://beta.freecodecamp.com . Please close this issue.
