### ISSUE TITLE
I believe I've found a bug in Lesson 52

### ISSUE THREAD

**Issue by kwillia007** [freeCodeCamp/freeCodeCamp#14466]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3D%20pink%20%3B%0A%20%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%20%22pink-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color= pink ;
  }
  
</style>
<h1 class= "pink-text">Hello World!</h1>

```

**Comment by shashank7200** [comment]
@kwillia007  You don't have found a bug, you wrote a wrong code block, Your code 
```
.pink-text {
    color= pink ;
  }
```
should be replaced with 

```
.pink-text {
    color: pink ;
  }
```

Please close the issue!

Thanks,
Shashank Shekhar

**Comment by kwillia007** [comment]
Thank you so much I didn't see that simple mistake sorry.

**Comment by gbzaid** [comment]
:( Having same issue, can anyone tell me what the issue was again?

**Comment by kwillia007** [comment]
gbzaid my code was wrong. Edited my mistake and moved to the next challenge.

**Comment by gbzaid** [comment]
I don't understand how your code was wrong, It seems exactly like what the
instructions asked for. You create a style with color pink and use it in
the h1 tag to see if it will override the body class? What was off about it?

**Comment by kwillia007** [comment]
Just sent you the correct code 
 

    On Thursday, April 20, 2017 11:53 PM, gbzaid <notifications@github.com> wrote:
 

 I don't understand how your code was wrong, It seems exactly like what the
instructions asked for. You create a style with color pink and use it in
the h1 tag to see if it will override the body class? What was off about it?
