### ISSUE TITLE
Documentation about twitch api in 'Use the Twitchtv JSON API' project is leading to 404 page

### ISSUE THREAD

**Issue by sevskii** [freeCodeCamp/freeCodeCamp#14463]
#### Challenge Name
Use the Twitchtv JSON API
https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api
#### Issue Description
Link from
8.Hint: The relevant documentation about this API call is here: https://github.com/justintv/Twitch-API/blob/master/v3_resources/streams.md#get-streamschannel.
is leading to 404 page

**Comment by RationalCoding** [comment]
Twitch's Github docs have been deprecated: https://github.com/justintv/Twitch-API

Link should be changed to: https://dev.twitch.tv/docs/v5/reference/streams/#get-stream-by-user

**Comment by Masya120** [comment]
I'd like to take this one if no one else has yet.

**Comment by TinCan-Assassin** [comment]
It happened to me, too. 

![screenshot from 2017-05-10 13-55-09](https://cloud.githubusercontent.com/assets/19189392/25913414/9ecc0746-3588-11e7-969b-e6aabe68a8bb.png)

**Comment by thebrokenkeyboard** [comment]
I can confirm the link (step 8, Hint) is still broken.

**Comment by raisedadead** [comment]
Yes, we have recently fixed the same for the beta site. I'll make a change for an urgent fix to production.
