### ISSUE TITLE
Local Scope and Functions tests not very strict

### ISSUE THREAD

**Issue by Blauelf** [freeCodeCamp/freeCodeCamp#14474]
#### Challenge Name

[Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions)

#### Issue Description

Code
```js
var myVar;
```
(yes, that's all the code, I removed all the rest) should pass neither of those checks

* No global myVar variable
* Add a local myVar variable 

but passes both.

First test: If the `myVar` created in my "global" context is indeed global, the corresponding test could be
```js
!("myVar" in window)
```
or
```js
!window.hasOwnProperty("myVar")
```
or similar.

If it isn't a real global variable (but one in an outer scope, which is almost the same), one could use strict mode and try reading from the variable (which would fail if it did not exist), or with ES6 defining another variable of the same name as `let myVar;`, which fails if a variable of the same name exists in the current scope.

Second test: The test should ensure the variable declaration is in the function (local), and that function (and its local scope) exists and the function is executed. With the current test for `/var\s+myVar/`, that string could be anywhere.

#### Browser Information

* Browser Name, Version: Firefox 51.0.1
* Operating System: Windows NT 6.1 ("Windows 7")
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
var myVar;
```
#### Screenshot

![Passing all the tests](https://cloud.githubusercontent.com/assets/5952026/25136180/8806db48-2454-11e7-89ea-f7a1f032e369.png)

**Comment by dhcodes** [comment]
Thanks @Blauelf for catching this.
