### ISSUE TITLE
404: We couldn't find a challenge with the name `waypoint-label-bootstrap-wells` upon completion

### ISSUE THREAD

**Issue by misterrorypond** [FreeCodeCamp/FreeCodeCamp#1447]
Upon successful completion, when I press the button to go to the next exercise, I can't progress to the next waypoint and the code onthe page is reset.
![addidattributes](https://cloud.githubusercontent.com/assets/11319764/9023283/9f8c5e6a-385a-11e5-9479-6688061f2d4e.png)
Challenge http://beta.freecodecamp.com/challenges/waypoint-add-id-attributes-to-bootstrap-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benmcmahon100** [comment]
I think this has been fixed in the latest deploy but I'll have to check
