### ISSUE TITLE
Code doesn't pass when it should for challenge  Where do I belong

### ISSUE THREAD

**Issue by PolarisTLX** [freeCodeCamp/freeCodeCamp#14478]
Challenge [Where do I belong](https://www.freecodecamp.com/challenges/where-do-i-belong) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I have tested my code below and according to my tests, my returned answer always matches the desired answer which this challenge wants in each of its checks. Yet it does not pass all of the checks.

My code:
```javascript

function getIndexToIns(arr, num) {
  
	function sortingNumbers(a,b){
  	return a - b;
  }
  arr.sort(sortingNumbers);
  
  console.log(arr);
  
  //if the target number is > the last (greatest number in the sorted source array), then simply return the last index in the source array, because it would be placed at the end
  if (num > arr[arr.length-1]) {
  	console.log(arr.length);
  	return arr.length;
  }
  
  //if not, then check which item in the sorted sourced array is larger, then return the index before that
  else {
    for (i=0; i < arr.length; i++){
    	if (arr[i] >= num){
      	console.log(i);
      	return i - 1;
      }
    }
  } 
}

getIndexToIns([2, 20, 10, 21, 28], 22);

```

**Comment by JoolsMcFly** [comment]
You're almost there.

> getIndexToIns([10, 20, 30, 40, 50], 35) should return 3

What your code does is loop through sorted array and stops when current array item is >= num
Then you return `i-1`. Why not `i`?

In above example, loop will reach 40 for i=3 but you return 2.

Here's a working solution which makes use of `Array.findIndex`:
```js
function getIndexToIns(arr, num) {
  arr.sort(function(a,b){
  	return a - b;
  });
  var index = arr.findIndex(function(item) {
    return item >= num;
  });

  return index !== -1 ? index : arr.length;
}
```

It's not an issue with freeCodeCamp so can you close this issue pls?
Thanks.

**Comment by PolarisTLX** [comment]
Thanks for the reply. 
That is odd as when I ran my code on another console it always returned the right answer for each check.
I did work through another method that passes in the end, which is much simpler and is close to yours so it's fine.  I'll try "closing the issue as requested.
