### ISSUE TITLE
could not make the color part even tho i did all solution

### ISSUE THREAD

**Issue by itsjacop** [freeCodeCamp/freeCodeCamp#14470]
Challenge [Change the Color of Text](https://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%0A%3Ch2%20style%3D%22color%3A%20blue%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Dragon/48.12.18.249 Chrome/48.0.2564.97 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h2 style="color: blue">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by randallkern** [comment]
Try
<h2 style="color: blue;">CatPhotoApp</h2>
Looks like you were missing the ";".

**Comment by randallkern** [comment]
="color: blue;"
Sorry about previous comment, it recognized the HTML.

**Comment by dhcodes** [comment]
@itsjacop you have an error in your code. Please consider asking for help in the [Help Chat Room](https://gitter.im/FreeCodeCamp/Help).
