### ISSUE TITLE
Styling div element with silver background

### ISSUE THREAD

**Issue by sprachstoff** [freeCodeCamp/freeCodeCamp#14477]
I see others had some challenge with this problem. Solution that worked:

* Browser Name, Version: Chrome
* Operating System: Win 10
* Mobile, Desktop, or Tablet: laptop
#### Your Code
<style>
  
  .red-text {
    color: red;
  }
  .silver-background {
    background-color: silver;
}
// other style elements//
</style
<div style="background-color: silver">

**Comment by dhcodes** [comment]
Please don't post solutions on the issue threads. This area is for bugs/issues with the site. Please help other campers in the Help chat room on Gitter.

**Comment by sprachstoff** [comment]
Dylan,
Apologies for that. Will post to the Help chat room.
Thank you,
