### ISSUE TITLE
Code tags shouldn't be included in console output

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#14479]
Challenge [use-responsive-design-with-bootstrap-fluid-containers](http://beta.freecodecamp.com/en/challenges/bootstrap/use-responsive-design-with-bootstrap-fluid-containers) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Here's a screenshot:
![](https://www.evernote.com/l/Ar_IwF1wGIJJOq1iMxBeruOv-jcRxZEX6wcB/image.png)

**Comment by Manish-Giri** [comment]
I've seen this occur over a **lot** of challenges.

**Comment by QuincyLarson** [comment]
Hey @Manish-Giri, thanks for confirming this isn't an isolated issue. Do you have any ideas for what might be causing this?

**Comment by lynxlynxlynx** [comment]
It happens when there are multiple tags. Only the outermost pair gets stripped (visible in the screenshot).

**Comment by techstonia** [comment]
Hey. I made some changes. Should be better now! ;)
