### ISSUE TITLE
Can't get past this level tried resetting and nothing

### ISSUE THREAD

**Issue by Harrmalik** [FreeCodeCamp/FreeCodeCamp#1448]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![image](https://cloud.githubusercontent.com/assets/10894742/9023467/55b4db04-386a-11e5-99c7-c7cb51993e16.png)

**Comment by ahstro** [comment]
Could you try this again? I can't reproduce the bug with your exact code, so it might've been fixed.

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
