### ISSUE TITLE
Free code camp debugger doesn't work after a correction to the code

### ISSUE THREAD

**Issue by MrToxy** [freeCodeCamp/freeCodeCamp#14481]
Challenge [Override Class Declarations with Inline Styles](https://www.freecodecamp.com/challenges/override-class-declarations-with-inline-styles#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20%23orange-text%20%7B%0A%20%20%20%20color%3A%20orange%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blue-text%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20id%3D%22orage-text%22%20style%3D%22color%3Awhite%22%20class%3D%22pink-text%20blue-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text {
    color: orange;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 id="orage-text" style="color:white" class="pink-text blue-text">Hello World!</h1>

```

So I will try to explain as thoroughly as I can.
when I jumped to this challenge my code was imported from the previous one just like the code above, but while I was reading the task to perform I eliminated the id from the h1 element and ran the code, which returned an error because I was actually supposed to leave the ID on that element.
After that I wrote down the ID again just like above and tried once more to run the code.
Even though the code was right this time, the debugger still returns the same error... I've tried to run it multiple times but I always got the same error...
Unfortunately this is not the only time some of the sort has happened since I already had to jump some challenges due to this problem...
PS: I verified my code both locally and with JsFiddle to make sure the code was right and didn't had any errors... both yielded positive results.

**Comment by texas2010** [comment]
@MrToxy 
Thanks for reporting this. But your code is incorrect and you got typo.
GitHub Issues are for reporting bugs on the website only. 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
