### ISSUE TITLE
Console always returns 1, and this should work. 

### ISSUE THREAD

**Issue by andresh83** [freeCodeCamp/freeCodeCamp#14489]
Challenge [Nesting For Loops](https://www.freecodecamp.com/challenges/nesting-for-loops#?solution=%0Afunction%20multiplyAll(arr)%20%7B%0A%20%20var%20product%20%3D%201%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20for%20(var%20i%3D0%3B%20i%20%3C%20arr.lenght%3B%20i%2B%2B)%7B%0A%20%20%20%20for%20(var%20j%3D0%3B%20j%20%3C%20arr%5Bi%5D.lenght%3B%20j%2B%2B)%7B%0A%20%20%20%20%20%20%20product%20*%3D%20arr%5Bi%5D%5Bj%5D%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20product%3B%0A%7D%0A%0A%2F%2F%20Modify%20values%20below%20to%20test%20your%20code%0AmultiplyAll(%5B%5B1%2C2%5D%2C%5B3%2C4%5D%2C%5B5%2C6%2C7%5D%5D)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function multiplyAll(arr) {
  var product = 1;
  // Only change code below this line
  for (var i=0; i < arr.lenght; i++){
    for (var j=0; j < arr[i].lenght; j++){
       product *= arr[i][j];
    }
  }
  // Only change code above this line
  return product;
}

// Modify values below to test your code
multiplyAll([[1,2],[3,4],[5,6,7]]);


```

**Comment by lynxlynxlynx** [comment]
No, the fact that it doesn't work even in the console should be a definitive clue that it is your code that is wrong. In this case you misspelled something vital — I suggest you add console.log calls to find the problem (you'll see that it is trivial).

**Comment by JoolsMcFly** [comment]
You fat-fingered _length_.
 Try arr.leng**th** instead of arr.leng**ht**

Can you close this issue then? Thanks.

**Comment by andresh83** [comment]
D'oh! Thanks guys, my bad!
