### ISSUE TITLE
possible bug on this challenge?

### ISSUE THREAD

**Issue by deaninous** [freeCodeCamp/freeCodeCamp#14497]
Challenge [match-characters-that-occur-zero-or-more-times](http://beta.freecodecamp.com/en/challenges/regular-expressions/match-characters-that-occur-zero-or-more-times) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

It sems to be rejecting my code even though it the code seems to produce  the desired result
![screenshot from 2017-04-19 14-19-31](https://cloud.githubusercontent.com/assets/12078887/25195428/96365b8c-250b-11e7-93b1-d39c6e0d07e1.png)

```js

"use strict";
let starWars = "Star Wars";
let starWarsRegex = /Star Wars.*/gi; // Change this line
let result = starWars.match(starWarsRegex);

```

**Comment by JoolsMcFly** [comment]
Challenge is fine, instructions say
> Your regex does not need flags.

Check your RegExp again and you can close this issue.

Thanks.

**Comment by deaninous** [comment]
Just closed it.

**Comment by ronnieg1988** [comment]
If rjfgxt ggkcfu44ayayaysgsjdjxnejfjandbzo;j;hhbbbbbb
xjxxhxjzvzjshw😕👍🍨😴👀👍😕👀😕👀😕👍😕👍😕👍😕👍😕👍😕👍😕😕😕😕😕😇😕😕👀👍😕🍧🍧🍧😱😱🍨🙈🍦🍦🚑🍨👀🍦🍦🍨🍦🍨🚑🍨🍦😱😱😋😴😱👍😱👀🍨😴🍨😕🍦🔫🙈👍🕦🕦🕦🕗🕗🕦‼🍧🎂😋😥😱😱😱😘😉😉😉😉🎂👀🍦🍨👀😱🚑🍨🚑🍧😋😦😋😦😂😂😥😋😥❄❄❄❄❄❄👍❄❄❄❄🗽🗽🗽⛺🌃🌆😕🍨😴🍨😘😕👀🔫😴🍧😋jsxjssgdbbszbsbsjdj.........
.....
;-,-.-;-Г&Ω,Ω,ΩΩΩ©🍨😴👍😴😱🚑🍨😴😴🍨😴🍧😴🍧😱😴😱😱👍😱👍👍😱👍👍😴😕😕🚑🍦🔫😝😴👍👍🍦😴🎂👍🕗👍🕦😱👍👍🕦😴👍😴🍦😴😴😌😒😁😌😒😒😒😒😒😒🍨😋🍨🍨😕🍨🍨🍨🍨📀⌛

**Comment by deaninous** [comment]
This language is on my list. Just let me finish javascript first lol.
