### ISSUE TITLE
Free Code Camp can't run code unless I delete the code before it

### ISSUE THREAD

**Issue by blastit** [freeCodeCamp/freeCodeCamp#14491]
#### Challenge Name = "Counting Cards"
https://www.freecodecamp.com/challenges/counting-cards#?

when I use the below code, I'm able to complete the first item on the checklist; but, if I delete the first two blocks of case statements, I'm able to complete the third item on the checklist:

* Browser Name, Version: Safari, Version 9.1.3 (9537.86.7.8)
* Operating System: Mac OS X Version 10.9.5
* Desktop 

```js
switch (card) {
    
    case card = 2:
    case card = 3:
    case card = 4:
    case card = 5:
    case card = 6:
      count++;
      break;
    
    case card = 7:
    case card = 8:
    case card = 9:
      count += 0;
      break;

    case card = 10:
    case card = 'J':
    case card = 'Q':
    case card = 'K':
    case card = 'A':
      count--;
      break;
  }
  
  var string;
  if (count > 0) {
    string = "Bet";
  } else {
    string = "Hold";
  }
  return count + " " + string;

```

![screen shot 1]
(https://cloud.githubusercontent.com/assets/23505048/25175980/eb7f6ca2-24b9-11e7-9de2-49cb9b715c85.png)

![screen shot 2](https://cloud.githubusercontent.com/assets/23505048/25176068/34c9b2b4-24ba-11e7-8b2e-34cc144e0712.png)

**Comment by JoolsMcFly** [comment]
Syntax `case card=2` is incorrect. It should be like this:
```js
switch (card) {
 case 'value': 
  //code
  break;
}
```
[Doc entry for switch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch).

**Comment by texas2010** [comment]
@blastit 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by blastit** [comment]
Thank you.
