### ISSUE TITLE
Test #1 is not passing yet should be.

### ISSUE THREAD

**Issue by manwithgills** [freeCodeCamp/freeCodeCamp#14498]
Challenge [remove-whitespace-from-start-and-end](http://beta.freecodecamp.com/en/challenges/regular-expressions/remove-whitespace-from-start-and-end) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


let hello = "   Hello, World!  ";
let wsRegex = /^\s+\s+$/; // Change this line
let result = hello.replace(wsRegex, ''); // Change this line
console.log(result);
return result;
```
Have been working on trying to get this to pass. It tells me it should return "Hello, World!". I have consulted the help section in gitter and it was tested in JSFiddle by another camper (https://jsfiddle.net/dq8Lvwda/) and it returns the result. 

Is there an issue with the first test or is it me being a noob? 

Thank you,
Chris

**Comment by JoolsMcFly** [comment]
If you open your browser's console you'll see an error message telling you 
```js
SyntaxError: unknown: 'return' outside of function
```
Just remove the `return` statement,  work on your regexp some more as it's not correct yet and close this issue. :)

Thanks!

**Comment by manwithgills** [comment]
Thank you.
