### ISSUE TITLE
Correct Code doesn't pass

### ISSUE THREAD

**Issue by quesurifn** [freeCodeCamp/freeCodeCamp#14494]
Challenge [verify-an-objects-constructor-with-instanceof](http://beta.freecodecamp.com/en/challenges/object-oriented-programming/verify-an-objects-constructor-with-instanceof) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Correct code doesn't pass.

```js


/* jshint expr: true */

function House(numBedrooms) {
  this.numBedrooms = numBedrooms;
}

// Add your code below this line
let myHouse = House(4);

myHouse instanceof House;



```

**Comment by JoolsMcFly** [comment]
Hint: 
> Create a **new** instance of the House constructor

;)

Problem is with your code, can you close this issue pls?
Thanks.

**Comment by quesurifn** [comment]
Coffee is good. *close*
