### ISSUE TITLE
Use Babel as our transpiler for reactify

### ISSUE THREAD

**Issue by terakilobyte** [FreeCodeCamp/freecodecamp#145]
I've experimented with using babel to transform our jsx and it couldn't be easier.

Including `'babelify'` and using it as the argument to transform instead of envify works. 

I really think we should push for this as a transformer for all of our source files to allow use of es6.

Thoughts?

**Comment by terakilobyte** [comment]
Example in commit e665ac4f9f9309f4c6a319af438f8fe88abc59ea

**Comment by BerkeleyTrue** [comment]
@terakilobyte You can add multiple transform to browserify. No need to overwrite Envify as they serve different functions.

**Comment by terakilobyte** [comment]
@BerkeleyTrue right, I hadn't meant to remove envify permanently, I actually just cut out what was in b.transform and added babelify. I need to stop super tired coding.

**Comment by BerkeleyTrue** [comment]
This is on hold at the moment. Using gulp-babel in combination with gulp-watch entries into infinite loop. Will need to investigate further, but for now we are sticking with current implementation to get the project moving along.

**Comment by BerkeleyTrue** [comment]
This issue is moot if we move to IO.js
