### ISSUE TITLE
first test won't pass

### ISSUE THREAD

**Issue by deaninous** [freeCodeCamp/freeCodeCamp#14505]
Challenge [add-items-using-splice](http://beta.freecodecamp.com/en/challenges/basic-data-structures/add-items-using-splice) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js

"use strict";
function htmlColorNames(arr) {
  // change code below this line
  arr.splice(0, 1, <option1>, );
  arr.splice(1, 1, <option2>)

//I tried this first. same result
  // change code above this line
arr.splice(0, 2, <option1, option2>)
  return arr;
}
 
// do not change code below this line
console.log(htmlColorNames(['DarkGoldenRod', 'WhiteSmoke', 'LavenderBlush', 'PaleTurqoise', 'FireBrick']));

```

**Comment by JoolsMcFly** [comment]
Your code in invalid as indicated by the red X on the left hand side of line 4:
```js
arr.splice(0, 1, <option1>, );
```

I suggest you read the [documentation on splice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) and compare your code with the provided example:
```js
colorScheme = colorChange(colorScheme, 2, '#332327');
```

Also, this is for reporting issues. Please use forums to ask questions.

Can you close this issue pls?

Thanks.
