### ISSUE TITLE
Reviewing Previous lessons on FCC

### ISSUE THREAD

**Issue by ogora** [freeCodeCamp/freeCodeCamp#14501]
How do I review what I have learnt in FCC wihout having to keep clicking the submit button and run. Is there a way to recapitulate what I have learned by just scrolling through a summarized interface?

**Comment by erictleung** [comment]
@ogora thanks for the issue and suggestion. Although this would be convenient, learning and review are up to the student themselves. The fCC curriculum, at least for the HTML and CSS, can be summarized using already made summary sheets found online, which makes having this feature redundant. I'll keep this open for others to weigh in, though.

**Comment by ogora** [comment]
@erictleung  certainly there is plenty of useful videos and fora online . However that requires sometimes sifting through threads of opinions and often vague explanations that eat up a lot of time. A summarized interface of "next" button could help at the end of each lesson  for quick review. Now I recognise that FCC is a a 501 (c) org  which means they dont have enough $$ to meet every whim , however it maybe be something to consider... I appreciate the work FCC is doing.

**Comment by erictleung** [comment]
@ogora don't get me wrong, as a self-proclaimed educator, I think this feature would be really convenient! I would use it myself :smile: But yes, it would be nice to have. Thanks for the feedback and suggestions. We do consider these seriously. However, as you've pointed out, these may be lower priority given other projects.

**Comment by raisedadead** [comment]
@ooade thanks for the feedback and the suggestion. Yup this is something that would be super interesting to have.

Although, I am not sure we can take this up right now as Eric already suggested, but I am going ahead and adding this as one of the first issues on the Open API Project (We will explains the details on that soon).

**Comment by OahMada** [comment]
Looking forward to this feature.
