### ISSUE TITLE
"Unexpected token )"

### ISSUE THREAD

**Issue by wildlifehexagon** [FreeCodeCamp/freecodecamp#1450]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This waypoint loads with the error "Unexpected token )". Unable to submit because of this.

**Comment by BerkeleyTrue** [comment]
I cannot reproduce. Can you try clearing your cache?

**Comment by wildlifehexagon** [comment]
I tried clearing the cache but it didn't help. I'm using Chrome Version 44.0.2403.125 m on Windows 10.

**Comment by benmcmahon100** [comment]
This is an issue I think i pushed a fix for this but i'll check and push it if not

**Comment by BerkeleyTrue** [comment]
@benmcmahon100 where you able to fix this?

**Comment by BerkeleyTrue** [comment]
Just pushed new stuff up. I'm still seeing this.

**Comment by benmcmahon100** [comment]
Yep sorry on this!

**Comment by BerkeleyTrue** [comment]
No worries, I think there is a typo somewhere with the first test on this challenge.

**Comment by benmcmahon100** [comment]
the asset( part is actually missing :p

**Comment by kyrize** [comment]
Awesome. Thanks man.

**Comment by BerkeleyTrue** [comment]
You are welcome! Fix is live!
