### ISSUE TITLE
Can't use Variables 

### ISSUE THREAD

**Issue by ElChepa** [freeCodeCamp/freeCodeCamp#14509]
Challenge [store-data-with-sass-variables](http://beta.freecodecamp.com/en/challenges/sass/store-data-with-sass-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  
  $text-color: red;
  
  .header{
    text-align: center;
  }
  .blog-post {
    color: $text-color;
  }
</style>

<h1 class="header">Learn Sass</h1>
<div class="blog-post">
  <h2>Some random title</h2>
  <p>This is a paragraph with some random text in it</p>
</div>
<div class="blog-post">
  <h2>Header #2</h2>
  <p>Here is some more random text.</p>
</div>
<div class="blog-post">
  <h2>Here is another header</h2>
  <p>Even more random text within a paragraph</p>
</div>

```
This does not work

**Comment by erictleung** [comment]
@ElChepa closing in favor of earlier issue of the same issue https://github.com/freeCodeCamp/freeCodeCamp/issues/14500. Happy coding!
