### ISSUE TITLE
the variables are initialized but cant pass

### ISSUE THREAD

**Issue by Kelvinson** [freeCodeCamp/freeCodeCamp#14503]
Challenge [Understanding Uninitialized Variables](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables#?solution=%0A%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%20%3D%206%3B%0Avar%20b%20%3D%2015%3B%0Avar%20c%20%3D%20%22I%20am%20a%20String%22%3B%0A%2F%2Fa%20%3D%206%3B%0A%2F%2Fb%20%3D%2015%3B%0A%2F%2Fc%20%3D%20%22I%20am%20a%20String%22%3B%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Initialize these three variables
var a = 6;
var b = 15;
var c = "I am a String";
//a = 6;
//b = 15;
//c = "I am a String";
// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";


```

**Comment by mosehub** [comment]
I had the same problem at first, read the instructions carefully.

**Comment by texas2010** [comment]
@Kelvinson 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only. 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
