### ISSUE TITLE
Problem with fetching nearest study group

### ISSUE THREAD

**Issue by PawanMKumar** [freeCodeCamp/freeCodeCamp#14513]
Hey Guys,
There was the problem fetching nearest study groups.
When I try to search nearest study groups based on my location, it was showing groups which is somewhere else.

I tried to search from Hyderabad location in India, It was showing Hyderabad from India along with Hyderabad in Pakistan too with same distance.

I'm using in Chrome in Android 6.0

Please find the screenshot 

http://share.pho.to/Afw7c

**Comment by dhcodes** [comment]
@PawanMKumar Can you paste the url for the search you used. I think it's recently been updated to this: https://www.freecodecamp.com/study-group-directory/

**Comment by PawanMKumar** [comment]
I've used the same link https://www.freecodecamp.com/study-group-directory/

**Comment by dhcodes** [comment]
Okay, I hadn't seen the geolocation issue originally. I believe this is an issue with the coordinates for Hyderabad, Pakistan. I'm taking a look at this.

**Comment by raisedadead** [comment]
Please follow the new issue created above.
