### ISSUE TITLE
Wrong pronoun

### ISSUE THREAD

**Issue by jpdevpro** [freeCodeCamp/freeCodeCamp#14514]
Challenge [Map the Debris](https://www.freecodecamp.com/challenges/map-the-debris) has an issue.

The word "their" refers to a plural, but there is no prior plural for it to refer to.

**Comment by JoolsMcFly** [comment]
I believe it should be _elements' average_ instead of _element's average_ since we're dealing with an array of elements, hence _their_ later on.

I'll fix in staging branch when I get a chance.
