### ISSUE TITLE
java script challange  "Storing Values with the Assignment Operator" 

### ISSUE THREAD

**Issue by kittu401** [freeCodeCamp/freeCodeCamp#14518]
Challenge [Storing Values with the Assignment Operator](https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator#?solution=%0A%2F%2F%20Setup%0Avar%20a%3B%0Avar%20b%20%3D%207%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Aa%20%3D%207%3B%0Ab%20%3D%20a%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var a;
var b = 7;

// Only change code below this line
a = 7;
b = a;

```
![image](https://cloud.githubusercontent.com/assets/19490714/25278051/cc429812-26be-11e7-8fc8-8a2952dcf45b.png)

**Comment by JoolsMcFly** [comment]
You changed `var b=2;` to `var b=7;` when instructions tell you not to.
Revert that and you should get green.

Can you please close this issue please?

Thanks.

**Comment by texas2010** [comment]
@kittu401 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by kittu401** [comment]
yes sure from now i will use forum for help... Thank you
