### ISSUE TITLE
The example website is searching indefinitely and I cannot get a good grasp of the example

### ISSUE THREAD

**Issue by asitaru** [freeCodeCamp/freeCodeCamp#14517]
Challenge [Build a Nightlife Coordination App](https://www.freecodecamp.com/challenges/build-a-nightlife-coordination-app) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by asitaru** [comment]
![screenshot from 2017-04-21 12-18-15](https://cloud.githubusercontent.com/assets/15832572/25271417/c63fb382-268c-11e7-8996-a8ac6a723ee9.png)

**Comment by DavOnGit** [comment]
I get:
```
{
    "statusCode":403,
    "data":"{\"error\": {\"text\": \"The OAuth credentials are invalid\",
    \"id\":"INVALID_OAUTH_CREDENTIALS\"}}"
}
```
