### ISSUE TITLE
The `user` instance is not valid

### ISSUE THREAD

**Issue by PaulChu756** [freeCodeCamp/freeCodeCamp#14525]
#### Issue Description
The `user` instance is not valid. Details: `username` User already exists (value: "paulchu756"); `username` is not unique (value: "paulchu756").

I have created a free code camp account and attempt to link my free code camp account to my github, and this is the error message I receive, please help.

**Comment by erictleung** [comment]
cc/ @QuincyLarson @BerkeleyTrue

**Comment by raisedadead** [comment]
@paul-howard Is this happening on the main website or the beta website.

**Comment by QuincyLarson** [comment]
@paul-howard I've attempted to fix this in our database manually. Please confirm whether you're now able to proceed.

**Comment by raisedadead** [comment]
Closing with no response from OP. Please revert back if this is still an issue for you.
