### ISSUE TITLE
I am on challenge 15, trying to change my CSS style element to blue.  I've already asked for help and I'm doing exactly what the community answered but I can't get to the next step.  Is there something wrong on this page right now?  The code is supposed to look like this: Line 1: <style>   Line 2: h2 {color: blue;}  Line 3: </style>   Am I missing something here? 

### ISSUE THREAD

**Issue by Dweber1020** [freeCodeCamp/freeCodeCamp#14539]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20blue%3B%7D%0A%3C%2Fstyle%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {color: blue;}
</style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by raisedadead** [comment]
Hi @Dweber1020 

Thanks for the report. The issue tracker is for reporting bugs only. 
Your code is incorrect, you are supposed to delete the style and the element.

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!

**Comment by Dweber1020** [comment]
I've attached a screen shot because I've already asked the community for
help and this is what I thought everyone has said.  I'm obviously missing
something because the text is not turning blue but I can't figure out what
I'm screwing up.  I sincerely apologize for the annoyance but I am very
interested in learning this material.

**Comment by raisedadead** [comment]
Hi Dweber, I am really sorry, but you need to visit the forum or the chat room.
