### ISSUE TITLE
error

### ISSUE THREAD

**Issue by evoxtorm** [freeCodeCamp/freeCodeCamp#14532]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript#?solution=%0Avar%20myVar%20%3D%2087%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20i%20%3D%20myVar%20%3B%0AmyVar%20%3D%20i%20%2B%201%3B%0AmyVar%20%3D%20i%2B%2B%20%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myVar = 87;

// Only change code below this line
var i = myVar ;
myVar = i + 1;
myVar = i++ ;


```

**Comment by X-T-G** [comment]
this is my code,and i have passed this course,just like this :
var myVar = 87;
// Only change code below this line
myVar ++;
var myVar;
