### ISSUE TITLE
Won't go to the next Challenge

### ISSUE THREAD

**Issue by MikBH** [FreeCodeCamp/freecodecamp#1453]
Challenge http://beta.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue. 
When you finish the challenge it won't allow you to go to the next one when clicking the green button, nor using the Ctrl + enter. You have to go to MAP and click on the next challenge.

**Comment by meirad** [comment]
I checked it out  and it ran fine. You just have to make sure that you add dashes in your code. 

Ex.) 

    .thick-green-border {
      border: 10px solid green ;
      border-width:10px;
    }
    </style>

    <h2 class='red-text'>CatPhotoApp</h2>

    <img class='smaller-image thick-green-border' src='https://bit.ly/fcc-kittens'/>
