### ISSUE TITLE
Iterate Through an Array with a For Loop

### ISSUE THREAD

**Issue by Retspihaton** [freeCodeCamp/freeCodeCamp#14544]
Challenge [Iterate Through an Array with a For Loop](https://www.freecodecamp.com/challenges/iterate-through-an-array-with-a-for-loop#?solution=%0Avar%20myArr%20%3D%20%5B%202%2C%203%2C%204%2C%205%2C%206%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20total%3D%200%3B%0A%0Afor%20(var%20i%3D%200%3B%20i%20%3C%20myArr.length%3B%20i%2B%2B)%20%7B%0A%20%20total%20%2B%3D%20myArr%5Bi%5D%3B%0A%7D%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myArr = [ 2, 3, 4, 5, 6];

// Only change code below this line
var total= 0;

for (var i= 0; i < myArr.length; i++) {
  total += myArr[i];
}


```

Not a 100% sure if this is a bug, but I was trying to practice getting into the habit of not having the example portion at the top of the page so that I could write the code without some form of "cheat sheet". So I deleted the example portion of it and typed in the correct code and I wasn't able to move forward with the exercise.

**Comment by JoolsMcFly** [comment]
Hi,

fcc checks for two `for` loops, one for the provided example and one for your code.
I guess it should only check for one.

I'll wait for mods to chime in and see if we need to change `>` to `>=` on [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/2913c5c353de7bdf75e864d634b1c0415c9cc02e/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L5218) .

**Comment by rholinshead** [comment]
Hi Retspihaton,

I don't think this is a bug, as the task says to only change the code below the line. This is common behaviour elsewhere, so I don't think it will be changed to use `>=`, unfortunately. If it does get changed, it might be good to check other places where example code is required and see if the same can be done there (the example code is sometimes redundant, like in this example).
