### ISSUE TITLE
#00F00

### ISSUE THREAD

**Issue by Razorsharpy** [freeCodeCamp/freeCodeCamp#14548]
Challenge [Use Abbreviated Hex Code](https://www.freecodecamp.com/challenges/use-abbreviated-hex-code#?solution=%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20%23F00%3B%0A%20%20%7D%0A%20%20.fuchsia-text%20%7B%0A%20%20%20%20color%3A%20%23F0F%3B%0A%20%20%7D%0A%20%20.cyan-text%20%7B%0A%20%20%20%20color%3A%20%230FF%3B%0A%20%20%7D%0A%20%20.green-text%20%7B%0A%20%20%20%20color%3A%20%230F0%3B%0A%0A%3C%2Fstyle%3E%0A%0A%3Ch1%20class%3D%22red-text%22%3EI%20am%20red!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22fuchsia-text%22%3EI%20am%20fuchsia!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22cyan-text%22%3EI%20am%20cyan!%3C%2Fh1%3E%0A%0A%3Ch1%20class%3D%22green-text%22%3EI%20am%20green!%3C%2Fh1%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: #F00;
  }
  .fuchsia-text {
    color: #F0F;
  }
  .cyan-text {
    color: #0FF;
  }
  .green-text {
    color: #0F0;

</style>

<h1 class="red-text">I am red!</h1>

<h1 class="fuchsia-text">I am fuchsia!</h1>

<h1 class="cyan-text">I am cyan!</h1>

<h1 class="green-text">I am green!</h1>
```

**Comment by Razorsharpy** [comment]
.green-text {
color: #0F0;
}

**Comment by JoolsMcFly** [comment]
Works fine if you don't forget to close `.green-text` rule.

Is that what your problem was? If so, can you close this issue please?
Thanks.

**Comment by raisedadead** [comment]
Hi @Razorsharpy 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
