### ISSUE TITLE
Image width challenge will not accept

### ISSUE THREAD

**Issue by mr2fngrz** [freeCodeCamp/freeCodeCamp#14541]
Challenge [Size your Images](https://www.freecodecamp.com/challenges/size-your-images#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%20%20.smaller-image%20%7Bwidth%3A%20100px%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%20alt%3D%22A%20cute%20orange%20cat%20lying%20on%20its%20back.%20%22%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  .smaller-image {width: 100px;}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by texas2010** [comment]
@mr2fngrz 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by grimthedeathdealer** [comment]
whats wrong with it?

**Comment by mr2fngrz** [comment]
That's what I would like to know. I did this code over at least 10 times by
resetting it and it was still not accepted. I verified it with other
campers in the chat room and it was verified good.

**Comment by texas2010** [comment]
Nothing wrong with this challenge. The hint is you forget to apply class into img element.

if you need a help. please use chat room or forum.

have a nice day!

**Comment by Hun9ryGh05t** [comment]
I just had the same problem. The text explaining is a bit misleading to a beginner like myself.

For example, if we wanted to create a CSS class called larger-image that gave HTML elements a width of 500 pixels, we'd use:

<style>
  .larger-image {
    width: 500px;
  }
</style>
Create a class called smaller-image and use it to resize the image so that it's only 100 pixels wide.

This gives the impression that all you need to do is: place . smaller-image {width:100px;} inside your style element. NOPE! Not enough. 
You have to also place   class="smaller-image" between img  and scr, l like below.

<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat">

This isn't a bug but to noobs, like me, it's confusing. Maybe, it's designed that way to force you to work it out yourself; I'm not sure. some of the exercises assume you know things you don't.

**Comment by fpadillajr01** [comment]
hun9ryGh5t - that was hands down the best tip for this challenge i have received --- Thank you!

**Comment by ck-hunu** [comment]
I agree with the people above,

**Comment by mr2fngrz** [comment]
Gho5t gave the BEST advice yet. I've seen far too many standard responses
from mods saying that there is no bug and that the code is wrong. It would
help if you guys can really look INTO our concerns.

While it may not be a bug, the directions are not written correctly for the
challenge
