### ISSUE TITLE
no writing code for me

### ISSUE THREAD

**Issue by seezzaeric** [freeCodeCamp/freeCodeCamp#14545]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=hi%3Eworld%20%0A%3Ch1%3EHello%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
hi>world 
<h1>Hello</h1>

```

**Comment by trikyas** [comment]
I don't think you have tried? Have you read the instructions???

To pass the test on this challenge,
change your h1 element's text to say "Hello World" instead of "Hello".
Then click the "Run tests" button.

**Comment by raisedadead** [comment]
Hi @seezzaeric 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
