### ISSUE TITLE
add anchor tags so users can share their answers to challenges

### ISSUE THREAD

**Issue by dcsan** [FreeCodeCamp/FreeCodeCamp#1454]
on the user profile page you show the users answers
it would be really nice to have a direct anchor to each specific answer eg like:  `##Bonfire XX`

eg

` http://beta.freecodecamp.com/dcsan2#BonFire: Title Case a Sentence`

[http://beta.freecodecamp.com/dcsan2#BonFire: Title Case a Sentence](http://beta.freecodecamp.com/dcsan2#BonFire: Title Case a Sentence)

then users could trade links around to compare answers. this may lead to some people just reading and not doign the work themselves, but could also allow for people to learn the finer points from each other.

**Comment by mistamadd001** [comment]
Could you include a check that validates that the user looking has ALSO completed the lesson thus stopping people from just bypassing lessons by looking at other peoples answers

**Comment by dcsan** [comment]
yes, or we could add something to your own profile to stop you getting points for doing that one if you click other people's solutions? but people are going to find this stuff anyway, there are many FCC blogs now.

**Comment by dcsan** [comment]
but i think discussion info *after* you've completed it is a really great thing - it helps you dig into solutions and really understand the points.

**Comment by ahstro** [comment]
From what I understand, the official stance is [if you want to cheat, you'll find a way](https://github.com/FreeCodeCamp/freecodecamp/issues/356#issuecomment-96308878), so anti-cheat measures doesn't have to be taken.

I like your idea @dcsan, but I'm not going to try to implement it since I haven't bothered to figure out MongoDB enough to add users to my local setup.

**Comment by BerkeleyTrue** [comment]
We have added something like this with Shareable Challenges® :)

Happy Coding!
