### ISSUE TITLE
Repeat a string repeat a string

### ISSUE THREAD

**Issue by randomd00d** [freeCodeCamp/freeCodeCamp#14553]
#### Challenge Name

https://www.freecodecamp.com/challenges/repeat-a-string-repeat-a-string

#### Issue Description

Instructions are not clear enough. How should the string be repeated? Should it be printed to console a specified number of times? No? 

OK, then I should surely alert the user the specified number of times, right? What, wrong again?

Oh, guess I'll just fill an array with the provided string, the number of times that was given. Hm, what, that's not it?

Hmmm... I'll try concatenating the string, and... Ah-ha!

In all seriousness, I feel that the instructions in this exercise should be more precise. Sure, we could just type our code, test it, and see (when it fails) what we should've done. But, why waste the time?

**Comment by erictleung** [comment]
@randomd00d thanks for the feedback. Although a bit sparse, I can see the argument to give more information about the task at hand. Our challenges usually involve looking at the challenge tests in the bottom left to see what the output should be, by the way.

We could change the instructions to something like:

> Return a string that repeats a given string `str` (first argument) for `num` times (second argument). Return an empty string if `num` is not a positive number.

**Comment by hkandrealaw** [comment]
Hello. I had the same issue and I would recommend changing the description to 

> Return a string that contains the string str(first argument) for num times(second argument).
