### ISSUE TITLE
[BUG] Only change the first line

### ISSUE THREAD

**Issue by danylevskyi** [freeCodeCamp/freeCodeCamp#14554]
Challenge [subtract-one-number-from-another-with-javascript](http://beta.freecodecamp.com/en/challenges/basic-javascript/subtract-one-number-from-another-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js
var difference = 45 - 33;
```
I'm getting an error: `Only change the first line`

**Comment by erictleung** [comment]
@danylevskyi thanks for the issue. A similar issue like this has come before. I think it has to do with the tests reading in the solution code and the challenge tests are reading it as well. That challenge test is [counting the number of `difference` variables there](https://github.com/freeCodeCamp/freeCodeCamp/blob/2913c5c353de7bdf75e864d634b1c0415c9cc02e/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L396).

**Comment by JoolsMcFly** [comment]
I have a regexp that will fix that. I'll make a PR right now! :)

**Comment by charlesBak** [comment]
hey @erictleung i did a PR. just checking in

**Comment by raisedadead** [comment]
Refer chat thread: [May 28, 2017 2:25 PM](https://gitter.im/FreeCodeCamp/Contributors?at=592a906beec422e415f73cfd)
