### ISSUE TITLE
Longest Streak/Current Streak Error

### ISSUE THREAD

**Issue by ChessFerret** [FreeCodeCamp/freecodecamp#1455]
It says longest streak is 2 days, but as you see all 48 points were gotten and signed in one day. So the second day still hadn't started. I made 45 (or so) exercises during the morning (01:00-05:00), went to sleep and later(15:00+) continued (3 points).
![screenshot from 2015-08-02 16 41 24](https://cloud.githubusercontent.com/assets/13605068/9026372/b5538058-3935-11e5-8e9d-06754536ad04.png)

**Comment by ahstro** [comment]
Thank you for reporting, but this is already being discussed in #479 and #1075, please post your comments in one of them.

**Comment by ChessFerret** [comment]
Closed due to collaborator pressure.
![image](https://cloud.githubusercontent.com/assets/13605068/9126124/f9ad691a-3cb1-11e5-92ce-56749ae3d75a.png)
Not fixed.

**Comment by ahstro** [comment]
Hahaha :heart_decoration:
