### ISSUE TITLE
I may have gotten this wrong but I've passed.

### ISSUE THREAD

**Issue by n4poleon** [freeCodeCamp/freeCodeCamp#14556]
Challenge [Return Early Pattern for Functions](https://www.freecodecamp.com/challenges/return-early-pattern-for-functions#?solution=%0A%2F%2F%20Setup%0Afunction%20abTest(a%2C%20b)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20if%20(a%20%3C%200%20%7C%7C%20b%20%3C%200)%7B%0A%20%20%20%20console.log(%22undefined%22)%3B%0A%20%20%7D%0A%20%20else%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%20%20return%20Math.round(Math.pow(Math.sqrt(a)%20%2B%20Math.sqrt(b)%2C%202))%3B%0A%20%20%7D%0A%7D%0A%0A%2F%2F%20Change%20values%20below%20to%20test%20your%20code%0AabTest(-2%2C2)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36 OPR/44.0.2510.857</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function abTest(a, b) {
  // Only change code below this line
  
  if (a < 0 || b < 0){
    console.log("undefined");
  }
  else {
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
  }
}

// Change values below to test your code
abTest(-2,2);

```

**Comment by rholinshead** [comment]
Funnily enough, the _return_ value of console.log is actually _undefined_ . In this case, the function both returns and logs _undefined_

**Comment by erictleung** [comment]
@n4poleon thanks for the issue. As @rholinshead has pointed out, it actually does return `undefined`. Console log just logs text to your console and actually returns `undefined`. This is more a "feature" than a bug. I'm closing this as it isn't really a bug. Happy coding!
