### ISSUE TITLE
DevOps: Remove all passwords from database

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#14559]
Refers #9660

**Comment by raisedadead** [comment]
I am reopening this because this is for DevOps (on production) tracking and not codebase.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue we should err on the side of caution wait several weeks after passwordless is running smoothly before we delete all the passwords, just in case something goes wrong and we need to roll back.

**Comment by raisedadead** [comment]
@QuincyLarson I believe we will be taking a dump of the DB before the switch and we can keep the DB as long as required.

**Comment by QuincyLarson** [comment]
@raisedadead Yes - we take database dumps every day. But restoring a dump would be a serious pain. So instead, I propose we wait a few weeks before deleting the passwords, just to make sure passwordless works as expected and we don't need to revert to using passwords temporarily.

**Comment by QuincyLarson** [comment]
This has been taken care of. There are no longer any passwords in the database.
