### ISSUE TITLE
[BUG] You should use two double quotes (") and four escaped double quotes (\").

### ISSUE THREAD

**Issue by danylevskyi** [freeCodeCamp/freeCodeCamp#14555]
Challenge [escaping-literal-quotes-in-strings](http://beta.freecodecamp.com/en/challenges/basic-javascript/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js
var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; // Change this line
```
I'm getting the next error: `You should use two double quotes (") and four escaped double quotes (\").`

**Comment by danylevskyi** [comment]
The issue has gone after I've reloaded the page.

**Comment by fatbacker** [comment]
In your process of teaching you should at least tell people that spacing between quotes is important. It gives us something to look for when we get an error.

**Comment by aliuk2012** [comment]
I had the same issue and after refreshing it also allowed me to successfully pass the challenge. All I did was refresh and then Ran the test

**Comment by gulptech** [comment]
Still a problem.  It does work after a refresh.

**Comment by Ansalibrahim** [comment]
I missed the fullstop at the end of the line.

**Comment by l-white** [comment]
This issue still exists, so the topic shouldn't be closed. The challenge will not pass with correct code:

var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; // Change this line

The error says:
You should use two double quotes (") and four escaped double quotes (\").

**Comment by prativaa** [comment]
yeah the error still exists

**Comment by Ansalibrahim** [comment]
`var myStr = "I am a \"double quoted\" string inside \"double quotes\".";`
This one worked fine for me.

**Comment by rossfaarley** [comment]
I had the same error today. refreshing solved

**Comment by uandrew** [comment]
Still not fixed. The error You should use two double quotes (") and four escaped double quotes (\") remains.

**Comment by CZweers** [comment]
wow, annoying....I can't get past this even after refreshing and rewriting several times....printed it and result is correct...
