### ISSUE TITLE
Need higher resolution GIF for Codepen

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#14561]
Refers a change done via https://github.com/freeCodeCamp/freeCodeCamp/pull/13895

We need a higher resolution GIF for this http://i.imgur.com/oLYs8EA.gif
It has to be hosted on imgur as the original and should have the same steps as done in the original.

We would then need a pull request replacing the image.

The file that needs to be modified is [`seed/challenges/01-responsive-web-design/responsive-web-design-projects.json`](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/responsive-web-design-projects.json#L42)

**Comment by dakshshah96** [comment]
I won't be taking this since this is a 'first timers only' issue 😃

Whoever is willing to take this issue can use [Recordit](http://recordit.co/) to record the gif. The resolution of the generated gif is pretty good and the app is simple to use.

Cheers!

**Comment by fortMaximus** [comment]
Can I give it a shot?

I'm actually a 2nd timer, but pretty much still a newbie.

**Comment by Marmiz** [comment]
As the original low ref .gif owner I can add that it was recorded on:

- MacBook pro with NVIDIA GeForce GT 650M
- QuickTime as the screen recorder
- Processed with imgur built in .gif maker

I strongly suspect that the last one is what caused the end result to be that low quality.

---
Also @raisedadead forgive me for the late reply on the original thread: busy busy days :)

**Comment by raisedadead** [comment]
@Marmiz Sure, thing. Thanks a lot for all the contributions you do.
@dakshshah96 thanks a lot for sharing the resource.
@fortMaximus sure thing if you are interested, you can record and share the link here in this thread for a review. Then once confirmed that the res is good enough, please make a pull request.

**Comment by lkeude96** [comment]
Hi I never contributed to an open source project before. I was wondering if I could work on that

**Comment by usunil0** [comment]
Hi everyone, i have done a video. It is here http://recordit.co/bLSBCcJl7z by using recordit as told by@dakshshah96 ,i am a first-timer so can anybody tell me what to do next.

**Comment by raisedadead** [comment]
@usunil0 

Click the button 

![image](https://cloud.githubusercontent.com/assets/1884376/25383249/dedb8912-29d8-11e7-983a-8596a9677fc2.png)

Generate the GIF and upload it to imgur.
Then share the link here

**Comment by pporche87** [comment]
@raisedadead In what file do we place the link to the new gif before submitting the pull request!?

**Comment by pporche87** [comment]
@raisedadead Created a branch called gif, and added a file called NEWGIF.md to the branch. Submitted the pull request with a link to the image. 

http://imgur.com/vidgif?url=http%3A%2F%2Frecordit.co%2FYK0paRsf6W

**Comment by raisedadead** [comment]
@pporche87 thanks but, your link doesn't fulfil the requirement. I have updated the opening post of the issue for clarification.

@fortMaximus @usunil0 and @pporche87 @lkeude96  if anyone of you can submit an pull request after following the GIF in the opening post, it would be awesome. 

P.S: The recordit video doesn't get converted to GIF on my side, so you may have to use an alternative.

**Comment by pporche87** [comment]
@raisedadead Thanks for the clarity. I'm on it.

**Comment by fortMaximus** [comment]
@raisedadead is [this](https://imgur.com/a/mvCPS ) one good?

**Comment by raisedadead** [comment]
@fortMaximus yes this is perfect, please make a pull request.

**Comment by raisedadead** [comment]
@fortMaximus and everyone else, we have a PR open for this issue. We thank everyone for their interest in fixing this issue.

Please do not be disheartened. We request you to look through any of the open issues that are tagged "help wanted".

Reach out to us in the chat rooms for any assistance, we would be happy to help.

**Comment by fortMaximus** [comment]
@raisedadead Thanks for the support.
