### ISSUE TITLE
With no spaces there is no response. With spaces there is no response. 

### ISSUE THREAD

**Issue by fatbacker** [freeCodeCamp/freeCodeCamp#14564]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%3D%22FirstLine%5Cn%5C%5CSecondLine%5C%5C%5CrThirdline%22%3B%20%2F%2F%20Change%20this%20line%0A%20%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:var myStr="FirstLine\n\\SecondLine\\\rThirdline";
```javascript

var myStr="FirstLine\n\\SecondLine\\\rThirdline"; // Change this line

Everything is go accept for the spacing. And the instructions say no spacing.

 


```

**Comment by erictleung** [comment]
@fatbacker similar to https://github.com/freeCodeCamp/freeCodeCamp/issues/14563. Closing as a non-bug. Happy coding!
