### ISSUE TITLE
instructions incorrect, wrong variable name

### ISSUE THREAD

**Issue by misterrorypond** [FreeCodeCamp/FreeCodeCamp#1457]
I was unable to get the exercise to work with the provided variable name myfloat. The test is seeking myDecimal. I can only get the exercise to work by saying myDecimal, so change the instructions?
![creatingdecimals](https://cloud.githubusercontent.com/assets/11319764/9027715/d8072fe2-3925-11e5-951e-6f02f3aa74de.png)

Challenge http://beta.freecodecamp.com/challenges/creating-decimals has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benmcmahon100** [comment]
Sorry thanks for spotting this i had changed it just before launching will sort now!

**Comment by benschenker** [comment]
Closing as stale
