### ISSUE TITLE
Define which console.log the user should remove

### ISSUE THREAD

**Issue by jdflick** [freeCodeCamp/freeCodeCamp#14570]
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=%0Afunction%20myLocalScope()%20%7B%0A%20%20'use%20strict'%3B%20%0A%20%20var%20myVar%3B%0A%20%20console.log(myVar)%3B%0A%7D%0AmyLocalScope()%3B%0A%0A%2F%2F%20Run%20and%20check%20the%20console%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myLocalScope%0A%0A%2F%2F%20Now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/57.0.2987.98 Chrome/57.0.2987.98 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function myLocalScope() {
  'use strict'; 
  var myVar;
  console.log(myVar);
}
myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope

// Now remove the console log line to pass the test


```
When the challenge is asked it suggests the user remove the console.log to pass the test.
It would be more descriptive to new coders to suggest which console.log to remove and why. 
For instance, saying "Now remove the console log line which references the global scope to pass the test" would hammer home that this is a global parameter for new folks.

**Comment by cmbolton1** [comment]
Instead of deleting the second console.log(myVar); comment it out with //
