### ISSUE TITLE
I went back 20 ?'s from 152 and found no teachings for results.

### ISSUE THREAD

**Issue by fatbacker** [freeCodeCamp/freeCodeCamp#14572]
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "dog, big, ran, quickly";
  // Your code below this line
  

  // Your code above this line
  return result ;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

You  give us no clue what to type here between your //'s I went back over 20 questions to find anything related to results and functions and there is nothing there. I am expected to go on the forum and ask a question I am not even sure how to ask? I couldn't find anything to reference too for answering my question. I also went on the forum to post my code and I get no help. More bugs more bugs more bugs.

**Comment by fatbacker** [comment]
You people write this code like we are supposed to actually know it.

**Comment by JoolsMcFly** [comment]
If you've gone back 20 questions then I guess you've solved [Constructing Strings with Variables](https://www.freecodecamp.com/challenges/constructing-strings-with-variables).

In [Word Blanks](https://www.freecodecamp.com/challenges/word-blank) challenge you're asked to do something similar.

> You will need to use string operators to build a new string, result, using the provided variables: `myNoun`, `myAdjective`, `myVerb`, and `myAdverb`.
> The output should be a complete sentence.

What does that say? Build a sentence using the provided 4 variables.
Example, broken down into multiple lines just to show how to use `+=` operator.

```js
function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "Once upon a time, in a galaxy far, far away lived a ";
  // Your code below this line
  result += myAdjective + " " + myNoun;
  result += " that liked to " + myVerb + " very " + myAdverb;
  // Your code above this line
  return result;
}
```

Everyone working on this project is doing it for free, in their free time. It would be nice if you could stop down-voting every comment we make here.

**Comment by raisedadead** [comment]
@fatbacker thanks for your feedback, but this issue tracker is not for general discussion. You are more than welcome to reach out to the chat room and the forums.

Trust me I share your frustration when I am stuck. But this is a part of learning. I request your patience.

Now, coming to the challenge itself, I think the instructions are clear enough. Any extra clarification would mean giving out the solution itself.

This challenge is in the algorithms, section which aim to be bit more tougher than the previous challenges. Hence the difficulty is justified.

Apologies, that we have to close this issue. Do not worry someone will sure enough get back to you in the chat rooms and the forums.

Goodluck and happy coding.

**Comment by fatbacker** [comment]
I am grateful for the info you sent me on the question I asked in freeCodeCamp. I am new at this so I was clueless as to what they were asking me to do. Now i understand what they were asking for.

Thanks.


________________________________

**Comment by jwynns** [comment]
Same issue here on Windows 10, on both Chrome and Firefox. Seems like it's every other challenge.
