### ISSUE TITLE
wrong feedback 

### ISSUE THREAD

**Issue by elctroshuk** [freeCodeCamp/freeCodeCamp#14583]
#### Challenge Name
Search and Replace 

https://www.freecodecamp.com/challenges/search-and-replace#?solution=%0Afunction%20myReplace(str%2C%20before%2C%20after)%20%7B%0A%20%20var%20exp%20%3D%20new%20RegExp(before%2C%20%22i%22)%3B%0A%20%20return%20str.replace(exp%2C%20after)%3B%0A%7D%0A%0AmyReplace(%22Let%20us%20get%20back%20to%20more%20Coding%22%2C%20%22Coding%22%2C%20%22algorithms%22)%3B%0A

#### Issue Description

when i try to use a specific solution i get the right return value, but still get wrong answer feedback in some of the questions

#### Browser Information

* Browser Name, Version: chrome 
* Operating System: linux fedora 24 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js


function myReplace(str, before, after) {
  var exp = new RegExp(before, "i");
  return str.replace(exp, after);
}

myReplace("Let us get back to more Coding", "Coding", "algorithms");


```
#### Screenshot

![screenshot from 2017-04-25 12-38-04](https://cloud.githubusercontent.com/assets/15894188/25378913/0c0e5092-29b4-11e7-9b1c-4fc5dd837b08.png)

**Comment by JoolsMcFly** [comment]
Hi, 

you're missing something important:

> NOTE: **Preserve the case** of the original word when you are replacing it. For example if you mean to replace the word "Book" with the word "dog", it should be replaced as "Dog"

Just make sure you implement what the note says and you'll get green.

Can you close this issue pls? Thanks.

**Comment by raisedadead** [comment]
Hi @elctroshuk 

Thanks for the report. The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!
