### ISSUE TITLE
Challenge: Factorialize a Number won't let me pass

### ISSUE THREAD

**Issue by tlcowart** [freeCodeCamp/freeCodeCamp#14586]
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#?solution=var%20factorial%20%3D%201%3B%0Afunction%20factorialize(num)%20%7B%0A%20%20for%20(var%20i%20%3D%201%3B%20i%3C%3Dnum%3B%20i%2B%2B)%7B%0A%20%20%20%20factorial%20*%3Di%3B%20%20%0A%20%20%7D%0A%20%20return%20factorial%3B%0A%7D%0Afactorialize(5)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
All of the provided test cases generate a correct factorial answer, any reason why this isn't passing?

My code:
```javascript
var factorial = 1;
function factorialize(num) {
  for (var i = 1; i<=num; i++){
    factorial *=i;  
  }
  return factorial;
}
factorialize(5);

```

**Comment by tlcowart** [comment]
Resolved. Placed var factorial = 1 inside the function.

**Comment by erictleung** [comment]
Closing as resolved. Happy coding!
