### ISSUE TITLE
Bug in code comment for challenge: Declare JavaScript Variables

### ISSUE THREAD

**Issue by TheBestPessimist** [freeCodeCamp/freeCodeCamp#14587]
Challenge [Declare JavaScript Variables](https://www.freecodecamp.com/challenges/declare-javascript-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourName;

// Define myName below this line
var myName = 'bloody variable :^)';

```
In the instructions for this page, nowhere can be found the word "define", but only declare. 
In the code comment however i can see this: ``` Define myName below this line```, and as you can see in the snippet above, i have _defined_ my variable. However i cannot pass the challenge since actually i had to only _declare_ the variable. (like so: ```var myName;```)

**Comment by djengle91** [comment]
I'll go ahead and take this one (will be my first open source contribution!).

**Comment by TheBestPessimist** [comment]
Hehe, no problems.
Haven't reached that far yet.
