### ISSUE TITLE
Passing without changes being made

### ISSUE THREAD

**Issue by Fenwick17** [freeCodeCamp/freeCodeCamp#14582]
Challenge [write-higher-order-arrow-functions](https://beta.freecodecamp.com/en/challenges/es6/write-higher-order-arrow-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36</code>.
When I submit without changing anything it passes. None of the criteria is met, however it still passes. This is leading to inaccurate results when I am trying to complete the task.

```js


const realNumberArray = [4, 5.6, -9.8, 3.14, 42, 6, 8.34];
// change code below this line
var squaredIntegers = realNumberArray;
// change code above this line
// test your code
console.log(squaredIntegers);

```

**Comment by JoolsMcFly** [comment]
Mods can confirm but ES6 is not really ready on the beta site, there are no tests written yet.

**Comment by Fenwick17** [comment]
Is there an ETA on the tests? Might delay progressing on these until complete.

**Comment by sourabhrangdal** [comment]
I had the same issue and interested to know is it okay to continue learning beta.freecodecamp? As I'm a beginner and doesn't understand whether I am progressing or writing a wrong code.

**Comment by dalbinana** [comment]
Same problem and concern here!

**Comment by systimotic** [comment]
We're tackling the ES6 tests in https://github.com/freeCodeCamp/freeCodeCamp/issues/12698 I'm closing this in favor of that. Thanks for reporting everybody!

Happy coding!
