### ISSUE TITLE
Jqeury Level bugged

### ISSUE THREAD

**Issue by Harrmalik** [FreeCodeCamp/freecodecamp#1458]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![image](https://cloud.githubusercontent.com/assets/10894742/9027792/d3b18978-3930-11e5-940d-602369b0185d.png)

**Comment by benmcmahon100** [comment]
Just fixed this now It won't be deployed for a while

**Comment by BerkeleyTrue** [comment]
closing this as there is no description of why it is bugged.
