### ISSUE TITLE
Image not available?

### ISSUE THREAD

**Issue by faizilfanie** [freeCodeCamp/freeCodeCamp#14584]
Challenge [Add Images to your Website](https://www.freecodecamp.com/challenges/add-images-to-your-website#?solution=%0A%3Cstyle%3E.red-text%20%7Bcolor%3A%20red%3B%20%7Dh2%20%7Bfont-family%3A%20Lobster%2C%20Monospace%3B%20%7D%0A%0Ap%20%7Bfont-size%3A%2016px%3Bfont-family%3A%20Monospace%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fwww.your-image-source.com%2Fyour-image.jpg%22%20alt%3D%22https%3A%2F%2Fs3.amazonaws.com%2Ffreecodecamp%2Frelaxing-cat.jpg%22%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.138 Safari/537.36 Vivaldi/1.8.770.56</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>.red-text {color: red; }h2 {font-family: Lobster, Monospace; }

p {font-size: 16px;font-family: Monospace;}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

<img src="https://www.your-image-source.com/your-image.jpg" alt="https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg">
```

**Comment by akshatbahety** [comment]
The image is not being displayed in the output right?

**Comment by texas2010** [comment]
@faizilfanie 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
