### ISSUE TITLE
Profile Lookup Challenge

### ISSUE THREAD

**Issue by emoudy** [freeCodeCamp/freeCodeCamp#14596]
I'm stuck in the Profile Lookup exercise. The code works in my browser but it won't work in Free Code Camp. Not sure what to do.

#### Challenge Name

Challenge Name: Profile Lookup
[Link]( https://www.freecodecamp.com/challenges/profile-lookup#?solution=%0A%2F%2FSetup%0Avar%20contacts%20%3D%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Akira%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Laine%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220543236543%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Pizza%22%2C%20%22Coding%22%2C%20%22Brownie%20Points%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Harry%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Potter%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220994372684%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Hogwarts%22%2C%20%22Magic%22%2C%20%22Hagrid%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Sherlock%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Holmes%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%220487345643%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Intriguing%20Cases%22%2C%20%22Violin%22%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%22firstName%22%3A%20%22Kristian%22%2C%0A%20%20%20%20%20%20%20%20%22lastName%22%3A%20%22Vos%22%2C%0A%20%20%20%20%20%20%20%20%22number%22%3A%20%22unknown%22%2C%0A%20%20%20%20%20%20%20%20%22likes%22%3A%20%5B%22Javascript%22%2C%20%22Gaming%22%2C%20%22Foxes%22%5D%0A%20%20%20%20%7D%0A%5D%3B%0A%0A%0Afunction%20lookUpProfile(firstName%2C%20prop)%20%7B%0A%20%20var%20firstNameCheck%20%3D%20false%3B%0A%20%20var%20propertyCheck%20%3D%20false%3B%0A%20%20var%20index%20%3D%200%3B%0A%20%20%0A%20%20function%20reset()%20%7B%0A%20%20%20%20firstNameCheck%20%3D%20false%3B%0A%20%20%20%20propertyCheck%20%3D%20false%3B%0A%20%20%20%20index%20%3D%200%3B%0A%20%20%7D%0A%0A%20%20function%20infoRequested(index%2C%20prop)%20%7B%0A%20%20%20%20if%20(firstNameCheck%20%3D%3D%3D%20true%20%26%26%20propertyCheck%20%3D%3D%3D%20true)%20%7B%0A%20%20%20%20%20%20return%20contacts%5Bindex%5D%5Bprop%5D%3B%0A%20%20%20%20%7D%20else%20if%20(firstNameCheck%20%3D%3D%3D%20false)%20%7B%0A%20%20%20%20%20%20return%20%22No%20such%20contact%22%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20return%20%22No%20such%20property%22%3B%0A%20%20%20%20%7D%0A%20%20%20%20reset()%3B%0A%20%20%7D%0A%20%20%0A%20%20function%20testProperty(index%2C%20prop)%20%7B%0A%20%20%20%20if%20(contacts%5Bindex%5D.hasOwnProperty(prop))%20%7B%0A%20%20%20%20%20%20propertyCheck%20%3D%20true%3B%0A%20%20%20%20%7D%0A%20%20%20%20infoRequested(index%2C%20prop)%3B%0A%20%20%7D%0A%20%20%0A%20%20function%20testFirstName(firstName%2C%20prop)%20%7B%0A%20%20%20%20for%20(var%20h%20%3D%200%3B%20h%20%3C%20contacts.length%3B%20h%2B%2B)%20%7B%0A%20%20%20%20%20%20if%20(firstName%20%3D%3D%3D%20contacts%5Bh%5D.firstName)%20%7B%0A%20%20%20%20%20%20%20%20firstNameCheck%20%3D%20true%3B%0A%20%20%20%20%20%20%20%20index%20%3D%20h%3B%0A%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20testProperty(index%2C%20prop)%3B%0A%20%20%7D%0A%20%20%0A%20%20testFirstName(firstName%2C%20prop)%3B%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%20your%20function%0AlookUpProfile(%22Kristian%22%2C%20%22lastName%22)%3B%0AlookUpProfile(%22Sherlock%22%2C%20%22likes%22)%3B%0AlookUpProfile(%22Harry%22%2C%20%22likes%22)%3B%0AlookUpProfile(%22Bob%22%2C%20%22number%22)%3B%0AlookUpProfile(%22Akira%22%2C%20%22address%22)%3B%0A )

#### Issue Description

The code works in my browser but it won't worn in Free Code Camp. Not sure what to do.   I solved it using Sublime Text for easier debugging.

#### Browser Information

* Browser Name, Version:  Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code

```js
function lookUpProfile(firstName, prop) {
  var firstNameCheck = false;
  var propertyCheck = false;
  var index = 0;

  function reset() {
    firstNameCheck = false;
    propertyCheck = false;
    index = 0;
  }

  function infoRequested(index, prop) {
    if (firstNameCheck === true && propertyCheck === true) {
      console.log(contacts[index][prop]);
      return contacts[index][prop];
    } else if (firstNameCheck === false) {
      console.log("No such contact");
      return "No such contact";
    } else {
      console.log("No such property");
      return "No such property";
    }
    reset();
  }
  
  function testProperty(index, prop) {
    if (contacts[index].hasOwnProperty(prop)) {
      propertyCheck = true;
    }
    infoRequested(index, prop);
  }
  
  function testFirstName(firstName, prop) {
    for (var h = 0; h < contacts.length; h++) {
      if (firstName === contacts[h].firstName) {
        firstNameCheck = true;
        index = h;
        break;
      }
    }
    testProperty(index, prop);
  }

  testFirstName(firstName, prop);
}


```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/7435053/25416792/9f85ea66-29f4-11e7-8765-7225d4072a5d.png)

![image](https://cloud.githubusercontent.com/assets/7435053/25416828/d20c36d4-29f4-11e7-82a0-9759f661c314.png)

**Comment by Data5tream** [comment]
Your return statements are inside the function `infoRequested` which is called from inside `testProperty` which is called from inside `testFirstName` which is called by your main function called `lookUpProfile`...

Let's say that I tell you ask John if dinner is ready, John will tell you, but does that mean that I know if dinner is ready or not? :wink:

**Comment by mtroj** [comment]
There are two separate conditions to check (name and property), so you need the nested ones. 



function lookUpProfile(firstName, prop){
// Only change code below this line
  for (i=0;i<contacts.length;i++) { 
    
    if(contacts[i].hasOwnProperty(prop)){
        
  if(contacts[i].firstName===firstName){ 
    
    return contacts[i][prop];}
       
  } else {return "No such property";}
  
  }
 return "No such contact";
  

  
// Only change code above this line
} 

// Change these values to test your function
lookUpProfile("Kristian", "likes");
