### ISSUE TITLE
nested array not accepted

### ISSUE THREAD

**Issue by misterrorypond** [FreeCodeCamp/FreeCodeCamp#1459]
Challenge http://beta.freecodecamp.com/challenges/nesting-arrays has an issue.
My basic nested array is not accepted. Unless I've magically forgot arrays, there's another bug!
![nestedarray](https://cloud.githubusercontent.com/assets/11319764/9027799/9983e33e-3928-11e5-9643-c3615ab68c15.png)

**Comment by benmcmahon100** [comment]
Just fixed this here https://github.com/FreeCodeCamp/freecodecamp/commit/c8f2b4a571a51c600772ad1e7cf0ad6e331653f3

**Comment by misterrorypond** [comment]
Still having same issue! 
![nestedarrays2](https://cloud.githubusercontent.com/assets/11319764/9027895/7e9fb508-392c-11e5-9821-1ad16ed1230a.png)

**Comment by benmcmahon100** [comment]
Yeah it hasn't been deployed yet but the fix is in that commit

**Comment by misterrorypond** [comment]
Ok!

**Comment by dgoetsch** [comment]
See notes on PR, didn't see that was waiting for deployment, had assumed bug had persisted.

```
Ah, I just saw that it was fixed, but not deployed. I saw that it still wasn't working and had assumed it had been deployed but is still broken.

Take it or leave it, I'm rather opinionated about tests and code validation and principles of OOO. IMO, regex's are neither safe nor clear in their intent, while an assertion pattern on the objects themselves is.

You may argue that this type of check is slow, but this is a test that is only run once on a button click on a users machine, so a user shouldn't notice any performance issues.
```

**Comment by BerkeleyTrue** [comment]
fixed. We now use super cool functional programming test. `Array.isArray(myArray) && myArray.some(Array.isArray)`
