### ISSUE TITLE
Facebook Login Error

### ISSUE THREAD

**Issue by meirad** [FreeCodeCamp/freecodecamp#1460]
Beta login with Facebook doesn't work.

"https://www.facebook.com/v2.2/dialog/oauth?response_type=code&redirect_uri=http%3A%2F%2Fbeta.freecodecamp.com%2Fauth%2Ffacebook%2Fcallback&scope=email&client_id=1644598365767721" 

[IMG]http://i58.tinypic.com/o02hqf.png[/IMG]

**Comment by benmcmahon100** [comment]
This is a known issue it's currently being added

**Comment by BerkeleyTrue** [comment]
We will not be adding facebook/google to beta site. This is an issue with api tokens for those sites. They will be re-added when we migrate beta to the main url.
