### ISSUE TITLE
Code works fine but does not seem to pass the test

### ISSUE THREAD

**Issue by tobioye88** [freeCodeCamp/freeCodeCamp#14607]
Challenge [Caesars Cipher](https://www.freecodecamp.com/challenges/caesars-cipher#?solution=%0Afunction%20rot13(str)%20%7B%20%2F%2F%20LBH%20QVQ%20VG!%0A%20%20var%20m%20%3D%2077%3B%0A%20%20%2F%2Freturn%20String.fromCharCode(%22Z%22)%3B%0A%20%20%2F%2Freturn%20%22Z%22.charCodeAt(0)%3B%0A%20%20var%20arr%20%3D%20str.split(%22%20%22)%3B%0A%20%20var%20decode%20%3D%20''%3B%0A%20%20for(i%3D0%3B%20i%3Carr.length%3B%20i%2B%2B)%7B%0A%20%20%20%20for(j%3D0%3B%20j%3Carr%5Bi%5D.length%3B%20j%2B%2B)%7B%0A%20%20%20%20%20%20var%20num%20%3D%20arr%5Bi%5D%5Bj%5D.charCodeAt(0)%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20var%20code%3B%0A%20%20%20%20%20%20if(num%20%3E%3D%2065%20%26%26%20num%20%3C%3D%2077)%0A%20%20%20%20%20%20%20%20code%20%3D%20num%20%2B%2013%3B%20%0A%20%20%20%20%20%20else%20if(num%20%3E%2077%20%26%26%20num%20%3C%3D%2090)%0A%20%20%20%20%20%20%20%20code%20%3D%20num%20-%2013%3B%0A%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20code%20%3D%20num%3B%0A%20%20%20%20%20%20decode%20%2B%3D%20String.fromCharCode(code)%3B%0A%20%20%20%20%7D%0A%20%20%20%20decode%20%2B%3D%20'%20'%3B%0A%20%20%7D%0A%20%20return%20decode%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%0Arot13(%22GUR%20DHVPX%20OEBJA%20QBT%20WHZCRQ%20BIRE%20GUR%20YNML%20SBK.%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function rot13(str) { // LBH QVQ VG!
  var m = 77;
  var arr = str.split(" ");
  var decode = '';
  for(i=0; i<arr.length; i++){
    for(j=0; j<arr[i].length; j++){
      var num = arr[i][j].charCodeAt(0);
      
      var code;
      if(num >= 65 && num <= 77)
        code = num + 13; 
      else if(num > 77 && num <= 90)
        code = num - 13;
      else
        code = num;
      decode += String.fromCharCode(code);
    }
    decode += ' ';
  }
  return decode;
}

// Change the inputs below to test
rot13("GUR DHVPX OEBJA QBT WHZCRQ BIRE GUR YNML SBK.");

```

**Comment by lynxlynxlynx** [comment]
The bug is in your code, not the test. Check the length of input and output strings and you will see they don't match. Finding the actual problem and fixing it should be trivial from there.

Please close this report.
