### ISSUE TITLE
help i m biginer

### ISSUE THREAD

**Issue by Deekshalavania** [freeCodeCamp/freeCodeCamp#14601]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello</h1>

```

**Comment by medabest1234** [comment]
-
