### ISSUE TITLE
“Every HTML element is a child of your body element”

### ISSUE THREAD

**Issue by jrpool** [freeCodeCamp/freeCodeCamp#14608]
Challenge [Target the Children of an Element Using jQuery](https://www.freecodecamp.com/challenges/target-the-children-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30</code>.

Every HTML element in the body, not those in the head. And guaranteed only to be a descendant, not necessarily a child.

**Comment by Ntropish** [comment]
I agree to both points. Also, talking about property inheritance isn't necessary for this challenge. How about:

When HTML elements are placed one level below another they are called `children` of that element. For example, the `button` elements in this challenge with the text "#target1", "#target2", and "#target3" are all children of the `<div class="well" id="left-well">` element.

jQuery has a function called `children()` that allows you to access the children of whichever element you've selected.

Here's an example of how you would use the `children()` function to give the children of your `left-well` element the color blue:

`$("#left-well").children().css("color", "blue")`

---

Give all the children of your `right-well` element the color orange.

**Comment by Ntropish** [comment]
I'll put a pull request together with those changes. I'm sure it could be improved further though so suggestions would be nice.

**Comment by Ntropish** [comment]
I'm new to this, what do we do about other translations?

**Comment by jrpool** [comment]
Thank you. That fix looks good to me.

**Comment by jrpool** [comment]
> I'm new to this, what do we do about other translations?

I’m not familiar with how FCC deals with localization.
