### ISSUE TITLE
[beta] Update email API error message do not reach the toaster logic

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#14604]
I have added a minor change to the update email logic in the passwordless implementation (#9660), to ensure delivery for success case.

But the error cases still need to be investigated.

**Comment by BerkeleyTrue** [comment]
The issue should be around this catch operator https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/routes/settings/redux/update-user-saga.js#L41

**Comment by raisedadead** [comment]
Closing in favor of more relevant issue linked.

**Comment by piggito** [comment]
@raisedadead Can we reopen this issue? I created a PR for #15876 but due to the front changes in staging we will need another PR for this branch.
I am already working on this fix for staging branch btw.
