### ISSUE TITLE
tests: Move from jsonlint-cli to eslint-plugin-json

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#14621]
We currently use a jsonlint-cli to lint our json files, but this hasn't worked that well with Windows machines. 

There is now an eslint plugin module for linting json files. We should move to using this plugin to lint everything. 

This should involve adding the plugin to both package.json dev dependencies and to the plugins section of .eslintrc. You will also need to update the npm scripts that run lint tasks.

This should greatly simplify our linting story.

**Comment by Ethan-Arrowood** [comment]
I'll give this a shot 😄

**Comment by BerkeleyTrue** [comment]
eslint-plugin-json is currently not usable for our cases
