### ISSUE TITLE
Answer returned is correct but Testcase is displaying wrong answer

### ISSUE THREAD

**Issue by SSheorain** [freeCodeCamp/freeCodeCamp#14628]
Challenge [Counting Cards](https://www.freecodecamp.com/challenges/counting-cards#?solution=%0Avar%20c%3D0%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20if(card%3D%3D2%7C%7Ccard%3D%3D3%7C%7Ccard%3D%3D4%7C%7Ccard%3D%3D5%7C%7Ccard%3D%3D6)%0A%20%20%20%20c%3Dc%2B1%3B%0A%20%20else%20if(card%3D%3D10%7C%7Ccard%3D%3D'J'%7C%7Ccard%3D%3D'Q'%7C%7Ccard%3D%3D'K'%7C%7Ccard%3D%3D'A')%0A%20%20%20%20c%3Dc-1%3B%0A%20%20%0A%20%20if(c%3E0)return%20c%2B%22%20Bet%22%3B%0A%20%20else%20return%20c%2B%22%20Hold%22%3B%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(10)%3B%20cc('J')%3B%20cc('Q')%3B%20cc('K')%3B%20cc('A')%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/48.0.2564.82 Chrome/48.0.2564.82 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var c=0;

function cc(card) {
  // Only change code below this line
  if(card==2||card==3||card==4||card==5||card==6)
    c=c+1;
  else if(card==10||card=='J'||card=='Q'||card=='K'||card=='A')
    c=c-1;
  
  if(c>0)return c+" Bet";
  else return c+" Hold";
  
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(10); cc('J'); cc('Q'); cc('K'); cc('A');

```

**Comment by minukumari** [comment]
![counting card](https://cloud.githubusercontent.com/assets/26218290/25529432/9c62af0c-2c3f-11e7-94e6-e36808487a78.PNG)

**Comment by minukumari** [comment]
u did not add for card 7,8,9.

**Comment by SSheorain** [comment]
it's not necessary to add 0 to current value ... i guess that doesn't change the value of count

**Comment by SSheorain** [comment]
@minukumari  i figured out where my code was going wrong.. Thanks for your response and it was not '7 8 9' which were faulty .. i changed variable name of count to c.. that was the issue.

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
