### ISSUE TITLE
Issue - Comparison with the Less Than Operator - less than 0 gives "55 or Over" result

### ISSUE THREAD

**Issue by AlexxMart** [freeCodeCamp/freeCodeCamp#14623]
Challenge [Comparison with the Less Than Operator](https://www.freecodecamp.com/challenges/comparison-with-the-less-than-operator#?solution=%0Afunction%20testLessThan(val)%20%7B%0A%20%20if%20(val)%20%7B%20if%20(val%20%3C%2025)%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Under%2025%22%3B%0A%20%20%7D%0A%20%20%0A%20%20if%20(val)%20%7B%20if%20(val%20%3C%2055)%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Under%2055%22%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20%2255%20or%20Over%22%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestLessThan(24)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function testLessThan(val) {
  if (val) { if (val < 25) // Change this line
    return "Under 25";
  }
  
  if (val) { if (val < 55) // Change this line
    return "Under 55";
  }
  
  return "55 or Over";
}

// Change this value to test
testLessThan(24);

```

**Comment by AlexxMart** [comment]
![fcc issue](https://cloud.githubusercontent.com/assets/26124377/25507562/ff37d0d4-2b69-11e7-943b-d3c18527b9da.png)

**Comment by JoolsMcFly** [comment]
Read up documentation about Boolean values and what JavaScript considers a truthy value. Then think about `if (val)`.

Challenge is fine, you can close this issue.

Thanks.
