### ISSUE TITLE
wrong class in directions

### ISSUE THREAD

**Issue by haasDev** [FreeCodeCamp/freecodecamp#1463]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

the directions say to add "fluid-container" class but it should be "container-fluid"

**Comment by ahstro** [comment]
This has been fixed in [beta](http://beta.freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers). Please close :)
