### ISSUE TITLE
Write Reusable JavaScript with Functions won't run

### ISSUE THREAD

**Issue by kiliffinjames** [freeCodeCamp/freeCodeCamp#14634]
Challenge [Write Reusable JavaScript with Functions](https://www.freecodecamp.com/challenges/write-reusable-javascript-with-functions#?solution=%0A%2F%2F%20Example%0Afunction%20ourReusableFunction()%20%7B%0A%20%20console.log(%22Heyya%2C%20World%22)%3B%0A%7D%0A%0AourReusableFunction()%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20reusableFunction()%20%7B%0A%20%20console.log(%22Hi%2CWorld%22)%3B%0A%7D%0A%0AreusableFunction()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourReusableFunction() {
  console.log("Heyya, World");
}

ourReusableFunction();

// Only change code below this line
function reusableFunction() {
  console.log("Hi,World");
}

reusableFunction();

```

**Comment by kiliffinjames** [comment]
Please what's is wrong with above code? It won't run saying, "reusableFunction should output "Hi World" to the dev console  "

**Comment by texas2010** [comment]
@kiliffinjames 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only. 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
