### ISSUE TITLE
Clicking on map opens up new page instead of a sidemenu

### ISSUE THREAD

**Issue by arshdkhn1** [freeCodeCamp/freeCodeCamp#14637]
Hi
I have tried to search for similar issue but haven't found it so I am opening it. IMHO map should be in sidemenu instead of separate page so that I can move to challenges staying on the same page. Opening new page is bad UX in my opinion.

Thanks

**Comment by raisedadead** [comment]
You are on beta website right? This is done because of an overhaul to frontend. We have moved to react, and would have a side nav single page UI in future.

**Comment by arshdkhn1** [comment]
@raisedadead cool :+1:

**Comment by arshdkhn1** [comment]
This is something not related to this issue but I would like bring it to your attention. @raisedadead can you tell whether mocha tutorials are workin or not ? While checking the tests offline, it works as expected but unfortunately when I enter glitch url on beta site that doesn't work.. I am interested in knowing how does only providing url checks whether user has made right changes or not.

**Comment by raisedadead** [comment]
Can you open a new issue for that, possibly with steps to reproduce and some screen shots, I personally have not checked that. Will take a look though.
