### ISSUE TITLE
Validation Issue

### ISSUE THREAD

**Issue by lightarcade** [freeCodeCamp/freeCodeCamp#14631]
Challenge [Declare String Variables](https://www.freecodecamp.com/challenges/declare-string-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var firstName = "Alan";
var lastName = "Turing";

// Only change code below this line
var myFirstName = "Kumar"
var myLastName = "Ethamukkala"


```

**Comment by raisedadead** [comment]
The issue tracker is for reporting bugs only. 

Please use the chat rooms: 
- [`HTML/CSS help chat room`](https://gitter.im/FreeCodeCamp/Help) 
- [`JavaScript help chat room`](https://gitter.im/FreeCodeCamp/HelpJavaScript) 
- [`Other Official Rooms`](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) 

or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge.

Happy Coding!

**Comment by minukumari** [comment]
use semicolon at the end.
like this-
var myFirstName = "Kumar";
var myLastName = "Ethamukkala";
