### ISSUE TITLE
log output not defined

### ISSUE THREAD

**Issue by khamp19** [freeCodeCamp/freeCodeCamp#14639]
Code getting error "logOutput not defined".

Challenge [write-reusable-javascript-with-functions](http://beta.freecodecamp.com/en/challenges/basic-javascript/write-reusable-javascript-with-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


// Example
function ourReusableFunction() {
  console.log("Heyya, World");
}

ourReusableFunction();

// Only change code below this line
function reusableFunction() {
  console.log("Hi World");
}

reusableFunction();

```

**Comment by erictleung** [comment]
@khamp19 thanks for the issue, but I'm unable to reproduce your issue. I clicked on the challenge directly from the link you have given and then copy-pasted your code and was able to pass the challenge. Let me know if you're able to pass it that way. Or if there's another way you have issues with the challenge, let us know.

**Comment by raisedadead** [comment]
Please revert, to get this reopened.
