### ISSUE TITLE
Code window does not scroll automatically

### ISSUE THREAD

**Issue by invinciblycool** [freeCodeCamp/freeCodeCamp#14632]
#### Challenge Name

Every challenge

#### Issue Description

When writing codes which exceed the length of the code Window, it does not scroll down automatically instead one has to scroll it manually.
#### Browser Information

* Browser Name, Version: Chrome, Version-58.0.3029.81
* Operating System: Windows
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```

**Comment by raisedadead** [comment]
Can you provide a few screen shots? Also please provide details if you are on the beta website or on the main website.

**Comment by invinciblycool** [comment]
I tried clearing cookies and site plugin data and now it seems to work fine.
Thanks for the prompt response

**Comment by raisedadead** [comment]
Great that you got it resolved. Happy coding!
