### ISSUE TITLE
npm run only-once throw Error: Connection strategy not found     at MongoStore 

### ISSUE THREAD

**Issue by tharun26** [freeCodeCamp/freeCodeCamp#14646]
#### Issue Description
'I am following the Getting-Started instructions on https://forum.freecodecamp.com/t/how-to-clone-and-setup-the-free-code-camp-website-on-a-windows-pc/19366

Mongo db is running in the back

After the command rpm run only-once, I get this (see below)...

[command_like_logs.txt](https://github.com/freeCodeCamp/freeCodeCamp/files/966517/command_like_logs.txt)

$ npm run only-once

> freecodecamp@0.1.0 only-once F:\FreeCodeCamp\freeCodeCamp
> npm run create-rev && echo '/****/' && echo 'Seeding Database' && echo '/****/' && node seed && echo '/****/' && echo 'Seeding Completed' && echo '/****/'

> freecodecamp@0.1.0 create-rev F:\FreeCodeCamp\freeCodeCamp
> node -e "var fs = require('fs'); fs.access('./server/rev-manifest.json', function(err) { if (err) { console.log('\n\ncreating manifest\n\n'); return fs.writeFileSync('server/rev-manifest.json', '{}'); } console.log('\n\nrev-manifest present\n\n'); });"

rev-manifest present

'/****/'
'Seeding Database'
'/****/'

The user model "User" is attached to an application that does not specify
whether other sessions should be invalidated when a password or
an email has changed. Session invalidation is important for security
reasons as it allows users to recover from various account breach
situations.

We recommend turning this feature on by setting
"logoutSessionsOnSensitiveChanges" to true in
server/config.json (unless you have implemented your own solution
for token invalidation).

We also recommend enabling "injectOptionsFromRemoteContext" in
User's settings (typically via common/models/*.json file).
This setting is required for the invalidation algorithm to keep
the current session valid.

Learn more in our documentation at
https://loopback.io/doc/en/lb2/AccessToken-invalidation.html

The user model "user" is attached to an application that does not specify
whether other sessions should be invalidated when a password or
an email has changed. Session invalidation is important for security
reasons as it allows users to recover from various account breach
situations.

We recommend turning this feature on by setting
"logoutSessionsOnSensitiveChanges" to true in
server/config.json (unless you have implemented your own solution
for token invalidation).

We also recommend enabling "injectOptionsFromRemoteContext" in
user's settings (typically via common/models/*.json file).
This setting is required for the invalidation algorithm to keep
the current session valid.

Learn more in our documentation at
https://loopback.io/doc/en/lb2/AccessToken-invalidation.html

Error: Connection strategy not found
    at MongoStore (F:\FreeCodeCamp\freeCodeCamp\node_modules\connect-mongo\src\index.js:105:23)
    at sessionsMiddleware (F:/FreeCodeCamp/freeCodeCamp/server/middlewares/sessions.js:15:12)
    at EventEmitter.proto.middlewareFromConfig (F:\FreeCodeCamp\freeCodeCamp\node_modules\loopback\lib\server-app.js:74:25)
    at F:\FreeCodeCamp\freeCodeCamp\node_modules\loopback-boot\lib\executor.js:353:9
    at Array.forEach (native)
    at setupMiddleware (F:\FreeCodeCamp\freeCodeCamp\node_modules\loopback-boot\lib\executor.js:340:14)
    at execute (F:\FreeCodeCamp\freeCodeCamp\node_modules\loopback-boot\lib\executor.js:40:3)
    at bootLoopBackApp (F:\FreeCodeCamp\freeCodeCamp\node_modules\loopback-boot\index.js:154:3)
    at Object.<anonymous> (F:/FreeCodeCamp/freeCodeCamp/server/server.js:42:1)
    at Module._compile (module.js:570:32)
    at loader (F:\FreeCodeCamp\freeCodeCamp\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (F:\FreeCodeCamp\freeCodeCamp\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "only-once"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! freecodecamp@0.1.0 only-once: `npm run create-rev && echo '/****/' && echo 'Seeding Database' && echo '/****/' && node seed && echo '/****/' && echo 'Seeding Completed' && echo '/****/'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the freecodecamp@0.1.0 only-once script 'npm run create-rev && echo '/****/' && echo 'Seeding Database' && echo '/****/' && node seed && echo '/****/' && echo 'Seeding Completed' && echo '/****/''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the freecodecamp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run create-rev && echo '/****/' && echo 'Seeding Database' && echo '/****/' && node seed && echo '/****/' && echo 'Seeding Completed' && echo '/****/'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freecodecamp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls freecodecamp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\FreeCodeCamp\freeCodeCamp\npm-debug.log

**Comment by mjgreen145** [comment]
Hi @tharun26, I also just experienced this on my mac, but fixed it when I realised I had missed the step where you copy the `.sample.env` file into a file called `.env`:

`cp sample.env .env` (or the equivalent on Windows)

Have you definitely completed this step?
