### ISSUE TITLE
Page stops loading after pressing Run tests

### ISSUE THREAD

**Issue by socialnatworks** [freeCodeCamp/freeCodeCamp#14648]
#### Challenge Name
https://www.freecodecamp.com/challenges/seek-and-destroy

#### Issue Description
After I entered the codes as attached and pressed Run Tests, the page just stops loading. The mouse becomes a typing cursor. I've reset the codes and pasted that in again and it freezes again.

#### Browser Information
* Browser Name, Version: Chrome Version 55.0.2883.95 (64-bit)
* Operating System: macOS Sierra Version 10.12.4
* Mobile, Desktop, or Tablet: MacBook Pro (Retina, Mid 2012)

#### Your Code

```js
see below


```
#### Screenshot

<img width="1254" alt="screen shot 2017-04-30 at 9 54 16 am" src="https://cloud.githubusercontent.com/assets/4922455/25560969/a533f7c4-2d8b-11e7-863a-23553709c5e9.png">

**Comment by erictleung** [comment]
@socialnatworks thanks for the issue. Can you please share your code to help us help you quicker? Thanks!

**Comment by raisedadead** [comment]
Hi @socialnatworks 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.

Happy Coding!
