### ISSUE TITLE
This challenge defines where the person  should edit, however it's incorrect

### ISSUE THREAD

**Issue by jdflick** [freeCodeCamp/freeCodeCamp#14641]
The challenged misses a key issue, that is to add a comma after the first entry.  I suggest removing the "add record here" field and just suggesting the student edit the code in the challenge.  This is otherwise confusing as students are not used to editing areas not indicated in  the challenge.

**Comment by OFFLlNE** [comment]
You should provide more details.. Try using the template








#### Challenge Name



#### Issue Description



#### Browser Information


* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

**Comment by jdflick** [comment]
**Challenge Name**

Manipulating Complex Objects 

**Issue Description**

The challenge misses a key issue, that is to add a comma after the first entry. I suggest removing the "add record here" field and just so suggest the student edit the code in the challenge. This is otherwise confusing as students are not used to editing areas not indicated in the challenge.

**Browser Information**

Browser Name, Version: Chromium, 58+
Operating System: Linux
Mobile, Desktop, or Tablet: Laptop
Your Code
`      "LP" ],
    "gold": true
  },
  // Add record here
  
  {
    "artist": "Nile",
    "title": "Black Seeds of Vengeance",
    "release_year": 2000,`

**Screenshot**

![missing_comma](https://cloud.githubusercontent.com/assets/26047810/25775026/0bd39b42-3250-11e7-9d95-7696ba22ce24.png)

**Comment by veeeeeee** [comment]
I think we're used to seen // instructions as "only edit below this line" so we are conditioned to only make changes below // [some kind of directions]. I also didn't realize that the `Note
You will need to place a comma after every object in the array, unless it is the last object in the array.` instructions was a suggestion to do exactly that--I think I assumed it was talking about commas after each item of metadata. These two things add up to a whole lot of confusion, judging by all the dismay!
