### ISSUE TITLE
Quotation Error

### ISSUE THREAD

**Issue by PizzaPokerGuy** [freeCodeCamp/freeCodeCamp#14645]
The test should be written in a way where 'Hi World' and "Hi World" are both passing solutions. This will be frustrating and confusing for users as both are strings and so early on may not be able to see such a small detail in terms of what quotations. 

Challenge [write-reusable-javascript-with-functions](http://beta.freecodecamp.com/en/challenges/basic-javascript/write-reusable-javascript-with-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


// Example
function ourReusableFunction() {
  console.log("Heyya, World");
}

ourReusableFunction();

// Only change code below this line
function reusableFunction(){
  console.log("Hi World");
}
reusableFunction();
```

**Comment by erictleung** [comment]
@PizzaPokerGuy thanks for the issue, but I can't reproduce your issue. I'm able to pass the challenge with both 

```js
function reusableFunction(){
  console.log("Hi World");
}
reusableFunction();
```

and

```js
function reusableFunction(){
  console.log('Hi World');
}
reusableFunction();
```
