### ISSUE TITLE
problem UI/UX Design

### ISSUE THREAD

**Issue by mkjn184** [freeCodeCamp/freeCodeCamp#14649]
Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by erictleung** [comment]
@mkjn184 thanks for the issue. Can you elaborate on what you mean by "problem UI/UX design"? Do you mean the example portfolio page? Or do you mean the freeCodeCamp page itself? The example is simply an example to build your portfolio. Please give us more information on what your issue is.
