### ISSUE TITLE
Small issue on Waypoint: Add Borders Around your Elements

### ISSUE THREAD

**Issue by willthamic** [FreeCodeCamp/freecodecamp#1464]
There is a small mistake on page http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements.
>>The fifth criteria for completion says:
Your img element should be green.
When it should say:
You img element's border should be green.

**Comment by ahstro** [comment]
This has been fixed in [beta](http://beta.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements). Please close :)
