### ISSUE TITLE
css override not working

### ISSUE THREAD

**Issue by neek81** [freeCodeCamp/freeCodeCamp#14656]
Challenge [Override Styles in Subsequent CSS](https://www.freecodecamp.com/challenges/override-styles-in-subsequent-css#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blue-text%20%7Bcolor%3A%20blue%3B%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22pink-text%22%20%22blue-text%22%3EHello%20World!%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
![screenshot 1](https://cloud.githubusercontent.com/assets/26780273/25566954/95ffd342-2db1-11e7-8651-dbae4bba305a.png)

```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {color: blue;}
</style>
<h1 class="pink-text" "blue-text">Hello World!</h1>

```
The color changes only if I change the class, but I'm still not passing the challenge. I did it in chrome, ME and IE 11.
![screenshot 2](https://cloud.githubusercontent.com/assets/26780273/25566992/35354ec4-2db2-11e7-8dd6-b6b8fbe52017.png)

**Comment by Keftie** [comment]
You should have a space between your classes. Not in seperate "".
class="pink-text blue-text"
