### ISSUE TITLE
Sorting in an array in place

### ISSUE THREAD

**Issue by allisonPlusPlus** [freeCodeCamp/freeCodeCamp#14657]
Challenge [Sort Arrays with sort](https://www.freecodecamp.com/challenges/sort-arrays-with-sort#?solution=%0Avar%20array%20%3D%20%5B1%2C%2012%2C%2021%2C%202%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Aarray.sort(function(a%2Cb)%20%7B%0A%20%20return%20a%20-%20b%3B%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var array = [1, 12, 21, 2];

// Only change code below this line.

array.sort(function(a,b) {
  return a - b; });

```

**Comment by priidikvaikla** [comment]
Hey, currently your code is sorting the elements from smallest to largest. If you want to sort them from largest to smallest then you should to `return b - a;`

**Comment by allisonPlusPlus** [comment]
Thank you friend!
