### ISSUE TITLE
wrong results espected @ Sum All Primes algorithm 

### ISSUE THREAD

**Issue by zuzubi** [freeCodeCamp/freeCodeCamp#14658]
#### Challenge Name

SUM ALL PRIMES

https://www.freecodecamp.com/challenges/sum-all-primes#?solution=%0Afunction sumPrimes(num) {%0A var taco%3D[]%3B%0A %0A var bell%3D[]%3B%0A var bello%3D[]%3B%0A var idefix%3D0%3B%0A var x%3D0%3B%0A var t%3D0%3B%0A for (var i%3D0%3Bi<num-1%3Bi%2B%2B){%0A taco[i]%3Di%2B1%3B%2F%2Ftaco[0]%3D1%2C taco[1]%3D2%2C ... %2Ctaco[num-2]%3Dnum-1%0A }%0A for (var y%3Dnum-2%3By>%3D0%3By--){%0A%0A for (i%3Dy%3Bi>1%3Bi--){%0A if (taco[y]%25i%3D%3D%3D0){%0A bell[x]%3Dtaco[y]%3B%0A x%2B%2B%3B%0A }%0A }%0A %0A %0A }%0A for (i%3D0%3B i<bell.length-1%3B i%2B%2B){%0A if(bell[i]%3D%3D%3Dbell[i%2B1]){%0Abell.splice(i%2C1)%3B %0A }%0A }%0A for (i%3D0%3B i<bell.length-1%3B i%2B%2B){%0A if(bell[i]%3D%3D%3Dbell[i%2B1]){%0Abell.splice(i%2C1)%3B %0A }%0A }%0A %0A for (i%3D0%3B i<taco.length%3Bi%2B%2B){%0A for (var p%3D0%3B p<bell.length%3Bp%2B%2B){%2F%2F%0A if(bell[p]%3D%3D%3Dtaco[i]){%0A taco.splice(i%2C1)%3B%0A i%3Di-1%3B%0A }%0A }%0A }%0A taco.shift()%3B%0A for (i%3D0%3Bi<taco.length%3Bi%2B%2B){%0A idefix%3Didefix%2Btaco[i]%3B%0A }%0A %0A return idefix%2Bnum%3B%0A}%0A%0AsumPrimes(977)%3B%0A

#### Issue Description

Hey. I'm doing the 'Sum all Primes' algorithm challenge. The One after the 'Sum All Odd Fibonacci Numbers'.
The challenge is to sum all prime numbers up to a given number, including the given number in the sum. 
For the number 10 you expect the result 17. But adding up all prime numbers up to and including 10 results in: 2+3+5+7+10=27. So this time you are not including the 10 in the sum.
The following expected result adds the given number on top of the sum of all prime numbers under it:
'sumPrimes(977) should return 73156' .
So there's no way to do this algorithm challenge right.
Either you do it including the provided number or not.

**Comment by guptar8jan** [comment]
@zuzubi- You want to include prime numbers up to the given max number in the sum.
2+3+5+7=17 is the correct answer when looking for prime number up to 10, since 10 is not a prime number.
sumPrimes(977) should return 73156 is also correct because 977 happens to be prime number.
