### ISSUE TITLE
Bonfire: Friendly Date Ranges

### ISSUE THREAD

**Issue by viniciuskneves** [FreeCodeCamp/FreeCodeCamp#1465]
After completing the test, the green button (to go to the next chapter) is not clickable, I could advance just with ctrl + enter.

Tried to be as brief as possible to explain this issue :)

**Comment by ahstro** [comment]
Could you provide the code and browser used? I'm not sure how to tackle this, but I'm sure that info will help :)

**Comment by viniciuskneves** [comment]
I've used Chrome.

The code has passed. Might it be a bug in the code? I mean, the code might has crashed the app?

**Comment by benschenker** [comment]
Hey @viniciuskneves I'm going to close this issue as stale, but feel free to reopen if it is still a problem for you
