### ISSUE TITLE
Can’t log in with Github 

### ISSUE THREAD

**Issue by jnthngc** [freeCodeCamp/freeCodeCamp#14669]
#### Issue Description
I've used FCC on another computer and I'm currently on the Basic Algorithm Scripting section. However, when I try to log in to FCC on my personal/primary computer (I signed up via Github), it takes me to the "Map" page and says "Oops! Something went wrong. Please try again later". It's done this every time I try for the last month. Is there a fix for this?

#### Browser Information
Chrome, Safari, and Firefox on a Mac.

**Comment by erictleung** [comment]
cc/ @QuincyLarson @BerkeleyTrue

**Comment by raisedadead** [comment]
@jnthngc Sorry to hear that you are facing this issue. Can you please drop an email to team@freecodecamp.com, we will be able to request and validate the private information related to your account that way.

Please provide the details of your github username, and the email that is associated with freeCodeCamp in the email. 

We will try and get back as soon as we can.

**Comment by stratospapazoglou** [comment]
Neither I can't login with github. I have already sent an email to team@freecodecamp.com. Can you help?
![error message](https://user-images.githubusercontent.com/33263269/32406265-f430b4da-c17d-11e7-82ac-40fd886e5a57.jpg)

**Comment by raisedadead** [comment]
@stratospapazoglou 
Yes, we have disabled new signups via GitHub, you can expect to see this button gone soon too(when we release next version).
If you are signing up for the first time, please do so via the email, and then link up GitHub through the settings on your profile.

Thanks.

**Comment by stratospapazoglou** [comment]
Thank you!

2017-11-04 20:15 GMT+02:00 mrugesh mohapatra <notifications@github.com>:

**Comment by shuvongkor-barman** [comment]
I can't not sign in to freeCodeCamp using my GitHub account. I used it two days ago but it is not working. And I don't have any other way to sign in.

Please Help Me. I don't want to loose my progress.

My freeCodeCamp User Name:  **shuvongkor-barman**

![01](https://user-images.githubusercontent.com/37457267/40265651-e8898984-5b5d-11e8-8468-acc26dfb955f.jpg)
![02](https://user-images.githubusercontent.com/37457267/40265652-e960e0d2-5b5d-11e8-9a1f-5f426d0f6b3f.jpg)

**Comment by Sy-CoDe** [comment]
@shuvongkor-barman (note the msg from freecodecamp) https://github.com/freeCodeCamp/freeCodeCamp/issues/14669#issuecomment-341918303 :
> @raisedadead commented on Nov 4, 2017
> Yes, we have disabled new signups via GitHub, you can expect to see this button gone soon too(when we release next version).
> If you are signing up for the first time, please do so via the email, and then link up GitHub through the settings on your profile.

Simply create a freecodecamp account using the same email you used to create your github account.
After that, log into freecodecamp using that email, then go to https://www.freecodecamp.org/settingsand you can link your github account, and your progress should still be there.
Good luck
