### ISSUE TITLE
Mobile view next challenge button

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#1466]
A camper relayed this to me:

There is some problem with the first challenge ending button on android with firefox browser. And in this moment I tried in chrome too, the issue is the same, the button is not active after the challenge is done. 

Xperia Z1 compact, android: 5.0.2, firefox: 39.0
Chrome: 43.0.2357.93

**Comment by Gmrpr7** [comment]
This is an issue whenever the screen size is small. It will also happen on a desktop if you resize the window to half screen or less.
