### ISSUE TITLE
[Beta] Suggested Description Changes—Work with Dynamic Data in D3 Challenge

### ISSUE THREAD

**Issue by honmanyau** [freeCodeCamp/freeCodeCamp#14668]
Challenge [work-with-dynamic-data-in-d3](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/work-with-dynamic-data-in-d3) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30</code>.

Part of the trigger for raising this issue is the incorrect use of "couple", instead of "couple of", in the D3 challenge in question (id: 587d7fa7367417b2b2512bc5).  Another instance can be found in the challenge **Use the d3.max and d3.min Functions to Find Minimum and Maximum Values in a Dataset** (id: 587d7fac367417b2b2512bdc).

If I'm not mistaken, the use of simple past when describing a fact, such as in the sentence "The last couple **of** challenges cover~~ed~~ the tools...", is also incorrect.

I think the description in the title challenge could use a rework—there are many ideas being explained but, in my opiniong, the current text is potentially confusing, particularly to non-native speakers.  For example, the sentence *"since the data from the dataset array is attached to each element, the callback function has access to it"* appears to be misleading because, if I'm not mistaken, each ```h2``` element only has access to an item in ```dataset``` that the element is mapped to.

I am more than happy to suggest a reworked description, but am not entirely sure how to go about it; not least because these changes can be subjective and I'm not entirely confident that I will be able to explain those concepts clearly with my lack of coding experience.

Many apologies in advance for any inconvenience caused—I have't had to report any issues or used GitHub beyond basic version control up until now.  :(

**Comment by raisedadead** [comment]
Hi @honmanyau Thanks for the suggestion.
/cc @freeCodeCamp/moderators anyone expert on D3 to guide?

**Comment by QuincyLarson** [comment]
@hkuz what are your thoughts on this usage change?

**Comment by HKuz** [comment]
@honmanyau - thanks for your suggestions! To avoid ambiguity, I think we can change the instances of "The last couple challenges covered" to "The last two challenges cover ...".

I wasn't sure where you were referencing for your other comment, but that sentence should be clarified as you suggest. Perhaps we could say "since one item from the dataset array is attached to each element..." or something similar. If you can create a re-write of the segment so it's clear for non-native English speakers in any other way, that would be ideal. You can post it as a comment here and we can comment or change it as needed. Thanks so much!

**Comment by honmanyau** [comment]
@HKuz—many apologies for the delayed response and appended is my attempted edit.  It is worth noting that I tried to avoid using passive voice as much as possible and included an example that I feel is important.  I understand that they may be stylistically different to the text currently in the D3 section, so please feel free to edit any of it, not least because something that is clear to me may not necessarily be clear to others.  :)

I hope that helps!

---

<p>The last couple of challenges cover the basics of displaying data dynamically with D3 using the <code>data()</code> and <code>enter</code> methods.  These methods take a dataset and, together with the the <code>append</code> method, create a new DOM element for each entry in the dataset.</p>

<p>In the previous challenge, a new <code>h2</code> element is created for each item in the <code>dataset</code> array, but they all contain the same text, "New Title", as we have not made use of the data that is bound to each of the <code>h2</code> element.</p>

<p>The D3 <code>text()</code> method can take a string or a callback function, instead of a string, as an argument:</p>

<p><code>selection.text((d) => d)</code></p>

<p>where the parameter <code>d</code> refers to a single entry in the dataset that a selection is bound to.</p>

<p>Using our current example as context, the first <code>h2</code> element is bound to 12, the second <code>h2</code> element is bound to 31, and the third <code>h2</code> element is bound to 22... etc.  Providing a callback function with <code>d</code> as a parameter as an argument to the <code>text()</code> method means that <code>d</code> will take a value of 12 for the first <code>h2</code> element, 31 for the second <code>h2</code> element, and 22 for the third <code>h2</code> element... etc.</p>

<hr>

<p>Change the <code>text()</code> method so that each <code>h2</code> element displays the corresponding value from the <code>dataset</code> array with a single space and "USD". For example, the first heading should be "12 USD".</p>

**Comment by HKuz** [comment]
Thanks so much for doing this @honmanyau - that text looks good! (I made a couple very minor formatting tweaks).

Contributors, this challenge text (located [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/04-data-visualization/data-visualization-with-d3.json#L171)) needs to be updated per the above comment. Check out the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) to get set up and feel free to ask questions in the [Contributor's chat room](https://gitter.im/freecodecamp/contributors). Thank you! 👍 :1st_place_medal: 💯

**Comment by honmanyau** [comment]
Absolutely no problem, @HKuz! :)

**Comment by dakshshah96** [comment]
Made the changed here: #15539

**Comment by akash987456** [comment]
try this,
.text((d) => d + " " + "USD")
