### ISSUE TITLE
Type error: arr.shift is not a function

### ISSUE THREAD

**Issue by jsrengg** [freeCodeCamp/freeCodeCamp#14678]
For the Stand in Line Challenge,

This is my code and for some reason I keep getting Type error:arr.shift is not a function. 

<img width="885" alt="screen shot 2017-05-01 at 8 08 18 pm" src="https://cloud.githubusercontent.com/assets/27872345/25603059/975095fe-2ead-11e7-9be2-5194fe329a33.png">

Could someone help me with this?

Thanks! I've already tried asking in the chatroom...

**Comment by JoolsMcFly** [comment]
Look at [Array.push](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push?v=control) documentation and what it returns.
Then consider your code:
`arr=arr.push(item);`

and you'll know why JS complains when doing `item=arr.shift()`

and then close the issue. ;)

**Comment by jsrengg** [comment]
Thanks!!

**Comment by knoxcard** [comment]
@JoolsMcFly - Thanks Kramer! :-)
