### ISSUE TITLE
Workaround solution. Too easy. Instead of using splice and slice it is easier to substitute with shift()

### ISSUE THREAD

**Issue by leetboy** [freeCodeCamp/freeCodeCamp#14673]
Challenge [Slasher Flick](https://www.freecodecamp.com/challenges/slasher-flick) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

*removed solution by mod*

**Comment by texas2010** [comment]
@leetboy 
Please do not post your solution on here. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
