### ISSUE TITLE
Accessing object properties : missing semicolon in example code

### ISSUE THREAD

**Issue by colegottdank** [freeCodeCamp/freeCodeCamp#14677]
#### Challenge Name

https://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables

#### Issue Description

Both of the examples don't have a `;` after the object initialization. 

#### Screenshot

![freecodecampbug](https://cloud.githubusercontent.com/assets/18726574/25599053/3cb6c0a6-2ea7-11e7-8ca1-f5563ee0aa0a.PNG)

**Comment by raisedadead** [comment]
@colegottdank Thanks for the issue, while the example is completely valid, and correct, lets add the semi colon.

Please note that semi colons are not mandatory and your code will be correct in JavaScript at least. But just for the sake of not confusing, new campers, we should add the semi colon as suggested.

Thanks for the issue.

**Comment by nicheProgramming** [comment]
I'll pick up this issue

**Comment by colegottdank** [comment]
Ah, didn't know that JavaScript can put in the ; for you. Very interesting!
Thanks.

**Comment by amartyaamp** [comment]
Already checked in the file and about to raise a pull request -  @nicheProgramming  - are you still on it ?

**Comment by nicheProgramming** [comment]
You go ahead! I have never worked with node anyway I couldn't find the right file. I will try to learn beforehand next time!

**Comment by amartyaamp** [comment]
@raisedadead - I have raised a pull request. Can members have a look and review?

https://github.com/freeCodeCamp/freeCodeCamp/pull/14684
