### ISSUE TITLE
Typo: "inputing" should be "inputting"

### ISSUE THREAD

**Issue by choiyoung7** [freeCodeCamp/freeCodeCamp#14686]
Challenge [Use HTML5 to Require a Field](https://www.freecodecamp.com/challenges/use-html5-to-require-a-field) has an issue

**Steps:**
Read the challenge text.

**Actual:** 
> It reads, "... Then try to submit the form without **inputing** any text..."

**Expected:** 
>"... Then try to submit the form without **inputting** any text..."

**Comment by raisedadead** [comment]
Nice catch, you have a good eye!

**Comment by Hoter11** [comment]
If you don't mind I'll try to fix it. Will be my first pull request ever :)

**Comment by choiyoung7** [comment]
Sure. Go right ahead!
