### ISSUE TITLE
Waypoint: Change the Font Size of an Element

### ISSUE THREAD

**Issue by EllieAdam** [FreeCodeCamp/freecodecamp#1468]
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue. Please describe how to reproduce it, and include links to screen shots if possible.
```
<style>
  .red-text {
    color: red;
   
  }
  p{
    font-size: 16px;
  }
</style>

<h2 class='red-text'>CatPhotoApp</h2>

<p class='red-text'>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p class='red-text'>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```
![screen shot 2015-08-02 at 9 39 25 pm](https://cloud.githubusercontent.com/assets/7389754/9030937/fb14b980-395e-11e5-9462-597f66611a01.png)

I added second p and added font-size 16px but #error is keep telling me I didn't add p.

**Comment by RobotLady** [comment]
Try pasting in this text for the second paragraph: "Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched."

**Comment by ahstro** [comment]
Like @RobotLady said. This is not a bug. Please close :)

**Comment by cdudley21** [comment]
it's definitely not a bug.....you have to change the second <p class to "style"

**Comment by cdudley21** [comment]
its definitely not a bug...... on the second "<p class", change it to "<p style" 

and you'll pass the challenge :100:

**Comment by mondayandfriday** [comment]
do not add a class attribute.
