### ISSUE TITLE
I believe that I have completed the challenge correctly but it states that It does not correctly capitalize the first letter and uncapitalized other letters.

### ISSUE THREAD

**Issue by prettygoodstudios** [freeCodeCamp/freeCodeCamp#14688]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Afunction%20titleCase(str)%20%7B%0A%20%20var%20words%20%3D%20str.split(%22%20%22)%3B%0A%20%20var%20sew%20%3D%20%22%22%3B%0A%20%20for(var%20i%3D0%3Bi%3Cwords.length%3Bi%2B%2B)%7B%0A%20%20%20%20var%20spl%20%3D%20words%5Bi%5D.split(%22%22)%3B%0A%20%20%20%20for(var%20j%3D0%3Bj%3Cspl.length%3Bj%2B%2B)%7B%0A%20%20%20%20%20%20if(j%3D%3D%3D0)%7B%0A%20%20%20%20%20%20%20%20var%20res%20%3D%20spl%5B0%5D.toUpperCase()%3B%0A%20%20%20%20%20%20%20%20if(res%20!%3D%20%22A%22)%7B%0A%20%20%20%20%20%20%20%20%20%20spl%5B0%5D%20%3D%20res%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7Delse%7B%0A%20%20%20%20%20%20%20%20var%20res2%20%3D%20spl%5Bj%5D.toLowerCase()%3B%0A%20%20%20%20%20%20%20%20spl%5Bj%5D%20%3D%20res2%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20sew%20%2B%3D%20%22%20%22%2Bspl.join(%22%22)%3B%0A%20%20%7D%0A%20%20return%20sew%3B%0A%7D%0A%0AtitleCase(%22HERE%20IS%20MY%20HANDLE%20HERE%20IS%20MY%20SPOUT%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function titleCase(str) {
  var words = str.split(" ");
  var sew = "";
  for(var i=0;i<words.length;i++){
    var spl = words[i].split("");
    for(var j=0;j<spl.length;j++){
      if(j===0){
        var res = spl[0].toUpperCase();
        if(res != "A"){
          spl[0] = res;
        }
      }else{
        var res2 = spl[j].toLowerCase();
        spl[j] = res2;
      }
    }
    sew += " "+spl.join("");
  }
  return sew;
}

titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");

```

**Comment by Manish-Giri** [comment]
@prettygoodstudios If you completed the challenge correctly, why do I get the same result as the input string - `HERE IS MY HANDLE HERE IS MY SPOUT`

Demo here - https://jsbin.com/rutagidopi/edit?js,console

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by dgierejkiewicz** [comment]
look at this: sew += " "+spl.join(""); // here it is :)
