### ISSUE TITLE
Replace the example of absolute positioning

### ISSUE THREAD

**Issue by ghost** [freeCodeCamp/freeCodeCamp#14681]
Challenge [lock-an-element-to-its-parent-with-absolute-positioning](https://beta.freecodecamp.com/en/challenges/applied-visual-design/lock-an-element-to-its-parent-with-absolute-positioning) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  #searchbar {
  position: absolute;
    top: 0;
    right: 0;    
  }
  section {
    position: relative;
  }
</style>
<body>
  <h1>Welcome!</h1>
  <section>
    <form id="searchbar">
      <label for="search">Search:</label>
      <input type="search" id="search" name="search">
      <input type="submit" name="submit" value="Go!">
    </form>
  </section>
</body>

```

I feel like while the above code works it simply fails to communicate the purpose of the exercise by delivering a visible change in the resulting page at the right side of the screen.

For comparison's sake, this is how it looks like when the code is executed in JSFiddle https://jsfiddle.net/39vmnwjc/. Given that the page display is narrow, my proposal is to change the required positioning entirely, so that the student will be able to see more clearly the results of the absolute positioning.

**Comment by HKuz** [comment]
Hi @Nathandim - thanks for pointing this out. Yeah, the narrow output screen unfortunately doesn't show the change at all. We could change the requirements to use `top: 150px` to make it more obvious. You titled the issue "Replace the example..." though, so if you had ideas to re-work this even more, let us know your thoughts!
