### ISSUE TITLE
Repeat a string: check marks appear without passing

### ISSUE THREAD

**Issue by marshallaf** [FreeCodeCamp/FreeCodeCamp#1469]
In the "[Repeat a string](http://www.freecodecamp.com/challenges/bonfire-repeat-a-string-repeat-a-string)" bonfire, green checkmarks appear next to each test, even though the first two fail, with the following code:

```
function repeat(str, num) {
  // repeat after me
  if (num < 0) {
    return '';
  } else {
    arr = [];
    for (var i = 0; i < num; i++) {
      arr.push(str);
    }
    return arr.join(' ');
  }
}
```
The success alert doesn't show up to give you the option of moving on to the next bonfire though, so I don't think it's actually passing the bonfire.

**Comment by ahstro** [comment]
Can't reproduce in [beta](http://beta.freecodecamp.com/challenges/bonfire-repeat-a-string-repeat-a-string). Can probably be closed.
