### ISSUE TITLE
My code returns the right answer but it does not pass the check.

### ISSUE THREAD

**Issue by PolarisTLX** [freeCodeCamp/freeCodeCamp#14698]
Challenge [Smallest Common Multiple](https://www.freecodecamp.com/challenges/smallest-common-multiple#?solution=function%20smallestCommons(arr)%20%7B%0A%20%20%0A%20%20var%20smallNum%3B%0A%20%20var%20bigNum%3B%20%20%20%20%0A%20%20%0A%09if%20(arr%5B1%5D%20%3E%20arr%5B0%5D)%7B%0A%20%20%09smallNum%20%3D%20arr%5B0%5D%3B%0A%20%20%20%20bigNum%20%3D%20arr%5B1%5D%3B%0A%09%7D%0A%20%20else%7B%0A%20%20%20%20bigNum%20%3D%20arr%5B0%5D%3B%0A%20%20%20%20smallNum%20%3D%20arr%5B1%5D%3B%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20var%20numArr%20%3D%20%5B%5D%3B%0A%20%20%0A%20%20for%20(i%3DsmallNum%3B%20i%3CbigNum%2B1%3B%20i%2B%2B)%7B%0A%20%20%20%20numArr.push(i)%3B%0A%20%20%7D%20%20%0A%20%20console.log(numArr)%3B%0A%20%20%0A%20%20var%20LCM%20%3D%20bigNum%2B1%3B%0A%20%20var%20anyFalse%20%3D%20false%3B%0A%20%0A%20%20while%20(anyFalse%20%3D%3D%3D%20false)%7B%0A%20%20%20%20anyFalse%20%3D%20true%3B%0A%20%20%09for%20(i%3D0%3B%20i%3CnumArr.length%3B%20i%2B%2B)%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%09if%20(LCM%20%25%20numArr%5Bi%5D%20!%3D%3D0)%7B%0A%20%20%20%20%09%09LCM%2B%2B%3B%0A%20%20%20%20%20%20%20%20anyFalse%20%3D%20false%3B%0A%20%20%20%20%20%20%09%2F%2Fconsole.log(LCM)%3B%0A%20%20%09%09%7D%0A%20%20%09%7D%0A%20%20%7D%20%20%0A%20%20console.log(LCM)%3B%0A%20%20return%20LCM%3B%20%20%20%0A%7D%0A%0AsmallestCommons(%5B23%2C18%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The last check in the challenge is:  "smallestCommons([23, 18]) should return 6056820."
And my code DOES return 6056820, yet it does not pass.

My code:
```javascript
function smallestCommons(arr) {
  
  var smallNum;
  var bigNum;    
  
	if (arr[1] > arr[0]){
  	smallNum = arr[0];
    bigNum = arr[1];
	}
  else{
    bigNum = arr[0];
    smallNum = arr[1];    
  }
  
  var numArr = [];
  
  for (i=smallNum; i<bigNum+1; i++){
    numArr.push(i);
  }  
  console.log(numArr);
  
  var LCM = bigNum+1;
  var anyFalse = false;
 
  while (anyFalse === false){
    anyFalse = true;
  	for (i=0; i<numArr.length; i++){
      
    	if (LCM % numArr[i] !==0){
    		LCM++;
        anyFalse = false;
      	//console.log(LCM);
  		}
  	}
  }  
  console.log(LCM);
  return LCM;   
}

smallestCommons([23,18]);

```

**Comment by teghmehta** [comment]
write //noprotect at the top

**Comment by valeriusturcanus** [comment]
+1
