### ISSUE TITLE
The page does not recognize the 100% zoom of my browser

### ISSUE THREAD

**Issue by alexsandrosantos35** [freeCodeCamp/freeCodeCamp#14695]
![capture](https://cloud.githubusercontent.com/assets/28292534/25657604/12c8f550-2fd5-11e7-8b5c-89c4cfc62f89.JPG)
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.21 Safari/537.36 MMS/1.0.2531.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
    
    p {
      font-size:16px;
      
    } 
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by nikefootbag** [comment]
Your p element selector is nested inside your .red-text class selector.

It should be:

```
<style>
  .red-text {
    color: red;
  }
  
  p {
    font-size: 16px;
  }
</style>
```

In future you should google for the answer before raising a github issue just to make sure it's definitely an issue.

**Comment by alexsandrosantos35** [comment]
I did not even look at my code once the page pointed to the zoom, thanks for the help

**Comment by raisedadead** [comment]
@nikefootbag thanks a lot for you help, we sincerely appriciate it. But please provide all assistance over the chat rooms and the forum.

We strongly discourage any coding assistance in the issue tracker, which is for reporting bugs only.
