### ISSUE TITLE
Instructions and list item values differ on this challenge

### ISSUE THREAD

**Issue by mergatroid** [freeCodeCamp/freeCodeCamp#14691]
Challenge [Understanding Uninitialized Variables](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables#?solution=%0A%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%20%3D%205%3B%0Avar%20b%20%3D%2010%3B%0Avar%20c%20%3D%20%22I%20am%20a%22%3B%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Initialize these three variables
var a = 5;
var b = 10;
var c = "I am a";

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";


```

**Comment by mergatroid** [comment]
![challenge-bug](https://cloud.githubusercontent.com/assets/6417786/25652433/7abd2010-2fe8-11e7-815b-2153ff210923.png)

**Comment by mergatroid** [comment]
The variable values defined in instructions do not match in the list under the Run Tests. It will only pass when you have the Instruction values.

**Comment by raisedadead** [comment]
This is intended. However, I think changing the tests to more understandable language should clear your confusion.

> `a` should be defined and have a value of `6`

> `a` should be defined and **should evaluate to** `6`

Potential contributors should make this small change to the test messages:
> **should evaluate to** replacing the *have a value of*

/cc @erictleung What do you think?

**Comment by erictleung** [comment]
@raisedadead agreed :+1: I've seen this issue come up a few times and I can see the confusion from reading it right now.

To be more precise on the changes needed, we need the first two challenge tests to be updated to be less confusing. So something similar to the following:

> `a` should be defined and evaluated to have the value of `6`
>
> `b` should be defined and evaluated to have the value of `15`

[These two lines of code](https://github.com/freeCodeCamp/freeCodeCamp/blob/0caef00dfe7b55b6bebaaa77caec83858d3d5b3a/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L259-L260) need to be updated.

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by TheBest101** [comment]
Going to try this as a first-timer in open source. Thank you
