### ISSUE TITLE
Surely the "Uncomment your h1, h2 and p elements." challenge has been met?

### ISSUE THREAD

**Issue by Jaff1** [freeCodeCamp/freeCodeCamp#14694]
Challenge [Uncomment HTML](https://www.freecodecamp.com/challenges/uncomment-html#?solution=%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%3C!--%0A--%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
<!--
-->
```

**Comment by nikefootbag** [comment]
In the testing requirement it states "Be sure to delete all trailing comment tags, i.e. -->."

**Comment by raisedadead** [comment]
@nikefootbag thanks a lot for you help, we sincerely appriciate it. But please provide all assistance over the chat rooms and the forum.

We strongly discourage any coding assistance in the issue tracker, which is for reporting bugs only.
