### ISSUE TITLE
Request: One-time donation option

### ISSUE THREAD

**Issue by ArielLeslie** [freeCodeCamp/freeCodeCamp#14696]
There has been [a request](https://forum.freecodecamp.com/t/i-just-wanted-to-donate-why-dont-you-have-an-option-to-donate-only-once/111763?u=arielleslie) for an option to make a one-time donation to Free Code Camp via https://www.freecodecamp.com/donate/ rather than a recurring payment.  If it's not too logistically difficult, I also think this is a good idea.

**Comment by raisedadead** [comment]
Issue moved to [freeCodeCamp/shop #2](https://github.com/freeCodeCamp/shop/issues/2) via [**ZenHub**](https://www.zenhub.com/)
