### ISSUE TITLE
Im getting the correct answers but the system does not acknowledge it. I have been asking in Help too  and so far no luck either

### ISSUE THREAD

**Issue by chameleon07** [freeCodeCamp/freeCodeCamp#14701]
Challenge [Counting Cards](https://www.freecodecamp.com/challenges/counting-cards#?solution=%0Avar%20count%20%3D%200%3B%0A%0Afunction%20cc(card)%20%7B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20%0A%20%20%0A%20%20switch%20(card)%7B%0A%20%20%20%20case%202%3A%0A%20%20%20%20case%203%3A%0A%20%20%20%20case%204%3A%0A%20%20%20%20case%205%3A%0A%20%20%20%20case%206%3A%0A%20%20%20%20%20%20count%20%2B%3D1%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%207%3A%0A%20%20%20%20case%208%3A%0A%20%20%20%20case%209%3A%0A%20%20%20%20%20%20break%3B%0A%20%20%20%20case%2010%3A%0A%20%20%20%20case%20'J'%3A%0A%20%20%20%20case%20'Q'%3A%0A%20%20%20%20case%20'K'%3A%0A%20%20%20%20case%20'A'%3A%0A%20%20%20%20%20%20count%20-%3D1%3B%0A%20%20%20%20%20%20break%3B%0A%20%20%7D%0A%20%20%0A%20%20if%20(count%20%3C%3D%200)%7B%0A%20%20%20%20key%20%3D%20%22%20Hold%22%3B%0A%20%20%7D%20else%20if%20(count%20%3E%200)%7B%0A%20%20%20%20key%20%3D%20%22%20Bet%22%3B%0A%20%20%7D%0A%0A%7D%0A%0A%2F%2F%20Add%2Fremove%20calls%20to%20test%20your%20function.%0A%2F%2F%20Note%3A%20Only%20the%20last%20will%20display%0Acc(2)%3B%20cc('J')%3B%20cc(9)%3B%20cc(2)%3B%20cc(7)%3B%0A%0Astring%20%3D%20count%20%2B%20key%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var count = 0;

function cc(card) {
  // Only change code below this line
  
  
  switch (card){
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      count +=1;
      break;
    case 7:
    case 8:
    case 9:
      break;
    case 10:
    case 'J':
    case 'Q':
    case 'K':
    case 'A':
      count -=1;
      break;
  }
  
  if (count <= 0){
    key = " Hold";
  } else if (count > 0){
    key = " Bet";
  }

}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc('J'); cc(9); cc(2); cc(7);

string = "\"" + count + key + "\"";


```

**Comment by chameleon07** [comment]
* I have even removed the extra double commas and it still does not work

**Comment by ogora** [comment]
if ( card <=6) count +=1;
  else if (card >6 && card < 10 ) count +=0;
  else if ( card === 10, 'J', 'K', 'A') count -=1;
if(count>0)return count +" Bet";
  else return count +" Hold";

**Comment by raisedadead** [comment]
Hi @chameleon07 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
