### ISSUE TITLE
Reverse a string - not accepting correct solution

### ISSUE THREAD

**Issue by tgardiner88** [freeCodeCamp/freeCodeCamp#14704]
Challenge [Reverse a String](https://www.freecodecamp.com/challenges/reverse-a-string#?solution=%0Afunction%20reverseString(str)%20%7B%0A%20%20var%20retstr%3D%22%22%3B%0A%20%20var%20l%3Dstr.length%3B%0A%20%20for%20(var%20i%3D0%3B%20i%3Cstr.length%3B%20i%2B%2B)%7B%0A%20%20%20%20retstr%2B%3D(str%5Bl-i-1%5D)%3B%0A%20%20%7D%0A%20%0A%20%20retstr%3D%22%5C%22%22%2Bretstr%2B%22%5C%22%22%3B%0A%20%20%0A%20%20%0A%20%20%0A%20%20return%20retstr%3B%0A%7D%0A%0AreverseString(%22Howdy%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
I can complete the assignment with unshift but wanted to create this function to reuse in the other algorithm challenges. My output seems correct but is not registering as being correct.

My code:
```javascript

function reverseString(str) {
  var retstr="";
  var l=str.length;
  for (var i=0; i<str.length; i++){
    retstr+=(str[l-i-1]);
  }
 
  retstr="\""+retstr+"\"";
  
  
  
  return retstr;
}

reverseString("Howdy");

```

**Comment by tgardiner88** [comment]
i meant split not unshift

**Comment by tpoikela** [comment]
I think your line 
`retstr="\""+retstr+"\"";`
is the problem. There is no need to add the double quotes around the reversed string.

**Comment by JoolsMcFly** [comment]
+1 @tpoikela 
Just remove that line and you're good to go, and close the issue as well! :)

Also, since you've stored `str.length` in `l` you can use it in the `for` loop:
```
function reverseString(str) {
  var retstr="";
  var l=str.length;
  for (var i=0; i<l; i++){
    retstr+= str[l-i-1]; // no need for brackets here
  }
  
  return retstr;
}
```

**Comment by Margaret2** [comment]
Yeah, that is not the correct solution @tgardiner88 
For `reverseString("Howdy");`, your function returns `""ydwoH""`, when it should return `"ydwoH"`

**Comment by kdheeraj1997** [comment]
function reverseString(str) {
  var retstr="";
  var l=str.length;
  for (var i=0; i<str.length; i++){
    retstr+=(str[l-i-1]);
  }
 return retstr;
}

reverseString("Howdy");



it works now :D

**Comment by dhcodes** [comment]
Closing as resolved.
