### ISSUE TITLE
Nesting For Loops

### ISSUE THREAD

**Issue by tdshandley** [freeCodeCamp/freeCodeCamp#14705]
Challenge [Nesting For Loops](https://www.freecodecamp.com/challenges/nesting-for-loops#?solution=%0Afunction%20multiplyAll(arr)%20%7B%0A%20%20var%20product%20%3D%201%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Afor(var%20i%3D0%3B%20i%3Carr.length%3B%20i%2B%2B)%7B%0A%20%20%20%20for(var%20j%3D0%3B%20j%3C%20arr%5Bi%5D.length%3B%20j%2B%2B)%7B%0A%20%20%20%20%20%20product%20*%3D%20arr%5Bi%5D%5Bj%5D%3B%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20product%3B%0A%7D%0A%20%20%7D%0A%0A%20%20%2F%2F%20Modify%20values%20below%20to%20test%20your%20code%0AmultiplyAll(%5B%5B1%2C2%5D%2C%5B3%2C4%5D%2C%5B5%2C6%2C7%5D%5D)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function multiplyAll(arr) {
  var product = 1;
  // Only change code below this line

for(var i=0; i<arr.length; i++){
    for(var j=0; j< arr[i].length; j++){
      product *= arr[i][j];
      
    }
  
  // Only change code above this line
  return product;
}
  }

  // Modify values below to test your code
multiplyAll([[1,2],[3,4],[5,6,7]]);


```
Will not accept answer. Even attempted to paste in others answers without success.

**Comment by Manish-Giri** [comment]
@tdshandley Your code is wrong. Your `return` statement should be **outside** both the for loops. If you have it inside the first loop, it just executes once. 

Also, please visit the [Help Room](https://gitter.im/FreeCodeCamp/HelpJavaScript) first for help with issues like these, in future.

**Comment by raisedadead** [comment]
Hi @tdshandley 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
