### ISSUE TITLE
The app on the right hand side does not appear. Neither does the tests run correctly. 

### ISSUE THREAD

**Issue by rizpixel** [freeCodeCamp/freeCodeCamp#14700]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment]
Hi @rizpixel 

Please provide some screenshots, and logs of your DevTools (you can google how to open it for your specific browser and OS)

Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.

Happy Coding!
