### ISSUE TITLE
Confirm field doesn't have any effect on the Password Reset screen

### ISSUE THREAD

**Issue by Atralbus** [freeCodeCamp/freeCodeCamp#14716]
#### Issue Description

My password is changed even if I don't fill up the confirm field on the "reset-password" page. I tried it with different passwords in two fields and it seems like confirm field doesn't have any effect on the process. I couldn't see any validation in the source code either.

**Comment by bonebizz21** [comment]
Thanks

**Comment by bonebizz21** [comment]
Needed that
