### ISSUE TITLE
[beta] Basic CSS: Adjust the Padding of an Element - does not display code in web form

### ISSUE THREAD

**Issue by Garlandjon95** [freeCodeCamp/freeCodeCamp#14719]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/basic-css/adjust-the-padding-of-an-element

#### Issue Description

Completed challenge before 45, then boxes do not appear in 45 such as the red-box.

#### Browser Information

Laptop, Windows 10, Google Chrome

* Browser Name, Version: Google Chrome
* Operating System: Windows
* Mobile, Desktop, or Tablet: 

#### Your Code

```js


<style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .yellow-box {
    background-color: yellow;
    padding: 10px;
  }
  
  .red-box {
    background-color: red;
    padding: 20px;
  }

  .green-box {
    background-color: green;
    padding: 10px;
  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/19752815/25713585/32e7b5f8-30c3-11e7-9f92-f000ef6fbc7a.png)

**Comment by raisedadead** [comment]
> Challenge45

Challenges do not have a no. These are your brownie scores. You get them for solving challenges and when someone thanks you in the chat.

**Comment by raisedadead** [comment]
Have you tried refresh - reset and submitting the solution?
