### ISSUE TITLE
Title case a sentence - Basic algorithmic scripting

### ISSUE THREAD

**Issue by jaspaulkhurana** [freeCodeCamp/freeCodeCamp#14717]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Afunction%20titleCase(str)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20var%20wordsArray%20%3D%20str.split(%27%20%27).map(function%20(val)%7B%20result%20%2B%3D%20%20%22%20%22%20%2B%20upperCaseFirstLetter(val.toLowerCase())%3B%7D)%3B%0A%20%20return%20result%3B%0A%7D%0A%0Afunction%20upperCaseFirstLetter(str)%7B%0A%20%20%20%20var%20wordArray%20%3D%20str.split(%27%27)%3B%0A%20%20%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%20%20for(var%20i%3D0%3Bi%3CwordArray.length%3Bi%2B%2B)%7B%0A%20%20%20%20%20%20if(i%3D%3D%3D0)%7B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20result%20%2B%3D%20wordArray%5Bi%5D.toUpperCase()%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20else%7B%0A%20%20%20%20%20%20%20%20result%20%2B%3D%20wordArray%5Bi%5D%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20return%20result%3B%0A%20%20%7D%0A%0A%0A%0AtitleCase(%22HERE%20IS%20MY%20HANDLE%20HERE%20IS%20MY%20SPOUT%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function titleCase(str) {
  var result = "";
  var wordsArray = str.split(' ').map(function (val){ result +=  " " + upperCaseFirstLetter(val.toLowerCase());});
  return result;
}

function upperCaseFirstLetter(str){
    var wordArray = str.split('');
    var result = "";
    for(var i=0;i<wordArray.length;i++){
      if(i===0){
        
        result += wordArray[i].toUpperCase();
      }
      else{
        result += wordArray[i];
      }
    }
   return result;
  }



titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");

```
I am not sure what is wrong with the code. The string produced is correctly Title cased.

**Comment by PaulNewman-M** [comment]
@jaspaulkhurana  Check with the Exact output ,be aware about the extra spaces which is intangible.

This will be useful:Checkout the link
https://jsbin.com/careyoputo/edit?js,console

**Comment by PaulNewman-M** [comment]
@jaspaulkhurana  Same Issue is raised by me.Hope this will be helpful.

https://github.com/freeCodeCamp/freeCodeCamp/issues/14709

Happy Coding!

**Comment by jaspaulkhurana** [comment]
Thanks Paul. Yes there was an extra space in the beginning of the sentence.
