### ISSUE TITLE
Chapter - Prioritize One Style Over Another

### ISSUE THREAD

**Issue by vrijender** [freeCodeCamp/freeCodeCamp#14711]
Challenge [Prioritize One Style Over Another](https://www.freecodecamp.com/challenges/prioritize-one-style-over-another#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-test%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Cbody%3E%0A%3Ch1%20class%20%3D%20%22pink-test%22%3EHello%20World!%3C%2Fh1%3E%0A%3C%2Fbody%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-test{
    color: pink;
  }
</style>
<body>
<h1 class = "pink-test">Hello World!</h1>
</body>
```

**Comment by vrijender** [comment]
Is this script correct?

**Comment by ooade** [comment]
@vrijender `.pink-text` is spelt wrongly.
Use the [help room](https://gitter.im/FreeCodeCamp/HelpFrontEnd) next time.

**Comment by vrijender** [comment]
@ooade Thanks!!!
