### ISSUE TITLE
Remove the font-size label before loading to the font-family task, it seems to be not working in presence of font-size label.

### ISSUE THREAD

**Issue by Upsehu** [freeCodeCamp/freeCodeCamp#14713]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by pburns1587** [comment]
👎 

Can't replicate:

Challenge Name: "Set the Font Family of an Element"

Issue Description: font-family conflicts with font-size

Browser Information

Browser Name, Version: Chrome, Version 59.0.3071.115
Operating System: Windows 10
Mobile, Desktop, or Tablet: Desktop

Your Code
` p {
    font-family: Monospace;
    font-size: 16px;
`

Works as expected for me.
