### ISSUE TITLE
Personal portfolio feature help!!

### ISSUE THREAD

**Issue by toasted121** [freeCodeCamp/freeCodeCamp#14728]
#### Challenge Name
Personal portfolio page

#### Issue Description
Hi all,

I had a go at the portfolio page recently and was trying to match the example page given. In particular, there was a feature where the buttons became highlighted as the scroll page reached a certain point. 

Seems like a more advanced feature so I actually left it at that, but I'd like to know if anyone succeeded or if you could have a look at my code. basically I just assigned different background colors to the buttons within a certain pixel range. 

I'm not sure if that's the right way to go about it, if you had any luck using another method, or if you know how to use scrollTop() : offset().top as a target etc. any advice would be great to add this feature to my page.

Thanks in advance. 

#### Your Code
  
  $(document).scroll(function(){           
    
  var target1 = 50;
  var target2 = 400;
  var target3 = 1600;
      
  var buttoncol = white;
          
    if( $("html, body").scrollTop: offset().top < target2  && $("html, body").scrollTop: offset().top >= target1){                $("#button1").css('background', silver);
                $("#button2").css('background', buttoncol);
                $("#button3").css('background', buttoncol);
            } 
else if ($("html, body").scrollTop: offset().top < target3 && $("html, body").scrollTop: offset().top >= target2) {
                $("#button2").css('background', silver);
                $("#button1").css('background', buttoncol);
                $("#button3").css('background', buttoncol);
            } 

else if ($("html, body").scrollTop: offset().top  >= target3){
                $("#button3").css('background-color', silver);
                $("#button2").css('background-color', buttoncol);
                $("#button1").css('background-color', buttoncol);
            }
        });

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
