### ISSUE TITLE
i did it right it doesnt say i completed it

### ISSUE THREAD

**Issue by MrPotat0** [freeCodeCamp/freeCodeCamp#14724]
Challenge [Find the Length of a String](https://www.freecodecamp.com/challenges/find-the-length-of-a-string#?solution=%0A%2F%2F%20Example%0Avar%20firstNameLength%20%3D%200%3B%0Avar%20firstName%20%3D%20%22Ada%22%3B%0A%0AfirstNameLength%20%3D%20firstName.length%3B%0A%0A%2F%2F%20Setup%0Avar%20lastNameLength%20%3D%208%3B%0Avar%20lastName%20%3D%20%22Lovelace%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%5C%0Avar%20lastNameLength%20%3D%208%3B%0Avar%20lastName%20%3D%20%22Lovelace%22%3B%0A%0AlastNameLength%20%3D%20lastName.length%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var firstNameLength = 0;
var firstName = "Ada";

firstNameLength = firstName.length;

// Setup
var lastNameLength = 8;
var lastName = "Lovelace";

// Only change code below this line.\
var lastNameLength = 8;
var lastName = "Lovelace";

lastNameLength = lastName.length;



```

**Comment by MrPotat0** [comment]
// Example
var firstNameLength = 0;
var firstName = "Ada";

firstNameLength = firstName.length;

// Setup
var lastNameLength = 8;
var lastName = "Lovelace";

// Only change code below this line.\
var lastNameLength = 8;
var lastName = "Lovelace";

lastNameLength = lastName.
this is my code

**Comment by MrPotat0** [comment]
nm

**Comment by erictleung** [comment]
Closing as resolved. If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!
