### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by MikBH** [FreeCodeCamp/freecodecamp#1473]
Challenge http://beta.freecodecamp.com/challenges/waypoint-ditch-custom-css-for-bootstrap has an issue. 
![screen shot 2015-08-03 at 09 06 28](https://cloud.githubusercontent.com/assets/13418244/9032445/fed552a4-39be-11e5-9d18-0ba66df4161c.png)

says: "You"

should be: "Your"

**Comment by djordjelacmanovic** [comment]
Fixed, generated a pull request

**Comment by BerkeleyTrue** [comment]
closed via #1485
