### ISSUE TITLE
issue after validation

### ISSUE THREAD

**Issue by MikBH** [FreeCodeCamp/freecodecamp#1474]
Challenge http://beta.freecodecamp.com/challenges/waypoint-add-id-attributes-to-bootstrap-elements has an issue. 

After validation of the exercise we have the following message:
![screen shot 2015-08-03 at 10 00 42](https://cloud.githubusercontent.com/assets/13418244/9033370/aab07eb2-39c6-11e5-9f79-ca62105bbf9e.png)

**Comment by benmcmahon100** [comment]
This could not be reproduced what browser/os combo are you using?

**Comment by MikBH** [comment]
I am on OSX 10.10.4 and browser: firefox 39.0

**Comment by benmcmahon100** [comment]
Hey We just fixed this now and it'll will be deployed to beta soon! The next challenge's route was broken

**Comment by MikBH** [comment]
Oki, I close the issue.
Thanks :)
