### ISSUE TITLE
"Drop it " not validating correctly

### ISSUE THREAD

**Issue by suli-g** [freeCodeCamp/freeCodeCamp#14747]
Challenge [Drop it](https://www.freecodecamp.com/challenges/drop-it#?solution=%0Afunction%20dropElements(arr%2C%20func)%20%7B%0A%20%20%2F%2F%20Drop%20them%20elements.%0A%20%20return%20arr.filter(function(a)%7B%0A%20%20%20%20return%20func(a)%3B%0A%20%20%7D)%3B%0A%7D%0A%0A%0AdropElements(%5B1%2C%201%2C1%2C1%2C1%5D%2C%20function(n)%20%7Breturn%20n%20%3E%202%3B%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function dropElements(arr, func) {
  // Drop them elements.
  return arr.filter(function(a){
    return func(a);
  });
}
```

The Response:

> `[Passed] dropElements([1, 2, 3, 4], function(n) {return n >= 3;}) should return [3, 4].`
> `[Failed] dropElements([0, 1, 0, 1], function(n) {return n === 1;}) should return [1, `**0**`, 1].`
**(there should not be a `0` at index 1)**

> `[Passed] dropElements([1, 2, 3], function(n) {return n > 0;}) should return [1, 2, 3].`
> `[Passed] dropElements([1, 2, 3, 4], function(n) {return n > 5;}) should return [].`
> `[Passed] dropElements([1, 2, 3, 7, 4], function(n) {return n > 3;}) should return [7, 4].`
> `[Failed] dropElements([1, 2, 3, 9, 2], function(n) {return n > 2;}) should return [3, 9, `**2**`].` 
**(there should not be a `1` at index 2)**

**Comment by paulo-raoni** [comment]
Same issue here mate. This is a "math" error. What should we do to pass through this challenge?

**Comment by suli-g** [comment]
It turned out that it actually was validating correctly --
instead of using `Array.filter`, I used a `while` loop and it worked (I don't think I understand `Array.filter` correctly yet.
```
function dropElements(arr, func) {
  // Drop them elements.
  while (!func(arr[0])){
      arr.splice(0,1);
  }  
  return arr;
}
```

**Comment by paulo-raoni** [comment]
Haha. I used some fancy code. But that is it. Problem solved. 
```
function dropElements(arr, func) {
  // Drop them elements.
  arr = arguments[0];
  var arrLength = arr.length;
  var temp;
  var receiver = [];
  var i = 0;
  
  //Loops until find a number to pass the test. If the current number doesn't pass the test we shift it out. If the current number passes the test we break the loop.  
  while(i < arrLength) {
    if(func(arr[0])) {
      break;
    }else{
      arr.shift();
    }
  i++;    
  }
  
  return arr;
}

console.log(dropElements([1, 2, 3, 9, 2], function(n) {return n > 2;}) );

```

**Comment by texas2010** [comment]
@paulo-raoni 
Please do not post your solution on here. This GitHub Issues are for reporting bugs on the website only.

Happy Coding!
