### ISSUE TITLE
camelcase issue

### ISSUE THREAD

**Issue by srikanthdasari66** [freeCodeCamp/freeCodeCamp#14745]
Challenge [Understanding Case Sensitivity in Variables](https://www.freecodecamp.com/challenges/understanding-case-sensitivity-in-variables#?solution=%0A%2F%2F%20Declarations%0Avar%20StUdLyCapVaR%3B%0Avar%20properCamelCase%3B%0Avar%20TitleCaseOver%3B%0A%0A%2F%2F%20Assignments%0Avar%20StudLyCapVaR%20%3D%2010%3B%0Avar%20properCamelCase%20%3D%20%22A%20String%22%3B%0Avar%20TitleCaseOver%20%3D%209000%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Declarations
var StUdLyCapVaR;
var properCamelCase;
var TitleCaseOver;

// Assignments
var StudLyCapVaR = 10;
var properCamelCase = "A String";
var TitleCaseOver = 9000;

```

**Comment by srikanthdasari66** [comment]
it is showing error like this:    studlyCapVar should use camelCase in both declaration and assignment sections.

**Comment by Margaret2** [comment]
Your code is incorrect. If you need help, ask in the [Javascript Help Room](https://gitter.im/freecodecamp/helpjavascript). Github Issues are only for reporting bugs.

**Comment by OFFLlNE** [comment]
Thank you for reporting the issue

As @Margaret2 as Margaret said, this is not an issue if your code is wrong.
Closing it as a request for help
