### ISSUE TITLE
Check the Length Property of a String Variable Bug.

### ISSUE THREAD

**Issue by Coder1988** [FreeCodeCamp/freecodecamp#1475]
Challenge http://beta.freecodecamp.com/challenges/check-the-length-property-of-a-string-variable has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

when you type lastNameLength.length there is an error below that writes:

Program Execution FailureNo user tests were run.

**Comment by benmcmahon100** [comment]
On this now!

**Comment by benmcmahon100** [comment]
This is actually because you tried to access the length of an undefined variable.
The challenge asks you to set lastNameLenght to be equal to the length of lastName so it should look like this
```javascript
    lastNameLength = lastName.length;
```
Trying to do what you did causes an error as you are trying to access the length of an undefined variable. I will create a default value for lastNameLength so that the tests will still run.

**Comment by Coder1988** [comment]
Thanks. I somewhat have the same problem with the next waypoint and I was about to post a new bug issue but I saw your reply.

**Comment by benmcmahon100** [comment]
Does the next challenge have a similar issue?
I appreciate the feed back as it allows me to harden the tests!

**Comment by Coder1988** [comment]
Yeah. I just typed **firstLetterOfLastName[0]** instead of **var firstLetterOfLastName = lastName[0];**

I just got used to Codecademy's editor where you don't have to type out **var firstLetterOfLastName = lastName[0];** and you can just type in **firstLetterOfLastName[0]** and get the correct answer.

**Comment by benmcmahon100** [comment]
Yeah firstLetterOfLastName represents the letter and not the whole string that's why you have to do it the other way as you are tying to get the first letter of last name via
```
lastName[0];
```
and assign it to firstLetterOfLastName in the way you have
```
firstLetterOfLastName = lastName[0];
```

**Comment by Coder1988** [comment]
Thanks for all your help and really, really fast feedback for my problem. Would have taken me a lot of time to figure out without you.

Thanks for all your great work here at FCC and I plan on helping out more by pointing out bugs that I encounter while doing the lessons.

P.S. is there a way I can thank you by giving you points or whatever?

**Comment by benmcmahon100** [comment]
Ha Ha I don't need any points! I appreciate the help with finding bugs even more!

**Comment by Coder1988** [comment]
Hoped that me pointing at the extra } at the end of line 14 in waypoint 5 in basic javascript helped you guys out.

**Comment by BerkeleyTrue** [comment]
@benmcmahon100 Has this issue been resolved?

**Comment by benmcmahon100** [comment]
Yes Sorry

**Comment by BerkeleyTrue** [comment]
@benmcmahon100 Woot!

**Comment by benmcmahon100** [comment]
woot indeed \#getting stuff done

**Comment by Goletian** [comment]
this thread was helpful just to help my brain troubleshooot without going to the chats! Thanks!
