### ISSUE TITLE
Incorrect visual

### ISSUE THREAD

**Issue by Abott1222** [freeCodeCamp/freeCodeCamp#14759]
Challenge [delete-html-elements](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/delete-html-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

The image does not correctly show what is currently there namely the h2 and p tags

**Comment by moyamanuel** [comment]
@Abott1222 Please try closing and reopening your browser.

**Comment by erictleung** [comment]
@Abott1222 can you be more specific? When is the visual incorrect? Do you have a screenshot of the issue you're experiencing? And did you run the tests or not?

**Comment by Abott1222** [comment]
Just a small bug probably. The Hello World doesn't display. Might be confusing for a beginner trying to figure out why it wasn't showing up. Trying to help the beta. :D

**Comment by raisedadead** [comment]
Hi @Abott1222 

Thanks a lot for the report and helping us out on the beta. Please report all issues you can find, we appreciate all the help we can get. 

I think what you are pointing out is being discussed already here #12923
Closing, let us know if that's not the case and we will reopen.

Happy hunting.
