### ISSUE TITLE
Target specific child w/ jQuery -- question regarding .nth-child() 

### ISSUE THREAD

**Issue by alaminos** [freeCodeCamp/freeCodeCamp#14751]
#### Challenge Name: 
Target a Specific Child of an Element Using jQuery

https://www.freecodecamp.com/challenges/target-a-specific-child-of-an-element-using-jquery

```
<script>
 $(document).ready(function() {
 $("#target1").css("color", "red");
 $("#target1").prop("disabled", true);
 $("#target4").remove();
 $("#target2").appendTo("#right-well");
 $("#target5").clone().appendTo("#left-well");
 $("#target1").parent().css("background-color", "red");
 $("#right-well").children().css("color", "orange");
 $(".target:nth-child(2)").addClass("animated bounce");
 $(".well:nth-child(2)").addClass("animated shake");
 

 });


<!-- Only change code above this line. -->

<div class="container-fluid">
 <h3 class="text-primary text-center">jQuery Playground</h3>
 <div class="row">
 <div class="col-xs-6">
 <h4>#left-well</h4>
 <div class="well" id="left-well">
 <button class="btn btn-default target" id="target1">#target1</button>
 <button class="btn btn-default target" id="target2">#target2</button>
 <button class="btn btn-default target" id="target3">#target3</button>
 </div>
 </div>
 <div class="col-xs-6">
 <h4>#right-well</h4>
 <div class="well" id="right-well">
 <button class="btn btn-default target" id="target4">#target4</button>
 <button class="btn btn-default target" id="target5">#target5</button>
 <button class="btn btn-default target" id="target6">#target6</button>
 </div>
 </div>
 </div>
</div>
```

#### Issue Description

After passing the challenge correctly, I wanted to tinker a little and try to target other elements.
I wanted to target the 2nd well and make it shake, I typed this line: 

```
$(".well:nth-child(2)").addClass("animated shake"); 
```

however it does not produce expected result. It actually shakes both wells. I thought maybe the reason is that each well element is embedded in their own div element. I tried this other line:

```
$(".well:nth-child(1)").addClass("animated shake"); 
```

result: no shake at all.

#### Browser Information
* Firefox
* Windows 8.1
* laptop

**Comment by Margaret2** [comment]
`nth-child()` targets elements *on the same level* as its selector. So `$(".well:nth-child(2)").addClass("animated shake");` does in fact work as it's supposed to.  Not sure about the second one. It would be better to ask this question in the Help Room or on the forum, since this is not really a bug with the actual challenge.

**Comment by stoltzld** [comment]
I had to use $(".well button:nth-child(2)").addClass("animated bounce"); to get it to behave correctly.  The nth-child led me to believe that it would select children of the .well divs.

**Comment by raisedadead** [comment]
@alaminos I have formatted the code that you had reported earlier for readability. Hope I have not messed it, please confirm.

Post that we can look into this.

**Comment by raisedadead** [comment]
Please revert back if this is an issue.
