### ISSUE TITLE
facing error with https API of local weather challenge

### ISSUE THREAD

**Issue by monala** [freeCodeCamp/freeCodeCamp#14758]
I have a problem [local weather challenge ](https://www.freecodecamp.com/challenges/show-the-local-weather) in description an API mentioned for https when I fetching to this API I face an error.

**No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.**

I can fix this problem in my local by enabling `Allow-Control-Allow-Origin: *` by a [chrome extension](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi)
but by enabling `Allow-Control-Allow-Origin: * ` Codepen won't open and will stay at loading. by disabling it my project output won't show properly.

**Comment by moyamanuel** [comment]
Can you please post the code you have written?

**Comment by monala** [comment]
[codepen](https://codepen.io/monala92/project/editor/DdxaeD/)
I put my code into Codepen. there is a script tag inside the index.html contains all the javascript code

**Comment by monala** [comment]
well, I add [this URL](https://cors-anywhere.herokuapp.com/) before the weather API URL and it works now. but I think you must introduce another API.
