### ISSUE TITLE
testEqual is not working propely

### ISSUE THREAD

**Issue by vineethkasula** [freeCodeCamp/freeCodeCamp#14765]
Challenge [Comparison with the Equality Operator](https://www.freecodecamp.com/challenges/comparison-with-the-equality-operator#?solution=%0A%2F%2F%20Setup%0Afunction%20testEqual(myval)%20%7B%0A%20%20if%20(myval%3D%3D10)%20%7B%20%2F%2F%20Change%20this%20line%0A%20%20%20%20return%20%22Not%20Equal%22%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20%22%20Equal%22%3B%0A%20%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtestEqual(10)%3B%0AtestEqual(12)%3B%0AtestEqual(%2212%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function testEqual(myval) {
  if (myval==10) { // Change this line
    return "Not Equal";
  }
  
  return " Equal";
 
}

// Change this value to test
testEqual(10);
testEqual(12);
testEqual("12");

```

**Comment by indefinite0212** [comment]
Looks like you copy the given example and replace the original value given. 
your code is incorrect you should ask for help first before posting a git hub issue
ask here https://gitter.im/FreeCodeCamp/HelpJavaScript

**Comment by raisedadead** [comment]
Hi @vineethkasula 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
