### ISSUE TITLE
bug in If condition

### ISSUE THREAD

**Issue by vineethkasula** [freeCodeCamp/freeCodeCamp#14764]
Challenge [Use Conditional Logic with If Statements](https://www.freecodecamp.com/challenges/use-conditional-logic-with-if-statements#?solution=%0A%2F%2F%20Example%0Afunction%20ourTrueOrFalse(isItTrue)%20%7B%0A%20%20if%20(isItTrue)%20%7B%20%0A%20%20%20%20return%20%22Yes%2C%20it's%20true%22%3B%0A%20%20%7D%0A%20%20return%20%22No%2C%20it's%20false%22%3B%0A%7D%0A%0A%2F%2F%20Setup%0Afunction%20trueOrFalse(wasThatTrue)%20%7B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%20%20%0A%20%20if(wasThatTrue)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20%22Yes%2Cthat%20was%20true%22%3B%0A%20%20%20%20%7D%0A%20%20%0A%20%20return%20%22No%2CThat%20was%20false!%22%3B%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AtrueOrFalse(true)%3B%0AtrueOrFalse(false)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
function ourTrueOrFalse(isItTrue) {
  if (isItTrue) { 
    return "Yes, it's true";
  }
  return "No, it's false";
}

// Setup
function trueOrFalse(wasThatTrue) {

  // Only change code below this line.
  
  if(wasThatTrue)
    {
      return "Yes,that was true";
    }
  
  return "No,That was false!";
  // Only change code above this line.

}

// Change this value to test
trueOrFalse(true);
trueOrFalse(false);

```

**Comment by indefinite0212** [comment]
Your code is incorrect make sure to copy the exact given return value
you should ask first before posting a git hub issue
ask here https://gitter.im/FreeCodeCamp/HelpJavaScript

**Comment by raisedadead** [comment]
Hi @vineethkasula 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
