### ISSUE TITLE
inadequate tests - function is correct, yet regex is off

### ISSUE THREAD

**Issue by misterrorypond** [FreeCodeCamp/freecodecamp#1476]
Challenge http://beta.freecodecamp.com/challenges/make-it-functional has an issue.

my function clearly is correct,, adds a and b to get 9, yet the regex is requiring parenthesis and no spaces, and is altogether far too limiting, resulting in the inability for me to pass the test even with correct code

![makeitfunctional](https://cloud.githubusercontent.com/assets/11319764/9042470/79a1e19a-39d4-11e5-92b3-0a8510d072b6.png)

**Comment by benmcmahon100** [comment]
On this now!

**Comment by benmcmahon100** [comment]
Just generalized the RegEx to Allow more variants of how to create that function

**Comment by misterrorypond** [comment]
Let me know when the fix is deployed - its still not working for me

**Comment by benmcmahon100** [comment]
That should be up now!

**Comment by misterrorypond** [comment]
thanks so much!
