### ISSUE TITLE
[beta] It creates an external link and take us to the bottom

### ISSUE THREAD

**Issue by anuraglahon16** [freeCodeCamp/freeCodeCamp#14771]
Challenge [link-to-internal-sections-of-a-page-with-anchor-elements](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/link-to-internal-sections-of-a-page-with-anchor-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<h2>CatPhotoApp</h2>
<main>
  
  <a href="#bottom" target="_blank">cat photos</a>
  
  <img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">
  
  <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff. Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  <p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff. Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
  <a name="bottom"></a>
</main>

```

**Comment by Rushyendher** [comment]
It's because you set target='_blank' in your "a" tag. Remove that it works fine.

**Comment by raisedadead** [comment]
The challenge instructions need additional text to remove the `target='_blank'`

**Comment by AndreiCalazans** [comment]
Possible additional text to remote the target='_blank' could be.... 

after the following text:

> **Change your external link to an internal link by changing the href attribute to "#bottom" and the anchor text from "cat photos" to "Jump to Bottom".**

Don't forget to remove the **target='_blank'** tag since this tag opens the linked document in a new window tab.

**Comment by toddtyler** [comment]
Thanks for the tag, I'm working on it!
