### ISSUE TITLE
Should change "property" to "name"?

### ISSUE THREAD

**Issue by janet-m** [freeCodeCamp/freeCodeCamp#14773]
This challenge uses the phrase "property and value pairs." Shouldn't that be "name and value pairs"? If I understand correctly, the term "property" refers to the entire name/value pair, not simply the name.

Challenge [Wherefore art thou](https://www.freecodecamp.com/challenges/wherefore-art-thou#?solution=%0Afunction%20whatIsInAName(collection%2C%20source)%20%7B%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20collection.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20for%20(var%20j%20%3D%200%3B%20j%20%3C%20source.length%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20if%20(collection%5Bi%5D.hasOwnProperty(source%5Bj%5D)%20%26%26%0A%20%20%20%20%20%20%20%20%20%20collection%5Bi%5D%20%3D%3D%3D%20source%5Bj%5D)%20%7B%0A%20%20%20%20%20%20%20%20arr.push(collection%5Bi%5D)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20arr%3B%0A%7D%0A%0A%2F%2F%20function%20whatIsInAName(collection%2C%20source)%20%7B%0A%2F%2F%20%20%20var%20arr%20%3D%20%5B%5D%3B%0A%2F%2F%20%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20collection.length%3B%20i%2B%2B)%20%7B%0A%2F%2F%20%20%20%20%20if%20(collection%5Bi%5D.keys().includes(source.keys())%20%26%26%20collection%5Bi%5D.values().includes(source.values()))%20%7B%0A%2F%2F%20%20%20%20%20%20%20arr.push(collection%5Bi%5D)%3B%0A%2F%2F%20%20%20%20%20%7D%0A%2F%2F%20%20%20%7D%0A%2F%2F%20%20%20return%20arr%3B%0A%2F%2F%20%7D%0A%0A%0AwhatIsInAName(%0A%5B%7Bfirst%3A%20%22Romeo%22%2C%20last%3A%20%22Montague%22%7D%2C%20%7Bfirst%3A%20%22Mercutio%22%2C%20last%3A%20null%7D%2C%20%0A%7Bfirst%3A%20%22Tybalt%22%2C%20last%3A%20%22Capulet%22%7D%5D%2C%20%0A%7Blast%3A%20%22Capulet%22%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by ooade** [comment]
I agree with you, it should be name and value pairs. But don't you think key/value pairs seem cooler :sweat_smile:

**Comment by Ntropish** [comment]
[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects) seems to agree as well and uses both "name" and "key". But it looks like "name" is more standard in the article.

**Comment by raisedadead** [comment]
I am in favor of the change.
/cc @freeCodeCamp/moderators

**Comment by dhcodes** [comment]
Starting with [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/3f0109ac28e3a2260768282728d758e25d0bb0e2/seed/challenges/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting.json#L255) replace all instances of `property` with `name`.

**Comment by helenyau0** [comment]
Hi, I'm new to contributing and would like to take this issue if it hasn't already been taken. :)

**Comment by raisedadead** [comment]
@helenyau0 please go ahead and make a pull request.

**Comment by helenyau0** [comment]
@raisedadead would you like the replacing of "property" to "name" to only happen in the intermediate-algorithm-scripting.json file or would you like to rename every instance of "property and value pairs" found in freeCodeCamp? lol I'm asking because that was a really easy task and I just finished :D
