### ISSUE TITLE
Course Addition - Debugger

### ISSUE THREAD

**Issue by PizzaPokerGuy** [freeCodeCamp/freeCodeCamp#14770]
For the debugging course "debugger" should be covered to help in the debugging learning curve. Even if it is an embedded video section if this can not be accomplished in FCC's IDE.

Challenge [catch-unclosed-parentheses-brackets-braces-and-quotes](http://beta.freecodecamp.com/en/challenges/debugging/catch-unclosed-parentheses-brackets-braces-and-quotes) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


let myArray = [1, 2, 3];
let arraySum = myArray.reduce((previous, current =>  previous + current));
console.log(`Sum of array values is: ${arraySum}`);

```

**Comment by raisedadead** [comment]
Hi @PizzaPokerGuy ! 

Thanks a lot for the suggestion. Can you elaborate a little bit more on what the expectation a here, to help us better understand the need?

/cc @freeCodeCamp/moderators

**Comment by PizzaPokerGuy** [comment]
This section is about debugging, but no where in here does it discuss "debugger" which is crucial to pause your code and debug. My suggestion is to include it in this section.
