### ISSUE TITLE
 Learn how Script Tags and Document Ready Work

### ISSUE THREAD

**Issue by yonatonrose** [freeCodeCamp/freeCodeCamp#14778]
#### Challenge Name

https://www.freecodecamp.com/challenges/learn-how-script-tags-and-document-ready-work
#### Issue Description

I type in the correct answer, and I know it's correct because I've even moved on to see the answer, and when I click run tests it won't let me move on.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: OSX El Capitan
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js

<script> $(document).ready(function)() {

      });
</script>


```
#### Screenshot

![screen shot 2017-05-08 at 3 46 01 pm](https://cloud.githubusercontent.com/assets/28495018/25822028/4e0d18e2-3405-11e7-8626-e7a2a03b1f3d.png)

**Comment by yonatonrose** [comment]
I understand that the code is unfinished but in the challenge all it tells me to do is what I did

**Comment by Margaret2** [comment]
You need to remove the extra `)` after the word `function`. Next time please ask in the [Help Room](https://gitter.im/FreeCodeCamp/Help?at=5910cc0483cb5db0730f3536) rather than posting an issue on Github.

**Comment by yonatonrose** [comment]
Sorry, thanks for the help

**Comment by JoolsMcFly** [comment]
You can close this issue then. :)

Thanks!

**Comment by Nsix6** [comment]
i did exactly same, but it still wont proceed to a new challenge

**Comment by JoolsMcFly** [comment]
@Nsix6 can you ask your question in the [Help Room](https://gitter.im/FreeCodeCamp/Help?at=5910cc0483cb5db0730f3536) pls?
Thanks.
