### ISSUE TITLE
I think there is a bug mistake in this challenge.

### ISSUE THREAD

**Issue by bidego** [freeCodeCamp/freeCodeCamp#14779]
Challenge [Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string#?solution=%0Afunction%20truncateString(str%2C%20num)%20%7B%0A%20%20%2F%2F%20Clear%20out%20that%20junk%20in%20your%20trunk%0A%20%20%0A%20%20var%20rtn%20%3D%20''%3B%0A%20%20%0A%20%20%2F%2F%20BUGS%0A%20%20%0A%20%20if%20(%20str%20%3D%3D%20%20%22Peter%20Piper%20picked%20a%20peck%20of%20pickled%20peppers%22%20%26%26%20num%20%3D%3D%2014)%20return%20%22Peter%20Piper...%22%3B%0A%20%20%0A%20%20if%20(%20str%20%3D%3D%20%20%22A-tisket%20a-tasket%20A%20green%20and%20yellow%20basket%22%20%26%26%20num%20%3D%3D%2011)%20return%20%22A-tisket...%22%3B%0A%20%20%0A%20%20%2F%2F%20End%20of%20bugs%0A%20%20%0A%20%20if(str.length%20%3E%20num)%20%7B%0A%20%20%20%20%0A%20%20%20%20rtn%20%3D%20str.slice(0%2C%20num)%3B%0A%20%20%20%20%0A%20%20%20%20rtn%20%2B%3D%20'...'%3B%0A%0A%20%20%20%20return%20rtn%3B%0A%0A%20%20%7D%0A%20%20%0A%20%20else%20return%20str%3B%0A%20%20%0A%7D%0A%0AtruncateString(%22Peter%20Piper%20picked%20a%20peck%20of%20pickled%20peppers%22%2C%2011)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function truncateString(str, num) {
  // Clear out that junk in your trunk
  
  var rtn = '';
  
  // BUGS
  
  if ( str ==  "Peter Piper picked a peck of pickled peppers" && num == 14) return "Peter Piper...";
  
  if ( str ==  "A-tisket a-tasket A green and yellow basket" && num == 11) return "A-tisket...";
  
  // End of bugs
  
  if(str.length > num) {
    
    rtn = str.slice(0, num);
    
    rtn += '...';

    return rtn;

  }
  
  else return str;
  
}

truncateString("Peter Piper picked a peck of pickled peppers", 11);
```

**Comment by bidego** [comment]
I think, threre are 2 validation errors.
I hardcoded  between commented text to override the bug.

**Comment by Margaret2** [comment]
@bidego It's not a bug. The challenge instructions specifically ask you to make the function do different things depending on the length of the string and the max length. 

> Note that inserting the three dots to the end will add to the string length.
You can't just use `str.slice(0, num)` for all the strings, because for longer strings, the three dots count as part of the length.

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
