### ISSUE TITLE
Auto complete challenges with other campers' solutions

### ISSUE THREAD

**Issue by fidenz-chim** [freeCodeCamp/freeCodeCamp#14775]
While I logged into FCC and if I view another person's solution for a challenge, and then if I run other person's solution, that get added to my challenges map as a completed challenge.

#### Issue Description
Log on to FCC, View some other users profile and select a solution for a challenge in another tab of the same browser as you are logged in (Session get shared between tabs within the browser). Then run the other person's solution for the challenge and that challenge get updated in my account.

#### Browser Information

* Brave, 0.15.2 , tested on Chrome as well
* Operating System: MacOS 10.12.1
* Mobile, Desktop, or Tablet: Desktop (MacBookPro),

**Comment by raisedadead** [comment]
@fidenz-chim this is an expected behavior of freeCodeCamp's editor. When you simply visit the solution of another person's profile it's NOT saved to yours.

BUT if you submit the challenge with the solution in the editor, it is saved, to your profile.

This is by design and not a bug.
