### ISSUE TITLE
instructions unclear

### ISSUE THREAD

**Issue by misterrorypond** [FreeCodeCamp/FreeCodeCamp#1477]
The final test is seeking "friends" as a property, not "enemies", yet the instructions do not ask for those specific object properties - as a matter of fact I assumed to use the same properties as cat - all are correct save friends vs enemies

Challenge http://beta.freecodecamp.com/challenges/i-object has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![iobject](https://cloud.githubusercontent.com/assets/11319764/9042660/cc55cfa4-39d5-11e5-985d-05cf643e1971.png)

**Comment by benschenker** [comment]
Closing as stale
