### ISSUE TITLE
[beta] Left over text in Iterate with JavaScript from previous challenge

### ISSUE THREAD

**Issue by RebeccaMorris** [freeCodeCamp/freeCodeCamp#14777]
Challenge [iterate-with-javascript-while-loops](https://beta.freecodecamp.com/en/challenges/basic-javascript/iterate-with-javascript-while-loops) has an issue.

It looks like there is some old text leftover from when the for loop section came before the while loop section. Now that while loops are the first time loops are mentioned, this text is confusing and out of place (highlighted in blue).
<img width="455" alt="screen shot 2017-05-08 at 3 06 29 pm" src="https://cloud.githubusercontent.com/assets/10439428/25820630/f5b16b62-33ff-11e7-9d7f-533ed019874d.png">

**Comment by JoolsMcFly** [comment]
How about:

The first type of loop we will learn is called a <code>while</code> loop because it runs "while" a specified condition is true and stops once that condition is no longer true..

I'll make a PR if you or mods agree.

**Comment by TeejayParker** [comment]
Go ahead and drop a PR

**Comment by raisedadead** [comment]
@JoolsMcFly thanks!

**Comment by frutsy007** [comment]
Ikhf j

**Comment by spieg** [comment]
Where can I see if this issue is cq should be resolved in the challenge I see in beta?

**Comment by raisedadead** [comment]
Beta, deployments are done one every couple of days, maybe you should hold on for a few days and if you still see the issue, then please report back.

Thanks.
