### ISSUE TITLE
dot notation better in instructions? even editor suggessts to do so (beta site)

### ISSUE THREAD

**Issue by misterrorypond** [FreeCodeCamp/FreeCodeCamp#1478]
even the editor suggests we do this in dot notation - i see this as a potential issue
I automatically went for dot notation then saw the instructions and got confused
test passes with dot notation though, just proper syntax?
![dotnotation](https://cloud.githubusercontent.com/assets/11319764/9042842/0156b262-39d7-11e5-8660-03dfe8716671.png)
![manipulatingobjects](https://cloud.githubusercontent.com/assets/11319764/9042817/d7bb54f8-39d6-11e5-806d-1c5071e999d0.png)
Challenge http://beta.freecodecamp.com/challenges/manipulating-objects has an issue.

**Comment by benmcmahon100** [comment]
Yes you can't add properties using dot notation but normally you would use dot notation everywhere else pretty much

**Comment by BerkeleyTrue** [comment]
Both are proper syntax, The editor is linting for style. I suggest adding to the instructions 
```
or like this `myObject.newProperty = "myValue";`
```

**Comment by benmcmahon100** [comment]
This was fixed a while ago i think :p

**Comment by misterrorypond** [comment]
I posted it a while ago...

**Comment by benmcmahon100** [comment]
Ha Ha yeah just saw that i was still assigned to it and remembered fixing it :p
