### ISSUE TITLE
I changed the color but it is not working

### ISSUE THREAD

**Issue by TheBika** [freeCodeCamp/freeCodeCamp#14782]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20h2%7Bcolor%3A%20blue%3B%7D%0A%3C%2Fstyle%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2{color: blue;}
</style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Ntropish** [comment]
I think there might be a problem with your style tag code in this problem. Notice that in the example they are styling an "h2" tag. But in the challenge you are styling a "p" tag.

**Comment by Ntropish** [comment]
I think there might be a problem with your html for this issue TheBika. The original code had an h2 element that is missing from your code. Maybe you misread the instructions and deleted the entire element instead of just the style attribute? They intended for you to just delete the part that says `style="color: red"`

**Comment by texas2010** [comment]
@TheBika 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
