### ISSUE TITLE
Record Collection

### ISSUE THREAD

**Issue by woaiios** [freeCodeCamp/freeCodeCamp#14787]
#### Challenge Name

https://www.freecodecamp.com/challenges/record-collection

#### Issue Description

All test cases should be passed！

#### Browser Information

* Browser Name, Version: Version 58.0.3029.96 (64-bit)
* Operating System:  Mac OS Sierra 10.12.4 (16E195)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  
  var obj = collection[id];
  if(prop === 'tracks') {
    if(obj[prop]===undefined) {
       obj[prop] = [];
    }
    if(value !== '') {
      obj[prop].push(value);
    }

  } else {
    if(value === '') {
      delete obj[prop];
    } else {
      obj[prop] = value;
    } 
  }

  return collection;
}

// Alter values below to test your code
updateRecords(2548, "tracks", "");

```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/4178793/25836766/18e78f14-34bc-11e7-8407-008396218017.png)
![image](https://cloud.githubusercontent.com/assets/4178793/25836776/2a0e9c6a-34bc-11e7-95a8-1fffcd3a3508.png)

**Comment by trufflesprouts** [comment]
The problem is that you forgot to fully implement the last rule

> If value is empty (""), delete the given prop property from the album

Your code only checks `value === ''` when the prop does not equal 'tracks'.
To fix this move the empty value check before checking whether prop equals 'tracks.
```js
if(value === '') {
    delete obj[prop];
} else if(prop === 'tracks') {
    if(obj[prop]===undefined) {
        obj[prop] = [];
    }
    if(value !== '') {
        obj[prop].push(value);
    }
} else {
    obj[prop] = value; 
}
```

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
