### ISSUE TITLE
"Your h2 element should be blue." why? =[

### ISSUE THREAD

**Issue by Randytran0411** [freeCodeCamp/freeCodeCamp#14784]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements#?solution=%3Cstyle%3E%0A%20%20%20h2%20%7Bcolor%3A%20blue%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
   h2 {color: blue;}
</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Marmiz** [comment]
Thanks for reporting this issue @Randytran0411 .

I fear that you have misinterpreted the instructions:

> Delete your h2 element's **style attribute** 

means that if this was your original code:
```html
<h2 style="color: red">CatPhotoApp</h2>
```
Get rid of the `style=".."` portion and/or change it according to the lesson's requirements.


Next time you have difficulties please don't hesitate to ask for assistance in one of the [official chat](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390)

-----------
To help you clear the concept; with your code:
```html
<style>
   h2 {color: blue;}
</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```
You're asking the browser to make the `h2` `blue` .... but there's no `h2` in your page to be colored.
The `style` only set an element's appearances properties, but you still need to have them declared in your body section.

**Comment by texas2010** [comment]
@Randytran0411 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by SuperAdamee** [comment]
I am having precisely the same problem.  I followed your instructions to the letter (I already had before even coming here) and the error still reads, "Your h2 element should be blue."

When I click on "help," I am sent to gitter where I attempt to sign in with github.  When I click on the "sign in with github tab, nothing happens.

**Comment by Margaret2** [comment]
@SuperAdamee You can also find help on the [forum](https://forum.freecodecamp.com).

**Comment by lebergamota** [comment]
I have the same problem

**Comment by Trime2x1** [comment]
Remember you have to edit the h2 first...
<h2 style="color: red">CatPhotoApp</h2>
This edited line will remain in your code.

The next step is to add the style block at the top of your code.
the style block will point to your h2

**Comment by tripol** [comment]
> I am having precisely the same problem. I followed your instructions to the letter (I already had before even coming here) and the error still reads, "Your h2 element should be blue."
> 
> When I click on "help," I am sent to gitter where I attempt to sign in with github. When I click on the "sign in with github tab, nothing happens.

Did you close the `<style>` tag?

**Comment by Trime2x1** [comment]
Yes...
<style> your code here </style>

**Comment by lihuelworks** [comment]
Same problem. Looked at it couple of minutes then skipped it. Seems like the issue exists since 2016, according to this post in _[freecodecamp's forum](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-use-css-selectors-to-style-elements/18349
)_
![2020-03-07_20-37](https://user-images.githubusercontent.com/49965980/76154042-6bf7c080-60b4-11ea-8466-8b89dfa90fa8.png)

**Comment by charithalkml** [comment]
I have mentioned the written code below but still no progress. 
Please help what should I do ?
`<style>
  h2 { color: blue;}
</style>

<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>`

**Comment by charithalkml** [comment]
I have mentioned the written code below but still no progress.
Please help what should I do ?

<style>
  h2 { color: blue;}
</style>

<h2>CatPhotoApp</h2>
 <p>Click here to view more <a href="#">cat photos</a>.</p>

**Comment by lihuelworks** [comment]
Had an issue with this, solved it by disabling any userstyle extensions (Stylus, Stylish, or any "dark mode" extensions). Turns out your userstyle affects how freecode evaluates your excercise. Hope it helps!

**Comment by Tepa6auT** [comment]
> Had an issue with this, solved it by disabling any userstyle extensions (Stylus, Stylish, or any "dark mode" extensions). Turns out your userstyle affects how freecode evaluates your excercise. Hope it helps!

Thank you very much, the first result in google wasn't helpful. But your advise solved the problem immediately

**Comment by mgb2504** [comment]
> Had an issue with this, solved it by disabling any userstyle extensions (Stylus, Stylish, or any "dark mode" extensions). Turns out your userstyle affects how freecode evaluates your excercise. Hope it helps!

How do you disable understyle extensions? Google just tells me how to disable plugins.

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for general coding questions. GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
