### ISSUE TITLE
Bug in this question.. Answer is correct but it doesn't register it as correct.

### ISSUE THREAD

**Issue by jlim039** [freeCodeCamp/freeCodeCamp#14794]
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#?solution=sum%20%3D%201%3B%0Afunction%20factorialize(num)%20%7B%0A%20%20for%20(i%20%3D%20num%3B%20i%3E0%3B%20i--)%7B%0A%20%20%20%20sum%20%3D%20sum*i%3B%0A%20%20%0A%20%20%7D%0A%20%20return%20sum%3B%0A%7D%0A%0Afactorialize(10)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
sum = 1;
function factorialize(num) {
  for (i = num; i>0; i--){
    sum = sum*i;
  
  }
  return sum;
}

factorialize(10);

```

**Comment by Margaret2** [comment]
Your solution is incorrect. You can't use a global variable (`sum`) in your solution because it won't work if you run the function more than once. The function has to be reusable so that it will work for all the tests. 
If you need help fixing it, please ask in the [JS Help Room](https://gitter.im/freecodecamp/helpjavascript).

**Comment by nandub** [comment]
This should do it:
```
function factorialize(num) {
  sum = 1;
  for (i = num; i>0; i--){
    sum = sum*i;
  
  }
  return sum;
}
```

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
