### ISSUE TITLE
Output in Javascript, not reflecting correct

### ISSUE THREAD

**Issue by pawanbhatia399** [freeCodeCamp/freeCodeCamp#14792]
#### Issue Description

https://www.freecodecamp.com/challenges/multiply-two-decimals-with-javascript#?solution=%0Avar%20multiplication%20%3D%202.0%20*%202.5%3B%0A%0A%0A

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by indefinite0212** [comment]
your code is incorrect. before posting a git hub issue you should ask in the [javascript helproom](https://gitter.im/FreeCodeCamp/HelpJavaScript)
you should not change the variable name, and make sure that you put the correct value 
@pawanbhatia399

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
