### ISSUE TITLE
Confirm Ending Is Not Clear for One Test

### ISSUE THREAD

**Issue by ogora** [freeCodeCamp/freeCodeCamp#14798]
Challenge [Confirm the Ending])
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.

My code passes all tests for this challenge except  the string and target in bold below. According to my understanding the code  should pass. So I am not asking for help, but I want an explanation why my code passess all tests except the string below. If not, it seems like there may be a bug in the test.
**My code:**
```javascript

function confirmEnding(str, target) {
    var last = str.substring(-1);
  var last2 = target.substring(-1);
  if (last == last2) return true;
  else if (last !== last2) return false;
}

**confirmEnding("Walking on water and developing software from a specification are easy if both are frozen", "specification") )****

 



```

**Comment by erictleung** [comment]
When I run your code, it doesn't pass multiple tests. 

![image](https://cloud.githubusercontent.com/assets/2754821/25909485/264ae81c-3562-11e7-9973-7f5b641183d4.png)

If you get stuck or have questions with a challenge in the future, please first ask questions to the [Help Room](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by ogora** [comment]
Thats interesting cause when I ran it I was only missing the first . Anyway I have chnaged it now. Yo can close this issue
