### ISSUE TITLE
correct while loop not passing! , serious instruction issues for vs while (beta site) 

### ISSUE THREAD

**Issue by misterrorypond** [FreeCodeCamp/FreeCodeCamp#1479]
Challenge http://beta.freecodecamp.com/challenges/looping-with-while has an issue. 
this is a while loop exercise.
firstly, the instructions say "first we will be taking a look at the for loop" then show a while loop.
then asks you to create a for loop after the while loop directions.
i made a while loop, and my while loop is not passing for some reason! can't read the test well due to formatting issues, so not sure exactly why

![loopingwithwhile](https://cloud.githubusercontent.com/assets/11319764/9043011/1495883e-39d8-11e5-9b3e-f07ab1dfaa3d.png)

**Comment by benmcmahon100** [comment]
Sorry the beta warning is ruining the site I'l see if i can get this sorted I'll fix the instructions now!

**Comment by misterrorypond** [comment]
Thank you so much for your swift responses!

**Comment by benmcmahon100** [comment]
No problem! I'm in bug fix mode!

**Comment by BerkeleyTrue** [comment]
beta warning has been removed

**Comment by eaglecookie** [comment]
Thanks, @BerkeleyTrue ! The while loop is passing now, but the instructions still have incomplete sentences and little explanation.

**Comment by benschenker** [comment]
Closing as stale
