### ISSUE TITLE
output mistake in Truncate a string challenge

### ISSUE THREAD

**Issue by maximilientoumi** [freeCodeCamp/freeCodeCamp#14800]
Challenge [Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string#?solution=%0Afunction%20truncateString(str%2C%20num)%20%7B%0A%20%20%2F%2F%20Clear%20out%20that%20junk%20in%20your%20trunk%0A%20%20if(str.length%3Enum)%20%7B%0A%20%20%20%20%0A%20%20%20%20if%20(num%3C%3D3)%20%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20return%20str.slice(0%2C%20num)%20%2B%22...%22%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20return%20str.slice(0%2C%20num-3)%20%2B%22...%22%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20str%3B%0A%20%20%7D%0A%20%20%0A%20%0A%7D%0A%0AtruncateString(%22A-tisket%20a-tasket%20A%20green%20and%20yellow%20basket%22%2C%2011)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function truncateString(str, num) {
  // Clear out that junk in your trunk
  if(str.length>num) {
    
    if (num<=3) {
      
      return str.slice(0, num) +"...";
    } else {
      
      return str.slice(0, num-3) +"...";
    }
    
  } else {
    return str;
  }
  
 
}

truncateString("A-tisket a-tasket A green and yellow basket", 11);

```
OUTPUT
this is a screenshot
![truncatechal](https://cloud.githubusercontent.com/assets/22794420/25878016/3c3ea176-3545-11e7-954f-770589b8147f.png)

**Comment by Margaret2** [comment]
It's not a mistake. Here are the instructions: 
> Truncate a string (first argument) **if it is longer than the given maximum string length** (second argument). 

In the 4th test, the max length is two longer than the length of the string, so there is no need to shorten it.

**Comment by raisedadead** [comment]
Hi @maximilientoumi 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
