### ISSUE TITLE
 " Invert Regular Expression Matches with JavaScript" challenge

### ISSUE THREAD

**Issue by 20learncode16** [freeCodeCamp/freeCodeCamp#14803]
Challenge [Invert Regular Expression Matches with JavaScript](https://www.freecodecamp.com/challenges/invert-regular-expression-matches-with-javascript#?solution=%0A%2F%2F%20Setup%0Avar%20testString%20%3D%20%22How%20many%20non-space%20characters%20are%20there%20in%20this%20sentence%3F%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Avar%20expression%20%3D%20%2F%5CS%2B%2Fg%3B%20%20%2F%2F%20Change%20this%20line%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line%0A%0A%2F%2F%20This%20code%20counts%20the%20matches%20of%20expression%20in%20testString%0Avar%20nonSpaceCount%20%3D%20testString.match(expression).length%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var testString = "How many non-space characters are there in this sentence?";

// Only change code below this line.

var expression = /\S+/g;  // Change this line

// Only change code above this line

// This code counts the matches of expression in testString
var nonSpaceCount = testString.match(expression).length;

```
 This is the code but it's not accepted and I don't understand why :
// Setup
var testString = "How many non-space characters are there in this sentence?";

// Only change code below this line.

var expression = /\S+/g; // Change this line

// Only change code above this line

// This code counts the matches of expression in testString
var nonSpaceCount = testString.match(expression).length; 

![screen shot](https://cloud.githubusercontent.com/assets/20506860/25896386/43a248c8-35c7-11e7-8c53-6fa18c2987b1.jpg)

**Comment by smithmallick149** [comment]
same here it doesn't accept the code

**Comment by smithmallick149** [comment]
var expression = /\S+/g; // Change this line--error
var expression = /\S/g; // Change this line--got the code submitted
