### ISSUE TITLE
Golf Code

### ISSUE THREAD

**Issue by 20learncode16** [freeCodeCamp/freeCodeCamp#14804]
Challenge [Golf Code](https://www.freecodecamp.com/challenges/golf-code#?solution=%0Afunction%20golfScore(par%2C%20strokes)%20%7B%0A%20%20if%20(strokes%3D%3D1)%20%7B%0A%20%20%20%20return%20%22Hole-in-one!%22%3B%0A%20%20%7D%20else%20if%20(par-strokes%3E%3D2)%20%7B%0A%20%20%20%20return%20%22Eagle%22%3B%0A%20%20%7D%20else%20if%20(par-strokes%3D%3D1)%20%7B%0A%20%20%20%20return%20%22Birdie%22%3B%0A%20%20%7D%20else%20if%20(strokes%3D%3Dpar)%20%7B%0A%20%20%20%20return%20%22Par%22%3B%0A%20%20%7D%20else%20if%20(strokes-par%3D%3D1)%20%7B%0A%20%20%20%20return%20%22Bogey%22%3B%0A%20%20%7D%20else%20if%20(strokes-par%3D%3D2)%20%7B%0A%20%20%20%20return%20%22Double%20Bogey%22%3B%0A%20%20%7D%20%0A%20%20%0A%20else%20%7B%0A%20%20%20%20%20return%20%22Go%20Home%22%3B%20%0A%20%7D%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AgolfScore(4%2C%207)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function golfScore(par, strokes) {
  if (strokes==1) {
    return "Hole-in-one!";
  } else if (par-strokes>=2) {
    return "Eagle";
  } else if (par-strokes==1) {
    return "Birdie";
  } else if (strokes==par) {
    return "Par";
  } else if (strokes-par==1) {
    return "Bogey";
  } else if (strokes-par==2) {
    return "Double Bogey";
  } 
  
 else {
     return "Go Home"; 
 }
}

// Change these values to test
golfScore(4, 7);

```
This is the code but it's not accepted and I don't understand why :
![screen sho1t](https://cloud.githubusercontent.com/assets/20506860/25896543/f3833b1c-35c7-11e7-9a00-382550dca1e8.jpg)
![screen sho1t](https://cloud.githubusercontent.com/assets/20506860/25896568/097aef78-35c8-11e7-8765-4214637b2636.jpg)

function golfScore(par, strokes) {
  if (strokes==1) {
    return "Hole-in-one!";
  } else if (par-strokes>=2) {
    return "Eagle";
  } else if (par-strokes==1) {
    return "Birdie";
  } else if (strokes==par) {
    return "Par";
  } else if (strokes-par==1) {
    return "Bogey";
  } else if (strokes-par==2) {
    return "Double Bogey";
  } 
  
 else {
     return "Go Home"; 
 }
}

// Change these values to test
golfScore(4, 7);

**Comment by gulpasa** [comment]
Instead of 
```
else {
return "Go Home";
}
```
You should write
```
else {
return "Go Home**!**";
}
```
The "!" character causes the problem...

**Comment by 20learncode16** [comment]
Hi Gülpaşa,
Thank you so much for your answer.
Regards,
Antonia
