### ISSUE TITLE
valid h4 element not accepted (beta site)

### ISSUE THREAD

**Issue by misterrorypond** [FreeCodeCamp/FreeCodeCamp#1480]
my h4 elements do not seem to pass the first test even though it works, and my h4 elements pass the other two tests! I see no issue save in the first test!
![labelbootstrapwells](https://cloud.githubusercontent.com/assets/11319764/9044671/ab1ef1ae-39e3-11e5-8f04-0074389bbe0d.png)
Challenge http://beta.freecodecamp.com/challenges/waypoint-label-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by QuincyLarson** [comment]
Thanks for reporting this. We've fixed it.
