### ISSUE TITLE
not passing tests !1, maybe it dosen't like regex solution?

### ISSUE THREAD

**Issue by zackn9ne** [freeCodeCamp/freeCodeCamp#14817]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=var%20tilerTwo%20%3D%20(phrase)%20%3D%3E%20%7B%0A%20%20%20%20let%20holder%20%3D%20%5B%5D%0A%0A%20%20%20%20phrase%20%3D%20phrase.split('%20')%0A%20%20%20%20for%20(%20i%20%3D%200%3B%20i%20%3C%20phrase.length%3B%20i%2B%2B%20)%7B%0A%09fixed%20%3D%20phrase%5Bi%5D.toLowerCase().replace(%2F(%5E%7C%5Cs)%5Ba-z%5D%2Fg%2C%20function(getEm)%20%7B%20return%20getEm.toUpperCase()%3B%20%7D%20)%0A%09%0A%09console.log(fixed)%0A%09holder.push(fixed)%0A%20%20%20%20%7D%0A%09console.log(typeof(holder))%0A%20%20%20%20return%20holder.join('%20')%0A%7D%0AtilerTwo(%22HERE%20IS%20MY%20HANDLE%20HERE%20IS%20MY%20SPOUT%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var tilerTwo = (phrase) => {
    let holder = []

    phrase = phrase.split(' ')
    for ( i = 0; i < phrase.length; i++ ){
	fixed = phrase[i].toLowerCase().replace(/(^|\s)[a-z]/g, function(getEm) { return getEm.toUpperCase(); } )
	
	console.log(fixed)
	holder.push(fixed)
    }
	console.log(typeof(holder))
    return holder.join(' ')
}
tilerTwo("HERE IS MY HANDLE HERE IS MY SPOUT");
```

**Comment by Margaret2** [comment]
The tests are calling the function `titleCase()`, not `tilerTwo()`

**Comment by zackn9ne** [comment]
@Margaret2 ugh function names ok TY
