### ISSUE TITLE
Local Scope in Functions - there seems to be no way for my code to work

### ISSUE THREAD

**Issue by nnennandukwe** [freeCodeCamp/freeCodeCamp#14816]
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=function%20myLocalScope()%20%7B%0A%20%20'use%20strict'%3B%20%2F%2F%20you%20shouldn't%20need%20to%20edit%20this%20line%0A%20%20%2F%2F%20var%20myVar%3B%0A%20%20console.log(myVar)%3B%0A%7D%0AmyLocalScope()%3B%0A%0A%2F%2F%20Run%20and%20check%20the%20console%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myLocalScope%0Aconsole.log(myVar)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function myLocalScope() {
  'use strict'; // you shouldn't need to edit this line
  // var myVar;
  console.log(myVar);
}
myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope
console.log(myVar);
```
I've taken out one of the console.log(); and it still didn't work. other people have had problems with this, too.

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by mboesiger90** [comment]
I am having the same issue, I cant get past this lesson. How do I move forward without completing it?
