### ISSUE TITLE
Applied Visual Design: Create Movement Using CSS Animation

### ISSUE THREAD

**Issue by tobi10** [freeCodeCamp/freeCodeCamp#14814]
Hello, I have been trying to figure this out, but i'm quite sure there's a bug here. I have tried a hard refresh and running it on a different browser and it still doesn't work. Please Help

Challenge [create-movement-using-css-animation](https://beta.freecodecamp.com/en/challenges/applied-visual-design/create-movement-using-css-animation) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  div {
    height: 40px;
    width: 70%;
    background: black;
    margin: 50px auto;
    border-radius: 5px;
    position: relative;
  }

#rect {
  animation-name: rainbow;
  animation-duration: 4s;
}

@keyframes rainbow {
  0% {
    background-color: blue;
    top: 0px;
    
  }
  50% {
    background-color: green;
    top: 50px;
    
  }
  100% {
    background-color: yellow;
    top: 0px;
    
  }
  
@keyframes rainbow {
  0% {
    left: 0px;
  }
  
  50% {
    left: 25px; 
  }
  
  100% {
    left: -25px;
  }
  
}
  
</style>

<div id="rect"></div>

```

**Comment by Margaret2** [comment]
Hi, you have a mistake in your code. The `left` px values need to go in the same @keyframes rule as the `top` and `background-color` values.

**Comment by tobi10** [comment]
Wow....how did I not think of that. Thanks :).

**Comment by Lakshmiprasannaap** [comment]
Hello,can anyone help me here!!!!!!
<style>
  div {
    height: 40px;
    width: 70%;
    background: black;
    margin: 50px auto;
    border-radius: 5px;
    position: relative;
    left: 0px;
  }

#rect {
  animation-name: rainbow;
  animation-duration: 4s;
}

@keyframes rainbow {
  0% {
    background-color: blue;
    top: 0px;
    left: 0px;
  }
    
  
  50% {
    background-color: green;
    top: 25px;
    left: 25px;
    
  }
  100% {
    background-color: yellow;
    top: -25px;
    left: -25px;
    
  }
}
}
</style>

<div id="rect"></div>

**Comment by Lakshmiprasannaap** [comment]
It's not working for me??????
<style>
  div {
    height: 40px;
    width: 70%;
    background: black;
    margin: 50px auto;
    border-radius: 5px;
    position: relative;
    left: 0px;
    
  }

#rect {
  animation-name: rainbow;
  animation-duration: 4s;
}

@keyframes rainbow {
  0% {
    background-color: blue;
    left: 0px;
    top: 0px;

  }
  50% {
    background-color: green;
    left: 25px;
    top: 50px;
    
  }
  100% {
    background-color: yellow;
    left: -25px;
    top: 0px;
  
  }
}
}
</style>
<div id="rect"></div>

**Comment by Designird** [comment]
I think I got my code right but im still not getting a pass. 
here's my code...
<style>
  div {
    height: 40px;
    width: 70%;
    background: black;
    margin: 50px auto;
    border-radius: 5px;
    position: relative;
  }

#rect {
  animation-name: rainbow;
  animation-duration: 4s;
}

@keyframes rainbow {
  0% {
    background-color: blue;
    top: 0px;
    left: 0px;
    
  }
  50% {
    background-color: green;
    top: 50px;
    left: 25px;
    
  }
  100% {
    background-color: yellow;
    top: 25px;
    left: -25px;
    
  }
}
</style>

<div id="rect"></div>

any help with this would be appreciated.

**Comment by ziaongit** [comment]
<style>
  div {
    height: 40px;
    width: 70%;
    background: black;
    margin: 50px auto;
    border-radius: 5px;
    position: relative;
  }

#rect {
  animation-name: rainbow;
  animation-duration: 4s;
}

@keyframes rainbow {
  0% {
    background-color: blue;
    top: 0px;
    left:0px;
    
  }
  50% {
    background-color: green;
    top: 50px;
    left:25px;
    
  }
  100% {
    background-color: yellow;
    top: 0px;
    left:-25px;
  }
}
}
</style>

<div id="rect"></div>
