### ISSUE TITLE
[beta] [project] Applied Responsive Web Design Projects: Build a Personal Portfolio Webpage

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#14810]
I opened the example project by Freecodecamp in codepen and 1 of the tests are not passing... is it a bug or is it due to the codepen's layout interfering with the project layout?

The task that is not passing is 

#Portfolio tests
#Layout
2. The height of the welcome section should be equal to the height of the viewport.

**Comment by tommygebru** [comment]
There may also be a bug with 
Applied Responsive Web Design Projects:  Build a Technical Documentation Page

#Portfolio tests
#Layout
1. On regular sized devices (laptops, desktops), the element with id="navbar" should be shown on the left side of the screen and should always be visible to the user.

**Comment by no-stack-dub-sack** [comment]
@tommygebru please note that in the issue template there is a note that asks campers to open these issues on that project's repo: https://github.com/freeCodeCamp/testable-projects-fcc.

Also, the Personal Portfolio project is passing all 11 tests on the browsers I just tried it in. Please reopen this issue in the correct repository with a bit more information on browser, device, etc.

**Comment by tommygebru** [comment]
Thanks peter!!
