### ISSUE TITLE
Firefox "Content Security Policy" Error in Beta site

### ISSUE THREAD

**Issue by utomic** [freeCodeCamp/freeCodeCamp#14822]
Beta site
Console error on all challenges (which require test to pass) that I've checked so far, preventing completion of challenges.

"Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead."

#### Browser Information

* Browser Name, Version: Firefox 53.0.2
* Operating System: Mac OS
* Mobile, Desktop, or Tablet: Desktop

**Comment by ooade** [comment]
CSP not showing here on Chrome.

**Comment by dhcodes** [comment]
I see the console error and it does prevent the mobile preview on the HTML challenges from auto-loading, but it shows up when you click "Run tests"

**Comment by raisedadead** [comment]
@dhcodes thanks.
