### ISSUE TITLE
these manually match the given tests. I'm confused

### ISSUE THREAD

**Issue by zackn9ne** [freeCodeCamp/freeCodeCamp#14826]
Challenge [Return Largest Numbers in Arrays](https://www.freecodecamp.com/challenges/return-largest-numbers-in-arrays#?solution=%0Aconst%20largestOfFour%20%3D%20(arr)%20%3D%3E%20%7B%0A%20%20%2F%2F%20You%20can%20do%20this!%0A%0A%20%20%20%20const%20holder%20%3D%20%5B%5D%0A%20%20%20%20let%20i%0A%20%20%20%20const%20payload%20%3D%20%5B%5D%0A%20%20%20%20%0A%20%20%20%20for%20(%20i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B%20)%20%7B%0A%09%0A%09console.log(Math.max(...arr%5Bi%5D))%0A%09payload.push(Math.max(...arr%5Bi%5D))%0A%0A%20%20%20%20%7D%0A%0A%20%20%20%20return%20payload%0A%0A%7D%0A%0A%2F%2F%20largestOfFour(%5B%20%5B4%2C%205%2C%201%2C%203%5D%2C%20%5B13%2C%2027%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A%0A%2F%2F%20largestOfFour(%5B%5B13%2C%2027%2C%2018%2C%2026%5D%2C%20%5B4%2C%205%2C%201%2C%203%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%0AlargestOfFour(%5B%5B4%2C%209%2C%201%2C%203%5D%2C%20%5B13%2C%2035%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2097%2C%2039%5D%2C%20%5B1000000%2C%201001%2C%20857%2C%201%5D%5D)%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.96 Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

const largestOfFour = (arr) => {
  // You can do this!

    const holder = []
    let i
    const payload = []
    
    for ( i = 0; i < arr.length; i++ ) {
	
	console.log(Math.max(...arr[i]))
	payload.push(Math.max(...arr[i]))

    }

    return payload

}

// largestOfFour([ [4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

// largestOfFour([[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]])
largestOfFour([[4, 9, 1, 3], [13, 35, 18, 26], [32, 35, 97, 39], [1000000, 1001, 857, 1]])

```

**Comment by Margaret2** [comment]
This solution works for me in Vivaldi. Maybe try refreshing or try a different browser...

**Comment by zackn9ne** [comment]
@Margaret2 went back to fiddle with code, and upon reaching page the code seemed to be refreshed and tests passed and I submitted. :7  TY
