### ISSUE TITLE
Challenge 3 Skipped While Moving Through Challenges

### ISSUE THREAD

**Issue by reliable-justin** [FreeCodeCamp/FreeCodeCamp#1482]
## Issue:
While going through FCC's "HTML5 and CSS" tutorial, the "Go to my next challenge (ctrl + enter)" button resulted in the skipping of challenge three "Waypoint: Inform with the Paragraph Element." 

## Reproduce:
(1) Complete challenge two
(2) Go onto the next challenge by pressing control + enter
(3) Observe the skipping of challenge three

## Note:
- I am using Chrome version 44.0.2403.125 (64-bit)
- **You guys working on FreeCodeCamp are awesome**

**Comment by benschenker** [comment]
Closing as stale
