### ISSUE TITLE
It passes the test without writing the code.

### ISSUE THREAD

**Issue by anuraglahon16** [freeCodeCamp/freeCodeCamp#14836]
Challenge [find-characters-with-lazy-matching](http://beta.freecodecamp.com/en/challenges/regular-expressions/find-characters-with-lazy-matching) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


let text = "<h1>Winter is coming</h1>";
let myRegex = /<h.*?>/; // Change this line
let result = text.match(myRegex);

```

**Comment by raisedadead** [comment]
This is what I have in the editor on a clean reload / reset of the page:

```js
let text = "<h1>Winter is coming</h1>";
let myRegex = /<.*>/; // Change this line
let result = text.match(myRegex);
```

Which is different from what you have above, try clearing your cache if the reset doesn't work.
