### ISSUE TITLE
missing ; before statement

### ISSUE THREAD

**Issue by eaglecookie** [FreeCodeCamp/freecodecamp#1483]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery has an issue.

Upon opening the challenge, there is a problem next to the RED X that says:  "missing ; just before statement" but nothing looks incorrect. When I enter the code to solve the problem, the correct animation occurs; however, the RED X still says the semicolon is missing and won't let me continue to the next lesson.

I also want to let you know that this is my first day on FCC, and I think the lessons on your live site are fantastic! But I switched to the beta version as soon as I started jQuery, because the Code Academy lessons felt foreign and confusing. FCC does a MUCH better job (even with bugs). So, thank you! I can't wait to keep learning!!!

**Comment by BerkeleyTrue** [comment]
@eaglecookie Thanks for kind words! We hope to get it all sorted out and pushed to everyone as soon as possible. @eaglecookie This is indeed an issue. The most likely culprit being the test suite.

This issue has already been reported here #1450 So we will close this issue in favor of that one. Happy Coding!
