### ISSUE TITLE
keep trying different browers and have zoom on 100% and it wont let me continue

### ISSUE THREAD

**Issue by Disposablerhero** [freeCodeCamp/freeCodeCamp#14831]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20%3CP%3E%20h1%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  <P> h1 {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by saintaj** [comment]
This style seemed to work for me:

<style>
  .red-text {
    color: red;
    font-size: 16px}
  p {
    font-size: 16px;
  }
</style>

**Comment by Margaret2** [comment]
@saintaj Github issues are not for coding help; there's a dedicated help room and a forum for that. You also should not be giving out answers to challenges, even in the help rooms / forum. 

@Disposablerhero Next time, please go to the [Help Room](https://gitter.im/FreeCodeCamp/Help) or the [forum](https://forum.freecodecamp.com) to ask for help before posting it as a bug.

**Comment by saintaj** [comment]
@Margaret2 Right. Good call. Next time I'll say something like:

@Disposablerhero Double check your syntax. If you need help please go to the Help Room or the Forum (as Sunset Margarita has mentioned) to help resolve your issue.

Cheers!

**Comment by texas2010** [comment]
@Disposablerhero 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by ToofreshCoder12** [comment]
I can only clear the 4th and 5th of this task:

1. You need 2 p elements with Kitty Ipsum text.
2. Make sure each of your p elements has a closing tag.
3. Your p element should contain the first few words of the provided additional kitty ipsum text.
4.The first p element should have the class red-text.
5. Do not add a class attribute to the second p element.
6. Between the style tags, give the p elements font-size of 16px. Browser and Text zoom should be at 100%

**Comment by ToofreshCoder12** [comment]
and my code is:


<style>
  .red-text {color: red;}
  p {  font-size: 16px;};
  p1 {  font-size: 16px;}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p1>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p1>

**Comment by ToofreshCoder12** [comment]
<style>
  .red-text {color: red;}
  p {  font-size: 16px;};
  p1 {  font-size: 16px;}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p1>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p1>

**Comment by ToofreshCoder12** [comment]
can anyone help pls

**Comment by texas2010** [comment]
@ToofreshCoder12 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

These GitHub Issues are for reporting bugs on the freeCodeCamp website only.
Happy Coding.
