### ISSUE TITLE
Error in description of max heap challenge

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/freeCodeCamp#14843]
Challenge [insert-an-element-into-a-max-heap](http://beta.freecodecamp.com/en/challenges/coding-interview-data-structure-questions/insert-an-element-into-a-max-heap) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 9000.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Here is some text from the description text of this challenge: 
> For instance, consider this array representation of a binary max heap:
> [ 6, 22, 30, 37, 63, 48, 42, 76 ]
> The root node is the first element, 6.

I'm almost postitve that that is a representation of a binary **min** heap, not a binary _max_ heap. Since this challenge is about binary max heaps, I think the array should be changed to:
[ 76, 63, 48, 42, 37, 6, 42, 22 ]

Am I OK to make the update myself? (Assuming I can figure out where to update at. I'm new to this. )

**Comment by bonham000** [comment]
@beaucarnes yes you're right about that. Go ahead and update the challenge description if you want, you can find it in the JSON challenge seed files.
