### ISSUE TITLE
Typeof object with value fails the test.

### ISSUE THREAD

**Issue by rajibmp** [freeCodeCamp/freeCodeCamp#14846]
Challenge [Using typeof](https://www.freecodecamp.com/challenges/using-typeof) 

```javascript
var a = "Hello",
    b = 3,
    c = [],
    d = {"here":"there"};

console.log(typeof "Hello"); // string
console.log(typeof 2); // number
console.log(typeof []); // object
console.log(typeof {}); // object


console.log(typeof a); // string
console.log(typeof b); // number
console.log(typeof c); // object
console.log(typeof d); // object

console.log(typeof {"here":"error"}); // object

```

If `typeof` empty object is provided then the test passes but `typeof` *object* with value fails the test, although chrome dev console shows it as object.

**Comment by raisedadead** [comment]
Hi @rajibmp I could not reproduce the issue with the code that you have provided above, can you check if the code is correctly mentioned in the report above?

Also, some screenshots of the page and the Chrome DevTools Console should be helpful.

Thanks.

**Comment by rajibmp** [comment]
@raisedadead I am closing this as even I cannot reproduce it again. Generally object with any value was showing error and only empty object would pass the test when I reported this. Maybe it is already fixed or somehow object with value passes the test now.
