### ISSUE TITLE
It returns the output 1 through 5 but doesnot pass the test

### ISSUE THREAD

**Issue by anuraglahon16** [freeCodeCamp/freeCodeCamp#14850]
Challenge [catch-off-by-one-errors-when-using-indexing](http://beta.freecodecamp.com/en/challenges/debugging/catch-off-by-one-errors-when-using-indexing) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


function countToFive() {
  let firstFive = "12345";
  let len = firstFive.length;
  // Fix the line below
  for (let i = 0; i <= len-1; i++) {
  // Do not alter code below this line
    console.log(firstFive[i]);
  }
}

countToFive();

```

**Comment by rajibmp** [comment]
As the condition check says

> Your code should set the terminal condition of the loop so it stops at the last index.  

The last index should be the length itself.
`for (let i = 0; i < len; i++)`  
should solve the issue

**Comment by raisedadead** [comment]
@rajibmp is correct, please check your solution once again.
