### ISSUE TITLE
code formatting in "Sass: Use @if and @else to Add Logic To Your Styles"

### ISSUE THREAD

**Issue by jonnyxox** [freeCodeCamp/freeCodeCamp#14856]
#### Sass: Use @if and @else to Add Logic To Your Styles
http://beta.freecodecamp.com/en/challenges/sass/use-if-and-else-to-add-logic-to-your-styles

#### Formatting of code
![image](https://cloud.githubusercontent.com/assets/24957042/26025237/14956e32-37db-11e7-8d79-d5c02bbf40c8.png)
The code doesn't give success if there is a space between 'border' and the colon afterwards
@if $val == light {border: 1px solid black;} = good
@if $val == light {border : 1px solid black;} = no good

#### Browser Information
Chrome

* Browser Name, Version: chrome
* Operating System: windows 8.1
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/24957042/26025264/8c2441c6-37db-11e7-8eb2-9845306a9400.png)

**Comment by charlesBak** [comment]
@raisedadead is it a bug, i could replicate the error, if it is i could fix it.

**Comment by charlesBak** [comment]
there you go @raisedadead :)
