### ISSUE TITLE
I think my answer is correct 

### ISSUE THREAD

**Issue by anuraglahon16** [freeCodeCamp/freeCodeCamp#14854]
Challenge [copy-array-items-using-slice](http://beta.freecodecamp.com/en/challenges/basic-data-structures/copy-array-items-using-slice) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


function forecast(arr) {
  // change code below this line
  arr.slice(2,4);
  return arr;
}

// do not change code below this line
console.log(forecast(['cold', 'rainy', 'warm', 'sunny', 'cool', 'thunderstorms']));

```

**Comment by ooade** [comment]
The whole point of the challenge is to show you that the `slice` method do not mutate arrays. So by just applying `arr.slice(2, 4)` without returning the sliced piece or unnecessarily assigning the sliced piece to a variable and return it, is vanity :sweat_smile:

**Comment by raisedadead** [comment]
@ooade is correct, you are not assigning the array returned by `arr.slic` to the array `arr` itself.
Or to make it more clear, it should have been:

```js
var resultArray = arr.slice(...);
return resultArray;
```

Closing as not an issue with the codebase.
