### ISSUE TITLE
I just found a bug in "Returning Boolean Values from Functions"

### ISSUE THREAD

**Issue by tgitari** [freeCodeCamp/freeCodeCamp#14852]
Challenge [Returning Boolean Values from Functions](https://www.freecodecamp.com/challenges/returning-boolean-values-from-functions#?solution=%0Afunction%20isEqual(a%2Cb)%20%7B%0A%20%20%2F%2F%20Fix%20this%20code%0A%20%20%20%20return%20a%20%3D%3D%3D%20b%3B%0A%7D%0A%0A%2F%2F%20Change%20these%20values%20to%20test%0AisLess(10%2C%2015)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function isEqual(a,b) {
  // Fix this code
    return a === b;
}

// Change these values to test
isLess(10, 15);

```

**Comment by rajibmp** [comment]
your function name is `isEqual` and you are calling `isLess` function which is not defined.

**Comment by texas2010** [comment]
@tgitari 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
