### ISSUE TITLE
Not able to resolve the issue of "Add a div element below your h3 element."

### ISSUE THREAD

**Issue by rupamdas1992** [freeCodeCamp/freeCodeCamp#14866]
Challenge [Create a Bootstrap Row](https://www.freecodecamp.com/challenges/create-a-bootstrap-row#?solution=%0A%3Cdiv%20class%3D%22container-fluid%20row%22%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%20%0A%20%20%3Cdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<div class="container-fluid row">
  <div class="row">
    
  <h3 class="text-primary text-center">jQuery Playground</h3> 
  <div>
  </div>
    </div>
</div>



```

**Comment by rajexp** [comment]
I guess you misunderstood the instructions. Here is the solution which works and follows the instructions:

```
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row"></div>
</div>
```

**Comment by raisedadead** [comment]
Hi @rupamdas1992 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by llllaa** [comment]
not able to solve add an div element below your h3 element
