### ISSUE TITLE
the ", 0)" part at the end of reduce, in the example, confuses a beginner like myself.

### ISSUE THREAD

**Issue by DeviatedMind** [freeCodeCamp/freeCodeCamp#14867]
Challenge [Condense arrays with reduce](https://www.freecodecamp.com/challenges/condense-arrays-with-reduce#?solution=%0Avar%20array%20%3D%20%5B4%2C5%2C6%2C7%2C8%5D%3B%0Avar%20singleVal%20%3D%200%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0AsingleVal%20%3D%20array.reduce(%0A%20%20function(hypo%2C%20num)%20%7B%0A%20%20%20%20return%20hypo%20%2B%3D%20num%3B%0A%7D%20)%3B%0A) has an issue.

the ", 0)" part at the end of reduce, in the example, truly confuses a beginner like myself. While the code works without it.

My code:
```javascript

var array = [4,5,6,7,8];
var singleVal = 0;

// Only change code below this line.

singleVal = array.reduce(
  function(hypo, num) {
    return hypo += num;
} );

```
I replaced the ```, 0);``` with ``` );```.

**Comment by rajexp** [comment]
Have a look here
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce?v=control
This tells that we have argument 0 optional here but it raises an error if array is empty. So better to have it in your solution.
