### ISSUE TITLE
H4 elements do not pass

### ISSUE THREAD

**Issue by jonwalz** [FreeCodeCamp/freecodecamp#1486]
Challenge http://beta.freecodecamp.com/challenges/waypoint-label-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

creating the h4 elements does not fulfill the required checkpoint.
![screen shot 2015-08-03 at 4 00 07 pm](https://cloud.githubusercontent.com/assets/249293/9049631/f1c7d192-39f8-11e5-9318-a63fc45cae81.png)

**Comment by BerkeleyTrue** [comment]
confirmed
![waypoint__label_bootstrap_wells___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/9049773/bb82223e-39fa-11e5-8278-b478d52f1587.png)

**Comment by BerkeleyTrue** [comment]
closing this issue as it has been reported in #1480
