### ISSUE TITLE
The wrong output of the test case in challange 290

### ISSUE THREAD

**Issue by chcifung** [freeCodeCamp/freeCodeCamp#14865]
Challenge [Inventory Update](https://www.freecodecamp.com/challenges/inventory-update#?solution=%0Afunction%20updateInventory(arr1%2C%20arr2)%20%7B%0A%20%20%20%20%2F%2F%20All%20inventory%20must%20be%20accounted%20for%20or%20you're%20fired!%0A%20%20if(arr1.length!%3D%3D0%26%26arr2.length!%3D%3D0)%7B%0A%20%20%20%20%0A%20%20%20%20var%20a1%20%3D%20%5B%5D%3B%0A%20%20%20%20for(var%20k%3D0%3Bk%3Carr1.length%3Bk%2B%2B)%7B%0A%20%20%20%20%20%20a1.push(arr1%5Bk%5D%5B1%5D)%3B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20for(l%3D0%3Bl%3Carr2.length%3Bl%2B%2B)%7B%0A%20%20%20%20%20%20if(a1.indexOf(arr2%5Bl%5D%5B1%5D)%3C0)%7B%0A%20%20%20%20%20%20%20%20arr1.push(arr2%5Bl%5D)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20for(var%20i%3D0%3Bi%3Carr1.length%3Bi%2B%2B)%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%20for(var%20j%3D0%3Bj%3Carr2.length%3Bj%2B%2B)%7B%0A%20%20%20%20%20%20%20if(arr1%5Bi%5D%5B1%5D%3D%3Darr2%5Bj%5D%5B1%5D%26%26arr1%5Bi%5D%5B0%5D!%3Darr2%5Bj%5D%5B0%5D)%7B%0A%20%20%20%20%20%20%20%20arr1.splice(i%2C1%2Carr2%5Bj%5D)%3B%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%0A%20%20%20%20%20%7D%0A%20%20%20%20%20%0A%20%20%20%7D%0A%20%20%7Delse%20if(arr1.length%3D%3D%3D0)%7B%0A%20%20%20%20arr1%3Darr2%3B%0A%20%20%7D%0A%20%20%20%0A%20%20arr1.sort(function(x%2Cy)%7B%0A%20%20%20%20return%20x%5B1%5D.localeCompare(y%5B1%5D)%3B%0A%20%20%7D)%3B%0A%20%20return%20arr1%3B%0A%7D%0A%0A%2F%2F%20Example%20inventory%20lists%0Avar%20curInv%20%3D%20%5B%0A%20%20%20%20%5B21%2C%20%22Bowling%20Ball%22%5D%2C%0A%20%20%20%20%5B2%2C%20%22Dirty%20Sock%22%5D%2C%0A%20%20%20%20%5B1%2C%20%22Hair%20Pin%22%5D%2C%0A%20%20%20%20%5B5%2C%20%22Microphone%22%5D%0A%5D%3B%0A%0Avar%20newInv%20%3D%20%5B%0A%20%20%20%20%5B2%2C%20%22Hair%20Pin%22%5D%2C%0A%20%20%20%20%5B3%2C%20%22Half-Eaten%20Apple%22%5D%2C%0A%20%20%20%20%5B67%2C%20%22Bowling%20Ball%22%5D%2C%0A%20%20%20%20%5B7%2C%20%22Toothpaste%22%5D%0A%5D%3B%0A%0AupdateInventory(curInv%2C%20newInv)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function updateInventory(arr1, arr2) {
    // All inventory must be accounted for or you're fired!
  if(arr1.length!==0&&arr2.length!==0){
    
    var a1 = [];
    for(var k=0;k<arr1.length;k++){
      a1.push(arr1[k][1]);
    }
    
    for(l=0;l<arr2.length;l++){
      if(a1.indexOf(arr2[l][1])<0){
        arr1.push(arr2[l]);
      }
    }
    
    for(var i=0;i<arr1.length;i++){
      
     for(var j=0;j<arr2.length;j++){
       if(arr1[i][1]==arr2[j][1]&&arr1[i][0]!=arr2[j][0]){
        arr1.splice(i,1,arr2[j]);
       }
       
     }
     
   }
  }else if(arr1.length===0){
    arr1=arr2;
  }
   
  arr1.sort(function(x,y){
    return x[1].localeCompare(y[1]);
  });
  return arr1;
}

// Example inventory lists
var curInv = [
    [21, "Bowling Ball"],
    [2, "Dirty Sock"],
    [1, "Hair Pin"],
    [5, "Microphone"]
];

var newInv = [
    [2, "Hair Pin"],
    [3, "Half-Eaten Apple"],
    [67, "Bowling Ball"],
    [7, "Toothpaste"]
];

updateInventory(curInv, newInv);

```

I use the updateInventory([[21, "Bowling Ball"], [2, "Dirty Sock"], [1, "Hair Pin"], [5, "Microphone"]], [[2, "Hair Pin"], [3, "Half-Eaten Apple"], [67, "Bowling Ball"], [7, "Toothpaste"]]) should return [[88, "Bowling Ball"], [2, "Dirty Sock"], [3, "Hair Pin"], [3, "Half-Eaten Apple"], [5, "Microphone"], [7, "Toothpaste"]].

The true result should be the 
(6) [Array(2), Array(2), Array(2), Array(2), Array(2), Array(2)]
0
:
Array(2)
0
:
67
1
:
"Bowling Ball"
length
:
2
__proto__
:
Array(0)
1
:
Array(2)
0
:
2
1
:
"Dirty Sock"
length
:
2
__proto__
:
Array(0)
2
:
Array(2)
0
:
2
1
:
"Hair Pin"
length
:
2
__proto__
:
Array(0)
3
:
Array(2)
0
:
3
1
:
"Half-Eaten Apple"
length
:
2
__proto__
:
Array(0)
4
:
Array(2)
0
:
5
1
:
"Microphone"
length
:
2
__proto__
:
Array(0)
5
:
Array(2)
0
:
7
1
:
"Toothpaste"
length
:
2
__proto__
:
Array(0)
length
:
6
__proto__
:
Array(0)

**Comment by raisedadead** [comment]
> challange 290

What is 290?

Hi @chcifung 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by texas2010** [comment]
@chcifung by the way, there has no number of the challenge. more like it is your brownie point. you could look at this link. you will understand. https://forum.freecodecamp.com/t/free-code-camp-brownie-points/18380

Happy coding!
