### ISSUE TITLE
[beta] Regular Expressions: Specify Upper and Lower Number of Matches

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#14878]
Regular Expressions: Specify Upper and Lower Number of Matches
http://beta.freecodecamp.com/en/challenges/regular-expressions/specify-upper-and-lower-number-of-matches

The challenge has difficulties passing some of the tests, refreshing the tab forced the test 
-Your regex should not match "Ohh no"
to pass

but 
-Your regex should not match "Ohhhhhhh no"
still does not pass

![screenshot 2017-05-15 at 9 22 38 am](https://cloud.githubusercontent.com/assets/7606025/26067883/6698e3b4-3950-11e7-9a6e-c52b11634a5b.png)

**Comment by ooade** [comment]
Bug here. None of your test should even pass. It says 3 to 6 on "h" but you did leave out the no... So you're just saying `Ohhh, Ohhhh, Ohhhhh`... Instead of `Ohhh no, Ohhhh no, Ohhhhh no`.

**Comment by tommygebru** [comment]
thanks for this, I didnt think to include the latter part of the string

I have been struggling with the last 2 regex challenges for the better part of an hour now

Regular Expressions: Reuse Patterns Using Capture Groups
Regular Expressions: Remove Whitespace from Start and End

**Comment by raisedadead** [comment]
Is this resolved, if not please revert back, to re-open?

**Comment by QueenAmeerah** [comment]
Here's the code I used to pass this challenge:
let ohStr = "Ohhh no";
let ohRegex = /Oh{3,6}\sno/; // change this line
let result = ohRegex.test(ohStr);
