### ISSUE TITLE
Build a random quote machine - The example on codepen is not working. 

### ISSUE THREAD

**Issue by cantones1** [freeCodeCamp/freeCodeCamp#14875]
Challenge [Build a Random Quote Machine](https://www.freecodecamp.com/challenges/build-a-random-quote-machine) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The example on codepen is not working. There are no quotes being generated.

**Comment by JoolsMcFly** [comment]
Hi,

it's due to `JSON.parse(response)`. It fails because `response` is already an object.

Here's a fork I made that works https://codepen.io/JoolsMcFly/full/Pmapae/

All that needs to be done is change

```js
success: function(response) {
  var r = JSON.parse(response);
```
to

```js
success: function(r) {
```

**Comment by raisedadead** [comment]
Thanks @JoolsMcFly ! We are on it.

**Comment by gnuns** [comment]
Hey! I'm the author of the example project.
Apparently, something changed on the API server and it has broken the code.
Here are a fixed version (and with the tumblr share button working):
http://codepen.io/hezag/full/ZGxOLX/

**Comment by raisedadead** [comment]
@gnuns Thanks a lot, I have updated the production pen (one on freecodecamp.com), can you confirm that I did not make any mistake.

I'll update the beta site (beta.freecodecamp.com), soon too.

**Comment by no-stack-dub-sack** [comment]
@raisedadead This issue was also caught on the testable-projects repo, and I made the correct fixes  on the pen associated with that project as well. So it seems to be fixed in both places now. This can probably be closed?

**Comment by raisedadead** [comment]
Oh awesome! Thanks for the update @no-stack-dub-sack !
