### ISSUE TITLE
Challenge Using Objects for Lookups - Misleading Instructions

### ISSUE THREAD

**Issue by AllstonS** [freeCodeCamp/freeCodeCamp#14879]
Challenge [Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%0A%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20val%20%3D%20%7B%0A%20%20%20%20%22alpha%22%3A%20%22Adams%22%2C%0A%20%20%20%20%20%22bravo%22%3A%20%22Boston%22%2C%20%0A%20%20%20%20%20%22charlie%22%3A%20%22Chicago%22%2C%0A%20%20%20%20%20%22delta%22%3A%20%22Denver%22%2C%0A%20%20%20%20%20%22echo%22%3A%20%22Easy%22%2C%0A%20%20%20%20%20%22foxtrot%22%3A%20%22Frank%22%0A%20%20%7D%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22charlie%22)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.

**Please describe how to reproduce this issue, and include links to screenshots if possible.**

I found using the example to help with the challenge was very misleading. The fact that the example uses [ ] to return the values, and the challenge uses only ( ) is never really explained. I realize that the challenge also uses return result, but the inconsistency and lack of explanation of these differences creates confusion.

My code:
```javascript

// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  val = {
    "alpha": "Adams",
     "bravo": "Boston", 
     "charlie": "Chicago",
     "delta": "Denver",
     "echo": "Easy",
     "foxtrot": "Frank"
  };

  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");
```

**Comment by raisedadead** [comment]
I see where your confusion lies in here as a beginner. Thanks for reporting.

Although I feel we could enhance the example, not to use a function returns at all, this should probably be done like the assignment challenge or the increment/decrement challenge.

/cc @freeCodeCamp/moderators thoughts?

**Comment by Balanced02** [comment]
// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  var lookup =
    { 
      "alpha": "Adams",
      "bravo": "Boston",
      "charlie": "Chicago",
      "delta": "Denver",
      "echo": "Easy",
      "foxtrot": "Frank"
  };
  result = lookup [val]; **//That's the line you're missing out**
  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");

**Comment by Saonyx** [comment]
I must admit, that is a rather clever answer @Balanced02. In my code, I got the initial setup of the dictionary, but I wasn't understanding how to interact with that object. Thanks for the clarification.

**Comment by Balanced02** [comment]
You're welcome @Saonyx happy to help...
