### ISSUE TITLE
flexwrap challenge has superfluous text

### ISSUE THREAD

**Issue by spieg** [freeCodeCamp/freeCodeCamp#14876]
Challenge [use-the-flexwrap-property-to-wrap-a-row-or-column](http://beta.freecodecamp.com/en/challenges/css-flexbox/use-the-flexwrap-property-to-wrap-a-row-or-column) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

In the text of the challenge , stating the options for align-items is confusing in a flexwrap challenge.

> The current layout has too many boxes for one row. Add the CSS property flex-wrap to the #box-container element, and give it a value of wrap.
> 
> flex-start: aligns items to the start of the flex container. For a row, this pushes the items to the left of the container. For a column, this pushes the items to the top of the container.
> flex-end: aligns items to the end of the flex container. For a row, this pushes the items to the right of the container. For a column, this pushes the items to the bottom of the container.
> space-between: aligns items to the center of the main axis, with extra space placed between the items. The first and last items are pushed to the very edge of the flex container. For example, in a row the first item is against the left side of the container, the last item is against the right side of the container, then the other items between them are spaced evenly.
> space-around: similar to space-between but the first and last items are not locked to the edges of the container, the space is distributed around all the items

**Comment by spieg** [comment]
Apparently it has to do with how you get to the challenge, Cause I also saw it on the next challenge. And now it's gone on both challenges.

**Comment by raisedadead** [comment]
Yeah, some screenshots, and your code if any should help. Thanks for reporting. Please revert back with these.

**Comment by raisedadead** [comment]
Please revert back with screenshots and more details if possible.
