### ISSUE TITLE
Challenge not working 

### ISSUE THREAD

**Issue by mobilecititechs** [freeCodeCamp/freeCodeCamp#14874]
Challenge [Quoting Strings with Single Quotes](https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes#?solution=%0Avar%20myStr%20%3D%20%22%3Ca%20href%3D%5C%22http%3A%2F%2Fwww.example.com%5C%22%20target%3D%5C%22_blank%5C%22%3ELink%3C%2Fa%3E%22%3B%0Avar%20myStr%20%3D%20'%3Ca%20href%3D%22http%3A%2F%2Fwww.example.com%22%20target%3D%22_blank%22%3ELink%3C%2Fa%3E'%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "<a href=\"http://www.example.com\" target=\"_blank\">Link</a>";
var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';


```

**Comment by texas2010** [comment]
@mobilecititechs nothing wrong with this challenge.  first thing is you need to remove first line. so you could pass this challenge.  

Happy Coding.

**Comment by texas2010** [comment]
Next time, please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
