### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Renestl** [FreeCodeCamp/freecodecamp#1487]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Selecting the button to proceed to the next challenge causes a 502 Bad Gateway error.

![capture 1](https://cloud.githubusercontent.com/assets/13346359/9050020/822d085a-3a0e-11e5-80af-74f003894f0c.PNG)
![capture2](https://cloud.githubusercontent.com/assets/13346359/9050019/822927a8-3a0e-11e5-8406-2c5a3777a1f7.PNG)

**Comment by BerkeleyTrue** [comment]
Hello @Renestl 

The beta site must have temporarily crashed or I might have been restarting it between pull requests. It should be working now. Happy Coding!

**Comment by BerkeleyTrue** [comment]
My Apologies @Renestl Looks like this came back. We will be tracking this in #1386
