### ISSUE TITLE
Track challenge submissions count

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#14881]
Modify this bit here to add a count of number of times use has submitted this challenge:

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/server/boot/challenge.js#L32-L36

Something like this:
```js
 finalChallenge = {
    ...completedChallenge,
    completedDate: oldChallenge.completedDate,
    lastUpdated: completedChallenge.completedDate,
    numOfAttempts: oldChallenge.numOfAttempts + 1
 };
```

Happy Coding!

**Comment by hemanthsavasere** [comment]
Hello,
I am a newcomer, can I start working on this.

**Comment by user512** [comment]
Looking forward to your pull request, @hemanthsavasere

**Comment by raisedadead** [comment]
@hemanthsavasere Sure, be sure to go through the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

Happy Coding!

**Comment by jonathanihm** [comment]
@hemanthsavasere are you still on this or can I jump on?

**Comment by BerkeleyTrue** [comment]
This one is still open. Please remember to verify that your changes have the desired effect.

Submitting a challenge, check the database and see the count on the challenge, submit the same challenge, check the database again to see if the count has increased

**Comment by akshatbahety** [comment]
@BerkeleyTrue How do I confirm if the challenge is completed from the database?

**Comment by dakshshah96** [comment]
Hey @BerkeleyTrue, can't see any of the fields in the database when I run this in my mongo shell — `db.challenge.find({"title": "Change the Color of Text"});`. Fields `completedDate`, `lastUpdated`, 'numOfAttempts` are missing.

**Comment by raisedadead** [comment]
Hi, @dakshshah96 @akshatbahety thanks for your interest in helping us out.

I recommend you use a tool such as https://robomongo.org/download, to graphically check the local MongoDB.

You would also have to add the missing keys to the User model in code.

This can be referred from the loopback docs https://loopback.io

**Comment by dakshshah96** [comment]
@raisedadead Thanks for that!

I'm using MongoDB Compass. When I sign up using a sample account details in my local instance, there is no `users` collection in the `freecodecamp` database. Just these three — `block`, `challenge`, `sessions`.

**Comment by akshatbahety** [comment]
@raisedadead Thanks 

But I don't think I will be able to solve this issue, its  beyond my knowledge right now will learn MongoDB and get back :)

**Comment by OGZCoder** [comment]
Is anybody still working on this? I am going to jump on it anyway, but let me know if someone is already working on this and I'll choose another issue

**Comment by texas2010** [comment]
@OGZCoder you can work on this.

**Comment by OGZCoder** [comment]
Already started

**Comment by QuincyLarson** [comment]
@ogzcoder Have you had any luck with this?

**Comment by ogzcoder** [comment]
@QuincyLarson, actually I have, im going to clean up my commits over the weekend
