### ISSUE TITLE
syntax errors in explanation

### ISSUE THREAD

**Issue by eaglecookie** [FreeCodeCamp/freecodecamp#1488]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue.

The initial explanation says:
Now you know three ways of targeting elements: by type ($('button')), by class (($('.btn')), and by id (($'#target1')).

I think that there is an extra parentheses before the $ of the class element, and the $ should be before the parentheses for the id element. This might trip up newbies like me. :-)

Also, is there a place to see if an issue has already been reported? I've never tested on a beta site, and I don't want to bog you down with problems that you already know.

**Comment by BerkeleyTrue** [comment]
@eaglecookie You can search in the the text input at the top of github here:

![syntax_errors_in_explanation_ _issue__1488_ _freecodecamp_freecodecamp](https://cloud.githubusercontent.com/assets/6775919/9050296/3923a478-3a01-11e5-86ab-0871c3d7992f.png)

I think this is a new one, though! Thanks for reporting!

**Comment by sonorangirl** [comment]
I think there's also a mistake in the instructions for this task, it asks you to add a class of 'button-primary' to the #target1 element. It should say to add 'btn-primary' instead.  The test is correct for it though.

<img width="779" alt="screen shot 2015-08-04 at 3 24 47 pm" src="https://cloud.githubusercontent.com/assets/6051437/9074323/51cc3e10-3abd-11e5-9529-b7067ecc66ce.png">

**Comment by QuincyLarson** [comment]
@eaglecookie and @sonorangirl thank you for pointing out these issues. I've fixed them and I've credited you in the commit message.
