### ISSUE TITLE
Return Largest Numbers in Arrays - undefined as Loop does not contain proper value.

### ISSUE THREAD

**Issue by atheriault** [freeCodeCamp/freeCodeCamp#14887]
#### Challenge Name
Return Largest Numbers in Arrays

#### Issue Description
First time through the z for loop and it is returning a value of 4 not 0 as it should be.  This then causes the inside for loop to be out of bounds and returns an undefined and errors out. I have attached a screenshot of the console log to show that it starts at 4.

#### Browser Information

* Browser Name, Version: Chrome 58.013029.81
* Operating System: OSX
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code
```js
function largestOfFour(arr) {
  // You can do this!
  var returnArr = [];
  var highestNumber = 0;
  
  for(var z = 0; z < arr.length; z++)
    // going through the main arrays
    highestNumber = 0;
    console.log(z);
    for(var x = 0; x < arr[z].length; x++){
      // going throught the sub arrays 
      if (arr[z][x] > highestNumber){
        highestNumber = arr[z][x];
      }
    }

    returnArr.push(highestNumber);
  return returnArr;
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);
```

#### Screenshot
![screen shot 2017-05-15 at 9 44 27 pm](https://cloud.githubusercontent.com/assets/7085109/26090255/888af22e-39b8-11e7-96f4-7fbcf6010621.png)

**Comment by jonathanihm** [comment]
Looks like you forgot brackets on the outer for loop.  Cheers! :-)
