### ISSUE TITLE
Introducing Else If Statements Issue

### ISSUE THREAD

**Issue by aefreema22** [freeCodeCamp/freeCodeCamp#14882]
Introducing Else If Statements

https://www.freecodecamp.com/challenges/introducing-else-if-statements

#### Issue Description

When entering the request based on the example provided the curly bracket behind  the second instance of "else" is wrong according to the console and will not accept the correction.  

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js

function testElseIf(val) {
  if (val > 10) {
    return "Greater than 10";
  }
  
  else if (val < 5) {
    return "Smaller than 5";
  }
else 
  return "Between 5 and 10";
}

// Change this value to test
testElseIf(7);



```
![capture](https://cloud.githubusercontent.com/assets/26582924/26082357/6fc4346e-399d-11e7-9118-f29b41ff97ad.JPG)

**Comment by hemanthsavasere** [comment]
Hello,
I am ready to work on this issue.

**Comment by raisedadead** [comment]
@aefreema22 your code passes for me. Can you share a screenshot of the console?

**Comment by texas2010** [comment]
@aefreema22 you have to add else {} as you write it. that is what this challenge asked you do that.

I close this issue. it seems this challenge don't have a problem.
if you think I make mistake to close this. please explain.

**Comment by miracle2542** [comment]
Dude, you have left out the curly braces for the last else statement; Your curly braces did not match.
