### ISSUE TITLE
Unable to Run Test even after clicking run test button

### ISSUE THREAD

**Issue by ashfaqahmed177** [freeCodeCamp/freeCodeCamp#14885]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment]
Hi @ashfaqahmed177 

Can you please share the details as needed in the opening post above? We need information as requested in the issue template above, before we can help you with your query.

Let us know in the comments. If you need assistance in creating the issue correctly, reach out to the  [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by jodellgroup** [comment]
<p>hello world</p>

<h2>CatPhotoApp</h2>
<h2></h2>
How do i comment out my p element so that is not visible on my page
<p>Hello Paragraph</p>


<p>textbooks.ng</p>
