### ISSUE TITLE
Incorrect phrasing on challenge "Drop It"

### ISSUE THREAD

**Issue by mattxgreen** [freeCodeCamp/freeCodeCamp#14880]
Challenge [Drop it](https://www.freecodecamp.com/challenges/drop-it#?solution=function%20dropElements(arr%2C%20func)%20%7B%0A%20%20return%20!arr.length%20%7C%7C%20func(arr%5B0%5D)%20%3F%20arr%20%3A%20dropElements(arr.slice(1)%2Cfunc)%3B%0A%20%20%2F%2F%20return%20(arr.filter(func).length)%20%3F%20arr.splice(arr.indexOf(arr.filter(func)%5B0%5D))%20%3A%20%5B%5D%20%3B%0A%7D) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I believe the using the term "argument" In the first sentence of this challenge is used incorrectly, and could be confusing, especially considering the second sentence.

**The current challenge text reads:**
Drop the elements of an array (first argument), starting from the front, until the predicate (second argument) returns true.

The second argument, func, is a function you'll use to test the first elements of the array to decide if you should drop it or not.

**I propose it reads:** 
Drop the elements of an array, starting from the first (0 index), until the predicate (second **element**) returns true.

The second argument, func, is a function you'll use to test the first elements of the array to decide if you should drop it or not.

**Comment by raisedadead** [comment]
Thanks, @mattxgreen. 

I think we could make this even clearer. Suggestions welcome.

**Comment by dakshshah96** [comment]
@raisedadead @mattxgreen I suppose using argument here is correct since `arr` is the first argument and `func` is the second argument (a function used to check whether an element needs to be dropped or not) of the `dropElements` function.

**Comment by jonathanihm** [comment]
I would have to agree with Daksh that the use of the word argument is correct.  However I can also agree that it may be worded in a more concise way.  What about:

The dropElements function has two arguments.  The first argument is an array, arr, which will be our source array we want to work on.  The second argument is our predicate, func, a function which will be used to test whether or not an element should be removed.

You will need to alter the dropElements function so we drop elements off of arr until func returns true.

If we do go forward with any changes, I would be happy to have this as my first PR.

**Comment by raisedadead** [comment]
Hmm, I'll seek the expert advice from @erictleung ! 
Eric has always been the best at verbiage 🙏 ✨ .

**Comment by erictleung** [comment]
@raisedadead thanks for the summoning :smile: 

Mmm yeah, I agree that this challenge needs to be revised. I like most of @jonathanihm's revision, but I don't like the use of "predicate." It makes when you [look it up](https://en.wikipedia.org/wiki/Predicate_%28mathematical_logic%29), but otherwise, it seems too jargon-filled, in my opinion.

How about something like this:

> Given the array `arr`, remove elements starting from the left-most element (the 0 index) of this array until the condition given in the function `func` is `true`.
>
> In other words, iterate through the elements in `arr` and pass it through the function `func` until it returns `true`. Return the rest of array once the condition is satisfied, otherwise, return an empty array.

I've cut a lot of the instructions out, but I think it is more concise and hopefully easier to understand. Feel free to suggest changes to my try at it. If there's anything unclear, please point it out. Additionally, if it is too easy, feel free to criticize that as well.

**Comment by dakshshah96** [comment]
@ericleung That sounds good to me! Here's something else we could use:

> Given the array `arr`, drop the elements starting from the first element (the 0 index) of this array until the function `func` returns `true` when the array is passed through it.
> 
> Then return rest of the array once the condition is satisfied, otherwise, return an empty array.

**Comment by jonathanihm** [comment]
I think Daksh's version looks pretty clear, but doesn't mention iterate (which I think might give clues to beginners on what they should be doing).  I think a minor change and it would look really good.

> Given the array arr, iterate through it and then drop each element starting from the first element (the 0 index) of this array until the function func returns true when the array is passed through it.
> 
> Then return rest of the array once the condition is satisfied, otherwise, return an empty array.
