### ISSUE TITLE
Unexpected Token )

### ISSUE THREAD

**Issue by kyrize** [FreeCodeCamp/freecodecamp#1489]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Upon entering this waypoint, 'Unexpected Token )' was a criteria to pass the exercise. It is either a glitch on my part or there is a missing criteria.

**Comment by BerkeleyTrue** [comment]
Hello @kyrize

This was just fixed but has not been pushed up. See #1450 Thanks for reporting! Happy Codding!
