### ISSUE TITLE
Instruction and Checking constraints mismatch (wtf?)

### ISSUE THREAD

**Issue by D3V4N5H** [freeCodeCamp/freeCodeCamp#14904]
Checking and Instructions mismatch
<img width="313" alt="weee" src="https://cloud.githubusercontent.com/assets/14008529/26125663/8588b12c-3aa0-11e7-8211-b51836680d5e.PNG">

Why are other issues closed?
like #10112 #9317 #10459 #12299 #13002 #13147 #13767 #14503 #14562 #14691

Challenge [Understanding Uninitialized Variables](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables#?solution=%0A%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%3B%0Avar%20b%3B%0Avar%20c%3B%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0Avar%20a%3D6%2C%20b%3D15%2C%20c%3D%22I%20am%20a%20String%22%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Initialize these three variables
var a;
var b;
var c;

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";

var a=6, b=15, c="I am a String";
```

**Comment by erictleung** [comment]
@D3V4N5H thanks for the issue. In the last issue you referenced, this lesson was actually updated to resolve what I interpret is the same issue you're bringing up here https://github.com/freeCodeCamp/freeCodeCamp/pull/14748. Please take a look at those changes and if they resolve your issue or not. If not, please comment back here with your suggestions and we can discuss it further. Thanks!

**Comment by raisedadead** [comment]
Closing as violation of [Code of Conduct](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CODE_OF_CONDUCT.md)
