### ISSUE TITLE
Back end test suite

### ISSUE THREAD

**Issue by Selhar** [freeCodeCamp/freeCodeCamp#14906]
Challenge [anonymous-message-board](http://beta.freecodecamp.com/en/challenges/information-security-and-quality-assurance-projects/anonymous-message-board) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
----
I cloned [this](https://github.com/freeCodeCamp/boilerplate-project-messageboard/) repo, added this line of code: `process.env.NODE_ENV = 'test';`
and then did "node server.js".
The server runs, but the tests don't seem to, i just get stuck with the following output: 
http://i.imgur.com/diPR6Jy.png
I can't see what the test parameters are or how to pass them, there's no output.

ps. the "listening on port undefined" warning isn't relevant, it's still listening on port 300, it's just a mistake in the console.log code
ps2. i'm not using glitch.io, all of these tests were done on my local machine, but it seems to be [bugging on glitch too](https://forum.freecodecamp.com/t/beta-challenge-install-and-set-up-mongoose/110688)

**Comment by QuincyLarson** [comment]
@Em-Ant do you know what might be causing this?

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
