### ISSUE TITLE
[beta] Create job queues for emails

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#14902]
Refers #9660

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (119/100 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:40451)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPURQ-00005i-Pk
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:57:08 -0400
Received: from out-5.smtp.github.com ([192.30.252.196])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUQh-0006RL-HE
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:56:23 -0400
Date: Sun, 03 Jun 2018 07:56:22 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037782;
	bh=mKp/3GGcGEUyNSzE5dWJjvzjn9FXgpSq4HldeRsSv4Q=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Di52cb8zech5MHgfOlC4Ig+Yup8mpaqAJTC5Xls0faZ7RVQYMN7CgR3Db0nRDspLz
	 cNTca0de6cILVUX/fkogf3g03dA3GkWJZ/EEz4GtG9C+2k3iYbQ/yhNsAZWoCVVqtG
	 tyGo7GntqSvMuJYA/fDdPIiCNsWsDDYcEccBjhbA=

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (118/100 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:40452)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPURQ-00005j-PD
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:57:08 -0400
Received: from out-5.smtp.github.com ([192.30.252.196])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUQl-0006RS-PP
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:56:28 -0400
Date: Sun, 03 Jun 2018 07:56:26 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037787;
	bh=gUNHHCUSLp7EtBKBA6o1kumnBN96NYljZy7k99tHq9E=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=IO1JvgssaxHxFsbIwKpH8KPq/cMY5Ul6S0z6uA3v0W/KWTsUkanzXBwBFOY0SdJ2x
	 iNDFuzqAgwXYW1uD9sHSbFg2cn5DTUmSvxhS2xOLRKGKAkKnMhY+2wMnKa2KAjNDgj
	 71YdfmS2nfdhPacSCnhpKu+m3c2COcMcNr5/Tzu0=
