### ISSUE TITLE
Codepen.io is throwing uncaught exception json at 0 ??? How to run it

### ISSUE THREAD

**Issue by dodlaashwini** [freeCodeCamp/freeCodeCamp#14913]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment]
Please share details as requested in the issue template above.

**Comment by texas2010** [comment]
closing this issue as no respond.
