### ISSUE TITLE
Tutorial on mLab should be added

### ISSUE THREAD

**Issue by thomlom** [freeCodeCamp/freeCodeCamp#14912]
#### Challenge Name

[Mongoose project](http://beta.freecodecamp.com/en/challenges/mongodb-and-mongoose/install-and-set-up-mongoose)

#### Issue Description

The challenge is saying : 

> [...] Then require mongoose. Store your mLab database URI in the private .env file as MONGO_URI 

Problem is that nothing have been said previously on mLab.

It could be more "user friendly" to have a link that redirects to mlab and to precise how to signup, create a database, add a new database user, etc.

I wanted to precise it just in case.

Keep up the good work ! 😄 

>

**Comment by thomlom** [comment]
If that needs to modify just to change the challenge in the `seeds` folder, I can handle this problem.

**Comment by mohitgarg** [comment]
I have done a few projects with mlab. I can make a beginner friendly guide if you guys like!

**Comment by dakshshah96** [comment]
@raisedadead Anything I can help with here?

**Comment by FranciscoKnebel** [comment]
I'm not sure how creating new challenges work, i'll look up later, but I can handle this issue.

Should it work like the challenge previous to this one: https://beta.freecodecamp.org/en/challenges/mongodb-and-mongoose/introduction-to-the-mongodb-and-mongoose-challenges

I was thinking of a new challenge with multiple steps;

- how to create an mLab account (link to mLab, image showing inputs).
- create a free sandbox (select provider, region and input the db name) and confirm.
- create a new user on the newly created db.
- show how to obtain the mLab URI.

This challenge would come before "Install and Set Up Mongoose", so the user would have the URI ready for use.

**Comment by raisedadead** [comment]
Yes, this is totally a good place to start. Let us know if you are stuck at figuring out how to add a challenge.

Refer: [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors).
