### ISSUE TITLE
Some JavaScript codes to practice, very crucial for technical tests

### ISSUE THREAD

**Issue by Pulkit219** [freeCodeCamp/freeCodeCamp#14921]
I couldn't find a better contact page so posting it here , specially referring to Quincy Larson.
My only suggestion is that it should be added to the front-end list for more parctice
`https://www.codementor.io/nihantanu/21-essential-javascript-tech-interview-practice-questions-answers-du107p62z`
```

**Comment by texas2010** [comment]
@QuincyLarson, someone left a message to you.

**Comment by raisedadead** [comment]
@Pulkit219 thanks for the suggestion. 

So far the resource shared is too, interview oriented and doesn't fit the format of front-end curriculum per se. Although, I can see that concepts are already covered in the curriculum.

IMHO this resource is great as it is, please consider sharing it on the wiki (our forum), with due credits to the author.
