### ISSUE TITLE
What is wrong?

### ISSUE THREAD

**Issue by raskolnicon** [freeCodeCamp/freeCodeCamp#14925]
Challenge [Find the Length of a String](https://www.freecodecamp.com/challenges/find-the-length-of-a-string#?solution=%0A%2F%2F%20Example%0Avar%20firstNameLength%20%3D%200%3B%0Avar%20firstName%20%3D%20%22Ada%22%3B%0A%0AfirstNameLength%20%3D%20firstName.length%3B%0A%0A%2F%2F%20Setup%0Avar%20lastNameLength%20%3D%208%3B%0Avar%20lastName%20%3D%20%22Lovelace%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AlastNameLength%20%3D%20lastName.length%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var firstNameLength = 0;
var firstName = "Ada";

firstNameLength = firstName.length;

// Setup
var lastNameLength = 8;
var lastName = "Lovelace";

// Only change code below this line.
lastNameLength = lastName.length;



```

**Comment by texas2010** [comment]
@raskolnicon you are not supposed to touch this line. var lastNameLength = 8;   you need to redo it again.

so this challenge don't have an issue.

Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
