### ISSUE TITLE
Mobile Browsers are not working perfectly for some challenges (especially HTML)

### ISSUE THREAD

**Issue by vyyres** [freeCodeCamp/freeCodeCamp#14922]
#### Challenge Name
Use a CSS Class to Style an Element
(could happen with others, but only tested this one so far)

#### Issue Description
kept saying one of the checks was wrong (the text was not showing up red), after several checks it was all correct so i went to the next challenge which was acting odd so i switched to desktop mode, it completed that one then took me to the previous one listed above and was fixed.

#### Browser Information

* Browser Name, Version: google search browser
* Operating System: android
* Mobile, Desktop, or Tablet: mobile

**Comment by raisedadead** [comment]
Hi @vyyres 

Thanks for the report, yes this has come up many times especially with mobile browsers. Can you check if the space characters are not the culprit, usually deleting the spaces in the CSS part of your code and adding them again works.

This is weird how mobile browsers are interpreting spaces sometimes.

**Comment by raisedadead** [comment]
I think we should have a different strategy for mobile devices completely. The current challenge layout is not very user-friendly.

Note: We recommend using a desktop over mobile because UX of coding on a desktop is much simpler than on a tiny screen. However, we do understand that mobile devices support can be enhanced much more than it currently is.

Suggestions welcome.

**Comment by vyyres** [comment]
i did play with the spacing in the css lines and that does fix it, with this particular problem it was the spaces it puts in before the color: red; line

**Comment by raisedadead** [comment]
@vyyres thanks, for confirming.

**Comment by texas2010** [comment]
this issue already fix in beta.  code editor will ignore fake space.  no need to keep this issue open. thanks.
https://github.com/freeCodeCamp/freeCodeCamp/pull/11472
