### ISSUE TITLE
143  Escape Sequences in Strings : Whats the problem in my code?

### ISSUE THREAD

**Issue by rishikeshct** [freeCodeCamp/freeCodeCamp#14928]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22FirstLine%5Cn%5C%5CSecondLine%5C%5C%5Crfn%22%3B%20%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "FirstLine\n\\SecondLine\\\rfn"; 


```

**Comment by indefinite0212** [comment]
Hi @rishikeshct 
your code is incorrect make sure you copy the correct Text. you can ask first at [JavaScript Help room ](https://gitter.im/FreeCodeCamp/HelpJavaScript ) before posting a git hub issue

**Comment by raisedadead** [comment]
Hi @rishikeshct 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
