### ISSUE TITLE
Comparisons with the Logical And Operator - Incorrect description of operator

### ISSUE THREAD

**Issue by jbosman** [freeCodeCamp/freeCodeCamp#14920]
#### Challenge Name
Comparisons with the Logical And Operator

#### Issue Description
The description for how the logical And Operator in this exercise is incorrect. It says the following:
The logical and operator (&&) returns true if and only if the operands to the left and right of it are true.

The operator actually returns either the result of the first of second argument. Which may not be a true of false value.
i.e. 
     "test" && "testing" will return "testing"
     0 && true will return 0

I understand it may be worded here for learning purposes, but I think pointing these things out as you're first learning these concepts can be helpful.

Here is a link to the ecmascript link for logical operators (the note at the bottom of the section describes what I'm referring too here):
http://www.ecma-international.org/ecma-262/6.0/#sec-12.12

**Comment by raisedadead** [comment]
@jbosman Thanks for the report! I tend to incline towards your comment. But that said, IMHO yes, the verbiage is meant for absolute beginners (which is a major part of our target audience). 

I agree too, this use case is used all the time in real life code. But these differences should come in as additional supplementary challenges and not this challenge itself to NOT confuse new campers.

**Comment by jbosman** [comment]
@raisedadead Yeah, I understand. 

Maybe something to keep in mind though if you're planning to add any modules on falsey values which I think this topic could be a good intro too. 

Do you know if there are plans to add intermediate or advanced javascript topics to the curriculum? There are a lot of future topics it looks like, but I don't see any more vanilla javascript sections ( intermediate or advanced ) that would probably be helpful for the future topics such as React.

**Comment by raisedadead** [comment]
Yes, I agree. Also, we are always expanding the challenges, if you are interested, please feel free to comment with any challenge ideas to illustrate truthy/falsy concepts.

This can be discussed in the thread and after a consensus, we can open the issue for contribution via a pull request.

Thanks once again.
