### ISSUE TITLE
Ambiguous phrasing in Drop it

### ISSUE THREAD

**Issue by etet245** [freeCodeCamp/freeCodeCamp#14939]
#### Challenge Name

Drop it
https://www.freecodecamp.com/challenges/drop-it#?solution=%0Afunction%20dropElements(arr%2C%20func)%20%7B%0A%20%20%2F%2F%20Drop%20them%20elements.%0A%20%20var%20newArr%20%3D%20arr.slice(0)%3B%0A%20%20%0A%20%20while%20(newArr.length%3E0)%20%7B%0A%20%20%20%20console.log(newArr)%3B%0A%20%20%20%20if%20(!func(newArr%5B0%5D))%20%7B%0A%20%20%20%20%20%20newArr.shift()%3B%0A%20%20%20%20%7D%20else%20if%20(newArr.length%20%3D%3D%3D%20arr.length)%20%7B%0A%20%20%20%20%20%20return%20%5B%5D%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20return%20newArr%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20return%20newArr%3B%0A%7D%0A%0AdropElements(%5B1%2C%202%2C%203%5D%2C%20function(n)%20%7Breturn%20n%20%3C%203%3B%20%7D)%3B%0A

#### Issue Description

The third paragraph of the instructions can be subject to the wrong interpretation. It's currently phrased "Return the rest of the array, otherwise return an empty array." Since we're supposed to return the rest of the array after elements have been removed, this sentence can be interpreted as meaning that we should return an empty array if no elements were removed, but based on the test cases, that's not true.

A more accurate revision could be "Return the rest of the array. If there are no elements left, return an empty array."

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by jonathanihm** [comment]
Please also look at https://github.com/freeCodeCamp/freeCodeCamp/issues/14880

**Comment by erictleung** [comment]
Closing as very similar to #14880 as @jonathanihm has pointed out. Feel free to continue the discussion over on that issue. Happy coding!
