### ISSUE TITLE
Point bug modal to forum instead of github issue tracker

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#14934]
When a user creates a bug report, that should be done in the forum. We will use that forum as a staging place for issues. Forums are more conducive to discussion. There on the forum moderators can then escalate issues.

This needs to happen on both staging and on backup/master

**Comment by padulam** [comment]
@BerkeleyTrue I'd like to take this one on. Should we direct them to a specific topic or just the forum home page?
