### ISSUE TITLE
Diff Two Arrays - The outputs match but the code isn't accepted.

### ISSUE THREAD

**Issue by abhinavagrawal1995** [freeCodeCamp/freeCodeCamp#14936]
Challenge [Diff Two Arrays](https://www.freecodecamp.com/challenges/diff-two-arrays#?solution=%0Afunction%20diff(arr1%2C%20arr2)%20%7B%0A%20%20%2F%2F%20difference%20between%20set%20A%20and%20set%20B%0A%20%20const%20diff%20%3D%20(A%2C%20B)%20%3D%3E%20new%20Set(%5B...A%5D.filter(n%20%3D%3E%20!B.has(n)))%3B%0A%20%20%2F%2F%20spread%20operator%20to%20convert%20array%20like%20object%20to%20array%0A%20%20const%20result%20%3D%20%5B...arguments%5D%0A%20%20%20%20%2F%2F%20map%20elements%20in%20arguments%20(array)%20to%20Set%0A%20%20%20%20.map(arr%20%3D%3E%20new%20Set(arr))%0A%20%20%20%20%2F%2F%20using%20the%20formula%20in%20https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FSymmetric_difference%0A%20%20%20%20%2F%2F%20i%20reduce%20it%20by%20uniting%20the%20diff(A%2C%20B)%20and%20diff(B%2C%20A)%0A%20%20%20%20.reduce((acc%2C%20set)%20%3D%3E%20new%20Set(%5B...diff(acc%2C%20set)%2C%20...diff(set%2C%20acc)%5D))%3B%0A%0A%20%20%2F%2F%20convert%20the%20set%20to%20array%20by%20using%20spread%20operator%20again%0A%20%20return%20%5B...result%5D%3B%0A%7D%0A%0Adiff(%5B%22diorite%22%2C%20%22andesite%22%2C%20%22grass%22%2C%20%22dirt%22%2C%20%22pink%20wool%22%2C%20%22dead%20shrub%22%5D%2C%20%5B%22diorite%22%2C%20%22andesite%22%2C%20%22grass%22%2C%20%22dirt%22%2C%20%22dead%20shrub%22%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function diff(arr1, arr2) {
  // difference between set A and set B
  const diff = (A, B) => new Set([...A].filter(n => !B.has(n)));
  // spread operator to convert array like object to array
  const result = [...arguments]
    // map elements in arguments (array) to Set
    .map(arr => new Set(arr))
    // using the formula in https://en.wikipedia.org/wiki/Symmetric_difference
    // i reduce it by uniting the diff(A, B) and diff(B, A)
    .reduce((acc, set) => new Set([...diff(acc, set), ...diff(set, acc)]));

  // convert the set to array by using spread operator again
  return [...result];
}

diff(["diorite", "andesite", "grass", "dirt", "pink wool", "dead shrub"], ["diorite", "andesite", "grass", "dirt", "dead shrub"]);
```

**Comment by forkerino** [comment]
You changed the function name...

**Comment by texas2010** [comment]
@forkerino is right about that.

Happy Coding.
