### ISSUE TITLE
Syntax Error in Explanation

### ISSUE THREAD

**Issue by eaglecookie** [FreeCodeCamp/FreeCodeCamp#1493]
Challenge http://beta.freecodecamp.com/challenges/waypoint-disable-an-element-using-jquery has an issue. 

In the explanation, it states:
Here's how you would disable all buttons: $('#button').prop('disabled', true);

But wouldn't it be $('button') without the #, or $('.btn') since it's not an id?

**Comment by benschenker** [comment]
Closing as stale
