### ISSUE TITLE
#target 4 .remove function

### ISSUE THREAD

**Issue by eaglecookie** [FreeCodeCamp/FreeCodeCamp#1494]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-appendto-to-move-elements-with-jquery has an issue.

...if we wanted to move "target4" from our right well to our left well, we would use $('#target4').appendTo('#left-well');

HOWEVER, target4 doesn't show up in the right well upon opening. The following function needs to be removed in the script element:

$('#target4').remove();

**Comment by benschenker** [comment]
Closing as stale
