### ISSUE TITLE
word-blanks

### ISSUE THREAD

**Issue by raiden357** [freeCodeCamp/freeCodeCamp#14943]
This is not a well explained exercise. I randomly tried to add a comma and it worked.
Why does it finally work when I add a comma  inside the double quotes ? i was just trying to use the quotes to create a space between the variables

Challenge [word-blanks](http://beta.freecodecamp.com/en/challenges/basic-javascript/word-blanks) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  result = "The " + myNoun + "," +  myAdjective + " looked around " + myVerb + " then " + myAdverb;

  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```

**Comment by huyenltnguyen** [comment]
Hi! I just tested the challenge and it worked fine for me.
Did you use the empty string `""` instead of `" "` by any chance? The words should be separated by non-word characters, so the `""` is not accepted here.

**Comment by raiden357** [comment]
Thanks for the help. That seemed to be the problem. I didn't know that there was a difference
