### ISSUE TITLE
Image Appears, but Tests says it doesn't.

### ISSUE THREAD

**Issue by RayF99** [freeCodeCamp/freeCodeCamp#14944]
In the live viewer, my image shows. This should be proof enough that the src is pointing to it, right? Why is the tests saying otherwise?

Challenge [Add Images to your Website](https://www.freecodecamp.com/challenges/add-images-to-your-website#?solution=%0A%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%20%20%0A%3C%2Fstyle%3E%0A%0A%3Cimg%20src%3D%22https%3A%2F%2Fs3.amazonaws.com%2Ffreecodecamp%2Frelaxing-cat.jpg%22%0A%20%20alt%3D%22Cute%20kitten%20relaxing%20the%20page.%22%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.47 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }
  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  
</style>

<img src="https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg"
  alt="Cute kitten relaxing the page.">

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by Marmiz** [comment]
@RayF99 thanks for reporting this issue.

The challenge is asking you to add a specific image source here:
>Try it with this image:
https://bit.ly/fcc-relaxing-cat

Make sure you're using the provided link since the test will look exactly for that.
Next time feel free to ask for assistance in one of the [official chat rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390)

**Comment by texas2010** [comment]
@freeCodeCamp/moderators 

Do we need to add another test for passing this URL "https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg"?

I noticed some people would use that URL.   

thought?

**Comment by RayF99** [comment]
The reason why I used the URL  "https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg" was because in the example given, the URL src code had a .jpg at the end. I thought you HAD to have the URL with that .jpg for the src code to work.
Someone did point out to me that even though my code was correct, FreeCodeCamp only counted the answer correct if we used the link provided in it's original form.  Is there a way for FreeCodeCamp to modify the challenge so that both answers are accepted, especially if the error is being made by many people?

**Comment by raisedadead** [comment]
Hi @RayF99, sorry about the delay in getting back to you. 
Yes, we have fixed this in our beta website where we accept both the URLs.

Unfortunately, we are unable to deploy the beta website (http://beta.freecodecamp.com) to production (https://freecodecamp.com), anytime soon before the new curriculum expansion and feature upgrades are ready.

We request you meanwhile continue using the URL that the challenge is expecting.

We accept this is and error on our part, and stay tuned for our upcoming release where the issue will be corrected.

Thanks for reporting and happy coding!

**Comment by speesey** [comment]
I also stumbled on this challenge, because I used the "https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg" URL.  When I used this URL, I was not allowed to advance to the next challenge.  Just wanted to point that out, since I saw the above response that stated both URLs would work.

**Comment by Marmiz** [comment]
> Just wanted to point that out, since I saw the above response that stated both URLs would work.

@speesey were you on the main website (https://freecodecamp.com) or the beta version (beta website (http://beta.freecodecamp.com)?

Because so far only the Beta should allow both url to pass, while the live version still looks for the specific URL.
