### ISSUE TITLE
Beta challenge sequence problem.

### ISSUE THREAD

**Issue by spieg** [freeCodeCamp/freeCodeCamp#14949]
Challenge [title-case-a-sentence](http://beta.freecodecamp.com/en/challenges/basic-algorithm-scripting/title-case-a-sentence) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

In the "basic algorithm scripting"sequence of the beta course, there is in between "Tile Case a Sentence" and "Falsy Bouncer", the first page of "object oriented programming". Seems totally out of place, and Ctrl-enter will not take you to "Falsy Bouncer" but to "Object Oriented Programming: Create a Basic JavaScript Object"
 
![image](https://cloud.githubusercontent.com/assets/24204953/26246724/dac44e98-3c9a-11e7-8b01-e4d58a40d542.png)

**Comment by jonathanihm** [comment]
Looking in the code base, Slice and Splice challenge should be here.  It is marked true for beta, and I am looking a little into it.

**Comment by jonathanihm** [comment]
![image](https://cloud.githubusercontent.com/assets/6002459/26264084/220ef73e-3ca1-11e7-8567-1fe9dd697c2c.png)

**Comment by jonathanihm** [comment]
Upon further research, it seems that this affects beta challenges.  Both current beta challenges do not appear properly, which may be related to the isBeta boolean on the object.

**Comment by systimotic** [comment]
Thanks for reporting and looking into this issue! This was recently doubly fixed (https://github.com/freeCodeCamp/freeCodeCamp/pull/12989), so I'm closing this issue.

Happy coding!
