### ISSUE TITLE
Beta Suggestion: do - while loop

### ISSUE THREAD

**Issue by spieg** [freeCodeCamp/freeCodeCamp#14948]
Challenge [iterate-with-javascript-while-loops](http://beta.freecodecamp.com/en/challenges/basic-javascript/iterate-with-javascript-while-loops) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Since the loop mechanism is taught differently, this seems to be a great place to teach the do while loop.

**Comment by quatridunull** [comment]
I'll work on this!
