### ISSUE TITLE
Understanding Uninitialized Variables

### ISSUE THREAD

**Issue by jtte1** [freeCodeCamp/freeCodeCamp#14951]
Challenge [Understanding Uninitialized Variables](https://www.freecodecamp.com/challenges/understanding-uninitialized-variables#?solution=%0A%2F%2F%20Initialize%20these%20three%20variables%0Avar%20a%3B%0Avar%20b%3B%0Avar%20c%3B%0A%0A%2F%2F%20Do%20not%20change%20code%20below%20this%20line%0A%0Aa%20%3D%20a%20%2B%201%3B%0Ab%20%3D%20b%20%2B%205%3B%0Ac%20%3D%20c%20%2B%20%22%20String!%22%3B%0A%0Avar%20a%20%3D%206%3B%0Avar%20b%20%3D%2015%3B%0Avar%20c%20%3D%20%22I%20am%20a%20String!%22%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Initialize these three variables
var a;
var b;
var c;

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";

var a = 6;
var b = 15;
var c = "I am a String!";
```

the instructions do not match what the code should be.

**Comment by jonathanihm** [comment]
Hi,

If you have a suggestion on if we should change the wording, please feel free to make a suggestion!  If you are stuck, then you should be initializing your variables (changing the first three lines so that they are not undefined).

**Comment by BerkeleyTrue** [comment]
@jonathanihm Thanks

@jtte1  Happy Coding!
