### ISSUE TITLE
Add donate page to staging

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#14959]
We currently have a donate button on the production website in place of the link to the shop.

Change the button in the nav bar that currently points to the shop to instead point to https://www.freecodecamp.com/donate/

**Comment by Crizzooo** [comment]
Could I take a loot at this?

**Comment by BerkeleyTrue** [comment]
@Crizzooo Thanks but there is already a PR open for this issue.
