### ISSUE TITLE
dont know to continue

### ISSUE THREAD

**Issue by faithto** [freeCodeCamp/freeCodeCamp#14953]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20h2%20%7Bcolor%3A%20%0A%20%20%20%20red%3B%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  h2 {color: 
    red;}
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by jonathanihm** [comment]
Hi there,

This doesn't seem to be a bug.  If you are stuck, please feel free to ask for help in the freeCodeCamp chatroom: https://gitter.im/FreeCodeCamp/FreeCodeCamp

You will need to do something similar to how the example is making the h2 contents red.
