### ISSUE TITLE
Clarify the short form usage

### ISSUE THREAD

**Issue by Spaum145** [freeCodeCamp/freeCodeCamp#14950]
#### Challenge Name

Sift through Text with Regular Expressions

#### Issue Description

Propose to extend theory part. 
It was unclear for me as a js newbie, why regexp is not surrounded with quotes, whereas in many languages it is usually represented with a string. Is it some diffirent value type or what? After a while I found a topic with description about that.

#### Your Code

```js
new RegExp("and", "gi"); // is full form of /and/gi
```
so that part inside / / corresponds to regular expression itself and part after / / is optional and represents a list of flags

**Comment by jonathanihm** [comment]
Hi,

I can see how that would confuse newbies.  The challenge itself isn't using the regexp constructor and only dealing with a literal.  I propose we can link to documentation like :

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

Also, maybe change the wording to include that with a regexp, what we are looking for is always in-between two slashes?

**Comment by Spaum145** [comment]
> part inside / / corresponds to regular expression itself and part after / / is optional and represents a list of flags
Isn't it a sufficient wording?
Yep, a link to documentation is surely helpful and may be enough
