### ISSUE TITLE
it should work with the dot.?

### ISSUE THREAD

**Issue by erevos-13** [freeCodeCamp/freeCodeCamp#14957]
Challenge [Testing Objects for Properties](https://www.freecodecamp.com/challenges/testing-objects-for-properties#?solution=%0A%2F%2F%20Setup%0Avar%20myObj%20%3D%20%7B%0A%20%20gift%3A%20%22pony%22%2C%0A%20%20pet%3A%20%22kitten%22%2C%0A%20%20bed%3A%20%22sleigh%22%0A%7D%3B%0A%0Afunction%20checkObj(checkProp)%20%7B%0A%20%20%2F%2F%20Your%20Code%20Here%0A%20%20if(myObj.hasOwnProperty(checkProp)%20%3D%3D%3D%20true%20)%7B%0A%20%20%20%20%20result%20%3D%20myObj%5BcheckProp%5D%3B%0A%20%20%20%20return%20result%3B%0A%20%20%7Delse%7B%0A%20%20%20%20return%20%22Not%20Found%22%3B%0A%7D%0A%20%20%0A%20%20return%20%22Change%20Me!%22%3B%0A%7D%0A%0A%2F%2F%20Test%20your%20code%20by%20modifying%20these%20values%0AcheckObj(%22pet%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.110 Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  if(myObj.hasOwnProperty(checkProp) === true ){
     result = myObj.checkProp; // myObj[checkProp];
    return result;
  }else{
    return "Not Found";
}
  
  return "Change Me!";
}

// Test your code by modifying these values
checkObj("pet");



### info ###
in the 
result = myObj[checkProp];
it is the correct to use an the dot "." ?
result = myObj.checkProp; 
in my code it not pass that as correct.
i need to put brackets.  

```

**Comment by MiloATH** [comment]
You need to use myObj[checkProp].
Also, please only post in the issues section after trying to get help from the [gitter chat](https://gitter.im/FreeCodeCamp/HelpJavaScript).

**Comment by erevos-13** [comment]
@BerkeleyTrue thank you for your time.
I only would like to now if is correct to use the dot and if yes why they do not pass it.

**Comment by MiloATH** [comment]
Using the dot is incorrect. See http://stackoverflow.com/questions/4968406/javascript-property-access-dot-notation-vs-brackets
