### ISSUE TITLE
Sum of Fibonacci Numbers

### ISSUE THREAD

**Issue by hailea** [freeCodeCamp/freeCodeCamp#14952]
Intermediate Algorithm Scripting:
Sum All Odd Fibonacci Numbers Assignment
In the tests it says the sumFibs(75025) should return 13572. But the following are the Fibonnaci odd numbers and it returns 60696.
[1, 1, 3, 5, 13, 21, 55, 89, 233, 377, 987, 1597, 4181, 6765, 17711, 28657]
 60696
Did I miss something?

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by jonathanihm** [comment]
Please post your code and also ask for help in the chatroom: https://gitter.im/FreeCodeCamp/FreeCodeCamp

If it's not a bug and just needs change to code, then the people there can help!

**Comment by BerkeleyTrue** [comment]
@jonathanihm Thanks

@hailea Happy Coding!
