### ISSUE TITLE
zoom problem

### ISSUE THREAD

**Issue by DivyaM23** [freeCodeCamp/freeCodeCamp#14969]
Challenge [Change the Font Size of an Element] I do not know why I am still getting zoom error when I have my zoom at 100 as they specified. 👎 
```
<style>
  .red-text {
    color: red;
  }
p{
    font-size: 16 px;
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by texas2010** [comment]
@DivyaM23 
Thanks for reporting this. But you got typo.  you almost get it
GitHub Issues are for reporting bugs on the website only. 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
