### ISSUE TITLE
parent body missing

### ISSUE THREAD

**Issue by eaglecookie** [FreeCodeCamp/FreeCodeCamp#1496]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue.

The explanation states:
For example, your "jQuery Playground" h3 element has the parent element of <div class='container-fluid'>, which itself has the parent body.

HOWEVER, there is no body element in the code.

**Comment by benschenker** [comment]
Closing as stale
