### ISSUE TITLE
Cloud9 integration does not work properly with GitHub challenge on FreeCode Camp

### ISSUE THREAD

**Issue by mcne65** [freeCodeCamp/freeCodeCamp#14962]
Challenge [Manage Packages with npm](https://www.freecodecamp.com/challenges/manage-packages-with-npm) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Make sure that this is error does not occur again. I cannot read these following links as of yet properly.
![githubcloud9issue](https://cloud.githubusercontent.com/assets/13967481/26272842/0b078158-3d66-11e7-8aa5-40ad99d30fd9.JPG)

**Comment by raisedadead** [comment]
Unfortunately, this is beyond our control, and you would have to change the syntax highlighting and/or the UI theme from C9 settings.

Reference can be found here:
https://docs.c9.io/docs/syntax-highlighting-themes
