### ISSUE TITLE
Minor text/ content error

### ISSUE THREAD

**Issue by satenndrra** [freeCodeCamp/freeCodeCamp#14967]
Challenge [learn-how-script-tags-and-document-ready-work](http://beta.freecodecamp.com/en/challenges/jquery/learn-how-script-tags-and-document-ready-work) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.

**Issue Description**
Remnant text (probably from freecodecamp v1.0 where JQuery comes prior to Javascript) in bold italics could be removed. Just a minor correction, as Javascript is now introduced prior to JQuery.  Quoting from the 1st content paragraph - 

*Now we're ready to learn jQuery, the most popular JavaScript tool of all time.* ***Don't worry about JavaScript itself - we will cover it soon.***

**Comment by jhowerin** [comment]
First timer here - I'll take this if ok...

**Comment by jhowerin** [comment]
FYI : I followed the FCC contributing process and submitted a pull request.

**Comment by satenndrra** [comment]
@jhowerin Thank you!
