### ISSUE TITLE
Timestamp Microservice 

### ISSUE THREAD

**Issue by UtkarshGupta-CS** [freeCodeCamp/freeCodeCamp#14963]
#### Challenge Name

https://www.freecodecamp.com/challenges/timestamp-microservice

#### Issue Description

Everything works perfect in example project provided by FCC but for the input `30December06`
it gives unix timestamp for `1970-01-14T12:17:16.800Z` . I attached the Screenshots for the same.

#### Browser Information

* Browser Name, Version: Safari (Version 10.1 (12603.1.30.0.34))
* Operating System: macOs Sierra
*  laptop

#### Screenshot

![screen shot 2017-05-20 at 10 29 22 am](https://cloud.githubusercontent.com/assets/20434874/26273156/949d8ce2-3d47-11e7-9e6f-b649d7a2e14b.jpg)
![screen shot 2017-05-20 at 10 29 43 am](https://cloud.githubusercontent.com/assets/20434874/26273155/949ac20a-3d47-11e7-9b62-9b95573db1ae.jpg)

**Comment by MiloATH** [comment]
Hi @UtkarshGupta-CS 

1167436800 is the time stamp for Saturday, December 30, 2006 12:00:00 AM.
1167436.8 is the time stamp for Wednesday, January 14, 1970 12:17:16.800 PM.
The example project is working as expected.

Here are some next steps that you should follow before we can help you with your query:

* Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
* Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](https://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT**:
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
