### ISSUE TITLE
form element

### ISSUE THREAD

**Issue by fjmclaro** [freeCodeCamp/freeCodeCamp#14977]
<form action="/submit-cat-photo">
<input type="text" placeholder="cat photo URL">
</form>

Im on lesson 35 and this is how ive nested the text input element. But it doesnt let me move on.

**Comment by texas2010** [comment]
@fjmclaro Did you go to freeCodeCamp chat room for ask help first?
if you didn't. please go there first.  [Help chat room](https://gitter.im/FreeCodeCamp/Help)

Happy Coding.
if still a problem. please come back this thread. tell us a what problem is.
