### ISSUE TITLE
convertToF doesn't work

### ISSUE THREAD

**Issue by juanangosto** [freeCodeCamp/freeCodeCamp#14978]
Challenge [Convert Celsius to Fahrenheit](https://www.freecodecamp.com/challenges/convert-celsius-to-fahrenheit#?solution=%0Afunction%20convertToF(celsius)%20%7B%0A%20%20var%20fahrenheit%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20farenheit%20%3D%20celsius%20*%209%20%2F%205%20%2B%2032%3B%0A%20%20%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20fahrenheit%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20inputs%20below%20to%20test%20your%20code%0AconvertToF(30)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function convertToF(celsius) {
  var fahrenheit;
  // Only change code below this line
  farenheit = celsius * 9 / 5 + 32;
  
  // Only change code above this line
  return fahrenheit;
}

// Change the inputs below to test your code
convertToF(30);

```

**Comment by indefinite0212** [comment]
hi @juanangosto 
something's wrong with your code, make sure to see if the variable name(fahrenheit) is the same.
you should ask first at [JavaScript help room](https://gitter.im/FreeCodeCamp/HelpJavaScript) before posting a git hub issue 
:)

**Comment by vish448** [comment]
Hi @juanangosto, I have ran the same code in you described above in both Chrome and safari. And i confirm that it works fine without any issue. 
Thanks

**Comment by Evan171** [comment]
You did a silly mistake.Change the farenhiet to fahrenheit. All the best
