### ISSUE TITLE
FCC Roman Numeral Converter Bug

### ISSUE THREAD

**Issue by Derplicity** [freeCodeCamp/freeCodeCamp#14985]
Challenge [Roman Numeral Converter](https://www.freecodecamp.com/challenges/roman-numeral-converter) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
<img width="515" alt="screen shot 2017-05-21 at 12 20 45 pm" src="https://cloud.githubusercontent.com/assets/24903093/26287421/5a92ae3c-3e38-11e7-964f-3f0a1d746706.png">

The page crashed while I was trying to figure out the code, tried to reload it and now it freezes every time. I assume that the code runs every time I reload it and that an infinite loop causes the browser to freeze. All I need is to somehow reset the challenge so I can start over.

Thanks in advance.

**Comment by robertspurlin** [comment]
In the URL of the challenge is where the code is stored. Try opening up this link (https://www.freecodecamp.com/challenges/roman-numeral-converter#?solution=%0Afunction%20convertToRoman(num)%20%7B), fixing the problems that the jshint points out for you (in my browser, it is showing that the bracket for the function is not closed), and call the function with the test that is given (convertToRoman(36)). 

Then, you should be able to run the tests and save it from there. I have had it freeze in the middle of debugging and this is the way I get around it to "reset".

**Comment by Derplicity** [comment]
@robertspurlin That fixed it. Thank you so much!
