### ISSUE TITLE
Using dot for accessing my object doesn't pass the test.

### ISSUE THREAD

**Issue by Balanced02** [freeCodeCamp/freeCodeCamp#14980]
Challenge [Testing Objects for Properties](https://www.freecodecamp.com/challenges/testing-objects-for-properties#?solution=%0A%2F%2F%20Setup%0Avar%20myObj%20%3D%20%7B%0A%20%20gift%3A%20%22pony%22%2C%0A%20%20pet%3A%20%22kitten%22%2C%0A%20%20bed%3A%20%22sleigh%22%0A%7D%3B%0A%0Afunction%20checkObj(checkProp)%20%7B%0A%20%20%2F%2F%20Your%20Code%20Here%0A%20%20var%20answer%3B%0A%20%20switch%20(checkProp)%20%7B%0A%20%20%20%20case%20%22gift%22%3A%0A%20%20%20%20case%20%22pet%22%3A%0A%20%20%20%20case%20%22bed%22%3A%0A%20%20%20%20%20%20answer%20%3D%20myObj.checkProp%3B%20break%3B%0A%20%20%20%20default%3A%20answer%20%3D%20%22Not%20Found%22%3B%0A%20%20%7D%0A%20%20return%20answer%3B%0A%7D%0A%2F%2F%20Test%20your%20code%20by%20modifying%20these%20values%0AcheckObj(%22gift%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  var answer;
  switch (checkProp) {
    case "gift":
    case "pet":
    case "bed":
      answer = myObj.checkProp; break; //This doesnt pass the test, except replaced with **answer = myObj[checkProp]; break;**
    default: answer = "Not Found";
  }
  return answer;
}
// Test your code by modifying these values
checkObj("gift");

```

**Comment by jonathanihm** [comment]
Hi @Balanced02,

You are correct, you cannot access a property like above.  Please see: 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

To access a property using bracket notation, you cannot access property with dot notation with a string.

Cheers!

**Comment by Balanced02** [comment]
Thanks for the clarification... I never knew before @jonathanihm
