### ISSUE TITLE
Cannot pass Tests with correct code, code only runs upon page refresh.

### ISSUE THREAD

**Issue by nestorst** [freeCodeCamp/freeCodeCamp#14984]
Challenge [update-the-height-of-an-element-dynamically](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/update-the-height-of-an-element-dynamically) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Code can never be submitted though correct (reproduced Opera & Chrome):
1. First submit attempt (CMD+ENTER) > 3/10 bars pass height requirements
![image](https://cloud.githubusercontent.com/assets/26751266/26287232/5b2937d4-3e34-11e7-8952-10f9ec297d25.png)
2. Second submit attempt > Error "Identifier 'dataset' has already been declared" #[14042](https://github.com/freeCodeCamp/freeCodeCamp/issues/14042)
3. Refresh page > Code runs and right pane visualization updates with correct div heights
![image](https://cloud.githubusercontent.com/assets/26751266/26287247/d5038442-3e34-11e7-95ba-5df9cb491125.png)
4. Third submit attempt > back to first submission attempt's output 

Submission Attempt's Code:
```html


<style>
  .bar {
    width: 25px;
    height: 100px;
    display: inline-block;
    background-color: blue;
  }
</style>
<body>
  <script>
    const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
    
    d3.select("body").selectAll("div")
      .data(dataset)
      .enter()
      .append("div")
      .attr("class", "bar")
      // Add your code below this line

      .style('height', (d) => d + 'px');
      
      // Add your code above this line
  </script>
</body>

```

**Comment by nestorst** [comment]
Same issue on next challenge [Change the Presentation of a Bar Chart](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/change-the-presentation-of-a-bar-chart).

**Comment by lynxlynxlynx** [comment]
See #15024, where the general problem is being tackled (even though it's a newer report).

**Comment by systimotic** [comment]
Hi! Thanks for reporting and looking into this issue.

This is a known issue. We're working on resolving it through #12762. I'm closing this as a duplicate.

Happy coding!
