### ISSUE TITLE
Accessing Objects Properties with Variables: clarify properties naming.

### ISSUE THREAD

**Issue by RickSanch3z** [freeCodeCamp/freeCodeCamp#14988]
#### Challenge Name

https://www.freecodecamp.com/challenges/accessing-objects-properties-with-variables

#### Issue Description

It's not an issue by itself. Just want to clarify that example given maybe not the best. Here we can see that properties name contain only digits. But if we try to name those properties with only 1 digit we'll get errors: `Object [ <1 empty slot>, "Namath", <8 empty slots>, 10 more… ]`

#### Browser Information

* Browser Name, Version: Firefox
* Operating System: Windows 7 (64)
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code

```js
var testObj = {
  12: "Namath",
  16: "Montana",
  19: "Unitas"
};


```

**Comment by huyenltnguyen** [comment]
I don't have any problem with 1 digit here.
![screenshot](https://cloud.githubusercontent.com/assets/25715018/26322972/683d5ed6-3f57-11e7-9c38-1337f30e671a.png)

**Comment by RickSanch3z** [comment]
Hi,
Run your code in Firefox console and observe the result.
Thanks.

**Comment by texas2010** [comment]
@RickSanch3z is this solved a problem?
