### ISSUE TITLE
Hex code not working!

### ISSUE THREAD

**Issue by Julian0925** [freeCodeCamp/freeCodeCamp#14983]
NOT WORKING! THE HEX CODE FOR DODGER BLUE IS #1e90ff BUT IT SAYS IT'S INCORRECT! PLEASE HELP! I'M STUCK!

**Comment by texas2010** [comment]
@Julian0925 what challenge name? Please show full code.

**Comment by Julian0925** [comment]
Use Hex Code to Mix Colors

**Comment by Julian0925** [comment]
<style>
  .red-text {
    color: #ff0000;
  }
  .green-text {
    color: #00ff00;
  }
  .dodgerblue-text {
    color: #1e90ff;
  }
  .orange-text {
    color: #ffa500;
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="green-text">I am green!</h1>

<h1 class="dodgerblue-text">I am dodger blue!</h1>

<h1 class="orange-text">I am orange!</h1>

**Comment by Julian0925** [comment]
Want a picture?

**Comment by Julian0925** [comment]
I need help! Anyone?

**Comment by texas2010** [comment]
please hold on. let me checking it.

**Comment by Julian0925** [comment]
ok thanks

**Comment by Julian0925** [comment]
the hex code for dodger blue is #1E90FF

**Comment by texas2010** [comment]
i could see a problem. it suppose to be dodger-blue-text.

**Comment by Julian0925** [comment]
oh nvm the hex code you guys provided for the dodger blue text is different the what is says online. I would suggest you guys change the hex to #1E90FF so it doesn't confuse people.

**Comment by texas2010** [comment]
@Julian0925 they did fixed it in beta site.

**Comment by Julian0925** [comment]
well not for me, lol

**Comment by texas2010** [comment]
no.  freecodecamp.com is not a beta.  they didnt released new challenges in fcc site.

you need to use this code.
  .dodger-blue-text {
    color: #2998E4;
  }  

happy coding

**Comment by Julian0925** [comment]
ok got it!
