### ISSUE TITLE
Can't move on to next challenge

### ISSUE THREAD

**Issue by eaglecookie** [FreeCodeCamp/freecodecamp#1498]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. 

I entered what I believe to be the correct code that appears to have changed all the right well children to green:
$('#right-well').children().css('color', 'green');

HOWEVER, none of the RED X's turn to GREEN CHECKS, so I can't continue to the next challenge.

Also, I'm nervous that (in my attempt to be helpful) I'm reporting issues that are already known, even though my searches come back empty. I sincerely apologize if this is the case, and I will stop reporting my problems asap. Please just let me know. Thanks!

**Comment by kurzninja** [comment]
Your code was correct, the test had the wrong RGB value (it was testing for blue, not green).
I have corrected this here: https://github.com/FreeCodeCamp/freecodecamp/pull/1706
