### ISSUE TITLE
Conflicting Challenge Request

### ISSUE THREAD

**Issue by eaglecookie** [FreeCodeCamp/freecodecamp#1499]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue. 

The challenge asks you to make the first buttons in each well bounce, but the RED X asks you to make the second buttons in each well bounce and only turns green after making the second buttons bounce.

**Comment by benflinn** [comment]
submitted a fix for this:

https://github.com/benflinn/freecodecamp/commit/87c4afcff5608b34ec086eb19437bb8dbcf1afe4

**Comment by QuincyLarson** [comment]
Thanks again for reporting this, @eaglecookie, and for fixing this, @benflinn!
