### ISSUE TITLE
Will not recognize I have completed the intructions. 

### ISSUE THREAD

**Issue by mgarry55** [freeCodeCamp/freeCodeCamp#14994]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!--
<h1>Hello World</h1>
-->
<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>


```

**Comment by huyenltnguyen** [comment]
Hi @mgarry55!
The challenge asks you to comment out both `h1` and `p` while you've only done it for the `h1`.

**Comment by texas2010** [comment]
@mgarry55, Thanks for reporting this. But you didn't finish your challenge. you forget to do another task.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
