### ISSUE TITLE
border and image size not showing up 

### ISSUE THREAD

**Issue by cwest21** [freeCodeCamp/freeCodeCamp#14991]
#### Challenge Name

https://www.freecodecamp.com/challenges/size-your-images
https://www.freecodecamp.com/challenges/add-borders-around-your-elements

#### Issue Description

When I code for the image size it didn't show up even though I was 100% zoom on my browser. 
I tried skipping to the next one with the border and the image size showed up but I couldn't get the border to work and I believe my code is correct.

#### Browser Information

I am doing this one google chrome on a laptop.

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
![image](https://cloud.githubusercontent.com/assets/28853373/26291392/8e03fd80-3e73-11e7-9e09-7af502f7a2db.png)

**Comment by aaronwi** [comment]
Try using the gitter chat, this is for issues with the freecodecamp site itself. You forgot a `;` (semicolon) after `border-style:solid`

**Comment by texas2010** [comment]
@cwest21 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by haze1995** [comment]
put a space after smaller image in line 29 and type thick-green-border
