### ISSUE TITLE
Why not able to submit the below challenge despite the code works perfeectly?

### ISSUE THREAD

**Issue by NawasNaziru** [freeCodeCamp/freeCodeCamp#14997]
Challenge [Reverse a String](https://www.freecodecamp.com/challenges/reverse-a-string#?solution=%0Afunction%20reverseString(str)%20%7B%0A%20%20arr%3Dstr.split('')%3B%0A%20%20x%3D%22%5C%22%22%3B%0A%20%20arr.push(x)%3B%0A%20%20arr.unshift(x)%3B%0A%20%20arr.reverse()%3B%0A%20%20str%3Darr.join('')%3B%0A%20%20%0A%20%20return%20str%3B%0A%7D%0A%0AreverseString()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36 OPR/36.2.2126.102826</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function reverseString(str) {
  arr=str.split('');
  x="\"";
  arr.push(x);
  arr.unshift(x);
  arr.reverse();
  str=arr.join('');
  
  return str;
}

reverseString("Greetings from Earth");

```
There is nothing wrong with the program above for reversing a string;it works perfectly. The problem i think is with the freecodecamp site which is unable to submit the codes so that i move to the next chalenge

**Comment by huyenltnguyen** [comment]
Hi @NawasNaziru! You added an extra pair of double quotes to your string, which made it incorrect.
Here is a quick fix: remove `\"` from the line `x="\""`.

**Comment by NawasNaziru** [comment]
I added the pair of double quotes to be able to have the function
return a string under double quotes as the answer as required by the
challenge

**Comment by NawasNaziru** [comment]
I added the pair of double quotes to be able to have the function
return a string under double quotes as the answer as required by the
challenge
Thanks for your assistance.
Nawas Nazir

**Comment by huyenltnguyen** [comment]
@NawasNaziru I think you're confused by the instruction. The double quotes in it just to tells you the result must be a string, not something else.
This challenge's test cases are just text, but what if I pass a string that contains only numbers, say `"123"`, to the function. If the instruction didn't have the double quotes around the answer (which would be `"321"`), then what data type would you think you should return, the **number** `321` wouldn't it?
Hope this explanation helps.

**Comment by NawasNaziru** [comment]
I got it!
Thanks a lot

**Comment by huyenltnguyen** [comment]
@NawasNaziru Glad I can help. Please close the issue if things work for you now.

**Comment by erictleung** [comment]
Closing as resolved. Happy coding!
