### ISSUE TITLE
My solution matches the assertion test  function  and therefore should pass the test

### ISSUE THREAD

**Issue by Markus1607** [freeCodeCamp/freeCodeCamp#14996]
Challenge [understand-the-differences-between-import-and-require](https://beta.freecodecamp.com/en/challenges/es6/understand-the-differences-between-import-and-require) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


import { capitalizeString } from "string_functions";

capitalizeString("hello!");

```

**Comment by ginhton** [comment]
Chromium 56.0.2924.76 Built on Ubuntu, running on Ubuntu 17.04
Just copy the code above and run the test.
I get the following output:
![image](https://cloud.githubusercontent.com/assets/17196141/26412114/43eb8df8-40da-11e7-82c7-4d2212662ad6.png)
I hope this can help.

**Comment by systimotic** [comment]
Hi! Thanks for reporting this issue.
The ES6 section's test do not work yet. This is a known issue we're working on resolving. See https://github.com/freeCodeCamp/freeCodeCamp/issues/12698 for more.

Happy coding!
