### ISSUE TITLE
Email Password Reset Form Not Working

### ISSUE THREAD

**Issue by lui8906** [FreeCodeCamp/freecodecamp#15]
Password form button does not respond to click. Additionally the jumbotron div that is meant to have a white background for the form is too short (only approx 96px and form is 317px).

**Comment by terakilobyte** [comment]
Lui8906 can you confirm the issue is resolved so we can close it?

**Comment by lui8906** [comment]
Still when I am at the reset form after recieving the email and following the link, I put in a matching password and the button does not do anything or provide any feedback, are there password requirements? etc..

**Comment by terakilobyte** [comment]
Ok, thanks. To confirm, this is on password reset, after requesting to reset password? I'll look into it, thanks.

**Comment by lui8906** [comment]
Yep

**Comment by FreeCodeCamp** [comment]
We've fixed this with our recent pull request.
