### ISSUE TITLE
Counting Cards has a bug

### ISSUE THREAD

**Issue by Avneet08** [freeCodeCamp/freeCodeCamp#15009]
![screenshot 52](https://cloud.githubusercontent.com/assets/23396567/26335102/542d412e-3f87-11e7-8f8c-a52a40607c87.png)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
var count = 0;

function cc(card) {
  // Only change code below this line
 if(card>1&&card<=6){
   count++;

 } 
  else if(card>6&&card<=9){
    count+=0;
  }
  else if(card===10||'J'||'K'||'Q'||'A'){
    count--;
  }
  else{
    return "Change Me";
  }
  if(count>0){
    return   "\""+count+" Bet\"";
  }
  else{
    return "\""+count+" Hold\"";
  }


  // Only change code above this line
}
// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc('J'); cc(9); cc(2); cc(7);


```

**Comment by OFFLlNE** [comment]
@Avneet08 Thank you for reporting the issue.

Could you please describe what kind of a bug are you experiencing?

**Comment by huyenltnguyen** [comment]
Hi @Avneet08! You got the same issue as #15015. This is not a bug. Please refer to #14997 for explanation and solution.

**Comment by erictleung** [comment]
@Avneet08 you're almost there. You don't need the extra set of double quotes there. Happy coding!
