### ISSUE TITLE
a true issue 

### ISSUE THREAD

**Issue by stewartburns** [freeCodeCamp/freeCodeCamp#15004]
Challenge [create-a-form-element](https://beta.freecodecamp.com/en/challenges/basic-html-and-html5/create-a-form-element) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form <input type="text" action="/submit-cat-photo"> </form>
<main

```

**Comment by huyenltnguyen** [comment]
@stewartburns Your opening form tag is missing the right angle bracket `>`.

**Comment by texas2010** [comment]
@stewartburns 
Thanks for reporting this. But your code is incorrect.
GitHub Issues are for reporting bugs on the website only. 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by Ninajl** [comment]
I believe it is buggy.
Here is my code:
<form action="/submit-cat-photo"> 
  <input type="text" placeholder="cat photo URL">
</form>
and it is not letting me pass this lesson.
I am assuming this is still an issue?

**Comment by Ninajl** [comment]
''
<form action="/submit-cat-photo"> 
  <input type="text" placeholder="cat photo URL">
</form>
''
