### ISSUE TITLE
odd vs even

### ISSUE THREAD

**Issue by eaglecookie** [FreeCodeCamp/FreeCodeCamp#1500]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-even-numbered-elements-using-jquery has an issue. 

"So what a human would consider odd numbers: 1, 3, 5, 7 - a computer would actually consider odd numbers."

A computer would actually consider them EVEN numbers, right?

Also, I'm not sure if this is a misunderstanding on my part, but when I complete the challenge, target1 and target5 shake in the left well, while target6 shakes in the right well. Shouldn't only odd numbers (even to the computer) shake? Or is the position of the buttons what determines whether something is odd or even?

**Comment by ALINATSUI** [comment]
Hi, 
I just completed this challenge myself. 1,3,5,7 are odd numbers and should be considered as such. What's your code for this challenge?

**Comment by eaglecookie** [comment]
I used:
$('.target:even').addClass('animated shake');

Oddly enough, if I accidentally make the semicolon a colon, it changes the names of the buttons to targets1-3 in the left well and targets 4-6 in the right well. But none of them shake.

**Comment by eaglecookie** [comment]
And wouldn't 1, 3, 5, 7 be considered even numbers, since 0 is technically 1? Or am I just misunderstanding that too?
Thanks @ALINATSUI !

**Comment by rodrigomb81** [comment]
Hi, I just gave that challenge a try and you are right @eaglecookie ; the second "odd" in that sentence ("So what[...]") should be "even".

Regarding your second point, $('.target:even') selects all the elements that have an even numbered index from the array of elements that have the "target" class. In this case the array of elements that have said class contains 6 elements (the buttons). If you were to select, from that array, the elements with even numberd indexes you'd select the first element (which has index 0), the third (with index 2) and the fifth one (with index 4).

Hope that helps clear things up

**Comment by eaglecookie** [comment]
@rodrigomb81 That makes sense. Thanks!

**Comment by BerkeleyTrue** [comment]
Yeah this is not correct. Odds are odds. This will be updated.

**Comment by benschenker** [comment]
Closing as stale
