### ISSUE TITLE
 [Concatenating Strings with Plus Operator]

### ISSUE THREAD

**Issue by jdavonte916** [freeCodeCamp/freeCodeCamp#15006]
Challenge [Concatenating Strings with Plus Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator#?solution=%0A%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%20%2B%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20%22This%20is%20the%20start.%22%20%20%2B%20%20%22This%20is%20the%20end.%22%3B%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr = "This is the start."  +  "This is the end.";



```

**Comment by huyenltnguyen** [comment]
Hi @jdavonte916! You're missing the space at the end of the first string.
What you should return: `This is the start. This is the end.`
What your code returns: `This is the start.This is the end.`

**Comment by texas2010** [comment]
@jdavonte916 
Thanks for reporting this. But you forget to add space like @huyenltnguyen say it.
GitHub Issues are for reporting bugs on the website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
