### ISSUE TITLE
Change the Font Size of an Element

### ISSUE THREAD

**Issue by TerryOdom** [freeCodeCamp/freeCodeCamp#15018]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element#?solution=%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```
The last task in the list "Between the style tags, give the p elements font-size of 16px. Browser and Text zoom should be at 100%." does not appear to be fixed.  

I updated my code and adjusted the zoom and still can't get it to work.  I used Chrome and IE with the same results.

**Comment by huyenltnguyen** [comment]
Hi @TerryOdom! The challenge asks you to change the font size of `p` elements, while here you're changing the font size of elements that have the class `.red-text`.

**Comment by mistwire** [comment]
Thanks for the clarification, I had the same issue :-)  The wording of the task is a little ambiguous :-)

**Comment by psk-69** [comment]
Hi i still didn't get it, can someone clarify?

**Comment by Fubinator** [comment]
Hey @psk-69 as @huyenltnguyen  said the task is to change the font-size of the` p`-element. The OP has changed the class `.red-text` to have a font-size of 16px. The problem is that the `h2`-element also has this class which causes the font-size of the `h2`-element to be 16px as well . This is not what the challenge asks you to do. Also, the second `p`-element does not have this class. 

To fix this, you have to create a 'p' selector in your `style` element with the font-size in it.
