### ISSUE TITLE
Your editor is creating problems sometimes!

### ISSUE THREAD

**Issue by arka97** [freeCodeCamp/freeCodeCamp#15014]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by jonathanihm** [comment]
You will need to elaborate on what issues you are experiencing and relevant information on what environment you are running FCC on.

**Comment by raisedadead** [comment]
Hi @arka97 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
