### ISSUE TITLE
Error: You should be using indexes to modify the values in myArray

### ISSUE THREAD

**Issue by ALINATSUI** [FreeCodeCamp/freecodecamp#1501]
Hello,
For this problem, I was able to pass one of the questions, but the error still persists. It appears that I did everything correctly. Attached is a screen-shot. 

![screen shot 2015-08-04 at 12 48 46 am](https://cloud.githubusercontent.com/assets/7786266/9053424/cde3582e-3a42-11e5-9d30-b5598246dd18.png)

Challenge http://beta.freecodecamp.com/challenges/modifying-data-with-indexes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by mistamadd001** [comment]
The error is not in the check but rather in the fact that you were able to move on to the next challenge, you are being asked to change only myArray[0] rather than overriding the whole array as you have

**Comment by benmcmahon100** [comment]
Yes the second test is to stop you from just re-writing the array. It's forcing you to use the bracket notation

**Comment by ALINATSUI** [comment]
I see where I went wrong...Sorry about that.
