### ISSUE TITLE
Using typeof console.log() bug

### ISSUE THREAD

**Issue by zyval** [freeCodeCamp/freeCodeCamp#15011]
#### Challenge Name

https://www.freecodecamp.com/challenges/using-typeof

#### Issue Description

Challenge Console not showing output from console.log(), output showing in the browser's console

#### Browser Information

* Browser Name, Version: Firefox 53.0.2 (32-bit)
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

console.log(typeof "");

console.log(typeof 0);

console.log(typeof []);

console.log(typeof {});

#### Screenshot

![freecodecamp_console_log_bug](https://cloud.githubusercontent.com/assets/17099684/26350762/679b6892-3fac-11e7-9f90-dcda323a2796.jpg)

**Comment by BerkeleyTrue** [comment]
![using_typeof___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/26361928/57d2bcc8-3f91-11e7-9f24-d8580d877513.png)

Per the description in the output field, console log's will be printed in the browsers dev tools. 

Happy Coding
