### ISSUE TITLE
waypoint-apply-the-default-bootstrap-button-style – test checking for "btn-default" class passes after only adding class "btn".

### ISSUE THREAD

**Issue by 1hella** [FreeCodeCamp/FreeCodeCamp#1502]
Challenge http://beta.freecodecamp.com/challenges/waypoint-apply-the-default-bootstrap-button-style has an issue. 

The test, 'Apply the "btn-default" class to each of your button elements.' passes after only adding the "btn" class.

![image](https://cloud.githubusercontent.com/assets/6580703/9053827/33b65a20-3a2f-11e5-97d3-da8415e0cd78.png)

**Comment by 1hella** [comment]
My bad didn't mean to close it.

**Comment by flota113** [comment]
fixed with https://github.com/FreeCodeCamp/freecodecamp/commit/c9e0184387de6a8e0a6c9d940350629dcf5eacd6

**Comment by ilochi** [comment]
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
        <button class="btn"></button>
        <button class="btn"></button>
        <button class="btn"></button>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <button class="btn"></button>
        <button class="btn"></button>
        <button class="btn"></button>
      </div>
    </div>
  </div>
</div>
how can I successfully apply the btn-default class to each of my above button elements

**Comment by texas2010** [comment]
@ilochi, 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
