### ISSUE TITLE
Beta Applied Web Design Project Video Broken

### ISSUE THREAD

**Issue by knight2** [freeCodeCamp/freeCodeCamp#15029]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-tribute-page

#### Issue Description

Clicking on the video for the tribute page project on Beta website results in the video player saying - ean error occurred. Please try again. playback id jNl5tJy5xhDnzQlf

#### Browser Information

Tried on chrome (Version 58.0.3029.96 (64-bit)
and firefox using windows 10 desktop

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

N/A

```
#### Screenshot
<!-- Add a screenshot of your issue -->
http://imgur.com/a/OhruK

**Comment by MiloATH** [comment]
Confirmed. Should this video be [the same video as before?](https://www.youtube.com/watch?v=qqrnzmqCGDw) Those videos are slightly outdated, but are only a year old. The videos in other project challenges don't seem to work either.

**Comment by raisedadead** [comment]
We are removing them in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/12753
