### ISSUE TITLE
[beta] Hard Redirect Keyboard Shortcuts Not Working 

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/freeCodeCamp#15023]
On beta, the hard redirect shortcut keys from this file do not work:
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/client/sagas/mouse-trap-saga.js

Ex. 'g n w' should take you to https://forum.freecodecamp.com.

**Comment by jonathanihm** [comment]
![image](https://cloud.githubusercontent.com/assets/6002459/26420546/7a955d9a-4088-11e7-96b6-dec3d0af04d3.png)

**Comment by jonathanihm** [comment]
The pushState function must have a URL that is of the same origin, I cannot advise what the correct solution would be here.

**Comment by dhcodes** [comment]
Closing for now as this seems to be resolved in staging.
