### ISSUE TITLE
Waypoints 2 and 3 in Basic HTML5 and CSS pass after only adding the closing tags

### ISSUE THREAD

**Issue by ariadna-m** [FreeCodeCamp/FreeCodeCamp#1503]
Waypoints 2 and 3 ( http://www.freecodecamp.com/challenges/waypoint-inform-with-the-paragraph-element ) in Basic HTML5 and CSS pass after only adding the closing tags for h2 and p elements respectively, without requiring the actual text "CatPhotoApp" and "Hello Paragraph" to be written between the tags.

The tests bellow the next challenge button indicate correctly that these are missing, but the "Go to my next Challenge" button is active and allows progression to the next chalenge.

Have a nice day and good luck fixing this. :)

**Comment by djordjelacmanovic** [comment]
I cannot reproduce this behavior. Provide screen cap perhaps?

To owners: has this been fixed and the issue not closed?

**Comment by ariadna-m** [comment]
![screenshot - 04 08 2015 - 20 33 48](https://cloud.githubusercontent.com/assets/5766265/9067847/94635288-3ae8-11e5-9af6-89e45813dc6e.png)
![screenshot - 04 08 2015 - 20 35 46](https://cloud.githubusercontent.com/assets/5766265/9067848/94637038-3ae8-11e5-93c7-59df1f6f9ab6.png)

This seems to be an issue for me in all of the Basic HTML5 and CSS waypoints so far.

The "Go to my next challenge" button activates too soon, before the last one or two conditions/tests for the lesson are fulfilled. As can be seen in the above screencaps from "Waypoint: Import a Google Font": I have not completed the font-family attribute, between the brackets, in the style section, for the h2 element, but the site allows me to move on, nevertheless.

I'm using a Firefox web browser on Linux: Fedora. Maybe it's something that only happens in Linux?

**Comment by lun471k** [comment]
You seem to have included your `link` element within your `style` element. It should be outside to begin with.  

Perhaps the interpreter/validator crashes because of this?

**Comment by ariadna-m** [comment]
Hello Jeff,

I don't think the validator crashes because of some code I write. It 
just seems to activate the "Go to the next challenge" button too soon, 
when you still have one or two tests left to pass. For example in the 
"Waypoint: Create a Set of Radio Buttons" it did not activate until 
there was only one test left, as can be seen from the screenshots 
attached. Here the code is as it should be, but the name attribute is 
missing.

Under Linux there have been many times that I have encountered sites 
that don't behave as they should, but I don't think this here is ok, as 
it lets lazy students pass without learning correctly.

Thank you for your input and have a nice day,
Ariadna

**Comment by BerkeleyTrue** [comment]
@ariadna-m Is this still an issue?
