### ISSUE TITLE
Red-flagged though I don't see errors in the code

### ISSUE THREAD

**Issue by luany37** [freeCodeCamp/freeCodeCamp#15034]
#### Challenge Name
https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements

#### Issue Description
I'm red-flagged for "color needs to be blue" and "need to have semicolon and closing brace". 

#### Browser Information

* Browser Name, Version: 
Google chrome
* Operating System: 
Android 7.0
* Mobile, Desktop, or Tablet: 
Mobile

#### Your Code
```html
<style>
  h2｛color: blue;｝
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by MiloATH** [comment]
You are using a different bracket character than most people use in the style. I use { and }. You are using｛ and ｝which are the Full width brackets. They look very similar, but are different characters. Here are the [Fullwidth bracket](http://www.fileformat.info/info/unicode/char/ff5b/index.htm) and [regular bracket](http://www.fileformat.info/info/unicode/char/007b/index.htm). Try using the regular brackets {}. 
Use `<style> h2{color:blue;} </style>` and not `<style> h2｛color: blue;｝ </style>`
This is true for all CSS in all browsers.

**Comment by luany37** [comment]
Got it. Thank you!
