### ISSUE TITLE
Oops! Something went wrong. Please try again later

### ISSUE THREAD

**Issue by dainamisk** [freeCodeCamp/freeCodeCamp#15038]
#### Issue Description

The error "Oops! Something went wrong. Please try again later" appears on screen when completing a challenge.

**Comment by aaronkyl** [comment]
Same issue here.

**Comment by erictleung** [comment]
@dainamisk thanks for the issue. [This issue should be resolved](https://twitter.com/freeCodeCamp/status/867480170722086912). If you're still having issues. Please comment back. Otherwise, I'll be closing this issue. Happy coding!
