### ISSUE TITLE
Replacing Heroku / C9.io instructions with Glitch.com instructions on production

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15044]
We no longer recommend using Heroku.com + C9.io for our back end projects. Both of them now require credit cards, and have limited resources.

Instead, we recommend Glitch.com. 

We need to update the instructions on our back end challenges to tell campers to use Glitch.com instead. Here's what these instructions look like on our beta branch:

![managing_packages_with_npm__how_to_use_package_json__the_core_of_any_node_js_project_or_npm_package___freecodecamp_](https://cloud.githubusercontent.com/assets/985197/26436688/dcc6f816-40dd-11e7-8ba8-336040d486d2.png)

Is anyone interested in branching off of backup/master and modifying the back end certificate's seed files to remove the references to Heroku and C9, and recommend Glitch.com instead?

**Comment by Masya120** [comment]
@QuincyLarson I'll do this one

**Comment by codemzy** [comment]
I can give this a go 😬

**Comment by texas2010** [comment]
It seems PR didn't close this issue.

do we need to close this? @raisedadead
