### ISSUE TITLE
The explanation is confusing

### ISSUE THREAD

**Issue by MANTENN** [freeCodeCamp/freeCodeCamp#15043]
#### Challenge Name

https://www.freecodecamp.com/challenges/sort-arrays-with-sort

#### Issue Description

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
This makes more sense.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by jonathanihm** [comment]
Hi,

Which part of the challenge explanation are you having difficulties with?  Do you have a suggestion on what can be changed?  Thanks!

**Comment by raisedadead** [comment]
Hi @MANTENN thanks a lot for the feedback, we would love to hear more about the specifics if any that were confusing or like so, so that we can enhance the instructions, etc.

Thanks for reporting.

**Comment by raisedadead** [comment]
@MANTENN Please revert back if you are still stuck with this.
