### ISSUE TITLE
Bug in Basic Algorithm Challenges:Where do I belong ?

### ISSUE THREAD

**Issue by heygema** [freeCodeCamp/freeCodeCamp#15047]
#### Challenge Name
https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=%0Afunction%20getIndexToIns(arr%2C%20num)%20%7B%0A%20%20%2F%2F%20Find%20my%20place%20in%20this%20sorted%20array.%0A%20%20var%20arr2%20%3D%20arr.push(3)%3B%0A%20%20return%20arr%3B%0A%7D%0A%0AgetIndexToIns(%5B40%2C%2060%5D%2C%2050)%3B%0A

#### Issue Description
The Issue is occurs when I push value in new array. And when I return the prior array, it instead returning the result of the new array (with the added value);

#### Browser Information
Chrome Browser, Ubuntu.

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code
```
function getIndexToIns(arr, num) {
  // Find my place in this sorted array.
  var arr2 = arr.push(3);
  return arr;
}

getIndexToIns([40, 60], 50);
```

it returns [40, 60, 50]
it should be [40, 50]

**Comment by jonathanihm** [comment]
Hi there,

I believe the challenge is asking you to sort and find an index, not return a new array.  You should be returning an index value.  When you push a value to an array, you are adding to it and not replacing a value.  Hope that helps!  Cheers!

**Comment by raisedadead** [comment]
Hi @heygema 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by raisedadead** [comment]
@jonathanihm thanks a lot for your comments, we sincerely appreciate your help. IMHO you should simply direct code assistance to the forums and chat rooms as you have correctly done without providing any hints and assistance in the tracker.
