### ISSUE TITLE
Create static 404/500/502 pages

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#1504]
Since we will be using NGINX between the world and our servers in the near future, I think it would be awesome for someone to come up with cool camping themed static pages to be shown when something goes wrong with our servers.

Any takers?

These would just be simple html/css pages with images.

for inspiration:
http://www.creativebloq.com/web-design/best-404-pages-812505
https://github.com/500

cc @Rybar :)

**Comment by mikestratton** [comment]
How about an animated fire that display's over your the campfire portion of your logo?

**Comment by BerkeleyTrue** [comment]
Ok, two 404's but no 500s?

**Comment by BerkeleyTrue** [comment]
Done
