### ISSUE TITLE
 the problem is in the assignment illustration and info.

### ISSUE THREAD

**Issue by rocnogu** [freeCodeCamp/freeCodeCamp#15049]
Challenge [Use the Bootstrap Grid to Put Elements Side By Side](https://www.freecodecamp.com/challenges/use-the-bootstrap-grid-to-put-elements-side-by-side) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

""Note that in this illustration, the col-md-* class is being used. Here, md means medium, and * is a number specifying how many columns wide the element should be. In this case, the column width of an element on a medium-sized screen, such as a laptop, is being specified.""
How i can note "" col-md-* class"" 
1 - then i dont have the code for this illustration.
2 - i dont know what is  ""col-md-* class"" becouse i m not a coder and this is a lesson to teach me about "" col-md-* class""  .

someone  forgot that the people coming to learn html actualy DONT KNOW HTML

! the code does not matter . the problem is in the assignment illustration and info.
My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text text-center">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>

  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">
  <button class="btn btn-block btn-primary">Like</button>
  <button class="btn btn-block btn-info">Info</button>
  <button class="btn btn-block btn-danger">Delete</button>
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

**Comment by jonathanihm** [comment]
Hi,

Previous lessons and challenges have you create and work with classes.  This is an assignment where you want to use an existing bootstrap class for your code.  Can you explain what about it is misleading?

If you need help, please feel free to use the chatrooms and forums.

Cheers!

**Comment by raisedadead** [comment]
Hi @rocnogu please revert back if you still feel this is an issue.
