### ISSUE TITLE
Can't move the cursor to some parts of the code

### ISSUE THREAD

**Issue by m3h0w** [freeCodeCamp/freeCodeCamp#15052]
#### Issue Description
Every 2 or 3 challanges (sometimes even in a row but I can't seem to understand what's the cause) I can't access far parts of the lines that I need to edit. The cursor just jumps to the next line or doesn't move at all.

I recorded a video of the behaviour: https://drive.google.com/open?id=0B_zGmwAmO3kCQ0VhWXZ0TlFoaEk

Interesetingly enough, reloading the page doesn't help. But the reset button on the left does. Furthermore, the bug also dissapears if I shrink the browser window (is stil gone after maximizing it afterwards).

#### Browser Information
Tried both the newest Chrome and Firefox.

* Operating System: Windows 7 64-bit

**Comment by texas2010** [comment]
@m3h0w Thanks for reporting an issue. This is a duplicate of a long-known issue with the editor. See: https://github.com/freeCodeCamp/freeCodeCamp/issues/7847. It will be fixed when the beta site replaces the current site.

**Comment by sogen** [comment]
For everyone having the mouse cursor problem, try Chrome Canary, works fine
