### ISSUE TITLE
CSS Flexbox - Use display: flex can not pass test

### ISSUE THREAD

**Issue by nicholasnbg** [freeCodeCamp/freeCodeCamp#15056]
#### Challenge Name

CSS Flexbox: Use display:flex to position 2 boxes

#### Issue Description

Simply following basic instructions not passing tests.

#### Browser Information

* Browser Name, Version: Firefox ver 53
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
#box-container {
    display: flex;
}


```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/17841511/26476697/d009c5a0-4203-11e7-808c-301bd1d4594d.png)

**Comment by MiloATH** [comment]
Could you please give the code as text.

**Comment by nicholasnbg** [comment]
Done MiloATH, sorry, first time reporting issues on GH!

Also I think it is a larger problem for me than just this exercise, I couldn't get the following exercise to work either.

**Comment by charlesBak** [comment]
the problem seems to with your version of firefox. Try Chrome

**Comment by systimotic** [comment]
Hi @nicholasnbg! Thank you for trying out the beta and reporting this issue.

As @charlesBak mentioned, we currently have some issues with Firefox in the beta. Specifically, any test that relies on the outputted CSS does not work. We're working on this in #10749

I'm closing this issue in favour of that. While we're working on fixing these tests, you should be able to pass the challenges that don't work in Chrome.

Happy coding!
