### ISSUE TITLE
Signed up with FCC using email address. When I signed back in under the email I signed up with, all my brownie points were gone and I was forced to start over twice.

### ISSUE THREAD

**Issue by Chelsea-Pittman92** [freeCodeCamp/freeCodeCamp#15057]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by Chelsea-Pittman92** [comment]
I'm using Google Chrome with macOSSierra version 10.12.3. Macbook pro

**Comment by raisedadead** [comment]
Hi @Chelsea-Pittman92 can you please drop an email to team@freecodecamp.com with the details of the email that you used, your username etc.

Thanks.
/cc @QuincyLarson

**Comment by dolunaykiz** [comment]
why the heck am i subscribed to this thread?

**Comment by dolunaykiz** [comment]
how can i unsubscribe? i have no idea how i even got on this. TAKE ME OFF.

**Comment by raisedadead** [comment]
@dolunaykiz you are subscribed most probably because you might have accidentally clicked the watch button on this page at the top.

To stop receiving notifications please visit the [subscriptions page](https://github.com/freeCodeCamp/freeCodeCamp/subscription) and select **"Not watching"**.

**Comment by raisedadead** [comment]
Hi @Chelsea-Pittman92 if you are still stuck with this please email us back at team@freecodecamp.com
