### ISSUE TITLE
Add image cat photo app

### ISSUE THREAD

**Issue by PaulWalt74** [freeCodeCamp/freeCodeCamp#15053]
![add an image](https://cloud.githubusercontent.com/assets/28942745/26470132/2cce579e-4162-11e7-8859-ef3b8de03e91.png)
 here is a screenshot i am using linux which can be an issue any ideas?

**Comment by texas2010** [comment]
@PaulWalt74 
Thanks for reporting this. But your code is in wrong place and not correct. 
These GitHub Issues are for reporting bugs on the website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
