### ISSUE TITLE
how tf does this work

### ISSUE THREAD

**Issue by MuhammadAsadIlyas** [freeCodeCamp/freeCodeCamp#15050]
Challenge [Comment out HTML](https://www.freecodecamp.com/challenges/comment-out-html#?solution=%0A%3C!--lmao--%3E%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%20%20%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%20%0A%0A%3C!--the%20fuck--%3E%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<!--lmao-->
<h1>Hello World</h1>  

<h2>CatPhotoApp</h2> 

<!--the fuck-->
<p>Hello Paragraph</p>


```

**Comment by jonathanihm** [comment]
Hello,

If you need help, please try the forums and chatroom.  

Cheers!

**Comment by raisedadead** [comment]
Hi @MuhammadAsadIlyas 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
