### ISSUE TITLE
Typo on Magical Maths Addition

### ISSUE THREAD

**Issue by ThiagoFerreir4** [FreeCodeCamp/freecodecamp#1505]
Challenge http://beta.freecodecamp.com/challenges/magical-maths-addition has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

"In JavaScript whole numbers (called integers) can be really "easily" to "preform"
![screenshot from 2015-08-04 10 56 21](https://cloud.githubusercontent.com/assets/10325354/9055895/a4504f58-3a97-11e5-9df8-52a6b6f74070.png)
 mathematical functions"

**Comment by mistamadd001** [comment]
I believe the paragraph should read: In JavaScript, whole numbers (integers, ints) can really easily perform mathematical functions.

or

In JavaScript, whole numbers (integers, ints) can really easily be made to perform mathematical functions.

**Comment by benmcmahon100** [comment]
fix https://github.com/FreeCodeCamp/freecodecamp/commit/fc0ccf3aeafcb66b5747858ecd5020db33c904d6

**Comment by benmcmahon100** [comment]
Thanks for pointing this out! We're still squashing those bugs and my horrific typos

**Comment by ThiagoFerreir4** [comment]
No problem Ben! Will post an issue if I spot something else! :)

**Comment by benmcmahon100** [comment]
Please do! Some of the fixes may not be deployed for a while
