### ISSUE TITLE
Code generates right results, yet they are not validated

### ISSUE THREAD

**Issue by relentlesscleaner** [freeCodeCamp/freeCodeCamp#15054]
Challenge [Roman Numeral Converter](https://www.freecodecamp.com/challenges/roman-numeral-converter#?solution=const%20thousands%20%3D%20(n)%20%3D%3E%20%7B%0A%20%20switch(n)%20%7B%0A%20%20%20%20case%200%3A%20return%20%22%22%3B%0A%20%20%20%20case%201%3A%20return%20%22M%22%3B%0A%20%20%20%20case%202%3A%20return%20%22MM%22%3B%0A%20%20%20%20case%203%3A%20return%20%22MMM%22%3B%0A%20%20%7D%0A%20%20%0A%7D%0A%0Aconst%20hundreds%20%3D%20(n)%20%3D%3E%20%7B%0A%20%20switch(n)%20%7B%0A%20%20%20%20case%200%3A%20return%20%22%22%3B%0A%20%20%20%20case%201%3A%20return%20%22C%22%3B%0A%20%20%20%20case%202%3A%20return%20%22CC%22%3B%0A%20%20%20%20case%203%3A%20return%20%22CCC%22%3B%0A%20%20%20%20case%204%3A%20return%20%22CD%22%3B%0A%20%20%20%20case%205%3A%20return%20%22D%22%3B%0A%20%20%20%20case%206%3A%20return%20%22DC%22%3B%0A%20%20%20%20case%207%3A%20return%20%22DCC%22%3B%0A%20%20%20%20case%208%3A%20return%20%22DCCC%22%3B%0A%20%20%20%20case%209%3A%20return%20%22CM%22%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20dozens%20%3D%20(n)%20%3D%3E%20%7B%0A%20%20switch(n)%20%7B%0A%20%20%20%20case%200%3A%20return%20%22%22%3B%0A%20%20%20%20case%201%3A%20return%20%22X%22%3B%0A%20%20%20%20case%202%3A%20return%20%22XX%22%3B%0A%20%20%20%20case%203%3A%20return%20%22XXX%22%3B%0A%20%20%20%20case%204%3A%20return%20%22XL%22%3B%0A%20%20%20%20case%205%3A%20return%20%22L%22%3B%0A%20%20%20%20case%206%3A%20return%20%22LX%22%3B%0A%20%20%20%20case%207%3A%20return%20%22LXX%22%3B%0A%20%20%20%20case%208%3A%20return%20%22LXXX%22%3B%0A%20%20%20%20case%209%3A%20return%20%22XC%22%3B%0A%20%20%7D%0A%7D%0A%0Aconst%20units%20%3D%20(n)%20%3D%3E%20%7B%0A%20%20switch(n)%20%7B%0A%20%20%20%20case%200%3A%20return%20%22%22%3B%0A%20%20%20%20case%201%3A%20return%20%22I%22%3B%0A%20%20%20%20case%202%3A%20return%20%22II%22%3B%0A%20%20%20%20case%203%3A%20return%20%22III%22%3B%0A%20%20%20%20case%204%3A%20return%20%22IV%22%3B%0A%20%20%20%20case%205%3A%20return%20%22V%22%3B%0A%20%20%20%20case%206%3A%20return%20%22VI%22%3B%0A%20%20%20%20case%207%3A%20return%20%22VII%22%3B%0A%20%20%20%20case%208%3A%20return%20%22VIII%22%3B%0A%20%20%20%20case%209%3A%20return%20%22IX%22%3B%0A%20%20%7D%0A%7D%0Afunction%20convertToRoman(num)%20%7B%0A%20n%20%3D%20%5BMath.floor(num%2F1000)%2C%20Math.floor(num%251000%2F100)%2C%20Math.floor(num%25100%2F10)%2C%20num%2510%5D%0A%20r%20%3D%20thousands(n%5B0%5D)%20%2B%20hundreds(n%5B1%5D)%20%2B%20dozens(n%5B2%5D)%20%2B%20units(n%5B3%5D)%0A%20return%20r%3B%0A%7D%0AconvertToRoman(2014)%3B%20%2F%2FCode%20seems%20to%20be%20working%2C%20yet%20not%20validating%20the%20tests%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
const thousands = (n) => {
  switch(n) {
    case 0: return "";
    case 1: return "M";
    case 2: return "MM";
    case 3: return "MMM";
  }
  
}

const hundreds = (n) => {
  switch(n) {
    case 0: return "";
    case 1: return "C";
    case 2: return "CC";
    case 3: return "CCC";
    case 4: return "CD";
    case 5: return "D";
    case 6: return "DC";
    case 7: return "DCC";
    case 8: return "DCCC";
    case 9: return "CM";
  }
}

const dozens = (n) => {
  switch(n) {
    case 0: return "";
    case 1: return "X";
    case 2: return "XX";
    case 3: return "XXX";
    case 4: return "XL";
    case 5: return "L";
    case 6: return "LX";
    case 7: return "LXX";
    case 8: return "LXXX";
    case 9: return "XC";
  }
}

const units = (n) => {
  switch(n) {
    case 0: return "";
    case 1: return "I";
    case 2: return "II";
    case 3: return "III";
    case 4: return "IV";
    case 5: return "V";
    case 6: return "VI";
    case 7: return "VII";
    case 8: return "VIII";
    case 9: return "IX";
  }
}
function convertToRoman(num) {
 n = [Math.floor(num/1000), Math.floor(num%1000/100), Math.floor(num%100/10), num%10]
 r = thousands(n[0]) + hundreds(n[1]) + dozens(n[2]) + units(n[3])
 return r;
}
convertToRoman(2014); //Code seems to be working, yet not validating the tests

```

**Comment by hugo-elliott** [comment]
There appear to be some missing semi-colons - the following works for me in Safari

const thousands = (n) => {
  switch(n) {
    case 0: return "";
    case 1: return "M";
    case 2: return "MM";
    case 3: return "MMM";
  }
};

const hundreds = (n) => {
  switch(n) {
    case 0: return "";
    case 1: return "C";
    case 2: return "CC";
    case 3: return "CCC";
    case 4: return "CD";
    case 5: return "D";
    case 6: return "DC";
    case 7: return "DCC";
    case 8: return "DCCC";
    case 9: return "CM";
  }
};

const dozens = (n) => {
  switch(n) {
    case 0: return "";
    case 1: return "X";
    case 2: return "XX";
    case 3: return "XXX";
    case 4: return "XL";
    case 5: return "L";
    case 6: return "LX";
    case 7: return "LXX";
    case 8: return "LXXX";
    case 9: return "XC";
  }
};

const units = (n) => {
  switch(n) {
    case 0: return "";
    case 1: return "I";
    case 2: return "II";
    case 3: return "III";
    case 4: return "IV";
    case 5: return "V";
    case 6: return "VI";
    case 7: return "VII";
    case 8: return "VIII";
    case 9: return "IX";
  }
};
function convertToRoman(num) {
 n = [Math.floor(num/1000), Math.floor(num%1000/100), Math.floor(num%100/10), num%10];
 r = thousands(n[0]) + hundreds(n[1]) + dozens(n[2]) + units(n[3]);
 return r;
}
convertToRoman(2014); //Code seems to be working, yet not validating the tests

**Comment by raisedadead** [comment]
Hi @relentlesscleaner 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
