### ISSUE TITLE
suggestion: allow a purely functional solution

### ISSUE THREAD

**Issue by marclundgren** [freeCodeCamp/freeCodeCamp#15065]
Challenge [Stand in Line](https://www.freecodecamp.com/challenges/stand-in-line#?solution=%2F%2F%20NOTE%3A%20this%20assignment%20is%20bullshit.%20here's%20the%20pure%20example%2C%20but%20they're%20expecting%20a%20non-pure%20method%0A%0A%2F%2F%20const%20nextInLine%20%3D%20(arr%2C%20item)%20%3D%3E%20arr.concat(item).shift()%0A%0A%0Afunction%20nextInLine(arr%2C%20item)%20%7B%0A%20%20%2F%2F%20Your%20code%20here%0A%20%20arr.push(item)%3B%0A%20%20%0A%20%20return%20arr.shift()%3B%0A%7D%0A%0A%2F%2F%20Test%20Setup%0Avar%20testArr%20%3D%20%5B1%2C2%2C3%2C4%2C5%5D%3B%0A%0A%2F%2F%20Display%20Code%0Aconsole.log(%22Before%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0Aconsole.log(nextInLine(testArr%2C%206))%3B%20%2F%2F%20Modify%20this%20line%20to%20test%0Aconsole.log(%22After%3A%20%22%20%2B%20JSON.stringify(testArr))%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
// Pure approach
// const nextInLine = (arr, item) => arr.concat(item).shift()

// Non-pure approach (mutates arr)
function nextInLine(arr, item) {
  // Your code here
  arr.push(item);
  
  return arr.shift();
}

// Test Setup
var testArr = [1,2,3,4,5];

// Display Code
console.log("Before: " + JSON.stringify(testArr));
console.log(nextInLine(testArr, 6)); // Modify this line to test
console.log("After: " + JSON.stringify(testArr));

```

The problem: 
This test assertion is expecting our method to mutate the original data set, something that is a terrible habit to teach newcomers about.

After `nextInLine(testArr, 10)`, `testArr[4]` should be `10`

My pure function that simple get's the next in line does it's job as a pure function. TL;DR don't write a function that mutates data passed in. This is a dangerous habit for new programmers to think is okay and normal.

**Comment by knyzorg** [comment]
Tbh it is imperative they new-comers **do** learn that arrays have a tendency to be muted by what should be pure functions.

Making immutable functions with arrays is of course a good thing, but cutting out the exercises show-casing Array mutability will set people up for failure.

**Comment by marclundgren** [comment]
good point
