### ISSUE TITLE
Beta: signed in user not detected

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/freecodecamp#1506]
I broke something switching over to loopback middleware phases, now when signed in the app does not detect that a user is not signed in. To sleepy to tackle this at the moment.

@benmcmahon100 let me know if you can figure this out before I wake up. If not I'll take a look first thing.

**Comment by benmcmahon100** [comment]
Hmmm interesting. On a possibly related note my own personal copy of FCC doesn't have working sign ins either. Its sounds like the same issue

**Comment by Canuckywoman** [comment]
I can't sign into the Beta at all with the email address I used to sign up to FCC. Oh well...

**Comment by benmcmahon100** [comment]
Potential fix for this and #1507 here https://github.com/FreeCodeCamp/freecodecamp/commit/fc0ccf3aeafcb66b5747858ecd5020db33c904d6

**Comment by BerkeleyTrue** [comment]
fixed.
