### ISSUE TITLE
Comparisons with the Logical And Operator bug

### ISSUE THREAD

**Issue by CaptainSteele** [freeCodeCamp/freeCodeCamp#15069]
I do not understand what I am doing wrong, everything looks good to me 

#### Challenge Name
https://www.freecodecamp.com/challenges/comparisons-with-the-logical-and-operator#?solution=%0Afunction testLogicalAnd(val) {%0A %2F%2F Only change code below this line%0A if (val>%3D25 %26%26 val<%3D50)%3B {%0A return "Yes"%3B%0A }%0A %2F%2F Only change code above this line%0A return "No"%3B%0A}%0A%2F%2F Change this value to test%0AtestLogicalAnd(10)%3B%0A

* Browser Name, Version: 
Firefox
* Operating System: 
* Mobile, Desktop, or Tablet: 
Desktop

#### Your Code
function testLogicalAnd(val) {
  // Only change code below this line
  if (val>=25 && val<=50); {
          return "Yes";
      }
  // Only change code above this line
  return "No";
}
// Change this value to test
testLogicalAnd(10);

```
#### Screenshot
![help](https://cloud.githubusercontent.com/assets/28496600/26513815/3b311642-4233-11e7-9c6f-e4b7e8eab4d9.jpg)

**Comment by CaptainSteele** [comment]
![capture](https://cloud.githubusercontent.com/assets/28496600/26514124/66489e66-4235-11e7-9d6b-94dcc5fef8d3.PNG)

**Comment by CaptainSteele** [comment]
![capture](https://cloud.githubusercontent.com/assets/28496600/26514266/664e2966-4236-11e7-81f8-b4eb5d6a2593.PNG)

**Comment by Renitstark** [comment]
@CaptainSteele
 function testLogicalAnd(val) {
  // Only change code below this line

  if (val >=25 && val<=50) {
    
      return "Yes";
    }
 

  // Only change code above this line
  return "No";
}

// Change this value to test
testLogicalAnd(10);
