### ISSUE TITLE
wont take answer even though it seems correct and works with every situation?

### ISSUE THREAD

**Issue by TheBlackCook** [freeCodeCamp/freeCodeCamp#15068]
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number#?solution=var%20array1%3D%5B%5D%3B%0Avar%20t%20%3D%200%3B%0Afunction%20factorialize(num)%20%7B%0A%20%20for%20(var%20i%3D1%3B%20i%3C%3D%20num%3B%20i%2B%2B)%7B%0A%20%20%20%20array1.push(i)%3B%7D%0A%20%20%0A%20%20if%20(num%20!%3D%3D%200)%7B%0A%20%20%20%20t%20%3D%20array1.reduce(function(a%2Cb)%7B%0A%20%20%20%20return%20a*b%20%3B%7D)%3B%0A%20%20return%20t%3B%7D%0A%20%20%0A%20else%20%7B%0A%20%20%20%20return%20i%3B%7D%0A%7D%0A%0Afactorialize(5)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array1=[];
var t = 0;
function factorialize(num) {
  for (var i=1; i<= num; i++){
    array1.push(i);}
  
  if (num !== 0){
    t = array1.reduce(function(a,b){
    return a*b ;});
  return t;}
  
 else {
    return i;}
}

factorialize(5);

```

**Comment by dhcodes** [comment]
@TheBlackCook sometimes the editor has issues with global variables. Move your first two lines into your function and it will pass. In the future consider asking for help in the HelpJavascript chat room.

**Comment by TheBlackCook** [comment]
thank you and i tried and got no answers after a couple of tries.
