### ISSUE TITLE
I tested severak times but not giving required result despite the logic is correct

### ISSUE THREAD

**Issue by NawasNaziru** [freeCodeCamp/freeCodeCamp#15060]
Challenge [Confirm the Ending](https://www.freecodecamp.com/challenges/confirm-the-ending#?solution=%0Afunction%20confirmEnding(str%2C%20target)%20%7B%0A%20%20%2F%2F%20%22Never%20give%20up%20and%20good%20luck%20will%20find%20you.%22%0A%20%20%2F%2F%20--%20Falcor%0A%20if(%20(str.substring((str.length-target.length-1)%2C(str.length)))%3D%3D%3Dtarget)%7B%0A%20return%20true%3B%0A%20%20%7D%0A%20%20else%7B%0A%20%20return%20false%3B%0A%20%20%20%20%0A%20%20%7D%0A%7D%0A%0AconfirmEnding(%22Bastian%22%2C%20%22n%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36 OPR/36.2.2126.102826</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function confirmEnding(str, target) {
  // "Never give up and good luck will find you."
  // -- Falcor
 if( (str.substring((str.length-target.length-1),(str.length)))===target){
 return true;
  }
  else{
  return false;
    
  }
}

confirmEnding("Bastian", "n");

```
I tested severak times but not giving required result despite the logic is correct

**Comment by jodylecompte** [comment]
Hey @NawasNaziru 

The logic is very close, but not 100% correct. For example, with the given test case you are actually looking at substr(5,7) so the comparison being made is "an" === "n" which returns false. 

Feel free to drop by the [chat](https://gitter.im/FreeCodeCamp/FreeCodeCamp) for some help with this challenge.

**Comment by raisedadead** [comment]
Hi @NawasNaziru 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
