### ISSUE TITLE
Not submitting despite all results are correct

### ISSUE THREAD

**Issue by NawasNaziru** [freeCodeCamp/freeCodeCamp#15062]
_Challenge_ [Repeat a string repeat a string](https://www.freecodecamp.com/challenges/repeat-a-string-repeat-a-string#?solution=var%20newStr%3D%22%22%3B%0Afunction%20repeatStringNumTimes(str%2C%20num)%20%7B%0A%20%20for(i%3D1%3Bi%3C%3Dnum%3Bi%2B%2B)%0A%20%20%7B%0A%20%20%20%20newStr%2B%3Dstr%3B%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20return%20newStr%3B%0A%0A%7D%0ArepeatStringNumTimes(%22*%22%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36 OPR/36.2.2126.102826</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var newStr="";
function repeatStringNumTimes(str, num) {
  for(i=1;i<=num;i++)
  {
    newStr+=str;
    
  }
  
  return newStr;

}
repeatStringNumTimes("*", 3);

```
Not submitting despite all results are correct

**Comment by jodylecompte** [comment]
This is not a bug, you're declaration of ```newStr``` needs to be moved inside your function. After doing so all tests will pass.

**Comment by raisedadead** [comment]
Hi @.

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by NawasNaziru** [comment]
Dear Sir/Ma,
 I am very grateful for your help. But please can you help know why it
works only if the newStr variable is declared locally?

Best regards,
Nawas Naziru

**Comment by raisedadead** [comment]
> But please can you help know why it works only if the newStr variable is declared locally?

@NawasNaziru please visit the chat room or the forum, this issue tracker is not the correct place for the queries you have.

Thanks and happy coding!
