### ISSUE TITLE
code is exact for the next lesson however mine is not working

### ISSUE THREAD

**Issue by tinoweeno** [freeCodeCamp/freeCodeCamp#15066]
Challenge [Change the Color of Text](https://www.freecodecamp.com/challenges/change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h2>style= "color: red"> CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Tsukuyomi19** [comment]
Looks like you have an extra > for the h2 element. Should look like <h2 style="color: red"> instead.

**Comment by dhcodes** [comment]
@Tsukuyomi19 is correct. In the future, consider asking for help in the chat room on gitter: 
https://gitter.im/FreeCodeCamp/Help
