### ISSUE TITLE
Bootstrap image is not displayed when clicked

### ISSUE THREAD

**Issue by HamerWV** [freeCodeCamp/freeCodeCamp#15072]
Hello freeCodeCamp,
In the directions is an image for the Bootstrap 12 column grid.  When you click on it you end up on a bootstrap page that explains how the grid works and the image is not available.  Although the info is very helpful, you cannot see the image.

I just checked the non-beta version and when you click on the image it does open up to see the grid system image.

Challenge [use-the-bootstrap-grid-to-put-elements-side-by-side](https://beta.freecodecamp.com/en/challenges/bootstrap/use-the-bootstrap-grid-to-put-elements-side-by-side) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text text-center">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>

  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera.">
  <button class="btn btn-block btn-primary">Like</button>
  <button class="btn btn-block btn-info">Info</button>
  <button class="btn btn-block btn-danger">Delete</button>
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

**Comment by gbrowdy** [comment]
The root of the problem is that the link for the image goes to a hash that does not exist, so it just sends to the top of the page.  

The other problem is that the page it sends to is the docs for Bootstrap v4-alpha, which does not even have that image in it, but rather a slightly different one.  The image thumbnailed in the exercise is from Bootstrap 3.3.7.

So, two ways to solve this:
1) Link to [Bootstrap 3.3.7](https://getbootstrap.com/css/#grid-example-basic), or
2) Link to [Bootstrap v4-alpha](https://v4-alpha.getbootstrap.com/layout/grid/#responsive-classes), which has different documentation and a different example, so the thumbnail ought to be changed, too, in this option.

**Comment by cbhtesthub** [comment]
Hello HamerWV. 

I was just glancing through your problem. The first answer to your problem is correct. However, to be a little more detailed, look for your anchor tags `<a>`. You have them linked to `#`. Which is simply going to refresh your page and bring you back to the top of your page.

**Comment by akkatracker** [comment]
Does this bug still exist? Can't seem to find what you're talking about
