### ISSUE TITLE
2

### ISSUE THREAD

**Issue by fikiardiyanto** [freeCodeCamp/freeCodeCamp#15071]
Challenge [Build a Personal Portfolio Webpage](https://www.freecodecamp.com/challenges/build-a-personal-portfolio-webpage) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by raisedadead** [comment]
Refer this comment https://github.com/freeCodeCamp/freeCodeCamp/issues/15070#issuecomment-304431561
