### ISSUE TITLE
[beta] Data Visualization with D3: Use Dynamic Scales

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#15078]
Data Visualization with D3: Use Dynamic Scales
https://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/use-dynamic-scales

Minor change to the instructions:

>Remember to keep the plot right-side-up. When you set the range for the y coordinates, the higher value (height **less** padding) is the first argument, and the lower value is the second argument.

Should/can be changed to 

>Remember to keep the plot right-side-up. When you set the range for the y coordinates, the higher value (height **minus** padding) is the first argument, and the lower value is the second argument.

**Comment by tommygebru** [comment]
Also the result window for the D3 lessons in Freecodecamp NightMode is pretty difficult to view.... suggest brightening the background or perhaps just the color of the elements... 

most likely the latter

**Comment by HKuz** [comment]
Hi @tommygebru - I think this is a fair point and we should make that change.

First timers only for this one - please consult the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) to get set up, and feel free to ask any questions in the [Contributor's chat room](https://gitter.im/freecodecamp/contributors). You can find the code to make this change [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/04-data-visualization/data-visualization-with-d3.json#L1544). Thank you! 🎉 :eagle: 💯

**Comment by tommygebru** [comment]
Woah - thanks for responding @HKuz l didnt know its been 25 days, can I help out FCC with some moderation as well? @raisedadead 🥇

**Comment by HKuz** [comment]
Thanks @tommygebru - and we appreciate your patience! With all the new Beta issues flowing in, some issues unfortunately got buried...

**Comment by shreyasminocha** [comment]
I'm willing to take this up.

**Comment by tommygebru** [comment]
thanks @shreyasminocha but i was able to make a pull request here #15484

**Comment by erictleung** [comment]
Closing as fixed by https://github.com/freeCodeCamp/freeCodeCamp/pull/15484. Happy coding everyone!
