### ISSUE TITLE
Bug in "Escape Sequences in Strings" when \r isnt used

### ISSUE THREAD

**Issue by rraffael** [freeCodeCamp/freeCodeCamp#15073]
#### Escape Sequences in Strings

https://www.freecodecamp.com/challenges/escape-sequences-in-strings

#### Issue Description

When you type the code with \n, \\, it only works if you fill with \r in the end, if not all the commands appears like "Text\nTest" rather than "Text
Test"

#### Browser Information

I use a notebook, in the university internet.
* Browser Name, Version: Chrome
* Operating System: Windows
* Mobile, Desktop, or Tablet: 
Mobile
#### Your Code

```js
var myStr = "FirstLine\n\\SecondLine\\\nThirdLine";
```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/27858619/26521333/8c057aac-42bc-11e7-8727-86074b0c2451.png)

**Comment by raisedadead** [comment]
Thanks for reporting @rraffael!

Isn't that the expectation from the test case and what the instructions precisely ask to? If this is a code assistance please consider consulting the chat rooms and the forum. The issue tracker is for bugs only.

Please revert back if that's not the case with the details.

Thanks and happy coding!

**Comment by rraffael** [comment]
Yes it is, but for example, at first i just type "FirstLine /n SecondLine"
to test if it was right, but it wasnt because the Run test show literally
"FirstLine /n SecondLine", and it is wrong, so it confuses me

2017-05-27 9:23 GMT-03:00 mrugesh mohapatra <notifications@github.com>:

**Comment by raisedadead** [comment]
Hi @rraffael 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
