### ISSUE TITLE
Text issue

### ISSUE THREAD

**Issue by misacas** [freeCodeCamp/freeCodeCamp#15077]
Challenge [Style Multiple Elements with a CSS Class](https://www.freecodecamp.com/challenges/style-multiple-elements-with-a-css-class) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.

Is it correct to say : "remember that class **declarations** don't use a period, like this: `<h2 class="blue-text">CatPhotoApp</h2>`" ? Shouldn't it be "remember that class **usage** don't use a period, like" ? because the css class has already been declared.

**Comment by ApCoder123** [comment]
When it says 'class declarations', it is referring to the class in the HTML(`<h2 class="blue-text">CatPhotoApp</h2>`), as that is where it originally gets declared. The class isn't declared in the CSS. The wording is correct

**Comment by raisedadead** [comment]
Yes, the verbiage is correct. Thanks for reporting @misacas and for the clarification @ApCoder123
