### ISSUE TITLE
Unable to Sign In with Twitter to Gitter Chat Room!! 

### ISSUE THREAD

**Issue by erthwzrd** [freeCodeCamp/freeCodeCamp#15075]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by erthwzrd** [comment]
Please email me with questions or when problem is fixed

**Comment by ApCoder123** [comment]
@erthwzrd FreeCodeCamp has set the Gitter chat room in that way, so that you are required to sign in with a GitHub account. This helps to ensure that members are legitimate and have followed the steps to set up a GitHub account

**Comment by raisedadead** [comment]
@ApCoder123 we support Github only login into our chat rooms.
