### ISSUE TITLE
Valid code in "No repeats please" challenge freezes browser up

### ISSUE THREAD

**Issue by k-kapp** [freeCodeCamp/freeCodeCamp#15087]
#### Challenge Name:
No Repeats Please
https://www.freecodecamp.com/challenges/no-repeats-please

#### Issue Description
Browser freezes up when I run perfectly valid code on freecodecamp JS interpreter - have tested it in my browser's JS interpreter and it runs fine.

NOTE: I know that this isn't the final solution, but this code should still not be freezing the browser up. Also, I followed the suggestion of entering `localStorage.clear()` into the console. That, however, has cleared the code from ALL my challenges, but it still shows on my map that I completed them. Does this mean that I will not have to redo the challenges, even though the code is now missing?

#### Browser Information

Firefox 53.0.3 (32-bit)
Windows 10 Home Edition
Desktop

#### Code

WARNING: the code below might be a slight spoiler for some who still wish to do the challenge.

```js

function perms(str)
{
  if (str.length === 0)
    return [""];
  else
  {
    var allPerms = [];
    for (var i = 0; i < str.length; i++)
    {
      var ch = str.charAt(i);
      var newString = str.substring(0, i) + str.substring(i + 1);
      var allThesePerms = perms(newString);
      for (var j = 0; j < allThesePerms.length; j++)
      {
        allThesePerms[j] = ch + allThesePerms[j];
      }
      allPerms = allPerms.concat(allThesePerms);
    }
    return allPerms;
  }
}


function permAlone(str) {
  return perms(str);
}

permAlone("abc");

```

**Comment by raisedadead** [comment]
Hi @k-kapp 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by raisedadead** [comment]
Please revert back with the details as requested.
