### ISSUE TITLE
ES6: Understand the Differences Between import and require

### ISSUE THREAD

**Issue by jaouadballat** [freeCodeCamp/freeCodeCamp#15089]
Challenge [understand-the-differences-between-import-and-require](https://beta.freecodecamp.com/en/challenges/es6/understand-the-differences-between-import-and-require) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3113.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js

import { capitalizeString } from "string_functions";

capitalizeString("hello!");

```

**Comment by xRahul** [comment]
I'm seeing this in the assertions. Seems to be an error with the data.
```
assert(code.match(/import\s+\{\s?capitalizeString\s?\}\s+from\s+"string_functions"/ig)
```

**Comment by davisec52** [comment]
I can also confirm issues with this challenge. As above, the import keyword does not appear to be working. I am running:
```
import { capitalizeString } from "string_functions";
capitalizeString("hello!");
```
And the error given is this:
```
//running tests
"require is not defined"
//tests completed

assert(code.match(/import\s+\{\s?capitalizeString\s?\}\s+from\s+"string_functions"/ig)

```

**Comment by AndreyAzimov** [comment]
same

**Comment by systimotic** [comment]
Hi everybody! Thanks for reporting and looking into this issue.

We're working on fixing the ES6 challenges in https://github.com/freeCodeCamp/freeCodeCamp/issues/12698. I'm closing this issue in favor of that.

Happy coding!
