### ISSUE TITLE
bug in passing the test with erroneous code

### ISSUE THREAD

**Issue by pehlivan38** [freeCodeCamp/freeCodeCamp#15088]
I passed the test with the following wrong coding - it did not even work correctly: see the image...

![image](https://cloud.githubusercontent.com/assets/29004885/26524609/93f2a9a8-4341-11e7-90ed-d5607042a608.png)

Challenge [Use Responsive Design with Bootstrap Fluid Containers](https://www.freecodecamp.com/challenges/use-responsive-design-with-bootstrap-fluid-containers) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<div class="container-fluid">

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
https://s3.amazonaws.com/freecodecamp/iphone6-frame.png
<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <label><input type="radio" name="indoor-outdoor"> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
  <label><input type="checkbox" name="personality"> Loving</label>
  <label><input type="checkbox" name="personality"> Lazy</label>
  <label><input type="checkbox" name="personality"> Crazy</label>
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>
  
</div>

```

**Comment by littlewise** [comment]
nice can you teach me how to code if yes you can email me on adisatolulopejoshua@gmail.com

**Comment by jmona789** [comment]
How is the code incorrect? It looks correct to me, everything is wrapped in a div with the class container-fluid

**Comment by mihaid85** [comment]
@jmona789 The opening div should be below the style. And the rest of the html is not nested. 

I checked and it works for me too.

**Comment by mihaid85** [comment]
The opening div should be below the the style. It violates HTML syntax rules, but it will still display properly, which is why it works.

**Comment by pehlivan38** [comment]
Indeed, I asumed that failure in syntax results in a failure in the compilation. But this assumption does not hold - I checked the code in an html-editor after mihaid85's comment- it displayed properly as well. 

I understand now that not all syntax rules are being forced by html.

**Comment by langmaza** [comment]
< div  class = " container-fluid " >

< link  href = " https://fonts.googleapis.com/css?family=Lobster "  rel = " stylesheet "  type = " text / css " >
< สไตล์ >
  .red-text { 
color : red ;   }    


  h2 { 
ครอบครัวแบบอักษร : กุ้งก้ามกราม, Monospace ;   }    


  p { 
font-size : 16 px ; แบบอักษรครอบครัว : Monospace ;   }    
    


  . สีเขียว - ชายแดน { 
border-color : green ; border-width : 10 px ; border-style : แข็ง ; รัศมีขอบ : 50 % ;   }    
    
    
    


  .smaller-image { 
กว้าง : 100 px ;   }    

< / style >

< h2  class = " red-text " > CatPhotoApp </ h2 >
https://s3.amazonaws.com/freecodecamp/iphone6-frame.png
< P > คลิกที่นี่เพื่อ < href = " # " > ภาพถ่ายแมว </ >. </ P > 

< href = " # " > < img ระดับ = "ขนาดเล็กภาพหนาสีเขียวพรมแดน" src = " https://bit.ly/fcc-relaxing-cat " Alt = "แมวสีส้มน่ารักนอนอยู่บนหลังของมัน . " > </ a >    

< p > แมวที่รัก: </ p >
< ul >
  < li > การหยิกแมว </ li >
  < li > ตัวชี้เลเซอร์ </ li >
  < li > ลาซานญ่า </ li >
</ ul >
< p > สิ่งที่เกลียดที่สุด 3 เรื่อง: </ p >
< ol >
  < li > การรักษาหมัด </ li >
  < li > ฟ้าร้อง </ li >
  < li > แมวอื่น ๆ </ li >
< ol >
< form  action = " / submit-cat-photo " >
  < label > < input  type = " radio "  name = " indoor-outdoor " > ในอาคาร </ label >
  < label > < input  type = " radio "  name = "ภายในอาคาร" > กลางแจ้ง </ label >
  < label > < input  type = " checkbox "  name = " personality " > รัก </ label >
  < label > < input  type = " checkbox "  name = " personality " > ขี้เกียจ </ label >
  < label > < input  type = " checkbox "  name = "บุคลิกภาพ" > บ้า </ label >
  < input  type = " text "  placeholder = " cat photo URL " ต้อง >
  < button  type = " submit " > ส่ง </ button >
</ form >
  
</ div >

**Comment by MiloATH** [comment]
I think this issue can be closed @raisedadead. The only possible test that could be added is a test to make sure all the seed code (and only the seed code) is in the div container.
