### ISSUE TITLE
This is telling me I need to use //unprotect on last test all the rest pass. If I had an infinite it would stop me before the other test started

### ISSUE THREAD

**Issue by DivaWeb** [freeCodeCamp/freeCodeCamp#15080]
Challenge [Smallest Common Multiple](https://www.freecodecamp.com/challenges/smallest-common-multiple#?solution=%0Afunction%20smallestCommons(arr)%20%7B%0A%20%20var%20smallest%20%3D%20(Math.min.apply(null%2C%20arr))%3B%0A%20%20var%20largest%20%3D%20(Math.max.apply(null%2C%20arr))%3B%0A%20%20%20var%20scm%20%3D%200%3B%0A%20%20%20var%20x%20%3D%20true%3B%0A%20%20%20var%20newArray%20%3D%20%5B%5D%3B%0A%20%0A%20%20%20for(var%20i%20%3D%20smallest%3B%20i%20%3C%3D%20largest%3B%20i%2B%2B)%7B%0A%20%20%20%20newArray.push(i)%3B%0A%20%20%7D%0A%20%20%20%20while(x)%7B%0A%20%20%20%20%20%0A%20%20%20%20%20%20scm%2B%2B%3B%0A%20%20%20%20%20%20%0A%20%20%20%20for(var%20j%20%3D%20smallest%3B%20j%20%3C%3D%20newArray.length%3B%20j%2B%2B)%7B%0A%20%20%20%20%20%20%20%20if(scm%20%25%20j%20!%3D%3D%200)%7B%0A%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20else%20if%20(j%20%3D%3D%3D%20newArray.length)%7B%0A%20%20%20%20%20%20%20%20x%20%3D%20false%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%7D%20%0A%20%20%7D%0A%0A%20%20%0A%20%20%0A%20%20return%20scm%3B%0A%7D%0A%0A%0AsmallestCommons(%5B23%2C18%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function smallestCommons(arr) {
  var smallest = (Math.min.apply(null, arr));
  var largest = (Math.max.apply(null, arr));
   var scm = 0;
   var x = true;
   var newArray = [];
 
   for(var i = smallest; i <= largest; i++){
    newArray.push(i);
  }
    while(x){
     
      scm++;
      
    for(var j = smallest; j <= newArray.length; j++){
        if(scm % j !== 0){
          break;
        }
     else if (j === newArray.length){
        x = false;
      }
        
      } 
  }

  
  
  return scm;
}


smallestCommons([23,18]);

```

**Comment by DivaWeb** [comment]
I have passed all the test but the last one which tells me I could have an infinite loop. I have tested and made sure that my numbers being used are [ 18, 19, 20, 21, 22, 23 ] and that it is pulling the smallest and largest. And by the way I have tried the chat rooms and no luck getting an answer anywhere.

**Comment by raisedadead** [comment]
Refer https://github.com/freeCodeCamp/freeCodeCamp/issues/15079, please do not open duplicate issues. You can continue on the other thread instead.
