### ISSUE TITLE
Symmetric Difference - infinite loop in my code crashes page

### ISSUE THREAD

**Issue by Anja18** [freeCodeCamp/freeCodeCamp#15086]
Challenge [Symmetric Difference](https://www.freecodecamp.com/challenges/symmetric-difference) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30</code>.

Apparently I have created an infinite loop, which causes my page to crash everytime I go on it to try and finish the challenge… I can't change/erase my code because of this… Help?

**Comment by raisedadead** [comment]
Hi @Anja18 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
