### ISSUE TITLE
Challenge font and font size changes when refreshing or opening with direct link

### ISSUE THREAD

**Issue by ApCoder123** [freeCodeCamp/freeCodeCamp#15099]
#### Challenge Name

[Introduction to the React Challenges](http://beta.freecodecamp.com/en/challenges/react/introduction-to-the-react-challenges)

#### Issue Description

If you open the page from the map, you see a slightly different page to the page when you refresh it or open it from the link

When you open the page from the map you see this:
![image](https://cloud.githubusercontent.com/assets/20560218/26530569/3cdb62e8-43cf-11e7-81e6-240187776025.png)

But then, if you refresh the page, or open it from the challenge link, you see this:
![image](https://cloud.githubusercontent.com/assets/20560218/26530573/4d44a950-43cf-11e7-9169-9d86c53d78a7.png)

#### Browser Information

* Browser Name, Version: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36`
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

**Comment by xRahul** [comment]
The `<p>` tag with class `step-description` is encapsulating all the data in case of bigger font, while only one line is getting encapsulated in that class in case of smaller font. Need to find this component and update it.

**Comment by dhcodes** [comment]
This is the file: https://github.com/freeCodeCamp/freeCodeCamp/blob/f4443e16dd5afd01af51c8825794f9e3edc00499/common/app/routes/challenges/views/step/Step.jsx

I messed around a bit, but couldn't figure out what is causing it to render two different ways (the normal way and then the incorrect way on refresh).

**Comment by meda123** [comment]
Hi! Been a part of the community for a while and would to contribute. This would be my first PR (ever), may I claim this issue and work on it? Any tips/advice would be appreciate it.

**Comment by dhcodes** [comment]
@meda123 Yep, you're welcome to work on it. It seems to be something with how React is rendering the `dangerouslySetInnerHTML`. It works on the first load but not on reload. To make a PR once you've determined the issue, follow the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md)

**Comment by Double-A-92** [comment]
Can anybody reproduce this? Just tried it but it always looks the same.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
