### ISSUE TITLE
It says that h2 element should be blue. I'm sure the code is right!!

### ISSUE THREAD

**Issue by AminuSufi585** [freeCodeCamp/freeCodeCamp#15090]
Challenge [use-css-selectors-to-style-elements](http://beta.freecodecamp.com/en/challenges/basic-css/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 
![bug_report](https://cloud.githubusercontent.com/assets/17682302/26525086/f4b01404-4343-11e7-9244-99b59ed47d54.png)
Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html

<style>
  h2  {
    color: blue;
  }
</style>
<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

**Comment by AminuSufi585** [comment]
I hope the issue will be tackled soon, it is on the beta site. I'm just trying out the challenges again, and I suddenly discovered this bug.

**Comment by xRahul** [comment]
It's working in chrome. I'm now curious to know the reason for this not working in firefox.

**Comment by karissabob** [comment]
I have the same problem. Have tried resetting the code and refreshing the page. Header is definitely blue!

**Comment by AminuSufi585** [comment]
Exactly.. It's working just fine in chrome, but WHY NOT firefox. It is my favorite browser.

**Comment by gpp1234** [comment]
It's not working on Safari either.

**Comment by CMexpressIT** [comment]
Aren't still not working in both!!!

**Comment by systimotic** [comment]
Sorry for the trouble everyone, thanks for looking into this. We recently fixed this (https://github.com/freeCodeCamp/freeCodeCamp/pull/15775), so I'm closing this issue.
If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Happy coding!
