### ISSUE TITLE
tip club

### ISSUE THREAD

**Issue by nguyenhabit** [freeCodeCamp/freeCodeCamp#15095]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%0A%3Ch1%3EHello%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h1>Hello</h1>

```

**Comment by greencleanique** [comment]
It's not responding on my Nokia Lumia,928

**Comment by MiloATH** [comment]
As the challenge states, your h1 element should have the text "Hello World".
