### ISSUE TITLE
JQuery: test case not accepting

### ISSUE THREAD

**Issue by sandeeproy** [freeCodeCamp/freeCodeCamp#15093]
108:
Challenge: To change text of a button element using JQuery.
line that will be affected: `<button class="btn btn-default target" id="target4">#target4</button>`
line by which the action will be performed: `$("#target4").html("<em>JQuery Playground</em>")`;

Outcome: 3 test cases passed, 2 not.

Please review. 
screenShot here : https://cloud.githubusercontent.com/assets/15712812/26527301/8b1509d0-43ae-11e7-912d-8ecd273fa86c.png

**Comment by MiloATH** [comment]
Hi, you need to make sure the text is unchanged. Use the text `#target4` instead of `JQuery Playground`. i.e. `<em>#target4</em>`

**Comment by raisedadead** [comment]
@MiloATH thanks for your comments, but we strictly discourage any assistance on this issue tracker. Please provide all guidance in the chat room or the forum.

Hi @sandeeproy 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by MiloATH** [comment]
@raisedadead I am terribly sorry. I won't provide guidance in the issue tracker and will provide guidance in the chat rooms. I have noticed you use a specific response format for issues similar to this one and I will adopt that technique. Thank you for the feedback.

**Comment by raisedadead** [comment]
@MiloATH Hey, no apologies needed... we sincerely thank you for all your contributions and help in triaging the issues.

Cheers and happy coding!
