### ISSUE TITLE
Little problem with align

### ISSUE THREAD

**Issue by yurichep** [FreeCodeCamp/freecodecamp#1510]
Hello!
Just signed up in FCC 10 minutes ago, came to my profile and saw strange align of '10'
![2015-08-04 16 29 45](https://cloud.githubusercontent.com/assets/13643079/9061823/fcbb003c-3ac6-11e5-84da-5b6c74df7405.png)

Tried to find the same issue, but haven't succeed.

**Comment by BerkeleyTrue** [comment]
@yurichep Welcome!

I cannot replicate this issue. Can you give us more information on your machine?

**Comment by yurichep** [comment]
Sorry, my bad!

I have: 
MacBook Air 13 mid2013 1.3 GHz i5 4gb 
Os Yosemite 10.10.4
Safari 8.07 (10600.7.12)
System runs on Russian

**Comment by BerkeleyTrue** [comment]
Safari..... (-_-) I loathe you Safari.

Confirmed Safari does not like our css.

Any css experts out there want to tackle this one?

**Comment by royshouvik** [comment]
I am working on it, going to create a PR soon.
