### ISSUE TITLE
Escape Literal Quote String Challenge

### ISSUE THREAD

**Issue by ezkl37** [freeCodeCamp/freeCodeCamp#15102]
The challenge asks to store this string using the Escape Quotes method. I need to use 2 quotes and 4 (\*) in my code.

string: I am a "double quoted" string inside "double quotes".

My code:
```javascript

var myStr="I am a \"double quoted \" string inside \"double quotes\".";

The console prints "I am a "double quoted" string inside "double quotes". 
However I still cant complete the following challenge. 
Variable myStr should contain the string: I am a "double quoted" string inside "double quotes".





```

**Comment by raisedadead** [comment]
Hi @ezkl37 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
