### ISSUE TITLE
sng

### ISSUE THREAD

**Issue by snaigiux91** [freeCodeCamp/freeCodeCamp#15109]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%3Ch1%3EHello%20snaige%0A%3C%2Fh1%3E%0A%3Ch1%3EHello%20snaige%3C%2Fh1%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code: 
```html
<h1>Hello snaige
</h1>
<h1>Hello snaige</h1>
```

**Comment by snaigiux91** [comment]
hi

**Comment by xRahul** [comment]
@snaigiux91 What is the issue?
It says your h1 tags should have 

> "Hello World" instead of "Hello"

And you're writing `Hello snaige`. That's why it isn't getting passed.

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
