### ISSUE TITLE
style issue 

### ISSUE THREAD

**Issue by ccnsunl** [freeCodeCamp/freeCodeCamp#15107]
Challenge [Use a CSS Class to Style an Element](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%0A%3Cstyle%3E%0A%20%20%20h2%20%7Bcolor%3Ared%3B%0A%20%20%7D%20%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22.red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
   h2 {color:red;
  } 
</style>

<h2 class=".red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```
I was using a desktop I received help from chat and from reading similar issues on github, however no matter what I changed the problem persisted.   the challenge asks 

Your h2 element should be red.
Your h2 element should have the class red-text.
Your stylesheet should declare a red-text class and have its color set to red.
Do not use inline style declarations like style="color: red" in your h2 element.

my code 

<style>
   h2 {color:red;
  } 
</style>

<h2 class=".red-text">CatPhotoApp</h2>

Challenge Response : 
Your h2 element should be red. ==== Green 
Your h2 element should have the class red-text.  === X
Your stylesheet should declare a red-text class and have its color set to red. ==== X
Do not use inline style declarations like style="color: red" in your h2 element. ==== Green 

new code 
<style>
   h2 .red-text {color:red;
  } 
</style>

<h2 class=".red-text">CatPhotoApp</h2>

Challenge Response:

Your h2 element should be red. ==== X
Your h2 element should have the class red-text. ===== X
Your stylesheet should declare a red-text class and have its color set to red. ==== Green
Do not use inline style declarations like style="color: red" in your h2 element. ==== Green

**Comment by texas2010** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
