### ISSUE TITLE
CSS: Change Color Text - Single Quotes not working

### ISSUE THREAD

**Issue by JBallin** [freeCodeCamp/freeCodeCamp#15117]
Challenge [change-the-color-of-text](http://beta.freecodecamp.com/en/challenges/basic-css/change-the-color-of-text) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Using Beta.

First line: doesn't pass with single quote around `'color:red;'` but double quotes `"color:red;"` does pass.

As instructed, I first went to chat and was told that there's an issue with the testing software that doesn't accept single quotes. When asked for a link I was told to search the main FCC site, I looked at the FAQ and found nothing. I also searched the forums.

If this is in fact a known issue, then it should be made clear in the actual lessons. Up to this point I've used single quotes on the challenges and haven't had an issue.

```html


<h2 style='color:red;'>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

**Comment by dhcodes** [comment]
@JBallin Thanks for the issue. Opening this one for first-timers only. Change [this line](https://github.com/freeCodeCamp/freeCodeCamp/blob/802f9b2ddb5d2d912ff8bc2263d74e47691dd13e/seed/challenges/01-responsive-web-design/basic-css.json#L90)
from:
`"assert(code.match(/<h2\\s+style\\s*=\\s*\"\\s*color\\s*:\\s*(?:rgb\\(\\s*255\\s*,\\s*0\\s*,\\s*0\\s*\\)|rgb\\(\\s*100%\\s*,\\s*0%\\s*,\\s*0%\\s*\\)|red|#ff0000|#f00|hsl\\(\\s*0\\s*,\\s*100%\\s*,\\s*50%\\s*\\))\\s*\\;?\">\\s*CatPhotoApp\\s*<\\/h2>/), 'message: Your <code>h2</code> element should be red.');"`

to:
`"assert(code.match(/<h2\\s+style\\s*=\\s*(\'|\")\\s*color\\s*:\\s*(?:rgb\\(\\s*255\\s*,\\s*0\\s*,\\s*0\\s*\\)|rgb\\(\\s*100%\\s*,\\s*0%\\s*,\\s*0%\\s*\\)|red|#ff0000|#f00|hsl\\(\\s*0\\s*,\\s*100%\\s*,\\s*50%\\s*\\))\\s*\\;?(\'|\")>\\s*CatPhotoApp\\s*<\\/h2>/), 'message: Your <code>h2</code> element should be red.');"`

Please follow the guidelines on the [Contributing Wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) when submitting a pull request.

**Comment by chrisrymer** [comment]
I am going to work on this. Just going through your contribution guidelines. I am about 30% through them at the moment.

**Comment by JBallin** [comment]
@chrisrymer I actually submitted a PR, didn't see your comment till now. Sorry for not commenting that I was working on it!

**Comment by chrisrymer** [comment]
No problem.

**Comment by raisedadead** [comment]
This issue has to be closed when a pull request is made. Please check [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), for more details.

**Comment by JBallin** [comment]
Thanks @raisedadead, working on setting up/learning how to contribute PR's locally. Will handle this issue.

**Comment by chrisrymer** [comment]
There is a kicker to this little bug, `style="color: red;'` also passes.

**Comment by JBallin** [comment]
@chrisrymer So you ended up solving this one? I thought we agreed I would?

**Comment by chrisrymer** [comment]
Apologies, I saw the ticket get re-opened. I had already invested the time actually reading the docs and doing the work. So I sent my PR.

**Comment by JBallin** [comment]
And you did claim it first! Glad you figured it out. I'll find another bug.

**Comment by chrisrymer** [comment]
Sure, it wasn't quite straightforward. It took a fair bit of effort to get set up. Again, apologies for the confusion. Look for the first-timers-only labels. There is was another last night.

**Comment by raisedadead** [comment]
@chrisrymer Yes, we have so many issues that are tagged help wanted. You could take a look at those too. And reach us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), for any assistance.

Thanks for the PR.

Happy fixing!
