### ISSUE TITLE
Error: TypeError: 0 is read-only

### ISSUE THREAD

**Issue by iben1907** [freeCodeCamp/freeCodeCamp#15112]
"Challenge  Understand String Immutability" (JavaScript)

Hi guys,

I just got this Error (TypeError: 0 is read-only) every time I run the code. I tried restarting browser etc. but nothing worked for me.

Does anyone have an idea?

Regards
Iben

**Comment by xRahul** [comment]
You cannot change a single character in a js string.
You'd have to change the entire string to get your result.

This is not an issue

**Comment by iben1907** [comment]
Got it... thank you!
