### ISSUE TITLE
I think there is a bug in this exercise since whithout filtering anything this code works

### ISSUE THREAD

**Issue by shrey2711** [freeCodeCamp/freeCodeCamp#15116]
Challenge [Falsy Bouncer](https://www.freecodecamp.com/challenges/falsy-bouncer#?solution=%0Afunction%20bouncer(arr)%20%7B%0A%20%20%2F%2F%20Don't%20show%20a%20false%20ID%20to%20this%20bouncer.%0A%20%20return%20arr.filter(function(val)%7B%0A%20%20%20%20%0A%20%20%20%20%0A%20%20%20%20return%20val%3B%0A%20%20%20%20%0A%20%20%7D)%3B%0A%7D%0A%0Abouncer(%5B7%2C%20%22ate%22%2C%20%22%22%2C%20false%2C%209%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function bouncer(arr) {
  // Don't show a false ID to this bouncer.
  return arr.filter(function(val){
    
    
    return val;

should be return val!=false,"",0,......;
    
  });
}

bouncer([7, "ate", "", false, 9]);

```

**Comment by MiloATH** [comment]
Hi @shrey2711 

This is a feature of javascript! You can read more about it [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean).

Here are some next steps that you should follow before we can help you with your query:

* Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
* Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](https://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT**:
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by shrey2711** [comment]
Oh thanks I didn't knew that

**Comment by MiloATH** [comment]
Closed
