### ISSUE TITLE
Bonfire: Find the longest word in a String - should include a test with a word > 9 characters

### ISSUE THREAD

**Issue by rjorgenson** [FreeCodeCamp/freecodecamp#1511]
Just completed this challenge with the below solution which would fail if a word in a sentence had > 9 characters.

```
function findLongestWord(str) {
  words = str.split(" ");
  lengths = [];
  for (var word in words) {
    lengths.push(words[word].length);
  }
  lengths = lengths.sort();
  return(lengths[lengths.length - 1]);
}

findLongestWord('The quick brown fox jumped over the lazy dog');
```

**Comment by djordjelacmanovic** [comment]
I second this - sort() will sort them as strings (alphabetically) by default. 
There should be a comparator function passed to the sort method to make it compare them numerically, something like
```javascript
function (length1,length2) { 
        return length1 - length2;
}
```

**Comment by rjorgenson** [comment]
Well that was fast! Thanks =]

**Comment by djordjelacmanovic** [comment]
They havent accepted the pull request yet so you should probs keep this open :)

**Comment by rjorgenson** [comment]
I see, still new to how git works =]
