### ISSUE TITLE
Problem with loading the forum since I set italian interface

### ISSUE THREAD

**Issue by Francesdenaro** [freeCodeCamp/freeCodeCamp#15114]
#### Issue Description
I can't log in anymore with my account on free code camp forum after I selected Italian Interface in my preferences.
If I try to load the forum in an anonymous google chrome session it works.

#### Browser Information

Any device and any browser with which I try to log in.
* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Screenshot

![image](https://cloud.githubusercontent.com/assets/26060576/26552106/fd8ebbdc-4485-11e7-8ad3-bf8b4970b5f2.png)

**Comment by OFFLlNE** [comment]
@Francesdenaro thank you for reporting that issue.

I managed to reproduce this and thus cannot change back to english 😂

**Comment by Francesdenaro** [comment]
Hope I'll return on the forum asap, I miss it xD

2017-05-29 17:07 GMT+02:00 Lauri <notifications@github.com>:

**Comment by raisedadead** [comment]
Issue moved to [freeCodeCamp/discourse #38](https://github.com/freeCodeCamp/discourse/issues/38) via [**ZenHub**](https://www.zenhub.com/)
