### ISSUE TITLE
API not working 

### ISSUE THREAD

**Issue by mhdns** [freeCodeCamp/freeCodeCamp#15122]
tried this address, https://wind-bow.glitch.me/twitch-api/users?login=OgamingSC2, and other channels but i only get this message, "{"error":"forbidden","status":403,"msg":"unaccepted route: users - see https://wind-bow.gomix.me/ for infos"}"

Challenge [Use the Twitchtv JSON API](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by hobbycoder7** [comment]
Try https://wind-bow.glitch.me/twitch-api/users/OgamingSC2

**Comment by CharlesMarlow** [comment]
Hey mhdns, did you ever get that resolved?

**Comment by ananaymital** [comment]
@mhdns Please reply whether your issue was resolved so we can close this Issue.

**Comment by CharlesMarlow** [comment]
Yes, this was eventually resolved, thanks.

בתאריך 14 בספט׳ 2017 03:03,‏ "Ananay" <notifications@github.com> כתב:

**Comment by ananaymital** [comment]
@QuincyLarson @Bouncey I think we can close this issue now.

**Comment by QuincyLarson** [comment]
@hobbycoder7 @ananaymital Thanks for your help with this!
