### ISSUE TITLE
Hello Word

### ISSUE THREAD

**Issue by CMexpressIT** [freeCodeCamp/freeCodeCamp#15120]
Challenge [Say Hello to HTML Elements](https://www.freecodecamp.com/challenges/say-hello-to-html-elements#?solution=%3Ch1%3E%22Hello%20word%22%3C%2Fh1%3E%0A%3Ch1%3EHello%20word%3C%2Fh1%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>"Hello word"</h1>
<h1>Hello word</h1>

```

**Comment by Marmiz** [comment]
Hello @CMexpressIT thanks for reporting this issue.

You have an error in your code that's preventing you to proceed.
The challenge asks for:
>your h1 element's text to say "Hello **World**"

While the text you have implemented is not. (Mind the spelling).

----
Please consider that Github is a place for reporting bug and issues, next time please check in one of the official [chat room](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) and ask for assistance first.

happy coding 👍

**Comment by CMexpressIT** [comment]
Sorry. ✅

**Comment by Marmiz** [comment]
No need to apologize @CMexpressIT .

Hope you fixed your code, and remember for the future the flow:
`Read Search Ask`

Happy coding journey 👍

**Comment by erictleung** [comment]
Closing as resolved. Happy coding!
