### ISSUE TITLE
showing as err even with the correct code.

### ISSUE THREAD

**Issue by maheshareddy** [freeCodeCamp/freeCodeCamp#15125]
Challenge [Manipulate Arrays With unshift](https://www.freecodecamp.com/challenges/manipulate-arrays-with-unshift#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B%22Stimpson%22%2C%20%22J%22%2C%20%22cat%22%5D%3B%0AourArray.shift()%3B%20%2F%2F%20ourArray%20now%20equals%20%5B%22J%22%2C%20%22cat%22%5D%0AourArray.unshift(%22Happy%22)%3B%20%0A%2F%2F%20ourArray%20now%20equals%20%5B%22Happy%22%2C%20%22J%22%2C%20%22cat%22%5D%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B%5B%22John%22%2C%2023%5D%2C%20%5B%22dog%22%2C%203%5D%5D%3B%0AmyArray.shift()%3B%0AmyArray.unshift(%5B%22paul%22%2C%2035%5D)%3B%0A%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArray = ["Stimpson", "J", "cat"];
ourArray.shift(); // ourArray now equals ["J", "cat"]
ourArray.unshift("Happy"); 
// ourArray now equals ["Happy", "J", "cat"]

// Setup
var myArray = [["John", 23], ["dog", 3]];
myArray.shift();
myArray.unshift(["paul", 35]);


// Only change code below this line.



```

**Comment by chrisrymer** [comment]
@maheshareddy I think you need to change the last line to have a capital 'p' `myArray.unshift(["Paul", 35]);`

**Comment by Manish-Giri** [comment]
@maheshareddy The tests are case sensitive, so you need `Paul`, as has been pointed out.

In future, please visit the [Help Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) first for coding help.

**Comment by texas2010** [comment]
@maheshareddy, 
Thanks for reporting this. But you got the typo in the code. like @Manish-Giri say it.
These GitHub Issues are for reporting bugs on the freeCodeCamp website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
