### ISSUE TITLE
How to pass this challenge?

### ISSUE THREAD

**Issue by tangxu0717** [freeCodeCamp/freeCodeCamp#15132]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function palindrome(str) {
  // Good luck!
  str = str.toLowerCase();
  str = str.replace("_","");
  str = str.replace(" ","");
  str = str.replace(",","");
  str = str.replace(".","");
  str = str.replace("0","");
  str = str.replace("1","");
  str = str.replace("(","");
  str = str.replace(")","");
  str = str.replace("-","");
  str = str.replace(":","");
  str = str.replace("/","");
  str = str.replace("'\'","");
  str = str.replace("|",""); 
  var newStr = str.split("").reverse().join("");
  if(str===newStr){
    return true;
  }else{
    return false;
  }
}



palindrome("eye");

```

**Comment by danghv** [comment]
try these words: "___eye", "My age is 0, 0 si ega ym.". You will know why. Good luck!

**Comment by tangxu0717** [comment]
What's wrong with my code ?

**Comment by raisedadead** [comment]
Hi @tangxu0717 

Thanks for reporting this issue. But we cannot provide coding assistance on the issue tracker. Please proceed to the forum.

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by tangxu0717** [comment]
I have resolved this problem, thank you very much
