### ISSUE TITLE
The FCC Inventory Update wont let me go after i got the answer

### ISSUE THREAD

**Issue by trextozyne** [freeCodeCamp/freeCodeCamp#15135]
Challenge [Inventory Update](https://www.freecodecamp.com/challenges/inventory-update#?solution=var%20arrQty%20%3D%20%5B%5D%3B%0Avar%20arrItmName%20%3D%20%5B%5D%3B%20%0A%20%20%20%20%20%20%20%0Avar%20arr%20%3D%20%5B%5D%3B%0A%0Afunction%20updateInventory(arr1%2C%20arr2)%20%7B%0Acount%20%3D%200%3B%0A%20%20%20%20%2F%2F%20All%20inventory%20must%20be%20accounted%20for%20or%20you're%20fired!%20%0A%20%20%20%20%24.each(arr1%2C%20(arr1Key%2C%20arr1Val)%3D%3E%7B%20%0A%20%20%20%20%20arrQty.push(arr1Val%5B0%5D)%3B%0A%20%20%20%20%20arrItmName.push(arr1Val%5B1%5D)%3B%0A%20%20%20%20%7D)%3B%0A%20%20%20%20%0A%20%20%20%20%20%20%20%24.each(arr2%2C%20(arr2Key%2C%20arr2Val)%3D%3E%7B%20%0A%20%20%20%20%20%20%20%20%20%20if(%24.inArray(arr2Val%5B1%5D%2C%20arrItmName)%20%3D%3D%3D%20-1)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20arrQty.push(arr2Val%5B0%5D)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20arrItmName.push(arr2Val%5B1%5D)%3B%0A%20%20%20%20%20%20%20%20%20%20%7Delse%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20arrQty%5BarrItmName.indexOf(arr2Val%5B1%5D)%5D%20%3D%20arrQty%5BarrItmName.indexOf(arr2Val%5B1%5D)%5D%20%2B%20arr2Val%5B0%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%7D)%3B%0A%20%20%20%20%20%20%20for(var%20i%3D0%3B%20i%3CarrQty.length%3B%20i%2B%2B)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20var%20columns%20%3D%20%5B%5D%3B%0A%20%20%20%20%20%20%20%20%20%20for(var%20j%3D0%3B%20j%3CarrItmName.length%3B%20j%2B%2B)%7B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20columns%5B0%5D%20%3D%20arrQty%5Bcount%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20columns%5B1%5D%20%3D%20arrItmName%5Bcount%5D%3B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20break%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20arr.push(columns)%3B%0A%20%20%20%20%20%20%20%20count%2B%2B%3B%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20arr.sort(function(a%2C%20b)%7B%0A%20%20%20%20%20%20%20%20if(a%5B1%5D%20%3C%20b%5B1%5D)%20return%20-1%3B%0A%20%20%20%20%20%20%20%20if(a%5B1%5D%20%3E%20b%5B1%5D)%20return%201%3B%0A%20%20%20%20%20%20%20%20return%200%3B%0A%7D)%3B%0A%20%20%20%20return%20arr%3B%0A%7D%0A%0A%2F%2F%20Example%20inventory%20lists%0Avar%20curInv%20%3D%20%5B%0A%20%20%20%20%5B21%2C%20%22Bowling%20Ball%22%5D%2C%0A%20%20%20%20%5B2%2C%20%22Dirty%20Sock%22%5D%2C%0A%20%20%20%20%5B1%2C%20%22Hair%20Pin%22%5D%2C%0A%20%20%20%20%5B5%2C%20%22Microphone%22%5D%0A%5D%3B%0A%0Avar%20newInv%20%3D%20%5B%0A%20%20%20%20%5B2%2C%20%22Hair%20Pin%22%5D%2C%0A%20%20%20%20%5B3%2C%20%22Half-Eaten%20Apple%22%5D%2C%0A%20%20%20%20%5B67%2C%20%22Bowling%20Ball%22%5D%2C%0A%20%20%20%20%5B7%2C%20%22Toothpaste%22%5D%0A%5D%3B%0A%0AupdateInventory(curInv%2C%20newInv)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var arrQty = [];
var arrItmName = []; 
       
var arr = [];

function updateInventory(arr1, arr2) {
count = 0;
    // All inventory must be accounted for or you're fired! 
    $.each(arr1, (arr1Key, arr1Val)=>{ 
     arrQty.push(arr1Val[0]);
     arrItmName.push(arr1Val[1]);
    });
    
       $.each(arr2, (arr2Key, arr2Val)=>{ 
          if($.inArray(arr2Val[1], arrItmName) === -1){
              arrQty.push(arr2Val[0]);
              arrItmName.push(arr2Val[1]);
          }else{
              arrQty[arrItmName.indexOf(arr2Val[1])] = arrQty[arrItmName.indexOf(arr2Val[1])] + arr2Val[0];
          }
       });
       for(var i=0; i<arrQty.length; i++){
            var columns = [];
          for(var j=0; j<arrItmName.length; j++){ 
             columns[0] = arrQty[count];
            columns[1] = arrItmName[count]; 
            break;
        }
        arr.push(columns);
        count++;
       }
       arr.sort(function(a, b){
        if(a[1] < b[1]) return -1;
        if(a[1] > b[1]) return 1;
        return 0;
});
    return arr;
}

// Example inventory lists
var curInv = [
    [21, "Bowling Ball"],
    [2, "Dirty Sock"],
    [1, "Hair Pin"],
    [5, "Microphone"]
];

var newInv = [
    [2, "Hair Pin"],
    [3, "Half-Eaten Apple"],
    [67, "Bowling Ball"],
    [7, "Toothpaste"]
];

updateInventory(curInv, newInv);

```

**Comment by raisedadead** [comment]
Hi @trextozyne 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
