### ISSUE TITLE
Word blanks exercise under Basic JS have a small bug

### ISSUE THREAD

**Issue by nikhilprabhakar** [freeCodeCamp/freeCodeCamp#15137]
Challenge [Word Blanks](https://www.freecodecamp.com/challenges/word-blanks#?solution=%0Afunction%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20%0A%0A%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22dog%22%2C%20%22big%22%2C%20%22ran%22%2C%20%22quickly%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "";
  // Your code below this line
  

  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```

The `var result = "";` should be inside ` // Your code below this line` and `// Your code above this line`

like this 👇 :
```
// Your code below this line

var result = "";

// Your code above this line

```

Instead this is showing up as  👉   [like this](https://www.freecodecamp.com/challenges/word-blanks#?solution=%0Afunction%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20%0A%0A%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22dog%22%2C%20%22big%22%2C%20%22ran%22%2C%20%22quickly%22)%3B%0A).

This can be very misleading for new coders like me as I/we think of not having to change `var result = "";` but do something else. This exercise is actually otherwise an easy exercise.

This issue also could be related to [#14630](https://github.com/freeCodeCamp/freeCodeCamp/issues/14630). Opened a new ticket as that was tagged `beta`.

PS: There is no mentioning on whom to tag when reporting an issue. It would be great if you guys could mention a person to tag to each ticket.

**Comment by raisedadead** [comment]
Hi @nikhilprabhakar  

Well IMHO this can be considered bike-shedding because it's somewhat the point of figuring out what to do.

Nevertheless, let's update the challenge considering this is for new campers getting confused rather. Thanks for reporting.

> PS: There is no mentioning on whom to tag when reporting an issue. It would be great if you guys could mention a person to tag to each ticket.

That's not required, someone from the team monitors the issue tracker and does the triage.

Happy Coding!

**Comment by raisedadead** [comment]
@JBallin Want to take a dig at this?

**Comment by nikhilprabhakar** [comment]
> That's not required, someone from the team monitors the issue tracker and does the triage.

I was about to comment on the old issue related to this 👉  [#14630](https://github.com/freeCodeCamp/freeCodeCamp/issues/14630). I was not sure if you guys get notified or not if I just comment on it which is why I created a new ticket. Which is why asked for a name to tag. Anyways, glad it acknowledged @raisedadead 👍

**Comment by jonathanihm** [comment]
I haven't done a PR yet, I would like to do it if no one else wants to

**Comment by raisedadead** [comment]
@jonathanihm sure go ahead. It's always the one who opens up a valid PR, here are the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by JBallin** [comment]
1. **#14630 != related, you were right to open a new issue:**
    - Beta != production FCC
    - Output bug != template code issue

2. **You're not supposed to change the variable declaration, only the `your code here` as instructed**:

    - [From JS Hoisting (w3):](https://www.w3schools.com/js/js_hoisting.asp)

> **Declare Your Variables At the Top !**
>
> Hoisting is (to many developers) an unknown or overlooked behavior of JavaScript. If a developer doesn't understand hoisting, programs may contain bugs (errors). To avoid bugs, always declare all variables at the beginning of every scope. Since this is how JavaScript interprets the code, it is always a good rule.

>JavaScript in strict mode does not allow variables to be used if they are not declared.

```javascript
function foo() {
  var result = "bar"
}
```
becomes the following when run:

```javascript
function foo() {
  var result
  result = "bar"
}
```
writing your code this way is more clear!

  - Yes, you can declare `var result` directly in `your code here` which makes the initial declaration unnecessary but beginners who may not fully understand how hoisting works - you need to train yourself to understand that variables are hoisted at the top of their [scope](https://www.w3schools.com/js/js_scope.asp)
  - #14630 actually has a solution that uses the template correctly where it references `result` within the `your code here` section. What's wrong with that solution?

3. **The current template maximizes clarity**:

    - Author wanted to declare `var result` as a string (`=''`) for clarity/hand holding. What your suggesting is unclear - when it says `your code here` that means that it's all YOUR CODE, not something provided in the template that you are supposed to edit

---

@jonathanihm what changes do you plan to propose exactly?

**Comment by jonathanihm** [comment]
Hey @JBallin,

Thanks for the input!  I opened a PR to move the line in between the comments.  A user would then be able to either declare an initial value or reassign result, it wouldn't matter.  I see what you are saying with the previous issue, and if we want to stay consistent and leave things how they are, we can revert the changes and add additional instructions to state that they will need to assign a new value to give users better direction (it doesn't state that we should reassign or leave the initial value alone, we could say it more verbosely in the instructions).

Please let me know!

**Comment by JBallin** [comment]
@jonathanihm I think that both suggestions create too much hand holding. 

What are your thoughts on briefly explaining hoisting in the description? I think this is a [good habit](https://stackoverflow.com/questions/2485423/is-using-var-to-declare-variables-optional) to start building early on.

> It is recommended to declare your variables at the top of your function before you use them:
 
```javascript
function foo(){
  // declare variable myName as a string
  var myName = ""

  myName = "Quincy"
}
```

**Comment by raisedadead** [comment]
I was under the impression that this would go off into a long discussion, early on... 😅 !

Nevertheless, the reason we would want to make the change as proposed by the opening post and the PR are:

1. At this point in the curriculum, the campers are mostly unaware of what a function is and does (basically they aren't aware how scopes work).
2. They will get to know this after about 10-15 more challenges, until which they are expected to get familiar with basics, in this case playing with strings.
3. freeCodeCamp's focus at this stage is completely centered on teaching the basic concepts and introductions.

That said we aren't rejecting or ignoring any of the best practices, the only thing being they would be taken up in the video tutorials, and the wiki resources.

Simply, speaking, we are keeping things as simple and bare as possible for people to get started and not be 100% spec proof.

I honestly thank you for the feedback, but the concerns you have raised are completely valid and understood. Only thing is the format of the challenges with regards to this issue is not the place.

They can be taken in the video series, where best practices are taken assuming, people have basic understanding.

The opening poster's confusion is very valid at this point.

**Comment by jonathanihm** [comment]
I definitely agree, we do want our coders to be learning best practices and code well- just how early on this lesson comes is of some concern.

Thanks all!
