### ISSUE TITLE
Between the style tags, give the p elements font-size of 16px. Browser and Text zoom should be at 100%

### ISSUE THREAD

**Issue by SanPio24** [freeCodeCamp/freeCodeCamp#15141]
<style>
  .red-text {
    color: red;
  }
  h1{
font-size: 16px;
  }
</style>
h1 {
font-size: 16px;
}
<h2 class="red-text">CatPhotoApp</h2>
<p 
   h1 {
   font-size: 16px;
   }
   class= "red-text"> 
   </p>
 <p h1 {
  font-size: 16px;
  }
  >Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p   h1 {
   font-size: 16px;
   }
   >Purr jump eat the grass rip the couch scratchedd sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. </p>

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment]
Hi @SanPio24 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
