### ISSUE TITLE
doesn't test for "row" class, also instructions have critical typo

### ISSUE THREAD

**Issue by benflinn** [FreeCodeCamp/FreeCodeCamp#1515]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

1. the "Your div element should have the class "row"" test doesn't test for the "row" class

2. the instructions say "To get started, we should nest all of our HTML in a div element with the class "fluid-container"."
-it should be "container-fluid", took me ten minutes to figure out why it wouldn't let me pass.

**Comment by bugron** [comment]
It seems this issue is fixed.

**Comment by BerkeleyTrue** [comment]
@bugron Thanks!
