### ISSUE TITLE
I am stuck at this challenge TypeError .indexOf() is not a function

### ISSUE THREAD

**Issue by D3V4N5H** [freeCodeCamp/freeCodeCamp#15158]
Someone at least share a passable code

Challenge [Mutations](https://www.freecodecamp.com/challenges/mutations#?solution=function%20mutation(arr)%20%7B%0A%20%20var%20firstArray%3Darr%5B0%5D.toLowerCase%3B%0A%20%20var%20secondArray%3Darr%5B1%5D.toLowerCase%3B%0A%0A%20%20var%20indexstatus%3D0%2Ci%3D0%2CisFirstArrayInsideSecond%3D0%2CisSecondArrayInsideFirst%3D0%3B%0A%0A%20%20while(indexstatus%3E-1)%7Bindexstatus%3DsecondArray.indexOf(firstArray%5Bi%5D)%3Bi%2B%2B%3B%7D%0A%0A%20%20if(indexstatus%3C0)isFirstArrayInsideSecond%3D1%3B%0A%0A%20%20i%3D0%3Bindexstatus%3D0%3B%0A%0A%20%20while(indexstatus%3E-1)%7Bindexstatus%3DfirstArray.indexOf(secondArray%5Bi%5D)%3Bi%2B%2B%3B%7D%0A%0A%20%20if(indexstatus%3C0)isSecondArrayInsideFirst%3D1%3B%0A%0A%20%20if(isFirstArrayInsideSecond%3D%3D1%7C%7CisSecondArrayInsideFirst%3D%3D1)%20return%20true%3B%0A%20%20else%20return%20false%3B%0A%7D%0Amutation(%5B%22hello%22%2C%20%22hey%22%5D)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function mutation(arr) {
  var firstArray=arr[0].toLowerCase;
  var secondArray=arr[1].toLowerCase;

  var indexstatus=0,i=0,isFirstArrayInsideSecond=0,isSecondArrayInsideFirst=0;

  while(indexstatus>-1){indexstatus=secondArray.indexOf(firstArray[i]);i++;}

  if(indexstatus<0)isFirstArrayInsideSecond=1;

  i=0;indexstatus=0;

  while(indexstatus>-1){indexstatus=firstArray.indexOf(secondArray[i]);i++;}

  if(indexstatus<0)isSecondArrayInsideFirst=1;

  if(isFirstArrayInsideSecond==1||isSecondArrayInsideFirst==1) return true;
  else return false;
}
mutation(["hello", "hey"]);
```

**Comment by jonathanihm** [comment]
Hey there,

When you declare the firstArray and secondArray, you are using toLowerCase without parenthesis.  This will end up assigning your variables as the actual functions instead of calling them on the array elements.  This should clear up and you can keep on working on this!

Cheers!

**Comment by raisedadead** [comment]
Hi @D3V4N5H 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
