### ISSUE TITLE
Does not work with mac/chrome

### ISSUE THREAD

**Issue by v786** [freeCodeCamp/freeCodeCamp#15151]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment]
Hi @v786 

Please fill the issue template that was presented to you. It would be difficult for us to help without knowing what is the issue.

If you need assistance in reporting an issue then please reach out to the chat room:
[Help Chat Room](https://gitter.im/FreeCodeCamp/Help).

Thanks, and happy coding!
