### ISSUE TITLE
Bug found

### ISSUE THREAD

**Issue by aditidankar** [freeCodeCamp/freeCodeCamp#15165]
```html
<style>
 .red-text {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

The code doesn't change the colour of h2 to read when solving this challenge on the phone, however the code works while solving the same question on a computer. There is a problem with the code running on the phone.

**Comment by jamuhuri** [comment]
Can you post how you have defined the class .red-text in h2 tag? Why Do you have that extra space on color inline css?

**Comment by raisedadead** [comment]
Hi, this is a known issue with some mobile devices and browsers on them. Unfortunately, we are unable to resolve this at the moment as we are focused on the beta website.

We strongly recommend using desktop browsers. 

If you still would like to continue on a mobile browser, please check that deleting the spaces in the code and adding them again sometimes resolves this.

Thanks, and we regret the inconvenience.

Happy coding!
