### ISSUE TITLE
stuck on submit button

### ISSUE THREAD

**Issue by coldcoke** [freeCodeCamp/freeCodeCamp#15163]
#### Challenge Name

The challenge is the platform (when submitting) and not a specific challenge 
on the platform

#### Issue Description

After every challenge having clicked the submit button. The platform rarely
transitions to the next challenge

#### Browser Information

* Browser Name, Version:  Mozilla Firefox, 53.0.2 (64 bit)
* Operating System: Fedora Linux
* Mobile, Desktop, or Tablet: Desktop

* Browser Name, Version:  Google Chrome, 58.0.3029.110(64 bit)
* Operating System: Fedora Linux
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```
#### Screenshot

![image](https://cloud.githubusercontent.com/assets/18445511/26698684/916d3374-471f-11e7-9e51-bde379d83396.png)

**Comment by raisedadead** [comment]
Hi, can you try in an incognito window with all add-ons disabled? Some add-ons like ad blockers have been known to cause issues.

Also if possible can you share the screenshots of the developer console (Press F12) and check the console tab.

**Comment by raisedadead** [comment]
Please revert if this is still an issue.

**Comment by coldcoke** [comment]
Sorry I haven't had internet for the past 3 days. Working to get service from another provider. 

I will gladly give back proper feedback about the thread I started once I get back online, for now am on forced leave from ‘freeCodeCamp’
 😪 

Kindly note that working Incognito didn't resolve the problem. Will try again once am connected

Regards
