### ISSUE TITLE
Challenge Nest an Anchor Element within a Paragraph

### ISSUE THREAD

**Issue by DriftingPandaa** [freeCodeCamp/freeCodeCamp#15166]
![screenshot 2017-06-01 at 3 02 16 pm](https://cloud.githubusercontent.com/assets/29084032/26702829/9f71638a-46db-11e7-953d-b715a9364942.png)
It's not letting me complete the challenge! I'm 99.9% sure this is the correct code.

**Comment by jamuhuri** [comment]
Try close the paragraph tag after the img tag such that the paragraph view more ends after the mage. Good luck!

**Comment by raisedadead** [comment]
Hi @DriftingPandaa 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by nizarhaddaji** [comment]
I did a copy/paste of the whole code to atom editor and it works, so why not on this challenge ???

**Comment by bjornpit** [comment]
It needs to be http://www.freecatphotoapp.com

You forgot www.
