### ISSUE TITLE
Bad recursive solution crashes the app

### ISSUE THREAD

**Issue by katreinhart** [freeCodeCamp/freeCodeCamp#15169]
#### Challenge Name
https://www.freecodecamp.com/challenges/factorialize-a-number

#### Issue Description
A bad recursive solution completely crashes the browser window. Since the state is saved across sessions, the problem does not go away by closing & reopening browser windows or sessions. 

#### Browser Information

* Browser Name, Version: Safari 10.11.1
* Operating System: Mac OS El Capitan
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
function factorialize(num) {
  if (num === 1) return 1;
  return factorialize(num * num-1); // should be return num * factorialize(num-1); silly mistake!!
}

factorialize(5);


```

**Comment by Marmiz** [comment]
Dear @katreinhart thanks for reporting this issue.

As already mentioned in various thread before, FCC has a way to disable the code auto-run.
Everything should be explained in this blog post:
https://forum.freecodecamp.com/t/free-code-camp-infinite-loop-protection/19550

In short all you have to do is add `run=disabled` in your URL.

Happy coding 👍

**Comment by dhcodes** [comment]
Thanks @Marmiz . Closing as resolved.
