### ISSUE TITLE
Make dead link using the hash tag symbol

### ISSUE THREAD

**Issue by Mwgunner22** [freeCodeCamp/freeCodeCamp#15162]
<p> The challenge name is " Make dead links using the hash tag symbol" 

<p> this issue keeps happening even after I shut down and reboot my computer and have clear my cache or whatever its called (the crtl F5) and that seems to not work either. I'm open to any ideas on how I can fix this or get past this particular lesson, because I have now been stuck on this lesson for 2 full days.</p>

#### Browser Information
<p> having issues getting past the make a dead link using a hash tag or # and I have google searched the problem and have posted on multiple forms, but I'm 99% sure its a bug. </p>
 internet explorer,
 ASUS computer,
 laptop

The line of code I'm having trouble with is line 32.
![coding problem 1 date June 1 2017](https://cloud.githubusercontent.com/assets/28991144/26696956/5b413020-46c5-11e7-91f8-50eb02eb1e5b.PNG)

**Comment by Mwgunner22** [comment]
If anyone knows a way to help me either get it right or to somehow skip it and then see what my mistake was on the next screen that would help me a lot! I'm eager to learn coding, but having a rocky start. 
Thanks for everyone's help!

**Comment by dhcodes** [comment]
@Mwgunner22 you have a typo in your code. `herf` should be `href`. In the future, consider askign for help in the chat room as the issues board is for bugs with the site. Others in the chat room can help confirm there is indeed a bug.

**Comment by Mwgunner22** [comment]
Thanks so much! can't believe I didn't notice that.
