### ISSUE TITLE
Problem is resolved

### ISSUE THREAD

**Issue by wilfredinni** [freeCodeCamp/freeCodeCamp#15179]
Challenge [Chaining If Else Statements](https://www.freecodecamp.com/challenges/chaining-if-else-statements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

the problem is resolved 

My code:

*removed solution by mod*

**Comment by PedroCSilva** [comment]
Just to make sure: did you solve the issue?

**Comment by texas2010** [comment]
@wilfredinni, do not use the issue for show your solution code.
These GitHub Issues are for reporting bugs on the freeCodeCamp website only.

Happy coding.

**Comment by texas2010** [comment]
@dhcodes Oh, odd. I did close this. but thank you!
