### ISSUE TITLE
import keyword not working! Challenge [Understand-the-differences-between-import-and-require]

### ISSUE THREAD

**Issue by IshtmeetSinghRissam** [freeCodeCamp/freeCodeCamp#15175]
Challenge [understand-the-differences-between-import-and-require](http://beta.freecodecamp.com/en/challenges/es6/understand-the-differences-between-import-and-require) has an issue.
```js

import {capitalizeString} from "string_functions";
capitalizeString("hello!");

```
It returns an error "require is not defined".

**Comment by IshtmeetSinghRissam** [comment]
![image](https://cloud.githubusercontent.com/assets/29104610/26734448/a372fb3c-47db-11e7-9987-bc86954cfaa0.png)

**Comment by PedroCSilva** [comment]
May be related to https://github.com/freeCodeCamp/freeCodeCamp/issues/15089.

**Comment by systimotic** [comment]
Hi everybody! Thanks for reporting and looking into this issue.

We're working on fixing the ES6 challenges in https://github.com/freeCodeCamp/freeCodeCamp/issues/12698. I'm closing this issue in favor of that.

Happy coding!

**Comment by systimotic** [comment]
Hi everybody! Thanks for reporting and looking into this issue.

We're working on fixing the ES6 challenges in https://github.com/freeCodeCamp/freeCodeCamp/issues/12698. I'm closing this issue in favor of that.

Happy coding!
