### ISSUE TITLE
Image in instructions does not exist

### ISSUE THREAD

**Issue by orygreg** [freeCodeCamp/freeCodeCamp#15181]
Challenge [Use the Bootstrap Grid to Put Elements Side By Side](https://www.freecodecamp.com/challenges/use-the-bootstrap-grid-to-put-elements-side-by-side) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The problem has nothing to do with the code in middle-pane of page.  It's the link to the image in left-hand instructions pane, which points to... https://i.imgur.com/FaYuui8.png.  This image file does not exist.  This also happened in a few of the earlier lessons too, but I didn't keep track.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text text-center">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>

  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">
  <button class="btn btn-block btn-primary">Like</button>
  <button class="btn btn-block btn-info">Info</button>
  <button class="btn btn-block btn-danger">Delete</button>
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

```

**Comment by PedroCSilva** [comment]
When you say "it doesn't exist" you mean clicking the link and getting some error?

It's working fine for me.

**Comment by orygreg** [comment]
When I click it, a white pop-up appears with a spinning gif (?) - no picture.  If I right-click the link and choose "Open link in new tab", the page says "This i.imgur.com page can’t be found" and "No webpage was found for the web address: https://i.imgur.com/FaYuui8.png" and "HTTP ERROR 404".  No change when I click the "Reload" button that google provides.  Maybe you have the image in your cache??  If you do Ctrl+F5, does the link still work for you?

**Comment by PedroCSilva** [comment]
No issue whatsoever. 👍

**Comment by orygreg** [comment]
Solved... it's something my company is preventing access.  I'm doing all this from work laptop and the image URL fails in all my browsers.  For kicks, I manually I entered the link from my smartphone - and of course the link is fine.  For some reason, that site/domain is getting blocked.  THANK YOU for looking into this for me! :+1:
