### ISSUE TITLE
manipulating arrays with shift

### ISSUE THREAD

**Issue by eaglecookie** [FreeCodeCamp/FreeCodeCamp#1518]
Challenge http://beta.freecodecamp.com/challenges/manipulating-arrays-with-shift has an issue.

I'm not sure if the directions are unclear, or if there is a mistake, or if I'm just not understanding; but I have entered this code:
var myArray = ['John', 23, ['dog', 3]];
var removed = myArray.shift();

which is followed by the comment:
//This should be ['John'] and myArray should now be ['John', 23]

Shouldn't myArray be [23, ['dog', 3] now?

And the code I entered removes John, but the RED X says it doesn't.

**Comment by pieterdeville** [comment]
I've also encountered this. 

Hi I'm trying to solve beta: "Javascript - Manipulating Arrays With shift()"
my code is:
```
var myArray = ['John', 23, ['dog', 3]];
var removed = myArray.shift();
//console.log(typeof(removed));

//This should be ['John'] and myArray should now be ['John', 23]


(function(y, z){return('myArray = ' + JSON.stringify(y) + ' & removed = ' + JSON.stringify(z) /* + ' ' + typeof(z) */);})(myArray, removed);
```
The first validation is correct, but the second is not, if I check the validation there is a section which checks if
<blockquote>assert((function(d){if(d === 'John' && typeof(removed) === 'function'){return(true);}else{return(false);}})(removed), 'Removed should contain "John"'); </blockquote>

Shouldn't this check if removed is a 'string'? If I perform a `typeof(removed)` I get a `string` value. I don't know how and if I should make removed a function.

<img width="1280" alt="screen shot 2015-08-05 at 16 02 21" src="https://cloud.githubusercontent.com/assets/13466453/9087470/2ea63ca0-3b8b-11e5-97ad-59f502a7f310.PNG">

**Comment by sonorangirl** [comment]
Also the instructions for this task has as small typo, should be 'performing'.
