### ISSUE TITLE
problem comes resolved

### ISSUE THREAD

**Issue by wilfredinni** [freeCodeCamp/freeCodeCamp#15182]
Challenge [Selecting from many options with Switch Statements](https://www.freecodecamp.com/challenges/selecting-from-many-options-with-switch-statements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:

*removed solution by mod*

**Comment by texas2010** [comment]
@wilfredinni, do not use the issue for show your solution code on the freecodecamp issue.
These GitHub Issues are for reporting bugs on the freeCodeCamp website only.

Happy coding.
