### ISSUE TITLE
phoneticLookup("") prints undefined to the console, but is still marked wrong

### ISSUE THREAD

**Issue by vonbrocke** [freeCodeCamp/freeCodeCamp#15194]
![captura de pantalla 2017-06-03 a la s 7 54 03 pm](https://cloud.githubusercontent.com/assets/13283890/26755842/7d9046f2-4896-11e7-947a-af8248d54715.png)
Challenge [Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%0A%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0A%20%20var%20lookup%20%3D%20%7B%0A%20%20%20%20alpha%3A%20%22Adams%22%2C%0A%20%20%20%20bravo%3A%20%22Boston%22%2C%0A%20%20%20%20charlie%3A%20%22Chicago%22%2C%0A%20%20%20%20delta%3A%20%22Denver%22%2C%0A%20%20%20%20echo%3A%20%22Easy%22%2C%0A%20%20%20%20foxtrot%3A%20%22Frank%22%0A%20%20%7D%3B%0A%20%20%0A%20%20result%20%2B%3D%20lookup%5Bval%5D%3B%0A%20%20%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  var lookup = {
    alpha: "Adams",
    bravo: "Boston",
    charlie: "Chicago",
    delta: "Denver",
    echo: "Easy",
    foxtrot: "Frank"
  };
  
  result += lookup[val];
  

  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("");

```

**Comment by ivancsicsmarkus** [comment]
Your code is not good. 

You are returning ```""+undefined```, it equals to ```"undefined"```, but it asked you to return ```undefined```.

**Comment by vonbrocke** [comment]
@ivancsicsmarkus Thank you Markus. I found the error. I mistakenly concatenated the result to the empty variable. It should not be 'result += lookup[val]' but 'result = lookup[val]'.
