### ISSUE TITLE
Simple Change Color to Red for H2 Element... Element is Red, but no credit given when run is clicked

### ISSUE THREAD

**Issue by M-C-Haker** [freeCodeCamp/freeCodeCamp#15199]
Challenge [Change the Color of Text](https://www.freecodecamp.com/challenges/change-the-color-of-text#?solution=%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3Ch2%20style%3D%22color%3A%20red%22%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<h2>CatPhotoApp</h2>
<h2 style="color: red">CatPhotoApp</h2>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

![capture](https://cloud.githubusercontent.com/assets/29156145/26757941/8a2d99da-4893-11e7-93d2-351bf361e73b.PNG)

**Comment by ScarlettKitsune** [comment]
I'm also having this issue but i only have 1 h2 instead of 2. See line 2 and 3 above.

**Comment by M-C-Haker** [comment]
@ScarlettKitsune I believe my duplicate h2 was part of the problem, i reset the code and started fresh and had no problem getting it. I would make sure you you are using the ":" instead of "=" to assign the style red, as that seems to be a common issue.

**Comment by DBrottlund** [comment]
@ScarlettKitsune I would say that the freecodecamp web app is parsing this out as incorrect because it sees two h2 tags with the same txt but one is formatted incorrectly. if you still having an issue with the single h2 tag, post your actual code. We'll take a look.

**Comment by ScarlettKitsune** [comment]
You are right it was formatted incorrectly. I just didn't notice until the 100th time looking over it to see what I did wrong. lol I can't wait until I know more so that I will recognize mistakes more easily.

**Comment by ScarlettKitsune** [comment]
@M-C-Haker @DBrottlund  Thank you guys for your help!
