### ISSUE TITLE
Failing delete tests for Record Collection

### ISSUE THREAD

**Issue by natac13** [freeCodeCamp/freeCodeCamp#15193]
Challenge [Record Collection](https://www.freecodecamp.com/challenges/record-collection#?solution=%0A%2F%2F%20Setup%0Avar%20collection%20%3D%20%7B%0A%20%20%20%20%222548%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%22Slippery%20When%20Wet%22%2C%0A%20%20%20%20%20%20%22artist%22%3A%20%22Bon%20Jovi%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%22Let%20It%20Rock%22%2C%20%0A%20%20%20%20%20%20%20%20%22You%20Give%20Love%20a%20Bad%20Name%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%222468%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%221999%22%2C%0A%20%20%20%20%20%20%22artist%22%3A%20%22Prince%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%0A%20%20%20%20%20%20%20%20%221999%22%2C%20%0A%20%20%20%20%20%20%20%20%22Little%20Red%20Corvette%22%20%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%221245%22%3A%20%7B%0A%20%20%20%20%20%20%22artist%22%3A%20%22Robert%20Palmer%22%2C%0A%20%20%20%20%20%20%22tracks%22%3A%20%5B%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20%225439%22%3A%20%7B%0A%20%20%20%20%20%20%22album%22%3A%20%22ABBA%20Gold%22%0A%20%20%20%20%7D%0A%7D%3B%0A%2F%2F%20Keep%20a%20copy%20of%20the%20collection%20for%20tests%0Avar%20collectionCopy%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0Afunction%20updateRecords(id%2C%20prop%2C%20value)%20%7B%0A%20%20var%20newCollection%20%3D%20JSON.parse(JSON.stringify(collection))%3B%0A%20%20%0A%20%20%0A%20%20if(prop%20!%3D%3D%20'tracks'%20%26%26%20value%20!%3D%3D%20'')%20%7B%0A%20%20%20%20newCollection%5Bid%5D%5Bprop%5D%20%3D%20value%3B%0A%20%20%7D%0A%20%20%0A%20%20if(prop%20%3D%3D%3D%20'tracks'%20%26%26%20newCollection%5Bid%5D.hasOwnProperty(prop)%20%3D%3D%3D%20false)%20%7B%0A%20%20%20%20newCollection%5Bid%5D%5Bprop%5D%20%3D%20%5B%5D%3B%0A%20%20%20%20newCollection%5Bid%5D%5Bprop%5D.push(value)%3B%0A%20%20%7D%0A%20%20%0A%20%20if%20(prop%20%3D%3D%3D%20'tracks'%20%26%26%20value%20!%3D%3D%20'')%20%7B%0A%20%20%20%20newCollection%5Bid%5D%5Bprop%5D.push(value)%3B%0A%20%20%7D%0A%20%20%0A%20%20if(value%20%3D%3D%3D%20'')%20%7B%0A%20%20%20%20console.log(1%2C%20id%2C%20prop%2C%20value)%3B%0A%20%20%20%20delete%20newCollection%5Bid%5D%5Bprop%5D%3B%0A%20%20%20%20console.log(newCollection)%0A%20%20%7D%0A%20%20%0A%20%20return%20newCollection%3B%0A%7D%0A%0A%2F%2F%20Alter%20values%20below%20to%20test%20your%20code%0AupdateRecords(2548%2C%20%22tracks%22%2C%20%22%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  var newCollection = JSON.parse(JSON.stringify(collection));
  
  
  if(prop !== 'tracks' && value !== '') {
    newCollection[id][prop] = value;
  }
  
  if(prop === 'tracks' && newCollection[id].hasOwnProperty(prop) === false) {
    newCollection[id][prop] = [];
    newCollection[id][prop].push(value);
  }
  
  if (prop === 'tracks' && value !== '') {
    newCollection[id][prop].push(value);
  }
  
  if(value === '') {


    console.log(1, id, prop, value);
    delete newCollection[id][prop];
    console.log(newCollection)
  }
  
  return newCollection;
}

// Alter values below to test your code
updateRecords(2548, "tracks", "");


```
So I am wondering why I am still failing the test to delete the records after seeing the property gone when I console.log the output. I have provided a screen shot to show this. 
I have logged to the console the id, prop and value then I have logged the updated object which show the prop deleted from the object. Leaving me quite confused.

Fyi, all other test pass.

![fccerror](https://cloud.githubusercontent.com/assets/10660283/26755680/89734914-4860-11e7-8565-0d74f74bf7bf.png)

**Comment by jonathanihm** [comment]
Did a few tests and reset, realized that you are creating a newCollection object.  Although technically correct, the reason its failing is because we are doing direct tests on the collection object; we should be returning the existing altered collection and not a copy (though we may want to explicitly say this in the instructions)
