### ISSUE TITLE
Beta: Name of the challenge missing in a map.

### ISSUE THREAD

**Issue by IshtmeetSinghRissam** [freeCodeCamp/freeCodeCamp#15192]
I've often seen this issue, while opening the map, I am not able to see the recent completed challenge on the map. Maybe it's an issue to look on?
![image](https://cloud.githubusercontent.com/assets/29104610/26755668/e06f7e0a-48af-11e7-8f9b-fd73bf282a51.png)

**Comment by jonathanihm** [comment]
Relates to #14949

**Comment by moaz-eldefrawy** [comment]
Hello, 
this my first time contributing to open-source, so sorry if I made any mistakes.

I have checked the source code. It's not a css or js problem. The text hasn't been written. 

![delete](https://user-images.githubusercontent.com/24529552/26854950-ca12216a-4b18-11e7-911a-9e42fe189a5f.jpg)

**Comment by raisedadead** [comment]
@moaz-eldefrawy Thanks, and yes @jonathanihm you are correct. Closing this as a duplicate
