### ISSUE TITLE
Local Scope and Functions Issue

### ISSUE THREAD

**Issue by AndroidHitchhiking** [freeCodeCamp/freeCodeCamp#15209]
Challenge [Local Scope and Functions](https://www.freecodecamp.com/challenges/local-scope-and-functions#?solution=%0A%20var%20myVar%3B%0Afunction%20myLocalScope()%20%7B%0A%20%20'use%20strict'%3B%0A%20%20%0A%20%20myVar%20%3D%20%22This%20is%20a%20scope%20test%22%3B%0A%20%20console.log(myVar)%3B%0A%7D%0AmyLocalScope()%3B%0A%0A%2F%2F%20Run%20and%20check%20the%20console%0A%2F%2F%20myVar%20is%20not%20defined%20outside%20of%20myLocalScope%0A%2F%2Fconsole.log(myVar)%3B%0A%0A%2F%2F%20Now%20remove%20the%20console%20log%20line%20to%20pass%20the%20test%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

 var myVar;
function myLocalScope() {
  'use strict';
  
  myVar = "This is a scope test";
  console.log(myVar);
}
myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope
//console.log(myVar);

// Now remove the console log line to pass the test


```

**Comment by AndroidHitchhiking** [comment]
//var myVar;
function myLocalScope() {
  'use strict';
  
  var myVar = "This is a scope test";
  console.log(myVar);
}
myLocalScope();

// Run and check the console
// myVar is not defined outside of myLocalScope
//console.log(myVar);

// Now remove the console log line to pass the test

**Comment by raisedadead** [comment]
Hi @AndroidHitchhiking Thanks for reporting, yes this is a known limitation. 
Commenting out is actually not caught perfectly by out code testing infrastructure.

We are trying to take this into account in future releases.

But for now, the only workaround is to delete the line completely.
