### ISSUE TITLE
Word Blanks, Not a Question.

### ISSUE THREAD

**Issue by SoulHarvest** [freeCodeCamp/freeCodeCamp#15200]
Challenge [Word Blanks](https://www.freecodecamp.com/challenges/word-blanks#?solution=%0Afunction%20wordBlanks(myNoun%2C%20myAdjective%2C%20myVerb%2C%20myAdverb)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%20%20%2F%2F%20Your%20code%20below%20this%20line%0A%20%20%0A%0A%20%20%2F%2F%20Your%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20the%20words%20here%20to%20test%20your%20function%0AwordBlanks(%22dog%22%2C%20%22big%22%2C%20%22ran%22%2C%20%22quickly%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function wordBlanks(myNoun, myAdjective, myVerb, myAdverb) {
  var result = "dog big ran quickly cat little hit slowly";
  // Your code below this line
  

  // Your code above this line
  return result;
}

// Change the words here to test your function
wordBlanks("dog", "big", "ran", "quickly");

```
Hello, I made this issue just to inform the powers that be, that with my code just there under the function in var result = (where you aren't supposed to code), I passed the challenge. 

How I found the issue (above^). Why I found it:

 I was messing around with the var result area because no matter what I tried in the area where I was instructed to code, I couldn't even get an answer in the output. Me being a fresh out the womb coder just said screw it and tried it (among many other unsuccessful things lol). I do not think this challenge is something that one can pull off without help or some prior knowledge, even after completing all the challenges before this. Part of it is the instructions, they are clear, but the part where it asks to put strings in between, etc. kind of odd/misleading. The challenge with the cat in the checkboxes also threw me off. 

Sorry for the paragraph, TLDR; this was easy to overcomplicate when all I had to do was create a few and connect some strings like the previous challenges. It felt like the challenge was asking for more. Maybe there should have been a simpler challenge to build up to this, where we use the result and function thingy first, without the Word Blank part so it's not so weird.

**Comment by SoulHarvest** [comment]
Not a request for help.

**Comment by ivancsicsmarkus** [comment]
You can "hack" at every challange it is not a special case.
