### ISSUE TITLE
Addition/Modification to the Code of Conduct 

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#15208]
We need to update the Code of Conduct Page
https://www.freecodecamp.com/code-of-conduct

**"Spamming includes posting off-topic messages to disrupt discussions, promote a product, or solicit donations"** to include the over posting (i.e posting pictures every minute) of images, video and text that are related to the current conversation.  

For example: 

Spamming includes posting off-topic messages to disrupt discussions, promote a product, solicit donations or posting multiple large pictures, videos, streams and text in sequence that disrupts discussions"** 

**Suggestions welcome for better verbiage**

The source file is here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/server/views/resources/code-of-conduct.jade

**Comment by raisedadead** [comment]
Note to contributors:

You need to suggest the change in this issue thread, before making a pull request.

**Comment by jrliv** [comment]
To me it sounds like what you are describing is flooding. What do you think about:

"Spamming includes posting off-topic messages to disrupt discussions, promote a product, solicit donations or flood discussions with consecutive large pictures, videos, streams and text."

**Comment by raisedadead** [comment]
@jrliv that sounds perfect, would you be interested in making a pull request?

**Comment by jrliv** [comment]
@raisedadead Yes I would be glad to contribute my first PR to FCC. Is there a specific set of instructions that I need to follow?

**Comment by raisedadead** [comment]
@jrliv Here are the [Guidelines for Contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md).

Happy fixing!

**Comment by jrliv** [comment]
@raisedadead I'm having issues installing the dependencies to setup freecodecamp and run the test suite because I'm using a 32-bit computer. I've reached out to the [Contributors chatroom](https://gitter.im/FreeCodeCamp/Contributors).
