### ISSUE TITLE
Infinite time for testing challenge | Find the Longest Word in a string | Microsoft Edge

### ISSUE THREAD

**Issue by Saif-Shines** [freeCodeCamp/freeCodeCamp#15203]
#### Find the longest word in a string
(https://www.freecodecamp.com/challenges/find-the-longest-word-in-a-string)

#### Issue Description
I usually use Google Chrome for freeCodeCamping!
For some personal reason, I had to use my friend's laptop, and forced to get on Microsoft edge.
Though I've solved few of challenges, this specific challenge is taking infinite time for testing challenge. 

#### Browser Information

* Browser Name, Version: Microsoft Edge
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```

function findLongestWord(str) {
  var strSplit = str.split(' ');
  var longestWord = 0;
  for(var i = 0; i<strSplit.length;i++){
    if(strSplit[i].length>longestWord){
      longestWord = strSplit[i].length;
    }
  }
  return str.length;
}

findLongestWord("The quick brown fox jumped over the lazy dog");



```

**Comment by raisedadead** [comment]
Have you tested that the common troubleshooting steps do not work?

**Comment by ruanhuhu** [comment]
return str.length;     --->    return longestWord;

**Comment by raisedadead** [comment]
Hi @Saif-Shines 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by Saif-Shines** [comment]
Yes I've gone through:
1. Hard Refreshing the Browser.
2. Resetting the code.
3.Clearing cache.
4. Got into gitter chat rooms. Community suggested me to go through same above steps. - Same happens.
5. Working fine on chrome.
6. Searched for `long time to test challenges`, `Infinite time to testing challeges`, `challenges testing` etc.

Couldn't able to find, similar issue.

**Comment by raisedadead** [comment]
Okay, I checked your code. It's not returning the expected results for the test case, which is OK.

@freeCodeCamp/moderators can anyone confirm this is reproducible on EDGE Browser? I don't have a Windows machine at the moment.

**Comment by Saif-Shines** [comment]
This is only not working on

Windows 10 pro Insider Preview
Build 16193.rs_prerelease.170507-1300

On older version of this, I was able to pass the test.

**Comment by raisedadead** [comment]
> On older version of this, I was able to pass the test.

@Saif-Shines We support only the latest stable browsers and OS. 
I am closing this on that note.
