### ISSUE TITLE
Multiple function call

### ISSUE THREAD

**Issue by Chiomaggia** [freeCodeCamp/freeCodeCamp#15213]
In "Profile Lookup" exercise of "Basic Javascript" section , the function lookUpProfile(firstName, prop) are called many times and the parameter change (like you can see on the code below):

```
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];


function lookUpProfile(firstName, prop){
// Only change code below this line
console.log('firstName= '+ firstName +'  ---  '+'prop= '+ prop);
// Only change code above this line
}

// Change these values to test your function
lookUpProfile("Akira", "likes");

```
CONSOLE LOG:

firstName= Akira  ---  prop= likes
firstName= Akira  ---  prop= likes
firstName= Kristian  ---  prop= lastName
firstName= Sherlock  ---  prop= likes
firstName= Harry  ---  prop= likes
firstName= Bob  ---  prop= number
firstName= Akira  ---  prop= address

**Comment by HugoPetla** [comment]
The function is only called one time, in: 

`lookUpProfile("Akira", "likes");`

It only change the value if you change manually in this example.

**Comment by raisedadead** [comment]
@HugoPetla I believe what @Chiomaggia points is that the function is called multiple times when the challenge is executed to test the results...:sweat_smile: !

That is actually correct, the code checker executes the entire code in the editor (along with some background stuff), for each test case that you see on the left-hand side instructions panel.

This is normal.

For each test case, you will get a different input for the lookUpProfile function.
You are expected to match the results of the test case as per the instructions.

This is the behavior of any and all the challenges that we have.

I hope this clears up any confusion! Closing as not an issue with the codebase. Please consult the chat room or the forum for further assistance!

Happy coding!

**Comment by Chiomaggia** [comment]
AAAAh ok, is the test script :)
I supposed this...
It become a little difficult to use the console log some times, but if it's the normal behaviour ok :)

Thank you
