### ISSUE TITLE
waypoint 142

### ISSUE THREAD

**Issue by desh1993** [freeCodeCamp/freeCodeCamp#15210]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings#?solution=%0Avar%20myStr%3D%22I%20am%20a%5C%22double%20quoted%5C%22string%20inside%5C%22double%20quotes%5C%22.%22%20%0A%3B%20%2F%2F%20Change%20this%20line%0A%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr="I am a\"double quoted\"string inside\"double quotes\"." 
; // Change this line
```

![image](https://cloud.githubusercontent.com/assets/28829091/26770784/3f685232-49ec-11e7-8669-06d4e82944b4.png)

Hi there, my javasript code and output seems to be correct in waypoint 142 but i am unable to pass this challenge.

This is my first time posting an issue. 
Humbly apologize if I am breaking any rules or regulations.

Thank you for the assistance.

**Comment by raisedadead** [comment]
Hi @desh1993 

Thanks for reporting, but your code is not completely correct. You are almost there. You are missing some spaces.

Please reach out to our forum for more help.

And challenges aren't numbered, that 142 is your score, also known as brownie points.

**Comment by desh1993** [comment]
Hi @raisedadead thank you very much for the response.

Really appreciate it, i have already solved it, guess it is abit unforgiving in the spacing.

Thank you very much though
