### ISSUE TITLE
Cant get out of the test. 

### ISSUE THREAD

**Issue by milindsh** [freeCodeCamp/freeCodeCamp#15214]
Challenge [Manipulating Complex Objects](https://www.freecodecamp.com/challenges/manipulating-complex-objects#?solution=%20%20%2F%2F%20Add%20record%20here%0A%20%20var%20myMusic%20%3D%20%5B%0A%20%20%7B%0A%20%20%20%20%22artist%22%3A%20%22Milind%20Sharma%22%2C%0A%20%20%20%20%22title%22%3A%20%22My%20Parents%22%2C%0A%20%20%20%20%22release_year%22%3A%202017%2C%0A%20%20%20%20%22formats%22%3A%20%5B%0A%20%20%20%20%22CD%22%2C%0A%20%20%20%20%22BlueRay%22%5D%0A%20%20%7D%0A%20%20%0A%5D%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
  // Add record here
  var myMusic = [
  {
    "artist": "Milind Sharma",
    "title": "My Parents",
    "release_year": 2017,
    "formats": [
    "CD",
    "BlueRay"]
  }
  
];


```

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
