### ISSUE TITLE
finding numbers with /\d+/g

### ISSUE THREAD

**Issue by eaglecookie** [FreeCodeCamp/FreeCodeCamp#1521]
Challenge http://beta.freecodecamp.com/challenges/finding-numbers has an issue.

The directions demonstrate finding numbers with the following:
/\d+/g

But the RED X insists on an incorrect code:
You should be using the following expression /d+/gi to find the numbers in the testString

This makes it impossible to move to the next challenge.

**Comment by benschenker** [comment]
Closing as stale
