### ISSUE TITLE
Validate US Telephone Numbers 

### ISSUE THREAD

**Issue by IrynaBakal** [freeCodeCamp/freeCodeCamp#15221]
Hi everyone! I'm not sure that it is issue, so will be glad to discuss this task with someone. 
At first, I'll show your my variant of validation US telephone number.

### code
```js
function telephoneCheck(str) {
                let valid1 = /1?\s?\d{3}-\d{3}-\d{4}/g;
                let valid2 = /1?\s?\(\d{3}\)\d{3}-\d{4}/g;
                let valid3 = /1?\s?\(\d{3}\)\s\d{3}-\d{4}/g;
                let valid4 = /1?\s?\d{3}\s\d{3}\s\d{4}/g;
                let valid5 = /1?\s?\d{10}/g;
                
                let validFormats = [valid1,valid2,valid3,valid4,valid5];
                
                 for(let i=0; i<validFormats.length;i++){
                    if(str.search(validFormats[i])==0){
                    	console.log('needed result '+ str.search(validFormats[i]));
                        return true;
                    }		
                }
                  return false;
            }
```
### end of code

It works, but one test is failed and I can't understand why.
I just really don't understand why this function call **telephoneCheck("27576227382")**  should return false. Hope somebody can help with this :)

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

I request you to reach out to the forum http://forum.freecodecamp.com for assistance.

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by satara2358** [comment]
function telephoneCheck(str) {
  // Good luck!
  let strreg=/^(1\s?)?(\(\d{3}\)|\d{3})[\s\-]?\d{3}[\s\-]?\d{4}$/g;
  return !!str.match(strreg);
}
