### ISSUE TITLE
Missing semi-colon in calculator.js

### ISSUE THREAD

**Issue by aashil** [freeCodeCamp/freeCodeCamp#15237]
#### Issue Description

Missing semi-colons on the below lines of file `public/js/calculator.js`:

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/public/js/calculator.js#L186
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/public/js/calculator.js#L203
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/public/js/calculator.js#L246

Note: Beginner friendly only.

**Comment by jonathanihm** [comment]
just curious, is this causing a bug?  I would think ASI would handle this, but it would make for a good PR for beginners.

**Comment by raisedadead** [comment]
Well, it's truly not required, but yes for the sake of keeping things consistent why not. Thanks, @aashil, and @jonathanihm!

**Comment by aashil** [comment]
@jonathanihm I don't think it's a bug in any way. Think of it as a task for first timers. I will be submitting more like these to help people make their first contribution.

**Comment by jonathanihm** [comment]
Consistency and best standards are best!

**Comment by raisedadead** [comment]
Oh first timer's this issue is about knowing how to setup and make a pull request. Here are the 
[Guidelines for Contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by CEREBR4L** [comment]
I'll take it... @raisedadead  😈

**Comment by jonathanihm** [comment]
Please let us know if you need any help!  Cheers!

**Comment by raisedadead** [comment]
@CEREBR4L Awesome!!!

**Comment by AnishHota** [comment]
Can i make the change and do a pull request?
