### ISSUE TITLE
Slot Machine bug

### ISSUE THREAD

**Issue by eaglecookie** [FreeCodeCamp/FreeCodeCamp#1523]
Challenge http://beta.freecodecamp.com/challenges/creating-a-slots-machine has an issue. 

The RED X says:
You should have used Math.floor(Math.random() * (5 - 1 + 1)) + 1; three times to generate your random numbers

Which is what I did, though it refuses to register.

Also, are the numbers supposed to appear in the slot squares?

![creating_a_slots_machine___free_code_camp](https://cloud.githubusercontent.com/assets/13627459/9067705/0117c166-3a94-11e5-8535-cc774cc68878.png)

**Comment by cristianvnica** [comment]
The code below is working for me. I think you use unnecessary () and 'var' keywords.
```
   slotOne = Math.floor(Math.random() * (5 - 1 + 1)) + 1;
   slotTwo = Math.floor(Math.random() * (5 - 1 + 1)) + 1;
   slotThree = Math.floor(Math.random() * (5 - 1 + 1)) + 1;

```

**Comment by benschenker** [comment]
Closing for now, please reopen if this is still an issue for you
