### ISSUE TITLE
Nest Not Working

### ISSUE THREAD

**Issue by lkareeml** [freeCodeCamp/freeCodeCamp#15233]
Challenge [nest-css-with-sass](http://beta.freecodecamp.com/en/challenges/sass/nest-css-with-sass) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.

Use the nesting technique shown above to re-organize the CSS rules for both children of .blog-post element. For testing purposes, the h1 should come before the p element.

I did exactly what the challenge want  but no success.

ERROR : 
Use the nesting technique shown above to re-organize the CSS rules for both children of .blog-post element. For testing purposes, the h1 should come before the p element.

```html


<style>
  .blog-post {
    h1 {
      text-align: center;
      color: blue;
      p {
          font-size: 20px;
        }
    }
  }
</style>

<div class="blog-post">
  <h1>Blog Title</h1>
  <p>This is a paragraph</p>
</div>

```

**Comment by kt20162** [comment]
you need to close the bracket of 'h1' section  before 'p' section,
in above code, you are doing it after the 'p' section

Something like this:

<style>
  .blog-post {
    h1 {
      text-align: center;
      color: blue;
         }

      p {
          font-size: 20px;
        }
  }
</style>

**Comment by lkareeml** [comment]
That's correct @kt20162  Thanks a lot 🥇  : )
