### ISSUE TITLE
Setting Up Slot Machine Slots missing numbers

### ISSUE THREAD

**Issue by eaglecookie** [FreeCodeCamp/FreeCodeCamp#1524]
Challenge http://beta.freecodecamp.com/challenges/setting-up-the-slot-machine-slots has an issue. 

The random numbers are no longer showing up in the slot machine once the if/else statement is added. We only see whether or not the numbers are "Not a Win" or a "Win."
![setting_up_the_slot_machine_slots___free_code_camp](https://cloud.githubusercontent.com/assets/13627459/9067962/60a25a00-3a95-11e5-8c7d-ee25c6e3ce75.png)

**Comment by benschenker** [comment]
Closing as stale, please reopen if you still experience this
