### ISSUE TITLE
All backslashes are gone and it will not pass the section for backslashes

### ISSUE THREAD

**Issue by DivaWeb** [freeCodeCamp/freeCodeCamp#15244]
Challenge [quoting-strings-with-single-quotes](http://beta.freecodecamp.com/en/challenges/basic-javascript/quoting-strings-with-single-quotes) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


var myStr = '< a href= "http:www.example.com" target="_blank">Link<a>';



```

**Comment by DivaWeb** [comment]
I have tried to refresh the screen and still no luck. I even removed the slash in front of the closing anchor tag and that didn't work either but that is a forward slash.

**Comment by Margaret2** [comment]
@DivaWeb this part is wrong: `< a href= "`. You need to remove the extra spaces. Remember to use the [help room](https://gitter.im/freecodecamp/help) before posting a Github issue~

**Comment by DivaWeb** [comment]
so here are the instructions:  Remove all the backslashes (\)
You should have two single quotes ' and four double quotes "

Where does it say to remove any spaces? And removing the space you say does not make a difference. 
So how else is this solution wrong? I am using google chrome.

**Comment by Margaret2** [comment]
Those are the tests, not the instructions. The instructions say: 
> Change the provided string from double to single quotes and remove the escaping. **Do not change anything else.**

Your solution is not passing because you made too many changes to the string. If you need further help, you need to ask in [Gitter help chat](https://gitter.com/freecodecamp/helpjavascript) or the [forum](https://forum.freecodecamp.com).

**Comment by raisedadead** [comment]
Hi @DivaWeb 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by dbsmandal** [comment]
this is the correct answer

const myStr = '<a href="http://www.example.com" target="_blank">Link</a>';
