### ISSUE TITLE
Modify Array Data With Indexes

### ISSUE THREAD

**Issue by djsirena** [freeCodeCamp/freeCodeCamp#15245]
It's a repeat of this:
https://github.com/freeCodeCamp/freeCodeCamp/issues/8960
I tried many variations of code, and I believe this is a bug. 

Challenge [Modify Array Data With Indexes](https://www.freecodecamp.com/challenges/modify-array-data-with-indexes#?solution=%0A%2F%2F%20Example%0Avar%20ourArray%20%3D%20%5B1%2C2%2C3%5D%3B%0AourArray%5B1%5D%20%3D%203%3B%20%2F%2F%20ourArray%20now%20equals%20%5B1%2C3%2C3%5D.%0A%0A%2F%2F%20Setup%0Avar%20myArray%20%3D%20%5B1%2C2%2C3%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0AmyData%20%3D%20myArray%3B%0Avar%20myArray%20%3D%20%5B3%2C2%2C3%5D%3B%20%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourArray = [1,2,3];
ourArray[1] = 3; // ourArray now equals [1,3,3].

// Setup
var myArray = [1,2,3];

// Only change code below this line.
myData = myArray;
var myArray = [3,2,3]; 


```

**Comment by Margaret2** [comment]
Hi, your code is incorrect. You need to modify a single item in the array, not the whole array: 
> Modify the data stored at index 0 of myArray to a value of 3.

If you need help fixing it, please ask in the [Help chat](https://gitter.im/freecodecamp/helpjavascript) or on the [forum](https://forum.freecodecamp.com)

**Comment by raisedadead** [comment]
Hi @djsirena 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
