### ISSUE TITLE
Is Image Search Abstraction still a valid challange? 

### ISSUE THREAD

**Issue by DoubleTri** [freeCodeCamp/freeCodeCamp#15249]
All the issues with is challenge are closed because it was "removed in beta".  But it's still a required challenge.  And the API issues that people were talking about still exist.  So...???? should this thing be removed or should we struggle through it with absolutely no guidance whatsoever?  
As a side note, I'm shocked at how disorganized and bumbling the back-end course is so far.  It's like you guys just gave up half way through.

**Comment by raisedadead** [comment]
Thanks for your feedback but the solution to this already stands, we will remove this from the main production site as well, but we do not have a timeline at the moment.

Please feel free to discuss this further on the forum.

Happy coding!

**Comment by raisedadead** [comment]
@QuincyLarson maybe we can mark the challenge as not required on the production? But I'll leave that to you.
