### ISSUE TITLE
[beta] Sign in issue with username 

### ISSUE THREAD

**Issue by Toughee** [freeCodeCamp/freeCodeCamp#15254]
#### Issue Description

I'm trying to sign back in to the beta site for Free Code Camp, but it's not letting me use my username to login.

It won't let me sign in unless I use an email, even if it shows inside the message box as "Invalid username".  First image is me trying to use my username. Second image is what shows up in the error message box.

#### Browser Information

* Browser Name: Chromium. Version: 59.0.3042.0 (Developer Build) (32-bit)
* Operating System: Windows 8
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![fcc_issue2](https://user-images.githubusercontent.com/21093554/26909363-13ff125a-4bb5-11e7-9681-3ee8b95ed32f.JPG)

![fcc_issue](https://user-images.githubusercontent.com/21093554/26909307-b465791a-4bb4-11e7-8c21-8d21409aec0e.JPG)

**Comment by raisedadead** [comment]
You will not be able to log in using the username on beta, and soon this would be replaced with a newer login, these messages that you see would be replaced.

We have fixes planned and on their way.

Thanks for reporting!

**Comment by systimotic** [comment]
The PR was merged, so I'm closing this issue. Happy coding!
