### ISSUE TITLE
502 issue

### ISSUE THREAD

**Issue by Shifthawke** [FreeCodeCamp/freecodecamp#1525]
Hey! I'm getting the 502 error when I click to go to the next challenge. It is under HTML5. going from waypoint '1.Waypoint: Use a CSS Class to Style an Element' to the next one. I kept getting 502 several times that I tried. If I select the next waypoint from the map though, it loads up just fine with no problem. And it seems like it is just that way point change. Also, this is on the beta site (I was too excited to wait, I'm sorry.)

**Comment by BerkeleyTrue** [comment]
Hello @Shifthawke,

This is a known issue. see #1386. Happy coding!

**Comment by Shifthawke** [comment]
Sorry to bog the bug page. My kids were screaming at me while I was looking to see if anyone else reported it, so I ultimately reported it. Sorry for the trouble ^_^ 


     On Tuesday, August 4, 2015 1:58 PM, Berkeley Martinez <notifications@github.com> wrote:
   

 Hello @Shifthawke,This is a known issue. see #1386. Happy coding!—

**Comment by BerkeleyTrue** [comment]
No worries.
