### ISSUE TITLE
video is not working

### ISSUE THREAD

**Issue by doroginalexanderqt** [freeCodeCamp/freeCodeCamp#15258]
Challenge [build-a-drum-machine](http://beta.freecodecamp.com/en/challenges/front-end-frameworks-projects/build-a-drum-machine) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by doroginalexanderqt** [comment]
visit that page and try to play video.

**Comment by raisedadead** [comment]
Duplicate #12753
