### ISSUE TITLE
Title Case a Sentence

### ISSUE THREAD

**Issue by Abdifatah25** [freeCodeCamp/freeCodeCamp#15251]
Title Case a Sentence

https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Afunction%20titleCase(str)%20%7B%0A%20%20var%20strZ%20%3D%20str.toLowerCase()%3B%0A%20%20%0A%20%20var%20word%20%3D%20strZ.split('%20')%3B%0A%20%20var%20list%20%3D%20%5B%5D%3B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20word.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20list%20%2B%3D%20word%5Bi%5D%5B0%5D.toUpperCase()%20%2B%20word%5Bi%5D.slice(1)%20%2B%20%22%20%22%3B%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20return%20list%3B%0A%20%20%0A%7D%0A%0AtitleCase(%22sHoRt%20AnD%20sToUt%22)%3B%0A

#### Issue Description
I have got a working solution, however it does not allow me to continue to the next task.  

#### Browser Information

* Browser Name, Version: safari
* Operating System: os 
* Mobile, Desktop, or Tablet: desktop

#### Your Code

```js

function titleCase(str) {
  var strZ = str.toLowerCase();
  
  var word = strZ.split(' ');
  var list = [];
  for (var i = 0; i < word.length; i++) {
    list += word[i][0].toUpperCase() + word[i].slice(1) + " ";
  }
  
  
  return list;
  
}

titleCase("sHoRt AnD sToUt");




```
#### Screenshot
![screen shot 2017-06-08 at 01 25 43](https://user-images.githubusercontent.com/27793916/26907189-94576e00-4be9-11e7-9e0a-41e2aa540e72.png)

![screen shot 2017-06-08 at 01 27 25](https://user-images.githubusercontent.com/27793916/26907197-abb7dcba-4be9-11e7-964b-3443bbd8ec7d.png)

**Comment by Fubinator** [comment]
your code is incorrect, because you're adding a blank space at the end. your result is not "Short And Stout" as the test expects but rather "Short and Stout "

Please use the [Forum](https://forum.freecodecamp.com/) or the [Chat](https://gitter.im/freecodecamp/help) if you need help fixing your code

**Comment by raisedadead** [comment]
Hi @Abdifatah25 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by Abdifatah25** [comment]
@Fubinator Thank you!
