### ISSUE TITLE
Ive tried requesting help didnt get any and cant see the mistake soooo could it posibly be a bug?

### ISSUE THREAD

**Issue by dianalizethromo** [freeCodeCamp/freeCodeCamp#15265]
Challenge [Using Objects for Lookups](https://www.freecodecamp.com/challenges/using-objects-for-lookups#?solution=%0A%2F%2F%20Setup%0Afunction%20phoneticLookup(val)%20%7B%0A%20%20var%20result%20%3D%20%22%22%3B%0A%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line%0Avar%20lookup%20%3D%20%7B%0A%20%20%20%20alpha%3A%20%22Adams%22%2C%0A%20%20%20%20bravo%3A%20%22Boston%22%2C%0A%20%20%20%20charlie%3A%20%22Chicago%22%2C%0A%20%20%20%20delta%3A%20%22Denver%22%2C%0A%20%20%20%20echo%3A%20%22Easy%22%2C%0A%20%20%20%20foxtrot%3A%20%22Frank%22%0A%20%20%7D%3B%0A%20%20%0A%20%20result%20%3D%20lookup%5Bval%5D%3B%0A%20%20%0A%20%20%7D%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line%0A%20%20return%20result%3B%0A%7D%0A%0A%2F%2F%20Change%20this%20value%20to%20test%0AphoneticLookup(%22charlie%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
var lookup = {
    alpha: "Adams",
    bravo: "Boston",
    charlie: "Chicago",
    delta: "Denver",
    echo: "Easy",
    foxtrot: "Frank"
  };
  
  result = lookup[val];
  
  }

  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");

```

**Comment by Fubinator** [comment]
There's one `}` too much in your code.

**Comment by erictleung** [comment]
@dianalizethromo as @Fubinator has pointed out, you have one too many curly brackets in your code that is preventing you from passing the challenge. I understand that the chat rooms can be quite busy at times. Please be patient. In the meantime, I'd take the time to go over your code carefully to see if you can debug it yourself. Happy coding!
