### ISSUE TITLE
No win on this task - targetting children of an element

### ISSUE THREAD

**Issue by DarrenfJ** [FreeCodeCamp/freecodecamp#1526]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

```javascript
<script>
  $(document).ready(function() {
    $('#right-well').children().css('color', 'green')
  });
</script>
```

**Comment by kurzninja** [comment]
The test for the RGB value was incorrect, I have fixed this in https://github.com/FreeCodeCamp/freecodecamp/pull/1706.
