### ISSUE TITLE
It seems that my code passes every test condition when I test it in the console, yet all but one of the tests are showing failure. Help?

### ISSUE THREAD

**Issue by bduncan136** [freeCodeCamp/freeCodeCamp#15267]
Challenge [Where do I belong](https://www.freecodecamp.com/challenges/where-do-i-belong#?solution=%0Afunction%20getIndexToIns(arr%2C%20num)%20%7B%0A%20%20arr.sort(function(a%2Cb)%7Breturn%20a-b%3B%7D)%3B%0A%20%20for(var%20i%20in%20arr)%7B%0A%20%20%20%20if(arr%5Bi%5D%3E%3Dnum)%7B%0A%20%20%20%20%20%20return%20i%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20arr.length%3B%0A%7D%0A%0AgetIndexToIns(%5B10%2C%2020%2C%2030%2C%2040%2C%2050%5D%2C%2035)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function getIndexToIns(arr, num) {
  arr.sort(function(a,b){return a-b;});
  for(var i in arr){
    if(arr[i]>=num){
      return i;
    }
  }
  return arr.length;
}

getIndexToIns([10, 20, 30, 40, 50], 35);

```

All parts of the challenge seem to be passed by the code above, yet almost all of the conditions are showing as failed.

**Comment by raisedadead** [comment]
Hi @bduncan136 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by bduncan136** [comment]
but it does seem like a bug, since my code works but isn't being acknowledged as such

**Comment by Margaret2** [comment]
@bduncan136 Your function is returning a string instead of a number. That's probably the problem.

**Comment by bduncan136** [comment]
That did it, thank you so much. I thought it was a glitch. Can you tell me how you could tell it was returning a string? To me, it looks like both types of returns are numbers.

**Comment by raisedadead** [comment]
Please proceed on the chat or the forum, this tracker is not for coding assistance.
