### ISSUE TITLE
what am i doing wrong?

### ISSUE THREAD

**Issue by ar94952** [freeCodeCamp/freeCodeCamp#15269]
Challenge [Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string#?solution=function%20truncateString(str%2C%20num)%20%7B%0A%20%20var%20newStr%20%3D%20''%3B%0A%0A%20%20if%20(num%20%3C%3D%203)%20%7B%0A%20%20%20%20newStr%20%3D%20str.slice(0%2C%20num)%20%2B%20'...'%3B%0A%20%20%7D%20else%20if%20(str.length%20%3E%20num)%20%7B%0A%20%20%20%20newStr%20%3D%20str.slice(0%2C%20num%20-%203)%20%2B%20'...'%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20str%3B%0A%20%20%7D%0A%0A%20%20return%20newStr%3B%0A%7D%0A%0AtruncateString(%22Absolutely%20Longer%22%2C%202)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function truncateString(str, num) {
  var newStr = '';

  if (num <= 3) {
    newStr = str.slice(0, num) + '...';
  } else if (str.length > num) {
    newStr = str.slice(0, num - 3) + '...';
  } else {
    return str;
  }

  return newStr;
}

truncateString("Absolutely Longer", 2);

```

**Comment by raisedadead** [comment]
Hi @ar94952 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
