### ISSUE TITLE
CodePen accounts now require a credit card.

### ISSUE THREAD

**Issue by deonoli4** [freeCodeCamp/freeCodeCamp#15276]
Challenge [Build a Tribute Page](https://www.freecodecamp.com/challenges/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by raisedadead** [comment]
Hi @deonoli4 

Yes, you can use Gomix.com to create your projects now.
We are in the process of adding this to the instructions.

Thanks and happy coding.

**Comment by QuincyLarson** [comment]
@deonoli4 I just checked and I was able to create a free account on CodePen without a credit card. Where did you see a requirement to add a credit card? Can you add a screenshot? I'm closing this issue pending further information.
