### ISSUE TITLE
Front end doesn't work

### ISSUE THREAD

**Issue by BenRitmicoCode** [freeCodeCamp/freeCodeCamp#15281]
Challenge [metricimperial-converter](http://beta.freecodecamp.com/en/challenges/information-security-and-quality-assurance-projects/metricimperial-converter) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.0.12137 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

https://hard-twilight.glitch.me/

Filling in the frontend portion returns nothing whenever the convert button is pressed

**Comment by raisedadead** [comment]
Can you please share some screenshots?

**Comment by raisedadead** [comment]
![2017-06-09 22 18 22](https://user-images.githubusercontent.com/1884376/26985578-b32eb6f2-4d61-11e7-887c-ca9c5eb647f0.gif)

**Comment by BenRitmicoCode** [comment]
oh wait I see, it's when I press enter instead of clicking the button

**Comment by raisedadead** [comment]
Yup, confirmed.

**Comment by raisedadead** [comment]
The form in this repo :
https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter/blob/gomix/views/index.html#L47-L50

is not handled correctly.

https://github.com/freeCodeCamp/boilerplate-project-metricimpconverter/blob/gomix/views/index.html#L61

Potential contributors, please fork and send a pull request to the repository.

@JosephLivengood @no-stack-dub-sack do you guys have an idea how do we update the deployed app itself.

**Comment by no-stack-dub-sack** [comment]
@raisedadead sorry, no. But I think @JosephLivengood or @erictleung perhaps would be better candidates to help with this. I helped QA certain portions of these projects, but didn't help build or deploy.

**Comment by dpw1** [comment]
What needs to be done? Make it work with the Enter key as well?

**Comment by raisedadead** [comment]
@dpw1 a pull request is already available and ready to be merged, @BerkeleyTrue since @JosephLivengood is not around, I guess could give the the PR a merge. Its good to go.

**Comment by BerkeleyTrue** [comment]
@raisedadead I've merged it. Thanks for checking it out!
