### ISSUE TITLE
Typo in instructions: Target a specific child element

### ISSUE THREAD

**Issue by DarrenfJ** [FreeCodeCamp/freecodecamp#1528]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The instructions ask for the 1st element to be made to bounce, but the test indicates it tests against the 2nd element bouncing. Confirmed change to 2nd element passes test.

**Comment by benflinn** [comment]
submitted a commit to fix this: 

https://github.com/benflinn/freecodecamp/commit/87c4afcff5608b34ec086eb19437bb8dbcf1afe4

**Comment by DarrenfJ** [comment]
thanks @benflinn, much appreciated!
