### ISSUE TITLE
Test passes with typo in <link href ..> that prevents Lobster font loading

### ISSUE THREAD

**Issue by mscott01** [freeCodeCamp/freeCodeCamp#15283]
Challenge [Import a Google Font](https://www.freecodecamp.com/challenges/import-a-google-font#?solution=%3Clink%20href%3D%22https%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20ref%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%0A%3Cstyle%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Notice in the <link href ...>  there is a typo...  **ref**="stylesheet" should be **rel**="stylesheet"
This prevents Lobster from loading, the web page preview never renders Lobster font
Yet, clicking run test proceeds with a pass and we move on

My code:
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" ref="stylesheet" type="text/css">

<style>                                                                                             
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by raisedadead** [comment]
I could not pass the challenge with the typo, is Lobster installed locally on your machine?

**Comment by mscott01** [comment]
Not that I know of.. I just tried it again.. Opened CodeCamp.. used Map to navigate to Import Google Font task, it was in the completed state with Lobster loading and rendering

Edited the <link href...>  my changing "rel"  to "ref" and the rendering of Lobster font stopped in preview but Run Test still passes. 

Where do I find in Lobster is loaded on my machine?

**Comment by mscott01** [comment]
Even when I only use this link statement it still passes the test...

<link href="https://fonts.googleapis.com">

**Comment by mscott01** [comment]
It appears there are problems in the validation of the import statement. I imported a different google font "Anton" like this...

<link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet" type="text/css">

and applied it to the h2 element like this...

h2 {
    font-family:Anton;
  }

and the test shows I passed the Import font step but failed the h2 element using Lobster. The import font step should have failed!  I imported the wrong font.
