### ISSUE TITLE
"Identifier 'dataset' has already been declared"  (Works only when const is commented out)

### ISSUE THREAD

**Issue by Bijay-Panthi** [freeCodeCamp/freeCodeCamp#15286]
Challenge [work-with-dynamic-data-in-d3](https://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/work-with-dynamic-data-in-d3) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<body>
  <script>
    //const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
    
    d3.select("body").selectAll("h2")
      .data(dataset)
      .enter()
      .append("h2")
      // Add your code below this line
      
      .text((dataset) => dataset + " USD");
      
      // Add your code above this line
  </script>
</body>

```

**Comment by planigan** [comment]
I'm going through the beta D3 stuff and I get this error on every challenge. Reloading the page allows me to run the tests and pass, but tests fail if run them again without a manually reloading the page.

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36`

**Comment by BtheGit** [comment]
Same issue, thanks for the tip on the manual refresh.

**Comment by IMBurbank** [comment]
I'm regularly getting this error on d3 challenges as well. I have been commenting out the line where `dataset` is defined to be able to pass the challenge.

**Comment by lynxlynxlynx** [comment]
This is a duplicate, there are older reports open for the exact same problem (#13267 and #12762).  Suggest closing.

**Comment by systimotic** [comment]
Hi! Thanks for reporting and looking into this issue.

This is a known issue. We're working on resolving it through https://github.com/freeCodeCamp/freeCodeCamp/issues/12762. I'm closing this as a duplicate.

Happy coding!
