### ISSUE TITLE
Possible bug in "Profile Lookup" challenge

### ISSUE THREAD

**Issue by CesarFerreiraGermano** [freeCodeCamp/freeCodeCamp#15287]
#### Challenge Name

Profile Lookup ( https://www.freecodecamp.com/challenges/profile-lookup )

#### Issue Description

My code looks right, and for the last condition that is missing, the expected response appears on the console. However, the challenge is not yet complete.

#### Browser Information

* Browser Name, Version: Chromium
* Operating System: Ubuntu
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



//Setup
var contacts = [
    {
        "firstName": "Akira",
        "lastName": "Laine",
        "number": "0543236543",
        "likes": ["Pizza", "Coding", "Brownie Points"]
    },
    {
        "firstName": "Harry",
        "lastName": "Potter",
        "number": "0994372684",
        "likes": ["Hogwarts", "Magic", "Hagrid"]
    },
    {
        "firstName": "Sherlock",
        "lastName": "Holmes",
        "number": "0487345643",
        "likes": ["Intriguing Cases", "Violin"]
    },
    {
        "firstName": "Kristian",
        "lastName": "Vos",
        "number": "unknown",
        "likes": ["Javascript", "Gaming", "Foxes"]
    }
];

var flagExist = false;
function lookUpProfile(firstName, prop){
// Only change code below this line
  for(var i = 0; i < contacts.length; i++){
    if (contacts[i].firstName == firstName){
      flagExist = true;
      if (contacts[i].hasOwnProperty(prop))
        return contacts[i][prop];
      else
         return "No such property";
    }
    if ((flagExist === false)&&(i == contacts.length - 1))
      return "No such contact";
  }
  
// Only change code above this line
}

// Change these values to test your function
lookUpProfile("Bob", "number");



```
#### Screenshot

![captura de tela de 2017-06-10 01-40-48](https://user-images.githubusercontent.com/15146897/27000069-2f7d7b22-4d7f-11e7-855a-499005c7631b.png)

**Comment by erictleung** [comment]
@CesarFerreiraGermano thanks for the issue. You have global variables in your code. Our challenge tests run your function over and over and if you have any global variables, they will change with each test. So move your global variables to within your function and your code will pass. Happy coding!
