### ISSUE TITLE
Code not passing despite correct output

### ISSUE THREAD

**Issue by CoryARamirez** [freeCodeCamp/freeCodeCamp#15289]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence#?solution=%0Avar%20firstLetters%20%3D%20%5B%5D%3B%0Avar%20lastLetters%20%3D%20%5B%5D%3B%0A%0Afunction%20titleCase(str)%20%7B%0A%20%20var%20splitString%20%3D%20str.split(%22%20%22)%3B%0A%20%20for%20(var%20i%20%3D%200%3B%20i%20%3C%20splitString.length%3B%20i%2B%2B%20)%20%7B%0A%20%20%20%20var%20firstLetter%20%3D%20splitString%5Bi%5D.charAt(0).toUpperCase()%3B%0A%20%20%20%20firstLetters.push(firstLetter)%3B%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20for%20(var%20j%20%3D%200%3B%20j%20%3C%20splitString.length%3B%20j%2B%2B%20)%20%7B%0A%20%20%20%20var%20lastLetter%20%3D%20splitString%5Bj%5D.substr(1).toLowerCase()%3B%0A%20%20%20%20lastLetters.push(lastLetter)%3B%0A%20%20%7D%0A%20%20%20%20%0A%20%20for%20(var%20k%20%3D%200%3B%20k%20%3C%20firstLetters.length%3B%20k%2B%2B)%20%7B%0A%20%20%20%20%20%20firstLetters%5Bk%5D%20%2B%3D%20lastLetters%5Bk%5D%3B%0A%20%20%7D%0A%20%20%0A%20var%20finalString%20%3D%20firstLetters.toString()%3B%0A%20var%20parsedString%20%3D%20finalString.replace(%2F%2C%2Fg%2C%20%22%20%22)%3B%0A%20return%20parsedString%3B%0A%7D%0A%0AtitleCase(%22HERE%20IS%20MY%20HANDLE%20HERE%20IS%20MY%20SPOUT%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var firstLetters = [];
var lastLetters = [];

function titleCase(str) {
  var splitString = str.split(" ");
  for (var i = 0; i < splitString.length; i++ ) {
    var firstLetter = splitString[i].charAt(0).toUpperCase();
    firstLetters.push(firstLetter);    
  }
  
  for (var j = 0; j < splitString.length; j++ ) {
    var lastLetter = splitString[j].substr(1).toLowerCase();
    lastLetters.push(lastLetter);
  }
    
  for (var k = 0; k < firstLetters.length; k++) {
      firstLetters[k] += lastLetters[k];
  }
  
 var finalString = firstLetters.toString();
 var parsedString = finalString.replace(/,/g, " ");
 return parsedString;
}

titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");

```

**Comment by erictleung** [comment]
@CoryARamirez thanks for the issue. You have global variables in your code. Our challenge tests run your function over and over and if you have any global variables, they will change with each test. So move your global variables to within your function and your code will pass. Happy coding!
