### ISSUE TITLE
After using the div element with class "well" in each of my "col-xs-6", its not working

### ISSUE THREAD

**Issue by tobawin** [freeCodeCamp/freeCodeCamp#15293]
Challenge [Create Bootstrap Wells](https://www.freecodecamp.com/challenges/create-bootstrap-wells) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.

After using the div element with class "well" in each of my "col-xs-6", its not working

My code:
```html

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div clas="well"></div>
    </div>
    <div class="col-xs-6">
      <div class="well"></div>
    </div>
  </div>
</div>

```

**Comment by holgermischke** [comment]
Typo in line 5: clas instead of class

**Comment by tobawin** [comment]
Wow! This is real....
Thanks greatly @holgermischke 
Resolved now.

**Comment by holgermischke** [comment]
No worries, tobawin. Happens all the time. :) Please close.
