### ISSUE TITLE
Typo in instrusions: Target same element multiple jQuery

### ISSUE THREAD

**Issue by DarrenfJ** [FreeCodeCamp/freecodecamp#1529]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

instructions say to add class 'button-primary' but tests against 'btn-primary'

**Comment by QuincyLarson** [comment]
@darrenfj thank you for catching this. We've fixed it.
