### ISSUE TITLE
Tests passing with wrong text

### ISSUE THREAD

**Issue by PedroCSilva** [freeCodeCamp/freeCodeCamp#15291]
Challenge [nest-an-anchor-element-within-a-paragraph](http://beta.freecodecamp.com/en/challenges/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<h2>CatPhotoApp</h2>
<main>
  
  <p><a href="http://freecatphotoapp.com" target="_blank">cat photos</a>View more </p>
  
  <img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">
  
  <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  <p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
</main>

```

This results in "cat photosView more ". I may be able to fix this issue as well.

**Comment by lynxlynxlynx** [comment]
I wouldn't consider this "wrong text", as the instructions say nothing about the order.

It is true thought that the description needlessly mentions that the new paragraph should be after main, while the tests (justly imo) allow also for just wrapping the existing link.

**Comment by systimotic** [comment]
I'm closing this issue as stale. If this problem comes up again, please comment here and we'll reopen.

Happy coding!
