### ISSUE TITLE
code is correct but still telling me to "keep trying"

### ISSUE THREAD

**Issue by BlackGrimReaper** [freeCodeCamp/freeCodeCamp#15296]
Challenge [use-css-selectors-to-style-elements](http://beta.freecodecamp.com/en/challenges/basic-css/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html

<style>
  h2 {color: blue;}
</style>

<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

```

![bug](https://user-images.githubusercontent.com/26975750/27004837-65400edc-4e2e-11e7-9076-5222aa1a5063.jpg)

**Comment by texas2010** [comment]
I test this challenge on chrome. it passed.
I test it on Firefox. it won't passed.
I use his code.

it seems this challenge have an issue with Firefox.

by the way, I use the Mac.

**Comment by wizofe** [comment]
Same problem here.

Using Macbook (Sierra 10.12.5) and Firefox 54.0.

**Comment by systimotic** [comment]
Hi! Thanks for reporting this issue. This was fixed in https://github.com/freeCodeCamp/freeCodeCamp/pull/15775, so I'm closing this issue.

Happy coding!
