### ISSUE TITLE
I think there is a bug in this challenge, it does not seem to run

### ISSUE THREAD

**Issue by jvs09182** [freeCodeCamp/freeCodeCamp#15292]
Challenge [Add Borders Around your Elements](https://www.freecodecamp.com/challenges/add-borders-around-your-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

<style>
  
  .red-text {
    color: red;
  }
  
  .thick-green-border { border-color: green;
  border-width: 10px;
  border-style: solid;
  }
 
  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="thick-green border smaller-image"                   src="https://bit.ly/fcc-relaxing-cat" 
     alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by mrbaker1917** [comment]
Jim, you are missing the hyphen in between "green" and "border" in the assignment of class to the img. "thick-green border". Try that and see if it works.

**Comment by raisedadead** [comment]
Hi @jvs09182 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by mariamach** [comment]
Same :(

**Comment by shutdown57** [comment]
follow this link, maybe it work for you too.
[stackoverflow](https://stackoverflow.com/questions/25139770/using-google-fonts-in-firefox)

**Comment by Mely89** [comment]
Same issue her!

**Comment by Mely89** [comment]
*here

**Comment by CosmicDog2000** [comment]
Your class ID in the HTML is "thick-green border", it should be "thick-green-border". Spaces aren't allowed in CSS identifiers.
