### ISSUE TITLE
Doesn't pass test

### ISSUE THREAD

**Issue by DarrenfJ** [FreeCodeCamp/FreeCodeCamp#1530]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
instructions ask for div class to be "fluid-container' but test says "your div element should have class 'row'" when switched to 'row' it still continues to fail test

**Comment by benflinn** [comment]
you need to use "container-fluid" and it will pass.

the row class check doesn't work, either

**Comment by DarrenfJ** [comment]
Thanks @benflinn , confirmed changed the 'container-fluid' and all is well.

Just needs a clean-up in the instructions.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1515
It seems this issue is fixed.
