### ISSUE TITLE
Error: TypeError: 0 is read-only

### ISSUE THREAD

**Issue by NoumbissiValere** [freeCodeCamp/freeCodeCamp#15305]
Challenge [Understand String Immutability](https://www.freecodecamp.com/challenges/understand-string-immutability) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myStr = "Jello World";

// Only change code below this line

myStr = "Hello World"; // Fix Me
myStr[0] = "H";


```

**Comment by raisedadead** [comment]
Hi @NoumbissiValere 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
