### ISSUE TITLE
Blue isn't recognized inside the bracket

### ISSUE THREAD

**Issue by jeremyjregister** [freeCodeCamp/freeCodeCamp#15302]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style> 
  h2 {color: blue;} >CatPhotoApp</style>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by Margaret2** [comment]
Hi - your code is not correct, it's not an issue with the FCC website. If you need help fixing it, please ask in the [Help chat](https://gitter.im/freecodecamp/help) or on the [forum](https://forum.freecodecamp.com)
