### ISSUE TITLE
My challenge is not submitting, why? 

### ISSUE THREAD

**Issue by RA9** [freeCodeCamp/freeCodeCamp#15317]
#### Challenge Name

https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element

#### Issue Description

The submit button is not working. 

#### Browser Information

<p> I am having problems with my html5 challenge in my work space,please I need help to submit my work. </p>
* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 
Chrome 
Android 5.0
Mobile 
#### Your Code

```js



```
#### Screenshot

<p> My challenge had finished but can't figure out why the page is not submitting my work? <br>
Here is my <a href="https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element">link</a> to the challenge. 
</p>

**Comment by raisedadead** [comment]
Hi @RA9 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
