### ISSUE TITLE
Can you help me to solve it please?

### ISSUE THREAD

**Issue by magicman42** [freeCodeCamp/freeCodeCamp#15318]
Challenge [Override Styles in Subsequent CSS](https://www.freecodecamp.com/challenges/override-styles-in-subsequent-css) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 class="class1 class2">
<h1 class="pink-text blue-text"> Hello World! </h1>
```
![image](https://user-images.githubusercontent.com/29311251/27012582-2844c434-4edb-11e7-9d81-1b404ff6e12d.png)

**Comment by magicman42** [comment]
The problem is with the last task. The h1 element became blue, but the programme doesn't seem to see this. Is it smth wrong with me code or is it a programme's bug?

**Comment by magicman42** [comment]
Thank you a lot

**Comment by raisedadead** [comment]
Hi @magicman42 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
