### ISSUE TITLE
Create an ordered list has an issue with test cases.

### ISSUE THREAD

**Issue by daveyx** [freeCodeCamp/freeCodeCamp#15314]
Challenge: Create an Ordered List
https://www.freecodecamp.com/challenges/create-an-ordered-list

My friend put the following in line 30 (i don't know why she did that):
<ol>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ol>

and the correct code at the end of the file:
<p>Top 3 things cats hate:</p>
<ol>
  <li>Cucumber</li>
  <li>Snake</li>
  <li>Dog</li>
</ol>

#### Issue Description
Following testcase fails:
You should have three li elements within your ol element.

The problem is that the testcase requirements are fullfilled, but fails because of the wrong code starting line 30.

The user now only looks on the li and ol elements, which is definitively correct. The app must recognize that it is because of another wrong insertion and inform the user.

**Comment by raisedadead** [comment]
@daveyx 

Thanks for reporting, but it would be best if you (or your friend) could submit the entire code in the editor that you had while this is happening.

I am blocking it meanwhile.

Happy coding!

**Comment by daveyx** [comment]
hi @raisedadead 

here the full code which fails:

```
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<ol>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ol>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>hot</li>
  <li>cold</li>
  <li></li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ol>

```
Kind regards

**Comment by dhcodes** [comment]
The issue here is not the test per se, but that the user is putting in 2 ordered lists when the test is looking for one. If she were to remove either ordered list so one remains, it would pass. I suppose we could add a test that ensures there is only one ordered list. What do others think? cc @freeCodeCamp/moderators

**Comment by raisedadead** [comment]
Thanks @dhcodes !

**Comment by QuincyLarson** [comment]
@dhcodes Yes - if this is something that is likely to happen, I agree that we should either improve the existing test, or create a new test that will fail and remind them to only use one ordered list.

**Comment by prateekgoel** [comment]
Can i work on this?

**Comment by QuincyLarson** [comment]
@prateekgoel Absolutely. This one's yours. As always, thanks for your help!

**Comment by prateekgoel** [comment]
I am happy to help. Thanks @QuincyLarson
