### ISSUE TITLE
I tried typing the Additonal kitty ipsum text.Still giving error.And how to adjust Text-zoom?

### ISSUE THREAD

**Issue by Rahulsuperrock94** [freeCodeCamp/freeCodeCamp#15319]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  
  .font-size_zoom{
    font-size:16px;
    Text-zoom:100%;
  }
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text" class="font-size-zoom">kitty ipsum text.</p>
<p style="color:red">kitty ipsum text.</p>


```

**Comment by mbandgeek08** [comment]
Try removing the period from the end of your text. It gave me the same issue when I tried adding an ellipses.

**Comment by raisedadead** [comment]
Hi @mbandgeek08 @Rahulsuperrock94 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
