### ISSUE TITLE
```

### ISSUE THREAD

**Issue by qreven** [freeCodeCamp/freeCodeCamp#15310]
Challenge [Factorialize a Number](https://www.freecodecamp.com/challenges/factorialize-a-number) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var sum = 1;
function factorialize(num) {
  for (var i = 1; i < num; i++){
      sum = sum*(1+i);
    }
  return sum;
}
factorialize(20);
```

**Comment by qreven** [comment]
i am getting the right answer but the program is not passing the code

**Comment by Manish-Giri** [comment]
@qreven Make this variable local - `var sum = 1;`.

Next time please use the [help room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for code assistance issues.

**Comment by erictleung** [comment]
@qreven thanks for the issue. You have global variables in your code. Our challenge tests run your function over and over and if you have any global variables, they will change with each test. So move your global variables to within your function and your code will pass. Happy coding!
