### ISSUE TITLE
won't acknowledge that I've changed the color to blue

### ISSUE THREAD

**Issue by lizh1969** [freeCodeCamp/freeCodeCamp#15313]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; OfficeLiveConnector.1.5; OfficeLivePatch.1.3; BRI/2; .NET4.0E; rv:11.0) like Gecko</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {color: blue;}
</style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by indefinite0212** [comment]
Hi @lizh1969 , you're missing something in your code. if you need help solving the challenge you should ask first at [help room](https://gitter.im/FreeCodeCamp/Help) before posting a git hub issue.

**Comment by raisedadead** [comment]
Hi @lizh1969 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by geebeedee** [comment]
<style>
  h2 { color: blue; } 
</style>

Can somebody tell me what's missing in this code if any ? Im stuck...
