### ISSUE TITLE
i couldn't able to pass this challenge plz help

### ISSUE THREAD

**Issue by bhavya2109sharma** [freeCodeCamp/freeCodeCamp#15325]
Challenge [Change the CSS of an Element Using jQuery](https://www.freecodecamp.com/challenges/change-the-css-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<script>
  $(document).ready(function() {
    $("target1").css("color","red");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by indefinite0212** [comment]
hi @bhavya2109sharma if you need help solving the challenge you should ask first at [help room](https://gitter.im/FreeCodeCamp/Help) before posting a git hub issue.

**Comment by bhavya2109sharma** [comment]
Okay . thank you

**Comment by LauS1020** [comment]
If you find any of the challenges not working try changing browser, this challenged qwouldnt work in google chrome, but as soon as opened it in internet explorer i passed it, hope this helps :)
