### ISSUE TITLE
Example given doesn't follow one of the user stories

### ISSUE THREAD

**Issue by j0hnc** [freeCodeCamp/freeCodeCamp#15321]
Challenge [Use the Twitchtv JSON API](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36</code>.

I added "brunofin", a user that doesn't exist and it says that it's offline. data.stream === undefined doesn't work anymore.

**Comment by raisedadead** [comment]
We want to update the user stories to user that is valid. Anyone up for checking and updating this?
You would also need to make two PR's for this one against `staging`, and other against `backup/master`

**Comment by padulam** [comment]
@raisedadead I'm up for taking this on, but I'm a little confused as to what we're trying to do. Are we eliminating user story 6?

**Comment by raisedadead** [comment]
@padulam Yes, that is correct. Sorry about the typo in earlier comment. I have updated my previous comment

**Comment by CyberPutty** [comment]
Is anyone going to remove user story 6? I spent a long time trying to fulfill it before thinking that it actually doesn't work anymore. When you click on the example project it also does not fulfill user story 6.
