### ISSUE TITLE
Test seem to pass even if code is incorrect

### ISSUE THREAD

**Issue by Matt-Farncomb** [freeCodeCamp/freeCodeCamp#15329]
Challenge [create-strings-using-template-literals](https://beta.freecodecamp.com/en/challenges/es6/create-strings-using-template-literals) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.

The tests pass if I leave the code as it was origianlly or even if I just type something random as the value for resultDisplay. 

```js


const result = {
  success: ["max-length", "no-amd", "prefer-arrow-functions"],
  failure: ["no-var", "var-on-top", "linebreak"],
  skipped: ["id-blacklist", "no-dup-keys"]
};
// change code below this line
const resultDisplay = null;
// change code above this line
console.log(resultDisplay);
/**
 * should look like this
 * <li class="text-warning">no-var</li>
 * <li class="text-warning">var-on-top</li>
 * <li class="text-warning">linebreak</li>
 **/

```

**Comment by systimotic** [comment]
Thanks for reporting! We're working on fixing this in https://github.com/freeCodeCamp/freeCodeCamp/issues/12698 I'm closing this as a duplicate.

Happy coding!
