### ISSUE TITLE
CodePen to all-HTTPS, breaking all ajax calls to HTTP endpoints

### ISSUE THREAD

**Issue by zapcannon99** [freeCodeCamp/freeCodeCamp#15324]
Challenge [Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

As of June 2, 2017, CodePen has moved to an all HTTPS format. This is has affected all ajax calls to HTTP endpoints and will cause pens to not function properly.

Suggesting instructions be reconsidered for at least the Free Weather App Project.

https://blog.codepen.io/2017/06/02/codepen-now-https/

**Comment by Marmiz** [comment]
Thanks for reporting this issue @zapcannon99.

There are currently discussion about what we can do to avoid this issue like in #12514   If you have any input or suggestion please don't hesitate to reply in one of those threads.

**Comment by raisedadead** [comment]
We should audit all of the codepens both on `backup\staging` and on `staging` branches and update all `http` instances to `https`

This needs to be done on both inside the pen code themselves, and the challenge seed as well.

This can be taken up via multiple PRs. 

Action items:

Contributors: - Audit and make PRs on both branches for changes from `http` to `https` in the challenge seed code.
raisedadead: - As per the need and comments made by contributors update the pens under freeCodeCamps' account.

**Comment by jonathanihm** [comment]
Potentially, we could look into using the Fetch API.  See example: 

https://codepen.io/RvQ/pen/wWjLBd

We could have them switch around http and https, but then we would need to do additional work to get around geolocation which relies on https.

Basic Fetch API support should be available on modern browsers, but the current support is limited here:

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by zapcannon99** [comment]
At least for this challenge, there exists ip location API that uses HTTPS. Aside fromt Fetch, there is https://ipapi.co/. This would be the easiest option to suggest to new coders.

I'm more worried however, that anybody that has used ajax calls to HTTP endpoints for their pens and projects will have non-functional pages. Though, I think raisedadead already has suggested the majority that needs to be done.

**Comment by zapcannon99** [comment]
Also, jonathanihm, I don't think we can have the users switch around HTTP and HTTPS. When using CodePen now, users/coders must connect to the website using HTTPS, which also means that ajax calls to HTTP endpoints will not work. The website has gone all in on HTTPS and all HTTP calls to their website are redone using HTTPS.

**Comment by jonathanihm** [comment]
I see that now, I was reading the workarounds from one of the linked issues  :-).  Would the ipapi.com solution still be able to handle the openweathermap api cors issue?

**Comment by raisedadead** [comment]
> We could have them switch around `http` and `https`

I believe we should be doing this. Campers can easily miss this. We should be doing the migrations as commented earlier.

That said, we are even okay with replacing the weather challenge in favor of something similar on similar lines, that teaches the use of the API.

**Comment by zapcannon99** [comment]
@jonathanihm 
Yes. I confirmed the api works for locating the user's location, and its endpoint is https.

@raisedadead 
I think I may have misunderstood the intention of the poster of that quote. If you mean switch to https, yes I totally agree.

**Comment by jonathanihm** [comment]
On a side note, the codepen http links will automatically forward to https

**Comment by jonathanihm** [comment]
It looks like there are four files that will need to be updated, I can take the last two (04-data-visualization\data-visualization-projects.json and 08-coding-interview-questions-and-take-home-assignments\take-home-interview-projects.json), and leave the first two for anyone who wants to contribute and change the http to https. 

![image](https://user-images.githubusercontent.com/6002459/27047422-ae57b756-4f6d-11e7-8fec-da3e61c7d945.png)

**Comment by raisedadead** [comment]
@jonathanihm thanks for the PR.

Now we need to update the pen's themselves. Can you or others possible help me out in making updates to the necessary pens?

They have to be audited separately on the beta (`staging`) and production (`backup/master`).

You can leave comments in this thread with any minor tweaks that I have to do on those pens (with their links) to update them to `https` compatible.

If they need a complete overhaul feel free to create a separate issue per pen as well (do tag me along) and we can discuss it further.

Thanks for contributing!

**Comment by Manish-Giri** [comment]
I'll take up the first two remaining files. 

@raisedadead I'll report what I can find on updating the pens.

**Comment by jonathanihm** [comment]
Also, what about https://www.apixu.com?  I believe this might be an alternative as I have read in some parts of the web and FCCs message boards.  We would have to do a bit more upgrading of the challenge though.

**Comment by Marmiz** [comment]
@jonathanihm I've tried and successfully used that API in a (5 minutes) showcase project here:

https://codepen.io/Marmiz/pen/zzqNLe

My question is, in case we decide to suggest a different API, what about the current live version and all the campers that are (maybe) struggling with SOP issues?

Do we have a suggested method to avoid errors and help them finishing the pen?
So far the only solution I've seen posted on the forum has been using 
https://cors-anywhere.herokuapp.com/
to parse the request and get back the data from the http endpoint.

**Comment by no-stack-dub-sack** [comment]
@raisedadead @Marmiz While we definitely need to resolve this issue on the production site, if there isn't another API that's free and easy and over https, we could consider @raisedadead's other suggestion for the beta curriculum of a different project that helps teach campers how to work with API's - especially since this project is no longer part of the core curriculum on beta (for this very reason - api projects are too prone to breakage).

**Comment by mierz00** [comment]
@raisedadead I am happy to update the pen using the [apixu](https://www.apixu.com) API, if you still need?

**Comment by mierz00** [comment]
@raisedadead I have fixed up the weather pen [here](https://codepen.io/mierz/pen/YQQLmR?editors=1111).

Notes 
- Removed angular completely and stuck with jQuery. 
- Utilised Dark Sky API, however CORS proxy is required. Loading time is super slow. 
- Now uses geolocation rather than ip API.
- Added "Loading..." message. 
- Removed some of the weather icon styles. They are still in the CSS.

If you or anyone else would like to add more icons to suit Dark Sky's icon list feel free. Currently only cloudy, rain, snow, and clear work.  

If there are any bugs let me know.

I am also happy to submit a pull request to fix the page on FFC.

**Comment by raisedadead** [comment]
@mierz00 thanks for working on this. I would rather update the current CodePen (becasue of the places it links to using your code) if you do not mind.

I'll let you know soon how this goes.

Thanks a lot once again for your contribution!

**Comment by mierz00** [comment]
@raisedadead 
No problem at all. 
Am I okay to submit a pull request to remove this paragraph 

"_Use an Internet Protocol API to get user location (ex. IP-API) and then use the OpenWeatherMap API for the weather. Be sure to connect to CodePen.io via http://._"

from the main site? (Purely as a learning experience, my first pull request)

**Comment by joshmorel** [comment]
I was able to use Yahoo Weather API with Geolocation and Fetch successfully. Yahoo Weather doesn't require a key and allows CORS.

https://codepen.io/joshmorel/pen/KqxXqg

Any thoughts? This is certainly an option!

**Comment by artoodeeto** [comment]
hello. im new. probably im too late but what i did to bypass the issue of CORS i used the heruko cors anywhere. heres the sample API that i used. 'https://cors-anywhere.herokuapp.com/http://api.openweathermap.org/data/2.5/weather?

and heres the codepen: https://codepen.io/artoo/pen/bRmrzz
thanks
