### ISSUE TITLE
Grammar error in challenge: "Waypoint: Ditch Custom CSS for Bootstrap"

### ISSUE THREAD

**Issue by MrTortoro** [FreeCodeCamp/FreeCodeCamp#1532]
It's really silly actually.
In the requeriments for completing the challenge there are places written "You" instead of "Your".

Thanks.
![captura de tela 2015-08-04 as 17 55 34](https://cloud.githubusercontent.com/assets/13291953/9072536/222c41fe-3ad2-11e5-8f6d-884963b3c95f.png)

**Comment by benschenker** [comment]
This has been fixed
