### ISSUE TITLE
Test case bug in 'Generate Random Whole Numbers within a Range'

### ISSUE THREAD

**Issue by mvroehling** [freeCodeCamp/freeCodeCamp#15322]
#### Challenge Name

[Generate Random Whole Numbers within a Range](https://www.freecodecamp.com/challenges/generate-random-whole-numbers-within-a-range)

#### Issue Description

One can simply use the code of the given function`ourRandomRange(ourMin, ourMax)` to solve the challenge.

However, calling this functions fails the test with the error message: "randomRange should use both myMax and myMin, and return a random number in your range. "

#### Your Code

```js
// Example
function ourRandomRange(ourMin, ourMax) {
  return Math.floor(Math.random() * (ourMax - ourMin + 1)) + ourMin;
}

ourRandomRange(1, 9);

// Only change code below this line.
function randomRange(myMin, myMax) {
  return ourRandomRange(myMin, myMax); // Test Fails
}

// Change these values to test your function
var myRandom = randomRange(5, 15);
```

```js
// Example
function ourRandomRange(ourMin, ourMax) {
  return Math.floor(Math.random() * (ourMax - ourMin + 1)) + ourMin;
}

ourRandomRange(1, 9);

// Only change code below this line.
function randomRange(myMin, myMax) {
  return Math.floor(Math.random() * (myMax - myMin +1) + myMin); // Test success
}

// Change these values to test your function
var myRandom = randomRange(5, 15);
```
See how inlining the code from `ourRandomRange(ourMin, ourMax)` suddenly passes the test

**Comment by raisedadead** [comment]
Isn't that what the instructions aim to? Do you feel this challenge could be done in a more abstract way while teaching the logic?

Open for suggestions.

**Comment by mvroehling** [comment]
Either solution should pass the test, as it uses the exact same formula.

**Comment by erictleung** [comment]
@mvroehling very clever answer 😄 I agree that your answer is correct but that is not the point of the challenge. The challenge really is for the learner to break down the function, write it for themselves, and understand *how* that function is giving them a random number between two numbers. We're open to suggestions on how we can convey this and still teach them something without losing them in the mathematic translation of the random number expression.
