### ISSUE TITLE
Incorrect Reference Link

### ISSUE THREAD

**Issue by nickpalmer789** [FreeCodeCamp/FreeCodeCamp#1533]
On http://www.freecodecamp.com/challenges/zipline-show-the-local-weather there is a link that is intended to direct you to the reference page for $.getJSON() but it instead directs you to the reference page for $.each().

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1394

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help!-I've-Found-a-Bug
