### ISSUE TITLE
splice() not working

### ISSUE THREAD

**Issue by jsonprry** [freeCodeCamp/freeCodeCamp#15339]
Challenge [Seek and Destroy](https://www.freecodecamp.com/challenges/seek-and-destroy) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.

I'm trying to use splice() to remove items from an array, but it's removing all items _except_ the ones in the splice() parameters. It's keeping the items that I'm trying to get rid of.

My code:
```javascript

function destroyer(arr) {
  // Remove all the values
  
  var filterValues = [];
  
  // Run through extra arguments
  for ( var i = 1; i < arguments.length; i++ ) {
    //run through arr to push matches to filterValues
    for ( var j = 0; j < arr.length; j++ ) {
      if ( arr[j] === arguments[i] ) {
        filterValues.push(j);
      }
    }
    
  }
  
  filterValues.sort(function(a, b) { return b - a; });
  
  for ( i = filterValues.length-1; i >= 0; i--) {
    arr.splice(filterValues[i], 1);
  }
  
  return arr;
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3);

```

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
