### ISSUE TITLE
Inappropriate use of variables teaches bad habit

### ISSUE THREAD

**Issue by willnwhite** [freeCodeCamp/freeCodeCamp#15333]
Challenge [Convert Celsius to Fahrenheit](https://www.freecodecamp.com/challenges/convert-celsius-to-fahrenheit) has an issue. It teaches an inappropriate use of variables (a bad habit I often see campers using), because it's a bad example to use for teaching variables. I would certainly not write code like this:

```javascript
function convertToF(celsius) {
  var fahrenheit;
  fahrenheit = celsius * 9 / 5 + 32;
  return fahrenheit;
}
```

There's unnecessary creation of and assignment to a variable. I'm sure most of us would write:

```javascript
function convertToF(celsius) {
  return celsius * 9 / 5 + 32;
}
```

If it's important to get the word "fahrenheit" into the code for clarity, it should be in the function's name (convertToFahrenheit).

**Comment by willnwhite** [comment]
An appropriate use of variables would be to refactor code that re-uses data, especially the result of a calculation. I will try to make an example.

**Comment by raisedadead** [comment]
@willnwhite thanks a lot for the feedback, yup I see what you are trying to point. Please do suggest any examples that better illustrates this.

However we do need to keep the underlying philosophy that the challenge should explain concepts in lieu of best practice (like code optimization). At this stage in the course the users are just understanding the basics.

Nonetheless a more real life example is not an bad idea at all.

Thanks.

**Comment by jonathanihm** [comment]
I would like to point out that this lesson only appears roughly 20 lessons after just learning how to create a variable.  Perhaps we could create new lessons that emphasize more fluent code, but I feel like the suggestion may take users out of their "comfort" zone.

**Comment by a8t** [comment]
In [Stand In Line](https://www.freecodecamp.com/challenges/stand-in-line): By creating a variable for arr.shift() and returning it (as in the example in the OP of this thread), we get the exact same result but the answer is not marked correct!

**Comment by dhcodes** [comment]
@jonathanihm this lesson is moved later in the beta site so that aspect is addressed. I'm fine with OP's suggestion to change to `convertToFahrenheit` but I'm not sure how to approach the nuance of getting them to write "better code". Over time, they will likely see many approaches to writing cleaner code, but there is a debate about what is "better" and "better for whom".

**Comment by jonathanihm** [comment]
I think this issue is more of an opinion rather than a bug

**Comment by willnwhite** [comment]
Convert Celsius to Fahrenheit is about testing your learning of variables and arithmetic. So I've removed the function (functions haven't been taught yet and it is [confusing learners]()), and tested whether the learner can assign 30 to celsius, use that variable in more than one place, and use the arithmetic operators.

```
var celsius;
var fahrenheit;
var kelvin;
```

```
var celsius = 30;
var fahrenheit = celsius * 9 / 5 + 32;
var kelvin = celsius + 273;
```

**Comment by forkerino** [comment]
@a8t It should work for Stand In Line as well, but you'd have to declare the variable after the  `arr.push(item);`

**Comment by jonathanihm** [comment]
Thanks for your example!

In my opinion, it looks like we might be over complicating this.  The note on the bottom of the lesson also explains not to worry about the function and will be covered later on.  It just seems to be a lot of discussion over the need to assign a variable or not (And I am not saying you are wrong at all).  Maybe we can have additional lessons later on that reinforce better code practices?

**Comment by willnwhite** [comment]
I'll admit that I am not completely satisfied with these examples. That could be because, again, I wouldn't write code like this. Just seeing it teaches learners to use global variables, another bad habit. I think we are digging at a bigger problem with the curriculum, which is that all the variables challenges use global variables, because variables are taught before functions. That is a separate issue to this one, so I'm not sure where this issue goes from here.

**Comment by willnwhite** [comment]
If functions were taught before variables, global variables could be avoided, and I believe we could come up with examples to teach the appropriate use of variables, solving the original issue. It's telling to me that the first Basic JavaScript challenge where learners make something useful, Convert Celsius to Fahrenheit, involves a function.

Teaching functions before variables would also mean teaching functions before arithmetic, as arithmetic is currently taught with variables. Perhaps a simpler function than convertToFahrenheit for beginners to write would be a currency conversion. Function syntax and `*` would be introduced at the same time. E.g.

```js
function convertToUSD30Jun2017(EUR) {
  return EUR * 1.14;
}
```
