### ISSUE TITLE
Beta Data Visualization with D3: Work with Dynamic Data in D3 - append()

### ISSUE THREAD

**Issue by dev1lbop** [freeCodeCamp/freeCodeCamp#15330]
Challenge [work-with-dynamic-data-in-d3](http://beta.freecodecamp.com/en/challenges/data-visualization-with-d3/work-with-dynamic-data-in-d3) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:51.0) Gecko/20100101 Firefox/51.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I keep receiving the error that I'm not including the "USD" on to each h2. I believe this is a bug can someone confirm if it's me or just my bad D3 coding ability.

Thanks

```html


<body>
  <script>
    const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
    
    d3.select("body").selectAll("h2")
      .data(dataset)
      .enter()
      .append("h2")
      // Add your code below this line
       //var u = " USD";
    .text(dataset, function (d, i) {
        return dataset[i].data.append("USD");
      
    }) 
      
      
      // Add your code above this line
  </script>
</body>

```

**Comment by williamsb** [comment]
I also had a problem with this challenge related to issue #15286. However, I think there might also be a problem with your code.

**Comment by dev1lbop** [comment]
Thanks! It was a problem with my code...closing.

**Comment by jjmgauna** [comment]
<body>
  <script>
    const dataset = [12, 31, 22, 17, 25, 18, 29, 14, 9];
    
    d3.select("body").selectAll("h2")
      .data(dataset)
      .enter()
      .append("h2")
      // Add your code below this line
      
      .text((d)=>d+" USD");
      
      // Add your code above this line
  </script>
</body>
