### ISSUE TITLE
Beta- Waypoint: Use Comments to Clarify Code

### ISSUE THREAD

**Issue by sonorangirl** [FreeCodeCamp/FreeCodeCamp#1534]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-comments-to-clarify-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Asks you to add a comment to the top of html.

Added my comment, but the tests are all failing, not even sure why the second test is needed.

<img width="766" alt="screen shot 2015-08-04 at 2 50 45 pm" src="https://cloud.githubusercontent.com/assets/6051437/9073739/6aa653bc-3ab8-11e5-8919-658194583812.png">

**Comment by cristianvnica** [comment]
On the same waypoint, before to write anything, we get this errors which i believe should not be there:
<img width="578" alt="screen shot 2015-08-05 at 11 21 48 am" src="https://cloud.githubusercontent.com/assets/3229023/9081369/66de27e4-3b64-11e5-8133-46609d0cb6a9.png">

**Comment by zeffii** [comment]
Also.. this happens (notice the existence of `-->`) on the emulator.
![image](https://cloud.githubusercontent.com/assets/619340/9327874/6631dea4-45a4-11e5-9f1b-f5b905afffec.png)

**Comment by benschenker** [comment]
Looks like this has all been fixed
