### ISSUE TITLE
Basic JS: Returning Boolean Values from Functions. Misleading information?

### ISSUE THREAD

**Issue by CodKingNZ** [freeCodeCamp/freeCodeCamp#15343]
I've spent a bit of time on this one, I tried all sorts using comparisons because that's what the question's information talks about. I then punched in what I thought was the 'cheaty' answer: "return a < b;" and of course it was correct.

I did some investigating and found this seems to be the answer but I'm not satisfied. If this indeed is correct then my question is; why does it raise the topic of comparisons, give 2 examples using ===, refer back to a question titled: Comparison with the Equality Operator and then the answer is essentially "<"???

Thanks for looking at my question!

Challenge [Return Early Pattern for Functions](https://www.freecodecamp.com/challenges/return-early-pattern-for-functions) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
function abTest(a, b) {
  // Only change code below this line
  
  
  
  // Only change code above this line

  return Math.round(Math.pow(Math.sqrt(a) + Math.sqrt(b), 2));
}

// Change values below to test your code
abTest(2,2);

```

**Comment by raisedadead** [comment]
> I did some investigating and found this seems to be the answer but I'm not satisfied. If this indeed is correct ...

@CodKingNZ Unfortunately that is not the correct understanding of the challenge, I advise you take this up in the chat room or the forum for assistance with the coding.
