### ISSUE TITLE
Upgrade Facebook GraphAPI to Version 2.9

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15340]
Facebook just sent me a notice that:

> Your App, Free Code Camp, is currently accessing Graph API v2.3 which will reach the end of its 2-year lifetime on 10 July, 2017. We estimate 1 endpoint that Free Code Camp calls will be impacted by this change and may stop working after the automatic upgrade push. To ensure a smooth transition, please migrate all calls to Graph API v2.4 or higher. Use the API Upgrade Tool to understand exactly how this change will impact your app.

> Note: If you do not see any impacted calls in the API Upgrade Tool, your app/code may not be affected by this upgrade.

When I use the tool, this is what I see: 

![](https://www.evernote.com/l/Ar_NTQmShOtB04nXf8Z69PM6xs-jyOoLKjQB/image.png)

According to Facebook, about 400 people sign in using the Facebook oauth option per week.

They recommend upgrading to the latest version of the API - v2.9.

@raisedadead @BerkeleyTrue Considering that we're about to roll out passwordless when we ship Beta, do we need to bother upgrading this?

**Comment by raisedadead** [comment]
@QuincyLarson we might need upgrading to API well before that on the production, but I'll explore more on the exact API call that is affected.

Do you mind adding me as a developer on the app's setting page in the facebook dasboard?

**Comment by raisedadead** [comment]
> According to Facebook, about 400 people sign in using the Facebook oauth option per week.

Do you have an insight if these are unique logins? Or does Facebook limit that knowledge to us?

**Comment by QuincyLarson** [comment]
@raisedadead I've added you as a developer on our Facebook app. From their wording, it looks like these are unique users.

**Comment by raisedadead** [comment]
@QuincyLarson I checked and seems that there is potentially **no change to be done**. I did some housekeeping with the app by updating the icon (it was the old one) and the name, since I was at it.

Let's keep this open till the deadlines just in case, post which we can simply close if it all goes well.

**Comment by raisedadead** [comment]
@QuincyLarson Can you confirm that we are using this app at only one instance that is for freeCodeCamp's legacy social login.

If that's the case please feel free to close this issue, there is no upgrade action on our side.

**Comment by BerkeleyTrue** [comment]
@raisedadead Yes that is correct

**Comment by raisedadead** [comment]
Awesome!
