### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by kalpu7** [freeCodeCamp/freeCodeCamp#15346]
Challenge [Import a Google Font](https://www.freecodecamp.com/challenges/import-a-google-font) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp
</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by indefinite0212** [comment]
Hi @kalpu7 , if you need help with a challenge you should ask at [help room](https://gitter.im/FreeCodeCamp/Help).

**Comment by anthonygallina1** [comment]
The h2 class need to be written in the style for the font family. Also the font link needs to be added as per the instructions on the left in the challenge.
