### ISSUE TITLE
solve this plzz...

### ISSUE THREAD

**Issue by siddu530** [freeCodeCamp/freeCodeCamp#15347]
Challenge [Golf Code](https://www.freecodecamp.com/challenges/golf-code) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function golfScore(par, strokes) {
  // Only change code below this line
  
  
  return "Change Me";
  // Only change code above this line
}

// Change these values to test
golfScore(5, 4);

```

**Comment by indefinite0212** [comment]
Hi @siddu530 if you need help with the challenge, you should ask at [JavaScript Help room](https://gitter.im/FreeCodeCamp/HelpJavaScript)

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
