### ISSUE TITLE
Doesn't test for spread operator

### ISSUE THREAD

**Issue by KerrGrah** [freeCodeCamp/freeCodeCamp#15351]
#### ES6: Use the Spread Operator to Evaluate Arrays In-Place
https://beta.freecodecamp.com/en/challenges/es6/use-the-spread-operator-to-evaluate-arrays-inplace

#### It is possible to pass the tests, including the "test for spread operator" test, using slice()
```

const arr1 = ['JAN', 'FEB', 'MAR', 'APR', 'MAY'];
const arr2 = arr1.slice(); // change this line
arr1.push('JUN');
console.log(arr2); // arr2 should not be affected



```

**Comment by KerrGrah** [comment]
found this:
https://github.com/freeCodeCamp/freeCodeCamp/issues/12698
I apologise.

**Comment by raisedadead** [comment]
@KerrGrah no worries, thanks for trying out the beta and reporting. Please report any issues that you find. Happy hunting!
