### ISSUE TITLE
I passed the next challenge for decrementing using the same solution.

### ISSUE THREAD

**Issue by Edwardpanas** [freeCodeCamp/freeCodeCamp#15359]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myVar = 87;

// Only change code below this line
myVar = ++myVar;


```

**Comment by raisedadead** [comment]
I cannot reproduce it on 
https://www.freecodecamp.com/challenges/decrement-a-number-with-javascript

Please provide some screenshots.

**Comment by Edwardpanas** [comment]
It was on the lesson before the link you sent.  (https://www.freecodecamp.com/challenges/increment-a-number-with-javascript <https://www.freecodecamp.com/challenges/increment-a-number-with-javascript>)

Here is the screen shot.  I believe I met all 4 requirements, but the 2nd one still shows a red X like I didn’t change the line but I did.

Thank you,
Ed

**Comment by raisedadead** [comment]
@Edwardpanas 

Please visit this link https://github.com/freeCodeCamp/freeCodeCamp/issues/15359 for the issue on GitHub. 
Please clarify the exact steps and posting screenshots on the comments (you can drag and drop images in the comments window).

Email attachments do not reach us.

Thanks.

**Comment by dhcodes** [comment]
Also cannot replicate.

**Comment by Edwardpanas** [comment]
Here are the steps with associated screenshots.

**STEP 1:** start of exercise
![step1](https://user-images.githubusercontent.com/13541847/27139654-9bb8392e-50f1-11e7-9685-30a09b62eb80.png)

**STEP 2:**  first attempt changing from `myVar = myVar + 1;` to `myVar = myVar++;`
![step2](https://user-images.githubusercontent.com/13541847/27139761-dbc41f42-50f1-11e7-8834-278394530bd7.png)

STEP 3: second attempt (and should be correct) changing from `myVar = myVar + 1;` to `myVar = ++myVar;`.  This solution worked in the decrement exercise  `myVar = --myVar;` so it should work here, right?
![step3](https://user-images.githubusercontent.com/13541847/27139870-1dbf79a0-50f2-11e7-95af-06399b134282.png)

**Comment by dhcodes** [comment]
I see what you mean now. Your solution to the decrement exercise shouldn't have worked but it's missing a test. I'll take this up.

**Comment by raisedadead** [comment]
@Edwardpanas thanks a lot for the additional clarifications, thanks @dhcodes for taking this up!
Happy coding!

**Comment by Edwardpanas** [comment]
It was on the lesson before the link you sent.  (https://www.freecodecamp.
com/challenges/increment-a-number-with-javascript)

Here is the screen shot.  I believe I met all 4 requirements, but the 2nd
one still shows a red X like



On Jun 14, 2017, at 12:38 AM, mrugesh mohapatra <notifications@github.com>
wrote:

I cannot reproduce it on
https://www.freecodecamp.com/challenges/decrement-a-number-with-javascript

Please provide some screenshots.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/15359#issuecomment-308316984>,
or mute the thread

**Comment by dhcodes** [comment]
@Edwardpanas According to the directions though, the way you solved it (while possible) is not in keeping with the concept trying to be taught, namely that you can increment or decrement a variable *without* reassigning it by simply doing `myVar++;` or `myVar--` so really your solution should not have worked on either. Do you agree @raisedadead? I don't want to remove some actual functionality of JS but in this case the point is to teach this specific concept, no? I wrote my Regex fix accordingly.

**Comment by Edwardpanas** [comment]
It was on the lesson before the link you sent.  (https://www.freecodecamp.
com/challenges/increment-a-number-with-javascript)

Here is the screen shot.



On Jun 14, 2017, at 12:38 AM, mrugesh mohapatra <notifications@github.com>
wrote:

I cannot reproduce it on
https://www.freecodecamp.com/challenges/decrement-a-number-with-javascript

Please provide some screenshots.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/15359#issuecomment-308316984>,
or mute the thread

**Comment by texas2010** [comment]
@Edwardpanas it seems you trying to send the screenshot to us. please use GitHub for upload screenshot. we can't see your screenshot though email.

**Comment by Edwardpanas** [comment]
Thank you for the clarification @dhcodes on this answer.  This section on JavaScript basics is a fairly simple review so some of my solutions have been overthinking the question.  I submitted the simpler increment code and it cleared the exercise for me.  Thanks again for your help!
