### ISSUE TITLE
Settings: "Are you available for hire?" button

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15357]
We need to add a button to our settings that allows campers to mark themselves as "available for hire". This won't change anything visible about their profile, but it will let us know that we can send that camper some career-related advice through email, and better track campers who get jobs.

Here's what this interface looks like on GitHub:

![your_profile](https://user-images.githubusercontent.com/985197/27104156-d6db62b6-5050-11e7-8d24-ff27f6a7b273.png)

Here's what it looks like on CodePen:
![](https://puu.sh/wjbHH/b606f8513c.png)

We may be able to turn it into a single button that toggles on and off like:

"No, I'm not available for hire" -> "Yes, I am available for hire"

**Comment by padulam** [comment]
How about the following?

![fccjobsettings](https://user-images.githubusercontent.com/11588747/27145207-de19feae-5102-11e7-8806-6b0443d0a3fc.png)

This would be similar to the design of the other items on the settings page. I'd be interested in taking this on once everyone agrees on the final design.

**Comment by QuincyLarson** [comment]
@padulam perfect! I like it! I would add a question mark to the "Available for hire?" text.
