### ISSUE TITLE
Return largest number in Arrays error with test cases

### ISSUE THREAD

**Issue by warriopradeep** [freeCodeCamp/freeCodeCamp#15353]
Challenge [Return Largest Numbers in Arrays](https://www.freecodecamp.com/challenges/return-largest-numbers-in-arrays) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function largestOfFour(arr) {
  // You can do this!
  var q=[];
  var max=0;
  for (var i =0; i<arr.length;i++){
    var r=arr[i];
    for(var j=0;j<4;j++){
      if (arr[i][j]>max){
        max=arr[i][j];
      }     
    }
    q.push(max);
    
  }
  return q;

}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

```

**Comment by jonathanihm** [comment]
Hi there,

It looks like your code contains a bug!  Please feel free to ask for help in the chatroom or the message boards.  Basically, you are testing the max value overall in each array and not the max value for each array.

Cheers!

**Comment by raisedadead** [comment]
Hi @jonathanihm 
Thanks a lot for your comments. Please note we strictly discourage any guidance to coding assistance on the issue tracker (hence the moderation... 😅 ). 

Hi @warriopradeep 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
