### ISSUE TITLE
Filter Arrays with filter has confusing text instruction and tests

### ISSUE THREAD

**Issue by cglsoft** [freeCodeCamp/freeCodeCamp#15354]
Challenge [Filter Arrays with filter](https://www.freecodecamp.com/challenges/filter-arrays-with-filter) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var oldArray = [1,2,3,4,5,6,7,8,9,10];

// Only change code below this line.

var newArray = oldArray.filter( function(val){
  return val <= 5; // Wrong condiction,   ( > 5 correct !! but, not by pass! )
});

```

**Comment by raisedadead** [comment]
@cglsoft 

Your code is NOT correct (i.e you have to have an array that has `< 6` in its elments)

As per the instructions:
> Use filter to create a new array with all the values from oldArray which are **less than 6**. The oldArray should not change.

> You should have **filtered out** all values from the array that are greater than 5.

I can see that this can create confusion amongst new users.

Potential contributors, please update the test case message as such:
> You should have filtered out all values from the array that are greater than 5.

to
> You should have filtered out all values from the array so that `newArray` has values less than 6.

Note before making a pull request make sure to our read [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and testing your changes locally.

**Comment by abkunal** [comment]
@raisedadead Will you please tell me where can I find this file in the repo? I am not able to find a challenge with this name in the repository. Thanks

**Comment by systimotic** [comment]
@abkunal Thanks for taking a look! It looks like we're teaching the filter method [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/d424b7331ded350e297387b134f5ab8e85631839/seed/challenges/02-javascript-algorithms-and-data-structures/functional-programming.json#L552) in the beta. It looks like this issue is no longer present there.

@raisedadead Can this be closed?

**Comment by raisedadead** [comment]
@systimotic yes, thanks for checking. I missed this challenge being updated/removed on beta
