### ISSUE TITLE
RGB to mix colors challenge not working

### ISSUE THREAD

**Issue by leul-m** [freeCodeCamp/freeCodeCamp#15365]
Challenge [Use RGB to Mix Colors](https://www.freecodecamp.com/challenges/use-rgb-to-mix-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: rgb(255,0,0);
  }
  .orchid-text {
    color: rgb (218,112,214);
  }
  .sienna-text {
    color: rgb(160,82,45);
  }
  .blue-text {
    color: rgb(0,0,255);
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>

```

**Comment by anthonygallina1** [comment]
Please take this issue into chat if needed.  Your h1  text is incorrect, it is not a bug.

**Comment by GSGV** [comment]
I'm having this same issue! the results are coming up correct, and i can't find any errors... what exactly is the incorrect text?

**Comment by texas2010** [comment]
@GSGV 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by Jkolly** [comment]
<style>
  .red-text {
     color: rgb(255,0,0)
  }
  .orchid-text {
    color: rgb(218,112,214)
  }
  .sienna-text {
    color: rgb(160,82,45)
  }
  .blue-text {
    color: rgb(0,0,255)
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>

Even with the above, it is still saying incorrect.

**Comment by texas2010** [comment]
@Jkolly 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by Jkolly** [comment]
Ok. I just did and the issue has been sorted out.
Thank you.

**Comment by StowellRyan** [comment]
<style>
  .red-text {
    color: rgb(255,0,0)
  }
  .orchid-text {
    color: rgb(218,112,214)
  }
  .sienna-text {
  color: rgb(160,82,45)
  }
  .blue-text {
    color: rgb(0,0,255)
  }
</style>

<h1 class="red-text">I am red!</h1>

<h1 class="orchid-text">I am orchid!</h1>

<h1 class="sienna-text">I am sienna!</h1>

<h1 class="blue-text">I am blue!</h1>
I am sure this is correct but says it is not. please help.

**Comment by CosmicDog2000** [comment]
@StowellRyan Just use the hex code supplied in the instructions.

**Comment by CosmicDog2000** [comment]
@StowellRyan You're missing the semi-colons after the color definitions.

**Comment by StowellRyan** [comment]
@CosmicDog2000, Thank you, the smallest thing makes all the difference. on prior lessons/examples it does not show the ; after the rgb( ). But it totally makes sense.
