### ISSUE TITLE
Grammatical Error: a instead of an before the h2 tag. 

### ISSUE THREAD

**Issue by cRAN-cg** [freeCodeCamp/freeCodeCamp#15362]
Challenge [Headline with the h2 Element](https://www.freecodecamp.com/challenges/headline-with-the-h2-element) has an issue.

Content:
```
Add an h2 tag that says
```
This can be simplest issue to be resolved. Just replace ```an``` with ```a```.

**Comment by LiamMorgan** [comment]
I'll do this.

**Comment by zayn1914** [comment]
<h1>Hello World</h1>
<h2>hello world"CatPhotoApp".</h2>

**Comment by zayn1914** [comment]
<h1>Hello World</h1>
<h2>hello world"CatPhotoApp".</h2>

**Comment by zayn1914** [comment]
![sfasfs](https://user-images.githubusercontent.com/28483872/27179225-53086f38-51d6-11e7-9cbb-f91b2f6034d4.JPG)

**Comment by texas2010** [comment]
@zayn1914 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by dhcodes** [comment]
See: https://www.quora.com/Is-it-an-honor-or-a-honor-Which-is-grammatically-correct. I'm not sure this should be changed.

**Comment by erictleung** [comment]
@LiamMorgan I agree with @dhcodes on this one, although my decision based on what sounded and felt more natural :sweat_smile:

**Comment by raisedadead** [comment]
Thanks @erictleung @dhcodes
