### ISSUE TITLE
CSS Naming Methodology, Unit and Integration Testing

### ISSUE THREAD

**Issue by Grimlek** [freeCodeCamp/freeCodeCamp#15367]
This isn't an issue but more so of a feature. I am not sure if this has been mentioned already and decided upon but I wanted to bring it up. CSS naming methodology will benefit many in the lines of reusable, specificity, maintainability and modularized css. Also with the non profit organization section you will have almost 0 conflicts when two or more people are working with CSS. BEM is the one i recommend but its more based on personal preference....

Unit and Integrations in my opinion is a must have feature just for any server side programming language. We all know the benefits of this. 

My apologies if this has already been mentioned.

**Comment by raisedadead** [comment]
@Grimlek awesome! Yes, our CSS need ❤️ and lots of it (the look is fine, but it breaks and is hard to understand at times).
 
While this is blocked until the layout goes in with #14707 

CSS naming rules and I was thinking something along the lines of https://www.styled-components.com/ would be great.
That would let us have a strong testing in place.

Thanks for bringing this up.

/cc @BerkeleyTrue @QuincyLarson
