### ISSUE TITLE
I don't change code below this line, but site say that I do.

### ISSUE THREAD

**Issue by helder-rangel** [freeCodeCamp/freeCodeCamp#15368]
Challenge [Storing Values with the Assignment Operator](https://www.freecodecamp.com/challenges/storing-values-with-the-assignment-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 OPR/45.0.2552.888</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var a = 7;
var b = a;

// Only change code below this line


```

**Comment by CosmicDog2000** [comment]
They don't want you to change their setup (i.e. declare var b = a). You should write an operation below the line that *changes* the value of b.
