### ISSUE TITLE
Title Case a Sentence

### ISSUE THREAD

**Issue by deNatallia** [freeCodeCamp/freeCodeCamp#15361]
Challenge [Title Case a Sentence](https://www.freecodecamp.com/challenges/title-case-a-sentence) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function titleCase(str) {
  var arr=str.split(' ');
  var newstr="";
  for (i=0; i<arr.length; i++){
     newstr+=arr[i].charAt(0).toUpperCase();
    for(j=1; j<arr[i].length;j++){
    newstr+=arr[i].charAt(j).toLowerCase();
      }
    newstr+=" ";
  }
  
  return newstr;
}


titleCase("I'm a little tea pot");
titleCase("sHoRt AnD sToUt");
titleCase("HERE IS MY HANDLE HERE IS MY SPOUT");

```

**Comment by abkunal** [comment]
Take a look at line with code `newstr+=" ";`
What do you think will happen when the last word of the array is handled?
