### ISSUE TITLE
Help button redirects to wrong chat room 

### ISSUE THREAD

**Issue by raiden357** [freeCodeCamp/freeCodeCamp#15363]
Challenge [Build a Roguelike Dungeon Crawler Game](https://www.freecodecamp.com/challenges/build-a-roguelike-dungeon-crawler-game) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0</code>.

When you click the help button it takes you to the data viz gitter room

**Comment by dhcodes** [comment]
@raiden357 DataViz is currently the recommended room for React questions and challenges. The forum is another good resource.
