### ISSUE TITLE
"Create a Form Element" Challenge line 29

### ISSUE THREAD

**Issue by rilelykaniewski** [freeCodeCamp/freeCodeCamp#15379]
#### Challenge Name

Create a Form Element

#### Issue Description

'>' is missing after '<h2' in line 29. 

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Sony Viao

#### Your Code

```js



```

**Comment by jonathanihm** [comment]
I am not able to see an issue here.  Could you have possibly deleted the closing bracket?  Try resetting the code and take a screenshot if you are seeing the same thing.  It should look like this:

`<h2 class="red-text">CatPhotoApp</h2>`

**Comment by raisedadead** [comment]
Please provide the details as asked in the original issue template, including screen shots, your complete code.

Thanks.

**Comment by rilelykaniewski** [comment]
Issue resolved mistake on my part.
My bad
