### ISSUE TITLE
Remove the views for CoC, Privacy and the ToS

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#15371]
#### Issue Description

~~The Beta Code of Conduct was updated but not the production one.~~
~~Updated: https://beta.freecodecamp.com/en/code-of-conduct ~~
~~Not updated: https://freecodecamp.com/en/code-of-conduct~~

Update(@raisedadead) :

The pages for code-of-conduct, privacy-policy and terms-of-service have moved to the independent static repos.
We just need to remove the routes and the views from the main repo.
This should happen once the redirects are done.

Thanks !!

**Comment by systimotic** [comment]
Good catch @mstellaluna! This has been resolved through https://github.com/freeCodeCamp/freeCodeCamp/issues/15474, so I'm closing this.
