### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by haysus15** [freeCodeCamp/freeCodeCamp#15382]
Challenge [Escaping Literal Quotes in Strings](https://www.freecodecamp.com/challenges/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr="I am a \"double quoted\"string inside\"double quotes\"."; // Change this line



```

**Comment by padulam** [comment]
@haysus15 It looks like the challenge is functioning fine. I recommend checking the spacing on your string.

**Comment by anthonygallina1** [comment]
Challenge works here.Checking spacing like in the example. Also I think you may forgot to escape something.

**Comment by anthonygallina1** [comment]
Please check in chat for more assistance.
