### ISSUE TITLE
Map the Debris uses a straight equality check for double precision floating point numbers numbers.

### ISSUE THREAD

**Issue by Cyberdr8gon** [freeCodeCamp/freeCodeCamp#15386]
Challenge [map-the-debris](http://beta.freecodecamp.com/en/challenges/intermediate-algorithm-scripting/map-the-debris) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This solution produces the correct answers as shown in the console logs with a variance small enough to be attributed to checking for equality between two floating point numbers. Because you are looking for a specific floating point number, any change in order of operations of calculating the orbital period will possibly produce a different result because of floating point rounding errors. 
The test for this should test the difference between the two values and check if it is less than 4 epsilon for IEEE double precision numbers at most. This is due to the rounding errors that could possibly propagate through the result. Due to the use of the exponent function to compute the orbital period, the possible error must be far higher than epsilon. It is 0.2935382368887076 in my case.

Another comparison operator should be used for this test.

```js


function orbitalPeriod(arr) {
  var GM = 398600.4418;
  var earthRadius = 6367.4447;
  return arr.map(function(el) {
    return {
      name: el.name,
      orbitalPeriod: 2 * Math.PI * Math.sqrt((Math.pow(el.avgAlt + earthRadius, 3))/(GM)),
    };
  });
}

console.log(orbitalPeriod([{name : "sputnik", avgAlt : 35873.5553}]));
console.log(orbitalPeriod([{name: "iss", avgAlt: 413.6}, {name: "hubble", avgAlt: 556.7}, {name: "moon", avgAlt: 378632.553}]));


orbitalPeriod([{name : "sputnik", avgAlt : 35873.5553}]);

```

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
