### ISSUE TITLE
General Annoyance - scrolling in the waypoints (text editor vs...)

### ISSUE THREAD

**Issue by matthewsvm** [FreeCodeCamp/FreeCodeCamp#1538]
I'm on a Mac OSX.  It's "easier" to scroll (using the two-finger scroll on my mac) when I put my mouse on the off-white space between the text editor and the description, rather than being able to scroll easily in the text editor alone.  

I've noticed that in beta there are scroll bars (perhaps to help with this issue) but it replaces it with a new problem. Once you hit the bottom (or top) of the editor, the scrolling doesn't stop and the editor moves out of view.  Or another way to put it is that the scrolling continues to scroll the whole page instead of stopping, and that makes you have to scroll the whole page now to get the editor back in view.  The sam over-scrolling issue results from scrolling the instructions area.  Also, I still find scrolling the editor to be stubborn (needing to "overscroll" to get movement).

Related to this...in order to avoid the scrolling annoyance, I tried just using the cursor + arrow keys on the keyboard in the text area.  if you scroll down that way, the bottom of the text editor area doesn't even show up and then you have to use the scroll method to finish it anyway...which brings up the same problems as stated above.

Sorry if this is a duplicate.  I couldn't find it.

**Comment by benschenker** [comment]
Hey @matthewsvm, is this still an issue for you?

**Comment by BerkeleyTrue** [comment]
This has since been addressed.

Happy Coding!
