### ISSUE TITLE
myVar = myVar should be changed?

### ISSUE THREAD

**Issue by zhuangyin8** [freeCodeCamp/freeCodeCamp#15381]
Challenge [Increment a Number with JavaScript](https://www.freecodecamp.com/challenges/increment-a-number-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3131.0 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myVar = 87;

// Only change code below this line
myVar = myVar++ + 1;


```

**Comment by zhuangyin8** [comment]
myVar++;

**Comment by zhuangyin8** [comment]
++myVar;

**Comment by anthonygallina1** [comment]
The challenge is functioning properly. Please take this question to open chat as it isnt a bug or issue with the challenge.
