### ISSUE TITLE
Applied Visual Design: Learn about Tertiary Colors

### ISSUE THREAD

**Issue by Remus432** [freeCodeCamp/freeCodeCamp#15384]
Challenge [learn-about-tertiary-colors](http://beta.freecodecamp.com/en/challenges/applied-visual-design/learn-about-tertiary-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

So I finished all the challenges on the Applied Visual Design chapter beside this one because I can't pass it as it says that only the cyan background-color is valid the other 2 background-color are not validated and I can't pass the challenge.I suppose this is a bug as this site is sill in beta but it might be that I didn't pick the right hex code for the colors?I can't get my certificate if I don't have everything completed 😆 

```html


<style>
  body {
    background-color: #FFFFFF;
  }
  
  .orange {
    background-color: #FFA500;
  }
  
  .cyan {
    background-color: #00FFFF;
  }
  
  .raspberry {
    background-color: #E30B5D;
  }
  
  div {
    height: 100px;
    width: 100px;
    margin-bottom: 5px;
  }
</style>
  
<div class="orange"></div>
<div class="cyan"></div>
<div class="raspberry"></div>

```

**Comment by mykkip** [comment]
Replace the following: 
  
  .orange {
    background-color: **#FF7D00;** 
  }
   .raspberry {
    background-color: **#FF007D;** 
  }
in your css code

The is issue is the Hex Code for orange and raspberry and that should work
  
![mike](https://user-images.githubusercontent.com/22755761/27203479-bd90a23c-522e-11e7-9472-951f3a9d93ad.png)

**Comment by systimotic** [comment]
Thanks for reporting this issue! Looks like this has been fixed, so I'm closing this. If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Happy coding!
