### ISSUE TITLE
tried zooming in, but how to pass?

### ISSUE THREAD

**Issue by briantqtran** [freeCodeCamp/freeCodeCamp#15389]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  red-text {
    color: red;
  }
  h1 {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by briantqtran** [comment]
oops it should be p not h1!!!!!

**Comment by briantqtran** [comment]
ignore the noob error please

**Comment by elissongois** [comment]
I've Solved this bug.
I only could pass by using this code:
`<style>
.red-text {
color: red;
}
p {
font-size: 16px;
}
</style>

CatPhotoApp

Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.

Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.

`
The other code that I was using had an issue, here is my old code, I still don't know why it wasn't working:
`<style>
.red-text {
color: red;
font-size: 16px;
}
</style>

CatPhotoApp

Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.

Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.

`
Can someone tell me why this last code is wrong?
