### ISSUE TITLE
Editor and Seed spacing is inconsistent

### ISSUE THREAD

**Issue by Cyberdr8gon** [freeCodeCamp/freeCodeCamp#15385]
Challenge [make-a-person](http://beta.freecodecamp.com/en/challenges/intermediate-algorithm-scripting/make-a-person) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The normal number of spaces for a challenge is 2 spaces to a tab, however, the default spacing for this challenge is 4. For the sake of appearing consistent across examples this should either be explained as a best practice or corrected.

```js


var Person = function(firstAndLast) {
    // Complete the method below and implement the others similarly
    let firstName = firstAndLast.split(" ")[0];
    let lastName = firstAndLast.split(" ")[1];
  
  
    this.getFullName = function() {
      return firstName + lastName;
    };
  
    this.getFirstName = function() {
      return firstName;
    };
  
    this.getLastName = function() {
      return lastName;
    };
    
    this.setLastName = function(el) {
      lastName = el;
    };
    
    this.setFirstName = function(el) {
      firstName = el;
    };
  
    el
    
    return firstAndLast;
};

var bob = new Person('Bob Ross');
bob.getFullName();

```

**Comment by HJain13** [comment]
```
var Person = function(firstAndLast) {
    // Complete the method below and implement the others similarly
    this.getFullName = function() {
      return "";
    };
    return firstAndLast;
};

var bob = new Person('Bob Ross');
bob.getFullName();

```

> The normal number of spaces for a challenge is 2 spaces to a tab, however, the default spacing for this challenge is 4.

A slight correction for better understanding: The editor still treats a tab as 2 space but the default code which comes has tab indentation treated like 4 spaces.
