### ISSUE TITLE
Last Test Unsuccessful

### ISSUE THREAD

**Issue by Mortichar** [freeCodeCamp/freeCodeCamp#15394]
Challenge [Arguments Optional](https://www.freecodecamp.com/challenges/arguments-optional) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//This seems bugged, even checking for an array and returning an undefined does not work.


function addTogether() {
  var args = new Array(arguments.length);
  for(var i = 0; i < args.length; i++){
    args[i] = arguments[i];
  }

  if(args.length == 2){
    if(typeof args[0] !== 'number' || typeof args[1] !== 'number'){
      return undefined;
    }else if (Array.isArray(args[0]) || Array.isArray[args[1]]){
      return undefined;
    }
    return args[0] + args[1];
  }else{
    if(typeof args[0] !== 'number'){
      return undefined;
    }
    return function(arr){
      return arr + args[0];
    };
  }
}


addTogether(2,[3]);

```
----------------------------

No matter what I do, I cannot get the last test to complete. I even tried copy-pasting code from one of the guides, which was basically identical to mine anyway, to no avail.

**Comment by jonathanihm** [comment]
Hi Mortichar,

Your code looks like it contains a bug.  Please feel free to reach out to someone on the message board or chatrooms for a little guidance!  Good luck!  (I was able to get it working, a few changes are needed).

Cheers!

**Comment by tommygebru** [comment]
@Mortichar have you tried sharing your work with the helpJavascript chatroom, for tips and guidance in solving this challenge - https://gitter.im/FreeCodeCamp/HelpJavaScript

**Comment by Mortichar** [comment]
Sorry, I have long-since solved this. I realized that I wasn't checking the args inside of the returned function. I come from a low-level OOP (C++) background and JS confuses the hell out of me sometimes with its function passing.
