### ISSUE TITLE
Challenge create-a-more-complex-shape-using-css-and-html has an issue.

### ISSUE THREAD

**Issue by RoaldN** [freeCodeCamp/freeCodeCamp#15390]
Challenge [create-a-more-complex-shape-using-css-and-html](http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-a-more-complex-shape-using-css-and-html) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Underlying code is wrong and does not create a heart. Yet keying this code will render a pass:

```html

<style>
.heart {
  position: absolute;
  margin: auto;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background-color: pink;
  height: 50px;
  width: 50px;
  transform: rotate(-45deg);
}
.heart:after {
  background-color: pink;
  content: "";
  border-radius: 50%;
  position: absolute;
  width: 50px;
  height: 50px;
  top: 0px;
  left: 25px;
}
.heart:before {
  content: "";
  background-color: pink;
  border-radius: 50%;
  position: absolute;
  height: 50px;
  width: 70px;
  top: -50px;
  left: 5px;
}
</style>
<div class = "heart"></div>

.heart { background-color: red;
  display: inline-block;
  height: 30px;
  margin: 0 10px;
  position: relative;
  top: 0;
  transform: rotate(-45deg);
  width: 30px;

```

Underlying code creates heart. taken from {https://css-tricks.com/hearts-in-html-and-css/}:

```html

<style>
body {
  background: #333;
  color: #fff;
  font-family: 'Archivo Black', sans-serif;
  font-size: 3em;
  margin-top: 1em;
  text-align: center;
  text-transform: uppercase;
}

.heart {
  background-color: red;
  display: inline-block;
  height: 30px;
  margin: 0 10px;
  position: relative;
  top: 0;
  transform: rotate(-45deg);
  width: 30px;
}

.heart:before,
.heart:after {
  content: "";
  background-color: red;
  border-radius: 50%;
  height: 30px;
  position: absolute;
  width: 30px;
}

.heart:before {
  top: -15px;
  left: 0;
}

.heart:after {
  left: 15px;
  top: 0;
}
</style>
I <span class="heart"></span> you.
```

**Comment by Enikol** [comment]
@RoaldN Hi! I think the problem with that shallenge is that `.heart: before` should have different `width`, `top` and `left` attributes:
```css
 .heart:before {
  content: "";
  background-color: pink;
  border-radius: 50%;
  position: absolute;
  width: 50px;
  height: 50px;
  top: -25px;
  left: 0px;
}
```

These are the attributes from the challenge seed (the pre-written code), with them everything works fine:
![heart](https://user-images.githubusercontent.com/19998290/27237341-68c9511a-52d1-11e7-8896-1fbb9006bf80.jpg)

 My guess is you copied `.heart: before` from the challenge description, where the attributes are different, and it broke the code.

**Comment by RoaldN** [comment]
Thank you @Enikol! I reset the code and followed the instructions and it works beautifully

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
