### ISSUE TITLE
[beta] Typo in the instructions of challenge, Data Visualization with D3: Set a Domain and a Range on a Scale

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#15399]
Typo in the instructions of the challenge, Data Visualization with D3: Set a Domain and a Range on a Scale

"Say a data set has values ranging from 50 to 480. This **in** the input information for a scale, and is also known as the domain."

**change to** 

"Say a data set has values ranging from 50 to 480. This **is** the input information for a scale, and is also known as the domain."

**Comment by dhcodes** [comment]
Fine by me, first-timers only. You can follow the [Contributing Guide](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) to submit a pull request once you've made the fix locally.

**Comment by htalat** [comment]
first timer here, is this up for grabs?

**Comment by tommygebru** [comment]
Its already been done @htalat

**Comment by tesla809** [comment]
@tommygebru Can this issue be closed if it is already done then?

**Comment by tommygebru** [comment]
hey @tesla809 I would if i could but i dont think the process is 100% complete, otherwise it would be closed

**Comment by tesla809** [comment]
@tommygebru Ok, sweet. Is there a way I can help? I am looking for my first pull request and commit on an open source project. Know of any?

**Comment by tommygebru** [comment]
@tesla809 there are a bunch of OS projects and Quincy posts a link to this often, but here is one that looks good http://up-for-grabs.net/#/

But if you review some challenges on Freecodecamp on the live or beta version you may find a typo or some inconsistency and you can help point that out and fix as well 👍

**Comment by CodingPower472** [comment]
I can do it.  I will make a pull request shortly.

**Comment by tommygebru** [comment]
@CodingPower472 please read the comment history, I have made a PR for this issue :+1:

**Comment by CodingPower472** [comment]
@tommygebru Oh.

**Comment by erictleung** [comment]
Closing as fixed by https://github.com/freeCodeCamp/freeCodeCamp/pull/15408.
