### ISSUE TITLE
Truncate a string has an issue.

### ISSUE THREAD

**Issue by Ace-Monkey-Ilium** [freeCodeCamp/freeCodeCamp#15407]
Challenge [Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function truncateString(str, num) {
  // Clear out that junk in your trunk


  if (str.length > num) {
    str = str.slice (0, num-3) + '...';
  }
  return str;
}



truncateString("A-tisket a-tasket A green and yellow basket", 11);

```
## These are correct
truncateString("A-tisket a-tasket A green and yellow basket", 11) should return "A-tisket...".
truncateString("Peter Piper picked a peck of pickled peppers", 14) should return "Peter Piper...".
truncateString("A-tisket a-tasket A green and yellow basket", "A-tisket a-tasket A green and yellow basket".length) should return "A-tisket a-tasket A green and yellow basket".
truncateString("A-tisket a-tasket A green and yellow basket", "A-tisket a-tasket A green and yellow basket".length + 2) should return "A-tisket a-tasket A green and yellow basket".
## These are wrong
truncateString("A-", 1) should return "A...".
truncateString("Absolutely Longer", 2) should return "Ab...".

**Comment by erictleung** [comment]
@Ace-Monkey-Ilium thanks for the issue! Can you explain further why you believe those tests are incorrect? According to the description and what the challenge describes, those tests you've pointed out are okay.

> However, if the given maximum string length `num` is less than or equal to 3, then the addition of the three dots does not add to the string length in determining the truncated string.

**Comment by tommygebru** [comment]
@Ace-Monkey-Ilium have you tried sharing your work with the helpJavascript chatroom, for tips and guidance in solving this challenge - https://gitter.im/FreeCodeCamp/HelpJavaScript

**Comment by erictleung** [comment]
@Ace-Monkey-Ilium closing as non-issue. Please take a look at the help rooms for more assistance. Happy coding!
