### ISSUE TITLE
Arrays on Sorted Union mismatch

### ISSUE THREAD

**Issue by Rafase282** [FreeCodeCamp/FreeCodeCamp#1540]
The script has unite([1, 2, 3], [5, 2, 1, 4], [2, 1]);
while the test has unite([1, 3, 2], [5, 2, 1, 4], [2, 1])

This creates confusion for those using the tests to get an idea of what should be returned as the order does not match.

**Comment by catapixel** [comment]
@Rafase282 Confirmed the issue you're pointing out exists though in this case, as I'm sure you discovered, it doesn't affect the answer/solution. I agree it should be "fixed" for clarity sake.

**Comment by Rafase282** [comment]
@catapixel Yes I figured it would not affect the answer, but while I was trying to figure it out I didn't notice the reason why my code would pass even thou the order was different. It makes the problem very confusing for those using the failed test before coding to get an extra hint.

The other issue was already solved which was checking for more than three arguments so I didn't add that one.

**Comment by BerkeleyTrue** [comment]
fixed
