### ISSUE TITLE
Applied Visual Design: Create a Gradual CSS Linear Gradient (Chrome Version 58.0.3029.110 (64-bit))

### ISSUE THREAD

**Issue by anthonytranDev** [freeCodeCamp/freeCodeCamp#15402]
Challenge [create-a-gradual-css-linear-gradient](https://beta.freecodecamp.com/en/challenges/applied-visual-design/create-a-gradual-css-linear-gradient) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>

  div{ 
    border-radius: 20px;
    width: 70%;
    height: 400px;
    margin:  50 auto;
    background: linear-gradient(35deg, #CCFFFF, #FFCCCC)
  }

</style>

<div></div>

```

**Comment by ferchuqui** [comment]
; is missing

**Comment by jonathanbcsouza** [comment]
`<style>

  div{ 
    border-radius: 20px;
    width: 70%;
    height: 400px;
    margin: 50px auto;
    background: linear-gradient(35deg, #ccffff, #ffcccc);
  }

</style>

<div></div>`

**Comment by KaaviyaB** [comment]
still the same error is persisting...It is showing that
The div element should have a linear-gradient background with the specified direction and colors.

**Comment by KaaviyaB** [comment]
Thanks. Now the error did not appear after changing the casing of the background colors.
