### ISSUE TITLE
Wouldn't acknowledge that the color is blue.

### ISSUE THREAD

**Issue by sayalip1908** [freeCodeCamp/freeCodeCamp#15400]
Challenge [Use CSS Selectors to Style Elements](https://www.freecodecamp.com/challenges/use-css-selectors-to-style-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2{color:blue;}
<h2>CatPhotoApp</h2>
</style>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by indefinite0212** [comment]
Hi @sayalip1908 , you shouldn't add `<h2>CatPhotoApp</h2>` between style tags. next time you can ask help in the [help chat room](https://gitter.im/FreeCodeCamp/Help) before posting a git hub issue.

**Comment by texas2010** [comment]
@sayalip1908 
Thanks for reporting this. But your code is incorrect.
These GitHub Issues are for reporting bugs on the freeCodeCamp website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by AndyCre8s** [comment]
Solution:

<style>
  h2 {color: blue;}
</style>

<h2 ="color: blue">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
