### ISSUE TITLE
Learner can erroneously change myArray by hand

### ISSUE THREAD

**Issue by willnwhite** [freeCodeCamp/freeCodeCamp#15406]
Challenge [Modify Array Data With Indexes](https://www.freecodecamp.com/challenges/modify-array-data-with-indexes) has an issue. This code passes the challenge when it shouldn't:

```javascript
var myArray = [3,2,3]; // erroneously changed by the learner from [1,2,3]
myArray[0] = 3;
```

**Comment by tommygebru** [comment]
Ah I see, are you saying that if the number before the modification is already 3, the challenge should not pass

**Comment by willnwhite** [comment]
> Ah I see, are you saying that if the number before the modification is already 3, the challenge should not pass

Yes. 

Just as the learner did, you changed code above "Only change code below this line".

**Comment by tommygebru** [comment]
Right but since the challenge does not pass, it gives the coder the opportunity to Read-Search and Ask, why?

**Comment by willnwhite** [comment]
A possible solution could be to move `// Only change code below this line.` up one line.

**Comment by tommygebru** [comment]
@willnwhite great observation I agree -  the comment can be moved up to indicate, write new lines only

**Comment by erictleung** [comment]
@willnwhite @tommygebru sounds good to me. There should be another test that checks for `var myArray = [45, 64, 99]` (the numbers are changed in the beta/staging). The test message could be "The initial `myArray` line shouldn't be changed."

**Comment by willnwhite** [comment]
@erictleung I thought this too, but then I thought the learner could write:

```
var myArray = [45, 64, 99];
// Only change code below this line.
var myArray = [3, 64, 99];
...
```
So where do the checks end?

I noticed that @tommygebru wrote code above the line, as did the learner who prompted this issue, indicating they hadn't read this instruction. So I think that moving the line up may be all that is necessary.

**Comment by tommygebru** [comment]
@erictleung @willnwhite The instructions are rather bare, usually we have a lot of good reading material in this panel, this will be a good opportunity to update... will try a new issue soon!

**Comment by MiloATH** [comment]
@willnwhite 
```js
var myArray = [45, 64, 99];
// Only change code below this line.
var myArray = [3, 64, 99];
```
This could wouldn't pass all the tests currently in place. This would fail test: "You should be using correct index to modify the value in myArray."

The camper still needs to use the assign operator `myArray[0]=` to pass that test. I will add a test to check the initial `myArray` line hasn't been changed.
