### ISSUE TITLE
pplied Visual Design: Create a Gradual CSS Linear Gradient Issue Moz 5.0 Windows 10

### ISSUE THREAD

**Issue by Sluthsaber95** [freeCodeCamp/freeCodeCamp#15401]
Challenge [create-a-gradual-css-linear-gradient](https://beta.freecodecamp.com/en/challenges/applied-visual-design/create-a-gradual-css-linear-gradient) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>

  div{ 
    border-radius: 20px;
    width: 70%;
    height: 400px;
    margin:  50 auto;
    background: linear-gradient(35deg, #CCFFFF, #FFCCCC)
  }

</style>

<div></div>

```
![screenshot 257](https://user-images.githubusercontent.com/24325483/27239617-9da9b6d4-52c9-11e7-967f-b0a2d4f3ea78.png)

**Comment by surajkumarsharma** [comment]
missing ; at the end
