### ISSUE TITLE
Applied Visual Design: Create Texture by Adding a Subtle Pattern as a Background Image Issue

### ISSUE THREAD

**Issue by anthonytranDev** [freeCodeCamp/freeCodeCamp#15403]
![screenshot 258](https://user-images.githubusercontent.com/26009168/27240535-02ceff76-52cd-11e7-843d-80300a196aac.png)
Challenge [create-texture-by-adding-a-subtle-pattern-as-a-background-image](https://beta.freecodecamp.com/en/challenges/applied-visual-design/create-texture-by-adding-a-subtle-pattern-as-a-background-image) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  body {
    background: url(https://i.imgur.com/MJAkxbh.png);
  }
</style>

```

**Comment by kanascyc** [comment]
you can add the quotation mark in the link like this ("https://i.imgur.com/MJAkxbh.png")

**Comment by LeviT23** [comment]
@kanascyc could you please explain why it passes only after you add the quotation mark ?

**Comment by kanascyc** [comment]
@LeviT23 the code should be 
body { background: url("");}
I searched it in this below website.
https://www.w3schools.com/cssref/css3_pr_background.asp
