### ISSUE TITLE
Change in instruction for Challenge: Using Objects for Lookups

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#15412]
The instructions includes the word "table" or phrase "lookup table" to describe an "object", I find that confusing as I have never heard it described in this manner, before or after this challenge in Javascript.

Suggest changing the instructions from
Convert the switch statement into **a lookup table** called lookup. Use it to lookup val and assign the associated string to the result variable.

to the following 
Convert the switch statement into **an object** called lookup. Use it to lookup val and assign the associated string to the result variable.

**Comment by tommygebru** [comment]
![screen shot 2017-06-17 at 10 11 31 am](https://user-images.githubusercontent.com/7606025/27254809-5b7c1550-5345-11e7-9e81-c449c456a4e7.png)

**Comment by tommygebru** [comment]
@anthonygallina1 can I get a second opinion? 👍

**Comment by erictleung** [comment]
@tommygebru someone's a step ahead of you, already fixed with https://github.com/freeCodeCamp/freeCodeCamp/pull/13822. Happy coding!

**Comment by tommygebru** [comment]
@erictleung Awww no 😞 that was one of the first bugs I seen and complained about a year or so ago
