### ISSUE TITLE
Wrong text in https://www.freecodecamp.com/challenges/use-spans-for-inline-elements

### ISSUE THREAD

**Issue by hermiyantoeko** [freeCodeCamp/freeCodeCamp#15414]
#### Challenge Name

https://www.freecodecamp.com/challenges/use-spans-for-inline-elements

#### Issue Description

The text:
"Nest the word "love" in your "Things cats love" element below within a span element. Then give that span the class text-danger to make the text red."

My comment:
"love" in this case should be hate since it corresponds with "btn-danger" and the next paragraph clearly states "hate" rather than "love".

#### Browser Information

* Browser Name, Version: Firefox 54.0
* Operating System: Ubuntu Linux 14.04
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```
#### Screenshot

![use spans for inline elements free code camp - mozilla firefox_134](https://user-images.githubusercontent.com/17229992/27255463-ecade034-53c8-11e7-9b99-f86eb3c66f3b.png)

**Comment by hermiyantoeko** [comment]
I love this. It is the first time I submit bug report, ever.

**Comment by varunu28** [comment]
Not sure if it can be considered a bug. If it gets approved as a bug I would be happy to take on the change and submit a PR
