### ISSUE TITLE
concatenating strings problem,it appears quotation in the output

### ISSUE THREAD

**Issue by hasaw-lalramenkawla** [freeCodeCamp/freeCodeCamp#15411]
Challenge [Concatenating Strings with Plus Operator](https://www.freecodecamp.com/challenges/concatenating-strings-with-plus-operator) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var ourStr = "I come first. " + "I come second.";

// Only change code below this line

var myStr = "This is the start. " + "This is the end.";



```

**Comment by mstellaluna** [comment]
Hi, 
Your code is correct. Please try to refresh your browser or copy your code, reset the challenge and paste it in again. 

Thanks
mstellaluna

**Comment by hasaw-lalramenkawla** [comment]
sorry....i didn't read ......i just reset ,my code and it's fine now.

**Comment by hasaw-lalramenkawla** [comment]
thanks anyway...
