### ISSUE TITLE
Truncate a string

### ISSUE THREAD

**Issue by migscay** [freeCodeCamp/freeCodeCamp#15416]
Challenge [Truncate a string](https://www.freecodecamp.com/challenges/truncate-a-string) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function truncateString(str, num) {
  // Clear out that junk in your trunk
  if (isNaN(num)) {
    return str;
  }
  var newStr="";
  var endPos=0;
  if (num > 3) {
	num -= 3;
  }
  //else
  //{
//	num -= 1;
 // }
  //return num;
  newStr = str.slice(0,num);
  //return newStr;
  newStr = newStr.concat("...");
  return newStr;
}

truncateString("A-tisket a-tasket A green and yellow basket".length);

```
My Code is failing this test, which is incorrect. How can the function return a String when it is being passed a number?

truncateString("A-tisket a-tasket A green and yellow basket", "A-tisket a-tasket A green and yellow basket".length) should return "A-tisket a-tasket A green and yellow basket".

**Comment by tommygebru** [comment]
@migscay have you tried sharing your work with the HelpJavascript chatroom, for tips and guidance in solving this challenge - https://gitter.im/FreeCodeCamp/HelpJavaScript

However it sounds to me like you need to review the instructions:
>Truncate a string (first argument) **if it is longer** than the given maximum string length (second argument). Return the truncated string with a ... ending.

**Comment by migscay** [comment]
ThanK you! I misread the instruction.
