### ISSUE TITLE
[curriculum][enhancement] New link for the modal, Did You Find A Bug?

### ISSUE THREAD

**Issue by tommygebru** [freeCodeCamp/freeCodeCamp#15413]
When new students click on the bug button in the instructions panel
![screen shot 2017-06-17 at 10 01 36 am](https://user-images.githubusercontent.com/7606025/27254739-0eefea64-5344-11e7-8d12-32d4b3bc32df.png)

They are given a few options with how to proceed, when finding a challenge does not pass a test case
![screen shot 2017-06-17 at 10 01 41 am](https://user-images.githubusercontent.com/7606025/27254758-433d2a66-5344-11e7-885e-99c4ec8bb7fc.png)

I suggest a new link to add to the modal, "Help Im stuck!" or "Read-Search-Ask" or find a "Freecodecamp Chatrooms"

This will help students engage with the fcc community if they had not beforehand, and encourage sharing, and describing their problem in detail.

**Comment by tommygebru** [comment]
**Update:** I think [Freecodecamp Chatrooms](https://gitter.im/FreeCodeCamp/home) works best because it is more applicable to different challenges, projects, and situations.

**Comment by texas2010** [comment]
I am not sure about that. but we already have a help button.

**Comment by tommygebru** [comment]
Its entirely possible that people overlook the help button because they think the problem they are experiencing is their own. 

Many of the students who post to github can benefit from the link "Freecodecamp Chatrooms" as a helpful deterrent to "Create my Github Issue"

All possible bugs can benefit from a discussion in the Gitter chats IMO
