### ISSUE TITLE
Testing Objects for Properties - Javascript - FCC 

### ISSUE THREAD

**Issue by shauryakapoor** [freeCodeCamp/freeCodeCamp#15421]
I just solved this myself. I am not sure, how to delete it. Sorry for the inconvinence. 

Challenge [Testing Objects for Properties](https://www.freecodecamp.com/challenges/testing-objects-for-properties) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here
  result = myObj.hasOwnProperty(checkProp);
if (result === true)
  return myObj[checkProp];
else 
  return "Not found";
}

// Test your code by modifying these values
checkObj("house");

```

**Comment by tommygebru** [comment]
@shauryakapoor No worries, someone will come along and remove the message shortly.

When you encounter bugs, try to bring it up in the [Freecodecamp Chatrooms](https://gitter.im/FreeCodeCamp/home) first and discuss it with other coders, most often than not, its a difficult challenge or project to problem solve.

Happy coding! 🎉

**Comment by DeNance143** [comment]
Ok
