### ISSUE TITLE
can anyone help me out with this

### ISSUE THREAD

**Issue by a7n007** [freeCodeCamp/freeCodeCamp#15424]

**Comment by a7n007** [comment]
thanks

**Comment by DeNance143** [comment]
Hi
Its 1:44am CST.
Night....from TEXAS.....
Nancy
Here ....use this okay...


// JavaScript source code

var count = 0;

function cc(card) {
    // Only change code below this line
    if (card == 2 || card == 3 || card == 4 || card == 5 || card == 6)
        count++;
    else if (card == 7 || card == 8 || card == 9)
        count += 0;
    else if (card == 10 || card == 'J' || card == 'Q' || card == 'K' ||
card == 'A')
        count -= 1;

    if (count <= 0);
    else if (count > 0); { return count + " Hold"; }


    // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

**Comment by DeNance143** [comment]
Hi
Its 1:44am CST.
Night....from TEXAS.....
Nancy
Here ....use this okay...



// JavaScript source code

var count = 0;

function cc(card) {
    // Only change code below this line
    if (card == 2 || card == 3 || card == 4 || card == 5 || card == 6)
        count++;
    else if (card == 7 || card == 8 || card == 9)
        count += 0;
    else if (card == 10 || card == 'J' || card == 'Q' || card == 'K' ||
card == 'A')
        count -= 1;

    if (count <= 0);
    else if (count > 0); { return count + " Hold"; }


    // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

**Comment by DeNance143** [comment]
Hi
I do not do fixes free. lol...
TC

**Comment by DeNance143** [comment]
Bug Fixes!
