### ISSUE TITLE
Typo: "CS" instead of "CD"

### ISSUE THREAD

**Issue by ncm1** [freeCodeCamp/freeCodeCamp#15425]
#### Challenge Name

https://www.freecodecamp.com/challenges/manipulating-complex-objects

#### Issue Description

In format, CS should be CD

#### Browser Information

* Browser Name, Version: Safari, Brave, Chrome
* Operating System:  Mac OSX
* Mobile, Desktop, or Tablet: 

#### Your Code

```js

```
#### Screenshot

<img width="1440" alt="screen shot 2017-06-18 at 2 27 28 am" src="https://user-images.githubusercontent.com/19338787/27258647-b3b4a0d8-53cd-11e7-9198-b8f7cc3c5185.png">

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/freeCodeCamp/pull/15417
