### ISSUE TITLE
The advice area disappears with commenting

### ISSUE THREAD

**Issue by garysmeade** [FreeCodeCamp/FreeCodeCamp#1542]
Challenge http://beta.freecodecamp.com/challenges/waypoint-create-a-form-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When starting to comment any area within the code window, the advice area on the page disappears.  I have included the visible advice area here:
![image](https://cloud.githubusercontent.com/assets/13364192/9078476/79b136cc-3b82-11e5-807a-73f92448ce1e.png)

And now when beginning to write an opening comment, how the full page appears: 
![image](https://cloud.githubusercontent.com/assets/13364192/9078516/eecd9644-3b82-11e5-9499-1d0c732bfec3.png)

This issue occurs on any of the HTML/CSS waypoints.

**Comment by benschenker** [comment]
Hey @garysmeade thanks for posting this issue!

This is really similar to #1081, so follow the discussion there.
