### ISSUE TITLE
i find no mistake  in my code

### ISSUE THREAD

**Issue by a7n007** [freeCodeCamp/freeCodeCamp#15430]
Challenge [Make Unique Objects by Passing Parameters to our Constructor](https://www.freecodecamp.com/challenges/make-unique-objects-by-passing-parameters-to-our-constructor) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; rv:54.0) Gecko/20100101 Firefox/54.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var Car = function() {
  //Change this constructor
  this.wheels = 4;
  this.seats = 5;
  this.engines = 1;
};

//Try it out here
var myCar=new Car(3,1,2);

```

**Comment by Jadeng24** [comment]
you need to enter wheels, seats, engines into your var Car = funtion() . so it will look like this
var Car = funtion(wheels, seats, engines) {
}
