### ISSUE TITLE
In the instructions there is a refernce to -> { color: #000000; } and the real answer is {  background-color: #000000; }

### ISSUE THREAD

**Issue by zeevig** [freeCodeCamp/freeCodeCamp#15434]
Challenge [Use Hex Code for Specific Colors](https://www.freecodecamp.com/challenges/use-hex-code-for-specific-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: #000000;
  }
</style>

```

**Comment by zeevig** [comment]
real user @ZevGev

**Comment by erictleung** [comment]
@zeevig @zeevig thanks for the issue! Yes, this is a bit odd. I thought this was moved into the instructions, but I guess not.

For whoever wants to take up this challenge, let's move that example up to the instructions. The "instructions" in the challenge test were just a reminder of how to set the colors. So moving them back up to the instructions should be intended as a reminder.

**Comment by texas2010** [comment]
ahh! I plan to respond but too slow. lmao

**Comment by texas2010** [comment]
@erictleung, I checking that challenge in beta. :O we have to do both. backup/master and staging.

**Comment by erictleung** [comment]
@texas2010 I don't think we need to do it for `backup/master` as changes for that should be critical changes. This "error" can stay, as it is only supposed to be a suggestion/reminder.

**Comment by Enikol** [comment]
@erictleung Hi! I'd like to take this one up and include it in the instruction like this, for example: "In CSS, we can use 6 hexadecimal digits to represent colors, two each for the red (R), green (G), and blue (B) components. For example, `body { color: #000000; }` will set the color of an element's text content to black (which is the lowest possible hex value). You can find more information about the RGB color system here." 
If it's okay, I'll create a PR!

**Comment by erictleung** [comment]
@Enikol thanks for your interest! I was thinking of having a separate code block just for the example

> ...For example, `#000000` is black and is also the lowest possible value. You can find more information about the RGB color system here.
> ```css
> body {
>   color: #000000;
> }
> ```
>
> Replace the word `black` in our body element's background-color with its hex code representation, `#000000`.

The code you need should be

```
"<blockquote>body {<br>  color: #000000;<br>}</blockquote>",
```

Let me know what you think. And please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.

**Comment by texas2010** [comment]
I would take this. but someone can have it. XD 

good luck. @Enikol

**Comment by Enikol** [comment]
@erictleung Awesome. thanks a lot! I created a PR, if you could take a look at it, it would be great!
@texas2010 Thanks :)

**Comment by haruna24** [comment]
Hi!am new here ,just want to clarify some thing plz don't laught if am wrong.what is backup/master? Thank you!

**Comment by texas2010** [comment]
@haruna24 backup/master is a git branch name in the freeCodeCamp repository.
