### ISSUE TITLE
It asks for the 'target1' element to be red and it is but doesn't pass

### ISSUE THREAD

**Issue by jonwalz** [FreeCodeCamp/FreeCodeCamp#1543]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![screen shot 2015-08-04 at 10 06 22 pm](https://cloud.githubusercontent.com/assets/249293/9078584/291c94e6-3af5-11e5-95c3-2611a349bf56.png)

**Comment by jhealy86** [comment]
The challenge is actually testing `background-color` to be red like it says in the instructions, not the text. The test wording should be changed to reflect this.

![image](https://cloud.githubusercontent.com/assets/11396325/9078659/6c303298-3afe-11e5-9a24-ace465e61fe7.png)

**Comment by danrhumphries** [comment]
<img width="1428" alt="screen shot 2015-08-19 at 6 51 31 am" src="https://cloud.githubusercontent.com/assets/13267128/9358138/67bc3d64-463f-11e5-9128-7019b3c6c31f.png">
The instructions say "Give the parent of the #target1 element background-color of red." but the check mark asks for "Your left-well element should have a red background."

**Comment by danrhumphries** [comment]
<img width="1432" alt="screen shot 2015-08-19 at 6 54 06 am" src="https://cloud.githubusercontent.com/assets/13267128/9358147/70f4d6b6-463f-11e5-99a0-ac6733711789.png">
Even after updating the code to change the left-well to inherit a red background from the parent the check still isn't taking.

**Comment by benschenker** [comment]
Thanks @jonwalz  and @jhealy86, this has been fixed!
