### ISSUE TITLE
Error in Theory of JS

### ISSUE THREAD

**Issue by techiespace** [freeCodeCamp/freeCodeCamp#15431]
Challenge [Generate Random Whole Numbers with JavaScript](https://www.freecodecamp.com/challenges/generate-random-whole-numbers-with-javascript) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
The theory on this page says 

> Use another function, Math.floor() to round the number down to its nearest whole number.
Instead, it should be something like,

> Use another function, Math.floor() to truncate the decimal part of the number.
or

>  Use another function, Math.floor() to get the largest integer less than or equal to the number.

**Comment by jonathanihm** [comment]
I do not believe this should be changed, please see provided documentation:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/floor
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc

The floor and trunc functions are different and changing the wording of this would increase confusion, as they are only equivalent with positive numbers and further explanation would only add fluff to the lesson in my opinion.

Thanks!

**Comment by CosmicDog2000** [comment]
"Use another function, Math.floor() to truncate the decimal part of the number" is only true for positive numbers...

**Comment by erictleung** [comment]
@techiespace thanks for the issue. Although, it is more precise to say ["get the largest integer less than or equal to the number"](http://mathworld.wolfram.com/FloorFunction.html), I think how it is currently described is the easiest to understand without the jargon used in "integer" or "less than or equal to". And I agree with others than truncate is definitely not appropriate.

I'll leave this open for others to comment on.

**Comment by prateekgoel** [comment]
@erictleung I think we should keep it as it as and we can have a article linked to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/floor which will help camper to dig deep and understand the technical terms involved.

If this workaround is fine, I'd like to take this task.
