### ISSUE TITLE
Counting Cards

### ISSUE THREAD

**Issue by louiss0** [freeCodeCamp/freeCodeCamp#15437]
Challenge [Counting Cards](https://www.freecodecamp.com/challenges/counting-cards) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var count = 0;

function cc(card) {
  // Only change code below this line
  switch(card) {
  case 2:
  case 3:
  case 4:
  case 5:
  case 6:
  count+=1;
  break;
      
 
  case 10:
  case 'J':
  case 'Q':
  case 'K':
  case 'A':
  count-=1;
  break;
      
      
  }
  
  return count + (count  > 0  ?  " Bet " : " Hold ");
  // Only change code above this line
}

// Add/remove calls to test your function.
// Note: Only the last will display
cc(2); cc(3); cc(7); cc('K'); cc('A');

```  i got 0 hold but it didnt go through

**Comment by nmdoliveira** [comment]
You have extra spaces after `"Bet"` and `"Hold"`.
