### ISSUE TITLE
Strange warning in my code

### ISSUE THREAD

**Issue by spqa** [freeCodeCamp/freeCodeCamp#15443]
Challenge [Binary Agents](https://www.freecodecamp.com/challenges/binary-agents) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function binaryAgent(str) {
  var charCode=str.split(" ");
  
  return charCode.map(toChar).join().replace(/,/g,"");
}

function toChar(item){
  'useversion:6';
  var digits=item.split("").reverse();
  var code=digits.reduce((x,currentVal,currentIndex)=>{
    x=x+currentVal* 2 ** currentIndex;
    return x;
  },0);
  return String.fromCharCode(code);
}

binaryAgent("01000001 01110010 01100101 01101110 00100111 01110100 00100000 01100010 01101111 01101110 01100110 01101001 01110010 01100101 01110011 00100000 01100110 01110101 01101110 00100001 00111111");

```

[http://i.imgur.com/FaJNCZj.png](url)

**Comment by dhcodes** [comment]
@spqa it's because `**` is an experimental feature of JS so the code editor likely doesn't recognize it. [Source](https://stackoverflow.com/questions/33284569/is-the-double-asterisk-a-valid-javascript-operator)
