### ISSUE TITLE
Waypoint: Label Bootstrap Wells - test not passing (beta)

### ISSUE THREAD

**Issue by robertozimek** [FreeCodeCamp/FreeCodeCamp#1544]
Challenge http://beta.freecodecamp.com/challenges/waypoint-label-bootstrap-wells has an issue. 
![screen shot 2015-08-05 at 8 59 05 am](https://cloud.githubusercontent.com/assets/11142652/9080035/51e923ac-3b50-11e5-854c-319acde10f64.png)
The "Add an h4 element to each of your \<div class='col-xs-6'\> elements." test does not pass even though there is clearly an h4 element inside of each \<div class='col-xs-6'\> element.

**Comment by benschenker** [comment]
Closing as stale
