### ISSUE TITLE
fa icon to be added or to replace the word "Like" in button

### ISSUE THREAD

**Issue by benomatis** [freeCodeCamp/freeCodeCamp#15446]
Challenge [Add Font Awesome Icons to our Buttons](https://www.freecodecamp.com/challenges/add-font-awesome-icons-to-our-buttons) has an issue.

The relevant bit of my code:
```html
<button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i></button>
```

The instruction says...
>...add a `thumbs-up` icon to your like button by giving it an `i` element with the classes `fa` and `fa-thumbs-up`.

I did just that above, yet I received the error...
>Your fa-thumbs-up icon should be located within the Like button.

The icon _is_ within the button, the instruction doesn't say that it has to be added next to the word `Like`, and not replace it, as I did, yet that's the only way it evaluates to a correct answer.

**Comment by erictleung** [comment]
@benomatis thanks for the issue. The instructions do say to *add* the icon to the button.

> Use Font Awesome to add a `thumbs-up` icon to your like button by giving it an `i` element with the classes `fa` and `fa-thumbs-up`.

which implies it should be next to the `Like` text.

These instructions could be more explicit in stating the text "Like" should still be there. I'll open this for anyone who wants to first suggest a fix.

**Comment by benomatis** [comment]
@erictleung ok, agreed, it does say _add_, though I guess, like you said, it could be slightly more explicit. Think I'll give it a go and try to suggest an edit... ;)
