### ISSUE TITLE
src attribute don't work

### ISSUE THREAD

**Issue by Maisko** [freeCodeCamp/freeCodeCamp#15444]
Challenge [Add Images to your Website](https://www.freecodecamp.com/challenges/add-images-to-your-website) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
<img src="https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg" alt="Author standing on a beach with two thumbs up. ">

```

**Comment by Maisko** [comment]
src attribute don't be okay

**Comment by n-tran** [comment]
i used your exact code and it didn't work, so I replaced your cat picture link with the link that was provided on the challenge and it works.

use (was provided on the challenge):
https://bit.ly/fcc-relaxing-cat

instead of:
https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg

hope that helps

**Comment by erictleung** [comment]
@Maisko take a look at @n-tran's comments. Don't use the expanded URL. Use the URL provided in the challenge. Happy coding!
