### ISSUE TITLE
Show the Local Weather challenge is not working for me

### ISSUE THREAD

**Issue by ugrinovs** [freeCodeCamp/freeCodeCamp#15447]
Challenge [Show the Local Weather](https://www.freecodecamp.com/challenges/show-the-local-weather) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.110 Chrome/58.0.3029.110 Safari/537.36</code>.

First issue is with `codepen` being served via **https**. The request to ipinfo api is failing. 
**Fix:** One solution is to replace http with https, but I think the better solution is to remove protocol completely (remove http: and leave the rest //api... ). That way it will work on both protocols.

Second issue has to do with openweather changing their api so now subdomain `api` is not used anymore
it's just //openweathermap.org/... (protocol should be removed here as well) and also query key for app id
is no longer APPID but `appid` so the link should look like this 
```
//openweathermap.org/data/2.5/weather?q=Belgrade,RS&units=metric&appid=b1b15e88fa797225412429c1c50c122a1&callback=angular.callbacks._1
```

Best regards,
Stefan Ugrinov

**Comment by MiloATH** [comment]
Hi @ugrinovs 

Thanks for reporting this issue. We recently built a FreeCodeCamp weather API. Pleases consider using that API. Here is the link: https://fcc-weather-api.glitch.me. The FreeCodeCamp codepen has been updated.

Here are some next steps that you should follow before we can help you with your query:

* Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
* Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](https://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

Happy Coding!

@raisedadead I think this issue can be closed.
