### ISSUE TITLE
Quotation mark

### ISSUE THREAD

**Issue by Quades** [freeCodeCamp/freeCodeCamp#15459]
Challenge [Override Class Declarations with Inline Styles](https://www.freecodecamp.com/challenges/override-class-declarations-with-inline-styles) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 OPR/45.0.2552.898</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text {
    color: orange;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 id="orange-text" class="pink-text blue-text" style="color: white>Hello World!</h1>

```
By writing "<h1 id="orange-text" class="pink-text blue-text" style="color: white>Hello World!</h1>", after the word "white" i don't add a quotation mark and the phone shows a string of code: =0||Object.prototype.hasOwnProperty.call(e,s)&&(r[s]=e[s]);return r}var _extends=Object.assign||function(e){for(var t=1;t
![screenshot_1](https://user-images.githubusercontent.com/29256113/27356488-526d945a-5617-11e7-8207-1128934b8b85.png)

**Comment by CosmicDog2000** [comment]
It looks like the "phone" is, itself, a JavaScript app and by failing to enclose your inline CSS, you've caused the code to break and print and object to the screen. Just throw in the closing quote and call it good.

**Comment by erictleung** [comment]
@Quades thanks for the issue. As you note, without the quotation mark, your code fails to be valid HTML. I don't think this is an edge case we have time to prioritize right now. As it was also mentioned, I would just take the odd output as feedback that something is wrong with your code and you can do something about it. Happy coding!
