### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by suzieapedo** [freeCodeCamp/freeCodeCamp#15452]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Linux; Android 5.1; CW-Hi12 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  p {
  font-size: 16px;   
  }  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat</p>
```

**Comment by n-tran** [comment]
you're missing a closing curly bracket at the end of ".red-text"

**Comment by texas2010** [comment]
Yep, @n-tran is right.

**Comment by texas2010** [comment]
@suzieapedo 
Thanks for reporting this. But the code is missing. that is why it won't pass.
These GitHub Issues are for reporting bugs on the freeCodeCamp website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by elissongois** [comment]
I've Solved this bug.
I only could pass by using this code:
`<style>
  .red-text {
    color: red;
  }
    p {
  font-size: 16px;   
  }  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>`

The other code that I was using had an issue, here is my old code, I still don't know why it wasn't working:
`<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
  </style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>`

Can someone tell me why this last code is wrong?
