### ISSUE TITLE
Challenge Appending Variables to Strings has an issue.

### ISSUE THREAD

**Issue by nmenag** [freeCodeCamp/freeCodeCamp#15455]
Challenge [Appending Variables to Strings](https://www.freecodecamp.com/challenges/appending-variables-to-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

// Example
var someAdjective = "awesome!";
var ourStr = "Free Code Camp is ";
ourStr += anAdjective;

// Only change code below this line

var someAdjective = "awesome!";
var myStr = "Learning to code is ";

myStr += someAdjetive;

```

![image](https://user-images.githubusercontent.com/4958877/27349421-c3edd9d8-55bc-11e7-9189-393b0b69c88d.png)

**Comment by n-tran** [comment]
you misspelled someAdjective

**Comment by texas2010** [comment]
@nmenag 
Thanks for reporting this. But you got the typo in your code.
These GitHub Issues are for reporting bugs on the freeCodeCamp website only.
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.

**Comment by nmenag** [comment]
solutioned!, @texas2010 @n-tran thanks you very much
