### ISSUE TITLE
I found that in some testcases   str.toLowerCase(); isn't' working

### ISSUE THREAD

**Issue by a7n007** [freeCodeCamp/freeCodeCamp#15458]
Challenge [Check for Palindromes](https://www.freecodecamp.com/challenges/check-for-palindromes) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; rv:54.0) Gecko/20100101 Firefox/54.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function palindrome(str)
{
   
  str.toLowerCase();
  alert(str);
  str=str.replace(/\s+/g,'');
  str=str.replace('-',''); 
  str=str.replace('_','');  
  str=str.replace('.','');
  str=str.replace(')','');  
  str=str.replace('(',''); 
  str=str.replace(':','');  
  str=str.replace('/',''); 
  str=str.replace(',',''); 
  var a=str.split('');
  a.reverse();
  var b=a.join('');
       if(str==b)
  return true;
  else
  return false;
}



palindrome("0_0 (: /-\ :) 0-0");

```

**Comment by zbanana** [comment]
I believe you need to assign str to a var. You can assign it to str like so:
`str = str.toLowerCase();`
I would also recommend using regular expressions to do your replacing process

**Comment by a7n007** [comment]
can  you tell me  best place  to  learn about regex

**Comment by mdxedia** [comment]
Dear Sir,

TFYEST me.


[image: --]

Md Xedia
[image: https://]about.me/mxedia
<https://about.me/mxedia?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=chrome_ext>
