### ISSUE TITLE
FreeCodeCamp Badges

### ISSUE THREAD

**Issue by codemzy** [freeCodeCamp/freeCodeCamp#15467]
I have been talking with @QuincyLarson about the possibility of a badge system for FCC. There are a few old issues discussing this... #9108 #604 #1296 #913 but they are closed so I thought I would open up a new one and look to actually put this into action.

I think using Mozilla Open Badges is a good idea. 

So, my initial thoughts are different badges for certain tasks or achievements throughout the map, but keep it totally separate to the points system which I know there is discussion about at the moment.

Badges you wont get as often as points, so it would add a new level of reward on top of the points system.

Here is the design idea I had...

<div align="center">

![fcc_badges](https://user-images.githubusercontent.com/13764272/27394078-d5157748-56a2-11e7-9bc6-305053c53bc4.jpg)

</div>

So essentially, the harder the task you completed, or better the achievement, the more stars on the badge, going from 1 - 5. 

Obviously there can be lots more achievements along the way, so there could be badges for:

- Completing your first challenge
- Completing a particular set of challenges
- Completing a particular set of projects
- Completing all the projects

That is the basic idea anyway. I have not looked into how hard this will be to implement, but I reckon I could have a good crack at it. I just wanted to get some feedback and make sure I am heading in the right direction before I make a start.

**Comment by jonathanihm** [comment]
Hi there,

I think the long sought after badge/award system sounds like an awesome idea!  It has much more appeal than points.  I would also suggest that we should refactor out the history and solutions section from users' profiles into it's own page and have it replaced with summary of badges.  In my opinion, that page becomes large, clunky, and slow with that section.  Let me know if you need more ideas on badges too!

**Comment by QuincyLarson** [comment]
@codemzy These are pretty good ideas (I don't know about "Reactor" though - we probably wouldn't want these to be technology-specific). Also these aren't flat white on green like our other assets. I think for visual consistency we would want them to be, or at least to conform to our [design style guide](https://www.freecodecamp.com/design-style-guide/).

Note that we also have some badge ideas in https://github.com/FreeCodeCamp/assets/issues

**Comment by codemzy** [comment]
Sorry about that I had no idea about the style guide!

Ok, I've updated the design to make the badges look more freeCodeCamp-ified...

<div align="center">

![fcc_badges2](https://user-images.githubusercontent.com/13764272/27432767-8cb3cc50-5749-11e7-8739-c54fb7f242d4.jpg)

</div>

Some ideas I had for badges to start things off...

**1 Star Badges**
STUDENT (joins fcc)
ROOKIE (completes first challenge)
CAMPER (completes first 10 challenges)
BATTLER (attempt to solve a challenge more than 10 times)

**2 Star Badges**
CADET (completes first 25 challenges)
BUILDER (completed a project)
LIBRARIAN (using first library like jQuery)
NAVIGATOR (finished first section of the map)
SLUGGER (attempt to solve a challenge more than 50 times)
BELIEVER (7 day streak)

**3 Star Badges**
HELPER (maybe helped someone in chat?)
SCOUT (completes first 50 challenges)
EXPLORER (learnt a JS framework like React)
WARRIOR (completed a challenge after more than 100 attempts)
FANATIC (30 day streak)

**4 Star Badges**
CONTRIBUTOR (contributes a pull request to fcc)
CHAMPION (gets 3 certificates)
SURVIVOR (completed a challenge after more than 200 attempts)
ADDICT (100 day streak)

**5 Star Badges**
TEAM (core team member)

Other badge name ideas that could be given but not sure what for...

ARTIST (maybe something to do with css)
MAKER
PIONEER
LEADER
INSTRUCTOR (maybe something to do with adding to the curriculum)
SUPPORTER (maybe for setting up a monthly donation)

**Comment by w96k** [comment]
Really good idea.

**Comment by QuincyLarson** [comment]
@codemzy These look great! Could you create a pull request with these assets for https://github.com/FreeCodeCamp/assets ?

We can work on adding something like these later once we ship beta.

**Comment by ahstro** [comment]
>(I don't know about "Reactor" though - we probably wouldn't want these to be technology-specific).

If we want them to be [Open Badges](https://openbadges.org/) (which I strongly encourage), it would probably make sense to have technology-specific ones, or ones that lean more towards *"this is a concrete skill I have"* instead of *"this is a semi-abstract achievement I've completed"*, if that makes sense?
