### ISSUE TITLE
Unable to get credits on Beta

### ISSUE THREAD

**Issue by cristianvnica** [FreeCodeCamp/FreeCodeCamp#1546]
I couldn't find if this issue is posted already:
Many times I complete a challenge on the beta website, even if on the map is marked as completed,  the number of credits I have on my profile page doesn't update.

<img width="115" alt="screen shot 2015-08-05 at 12 23 26 pm" src="https://cloud.githubusercontent.com/assets/3229023/9082477/fb49bd28-3b6c-11e5-8758-bd4572954581.png">

**Comment by benschenker** [comment]
Closing as stale
