### ISSUE TITLE
the code won't work

### ISSUE THREAD

**Issue by saahil777** [freeCodeCamp/freeCodeCamp#15466]
Challenge [Make Dead Links using the Hash Symbol](https://www.freecodecamp.com/challenges/make-dead-links-using-the-hash-symbol) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 OPR/45.0.2552.898</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by erictleung** [comment]
@saahil777 thanks for the issue. I wasn't able to reproduce your error and your code works.

![image](https://user-images.githubusercontent.com/2754821/27392200-eb36f422-565a-11e7-9352-318dfc3c1730.png)

What browser are you using? And are you using a desktop/laptop or tablet?

**Comment by n-tran** [comment]
@saahil777 you got a syntax error. this isn't a bug - please use the help button

hint: # is not a string

**Comment by n-tran** [comment]
sorry, i re-tested and used @saahil777  code and it worked for me as well.

**Comment by saahil777** [comment]
Yes it worked. There was some problem with the page. I restarted the
browser and it worked

**Comment by saahil777** [comment]
thanks you for your help. i restarted the browser and it sent directly to the next challenge
