### ISSUE TITLE
I've tried to overcome this challenge in two browsers. It shows the same issue. It looks to be a problem in the zoom. Someone has solved this?

### ISSUE THREAD

**Issue by Gillly** [freeCodeCamp/freeCodeCamp#15462]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;font-size: 16px;
  }}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```
![image](https://user-images.githubusercontent.com/29571100/27359994-2ad63686-5662-11e7-9941-bf0f0adaaed4.png)

**Comment by n-tran** [comment]
this isnt a bug, please use the "help" button

hint: your style class is incorrect.

**Comment by Gillly** [comment]
Ok Thanks!!

**Comment by texas2010** [comment]
@Gillly 
Thanks for reporting this. But your code is incorrect.
These GitHub Issues are for reporting bugs on the freeCodeCamp website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
