### ISSUE TITLE
Does not register #HEX for Orange & Raspberry on Chrome

### ISSUE THREAD

**Issue by bcecil88** [freeCodeCamp/freeCodeCamp#15463]
Challenge [learn-about-tertiary-colors](http://beta.freecodecamp.com/en/challenges/applied-visual-design/learn-about-tertiary-colors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```html


<style>
  body {
    background-color: #FFFFFF;
  }
  
  .orange {
    background-color: #FFA500;
  }
  
  .cyan {
    background-color: #00FFFF;
  }
  
  .raspberry {
    background-color: #E30B5D;
  }
  
  div {
    height: 100px;
    width: 100px;
    margin-bottom: 5px;
  }
</style>
  
<div class="orange"></div>
<div class="cyan"></div>
<div class="raspberry"></div>

```

**Comment by CosmicDog2000** [comment]
I'm not sure what your issue is, but I see that your hex code for orange and raspberry do not match the instructions. You might start there and see if that fixes your issue.

**Comment by bcecil88** [comment]
I see now, sorry i must have overlooked it i jumped on Google for the hex
codes

**Comment by dhcodes** [comment]
Thanks @CosmicDog2000 . Closing as resolved.
