### ISSUE TITLE
Challenge [use-class-syntax-to-define-a-constructor-function] passes with incorrect solution

### ISSUE THREAD

**Issue by monty-cantsin** [freeCodeCamp/freeCodeCamp#15472]
Challenge [use-class-syntax-to-define-a-constructor-function](http://beta.freecodecamp.com/en/challenges/es6/use-class-syntax-to-define-a-constructor-function) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


/* Alter code below this line */
class Vegetable {
  
}
/* Alter code above this line */
const carrot = new Vegetable('carrot');
console.log(carrot.name); // => should be 'carrot'

```
the above code will pass even though console.log(carrot.name) returns undefined

**Comment by mdxedia** [comment]
Dear Sir/mdm,

Carrot is all about burger method. Its a food as long as u can eat. Find
another chips.

Regards


[image: --]

Md Xedia
[image: https://]about.me/mxedia
<https://about.me/mxedia?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=chrome_ext>
