### ISSUE TITLE
Your image element should have the class smaller image.

### ISSUE THREAD

**Issue by Teddi86** [freeCodeCamp/freeCodeCamp#15471]
![size your images](https://user-images.githubusercontent.com/29310066/27402365-6421df26-5694-11e7-944e-b070a26617da.PNG)
Challenge [Size your Images](https://www.freecodecamp.com/challenges/size-your-images) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
  font-family: Lobster, Monospace;
  }

  p {
  font-size: 16px;
  font-family: Monospace;
  }
  .smaller-image{
    width: 100px;
  }  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class= "smaller.image" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by Teddi86** [comment]
What am I missing?

**Comment by aamills** [comment]
Check your formatting in this line...
`<img class= "smaller.image" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">`

Wrong symbol between smaller and image?

**Comment by Teddi86** [comment]
Omg, Thank you so much!!!!

**Comment by mdxedia** [comment]
Dear Sir,

Thanks for your email sent to me. Cat is Aldzun and cannot be count of
their ability to conquer its world. But the true one is kutulullah.

Regards


[image: --]

Md Xedia
[image: https://]about.me/mxedia
<https://about.me/mxedia?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=chrome_ext>

**Comment by texas2010** [comment]
@mdxedia 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!

**Comment by rahulv1997** [comment]
<style>
.smaller-image
{
   width: 100px;
    }
    
</style>

<img  src="https://bit.ly/fcc-relaxing-cat" class="smaller-image"/>
<img class="smaller-image" />
