### ISSUE TITLE
"Hello World" Run Test issue on Win 10 Edge Browser

### ISSUE THREAD

**Issue by deimateos** [freeCodeCamp/freeCodeCamp#15478]
#### Challenge Name

[Hello World](https://www.freecodecamp.com/challenges/say-hello-to-html-elements)

#### Issue Description

I've been using the site via Microsoft Edge without issue up until the [Hello World](https://www.freecodecamp.com/challenges/say-hello-to-html-elements) page. Entering the code for "Hello World", and clicking on either "Run Test" or "ctrl+enter" does nothing. I thought I was going crazy for a bit, but both operations on Firefox 54.0 perform perfectly. I'll be using firefox for now, but I thought I should bring this up.

#### Browser Information

* Browser Name, Version: Microsoft Edge 40.15063.0.0
* Operating System: Windows 10 Home
* Mobile, Desktop, or Tablet: Razer Blade 2015

#### Your Code

```js
<h1>Hello World</h1>



```
#### Screenshot

![hello](https://user-images.githubusercontent.com/5152229/27416319-94f5045c-56c1-11e7-897a-1353732f2138.JPG)

**Comment by erictleung** [comment]
@deimateos thanks for the issue. I am unable to even try to reproduce this error, because I don't have access to a Windows 10 machine. I'll leave this open for others to comment if they run into the same error. Additionally, I'm not sure how much support we're giving to Windows 10 Edge.

cc/ @freeCodeCamp/moderators

**Comment by parimatrix** [comment]
@deimateos thanks for the issue. Please recheck once again. I checked it right now and its working absolutely fine. My browser details and OS details are exactly same as yours. Please check again and report again.thanks!

**Comment by Greenheart** [comment]
@erictleung As MS Edge v40 is one of the latest releases, we probably want to support it. Edge has improved their standard compliance significantly over the past few years, although they still have work to do before getting to the level of Firefox and Chrome.

I just wonder what could cause this. If anyone are able to reproduce - please share any errors or other information you can see in the developer console of your browser **[F12] > Console** (or something similar).
