### ISSUE TITLE
Remove old static pages from freeCodeCamp platform

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15474]
We've factored several static pages out of freeCodeCamp's core platform. These are now stand alone GitHub Pages apps that we redirect to. 

There is still some dead code associated with these pages (views, routing functions, etc.) that we should remove.

Here are a few static pages that we should go through and delete all trace of:
- [x] Terms of Service
- [x] Privacy
- [x] Code of Conduct
- [ ] Shop
- [ ] About

And while we're in there, we should see whether there are any other completely static pages that should similarly be factored out and create separate issues for those.

**Comment by padulam** [comment]
I'd like to take this one on. Do these changes only need to be applied to the staging branch? Also 'How our Nonprofit Projects Work' seems like it would a good candidate to be factored out.

**Comment by mdxedia** [comment]
Dear Sir,

Okay agree with you. Non profits project for a unexpected coming event.

Regards


[image: --]

Md Xedia
[image: https://]about.me/mxedia
<https://about.me/mxedia?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=chrome_ext>

**Comment by texas2010** [comment]
I did PR Code of Conduct in backup/master. #15475
I will PR Code of Conduct in staging.

**Comment by dhcodes** [comment]
I already did Shop I believe. I do see a remnant in randomAPIs though so I'll take care of that shortly and also pick up the About page. @padulam do you want to handle the Terms of Service and Privacy pages?

**Comment by padulam** [comment]
@dhcodes Sounds good!

**Comment by dhcodes** [comment]
Merged @padulam's and checked them off the list.

**Comment by texas2010** [comment]
I did PR code of conduct in staging. #15522

**Comment by dhcodes** [comment]
Merged @texas2010.

**Comment by texas2010** [comment]
@QuincyLarson, Do we need to remove them in backup/master too? just wondering.

**Comment by QuincyLarson** [comment]
@texas2010 Thanks for your patience, and for fixing this. I think we can leave backup/master as-is for now.
