### ISSUE TITLE
No profile page yet, eh?

### ISSUE THREAD

**Issue by Canuckywoman** [FreeCodeCamp/freecodecamp#1547]
Challenge http://beta.freecodecamp.com/challenges/waypoint-join-our-chat-room has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

So since I couldn't log in to the beta site and I wasn't that far into the course, I thought I'd re-register. No problem, even with the same email and username.

Can't make a profile page though. 
<img width="1342" alt="fcc_bug_profile_page" src="https://cloud.githubusercontent.com/assets/6067368/9083566/a2350824-3b6b-11e5-9c38-b6386470f603.png">

Did I create more problems by re-registering? Sorry. *blush*

**Comment by benmcmahon100** [comment]
@Canuckywoman It is made clear to people that accounts may or may not work on the beta site. At that moment in time we had an issue with sign ins and sign ups which to my knowledge has since been fixed
