### ISSUE TITLE
Issue: Not registering the task is complete

### ISSUE THREAD

**Issue by duncanmccoll** [freeCodeCamp/freeCodeCamp#15480]
Challenge [Quoting Strings with Single Quotes](https://www.freecodecamp.com/challenges/quoting-strings-with-single-quotes) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.109 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = 'This string has "double quotes" in it. And "probably" lots of them.';



```

**Comment by codemzy** [comment]
Looking at that challenge, the code you have above is just an example given, it is not the actual challenge.

Your supposed to update the code that your given (if you reset the challenge) you will see this...

`var myStr = "<a href=\"http://www.example.com\" target=\"_blank\">Link</a>";`

You need to update that code as per the instructions...

Instructions
Change the provided string from double to single quotes and remove the escaping.

**Comment by dhcodes** [comment]
Thanks @codemzy. Closing as resolved.
