### ISSUE TITLE
Waypoint: Label Bootstrap Wells - first challenge not correctly checked

### ISSUE THREAD

**Issue by pieterdeville** [FreeCodeCamp/FreeCodeCamp#1548]
Challenge http://beta.freecodecamp.com/challenges/waypoint-label-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I have the following code, but the the first challenge "Add an h4 element to each of your <div class='col-xs-6'> elements." is not correctly validated (see screenshot below).

```
<div class='container-fluid'>
  <h3 class='text-primary text-center'>jQuery Playground</h3>
  <div class='row'>
    <div class='col-xs-6'>
      <h4>#left-well</h4>
      <div class='well' id='left-well'>
        <button class='btn btn-default target'></button>
        <button class='btn btn-default target'></button>
        <button class='btn btn-default target'></button>
      </div>
    </div>
    <div class='col-xs-6'>
      <h4>#right-well</h4>
      <div class='well' id='right-well'>
        <button class='btn btn-default target'></button>
        <button class='btn btn-default target'></button>
        <button class='btn btn-default target'></button>
      </div>
    </div>
  </div>
</div>
```
<img width="1280" alt="screen shot 2015-08-05 at 12 16 17" src="https://cloud.githubusercontent.com/assets/13466453/9083671/71ed22c2-3b6c-11e5-8670-dda7ec9f89d4.PNG">

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1544

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

**Comment by rowansen** [comment]
every asking for help has been duplicated with the same issue but no Answer?

**Comment by bugron** [comment]
@rowansen thanks for you comment!
Possible reason - this is not a critical issue. 
In last few days @BerkeleyTrue closed ~ **100 duplicate** issues. And there are more than **540** issues currently open. [FreeCodeCamp](http://www.freecodecamp.com)'s team and [FreeCodeCamp](http://www.freecodecamp.com)'s campers do their best to resolve as many issues as they can. And you can also help them.

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by esaky** [comment]
`i thought and added the code #left-well and #right-well as id in the text <h4>.`
