### ISSUE TITLE
Clarification required on more than three repetitions

### ISSUE THREAD

**Issue by Blauelf** [freeCodeCamp/freeCodeCamp#15481]
Challenge [reuse-patterns-using-capture-groups](http://beta.freecodecamp.com/en/challenges/regular-expressions/reuse-patterns-using-capture-groups) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I have some clarification issue.

There is some test case

> Your regex should not match `"42 42 42 42"`.

which passes when my regular expression *matches* this string, which is an obvious bug.

Also, behaviour for extra characters around the number that's repeated twice (like a fourth copy) is not specified in the task description, so should "12 2 23" or "42 42 42 42" match?

```js
let repeatNum = "42 42 42 42";
let reRegex = /^(\d+)\s\1\s\1$/; // Change this line
let result = reRegex.test(repeatNum);
```

**Comment by erictleung** [comment]
@Blauelf thanks for the issue. Yes, there's an error for that [test](https://github.com/freeCodeCamp/freeCodeCamp/blob/5d408b2b105fd71b36f434a9d4303166bf8a7e92/seed/challenges/02-javascript-algorithms-and-data-structures/regular-expressions.json#L926). 

Additionally, yes, the challenge requirements is imprecise. We could change it to something like

> Use `capture groups` in `reRegex` to match numbers that are repeated only three times in a string, each separated by a space.

**Comment by dakshshah96** [comment]
@erictleung I'd like to work on this.

**Comment by erictleung** [comment]
@dakshshah96 awesome! Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help in case you need clarification or help on making changes. Thanks!

**Comment by dakshshah96** [comment]
@erictleung Thanks! Should I fix both the test as well as the description in the same commit?

**Comment by erictleung** [comment]
@dakshshah96 yes, that'd be great!

**Comment by dakshshah96** [comment]
@erictleung Made the change here: #15515
