### ISSUE TITLE
Disappearing advice panel

### ISSUE THREAD

**Issue by garysmeade** [FreeCodeCamp/FreeCodeCamp#1549]
Challenge http://beta.freecodecamp.com/challenges/waypoint-create-a-set-of-radio-buttons has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
When starting to enter an <input> tag I found the advice section disappear.  Here is a screenshot just prior to the tag input:
![screen shot 2015-08-05 at 8 21 51 pm](https://cloud.githubusercontent.com/assets/13364192/9083698/bfbd56a0-3baf-11e5-87ea-ec4daa60c65d.png)

And just upon entering "<i" the advice window disappears as below:
![image](https://cloud.githubusercontent.com/assets/13364192/9083773/697789fe-3bb0-11e5-958c-e5e9aecf1d9d.png)

**Comment by benschenker** [comment]
Hey @garysmeade thanks for posting this issue!

This is really similar to #1081, please follow the discussion there.
