### ISSUE TITLE
I don't know whats wrong with this challenge.

### ISSUE THREAD

**Issue by prashantmasule** [freeCodeCamp/freeCodeCamp#15498]
Challenge [Nest an Anchor Element within a Paragraph](https://www.freecodecamp.com/challenges/nest-an-anchor-element-within-a-paragraph) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<p>View more 
  <a href="http://www.freecatphotoapp.com">cat photos
  </a>
</p>
<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by jonathanihm** [comment]
Hi there!  I am able to get your code to pass, could you post a description of what errors you are getting and possibly a screenshot?

Cheers!

**Comment by texas2010** [comment]
@prashantmasule you have two opinions.

first, try the refresh on that challenge. 
or second, you could copy your code then reset it then paste it.

I hope that will solve a problem.

I close this because this doesn't have a bug. we could reopen this issue if you still have a problem.
