### ISSUE TITLE
Cant' understand how we are going to target 2nd child of 'well' if we have not mentioned element 'well' anywhere in the query..

### ISSUE THREAD

**Issue by Shikhargupta1** [freeCodeCamp/freeCodeCamp#15496]
Challenge [Target a Specific Child of an Element Using jQuery](https://www.freecodecamp.com/challenges/target-a-specific-child-of-an-element-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
html

<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
    $("#right-well").children().css("color", "orange");
 ------->   $(".target:nth-child(2)").addClass("animated bounce");

  });
</script>

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by jonathanihm** [comment]
Hi there!

It looks like you may want to ask for help in the chat rooms or message board!  There is a way to do this, so keep trying and ask for help if you get stuck!

Cheers!

**Comment by Shikhargupta1** [comment]
Solving that problem wasn't the problem, it's the concept.
But thanks I think I have figured it out and I also used the chat rooms and
even wrote back what I thought is the satisfactory answer.
But I still think the language used in the question is not appropriate.
What u should be telling is to target the 2nd child of class 'target'
rather then class 'well'

**Comment by jonathanihm** [comment]
I am having trouble seeing the wording that you are.  Could you copy and paste the actual wording on the challenge and maybe we can change it?  What I see is this:

`Make the second child in each of your well elements bounce. You must target the children of element with the target class.`

**Comment by tommygebru** [comment]
@Shikhargupta1 I believe you make a good point, I just completed the challenge, and had to read the last bit of instructions maybe 3-4x times to understand that it needed to be rewritten from:

"Make the second child in each of your well elements bounce. You must target the children of element with the` target` class."

to the following

"Make the second child with class of `target` in each of your well elements bounce."

@jonathanihm @Shikhargupta1 do you think is this more readable?

**Comment by jonathanihm** [comment]
I see what is being said now and I see the ambiguity.  I agree there needs to be a wording change.

**Comment by tommygebru** [comment]
Hey @jonathanihm github first thing in the morning :) i would like to work this PR

**Comment by jonathanihm** [comment]
Sounds good!  Also, you may want to consider including wording regarding the well class as well so we know what the parent of the child is.  Maybe something like this: 

"Make the second child of every `.well` target bounce.  You will want to target children elements using the `target` class"

**Comment by tommygebru** [comment]
very nice :+1:  will do
