### ISSUE TITLE
Sticky Highlighting on 'Community' Nav Bar Button

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/freeCodeCamp#15509]
On beta/staging, if you click the community button on the nav bar, it remains highlighted even after you navigate away and the menu closes. I believe this is unintentional and if the menu is not open, it should not remain highlighted in the navbar.

**Comment by ZacharyCauchi** [comment]
Right, I see. what you mean. hovering on the community button displays the drop down menu, clicking on the community button has no actual effect (unlike the others in the nav bar), so it remains highlighted. This is my first attempt at helping an open source project, so I'll give it a go and get back to you! :nerd_face:
