### ISSUE TITLE
Beta: ES6: Create an Export Fallback with export default

### ISSUE THREAD

**Issue by JM-Mendez** [freeCodeCamp/freeCodeCamp#15507]
Challenge [create-an-export-fallback-with-export-default](https://beta.freecodecamp.com/en/challenges/es6/create-an-export-fallback-with-export-default) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The code below is what the test is currently expecting, but default exports cannot be used with var, let, or const
[Ref here under 'using default export'](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export#Using_the_default_export)
```js

export default const subtract = (x,y) => {return x - y};

assert(code.match(/export\s+default\s+const\s+subtract\s+=\s+\(x,y\)\s+=>\s+{return\s+x\s-\s+y;}/ig))

```

**Comment by dhcodes** [comment]
confirmed. Submitted a fix.
