### ISSUE TITLE
Caesars Cipher i GOT RESULT BUT ONE SMALL ISSUE

### ISSUE THREAD

**Issue by CSE13124** [freeCodeCamp/freeCodeCamp#15505]
Challenge [Caesars Cipher](https://www.freecodecamp.com/challenges/caesars-cipher) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

function rot13(str) { 
  // LBH QVQ VG!
  var str1=str.split("");
  var value=[];
  var newstr;
  for(var i=0;i<str.length;i++){
   value[i] = str.charCodeAt(str1[i]);
  }
  for(var j=0;j<str1.length;j++){
  if(value[j]>64 && value[j]<78){
    value[j]+=13;
 }
    else if (value[j]>77 && value[j]<90){
      value[j]-=13;
    }
    else{
      value[j]=value[j];
    }
  }
  for(var k=0;k<str.length;k++){
   value[k]=String.fromCharCode(value[k]);
  }
  value=value.join("");
  return value;
}

// Change the inputs below to test
rot13("SERR PBQR PNZC");

```
I got result even :  FFFFFFFFFFFFFF
THE LENGTH SAME AS STR.LENGTH

**Comment by jonathanihm** [comment]
Hi there,

Your code definitely contains bugs!  Please reach out to the chatroom or message board and ask for help!  

Cheers!

**Comment by CosmicDog2000** [comment]
That's what I was going to say. You might want to refresh yourself on methods to add items to an array. Good luck!

**Comment by tommygebru** [comment]
For more help try sharing your code and ask for hints, tips, and code review in the Freecodecamp Chatrooms specifically @CSE13124 you want to join HelpJavascript
Happy Coding! :tada: :smile: :tada:

# CLOSE ISSUE
