### ISSUE TITLE
Bad Gateway; so much for beta

### ISSUE THREAD

**Issue by Canuckywoman** [FreeCodeCamp/FreeCodeCamp#1550]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I finished this challenge, no prob, but when I clicked to continue, I got this page. I guess I can't go any further in Beta...Oh well, I tried to help!

<img width="1118" alt="fcc_bugs_bad_gateway" src="https://cloud.githubusercontent.com/assets/6067368/9083839/ea28dc62-3b6d-11e5-9760-427b3f2aa112.png">

**Comment by pieterdeville** [comment]
You could continue by going to:

http://beta.freecodecamp.com/map 

and select your next challenge.

**Comment by Canuckywoman** [comment]
Could, but doesn't actually fix it.

**Comment by benmcmahon100** [comment]
Please use the challenge map for now as it is a beta there is a lot of stuff chopping and changing constantly so fixing this and then making a change may cause the bug again. Any ideas @BerkeleyTrue ?

**Comment by Canuckywoman** [comment]
Fair enough. I'm mid jQuery now so would rather finish what I started in the old site...unless there is a huge advantage to starting over in beta...
