### ISSUE TITLE
replacing-if-else-chains-with-switch ??? 

### ISSUE THREAD

**Issue by bneng** [freeCodeCamp/freeCodeCamp#15504]
**Replacing if/else chains with switch**

https://www.freecodecamp.com/challenges/replacing-if-else-chains-with-switch

#### Issue Description
I have worked this several different times, removing my code, refreshing the browser, clearing the cache, wiping my code, etc.  

#### Browser Information
* Browser Name, Version: Chrome Version 58.0.3029.110 (64-bit)
* Operating System: Mac OS 10.12.2
* Mobile, Desktop, or Tablet: Desktop

With this code below I have alternately gotten:
(1) the first three issues stating that I should not have if-else statements in my code, but all the rest of the switch-test issues correct. 

To fix this, I deleted the original if-else code that I'd obscured (//).  Still got these issues.
 
(2) Cleared my code, refreshed the browser, cleared the cache, re-set the exercise code:  The "successful" passed switch items remained, but the if-else complaints persisted.  

(3) I again cleared the original code, refreshed the browser, re-set--hit the "remove my code" button on the exercise refresh, as before.  Then I re-pasted my code that had achieved success with the actual switch issues, while not clearing the if-else complaints(despite having no if-elses). 

I then obscured once again the original if-else code of the exercise.  I hit "Test" and this time I got "Maximum call overload" or something to that effect.  

(4) I again clear, clear the cache, restart, etc.  Input my "good" code and removed the original exercise code.  This time, again, I passed all switch challenges, but the exercise continued to claim that I still had "if-else" statements in my code, and did not have "at least 3 break statements".  As you will see, I had quite a few break statements.  

 I'm going to move on anyway, but I wonder what if anything is wrong with my code.  Or the browser or browser version I'm using or...what?

#### Code

```js
function chainToSwitch(val) {
  var answer = "";

  switch(val) {
   case chainToSwitch("bob"): 
      answer = "Marley";
      break;
    case chainToSwitch(42):
      answer = "The Answer";
       break;
    case chainToSwitch(1):
      answer = "There is no #1";
       break;
    case chainToSwitch(99):
      answer = "Missed me by this much!";
       break;
    case chainToSwitch(7):
      answer = "Ate Nine";
      break; 
    case chainToSwitch("John"):
        answer ="";
        break;
    case chainToSwitch(156):
        answer = "";
  }
    
/*  if (val === "bob") {
    answer = "Marley";
  } else if (val === 42) {
    answer = "The Answer";
  } else if (val === 1) {
    answer = "There is no #1";
  } else if (val === 99) {
    answer = "Missed me by this much!";
  } else if (val === 7) {
    answer = "Ate Nine";
  }*/
  
  return answer;  
}

// Change this value to test
chainToSwitch(7);
```

**Comment by bneng** [comment]
The Exact error message is:  "Maximum call stack size exceeded" - But in the meantime, I get all the switch challenges noted as "correct" and the three complaints about how I should not have any If-else statements in the editor, and that I should have "at least 3 break statements" are not satisfied. 

To address the presence of the "If-else" statements in the editor, (even though they existed in the original exercise code, I had obscured all of the original exercise code in the editor with */ - */), I tried again, deleting all the obscured original exercise code, leaving only what I thought would now be recognized as 100% correct.  But after refreshing, etc. I still got the same issues:
(1) the maximum call stack error message
(2) all passed but the first 3--still not reading the fact that I have more than 3 break statements in the code and that all the if-else statements are gone. 
What am I missing?

**Comment by GingerDragon7** [comment]
hello bro!!!
this is my code....just now i have solved!!

![screenshot 139](https://user-images.githubusercontent.com/17198965/27494371-3f9f23ce-586b-11e7-9e1e-094c07a13645.png)

**Comment by GingerDragon7** [comment]
You can post a screenshot if the problem still persists.
Cheers!!

**Comment by erictleung** [comment]
@bneng Thank you for reporting this issue. You're creating infinite loops because your function never resolves itself. Please take a look at the example of how to implement `switch` statements. You don't need to call `chainToSwitch` within the switch statement. If you need a hint, you can take a look at the code someone has kindly shared above. In the future, please head to the Gitter chat rooms for coding help.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the "help" button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [full list of official chatrooms](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding!
