### ISSUE TITLE
Sass Use @each to map over items in a list

### ISSUE THREAD

**Issue by benjaminadk** [freeCodeCamp/freeCodeCamp#15510]
I can entering in correct code in Sass Use @each to map over items in a list but not passing the tests.

#### Challenge Name

https://beta.freecodecamp.com/en/challenges/sass/use-each-to-map-over-items-in-a-list

#### Issue Description

This code works on codepen. but not in beta fcc. also, did not see $key syntax in @each section of Sass Docs.  the $key syntax did not work for me on codepen either. thanks.
#### Browser Information

* Browser Name, Version: chrome latest version
* Operating System: Version 59.0.3071.91 (Official Build) (64-bit)
* Mobile, Desktop, or Tablet: chromebook acer 11

#### Your Code

```scss
@each $color in blue,black,red {
  .#{$color}-bg {
    background-color: $color;
}
}


```
#### Screenshot

![screenshot 2017-06-23 at 6 47 51 pm](https://user-images.githubusercontent.com/28043421/27504720-7d88595c-5844-11e7-9d5d-5c046c681276.png)
![screenshot 2017-06-23 at 6 49 00 pm](https://user-images.githubusercontent.com/28043421/27504732-aa0808b0-5844-11e7-9331-568039999ed6.png)

**Comment by gtreviranus** [comment]
SCSS is weird; I've had this issue outside of the course and I don't have a real answer. Maybe define a map more explictly like this?

```shell
// map
$colors: (
  blue: blue,
  black: black,
  red: red
);
```

and then use it in the `@each` function:

```shell
// function
@each $name, $color in $colors {
  .#{$name}-bg { 
    background-color: $color;
  }
}
```

**Comment by DusanSacha** [comment]
Unfortunately, as it was mentioned in #12699, compiling to SASS is not yet supported in the beta.
So it is not exactly a bug 😄
