### ISSUE TITLE
Challenge reads the ipsum text as wrong when it isnt

### ISSUE THREAD

**Issue by billyjacoby** [freeCodeCamp/freeCodeCamp#15517]
Challenge [Change the Font Size of an Element](https://www.freecodecamp.com/challenges/change-the-font-size-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.25 (KHTML, like Gecko) Version/11.0 Mobile/15A5304i Safari/604.1</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  .red-text {
    color: red;
  }
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack</p>
```

**Comment by indefinite0212** [comment]
hi @billyjacoby , your second `p` element's text is wrong. you need to use the text they provide which start with the word `Purr`. next time you can ask help at [help room](https://gitter.im/FreeCodeCamp/Help)

**Comment by billyjacoby** [comment]
damnit i’m sorry lol
