### ISSUE TITLE
Sass  Apply a Style Until a Condition is Met with @while

### ISSUE THREAD

**Issue by benjaminadk** [freeCodeCamp/freeCodeCamp#15511]
Challenge [apply-a-style-until-a-condition-is-met-with-while](https://beta.freecodecamp.com/en/challenges/sass/apply-a-style-until-a-condition-is-met-with-while) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 9460.60.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.91 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
I am simply not passing the test even though code is valid and checked on codepen.  The challenges were fine until i hit the @for directive so far @for @each and now @while all wont pass me.
![screenshot 2017-06-23 at 7 00 30 pm](https://user-images.githubusercontent.com/28043421/27504801-437e0e76-5846-11e7-8660-792d650e3a77.png)

```html


<style>
 $x: 1;
  @while $x <= 10 {
    .text-#{$x} { font-size: 5px * $x;}
    $x: $x + 1;
  }
  
  
</style>

<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>
<p class="text-6">Hello</p>
<p class="text-7">Hello</p>
<p class="text-8">Hello</p>
<p class="text-9">Hello</p>
<p class="text-10">Hello</p>

```

**Comment by DusanSacha** [comment]
Unfortunately, as it was mentioned in #12699, compiling to SASS is not yet supported in the beta.
So it is not exactly a bug 😄
