### ISSUE TITLE
Move from freecodecamp.com to freecodecamp.org

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15523]
Since we're a donor-supported nonprofit, we've long intended to transition from freeCodeCamp.com  to freeCodeCamp.org. Since we're bracing for a lot more campers when we release our new certificates and our Guides section, we should go ahead and make the transition now.

To preserve our standings in Google results, we'll want to [use 301 redirects throughout](https://www.hobo-web.co.uk/how-to-change-domain-names-keep-your-rankings-in-google/) and minimize broken links.

Here's what will be necessary:
- [x] Transition medium.freecodecamp.com
- [x] Transition forum.freecodecamp.com

- [x] Update any references within our codebase

- [x] Spin up new instance of production
    - [x] Add Facebook auth token
    - [x] Add GitHub auth token
    - [x] Add Google auth token
    - [x] Add Twitter auth token
    - [x] Add nginx route handler

- [x] Move dns to cloudflare
  - [x] Replicate previous dns records
  - [ ] Add .com to .org redirect to current production

**Comment by CodingPower472** [comment]
I support this change.  +1

**Comment by erictleung** [comment]
@QuincyLarson can this issue be closed? The production site, at least for me, does redirect from .com to .org if I initially visit the .com version.

**Comment by QuincyLarson** [comment]
@erictleung We still to finish shifting people over to freecodecamp.org (we still have separate servers running). Once we shut down the old servers completely, we'll close this issue.

**Comment by systimotic** [comment]
Only just found this issue 😄 I have an item to add to the list: the beta is currently only available on .com

**Comment by QuincyLarson** [comment]
@systimotic Yes - this is a known issue.
