### ISSUE TITLE
escape charactor bug

### ISSUE THREAD

**Issue by hardikpatel21** [freeCodeCamp/freeCodeCamp#15524]
Challenge [Escape Sequences in Strings](https://www.freecodecamp.com/challenges/escape-sequences-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line



```

**Comment by DusanSacha** [comment]
@hardikpatel21 Why do you think there is an issue in this challenge?
I tried your solution, it worked and it seems correct to me.

**Comment by tommygebru** [comment]
@hardikpatel21 your solution looks fine as @DusanSacha mentioned

For more help try sharing your code and ask for hints, tips, and code review in the Freecodecamp Chatrooms specifically @hardikpatel21 you want to join HelpJavascript

Happy Coding! :tada: :smile: :tada:

# CLOSE ISSUE

**Comment by hardikpatel21** [comment]
That why I wore there is a bug in this page coz when I run this code it is not showing the output.

**Comment by tommygebru** [comment]
@hardikpatel21 output is usually displayed with a return statement or console.log, however when I passed the statement with your solution I saw the output like so...


`var myStr = "FirstLine\n\\SecondLine\\\rThirdLine";`
