### ISSUE TITLE
Gomix website not available

### ISSUE THREAD

**Issue by JohnnyBizzel** [freeCodeCamp/freeCodeCamp#15526]
Challenge [Use the Twitchtv JSON API](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36</code>.
The link to [wind-bow.gomix.me/twitch-api](https://wind-bow.gomix.me/twitch-api)  is down.

**Comment by MiloATH** [comment]
Hi @JohnnyBizzel, 

[https://wind-bow.gomix.me/twitch-api](https://wind-bow.gomix.me/twitch-api) is working as expected. For more instructions, go to [https://wind-bow.glitch.me](https://wind-bow.glitch.me).

Here are some next steps that you should follow before we can help you with your query:

* Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
* Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](https://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT**:
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
