### ISSUE TITLE
Your sample project no longer loads...

### ISSUE THREAD

**Issue by AzFalconer** [freeCodeCamp/freeCodeCamp#15525]
Challenge [Use the Twitchtv JSON API](https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by AzFalconer** [comment]
Looks like this issue was first reported in March... 
[Issue #13930](https://github.com/freeCodeCamp/freeCodeCamp/issues/13930)
But was closed unresolved... WTH?

**Comment by erictleung** [comment]
@AzFalconer thanks for the issue. Can you be more specific which project doesn't load? Are you talking about https://codepen.io/freeCodeCamp/full/Myvqmo? Or are you talking about the API?

**Comment by andmckvr13** [comment]
@erictleung  I clicked the codepen link and the app only partially loads. I'm assuming this is what @AzFalconer was writing about

**Comment by andmckvr13** [comment]
@erictleung  looking at the source code there are only 3 user acccounts inside the channels array, perhaps adding a few more will fix this issue

**Comment by AzFalconer** [comment]
@erictleung, @andmckvr13  yes that is the sample pen. Looks like it has been fixed. Thank you. Lot of confusion in the forum/chat/various websites about this bonfire. Some say it has been deprecated and should just be skipped. I hope if that was true, it would be removed from the curriculum. So wanted to report the bug. 
Thank you for the prompt repair.

**Comment by erictleung** [comment]
@AzFalconer okay, thanks for the update. Closing this issue as resolved. Happy coding!
