### ISSUE TITLE
Size your Images

### ISSUE THREAD

**Issue by computer590** [freeCodeCamp/freeCodeCamp#15532]
Challenge [Size your Images](https://www.freecodecamp.com/challenges/size-your-images) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I entered in the appropriate code:    .smaller-image {
    width: 500px;
  } and it won't let me move on to the next step.. 
My code:
```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }
  .smaller-image: {width: 100px}
  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by Marmiz** [comment]
Dear @computer590 thanks for reporting this issue.

Your code is incorrect therefore you are not passing the challenge.
In this case you created the class but: 
- the class has a typo so it's not valid.
- it never get  assigned it to the `image`.

Please consider that Github is a place for reporting bugs only, next time ask for assistance first on one of the [official chat room](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).
Happy coding 👍

**Comment by texas2010** [comment]
Yep, one more task to do in there. 


@computer590 
Thanks for reporting this. But your code is incorrect.
These GitHub Issues are for reporting bugs on the freeCodeCamp website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
