### ISSUE TITLE
error on api of fcc

### ISSUE THREAD

**Issue by eladonline** [freeCodeCamp/freeCodeCamp#15547]
#### Challenge Name
Image Search Abstraction Layer
https://www.freecodecamp.com/challenges/image-search-abstraction-layer

#### Issue Description
when you click on the link to the cats images it return an error

#### Screenshot

![image](https://user-images.githubusercontent.com/20336964/27572207-2df20754-5b13-11e7-8c50-ca81a5902452.png)

**Comment by DusanSacha** [comment]
Hi @eladonline,
thank you for reporting the issue.
Could you provide the exact link, which returned an error? I tested all links in the challenge description and all were working fine to me.
