### ISSUE TITLE
steamrollArray issue

### ISSUE THREAD

**Issue by gpiliponyte** [freeCodeCamp/freeCodeCamp#15548]
Challenge [Steamroller](https://www.freecodecamp.com/challenges/steamroller) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var a = [];
function steamrollArray(arr) {
  for(var i in arr)  {
    if(Array.isArray(arr[i]) && arr[i]!==[]) steamrollArray(arr[i]);
    else a.push(arr[i]);
  }
  return a;
                    
}

steamrollArray([1, [2], [3, [[4]]]]); //should pass all the tests!

```

**Comment by erictleung** [comment]
@gpiliponyte thanks for the issue. You have global variables in your code. Our challenge tests run your function over and over and if you have any global variables, they will change with each test. So move your global variables to within your function and then you can complete the challenge accordingly. Happy coding!
