### ISSUE TITLE
String.startsWith() not supported by IE

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#15558]
Whilst investigating #15533 I found that IE11 does not support `String.protype.startsWith()` which is used [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/d9c166111b5d0b3d8e16c908e0f9dd73e5d6610a/common/app/routes/challenges/utils.js#L93) in our code base.

We need to refactor this method out

**Comment by CodingPower472** [comment]
I'm working on this.  I will refactor using a polyfill.

**Comment by Bouncey** [comment]
@CodingPower472 Thanks for taking this on. We do not need a pollyfill for this as it adds weight to the app bundle.

Can you see if there is an ES5 method or process of achieving the same thing please 👍 

Many thanks

**Comment by CodingPower472** [comment]
Alright.  I think I found an alternative.

**Comment by CodingPower472** [comment]
What is the status of this issue?
