### ISSUE TITLE
Beta - Waypoint: Target the Children of an Element Using jQuery

### ISSUE THREAD

**Issue by pieterdeville** [FreeCodeCamp/freecodecamp#1555]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Validation is not correct and does not correspond with description:
<blockquote>Give all the children of your #right-well element a color of green.</blockquote>

<blockquote>Your "target6" element should have green text.</blockquote>
is only validated with blue color:
```
$('#right-well').children().css('color','blue');
```

Second and Third validation are not valid.

<img width="1280" alt="screen shot 2015-08-05 at 14 22 23" src="https://cloud.githubusercontent.com/assets/13466453/9085496/92b83878-3b7d-11e5-97e8-54ac367f6f65.PNG">

**Comment by Renestl** [comment]
To add to this, the second validation checks as valid before any code is added.

![target children](https://cloud.githubusercontent.com/assets/13346359/9113932/d05e2102-3c1c-11e5-9b15-1273c78a60a6.PNG)

**Comment by BerkeleyTrue** [comment]
We are tracking bugs with this challenge in #1713 

Happy Coding!
