### ISSUE TITLE
Escaping Literal Quotes in Strings

### ISSUE THREAD

**Issue by vlastapolach** [freeCodeCamp/freeCodeCamp#15566]
Challenge [escaping-literal-quotes-in-strings](http://beta.freecodecamp.com/en/challenges/basic-javascript/escaping-literal-quotes-in-strings) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js

var myStr = "I am a \"double quoted\" string inside \"double quotes\"."; // Change this line

```

There is an error with testing the correct solution. Even if I type it correctly on the first pass, there is error, even after resetting code. 

For me worked to reload page with message "I found same saved work. Loading now." and then the same code was OK. 

here is the screenshot: [http://vlastapolach.cz/download/doubleQuotes.png](http://vlastapolach.cz/download/doubleQuotes.png)

**Comment by AndreyAzimov** [comment]
same
