### ISSUE TITLE
Profile Lookup challenge needs test with non-existent firstName AND prop

### ISSUE THREAD

**Issue by willnwhite** [freeCodeCamp/freeCodeCamp#15563]
#### Profile Lookup
https://www.freecodecamp.com/challenges/profile-lookup

#### Issue Description
There is no test with both a name and property that doesn't exist, e.g. "Bob" "address". If the user is capable of not knowing contacts or properties, the code should handle the case of them not knowing both.

**Comment by MiloATH** [comment]
Hi @willnwhite,

Thanks for the suggestion. I think this test might be redundant. However, I will go ahead and make a PR with the test.

**Comment by willnwhite** [comment]
My original motivation for this test was that I solved this challenge with code that returned 'No such property' for `lookUp("Bob", "address")`, which leads the user into thinking there is a contact called Bob, which is untrue.

**Comment by systimotic** [comment]
Hi all! Thanks a lot for reporting and even working on a fix. This test was indeed needed. However, we have already fixed it with https://github.com/freeCodeCamp/freeCodeCamp/pull/11821 The change is still in the beta, but once it goes live, this problem will be resolved.

Happy coding!
