### ISSUE TITLE
Wrong link in "Read thousands of coding articles" button in https://www.freecodecamp.com/settings

### ISSUE THREAD

**Issue by AlanGabbianelli** [freeCodeCamp/freeCodeCamp#15562]
#### Issue Description

In [Settings](https://www.freecodecamp.com/settings), the `Read thousands of coding articles` button points to the wrong page. The href is the same as the one in the `Add freeCodeCamp to my LinkedIn` button.

#### Screenshot

<img width="1110" alt="screen shot 2017-06-29 at 14 36 36" src="https://user-images.githubusercontent.com/14851208/27690186-85bc32fe-5cd8-11e7-8f23-b65271d8a862.png">

**Comment by CodingPower472** [comment]
I've got this.

**Comment by CodingPower472** [comment]
It seems the issue is the "Add freeCodeCamp to my LinkedIn" button

**Comment by CodingPower472** [comment]
I don't actually see where the code actually assigns these links.

**Comment by erictleung** [comment]
@AlanGabbianelli thanks for the issue. Yes, this seems like an error. I'm not sure what the correct link should be though.

cc/ @QuincyLarson do you know what link is supposed to be here?

**Comment by antonioalmeida** [comment]
It's probably meant to link to the Medium publication - https://medium.freecodecamp.org/

**Comment by QuincyLarson** [comment]
Thanks for raising this issue. Sorry it took me so long to notice this issue. I've fixed this.
