### ISSUE TITLE
Lessons that I've Taken are Not Showing as Completed!

### ISSUE THREAD

**Issue by MtZionCode** [freeCodeCamp/freeCodeCamp#15560]
I have taken hundreds of lessons here on Free Code Camp. But when I go to the "Map" menu, none of the lessons that I have taken previously are showing as greyed out and checkmarked! I'm afraid that this might affect me getting my certification. Can anyone tell me why this is happening? I need an explanation now!

**Comment by raisedadead** [comment]
@MtZionCode Hi, Can you confirm that your profile is https://www.freecodecamp.com/MtZionCode?

Is it possible that you have a different account as well? This could happen if you chose to sign up via an email address, and then signed up again via Github, accidentally?

**Comment by harsh4123** [comment]
yup same happened with me

**Comment by raisedadead** [comment]
> Is it possible that you have a different account as well? This could happen if you chose to sign up via an email address, and then signed up again via Github, accidentally?
