### ISSUE TITLE
'Show local weather' challenge needs update since "CodePen is going HTTPS"

### ISSUE THREAD

**Issue by JayV3e** [freeCodeCamp/freeCodeCamp#15576]
#### Challenge Name

Show the Local Weather

#### Issue Description

Taken from CodePen website :

> What Will Change
> Beginning June 1, 2017:
> 
> Every page on CodePen will be served over HTTPS.
> Requests that come in over HTTP will be redirected to HTTPS.
> We’ll attempt to request an HTTPS version of any content linked via HTTP. If an HTTPS version is available, we’ll load that content over HTTPS. If not, the content may fail to load (more details below).

Therefore we cannot use the second method proposed on the challenge :

> Or:
> 
> Use an Internet Protocol API to get user location (ex. IP-API) and then use the OpenWeatherMap API for the weather. Be sure to connect to CodePen.io via http://.

The other option gives a cross-origin error : 

> Use HTML5 Geolocation to get user location and then use the Dark Sky API which uses an HTTP Secure connection for the weather. Also, be sure to connect to CodePen.io via https://.

Managed to work around it by adding "https://crossorigin.me/" before the actual api request path.

I think this is would be useful information for campers.

**Comment by dhcodes** [comment]
Closing in favor of #15598
