### ISSUE TITLE
Change color/background color in Night Mode preview

### ISSUE THREAD

**Issue by vlastapolach** [freeCodeCamp/freeCodeCamp#15572]
Challenge [create-visual-balance-using-the-textalign-property](http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-visual-balance-using-the-textalign-property) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Please, is it possible to change
a) font color or
b) background color of preview window 
in the Night Mode? 
The black text on dark grey background is pretty hard to read (and especially with lower contrast - which is widely used at night)

Screenshot here: [http://vlastapolach.cz/download/nightMode.png](http://vlastapolach.cz/download/nightMode.png)

Thank you

**Comment by texas2010** [comment]
@hallaathrad, i think this case for you.
