### ISSUE TITLE
React : Challenge no. 47 

### ISSUE THREAD

**Issue by IshtmeetSinghRissam** [freeCodeCamp/freeCodeCamp#15577]
The  challenge "Use Array.map() to dynamically render elements" has a problem. The solution is correct, and it shows a error "Test case not passed", for the last case. Even, pressing the "Get solution code button" didn't worked. Everything was working, according to the challenge.

#### Screenshot
![fcc](https://user-images.githubusercontent.com/29104610/27764327-50763ca6-5eb4-11e7-8132-73358a29003e.png)

**Comment by Manish-Giri** [comment]
@IshtmeetSinghRissam It works for me - 


![react](https://user-images.githubusercontent.com/11348778/27842729-92ae8bd2-60da-11e7-8e47-826dd0a747ed.png)

**Comment by dhcodes** [comment]
Closing as resolved. Please reopen if this still is not working correctly.
