### ISSUE TITLE
learn to code javascript at freeCodeCamp logo      Community     Map     Donate      [ 345 ]   Basic Data Structures: Iterate Through All an Array's Items Using For Loops Test 2 displayed to user is incorrect

### ISSUE THREAD

**Issue by Sluthsaber95** [freeCodeCamp/freeCodeCamp#15571]
Challenge [iterate-through-all-an-arrays-items-using-for-loops](https://beta.freecodecamp.com/en/challenges/basic-data-structures/iterate-through-all-an-arrays-items-using-for-loops) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js

function filteredArray(arr, elem) {
    let newArr = [];
    let otherArr = [];
    // change code below this line
    for (let i = 0; i < arr.length; i++) {
        if (arr[i] === elem || arr[i].indexOf(elem) !== -1) {
            otherArr.push(arr[i]);

        } else {
            newArr.push(arr[i]);
        }
    }
    // change code above this line
    return newArr;
}

console.log(filteredArray([
    ["trumpets", 2],
    ["flutes", 4],
    ["saxophones"], 2
], 2));
```

Test two currently is stated as 

filteredArray([ ["trumpets", 2], ["flutes", 4], ["saxophones"], 2], 2) should return [ ["flutes", 4] ]

The correct test should return

filteredArray([ ["trumpets", 2], ["flutes", 4], ["saxophones"], 2], 2) should return[ [ 'flutes', 4 ], [ 'saxophones' ] ]

**Comment by earthtone0ne** [comment]
Looks like the last item's bracket is in the wrong place -- should be `["saxophones", 2] ]` to continue the pattern, which would make the expected result correct -- I'll do a PR
