### ISSUE TITLE
Change Text Inside an Element Using jQuery

### ISSUE THREAD

**Issue by westcoast23** [freeCodeCamp/freeCodeCamp#15584]
#### Issue Description

I can seem to get freecode camp to work with me on this issue, its annoying as hell. Theyre so vague its disgusting. Ive tried 10 different ways to "Emphasize the text in your target4 button by adding HTML tags." and nothing works and all the "solutions" i find on the internet dont work either. Maybe free code camp is broken. who knows

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```html
<script> $(document).ready(function() { $("#target1").css("color", "red");$("#target4").html("<i>#target4</i>")
 }); </script>


<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```

**Comment by westcoast23** [comment]
can't*

**Comment by Manish-Giri** [comment]
@westcoast23 You didn't try using `em` tags? There's even an example shown using `em` tags.

**Comment by westcoast23** [comment]
I tried that too... :/

Thanks, 
~Brandon~

**Comment by Mortichar** [comment]
Could you show more of your code? Or is that it? Because what you have is not enough to accomplish the task. You can copy it in \`\`\```` tags ```\`\`\` to keep formatting and automatically use escape characters.

**Comment by texas2010** [comment]
@westcoast23, did you go to chat room or forum for ask help about it first?

[HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript)

**Comment by manmeet17** [comment]
Just change the **i** tag to **em** tag , the challenge says that you need to emphasize the text 
I know that i tag and em tag are supposed to give the same end result, but the difference is
**i** has the purpose of presenting something in italicised style.
**em** has the purpose of giving emphasis to the content.
HTML is all about the semantics

**Comment by westcoast23** [comment]
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("target4").html("<i></i>");
    
  });
</script>



<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

**Comment by westcoast23** [comment]
damn... it didnt post right, i tried the i tas and it still wont work right

**Comment by westcoast23** [comment]
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").html();
    
  });

</script>

**Comment by westcoast23** [comment]
$("#target4").html(<i>"#target4"</i>);   

idk what else to do

**Comment by manmeet17** [comment]
Try 
$("#target4").html("<em>#target4</em>");
Thats what I meant in my previous comment

**Comment by Manish-Giri** [comment]
@westcoast23 You're not using `em` tags. I told you that earlier as well. If you tried that code, and it still didn't work, please head to the [Help Room](https://gitter.im/FreeCodeCamp/Help).

**Comment by westcoast23** [comment]
didnt work... this freecode camp thing is really frustrating i think im getting stomach ulcers bc of it. Its THAT stressful. Theres no solid guide, its like trying to figure out a puzzle minus the part that the reason im taking the course is to learn... not to have to guess everyday and hope for the best on every lesson bc they are so vague

**Comment by westcoast23** [comment]
i tried the em tags several times a thousand different ways
