### ISSUE TITLE
Beta - Manipulating Objects

### ISSUE THREAD

**Issue by pieterdeville** [FreeCodeCamp/freecodecamp#1558]
Challenge http://beta.freecodecamp.com/challenges/manipulating-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The exercise requires to add a property `age` to `myDog`, but the validation requires to add the property `bark`.
```
//Let's add the property age to myDog
myDog['bark'] = 'whoof';
```
The code above is correctly validated. 
<img width="1280" alt="screen shot 2015-08-05 at 16 10 46" src="https://cloud.githubusercontent.com/assets/13466453/9087693/847b937c-3b8c-11e5-9b59-bb41b49b841c.PNG">

**Comment by benmcmahon100** [comment]
Hey there just sorted this now!
