### ISSUE TITLE
Use Colorblind-OK colors in box model challenges 

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15580]
#### Challenge Name
https://www.freecodecamp.com/challenges/adjusting-the-padding-of-an-element and the subsequent challenges

#### Issue Description

These challenges rely on the user being able to discern between red and green, and red-green colorblindness is common. We should change these colors to colors that are less likely to be confused, and be sure to update the copy and tests for these challenges where necessary.

**Comment by Manish-Giri** [comment]
I'll take a crack at this.

**Comment by Darkpingouin** [comment]
I've corrected it. Need translation help for Spanish, Russian and pt-br...
