### ISSUE TITLE
Recieveing error stating that i used a case, switch, or if else statement but did not use any of them.

### ISSUE THREAD

**Issue by Terron23** [freeCodeCamp/freeCodeCamp#15585]
Challenge [using-objects-for-lookups](http://beta.freecodecamp.com/en/challenges/basic-javascript/using-objects-for-lookups) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js


// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  var lookup = {
    "alpha": "Adams",
       "bravo": "Boston",
       "charlie": "Chicago",
      "delta": "Denver",
      "echo": "Easy",
    "foxtrot": "Frank"
  };
  
  result = lookup[val];

 
  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");

```
my code 
// Setup
function phoneticLookup(val) {
  var result = "";

  // Only change code below this line
  var lookup = {
    "alpha": "Adams",
       "bravo": "Boston",
       "charlie": "Chicago",
      "delta": "Denver",
      "echo": "Easy",
    "foxtrot": "Frank"
  };
  
  result = lookup[val];

 
  // Only change code above this line
  return result;
}

// Change this value to test
phoneticLookup("charlie");

**Comment by Marmiz** [comment]
I was able to pass the challenge with your code on Chrome.

Try refreshing the browser and see if the outcome changes.
If not, are there any errors in the browser's console that may give us a bit more information on this?

**Comment by dhcodes** [comment]
Closing as resolved. Please reopen if you are still experiencing this.

**Comment by Terron23** [comment]
Yes it works
