### ISSUE TITLE
I don't understand the instructions to "use strict";

### ISSUE THREAD

**Issue by FullstopCoding** [freeCodeCamp/freeCodeCamp#15586]
I put some comments in my code, but I'm not sure if this was correct, the challenge passed with/without the line at the top, but I'm not sure if I used it in the manner that you were hoping.  Maybe clearer instructions if I used it incorrectly?  Hard to say :)  Keep up the good work though!

Challenge [explore-problems-with-the-var-keyword](https://beta.freecodecamp.com/en/challenges/es6/explore-problems-with-the-var-keyword) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

```js

"use strict"; // I don't understand the instructions or if this is right.

let redNosedReindeer = "Rudolph";
let favorite = redNosedReindeer + " is Santa's favorite reindeer.";


```

**Comment by AkiraLaine** [comment]
It might be confusing for a beginner. There's not explanation as to what `"use strict"` does.
Also, the instructions say to use "let" but doesn't tell you to remove the other `redNosedReindeer` variable. Feels like the instructions could be clearer.

@freeCodeCamp/moderators Thoughts?

**Comment by willnwhite** [comment]
> Some modern browsers require you to add "use strict"; to the top of your code before you can use the new features of ES6.

I would add ", including `let`", so it's clearer that `"use strict";` is connected to `let`.

**Comment by Talkingbaby** [comment]
Whatever error checking system fcc is using it mentions that use strict should be within function scope. Like this: function() {'use strict';}; So the first line of the function has use strict and the rest of the code comes after. That would mean the santa variables would have to go inside the function as well. Not really sure if that is what fcc wants though. Also for these activities check the errors, do some problem solving, and check google. That's what I had to do as well.
