### ISSUE TITLE
Link to gitter FreeCodeCamp chat rooms is missing from challenges

### ISSUE THREAD

**Issue by SkyC0der** [freeCodeCamp/freeCodeCamp#15581]
#### Issue Description

There used to be a link in all of the challenges where you could ask for help in the [Gitter FreeCodeCamp chat rooms](https://gitter.im/FreeCodeCamp/home). That link is now missing and the challenge introducing us to the chat rooms is also gone.   

I can't find any commits or issues related to this change here in this github repo with the search of `chat in:title` and questions about it on the forums have gone unanswered.  

I'm reporting this issue in case the change was unintended, and for a notification about the change if not.

Thanks!

Here are the forum questions referred to above:
- https://forum.freecodecamp.org/t/what-happened-to-the-help-button-that-would-lead-to-the-chat-page/133204/4
- https://forum.freecodecamp.org/t/freecodecamp-help-chat-not-working/132746/5

Example of previous functionality ("Chat" link partially hidden by flyout menu):  
![Image of FreeCodeCamp Chat Room Link](https://s23.postimg.org/k327kftwr/Untitled.png)

**Comment by Manish-Giri** [comment]
@SkyC0der From what I hear, the help button was removed (intentionally) because it appeared that new campers were being asked for signing up for too many accounts.

**Comment by texas2010** [comment]
@SkyC0der, well. Quincy did remove chat button. he did make the plan for removing it. 

I am sorry about I don't have a news about why is it been removed.

thank you for considering about it.
I closed this issue because of nothing wrong with this freecodecamp site. and Quincy removed chat button.

**Comment by SkyC0der** [comment]
That is unfortunate, and strange that there is no commit or announcement associated with the change. 

Anyway, as long as the change was intended, it is fine to close this issue. I mainly filed it as a potential bug, not a "question" as the bot has labeled it. 

**What is the best way to provide feedback that we should add "Chat" back as a visible feature for requesting help with the challenges?** 

I've been using the forums for a few days now and find it to be an inferior experience compared to the realtime assistance we give and receive on gitter.

Thanks!

**Comment by texas2010** [comment]
@SkyC0der, no problem. there actually have commit. it is in backup/master branch if you wonder.


> What is the best way to provide feedback that we should add "Chat" back as a visible feature for requesting help with the challenges?

Well, I don't have an answer for your question. sorry again.

**Comment by VicC93** [comment]
@SkyC0der  Gitter chat still exists, you can go to Gitter(dot)im and sign in with your Github account, simple as that.
Happy coding

**Comment by SkyC0der** [comment]
@VicC93 This issue has been closed since July 3.  

Check the link I put in the original issue description for a link to Free Code Camp's rooms on Gitter - this issue was never about an inability to reach https://gitter.im.  It was originally about the link to the chat rooms getting removed from the Navbar at https://www.freecodecamp.org without notice.  

Happy coding
