### ISSUE TITLE
Manage a Book Trading Club Application Error

### ISSUE THREAD

**Issue by DavOnGit** [freeCodeCamp/freeCodeCamp#15583]
__Manage a Book Trading Club__  Example Application not working.

It was working but when i've tried to add a book with a wrong title it crashed (the dummy title was something like 'jhasdghfdk')...

@clnhll Can you check this one out?

**Comment by MiloATH** [comment]
Hi @DavOnGit, 

Thanks for reporting this issue. The app crashed on me as well. However, this repo doesn't manage that project. Please report that issue to the corresponding repo [here](https://github.com/clnhll/bookjump/issues).

**IMPORTANT**:
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only. 

Happy Coding!
