### ISSUE TITLE
tribute page doesn't include user stories and video is not working

### ISSUE THREAD

**Issue by deannekeene** [freeCodeCamp/freeCodeCamp#15596]
Challenge [build-a-tribute-page](http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; CrOS x86_64 9460.60.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.91 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The text in the challenge says "Fulfill the user stories by getting all of the tests to pass. Use whichever libraries you need. Give it your own personal style.", But there are no user stories on the page?

Also, when I go to play the video, its not working. I am getting an error message of "an error occurred please try again later"

**Comment by Marmiz** [comment]
Dear @deannekeene thanks for reporting this issue.

As far as I'm concerned there is a UI revamp going on with the challenges, passing from a user story to a in-browser testing method.

All this challenges and description are about to be changed, videos as well.

Please refer to  #12753  or #15178 for further explanations.

Happy coding

**Comment by dhcodes** [comment]
Thanks @Marmiz. Closing as duplicate.
