### ISSUE TITLE
Won't recognise src to add image

### ISSUE THREAD

**Issue by SafraCoder** [freeCodeCamp/freeCodeCamp#15593]
Hi here, I am trying to add an image but even though I entered in src it won't let me move to the next challenge. Here is the code. I am using Google Chrome. 

```html
<img src="https://s3.amazonaws.com/freecodecamp/relaxing-cat.jpg" alt="Relaxing Cat">

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>
```
![image](https://user-images.githubusercontent.com/29798477/27808885-e86c467e-6042-11e7-9e30-2b7ac9d68ad7.png)

**Comment by texas2010** [comment]
@SafraCoder 
Thanks for reporting this. But your URL is incorrect. 
you suppose to use this URL `https://bit.ly/fcc-relaxing-cat`. your challenge will be pass.
These GitHub Issues are for reporting bugs on the freeCodeCamp website only.
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.
