### ISSUE TITLE
JSON & API curriculum doesn't prepare students for Intermediate Front-End Challenges

### ISSUE THREAD

**Issue by allardbrain** [freeCodeCamp/freeCodeCamp#15594]
#### Issue Description
I've been leading my students through the FCC exercises. Thanks for the amazing curriculum! Today, I was going through the JSON & API section to prepare for our next class. I looked ahead to the first Intermediate Front-End Project, and see that the students are to use the Twitter API. FCC hasn't provided instructions or tutorials on API keys, keeping API keys secret, how to hit a live API endpoint, how to code an HTTP request, etc. (except for the limited cat API example). The way the curriculum is currently structured, it seems like a huge leap from the exercises provided to using the Twitter API. I'm very much in favor of letting the students puzzle things out on their own for awhile, but there seem to be some major concepts that are missing. Is this something FCC is already working on? Thanks!

Another student has discovered this and posted in the forum as well: https://forum.freecodecamp.org/t/where-to-learn-about-api-weather-api-resources-needed/80090/5

**Comment by nsuchy** [comment]
I agree with this, the json lessons were really unclear, it was just like copy and paste this didn't explain much, very unusual for freeCodeCamp Challenges. Another camper helped me learn how to properly insert json keys into HTML but it shows a bigger problem if campers don't understand after going thru the json challenges.
