### ISSUE TITLE
Twitch API started using X-Frame-Option. Breaks anchor tags to Twitch in codepen.

### ISSUE THREAD

**Issue by zapcannon99** [freeCodeCamp/freeCodeCamp#15600]
#### Challenge Name: Use the Twitchtv JSON API

https://www.freecodecamp.com/challenges/use-the-twitchtv-json-api

#### Issue Description

Anchor tags to Twitch API (through the pass-around link) fail to load properly.

I believe the endpoint has implemented X-Frame-Option (set to sameorigin) and is blocking all attempts on codepen to render calls into a frame. Opening in a new tab also does not work.

#### Browser Information

* Browser Name, Version: Chrome Version 59.0.3071.115, Mozilla 54.0.1 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
Just check the example twitch app with the dev console open and see what happens.

https://codepen.io/freeCodeCamp/full/Myvqmo



```

**Comment by MiloATH** [comment]
Hi @zapcannon99, 

I just checked the freeCodeCamp codepen and can assure the Twitch API is functioning correctly.

As for how to make requests to an API, I encourage you to asking the [gitter chat](https://gitter.im/FreeCodeCamp/HelpJavaScript).

Here are some next steps that you should follow before we can help you with your query:

* Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
* Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](https://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.


Happy Coding!

**Comment by zapcannon99** [comment]
So you clicked on the hyperlinks that sends you the streamers' twitch homepages?

**Comment by zapcannon99** [comment]
Also for clarification, the problem is not with the API, it's with the hyperlinks to the streamers homepages, which, for whatever reason, are being blocked by chrome and mozilla as "ERR_BLOCKED_BY-CLIENT" (by chrome) or "operation is insecure" by Mozilla.

**Comment by nsuchy** [comment]
freeCodeCamp runs a API-keyless proxy at https://wind-bow.glitch.me/twitch-api/ maybe that'll help?

**Comment by zapcannon99** [comment]
@nsuchy 

I'm not talking about the keyless api, I know that works. I'm worried about a basic hyperlink to twitch that is somehow deemed as insecure by chrome and mozilla, but not safari.

But seeing how nobody else seems to be having this problem, then I'll just close the issue and ask on gitter like the first guy suggested.
