### ISSUE TITLE
https://tppr.me/5JhnJ error on the youtube video

### ISSUE THREAD

**Issue by IuryPiva** [freeCodeCamp/freeCodeCamp#15603]
Challenge [build-a-tribute-page](http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-tribute-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.50 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by Apoorv-Mittal** [comment]
Just click on the link and try to play the video. The error will be produced. This happens in safari and chrome browser. I have attached the screenshot of the issue. 


![screen shot 2017-07-06 at 10 42 13 pm](https://user-images.githubusercontent.com/22995574/27941049-82faa040-629c-11e7-9ebd-de26e7a6f3e2.png)

**Comment by raisedadead** [comment]
We are removing videos in beta, https://github.com/freeCodeCamp/freeCodeCamp/issues/12753
Please check for existing issues including closed ones while reporting.
