### ISSUE TITLE
Unsubscribing from email should unsubscribe duplicate accounts, too

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15606]
A lot of campers have accidentally created duplicate accounts, and even though they unsubscribe, they still receive emails because their duplicate account hasn't been unsubscribed. I get emails about this several times a week. Luckily, there's an easy fix.

When someone follows the unsubscribe link (like https://www.freecodecamp.com/unsubscribe/[email]) we should search for ALL accounts that have that email address, and unsubscribe all of them.

**Comment by jonathanihm** [comment]
I'll be glad to take this one

**Comment by jonathanihm** [comment]
Just curious how this happens, as I am looking at the user.json and it's marked as unique.

**Comment by jonathanihm** [comment]
Is this due to username being the email address?

**Comment by QuincyLarson** [comment]
@jonathanihm I'm not sure what has caused this, but there are indeed instances of multiple accounts with the same email address in the database. Cleaning these up may be a long, manual process.

In the meantime, we just need to ensure that the unsubscribe function unsubscribes these duplicate accounts as well.

**Comment by jonathanihm** [comment]
@QuincyLarson From what I can see, even if there are multiple clones of an email record, the User.updateAll functionality should find all records where email is equal to the email parameter passed in.  My suspicion is that if is true, the username could possibly be the issue.  In randomAPIs.js, the query to find emails is:

`var query = { email: req.params.email };`

I can update the query to do an or query on both email and username, but I honestly don't know if that would help.  Would it be possible to have someone query the production database and see if this indeed would fix this, as there is no way for me to duplicate this and I don't want to add code complexity if it won't do anything.

**Comment by BerkeleyTrue** [comment]
I'd first verify that two duplicate email accounts are not updated by the end point before writing any code. My suspicion is that the reports from users are in error and not an issue with the query. Luckily this is easily testable

**Comment by jonathanihm** [comment]
![image](https://user-images.githubusercontent.com/6002459/28235897-d704bc38-68dd-11e7-9f5f-ab2504caa7eb.png)

Set email unique to false locally and added two more users, then hit the unsubscribe endpoint and this set them all to false.  Have to hand this back over, not sure where to go from here as I don't see an issue with the endpoint.

**Comment by jonathanihm** [comment]
The last find() was ran right after I called the unsubscribe endpoint

**Comment by BerkeleyTrue** [comment]
@jonathanihm Thanks for verifying. 

@QuincyLarson Looks like this is reported in error. Happy Coding
