### ISSUE TITLE
While 'private browsing' - no code samples in Beta

### ISSUE THREAD

**Issue by cristianvnica** [FreeCodeCamp/FreeCodeCamp#1561]
When I am trying to navigate through out the challenges in a private session using Safari, I cannot see any code sample: 
<img width="1124" alt="screen shot 2015-08-05 at 5 45 56 pm" src="https://cloud.githubusercontent.com/assets/3229023/9088951/67eed930-3b9b-11e5-91c6-2ef3a2523ba2.png">
<img width="1127" alt="screen shot 2015-08-05 at 5 48 31 pm" src="https://cloud.githubusercontent.com/assets/3229023/9088959/6e5e9f8a-3b9b-11e5-8975-c2426f5c187f.png">
<img width="1123" alt="screen shot 2015-08-05 at 5 52 45 pm" src="https://cloud.githubusercontent.com/assets/3229023/9088962/7200ab6a-3b9b-11e5-9d92-0b22670e7eab.png">

**Comment by benmcmahon100** [comment]
Hi @cristianvnica safari has a lot of problems. One of which is that it doesn't like our web workers which give the effect of multi-threading can you attach a screen shot of your web console? I think it'll have something to the effect of a blob being undefined.

**Comment by benmcmahon100** [comment]
It is also possibly cause by safari blocking access to/from web-storage. Something again that our editor relies on

**Comment by cristianvnica** [comment]
<img width="1140" alt="screen shot 2015-08-05 at 6 18 11 pm" src="https://cloud.githubusercontent.com/assets/3229023/9089560/64a5ef86-3b9e-11e5-9be1-a624b546aa85.png">

**Comment by benmcmahon100** [comment]
Okay the private browsing is stopping the web-storage
