### ISSUE TITLE
French translation of 01-responsive-web-design/

### ISSUE THREAD

**Issue by Darkpingouin** [freeCodeCamp/freeCodeCamp#15612]
#### Challenge Name

All challenges in 01-responsive-web-design section

#### Issue Description

I am willing to do the french translation for this challenges but I need more information on how to do it correctly, is there any template I need to follow ??

**Comment by gmfvpereira** [comment]
Hi @Darkpingouin, have you seen this: https://forum.freecodecamp.org/t/guidelines-for-translating-free-code-camp-to-any-language/19111

**Comment by raisedadead** [comment]
Hi @Darkpingouin 

Thanks for your interest in contributing to the translation effort:

Please check if there is no pre-existing issue on our https://github.com/freeCodeCamp/TranlationExpansion repo.

And then proceed with the guidelines as suggested by @gmfvpereira !

Happ translating!
