### ISSUE TITLE
Wrong description:

### ISSUE THREAD

**Issue by prateekgoel** [freeCodeCamp/freeCodeCamp#15611]
#### Basic JavaScript: Logical Order in If Else Statements

http://beta.freecodecamp.com/en/challenges/basic-javascript/logical-order-in-if-else-statements

#### Incorrect desciption
if..else is a statement and not a loop. I think it would be incorrect to describe it as loop.
Share your thoughts on this.
I am willing to work on this.

**Comment by pepperyspray** [comment]
If you are referring to this part: "the loop is executed from top to bottom...", then I think in that context the word "loop" is used correctly, since we're looping until we get to "10". The word "statement" is used in other parts of the challenge correctly.

**Comment by shubhshrma** [comment]
Hi.
I think the word "loop" is erroneously used instead of the word "function" here because all the if and if else statements are inside a function and there is no iteration here.

**Comment by pepperyspray** [comment]
I didn't look at the code closely enough the first time -- you're right, there's no looping! "Function" would be a good replacement.

**Comment by erictleung** [comment]
Thanks, everyone. Yes, it does seem that the text is incorrectly mentioning loops. The correct terminology should be "function".

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/Contributors) chat room if you have any questions about helping. We're there to help.

**Comment by shubhshrma** [comment]
Thanks, I will make a PR soon enough.

**Comment by Logan1x** [comment]
@shubhshrma  you should close this issue now.

**Comment by usmandap** [comment]
#15650

**Comment by usmandap** [comment]
#15650
