### ISSUE TITLE
issue found inspite the right code (target even number elements using jQuery)

### ISSUE THREAD

**Issue by Karthikregs** [freeCodeCamp/freeCodeCamp#15610]
![untitled](https://user-images.githubusercontent.com/30015751/27991725-9dc6e368-649d-11e7-85fa-f15a742c3ef2.jpg)
please find if something is wrong and help me out!

**Comment by Karthikregs** [comment]
i guess there is a bug that is the reason why iam not able to get the soln.

**Comment by sonimadhuri** [comment]
@Karthikregs there isnt any bug in the challenge .it is only that you had added `bounce` class instead of `shake` while targetting  even number eleemnts`.target:even` .check your last line
