### ISSUE TITLE
Display meaningful placeholder usernames in for new signups

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#15625]
Currently, the uuid has gotten very long. It's not a friendly identifier for users when they haven't yet linked a GitHub account.

![image](https://user-images.githubusercontent.com/1884376/28053337-80966dae-662d-11e7-9750-47e2335773c2.png)

~~We should rather display an email associated here as a place holder.~~ We should not display email.

We should have something meaningful and memorable.
Note: This DOES NOT mean we are changing the user id. This issue is just about the display fields on the rendered page.

**Comment by raisedadead** [comment]
On that note, this would be a huge privacy concern, so I recommend that profiles be made private by default?

**Comment by BerkeleyTrue** [comment]
I don't think we should display user email address. We should also not have accounts private by default.

I'd be ok to have replace anon usernames with `Anonymous user` or `Unauthenticated User` of something along these lines.

**Comment by QuincyLarson** [comment]
@raisedadead We should never make user emails public anywhere in the app. Someone will scrape them all then start spamming people. Why not the user ID so long? Why not just use the system we use in production of fcc + an 8 character hex?

**Comment by raisedadead** [comment]
@BerkeleyTrue Totally agree I realized the same as soon as I opened the issue.

> I'd be ok to have replace anon usernames with Anonymous user or Unauthenticated User of something along these lines.

How about something like generating two random memorable strings and a couple of no.s like, heroku, Glitch etc. do for app names:

`blue-unicorn-2358` or `red-dragon-7456` etc.

I am sure there are packages out there, which will do that.

> Why not just use the system we use in production of fcc + an 8 character hex?

I am not sure why we moved from that, but its worth noting that old convention is not very friendly either.

In any case, I completely agree that using email is a bad idea. I will update the issue OP and title.

**Comment by BerkeleyTrue** [comment]
I don't think we should invest to much effort into this. Linking with github is the simplest way around this issue and we already do this.

**Comment by raisedadead** [comment]
Yes, I agree this is the least of the concerns at the moment. 

The only point being since some of the users may not choose to link GitHub as soon as they join, it's a bit of a not so nice UX to interact socially say forums and chat without a memorable username so to speak.

Nevertheless, we can keep this for later. Surely not a priority.

**Comment by QuincyLarson** [comment]
I agree with @BerkeleyTrue think the benefits from encouraging campers to link GitHub outweigh the costs (especially considering this is completely optional). 

We should go back to the short usernames we're using in production though, instead of these ridiculously long UUIDs. @raisedadead Would you be interested in fixing this on staging?

**Comment by raisedadead** [comment]
@QuincyLarson yup, why not. But I will want to hold on till we merge passwordless and I believe that's going to take a day or so.

**Comment by BerkeleyTrue** [comment]
@QuincyLarson and @raisedadead this was an intentional change to avoid duplicate usernames.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue @raisedadead We could use a 16 character hex. With that, we could create more than 600,000,000 accounts before we had even a 1% chance of a namespace collision occurring.

https://en.wikipedia.org/wiki/Birthday_problem#Probability_table

If we choose to continue to use the 32-character hex we're using now, we should remove the dashes, as they make it harder to double click to select the username.

**Comment by jmetev1** [comment]
I was going to report an issue of my username appearing as uuid but i guess that's known and intended. Sure looks like a bug though. Maybe we could consider changing language from `Account settings for uuid` to Account settings for jmetevier@gmail.com` ? 
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/20405975/1922f685-c3b7-42ea-933d-29de46af3798)
