### ISSUE TITLE
Use Bracket Notation to Find the Nth... on Beta

### ISSUE THREAD

**Issue by cristianvnica** [FreeCodeCamp/freecodecamp#1562]
Challenge http://beta.freecodecamp.com/challenges/use-bracket-notation-to-find-the-nth-to-last-character-in-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

There is a mistake in the code sample: 
```
It should be: var thirdToLastLetterOfFirstName = firstName[firstName.length - 3];
but is: var thirdToLastLetterOfFirstName = firstName[firstName.length - 2];

```
<img width="1144" alt="screen shot 2015-08-05 at 6 09 45 pm" src="https://cloud.githubusercontent.com/assets/3229023/9089469/e8d657e2-3b9d-11e5-8689-750ffd556301.png">

**Comment by cristianvnica** [comment]
I've tried to fix this myself, but i don't know how it went. I am beginner with github. @benmcmahon100 please mention if I done something wrong.

**Comment by benmcmahon100** [comment]
No this was perfect! One tip is to always check your JSON here http://jsonlint.com/ and if you start making more serious changes or more complex fixes you should get a local cop of FCC going by cloning the repo and make sure everything works!
