### ISSUE TITLE
beta HTML does not preload for any challenge

### ISSUE THREAD

**Issue by tehDrew** [freeCodeCamp/freeCodeCamp#15620]
#### Challenge Name
All challenges on the beta site I've encountered thus far (I'm up to #106).

Name of current challenge is "Applied Visual Design: Use the CSS Transform scale Property to Change the Size of an Element" but like I said, applies to all on beta. subdomain.

#### Issue Description

Every time I progress to the next challenge, the challenge's HTML is NOT preloaded - I have to click on "Reset

" for the challenge's HTML to show up on the right hand side (previous to any changes for the challenge, I mean).

#### Browser Information

* Browser Name, Version: Chrome, version 59.0.3071.115 (Official Build) (64-bit)
* Operating System: Windows 8.1
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

Before I hit "Reset"
![beta-site-html-not-loading-issue](https://user-images.githubusercontent.com/6607799/28024003-22e1937e-6555-11e7-823f-12b4a18a5cf1.jpg)
After I hit "Reset"
![screenshot of applied visual design- use the css transform scale property to change the size of an element - freecodecamp](https://user-images.githubusercontent.com/6607799/28024183-90f2623a-6555-11e7-9862-1e6331da48d1.jpg)

**Comment by jimtryon** [comment]
Why did you close the issue? It still is not loading any of the HTML on the right side

**Comment by tehDrew** [comment]
Meant to reopen it; the "beta" tag wouldn't stick for some reason (on my
phone).

On Jul 17, 2017 5:38 AM, "Jim Tryon" <notifications@github.com> wrote:

Why did you close the issue? It still is not loading any of the HTML on the
right side

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/15620#issuecomment-315720204>,
or mute the thread

**Comment by isehrob** [comment]
Hi all! I'm working on this issue.

**Comment by tehDrew** [comment]
Thanks, Sehrob!
