### ISSUE TITLE
Add "Help" buttons to forum navigation

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15636]
The forum is a great place to get near real-time help. The operative word here being "near". In practice, it takes 1 to 5 hours to get a response, which isn't fast enough for many people.

![admin_-_freecodecamp_forum](https://user-images.githubusercontent.com/985197/28133377-6bc7393e-6705-11e7-9390-34cf28a0f596.png)

The good news is we can significantly accelerate that process. We may be able to get the wait time for a response down to a few minutes.

We can do this by making it easier to browse posts that haven't yet been replied to (a vast majority of posts on the forum are either questions or requests for project feedback).

I think we should add two buttons to the forum navigation:

![](https://www.evernote.com/l/Ar_TaYM8kE1ONZ_J5Jxs8EG2Hx4ec4Jcs7oB/image.png)

[Answer Questions](https://forum.freecodecamp.org/?max_posts=1)

and

[Give Project Feedback](https://forum.freecodecamp.org/c/project-feedback?max_posts=1)

These could probably replace New and Unread which at the volume of posts we have aren't very useful. 

[Here is my discussion with Discourse](https://meta.discourse.org/t/whats-the-simplest-way-to-add-a-new-navigation-menu-item/65909)

And [here are the instructions they recommended we follow](https://meta.discourse.org/t/adding-unsolved-button-to-top-menu-using-custom-html/59758?source_topic_id=65909)

Would anyone be interested in trying to get this working?

**Comment by nsuchy** [comment]
I think that adding an "Answer Questions" and "Give Project Feedback" buttons would be a good idea. You shouldn't have to wait 5 hours for a response, when you just want to keep coding and our stuck and can't get help quickly it can be frustrated. Clearly defining those buttons would be a good idea so people who want to help are more able to understand it.

**Comment by raisedadead** [comment]
Incorrect repo, I am keeping this open with comments disabled, please visit the correct issue linked above and continue.

**Comment by QuincyLarson** [comment]
@raisedadead @nsuchy I think we should first rely on the freecodecamp.org/contribute page directing people to these categories ("project feedback" and "help") instead of putting them in the navigation.
