### ISSUE TITLE
Change mention of "operator" to "notation" in Object Access

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/freeCodeCamp#15646]
#### Challenge Name

https://www.freecodecamp.org/challenges/accessing-objects-properties-with-the-dot-operator

#### Issue Description

[Quoted](https://github.com/freeCodeCamp/freeCodeCamp/issues/6298#issuecomment-315369258) from @4mifix (bolded text was added for emphasis)

> The issue with this challenge is the Operator wording, **in Java most people know the word dot operator and in Javascript we use dot notation**. Basically the same thing but in this challenge for a beginner programmer the semantics can be confusing. With a little research and reading the difference becomes clear. I was confused about both until I did the research. .**Operator and .Notation slight difference but the challenge is about accessing Objects.** Dot operator originated in Java.

[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_Accessors) also uses the terminology of "dot notation", rather than "dot operator".

There is a nuance between the two, operator and notation, but I think for future use, it is an improvement. But as it was pointed out earlier, experienced programmers may be confused for a little bit when reading about this initially.

### Proposed Change

Change mentions of "dot operator" to "dot notation".

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: macOS
* Mobile, Desktop, or Tablet: Laptop

**Comment by dhcodes** [comment]
I'm in favor of this change.

**Comment by Bouzmine** [comment]
Can I submit a PR with those changes?

**Comment by erictleung** [comment]
@Bouzmine sorry for the late reply, but yes, go for it! Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/HelpContributors) chat room if you have any questions about helping. We're there to help.
