### ISSUE TITLE
What is the Problem in my c# code?

### ISSUE THREAD

**Issue by adrishnaskar** [freeCodeCamp/freeCodeCamp#15642]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PracticeDicisionMaking
{
    class Program
    {
        static void Main(string[] args)
        {
            //I am here printing that this is my favourite Game
            //I am here asking the user to choose one door
            Console.WriteLine("My Favourite Game");
            Console.Write("Chose a door: 1,2 or 3: ");
            //Now I am Getting that what the user is typing
            string userValue = Console.ReadLine();

            if (userValue == "1")
            {
                Console.WriteLine("Excelent!!!");
            }
            else if (userValue == "2")
            {
                Console.WriteLine("Very Good!!");
            }
            else if (userValue == "3")
            {
                Console.WriteLine("Good!");
            }
            else
            {
                Console.WriteLine("You are a bad boy!");
            }
        }
}

**Comment by raisedadead** [comment]
Hi @adrishnaskar  

Thanks for reporting this issue. 

Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
