### ISSUE TITLE
`box-sizing` for adding border css challenge

### ISSUE THREAD

**Issue by lionel-rowe** [freeCodeCamp/freeCodeCamp#15644]
#### Challenge Name

Live:
https://www.freecodecamp.org/challenges/add-borders-around-your-elements
Corresponding beta challenge:
https://beta.freecodecamp.com/en/challenges/basic-css/add-borders-around-your-elements

#### Issue Description

At least in the live version, all the "kitty app" stuff uses bootstrap, which sets `box-sizing` to `border-box` - this isn't explained, so could be confusing for newbies because the behavior is different from the standard (especially noticeable with huge 10px borders like in this challenge).

#### Browser Information

* Browser Name, Version: Chrome 55.0.2883.87
* Operating System: Win 7
* Mobile, Desktop, or Tablet: Desktop

**Comment by 4mifix** [comment]
This should is non issue basic CSS and Bootstrap with a addition of class like so

.thick-green-border {
    color: green;
    border-width: 10px;
    border-style: solid; 
  }

<a href="#"><img class="smaller-image **thick-green-border**" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>

**Comment by 4mifix** [comment]
This should is a non issue basic CSS and Bootstrap with a addition of class like so

**.thick-green-borde**r {
color: green;
border-width: 10px;
border-style: solid;
}

pay attention to the image class
img class="smaller-image **thick-green-border**"


I had some issues understanding how this works but once you get it. You get it.

**Comment by dhcodes** [comment]
Closing this for now. If more confusion crops up around this issue, then we'll reopen it. Thanks for your help too @4mifix
