### ISSUE TITLE
Updating the contributing instructions and general guidelines

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#15648]
We have a good contributing guide in place for this repository, but as noted in forums and chat room that's this is not enough as we get more and more people to contribute to the project.

I propose to streamline the instructions into sections, it's a good 15-20 minutes read right now, and I believe the instructions if followed word to word can be a bit daunting although it is very neatly worded.

I tried to do setup my self once again to get a feel of how it would be to new comers.

Please feel free to leave your questions and gotchas that the guide misses out on in the thread, we will try to look into it and update accordingly.

For now, I am considering to follow the twbs/bootstrap guide for inspiration.
/cc @freeCodeCamp/moderators

**Comment by yogaboll** [comment]
I just set up the project for the first time (Windows 10). The contributing guide tells you to run `mongo --version` to check your version of mongoDB and later run `mongod` to start the database. But these don't work in either git bash or cmd. You have to navigate to `/c/Program/MongoDB/Server/3.4/bin/mongo`
or something like that to run these commands.

Anyway, I got it working but maybe this should be changed?

**Comment by vikramnr** [comment]
`mangoDb `setup is somewhat confusing for window and that is one place I got stuck and even still now also. May be few screen shoots will help.

**Comment by raisedadead** [comment]
@yogaboll @vikramnr yup, we need to keep the guide OS-agnostic but they will be (ad have been added as OS specific guides). Thanks, We'll take this into account.

**Comment by QuincyLarson** [comment]
@yogaboll Please take a look at https://forum.freecodecamp.org/t/how-to-clone-and-setup-the-free-code-camp-website-on-a-windows-pc/19366

How are these instructions? Feel free to update them.

**Comment by QuincyLarson** [comment]
@raisedadead Our CONTRIBUTING.md file is pretty clear, and I've even heard of other projects using it as an example. I don't think it's the limiting factor.

I think the real reason why we're not getting more contributions is because of the beta-production split. Once we resolve this, contributors will be able to more tangibly see their contributions.

**Comment by raisedadead** [comment]
I cannot deny that, of course. And I am just proposing to make it more streamlined, as in re-arranging the things in a more logical way. The content is good and will win solid points for that, but the verbiage and the consistency sure needs a slight update.

The guide assumes some of the caveats for a new contributor. Plus it needs an update anyway for our more standard patterns like the commit messages, also removing things about editing via GitHub interface which has come to that fact almost all of the Pull requests coming from that path get rejected.

Nevertheless, I'll make a pull request. I urge you to take a look and feel free to comment and guide on improvements.

**Comment by QuincyLarson** [comment]
@raisedadead Awesome - sounds good :) I'm looking forward to seeing your suggested improvements.

**Comment by yogaboll** [comment]
@QuincyLarson I used those instructions when I did the set up and they're fine. I did get confused though, because https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#setup-freecodecamp has basicly the same instructions, except with mongo-commands that don't work on Windows.

**Comment by QuincyLarson** [comment]
@yogaboll We may just want to update the CONTRIBUTING.md to include Windows-specific Mongo commands as well. That way everything's all in the same document. This would reduce confusion. Would you be interested in updating the CONTRIBUTING.md file and opening a pull request? You could mark it as closing this issue.

**Comment by yogaboll** [comment]
I'll give ut a shot tomorrow

**Comment by QuincyLarson** [comment]
@yogaboll OK - sounds good. Thanks for keeping us posted on this :)
