### ISSUE TITLE
JavaScript Syntax check error

### ISSUE THREAD

**Issue by aviral1701** [freeCodeCamp/freeCodeCamp#15640]
Whenever one writes code in the Editor, it **starts checking it and shows the red error mark even before that line of code is complete**.So this results in a irritating red mark.

**So is this intentional?**

If not , Can I take the liberty of fixing it?

**Comment by raisedadead** [comment]
Hi @aviral1701 

Thanks a lot for reporting.

Well, unless we can propose to cleverly guess when the code is actually ready before parsing for the check, I would consider this to be a bikeshedding issue.

Nevertheless, it's the standard code mirror config that we use.

Please feel free to take a look, and suggest alternatives though. We would definitely consider if it will not introduce a bug.

**Comment by erictleung** [comment]
@aviral1701 I would agree with @raisedadead. I want to say this editor UX behavior is fairly standard so it is something I've gotten used to as well. You could propose some feature where you can turn that feature off. However, given the current demands of the freeCodecamp team, that kind of feature would be fairly low priority. So again, if you can propose a solution, I think the community would be open to it 👍

**Comment by raisedadead** [comment]
Thanks, @erictleung and @aviral1701 
I am closing this for now, but please feel free to continue on this thread with your suggestions.
