### ISSUE TITLE
Understanding Uninitialized Variables | Allows you to edit variable directly below allowed edits line.

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/freeCodeCamp#15657]
#### Challenge Name
Understanding Uninitialized Variables

#### Issue Description
The challenge allows me to skirt actually solving the challenge and edit the variable directly. This defeats the purpose of the challenge and should be updated as appropriate.  You should only be allowed to edit above the line otherwise a user may pass the challenge without understanding the actual concept.

#### Attribution
The user 'sonimadhuri' on Gitter pointed out this issue to me.

#### Browser Information

* Browser Name, Version: Google Chrome
* Operating System: macOS
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
```
// Initialize these three variables
var a;
var b;
var c;

// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";

var a = 6;
var b = 15;
var c = 'I am a String!';

```

#### Screenshot

<img width="1280" alt="screen shot 2017-07-16 at 10 45 20 am" src="https://user-images.githubusercontent.com/8227641/28248554-661e63ec-6a14-11e7-8d98-7a68981730c5.png">

**Comment by edgevoid** [comment]
Hi there , please excuse me if i am wrong. We can initialize the variable as below for the the above output 

a = 5 ;
b =10 ;
c = 'I am a';

**Comment by dhcodes** [comment]
Thanks for the issue @nsuchy. There is a test that ensures the code is not changed. There's not really a way to "lock" other code from being able to be entered below the line. Closing as `wontfix` for now. Will reopen if this becomes a source of confusion.
