### ISSUE TITLE
[FCC Beta] Test suite failing on SASS Challenge (Use @each to Map Over Items in a List)

### ISSUE THREAD

**Issue by mobesa** [freeCodeCamp/freeCodeCamp#15659]
#### Challenge Name
[Sass: Use @each to Map Over Items in a List](https://beta.freecodecamp.com/en/challenges/sass/use-each-to-map-over-items-in-a-list)

#### Issue Description
The test suite for this challenge should verify that:

- the `.blue-bg` class should have a `background-color` of blue,
- the `.black-bg` class should have a `background-color` of black,
- and the `.red-bg` class should have a `background-color` of red.

However, according to the 'pretty-fied' version of the test suite (extracted from the script in the html code of the webpage) of the challenge, it seems that it's testing for the `background-color` of the elements with the tags `<blue-bg>`, `<black-bg>` and `<red-bg>`. See for yourself:

```
"tests": [
  "assert(code.match(@each, 'message: Your code should use the @each code directive.');",
  "assert($('blue-bg').css('background-color') == 'rgb(0, 0, 255)', 'message: Your .blue-bg class should have a background-color of blue.');",
  "assert($('black-bg').css('background-color') == 'rgb(0, 0, 0)', 'message: Your .black-bg class should have a background-color of black.');",
  "assert($('red-bg').css('background-color') == 'rgb(255, 0, 0)', 'message: Your .red-bg class should have a background-color of red.');"
]
```
As you can see, the line `assert($('blue-bg').css('background-color') == 'rgb(0, 0, 255)` looks for html elements with the tag `<blue-bg>` and not the class name `.blue-bg`.

#### Browser Information
Chromium x86, Ubuntu 16.04

#### What I did to the cheat the test suites
Here's the code I submitted to trick 'em:
```
<style>

/* This would have worked if the SASS compiler on FCC worked  :/ */
@each $color in blue, black, red {
    .#{$color}-bg { background-color: $color; }
  }
  
  /* Normally, the following hardcoded CSS code would have worked, unfortunately, the test suites are wrongly put together (they reference the blue-bg, black-bg and red-bg elements instead of the .blue-bg, .black-bg and .red-bg classes)... Oh well...
  .blue-bg {
    background-color: blue;
  }

  .black-bg {
    background-color: black;
  }

  .red-bg {
    background-color: red;
  }
  */

/*Test suite workaround... silly... */

  blue-bg {
    background-color: blue;
  }
  
  black-bg {
    background-color: black;
  }
  
  red-bg {
    background-color: red;
  }
  
  div {
    height: 200px;
    width: 200px;
  }
</style>

<div class="blue-bg"></div>
<div class="black-bg"></div>
<div class="red-bg"></div>
<blue-bg></blue-bg>
<black-bg></black-bg>
<red-bg></red-bg>
```
I shamelessly inserted tags that don't exist just to pass the test!!!

**Comment by mobesa** [comment]
I also have to mention that the SASS code I submit doesn't work (ie doesn't compile into the CSS)... But that's whole other issue...

**Comment by knight2** [comment]
@mobesa I also experienced this issue.

Problem is with SASS not working on FCC.
