### ISSUE TITLE
Find longest word in a string function naming

### ISSUE THREAD

**Issue by d33con** [freeCodeCamp/freeCodeCamp#15652]
#### Find the Longest Word in a String

https://beta.freecodecamp.com/en/challenges/basic-algorithm-scripting/find-the-longest-word-in-a-string

#### Issue Description
The function name `findLongestWord` is a little misleading as the challenge asks to return the length of the word not the word itself. How about `findLongestWordLength` instead?

**Comment by vikramnr** [comment]
Were you able to complete the challenge?

**Comment by usmandap** [comment]
@d33con Yes he is right function name should be  findLongestWordLength() instead of findLongestWord(). Let me know if I can fix this issue I am a new contributor just started open source developement.

**Comment by d33con** [comment]
No bug, it doesn't affect the completion of the challenge. It's purely for clarity. I was going to suggest fixing as I too am looking for something like this as I've never contributed before but if @usmandap has called first then I don't mind.

**Comment by prateekgoel** [comment]
Are you working on this @usmandap ?
If not, I would like to work on this.

**Comment by usmandap** [comment]
@prateekgoel I have to work on it but no one updated me yet. I can fix it as it will be my first open source contribution but I am waiting for an approval. Since @d33con has reported this issue so I am waiting if he is going to fix it or let me give a chance to submit my first contribution.

**Comment by prateekgoel** [comment]
@usmandap He already confirmed in his last comment.

**Comment by d33con** [comment]
@usmandap , @prateekgoel Sorry for any confusion, I thought a person from fCC was going to come in and assign it or something. I'll start working on it this weekend.

**Comment by usmandap** [comment]
@d33con Sounds good.. 👍

**Comment by d33con** [comment]
Hey @usmandap. You can do this if you want. I've tried and I'm having problems with node errors when running the tests. I've asked for help in the chat twice and re-installed the repo & dependencies sveral times but I'm getting the same thing. It's not worth the time anymore just to change one word. I hope you have better luck than me!

**Comment by usmandap** [comment]
@d33con Thanks bro and sure I will give it a try.

**Comment by usmandap** [comment]
#15744

**Comment by usmandap** [comment]
#15744
