### ISSUE TITLE
Loop Protect Error-Finding length of the word in the string

### ISSUE THREAD

**Issue by vikramnr** [freeCodeCamp/freeCodeCamp#15651]
#### Challenge Name
[Find the Longest Word in a String](http://beta.freecodecamp.com/en/challenges/basic-algorithm-scripting/find-the-longest-word-in-a-string) has an issue.
#### Browser Information

User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0</code>.

#### Your Code
```js

function findLongestWord(str) {
  str=str.split(' ');
  var lenlt=0;
  var temp;
  for(var i=0;i<str.length;i++){
    
    temp=str[i].length;
    if(temp>lenlt){
      lenlt=temp;
    }else{
      lenlt=lenlt;
    }
  }
  return lenlt;
}

findLongestWord("The quick brown fox jumped over the lazy dog");
//console.log(lt);
```

![image](https://user-images.githubusercontent.com/8538409/28239488-d0902286-698a-11e7-84fa-720c4ae1f0cc.png)

The above code works fine in Live site with out any issues.

**Comment by anku255** [comment]
@vikramnr I copy and pasted your code in beta site and your code passed all of the tests. Can you please check again?
![image](https://user-images.githubusercontent.com/22813027/28249623-c4fad410-6a76-11e7-9008-d5abedf02284.png)

Also I would like to suggest a minor improvement in your code. You don't really need the "else" part.  You can remove the else block and it will still pass all the tests.

```
function findLongestWord(str) {
  str=str.split(' ');
  var lenlt=0;
  var temp;
  for(var i=0;i<str.length;i++){
    
    temp=str[i].length;
    if(temp>lenlt){
      lenlt=temp;
    }
  }
  return lenlt;
}

findLongestWord("The quick brown fox jumped over the lazy dog");
```

**Comment by vikramnr** [comment]
@anku255  Yes its passing the test now. Thanks for the suggestion.  But how is possible. Is it browser refresh/cache  stored .?
