### ISSUE TITLE
Accessibility: Please add main landmark to indicate where main content starts  exercise screens for more efficient Navigation

### ISSUE THREAD

**Issue by jhomme** [freeCodeCamp/freeCodeCamp#15658]
#### Issue Description

Using any screen reader, go to an exercise screen and navigate by landmark. There is no main landmark, so that the user can skim over the top portions of pages to get to the top of the exercise content quickly.

In Windows, using NVDA, use D to navigate downward and SHIFT+D to navigate upward..

On Mac, using VoiceOver, when on web content, use Option+CTRL+U to access  the rotor, use Left and Right Arrows to choose Landmark, and choose Up and Down arrows to navigate.

This symptom is also present in other screen readers. 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by axtscz** [comment]
So basically you would like a `role="main"` to be added on the relevant tag on exercise screens?

**Comment by jhomme** [comment]
Hi,
Yes, please. Either that, or use the <main> tag instead of the wrapper div, assuming there is one around the body.

Thanks.

Jim


On Jul 25, 2017, at 7:22 PM, Alexander Cruz <notifications@github.com> wrote:

So basically you would like a role="main" to be added on the relevant tag on exercise screens?

**Comment by axtscz** [comment]
I'll look into this and try to submit a pull request

**Comment by dhcodes** [comment]
@axtscz how's this coming?

**Comment by xnt** [comment]
@axtscz @dhcodes are you fixing this? Otherwise I'd like to try.

**Comment by axtscz** [comment]
Yeah, go ahead and try. I had some things come up and can't get to it right
now. Let me know if you want help though.

**Comment by xnt** [comment]
Awesome! I'm on it. Thanks!
