### ISSUE TITLE
Can't log in all my progress since isn't showing

### ISSUE THREAD

**Issue by KamonLeigh** [freeCodeCamp/freeCodeCamp#15656]
I was reviewing my javascript and then I received a pop to sign in. I then proceeded then I was asked look in and I was refused. When I tried log in it refused my user name KamonLeigh. I then went reset my password. Followed the link and logged and now all my work is gone and now I have a new profile. This is frustrating as just done exercises in the Basic Algorithm. When I go on web page which had my profile it now shows user name fcce34c437e and now KamonLeigh is showing zero done. I have been doing this June there is no way I am doing this again as I have spent hours. This needs to be sorted out.  

```
#### Screenshot
<!-- Add a screenshot of your issue -->

**Comment by erictleung** [comment]
@KamonLeigh thanks for the issue. Sorry to hear you're having account issues. I'd email team@freecodecamp.com to hopefully get a solution.

cc/ @QuincyLarson

**Comment by BerkeleyTrue** [comment]
Please email team@freecodecamp.com and we will see what we can do. 

Happy Coding
