### ISSUE TITLE
ES6: Set Default Parameters for Your Functions - console.log() fix

### ISSUE THREAD

**Issue by cowCrazy** [freeCodeCamp/freeCodeCamp#15654]
#### Challenge Name
[ES6: Set Default Parameters for Your Functions](http://beta.freecodecamp.com/en/challenges/es6/set-default-parameters-for-your-functions)

#### Issue Description
It is confusing that showing `console.log(increment(5)); // returns NaN` although it shouldn't be NaN, it should simply return `number + 1`, in this case 6.

#### Browser Information

* Chrome 59.0.3071.115 (Official Build) (64-bit)
* Win 7 64-bit

#### Code
```js

function increment(number, value = 1) {
    return number + value;
}
console.log(increment(5, 2)); // returns 7
console.log(increment(5)); // returns NaN


```

**Comment by Manish-Giri** [comment]
@cowCrazy There's nothing wrong here. With the default challenge seed code, if there is no default value assigned to the parameter `value`, it remains `undefined`, and adding to it will result in `NaN`. See screenshot - 

![screenshot 2017-07-23 02 26 44](https://user-images.githubusercontent.com/11348778/28497168-ce67d76e-6f4e-11e7-9749-d4cd4f2bb071.png)

Once you make the change required in the challenge, `value = 1`, it won't return `NaN`.

**Comment by cowCrazy** [comment]
@Manish-Giri OK, I see what you mean.

**Comment by fotisoikonomou** [comment]
const increment = (function() {
  "use strict";
  return function increment(number,value=1) {
   switch(value) {
   case isNaN(value) :
     return number +value;
     break;
   case value  : 
   return number+value;
   break;
   default : return NaN;}
  };
})();
console.log(increment(5, 2)); // returns 7
console.log(increment(5)); // returns NaN
