### ISSUE TITLE
Bug on forum.freecodecamp.org

### ISSUE THREAD

**Issue by username1001** [freeCodeCamp/freeCodeCamp#15653]
Not exactly sure if this is the correct place to post, but I've noticed a bug on the forum website. 

Issue: 
While looking through a thread, I wanted to follow the conversation, so I clicked the "reply" to see who replied, and what they said. Previously, it indeed showed the replies. But on a specific post, with each "reply" clicked, it just added the content again, on the page. So basically, with each new click, it's document.writing the post on the page(?). I'm not sure if this is a consistent thing, but I imagine it to be.

My environment: 
Browser: Chromium Version 59.0.3071.109 (Developer Build) 
OS: Ubuntu 16.04 (64-bit)

![bug1](https://user-images.githubusercontent.com/11285175/28244149-6b897394-69b0-11e7-9185-ed036caa339b.png)

Thread:
https://forum.freecodecamp.org/t/why-do-so-many-devs-use-macs-for-laptop-choice/135958/55

**Comment by raisedadead** [comment]
Issue moved to [freeCodeCamp/discourse #41](https://github.com/freeCodeCamp/discourse/issues/41) via [**ZenHub**](https://www.zenhub.com/)
