### ISSUE TITLE
Return value calculates without argument

### ISSUE THREAD

**Issue by roborache** [freeCodeCamp/freeCodeCamp#15655]
#### Return a Value from a Function with Return

https://www.freecodecamp.org/challenges/return-a-value-from-a-function-with-return

#### Argument is taken wrong

The task was to create a function timesFive that accepts one argument, multiplies it by 5, and returns the new value.

But even tho I didn't write : 
function timesFive(num) {
  return num * 5;
}
timesFive(5);
-------------------------------------- 
it accepted the challange and let me pass . Here is the wrong code that also was accepted by freecodecamp : 

function timesFive(num) {
  return num * 5;
}
 And when even when i didnt wrote the functions argument or changed the number .
Without to initialize the "timesFive" to the value of "5" it calculated himself " 5 * 5 " somehow.
#### Browser Information

* Browser Name, Version: Version 59.0.3071.115 (Official Build) (64-Bit)
* Operating System: Windows 8.1
* Mobile, Desktop, or Tablet:  Laptop(Desktop)

#### Your Code

// Example
function minusSeven(num) {
  return num - 7;
}

// Only change code below this line

function timesFive(num) {
  return num * 5;
}
```js



```

**Comment by raisedadead** [comment]
Hi, this is okay and valid actually. Here is how the test cases work:

They look for the definition of the function in your code which you have correctly done and then they execute it in the background.

But that said this challenge needs to have an additional test to check for a function call as well to avoid this confusion.

**Comment by Manish-Giri** [comment]
I'll take this up.
