### ISSUE TITLE
Move Fahrenheit Variable Below Comment Line

### ISSUE THREAD

**Issue by andreagoulet** [freeCodeCamp/freeCodeCamp#15664]
#### Convert Celsius to Fahrenheit
https://www.freecodecamp.org/challenges/convert-celsius-to-fahrenheit

#### Issue Description
There's an inconsistency between the forum solution to this module and the needed solution. In order to get the tests to pass, you need to modify the Fahrenheit variable, but it's above the comment that says to only modify code below that comment. 

My proposed solution is to update the content on the exercise so the variable is below the comment, so it would appear like this: 

```
function convertToF(celsius) {
  // Only change code below this line
  
  var fahrenheit 
  
  // Only change code above this line
  return fahrenheit;
}

// Change the inputs below to test your code
convertToF(30);
function convertToF(celsius) {
  var fahrenheit = (celsius * 9/5) + 32;
  // Only change code below this line
  
  // Only change code above this line
  return fahrenheit;
}

// Change the inputs below to test your code
convertToF(30);
```

Here's a link to the solution in the forum so you can see the discrepency: https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-convert-celsius-to-fahrenheit/16806

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Mac OS Sierra
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
This is what I used to get the tests to pass. I had to modify ```var fahrenheit``` which is above the comment line. My sense is this is where a lot of the confusion from this exercise is coming from. 

```
function convertToF(celsius) {
  var fahrenheit = (celsius * 9/5) + 32;
  // Only change code below this line
  
  // Only change code above this line
  return fahrenheit;
}

// Change the inputs below to test your code
convertToF(30);
```
#### Screenshot

Notice how the comments between the exercise and the solution are not in the same place. This is what's creating the confusion because in order to solve the problem you need to modify the ```var``` that's above the comment in the exercise.  

<img width="748" alt="screen shot 2017-07-18 at 10 55 35 pm" src="https://user-images.githubusercontent.com/136095/28348710-5e9f2526-6c0c-11e7-810c-281100deff74.png">

<img width="842" alt="screen shot 2017-07-18 at 10 56 14 pm" src="https://user-images.githubusercontent.com/136095/28348714-625f61f8-6c0c-11e7-9c93-5f80d486e6a4.png">

**Comment by Marmiz** [comment]
I guess that the variable declaration at the top was placed there either to ease the testing or to help campers have a structure to start working with.

What probably many new coders don't consider is that the solution can simply be achieved by a basic value assign:
```js
var fahrenheit;
 // Only change code below this line
 fahrenheit = // my expression
 // Only change code above this line
 return fahrenheit;
```

Then again I've seen this confusion happening before so I guess we could consider re-write the seed code as you proposed to lead to less confusion.

----

*note* this challenge is not tested in strict mode so the following code pass:
```js
function convertToF(celsius) {
 fahrenheit =  //expression
 return fahrenheit;
}
```
maybe while we are at it we want to tackle it for better consistency?

**Comment by erictleung** [comment]
@andreagoulet thanks for the issue and feedback. 

I'm able to pass the challenge with all variations on how the equation is placed (with the initial `var fahrenheit`, with a `fahrenheit = ...` on another line, etc), so I'm not sure what bug there is from the challenge not working correctly.

I agree that the forum wiki and the challenge itself should be consistent :+1: 

We can make it cleaner on what the "Instructions" are for the challenge.

> To test your learning, you will create a solution "from scratch". Place your code between the indicated lines and it will be tested against multiple test cases.
>
> The algorithm to convert from Celsius to Fahrenheit is the temperature in Celsius times 9/5, plus 32.
>
> ### Instructions
>
> You are given a variable `celsius` representing a temperature in Celsius. Use the variable `fahrenheit` already defined and assign it the Fahrenheit temperature equivalent to the given Celsius temperature. Use the algorithm mentioned above to help convert the Celsius temperature to Fahrenheit.
>
> **Note**
> Don't worry too much about the function and return statements as they will be covered in future challenges. For now, only use operators that you have already learned.

**Comment by prateekgoel** [comment]
I agree with @erictleung . 
I would like to have a chance to work on this.
I am working on this and will submit a PR soon.
