### ISSUE TITLE
Google Analytics not tracking `www.freecodecamp.ORG`?

### ISSUE THREAD

**Issue by evaristoc** [freeCodeCamp/freeCodeCamp#15663]
It seems that Google Analytics is still tracking `www.freecodecamp.COM`.
![currentpropertysettingsga](https://user-images.githubusercontent.com/5592713/28308537-c5fdfa64-6ba6-11e7-8061-05b3c6ad95f5.png)

There is still substantial activity through the `*.com`  according to Google Analytics. Apparently Google Analytics is not registering information coming from `*.org`?

The reason why I think the `*.com` is still alive is because the removal of the MAP SECTION `/challenges/learn-how-freecodecamp-works` is still registering activity:

![learnhowfccworksrecentactivity](https://user-images.githubusercontent.com/5592713/28309257-2246d55a-6ba9-11e7-90fd-f838bc6e2f72.png)

Similarly I tried to find information about the `*.org` recent changes in the onboarding page and I couldn't find any.

Wondering how that can be?

It is possible that `www.freecodecamp.com` is redirecting to `www.freecodecamp.org` for some of the existing pages but it is still registered as `www.freecodecamp.com`. However it could be also that GA is missing all those redirects because they are not tracked.

Does anyone can advise about the date the change into `*.org` was implemented, so I can try to trace the effects using GA?

Although the correct way would be to merge both views at some point, I would advise to create a new tracking ID and a new view for `www.freecodecamp.ORG` temporarily instead of merging with `www.freecodecamp.COM` until we get some idea of why this is happening?

Hope this helps.

**Comment by QuincyLarson** [comment]
@raisedadead I've updated the default URL in Google Analytics to www.freecodecamp.org. It doesn't seem to have changed anything in the realtime stats. My understanding is that Google gets this information from the UA code, and the domain doesn't really matter.

I think some traffic is still going to www.freecodecamp.com - @BerkeleyTrue configured it to gradually shift traffic over to freecodecamp.org so it may take a few weeks for this to be fully resolved.

**Comment by raisedadead** [comment]
Perfect thanks @QuincyLarson !

**Comment by evaristoc** [comment]
@QuincyLarson @raisedadead 

Now I can see both - *.com and *.org - in the reports. I was expecting that but I was not sure, this is why asked for a test, but nice that resulted in what I wanted!

Thanks for dealing with my request.!
