### ISSUE TITLE
MS Edge browser support

### ISSUE THREAD

**Issue by Koriban** [FreeCodeCamp/freecodecamp#1566]
moving from Waypoint: Mobile Responsive Images to Waypoint: Center Text with Bootstrap
produces a 404 : We couldn't find a challenge with that name. Please double check the name.

![screenshot 2015-08-05 12 53 44](https://cloud.githubusercontent.com/assets/366218/9091978/60dbb020-3b71-11e5-9e83-96a769b9f5a5.png)

System Info:
Windows 10
Microsoft Edge

**Comment by benmcmahon100** [comment]
@Koriban Hey do you have any errors in your browser console?

**Comment by Koriban** [comment]
![screenshot 2015-08-05 13 51 32](https://cloud.githubusercontent.com/assets/366218/9093268/1b929c56-3b79-11e5-9900-ccd80dc54f37.png)

Here ya go :) ina  bit of a rush so just a screenie.

**Comment by benmcmahon100** [comment]
@Koriban It is as i feared. Edge has issues with web workers so you'll need to use another browser. Sorry about the inconvenience.

**Comment by BerkeleyTrue** [comment]
@benmcmahon100 Lets keep this issue open to track Edge compatibility. Not sure what can be done at this moment.

**Comment by BerkeleyTrue** [comment]
@benmcmahon100 Did you find any relevent articles on M$ Edge and web workers?

**Comment by benmcmahon100** [comment]
@BerkeleyTrue Here's the problem second table -> http://caniuse.com/#search=web%20workers

**Comment by BerkeleyTrue** [comment]
I see shared webworkers are not working, is that the issue?

**Comment by benmcmahon100** [comment]
It says it's a security issue which suggests that we are using a shared one.

**Comment by benmcmahon100** [comment]
Yeah we have a shared one. The fix is to create a web worker for each script if the user is on edge

**Comment by BerkeleyTrue** [comment]
Alright, we'll put this on the back burner for now. We won't fix this for now. Hopefully when bonfires gets rewritten it will fix this issue but that won't happen for a while

**Comment by benmcmahon100** [comment]
Yeah I'm also curious to see if multi-web workers craps out performance or if Edge will add support for shared workers

**Comment by BerkeleyTrue** [comment]
Well they're supposed to be on the Edge, right? BTW I found out today Edge has target adds built into the browser. Thats M$ for ya!

**Comment by benmcmahon100** [comment]
Nah that's an optional built into bing. To be fair you can see the issue with shared web workers but I'd be surprised if they didn't release a build that allows them and just does a job of making them safe as opposed to assuming they're not. There's an "Open this in IE" button in Edge which should be offered as the immediate solution to all Edge-related issues

**Comment by benmcmahon100** [comment]
@BerkeleyTrue Looking at the table i think this may be worth moving up the priority queue as it will fix almost all the mobile issues in one go. The only browser that wouldn't benefit from using non-shared web workers would be Opera. So all browsers would work with executing the bonfires
