### ISSUE TITLE
Beta - Test Case Broken - Sass: Use @for to Create a Sass Loop 

### ISSUE THREAD

**Issue by knight2** [freeCodeCamp/freeCodeCamp#15662]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/sass/use-for-to-create-a-sass-loop?

#### Issue Description

The test case for this challenge is broken. 

SASS does not appear to be working for the in browser editor, as hitting submit doesn't properly show the SASS changes.

Using an editor like codepen that has sass configured will show that the code does what is instructed.

FCC says it fails these tests, but the code is correct, FCC is wrong.
Your .text-1 class should have a font-size of 10px.
Your .text-2 class should have a font-size of 20px.
Your .text-3 class should have a font-size of 30px.
Your .text-4 class should have a font-size of 40px.
Your .text-5 class should have a font-size of 50px.

#### Browser Information

* Browser Name, Version:  Chrome
* Operating System:  Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```

<style>
  @for $j from 1 to 6{
    .text-#{$j} {font-size: 10px* $j};
  }
  
  
</style>

<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>

```
#### Screenshot

![fcc](https://user-images.githubusercontent.com/8440420/28289172-a41ee9fe-6b0f-11e7-99ff-10b5a1aeb567.PNG)

**Comment by tsss85** [comment]
I've the same problem !

**Comment by teedoot** [comment]
My code appears to be correct but can't seem to pass it either using "Through" or "To". I keep getting the following issues, anyone knows how to resolve it?

**Comment by danchann** [comment]
Having the same problem, it won't pass even with bluchill's suggestions.

**Comment by bluchill** [comment]
Hi danchann,

can I see your code?

**Comment by danchann** [comment]
`<style type='text/sass'>

@for $j from 1 to 6 {
  .text-#{$j} {font-size: 10px*$j;}
}
  
</style>

<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>`

**Comment by bluchill** [comment]
Sometimes even after deleting **all** the spaces (with mine I only had to delete spaces inside the curly braces) try and refresh the page a couple of times and most importantly you have to use "to" not "through" as they are asking you to do in the exercise. Eventhough the output is the same I find mine only passes with "to" - as long as you know the difference between the two.

**Comment by bluchill** [comment]
Yup your code looks fine to me, try even deleting the space after "font-size:"  before the 10px...and refresh the page.

**Comment by danchann** [comment]
![image](https://user-images.githubusercontent.com/3872230/40885340-f4a1957c-6756-11e8-8408-cae216468b4d.png)

Strange!

**Comment by bluchill** [comment]
Hmm that's wierd...I was about to ask you if your output is correct (as in the heading are getting bigger as the go down the list?).
But yours says only your first element is not conforming. Mine usually said all of them were not correct (as in they did not have the green ticks) - but my output was showing correctly what was required, so I just kept refreshing and deleting  spaces.

**Comment by bluchill** [comment]
danchann you also seem to have a inverted coma in front of your first style...hope it just made it here accidentally and it is not in your code.

**Comment by JQuinnie** [comment]
I had the same issue, took @bluchill advice (thanks!!) and removed spaces from code like below:

`  @for $j from 1 to 6 {
  .text-#{$j} {font-size:10px*$j;}
}`

Worked first thing I changed, then I went back and paste it but it didn't work, did a refresh to page and then it worked again. Definitely glitchy.

**Comment by OMahonyD** [comment]
Hmmm... also tried all formatting changes I could think of but no joy. A glitch I say!

**Comment by zlayabekrija** [comment]
Ok guys,
I tried on first and this challenge also and it worked.
What you need to do is to manually (hardcode) given parameters in classes.
Example:
else than using for loop,if you want to pass the test do following:
<p class="text-1" style="font-size:10px;">Hello</p>
This is passing 100%.

**Comment by zlayabekrija** [comment]
Ok guys,
I tried on first and this challenge also and it worked.
What you need to do is to manually (hardcode) given parameters in classes.
Example:
else than using for loop,if you want to pass the test do following:
`<p class="text-1" style="font-size:10px;">Hello</p>`
Hello
This is passing 100%.

**Comment by penggunaphp** [comment]
Try refresh page

**Comment by P1xt** [comment]
@QuincyLarson This is still an issue. The test is very sensitive to whitespace and formatting exactly as the instructions instruct doesn't work.

**Comment by QuincyLarson** [comment]
@P1xt Thanks for confirming this is still an issue. It sounds like

**Comment by P1xt** [comment]
@QuincyLarson Actually, there's a chance that this (along with a ton of other closed Sass issues) are related to 
https://github.com/freeCodeCamp/freeCodeCamp/issues/17570

It might be a platform issue, not a test case issue.

**Comment by npellow** [comment]
I've tried it with the normal whitespace; tried it without the added white space; tried clearing cache, resetting the code. The code works, just doesn't want to pass the tests. The first screenshot is in Chrome. I tried it on IE (second screenshot), and it wouldn't work either; it seemed to get stuck when I clicked Run the Tests.

![sassproblem2](https://user-images.githubusercontent.com/21061478/41500053-f8f31a72-7158-11e8-8fab-169f7e6f0ab4.JPG)

![sassproblem2-ie](https://user-images.githubusercontent.com/21061478/41500134-91cc3a7a-715a-11e8-8845-56a0cf71bd5d.JPG)

**Comment by Brainy0003** [comment]
click the submit button repeatedly if you are having this issue of submitting, it is a break in the progrm and not your fault if you have the following code you are definitely right:
 
  @for $j from 1 to 6 {
    .text-#{$j} { font-size: 10px * $j; }
  }
I hope this helps...

**Comment by mattszcz** [comment]
#12699 root issue

**Comment by tj3407** [comment]
white space around '$j' in '.text-#{ $j }' worked for me .. wouldn't pass it otherwise

**Comment by nurulilmaan** [comment]
<style type='text/sass'>
  @for $j from 1 to 6 {
    .text-#{ $j } { font-size: 10px * $j ; }
  }
</style>

<p class="text-1" style="font-size: 10px">Hello</p>
<p class="text-2" style="font-size: 20px">Hello</p>
<p class="text-3" style="font-size: 30px">Hello</p>
<p class="text-4" style="font-size: 40px">Hello</p>
<p class="text-5" style="font-size: 50px">Hello</p>

**Comment by nurulilmaan** [comment]
![image](https://user-images.githubusercontent.com/28183605/43874907-8551040a-9bb8-11e8-8ce1-28a53dc514b9.png)

**Comment by Sigurd-W23** [comment]
The following code works on **Firefox** only

```
<style type='text/sass'>
    @for $j from 1 to 6 {
        .text-#{ $j } { font-size: 10px * $j ; }
    }
</style>

<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>
```

**Comment by shtscompany** [comment]
<style type='text/sass'>
  
  @for $j from 1 to 6 {
    .text-#{$j} { font-size: 10px*$j; }
  }
.text-1{
  font-size: 10px;
}
.text-2 {
  font-size: 20px;
}
.text-3{
  font-size: 30px;
}
.text-4{
  font-size: 40px;
}
.text-5{
  font-size: 50px;
}
  
</style>

<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>

**Comment by shtscompany** [comment]
This is working 100%`

<style type='text/sass'>
  
  @for $j from 1 to 6 {
    .text-#{$j} { font-size: 10px*$j; }
  }
.text-1{
  font-size: 10px;
}
.text-2 {
  font-size: 20px;
}
.text-3{
  font-size: 30px;
}
.text-4{
  font-size: 40px;
}
.text-5{
  font-size: 50px;
}
  
</style>

```
<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>`
```

**Comment by Nirajn2311** [comment]
As this issue is solved, I am closing this issue.

If this was a mistake, please open the issue with a reason.

**Comment by mubarak23** [comment]
still getting the same error

**Comment by MysticBlaze085** [comment]
I am currently getting this error

**Comment by P1xt** [comment]
@Nirajn2311 this wasn't solved, the challenge is still broken in that following the instructions will not guide you to a correct solution. All of the 'solutions' you see above are workarounds that people came up with to get around how broken this challenge is.

**Comment by pathgeek** [comment]
@Nirajn2311  this isn't a solved issue.

**Comment by RandellDawson** [comment]
@pathgeek There is a fix, but it has not been deployed to production.  Once the master branch has been deployed, users will not experience this issue anymore.  We hope to have master ready to be to deployed in the near future.
