### ISSUE TITLE
"Ask for help" button that pre-populates forum post

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15669]
# User story
As a user, if I need help with a challenge, I can click a "Ask for help on the forum" button. A modal will pop up with the following text:

"If you've already tried [the Read-Search-Ask Method](https://forum.freecodecamp.org/t/the-read-search-ask-methodology-for-getting-unstuck/137307), then you can ask for help on the freeCodeCamp forum." [Create a help post on the forum]

A new tab will open with a prep-populated forum post with: 
- the the title of my current challenge in the subject line
- the post body, which includes this:

#### My code so far
*this should be automatically populated and formatted*

#### My browser information

User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36</code>.

# Discourse URL

Here's how to format a URL for creating a post on Discourse

`http://forum.freecodecamp.org/new-topic?title=**topic%20title**&body=**topic%20body**&category=help`

# UI element

Here's what the button should look like. This should be added to all views that have tests:

![](https://www.evernote.com/l/Ar8kFtBc42tICrz8ycUXkpCrIFT3Qak0mBoB/image.png)

**Comment by lricoy** [comment]
I can tackle this as a first-timer here if it's up for grabs.

**Comment by QuincyLarson** [comment]
@lricoy Sure - take a crack at it. Let us know if you need any help.

**Comment by raisedadead** [comment]
@QuincyLarson this is already implemented. It was removed most probably when we updated production and staging.

Please check 
https://github.com/freeCodeCamp/freeCodeCamp/pull/15488
https://github.com/freeCodeCamp/freeCodeCamp/pull/14979

**Comment by raisedadead** [comment]
We just need to add this back to the view. @padulam did some awesome implementation of it.

**Comment by QuincyLarson** [comment]
@raisedadead This was indeed implemented for reporting bugs. But this is a different use case. We are trying to help campers who are stuck - not necessarily those who've encountered bugs. 

I don't think we should even have a button in the UI to report bugs, because most bugs we receive from campers are just attributable user error. Instead, we should assume it's a help issue, and if the person who's helping them on the forum thinks they've indeed encountered a bug, then they can help open an issue.

I've updated my original post on this thread to clarify what the copy for the modal should be.

**Comment by raisedadead** [comment]
Thanks @QuincyLarson that clarifies it.

**Comment by QuincyLarson** [comment]
@lricoy this feature is pretty high-priority. If you've already made progress on this, please let me know. Otherwise I'm going to assign it to another contributor.

**Comment by prateekgoel** [comment]
@QuincyLarson I am willing to take this if someone else is not working.

**Comment by QuincyLarson** [comment]
@prateekgoel OK - sounds good. Let me know if I can be of further help. Looking forward to helping you QA this. Happy coding!

**Comment by prateekgoel** [comment]
Thanks @QuincyLarson . I'll start this today itself.

**Comment by rugano** [comment]
Hello Sir,I am brushing up through basic JavaScript and I have encountered
a problem with passing these challenges.Please help: 1.Return a value from
a Function with return.2.Use Conditional Logic with if statements. I have
posted in the forum. I had done all the challenges before but I seemed to
have lost them maybe due to not signing in. Thanks.

**Comment by prateekgoel** [comment]
@QuincyLarson This issue targets the current FCC and not the beta one, right?
Because I see beta already have an option to create topic on forum under the Bug Button functionality.
And the layout described in issue belongs to current FCC.
So the code resides in backup/master branch, right?
Also, can you please help me location the files i need to work on?

**Comment by QuincyLarson** [comment]
@prateekgoel Yes - it should target the backup/master branch. That's what we use for production. 

Later we will get this working for the staging branch as well. That will involve using React instead of jQuery.

**Comment by prateekgoel** [comment]
@QuincyLarson Thanks. Can you please guide me to the files i need to work? I am not able to find those.

**Comment by QuincyLarson** [comment]
@prateekgoel They are the view files like show.jade, showjavascript.jade. For the JavaScript, you'd want to put this in main.js with all the other clientside JavaScript logic. Let me know if I can be of further help with this. This is a high-priority issue.

**Comment by prateekgoel** [comment]
@QuincyLarson Thanks. Yes I understand this is a high-priority issue. Actually, being a beginner, I found it difficult to find the files. I will try and implement the modal soon.

**Comment by QuincyLarson** [comment]
@prateekgoel have you had a chance to start working on this?

**Comment by prateekgoel** [comment]
@QuincyLarson Yes, I'm working on this. Probably by this weekend i'll submit the PR.

**Comment by prateekgoel** [comment]
@QuincyLarson I created the modal successfully with takes to the forum. But i need little help in pre-populating the forum post. Can you please guide me on how can I fetch the title and body so that I can pass in in querystring?

**Comment by QuincyLarson** [comment]
@prateekgoel You should be able to just jQuery to select the code editor and grab its contents. An example of us doing this is when we update the challenge URL after a camper runs their code. We append their code to the URL. I would find that code and use it as an example.

**Comment by prateekgoel** [comment]
@QuincyLarson PR submitted.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (122/100 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60357 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx7F-0004f1-8F
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:20:53 -0400
Received: from o9.sgmail.github.com ([167.89.101.2]:6898)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx76-000252-A6
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:20:44 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=5xwVQ8qPJsM57JpSenifF7GsQd8=; b=lLgNTqRCBeokfG/g
	ChIvDDdQMomHZWa/vB3zoHlfky23kOMqk9lai5x8zKux3+D8yzT+QPyi1C5mN8ff
	xg56YWBreCReSWFZ/Vf+mW3RUJCERkyp9PcaBNMD9T5qbehiKBMGPU5n5tTjcwE4
	XESBibJ+gzwZ4Xzk8JIXLLvOnM0=
Received: by filter1160p1mdw1.sendgrid.net with SMTP id filter1160p1mdw1-25183-59AA076B-14
        2017-09-02 01:20:43.927200249 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0030p1mdw1.sendgrid.net (SG) with ESMTP id 2cLqrToiTGC8mlmit4cYhQ
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:20:43.889 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:20:43 +0000 (UTC)
