### ISSUE TITLE
Page unresponsive

### ISSUE THREAD

**Issue by juliativas** [freeCodeCamp/freeCodeCamp#15665]
#### Challenge Name

https://www.freecodecamp.org/challenges/sum-all-odd-fibonacci-numbers

#### Issue Description
I was trying to solve this challenge, wrote some bad code, and the tab became unresponsive. The worst part of it is that every time I load fCC page, this page loads and freezes, so I can not delete the code. How do I get fCC to work again? Restarting browser, logging out/in, and restarting the computer does not seem to help - still getting the same page with my deadly code.

#### Browser Information
* Chrome: 
* Operating System: OS X EL Capitan 10.11.5 
* Desktop

#### Your Code

```js



```
#### Screenshot

<img width="1280" alt="screen shot 2017-07-18 at 11 26 37 pm" src="https://user-images.githubusercontent.com/28714356/28349380-9495c6e0-6c10-11e7-9a52-81659151f8ac.png">

**Comment by Marmiz** [comment]
Looks like you started an infinite loop.

To prevent the page from auto-running the code, thus make it unresponsive try to add
`?run=disabled` at the end of the url.

other solutions can be found here:
https://forum.freecodecamp.org/t/free-code-camp-infinite-loop-protection/19550

Hope it helps 👍

**Comment by raisedadead** [comment]
Thanks @Marmiz , @juliativas please follow the steps as mentioned above.
