### ISSUE TITLE
Teacher_Student_Program

### ISSUE THREAD

**Issue by septimius72** [freeCodeCamp/freeCodeCamp#15677]
#### Issue Description
**### #WORK ON THIS<<<<<<<< cannot seem to figure out adding a student and grade to the dict/database** Program runs fine, but number [5] has an issue:

        [1] - Enter Grades < runs/no issues
	[2] - Remove Student < runs/no issues
	[3] - Student Average Grades < runs/no issues
	[4] - Exit < runs/exits/no issues
	[5] - Enter Student < problematic one, runs but it only shows Student Name, Grade and it wont add into the dictionary. it should append into sutdentDic in form { 'Name': [Grade]}

#### Your Code ####

#Teacher_Student project...simple grading and adding

from statistics import mean as m

admins = {'Python': 'Pass123@', 'user2': 'pass2'}

studentDict = {'Alex':[78,88,93],
				'Brandon':[87,67,76],
				'Joshua':[80,56,70], 
				'Peter': [67,65,70], 
				'Adam': [90,89,95], 
				'Elizabeth':[90,89,95]}

def enterGrades(): #adding grade function
	nameToEnter = input('Student Name: ')
	gradeToEnter = input('Grade: ')

	if nameToEnter in studentDict:
		print('Adding Grade... ')
		studentDict[nameToEnter].append(int(gradeToEnter))
	else:
		print('Student does not exist...')

	print(studentDict)	

def nameToRemove(): #removing student function
	nameToRemove = input('What student to remove?: ')
	if nameToRemove in studentDict:
		print('Removing student...')
		del studentDict[nameToRemove]

	print(studentDict)

def studentAVGs(): #average grade function
	for eachStudent in studentDict:
		gradeList = studentDict[eachStudent]
		avgGrade = m(gradeList)

		print(eachStudent, 'has an average grade of:', avgGrade)

**#WORK ON THIS<<<<<<<< cannot seem to figure out adding a student and grade to the dict/database**
def enterStudent():#adding student function
	nameToEnter2 = input('Student Name: ')
	gradeToEnter2 = input('Grade: ')

	if nameToEnter2 in studentDict:
		print('Adding student....')
		studentDict[nameToEnter2].append(nameToEnter2)

	elif gradeToEnter2 in studentDict:
		studentDict[gradeToEnter2].append(int(gradeToEnter2))
	
	else:
		print('wrong input')

	print(studentDict)
#WORK ON THIS<<<<<<<<

#main function
def main():
	print("""
	Welcome to Grade Central	

	[1] - Enter Grades
	[2] - Remove Student
	[3] - Student Average Grades
	[4] - Exit
	[5] - Enter Student
	""")
	
	action = input('What would you like to do today? (Enter a number) ')

	if action == '1':
		enterGrades()
	elif action == '2':
		nameToRemove()
	elif action == '3':
		studentAVGs()
	elif action == '4':
		exit()
	elif action == '5':
		enterStudent()
	else:
		print('No valid choice was given, try again')
#login section
login = input('Username: ')
passw = input('Password: ')

if login in admins:
	if admins[login] == passw:
		print('Welcome,', login)
		#puts me back at the beginning of the def main function/main loop
		while True:
			main()
	else:
		print('Invalid password, leave now!')
else:
	print('Invalid user name, DHS will be notified')

```
#### Screenshot

**Comment by septimius72** [comment]
not sure why my indentation shows like this code above.?..?
Original indentation is in order (i.e. as it should be)

**Comment by texas2010** [comment]
@septimius72 
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **"Help"** button on the challenge on freeCodeCamp, which will take you to the help chatroom for that specific challenge. You can also view our [**full list of official chatrooms**](http://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390).

If you think I'm wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
