### ISSUE TITLE
Camperbot PR cooperation with Commitizen

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/freeCodeCamp#15674]
The recent addition of commitizen to the npm package list means that if you follow the command prompts when making a commit, it will get flagged by camperbot for using an issue number in the commit message when you push the commit.

We should either update camperbot or update our settings on commitizen.

**Comment by QuincyLarson** [comment]
Agreed. A first-time contributor got this message from Camperbot. @BerkeleyTrue do you have access to Commitizen? If so, could you update its settings?

**Comment by vs1682** [comment]
Hi,
I raised a PR and the CamperBot flagged me for this same reason. 
I can raise a PR for freeCodeCamp/cz-freecodecamp to remove the part which asks for the issue number.

**Comment by BerkeleyTrue** [comment]
We should instead update camperbot as having issue numbers in commit messages is a standard across many open source projects.

**Comment by QuincyLarson** [comment]
OK - I've created an issue on CamperBot: https://github.com/freeCodeCamp/camperbot/issues/143

Any takers?

**Comment by dhcodes** [comment]
@QuincyLarson I may be wrong, but I think there are two camperbots, one for gitter and one for github. I believe this is the Github one: https://github.com/freeCodeCamp/camper-gh-bot

**Comment by aviral1701** [comment]
@dhcodes is right perhaps! Second one looks like the github one.Can I work on the issue?

**Comment by dhcodes** [comment]
@aviral1701 go for it

**Comment by QuincyLarson** [comment]
@dhcodes Thanks for the clarification. I've opened the issue there and closed the old one: https://github.com/freeCodeCamp/camper-gh-bot/issues/9

**Comment by BerkeleyTrue** [comment]
Closing this in favor of https://github.com/freeCodeCamp/camper-gh-bot/issues/9
