### ISSUE TITLE
Choose 5 algorithm challenges to be required for the new Algorithms and Data Structures certificate

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15675]
All of the certificates on beta require completing 5 projects. That is, all of the certificates except the Algorithms and Data Structures certificate, which instead requires completion of about 40 algorithm challenges.

This means we have to have the following text on the map: 
![a picture of the text "Challenges required for certifications are marked with a *"](https://www.evernote.com/l/Ar8p1BiJ8OhGfKyAcvgH7a5EJs6OMGXmaaMB/image.png)

To make things simpler, we should just choose 5 of these algorithm challenges and make those the required "Algorithm and Data Structures Projects" like we've done for all the other sections.

Then we won't have to explain: "In order to earn a certificate, complete its 5 required projects, except for the Algorithms and Data Structures certificate, where you'll need to complete 40 required  algorithm challenges."

Instead we'll just be able to say: "In order to earn a certificate, complete its 5 required projects."

This also jives with our philosophy of campers being able to "test out" of certificates. If a developer who's already really good at algorithms and data structures wants to claim the algorithms and data structures certificate, they shouldn't need to work through 40 algorithms to prove themselves. 5 algorithm challenges should be plenty to verify that they're ready.

So the task at hand is to choose which 5 algorithm challenges we want promote to being required "algorithm and data structure projects."

My intuitive answer is "we should just require them to pass the 5 hardest ones." But I thought it'd be a good idea to get other contributors' opinions on this.

**Comment by ooade** [comment]
The 5 hardest should do because if you can pass them it means you know the rest :)

**Comment by rmonastra** [comment]
If someone wants to "test out", I see no reasons the top 5 hardest challenges shouldn't be used.

**Comment by QuincyLarson** [comment]
Thanks for everyone's feedback. I will make the 5 hardest challenges required and remove the requirements for the other algorithm challenges. I'll just do this on beta for now simplicity.

**Comment by heatxizt** [comment]
Hey I know this has been closed, however I will like to suggest:
The 5 problems should be really different from each other, so that you really cover a variety of algorithms (you can select the hardest from each group)
Thanks for reading.

**Comment by QuincyLarson** [comment]
@heatxizt Thanks for your feedback. With this in mind, which 5 intermediate algorithm challenges would you would recommend we use?
