### ISSUE TITLE
Course Idea : Machine Learning using Octave

### ISSUE THREAD

**Issue by Survivor75** [freeCodeCamp/freeCodeCamp#15685]
Machine Learning course presented by Professor Andrew Ng and originally posted on the ml-class.org website. The course uses Octave to do all the programming assignments, which include real-life problems.
It would be awesome to have an interactive course on Machine Learning providing all the related Math and new technologies to work with.
Is there anyone who is working or willing to work on this?

**Comment by erictleung** [comment]
@Survivor75 thanks for the suggestion. I'm all for having a knowledge base and learning system for machine learning, but for the near future, I think freeCodeCamp has other priorities. You can contribute to the [machine learning guides](https://github.com/freeCodeCamp/guides/tree/master/src/pages/articles/machine-learning) in the meantime. You can also check out the [Python challenges](https://github.com/freeCodeCamp/python-coding-challenges) for another place to contribute for NumPy, pandas, and sci-kit learn.

cc/ @QuincyLarson

**Comment by Survivor75** [comment]
@erictleung I understand. However, I believe to build up on the documentation early as now will be good for exploring ways to present the course when freeCodeCamp will begin focussing on ML :)

**Comment by Survivor75** [comment]
@erictleung  I have begun working on ML guides and I cannot seem to find a way to add images to those documents :|

cc/ @QuincyLarson

**Comment by QuincyLarson** [comment]
@Survivor75 You can add images by using `![alt text](image URL)`

I agree with @erictleung that we should focus on Python for machine learning guides. Introducing Octave adds more complexity because most campers will not be familiar with C/C++.
