### ISSUE TITLE
User Profile Streak Chart uses different date/time than the table below it

### ISSUE THREAD

**Issue by mattgartner** [freeCodeCamp/freeCodeCamp#15689]
#### Issue Description
On the user profile page (i.e. https://www.freecodecamp.org/{username}, where it shows the chart with different months, and number of challenges per day on it, the chart seems to be using a different timing mechanism than the table below it. For example, if I'm in the Eastern U.S. timezone completing challenges at night, the table of completed challenges will show the following day, but the chart will show all of the challenges as having been completed on the current day. 

#### Browser Information
* Browser Name, Version: Chrome 59 (official build)
* Operating System: OS X Sierra
* Mobile, Desktop, or Tablet: Desktop

**Comment by J36miles** [comment]
Seems related to #7925 and #7468.

**Comment by dhcodes** [comment]
Thanks @J36miles. Closing as duplicate. Someday a hero will come along and fix the streak.
