### ISSUE TITLE
Not showing completed action when completed

### ISSUE THREAD

**Issue by JonathanKreiter** [FreeCodeCamp/FreeCodeCamp#1568]
Challenge http://beta.freecodecamp.com/challenges/waypoint-label-bootstrap-wells has an issue.

![image](https://cloud.githubusercontent.com/assets/12437314/9093899/a6714aae-3b63-11e5-9526-9b46d2a4f78c.png)

#left-well and #right-well have been inserted as instructed, though it is not being shown that it is done correctly, even though it is correctly inserted. Picture shows, above.

Thanks!

**Comment by flota113** [comment]
fixed in https://github.com/FreeCodeCamp/freecodecamp/commit/c66d2d54d5290b6cbabbf4f8745090a7cd1a0ccc
