### ISSUE TITLE
Stuck on "running tests" for entire APIs and Microservices section

### ISSUE THREAD

**Issue by oscarwong67** [freeCodeCamp/freeCodeCamp#15688]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/managing-packages-with-npm/how-to-use-packagejson-the-core-of-any-nodejs-project-or-npm-package

#### Issue Description

Upon providing a URL e.g. https://fanatical-psychiatrist.glitch.me/ for testing, the output reads "// running tests" and gets stuck there - no fail or pass.

#### Browser Information

* Browser Name, Version: Chrome, 58.0.3029.81
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```
{
	"name": "fcc-learn-npm-package-json",
        "author": "Oscar",
	"dependencies": {
		"express": "^4.14.0"
	},
	"main": "server.js",
	"scripts": {
		"start": "node server.js"
	},
	"engines": {
		"node": "4.4.5"
	},
	"repository": {
		"type": "git",
		"url": "https://idontknow/todo.git"
	}
}
```

#### Screenshot

![capture](https://user-images.githubusercontent.com/12058020/28647704-f8b33296-7225-11e7-89b6-5346fbeb1692.JPG)

**Comment by DarrenfJ** [comment]
I have the same issue.. noticed it seems to be something that's happened in the past too:

https://github.com/freeCodeCamp/freeCodeCamp/issues/13095

used the back end tester and each step 'passed'

https://narrow-plane.glitch.me/ <-- back end tester

**Comment by vkWeb** [comment]
@oscarwong67 I'm not able to reproduce this on my system. Please try entering ` https://fanatical-psychiatrist.glitch.me` once again and if the issue still persists, we'll have to look at the underlying functionality.

**Comment by oscarwong67** [comment]
The bug has been fixed in the months since this issue was created, from
what I can tell.
