### ISSUE TITLE
Factorialise a number - Working answer not accepted

### ISSUE THREAD

**Issue by Jimjule** [freeCodeCamp/freeCodeCamp#15692]
#### Challenge Name

https://www.freecodecamp.com/challenges/factorialize-a-number

#### Issue Description

I have a working solution to this problem (e.g. Factorialize(5) returns 120), but this is not acknowledged. I've returned the answer through 'num' as well as 'total', using 'i' as a parameter instead of 'num', but no luck.

#### Browser Information

* Browser Name, Version: Chrome 59.0.3071.115 
* Operating System: OSX
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
var total = 1;

function factorialize(num) {
  var array = [];
  for(num; num>0; num--){
    array.push(num);
    total *= num;
  }
return total;
}

factorialize(5);


```
#### Screenshot

![screen shot 2017-07-29 at 16 19 25](https://user-images.githubusercontent.com/17428597/28745884-c8427bd4-7479-11e7-9c58-b2d394556afa.png)

**Comment by erictleung** [comment]
@Jimjule thanks for the issue. You have global variables in your code. Our challenge tests run your function over and over and if you have any global variables, they will change with each test. So move your global variables to within your function and your code will pass. Happy coding!

**Comment by Jimjule** [comment]
Many thanks for your help, I'll remember that in the future.
