### ISSUE TITLE
Create a Controlled Form challenge does not actually create a form

### ISSUE THREAD

**Issue by AryanJ-NYC** [freeCodeCamp/freeCodeCamp#15690]
#### Challenge Name
http://hysterical-amusement.surge.sh/

React 30: Create a Controlled Form

#### Issue Description
The instructions for the challenge is as follows:

> The MyForm component is set up to handle changes on an input element. Add the input element in the return of the MyForm component, setting its value and onChange() attributes like the last challenge. Then, create a button with the text "Submit" to submit the input value. (The form won't submit anywhere, this is a simulation). The button should have an onClick() handler which triggers a method called handleSubmit(). This method should take the value that's currently in the input and set it to the submit property in local state. 

> Finally, create an h1 tag below the button which renders the submit value from the component's state. You can type in the form and click the button, and you should see your input rendered to the page.

I believe this challenge will teach students bad practice. In this form, the input element does not respond to the user pressing 'Enter' to submit the form.

I propose the solution require students to use a `<form>` tag with an `onSubmit` prop that is set to the `handleSubmit` function.  This is what is used in the [official React documentation](https://facebook.github.io/react/docs/forms.html#controlled-components).

#### Current Challenge Solution

```jsx
class MyForm extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			input: '',
			submit: ''
		};
	}
	handleChange = (event) => {
		this.setState({
			input: event.target.value
		});
	}
	handleSubmit = () => {
		this.setState({
			submit: this.state.input
		});
	}
	render() {
  	return (
	    <div>
        <input
        	value={this.state.input}
        	onChange={this.handleChange} />
        <button onClick={this.handleSubmit}>Submit!</button>
        <h1>{this.state.submit}</h1>
	    </div>
    );
  }
};
```
#### Proposed Challenge Solution
```jsx
class MyForm extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			input: '',
			submit: ''
		};
	}
	handleChange = (event) => {
		this.setState({
			input: event.target.value
		});
	}
	handleSubmit = () => {
		this.setState({
			submit: this.state.input
		});
	}
	render() {
  	return (
	    <form onSubmit={this.handleSubmit}>
        <input
        	value={this.state.input}
        	onChange={this.handleChange} />
        <button>Submit!</button>
        <h1>{this.state.submit}</h1>
	    </form>
    );
  }
};
```

**Comment by dhcodes** [comment]
paging @bonham000

**Comment by bonham000** [comment]
Hi, @AryanJ-NYC 

Thanks for this idea, I think it would be a good improvement. Are you interesting in making a PR to that repository? If not, let's open this issue there. Let me know what you'd like to do.

Thanks for the heads up @dhcodes

**Comment by bonham000** [comment]
Ok I moved this over, I'm going to close it here.
