### ISSUE TITLE
The 'Build a Pinterest Clone' challenge's example gives warning about site being insecure

### ISSUE THREAD

**Issue by aaronArinder** [freeCodeCamp/freeCodeCamp#15691]
#### Challenge Name

Build a Pinterest Clone
https://www.freecodecamp.com/challenges/build-a-pinterest-clone

#### Issue Description

Following the link to the [example](https://midnight-dust.hyperdev.space/) gives the following warning in Firefox: 

'The owner of midnight-dust.hyperdev.space has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.'

#### Browser Information

Firefox 54.0.1
Mac OS El Capitan 10.11.6

**Comment by dhcodes** [comment]
Confirmed on chrome too. Must have missed this when we changed all the hyperdev links to glitch.

**Comment by shubhshrma** [comment]
I would like to tackle this.
