### ISSUE TITLE
Erroneous instructions for "Waypoint: Use Responsive Design with Bootstrap Fluid Containers"

### ISSUE THREAD

**Issue by cherrychupachups** [FreeCodeCamp/FreeCodeCamp#1569]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Instructions state to "...nest all of our HTML in a div element with the class "fluid-container"..." However, the correct class should be "container-fluid". Similarly, the hint section states "Your div element should have the class "row"" which is also misleading.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1530
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1515
It seems this issue is fixed.
