### ISSUE TITLE
New navigation pane on beta has incorrect styling (night mode)

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/freeCodeCamp#15702]
While doing a beta challenge, I discovered that a navigation pane (like a mini-map) is now available on the left. I think this is probably a recent addition.  

The navigation page's styling in night mode is way off - 

![screenshot 2017-08-01 01 14 53](https://user-images.githubusercontent.com/11348778/28810281-e8c9b906-7656-11e7-8657-59c4ccb6ef6b.png)

The same pane in the regular theme - 

![screenshot 2017-08-01 01 16 25](https://user-images.githubusercontent.com/11348778/28810314-0e7437bc-7657-11e7-92c5-87417170dab2.png)

I'm not sure if this has already been reported. I did a quick search, didn't come up with anything.

**Comment by marigerr** [comment]
I'm having problems with Night Mode also with same look.  
Also it seems that I am unable to change from Night Mode back to Regular Mode.    When I go to settings and click on button for Night Mode, there is no response.

**Comment by theomeli** [comment]
Same here like @marigerr . There is no response when I am clicking on button for Night Mode when I am in Regular Mode

**Comment by wizofe** [comment]
Same problem here. Plus I can't find a way to disable Night Mode while on Beta.
