### ISSUE TITLE
Hour estimates don't wrap properly

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15706]
The hour estimates (for example: "(5 hours)") will get pushed down to the subsequent line if the map viewport gets narrow enough, and they no longer line up with the challenges they describe.

![jquery__target_html_elements_with_selectors_using_jquery___freecodecamp](https://user-images.githubusercontent.com/985197/28831682-e829b70a-769f-11e7-8b93-b81d1de3af4f.png)

We need someone to dig in and figure out a way these can float right without getting misaligned with subsequent lines.

**Comment by anawebdev** [comment]
Hi! Can I give it a try? I'm a first timer, would that be an issue?

**Comment by QuincyLarson** [comment]
@anawebdev Sure - that would be great. Please let me know if I can be of any help.

**Comment by dhcodes** [comment]
@anawebdev follow [these instructions](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) to get your local instance setup and go from there. You can ask questions in: https://gitter.im/FreeCodeCamp/Contributors

**Comment by 09JDPhil** [comment]
I'm not sure if this issue is resolved yet or not but I'll take a look into it.

**Comment by anawebdev** [comment]
@09JDPhil Hi! I just made  a pull request. Are you looking into that? I'm not sure what's supposed to happen after making a PR.

**Comment by 09JDPhil** [comment]
@anawebdev Hey! Sorry I don't know anything about your PR. I was also looking into fixing the problem but it seems you may have beat me to it :)
