### ISSUE TITLE
Update Editor skeleton theme 

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#15700]
The current editor skeleton does not match the style of the editor. This will need to be updated to match.

![learn_to_code___freecodecamp](https://user-images.githubusercontent.com/6775919/34641881-62f37cdc-f2bf-11e7-8d8b-6d7389f7d3b9.png)
![basic_html_and_html5__say_hello_to_html_elements___freecodecamp](https://user-images.githubusercontent.com/6775919/34641886-7593d7ba-f2bf-11e7-867c-e12b7b88163f.png)

Bonus points if you can couple the them of the skeleton to the theme of the editor so changing one changes the other.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
