### ISSUE TITLE
Syntax highlighting in editor

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15704]
Currently the beta code editor pane (light theme) doesn't have syntax highlighting.

![basic_javascript__word_blanks___freecodecamp_and_word_blanks___freecodecamp](https://user-images.githubusercontent.com/985197/28831606-a10333a6-769f-11e7-8516-d7abd5c1eb71.png)

**Comment by systimotic** [comment]
@QuincyLarson It looks like this was a conscious choice by Berkeley: https://github.com/freeCodeCamp/freeCodeCamp/pull/14707/commits/4a63126fa575661e2907ed9d8e1f629575356125
I could add it back in, but it would probably useful to learn why it was removed first. /cc @BerkeleyTrue

**Comment by BerkeleyTrue** [comment]
An unfortunate side effect of changing themes.

**Comment by QuincyLarson** [comment]
@systimotic Yes - please see if you can get the syntax highlighting to work in the light theme. Ideally, switching to dark mode would also switch the Codemirror theme back to the old dark theme. That's probably a separate issue, but since you're digging around in there, I thought I'd mention this.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson @systimotic I've just made a PR to fix this, but like @systimotic, I am unsure if there was some deeper reason for @BerkeleyTrue's original choice here. Though it does seem like this is doable with no other noticeable side effects. 

Though we are not in production with this, people are still using the beta site quite a bit, and this makes the overall experience quite a bit better, so I'm all for it unless there's something else going on here I'm unaware of. Thanks.

**Comment by BerkeleyTrue** [comment]
> please see if you can get the syntax highlighting to work in the light theme

@no-stack-dub-sack monokai was removed in favor of a light theme.

**Comment by no-stack-dub-sack** [comment]
Here are some choices. Or, we could just keep the old theme which has nice vibrant colors, and just make the editor background white (and change unquoted strings to a different color).

Thoughts @raisedadead @BerkeleyTrue @QuincyLarson? 

default 
![image](https://user-images.githubusercontent.com/18563015/31556822-887d00a6-b014-11e7-8bba-ae130c507c6e.png)

paraiso-light
![image](https://user-images.githubusercontent.com/18563015/31556514-6196ea7a-b013-11e7-97a2-c96c54205570.png)

base-16-llight
![image](https://user-images.githubusercontent.com/18563015/31556588-a737647e-b013-11e7-80e1-084d15d2c594.png)

solarized-light
![image](https://user-images.githubusercontent.com/18563015/31556741-35a81c3a-b014-11e7-85a4-e0972bead379.png)

**Comment by BerkeleyTrue** [comment]
The default of Monokai with a white background will work for me. The others will cause the codemirror instance to stand out from the rest of the pane.

@QuincyLarson thoughts?

**Comment by raisedadead** [comment]
I am also in favor of default one, for light theme.

**Comment by texas2010** [comment]
I am fine with default

**Comment by BerkeleyTrue** [comment]
@texas2010 Awesome. Let's move with the default theme.

**Comment by QuincyLarson** [comment]
@texas2010 @raisedadead @no-stack-dub-sack I am also in favor of the default theme for light mode.

**Comment by no-stack-dub-sack** [comment]
Sounds good, I'll update the PR
