### ISSUE TITLE
Make font size consistent across panes

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15703]
Currently the font size is different for each pane. 

![jquery__target_html_elements_with_selectors_using_jquery___freecodecamp](https://user-images.githubusercontent.com/985197/28826377-96755762-768f-11e7-8b32-159b1681b035.png)

I checked CodePen and they're using 15 px for all of their editors. JSBin is using 14px. I think 15 px is a good tradeoff between readability and compactness. So we should make all non-header text 15px.

**Comment by prateekgoel** [comment]
@QuincyLarson I agree that 15px if a good size. If you allow, i'd like to do this.

**Comment by QuincyLarson** [comment]
@prateekgoel OK - great! I think you were also working on the "help" button for production, right? That is a higher priority.

**Comment by prateekgoel** [comment]
@QuincyLarson Thanks. Yes, I'm working on the "help" button for production and it's at the top on my list.

**Comment by AbdelghaniTassi** [comment]
Can i work on this issue ?
i am a first timer

**Comment by QuincyLarson** [comment]
@AbdelghaniTassi Sure - I think most of what will need to be changed will be in the main.css file. You may be able to figure out what classes the different text elements are using by inspecting them in your browser.

**Comment by prateekgoel** [comment]
@AbdelghaniTassi As @QuincyLarson mentioned, you work on this then. All the best.

**Comment by AbdelghaniTassi** [comment]
@QuincyLarson @prateekgoel  Ok thank you i'll get started on this.

**Comment by prateekgoel** [comment]
@AbdelghaniTassi Did you get a chance to work on this?

**Comment by SavSE** [comment]
May I contribute?

**Comment by AbdelghaniTassi** [comment]
@prateekgoel i was busy lately i looked in the code and i identified the css classes that should be modified
i will finish it this weekend

**Comment by QuincyLarson** [comment]
@AbdelghaniTassi Awesome - thanks for the update. 

@SavSE We would love your help with some of these other help-wanted issues here: https://github.com/FreeCodeCamp/freecodecamp/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

**Comment by AbdelghaniTassi** [comment]
15px font size should be applied to tasks desriptions also ?
tasks description font size is by default equal to 1.5*nomal text size so i don't know if that should also have the same font size as the other panes
below the difference between a 15px task description and 15*1.5 
![15px_task_description](https://user-images.githubusercontent.com/6968349/29245315-de9e0390-7fd6-11e7-9b5c-fab82d893f08.PNG)
![orginal_size1 5](https://user-images.githubusercontent.com/6968349/29245317-e20249ec-7fd6-11e7-94e0-a8fe631b38ef.PNG)

**Comment by QuincyLarson** [comment]
@AbdelghaniTassi Excellent question. My inclination is to leave those descriptions the size that they are currently (we could specify a specific font size instead of using the 1.5x multiplier). What do you think about the current text size?

**Comment by AbdelghaniTassi** [comment]
@QuincyLarson I think that the current text size is ok it's big and catchy for the small descriptions. 
and as you said maybe we should specify a fixed size for the descriptions later so they don"t get bigger or smaller when we change the text size of other panes

**Comment by QuincyLarson** [comment]
@AbdelghaniTassi OK - we can leave the "slide" style challenge text the current size, but I think we should change it for all the other challenge views. 

Regarding your suggestion of fixing the size of text, I'm not sure if I correctly understand what you're proposing. We still want for people who have visual impairments or bad eyesight to be able to make text larger, right?

**Comment by AbdelghaniTassi** [comment]
@QuincyLarson Of course will always be able to adjust text in the browser. what i meant by fixed text size is removing the 1.5 multiplier (maybe later).

I set text size to 15px, now it looks consistent.

**Comment by vivek-agrawal27** [comment]
@AbdelghaniTassi Great Work!
