### ISSUE TITLE
Misspelling within Show The Local Weather challenge page

### ISSUE THREAD

**Issue by sophyphreak** [freeCodeCamp/freeCodeCamp#15711]
#### Challenge Name

https://www.freecodecamp.org/challenges/show-the-local-weather

#### Issue Description

When you click the link to the weather api -- https://fcc-weather-api.glitch.me/ -- the part where it says "Example: Requets[sic]: Response:" "Request" is misspelled.

#### Browser Information

* Browser Name, Version: Chrome, Version 60.0.3112.78 (Official Build) (64-bit), Most Recent
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

<img width="960" alt="2017-08-02" src="https://user-images.githubusercontent.com/22810755/28868617-3621207e-77a4-11e7-9f9f-de456873c6d3.png">

**Comment by sophyphreak** [comment]
I would fix it myself, but I'm really not sure where this is located in github. If someone can tell me, I would just fix it.

**Comment by dhcodes** [comment]
tagging @Em-Ant. Do you have edit rights to this?

**Comment by sophyphreak** [comment]
I don't think so no.

**Comment by Em-Ant** [comment]
@dhcodes no, it's not one of my glitch projects.

**Comment by erictleung** [comment]
cc/ @QuincyLarson not sure who has access to this Glitch project, but this should be a quick fix.

**Comment by QuincyLarson** [comment]
@MiloATH it looks like you control this Glitch project (at least judging from the Git blame function in the seed file). Can you make the edit real quick? I would fork your project and update it, but you seem to have made the Glitch project private.

**Comment by MiloATH** [comment]
I have fixed the 'Request' typo in the project. Let me know if there is anything else I should do.

**Comment by maciek23028** [comment]
Thanks i will definitely need more later at some stage.

**Comment by erictleung** [comment]
@MiloATH thanks for fixing this!

Closing as resolved. Happy coding everyone!

**Comment by QuincyLarson** [comment]
@MiloATH Thanks!
