### ISSUE TITLE
Update view to remove option of preview pane on JavaScript-only challenges

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15715]
Update view to remove option of preview pane on JavaScript-only challenges.

For example, http://beta.freecodecamp.com/en/challenges/basic-algorithm-scripting/convert-celsius-to-fahrenheit

![basic_algorithm_scripting__convert_celsius_to_fahrenheit___freecodecamp](https://user-images.githubusercontent.com/985197/28889166-c9d5856a-7788-11e7-8e1f-c34b501bc549.png)

**Comment by Bouzmine** [comment]
First timer here. I looked a bit through the codebase and found that it should already not be shown according to `common/app/routes/challenges/redux/index.js` at line 208:
> showPreview: challengeType === html,

Is that piece of code working ?

**Comment by QuincyLarson** [comment]
@Bouzmine I think @BerkeleyTrue intends to create some sort of flag on the challenges themselves that dictates what panes should be shown. He may not have finished it yet.

**Comment by algotastic** [comment]
I'm going to attempt to fix this.

**Comment by QuincyLarson** [comment]
@algotastic Awesome - please keep us posted on your progress with this.
