### ISSUE TITLE
JSBin-like pane control navigation button bar

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15710]
Currently the beta navigation looks like this: 

![basic_html_and_html5__headline_with_the_h2_element___freecodecamp](https://user-images.githubusercontent.com/985197/28831836-7434a214-76a0-11e7-812e-21bbdabdba9a.png)

We want to overhaul the navigation buttons control what's shown to look more like JSBin.com:

![js_bin_-_collaborative_javascript_debugging_](https://user-images.githubusercontent.com/985197/28838520-2e798f80-76b6-11e7-95a4-ac1887d24d97.png)

This should be right-adjusted in the navbar to make room for the forthcoming search bar.

This style of button is also commonly referred to as "pills." These would need to be able to change to an active state when the pane is open.

**Comment by buoyantair** [comment]
Ohh I'd like to try this on codepen first and see how it goes :O

**Comment by BerkeleyTrue** [comment]
I seem to remember we agreed to keep the buttons as is. This would not be a trivial change.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue I seem to remember agreeing that this UI change shouldn't hold up merging your branch. I do think we'll need a JSBin-like button bar to clearly indicate which panes are active.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue I updated the original issue to mention that the buttons should communicate the state of the active panes.

**Comment by buoyantair** [comment]
Wouldn't it be nice if you just had a drop down menu to the top of the "code" panel that indicates in what section they are? Or maybe it can be done such that the HTML/CSS/JS buttons are Inside the code panel, just like how it worked for the other panels (code panel, map, topic/tests). So the buttons in the menu bar are for the toggling of these major panels, and the buttons inside the codepanel are for toggling the different "language(html/css/js)" specific panels.

**Comment by QuincyLarson** [comment]
@buoyantair Can you create an illustration or point to an implemented example so we can better understand what you're proposing?

**Comment by buoyantair** [comment]
@QuincyLarson o_O 😅  Lemme do something to explain better >_>

**Comment by buoyantair** [comment]
@QuincyLarson o_O 😅  Lemme do something to explain clearly >_>

**Comment by QuincyLarson** [comment]
@buoyantair We plan to eventually allow for multiple JavaScript files and loading of specific libraries. Would you be interested in helping us implement this feature?

**Comment by systimotic** [comment]
@QuincyLarson What's the status of this issue? It's still labeled blocked, I'm not sure what needs to happen here.

**Comment by BerkeleyTrue** [comment]
The status of this issue is blocked. No action is requred
