### ISSUE TITLE
Update auto-email triggered by claiming final certificate in production

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15717]
When a camper claims their final certificate, we want a single email sent to them from my email address saying the following:

```

Subject: Congratulations on completing all of the freeCodeCamp certificates

Hi {{name}},

Congratulations on completing all of the freeCodeCamp certificates!

All of your certificates are now live at at: https://www.freecodecamp.org/{{username}}

Please tell me a bit more about you and your near-term goals.

Are you interested in contributing to our open source projects used by nonprofits?

Also, check out https://www.freecodecamp.org/contribute/ for some fun, convenient ways you can contribute to the community.

Happy coding,

Quincy

```

This will put the ball in their court and they can respond if they want to contribute to Open Source for Good.

This should replace the current system of emailing Michael and the team email.

This email, combined with their response, will give the information I need to provide further guidance on contributing to Open Source for Good.

**Comment by bonebizz21** [comment]
Remove
