### ISSUE TITLE
map text appears white

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#15721]
In the new multi-tab version, in Chrome (latest) on OSX 10.11.6:
![image](https://user-images.githubusercontent.com/18563015/28903100-13af658c-77d1-11e7-992b-4e1bbbdb65d2.png)

**Comment by Manish-Giri** [comment]
Reported here - https://github.com/freeCodeCamp/freeCodeCamp/issues/15702
