### ISSUE TITLE
Reactify User Profile Page

### ISSUE THREAD

**Issue by dhcodes** [freeCodeCamp/freeCodeCamp#15729]
Open the settings on Beta by clicking your avatar. Then click Show Me My Public Profile. The avatar image and profile image then expand to a 400x400 size.

Edit @quincylarson: We're making this the issue around-which we'll reactify the user profile and settings pages.

**Comment by BerkeleyTrue** [comment]
Navbar css has changed a lot on the react side, but these changes have not trickled into the static user navbar. 

It might be a better option to convert the user page into a react page. I believe this is the last static page that exist in the codebase. (

We would have to take care to handle the case when the user is looking at their own page or an anon user. We definitely don't want to start rendering pages with sensitive user information server side. This is due to our efforts to eventually move to a completely static generated site.

**Comment by raisedadead** [comment]
Yes, I have been wondering for some time now that we should be doing this.! If no else beats me to this I would love to get my hands a bit dirty on this one. 

Of course after I wind up other pressing PRs..!

**Comment by QuincyLarson** [comment]
Here's the main view that currently powers the profiles: https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/server/views/account/show.jade

The settings page is already reactified. This can serve as a model for what the reactified profile might look like structurally. Here are the components: https://github.com/freeCodeCamp/freeCodeCamp/tree/staging/common/app/routes/settings

**Comment by QuincyLarson** [comment]
@raisedadead have you had a chance to look at this? Would you or @dhcodes be interested in tackling this?

**Comment by zk433** [comment]
Can I just check if @raisedadead or @dhcodes are working on this?

**Comment by raisedadead** [comment]
@zk433 please go ahead... if you would be interested in working on this. happy coding!

**Comment by dhcodes** [comment]
agreed!

**Comment by zk433** [comment]
Ok, me, @chiefoleka and @Exclusiveyash are working on it.

**Comment by QuincyLarson** [comment]
@zk433 @chiefoleka @Exclusiveyash How is this going so far? Let me know if there's anything blocking your path here. We are all extremely excited about a reactified, updated user profiles 😄

**Comment by zk433** [comment]
@QuincyLarson,   @Exclusiveyash is working on the HTML and CSS now, I and @chiefoleka will attempt to reactify it. I was busy over the past few days but I'll get to it this week. If we struggle, you'll be the first to know :)

**Comment by QuincyLarson** [comment]
@zk433 Thanks for keeping me posted on this. I'm happy to help as necessary. My advice is demo early and often to get feedback :)

**Comment by codejockie** [comment]
Can I try this?

**Comment by Velveeta** [comment]
I was just eyeballing this also, for Hacktoberfest... It looks like this is actually in progress by @zk433 et al... If that's the case, you might want to remove the label on this particular issue, or you may just get more and more inquiries as it gets closer to October :)

**Comment by zk433** [comment]
Hi, yes, we are still working on it. If we get stuck, I'll ask for your help @codejockie  and @Velveeta, so stand by! :)

**Comment by QuincyLarson** [comment]
@zk433 Awesome - thank you for keeping us updated on this.

**Comment by martindavid** [comment]
@zk433 How is it going with this? I'd like to take part working on this as well if help is still needed?

**Comment by zk433** [comment]
@martindavid Hi! Please see issue #15942 for more details. I'll check with the rest of the team if they need any help, I'm currently working on the user page wireframe.

**Comment by theoutlander** [comment]
Is this still available?

**Comment by QuincyLarson** [comment]
@theoutlander It's almost done - @jonathan-grah is finalizing it.

**Comment by theoutlander** [comment]
Thanks. I think I’m missing something. Shouldn’t these issues be assigned? I’ve had a problem picking an issue on and off for the past week as everything I tried to claim was being worked on.

Sent from my iPhone

On Dec 22, 2017, at 7:10 PM, Quincy Larson <notifications@github.com<mailto:notifications@github.com>> wrote:


@theoutlander<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftheoutlander&data=02%7C01%7C%7Cdd8a4057405b4d349cf008d549b2b266%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636495954196121446&sdata=Td5%2BjvhSpgBwRxbFydjLmKNnijvL2pBLv9YGDKRBhoc%3D&reserved=0> It's almost done - @jonathan-grah<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjonathan-grah&data=02%7C01%7C%7Cdd8a4057405b4d349cf008d549b2b266%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636495954196121446&sdata=CL%2BJUK9KNVtj10dlpgOJkrloGdQNd79PyaDrNAV0slo%3D&reserved=0> is finalizing it.

**Comment by QuincyLarson** [comment]
@theoutlander Yes - it should have been assigned. We've assigned this one to @jonathan-grah.

**Comment by akkatracker** [comment]
Just going through old issues, was this fixed with #16743? https://github.com/freeCodeCamp/freeCodeCamp/pull/16743

**Comment by raisedadead** [comment]
Yup. Thanks @akkatracker
