### ISSUE TITLE
beta: map: "No Super Blocks"

### ISSUE THREAD

**Issue by ArielLeslie** [freeCodeCamp/freeCodeCamp#15725]
#### Challenge Name
http://beta.freecodecamp.com/en/map

#### Issue Description
A recent change seems to have messed up the map page. When it first loads it shows "No Super Blocks" and then when the map loads, it does not have the usual styling.  The collapse and search inputs are also missing, but I don't know if that was a deliberate choice.

#### Browser Information
* Browser Name, Version: Chrome 60
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![image](https://user-images.githubusercontent.com/6234475/28926612-912db316-7825-11e7-9ebc-fd09bb617995.png)

![image](https://user-images.githubusercontent.com/6234475/28926719-da95c264-7825-11e7-9e6e-be015a8258c4.png)

**Comment by dhcodes** [comment]
@ArielLeslie regarding the UI changes; yes they are intentional and search is coming back once it is improved. I've noticed the superblocks as let's leave this open. I suspect we need to incorporate a brief loading icon until the list populates.

**Comment by BerkeleyTrue** [comment]
closing in favor of #15697
