### ISSUE TITLE
Maybe add option that let users choose their own projects which fulfills the default project user stories?

### ISSUE THREAD

**Issue by dexrualo** [freeCodeCamp/freeCodeCamp#15722]
#### Issue Description
Feature request: Maybe add an option to let users choose their own projects? This may enable campers to code about things they are interested in and maybe hone creativity skills more. I don't know, just a suggestion.

**Comment by bonebizz21** [comment]
Aloha

**Comment by bonebizz21** [comment]
Thanks

**Comment by sithsupersu** [comment]
Sounds good to me.

**Comment by dhcodes** [comment]
Could you please elaborate? The projects are already intended to allow creativity. The user stories are just to provide some rough goals.

**Comment by dexrualo** [comment]
Maybe like this:
Option 1: Create a (default project) that fulfills the following user stories...

Option 2: Or create your own project that fulfills the following: a) Create using  (something learned from previous challenge)
b) Add a (something learned from previous challenges)
Etc.

**Comment by erictleung** [comment]
@dexrualo although I like the idea for learners to work on projects they genuinely are interested and are passionate about, I don't think having such open-ended projects is a good idea. For the general audience, this leads to non-concrete goals to achieve and more time spent on thinking of ideas of projects to complete. 

But you did mention it should be an option for those wanting to have this option. Even if you are dedicated to making your own application that is different from the project required, this may be hard to evaluate with such different variations (I can't say for sure as I don't "grade" them myself for handing out certificates).

cc/ @QuincyLarson @CodeNonprofit

**Comment by bonebizz21** [comment]
Create their on projects.

bonebizz

**Comment by rmonastra** [comment]
While I like the idea of creating your own projects, I like the backend projects format.  FCC gives you a boilerplate and you fill it in.  I feel this is helpful for real world experience.  From research, I've found you'll work a lot other people's code.

**Comment by QuincyLarson** [comment]
What to build is a business decision. How to build it is an engineering one.

Also, for the purpose of issuing certifications, we need some degree of standardization in what campers build. 

You're welcome to build whatever additional projects you want, though. We're working on adding dozens of optional extra project ideas with working demos and agile user stories.
