### ISSUE TITLE
feature request. search box on map. map could also be a fast reference book now.  

### ISSUE THREAD

**Issue by fastestnoob** [freeCodeCamp/freeCodeCamp#15736]
Not a bug.  

there is 4 pane view now. (beta)
when a user just close the editor and the preview panes we have: 
map + cheat sheat to selected subject. 
so this is basically a reference book now.  so it needs a search box.

[........................color......................] search. 

did you mean?

Css color text.
Coloring frames
Coloring HTML buttons
Coloring Bootstrap buttons.
Bootstrap class coloring
...
..
.
+
it could be even used for a fast reference lookup app. with improved search abilities. (a mobile app. preview+coding closed by default)

**Comment by knrt10** [comment]
I am intrested in this issue can this be assigned to me and can you direct me to the files that need to be changed.

**Comment by QuincyLarson** [comment]
@fastestnoob I agree. This would be great. @Bouncey is working on a full search engine for freeCodeCamp: https://github.com/freeCodeCamp/search
