### ISSUE TITLE
Need challenge teaching Object.freeze()

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/freeCodeCamp#15746]
#### Challenge Name

Currently non-existent

#### Issue Description

As brought up in the discussion of https://github.com/freeCodeCamp/freeCodeCamp/issues/14832, there needs to be challenge teaching how to use `Object.freeze()`, as the inclusion of this concept in a previous challenge was too lightly introduced and necessitated its own challenge.

#### Proposal

Create challenge teaching `Object.freeze()`. See [MDN's example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) for some guidance.

#### Contributing

Please first read the [contributing guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) before taking care of this issue. And feel free to visit the [Contributors Help](https://gitter.im/FreeCodeCamp/Contributors) chat room if you have any questions about helping. We're there to help.

**Comment by Manish-Giri** [comment]
I'll take this up.
