### ISSUE TITLE
Beta site UX GitHub login

### ISSUE THREAD

**Issue by saadanerdetbare** [FreeCodeCamp/freecodecamp#1574]
The GitHub login button is the first in the row
Could there be done more with layout to nodge new users to first make a GitHub account and then use that to login. The GitHub account is mandatory for the gitter chat and later for the basejumps

**Comment by BerkeleyTrue** [comment]
The flow we want: Sign it with what ever, reach the waypoint where it tells you about Github and how to create an account, signup with Github, link Github account.

We are taking steps to encourage Github auth but we do not want to add friction to new user before they start coding.

@saadanerdetbare Happy Coding!
