### ISSUE TITLE
'Bug' button not working in Es6 challenges

### ISSUE THREAD

**Issue by abohannon** [freeCodeCamp/freeCodeCamp#15740]
#### Challenge Name

All ES6 Challenges

#### Issue Description

Bug button not working

#### Browser Information

* Browser Name, Version: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
OSX
* Operating System: MacOS Sierra 10.12.3 (16D32)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```

**Comment by mariusespejo** [comment]
What exactly is the expected behavior for the bug button? I tried it on a couple other challenges (not just the es6 ones) and it doesn't appear to do anything.

**Comment by abohannon** [comment]
I believe it’s suppose to take you to GitHub so you can report it.

**Comment by Nevillealee** [comment]
Im going to take a stab at this if no one minds

**Comment by Nevillealee** [comment]
Does the Bug button open a modal?

**Comment by abohannon** [comment]
It doesn't do anything for me. After inspecting it, it looks like the input isn't setup.

**Comment by Nevillealee** [comment]
ok so the working version of the code should open a modal? or redirect straight to github?

**Comment by abohannon** [comment]
I think it is intended to point to github.

**Comment by zk433** [comment]
'Bug' button not working on SASS challenges either.

**Comment by w96k** [comment]
Confirm that its not working.
