### ISSUE TITLE
Teach string interpolation in Word Blanks

### ISSUE THREAD

**Issue by willnwhite** [freeCodeCamp/freeCodeCamp#15747]
#### Word Blanks
https://www.freecodecamp.org/challenges/word-blanks

#### Issue Description
Word Blanks is a good example of why string interpolation (`The ${myAdjective} ${myNoun}...`) is useful, so I think it would be good to teach it here.

**Comment by dhcodes** [comment]
I agree we should have a challenge for string interpolation but it seems possibly a little early in the curriculum at that point to introduce it. What do others think? cc @freeCodeCamp/moderators

**Comment by erictleung** [comment]
I think this will be good. But yes, this part of the curriculum might not be the best place to put it. Maybe near the end of Basic JavaScript would be a better place for it.

**Comment by willnwhite** [comment]
I think string interpolation should be taught with Word Blanks, even if that means moving Word Blanks to later in the curriculum. Otherwise, learners could do Word Blanks, stop doing Free Code Camp, and go off into the wide world using string concatenation where they should be using interpolation.

**Comment by QuincyLarson** [comment]
@willnwhite @dhcodes @erictleung I agree that we should teach string interpolation before we have the Word Blanks challenge. Would any of you be interested in designing one or two challenges around string interpolation that we could put before Word Blanks?

**Comment by willnwhite** [comment]
@QuincyLarson How about Word Blanks just linking to e.g. https://en.wikipedia.org/wiki/String_interpolation#JavaScript or https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals?

**Comment by QuincyLarson** [comment]
@willnwhite We would ultimately like to get rid of these links to external sources and say everything the campers needs to complete the challenge in the description. Linking to an external resource may actually increase the length of time it takes for the camper to finish the challenge. We can link to these articles from the wiki article that's shown when campers click the "help" button, but this is no substitute for making the challenge clearer.

**Comment by willnwhite** [comment]
@QuincyLarson I see. We can't count on the suitability of the article for the camper. What about Word Blanks just mentioning "string interpolation", then it's up to the camper to find a suitable reference?

**Comment by QuincyLarson** [comment]
@willnwhite I would recommend showing a quick example of how you can perform string interpolation - perhaps as a separate coding challenge that precedes this one. Would you be interested in helping create one?

**Comment by willnwhite** [comment]
Thank you, but no. I think campers should find and use references to do FCC (and use the browser console to try out small things from those references, like string interpolation). For instance, I searched for "string interpolation javascript" and found a nice intro: https://developers.google.com/web/updates/2015/01/ES6-Template-Strings.

**Comment by dhcodes** [comment]
@QuincyLarson I'll work on a challenge, but I sort of think it should come after Word Blanks. Word Blanks would teach how to pass parameters for use within a function and the new challenge would show another way to pass these parameters, but only when they are specifically strings). Thoughts?

**Comment by QuincyLarson** [comment]
@willnwhite I understand that sentiment. The situation is that campers are hitting this challenge, not figuring it out, and never coming back. We need to make this challenge clearer and easier to solve so they can keep moving forward. There will be plenty of opportunities for campers to sift through documentation when they reach the projects. When they are just starting out, we want to help them conserve momentum.

**Comment by QuincyLarson** [comment]
@dhcodes Word Blanks was originally designed as a "checkpoint" - it wasn't meant to teach anything new, but rather to review concepts campers had already learned. Can you think of a way we can teach a few concepts leading up to this challenge that will better-prepare campers to succeed on this challenge?

**Comment by willnwhite** [comment]
@QuincyLarson I'm sure you've heard though of campers "crashing" when they hit the projects. I'd treat Word Blanks as a warm up for the projects. It is actually a project in the sense that you're making something that someone else could use.

As to why Word Blanks is causing campers to leave, I think it could be because they don't know how functions work (they also [get stuck](https://github.com/freeCodeCamp/freeCodeCamp/issues/14143) on Convert Celsius to Fahrenheit, the first challenge with a function). I think that functions should be taught for those challenges, because the code campers end up writing [isn't good](https://github.com/freeCodeCamp/freeCodeCamp/issues/15333).

**Comment by QuincyLarson** [comment]
@willnwhite I agree that they need some practice, but this looks like just another challenge to them and there's nothing to indicate a ramp up in difficulty.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
