### ISSUE TITLE
Typos in Exercise Tracker API User Stories

### ISSUE THREAD

**Issue by anawebdev** [freeCodeCamp/freeCodeCamp#15769]
#### Exercise Tracker

https://beta.freecodecamp.com/en/challenges/api-and-microservice-projects/exercise-tracker

#### Issue Description

Third user story:
"Returned will **the the** user object **with also with the** exercise fields added. "

Fourth user story: 
"**Return** will be the user object with added array log and count (total exercise count)."

#### Browser Information

* Browser Name, Version: Chrome 60.0.3112.90 
* Operating System: Windows NT 10.0; Win64; x64
* Mobile, Desktop, or Tablet: Desktop

**Comment by kkavita92** [comment]
Will submit a PR in an hour or so!

**Comment by dhcodes** [comment]
Please change these sentences to be "App will return the user object..." @kkavita92

**Comment by systimotic** [comment]
@kkavita92 Would you still like to do this? Otherwise, I'll open this up to first timers.
