### ISSUE TITLE
Lesson 287 - The lesson is not letting me go forward, but my code is correct in any browser.

### ISSUE THREAD

**Issue by antonongithub** [freeCodeCamp/freeCodeCamp#15762]
#### Challenge Name

https://www.freecodecamp.org/challenges/record-collection

#### Issue Description

I created a function according to the rules of the task that accomplishes all of the objectives. I know this because any browser I have used, it shows me that what I have done is correct. The Free Code Camp editor, however, is not registering it as correct, thus not letting me pass off the task. The code I am using is at the bottom.

#### Browser Information

just the free code camp editor
* Browser Name, Version: Chrome 60.0.3112.78 + Firefox + Safari
* Operating System: iOS
* Mobile, Desktop, or Tablet: laptop

#### Your Code

```js

// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};

function updateRecords(id, property, value){
	if (value == ""){
		delete collection[id][property];
    }else if (Array.isArray(collection[id][property])){
		collection[id][property].push(value);
    }else if (property == "tracks"){
		collection[id][property] = [value];
    }else{
		collection[id][property] = value;
    }
}

updateRecords(5439, "artist", "ABBA");
updateRecords(5439, "tracks", "Take a Chance on Me");
updateRecords(2548, "artist", "");
updateRecords(1245, "tracks", "Addicted to Love");
updateRecords(2468, "tracks", "Free");
updateRecords(2548, "tracks", "");
console.log(collection);


```
#### Screenshot

![screen shot 2017-08-13 at 6 35 11 pm](https://user-images.githubusercontent.com/17724615/29254663-2e3da67e-8056-11e7-8448-9a57f9bf87d5.png)

**Comment by Marmiz** [comment]
@antonongithub Thanks for reporting this issue.

Your code is not submitting the correct solution.

The instructions states:

>Your function must always return the entire collection object.

On the other hand, you are manipulating the collection object but never returning it, therefore the test challenges won't let you through.

Also for the sake of clarity you have two instances of `var collection`; that can be problematic and cause some issues of variables with the same name.

same goes for the functions call, once you launch the test the system will call them for you under the hood, so no need to manually write all those functions:
```
updateRecords(5439, "artist", "ABBA");
updateRecords(5439, "tracks", "Take a Chance on Me");
updateRecords(2548, "artist", "");
updateRecords(1245, "tracks", "Addicted to Love");
updateRecords(2468, "tracks", "Free");
updateRecords(2548, "tracks", "");
console.log(collection);
```

If you have any more difficulty or doubt remember that you can always ask for further assistance in the [forum](https://forum.freecodecamp.com/) or in one of the official [chat rooms](https://forum.freecodecamp.org/t/free-code-camp-official-chat-rooms/19390)

**Comment by dhcodes** [comment]
thanks @Marmiz for the clear explanation. Closing as resolved.
