### ISSUE TITLE
Free Code Camp Weather API needs a list of all the possible weather outcomes and descriptions.

### ISSUE THREAD

**Issue by andrejarboe** [freeCodeCamp/freeCodeCamp#15767]
#### Challenge Name

[Show the Local Weather](https://www.freecodecamp.org/challenges/show-the-local-weather)
[Free Code Camp Weather API Pass-through](https://fcc-weather-api.glitch.me/)

#### Issue Description

We need a list of all the possible outcomes for that the weather API  JSON at "weather[0].main" and their descriptions at "weather[0].description". 

[The code pen example](https://codepen.io/freeCodeCamp/pen/bELRjV) gives 6 outcomes for weather[0].main but none for weather[0].description.  [The API example cal](https://fcc-weather-api.glitch.me/api/current?lat=35&lon=139)l gives an additional out come for a total of 7.

#### Known  out comes:
| weather[0].main | weather[0].description |
|-------------------|--------------------------|
| Drizzle                |                                      |
| Clouds               |                                       |
| Rain                   | moderate rain               |
| Snow                 |                                       |
| Clear                  |                                       |
| Thunderstorm   |                                       |
| Mist                   | mist                               |

Also, I don't know if weather[0].main is directly linked to weather[0].description, for example, if Rain can have more than one description. So that would be worth looking into as well.

#### Screenshot

![fccweatherapi](https://user-images.githubusercontent.com/17892981/29336601-5d97751c-81dc-11e7-9a70-8257670df853.PNG)

Api example call: 
![api](https://user-images.githubusercontent.com/17892981/29336727-be6f1ff2-81dc-11e7-81f5-8784e416d950.PNG)

**Comment by MatiasPi** [comment]
Add "Smoke" to the list. A friend got this output just now:

[Image](https://i.imgur.com/lhHaZfZ.png)

It is accurate. He said "There are wildfires up wind".

**Comment by moT01** [comment]
is this a workaround to another api? if so, you could maybe go there and find the list.

**Comment by lindakatcodes** [comment]
The FCC weather API uses data from openweathermap. I'm including a link here that shows the meaning for the weather icons and a list of the descriptions based on their id. As for main, I think the first number of the id describes the group, though I could be wrong on that. 

https://openweathermap.org/weather-conditions

I'd be happy to add this into the description page for the FCC API if desired. Just need to know where to go to do that. #15878 mentions a repo for it, but it's not owned/created by FCC so I'm not sure if it'll really work for the FCC endpoint or not.

**Comment by QuincyLarson** [comment]
@andrejarboe Thanks for bringing this to our attention. I agree - we should clarify the different possible weather outcomes right in the challenge instructions. Would you be interested in adding (or updating) a user story to specify the possible outcomes that the open weather API can return?

**Comment by QuincyLarson** [comment]
@guiKailu Yes - though I wouldn't use "e.g."

How about this:

User Story: I can see a different icon or background image that corresponds to the current weather. (The weather could be rain, snow, clouds, drizzling, clear, thunderstorm, fog, or smoke).

**Comment by guiKailu** [comment]
@QuincyLarson Yes, that grammar does clarify it. I found a few more weather conditions though, thanks to this [post](https://forum.freecodecamp.org/t/local-weather-api-call-problems/55047) by @merlincatman 

Perhaps all should be included, but with a license to combine subcategories under the same image, as @merlincatman has done with || operators in his post?

How about this? Maybe a bit too long now:

User Story: I can see a different icon or background image that matches the current weather. The weather could be rain, shower rain, light rain, moderate rain, snow, few clouds, scattered clouds, broken clouds, clouds, drizzling, clear sky, thunderstorm, mist, fog, or smoke. (The icon or image could be the same for shower rain, light rain, etc.)

The last sentence could be left out, with people figuring that idea out for themselves.

**Comment by QuincyLarson** [comment]
@guiKailu Awesome - I like that user story copy even better! I don't think it's too long. It succeeds in making things clearer. 

Would you be interested in opening a pull request to update the copy in the challenge?

**Comment by andrejarboe** [comment]
How do I help out and make changes?

**Comment by guiKailu** [comment]
@QuincyLarson Yes, I would be interested! I was going to let you know once I'm done :grinning:, but then I read the instruction, "Let us know you are working on it" :sweat_smile:
@QuincyLarson Thank you so much for everything you do here at FCC! I'm loving it.
I'll go back to learning about making a pull request now... :innocent:
