### ISSUE TITLE
Submit button doesn't work on click

### ISSUE THREAD

**Issue by Talkingbaby** [freeCodeCamp/freeCodeCamp#15763]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/es6/use-class-syntax-to-define-a-constructor-function

#### Issue Description

After completing one of the tasks the modal appeared saying I was successful. However, the next button did not work. So I used control + enter which allowed me to continue to the next lesson. From the next lesson without doing anything else you can use control + enter to successfully complete the assignment then skip to the next lesson.

* Browser Name, Version: chrome
* Operating System: mac
* Mobile, Desktop, or Tablet: desktop

**Comment by DusanSacha** [comment]
I can confirm. It is not only this mentioned challenge. I tried submit button in more beta challenges and it doesn't seem to work.

-    Browser Name, Version: chrome
-    Operating System: windows
-    Mobile, Desktop, or Tablet: desktop

**Comment by dhcodes** [comment]
Confirmed as well. Open for takers.

**Comment by adityaparab** [comment]
Looking into it.

**Comment by ajomadlabs** [comment]
@dhcodes Can I take up this issue ?

**Comment by dhcodes** [comment]
@ajomadlabs looks like @adityaparab is already working on it. You can find other issues by filtering for the help wanted tag. Many are still open or if they are older, then you can probably assume the person who claimed it is not still working on it.

**Comment by vivek-agrawal27** [comment]
@adityaparab Please update. How far have your work reached?

**Comment by adityaparab** [comment]
@vivek-agrawal27 : Take a look at [PR above your comment](https://github.com/freeCodeCamp/freeCodeCamp/pull/15770), :)
It is fixed but it needs to be updated as per review comment I received there. I'm on it. Please look into some other issue.

**Comment by vivek-agrawal27** [comment]
@adityaparab Yes I saw that :) I just wanted to know its latest stage. 
btw Great work.
