### ISSUE TITLE
Example Weather App Broken

### ISSUE THREAD

**Issue by nickpalmer789** [FreeCodeCamp/FreeCodeCamp#1577]
The codepen that is linked in http://www.freecodecamp.com/challenges/zipline-show-the-local-weather (http://codepen.io/AdventureBear/full/yNBJRj) does not work. The server gives the following error from http://www.ipinfo.io  "Failed to load resource: the server responded with a status of 429 (Too Many Requests)"
Maybe use something like navigator.geolocation to find the location of the user.
![weathercodepen](https://cloud.githubusercontent.com/assets/9010796/9097040/507afd8c-3b7e-11e5-8842-05189ed226a4.PNG)

**Comment by benmcmahon100** [comment]
Hey @nickpalmer789 I'm afraid that there is nothing really that can be done to solve this as even if it were fixed in the short term this would eventually happen again anyway. If the owner of the example is willing they might go and put some sample data in the make it look nicer
