### ISSUE TITLE
Responsive Web Design Principles: Make an Image Responsive challenge is not working

### ISSUE THREAD

**Issue by jenkuy** [freeCodeCamp/freeCodeCamp#15771]
#### Challenge Name
http://beta.freecodecamp.com/en/challenges/responsive-web-design-principles/make-an-image-responsive

#### Issue Description
The challenge is telling me that display is not set to blocked. When I asked in the help chat it worked for other users... I can't get it to approve that portion.

#### Browser Information
* Browser Name, Version: Firefox 54.0.1 (32-bit)
* Operating System: Windows 10 Pro
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
<style>
  img {
    max-width: 100%;
    display: block;
    height: auto;
  }
</style>

<img src="https://s3.amazonaws.com/freecodecamp/FCCStickerPack.jpg" alt="freeCodeCamp stickers set">

**Comment by joshua-fogg** [comment]
Hey Jenkuy,
have you tried refreshing the page and doing the example again?
sometimes it just needs a refresh to work.
I ran your code through the test and it passed on my end.

Let me know if this helps you

**Comment by jenkuy** [comment]
Yeah, I have refreshed, logged out and back in, cleared cookies, etc. The challenges after this one are also not clearing for me.

**Comment by dhcodes** [comment]
I think this PR will fix the issue. Thanks for reporting it!

**Comment by jenkuy** [comment]
Replacing "blocked" with "none" did not work for me in Firefox. But I got it to accept "blocked" in Chrome. Thank you!

**Comment by CHAITANYASAI-del** [comment]
> Yeah, I have refreshed, logged out and back in, cleared cookies, etc. The challenges after this one are also not clearing for me.

same issue

**Comment by ShaunSHamilton** [comment]
Please use the [forum](https://forum.freecodecamp.org/) to get assistance with a challenge. If it is determined to be a bug on the forum, **then** an issue may be opened here on the repo.

Thank you
