### ISSUE TITLE
Build A Nightlife Coordination App no longer works

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#15779]
#### Challenge Name

Main: https://www.freecodecamp.org/challenges/build-a-nightlife-coordination-app
Broken: http://whatsgoinontonight.herokuapp.com/

#### Issue Description

The app in the link for the Nightlife Coordination App http://whatsgoinontonight.herokuapp.com/ no longer works. The site loads but no search data is coming up, just stuck at the loading. 
#### Browser Information

* Browser Name, Version:  MS Edge, Chrome,  Firefox
* Operating System: Window 10 Pro 64-bit
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```
#### Screenshot

This is the output i see on the dev console after attempting a search for the city of Montreal. Same issue happens when searching for other major city such as new york city

![image](https://user-images.githubusercontent.com/22984739/29490638-351fff5a-8510-11e7-9a6e-a7368d960ddd.png)

**Comment by mstellaluna** [comment]
.

**Comment by vivek-agrawal27** [comment]
@mstellaluna I'm Looking into it. I'll update you soon about the issue.

**Comment by wwSchrader** [comment]
I second this. It keeps returning server status 500.

**Comment by yasserhussain1110** [comment]
Maybe you could use my app in its stead https://yasser-nightlife-app.herokuapp.com/

**Comment by QuincyLarson** [comment]
@yasserhussain1110 Nicely done. I like your app. Could you create a pull request updating the URL in the challenge?

**Comment by systimotic** [comment]
This has been fixed in #15825. This issue should have been closed automatically when that was merged, but apparently GitHub thought it would be a good idea to skip that on this one. 😄 If GitHub doesn't want to close this issue for us, I'll close it manually. Happy coding!
