### ISSUE TITLE
For recovering page

### ISSUE THREAD

**Issue by dishaspatel** [freeCodeCamp/freeCodeCamp#15776]
I think my program is in infinite loop. So, I can not rewrite the code. how can I break this loop and recover page?

**Comment by usmandap** [comment]
Kindly mention in what task you are facing this issue so we can help you. Share the url for that particular task. Thankyou

**Comment by erictleung** [comment]
@dishaspatel please take a look at https://forum.freecodecamp.org/t/free-code-camp-infinite-loop-protection/19550. Closing as not a bug on the site. Happy coding!

**Comment by dishaspatel** [comment]
@usmandap URL : https://www.freecodecamp.org/challenges/roman-numeral-converter
I am facing infinite loop problem for this particular program.
Thank you
