### ISSUE TITLE
GitHub Description of freeCodeCamp Organization Account uses .com domain

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/freeCodeCamp#15782]
#### Challenge Name
N/A

#### Issue Description
View https://github.com/freeCodeCamp/ and see the freeCodeCamp Website URL uses the .com and not the .org domain name.

#### Browser Information

* Browser Name, Version: Google Chrome
* Operating System: macOS
* Mobile, Desktop, or Tablet: Laptop

#### Your Code
N/A

```
#### Screenshot
N/A

**Comment by erictleung** [comment]
I think @QuincyLarson or @BerkeleyTrue might be the ones to change this.

**Comment by BerkeleyTrue** [comment]
Fixed. Happy Coding

**Comment by QuincyLarson** [comment]
@nsuchy thanks for catching this.

**Comment by nsuchy** [comment]
@QuincyLarson No problem, I'm going through all freeCodeCamp repos and opening issues / PRs where they're needed to address the .com links.
