### ISSUE TITLE
Not login with Github.

### ISSUE THREAD

**Issue by HuseyinTurkmenoglu** [freeCodeCamp/freeCodeCamp#15786]
#### Issue Description
I can not log in using the email address I used for Github. I gave it my permission. 

I always get this error.
**_Oops! Something went wrong. Please try again later_**

#### Browser Information

* Browser Name, Version: Chrome 60
* Operating System: Windows
* Mobile, Desktop, or Tablet:  Desktop

**Comment by erictleung** [comment]
I'd email team@freecodecamp.com for support help on your account.

cc/ @QuincyLarson @BerkeleyTrue
