### ISSUE TITLE
test not passing for <h4> elements present in <div class='col-xs-6'> elements

### ISSUE THREAD

**Issue by Joe-Balsamo** [FreeCodeCamp/FreeCodeCamp#1578]
Challenge http://beta.freecodecamp.com/challenges/waypoint-label-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Here is gist of my code: https://gist.github.com/Joe-Balsamo/73c16c3d877a366a557c

**Comment by benschenker** [comment]
Closing as stale
