### ISSUE TITLE
Toggle night mode in settings menu doesn't work

### ISSUE THREAD

**Issue by yogaboll** [freeCodeCamp/freeCodeCamp#15790]
#### Issue Description

When I go into settings and click on the night mode button, the website does not switch to night mode. It cannot switch back from night mode to default mode either. There is an error message in the console: `Cannot read property 'theme' of undefined`

I went into the code and to try to fix the issue, but I have so far come up short. The problem seems to be that `client/epics/night-mode-epic.js` is looking for the property `app.theme` in the redux store, which does not exist.

In `common/app/redux/index.js` there is an initialState object that looks like it is setting `app.theme` to `"default"`, however, clearly app.theme is never actually set to the redux store.

#### Browser Information

* Browser Name, Version: Chrome 60.0.3112.78, Firefox
* Operating System: Linux Mint
* Mobile, Desktop, or Tablet: Desktop

**Comment by hadaclay** [comment]
Had a look at this for a little bit. If night mode is already set somehow, the following error is thrown: 
```
Warning: 
        Future versions of redux-epic will pass all items to the dispatch
        function.
        Make sure you intented to pass [object Object] to the dispatch or you
        filter out non-action elements at the individual epic level.
        Check the nightModeSaga epic.
```
I got here after trying to manually set `app.theme` in `client/index.js`. Hopefully this helps somehow, I'm not terribly familiar with redux/redux-epic.

**Comment by QuincyLarson** [comment]
@yogaboll Well done. Works for me.
