### ISSUE TITLE
React challenge alpha #35 incorrectly accepts a string as a parameter to add or remove event listener call

### ISSUE THREAD

**Issue by grumpwagon** [freeCodeCamp/freeCodeCamp#15793]
#### Challenge Name
http://hysterical-amusement.surge.sh/ 
React challenge number 35 - Add Event Listeners

#### Issue Description
I hope this is the right place for this issue. 

The second parameter for the remove/addEventListener calls will accept the strings "handleKeyPress" or "handleKeyPress()" as correct input. All tests pass with either of those strings, allowing you to move on to the next challenge. Code sample that passes all tests (but does not operate as expected) attached below.

#### Your Code

```js
class MyComponent extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			message: ''
		};
	}
	// change code below this line
	componentDidMount() {
		document.addEventListener("keydown", "handleKeyPress")
	}
	componentWillUnmount() {
		document.removeEventListener("keydown", "handleKeyPress()")
	}
	// change code above this line
	handleEnter = () => {
		this.setState({
			message: this.state.message + 'You pressed the enter key! '
		});
	}
	handleKeyPress = (event) => {
    if (event.keyCode === 13) {
    	this.handleEnter();
    }
  }
  render() {
    return (
			<div>
				<h1>{this.state.message}</h1>
			</div>
    );
  }
};

```
#### Screenshot

<img width="1636" alt="screen shot 2017-08-23 at 15 16 30" src="https://user-images.githubusercontent.com/1668286/29636401-183a3ae6-8816-11e7-9445-898a77ba1072.png">

**Comment by dhcodes** [comment]
tagging @bonham000. Should I suggest moving these issues to your repo?

**Comment by bonham000** [comment]
Yes, @grumpwagon can you post this issue on the repo for those challenges?

**Comment by grumpwagon** [comment]
Sure! Didn't realize that existed. Opened [issue 228](https://github.com/bonham000/fcc-react-tests-module/issues/228)
