### ISSUE TITLE
Text doesn't change when going to next/previous step

### ISSUE THREAD

**Issue by anawebdev** [freeCodeCamp/freeCodeCamp#15796]
#### Challenge Name

https://beta.freecodecamp.com/en/challenges/basic-node-and-express/introduction-to-the-basic-node-and-express-challenges

#### Issue Description

1. When going to step 2/2, the last 3 paragraphs of step 1/2 are still displayed
2. If I click "Go to my previous step", the same 3 paragraphs are displayed twice, with different font

#### Browser Information

* Browser Name, Version: Chrome 60.0.3112.90
* Operating System: Windows NT 10.0; Win64; x64
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![](http://i.imgur.com/qul5zq1.jpg)

**Comment by vivek28111992** [comment]
Can I give it a try?

**Comment by dhcodes** [comment]
Confirmed. Go ye forth @vivek28111992
