### ISSUE TITLE
Clarification on "Map the Debris" Bonfire

### ISSUE THREAD

**Issue by jonboiser** [FreeCodeCamp/freecodecamp#158]
[Link to Bonfire](http://www.freecodecamp.com/bonfires/map-the-debris)

1. By "Sputkin" do they mean "Sputnik"? If it is really Sputnik, the Wikipedia article for Sputnik1 says that its semi-major axis was about 6500 km.
2. ~~What are the units involved? Looking at the test case for the Moon: `{name: "moon", orbitalPeriod: 2377399}`, if the Orbital Period is in seconds, then that is 2377399 / (60 * 24 * 60) = 27.52 days. If the GM constant provided by the problem is also in units of km^3/s^2 (as in Wikipedia), than this would be so.~~ (EDIT: I left out an extra 7 in that calculation).

If the purpose is to get the solver to use the `Math` object methods (`PI`, `pow`, etc.) and maybe the `map` method, it might be better to just provide an explicit formula, since I don't think I'm applying the information from Wikipedia correctly.

**Comment by jonboiser** [comment]
Ah, I found my mistake in implementing the Wikipedia formula. The "sputkin" still bothers me though, also more pedantic people might get hung up on using assuming that the average altitude can be used to compute the semi-major axis, unless they are explicitly told they can make that assumption.

**Comment by terakilobyte** [comment]
Jonathan,

Sputkin was a joke, a play on sputnik.
