### ISSUE TITLE
Top menu button remains active after click.

### ISSUE THREAD

**Issue by w96k** [freeCodeCamp/freeCodeCamp#15806]
#### Issue Description

This behavior looks like a little defect. After clicking on a menu item it remains to be active. Actually would be great menu items active while they are really active like map menu item is active (light bg) when map sidebar is open and non-active when it doesn't.

#### Browser Information

* Browser Name, Version: Opera 47.0
* Operating System: Mac OS
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![image](https://user-images.githubusercontent.com/22467404/29734824-23b09968-89fd-11e7-85d2-56618a9cc232.png)

**Comment by m-henderson** [comment]
I cant reproduce this issue.

**Comment by rcohane** [comment]
I was able to reproduce this issue on Chrome, but not on Safari. I'm running Mac OS. On Safari, the menu items are only highlighted when the pointer is hovering over them.

On Chrome, the first time you click on Map, the map is opened and Map is not highlighted in the navbar. Each time you click on Map after that, it remains highlighted. If you click anywhere else on the page or reload the page, it will unhighlight.
The behavior is the same for Map, Side Panel and Editor. For Community, if you click on it from the home page it works correctly. If you click on Community after having clicked Map, then Community has the same suspect behavior.

After clicking on Map for the first time from the home screen, it is not highlighted:
![screen shot 2017-12-09 at 12 32 33 pm](https://user-images.githubusercontent.com/21317235/33797859-0c4b8a2a-dcdd-11e7-820a-156fa26dff0b.png)

It is highlighted on all subsequent clicks:
![screen shot 2017-12-09 at 12 32 56 pm](https://user-images.githubusercontent.com/21317235/33797864-2359e0cc-dcdd-11e7-9494-ec7750f501a1.png)

![screen shot 2017-12-09 at 12 33 01 pm](https://user-images.githubusercontent.com/21317235/33797865-2603bc62-dcdd-11e7-868a-fbfb7cb8742e.png)

It unhighlights after clicking elsewhere on the page.
![screen shot 2017-12-09 at 12 34 16 pm](https://user-images.githubusercontent.com/21317235/33797877-540e7c64-dcdd-11e7-82ef-75e70d02a901.png)

**Comment by raisedadead** [comment]
This seems to have been resolved.
