### ISSUE TITLE
Submit button doesn't work on click [beta]

### ISSUE THREAD

**Issue by w96k** [freeCodeCamp/freeCodeCamp#15805]
#### Challenge Name

Any challege on beta

#### Issue Description

After finishing any challenge I can't click on the "Submit and go to next challenge" button but can pass it with ctrl+enter key-combo.

#### Browser Information

* Browser Name, Version: Opera 47.0
* Operating System: MacOS
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
![image](https://user-images.githubusercontent.com/22467404/29734541-6e26cffa-89fb-11e7-953c-dfa7bc1f9d47.png)

**Comment by vivek28111992** [comment]
Can I try this?

**Comment by systimotic** [comment]
Hi @w96k! Thanks for reporting this issue.

I'm closing this as a duplicate of #15763
I have updated the title of that issue to make it easier to find.

Happy coding!
