### ISSUE TITLE
the wrong way lead to Chrome crash

### ISSUE THREAD

**Issue by hitao123** [freeCodeCamp/freeCodeCamp#15810]
#### Challenge Name

https://www.freecodecamp.org/challenges/sum-all-odd-fibonacci-numbers

#### Issue Description

some wrong code make Chrome crash  even if i know how to clear localstorage but i can not open Developer tools !  so any solutions to solution to fix this bug when user make some mistakes in writing the wrong code. [solution](https://forum.freecodecamp.org/t/clear-specific-values-from-your-browser-local-storage/19128)
![_e pl ns xes au0z 4](https://user-images.githubusercontent.com/16607714/29747898-88ba8280-8b3b-11e7-9272-91e4c3966211.png)

#### Browser Information

* Browser Name, Version:  60.0.3112.101
* Operating System: Windows7
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code

```js



```

**Comment by Marmiz** [comment]
Hello @hitao123 , thanks for reporting this issue.

Seems like you have written an infinite loop causing your browser to crash.
FCC has an autorun feature that run you previous code automatically on page load.

You should disable this feature by adding
```
run=disabled
```
In the url.
More info on the topic [here](https://forum.freecodecamp.org/t/free-code-camp-infinite-loop-protection/19550).

Next time also consider asking for help in the forum or in chat.

**Comment by dhcodes** [comment]
Thanks @Marmiz . Closing as resolved.
