### ISSUE TITLE
Update Docs to Show How to Push to Production

### ISSUE THREAD

**Issue by benschac** [freeCodeCamp/freeCodeCamp#15812]
Document how to work off production.

**Comment by dhcodes** [comment]
@benschac Thanks for the issue and PR. I'm conflicted on whether to include this mostly because the changes to production are rare and I wouldn't want to cause more confusion for a new contributor. What do others think? cc @freeCodeCamp/moderators

**Comment by Bouncey** [comment]
I would suggest it is an edge case and will not be required when staging is merged into master

**Comment by benschac** [comment]
Could we label it as something along the lines of Legacy work?

**Comment by benschac** [comment]
While it's one off there are still requests for this work and we should
have documentation for it while we still need it.  Warning signs could also
work too :D

**Comment by texas2010** [comment]
I am not sure about that one.  when we release the beta to production. backup/master will be "gone". we will not work on that branch after beta released.

more like we have to use example branch. so we don't have to change it again.   for showing them how to use checkout track on another branch. or something.

**Comment by systimotic** [comment]
Thanks for the issue @benschac! More documentation is often good, but I think there are a couple issues with this:
1. A lot of people reading this guide already are at the edge of their abilities trying to understand what's going on. Adding this without clear instructions not to do this unless it's explicitly mentioned will cause confusion.
2. Because of the massive differences between dependencies and workflow, a lot more needs to happen than switching the branch. As far as I'm aware, most contributors who need to get an instance of the `backup/staging` running branch clone it into a new folder and follow the `CONTRIBUTING.md` of that branch to install and run everything.

I'm not sure if there is a good way to document this.

**Comment by raisedadead** [comment]
FWIW, I am inclined to understand what the potential issues especially new contributors and/or occasional contributors should be facing. I have commented on this earlier, faced this while helping potential contributors in chat and even answered on the forum for a question on split versions of the codebase.

But, what @benschac has pointed is correct. 

I suggest let's rather have this as a wiki guide on the forum and link to it from the contributing guide at the very top with a warning about the staging vs production (master). _just like you would see at times on a Wikipedia article, going through a change frequently_

We could then remove the warning when needed.

**Comment by benschac** [comment]
I'll update my PR after work. Thnx.

**Comment by systimotic** [comment]
@benschac Ping! 🔔 No hurry, just making sure you didn't forget about this 🙂

**Comment by benschac** [comment]
Hey,

Sorry for the late response! I've been moving and I have some work stuff.
I'll totally get to this soon. Thanks for the ping. :D.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (111/100 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:39157)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUOk-0006Lf-Tu
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:54:22 -0400
Received: from out-10.smtp.github.com ([192.30.254.193])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUOK-0006Hk-6Z
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:56 -0400
Date: Sun, 03 Jun 2018 07:53:54 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037634;
	bh=AG81nfO8ZUUhsX0JVzcoWDzsiofvoxXCHWNKahhhxlo=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=rvTFGh6LEGvDlmPD5uRjtoexxd6amQThZxL6wcVVpcAh9PODvuTsRIhBDZXvtbcrC
	 O+r8YwHtjHtNXHEIchzbsi1IkON4KxyXxus1MMVUNi/XjZqvGc7xLaRpEzfQpvGIMv
	 9IaykmaEQxT3yXgFOMiGGLxvy59PbQbwCI/0Hfy4=

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (113/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:39629)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUPj-000761-Kh
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:55:23 -0400
Received: from out-4.smtp.github.com ([192.30.252.195])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUOG-0006Hh-9m
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:52 -0400
Date: Sun, 03 Jun 2018 07:53:50 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037630;
	bh=ahkzeu+8haFyGEPrs4XLi+Zcfkej8rngsmBbdkAdb9E=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Ts1AkUrIJMk7ZBtAC6lSKiEhbPNs5i41xfHKe6rM3kALrV02UaRSsVDAs8PuFoIPW
	 g8WFEeVfsdvr2hjGJUhkSOl2bN+Ajf50SdDllgFfotfu2xyVbBlNRwWhzY3YsU6heO
	 n/mXt3npO8mzI9KEIY/Lb3pferiyu68SNFbEke9I=
