### ISSUE TITLE
Update email should not modify user object before its confirmed

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#15822]
After passwordless #9660 has landed, the reset logic on accounts will be removed.
 
This means that we should not be updating the email on records with an update unless it's confirmed via the update email sent.

This needs a minor refactoring to the updating logic.

**Comment by raisedadead** [comment]
I can work upon this as soon as https://github.com/freeCodeCamp/freeCodeCamp/pull/15891 has landed

**Comment by fumblehool** [comment]
What is the status of this issue? Is it still open? Is anyone working on this?

**Comment by QuincyLarson** [comment]
@raisedadead Now that #15891 has landed, are you interested in starting working on this? We are getting closer to shipping beta, and this issue is on the critical path :)

**Comment by raisedadead** [comment]
@QuincyLarson I have already made a PR, see linked above.
