### ISSUE TITLE
Create or find a Calendar Heatmap React component

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15826]
Currently we're using [this D3 library](https://github.com/wa0x6e/cal-heatmap) to generate a calendar heatmap.

Here's what it looks like:

![camper_quincylarson_s_code_portfolio___freecodecamp](https://user-images.githubusercontent.com/985197/29942423-a91ccbb6-8e4a-11e7-9e7a-d3b3c5cdc3cb.png)

We want help converting this into a react component.

**Comment by dhcodes** [comment]
[react-calendar-heatmap](https://www.npmjs.com/package/react-calendar-heatmap) seems to have potential.

**Comment by QuincyLarson** [comment]
@dhcodes Awesome - would you be interested in plugging it in and seeing if you can get it to work? This is related to https://github.com/freeCodeCamp/freeCodeCamp/issues/15729 which I think you're already familiar with.

**Comment by jackyho112** [comment]
@QuincyLarson 

I have been wanting to contribute to freeCodeCamp for a while now. I think I can handle this and i can get to it right away. Is it ok if I give this one a go?

**Comment by adityaparab** [comment]
@QuincyLarson @dhcodes : I deal with graphs almost everyday. I'll work on this.

**Comment by dhcodes** [comment]
go for it @adityaparab !

**Comment by adityaparab** [comment]
@dhcodes : Confirmed.. Will start on it asap.

**Comment by QuincyLarson** [comment]
@adityaparab Awesome. Thanks for your help. Please keep us posted on your progress with this.

**Comment by adityaparab** [comment]
@QuincyLarson Sorry for delayed response. I've been travelling a lot for last couple of weeks and have no internet access on my laptop as of now. I'll be submitting PR for this and other two issues this weekend.

**Comment by QuincyLarson** [comment]
@adityaparab Thanks for keeping us posted on this :)

**Comment by ecotg** [comment]
@adityaparab Are you still interested in working on this? I'd love to implement it

**Comment by adityaparab** [comment]
@ecotg : Give me a couple of days. It's been very busy couple of months at work and I'm on a move constantly. I have implemented the component but not finding enough time to test it after integrating it with fcc environment.

If I'm unable to raise a PR on this by Oct 1st 1am PST, feel free to take it up. 
If I'm not able to finish this by then, I'll also make sure I commit the heatmap component with all the business logic on my github repo and share the link with you. So that you can start integrating it directly.

**Comment by makeupsomething** [comment]
@adityaparab @ecotg 
If still available after Oct 1st I'm very interested to work on this as part of Hacktoberfest.
First time contributor to an open source project btw.

**Comment by QuincyLarson** [comment]
@ecotg 1 a.m. PST has come and gone, so it doesn't look like @adityaparab is going to get to it (to their credit, they are working on a lot of other issues here). Are you still interested in tackling this? 

@makeupsomething also expressed interest in helping on this, so perhaps the two of you could pair program on it?

**Comment by adityaparab** [comment]
To be fair, it's all yours @ecotg @makeupsomething 

@QuincyLarson : Sorry for the delay mate. :(

**Comment by ecotg** [comment]
Yep, still interested. Already started working on it.

**Comment by QuincyLarson** [comment]
@ecotg Awesome - thanks for keeping us posted on your progress on it :)

**Comment by surmistry** [comment]
Hey Quincy, huge fan of freeCodeCamp and would love to tinker with this bug. 
Looks fairly straight forward

**Comment by zk433** [comment]
@ecotg Hi! I was just wondering if you have had any chance to work on this? Thank you for letting us know :)

**Comment by QuincyLarson** [comment]
@surmistry Thanks for your kind words.

@ecotg have you had a chance to start working on this? If not, could we let @surmistry take a crack at it?

**Comment by martindavid** [comment]
@surmistry @ecotg have you guys working on this? I wondering since a couple of days, because no answer to Quincy question. If no one working on this, I'd love to take this.

**Comment by ecotg** [comment]
Hi, yes already started work on this. Should have a PR ready sometime this week. Sorry for the delay

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
