### ISSUE TITLE
Old links in descriptions

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/freeCodeCamp#15824]
#### Issue Description
1. The short description on the main page of this repo links to `.com` instead of `.org`
2. The organisation page links to `http` instead of `https` (sidenote: Should it say fCC is located in SF?)

@QuincyLarson I think that you and Berkeley are the only ones that can change this.

#### Screenshot
1.
![firefox_2017-08-31_13-15-15](https://user-images.githubusercontent.com/7262039/29920609-758f8154-8e4e-11e7-8aee-414c5d626a7f.png)
2.
![firefox_2017-08-31_13-16-06](https://user-images.githubusercontent.com/7262039/29920633-8f792610-8e4e-11e7-9243-2d9dd9e2fcc1.png)

**Comment by QuincyLarson** [comment]
@systimotic Nice catch. Fixed!
