### ISSUE TITLE
[BETA] SASS section doesn't work

### ISSUE THREAD

**Issue by w96k** [freeCodeCamp/freeCodeCamp#15830]
#### Challenge Name

http://beta.freecodecamp.com/en/challenges/sass/store-data-with-sass-variables

#### Issue Description

Seems like sass section doesn't work yet.

#### Browser Information

* Browser Name, Version: Opera 47.0
* Operating System: MacOS
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```html

<style>
  $text-color: red;
  
  .header{
    text-align: center;
    color: $text-color
  }
  .blog-post h2 {
    color: $text-color;
  }
</style>

<h1 class="header">Learn Sass</h1>
<div class="blog-post">
  <h2>Some random title</h2>
  <p>This is a paragraph with some random text in it</p>
</div>
<div class="blog-post">
  <h2>Header #2</h2>
  <p>Here is some more random text.</p>
</div>
<div class="blog-post">
  <h2>Here is another header</h2>
  <p>Even more random text within a paragraph</p>
</div>

```

**Comment by QuincyLarson** [comment]
This is a known issue. We're closing this but will definitely get this working before we push beta to production.
