### ISSUE TITLE
Where can I find my certificate?

### ISSUE THREAD

**Issue by sandeshvijayraj** [freeCodeCamp/freeCodeCamp#15835]
#### Issue Description
https://www.freecodecamp.org/challenges/claim-your-front-end-development-certificate
i completed everything in front end but while claming ir said it put my certificate on personal portfolio now were did that come how do i know from were i can access that certificate
_Title moved to description by @systimotic_

**Comment by systimotic** [comment]
Hi @sandeshvijayraj! Congratulations! 🎉 

Your public profile is at the following URL: https://www.freecodecamp.org/sandeshvijayraj
You should also get there by clicking your profile picture in the top right of every page on freeCodeCamp.

You can click the button on your profile to view your certificate. Here is the URL: https://www.freecodecamp.org/sandeshvijayraj/front-end-certification

I hope this answer satisfies your question. If not, please add additional info and reopen this issue. Happy coding!
