### ISSUE TITLE
Sum All Odd Fibonacci Numbers

### ISSUE THREAD

**Issue by username1001** [freeCodeCamp/freeCodeCamp#15832]
#### Challenge Name

https://www.freecodecamp.org/challenges/sum-all-odd-fibonacci-numbers

#### Issue Description

At first, I thought this might have been an issue on my part(i.e. browser history, cache, etc.) I cleared everything and tried again. No luck. I then assumed something might have been wrong with FCC itself. Every time I logged on, it brought me to my last challenge, and became unresponsive. Upon looking at my code, I realized that it might be causing the problem, so I went to freecodecamp.com/usernameHere, and everything worked fine. 

**The Issue:** 
My code is _allegedly_ freezing the page(can't click anything), and because of this, I will not be able to do the challenge. But this might be a bigger issue aside from that(or I'm completely missing something, haha).

#### Browser Information

Chromium | 60.0.3112.113 (Developer Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

#### Your Code

```js
function sumFibs(num) {
  if (num <= 1) {
    return 1;
  }
  return sumFibs(num - 1) + sumFibs(num - 2);
} 

sumFibs(4);
```

**Comment by Manish-Giri** [comment]
@username1001 you're using recursion, so shouldn't your base case be something like -
```
if (num === 0 || num === 1) {
  return 1;
}
```

**Comment by systimotic** [comment]
Hi @username1001! Nice username 😄

The live version of freeCodeCamp runs all the challenge tests on page load. One of the tests for this challenge uses `4000000` as the value for `num`. That's four million. Using your code, a _lot_ of function calls are made. So many in fact that it freezes the browser. Whoops 😅

We learned that automatically running the tests isn't always a great idea. 😄 In the beta, we're not doing that anymore. For the live site, you can disable it by adding `?run=disabled` to the URL. The following link should work https://www.freecodecamp.org/challenges/sum-all-odd-fibonacci-numbers?run=disabled Once there, you can't run your code, but if you change it changes will be saved. You can make the changes required to have it not freeze the page anymore and then go to the normal challenge URL again.

Hopefully that helps. I'm closing this issue, but if you still have problems after trying the above, feel free to add additional info and reopen. Happy coding!
