### ISSUE TITLE
Delete Project Euler Problem 22

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/freeCodeCamp#15831]
This problem does not work with the freeCodeCamp platform since the description says to use an external file. This is impossible with the platform. After consulting with @BerkeleyTrue & @QuincyLarson, it was decided to delete this challenge completely. This needs to be done.

**Comment by williamsb** [comment]
Does this involve just removing the problem from the project-euler-problems.json file?

**Comment by beaucarnes** [comment]
Yup! Pretty simple. Just delete the entire problem from project-euler-problems.json. Thanks for claiming this one.
