### ISSUE TITLE
Concatenating Strings with Plus Operator - space missing in instructions

### ISSUE THREAD

**Issue by sogen** [freeCodeCamp/freeCodeCamp#15836]
#### Challenge Name
Concatenating Strings with Plus Operator
https://www.freecodecamp.org/challenges/concatenating-strings-with-plus-operator

#### Issue Description

```
Instructions
Build myStr from the strings "This is the start. " and "This is the end." using the + operator.
````

Instruction above don't mention the space.
While the instructions below mention that it needs a space.

Notice that the next challenge (https://www.freecodecamp.org/challenges/concatenating-strings-with-the-plus-equals-operator) has the instructions about the space correct in both places.
 

#### Browser Information
Chrome 59 
OSX
Desktop

#### Your Code
Not working code:
`var myStr = "This is the start." + "This is the end.";`

Working code:
`var myStr = "This is the start." + " This is the end.";

#### Screenshot
![screen shot 2017-09-02 at 6 24 25 pm](https://user-images.githubusercontent.com/2784323/29999606-649906e4-900c-11e7-868f-878768b77219.png)

**Comment by zk433** [comment]
Hi @sogen ,
not sure what you mean? Both challenges have a note about the spaces, as far as I can see.

> Note
> Watch out for spaces. Concatenation does not add spaces between concatenated strings, so you'll need to add them yourself.

Also, as for the instructions for https://www.freecodecamp.org/challenges/concatenating-strings-with-plus-operator, space is already inserted in the string (after 'start. '):

> "This is the start. "

**Comment by systimotic** [comment]
Hi @sogen!

As @zk433 mentioned, this challenge does include the note warning about the spaces. Additionally, the first string in the instructions already ends in a space: `"This is the start. "` There's a space after the `.` there.

I'm closing this issue as resolved. If you think I'm wrong in closing this issue, please reopen it and add further clarification.

Happy coding!

**Comment by sogen** [comment]
+1
