### ISSUE TITLE
Bad UX on mobile devices

### ISSUE THREAD

**Issue by ooade** [freeCodeCamp/freeCodeCamp#15840]
I think it will be better to stack the grids on top of each other on mobile devices rather than having them side by side.

#### Screenshot

![bad ux](https://user-images.githubusercontent.com/11811904/30005921-db91e04e-90e4-11e7-8b81-fbb37ab0fad6.png)

**Comment by ooade** [comment]
I should take this. The first issue we have is the inline css used in styling the grids, maybe we can take it off and create a css file for it. Can we also make each grid a flexbox container? :sweat_smile:

**Comment by jimjja** [comment]
Is this issue still available? I can have a look at it.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
