### ISSUE TITLE
Please change all CodePen example projects to use projectName instead of project_name.

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/freeCodeCamp#15848]
#### Challenge Name
All CodePen challenges that use the [testable projects code](https://github.com/freeCodeCamp/testable-projects-fcc)

#### Issue Description
Over at https://github.com/freeCodeCamp/testable-projects-fcc we are cleaning up the code to make sure all ESLint warnings are fixed. We are finished, except for one variable name `project_name` that should be renamed to camel case. We need all of the CodePen example projects to make this change before we can finish the change in our file.

For example, you'll find the following at the top of the [D3 Tree Map Pen](https://codepen.io/freeCodeCamp/pen/KaNGNR)

```
const project_name="tree-map"
```

It should be changed to

```
const projectName="tree-map"
```

Note we have already changed the code on our side to accept either variable name. As soon as all the CodePens are changed to use the new name, we will delete the old name and our project will 100% pass all ESLint checks. At which point we can add the ESLint checking to our Travis CI build, and make sure all future PRs adhere to our coding standards.

If the maintainers of the individual CodePens can please let us know in the comments when they have changed their code, I will keep track of what has been finished and when we can make the change on our side.

Thanks in advance for your help on this.

#### Browser Information
N/A

#### Your Code
N/A

**Comment by tchaffee** [comment]
@QuincyLarson Could you please notify / assign the various maintainers of the official example CodePen projects?

**Comment by QuincyLarson** [comment]
@tchaffee Thanks for your patience. All of these projects should be forked and maintained in the freeCodeCamp CodePen account. @raisedadead has full access to it, and I can give you full access to it, too, if you want. We just need to be careful not to delete any existing projects in there because production references these.

**Comment by tchaffee** [comment]
@QuincyLarson I've tested the credentials you sent me and they work. So I'm happy to take this on now if someone wants to assign it to me. Just an FYI - I'm traveling for a couple of weeks starting tomorrow and I'm not sure when I'll get to this, but I definitely will.

**Comment by QuincyLarson** [comment]
@tchaffee Awesome! As long as the challenges all work currently, then you can take your time on this. You are definitely the best person to change this imho. Have fun and safe travels!

**Comment by tchaffee** [comment]
@QuincyLarson Just to confirm, the challenges do all work currently.

**Comment by QuincyLarson** [comment]
@tchaffee OK - thanks for confirming!

**Comment by tchaffee** [comment]
This is finished now. All the CodePens have been backed up and the variable name changed. The code in testable-projects has also been updated and everything is working.

**Comment by QuincyLarson** [comment]
@tchaffee Awesome! Congratulations on making all of these updates!
