### ISSUE TITLE
Code is not saved

### ISSUE THREAD

**Issue by charlottejoy** [freeCodeCamp/freeCodeCamp#15849]
#### Challenge Name
From the screenshots: Applied Visual Design: Create Visual Balance Using the text-align Property
http://beta.freecodecamp.com/en/challenges/applied-visual-design/create-visual-balance-using-the-textalign-property

First noticed with: Basic Algorithm Scripting: Finders Keepers
http://beta.freecodecamp.com/en/challenges/basic-algorithm-scripting/finders-keepers

Since I first saw it, I've tried it with other challenges. I see it for every challenge. 

#### Issue Description

I pass the test, I get the "Submit and go to next challenge". Clicking the button doesn't work, pressing Control+ Enter moves to the next challenge. In the bottom right I see "Your next challenge has arrived" and "Keep trying".
If I return to the precious challenge, my code is gone.

I tried a hard refresh as recommended, but it didn't help.

When I first saw this, I also noticed that the work area now had a white background. I think this was first about a month ago.

#### Browser Information

* Browser Name, Version: 
Chrome: Version 60.0.3112.113 (Official Build) (64-bit)
Safari:  Version 10.1.2 (12603.3.8)
* Operating System: 
OS X 10.12.6
* Mobile, Desktop, or Tablet: 
Desktop

I also tried the "Submit and go to next" button on Android 6.0 Chrome, but couldn't move forward. 

#### Screenshot

This button doesn't work for me.
![image](https://user-images.githubusercontent.com/17909419/30035228-ea9c5812-9175-11e7-83d9-690ccc9066ef.png)

Press Control+ Enter and I move forward, if I go back to that challenge, my work is gone.

![image](https://user-images.githubusercontent.com/17909419/30035232-f4e332e6-9175-11e7-897c-514cd408b531.png)

**Comment by adityaparab** [comment]
Thank you for reporting this. The issue of non functional click on challenge completion modal has already been [logged and closed](https://github.com/freeCodeCamp/freeCodeCamp/issues/15763) with [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/15834)

It looks like latest staging is not currently deployed.

I'll look into why the code is not retained issue.

**Comment by charlottejoy** [comment]
Thanks for the info and for looking into the second issue.

**Comment by QuincyLarson** [comment]
@adityaparab Awesome - thanks for helping with this. If the nonfunctional click hasn't been fixed, would you be interested in fixing it? 

When this is working, we can ask @BerkeleyTrue to deploy the fix and close this issue.

**Comment by adityaparab** [comment]
@QuincyLarson : the non functional issue is already fixed and merged. It can be deployed.

I'm looking into another issue where the code is not retained in the db after submission:

**Comment by ogzcoder** [comment]
I was looking into this a little bit and it seemed that the data is stored in the db but not returned when the camper returns to the challenge. I'd like to give this a shot if that's ok?

**Comment by adityaparab** [comment]
@ogzcoder : You're right, the data is getting saved on my end as well.. It is not being returned.
I'm done with my changes to fix this and will be submitting a PR soon.
Would you consider looking into another issue? :)

**Comment by ogzcoder** [comment]
@adityaparab : surely will :)

**Comment by QuincyLarson** [comment]
@adityaparab Have you made any progress on this? Let me know if I can be of any help here. Thanks for helping fix this.

**Comment by adityaparab** [comment]
@QuincyLarson PR coming up this weekend. :) Sorry I have unreliable internet access during travel.

**Comment by QuincyLarson** [comment]
@adityaparab No worries. Thanks for keeping us posted.

**Comment by BerkeleyTrue** [comment]
Is this still an issue for @charlottejoy ?

**Comment by ogzcoder** [comment]
I am still willing to work on this if @adityaparab never found a fix

**Comment by adityaparab** [comment]
@ogzcoder: sure go ahead. I’m not finding enough time from my work schedule to work on my open source ventures.

I already have code fix for this. Let me know if you want it, I’ll share it soon here.

**Comment by QuincyLarson** [comment]
@ogzcoder Thanks for looking into this. Please keep us posted and open a pull request when your fix is ready. Let us know if we can do anything to help :)

**Comment by charlottejoy** [comment]
I've tried it on mobile (Chrome, Android 6.0.1) and laptop in Chrome. I'm able to click the button to continue. Back button shows saved work. So it seems that it is working for me.

**Comment by adityaparab** [comment]
@charlottejoy: clicking back buttons pulls up page from local browser cache. The problem comes up when you directly jump to a problem that you have already solved.
Instead of clicking back, try pasting the same url in a new tab. The code disappears

**Comment by charlottejoy** [comment]
Thanks @adityaparab. 
I've done as you've suggested. I do see my saved code when pasting the challenge link into a new tab in the same browser or going to a new tab and clicking on the challenge. I assume the challenge has no check-mark because there's no more beta login, but my code is there for me in Chrome and Firefox. 
Perhaps the issue is solved, or I'm not clear on this part of the issue. For me, it doesn't seem I'm experiencing what I initially described.
In either case, thanks people for looking into this! It's really a wonderful thing!

**Comment by Bouncey** [comment]
Closing as resolved in staging
