### ISSUE TITLE
Verifying email address on a new account should sign user in as well

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15854]
Currently when verifying an email, it forces the user to sign in again. We should instead sign the user in.

![sign_in_to_freecodecamp_using_your_email_address___freecodecamp](https://user-images.githubusercontent.com/985197/30094220-5fcb0730-9290-11e7-85cd-287cd1397b22.png)

We are looking for a contributor who can implement this fix on both on the staging branch and on backup/master (our production branch).

**Comment by adityaparab** [comment]
me!

**Comment by Esslamb** [comment]
Will attempt to add this feature!

**Comment by QuincyLarson** [comment]
@Esslamb Awesome! Since @adityaparab is already tackling a few other issues, we would welcome your help with this. Have you managed to get freeCodeCamp running on your local computer yet?

**Comment by Esslamb** [comment]
Hi @QuincyLarson sorry for not posting an update, I actually got hung up on making my personal portfolio into a PWA. It's very interesting/distracting stuff.  I did actually get freeCodeCamp running, was going in blind as I'm on Ubuntu but it was easy enough. In terms of a fix I actually wanted to ask if you had a preferred method or suggested way to fix it. Keep in mind this is my first time pulling the repo so I don't know what the confirm email logic looks like but I can probably come up with something.

**Comment by ryanbsherrill** [comment]
Hey @QuincyLarson and @Esslamb Would like to assist if there's anything I can do on this.

**Comment by QuincyLarson** [comment]
@Esslamb Have you had a chance to look into this? Note that you'll have to fork off of the backup/master branch. 

If you need help, but @ryanbsherrill and I are here on this thread to answer questions - just keep us posted :)

**Comment by Esslamb** [comment]
No update as of yet, I dropped a reply 6 days ago asking if you had a preferred method on how you wanted me to deal with it? But I guess I will just use my initiative. 👍

**Comment by QuincyLarson** [comment]
@Esslamb I think this will be handled entirely in the controllers. Instead of sending campers to the signin page, the URL itself should sign them in and redirect them to the first challenge. Let me know if I can be of further help with this.

**Comment by raisedadead** [comment]
@QuincyLarson this wont be trivial to implement on production. I am listing the flow that is needed in our production setup for anyone attempting this:

- When user requests an email verification, a verification token is created.
- This verification token is stored on User model.
- The verification token is used is used to hit a endpoint which is directly exposed by LoopBack to update the user model, that email is verified.
- This also invalidates, the verification token.
- Currently, as you have noticed, it does not login the user.
- We need to add handlers, that in addition to updating the user model, should create a access token with a login TTL.
- The access token is to be stored on AccessToken model.
- The access token is then used to create a Session object and set a session cookie in the response.
- We also should note, this should also take care to invalidate an existing session and access tokens, should the user is logged in already.

In beta, with passwordless we have manage to simplify this.

The conclusion being, its possible to implement just not very trivial, with mechanism that we have in place on production.

Please feel free to drop any additional queries should this be not clear.

**Comment by QuincyLarson** [comment]
@raisedadead Thanks for the detailed explanation. 

OK - if this is already handled in beta, and if it would be complicated to implement in production, then I agree that we should just leave it as-is for now.
