### ISSUE TITLE
Camperbot is offline - Not giving out cookies/brownies

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#15857]
#### Issue Description

Camperbot since the database issue has been offline. It is not assigning brownie points in Gitter Chat. 
cbot status says the api is online but when thanking someone it comes back with api offline.
screenshot below
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/30172328-8c3f5644-93c2-11e7-9c2f-dcc0481e63b3.png)

**Comment by mstellaluna** [comment]
camperbot is still having issues, it works okay on the 1st thanks and then on the second thanks it crashes again with the api offline if the 2nd thanks quickly follows the other. Screenshots below :) 

![image](https://user-images.githubusercontent.com/22984739/30180703-c92843ce-93de-11e7-9df2-037c6bbf1825.png)
![image](https://user-images.githubusercontent.com/22984739/30180715-d2d342ca-93de-11e7-8123-3f0ac7be3a03.png)

**Comment by BerkeleyTrue** [comment]
@mstellaluna Thanks for the notification. It is still working, it's just that trying to send two thanks to the same person hits a rate limit and will respond with an error.

Generally the server responds with JSON but I think the way our error messages are now handled are catching message through the API that should be sent directly to the client. I'll need to fix this in our codebase.

**Comment by mstellaluna** [comment]
@BerkeleyTrue Yea, I wasn't sure if this was something you wanted to be aware of as its wasn't the behavior before the database issues, it would have normally returned something along the lines of "texas2010 already gave points to mstellaluna" . Yes, campers are getting their cookies.

**Comment by mstellaluna** [comment]
It's intermittent this just happened it was the first cookie, the chat is quiet right now so I haven't seen it happen in the other room aside from the main room. The time is EST btw.

![image](https://user-images.githubusercontent.com/22984739/30186965-bf5827bc-93f5-11e7-8789-d21f824c4cd9.png)

**Comment by QuincyLarson** [comment]
@mstellaluna Thanks for reporting this. I noticed this as well. 

@BerkeleyTrue shipping the beta platform is a much higher priority - can you think of a quick fix for this for now?

**Comment by systimotic** [comment]
I think #15861 should close this

**Comment by BerkeleyTrue** [comment]
This should now be fixed
