### ISSUE TITLE
Beta Version: 'No Super Blocks' Error on opening challenges

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#15851]
**Issue Description**

On opening https://beta.freecodecamp.com/en/map - A error/message/log - 'No Super Blocks' for a very short duration of time like for 3-5 seconds is seen. After those few seconds the challenges come up.

**Browser Information**

* Browser Name, Version: Google Chrome, Latest release 
* Operating System: Windows 10 pro
* Mobile, Desktop, or Tablet: Desktop

**Screenshot**
 
This only comes up for few seconds. It should be resolved as it confuses campers. 

![Image](https://i.imgur.com/3kpJCaK.png)

**Comment by systimotic** [comment]
Hi @vkWeb, thanks for reporting this issue!
I absolutely agree, this is quite annoying. We have two open issues that should address this: https://github.com/freeCodeCamp/freeCodeCamp/issues/15696 and https://github.com/freeCodeCamp/freeCodeCamp/issues/15730, so I'm closing this as a duplicate.

Happy coding!
