### ISSUE TITLE
GitHub account linking is broken

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15855]
Several campers have reported this, and I tried to update my own account from GitHub and experienced this error message:

![settings___freecodecamp](https://user-images.githubusercontent.com/985197/30134546-1b521804-931d-11e7-983a-d243ee2174b9.png)

**Comment by scrabill** [comment]
From the settings page, clicking Update my profile on Github does not give me an error, but I am redirected to www.freecodecamp.org/map. Is this the same error you are referring too?

**Comment by BerkeleyTrue** [comment]
This has been fixed. Happy Coding
