### ISSUE TITLE
Updating profile from GitHub should redirect to profile with flash message

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15859]
Currently when a user successfully updates their profile from GitHub, the platform just sends them back to their current challenge. Instead, it should redirect them to their updated profile with a green flash message: "We have successfully updated your freeCodeCamp profile using information from your GitHub profile."

**Comment by fumblehool** [comment]
@BerkeleyTrue I would like to contribute to this issue but I would require your guidance.

**Comment by martindavid** [comment]
@QuincyLarson @BerkeleyTrue anyone working on this? @fumblehool have you started working on this? If you haven't, I'd like to take this one.

**Comment by QuincyLarson** [comment]
@martindavid This is a production issue, and it should be fixed in beta. So I'm going to close this issue and we can focus on beta issues. We would welcome your help on other issues :)
