### ISSUE TITLE
Beta - Basic Javascript - Modifying Data with Indexes - Typos

### ISSUE THREAD

**Issue by sonorangirl** [FreeCodeCamp/FreeCodeCamp#1585]
Challenge http://beta.freecodecamp.com/challenges/modifying-data-with-indexes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

<img width="347" alt="screen shot 2015-08-05 at 5 24 22 pm" src="https://cloud.githubusercontent.com/assets/6051437/9101056/d8f88748-3b96-11e5-9876-a07a1647bbe1.png">

Just a few typos, I think it should probably say "We are able to modify the data store**d** in an array b**y** using indexes"

**Comment by sonorangirl** [comment]
Also the next challenge #20 - Manipulating Arrays has some typos:

<img width="352" alt="screen shot 2015-08-05 at 5 40 28 pm" src="https://cloud.githubusercontent.com/assets/6051437/9101242/3cfb5886-3b99-11e5-8135-3d1d69d04776.png">

In the first sentence I believe it should be 'When **an** array', not 'When and array'.

In third paragraph 'performing' is spelled incorrectly.

In the fourth paragraph the first word should be capitalized and the end of the sentence should probably be '**an** array', not 'and array'.

**Comment by sonorangirl** [comment]
Whoops, sorry, new to this.

**Comment by sonorangirl** [comment]
Sorry I sound like a grammar nazi, just trying to help. I found another typo in the Basic Javascript challenges-
<img width="348" alt="screen shot 2015-08-05 at 6 20 52 pm" src="https://cloud.githubusercontent.com/assets/6051437/9101685/c6263176-3b9e-11e5-8d6e-5da23a0f7da4.png">

I think the second sentence was meant to say "Here's an example of a function" not 'here's and example'.

Also, the third sentence isn't capitalized.

I hope it's ok that I'm putting all these typos I'm finding for the Javascript challenges in the same issue thread, didn't want to create a whole bunch of open issues for them if you might have found them already.

**Comment by sonorangirl** [comment]
And another in Basic Javascript #25 I Object - I searched and found the first typo had been fixed by a camper, but there's another in the last paragraph:
<img width="350" alt="screen shot 2015-08-05 at 6 40 42 pm" src="https://cloud.githubusercontent.com/assets/6051437/9101904/833a9a66-3ba1-11e5-8c3b-372a5f4ebb1d.png">

I think it should be "Let's try to make **an** Object that represents a dog called myDog!"

**Comment by BerkeleyTrue** [comment]
Is this still
