### ISSUE TITLE
[Bug] "Applied Visual Design: Change an Element's Relative Position" challenge in Beta curriculum does not work

### ISSUE THREAD

**Issue by yrahul3910** [freeCodeCamp/freeCodeCamp#15868]
#### Challenge Name
[Applied Visual Design: Change an Element's Relative Position](https://beta.freecodecamp.org/en/challenges/applied-visual-design/change-an-elements-relative-position)

#### Issue Description
The correct solution isn't accepted, giving the output:
```
// running test
"message: The h2 element should have a position property set to relative."
"b is null"
// tests completed
```

#### Browser Information

* Browser Name, Version: Firefox Nightly 57.0a1 (2017-09-08) 64-bit
* Operating System: Debian GNU/Linux 9.3, 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```
<style>
  h2 {
    position: relative;
    top: 15px;    
  }
</style>
<body>
  <h1>On Being Well-Positioned</h1>
  <h2>Move me!</h2>
  <p>I still think the h2 is where it normally sits.</p>
</body>
```

### Additional Information
The "Bug" button to report an issue also doesn't work on that page. I've tried refreshing, but the issue persists.

**Comment by vkWeb** [comment]
@yrahul3910 I tried to reproduce the error but I was unable to do so. I think it's a browser specific error(the beta version is highly unstable with Edge), have you tried the challenge in any other browser?     

![](https://i.imgur.com/GjrphmT.png)
*Tested on Opera latest release.*

**Comment by yrahul3910** [comment]
I've tried and had the same issue on Firefox 54.0.1 32-bit (stable) running on Windows 7. And yes, it gets stuck on `// running test` in Edge. Sigh.

**Comment by yrahul3910** [comment]
It works on Chromium too (kinda obvious since it works on Opera I guess). I'm not sure if this is a bug with other browsers or with FCC's beta.

**Comment by systimotic** [comment]
Thanks for reporting this issue and looking into it @yrahul3910 @vkWeb!

This is a known issue we had with CSS tests in Firefox. This has been fixed recently with https://github.com/freeCodeCamp/freeCodeCamp/pull/15775
This change isn't on the beta site yet, but I can confirm that this work fine on the latest staging. Hopefully it'll go up soon!

I'm closing this as resolved. Happy coding!
