### ISSUE TITLE
Solutions to Challenges disappeared from "Map" topbar menu. But present in User Profile page. Then re-appeared again in Map menu.

### ISSUE THREAD

**Issue by fivefishstudios** [freeCodeCamp/freeCodeCamp#15864]
I encountered a bug where my code solutions to the challenges disappeared on my account when accessed/viewed using the "Map" topbar menu option. The Challenge looks like it has never been touched. The code window is in its original state. So therefore, all the tests were also failing. 

But clicking on the same Challenge from the User Profile page shows that my code solutions are still there. And that all tests passes. 

And here comes the weird part... after I've viewed the Challenge using the User Profile menu links, and then go back to the "Map" topbar menu and click the same Challenge, my solution is now showing and also passing the test. 

I cannot tell you though when exactly this behavior started. All I know is one day I visit FCC, and it prompted me to login again (even though I never logged out of it). I login back (and I'm only using one authorization method) and that's where I noticed my Challenge answers/code are empty. 

https://image.ibb.co/mbqfYa/map_ns.png

From the "Map" menu, as you can see, the Challenge was answered previously and submitted indicated by the checkmark. 

https://image.ibb.co/hiZURv/map_sol.png

But code window shows solution is empty. There is a green checkmark though on the Challenge. All Tests also fail, since there is no new code in the code window. 

https://image.ibb.co/eFRb6v/profile_1.png

Accessing the same Challenge from the User Profile page, and clicking "View solution" shows my code/answer to the Challenge.

https://image.ibb.co/hioCeF/profile_sol.png

And all tests passes...

Now, when I go back to the Map menu, and access the same Challenge again, my solution now appears, my code is there, and all tests Pass.

**Comment by ananaymital** [comment]
I made this [Youtube Video](https://youtu.be/96nxsZLBmF0) in case someone was not able the issue here.

**Comment by vkWeb** [comment]
@systimotic This issue has been fixed with the help of @ananaymital. @fivefishstudios If the issue persists after following the video then please reply. 

@systimotic @Bouncey @QuincyLarson  This issue can be closed as it's been resolved.

**Comment by fivefishstudios** [comment]
@ananaymital  made the video showing the problem (I only made screenshots). 

I tried logging out and logging in again, the issue is still the same.  I have to load the solutions using the User Profile page so the "Map" menu will show the correct submitted solution (instead of the original, unanswered code). 

I think this problem started when I changed some security settings on my browser, and Local Storage got cleared. -- and I think that's why "Map" menu are showing blank/unanswered solutions... the submitted solution doesn't get reloaded until the same challenge question is viewed using the User Profile page.

**Comment by QuincyLarson** [comment]
@fivefishstudios Can you do a hard refresh, then try again?

**Comment by QuincyLarson** [comment]
@fivefishstudios Thanks for your patience, and for creating that video.That's a great way to record the steps to reduce a bug.

We are planning to move all of this functionality out of local storage, and only store the current challenge campers are working on in their local storage. The only reason we do this at all is to prevent campers from losing their work on a given challenge if they accidentally close the tab or navigate away before submitting it.

So I think we will label this "wont fix" for now since we're changing this in the near future anyway.
