### ISSUE TITLE
[Beta]Stock Price Checker project

### ISSUE THREAD

**Issue by rmonastra** [freeCodeCamp/freeCodeCamp#15863]
Hello,
I'm working on the stock price checker project.  The url to get stock prices doesn't work anymore.  I've found a Quandl npm, working with it at the moment.  I was wondering if this project will stay as is with the url not working anymore.

**Comment by erictleung** [comment]
@rmonastra thanks for the issue. I'm assuming the URL you're referring to is https://giant-chronometer.glitch.me/? If so, I can confirm it appears to not be working anymore, unless I'm using it wrong.

cc/ @freeCodeCamp/moderators

**Comment by rmonastra** [comment]
@erictleung, the url is: _https://finance.google.com/finance/info?q=NASDAQ%3a + stock(GOOG,INTC, etc)_.  Google and Yahoo have stop supporting these APIs.  I've found 2 free APIs, Quandl and Alpha Vantage but they don't let you call multiple stock symbols unless you download the report.

**Comment by QuincyLarson** [comment]
@rmonastra Thanks for letting us know. Can you see if you can find a good API that will let you call multiple stock symbols?

If it requires an API key, we could build a Glitch.com pass-through app, like we did with the Local Weather app's API.

**Comment by rmonastra** [comment]
@QuincyLarson, I'll continue looking for an good free API(with or without an API key) for stock prices.  In the event one can't be found, I was wondering if another subject besides stocks can be used.  I haven't looked into different subjects yet.  If I can find a subject that works similar, I'll post those API for a backup.

**Comment by QuincyLarson** [comment]
@rmonastra We've already replaced this project in our beta curriculum. It is now optional there. But it would still be nice to have a good recommended API for this, if you can find one. My advice would be to continue looking, and if you think you've exhausted the likelihood of reasonably finding one, you can close this issue.

Either way, thanks for all your help with this.

**Comment by brusbilis** [comment]
Free api with real time 
[https://iextrading.com/developer/docs/](https://iextrading.com/developer/docs/)

I am using for this [sp500 realtime dashboard](https://codetabs.com/stock-market/sp500.html) and works very well.
You can call multiple symbols (i call 505 symbols in one request)

**Comment by hsribei** [comment]
@QuincyLarson I'm following the beta curriculum and also ran into the problem of the Google Finance API being deprecated.

The [beta website](https://beta.freecodecamp.org/en/challenges/information-security-and-quality-assurance-projects/stock-price-checker) doesn't say anything about this project having become optional though, nor of a replacement for it. Am I looking at the wrong place? Thanks!

**Comment by hsribei** [comment]
Btw for others trying to complete it, I've found the [AlphaVantage](https://www.alphavantage.co) API works, although it's often offline.
