### ISSUE TITLE
Missing text in advice window

### ISSUE THREAD

**Issue by garysmeade** [FreeCodeCamp/FreeCodeCamp#1586]
Challenge http://beta.freecodecamp.com/challenges/waypoint-override-class-declarations-with-inline-styles has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The advice window should have "color: white" but stops short at "color - see screenshot.

![image](https://cloud.githubusercontent.com/assets/13364192/9101342/f0a94a02-3c28-11e5-83d5-58c3e054beb0.png)

**Comment by cristianvnica** [comment]
Also when we are about to fill in the style we get this error which can be confusing for beginners: 
<img width="743" alt="screen shot 2015-08-06 at 11 59 02 am" src="https://cloud.githubusercontent.com/assets/3229023/9107812/ea5915d8-3c32-11e5-9173-1980b4c1905e.png">

**Comment by benschenker** [comment]
This is fixed
