### ISSUE TITLE
Update settings buttons

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15860]
This block of buttons at the top of freeCodeCamp.org/settings needs to be updated:

![settings___freecodecamp](https://user-images.githubusercontent.com/985197/30176649-da90973a-93c8-11e7-97fa-4385620ee9e0.png)

Since this links to a forum post explaining how to create a GitHub account, the button should instead say "Learn how to customize my public profile"

Also, since we've removed the "check out YouTube channel" challenge from the map, we should add a button that says "Watch hundreds of coding videos" and links to https://www.youtube.com/freeCodeCamp

Note that this is a fix for www.freecodecamp.org (not beta.freecodecamp.org) so you will need to branch off of the backup/master branch.

**Comment by aharcourt** [comment]
This is my first time getting started with open source software. Can I work on this?

**Comment by addisonday** [comment]
This would be my first time as well, but I am interested.

**Comment by vkWeb** [comment]
I am a first-timer and I would love to contribute to this community. I am helping people through FCC's Fb group and other possible ways.

**Comment by ddeason37** [comment]
Hey Quincy - would like to give a try on this one, would be my first open source contribution

**Comment by Astroknut** [comment]
@QuincyLarson I am looking for ways to make my first contribution and would love to have a go at this

**Comment by GComputeNerd** [comment]
Hello, I have been use open source software alot and would love to give back to the community. I help out in forums a lot of the time, but this would be the first time helping out by writing code instead of just fixing code.

**Comment by QuincyLarson** [comment]
Thanks everyone for commenting on this. I just now saw these comments. @aharcourt since you were the first person to respond to this, are you still interested? If so, please write back as in the next 24 hours. Otherwise I will release this to another potential contributor.

**Comment by Georgeyoo** [comment]
Hello! I was just browsing through issues in this repo and ran into this. I'd very much like to go ahead and make these changes!

**Comment by shovanch** [comment]
@QuincyLarson Hi, I am new to the open source community. Looking to make my first contribution. Would like to give a try on this.

**Comment by QuincyLarson** [comment]
OK @Georgeyoo, can you confirm whether you're able to work on this? If so, you can have it. If not, we can let @shovanch tackle it.

**Comment by Georgeyoo** [comment]
@QuincyLarson Confirmed. I will get it done!

**Comment by QuincyLarson** [comment]
@Georgeyoo Awesome - thanks for your fast response 😄  Let me know if I can do anything to help.

**Comment by joncancode** [comment]
@QuincyLarson I'd also love to work on this, but will definitely wait in line for those before me.

**Comment by pranavchauthaiwale** [comment]
Hi @QuincyLarson . I would love to contribute to this project. This is my first contribution to open source community. Please let me know what I can do to help. 
Many Thanks.

**Comment by RohitNethi** [comment]
@QuincyLarson I would love to contribute to this too. Will keep a look out for future issues.

**Comment by omerharshit** [comment]
This is my first time in github open source and i am finding that open source community contribution very useful.

**Comment by manohar566** [comment]
I wish I was assigned. @QuincyLarson

**Comment by caspervonb** [comment]
#15884

**Comment by aguscha333** [comment]
Why has this been opened again? Does this mean that the issue still needs fixing? if so I would love to help.

**Comment by Georgeyoo** [comment]
@aguscha333 My apologies for it being a little confusing! I closed #15884 due to a poorly written commit message and differing npm version

**Comment by QuincyLarson** [comment]
@Georgeyoo Thanks again for fixing this! I'm closing this issue.
