### ISSUE TITLE
Misleading direction in Reuse Patterns Using Capture Groups

### ISSUE THREAD

**Issue by addisonday** [freeCodeCamp/freeCodeCamp#15862]
#### Challenge Name
Reuse Patterns Using Capture Groups
https://beta.freecodecamp.org/en/challenges/regular-expressions/reuse-patterns-using-capture-groups

#### Issue Description
The directions state:
Use capture groups in reRegex to match numbers that are repeated only three times in a string, each **separated by a space.**
One of the tests states:
Your regex **should have two spaces** separating the three numbers.

Plain and simple, it says to do one thing, but checks for something else. 
#### Browser Information

* Chrome, 60.0.3112.113: 
* Windows 10 
* Desktop 

#### Screenshot

![contradictingdirection](https://user-images.githubusercontent.com/27864378/30198469-bd6317e6-9422-11e7-9584-2e2490ced467.PNG)

**Comment by addisonday** [comment]
I'm interested in contributing and taking care of this myself if that is possible

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
