### ISSUE TITLE
Logging In Takes Me To Someone Else's Account

### ISSUE THREAD

**Issue by brockt** [freeCodeCamp/freeCodeCamp#15869]
#### Issue Description

I recently reset my password (it had been over a year since I had last logged in) and logged in to my account; however, it is not my account that I have access to. It belongs to someone else. 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by texas2010** [comment]
@brockt I have to remove your email for the safety reason in the issue Description.  
More like it is your account since you log in your account with your email address. so it is not error or mistake in the database.
