### ISSUE TITLE
location provided by freecodecamp API is not correct everytime.

### ISSUE THREAD

**Issue by AshishkrGoyal** [freeCodeCamp/freeCodeCamp#15871]
freecodecamp weather API is not showing correct location i.e. city using latitude and longitude of user.
sometimes it is correct but many times it shows wrong location.

Thanks

**Comment by rmonastra** [comment]
Go to a site that checks your IP address, make sure it provides a location for you.  I ran into this problem and it was the ISP.  My ip address was coming from servers a few cities away.  Also, it could be some kind of security software you're running.

**Comment by AshishkrGoyal** [comment]
@rmonastra 
what is the use of ip address in API while we are providing longitude and latitude for finding our location??

i think your solution will not work for me !!

Thanks 😄

**Comment by rmonastra** [comment]
Where are you getting the longitude and latitude?  Do you have fields where you can put in longitude and latitude?  This is my code to get longitude and latitude:
 
$.getJSON("http://ip-api.com/json", function(data2) {
      lat = data2.lat;
      long = data2.lon;
      console.log(long);
      console.log(lat);

If you go to http://ip-api.com/ it will show you the location of the device you're on.  When you get a different location, check that website to see if locations match.

**Comment by vkWeb** [comment]
@AshishkrGoyal Actually many users have complained about freecodecamp's weather API. If it doesn't work well for you. You can try any of these, they all are pretty accurate:-
- [Open Weather API](https://openweathermap.org)
- [AccuWeather API](https://www.accuweather.com)
- [DarkSky API](https://darksky.net)

@systimotic, @QuincyLarson @Bouncey This issue can be closed now.

**Comment by QuincyLarson** [comment]
@vkWeb OK - I will close this issue. Rather than recommending other APIs (which unlike the one we set up, require API keys) we should try to fix any outstanding issues with our API. Could you open issues for specific problems with the API that you think needs to be fixed?

**Comment by vkWeb** [comment]
@QuincyLarson I'll surely open an issue about the fixes needed in the API to work accurately.
