### ISSUE TITLE
Add a "Delete all of my solutions" button to /settings

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#15870]
One of the most common support questions we get is: "I stopped doing freeCodeCamp a few months ago, and now I'm back. How can I erase all my solutions and start over from the beginning?"

Here is [our advice to campers when they encounter this situation](https://forum.freecodecamp.org/t/how-to-reset-your-progress-and-clear-your-solutions/146222).

We would like to add a "Delete all of my solutions" button to the "danger zone" section of the /settings page. Just like with the "Delete my account" this button would pop up a modal with the following text:

> Are you 100% sure that you want to delete all of your solutions?
> This will really delete all of your solutions, including your brownie points. It will also clear all the solutions that are saved in your browser's local storage.
> We won't be able to recover any of this for later for you, even if you change your mind.
> Nevermind, I don't want to delete all of my solutions
> I am 100% sure I want to delete all of my solutions

For reference, this is what our "delete my account" modal looks like:

![settings___freecodecamp](https://user-images.githubusercontent.com/985197/30244609-404ef386-9587-11e7-9bc5-4ea2d8d7871d.png)

As with anything that deletes data, we want to be super careful with this. If you can add tests (for example, creating a user object, then deleting part of it and verifying that the rest of the object is still intact) that would be preferable.

**Comment by Aj1402** [comment]
I would like to work on this issue, hoping to add it asap!

**Comment by shovanch** [comment]
@QuincyLarson Would love to give a try on this one. This would be my first contribution

**Comment by QuincyLarson** [comment]
@Aj1402 Awesome! Have you been able to get the freeCodeCamp codebase running on your local computer? Let me know if you have any questions.

**Comment by QuincyLarson** [comment]
@shovanch wow - you commented right at the exact moment I did. Yes - if you want to take a look at it too, you can.

**Comment by shovanch** [comment]
Cool. Working on it.

**Comment by shovanch** [comment]
@QuincyLarson Is it only needed to add the button with modal? Does the button have to perform the actual deleting action from database?

**Comment by omerharshit** [comment]
This would be my first open source project contribution . Can i work on this issue.

**Comment by shovanch** [comment]
@QuincyLarson Just a question, Is it only needed to create the button or the button must also perform the delete action from database?

**Comment by adityaparab** [comment]
@shovanch : of course, the button needs to perform delete operation on the user's model in the db.

It should happen in following steps
1) user clicks button to clear their progress
2) confirmation modal is shown
3) in confirmation, the API call is to be made to backend, that will reset property called "challengesMap" on user model. (Although I'm not sure if the property name is correct)

**Comment by QuincyLarson** [comment]
@shovanch Yes - what @adityaparab said. 

It should completely clear `completedChallenges` and all of the challenge-related objects in `progressTimestamps` so that the user object is as though it was just created, though all the non-challenge related objects in `progressTimestamps` should still be intact. As should any other attributes, like their username and bio.

**Comment by shovanch** [comment]
@QuincyLarson @adityaparab Got it. Hoping to give status update ASAP.

**Comment by shovanch** [comment]
@QuincyLarson @adityaparab Understood. Hoping to give status update ASAP

**Comment by shovanch** [comment]
@QuincyLarson @adityaparab Thanks for the explanation. Hoping to give status update ASAP

**Comment by QuincyLarson** [comment]
@shovanch Sure thing. Please let me know if I can be of further help. Thanks for helping implement this!

**Comment by shovanch** [comment]
@QuincyLarson I have been working on this. But unable to make any progress. Quite new to Mongo and Node. Probably need to learn them more. Would love to contribute on future issues. Thanks for the opportunity.
If anyone wants to work on this one, feel free to do so.

**Comment by ltegman** [comment]
Sorry if this is a stupid question, but it looks like this functionality already exists in the beta. Is this item for adding similar functionality to the production site without waiting for the beta to be released?

**Comment by shubhshrma** [comment]
I'd love to work on implementing this button as @shovanch has left.

**Comment by meetzaveri** [comment]
Here's my point on deleting selected areas on user's query :
1. Deleting only beginner projects/challenges
2. Deleting only intermediate projects/challenges
3. Deleting only advanced projects/challenges
4. Deleting algorithms based on beginner/intermedaite/advanced
5. Deleting whole backend development progress and certification
6. Deleting whole frontend development progress and certification
7. Deleting whole data-visualization progress and certification

Apology if this analysis I have issued is inappropriate or previously closed.

**Comment by shubhshrma** [comment]
@QuincyLarson does this need to target ```backup/master``` or ```staging``` ? Thanks.

**Comment by Spidy88** [comment]
Is this issue still open? I see that the button does exist, a modal does appear, and the server seems to be performing an operation on modal confirmation. @QuincyLarson

**Comment by QuincyLarson** [comment]
@shubhshrma @meetzaveri @shovanch as @ltegman pointed out, this functionality already exists in beta. I wasn't aware of this fact when I opened this issue. We are getting closer to releasing beta, so I think this functionality can wait until then. So I'm closing this issue. 

Thanks anyway everyone for your help!
