### ISSUE TITLE
Moving on produces a 502 Bad Gateway error

### ISSUE THREAD

**Issue by kurzninja** [FreeCodeCamp/freecodecamp#1587]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element has an issue.

Solving this bonfire and attempting to move on produces a 502 Bad Gateway error.

**Comment by BerkeleyTrue** [comment]
Hello @kurzninja 

This is a duplicate of #1386 

Happy Coding!

-Berkosaurus
