### ISSUE TITLE
Beta - Basic Javascript - #27 - Looping with For

### ISSUE THREAD

**Issue by sonorangirl** [FreeCodeCamp/FreeCodeCamp#1588]
Challenge http://beta.freecodecamp.com/challenges/looping-with-for has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The challenge wouldn't accept my for loop when I first tried: 
<img width="761" alt="screen shot 2015-08-05 at 7 29 38 pm" src="https://cloud.githubusercontent.com/assets/6051437/9102551/94f5c60c-3ba8-11e5-8abf-5549e75ad0eb.png">

I realized it was failing because of the spaces I was adding in the for loop, which I added because I understand it better when it's not all joined together, but I thought that most of the time spaces didn't matter in javascript? Shouldn't it still work with the spaces there? Or do the spaces matter?

...Also there's something wrong or missing from the instructions:
<img width="346" alt="screen shot 2015-08-05 at 7 29 51 pm" src="https://cloud.githubusercontent.com/assets/6051437/9102635/7754c9f8-3ba9-11e5-8098-e07dd2e3d33d.png">

Seems like you deleted something in the middle.

**Comment by sonorangirl** [comment]
The same problems also happen in the next challenge #28 Looping with While

**Comment by benschenker** [comment]
Closing as stale, this seems to have been fixed
