### ISSUE TITLE
The issue to updating my e-mail

### ISSUE THREAD

**Issue by WebTeenager** [freeCodeCamp/freeCodeCamp#15888]
#### Issue Description

I want to update my e-mail but when I typing new e-mail address I see the following answer (on the screen below).
There is no text on the blue line. I can only close this page or “Go back to Settings”.
New mail box is empty (spam list too).
Can you help me?

#### Browser Information

Using freecodecamp.org (not beta.freecodecamp.org)
* Browser Name, Version:  Google Chrome Version 60.0.3112.113 x64
* Operating System: Windows 10 x64 
* Mobile, Desktop, or Tablet:  Desktop

#### Screenshot

![9b7ed8fb304afc9241250e5c4a88f14b2df065dc](https://user-images.githubusercontent.com/21991301/30514476-c2dc08ca-9b1d-11e7-9c86-891612160944.png)

**Comment by raisedadead** [comment]
Duplicate issue of https://github.com/freeCodeCamp/freeCodeCamp/issues/15876
