### ISSUE TITLE
[Beta] Content overflows when width <= 1030

### ISSUE THREAD

**Issue by iam13islucky** [freeCodeCamp/freeCodeCamp#15885]
#### Challenge Name

All API and Microservice parts except for the introductions

#### Issue Description

When the width of the browser is less than 1031px, the text overflows off either side when viewing an API challange. This occurs regardless of if the map is open as well.

To reproduce, resize your browser while viewing one of the API challenges on beta.freecodecamp.com.

#### Browser Information

* Browser Name, Version: Chrome 60.0.3112.113
* Operating System: Windows 10 Pro 64bit
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![screenshot 1](https://user-images.githubusercontent.com/4074135/30442572-193a6f12-993a-11e7-8f00-9ed3e1d254c9.png)
![screenshot 2](https://user-images.githubusercontent.com/4074135/30442642-40bf3a22-993a-11e7-91cb-866028f3852c.png)

**Comment by bonebizz21** [comment]
Maybe this will help

**Comment by iam13islucky** [comment]
What do you mean? Maybe what will help?

**Comment by honmanyau** [comment]
If I'm not mistaken this has already been addressed with #15022.

**Comment by iam13islucky** [comment]
Very well might have, I didn't see that. But, if it was, it still isn't pushed onto the beta site.

**Comment by systimotic** [comment]
Thanks for reporting this issue @iam13islucky!

Good catch @honmanyau! This issue is indeed present in the beta, but I just checked, and it has been resolved in staging, so I'm closing this issue.

Happy coding!
