### ISSUE TITLE
Couldn't get acces to freecodecamp.org

### ISSUE THREAD

**Issue by zglrx99** [freeCodeCamp/freeCodeCamp#15900]
Hello,

I couldn't visit freecodecamp because of bad gateway 502 error.
![image](https://user-images.githubusercontent.com/25727023/30566178-9d258108-9cd3-11e7-9bd3-2f398c607af7.png)

**Comment by Chasls** [comment]
same problem with me. But the forums are working

**Comment by texas2010** [comment]
@zglrx99 @Chasls thank you for the report. 

@QuincyLarson @BerkeleyTrue, let you know. the freeCodeCamp site is down.

@Chasls forum and fcc site are on the separate server. if you wonder.

**Comment by Chasls** [comment]
@QuincyLarson Any update when it will be up?

**Comment by vkWeb** [comment]
@texas2010 @Chasls @zglrx99 It's up and running now. Happy coding. ✨

**Comment by vkWeb** [comment]
@QuincyLarson @systimotic @BerkeleyTrue @raisedadead Issue can be closed now.

**Comment by texas2010** [comment]
@vkWeb, Yeah. it is up again.  and now I could close this issue. 
It was down for few hours. so it is fine now.
have a nice day.
