### ISSUE TITLE
Shopping list JS challenge redirects to shop

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#15906]
#### Challenge Name

https://www.freecodecamp.org/challenges/shopping-list

#### Issue Description

Visiting the challenge URL redirects to the freeCodeCamp shop. I tried going to the challenge via the map and my profile page. Both of them redirects.

**Comment by texas2010** [comment]
@BerkeleyTrue, I think this case for you. 
> Visiting the challenge URL redirects to the freeCodeCamp shop

**Comment by BerkeleyTrue** [comment]
@kevcomedia thanks for reporting.

This should now be fixed. Your browser may still redirect you as 301 redirects are cached. This should go away soon.

Happy Coding
