### ISSUE TITLE
Update email unsubscribe links to use a hash instead of an email

### ISSUE THREAD

**Issue by ilaiyarajak** [freeCodeCamp/freeCodeCamp#15903]
#### Challenge Name

Update email unsubscribe links to use a hash instead of an email

#### Issue Description

Last week I received an email from Quincy Larson. In that I have seen unsubscribe link is linked with email address(https://www.freecodecamp.org/unsubscribe/emailaddress). 
Using this kind of unsubscribe link, someone can easily unsubscribe me eventhough I wanted to get emails..

#### Browser Information

* Browser Name, Version: Chrome,60.0.3
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```

**Comment by BerkeleyTrue** [comment]
@ilaiyarajak Thanks for the issue. While this is indeed possible it is a low risk and low reward. We will eventually move this to our email service which will provide use with anonymizing service but for now we will close this issue.

Happy Coding.
