### ISSUE TITLE
Password can be reset wiithout new password confirmation.

### ISSUE THREAD

**Issue by ilhamije** [freeCodeCamp/freeCodeCamp#15909]
#### Issue Description

User can reset their password by only fiilling out new password field without filling out password confirmation.

How to reproduce it:

1. Go to [https://www.freecodecamp.org/forgot](https://www.freecodecamp.org/forgot) and try to reset your password.
2. Open a confirmation email from FCC to be directed to reset password page.
3. Fill out your new password on the **New Password field** and **leave the Confirm Password blank.**
4. Hit Change Password button.
5. Try to login with your new password.

#### Browser Information

* Browser Name, Version: Google Chrome Version 58.0.3029.110 (64-bit)
* Operating System: Linux Ubuntu 16.04
* On Desktop

#### Screenshot

![screenshot from 2017-09-23 01-35-43](https://user-images.githubusercontent.com/1570096/30760732-8828ff7a-a005-11e7-8ab4-85dc8b787db3.png)
![screenshot from 2017-09-23 01-36-09](https://user-images.githubusercontent.com/1570096/30760749-9f07e972-a005-11e7-9ff9-fbf809248c02.png)
![screenshot from 2017-09-23 01-36-34](https://user-images.githubusercontent.com/1570096/30760754-a48a937c-a005-11e7-813e-7c85b5ed3a23.png)
![screenshot from 2017-09-23 01-37-07](https://user-images.githubusercontent.com/1570096/30760763-ac096a6a-a005-11e7-948d-9e8270cbb3cc.png)
![screenshot from 2017-09-23 01-37-23](https://user-images.githubusercontent.com/1570096/30760772-b15c4de8-a005-11e7-93a8-ce3e32e5ecfa.png)
![screenshot from 2017-09-23 01-37-51](https://user-images.githubusercontent.com/1570096/30760776-b9ea7c8c-a005-11e7-93ec-49a53925d1df.png)
![screenshot from 2017-09-23 01-38-10](https://user-images.githubusercontent.com/1570096/30760778-bc761790-a005-11e7-9c11-02e7d73c0ea1.png)

**Comment by raisedadead** [comment]
This essentially needs a client-side validation of the password to be same in both the inputs, and should be added here.

https://github.com/freeCodeCamp/freeCodeCamp/blob/backup/master/server/views/account/reset.jade#L15

The server-side code is all fine.

**Comment by raisedadead** [comment]
Potential contributors, please add some jQuery based validation in the reset view mentioned above. Also note that this needs to go into the `backup/master` branch.

Happy fixing!

**Comment by shovanch** [comment]
@raisedadead Looking forward to fix this. This would be my first open source contribution to freeCodeCamp

**Comment by raisedadead** [comment]
Yes please go ahead!

**Comment by msasad** [comment]
All input validations must be carried out on the server side also. Just client side validation is not the solution. Server side code needs to be fixed as well.

**Comment by raisedadead** [comment]
> Server side code needs to be fixed as well.

Please elaborate, or point to code which is to be fixed.

**Comment by tracyalison11** [comment]
Are you looking for the change password button to be disabled until both inputs are filled and matched or do you want an error message thrown?

**Comment by raisedadead** [comment]
@tracyalison11 we would like to display an error message (basic html5 validation), and of course blocking the submit until the form has validated.

some inspiration https://www.html5rocks.com/en/tutorials/forms/constraintvalidation/

**Comment by shovanch** [comment]
@raisedadead I have been working on this. Hoping to add PR before the end of the day

**Comment by msasad** [comment]
> Please elaborate, or point to code which is to be fixed.

If password can be changed without conformation, this clearly means that there is no validation on the server side. The lack of validation at the server side itself is an issue which needs to be fixed.
The answer to [this SF question](https://stackoverflow.com/questions/15855770/why-do-we-need-both-client-side-and-server-side-validation) might help in understanding why server side validation is necessary.
While it is better to have validation on both sides, if we ever choose to have validation in only one side, then it has to be at the server.

**Comment by raisedadead** [comment]
> If password can be changed without confirmation, this clearly means that there is no validation on the server side.

Did you get a chance to look at the server side code and confirm this? And that there is actually no validation?

What the SF article suggests is totally valid, and thanks for sharing it.

> _... Server-side validation is also crucial due to the fact that client-side validation can be completely bypassed by turning off JavaScript. ..._

But that said, the use case we have here has one additional server-side check already. Hence my comments earlier. IMHO, I suggest you to please confirm this yourself if you so, please by actually checking the code. Should you face issues finding it, we would be glad to help you.

Yes, that said the client side view needs to be fixed, which again as per the article you shared:

> _... In practice, all it does is prevent your client (with JS enabled) to know whether the form is okay ..._

And I totally agree. 

Finally, this issue basically boils down to the fact that we had missed doing so in letting the user know that the form was not okay, as pointed out by OP.

**Comment by mohisen** [comment]
Thanks a lot

‏في الثلاثاء، ٢٦ سبتمبر، ٢٠١٧, mrugesh mohapatra <notifications@github.com>
كتب:
