### ISSUE TITLE
Make the success modal static

### ISSUE THREAD

**Issue by himanshukhosla123** [freeCodeCamp/freeCodeCamp#15904]
#### Issue Description

success popup closes while clicking on the black screen around modal , so it will good if we make it static . What do you say . we just need to add data-dropback="static" in modal div

**Comment by systimotic** [comment]
Hi @himanshukhosla123! Thanks your interest in the project.

Can you clarify what you mean by this? What benefit would adding `data-dropback="static"` have?

**Comment by himanshukhosla123** [comment]
sir , whenever i complete a task , the success pop-up that shows up ,
closes when i click around the modal i.e black background and after that i
have to again click on test button to open modal , which in not good in
terms of Ui flow . This , was just a suggestion from my side

**Comment by BerkeleyTrue** [comment]
@himanshukhosla123 Thanks for the issue but this is an accept UI practice to have a modal close when clicking on the blacked out background.

Happy Coding.

**Comment by dhcodes** [comment]
While I cannot find any specification or "best practice" from a reliable source, I find that clicking outside a modal to close it is preferable to not, especially on mobile.

**Comment by dhcodes** [comment]
Berkeley beat me to it.

**Comment by systimotic** [comment]
Thanks for the suggestion @himanshukhosla123!
