### ISSUE TITLE
Look and feel of CodePen js gear different now

### ISSUE THREAD

**Issue by DarrenfJ** [FreeCodeCamp/freecodecamp#1591]
Challenge http://beta.freecodecamp.com/challenges/waypoint-get-set-for-ziplines has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
I'm sure someone has caught this already.. but in case it's been missed:

at least it was for me. No 'Latest Version of.." Instead goto drop down 'Quick add --" It's the first option

**Comment by Greenheart** [comment]
Fixing! :)

**Comment by DarrenfJ** [comment]
Thanks guys!

**Comment by Greenheart** [comment]
@DarrenfJ Thanks for submitting the issue! Keep it up!
