### ISSUE TITLE
Translations are no longer working

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#15917]
I can't seem to find any page on beta that has a Spanish translation.

**Comment by dhcodes** [comment]
Possibly related, I just rebased and now have the following `undefined` note in the console regarding languages. It also is preventing the map from loading and only says "Something went wrong"

```
fcc:services:map en language requested +162ms
  **fcc:services:map undefined language requested +43ms**
200 GET 45.148 ms - /services/map;block=join-the-freecodecamp-community;dashedName=learn-how-freecodecamp-works;lang=en?_csrf=V83U7AYV-_INUPXfYpZfC-Uh-LQdl3vT9Umc&returnMeta=true
200 GET 75.255 ms - /services/map?_csrf=V83U7AYV-_INUPXfYpZfC-Uh-LQdl3vT9Umc&returnMeta=true
```

**Comment by thuanhp** [comment]
Co

**Comment by fizzvr** [comment]
I agree

**Comment by garritfra** [comment]
I was wondering about a similar problem, but this answer is related
https://github.com/freeCodeCamp/freeCodeCamp/issues/15989

**Comment by BerkeleyTrue** [comment]
@dhcodes that happens when a request for the map data does not include a lang tag and defaults to english
