### ISSUE TITLE
Add note for conventional commit messages to contributing.md

### ISSUE THREAD

**Issue by prateekgoel** [freeCodeCamp/freeCodeCamp#15927]
#### Issue Description

I was a nice step to enforce conventional commit messages at https://github.com/freeCodeCamp/freeCodeCamp/pull/15643.
I feel that new contributors, or even some existing contributors won't be aware about this unless they get a warning while committing something.
Can we have a section or note to this in our Contributing.md ?

If yes, I would like to update the same.

**Comment by QuincyLarson** [comment]
@prateekgoel Yes - if you could add a note about this to contributing.md and make it as concise as possible (with example commands), that should make this less confusing for new contributors. We would welcome your help with this.

**Comment by prateekgoel** [comment]
Thanks @QuincyLarson .
I will update that.

**Comment by prateekgoel** [comment]
PR submitted @QuincyLarson .
