### ISSUE TITLE
freeCodeCamp logo not redirecting properly

### ISSUE THREAD

**Issue by pedrosaisse** [freeCodeCamp/freeCodeCamp#15921]
The freeCodeCamp logo at the nav-bar is calling the /challenges/next-challenge/ route.
Shouldn't the main page's route be called, instead ?

Here's the reason I opened this issue:
I visited https://about.freecodecamp.org/ and then clicked on the logo to return to the main page. But received an 404 error.
The URL informed was https://about.freecodecamp.org/challenges/next-challenge

**Comment by erictleung** [comment]
I think [this line of code](https://github.com/freeCodeCamp/about/blob/master/index.html#L101) needs to be changed. I could be wrong if I'm missing something about the redirects.

cc/ @BerkeleyTrue @QuincyLarson

**Comment by RyanGPalmer** [comment]
I'm working on the issue

**Comment by texas2010** [comment]
@RyanGPalmer Please look at link. @erictleung did post line of code link.. that is what you need to change that.  i repost link for you. https://github.com/freeCodeCamp/about/blob/master/index.html#L101

**Comment by RyanGPalmer** [comment]
Opened a new pull request on the correct repository with the correction. I'm very new, thank you for the help!

**Comment by texas2010** [comment]
@RyanGPalmer No problem! thank you for fix it!

**Comment by prateekgoel** [comment]
Referencing the PR here: https://github.com/freeCodeCamp/about/pull/14

**Comment by texas2010** [comment]
close this issue since PR got merge. thanks!
