### ISSUE TITLE
FCC Website is currently down !!!! 502 - Gateway Timeout

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#15929]
#### Issue Description
FCC website is down, forum is not affected. This is has been reported by several users and verified. 
Posted also to the contributors chat room. 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot
![image](https://user-images.githubusercontent.com/22984739/31090177-c2990684-a774-11e7-9993-3b3d33d583eb.png)

**Comment by EroMonsterSanji** [comment]
Confirmed, it's down right now.

**Comment by vitalkanev** [comment]
I can confirm that too on Android 4.2.2 (I don't even know which Chrome'). Not loading

**Comment by jcpsimmons** [comment]
Down for me too

**Comment by david-w** [comment]
Looks like it's working to me.

**Comment by QuincyLarson** [comment]
Thanks for your confirmations of this outage, everyone. We're actively working on this and will post updates to Twitter. It mostly just seems to be extremely slow at certain times, but in some cases, is returning 500 errors.
