### ISSUE TITLE
Twitch API Challenge documentation link moved

### ISSUE THREAD

**Issue by JheeBz** [freeCodeCamp/freeCodeCamp#15933]
#### Challenge Name
https://www.freecodecamp.org/challenges/use-the-twitchtv-json-api

#### Issue Description
The challenge links to a hosted version of the Twitch API (https://wind-bow.glitch.me/) which makes reference to a deprecated documentation. The GitHub (https://github.com/justintv/Twitch-API) links to https://dev.twitch.tv/docs. It would probably be better to link to it directly as the GitHub repo will eventually be removed.

#### Screenshot
![image](https://user-images.githubusercontent.com/820173/31158254-b86191e6-a903-11e7-9164-27fd3b022441.png)

I'd be happy to have a crack at fixing this myself.

**Comment by AlexxMart** [comment]
I can help with this, I could change the link to the Twitch Dev docs and I also have an API that works just fine for this challenge and doesn't have the CORS protection

**Comment by PedroFlaxh** [comment]
What's the status of this issue?

**Comment by misterhtmlcss** [comment]
@AlexxMart I would like to do some PRs, but I'm unclear on the folder structure, which makes it hard for me to see something like this that has sat incomplete for 6 months and I'd love to have helped you.

**Comment by AlexxMart** [comment]
hey @misterhtmlcss I totally forgot about this, I talked to someone at the "contributors" Gitter chat a few months ago because apparently he was working on it, I sent the links to this person and I thought that the change was made long time ago.

I tried to do it myself but coulnd't understand the structure either, that's why I looked for help there

**Comment by QuincyLarson** [comment]
@Em-Ant When you get a moment, could you take a look at your Twitch API app and make sure it's still working? If so, please close this issue.

**Comment by Em-Ant** [comment]
@QuincyLarson both the 'take home' project [here](https://learn.freecodecamp.org/coding-interview-prep/take-home-projects/use-the-twitch-json-api), and the twitch project on my codepen account are still working fine.

**Comment by QuincyLarson** [comment]
@Em-Ant Awesome! Thank you for confirming this.
