### ISSUE TITLE
Broken Link on contribute.freecodecamp.org

### ISSUE THREAD

**Issue by barmetma** [freeCodeCamp/freeCodeCamp#15931]
Hi im quite new to github and I hope this is the right place to create that issue.

When visiting https://contribute.freecodecamp.org there is a broken link on the FCC-Logo. 
The link is targeting to https://contribute.freecodecamp.org/challenges/next-challenge and I recieve a 404 Error.

**Comment by antoniomaia** [comment]
Hi! I believe it should target [https://www.freecodecamp.org/challenges/next-challenge](https://www.freecodecamp.org/challenges/next-challenge) instead. 
Let me know if I can look into this issue as my first contribution, thanks.

**Comment by andpawlenko** [comment]
Same issue while visiting donate.freecodecamp.org. Maybe, this link should refer to freecodecamp.org, like at about.freecodecamp.org :thinking:

**Comment by antoniomaia** [comment]
@andpawlenko That's good, keeping consistency.

**Comment by texas2010** [comment]
thanks. I did make PR for a fix that link.
