### ISSUE TITLE
Have FCC Eslint Rules Be Importable

### ISSUE THREAD

**Issue by jnmorse** [freeCodeCamp/freeCodeCamp#15938]
[copy from](https://github.com/freeCodeCamp/testable-projects-fcc/issues/232)

In Issue [120](https://github.com/freeCodeCamp/testable-projects-fcc/issues/120) of testable-projects-fcc, I was discussing having an importable eslint config. This would require a separate repository to be set up for it.

I created a repository here https://github.com/jnmorse/eslint-config-fcc that does include the fcc rules and can be installed as a dev package to serve as an example. This package is using a more up to date release of eslint 4.7.2.

Think it would be best if the package that is used was published to npm so it could be installed like a normal package.

At @tchaffee suggestion, I am opening the issue and will post in the main repo as well for discussion.

The benefits to having eslint-config package are that it can be maintained and used for multiple projects, and campers could include it as a dependency for their own projects. The downside is that would be external and all changes will have to happen there, aside from any project specific rules.

**Comment by tchaffee** [comment]
This will be an improvement over having to maintain a separate eslint config for each FCC project. As a first step we could try it from a repo like freeCodeCamp/eslint-config-fcc, and if everyone agrees it works well we could publish it to npm, as @jnmorse suggested.

**Comment by BerkeleyTrue** [comment]
@jnmorse thanks for the suggestion. I'll put together an npm package.

**Comment by BerkeleyTrue** [comment]
released here https://www.npmjs.com/package/eslint-config-freecodecamp
