### ISSUE TITLE
Unable to see certificate background image

### ISSUE THREAD

**Issue by birant** [freeCodeCamp/freeCodeCamp#15935]
#### Challenge Name

Front End Certificate

#### Issue Description

The certificate’s image is hosted on imgur which is banned in the country I live. Therefore, I need a vpn to see my certificate. It is not a problem for me, but I want to send my certificate to my potential employees in my country. They may not authorized to use vpn at work.

**Comment by raisedadead** [comment]
/cc @QuincyLarson @BerkeleyTrue do we have any plans to handle such cases? 

I would tend to incline that as a workaround, we could use S3 buckets on a case by case basis?

**Comment by systimotic** [comment]
We should be careful with using Imgur as an image host in general. From [their Terms of Service page:](https://imgur.com/tos)
> Also, don't use Imgur to host image libraries you link to from elsewhere, content for your website, advertising, avatars, or anything else that turns us into your content delivery network. If you do (...) we will ban you along with the site you're hotlinking from, (...) We mean it.

**Comment by raisedadead** [comment]
In that case, it would be great to have a cleaner way, how about having a template .svg for the certs, and generating them on the fly for users?

That would not require any additional storage of any sort other than the data that we have about the users in the db already.

**Comment by raisedadead** [comment]
Plus, it would be trivial as all old certs would continue to be available this way, by keeping a state of the old certs earned, and this we have already.

**Comment by QuincyLarson** [comment]
@raisedadead @systimotic we are using an HTML template for the new certificates. Would either of you be interested in helping get those integrated? Here's GitHub issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/12794

**Comment by QuincyLarson** [comment]
@raisedadead @systimotic regarding hotlinking images, I've opened this issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/15941

@birant we plan to address this issue for beta (staging) which we will ship as soon as possible.
