### ISSUE TITLE
Add ID Attributes to Bootstrap Elements - not working

### ISSUE THREAD

**Issue by sree1995** [freeCodeCamp/freeCodeCamp#15945]
Add ID Attributes to Bootstrap Elements

#### Challenge Name

https://www.freecodecamp.org/challenges/add-id-attributes-to-bootstrap-elements

#### Issue Description

while clicking the button "Run Tests", the page is getting stuck

#### Browser Information

* Browser Name, Version: Chrome (Latest)
* Operating System: MAC OS SIERRA
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
