### ISSUE TITLE
Map link in navbar not loading map (no response

### ISSUE THREAD

**Issue by smkatz** [freeCodeCamp/freeCodeCamp#15948]
#### Issue Description

Used Chrome on Mac OS Sierra, two separate machines. Map link in navbar no longer loads map.

#### Browser Information

* Browser Name, Version: Google Chrome (up to date, production version as of 10/8/2017
* Operating System:  Mac OS Sierra
* Mobile, Desktop, or Tablet: Desktop

Corraboration:

Colleagues on Slack also reported the problem. Campers on Gitter tested multiple browsers, Opera, etc. and no luck.

Explanation of edits:

My colleague's birthday was today and was on my mind. Year corrected.

**Comment by BerkeleyTrue** [comment]
@smkatz Thanks for reporting. I will fix shortly.

**Comment by BerkeleyTrue** [comment]
This has been fixed.

Happy Coding
