### ISSUE TITLE
Create a Set of Radio Buttons - Not Showing Best Practices

### ISSUE THREAD

**Issue by camper-fcc** [freeCodeCamp/freeCodeCamp#15946]
In the *Create a Set of Radio Buttons* challenge of the *HTML5 and CSS* section (https://www.freecodecamp.org/challenges/create-a-set-of-radio-buttons), it states:

> Here's an example of a radio button:
> ```
> <label><input type="radio" name="indoor-outdoor"> Indoor</label>
> ```

Yet, in more official Mozilla documentation (https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form#The_%3Clabel%3E_element), it states:

> Note that a widget can be nested inside its <label> element, like so:
> 
> ```
> <label for="name">
>   Name: <input type="text" id="name" name="user_name">
> </label>
> ```
> 
> Even in such cases however, it is considered best practice to set the for attribute because some assistive technologies do not understand implicit relationships between labels and widgets.

This was discussed here: https://forum.freecodecamp.org/t/anyone-notice-that-some-of-the-challenges-dont-demonstrate-best-practices/151348

Please update the challenge to reflect best practices.

**Comment by darthgera123** [comment]
Ill work on this issue. Just a clarification, do i have to like update wherever its written the set with the new documentation

**Comment by camper-fcc** [comment]
@darthgera123 Awesome! Thanks.

I'm not sure if you're asking me or the experienced Free Code Camp contributors, but I'd say yeah, change the code/language wherever it needs to be changed, not just in the specific example/challenge cited above. In my opinion, every Free Code Camp challenge should suggest and show code that matches current best practices, even if the code in a particular challenge is just supporting code and not the focus of that challenge. Does that answer your question or were you hoping to get an answer from someone else?

**Comment by darthgera123** [comment]
Yeah more or less it does. Ill do what i can

**Comment by dhcodes** [comment]
@darthgera123 the challenge code is [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/bd998042d5344f77a103aadfe8493d226f0da6fc/seed/challenges/01-responsive-web-design/basic-html-and-html5.json#L1653)

You would need to update the instructions and the tests for this challenge, then update the instructions and tests for the checkbox challenge after, and update the code that is preloaded in the editor for every subsequent challenge.

@freeCodeCamp/moderators I'm fine with this change, but would like to hear others' thoughts.

**Comment by QuincyLarson** [comment]
@camper-fcc Yes - if you're talking about just nesting the checkbox within the label (instead of having everything on one line), sure, we can teach the recommended way. 

Please note that when you make this change, you'll need to also change the lesson instructions which introduce this syntax, and you may need to update some tests. You'll also need to update subsequent challenges that have that element in their challenge seeds.

**Comment by raisedadead** [comment]
@camper-fcc thanks for the report.

@QuincyLarson 
IMHO, I think we do not need to modify the tests to check for this attribute. Because we are not enforcing best practices but recommending them where we can.

So, any best practice updates to any challenges can be done async.

**To contributors:**

This line needs to be updated 

https://github.com/freeCodeCamp/freeCodeCamp/blob/f792a4380a894ba294873b69d4eca747b8564fef/seed/challenges/01-responsive-web-design/basic-html-and-html5.json#L1772

to add the `for="indoor"` into the sample snippet, and additional clarification as simple text like so:

> It is considered best practice to set the `for` attribute for assistive technologies to be able to link the relationship between the label and the child elements such as an `input` in this case.

**Comment by QuincyLarson** [comment]
@raisedadead I agree that we shouldn't be enforcing the more fashionable best practices, but if it's a long-held and wide spread norm, I think it's OK to mention it in the lesson text and have a test for it.

**Comment by t3h2mas** [comment]
> Yes - if you're talking about just nesting the checkbox within the label (instead of having everything on one line), sure, we can teach the recommended way.

Is the point discussion about the nesting or the `for` attribute, and how it improves [screen reader](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form#The_%3Clabel%3E_element) experience?

**Comment by raisedadead** [comment]
The OP's intention is discussion about the `for` attribute and how it improves screen reader experience.

**Comment by camper-fcc** [comment]
@darthm3gatron and others. Thanks for fixing this and taking it seriously! :1st_place_medal:

**Comment by yoizfefisch** [comment]
@raisedadead @darthgera123 If the goal is teaching best practice, then you need to explain that the `label` element's `for` value has to match the `input` element's `id` value as explained in [the linked Mozilla documentation page](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form#The_%3Clabel%3E_element).

In addition:
1. This advice applies not only to clickable `input` elements, the Mozilla page actually discusses `input type="text"` which is covered in a previous lesson: Create a Text Field.
2. The same issue applies to the next lesson: Create a Set of Checkboxes.

However, keep in mind that this topic is actually covered in its own lesson under: Applied Accessibility: Improve Form Field Accessibility with the label Element.

**Comment by raisedadead** [comment]
Hi @yoizfefisch thanks for the feedback, please feel free to make a PR if you would be interested or create a separate issue for us to add these recomendations.
