### ISSUE TITLE
Map: Labels arrows don't change direction when click on them

### ISSUE THREAD

**Issue by brushtab** [freeCodeCamp/freeCodeCamp#15955]
#### Issue Description

1. Open https://www.freecodecamp.org/map
2. You see all menus expanded, click on any to collapse it

Expected: Arrow directed right and collapsed menu
Actual: Arrow directed down and collapsed menu

When you click on "Expand/Collapse all chalenges" button everything works fine and arrows changes it's directions.
Same repeats when map occurs as slide window on the right side.

#### Browser Information

* Browser Name, Version: Opera 48.0.2685.39
* Operating System:  Windows 10 64 bit
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
![2017-10-13_22-55-20 3](https://user-images.githubusercontent.com/3997090/31562040-097b1dae-b06b-11e7-9cba-66f2214ea648.png)

**Comment by raisedadead** [comment]
Anyone looking into this please make a change against `backup/master`

**Comment by dshubhadeep** [comment]
Is it okay if I work on this ?

**Comment by raisedadead** [comment]
@dshubhadeep sure!

**Comment by sanatankc** [comment]
is this issue still open? may i fix this?

**Comment by jonathan-grah** [comment]
@sanatankc; unfortunately @JustusFT has grabbed that one!

If you still want to help out, check any of the issues with the [`help wanted`](https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted) label, read our [Contributing Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) and  feel free to ask for help in our [Contributors](https://gitter.im/FreeCodeCamp/Contributors) Gitter room.

**Comment by Mattd1234** [comment]
Is this topic still open?

**Comment by Greenheart** [comment]
Closing this issue as the fix seems to have been merged. Thanks everyone! :)

https://github.com/freeCodeCamp/freeCodeCamp/pull/16038
