### ISSUE TITLE
Dynamic variable in for loop causes crash

### ISSUE THREAD

**Issue by kgwebsites** [freeCodeCamp/freeCodeCamp#15967]
#### Challenge Name

Sum All Odd Fibonacci Numbers

https://www.freecodecamp.org/challenges/sum-all-odd-fibonacci-numbers

#### Issue Description

When entering in the parameter of the function as a variable in the for loop in the max place as shown below, it causes an endless loop and crashes the browser.

#### Browser Information

* Chrome, Version: 61.0.3163.100 
* Operating System: MacOS Sierra 10.12.6
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```
function sumFibs(num) {
  var fib = [1,1];
  
  for(var f=0;f<num;f++){
    var secondLast = fib.slice(-2);
    var last = fib.slice(-1);
    fib.push(secondLast[0] + last[0]);
  }
  return fib;
}

sumFibs(4);
```

**Comment by raisedadead** [comment]
I am inclined to close this as a edge case because what we could device numerous such cases and having checks against them would be tedious in browser.

The loopProtect library that we use for preventing loops seems not to catch them, I am tagging as help wanted for more investigation.

Thanks for the issue.

**Comment by IAmMyself** [comment]
The problem here is that something **_handling_** the returned data is not expecting an array, not that the original loop itself is going on _ad infinitum_.

**Comment by Barkha54** [comment]
Hi, I'm cloning the FCC repo onto my windows laptop and while running gulp it is showing me could not find module babel-core/register. I tried installing babel-core using npm install babel-core/register but it is showing me a lot of errors.

![image](https://user-images.githubusercontent.com/24354626/31853131-53d233ec-b6a1-11e7-992e-5203ac6fa6ff.png)


Can someone help me with this please?

**Comment by Dayfiri** [comment]
Hey, @Barkha54 
As I am looking at your `cmd` output, it seems to me that you don't have a problem with Gulp but with npm and fetching the remote repository you're trying to clone.
You can see one of many errors  saying: 
`Permission denied` and `Could not read remote repository`.
Can you please elaborate how did you "clone" the FCC repository ?
Did you `Fork` it before cloning to your PC ?

**Comment by Barkha54** [comment]
Hi,

Thanks for your response.

Yes, I did fork the repository before cloning it. Then I cloned my version
of the repository and added the freeCodeCamp repo as my upstream
repository. I followed all the instructions as mentioned in the
CONTRIBUTING.md file.

Not sure why I am still getting this issue.

Thanks,
Barkha

**Comment by raisedadead** [comment]
Hi @Barkha54 please reach out to the 
[Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by bgates** [comment]
The original problem was to find the sum of odd numbers in the Fibonacci sequence less than a given `n`, but the code in the issue description will calculate _the first n numbers in the sequence_. 

One of the tests involves calculating `sumFibs(4000000)`, which means dealing with every Fibonacci number less than 4,000,000 - but the 32nd number in the sequence is greater than 4,000,000. Calculating 4,000,000 numbers in the sequence will freeze a browser!

**Comment by kevindessely** [comment]
Like @bgates has said, the `n` number of fibs are too huge for the browser to run especially the test that involves 4,000,000 fib and the solution above are done in a growing array. Which is not an optimized solution.

I have come up with a solution where by, I always keep track of the last two sequence of the fibs instead of the entire sequences of fibs. Which save lots of memory and the addition is done on a separate variable on every loop.

```javascript

function sumFibs(num) {
  var seq = [1,1];
  var summy = 0;
  
  do {
    summy += seq.filter(filterLessThanFibNum(num)).reduce(additionOddReducer, 0);
    
    var sumOfPreviousTwoFibs = seq.reduce(additionReducer, 0);
    seq = [sumOfPreviousTwoFibs, sumOfPreviousTwoFibs + seq[1]];
  } while(seq[0] <= num);
  
  return summy;
}

function filterLessThanFibNum(maxFibNum) {
  return function(number) {
    return number <= maxFibNum;
  };
}

function additionOddReducer(accum, number) {
  if (number % 2 === 0) {
    return accum;
  } else {
    return accum + number;
  }
}

function additionReducer(accum, number) {
  return accum + number;
}

sumFibs(4);
```

**Comment by theoutlander** [comment]
Looking into this item. Here's an efficient solution:

``` 
function sumFibs(num) {
    var prev = 1;
    var next = 1;
    var total = 2;
    var sum = 0;

    for (var i = 0; i < num; i++) {
    sum = prev + next;

    if (sum <= num && sum % 2 !== 0) {
      total += sum;
    }

    prev = next;
    next = sum;
  }

  return total;
}
```

However, I can't seem to repro the problem?

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
