### ISSUE TITLE
Redux Challenge 7 Wording in the description and the tests potentially misleading

### ISSUE THREAD

**Issue by Pethaf** [freeCodeCamp/freeCodeCamp#15975]
#### Use a Switch Statement to Handle Multiple Actions

http://hysterical-amusement.surge.sh/

#### Issue Description

The description says that the the reducer should return an object with the authenticated property set to either true or false. The test description says 
    
    Dispatching loginUser should update the login property in the store's state to true.
    Dispatching logoutUser should update the login property in the store's state to false.

This is a bit missleading as test descriptions could be interpreted as stating that the reducer should return an object with a login property. 

A simple fix would be to change the relevant test descriptions.

**Comment by dhcodes** [comment]
@Pethaf Please copy/paste your issue text and open it at https://github.com/bonham000/fcc-react-tests-module/issues

Thanks, closing this one.
