### ISSUE TITLE
Adding RSS feed for Camper News

### ISSUE THREAD

**Issue by prashcr** [FreeCodeCamp/FreeCodeCamp#1597]
I love the links I find on Camper News, and while I like both FCC and my own Camper News Zipline, I'd love to have the links aggregated along with my other RSS feeds to get more control and avoid having to repeatedly visit FCC/my Zipline.

I tried looking for a way to integrate it into my own Zipline but it seems that this can only be done on the back-end.

To add an RSS feed to the site, I'd need to add a feed.xml.jade template that looks *something* like this

```
doctype xml
rss(version="2.0", xmlns:atom="http://www.w3.org/2005/Atom")
  channel  
    title= title
    link= url
    description= description
    atom:link(href="#{ url }/feed.xml", rel="self", type="application/rss+xml")
    for post, slug in posts
      item
        title= post.title
        description <![CDATA[!{ partial(slug) }]]>
        pubDate= new Date(post.date)
        link #{ url }/news/#{ slug }
        guid(isPermaLink="true") #{ url }/news/#{ slug }
```

And then *something* like this in `<head>` of the page that advertises the feed. Can either be included in universal header or in a specific page. Since Camper News is just a part of FCC, I think just adding it to the stories page would suffice.

```
link(rel="alternate" type="application/rss+xml" title="{{ site.name }}" href="{{ site.url }}/feed.xml")
```

That's all I can figure out so far, I'd like some pointers in the right direction.

Thanks!

**Comment by BerkeleyTrue** [comment]
@prashcr LGTM. Form a PR and I'll merge it.

**Comment by BerkeleyTrue** [comment]
Anyone else want to give this a try?
