### ISSUE TITLE
Beta doesn't work at all on iPad Air

### ISSUE THREAD

**Issue by marienhof** [freeCodeCamp/freeCodeCamp#15973]
#### Challenge Name

Every challenge 

#### Issue Description

Nothing works and everything looks incomplete 

#### Browser Information

* User Agent is: Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1.

#### Your Code

```js



```
#### Screenshot

https://discourse-user-assets.s3.amazonaws.com/original/3X/d/b/dbaf8d414f73d0689cfa957e95e6eae3f5e74608.PNG

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
