### ISSUE TITLE
Can confirm the ending with endsWith using bracket notation

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#15984]
#### Challenge Name

https://www.freecodecamp.org/challenges/confirm-the-ending

#### Issue Description

It's possible to pass **Confirm the Ending** with the `endsWith` method by using bracket notation.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
function confirmEnding(str, target) {
  return str['endsWith'](target);  
}

confirmEnding("Bastian", "n");


```

**Comment by friscomm** [comment]
can I give this one a shot? anybody else called dibs on this?

**Comment by dhcodes** [comment]
Go forth @friscomm. I don't know that anyone is working on it.

**Comment by jamal-pb95** [comment]
Yes, you can pass with bracket notation.

## Browser Information

- Browser Name, Version: Google chrome v61
- Operating System: Windows 7
- Mobile, Desktop, or Tablet: Desktop

**Comment by Spidy88** [comment]
I was thinking the best solution would be to override the `String.prototype.endsWith` method for this test call, have it throw an error. Unfortunately, that change seems to persist outside of the test and disables `endsWith` for all tests. Here's an example of the direction I was going, but I've hit a wall. 

https://github.com/Spidy88/freeCodeCamp/commit/f6ffe41b097ef93919a7182e0b339a968091dc42

I should also note, I tried adding a `tail` that reset the prototype method back to the original but it seemed to have no effect. If only we could run these tests and code in a perfectly isolated environment.

**Comment by TheWillG** [comment]
I solved this issue by simply added another regex conditional to the existing one.  This avoids the use of monkey patching global objects such as String.  I tested it for both .endsWith() and ['endsWith'], as well as verified it does not pick up on false positives.
