### ISSUE TITLE
Other Languages?

### ISSUE THREAD

**Issue by garritfra** [freeCodeCamp/freeCodeCamp#15989]
I'd find it cool if other languages like german or spanish would be supported.
I don't know how much effort that would require, but I'd love to hear your opinion of this!

**Comment by garritfra** [comment]
[This file](freeCodeCamp/seed/challenges/01-responsive-web-design/basic-html-and-html5.json) shows that there are multiple languages. Sorry 'bout that! Issue should be closed.

**Comment by dhcodes** [comment]
@garritfra yes, they are not currently working in beta but will be before it's released. Should you want to add to the translations, please feel free to do so by submitting a PR.
