### ISSUE TITLE
lesson 12 "Use CSS Selectors to Style Elements " does not pass

### ISSUE THREAD

**Issue by mtpjr88** [freeCodeCamp/freeCodeCamp#16005]
The Lesson wants you to style a h2 element changing the color to red, but it does not have the h2 element written. Thus will not pass unless you code in the h2 element.

####  Use CSS Selectors to Style Elements

https://www.freecodecamp.org/challenges/use-css-selectors-to-style-elements

#### Browser Information

* Browser Name, Version: Google Chrome Version: 
Version 62.0.3202.62 (Official Build) (64-bit)
* Operating System: 
Mac Os Sierra 
version 10.12.06
* Mobile, Desktop, or Tablet: 
Desktop

#### Your Code

```js



```

**Comment by TheHollidayInn** [comment]
This seems to be fixed on staging: https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/basic-css.json#L151

**Comment by zk433** [comment]
@mtpjr88 Can you please clarify what you mean? 

As far as I understand, the lesson wants you to change the h2 element to a .red-text class instead and change the color to red. Then apply this class to the h2 element.

Thank you.

**Comment by mtpjr88** [comment]
Yeah so it tells you to style the h2 element and when a newbie does what it says they don't relize that the h2 element isn't coded in the "body", so it will not pass.  The only way to get it to pass is to make sure you add the h2 tags. Otherwise they aren't provided.
```
<h2> </h2>
```

**Comment by huyenltnguyen** [comment]
@mtpjr88 Actually, the challenge asks you to change the h2 from red to blue using the `<style>` element instead of inline styling. I personally think the word `blue` in the instruction should be highlighted to avoid confusion. What do you think?

**Comment by dhcodes** [comment]
The `h2` is coded in the challenge. Campers need only removed the inline style. Closing as such.
