### ISSUE TITLE
text bubble created when cursor hovers over warning icon hidden by navbar

### ISSUE THREAD

**Issue by MikeMullen227** [freeCodeCamp/freeCodeCamp#16002]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/es6/explore-problems-with-the-var-keyword

#### Issue Description

After writing "use strict" at the top of the editor, the warning icon appears to the left. When the cursor hovers over it, the text bubble that describes the issue is covered by the navbar making it unreadable. 

#### Browser Information

* Browser Name, Version: Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
* Operating System: mac OS Sierra version 10.12.6
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/20865245/31848217-24eba640-b5fb-11e7-820c-654cdb550f85.png)
<img width="1440" alt="screen shot 2017-10-21 at 12 52 09 am" src="https://user-images.githubusercontent.com/20865245/31848228-41230a4c-b5fb-11e7-86fb-3c6d9527b5b4.png">

**Comment by HTMLNoob** [comment]
Confirmed this
![screenshot 2017-10-21 17 44 26](https://user-images.githubusercontent.com/16970112/31856475-998d0c1e-b687-11e7-9e3b-d77618f11503.png)

**Comment by dhcodes** [comment]
Fixed. Thanks for this issue; I needed a good hacktoberfest PR

**Comment by MikeMullen227** [comment]
No problem!
