### ISSUE TITLE
Can’t Link FreeCodeCamp to Github

### ISSUE THREAD

**Issue by DaveOrDave** [freeCodeCamp/freeCodeCamp#16027]
#### Issue Description
The forum side of my FreeCodeCamp account is linked to Github, but I absolutely cannot linked my main FreeCodeCamp account that shows the progress I’ve made to Github. Since I wasn’t very far along, I even completely deleted my Github account and recreated it.  *Now I’ve even deleted and re-created my FreeCodeCamp account (I guess I could use review), and this issue is still happening. 

Every time I click on it and enter my password and username for Github, I get a message which says “The code passed is incorrect or expired.”  I will attach screenshots of where I am starting and the message I am getting.

I emailed FreeCodeCamp a month or two ago about this but didn’t get a response. I really enjoy FreeCodeCamp, and I would like to be able to have a public profile to which I can link.

#### Browser Information
I have tried Internet Explorer, Firefox, and Chrome.
![github1](https://user-images.githubusercontent.com/32531625/31974569-79023012-b8fa-11e7-8330-415903d4f361.jpg)
![github2](https://user-images.githubusercontent.com/32531625/31974570-79187020-b8fa-11e7-98d8-36dca88331f9.jpg)

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment]
@BerkeleyTrue Looks like their deletion of GitHub account could have orphaned the UserIdentity object. Maybe this needs to be fixed in backend directly?

**Comment by QuincyLarson** [comment]
@BerkeleyTrue any ideas?

**Comment by BerkeleyTrue** [comment]
No I don't have any. The error does not indicate an orphaned identity but points to the code returned by Github isn't validating

**Comment by DaveOrDave** [comment]
Hello.  Thanks for looking into it.  This was happening before I deleted and re-created the accounts.  I did the deletions/re-creations in an attempt to fix the problem.

**Comment by QuincyLarson** [comment]
@DaveOrDave could you send me an email with your email address and I can look into fixing this for your specific account? Then if anyone else reports this, we can re-open this issue.

**Comment by DaveOrDave** [comment]
Sure.  I'll do it in just a moment.  I really appreciate you looking into this.  I'm really enjoying FreeCodeCamp, and I want to be able to share what I'm doing at FreeCodeCamp on GitHub.  Thanks!
