### ISSUE TITLE
[beta] Differentiate between SASS and SCSS

### ISSUE THREAD

**Issue by Pethaf** [freeCodeCamp/freeCodeCamp#16031]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/sass/introduction-to-the-sass-challenges

#### Issue Description

The wording on the Sass challenges are a bit confusing. The syntax uses in the challenges is acutally SCSS. This can cause confusion if attempting to write sass on codepen.

**Comment by boniverski** [comment]
Hi, I would like to help with this issue. To be clear, in every challenge SCSS syntax should be changed to SASS or should be both included?
