### ISSUE TITLE
Create a set of radio buttons challenge not passing in Safari 11.0

### ISSUE THREAD

**Issue by jamesbarrett95** [freeCodeCamp/freeCodeCamp#16032]
#### Challenge Name

https://www.freecodecamp.org/challenges/create-a-set-of-radio-buttons

#### Issue Description

''Each of your two radio button elements should be nested in its own label element." - This is the only task that doesn't pass in Safari 11. I used the exact same code I attached below into Chrome and it passed fine.

#### Browser Information

* Browser Name, Version: Safari 11.0
* Operating System: macOS Sierra 10.12.6
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
  <label><input type="radio" name="indoor-outdoor"> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
  </form>
```
#### Screenshot

![image](https://user-images.githubusercontent.com/15526293/32010820-be670b68-b9aa-11e7-845e-b90a5ab065d8.png)

**Comment by raisedadead** [comment]
Hi @jamesbarrett95 

Thanks for reporting this issue. 

**Your code passes for me in Safari 11. Can you confirm that this is being faced by someone else as well?**

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

**Comment by jamesbarrett95** [comment]
Tested on another Mac using Safari 11.0 and worked fine, very strange! Apologies.
