### ISSUE TITLE
Wrong navbar color combination for dark theme

### ISSUE THREAD

**Issue by adityaparab** [freeCodeCamp/freeCodeCamp#16030]
With latest merge of #15993 the colors for dark theme are broken.

#### Screenshot

![dark-theme](https://user-images.githubusercontent.com/5561498/31987502-a21e4848-b989-11e7-809b-11d548197a02.png)

**Comment by adityaparab** [comment]
I'll be fixing this in some time.

**Comment by raisedadead** [comment]
This is now resolved
