### ISSUE TITLE
Bonfire: Make a Person - Issue with paramater in test: bob.getFullName();

### ISSUE THREAD

**Issue by smeloa** [FreeCodeCamp/freecodecamp#1604]
Hi,

So this was my initial solution to this bonfire:

```
var Person = function(firstAndLast) {

var firstName = firstAndLast.split(' ')[0];
var lastName = firstAndLast.split(' ')[1];
  
this.setFirstName = function(firstNameNew) { 
  firstName = firstNameNew;
};

this.setLastName = function(lastNameNew) { 
  lastName = lastNameNew;
};

this.setFullName = function (fullNameNew) {
  firstName = fullNameNew.split(' ')[0];
  lastName = fullNameNew.split(' ')[1]; 
};

this.getFullName = function() {
  return firstName + ' ' + lastName;
};

this.getFirstName = function() { 
return firstName;
};

this.getLastName = function() { 
return lastName;
};


};

var bob = new Person('Bob Ross');
bob.getFullName();
```

as much as I changed the fullName formulas (set and get), it always told me that Happy Trees and Bob Ross where not equal to George Carlin. 

only way to solve it was to remove

```
bob.getFullName();
```

from the challenge.

this is the original challenge question:

```
var Person = function(firstAndLast) {
    return firstAndLast;
};

var bob = new Person('Bob Ross');
\\ Line below should be removed
bob.getFullName(); 

```

Thanks

**Comment by catapixel** [comment]
@smeloa I copied and pasted your "inital solution" code into the bonfire and it passed all tests with no changes. I'd refresh your browser and then try it again.

**Comment by Greenheart** [comment]
I tried running your initial solution and it worked for me too.
@smeloa Try @catapixel 's solution!

**Comment by smeloa** [comment]
Thanks. Tried it again and it worked, do not know what caused that error.
