### ISSUE TITLE
FCC beta map not loading, says "No Super Blocks"

### ISSUE THREAD

**Issue by sophyphreak** [freeCodeCamp/freeCodeCamp#16047]
#### Issue Description

For several weeks, when I go to the freecodecamp beta site, the map takes a long time to load. 

Today it doesn't load at all.

#### Browser Information

* Chrome Version 61.0.3163.100 (Official Build) (64-bit)
* Windows 10
* Desktop

```js



```
#### Screenshot

<img width="960" alt="2017-10-28 2" src="https://user-images.githubusercontent.com/22810755/32136703-87a59646-bc3c-11e7-8389-06eab2ab5120.png">
<img width="960" alt="2017-10-28 3" src="https://user-images.githubusercontent.com/22810755/32136704-87e95aa2-bc3c-11e7-9349-f5e42abbccf3.png">
<img width="960" alt="2017-10-28 4" src="https://user-images.githubusercontent.com/22810755/32136705-882aa624-bc3c-11e7-8fac-72410d01b903.png">

**Comment by sophyphreak** [comment]
I did get it to load, but I'm not 100% sure what did it.

**Comment by anhtran1906** [comment]
superBlocks are an array loading from redux store. While loading, it renders the <div>No Super Blocks</div> html block until it has the list of the challenges. I think it's better if we add a <Loader/> instead of leaving it as a <div> of text like the above.

**Comment by BerkeleyTrue** [comment]
If you are seeing the 'No super blocks' message this is an indication that the data isn't being properly loaded. I'll take a look at Beta and see what's going on

**Comment by BerkeleyTrue** [comment]
This may be an issue I have fixed in #15781 
Can anyone replicate this locally?

**Comment by BerkeleyTrue** [comment]
closing in favor of #15972
