### ISSUE TITLE
Bug in Shopping List that accepts incorrect values

### ISSUE THREAD

**Issue by denzuko** [freeCodeCamp/freeCodeCamp#16044]
#### Challenge Name

https://www.freecodecamp.org/challenges/shopping-list

#### Issue Description

when using Array(5).forEach(); along with myArray.push() the tests past but values are all null which is not what the assignment is expecting.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

var myList = new Array(5);

myList.forEach(function(idx){
  myList.push(["lorum ipsom delorum...",  Math.floor(Math.random() * (20 - 1) + 1)]);
});


```
#### Screenshot

![How its broken](https://i.imgur.com/t7X4tTa.png)

**Comment by walllFlower** [comment]
`new Array(5)` create an array with 5 empty, and forEach will ignore the empty

**Comment by denzuko** [comment]
@walllFlower Yeah that appears to be the bug itself. What ever test is being ran behind the scenes is only evaluating the `var myList = new Array(5);` portion and ignoring everything else.

![how it breaks](https://user-images.githubusercontent.com/19776/33854974-23b7d5bc-de89-11e7-935f-eb7b7f5b9ff3.png)

While its my understanding that the challenge is to have an array of arrays, with the first element in the subarray a name and second the value. (imho an odd way of doing key pair dictionaries but I get that we're trying to teach the versatility of arrays)

![expected not broken](https://user-images.githubusercontent.com/19776/33854995-2f8d79f0-de89-11e7-85b9-29c9ebab2bcb.png)

**Comment by QuincyLarson** [comment]
Is this still an issue with the new learning platform?

**Comment by QuincyLarson** [comment]
@denzuko @walllFlower Is this still an issue on the new learning platform? (https://learn.freecodecamp.org)? If so, would you still be interested in helping fix it?

**Comment by RandellDawson** [comment]
This was an old one that needed to be resolved.  Hopefully, my PR will be validated and merged.

**Comment by QuincyLarson** [comment]
@RandellDawson Awesome! 

@ahmadabdolsaheb could you QA this and merge it if it looks good?
