### ISSUE TITLE
Beta - Waypoint: Override All Other Styles by using Important -Typos

### ISSUE THREAD

**Issue by lmorris2004** [FreeCodeCamp/freecodecamp#1606]
Challenge http://beta.freecodecamp.com/challenges/waypoint-override-all-other-styles-by-using-important has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In the first sentance: "Yay! **we** just proved that in-line styles will override all the CSS declarations in your style element."  The W in we should be capitalized.

In the 5th paragraph, "Let's add the keyword !important to your **body'** element's color declaration to make 100% sure that your h1 element will be pink." The word body' should be **pink-text**

**Comment by Greenheart** [comment]
I'll fix it, should be some good practice with git :smile:
