### ISSUE TITLE
Conflicting Instructions In JavaScript Variable Assignment Lesson

### ISSUE THREAD

**Issue by jhomme** [freeCodeCamp/freeCodeCamp#16064]
#### Challenge Name

https://www.freecodecamp.org/challenges/understanding-uninitialized-variables

#### Issue Description

The instructions read differently than the error message when the system thinks the code does not work.

#### Instructions

Initialize the three variables a, b, and c with 5, 10, and "I am a" respectively so that they will not be undefined.

#### Error Message

a should be defined and have a value of 6
b should be defined and have a value of 15
c should not contain undefined and should have a value of "I am a String!" 
Do not change code below the line 

#### Browser Information

* Browser Name, Version:  Firefox 56.0.2
* Operating System:  Windows 10 Creators Edition
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code

```
```

// Example
var ourVar = 19;

// Only change code below this line

var a = 5;
var b = 10;
var c = "I am a";
```

**Comment by bcpete** [comment]
I'd like to work on this!

**Comment by qmikew1** [comment]
The actual instructions are pretty clear (and aren't conflicting)
because they don't ask one to evaluate the tests and if the correct
values are initialized (as directed), the challenge is passed/completed.

The initial state of errors when one
lands on/accesses lesson is reflecting 
tests on expected values associated with adding
1, 5, and string concatenation of ' String!'
to each of the variables (in assignments) under:
```
// Do not change code below this line

a = a + 1;
b = b + 5;
c = c + " String!";
```
This amounts to 'supply what was asked, and we're going to add numbers and concatenate
strings to that and evaluate stuff as a whole'. I guess you could argue that it could be confusing,
but (imo) I think they're giving you indirect hints to what's possible as you progress

**Comment by jhomme** [comment]
Hi,
I have a feeling I pointed you to a wrong link, because I did not see
any math or concatination. Perhaps you should close this and let me
reinvestigate. I apologize.

Jim

On 11/3/17, Serenity <notifications@github.com> wrote:
> The actual instructions are pretty clear (and aren't conflicting)
> because they don't ask one to evaluate the tests and if the correct
> values are initialized (as directed), the challenge is passed/completed.
>
> The initial state of errors when one
> lands on/accesses lesson is reflecting
> tests on expected values associated with adding
> 1, 5, and string concatenation of ' String!'
> to each of the variables (in assignments) under:
> ```
> // Do not change code below this line
>
> a = a + 1;
> b = b + 5;
> c = c + " String!";
> ```
> This amounts to 'supply what was asked, and we're going to add numbers and
> concatenate
> strings to that and evaluate stuff as a whole'. I guess you could argue that
> it could be confusing,
> but (imo) I think they're giving you indirect hints to what's possible as
> you progress
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/freeCodeCamp/freeCodeCamp/issues/16064#issuecomment-341632863


-- 
==========

Jim Homme
http://www.jimhommewebdev.com
Twitter: @jimhomme
Facebook: http://www.facebook.com/jimhomme
LinkedIn: https://www.linkedin.com/in/jimhomme

**Comment by rcohane** [comment]
This issue should be closed. jhomme didn't realize that the code below "// Do not change code below this line" changed the values of the variables he initialized. The error message is correct.
