### ISSUE TITLE
Redirect to Current Challenge does not work when change browser / system

### ISSUE THREAD

**Issue by johnkennedy9147** [freeCodeCamp/freeCodeCamp#16075]
#### Issue Description

If you login to FCC from a different browser  or system you may not be redirected to what is currently your current challenge. Rather you will be directed to the last one you accessed on the browser you are currently logging in from.

Cookie currentChallengeId is storing the last accessed challenge. Could we do this by user profile instead?

**Comment by raisedadead** [comment]
Hi,

Thanks for the reporting
Yes, this is something I believe we are doing in one of the next release of the platform. 
The current challenge is stored on the User Object.

But, that said I can't speak of a date, of the availability as we are working to get the beta out.
Stay tuned.

For now, I'll close this as resolved in `staging`.
