### ISSUE TITLE
Support for Gmail "append keyword to email" like user ids

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16070]
Gmail allows users to append keywords with a `+` symbol in their user ids, like so someone.example+keyword@gmail.com

Currently we have a partial support (by virtue of default implementation) for such emails.

This is particularly an issue while sign-up when we receive a request to authenticate here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/89306fb875382a5aa40251b04df073dd0cbc33ef/server/boot/user.js#L272-L287

We have three paths to fix this:
1. Easiest, simply throw a validation error for such emails to begin with while sign up, which is not cool and rather a bad UX.
2. Fix up the logic around sending auth emails, so that the magic link is a `hashed` email.
3. Fix up the logic around the code mentioned earlier, to find and correctly parse the req object.

I'll leave this for open thoughts before a fix.

**Comment by raisedadead** [comment]
Note this is a specific use-case and while not common for most users, yet considering the user base we have, we might run into a lot of cases, where this blocks user from sign in.

@BerkeleyTrue What are your thoughts? I am personally in favour of the hashed emails.

**Comment by BerkeleyTrue** [comment]
@raisedadead I'm not sure I understand the issue. Is it that if someone uses a keyword our auth logic won't work?

**Comment by raisedadead** [comment]
@BerkeleyTrue Yes, if someone uses the a keyword like in the example, its parsed incorrectly from the `req` object in the snippet I shared earlier.

So, if we have `someone.example+fcc@gmail.com` then the line is resulting in

```js
const authEmailId = req.query.email; // authEmailId = 'someone.example fcc@gmail.com'
```

Since its encoded as a get request parameter from the magic link. I was hoping a base64 hashing should be enough to solve this. But wanted to double check with you.

**Comment by BerkeleyTrue** [comment]
@raisedadead I think this is a good idea. Thanks for bringing this to my attention.
