### ISSUE TITLE
"Exact Change" algorithm challenge should return single data type.

### ISSUE THREAD

**Issue by johntyree** [freeCodeCamp/freeCodeCamp#16083]
#### Challenge Name

https://www.freecodecamp.org/challenges/exact-change

#### Issue Description

My own two cents as an experienced developer is that this problem teaches newcomers that it's totally normal and acceptable for your functions to return completely different types depending on arbitrary input conditions. I know javascript is not statically typed, but this is the stuff that bugs are made of. 

I'd suggest having it at least tag the return value with the type in some way, such as `{registerState: 'CLOSED', change: [...]}` or `{registerState: "INSUFFICIENT_FUNDS", change: []}` etc. As-is, the correct solution wouldn't pass code review at any of the places I've worked. Seems in bad taste to teach it to people that are trying to pass interviews someday.

To clarify, I propose that the function *always* return an object containing a `status` key and a `change` key. The `status` is one of `INSUFFICIENT_FUNDS`, `CLOSED`, `OPEN`, and `change` is a 2D array that is described in the original problem. Examples:

```
{status: "INSUFFICIENT_FUNDS", change: []}  // change should probably always be empty list in this case
{status: "CLOSED", change: [["PENNY", 1.01], ["NICKEL", 2.05]]}
{status: "OPEN", change:  [["TEN", 20.00], ["TWENTY", 60.00]]}
```

Discuss.

**Comment by johntyree** [comment]
See https://github.com/freeCodeCamp/freeCodeCamp/issues/9657#issuecomment-280932294 for motivating comment.

**Comment by scissorsneedfoodtoo** [comment]
Hi there. 

After reading your description of the problem and suggestions, I'd like to try and help with this. Hope to be able to submit a pull request within the next couple of days.
