### ISSUE TITLE
FCC Website is down

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16086]
#### Issue Description
FreeCodeCamp.org is currently down.
Error 502 - Bad Gateway
it's being reported by several users. 
The FCC Forum doesn't not appear to be affected.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/32689903-d48cdc84-c6ba-11e7-83c1-2bf107d43446.png)

**Comment by mstellaluna** [comment]
@QuincyLarson @BerkeleyTrue

**Comment by mstellaluna** [comment]
Camperbot is also affected. Generating 'api offline' when thanking

**Comment by BerkeleyTrue** [comment]
@mstellaluna Thank you for letting us know. We have got the site back up and looking into the cause.
