### ISSUE TITLE
FCC's Manage a Book Trading Club deafult accounts login issues

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16084]
#### Challenge Name

Back End Development Certification Section
Manage a Book Trading Club
https://www.freecodecamp.org/challenges/manage-a-book-trading-club

#### Issue Description

The FCC example is not working properly. Users cannot login to see the full functionality of the app. 
This happens for both the test account and the admin account. 
Getting error "This password is not correct".
It does allow me to register an account.

#### Browser Information

* Browser Name, Version: MS Edge 4, Chrome 63, Firefox 53
* Operating System: Windows 10 64-bit with Anniversary update
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/32607261-57b7823a-c526-11e7-8147-2a168861758e.png)

![image](https://user-images.githubusercontent.com/22984739/32607249-45de0886-c526-11e7-899d-67772305443e.png)

**Comment by tiagocorreiaalmeida** [comment]
![image](https://user-images.githubusercontent.com/17684951/32608897-b659afbe-c555-11e7-8dd9-c8a1a560afc1.png)

The request button is missing aswell

**Comment by raisedadead** [comment]
@freeCodeCamp/moderators I am not sure who is the original author/maintainer of the example app. Can anyone pitch in to guide on this?

**Comment by J36miles** [comment]
@clnhll, are you able to assist on this?
https://github.com/clnhll/bookjump

**Comment by ooade** [comment]
I suggest we move these basejumps examples to FreeCodeCamp Organization, or we re-create them :man_shrugging:

**Comment by raisedadead** [comment]
@JosephLivengood @QuincyLarson 
Are we able to assist on this by moving the same to Gomix? 
This is a potential show stopper.

**Comment by QuincyLarson** [comment]
@raisedadead @mstellaluna I've reached out to the project creator on Twitter and asked him if he can fix this in his app. On beta, we've moved this project over to a practice project - it's no longer part of the core curriculum. But ideally, we should host our own official version on Glitch.

**Comment by raisedadead** [comment]
@QuincyLarson could you layout the steps to create and host a Glitch project under freeCodeCamp?

**Comment by Em-Ant** [comment]
Hi @raisedadead, how are you? 
I'm about to start working on [this PR](https://github.com/freeCodeCamp/freeCodeCamp/issues/16118). Is this related ?

**Comment by raisedadead** [comment]
Hi @Em-Ant I am doing great, nice to have you back! Yup this can be taken up as a part of that thread. Thanks.

**Comment by raisedadead** [comment]
Closing in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/16118
