### ISSUE TITLE
Won't let me pass even when all tests are passed

### ISSUE THREAD

**Issue by jasonszhao** [FreeCodeCamp/FreeCodeCamp#1608]
On the [reversing a string challenge](http://www.freecodecamp.com/challenges/bonfire-reverse-a-string), it won't let me pass even when all the tests have a green checkmark. I tried this on Mac 10.10, Safari 8, Chrome 44, and FF 39, and none work, even with Adblock disabled.
<img width="1309" alt="screen shot 2015-08-06 at 11 50 32 am" src="https://cloud.githubusercontent.com/assets/5283282/9120491/66506e36-3c31-11e5-998a-3dcd099bd3a9.png">

I know my code is wrong (I passed it eventually), but there I think there should be a better, explicit indication that the solution is incorrect.

**Comment by Jorgixhallo** [comment]
@jasonszhao Check the Map. Does it say you have done it?

**Comment by jasonszhao** [comment]
No. I know I have not passed it because I know the `return` output is wrong (There aren’t supposed to be commas.) However, all the tests appear to pass. I was deceived for a moment.

**Comment by benschenker** [comment]
Hey @jasonszhao is this still an issue for you?
