### ISSUE TITLE
Style guide alternative logo wrong colour underline.

### ISSUE THREAD

**Issue by Middi** [freeCodeCamp/freeCodeCamp#16080]
#### Issue Description
Color of the underline of the fire portion of the logo for the alternative logo in png, jpeg and eps is white and should be green.

#### Screenshot
<img width="492" alt="screen shot 2017-11-07 at 15 16 34" src="https://user-images.githubusercontent.com/15717148/32501066-f28e1ae8-c3ce-11e7-9000-709be8787734.png">

#### Link
https://design-style-guide.freecodecamp.org

**Comment by Barkha54** [comment]
Hi, can you tell me where I will find this file? All the images seems to be hosted on Amazon AWS and I'm not able to find them on my local setup. I would like to take up this issue.

**Comment by raisedadead** [comment]
Issue moved to [freeCodeCamp/assets #148](https://github.com/freeCodeCamp/assets/issues/148) via [**ZenHub**](https://www.zenhub.com/)
