### ISSUE TITLE
Callback Functions are introduced without a description

### ISSUE THREAD

**Issue by JB-Walker** [freeCodeCamp/freeCodeCamp#16089]
#### Challenge Name
https://www.freecodecamp.org/challenges/iterate-over-arrays-with-map

Callback functions are first introduced here, but there is no description given or link to outside reference.

**Comment by ChristianLapinig** [comment]
@raisedadead I can take this one. Do you guys want it to be a link to a reference where it says callback in the description or a separate section called references/resources after the description?

**Comment by raisedadead** [comment]
@ChristianLapinig Awesome! Thanks for helping us out with this.

I think we would prefer a short description in the challenge it self. 

Also note that this has to go in in two separate branches with pull requests for each `backup/master` and `staging`

Let us know if you need any assistance.

**Comment by ChristianLapinig** [comment]
@raisedadead just sent a pull request which will go into ```backup/master``` but wasn't really sure where it goes in ```staging```. I would think it does under Understand the Hazards of Using Imperative Code?

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
