### ISSUE TITLE
Unexpected behaviour if I use assert in my code for challenge

### ISSUE THREAD

**Issue by InNoobWeTrust** [freeCodeCamp/freeCodeCamp#16098]
#### Challenge Name

Truncate a string

#### Issue Description

Inside the function, before doing the operation, I would like to check the argument first for sure
```js
assert(typeof num === 'number' && num >= 0);
```
My code produces the visually correct result on result panel but the tests are all failing. When I comment out the assert line, it passes all the tests.

I think there is a problem when handling user code if they use assert() like me...

#### Browser Information

* Browser Name, Version: Chrome portable, Version 62.0.3202.94 (Official Build) (32-bit)
* Operating System: Windows 10 Fall Creators
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js
function truncateString(str, num) {
  // Clear out that junk in your trunk
  assert(typeof num === 'number' && num >= 0);
  return str.length > num ? str.slice(0, num <= 3 ? num : num - 3).concat('...') : str;
}

truncateString("A-tisket a-tasket A green and yellow basket", 11);
```

**Comment by raisedadead** [comment]
@InNoobWeTrust 

Can you share what's the output on your browser's console window in developers tools (Press <kbd>F12</kbd>)? We would love some screenshots too.

**Comment by InNoobWeTrust** [comment]
Here is the screenshot:
<img width="960" alt="freecodecampissue" src="https://user-images.githubusercontent.com/23432432/32877173-d0db3970-cad2-11e7-83c0-0fb31a48159b.png">

Here is the console output:
```
Uncaught ReferenceError: assert is not defined
    at truncateString (<anonymous>:5:3)
    at <anonymous>:9:1
    at commonFramework-211bd0b00d.js:1
    at vendor-main-73068f4947.js:58
    at c.Qa.FlatMapObservable.c.next (vendor-main-73068f4947.js:59)
    at c.Qa.internals.AbstractObserver.b.onNext (vendor-main-73068f4947.js:58)
    at c.<anonymous> (vendor-main-73068f4947.js:58)
    at b.c.next (vendor-main-73068f4947.js:62)
    at b.Qa.internals.AbstractObserver.b.onNext (vendor-main-73068f4947.js:58)
    at c.next (vendor-main-73068f4947.js:60)
```
Somehow assert is not available for user code. I don't know exactly why, may be the extensions like Ublock Origin or Violent Monkey in my browser cause unexpected behaviour or assert is not allowed intentionally?

And I wonder, if assert() fails, why does the output panel on this page still give output? It seems strange to me... 🙄

**Comment by raisedadead** [comment]
Its actually expected. 

Your code is being run in the browser and hence you need to use a browser's implementation for instance like doing a `console.assert` rather than a plain `assert` like you would do with a testing framework or library.

On that note, I personally think a if..else is a much better option in this case.
Please reach out to the forum for more assistance on your code.

I'll go ahead and close this as its not an issue with the code-base.

Happy coding!

**Comment by InNoobWeTrust** [comment]
Oh, thanks. I didn't know there is a difference in ```console.assert``` and plain ```assert```. I've seen the use of ```assert``` somewhere and assume that it is a feature of javascript itself, turn out I was so careless...

Anyway, thanks for taking time on this, I'll be more careful and check the console first before raising an issue. 😉
