### ISSUE TITLE
Why is SQL not part of the FCC curriculum?

### ISSUE THREAD

**Issue by arielcamus** [freeCodeCamp/freeCodeCamp#16095]
#### Issue Description
As a developer, I've found myself countless of scenarios where a NoSQL database was not the right solution for an application. Why is SQL not part of the FCC curriculum?

Also, what's the best place to ask about why some things are in the curriculum and some others are not?

**Comment by raisedadead** [comment]
Hi @arielcamus thanks for the issue. I strongly advice you to take it up in the [Forum](https://forum.freecodecamp.org) and maybe even our Quora pages.

This way you are able to get strong community feedback on feature/curriculum requests.

You can then still comeback and open an issue on this tracker for actual discussion on the implementation.

As for why we do not have SQL, IMHO we have chosen JavaScript simply as its 'fairly easy' for beginners to get started with it, and hence the eco-system around it is a natural choice.

While SQL, is compatible, and people build systems in JavaScript around that stack, we have limited resources that we can dedicate on creating curriculum on every topic that can be covered. For instance SQL.

That said, I clearly agree that we are open to adding it to curriculum as long as there is a demand and more importantly we have contributors to design curriculum around it.

So, before we go ahead and get into the technical side of implementing it, I recommend you reach out to the community on the forum, [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), and even the Quora channels.

We would happy to assist post that.

Thanks,
Happy coding!

**Comment by raisedadead** [comment]
I am closing this, for now to keep the relevance on fixing issues. Please feel free to re-open once again when this becomes relevant.
