### ISSUE TITLE
feature/ can we add more hidden tests

### ISSUE THREAD

**Issue by itsjzt** [freeCodeCamp/freeCodeCamp#16092]
#### Issue Description
It's very easy to return test result values directly instead of writing the algorithm. Can we add more hidden test cases?

#### ScreenShot
![smart](https://user-images.githubusercontent.com/22629916/32730410-00282080-c8ad-11e7-9a15-41a9f7761f85.png)
Another exaxmple
![another_smart](https://user-images.githubusercontent.com/22629916/32730632-bf1522a4-c8ad-11e7-84cc-31d90967e0fa.png)

**This can be done in every challenge of algorithm section so needs to get better**

**Comment by sanatankc** [comment]
+1

**Comment by raisedadead** [comment]
@itsjzt 

Thanks for the issue, unfortunately adding hidden tests is just circumventing the problem of dishonesty. There will always be a way where users can submit such solutions for example searching this public codebase.

Adding hidden tests are also less helpful when someone is trying to genuinely debug their algorithm.
They see the challenge failing, but do not know the expected results.

We have rather a way to flag any such submissions by user reports on our support channels.
Upon going though the review process, we can flag users as dishonest and then then are unable to get the certifications.

And more crucially if users are not being reported, and are getting the challenges done using such submissions, trust me they are failing to understand why they are on the platform in the first place. Learning doesn't come via the shortcuts.

Happy coding!
