### ISSUE TITLE
Beta: Waypoint: Use Hex Code for Specific Colors - wording on 2nd checkpoint

### ISSUE THREAD

**Issue by lmorris2004** [FreeCodeCamp/FreeCodeCamp#1609]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-colors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The 2nd checkpoint is missing the rest of the "example" when you first load the page.
![image](https://cloud.githubusercontent.com/assets/13663814/9120813/846b5abe-3c4c-11e5-8c08-77a5fd36211b.png)

After you change the background color value to #000000 then it updates the checkpoint wording:
![image](https://cloud.githubusercontent.com/assets/13663814/9120875/e3c0a6ea-3c4c-11e5-8eaa-e48fef8a7067.png)

**Comment by lmorris2004** [comment]
The next Waypoint has the same issue: Waypoint: Use Hex Code to Color Elements White

**Comment by benschenker** [comment]
Closing as stale, please reopen if this is still an issue for you
