### ISSUE TITLE
Campberbot not issuing cookies/brownies

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16096]
#### Issue Description
Since the FCC website crash the other day, camperbot is no longer issuing cookies/brownies. 
He does respond to other commands such as find, botstatus, eightball, rooms.
This is affecting all rooms in chat not sure if it is affecting the challenges or the forum.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/32797384-94f62148-c93f-11e7-8a92-33be241ecad7.png)

**Comment by mstellaluna** [comment]
@QuincyLarson @BerkeleyTrue

**Comment by BerkeleyTrue** [comment]
Thanks @mstellaluna for staying on top of things. We recently upgraded camperbot so this could be the cause. I will look into this shortly

**Comment by mstellaluna** [comment]
@BerkeleyTrue thank you :) let me know if you need me to test camperbot when you are ready.

**Comment by BerkeleyTrue** [comment]
fixed. Thanks for the help @mstellaluna 

Happy Coding

**Comment by mstellaluna** [comment]
thanks !!
