### ISSUE TITLE
Study group searches show groups abroad

### ISSUE THREAD

**Issue by d33con** [freeCodeCamp/freeCodeCamp#16093]
#### Issue Description
https://study-group-directory.freecodecamp.org/
When searching for a local study group the city names fetch any city worldwide with that name and report the distance as the same. I am in the UK and it is also showing me US cities with the same name as nearby UK cities

#### Screenshot
![fcc](https://user-images.githubusercontent.com/13669754/32737730-c1f7da9a-c892-11e7-829c-7233a41a628e.jpg)

**Comment by Shikhargupta1** [comment]
Hey any suggestions on how to stop these emails for good..

**Comment by texas2010** [comment]
@Shikhargupta1 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!

**Comment by Shikhargupta1** [comment]
Hey thanks there
Didn't really think someone would respond.
Learning python and Java right now by the way and these emails were just
not at all helpful, annoying really.
So ya thanks.

**Comment by raisedadead** [comment]
Issue moved to [freeCodeCamp/study-group-directory #53](https://github.com/freeCodeCamp/study-group-directory/issues/53) via [**ZenHub**](https://www.zenhub.com/)
