### ISSUE TITLE
[beta] Console.log outputs do not appear in display

### ISSUE THREAD

**Issue by thmsdnnr** [freeCodeCamp/freeCodeCamp#16100]
Hi @BerkeleyTrue, Quincy asked me to write an issue about this & tag you on it after I mentioned it in the Arcade Mode Gitter chat.

Previously, we closed issue https://github.com/freeCodeCamp/freeCodeCamp/issues/10977 because it was believed to be fixed with a React update. However, the console.log() behavior is still not displaying as expected.

#### Issue Description
Go to any challenge that requires you to type in JavaScript code and run tests on it, either beta or existing. 

1. For instance, go here: https://beta.freecodecamp.org/en/challenges/project-euler-problems/problem-1-multiples-of-3-and-5
2. Paste `console.log('param #:', number);` in the function body.
3. Click Run Tests
4. Note lack of console output on page, although it does appear in the dev console of the browser.
5. Click Refresh on the page.
6. Note the console logged output, but only on page refresh, and only for the function call of `euler1(1000)`. 
* Click Run Tests again and the output disappears.
* Note that if you try to console log something undefined in the function, like `console.log(meh)`, you get four instances of `meh is not defined`.

At first I thought the code might be logging console output but that it's then getting overwritten by the test runner results, whenever the function executes fully without throwing a ReferenceError. However, if you try logging something before you hit the error, e.g., 

```javascript
  console.log('44');
  console.log(meh);
```

you only get `meh is not defined` for output x4, and "44" never displays.

#### Browser Information
I verified this is happening in:

Chrome Version 61.0.3163.100
Safari Version 11.0.1 (12604.3.5.1.1)
Firefox Quantum Version 57.0

* Operating System: OS X 10.12.6
* Mobile, Desktop, or Tablet: Laptop

#### Solutions?

We could of course change the message to say check the Developer Console, but as-is, it'd be confusing since we tell people to look for console.log() output but never provide it in a way that would be expected. I think we should either change the message, or find out why it's not working properly. It'd be a nice feature to have.

**Comment by raisedadead** [comment]
I think we are still working on it, even for releasing to beta.

**Comment by BerkeleyTrue** [comment]
This should be fixed in beta.

Happy Coding
