### ISSUE TITLE
Shopping List misuses arrays, should use objects

### ISSUE THREAD

**Issue by willnwhite** [freeCodeCamp/freeCodeCamp#16108]
#### Challenge Name
Shopping List

#### Issue Description
Each item has a name and a quantity, so should be represented as `{ name: "Chocolate Bar", quantity: 15 }`, not `["Chocolate Bar", 15]`. The latter relies on whoever's using the data to remember that name is at index 0, quantity at 1 (when they want the quantity, they have to do `item[1]`, rather than `item.quantity`. This approach doesn't scale, and shouldn't be taught. This may mean introducing objects earlier, or moving this challenge to later in the curriculum (after objects have been introduced).

**Comment by cdrainxv** [comment]
The challenge's singular purpose is to introduce multi-dimensional arrays (in this case a 2-D array). There is no requirement to actually retrieve any of the values in the array. In my opinion this challenge is placed correctly with respect to its preceding and following challenges.

**Comment by willnwhite** [comment]
Just _using_ an array as an object teaches bad practice. I think the challenge needs a better example, e.g. a bitmap can be represented with a 2D array.

**Comment by EstebanBorai** [comment]
I'm thinking about an array of objects where each index represents a category from a grocery store based on the different categories you are able to find when you visit the market.
So the two dimension array would look like:

`const groceryStore = [
    [{
      product: 'Jam',
      price: 1.50
    } (...)
    ],
    (...),
    `
Here you can find an index representing a category (you can use a Map to make a enumerable like data structure and then manage to create multiple categories and products.

**Comment by cdrainxv** [comment]
Objects haven't been taught at this stage yet (based on the map). # However, a simple coordinate system would suffice for this challenge -- most likely everyone will know what x and y values. How about just getting them to "plot" five points inside of an array?

`var coordinates = [[12, 4], [23, 56], ... [89, 12]];`

In my honest opinion I think too much time is being afforded to this lesson considering the intent of the lesson.

**Comment by willnwhite** [comment]
Though coordinates works much better than the shopping list, in my own code I'd use an array of `{x, y}` objects, rather than relying on a 0 = x, 1 = y convention.

If we can't think of a worthwhile example of use of a multidimensional array, should the curriculum cover it at all? Is it counter-intuitive that arrays can be nested?

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
