### ISSUE TITLE
Very important information omitted in the intro to the algorithms

### ISSUE THREAD

**Issue by JB-Walker** [freeCodeCamp/freeCodeCamp#16111]
The intro to the algorithm challenges is a great idea, but it makes no mention of the fact that the 'hint' section is now providing more than hints - it is now beginning to  include basic, intermediate, and advanced solutions to the challenge. After people solve their algorithms, they can now compare their solutions to the approach that a professional developer would take. These solutions are an invaluable learning tool, but people need to be told that they are now being included.

I didn't learn about the presence of these solutions until I had completed all of the basic algorithm challenges and 90% of the intermediate challenges. Now I am having to backtrack and review 35 previous lessons to learn what I may have missed. It didn't need to be this way. I strongly suggest modifying the intro to make it plain that the 'hint' section now provides more than hints and making the intro mandatory so that no one else will miss this important information.

https://www.freecodecamp.org/challenges/get-set-for-our-algorithm-challenges

**Comment by blairfrandeen** [comment]
I would like to second this, and add that the "flow" of completing challenges (particularly algorithm challenges) should be changed to encourage users to compare their solution to other solutions prior to pressing ctrl+enter to move on to the next challenge. It's too easy to pass the challenges with inefficient code or poor practices. I've learned a great deal from reading through and understanding the solutions, both on freeCodeCamp and on CodeWars.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
