### ISSUE TITLE
Move take-home project examples to freeCodeCamp's Glitch account

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16118]
- [x] [Book trading club](https://beta.freecodecamp.org/en/challenges/coding-interview-take-home-projects/manage-a-book-trading-club) - Needs to remix [the Book Trading Club on Glitch](https://thing-exchange.glitch.me/books), update .env, and update challenge description
- [x] [P2P Video app](https://beta.freecodecamp.org/en/challenges/coding-interview-take-home-projects/p2p-video-chat-application) - this is currently on Glitch but we need to "remix" it, update .env and the URL on the challenge
- [x] [Pinterest clone](https://beta.freecodecamp.org/en/challenges/coding-interview-take-home-projects/build-a-pinterest-clone) - this is currently on Glitch but we need to "remix" it, update .env and the URL on the challenge

--------------------
Remixed project urls:

Book Club: https://chrome-delivery.glitch.me/ (Github login only)
Pinterest: https://wild-song.glitch.me/
P2P: https://grove-voice.glitch.me/

**Comment by Em-Ant** [comment]
@karuppiah7890 are you the owner of the [p2p chat](https://unequaled-cement.glitch.me/) glitch project ? It works but I cannot access the code to remix it. Is it private ? I found a similar public project on your glitch account, but it doesn't work. If you are the owner of the working project, can you please give me access to the source code ? You can drop a comment here or reach me in gitter.

**Comment by karuppiah7890** [comment]
I don't think the source code should be visible since it's a challenge and
no one should try to see the code. And I will check with Quincy and let you
know about moving the project to glitch, since I don't know much about
this.

And about the other similar public project, I will check on it :)

**Comment by Em-Ant** [comment]
@karuppiah7890 to remix the project under the FCC glitch account (as stated in the description of this issue) I need to access your project's source page. Then the project can be made private again in FCC if it's ok with Quincy. You can even make it public just for 10 minutes, and let me know when you are ready, if you want. Anyway please check with @QuincyLarson,  and let me know. Thanks.

**Comment by karuppiah7890** [comment]
Oh, I am sorry. Now I get it that you want to keep it private under FCC's
glitch account. Makes sense. I also thought about this when I put up the
challenge with my project link. But I was careful not to delete it so the
links don't get broken. I will make it public and comment here. The project
is also in my GitHub account as "p2p-videochat" but I have to check which
one is up to date

**Comment by Em-Ant** [comment]
@karuppiah7890 I fixed the non-working public app, and remixed it.

**Comment by Em-Ant** [comment]
[PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/16172) ready !!!

**Comment by raisedadead** [comment]
@Em-Ant great work.. thanks a lot.

**Comment by raisedadead** [comment]
I am linking more topics as I find. If that's okay? Or do we want to track them separatly to be easy for you?

**Comment by QuincyLarson** [comment]
@Em-Ant Awesome! Thank you for moving these!

**Comment by billionairekid89** [comment]
How can I unsubscribe

**Comment by texas2010** [comment]
@billionairekid89 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!
