### ISSUE TITLE
Make Instances of Objects with a Constructor Function - Can pass using a plain object

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#16112]
#### Challenge Name

https://www.freecodecamp.org/challenges/make-instances-of-objects-with-a-constructor-function

#### Issue Description

It is possible to pass the challenge by assigning `myCar` with a plain object, then giving it `wheels` and `nickname` properties.

Related forum post:
https://forum.freecodecamp.org/t/make-instances-of-objects-with-a-constructor-function-right-code/160347

#### Your Code

```js
var Car = function() {
  this.wheels = 4;
  this.engines = 1;
  this.seats = 5;
};

// Only change code below this line.

var myCar = {};

myCar.nickname = "Betsy";
myCar.wheels = 4;


```
#### Screenshot

![image](https://user-images.githubusercontent.com/17902987/33124518-355d5baa-cfb8-11e7-9e9e-4d47c71aa177.png)

**Comment by cdrainxv** [comment]
I would love to take this up. I've noticed that this challenge is not in the staging branch, but it's in the [backup/master](https://github.com/freeCodeCamp/freeCodeCamp/blob/38fbd6651f37d917f7bb4a1377b3d2676f8838d1/seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json#L114). Am I right in assuming that I can send the fix to that branch?

**Comment by raisedadead** [comment]
Hi, @cdrainxv 

If you fail to find the challenge then its an indicator that it was chosen to be removed in favor of a better challenge/example or replacement.

At @kevcomedia do you think we would need this in the new curriculum? I would like to know your opinion.

Else this can be closed.

Happy coding!

**Comment by kevcomedia** [comment]
I wanted to make a quick run through the new JavaScript challenges, but I can't navigate to any of them. But if there are better challenges than this one in the new curriculum, then there's probably no reason to keep this.

**Comment by raisedadead** [comment]
Oh snap, yes. I know its being worked upon. Lets keep this open.

**Comment by QuincyLarson** [comment]
@kevcomedia Now that our newly updated platform is live, are we able to fix this issue? We would welcome your help with it :)

**Comment by kevcomedia** [comment]
I think the closest exercise to the old one is [Object Oriented Programming - Use a Constructor to Create Objects](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/use-a-constructor-to-create-objects). It looks fine as it is IMO.

However the next one ([Extend Constructors to Receive Arguments](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/extend-constructors-to-receive-arguments)) has a similar quirk to the old exercise. This code passes:

```javascript
function Dog(name, color) {
  this.name = name;
  this.color = color;
  this.numLegs = 4;
}

var terrier = new Dog(); // should be `new Dog('Doggo', 'brown')`
terrier.name = 'Doggo';
terrier.color = 'brown';
terrier.numLegs = 4;
```

Maybe we need to test if `Dog()` was called with the right arguments?

**Comment by addv12345** [comment]
I tried to access the problem using the link that was provided but it directed me to the main curriculum page instead. Is this exercise removed from the freeCodeCamp curriculum? If so, this ticket should be closed.

**Comment by thecodingaviator** [comment]
@addv12345 That is the only challenge where we are having this problem. Right?

**Comment by thecodingaviator** [comment]
The latest version of the repository available at [freecodecamp.rocks](https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/object-oriented-programming/extend-constructors-to-receive-arguments) has this problem fixed with an additional test.

I'm closing this issue, if you feel like it has not been fixed, add further clarification and reopen the issue

**Comment by raisedadead** [comment]
Just to note on @thecodingaviator 's comment.

This issue is fixed on our upcoming version, which you can test on the beta website we will push these fixes to the main production version in the upcoming weeks..
