### ISSUE TITLE
[beta] cannot use/navigate to any challenge.

### ISSUE THREAD

**Issue by a7mam7ma** [freeCodeCamp/freeCodeCamp#16129]
#### Issue Description

I can't navigate to any of the challenges either by clicking on its link in map or by finishing the getting started challenge.

it gives me a `something went wrong` message after i get to the final step of the getting started challenge and nothing happens if i click on a challenge link from map or copy paste the link of the challenge from the map.

#### Browser Information

* Browser Name, Version: Google chrome Version 62.0.3202.94 (Official Build) (32-bit)
* Operating System: Windows 7 
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

this is the console error it throws ad 

#### Screenshot

![image](https://user-images.githubusercontent.com/22580554/33319775-7f61bef0-d448-11e7-8093-d330880e3e68.png)

the console error it throws at me if i click on finish challenge
![image](https://user-images.githubusercontent.com/22580554/33319891-0a1c6b30-d449-11e7-9937-5ba0a77d5f98.png)

**Comment by raisedadead** [comment]
Hi @a7mam7ma,
 
This could be a build issue. 

Just to note that beta is heavily being patched right now, for QA. Some unstablity is hence expected.
Please keep reporting. 

Thanks for your contribution and happy coding!

**Comment by wahajs00** [comment]
same isuue with me can able to click link

**Comment by a7mam7ma** [comment]
i tried testing it in a remote desktop machine using (rabb.it) and the beta website worked with me flawlessly so i think you are right.

but my local machine keeps giving me the same error message and a request time out in the console, i will keep on testing every now and then to check if it is stable.

**Comment by BerkeleyTrue** [comment]
@a7mam7ma Can you try a hard refresh (ctrl + shift + r)?

**Comment by a7mam7ma** [comment]
@BerkeleyTrue yeah and i tried incognito mode too, same problem.

**Comment by onelharrison** [comment]
Info: I'm able to navigate just fine on Firefox Quantum and Chrome 63.

**Comment by raisedadead** [comment]
@onelharrison are you on windows as well.

**Comment by onelharrison** [comment]
@raisedadead Yes, I'm on windows 10.

**Comment by raisedadead** [comment]
@onelharrison Thanks for the additional clarification.

**Comment by raisedadead** [comment]
Closing in favor of linked issue.
