### ISSUE TITLE
Change coloro of text missing semicolon

### ISSUE THREAD

**Issue by mazer-rakham** [freeCodeCamp/freeCodeCamp#16127]
#### Challenge Name
https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-change-the-color-of-text/16775

#### Issue Description
The semicolon is missing and confusing people. I had someone I recommended this course to have issues. 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by cdrainxv** [comment]
The semi-colon isn't necessarily if you only have one style in the element. It's only required to separate multiple styles.

**Comment by mazer-rakham** [comment]
I know that, but your course is not letting it pass with one style and no semicolon

**Comment by mazer-rakham** [comment]
*the course

**Comment by raisedadead** [comment]
Hi, 

We have updated such wiki articles on our new guides platform. Please visit https://guides.freecodecamp.org and feel free to add/edit as necessary.

Now coming to the issue being discussed over here:

@mazer-rakham I request you to please share the details following this template (that you were also presented while reporting)

https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/staging/.github/ISSUE_TEMPLATE.md

This will help us reproduce your exact issue and resolve this.

Thanks and happy coding.
