### ISSUE TITLE
Reset Password Link on freecodecamp.org is returning a "Oops! Something went wrong. Please try again later"

### ISSUE THREAD

**Issue by KentShikama** [freeCodeCamp/freeCodeCamp#16137]
#### Issue Description

1. Navigate to https://www.freecodecamp.org/forgot (make sure to be logged out)
2. Send yourself a reset link
3. Click the email link and try to reset your password
4.  See the "Oops! Something went wrong. Please try again later"

#### Browser Information

* Browser Name, Version: Firefox, 58
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

**Comment by Beesu** [comment]
why？




发自网易邮箱大师
On 12/01/2017 18:16, Kent Shikama wrote:
Issue Description
Navigate to https://www.freecodecamp.org/forgot (make sure to be logged out)
Send yourself a reset link
Click the email link and try to reset your password
See the "Oops! Something went wrong. Please try again later"
Browser Information
Browser Name, Version: Firefox, 58
Operating System: Ubuntu 16.04
Mobile, Desktop, or Tablet: Desktop

**Comment by Beesu** [comment]
Who are you? I don't know you




发自网易邮箱大师
在2017年12月01日 18:17，18589530119@163.com 写道：
why？




发自网易邮箱大师
On 12/01/2017 18:16, Kent Shikama wrote:
Issue Description
Navigate to https://www.freecodecamp.org/forgot (make sure to be logged out)
Send yourself a reset link
Click the email link and try to reset your password
See the "Oops! Something went wrong. Please try again later"
Browser Information
Browser Name, Version: Firefox, 58
Operating System: Ubuntu 16.04
Mobile, Desktop, or Tablet: Desktop

**Comment by KentShikama** [comment]
It works now!

**Comment by texas2010** [comment]
@Beesu 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!
