### ISSUE TITLE
Passing Values to Functions with Arguments

### ISSUE THREAD

**Issue by yinsang** [freeCodeCamp/freeCodeCamp#16141]
#### Challenge Name

Passing Values to Functions with Arguments
https://www.freecodecamp.org/challenges/passing-values-to-functions-with-arguments

#### Issue Description

I am a old hand for javascript .
first of all；
I used
` const functionWithArgs = ()=> {
//something;
}
`
the first time didn't passed; 
and then I wrote the right code,bug   I can't passed it from here; I was so confused !
I saw the hint and github issue ,but cant found why;
sometimes later, I got the answer!
this is the reason:
the dev console had an error for `Uncaught SyntaxError: Identifier 'functionWithArgs' has already been declared`
and you will never passed it from then;
unless you create a new tab in the browser to copy the url to it; 
it's all because of the `const` , oh my god~!
is it a bug ?hia hia hia;
:)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



// Example
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.
function functionWithArgs (a,b) {
  console.log(a+b);
  return a+b;
}
functionWithArgs(1,2);

functionWithArgs(7,9);
```

**Comment by krisb1220** [comment]
Your example uses ES6 Arrow Functions but does not declare it in the js hint comment. Here's my code that I used to fix your "const" issue

```javascript
//jshint esversion: 6
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.
const functionWithArgs =  (a,b) => {
  console.log(a+b);
  return a+b;
};
functionWithArgs(1,2);

functionWithArgs(7,9);
````
