### ISSUE TITLE
Domain name in Twitch API passthrough instructions and actual domain name don't match

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#16148]
#### Challenge Name

https://www.freecodecamp.org/challenges/use-the-twitchtv-json-api

#### Issue Description

The domain name in the Twitch API passthrough instructions (`https://wind-bow.gomix.me/twitch-api`) doesn't match the page's actual domain name (`https://wind-bow.glitch.me/`). Using the `gomix.me` one for the project causes a CORS warning, while using `glitch.me` doesn't.

The link in the project page also still says `gomix.me` (although it redirects to `glitch.me`).

**Comment by littledago22** [comment]
Stop with the emsils

**Comment by raisedadead** [comment]
Hi @littledago22 ,

Looks like you have subscribed to all emails from freeCodeCamp.
Please follow the link below for how to unsubscribe:

https://forum.freecodecamp.com/t/faq-unsubscribe-from-github-emails-on-issue-tracker/78944

Happy Coding!

**Comment by raisedadead** [comment]
Hi @kevcomedia thanks for pointing. We have removed this challenge on staging.

This line needs to be updated, changing `gomix` to `glitch` at all its occurrences.

https://github.com/freeCodeCamp/freeCodeCamp/blob/122f685f769d699e52deac2c1dd34fe50ee8169e/seed/challenges/01-front-end-development-certification/intermediate-ziplines.json#L171

**Potential contributors:**
Please make a pull-request against the `backup/master` branch. Follow the guidelines on the [`backup/master`](https://github.com/freeCodeCamp/freeCodeCamp/blob/backup/master/CONTRIBUTING.md) branch (and not the staging, only for this issue).

**Comment by urohit011** [comment]
I would like to take this. Can you please help me in getting started?

**Comment by raisedadead** [comment]
Sure, you can start by setting up the local dev environment. If you are stuck reach out to the 
[Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by raisedadead** [comment]
This is still open for contribution on the `staging` branch.

**Comment by nathanhannig** [comment]
I will work on the staging branch to add the missing UPDATE and correct the url

**Comment by raisedadead** [comment]
@nathanhannig awesome, thanks a lot!
