### ISSUE TITLE
More specific language on non-profit projects

### ISSUE THREAD

**Issue by IsaacAbrahamson** [freeCodeCamp/freeCodeCamp#16144]
A person just asked on our forums about waiting to hear about being accepted to a non-profit project, and this is a semi-regular occurrence. I think we should change some language to make it more clear that campers are building applications used by non-profits, not working for non-profits directly as was the case in the past.

**Comment by IsaacAbrahamson** [comment]
Also, I'd like to have a go at rewording some of it, but I can't find where the main page is... can someone direct me to the file?

**Comment by raisedadead** [comment]
Hi @IsaacAbrahamson I am not sure if I understand which text they are referring to. Can you let us know which page on the website are they referring for more clarity? I'll be sure to find the code for you?

**Comment by raisedadead** [comment]
@IsaacAbrahamson please reopen when you have more information, requested above. We closing issues while we prioritise on beta.

**Comment by IsaacAbrahamson** [comment]
@raisedadead, yes sorry, I completely forgot about it. Please focus on the beta, I need to ask some of the users about their confusion.

**Comment by raisedadead** [comment]
Sure, thing... I am tagging @QuincyLarson to follow along just in case, he has any idea on this any way.

He is usually getting a lot of queries or so I believe.
Thanks once again!

**Comment by IsaacAbrahamson** [comment]
@raisedadead, a person just asked again about this on the forums 20 minutes ago, so I think nows a good time to at least bring it up. Here are the most recent questions:

The most recent one from today:
https://forum.freecodecamp.org/t/how-long-time-wise-is-the-waiting-list-for-nonprofit-projects/163619

A few others from the past few months:
https://forum.freecodecamp.org/t/ive-got-my-certificates-now-what/162069

https://forum.freecodecamp.org/t/will-new-freecodecamp-have-nonprofit-projects/152180

https://forum.freecodecamp.org/t/do-we-not-get-to-work-for-non-profits-anymore/153906

https://forum.freecodecamp.org/t/when-to-start-with-non-profits/141609

https://forum.freecodecamp.org/t/the-nonprofits-proyects-can-not-be-reached/134399/3

https://forum.freecodecamp.org/t/information-on-non-profit-projects/136383

https://forum.freecodecamp.org/t/where-did-the-non-profit-coding-section-go/141307

https://forum.freecodecamp.org/t/confused-on-how-to-proceed-for-full-stack-certificate/140954

https://forum.freecodecamp.org/t/did-anyone-finished-3-certificate-and-arent-chosen-for-non-profit-project/119163

https://forum.freecodecamp.org/t/open-source-for-good/141352

**Comment by raisedadead** [comment]
Great thanks for bringing this up. Although not a direct code-base issue, we should be adding the clarifications to the about or similar FAQ sections.

@QuincyLarson you are probably the best person to clarify these queries, or at least set the guidelines for such.

**Comment by raisedadead** [comment]
And @IsaacAbrahamson great work compiling all these together! 👍 ✨

**Comment by QuincyLarson** [comment]
@IsaacAbrahamson Yes - there may be confusion since we called it "open source for good" on the map. I can rename it.

**Comment by IsaacAbrahamson** [comment]
Thanks, @QuincyLarson, hopefully, this will make it more clear to people!
