### ISSUE TITLE
Bug preventing the last IDE line from being usable

### ISSUE THREAD

**Issue by StevenDStanton** [freeCodeCamp/freeCodeCamp#16154]
#### Challenge Name
Effects various challenges at different times

#### Issue Description
At certain points the very last line on the IDE is not usable. You can bypass this by clicking just before the last line of code and pressing back space I Found. Video below

Chrome 62.0.3202.94
Windows 10 Profesional
Desktop

#### Screenshot
https://www.youtube.com/watch?v=cv3--_Hy1Qk

**Comment by raisedadead** [comment]
Hi @StevenDStanton 

Thanks for reporting. 

Unfortunately this has been an issue that we have seen in the past that keeps coming back. 

Do you mind taking a screenshot of your DevTools console tab?
You can do so Hit <kbd>F12</kbd>, and then select the console tab, or hit <kbd>Esc</kbd>

Then simply take a screenshot (video not required).

**Comment by raisedadead** [comment]
In any case, anyone interested in investigation, please look in the `backup/master` branch. 
I am guessing this has something to do with the wrapping and code-mirror.

**Comment by StevenDStanton** [comment]
I have taken the Screenshot, however, I doubt it will be of much use as the console is completely empty. 

If you want a list of addons I use I can provide that as well

![ss](https://user-images.githubusercontent.com/7123954/33680748-9502107c-da90-11e7-8c6c-a9b48192561a.png)

**Comment by raisedadead** [comment]
Nope, I don't think add-ons are an issue here. You can quickly confirm this by simply launching an incognito window(which has all add-ons disabled).

**Comment by JosephLivengood** [comment]
@raisedadead Im looking into it, Im able to get reproducible behavior where the cursored line is dependent on how many lines get wrapped how much

**Comment by raisedadead** [comment]
@JosephLivengood Awesome! Thanks for looking into it.

**Comment by JosephLivengood** [comment]
@raisedadead The source is the css/page changing after the editor has been configured and initiated. I cannot determine exactly what it is and I'm sure it will differ from people but I do have a catch-all solution working that also fixes this issue when lines are wrapping strange.

Basically, `editor.on('mousedown', () => editor.refresh() );`, which is uses the only solution CodeMirror has (to call refresh after everything is confirmed loaded).

Is there somewhere in the base Im not familiar with that is called/recognizes when the entire challenge page is loaded? If so I can put the fix exclusively there. If not, should the method I have here be completed and PR'd?

**Comment by raisedadead** [comment]
@JosephLivengood 

Great! I get what you mean. I don't remember exactly how we had tackled this the last time, with cursor jumps.

So, coming to your query:
For the `staging` branch I am not sure if we have this issue, but if we do, it should be something like hooking on to the `componentDidMount` or similar for the editor component. Maybe @BerkeleyTrue can guide more on that.

For the `backup/master` I don't know for sure if there is a way for adding this, but your trick should do the job. If I understand correctly, you want to refresh as soon a user clicks/focuses the editor. That said, maybe this can rather be obsolete when we ship the beta.

May be you can check if we are having similar issues?

P.S: For anyone, coming to this issue first time, Joseph is proposing a re-render of the editor as close to as the editor is ready for input as possible.

**Comment by JosephLivengood** [comment]
@raisedadead Ill look into reproduction and fixing it on `staging` tomorrow. Should the fix that works on the live version be pr'd against `backup/master` as well?

**Comment by raisedadead** [comment]
Yeah, sure why not. If you have something ready, lets add this.

**Comment by JosephLivengood** [comment]
Should be easy to get the `staging` version once I get to the correct component and test it tomorrow. PR incoming for `backup/master` now.

**Comment by raisedadead** [comment]
@JosephLivengood I'll go ahead and close this, we have several updates being landed on the staging so its, more suitable to check after we have shipped beta.

Thanks a lot for fixing this on production.

@StevenDStanton Please check at your side, if the issue has resolved. We have pushed the patches to the website! 

Happy coding!
