### ISSUE TITLE
Gitter chat rooms archiving

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16158]
Moved from https://github.com/freeCodeCamp/freeCodeCamp/issues/8418 owing to its freshness

As mentioned by `@evaristoc` 

----
New rooms scheduled for archiving:
* FreeCodeCamp/NewYorkCity (id: 5593982115522ed4b3e3263f)
*  FreeCodeCamp/CoreTeam

Currently exploring `@abhisekp` approach to archiving before initiating the process of downloading the  data:

https://github.com/freeCodeCamp/freeCodeCamp/issues/8418#issuecomment-238083019
https://github.com/freeCodeCamp/freeCodeCamp/issues/8418#issuecomment-269025399
https://github.com/freeCodeCamp/freeCodeCamp/issues/8418#issuecomment-258058263

----
`@QuincyLarson` :

I was trying to use the great package made by `@abhisekp`: npmjs.com/package/gitter-archive-cli but unfortunately it didn't work on my computer. It is giving a 404 error that I am finding hard to debug.

I will likely work this on Python. My current code seems to be outdated though. Apparently I am also affected by the rate limits with an 459 error - didn't happen before, I managed to download
messages over the limit in March 2017 with a simpler code.

If it works, I will make my Python code available. Hoping that will help to find a standard code to approach chatroom-archiving in the future.

----

Another, simpler option by `@ladybugtju` :
https://github.com/ladybugtju/ffcGitterData/blob/master/fccGitterData.js

----
This is a previous message by `@abhisekp` to be kept here as reference: https://github.com/freeCodeCamp/freeCodeCamp/issues/8418#issuecomment-252860430

**Comment by evaristoc** [comment]
Thanks, @raiseadead!

**Comment by QuincyLarson** [comment]
@raisedadead Awesome - sounds good. It's a shame @abhisekp's tool doesn't seem to work at the moment, because I could imagine a lot of communities being able to use that. But if it's faster to just download the data using Python, that works too :) Thanks for digging into this!

**Comment by evaristoc** [comment]
@QuincyLarson 

No worries. My code is currently in Python so it is easier to modify that one.

Sorry for being too late though - I made a wrong assumption about the behaviour of the duration of the download process worsened by a line in my code and I entered into EXPONENTIAL TIME (0o0) when downloading data from the Casual room. THREE DAYS DOWNLOADING DATA!! First time in my life, never happened to me before. But glad that happened : Makes me a better coder :) .

I made the corresponding amendments and although not perfect it is much better now.

**FreeCodeCamp/NewYorkCity (id: 5593982115522ed4b3e3263f)**:
- [x] Download
- [ ] Compression
- [ ] Push Request
FreeCodeCamp/CoreTeam:
- [ ] Download
- [ ] Compression
- [ ] Push Request

**Comment by QuincyLarson** [comment]
@evaristoc Thrilled to see this backup underway! Let me know if I can do anything to help :)

**Comment by evaristoc** [comment]
/home/ec/Documents/MainComp_Programming/FreeCodeCamp/chatrooms_deprecated/newyorkcity_chatroom.json.tar.gz

**Comment by evaristoc** [comment]
**Update**:
[x] FreeCodeCamp/FreeCodeCamp : a download that included data until 9 Dec 2017 was made available in Kaggle

We are having other ones currently in the list. I will keep updates for those rooms that were downloaded in this thread.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
