### ISSUE TITLE
Donate Page Not working

### ISSUE THREAD

**Issue by kudzaidotnet** [freeCodeCamp/freeCodeCamp#16150]
The link to the "Donate" page on the following page: https://www.freecodecamp.org/challenges/become-a-supporter ....... is going to an error page: https://donate.freecodecamp.org

Can i fix it? I'm new to GitHub!

![2017-12-06](https://user-images.githubusercontent.com/33347607/33668133-7a3853e0-da64-11e7-8a86-1f9cb8b86143.png)

**Comment by raisedadead** [comment]
This is working for me. Can you check again and maybe try a hard refresh?

**Comment by raisedadead** [comment]
I am going to go ahead and close this. Please let us know if this is still broken.

**Comment by QuincyLarson** [comment]
@kudzaidotnet This is the only instance I've heard of regarding the donate page being inaccessible. I'm going to close this issue, but let me know if you're still having problems getting it to load.
