### ISSUE TITLE
Confusing Instructions for React Challenge 2 => Build a Campers Leaderboard

### ISSUE THREAD

**Issue by rajatvijay** [freeCodeCamp/freeCodeCamp#16157]
#### Challenge Name
Build a Camper's Leaderboard

https://www.freecodecamp.org/challenges/build-a-camper-leaderboard

#### Issue Description

The description of this challenge is confusing:

1. The video provided shows older objectives.
2. The API shown in the video is also diff than the one provided in the objectives
3. It is also not clear whether we have to make an API call or we can just get the data using copy/paste.
4. The reason for providing two APIs are also not clear. Since it seems both provides the same data(maybe) or just the ordering is diff. 
5. Or if one provides top 100 according to all time and other according to recent then, should we make an API call for sorting?
6. How the sorting is to be done is also not clear.    

#### Screenshot

![screenshot-www freecodecamp org-2017-12-08-14-43-44-103](https://user-images.githubusercontent.com/11032856/33758953-77e6610e-dc26-11e7-85be-c83ff4477c39.png)

**Comment by raisedadead** [comment]
Hi thanks, for reporting. Yes this challenge has gotten stale with the old videos. We are doing away with this challenge and moving it to the Take home projects on our new curriculum 

One of the team members (@Em-Ant) is migrating the same under our ownership to Glitch.

I understand that this is a required project on the Certification path on the production site. 
@QuincyLarson can you please guide what are we planning to mitigate this on the current production?

**Comment by raisedadead** [comment]
Update: Here is the link on how its going to work going forth https://forum.freecodecamp.org/t/freecodecamps-new-certificates-heres-how-were-rolling-them-out/141618

**Comment by raisedadead** [comment]
To be moved in https://github.com/freeCodeCamp/freeCodeCamp/issues/16118

**Comment by QuincyLarson** [comment]
@rajatvijay Thanks for pointing this out. We are removing the videos completely on beta. So this inconsistency will cease to exist in a couple weeks when we ship beta.
