### ISSUE TITLE
Consider adding Subresource integrity to Bootstrap code examples.

### ISSUE THREAD

**Issue by Mandihamza** [freeCodeCamp/freeCodeCamp#16163]
#### Challenge Name

Bootstrap: Use Responsive Design with Bootstrap Fluid Containers

#### Issue Description

Subresource Integrity (SRI) is a security feature that enables browsers to verify that files they fetch (for example, from a CDN) are delivered without unexpected manipulation.

#### Browser Information

* Browser Name, Version: Chrome 63.0.3239.84 
* Operating System: macOS 10.12.6 (16G1036)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

https://github.com/Mandihamza/freeCodeCamp/commit/be26e9bd21a0f8454c5525db2692ab924d07837d

#### Screenshot

![image](https://user-images.githubusercontent.com/23363171/33788665-b2def24e-dc30-11e7-9589-0f877ed30f27.png)

**Comment by raisedadead** [comment]
@Mandihamza awesome, could you please make the pull request?

**Comment by Mandihamza** [comment]
Hey @raisedadead! Sure, do you want me to add hashes to the other examples as well, or just make a PR for this commit? Here you can see similar places where the same update can be made: https://cl.ly/2X2H2g1D090B.

**Comment by raisedadead** [comment]
Hi @Mandihamza ! Yup, while you are at, you can add them all to your PR. Thanks a lot.

**Comment by Mandihamza** [comment]
@raisedadead I'm having some issues with the squash.  Can you point me in the right direction?
