### ISSUE TITLE
[beta] Fix the UI of the static Public Profile

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16168]
We are doing a overhaul for the public profile page by a upgrading them to react pages.
Refer: https://github.com/freeCodeCamp/freeCodeCamp/issues/15942
Refer: https://github.com/freeCodeCamp/freeCodeCamp/issues/15729

But, while that is deferred to until after the release of beta, we want fixes to the currently broken UX on the setting page which is a static server rendered page available here:

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/server/views/account/show.jade

As of this issue post it renders like so:
![profile](https://user-images.githubusercontent.com/1884376/33795990-cdd19f52-dd11-11e7-8166-43e0ddf54c50.gif)

**Comment by onelharrison** [comment]
@raisedadead, I'll tackle this.

**Comment by anhtran1906** [comment]
Hi I have a question about sign-in functionality on the beta site (on branch staging). I registered an account on the live site but when I reused the email account on the beta site on my local host, the site does not allow me to sign in (I've never received an email from this message)
<img width="1486" alt="screen shot 2017-12-09 at 4 04 31 pm" src="https://user-images.githubusercontent.com/20694114/33799519-71d245c8-dcfb-11e7-8603-2dbdb30e6017.png">
Am I missing something or how could I sign in on beta site to contribute help to sign-in related issues?

**Comment by onelharrison** [comment]
@anhtran1906, you have to setup up mailhog. Then, you can use whatever email to sign in locally. Mailhog will capture any outgoing emails sent by the local fcc app. See [CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) for more details.

**Comment by anhtran1906** [comment]
@onelharrison Thanks for your comments. I asked the question in Gitter also so I deleted mine on here to avoid duplication. @raisedadead I also found this UI issue of the available-to-hire button on the Profile page:
![availabletohire-button-ui-issue](https://user-images.githubusercontent.com/20694114/33799702-dcad269e-dcfe-11e7-9fb1-fe04202d258d.gif)
Basically when you resize your browser window, the label on the button "Unavailable" will be out of the button box. A quick fix I could think of is to change the label into "Yes" and "No" to avoid long texts.
Should I open this as a separate issue and refer to this issue?

**Comment by raisedadead** [comment]
@anhtran1906 
> A quick fix I could think of is to change the label into "Yes" and "No" to avoid long texts.
> Should I open this as a separate issue and refer to this issue?

Yes, please. If we do not have a issue logged already. Thanks.

**Comment by anhtran1906** [comment]
@raisedadead Thanks for confirming. I opened the issue at #16175. Please confirm the tags on the issue and my solution so I could go ahead and fix it.
