### ISSUE TITLE
[beta] Search Challenges in Map

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16166]
- [ ] Add Search box on the map similar to previous version.
- [ ] Search should be fuzzy.
- [ ] Search should be available from all pages.

**Comment by BerkeleyTrue** [comment]
We removed this feature. We will adding in @Bouncey 's search feature as a replacement.

Happy Coding

**Comment by raisedadead** [comment]
Hi @BerkeleyTrue 

We might anticipate Navigation UX issues a lot after we ship the new batch of challenges.

Sure, I don't know the motivation behind removing the search, currently its annoying to reach any challenge while browsing. Even more is the case for ability to fuzzy search like we can in the production. 


I am not sure, if you are talking about the Elastic Search Feature which I remember @QuincyLarson mentioning? If yes, then it maybe a while before we have that.

Isn't that supposed to be able to search everything on freeCodeCamp (guides, forum, etc.)?

> The scope of this issue is to have, a light weight UI component similar to that we have on production, for quick navigation.

**Comment by QuincyLarson** [comment]
@raisedadead I'll check with @Bouncey and see whether he can incorporate his search box into the nav bar in advance of shipping beta.

**Comment by raisedadead** [comment]
Sure, @QuincyLarson in that case, lets leave this open and blocked.

**Comment by QuincyLarson** [comment]
@raisedadead Sounds good. @Bouncey is making rapid progress on this: https://www.npmjs.com/package/react-freecodecamp-search

**Comment by raisedadead** [comment]
@QuincyLarson thanks for the updates.
