### ISSUE TITLE
[beta] Toggle Collapse Map

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16167]
- [ ] Add toggle collapse to the Map

**Comment by rossijonas** [comment]
I've forked FCC today... I'll try my first open source contribution and this issue seems a good point to start. Is there anyone already helping this one?

**Comment by raisedadead** [comment]
Hi @rossijonas thanks for looking into this, this might be taken care of until after beta is shipped. I recommend you should start with the issues labled as "help wanted" on the tracker.

You can hang out with us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), for any assistance.

Thanks and Happy coding!

**Comment by BerkeleyTrue** [comment]
@QuincyLarson Thoughts on this. I remember at some point we decided to remove the buttons on the map feature.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue Yes - they are all collapsed by default and you can drill into them. 

@raisedadead We don't want to complicate the UI with buttons. I think https://devdocs.io does a great job of this - a clean, intuitive, unambiguous sidenav.

So I'm going to close this issue.
