### ISSUE TITLE
[beta] Instruction content overflow

### ISSUE THREAD

**Issue by onelharrison** [freeCodeCamp/freeCodeCamp#16174]
#### Issue Description

I first noticed this issue on [adjust-the-margin-of-an-element](https://beta.freecodecamp.org/en/challenges/basic-css/adjust-the-margin-of-an-element). The contents of the instruction section overflow their boundaries. 

I also noticed the same issue in multiple other challenges.

#### Browser Information

* Browser Name, Version: Firefox Quantum, Google Chrome 63
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

<img width="668" alt="fcc margin overflow" src="https://user-images.githubusercontent.com/10459779/33808662-694eedb2-ddb8-11e7-9292-94358741771c.png">

**Comment by raisedadead** [comment]
@onelharrison thanks for the report, while this is something we are already aware off. 

We maybe wating for the core challenge infrastructure to be ready, before diving into the UX. Please keep reporting any such issues.

This is primarily becasue we can then focus on having a cleaner way to get the feedback and do some A/B testing.

/cc @QuincyLarson @BerkeleyTrue

**Comment by onelharrison** [comment]
@raisedadead, understood. I'll keep reporting anything I come across. Thanks for the info.

**Comment by oyin-k** [comment]
@raisedadead would it be fine if i find more of these issues and try to fix them?

**Comment by QuincyLarson** [comment]
@oyin-k Yes! Absolutely. We would love your help fixing these issues. If you see anything out of sorts, make sure there isn't already an issue. If there isn't one, go ahead and open it - no matter how small the issue may be. This will help us all a ton!

**Comment by 67shafar** [comment]
I can grab this one. 

It looks like all the Dividers have been shifted 4 pixels off center, and to the left.
It makes the left side of the rendered challenges-instructions-panel look as if it were padded, but causes issues on the right side.

I think it would make more sense to remove the offset and replace it with actual padding for the panel contents. 

I can submit a pull request for that.
