### ISSUE TITLE
[beta] Fix UI problem with the available-to-hire button

### ISSUE THREAD

**Issue by anhtran1906** [freeCodeCamp/freeCodeCamp#16175]
#### Issue Description
When you sign in to your account on the beta site and navigate to your Setting page by clicking "Update your setting" button, you will see the "Are you available to hire?" button to toggle between "Available" and "Unavailable". However, when you resize your browser window, the label on the button ("Unavailable"/"Available" will be out of the button box. A quick fix I could think of is to change the label into "Yes" and "No" to avoid long texts. Please confirm so I could go ahead and fix this bug.

#### Browser Information

* Browser Name, Version: Chrome 62.0.3202.94
* Operating System: MacOS Sierra 10.12.4
* Mobile, Desktop, or Tablet: Macbook

#### Screenshot
![availabletohire-button-ui-issue](https://user-images.githubusercontent.com/20694114/33808970-09b4688c-ddbd-11e7-9ad3-7022dce6439a.gif)

Related #16168

**Comment by raisedadead** [comment]
> A quick fix I could think of is to change the label into "Yes" and "No" to avoid long texts.

Agreed. Thanks for looking into this.

**Comment by anhtran1906** [comment]
@raisedadead thanks for confirming. Working on it now
