### ISSUE TITLE
Check if GitHub is already linked to an existing account

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16177]
Steps: 
- Create account for Alice and link it to GitHub profile of Alice via update profile.
- Sign out
- Create account for Bob and link it to GitHub profile of Alice via update profile.

We want to prevent this for user name collision that can come from this path.

**Comment by shabeermothi** [comment]
Hi. Am interesting in getting this feature done. How do i get started?

**Comment by inoabrian** [comment]
I will also try working on this issue.

**Comment by raisedadead** [comment]
Thanks guys. 

You might have to check the docs for [Loopback 3.0](https://loopback.io) and maybe looking into the [User-Credential.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/models/User-Credential.js) is a place to start understanding how it all ties together.

We don't have excellent documentation on our architecture. But that's what we have for now. Drop us comments here if you are unaware of something.

What we want is to check if a Credential/Identity Object is not already attached to the User. If yes, they we throw off an API error that its already linked or similar.

But, that said, we are keeping this as deferred until Beta is Shipped so please bear with the delays.

If you are just getting started with the code-base, we highly recommend taking a look at more issues that will give you a hang of our code-base.

Happy fixing!

**Comment by meda123** [comment]
Hi! I know two other people are working on this issue. Could I take a look as well? Looks like an interesting project.

**Comment by inoabrian** [comment]
@raisedadead 
I successfully setup the environment, could you please reiterate the bug and expected behavior.
"
What we want is to check if a Credential/Identity Object is not already attached to the User. 
If yes, then we throw off an API error that its already linked or similar.
"

Is this happening for all methods of sign-in that are not the default email?

**Comment by raisedadead** [comment]
@inoabrian awesome!

Nope, we are interested only in the GitHub update profile path. You just need the GitHub keys in ENV.

This can be reproduced with the steps in the opening post.

**Comment by inoabrian** [comment]
@raisedadead I will message you in the gitter chat.

**Comment by raisedadead** [comment]
Sure, anytime. Thanks a lot.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
