### ISSUE TITLE
New lessons weren't added to previous work.

### ISSUE THREAD

**Issue by JanetShuman** [freeCodeCamp/freeCodeCamp#16182]
#### Issue Description

I started yesterday with 116 completed lessons and did 54 more.  The 54 did not show up in my completed history.  In the screenshot, please note the 116 below my name and the 54 at the right.
How the issue developed:  I had used this early in the year and tried to login again and continue.  When I logged in, it showed me at [0] under my name.  Following advice from others in the forum, I navigated to the last lesson I had completed using the "Map" feature and began completing exercises.  The number went up to 54 as I completed lessons, however if I click on the "54", it still shows 116 under my name and does not show the other 54 added to that.  Also of note, when I login now it DOES direct me to the correct lesson (i.e. I am not on lesson number 55.)
Thank you!

#### Browser Information

* Browser Name, Version:  Version 63.0.3239.84 (Official Build) (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop

```
```

#### Screenshot

![image](https://user-images.githubusercontent.com/24833395/33852338-bc2509fa-de7f-11e7-9f58-bd866caef827.png)

**Comment by raisedadead** [comment]
Please note that the lessons are not numbered, those are your brownie points, https://forum.freecodecamp.org/t/free-code-camp-brownie-points/18380

Seems this is related to #16147

**Comment by QuincyLarson** [comment]
@JanetShuman Sorry for the inconvenience this bug has caused!  We are working on fixing this. I will close this issue in favor of our discussion about this bug on #16147
