### ISSUE TITLE
Wiki article request:

### ISSUE THREAD

**Issue by AshRoulston** [FreeCodeCamp/FreeCodeCamp#1618]
I think it would be helpful to have an article on the estimated time commitment per waypoint/bonfire. I know the program as a whole has an estimated time but would like to see 
Basic html5 and CSS (1 hour)
1. Waypoint title (1min)
2. Waypoint title (3min)
I would find this helpful because it wod allow me to set reasonable goals and daily tasks for myself.

**Comment by BerkeleyTrue** [comment]
This isn't something we want to do since it could lead to undue stress when a camper gets stuck. The important thing is understanding(to grok a thing is to become it). Speed comes with wisdom and experience. Timing should only be important when going back over challenges/previous work.

Happy Coding!

**Comment by AshRoulston** [comment]
It would be helpful to those of us with kids and obligations- knowing
whether I have the time to start and finish just one more waypoint or
should wait until next time. For example, many waypoints up until jQuery
took me minutes but the ones in jQuery are part of a 3 hour codeacademy
course which would've been helpful to know in advance.

**Comment by BerkeleyTrue** [comment]
cc @QuincyLarson

**Comment by benschenker** [comment]
@AshRoulston, we do have difficulty stars for the bonfires, and we no longer use the codeacademy course.  Is this still something you still want?

**Comment by AshRoulston** [comment]
Yes, see knowing approximately how long it will take me is important
because I have children. If I am looking at the map and know my kids are
napping, if it is something that takes 5min, I'd probably do it. If it
takes an hour, I'd probably postpone doing it.
I have been working through without it but sometimes things that look super
complex and time consuming are actually just a minute or two while some
stuff that looks easy has taken closer to 30min. I know that this will only
be more true as I get further into the program and I think that it would
help more than just me and other parents. If people are learning in their
spare time and have a 30min break at work, the heads up that it takes most
people 45 minutes would help them too. I also know that some people set
aside a specific time to study, 8-11pm, at 10:45 they wouldn't want to
start an hour long lesson.

**Comment by benschenker** [comment]
OK, @AshRoulston I'll leave this open if anyone wants to tackle it

**Comment by BerkeleyTrue** [comment]
Closing as stale. I'm still against this as any number would be just a guess. There is also the side effect of undue pressure for some.
