### ISSUE TITLE
[beta] Opening/Closing Map should scroll to current challenge

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16192]

**Comment by BerkeleyTrue** [comment]
> Yes - they are all collapsed by default and you can drill into them.

Going by @QuincyLarson statement here this is not the direction we want to go. @QuincyLarson thoughts?

**Comment by raisedadead** [comment]
Oh yes, I just realised that. If we are having search on the nav. I guess this is not necessary. Thanks.
