### ISSUE TITLE
Sort Arrays with .sort - confusing description of how it works

### ISSUE THREAD

**Issue by alaminos** [freeCodeCamp/freeCodeCamp#16190]
#### Challenge Name
https://www.freecodecamp.org/challenges/sort-arrays-with-sort

#### Issue Description
This description is highly confusing:

  _`sort `can be passed a compare function as a callback. The compare function should return a negative number if a should be before b, a positive number if a should be after b, or 0 if they are equal._

Here's what's wrong:

* It talks about a compare function but I do not think that the learner knows at this point what it is, and does it matter anyway for the completion of this exercise?

* The line
> if a should be before b
 
is very ambiguous. Are we talking about the function call line, ie. `function(a,b)`, or are we talking about the return line, ie. `return a - b` ? Or maybe both? It should be clearer to which of these lines we are referring to.

* Why are we talking about negative and positive numbers? How does that relate to an ascending or descending order? The relation should be stated.

#### Alternative
I am not sure how to improve it because I am not sure how .sort works, but something in the lines of this would have been very clear:

> If the function called by .sort returns a positive number, the array will be ordered in an ascending order, if a negative number is returned instead, then the array will be ordered in a descending order.

**Comment by angelfeliz** [comment]
I read the [Sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) documentation, and what I see in the challenge description is a very short summary that  may get confusion some campers, but I suggest to take @alaminos alternative and modified a little with:

>If the comparing function for a and b elements called by .sort returns a positive number, sort b to an index lower than a, if a negative number is returned instead, sort a to an index lower than b and if a cero is returned instead, leave a and b unchanged with respect to each other.

I think is good to keep the description of the challenge with the same words of the explanation link that is provide in the challenge. 

When the final suggestion for the description is decide, I will be happy to do the change in the challenge.

**Comment by Ayush-Rawal** [comment]
The compare function is not any 'named' or 'special' function, it can be any function that compares two elements of the same data type. Also the difference between f(a,b) and f(b,a) is just a matter of semantics as long as you define it appropriately.

While I believe the current description to be good enough, the description by @angelfeliz is indeed clearer.

P.S. not all objects can be compared by subtraction, say you might want to compare two strings, two lists or an object to name a few...

**Comment by ninadingole** [comment]
@alaminos @angelfeliz 
I feel to change the wordings as following:
`sort` can be passed a compare function as a callback like `.sort([compareFunction])`. The compare function should return a negative number if `a` is less than `b`, a positive number if `a` is greater than `b`, or `0` if both the values are equal. This returned value from the compareFunction will help the `.sort` method to decide the position of the element in the sorted array. 

A negative value pulls the element toward lower index i.e. `<- left side` of the current position, a positive value will push the element towards the higher index of the array i.e. `right side ->` of its current position and a `0` value will keep the element at the same position where it is.

**Comment by QuincyLarson** [comment]
@alaminos Are you still interested in helping update this challenge to make it clearer? 

We just launched the new learning platform and expanded curriculum here: https://learn.freecodecamp.org - take a look at it and let me know what you think :)

**Comment by Vimal-Raghubir** [comment]
Hi, could I potentially tackle this issue?

**Comment by QuincyLarson** [comment]
I'm closing this issue since we haven't heard back from @alaminos yet.
