### ISSUE TITLE
Wiki article request: The curse of CORS and how to overcome it

### ISSUE THREAD

**Issue by pdsoper** [FreeCodeCamp/FreeCodeCamp#1619]
If you're working on the Twitch Zipline and getting a error message instead of data, you are likely a victim of a Cross-Origin Resource Sharing (CORS) restriction.

I'd be glad to point to CORS documentation and explain how I solved it, but others would need to add to it to make the article complete.

**Comment by leonfeng** [comment]
I've made an entry here: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Zipline:-Use-the-Twitchtv-JSON-API. Please feel free to correct/expand.

**Comment by krisgesling** [comment]
I think the article mentioned above has been moved to:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Zipline-Use-the-Twitchtv-JSON-API

**Comment by bugron** [comment]
@pdsoper thanks for posting this issue!
@leonfeng thanks for creating that Wiki article, @krisgesling thanks for noticing that article has been moved to [Zipline Use the Twitchtv JSON API](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Zipline-Use-the-Twitchtv-JSON-API). 
Closing this issue as the article is created.
