### ISSUE TITLE
Cannot submit API Projects (Submitting refreshes the page)

### ISSUE THREAD

**Issue by anku255** [freeCodeCamp/freeCodeCamp#16191]
#### Challenge Name

[Timestamp Microservice](https://www.freecodecamp.org/challenges/timestamp-microservice)

#### Issue Description

I cannot submit any API Project after completion. When I enter the glitch and Github URL and press submit, it just refreshes the page. 

I have not used the boilerplate given by FCC and created my project from scratch. Please let me know if that's a problem. 

**Glitch URL App**
`https://timestamp-fcc-.glitch.me/`

**Glitch URL Project**
`https://glitch.com/edit/#!/timestamp-fcc-`

**Github**
`https://github.com/anku255/FreeCodeCamp/tree/master/API%20Projects/Timestamp%20Microservice`

#### Browser Information

* Browser Name, Version:  Chrome 62.0.3202.94
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Asus Laptop

**Comment by raisedadead** [comment]
We need help in assessment. Can any one check and confirm the issue in submissions? 
@anku255 do you have any screenshots? Could you also check your browser's Dev Tools console, for logs if any?

**Comment by raisedadead** [comment]
@anku255 were you able to get any support in the Chat rooms and the forum?

**Comment by anku255** [comment]
@raisedadead No, I posted in forum 2 days ago but nobody replied. Also, I asked in chat but no body was able to help me. Then, I had to create this jssue.

**Comment by raisedadead** [comment]
> do you have any screenshots? 
> Could you also check your browser's Dev Tools console, for logs if any?

**Comment by anku255** [comment]
@raisedadead I didn't think that screenshots will be helpful. Anyway, I am posting screenshots that also contain logs.

**Before Clicking Submit:**

![chrome_2017-12-16_12-25-29](https://user-images.githubusercontent.com/22813027/34068112-6f5a8268-e25c-11e7-87bb-712ad75a28d6.png)

**After Clicking Submit:**

![chrome_2017-12-16_12-25-48](https://user-images.githubusercontent.com/22813027/34068121-909e0d0a-e25c-11e7-90d7-e40ac6d63f99.png)

Is there anything else that I can help with?

**Comment by anku255** [comment]
@raisedadead Hey! I found the bug. The problem is in my app URL `https://timestamp-fcc-.glitch.me/`. Notice, before `glitch`, there is a dash and dot. This is making the URL invalid. I came to know about this when I tried to submit the same project in beta (beta wasn't working for me before else this would have been solved days ago). In beta, I get an error message saying URL is invalid.

So, I think you need to fix the algorithm for validating URL or maybe not if that's how you want it.  Anyways, thanks for your help.
