### ISSUE TITLE
www.globe.com.ph

### ISSUE THREAD

**Issue by abdurajak** [freeCodeCamp/freeCodeCamp#16196]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by abdurajak** [comment]
lin

**Comment by raisedadead** [comment]
@abdurajak please do not spam the issue, tracker.

Here is our [Code of Conduct](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CODE_OF_CONDUCT.md)
