### ISSUE TITLE
Test ES6 Section

### ISSUE THREAD

**Issue by Ethan-Arrowood** [freeCodeCamp/freeCodeCamp#16207]
## Tracking ES6 Section tests via this issue.
Will be using atomic commits and will merge completed challenges as I go.
✅ - All complete
⚠️ - challenges require QA (have been completed and merged)
⏳ - pull request requires review (pull requests at bottom of list)
✖️ - requires tests
1. ⏳ Introduction to the ES6 Challenges
2. ⏳Explore Problems with the var Keyword
3. ⏳Compare Scopes of the var and let Keywords
4. ⏳Declare a Read-Only Variable with the const Keyword
5. ⏳Mutate an Array Declared with const
6. ⏳Prevent Object Mutation
7. ⏳Use Arrow Functions to Write Concise Anonymous Functions
8. ⏳Write Arrow Functions with Parameters
9. ⏳Write Higher Order Arrow Functions
10. ⏳Set Default Parameters for Your Functions
11. ⏳Use the Rest Operator with Function Parameters
12. ⏳Use the Spread Operator to Evaluate Arrays In-Place
13. ⏳Use Destructuring Assignment to Assign Variables from Objects
14. ⏳Use Destructuring Assignment to Assign Variables from Nested Objects
15. ⏳Use Destructuring Assignment to Assign Variables from Arrays
16. ⏳Use Destructuring Assignment with the Rest Operator to Reassign Array Elements
17. ⏳Use Destructuring Assignment to Pass an Object as a Function's Parameters
18. ⏳Create Strings using Template Literals
19. ⏳Write Concise Object Literal Declarations Using Simple Fields
20. ⏳Write Concise Declarative Functions with ES6
21. ⏳Use class Syntax to Define a Constructor Function
22. ⏳Use getters and setters to Control Access to an Object
23. ⏳Understand the Differences Between import and require
24. ⏳Use export to Reuse a Code Block
25. ⏳Use * to Import Everything from a File
26. ⏳Create an Export Fallback with export default
27. ⏳ Import a Default Export

PR Challenges: https://github.com/freeCodeCamp/freeCodeCamp/pull/16201

**Comment by Ethan-Arrowood** [comment]
For discussion:
Some of the challenges test for `proper use of arrow function syntax`.
1. Why are we testing this? Shouldn't the code fail if they aren't using proper syntax? 
  - testing for the absence of `function` and testing that the declared variables are of `typeof functionName === 'function'` should ensure the user is using an arrow function.
2. If we really wanna test proper arrow function use I'll need some help writing a regex expression to cover all of these types of array functions:
```
() => {}
() => {a}
(a) => {}
(a) => {b}
(a, b) => {c}
a => {}
a => {b}
a => b
a => (c)
(a, b) => c
(a, b) => (c)

```

**Comment by Ethan-Arrowood** [comment]
Found issues with challenges #c23 - #c27 
'Require is not defined' produced for challenges 23, 25, 27
'exports is not defined' produced for challenges 24, 26

**Comment by QuincyLarson** [comment]
@Ethan-Arrowood Awesome! Thanks for keeping this list so nicely groomed and updated. It looks like you're rapidly converging on a PR. Let us know when it's ready - we'll QA and merge ASAP.

**Comment by Ethan-Arrowood** [comment]
Is "use strict"; necessary for this section? Why do we make the users input it into the editors every challenge? should that just be auto inserted via "challengeSeed"?
