### ISSUE TITLE
Unclear instructions for Waypoint: Use Responsive Design with Bootstrap Fluid Containers

### ISSUE THREAD

**Issue by garysmeade** [FreeCodeCamp/freecodecamp#1620]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The instructions state: "To get started, we should nest all of our HTML in a div element with the class "container-fluid"."  This is not entirely clear.  Where does the div start and stop?  And then the advice window states: "Your div element should have the class "row"."  Which one is correct, or are both required?  

With these confusing elements, this waypoint significantly drops in the usual FreeCodeCamp user-friendly standards.

![image](https://cloud.githubusercontent.com/assets/13364192/9125613/e4d5698c-3ce5-11e5-9d2e-6bd8907277ce.png)

**Comment by AkiraLaine** [comment]
@garysmeade It clearly says:  "To get started, we should nest all of our HTML in a div element with the class 'container-fluid'". So take all of your HTML and put it inside a div with a class of 'container-fluid'.

**Comment by BerkeleyTrue** [comment]
This is fixed now in beta. 

Happy Coding!
