### ISSUE TITLE
Unrelated test output logging to console

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#16210]
Current staging has test output logging to the console. But the test output is from a completely separate challenge.

I am working in HTML & HTML5 but keep getting 

```sh
frame.js:77 Block scope i is:  block scope
frame.js:77 Function scope i is:  block scope
```

**Comment by raisedadead** [comment]
Hi @Bouncey is this still an issue? Can you guide on how to reproduce if yes?

**Comment by Bouncey** [comment]
I haven't seen this again. Closing
