### ISSUE TITLE
System Design and Concept Questions: Array.prototype.map: Question 5

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#16229]
#### Issue Description
Question 6 has two issues:

### 1. The code sample doesn't produce any of the available choices.
![concept-question-bug](https://user-images.githubusercontent.com/6125097/34220952-a8bd7792-e5b6-11e7-9830-59942b5935d1.png)

#### Solutions
- Either fix the code...
- or keep this as an intentional bug, along with a new option with the actual output. This could add a new kind of problem to these questions. But I'm not sure we want to go this way 😋 

### 2. The description has an unrelated code sample (the bottom one).

This seems to follow along with other questions as well.
![extra-description](https://user-images.githubusercontent.com/6125097/34221264-b442cd3c-e5b7-11e7-80a9-0e46662d6fe4.png)

#### Browser Information

* Browser Name, Version: Firefox 57.0.2
* Operating System: Windows 10, 64 bit
* Mobile, Desktop, or Tablet: Desktop

**Comment by Greenheart** [comment]
The correct code that matches the currently correct answer:
```js
const results = [8, 5, 3]
  .map((a, i, o) => o[o.length - i - 1])
console.log(results);

// [3, 5, 8]
```

**Comment by saurishkar** [comment]
I am working on this one.

**Comment by raisedadead** [comment]
ProTip: You can lookup the files by searching for challenge names on the github search on this repo.
[Example](https://github.com/freeCodeCamp/freeCodeCamp/search?utf8=%E2%9C%93&q=Array.prototype.map%3A+Question+5&type=)

**Comment by saurishkar** [comment]
@raisedadead I found the seed file and have made the changes for the First issue.
However, the second one seems to be an issue on the side of react component rendering.
The `<pre>` code for the first question renders outside of `<p>` tag , while all others are rendered inside it. That's why the first Question gets appended to all subsequent questions.

**Comment by raisedadead** [comment]
Okay, the second seems to be a platform issue, we should just take this separately, Can you please make a PR with your changes, and log a new one when its merged, for the second part ?

It should be the react views. I think, but will have to check.

**Comment by saurishkar** [comment]
Sure, yeah it seems a rendering issue.
I will raise a PR for the first one, meanwhile i am going through the React code if i can pinpoint the second.
