### ISSUE TITLE
Challenge map is slow to show/hide

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#16228]
#### Issue Description
On mid- to low-end, computers, the challenge map has a significant delay when opening/closing it, which affects the UX.

#### Questions
- What is causing this?
- Could it be fixed by...
  - hiding/showing the map without the animation?
  - experimenting with different techniques in CSS for hiding the map?
  - making sure the map is kept in the DOM at all times, to prevent heavy re-rendering?

Ultimately, this comes down to a tradeoff between RAM and CPU power. What should be the priority on these computers?

#### Browser Information
* Browser Name, Version: Firefox 57.0.2 & Chrome 63.0.3239.108
* Operating System: Windows 10, 64 bit
* Mobile, Desktop, or Tablet: Desktop

**Comment by ZeroZipZilch** [comment]
This applies to Google Chrome on mobile as well

**Comment by raisedadead** [comment]
This should be fixed with the recent updates. Closing. Please create a fresh issue if this persists.
