### ISSUE TITLE
Wiki article request: I have reached a learning plateau

### ISSUE THREAD

**Issue by outsmart** [FreeCodeCamp/FreeCodeCamp#1622]
So I guess the question we are asking here is what so we do if we feel like we are going along just great, and then suddenly we feel as though we have reached a plateau.

For me, this is the Roman Numerals Bonfire. yes I can pair, and yes I can search for a solution, but should I not need to be able to come up with my own algorithm for efficiently solving the problem?

**Comment by BerkeleyTrue** [comment]
This request doesn't seem to be gaining any traction. Closing as stale.
