### ISSUE TITLE
[beta] Undeclared variable on Size of the Set challenge causing error

### ISSUE THREAD

**Issue by cassidypignatello** [freeCodeCamp/freeCodeCamp#16222]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/coding-interview-data-structure-questions/size-of-the-set

#### Issue Description
The code that automatically loads on the page has an undeclared variable `index` on line 24 that throws an error when submitting your code. This is a pretty easy problem to catch, but I'm thinking it should be changed since it's in a part of the code that isn't supposed to be modified in the exercise anyway.

#### Browser Information

* Browser Name, Version: Chrome, 63.0.3239.84
* Operating System: OS X Sierra
* Mobile, Desktop, or Tablet: Desktop

**Comment by raisedadead** [comment]
@cassidypignatello thanks a lot for reporting.

This should be pretty easy fix, by adding `var` keyword.

To contributors:

Here are our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

And if you need assistance reach us in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by cassidypignatello** [comment]
No problem! I'm happy to jump in and work on this one, I've never contributed before and thought it'd be a good opportunity to familiarize myself with the codebase. :)

**Comment by raisedadead** [comment]
Sure, please go ahead! Happy fixing.
