### ISSUE TITLE
Update view to show new claimed certificates

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16234]
#### Issue Description

New claimed certificates aren't showing up on the profile yet.

#### Screenshot

![app30893198_user_and_camper_quincylarson_s_code_portfolio___freecodecamp](https://user-images.githubusercontent.com/985197/34235955-b1768f1e-e5ba-11e7-9df4-22543e5fb481.png)

**Comment by jonathan-grah** [comment]
@QuincyLarson, this is implemented with the overhauled profile. This has the ability to be properly tested once that PR is merged.
