### ISSUE TITLE
Second goal for this Waypoint need edited

### ISSUE THREAD

**Issue by haunja** [FreeCodeCamp/FreeCodeCamp#1623]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-hex-code-to-mix-colors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The second goal of this challenge needs to be clarified.  It looks like the wording should be 
*Use __the__ hex code __for__ the color orange instead of the word "orange".*   
Also  the example at the bottom doesn't appear to be complete  

![mix-color](https://cloud.githubusercontent.com/assets/5329973/9126634/b8f5849a-3c7d-11e5-9886-bb893f864fe6.PNG)

**Comment by benschenker** [comment]
This seems to have been fixed
