### ISSUE TITLE
Proper Testing discussion

### ISSUE THREAD

**Issue by Ethan-Arrowood** [freeCodeCamp/freeCodeCamp#16231]
Traditionally, challenges used 
```"assert(code.match(/.../), 'message: ... ');"``` 
in order to test user input.
Recently, @BerkeleyTrue released a new untranspiled version of a users code via `getUserInput`. Now tests can be written like so:
```"getUserInput => assert(getUserInput('index').match(/../)...., 'message: ....');"```

Please use this issue to discuss the proper way to test challenges. If we can consolidate any ideas we should commit them to `CONTRIBUTING.md`

**Comment by BerkeleyTrue** [comment]
To add some context for the changes:

The move to using this function is made in preparations for multifile challenges. `code` would not be sufficient to target multiple files as you could not know which file `code` would refer to. 

In the future we may have challenges that have separate css/html parts that campers must edit to complete. Indeed, we will have challenges to teach the modules spec. This would require multiple files and the test writer would need a way to grab the untouched user code for specific files.

**Comment by raisedadead** [comment]
how about creating localStorage keys per file, while evaluating client side, and clearing them once tests are run and submitted successfully?

```
challengeId.code.fileName1
challengeId.code.fileName2
challengeId.code.fileName3
...
```

Or do you think we may run into space constraints?

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
