### ISSUE TITLE
System Design and Concept Questions: Array.prototype.map: Missing space in results view.

### ISSUE THREAD

**Issue by Greenheart** [freeCodeCamp/freeCodeCamp#16230]
#### Issue Description
There's a space missing before the number representing the total number of questions.
![screenshot-2017-12-20 learn to code with free online courses programming projects and interview preparation for developer](https://user-images.githubusercontent.com/6125097/34221857-b95510d0-e5b9-11e7-99ca-351b77ca080f.png)

### Note to moderators
This could be a potential `first-timers-only`-issue, if we add some instructions.

**Comment by angelfeliz** [comment]
I can do this one, if I need any help searching where is that description, I will come back to ask, but first I'm going to find it for myself. On my way to fix the issue
