### ISSUE TITLE
Search bar text color to be muted and icon to be fixed

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16247]
![image](https://user-images.githubusercontent.com/1884376/34266565-ae4110b8-e69f-11e7-9540-1a2c57f28600.png)

**Comment by raisedadead** [comment]
Looks like the icon issue is sporadic, but the color should definitely be muted down

**Comment by KhaledSamir** [comment]
@raisedadead Let me work on this issue, please.

**Comment by raisedadead** [comment]
Sure, go ahead?

**Comment by KhaledSamir** [comment]
@raisedadead Thanks!.I started working on it. Unfortunately am not familiar with React but I'll keep you updated by tomorrow if I could figure it out.

**Comment by raisedadead** [comment]
You should reach out to [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), for help.

**Comment by KhaledSamir** [comment]
@raisedadead Thank you, I figured it out!. I'll do the change and create a pull request.

BTW, the search icon is renderable right, I took a branch off Staging. Please check this out maybe you're on different or you don't have the latest script.

**Comment by raisedadead** [comment]
> BTW, the search icon is renderable right, I took a branch off Staging. Please check this out maybe you're on different or you don't have the latest script.

Yes, it started to be just fine, when I did a re-build. As I said before it is sporadic.

**Comment by raisedadead** [comment]
Looking forward to your PR.

**Comment by Bouncey** [comment]
The icon relies on the font awesome font familiar being available. There is no reliable fallback font. @QuincyLarson maybe we should look at other options re the search icon?

**Comment by raisedadead** [comment]
Maybe we can see what others have done? Clearly this is not unique to us.

**Comment by QuincyLarson** [comment]
@Bouncey Perhaps we could check and only render the icon if Font Awesome is loaded? Then worst case scenario we'd just have text there, which wouldn't be so bad.

**Comment by raisedadead** [comment]
Closing this as I can't seem to get the icon issue any longer, I think it was previously because the builds and bundle pushing were slower, which I think we have sped up significantly thanks to Bouncy and Berkeley.
