### ISSUE TITLE
Title Case A Sentence - all tests pass but the code is still wrong

### ISSUE THREAD

**Issue by thejasonfile** [FreeCodeCamp/FreeCodeCamp#1624]
Challenge http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

My first pass at this Bonfire produced a result where all 4 tests seem to pass (green check marks) but I didn't get the pop up saying I could move on to the next bonfire.  I copied my code to repl.it and ran my code against each of the test cases manually.  Looks to me that with the way my code was written at first, the first two tests would pass but the last two would not (I didn't convert the strings to lower case).  Once I realized this and included the toLowerCase() line, all tests passed and I was allowed to go on.  I've included screenshots to show the results I was seeing.

![image 001](https://cloud.githubusercontent.com/assets/9918971/9126826/5bdd3192-3c80-11e5-933b-f6a1ae1535b6.jpg)
![image 002](https://cloud.githubusercontent.com/assets/9918971/9126827/5bde979e-3c80-11e5-8ecb-8c772b6c38da.jpg)

The first shot shows that "I'm a little teapot" is the result and everything passes.
The second shot shows that "HERE IS MY HANDLE AND HERE IS MY SPOUT" is the result and the 4th test still passes even though the only caps should be the first letters.

Again, in both of these cases all test cases seem to pass (4 green checks) but the bonfire is not marked complete.  Only after I converted the strings to lower case did the bonfire complete.

Thanks!

**Comment by benschenker** [comment]
Hey @thejasonfile I'm going to close this issue as stale, but feel free to reopen if it is still a problem for you (include code too so we can try to reproduce)
