### ISSUE TITLE
Dark mode CSS improvements

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16243]
Here are several ways we could improve the CSS for dark mode for better contrast and accessibility: 
![learn_to_code___freecodecamp](https://user-images.githubusercontent.com/985197/34244356-8862df08-e5ea-11e7-834e-ab40486e40fc.png)

**Comment by AlyChloe** [comment]
@QuincyLarson love to help out! I'll let you know if I have any questions.

**Comment by QuincyLarson** [comment]
@AlyChloe Awesome! Sounds great! Please keep us posted on your progress :)

**Comment by AlyChloe** [comment]
@QuincyLarson I'm about done with this issue but I can't seem to figure out why my changes for [`.@{ns}-editor .CodeMirror`](https://github.com/AlyChloe/freeCodeCamp/commit/5f57923d821a0b83b3d7100ac8c30c14d546e682#diff-980f586a94989488bd5bd7c9a416b66cR96) will not compile? 

My changes elsewhere compile just fine. Seems to not work for that section of text?

**Comment by QuincyLarson** [comment]
@AlyChloe Could you open a pull request with your current changes (you can add the label "work in progress" - that way we can see your code and help you figure out how to fix this :)

**Comment by raisedadead** [comment]
We should just use the default code mirror theme for day mode and dracula theme for for night mode in code mirror config.

Its well maintained for very many coding languages.

**Comment by QuincyLarson** [comment]
@raisedadead Is there a way to tie these codemirror theme changes to switching between light and dark mode? I like the way @AlyChloe's changes look, but I agree that we should ideally use a Codemirror theme instead of trying to change this with CSS.

**Comment by raisedadead** [comment]
@QuincyLarson 
> Is there a way to tie these CodeMirror theme changes to switching between light and dark mode?

Yes, it will be an additional code fix. When a user toggles night mode in settings, currently we are changing the CSS classes for our UI elements (background, buttons, etc.)

But it should be simple enough to improve that logic to toggle the theme of the CodeMirror component to corresponding light / dark i.e (default / dracula) themes.

**Comment by raisedadead** [comment]
The only thing that remained is the code editor, for which we already have a related issue.
