### ISSUE TITLE
[beta] Certificates should be added to the static profile path

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16246]
Need to add the new certificate buttons to the static profile before we have the react profiles. This is blocker unless that feature is available.

The code that needs to be updated is here:

https://github.com/freeCodeCamp/freeCodeCamp/blob/5a18d1cf8091da919cd213017b55888ad83d320e/server/views/account/show.jade#L51-L58

The new certificate object ids are here:

https://github.com/freeCodeCamp/freeCodeCamp/blob/5a18d1cf8091da919cd213017b55888ad83d320e/common/models/user.json#L162-L200

**Comment by raisedadead** [comment]
Also please double check the routes while updating the links which are available here:

https://github.com/freeCodeCamp/freeCodeCamp/blob/5a18d1cf8091da919cd213017b55888ad83d320e/server/boot/user.js#L229-L272

**Comment by raisedadead** [comment]
Please refer to our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), and reach us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), for any assistance.

**Comment by cpheimbach** [comment]
OK will give it a go on this issue.

**Comment by cpheimbach** [comment]
Hey @raisedadead, the user.json refers to a new Data Vis Certification (isNewDataVisCert) but there is only one route for data viz. 

Is the one below what you want me to use? 
` api.get(
    '/:username/data-visualization-certification',
    showCert.bind(null, certTypes.dataVis)
  );`

**Comment by raisedadead** [comment]
Hi @cpheimbach you can leave the ones for the new data viz route, and proceed with the rest. Thanks.

**Comment by jonathan-grah** [comment]
This is closed in relation to the closure of the pull request (#16251).
