### ISSUE TITLE
Line number column in code editor is too wide

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16242]
The line numbers in the code editor are about twice as wide as they need to be. I'm hoping we can make this narrow enough to 

![learn_to_code___freecodecamp](https://user-images.githubusercontent.com/985197/34243419-43e620fa-e5e6-11e7-94c4-67915754d6cb.png)

@67shafar since you're on a roll with CSS fixes, this might be a good one for you to tackle :)

**Comment by 67shafar** [comment]
@QuincyLarson Sure, I'll grab this one too :)

**Comment by QuincyLarson** [comment]
@67shafar I think I made a mistake. Even though this looks wide, when there are linting errors, their badges take up most of the horizontal space. I just noticed this when I QAing a challenge. As such, I don't think we should change this. Sorry for the false start.

**Comment by 67shafar** [comment]
@QuincyLarson no problem. I figured it out pretty quickly myself, but hadn't had a chance to make a comment. 

Thanks
