### ISSUE TITLE
System Design and Concept Questions: Array.prototype.map: Question 2

### ISSUE THREAD

**Issue by angelfeliz** [freeCodeCamp/freeCodeCamp#16245]
#### Challenge Name

System Design and Concept Questions: Array.prototype.map

#### Issue Description

https://beta.freecodecamp.org/en/challenges/system-design-and-concept-questions/arrayprototypemap

If you pick a wrong answer it will show the explanation message which point to a wrong answer, it should be [['A'], ['B'], ['C']]

#### Browser Information

* Browser Name, Version: Chrome (Versión 63.0.3239.108 (Build oficial) (64 bits))
* Operating System:  Windows 10
* Mobile, Desktop, or Tablet:  Desktop

#### Screenshot

![choiceingandexplanationdontmach](https://user-images.githubusercontent.com/7728678/34263928-82f5a70a-e647-11e7-89e7-558a8f025801.PNG)

**Comment by raisedadead** [comment]
@angelfeliz thanks for reporting.

**Comment by edgargonzalez2020** [comment]
I'm aware of the issue now and working on fixing it.

**Comment by kpranke** [comment]
Do you still need help with this one?

**Comment by raisedadead** [comment]
Yes, we do.

**Comment by saurishkar** [comment]
@raisedadead : If this issue is still open, may i take this up on priority. I have just setup my forked repo for contributing.
