### ISSUE TITLE
When a user hides the map, it should stay hidden until toggled on again

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16249]
Even if a user toggles the map off, when they complete a challenge, the map will appear again on the next challenge. If the user toggles the map off, it should stay hidden until they toggle it back on, so that they don't have to keep hiding it on every challenge.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson the same is also true for the preview pane. I tried taking a look at where this originates, but couldn't quite follow it back.

**Comment by QuincyLarson** [comment]
@no-stack-dub-sack Agreed. 

@BerkeleyTrue do you know how to update the panes so they stay open/shut between challenges and sessions? Perhaps we could put a flag in local storage?

**Comment by mstellaluna** [comment]
the same happens on mobile .. I am on Samsung S7 Edge using chrome browser.. map keeps re-appearing at each challenge even if I toggle it off.

**Comment by BerkeleyTrue** [comment]
The pane logic is in the reducer for panes. These would require changing the logic so panes that existed in the previous state during challenge transition should keep their previous state.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue How much time would it take to make this refactor? Because I am confident people will immediately start complaining about this.

**Comment by Bouncey** [comment]
@QuincyLarson does this need to persist across sessions, or do we default it open for each new session?

**Comment by QuincyLarson** [comment]
@Bouncey I think we should just store this in the browser rather than in the database. We don't want to have to write to the database every time someone toggles a pane open or closed. If someone switches devices or logs out, I think we should default to showing all the panes for that challenge (including the map pane).
