### ISSUE TITLE
Code linter throwing error on valid ternary statement

### ISSUE THREAD

**Issue by krisb1220** [freeCodeCamp/freeCodeCamp#16256]
#### Challenge Name

https://www.freecodecamp.org/challenges/record-collection

#### Issue Description

Code linter throwing error on valid ternary statement
#### Browser Information

* Chrome 
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Null

#### Screenshot

https://imgur.com/a/90f8F

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
