### ISSUE TITLE
Control+Enter keyboard shortcut should unlock the "Code locked. Unlock?" button and show a toast

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16250]
Scrolling to the bottom of lesson to unlock the code is tedious.

![learn_to_code___freecodecamp](https://user-images.githubusercontent.com/985197/34268687-41d23806-e647-11e7-9e0b-b744ed9b0f7a.png)

For power users who use the control+enter shortcut to run their code, the first time they press the control+enter shortcut, it should: 

1. unlock their code 
2. pop up a toast that says: "You've unlocked your code. Careful! Only run code you trust. You can now run your code with ctrl+enter shortcut."

**Comment by raisedadead** [comment]
> "You've unlocked your code. Careful! Only run code you trust. You can now run your code with ctrl+enter shortcut."

That's too big for a toast message, and most certainly is going to break on all screens.

**Comment by QuincyLarson** [comment]
@raisedadead OK how about we assume that if they know the shortcut, they've previously run that warning, and we just run the code. No toast.

**Comment by raisedadead** [comment]
Hi @QuincyLarson 

May be a simpler way is to just update the button label from `Code Locked. Unlock?` to something more meaningful? like `Code Locked. Unlock? (Ctrl + Enter)`

And the tooltip is already identifying the warning.

So, yup we could be safe without a toast. 😅 !

**Comment by QuincyLarson** [comment]
@raisedadead I'm not a fan of tooltips, as they don't even work on touch screens. I agree that instead we should change the copy. Perhaps something like: "Code locked. Only run code you trust. Unlock? (Ctrl + Enter)" That will make it a multi-line button, but I still think it's better and more clear.

**Comment by raisedadead** [comment]
Yes.. it seems logical to me.

**Comment by theoutlander** [comment]
Is the work here to simply trigger a mouse click on the unlock button when the user presses Control + Enter??

**Comment by QuincyLarson** [comment]
@theoutlander I suspect there would be a more elegant way than simulating a mouse click on a button. I think you'd want to find how the control+enter logic currently works and make that trigger the unlocking of the code in the same way.

**Comment by lijin3096** [comment]
密码密密麻麻

**Comment by theoutlander** [comment]
I'm working on this one

**Comment by QuincyLarson** [comment]
@theoutlander Awesome! Thanks for keeping us posted on your progress :)
