### ISSUE TITLE
Stuck on profile page - Beta

### ISSUE THREAD

**Issue by ncaron** [freeCodeCamp/freeCodeCamp#16269]
#### Issue Description

After going to the profile page, I can no longer navigate away from it. I do not see any errors in the console.

Steps to reproduce:
1. Go to https://beta.freecodecamp.org/
2. Click on "My Profile".
3. Click on "Map", "My Profile" or the freeCodeCamp logo. Nothing happens.

#### Browser Information

* Browser Name, Version:  Chrome 63
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

AND

* Browser Name, Version:  Chrome 63
* Operating System: Android Nougat on Samsung Galaxy S6
* Mobile, Desktop, or Tablet: Mobile

**Comment by raisedadead** [comment]
This is now fixed in recent updates, thanks for reporting. Closing.
