### ISSUE TITLE
target same element with multiple jquery selector: passing function for checkmarks not working when completing tasks appropriately

### ISSUE THREAD

**Issue by JonathanKreiter** [FreeCodeCamp/freecodecamp#1626]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. 

Completed task appropriately, though was not able to continue due to code not being recognized properly by the code checking for the right answers. 

in BETA FCC

**Comment by BerkeleyTrue** [comment]
closing as duplicate of #1529
