### ISSUE TITLE
Select a Group of Elements with D3 instructions need to be clearer

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16268]
#### Challenge Name
Select a Group of Elements with D3 (https://beta.freecodecamp.org/en/challenges/data-visualization-with-d3/select-a-group-of-elements-with-d3)

#### Issue Description
This challenge requires using the `.text("")` method, which is not included in the challenge. We need to make sure it's somehow included in the instructions - otherwise people wouldn't necessarily know how to complete this challenge.

#### Screenshot

![learn_to_code___freecodecamp](https://user-images.githubusercontent.com/985197/34314654-6e0d204e-e73b-11e7-9674-cdd80c84e790.png)

**Comment by MP7373** [comment]
I tried to make a pull request that added a hint to use the .text() function why was it rejected?

**Comment by QuincyLarson** [comment]
@MP7373 Can you link to that pull request here?

**Comment by MP7373** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/pull/16302
It says I need to be in another branch to make the pull request. The problem is in my local repo I made a branch correctly named fix/#16268 but I still have the changes on the staging branch (so my there are no changes to be added to the new branch). I also don't know if the text I added is satisfactory or if it gives away too much.

**Comment by sagarjhaa** [comment]
Hi @QuincyLarson , @MP7373 
I would like to help with the bug. Can I work on it?

**Comment by QuincyLarson** [comment]
@MP7373 Your issue was auto-closed by CamperBot. Read [its message](https://github.com/freeCodeCamp/freeCodeCamp/pull/16302#issuecomment-353740924) and it explains the reasoning behind this, which I agree with.

> Like do I need to revert my staging branch then switch to my fix/#16268 brach and make the pull request from there?

I think that would work. A couple notes: 
1. Your commit message should be descriptive. The issue it's fixing should be in the PR's description, not the commit message.
2. be sure to pull down the latest copy of staging, then branch off of the staging branch, then commit and push to that branch on your fork (your own version of the freeCodeCamp GitHub repository). Then when you make the pull request from your fork's branch into freeCodeCamp's staging branch, CamperBot should accept it and we can start QA'ing your code :)

**Comment by QuincyLarson** [comment]
@sagarjhaa Please take a look at some of the other [help wanted issues](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) - there are a ton of them we could use your help with :)

**Comment by raisedadead** [comment]
This is open for anyone to work on.

**Comment by sagarjhaa** [comment]
Working on it.

**Comment by QuincyLarson** [comment]
@sagarjhaa Welcome back! Thank you for your patience, and taking the initiative! Let us know if we can do anything to help. Thanks for keeping us posted on your progress :)

**Comment by sagarjhaa** [comment]
@QuincyLarson I want to thank you for hosting freecodecamp and I am humbled to contribute.

**Comment by QuincyLarson** [comment]
@sagarjhaa We are thrilled to have you contributing!
