### ISSUE TITLE
"What would you like to know?" Search Input Not Working 

### ISSUE THREAD

**Issue by jjprevite** [freeCodeCamp/freeCodeCamp#16272]
#### freeCodeCamp beta website
[https://beta.freecodecamp.org/](https://beta.freecodecamp.org/)

#### Issue Description
The search box labeled "What would you like to know?" does not seem to be working. When I type something in and hit enter, nothing happens.

To recreate issue:

1. log in to [https://beta.freecodecamp.org/](https://beta.freecodecamp.org/)
2. click on any challenge on the from the Map (i.e. Introduction to the Basic HTML and HTML5 Challenges)
3. Click on the search box input field and type anything (i.e. debugging)
4. Press enter

#### Browser Information

* Browser Name, Version: Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Operating System: mac OSX High Sierra Version 10.13.1 (17B1003)
* Mobile, Desktop, or Tablet: Desktop 

#### Screenshot
<img width="1680" alt="screen shot 2017-12-22 at 6 45 43 pm" src="https://user-images.githubusercontent.com/3806031/34315985-656e3e0c-e748-11e7-9e1e-9db68f4db984.png">

**Comment by mstellaluna** [comment]
added Beta label.

**Comment by QuincyLarson** [comment]
@Bouncey We have the steps to reproduce this - could you take a look at it? I've assigned you.

**Comment by Bouncey** [comment]
I have (patched the search server)[https://github.com/freeCodeCamp/search/pull/64] to be more flexible with our sub-domains.

This is working on `staging`. I suspect the beta server needs a refresh to have the changes required in `/server/middlewares/csp.js`

@BerkeleyTrue
