### ISSUE TITLE
Privacy Settings - Button stays green (active) when toggling from On to Off

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16277]
#### Challenge Name

My Profile - Update My Settings - Privacy Settings

#### Issue Description

The toggle button by default is White with the label Off.
When selecting On it goes to FCC Green so the selection is active.
When clicking on the button again, the label switches to Off but stays green until you click elsewhere on the page. 
Can be confusing if the setting is enabled/disabled

#### Browser Information

* Browser Name, Version:  
* Operating System: FireFox 57.0 (64-bit)  and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34316182-a4933690-e75d-11e7-985b-4462833ab227.png)

**Comment by Bouncey** [comment]
Is it a focus issue? Did you click away from the button?

**Comment by jonathan-grah** [comment]
This has been fixed in the upcoming release as we now have an "on-off" switch.
