### ISSUE TITLE
Search results point to www.freecodecamp.org when running locally

### ISSUE THREAD

**Issue by theoutlander** [freeCodeCamp/freeCodeCamp#16275]
#### Issue Description
The search feature on the top bar loads results that go to the main site on www.freecodecamp.org. This is when I was using it locally from localhost:3000.

#### Browser Information
* Browser Name, Version 63.0.3239.108 (Official Build) (64-bit): 
* Operating System: Mac OS
* Desktop 

#### Screenshot
Notice the link on the status bar

<img width="1680" alt="screenshot 2017-12-22 18 03 01" src="https://user-images.githubusercontent.com/749084/34316066-5f857a88-e742-11e7-85db-875c6994ff4e.png">

**Comment by Bouncey** [comment]
@theoutlander Thanks for the the issue. The absolute links as known about and under discussion [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/16219#issuecomment-352858887)
