### ISSUE TITLE
[beta] Certificate Names Expand Beyond Boxes on Commit/Pledge Page

### ISSUE THREAD

**Issue by jjprevite** [freeCodeCamp/freeCodeCamp#16274]
#### Issue Description
Data Visualization and APIs and Microservices expand outside of their "boxes" in Step 1 on the [Commit page](https://beta.freecodecamp.org/en/commit)

1. log in to https://beta.freecodecamp.org/
2. click on My Profile
3. click "Edit my pledge"
4. scroll down until you see Step 1.

#### Browser Information

* Browser Name, Version: Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Operating System: mac OSX High Sierra Version 10.13.1 (17B1003)
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
<img width="1680" alt="screen shot 2017-12-22 at 6 53 02 pm" src="https://user-images.githubusercontent.com/3806031/34316023-8fb7fe18-e749-11e7-828a-6755bd9006bb.png">

**Comment by mstellaluna** [comment]
added beta label

**Comment by raisedadead** [comment]
To potential contributors:

The views for this page are in this directory
https://github.com/freeCodeCamp/freeCodeCamp/tree/staging/server/views/commit

The CSS is in the `main.less` file.

Please follow our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), and reachus in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for assistance.

**Comment by briancmlee** [comment]
Applying the `overflow-wrap: break-word` property to `.btn-primary` fixes the text expanding beyond boxes but brings up a new UX problem. 
![freecodecamp overflow fix](https://user-images.githubusercontent.com/13359568/34899328-5cf2c4d6-f84c-11e7-90a8-26f89e70e2e4.PNG)
As can be seen in the screenshot, words that are too long have some characters that wrap into their own line, making it hard to read.

A possible solution would be to reduce the padding of the elements. As of now, the elements have 6px left and right padding applied from the `.btn` class and this is resulting in less space for the text to fit in. However, this doesn't completely fix the issue as there are still a few characters wrapping onto new lines on smaller viewports. Perhaps smaller viewports could be handled by setting padding with a responsive unit or using media queries?

**Comment by raisedadead** [comment]
@briancmlee thanks for taking the time to look into this.

A simpler solution would be to lay the buttons horizontally instead? In the past we had fewer buttons, and hence vertical grouping made sense. Now that we have more we can lay them in a horizontal layout instead?

Thanks once again, happy contributing!

**Comment by raisedadead** [comment]
@meajinkya @briancmlee yes, that is correct.

**Comment by briancmlee** [comment]
@meajinkya Please don't take this the wrong way, but I don't think this is an issue that needs multiple people working on it.

@raisedadead How's this looking? Just applied `.btn-group-vertical` and some width styling.
![screenshot-2018-1-15 learn to code with free online courses programming projects and interview preparation for developer](https://user-images.githubusercontent.com/13359568/34922473-753bba22-f9e4-11e7-81f9-e67530d65bc5.png)

Ready for PR?

**Comment by briancmlee** [comment]
@meajinkya Please don't take this the wrong way, but I don't think this issue needs more than two people working on it.

@raisedadead I've laid out the buttons vertically by replacing `btn-group` with `.btn-group-vertical` and removing the `.btn-group-justified`.
![freecodecamp pldege certificate text fix](https://user-images.githubusercontent.com/13359568/34922984-38cc33da-f9eb-11e7-8e40-ca88e3add38a.PNG)
Is this ready for PR?

**Comment by meajinkya** [comment]
No problem @briancmlee.
and yes this looks good!
