### ISSUE TITLE
Beta: Waypoint: Use Responsive Design with Bootstrap Fluid Containers - typo

### ISSUE THREAD

**Issue by richyvk** [FreeCodeCamp/freecodecamp#1627]
http://beta.freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers

Instructions are to add a div with a class "container-fluid", but the test asks for a div with a class "row".

Test passes with class="container-fluid" and fails with class="row"

**Comment by BerkeleyTrue** [comment]
This has been fixed.

Happy Coding!
