### ISSUE TITLE
Toggle Button in Dark Mode should read as Toggle Light Mode

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16276]
#### Challenge Name

My Profile -> Update My Settings -> Toggle Dark Mode

#### Issue Description

When in dark mode, the toggle button should say "Toggle Light Mode" instead of "Toggle Dark Mode"

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34316103-407aae46-e75c-11e7-999d-b3c63e61968d.png)

**Comment by Bouncey** [comment]
I would say that button is still correct. The button toggles night mode on and off.

Maybe it would be better as a toggle switch?

**Comment by jonathan-grah** [comment]
We now have this as an "on-off" switch. This can be closed.
