### ISSUE TITLE
Social Media: Adding Twitter or LinkedIn modifies the other mned

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16273]
#### Challenge Name

My Profile -> Update my Settings
Add my twitter account and add my linked in account

#### Issue Description

After adding only the twitter account, the linkedin account becomes active as if a linkedin account was added but was not.
cannot remove the falsely account. URI does not match.
but the twitter logo is available on public profile with privacy settings disabled.

#### Browser Information

* Browser Name, Version:  
* Operating System: FireFox 57.0 (64-bit)  and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34316003-9df94b3e-e759-11e7-9672-5858782761c0.png)

![image](https://user-images.githubusercontent.com/22984739/34316013-f61aee76-e759-11e7-92dd-343c38d4e1e9.png)

![image](https://user-images.githubusercontent.com/22984739/34316242-d6b706aa-e75e-11e7-946c-c957ad79e646.png)

**Comment by raisedadead** [comment]
There could be two separate issues here:

1. The URI error is because we are missing the correct APP_KEY_SECRETS from LinkedIn for beta URL.
2.

**Comment by raisedadead** [comment]
@QuincyLarson do you have access to the LinkedIn Developer dashboard?

**Comment by QuincyLarson** [comment]
@mstellaluna @raisedadead We are in the process of removing LinkedIn and Twitter auth in favor of just having campers paste in the link to their LinkedIn and Twitter profiles manually.
