### ISSUE TITLE
After completing the challenge it shows something is not right and map is not working while doing challenges

### ISSUE THREAD

**Issue by RitikPatni** [freeCodeCamp/freeCodeCamp#16286]
#### Get Set for our Responsive Web Design Projects

https://beta.freecodecamp.org/en/challenges/applied-responsive-web-design-projects/get-set-for-our-responsive-web-design-projects

#### Issue Description
After completing this challenge it shows something went wrong and doesn't redirects to next page also the map won't work when you are on challenges in case you want to navigate through the map then you need to open a separate tab for it and work in other tabs

#### Browser Information

* Chrome, Version 62.0.3202.94 (Official Build) (64-bit)
* Operating System: Linux Mint Cinnamon
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code

```js



```
#### Screenshot

![screenshot from 2017-12-23 11-48-22](https://user-images.githubusercontent.com/16117262/34317540-3a095096-e7d7-11e7-8810-e9750f8037f4.png)

**Comment by Bouncey** [comment]
@RitikPatni Are there any messages in the developer tools console?

**Comment by RitikPatni** [comment]
@Bouncey nothing is working now not even the search box or the map so I can't navigate to the error I'm attaching the console screenshots so that you can look into the issue
![screenshot from 2017-12-23 19-51-29](https://user-images.githubusercontent.com/16117262/34320233-f1173cce-e81a-11e7-8517-6fb4ff2177d8.png)

**Comment by raisedadead** [comment]
The naviagation issues should be solved, other platform specific issues are already tracked. Closing.
