### ISSUE TITLE
Can't login from email link on second reset "Oops, something is not right, please request a fresh link to sign in / sign up."

### ISSUE THREAD

**Issue by urbanware** [freeCodeCamp/freeCodeCamp#16288]
#### Challenge Name

https://beta.freecodecamp.org/en/email-signin

#### Issue Description

Site no longer responds after second deletion of account.  

I received initial email link and opened account (email 1) (test account beta@urbanware.com)
I tried browsing (screenshots below) 
Only My Profile working, couldn't access challenges
Logout/Login worked, challenges accessible
I reset challenge progress, Logout and Login results in failure, can't progress
I deleted the account, Github association (first)
I setup a new account with same email and Github (email 2)
Again only My Profile worked, this time Logout/Login didn't work, challenges inaccessible
I deleted the account, Github association (second)
I setup a new account with same email and Github (email 3)
Website produces Ooops message. 
I can no longer login

#### Browser Information

* Browser Name, Version:   Chromium, Version 63.0.3239.84 (Official Build) 
* Operating System:   Built on Ubuntu , running on LinuxMint 18.3 (64-bit)
* Mobile, Desktop, or Tablet:   Desktop (HP Elitebook 8540w Laptop)

#### Screenshot

**Initial login to beta with challenges intact.  However can't browse challenges list left menu**

![001-can t finish initial challenge](https://user-images.githubusercontent.com/16967/34317692-25029ab8-e782-11e7-93b6-b6fa5845918b.png)
![002-click map at top same initial challenge error](https://user-images.githubusercontent.com/16967/34317759-8fdb98d4-e783-11e7-98ca-032d82059550.png)

**Logout and Login makes it work okay here** 

![003-works after initial logout and login](https://user-images.githubusercontent.com/16967/34317762-9b65a186-e783-11e7-97c9-d9f987d4de33.png)

**Reset progress, Logout and Login results in failure, can't progress, deleted account after**

![006-can t progress on left menu list get two popups not one](https://user-images.githubusercontent.com/16967/34317771-c74ffa76-e783-11e7-9e77-c91d1f77f95a.png)

**Second deleted account, Logout and resent email, failure, can't progress**

![007-cant login again after reset](https://user-images.githubusercontent.com/16967/34318003-8028d09e-e78a-11e7-9553-05ad70d7f03f.png)

**Comment by raisedadead** [comment]
Need to investigate this on the production, its not reproducible locally.

**Comment by BerkeleyTrue** [comment]
Yeah there seems to be some something funky going on in the passwordless auth. 

From opbeat I'm seeing errors that might be related. I'm gonna do a quick refactor to see if this will help. Keep an eye out for the PR.

**Comment by raisedadead** [comment]
Thanks @BerkeleyTrue

**Comment by QuincyLarson** [comment]
@BerkeleyTrue OK - good luck with the refactor. In the meantime I'm recommending campers who get locked out to focus on QA'ing individual challenges.

**Comment by IsaacAbrahamson** [comment]
@QuincyLarson, Since this is closed and merged, should it be removed from the TODO list?

**Comment by raisedadead** [comment]
@IsaacAbrahamson yup on it. thanks.
