### ISSUE TITLE
Delete Progress/Brownie Points - Confirmation Popup - cannot read text in dark mode

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16280]
#### Challenge Name
My Profile -> Update My Settings -> Reset Progress/Brownie Points

#### Issue Description

The confirmation popup window, the text is not readable.
Either the background is too dark because its in dark mode
or the buttons should be filled in and the text be in white

#### Browser Information

* Browser Name, Version:  
* Operating System: FireFox 57.0 (64-bit)  and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34316567-28edf124-e767-11e7-9d4f-5450a23f6675.png)

**Comment by vkWeb** [comment]
@raisedadead Fixing this with #16501. I'll be waiting for your review. 😃
