### ISSUE TITLE
Beta.FreeCodeCamp.org is down - 502 Bad Gateway

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16281]
#### Challenge Name

beta.freecodecamp.org 

#### Issue Description

Beta is down again for the second time this evening. Quincy corrected it the first time but now getting errors again 502 Bad Gateway

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34316751-ebd50648-e76a-11e7-865a-af214330fe91.png)

**Comment by mstellaluna** [comment]
@QuincyLarson @BerkeleyTrue

**Comment by theoutlander** [comment]
It appears that the site has been going down a few times. I think we should integrate with https://sentry.io so it helps us pinpoint these issues without much effort. I'm happy to take that task.

**Comment by BerkeleyTrue** [comment]
Thanks for reporting @mstellaluna 

It's back up now.

Happy Coding

**Comment by mstellaluna** [comment]
@BerkeleyTrue @QuincyLarson  re-opening its down again.. same error

**Comment by QuincyLarson** [comment]
@mstellaluna Thanks for the heads-up. I just messaged @BerkeleyTrue and we're going to get it back up as quickly as possible.

**Comment by wildlifehexagon** [comment]
Looks like it's back up?

**Comment by theoutlander** [comment]
I had mentioned above that we should integrate with sentry. Any thoughts on that?

**Comment by QuincyLarson** [comment]
Thanks for the suggestion, @theoutlander. We have an open source tool that watches for outages and calls us. We just haven't configured it to run on beta.freecodecamp.org

**Comment by theoutlander** [comment]
Nice. I didn't know that. People testing it were not sure what was going on, so I figured access to a dashboard might be nice.

**Comment by systimotic** [comment]
Looks like it's up again 🙌  Can this be closed?

**Comment by QuincyLarson** [comment]
@theoutlander Thanks for the feedback. We may be able to build some sort of status page in the future.
