### ISSUE TITLE
Public Profile - Social Media Buttons look and behave differently

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16283]
#### Challenge Name
https://beta.freecodecamp.org/<username>
Privacy Settings must be turned off and a social media account linked to verify

GitHub Button: By Default is Green instead of white and turns a different shade of light grey on hover
Twitter Button: By Default is White and turns a different shade of dark green (not the FCC green) on hover
LinkedIn: unknown since there is an issue in an inability to remove social accounts, due to privacy not linking my linkedin. Please verify

For UX consistency, the buttons should appear and behave the same.

#### Browser Information

* Browser Name, Version:  
* Operating System: FireFox 57.0 (64-bit)  and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34316827-b79d9de8-e76c-11e7-9263-29bca66615ff.png)

![image](https://user-images.githubusercontent.com/22984739/34316838-17161b92-e76d-11e7-8524-7bf82563c8c3.png)

![image](https://user-images.githubusercontent.com/22984739/34316839-3a228efe-e76d-11e7-9607-37c94d6da6fe.png)

**Comment by QuincyLarson** [comment]
@mstellaluna thanks for reporting this!

@jonathan-grah once you ship the updated profiles, can you confirm that these buttons behave consistently?

**Comment by jonathan-grah** [comment]
@QuincyLarson; I don't believe we have these buttons formatted like this, as it wasn't in the mockup. Should they be changed to use this styling?

**Comment by QuincyLarson** [comment]
@jonathan-grah Let's focus on getting your current profile merged. Then we can go back and make cosmetic changes like this as necessary.
