### ISSUE TITLE
Changes to privacy setting does not show popup confirm changes

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16285]
#### Challenge Name

My Profile -> Update my Settings -> Privacy Settings

#### Issue Description

When toggling privacy settings between On or Off, there is no confirmation the changes were done. When you verify your public profile the changes do take effect.

Production FCC does alert when the changes are executed.
The screenshot below is from Production FCC. 
#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js



```
#### Screenshot

Production FCC:
![image](https://user-images.githubusercontent.com/22984739/34317425-6ad70afc-e77c-11e7-8114-7f0d4dec95c9.png)

**Comment by onelharrison** [comment]
@raisedadead I'll tackle this one.
