### ISSUE TITLE
cursor in the editor is not visible enough in dark mode

### ISSUE THREAD

**Issue by agitaev** [freeCodeCamp/freeCodeCamp#16284]
#### Issue Description

When the dark mode is enabled, the cursor in the editor's field (coding area) is not visible enough without the higher brightness of the screen. 

#### Browser Information

* Version 63.0.3239.84 (Official Build) (64-bit): 
* macOS High Sierra v10.13.2:  

#### Screenshot
```
https://user-images.githubusercontent.com/23414386/34317416-d2633f26-e7cf-11e7-9064-57b5a7f23289.png
```
P.S. In case you cannot find a cursor in the screenshot, it's in line 9 :)

**Comment by mstellaluna** [comment]
added beta label

**Comment by DarrenfJ** [comment]
I can concur on this one. it's the first thing I noticed.. it's a black cursor on a black background.. very hard to notice and somewhat disconcerting ( from a UI perspective, causes you to pause as it feels like it hasn't 'accepted' the click to activate the window )

**Comment by vkWeb** [comment]
By Just changing the cursor color to grey we'll be able to resolve this.

**Comment by vkWeb** [comment]
@raisedadead This will be fixed in my up-coming PR.
