### ISSUE TITLE
UI changes for User Profiles/Settings

### ISSUE THREAD

**Issue by jonathan-grah** [freeCodeCamp/freeCodeCamp#16297]
- [ ] put everything in a more narrow container
- [ ] centre buttons vertically with their text description to the left
- [ ] enlarge text size for settings page
- [ ] add vertical space between settings rows for claiming certificates
- [ ] when claiming certificates, the text description to the left should link to the appropriate challenge
- [ ] add danger buttons on bottom of settings page like on production
- [ ] add a list of completed challenges/projects/algorithms to user profiles like production

**Comment by raisedadead** [comment]
Closing as the user stories in the OP are stale now.
