### ISSUE TITLE
[Beta] UI Polishing tasks which need to be done before shipping. 

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16293]
### [Beta] UI Polishing tasks

- [ ] Navigation bar should look exactly similar to the master FCC.
- [ ] The map section should be implemented like the master FCC one. 
- [ ] There should be proper margins in the lesson section for better readability. 
- [ ] On closing the map section, the lesson section isn't  resizable.  
- [ ] The map button's hover animation overlaps the search bar.  

#### 1. Navigation bar should look exactly similar to the master FCC
The navigation bar looks too thin and the fonts are too small which makes it look weird especially on large screens. The implementation of the navigation bar in beta should be exactly similar to the master FCC one.
![](https://i.imgur.com/5x86WFn.png)

#### 2. The map section should be implemented like the master FCC one
I really like the way map section is implemented in the master FCC (check the GIF below). It doesn't come on your way and it's easily accessible. So, I think in the beta version too we should implement the same before we ship it to the world. 
![](https://i.imgur.com/zd7mNEe.gif)

#### 3. There should be proper margins on the lesson section for better readability
There is almost no left margin in the lesson section which affects the readability on the large screens. Though, It's not properly visible in the GIF below. You can experience it much better on your machine.   
![](https://i.imgur.com/UbP0ikc.gif)

#### 4. On closing the map section, the lesson section isn't  resizable
As you can see in the GIF below when the map section is not closed the lesson section gets resized easily. But when it is toggled-off the lesson section is not resizing to the left.
![](https://i.imgur.com/TX1m7AF.gif)
 
#### 5. The map button's hover animation overlaps the search bar
The hover animation of map button overlaps the ending of the search bar.
![](https://i.imgur.com/h0389g6.jpg)

### Browser Information

* Browser Name, Version:  Chrome (latest release) & Firefox (57.0.2).
* Operating System: Windows 10 Pro 32 bit.
* Mobile, Desktop, or Tablet: Desktop. 

@QuincyLarson , @systimotic , @Bouncey 
These are the changes I think should be made to the beta version before shipping. You can comment your opinions down below on these :)

**Comment by Bouncey** [comment]
I agree that 3, 4 and 5 should be addressed.

**Comment by vkWeb** [comment]
@Bouncey I think we should put this issue in the beta-release project. What do you think? 

@QuincyLarson , @systimotic , @no-stack-dub-sack . Your opinions on this, please?

**Comment by QuincyLarson** [comment]
@vkWeb Thanks for your detailed feedback. I agree with @Bouncey that issues 3, 4, and 5 should be addressed. We made conscious decisions to overhaul the navbar and map functionality, so those will be different from how they are on production. 

Could you open separate issues for your points 3, 4, and 5? That will make it easier for us to track progress on them.

**Comment by vkWeb** [comment]
Sure.
