### ISSUE TITLE
Can't login with passwordless authentication

### ISSUE THREAD

**Issue by RitikPatni** [freeCodeCamp/freeCodeCamp#16296]
#### Issue Description

When I try to log in with my existing freeCodeCamp account I just get a message like this "Please wait 4 minutes to resend an authentication link." with any number of minutes and when I try it with a new unregistered email id it sends the email but again when I try to log in it says the same again.

#### Browser Information

* Browser Name, Version: Version 62.0.3202.94 (Official Build) (64-bit)
* Operating System: Linux Mint 18.1 Cinnamon 64 bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

```
#### Screenshot

![screenshot from 2017-12-23 20-12-03](https://user-images.githubusercontent.com/16117262/34320314-9a39bd70-e81d-11e7-8560-dc9815f57524.png)
![screenshot from 2017-12-23 20-12-12](https://user-images.githubusercontent.com/16117262/34320315-9a7dd280-e81d-11e7-8cbd-a8aa8111d776.png)

**Comment by Asjas** [comment]
Hi @RitikPatni 

This is a duplicate of #16288 which is already addressing the problem.

**Comment by RitikPatni** [comment]
@Asjas Got it closing it now
