### ISSUE TITLE
Waypoint: Call out Optional Actions with Button Info - instructions change

### ISSUE THREAD

**Issue by richyvk** [FreeCodeCamp/FreeCodeCamp#1629]
Challenge http://beta.freecodecamp.com/challenges/waypoint-call-out-optional-actions-with-button-info

Think instructions could be improved if 2nd para changed to:

"Create a new block-level Bootstrap button below your "Like" button with the text "Info", and add Bootstrap's "btn-info" class to it."

In light of third para.

**Comment by Greenheart** [comment]
@richyvk I don't think this is any issue, since the buttons also should have the bootstrap-class ```btn-block``` according to the tests.

**Comment by richyvk** [comment]
True. Guess I just thought don't need to say it twice

**Comment by benschenker** [comment]
Closing as stale
