### ISSUE TITLE
Code Locked. Unlock? Button does not 'lock' code

### ISSUE THREAD

**Issue by DarrenfJ** [freeCodeCamp/freeCodeCamp#16291]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/json-apis-and-ajax/handle-click-events-with-javascript-using-the-onclick-property

#### Issue Description

left the page, came back. saw the "I found some saved work, loading now" dialogue box bottom right, Noticed the 'Run tests (ctrl + enter)' button changed to 'Code Locked. Unlock?'

Was still allowed me to remove my code before clicking it.. Clicked it and got the 'Run tests (ctrl + enter)' button again but my code was gone

Not sure what the intended functionality of the button is if it does not actually lock the Editor Panel.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Laptop

#### Screenshot
![image](https://user-images.githubusercontent.com/13170765/34318463-3e1f15f8-e796-11e7-8428-b7f90ed86ff7.png)

**Comment by Bouncey** [comment]
Code lock stops any code running in your browser. If the code looks 'funky', please ask in gitter chat to make sure it is doing what is it supposed to be doing :+1:

**Comment by DarrenfJ** [comment]
Gotcha. thanks for the heads up.
