### ISSUE TITLE
[Beta]There should be proper margins on the lesson section for better readability

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16299]
#### Issue Description
There is almost no left margin in the lesson section which affects the readability on the large screens. Though, It's not properly visible in the GIF below. You can experience it much better on your machine.
![](https://i.imgur.com/UbP0ikc.gif)

#### Browser Information

* Browser Name, Version:  Chrome (latest release) & Firefox (57.0.2).
* Operating System: Windows 10 Pro 32 bit.
* Mobile, Desktop, or Tablet: Desktop.

**Comment by QuincyLarson** [comment]
@vkWeb I think we recently added 4px of margin on both sides. How many pixels do you think would look good. Keep in mind that horizontal real estate is at a premium with 4 to 6 vertical panes (we'll soon add additional panels for HTML, CSS, JavaScript)

**Comment by vkWeb** [comment]
@QuincyLarson I think adding 14px of left padding and 12px of right padding will make it more readable. Here's a screenshot comparison to make things more clear: 

_Before: 4px padding_
![](https://i.imgur.com/vttlE6k.png)

_After: 12px and 10px padding_
![](https://i.imgur.com/fmYjFLb.png)

What do you think?

**Comment by vkWeb** [comment]
@QuincyLarson I would like to implement this change if you agree with the 12px and 14px padding.

**Comment by QuincyLarson** [comment]
@vkWeb Shouldn't we use the same amount of padding on each side? Otherwise it will be asymmetrical.

**Comment by vkWeb** [comment]
@QuincyLarson Yes, you're right. I think 14px on both the sides will look good. 
What do you say, should I Implement it?

**Comment by QuincyLarson** [comment]
@vkWeb My concern is that's a lot of horizontal space on every page. Could we get away with say 10px on each side?

**Comment by vkWeb** [comment]
@QuincyLarson According to me 10px would be too low. 
I think most of the campers will toggle-off their map while playing through the challenges, so it's important for us to give appropriate padding on the lesson section for better readability because that's the place where they'll be reading all the stuff. Also, In the production, we have perfect padding on the sides.

**Comment by QuincyLarson** [comment]
@vkWeb Yes - but soon we're going to have up to 6 panes on screen. (Map, Lesson, HTML, CSS, JavaScript, Preview). 

For perspective, here's what JSBin looks like on my 13" laptop's display:

![js_bin_-_js_bin_and_re__freecodecamp_-_authentication_request__-_team_freecodecamp_org_-_free_code_camp_mail](https://user-images.githubusercontent.com/985197/34360135-6fc2ae5a-ea23-11e7-805d-284eb4b4c66d.png)

**Comment by vkWeb** [comment]
@QuincyLarson I think most of the campers will toggle their map off while playing through the challenges. So, there's a very high probability of lesson section sticking to the leftmost and code editors going right of it. So, we'll give particularly the lesson div a 14px padding.  

Also, shouldn't we create a single section with multiple tabs on it for HTML, CSS, and JS? I really like the way Codecademy does this: 
![](https://i.imgur.com/mi2spp9.gif)

**Comment by QuincyLarson** [comment]
@vkWeb Yes - that's a nice way of grouping it as well. This said, CodePen, JSbin, JSFiddle, and countless other websites choose to show all the files expanded by default for easy access. I think that is the simplest way, and in keeping with our general UX approaches of making things transparent and accessible. 

Go ahead and try the 14px and we can see how it looks.

**Comment by vkWeb** [comment]
@QuincyLarson If in case we make up our mind to group them in tabs. We'll set a shortcut like `ctrl + arrow keys` to cycle focus between different tabs for improved accessibility. 
Sure. I'll raise a PR for this as well.

**Comment by QuincyLarson** [comment]
@vkWeb OK - we can add more hotkeys later. For now we'll stick with the simpler hierarchy that most websites are using. We may consider a more complicated nested hierarchy like CodeCademy's in the future though.

Thanks for raising the PR. I'm looking forward to QA'ing it :)

**Comment by vkWeb** [comment]
@QuincyLarson Yes. I'm on my way.
