### ISSUE TITLE
Passwordless Authentication not working - cannot login

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16303]
#### Challenge Name

https://beta.freecodecamp.org/en/signin

#### Issue Description

After last night's beta website crash, I am not longer able to login to QA Beta. 
METHOD 1:
If I try the following:
1) https://beta.freecodecamp.org/en/signin
2) email my email address associated to my production FCC
3) select 'Or click here if you want to sign in with other options'
4) select 'Signin With Github'

![image](https://user-images.githubusercontent.com/22984739/34321958-33fe46f4-e7e9-11e7-926a-bd5a8c72bd14.png)
METHOD 2: 
If I try the following:
1) email my email address associated to my production FCC
2) Click on the 'Get a magic link to sign in'
3) Go to my email
4) copy the link in the email to my chrome and firefox (I'm testing in both browsers) OR open the link in chrome and firefox directly from email
5) I cannot login I get the following error 

The link was accessed within the 15 minute time frame
![image](https://user-images.githubusercontent.com/22984739/34321996-e3f7f71c-e7e9-11e7-961e-c69b29e616d3.png)

#### Browser Information

* Browser Name, Version:  
* Operating System: FireFox 57.0 (64-bit)  and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
* Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js



```
#### Screenshot

REFER TO ABOVE

**Comment by mstellaluna** [comment]
@QuincyLarson  @raisedadead

**Comment by QuincyLarson** [comment]
Hey @raisedadead Can you see whether you can reproduce this on your end?

**Comment by darrell24015** [comment]
FWIW: same issue here.
OS: Ubuntu 16.04
Browser: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by SanD94** [comment]
I have the same issue.
OS: Ubuntu 16.04
Browser: Opera 49.0.2725.64

**Comment by andres-uris** [comment]
@QuincyLarson @raisedadead I deleted my account and try to sign up/ in and then this happen. I think is a data base issue or a inconsistency in the link validation time.

This is the output on firefox console 

![image](https://user-images.githubusercontent.com/12199455/34323131-b8041410-e811-11e7-8c50-4eb665236721.png)

**Comment by raisedadead** [comment]
Please check for open issues https://github.com/freeCodeCamp/freeCodeCamp/issues/16288
