### ISSUE TITLE
[Beta]The map button's hover animation overlaps the search bar

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16301]
#### Issue Description
The hover animation of map button overlaps the ending of the search bar.
![](https://i.imgur.com/h0389g6.jpg)

#### Browser Information

* Browser Name, Version:  Chrome (latest release) & Firefox (57.0.2).
* Operating System: Windows 10 Pro 32 bit.
* Mobile, Desktop, or Tablet: Desktop.

**Comment by davinderpalrehal** [comment]
@ncaron I would like to take on this issue if it still exists

**Comment by ncaron** [comment]
@davinderpalrehal I've already submitted a PR for it.
