### ISSUE TITLE
Fix map loading UI

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16317]
Currently while the map loads it looks like this: 

![learn_to_code___freecodecamp](https://user-images.githubusercontent.com/985197/34328036-a22d03b2-e899-11e7-83f4-a0900e569603.png)

Instead, we should show the spinner in the upper middle of that pane until it's fully loaded. This will communicate that the map is still loading, and will prevent people from clicking anything (which can potentially break the app at this point).

@BerkeleyTrue @Bouncey @raisedadead I consider this a must-fix before shipping beta. If you don't have time to significantly improve the performance of the map, I think using a spinner is our best option.

**Comment by BerkeleyTrue** [comment]
@QuincyLarson We should find the underlying issue instead of bandaiding it with a loader. I've commented on the issue this originates with. I prefer we actually investigate the get ride of something.
