### ISSUE TITLE
Dark Mode - Preview Text is too dark

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16318]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/basic-html-and-html5/say-hello-to-html-elements and onward

#### Issue Description

The text in the preview pane is black on dark grey.
Makes it hard to view

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34328619-add4f036-e8b1-11e7-8f4d-dd90aa36bf31.png)

**Comment by vkWeb** [comment]
@raisedadead I think keeping the background color `#ffffff` is the most feasible solution. What do you say?
![2018-01-13 2](https://user-images.githubusercontent.com/26724128/34899752-cc682260-f820-11e7-873b-3b34f95f9d8a.png)

**Comment by raisedadead** [comment]
Yes, the preview is rendering user code, and hence applying styles their does not make sense, we should make is a whiter shade, however `#ffffff` maybe too blown out can you tone it down to something like `#fcfcfc`?

Thanks.

**Comment by vkWeb** [comment]
@raisedadead Okay. I'll raise a PR for this as well.

**Comment by icarlossz** [comment]
If this is a Dark Mode is more effective give the color #FFF to the text, not to the background, i think.

**Comment by vkWeb** [comment]
@icarlossz Sorry, but I'm unable to understand that. Can you please elaborate that.
