### ISSUE TITLE
How long does it take Wiki page edit

### ISSUE THREAD

**Issue by mistamadd001** [FreeCodeCamp/FreeCodeCamp#1631]
Looking at the page now, and its all over the site but 1600 hours is quite a daunting number, if you put a disclaimer saying UPTO 1600 hours you may find that you get less questions about it in gitter, I personally thought 1600 was quite excessive when I started, having SOME coding experience already I was able to blast through certain sections and concentrate on new concepts, so far I have been on the site for a month, having spent only a couple of hours a day, and have nearly reached the OO JS section.

Adding somewhere as a note something like: Up to 1600 hours*

Based on a complete novice with no previous coding knowledge, people with more experience may complete sooner.

**Comment by benschenker** [comment]
Thanks for asking about this @mistamadd001!

@QuincyLarson, any thoughts?

**Comment by BerkeleyTrue** [comment]
Closing as stale.

Happy Coding!
