### ISSUE TITLE
Audio Controls  cursor should be pointer on hover

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16328]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/applied-accessibility/improve-accessibility-of-audio-content-with-the-audio-element

#### Issue Description
when hovering over the controls of the audio element added in the challenge, they aren't changing to a pointer cursor

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34363045-7311db94-ea46-11e7-9d1b-f66f9f5fb358.png)

**Comment by codingjunkie** [comment]
did you add the closing tag "<audio/>"

**Comment by mstellaluna** [comment]
@codingjunkie the issue isn't the </audio> tag. the issue is since they are controls, the pointer should change accordingly to a pointer cursor.

**Comment by vkWeb** [comment]
@mstellaluna On hovering they're not supposed to change to a pointer cursor on chrome and firefox. Also, the media player is browser specific. 

@QuincyLarson, @systimotic  Close this issue.

**Comment by QuincyLarson** [comment]
@mstellaluna yes - @vkWeb is right. This is controlled by the browser and out of our control. There's a frustrating design trend in where hovering over something clickable doesn't result in a "pointer" cursor, and it looks like this may have fell victim to that. Thanks for pointing this out!
