### ISSUE TITLE
Wiki pages for each lesson?

### ISSUE THREAD

**Issue by mistamadd001** [FreeCodeCamp/freecodecamp#1632]
I was thinking we could talk people through the lessons more in depth using the wiki, creating a page where we can walk through each step, explaining the concepts and practices, could help people to understand the lessons on a more ongoing basis rather than completing the lesson and moving on. As you move on to bonfires, looking at different approaches and suggesting industry standards, thus helping campers to better understand the concepts, as well as teaching them better practices.

eg:

## WAYPOINT 11: *Use CSS selectors to style an Element*

This lesson we look at moving our styling out of individual elements and into a more industry standard 'Stylesheet' format. When designing websites, you will often find that you work with a limited number of styling effects, be it a limited color palette, specific looks to your content or just giving everything a rounded edge.

Instead of coding these styles into *each* element, CSS gives us the opportunity to style *every* element of a specific type. For example

```
<h2 style='color: red'>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

We currently have the style of our h2 element set to a **color** of **red**, this is fine for just one h2 element, but what if we had 4 or 5 h2's, it would get quite tedious to type out *style='color: red;'* 4 or 5 times. with CSS we can create a *style* element in our html file and create a style for **all** h2 elements. For example

```
<style>
  h2 {
    color: blue;
  }
</style>
<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

By adding the *style* element, we are able to manipulate the entire html file rather than only individual elements, this cuts down a lot of time allowing more time for more exciting code.

CSS stylesheets can be used for more than just styling types of elements but can also style specific classes, ID's and other various identifiers. In the next lesson we will look at how these can be used.

-------------------------------------------------------------------------------------------------------------------

By giving campers outlines like this, it goes into more depth than the outline, and gives people a chance to better understand **why** we do things that way.

**Comment by Greenheart** [comment]
I think this sounds like a good idea, though it will require quite some work to keep both the challenges and the corresponding walkthrough updated.

**Comment by 4mifix** [comment]
Matt I like the idea and others would appreciate this also. If you get this
concept it will saves a lot of time, some things are also learned studying
with another developer who is able to guide you in areas that you are
lacking and vise versa.

On Fri, Aug 7, 2015 at 12:25 AM, Matt Huijsse <notifications@github.com>
wrote:

> I was thinking we could talk people through the lessons more in depth
> using the wiki, creating a page where we can walk through each step,
> explaining the concepts and practices, could help people to understand the
> lessons on a more ongoing basis rather than completing the lesson and
> moving on. As you move on to bonfires, looking at different approaches and
> suggesting industry standards, thus helping campers to better understand
> the concepts, as well as teaching them better practices.
>
> eg:
> WAYPOINT 11: *Use CSS selectors to style an Element*
>
> This lesson we look at moving our styling out of individual elements and
> into a more industry standard 'Stylesheet' format. When designing websites,
> you will often find that you work with a limited number of styling effects,
> be it a limited color palette, specific looks to your content or just
> giving everything a rounded edge.
>
> Instead of coding these styles into *each* element, CSS gives us the
> opportunity to style *every* element of a specific type. For example
>
> <h2 style='color: red'>CatPhotoApp</h2>
>
> <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
>
> We currently have the style of our h2 element set to a *color* of *red*,
> this is fine for just one h2 element, but what if we had 4 or 5 h2's, it
> would get quite tedious to type out *style='color: red;'* 4 or 5 times.
> with CSS we can create a *style* element in our html file and create a
> style for *all* h2 elements. For example
>
> <style>
>   h2 {
>     color: blue;
>   }
> </style>
> <h2>CatPhotoApp</h2>
>
> <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
>
> By adding the *style* element, we are able to manipulate the entire html
> file rather than only individual elements, this cuts down a lot of time
> allowing more time for more exciting code.
>
> CSS stylesheets can be used for more than just styling types of elements
> but can also style specific classes, ID's and other various identifiers. In
> the next lesson we will look at how these can be used.
> ------------------------------
>
> By giving campers outlines like this, it goes into more depth than the
> outline, and gives people a chance to better understand *why* we do
> things that way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/freecodecamp/issues/1632>.
>



-- 
Brian L. Mayers
917-459-3517

**Comment by BerkeleyTrue** [comment]
Hello @mistamadd001 

This is exactly what we are doing. Bonus, CamperBot is able to pull in that information and walk users through them.

If you don't see a wiki for a bonfire/waypoint please feel free to add one. See the previous ones for a guide line on style and formatting (important for CamperBot).

Happy Coding!

**Comment by abdullahi14** [comment]
You Dont Understand How Much This Helped Me!!!! Thanks
