### ISSUE TITLE
Vertical ScrollBar is not Showing Up in editor with code

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16327]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/applied-visual-design/animate-multiple-elements-at-variable-rates

#### Issue Description
-- Affects Challenges that have code longer than 42 lines 

The vertical scrollbar is not available on code that is longer than 42 lines. I have to use the cursor to navigate to the code lines below that. 

The horizontal scrollbar is viewable but does not seem to be active as the code appears to be line-wrapping in the editor

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js



```
#### Screenshot

VERTICAL SCROLLBAR:
![image](https://user-images.githubusercontent.com/22984739/34359813-299ef3f6-ea29-11e7-877c-6548753e1efe.png)

HORTIZONTAL SCROLLBAR:
![image](https://user-images.githubusercontent.com/22984739/34359831-49200850-ea29-11e7-96ed-7b9b64e0eac6.png)

**Comment by mstellaluna** [comment]
may be related to :: https://github.com/freeCodeCamp/freeCodeCamp/pull/13981

**Comment by vkWeb** [comment]
@mstellaluna Actually, I also noticed this. But having too many scroll bars will result in less room for the main content. 
If you focus your cursor on the code editor you'll able to scroll through the code by using your scroll wheel on the mouse. Here's a GIF below to illustrate: 
![](https://i.imgur.com/r1z7VFL.gif)

**Comment by mstellaluna** [comment]
@vkWeb yea that's what I been doing..

**Comment by vkWeb** [comment]
@QuincyLarson We'll need to dig into this.

**Comment by QuincyLarson** [comment]
@mstellaluna Thanks for discovering this strange corner case. It's possible that our solution to #13981 was incomplete. 

@vkWeb would you be interested in looking into this as well?

**Comment by vkWeb** [comment]
@QuincyLarson I'll surely look into this and I'll inform you what can be done.

**Comment by QuincyLarson** [comment]
@vkWeb Awesome! Thank you for looking into this. Please keep us posted :)

**Comment by satyaim** [comment]
@QuincyLarson  I was just going through code difference in the two above mentioned problems, and it seems as if I found out the bug. I'll be more than happy to contribute :)

**Comment by QuincyLarson** [comment]
@satyaim Awesome - if you think you've found the bug, go ahead and see if you can fix it. We would welcome your help with this! Please keep us posted on your progress.

**Comment by vkWeb** [comment]
@satyaim Great - Go ahead. Good luck 😃. 
Before raising a PR please read our [Guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by vkWeb** [comment]
@satyaim Please update us on your current status of work?

**Comment by QuincyLarson** [comment]
@vkWeb It would seem @satyaim hasn't responded - would you be interested in helping tackle this issue?

**Comment by vkWeb** [comment]
@QuincyLarson I investigated this issue. Actually, this is limited to react & redux challenges only.

**Comment by QuincyLarson** [comment]
@vkWeb OK - thanks for digging in deeper on this. Can you figure out why this is affecting the React & Redux challenges? If you can find the guilty code, we can discuss how to most elegantly fix it.

**Comment by vkWeb** [comment]
@QuincyLarson I tried looking into this but I'm unable to find the bug that's causing this. By the way, I don't think this will create any problem for our campers. Also, the react & redux challenges are kinda very sensitive right now. So, maybe we should skip this.

**Comment by damontian1** [comment]
@QuincyLarson I think [this](https://github.com/freeCodeCamp/freeCodeCamp/pull/16625) should fix it?

**Comment by vkWeb** [comment]
@damontian1 That's great.

**Comment by QuincyLarson** [comment]
@damontian1 OK - I've asked @Bouncey to QA this :)
