### ISSUE TITLE
Image Search Abstraction API listed as Exercise Tracker on profile page

### ISSUE THREAD

**Issue by JacksonBates** [freeCodeCamp/freeCodeCamp#16336]
#### Issue Description

The 'Exercise Tracker' shows up as completed on 7th July 2016 on my profile. The actual project it is referring to is the Image Search Abstraction Layer project.

The 'view solution' link links to: `https://beta.freecodecamp.org/challenges/api-and-microservice-projects/exercise-tracker?solution=http%3A%2F%2Fpowerful-lowlands-49298.herokuapp.com%2F`

As you can see, the url definitely thinks it's the tracker, but my app linked to is the image one. I haven't completed the exercise tracker. 

The link doesn't actually open up the tracker / image app, it just links to the incomplete exercise tracker challenge page.

You can find this on my profile page, in the challenges section: https://beta.freecodecamp.org/en/jacksonbates

#### Browser Information

* Browser Name, Version: Chrome 60
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![ex tracker bug](https://user-images.githubusercontent.com/4337740/34377916-7d18adfa-eb47-11e7-9964-398d127e8e6e.png)

**Comment by Bouncey** [comment]
I have found the issue. It seems that the image search project was removed at the same time the exercise tracker project was added. For some reason, the exercise tracker project was given the id of the image search project.

@QuincyLarson [this commit](https://github.com/freeCodeCamp/freeCodeCamp/commit/b92d3cc62585afb0a6457d81849c27c7ff8a5e6b#diff-7feeb22a99fc88053d8290b0a3e0ab28) is responsible. What would you like to do?

**Comment by Bouncey** [comment]
This will also effect the ability to claim legacy certs.

I think the easiest way around this is generating a new `ObjectId()` for the exercise tracker project

**Comment by QuincyLarson** [comment]
@Bouncey Nice catch. I'll fix this real quick and open a PR.
