### ISSUE TITLE
Basic JavaScript: Quoting Strings with Single Quotes - 2nd test failing

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16332]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/basic-javascript/quoting-strings-with-single-quotes

#### Issue Description

The code is failing to pass the challenge.
I have tried reset and a browser refresh, still fails.
the code passes FCC production equivalent of the challenge.

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js
`var myStr = '<a href="http://www.example.com" target="_blank">Link</a>';`


```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34367225-d9873ed0-ea75-11e7-98e6-d63742e46e5e.png)

**Comment by systimotic** [comment]
Good catch @mstellaluna!

Related: #16344

**Comment by bteng22** [comment]
This one seems like a quick fix—I can pick it up if no one's assigned!
