### ISSUE TITLE
How to use package.json challenge not accepting correct answer

### ISSUE THREAD

**Issue by trothaar** [freeCodeCamp/freeCodeCamp#16333]
![screenshot 6](https://user-images.githubusercontent.com/8755099/34368655-7b6fa8f6-ea83-11e7-8fd2-c262fc3730e6.png)
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/managing-packages-with-npm/how-to-use-packagejson-the-core-of-any-nodejs-project-or-npm-package

#### Issue Description

My answer is correct, but FCC won't accept it; the console says that it isn't communicating with Glitch (see screenshot).

#### Browser Information

* Browser Name, Version:  Google Chrome Version 63.0.3239.108 (Official Build) (64-bit)
* Operating System: Windows 10 Home
* Mobile, Desktop, or Tablet:  Laptop

#### Your Code

{
	"name": "fcc-learn-npm-package-json",
  "author": "Teresa Rothaar,
	"dependencies": {
		"express": "^4.14.0"
	},
	"main": "server.js",
	"scripts": {
		"start": "node server.js"
	},
	"engines": {
		"node": "4.4.5"
	},
	"repository": {
		"type": "git",
		"url": "https://idontknow/todo.git"
	}
}

```
#### Screenshot
<!-- Add a screenshot of your issue -->
![screenshot 6](https://user-images.githubusercontent.com/8755099/34368620-3fbe5366-ea83-11e7-9ae4-c2bac8664bf9.png)

**Comment by huyenltnguyen** [comment]
You forgot to add a closing quotation mark `"` in `"author": "Teresa Rothaar`.

**Comment by ncaron** [comment]
Your answer is not correct. You should use the live link of your project, not link to edit the project. Click there and use the new link.

![glitch](https://user-images.githubusercontent.com/13804601/34369926-74e12b82-ea96-11e7-890c-e89ee81ed8d2.png)

**Comment by trothaar** [comment]
Well, I feel silly now. Sorry about that, but thanks for pointing out my error!

**Comment by ChrisBrownie55** [comment]
@QuincyLarson Looks like a closed issue

**Comment by Kose-Uk45** [comment]
Hi! The Glitch links doesn't not properly import the github repo and as so the server.js and other files does not get the required validation scripts. 
I tried many times for long until lately. 
The best solution to this problem is;
Create a new Glitch project,
Clone the github repository to your system and then upload the files manually to your glitch project.
Hope this one works out for someone out there struggling on the same issue.

**Comment by harshil-darji** [comment]
This link helped me out.

https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package/301528
