### ISSUE TITLE
"submit and go to next challenge" is not responding to a keyboard shortcut

### ISSUE THREAD

**Issue by agitaev** [freeCodeCamp/freeCodeCamp#16352]
#### Issue Description

Keyboard shortcut (**_Command + Enter_**) for 'Submit And Go To Next Challenge', which pops up in a modal window after challenge completion is not working.

#### Browser Information

* Browser Name, Version: Google Chrome
Version 63.0.3239.108 (Official Build) (64-bit) 
* Operating System: MacOS High Sierra v10.13.2

#### Screenshot

![image](https://user-images.githubusercontent.com/23414386/34401993-af694a5c-ebc0-11e7-9d1b-331e8812ab9d.png)

**Comment by mstellaluna** [comment]
added beta label

**Comment by vkWeb** [comment]
@agitaev It is working fine for me. Please make sure that the code isn't locked.  
![](https://i.imgur.com/9D4DGsp.png)

@QuincyLarson This can be closed.

**Comment by fhavrlent** [comment]
Ctrl+Enter works, I think @agitaev is reffering to the fact that Mac uses Command instead of Ctrl.

**Comment by systimotic** [comment]
@agitaev Thanks for reporting this bug! Can you check the console to see if there are any errors when you press `Cmd + Enter`?

Can somebody else on macOS confirm that `Cmd + Enter` doesn't work?

**Comment by vkWeb** [comment]
@systimotic  Oh. Actually, It's working fine on Windows.

**Comment by fhavrlent** [comment]
@systimotic I tried it and it was not working, there was just `meta` instead of `metaKey` in the code.
