### ISSUE TITLE
Beta: Waypoint: Create a Bootstrap Headline - typo

### ISSUE THREAD

**Issue by richyvk** [FreeCodeCamp/freecodecamp#1635]
Challenge http://beta.freecodecamp.com/challenges/waypoint-create-a-bootstrap-headline

Third para, bootstrap should be Capiltalised, like:

"Color your h3 element with the "text-primary" Bootstrap class, and center it with the "text-center" Bootstrap class."

**Comment by Greenheart** [comment]
Fixing it right now :)
