### ISSUE TITLE
Using typeof challenge requires semicolons to be correct

### ISSUE THREAD

**Issue by ChrisBrownie55** [freeCodeCamp/freeCodeCamp#16359]
#### Challenge Name

[Using typeof](https://www.freecodecamp.org/challenges/using-typeof)

#### Issue Description

In the Using typeof challenge, if one were to submit:
```
console.log(typeof "")

console.log(typeof 0)

console.log(typeof [])

console.log(typeof {})
```
However, if semicolons were added:
```
console.log(typeof "");

console.log(typeof 0);

console.log(typeof []);

console.log(typeof {});
```
Then all the tests are passed. Javascript does not require semicolons therefore this is simply complicating the challenge for users who do not use semicolons.

#### Screenshot

![screenshot 2017-12-28 at 11 51 18 am](https://user-images.githubusercontent.com/19195374/34420205-8930390e-ebc5-11e7-9afc-ee7c5e7ace21.png)

**Comment by systimotic** [comment]
Thanks for reporting this bug @ChrisBrownie55!

The challenge has been removed in the beta, but there is still a challenge about typeof. It also requires a semicolon. We don't need to enforce that here.

---

### What needs to be changed

You can find the code here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/5214371ef124f24f242cd8a619ba8a8f1992cbe6/seed/challenges/02-javascript-algorithms-and-data-structures/debugging.json#L129

Removing the semicolon from the regular expression there should do the trick.

Check out [CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) to get your local development environment set up.

If you need help, please go to our [contributors chatroom](https://gitter.im/FreeCodeCamp/Contributors). We're always happy to answer any questions!

**Comment by ncaron** [comment]
I submitted a PR for this. It should now work as intended.

**Comment by systimotic** [comment]
Thanks @ncaron!
