### ISSUE TITLE
Oops, something is not right, please request a fresh link to sign in / sign up.

### ISSUE THREAD

**Issue by WaysToGo** [freeCodeCamp/freeCodeCamp#16355]
#### Challenge Name
https://beta.freecodecamp.org/en/email-signin

#### Issue Description
 issue in authentication

#### Browser Information
 Google chrome Version 63.0.3239.108 (Official Build) (64-bit)->

* Browser Name, Version: Google Chrome Version 63.0.3239.108 (Official Build) (64-bit)-
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![image](https://user-images.githubusercontent.com/17769286/34417775-4cb460b2-ec20-11e7-931f-1799cb1309ce.png)

**Comment by mstellaluna** [comment]
Hello @WaysToGo this issue has already been reported and is currently being investigated. Please see https://github.com/freeCodeCamp/freeCodeCamp/issues/16288 for additional information. Thank you for reporting this issue. Happy Coding !
