### ISSUE TITLE
ES6: Create Strings using Template Literals - Test Fails - Doesn't detect template strings

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16358]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/es6/create-strings-using-template-literals

#### Issue Description

The challenge is failing the last test, 'Template strings were used'.

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js

`const resultDisplayArray = result.failure.map(x => `<li class="text-warning">${x}</li>`);`

```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34419168-58e56246-ebd0-11e7-8578-9c8da7d04ea2.png)

**Comment by mstellaluna** [comment]
Update: after some investigation by one of our campers, it seems the staging branch fixes the issue but has not been ported over to beta.

**Comment by systimotic** [comment]
I can confirm that it does work on staging, but I think the description could use a bit of clarification.

**Comment by vipatron** [comment]
Had a similar issue. Agree with systimotic. Text change in the test cases proposed as follows:

Current: Template strings were used
Proposed: Template strings were used with map()

**Comment by PolarisTLX** [comment]
I have looked into this today, the challenge does not indicate that using .map()  is required, and I was able to solve/complete it with and without using .map().  Therefore I don't believe that this needs any changes?

Paul (@PolarisTLX) and Kyle (@jklemon17)

**Comment by scissorsneedfoodtoo** [comment]
I checked this out recently using @mstellaluna's solution and also solved it without using map as @PolarisTLX did. Using map is probably the most concise way to complete this challenge, but I think we should leave it up to users how to go about it. I'm not sure the description needs any changes since the user is told what the makeList function should return.

**Comment by yoizfefisch** [comment]
The test also fails when using a for loop.

**Comment by scissorsneedfoodtoo** [comment]
@yoizfefisch, you're right. Both of those are valid solutions, but they don't pass.

It seems like test case for template literals is not quite flexible enough: 

```
getUserInput => assert(getUserInput('index').match(/\\`<li class=\"text-warning\">\\$\\{\\w+\\}<\\/li>\\`/g)
```

The regex doesn't expect brackets before the next curly brace, and your solutions cause the test to fail. Should be a simple enough fix. I'm not the best with regex, but this should allow for different solutions like the ones above:

```
`<li class=\"text-warning\">\$\{(\w+|\w+\[[\w\W]+\])\}<\/li>\`
```

I'm not sure exactly where some characters would have to be double escaped with two slashes like in the current tests, though. Would anyone here in interested in updating this test and submitting a PR?

**Comment by MarkKGit** [comment]
Would also like to report this is still an issue, map works for the solution.

**Comment by aenkirch** [comment]
Considering I have the same problem on the stable version of ES6 on FCC that was just deployed earlier this week, I have some doubt considering my code.. Can someone help me ?

Here is my code : https://repl.it/repls/DizzyNiftyLocatorprogram

**Comment by MarkKGit** [comment]
Push doesn't work in this exercise (or it hasn't or me and seems like
others), use the .map method to pass the test.

*Mark Kleinhaus*
*mkleinhaus@gmail.com <mkleinhaus@gmail.com>*
*206-234-4887*

**Comment by Omerdogan3** [comment]
They are passing result.failure as a parameter.

The Right Answer Is

`const result = {
  success: ["max-length", "no-amd", "prefer-arrow-functions"],
  failure: ["no-var", "var-on-top", "linebreak"],
  skipped: ["id-blacklist", "no-dup-keys"]
};
function makeList(arr) {
  "use strict";

  // change code below this line
  const resultDisplayArray = arr.map(x => `<li class="text-warning">${x}</li>`);

  return resultDisplayArray;
}
/**
 * makeList(result.failure) should return:
 * [ <li class="text-warning">no-var</li>,
 *   <li class="text-warning">var-on-top</li>, 
 *   <li class="text-warning">linebreak</li> ]
 **/
const resultDisplayArray = makeList(result.failure);`

**Comment by P1xt** [comment]
confirmed:

```
const resultDisplayArray = arr.map((a) => {
  return `<li class="text-warning">${a}</li>`
});
```
works
but
```
const resultDisplayArray = [
  `<li class="text-warning">${arr[0]}</li>`,
  `<li class="text-warning">${arr[1]}</li>`,
  `<li class="text-warning">${arr[2]}</li>`
];
```
does not work. And, there's no mention of map in the lesson - and, map isn't even introduced in the curriculum until the Functional Programming section which comes after this section.

**Comment by inquiloper** [comment]
@P1xt  Having the same problem. Thankfully is not only me.

**Comment by richa031** [comment]
const result = {
  success: ["max-length", "no-amd", "prefer-arrow-functions"],
  failure: ["no-var", "var-on-top", "linebreak"],
  skipped: ["id-blacklist", "no-dup-keys"]
};
function makeList(arr) {
  "use strict";

  // change code below this line
  const resultDisplayArray =
 [`<li class="text-warning">${arr[0]}</li>`, 
  `<li class="text-warning">${arr[1]}</li>`, 
  `<li class="text-warning">${arr[2]}</li>`];
  // change code above this line

  return resultDisplayArray;
}
/**
 * makeList(result.failure) should return:
 * [ <li class="text-warning">no-var</li>,
 *   <li class="text-warning">var-on-top</li>, 
 *   <li class="text-warning">linebreak</li> ]
 **/
const resultDisplayArray = makeList(result.failure);****

**Comment by richa031** [comment]
i'm having the same problem

**Comment by inquiloper** [comment]
@richa031  As pointed out above, you need to use Array.map, with your approach does not work.

**Comment by richa031** [comment]
is there anything i wrote wrong? and why are we using map function here?

**Comment by kanexte** [comment]
It's a silly issue but but double quotes are also required between the string literal when single quotes should be an acceptable solution as well.

**Comment by aps120797** [comment]
In continuation to https://github.com/freeCodeCamp/freeCodeCamp/issues/16358#issuecomment-396369730,
I would like to add that this neither works: 
```js
const resultDisplayArray = [];
  for (let i = 0; i < arr.length; i++) {
    resultDisplayArray[i] = `<li class="text-warning">${arr[i]}</li>`
  }
```

**Comment by richa031** [comment]
@kanexte thank u

**Comment by bapinney** [comment]
Just wanted to chime in and mention I am having this same problem, too.  Glad to hear it's not me.  Hope it gets fixed soon.

**Comment by numoonchld** [comment]
Facing the same issue. I guess I'll have to keep this challenge officially unfinished and move on. IM(H)O - for the scope of this challenge, referencing the array elements by their indices is the most elegant solution and using map/loops clutters up the code.

**Comment by Tirjasdyn** [comment]
I am also having this problem. I tried using map and I now get an error that says: 

React is not defined

I thought I was getting this too but throwing map in here just makes it unnecessarily difficult.

**Comment by raftar2097** [comment]
how did u solve the issue @richa031

**Comment by osmi2017** [comment]
P1xt is rigth array.map is the key for this challenge but you shouldnot forget that it takes a function as a parameter

**Comment by stayreal123** [comment]
@Tirjasdyn  i Am having the same issue , fcc Es6 section is so broken. Very less instructions. No instruction of how to use map(), filter() , reduce() in previous challenges too .

**Comment by stayreal123** [comment]
is there any proper solution to this prob ?

**Comment by stayreal123** [comment]
@Omerdogan3 This is not the correct way , as you look in the challenge the desired output is 
makeList(result.failure) should return:
 * [ <li class="text-warning">no-var</li>,
 *   <li class="text-warning">var-on-top</li>, 
 *   <li class="text-warning">linebreak</li> ]
as your solution didn't print comma or ',' .

**Comment by alhazen1** [comment]
I'm in agreement with @scissorsneedfoodtoo that the regex in test case is too restrictive.

I'm no regex wiz but this is what I came up with /`<li class="text-warning">\$\{[\w\[\]]+\}</li>`/g (without the backslashes escaped for string). This would allow for... loop solutions that accessed the array with bracket notation arr[i] which appears to be disallowed with the current regular expression test.

**Comment by osmi2017** [comment]
const resultDisplayArray = arr.map((a) => {
  return `<li class="text-warning">${a}</li>`
});``

**Comment by pcatana** [comment]
Still getting `Invalid regular expression flags`

**Comment by hnryjmes** [comment]
I just get `Invalid regular expression flags`

**Comment by mjbenefiel** [comment]
I’m still receiving errors for correct solutions, as well.

**Comment by 2series** [comment]
still getting the> Invalid regular expression flags

**Comment by scissorsneedfoodtoo** [comment]
Hi all. Thank you for taking the time to update us about this ongoing issue. Just wanted to let you all know that the regex test for this challenge was updated recently, and it should be pushed to production soon.

**Comment by mirkocoppola80** [comment]
Still getting Invalid regular expression flags

**Comment by zeb-stephen-downs** [comment]
@mirkocoppola80 yeah, I'm not sure how often their merge/builds are. I don't think they've done one since May 30th though, so we're waiting on that for the changes to take effect.

**Comment by chenjacky131** [comment]
Invalid regular expression flags for today,waiting for the update...

**Comment by jsparadacelis** [comment]
i try wiht map, for loops, etc, but i don found a solution. You can see it, maybe found a key idea. https://www.youtube.com/watch?v=XzExdQye1Ls

**Comment by chenjacky131** [comment]
@jsparadacelis  I follow the code on that video ,that doesn't work

**Comment by AndrewJBateman** [comment]
Hi, I am also still getting Invalid regular expression flags with:

const resultDisplayArray = arr.map(item => `<li class="text-warning">${item}</li>`);

**Comment by pedrobertao** [comment]
It is still not working. Can we have a light here please ?

**Comment by iamskok** [comment]
I get **Invalid regular expression flags** error. 

const resultDisplayArray = arr.map((msg) => {
    return `<li class="text-warning">${msg}</li>`;  
});

**Comment by nabendu82** [comment]
I also get the **Invalid regular expression flags** error for below.
<img width="629" alt="screen shot 2018-07-11 at 9 37 41 pm" src="https://user-images.githubusercontent.com/17110163/42585231-aded94ae-8552-11e8-9fe2-081b9783883f.png">

**Comment by kguevara** [comment]
I’m still receiving  **Invalid regular expression flags** error.
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/create-strings-using-template-literals/

**Comment by OumaimaTiguint** [comment]
I tried it with map and everything and I still get Invalid regular expression flags

**Comment by dbaleeds** [comment]
Confirmed still not working

**Comment by ryanxmccarthy** [comment]
Still not working, rather frustrating

**Comment by typhoon93** [comment]
Right now neither MAP method nor the more simple but lengthy approaches work, same error - "Invalid regular expression flags" even though the other tests are passed

**Comment by ThiagoRAD** [comment]
Hey, if anyone found a way please tell meeee, I can't advance xD (i know i could skip it but oh my OCD)

**Comment by iamtirado** [comment]
Still not working for me.

**Comment by Yonazar** [comment]
Hey, i'm just another guy to write that it doesn't work still.

**Comment by cdmccauley** [comment]
I've seen that this is supposedly fixed and not yet deployed but, wanted to post in case it needs more info. I've confirmed the correct output with console.log() however, my solution does not pass the test "Template strings were used".
my code:
```
const resultDisplayArray = arr.map(x => `<li class="text-warning">${x}</li>`);
console.log(resultDisplayArray);
```
console output:
```
// running test
Invalid regular expression flags
// tests completed
<li class="text-warning">no-var</li>,<li class="text-warning">var-on-top</li>,<li class="text-warning">linebreak</li>
```

**Comment by TheNewStyles** [comment]
Still not working. const resultDisplayArray = arr.map(num => `<li class="text-warning">${num}</li>`); 
// running test
Invalid regular expression flags
// tests completed

**Comment by mihaid85** [comment]
Map method still doesn't work. With or without return.

**Comment by alex88K** [comment]
still waiting for fix

**Comment by LML013** [comment]
`const resultDisplayArray = arr.map(val=>{return `<li class="text-warning">${val}</li>`});`

Getting Invalid regular expression flags result.

**Comment by seely1991** [comment]
const resultDisplayArray = arr.map(x => `<li class="text-warning">${x}</li>`);

const resultDisplayArray = [ `<li class="text-warning">${arr[0]}</li>`, `<li class="text-warning">${arr[1]}</li>`, `<li class="text-warning">${arr[2]}</li>` ];


both don't work for me, I thought it was my code, but it seems like something is broken

**Comment by baisho** [comment]
Tried to solve it today, but it still doesn't work.

**Comment by thembones79** [comment]
I've tried it also with escape marks:

> const resultDisplayArray = arr.map(x => `<li class=\"text-warning\">${x}</li>`);

but it is still "Invalid regular expression flags"

**Comment by omendez30** [comment]
I too have tried to solve it, but continue to get the same "Invalid regular expression flags" as an output. 2 out of the three test are being passed but I continue to get the message. 

const resultDisplayArray = arr.map(val =>`<li class="text-warning">${val}</li>`);

I also used a simple for loop and get the same result

**Comment by AlessioMaddaluno** [comment]
Still not fixed! 😢

**Comment by hnryjmes** [comment]
I've now completed the rest of the JavaScript course, so this is the only thing preventing me from getting a certificate. If anyone could suggest a way to get the checks to work, so I can claim my certificate, I would really appreciate it!

**Comment by coolcourd** [comment]
yeah i have written it like 4 ways and it doesnt work. its busted. just skip it and move on

**Comment by Cr0s4k** [comment]
Still not working..

**Comment by bauerpm7** [comment]
Same problem; 

``const resultDisplayArray = arr.map((a) => {
  return `<li class="text-warning">${a}</li>`
});``

returns the error "invalid regular expression flags"

**Comment by Magvin** [comment]
Confirm still not working.
Tried forEach, for loop,map..No idea what is going on with this challenge

**Comment by alex-mos** [comment]
It works! I try the same solution with map every week and now it has passed! Hooray!

**Comment by jasjitsm** [comment]
Worked for me too! :) Wasn't working yesterday.

**Comment by alexanderc12** [comment]
Confirmed now works with 

```
const resultDisplayArray = arr.map((msg) => {
  return `<li class="text-warning">${msg}</li>`;
});
```

Thanks for the fix.

**Comment by chenjacky131** [comment]
alleluia.finally works

**Comment by federicosan** [comment]
this should work without the map function, just using normal template literals, ass this would teach how  space is preserved without adding <br> tags or &nbsp;

**Comment by RilindaA** [comment]
Below you can find the code that works :) : 

const result = {
  success: ["max-length", "no-amd", "prefer-arrow-functions"],
  failure: ["no-var", "var-on-top", "linebreak"],
  skipped: ["id-blacklist", "no-dup-keys"]
};
function makeList(arr) {
  "use strict";

  // change code below this line
  const resultDisplayArray = [`<li class="text-warning">${arr[0]}</li>`,
  `<li class="text-warning">${arr[1]}</li>`,
  `<li class="text-warning">${arr[2]}</li>` ];
  // change code above this line

  return resultDisplayArray;
}
/**
 * makeList(result.failure) should return:
 * [ `<li class="text-warning">no-var</li>`,
 *   `<li class="text-warning">var-on-top</li>`, 
 *   `<li class="text-warning">linebreak</li>` ]
 **/
const resultDisplayArray = makeList(result.failure);
