### ISSUE TITLE
[Beta] Matching Braces color in the editor needs to be changed

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16363]
#### Issue Description
The matching braces color `#00ff00` in the beta looks weird and after some time it becomes difficult to trace the matching pair. So, with my idea of adding a border around the matching braces like in VSCode, will resolve this issue.
Please, have a look at the below GIF's in fullscreen by clicking on them to notice the difference effectively. **This issue will be addressed in my up-coming PR.**  

Default Setup:
![before](https://user-images.githubusercontent.com/26724128/34421606-521e9700-ec36-11e7-8d27-8987550c6b95.gif)

After applying the proposed changes: 
![after](https://user-images.githubusercontent.com/26724128/34421610-5657ad16-ec36-11e7-827e-b39bf2351aff.gif)

#### Browser Information
* Browser Name, Version: Chrome(latest release) & Firefox(latest release).
* Operating System: Windows 10 Pro 32 Bit. 
* Mobile, Desktop, or Tablet: Desktop

@QuincyLarson, @raisedadead Thoughts on this?

**Comment by QuincyLarson** [comment]
@vkWeb I agree this seems friendlier than the color change, and will look uniform on night mode as well :)

**Comment by vkWeb** [comment]
@QuincyLarson Thank you so much :). I'll raise a PR for this as well.

**Comment by QuincyLarson** [comment]
Thanks for your help with this everyone. We're now using a different code editor (Monaco) so this is no longer relevant.
