### ISSUE TITLE
style `js is disabled` message in preview plane

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#16362]
As seen in #16361

At the moment it is a message in a span. This span should be classed to take advantage of bootstraps info styling. 

The component responsible for rendering can be found here: https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/routes/Challenges/Preview.jsx#L26

**Comment by Joshuaswift** [comment]
I'm working on this 👍

**Comment by joshuaswift** [comment]
This should now be styled as requested, please see PR above.
