### ISSUE TITLE
Streaks Broken?

### ISSUE THREAD

**Issue by Jorgixhallo** [FreeCodeCamp/freecodecamp#1636]
It should be 7 day streak right on both right?
![fcc](https://cloud.githubusercontent.com/assets/5603445/9134008/392e1e86-3cf8-11e5-88a9-2ae32fa6f7d9.jpg)

**Comment by BerkeleyTrue** [comment]
hello @Jorgixhallo 

This is a duplicate of #1075 and is current being fixed.

Happy Coding!
