### ISSUE TITLE
Intermediate Algorithm Scripting: Pig Latin - Not Accepting Wiki/Production Hint Code

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16378]
#### Challenge Name
Challenge Link:
https://beta.freecodecamp.org/en/challenges/intermediate-algorithm-scripting/pig-latin

Wiki Link: 
https://forum.freecodecamp.org/t/freecodecamp-algorithm-challenge-guide-pig-latin/16039

#### Issue Description
The pig latin challenge is not accepting the Wiki resource code for the challenge if a camper
uses the Wiki for help in solving the challenge.
Unsure if the challenge was updated or if this is the original challenge from production FCC.
Please verify the challenge so it either:

1) Passes using the existing Wiki page code for this challenge
2) Update the Wiki page code for this challenge accordingly

#### Browser Information

Browser Name, Version:
Operating System: FireFox 57.0 (64-bit) and Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Mobile, Desktop, or Tablet: Laptop Windows 10 Professional 64-bit

#### Your Code

```js
`  // Create variables to be used
  var pigLatin = '';
  var regex = /[aeiou]/gi;

  // Check if the first character is a vowel
  if (str[0].match(regex)) {
    pigLatin = str + 'way';

  } else {

    // Find how many consonants before the first vowel.
    var vowelIndice = str.indexOf(str.match(regex)[0]);

    // Take the string from the first vowel to the last char
    // then add the consonants that were previously omitted and add the ending.
    pigLatin = str.substr(vowelIndice) + str.substr(0, vowelIndice) + 'ay';
  }

  return pigLatin;`


```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/34456720-d5662d72-ed6b-11e7-9ba2-869806880af5.png)

**Comment by saurishkar** [comment]
Hi @mstellaluna,
I think the tests in the challenge are fine. The Wiki page needs to be updated to accommodate the condition for checking if the string does not contain any vowel.

In regard to this, i have raised a PR in freeCodeCamp/guides repo. 
Reference : [Pull Request Details](https://github.com/freeCodeCamp/guides/pull/7998)

**Comment by Bouncey** [comment]
Guide PR merged

**Comment by akkatracker** [comment]
Is this good to close then?

**Comment by Bouncey** [comment]
@mstellaluna can you please confirm :+1:

**Comment by mahmoud-coo6** [comment]
here my solution , worked for me..

function translatePigLatin(str) {
  var length = str.length;
  var tab = [];
   if(str.match(/[aeiou]/gi) === null) {
        // Check if the string contains only consonants
        var temp;
       temp= str + 'ay';
       return temp;
              } 
              
  for(var i=0; i<length; i++){
    var first = str.charAt(i);
    //voyelle
    if(first === "a" || first === "e" || first === "i" || first === "o" || first === "u" || first === "y"){
      if(i === 0){
        str = str + "way";
      }
      else{
        str = str.substring(i) + tab.join("") + "ay";
      }
      break;
    }
    //consonne
    else{
      tab.push(first);
      
    }
  }
  return str;
}

console.log(translatePigLatin("consonant"));

**Comment by AIV-T-STARK** [comment]
Here my solution: 
function translatePigLatin(str) {
  let pigLatin = "";
  let regex = /[aeiou]/;
  if(regex.test(str) === false){
    pigLatin = str + 'ay';
  }
  else {
    if(regex.test(str[0])) {
      pigLatin = str + 'way';
    }
    else {
      let x = str.indexOf(regex.exec(str)[0]);
      pigLatin = str.substr(x) + str.substr(0, x) + 'ay';
    }
  }
  return pigLatin;
}

translatePigLatin("consonant");
console.log(translatePigLatin("consonant"));
console.log(translatePigLatin("eight"));
console.log(translatePigLatin("0"));
