### ISSUE TITLE
Search is not working on beta

### ISSUE THREAD

**Issue by RitikPatni** [freeCodeCamp/freeCodeCamp#16384]
#### Issue Description

Nothing works for me I tried the map or search box and everything else nothing seems to be working for me. I've attached a gif to help with the issue and a console screenshot so that you can easily spot the problem

#### Browser Information

* Browser Name, Version: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
 
* Operating System: Linux Mint Cinnamon 18.1 64-Bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```
#### Screenshot

**Problem GIF**
![applied-responsive-web-design-projects_-build-a-survey-form-_-freecodecamp](https://user-images.githubusercontent.com/16117262/34462078-611ea600-ee61-11e7-964a-0214d4dafe0c.gif)
**Console ScreenShot**
![screenshot from 2017-12-31 19-34-42](https://user-images.githubusercontent.com/16117262/34462092-b6780132-ee61-11e7-96a4-a1f93c11b906.png)

**Comment by saurishkar** [comment]
@RitikPatni Hi , Are you still receiving this error ?

**Comment by RitikPatni** [comment]
Here's the screenshot 
![screenshot from 2018-01-02 19-31-45](https://user-images.githubusercontent.com/16117262/34486015-a5412090-eff3-11e7-93b3-dd3905ce7819.png)

**Comment by hadiswais** [comment]
Same problem here

**Comment by accimeesterlin** [comment]
It works for me. Consider doing ```git pull --rebase upstream staging``` to get the most recent changes.
