### ISSUE TITLE
Gracefully handle missing hints

### ISSUE THREAD

**Issue by ozzymuppet** [freeCodeCamp/freeCodeCamp#16381]
#### Challenge Name
https://www.freecodecamp.org/challenges/manipulating-complex-objects

#### Issue Description
When clicking on 'Get a Hint' it leads to a "Oops! That page doesn’t exist or is private." page.

#### Browser Information
* Browser Name, Version: Firefox 57.0.3
* Operating System: Windows 10
* Mobile, Desktop, or Tablet:  Desktop

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/20009986/34458232-adb0d12a-ee1e-11e7-9486-b7b726778dc8.png)

**Comment by QuincyLarson** [comment]
Closing in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/16388
