### ISSUE TITLE
Beta: Typo in Basic JavaScript: Iterate with JavaScript Do...While Loops

### ISSUE THREAD

**Issue by agitaev** [freeCodeCamp/freeCodeCamp#16389]
#### Challenge Name

Basic JavaScript: Iterate with JavaScript Do...While Loops
https://beta.freecodecamp.org/en/challenges/basic-javascript/iterate-with-javascript-dowhile-loops

#### Issue Description

Typo in the pre-last paragraph of the description of the challenge - 'Essenially' written instead of 'Essential'.

**Comment by warborn** [comment]
I'd like to take this if it's possible, i found the typo and it seems that only a change in the seed file is required

**Comment by raisedadead** [comment]
@warborn sure please go ahead. if you need assistance then hit us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), and follow our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) for setup.
