### ISSUE TITLE
[Beta] [Important] Git Challenges are Missing 

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16383]
#### Issue Description

In the beta version, Git challenges are missing. I think Git is a very important tool for our campers and it's the same tool powering freeCodeCamp codebase. 

@QuincyLarson, @Bouncey, @BerkeleyTrue. This is important.

**Comment by QuincyLarson** [comment]
@vkWeb We plan to add these in the near future. We will need to "fake" these, since we will want to be able to teach these completely client-side, and as far as I know there's now way to emulate Git in the browser.

**Comment by vkWeb** [comment]
@QuincyLarson Okay. We should have included Git-it for the time. But No problem 👍

**Comment by QuincyLarson** [comment]
@vkWeb I've opened an issue here. Is this something you might be interested in tackling? https://github.com/freeCodeCamp/freeCodeCamp/issues/16390
