### ISSUE TITLE
Normalize flash type

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#16395]
Normalize flash type.
The different level of message types provided by bootstrap are 'info', 'warning', 'danger', 'success'. The express flash system is currently using 'info', 'success', 'errors' (inconsistent with BS style and inconsistent pluralization)

 These should all be normalized to the BS style from front to back.

Relavent code:

https://github.com/freecodecamp/freecodecamp/blob/staging/server/views/partials/flash.jade
https://github.com/freecodecamp/freecodecamp/blob/staging/server/middlewares/error-handlers.js#L33
https://github.com/freecodecamp/freecodecamp/blob/staging/server/views/account/email-signin.jade#L65

(note: this is some not all of the locations where we use flash/alert messages)

**Comment by Powell-v2** [comment]
Heyyo, I think I can help with this one. It will be my first contribution to this project, so could you please elaborate a bit more on the objective? Namely, terms **flash type** and **express flash system** confuse me :D

**Comment by BerkeleyTrue** [comment]
The objective is to normalize the flash naming convention across the front and backend. flash type dictates the style of message to display. express flash is a library

**Comment by cassidypignatello** [comment]
I'm happy to take this one if it's not being worked on!

**Comment by Powell-v2** [comment]
Go ahead, Cassidy : )
