### ISSUE TITLE
Octal Escape Sequence Error with Travis CI Build

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#16396]
#### Issue Description

User @AungMyoKyaw issued a pull request (#15856) to update Euler Project problem 4 in the interview prep section. Though the updated code in the pull request is correct and passes `npm test`, Travis CI throws the error `Octal escape sequences are not allowed in strict mode.` However, the error occurs due to a leading zero in the solution of the Create a Priority Queue problem in the data structures portion of the interview prep section.

**Comment by raisedadead** [comment]
Closing as its to be solved on the original PR.
