### ISSUE TITLE
Laptop webpage loads to fill width of entire screen instead of in sections

### ISSUE THREAD

**Issue by LiVinson** [freeCodeCamp/freeCodeCamp#16402]
#### Issue Description

I was in the middle of doing the “Line up Form Elements Responsively with Bootstrap” lesson when I began having issues with the page and the code editor was not responding so I refreshed the page.

What loads now stretches to fill the entire width of the window: the instructions were stretched the full width of the screen instead of being the left column, the text editor is stretched the full width of the screen instead of being in the center, and the webpage that is created from the text editor is the full width instead of being on the right. This makes it so everything is very wide and I have to scroll really far down to see all of the content instead of it fitting in my window with minimal scrolling.

This occurs on the home page and all freeCodeCamp learning pages for me, but not for the forums or other sections. When I load the page in a different browser, it works (i.e. Microsoft Edge).

#### Browser Information

* Browser Name, Version:  Chrome, Version  63.0.3239.108
* Operating System:  Windows 10
* Mobile, Desktop, or Tablet:  Desktop

#### Screenshot
**How it Should Display (Microsoft Edge):**

![fccimage3](https://user-images.githubusercontent.com/32377608/34505546-99d6bab2-eff3-11e7-85b2-10584f6df4aa.JPG)

**How it Displays for me in Chrome:**

![fccimage1](https://user-images.githubusercontent.com/32377608/34505521-6db82948-eff3-11e7-809e-482d1609e93a.JPG)

![fccimage2](https://user-images.githubusercontent.com/32377608/34505535-82ab1702-eff3-11e7-9a29-edbf0e34ad29.JPG)

**Comment by Bouncey** [comment]
Is this using the same device? What is your screen width?

**Comment by LiVinson** [comment]
Yes, it's the same 13.3 " laptop.

**Comment by LiVinson** [comment]
When I booted up today, it worked fine. Not sure of the original cause.
