### ISSUE TITLE
[beta] Project submission challenges - Images are undefined

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#16410]
Most images on the submission pages are broken due to an incorrect link, the majority are `http://i.imgur.com/undefined.png`

If `image` is falsey [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/a7a436651d338059a0f7506cfd9b9495eb737f6e/common/app/routes/Challenges/views/project/Project.jsx#L44) then we shouldn't try to render an image.

**Comment by jameskaupert** [comment]
Believe I have a fix for this.  Changed line 62 to `src={ image ? imageURL : false }`

**Comment by jameskaupert** [comment]
I posted in the PR but it looks like this is still an issue.  I have two options for fixing this.  Waiting for an understanding in the Gitter channel or here for what our process is to reopen / resubmit.
