### ISSUE TITLE
Escape Sequences in Strings coming up with bad solution even when solution is correct

### ISSUE THREAD

**Issue by pekac45** [freeCodeCamp/freeCodeCamp#16425]
#### Challenge Name

Escape Sequences in Strings 
https://www.freecodecamp.org/challenges/escape-sequences-in-strings

#### Issue Description

I come up with correct solution which works in brackets or any other text editor but freeCodeCamp editor comes up saying it's wrong. Tried multiple different solutions from "get a hint" but none of them are working. 

#### Browser Information

* Browser Name, Version:  Chrome 63.0.3239.84
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

var myStr = "FirstLine\n\\SecondLine\\\nThirdLine"; 


```

**Comment by Asjas** [comment]
@pekac45 Your code will fail. The reason being your code fails two of the tests.

The first is your variable `myStr` should have **only** one newline character `\n`
The second is your variable `myStr` should have one carriage return character `\r`

You have two newline `\n` characters. That will cause the tests to fail

**Comment by Asjas** [comment]
@pekac45 

Github issues are reserved for reporting bugs or broken tests.

If you need assistance with understanding how to solve a particular challenge the [Freecodecamp gitter](https://gitter.im/FreeCodeCamp/HelpFrontEnd) chatroom is where you can ask for help.

**Comment by pekac45** [comment]
Thanks, that was my bad.
