### ISSUE TITLE
Add default image to Projects

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#16426]
Same project challenges do not provide an image. We will need a default image to render here instead of nothing.

see: #16410

**Comment by jameskaupert** [comment]
I'll take a look at this since I had worked #16410.  Any preference on what the default image should display?  Some ideas:

- FCC logo or a variant on it
- Some sort of generic "Placeholder Image" text on a colored background (don't think we'd want this)
- "Good Luck!" text on a colored background

**Comment by raisedadead** [comment]
We could use some of the motivational quotes? These could be added to the words.json in common / utils.

**Comment by BerkeleyTrue** [comment]
@raisedadead that might add a lot of complications. We should just add a default image (fcc logo) to get this solved.

**Comment by raisedadead** [comment]
@jameskaupert so, lets add the freeCodeCamp logo with a `@darkgreen` (`#006400`) background. You can grab the asset for logo at https://github.com/freeCodeCamp/assets/tree/master/assets/logos

You will have to upload them to imgur for now. And create a PR. We will later check with Quincy to move it to S3 bucket, as a part of our ongoing chore.

**Comment by jameskaupert** [comment]
Awesome, will do.  Thanks!
