### ISSUE TITLE
A list of Bonfires that have missing punctuation or mispellings

### ISSUE THREAD

**Issue by thepeted** [FreeCodeCamp/freecodecamp#1642]
Challenge http://beta.freecodecamp.com/challenges/magical-maths-addition has an issue. 

In JavaScript whole numbers (called integers) can be easily used to preform mathematical functions  <--

Let's try a few of the most commonly used ones now  <--

We use + for addition  <--

__________________________

Challenge http://beta.freecodecamp.com/challenges/magical-maths-subtraction has an issue.

In JavaScript whole numbers (called integers) can be easily used to preform mathematical functions <--

Let's try a few of the most commonly used ones now <--

We use - for subtraction <---

_________________________

Challenge http://beta.freecodecamp.com/challenges/magical-maths-multiplication has an issue.

In JavaScript whole numbers (called integers) can be easily used to preform mathematical functions <--

Let's try a few of the most commonly used ones now <---

We use * for multiplication <---

________________________

Challenge http://beta.freecodecamp.com/challenges/creating-decimals has an issue.

*i*n JavaScript we can can work with decimal numbers <--- needs full stop.

_________________________________________________________

*i*n JavaScript we can can work with decimal numbers <--- needs fullstop.

These decal numbers are known as floats.

Let's take a look at working with floats now <---- needs full stop

**Comment by BerkeleyTrue** [comment]
Hello @thepeted 

Can you combine the previous issues on missing punctuations and misspelling into this issue and close the others?

**Comment by thepeted** [comment]
Yep, its done.
