### ISSUE TITLE
[Beta] [React & Redux Challenges] Code Mirror has White Background in Night Mode

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16434]
#### Challenge Name
All React, Redux, and React & Redux Challenges. 

#### Issue Description
The code editor on all of the React, Redux, and React & Redux Challenges has a white background in night mode. It should be same as that of other challenges. 
![2018-01-07](https://user-images.githubusercontent.com/26724128/34647630-0fa5177c-f3ad-11e7-8b70-412d136b3439.png)

#### Browser Information
* Browser Name, Version: Chrome & Firefox (latest release of both) 
* Operating System: Windows 10 Pro 32 Bit.
* Mobile, Desktop, or Tablet: Desktop.

**Comment by raisedadead** [comment]
See discussion in https://github.com/freeCodeCamp/freeCodeCamp/issues/16319
