### ISSUE TITLE
[Beta] Preview Pane has a different background color

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16435]
#### Issue Description
Preview pane has a `#737373` background-color. It should be white. 

#### Browser Information
* Browser Name, Version: Chrome & firefox (latest).
* Operating System: Windows 10 Pro 32 Bit.
* Mobile, Desktop, or Tablet: Desktop

**Comment by raisedadead** [comment]
Fixed in #14507
