### ISSUE TITLE
Twitch TV API v5 will be out of use by the end of 2018

### ISSUE THREAD

**Issue by onomesotu** [freeCodeCamp/freeCodeCamp#16439]
#### Issue Description
The current Twitch Tv API v5 is deprecated and will be completely replaced by the end of 2018.
Just an FYI so the challenge may be updated to the new API or new challenge proposed.

**Comment by erictleung** [comment]
@onomesotu thanks for bringing to this our attention! The [challenge itself](https://www.freecodecamp.org/challenges/use-the-twitchtv-json-api) doesn't suggest using the API directly, but instead to use a workaround we've implemented so you don't need an API key. However, this workaround may and probably does use the API V5 (someone would need to verify this).

Sidenote: just [a reference](https://dev.twitch.tv/docs) for Twitch announcing the API deprecation and removal

> V5 is deprecated as of 8/31/17 and will be removed entirely on 12/31/18 (in favor of the new Twitch API, mentioned above).

cc/ @freeCodeCamp/moderators

**Comment by mstellaluna** [comment]
@erictleung  maybe a contact us page that integrates the google map API ? https://developers.google.com/maps/documentation/api-picker

**Comment by RaphaelAddile** [comment]
@erictleung Just started working on the Twitch API challenge and it uses the V5 API.

Also the fcc wrapper documentation says:

> Replace the Twitch API base URL `https://api.twitch.tv/kraken` with `https://wind-bow.gomix.me/twitch-api`. Use this endpoint according to the Twitch API documentation.

`https://api.twitch.tv/kraken` is for V5, the new one uses `https://api.twitch.tv/helix`.

Also while at it, the wrapper should probably update the link to the documentation. It still links to https://github.com/justintv/Twitch-API, the current documentation for the V5 API is at https://dev.twitch.tv/docs/v5. The challenge itself already links to new location.

**Comment by erictleung** [comment]
@mstellaluna just to clarify, you are suggesting a new API challenge with the Google Map API? If so, that could be an interesting challenge, as it is something that many developers might want to make for themself on their own personal page. I like the idea. However, we might be able to just update the Gomix instance with the new Twitch API (I'm not sure how much effort this would take).

@RaphaelAddile thanks for the additional details on the Kraken vs Helix API names. Indeed, we should at least change the wrapper link.

**Comment by Ethan-Arrowood** [comment]
@RaphaelAddile can you open a PR with these changes?

**Comment by Em-Ant** [comment]
The wrapper project is on my glitch account, and at the moment it is using my api key. I'll make camperbot's account a collaborator of the project in glitch, so freecodecamp will own the project.

Is changing `/kraken` to `/helix` the only change required ? If so I will edit my project in the next days.

**Comment by RaphaelAddile** [comment]
@Em-Ant The root URL of the API changing isn't the only difference. I'm still new, so someone more experienced should probably have a look at the [new API](https://dev.twitch.tv/docs/api/reference). But I think for the `/users/` and `/streams/` routes there should be nearly no changes necessary. The `/channels/` route on the other hand is completely gone in the new API. But you can get the interesting data from the `/streams/` route anyways.

Additionally the `/streams` route now returns a `game_id` instead of the name of the game, so if people should be able to display the game name in their projects we should probably implement the `/games` route to allow them to get the name from the id.

**Comment by Em-Ant** [comment]
At the moment my proxy passes everything that in the url  comes after `[project-url]/twitch-api` to `https://api.twitch.tv/kraken`. It will not work as is with the new api. 

I'll update it so that if you hit the url `[glitch-url]/twitch-api` or `[project-url]/kraken` it use the old api, if we hit `[project-url]/helix` it uses the new api. What do you think ?

**Comment by mstellaluna** [comment]
@erictleung Sorry for the delayed answer. Yes, I'm suggesting something new :)

**Comment by erictleung** [comment]
@Em-Ant 

> I'll update it so that if you hit the url [glitch-url]/twitch-api or [project-url]/kraken it use the old api, if we hit [project-url]/helix it uses the new api. What do you think ?

That appears to be a reasonable update. I haven't really looked into the new API much so we'd have to test it out. But for now, that seems like a sensible update.

@mstellaluna awesome, just checking :) If we end up not replacing it with your Google Maps API contact page, that might be a nice addition to the projects to work on.

**Comment by QuincyLarson** [comment]
@Em-Ant That sounds good to me. Please let us know once you've made the change and verified that it still works!

**Comment by QuincyLarson** [comment]
@Em-Ant Did you ever get a chance to update this?

**Comment by Em-Ant** [comment]
No sorry. It's not so easy to make it work for both the old and new
projects.

Il dom 3 giu 2018, 16:37 Quincy Larson <notifications@github.com> ha
scritto:

**Comment by thecodingaviator** [comment]
@QuincyLarson / @ezioda004 / @raisedadead I think this issue should take high priority now since we have just a month before the API is deprecated and holiday season is starting so everyone would not be free at all times

**Comment by QuincyLarson** [comment]
@Em-Ant It looks like this will be deprecated in just a couple weeks. Could you help update our Glitch project?

**Comment by Em-Ant** [comment]
@QuincyLarson I'm having a look at it. I'll try to migrate to the new api before next year. In the meantime the service has a cache db and a static list of users (the ones in the example exercise). It can keep working in 'emergency' mode indefinitely serving a limited number of twitch users data. 

Also it seems that somebody is using it outside the scope of freeCodeCamp. I have blacklisted the domain, but we need to be careful. I'll let you know.

**Comment by Em-Ant** [comment]
I have a working api locally on my computer. @QuincyLarson / @raisedadead  do you want me to deploy it now ? or should I wait until the end of December ?
The new API will be not backward compatible, but I am serving a static data snapshot at the old enpoint `/wind-bow.glitch.me/twitch-api`, for the 8 users listed in the exercise description.
The new API endpoint will be `/wind-bow.glitch.me/helix`.
Also, the api now is in my glitch account. I think We should transfer the ownership to freeCodeCamp (camperbot ?). Let me know.

**Comment by Em-Ant** [comment]
the new api can be tested here https://em-ant-twitch-api.glitch.me/ . my old twitch project still works with the served static data. I will deploy the code to wind-bow before new year. We also need to update the challenge description [here](https://learn.freecodecamp.org/coding-interview-prep/take-home-projects/use-the-twitch-json-api) and update the forum post [here](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-how-to-use-the-twitchtv-api/19541) I will submit a PR with the text changes. Can anybody update the forum article ?

**Comment by QuincyLarson** [comment]
@Em-Ant which would you recommend? If you want me to update the post, I can do so - just tell me what update you'd like to make to it.

**Comment by Em-Ant** [comment]
I updated the PR removing the link to the forum post. I think that post is not relevant anymore for the new api.

**Comment by QuincyLarson** [comment]
@Em-Ant Awesome! Thanks for fixing this and for updating the challenge! It always feels good to close one of these issues that's nearly a year old!

I've updated the old Forum post we were linking to with your updated instructions. I agree, we shouldn't link to that post anymore. But now if people end up on that post they'll have your new instructions.

As always, thanks for your help, and thanks to everyone on this thread who helped us arrive at this solution!

**Comment by Em-Ant** [comment]
the new version on the api is deployed on wind-bow.glitch.me. 
@QuincyLarson it's always a pleasure to help.
