### ISSUE TITLE
Can't login using github account

### ISSUE THREAD

**Issue by prakhar897** [freeCodeCamp/freeCodeCamp#16438]
#### Issue Description

I tried to login using github but it displays an alert box opens instead.

#### Browser Information

* Browser Name, Version:  Google Chrome
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```
#### Screenshot

![untitled](https://user-images.githubusercontent.com/25222802/34648798-35ccb756-f3c7-11e7-9dde-e5394db33a77.jpeg)

**Comment by raisedadead** [comment]
Yes, we have disabled GitHub for new accounts, only old accounts are allowed sign in via this. 

Are you a returning user? And still seeing this?

**Comment by LukeB2016** [comment]
how do we get our progress back i also had signed up using github but can't log back into my profile using github now this is stressful i was on the javascript track how can we fix this ??!?!

**Comment by raisedadead** [comment]
Hi @LukeB2016 

Please do not panic. I can see your profile is safe, https://www.freecodecamp.org/LukeB2016
Since you joined Dec 30' 2017. You should have signed up using an email, and then linked your profile to GitHub.

You should use the same email on the sign in page, and the password which you created.

In case you have forgotten the password, please use the forget password option on the email sign in page.

**Comment by okOvOko** [comment]
![image](https://user-images.githubusercontent.com/16106823/40737731-454cc72c-644a-11e8-9389-57ab72a0c74e.png)
I can't log in using gitHub.. and I can't do it using e-mail... Help me, please. I want my profile back :(

**Comment by Mohab17** [comment]
Hi @raisedadead ,

I've got the same problem and I tried to sing in with my email but now It shows me just totally like my account is new! and all my study there is gone because I use to sing in just using my Github.
I hope if you can please help me with Fixing it.

**Comment by nblank** [comment]
I am also having the same problem. I have lost all my progress as I used to sign in with Github and the option is no longer there.

**Comment by QuincyLarson** [comment]
@Mohab17 @nblank Could you email me at team@freecodecamp.org with your email address and GitHub usernames? I will fix this for you manually in our database, and in doing so can get a better idea of the problem.

**Comment by nblank** [comment]
@QuincyLarson I emailed my info to that email address about 10 minutes ago. I appreciate the assistance!

**Comment by Mohab17** [comment]
@QuincyLarson I also send my email address and username to you. thanks for your efforts!

**Comment by okOvOko** [comment]
@QuincyLarson Could you help me too, please? I have the same problem :( I've emailed you at team@freecodecamp.org  with my email address and GitHub username. Thank you~

**Comment by raisedadead** [comment]
We just dropped a fix for the this issue, can you please try again and let us know.

**Comment by okOvOko** [comment]
@QuincyLarson @raisedadead
It works!
Thank you <3

**Comment by practicaltexan** [comment]
@QuincyLarson I also sent my email address and username to you as I have been unable to login for a while.
