### ISSUE TITLE
[beta] Bar Chart Codepen has misalignment

### ISSUE THREAD

**Issue by tbushman** [freeCodeCamp/freeCodeCamp#16436]
#### Issue Description

The Bar Chart Codepen has a few `<rect>` elements that do not align with relative axis ticks. In order to accommodate the misalignment, we have added 5.5px to the alignment tests at https://github.com/freeCodeCamp/testable-projects-fcc. This may cause aligned student projects to fail the y-axis alignment test.

#### Browser Information

* Browser Name, Version: all
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment]
Hi @tbushman thanks a lot for improving on the tests there, could you list out which are the affected projects, and what needed to be done in terms of contributions in this repo?

We should be able to tag the same accordingly for contributors to help fix them

Happy contributing.

**Comment by tbushman** [comment]
@raisedadead thanks. It's only the Bar Chart Codepen project, so it won't affect this repo ... sorry to bother. It looks like a problem with the chart margins.

**Comment by raisedadead** [comment]
Awesome... thanks for the update. So we can close this then?

**Comment by Knochenmark** [comment]
@raisedadead i am pretty sure you can close this. I think the original bug in the test suite was raised by me and @tbushman fixed this already. For reference https://github.com/freeCodeCamp/testable-projects-fcc/issues/273

**Comment by tbushman** [comment]
Hey, sorry. The Bar Chart Codepen still has misalignment. But it's code is not part of this repo. I'll need to contact the author or someone with access to it.

**Comment by Knochenmark** [comment]
@tbushman So the issue i linked is unrelated? Sorry, my bad then.

**Comment by tbushman** [comment]
@knochenmark It is related. The Bar Chart test now accommodates the official fCC Bar Chart Codepen misalignment with an 11px leeway. That code is not, however, part of this repo. I'll close this.
