### ISSUE TITLE
[Beta] Freecodecamp progress stuck after submitting a project

### ISSUE THREAD

**Issue by Asjas** [freeCodeCamp/freeCodeCamp#16433]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/applied-responsive-web-design-projects/build-a-survey-form

#### Issue Description

This issue appeared right after I submitted a codepen link to a project. After I pasted the link and pressed the `I completed this challenge` button it froze.

The project I submitted was the `Build a tribute page` but I submitted it on the `Build a survey form` challenge.

Now every time I sign-out and log back in it gets stuck on that same challenge again. It isn't allowing me to progress or click on any of the map headings. It keeps forcing me to stay on this challenge.

The only way I can move on to other challenges is by signing out. It almost seems like something bugged out on my account.

Tested on latest Chrome and FF.

I'm attaching two screenshots of what is appearing in the console.

#### Browser Information

* Browser Name, Version: Firefox, 57.0.4
* Operating System: Windows 10 Home
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![fcc](https://user-images.githubusercontent.com/3828967/34647511-656039aa-f38d-11e7-879e-99108e8c6f5c.jpg)

![fcc-2](https://user-images.githubusercontent.com/3828967/34647512-69b06278-f38d-11e7-973b-f8f7f51f1c3a.jpg)

**Comment by raisedadead** [comment]
Thanks @Asjas 
For anyone looking to contribute. We need assistance in analysis of this issue.

**Comment by LiteSoul** [comment]
The issue is quite easy to replicate, just go to any Beta challenge, put some code so it PASSES the test, and you will see you get stuck. Unable to go to next challenge or drop-down the menus

**Comment by raisedadead** [comment]
Hi @LiteSoul yes, thanks we need help in finding the root cause of the issue.

**Comment by Bouncey** [comment]
@Asjas @LiteSoul Can one of you confirm this is still an issue, I think this may have been fixed

**Comment by Asjas** [comment]
@Bouncey Thank you. :tada:

I can confirm that it is fixed. The map is no longer stuck and I can more around between challenges when I'm logged in.

**Comment by raisedadead** [comment]
Thanks @Asjas

**Comment by LiteSoul** [comment]
For me the problem still persists, even after logging out or clearing cache. This is the error now:
![errepic](https://user-images.githubusercontent.com/22918889/36394070-4978a5e4-1591-11e8-97e2-feb9ec242c2c.png)

**Comment by LiteSoul** [comment]
Yes! It's working now!

**Comment by LiteSoul** [comment]
Ok guys, I'm sorry to say that it's not fixed... I'm still stuck.
It worked a few minutes (on a 3Mbps connection), after I cleared the cache and logged in again.
Then turned off my laptop, when to another place (10Mbps) and the problem appeared again.
I don't have any weird chrome extension or anything, and I don't want to clear chrome cache every time... this is the error:

![errepic](https://user-images.githubusercontent.com/22918889/36400309-f186d856-15ae-11e8-8215-88ea86f97044.png)
