### ISSUE TITLE
Progress of freeCodeCamp challenges not matching/updating

### ISSUE THREAD

**Issue by antofon** [freeCodeCamp/freeCodeCamp#16440]
#### Issue Description

The number of challenges completed do not match (see screenshots, center and top right of screen). The "98" completed and its corresponding info (i.e. streak, history of completed challenges) refers to an older account linked to my GitHub. However, the "258" completed in the top right refers to a separate, more actively used account.

I tested whether the "258" number changes by completing a challenge and it does (at the time 259). The "98" number remains the same and its info below. Not sure if this will eventually impact my ability to earn certificates, but this is the current issue.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 63.0.3239.132 (Official Build) (64-bit)
* Operating System: Windows
* Mobile, Desktop, or Tablet: All devices 

```js



```
#### Screenshots

![login_info](https://user-images.githubusercontent.com/10703498/34653343-7f14af54-f39f-11e7-966f-563e5830e4a1.jpg)
![login_info2](https://user-images.githubusercontent.com/10703498/34653344-7f2f1ccc-f39f-11e7-9d88-f85c6b95e269.jpg)

**Comment by systimotic** [comment]
That's really weird, I've never seen this before. @QuincyLarson Any ideas?

**Comment by QuincyLarson** [comment]
@systimotic This is the first time I've ever seen this. 

@antofon I was able to fix it by deleting a duplicate record in the database.

**Comment by antofon** [comment]
Great, thank you @QuincyLarson. This screenshot confirms the fix:

![freecodecamp_fixed_profile](https://user-images.githubusercontent.com/10703498/34750703-692e6bf2-f55d-11e7-8b12-6a03130c74c3.PNG)
