### ISSUE TITLE
Applied Visual Design: Create Visual Balance Using the text-align Property. Missing crucial infos 

### ISSUE THREAD

**Issue by DGC75** [freeCodeCamp/freeCodeCamp#16446]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/applied-visual-design/create-visual-balance-using-the-textalign-property

#### Issue Description

On the challenge linked above you have to center the h4 tag with the text-align property set to “center”, but the FCC doesn’t explicitly say what are the possible values.
#### Browser Information

* Browser Name, Version: 
Firefox Developer Edition 58.0b14 (64 bit)
* Operating System: 
macOS Sierra 10.12.6 (16G1114)
* Mobile, Desktop, or Tablet: 
Desktop

#### Screenshot

![schermata 2018-01-08 alle 22 46 36](https://user-images.githubusercontent.com/26718775/34693989-d28e2b02-f4c5-11e7-8511-1cf8a8e89899.png)

**Comment by vkWeb** [comment]
@DGC75 Yes - Should we explain all the basic values i.e left, right, center & justify? What changes would you like to see?

**Comment by DGC75** [comment]
I think it would be beneficial for everyone to know what are the possible values (you've mentioned them) and what they do to the text. (Actually FCC explains only the justify value)
Thanks for the response!

**Comment by vkWeb** [comment]
@raisedadead, @systimotic, Your suggestion on this?

**Comment by christianbender** [comment]
@vkWeb @all 
I want like fix this problem. Where can I found the text of the section called "Applied Visual Design: Create Visual Balance Using the text-align Property" ?
I wanted add a detailed describition of the text-align property.

**Comment by DGC75** [comment]
freeCodeCamp/seed/challenges/01-responsive-web-design/applied-visual-design.json

**Comment by christianbender** [comment]
@DGC75  thanks for response

**Comment by christianbender** [comment]
@DGC75  @all 
How can I test my changes? I cloned the repository and download it on my own machine.

**Comment by raisedadead** [comment]
@christianbender 

You should follow the instructions in [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md)

If you face issues, is setup we are happy to help in our [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors)

Happy contributing!
