### ISSUE TITLE
Make freeCodeCamp Logo look better on small viewport

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16452]
Currently when the viewport is narrow on beta.freecodecamp.org, the freeCodeCamp logo will be replaced with just our "bonfire function call" symbol. This symbol looks larger than it should be, and it needs to be vertically centered.

![applied_accessibility__improve_chart_accessibility_with_the_figure_element___freecodecamp](https://user-images.githubusercontent.com/985197/34743826-c8913136-f550-11e7-84d9-7f1d7d150c16.png)

**Comment by AustinTice** [comment]
Quincy, I have this code ready. Will be opening a PR soon!
