### ISSUE TITLE
Change "N/A" to blank in map time estimates

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16454]
Instead of showing "N/A" in the map for the interview prep and open source for good sections, we just shouldn't show a time estimate - it should be blank.

![project_euler_problems__problem_7__10001st_prime___freecodecamp](https://user-images.githubusercontent.com/985197/34744886-4fa2b28c-f554-11e7-974b-02d3d5312db5.png)

**Comment by vkWeb** [comment]
@QuincyLarson I'll like to implement this change. My local development is down right now 😞.
It's showing that some node modules are missing, I've already reinstalled it several times. I'll do recloning of my fork and will fix it soon. So, I'll submit a PR within few days. (If it's urgent then someone else should take this.)

**Comment by r1chard5mith** [comment]
I know how to do this.
