### ISSUE TITLE
[Beta] Possibly unfit test case in regular expression challenge

### ISSUE THREAD

**Issue by kgalang** [freeCodeCamp/freeCodeCamp#16450]
#### Challenge Name
Regular Expressions: Specify Upper and Lower Number of Matches

https://beta.freecodecamp.org/en/challenges/regular-expressions/specify-upper-and-lower-number-of-matches

#### Issue Description

From the instructions and previous lessons, the challenge is asking us to create the regex, "/oh{3,6}/i". This matches all tests except for the final one. The final test of this challenge says that our regular expression should not match "Ohhhhhhh no" (7 'h's). However, I believe this test case is misplaced as the regular expression with the quantity specifiers should match this but with only up to six 'h's. So the match, "Ohhhhhh", should still occur.  In order for us to pass the test case with one too many 'h's, we must use a positive look ahead to show that there is white space after our last 'h'. This is something that hasn't been introduced yet in the regular expression track.

#### Your Code

```js
let ohStr = "Ohhh no";
let ohRegex = /oh{3,6}/i; // Change this line
let result = ohRegex.test(ohStr);


```
#### Screenshot

<img width="724" alt="screen shot 2018-01-09 at 9 50 31 am" src="https://user-images.githubusercontent.com/18174574/34726629-a10a18ea-f522-11e7-8d8a-bf3a65cf9707.png">
<img width="721" alt="screen shot 2018-01-09 at 9 50 40 am" src="https://user-images.githubusercontent.com/18174574/34726634-a6e4fe4c-f522-11e7-87f2-1dde9d30f949.png">

**Comment by erictleung** [comment]
@kgalang I believe I designed these challenge and I think I intended for the regex to be written with the addition of "no" in it so if you add that in, then it should work. Thus, the challenge should be sufficient as is. Let me know if that makes sense.

**Comment by kgalang** [comment]
@erictleung that makes sense. Thanks for the quick follow up!
