### ISSUE TITLE
How to Install???

### ISSUE THREAD

**Issue by Bahodir94** [freeCodeCamp/freeCodeCamp#16461]
Hello, I want to install FreeCodeCamp. But I don't know How to install.
Please help me to install FreeCodeCamp to my Server.
My server is Ubuntu 16,04

**Comment by raisedadead** [comment]
Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
