### ISSUE TITLE
I search the content for #16446

### ISSUE THREAD

**Issue by christianbender** [freeCodeCamp/freeCodeCamp#16462]
I want fix the issue #16446 . But where can I found the content in this repo?
It is for [this site](https://beta.freecodecamp.org/en/challenges/applied-visual-design/create-visual-balance-using-the-textalign-property)

Where can I found the following content?
>This section of the curriculum focuses on Applied Visual Design. The first group of challenges build on the given card layout to show a number of core principles. Text is often a large part of web content. CSS has several options for how to align it with the text-align property. The justify property causes all lines of text except the last line to meet the left and right edges of the line box.

**Comment by raisedadead** [comment]
Hi please continue on the issue thread instead of creating a fresh issue. We are in process of updating or docs, but most of the guidelines are already outlined in [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md)
