### ISSUE TITLE
Passing to next step without error

### ISSUE THREAD

**Issue by blaisck** [freeCodeCamp/freeCodeCamp#16470]
#### Challenge Name

https://www.freecodecamp.org/challenges/target-html-elements-with-selectors-using-jquery

#### Issue Description

I placed the `$("button").addClass("animated bounce");` outside `$(document).ready(function() {});` and then I __Ctrl+Enter__ it, and its not considered wrong.  

#### Browser Information

* Browser Name, Version:  Google Chrome, 63.0.3239.132 (Official Build) (64-bit)
* Operating System: Windows 10 Pro 64-bit
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code

```js

<script>
  $(document).ready(function() {

  });
  
  $("button").addClass("animated bounce");
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target bounce" id="target1">#target1</button>
        <button class="btn btn-default target bounce" id="target2">#target2</button>
        <button class="btn btn-default target bounce" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target bounce" id="target4">#target4</button>
        <button class="btn btn-default target bounce" id="target5">#target5</button>
        <button class="btn btn-default target bounce" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```
#### Screenshot

![fcc](https://user-images.githubusercontent.com/1886175/34822947-309de2d2-f6fb-11e7-9a33-c741a4fa3581.png)

**Comment by rohan598** [comment]
It is not considered wrong because technically it is not wrong. However, it is not safe to do so and in some cases (like, a HTML document with large number of elements) it may produce an error. It is better practice to include all your jQuery code within  $(document).ready() 
Refer to this link for clarity :
https://learn.jquery.com/using-jquery-core/document-ready/

**Comment by CthuKyaw** [comment]
Hi @raalejandre, I am first timer. Can I work on this issue. If so, let me clear with the issue.
Did you mean the test should also check whether the required script is written inside `document.ready(function(){})`?

**Comment by blaisck** [comment]
@CthuKyaw : I hope like that. Because we came to freeCodeCamp to practice, so like @rohan598 said, **It is better practice to include all your jQuery code within** `$(document).ready()`

**Comment by ninadingole** [comment]
@raisedadead can I work on this issue ?

**Comment by raisedadead** [comment]
@ninadingole Sure! look forward to a PR.

Happy contributing!

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
