### ISSUE TITLE
Responsive Web Design Principles: Create a Media Query - Test won't pass

### ISSUE THREAD

**Issue by manikandanelangovan** [freeCodeCamp/freeCodeCamp#16474]
#### Challenge Name
Responsive Web Design Principles: Create a Media Query
https://beta.freecodecamp.org/en/challenges/responsive-web-design-principles/create-a-media-query

#### Issue Description
Even though the correct answer was submitted it shows the error message, the output of the code is changed properly in the preview panel but the instructions panel is still showing the error message as "Declare a @media query for devices with a height less than or equal to 800px".

#### Browser Information

* Browser Name, Version:  Google Chrome, Version 65.0.3318.0 (Official Build) canary (64-bit)
* Operating System: MacOS High Sierra
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

@media (max-width: 800px) {        
     p {
       font-size: 10px; 
    }
  }

```
#### Screenshot

<img width="1280" alt="issue_screenshot" src="https://user-images.githubusercontent.com/31500057/34857614-b7ac0940-f771-11e7-9ea3-2725d8c3e725.png">

**Comment by vkWeb** [comment]
@manikandanelangovan Confirmed.
@raisedadead This is strange. If the first test passed then It's obvious that the second test should pass too(In my opinion). As the font-size will be 10px on devices with less than or equal to 800px viewport only when a media-query is declared.

**Comment by raisedadead** [comment]
We need help in analysis of this issue.

**Comment by huyenltnguyen** [comment]
@manikandanelangovan The tests work fine. The challenge asks you to add a media query when the device's **height** is <= 800px. What you did was setting rule for max-**width**. 😄

**Comment by ahmadabdolsaheb** [comment]
@raisedadead @vkWeb @manikandanelangovan 
the correct answer is:
`@media (max-height: 800px) {        
     p {
       font-size: 10px; 
    }
  }`
the tests are fine but the description could be improved by adding an example of max-**height** to make it less tricky.

**Comment by raisedadead** [comment]
@ahmadabdolsaheb sure.

**Comment by ahmadabdolsaheb** [comment]
@raisedadead @huyenltnguyen @vkWeb, made a PR yesterday. not sure if it gives a notification to the moderators or not :) let's :ship: it

**Comment by 43noodles** [comment]
the same issue for me....

even I entered correct answer, the test still fail...

**Comment by raisedadead** [comment]
Please report a fresh issue with the details on the tracker.
