### ISSUE TITLE
Clarify instructions to raise a PR to Base Repo instead of Local Fork.

### ISSUE THREAD

**Issue by saurishkar** [freeCodeCamp/freeCodeCamp#16477]
#### Target File
**CONTRIBUTING.md**

#### Issue Description
There is a scenario where I raise a PR to my local copy of FreeCodeCamp instead of the Base Repository. 
If i merge my commits in the PR (since it is my local copy), my local fork of FCC gets the changes while the Base repository still remains unchanged.

**This can seem confusing (especially to First Timers), as it might seem to you that even though i made my changes, my changes are not getting updated in the Base Repository.**   

#### What needs to be updated ?

The updated instructions should be along the lines of : 

> Make sure that your **Base Fork** is set to **freeCodeCamp/freeCodeCamp** when raising a Pull Request

#### Screenshot

![Keeping the Base Repo to freeCodeCamp/freeCodeCamp](https://user-images.githubusercontent.com/19742306/34858132-81b21a3e-f774-11e7-8dd6-fe48a5025da4.png)

#### Additional Instructions :

You can refer the official Github Documentation for raising a PR to a forked repository here : 
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

#### What's the Fix if i already encountered this issue ?

Thanks to @raisedadead , you can follow the instructions below to rewind the changes : 

> For fixing the head if accidental commits are made to the staging branch of ones own fork via pull-request, etc.:

> On your local machine
> 
> git checkout staging
> git fetch upstream staging
> git reset --hard upstream/staging
> git push --force origin staging
> 
> where your remotes [git remote -v] are:
> 
> origin	https://github.com/USERNAME/freeCodeCamp.git (fetch)
> origin	https://github.com/USERNAME/freeCodeCamp.git (push)
> upstream	https://github.com/freeCodeCamp/freeCodeCamp.git (fetch)
> upstream	https://github.com/freeCodeCamp/freeCodeCamp.git (push)

**Comment by SavaVuckovic** [comment]
Hey, I am just learning about contributing to open source and came across this.
I think it's a valid issue, and would like to resolve it as my first contribution if it hasn't been resolved yet.
I have a feeling it will help other first timers like myself.

**Comment by raisedadead** [comment]
@SavaVuckovic sure, please go ahead.

**Comment by SavaVuckovic** [comment]
@raisedadead Thank you, I am going to submit a PR tomorrow.

**Comment by SavaVuckovic** [comment]
So I was about to submit a PR, and I was wondering if I could attach an image for reference?
My solution would look like [this](https://www.dropbox.com/s/hmwoh342agix5rv/fixone.png?dl=0) 
Otherwise my solution would look like [this](https://www.dropbox.com/s/4o2xadxqta6zx4s/fixtwo.png?dl=0)

**Comment by raisedadead** [comment]
You should open a PR, and if necessary drag drop images right in the text area of the PR description (GitHub auto uploads these)

**Comment by SavaVuckovic** [comment]
@raisedadead Thank you for your help :)
