### ISSUE TITLE
[beta] Test fails in Perform New Updates on a Document Using model.findOneAndUpdate()

### ISSUE THREAD

**Issue by psitronic** [freeCodeCamp/freeCodeCamp#16478]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/mongodb-and-mongoose/perform-new-updates-on-a-document-using-modelfindoneandupdate

#### Issue Description

The test does not pass. The glitch logs:
```/app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:123
11:38 AM
    process.nextTick(function() { throw err; });
11:38 AM
                                  ^
11:38 AM
11:38 AM
ReferenceError: data is not defined
11:38 AM
Jump to
at /app/server.js:197:11
```

Fix: in ```server.js``` line 197 move the statement
```
        if(!data) {
          console.log('Missing `done()` argument');
          return next({message: 'Missing callback argument'});
        }
```
in ```try {}``` after ```if(err) { return next(err) }```

#### Browser Information

* Browser Name, Version: Chrome, 62.0.3202.94
* Operating System: Win 10
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code

```js



```

**Comment by TylerDelRosario** [comment]
Could I take this issue?

**Comment by raisedadead** [comment]
@TylerDelRosario sure.

**Comment by TylerDelRosario** [comment]
I'm sorry if this is an obvious question, but is there a way to start up and test a local version of freecodecamp?

**Comment by raisedadead** [comment]
@TylerDelRosario yes, thats a perfectly valid question, its documented in our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md)

If you are just getting started we hangout in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), you can ask questions there too.

**Comment by Brybro** [comment]
@raisedadead - Is this still open?  If so, I can resolve it.

**Comment by Bouncey** [comment]
@raisedadead @BerkeleyTrue, how do we update the boiler plate? Who owns the boilerplate projects on gomix?

**Comment by raisedadead** [comment]
I believe @Em-Ant should have the access to these, or @QuincyLarson

**Comment by QuincyLarson** [comment]
@raisedadead I have access to these, but @Em-Ant has the deepest understanding of them. I'll message him and see if he can fix this.

**Comment by Em-Ant** [comment]
Hi guus. The projects are owned by camperbot github account, so you should be able to access them. Anyway I'll have a look this evening.

**Comment by raisedadead** [comment]
Thanks for the update @Em-Ant !

**Comment by QuincyLarson** [comment]
@Em-Ant Awesome! Thanks for looking at these. Please keep us posted :)

**Comment by Em-Ant** [comment]
Hi @psitronic , can I see your code or your glitch project link ? I just tested it in beta.freecodecamp with the original project that I used to develop these challenges, and it worked. If you want I can share the link here or in gitter to compare the solutions.

**Comment by psitronic** [comment]
Hi @Em-Ant! Sorry I was in a hospital for a few day and could not reply. The link to my code  https://glitch.com/edit/#!/fixed-shampoo?path=myApp.js:1:0 .

I still see in server.js the same problem with the lines displacement (in two places):
1) 
`var update = require('./myApp.js').findAndUpdate;
router.post('/find-one-update', function(req, res, next) {
  var t = setTimeout(() => { next({message: 'timeout'}) }, timeout);
  var p = new Person(req.body);
  p.save(function(err, pers) {
    if(err) { return next(err) }
    if(!data) {
      console.log('Missing `done()` argument');
      return next({message: 'Missing callback argument'});
    }
    try {
      update(pers.name, function(err, data) {
        clearTimeout(t);
        if(err) { return next(err) }
        res.json(data);
        p.remove();
      });
    } catch (e) {
      console.log(e);
      return next(e);
    }
  });
});
`

2)
`var chain = require('./myApp.js').queryChain;
router.post('/query-tools', function(req, res, next) {
  var t = setTimeout(() => { next({message: 'timeout'}) }, timeout);
  Person.remove({}, function(err) {
    if(err) if(err) { return next(err) }
    Person.create(req.body, function(err, pers) {
      if(err) { return next(err) }
      if(!data) {
        console.log('Missing `done()` argument');
        return next({message: 'Missing callback argument'});
      }
      try {
        chain(function(err, data) {
          clearTimeout(t);
          if(err) { return next(err) }
          res.json(data);
        });
      } catch (e) {
        console.log(e);
        return next(e);
      }
    });
  })
});`

**Comment by Em-Ant** [comment]
@raisedadead (or other reviewers) the PR is https://github.com/freeCodeCamp/boilerplate-mongomongoose/pull/2
