### ISSUE TITLE
Give a Background Color to a Div Element - second test won't pass even though the div's background is silver

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#16473]
#### Challenge Name
Give a Background Color to a Div Element

#### Issue Description

If you give the div the wrong class name but the background color is correct, the second test ("Your div element should have a silver background.") should pass, but it doesn't.

#### Your Code

```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
  
  .wrong-class-name {
    background-color: silver;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<div class="wrong-class-name">
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
</div>

<form action="/submit-cat-photo">
  <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
  <label><input type="checkbox" name="personality" checked> Loving</label>
  <label><input type="checkbox" name="personality"> Lazy</label>
  <label><input type="checkbox" name="personality"> Energetic</label>
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>



```
#### Screenshot

![image](https://user-images.githubusercontent.com/17902987/34856066-20bfa304-f77e-11e7-9066-3fb3f88d2d9c.png)

**Comment by blaisck** [comment]
Based on tutorial, you should name your class to `silver-background` so it won't show an error

**Comment by rohan598** [comment]
Yes, the test checks if the class name is "silver-background" and then checks if it changes the background colour to silver. If you change the name of the class, it will flag an error.

**Comment by kevcomedia** [comment]
The tests are testing two things that are independent of each other. If the div is colored silver, the second test should pass regardless of whether or not the right class name is used.

**Comment by rohan598** [comment]
Your argument is correct. But on testing with various class names and colour combination, I believe that the test is checking both the things together and not as separate entities, which should be rectified.

**Comment by rohan598** [comment]
Just follow these steps to see for yourself why this error is occurring.

1) Open this link in google chrome :
 https://www.freecodecamp.org/challenges/give-a-background-color-to-a-div-element
2) Open developper tools
3) Look for a 'script tag' from the bottom. The one you should be looking for is just bellow 
"<div id="ask-for-help-modal" tabindex="-1" class="modal>"
4) Open the script and check "common.tests " 

Observation:-
1) It checks the class name to be equal to 'silver-background'
2) Then, it checks the property 'background-color' of 'silver-background' to be 'rgb(192,192,192)' which is same as 'silver'

**Comment by jpdail01** [comment]
I'd like to take a shot at this one
