### ISSUE TITLE
&AMP; et al; Not valid for tests. Please advise users.

### ISSUE THREAD

**Issue by leftfieldhero** [FreeCodeCamp/freecodecamp#1647]
Challenge http://www.freecodecamp.com/challenges/bonfire-convert-html-entities has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

The capital letter versions of HTML entities are not valid for the tests. Perhaps you could or them through.  Also maybe you could remind users to include the ";" at the end of their entities in the description. Thanks for all your teams great work! I'm loving freecodecamp.com.

**Comment by ahstro** [comment]
I fixed the allowed capitalization. The [W3 HTML Entities link](http://dev.w3.org/html5/html-author/charref) shows every entity with a semicolon `;` at the end, so I don't think it's necessary to add a reminder.
