### ISSUE TITLE
Disable an element using jQuery's bug

### ISSUE THREAD

**Issue by blaisck** [freeCodeCamp/freeCodeCamp#16471]
#### Challenge Name

https://www.freecodecamp.org/challenges/disable-an-element-using-jquery

#### Issue Description

I type `$("#target1").prop("disabled", "true");` instead of `$("#target1").prop("disabled", true);` and it's still work, I think it should be an error.

#### Browser Information

* Browser Name, Version: Google Chrome, 63.0.3239.132 (Official Build) (64-bit)
* Operating System: Microsoft Windows 10 Pro 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

<script>
  $(document).ready(function() {
    $("#target1").prop("disabled", "true");

  });
</script>

<!-- Only change code above this line. -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```
#### Screenshot

![fcc-2](https://user-images.githubusercontent.com/1886175/34854148-701f5e12-f76a-11e7-84dd-1f541ec64ba1.png)

**Comment by raisedadead** [comment]
> I type `$("#target1").prop("disabled", "true");` instead of `$("#target1").prop("disabled", true);` 
and it's still work, I think it should be an error.

Isn't that expected of the tests? What is the exact difference you are looking for?

**Comment by blaisck** [comment]
The difference is in value `true`, I'm using double quotation mark and in the tutorial not use it.
If it's expected, then is `"true"` and `true` is same?

**Comment by raisedadead** [comment]
Hi @blaisck thanks for the additional clarification, I admit I missed the quotes :sweat_smile: !

Well, theoretically the incorrect code is actually correct, because in JavaScript a string values is considered truthy, which means you could use `"false"` and it would still pass! Or any string `"some string"`.

So, I agree we should update the tests to make this fail when boolean `true` is not used, just to encourage good practice.

**Comment by saurishkar** [comment]
Hi @raisedadead, can i take this one up if nobody is working on it ?

**Comment by raisedadead** [comment]
Yes, sure. Happy contributing.

**Comment by rdbaron** [comment]
Hmm... the result of this change is that if you do use "true", the button becomes disabled in the sandbox, but the test fails with the error "Disable your target1 button."

Confusing when you can see that your button is disabled.
