### ISSUE TITLE
[Beta] Test-suite Rows Should have Adequate Spacing

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16484]
### Issue Description
@raisedadead 
There should be adequate spacing on the test-suite rows for better readability. 

**Before:**
![before_spacing](https://user-images.githubusercontent.com/26724128/34897785-e55cab0c-f815-11e7-824a-578cb42b0170.PNG)

**After:**
I've added `14px` top-margin between the rows. The code is ready. I'll raise a PR once the changes are finalized. 
![after_spacing](https://user-images.githubusercontent.com/26724128/34897789-e766347c-f815-11e7-8465-ee3fcf13eef4.PNG)

### Browser Information
* Browser Name, Version: Chrome & Firefox [Both latest stable release]
* Operating System: Windows 10 Pro 32 Bit
* Mobile, Desktop, or Tablet: Desktop

**Comment by raisedadead** [comment]
@vkWeb you can directly create PRs without issues, if you have a fix ready. I like your changes, lets fix them.

Thanks.

Happy contributing!

**Comment by vkWeb** [comment]
@raisedadead Okay, I'll keep that in mind 😄. PR is on the way.
