### ISSUE TITLE
[Beta] Navigation links are rendering Poorly

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16487]
### Issue Description
@raisedadead, @QuincyLarson The navigation links are not rendering properly. They look really weird. 

**Before:**
Please notice how `Preview` & `Donate` link looks. 
![before](https://user-images.githubusercontent.com/26724128/34899242-a8f0c010-f81d-11e7-9d6e-0346ec05ea1f.PNG)

**After:**
Decreasing the font-weight to `100` and increasing the font-size to `16px` makes them look much better. The code is ready. Once the changes are finalized I'll raise a PR for it. 
![after 2](https://user-images.githubusercontent.com/26724128/34899340-619f181e-f81e-11e7-90bf-97aa05cd83ae.PNG)

### Browser Information
* Browser Name, Version: Chrome & Firefox [Latest]
* Operating System: Windows Pro 32 bit.
* Mobile, Desktop, or Tablet: Desktop

**Comment by raisedadead** [comment]
This is a issue, limited to systems like Windows 10 32 bit, with possibly screens that are a bit older, the fonts antialiasing doesn't play well.

The same for instance on a retina or HD screen will look fairly crisp.

![image](https://user-images.githubusercontent.com/1884376/34903909-29ca591a-f861-11e7-85aa-f08458efe17f.png)

**Comment by raisedadead** [comment]
This how it looks without the bold

![image](https://user-images.githubusercontent.com/1884376/34903917-5d1e4452-f861-11e7-82e5-4cb83d72d136.png)

I think this also not too bad.

**Comment by raisedadead** [comment]
Hi @vkWeb I am going to have to close this, official we support only latest LTS Devices / OS / Browsers, combination.

I think its a minor inconvenience only to a fraction of users, but changing this is going to affect all. We regret the inconvenience,  however if such an issue is raised by more user we can think of fixing this.

Thanks for reporting

**Comment by vkWeb** [comment]
@raisedadead I'm heavily disappointed with this decision. As freeCodeCamp has a very huge community we should keep every small corner cases in mind.

**Comment by raisedadead** [comment]
Yes, we are keeping it in mind. Closing an issue is not ignoring it. Just waiting if we get more feedback will find an optimal fix.

**Comment by vkWeb** [comment]
@raisedadead Okay then.
