### ISSUE TITLE
Public Profile refresh to same screen

### ISSUE THREAD

**Issue by haleyelder** [freeCodeCamp/freeCodeCamp#16499]
#### Visiting Public Profile button in *settings panel* reverts back to page after trying to load
To see and track progress through beta, trying to view and click the "show me my public profile" button in the settings portion of my account reverts back to the page I currently on after attempting to load. Attempted this first late last week and still doing the same actions.

#### Browser Information

* Browser Name, Version: Chrome, v63
* Operating System: Windows10
* Mobile, Desktop, or Tablet: Desktop

**Comment by raisedadead** [comment]
Hi @haleyelder thanks for reporting. I cannot seem to reproduce this. 

Can you please confirm that this redirected you back once again to the settings page itself, or the challenge that you were on?

Also, were there any "Something is not ..." like error messages / notifications ?

If possible, and you can reproduce this can you visit the DevTools's Console Tab on your browser? On windows its launched using <kbd>F12</kbd>

**Comment by haleyelder** [comment]
It seems to be working now, for the few times I've tried it, it was not properly redirecting. Good to see it now!

**Comment by raisedadead** [comment]
Awesome! thanks for confirming... happy coding.!
