### ISSUE TITLE
Navigating to /map should show just the map - no expanded challenges

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16504]
Currently when navigating to https://beta.freecodecamp.org/map, the behavior is it will show your current challenge (or the first challenge if you aren't authenticated).

Since a lot of people link directly to the map, we should create a view that is just the fully-expanded map - no challenge.

The navbar would only have the "map" option in it, since there wouldn't be any other tabs on this page.

![applied_responsive_web_design_projects__build_a_tribute_page___freecodecamp](https://user-images.githubusercontent.com/985197/34958549-0e31afc6-f9f8-11e7-86d4-22dec2c9fb10.png)

**Comment by vkWeb** [comment]
@QuincyLarson I think this is will look awkward. We should think of another solution. Like for example, we should create a static learning map showing all the topics and certificates and all. What do you say?

**Comment by QuincyLarson** [comment]
@vkWeb We want a single source of truth for our map, so we wouldn't want this map to be different from the other ones.

**Comment by vkWeb** [comment]
@QuincyLarson No - Like when a camper clicks on the map, we shouldn't show him our original map. Instead, we should present a graphical overview of our curriculum (a better term is 'learning-path'). 

Something similar to this:
![map](https://user-images.githubusercontent.com/26724128/34961181-41332a14-fa64-11e7-8b9d-58462867d0ca.PNG)

**Comment by raisedadead** [comment]
This is not trivial, with the current client side implementation. Static view is also no longer possible.

**Comment by bennett-elder** [comment]
@vkWeb As long as it's centered better than in the screenshot, the proposed /map page would look very similar to the way freecodecamp.org/map looks now. Not too awkward....

Has there been a thread discussing the lack of visual cues in the new map as compared to the old one? The new map lacks the difference in font-size and the shaded background that helps distinguish the different levels of hierarchy from one another. It was actually the first thing I noticed about the beta.

**Comment by vkWeb** [comment]
@bennett-elder 
>As long as it's centered better than in the OP's screenshot, the proposed /map page would look...

Ya, If we center the map and make some UI adjustments, we can make it look better. 

>Has there been a thread discussing the lack of visual cues in the new map as compared to the old one?... 

Yes - I raised an issue about this a while ago that we should implement the map functionality as we have in production. In production's map, we have a 'collapse all' button, we can search challenges and the curriculum is divided into different sections and UI looks better there.

**Comment by bennett-elder** [comment]
I'm thinking something like this that uses font family, font size, font style, and a bit of graphics and color to make the map sections more distinct.

![quick-sidemap-a11y-mockup](https://user-images.githubusercontent.com/13042179/35569879-747206a6-059b-11e8-96f6-4d210ebc9347.png)

**Comment by vkWeb** [comment]
@bennett-elder The different levels of font-size looks great 👍 but I don't think we should apply different font-families to the different hierarchical levels of our map. Also, adding icons isn't a good idea.

**Comment by QuincyLarson** [comment]
@bennett-elder I agree with @vkWeb - we want to keep everything Lato. We could potentially change the font size to give the map a more clear hierarchy.

As for items, we'd want to use .svg files and have them be monochromatic, like the ones located on our landing page: 

![learn_to_code_and_help_nonprofits___freecodecamp](https://user-images.githubusercontent.com/985197/35763553-78e16070-0874-11e8-809c-4889a06ca5c7.png)

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
