### ISSUE TITLE
Add Lite-Brite project to Interview Takehome Project section

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16505]
A camper built this awesome Lite-Brite app (based on the 1980s toy). It would make a fine addition to our practice projects collection.

Here's the demo: https://codepen.io/freeCodeCamp/full/eyLYXE

We need to create agile use stories for this, then add it to the Take Home Interview Projects section. 

The challenge should be added to this directory: https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/08-coding-interview-questions-and-take-home-assignments/take-home-interview-projects.json

You can use this as the ID: 5a5d02bd919fcf9ca8cf46cb

**Comment by vkWeb** [comment]
@QuincyLarson I think I'll be able to do this. I just want to know how can I generate the challengeSeed? 

Can I give this an attempt?
