### ISSUE TITLE
After what happened in Hawaii, our "Nuclear Launch Detected" Starcraft reference isn't funny any more.

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16506]
This reference should be removed, out of respect for those affected by Saturday's tragic false alarm.

**Comment by reddysridhar53** [comment]
shall I pick this up?

**Comment by raisedadead** [comment]
Looks like there are open PRs for this already @reddysridhar53

**Comment by reddysridhar53** [comment]
thank you @raisedadead , will look for something else then.
