### ISSUE TITLE
[Security] JS challenges vulnerable to XSS

### ISSUE THREAD

**Issue by linkenneth** [freeCodeCamp/freeCodeCamp#16510]
Update: Details hidden, by mod.

**Comment by raisedadead** [comment]
Hi @linkenneth thanks for taking the time to report. 

However, can we please request you to follow [responsible disclosure](https://en.wikipedia.org/wiki/Responsible_disclosure) in future, you can always contact privately on such issues, on our chat / email (team@freecodecamp.org) / twitter DM etc.

I, am available at https://gitter.im/raisedadead if you want to leave any additional info.

We are discussing this report of yours and will get back.

**Comment by raisedadead** [comment]
Closed, to reduce public visibility, we are still on top of this.

**Comment by raisedadead** [comment]
We have fixed this in production. As a side effect, the sharing code URLs from profile, and viewing solutions from profiles is disabled.

This is side effect is temporary and is already handled more elegantly in the beta.

We will soon be adding a more clear warning notice on the profile page, for clarification.

> **_Note:_** none of the progress is lost, and all submitted solutions are safe in the user's profiles, except we are temporarily limiting the ability to view and share them.

**Comment by QuincyLarson** [comment]
@raisedadead Awesome - thanks for the update. Please @-mention me when you create that pull request, as I have had campers asking me about not being able to view solutions.

**Comment by raisedadead** [comment]
@QuincyLarson I have posted an announcement on the forum:

https://forum.freecodecamp.org/t/announcement-viewing-and-sharing-solutions-from-user-profiles-is-temporarily-disabled/169339

I'll let you know as soon as I have the update PR ready.

**Comment by QuincyLarson** [comment]
@raisedadead OK - thanks! We definitely want this on the challenge map ASAP since that's where 99% of campers will see it.

**Comment by raisedadead** [comment]
@QuincyLarson PR is up. I have added this to the profile page actually, I think this is where the users usually go to visit the solutions.

**Comment by raisedadead** [comment]
I am working on one more, so that campers can view the solution without needing to execute it.

**Comment by linkenneth** [comment]
Thanks for the fix! Verified that the issue as it was no longer works. Sorry again for the irresponsible disclosure, hope it didn't cause too much trouble.
