### ISSUE TITLE
Challenge "Override Class Declarations by Styling ID Attributes" accepts two h1's, the first unclosed.

### ISSUE THREAD

**Issue by cxw42** [freeCodeCamp/freeCodeCamp#16512]
#### Override Class Declarations by Styling ID Attributes
[Override Class Declarations by Styling ID Attributes](https://www.freecodecamp.org/challenges/override-class-declarations-by-styling-id-attributes)

#### Issue Description
The below challenge code should not be accepted, but is.  Apparently the unclosed `<h1>` isn't being correctly filtered out by [this test](https://github.com/freeCodeCamp/freeCodeCamp/blob/79c06ac6a55c1aeb3d9c95de4c784090f4ea689a/seed/challenges/01-responsive-web-design/basic-css.json#L2960).

#### Browser Information

* Browser Name, Version: Chrome 63.0.3239.132 (Official Build) (32-bit) (cohort: Stable)
* Operating System: Win 8.1 Enterprise x64
* Mobile, Desktop, or Tablet: Desktop

The same happens on Chrome 63.0.3248.84 x64 on Windows 10 (Desktop).

#### Your Code
```js

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
  #orange-text { color: orange; }
</style>
<h1 id="orange-text">
<h1 class="pink-text blue-text">Hello World!</h1>

```

`h1#orange-text` is not closed.  I'm not sure how that is handled in the freecodecamp codebase, but I did a quick check: Chrome 63.0.3239.132 transforms 

    <html><body><h1>Foo<h1>Bar</h1></body></html>

into

```html
<html><head></head><body><h1>Foo</h1><h1>Bar</h1><!--unclosed h1-->

</body></html>
```

#### Screenshot (marked up in pbrush --- sorry there are no hand-drawn circles ;) )
![screenshot](https://user-images.githubusercontent.com/10515894/34999852-d5bae6f8-fab0-11e7-94fb-f9ac8b0a2d94.png)

Credit to @bluecabbages for discovering this issue.

**Comment by huyenltnguyen** [comment]
The [beta version of this challenge](https://beta.freecodecamp.org/en/challenges/basic-css/override-class-declarations-by-styling-id-attributes) has a test case to cover this issue, so I think we just leave it at that and wait for the beta launch.

**Comment by cxw42** [comment]
Thanks for letting me know!  I just tried it in my browser (same version as above - Chrome 63.0.3239.132).  The code above did fail the challenge, so the beta does take care of the fundamental problem.  However, not all the diagnostics are accurate:

![cropped](https://user-images.githubusercontent.com/10515894/35104244-4345faec-fc36-11e7-903f-a224a922437b.png)

Should I open a separate issue for that against the beta?  I used the Developer Console to check some of the tests from [the beta source](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/basic-css.json#L2962) in `fcc-main-frame` and got:

    >  $('h1').length
    <- 2

(the red X in the screenshot)

    >  $('h1').hasClass('pink-text')
    <- true
    >  $('h1').eq(0).hasClass('pink-text')
    <- false
    >  $('h1').eq(1).hasClass('pink-text')
    <- true

    >  $('h1').attr('id')==='orange-text'
    <- true
    >  $('h1').eq(0).attr('id')==='orange-text'
    <- true
    >  $('h1').eq(1).attr('id')==='orange-text'
    <- false

I think the issue is partly differences in behaviour between [`$.attr()`](http://api.jquery.com/attr/) and [`$.hasClass()`](http://api.jquery.com/hasClass/): "The `.attr()` method gets the attribute value for _only the first element_ in the matched set," whereas `.hasClass()` determines "whether _any_ of the matched elements are assigned the given class" (emphasis added).  Adding `.eq(0)` to all the tests would probably take care of it, as far as I can tell from my very small exposure to the codebase.  

Let me know how (or if) you would like to proceed.  If my analysis above is correct, I would be happy to submit a small PR.  Thank you!

**Comment by huyenltnguyen** [comment]
@cxw42 Thanks for taking the time to investigate and for the detailed reports!

Your analysis looks correct to me. However, the tests in this challenge are designed to be independent of each other. It can be interpreted like this: 
- Check if there is a `h1` with a `pink-text` class, don't care how many `h1`'s there are.
- Check if there is a `h1` with a `orange-text` id, don't care how many `h1`'s there are.
- Check if there is only one `h1`, don't care what id or class it has.

 I only know the very basics of unit testing, so I can be wrong, but IMHO, because of the reason above, it's not necessary to check the class of the first child in the node list. 

The last test case is correct, though. You don't see the orange text on the preview pane because you didn't give it (the first `h1`) any text 😄. And when it comes to invalid HTML, don't trust what browsers show you. They are very forgiving and try to display what they can see and silently ignore any error.

Let me know what you think.

**Comment by cxw42** [comment]
@huyenltnguyen I agree with your point about unit testing.  However, I am not sure the target audience (which has probably never heard of unit testing ;) ) is best served by totally independent messages, at least in this case.  I am going to see if I can get some input from some non-technical people I know.

**Comment by raisedadead** [comment]
I agree for more tests to cover the use case in beta.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (112/100 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:39628)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUPj-000760-Jv
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:55:23 -0400
Received: from out-7.smtp.github.com ([192.30.252.198])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUOY-0006Iz-LG
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:54:10 -0400
Date: Sun, 03 Jun 2018 07:54:09 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037649;
	bh=ouM6bv7MyGmu51wjm53iBU/1JSGDe1AkWM2nW8PXZ/Q=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=PrTknRtuU79fWxSinX1OTH8sbau6o0Ffd9LzQZzoTHasoFLts2BfNxO1+8ayKwu9i
	 Zk2+brRfwByI52qqJagd/+BsKW/Y5R1tHj6qqDqwPtMoVIZAsBMFmrSaNUxAtLahgU
	 RnP1pcbHW+MJWyQx8n/180fgNtiT1oCL+GP5wE2c=

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (117/100 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:39845)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUQE-0007UL-DY
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:55:54 -0400
Received: from out-16.smtp.github.com ([192.30.254.199])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUOi-0006J5-D7
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:54:20 -0400
Date: Sun, 03 Jun 2018 07:54:18 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037658;
	bh=ZtvPZHddpu0+q4Pho9icUsAXsw08oO3zyoYOhuNU8Z4=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=h00PDkmBqJrwmXxzxrIBVxiZQmM4MTgUFFmQOfD9b/+AGB3tBr67z1P1DgzW3z5Ym
	 Da92MDluibGI31IsSuhKwtisK16PojnXSks9FDNKG+J5QoIo6adgmPDVs2O9/UG5hy
	 5/8E5e6LBTnEBrPPuQd4esbiZ1UI7AT+Fc0c27as=
