### ISSUE TITLE
move testfirst.org labs into FCC

### ISSUE THREAD

**Issue by alexch** [freeCodeCamp/freeCodeCamp#16519]
Many years ago, I taught a Ruby class with @ultrasaurus . Together we invented *test-first teaching* (so did a lot of others around this time, but it was new to us) and created http://testfirst.org to house our course materials. Over time the materials grew -- adding many Ruby tests, plus suites for JavaScript and Java, and an experimental "live" branch at http://testfirst.org/live -- but the site didn't.

- http://testfirst.org
- https://github.com/ultrasaurus/test-first-teaching (the original repo)
- https://github.com/alexch/test-first-teaching (and my personal fork)
- http://codelikethis.com (my slides and lessons, with links to the live Ruby tests)

Now the test-driven teaching world has moved far beyond our experiment, and I'd like to put our test-first labs up where more people can enjoy them... on FreeCodeCamp. At least the JS labs, for now, and at least on the FCC platform, if not the main FCC site itself. 

A few months ago, I checked in with @QuincyLarson and he said it was cool to use the platform for this and contribute new challenges and improvements, while giving due credit to FCC; if you have any questions or concerns about that, please let me know and we can hash them out here in this issue.

There's a lot of duplication between our tests and yours, and I want to separate the work of *converting* the tests from the work of *integrating* them into the `seed` challenges. After browsing the repo and messing around a bit in the code, here's my game plan.

- [x] improve documentation -- DONE and ongoing, starting with #16511 

- [x] write `unpack` script, to turn challenge JSON into a bunch of test/code/html files for editing & running, then `repack` script, to turn them back into JSON for checkin

- [ ] create JS versions of https://github.com/alexch/test-first-teaching/tree/master/learn_javascript and get them running locally, then

- [ ] talk with FCC maintainers about the best way to integrate these now-running tests into FCC proper, but also

- [ ] launch my own version of them, with due credit to FCC and upstream links, to use when teaching my [3 month in-person bootcamp](http://www.burlingtoncodeacademy.com/bootcamp/) this summer

How does that sound?

**Comment by raisedadead** [comment]
@alexch Thanks a lot for sharing your thoughts and interest on moving testfirst.org curricular content.

If you are willing to mentor the contributors, I think we can get this done in collaboration. But, before any confirmation We will have to defer to Quincy first for the thoughts.

@QuincyLarson I think Alex, has got some great ideas here. Do you mind sharing your thoughts as well?  IMHO this would be a nice addition, and we could use Alex's expertise on this.

**Comment by QuincyLarson** [comment]
@alexch Yes - I remember talking with you about this. We would love to have more comprehensive coverage of testing as part of the core freeCodeCamp curriculum. Currently we have a section on testing, though it doesn't go very deep. If you can adapt these challenges to run on freeCodeCamp client-side, we'd be interested in including some of them.

Your game plan looks solid. You can definitely use the freeCodeCamp open source project as you wish (within the bounds of the quite permissive BSD-3 license), and many intensive programs are already doing this, so no problem there :)

**Comment by raisedadead** [comment]
Hi @alexch I have landed your commits over in staging. Thanks for confirming on the inconsistency. 

Since you are already at it. I have two more additional points to the OP for your consideration:

1. Could you add (and rather seamlessly integrate) a normalizing script as we were talking about in #16544, so that when some one does a `npm run repack`, its all taken care off?

2. Can we add some tests for linting the seed files? we are using a user friendly reporter already 
    `npm run test-develop`

See https://github.com/freeCodeCamp/freeCodeCamp/blob/30b26e1476eb2e40695256c5e060c2d804138789/package.json#L29

**Comment by alexch** [comment]
Sure, I love writing tests. But can we do those in a new PR? I'm already seeing conflicts in the current PR and I'm afraid those will only multiply.

The normalizing is already done (via `JSON.stringify` and by @Bouncey 's branch); the only question is whether to add `"+'\n'"` to the end of that line in `unpackedChallenge.js`.

**Comment by raisedadead** [comment]
Yes, absolutely.. I have landed your current PR already. I could see that we were seeing more conflicts as we waited. I have rebase some files already and you can work on the enhancements as you please.

I think adding a new line is a good idea in practice.

**Comment by raisedadead** [comment]
Looks like this was closed in error.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, seems stale, but what do you think?
