### ISSUE TITLE
Challenge missing

### ISSUE THREAD

**Issue by DarrenfJ** [FreeCodeCamp/freecodecamp#1651]
Challenge http://beta.freecodecamp.com/challenges/waypoint-generate-random-fractions-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

"404: We couldn't find a challenge with the name `waypoint-iterate-with-javascript-do-while-loops` Please double check the name."

Just bypassed it to the next one

**Comment by sonorangirl** [comment]
That happened to me as well on #29 Waypoint: Iterate with JavaScript Do-While Loops and also on #33 Waypoint: Use Conditional Logic with If-Else Statements

<img width="1152" alt="screen shot 2015-08-07 at 7 16 49 pm" src="https://cloud.githubusercontent.com/assets/6051437/9148661/5806d88e-3d39-11e5-89fc-186ea02b67be.png">

**Comment by ahstro** [comment]
I believe this might stem from the same bug as is being discussed in #1439.

**Comment by BerkeleyTrue** [comment]
This should be fixed now. Happy Coding!

**Comment by interglobalmedia** [comment]
Hi, I also came up with "link not found" for "Storing Values with the Equal Operator" challenge just now. You are still taken nowhere. Shouldn't this  link either be updated or removed? Thanks!
