### ISSUE TITLE
npm run seed

### ISSUE THREAD

**Issue by alexch** [freeCodeCamp/freeCodeCamp#16520]
I can see what `node seed` does -- it runs seed/index.js -- but should that code be moved to use gulp instead, for conformity with `npm run test` et al.? It's confusing that some dev scripts are run with `npm run` and others with `node`.

**Comment by raisedadead** [comment]
Yup, we recently updated the scripts to have `npm run develop` instead of `gulp` (default). I am thinking we could do a `npm run seed` ?

The scripts should be independent to differentiate  between different tasks. 

Do you have any proposals in mind? How we should go about it? Ideally we would want to do a `npm run xxxx` for xxxx like instruction in the docs.

**Comment by raisedadead** [comment]
What would you like to add to the `gulp` scripts BTW? 

I think we would want a common script that can (in pseudo code):
```
if ( server/rev-manifest.json exists? ) {
   npm run only-once
} else {
   node seed
}
```

This should simply be a `npm run seed` eliminating the need for the `only-once`?

**Comment by alexch** [comment]
Please forget I said anything about gulp. I was confused. 

This is what I mean:

https://github.com/freeCodeCamp/freeCodeCamp/pull/16544/commits/8ed1b3a6031942d363680de4a356209ca19e5487

(I went ahead and implemented it on my own branch. I can cherry-pick it onto a new branch if you like, for separate PR review.)

Sorry, I don't know what `rev-manifest` is for or why it would ever not exist. It's in the repo, after all (though it's an empty `{}` now).

**Comment by raisedadead** [comment]
Ah.. right. Sorry I should have clarified.

Well, when a server is setup first time, a rev-manifest is created, I believe for versioning, its content change locally. And hence its "changes" are not tracked in `git`.

This file is to be populated for the first time using `npm run only-once`, and seeding the DB.
Then on `node seed` is used, whenever seed files are updated.

I am sure we could this more elegantly. I'll have to confirm from @BerkeleyTrue more on that.

But, yeah... like you already said, we should simply add the change in the commit you mentioned are good enough, for a unifying experience of using `npm run xxxx` from a contributors point of view.

**Comment by BerkeleyTrue** [comment]
@raisedadead you summery is correct. We must first verify that the manifest file exists in order for the seed script to run.
