### ISSUE TITLE
[beta] Update tests for checking valid ObjectId for challenges

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16524]
Checking for invalid Ids:

- [ ] We need to have some tests or update them for valid ObjectIds.
- [ ] We would also, as a precaution want to identify duplicate ObjectIds if present.
- [ ] Finally we would need to audit and fix up any, ObjectIds which are not valid.

See https://github.com/freeCodeCamp/freeCodeCamp/issues/16523
The documentation update is tracked via #16373 

Our challenge ids have to be a valid 24 char Hex MongoDB compatible ObjectId.
Some, reference on checks:
https://stackoverflow.com/a/11989159/1932901

**Comment by raisedadead** [comment]
From what I can see, we just need to check this as `isMongoId` and the specs are they should be a hexadecimal, 24 char string?

/cc @BerkeleyTrue

**Comment by BerkeleyTrue** [comment]
@raisedadead Sounds good. `validator` has a `isMongoId` function. We we will need to add some functionality to check for duplicates though. This is usually caught with node seed, since mongodb auto rejects dup ids.

**Comment by tienanh2007** [comment]
Hi, I have been using FCC for a while and learn a lot about web development. Now, I want to help by contributing. Could I try to do this? And if so how do I get started on this?

**Comment by raisedadead** [comment]
@tienanh2007 sure, this is the file where the tests are https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/test-challenges.js

We are using a package called `validator` which has a method that checks for a valid id using `isMongoId`.

You need to update the tests to check for this.

Check our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and reach us in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for assistance.

Happy contributing!
