### ISSUE TITLE
"Record Collection" challenge Code Editor not changing console

### ISSUE THREAD

**Issue by Giagnus64** [freeCodeCamp/freeCodeCamp#16527]
#### Challenge Name

https://www.freecodecamp.org/challenges/record-collection
#### Issue Description

When inputting anything into the code editor on the right side, the console on the left side only outputs the "collection". I have tried deleting local storage on the browser, clearing cache, refreshing, etc. 

#### Browser Information

* Browser Name, Version:  | 50.0.2762.58 - Opera is up to date
Mac OS X 10.10.5 64-b
* Operating System: Mac OS Yosemite 10.10.5
* Mobile, Desktop, or Tablet: Desktop
#### Screenshot

![screen shot 2018-01-18 at 4 21 00 pm](https://user-images.githubusercontent.com/28762593/35122299-40813084-fc6c-11e7-8cb6-f782edb918af.png)

**Comment by systimotic** [comment]
Thanks for reporting this issue @Giagnus64.

This was intended behavior. It will always show the value of the `collection` variable after running the code in the editor, thanks to the following line:
https://github.com/freeCodeCamp/freeCodeCamp/blob/938d38857e4ee512e213f6a63d735113367ce581/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json#L5037
In the beta, this does not work anymore, as returned values are no longer showed in the window on the left. Instead, only the output of `console.log`'s in the editor is supposed to be shown in the editor (I can't seem to get that to work right now).
I thought Quincy had gone through and added `console.log`'s to all of the challenges, but that doesn't seem to be the case here.

This may be a broader issue, especially since the window does not show `console.log` output. @raisedadead What do you think?

**Comment by raisedadead** [comment]
@systimotic yes, you are correct. This still needs to be handled in some challenges, by updating the seed code.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (102/100 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:38394)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUNP-0005Gr-VM
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:00 -0400
Received: from out-5.smtp.github.com ([192.30.252.196])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUN0-0006Ei-0N
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:52:34 -0400
Date: Sun, 03 Jun 2018 07:52:33 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037553;
	bh=EwkvZjbjwgdieRjgRbYhP3fKcQtUemE49+X+9gNpcyE=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=E5P4n8zH/UzH6B73xDMmneFStaXb8dkt0q12UOrwfSApN9znIYd7icPhqHh4UEBKu
	 Qi9FxmaOGNCN0jQjD0cVI00Nj39LqPmRb04pAVAyLPIk8ag6SmJMe0NA5YHzRuwQf9
	 KjOXH4yJ4TDa6dnt+IzUyrQBJatzBO0vw9LOt3fg=

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (104/100 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:38399)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUNQ-0005HO-8F
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:00 -0400
Received: from out-2.smtp.github.com ([192.30.252.193])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUMz-0006Eh-9b
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:52:33 -0400
Date: Sun, 03 Jun 2018 07:52:32 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037552;
	bh=NzcA6N5EO41yGRou93D605zpQlzVV4afZGoDdDX7Rcs=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ucrOsoMl/VlrwjfAAJ5KQ6p6lTscMFnygeMS421YVaj15XqsGsKK0pnwWIq2/lLbq
	 Amj57s43P3li3pwpaHmzEO18kH0NK3DkVLTSw3itRCf1gtEIQOEnaePQs5qPaBzJbb
	 5tZPxxSdKW+C4ICuy4ei9c8tU3iZ925YNxo5v8Rs=
