### ISSUE TITLE
Beta: Waypoint: Add ID Attributes to Bootstrap Elements - tests not correct

### ISSUE THREAD

**Issue by richyvk** [FreeCodeCamp/FreeCodeCamp#1652]
Challenge http://beta.freecodecamp.com/challenges/waypoint-add-id-attributes-to-bootstrap-elements

I can get the tests to pass by putting the well-left and well-right ids on button elements instead of the well div.

![screen shot 2015-08-08 at 9 02 31 am](https://cloud.githubusercontent.com/assets/4687812/9147751/f0bc9a58-3dae-11e5-9b00-9977bb8b2eaf.png)

**Comment by benschenker** [comment]
Thanks @richyvk,
I've been able to replicate this

**Comment by bugron** [comment]
Closing this issue as it is fixed. See [L1939](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/bootstrap.json#L1939) and [L1940](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/bootstrap.json#L1940).
