### ISSUE TITLE
Audit codebase to make sure all relative protocol URLs start with "HTTPS"

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16522]
We have been using and recommending protocol relative URLs like so:

```html
<script src="//code.jquery.com/jquery-2.2.3.min.js"></script>
```

This was made popular by:
https://www.paulirish.com/2010/the-protocol-relative-url/

But, I believe, this something we should be NOT be doing now on, since the author have long since updated their advice.

More reference: https://jeremywagner.me/blog/stop-using-the-protocol-relative-url/

Hence we need to audit our code-base for such uses, list them here and update the links after confirmation.

Original seen in https://github.com/freeCodeCamp/freeCodeCamp/pull/16488#issuecomment-358730193

**Comment by QuincyLarson** [comment]
@raisedadead I agree with Paul Irish's logic here. @BerkeleyTrue what do you think? Should we create an issue to go through and turn these relative URLs into https URLs?

**Comment by raisedadead** [comment]
Note, this should only be done for URLs that we can confirm are served over https already.

**Comment by BerkeleyTrue** [comment]
I'm for making cdn links explicitly https.

**Comment by QuincyLarson** [comment]
@raisedadead @BerkeleyTrue Sounds like a plan! 

I've updated the issue title and added the Help Wanted label.

**Comment by LorenpNYC** [comment]
HELLO,
HOW DO I UNSUBSCRIBE FROM THESE EMAILS???

SICK AND TIRED OF MY PHONE CONSTANTLY BLOWING UP WITH FREE CODE CAMP BS!!!!

**Comment by tarun7singh** [comment]
@raisedadead 
I am starting to work on this.

**Comment by QuincyLarson** [comment]
@tarun7singh OK - thanks for jumping on this one. Please keep us posted on your progress with it, and let us know if you have any questions :)

**Comment by tarun7singh** [comment]
I have made a PR request to complete this issue.
