### ISSUE TITLE
Modern Challenges: when only one editor, default nav link to "Editor", else use file name

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#16529]
[Per @BerkeleyTrue's suggestion](https://github.com/freeCodeCamp/freeCodeCamp/pull/16459#issuecomment-358042085), modify modern challenges editor nav link to default to "Editor" instead of "index" when there is only one editor tab. Set it up so that in the future, when we have multi-tab editor, it will default to file name:

> The original intent here was to replicate an actual editor, with the name of the file you are actually editing at the top of the file but I see the issue with the name in the nav that could confuse new users. The problem with renaming it to editor is when you have more than one, you can't call them both Editor.
>
> A compromise: When there is only one editor we can default to Editor and when there is more than one we could name them by file. Thoughts?

**Comment by werne2j** [comment]
@raisedadead @no-stack-dub-sack Working on this fix, should be pushing up a PR soon!
