### ISSUE TITLE
[beta] Invalid ObjectId in Introduction to Arrays Challenge

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16530]
We have an invalid MongoDB ObjectId set for the "Introduction to Arrays" challenge.

Looking at the git blame

https://github.com/freeCodeCamp/freeCodeCamp/blame/76941a08d87f0806da1674d5d60a3ae0087cbfa7/seed/challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json#L8

This came from https://github.com/freeCodeCamp/freeCodeCamp/pull/12817

Fix:

We should update this to a valid ObjectId, See #16373 on how to do so.

This line needs to be updated with a valid ObjectId.

https://github.com/freeCodeCamp/freeCodeCamp/blob/76941a08d87f0806da1674d5d60a3ae0087cbfa7/seed/challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json#L8

**Comment by Asjas** [comment]
Hi @raisedadead 

I'll take a look at fixing this. Seems easy enough for a first time contribution :smile:

**Comment by raisedadead** [comment]
Hi @Asjas super excited to see you getting ready for contributing to code on this code-base, Your issue reports here and work on guides are really great! Looking forward to a PR.

Happy contributing!
