### ISSUE TITLE
Outdated Challenge Information - Safari/HTML5

### ISSUE THREAD

**Issue by egavett** [freeCodeCamp/freeCodeCamp#16533]
#### Challenge Name
[Use HTML5 to Require a Field](https://www.freecodecamp.org/challenges/use-html5-to-require-a-field)

#### Issue Description
While working through the exercise on HTML5 and the ‘required’ attribute, I noticed that the last line mentions:
>Note: this field does not work in Safari.

However, while working on the exercise in Safari 11.0.2, I found that the ‘required’ field works as intended. Everything I’ve found says that Safari has supported the ‘required’ field for over a year now.

The issue can be reproduced by completing the challenge while using Safari.

#### Browser Information
* Browser Name, Version: Safari 11.0.2
* Operating System: Mac OS High Sierra 10.13.2
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
![html5 required](https://user-images.githubusercontent.com/10409060/35139191-daf5ddc4-fca6-11e7-8523-d3f9244eefa3.png)

**Comment by davinderpalrehal** [comment]
@egavett is right Safari has supported the required for some time now. Can I work on this PR?

**Comment by raisedadead** [comment]
@davinderpalrehal sure, why not. You just have to remove the note.

Here are our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and we can be reached for any assistance in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by davinderpalrehal** [comment]
Awesome... will be submitting a PR in the next hour 😄

**Comment by davinderpalrehal** [comment]
Just submitted the PR, also realised I didn't follow all the guidelines, sorry guys
