### ISSUE TITLE
All challenges in "Front End Development Certification" completed, but don't claim certificate.

### ISSUE THREAD

**Issue by plasteelin** [freeCodeCamp/freeCodeCamp#16538]
#### Issue Description

I've completed all challenges in "Front End Development Certification" but I've not received the certificate. 
On the Gitter Help channel I've been advised to wait 1-2 days until they check my challenges.
Then on the forum we found that progress on the map and progress in my profile don't match.
The last suggestion on the forum is to open an issue here on GitHub.

Any help would be appreciated.

Thanks.

#### Browser Information

* Browser Name, Version: Google Chrome, ver. 63.0.3239.132
* Operating System: Windows 10, 64-bit
* Mobile, Desktop, or Tablet: Desktop

```js



```
#### Screenshot

This is the  my issue:
![1](https://user-images.githubusercontent.com/18583374/35161358-a2fb78be-fd48-11e7-94ee-2dc267c8d902.png)

I had completed all challenges on the map:
![2](https://user-images.githubusercontent.com/18583374/35161832-0f2d7b58-fd4a-11e7-9bca-47914dab106f.png)
![3](https://user-images.githubusercontent.com/18583374/35161834-0f67c4a2-fd4a-11e7-9758-e1a6ff48555e.png)
![4](https://user-images.githubusercontent.com/18583374/35161835-0f94b750-fd4a-11e7-8394-fe8ceec4f086.png)
![5](https://user-images.githubusercontent.com/18583374/35161837-0fba3d54-fd4a-11e7-886b-71c5d9f0ed27.png)
![6](https://user-images.githubusercontent.com/18583374/35161838-0fee91a8-fd4a-11e7-8195-1456a737c14f.png)

**Comment by raisedadead** [comment]
@BerkeleyTrue looks like this is recurring issue. Quincy, manually added a fix for a user.
Can you check in the backend, if we have all the flags for the user correctly set.

If you give some pointers, I can take up looking in the code for anything that is missed for any required flag that is not set, for some buggy logic.

**Comment by raisedadead** [comment]
Here is the previous issue for more context:

https://github.com/freeCodeCamp/freeCodeCamp/issues/16091

**Comment by raisedadead** [comment]
@plasteelin if you agree, can we close this in favour of more technically relevant thread I listed above?

**Comment by plasteelin** [comment]
I agree, but what I do now?

**Comment by raisedadead** [comment]
Hi, I understand this is an inconvenience. 

We request you to bear with us while we try to identify the bug.
You should proceed with the curriculum and we will update you once this is fixed. You will be able to claim your certificate then.

Rest assured your progress will be safe.

**Comment by plasteelin** [comment]
i.e when i passed back-end , i can claim and front-end?

**Comment by raisedadead** [comment]
Yes @plasteelin you are correct, you can continue with solving the challenges. And later on visit to claim the certificates.

/cc @QuincyLarson

**Comment by QuincyLarson** [comment]
@plasteelin I'm closing this issue and fixing your database record. Please try claiming your front end cert again and confirm that this worked :)

**Comment by BerkeleyTrue** [comment]
@QuincyLarson we shouldn't be manually modifying records. This is an issue that has popped up more that once. We need to find the root of the issue and create a solution.

**Comment by QuincyLarson** [comment]
@BerkeleyFalse In this case, I added the following properties to the record:
```
  "isBackEndCert": false,
  "isFrontEndCert": false,
  "isNewDataVisCert": false,
  "isFullStackCert": false,
```

Unlike the situation before where I created the property and toggled it for them. I may have misunderstood you last time we talked about this.

 It probably isn't worth the time investment of addressing this issue on backup/master. Is this likely to be an issue with beta?

**Comment by BerkeleyTrue** [comment]
> Unlike the situation before where I created the property and toggled it for them.

Whether the values are there or not wouldn't effect the logic as loopback auto-populates it. 
https://github.com/freecodecamp/freecodecamp/blob/backup/master/common/models/user.json#L148

> Is this likely to be an issue with beta?

Yes, as the logic is the same between both.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue OK - I won't make any further changes when people report this sort of issue. I'll just refer them to https://github.com/freeCodeCamp/freeCodeCamp/issues/16091
