### ISSUE TITLE
LinkedIn Scope issue "InternalOAuthError: failed to fetch user profile"

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16559]
We have been getting InternalOAuthErrors for linkedIn recently on PRODUCTION. 

Also reported by @IsaacAbrahamson in https://github.com/freeCodeCamp/freeCodeCamp/issues/14652#issuecomment-359528285

We need to update our config as per the suggested fix for the correct scope:
https://github.com/auth0/passport-linkedin-oauth2/issues/24#issuecomment-358279513

Just to note, this still links the profile, correctly, only thing is this exception needs to be handled, by correcting the scopes.

**Comment by raisedadead** [comment]
@BerkeleyTrue I confirmed this on the opbeat dashboard.

**Comment by QuincyLarson** [comment]
@raisedadead the only thing I can think of is that LinkedIn suddenly got stricter about HTTPS. I've updated all the URLs associated with our LinkedIn API key to use HTTPS.

**Comment by raisedadead** [comment]
Yup, while using HTTPS is a good idea, we also need to update our config to limit the scope that is the `public_url` of the user in the request that we are making to LinkedIn API.

We are currently using a default config, that may have been breaking this in production.

**Comment by QuincyLarson** [comment]
@raisedadead Do you know how we'd go about doing this? If this is breaking this aspect of production, then we should go ahead and make a hot-fix.

**Comment by QuincyLarson** [comment]
@raisedadead Do you know how we'd go about doing this? If this is breaking this aspect of production, then we should go ahead and make a hotfix.

**Comment by ojongerius** [comment]
Reading through https://github.com/auth0/passport-linkedin-oauth2/issues/24 and looking at the config used in your code the `scope` looks fine, but the `profileFields` need being set -unless you prefer catch the exception and shrug.

I'm not familiar with this code base, but based on @raisedadead's suggestion to just catch the exception it sounds like we don't really care what is returned at all.

A blunt fix would be to just add the suggestion in https://github.com/auth0/passport-linkedin-oauth2/issues/24 and specify the `profileFields`:

```
{
   // specify which profile fields to fetch, instead of the default to return all the things
    profileFields: [
                "formatted-name",
                "headline",
                "id",
                "public-profile-url",
                "email-address",
                "location",
            ],
    scope: ["r_basicprofile", "r_emailaddress"], // as in place at the moment
}
```

I noticed you have three places where you configure linkedin, as `linkedin` in [/config/secrets.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/549cfc305f75d8c6036a3cde65c47b518607b18c/config/secrets.js) and as `linkedin-login` and `linkedin-link` in [/server/passport-providers.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/1d7e5535d104266e02c2883ec8c38db4d14afcba/server/passport-providers.js)

**Comment by ojongerius** [comment]
@raisedadead @QuincyLarson just got back from lunch, have created and linked a PR to this issue.

**Comment by ojongerius** [comment]
@raisedadead case closed?

**Comment by raisedadead** [comment]
Thanks @ojongerius
