### ISSUE TITLE
[beta] Invalid ObjectId in Access an Array's Contents Using Bracket Notation challenge

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16550]
We have an invalid MongoDB ObjectId set for the "Access an Array's Contents Using Bracket Notation" challenge.

**Fix:**
We should update this to a valid ObjectId, See #16373 on how to do so.

This line needs to be updated with a valid ObjectId.

https://github.com/freeCodeCamp/freeCodeCamp/blob/7cbe4141ced9cf8409fd33a0eb85541370c7fa6c/seed/challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json#L67

**Comment by raisedadead** [comment]
Here are our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and we hangout in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for any assistance.

**Comment by shovanch** [comment]
Hi @raisedadead  I'll give it a try. Looking forward to submit PR ASAP.

**Comment by ATLowther** [comment]
Hello @shovanch, were you unable to get to this? I'll try to take care of this right now.

**Comment by shovanch** [comment]
@ATLowther No problem, Go ahead

**Comment by no-stack-dub-sack** [comment]
@raisedadead are you sure this is the only challenge in this section with an invalid ObjectId by any chance? This was my section, and this was before I knew how to correctly generate them (and before we had documentation on how to do so) 😬

**Comment by raisedadead** [comment]
@no-stack-dub-sack see #16524

**Comment by no-stack-dub-sack** [comment]
@raisedadead ahhh, gotcha. This should def turn up a few :smile:
