### ISSUE TITLE
[Beta] React set state challenge doesn't need any code to pass tests

### ISSUE THREAD

**Issue by kgalang** [freeCodeCamp/freeCodeCamp#16555]
https://beta.freecodecamp.org/en/challenges/react/set-state-with-thissetstate
#### Challenge Name
React Set State with this.setState()

https://beta.freecodecamp.org/en/challenges/react/set-state-with-thissetstate

#### Issue Description

The default code passes all tests no matter what you put. This has been verified by two other users on gitter.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 63.0.3239.132 (Official Build) (64-bit)
* Operating System: Mac OS High Sierra 10.13.2
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
This is the default code:

```js
class ControlledInput extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      input: ''
    };
  }
  // change code below this line

  // change code above this line
  render() {
    return (
      <div>
        { /* change code below this line */}

        { /* change code above this line */}
        <h4>Controlled Input:</h4>
        <p>{this.state.input}</p>
      </div>
    );
  }
};


```
#### Screenshot

Here are the challenge instructions and tests that are displayed:

<img width="760" alt="screen shot 2018-01-22 at 10 36 35 am" src="https://user-images.githubusercontent.com/18174574/35229026-406f6a6a-ff60-11e7-853e-072a63d6fbc6.png">

<img width="758" alt="screen shot 2018-01-22 at 10 36 45 am" src="https://user-images.githubusercontent.com/18174574/35229025-405ee2bc-ff60-11e7-83f3-5540ef04c624.png">

**Comment by diogorighi** [comment]
Hey, I have experience with react but not much experience contributing with open source projects. How can I be helpful?

**Comment by Asjas** [comment]
Hi @diogorighi 

This challenge can be found on [this](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/03-front-end-libraries/react.json#L1297) line in the challenge seed directory. It seems there are problems with the testing of this challenge. You can find the tests underneath the challenge contents.

You can see if you can find the problem and get a solution for it. Just remember that after you make changes to the tests you need save the file and run `node seed` to populate the database with the updated tests. You can then re-run the tests to see if it is fixed.

Good luck 👍

**Comment by diogorighi** [comment]
Thanks, @Asjas! I'm working on it!
