### ISSUE TITLE
[Beta] Comment on where to code is misplaced in React challenge

### ISSUE THREAD

**Issue by kgalang** [freeCodeCamp/freeCodeCamp#16554]
#### Challenge Name
React Write a Simple Counter

https://beta.freecodecamp.org/en/challenges/react/write-a-simple-counter

#### Issue Description

The default code tells you to define methods underneath the constructor. However, the default code doesn't include the explicit binding of these methods that need to go within the constructor. I'm not sure if the fix should be moving up the comment that says  "change code below this line" or if the challenge should already have the binding lines within the constructor. Once I know which solution would be better, I'd like to help make a PR to correct this.

#### Browser Information

* Browser Name, Version: Google Chrome, Version 63.0.3239.132 (Official Build) (64-bit)
* Operating System: Mac OS High Sierra 10.13.2
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

Here is the successful challenge code.
```js
class Counter extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0
    };
    this.reset = this.reset.bind(this);
    this.increment = this.increment.bind(this);
    this.decrement = this.decrement.bind(this);
  }
  // change code below this line

  reset() {
    this.setState({ count: 0 });
  }
  
  increment() {
    this.setState({ count: (this.state.count + 1) })
  }
  
  decrement() {
    this.setState({ count: this.state.count - 1 })
  }
  // change code above this line
  render() {
    return (
      <div>
        <button className='inc' onClick={this.increment}>Increment!</button>
        <button className='dec' onClick={this.decrement}>Decrement!</button>
        <button className='reset' onClick={this.reset}>Reset</button>
        <h1>Current Count: {this.state.count}</h1>
      </div>
    );
  }
};

```
#### Screenshot

<img width="720" alt="screen shot 2018-01-22 at 10 06 00 am" src="https://user-images.githubusercontent.com/18174574/35227352-e533b556-ff5b-11e7-8568-fa21e7c3ec09.png">

**Comment by kgalang** [comment]
This issue is also in React: Create a Controlled Input challenge
https://beta.freecodecamp.org/en/challenges/react/create-a-controlled-input

I'm not sure if it is in any of the other react challenges yet. Still working through them

**Comment by no-stack-dub-sack** [comment]
@kgalang Nice catch, if you're still working through them, let's find out if this issue is in any other challenges so we can fix them all at once. This is likely because on the Alpha versions of these challenges, we were using arrow function syntax for binding methods to the class. The FCC environment doesn't support this, so we had to switch back to the good ol' fashioned way, and clearly we didn't think of adding the comments to denote that code needs to be added there. 

My suggestion would be, that as long as these challenges come after where we teach binding methods, than we should just add another set of comments to denote that code needs to be changed in the constructor, rather than doing it for them. This is an important concept, so this will help drive it home. 

Thanks for pointing this out!

**Comment by raisedadead** [comment]
@no-stack-dub-sack Since the change you suggest looks trivial enough, I am of the opinion that we can open separate issues per challenge, and tag them for first timers? What do you think?

**Comment by kgalang** [comment]
@no-stack-dub-sack I agree. Having to type the bind statements has helped me internalize the concept.

@raisedadead Sounds like a good plan to me!

I will keep you both updated in this thread if I find similar issues throughout the rest of the react challenges. Let me know if you'd like me to update you anywhere else.

**Comment by raisedadead** [comment]
@kgalang awesome, please prefer creating separate issues, we could engage more contributions.

**Comment by no-stack-dub-sack** [comment]
@raisedadead I definitely agree. These are perfect issues for first-times to get used to our process on. 

@kgalang if you find any others, please open new issues as @raisedadead has suggested. 

Thanks!

**Comment by bqnguyen94** [comment]
I will give this a try!
