### ISSUE TITLE
Someone has temote access to all my acconts and servers

### ISSUE THREAD

**Issue by Mkdeacon** [freeCodeCamp/freeCodeCamp#16564]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by Asjas** [comment]
@Mkdeacon I am not seeing anything logged in this issue? Can you explain what you mean by the issue title?

**Comment by Mkdeacon** [comment]
Someone is accessing through my home ip. They have been able to put malware in my cell phones. My apple and android phones are beinging accessed. Downloaded my google dashboard and stolen my idenity. They changed nfc settings and file shared all my files again today.  My addministration access has been changed on my server ss well as my pc. I found a software program called 5nine

**Comment by Asjas** [comment]
Hi @Mkdeacon 

Unfortunately this isn't a support forum. Best you get technical assistance from a local computer shop.
