### ISSUE TITLE
Beta: English error in Basic HTML and HTML5

### ISSUE THREAD

**Issue by ReveurGAM** [freeCodeCamp/freeCodeCamp#16561]
#### Challenge Name

[Basic HTML and HTML5: Link to External Pages with Anchor Elements](https://beta.freecodecamp.org/en/challenges/basic-html-and-html5/link-to-external-pages-with-anchor-elements)
**-AND-**
[Basic HTML and HTML5: Nest an Anchor Element within a Paragraph](https://beta.freecodecamp.org/en/challenges/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph)

#### Issue Description

It says:
> The text, "link to freecodecamp.org", within the anchor element called anchor text, will display a link to click:

This sentence is a bit of a mess. It would be best corrected thusly:
"The text "link to freecodecamp.org" (found between the opening and closing tags: <a></a>) is called "anchor text", and it will be displayed as a link to click:"

PortableStick suggested I post this here.

I'd go in and correct it myself if I knew how.  GitHub baffles me.

**Comment by ReveurGAM** [comment]
A more simplified approach would be:
"The text "link to freecodecamp.org" will be displayed as a link to click.   It is located between the opening and closing tags, and is called "anchor text."

**Comment by ninadingole** [comment]
@ReveurGAM your approach is good, I just want to add a few words to it:
"The text "link to freecodecamp.org" will be displayed as a link which a user can click. It is located between the opening and closing tags, and is called "anchor text."

@ReveurGAM @raalejandre Let me know which approach to take I will do the changes. 🌞

**Comment by ReveurGAM** [comment]
Either is fine with me.

**Comment by ninadingole** [comment]
@ReveurGAM @raisedadead I will proceed with the changes.
