### ISSUE TITLE
Beta:"Cannot set property 'credentials' of null" message

### ISSUE THREAD

**Issue by ReveurGAM** [freeCodeCamp/freeCodeCamp#16568]
#### Challenge Name

I'm not certain when it appeared, as I've been multi-tasking, but it may have shown up on Basic [HTML and HTML5: Add Placeholder Text to a Text Field](https://beta.freecodecamp.org/en/challenges/basic-html-and-html5/add-placeholder-text-to-a-text-field)

#### Issue Description

I have no clue.  I just noticed it.  There is a blue bar above the challenge frame with the message: "Cannot set property 'credentials' of null".  Inspecting it, the HTML is:

```html
<div class="flash-container bg-info">
  <div class="flash-content">
    <p class="flash-message">Cannot set property 'credentials' of null</p>
    <button type="button" class="close">
      <span aria-hidden="true">×</span>
      <span class="sr-only">Close</span>
    </button>
  </div>
</div>
```
_Edited by Timo: code formatting_

#### Browser Information

* Browser Name, Version: Chrome, current v.
* Operating System: Windows 7 Ultimate, SP1
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![screenshot of error message](https://user-images.githubusercontent.com/35181004/35363953-565cce16-0132-11e8-873b-ababc20259a0.png)

**Comment by huyenltnguyen** [comment]
Hi @ReveurGAM, thanks for reporting!
Are you referring to the 'JavaScript is disabled' message? This is a new feature, I believe. It's to prevent/minimize the risk of users executing malicious code. You'll need to click the 'Code Locked. Unlock?' to unlock, then click it again to run the code.

**Comment by ReveurGAM** [comment]
@huyenltnguyen No, please reread what I wrote.  I know why the JS message is there.  This is about the one in the blue bar at the top that I highlighted (grey).

> There is a blue bar above the challenge frame with the message: "Cannot set property 'credentials' of null".

**Comment by raisedadead** [comment]
@ReveurGAM thanks for reporting. 

@huyenltnguyen thanks for taking the time for looking at this, just to note we have https://github.com/freeCodeCamp/freeCodeCamp/issues/16250 for the UX confusion.

As for this issue, I am unable to reproduce this as of yet. Any help in the steps to get this, would be appreciated.

**Comment by systimotic** [comment]
@ReveurGAM That's weird 😕 I'm noticing it says there are nine errors in the console, can you show us what those are?

**Comment by ReveurGAM** [comment]
I just got on and went to look at that page (I left the tab open but closed Chrome), and the error has reappeared, but on a different challenge.  Here's a screenshot.  It wasn't there last night.

I'm not sure what you mean by the nine errors....
![image](https://user-images.githubusercontent.com/35181004/35390453-252f3fbc-01a1-11e8-95d7-0b644fbc2dc0.png)

**Comment by raisedadead** [comment]
@ReveurGAM can you click the console tab on the Dev tools? If there are errors in red ?

**Comment by ReveurGAM** [comment]
@raisedadead @systimotic 
There are currently no errors in the console.  I will close the error and check this from a different computer as I must leave, then I will check again when I get home.

**Comment by raisedadead** [comment]
@BerkeleyTrue would you have any idea on this?

**Comment by BerkeleyTrue** [comment]
@ReveurGAM Are you signing in by email or social auth?

**Comment by systimotic** [comment]
I'm not well versed enough in RxJS and the codebase to really pinpoint the problem, but I did find something interesting. @BerkeleyTrue might be able to make more sense of it.

https://github.com/freeCodeCamp/freeCodeCamp/blob/2fcd9767005579b1f33433032f23012a19121ee7/common/models/User-Credential.js#L53
This line suggests that it possible for `_credentials` to be falsy. `null` just so happens to be falsy (`{}` is truthy).

https://github.com/freeCodeCamp/freeCodeCamp/blob/2fcd9767005579b1f33433032f23012a19121ee7/common/models/User-Credential.js#L67
On this line, the `credentials` property is set of a variable that could still be falsy.

This looks like a condition where it would be possible to get this exact error message. Maybe it's useless, but it seemed related to my untrained eye. What do you think @BerkeleyTrue?

**Comment by BerkeleyTrue** [comment]
Yes, nice catch @systimotic there should be an `else` statement there.

**Comment by ReveurGAM** [comment]
@BerkeleyTrue Email log-in.  So far, no error...
