### ISSUE TITLE
Beta: Distance calculations incorrect for finding a study group

### ISSUE THREAD

**Issue by ReveurGAM** [freeCodeCamp/freeCodeCamp#16562]
****Area & Link
[Join a study group](https://study-group-directory.freecodecamp.org/)

****Problem Description
(Sorry, I aborted a report before because there was no cancel button, but then this app wouldn't reload the template, so I'm writing without the template).

The website is not calculating distances correctly.  I highly doubt that CA is closer to Milwaukee, WI than WV, nor is it just past Sheboygan. ;)

****Browser & Environment
Chrome Version 63.0.3239.132 (Official Build) (64-bit)
Desktop with W7 Ultimate

****Screenshots
![image](https://user-images.githubusercontent.com/35181004/35300443-030e33ec-004e-11e8-8136-05df32687795.png)

**Comment by raisedadead** [comment]
Issue moved to [freeCodeCamp/study-group-directory #61](https://github.com/freeCodeCamp/study-group-directory/issues/61) via [**ZenHub**](https://www.zenhub.com/)
