### ISSUE TITLE
[Beta] Typos within React Challenge

### ISSUE THREAD

**Issue by kgalang** [freeCodeCamp/freeCodeCamp#16567]
#### Challenge Name
React: Use Advanced JavaScript in React Render Method

https://beta.freecodecamp.org/en/challenges/react/use-advanced-javascript-in-react-render-method

#### Issue Description

There are a few typos in the instructions and tests of this challenge. It instructs you to change the incorrect line number and also the tests spell "components" incorrectly.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

<img width="960" alt="screen shot 2018-01-24 at 11 57 57 am" src="https://user-images.githubusercontent.com/18174574/35345569-fb53486c-00fd-11e8-9f1b-f9c7e0c877eb.png">
<img width="482" alt="screen shot 2018-01-24 at 11 58 15 am" src="https://user-images.githubusercontent.com/18174574/35345575-021648ca-00fe-11e8-8eea-6bb0ce70a9e1.png">

**Comment by kgalang** [comment]
Please let me know if you guys would prefer that in the future I just resolve these types of issues myself. I just figured they are inviting issues for first timers.

**Comment by erictleung** [comment]
@kgalang thanks for reporting this error! You're always free to take care of issues yourself, but you're more than welcome to offer this opportunity for first-time contributors :smile: Let us know what you want to do, no pressure.

**Comment by raisedadead** [comment]
@erictleung actually we had requested @kgalang for these first timer issues

**Comment by kgalang** [comment]
@204070 sure! Especially if you're a first timer, feel free to :)

**Comment by pooranp** [comment]
Hi @kgalang , I'm a beginner and I was wondering if I'm allowed to work on this if it's already been requested by another user. I ask because this issue is still labeled with a 'help wanted' tag.
