### ISSUE TITLE
Challenge not completing when proper work is shown

### ISSUE THREAD

**Issue by JonathanKreiter** [FreeCodeCamp/freecodecamp#1656]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue.

![image](https://cloud.githubusercontent.com/assets/12437314/9148483/63a65ebe-3d32-11e5-860e-f53b428d63cd.png)

Completed objectives, only to have them not be show as such in browser. Please Fix!

**Comment by kurzninja** [comment]
The test for checking the color was checking for the wrong RGB value. I have corrected it in https://github.com/FreeCodeCamp/freecodecamp/pull/1706.
