### ISSUE TITLE
Profile appears reset, cannot see certificate anywhere after completion

### ISSUE THREAD

**Issue by jeremiahfernandezzzz** [freeCodeCamp/freeCodeCamp#16576]
#### Challenge Name

https://www.freecodecamp.org/jeremiahfernandezzzz

#### Issue Description

I have just completed all the challenges for the Back End Web Development Certification, including the last step which is "Your Back End Development Certificate", but my certificate does not appear on my profile. When i try to access the url where the certificate is supposed to be (freecodecamp.com/jeremiahfernandezzzz/back-end-certification), it just says that i haven't agreed to the Academic Honesty Pledge, which I already did, as part of the last step.
Also, a few days before finishing my last challenge, my profile page looks like it has been reset, with only one challenge listed, which isn't part of the certificate, and my points (or score?) were reduced to [2]. On the top navigation bar, however, it shows that my points were at [24]. My finished challenges were also checked just fine on the map.

#### Browser Information

* Browser Name, Version: Google Chrome Version 63.0.3239.132 (Official Build) 
* Operating System: Windows 7 Ultimate SP1 (64-bit)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```
#### Screenshot

![issue](https://user-images.githubusercontent.com/22298005/35421729-cadbfe62-027f-11e8-8ffb-f5225061498e.png)

**Comment by raisedadead** [comment]
Looks like there is a duplicate account accidentally created. @QuincyLarson can you please take a look? 

/cc @BerkeleyTrue Is this still a recurring occurence?

**Comment by QuincyLarson** [comment]
@jeremiahfernandezzzz There was a duplicate account that was somehow blocking your account. I've deleted it, and it seems to be fixed. @raisedadead I'm not sure what caused these duplicate accounts in the past but we get fewer and fewer issues related to them with time.

**Comment by jeremiahfernandezzzz** [comment]
thanks guys!
