### ISSUE TITLE
Beta - Basic Javascript #35 Find Numbers... -missing a semicolon

### ISSUE THREAD

**Issue by sonorangirl** [FreeCodeCamp/FreeCodeCamp#1657]
Challenge http://beta.freecodecamp.com/challenges/waypoint-find-numbers-with-regular-expressions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Your Do Not Modify code is missing a semicolon
<img width="881" alt="screen shot 2015-08-07 at 7 24 27 pm" src="https://cloud.githubusercontent.com/assets/6051437/9148678/45f75c44-3d3a-11e5-9347-b2b229d8096a.png">

**Comment by benmcmahon100** [comment]
This no longer seems to be an issue
