### ISSUE TITLE
(Beta Version) - Add Labels to Scatter Plot Circles

### ISSUE THREAD

**Issue by ukirderohit** [freeCodeCamp/freeCodeCamp#16588]
#### Data Visualization with D3: Add Labels to Scatter Plot Circles

https://beta.freecodecamp.org/en/challenges/data-visualization-with-d3/add-labels-to-scatter-plot-circles

#### Issue Description

When Inspecting the SVG elements the console shows right data but the test fails.
(See ScreenShots)
#### Browser Information

* Google Chrome, Version: 63.0.3239.132 (Official Build) (64-bit
* Operating System: MACOS
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

<body>
  <script>
    const dataset = [
                  [ 34,    78 ],
                  [ 109,   280 ],
                  [ 310,   120 ],
                  [ 79,    411 ],
                  [ 420,   220 ],
                  [ 233,   145 ],
                  [ 333,   96 ],
                  [ 222,   333 ],
                  [ 78,    320 ],
                  [ 21,    123 ]
                ];
    
    
    const w = 500;
    const h = 500;
    
    const svg = d3.select("body")
                  .append("svg")
                  .attr("width", w)
                  .attr("height", h);
    
    svg.selectAll("circle")
       .data(dataset)
       .enter()
       .append("circle")
       .attr("cx", (d, i) => d[0])
       .attr("cy", (d, i) => h - d[1])
       .attr("r", 5);
    
    svg.selectAll("text")
       .data(dataset)
       .enter()
       .append("text")
       // Add your code below this line
       .attr("x", (d) => d[0]+5)
       .attr("y", (d) => h - d[1])
       .text((d) => d);
       // Add your code above this line
  </script>
</body>



```
#### Screenshot

![test1](https://user-images.githubusercontent.com/16518829/35474487-cbe09984-035c-11e8-9520-4ec5d817f904.png)
![test2](https://user-images.githubusercontent.com/16518829/35474488-cbf02390-035c-11e8-9be5-7937ecb6c743.png)

**Comment by ninadingole** [comment]
The Text needs to be of format `34,<space>70`, but in this case, there is no space after comma. Could you try adding space to the text and run the example again.

**Comment by ukirderohit** [comment]
Yeah It Worked !! Thanks

**Comment by manoj10101996** [comment]
Perfect solution:
            Understand the scenario visualize it. Its not properly placed when we plot so we have increase **x** attribute value by **5** so it will visualized properly.

Programmer thinks ... </>


<body>
  <script>
    const dataset = [
                  [ 34,    78 ],
                  [ 109,   280 ],
                  [ 310,   120 ],
                  [ 79,    411 ],
                  [ 420,   220 ],
                  [ 233,   145 ],
                  [ 333,   96 ],
                  [ 222,   333 ],
                  [ 78,    320 ],
                  [ 21,    123 ]
                ];
    
    
    const w = 500;
    const h = 500; 
    const svg = d3.select("body")
                  .append("svg")
                  .attr("width", w)
                  .attr("height", h);
    
    svg.selectAll("circle")
       .data(dataset)
       .enter()
       .append("circle")
       .attr("cx", (d, i) => d[0])
       .attr("cy", (d, i) => h - d[1])
       .attr("r", 5);
    
    svg.selectAll("text")
       .data(dataset)
       .enter()  .append("text")
       
       // Add your code below this line
       
       .text((d) => (d[0] + ", " + d[1])) 
      **//The thing is the x attribute should be increase by 5 more.**
       .attr("x", (d, i) => d[0]+**5**)
       .attr("y", (d, i) => h - d[1])
       
       
       // Add your code above this line
  </script>
</body>

**Comment by RandellDawson** [comment]
@manoj10101996 GitHub issues are meant for discussing actual problems with our platform and not posting solutions.
