### ISSUE TITLE
[Beta] In Firefox setting page can't align properly with navigation bar.

### ISSUE THREAD

**Issue by momitrahman** [freeCodeCamp/freeCodeCamp#16587]
This alignment problem happen only in setting page. Its happen when browser zoom set in more than 40% and current monitor resolution set in 1920 * 1080 (16:9). But in 40% zoom setting page is harder to read. For more details please check below screenshots. 
### Set in 40% zoom
![40 _zoom](https://user-images.githubusercontent.com/11898284/35473253-7731adc4-03a7-11e8-8a93-056c8ad14d4a.png)
### Set in 100% zoom
![100 _zoom](https://user-images.githubusercontent.com/11898284/35473254-777018c0-03a7-11e8-8a75-c1f3d25e1513.png)

Current Environment: 
* Browser Name, Version:  Firefox 58
* Operating System: Linux Mint 18.3
* Mobile, Desktop, or Tablet: Desktop with 21.5" Monitor

**Comment by raisedadead** [comment]
Just to confirm, in the 100% zoom, could you try a refresh and check that this is alignment still exists?

**Comment by momitrahman** [comment]
Yes it still exists after normal and hard refresh.

**Comment by Bouncey** [comment]
Thanks for the issue @momitrahman 

This has already been addressed in a current PR #16412 


Happy coding!
