### ISSUE TITLE
[Beta] On site code editor and page not working when reloading/refreshing react challenge

### ISSUE THREAD

**Issue by kgalang** [freeCodeCamp/freeCodeCamp#16581]
#### Challenge Name
React: Use Array.filter() to Dynamically Filter an Array

https://beta.freecodecamp.org/en/challenges/react/use-arrayfilter-to-dynamically-filter-an-array

#### Issue Description

On the above challenge, when you reload or refresh the page, the on site code editor doesn't load and stays on the black shimmering type animation and the formatting of the instructions change. Also, none of the buttons work except for the ones with an href attribute with an outside link.

I have been able to reproduce this this on my three browsers of Chrome, Firefox, and Safari.
#### Browser Information

* Browser Name, Version: 

- Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- Mozilla Firefox Quantum 57.0.4 (64-bit)
- Apple Safari Version 11.0.2 (13604.4.7.1.3)

* Operating System: Mac OS High Sierra 10.13.2
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```
#### Screenshot

<img width="1440" alt="screen shot 2018-01-26 at 11 32 15 am" src="https://user-images.githubusercontent.com/18174574/35450030-c9277274-028c-11e8-91cf-c781c49da200.png">
<img width="361" alt="screen shot 2018-01-26 at 11 32 48 am" src="https://user-images.githubusercontent.com/18174574/35450050-d6e9e46e-028c-11e8-91a5-dd4ecfd9868a.png">
<img width="364" alt="screen shot 2018-01-26 at 11 32 56 am" src="https://user-images.githubusercontent.com/18174574/35450055-daf071d6-028c-11e8-9f1e-c92a666ad58f.png">

**Comment by jkao1** [comment]
Alright if I open a PR to this?
