### ISSUE TITLE
Update email settings

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16599]
![cursor_and_settings___freecodecamp](https://user-images.githubusercontent.com/985197/35522814-f3e3426a-04e2-11e8-8e64-7c5ec2b7c954.png)

**Comment by ninadingole** [comment]
I have the lastest pull of `staging` branch, however, I still don't see the first "Allow people to send me email" option. Otherwise, I could try working on this change.

**Comment by Bouncey** [comment]
@ninadingole this issue as raised as part of a PR review. I should have added the in progress label sooner

Sorry for the confusion

**Comment by akhil070** [comment]
Good
