### ISSUE TITLE
[Beta]Link to Internal Sections of a Page with Anchor Elements

### ISSUE THREAD

**Issue by anirudh991** [freeCodeCamp/freeCodeCamp#16590]
#### Challenge Name
Link to Internal Sections of a Page with Anchor Elements in Beta version

#### Link to the challenge
https://beta.freecodecamp.org/en/challenges/basic-html-and-html5/link-to-internal-sections-of-a-page-with-anchor-elements

#### Issue Description
I've tried my code locally and it was working right, but not on freecodecamp challenge preview.
![screenshot from 2018-01-28 13-10-06](https://user-images.githubusercontent.com/16043410/35480060-9592af5e-042c-11e8-973c-78dc49aa20fb.png)

#### Browser Information
* Browser Name, Version: Opera 50.0.2762.58
* Operating System: LInux MInt 18.3, 64bit
* Mobile or Tablet: None 

#### Your Code
```
<h2>CatPhotoApp</h2>
<main>
  
  <a href="#footer">cat photos</a>
  
  <img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">
  
  <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff. Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  <p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff. Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
  <p>Meowwww loved it, hated it, loved it, hated it yet spill litter box, scratch at owner, destroy all furniture, especially couch or lay on arms while you're using the keyboard. Missing until dinner time toy mouse squeak roll over. With tail in the air lounge in doorway. Man running from cops stops to pet cats, goes to jail.</p>
  <p>Intently stare at the same spot poop in the plant pot but kitten is playing with dead mouse. Get video posted to internet for chasing red dot leave fur on owners clothes meow to be let out and mesmerizing birds leave fur on owners clothes or favor packaging over toy so purr for no reason. Meow to be let out play time intently sniff hand run outside as soon as door open yet destroy couch.</p>
  
</main>
  
<footer id="footer">Copyright Cat Photo App</footer>
```
#### Screenshot
![screenshot from 2018-01-28 12-55-46](https://user-images.githubusercontent.com/16043410/35480003-a3e15ee0-042a-11e8-819f-cc8f90e82947.png)

**Comment by ninadingole** [comment]
@anirudh991 You have to change your anchor tag Text to `Jump to Bottom` it will work.

**Comment by raisedadead** [comment]
> I've tried my code locally and it was working right, but not on freecodecamp challenge preview.

**Comment by raisedadead** [comment]
> I've tried my code locally and it was working right, but not on freecodecamp challenge preview.

@anirudh991 can you elaborate, also please confirm with the forum and/or chat others are facing this?

**Comment by anirudh991** [comment]
Ah I was such a Idiot, Thanks @ninadingole I've corrected it
