### ISSUE TITLE
Wiki article request: Basejump starter guide/resources

### ISSUE THREAD

**Issue by 1hella** [FreeCodeCamp/FreeCodeCamp#1660]
I've noticed tons of people have trouble getting started on the basejumps, myself included.

It would be good to have a wiki article with a lot of helpful resources to get going.

For example, something like this:
#### Reference Guides
- [Intro to Yeoman Angular-Fullstack Basejumps](https://github.com/clnhll/guidetobasejumps)
- [Mongo Shell Quick Reference](http://docs.mongodb.org/manual/reference/mongo-shell/)

#### Courses
- [M101JS: MongoDB For Node.JS Developers](https://university.mongodb.com/courses/M101JS/about)
- [A Better Way to Learn AngularJS](https://thinkster.io/a-better-way-to-learn-angularjs/)
- [Learn AngularJS – Codecademy](https://www.codecademy.com/en/courses/learn-angularjs)

#### Tutorials
- [Clementine.js Beginner Tutorial](http://johnstonbl01.github.io/clementinejs/tutorials/tutorial-beginner.html)
- [Using mongoose.js in node and mongoDB applications](https://scotch.io/tutorials/using-mongoosejs-in-node-js-and-mongodb-applications)
- [Setting Up a MEAN Stack Single Page Application](https://scotch.io/tutorials/setting-up-a-mean-stack-single-page-application)
- [Pretty much anything on scotch.io](https://scotch.io/tag/mean)
- [Building an Angular + Node Comment App using Yeoman](http://tylerhenkel.com/building-an-angular-node-comment-app-using-yeoman/)

**Comment by rrandom** [comment]
+1

**Comment by AkiraLaine** [comment]
@1hella I was going to create a Wki for getting started with Basejumps. But do you want to do it or should I?

**Comment by 1hella** [comment]
@AkiraLaine You can go ahead. I haven't made it through any base jumps yet.

**Comment by 1hella** [comment]
Someone made it here https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Basejump-Resources
