### ISSUE TITLE
Understanding Case Sensitivity in Variables

### ISSUE THREAD

**Issue by Pinoy2400** [freeCodeCamp/freeCodeCamp#16601]
<img width="1240" alt="skaermbillede 2018-01-29 kl 23 02 03" src="https://user-images.githubusercontent.com/31646338/35536871-74863106-0548-11e8-85ad-26906482bec1.png">

Please help, what is missing here? I can't understand this..

**Comment by bennett-elder** [comment]
camelCase is used on line 10 but PascalCase is used on line 5. In case-sensitive languages like JavaScript that makes them different variables. Try resetting the code to start from the beginning and make the tests pass one at a time. You got this.

A better area to get more help with exercises like that is the [Help with JavaScript](https://gitter.im/FreeCodeCamp/HelpJavaScript) gitter chatroom. The area we're in right now is to raise issues with the underlying code of freeCodeCamp itself. :)

**Comment by raisedadead** [comment]
Hi @Pinoy2400 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
