### ISSUE TITLE
'Add my LinkedIn to my profile' button not working

### ISSUE THREAD

**Issue by SarahCrowe** [freeCodeCamp/freeCodeCamp#16607]
Hello. I am having trouble adding my LinkedIn to my FreeCodeCamp profile. When I click on the ‘Add my LinkedIn to my profile’ button I get taken to the most recent challenge that I was working on. When I go back to my profile page on FCC, the add LinkedIn button is still there and my LinkedIn has not been added. Please can someone help? Thanks

**Comment by Asjas** [comment]
Hi @SarahCrowe 

This seems to have been reported in issue #16273 and #14652. Currently it is in the process of being removed in favour of just having campers paste in the link to their LinkedIn and Twitter profiles manually.

**Comment by SarahCrowe** [comment]
Thanks @Asjas
