### ISSUE TITLE
Access an Array's Contents: Correct Answer, but Error so not Scoring

### ISSUE THREAD

**Issue by kodster28** [freeCodeCamp/freeCodeCamp#16602]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/basic-data-structures/access-an-arrays-contents-using-bracket-notation

#### Issue Description

Input any correct answer into the coding pane (true, 'c', 7) and the system will pass me through to the next challenge and give a green check, but then say, "Something went wrong, please try again later.' No credit is given.

#### Browser Information

* Browser Name, Version: Chrome, 63.0.3239.132; Firefox, 58.0.1
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

function mixedNumbers(arr) {
  // change code below this line
  arr.push(7, 'VIII', 9);
  arr.unshift('I', 2, 'three');
  // change code above this line
  return arr;
}

// do not change code below this line
console.log(mixedNumbers(['IV', 5, 'six']));



```
#### Screenshot

![freecodecamp1](https://user-images.githubusercontent.com/26727299/35541268-8f4e74fe-051f-11e8-9a9d-ba926e5a9675.png)
![freecodecamp2](https://user-images.githubusercontent.com/26727299/35541269-8f5e6b20-051f-11e8-9466-3799ef50ec2e.png)

**Comment by raisedadead** [comment]
I am unable to reproduce this, strangely. The error about "Something went wrong..." could be unrelated to the challenge itself.

Can you please take a screenshot of your DevTools console?
On Chrome, press <kbd>F12</kbd>, switch to the Console tab on the DevTools panel, see if there are errors in red?

**Comment by kodster28** [comment]
Oh, that is so weird!

It fixed itself today. So I guess I'm unable to reproduce the error as well?

Thank you for the prompt response!

**Comment by raisedadead** [comment]
Great, thanks for letting us know. Please open a fresh issue if you get this in future.
