### ISSUE TITLE
Declare a Read-Only Variable with the const Keyword has an issue

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#16619]
The instructions on this challenge don't tie up with the tests. 

One test asserts that the word `sentence` in all caps, but other tests are looking for a declaration of `str2`.

`str2` is not mentioned in the instructions.

There is a note saying that using all caps for `const` declarations is a common practise, this can be removed.

**Comment by vkWeb** [comment]
@Bouncey I think you forgot to put the challenge's link. Please update this issue.

**Comment by alanmathew6711251** [comment]
j
