### ISSUE TITLE
[Beta] 'Email-us' button in settings has the old 'team@freeCodeCamp.com' Email-ID

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16613]
### Issue Description
The Settings page has the old `team@freeCodeCamp.com` email address in the `email-us` button. I think it should be updated to `team@freeCodeCamp.org`. 
@raisedadead Your thoughts on this?  
![issue](https://user-images.githubusercontent.com/26724128/35627094-dc2dae58-06bd-11e8-8e4d-404b4f9a9d08.PNG)

### Browser Information

* Browser Name, Version: Chrome and Firefox (latest release).
* Operating System: Windows 10 Pro 32 Bit.
* Mobile, Desktop, or Tablet: Desktop.

**Comment by raisedadead** [comment]
The button is actually to be removed completely.

**Comment by gracemgately** [comment]
Hi! I'd like to work on this issue. I was looking at the code and the href attribute doesn't seem to be working (maybe it was supposed to be a `mailto`?) -- I just want to make sure this is intentional and that it should all be removed regardless.

**Comment by raisedadead** [comment]
Yes, this button is to be removed completely

**Comment by vkWeb** [comment]
Great.
