### ISSUE TITLE
Can't add Google+ account to my profile

### ISSUE THREAD

**Issue by HasanSakr** [freeCodeCamp/freeCodeCamp#16610]
I've got an account on your site and I've successfully added GitHub, Twitter and Linkedin to my profile, but it seems that the G+ account not found in my profile settings!

**Comment by Bouncey** [comment]
@HasanSakr Thanks for the issue. Are you maybe talking about signing in with google? I don't remember having G+ account linking feature.

**Comment by HasanSakr** [comment]
I mean that some profiles linked are linked to Facebook and Google plus.
Maybe the feature of adding Facebook and G+ to FCC account have been
removed.
Thank you Stuart

On Jan 31, 2018 11:47 AM, "Stuart Taylor" <notifications@github.com> wrote:

@HasanSakr <https://github.com/hasansakr> Thanks for the issue. Are you
maybe talking about signing in with google? I don't remember having G+
account linking feature.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/16610#issuecomment-361877650>,
or mute the thread

**Comment by raisedadead** [comment]
Yes, we are deprecating all social logins. And with beta, you will be able to add a profile, as you with just the link to your profile.

As for sign in, make sure you have your email updated with us. We will use that by default for sign in, etc.

Thanks.
