### ISSUE TITLE
Codepen Random Quote machine does not work anymore

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/freeCodeCamp#16620]
The Random Quote Machine Codepen example doesn't work any more. 

https://codepen.io/freeCodeCamp/pen/qRZeGZ

It looks like all the JavaScript in the CodePen was deleted. 

The CodePen was recently updated and was working, so this must have been done in the last few weeks. The only backup we have is the older version which gets quotes from an API. Is there any way to have CodePen restore the most recent version with the JavaScript, or do we have a backup somewhere else?

**Comment by raisedadead** [comment]
Hi @tchaffee I can update this pen, can you fork/share a working copy?

**Comment by justinemar** [comment]
Here's the cached page of the pen.

[google cached](https://webcache.googleusercontent.com/search?q=cache:dRAKeWMDmO8J:https://codepen.io/freeCodeCamp/pen/qRZeGZ+&cd=1&hl=en&ct=clnk&gl=ph)

**Comment by raisedadead** [comment]
Fixed.

@justinemar thanks a lot for sharing this.

**Comment by tchaffee** [comment]
The restored js is actually an older version. I recently updated the CodePen to use data from our own gist since the API was slow and breaking our tests. See https://github.com/freeCodeCamp/testable-projects-fcc/issues/218. Can you please re-open this issue and I will make those changes again, from memory.

Going forward, any ideas on how we can backup these pens in case the code gets clobbered again? This article looks promising. https://blog.codepen.io/2016/09/19/using-gists-see-versions-pens-dif-pen-changes/

**Comment by raisedadead** [comment]
Well one way would be to create a curriculum directory and Pen sub-directories on the testable project repo. The Pen sub-directories can have 3 files for the Pen.

This way it will be version controlled?

**Comment by raisedadead** [comment]
Although, we are working towards being able to do this ourselves, on beta, as you maybe aware. So if its worth investing the effort is a real question.

I am okay with the versioning on GitHub though. Gists are a bit tedious to manage.

**Comment by tchaffee** [comment]
For the time being I will create sub-directories in the testable project repo. Thanks for the suggestion.

**Comment by tchaffee** [comment]
I found the most recent code for this in my own fork of the pen. It's fixed now in the official version. I will open an issue in the testable projects repo to back up all the source for all the CodePens.
