### ISSUE TITLE
[Beta] Map view doesn't expand when accessing through a deep link

### ISSUE THREAD

**Issue by arielcamus** [freeCodeCamp/freeCodeCamp#16628]
#### Issue Description
When I click on a deep link (e.g. link to first challenge in Regular Expressions section), the website loads the corresponding challenge, but the map on the sidebar doesn't expand to show the corresponding challenge.

To replicate the issue just click on the following link:
https://beta.freecodecamp.org/en/challenges/regular-expressions/introduction-to-the-regular-expression-challenges

#### Browser Information
* Browser Name, Version: Chrome v63.0.3239.132
* Operating System: macOS High Sierra
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot
[Collapsed map](https://www.dropbox.com/s/w6w2duklkykkc1a/Screenshot%202018-02-03%2019.42.35.png?dl=0)

**Comment by raisedadead** [comment]
Hi, 

Thanks for reporting.

Could you try and post the screenshot of your DevTools? On a Chrome browser, on Mac you can do with <kbd>⌘</kbd> + <kbd>⌥</kbd> + <kbd>I</kbd>.

On the Dev tools widow, switch to the console tab, and see if errors are reported in red.

You can drag drop images, here in the comment box directly.

**Comment by vkWeb** [comment]
@raisedadead This seems like a duplicate of issue #16248 and PR #16531 will close the issue.

**Comment by arielcamus** [comment]
@vkWeb you are totally right. Glad to hear someone is working on fixing that already.
