### ISSUE TITLE
Debugging challenges don't mark as completed

### ISSUE THREAD

**Issue by zk433** [freeCodeCamp/freeCodeCamp#16622]
#### Challenge Name

[Debugging](https://beta.freecodecamp.org/en/challenges/debugging/introduction-to-the-debugging-challenges)

#### Issue Description

The first two challenges (Introduction to Debugging Challenges and Use the JavaScript Console to Check the Value of a Variable) don't mark as 'done' upon completing. 

#### Browser Information

* Browser Name, Version: Chrome, version 63.0.3239.132 (Official Build) (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![screenshot](https://user-images.githubusercontent.com/15965102/35736324-8690f582-081f-11e8-99d2-a5cb9a87076b.png)

**Comment by Asjas** [comment]
Hi @zk433. 

Thank you for reporting this.

I just confirmed by testing this on `beta.freecodecamp.org` and mine doesn't mark the challenge as done either.

**Comment by Asjas** [comment]
I tested this locally and it seems to be marking the challenge as done. I wonder if it was patched in a PR and hasn't been pushed to prod yet. One of the freecodecamp team will know if it has been fixed.

**Comment by raisedadead** [comment]
Strange it works for me:

![image](https://user-images.githubusercontent.com/1884376/35753407-a599e054-0885-11e8-8851-b23cff16fe6a.png)

**Comment by raisedadead** [comment]
Could be a Windows specific issue?

**Comment by huyenltnguyen** [comment]
I'm able to reproduce this issue on both live and local versions. It occurs when user is not logged in, and it's not just for the Debugging section but for the entire curriculum. Could this have something to do with localStorage or something like that?

**Comment by zk433** [comment]
I am logged in when I have the issue.
@raisedadead it's possible, I have Windows. @Asjas , @huyenltnguyen , what OS are you using?

**Comment by huyenltnguyen** [comment]
@zk433 I'm on Windows too.
I just did a quick check on the official FCC, the completed challenges don't get marked if I'm not signed in. So this is by design then, which means... nope, I can't reproduce it.

**Comment by Asjas** [comment]
I tested this on Windows 10 and Linux Mint. Neither completes the challenges for me.

**Comment by raisedadead** [comment]
Hi @zk433 @Asjas could you check and report if there are any errors in your browser DevTools console?

**Comment by Asjas** [comment]
@raisedadead This is the only thing I get in the DevTool Console.

Chrome
```
DOMPropertyOperations.js:139 Mixed Content: The page at 
'https://beta.freecodecamp.org/en/challenges/debugging/introduction-to-the-debugging-challenges' 
was loaded over HTTPS, but requested an insecure image 'http://imgs.xkcd.com/comics/debugging.png'. 
This content should also be served over HTTPS.

[Violation] 'click' handler took 197ms
[Violation] Forced reflow while executing JavaScript took 75ms
```

FF Dev Edition
```
Content Security Policy: The page’s settings blocked the loading
of a resource at data:application/javascript;base64,KGZ1b... (“script-src”).
```

**Comment by zk433** [comment]
@raisedadead  strangely, the challenges now mark as complete. I don't know why and what has changed, but it works on my side now.

**Comment by vkWeb** [comment]
@raisedadead I tried reproducing this, there are two cases: 
- When I'm signed-in
The challenge gets completed and there's a tick mark on the map's block.
- When I'm not signed-in
The challenge gets completed but there's no tick mark on the map's block.

To reproduce, follow the below steps: 
1. Open Incognito tab and try the challenges. They'll pass but they'll not be shown as completed on the map. 
2. Sign-in to your account and then try the challenges again, everything works fine.

**Comment by raisedadead** [comment]
> When I'm not signed-in
> The challenge gets completed but there's no tick mark on the map's block.

This behaviour is expected.

**Comment by systimotic** [comment]
Works for me as well on Windows. I'll assume this has been fixed, as it can no longer be reproduced. If anybody else does still run into this issue, please leave a comment here.

Happy coding!
