### ISSUE TITLE
[Beta] Solution doesn't pass for challenge "React: Use a Ternary Expression for Conditional Rendering"

### ISSUE THREAD

**Issue by antonshevyrin** [freeCodeCamp/freeCodeCamp#16636]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/react/use-a-ternary-expression-for-conditional-rendering

#### Issue Description

Correct solution doesn't pass. Behavior of "Preview" page matches challenge description but these tests don't pass:

- When a number of less than 18 is entered into the input element and the button is clicked, the button's inner text should read You Shall Not Pass. };
- When a number greater than or equal to 18 is entered into the input element and the button is clicked, the button's inner text should read You May Enter. };
- Once a number has been submitted, and the value of the input is once again changed, the button should return to reading Submit. };

#### Browser Information

* Browser Name, Version: Chrome, Version 64.0.3282.140 (Official Build) (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

const inputStyle = {
  width: 235,
  margin: 5
}

class CheckUserAge extends React.Component {
  constructor(props) {
    super(props);
    // change code below this line
    this.state = {
      input: '',
      userAge: ''
    };
    // change code above this line
    this.submit = this.submit.bind(this);
    this.handleChange = this.handleChange.bind(this);
  }
  handleChange(e) {
    this.setState({
      input: e.target.value,
      userAge: ''
    });
  }
  submit() {
    this.setState({
      userAge: this.state.input
    });
  }
  render() {
    const buttonOne = <button onClick={this.submit}>Submit</button>;
    const buttonTwo = <button>You May Enter</button>;
    const buttonThree = <button>You Shall Not Pass</button>;

    return (
      <div>
        <h3>Enter Your Age to Continue</h3>
        <input
          style={inputStyle}
          type="number"
          value={this.state.input}
          onChange={this.handleChange} /><br />
        {
          
          /* change code here */
          this.state.userAge.length > 0 ? (this.state.input < 18 ? buttonThree : buttonTwo) : buttonOne
        }
      </div>
    );
  }
};
```
#### Screenshot

<img width="422" alt="react-use-a-ternary-expression-for-conditional-rendering" src="https://user-images.githubusercontent.com/807405/35778807-3bc4bb48-09cc-11e8-994c-3a475a7823f3.png">

**Comment by jkao1** [comment]
`this.state.input` is a string, and you cannot compare it to the integer 18.

In JavaScript, strings are compared lexicographically (you can think of this as a fancier version of alphabetical ordering, the difference being that alphabetic ordering only covers the 26 characters a through z). Here are a few examples:
```js
// true (we follow alphabetical order here)
console.log("a" < "b")

// true (since the first characters of both strings are equal, we look at the next one, and "a" < "b".)
console.log("aa" < "ab") 

// true
console.log("1" < "3")

// false, because "2" comes after "1".
console.log("2" < "10")

**Comment by jkao1** [comment]
I'll take a look at the tests and open a PR.

**Comment by jkao1** [comment]
I've opened a pull request to fix these tests.

**Comment by antonshevyrin** [comment]
@jkao1 thanks for explaining and for fixing :+1:

**Comment by jkao1** [comment]
@antonshevyrin anytime :smiley:

**Comment by raisedadead** [comment]
Hi guys, thanks for taking the time to report and fix, we will get this reviewed soon.

Happy contributing!

**Comment by Randore** [comment]
Hi, why this solution is not working.
It's working fine if I enter a value greater than 18 but fails when I enter a value lesser than 18.

```
{
      (this.state.userAge >= 18) ? buttonTwo : buttonThree && buttonOne
}
```

**Comment by Dhrumil1808** [comment]
@Randore  it won't work for values lesser than 18 as it this is an invalid expression (buttonThree  && buttonOne)

Instead, try the below solution :
 { (this.state.userAge == '' ? buttonOne: (this.state.input < 18 ? buttonThree : buttonTwo)  }
