### ISSUE TITLE
cant get the background image to work with (section.main aside.content.trending) it wont show

### ISSUE THREAD

**Issue by cairotx** [freeCodeCamp/freeCodeCamp#16634]
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Creating a Responsive Web Design</title>
<link rel="stylesheet" type="text/css" media="screen" href="css/screen.css">
</head>
<body>
<div id="page">
  <header> <a class="logo" title="myLogo" href="http://codifydesign.com" ><span>Everyday things</span></a>
    <div class="hero">
      <h1>Add interest of natural texture</h1>
      <a class="btn" title="Get advice from top designers" href="#">Get advice from top designers</a> </div>
  </header>
  <section class="main">
    <aside>
      <div class="content trending">
        <h3><a href="#" class="logo">What&apos;s trending</a></h3>
        <p>Lorem ipsum dolor sit amet, consect etuer adipiscing elit. <a href="http://codifydesign.com">Morbi commodo</a>, ipsum sed pharetra gravida, orci magna rhoncus neque, id pulvinar odio lorem non turpis.</p>
      </div>
    </aside>
    <aside>
      <div class="content find-it">
        <h3><a href="#">Where to find it</a></h3>
        <p>Morbi commodo, ipsum sed pharetra gravida, orci magna rhoncus neque, id pulvinar odio lorem non turpis. Nullam sit amet enim. Lorem ipsum dolor sit amet, consect.</p>
      </div>
    </aside>
    <aside>
      <div class="content tools">
        <h3><a href="#">Tools of the trade</a></h3>
        <p>Nullam sit amet enim. Lorem ipsum dolor sit amet, consect etuer adipiscing elit. Morbi commodo, ipsum sed pharetra gravida, orci rhoncus neque, id pulvinar odio.</p>
      </div>
    </aside>
  </section>
  <section class="atmosphere">
    <article>
      <h2>Creating a modern atmosphere</h2>
      <p>Morbi commodo, ipsum sed pharetra gravida, orci magna rhoncus neque, id pulvinar odio lorem non turpis. Lorem ipsum dolor sit amet etuer adipiscing elit.  Pulvinar odio lorem non turpis. Nullam sit amet enim lorem.</p>
      <a class="btn" title="Creating a modern atmosphere" href="#">Learn More</a> </article>
  </section>
  <section class="how-to">
    <aside>
      <div class="content"> <img alt="chossing the proper seating" src="images/photo_seating.jpg">
        <h4>How-To: Seating</h4>
        <p>Consectetuer adipiscing elit. Morbi commodo ipsum sed gravida orci magna rhoncus pulvinar odio lorem.</p>
        <a title="Learn how to choose the proper seating." href="http://codifydesign.com">Learn more</a> </div>
    </aside>
    <aside>
      <div class="content"> <img alt="chossing the proper Lighting" src="images/photo_Lighting.jpg">
        <h4>How-To: Lighting</h4>
        <p>Morbi commodo, ipsum sed pharetra gravida magna rhoncus neque id pulvinar odio lorem non turpis nullam sit amet.</p>
        <a title="Learn how to choose the proper lighting." href="http://codifydesign.com">Learn more</a> </div>
    </aside>
    <blockquote>
      <p class="quote">Lorem ipsum dolor sit amet conse ctetuer adipiscing elit. Morbi comod sed dolor sit amet consect adipiscing elit.</p>
      <p class="credit"><strong>Author Name </strong><br>
        <em>Business Title <br>
        Company</em></p>
    </blockquote>
  </section>
  <nav>
    <ul>
      <li> <a title="About US" href="#">About US</a>
        <ul>
          <li> <a title="sublink1" href="#">sublink1</a> </li>
          <li> <a title="sublink2" href="#">sublink2</a> </li>
          <li> <a title="sublink3" href="#">sublink3</a> </li>
        </ul>
      </li>
      <li> <a title="Design Corner" href="#">Design Corner</a>
        <ul>
          <li> <a title="sublink1" href="#">sublink1</a> </li>
          <li> <a title="sublink2" href="#">sublink2</a> </li>
        </ul>
      </li>
      <li> <a title="Products" href="#">Products</a>
        <ul>
          <li> <a title="sublink1" href="#">sublink1</a>
            <ul>
              <li> <a title="sub sublink1" href="#">sub sublink1</a> </li>
              <li> <a title="sub sublink2" href="#">sub sublink2</a> </li>
            </ul>
          </li>
          <li> <a title="sublink2" href="#">sublink2</a>
            <ul>
              <li> <a title="sub sublink1" href="#">sub sublink1</a> </li>
              <li> <a title="sub sublink2" href="#">sub sublink2</a> </li>
            </ul>
          </li>
        </ul>
      </li>
      <li> <a title="Contact Us" href="#">Contact Us</a> </li>
    </ul>
  </nav>
  <footer> &copy; Everyday Things
    <div class="content"> <a title="Privacy policy" href="#">Privacy policy</a> <a title="Terms of Service" href="#">Terms of Service</a> </div>
  </footer>
</div>
</body>
</html>

CSS

@import url('https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,700');

body{
	font-family: 'Open Sans', sans-serif;
	font-size:16px;
	font-weight:300;
	color:#555;
	margin:0;
	padding:0;
	}
#page{ max-width:1200px; margin:0 auto; position:relative;
		
		}

/* Text*/
h1 {
margin:0 0 1em 0;
font-size:2.8em;
font-weight:700;
	
	
	
	
	}	
h2 {
margin:0 0 .5em 0;
font-size:1.6em;
font-weight:700;
line-height:1.1em;
}	
h3 {
margin:0 0 .5em 0;
font-size:1.3em;
font-weight:700;
}	
h3 {
margin:0 0 1.5em 0;
font-size:1em;
font-weight:700;
}
p{
	margin:0 0 1em 0;
}
a {
	color:#007eff;
	}
a:visited {
	color:#3F3;
	}
a.btn{
	font-size:1.2em; text-decoration:none; color:#fff; border: 1px solid #fff; padding:4px 15px; transition:background-color .5s;
	}
a.btn:hover{
	background-color:rgba(0,0,0,03);
	
	}	
	
		

/* Header*/
header{
	height:430px;
	background:#cf0004 url(../images/banner_1200.jpg) no-repeat center bottom;
	position:relative;
	
	}	
	
header a.logo{
	position:absolute; 
	display:block;
	width:160px;
	height:66px;
	background: url(../images/logo.svg) no-repeat 0 0; 
	background-size:contain;
	top:15px;
	left:20px;
	
	
	}	
	
header a.logo span{
	display:none;
	
	}	
header div.hero{
	position:absolute; width:42%; top:130px; left: 55%;
	}	
header div.hero h1{
	line-height:1em; margin: 0 0 30px 0; color:white;
	}
/* section-All*/	
section{ padding: 0 30px;
	
	}

	
/* section-main*/
	
section.main{
	margin-top:20px;
	margin-bottom:30px;
	padding:0;
	
	}	
section.main aside{
	width: 33%; float:left; text-align:center;
	}	

section.main .content{
	margin:15px;
	background:no-repeat center top; background-size: 75px 75px; padding-top:85px;
	
	}

section.main aside h3 a {
	color:000;
	text-decoration:none;
}
section.main aside h3 a:hover {
	text-decoration: underline;
	
}
section.main aside.content.trending{background-image:url(../images/icon_star.svg);}
section.main aside.content.find-it{background-image:url(../images/icon_marker.svg);}
section.main aside.content.tools{background-image:url(../images/icon_gear.svg);}

**Comment by raisedadead** [comment]
Hi there please submit a fresh issue using the issue template presented to you will creating one.
