### ISSUE TITLE
https://www.freecodecamp.org/challenges/no-repeats-please - not registering return value

### ISSUE THREAD

**Issue by clickingmouse** [freeCodeCamp/freeCodeCamp#16635]
#### Issue Description

it seems to not work, the auto check is not registering the return output from file... it registers if I hard code "return 2" and the auto check will register the 2, but it does not register any thing else such as return "Arr.length" or "return Arr[x]"

#### Browser Information

* Browser Name, Version:
Chrome Version 64.0.3282.119 (Official Build) (64-bit)
 Firfox 57.0.4 64bit
Safari
Version 11.0.2 (13604.4.7.1.3)
* Operating System: 
MacOS high sierrra
* Mobile, Desktop, or Tablet: 
Desktop
#### Your Code

```js

var count;
var globalPermuArr = [];
function print_swap(a, b, n) {
  var i;
  console.log("print_swap " + count++);
  //  printf("%5d ", count++);
  for (i = 0; i < n - 1; i++) {
    if (a == i) {
      console.log("|--");
    } else if (a < i && i < b) {
      console.log("---");
    } else {
      console.log("|  ");
    }
  }
  console.log("|");
}

function swap(str, a, b) {
 // console.log("preSwap:::"+str + "indexes "+a+" "+b +" stores ["+ str[a] +"] & [" + str[b] + "]");
  var t = str[a];
  str[a] = str[b];
  //console.log(str);
  str[b] = t;
  //console.log("afterSwap:::"+str+" :::t:::"+t);
}

function h(str, n, len) {
  var i;
  for (i = 0; ; i++) {
    if (n > 2) {
      h(str, n - 1, len);
    }
    if (i == n - 1) {
      break;
    }
    if (n % 2 == 0) {
      swap(str, i, n - 1);
      //print_swap(i, n - 1, len);
    } else {
      swap(str, 0, n - 1);
     // print_swap(0, n - 1, len);
    }
    
    console.log(str + ",,,,,,,,,,,,,,,,,,,,,, " + n);
    var str1 = str.join("");
    console.log("storing...."+str1);
    globalPermuArr[globalPermuArr.length]=str1;
  }
}

function heap(str, len) {
  if (len < 2) {
    console.log("The only permutation is \n" + str);
    return;
  }
  count = 1;
  print_swap(-1, -1, len);
  console.log("inside heap str:"+str);
  //printf(" %s\n", str);
  h(str, len, len);
}

function permAlone(str) {
  //  return str;
  //}
  //console.log(str);
  //int main() {
  //var str=[str.length];
  //  char s[MAX_LEN];
  var len;
  var tmpArr=[];
  console.log(typeof str);
  globalPermuArr[0] = str;
  //convert str to array
  arr=str.split("");
  console.log(arr);
  //Ss(s);
  for (len = 0; str[len] != null; len++);
  heap(arr, len);
  console.log("complete: "+arr);
  console.log(globalPermuArr);
  
  var finalArr= globalPermuArr;
  
  // filter the globalPermutationsArray
   var regex=/(.)\1/;
       //.{2}/;
  //(.)\1+
  var countPermu = 0;
  for(var x=0; x < finalArr.length; x++){
    console.log("filtering .." + globalPermuArr[x]);
    console.log(regex.test(finalArr[x]));
    if(  regex.test(finalArr[x]) === false ) {
      
      countPermu= countPermu+1;
      tmpArr[tmpArr.length]=finalArr[x];
    }
    
    //console.log(regex.test(finalArr));
  }
//  new RegExp(/ab+c/, 'i');
 
  
  
  //console.log(countPermu);
  return tmpArr.length;
//  return countPermu;
}

permAlone("aab");




```
#### Screenshot

![screen shot 2018-02-04 at 9 55 53 pm](https://user-images.githubusercontent.com/35300393/35778239-7c770888-09f6-11e8-9fe6-98b473cfbbf6.png)

**Comment by raisedadead** [comment]
Hi @clickingmouse thanks for reporting, and sorry about the delay in getting back to you.

Unfortunately, this is due the use of Global vars in your code, which is a limitation on our code editor. This is as per design.

So unless, specified you should not be using globals.

Because the tests run consecutively, and the last values of your globals.

A simple way to avoid globals (which is a good practice in real world too), is simply moving all you declarations including the functions inside your main function (which is `permAlone`) in this case.

That should do the trick.

Sorry, that we are going to have to close this. We are working towards supporting globals in our beta platform.

Happy coding!
