### ISSUE TITLE
FCC Forum is down - Internal Server 500 error

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16640]
#### Issue Description
freecodecamp forums are currently down.
receiving reports from users in chat
verified I am unable to access the forums

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/35782887-497f742a-09cd-11e8-8802-b83eaf070170.png)

**Comment by mstellaluna** [comment]
@QuincyLarson @BerkeleyTrue

**Comment by BerkeleyTrue** [comment]
Thanks for reporting @mstellaluna . I've pinged @QuincyLarson.

**Comment by BerkeleyTrue** [comment]
@QuincyLarson is aware and contacting discourse team.

**Comment by BerkeleyTrue** [comment]
discourse is working on getting the server up and running again.

**Comment by BerkeleyTrue** [comment]
We're back up!

Happy Coding!

**Comment by m-henderson** [comment]
good deal (:

**Comment by mstellaluna** [comment]
Thank you !! :)

**Comment by QuincyLarson** [comment]
Here's my quick explanation of what happened in case you're curious: https://forum.freecodecamp.org/t/why-the-forum-went-down-earlier-today/172818

**Comment by StubRavi** [comment]
Today this error has appeared again.
![freecodecamp 500](https://user-images.githubusercontent.com/34769076/49133708-04769100-f307-11e8-93d2-b21f806827e4.JPG)

**Comment by m-henderson** [comment]
@StubRavi could you please create a new issue for this? I am going to alert the others about hte issue.

**Comment by StubRavi** [comment]
Hey, @m-henderson , Thank you.
Now, It working normally. Hence, There is no need to further action.

**Comment by spidyhackx** [comment]
https://www.freecodecamp.org/forum/
is currently down.servers not working
![error](https://user-images.githubusercontent.com/40536205/51761183-4a13c800-20c4-11e9-9bc9-0c29f729faee.png)
