### ISSUE TITLE
BETA: Applied Accessibility: Improve Accessibility of Audio Content with the audio Element, not detecting closing </audio> tag.

### ISSUE THREAD

**Issue by akubie** [freeCodeCamp/freeCodeCamp#16645]
#### Applied Accessibility: Improve Accessibility of Audio Content with the audio Element

https://beta.freecodecamp.org/en/challenges/applied-accessibility/improve-accessibility-of-audio-content-with-the-audio-element

#### Issue Description

I tried to complete the task at hand. I believe it is done correctly, but it is saying that I still require a closing audio tag. You can see from the image below that I do have one in there and it is still not passing.

#### Browser Information

Note that this was performed in Chrome.
* Browser Name, Version: Chrome, latest version
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
<body>
  <header>
    <h1>Real Coding Ninjas</h1>
  </header>
  <main>
    <p>A sound clip of Zersiax's screen reader in action.</p>
  <audio controls>
    <source src="https://s3.amazonaws.com/freecodecamp/screen-reader.mp3" type="audio/mpeg" />    </audio>   
  </main>
</body>
```
#### Screenshot

![audio](https://user-images.githubusercontent.com/15224111/35822204-ad8d3862-0a68-11e8-8bfb-9ae0692d248b.jpg)

**Comment by SilentGamelan** [comment]
I also have this issue: receiving error message "cannot read property 'length' of null" and failing checks despite closing ```<audio>``` tag being in appropriate place.

![bug-audio_source_failing_checks](https://user-images.githubusercontent.com/28412081/35829326-72396450-0aba-11e8-8c90-a66d7eb1dacf.JPG)


**Browser Information**

- Browser Name, Version: Vivaldi 1.13.1008.44
- Operating System: Windows 10
- Mobile, Desktop, or Tablet: Desktop

**Comment by jkao1** [comment]
Isolated the error locally. I'll be opening a PR/fix later today.

**Comment by Herbertbhs02** [comment]
(Real Coding Ninjas)Audio closing tag still not detected!!!!

**Comment by NANAENGLISH** [comment]
SAME! It is not being detected. 

<body>
  <header>
    <h1>Real Coding Ninjas</h1>
  </header>
  <main>
    <p>A sound clip of Zersiax's screen reader in action.</p>
    <audio id="audio/mpeg" controls>
      <source src="https://s3.amazonaws.com/freecodecamp/screen-reader.mp3"type="audio/mpeg">   </audio>

    
</main>
</body>

**Comment by NANAENGLISH** [comment]
``<body>
  <header>
    <h1>Real Coding Ninjas</h1>
  </header>
  <main>
    <p>A sound clip of Zersiax's screen reader in action.</p>
    <audio id="audio/mpeg" controls>
      <source src="https://s3.amazonaws.com/freecodecamp/screen-reader.mp3"type="audio/mpeg">   </audio>

    
</main>
</body>
``

**Comment by NANAENGLISH** [comment]
`<body>
  <header>
    <h1>Real Coding Ninjas</h1>
  </header>
  <main>
    <p>A sound clip of Zersiax's screen reader in action.</p>
    <audio id="audio/mpeg" controls>
      <source src="https://s3.amazonaws.com/freecodecamp/screen-reader.mp3"type="audio/mpeg">   </audio>

    
</main>
</body>
`

**Comment by johanvl** [comment]
still not fixed

**Comment by bashkeyboard** [comment]
Ran into this same issue tonight. For everyone still having trouble, do not include an id attribute in your audio tag. It seemed to accept my answer after I removed the id attribute completely.

```
    <audio controls>
      <source src="https://s3.amazonaws.com/freecodecamp/screen-reader.mp3" type="audio/mpeg" />
    </audio>
```
