### ISSUE TITLE
BETA: Teaching negative margins

### ISSUE THREAD

**Issue by ReveurGAM** [freeCodeCamp/freeCodeCamp#16649]
#### Challenge Name
Basic CSS: Add a Negative Margin to an Element
https://beta.freecodecamp.org/en/challenges/basic-css/add-a-negative-margin-to-an-element

#### Issue Description
The current order of challenges teaches about margin, padding and border, then goes to negative margin sizes.  Wouldn't it be better to teach about the individual parts of margin (e.g. margin-bottom:0;), border and padding, and how using margin-[side] can accomplish the same effect before teaching this trick?

**Comment by raisedadead** [comment]
Agreed. These could be re-ordered. Thanks a lot for pointing out.

**Comment by Manish-Giri** [comment]
I'll take a look into this.

**Comment by QuincyLarson** [comment]
@Manish-Giri We just launched our new learning platform: learn.freecodecamp.org Do you think we still need to re-order these? If so, would you be interested in helping?

**Comment by Manish-Giri** [comment]
@QuincyLarson In the current lessons, negative margin (Basic CSS: Add a Negative Margin to an Element) is introduced right after margin (Basic CSS: Adjust the Margin of an Element) itself. Specifying different margins to each side of an element is introduced later. This order looks right to me. 

The final decision is up to you!

**Comment by QuincyLarson** [comment]
@Manish-Giri Thanks for your feedback. I agree that teaching reciprocal actions (positive VS negative margin) consecutively is fine. I don't think these need to be reordered either, so I'm going to close this issue. @ReveurGAM @raisedadead Thanks for chiming in with your opinions on this.
