### ISSUE TITLE
'Use strict' explanation missing

### ISSUE THREAD

**Issue by zk433** [freeCodeCamp/freeCodeCamp#16643]
#### Issue Description

In the ES6 challenges, there is  `"use strict"` included in the code. However, there is no explanation of its meaning or what it does anywhere.

I'd suggest a few sentences about 'use strict' should be included at the beginning of the section.

**Comment by jkao1** [comment]
I'll open a PR later today proposing a short explanation; hopefully it will run well with the moderators.

### For those with the same issue 
In short, `"use strict"` enables the "strict" mode. This mode catches common coding bloopers and "unsafe" actions (such as access to the global object).
```js
"use strict";
x = 3.14;  // This will cause an error because x is not declared
```
If you want a more in-depth explanation you should read [John Resig's article](https://johnresig.com/blog/ecmascript-5-strict-mode-json-and-more/) about JavaScript strict mode.

**Comment by jkao1** [comment]
I'd like to point out how my PR differs from #16650:
- **It provides an example.** Most JavaScript beginners do not understand what the "unsafe actions" in #16650 are; I provide a two-line code example (long enough to let the user understand, but short enough to not clutter the page with directions).
- **It is more sensibly worded.** The explanation in #16650 is not only a run-on sentence, but it also exhibits a misunderstanding of Strict Mode (inferred from incorrect usage of capitalization, quotes, and syntax).
- **The description location is correct.** My explanation is grouped with the introductory description of the challenge, unlike #16650's, which is grouped in the challenge instructions section.
