### ISSUE TITLE
map doesn't show my completed tasks

### ISSUE THREAD

**Issue by JainJuhi** [freeCodeCamp/freeCodeCamp#16657]
i logged on to freecodecamp after 10 days. And it doesn't show my comp[eted tasks on the map. it says i have completed only 25 tasks. i had actually completed 258 tasks. when i go to my profile it still shows 258 tasks completed.
**on map: 25
on profile:258
actually completed :258**
there is a bug, please fix it soon.

**Comment by QuincyLarson** [comment]
@JainJuhi It looks like this is now fixed so I'm closing this. https://www.freecodecamp.org/JainJuhi
