### ISSUE TITLE
BETA: separated margin & padding attributes taught, but clockwise notation accepted; minor formatting error too

### ISSUE THREAD

**Issue by ReveurGAM** [freeCodeCamp/freeCodeCamp#16651]
#### Challenge Name
Basic CSS: Add Different Padding to Each Side of an Element
https://beta.freecodecamp.org/en/challenges/basic-css/add-different-padding-to-each-side-of-an-element

Basic CSS: Add Different Margins to Each Side of an Element
https://beta.freecodecamp.org/en/challenges/basic-css/add-different-margins-to-each-side-of-an-element

Basic CSS: Use Clockwise Notation to Specify the Padding of an Element
https://beta.freecodecamp.org/en/challenges/basic-css/use-clockwise-notation-to-specify-the-padding-of-an-element

Basic CSS: Use Clockwise Notation to Specify the Margin of an Element
https://beta.freecodecamp.org/en/challenges/basic-css/use-clockwise-notation-to-specify-the-margin-of-an-element

#### Issue Description
The first two challenges teach individual property usage for borders and margins, while the last 2 teach clockwise notation.  I completed the first two using clockwise notation and my solutions were accepted, despite the goal of learning the long form.  If the goal is to have them use the long form, why accept the short form on the first two challenges?

Also, in the 4th challenge, for some reason the phrase "Clockwise Notation" is formatted as if it were part of a property, whereas it is correctly without formatting in the 3rd.

#### Screenshot
3rd challenge:
![image](https://user-images.githubusercontent.com/35181004/35829233-d1f0bb56-0a87-11e8-9ef6-816f4f7d999d.png)
4th challenge (note the incorrect formatting):
![image](https://user-images.githubusercontent.com/35181004/35829292-01adf8f4-0a88-11e8-935b-7bb56b16cb88.png)

**Comment by utkarshsingh99** [comment]
Instead of focussing on the solutions, we can remove the first two Challenges and mention the margin-left,margin-right, etc properties. The content might be a 'little' long, but if written properly, it could be made more concise.

**Comment by utkarshsingh99** [comment]
As for the minor formatting error, I would be happy to modify it and submit a PR within an hour once I have your permission for it.

**Comment by raisedadead** [comment]
@utkarshsingh99  

I think there is worth in teaching these progressively and keeping the challenges. To an expert/advanced eye this may look a little too easy, or redundant, but trust me new comers usually feel this is good to be a exercise.

But, we would love a pull request for the formatting issue on the fourth challenge in the OP.

Thanks for your interest in tackling that.

@ReveurGAM

Thanks for the issue and the feedback.

>  If the goal is to have them use the long form, why accept the short form on the first two challenges?

While there is no harm in accepting short form, because its not explicitly being said to NOT do that in the description. But, I agree we can check for this in the tests. 

Happy contributing!

**Comment by ninadingole** [comment]
@raisedadead I did some analysis and the tests for this challenge checks for paddings from the output pane. We need to add the test to assert user-written code.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
