### ISSUE TITLE
A typo in 'Modify an array stored in an object' challenge

### ISSUE THREAD

**Issue by zk433** [freeCodeCamp/freeCodeCamp#16659]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/basic-data-structures/modify-an-array-stored-in-an-object

#### Issue Description

There is a typo in the description of the challenge. It says:

> The data key contains four keys, one of which contains an array of friends.

when, in fact, the data key contains five keys (username, joinDate, organization, friends and location). I think it should be changed so that campers don't get hang up on it (like I did).

**Comment by zk433** [comment]
I'm happy to fix the typo and submit a PR tomorrow.

**Comment by jkao1** [comment]
Go for it!

**Comment by rabindranathfv** [comment]
is this fixed? i trying but i can not access to array friends nested in object
