### ISSUE TITLE
Completed Beta Certification (Javascript Algorithms and Data Structures), but Not Seeing Certificate

### ISSUE THREAD

**Issue by kodster28** [freeCodeCamp/freeCodeCamp#16661]
#### Claim Your JavaScript Algorithms and Data Structures Certificate
https://beta.freecodecamp.org/en/challenges/claim-your-javascript-algorithms-and-data-structures-certificate/claim-your-javascript-algorithms-and-data-structures-certificate

#### Issue Description
I'm able to go through all of the steps for claiming my certificate, and then FCC tells me it has been added to my profile page. 

But, in looking at my profile page, I'm not able to find the certificate. It might be on my end, but there seems to be no place that it's listed.

Potential issue: I linked my github account after claiming the certificate for the first time. 

#### Browser Information
Chrome: 64.0.3282.140

* Browser Name, Version: 
* Operating System:  Windows 10.0.14393
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/26727299/35917076-5ae4ce02-0bd2-11e8-9be2-72cbcd27d96e.png)

**Comment by Bouncey** [comment]
Thanks for reporting this. I have a PR that addresses this issue #16412

**Comment by Oyelowo** [comment]
I also can't seem to find the certificate for the javascript algorithms and data structures: 
![image](https://user-images.githubusercontent.com/31687368/39666972-36b82484-50b5-11e8-952c-a9c926f61cb0.png)
