### ISSUE TITLE
Test if a Value Falls within a Specific Range - always fails

### ISSUE THREAD

**Issue by iabrenne** [freeCodeCamp/freeCodeCamp#16665]
#### Test if a Value Falls within a Specific Range 

https://beta.freecodecamp.org/en/challenges/quality-assurance-and-testing-with-chai/test-if-a-value-falls-within-a-specific-range

#### Issue Description
The test always fails. It appears that there are two problems in /freeCodeCamp/seed/challenges/06-information-security-and-quality-assurance/quality-assurance-and-testing-with-chai.json:

1. Test is checking unit test No. 10 but it should be No. 9 : 
```
 "title": "Test if a Value Falls within a Specific Range",
...
...
"testString": "getUserInput => $.get(getUserInput('url') + '/_api/get-tests?type=unit&n=10')
... 
```

Here are the results to the get-tests glitch api, both with `unit&n=9` and `unit&n=10` query strings.

`https://honeysuckle-crime.glitch.me/_api/get-tests?type=unit&n=10`

```
{"title":"#isArray, #isNotArray","context":"Unit Tests -> Arrays","state":"failed","assertions":[{"method":"fail","args":["'isThisAnArray?'.split('')","'String.prototype.split() returns an Array'"]},{"method":"fail","args":["[1,2,3].indexOf(2)","'indexOf returns a number.'"]}]}
```

`https://honeysuckle-crime.glitch.me/_api/get-tests?type=unit&n=9`

```
{"title":"#isApproximately","context":"Unit Tests -> Comparisons","state":"passed","assertions":[{"method":"approximately","args":["weirdNumbers(0.5)","1","0.5"]},{"method":"approximately","args":["weirdNumbers(0.2)","1","0.8"]}]}
```

No. 10 is for the next challenge ( Test if Value is An Array )

2) Test is checking for the assertion method "isApproximately" but it should be "approximately"

          `{  assert.equal(data.assertions[1].method, 'isApproximately'); ` 

#### Screenshot

![image](https://user-images.githubusercontent.com/24214306/35958366-0ba542d8-0c66-11e8-9939-63f625152e81.png)

I would be happy to tackle this one if FreeCodeCamp team agrees this is an issue.

Thank you.

**Comment by raisedadead** [comment]
@iabrenne sure, please go ahead. and thanks for reporting.

**Comment by Brybro** [comment]
@raisedadead - Is assigned or open to be worked on?

**Comment by iabrenne** [comment]
@Brybro - I was planning on subbing a PR for this but unfortunately didn't get a chance to. Don't want to speak for @raisedadead but I'd say go for it! :)

**Comment by raisedadead** [comment]
@Brybro sure thing, if you are ready please go ahead.

**Comment by Brybro** [comment]
@iabrenne @raisedadead - Since I am new to this project, do you mind explaining how I can go about producing this bug?

**Comment by iabrenne** [comment]
@Brybro - sorry for the delay in responding, but looks like you have figured it out :)

**Comment by QuincyLarson** [comment]
@Em-Ant Since you helped design and implement this challenge, could you take a look at this and see whether @Brybro's PR elegantly fixes this issue?
