### ISSUE TITLE
Test if One Value is Below or At Least as Large as Another - always fails

### ISSUE THREAD

**Issue by iabrenne** [freeCodeCamp/freeCodeCamp#16668]
#### Test if One Value is Below or At Least as Large as Another
http://localhost:3000/en/challenges/quality-assurance-and-testing-with-chai/test-if-one-value-is-below-or-at-least-as-large-as-another

#### Issue Description
This test always fails. Looks like the problem is that only first element in the assertions array is checked
inside freeCodeCamp/seed/challenges/06-information-security-and-quality-assurance/quality-assurance-and-testing-with-chai.json

![image](https://user-images.githubusercontent.com/24214306/35981361-af438ed0-0cb2-11e8-944c-76ae3119d67f.png)

Here are the results from the get-tests gltich api : 

![image](https://user-images.githubusercontent.com/24214306/35981603-44e717b8-0cb3-11e8-9c1e-8b2efdd039c3.png)

There are four items in the data.assertions array , but the test is checking the first element ( data.assetions[0] ) 4 times.

#### Your Code

```js
    test('#isBelow, #isAtLeast', function() {
      assert.isAtLeast('world'.length , 5);
      assert.isAtLeast(2*Math.random(), 0);
      assert.isBelow(5 % 2, 2);
      assert.isBelow(2/3, 1);
    });



```
#### Screenshot

![image](https://user-images.githubusercontent.com/24214306/35981746-a71bf8cc-0cb3-11e8-8959-96d2186cadb9.png)

I plan on submitting a PR for this shortly, if that is OK. Thank you.

**Comment by raisedadead** [comment]
Hi @iabrenne yes please we would love a PR.
