### ISSUE TITLE
All my Certs are gone 

### ISSUE THREAD

**Issue by thadia** [freeCodeCamp/freeCodeCamp#16669]
#### Challenge Name

Certificates gone
https://www.freecodecamp.com/thadia/back-end-certification

#### Issue Description
Example: https://www.freecodecamp.com/thadia/back-end-certification 
Error: Looks like user thadia is not Back End Certified

I believe all my progress is as I remember it. Just that the links to the certs that I have added to LinkedIn are not working and not sure when they stopped working. Already tried to request them again, but even though I can successfully do that without any errors --> nothing really happens/changes.
Can anyone help or at least send me a copy of the initial ones ?

Thanks!

**Comment by raisedadead** [comment]
@QuincyLarson @BerkeleyTrue this could be another case of duplicate accounts.

**Comment by QuincyLarson** [comment]
@thadia Thanks for your patience. I've fixed this. It was indeed an issue with a duplicate account in our database. Please see your profile now: https://www.freecodecamp.org/thadia
