### ISSUE TITLE
LinkedIn Sharing

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#1666]
Example URI: https://www.linkedin.com/shareArticle?mini=true&url=http://stackoverflow.com/questions/10713542/how-to-make-custom-linkedin-share-button/10737122&title=How%20to%20make%20custom%20linkedin%20share%20button&summary=some%20summary%20if%20you%20want&source=stackoverflow.com

**Comment by N0bl3** [comment]
Hello!
What do you want to share via this button?

**Comment by erictleung** [comment]
This might help http://stackoverflow.com/a/10737122, but do we still need this @QuincyLarson?

**Comment by BerkeleyTrue** [comment]
I don't think we need this anymore.

Happy Coding!
