### ISSUE TITLE
Need help getting front end certificate

### ISSUE THREAD

**Issue by oluwatomigbekele** [freeCodeCamp/freeCodeCamp#16671]
#### Issue Description

I’ve finished the last challenge for the Front End Web Development Certfication and the “Claim Your Certificate” step, but every time I try to access the certificate, it returns the message “oluwatomigbekele has not yet agreed to our Academic Honesty Pledge”.I need help pls.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment]
I'll try and take a dig at this over the weekend. It was not reproducible last time I checked on local, and seems to be continuously coming up on production.

**Comment by BerkeleyTrue** [comment]
@raisedadead let me know and I can get you some actual data to test against.

**Comment by raisedadead** [comment]
Hi @BerkeleyTrue thanks, I am having a hard time getting my local setup running on the `backup/master` branch.

I'll get back as soon as I have that figured out, it crashing every time on the login path. I may have to double check for any dependency mismatch.

**Comment by BerkeleyTrue** [comment]
@raisedadead Protip: I have two instances of the fcc git. One forever on the backup/master to keep from having to switch the npm packages back and forth.

**Comment by raisedadead** [comment]
Yes, I have had the same as well, to avoid switching.

Its weird that I am getting this crash everytime only at the login:

```
200 GET 114.383 ms - /email-signin
404 GET 28.971 ms - /api/flyers/findOne?filter%5Border%5D=id+DESC
  fcc:user:remote setting cookies +4m
  fcc:user:remote user logged in +2ms
302 POST 43.384 ms - /api/users/login
/Users/raisedadead/DEV/freeCodeCamp-production/node_modules/mongodb/lib/utils.js:123
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Invalid attempt to destructure non-iterable instance
    at /Users/raisedadead/DEV/freeCodeCamp-production/server/component-passport.js:9:585
    at /Users/raisedadead/DEV/freeCodeCamp-production/server/component-passport.js:43:49
    at handleCallback (/Users/raisedadead/DEV/freeCodeCamp-production/node_modules/mongodb/lib/utils.js:120:56)
    at /Users/raisedadead/DEV/freeCodeCamp-production/node_modules/mongodb/lib/collection.js:2697:7
    at handleCallback (/Users/raisedadead/DEV/freeCodeCamp-production/node_modules/mongodb/lib/utils.js:120:56)
    at /Users/raisedadead/DEV/freeCodeCamp-production/node_modules/mongodb/lib/db.js:313:20
    at /Users/raisedadead/DEV/freeCodeCamp-production/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at /Users/raisedadead/DEV/freeCodeCamp-production/node_modules/async-listener/glue.js:188:31
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:218:9)
[00:12:34] [nodemon] app crashed - waiting for file changes before starting... 
```

**Comment by BerkeleyTrue** [comment]
Sounds like there is some function call with undefined arguments trying to destructure an array.

**Comment by oluwatomigbekele** [comment]
Thank you very much. It has been solved.
