### ISSUE TITLE
BETA: Minor English error

### ISSUE THREAD

**Issue by ReveurGAM** [freeCodeCamp/freeCodeCamp#16675]
#### Challenge Name
Basic CSS: Use Attribute Selectors to Style Elements
https://beta.freecodecamp.org/en/challenges/basic-css/use-attribute-selectors-to-style-elements

#### Issue Description

In the third paragraph:
> This selector matches and style elements with a specific attribute value.

Unless style is an adjective, it needs to have an s to follow subject-verb agreement.

I.E. This selector matches and **styles** elements with a specific attribute value.

You might also consider rewriting this sentence entirely to make it a bit easier to comprehend.

E.G. This selector allows you to {style} the indicated [elements].

**Comment by akkatracker** [comment]
I think *styles* is a better fix.

I'll submit a PR
