### ISSUE TITLE
Able to past tests without finishing challenges 

### ISSUE THREAD

**Issue by lalov1** [freeCodeCamp/freeCodeCamp#16677]
#### Challenge Name
React: Compose React Components
https://beta.freecodecamp.org/en/challenges/react/compose-react-components

#### Issue Description
I was able to move forward without reaching all the challenge statements including the following:
"Nest two components inside of Fruits — first NonCitrus, and then Citrus. Both of these components are provided for you in the background. "I was able to move forward without reaching all the challenge statements including the following:
"Nest two components inside of Fruits — first NonCitrus, and then Citrus. Both of these components are provided for you in the background. "

#### Browser Information

Chrome
Windows 10
Desktop 

#### Your Code

```
class Fruits extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <div>
        <h2>Fruits:</h2>
        { /* change code below this line */ }

         { /* change code above this line */ }
      </div>
    );
  }
};

class TypesOfFood extends React.Component {
  constructor(props) {
     super(props);
  }
  render() {
    return (
      <div>
        <h1>Types of Food:</h1>
        <Fruits />
        <Vegetables />
      </div>
    );
  }
};
```
#### Screenshot
![screenshot 2018-02-09 22 57 20](https://user-images.githubusercontent.com/7785251/36059047-ae746192-0dec-11e8-9191-230a09617fbf.png)

**Comment by bqnguyen94** [comment]
On it.
