### ISSUE TITLE
Got certificate claim challenge marked complete before it should be possible

### ISSUE THREAD

**Issue by smsrkr** [freeCodeCamp/freeCodeCamp#16679]
#### Challenge Name

[Claim Your Front End Development Certificate](https://www.freecodecamp.org/challenges/claim-your-front-end-development-certificate)

#### Issue Description

I have got this checkpoint marked as complete before finishing all prerequisite challenges.

The certificate is not granted in fact, but the "Confirm" buttons in step 2/4 & 3/4 do not seem to work, and "Go to my next step" buttons are unblocked.

#### Browser Information
* Browser Name, Version: Any
* Operating System: Any
* Mobile, Desktop, or Tablet: Any

#### Screenshot
![clipboard-20180211](https://user-images.githubusercontent.com/3525376/36065714-cc9266f6-0ec8-11e8-9888-38d06a905d24.jpg)

**Comment by Bouncey** [comment]
@smsrkr Thank you for reporting this issue. I have resolved this in an open PR #16664

**Comment by smsrkr** [comment]
My certificate checkpoint is still marked as complete.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
