### ISSUE TITLE
FCC Beta doesn't behave correctly at public library

### ISSUE THREAD

**Issue by ReveurGAM** [freeCodeCamp/freeCodeCamp#16682]
#### Challenge Name
Basic CSS: Use Attribute Selectors to Style Elements
https://beta.freecodecamp.org/en/challenges/basic-css/use-attribute-selectors-to-style-elements
and subsequent ones

#### Issue Description
When I loaded up FCC, I was unable to work on exercises or even navigate using map.  I tried refreshing the screen and even opening it in a new tab.  See screenshot section for more details.
Toggling the 4 sections works, and the community and settings buttons work.

#### Browser Information
* Browser Name, Version: Chrome Version 63.0.3239.132 (Official Build) (32-bit)
* Operating System: Windows 7 Pro
* Mobile, Desktop, or Tablet: desktop

#### Screenshot

Initially:
![image](https://user-images.githubusercontent.com/35181004/36066967-6192b260-0e79-11e8-9864-25808a32fc47.png)
![image](https://user-images.githubusercontent.com/35181004/36066959-394960a6-0e79-11e8-9898-7bde905cccb1.png)
After toggling map off, I got this.  The code inside the objects in the editor cannot be edited.
![image](https://user-images.githubusercontent.com/35181004/36066964-4ba5336a-0e79-11e8-8def-52891117bcba.png)
When I tried to select a different exercise from the map, I initially was able to do so, but got the error shown in 2nd image above.  Now, however, it won't allow me to expand the map at all.  Right clicking on a major category in the map and selecting "open in a new tab" failed - the current exercise was opened instead.
![image](https://user-images.githubusercontent.com/35181004/36066974-9b58fb58-0e79-11e8-9f13-63ab3e7b1914.png)

**Comment by Asjas** [comment]
Hi @ReveurGAM Thanks for your report. This has already been reported in #16468 and #16433 and it is being investigated currently.

**Comment by raisedadead** [comment]
Hi @ReveurGAM thanks for report, closing as duplicates of previous issues.
