### ISSUE TITLE
FCC Beta Settings has errors at public library

### ISSUE THREAD

**Issue by ReveurGAM** [freeCodeCamp/freeCodeCamp#16683]
#### Issue Description

Most settings work (add Twitter, night mode, show public profile, pledge, etc.), others do not (GitHub, LinkedIn).
1) I am logged into GitHub, obviously, but the first time that I clicked on "add GitHub to my profile", I got the error message "Something went wrong."; after that, the screen refreshed if I tried again and there was a message saying it'd updated my profile: "We've updated your profile based on **your your** GitHub account."  Please note the English error in the message.

2) When I tried "add LinkedIn to my profile", I got the error shown below.  I was surprised to see this option since, after a previous report I'd made about this option, I was told this would be disabled.
![image](https://user-images.githubusercontent.com/35181004/36067093-c6c0ccb0-0e7b-11e8-9c8a-9475665bd5c6.png)
![image](https://user-images.githubusercontent.com/35181004/36067103-2ebdd448-0e7c-11e8-9437-def65faed57f.png)

#### Browser Information

* Browser Name, Version: Chrome Version 63.0.3239.132 (Official Build) (32-bit)
* Operating System: W7 Pro
Desktop

**Comment by raisedadead** [comment]
Hi this is being resolved and tracked already in the settings page updates. Refer #16412
