### ISSUE TITLE
PH7 license were do i start 

### ISSUE THREAD

**Issue by vinny1962** [freeCodeCamp/freeCodeCamp#16686]
#### Learning  

friendclass.net

#### Issue Description

I was told this is open source free software can anyone help me to get this fully functional or can anyone point a admin with years of experience seeking a new platform i believe PH7 is about the best i have seen so far. 

#### Browser Information

* Browser Name, Version:  
* Operating System: Linux
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by Asjas** [comment]
Hi @vinny1962. I am not sure what you are trying to ask but I suspect our gitter channel might be a better place to ask that. It can be found [here](https://gitter.im/FreeCodeCamp/FreeCodeCamp).
