### ISSUE TITLE
FCC (regular and Beta) marked as unsafe at public library

### ISSUE THREAD

**Issue by ReveurGAM** [freeCodeCamp/freeCodeCamp#16681]
#### Issue Description

I am at the public library and, when I tried to access FCC, regular and beta, I got the same warning (see screenshot).

#### Browser Information

* Browser Name, Version: Chrome Version 63.0.3239.132 (Official Build) (32-bit)
* Operating System: Windows 7 Pro
* Mobile, Desktop, or Tablet: desktop

#### Screenshot

![image](https://user-images.githubusercontent.com/35181004/36066863-ac958dac-0e77-11e8-8bad-5f8501e924ff.png)

**Comment by raisedadead** [comment]
We use CloudFlare as a CDN in front of our servers. As for the certs, I think they are provided by LetsEncrypt.

@BerkeleyTrue do you think this is due something at our end? I can not think of anything that would be causing this.

**Comment by systimotic** [comment]
Looks like our certificate should be good: https://www.ssllabs.com/ssltest/analyze.html?d=freecodecamp.org
![20180211_14-55-37_firefox](https://user-images.githubusercontent.com/7262039/36074113-bec7d826-0f3b-11e8-967d-0e7be8a41a8d.png)
It also says it should run fine on your version of Chrome (as it does for me).

@ReveurGAM Can you check if https://www.opensourceforgood.org/ gives you the same error? It should be running on the same certificate, so if it works fine, this may be a cache issue.

**Comment by BerkeleyTrue** [comment]
I don't think this is on our end. We use industry standard certs provided by cloudflare.

**Comment by ReveurGAM** [comment]
@systimotic Hi, when I get back to the West Allis Library (Wisconsin), I will try to check.  I don't have this problem anywhere else, which is what makes it odd, but I thought I should report it because I don't want library users to be discouraged from using FCC.

**Comment by vkWeb** [comment]
@ReveurGAM Please try running in incognito mode. I'm 100% sure it'll work ;).

**Comment by ReveurGAM** [comment]
Next time I'm there, but I wouldn't be surprised if they disabled private browsing, given how locked down the computers are...

**Comment by vkWeb** [comment]
@ReveurGAM Ya. So, try clearing all the browsing data (Including cache) and visit the site again.

**Comment by ReveurGAM** [comment]
Ok, guys, I've made a special trip to the library. :)

First, please note this happens on the children's section's computers.  This does NOT occur on the adult computers so, if you're not interested in having kids study on FCC, you might as well close this.  It's probably the filtering from ContentProtect (www.contentwatch.com) and/or SAM (security account manager), so I guess you'd have to contact the respective owners to see if you can be exempted from blocking.
ContentProtect:
![image](https://user-images.githubusercontent.com/35181004/36124501-e4a9e91e-1015-11e8-85f2-c130de646419.png)
![image](https://user-images.githubusercontent.com/35181004/36124504-e9c270c4-1015-11e8-9306-88a8c0beda0b.png)
![image](https://user-images.githubusercontent.com/35181004/36124508-edbd5310-1015-11e8-9fc2-63d7845d01d2.png)

You can see the SAM icon in the bottom right corner.
![image](https://user-images.githubusercontent.com/35181004/36124536-0bee4fec-1016-11e8-85cc-f0fc1cc048e7.png)

@systimotic Same result on that website.
![image](https://user-images.githubusercontent.com/35181004/36123768-53a184ce-1013-11e8-86bf-3744668f24c0.png)

@vkWeb I tried Incognito.  Since I was already logged in to BFCC, I didn't get the warning.  However, the website still behaves incorrectly, which seems to support my belief that the filters are causing this.

I cleared the browser (which was almost empty) and refreshed my screen, which netted me the warning again, and the website still doesn't behave correctly.  Also, right-click is sometimes disabled. When I opened the dev tools, I got this on that error:
![image](https://user-images.githubusercontent.com/35181004/36124319-3b350b2a-1015-11e8-83a6-b4eb5aeb1a5f.png)

Here's the dev tools, inspecting the empty editor, map opened:
![image](https://user-images.githubusercontent.com/35181004/36124401-7a9b4392-1015-11e8-9d22-5daaee20c4d1.png)

And focused on the preview:
![image](https://user-images.githubusercontent.com/35181004/36124430-9826f7a8-1015-11e8-9af3-a641bbe12e95.png)

Inspecting the dysfunctional editor, map closed:
![image](https://user-images.githubusercontent.com/35181004/36124450-b0ad26c6-1015-11e8-98f8-230ca281a1ea.png)

And, the preview pane, map closed:
![image](https://user-images.githubusercontent.com/35181004/36124474-c7634f9e-1015-11e8-802d-593bbe439345.png)


I hope this helps.  It's time to get home to my kids. :)

**Comment by ReveurGAM** [comment]
BTW, after logging out of BFCC, I used Incognito to see if I'd get the error; I didn't.
![image](https://user-images.githubusercontent.com/35181004/36124603-4552e96e-1016-11e8-8f8a-e4f7b40538e3.png)

**Comment by raisedadead** [comment]
This is due to the protection software, being used at library. Unfortunately that is beyond the scope of this project.

Will have to close.
