### ISSUE TITLE
animation-timing-function default is ease, not linear

### ISSUE THREAD

**Issue by akshat-harit** [freeCodeCamp/freeCodeCamp#16684]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/applied-visual-design/change-animation-timing-with-keywords

#### Issue Description

In the text "There are a number of predefined keywords available for popular options. For example, the default value is linear, which applies a constant animation speed throughout.", linear seems to be wrong. The default value seems to be ease (https://www.w3schools.com/cssref/css3_pr_animation-timing-function.asp). Also changing the value to linear as per exercise does change the animation timing.

#### Browser Information

Google Chrome Version 64.0.3282.140 (Official Build) (64-bit), Windows 10

I can pick it up and submit a pull request, as it seems pretty easy in terms of first bug i.e just a typo.

**Comment by raisedadead** [comment]
@akshat-harit thanks for reporting. Yes please go ahead.
