### ISSUE TITLE
[Beta] There are two scrollbars in the Preview Panel

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16695]
### Issue Description
In many challenges eg. [Use a CSS Class to style an element](https://beta.freecodecamp.org/en/challenges/basic-css/use-a-css-class-to-style-an-element) or [Create a block element bootstrap button](https://beta.freecodecamp.org/en/challenges/bootstrap/create-a-block-element-bootstrap-button), there are two scrollbars in the preview panel. There should be a single scrollbar like we have in all of our challenges.  

![issue](https://user-images.githubusercontent.com/26724128/36087054-1cc57158-0ff6-11e8-9b2d-64b4546e814c.PNG)

### Browser Information
* Browser Name, Version: Chrome and Firefox (latest).
* Operating System: Windows 10 Pro 32 Bit.
* Mobile, Desktop, or Tablet: Desktop.

**Comment by Bouncey** [comment]
This can be fixed through CSS.

The CSS class for this panel is `challenges-preview`

**Comment by quimbyosis** [comment]
Mind if I take a crack at this?

**Comment by Bouncey** [comment]
Go for it @quimbyosis 👍

**Comment by vkWeb** [comment]
@masterchef2209 Thanks for showing interest but @quimbyosis is already working on this. You can consider looking at the To-Do card of beta-release [here](https://github.com/freeCodeCamp/freeCodeCamp/projects/1?fullscreen=true).

**Comment by vkWeb** [comment]
@quimbyosis Are you working on it?
