### ISSUE TITLE
[Beta] Broken tests in React, Redux and React & Redux Challenges. 

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16696]
### Issue Description
There a lot of broken tests in React, Redux and React & Redux Challenges. When clicking on **Run tests** the challenge log gets stuck on **// running tests** and **Something went wrong, please try again later** messages are displayed.

#### Broken tests in React section:
- [ ] [Use Array.map() to Dynamically Render Elements.](https://beta.freecodecamp.org/en/challenges/react/use-arraymap-to-dynamically-render-elements)
- [ ] [Use Array.filter() to Dynamically Filter an Array.](https://beta.freecodecamp.org/en/challenges/react/use-arrayfilter-to-dynamically-filter-an-array)
- [ ] [Render Conditionally from Props.](https://beta.freecodecamp.org/en/challenges/react/render-conditionally-from-props)
- [ ] [Give Sibling Elements a Unique Key Attribute.](https://beta.freecodecamp.org/en/challenges/react/give-sibling-elements-a-unique-key-attribute)

#### Broken tests in Redux section:
- [ ] [Write a Counter with Redux.](https://beta.freecodecamp.org/en/challenges/redux/write-a-counter-with-redux)

#### Broken tests in React & Redux section:
- [ ] [Connect Redux to the Messages App.](https://beta.freecodecamp.org/en/challenges/react-and-redux/connect-redux-to-the-messages-app)

### Browser Information
* Browser Name, Version: Chrome and Firefox(latest)
* Operating System: Windows 10 Pro 32 Bit. 
* Mobile, Desktop, or Tablet: Desktop.

**Comment by Bouncey** [comment]
The `challengeSeed` for these challenges have unfinished declarations in them. Babel falls over trying to do it's thing.
> Use Array.map() to Dynamically Render Elements.
> Use Array.filter() to Dynamically Filter an Array.
> Render Conditionally from Props.
> Give Sibling Elements a Unique Key Attribute.
> Write a Counter with Redux.

The `challengeSeed` has an invalid `render` method in the `Component`. React Components/functions cannot return undefined, Babel falls over trying to do it's thing.
> Connect Redux to the Messages App.

**Comment by bqnguyen94** [comment]
I’m on it
