### ISSUE TITLE
[beta] Move a Relatively Positioned Element with CSS Offsets - needs better verbiage

### ISSUE THREAD

**Issue by ReveurGAM** [freeCodeCamp/freeCodeCamp#16692]
#### Challenge Name
Applied Visual Design: Move a Relatively Positioned Element with CSS Offsets
https://beta.freecodecamp.org/en/challenges/applied-visual-design/move-a-relatively-positioned-element-with-css-offsets

#### Issue Description
I think it would be easier to understand the effect if it were explained that it's not really moving in the opposite direction, but rather it's moving away from the referenced side.  You might say:
"Assigning a value to top moves the element away from the top, left moves the element away from the left side, etc."

**Comment by TJBarrettJR** [comment]
I wonder if there is a way to add an additional visual element to help with the confusion?

One idea would be to adjust the challenge to be with colored blocks like in this [Basic CSS](https://beta.freecodecamp.org/en/challenges/basic-css/adjust-the-padding-of-an-element) challenge.

I think adding an image like the above blocks showing before and after with the CSS could be hugely beneficial. Maybe have two block on top of each other, one stays put while the user is able to adjust the CSS and see the second block move relative to the position of the first?

**Comment by qmikew1** [comment]
I think the simplest way to illustrate would be to take advantage of the fact that there's live output to editor changes (i.e, user could see what's going on as they make changes). Maybe including some default values would help:

Example:
```html
<head>
    <style>
        h2 {
            position: relative;
            /*Only Change Code Below*/
            right: 10px;
            top: 5px;
            /*Only Change Code Above*/
        }
    </style>
</head>

<body>
    <h1>On Being Well-Positioned</h1>
    <h2>Move me!</h2>
    <p>I still think the h2 is where it normally sits.</p>
</body>
```
-Or- 
a simple animated gif could illustrate the basic concept 
![fcc_css_offset_concept](https://user-images.githubusercontent.com/13352783/36211675-eaf74054-116f-11e8-861c-11ba9a985d4a.gif)

**Comment by ReveurGAM** [comment]
Well, whatever you folks decide.  My point is just that the current wording is actually going to cause confusion.  I've learned the offsets before, and this is the first time I've seen an exercise that made it confusing.

**Comment by TJBarrettJR** [comment]
@ReveurGAM I do agree with you still on the wording, we are just brain storming some other ideas to accompany the words. 
Something like:
> The CSS offsets of `top` or `bottom`, and `left` or `right` tell the browser how far to offset an item relative to where it would sit in the normal flow of the document. You're offsetting an element away from a given spot, which moves the element away from the referenced side (effectively, the opposite direction). As you saw in the last challenge, using the top offset moved the h2 downwards. Likewise, using a left offset moves an item to the right.

@qmikew1 I like both ideas, I think the best would be expanding the gif to have the css next to it? Like for top it had the same gif but had css to the side that said "top: 10px;" to show what each did? Ideally, I would think we would want to have the learner type as much of the code as possible.

**Comment by qmikew1** [comment]
I generally would agree that learners should be typing as much code as possible; however, in this specific context/challenge, it's not immediately apparent what should go there in terms of top/bottom/left/right (or units). The prior challenge [Change an Element's Relative Position](https://beta.freecodecamp.org/en/challenges/applied-visual-design/change-an-elements-relative-position) there is an example of ```bottom: 10px;```  (and, yes, one could piece together what to do from that example.....but) - so including default (or showing an example in description) would seem to be, actually, consistent with prior challenges. 

In terms of design decisions (inclusion/lack of inclusion, placement etc.) that's up to folks evaluating issues.

**Comment by ReveurGAM** [comment]
@TJBarrettJR I like your wording, and I also like the idea of a visual aid.  Not everyone learns from words alone, and FCC doesn't use many visuals.  Yes, you can play with the values and see it change in the preview panel, but I suspect some people don't realize/feel comfortable/or whatever doing that for a variety of reasons.  Anything that stacks the deck in the learner's favor, without taking away the challenge, tends to be a good thing to add.

@qmikew1 BTW, I like your gif.  Did you make that?

@all:
If you're feeling overwhelmed by working on FCC right now, you may want to skip this next part. ;)  I get too ambitious sometimes.  I'd help myself if I could actually wrap my head around the programming necessary, plus Git/GH still confuses me...

I'm a fan of playing with values, so I tend to play sometimes, and my son (9 yo) thinks it's pretty fun. ;)  It can help me understand.  In fact, to get over the confusion **caused** BY the confusion alert in the instructions of this challenge, I played with the values.

Which gives me a **bigger** idea that is probably going to take way more effort (unless you can get existing code from other sites), because it'd be useful on most/all challenges/areas/sections and, thus, require addition to multiple pages.  As an educator, I recognize that different people learn differently so, while I really dislike Code School, other people think it's great.  Anything that can increase the viability of FCC should at least be considered for inclusion - if not for the upcoming version, then for future versions - don't you think?

You could add generator-type examples that allow a person to see how changing a value affects the GUI.  I'm not saying that you should show the code, but that you should allow the relevant value(s) to be manipulated with a slider so they can see the change.  Would this would take more effort than generating animated images?

If I'm not being clear, here's some info on some sites I've found that offer this sort of thing (the Ultimate CSS Generator is possibly the most complete).  Most of these offer generators which let you change attributes of various things you can do in CSS, just using sliders (there are other sites that offer the same for BootStrap, HTML, etc.

*CSS Generator.org has 10 generators:Box Shadow, Text Shadow, Gradient, CSS Cursor, Border, Border Radius, Transform, RGBA & Hex Color, Filter, Multiple Columns

*CSSmatic offers 4 generators: gradient, box-shadow, noise texture and border radius generators using sliders, toggles and color pickers, so you can see both the effect and the corresponding code.

*CSS3 Generator offers 13 different generators: Border Radius, Box Shadow, Text Shadow, RGBA, @Font Face, Multiple Columns, Box Resize, Box Sizing, OutlineTransition, Transform, Flexbox, Gradient.

*Enjoy CSS has a few stylers for blank, input, block and button; generators for text, background, shadows, border & radius, transition, transform, with a gallery of buttons, text fields, text effects, shapes, gradient patterns and art; various options exist for each choice.

*CSS Layout Generator is a 100% free tool used for creating HTML/CSS templates. It lets you get up and running with barebones design code ASAP.  You can set the doctype, CSS reset, layout width, header and footer sizes, 0-2 sidebars on the left or right, and keep the footer at the bottom of the screen or emulate equal height columns. Click the link and it'll show you a sample of what you chose, and there is a link to a .zip file with the HTML and (unformatted) CSS files.

*HTML Table Styler - CSS Generator is a selection rich environment for generating code to create a website template with 13 preset styles.  It also has a table to div converter (link at bottom). It displays the HTML & CSS, and WYSIWYG display. The table GUI has options:
-Create a table using the div or table tag and define the font, border, background color, cell, padding, width and height (px or %), and border collapse, with or without demo text.
-Style the header's font size, bold, text color, background color & gradient, divider's color & size, line color & size, text-align.
-Style the body's font size, bold, text color, border size & color, h-stripes & v-stripes, size.
-Style the footer's font size, bold, text color, background color & gradient, line color & size, link colors.

*CSS Code Generators has Gradient, Box Shadow, Text Shadow, Color Picker, Font Styler, Table Styler, Column, Border & Outline, Border Radius, Box Transform, and Background Image with HTML, CSS and WYSIWYG display, with sliders, color pickers, etc.

*The Ultimate CSS Generator has Code Generators for:
-CSS3, HTML5, Microdata, JSON-LD, Meta Tags, Open Graph, Twitter Card, and File Name
-Animation
-Background (BACKGROUND COLOR, BACKGROUND GRADIENT, BACKGROUND IMAGE), Border (BORDER, BORDER IMAGE, BORDER RADIUS, BOX RESIZE, BOX SHADOW, OUTLINE, OVERFLOW (X, Y), VISIBILITY)
-Color (OPACITY)
-Filter (BLUR, BRIGHTNESS, CONTRAST, GRAYSCALE, HUE-ROTATE, INVERT, SATURATE, SEPIA)
-Layout (COLUMNS, DISPLAY)
-List (LIST STYLE)
-Miscellaneous (CURSOR)
-Text (LETTER SPACING, LINE HEIGHT, TAB SIZE, TEXT ALIGN, TEXT DECORATION, TEXT INDENT, TEXT SHADOW, TEXT TRANSFORM, WHITE SPACE, WORD BREAK, WORD SPACING, WORD WRAP)
-Transform (PERSPECTIVE, TRANSFORM)
-Transition
and links to: Rank Gen SEO Analyzer, and Programmer Shirts & Mugs

*W3Schools Web Templates has a selection of CSS Templates.

**Comment by qmikew1** [comment]
ty :smile: yep (did it in fireworks)

**Comment by TJBarrettJR** [comment]
@ReveurGAM I think there could be a lot of good discussion about the second part of what you put, but I think it may be better suited for the true [forums](https://forum.freecodecamp.org/). 

For updating the wording for this challenge. I can certainly look into how to get going on that if you would like? If so, when I get home from work, I will read more into contributing and getting moving on this.

**Comment by ReveurGAM** [comment]
@TJBarrettJR Where in the forums would you suggest I put my idea?

If you are up to tackling the wording, I have no objections. Are you going to put in that image that @qmikew1 made? @raisedadead Is this okay with you folks?

**Comment by TJBarrettJR** [comment]
@ReveurGAM I would think [here](https://forum.freecodecamp.org/c/contributors) in the contributors category?

**Comment by raisedadead** [comment]
I think @TJBarrettJR suggestion in https://github.com/freeCodeCamp/freeCodeCamp/issues/16692#issuecomment-365664126 seems reasonable for the verbiage.

Also, I am in favor of the visual aid, @qmikew1 could you upload the GIF to imgur and share a link that can be embedded in the challenge?

And once ready we can have a PR, whosoever amongst you are interested in so.

**Comment by qmikew1** [comment]
@raisedadead, @TJBarrettJR [here's the image link](https://i.imgur.com/eWWi3gZ.gif) -imgur can be kind of flaky (if so, I'll use my normal image hosting service)

**Comment by ninadingole** [comment]
@raisedadead do we want this image to be present just after the description of the challenge? I can do this.

**Comment by raisedadead** [comment]
@qmikew1 thanks for the image. 

We are undertaking a separate task #15941 for moving over images. Please feel free to follow along and pitch in.

@ninadingole yes, that sounds right.

**Comment by ReveurGAM** [comment]
@raisedadead So do you want the image on S3 or imgur?

Also, what about Quincy's note  that he wants to eliminate images, in that thread you just referenced (10/7/17)?

**Comment by raisedadead** [comment]
We want to takle this current issue with the imgur, and then on whenever the audit is done on the code-base, we can collectively move over everything to S3. 

As for Quincy's comment, I think, we want to keep it to the minimum where it becomes essential.

**Comment by TJBarrettJR** [comment]
@ninadingole are you taking care of this? Just want to verify if I should get started on it or not.

**Comment by ninadingole** [comment]
@TJBarrettJR yes, I am starting on this.

**Comment by TJBarrettJR** [comment]
@ninadingole @raisedadead I think that perhaps the image should be instead with a new guide page for this challenge instead of on the challenge itself. Based upon the discussion in [this](https://github.com/freeCodeCamp/freeCodeCamp/issues/15941) issue we may be better suited by having this image in the guide instead with any additional explanation we feel is needed.  

I think the wording probably does still need a change, just shift the image to a guide instead of the main challenge section. 

Thoughts? @ReveurGAM @qmikew1

**Comment by qmikew1** [comment]
@TJBarrettJR I like the guide idea (vs. in-challenge) - one of the issues with images is theming (general, page mode (night vs. not etc.) - and I feel like it's easy to break consistency.

**Comment by ReveurGAM** [comment]
@TJBarrettJR I'm afraid I don't know what you mean by a guide page.  Please explain.

What's wrong with the wording?

I don't follow about the theming.  Unless you're planning to make multiple images to match the themes, which is (IMHO) a waste of space, a single image should be fine.  If you really want to be strict, then you'd need to make sure that all images across the site followed a specific set of rules regarding coloration, border, corners, and so on, unless the challenge warranted something different.

**Comment by TJBarrettJR** [comment]
Hey, I linked the guide on the forums post we were talking in.

**Comment by ReveurGAM** [comment]
@TJBarrettJR Yup.  I noticed a typo in what I wrote.  I don't like the idea of putting an image meant to clean up an immediate comprehension problem into the guide.  But, again, it's not my site.

**Comment by raisedadead** [comment]
Hi @TJBarrettJR @ReveurGAM @qmikew1 I merged a PR from @ninadingole for this issue, however as most of us are inclined that a guide is a better place for this additional help, it would be great if someone can create a article with the same image and link it in the challenge.

**Comment by qmikew1** [comment]
@raisedadead @TJBarrettJR @reveurGAM,  If it's not pressing (like within 48 hrs or something) I can put something together (assuming via the process in [guides readme](https://github.com/freeCodeCamp/guides) - ) Will take the guide-centric convo to gitter-contributors' channel for follow-up or questions etc. - Again though probably looking at 1-3 days

**Comment by raisedadead** [comment]
Hi @qmikew1 of course take all the time you need, and thanks a lot for taking contributing.
