### ISSUE TITLE
React: Write a React Component from Scratch test case issue

### ISSUE THREAD

**Issue by AdityaOli** [freeCodeCamp/freeCodeCamp#16698]
#### Challenge Name
React: Write a React Component from Scratch

https://beta.freecodecamp.org/en/challenges/react/write-a-react-component-from-scratch

#### Issue Description

There seems to be an issue when I try to test the Write a React Component from Scratch module. For example: 
It works completely fine when the answer is written as:
```js
class MyComponent extends React.Component {
  constructor(props) 
  {
    super(props);
  }
  render() 
  {
    return (
      <div>
        <h1>My First React Component!</h1>
      </div>
    );
  }
};

ReactDOM.render(<MyComponent />, document.getElementById("challenge-node"));

```
But, when there is only a bracket shifted down in the first line ,i.e:

```js
class MyComponent extends React.Component 
{
  constructor(props) 
  {
    super(props);
  }
  render() 
  {
    return (
      <div>
        <h1>My First React Component!</h1>
      </div>
    );
  }
};
ReactDOM.render(<MyComponent />, document.getElementById("challenge-node"));
```
Then in that case, the ```There should be a React component called MyComponent.``` test case fails. I do not think the test case should fail in this scenario.

#### Browser Information

* Browser Name, Version: Google Chrome, 56.0.2924.76 (64-bit)
* Operating System: Windows 7 (64-bit)
* Mobile, Desktop, or Tablet: Desktop

**Comment by sammcoe** [comment]
I've got this.
