### ISSUE TITLE
correct answer not passing

### ISSUE THREAD

**Issue by haasDev** [FreeCodeCamp/freecodecamp#1669]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![screen shot 2015-08-08 at 2 21 09 pm](https://cloud.githubusercontent.com/assets/11150235/9152105/c8a08f46-3dd8-11e5-9441-b88d3ddc0589.png)

**Comment by kurzninja** [comment]
The test that checks for the correct color in was wrong, I have fixed it in https://github.com/FreeCodeCamp/freecodecamp/pull/1706.
