### ISSUE TITLE
 # virtual machine crash logs, see http://www.java.com/en/download/help/error_hotspot.xml hs_err_pid*

### ISSUE THREAD

**Issue by noorizzwan** [freeCodeCamp/freeCodeCamp#16703]
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment]
@noorizzwan please do not spam on the issue tracker. Refer our [Code of Conduct](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CODE_OF_CONDUCT.md)
