### ISSUE TITLE
Another disappearing advice window

### ISSUE THREAD

**Issue by garysmeade** [FreeCodeCamp/FreeCodeCamp#1670]
Challenge http://beta.freecodecamp.com/challenges/waypoint-create-a-bootstrap-row has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Another example of the advice window disappearing upon input.  Here is the initial window:
![image](https://cloud.githubusercontent.com/assets/13364192/9152756/7d86cd68-3e78-11e5-95b4-c2a48a68aa4b.png)

As soon as you start typing "<d", the window disappears:
![image](https://cloud.githubusercontent.com/assets/13364192/9152759/96aeb396-3e78-11e5-9d6b-fa5a969b8577.png)

**Comment by AkiraLaine** [comment]
@garysmeade Have you completed the Waypoint? Just typing ```<d```` would cause an error.
