### ISSUE TITLE
React: Create a Controlled Input

### ISSUE THREAD

**Issue by lalov1** [freeCodeCamp/freeCodeCamp#16705]
#### Challenge Name
React: Create a Controlled Input

#### Issue Description
I think I have the correct code and it is working like it is supposed to, but I'm not passing the test.

#### Browser Information

Chrome 64 (64 Bit)
Windows 10
Desktop 

#### Your Code
```js
class ControlledInput extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      input: ''
    };
    // change code below this line
    this.handleChange = this.handleChange.bind(this);
    // change code above this line
  }
  // change code below this line
  handleChange(event){
    this.setState({
      input: event.target.value
    })
  }
  // change code above this line
  render() {
    return (
      <div>
        { /* change code below this line */}
        <input onChange={this.handleChange} />
        { /* change code above this line */}
        <h4>Controlled Input:</h4>
        <p>{this.state.input}</p>
      </div>
    );
  }
};
```
#### Screenshot
![screenshot 2018-02-12 22 35 57](https://user-images.githubusercontent.com/7785251/36135051-c7df27d8-1045-11e8-977a-793d63d6f94c.png)

**Comment by bqnguyen94** [comment]
You forgot to add `value` to `input`:

> In the render method, create the input element above the h4 tag. **Add a value attribute which is equal to the input property of the component's state**. Then add an onChange() event handler set to the handleChange() method.

**Comment by raisedadead** [comment]
Thanks @bqnguyen94 

@lalov1 can you check once again as per @bqnguyen94 suggestion. Happy coding!

**Comment by lalov1** [comment]
Yes, that works! Sorry about that...

**Comment by VolodymyrPliuta** [comment]
works in real life but test is not passed 
I think you should let ES6 binding work 

```
class ControlledInput extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      input: ''
    };
  }

   handleChange = (event) => {
   this.setState({
     input: event.target.value
   })
   console.log(this.state.input)
 }
  render() {
    return (
      <div>
        <input type="text" value={this.state.value} onChange={(event) => this.handleChange(event)}/>
        <h4>Controlled Input:</h4>
        <p>{this.state.input}</p>
      </div>
    );
  }
};
```

**Comment by OlegSemko** [comment]
try to use this in last field  
<input value = {this.state.input} onChange = {this.handleChange.bind(this)}/>

**Comment by OlegSemko** [comment]
<input value = {this.state.input} onChange = {this.handleChange.bind(this)}/>

**Comment by arnabbarui5** [comment]
You just have to write this line

<input type="text" onChange={this.handleChange} value={this.state.input} />

`
class ControlledInput extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      input: ''
    };
    // change code below this line
    this.handleChange = this.handleChange.bind(this)
    // change code above this line
  // change code below this line
}
handleChange(e) {
    this.setState({
      input: e.target.value
    })
  }
  // change code above this line
  render() {
    return (
      <div>
        { /* change code below this line */}
        <input type="text" onChange={this.handleChange} value={this.state.input} />


        { /* change code above this line */}
        <h4>Controlled Input:</h4>
        <p>{this.state.input}</p>
      </div>
    );
  }
};

`

**Comment by hygtfrde** [comment]
class ControlledInput extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      input: ''
    };
    // Change code below this line
    this.handleChange = this.    handleChange.bind(this); 
    // Change code above this line
  }
  // Change code below this line
  handleChange(event) {
    this.setState( {
      input: event.target.value
    })
  }
  // Change code above this line
  render() {
    return (
      <div>
        { /* Change code below this line */}
        <input value={this.state.input} onChange={(e)=>this.handleChange(e)} /> 
        { /* Change code above this line */}
        <h4>Controlled Input:</h4>
        <p>{this.state.input}</p>
      </div>
    );
  }
};

**Comment by blackboldse** [comment]
First step will be making a function that changes the state variable `input`.
![image](https://user-images.githubusercontent.com/39994467/190446519-4e019e73-9d01-48c8-bea2-edc9f1008b58.png)

Add a `value` attribute which is equal to the `input` property of the component's `state`. Then add an `onChange()` event handler set to the handleChange() method.
![image](https://user-images.githubusercontent.com/39994467/190447668-77b3530f-d1a2-420f-bffd-e48fa26fd205.png)

Remember to bind `this` to the function.
![image](https://user-images.githubusercontent.com/39994467/190447445-20dbe5dc-4cac-4e83-8456-42a7a4f6ff9c.png)

And you can try with solution if you forget bindings in the constructor:
![image](https://user-images.githubusercontent.com/39994467/190448526-d7b9e644-89fe-472f-b3df-60b9dcc84c68.png)

Hope reply for help.

Enjoy!
