### ISSUE TITLE
refactor redux-form to use react-redux-form

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#16726]
This issue will require some initial knowledge of react/redux and the structure of the codebase

**Comment by Bouncey** [comment]
👍 great @jkao1, go for it!

**Comment by jkao1** [comment]
@Bouncey, I only recently came across a problem with my packages that's interfering with my ability to work on this refactor. I `npm install`'d a new package to help with my debugging (`redux-logger`) and, if I visit the local site, it tells me that the `index.js`'s cannot be found in two npm packages, `store` and `react-notification`. These are the only packages in `package.json`. that are forks of the original:
```js
"react-notification": "github:BerkeleyTrue/react-notification",
"store": "git+https://github.com/berkeleytrue/store.js.git#feature/noop-server",
```

Could you help me out?

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (100/100 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:38365)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUNN-0005F9-Uf
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:52:58 -0400
Received: from out-5.smtp.github.com ([192.30.252.196])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUN0-0006Ej-IN
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:52:34 -0400
Date: Sun, 03 Jun 2018 07:52:33 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037553;
	bh=OW+ygqVtHZUkf6EnmBew/nBmqKKLHwR4okYm1JJFBJ0=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=qRUrNzRQmeqfUXOULb230S0HOtaGRW/He5V2yfFtq20h/iN0wGghRA6lV0qSTDhWb
	 Zd7rKYY3kuJTQQc2LmW2EUD6/M++RuM1xa6cEsicJmC403TU/FEKO+N1KgXR4lOyL7
	 Hhr7XCC4jeX06/YCf0LM7RBciJCes8dt3mKDIbIk=

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (103/100 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:38397)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUNQ-0005HB-52
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:00 -0400
Received: from out-2.smtp.github.com ([192.30.252.193])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUNL-0006Ev-7h
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:52:55 -0400
Date: Sun, 03 Jun 2018 07:52:54 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037574;
	bh=q2aP0EtJJE17D+hQ4FBIFMfqaTfqBiIXhfz8kGPXTtU=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=H6teHlv/zNdTbmibNWCsY8EVFcQO3d62kOET2/dNbud9UAPsgSz5idBVsbgypdmCH
	 NukQjw358UeXC5XV60OI+waQKVxr8CThh/cdx658cLbEiMjnBJSL0UxW5E0FJ5UGAm
	 MtdXG5lWp8Tsrh1lCPGjO4MydkQRNvyzfn1B68fk=
