### ISSUE TITLE
Comments causing advice window to disappear

### ISSUE THREAD

**Issue by garysmeade** [FreeCodeCamp/FreeCodeCamp#1672]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-comments-to-clarify-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

See below for screen appearance prior to adding comments tag:
![image](https://cloud.githubusercontent.com/assets/13364192/9153161/ae166be4-3e89-11e5-9406-4ee65c553598.png)

And then after the initial comments tag:
![image](https://cloud.githubusercontent.com/assets/13364192/9153163/c2c7ede2-3e89-11e5-9866-a304fc154ae1.png)

**Comment by michael-krebs** [comment]
This isn't a bug, it's what happens if you don't close a comment on all text editors. Just close the comment with `-->`

**Comment by AkiraLaine** [comment]
@garysmeade Nothing is displaying because you haven't closed the comments tag. It should look like this: ```<!--You shouldn't need to modify code below this line-->```
