### ISSUE TITLE
refactor codemirror to use eslint

### ISSUE THREAD

**Issue by BerkeleyTrue** [freeCodeCamp/freeCodeCamp#16727]

**Comment by hibaAkroush** [comment]
hi @BerkeleyTrue  can you provide more description? 
im not familiar with your code 
it would make it much easier if  you can send me the path to codemirror please

thanks

**Comment by BerkeleyTrue** [comment]
We use code mirror for both of our challenge editors. They are currently set up to use jshint for linting. We'd like to use eslint instead. 

A quick search of the code base points to the relevant files
https://github.com/freeCodeCamp/freeCodeCamp/search?l=JSX&q=codemirror&type=&utf8=%E2%9C%93

Mainly, Challenges/views/Modern/Editor and Challenges/views/Classic/Editor

**Comment by gondar00** [comment]
Can i take this up?

**Comment by hibaAkroush** [comment]
@gondar00  I found it first friend  :) 
will work on it today I hope its okay with you

**Comment by gondar00** [comment]
@hibaAkroush sure, its cool 😄 

I was thinking to use http://codemirror.net/doc/manual.html#registerHelper and then build a custom eslint validator,

Feel free to discuss if needed, I would be happy to help 😊
