### ISSUE TITLE
U tag to underline - test doesn't check whether text is only thing underlined

### ISSUE THREAD

**Issue by akkatracker** [freeCodeCamp/freeCodeCamp#16730]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/applied-visual-design/use-the-u-tag-to-underline-text

#### Issue Description

The test doesn't check for whether "Ph.D. students" is the only thing underlined - just whether it is. Unsure if this is the intention (if it is feel free to close), but if not, it needs to be fixed (however absolutely not critical). 

#### Browser Information
Chrome + Firefox on Windows

#### Screenshot
![image](https://user-images.githubusercontent.com/2032746/36338786-55d0f70a-140c-11e8-8894-b1c48c7a07c3.png)

**Comment by vkWeb** [comment]
@akkatracker The second test reads `The u tag should wrap around the text "Ph.D. students"`. This means it needs to be fixed. Will you be interested in tackling this?

**Comment by akkatracker** [comment]
I'm happy to leave it up for grabs

**Comment by vkWeb** [comment]
@akkatracker No issues.

**Comment by Hzuni** [comment]
I'd like to give it a shot. I think I see a fix, but might take a little bit since I've never tried an issue for this project before.

**Comment by akkatracker** [comment]
Sure, have a crack! If you need help, feel free to ask here or post in the
gitter
