### ISSUE TITLE
Challenge Success modal should not repeat the same Quote

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16738]
### Issue Description
In production on completing a challenge, campers get different quotes on different challenges which motivate them on their journey. But in beta the quote `Happy Coding!` keeps on repeating on every challenge. 
So, I think we should discuss whether it should be left as it is or should we implement the production's functionality. 
@QuincyLarson, I'll be waiting for your input on this :). 
### Browser Information
* Browser Name, Version: Chrome & Firefox(latest).
* Operating System: Windows 10 Pro 32 Bit. 
* Mobile, Desktop, or Tablet: Desktop.

**Comment by Bouncey** [comment]
It seems like we have stopped calling the `updateSuccessMessage` action after a challenge mounts/updates. We should enable this again.

**Comment by vkWeb** [comment]
@Bouncey Thanks for the quick response. Yes, we should enable that functionality.

**Comment by warborn** [comment]
I would like to work on this issue.
