### ISSUE TITLE
Beta: Waypoint: Target the Children of an Element Using jQuery - instructions

### ISSUE THREAD

**Issue by richyvk** [FreeCodeCamp/freecodecamp#1673]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery 

The instructions don't seem to be right for this. Firstly, the first sentence of the instructions doesn't really make sense: 

"Many HTML elements has a "children" element from which they "inherits" properties."

The second sentence says all elements are children of the body element, that's not right is it?

Then the instructions ask to turn all the #right-well div's children green. Doing this doesn't pass the tests.

**Comment by kurzninja** [comment]
The color checking test for this waypoint was wrong. I have fixed it in https://github.com/FreeCodeCamp/freecodecamp/pull/1706.
