### ISSUE TITLE
BETA - Challenge links to the wrong next challenge

### ISSUE THREAD

**Issue by mrbrooks74** [FreeCodeCamp/freecodecamp#1674]
Challenge http://beta.freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

After completing the add images to your website challenge, when you click on the green Go to my next challenge button, it links to http://beta.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-push

It should link to : http://beta.freecodecamp.com/challenges/waypoint-size-your-images

Thanks

**Comment by BerkeleyTrue** [comment]
This should be fixed in latest version.

Happy Coding!
