### ISSUE TITLE
Improvements to project view

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16748]
Please see screenshot below. I've already removed the references to images from the seed file as part of another PR.

![coding_interview_take_home_projects__build_a_light-bright_app___freecodecamp](https://user-images.githubusercontent.com/985197/36392515-4208c7a0-1571-11e8-94c3-09d5c4d176cb.png)

**Comment by vkWeb** [comment]
@QuincyLarson Shouldn't we align the div to the center?

**Comment by QuincyLarson** [comment]
@vkWeb we want the text to be left adjusted and of a limited width for readability reasons.

**Comment by vkWeb** [comment]
@QuincyLarson Okay. Got it ;).
