### ISSUE TITLE
[BETA] The navbar "Map" link does not work from the User Profile / Settings page 

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/freeCodeCamp#16746]
#### Issue Description
1. Go to https://beta.freecodecamp.org/en/settings
1. Click on the "Map" link in the navbar.
1. Nothing happens. The href attribute is set to #.

#### Screenshot

![image](https://user-images.githubusercontent.com/148813/36380367-cbe4450a-1560-11e8-814e-c8e8660b23ee.png)

**Comment by Bouncey** [comment]
Thanks for reporting this issue, I have already addressed this in #16743

**Comment by tchaffee** [comment]
Sorry about the dup issue. I did search open issues but didn't find that one. Closing as dup.

**Comment by Bouncey** [comment]
@tchaffee it is not a duplicate, I found whilst working it that area and just patched it as I went. We should keep this issue open just incase my PR does not get merged, in which case this will still be an issue
