### ISSUE TITLE
Button appears twice when running tests instead of just once.

### ISSUE THREAD

**Issue by sahiljuneja** [freeCodeCamp/freeCodeCamp#16745]
#### Challenge Name

https://www.freecodecamp.org/challenges/clone-an-element-using-jquery

#### Issue Description

- Added the following to the editor as required by the challenge - `$("#target5").clone().appendTo("#left-well");`
- `#target5` appears in both the left and right wells.
- Click `Run tests`.
- `#target5` appears twice in the left well (instead of just once).

Seems like when it's testing it loads/runs all of the code again and that causes the element to appear twice? [Would like to understand why something like this happens, if possible]

#### Browser Information

* Browser Name, Version: Firefox Quantum 58.0.1 (64-bit)
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
$("#target5").clone().appendTo("#left-well");


```
#### Screenshot

![image](https://user-images.githubusercontent.com/12501638/36377945-e451cde0-159e-11e8-9d6e-eb343c5564c1.png)

**Comment by sahiljuneja** [comment]
In the next challenge https://www.freecodecamp.org/challenges/target-the-parent-of-an-element-using-jquery, with the default code provided, `#target5` appears twice as well, instead of just once.

**Comment by bqnguyen94** [comment]
This issue is already resolved in #7430. You can try it in the [beta version](https://beta.freecodecamp.org/en/challenges/jquery/clone-an-element-using-jquery).

**Comment by raisedadead** [comment]
Hi @sahiljuneja this is a long time bug, and unfortunately we do not have a fix for it on the production site (the URL you have shared).

We have made a better platform level changes, to address this in the beta version of our site which we plan to release next.
