### ISSUE TITLE
Beta site error

### ISSUE THREAD

**Issue by laszlotordacsanyi** [freeCodeCamp/freeCodeCamp#16754]
On Sun, Feb 18, 2018 at 1:02 PM, Laszlo Torda Csanyi <laszlotordacsanyi@europemail.com> wrote:
Dear FCC Team!
 
I wanted to submit my completed job in https://beta.freecodecamp.org/en/challenges/applied-responsive-web-design-projects/build-a-technical-documentation-page
 
#### Issue Description

but the submit fuction not working,does not go further for the next task, and the map section libraries do not open.
 
I attached an image file with the bugs.
 
I hope the problems will be solved soon,because I'm done with all responsive web design projects.

#### Challenge Name

https://beta.freecodecamp.org/en/challenges/applied-responsive-web-design-projects/build-a-technical-documentation-page

* Browser Name, Version:  Google Chrome 64
* Operating System:  Windows 7 sp1 
* Mobile, Desktop, or Tablet:  Desktop

#### Screenshot
![fcc beta site error](https://user-images.githubusercontent.com/31016115/36431794-c66c1e56-1658-11e8-9260-ef15d2faf5af.jpg)

ps.: Thank you for responding to my letter. I hope the screenshot helps the troubleshoot.
      The beta curriculum is excellent. 
      The test modul: https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js 
      excellent idea, great help to perform the exam tasks correctly!
      Thank you for your work !

Best regards!

László Torda Csányi

**Comment by raisedadead** [comment]
Hi @laszlotordacsanyi 

Thanks for reporting, this is an ongoing issue https://github.com/freeCodeCamp/freeCodeCamp/issues/16468

Please feel to follow along.

**Comment by Bouncey** [comment]
Cross-posting so that you can still keep working on the challenges until we get this fixed

>What you could do to keep the challenges coming is navigate directly to the challenges themselves. Hovering over the challenge in the map will show you the address of the next challenge.

![hover for url](https://user-images.githubusercontent.com/18572518/36533311-1200926c-17bb-11e8-8b88-513b546df09e.png)

>I know this is not ideal, I should have a PR ready today.
