### ISSUE TITLE
[beta] make warning in delete progress / account more common to non-native speakers

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#16755]
![image](https://user-images.githubusercontent.com/1884376/36435587-0cfbcce8-1688-11e8-8cf8-b0ed0130c49b.png)

> Tread carefully, changes made in this area are permanent. They cannot be undone.

This message needs to be more common to non-native speakers. Something on lines of 

> Please be careful. Changes made in the section cannot be reversed.

**Comment by Brybro** [comment]
![image](https://user-images.githubusercontent.com/12816276/36445484-09da3b4c-1644-11e8-8830-17e1fad2a156.png)

@raisedadead - How does this look?

**Comment by jkao1** [comment]
@Brybro, small thing: the wording is a bit redundant. I recommend removing the part about how it's permanent. Anything that's irreversible is permanent.

**Comment by Brybro** [comment]
@jkao1 Thanks for the feedback.  Just fixed it and updated my pull request!  Please let me know what you think!

**Comment by jkao1** [comment]
Looks good!

**Comment by vkWeb** [comment]
@jkao1 Please remove the italics style from text.
