### ISSUE TITLE
[Beta] Required Improvements in Search functionality & its UX

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16750]
### Issue Description
@Bouncey I was playing with the search bar and found some glitches which need to be addressed.

- [ ] Right-clicking on output search modal or on opening chrome dev tools the modal disappears. It should disappear only when clicked outside the modal.   
- [ ] The output search modal is overflowing i.e. it needs a scrollbar. 
- [ ] The highlighting style of searched text needs to be changed. <details><summary>Screenshot and details.</summary>The highlighting style is causing an accessibility issue here. 
![2018-02-20](https://user-images.githubusercontent.com/26724128/36395326-a5145900-15de-11e8-90ab-cbf106edbc31.png)</details>
- [ ] Searching a term multiple times consecutively doesn't show the results. 
- [ ] If the searched term doesn't match any result, an appropriate message must be displayed.

### Browser Information
* Browser Name, Version: Chrome (latest).
* Operating System: Windows 10 Pro 32 Bit.
* Mobile, Desktop, or Tablet: Desktop.

**Comment by Bouncey** [comment]
@vkWeb please raise this issue in [freecodecamp/react-freecodecamp-search](https://github.com/freecodecamp/react-freecodecamp-search)

**Comment by vkWeb** [comment]
@Bouncey Done.
