### ISSUE TITLE
Adding 7 new sets of systems design questions to seed files

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16758]
@ocelotdive has created 7 sets of multiple choice questions for the Interview Prep section. 

Here they are: https://github.com/OcelotDive/FCCquestions

We're looking for an open source contributor who can help port these text files over to freeCodeCamp's JSON files so that these challenges will be accessible from the challenge map.

Here's the file where they would go, which already includes a set of multiple choice questions for reference: https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/08-coding-interview-questions-and-take-home-assignments/system-design-and-concept-questions.json

This would make a good first issue issue. To get started:

Get freeCodeCamp running locally: https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md

Join the Contributors chatroom: https://gitter.im/freecodecamp/contributors

And comment here to claim this issue. Then please post frequent updates so we can ensure this is ready in time for shipping beta :)

**Comment by jsparanoguy** [comment]
Hi, 
I'm on it, i'll start today after work !

**Comment by QuincyLarson** [comment]
@jsparanoguy Awesome! Sounds great. I've set this to "in progress". Please keep us posted on your progress :)

**Comment by jsparanoguy** [comment]
@QuincyLarson i checked it more in depth, initialised the project on local, if i didnt musunderstood it, it will be ready for saturday night (at least saturday nitght for me, sunday morning for you i guess because of the timezone !)

**Comment by QuincyLarson** [comment]
@jsparanoguy Awesome! I'm excited to see your work on it! Thanks for keeping us updated.

**Comment by jsparanoguy** [comment]
Hi !
It's almost done there is only one problem i have, for the question 4 from https://github.com/OcelotDive/FCCquestions/blob/master/GeneralFCC.txt it doesn’t look like a choice question for me… 
so i’m a bit stuck here ! i don't know how to handle this one, but everything else seems ok

**Comment by vkWeb** [comment]
@jsparanoguy Yes - It is not a choice question, but we can make it a choice one. You can present the question in this manner:

**Q.1) Select the correct Numeric types to their correct size.**
a) Byte - 32 bits, long - 8 bits , int - 64 bits, short - 16 bits. 
b) Byte - 8 bits, long - 32 bits , int - 64 bits, short - 16 bits. 
c) Byte - 8 bits, long - 16 bits , int - 32 bits, short - 64 bits. 
d) Byte - 8 bits, long - 32 bits , int - 64 bits, short - 16 bits. 

In above question, option (a) is correct. I hope it'll help. If you need any further assistance please reply back. Happy coding! 😄.

**Comment by jsparanoguy** [comment]
@vkWeb Thanksyou !

**Comment by QuincyLarson** [comment]
@vkWeb Thanks for the suggestion! That's a good set of potential answers. 

@jsparanoguy how is this coming along? Let us know if we can do anything to help.

**Comment by jsparanoguy** [comment]
@QuincyLarson well i did what i could for the subtitles fields, i'm just waiting for the feedback from the PR if there is anything to change :) !
