### ISSUE TITLE
Streak shows wrong value.

### ISSUE THREAD

**Issue by KarthikKadambi** [freeCodeCamp/freeCodeCamp#16765]
#### Challenge Name

Profile Page streak.

#### Issue Description

I have only completed challenges 3 day straight.(From 20th till 22nd feb). Instead of showing streak as 3 it shows 4.

#### Browser Information

* Browser Name, Version: Chrome
* Operating System: Mac 10.13.3
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
N/A


```
#### Screenshot

<img width="1440" alt="screen shot 2018-02-22 at 11 51 42 am" src="https://user-images.githubusercontent.com/1627832/36523277-d3d6a038-17c6-11e8-9c92-cd952e18af34.png">

**Comment by systimotic** [comment]
I originally misread the issue when adding the labels 😅. I can't reproduce this issue. [My test account](https://beta.freecodecamp.org/en/fcc4d4f0d2f-f78d-4813-be11-a744dfb686d6) correctly shows a three day streak.

Calculating the streak correctly has been always caused issues. We still have https://github.com/freeCodeCamp/freeCodeCamp/issues/7925 open about it. I believe this may be a duplicate.

**Comment by QuincyLarson** [comment]
@KarthikKadambi This is because your score starts at 1. We essentially give you a point for creating your account.
