### ISSUE TITLE
Beta site not working.

### ISSUE THREAD

**Issue by Ishtmeet-Singh** [freeCodeCamp/freeCodeCamp#16766]
Beta site does not seems to work fine since a couple of days. I cannot go to the next challenge, or use map. Whenever I try to click map, i get this error - 
![screen shot 2018-02-22 at 12 28 08 pm](https://user-images.githubusercontent.com/30657558/36524441-030b7842-17cc-11e8-968b-d122beca4a94.png)
And when I try to click go to next challenge, this error occurs - 
![screen shot 2018-02-22 at 12 27 32 pm](https://user-images.githubusercontent.com/30657558/36524453-11b1f5d8-17cc-11e8-9d1b-168b15cb0f02.png)
Can someone look into this issue?
Operating system - MacOS / Chrome

**Comment by thisiswhale** [comment]
Also getting the same error with Firefox on Windows

**Comment by systimotic** [comment]
This sounds like the issue @Bouncey fixed yesterday with #16759. Can you try clearing your cache and trying again?

**Comment by Ishtmeet-Singh** [comment]
@systimotic  I did. Still the same problem.

**Comment by Bouncey** [comment]
@Ishtmeet-Singh Thank you for reporting this issue. This is related to #16468 and is something I am actively working on.

What you could do to keep the challenges coming is navigate directly to the challenges themselves. Hovering over the challenge in the map will show you the address of the next challenege.
![hover for url](https://user-images.githubusercontent.com/18572518/36533311-1200926c-17bb-11e8-8b88-513b546df09e.png)

I know this is not ideal, I should have a PR ready today.

**Comment by Ishtmeet-Singh** [comment]
@Bouncey  Thank you for mentioning that. Yes, that's possible but by that way, I will not be able to see if the submission is right or wrong. Because, the popup that shows if you're going to move to the next level doesn't pops up.

I think I'll wait for the changes you make in PR and use it afterwards.

**Comment by Ishtmeet-Singh** [comment]
@Bouncey Actually, the way you said doesn't seems to work. Because, I cannot see the expanded version of the curriculum. So there are only the headings, and their "url" is something like - `https://beta.fcc.org/en/how-freecodecamp-works#Responsive Web Design`.
But it's not possible to navigation on them.

Here's an image to demonstrate, what I am trying to say. 
![screen shot 2018-02-22 at 5 20 33 pm](https://user-images.githubusercontent.com/30657558/36537052-00a2e9c2-17f5-11e8-92ba-39fa011479d6.png)
So as mentioned, to go to a challenge, I need to open the accordion but clicking on it is throwing XHR error as mentioned here https://github.com/freeCodeCamp/freeCodeCamp/issues/16766#issue-299242132

**Comment by systimotic** [comment]
Thanks for the fix Stuart!

@Ishtmeet-Singh If you refresh the page and don't interact with the challenge, you should still be able to use the map.

**Comment by Ishtmeet-Singh** [comment]
@systimotic  @raisedadead  If we're completing challenges on Beta's site, will the progress get deleted one you move the beta curriculum on the main site?

**Comment by Bouncey** [comment]
@Ishtmeet-Singh last I heard on this topic was that any progress made on the beta platform will not be carried over when it is released.
