### ISSUE TITLE
Incorrect answer accepted and passed for challenge: Create a Bootstrap Button

### ISSUE THREAD

**Issue by idlesHand** [freeCodeCamp/freeCodeCamp#16763]
#### Challenge Name

https://www.freecodecamp.org/challenges/create-a-bootstrap-button

#### Issue Description

I rushed and misread the question and instead of creating a new button as requested I merely edited the existing button and it passed the checks. Realised in next challenge my mistake.

#### Browser Information

* Browser Name, Version: chrome v.64
* Operating System: Linux Mint
* Mobile, Desktop, or Tablet: 

#### Your Code

```html

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text text-center">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>

  <img src="https://bit.ly/fcc-running-cats" class="img-responsive" alt="Three kittens running towards the camera. ">

  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit" class="btn">Like</button>
  </form>
</div>


```

**Comment by Hzuni** [comment]
I'm able to replicate this issue. Were you planning on tackling this issue?

**Comment by idlesHand** [comment]
I have had a brief look and the functions and regex are still beyond my js skills for at least a few more weeks.

First thoughts are to add a check for two buttons, one submit and the new button with the attribute 'btn'.

Or (this may catch less cases I think) to check that the like button is child to '<div>'
e.g. `assert($(\"div\").children(\"button\").length > 0` (I am guessing and stealing from another challenge)

Just to check that I have understood the structure of the project/challenges correctly. The appropriate file to edit would be the seed/challenges/03-front-end-libraries/bootstrap.json file? 

And that the various json files under 'challenges' are used to build the page and that the checks are the regex 'assert' statements? I assume after finding no reference to assert in js that it uses JSONassert unit testing lib.

**Comment by shubhamivane** [comment]
If it is still open I would like to work on it.

**Comment by gondar00** [comment]
If this is still open I would like to take it up.

**Comment by Asjas** [comment]
@gondar00 It seems no-one has started work on it so you can take it. :+1:
