### ISSUE TITLE
[Beta] "Ctrl + Enter" hotkey not working for Projects

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16769]
### Issue Description
The Project sections mentioned below run tests/submit on pressing <kbd>enter</kbd> not on <kbd>ctrl + enter</kbd>:

- [ ] Front End Libraries Projects
- [ ] Data Visualization Projects
- [ ] Information Security and Quality Assurance Projects
- [ ] Coding Interview Take-home Projects

### Browser Information
* Browser Name, Version: Chrome(64.0.3282.186)
* Operating System: Windows 10 Pro 32 Bit. 
* Mobile, Desktop, or Tablet: Desktop.

**Comment by elbaumpj** [comment]
I'd like to take a crack at this when it's ready!

**Comment by systimotic** [comment]
Thanks for reporting this @vkWeb. This may be related to #16773 /cc @Bouncey

**Comment by Bouncey** [comment]
@vkWeb the project challenge is a form, pressing enter on a form generally submits the form. The issue that's Timo referenced is that the project challenges do not display a completion modal once the challenge has been submitted. 

Is it that Ctrl + Enter does not submit the challenge, but that was the expectation?

**Comment by vkWeb** [comment]
@Bouncey Yes, that was the expectation as its written on the button. 
![capture](https://user-images.githubusercontent.com/26724128/36638595-1472697e-1a1f-11e8-8f78-c32fcf122ba6.PNG)

**Comment by SemperPeritus** [comment]
Can't reproduce.
Browser: Vivaldi | 1.14.1077.55 (Stable channel) (64-bit) (Chrome/64.0.3282.189)
OS: Windows 10 Pro 64-bit

**Comment by Bouncey** [comment]
@vkWeb, I don't think there is an easy fix for stopping the form from submitting on pressing `enter`, It would require us to modify the `redux-form` package.

I cannot reproduce the `not submitting on crtl + enter` issue you mention.

**Comment by vkWeb** [comment]
@Bouncey I think you're using Firefox? This isn't reproducible in Firefox.

**Comment by vkWeb** [comment]
@Bouncey Also, entering https://example.com passes the test. Is this behaviour expected?

**Comment by Bouncey** [comment]
We have no test suite for projects, so yes. This is the same as the current production site also.

**Comment by vkWeb** [comment]
@Bouncey Okay.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
