### ISSUE TITLE
Change the Color of Text challenge won't run test

### ISSUE THREAD

**Issue by amberferrerolaub** [freeCodeCamp/freeCodeCamp#16768]
https://www.freecodecamp.org/challenges/change-the-color-of-text

I searched for the issue but couldn't find this exact problem - please forgive me if it's there... there's lots to search through. :)

I believe the code is correct but the "Run tests" button won't run the test after completing the challenge. I've tried in Firefox, Chrome and Safari. I've tried resetting the code, clearing cache, restarting browser.

In Chrome I can at least get the "Run test" button to change color, this does not happen in Safari and Firefox when I click it.

* Browser Name, Version: Firefox 58.0.2, Chrome 64.0.3282.167, Safari 11.0.2
* Operating System: OS X 10.13 
* Mobile, Desktop, or Tablet: Desktop

![change_the_color_of_text___freecodecamp](https://user-images.githubusercontent.com/36485407/36565328-fe188fa6-17d4-11e8-8909-5ec31f5c78b8.png)

**Comment by amberferrerolaub** [comment]
Just realized my code was wrong and that was the issue! I guess I thought there would be more of an indicator that it was wrong. Sorry! :)

**Comment by raisedadead** [comment]
> I guess I thought there would be more of an indicator that it was wrong.

Do you mean the test messages were not shown with your code?

![image](https://user-images.githubusercontent.com/1884376/36577120-378b5286-187b-11e8-877e-ff157397cb79.png)

If that is the case, please share your code here.

**Comment by systimotic** [comment]
Hi @amberferrerolaub! It looks like this was indeed caused by your code. But as @raisedadead mentioned, if the message did not show up at all, that would be an issue. If that's the case, please let us know and we'll reopen the issue.

Happy coding!
