### ISSUE TITLE
Beta: Waypoint: Target a Specific Child of an Element Using jQuery - instructions don't match test

### ISSUE THREAD

**Issue by richyvk** [FreeCodeCamp/freecodecamp#1676]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery

Instructions ask to "Make the first child in each of your well elements bounce."

But, test expects "The second element in each of your "well" elements should bounce."

**Comment by BerkeleyTrue** [comment]
This is being tracked in #1713
