### ISSUE TITLE
"Change the Color of Text" challenge does not load

### ISSUE THREAD

**Issue by systimotic** [freeCodeCamp/freeCodeCamp#16762]
#### Affected challenge
[Beta: Change the Color of Text](https://beta.freecodecamp.org/en/challenges/basic-css/change-the-color-of-text)

## Issue description
There was a small mistake in a recent change, which prevents this challenge from loading correctly when it is loaded from the server. This means that it works fine when you browse to it using the map, but if you refresh the page or click [a link to the challenge](https://beta.freecodecamp.org/en/challenges/basic-css/change-the-color-of-text), it will break.

### What should be changed
This line is causing the problem:
https://github.com/freeCodeCamp/freeCodeCamp/blob/82ec375f19b7289d0d9b996fc19f04bcff71fa6e/seed/challenges/01-responsive-web-design/basic-css.json#L50
Specifically, this part:
```html
<code>color</color>
```
should be
```html
<code>color</code>
```

### How to get started

Check out the [CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) to get your local development environment set up.

If you need help, please go to our [contributors chatroom](https://gitter.im/FreeCodeCamp/Contributors). We're always happy to answer any questions!

Happy coding!

---

This issue was originally reported by @alysabax in #16756

**Comment by renisalcedo** [comment]
Hi, can I take this one?

**Comment by alysabax** [comment]
<img width="1280" alt="screen shot 2018-02-24 at 5 48 33 am" src="https://user-images.githubusercontent.com/35865223/36611069-61ed4542-1926-11e8-8d99-693514abe0ab.png">

Hey! I'm still getting these errors!

**Comment by alysabax** [comment]
@systimotic  :)

**Comment by renisalcedo** [comment]
Hi @alysabax I will take a look asap.

**Comment by systimotic** [comment]
@alysabax @renisalcedo Hi! This issue is indeed still present on https://beta.freecodecamp.org. This is because since it has not been updated since I merged @renisalcedo's fix. I can confirm that the fix worked when I tried it out locally. It should start working on the beta site as soon as it's updated, which I expect to be within a couple of days (usually when a major update/fix happens).
