### ISSUE TITLE
Canno't create c9 account without credit card.

### ISSUE THREAD

**Issue by cerushdope** [freeCodeCamp/freeCodeCamp#16760]
As I see in tutorial, in the past you could create account free but now I can't create c9 account without credit card. Any suggestions?

**Comment by huyenltnguyen** [comment]
Hi @cerushdope, FCC now recommends using https://glitch.com/ as a c9 alternative.

**Comment by cerushdope** [comment]
@huyenltnguyen  yeah, but how can I go on with the tutorial?

**Comment by huyenltnguyen** [comment]
What tutorial are you referring to? Would you mind posting the link here?

**Comment by raisedadead** [comment]
Yes, we need to update the production challenges to recommend using glitch instead.
For example this:

https://www.freecodecamp.org/challenges/manage-packages-with-npm

We anticipate moving to the newer beta edition where this is already done. But for now, its alright if we can replace the links in the challenges, with a a guide to using glitch as an alternative.

Contributions needed:

1. Create a guide on using Glitch, at guides.freecodecamp.org
2. Replace the links on `backup/master` with the link to the guide, and update the instructions.

@QuincyLarson do you think this is Okay? Or should we just wait for launching beta and avoid this interim fix?

**Comment by raisedadead** [comment]
P.S: The original issue https://github.com/freeCodeCamp/freeCodeCamp/issues/9826

**Comment by huyenltnguyen** [comment]
@raisedadead Thanks for the link. I was totally unaware of the challenge (I went straight to the beta after I finished the front-end cert).

If I may throw in my two cents on the matter,
> 1. Create a guide on using Glitch, at guides.freecodecamp.org

Agreed.
@QuincyLarson There is an idea just popped up in my head. What do you think about making a short youtube video on this, too? I think the visual would make it easier for users to follow, compared to having to read and mentally locate where a button is.

> 2. Replace the links on `backup/master` with the link to the guide, and update the instructions.

What if we just leave it as it is and add a note at the top of all back-end challenges? The note could say something like: "We recommend using Glitch for back-end challenges. Follow this [link] for the setup guide. If you wish to use C9, continue with the instructions below."

**Comment by huyenltnguyen** [comment]
@cerushdope My recommendation, as a camper, is to learn back-end on the beta site (https://beta.freecodecamp.org/en/challenges/managing-packages-with-npm/introduction-to-the-managing-packages-with-npm-challenges). Please note that your progress on beta will be lost once it goes live, so remember to backup your solutions and save it somewhere else.

**Comment by cerushdope** [comment]
@huyenltnguyen  Alright. Guess everything is settled here. Thanks a lot.

**Comment by huyenltnguyen** [comment]
@cerushdope You're welcome. Happy coding!
