### ISSUE TITLE
"Javascript is disabled. Something went wrong. Please try again later. " Error

### ISSUE THREAD

**Issue by HebleV** [freeCodeCamp/freeCodeCamp#16772]
Unable to execute the first task due the javascript error.

I have just started React tutorials and unfortunately I keep getting the following error for the very first task "**Javascript is disabled. Something went wrong. Please try again later.**" 

#### Challenge Name

React
**Create a Simple JSX Element**

#### Browser Information

* Browser Name, Version: Google Chrome, 64.0.3282.167
* Operating System: windows 7
* Mobile, Desktop, or Tablet: Laptop

#### Screenshot

**Here is a screenshot.** 

![issue](https://user-images.githubusercontent.com/29232159/36611029-236a67ce-18f8-11e8-97d3-16c27356a805.png)

**Comment by Whizkevina** [comment]
Can you try Firefox and then review the code again....

**Comment by vkWeb** [comment]
@HebleV This issue will be fixed with #16370. @Bouncey Please look into this.

**Comment by HebleV** [comment]
@Whizkevina Yes the error shows up even for Firefox

**Comment by HebleV** [comment]
@vkWeb Ok thanks for the update

**Comment by Bouncey** [comment]
This is now resolved in staging, just waiting for it to be released in to the wild

**Comment by vkWeb** [comment]
@Bouncey Ya! ✨
