### ISSUE TITLE
[Beta] On running tests, the lesson page should automatically scroll down

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16770]
### Issue Description
In production whenever tests are run, the lesson panel automatically scrolls down which makes it easier & faster to get information about failing/passing tests. But on Beta we don't have that functionality, scrolling down on each and every lesson is a cumbersome process. So, that functionality should be added. 

### Browser Information
* Browser Name, Version: Chrome(64.0.3282.186)
* Operating System: Windows 10 Pro 32 Bit.
* Mobile, Desktop, or Tablet: Desktop.

**Comment by raisedadead** [comment]
We are under a feature freeze, I am differing this until after beta is shipped, however PRs are still welcome.

**Comment by vkWeb** [comment]
@raisedadead Okay. We'll do this after beta is shipped.

**Comment by Bouncey** [comment]
We had this before, where did it go?

**Comment by raisedadead** [comment]
Probably, worth looking into the component scrolling.

**Comment by anhtran1906** [comment]
I investigated the problem and it seems like the problem was fixed with [https://github.com/freeCodeCamp/freeCodeCamp/pull/9151]. However, the commonFramework directory that was supposed to merge is not in staging right now. Please take a look.

**Comment by raisedadead** [comment]
Hi @anhtran1906 we have moved to react instead of the code that you see.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
