### ISSUE TITLE
About localization

### ISSUE THREAD

**Issue by t-cool** [freeCodeCamp/freeCodeCamp#16779]
I'm trying to set up the freeCodeCamp using Docker on my Macbook.
I found the learning material in seed directory.
All the data seem to be defined in each json file.
In the json files, there is a part named "translations."
For instance, this part seems to be the German translation.

```
 "translations": {
        "de": {
          "description": [
            "Lass uns jetzt die Farbe von unserem Text ändern.",
            "Wir können das bewerkstelligen, indem wir den <code>style</code> des <code>h2</code> Elements ändern.",
            "Der Style, der zuständig für die Textfarbe eines Elements ist, ist der \"color\" Style.",
            "So könntest du die Textfarbe des <code>h2</code> Elements in Blau ändern:",
            "<code>&#60;h2 style=\"color: blue\"&#62;CatPhotoApp&#60;/h2&#62;</code>",
            "<hr>",
            "Ändere den Style des <code>h2</code> Elements, damit die Textfarbe rot (\"red\") ist."
          ]
        },
```
I'd like to insert Japanese translation as "jpn".

How could I insert and how can I switch to Japanese translation?

I'd appreciate your help.

**Comment by raisedadead** [comment]
See:
https://forum.freecodecamp.org/t/guidelines-for-translating-free-code-camp-to-any-language/19111

And then you will have to add an entry here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/utils/supported-languages.js
