### ISSUE TITLE
Mongoose -Delete Many Documents with model.remove()

### ISSUE THREAD

**Issue by clickingmouse** [freeCodeCamp/freeCodeCamp#16775]
#### Challenge Name
Delete Many Documents with model.remove()

https://beta.freecodecamp.org/en/challenges/mongodb-and-mongoose/delete-many-documents-with-modelremove

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
var removeManyPeople = function(done) {
  console.log("*********")
  var nameToRemove = "Mary";
  Person.remove({"name": nameToRemove}, function(err,result){
  if (err)   done(err)

  done(null,result)
  })


```
#### Screenshot

events.js:160

      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unexpected token o in JSON at position 1
    at Object.parse (native)
at /app/server.js:271:25
    at Query.<anonymous> (/app/node_modules/mongoose/lib/model.js:3928:16)
    at /app/node_modules/kareem/index.js:297:21
    at /app/node_modules/kareem/index.js:135:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by Em-Ant** [comment]
Hi @clickingmouse, I'm trying to understand what is happening. Are the previous mongo challenges passing for you?  Can I have the link to your glitch project ?

**Comment by Em-Ant** [comment]
@clickingmouse I don't need your project. I found the problem. The result checking in server.js is not compatible with mongoose 5. I'll update the boilerplate and the github repo.

@raisedadead do you think I should update this PR https://github.com/freeCodeCamp/boilerplate-mongomongoose/pull/2/commits/afbb9cd46f2294b49b2e4db3745071a9438026e9 or open a new one ?

**Comment by clickingmouse** [comment]
hi . sorry for the slow response, glad that all is done.. i sort of lost faith and thought it was my code seeing no one assigned after like a week. and havent checked these pages. sorry

**Comment by QuincyLarson** [comment]
@Em-Ant OK - great! Thanks for the PR. 

I'm closing this - please re-open this if there's anything further we need to do on this.
