### ISSUE TITLE
Target html elements with selectors using jquery: Information incorrect in advice window

### ISSUE THREAD

**Issue by garysmeade** [FreeCodeCamp/freecodecamp#1677]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The advice window suggests adding a class to an img element but there are only button elements to add to in this exercise:

![image](https://cloud.githubusercontent.com/assets/13364192/9154513/34f6f2f4-3ed6-11e5-98dc-4b15f570b4a6.png)

**Comment by QuincyLarson** [comment]
@garysmeade thank you for reporting this. We've fixed it. Happy coding!
