### ISSUE TITLE
Beta - Dark Mode - Academic Dishonesty Policy - Text Illegible 

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16781]
#### Challenge Name

FCC Beta User Profile

#### Issue Description

When attempting to read the Academic Dishonesty Policy while in dark mode, the text is illegible.
it is too light against the white background. 

Text needs to be darkened

#### Browser Information

* Browser Name, Version:  Version 64.0.3282.186 64-bit
* Operating System: Windows 10 Professional (Latest Updates) 64bit 
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/36706173-a99b42a6-1b36-11e8-899c-756e72cf5e4c.png)

**Comment by adiconstante** [comment]
Hi, I'd like to work on this (:
