### ISSUE TITLE
Beta - User Profile - Dark Mode - About Settings - Hover on Tabs - Text Illegible

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16786]
#### Challenge Name

FCC Beta Profile - About Settings 

#### Issue Description

When hovering over the tabs in the About Settings in the User profile, 
the text becomes illegible as the :hover color is the same as the text
the text needs to be changed to another color

#### Browser Information

Browser Name, Version: Version 64.0.3282.186 64-bit
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/36708486-3a9f225e-1b41-11e8-8d2b-a90636193f1f.png)

**Comment by nethanelkohen** [comment]
I'd like to take care of this!

**Comment by nethanelkohen** [comment]
@mstellaluna Would you be able to point me to the correct file? I'm having a bit of trouble navigating this on my machine. Thank you in advance
