### ISSUE TITLE
Beta - User Profile - Cannot unsubscribe from weekly emails - not toggling 

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16784]
#### Challenge Name

FCC User Profile

#### Issue Description

Cannot unsubscribe from Quincy's weekly emails. It is not toggling and no account change
confirmation appears. 

Appears to be a broken button.

there is no error in the dev tools console. 

#### Browser Information

Browser Name, Version: Version 64.0.3282.186 64-bit
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```
#### Screenshot

ORIGINAL STATE:
![image](https://user-images.githubusercontent.com/22984739/36707828-ffd2b92c-1b3d-11e8-83e4-29600c058eb0.png)

ATTEMPTING TO TOGGLE OFF:
![image](https://user-images.githubusercontent.com/22984739/36707860-1bf98de2-1b3e-11e8-8756-c7adbc7e1309.png)

STILL HAS NOT CHANGED: 
![image](https://user-images.githubusercontent.com/22984739/36707828-ffd2b92c-1b3d-11e8-83e4-29600c058eb0.png)

**Comment by vkWeb** [comment]
@Bouncey Confirmed.
