### ISSUE TITLE
Missing "anatomy of a CSS class:" image (or code) in: 11. Waypoint: Use a CSS Class to Style an Element

### ISSUE THREAD

**Issue by izybit** [FreeCodeCamp/freecodecamp#1678]
Apparently there is either an image or some example code missing from there.

Full link: http://www.freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element

**Comment by BerkeleyTrue** [comment]
Please provide screen caps of your issue.

**Comment by izybit** [comment]
I was getting the camper image placeholder instead of the diagram but I had another look at it and it seems that uBlock on Waterfox was to blame.
