### ISSUE TITLE
Beta - User Profile - Certifications Settings - Unable to type in fields

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16785]
#### Challenge Name

FCC Beta User Profile - Certification Settings

#### Issue Description

I can't seem to be able to type into any of the fields nor am I able to copy/paste a URL
There is no error message that appears in the dev tool console when inspecting the element
I don't see the field as being disabled either 

#### Browser Information

Browser Name, Version: Version 64.0.3282.186 64-bit
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/36708151-aaf8860a-1b3f-11e8-8066-8f255f0dece0.png)

**Comment by vkWeb** [comment]
@mstellaluna I think you have not completed the projects. Please try completing the "Build a tribute page" or any of the Applied Responsive Web Design Project, you'll find that these fields are automatically populated with your project links & then you'll be able to edit/enter your project links. 

But yes from UX perspective we need to make this more clear.

**Comment by Bouncey** [comment]
@vkWeb you can complete the project by either the challenge itself or this field in certificate settings. I never had this issue when building it??

**Comment by mstellaluna** [comment]
@Bouncey @vkWeb the screenshot doesn't show it but when I click on it the :focus does become active and the cursor is there but it doesn't allow me to type in ... the fields that are not related of the Certificate areas (i.e Internet Presence) I am able to write in them

**Comment by vkWeb** [comment]
@Bouncey No - I'm not able to complete the projects by entering links on the certification settings fields. To reproduce please reset all your progress and then try again entering links.

**Comment by Bouncey** [comment]
@mstellaluna @vkWeb I am unable to reproduce locally, I have been all over the code for this whilst build [the claim legacy certs feature](https://github.com/freeCodeCamp/freeCodeCamp/pull/16788)

**Comment by Bouncey** [comment]
I have it, I hadn't rebased and was missing some new code. I believe I have fixed it also. PR incoming.

**Comment by vkWeb** [comment]
@Bouncey You're a super hero ✨- From react settings page, faster initial fetch of challenges to react babel errors, beta has lifted up to an another level!
