### ISSUE TITLE
Beta - Dark Mode - Search Results - Text Illegible

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16787]
#### Challenge Name

FCC Beta Search Bar

#### Issue Description

The search results in dark mode, the text is illegible
I cannot see any words just the orange highlight confirming my search results with my search value

#### Browser Information

Browser Name, Version: Version 64.0.3282.186 64-bit
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/36709056-f2f58364-1b43-11e8-821b-8464a2c06420.png)

**Comment by jsparanoguy** [comment]
Hi !
I'm up to do this one (i could take all the dark mode issue that @mstellaluna openned)

**Comment by vkWeb** [comment]
@mstellaluna All issues related to search bar from freeCodeCamp repo are centralised in [one place](https://github.com/freeCodeCamp/react-freecodecamp-search/issues/55). Please, close this one. 😃

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (106/100 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:38778)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1fPUNz-0005jd-B3
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:35 -0400
Received: from o1.sgmail.github.com ([192.254.114.176])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1fPUNo-0006Gt-Ul
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:25 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=n4oyWOyXgE6Gg4E/89XJBgZMsXo=; b=ogdqTyaS4zYOw2vF
	AgVIdGucgFzbWkP+DYj9vZz7b4RaKXv5v/IP5BRnH1C9RH/uSnVNdzAB6DUzJN/S
	DMx2AWCBbuL9BwC3RzhIGUdXHElukT4tWuCYtqgFSUsJjEqtXqqMJWTZUi/cRuSt
	yOe3NSIZ9ctyWBX6298gyaVZa1A=
Received: by filter1402p1mdw1.sendgrid.net with SMTP id filter1402p1mdw1-11156-5B1400E3-3
        2018-06-03 14:53:23.111909531 +0000 UTC
Received: from github-lowworker-643483b.cp1-iad.github.net (unknown [192.30.252.45])
	by ismtpd0010p1iad1.sendgrid.net (SG) with ESMTP id cGWzPBQjTT6Df6FyXhiMPA
	for <manzil@funtasticlabs.com>; Sun, 03 Jun 2018 14:53:23.072 +0000 (UTC)
Received: from github.com (localhost [127.0.0.1])
	by github-lowworker-643483b.cp1-iad.github.net (Postfix) with ESMTP id 0EC526C1AB4
	for <manzil@funtasticlabs.com>; Sun,  3 Jun 2018 07:53:23 -0700 (PDT)
Date: Sun, 03 Jun 2018 14:53:23 +0000 (UTC)

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (107/100 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:38779)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUNz-0005je-Ac
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:35 -0400
Received: from out-2.smtp.github.com ([192.30.252.193])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUNl-0006Gr-T4
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:22 -0400
Date: Sun, 03 Jun 2018 07:53:21 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037601;
	bh=Sc+ojPl6y6tiwr27ubHQ1AEmcf0chEySC3epkq+VMEo=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=BP40gSFVEP4hNcc9qdckAtT0hA5EYEKwtkHYLr+RwSX+xaz9F/Xeeb6HiPEfF5LpD
	 AJw8nPSnTuQCt4qiAck2L5JGGn4GAAvuVeGfWfzh6HKdd5XnraI5h5vzr9vVU4kWiD
	 qDx5cIUh8J7QHNKGgi7YM9ZnzrtaihY4N0RpUM2Y=
