### ISSUE TITLE
Beta - Dark Mode - Profile Heat Map Streaks - Text Blends with Background

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16780]
#### Challenge Name

FCC Beta User Profile

#### Issue Description

When reviewing my beta profile, the heat map streaks text is blended with the background.
Needs to be changed to white to conform with the rest of the color scheme.

Missing/Illegible Text:
Longest Streak:
Current Streak:

#### Browser Information

* Browser Name, Version:  Version 64.0.3282.186 64-bit
* Operating System: Windows 10 Professional (Latest Updates) 64bit 
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/36705941-9bb78452-1b35-11e8-8499-5bc775cf9644.png)

**Comment by vkWeb** [comment]
@mstellaluna PR incoming. It'll cover all night mode settings & profile page style issues.
