### ISSUE TITLE
Beta - Dark Mode - User Profile -  Confirmation Message Text Illegible 

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16783]
#### Challenge Name

FCC Beta User Profile

#### Issue Description

When making changes to profile ( in this case switching from light mode and dark mode) the confirmation alert message at the top (you need to scroll up to see it) the text is illegible, its too light. 

#### Browser Information

Browser Name, Version: Version 64.0.3282.186 64-bit
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Laptop: 

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/36707613-0b16694c-1b3d-11e8-8b21-caed1b834de8.png)

**Comment by HebleV** [comment]
Hey  I am on this.
