### ISSUE TITLE
Beta: Search bar showing no results / not working

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#16791]
#### Unable to get search results when using the search bar on beta

The issue seems to work like this:
**I can search successfully as many times as I want until I switch pages.**
For example: If I'm on the settings page, I can make searches just fine - then I go to the map page and searching doesn't work.
If reload the base url, the map is open and I can make searches - then go to the settings page and can't make searches.

confirmed by @mstellaluna

**Comment by mstellaluna** [comment]
added beta label

**Comment by mstellaluna** [comment]
To give further details, searching via the search bar is inconsistent.  
there seem to be a few issues:

1) searching for ELEMENTS produces no results but elements gives results. Same if i search for CHECKBOX vs checkbox, uppercased search value isn't producing any results 

2) searching for words in challenge names is inconsistent. If I search for 'html' and I know we do have HTML in the title of some challenges its coming up empty 'no records to be found'. If I search for 'checkbox', titles of challenges appear with a description of the challenge.  

3) while searching I can search successfully the first time. If I erase and look up another term or the same one, nothing happens. I have to erase it again and wait about 5 seconds and it results a result. For example if I search flexbox the first time I get something, the second time nothing. Doesn't seem to respond to the enter key either, I have to wait that 5 second delay. This is intermittent and hard to reproduce

Screenshots:
For issue 1: 
lowercased search:
![image](https://user-images.githubusercontent.com/22984739/36757187-f2b3e224-1bde-11e8-8b7b-d49ff6a6804d.png)

uppercased search: 
![image](https://user-images.githubusercontent.com/22984739/36757336-4d36d940-1bdf-11e8-96ee-0cea25e7cfea.png)

For issue 2:  
![image](https://user-images.githubusercontent.com/22984739/36756951-777d2502-1bde-11e8-84dc-4d113edeaafe.png)

**Comment by Bouncey** [comment]
@moT01 thank you for finding this issue and @mstellaluna thank you for the extra information.

Please can you raise points 1 & 2 in the freecodecamp/search repo, as they are related to how we query the search engine.

Point 3 I cannot reproduce, but I think it should go to the freeCodeCamp/react-freecodecamp-search repo, as that holds the code for the the search bar, and I think it would be best resolved there.

Many thanks :+1:
