### ISSUE TITLE
flash messages sometimes don't show in Chrome

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16793]
Steps to reproduce:

1. Create a new account
2. claim a certificate, but don't accept the academic honesty pledge
3. attempt to view a certificate. In Firefox, you'll see a flash message:

![cursor_and_profile___freecodecamp](https://user-images.githubusercontent.com/985197/36754150-da64afac-1bcd-11e8-9ff2-d0bc84a79559.png)

But in Chrome you won't see the flash message - it will just redirect you to the profile with no flash message.

I'm using Chrome 64.0.3282.186 on MacOS.

**Comment by klamgade** [comment]
I am new about claiming certification in freecodecamp. Will this bug be only suitable or accessible to a member who has completed a course or a challenge? I am not sure if I can look on this bug. Please advise.

**Comment by leonfeng** [comment]
Cannot reproduce this issue. Maybe it got fixed recently?

I tried the _Front End Libraries Certificate_, _Data Visualization Certificate_, and _Information Security and Quality Assurance Certificate_. All had the flash message properly displayed at the top.

I'm using Chrome Version 65.0.3325.162 on MacOS.

**Comment by QuincyLarson** [comment]
@leonfeng Yes - it may have been fixed. Thanks for confirming this.
