### ISSUE TITLE
Waypoint Add Borders To Element

### ISSUE THREAD

**Issue by europaradise** [FreeCodeCamp/freecodecamp#1679]
I can't get this right.
I would like help in placing border elements in this waypoint exercise. 
![addborders](https://cloud.githubusercontent.com/assets/13596294/9156851/48d56712-3eb6-11e5-8f3f-2cb3cb8a2405.PNG)

**Comment by joysyu** [comment]
you're missing a hyphen :) you have 'thick-green border' instead of 'thick-green-border'.

**Comment by europaradise** [comment]
Ah! ha!
I see that.
Thank you. 
I have been staring at this for 3 hours now :)
