### ISSUE TITLE
Beta: First time users can't open map from other pages

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#16792]
#### Beta: First time users can't navigate to the map until they have selected a challenge

Here's what happened...
I created an account on beta for the first time and went straight to the settings page after logging in. From there I could not open the map. I was able to reload the base url to bring up the map page. I went to settings, and again could not open the map. It was only after reloading the home page again and **clicking on a challenge for the first time** that I was then able to bring up the map at any time.

The FCC Logo at the top left must perform the same action as the map button - because that had the same issue. It took me nowhere untill I had selected a challenge for the first time.

confirmed by @mstellaluna

**Comment by mstellaluna** [comment]
In my case, also from the settings page the map does not open. I have to go to my browser's address bar and head back to the beta's homepage to get the map to work.

**Comment by mstellaluna** [comment]
Here are some screenshots to give a visual of what is happening:

from the main page:
![image](https://user-images.githubusercontent.com/22984739/36758038-257578ec-1be1-11e8-8494-3a48bc0025f9.png)

from settings page:
![image](https://user-images.githubusercontent.com/22984739/36758158-92454d08-1be1-11e8-896d-2a0ef19155ff.png)
