### ISSUE TITLE
Multiple choice challenge bug

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16801]
Steps to reproduce: 

1. Start a multiple choice question challenge and answer one or more of the questions.
2. On the map, choose another multiple choice question challenge

You'll notice that whichever question you were on in the previous challenge, you'll stay on the subsequent challenge. 

Here's a gif that demonstrates this:

![multiple choice bug mov](https://user-images.githubusercontent.com/985197/36807109-a46606de-1c87-11e8-9530-f02cc56f49a3.gif)

**Comment by dbarraca** [comment]
I'm going to try tackling this bug.  Firsts, I'll have to read up on contributing to open source projects and freeCodeCamp bugs specifically.  I should be able to look more into this within the next few days

**Comment by QuincyLarson** [comment]
@dbarraca Awesome - consider this bug "assigned" to you. :) Please keep us posted, and if you need help, you can ask here or join gitter.im/freecodecamp/contributors
