### ISSUE TITLE
[Beta] Preview is improper during JS warning

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16804]
### Issue Description
On typing/editing, a JS warning comes up in the preview pane which distorts the preview. Here are some screenshots to clarify that. I'm seeing this issue since PR #16737 was merged. 

**When there's no JS warning: The preview is complete as all the eleven hellos are printed properly.**

![without js](https://user-images.githubusercontent.com/26724128/36833859-ceaff920-1d56-11e8-9d88-ed5ddcdd23ef.PNG)

**During JS warning: The tenth and eleventh hellos are not properly printed.**

![with js](https://user-images.githubusercontent.com/26724128/36833858-ce6dc06e-1d56-11e8-9e9c-a4f27ecb9e76.PNG)

### Browser Information
* Browser Name, Version: Chrome & Firefox.
* Operating System: Windows 10 Pro 32 Bit.
* Mobile, Desktop, or Tablet: Desktop.

**Comment by vkWeb** [comment]
@raisedadead Input on this?

**Comment by raisedadead** [comment]
Thanks @vkWeb !

**Comment by vkWeb** [comment]
@raisedadead Any idea how can this be solved? I tried tweaking the CSS but during JS warning it adds up a second scroll bar which is not desired.
