### ISSUE TITLE
[beta] Applied Responsive Web Design Projects - guide links are broken

### ISSUE THREAD

**Issue by a7mam7ma** [freeCodeCamp/freeCodeCamp#16812]
#### Challenge Name

Applied Responsive Web Design Projects

#### Issue Description

When i click get hint on any of the Applied Responsive Web Design Projects it redirects me to a non-existing guide url.

**e.g**
[build a tribute page](https://guide.freecodecamp.org/certificates/build-a-tribute-page)
[Build a Personal Portfolio Webpage](https://guide.freecodecamp.org/certificates/build-a-personal-portfolio-webpage)
#### Browser Information

* Browser Name, Version: Google Chrome Version 64.0.3282.186
* Operating System: Windows 7 32-bit

**Comment by mstellaluna** [comment]
@a7mam7ma Hello the projects do not have a Hint Guide for them. Within the instructions there is a working example link you can click on to view what is required. To find out the user stories, you need to click on the 'Run Tests' button and once its completed you need to select the green 'Tests' button to see the requirements.

**Comment by a7mam7ma** [comment]
@mstellaluna so get hint button should be disabled for projects, right?

**Comment by mstellaluna** [comment]
@a7mam7ma 
I agree, I suggest to leave this issue open so it can be reviewed and discussed.
Thanks for opening the issue.
Happy Coding !

**Comment by raisedadead** [comment]
Agreed.  I am of the opinion that the button could be removed for the projects

**Comment by QuincyLarson** [comment]
@raisedadead We have created stubs for the projects and do indeed want guide articles that correspond to the projects. 

We have an open PR on guides that will add these stubs - we're just working on a way to merge it: https://github.com/freeCodeCamp/guides/pull/8026
