### ISSUE TITLE
Beta - Add Different Margins to Each Side - Guide Page 404 Not Found

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16813]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/basic-css/add-different-margins-to-each-side-of-an-element

#### Issue Description

When selecting the 'Get Hint' button, it re-directs you to the guides but there is no guide page for this challenge.

Returns Page not found. 

#### Browser Information

Browser Name, Version: Chrome 64.0.3282.186 64-bit
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```
#### Screenshot

URL: https://guide.freecodecamp.org/certificates/add-different-margins-to-each-side-of-an-element

SCREENSHOT:

![image](https://user-images.githubusercontent.com/22984739/36883258-fac3a0fc-1da6-11e8-81b9-075a2781ed5d.png)

**Comment by Bouncey** [comment]
@mstellaluna, The guide does not have these pages as the challenges are not in production yet. As soon as the new challenges make it to the `master` branch, the guide will be updated

**Comment by mstellaluna** [comment]
Reason for close, see  https://github.com/freeCodeCamp/freeCodeCamp/issues/16817
