### ISSUE TITLE
Wiki request Adopt Bianca Mihai's articles into wiki entries

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#1681]
These could be spread out across several wiki articles:
Bianca's blog post: http://blog.freecodecamp.com/2015/06/10-steps-to-plan-better-so-you-can-write-less-code.html

Upcoming article: https://docs.google.com/document/d/1FA78Bt1Y-Rc5eDPHeYEDBJuxj1lWDOhw2oInP6ppZrE/edit

**Comment by AkiraLaine** [comment]
@QuincyLarson I can do this if you want :D

**Comment by awesomeaniruddh** [comment]
@AkiraLaine Why don't you get started? :) Thanks for volunteering!

**Comment by AkiraLaine** [comment]
@awesomeaniruddh its finished.
