### ISSUE TITLE
beta - set the font family of an element - passed without semicolon in CSS rule

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16811]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/basic-css/set-the-font-family-of-an-element

#### Issue Description

The challenge allows the code to pass when the semicolon is omitted from the CSS rule

#### Browser Information

Browser Name, Version: Chrome 64.0.3282.186 64-bit
Operating System: Windows 10 Pro 64-bit
Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js

  p {
    font-size: 16px;
    font-family: monospace
  }

```
#### Screenshot

CODE:
![image](https://user-images.githubusercontent.com/22984739/36868211-ac072c9a-1d65-11e8-8da8-74f965e09857.png)

CHALLENGE PASSED MODAL:

![image](https://user-images.githubusercontent.com/22984739/36868281-df2bad58-1d65-11e8-89b6-30d07ee5257b.png)

**Comment by christophherr** [comment]
Hi @mstellaluna, 
while it may not a best practice to omit the last semi-colon, it's valid.
https://www.w3.org/TR/CSS2/syndata.html#declaration
https://www.w3.org/TR/CSS22/syndata.html#declaration

**Comment by QuincyLarson** [comment]
@mstellaluna People should definitely use a semicolon, but we should probably have a greater discussion around whether we want tests to enforce this. For now I'm going to label this as a wontfix.
