### ISSUE TITLE
[Beta] Basic JavaScript - Mistake in example code

### ISSUE THREAD

**Issue by elvinasv** [freeCodeCamp/freeCodeCamp#16827]
#### Challenge
Javascript Algorithms And Data Structures - Basic JavaScript: Accessing Object Properties with Variables
https://beta.freecodecamp.org/en/challenges/basic-javascript/accessing-object-properties-with-variables 

#### Issue Description
There's a minor mistake in the second example. 
The example code says
```javascript
var someObj = {
  propName: "John"
};
function propPrefix(str) {
  var s = "prop";
  return s + str;
}
var someProp = propPrefix("Name"); // someProp now holds the value 'propName'
console.log(obj[someProp]); // "John"
```
![fcc-basic-js-example-code](https://user-images.githubusercontent.com/10553848/36944086-b421958c-1fc7-11e8-9cdb-3abbf9f89f00.png)

If you tried to run the code, it wouldn't print "John" in the console as variable _obj_ is not defined. 
I guess the last line was supposed to be 
```javascript
console.log(someObj[someProp]); // "John"
```

**Comment by tushar-nitave** [comment]
I will try to look into it.

**Comment by raisedadead** [comment]
Thanks @tushar-nitave I have left some comments on the linked pull request, can you please make a fresh one following our [Guidelines for Contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md), if you need any assistance, we are happy to offer assistance in our [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by shubhamivane** [comment]
If it is still open I would like to work on it.
