### ISSUE TITLE
No completed challenges are showing up in my profile page.

### ISSUE THREAD

**Issue by JonDevOps** [freeCodeCamp/freeCodeCamp#16823]
#### Challenge Name

All challenges

#### Issue Description

No completed challenges are showing up in my profile page as completed on the timeline.
Link to original issue description: https://forum.freecodecamp.org/t/ever-since-fcc-retired-third-party-sign-ups-the-progress-from-my-github-fcc-account-has-not-synced-with-my-email-fcc-account/177466/3

#### Browser Information

* Browser Name, Version: Mozilla Firefox Developer Edition
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: RCA 2 in 1 Tablet

#### Screenshot

![ ](https://i.imgur.com/KEBzSpA.png)

**Comment by JonDevOps** [comment]
I was rereading some other issues which also had the "support:accounts" label. Is this another "duplicate account" issue?

**Comment by raisedadead** [comment]
Seems likely to me. @QuincyLarson can you check and resolve?

**Comment by QuincyLarson** [comment]
@JonDevOps Thanks for your patience. You had a duplicate account which was obfuscating your progress. I've deleted it and now everything looks good again: https://www.freecodecamp.org/JonDevOps

@raisedadead this seems to be a systematic issue that we need to fix. I think it's been reported several times. There are a lot of people with duplicate accounts in the system. Do you have any ideas for how we could fix this, or elegantly detect and remove duplicate accounts?

**Comment by raisedadead** [comment]
@QuincyLarson this is going to be tricky with old accounts, that do not have an email associated with them. 

On production, the easiest way is to have a feature, where users can request account merging which can be done post review by us.

On beta, we will have email only login, meaning this could be a problem for anyone who does not have an email associated with their social profiles.

Can I check the analytics of how many users are still using the social logins which we have deprecated?

**Comment by QuincyLarson** [comment]
@raisedadead There are 218,084 accounts that don't have an email address associated with them.

**Comment by JonDevOps** [comment]
Is there any way to have users completed PROJECTS from one profile to be transfered to another NEW profile automatically(so you can tell old users to just create a new account and then go to setting and click "This" button to load all you challenges that are stored in the cloud from your other account to the new account, while automatically deleting the old account so you can only do the transfer once, and not have a bunch of people spam the same account and make a bunch of new accounts with it.)
