### ISSUE TITLE
Getting 522 (connection timed out) errors

### ISSUE THREAD

**Issue by mariniertje** [freeCodeCamp/freeCodeCamp#16834]
![522-error](https://user-images.githubusercontent.com/24515885/36959457-f4985af4-1ff6-11e8-9de4-4c2d03434816.JPG)

#### Issue Description

While completing challenges, i keep getting 522 errors and slow response times.

#### Browser Information

* Browser Name, Version:  Chrome v63.0.3239.132
* Operating System: Windows8.1
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js



```

**Comment by ayyanztech** [comment]
N#ñ#b ?rNV !h!h!k)c*cvcxçn ? Ndxcgx/n( jff ? Fkjj)&b!!v&vgc '

**Comment by Asjas** [comment]
Hi @mariniertje. Please refer to issue #16833. This should resolve on its own.
