### ISSUE TITLE
[BETA] When no challenges have been completed, timeline link in profile gives a 404 error

### ISSUE THREAD

**Issue by HPringles** [freeCodeCamp/freeCodeCamp#16836]
#### Challenge Name

FCC Beta Public Profile

#### Issue Description

 When clicking the "Not challenges have been completed yet. Get started here" link, it redirects to a nonexistent page.

1. Using a new profile where no challenges have been completed, navigate to the public profile for the user
2. Click the link at the bottom of the page "Get started here"
3.  A 404 error will be displayed

#### Browser Information

* Browser Name, Version: Chrome 64.0
* Operating System: Windows 10 Educational
* Mobile, Desktop, or Tablet: Destop

#### Your Code

*N/A

#### Screenshot

![timeline](https://user-images.githubusercontent.com/16962690/36972061-ae61595e-2065-11e8-891e-a359261d5a87.png)
![404](https://user-images.githubusercontent.com/16962690/36972069-b5c69a88-2065-11e8-99ed-f88ac18a3eb1.png)

**Comment by harryingles** [comment]
I will be looking into this issue myself

**Comment by harryingles** [comment]
After a quick look through the code for this. I have located the error : common/utils/constantStrings.json is expected to have homeUrl however this has not been created.

**Comment by Bouncey** [comment]
That is weird the linting didn't pick this up.

Are you OK to submit a PR for this @harryingles?

**Comment by harryingles** [comment]
I will be looking tonight
