### ISSUE TITLE
Beta - Dark Mode - Incorrect flash notification

### ISSUE THREAD

**Issue by HPringles** [freeCodeCamp/freeCodeCamp#16835]
#### Challenge Name

FCC Beta Profile

#### Issue Description

When selecting dark theme, flash notification at the top of the page does not conform to night mode settings.

It is also a different style of flash notification to the other account updates(e.g making solutions private) and has some padding issues in chrome.

Steps to reproduce : 

1. Navigate to profile page in beta
2. Turn on night mode
3. Incorrect flash notification will appear

#### Browser Information

* Browser Name, Version: Google Chrome 64.0
* Operating System: Windows 10 Education
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

*N/A
```js
```
#### Screenshot

![nightmode](https://user-images.githubusercontent.com/16962690/36971313-59361098-2063-11e8-891e-a5fd56d8634f.png)

**Comment by harryingles** [comment]
I intend to fix this bug myself - However I am new, so it may take a couple of days to get the PR sorted out.

**Comment by raisedadead** [comment]
@harryingles thanks for your interest, however this may be differed until later. Sure, we need a little tweaking, but it can wait for now, where we have a feature freeze.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (109/100 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:38782)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUNz-0005jj-C6
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:35 -0400
Received: from out-1.smtp.github.com ([192.30.252.192])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUNh-0006Gl-KQ
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:17 -0400
Date: Sun, 03 Jun 2018 07:53:16 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037596;
	bh=UBDCWUntFlHTREbrHOzu/CnhszSXvMDFrCS0D8m76w0=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=oWx90XsBmKf5c46Y1UOQCNpLliOwnpt8k/aVAMENzN/Rt2cM+APbB1Ygxe8gzxIMe
	 DHtFoQB2cid3FSDx3T2/Db4OCz/vBQEJBtbD3gCqg+OEwmqPnDxAL3YWihYOrlUV6L
	 blOHKuJXMbwyeBERXGwn10Ru3bGt5BRVeB3+1hOQ=

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (110/100 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:38862)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUO6-0005qP-8U
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:42 -0400
Received: from out-3.smtp.github.com ([192.30.252.194])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUO3-0006HR-E6
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:53:39 -0400
Date: Sun, 03 Jun 2018 07:53:38 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037618;
	bh=y5pwgBcAGSx6RMOAo7NSSrHOXlv9ATDP1cFMs5cQswA=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=cw/wiIItsJGCz8CflVYxQ6kXmRW+TMiIp/ETEyFUSGWQIRWxahevoTyTIdRLjdX0n
	 DC9xhLdJqiv3XeCcmZ4hVbygNvy9G/TQiDY9nzHQgc0r/uQyLVZxn46m1tPQw1Rj/7
	 KyhdPxtQUw5OwdNkJTag2LhuI/8/JDN+QfxZ09wU=
