### ISSUE TITLE
FreeCodeCamp.org is down -- 522 - Connection Time Out - Flaky Response

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16833]
#### Challenge Name

http://freecodecamp.org/

#### Issue Description

Production FreeCodeCamp.org is down, it is being reported by several users
I verified and cannot reach the site 

FCC Forum does not appear to be affected ... 

It seems to be flaky connection, it recovers and crashes again 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![image](https://user-images.githubusercontent.com/22984739/36958035-de91de46-2006-11e8-9984-be508d3a2284.png)

**Comment by mstellaluna** [comment]
@QuincyLarson @BerkeleyTrue @Bouncey  FYI !

**Comment by BerkeleyTrue** [comment]
Thank you. DO is currently experiencing connectivity issues. I'll be monitoring while they fix the issue. As soon as they do everything should return to normal on it's own.

Happy Coding

**Comment by mstellaluna** [comment]
@BerkeleyTrue Thank you for the update ! Greatly Appreciated.

**Comment by BerkeleyTrue** [comment]
Thanks for pinging us. Unfortunately there is not much we can do at this moment

**Comment by BerkeleyTrue** [comment]
Looks like DO has resolved the issue. I'm gonna get some sleep. Good night all and happy coding
