### ISSUE TITLE
Add "Spread syntax" MDN link to the Sorted Union exerices

### ISSUE THREAD

**Issue by paulcarroty** [freeCodeCamp/freeCodeCamp#16846]
#### Challenge Name

https://www.freecodecamp.org/challenges/sorted-union

#### Issue Description

The patch is here: https://github.com/freeCodeCamp/freeCodeCamp/pull/16840

This case is described in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) together with `Function.prototype.apply`.

I think it will be a good addition to the helpful links.

**Comment by Asjas** [comment]
@paulcarroty You are linking to `www.freecodecamp.org` but the PR you submitted is targeting `beta.freecodecamp.org`. You are aware of this?
