### ISSUE TITLE
[Beta] Preview Pane resizing Bug

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16843]
### Issue Description
I recently noticed that on resizing the preview pane, it acts in an unexpected manner. 

**Steps to reproduce:** 
1. Try resizing other panes i.e. lesson, map, editor. They resize smoothly. 
2. Then resize the preview pane and you'll see that sometimes it get stuck on a particular point.  

I'm not uploading a GIF because there was a considerable amount of lag.
### Browser Information
* Browser Name, Version: Tested on Chrome(64.0.3282.186) and Firefox(58.0.2)
* Operating System: Windows 10 Pro 32 Bit.
* Mobile, Desktop, or Tablet: Desktop.

**Comment by moT01** [comment]
@vkWeb I noticed this as well - it seems to be when you move your mouse too fast it will get stuck. If you go real slow the resizing will work.

**Comment by vipatron** [comment]
I third this. Thank you @moT01. Whatever is causing this "sticky" behavior doesn't seem to activate if you sloooowly drag the resize bar.

Browser: Firefox 58.0.02
OS: Windows 8.1 64-bit
Device: Desktop

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (116/100 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:39835)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUQD-0007TO-V1
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:55:54 -0400
Received: from out-15.smtp.github.com ([192.30.254.198])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUPo-0006OO-JQ
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:55:28 -0400
Date: Sun, 03 Jun 2018 07:55:26 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037727;
	bh=Ak9mD6np5LEH/zn4injgJers78XJ+vPiOgCQs7abt7I=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=gVqKkgWVbr2yfd/a8e4P0xANaWoOc3nlK3RS2cNdOdwlurtWl57hKi7iTIJlsL1BA
	 Q5hYE5MOYVGedoFkcv2KgDbQPHGNySFwLcCnlaE+UqoY2eMzwYJU7LTFN64oIxe5cB
	 IuOuOGSOJ5tSu1F6BueH3cHhXEslsCYe7Rz1nWQ8=

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (115/100 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:39831)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUQD-0007TF-So
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:55:53 -0400
Received: from out-3.smtp.github.com ([192.30.252.194])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUPf-0006Ma-C8
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:55:19 -0400
Date: Sun, 03 Jun 2018 07:55:16 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037716;
	bh=s0yKwFzlZP5jYLhxv/xqNWLjlaw/xs17TLzX3dwiFPg=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=TYp7sPwvCcU0GRm+CqGNX0igdwI6fp02/I8kkFF5L0L3+o1NWVFN0ocCSmrqSvcjk
	 XwWw8N3B8YdfubTOn8fNq4SxQDVhXU3dy48WKUyLpAlgs+/pKD8f2qM6wOGtstamu6
	 pCUl9cLlwvMqX3KVdAZBGAkkaLzw27bXE06wjjoE=
