### ISSUE TITLE
Create logic that redirects old challenge URLs to new beta URLs

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16858]
For example, `/challenges/check-for-palindromes` should redirect to `/en/challenges/javascript-algorithms-and-data-structures-projects/palindrome-checker`

[Here is a full list of current challenges on production](https://gist.github.com/QuincyLarson/c21fde97e43a27618694f12f3ee9e25a).

In situations where these lack a beta equivalent, they can just redirect to /map

Note that all existing projects still exist on beta, though some of them have been moved to the interview-prep section.

**Comment by BerkeleyTrue** [comment]
We discussed this a while ago. This is quite an expensive endpoint and we decided to remove it.

**Comment by raisedadead** [comment]
I agree, having to search though all of the challenges. 

Maybe we should have the 404 with an additional pre-filled form for a search query (that re-uses the search) as a tradeoff?

**Comment by BerkeleyTrue** [comment]
@raisedadead sounds like a great idea, that off loads the work from the servers.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue @raisedadead I'm not proposing a regex search. Rather, I'm suggesting that we take all the existing challenge URLs and map them to the new locations of those challenges. There are only a few hundred of them. Yes - this would represent some complexity, but it would give users what they expect when they follow a link - the latest version of that challenge.

**Comment by raisedadead** [comment]
Okay, I see what you mean is a direct one to one mapping of the challenge? 
If yes do we have such a list? I am okay with the idea as long as we have a static mapping.

**Comment by QuincyLarson** [comment]
@raisedadead We will need to create a list manually and just hard-code the redirects. It should be pretty high performance. It will just be an ugly part of the codebase. This would be a good help wanted issue.

**Comment by QuincyLarson** [comment]
@raisedadead Where would be the best place to put this new routing logic?

**Comment by QuincyLarson** [comment]
@raisedadead @BerkeleyTrue I've updated the issue description and attached a link to all of the current production challenge URLs.

**Comment by joker314** [comment]
I've started making a mapping between the old links and the new ones. @QuincyLarson out of interest, how did you generate your list?

I'd like to check a few things, from what I've encountered so far
 - `beta` doesn't have a `/videos` endpoint for video lessons
 - `beta` doesn't have certificates for projects other than the JS one

Here is what I have so far. Each completed URL is associated with three lines, in the form

```
OLD
NEW
<blank line>
```

**Comment by joker314** [comment]
Okay, so I've made quite a bit of progress. I've now manually mapped about 100 endpoints. I've got another 300 to go.

While I was at it, a few points for us to discuss arose.

First of all, the JSON API & AJAX section used to be very jQuery oriented. It is now, however, composed of vanilla JavaScript.

 - Do we map these jQuery links to their JavaScript equivalents, or do we just send these users to the map because they probably wanted to learn jQuery? (I've done the former, but this can be changed)

Secondly, the below endpoint

```
/challenges/get-set-for-our-api-development-projects
``` 

is the introduction for the `API and Microservice Projects` section in freeCodeCamp. But that's the problem, it's an entire section, not a challenge, and it lacks an introduction like the old version does.

So what do we do? The link is clearly pointing to a thing in the beta, and it would be incredibly annoying to send them to the map even though we know what they want to see.

 - Do we send the user to the first project in that section (what I'm doing at the moment, but can be changed), or, do we send the user to the map [is there a way to highlight a particular section in the map; a bit like the suggestion in #16902]

I'd love to hear your thoughts on what should be done about the above two issues.

**Comment by QuincyLarson** [comment]
Hi @joker314 thanks for your work on this so far! To answer your questions individually:

> @QuincyLarson out of interest, how did you generate your list?

I used https://www.freecodecamp.org/sitemap.xml and filtered out the challenge URLs. 

> beta doesn't have a /videos endpoint for video lessons

Yes - we can ignore those video links - we don't need to redirect them.

> beta doesn't have certificates for projects other than the JS one

I'm not sure what you mean here. The projects themselves have beta equivalents (though some of them may be in the Interview Prep > Takehome Projects section.

> Do we map these jQuery links to their JavaScript equivalents, or do we just send these users to the map because they probably wanted to learn jQuery? (I've done the former, but this can be changed)

Please use your best judgement on these. In this case, I think you're correct in linking to the JavaScript equivalents.

> Do we send the user to the first project in that section (what I'm doing at the moment, but can be changed), or, do we send the user to the map [is there a way to highlight a particular section in the map; a bit like the suggestion in #16902]

We don't yet have a way to link directly to an entire section of the map. https://github.com/freeCodeCamp/freeCodeCamp/issues/11060

**Comment by QuincyLarson** [comment]
This has been completed.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (122/100 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:40901)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUSQ-0000qv-5f
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:58:10 -0400
Received: from out-7.smtp.github.com ([192.30.252.198])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPURZ-0006U4-DU
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:57:17 -0400
Date: Sun, 03 Jun 2018 07:57:16 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037836;
	bh=gCMLjzEn1o1gP+wtVbrJ9J9NKCGDY7DZ2TvYeJLXSZs=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Chj2b7HVSvSOeJtTzZEoThCUl1WQ55IvCQHz+K/eXkS9aMQkJRr5Td3qDY3LMxwd0
	 dkWdNWRxYfsocezVzLWA/bH4QFtq19poEGmrJ22dASefGe/D/jwVxbaUeRzX1X4QAC
	 ACQaXO86Gj5XuTyp3a4qN2I/8VenuXR35gndckWY=
