### ISSUE TITLE
Beta - CSS Grid - Use grid-column to control spacing - Add Visual Reference

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#16852]
#### Challenge Name

http://localhost:3000/en/challenges/css-grid/use-gridcolumn-to-control-spacing

#### Issue Description

There isn't an issue with the challenge itself
But campers may have an issue visualizing the grid lines referred to in the challenge without a visual aid
Two possibilities.
Either:

1) we can add an external link to an image or reference documentation
2) add them to the preview

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

 ORIGINAL PREVIEW:
![image](https://user-images.githubusercontent.com/22984739/37154351-b6ffcd58-22ad-11e8-9ad3-a12a716e9162.png)

SUGGESTION 1: ADD EXTERNAL RESOURCE LINK: 
[css-tricks](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-names.png)

SUGGESTION 2: ADD TO PREVIEW - so something like this I guess
![image](https://user-images.githubusercontent.com/22984739/37154384-d3a098a2-22ad-11e8-8b93-bf2749d081d6.png)

**Comment by ahmadabdolsaheb** [comment]
@mstellaluna @moT01 adding a visual reference is a great idea.
option 1 is easier. maybe we make a simple diagram internally for this challenge. 
option 2, adding the lines is also easy. I could just add a border to the cells; however, I am not sure if it would be helpful unless we started adding text and numbers outside the grid which might make the seed more complicated.

**Comment by moT01** [comment]
@ahmadabdolsaheb @mstellaluna - there really isn't an easy way to just add the lines on the grid itself, I'm sure we could figure that out if we want, but I propose this...

`The hypothetical horizontal and vertical lines that create the grid are referred to as lines. These lines are numbered starting with 1 at the top left corner of the grid and count right for columns:`
![columnlines](https://user-images.githubusercontent.com/20648924/37308314-a25f9746-260b-11e8-9853-a71d3646d692.png)

`And down for rows:`
![rowlines](https://user-images.githubusercontent.com/20648924/37308315-a529967a-260b-11e8-8829-fde35e9bd8d4.png)

Add some images with a little change of the description. What do you think?

**Comment by mstellaluna** [comment]
@moT01 @ahmadabdolsaheb you mean to the lesson? I think that would be easiest. Kind of how I believe its the anchor challenge in the basic HTML has a image in the lesson..

**Comment by moT01** [comment]
Yes @mstellaluna, those images would be directly in the description is what I had in mind.

**Comment by moT01** [comment]
I can add those

**Comment by mstellaluna** [comment]
@moT01 @ahmadabdolsaheb  yea that is easiest way and the camper can always easily refer back to it

**Comment by ahmadabdolsaheb** [comment]
@moT01 @mstellaluna On the side note, would combining the two pictures save some space?

**Comment by moT01** [comment]
@raisedadead hey, you said we dont want images in challenge descriptions, I had that planned for this - what if I just put the image in the seed code and it shows up in the preview?

**Comment by moT01** [comment]
okay, if we dont want images in the description - thats the new plan - put it in the seed code and show it in the preview... I see some other images hosted on aws @mstellaluna I think you were right there - it looks like there's a freecodecamp account - do any of you know who can put a picture there for me? here's the new pic...
![gridlines](https://user-images.githubusercontent.com/20648924/37381880-b2ba723e-270d-11e8-85d7-ce69c462f216.gif)

**Comment by mstellaluna** [comment]
I don't have access to the AWS account, I'm not sure who does.

**Comment by raisedadead** [comment]
@QuincyLarson can upload them to the bucket for you.

**Comment by raisedadead** [comment]
You can share a link or the image in this thread

**Comment by QuincyLarson** [comment]
@mstellaluna we have eliminated all images from freeCodeCamp's curriculum in favor of text-based explanations. There are a number of reasons for this (performance, offline capability, accessibility).

Instead of using an image, since this is a pretty simple thing, could we just build this using HTML and CSS and show it in the Preview section of the challenge, then have the camper interact with it some how?

**Comment by moT01** [comment]
How does this look? https://codepen.io/moT01/pen/OQqKyq?editors=1000

**Comment by ahmadabdolsaheb** [comment]
@moT01 looks good.

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb Yes - this looks great! You might also try just adding this to the lesson text since we can add HTML in there. That would simplify how the Preview pane and code editor look.

**Comment by ahmadabdolsaheb** [comment]
@QuincyLarson @moT01 the challenge seed only accepts inline html styling and writing inline animations is not possible. So i converted the styles to inline styles and removed the animation.
here is what I got:
https://codepen.io/abdolsa/pen/qomKEe
let me know if it needs improvements or not. thanks

**Comment by moT01** [comment]
@ahmadabdolsaheb looks good to me :smile:
