### ISSUE TITLE
Flash messages need a margin

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16857]
Flash messages need a margin on top so they're not smashed up under the navbar.

![sign_in_to_freecodecamp_using_your_email_address___freecodecamp](https://user-images.githubusercontent.com/985197/37184698-57041008-2302-11e8-871c-cc8279829a01.png)

**Comment by mackmmiller** [comment]
I'd like to take this on if no one else is yet.

**Comment by QuincyLarson** [comment]
@mackmmiller Great! Thanks for tackling this one. Please keep us posted on your progress :)

**Comment by vkWeb** [comment]
@mackmmiller  Brother, I'm sorry that I took your issue. Actually, when I was fixing #16860, this issue seemed obvious to me as the changes required were related. 

There are a lot of issues we need help with. you can explore them [here](https://github.com/freeCodeCamp/freeCodeCamp/projects/1?fullscreen=true). 😄

**Comment by mackmmiller** [comment]
@vkWeb, not a problem. Hadn't even started yet.
