### ISSUE TITLE
Signing into an account that most recently completed a non-beta challenge causes a 404 error

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#16862]
Steps to reproduce:

1. Checkout the backup/master branch
2. Complete a challenge
3. Switch to the staging branch
4. Attempt to sign in. The platform will attempt to redirect you back to your next challenge, but that challenge URL will have changed.

For example: `/challenges/check-for-palindromes` on backup/master becomes `/en/challenges/javascript-algorithms-and-data-structures-projects/palindrome-checker` on staging

Screenshot of what happens when you sign in:

![404___freecodecamp](https://user-images.githubusercontent.com/985197/37191598-47cc33c6-2326-11e8-9da6-f45da93ff1ea.png)

This is a high-priority bug that will affect all existing freeCodeCamp accounts when we migrate to beta if we don't fix this first.

This may be fixable by fixing https://github.com/freeCodeCamp/freeCodeCamp/issues/16858

**Comment by BerkeleyTrue** [comment]
how is this not the same as #16858?

**Comment by QuincyLarson** [comment]
@BerkeleyTrue We should not be redirecting newly signed in users to a 404 page.

One way to fix this might be to remove the "currentChallenge" property from all user records so that it just redirects to the first challenge.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (120/100 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:40459)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPURR-000064-46
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:57:09 -0400
Received: from out-3.smtp.github.com ([192.30.252.194])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPUQl-0006RR-I7
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:56:27 -0400
Date: Sun, 03 Jun 2018 07:56:26 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037786;
	bh=l/0MHoeItY4+pPX7/s8eCKm2en7MZQOE1WkqtvhfHgs=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=bST0IHnEFM6ffg04T1DLeUoLhBzVeuFR4LrKzVY0iSSAqm01WRArCKoWmENVudlaL
	 OZN0xhfmb5QebdIqT0bSPZqOHXKn0KlExLp3R1h1ZhXwNX16iOfNZaO0yC/QT1gozI
	 JWoxmIloomkglolSsKe4Cd+z+oI2BU1ddoqGMjPk=
