### ISSUE TITLE
[Beta] Default Project view should be changed

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16863]
### Issue Description
@QuincyLarson The default project views i.e. when there are only two panes on the workspace viz. Map and main, the view is divided in the ratio 1:1(map and main occupy equal width). e.g. [Implement the Serialization of a Passport User](https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/implement-the-serialization-of-a-passport-user) or any project view. 

**The default view:**
![before](https://user-images.githubusercontent.com/26724128/37197462-e0d582f0-23a0-11e8-9b93-91c92a700c28.PNG)

**The Proposed default view:**
![after](https://user-images.githubusercontent.com/26724128/37197484-f2b6eae0-23a0-11e8-8740-4e4f82df0952.PNG)

I think we should give the main section more width as shown in the screenshot above which will greatly increase the readability and overall UX of a user.

**Comment by QuincyLarson** [comment]
@vkWeb Thanks for the feedback. Yes - I agree - when there are only two panes, the lesson pane should have most of the width by default (users should still have the freedom to drag the map to expand it).

**Comment by rajatkantinandi** [comment]
Trying this for the first time.
Hope I succeed

**Comment by QuincyLarson** [comment]
@rajatkantinandi Great! Please keep us posted on your progress on this.

**Comment by vkWeb** [comment]
@rajatkantinandi We'll be waiting for your PR! :)

**Comment by rajatkantinandi** [comment]
I think changing the common/app/Panes/redux/util.js and adding following code in the function get DividerLeft will make the map 33% & main pane 67% which by default when we have 2 panes only.
I am unable to test this feature.
Can anyone test it & confirm??

```js
  if (numOfPanes === 2 && numOfPanes !== index + 1) {
    dividerLeft = 33;
  } else if (numOfPanes > 1 && numOfPanes !== index + 1) {
    dividerLeft = (100 / numOfPanes) * (index + 1);
  }
```

**Comment by rajatkantinandi** [comment]
I am having trouble setting up the freecodecamp clone website run on my pc.
I am using VSCode coupled with bash on windows as my integrated terminal.
I have npm, node,  mongodb installed also eslint.
npm install works but npm run shows bunch of errors & having trouble fixing them.
Also having trouble setting up mailhog.
Where can I get a detailed guide to setup the whole process?
Can anyone provide some links??
I can't test my changes.
