### ISSUE TITLE
Running code in isolation, when global declarations are used

### ISSUE THREAD

**Issue by ogzcoder** [freeCodeCamp/freeCodeCamp#16872]
#### Challenge Name
[Steamroller](https://www.freecodecamp.org/challenges/steamroller) in Intermediate Algorithm Scripting

#### Issue Description
I used a recursive function to complete this challenge and when tested the called challenge function returns the correct value but my challenge is not marked as completed and the tests do not pass. 

#### Browser Information
Chrome Version 65.0.3325.146 (Official Build) (64-bit) on Windows 10 x64 (Desktop)

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js

var newArr = [];

function testArr(item){
  if (Array.isArray(item)) {
    for (let i = 0; i < item.length; i++) {
      testArr(item[i]);
    }
  } else { 
    newArr.push(item);
  }
}

function steamrollArray(arr) {
  // I'm a steamroller, baby
  for (let i = 0; i < arr.length; i++){
    testArr(arr[i]);
  }
  return newArr;
}

steamrollArray([1, {}, [3, [[4]]]]);


```
#### Screenshot

![2018-03-12](https://user-images.githubusercontent.com/24999870/37273879-473379be-2598-11e8-8fb5-638a893b575e.png)
![2018-03-12 1](https://user-images.githubusercontent.com/24999870/37273880-4753d18c-2598-11e8-8872-b0f2e6cf4789.png)
![2018-03-12 2](https://user-images.githubusercontent.com/24999870/37273881-47753746-2598-11e8-81b0-684b10964d96.png)
![2018-03-12 3](https://user-images.githubusercontent.com/24999870/37273882-479339f8-2598-11e8-930e-be4e4de54150.png)

**Comment by raisedadead** [comment]
Yes, this is a platform limitation with use of global methods. 
While its also not recommended to use globals, I understand that this intent is not very clear. 

The tests are not run in isolation, and hence the last value of your globals persist, breaking them.

We of course can't make any changes, to the current production at freeCodeCamp.org, however we should discuss the possibility of at least making the intent known in some form on beta.

Same challenge on beta, for reference debugging:
https://beta.freecodecamp.org/en/challenges/intermediate-algorithm-scripting/steamroller
Originally reported in https://github.com/freeCodeCamp/freeCodeCamp/issues/9063

**Comment by raisedadead** [comment]
Hi @BerkeleyTrue I believe you have been working on overhauling the testing logic, do you think there is a way to clarify the intent here, maybe with a notification for use of globals?

**Comment by BerkeleyTrue** [comment]
I believe @Bouncey solved this on beta a while back. If globals are introduced, the lint will will fail to run.

**Comment by Bouncey** [comment]
@BerkeleyTrue that was enabling linting errors in the editor if the campers code would overwrite a global variable like `name` and such like.

The problem here is the global `newArr`, it never gets reinitialized. 

A second/third/fourth/fifth function declared in global scope will not cause the tests to fail.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
