### ISSUE TITLE
Beta - CSS Grid - CSS Grid should be capitalized in the challenges.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#16870]
#### Challenge Name

All CSS Grid Challenges

#### Issue Description

CSS Grid should be capitalized in the title of the challenges.
To fix this issue, 'css-grid': 'CSS Grid', should probably be added after line 5 in the blockNameify function linked below.
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/utils/blockNameify.js#L5

#### Screenshot

![screen shot 2018-03-01 at 15 55 31](https://user-images.githubusercontent.com/4591597/37267150-826bbcda-25cf-11e8-9ff8-7fb6abbf71b3.png)

**Comment by ahmadabdolsaheb** [comment]
I would like to work on this issue if possible.

**Comment by raisedadead** [comment]
@ahmadabdolsaheb sure thing
