### ISSUE TITLE
Beta/Responsive Web Design/CSS Flexboxes Not displaying

### ISSUE THREAD

**Issue by vipatron** [freeCodeCamp/freeCodeCamp#16878]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/css-flexbox/use-display-flex-to-position-two-boxes
https://beta.freecodecamp.org/en/challenges/css-flexbox/use-the-flexdirection-property-to-make-a-row
https://beta.freecodecamp.org/en/challenges/css-flexbox/use-the-flexdirection-property-to-make-a-column

#### Issue Description

The blue and orange flexboxes don't display because they contain no content, and thus have no height enforced on them.

**Kludgy solution:** Even adding a single character between the div tags fixes the problem. I used "a" and "b" for #box-1 and #box-2 respectively. Whitespace does not fix the problem.

Example kludgy hack code in the above links:
```
<div id="box-container">
  <div id="box-1">a</div>
  <div id="box-2">b</div>
</div>
```

**Elegant solution:**  Actually, I stole it from another "theory challenge" in the in CSS-flexbox unit - (https://beta.freecodecamp.org/en/challenges/css-flexbox/align-elements-using-the-justifycontent-property)

In all the problematic challenges, I was able to modify the CSS for the div "#box-container" to add a height, and it fixed the problem. 
` #box-container {
    height: 25%;
  }`

#### Browser Information

* Browser Name, Version: Firefox 58.0.2
* Operating System: Windows 8.1 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
#box-container {
    height: 25%;
  }
```

**Comment by PolarisTLX** [comment]
Have this resolved and creating pull-request shortly.

**Comment by mstellaluna** [comment]
@PolarisTLX I tested your changes in firefox and in chrome. Looks great to me :) I will go ahead an approve the changes. Great Job. Thank you for contributing. Happy Coding !
