### ISSUE TITLE
Beta - CSS Grid - Challenge titles should be properly capitalized.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#16873]
#### Challenge Name

All CSS Grid Challenges

#### Issue Description

The titles of the challenges in CSS-Grid should be properly capitalized. 

e.g. "Add columns with grid-template-columns" should be changed to "Add Columns with grid-gemplate-columns"

Note: the CSS properties in the title should not be capitalized, and CSS should always be capitalized.

This is the file to that contains the CSS Grid challenges: 
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/css-grid.json

The following is the title of the challenges that need changing:

- Create your first CSS Grid
- Add columns with grid-template-columns
- Add rows with grid-template-rows
- Use CSS Grid units to change the size of columns and rows
- Create a column gap using grid-column-gap
- Create a row gap using grid-row-gap
- Add gaps faster with grid-gap
- Use grid-column to control spacing
- Use grid-row to control spacing
- Align an item horizontally using justify-self
- Align an item vertically using align-self
- Align all items horizontally using justify-items
- Align all items vertically using align-items
- Divide the grid into an area template
- Place items in grid areas using the grid-area property
- Use grid-area without creating an areas template
- Reduce repetition using the repeat function
- Limit item size using the minmax function
- Create flexible layouts using auto-fill
- Create flexible layouts using auto-fit
- Use media queries to create responsive layouts
- Create grids within grids

Happy contributing.

**Comment by ahmadabdolsaheb** [comment]
@raisedadead probably first timers friendly.

**Comment by ashutupa** [comment]
Hi,
I am going to contribute for the first time.
What i understood with the description that we have to capitalized the title in `css-grid.json` file.
let me know how to proceed and whether my understanding is correct or not?

**Comment by raisedadead** [comment]
Hi @ashutupa welcome to contributing to this codebase. 

We would want to normalize the titles of the challenges as mentioned in the OP
like so:

"Add columns with grid-template-columns" should be changed to "Add Columns with grid-gemplate-columns"

You should follow our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and reach us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for any assistance.

**Comment by ashutupa** [comment]
Thanks,
let me proceed with setup and update my progress here.

**Comment by ashutupa** [comment]
Hi guys,
I have done with my setup and created a PR, Who approves/reviews the PR?

**Comment by mstellaluna** [comment]
@ahmadabdolsaheb I finished reviewing your PR.  Looks good to me. I will go ahead and approve the changes.

**Comment by ashutupa** [comment]
Thanks,It was nice way to be hooked into process of committing for a first-timer.

**Comment by ahmadabdolsaheb** [comment]
@ashutupa Great job. 👍
