### ISSUE TITLE
Beta - CSS Grid - Three Typo Corrections

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#16871]
#### Issue Description
The following is a list of needed corrections that needs to be implemented. 

1. Change __5px of the grid's height__ to __5px tall__
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/css-grid.json#L279

2. Change __\<cod>20px\</code>__ in the test message with __\<code>20px\</code>__ ( missing __e__)
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/css-grid.json#L328

3. Change __between the first and forth horizontal lines and between the third and forth vertical lines__ to __between the third and forth horizontal lines and between the first and forth vertical lines__ .
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/css-grid.json#L819

**Comment by raisedadead** [comment]
Sorry, I am a bit lost in the exact behavior here?

**Comment by ahmadabdolsaheb** [comment]
@raisedadead there are a couple of challenges that have typos or some sentences need to be changed. I was not sure If I need to make issues for them one by one or bundle them together in one issue since they are minor issues.

**Comment by raisedadead** [comment]
Ah the "bundle" word threw me off. 

Sure if you could link the files to be changed in the opening post, we can open this to potential first time contributors. 

Thanks for reporting!

**Comment by ahmadabdolsaheb** [comment]
@raisedadead I modified the description and added the files and line numbers.

**Comment by ganes1410** [comment]
@ahmadabdolsaheb  @raisedadead  can i take this up ??

**Comment by raisedadead** [comment]
@ganes1410 sure thing, here are our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) and you can reach us in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for any assistance.

**Comment by ganes1410** [comment]
@ahmadabdolsaheb  @raisedadead for that third typo is it fourth or forth

**Comment by raisedadead** [comment]
Yes its numeric `fourth`. Thanks for catching.
