### ISSUE TITLE
[Beta] Basic HTML and HTML5, inconsistent closing methods for input element

### ISSUE THREAD

**Issue by miwojc** [freeCodeCamp/freeCodeCamp#16880]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/basic-html-and-html5/add-placeholder-text-to-a-text-field

#### Issue Description

input tag description is inconsistent within the beta freeCodeCamp. Sometimes is "self closed" by "/>" and sometimes is just closed by ">". Suggestion: align to the way it is described at Mozilla and w3school, that is closing by ">"

#### Browser Information

* Browser Name, Version: Google Chrome, Version 65.0.3325.146 (Official Build) (64-bit)
* Operating System: macOS High Sierra
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js



```
#### Screenshot

![screen shot 2018-03-12 at 9 25 44 pm](https://user-images.githubusercontent.com/32404415/37317563-ffc35118-263b-11e8-9ad8-9f728c8e2cc2.png)
![screen shot 2018-03-12 at 9 26 47 pm](https://user-images.githubusercontent.com/32404415/37317579-17c41234-263c-11e8-8761-9049544e908c.png)

**Comment by MarkusToe** [comment]
Hello! If this issue is still to have, I would like to volunteer.

**Comment by YogeshSharma0201** [comment]
In the latest version of the code base, the input tags are closed by ">" and not "/>", so i don't this is an issue any more

Screenshot, when i ran it locally:
![input](https://user-images.githubusercontent.com/21025052/37328304-b1ce15f4-26bf-11e8-9253-caede252c23e.png)
