### ISSUE TITLE
Beta/Responsive Web Design/CSS Grid Errata (Row/Column transposition)

### ISSUE THREAD

**Issue by vipatron** [freeCodeCamp/freeCodeCamp#16881]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/css-grid/use-gridarea-without-creating-an-areas-template

#### Issue Description

Instructions for the challenge don't match the automated checks. (rows & columns are transposed)

The theory blurb states: 
>item1 { grid-area: 1/1/2/4; }
>The numbers in the example above represent these values:
>grid-area: horizontal line to start at / vertical line to start at / horizontal line to end at / vertical line to end at;

The challenge instructions state:
>Using the grid-area property, place the element with item5 class between the first and forth horizontal lines and between the third and forth vertical lines.

#### Browser Information

* Browser Name, Version: Firefox 58.0.2
* Operating System: Windows 8.1
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
  .item5 {
    background: PaleGreen;
    /* add your code below this line */
    grid-area: 3/1/4/4;
    
    /* add your code above this line */
  }
```
#### Screenshot

The results of following the instructions:
![image](https://user-images.githubusercontent.com/36994955/37320057-4fe92954-2648-11e8-89a7-cf2b8b59989c.png)

**Comment by moT01** [comment]
Thanks for pointing this out @vipatron, however, there's already an open issue for this. https://github.com/freeCodeCamp/freeCodeCamp/issues/16871
The third problem in that issue will solve this - and if you follow those instructions you can pass the tests. 
You should close this issue since it's being fixed.

**Comment by vipatron** [comment]
I was spending so much time crafting this huge explanation all marked-down nicely. Haha. Will close. Thanks!

**Comment by moT01** [comment]
@vipatron and a great explanation it is. Be sure to search for your issue before creating - although that one might be tough to find even if you did.
