### ISSUE TITLE
Implement an API 

### ISSUE THREAD

**Issue by ojongerius** [freeCodeCamp/freeCodeCamp#16889]
I'd like to programmatically interact with FCC, and noticed openapi was, but is not longer support. 

Looks like there is a desire to have an API that is open, but not maybe no OpenAPI -the REST standard.

I'd be happy to implement either or both. Let's flesh it out in this issue.

Deprecated project: https://github.com/freeCodeCamp/open-api
Related board: https://github.com/freeCodeCamp/freeCodeCamp/projects/5

/cc @raisedadead

**Comment by raisedadead** [comment]
Yes, we are going to do it as per the OpenAPI Standard Spec, it will be separate project of itself running in conjunction with the platform.

**Comment by ojongerius** [comment]
Where was the decision made to chose REST instead of GraphQL? If choosing REST, OpenAPI is the right choice. But as this is a green fields project, why not chose a technology that requires less maintenance?

**Comment by ojongerius** [comment]
We've met, and since then I've gotten write access to https://github.com/freeCodeCamp/open-api. I'm going to close this issue and continue working on this in the issues in that project.
