### ISSUE TITLE
usage of children() jquery method labelled as wrong

### ISSUE THREAD

**Issue by kalunlee136** [FreeCodeCamp/freecodecamp#1688]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The second check point is labelled correct when children() is not used in the code and labelled incorrect when children() is used. 

I used the following code:

 $('#right-well').children().css('color','green');
 
  });

**Comment by BerkeleyTrue** [comment]
This is being tracking in #1713
