### ISSUE TITLE
Differences Between the var and let Keywords lesson has unnecessary note

### ISSUE THREAD

**Issue by yoizfefisch** [freeCodeCamp/freeCodeCamp#16893]
#### Challenge Name

[ES6: Explore Differences Between the var and let Keywords](https://beta.freecodecamp.org/en/challenges/es6/explore-differences-between-the-var-and-let-keywords)

#### Issue Description

At the bottom of the lesson there is a note:
> Remember that since let prevents variables from being overridden, you will need to remove one of the declarations entirely.

But in the code, none of the variables are decalred more than once.

**Comment by raisedadead** [comment]
I think the note is redundant here. This can be removed. 

Here are our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md)and you can reach us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for help.

**Comment by raisedadead** [comment]
First time contributors, you can simply use the search at the top of this page to look for the string in the note to identify the file that needs changing.

**Comment by muratdogan17** [comment]
I'm working on it 👍
