### ISSUE TITLE
Job Board functionality

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#1689]
- [x] Remove according
- [x] picture should 100/100
- [x] add highlight (yellow)
- [x] Jobs should also have own url
- [x] Add signup form
- [x] Paypal integration
- [x] Clicking on job in list view takes you to show job view
- [x] Make list page plain list (company title date)
- [x] redirect on preview if no job preview is found
- [x] redirect if no job is found or job isFilled/!isPaid/!isApproved
- [x] clear LS on submit
- [x] test memory management
- [x] front/full cert requirement on form
- [x] remote ok flag
- [x] different PayPal forms with normal/highlight
- [x] How do campers apply to position box
- [x] Copy for flag buttons
- [x] Copy on completed
- [x] remove phone number
- [x] Find links in how to apply text
- [x] Change default image to fcc-camper
- [x] Make url not require protocol
- [x] fix font

**Comment by kennethmath** [comment]
Man I don't even know how I ended up here luckless what to do with them but what I do know is everyone been saying whoever did this to my phone was smart real smart but now reading yalls comments they r dumb cause it sounds like they stole them and changed um up some how crazy and thank all of yall and sorry for the troublekennethmathenyxyz@gmail.com
