### ISSUE TITLE
Unable to reset forgotten password

### ISSUE THREAD

**Issue by MrAJGurney** [freeCodeCamp/freeCodeCamp#16892]
#### Issue Description

I seem to be unable to reset my password.

1. I go to https://www.freecodecamp.org/signin and select "Sign in with Email"
2. I am taken to https://www.freecodecamp.org/email-signin
3. I select "Forgot your password?"
4. I am, taken to https://www.freecodecamp.org/forgot
5. I enter my email address, and select "Reset Password"
6. A popup appears saying "An e-mail has been sent to [email address] with further instructions."
7. I recieve an email with a link, and select the link. It is  https://www.freecodecamp.org/reset-password?access_token=Bhlah87328bBHBklgh87Bg7lvcg7ibals77G (I have replaced the access_token with some random letters/numbers)
8. I enter a password into the "New Password" and "Confirm Password" areas.
9. I select "Change Password"
10. I get take to https://www.freecodecamp.org/map and see a popup with "Oops! Something went wrong. Please try again later"

I've repeated these steps half a dozen times in an attempt to reset my password. I can log in/out thanks to my browser remembering my old password - I've tried resetting on a machine that doesn't have the credentials saved - but I'm not sure what I'm doing wrong.

In case it was something being saved my the browser I tried repeating the steps in incognito mode - manually copy/pasting the link sent to my email - but it still comes up with the same error message.

#### Browser Information

* Browser Name, Version: Google Chrome 64.0.3282.186
* Operating System: Microsoft Windows 10 - 64-Bit
* Mobile, Desktop, or Tablet: Desktop

**Comment by raisedadead** [comment]
@QuincyLarson @BerkeleyTrue I cannot reproduce this locally.
@MrAJGurney Can you shoot us an email team@freecodecamp.org.

We will try and get this resolved for you.

**Comment by Andrew-Gurney** [comment]
I've sent an email to team@freecodecamp.org with the title **Unable to reset forgotten password**.

**Comment by nilbenis** [comment]
Having the same issue.
Any advise?
Thanks a lot

**Comment by QuincyLarson** [comment]
@nilbenis send me an email at team@freecodecamp.org

**Comment by nilbenis** [comment]
@QuincyLarson I replied github notification email "[freeCodeCamp/freeCodeCamp] Unable to reset forgotten password (#16892)".

**Comment by raisedadead** [comment]
@nilbenis you would need to  a send fresh email to this email: team@freecodecamp.org., if you havent already

**Comment by nilbenis** [comment]
@raisedadead just did. Thanks!

**Comment by nilbenis** [comment]
Just to let you know, I got access again to my account.
I am not sure, but I think the whole "Unable to reset forgotten password" problem has been caused because my previous session was still active on another computer. The same computer I was able to get access again.

**Comment by QuincyLarson** [comment]
@nilbenis Ah - you may be on to something there! Glad you have access again.

@raisedadead Can you think of any reason why having an active session on another computer would prevent being able to reset one's password?
