### ISSUE TITLE
SASS Challenges not working

### ISSUE THREAD

**Issue by elbui3** [freeCodeCamp/freeCodeCamp#16894]
#### Challenge Name
Sass: Use @each to Map Over Items in a List

#### Issue Description
The challenge always fails on the point 2-3-4, despite the code seems to be correct, the preview works fine and inspecting the html show me the three styles (blue-bg, black-bg, red-bg) properly expanded

#### Browser Information
* Browser Name, Version: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36.
* Operating System: Microsoft Windows 7 Enterprise SP1
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
```
<style type='text/sass'>
  
  @each $color in blue, black, red {
    .#{$color}-bg {background-color: $color;}
  }

  div {
    height: 200px;
    width: 200px;
  }
</style>

<div class="blue-bg"></div>
<div class="black-bg"></div>
<div class="red-bg"></div>
```

#### Screenshot
![image](https://user-images.githubusercontent.com/20560957/37390394-3348ee08-2768-11e8-82d1-78dc4cb938d8.png)

**Comment by hibaAkroush** [comment]
checkout this issue #16896
