### ISSUE TITLE
Sass Challenge:Use @each to Map Over Items in a List

### ISSUE THREAD

**Issue by GilTorch** [freeCodeCamp/freeCodeCamp#16896]
#### Challenge Name
Use @each to Map Over Items in a List

https://beta.freecodecamp.org/en/challenges/sass/use-each-to-map-over-items-in-a-list
#### Issue Description

My code clearly works and provide the right result in the preview section but for some reason I don't
understand I don't pass the challenge.
#### Browser Information

* Browser Name, Version:  Chrome 64.0.3282.186
* Operating System: Windows 7
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
<style type='text/sass'>
@each $color in blue, black, red {
  .#{$color}-bg {background-color: $color}
}

  div {
    height: 200px;
    width: 200px;
  }
</style>

<div class="blue-bg"></div>
<div class="black-bg"></div>
<div class="red-bg"></div>
```
#### Screenshot

![screenshot-2](https://user-images.githubusercontent.com/12599950/37401860-e1dc1c46-275f-11e8-9571-1d7b4dab62ad.png)

**Comment by sjames1958gm** [comment]
Looking in the source it appears the test is missing the `.` required for class selectors
See below the assert is using `blue-bg` and should be `.blue-bg`
        "assert($('blue-bg').css('background-color') == 'rgb(0, 0, 255)', 'message: Your <code>.blue-bg</code> class should have a <code>background-color</code> of blue.');",

**Comment by elbui3** [comment]
Do you know if anybody is going to fix this issue?

**Comment by huyenltnguyen** [comment]
@sjames1958gm Nice catch there! Are you interested in fixing the tests?
Here is the [Contributing Guide](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md) that you should refer to, and the [Contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) if you need help.
