### ISSUE TITLE
Challenges on beta requiring a semi colon

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/freeCodeCamp#16897]
I've noticed on the beta that the interface shows an error if your code does not have a semi colon. In most cases you don't need to include a semi colon, why is the editor being strict about semi colons when unless you have an edge case or badly formatted code you won't need it?

**Comment by DawoodMorris** [comment]
I've noticed on the beta that the interface shows an error if your code does not have a semi colon. In most cases you don't need to include a semi colon, why is the editor being strict about semi colons when unless you have an edge case or badly formatted code you won't need it?

**Comment by nsuchy** [comment]
@mstellaluna The second response looks like it accidentally forwarded the same message. This should probably be edited out, at least the unsubscribe link as that should remain private to protect the user.

**Comment by raisedadead** [comment]
Hi @nsuchy we debated about this in https://github.com/freeCodeCamp/freeCodeCamp/issues/16509 and came to a consensus that this is intended.

**Comment by nsuchy** [comment]
@raisedadead While I think this could lead to bad habits I respect the teams' decision :)
