### ISSUE TITLE
Beta: Waypoint: Use Bracket Notation to Find the Last Character in a String - cant' progress

### ISSUE THREAD

**Issue by richyvk** [FreeCodeCamp/FreeCodeCamp#1690]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-last-character-in-a-string

I can't get to the next waypoint after completing this, get a 404.

![screen shot 2015-08-10 at 11 31 04 am](https://cloud.githubusercontent.com/assets/4687812/9158050/83443778-3f53-11e5-99a7-5f2f618200b7.png)

**Comment by benschenker** [comment]
Closing as stale
