### ISSUE TITLE
[BETA] Code from URI is not loaded

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/freeCodeCamp#16904]
#### Issue Description
When a URI has solution code in it, the browser shows the toast that the code from the URI has been loaded, but code is not loaded and the default code remains.

As an example you can try this URI:

http://beta.freecodecamp.com/en/challenges/javascript-algorithms-and-data-structures-projects/palindrome-checker?solution=function%20palindrome(str)%20%7B%0A%20%20str%20%3D%20str.toLowerCase().replace(%2F%5B%5CW_%5D%2Fg%2C%20%27%27)%3B%0A%20%20for(var%20i%20%3D%200%2C%20len%20%3D%20str.length%20-%201%3B%20i%20%3C%20len%2F2%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if(str%5Bi%5D%20!%3D%3D%20str%5Blen-i%5D)%20%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20true%3B%0A%7D

The expected behavior for the above URI is to load the following code in the editor pane:

```
function palindrome(str) {
  str = str.toLowerCase().replace(/[\W_]/g, '');
  for(var i = 0, len = str.length - 1; i < len/2; i++) {
    if(str[i] !== str[len-i]) {
      return false;
    }
  }
  return true;
}
```
Instead, it leaves the default code there.

The problem seems to be in the `legacyToFile` function. 

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/routes/Challenges/redux/code-storage-epic.js#L57

When I locally change `if (isPoly(files))` to `if (isPoly(files[key]))` it fixes the problem and I get the expected behavior.

I could go ahead with a PR for this, but `legacyToFile` is used in two other places. I have not been able to recreate the conditions to reach those lines of code, so I'm hesitant to propose a fix that has not been fully tested.

#### Screenshot
![image](https://user-images.githubusercontent.com/148813/37531112-fb3f1204-2919-11e8-9e1e-5399cae561c4.png)

**Comment by tchaffee** [comment]
Please note that this issue is blocking my progress on #16565.

**Comment by QuincyLarson** [comment]
@BerkeleyTrue Could you take a look at this issue?

**Comment by BerkeleyTrue** [comment]
We removed code-uri in beta with the intention of storing user code in a redis backend and pulling it down using id's. This was to be introduced after release.

**Comment by tchaffee** [comment]
> We removed code-uri in beta

Just from looking at the code, the logic is still there for code-uri. It's broken, but the code is there.

> storing user code in a redis backend and pulling it down using id's

I'm not sure how this is related to user code. Code in a URI should always be initially coming from somewhere else? Or am I missing something?

Are there links out there that folks could click on with code in the URI? If there are no links then I think the easiest thing to do at the moment is to remove the logic around code URIs. 

If there are already links out there with code in the URI, then it would make sense to fix this logic. 

Sorry if I'm beating a dead horse, but my fix for code in the URI works. I'm just concerned about the other cases (not related to code in the URI) in which `legacyToFile` is used.

The other cases are:

Possibly for when the seed code is found? 

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/routes/Challenges/redux/code-storage-epic.js#L121

When a previous solution is found?

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/routes/Challenges/redux/code-storage-epic.js#L140

Something else to do with a previous solution:

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/routes/Challenges/redux/code-storage-epic.js#L161

But I can't seem to hit those lines no matter what I try. So I'm just not sure what use case that code is for, and I have no way to test it to make sure I'm not breaking that function for the other places it is used.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.

**Comment by manzilo** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (123/100 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-04.elitehosts.com ([72.9.130.158]:40902)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1fPUSQ-0000qw-5u
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:58:10 -0400
Received: from out-9.smtp.github.com ([192.30.254.192])
	by mailin-04.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <noreply@github.com>)
	id 1fPURQ-0006TK-Dh
	for manzil@funtasticlabs.com; Sun, 03 Jun 2018 10:57:08 -0400
Date: Sun, 03 Jun 2018 07:57:05 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1528037826;
	bh=xrsEFtkVsUi6qWJBFVQY5KoOUG5pfnk2kXxDdneSZm4=;
	h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=fYTTF3nH3f+erJ870+D/svuzg/Rb3MY6uzl8w1keIhWXDKhSsoUJ5OpB5BAARx8Zn
	 MuMC3jNhsuZ1SXCjKCmcNE2sEOO0rp4P6Z5cq//j8e4x9XAtjcs6uLqafu6Wfkxau7
	 JXJVVS7flsqR+F8FtbCz0IiubkYt/e36yaasQRqU=
