### ISSUE TITLE
Unused and confusing variable in challenge's code: Declare a Read-Only Variable with the const Keyword

### ISSUE THREAD

**Issue by yoizfefisch** [freeCodeCamp/freeCodeCamp#16900]
#### Challenge Name

[ES6: Declare a Read-Only Variable with the const Keyword](https://beta.freecodecamp.org/en/challenges/es6/declare-a-readonly-variable-with-the-const-keyword)

#### Issue Description

Based on the code, it seems that the intended result would be a message that adds the string " is cool!" to the parameter string. However, to achieve that, we need to change `console.log(str);` to `console.log(sentence);`. Otherwise, there is no use for the constant `sentence` in this code and thus creates confusion.
In #16584 this line was changed from `console.log(str2);` .

It should also test for "freeCodeCamp is cool!" to confirm that the user updated this line to all-caps as well.

Additionally, information in [the next challenge](https://beta.freecodecamp.org/en/challenges/es6/mutate-an-array-declared-with-const) may be important for campers to understand this one because at first it seems odd to declare `sentence` as a constant and then mutating it with changes in the `str` variable.

**Comment by ahmadabdolsaheb** [comment]
@yoizfefisch thanks for reporting this bug. 
@raisedadead I think the <code>console.log(str);</code> in the challengeSeed should be changed to <code>console.log(sentence);</code>, also we need a test that checks if the capitalized version of <code>sentence</code> is used in the <code>console.log()</code>

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb We just launched our new curriculum and learning platform. Now is a good time to start making improvements like this. I think our console.log functionality isn't quite yet working, but aside from that would you be interested in helping make this fix?

**Comment by ahmadabdolsaheb** [comment]
@QuincyLarson will get it done first thing tomorrow.

**Comment by ahmadabdolsaheb** [comment]
if anyone would like to tackle this issue the following info might come handy.
There are three changes that need to take place.
1. here is the location of the first line https://github.com/freeCodeCamp/freeCodeCamp/blob/6d7092928e852755fa0d4d9489b3c8748b466a94/seed/challenges/02-javascript-algorithms-and-data-structures/es6.json#L164

    it should change to  "    console.log(sentence);",

2. here is the location for the tests
https://github.com/freeCodeCamp/freeCodeCamp/blob/6d7092928e852755fa0d4d9489b3c8748b466a94/seed/challenges/02-javascript-algorithms-and-data-structures/es6.json#L134

    the following test should be added to the rest of the tests
```       
       {
          "text": "<code>console.log</code> should be adjusted to print the variable <code> SENTENCE </code>.",
          "testString": "getUserInput => assert(getUserInput('index').match(/console.log\(\s*?SENTENCE\s*?\)\s*?;/g), '<code>console.log</code> should be adjusted to print the variable <code> SENTENCE </code>.');"
        }
```
3. finally, the challenge description should give a let the users know about changing the sentence in console.log accordingly

happy conding

**Comment by prateek3255** [comment]
Is this issue still open for first timers?
