### ISSUE TITLE
Beta: Add horizontal scroll bars to some panels?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#16903]
**I propose to add horizontal scroll bars to the map and editor panels, removing the wrapping of text to new lines**
<hr>

![screenshot from 2018-03-15 18-47-23](https://user-images.githubusercontent.com/20648924/37496621-9815715c-2881-11e8-8db4-58f51e981a01.png)
<br>
In the editor section above, that group of HTML is difficult to read -- removing the text wrap would make it easier for that section and a lot of other sections -- It might also make it harder to read in other cases(like maybe for a real long paragraph). So perhaps it's something to discuss. But I think it would be better overall if they didn't wrap, and it has annoyed me on more than one occasion.
<hr>

![screenshot from 2018-03-15 17-50-28](https://user-images.githubusercontent.com/20648924/37496925-54e680ea-2883-11e8-9f97-74bd9b924291.png)
<br>
In the above picture, the `Nest an Anchor Element within a Picture` challenge is displayed. And it's located 4th from the bottom of the map/screen. When I click the next challenge the whole map jumps because two of the panels disappear and the challenge titles in the map have space to no longer wrap to new lines. Below is that next challenge (I didn't scroll anywhere), the `Nest an Anchor Element` challenge jumped up to 9th from the bottom and I get lost on where I am and where I just clicked.
<br>
![screenshot from 2018-03-15 17-51-05](https://user-images.githubusercontent.com/20648924/37496924-5414fc00-2883-11e8-84d2-2b6d093a2049.png)
<br>
<hr>
These may seem minor, but I think it would make for a better experience. 
<br>
I have a small 13" screen - with a bigger screen this wouldn't be much of a problem - But I can't be the only one with a small screen.

**Comment by raisedadead** [comment]
This layout is planned to be changed in future, we are noting the requirement and thank you for the feedback.

**Comment by moT01** [comment]
no longer an issue with the new layout
