### ISSUE TITLE
Twitch.tv API workaround broken

### ISSUE THREAD

**Issue by scwilbanks** [freeCodeCamp/freeCodeCamp#16911]
#### Challenge Name

Use the Twitchtv JSON API

#### Issue Description

Any new API calls to https://wind-bow.gomix.me/twitch-api/ with channels, streams, or users are met with error message: "This project has received too many requests, please try again later."

#### Browser Information

Using Chrome v.65 on Mac OS X 10.13.3

**Comment by chetat** [comment]
@scwilbanks Try https://wind-bow.glitch.me/twitch-api/
.I think it's the updated link.
I am stuck in the same challenge but have a different issue.

**Comment by scwilbanks** [comment]
@chetat Oh, I see. So the link on the page just needs to be updated. Thanks!

**Comment by chetat** [comment]
Yes. You are  Welcome.

**Comment by raisedadead** [comment]
Hi thanks, for reporting, this is resolved but the patch has not been released to the main website yet. Please bear with us while that happens.
