### ISSUE TITLE
Use organisational projects boards

### ISSUE THREAD

**Issue by ojongerius** [freeCodeCamp/freeCodeCamp#16918]
Hi there,

@raisedadead and I will be working on the freeCodeCamp API. The code will be located in a separate repository, at the moment https://github.com/freeCodeCamp/open-api . The current project boards have been created on a repository instead of organisational level. As freeCodeCamp moves away from the current monolithic architecture it will be more common to have projects that span multiple repositories.

I propose that we move, migrate or reproduce https://github.com/freeCodeCamp/freeCodeCamp/projects/5 from github.com/freeCodeCamp/freeCodeCam (tied to the  freeCodeCamp *repository*) to the github.com/freeCodeCamp *organisation*.

See Github doco at https://help.github.com/articles/about-project-boards:
> Organization-wide project boards can contain issues and pull requests from any repository that belongs to an organization.

**Comment by ojongerius** [comment]
Not sure, but one issue *could* be that people, like me, that have write access to one repository but are not a member of the FCC GH org would not be able to use the board.

**Comment by raisedadead** [comment]
Hi, we have considered this previously. But the only reason we have it this way is because of the discoverability.

The main repo is the one which gets most traffic. Hence we have chosen to use its project boards for this. Since GitHub lets us link issues from anywhere. I think this is a better way.

I understand this is not conventional. But its the least confusing.

**Comment by raisedadead** [comment]
I guess, we could add documention to reflect this.

**Comment by QuincyLarson** [comment]
@raisedadead @ojongerius I created an organization-level board here: https://github.com/orgs/freeCodeCamp/projects/1

I can see @raisedadead's point about discoverability. I can also see @ojongerius's point about many of these projects transcending individual repos.

While freeCodeCamp/freeCodeCamp is definitely the most prominent repo on the freeCodeCamp.org, that may gradually change. We have a lot of exciting projects coming up, including this open API project. So I would consider myself on the "organization-level projects" side of the fence.

**Comment by ojongerius** [comment]
Thanks @QuincyLarson . Just tried to access that board and am a little bummed to find out that project boards on an organisational level are only visible to org members. I'd say that is a Github bug. I've shot them a message to see it there is an issue I can link to.

I imagine we want to keep boards visible to the public, right?

**Comment by ojongerius** [comment]
GH reply:

>  Hi Otto,Thanks for contacting GitHub Support! We're always working to improve GitHub and we consider every suggestion we receive.While this isn't currently possible, I'm pleased to let you know that this is something we are considering for the future.I've just add your +1 to our internal feature list but I can't make any promises around when this might be implemented.Thanks again, and do let us know if you have any other suggestions or concerns!Best regards,Tiara GitHub Support

**Comment by QuincyLarson** [comment]
@ojongerius OK - great! Thanks for discovering this limitation. 

I propose we continue to use the old board in the meantime until they've lifted this limitation. I'm going to close this issue and the board I created.
