### ISSUE TITLE
Broken Links in - Make a Person Challenge

### ISSUE THREAD

**Issue by dardandemiri** [freeCodeCamp/freeCodeCamp#16919]
#### freeCodeCamp Algorithm Challenge Guide: Make a Person
https://forum.freecodecamp.org/t/freecodecamp-algorithm-challenge-guide-make-a-person/16020

#### Issue Description

The Relevant Links are placeholder hyperlinks with no href
 - How to build objects
 - Construct objects with functions
 - Declare objects as variables

#### Screenshot

![image](https://user-images.githubusercontent.com/6118247/37629647-4183b1c0-2be0-11e8-9c34-310421777bc8.png)
![image](https://user-images.githubusercontent.com/6118247/37629676-6b6ea54e-2be0-11e8-898e-b0d3c99759e2.png)

**Comment by dardandemiri** [comment]
If the links are supposed to be searched in google then why adding them as a link instead of normal text?

**Comment by joker314** [comment]
Here is the markdown which generated the unordered list.

```markdown
- [How to build objects](Challenge-Build-JavaScript-Objects)
- [Construct objects with functions](Challenge-Construct-JavaScript-Objects-With-Functions)
- [Declare objects as variables](Challenge-Declare-JavaScript-Objects-As-Variables)
```

These are clearly intended to link to particular challenges, but the markdown parser doesn't understand what to do with then (they don't have a schema, etc.), so no `href` attribute is provided.

This is either an issue with the markdown parser which is supposed to have a custom feature but doesn't; or, the links have been incorrectly entered.

**Comment by akkatracker** [comment]
The link closures - under relevant links at the top of the post is also 'broken'

**Comment by raisedadead** [comment]
Hi, we are in the process of deprecating/removing these articles in favor of https://guide.freecodecamp.org 

I am tagging along @IsaacAbrahamson and @ArielLeslie if they can link to any relevant discussions on the forum?
@QuincyLarson can you fill in if I have this correct?

Closing, as not related to code base, but still open to discussion for the resolution.

**Comment by ArielLeslie** [comment]
I'm guessing that this is something that happened because the Guide topics were copied from the Wiki? I think that those used to be internal links to other pages. For now, I will update the links to go to the relevant challenge on FCC.

**Comment by raisedadead** [comment]
@ArielLeslie awesome! thanks a lot for working on these.
