### ISSUE TITLE
Beta: Waypoint: Perform Arithmetic Operations on Decimals with JavaScript

### ISSUE THREAD

**Issue by richyvk** [FreeCodeCamp/FreeCodeCamp#1691]
Challenge http://beta.freecodecamp.com/challenges/waypoint-perform-arithmetic-operations-on-decimals-with-javascript

No instructions on this waypoint. Maybe that's intentional??

**Comment by europaradise** [comment]
![product 5](https://cloud.githubusercontent.com/assets/13596294/9483688/e4e8c498-4b70-11e5-8734-9da87794d5c0.PNG)
