### ISSUE TITLE
FCC Advanced Node and Express not working?

### ISSUE THREAD

**Issue by clickingmouse** [freeCodeCamp/freeCodeCamp#16915]
not passing the tests when i am fairly sure my code should work

#### Challenge Name

https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/set-up-a-template-engine
https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/use-a-template-engines-powers
https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/set-up-passport

#### Issue Description

just can't pass them, I am almost certain my code is okay

#### Browser Information

iMac, chrome 
* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
https://glitch.com/edit/#!/tan-bow?path=server.js:41:2


```

**Comment by raisedadead** [comment]
Hi @Em-Ant just tagging you alone for an analysis?

**Comment by Em-Ant** [comment]
@raisedadead I'll have a look in the next days, but I don't know the advanced-express section well. It was made by another contributor.

**Comment by clickingmouse** [comment]
Cool, it seems to solve it for for the first challenge
