### ISSUE TITLE
[Beta] Typo in Redux: Dispatch an Action Event

### ISSUE THREAD

**Issue by helplah** [freeCodeCamp/freeCodeCamp#16920]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/redux/dispatch-an-action-event

#### Issue Description

Redux: Dispatch an Action Event

The first sentence reads, "od is what you use to dispatch actions to the Redux store." That makes no sense and is probably a typo.

#### Browser Information

* Browser Name, Version: Firefox Quantum 59.0.1 (64-bit)
* Operating System: Windows 7 x64
* Mobile, Desktop, or Tablet: NIL

#### Screenshot

![image](https://user-images.githubusercontent.com/30688276/37639438-5a7365ba-2c4c-11e8-97bc-cd20f05b3edd.png)

**Comment by raisedadead** [comment]
This should read:

> `dispatch` method is what you ...

**Comment by jpdail01** [comment]
I'd like to take this

**Comment by durgeshra** [comment]
Hi! I have sent a PR with the changes as mentioned. Please look into it
