### ISSUE TITLE
audio files from simon game challenge not playing properly in chrome

### ISSUE THREAD

**Issue by catshark** [freeCodeCamp/freeCodeCamp#16927]
#### Challenge Name
https://www.freecodecamp.org/challenges/build-a-simon-game

#### Issue Description
in the project description for the simon game, navigate to one of the sample audio file's respective web link and click play. Observe that the sound is only partially played in Chrome.

Additional information: problem doesn't arise when reproducing in Firefox or IE

#### Browser Information

* Browser Name, Version: Chrome 65
* Operating System: OSX and windows 10
* Mobile, Desktop, or Tablet: Desktop

**Comment by mstellaluna** [comment]
Confirmed. I am also experiencing this issue when accessing the sound files from the S3 URL in chrome but the issue does not occur in either Edge or FF.

**Comment by jaimex8** [comment]
Possible bug in chrome 45 and up
https://stackoverflow.com/questions/32396054/certain-mp3-files-not-playing-in-chrome

Current audio file bitrate is below 128Kbps, recommend updating to 160Kbps

**Comment by doubleUTF** [comment]
+1. I finished my game at the end of 2017 and tested the sounds with Chrome; it was fine then so definitely not all of Chrome 45+. Can confirm that Chrome 65 will cut the audio off short and stop playing future instances. Other browsers work fine.

**Comment by NJM8** [comment]
I wanted to add to this as I was having trouble as well with Chrome. It would seem a lot of users are having trouble. I came across this forum post: https://forum.freecodecamp.org/t/the-provided-build-a-simon-game-mp3s-cause-problems-with-chrome-64/171473.  

I modified the files with twistedwave.com and trimmed 100 ms from the front and added 100ms or so to the back of each file. Upon using the new files there were no issues in Chrome, Firefox, or Safari. I checked the file with chrome://media-internals and did not see any errors present. 

I would suggest replacing the current sounds provided with these modified ones. They are available here: https://github.com/NJM8/sounds.

**Comment by doubleUTF** [comment]
@NJM8 Thank you, your workaround does indeed work. Just have to set the sound element's currentTime property to 0 on every playback or else there will be no new sound until the previous playback is completely over.

**Comment by doubleUTF** [comment]
Yes I used your modified sounds. The crackles are present only if spammed repeatedly, which is not a huge issue.

**Comment by NJM8** [comment]
Well I was hoping I got rid of the crackles, probably someone who knows more than I do about sounds can just make some new ones.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
