### ISSUE TITLE
[Beta] Unable to claim some certificates

### ISSUE THREAD

**Issue by leonfeng** [freeCodeCamp/freeCodeCamp#16923]
#### Issue Description

Assuming it is still the case that only the projects are required to claim a certificate, then something is preventing me from claiming the _Applied Responsive Web Design_, _JavaScript Algorithms and Data Structures_, and _API and Microservice_ certificates.

As you can see from the screenshots, I have completed all 5 projects under _Applied Responsive Web Design_:
![screen shot 2018-03-20 at 18 42 10](https://user-images.githubusercontent.com/241553/37703760-28a759f0-2d10-11e8-82ac-29802d7ccf8f.png)

But when I claim the certificate, I get this error message:
![screen shot 2018-03-20 at 18 43 31](https://user-images.githubusercontent.com/241553/37703761-28de89b6-2d10-11e8-8ef2-79226b6443e5.png)

The same thing happens with _API and Microservice_.

Finally, I can claim the _JavaScript Algorithms and Data Structures_ certificate by completing its challenge:
![screen shot 2018-03-21 at 00 45 34](https://user-images.githubusercontent.com/241553/37704130-73d59710-2d11-11e8-9893-f81190aa3f1a.png)

But it's not listed on my public profile:
![screen shot 2018-03-21 at 13 18 45](https://user-images.githubusercontent.com/241553/37704131-73fa4434-2d11-11e8-8b6a-ff15c7f013f3.png)

Neither is there a `Show/Claim Certificate` button:
![screen shot 2018-03-21 at 13 19 06](https://user-images.githubusercontent.com/241553/37704132-741b3a86-2d11-11e8-83c5-55fbc87ccb36.png)

I am aware this has been reported and resolved before (#16661 ), but maybe the problem has resurfaced.

Reproducible on beta.freecodecamp.org and my local copy.

**Comment by bryan0767** [comment]
Also having trouble claiming Algorithms and Data Structures certificate


![screen shot 2018-05-12 at 7 05 38 pm](https://user-images.githubusercontent.com/33098684/39962571-e78c4cb0-5617-11e8-952d-dcae15d70426.png)


Despite completing all required projects 


![2](https://user-images.githubusercontent.com/33098684/39962569-d78a5f64-5617-11e8-96cb-f5ec4f6935d5.png)

Any help is appreciated!

**Comment by JMagers** [comment]
These issues have been addressed in the following PRs:
* #17102
* #17104
* #17105

I think this issue can be closed now.
