### ISSUE TITLE
Instructions discrepancy

### ISSUE THREAD

**Issue by garysmeade** [FreeCodeCamp/freecodecamp#1693]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In this waypoint, the initial instructions request the user to modify the children of #right-well with the color of green.  I correctly entered the code: $('#right-well').children().css('color', 'green'); which changes the text of the children elements of #right-well.  

The advice window states: 
Your "target6" element should have green text.

And as shown in the screenshot, #target6 does have green text.
![image](https://cloud.githubusercontent.com/assets/13364192/9159591/d8333b10-3f6e-11e5-8d0b-e5c4e11ae74c.png)

**Comment by kurzninja** [comment]
The test for colors was incorrect. I have fixed it in https://github.com/FreeCodeCamp/freecodecamp/pull/1706
