### ISSUE TITLE
Typo in the challange "Change Text Inside an Element using jQuery"

### ISSUE THREAD

**Issue by aseralis** [freeCodeCamp/freeCodeCamp#16934]
please delete

**Comment by alexch** [comment]
I don't think this is a valid bug report.  `$("h3").html("<em>jQuery Playground</em>");` looks correct to me. The JS string `"<em>jQuery Playground</em>"` contains HTML that opens and closes an `em` element.

**Comment by aseralis** [comment]
You are completly right, I don't know what I thought when I opened this!

**Comment by alexch** [comment]
No worries! :-)
