### ISSUE TITLE
[Beta] Pane lesson not found Error

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16947]
### Issue Description
@Bouncey, @raisedadead On visiting a challenge which I have not visited earlier shows me `pane lesson, pane editor not found` error.

To reproduce, try visiting challenges which you've not visited earlier, I'm 100% sure you'll encounter this error after few attempts. 

![pane lesson not found](https://user-images.githubusercontent.com/26724128/37862344-5d951982-2f71-11e8-936e-bdef23827c3f.PNG)

### Browser Information
* Browser Name, Version: Chrome(65.0.3325.181) and Firefox(59.0.1).
* Operating System: Windows 10 Pro 32 Bit.
* Mobile, Desktop, or Tablet: Desktop.

**Comment by ahmadabdolsaheb** [comment]
I could not reproduce this from the following browser and system :(:
Chrome Version 65.0.3325.181 (Official Build) (64-bit)
MacOS High Sierra

**Comment by vkWeb** [comment]
@ahmadabdolsaheb I faced this many times. I think you should try visiting challenges in incognito mode and keep on changing challenges quickly, more likely you'll observe this in the back-end(APIs, Node, etc) section.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
