### ISSUE TITLE
Challenege: Create a Set of Radio Buttons

### ISSUE THREAD

**Issue by MANTENN** [freeCodeCamp/freeCodeCamp#16944]
#### Create a Set of Radio Buttons
https://www.freecodecamp.org/challenges/create-a-set-of-radio-buttons

#### Issue Description
The attribute value for the input element is missing in the challenge, so its a bit misleading.

**Comment by hamzaerbay** [comment]
@MANTENN could you explain more which input is missing attribute value?

**Comment by raisedadead** [comment]
Hi @MANTENN Can you please fill all the details as per this template which was presented to you while opening this issue:

https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/staging/.github/ISSUE_TEMPLATE.md

**Comment by raisedadead** [comment]
Closing, please comment back if you need this re-opened.
