### ISSUE TITLE
[Beta] Required improvements in Panel control buttons and Navigation bar

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16946]
### Issue Description
**Issues with panel control buttons:**

- [ ] During night mode the buttons look like they are disabled.
![night mode 01](https://user-images.githubusercontent.com/26724128/37862265-0d61fd5a-2f70-11e8-8c80-0613a98f4285.PNG)

- [ ] On disabling more than one panel it is not reflected in button's UI i.e. all the disabled panel buttons should grey out but only one button is greyed out not the others. 
![2018-03-24 1](https://user-images.githubusercontent.com/26724128/37862047-c3f2431c-2f6c-11e8-940c-231b52c35c19.png)
- [ ] During loading on slow networks the buttons should not be clickable. 
- [ ] On enabling a panel it still looks like disabled until we click somewhere on the screen. (Related to #16942) 
- [ ] On hovering over the button, the background blends with the navigation bar, it should look a bit lighter than dark green. Setting rgba value to (0, 100, 0, 0.4) will fix it. 

**Issue with navigation bar:**
- [ ] There is a very large amount extra whitespace at the right end of the navigation bar.
![capture](https://user-images.githubusercontent.com/26724128/37862234-b4030498-2f6f-11e8-8117-47bcedf039ae.PNG)
- [ ] The search bar's width should be increased so that the placeholder text is properly visible. 
![search bar nav](https://user-images.githubusercontent.com/26724128/37862192-0e7e9ac8-2f6f-11e8-98b1-d1369ec3896c.PNG)

### Browser Information
* Browser Name, Version: Chrome(65.0.3325.181) and Firefox(59.0.1). 
* Operating System: Windows 10 Pro 32 Bit. 
* Mobile, Desktop, or Tablet: Desktop.

**Comment by vkWeb** [comment]
@raisedadead Thanks for the edit but I have already included that issue, checkpoint number 4. So I'm removing it.

**Comment by raisedadead** [comment]
We are blocking any enhancements until beta. PR's are welcome.

**Comment by vkWeb** [comment]
@raisedadead But why brother? If we are blocking any enhancements then why are we in beta right now?

**Comment by tchaffee** [comment]
Concerning the panel buttons (Map, Lesson, Editor, Preview) I have traced the current behavior to the ` client/less/lib/bootstrap/buttons.less` and `client/less/lib/bootstrap/mixins/buttons.less` files and the `:focus` pseudo-class. If someone can describe what the desired behavior is, I might be able to figure this out and submit a PR.

What I need is the expected appearance for all of these possible states. I think I understand the first two, which is the behavior as of today:

1. panel is enabled: white bg with dark green color (font)
1. panel is enabled + hover: reversed, dark green bg, white color 
1. panel is enabled + focus: ?
1. panel is enabled + focus + hover: ?
1 panel is disabled: ?
1. panel is disabled + focus: ?
1. panel is enabled + hover: ?
1. panel is disabled + focus + hover: ?

**Comment by tchaffee** [comment]
@QuincyLarson @raisedadead  Any feedback on my suggestions above for fixing the panel toggle buttons? Has someone already fixed this? Or if not, can I get the answers to my questions about desired behavior so I can move forward on this?

**Comment by raisedadead** [comment]
Hi @tchaffee this was fixed partly. But that said, we would need to revisit this once https://github.com/freeCodeCamp/learn is ready. 

We appreciate the feedback, but its worth waiting for now. We may have a different approach to multi-tab editor since we are replacing codemirror with monaco
