### ISSUE TITLE
[Beta] Tests are not shown on visiting challenges for the first time

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16948]
### Issue Description
@Bouncey Clear your browser cache and try visiting challenges randomly from all the sections, you'll see that in some challenges tests are not visible, this is very strange. I think we need to fix this before shipping. 

![test](https://user-images.githubusercontent.com/26724128/37862469-41cd1d7e-2f73-11e8-954e-77db4d4e7544.PNG)

### Browser Information
* Browser Name, Version: Chrome(65.0.3325.181) and Firefox(59.0.1).
* Operating System: Windows 10 Pro 32 Bit.
* Mobile, Desktop, or Tablet: Desktop.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
