### ISSUE TITLE
Login buttons not showing up in Chrome on Windows 10

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/freecodecamp#1694]
A camper just reported this.
https://mail.google.com/mail/u/0/?ui=2&ik=562565a4bb&view=fimg&th=14f14d19f9a06fb5&attid=0.1&disp=emb&realattid=ii_14f14cfae889b089&attbid=ANGjdJ88LkTHLbIEK5zbxsQXxx50dm_bQDnglJjT0VotD13HTyEVHECj7RDGzaf5fiq801WsR1QRbtO2bLK2BQzg10zQiEdyZ1TI-sOhatwfgpanEEFs2A0e_mVksMc&sz=w1100-h618&ats=1439163565611&rm=14f14d19f9a06fb5&zw&atsh=1

**Comment by BerkeleyTrue** [comment]
@QuincyLarson That image is 404'd
