### ISSUE TITLE
[BETA] New panel toggle buttons stay grayed out after unhiding panel

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/freeCodeCamp#16942]
#### Issue Description
The new buttons do not toggle back from gray when you unhide a panel.

#### Browser Information

* Browser Name, Version: Chromium 64.0.3282.167 and Firefox 59.0.1 (64-bit)
* Operating System: Ubuntu 16.04
* Mobile, Desktop, or Tablet: Desktop

#### Screenshot

![image](https://user-images.githubusercontent.com/148813/37836684-da729fbe-2e91-11e8-8173-66b8d9d7d683.png)

**Comment by Bouncey** [comment]
There is no logic affecting the colour of the button text. The button holds focus until you move it elsewhere.

**Comment by tchaffee** [comment]
I moved the mouse elsewhere and it still stays gray.

**Comment by raisedadead** [comment]
This issue was logged first, but https://github.com/freeCodeCamp/freeCodeCamp/issues/16946 seems to have more relevant details. 

I am copying over the OP details there.

Thanks.
