### ISSUE TITLE
Incorrect instructions for targeting specific child element

### ISSUE THREAD

**Issue by garysmeade** [FreeCodeCamp/freecodecamp#1695]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I'm feeling like a pest posting all these bug reports :)  The instructions state "Make the first child in each of your well elements bounce."  But the advice window advises to target the second elements...
![image](https://cloud.githubusercontent.com/assets/13364192/9160032/dcf9436c-3f76-11e5-9eff-e2b9b511a900.png)

**Comment by BerkeleyTrue** [comment]
This is being tracked in #1713 

Happy Coding!
