### ISSUE TITLE
[NON-ISSUE] BETA:Regex Match Single Characters not specified.

### ISSUE THREAD

**Issue by vipatron** [freeCodeCamp/freeCodeCamp#16953]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/regular-expressions/match-single-characters-not-specified

#### Issue Description
Running the tests doesn't pass all the test cases. The results say the expression (no alphanumerics) should match 9 items, but it really should match 3 in "3 blind mice.". [(This regex tester visualizes the issue)](https://regexr.com/3mqh4). 

#### Browser Information
* Browser Name, Version: Firefox 59.0.1
* Operating System: Win 8.1
* Mobile, Desktop, or Tablet: Desktop 

#### Your Code
```
let quoteSample = "3 blind mice.";
let myRegex = /[^a-z0-9]/gi; // Change this line
let result = quoteSample.match(myRegex); // Change this line
```
#### Screenshot
![image](https://user-images.githubusercontent.com/36994955/37869269-eebedf1a-2f8a-11e8-8002-21e05b01b2ae.png)

**Comment by bqnguyen94** [comment]
The instruction says: 

> Create a single regex that matches all characters that are **not a number or a vowel**. Remember to include the appropriate flags in the regex.

Your regex matches all that are not a letter or a number, which is not what is required.

**Comment by vipatron** [comment]
You are correct. No matter how many times I read it, my internal schema kept me seeing "number or letter." Thanks for pointing that out. I will close this thread out.

**Comment by neofito777** [comment]
Hey guys, it work for me when I use just to exclude the vowel ^aeiou
