### ISSUE TITLE
BETA: test output for challenges is incomplete when read with screen reader

### ISSUE THREAD

**Issue by zersiax** [freeCodeCamp/freeCodeCamp#16951]
#### Challenge Name

All challenges on beta.freecodecamp.com

#### Issue Description

The test output area of the lesson interface is currently not ideal for the following reasons:

  -  The results are printed to a similar javascript-powered control to the CodeMirror editor, making it impossible for screen reader users to efficiently read them. Since this content does not need to be edited, this is far less of an issue than the CodeMirror problem.
  - Test results are not complete; at times, a message printing what the test expects is printed and readable, but there's no diff, comparison or any way to figure out what your code returned and what was expected.
This means the tests are , in fact, useless; I have to work through the logic in my head and comb through the code for syntax errors, since I can't see my code's output and have to guess at why the tests aren't completing.
This is as you might say less than ideal. :-)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment]
I think we would have to replace the react-codemirror with react-codemirror2 for starters, which is being discussed in a separate thread.

We are extremely sorry for the inconvenience. And at the same time I am afraid this will be tough to get sorted soon.

Maybe with open-api we will be able to have a rather simpler, dedicated a11y first client application for users.

/cc @ojongerius @QuincyLarson

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
