### ISSUE TITLE
website doesn't scroll down

### ISSUE THREAD

**Issue by cherepaxa1207** [freeCodeCamp/freeCodeCamp#16964]
website doesn't scroll down 

#### Browser Information

* Browser Name, Version: Version 65.0.3325.162 (Official Build) (64-bit)
* Operating System: High Sierra 10.13.3
* Mobile, Desktop, or Tablet: desktop

#### Your Code

```js



```
#### Screenshot

![screen shot 2018-03-26 at 16 36 11](https://user-images.githubusercontent.com/37816230/37933197-7f799db8-3118-11e8-941f-639a58368c91.png)

**Comment by musiyenko** [comment]
Scroll on the left part, where the lesson part is.

**Comment by raisedadead** [comment]
Hi @cherepaxa1207,

Can you please reach out to the [Chat Rooms](https://forum.freecodecamp.com/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](http://forum.freecodecamp.com) for help.

I think this isn't a issue with the platform.

Happy coding.
