### ISSUE TITLE
Add instructions on how to create your first user 

### ISSUE THREAD

**Issue by ojongerius** [freeCodeCamp/freeCodeCamp#16966]
[CONTRIBUTING](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) currently describes how to set everything up, but leaves it up to the reader to understand that you will have to sign up locally, that the sign in link can be found in the console output or Mailhog and so forth.

It is not rocket science to figure it all out, but it would easier to get started if contributing documentation would show the whole flow.

Any takers?

**Comment by stevenandersonz** [comment]
I would like to help here, how I can start?

**Comment by ojongerius** [comment]
Start by setting up your local development environment. Once you've got freeCodeCamp running locally, you will be able to have a local user sign up.
If you keep track of the steps you have to take to get your first user up and running, and document that in CONTRIBUTING. Hint: to get the sign in link you'll have to visit your local mailhog instance to retrieve it.

Having some clarity of what steps you have to take would really help.
