### ISSUE TITLE
[BETA ES6 Path] Verification bypassed.

### ISSUE THREAD

**Issue by musiyenko** [freeCodeCamp/freeCodeCamp#16969]
#### ES6: Use Destructuring Assignment to Pass an Object as a Function's Parameters

https://beta.freecodecamp.org/en/challenges/es6/use-destructuring-assignment-to-pass-an-object-as-a-functions-parameters

#### Issue Description

Verification is not working correctly, because it doesn't ignore comments. Please, refer to the screenshot. 

#### Browser Information

* Browser Name, Version: Chrome (dev channel)
* Operating System: Linux
* Mobile, Desktop, or Tablet: 

#### Your Code

```js


const stats = {
  max: 56.78,
  standard_deviation: 4.34,
  median: 34.54,
  mode: 23.87,
  min: -0.75,
  average: 35.85
};
const half = (function() {
  "use strict"; // do not change this line

  // change code below this line
  
  
/* Marked as a correct solution
  const half = ({ min, max}) =>
   Marked as a correct solution*/
  
  
  return function half(stats) {
    // use function argument destructuring
    return (stats.max + stats.min) / 2.0;
  };
  // change code above this line

})();
console.log(stats); // should be object
console.log(half(stats)); // should be 28.015


```
#### Screenshot

![screenshot from 2018-03-27 14-19-16](https://user-images.githubusercontent.com/18217335/37966848-e9f331ca-31c9-11e8-8c28-2a6d6d883420.png)

**Comment by raisedadead** [comment]
Yup, this has been a known issue to us. A good way to be able to do so would be to strip off comments. Unfortunately we can't do that reliably.
