### ISSUE TITLE
List order is incorrect in "Build a Tribute Page" challenge

### ISSUE THREAD

**Issue by psychelzh** [freeCodeCamp/freeCodeCamp#16977]
#### Challenge Name

[Build a Tribute Page](https://www.freecodecamp.org/challenges/build-a-tribute-page)

#### Issue Description

The ordered list does not have correct order. The ordinals are all `1`'s.

#### Browser Information

* Browser Name, Version:  Microsoft Edge 41.16299.248.0
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: N/A

#### Screenshot

![image](https://user-images.githubusercontent.com/13306020/38063356-440e8b98-332b-11e8-9fff-fa90d38862c0.png)

**Comment by psychelzh** [comment]
And I have found that this issue does not occur in `Chrome` browser.

**Comment by augiemagic** [comment]
Looks like this is the case for all project pages in Edge.

![image](https://user-images.githubusercontent.com/9977874/38318391-d2a9b706-37f4-11e8-8e66-7aa054caeb2c.png)

![image](https://user-images.githubusercontent.com/9977874/38318406-dd7b93a2-37f4-11e8-9f6b-9b9828f2f048.png)

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
