### ISSUE TITLE
Incorrect data from FCC leaderboard API

### ISSUE THREAD

**Issue by SweetCodingInc** [freeCodeCamp/freeCodeCamp#16976]
#### Challenge Name

General

#### Issue Description

Incorrect data is being returned from the [camper leaderboard api](https://fcctop100.herokuapp.com/api/fccusers/top/recent?)

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js
// Example wrong data

{
	"username": "shanelockart",
	"img": "https://avatars1.githubusercontent.com/u/35314620?v=4",
	"alltime": 1,
	"recent": 19,
	"lastUpdate": "2018-03-19T19:23:02.585Z"
}

```

**Comment by raisedadead** [comment]
@Em-Ant just curious do we have an equivalent of this on glitch

**Comment by Em-Ant** [comment]
As far as I know We don't

**Comment by victorhmp** [comment]
Sorry, I couldn't understand what is the actual issue. 
What should the data from the API look like?

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
