### ISSUE TITLE
Nightlife Co-ordination app example link is broken

### ISSUE THREAD

**Issue by rajatkantinandi** [freeCodeCamp/freeCodeCamp#16971]
#### Challenge Name

https://www.freecodecamp.org/challenges/build-a-nightlife-coordination-app

#### Issue Description

Nightlife Co-ordination app example link is broken.
It shows Application error on opening the link:
https://yasser-nightlife-app.herokuapp.com/

#### Screenshot

![screenshot 26](https://user-images.githubusercontent.com/17743895/37986381-ecb28f06-3218-11e8-942b-6c49d0bafe18.png)

![screenshot 27](https://user-images.githubusercontent.com/17743895/37986362-e0004ed8-3218-11e8-87c8-9da72e4376e1.png)

**Comment by mstellaluna** [comment]
Notified Yasser in chat to verify his app. Pointed to this issue for him to update

**Comment by mstellaluna** [comment]
As per Yasser, he is receiving the following message "Free app running time quota exhausted".

**Comment by yasserhussain1110** [comment]
Yeah @mstellaluna is right, me free dyno hours have been exhausted for this month. It will be back up from next month.

**Comment by rajatkantinandi** [comment]
@yasserhussain1110 
That's right it's working today as the new month started. 
But I think it should able to recognize the location based on browser location service instead of typing it manually.
