### ISSUE TITLE
[BETA]: Minor Typo/Oversight in Lesson text (Hazards of Imperative Code)

### ISSUE THREAD

**Issue by vipatron** [freeCodeCamp/freeCodeCamp#16970]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/functional-programming/understand-the-hazards-of-using-imperative-code

#### Issue Description
The lesson misses an expected 'new tab' after the 5 social media sites. i.e.: The lesson should say the expected output is:
`['FB', 'Gitter', 'Reddit', 'Twitter', 'Medium', 'new tab', 'Netflix', 'YouTube', 'Vine', 'GMail', 'Work mail', 'Docs', 'freeCodeCamp', 'new tab']`

instead of:

`['FB', 'Gitter', 'Reddit', 'Twitter', 'Medium', 'Netflix', 'YouTube', 'Vine', 'GMail', 'Work mail', 'Docs', 'freeCodeCamp', 'new tab']`

Importantly the code runs as written, and produces the correct expected output.

#### Browser Information
* Browser Name, Version: Firefox 59.0.1
* Operating System: Win 8.1, 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
The lesson says to run the code, not edit it, but the relevant piece of provided code is reproduced here:
```
// Let's create three browser windows
var workWindow = new Window(['GMail', 'Inbox', 'Work mail', 'Docs', 'freeCodeCamp']); // Your mailbox, drive, and other work sites
var socialWindow = new Window(['FB', 'Gitter', 'Reddit', 'Twitter', 'Medium']); // Social sites
var videoWindow = new Window(['Netflix', 'YouTube', 'Vimeo', 'Vine']); //  Entertainment sites

// Now perform the tab opening, closing, and other operations
var finalTabs = socialWindow
                    .tabOpen() // Open a new tab for cat memes
                    .join(videoWindow.tabClose(2)) // Close third tab in video window, and join
                    .join(workWindow.tabClose(1).tabOpen());

alert(finalTabs.tabs);
```

#### Screenshot
![image](https://user-images.githubusercontent.com/36994955/37984921-8878e3b2-31c5-11e8-8970-7674d90101fa.png)

![image](https://user-images.githubusercontent.com/36994955/37984903-7c346018-31c5-11e8-978f-71be4d896ad3.png)

**Comment by mstellaluna** [comment]
Currently working on this PR
