### ISSUE TITLE
Typo in lesson: Regular Expressions: Match Letters of the Alphabet

### ISSUE THREAD

**Issue by yoizfefisch** [freeCodeCamp/freeCodeCamp#16979]
#### Challenge Name

[Regular Expressions: Match Letters of the Alphabet](https://beta.freecodecamp.org/en/challenges/regular-expressions/match-letters-of-the-alphabet)

#### Issue Description

The following text seems to be a typo:
>Be sure to match both upper- and lowercase vowels.

It should say:
>Be sure to match both upper- and lowercase **letters**.

**Comment by LoTerence** [comment]
Hey, I'm a first timer to open source. Is it alright if I take this issue?

**Comment by accimeesterlin** [comment]
PR out https://github.com/freeCodeCamp/freeCodeCamp/pull/17015
