### ISSUE TITLE
"Iterate through an array with a for loop" checks forces you to use "var" cannot use "let" or "const"

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/freeCodeCamp#16983]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/basic-javascript/iterate-through-an-array-with-a-for-loop

#### Issue Description
The challenge requires you to initialize a variable however it forces you to use var, rather than let or const.

#### Browser Information

* Browser Name, Version: Ungoogled Chromium
* Operating System: macOS
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js

N/A

```
#### Screenshot
<img width="1280" alt="screen shot 2018-03-29 at 1 23 37 pm" src="https://user-images.githubusercontent.com/8227641/38103480-6d286e12-3354-11e8-9788-9aced61466c4.png">

**Comment by germangamboa95** [comment]
It is looking for a specific solution that uses the var keyword. 
```  "tests": [
        "assert(code.match(/var.*?total\\s*=\\s*0.*?;/), 'message: <code>total</code> should be declared and initialized to 0');"
      ] ```

As a side note, a lot of the beginning javascript challenges force you to use var. I am pretty sure this is by design.

**Comment by nsuchy** [comment]
In many other begineer challenges I can use let or const without fail - I don't think users should be overly limited in how they can solve a challenge.

**Comment by raisedadead** [comment]
I think I incline towards adding support for `let`. But it doesn't have to be explicit or obvious, even in the test message. As long as we can keep that I am okay to update the tests.

**Comment by saulius-spiridonas-ht** [comment]
I think fcc should not only start supporting but also encourage using ES6 already. Furthermore, arrow functions also somehow buggy. I have encountered a problem while solving basic js tasks, where the same function written as an arrow function provides a different result than conventional function declaration. I have tested this on VScode and it was functioning normally. 

Anyways too much off topic here. like I said it would be nice if fcc would already encourage using ES6 OR at least have a separate module to for teaching ES6 basics and new syntax.

**Comment by Asjas** [comment]
@sINFmaduft Sure you can take it on.

**Comment by Clarke92** [comment]
@Asjas Ok, do i have to mark it somehow?

**Comment by Asjas** [comment]
@Clarke92 Sorry I am not sure what you are talking about? What are you trying to mark?

**Comment by QuincyLarson** [comment]
@sINFmaduft @nsuchy did either of you get around to updating the tests for this challenge to allow for ES6 syntax?

**Comment by mail-liam** [comment]
Hi, I have opened a pull request that updates the tests to fix this issue.
