### ISSUE TITLE
Assert Error: Create A Map Data Structure

### ISSUE THREAD

**Issue by rkm09** [freeCodeCamp/freeCodeCamp#16981]
#### Challenge Name : Create a Map Data Structure

https://beta.freecodecamp.org/en/challenges/coding-interview-data-structure-questions/create-a-map-data-structure

#### Issue Description

[The code below works fine on my IDE, but the 3rd test of “add” fails in fcc sandbox.]
In the seed code of this challenge, the 3rd assert instruction reads :

_“assert((function() { var test = false; if (typeof Map !== ‘undefined’) { test = new Map() }; test.add(5,6); test.add(2,3); test.add(2,5); return (test.size() == 3)})(), ‘message: The add method adds items to the map.’);”_

It adds (5,6),(2,3),(2,5) … then why is it asserting test.size() = 3 ? Shouldn’t it be = 2, since (2,3) and (2,5) will still map to the same key : 2 …?

Shouldn't the assert  be corrected ? 

#### Browser Information

* Browser Name, Version: Mozilla/5.0  Gecko/20100101 Firefox/59.0.
* Operating System: (X11; Ubuntu; Linux x86_64; rv:59.0)
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js
var Map = function() {
  this.collection = {};
  // change code below this line
  this.add = (key,value)=>{
    this.collection[key] = value;
    return this.collection[key];
  };
  this.remove = (key)=>{
    if(this.collection.hasOwnProperty(key)){
      this.collection.delete(key);
    }
  };
  this.get = (key)=>{
    return this.collection[key];
  };
  this.has = (item)=>{
    return (this.collection.hasOwnProperty(item));
 };
 this.values = ()=>{
   let ar = [];
   for(let v in this.collection){
	   ar.push(this.collection[v]);
   }
   return ar;
 }; 
  this.size = ()=>(Object.keys(this.collection).length);
  this.clear = ()=>{
    this.collection = {};
  };
  // change code above this line
};

var m1 = new Map();
m1.add("p1","Tom");
m1.add("p2","Jerry");
m1.add("p3","Julie");
console.log(m1.values());
console.log(m1.size());
m1.clear();
m1.add(2,3);
m1.add(2,5);
m1.add(3,6);
console.log(m1.values());
console.log(m1.size());

```
#### Screenshot

![create-map-data-structure](https://user-images.githubusercontent.com/19933272/38095077-2edb3eda-338d-11e8-8721-6e50f320ff26.png)

**Comment by flipsyde606** [comment]
Hi, from what I can see the OP is right. I can pick this up if no one else is working on it.
