### ISSUE TITLE
Typo - CSS Grid: Limit Item Size Using the minmax Function

### ISSUE THREAD

**Issue by camper-fcc** [freeCodeCamp/freeCodeCamp#16996]
#### Challenge Name
[CSS Grid: Limit Item Size using the minmax Function](https://beta.freecodecamp.org/en/challenges/css-grid/limit-item-size-using-the-minmax-function)

#### Issue Description
For the  challenge, the text states:

> `grid-template-columns: 100px minmax(50px, 200px);`
> 
> In the code above, grid-template-columns is set to create three columns; the first is 100px wide, and the second has the minimum width of 50px and the maximum width of 200px.

This may confuse people who are unfamiliar with the code. Instead, this should read:

> In the code above, grid-template-columns is set to create **two** columns; the first is 100px wide, and the second has the minimum width of 50px and the maximum width of 200px.

#### Screenshot
![css-grid-screenshot](https://user-images.githubusercontent.com/32378788/38169715-5a7780d6-353f-11e8-8618-f3dcce741a5c.png)

**Comment by mglasser** [comment]
I would like to work on this.

**Comment by Bennet11** [comment]
Hi there can I work on this one?

**Comment by huyenltnguyen** [comment]
@Bennet11 Yes, why not?
You'll need to follow the [Contributor's Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md) to raise your PR. If you need any assistance, come and drop a line in the [Contributors chat room](https://gitter.im/FreeCodeCamp/Contributors), or just come say hi anyway. :)

**Comment by moT01** [comment]
@Bennet11 there's another issue you could knock out when you are working on this if you want https://github.com/freeCodeCamp/freeCodeCamp/issues/17004 - it's in the same file

**Comment by Bennet11** [comment]
@moT01 thanks but i checked the issue but somebody already fixed it. Thank you anyway.

**Comment by bhoibrijesh** [comment]
CSS Grid: Limit Item Size Using the minmax Function
Using the minmax function, replace the 1fr in the repeat function with a column size that has the minimum width of 90px and the maximum width of 1fr, and resize the preview panel to see the effect.

<style>
  .item1{background:LightSkyBlue;}
  .item2{background:LightSalmon;}
  .item3{background:PaleTurquoise;}
  .item4{background:LightPink;}
  .item5{background:PaleGreen;}
  
  .container {
    font-size: 40px;
    min-height: 300px;
    width: 100%;
    background: LightGray;
    display: grid;
    /* change the code below this line */
    
    grid-template-columns: repeat(3, 1fr);
    
    /* change the code above this line */
    grid-template-rows: 1fr 1fr 1fr;
    grid-gap: 10px;
  }
</style>
  
<div class="container">
  <div class="item1">1</div>
  <div class="item2">2</div>
  <div class="item3">3</div>
  <div class="item4">4</div>
  <div class="item5">5</div>
</div>

**Solution**
grid-template-columns: repeat(3, 1fr);
change this line with
grid-template-columns: repeat(3, minmax(90px,1fr));
