### ISSUE TITLE
Pinterest clone example project is not working  

### ISSUE THREAD

**Issue by abdelrahman1** [freeCodeCamp/freeCodeCamp#16997]
#### Challenge Name

https://www.freecodecamp.org/challenges/build-a-pinterest-clone

#### Issue Description

Pinterest Clone app example link is broken.
It shows This site can’t be reached on opening the link:
https://midnight-dust.hyperdev.space/

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![sc](https://user-images.githubusercontent.com/5148868/38177174-d2421690-35fc-11e8-9d63-16c574b716fa.png)

**Comment by raisedadead** [comment]
Thanks the updated URL needs to be https://midnight-dust.glitch.me/ and the same is to be done for any urls that are `hyperdev`

We would love a PR to address this, and look though the challenges in `backup/master` branch and update them.

**Comment by raisedadead** [comment]
This is still open for contribution. Please note that we need a PR on the `backup/master` and it should be changing all of the old hyperdev links to glitch

**Comment by leahzxxz** [comment]
@raisedadead tried looking for old hyperdev links on `backup/master` and couldn't find any...is this issue solved?

**Comment by raisedadead** [comment]
Oh yes, @leahzxxz sorry that's my bad it was actually fixed in https://github.com/freeCodeCamp/freeCodeCamp/pull/16917

@Bouncey can you deploy latest production.

**Comment by dboydgit** [comment]
@raisedadead I know this was closed, but did anyone try the new link? I just got to this part of the curriculum and the link returns a timeout.
