### ISSUE TITLE
Typo in the challenge description

### ISSUE THREAD

**Issue by Ildarik** [freeCodeCamp/freeCodeCamp#17000]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/basic-html-and-html5/uncomment-html

#### Issue Description
Typo in the challenge description
`... displayed `~~the~~` to the end user`

#### Screenshot
![image](https://user-images.githubusercontent.com/10713674/38192446-95f8a324-3675-11e8-85b9-e56cce19ca57.png)

**Comment by heanfig** [comment]
i would like to do it :)

**Comment by masterchef2209** [comment]
i would like to work on it

**Comment by chris-joseph** [comment]
so would i..  :-)

**Comment by realgio95** [comment]
Would love to work on this
