### ISSUE TITLE
Typo on CSS Grid: Limit Item Size Using the minmax Function

### ISSUE THREAD

**Issue by snyderc** [freeCodeCamp/freeCodeCamp#17005]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/css-grid/limit-item-size-using-the-minmax-function

#### Issue Description

From the challenge:

> grid-template-columns: 100px minmax(50px, 200px);
> In the code above, grid-template-columns is set to **create three columns**; the first is 100px wide, and the second has the minimum width of 50px and the maximum width of 200px. [emphasis mine]

However, the markup appears to create two columns, not three columns.

**Comment by moT01** [comment]
@snyderc you are correct - there is already an open issue for this - so if you could close this one that would be great.

**Comment by accimeesterlin** [comment]
Here is the other open issue that @moT01  is referring to #16996. @snyderc, Please go ahead and close this issue. Thank you for your contribution of reporting this issue.
