### ISSUE TITLE
Typo - CSS Grid: Align an Item Horizontally using justify-self

### ISSUE THREAD

**Issue by snyderc** [freeCodeCamp/freeCodeCamp#17004]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/css-grid/align-an-item-horizontally-using-justifyself

#### Issue Description
Typo:

Sentence reads: "By default, this property has a value of stetch, which will make the content fill the whole width of the cell."

The word "stetch" should likely be "stretch" ?

**Comment by moT01** [comment]
@snyderc you are correct, this should be changed to `stretch` as described
