### ISSUE TITLE
Single Quote Selectors Pass Test

### ISSUE THREAD

**Issue by afable** [freeCodeCamp/freeCodeCamp#17014]
#### Challenge Name
https://www.freecodecamp.org/challenges/target-html-elements-with-selectors-using-jquery

#### Issue Description

Challenge description states at the bottom that single quote selectors will not pass the test but they do.

#### Browser Information
Google Chrome, Version 65.0.3325.181 (Official Build) (64-bit)
Windows 10
Desktop

#### Your Code

``` 
$('button').addClass( "animated bounce" );
```
#### Screenshot
![2018-04-03](https://user-images.githubusercontent.com/1513169/38267134-6f538fc6-372f-11e8-813d-2380b1f1fc5e.png)

**Comment by bqnguyen94** [comment]
Thanks for reporting the bug! This has been fixed in the beta by removing the single quote restriction. You can check out the beta lesson here:
https://beta.freecodecamp.org/en/challenges/jquery/target-html-elements-with-selectors-using-jquery
