### ISSUE TITLE
[BETA]: Test not working for Sass:Extend Waypoint

### ISSUE THREAD

**Issue by vipatron** [freeCodeCamp/freeCodeCamp#17019]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/sass/extend-one-set-of-css-styles-to-another-element

#### Issue Description
I followed the lesson instruction and extended class .info in the "subclass" .info-important per the code below. It creates two panels, one in magenta (.info-important) per the screenshot below. However, the final test in this waypoint doesn't pass. The in-document console reports similarly:
>Your info-important class should inherit the styling from the info class.

#### Browser Information
* Browser Name, Version: Firefox 59.0.2
* Operating System: Win 8.1, 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```
<style type='text/sass'>
  h3{
    text-align: center;
  }
  .info{
    width: 200px;
    border: 1px solid black;
    margin: 0 auto;
  }
  
  .info-important{
    @extend .info;
    background-color: magenta;
  }
</style>
<h3>Posts</h3>
<div class="info-important">
  <p>This is an important post. It should extend the class ".info" and have its own CSS styles.</p>
</div>

<div class="info">
  <p>This is a simple post. It has basic styling and can be extended for other uses.</p>
</div>
```
#### Screenshot
![image](https://user-images.githubusercontent.com/36994955/38282354-ac62453a-377d-11e8-82f3-4c60f9654058.png)

**Comment by bqnguyen94** [comment]
This happens for me too. In my case the last 2 tests won't pass, but if I run the tests again all tests would pass.

**Browser Information**
- Browser Name, Version: Google Chrome Version 65.0.3325.181 (64-bit)
- Operating System: Win 10, 64-bit
- Mobile, Desktop, or Tablet: Desktop

**Comment by ahmadabdolsaheb** [comment]
@vipatron thanks for reporting this issue, and thanks @bqnguyen94 for confirming it.
@raisedadead  For the third test probably the test runs before SASS compiles to CSS or something but not sure. In any case , I suggest using two regex tests in total. One will look for the background color and the other will look for @extend .   Let me know if you are ok with the solution.

```
 assert(code.match(/\\.info-important\\s*?{[\\s\\S]*background-color\\s*?:\\s*?magenta\\s*?;[\s\S]*}/gi)

 assert(code.match(/\\.info-important\\s*?{[\\s\\S]*@extend\\s*?.info\\s*?;[\\s\\S]*/gi)
```
