### ISSUE TITLE
[BETA]: Possible typo in "Sass: Use @if and @else" Lesson.

### ISSUE THREAD

**Issue by vipatron** [freeCodeCamp/freeCodeCamp#17018]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/sass/use-if-and-else-to-add-logic-to-your-styles

#### Issue Description
I believe there is a typo that can lead to confusion in the first code block in the lesson:
```
@mixin make-bold($bool) {
  @if $bool == bold { font-weight: bold; }
}
```
I believe `$bool` should be a boolean, for clarity and code legibility, and is probably just a typo.

**Proposed Solution:**
I believe the code block should be rewritten as follows:
```
@mixin make-bold($bool) {
  @if $bool { font-weight: bold; }
}
```

#### Browser Information
* Browser Name, Version: Firefox 59.0.2
* Operating System: Win 8.1, 64-bit
* Mobile, Desktop, or Tablet: Desktop

**Comment by varunzxzx** [comment]
Can I start working on this?

**Comment by Asjas** [comment]
@varunzxzx Sure feel free to work on this :+1:

**Comment by texas2010** [comment]
somehow this challenge didn't tell me which CSS code I need to use. but I found out it is the border. so it need to fix that.
