### ISSUE TITLE
Will not accept valid solution

### ISSUE THREAD

**Issue by japfohl** [FreeCodeCamp/freecodecamp#1702]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible. 

See the screenshot for the issue.  I typed the jQuery just as it would have been expected but the tests do not recognize the solution as correct.

![image](https://cloud.githubusercontent.com/assets/13117541/9171188/9164b10a-3f37-11e5-89f7-d5ca927b0ff1.png)

**Comment by kurzninja** [comment]
+1, this waypoint does not accept valid solutions.

**Comment by kurzninja** [comment]
The test on the challenge is testing for the wrong value.
Currently the test checks for rgb(0,0,255) which is blue.
Should be testing for rgb(0,255,0), which is green.
I've fixed and created a pull request for this.
https://github.com/FreeCodeCamp/freecodecamp/pull/1706
