### ISSUE TITLE
Remove instructions for platform specific setup from CONTRIBUTING

### ISSUE THREAD

**Issue by ojongerius** [freeCodeCamp/freeCodeCamp#17022]
I think the Docker set up is mature enough so that we can simplify the contributing document to just refer to Docker.
Doing this will simplify the document, make it easier to maintain. I suspect it will make it really easy for new and existing developers to get started, and for existing contributors to get help from others as reproducing their setup became easy as pie.

As far as I can see the [set-up-mailhog ](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#set-up-mailhog) can be removed, apart from instructions on how to access it. and 
we can merge [set-up-freecodecamp](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#set-up-freecodecamp) with [setup-freecodecamp-using-docker](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#setup-freecodecamp-using-docker).

Any lost value in removing instructions on how to install locally on multiple platforms?

**Comment by varunzxzx** [comment]
But, not everyone uses docker.

**Comment by ojongerius** [comment]
@varunzxzx is there a compelling reason to not use Docker?

**Comment by varunzxzx** [comment]
I am not saying that we shouldn't use Docker. I personally believe that Docker works great when it comes to setting up the development environment. But, I don't think that everyone is familiar with Docker. So, we may lose some contributions.

**Comment by raisedadead** [comment]
is there a compelling reason to not use Docker?

Host system constraints can be an issue for some actually. For example, devices with 4GB of RAM or Windows 7, etc.

These "do not play well" with docker itself often

**Comment by ojongerius** [comment]
I come from environments where Mac and Linux dominate, mostly run on powerful machines. If it is known that those setups do not work well, then I guess we should keep it in there! Thanks for enlightening me 😄
