### ISSUE TITLE
Two Lakewoods, one  camp

### ISSUE THREAD

**Issue by spedoinkle** [freeCodeCamp/freeCodeCamp#17028]
#### Find a local

https://study-group-directory.freecodecamp.org

#### Lakewood, Washington != Lakewood, Colorado

Lakewood, Washington has been entangled into the location of Lakewood, Colorado and Lakewood, Colorado has ceased to exist.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment]
Issue moved to [freeCodeCamp/study-group-directory #84](https://github.com/freeCodeCamp/study-group-directory/issues/84) via [**ZenHub**](https://www.zenhub.com/)
