### ISSUE TITLE
problem with draggable

### ISSUE THREAD

**Issue by acweb-2004** [freeCodeCamp/freeCodeCamp#17023]
#### Issue Description
Hi all, 
this is Augusto from Italy.
In one of my web pages there is a div containing an image wider than the div (container). In order to view it completely, it is to be moved by mouse.
My problem arises when, moving it to the right, and to other directions as well, it goes on beyond the edge instead of stopping at the end of the shot.
I made some attempts:
#### Your Code
{containment: "parent"}

#### Issue Description
When the image is moved, it jumps then stopping random.
Also, when dragging the image, the cursor remains the one defined by (css) and does not change, though I stated:

#### Your Code
{cursor: "move"}
#### Issue Description
Here is the link with the page malfunction:
http://www.parcomonza.org/v4-0/mappa-parco_pc.htm

#### Browser Information
all browsers

**Comment by varunzxzx** [comment]
Hey, @acweb-2004. This is not the place to ask such questions. It's better if you ask it in [freeCodeCamp Earth Facebook Group](https://www.facebook.com/groups/freeCodeCampEarth/) or in the appropriate FreeCodeCamp Gitter room. In this case, it is [FreeCodeCamp/HelpFrontEnd](https://gitter.im/FreeCodeCamp/HelpFrontEnd). Here is the [list](https://gitter.im/FreeCodeCamp/home) of all the rooms which you may need in future :wink:
