### ISSUE TITLE
how-to-use-passport-strategies not testing correctly

### ISSUE THREAD

**Issue by clickingmouse** [freeCodeCamp/freeCodeCamp#17039]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/how-to-use-passport-strategies
https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/create-new-middleware
#### Issue Description

not passing 2nd test

#### Browser Information

chrome/MacOS

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```
  app.route('/login')
  .post(passport.authenticate('local', {failureRedirect:'/'}),(req,res)=>{
res.redirect('/profile');
//res.redirect('/');
});//.post
--------------------------

function ensureAuthenticated(req,res,next) {
if(req.isAuthenticated()) {
return next();
}
res.redirect('/');


  app.route('/profile')
     .get(ensureAuthenticated, (req,res) => {
     res.render(process.cwd() + '/views/pug/profile');
       });

I've even copied the solution template, and modified as above
```
#### Screenshot

![screen shot 2018-04-07 at 11 19 07 am](https://user-images.githubusercontent.com/35300393/38450745-b8462102-3a55-11e8-8cc4-abf49a28b97e.png)

**Comment by raisedadead** [comment]
Hi @clickingmouse can you please share your solution here once again. I tried checking the same from your OP, but seems it could be incomplete?

You can comment below with the entire code. And here is an helpful link https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by clickingmouse** [comment]
https://cheerful-crafter.glitch.me/

here is what i've done, but i might have change those code parts since.. you can try to paste your own solution provided in the link
https://gist.github.com/JosephLivengood/8a335d1a68ed9170da02bb9d8f5b71d5

**Comment by raisedadead** [comment]
Hi @clickingmouse 

I am unsure of the issue here. We request you to give us a succinct explanation of the issue that you are facing.

The link `cheerful-crafter.glitch.me` is your output code. 

> here is what i've done, but i might have change those code parts since.. you can try to paste your own solution provided in the link

This does not help us understand the issue you that you are having.

I would recommend reaching out to the forum or chat for help with reporting the issue.

**Comment by clickingmouse** [comment]
Hello,

I cannot past the second test. (see screen shot)
I have also copy and pasted the model answer provided . and it also does not pass the 2nd test

**Comment by Asjas** [comment]
@clickingmouse Please see our [freeCodeCamp BackEnd Support Channel](https://gitter.im/FreeCodeCamp/HelpBackEnd) for any assistance. We also have a [freeCodeCamp Forum](https://forum.freecodecamp.org/).
