### ISSUE TITLE
Unable to claim Responsive web design certificate

### ISSUE THREAD

**Issue by Vijayalakshmi25** [freeCodeCamp/freeCodeCamp#17031]
I have completed all the projects relevant to responsive web design certificate but unable to claim it and getting below error message. 
![image](https://user-images.githubusercontent.com/34175632/38384380-a1c4b49a-392c-11e8-960e-56f04d953da3.png)

![issue](https://user-images.githubusercontent.com/34175632/38384343-855a268c-392c-11e8-80a0-8c9cf4c38a16.png)

**Comment by raisedadead** [comment]
Hi @Vijayalakshmi25 thanks for reporting. 

We will get this checked. As you may know that beta can be unstable at times, we regret the inconvenience.

Happy coding!

**Comment by Oyelowo** [comment]
I am having the same problem

**Comment by IbrahimTarabay** [comment]
Unable to claim Responsive web design certificate

**Comment by surajsharma** [comment]
Where can i claim my responsive web design certificate?

**Comment by raisedadead** [comment]
Please connect with me via an email `mrugesh at freecodecamp dot org` for login issues. Be sure to include screenshots of your browser console:

On Windows:

Press <kbd>F12</kbd> and then switch to the Console Tab

On macOS:

Press <kbd>⌘</kbd>+<kbd>⌥</kbd>+<kbd>i</kbd> and then switch to the Console Tab

Other Systems:
Please lookup on google on how to open Browser Dev tools
