### ISSUE TITLE
[BETA] Test failure & Typo in "React: Create a Controlled Form" Waypoint

### ISSUE THREAD

**Issue by vipatron** [freeCodeCamp/freeCodeCamp#17033]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/react/create-a-controlled-form

#### Issue Description
**Typo:** The lesson states - 
>The submit handler will be called when the **formed** is submitted.

*Suggested Replacement*:
>The submit handler will be called when the **form** is submitted.

**Test Failure**
Can't get last test to pass [no closed or open issues here, nor on forum], despite testing JSX proving that my code does do what is asked. (I added some html elements to the render() method to prove to myself I wasn't crazy and that the` <input/>` tag was triggering `onChange` events that were being handled properly. The extra code I added in the attached codeblock is as follows:
```
<hr />
<h2>{this.state.input}</h2>
```
The second line should (and does) update with every added or deleted character in the input.
The first line creates a horizontal rule that separates the `<h2>` from the `<h1>` that displays the value of {this.state.submit}, but doesn't appear until the button is clicked. If the error messages were correct, and "Typing in the input element [doesn't] update the input property of the component's state," then the h2 element shouldn't mirror the input's value.

#### Browser Information

* Browser Name, Version: Firefox 59.0.2
* Operating System: Win 8.1, 64-bit
* Mobile, Desktop, or Tablet: Desktop

#### Your Code
```
class MyForm extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      input: '',
      submit: ''
    };
    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }
  handleChange(event) {
    this.setState({
      input: event.target.value
    });
  }
  handleSubmit(event) {
    // change code below this line
    this.setState({
      submit: this.state.input
    });
    event.preventDefault();
    // change code above this line
  }
  render() {
    return (
      <div>
        <form onSubmit={this.handleSubmit}>
          { /* change code below this line */ }
          <input value={this.state.value} onChange={this.handleChange} />
          { /* change code above this line */ }
          <button type='submit'>Submit!</button>
        </form>
        { /* change code below this line */ }
        <h1>{this.state.submit}</h1>
        <hr />
        <h2>{this.state.input}</h2>
        { /* change code above this line */ }
      </div>
    );
  }
};
```

**Comment by bqnguyen94** [comment]
Your `input` value should be `{this.state.input}` instead.

**Comment by vipatron** [comment]
Thanks! The tests pass now. Which implies to me that the testing suite is looking at something other than the state variables themselves. I am just getting started, so I don't know if those state variables are accessible outside of components in React, or if the test is a regex on the JSX. If the latter, and the test is the best it can be, should I edit my issue back down to just the typo?

**Comment by bqnguyen94** [comment]
It's not a regex matching. The test simply compares value of the `input` with `this.state.input`. I'm not 100% sure but looks like if value of `input` is set to `this.state.value` which doesn't exist, the test fails to grab the input value itself?

**Comment by vipatron** [comment]
Thanks for the peek under the hood. I was a little confused as to why the behavior seemed to work despite my typo (which I only introduced on the fourth try of resetting my code because I couldn't wipe out other, weirder errors.

**Comment by EditB** [comment]
Can I fix the typo?

**Comment by varunzxzx** [comment]
@EditB Thanks for your consideration. I already did it. Their are many issues, no one is working on. You can takeup those issues. Make sure you comment on that issue, that you are working on it. So, anyone else don't duplicate his/her efforts. Happy Coding!

**Comment by EditB** [comment]
Thanks @varunzxzx. I have a browse and see what else I can fix.
