### ISSUE TITLE
[BETA] Broken link in React Introducing Inline Styles Waypoint

### ISSUE THREAD

**Issue by vipatron** [freeCodeCamp/freeCodeCamp#17038]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/react/introducing-inline-styles

#### Issue Description
In the lesson, there is a broken link:
*Link text:*"the way you apply classes to JSX elements"
*URL*"https://beta.freecodecamp.org/en/challenges/react/link%20to%20classes%20challenge"

Having done the React lessons in a short time, I just looked at the Map for the React section (because I remembered doing it), and found the unbroken link.

**Suggested Replacement Text**
*Link text:*"the way you apply classes to JSX elements"
*URL*"https://beta.freecodecamp.org/en/challenges/react/define-an-html-class-in-jsx"

**Comment by EditB** [comment]
Can I do this fix?

**Comment by varunzxzx** [comment]
@EditB Yeah sure.

**Comment by EditB** [comment]
I fixed the issue and pushed it to GitHub. This is my first contribution, I hope I did it right.

**Comment by vipatron** [comment]
@EditB Great job! I am trying to learn more before I contribute, so I am trying to be the best beta tester I can be. Sometimes, I just want to keep going, but my duty calls. I am so glad my fastidiousness gave you the chance to pitch in. I and all the other learners thank you. Keep it up!

**Comment by raisedadead** [comment]
@EditB awesome, did you make a pull request, yet?

**Comment by EditB** [comment]
@raisedadead, I believe I did make a pull request as now I only have a 'Close pull request' option... Did it come up ok?

**Comment by EditB** [comment]
@vipatron, Thank you for picking this issue up for me to fix :-) It's a great one for first time contributors. The code fix was the easy part, but man, it's hard work to figure out how to document that one line change properly in the system... Keep up your fantastic testing!
