### ISSUE TITLE
Expects different solution than instructions ask for

### ISSUE THREAD

**Issue by japfohl** [FreeCodeCamp/freecodecamp#1703]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue. 

![image](https://cloud.githubusercontent.com/assets/13117541/9171373/fa58015c-3f38-11e5-9da6-ff9cb501e48b.png)

The instructions on this waypoint ask the user to target the first child of .well but the solution is checking for the user to target the second child.

**Comment by BerkeleyTrue** [comment]
This is being tracked in #1713
