### ISSUE TITLE
Wrong error warning. 

### ISSUE THREAD

**Issue by ArcaneHunter** [freeCodeCamp/freeCodeCamp#17034]
#### Challenge Name

https://www.freecodecamp.org/challenges/change-text-inside-an-element-using-jquery

#### Issue Description

04/april/2018 2:30 (gmt -3)
The errors 

(Emphasize the text in your target4 button by adding HTML tags.
Make sure the text is otherwise unchanged.)

were appearing when just the second one should, here is the code I used in the script.

#### Browser Information

* Browser Name, Version: Gooogle Chrome: 65.0.3325.181 (Versão oficial) 64 bits
* Operating System: Windows 10
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

```js


<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").html("<em>target4</em>");
  });
</script>

here is the one when I finally realize what was wrong.
 
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target4").html("<em>#target4</em>");
  });
</script>



```
#### Screenshot

![freecodecamp](https://user-images.githubusercontent.com/25313105/38405489-806f367a-3946-11e8-97c1-3a020f64b06c.png)
![freecodecamp](https://user-images.githubusercontent.com/25313105/38405494-8be5d8f6-3946-11e8-8bd1-e84d0513271f.png)
https://puu.sh/zXiBW/b3eb3577ae.png

**Comment by raisedadead** [comment]
The second test states the content should not be changed. This text is like so because often times campers, do not pay attention to the instructions and copy the identifiers, variables etc. from the instruction areas.

I think what you have realized is OK, when you are getting started?.

I mean we can of course amend the instructions. But I believe there is worth in keeping this as it is?

What do say?

**Comment by ArcaneHunter** [comment]
The error "emphasize the text in your target4 by adding html tags, shouldn't appear, I actually changed the color. Only the second error should show, "make sure the text is otherwise unchanged" since I change the color and the text, That is what I am suggesting to fix, I spent almost 1 hour trying to fix the color before seeing that I only thing I needed to fix was the text not the color.
