### ISSUE TITLE
Declare a readonly variable with the const keyword uses wrong variable name in tests

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/freeCodeCamp#17041]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/es6/declare-a-readonly-variable-with-the-const-keyword

#### Issue Description
The challenge requires you to change sentence to a const from var, however the default code example uses the variable sentence in lowercase, however you have to change the variable to uppercase for the test to pass.

#### Browser Information

* Browser Name, Version: Firefox ESR
* Operating System: Debian
* Mobile, Desktop, or Tablet: Virtual Machine in Virtual Box

#### Your Code
Not applicable

#### Screenshot
Not available

**Comment by texas2010** [comment]
@nsuchy, I don't see a reason to change that. I checked this challenge. it is fine to me.  you said it is the wrong variable name. I checked the challenge. I test it. I passed what challenged asked us what we suppose to do.   

so it is correct variable name.  they asked to change to const variable name to the uppercase letter

**Comment by texas2010** [comment]
I am sorry, I have to close this. this challenge info is correct.
