### ISSUE TITLE
[BETA] React: Render Conditionally from Props (Pedagogy Problem)

### ISSUE THREAD

**Issue by vipatron** [freeCodeCamp/freeCodeCamp#17048]
#### Challenge Name
https://beta.freecodecamp.org/en/challenges/react/render-conditionally-from-props

#### Issue Description
The lesson starts off saying:
>So far, you've seen how to use `if/else`, `&&`, `null` and the ternary operator (`condition ? expressionIfTrue : expressionIfFalse`) to make conditional decisions about what to render and when. 

I manually checked every waypoint in the React module prior to this one, searching for "null". Except for one state assignment where a variable was set to null, there is no mention of null, thus there is no mention of using null to render conditionally. [The React documentation explains using null to control rendering](https://reactjs.org/docs/conditional-rendering.html#preventing-component-from-rendering). 

**Two possible solutions I see:**
1. Add another waypoint that explains conditional rendering with an example similar to that in the React documentation (it's a good one).

2. Explain it briefly in either:
A) the original [React rendering waypoint](https://beta.freecodecamp.org/en/challenges/react/render-a-class-component-to-the-dom) (less good pedagogically).
B) the [Use && for a More Concise Conditional Waypoint](https://beta.freecodecamp.org/en/challenges/react/use--for-a-more-concise-conditional), which is just 2 waypoints prior to this one (and thus more pedagogically sound). The issue can be explained by showing the students what exactly is going on under the hood in terms of boolean logic, similarly to how it is explained in [the React Documentation here](https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator). To quote them:
>It works because in JavaScript, `true && expression` always evaluates to `expression`, and `false && expression` always evaluates to `false`.

I cannot create a new waypoint (I don't know enough to edit the FCC backend yet), so I can't write up that solution, although I could help design it. If someone on the contributing team decides that option 2B is better, I would suggest basically duplicating the quote from the React documentation, and adding it at the end of the didactic part of that lesson.

**Comment by vipatron** [comment]
I look forward to being able to contribute in more than a beta-tester role, but I don't know the technology stack FCC is using. I see all sorts of error messages from libraries which I have to google, like epic.js. I am just wrapping up React-redux now. Is that part of it?

**Comment by raisedadead** [comment]
Ah.. do not worry, just go through the contributing docs and also the challenge style guide 

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenge-style-guide.md

Hit us up in the chat and we will help!

**Comment by ahmadabdolsaheb** [comment]
@vipatron the file that needs to be modified is the following.
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/03-front-end-libraries/react.json
There you can search for **null** in the document. As you can see the document is divided into challenges. To add a new challenge, duplicate a challenge and change its data accordingly. Don't forget to add a unique id. Follow the instruction for making a new id and making a pull request from the links @raisedadead provided.
Happy contributing and let us know about the progress in here or the contributors gitter room. 👍

**Comment by imcodingideas** [comment]
Im working on fixing this by started out with duplicating this challenge and giving it a unique id. However; how can I access this? I tried localhost.../react/make-conditional-decisions but its not working?

```
    {
      "id": "5add3efd03cc35382f4136d8",
      "title": "Make Conditional Decisions",
      "releasedOn": "April 22, 2018",
      "description": [
        "So far, you've seen how to use <code>if/else</code>, <code>&&,</code> <code>null</code> and the ternary operator (<code>condition ? expressionIfTrue : expressionIfFalse</code>) to make conditional decisions about what to render and when. However, there's one important topic left to discuss that lets you combine any or all of these concepts with another powerful React feature: props. Using props to conditionally render code is very common with React developers &mdash; that is, they use the value of a given prop to automatically make decisions about what to render.",
        "In this challenge, you'll set up a child component to make rendering decisions based on props. You'll also use the ternary operator, but you can see how several of the other concepts that were covered in the last few challenges might be just as useful in this context.",
        "<hr>",
        "The code editor has two components that are partially defined for you: a parent called <code>GameOfChance</code>, and a child called <code>Results</code>. They are used to create a simple game where the user presses a button to see if they win or lose.",
        "First, you'll need a simple expression that randomly returns a different value every time it is run. You can use <code>Math.random()</code>. This method returns a value between <code>0</code> (inclusive) and <code>1</code> (exclusive) each time it is called. So for 50/50 odds, use <code>Math.random() > .5</code> in your expression. Statistically speaking, this expression will return <code>true</code> 50% of the time, and <code>false</code> the other 50%. On line 30, replace the comment with this expression to complete the variable declaration.",
        "Now you have an expression that you can use to make a randomized decision in the code. Next you need to implement this. Render the <code>Results</code> component as a child of <code>GameOfChance</code>, and pass in <code>expression</code> as a prop called <code>fiftyFifty</code>. In the <code>Results</code> component, write a ternary expression to render the text <code>\"You win!\"</code> or <code>\"You lose!\"</code> based on the <code>fiftyFifty</code> prop that's being passed in from <code>GameOfChance</code>. Finally, make sure the <code>handleClick()</code> method is correctly counting each turn so the user knows how many times they've played. This also serves to let the user know the component has actually updated in case they win or lose twice in a row."
      ],
      "files": {
        "indexjsx": {
          "key": "indexjsx",
          "ext": "jsx",
          "name": "index",
          "contents": [
            "class Results extends React.Component {",
            "  constructor(props) {",
            "    super(props);",
            "  }",
            "  render() {",
            "    return (",
            "      <h1>",
            "      {",
            "        /* change code here */",
            "      }",
            "      </h1>",
            "    )",
            "  };",
            "};",
            "",
            "class GameOfChance extends React.Component {",
            "  constructor(props) {",
            "    super(props);",
            "    this.state = {",
            "      counter: 1",
            "    }",
            "    this.handleClick = this.handleClick.bind(this);",
            "  }",
            "  handleClick() {",
            "    this.setState({",
            "      counter: 0 // change code here",
            "    });",
            "  }",
            "  render() {",
            "    let expression = null; // change code here",
            "    return (",
            "      <div>",
            "        <button onClick={this.handleClick}>Play Again</button>",
            "        { /* change code below this line */ }",
            "",
            "        { /* change code above this line */ }",
            "        <p>{'Turn: ' + this.state.counter}</p>",
            "      </div>",
            "    );",
            "  }",
            "};"
          ],
          "tail": "ReactDOM.render(<GameOfChance />, document.getElementById('root'))"
        }
      },
      "solutions": [
        "class Results extends React.Component {\n  constructor(props) {\n    super(props);\n  }\n  render() {\n    return (\n      <h1>\n      {\n        this.props.fiftyFifty ?\n        'You Win!' :\n        'You Lose!'\n      }\n      </h1>\n    )\n  };\n};\n\nclass GameOfChance extends React.Component {\n  constructor(props) {\n    super(props);\n    this.state = {\n      counter: 1\n    }\n    this.handleClick = this.handleClick.bind(this);\n  }\n  handleClick() {\n    this.setState({\n      counter: this.state.counter + 1\n    });\n  }\n  render() {\n    const expression = Math.random() > .5;\n    return (\n      <div>\n        <button onClick={this.handleClick}>Play Again</button>\n        <Results fiftyFifty={expression} />\n        <p>{'Turn: ' + this.state.counter}</p>\n      </div>\n    );\n  }\n};"
      ],
      "challengeType": 6,
      "isRequired": false,
      "translations": {},
      "react": true
    },
```

**Comment by ahmadabdolsaheb** [comment]
@imcodingideas You need to reseed the database by <code>node seed</code> to parses all the changes in JSON files and saves them into the MongoDB.

After that, start the application by <code>npm run develop</code> and to the site's map and navigate to your specific challenge from there.

**Comment by scissorsneedfoodtoo** [comment]
Closing as stale.
