### ISSUE TITLE
Waypoint challenge does not accept this style tag

### ISSUE THREAD

**Issue by rahulkapoor90** [FreeCodeCamp/FreeCodeCamp#1705]
While doing Waypoint: Use CSS Selectors to Style Elements challenge, i used

`<style type="text/css">` tag to complete the code, but it didn't accept it rather accepted only `<style>` tag.

It should accept both kind of tags.

**Comment by Pratik151** [comment]
<style="text/css" is wrong. did you mean <style type="text/css"

Check here for more information : http://www.w3schools.com/tags/att_style_type.asp
I don't know if i am correct as i am also learning.

**Comment by rahulkapoor90** [comment]
Nope , sorry i just wrote it down wrong here.

**Comment by BerkeleyTrue** [comment]
This is the offending test. https://github.com/FreeCodeCamp/freecodecamp/blob/staging/seed/challenges/html5-and-css.json#L386

It does a regex test for style tag. 

@QuincyLarson The cracks are starting to show from our attempt to check for closing tags. Not sure what do about it. We could create our own custom method that takes a tag element as an input and checks to make sure that tag has closing tag. That way we can abstract away this complicated system we have in place.

A quick fix would be for someone in the community to fix the Regex so it is not so strict.

**Comment by rahulkapoor90** [comment]
I'll try.

**Comment by BerkeleyTrue** [comment]
> The import thing is to make editor.match(`/<style>/g`) allow for an optional type attribute equal to "text/css".

**Comment by viznev** [comment]
I submitted a pull request to hopefully fix the issue. The new regex allows for the optional attribute type with both kinds of quotes.

**Comment by rahulkapoor90** [comment]
Nice.

**Comment by viznev** [comment]
My bad, I thought I had submitted a pull request. Turns out I actually had forked a forked copy and submitted a pull request to that instead... yeah, I know, mistake... not one I'll soon forget though haha

**Comment by rahulkapoor90** [comment]
is it fixed or not!

**Comment by jbmartinez** [comment]
I think this may be related to #969 and there's a PR #1752 that try to fix this. I could try to fix both issues if the current PR isn't enough
