### ISSUE TITLE
CSS tutorials not accepting Hex or rgb color values.

### ISSUE THREAD

**Issue by rajatkantinandi** [freeCodeCamp/freeCodeCamp#17052]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/basic-css/use-a-css-class-to-style-an-element

#### Issue Description

In this challenge Hex color values or rgb values are not accepted only ```color:red;``` is accepted.

#### Browser Information

* Mozilla Firefox, Version: 60.0b10 (64-bit)
* Operating System: Ubuntu 17.10

#### Your Code

```html

<style>
  .red-text {
    color: #f00;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>


```
#### Screenshot

![screenshot from 2018-04-10 20-49-49](https://user-images.githubusercontent.com/17743895/38566472-5e612548-3d01-11e8-8f5a-b394b8002943.png)

![screenshot from 2018-04-10 21-14-43](https://user-images.githubusercontent.com/17743895/38567610-4c809504-3d04-11e8-8fd6-9a77c6dea712.png)

![screenshot 28](https://user-images.githubusercontent.com/17743895/38572711-82c1d3c8-3d11-11e8-8164-18c97bda643c.png)

**Comment by mstellaluna** [comment]
@rajatkantinandi Hello. The lesson is designed to use word value for the color as it is the introductory lessons. The test specifically checks for that. Hex values for colors are taught further down. I don't believe this is a bug.

**Comment by rajatkantinandi** [comment]
@mstellaluna 
I know that Hex values are taught in the subsequent lessons but still it should accept those values.
Even after those lessons there is some lessons like: https://beta.freecodecamp.org/en/challenges/applied-visual-design/adjust-the-hover-state-of-an-anchor-tag
which does not accept hex values.
You are right, this is not a bug but I think it is better to accept word value, hex value as well as rgb values.

**Comment by akkatracker** [comment]
I disagree, I think (especially if hex is taught later on) that the word should be the only acceptable solution. The first test addresses whether it is red, the third is whether it is _set_  to red

Only think I maybe think is make the red in the failing test in the 
```
code format
```

**Comment by raisedadead** [comment]
Hi @rajatkantinandi thanks for reporting. What you have pointed might be a good to have case, because the code would be valid.

But, this increases the test complexity. 

Since by design we are looking for specific use case on this challenge, I think its okay to accept only word only values.

Thanks a lot once again, for the QA.

Happy coding!
