### ISSUE TITLE
Redirect old nonprofit project path to new description

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17065]
We need to delete this outdated explanation of our nonprofit projects: `https://www.freecodecamp.org/how-nonprofit-projects-work`

And instead forward the `how-nonprofit-projects-work` tab to this with a 301 redirect: `https://medium.freecodecamp.com/open-source-for-good-1a0ea9f32d5a`

**Comment by Clarke92** [comment]
Hi i would really love to tackle this one!

**Comment by Asjas** [comment]
@Clarke92 There is already a PR made by someone else for this

**Comment by Clarke92** [comment]
@Asjas Sorry, didn't know that. Are there any issues for a beginner, that i could take on?

**Comment by Asjas** [comment]
@Clarke92 Those would be the ones labeled `first timers welcome`. You can see if there are any that aren't currently being worked on, or doesn't have any PRs already open.

**Comment by huyenltnguyen** [comment]
@Clarke92 The issue https://github.com/freeCodeCamp/freeCodeCamp/issues/16983 is quite beginner-friendly, if you'd like to give it a try.
