### ISSUE TITLE
the code is been detected wrongly if attributes added in the opening tag "it don't detect the closing tag as it expect to be <audio controls> only"

### ISSUE THREAD

**Issue by Saadelkheety** [freeCodeCamp/freeCodeCamp#17063]
https://github.com/freeCodeCamp/freeCodeCamp/blob/5b658ae62d7a853529d6e04f23e27f0652bfc02f/seed/challenges/01-responsive-web-design/applied-accessibility.json#L409

**Comment by raisedadead** [comment]
Hi @Saadelkheety can you fill the complete issue template presented to you? It will help us understand the issue much better.

Please reopen a fresh issue.

**Comment by ansonlowzf** [comment]
He means <audio id="sound" controls><source> </audio> take away the id="sound" and leave controls attributes only

Hope its help
