### ISSUE TITLE
Remove LinkedIn account linking

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17066]
2 different campers have reported an issue with LinkedIn account linking. They are getting someone else's account when they attempt to link their account. It's a strange behavior, and it seems to have emerged within the past couple days.

Since we've already removed LinkedIn account linking on beta, we should just remove this feature from production.

I think for now we can just remove the button on the settings page.

**Comment by texas2010** [comment]
@akkatracker thanks.
