### ISSUE TITLE
https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/social-authentication-with-oauth

### ISSUE THREAD

**Issue by clickingmouse** [freeCodeCamp/freeCodeCamp#17068]
1) Same as previous bug; provided glitch template does not have beta.freecodecamp.org in test file...
2) the page doesnt load when entering link in browser, need to select on other challenges, then go to map.. then select the challenge

#### Challenge Name

https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/social-authentication-with-oauth
https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/implementation-of-social-authentication-ii
https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/implementation-of-social-authentication-iii

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment]
@Em-Ant can you guide what is a fix. We can get contributions as per your feedback

**Comment by Em-Ant** [comment]
@raisedadead I need to have a look at the code. I'll let you know in the next days...

**Comment by QuincyLarson** [comment]
@Em-Ant Did you get a chance to investigate this?

**Comment by Em-Ant** [comment]
I'm sure we have the same CORS issue as [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/16967#issuecomment-394180285). 

Probably there is something else to fix,but I'didn't investigate (sorry :innocent: )

**Comment by clandau** [comment]
Here's my pull request. https://github.com/freeCodeCamp/boilerplate-socialauth/pull/1
I'm happy to fix any others that need to be changed.

**Comment by clandau** [comment]
related to this issue...in the new curriculum, I don't think it's clear enough in this challenge that the boilerplates are switching. Maybe the text could mention this. I kept using the advanced node boilerplate and then tests failed due to it testing my server.js file instead of routes.js, as the previous challenge was to separate the project into modules.  
But really I don't think a new boilerplate for social auth is even necessary anymore.  Although then the tests would need to change.

**Comment by QuincyLarson** [comment]
@clandau Thanks for opening this pull request! 

@Em-Ant What are your thoughts on the use of the boilerplate at this point?

**Comment by thecodingaviator** [comment]
Since we've released the changes, this issue should have been fixed. I am, therefore, closing this issue. Please add more information if this still persists and I'll reopen it.
