### ISSUE TITLE
Brand Authorization

### ISSUE THREAD

**Issue by RSyehann** [freeCodeCamp/freeCodeCamp#17076]
#### Issue Description

Dear FreeCodeCampTeam,

I am Ryan Shen, a coder from [Taiwan](https://en.wikipedia.org/wiki/Taiwan). I am writing regarding the possibility of brand authorization of the FreeCodeCamp.

We are a group of Taiwanese coders and freelancers using the FreeCodeCamp online courses to learn and improve our programming skills. To promote the FreeCodeCamp online courses to people who are not familiar with English, we build a website called “freecodecamp.tw” with translators and volunteers.

The reason why we choose to promote FreeCodeCamp is because it is one of the few platforms which provide free, systematic educational resources for beginners and advanced coders alike. We are aware that the website is localized into Simplified Chinese. However, users in both the Hong Kong and the Taiwanese market use Traditional Chinese. The differences are distinct in terminologies and written characters. Localizing the contents into Traditional Chinese would help introduce FreeCodeCamp to more users and contribute largely to the industry and community in Taiwan. We as a group of experienced coders and translators would love to do so with your brand’s authorization.

So far, I’ve already translated 30 articles into Traditional Chinese and my translated articles are posted on my Medium blog and here is the link:
https://medium.com/@RSyehann

slack : [freecodecampclub](https://join.slack.com/t/freecodecampclub/shared_invite/enQtMzQ2NDgxMjc2NDgxLTNlOGY1Y2U3MTc2YzM5NGNjMzM2ZTEzNjdkY2E1NDg0NTI4MzM4MDc0MWY3NDJkNzY5ZTBhOGI0NTljMjk4MWY
)

For any further questions or concerns, please don’t hesitate to contact me.
I look forward to hearing back from your team.

Best regards,
Ryan Shen
NGO Learner Group
ryanshen0922@gmail.com

**Comment by mstellaluna** [comment]
@QuincyLarson FYI.

**Comment by QuincyLarson** [comment]
@RSyehann I saw your email. I will reply to you there.
