### ISSUE TITLE
How do I unsubscribe from freeCodeCamp?

### ISSUE THREAD

**Issue by steelbrain** [freeCodeCamp/freeCodeCamp#17079]
< rant >

I have been trying since forever to unsubscribe from the service's mailing list. Every single time I try to unsubscribe it just says that something went wrong. I have tried marking your email as spam but the fact that I cannot make them stop is extremely annoying and makes me rage :sob:. I even tried to reset my password on your service but every single time I try to reset it I get the same error message that something went wrong.

< /rant >

Apologies for the rant. Here's the URL I get in the email and have tried: https://www.freecodecamp.org/u/i@steelbrain.me

Here's the screenshot

![screen shot 2018-04-23 at 9 32 26 pm](https://user-images.githubusercontent.com/4278113/39140388-dd1b9a94-473d-11e8-9823-6831af580e47.png)

**Comment by bigkatspence** [comment]
team@freecodecamp.org have you tried emailing them directly but email above
to let them know that you wish to unsubscribe from Free code camp

**Comment by teja2210** [comment]
Maybe u can change it email id to some random email is that u don't use

**Comment by raisedadead** [comment]
@QuincyLarson @Bouncey does this have to do with a recent rollout of the email unsubscribe?

**Comment by Bouncey** [comment]
Hi @steelbrain, could you try signing in and then going to `https://www.freecodecamp.org/u/i@steelbrain.me` please. Please let us know if there are any changes or not

**Comment by steelbrain** [comment]
@Bouncey Thank you for the response - I don't remember my password, and reset password doesn't work with the same error message as mentioned in the initial report.

Let me know if there's something else I can do to help debug/fix this issue

**Comment by steelbrain** [comment]
I managed to get into my account through Github SignOn but the unsubscribe link still failed as usual. I was able to turn them emails off through my user preferences.

I personally no longer face this issue so feel free to close, but the underlying bug stands

**Comment by raisedadead** [comment]
Not to be closed, as the underling bug still needs to be resolved.

**Comment by QuincyLarson** [comment]
@steelbrain I tried clicking that link you provided, and it seems to have successfully unsubscribed you. I'm not sure why you were getting an error.

From the screenshot, it looks like an incognito version of Chrome, which is what I also used. And you're the only person who's reported this problem lately (we previously had an issue where people who had accidentally created duplicate accounts wouldn't be able to unsubscribe, but we've since fixed that, and you didn't have duplicate accounts.)

**Comment by steelbrain** [comment]
@QuincyLarson It may be because I have already unsubscribed from the settings. I got the same error from non-incognito window so used an Incognito one for a clean repro for the report

**Comment by Bouncey** [comment]
@steelbrain are you still subscribed or can we close this?

**Comment by steelbrain** [comment]
@Bouncey I am no longer subscribed but the issue was kept open on request of @raisedadead because as he mentioned underlying issue stands

**Comment by raisedadead** [comment]
Yes, that is correct and we are refactoring the code for a different approach for this. I'll close this. We have a separate issue tracking it. Thanks @steelbrain
