### ISSUE TITLE
Code validations on translations

### ISSUE THREAD

**Issue by MichaelMejiaMora** [freeCodeCamp/freeCodeCamp#17073]
#### Challenge Name

Link to external page with anchor elements

#### Issue Description

In the translation to Spanish, the instruction is:
 "Create an `a` element which links to http://freecatphotoapp.com and have the anchor text **"fotos de gatos".**

The validator says:
Your a element should have the anchor text of **"cat photos".**

This will be a trouble in all translations when the validator looks for a string given in a specific language.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

![captura](https://user-images.githubusercontent.com/35932384/39001144-d78b7bd2-43b2-11e8-8e63-38b20f1f8751.PNG)

**Comment by mattlub** [comment]
I can do this!

**Comment by mattlub** [comment]
> This will be a trouble in all translations when the validator looks for a string given in a specific language.

I guess an overhaul of the challenge JSON structure could go something like:

```js
"tests": [
  {
    "assertion": "(/cat photos/gi).test($(\"a\").text())",
    "message": "should have the <code>anchor text</code> of \"cat photos\".",
    "translations": {
      "es": {
        "assertion": "(/fotos de gato/gi).test($(\"a\").text())",
        "message": "debe tener como <code>texto de ancla</code> \"fotos de gato\".",
      }
    }
  },
  {
    "assertion": "etc...",
    "message": "etc..."
  }
]
```
