### ISSUE TITLE
Wrong bootstrap button usage in challenge.

### ISSUE THREAD

**Issue by trockennasenaffe** [freeCodeCamp/freeCodeCamp#17075]
#### Challenge Name

https://www.freecodecamp.org/challenges/create-a-bootstrap-button

#### Issue Description

The button doesn't render in chrome. In Firefox and Safari a grey area appears, but it doesn't seem to be an actual bootstrap button (see screenshots). A default button is created by adding the classes btn and btn-default to the button element. Usage according to the documentation http://bootstrapdocs.com/v3.3.1/docs/css/#buttons:
```js
<!-- Standard button -->
<button type="button" class="btn btn-default">Default</button>


```

#### Browser Information

* Browser Name, Version: Chrome 66.0.3359.117
* Operating System: MacOS 10.13.2
* Mobile, Desktop, or Tablet: Desktop

#### Your Code

imho wrong:
```js

<button class="btn">Like</button>

```
#### Screenshot

the button isn't visible in chrome:
<img width="335" alt="chrome" src="https://user-images.githubusercontent.com/36515150/39026264-6c4d784e-444c-11e8-8fa9-e8c62aa7f9a1.png"><br>
there is a buttonlike gray area rendered in Firefox, but it doesn't have a style which is documented in the bootstrap documentation:
<img width="334" alt="firefox" src="https://user-images.githubusercontent.com/36515150/39026265-6c6b9400-444c-11e8-9f0e-8e73bbe636c8.png"><br>
Valid bootstrap (v3.3.1) buttons:
<img width="558" alt="bootstrap_buttons" src="https://user-images.githubusercontent.com/36515150/39026263-6c28bdc4-444c-11e8-9463-066cf542636f.png">

**Comment by mpro7** [comment]
You have right, it seems that there is a second class missed, which gives the button proper colors. I've also found it as strange when walked through the course but left it without a word. However, even the mistaken one renders good in Chrome 66.0.3359.117 64-bit one ran on Windows 10.

**Comment by SimonOsipov** [comment]
Everything is fine in my Chrome
Version 59.0.3071.115 (Official Build) (64-bit)
Win10

**Comment by raisedadead** [comment]
The rendering issue with chrome is seemingly macOS only.
