### ISSUE TITLE
UX = RADIO BUTTOM for FREE CODE CAMP RADIO !!!

### ISSUE THREAD

**Issue by zoltanalmodo** [freeCodeCamp/freeCodeCamp#17074]
>>> Better UX for FCC radio listeners <<<

I think that radio is a great addition to the website. this feature gives a whole new dimension (AUDIO / SOUND) to the experience of using it.
+most of us listen to music when using the site = (pretty sure many ppl listening.)
the selection is great, the idea also...

BUT i discovered a flaw in the UX on how to reach it.
and this could be improved.

>>>PRESENT STATE of UX
(standpoint = i know nothing about the radio)
i get a push note saying that FCC radio available (but i opt out) only to find out i need a change and don't want to listen to my selection anymore ...

>>>OK BUT
how can i find the radio ??? ( i lost the link when i switched off the push note )
after some search on the forum (searched for "radio" , "free code camp radio" and found nothing)
i eventually asked this on the forum as i could not find the radio.

i got a nice response with the direct link to the radio embedded in the message:
![screen shot 2018-04-19 at 16 38 18](https://user-images.githubusercontent.com/19627325/39002870-6eb4ddc6-43f1-11e8-8549-d97e573d52a2.png)
OK. BUT how can i reach the radio form the site (i asked)...
than i got this message:
![screen shot 2018-04-19 at 16 38 36](https://user-images.githubusercontent.com/19627325/39003760-748ecaca-43f3-11e8-90f6-bcd96de89194.png)

OK. OK it is on RCC you-tube channel.

GREAT!

>>> THE ISSUE with this...
with present UX there is no way to find the radio on the website.
if the user wants to use this feature he has to click (1st) on >>> COMMUNITIES than click (2nd) >>>YOUTUBE and >>> click (3rd) >>> radio on top of the videos.
then it comes alive (in a separate window)
(notice that all other videos are about programming and music is on top.)

>>>????
if Music is so much part of our everyday programming:
quote from an article on medium: 
"campers have collectively spent more than 10,000 hours listening to it while coding."

>>>THAN
-why not have a separate button? with direct access?
-why the station is on you-tube, and why it is a video? (video for audio files?)

I suggest that we first create a separate button (under >>>YOU TUBE<<< and name it >>>RADIO<<< or simple >>>MUSIC<<< or even >>>FCC RADIO<<< or >>>RADIO STATION<<<

than we can also argue about whether it is necessary to keep it on you-tube at all and if we could build this function in the website with a simple on / off button and a visual sign showing that the radio is on... (like the waves on the you-tube channel now.) 

please note: i raised this issue to improve FCC website. i have no intention to criticise it's working or the persons/s who created the website and this function.

please let me know what you think.
thank you.
zoltan

**Comment by Asjas** [comment]
Hi @zoltanalmodo.

The way you are presenting this issue appears almost spam like because of the excessive use of capital letters and very little sentence structure. There are more succinct ways to ask if the freeCodeCamp radio can be added as a separate button on the website. Or why the radio is hosted on YouTube as a video and not somewhere else. Can you rather edit this issue so that it would be more structured?

**Comment by zoltanalmodo** [comment]
I see what you mean...

maybe better just to suggest creating a separate button on the website for the RADIO station (under YouTube). even before thinking about building this function into the website as an extra.

**Comment by Asjas** [comment]
Building the radio into the website would incur charges for hosting and bandwidth. Whereas hosting on a free service such as YouTube there are no costs.

**Comment by zoltanalmodo** [comment]
I understand. === still, a separate button would help a lot! ==== and this issue is about the button and how to access the service. rather than the service itself.

**Comment by mstellaluna** [comment]
@zoltanalmodo Hello. Can you please modify your issue text so it is more readable? It is very hard to tell what your request is concerning FCC Radio due to the excessive use of capital letters and special characters. Thank you.

**Comment by texas2010** [comment]
@zoltanalmodo Sorry, we are not going to build feature for radio. And we cant make a direct link to the live stream. since live stream link is always different. so we are not going to change the direct link every time when someone starts the live stream every time. that is why we put youtube channel link on there. 

I have to close this issue. I don't see a reason for this have a flaw UX about radio issue. sorry again.
