### ISSUE TITLE
Applied Visual Design: Use the em Tag to Italicize Text - nesting change

### ISSUE THREAD

**Issue by lydatech** [freeCodeCamp/freeCodeCamp#17077]
#### Applied Visual Design: Use the em Tag to Italicize Text

https://beta.freecodecamp.org/en/challenges/applied-visual-design/use-the-em-tag-to-italicize-text

#### Issue Description

Incorrect nesting of the <em> element.
The challenge states:  **Wrap an em tag around the paragraph tag to give it emphasis.**
giving this format: `<em><p>Some Text</p></em>`

Should be:  **Wrap an em tag around the paragraph content to give it emphasis.**
with the proper answer:  `<p><em>Some text</em></p>`

**Comment by VoxHumana** [comment]
If no one else is already on it, I'd be happy to take a stab at this.

**Comment by NabheetCloud** [comment]
Is this issue still open? Can i take it up?

**Comment by Asjas** [comment]
Hi @NabheetCloud 

There has already a PR #17093 open for this.

**Comment by thenikhilsaini** [comment]
Hi, This is still an issue.

I am encountering with the same problem.

<p> <em>Google  was founded </em>  by Larry Page and Sergey Brin while they were <u>Ph.D. students</u> at <strong>Stanford University</strong>.</p>

Error: The em tag should wrap around the contents of the p tag but not the p tag itself.

**Comment by thenikhilsaini** [comment]
<p> <em>Google  was founded </em>  by Larry Page and Sergey Brin. </p>

**Comment by RandellDawson** [comment]
@thenikhilsaini Your code is incorrect.  The em tags should be around the entire contents of the paragraph element and not just the words "Google was founded".  

It is best to discuss your code issues on the [forum](https://www.freecodecamp.org/forum/).  If the forum determines you have found a bug, they will point you to the issues tracker.

**Comment by thenikhilsaini** [comment]
Sorry!

It worked now, Thank you so much for the help,

Regarding the code issues, I will keep in mind to discuss it inside the forum.
