### ISSUE TITLE
"Using .env" challenge doesn't test for environment variable correctly

### ISSUE THREAD

**Issue by JMagers** [freeCodeCamp/freeCodeCamp#17080]
#### Using .env
https://beta.freecodecamp.org/en/challenges/basic-node-and-express/use-the-env-file

#### Issue Description
Part of the test is to check if the MESSAGE_STYLE environment variable was provided in the .env file. The current implementation uses the regex [here](https://github.com/Em-Ant/fcc-express-bground-pkg/blob/87a4fe129ac4bc2200a392ff70718fd1617e9d19/index.js#L75) that checks anywhere in the file for a match.

#### Your Code
Examples of code that will match but shouldn't:
```
MESSAGE_STYLE=uppercasejjjj
kkkkMESSAGE_STYLE=uppercase
```
Examples of code that won't match but should:
```
MESSAGE_STYLE='uppercase'
MESSAGE_STYLE="uppercase"
```

**Comment by JMagers** [comment]
I'm working on a PR that avoids using a regex altogether to avoid this problem.

**Comment by raisedadead** [comment]
Hi @JMagers thanks for reporting. @Em-Ant can you confirm the PR opened is at the right repo?

**Comment by Em-Ant** [comment]
@raisedadead Yes I get the PR on my repo. @JMagers is right. I will approve this PR. I think this packege should be forked under freecodecamp, and the boilerplate should access the forked version, so you have control on it.

**Comment by raisedadead** [comment]
Okay, in that case you should transfer the repo over to freeCodeCamp. @Bouncey can help you with the same.

**Comment by raisedadead** [comment]
Thanks a lot for merging the PR.
