### ISSUE TITLE
Camperbot is offline in gitter - approx for 1 week+

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#17094]
#### Challenge Name

Not challenge related. 

Campers in the gitter platform have noticed that camperbot has been offline for
approximately a week or more around the same time as the last FCC maintenance. 

Is it possible to please bring camperbot back online ?

It is not responding to any of the built-in commands (ie. botstatus, rooms, commands)

this is affecting all gitter rooms for FCC.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by raisedadead** [comment]
Hi @mstellaluna we are looking into this.
