### ISSUE TITLE
Contributing Guide- PR instructions inconsistency

### ISSUE THREAD

**Issue by mattlub** [freeCodeCamp/freeCodeCamp#17090]
#### Issue Description
I just submitted a PR for the first time, following the instructions in the Contributing Guide, and noticed a couple of conflicting points:

[link to the Contributing Guide "Creating a PR" section](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#common-steps)

- under **Creating a PR**
  - **method 1/point 8** instructs you to use the tool to create a commit, which automatically adds an issue number and description to the commit message
- under **Common Steps**
  - **point 4** says "Do not add the issue number in the PR title or commit message."
  - **point 5** says "at the end of your PR's description, append the keyword closes and #xxxx (where xxxx is the issue number)"

**I guess the **Common Steps**/**point 4** part should be removed ?**

**Comment by raisedadead** [comment]
Yes, that is correct.

**Comment by Komorebi-Girl** [comment]
Hi! I'm completely new to contributing to open source projects so I'd like to work on this small issue as my first step. Am I correct in thinking that information for common step 4 needs to be completely removed and common steps 5 & 6 need to be re-numbered as common steps 4 & 5?

**Comment by raisedadead** [comment]
Yes.. that is correct @Komorebi-Girl !

**Comment by Komorebi-Girl** [comment]
Okay, great! Can I handle this tiny issue then?

**Comment by sourabh1031** [comment]
is the issue resolved ?I am looking to work on it if not

**Comment by raisedadead** [comment]
Hi @sourabh1031 thanks for the interest. I suggest you look into the tracker, we have more open issues that we can use your help.

**Comment by Komorebi-Girl** [comment]
Okay, I'm a bit stuck. I'm trying to run the npm run commit command to use the commit tool but I get this error message from npm: "'git-cz' is not recognized as an internal or external command,
operable program or batch file." 

I thought perhaps I should do an npm install but when I try to do that nothing happens. No error message. Nothing at all. Am I maybe missing something important?

**Comment by raisedadead** [comment]
@Komorebi-Girl can you reach out to the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by Komorebi-Girl** [comment]
Ok, will do. Thanks!
