### ISSUE TITLE
feat: challenge editor

### ISSUE THREAD

**Issue by thefrontendwizard** [freeCodeCamp/freeCodeCamp#17095]
I've been working ~very very slowly~ on translations of FCC challenges for quite a while now. Honestly, there's a ton of translations to be made and it's unnecessarily hard to do it. I've bootstrapped a super simple app that I believe will make the translators life easier and I'd like a feedback on wether other people feel like this is necessary or not. I'll try to explain where I am now. I've worked on this for less than a day, so it's pretty much a super simple app at it's beginning.

![image](https://user-images.githubusercontent.com/1124448/39408707-cee5be38-4bb0-11e8-8a42-01b13685c8d2.png)
This is the initial screen. It loops through the challenges, counts them and shows up how many has translations and to which languages.

![image](https://user-images.githubusercontent.com/1124448/39408717-06216aa0-4bb1-11e8-8707-00e96a31da79.png)
You click on a language, it shows up the map. All sections are collapsed.

![image](https://user-images.githubusercontent.com/1124448/39408736-45fc9af0-4bb1-11e8-889b-0c87173889a1.png)
You click on a section, it shows up the challenges. The check mark indicates wether or not there's already a translation of that challenge in that language.

![image](https://user-images.githubusercontent.com/1124448/39408754-7579fac0-4bb1-11e8-9637-311a34f93b9e.png)
You click on a challenge. It shows up it's title and it's description. Below there's a input for the title's translation and a textarea for the description.

![image](https://user-images.githubusercontent.com/1124448/39408795-33871840-4bb2-11e8-8eee-9377672c7183.png)
For now it's showing the result on a browser alert when you click submit.

Does anyone see's value on this idea?
I'd like to know to decide wether I keep going or not.

**Comment by raisedadead** [comment]
@julianorafael this is amazing. Nice work!

Have you had a chance to look at the unpack/repack feature added recently to the staging branch?

It unpacks the json files into friendly html files that can be edited in any test editor and then you can re-pack them back to json. See the contributing guide for the commands.

I think that should be a really good place to start. You can theoretically add the UI have on top of that, and we should be able to have an editor (not just for the translation but for the challenges them selves.)

I think we could collaborate your efforts and have a dedicated challenge editor. We have had one in the past but, I like the direction you are headed.

Let us know, if you would like any clarifications.

**Comment by julianorafael** [comment]
@raisedadead thank you.

I'll take a look into it right now. It'd be awesome if could incorporate this into it.

**Comment by bennett-elder** [comment]
I really like the direction this is going. The next task might need to be unpacking the translations:
https://github.com/freeCodeCamp/freeCodeCamp/blob/5fbf8a93a0450ca8064af34a17d9e103f65d0c39/seed/unpack.js#L12

**Comment by julianorafael** [comment]
I'm still going over the pack and unpack code to see how I can incorporate this into it. My first impression is that all that generated html is a bit unnecessary. Couldn't we just work with the json into a react application? The only real issue is reading the data from a file and saving it.

**Comment by julianorafael** [comment]
I should point that I'm biased towards React because I'm a React developer. The goal of this react application would be a generic challenge editor then. That's a fairly simple application to make. I made this prototype in one night.

**Comment by QuincyLarson** [comment]
@julianorafael We just launched the new curriculum and coding platform here: learn.freecodecamp.org

I am now of the opinion that we should have a separate npm module for each of the translated versions of the curriculum. Then we can spin up parallel apps based on different language groups, and people can even host their own translated versions of the curriculum in their own countries if they want. 

Here's the npm module: https://www.npmjs.com/package/@freecodecamp/curriculum We are still working on refactoring this. Would you be interested in helping translate these challenges there?

What are your thoughts on this?

**Comment by julianorafael** [comment]
That's interesting. I'd be happy to contribute to it. I started this because the need for a better environment for translations on FCC is real. Making the translations on the json files is just counter productive. We do need a better of:

1. Visualise the current state of a language translation.
1. Navigate quickly through the challenges.
1. See both the content to be translated (title/description) and the translation side by side at the same screen.

I believe this would make the translations efforts a lot easier and hopefully more people would be able to. We should also keep track of challenges that had either content or title changes so that the translations should be updated accordingly.

**Comment by QuincyLarson** [comment]
@julianorafael Have you had a chance to design any explore this further? I am eager to hear your thoughts on this and see any designs you come up with. If we can converge on a process that works, we can use this same approach with translation into other world languages :)

**Comment by julianorafael** [comment]
@QuincyLarson I've been discussing this topic with @tchaffee, @raisedadead and others on #17511 and #17504. It seems that we agree that there is a need for a more general purposed tool for challenge creation and editing, as well as the translation tool. While we've been brainstorming it, we have not reached into a solid goal yet.

**Comment by tchaffee** [comment]
> I am now of the opinion that we should have a separate npm module for each of the translated versions of the curriculum.

@QuincyLarson Could you explain (over on issue #17511) what you are looking for in non-technical terms? What are you envisioning the workflow would be for translators as well as deploying? If we can understand the vision then we can decide the best way to implement, which might be separate npm modules or something entirely different.

**Comment by thecodingaviator** [comment]
@thefrontendwizard Are we still on with this?

**Comment by thefrontendwizard** [comment]
I'm really not sure. Personally I'm not. The automated translations kind of solved the translating problem. It'd be useful to have a mean to quickly compare different languages sometimes, but I'm not sure this is worth doing a separate application anymore. I'm gonna close this for now. If @tchaffee or anyone else is still pursuing this, feel free to open up and follow up on the topic.

**Comment by raisedadead** [comment]
We are not pursuing the editor anymore. 

We have made good progress in making the local setup working with live changes to the markdown based challenges now. :tada:

We think this is seamless enough for most contributors, with just having to edit markdown, and see the changes live for the coding challenges.
