### ISSUE TITLE
Logo/img is not loading

### ISSUE THREAD

**Issue by Leeoku** [freeCodeCamp/freeCodeCamp#17092]
#### Challenge Name

https://beta.freecodecamp.org/en/challenges/css-flexbox/apply-the-flexdirection-property-to-create-a-column-in-the-tweet-embed

#### Issue Description

When starting challenge, an image file is broken

#### Browser Information

* Browser Name, Version: Firefox focus, latest
* Operating System: w7
* Mobile, Desktop, or Tablet: desktop 

#### Your Code

```js



```
#### Screenshot

https://i.imgur.com/VgVNSfp.png

**Comment by raisedadead** [comment]
@Leeoku could you check your browser's developer console for logs? I believe it should be opened with `F12` key.

**Comment by Leeoku** [comment]
found the reason. Turns out my browser had tracking protection on and hence the image wasn't let through.
