### ISSUE TITLE
[Challenge] Escape Sequences in Strings

### ISSUE THREAD

**Issue by raveesh-me** [freeCodeCamp/freeCodeCamp#17106]
#### Escape Sequences in Strings

https://www.freecodecamp.org/challenges/escape-sequences-in-strings

#### Issue Description

The challenge requires three lines to be stored in a single myStr value:
```
FirstLine
\SecondLine\
ThirdLine
```
This passes for:
```js
var myStr = "FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line
```

The above passing code has the output:
```
FirstLine
\SecondLine\ThirdLine
```
in the console.

#### Browser Information

* Browser Name, Version: Google Chrome `Version 66.0.3359.139 (Official Build) (64-bit)`
* Operating System: Ubuntu 18.04 LTS
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js
var myStr = "FirstLine\n\\SecondLine\\\rThirdLine"; // Change this line
```
#### Screenshot

![screenshot 1](https://user-images.githubusercontent.com/15698263/39562435-40758874-4ec9-11e8-87c3-c120b50b8b54.png)

**Comment by raisedadead** [comment]
Hi @raveesh-me thanks, for reporting. We will be releasing the fix with beta being launched soon.

**Comment by raveesh-me** [comment]
Can you please reference the related commit so that I could see where the code was changed? Would love to explore FCC codebase myself!
