### ISSUE TITLE
Error in Use the Bootstrap Grid to Put Elements Side By Side

### ISSUE THREAD

**Issue by hofmanlc** [freeCodeCamp/freeCodeCamp#17101]
#### Challenge Name

https://www.freecodecamp.org/challenges/use-the-bootstrap-grid-to-put-elements-side-by-side

#### Issue Description

I keep receiving this issue: Make sure each of your div elements has a closing tag.

#### Browser Information

* Browser Name, Version: Chrome, 64.0.3282.186
* Operating System: MAC osSierra 10.12.6
* Mobile, Desktop, or Tablet: Laptop

#### Your Code

```js
 <div class="row">
  <div class="col-xs-4"><button class="btn btn-block btn-primary">Like</button></div>
  <div class="col-xs-4"><button class="btn btn-block btn-info">Info</button></div>
  <div class="col-xs-4"><button class="btn btn-block btn-danger">Delete</button></div>
  </div>



```

**Comment by anthonygallina1** [comment]
I couldn’t reproduce the issue here with Firefox or Chrome. Please try saving your code. Then resetting the Use the Bootstrap Grid to Put Elements Side By Side  lesson.

**Comment by raisedadead** [comment]
Hi there,

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://forum.freecodecamp.com/t/how-to-report-a-bug/19543) first.
- Please try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

If you are still unable, to resolve your issue. Please post all of your code from the editor. 

Happy Coding!
