### ISSUE TITLE
Remove typo from task description

### ISSUE THREAD

**Issue by Ildarik** [freeCodeCamp/freeCodeCamp#17107]
#### Challenge Name
[React: Compose React Components ](https://beta.freecodecamp.org/en/challenges/react/compose-react-components)

#### Issue Description
Typo in task description
`...Next, nest the Fruits class component into` ~~the~~ `the TypesOfFood component, `

**Comment by adi44** [comment]
i will be solving this issue

**Comment by benscho** [comment]
I submitted a pull request, but I'm relatively new to open source github projects so please excuse any errors :)

**Comment by aditya1994** [comment]
Is the task complete or should I do it?

**Comment by Ildarik** [comment]
No, not completed. Open for new attempt )

**Comment by aditya1994** [comment]
Just sent a Pull request. Please check.

**Comment by benscho** [comment]
Hey all, sounds like I didn't properly complete the task. Sorry about that. Would someone mind providing some feedback so I can better understand how to contribute in the future? Thanks!
