### ISSUE TITLE
Not able to proceed further.

### ISSUE THREAD

**Issue by Anikakp** [FreeCodeCamp/freecodecamp#1711]
Challenge http://www.freecodecamp.com/challenges/bonfire-symmetric-difference has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

I am not able to proceed further from this excercise. All the test cases have been passed and I dont see any error. Please let me know what might be the issue here. Attaching screenshot for your reference.
![screen shot 2015-08-10 at 4 37 31 pm](https://cloud.githubusercontent.com/assets/12467036/9186876/ed1ecb9c-3f7e-11e5-9cfa-aa8bd35a1863.png)
![screen shot 2015-08-10 at 4 39 57 pm](https://cloud.githubusercontent.com/assets/12467036/9186884/0c3d67d6-3f7f-11e5-895c-dbb94da2b173.png)

**Comment by Butter1484** [comment]
I'm also having issues, but with the first test
![symmetricdifference](https://cloud.githubusercontent.com/assets/5353136/9188329/104c6960-3fa9-11e5-98e6-f9907fadbea4.PNG)

**Comment by BerkeleyTrue** [comment]
This is fixed in #1671 and will be up soon.

Happy coding!

**Comment by Anikakp** [comment]
Can you please let us know by when the issue will be fixed.

**Comment by BerkeleyTrue** [comment]
Its in beta now.

**Comment by Anikakp** [comment]
I guess this issue will also be resolved in next release. I am facing same issue in almost all exercises.
![screen shot 2015-08-11 at 1 11 42 pm](https://cloud.githubusercontent.com/assets/12467036/9210148/63887fd4-402f-11e5-88ff-0da6948846a4.png)

**Comment by BerkeleyTrue** [comment]
@Anikakp Are you on the beta site?

**Comment by Anikakp** [comment]
Nope. http://www.freecodecamp.com/challenges/bonfire-inventory-update

**Comment by BerkeleyTrue** [comment]
Ok, this won't be fixed in production until beta is released in a couple of days.

**Comment by Anikakp** [comment]
Oh okay. Thank you.

**Comment by BerkeleyTrue** [comment]
Thank you for reporting!

Feel free to reopen if it also does not work on beta.

Happy Coding!

**Comment by Anikakp** [comment]
I am facing same issue in Beta as well. 
![screen shot 2015-08-11 at 6 14 27 pm](https://cloud.githubusercontent.com/assets/12467036/9214608/dac358d8-4054-11e5-820d-7a567723a213.png)

**Comment by BerkeleyTrue** [comment]
Try not to change anything outside your function.

**Comment by BerkeleyTrue** [comment]
This challenge works for me. (with several different versions)

Can you paste the code here?

**Comment by Anikakp** [comment]
function inventory(arr1, arr2) {
    // All inventory must be accounted for or you're fired!
 
 for(var item =0;item<arr1.length;item++){
     for(var current = 0;current<arr2.length;current++){
        if(arr1[item][1] == arr2[current][1]){
          arr2.splice(current,1);
          continue;
        }       
     }
 }
  console.log(arr2);
  arr1 = arr1.concat(arr2);
  arr1.sort(function sortFunction(a, b) {
    if (a[1] === b[1]) {
        return 0;
    }
    else {
        return (a[1] < b[1]) ? -1 : 1;
    }
});
  
    return arr1;
}

**Comment by BerkeleyTrue** [comment]
@Anikakp You code is incorrect. You are forgetting to add up the inventory number.

In the future first try the help chat before posting an issue, chances are some else has gotten stuck on the same issue.

Happy Coding!

**Comment by Anikakp** [comment]
Thanks. got it. Output was same so was not sure if its problem with code. Anyway got it. Thanks.
