### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by garysmeade** [FreeCodeCamp/FreeCodeCamp#1712]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-last-character-in-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

See below for screenshot of the error after entering the code correctly, hitting "Run code",  and then "Go to my next challenge".
![image](https://cloud.githubusercontent.com/assets/13364192/9187045/7450f8d4-400f-11e5-8d31-50bf9d1f0bb5.png)

**Comment by benschenker** [comment]
Closing as stale
