### ISSUE TITLE
Gamification Improvement - Congratulations on Front-End Development Cert

### ISSUE THREAD

**Issue by iarobinson** [freeCodeCamp/freeCodeCamp#17135]
#### Issue Description
After someone works so hard to achieve this point, it might be cool to have some sort of unlisted YouTube video from Quincy congratulating the students on their hard work.

From my personal experience, it feels so good to reach this point and if there was a little video or something, it would have been great.

**Comment by QuincyLarson** [comment]
@iarobinson This is an awesome idea!

I do send out an email to everyone who completes all three certificates, and a lot of people reply to that email and it the basis for much longer discussions about career plans and open source contributions.

I will consider also creating a video for this next time I get a chance (I would want it to have good sound and lighting, and I don't actually own any A/V gear myself. Maybe I can have someone record this at an upcoming conference or something).
