### ISSUE TITLE
[BETA] CSS Grid Auto-Fill TYPO

### ISSUE THREAD

**Issue by akubie** [freeCodeCamp/freeCodeCamp#17137]
#### CSS Grid: Create Flexible Layouts Using auto-fill
https://beta.freecodecamp.org/en/challenges/css-grid/create-flexible-layouts-using-autofill

#### Issue Description
There is a small typo in the CSS class name.

'container 2' needs to be changed to 'container2', this way the user can see the differences between using auto-fill and not using it. (see pictures below)

#### Your Code

```js
  .container2 {
    font-size: 40px;
    min-height: 100px;
    width: 100%;
    background: Silver;
    display: grid;
    grid-template-columns: repeat(3, minmax(60px, 1fr));
    grid-template-rows: 1fr 1fr 1fr;
    grid-gap: 10px;
  }


```
#### Screenshot

![bug](https://user-images.githubusercontent.com/15224111/39714677-1173a610-51e8-11e8-8e07-1e192de371d3.jpg)

![fixed](https://user-images.githubusercontent.com/15224111/39714682-159ee24a-51e8-11e8-81d4-b7b8e38e0249.jpg)

**Comment by raisedadead** [comment]
Its already `container2` for me:

![image](https://user-images.githubusercontent.com/1884376/39718789-f75d3db4-5254-11e8-884a-a621acb96635.png)


Can you check in an incognito window, and confirm?

**Comment by akubie** [comment]
Hmmmm maybe I hit the space bar? I've already solved the problem so I do not know how to go back and see if there is actually an error in the original.

**Comment by raisedadead** [comment]
You could use an incognito window?
