### ISSUE TITLE
Didn't receive F2e certification (the web account have bug).

### ISSUE THREAD

**Issue by Yishin26** [freeCodeCamp/freeCodeCamp#17143]
#### Issue Description

I finished all the challenges and click claim, but I don't receive the certification.

#### Screenshot

![a](https://user-images.githubusercontent.com/8706627/39851874-22dd03e0-544c-11e8-9ab7-c3fecc9894a0.png)

**Comment by raisedadead** [comment]
Hi can you please send an email to team@freecodecamp.org with the full link to your profile https://www.freecodecamp.org/Yishin26

**Comment by curly-brace** [comment]
can confirm this too. completed the last challenge. trying to view certificate by direct link, says that i didn't accepted the academic pledge.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
