### ISSUE TITLE
Escape Sequence in String

### ISSUE THREAD

**Issue by Fahmisyahya** [freeCodeCamp/freeCodeCamp#17141]
Challenge [Escape Sequences in Strings](https://camp.semarangjs.org/challenges/escape-sequences-in-strings#?solution=%0Avar%20myStr%20%3D%20%22firstLine%5C%5C%5Ct%5CtsecondLine%5Cr%5CnthirdLine%22%3B%20%2F%2F%20Change%20this%20line%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:59.0) Gecko/20100101 Firefox/59.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript

var myStr = "firstLine\\\t\tsecondLine\r\nthirdLine"; // Change this line

```

**Comment by raisedadead** [comment]
Hi @Fahmisyahya  as notified to you before, but we do not support issue reports for forks or clones of this project. Please reach out to them.
