### ISSUE TITLE
Why explicitly to set value attribute of input?

### ISSUE THREAD

**Issue by Ildarik** [freeCodeCamp/freeCodeCamp#17151]
#### [React: Create a Controlled Input](https://beta.freecodecamp.org/en/challenges/react/create-a-controlled-input)

Why we need to add `value` attribute (`value={this.state.input}`) to the input? Without setting `value` explicitly we have same result.

**Comment by Bouncey** [comment]
Setting a value allows react to control the input component. It also gives you better access to user input by keeping track of the input value.

Here are the [react docs](https://reactjs.org/docs/forms.html) explaining the controlled vs uncontrolled thing a lot better than I can.

Closing as this isn't and issue, more of a question. We have an awesome [forum](https://forum.freecodecamp.org) for questions like this :+1:
