### ISSUE TITLE
Pairwise Hint Link is broken

### ISSUE THREAD

**Issue by akinhwan** [freeCodeCamp/freeCodeCamp#17156]
Currently from this page https://www.freecodecamp.org/challenges/pairwise
when a user clicks on "Get a Hint" button they are redirected to https://forum.freecodecamp.org/t/freecodecamp-algorithm-challenge-guide-pairwise
but this page says **Oops! That page doesn’t exist or is private.**

it should actually be redirected to https://forum.freecodecamp.org/t/algorithm-pairwise/16038
where the hint page exists for the Pairwise algorithm question!

**Comment by rsangdoung** [comment]
I would like to be assigned to fix (contribute) to this issue.  I'm still new so I'm not sure if I am doing this correctly!

**Comment by raisedadead** [comment]
Hi, while this issue needs a fix or some form of consolidation we would need to take this up after beta is released. Please bear with us in the interim.

**Comment by QuincyLarson** [comment]
I'm closing this issue as stale since it hasn't been active lately. If you think this is still relevant to the newly updated platform, please explain why, then reopen it.
