### ISSUE TITLE
Possible solution issue Project 180 freecodecamp

### ISSUE THREAD

**Issue by Daniel-Michael** [freeCodeCamp/freeCodeCamp#17155]
#### Challenge Name
Introducing else if statements

####  link to challenge
https://www.freecodecamp.org/challenges/introducing-else-if-statements

#### Issue Description
I believe there is a missing parentheses after the second `else` statement which should not pass the test, however it currently does.

If you see the screenshots attached, without the closing parenthese the code passes, but add it in as per the example code and it won't pass the test. 

#### Browser Information

* Browser Name, Version:  Chrome 4.3
* Operating System:  Android
* Mobile, Desktop, or Tablet: Tablet

#### Your Code
```js

function testElseIf(val) {
  if (val > 10) {
    return "Greater than 10";
  } else if (val < 5) {
    return "Smaller than 5";
  } else 
  
  return "Between 5 and 10";
}

// Change this value to test
testElseIf(7);


```
#### Screenshot

![screenshot_20180513-101907](https://user-images.githubusercontent.com/5474330/39962606-759089ca-5697-11e8-9681-8744f0849570.png)

![screenshot_20180513-101927](https://user-images.githubusercontent.com/5474330/39962607-7cffcedc-5697-11e8-8c4b-b1bc46b671a4.png)

**Comment by rsangdoung** [comment]
I would like to be assigned to fix/contribute to this issue.  I'm still new so I'm not sure if I'm doing this correctly.

**Comment by Daniel-Michael** [comment]
@rsangdoung I'd like to accept but I don't know how to assign you.

**Comment by Bouncey** [comment]
Is this a bug or is it just a weird JavaScript thing?

```is
if (someCondition) return foo;
```

Is valid JavaScript, I wouldn't be surprised if the block-less `else` is as well

**Comment by QuincyLarson** [comment]
@Daniel-Michael I agree that we need a curly brace after the else statement.

@rsangdoung Were you able to figure out how to get freeCodeCamp running locally so you can go in and fix it?

**Comment by rsangdoung** [comment]
@QuincyLarson I have forked the repo and created a new branch called "fix/#17155".  It looks like I'm ready to fix it.

**Comment by QuincyLarson** [comment]
@rsangdoung Thanks for your patience. Have you had time to work on this? Once you have successfully forked freeCodeCamp, created a branch, and fixed the issue, you can open a pull request. We have additional details on how to do this in https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md

**Comment by rsangdoung** [comment]
@QuincyLarson I haven't had much success in resolving the seeding issue and my http://localhost:3000 is not functioning properly.  I think you should give it to someone else because I'm not much help at this point.  It's okay.  Thank you.

**Comment by QuincyLarson** [comment]
@rsangdoung OK - no worries. I've added the help wanted label. Anyone who's looking for a curriculum-focused issue to tackle, this is a good one :)

**Comment by devocija-it** [comment]
I would like to work (fix) on this issue if nobody is working on it currently.

**Comment by QuincyLarson** [comment]
@devocija-it OK - sounds great! I've added the in-progress label and am looking forward to seeing your fix for this!
