### ISSUE TITLE
Travis Build Errors

### ISSUE THREAD

**Issue by mstellaluna** [freeCodeCamp/freeCodeCamp#17153]
#### Challenge Name

Not Challenge Related

#### Issue Description

There appears to be an issue with the travis build(s), there are 5 PRs that have failed 

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```
#### Screenshot

 PRs that have failed

https://github.com/freeCodeCamp/freeCodeCamp/pull/17152
https://github.com/freeCodeCamp/freeCodeCamp/pull/17150
https://github.com/freeCodeCamp/freeCodeCamp/pull/17149
https://github.com/freeCodeCamp/freeCodeCamp/pull/17144
https://github.com/freeCodeCamp/freeCodeCamp/pull/17110

**Comment by mstellaluna** [comment]
@QuincyLarson @raisedadead  @Bouncey  FYI

**Comment by QuincyLarson** [comment]
@mstellaluna thanks for reporting this! 

@Bouncey any idea what could be causing these?

**Comment by mstellaluna** [comment]
@QuincyLarson Anytime 😄

**Comment by Bouncey** [comment]
It seems to be a lock file issue. The PR's should be OK to merge, I have fixed the lock file in both of my PR's.

@raisedadead My machine always seems to drop `loopback-component-passport` when I install a package, but picks it up again once I run `npm i`. Any ideas?

**Comment by mstellaluna** [comment]
@Bouncey Hi. I wasn't reviewing or merging the PRs when I noticed this. It seems they are new PRs that were created and fail at the Travis step..

**Comment by raisedadead** [comment]
Hi @Bouncey @mstellaluna thanks for reporting and looking into these. I have recently updated the "custom" loopback component, while I was working on my auth PR. 

This is installed like so https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/package.json#L90

I would consider republishing this and installing from `npm`. Let me take a look and get back to you.

**Comment by raisedadead** [comment]
@Bouncey 's update and clearing off the cache from Travis has fixed the builds. Please re-open in case this persists
