### ISSUE TITLE
Create a maintenance page for freeCodeCamp

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#17161]
This page will be a static page that will be shown when freeCodeCamp is intentionally down for maintenance purposes.

It should be served for all routes

**Comment by aditya1994** [comment]
Hey! I can help.

**Comment by AbdulrahmanEng** [comment]
I would be happy to help.

**Comment by captain-vipul** [comment]
Hello Everyone, I saw this page and I would be happy to contribute to this page, I need mentor for better contribution and do something which makes my contribution acceptable. I am very lucky towards able to contribute and utilized in it!

**Comment by QuincyLarson** [comment]
Done. I just pushed this to https://maintenance-page.freecodecamp.org

**Comment by Nerajno** [comment]
I think i can do a bit more on this .....  the twitter link needs to be centered and open in another page... #my2cents

**Comment by QuincyLarson** [comment]
@Nerajno Thanks for the feedback. We'd welcome your pull requests to improve it :)
