### ISSUE TITLE
Tests do not match the instructions

### ISSUE THREAD

**Issue by 01abhishekjain** [freeCodeCamp/freeCodeCamp#17169]
**Understanding Uninitialized Variables**

In the tests it says:

> **a** should be defined and have a value of **6**

while in the instructions, it is asked to put in a value of **5** for **a**

Similarly, there is mis-match in the tests' description and instruction for variables **b and c also**

#### Screenshot

<img width="1440" alt="screen shot 2018-05-15 at 2 17 30 pm" src="https://user-images.githubusercontent.com/11534188/40046624-065ec3d6-584b-11e8-8c07-ac81d8b08f63.png">

**Comment by raisedadead** [comment]
Hi there,

Thanks for reporting this issue. This is intentional. 

Have a look at the instructions and the code already in the editor and then the tests.
Try looking through our [forum](http://forum.freecodecamp.com) for help with a specific challenge and any coding assistance.

Happy Coding!
