### ISSUE TITLE
Remove all Opbeat Logging

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#17176]
![opbeat-closing](https://user-images.githubusercontent.com/18572518/40123879-21c5f732-591f-11e8-9b42-de704df84dcf.png)

We still have Opbeat on the server, we should remove it as it will not be very helpful next week.

This issue is a good fit for anyone that can delete code :grin:

**Comment by tamj0rd2** [comment]
On it B)

**Comment by rishiip** [comment]
@Bouncey I can work on it, does it already picked up by @tamj0rd2 ?
let me know

**Comment by tamj0rd2** [comment]
Yep I have @rishiip PR coming shortly

**Comment by rishiip** [comment]
@tamj0rd2 no worries.
