### ISSUE TITLE
Investigate Chrome caching browser request

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#17177]
We need to revert this, https://github.com/freeCodeCamp/freeCodeCamp/pull/17170 and for that to work the caching issue discussed on the PR thread needs to be investigated

**Comment by QuincyLarson** [comment]
@raisedadead Is this still something we need to look into?

**Comment by raisedadead** [comment]
Yes. This still needs an investigation.

**Comment by amar633** [comment]
yet another overwhelming message from mrugesh....yaom!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
