### ISSUE TITLE
UI on freecodecamp.org, Potential Confusion Area

### ISSUE THREAD

**Issue by jeinhorn787** [freeCodeCamp/freeCodeCamp#17183]
#### Issue Description
This is more of a comment on the UI of the freecodecamp.org site.  Clicking on the big freeCodeCamp logo in the top left corner of the page initiates different challenges for the user to try out.  This may become very confusing for a brand new visitor just trying to explore the site, especially if they have absolutely no background in coding.  Perhaps these challenges can be inside a new "Challenges" tab?  It may become confusing if someone is just trying to return to the home page only to keep seeing new challenges.

#### Browser Information

* Browser Name, Version:  Chrome, Version 66.0.3359.181
* Operating System: Windows
* Mobile, Desktop, or Tablet: Desktop

**Comment by raisedadead** [comment]
Yes, we are overhauling this experience with the new platform. Try out https://beta.freecodecamp.org
