### ISSUE TITLE
I can't sign in to freeCodeCamp through GitHub or Twitter account, Please help

### ISSUE THREAD

**Issue by shuvongkor-barman** [freeCodeCamp/freeCodeCamp#17185]
I used my GitHub account to sign in to freeCodeCamp but now I can't sign in. I also connected my twitter account with freeCodeCamp but it is not working as well.

I feeling very confused and stressed since I have completed a lot of challenge.

Please help me get my account back.

#### User Information:

Full Name: Shuvongkor Barman
User Name: **shuvongkor-barman**

GitHub User Name: shuvongkor-barman

Twitter User Name: shuvongkor1

#### Browser Information

* Browser Name = Opera
* Version: 52.0
* Operating System: Windows 10
* Desktop 

#### Your Code

```js



```
#### Screenshot
![00](https://user-images.githubusercontent.com/37457267/40252224-84163fc0-5afd-11e8-91ce-6f900b14e2ae.png)
![01](https://user-images.githubusercontent.com/37457267/40252229-88e80326-5afd-11e8-98fd-7b129418e073.png)

**Comment by Sy-CoDe** [comment]
@shuvongkor-barman (note the msg from freecodecamp) https://github.com/freeCodeCamp/freeCodeCamp/issues/14669#issuecomment-341918303 :
> @raisedadead commented on Nov 4, 2017
> Yes, we have disabled new signups via GitHub, you can expect to see this button gone soon too(when we release next version).
> If you are signing up for the first time, please do so via the email, and then link up GitHub through the settings on your profile.

Simply create a freecodecamp account using the same email you used to create your github account.
After that, log into freecodecamp using that email, then go to https://www.freecodecamp.org/settingsand you can link your github account, and your progress should still be there.
Good luck

**Comment by shuvongkor-barman** [comment]
I did exactly what you said but although it is showing that I have completed 112 challenges, on the top it was showing only 1 and when I completed some now it is showing 4. And in the Map it is showing that I did not complete the first 112 challenges.

Why is that?

And please help me solve this problem.

![01](https://user-images.githubusercontent.com/37457267/40266031-b2c6f202-5b65-11e8-8b0f-a68b0432df97.png)
![02](https://user-images.githubusercontent.com/37457267/40266032-b8ea9a08-5b65-11e8-8deb-f14581449136.png)
![03](https://user-images.githubusercontent.com/37457267/40266033-bc0dec62-5b65-11e8-97b5-eff09a75bbd1.png)
![04](https://user-images.githubusercontent.com/37457267/40266034-bf52f354-5b65-11e8-956f-071badc9538f.png)

**Comment by Sy-CoDe** [comment]
-try https://forum.freecodecamp.org/c/support bc it seems this is a known issue
-Also try reaching someone at freecodecamp https://github.com/orgs/freeCodeCamp/people like @raisedadead @QuincyLarson

**Comment by raisedadead** [comment]
@shuvongkor-barman apologies for the delay in getting back to you. please send an email to team@freecodecamp.org from your email that you have with us.

We will try and get this fixed.

/cc @QuincyLarson

**Comment by mabras** [comment]
@raisedaddead I can't sign in either. I have already sent you team@freecodecamp.org without any response.

cc @QuincyLarson

**Comment by raisedadead** [comment]
Hi @shuvongkor-barman @mabras Quincy is currently away until Monday for a work trip. He may not have had access to emails. 

He is the sole person at the moment, who can access the DB.

**Comment by raisedadead** [comment]
Hi @shuvongkor-barman I understand the frustration and apologise for the delay. Unfortunately, as I said, we will have to wait for Quincy to be back. The write access to DB is limited for obvious security reasons. 

We know the issue that you have duplicate accounts which need to be merged. Rest assured, your progress is saved. Merging them to your email account with us will get this working again. 

May I suggest that you do not wait, and keep working through the next challenges, and save the solutions offline somewhere? This way when we have merge your old account with your email, all you would have to do is just re-submit them?

Quincy, reaches US on Monday just so that you know.

Thanks and sorry about the inconvenience.

**Comment by shuvongkor-barman** [comment]
Okay Then. I will wait for the fixing. But I will continue my practice and save my project somewhere online or offline.

Thanks.

**Comment by QuincyLarson** [comment]
@shuvongkor-barman This should now be working on learn.freecodecamp.org

**Comment by kanyshaiosmonova** [comment]
I also have this Problem. I am logging in with my GitHub. I already had to have a Responsive Web Design Certificate there. But there is no certificate and no progress of a curriculum.

**Comment by ilenia-magoni** [comment]
@kanyshaiosmonova if you changed the email address on your github account that would explain what happened, freecodecamp uses the email address to recognise the account.

Please write to support@freecodecamp.org
