### ISSUE TITLE
React challenge should mention 'ReactDOM.render'

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/freeCodeCamp#17186]
#### Challenge Name
Create a Simple JSX Element
https://beta.freecodecamp.org/en/challenges/react/create-a-simple-jsx-element

#### Issue Description
This is not an error. It is a suggestion for how to improve the description of the challenge. 
The way it is currently written, it seems that the code `const JSX = <div></div>;` automatically updates the website with text. 

However, in reality the following line of code is running in the background (but never mentioned): `ReactDOM.render(JSX, document.getElementById('root'))`.

I think this should be more clear in the description of this challenge so people have a more accurate idea about how this works.

**Comment by wesleypearce** [comment]
I'd like to work on this one please!

**Comment by raisedadead** [comment]
@wesleypearce all yours.

**Comment by QuincyLarson** [comment]
@wesleypearce Any updates on this?

**Comment by Wojonatior** [comment]
I will take a stab at this since there hasn't been any updates in 18 days.

**Comment by Wojonatior** [comment]
I've submitted a PR for this issue at  #17473
