### ISSUE TITLE
Test case bug in 'Add Images' Challenge

### ISSUE THREAD

**Issue by lonnv** [freeCodeCamp/freeCodeCamp#17189]
#### Challenge Name

[Add Images to your website](https://www.freecodecamp.org/challenges/add-images-to-your-website)

#### Issue Description

In this challenge you are asked to add an image with an alt attribute.
When you add an alt containing a hyphen the test won't pass.
eg: 
`<img src="https://bit.ly/fcc-relaxing-cat" alt="relaxing-cat">` will faill
`<img src="https://bit.ly/fcc-relaxing-cat" alt="relaxing cat">` will pass

Considering alt attributes are used for screen readers to improve accessibility, I agree that we should not allow hyphens in alts. I think that we should update the wording of the alt test case to reflect that. 

Looking at the get help page for this challenge  a lot of questions from users who used hyphens in their `img` and didn't understand why the tests weren't passing: [link](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-add-images-to-your-website/16640)

**Comment by QuincyLarson** [comment]
@lonnv Thanks for catching this issue. I agree that we should specify in the test something like "Make sure your alt text doesn't have dashes in it." Would you be interested in updating the test for this?

**Comment by lonnv** [comment]
@QuincyLarson I'll make a PR. Just to clarify, do you mean updating the text of the current alt test case. Or adding another test specifically for the dashes. And letting the current alt test case pass with dashes?

**Comment by raisedadead** [comment]
@lonnv a new test case would be clear to beginners IMHO. Thanks for reporting and looking forward to your PR.

**Comment by accimeesterlin** [comment]
Good catch @lonnv 💪!

**Comment by QuincyLarson** [comment]
@lonnv Thanks again for reporting this issue. Have you had a chance to look at this and see if you can get it running locally so you can add the new test?

**Comment by MitsyAahar** [comment]
Hey! if the issue isn't resolved yet. I would like to work upon the same

**Comment by QuincyLarson** [comment]
@MitsyAahar Thanks for your patience. This hasn't been resolved yet. Are you still interested in working on it?

**Comment by MitsyAahar** [comment]
Yes, I am!

**Comment by QuincyLarson** [comment]
@MitsyAahar OK - great. I've set the issue to "in progress". Please keep us posted and if you have any questions for how to fix it, let us know!

**Comment by ChrisBrownie55** [comment]
@QuincyLarson  This should be closed, this error no longer exists. When tested, `<img src="https://bit.ly/fcc-relaxing-cat" alt="relaxing-cat">` passes all the tests.

**Comment by raisedadead** [comment]
Thanks @ChrisBrownie55
