### ISSUE TITLE
freeCodeCamp Thunder Bay https://www.facebook.com/groups/213295925942624/edit/

### ISSUE THREAD

**Issue by ectrion** [freeCodeCamp/freeCodeCamp#17182]
#### Security
Trying to report a security issue?

👌 please report security issues to security@freecodecamp.org instead of raising a Github issue. We look forward to working with you. If the issue is significant we'll work on resolving it as quickly as we can. We'll be happy to mention you in a published list of security researchers that found issues in our projects if you so desire.

#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

```js



```

**Comment by Bouncey** [comment]
Is everything OK @ectrion?

**Comment by QuincyLarson** [comment]
@ectrion I'm closing this issue and sending a message to @johnkennedy9147 to see if he can add this to our directory.

**Comment by johnkennedy9147** [comment]
will include this in the update I am working on just now, thanks
