### ISSUE TITLE
challenge description and solution needs updating to align with MDN best practice

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/freeCodeCamp#17184]
Challenge: "Basic HTML and HTML5 - Create a Set of Radio Buttons"
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-set-of-radio-buttons

Here is the relevant text in the description for this challenge:

> Each of your radio buttons should be nested within its own label element. Wrapping an input element inside of a label element makes the label text clickable.

It is NOT necessary to wrap an input element inside of a label element to make the text clickable as long as there is a `for` field on the label that matches the `id` of the input. The recommendation on fCC is contrary to what is shown at MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

Same for checkboxes. This should be changed as well to match best practices shown on MDN.

It works either way so this is not necessarily an error but I think it is best to change this to go along with MDN.

**Comment by mstellaluna** [comment]
@beaucarnes Hi. Since this one is for learn, do you want to close this one out and re-open it on the learn repo? I can quickly do it if you're not available.

**Comment by beaucarnes** [comment]
I initially had it on learn and was told to close it out and open here. 😀
https://github.com/freeCodeCamp/learn/issues/42

**Comment by mstellaluna** [comment]
@beaucarnes 😄

**Comment by Bouncey** [comment]
To clear any confusion, curriculum issues belong here, platform issues belong in the learn repo. 

We will be publishing the seed files as an npm package shortly, so the seed files held in learn will no longer exist

**Comment by raisedadead** [comment]
And to further clear any confusion log any issue on any of the repositories. 
We (@freeCodeCamp/moderators) will take care of moving them around as needed. There is a (chrome extention)[https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd] that makes this as simple as clicking a few buttons.

**Comment by QuincyLarson** [comment]
@beaucarnes Would you be interested in updating this challenge real quick to bring it into line with best practices?

**Comment by DevonAleshire** [comment]
@beaucarnes I can take care of this. I have looked through the freecodecamp repo and learn repo but did not see where the curriculum is located at though. Must be overlooking it?
