### ISSUE TITLE
Bonfire Sum All Primes Has A Bug

### ISSUE THREAD

**Issue by ayondot** [FreeCodeCamp/freecodecamp#1718]
In the challenge, if you write the codes for the body of the function but you return ''num" (which is the argument passed to the function) instead of "sum" (the expected return value of the function) , all the test cases are marked as being passed though no notification pops up congratulating you and prompting you to move on to the next challenge. 
![buggyprimes](https://cloud.githubusercontent.com/assets/12812037/9190769/1d4534d8-3ff1-11e5-9eb5-5aad614d2525.PNG)
![buggyprimes1](https://cloud.githubusercontent.com/assets/12812037/9190773/23376c9e-3ff1-11e5-8940-89f8ca820817.PNG)

**Comment by ayondot** [comment]
the pictures above are screenshots of my code. As you can see, returning num from my function passes all the test cases but I wasn't able to move to the next challenge, and that was how I figured out there's something wrong with my code. You may want to fix that. Keep on the good work guys! FCC is a great open-source community.

**Comment by BerkeleyTrue** [comment]
@ayondot Which browser and operating system are you running?

**Comment by ayondot** [comment]
I use a Maxthon browser, on a PC running on Windows 8 OS.

**Comment by BerkeleyTrue** [comment]
We do not currently support Maxthon browser.

Its most likely an issue with web workers which will be refactored soon. When that happens it *might* fix this issue.

Happy Coding!
