### ISSUE TITLE
Various Style and wording issues with portfolio/settings pages

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17191]
While QA'ing another PR I noticed several minor style and wording issues.

1. ![localhost_3000_certificates_fcc53b2f70b-6e3d-440a-a90d-cfcba263ced8_responsive-web-design](https://user-images.githubusercontent.com/985197/40273861-55a48c82-5b8e-11e8-8239-7c0e22f91aeb.png)
2. ![profile___freecodecamp](https://user-images.githubusercontent.com/985197/40273862-5ba3bd24-5b8e-11e8-988c-bbccf7028815.png)
3. ![settings___freecodecamp](https://user-images.githubusercontent.com/985197/40273863-65f9f342-5b8e-11e8-9545-6579e05e67d5.png)
4. ![profile___freecodecamp](https://user-images.githubusercontent.com/985197/40273865-6ba724c2-5b8e-11e8-9a92-523469780770.png)
5. ![profile___freecodecamp_](https://user-images.githubusercontent.com/985197/40273867-720f1310-5b8e-11e8-8a59-8adbde86bb16.png)
6. ![settings___freecodecamp_](https://user-images.githubusercontent.com/985197/40273869-7ab4e710-5b8e-11e8-9726-0e84d85b9366.png)
7. ![settings___freecodecamp_](https://user-images.githubusercontent.com/985197/40273871-81f8b3f8-5b8e-11e8-9ac8-0997bd9d68c1.png)
8. ![profile___freecodecamp](https://user-images.githubusercontent.com/985197/40273874-903fbbaa-5b8e-11e8-88b0-fed6b2dde10d.png)
9. ![profile___freecodecamp](https://user-images.githubusercontent.com/985197/40273877-9a841d04-5b8e-11e8-80e7-f30a9baac4bb.png)
10. ![profile___freecodecamp](https://user-images.githubusercontent.com/985197/40273887-c238306a-5b8e-11e8-9962-adc3b1003a10.png)
11. ![profile___freecodecamp](https://user-images.githubusercontent.com/985197/40273879-a254a3e6-5b8e-11e8-9996-6f7c111ce616.png)
12. 
![profile___freecodecamp](https://user-images.githubusercontent.com/985197/40273889-d0fd441e-5b8e-11e8-9e0a-aeb3353fc9cb.png)
13. ![profile___freecodecamp](https://user-images.githubusercontent.com/985197/40273897-1a585004-5b8f-11e8-9b33-55b61a634aa7.png)
14. ![profile___freecodecamp](https://user-images.githubusercontent.com/985197/40273902-2e8f4a50-5b8f-11e8-8f48-8c71979cc8df.png)
15. 
![profile___freecodecamp](https://user-images.githubusercontent.com/985197/40273904-391bce12-5b8f-11e8-83b3-b78f39287c11.png)
16. 
![profile___freecodecamp](https://user-images.githubusercontent.com/985197/40273907-46879ff4-5b8f-11e8-878c-34811eab2121.png)
17. 
![welcome_back_camper___freecodecamp](https://user-images.githubusercontent.com/985197/40273909-4f3c3d44-5b8f-11e8-985b-2d0bd1c2a60c.png)

**Comment by varunzxzx** [comment]
I want to work on some of these issues. I see @Bouncey is assigned to this issue. Can I still submit a PR?

**Comment by Bouncey** [comment]
@varunzxzx We are time critical. We would like to have a PR merged within a few hours. If this seems do-able then go right ahead :+1:
