### ISSUE TITLE
Meet Bonfire

### ISSUE THREAD

**Issue by ayondot** [FreeCodeCamp/freecodecamp#1719]
There seems to be a bug in the above named bonfire. Since the instruction says the function should return true no matter what, simply  assigning "true" as the return value of the function does not pass the tests. Instead, it says "No user tests were run." But it works after console.log() has been commented out.
![meetbonfire](https://cloud.githubusercontent.com/assets/12812037/9190961/af6b15a6-3ff3-11e5-815a-f41f65a6e3fa.PNG)
![meetbonfire1](https://cloud.githubusercontent.com/assets/12812037/9190962/b3bf5248-3ff3-11e5-9f36-0fb40744f1a0.PNG)
The first screenshot shows the code I ran on it, while the second shows the output.You may want to fix that. Keep on the good work. FCC rocks!

**Comment by BerkeleyTrue** [comment]
Hello @ayondot 

Which browser are you running?

**Comment by ayondot** [comment]
I use a Maxthon browser, on a PC running on Windows 8 OS.

**Comment by BerkeleyTrue** [comment]
We do not currently support Maxthon browser.

Its most likely an issue with web workers which will be refactored soon. When that happens it *might* fix this issue.

Happy Coding!
