### ISSUE TITLE
Changing an email on the settings page should change it on Auth0

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#17193]
@Bouncey we need to implement this flow. Until then we should disable changing emails on the profile.  Else this will create multiple accounts on Auth0 itself.

**Comment by RandellDawson** [comment]
@raisedadead Is this still relevant?

**Comment by raisedadead** [comment]
Yes, it is.

Currently if a user changes their email on the profile, it's not updated in Auth0. This can lead to potential conflict. 

We periodically delete emails not found on the User objects from Auth0, but that's still a manual chore. We should be doing this programmatically instead.

Essentially our API (on an email change event) should trigger an update call to the Auth0 management API. This can be achieved using their SDK for Node.js
