### ISSUE TITLE
Fix progress time formatting on portfolios

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17199]
![profile___freecodecamp](https://user-images.githubusercontent.com/985197/40281785-2954c014-5c2b-11e8-842b-3a699caf7b87.png)

**Comment by rishiip** [comment]
@QuincyLarson I would like to work on it, please let me know if it's not been assigned to anyone.

**Comment by Bouncey** [comment]
@QuincyLarson Leading zeros like `01` `02` etc...?

**Comment by raisedadead** [comment]
Hi @rishiip thanks a lot for your interest. We would love your help. Can I recommend you to visit https://github.com/freeCodeCamp/learn and check out the issues there? We need help with the UI and the CSS in general
