### ISSUE TITLE
More minor UI fixes for welcome/settings/portfolios

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17208]
1. ![settings___freecodecamp](https://user-images.githubusercontent.com/985197/40318150-4dfefdda-5ce9-11e8-9942-5f62351d61f4.png)
2. ![banners_and_alerts_and_welcome__quincy_larson____freecodecamp](https://user-images.githubusercontent.com/985197/40318157-555ddb32-5ce9-11e8-9d91-36a813325bda.png)
3. ![settings___freecodecamp](https://user-images.githubusercontent.com/985197/40318162-5a67c034-5ce9-11e8-8753-fe9563db0c71.png)
4. ![profile___freecodecamp](https://user-images.githubusercontent.com/985197/40318202-788d801c-5ce9-11e8-99cd-6cdcf8e81ad1.png)
5. 
![learn_to_code_and_help_nonprofits___freecodecamp](https://user-images.githubusercontent.com/985197/40318972-154c0de0-5cec-11e8-8e4b-e36c6fa2187e.png)

**Comment by aditya1994** [comment]
I'll look into it.
