### ISSUE TITLE
General React/Jest testing errors

### ISSUE THREAD

**Issue by LBWright** [freeCodeCamp/freeCodeCamp#17203]
#### Describe your problem and - if possible - how to reproduce it
Going through Beta with React and after going through a few of the classes, I'm receiving errors or the tests just aren't passing. The first error is `f(...) undefined' in the stateless component section. The second of the errors  is `Enzyme Internal Error: unknown composite type undefined` in the `Create a React Component` page. 
This problem is reproduced by just providing the solution to the problem.

*I've heard of these issues when the package.json and the Jest configuration don't match but I could also be completely wrong.*

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react/create-a-react-component

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: UTD
* Operating System: Ubuntu 16.04

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/36030324/40290778-01065400-5c86-11e8-9fb7-dcb83e8ba4bd.png)
![image](https://user-images.githubusercontent.com/36030324/40290782-0c4fc13e-5c86-11e8-8ce2-75385ff0e54b.png)

**Comment by LBWright** [comment]
Went ahead and tried one more and got the same error.
![image](https://user-images.githubusercontent.com/36030324/40290961-61a67dc0-5c87-11e8-81e3-c2d82921fd2d.png)

**Comment by raisedadead** [comment]
Issue moved to [freeCodeCamp/learn #79](https://github.com/freeCodeCamp/learn/issues/79) via [**ZenHub**](https://www.zenhub.com/)
