### ISSUE TITLE
Forgot password link doesn't expire after use

### ISSUE THREAD

**Issue by jcisneros01** [freeCodeCamp/freeCodeCamp#17201]
#### Describe your problem and - if possible - how to reproduce it
The password reset link does not expire after the user resets their password. A user can use the link indefinitely until the link expires. This is a potential issue if an attacker gains access to a user’s email. With the reset link, the attacker will be able to gain access to a user’s freecodecamp account by using the link to reset the password.

How to Reproduce issue:
1-	Go to https://www.freecodecamp.org/forgot
2-	Enter your email and a reset link will be sent to your email
3-	Use the link to change your password
4-	Use the link multiple times and you’ll be able to change your password until the token expires.

POSSIBLE FIX:
All password reset links should expire immediately after use.

#### Add a Link to the page with the problem
 https://www.freecodecamp.org/reset-password

#### Tell us about your browser and operating system

* Browser Name: Safari
* Browser Version: 11.1
* Operating System: macOS High Sierra 10.13.4

**Comment by raisedadead** [comment]
Thanks for reporting. We have fixed this in our upcoming release. We are getting rid of passwordless completely.

**Comment by raisedadead** [comment]
Closing.. we do not have password based authentication anymore. You will get a sign in code or a link directly on your email every time you sign in.
