### ISSUE TITLE
Completing projects from the settings page does not increment points

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#17200]
Completing projects from the settings page, submitting a url, dose not increment the points a user has.

We need to push a new timestamp to the users `progressTimestamps` array.

**Comment by scissorsneedfoodtoo** [comment]
Hi @Bouncey, I can help out with this. Am I correct in thinking that this should be done in the `common/app/routes/Settings/components/Cert-Settings.jsx` file? If so, I'll look at `server/boot/challenge.js` for some guidance.
