### ISSUE TITLE
Add a Text Alternative to Images for Visually Impaired Accessibility - Broken Image

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#17204]
https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/add-a-text-alternative-to-images-for-visually-impaired-accessibility

This challenge contains a broken image link.

**Comment by sharad-vm** [comment]
At the bottom, the challenge says - "(The image src doesn't link to an actual file, so you should see the alt text in the display.)".

So, I'm guessing, the broken image link is by design? 
If not, I can certainly fix it. Which image should it be using?

**Comment by Bouncey** [comment]
@sharad-vm you are correct. Closing
