### ISSUE TITLE
Can't access previously saved/ completed challenge solutions on learn.freecodecamp.org platform

### ISSUE THREAD

**Issue by rajatkantinandi** [freeCodeCamp/freeCodeCamp#17212]
#### Describe your problem and - if possible - how to reproduce it
Since the launch of new learn.freecodecamp.org platform I'm unable to access previously completed beta challenge solutions. Earlier when I click on a previous challenge link from the map it used to load the previous solution on beta platform.
Now I'm missing this feature & unable to access my earlier solutions.
Please fix this issue.

#### Tell us about your browser and operating system

* Browser Name: chromium
* Browser Version: 66
* Operating System: Ubuntu 18.04

**Comment by raisedadead** [comment]
This is known and we are working on it. We are building beta and its our testing setup. There are chances your progress will reset. And when we launch, it will not be saved.

Your progress from the main site i.e freecodecamp.org will be carried over when we launch.

Here are the FAQs https://forum.freecodecamp.org/t/134331

**Comment by rajatkantinandi** [comment]
OK great then, We should wait until it is completed.
