### ISSUE TITLE
React Issue - this.updater.enqueueCallback is not a function

### ISSUE THREAD

**Issue by LBWright** [freeCodeCamp/freeCodeCamp#17215]
#### Describe your problem and - if possible - how to reproduce it
in `React - Render State in the User Interface`, there is a problem with the testing. The following appears in the test phase of the screen. It never reaches the last test.
```
// running test
this.updater.enqueueCallback is not a function
// tests completed
```
This is my code in the challenge
```
class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      name: 'freeCodeCamp'
    }
  }
  render() {
    return (
      <div>
        { /* change code below this line */ }
          <h1>{this.state.name}</h1>
        { /* change code above this line */ }
      </div>
    );
  }
};
```
#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react/render-state-in-the-user-interface

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: Latest
* Operating System: Ubuntu 16.04

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/36030324/40331413-eb9ac99e-5d15-11e8-8020-de524d2ffbcb.png)

**Comment by LBWright** [comment]
After pursuing the next few tasks, I received the same error in the next 3 fCC React Tasks.

**Comment by Ildarik** [comment]
Same in the task `Use Array.filter() to Dynamically Filter an Array`

**Comment by rajatkantinandi** [comment]
Same problem here..

![image](https://user-images.githubusercontent.com/17743895/40518674-69510ca2-5fd9-11e8-8fff-6c87f87e1ba7.png)

**Comment by rajatkantinandi** [comment]
Is this fix live or yet to be published in Beta release??

Because I'm still getting the error.

Here's the screenshot taken right now..
![image](https://user-images.githubusercontent.com/17743895/40567230-06c32a62-6064-11e8-9104-c048f1473dd8.png)

**Comment by Bouncey** [comment]
@rajatkantinandi The changes will be live around 15 minutes after freeCodeCamp/learn#100 has been merged

**Comment by Bouncey** [comment]
@LBWright @rajatkantinandi @Ildarik A fix has been deployed for this issue, can you please confirm that these challenges now work as expected? Many thanks

**Comment by Ildarik** [comment]
@Bouncey It works, thanks )

**Comment by LBWright** [comment]
Confirmed! Thanks, you're a magician @Bouncey
