### ISSUE TITLE
Clear old access tokens via a cron job

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#17222]
We should find and delete access tokens that have an expired ttl via a cron job.

**Comment by raisedadead** [comment]
We need to implement this. https://docs.mongodb.com/manual/tutorial/expire-data/

**Comment by anubhavsinha98** [comment]
Hey can I work upon this issue?

**Comment by Deborah-Digges** [comment]
Hello @raisedadead. If nobody is working on this, I'd like to help out :)

**Comment by raisedadead** [comment]
Hi, apologies. This was incorrectly flagged. This more of a DevOps issue.

**Comment by codexetreme** [comment]
can I work on this?

**Comment by raisedadead** [comment]
Locking this thread, this is a internal DevOps task for dev team.
