### ISSUE TITLE
how to change old method of login by github account  to new method login with email

### ISSUE THREAD

**Issue by badgh** [freeCodeCamp/freeCodeCamp#17223]
#### Describe your problem and - if possible - how to reproduce it
I used to login with github account. But now I want to use new login method by email. I updated my profile and included email (which was then confirmed by subsequent letter). Now how can I start login with email? I couldn't find any setting to change login method. I do not want to use github account anymore. Of course, all saved status of progress should be kept intact.

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by raisedadead** [comment]
Yes, once you have updated your email. You can start using your email, but as you have added it only after signing up with GitHub, you will have to update the password on it by requesting a link through the forget password.

Then on, you should be able to use your email.

Thanks.

**Comment by raisedadead** [comment]
Here is the link for your reference https://www.freecodecamp.org/forgot
