### ISSUE TITLE
Refactor brownie point API and CamperBot for our migrated User Schema

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#17220]
Reference:

API:
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/models/user.js#L850

Schema
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/models/user.json#L44

CamperBot:
https://github.com/freeCodeCamp/camperbot/blob/master/lib/bot/cmds/thanks.js#L39

Mostly you may not need to change anything in the CamperBot itself.

The API referred above will no longer be storing the giver

**Comment by raisedadead** [comment]
Fallback on launch would be we would have to shutdown the bot unless this is resolved.

**Comment by QuincyLarson** [comment]
We've shut down the Gitter CamperBot temporarily while we figure out an approach for this.

**Comment by raisedadead** [comment]
We are not resurrecting the camperbot. It served us well.

**Comment by QuincyLarson** [comment]
RIP in peace, Gitter CamperBot.
