### ISSUE TITLE
Waypoint: Target the Children of an Element Using jQuery

### ISSUE THREAD

**Issue by FabioSeves** [FreeCodeCamp/freecodecamp#1723]
Challenge http://beta.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by BerkeleyTrue** [comment]
Hello @FabioSeves 

Please do a search before filing issue's. The open issue right before this one is the same. #1713 

Happy coding!
