### ISSUE TITLE
Make the update my settings button same width as the ones on the setting page

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#17230]
Make the update my settings button same width as the ones on the setting page

![image](https://user-images.githubusercontent.com/1884376/40499006-40806fe2-5f9e-11e8-97bd-494ef638d588.png)

![image](https://user-images.githubusercontent.com/1884376/40499040-5ca8baee-5f9e-11e8-9768-1f407b30ee61.png)

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo I saw you were interested in some issues, do you think you will like to take a dig as this?

**Comment by bettychow** [comment]
Can I take this issue?

**Comment by raisedadead** [comment]
@bettychow sure thing! Please go ahead.

**Comment by scissorsneedfoodtoo** [comment]
@bettychow, let us know if you need help with anything!

@raisedadead, thanks! I'll try to pick up another issue here or over on the learn repo. Still have a lot of work formatting challenge descriptions in the interview prep section that I've been putting off, too.

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo great! Thanks a lot for all the efforts, you have put in.
