### ISSUE TITLE
/current-challenge on home does not have my current challenge.

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#17231]
![2018-05-25 02 12 15](https://user-images.githubusercontent.com/1884376/40512683-33dc0378-5fc1-11e8-83b7-0b29fb9fd351.gif)

**Comment by raisedadead** [comment]
I think my last challenge before this was at `HTML Uncomment Elements`

**Comment by Bouncey** [comment]
Closed via freecodecamp/learn#101
