### ISSUE TITLE
 Beta curriculum exercise - Basic JavaScript - Manipulate Arrays With shift()

### ISSUE THREAD

**Issue by seekingcat** [freeCodeCamp/freeCodeCamp#17235]
#### Describe your problem and - if possible - how to reproduce it
I didn't know where to put this, but in this exercise the example code on line 3 does not define the removedFromOurArray variable with the var keyword. This causes the test to fail if the user follows the exercise explicitly and only changes the code below the commented line. I imagine this would be frustrating to new users.

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/manipulate-arrays-with-shift
#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Windows 10

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/23659239/40538145-bf5e3cb2-6008-11e8-91a6-b9fe17f3cc36.png)

**Comment by rajatkantinandi** [comment]
Working on it

**Comment by johnkennedy9147** [comment]
@seekingcat @rajatkantinandi  I think this would need to raised on the repo for learn: https://github.com/freeCodeCamp/learn
cc @raisedadead @Bouncey

**Comment by raisedadead** [comment]
Hi we may have created some confusion on where to create issues and PR

Issues are welcome to opened on any repo you like learn or the main repo. We (@freeCodeCamp/moderators) will take care of moving them around as needed. Just tag us when in doubt. But its fine to just report an not worry 😃!

As for which repo to make a PR against:

- All of the challenge execution logic is now moved to the learn repo. That is to say, it has become our challenge platform. Its based on Gatsby, and is a simple static app.

- The challenge themselves (just the content, instructions, and the tests) are on the main repo. They are now published as a npm package. And used on learn as a dependency.

- The main repo, will just serve the welcome page, user settings and portfolio.

**Comment by seekingcat** [comment]
Thank you for the information. I am just a beginner student, so I’m sure I’ve done something stupid. I didn’t know where to put this, but thought I’d raise this as it confused me and I thought it would confuse others. Please move this to the correct place or delete if appropriate. Thank you.

**Comment by raisedadead** [comment]
@seekingcat its perfectly alright. Thanks for reporting issues. Please keep it up (on any repo you prefer) 👍
