### ISSUE TITLE
FCC Weather API - weather array & icon issue

### ISSUE THREAD

**Issue by psitronic** [freeCodeCamp/freeCodeCamp#17233]
**Challenge Name**

https://www.freecodecamp.org/challenges/show-the-local-weather

**Description**

FCC Weather API looks not to be stable yet. I have a trouble with weather icons. Yesterday I could access it with `weather[0].icon` and there was only one element in the array, but today it looks that  there are already two elements and the icon-key value is not a path to the icon file anymore.

```
"weather":[{"id":521,"main":"Rain","description":"shower rain"},{"id":211,"main":"Thunderstorm","description":"thunderstorm","icon":"11d"}]
```
versus
```
"weather":[ { "id":500, "main":"Rain", "description":"light rain", "icon":"https://cdn.glitch.com/6e8889e5-7a72-48f0-a061-863548450de5%2F10n.png?1499366021399" } ]
```

#### Add a Link to the page with the problem

https://fcc-weather-api.glitch.me/api/current?lat=48.1991623&lon=16.367727

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66.0.3359.170 (Official Build) (64-bit)
* Operating System: Linux

**Comment by QuincyLarson** [comment]
We've moved this challenge into the Interview Prep section with the launch of our new curriculum, so this is less of a priority. This said, @Em-Ant, could you take a look at this when you have time and see if this is still an issue?

**Comment by Em-Ant** [comment]
@QuincyLarson I'm not the author of this api-proxy.
Looking at the project, it seems that @MiloATH is the author. Maybe He has been changing something on it in the last days. I guess He can help better than me.

**Comment by QuincyLarson** [comment]
Hey @MiloATH I just wanted to be sure you saw this issue. Do you have any ideas for how we can fix this?

**Comment by scissorsneedfoodtoo** [comment]
Seems to be working. Closing as stale.

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo This is still an issue that was never fixed.

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, sorry, I checked with a few different city coordinates and never got more than one object in the weather array. Are you still getting the issue?
