### ISSUE TITLE
(beta) user story missing in tribute page (compared to test suite)

### ISSUE THREAD

**Issue by dcookwebdev** [freeCodeCamp/freeCodeCamp#17248]
#### Describe your problem and - if possible - how to reproduce it
- there are 8 user stories on the page
- the test suite has 10 tests
- one test that should be included on the webpage as a user story is that the image should be centered. (simple fix!)
- i.e. **User Story #9:** The img element should be centered on the page.
- *OR* include it in `user story 8` however I think it's more clear for beginners as a separate point

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-tribute-page

**Comment by megantaylor** [comment]
@raisedadead i can haz?
