### ISSUE TITLE
(beta) Survey Form example doesn't pass all tests

### ISSUE THREAD

**Issue by dcookwebdev** [freeCodeCamp/freeCodeCamp#17249]
#### Describe your problem and - if possible - how to reproduce it
- this is not a problem for the curriculum code but on the codepen example
- one test is not passing. see screenshot below

#### Add a Link to the page with the problem
https://codepen.io/freeCodeCamp/full/VPaoNP

#### Tell us about your browser and operating system
* Browser Name: Safari

#### If possible, add a screenshot here
<img width="808" alt="screen shot 2018-05-27 at 21 17 07" src="https://user-images.githubusercontent.com/12954427/40585806-9fb816fc-61f3-11e8-86c2-7c203f275f94.png">

**Comment by esotheriax** [comment]
Hi, I think that this issue deals with your problem:
https://github.com/freeCodeCamp/freeCodeCamp/issues/17506

**Comment by thecodingaviator** [comment]
All tests are passing now, please close this issue @dcookwebdev / @scissorsneedfoodtoo

**Comment by scissorsneedfoodtoo** [comment]
@dcookwebdev, thanks for reporting this. I just checked it out and it seems like your survey form is passing all the tests in Chrome:

![image](https://user-images.githubusercontent.com/2051070/49078535-a18ee680-f281-11e8-924b-a45dee48300c.png)

I think the problem might have been that the test suite only runs in Chrome at the moment, at least according to the template here: https://codepen.io/freeCodeCamp/pen/MJjpwO

I'll close this for now, but please go ahead and run the test suite again in Chrome and report back if you still have problems passing all the tests.

Also, thanks @esotheriax and @thecodingaviator for helping out with this issue!
