### ISSUE TITLE
Add option to claim "Full Stack Developer Certification" to options

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17258]
We want to create one more certification view - the "Full Stack Developer Certification."

This can be claimed with a single click from the settings interface upon having already earned the following certifications. The button for claiming this should be below the new certifications and above the legacy certifications. And should have the following text:

Once you've earned the following freeCodeCamp certifications, you'll be able to claim this The Full Stack Developer Certification:
- Responsive Web Design
- Algorithms and Data Structures
- Front End Libraries
- Data Visualization
- APIs and Microservices
- Information Security and Quality Assurance

[ Claim your Full Stack Developer Certification ]

**Comment by NitronR** [comment]
I have started working on this issue. I will do the following for now, suggestions are welcome:
1. Add the section for the Full Stack Developer Certification at the required position.
2. The section will contain heading and the text about the certification.

**Comment by QuincyLarson** [comment]
These user stories all look good. Thanks for doing this! 

Note that these are certifications - not certificates. The distinction is that certifications have an evaluation criteria (in freeCodeCamp's case, required projects.)

**Comment by NitronR** [comment]
OK, I understand.
