### ISSUE TITLE
How long should I wait for my front-end-certificate? Unable to claim it.

### ISSUE THREAD

**Issue by AlanMamphs** [freeCodeCamp/freeCodeCamp#17251]
#### Describe your problem and - if possible - how to reproduce it

How long should I wait for my front-end-certificate? Should not this bug be resolved already? I have passed everything up to certification. (292 completed tasks). My profile:alanmamphs.

I claimed certificate several times, confirming academic honesty, but it was useless.

#### Add a Link to the page with the problem
https://www.freecodecamp.org/alanmamphs/front-end-certification

https://codepen.io/AlanMamphs

#### Tell us about your browser and operating system

* Browser Name: Chromium
* Browser Version: Version 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Linux 17.04

#### If possible, add a screenshot here
![screenshot from 2018-05-28 06-13-58](https://user-images.githubusercontent.com/14315501/40592214-764ef236-623e-11e8-871f-d74cea8bd2c3.png)
![screenshot from 2018-05-28 06-14-39](https://user-images.githubusercontent.com/14315501/40592215-767d67f6-623e-11e8-86e0-7074ff00064c.png)

**Comment by AlanMamphs** [comment]
No, I did not

**Comment by raisedadead** [comment]
Hi @AlanMamphs apologies for the delays,  this should be resolved now.
