### ISSUE TITLE
Make navbars uniform height, spacing, font-size

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17266]
![freecodecamp_search___learn_to_code_and_help_non-profits_and_settings___freecodecamp_and_responsive_web_design_projects___freecodecamp](https://user-images.githubusercontent.com/985197/40681894-fd9c65e0-634f-11e8-8805-0c0f0e0d6d19.png)

**Comment by scissorsneedfoodtoo** [comment]
Hi @QuincyLarson! I could take care of this. Of the three versions of the navbar, which one is best to base the uniform style on? I'm thinking some combination of the first and second examples, with the height, spacing, and font weight of the second example, but with the search bar wider and centered like in the first example.

**Comment by QuincyLarson** [comment]
Awesome - we would welcome your help! IMHO the best-looking navbar is the the one with the smaller search bar (the middle one). That gives plenty of space for menu items. Currently there are only 3 but we're planning to add 2 more later this year.

**Comment by scissorsneedfoodtoo** [comment]
Okay! I can work on it after going through the open PRs.
