### ISSUE TITLE
Beta: intro challenges cannot be completed

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#17265]
**When you view the curriculum/challenges, there's a check mark next to all the ones you have completed - the intro challenges have no way to submit/complete them so there's no way to get that little check mark (that I am aware of)**

**It's a pretty insignificant thing - but, for some reason, it provides the satisfaction of being completely done with the section**

**Comment by moT01** [comment]
Im not sure we're talking about the same thing... what exactly happened for you? it does not show completion for the challenges in between the two mentioned even though you did complete them?

**Comment by TheMarco77** [comment]
Yes. See attachment. I've completed them all in between. 
![fcc-not_saving](https://user-images.githubusercontent.com/29189997/40682596-2a15caf8-635a-11e8-90ce-701149eac548.jpg)
![fcc-not_saving_1](https://user-images.githubusercontent.com/29189997/40682597-2a25d786-635a-11e8-87a0-45d5d1fd4c89.jpg)

**Comment by moT01** [comment]
I was specifically talking about the "introduction" challenges - like the first one under `basic css` - you can't complete them or get the check mark - what you're seeing is probly a bigger problem

**Comment by TheMarco77** [comment]
Ah okay.

**Comment by mattszcz** [comment]
Now that beta is live, this bug still persists. Cannot receive a checkmark for the first lesson of every section.
