### ISSUE TITLE
Beta Navigation Inconsistencies

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#17261]
**Beta navigation bar links are inconsistent - sometimes they open in new tabs, and sometimes in the current tab - here's exactly what happens...**

###### from the home page
- learn + forum open new tab
- settings + next challenge open in current tab 

###### from the settings page 
- forum + learn = new tab 

###### from the learn page 
- settings + forum + learn = current tab 

###### from a challenge 
- everything opens in current tab

<br>

**I think the best user experience would be to always have the forum open in a new tab - and everything else always open in the current tab**

<hr>

* Browser Name: Firefox
* Browser Version: 60.0.1
* Operating System: High Sierra

**Comment by QuincyLarson** [comment]
One issue with this is that on learn the curriculum should open in a new tab because otherwise it might wipe out the camper's progress on their current challenge, which is only saved whenever they run their code.

**Comment by moT01** [comment]
@QuincyLarson it looks like `learn` already behaves that way... The PR I made over on that repo would change the forum button to open in a new tab - but not curriculum. 

This PR would change it so the curriculum will open in the current tab when clicking it while on homepage or the settings page

**Comment by raisedadead** [comment]
Ok.. I went over this once again and I think @moT01 is correct. However I see that the learn is opening in the same tab. I guess we should change that over there. I'll accept the PR once I have a word with Quincy.
