### ISSUE TITLE
Make privacy toggles easier to read and add save button

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17275]
![settings___freecodecamp](https://user-images.githubusercontent.com/985197/40737926-bdce826e-6407-11e8-8f49-e4818bb34f28.png)

**Comment by rajatkantinandi** [comment]
I want to try this one.
What should be the onclick event function on the save button??

**Comment by QuincyLarson** [comment]
@rajatkantinandi We're refactoring this to use Pug instead of React (React isn't really justified for such a simple web app at this point). I'm closing this issue for now and we can look at the formatting again once the Pug version is live.
