### ISSUE TITLE
Convert challenge seeds to the new format

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/freeCodeCamp#17270]
It seems like the challenge seed format has changed sometime in the past couple of months? For example, there is now a `files` property which I think replaces the `challengeSeed`. I'm assuming someone wrote a script or something to convert from the old format into the new format?

**Comment by tchaffee** [comment]
@QuincyLarson @raisedadead @Bouncey Any ideas on this? I would like to switch over to the new learn platform for a custom curriculum I wrote, but this is holding me back.

**Comment by raisedadead** [comment]
Hi @tchaffee this repo is coming up real soon https://github.com/freeCodeCamp/curriculum I'll comment here as soon as its ready.

Just so that you know it will the the npm package that we will use on learn
