### ISSUE TITLE
Issue with Curriculum, Sent back to first challenge.

### ISSUE THREAD

**Issue by Prachi2322** [freeCodeCamp/freeCodeCamp#17273]
Creating the issue with actual user.

Email Id - prachik2322@gmail.com

I joined freeCodeCamp 2-3 days back for learning node js, though on joining I have no way of navigating to NodeJS curriculum , I have to start with HTML, I started from there and somehow completed around 32 challenges, now today when I am logging in , it shows me that I have completed 32 challenges, but it redirects me to first challenge again on clicking on go to next challenge.

Link - https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements

#### Tell us about your browser and operating system

* Browser : Google Chrome 
* Browser Version: Version 66.0.3359.181 (Official Build) (64-bit)  
* Operating System :  Windows 10
![courseoffered](https://user-images.githubusercontent.com/25793622/40737541-b0b58aa8-645e-11e8-8729-7a87b93626fa.JPG)
![homepage](https://user-images.githubusercontent.com/25793622/40737543-b108dcf8-645e-11e8-8727-801593638693.JPG)

**Comment by TheMarco77** [comment]
Having the same issue.

**Comment by richRocksCodeBlocks** [comment]
Do a hard refresh of the page.  That worked for me and now all of my challenges and solutions are showing.

**Comment by TheMarco77** [comment]
Cool! 
Newbie question!
What does a hard refresh mean to you? Deleting history "cache, cookies"?

**Comment by QuincyLarson** [comment]
@TheMarco77 I believe it clears the cache and reloads all the assets (images, HTML, CSS, JavaScript, JSON, etc) from scratch. I don't think it affects history or cookies.

**Comment by TheMarco77** [comment]
@QuincyLarson I did that, I still have a large amount of challenges that are not checked off. I did them and it still shows as I did not.

**Comment by TheMarco77** [comment]
Hello all, I also noticed it my activities on the grid! If that is the correct term for it! It is not recording, here is my profile link https://www.freecodecamp.org/portfolio/marcodoescode

**Comment by QuincyLarson** [comment]
@TheMarco77 it's possible that you have more than one account. If you think this is the case, could you send me an email at team@Freecodecamp.org with any other accounts, email addresses, etc you may have used? I can look into this for you.
