### ISSUE TITLE
Issue with the curriculum. Back to challenge one.

### ISSUE THREAD

**Issue by kratikaguptauser** [freeCodeCamp/freeCodeCamp#17272]
Email Id - prachik2322@gmail.com

I joined freeCodeCamp 2-3 days back for learning node js, though on joining I have no way of navigating to NodeJS curriculum , I have to start with HTML, I started from there and somehow completed around 32 challenges, now today when I am logging in , it shows me that I have completed 32 challenges, but it redirects me to first challenge again on clicking on go to next challenge.

Link - https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements

#### Tell us about your browser and operating system

* Browser : Google Chrome 
* Browser Version: Version 66.0.3359.181 (Official Build) (64-bit)  
* Operating System :  Windows 10
![courseoffered](https://user-images.githubusercontent.com/39596125/40737213-be5d0498-645d-11e8-9913-bccd1dbc2a32.JPG)
![homepage](https://user-images.githubusercontent.com/39596125/40737214-be9b8c5e-645d-11e8-8a2a-3fc2b74f8459.JPG)

**Comment by QuincyLarson** [comment]
Please try refreshing https://learn.freecodecamp.org. Then click on the "view full curriculum" button and see if it shows your progress. Please let us know if that works.

**Comment by thecodingaviator** [comment]
@QuincyLarson Since we have not heard from @kratikaguptauser , I think we can close this issue
