### ISSUE TITLE
Revert to Bootstrap Flash notifications instead of current mishmash of flashes

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17276]
![settings___freecodecamp](https://user-images.githubusercontent.com/985197/40738069-23f64d38-6408-11e8-8b3a-f67ad61c3ac3.png)

![settings___freecodecamp](https://user-images.githubusercontent.com/985197/40738574-8a50e09c-6409-11e8-9904-6b43948222db.png)

**Comment by raisedadead** [comment]
Resolved in staging.
