### ISSUE TITLE
Typo on private profile notification

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#17285]
#### Describe your problem and - if possible - how to reproduce it

There is a typo on the notification shown to the user. certifications is incorrectly spelled.

#### Add a Link to the page with the problem

`/portfolio`

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System: 

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/1884376/40742838-5d6ce3a0-646d-11e8-93a7-dcfae6bf7b26.png)

**Comment by ChristianBeach** [comment]
I made the change. https://github.com/freeCodeCamp/freeCodeCamp/compare/master...ChristianBeach:patch-1

Not sure if that is the right link. This is my first change

**Comment by ChristianBeach** [comment]
Argh sorry, didn't follow the guidelines very well with my last one. It's closed now. This one should follow everything correctly
https://github.com/freeCodeCamp/freeCodeCamp/compare/staging...ChristianBeach:patch-2
