### ISSUE TITLE
Feature request - add night mode to new code editor

### ISSUE THREAD

**Issue by JustFly12** [freeCodeCamp/freeCodeCamp#17289]
#### Describe your problem and - if possible - how to reproduce it
It wull be nice to keep a night mode as in the previous version of code editor, where the background was dark by default,

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by johnkennedy9147** [comment]
@JustFly12 Thanks for raising this, it is planned to have night mode available in the editor.
But rather than a default it will track the users choice in settings.
I'm closing this issue in favour of #17412 which better describes the issue.
