### ISSUE TITLE
View Curriculum button leading to blank pages. 

### ISSUE THREAD

**Issue by Siege211** [freeCodeCamp/freeCodeCamp#17283]
#### Describe your problem and - if possible - how to reproduce it
Clicking on "view curriculum" button crashes the page. When refreshed, the button will work and be able to navigate to a new challenge. After completing the next challenge, you must repeat the cycle of crash-refresh-click in order to view curriculum. 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/define-the-head-and-body-of-an-html-document

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66.0.3359.181
* Operating System: Windows 10
![screenshot](https://user-images.githubusercontent.com/18180182/40741589-885996c8-6411-11e8-8ef8-0863a3119b75.jpg)

**Comment by mattszcz** [comment]
#17309

**Comment by ahmadabdolsaheb** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #17309, so I am closing it as a duplicate.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding
