### ISSUE TITLE
JavaScript Algorithms and Data Structures Projects - Caesars Cipher

### ISSUE THREAD

**Issue by JMVL64** [freeCodeCamp/freeCodeCamp#17282]
#### Describe your problem and - if possible - how to reproduce it
I cannot pass the JavaScript Algorithms and Data Structures Projects - Caesars Cipher even though it works fine in my IDE (visual studio code).
to reproduce: 
go to: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/caesars-cipher
fill in this:
function rot13(str) { // LBH QVQ VG!
    var decoded = "";
  for(let x = 0; x < str.length; x++){
      var letter = str[x];
      if(!letter.match(/[A-Z]/)){
      } else {
          var charcode = letter.charCodeAt(0);
          letter = String.fromCharCode(((charcode - 65 + 13) % 26) + 65);
          
      }
      decoded += letter;
  }
  console.log(decoded);
}

// Change the inputs below to test
rot13("SERR PBQR PNZC");
(which I think is right)
and click on run tests

#### Add a Link to the page with the problem
 https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/caesars-cipher

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66.0.3359.181
* Operating System: MacOs

**Comment by JMVL64** [comment]
never mind! my bad! forgot the console.log. Although it is weird that this does not show up in the terminal inside FreeCodeCamp. Sorry!

**Comment by moT01** [comment]
@JMVL64 you should close this issue if it's no longer a problem

**Comment by JMVL64** [comment]
Yes, no longer a problem. Had some busy times and forgot to close it.
