### ISSUE TITLE
View The Curriculum

### ISSUE THREAD

**Issue by tondemut** [freeCodeCamp/freeCodeCamp#17288]
Clicking the view the curriculum button leads to a blank webpage. Refreshing the page makes the button work, only once though.

**Comment by karlchvojka** [comment]
Found this as well.

**Comment by mrwanashraf** [comment]
same here

**Comment by JustFly12** [comment]
duplicates https://github.com/freeCodeCamp/freeCodeCamp/issues/17283

**Comment by mattszcz** [comment]
duplicate #17309

**Comment by ahmadabdolsaheb** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #17309, so I am closing it as a duplicate.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding
