### ISSUE TITLE
'var' is missing in Basic JavaScript - Manipulate Arrays With shift()

### ISSUE THREAD

**Issue by JustFly12** [freeCodeCamp/freeCodeCamp#17287]
#### Describe your problem and - if possible - how to reproduce it
go to Basic JavaScript - Manipulate Arrays With shift()
`// Example
var ourArray = ["Stimpson", "J", ["cat"]];
removedFromOurArray = ourArray.shift();`
 removedFromOurArray - misses a declaration.
#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by JustFly12** [comment]
@johnkennedy9147 no as far as I can see on production, it is not fixed there.
If a regular user runs the code, he can be confused by `removedFromOurArray is not defined`

**Comment by VoodooChum** [comment]
I had the same issue when I reached this lesson 2 days ago and fixed line 3 by adding var in front of removedFromOurArray.  I didn't want to modify code above the line however, the test would not pass otherwise.

**Comment by johnkennedy9147** [comment]
Fixed in #17239
