### ISSUE TITLE
SASS course 'While loop' challenge auto-update crashes browser

### ISSUE THREAD

**Issue by ronmaple** [freeCodeCamp/freeCodeCamp#17291]
First time reporting an issue, and it doesn't seem to be brought up yet, if it was then I apologize.

#### Describe your problem and - if possible - how to reproduce it

New SASS course on FCC - 'Apply A Style Until a Condition is Met With While' - 
The auto-update feature on the editor executed the while loop as I typed, thereby crashing the window. 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while
#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 66.0.3359.181
* Operating System: macOS Sierra 10.12.6

#### If possible, add a screenshot here
<img width="378" alt="screen shot 2018-05-30 at 1 10 29 pm" src="https://user-images.githubusercontent.com/31875601/40744928-e9bc19c4-640a-11e8-957a-29e44a5bb696.png">

**Comment by mattszcz** [comment]
Confirmed infinite loop on ChromeOS.
Makes tab unresponsive. Have to refresh page.

**Comment by Nei-V** [comment]
One solution I found is not to close the final   "  } "  after the sass code until you write the iterator condition.
It still doesn't pass the test but at least it doesn't crash the browser tab.

**Comment by jmatty16** [comment]
Experienced same issue in Chrome. I had to add the @while last to my code to avoid it crashing before I could increment x.

**Comment by vuongggggg** [comment]
Crash on Chrome 68.x when typing.
But if I copying the code from example to the practice editor and edit, it will not be crashed.

**Comment by JohnnyBizzel** [comment]
This will always crash as the code is automatically evaluated. The instructions should be changed to be more specific. Maybe the challenge should be simpler so the while loop is already part written.

**Comment by bentom03** [comment]
Try writing the code in notepad and copy paste it in the editor. It worked for me that way.

**Comment by Ishaan0704** [comment]
Just finished the "while" loop challenge after a lot of timeoutss..
you can simply undestand the code mentioned below and just try writing "while" after your entire code is written.. 
worked for me that way.


// Setup
var myArray = [];

// Only change code below this line.
 var i = 5;
while(i > -1) {
   myArray.push(i);
   i--;
}
