### ISSUE TITLE
Heatmap does not display current month

### ISSUE THREAD

**Issue by JustFly12** [freeCodeCamp/freeCodeCamp#17296]
#### Describe your problem and - if possible - how to reproduce it
Not sure what is the specification on how many montth should be visible in the heatmap, 
BUT current month is not there.
You can see in the screenshot, that the 6-days streak i made thru the last 6 days in May'18 is not visible

#### Tell us about your browser and operating system

* Browser Name: chrome
* Browser Version: 66
* Operating System: macos

#### If possible, add a screenshot here
<img width="944" alt="screenshot 2018-05-30 21 46 31" src="https://user-images.githubusercontent.com/3913802/40746019-6d48302c-6459-11e8-8d7d-51c28eb341e3.png">

**Comment by jonathan-grah** [comment]
@johnkennedy9147, agreed. Thank you for reporting @JustFly12 👍
