### ISSUE TITLE
Testing with Chai challenges are 404'ing

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17298]
Here's what the page looks like: https://learn.freecodecamp.org/information-security-and-quality-assurance/quality-assurance-and-testing-with-chai

When you try to expand it on the curriculum map, it crashes and doesn't let you see the challenges inside of it.

Thanks to @LeDragon for reporting this!

**Comment by Ledragon** [comment]
You're welcome I guess, but I have no recollection of reporting this :p

**Comment by QuincyLarson** [comment]
@Ledragon I think you reported it through email and I created the issue for it.

**Comment by Ledragon** [comment]
ooh I think it was twitter. Anyway, you're welcome
And it works now :-)

**Comment by shehbazjafri** [comment]
Sorry for being so late. I just thought I should let you know. I reported the issue. It was on FCC Forum and I didn't have the same name for both Github and Forum accounts. I have fixed that now, but I wasn't able to delete the leDragon account. 😅
@Ledragon

**Comment by Ledragon** [comment]
:D okay, this explaining that...
