### ISSUE TITLE
Defunct links on 'Record Collection'

### ISSUE THREAD

**Issue by maxfettes** [freeCodeCamp/freeCodeCamp#17295]
The links in 'Record Collection' at [https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/record-collection] for accessing 'Manipulating Complex Objects' and 'Accessing Objects Properties with Variables' do not work.

I.E. 

[https://learn.freecodecamp.org/manipulating-complex-objects]
&
[https://learn.freecodecamp.org/accessing-objects-properties-with-variables]

need to be replaced with,

[https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/manipulating-complex-objects]
&
[https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/accessing-object-properties-with-variables]

respectively :)

**Comment by aditijoshi14** [comment]
Both of these broken links are fixed. Hence this issue can be closed.

**Comment by aditijoshi14** [comment]
Both of these broken links are fixed. You may close this issue.

**Comment by ezioda004** [comment]
@aditijoshi14 Thanks for the heads up!

Closing since the issue has been fixed in the master.
