### ISSUE TITLE
Introduction pages not shown as complete after viewing in curriculum list

### ISSUE THREAD

**Issue by thehomebrewnerd** [freeCodeCamp/freeCodeCamp#17294]
#### Describe your problem and - if possible - how to reproduce it
Curriculum doesn't show a completed check mark by Introduction pages. Have only tested this for Basic HTML and HTML5, Basic CSS, and Applied Visual Design, but all have the same problem.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66.0.3359.181
* Operating System: macOS 10.13.4

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/4307001/40745830-28e3209e-641e-11e8-992a-3ed74a5c2303.png)

**Comment by Roninii** [comment]
I am experiencing this as well. The completionist in me is going absolutely insane.

**Comment by mattszcz** [comment]
duplicate #17265

**Comment by moT01** [comment]
I closed the other one since it was a duplicate

**Comment by JosefSaltz** [comment]
Also experiencing this. I'm a user who uses a Github login from the legacy course-ware. Have registered email via the token code.

Browser Name: Firefox
Version: 60.0.1
OS: Windows 10 17134.48

**Comment by bronwynv** [comment]
Also experiencing this issue

**Comment by moT01** [comment]
@thehomebrewnerd I believe this has been fixed - you should check it out and close this issue if that's the case

**Comment by thehomebrewnerd** [comment]
Seems to be fine now with the new updates. Closing.
