### ISSUE TITLE
Vertical scrollbars don't fully scroll through their contents

### ISSUE THREAD

**Issue by Ashto10** [freeCodeCamp/freeCodeCamp#17293]
#### Description
In any of the curriculum challenges, the scrollbar attached
to the text editor does not fully scroll through its contents.
Instead, it appears to scroll the parent div container itself.

This issue is also prevalent on the output display as well. In
order to see it, you would need to shrink your browser's
window so that the text overflows.

[Link to one of the examples with this issue](https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-size-of-a-header-versus-a-paragraph-tag)

#### Browser information

* Browser Name: Firefox Quantum
* Browser Version: 59.0.3 (64-bit)
* Operating System: Windows 10 Pro

#### Screenshots

![image](https://user-images.githubusercontent.com/18147921/40745280-0649605a-6425-11e8-8e48-68692e76e7fd.png)
Scrollbar at the top of the div

![image](https://user-images.githubusercontent.com/18147921/40745299-160bd522-6425-11e8-8fe3-2c559c48ca78.png)
Scrollbar at the "bottom" of the div

![image](https://user-images.githubusercontent.com/18147921/40745315-20ea03ce-6425-11e8-803d-7edc8aa070d2.png)
The content that's been cut off

**Comment by C0nst4nt1ne85** [comment]
Same here. All challenges have the same issue you can only access the rest code with arrow keys no scrollbars.

I tried to fix it in my browser and div.reflex-element { overflow: visible } seems to work for me!

Chrome
Version 67.0.3396.62 (Official Build) (64-bit)
Windows 10

**Comment by huyenltnguyen** [comment]
@Ashto10 @C0nst4nt1ne85 Thank you for reporting the issue! I'll try to fix it asap.

In the meantime, you can scroll the editor by hover on it and scroll with the mouse wheel.

**Comment by huyenltnguyen** [comment]
I'm closing this issue as it has been resolved. Thank you for reporting and happy coding!
