### ISSUE TITLE
Issues with streak being offset

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17299]
![profile___freecodecamp](https://user-images.githubusercontent.com/985197/40749225-e422521c-6428-11e8-81ee-c55de55cf2f2.png)

**Comment by MarthaC444** [comment]
My calendar is showing the same months as well, all in 2017. None of the time from 2018 is showing up.

**Comment by lalov1** [comment]
I think it is showing from when I first started and doesn't have anything recent: 
https://www.freecodecamp.org/lalov1

**Comment by naviscript** [comment]
It is still not solved after such a long time?

**Comment by naviscript** [comment]
@lalov1 Hey, this is my profile link: https://www.freecodecamp.org/naviscript - I would really appreciate, if you could help me. I just don´t get, how to fix it. It does not even show my progress in the form of a list.
<img width="715" alt="screenshot 2018-10-17 at 21 19 06" src="https://user-images.githubusercontent.com/24709369/47113953-4f09e580-d252-11e8-8252-491e8c3596d7.png">

**Comment by lalov1** [comment]
@naviscript It looks like it's only showing the last month. When did you create your account?

**Comment by naviscript** [comment]
@lalov1 Sine 1 year, but this should be fine. I did reset it 2 days ago. Do you see the green dots when you look at my profile? I did today 8 tasks. Can you see this or does it also not show up?

**Comment by lalov1** [comment]
@naviscript I don't see any tasks completed. Are you sharing that information in your settings?

**Comment by RaspberryLime** [comment]
Not sure if my issue belongs here or in a separate one, but it seems related. Streak is correct, tasks show up when completed fine, but the calendar at the top shows the wrong months.

I'm on an iPad if that's relevant, latest iOS, using Safari.

![acbe1216-22dc-4959-b885-3c357097f97d](https://user-images.githubusercontent.com/25120737/47148907-ef4f2100-d2c9-11e8-8fbc-af6f2a4857e0.png)

**Comment by lalov1** [comment]
@RaspberryLime That seems like a break point issue. Have you checked it with other devices and is it portrait or landscape mode?

**Comment by RaspberryLime** [comment]
> @RaspberryLime That seems like a break point issue. Have you checked it with other devices and is it portrait or landscape mode?

It was in landscape mode. I don’t have a computer right now to check there. On my iPhone the page doesn’t adjust correctly in either landscape or portrait but I can get the graph to show. Would this be better as a separate issue?
![0f0ce626-0243-4dd4-b57e-82bbd7deb5a6](https://user-images.githubusercontent.com/25120737/47240214-97a2d980-d3df-11e8-8c45-6936137f8f4b.png)

**Comment by RaspberryLime** [comment]
> I even deleted my account, but nothing works. Sad, that no one from freecodecamp actually helps or fix that problem and just send you to this thread. It bothers me so much. However, I appreciate your help lalov1.

What is your new account? If they can't see the problem then it'll be much harder for it to be fixed.

**Comment by naviscript** [comment]
@RaspberryLime Hey, my account is public. However, I noticed that it finally shows up now. However, when I hover over the day, the date is showed on the left side (see the attached files). Is this normal? Btw. I have logged in with my GitHub account this time (if that matters). Thank you for your help! (My profile: https://www.freecodecamp.org/fcca465863b-f6bd-4f00-abe6-1dad4d356b00)
<img width="620" alt="screenshot 2018-10-24 at 02 31 51" src="https://user-images.githubusercontent.com/24709369/47400428-03b17480-d735-11e8-8680-33baf8a2cd0d.png">

**Comment by RaspberryLime** [comment]
> @RaspberryLime Hey, my account is public. However, I noticed that it finally shows up now. However, when I hover over the day, the date is showed on the left side (see the attached files). Is this normal? Btw. I have logged in with my GitHub account this time (if that matters). Thank you for your help! (My profile: https://www.freecodecamp.org/fcca465863b-f6bd-4f00-abe6-1dad4d356b00)

I can see your account at https://www.freecodecamp.org/naviscript now, and it appears the same for me as in your screenshots. I don't think the hover effect is normal to be placed on the left, but I don't know if that part should be logged as a new issue or whether it'll be tracked in here.

**Comment by naviscript** [comment]
@RaspberryLime I may just post the issue in the forum and maybe someone response to it. Thanks for your help.

**Comment by drecali** [comment]
Does anyone know which timezone is used by the streak counter and the heatmap? I just lost a 74 day streak even though I finished a challenge by 15:45PM KST (UTC +0900). The streak shows only 1 day but today's square on the heatmap is colored green, and on the timeline the challenge is recorded as being completed today as well. It seems like the streak counter is using one timezone, while the heatmap and timeline are using a second timezone. Can someone please confirm? It's really demoralizing as I was taking pride in watching the number grow every day and being able to share it with friends, family, and potential employers.

I understand that it may not be a high priority to fix, so at least knowing the rules of the streak would really help me understand and adjust my coding accordingly.

Screenshots: https://imgur.com/a/c47JNv9

Quoted from https://github.com/freeCodeCamp/freeCodeCamp/issues/7925#issuecomment-361716788
> I observed how challenges are recorded during the last week and basically saw challenge dates and streak are going by UTC and the heatmap is using EST...

**Comment by moT01** [comment]
Similar, but not the same as https://github.com/freeCodeCamp/freeCodeCamp/issues/17822 and https://github.com/freeCodeCamp/freeCodeCamp/issues/22031

**Comment by EliasOPrado** [comment]
my streaks don't appear at all.

**Comment by kiwisquash** [comment]
My current streak should be 63 according to the heatmap, but because of some time-zone funkiness, I have the longest streak of 32, and current streak of 1. Sad.

<img width="623" alt="Screen Shot 2019-06-06 at 11 40 58 PM" src="https://user-images.githubusercontent.com/34022735/59085792-9cf05e00-88b4-11e9-9b8c-dd62dfdca379.png">

**Comment by ianbattison** [comment]
![Screenshot](https://user-images.githubusercontent.com/16448470/59719181-b75efb80-9213-11e9-8026-f518c0da847f.png)
Can my current streak be corrected. Due to some time zone issue, it has reset my current streak. I have not missed a day since starting the 100 day challenge. I wanted to get to the end in one streak. As you can see, I have completed challenges every day since I started.
Thanks.

**Comment by RandalMorin** [comment]
I just ran into this same issue with my streak not showing AT ALL on my github profile. I would love to get some help with showing my streak as I'm on a roll! Thank you if you can help! 
![githubstreak](https://github.com/freeCodeCamp/freeCodeCamp/assets/153778927/64a8e659-6b6b-4b89-b7d5-99170f7da77c)
