### ISSUE TITLE
Certification section of portfolio should show legacy certifications, too

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17300]
![profile___freecodecamp](https://user-images.githubusercontent.com/985197/40749283-134c82a6-6429-11e8-88df-789a127c2cee.png)

**Comment by sanchitbansal10** [comment]
Working on it...

**Comment by JacksonBates** [comment]
Hey folks, if this is still up for grabs, I'll take a crack at it this week.

**Comment by jonathan-grah** [comment]
@JacksonBates, any update on this? If not, I can take a go at it

**Comment by thecodingaviator** [comment]
@QuincyLarson Any example profile where I can see this in action?

**Comment by scissorsneedfoodtoo** [comment]
@ahmadabdolsaheb, not sure, but your PR https://github.com/freeCodeCamp/freeCodeCamp/pull/35608 might also address this
