### ISSUE TITLE
Fix font weights on welcome page and settings

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17305]
![welcome__quincy_larson____freecodecamp](https://user-images.githubusercontent.com/985197/40750150-edb7e60e-642b-11e8-9a75-6126598b2c84.png)

![settings___freecodecamp](https://user-images.githubusercontent.com/985197/40750128-d94cea5c-642b-11e8-9c1f-083519cd86d2.png)

![settings___freecodecamp_](https://user-images.githubusercontent.com/985197/40750475-13cea8ae-642d-11e8-985a-a560079b2818.png)

![profile___freecodecamp_](https://user-images.githubusercontent.com/985197/40750517-330ce2d0-642d-11e8-9e5d-49d9edfcfa61.png)

**Comment by sunsplat** [comment]
I'd like to be assigned to this
