### ISSUE TITLE
View Curriculum rendering page blank

### ISSUE THREAD

**Issue by Halfcreative** [freeCodeCamp/freeCodeCamp#17309]
#### Describe your problem and - if possible - how to reproduce it
When jumping around the curriculum (to complete lessons or projects out of order) the "view curriculum" button occasionally renders the entire page blank, forcing the need for a page refresh.

Steps I take that can reproduce the error-
1. Click "View Curriculum"
2. Select a lesson or Project that is not yet complete
3. Complete lesson or Project
4. Move on to "next lesson" (sidenote: I wish this sent you to the next incomplete lesson)
5. While on the "next lesson" once again click "View Curriculum"
6. Voila

#### Add a Link to the page with the problem
No specific page that causes the issue. 

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: Chrome 67
* Operating System: Linux Mint 18.3

#### If possible, add a screenshot here
Would a screenshot of a white screen be that helpful?

**Comment by W8sconsin** [comment]
I also experience this.

**Comment by cj-sv** [comment]
I experience the same issue when selecting "View the Curriculum" just after finishing a challenge.  

* Firefox Nightly 62.0a1
* Ubuntu 18.04

**Comment by MarkKGit** [comment]
Upvoted. Also experience on Chrome Version 67.0.3396.62 (Official Build) (64-bit)

**Comment by petercr** [comment]
#### I have experienced **this** error myself on both on Windows 10 build: 17134.8 running 
#### Chrome version 67.0.3396.62 (_stable build_)

And on Ubuntu 16.04 LTS with 
Chrome version 67.0.3396.62

Here's a screen shot of the Dev Tools panels and the `errors` that it is returning.
![freecodecamp-errorlog](https://user-images.githubusercontent.com/26460352/40881594-a838a8ec-6698-11e8-912d-c56b9aa0106d.png)

The first error is a `TypeError: Cannot read property of 'id' of undefined` and the callback is to **line 69** of https://learn.freecodecamp.org/commons-005ae6459fd78eacb229.js

The second error looks to just be an expansion of the first, and the callback is again to **line 69** .

**Here are the error log files, hopefully that will be of some help :+1: :smile:** 
[learn.freecodecamp.org-1527981353474.log](https://github.com/freeCodeCamp/freeCodeCamp/files/2065484/learn.freecodecamp.org-1527981353474.log)
[learn.freecodecamp.org-1527981337090.log](https://github.com/freeCodeCamp/freeCodeCamp/files/2065485/learn.freecodecamp.org-1527981337090.log)

**Comment by petercr** [comment]
Also **both times** this happened to me it was after the first time I had registered the browser 
and signed into Free Code Camp for the first time.

**Did anyone else have a similar experience??:thinking:**

**Comment by rlords** [comment]
I have this issue as well. Doing the outlined above of refreshing the page fixes it.

    Browser Name: Mozilla Firefox
    Browser Version: 60.0.1
    Operating System: Windows 10 Pro

**Comment by petercr** [comment]
@rlords Yes it is easy to fix. But that doesn't mean we couldn't at least put in a `try{...} catch{...}` and show something on the screen that says 

> Oops, something went wrong. Please refresh page 

Or I guess in the event of the error we could just have the browser refresh itself

**Comment by moT01** [comment]
@Halfcreative I think this has been fixed - you should check it out and close this issue if it is

**Comment by Halfcreative** [comment]
@moT01 appears so, closing the issue.
