### ISSUE TITLE
Account not signed in to learn.freecodecamp.org after successful sign in from freecodecamp.org/signin using Github.

### ISSUE THREAD

**Issue by cj-sv** [freeCodeCamp/freeCodeCamp#17316]
#### Describe your problem and - if possible - how to reproduce it

Even after signing in the main freecodecamp page, I am not signed in when visiting learn.codecamp.org.

Steps used in signing:
1. Visit https://www.freecodecamp.org
2. Click Sign In (https://www.freecodecamp.org/signin)
3. Sign in through deprecated login using Github successfully.
4. Click Learn (https://learn.freecodecamp.org/) or Go to my next coding challenge.

Option to Sign In is still available on the upper right of the navigation bar after signing in.

#### Add a Link to the page with the problem

* https://www.freecodecamp.org
* https://learn.freecodecamp.org

#### Tell us about your browser and operating system

* Browser Name: Firefox Nightly
* Browser Version: 62.0a1
* Operating System: Ubuntu 18.04

#### If possible, add a screenshot here
![screenshot_2018-05-31 learn to code with free online courses programming projects and interview preparation for developer](https://user-images.githubusercontent.com/11567756/40760777-ea759398-64ca-11e8-9b5d-04b58d4df31f.png)
![screenshot_2018-05-31 welcome to learn freecodecamp](https://user-images.githubusercontent.com/11567756/40760778-eace6f72-64ca-11e8-946a-b3957433f752.png)

**Comment by Vikilator** [comment]
Steps:
1- Go to freecodecamp.org
2- Click Sign In at right upper corner button
2- Enter email to sign in or sign up
3- Click Enter
4- Ask for Code sent to email
5- Enter code
6- Message said to go back to freecodecamp to try again

When I try again decided to click the link to sign up with Github

1- Enter email from Github account
2- Enter User Name
3- Enter Password
4- Message said Username already in used
5- Enter email from freecodecamp account
6- Enter User Name
7- Enter Password

This got me in but it still show the sign in button at the right upper corner instead of the profile photo.
At the lesson screen it doesn't show like it used to be with the black background and colored text. Instead it shows like this:
![basic javascript - shopping list freecodecamp org_jav](https://user-images.githubusercontent.com/25875377/40763085-6a46e64e-6471-11e8-8b45-6f7cba4715f3.png)
This is using Chromebook OS 65.0

If I do the same thing on Windows Vista Home Edition using Opera Browser 36.0 it only loads the freecodecamp navigation bar and then disappears leaving the screen in blank.

**Comment by vikramnr** [comment]
Sign in'ed via account email and its working but not via Github

**Comment by cj-sv** [comment]
Just tried signing in though email and it now works, albeit the page doesn't refresh and remove the sign in button unless I click "Explore the curriculum". (Could be my cache tho)

I didn't use the email method at first since I kept on getting an error, turns out uBlock Origin was blocking something.

All in all:
* Email sign in works.
* Github sign in doesn't.

**Comment by Shuin-San** [comment]
+1 to this problem as OP

github login returns an error with message "New accounts can only be created using an email address."
email login returns a fresh account without progress

my account is [https://www.freecodecamp.org/portfolio/shuin-san](https://www.freecodecamp.org/portfolio/shuin-san)

**Comment by emdashv** [comment]
Experiencing same issue as OP. I am logging in with GH and am unable to see my previous progress.

**Comment by Banditek85** [comment]
Same here, Github login shows Welcome screen and I can acces my settings, but when clicking on "Go to the coding curriculum" the yellow sign-in button is again visible and apparently I am not signed in anymore as my previous progress is not visible.

**Comment by jeremybbauer** [comment]
Thanks for posting, @cj-sv . I'm having the same issue.

**Comment by Vikilator** [comment]
Yesterday, at least let me Run the test button. Today it doesn't do anything.

**Comment by planetofcode** [comment]
I can't able to sign in with GitHub and all my progress was lost.

**Comment by dudeguykid** [comment]
Historically i logged in with Github and saw the message that it will be going away. So I tried logging in with my email and some of my personal info is still in the profile but none of my progress in the curriculum is there anymore. any help is appreciated.

**Comment by huyenltnguyen** [comment]
If anyone here still having problem with signing in, please try the following steps:
- Sign in via https://www.freecodecamp.org/deprecated-signin
- It will take you to www.freecodecamp.org. Click the Curriculum button on the upper right, click on the yellow Sign in button, type in your email address. A code will be sent to your inbox, submit it and you're in. You should see your progress on the curriculum now.

If you're logged in to the curriculum page, but still don't see your progress, please send an email to team@freecodecamp.org with info of your github account and your email address.

In the case that the completed challenges set to 0 and your username (on the Settings page) is a weird string, then you have accidentally created a new account. Please also send an email to team@freecodecamp.org with your accounts info so the data can be merged.

**Comment by dudeguykid** [comment]
worked, thanks!

**Comment by mchoeti** [comment]
Hoi, on my side this is not working. 
1.) typed my email in
2.) entered the one time code
3.) Error : Oops! Something went wrong. Please try again in a moment.

Anyone else?
cheers

**Comment by geniusmousa** [comment]
> Hoi, on my side this is not working.
> 1.) typed my email in
> 2.) entered the one time code
> 3.) Error : Oops! Something went wrong. Please try again in a moment.
> 
> Anyone else?
> cheers

I have the same problem
