### ISSUE TITLE
Broken Project Link

### ISSUE THREAD

**Issue by aljf** [freeCodeCamp/freeCodeCamp#17312]
#### Describe your problem and - if possible - how to reproduce it
The tic tac toe game is listed as a requirement for the legacy front end development certification but the think for it is 404. 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-take-home-projects/build-a-tic-tac-toe-game

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.62
* Operating System: Windows 10 (64-bit)

#### If possible, add a screenshot here
![fccttterror](https://user-images.githubusercontent.com/38641143/40756008-a6f4827a-6446-11e8-8c02-ff5c12a3edb5.PNG)

**Comment by jonathan-grah** [comment]
@aljf, you are correct, this needs sorted out! I'm gonna merge this with https://github.com/freeCodeCamp/freeCodeCamp/issues/17304 as it was already opened and is part of the broader issue. Thank you for reporting 😄
