### ISSUE TITLE
Incorrect "result is not defined" error

### ISSUE THREAD

**Issue by theChepito** [freeCodeCamp/freeCodeCamp#17310]
#### Describe your problem and - if possible - how to reproduce it
When attempting to complete the lesson "Regular Expressions - Using the Test Method", I get the error "result is not defined" when submitting the following code:

`let myString = "Hello, World!";`
`let myRegex = /Hello/;`

`myRegex.test(myString);`

When i use this code in the Chrome console it evaluates to `true`.  

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/using-the-test-method

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66.0.3359.181 (Official Build) (64-bit)
* Operating System: macOS High Sierra v10.13

#### If possible, add a screenshot here

![region capture 13](https://user-images.githubusercontent.com/7246519/40752903-7aa4b048-6426-11e8-95c4-5e8b4837b183.png)
![region capture 15](https://user-images.githubusercontent.com/7246519/40753007-f5c350c2-6426-11e8-9634-2ed0e76d5e3d.png)

**Comment by johnkennedy9147** [comment]
@theChepito for the tests to pass the variable `result` has to have the expected value, you've removed it from the code completely

**Comment by theChepito** [comment]
got it.  once i included `let result=` it passed.
