### ISSUE TITLE
After complete a waypoint It wont go to the next challenge and It gives you 2 score points

### ISSUE THREAD

**Issue by FabioSeves** [FreeCodeCamp/FreeCodeCamp#1731]
Challenge http://beta.freecodecamp.com/challenges/waypoint-declare-string-variables has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
This issue is stale, @FabioSeves can you still replicate it?

**Comment by BerkeleyTrue** [comment]
fixed
