### ISSUE TITLE
Duplicate "id" and "for" form fields attributes (settings page)

### ISSUE THREAD

**Issue by guryanov-a** [freeCodeCamp/freeCodeCamp#17318]
#### Describe your problem and - if possible - how to reproduce it
Some form fileds have duplicate "id" attributes and corresponding `label` elements have duplicate "for" attributes, e. g. :
On `/settings` page "Build A Pomodoro Clock" fields in "Legacy Front End Projects" and "Front End Libraries Projects" sections have the same ids (`build-a-pomodoro-clock`) and corresponding labels have the same for attributes (`build-a-pomodoro-clock`).
So, when you click on label "Build A Pomodoro Clock" in "Legacy Front End Projects" section, field with the same id in "Front End Libraries Projects" becomes active.

#### Add a Link to the page with the problem
https://www.freecodecamp.org/settings

#### If possible, add a screenshot here
![settings freecodecamp 1](https://user-images.githubusercontent.com/12662274/40763770-e8a580f8-64c7-11e8-8d81-5b3817070a2c.png)
![settings freecodecamp](https://user-images.githubusercontent.com/12662274/40763771-e8da8dfc-64c7-11e8-9485-f1f009b7d614.png)

**Comment by valishah** [comment]
If this is still open i would like to take and fix.

**Comment by nathanhannig** [comment]
I took a look and here are my findings. We, of course, know the main issue is that the Labels are not completely unique.

Label's `for` and Input's `id` are set in the <FormFields> component (.\common\app\routes\Settings\formHelpers\FormFields.jsx)

They get their value from the prop `fields` object and iterate over its keys to get the `name` property and create a field for each key. Legacy projects have the same name for projects, and their `fields` object looks almost the same. Except, there is one key on the fields object which is unique called `id`.

My two suggestions are to either:
Append the `id` key's `initialValue` property to each `name`. Concerns are that using the initialValue property seems ambiguous.
Pass down the `id` prop used in the `<Forms>` component to `<FormFields>` and append it to each `name`.

Other concerns: Does change the Input's `id` attribute mess around with and loading or saving of values to the database.

**Comment by nathanhannig** [comment]
It also appears that if you update the URL of a legacy or modern project, it will update the URL in both input fields. I don't know if this is expected behavior or a bug? 

Are legacy and modern project of the same name considered the same or different? (I assume differently and should not be correlated)

However, any changes could cause an impact to existing user data. It is important to see how this data is being saved  behind the scenes and filling the app. I will see if I can study this.

**Comment by johnkennedy9147** [comment]
@nathanhannig yes, exactly.  Some projects from legacy are also used in the new curriculum so a submission to them count for the legacy certificate also, likewise if someone submitted a project for legacy they do not need to redo it for it to be eligible for the new certificates.  Any changes made to remove duplication of ids and for fields should not break this linkage.

Option 2 is what I would do but prepend to create unique ids in form `formID_projectName`

**Comment by nathanhannig** [comment]
thanks for the feedback, I agree and will implement this way
