### ISSUE TITLE
Simplified Learn UI

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17313]
Based on talking with a dozens of campers today, I think we should make our UI much simpler. Basically, the way it was before.

Instead of having a curriculum modal, just the root page (learn.freecodecamp.org) be the curriculum view:

![welcome_to_learn_freecodecamp_](https://user-images.githubusercontent.com/985197/40757066-53503410-644c-11e8-8f5a-c80ac10cc192.png)

I carefully rewrote the text to make everything as obvious as possible:

- These are certification tracks, and they each take about 300 hours
- You earn the certification by completing the final 5 projects
- Beginners should start at the beginning (with link to the first challenge)

By expanding the first certification - and its first topic - by default, campers can immediately get a sense of how the accordion works and see some of their progress. This is a big deal because many people are having trouble getting to the accordion, and thus assume their progress has been lost.

Second, here's what I think the challenge UI should look like (non-HTML challenges would simply omit the right-hand 1/3rd panel): 

![basic_html_and_html5_-_headline_with_the_h2_element___learn_freecodecamp](https://user-images.githubusercontent.com/985197/40756975-c7ed7392-644b-11e8-806f-10106d2b86d6.png)

On production we had a symbol for tests that hadn't yet been run. That way people didn't see big scary red X's until they ran the tests. I think we should add those back in for unrun tests.

**Comment by huyenltnguyen** [comment]
Hi @QuincyLarson, is it ok if we break this issue up into smaller ones? I'd like to help Bouncey out, but can only do task by task.
I've made a to-do list from your post:
## On the index page:
- [ ] 1. Add these lines:
```
If you're new to coding, we recommend starting [at the beginning](link to the first challenge).
You can earn each certificate by completing its 5 final projects.
```
- [ ] 2. Add the full curriculum, with the estimated time to complete (`300 hours`) next to each track. Expand the first track by default.
## On the navbar:
- [ ] 1. Change `Learn` button to `Curriculum`. The button should open `learn.freecodecamp.org` in a new tab.
## On the challenge page:
- [ ] 1. Add the following buttons to the bottom of the challenge description pane: `Run tests`, `Get a hint`, `Ask for help on the forum`, `Reset your code`
- [ ] 2. Remove the tool panel
- [ ] 3. The preview pane should be wider
- [ ] 4. Move the test suite to the challenge description page, below the buttons. Don't show the pass/fail icons when the tests haven't yet run

**Comment by huyenltnguyen** [comment]
@QuincyLarson My internet connection is super slooow right now, so I haven't been able to sign in to the new fcc. Please ignore this if I'm wrong about the UI/UX flow. But if I may throw in my 2 cents, I agree with all the changes, except the navbar one.

Looking at your first screenshot, I can see you're on the `learn` index page. I think it's unneccessary to open this very page in another tab when click `Curriculum`. And when on a challenge page, I'd say it's going to be annoying if I everytime I check the map, I get sent to the index page on a new tab.

Many campers would like to 'have the Map back', as in they would like to quickly access the map by clicking that button on the top right corner, which opens the curriculum modal. I totally agree with them, as it has been in my muscle memory for so long.

**Comment by Twaha-Rahman** [comment]
@huyenltnguyen I agree with you. I would like to see map back, as I found that really handy!

**Comment by johnkennedy9147** [comment]
I agree with @huyenltnguyen  and @Twaha-Rahman Curriculum as a modal or drop down menu works better.

Agree with everything else you suggested for the challenge pages.

Having the curriculum on the learn homepage makes sense, as does it being expanded by default - but I'd suggest if camper has already started it should expand to show their current place in the curriculum.

**Comment by bauhouse** [comment]
The challenges pages used to be usable on mobile devices. Now these pages are not properly optimized for small screens.

![img_3020](https://user-images.githubusercontent.com/42321/40788380-c6ae6276-64a4-11e8-8dc0-67c7acfb68e3.jpg)
![img_3021](https://user-images.githubusercontent.com/42321/40788382-c6c6e940-64a4-11e8-9a21-d1af03d04478.jpg)

- iPhone 6 Plus Model MG9Q2CL/A
- iOS 11.4
- Chrome Version 66.0.3359.122
