### ISSUE TITLE
UI mistake in dark mode

### ISSUE THREAD

**Issue by Twaha-Rahman** [freeCodeCamp/freeCodeCamp#17324]
When I change my theme to dark mode in settings and save my settings it gives me a confirmation in the top of the page , in which the color of the paragraph is black which is really hard to see and I guess it is mistake.

https://www.freecodecamp.org/settings

* Browser Name: Google Chrome
* Browser Version: 66.0.3359.181
* Operating System: Windows 10 (Version 1803 and Build 17134.1)

![screenshot 8](https://user-images.githubusercontent.com/39026437/40772044-c48b44c8-64e0-11e8-8cc5-44801562cb08.png)

**Comment by johnkennedy9147** [comment]
related to #17276

**Comment by jonathan-grah** [comment]
Hey @Twaha-Rahman, thanks for reporting this. I'm gonna close this as #17276 will resolve this issue additionally as far as I'm aware.
