### ISSUE TITLE
Heat map shows only the first 8 months on freeCodeCamp (public portfolio page)

### ISSUE THREAD

**Issue by guryanov-a** [freeCodeCamp/freeCodeCamp#17320]
#### Describe your problem and - if possible - how to reproduce it
When you look at the heat map on the `/portfolio/*` pages, it shows only the first 8 months on freeCodeCamp

#### Add a Link to the page with the problem
https://www.freecodecamp.org/portfolio/guryanov-a

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 66.0.3359.181 (Official Build) (64-bit)
* Operating System: macOS High Sierra Version 10.13.4

#### If possible, add a screenshot here
![heat map shows only the first year on freecodecamp](https://user-images.githubusercontent.com/12662274/40766790-7af0ba68-64d2-11e8-9c41-898dfc653e0e.png)

**Comment by MarthaC444** [comment]
Same here. The days of the months are also reading top to bottom, left to right, instead of left to right, top to bottom.

Ubuntu 16.04
Chromium, Firfox, Opera

https://www.freecodecamp.org/marthac444

![heatmap from 2018-06-01 11-04-21](https://user-images.githubusercontent.com/25692095/41327169-ace68c9e-6e98-11e8-9ea3-b7650f286984.png)

**Comment by Wojonatior** [comment]
What would be the preferred behavior here? The last 8 months of activity? 

I should be able to handle this. I just may need some help with how to generate some user test data so I can actually verify the behavior.

**Comment by guryanov-a** [comment]
@Wojonatior I think that showing the last 8 months would be great. Sorry, but I don't know anything about how to generate the test data.

**Comment by MarthaC444** [comment]
Googled "how to generate test data". 

Perhaps a good result:
[]( https://www.rankred.com/test-data-generation-tools/)

The first listed:
[](http://generatedata.com/)

Anything there help?

**Comment by Wojonatior** [comment]
@raisedadead Can you provide me some guidance as to defining this issue and how to generate some of this data for testing?

**Comment by Atita** [comment]
I have the same issue on my account I'm stuck in April even though  I was solving problems continuously until today.

![image](https://user-images.githubusercontent.com/2093920/42119436-5e156e80-7c14-11e8-9881-36070ca26614.png)

**Comment by greekmido** [comment]
i have the same problem on my portfolio page
https://www.freecodecamp.org/greekmido 
it only shows jan 2018 as the last month
im on win10 pro 64X
crhome Version 68.0.3440.84 (Official Build) (64-bit)
![issue](https://user-images.githubusercontent.com/29352863/43764746-f8ba122a-9a36-11e8-91d3-c5db9b5b4ff8.jpg)
