### ISSUE TITLE
Quotes before angle brackets

### ISSUE THREAD

**Issue by iskmar** [freeCodeCamp/freeCodeCamp#17326]
#### Describe your problem and - if possible - how to reproduce it
Using quotes just before angle brackets, will not give you double quotes as it does if there is space in between.
img src="" alt="> -notice there is no space between " and > and therefore only one quote mark;
img src="" alt="" > -if used with space. 

I know it's not a big deal but having used to it on my code editor, it does feels wierd and tedious to work around.

#### Add a Link to the page with the problem
Simplest one to test:
https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/add-a-text-alternative-to-images-for-visually-impaired-accessibility

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 60.0.1 (64-bit)
* Operating System: Linux Manjaro 17.1.1

**Comment by Twaha-Rahman** [comment]
It would have been helpful if you added a screenshot

**Comment by johnkennedy9147** [comment]
@iskmar  is this what you mean - if the cursor position does not have whitespace either side, or is immediately after a closed double quotes with whitespace after, then when opening double quotes the closing double quote is not automatically inserted into the code editor. 

I don't believe this is an issue, its the same in VS Code.

**Comment by texas2010** [comment]
Sorry, I have to close this. since this doesn't have a bug. it seems it related to the editor. more like it is a normal editor.
