### ISSUE TITLE
Tests for adding properties in package.json failing

### ISSUE THREAD

**Issue by raditotev** [freeCodeCamp/freeCodeCamp#17323]
In module Apis And Microservices > Managing Packages with Npm, tests failing although providing link to seemingly valid Glitch package.json with the required changes.

What I do:
1. Adding the required property in the package.json and copy the url:
![image](https://user-images.githubusercontent.com/5617443/40770924-e7a20b7c-64b3-11e8-9763-04f3f82b3541.png)

2. Paste url and submit. Test fails because of unexpected token and there is a warning in the console:
![image](https://user-images.githubusercontent.com/5617443/40773332-79fefa74-64ba-11e8-8c12-442a4b8f491a.png)

Tests are also failing for the following related lessons:
[Add a Description to Your package.json](https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/add-a-description-to-your-package-json)
[Add Keywords to Your package.json](https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/add-keywords-to-your-package-json)
[Add a License to Your package.json](https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/add-a-license-to-your-package-json)
[Add a Version to Your package.json](https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/add-a-version-to-your-package-json)

Environment:
Windows 10
Chrome 66

**Comment by raditotev** [comment]
I found another issue raised during beta, related to this one that helped me submit my solutions. More information here #13095. In short, if you're using Glitch in order to complete the lessons, first make sure you open the Glitch project from the [link](https://glitch.com/#!/import/github/freeCodeCamp/boilerplate-npm) provided in **Introduction to the Managing Packages with npm Challenges**. Once you make the required changes click on **Show Live**  button (top right). Copy the link from the newly opened tab for the solution.

**Comment by arun9787** [comment]
anybody give the answer for this questions
