### ISSUE TITLE
Settings page not opening in firefox

### ISSUE THREAD

**Issue by aweoluwatobi** [freeCodeCamp/freeCodeCamp#17327]
I tried to open the settings page on firefox which i use but it was blank. Had to use chrome and it opened. Please look into this cross browser issue.
The link is https://www.freecodecamp.org/settings
I'm using Mozilla firefox version 48.0.2 and windows 7 OS.

![freecodecamp_issue](https://user-images.githubusercontent.com/20822384/40778030-3a6bb4e2-64bf-11e8-94e8-70e38a2c16a9.JPG)

**Comment by johnkennedy9147** [comment]
@aweoluwatobi that version of firefox is nearly two years old, can you try updating. I use firefox on win 7 and it is fine.

**Comment by aweoluwatobi** [comment]
Thanks. Would work on that
