### ISSUE TITLE
Revert back to the old look,Especially the certification and Map part.

### ISSUE THREAD

**Issue by binayak1998** [freeCodeCamp/freeCodeCamp#17329]
The MAP which used to be very simplified and straight forward is not there anymore.
Kindly bring it back or make it look like the previous version.
It's a kind request from us.

![screenshot 75](https://user-images.githubusercontent.com/28681938/40779962-7ff97fbe-64f4-11e8-9bf7-9194f1dfa796.png)

#### Tell us about your browser and operating system

* Browser Name: Chrome 
* Browser Version: Latest
* Operating System: Windows 10

**Comment by texas2010** [comment]
Sorry, we will not revert it back to the old freecodecamp site. We decided to improve the freecodecamp site.
