### ISSUE TITLE
Privacy settings public-private toggle buttons not workind

### ISSUE THREAD

**Issue by yashsartanpara** [freeCodeCamp/freeCodeCamp#17337]
#### Describe your problem and - if possible - how to reproduce it

Toggle buttons of public-private in privacy settings section of settings page not working.

#### Add a Link  to the page with the problem
https://www.freecodecamp.org/settings

#### Tell us about your browser and operating system

* Browser Name:  Chrome
* Browser Version:  66.0.3359.181
* Operating System: Windows 10

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/16891089/40791970-59542180-6516-11e8-8ae3-303241859398.png)

**Comment by mstellaluna** [comment]
@yashsartanpara Hello, I will be closing this issue as this is a duplicate issue. Please see https://github.com/freeCodeCamp/freeCodeCamp/issues/17349 for any updates concerning your inquiry. Thank you for reporting your issue. Happy Coding !
