### ISSUE TITLE
Receive `Oops! Something went wrong. Please try again later` message when using the verification code

### ISSUE THREAD

**Issue by fendermaniac** [freeCodeCamp/freeCodeCamp#17338]
#### Describe your problem and - if possible - how to reproduce it
When trying to login with the new verification code, I keep getting redirected back to the freecodecamp.org homepage with the message: `Oops! Something went wrong. Please try again later`.  

I have cleared my cache on my chrome browser, tried using the MS Edge browser and the issue replicates everytime.  

#### Add a Link to the page with the problem
https://auth.freecodecamp.org/login?state=sxZCmePxAEowpDWMVTDB2y2REJcZLmhX&client=aUDv9jVqTfxBRE1l60NA5Af7yTCGE4cy&protocol=oauth2&response_type=code&redirect_uri=http%3A%2F%2Fwww.freecodecamp.org%2Fauth%2Fauth0%2Fcallback&scope=openid%20email
https://www.freecodecamp.org/
#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Windows 10

#### If possible, add a screenshot here

<img width="935" alt="capture" src="https://user-images.githubusercontent.com/1470569/40793292-0b674976-64ca-11e8-9898-621fc9fdb486.PNG">

**Comment by dangialdini** [comment]
I too, have the same issue!

**Comment by wesgray76** [comment]
Same here. I used developer tools and discovered that I had a type error.

**Comment by wesgray76** [comment]
I think there might be a broken link or something. 
![image](https://user-images.githubusercontent.com/28853982/41658811-333773e8-745d-11e8-9b36-d01f3d903aa9.png)

**Comment by YetiJr** [comment]
<img width="1440" alt="screen shot 2018-07-30 at 4 53 56 pm" src="https://user-images.githubusercontent.com/25313240/43423451-78dbb9c2-941a-11e8-9017-9390e199d00a.png">
<img width="1440" alt="screen shot 2018-07-30 at 4 59 16 pm" src="https://user-images.githubusercontent.com/25313240/43423452-78f4c2a0-941a-11e8-8a52-fd05d2a51b87.png">

Also having the same issue. I read not to use Safari, but I've updated Chrome and still having issues.

**Comment by fendermaniac** [comment]
I was able to get it to work.  Can't seem to recreate the issue.
