### ISSUE TITLE
save current progress

### ISSUE THREAD

**Issue by wendy0402** [FreeCodeCamp/freecodecamp#1733]
Hi guys, freecodecamp is awesome. I learn a lot from it. 
However, it will be great if user can save its current progress of a particular task. Some accident might be happened and they need to code from scratch again. e.g. the computer crash and reboot by itself, or they stuck in a particular test, want to continue later then close the browser without knowing that it doesn't save your progress.

how about that?

**Comment by BerkeleyTrue** [comment]
Saving current text in a challenge? We already store you code in localStorage as you type. You will notice if you refresh your code is still there.

**Comment by wendy0402** [comment]
I tried it in `advanced algorithm scripting` with challenge: `Bonfire: Inventory Update
Difficulty`. I change several variable, try refresh it, then it back to default code again, not my code

**Comment by BerkeleyTrue** [comment]
@wendy0402 Which browser and OS are you using?

**Comment by BerkeleyTrue** [comment]
Apologies, didn't realize that didn't make out into production yet. We have this feature on beta. (rumor has beta will be released tonight, don't quote me on that...).
