### ISSUE TITLE
Not updating new progress after the website update

### ISSUE THREAD

**Issue by lucynaaleksandra** [freeCodeCamp/freeCodeCamp#17339]
#### Describe your problem and - if possible - how to reproduce it
I just completed a new section that was added on new FCC platform… but when I checked my profile, the new section I just completed didn’t save on my account and when I revisit this section it shows incomplete... 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 
* Operating System: 

#### If possible, add a screenshot here
<img width="1277" alt="screen shot 2018-05-31 at 12 12 59 pm" src="https://user-images.githubusercontent.com/30958921/40794068-22477be6-64cc-11e8-8ed5-30c9cfcddb70.png">

**Comment by Ruvalter** [comment]
Same with me

**Comment by raisedadead** [comment]
Does refreshing help? 

@Ruvalter can you help us with a screenshot and the challenge that you were trying to complete?

**Comment by Ruvalter** [comment]
@raisedadead I have tried refresh, hard reload, clean cash and hard reload. nothing works. There are a lot of errors in the console as well.

I can not complete any "introduction".

Right now I can not access my curriculum at all. When I click the link to go to my curriculum I get a blank page with lots of errors.

![image](https://user-images.githubusercontent.com/20053230/40797845-8427a3e4-64d7-11e8-8106-b272d45bbdb1.png)

**Comment by raisedadead** [comment]
Ok. We are on top of this. Thanks for reporting.

**Comment by delta-foxtrot** [comment]
Same problem as me :(

BUT! If you try to do some new lesson for example you click "Basic HTML and HTML5" and then "Start first lesson" it will open the last of the lessons (about body and head). 
Then you can do a CSS tasks. 
I think it's a layout problem :(

**Comment by delta-foxtrot** [comment]
SOLUTION:
You need to go to the exactly lesson which you need for example you need to choose "Headline with the h2 Element", solve it and check. Then you will see progress.
ISSUE:
It's not working for the first task :( (""Introduction to Basic HTML and HTML5").

**Comment by eatcodesforlife** [comment]
Just to add to this. While the progress checklist shows that you've already completed a certain challenge but when you click on a completed it doesn't show your solutions:

![image](https://user-images.githubusercontent.com/35595513/40839018-41d0c29e-65d3-11e8-9b9b-c987d4bbb4fc.png)

![image](https://user-images.githubusercontent.com/35595513/40839153-d2c5ebc6-65d3-11e8-9ad4-974343ebacb3.png)

**Comment by raisedadead** [comment]
@eatcodesforlife can you log a separate issue about this?

**Comment by raisedadead** [comment]
Resolved the original issue about the progress. Please report fresh issues if facing similar
