### ISSUE TITLE
Navigating through "View the curriculum" causes the program to refresh or make no action at all

### ISSUE THREAD

**Issue by vytautas-pilk** [freeCodeCamp/freeCodeCamp#17331]
#### Describe your problem and - if possible - how to reproduce it
On any lesson page, when pressing 'View the curriculum' and navigating it, the program refreshes the whole page and returns you to the intro page of that subsection (for example, applied visual design).

#### Add a Link to the page with the problem
It happens with every lesson page everytime.

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 60.0.1
* Operating System: Linux

#### If possible, add a screenshot here
1) Casually opening curriculum navigation
2) Immediately after pressing any subsection
3) After closing the navigation
![image](https://user-images.githubusercontent.com/28671817/40783573-8e732134-64eb-11e8-8e60-1a677efce96d.png)
![image](https://user-images.githubusercontent.com/28671817/40783654-cdc947f0-64eb-11e8-8a91-f1220db86cb4.png)
![image](https://user-images.githubusercontent.com/28671817/40783679-e41aa166-64eb-11e8-9ada-8213bc34a150.png)

**Comment by moT01** [comment]
@vytautas-pilk is this still an issue? I think it has been fixed - you should check and close this if it is no longer a problem
