### ISSUE TITLE
Trying to claim my certification

### ISSUE THREAD

**Issue by PABlond** [freeCodeCamp/freeCodeCamp#17336]
#### Describe your problem and - if possible - how to reproduce it
I have completed every of the 5 projects in the “Apis And Microservices” category. But when I try to claim my certificate, I can see : “it looks like you have not completed the necessary steps. Please complete the required challenges to claim the APIs and Microservices”.

#### Add a Link to the page with the problem
Account settings (APIs and Microservices Projects)

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version:  Version 67
* Operating System: W10

#### If possible, add a screenshot here

<img src="https://discourse-user-assets.s3.amazonaws.com/original/3X/d/f/df124b2276e2c8f39f20d8c80dd0a27cd40013af.png" />
<img src="https://discourse-user-assets.s3.amazonaws.com/original/3X/8/5/858dc150ae8f921b17a52e7f1d5af4b6574dd607.png" />

**Comment by PABlond** [comment]
I want to add that the second screenshot is not visible anymore ... 
<img src="http://res.cloudinary.com/pablond/image/upload/v1527846696/Sans_titre.png" />

**Comment by PABlond** [comment]
I saw that the problem was resolved for (everybody ?) but not for me ... Are you aware of that ? I still cannot see the certification part in the setting page.

**Comment by johnkennedy9147** [comment]
@PABlond see my response to your comment on #17389

**Comment by kevintd** [comment]
Hi, 
![screen shot 2018-06-09 at 2 09 07 am](https://user-images.githubusercontent.com/4203786/41171154-77be9a86-6b8a-11e8-9198-18acc6b9d93a.png)
![screen shot 2018-06-09 at 2 07 12 am](https://user-images.githubusercontent.com/4203786/41171155-77efa720-6b8a-11e8-920d-d96798af519d.png)

This issue also happened to me again. Are there any things what i have to do
