### ISSUE TITLE
The output box below the code editor currently only displays test results, not console statements or returned values

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17348]
![basic_javascript_-_subtract_one_number_from_another_with_javascript___learn_freecodecamp](https://user-images.githubusercontent.com/985197/40801086-b1d76d74-64d7-11e8-9b10-a6c46c88adec.png)

**Comment by mstellaluna** [comment]
Closing. Duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/17356
