### ISSUE TITLE
not recognizing closing audio tag in accessibility lesson

### ISSUE THREAD

**Issue by udidol** [freeCodeCamp/freeCodeCamp#17343]
#### Describe your problem and - if possible - how to reproduce it
In the lesson: Applied Accessibility - Improve Accessibility of Audio Content with the audio Element

When I completed the challenge properly (with a closing audio tag of course) and click run tests, I pass all of the tests but the site doesn't recognize the closing </audio> tag I put.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/improve-accessibility-of-audio-content-with-the-audio-element

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 66.0.3359.139 (64 Bit)
* Operating System: Windows 10 Home

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/36724484/40797147-d79d216a-650f-11e8-97d8-0e1bcc7104f5.png)

**Comment by jonathan-grah** [comment]
@udidol, thank you for reporting this. The tests all pass for me until I add an `id` attribute to the `audio` tag. This shouldn't affect the tests passing correctly.

**Comment by mstellaluna** [comment]
@udidol @jonathan-grah I just tried the challenge in both FF and Chrome and I am able to successfully pass the challenge. The challenge does not require you to enter an ID in the opening audio tag. The challenge passes without the ID entered from the example. Please verify your code and let us know.

**Comment by udidol** [comment]
I added a screenshot with my code.
You can see if you find a problem...

**Comment by mstellaluna** [comment]
@udidol  in your audio tags you had added the `id="meowClip`. This is part of the example. It is not required for the challenge

**Comment by jonathan-grah** [comment]
@mstellaluna, you are correct but it shouldn't stop the tests from passing.
thanks @hctpscl

**Comment by raisedadead** [comment]
@udidol Can you try again? 

Here is the pseudo code that I tried.

```html
<audio controls>
	<source src="..." type="audio/mpeg" />
</audio>
```

I remember this was fixed recently.

**Comment by raisedadead** [comment]
In any case, the `id` for the attribute should not be what is breaking or passing the test. Its not required to be added to the code. A PR is welcome though to strengthen this.

**Comment by udidol** [comment]
when I deleted the id attribute it worked.

**Comment by jonathan-grah** [comment]
@udidol, yeah that is correct.
The point is that whether or not there is an `id` attribute, the tests should still pass if the closing tag is present.
