### ISSUE TITLE
Add favicon to http://search.freecodecamp.org

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/freeCodeCamp#17347]
Add favicon to http://search.freecodecamp.org. Currently there is not one.
![image](https://user-images.githubusercontent.com/1513130/40799959-0b92e8fc-64dd-11e8-80ac-e4b44ced9531.png)

**Comment by Stevegolden12** [comment]
Mind if I try it?

**Comment by raisedadead** [comment]
The app is a [Gatsby](https://www.gatsbyjs.org/) based app https://github.com/freeCodeCamp/search-assets.

You should look at the `www` directory and see what we have done for the [guide](https://github.com/freeCodeCamp/guide) or the [learn](https://github.com/freeCodeCamp/learn) projects.

**Comment by raisedadead** [comment]
@beaucarnes I think that static background with the faded logo is also horrendous. Should we replace that with something else? Like maybe quotes as we do on the welcome page for main site?

**Comment by beaucarnes** [comment]
Yeah, I like the idea of quotes like the main page instead of the logo. 

@Stevegolden12 Try it! Also, if your up for it, try adding quotes like in the main page. You can use similar code.

**Comment by Nirajn2311** [comment]
What’s the progress of this issue?

**Comment by borisyordanov** [comment]
@beaucarnes i can give this a go but there's not a lot of documentation. How do you even run the app?

**Comment by edkahara** [comment]
I opened a pull request that addresses this issue [here](https://github.com/freeCodeCamp/search-assets/pull/9).

**Comment by suhailsinghbains** [comment]
Hi, I'll send a PR, I think I have the skills to close this issue.
Thanks

**Comment by thecodingaviator** [comment]
Since the search now has a favicon, I'm closing the issue
