### ISSUE TITLE
Loading indicator for any view that is updating

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#17344]
We need loading indication for components to reflect their hung or processing state:

- [ ] Sign in button -> Profile pic on Learn
- [ ] Challenge page coming from outside the app on Learn
- [ ] Bundle loading and not ready yet on slow networks.

**Comment by raisedadead** [comment]
These indicators should be able to justify the delay and result in lesser confusion on the actual state of the app.

Users are currently getting the false positive of not being signed in like so:
https://github.com/freeCodeCamp/freeCodeCamp/issues/17341

**Comment by ktajpuri** [comment]
Can I take this up if anyone else has not picked it up yet?

**Comment by raisedadead** [comment]
@ktajpuri yes please.

**Comment by raisedadead** [comment]
Please note that some of this like the profile pic indicator is already implemented, but feel free to improvise it, if need be.

**Comment by ktajpuri** [comment]
I am currently unable to signin to FCC local because of the oauth issue. Any idea when that will be fixed or we get a workaround?

**Comment by raisedadead** [comment]
> Any idea when that will be fixed or we get a workaround?

No Idea. Unless the core team is free from other pressing tasks, I am unfortunately unable to state an ETA. A PR is welcome though.

**Comment by mcelis13** [comment]
I would love to contribute to this issue if it is still unresolved.

**Comment by raisedadead** [comment]
This is now stale and parts of this have been fixed.
