### ISSUE TITLE
Make certificates more printable

### ISSUE THREAD

**Issue by mouri11** [freeCodeCamp/freeCodeCamp#17346]
#### Describe your problem and - if possible - how to reproduce it
I am not able to print my legacy certificate. I am trying to print it using Ctrl + P, and Print option in the right click dropdown menu. The pdf appears blank.

#### Add a Link to the page with the problem
Here is the link to my [certificate](https://www.freecodecamp.org/certification/mouri11/legacy-front-end).

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 66.0.3359.181
* Operating System: Windows 8.1 Single Language 64-bit

#### If possible, add a screenshot here
![screenshot 29](https://user-images.githubusercontent.com/17742382/40799476-504b8e7e-652b-11e8-8b6c-e956ff5e9b9d.png)
![screenshot 30](https://user-images.githubusercontent.com/17742382/40799477-5080ab9a-652b-11e8-84e0-5fdc34544f45.png)

**P.S.:** I am not sure if it is a bug or intended to be unprintable, but I found why I can't print it.
```
@media print {
  * {
    display: none !important;
  }
}
```
Thanks.

**Comment by QuincyLarson** [comment]
@mouri11 If you remove that JavaScript, are you able to print it? If so, how does it look?

**Comment by mstellaluna** [comment]
@QuincyLarson  I tried to print his certificate to see if it was a local issue or not. I am not having issues seeing a preview or a printer listed on my Win10 in either Edge or Firefox... but chrome gives me this. 
![image](https://user-images.githubusercontent.com/22984739/40813934-5fbf68b4-650b-11e8-9010-137204ff428c.png)

**Comment by jonathan-grah** [comment]
This is the same for me. As far as I'm aware, @QuincyLarson certificates were specifically not allowed to be printed and this was decided during the process. Do we want this to change?

**Comment by mouri11** [comment]
@QuincyLarson Hi. Removing the javascript messes up the layout of the document. The signature becomes huge, the date gets skewed, etc.

**Comment by mouri11** [comment]
I guess not being able to print would be fine, except if we have to carry hardcopies to interviews.

**Comment by huyenltnguyen** [comment]
How about taking a screenshot? :wink:

**Comment by mouri11** [comment]
![screenshot 31](https://user-images.githubusercontent.com/17742382/40824837-3cc5b740-6593-11e8-9f4d-3736c03e3b6f.png)

**Comment by huyenltnguyen** [comment]
@mouri11 Sorry, I meant taking a screenshot of the certificate, save it as png or something, then print that photo out. Firefox has the 'take a screenshot' feature built in, if you're not aware of.

**Comment by mouri11** [comment]
Oh right. Sorry to misinterpret it. I already took a fullscreen screenshot of the certificate. I had asked this to know if this blocking of printing is intended or just a bug. Thanks though.

**Comment by huyenltnguyen** [comment]
Oh cool! Glad you could find a way around it.

**Comment by QuincyLarson** [comment]
@jonathan-grah @huyenltnguyen I've changed the title of this issue to "make certificates more printable". I believe since they're just HTML and CSS, with a couple images, we should be able to make them reliably print. This has always been a very common request among campers, and it would be worth fixing for the new certificates :) Would either of you be interested in tackling this?

**Comment by jonathan-grah** [comment]
@QuincyLarson, sure, I can tackle this soon. This has been highly requested by campers.
If this needs to be done quickly, it might be better for @huyenltnguyen to give this a go, if they want, because I mightn't be able to get this done this week.

**Comment by huyenltnguyen** [comment]
@jonathan-grah I'll gladly take it from you :) Will try to submit a PR asap.

**Comment by QuincyLarson** [comment]
@jonathan-grah OK - thanks for being candid about your availability. 

@huyenltnguyen Awesome - thanks for your help with this. Please keep us posted and let us know if we can be of any help during the process :)
