### ISSUE TITLE
The "Explore the curriculum" button does nothing

### ISSUE THREAD

**Issue by udidol** [freeCodeCamp/freeCodeCamp#17345]
#### Describe your problem and - if possible - how to reproduce it
Clicking on "Explore the curriculum" in the main "Learn" page doesn't do anything.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66.0.3359.139 (Official Build) (64-bit)
* Operating System: Windows 10 Home

**Comment by nalinpuri** [comment]
My Browser Name--- Opera
Its 32-Bit
Same Problem

**Comment by moT01** [comment]
@udidol are you still having this problem? I think it has been fixed - if it's working you can close this issue

**Comment by udidol** [comment]
@moT01 

When I removed the `id=""` attribute it let me pass the lesson.
Isn't this still a bug since having an `id` attribute in the `<audio>` tag still prevents passing the lesson?

**Comment by moT01** [comment]
@udidol you are referencing an unrelated lesson in your last comment - this issue mentioned the `Explore the curriculum` button doing nothing - it should be fixed now as learn redirects directly to the curriculum - you should verify that it is working now and close this if it is

**Comment by udidol** [comment]
@moT01 You are right! I accidentally mixed this issue with a different one, apologies.

Yes, it seems to be fixed. Closing the issue.
