### ISSUE TITLE
Unable to login into profile

### ISSUE THREAD

**Issue by ELRuncho** [freeCodeCamp/freeCodeCamp#17340]
#### Describe your problem and - if possible - how to reproduce it
Hi, after the update I proceeded to login using my github account and the website requested to confirm my email which I did. after receiving the confirmation email it takes me to a welcome page aknowledging my name and profile information:

after I click on "go to the coding curriculum" it takes me to the curriculum but I'm not logged into my profile it still shows the sign in button on the top right 

#### Add a Link to the page with the problem
 this is the first website I get to https://www.freecodecamp.org/
and this is where it sends me after clicking on the go to button https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements

#### Tell us about your browser and operating system

* Browser Name: firefox
* Browser Version: 60.0.1
* Operating System:  Windows

#### If possible, add a screenshot here

![screenshot-2018-5-31 learn to code with free online courses programming projects and interview preparation for developer](https://user-images.githubusercontent.com/14805845/40795964-34a7c35c-64c9-11e8-9218-0b81a1d7ec53.png)

![screenshot-2018-5-31 https learn freecodecamp org](https://user-images.githubusercontent.com/14805845/40795967-3996d4a2-64c9-11e8-865e-ba22a679d73d.png)
-----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
UPDATE:

I tried login using firefox developer edition and it worked. seems that the issue is isolated to regular firefox, at least in my case

**Comment by raisedadead** [comment]
Yes this is known we are working on a fix. Meanwhile you can sign in once again using the email id that you just confirmed. That will get you signed in.

Sorry about the inconvenience.

**Comment by RiaClay** [comment]
I am having the same issue. Even after re-signing in. I still can't access the curriculum. It will just send me to a blank page with a yellow Sign-In button on the right. I was in the middle of working on a coding challenge when it happened.

**Comment by ELRuncho** [comment]
I tried login usinf firefox developer edition and it worked. seems that the issue is isolated to regular firefox, at least in my case

**Comment by eeglantine** [comment]
same here .. and even after siging in i still can't access the curriculum .. i was working when it happened

**Comment by aprioriO** [comment]
hi, 
the same problem is in my FreeCodeCamp acc.
I can sign in using GitHub, but  

"after I click on "go to the coding curriculum" it takes me to the curriculum but I'm not logged into my profile it still shows the sign in button on the top right"
So I  cannot see my progress and have to start from the beginning if I sign in using e-mail.
Browser Name: Google Chrome
Browser Version: Version 66.0.3359.181 (Official Build) (64-bit)
Operating System: macOS Sierra

**Comment by raisedadead** [comment]
Hi everyone we dropped in a new fix. You might have to actually sign in one more time to check this. But that would be it.

Once again sorry about the inconvenience and happy coding.

**Comment by iDada5** [comment]
Hi I've tried to sign in with github (as this is what I used previously ) but it won't let me log in at all that is the screen I get if i choose github : 
![image](https://user-images.githubusercontent.com/36464368/40839313-fe3bbf56-656f-11e8-8dc2-42410780d5cb.png)

Thanks
Browser Name: Google Chrome
Browser Version: Version 67.0.3396.62 
Operating System: Windows 10

**Comment by raisedadead** [comment]
Hi @iDada5 Can you connect with me via an email mrugesh at freecodecamp dot org, with issue that you are having?

**Comment by rosty11** [comment]
Free code camp wont let me log in at all using any browser, but I can log in on my phone without any problems.

**Comment by raisedadead** [comment]
Please connect with me via an email `mrugesh at freecodecamp dot org` for login issues. Be sure to include screenshots of your browser console:

On Windows:

Press <kbd>F12</kbd> and then switch to the Console Tab

On macOS:

Press <kbd>⌘</kbd>+<kbd>⌥</kbd>+<kbd>i</kbd> and then switch to the Console Tab

Other Systems:
Please lookup on google on how to open Browser Dev tools
