### ISSUE TITLE
It's possible for toggle buttons to both be active at once

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17349]
Steps to reproduce: rapidly click down the column of privacy toggle buttons. Some of them will strangely be active at the same time.

![image](https://user-images.githubusercontent.com/985197/40801160-db291cd6-64d7-11e8-8adb-56889fe684c1.png)

**Comment by mstellaluna** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/issues/17337 <- similar issue
