### ISSUE TITLE
View Curriculum Signs me out and presents a blank page.

### ISSUE THREAD

**Issue by KevinGodinho** [freeCodeCamp/freeCodeCamp#17341]
When I click view curriculum it sends me to a page that has the headings at the top of the screen but a blank page beneath it without the curriculum, then the upper right corner says sign in. When I push sign in, it takes me to view curriculum and the process repeats. Just before this happened I was doing one of the lessons and when I would submit my code it would say congrats and then I would click submit and go to next challenge and it would just reload the same challenge, then trying to go to view curriculum to manually choose the next challenge, view curriculum would not load, like above issue.

https://www.freecodecamp.org

https://www.freecodecamp.org/challenges/current-challenge

I am using Safari version 11.1
MacBook Pro 
MacOS High Sierra version 10.13.4.

![screen shot 2018-05-31 at 10 06 21 am](https://user-images.githubusercontent.com/39806291/40796549-4f6b67c0-64ba-11e8-9ac3-231c0802e3d7.png)

![screen shot 2018-05-31 at 10 07 47 am](https://user-images.githubusercontent.com/39806291/40796616-818782ca-64ba-11e8-866f-b132cf39ba4f.png)

**Comment by dstarrtrey** [comment]
Having the same issue on PC with Chrome

**Comment by winslow462** [comment]
same here, Chrome on Windows 7 pro

**Comment by raisedadead** [comment]
Hi guys can you please check your dev consoles and dump the screenshot, here.
On windows, you can hit <kbd>F12</kbd> to open the devtool, and then switch to the console tab.

**Comment by KevinGodinho** [comment]
Thanks for commenting guys, so I know I'm not alone lol. I sat down with a coffee and was fully ready to spend a few hours coding. Kind of a bummer. Once everything is up and running properly I think that their new layout is going to be awesome.

**Comment by Bkreps** [comment]
![error](https://user-images.githubusercontent.com/28685980/40797255-8a5c2e26-64d5-11e8-8cc9-e07f6b0d5d2f.png)

Using Chrome

**Comment by deepaklalwani97** [comment]
![image](https://user-images.githubusercontent.com/32839217/40797289-49057892-6525-11e8-855c-6e429cc8dd14.png)

**Comment by Bkreps** [comment]
Seems to be working now thank you.

**Comment by deepaklalwani97** [comment]
still having this problem in mac os using chrome

**Comment by winslow462** [comment]
![devcon](https://user-images.githubusercontent.com/3596704/40798271-365c31ea-64d0-11e8-84a3-54120163c0e8.PNG)

**Comment by winslow462** [comment]
hard refresh seems to have brought it back. terrific! so curious about what the issue was...maybe someday I will understand these things!

**Comment by akwong372** [comment]
Clearing the cached files in chrome appears to make the rest of the page load, but it still signs me out when I try to view the curriculum.

**Comment by AryanJ-NYC** [comment]
Clicking the freeCodeCamp brand icon on the top-left (on the navbar) continuously brings me back to a blank, even after a hard refresh.

![screen shot 2018-06-02 at 8 24 50 pm](https://user-images.githubusercontent.com/8263430/40882006-7b6bf85e-66a3-11e8-9d6f-41803faf9515.png)

**Comment by moT01** [comment]
@KevinGodinho if this is fixed now - you could probly close this issue
