### ISSUE TITLE
Unable to sign in with github

### ISSUE THREAD

**Issue by planetofcode** [freeCodeCamp/freeCodeCamp#17359]
#### Describe your problem and - if possible - how to reproduce it
1. Go to https://www.freecodecamp.org/deprecated-signin
2. Try to sign in with your GitHub account
3. You will be redirected to the homepage with the alert "New accounts can only be created using an email address."

#### Add a Link to the page with the problem
Signing in with github, https://www.freecodecamp.org/deprecated-signin
#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66.0.3359.181
* Operating System: Window

#### If possible, add a screenshot here
![sign in to freecodecamp using a deprecated login freecodecamp](https://user-images.githubusercontent.com/16446205/40822041-de2deb90-6587-11e8-990d-422159d93343.png)
![learn to code and help nonprofits freecodecamp](https://user-images.githubusercontent.com/16446205/40822045-e056ecaa-6587-11e8-8674-aef3797a002b.png)

**Comment by iDada5** [comment]
yep same here too

**Comment by raisedadead** [comment]
Did you create an account with GitHub login previously? If yes then can you share your details privately be emailing me (mrugesh@freecodecamp.org) and team@freecodecamp.org

**Comment by raisedadead** [comment]
You can login to your accounts with the email that you have on records:

1. Click the "sign in" button in the upper right hand corner on the navigation bar.
2. Enter your email.
3. Enter the sign in code you get in your email.
4. Click "Learn" in the navigation bar.

If you are unable to access your email inbox where you would receive the code, let us know by emailing our support account team@freecodecamp.org.

Happy coding!

**Comment by planetofcode** [comment]
you're telling the temporary solution but this issue haven't resolved yet.

**Comment by raisedadead** [comment]
> you're telling the temporary solution but this issue hasn't resolved yet.

Hi @planetofcode 

This is not a temporary solution. We have disabled new sign ups via GitHub completely to adhere to the privacy guidelines. 

So, the only way you can access your user account is by using the email that you have on records with us.

But If you DID create an account on freeCodeCamp via GitHub you can still sign in thru GitHub and update your email.

**Comment by planetofcode** [comment]
previously thousands of people used this Github sign in, now you ask them to mail you to set up the account, isn't it? @raisedadead

**Comment by raisedadead** [comment]
> now you ask them to mail you to set up the account, isn't it?

Nope. we do not. if YOU have an account with us that was created using GitHub then you can still use it to sign in.

**Comment by planetofcode** [comment]
Github sign in is not working at all. It is showing this error "New accounts can only be created using an email address." message. :)

**Comment by Shuin-San** [comment]
well... i understand the changes

but i still cant access my account when i use my email...

using my email logs me into a new account with 0 progress

how do i sign in to my old account -> this is my old account
https://www.freecodecamp.org/portfolio/shuin-san

when i use the new login method (email shuingr@gmail.com ) i get to a new
account with 0 progress.....

thanks


2018-06-02 10:30 GMT+02:00 mrugesh mohapatra <notifications@github.com>:

**Comment by Shuin-San** [comment]
hmm thats strange. my github was a different mail... now everything is
fine...


thanks !

Στις Σάβ, 2 Ιουν 2018, 14:25 ο χρήστης mrugesh mohapatra <
notifications@github.com> έγραψε:
