### ISSUE TITLE
Console not displaying return values

### ISSUE THREAD

**Issue by JamesStaffordCoyte** [freeCodeCamp/freeCodeCamp#17356]
#### Describe your problem and - if possible - how to reproduce it
The problem is with all algorithm problems. The test runs against all the test values but the console does not return the actual value you ask it to return. I like to test certain return values either by returning them or by console.log(); but with the recent update this doesn't seem to work at all so I have 0 idea what I might be returning. I'd rather see see what it does return, not what it should. I cannot debug.  This makes bugs/errors incredibly difficult to solve.

#### Add a Link to the page with the problem
All Algorithm Challenges

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66
* Operating System: MacOS

#### If possible, add a screenshot here
![screen shot 2018-05-31 at 3 44 55 pm](https://user-images.githubusercontent.com/26333632/40812252-af836778-64e9-11e8-9560-8b7350ad8da4.png)

**Comment by raisedadead** [comment]
Thanks for the report. As a work around while we fix this you can look at the DevTools console of your browser and still see the console.log statements?

![image](https://user-images.githubusercontent.com/1884376/40813004-525b75e6-6556-11e8-8ea7-46cffbe1caca.png)


That said we definitely need to pass the log back to the in app log area.

**Comment by JamesStaffordCoyte** [comment]
Thanks raisedadead. That's what I've been using. Just wanted to know if there were plans to fix this. Glad to here there is. Thanks again.

**Comment by florisvaneck** [comment]
Same problem here on latest MacOS release running Safari. Start state of console:

/**
* Your test output will go here.
*/

End state:

// running test
// tests completed

No in between messages. 

If I use console.log, it would be very helpful to actually see that output so I can actually debug (like similar to running JavaScript in Chrome Developer tools).

**Comment by Nirajn2311** [comment]
It is a feature that will be coming soon.

**Comment by raisedadead** [comment]
Issue moved to [freeCodeCamp/learn #189](https://github.com/freeCodeCamp/learn/issues/189) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Sauletekis** [comment]
Not sure if this is the right place to raise this, but it looks like this is happening again on *some* of the Algorithm Challenges (for example, Comparison with the Strict Equality Operator), but on others it is working as planned according to [fix(console): output user logs after running tests #296](https://github.com/freeCodeCamp/learn/pull/296).

I'm new to all this and don't really know how reporting things works, but this is making it hard to debug while I work through these exercises as written tests don't test things in a way I can see.

Oh, yeah - using Chrome.
