### ISSUE TITLE
Update readme for new certifications and curriculum 

### ISSUE THREAD

**Issue by sanchit0496** [freeCodeCamp/freeCodeCamp#17361]
#### Describe your problem and - if possible - how to reproduce it
The READ.md file displays information about the old curriculum and certification programs. It needs to be updated as per the current curriculum.

#### Add a Link to the page with the problem
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/README.md

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Operating System: Windows 10

#### If possible, add a screenshot here
![isfgh](https://user-images.githubusercontent.com/32457437/40824011-109dea28-6590-11e8-9920-fb80f8b5aed4.JPG)

**Comment by sanchit0496** [comment]
Although it's not related to the website, still I think this needs to be updated. 
I've made a pull request https://github.com/freeCodeCamp/freeCodeCamp/pull/17351

**Comment by moT01** [comment]
Thank you for reporting this issue.

    This appears to be fixed so I am closing this issue.

    If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
