### ISSUE TITLE
Responsive Design Certification can not be claimed

### ISSUE THREAD

**Issue by C0nst4nt1ne85** [freeCodeCamp/freeCodeCamp#17363]
I completed the projects for Responsive Design Cert and even edit the older ones, from Legacy, to complete the new goals. But when I claim my cert a message appears that says "it looks like you have not completed the necessary steps. Please complete the required challenges to claim the Responsive Web Design"

Is it because I can not find how to complete introductions???

https://www.freecodecamp.org/settings

* Browser Name: Chrome 
* Browser Version: Version 67.0.3396.62 (Official Build) (64-bit)
* Operating System: Windows 10

![image](https://user-images.githubusercontent.com/32928319/40831439-aebba528-6591-11e8-9fd4-10f15f448d9e.png)

**Comment by momitrahman** [comment]
This issue also happening for me i tried in different browser also. Only i can claim my Front End Libraries  certification.

**Comment by C0nst4nt1ne85** [comment]
I totally invested some time to recreate my older projects with all the new user stories, but this did not fix the problem. 
It still says that I have not completed the necessary steps. 

![claim](https://user-images.githubusercontent.com/32928319/40871471-ff0fda36-6644-11e8-9138-b75ce60ae405.png)
![tribute_page](https://user-images.githubusercontent.com/32928319/40871473-ff2f0b2c-6644-11e8-8b84-da6fcc68e9fd.PNG)
![survey](https://user-images.githubusercontent.com/32928319/40871474-ff503c70-6644-11e8-8db0-adda6eb71093.PNG)
![product](https://user-images.githubusercontent.com/32928319/40871475-ff6d3960-6644-11e8-908e-8838b6df40f2.PNG)
![technical](https://user-images.githubusercontent.com/32928319/40871476-ff8a8344-6644-11e8-9d28-878b916cb673.PNG)
![portfolio](https://user-images.githubusercontent.com/32928319/40871477-ffa82fac-6644-11e8-911e-bcfd96560825.PNG)

**Comment by johnkennedy9147** [comment]
@JMVL64 see issue #17278
