### ISSUE TITLE
Problem loading page, Unable to establish a secure connection : General region Pakistan

### ISSUE THREAD

**Issue by Ozarion** [freeCodeCamp/freeCodeCamp#17360]
#### Describe your problem and - if possible - how to reproduce it
For some reason, learn.freecodecamp.org is not accessible in my area on any of the internet browser. 
1. Firefox shows the message 'Secure Connection Failed'.
2. Chrome shows 'Surf safely'

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/

#### Tell us about your browser and operating system

* Browser Name: Firefox/Chrome
* Browser Version: both updated to latest version
* Operating System: Windows 10

#### If possible, add a screenshot here
https://ibb.co/goJ5ky

**Comment by wahaj-47** [comment]
For me the connection resets

**Comment by raisedadead** [comment]
Hi @Ozarion @wahaj-47 can you share the general region where you are located? (Do NOT be specific).

We do not do anything to block it in any region, so it could be down to an `ad blocker` if you are using it (we don't run any ads at all btw.) OR the ISP, country or region restrictions.

**Comment by Ozarion** [comment]
Thanks for replying @raisedadead My general region is Karachi, Pakistan if that helps, and I'm not using any sort of ad blocker or proxy. My ISP apparently only blocks major adult sites and nothing else. I hope this helps.

**Comment by raisedadead** [comment]
Ah.. @Ozarion thanks we have been getting reports of some issues of network issues with your general region.

Let me get back to you.

**Comment by Ozarion** [comment]
@raisedadead I see. Thank you.

**Comment by Ozarion** [comment]
The issue seems to be resolved now. I can access learn.freecodecamp.org now. Thank you

**Comment by raisedadead** [comment]
Oh.. okay great. Did you have to do anything specific to address this issue?

**Comment by raisedadead** [comment]
![img](https://user-images.githubusercontent.com/34722336/40880555-b85d5d92-66cc-11e8-89c0-782db20662cb.PNG)

![img](https://user-images.githubusercontent.com/34722336/40880556-b8903c94-66cc-11e8-90c2-6a67f01b9189.PNG)

**Comment by raisedadead** [comment]
![img](https://user-images.githubusercontent.com/9195137/40880515-e41a3e56-66cb-11e8-8234-394be79a4b7f.png)

**Comment by iamzakofficial** [comment]
@raisedadead yes my region is also Pakistan and it works on proxy only.

**Comment by wahaj-47** [comment]
Same region same issue

**Comment by Rashheh** [comment]
Also from Karachi, Pakistan.
The website was working fine till the 31st of May, 2018 but isn't working now.

**Comment by huyenltnguyen** [comment]
I recommend reaching out to your ISP, too.
I would also like to suggest using DNS as a workaround in the meantime. Either [OpenNIC's](https://www.opennic.org/) or [Cloudflare's](https://1.1.1.1/) could work. (I'm not affiliated with either of them, only suggested them because they claim they don't keep logs).

**Comment by raisedadead** [comment]
Hi @Ozarion @wahaj-47 @iamzakofficial @Rashheh 

Can you guys check if the same issue persists with https://guide.freecodecamp.org/ ?? Its also hosted on netlify and if it is the case as well, then we should be able to isolate the issue.

**Comment by Rashheh** [comment]
@raisedadead same issue

**Comment by AliAdil** [comment]
For some reason, learn.freecodecamp.org is not accessible in my area on any of the internet browser.
*********************************************
Firefox shows
Secure Connection Failed

The connection to the server was reset while the page was loading.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Learn more…

Report errors like this to help Mozilla identify and block malicious sites

********************************************
Chrome shows 
This site can’t be reached
The connection was reset.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_RESET
********************************************

Add a Link to the page with the problem
https://learn.freecodecamp.org/

Tell us about your browser and operating system
Browser Name: Chrome, Firefox and IE
Browser Version:latest version
Operating System: Windows 10
Screenshot
google chrome link
https://ibb.co/fA2CNo
firefox screenshot link
https://ibb.co/kHNU2o

I can access this site using proxy  but it is not working without proxy.

**Comment by Ozarion** [comment]
This appears to be an ISP issue.

**Comment by iamzakofficial** [comment]
@raisedadead guide.freecodecamp.org is also not working, exact same issue .

**Comment by Ozarion** [comment]
@raisedadead Yes. guide.freecodecamp.org is also unreachable.

**Comment by shabbas** [comment]
I have tried with 2 different ISPs but i face same issue everywhere... same result for https://guide.freecodecamp.org/. I will try to reach out one ISP and see if they can solve this at their end.

**Comment by shabbas** [comment]
I contacted my ISP and worked with them over some network settings changes but still facing the same issue. @raisedadead

**Comment by raisedadead** [comment]
We have narrowed down the issue as to be an IP from Netlify (our CDN partner) being specifically blocked in the general region of Pakistan.

Unfortunately a proper fix involves getting in touch with the ISP and service providers. 

The CDN partner can not do much, because their infrastructure is responding as expected. The ISP / authorities there need to be made aware of the fact that its hurting users of a learning platform.

We can reach out out to them, if you all can help us with the relevant contact details of the authorities and the official processes.

Until then sadly we are limited in terms of any technical solution that we can offer.

**Comment by iamzakofficial** [comment]
@raisedadead this is official contact email of my ISP provider info@cyber.net.pk, i have also emailed them about the issue.

**Comment by raisedadead** [comment]
Hi All,

We have a reply from our CDN partner. Can anyone confirm that you can access the site without any proxies? As you would normally?

Thanks.

**Comment by raisedadead** [comment]
Awesome.. lets wait for a few others as well before closing this.

**Comment by wahaj-47** [comment]
Nope still can't access the curriculum page

**Comment by iamzakofficial** [comment]
Yes, Its working and now i can access curriculum without proxy or vpn

**Comment by shabbas** [comment]
@raisedadead it started failing again for me now. Not sure, if your CDN partner did some temporary changes or they were permanent.

**Comment by Ozarion** [comment]
@raisedadead It appears to be inaccessible on my side.

**Comment by Ozarion** [comment]
@raisedadead Issue is resolved.

**Comment by Ozarion** [comment]
Issue seems to be resolved from my side. Please update your status so we can happily close this issue. :)

**Comment by Rashheh** [comment]
Issue resolved, can access the site without using a proxy.

**Comment by wahaj-47** [comment]
Yep,  issue resolved :)

**Comment by AliAdil** [comment]
Yup, it works fine now.
