### ISSUE TITLE
Blank page shown while selecting the curriculam link

### ISSUE THREAD

**Issue by gopinathanjeeva** [freeCodeCamp/freeCodeCamp#17365]
#### Browser and operating system

* Browser Name: firefox
* Browser Version: 60.0.1
* Operating System: Windows 7

#### If possible, add a screenshot here

![freecodecamp](https://user-images.githubusercontent.com/39827740/40836363-1737e7b6-65b4-11e8-95ee-b6f82772a018.png)

**Comment by JMVL64** [comment]
same problem here!

Browser name: Chrome
Browser Version: 66.0.3359.181
Operation system: MacOs

**Comment by Bouncey** [comment]
We had an issue of an over-active service worker not letting go of the cache. We have pushed a fix for this. Hopefully you will not see it again

**Comment by Ruvalter** [comment]
Same problem here. Every time I try to access my curriculum I got a problem.
Clicking on the curriculum button I would go to a blank page and lots of errors in the console.
Now, when I click on the curriculum button from the settings page, I am redirected to the curriculum page but I am not logged in anymore. In that case I can not see my real progress and choose the next challenge
