### ISSUE TITLE
Adding 2 break lines to space the sections out waypoint

### ISSUE THREAD

**Issue by rwickline11** [FreeCodeCamp/FreeCodeCamp#1736]
Challenge http://www.freecodecamp.com/challenges/waypoint-clean-up-your-form-using-linebreaks has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

It seems that there isn't enough space on the display given to add two line-breaks. However, it does let you pass and move forward.

**Comment by ByteOnThis** [comment]
It is working for me and is displaying fine in the side preview. Did you add one <br> element underneath at least two <label> elements in the form element?

Here is a screenshot.
![issue-1736](https://cloud.githubusercontent.com/assets/13778507/9265694/d7d824e4-41eb-11e5-95c3-73ff01b03726.png)

**Comment by kennethmath** [comment]
What is it but more troubles now anyway it does whateverthey want it to think they just log in with a wireless device cause I couldn't put my number in then it said wireless where my #goes and took off and I started hitting the x Idk

**Comment by kennethmath** [comment]
Idk how can't do nothing

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
