### ISSUE TITLE
problem running tests for Sum All Primes Intermediate Algorithm Scripting challenge

### ISSUE THREAD

**Issue by smithfred0987** [freeCodeCamp/freeCodeCamp#17374]
#### Describe your problem and - if possible - how to reproduce it
When I run the tests for this challenge on my code, it fails me for the last test where num = 977 and the result is 73156.
The problem is my code does in fact get the correct result of 73156 when num = 977 and I run this code external to FCC, but the FCC run test still fails me.
I started a Forum topic at FCC on this as per the first link below, and they said my code was timing out because there is a 500 ms infinite loop stop protection device in FCC's tests.  I told them that 1) I never receive an error message to this effect, and 2) when I try to prevent the system from timing me out by adding  "//noprotect" as per the second link below to every other line of my code, I still get the same result. 

They also insisted that my code was in deed triggering the 500 ms infinite loop protection device even though I do not get an error message to this effect, and that my "//noprotect" may not be working correctly.  

As a result, I was instructed by the FCC forum to start a GitHub issue, which I am now doing.  

#### Add a Link to the page with the problem
https://forum.freecodecamp.org/t/problem-with-sum-all-primes-intermediate-challenge/194841/9
https://forum.freecodecamp.org/t/free-code-camp-infinite-loop-protection/19550
https://codepen.io/smithfred0439/pen/wXamLY

#### Tell us about your browser and operating system

* Browser Name: Firefox Quantum  (as well as Chrome)
* Browser Version: 60.0.1 (64-bit)  (Version 66.0.3359.181 (Official Build) (64-bit) for Chrome)
* Operating System: Windows 10 Pro 64 bit

**Comment by lynxlynxlynx** [comment]
//noprotect as line 1 worked for me when helping a forum user.

**Comment by moT01** [comment]
The code in your forum post passes all tests on the [beta site](https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sum-all-primes) - So, I believe, this is no longer an issue. If you are still having problems, you can reopen it.
