### ISSUE TITLE
Sign in problem

### ISSUE THREAD

**Issue by AwsmAbhishek** [freeCodeCamp/freeCodeCamp#17372]
#### Describe your problem and - if possible - how to reproduce it
I can't sign in using my github account.

#### Add a Link to the page with the problem
https://www.freecodecamp.org

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 66.0.3359.181
* Operating System: Windows 10

**Comment by raisedadead** [comment]
Did you sign up previously using GitHub? If yes, can you privately share your details to our support email team@freecodecamp.org

**Comment by raisedadead** [comment]
Closing in favor of duplicate https://github.com/freeCodeCamp/freeCodeCamp/issues/17359

**Comment by AwsmAbhishek** [comment]
Well Thanks.
