### ISSUE TITLE
Dropdown for tests not showing in codepen.

### ISSUE THREAD

**Issue by RiaClay** [freeCodeCamp/freeCodeCamp#17375]
#### Describe your problem and - if possible - how to reproduce it
I am working on the Build A Tribue Page project and when I forked the Test Suite Template, it does not have a drop down box to select the test. I am using the Chrome browser. 

#### Add a Link to the page with the problem
https://codepen.io/SherriaClay/pen/dKYNZM
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-tribute-page/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version:  66.0.3359.181 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by RiaClay** [comment]
When trying to access the CDN link, it says that the CDN is blacklisted. I'm guessing that may have something to do with it. 

![image](https://user-images.githubusercontent.com/35746994/40860185-1c2b0122-65aa-11e8-88ad-6921f73a87a3.png)

**Comment by QuincyLarson** [comment]
I just confirmed this. GitHub seems to have blacklisted our GitCDN link: https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js

We're looking for another place to host this real quick.
