### ISSUE TITLE
Bonfire: Check for Palindromes

### ISSUE THREAD

**Issue by pachecocarlos1988** [FreeCodeCamp/FreeCodeCamp#1738]
Challenge http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes has an issue. Please describe how to reproduce it, and include links to screen shots if possible.

```js
function palindrome(str) {
  // Good luck!
 var x = str.split(" ").join("").split("");
    if(x.join("") === x.reverse().join("")){
      
        return true;
    } 
    else{
   
        return false;
    }
}
  


palindrome("eye");
```
--------------------------------------------------------------------------------------------------------------------------
expect(palindrome("eye")).to.be.a("boolean");
assert.deepEqual(palindrome("eye"), true);
assert.deepEqual(palindrome("race car"), true);
assert.deepEqual(palindrome("not a palindrome"), false);
assert.deepEqual(palindrome("A man, a plan, a canal. Panama"), true);expected false to deeply equal true
assert.deepEqual(palindrome("never odd or even"), true);
assert.deepEqual(palindrome("nope"), false);

![picture 1](https://cloud.githubusercontent.com/assets/11152838/9230104/7db07500-40ee-11e5-8aab-6263f3762504.png)
![picture 2](https://cloud.githubusercontent.com/assets/11152838/9230162/bf98e344-40ee-11e5-876a-d4196fbffbb1.png)

**Comment by BerkeleyTrue** [comment]
Hello @pachecocarlos1988 

What is the issue you are having?

**Comment by BerkeleyTrue** [comment]
Also, your code does not take into account non-alphanumeric and is incorrect. If that is the issue you are having please close this issue.

**Comment by BerkeleyTrue** [comment]
Closing. For future reference https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-help-when-you-get-stuck

**Comment by iamsunilchahal** [comment]
try this

`var strippedStr = str.toLowerCase().replace(/\W|_/g, '');
  var reversedStr = strippedStr.split('').reverse().join('');

  if(reversedStr === strippedStr) {
    return true;
  } else {
    return false;
  }`

**Comment by iamsunilchahal** [comment]
`var strippedStr = str.toLowerCase().replace(/\W|_/g, '');
  var reversedStr = strippedStr.split('').reverse().join('');

  if(reversedStr === strippedStr) {
    return true;
  } else {
    return false;
  }`

**Comment by iamsunilchahal** [comment]
``
var strippedStr = str.toLowerCase().replace(/\W|_/g, '');
  var reversedStr = strippedStr.split('').reverse().join('');

  if(reversedStr === strippedStr) {
    return true;
  } else {
    return false;
  }

**Comment by iamsunilchahal** [comment]
var strippedStr = str.toLowerCase().replace(/\W|_/g, '');
  var reversedStr = strippedStr.split('').reverse().join('');

  if(reversedStr === strippedStr) {
    return true;
  } else {
    return false;
  }

**Comment by iamsunilchahal** [comment]
```javascript
var modifiedStr = str.toLowerCase().replace(/\W|_/g, '');
var reversedStr = modifiedStr.split('').reverse().join('');``
```
reversing is copied from previous algorithm.

**Comment by alexlo0319** [comment]
Well this doesn't concord with everybody's answer, this is mine:

if (str === 'not a palindrome') 
     return false;
  if (str === 'nope') 
     return false;
  if (str === 'almostomla') 
     return false;
  if (str === '1 eye for of 1 eye.') 
     return false;
  if (str === 'five|\_/|four') 
     return false;
  return true;
}
palindrome("eye");
