### ISSUE TITLE
Where did all my progress go?

### ISSUE THREAD

**Issue by dougBelcher** [freeCodeCamp/freeCodeCamp#17383]
This is the first time I have tried to log in since the update and I'm not getting to the correct profile because all of my progress is gone.  It has been a while since I worked steadily on it but now it is gone?

https://www.freecodecamp.org/

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: Version 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Win 10

**Comment by sdabhi23** [comment]
Hey @dougBelcher you can check your previously completed challenges on the [Curriculum Page](https://learn.freecodecamp.org/) after logging in. Also you can view the same on your profile page too on the link `https://www.freecodecamp.org/portfolio/:username`.

Your legacy certifications and progress on the related projects is available under Legacy Certifications section on the [settings page](https://www.freecodecamp.org/settings)!

**Comment by dougBelcher** [comment]
Thanks for the info.  I must have been logging incorrectly because I can now see all my progress.
