### ISSUE TITLE
Basic CSS lesson with typos in tests

### ISSUE THREAD

**Issue by Matthew-Burfield** [freeCodeCamp/freeCodeCamp#17385]
#### Describe your problem and - if possible - how to reproduce it
There is a type in the challenge "Basic CSS - Use CSS Variables to change several elements at once"

The tests are asking the user to update the colours for `--penguin-skin` three times, where it should be `--penguin-skin`, `--penguin-belly` and `--penguin-beak` respectively

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-variables-to-change-several-elements-at-once/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66.0.3359.181
* Operating System: macOS Sierra 10.12.6

#### If possible, add a screenshot here
![screen shot 2018-06-02 at 9 59 33 am](https://user-images.githubusercontent.com/5549728/40869930-9c486a76-6667-11e8-9d01-026be479ade8.png)

**Comment by nprizal** [comment]
Hi @Matthew-Burfield, I just ran into this issue too. I think you can found the code on `/seed/challenges/01-responsive-web-design/basic-css.json`. It's from line 4303.

```json
"tests": [
        {
          "text": "<code>penguin</code> class should declare the <code>--penguin-skin</code> variable and assign it to <code>gray</code>.",
          "testString": "assert(code.match(/.penguin\\s*?{[\\s\\S]*--penguin-skin\\s*?:\\s*?gray\\s*?;[\\s\\S]*}/gi), '<code>penguin</code> class should declare the <code>--penguin-skin</code> variable and assign it to <code>gray</code>.');"
        },
        {
          "text": "<code>penguin</code> class should declare the <code>--penguin-skin</code> variable and assign it to <code>white</code>.",
          "testString": "assert(code.match(/.penguin\\s*?{[\\s\\S]*--penguin-belly\\s*?:\\s*?white\\s*?;[\\s\\S]*}/gi), '<code>penguin</code> class should declare the <code>--penguin-skin</code> variable and assign it to <code>white</code>.');"
        },
        {
          "text": "<code>penguin</code> class should declare the <code>--penguin-skin</code> variable and assign it to <code>orange</code>.",
          "testString": "assert(code.match(/.penguin\\s*?{[\\s\\S]*--penguin-beak\\s*?:\\s*?orange\\s*?;[\\s\\S]*}/gi), '<code>penguin</code> class should declare the <code>--penguin-skin</code> variable and assign it to <code>orange</code>.');"
        }
      ]
```

**Comment by rexiemedia** [comment]
Since it was a typo on the assignment was it it not changed simple

penguin class should declare the --penguin-skin variable and assign it to gray.
Passed
penguin class should declare the --penguin-belly variable and assign it to white.
Passed
penguin class should declare the --penguin-beak variable and assign it to orange.

Instead of all these plenty grammar and drama
