### ISSUE TITLE
Example code in challenge causes tests to fail - Manipulate Arrays With shift()

### ISSUE THREAD

**Issue by alhazen1** [freeCodeCamp/freeCodeCamp#17384]
Challenge Basic JavaScript - Manipulate Arrays With shift()
This challenge contains example code in code window. That example code causes the tests to fail.

Error message in console window pertaining to example code
**removedFromOurArray is not defined**

Line 3 is 
removedFromOurArray = ourArray.shift();

problem resolved by changing line 3 to 
var removedFromOurArray = ourArray.shift();

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/manipulate-arrays-with-shift/

Also, from the forum
https://forum.freecodecamp.org/t/bug-on-manipulate-arrays-with-shift/195248

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Ubuntu 16.04

**Comment by thatnini** [comment]
Duplicate of [#17287](https://github.com/freeCodeCamp/freeCodeCamp/issues/17287)

**Comment by alhazen1** [comment]
Oops - did not see duplicate. Closing this one.
