### ISSUE TITLE
The test CDN link is blacklisted

### ISSUE THREAD

**Issue by C0nst4nt1ne85** [freeCodeCamp/freeCodeCamp#17380]
The link https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js it is not working. No tests show up on codepen anymore.

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.62 (Official Build) (64-bit)
* Operating System: Windows 10

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/32928319/40864449-8f3aad00-65fc-11e8-862e-e5f0b3fa93e7.png)

**Comment by raisedadead** [comment]
Hi thanks for reporting. We have got a fix ready.. it should be live in a few hours. Meanwhile you can use this <https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js>

**Comment by raisedadead** [comment]
Fixed via https://github.com/freeCodeCamp/freeCodeCamp/pull/17376
