### ISSUE TITLE
Predefined user account for local login and development setup

### ISSUE THREAD

**Issue by iliasTsiortas** [freeCodeCamp/freeCodeCamp#17382]
I had a problem with mongo that i didnt know how to solve and i cloned and set up the local app again.When i went to localhost and i clicked on sign in , it redirected me to 
https://stuff/authorize?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fauth0%2Fcallback&scope=openid%20email&client_id=stuff.
 
I didnt do anything different from when i first set up my local app other than updating my fork.

* Browser Name: Mozilla firefox
* Browser Version: 60.0.1
* Operating System: windows 10 home 1803

![image](https://user-images.githubusercontent.com/26048222/40868171-104c52ca-6613-11e8-8b2f-ca4169b3cb5b.png)

![image](https://user-images.githubusercontent.com/26048222/40868175-1c590180-6613-11e8-89d0-4ce9519510c4.png)

**Comment by QuincyLarson** [comment]
@iliasTsiortas We're working on a workaround so you can authenticate in development mode without needing to worry about Auth0

@raisedadead is working on updating the Contributing.md file with details as soon as he's implemented the fix - hopefully in the next 48 hours.

**Comment by iliasTsiortas** [comment]
@QuincyLarson great thanks!

**Comment by tchaffee** [comment]
Related to https://github.com/freeCodeCamp/learn/issues/105

**Comment by Nirajn2311** [comment]
@QuincyLarson any updates on the authentication.

**Comment by raisedadead** [comment]
@Nirajn2311 thanks for your interest. 

The updates will come soon, unfortunately we can't exactly state when. We recommend you to take a look at some of the other repos meanwhile to continue contributing without being blocked.

Happy contributing!

**Comment by ktajpuri** [comment]
Is there a workaround for this? I am facing this issue too.

**Comment by Flarp** [comment]
I was able to temp fix this issue by creating an auth0 account, and putting all the related content in the `AUTH0` fields.

**Comment by tchaffee** [comment]
@Flarp Can you give more details on exactly what you had to put where? Did you have to change URLs anywhere? Or just put some info in a config file? As many details as possible will help others try this too. Thanks!

**Comment by Nirajn2311** [comment]
@tchaffee I also was able to temp fix it. You have to copy paste (from your application in auth 0) the auth0 domain, client Id and secret key to your .env file. Also you have to add http://localhost:3000/auth/auth0/callback to your apps allowed callback url.

**Comment by raisedadead** [comment]
The ideal fix for this is:

1. Add a local auth route handler in the `authentication.js`
2. Update the `component-passport.js` to have a environment specific bypass (`NODE_ENV=development`) for letting in a user in. That is `login` cookies are to be set.
    1. Setting a login cookie needs you to set the `access_token` 
    2. Setting access from `learn` needs you to have a jwt token in the cookie.
3. Updating seeding script to add the same user while in development (`npm run seed`)
4. The user object should be seeded before the server is running.

Anyways, the implementation should more importantly, handle the fact the none of the code should execute in production.

I am open to guide more on a pull request.

**Comment by Flarp** [comment]
@raisedadead if `NODE_ENV=development`, the code should never run in production anyway.

**Comment by tchaffee** [comment]
@Nirajn2311 I did all that but am still getting an error.

Right after I get redirected to auth0 for the sign-in, it tries to go to URL http://localhost:3001/auth/auth0/callback?code=j2QobDLO6eKylrPB which crashes the app with the following:

```
2018-07-13T22:48:04.476Z 302 GET 4.859 ms - /auth/auth0
/vagrant/node_modules/rx/dist/rx.js:77
    throw e;
    ^

Error: secretOrPrivateKey must have a value
    at Object.module.exports [as sign] (/vagrant/node_modules/jsonwebtoken/sign.js:102:20)
    at /vagrant/server/component-passport.js:160:37
    at Strategy.strategy.success (/vagrant/node_modules/passport/lib/middleware/authenticate.js:214:18)
    at verified (/vagrant/node_modules/passport-oauth2/lib/strategy.js:177:20)
    at /vagrant/node_modules/@freecodecamp/loopback-component-passport/lib/passport-configurator.js:291:7
    at AnonymousObserver._onNext (/vagrant/common/models/User-Identity.js:148:32)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/vagrant/node_modules/rx/dist/rx.js:1828:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/vagrant/node_modules/rx/dist/rx.js:1762:31)
    at AnonymousObserver.tryCatcher (/vagrant/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/vagrant/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/vagrant/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.next (/vagrant/node_modules/rx/dist/rx.js:3763:21)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/vagrant/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.tryCatcher (/vagrant/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/vagrant/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/vagrant/node_modules/rx/dist/rx.js:1762:31)
[22:48:12] [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by nathanhannig** [comment]
Are you still having issues?

- Setup freeCodeCamp repo
- Setup learn repo (optional)
- Created Auth0 account
- Create an application for fCC on Auth0 with required callback URL
- Copied required info to .env file
- Start/Restart freeCodeCamp repo
- I am able to authenticate locally

**Comment by bvipul** [comment]
Okay, I will try. Thanks

**Comment by ktajpuri** [comment]
I have tested it. Steps  @nathanhannig has mentioned work perfectly. I would just like to mention something which might not be obvious to someone. You need to have a userid and password which you can use to authenticate after the oAuth login screen is presented after you click on signin button in local FCC. For this you need to create a user in your oAuth application. Click on users in the left sidebar and then click on create user from your oAuth account. You wil lget an activation email on the email you use to create an account. After you activate this, you can use this credential for login to local FCC.

**Comment by chaitanyaashtekar** [comment]
@nathanhannig  @ktajpuri  I did the steps as you asked.the server crashes.think you could help me ?
server crashes after I put in my usrname and password in the auth0 window
![err](https://user-images.githubusercontent.com/3967029/43413866-d4fa2b74-944e-11e8-81b4-78e8f13de224.png)

**Comment by Nirajn2311** [comment]
@chaitanyaashtekar try restarting it by typing ‘rs’ when nodemon app crashes error comes

**Comment by chaitanyaashtekar** [comment]
@Nirajn2311  tried it as many times as read in other pages 'rs', the server still crashes

**Comment by sanchitbansal10** [comment]
@chaitanyaashtekar did the steps mentioned by nathanhannig and its working fine...

**Comment by zolbayars** [comment]
So, there's no need to run the MailHog?

**Comment by nathanhannig** [comment]
@zolbayars
not required, only if you need to send and receive emails

**Comment by tchaffee** [comment]
@raisedadead I'll start working on this right away. Is this still the approach you would recommend, from your comment above in June? 

The ideal fix for this is:

    Add a local auth route handler in the authentication.js
    Update the component-passport.js to have a environment specific bypass (NODE_ENV=development) for letting in a user in. That is login cookies are to be set.
        Setting a login cookie needs you to set the access_token
        Setting access from learn needs you to have a jwt token in the cookie.
    Updating seeding script to add the same user while in development (npm run seed)
    The user object should be seeded before the server is running.

Anyways, the implementation should more importantly, handle the fact the none of the code should execute in production.

**Comment by raisedadead** [comment]
### We now have local auth support for a development user 🎉 !

Two things to note:

- If you already have a setup, and/or you used the AUTH0 keys. You can replace them with the `sample.env` values like `stuff`.
-Additionally you need to add `LOCAL_MOCK_AUTH=true` to your current `.env`

New setups can simple follow the usual guidelines.

Thanks a lot to the efforts of @tchaffee ! 👏

**Comment by FranciscoImanolSuarez** [comment]
Hello, how should I do to log in with our own credentials or service providers (Google)?
