### ISSUE TITLE
Unable to open curriculum(learn.freecodecamp.org) after clicking Go to my curriculum(freecodecamp.org)

### ISSUE THREAD

**Issue by iamzakofficial** [freeCodeCamp/freeCodeCamp#17398]
![image](https://user-images.githubusercontent.com/9195137/40880515-e41a3e56-66cb-11e8-8234-394be79a4b7f.png)

**Comment by Kiyani-g** [comment]
same problem

**Comment by raisedadead** [comment]
Is this a possible duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/17360? Can you guys confirm you general region as in the other thread?

**Comment by iamzakofficial** [comment]
i tried onProxy, it works on proxy.

**Comment by Kiyani-g** [comment]
how proxy works ? i still have problem

**Comment by Kiyani-g** [comment]
how to use proxy?

**Comment by iamzakofficial** [comment]
install chrome extension browsec, turn it on and then open freecodecamp
