### ISSUE TITLE
Incorrect link on the JSON API Challenge

### ISSUE THREAD

**Issue by sdabhi23** [freeCodeCamp/freeCodeCamp#17395]
#### Describe your problem and - if possible - how to reproduce it

The relative link for API used in the [JSON APIs and Ajax - Get JSON with the JavaScript XMLHttpRequest Method](https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/get-json-with-the-javascript-xmlhttprequest-method) challenge leads to https://learn.freecodecamp.org/json/cats.json which returns a **404**.

While using the actual link, i.e. https://www.freecodecamp.org/json/cats.json in the code leads to **No 'Access-Control-Allow-Origin' header is present on the requested resource** error.

It will be great if this can be fixed. The tests are all running fine regardless of the error. But the users won't be able to see the code in action due to this.

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 66.0.3359.181
* Operating System: Windows 10

#### If possible, add a screenshot here

* While using the relative (incorrect) link
![image](https://user-images.githubusercontent.com/25759344/40879048-deba91fe-66b7-11e8-8bb2-99c69b40a4a7.png)

* While using the correct link
![image](https://user-images.githubusercontent.com/25759344/40879057-f348c794-66b7-11e8-832d-b2426af1687d.png)

**Comment by raisedadead** [comment]
This is an easy fix, we need to move the `json` file over to https://github.com/freeCodeCamp/learn and the make the linking relative as before.

Please open a PR on the Learn repo.

**Comment by sdabhi23** [comment]
I would also like to for it. The problem is I am not able to find the relevant file which handles the routes on https://github.com/freeCodeCamp/learn

**Comment by wildhamster26** [comment]
@raisedadead I've gone over it and want to make sure I got it right... Sorry if it's too much, but it's my first time... o.O

**The problem** is that the current link is local: "/json/cats.json" so it points to "learn.freecodecamp.org" ,because it's called from there. However, the actual code sits in the freecodecamp.org repo so it gets an error.

**The solution** is to create a library called "04-data-visualization" inside "learn>seed>challenges" and copy-paste the json file "json-apis-and-ajax" over there...? 
If so, then I don't see where I should change the code to be relative as you've said: "and then make the linking relative as before"...

Sorry again if it's an inappropriate question here in some way... 

Thanks in advance.

**Comment by wildhamster26** [comment]
@sdabhi23  - good chance that I'm out of my depth here, but I have to ask if I want to learn, right? :)
Why would you need to to change the routes?
The way the site is built (I think) calls for the folder it's in and then uses the json object for the name and title properties... isn't it?

**Comment by sdabhi23** [comment]
@wildhamster26 the seed>challenges folder is only meant to hold the data required to inflate the challenge templates. So I think, most probably that approach won't work. Will have to think of something else. Looking at [buildChallenges.js](https://github.com/freeCodeCamp/learn/blob/master/seed/buildChallenges.js) will help you understand this better.

I was asking for routes coz then we can just add a new route to /json/cats.json and point it to cats.json in the relevant folder.

**Comment by wildhamster26** [comment]
@sdabhi23  So that would be what riasedadead meant in making sure the code is relative...

I need to do more backend work.

Thanks for explaining. :)

**Comment by anku255** [comment]
@raisedadead I have created a PR [#176](https://github.com/freeCodeCamp/learn/pull/176) to address this issue. Please take a look.

**Comment by anku255** [comment]
@raisedadead @Bouncey Thanks for merging my PR. This issue can be closed now.

**Comment by Bouncey** [comment]
Closed via #179.

Thanks for the heads up @anku255
