### ISSUE TITLE
Zipline Twitch.tv API hint contains two usernames that return errors on query

### ISSUE THREAD

**Issue by cch5ng** [FreeCodeCamp/FreeCodeCamp#1739]
* In this zipline: http://www.freecodecamp.com/challenges/zipline-use-the-twitch.tv-json-api
there is a hint: 
  * Here's an array of the Twitch.tv usernames of people who regularly stream coding: ["freecodecamp", "storbeck", "terakilobyte", "habathcx","RobotCaleb","comster404","brunofin","thomasballinger","noobs2ninjas","beohoff"]
* If I test the streams API query with the users: brunofin and comster404, I get an error
  * https://api.twitch.tv/kraken/streams/brunofin
    * Error: "Channel 'brunofin' is not available on Twitch"
  * https://api.twitch.tv/kraken/streams/comster404
    * Error: "Channel 'comster404' is not available on Twitch"
* I would suggest those users should be removed from the hint to save the students' testing time
* In addition, I would suggest one user should be added to the hint: medrybw
  * The reason is that this channel appears to be streaming 24/7 while most other channels are streaming intermittently. This will help in testing the application.

**Comment by cch5ng** [comment]
on later reflection, it might be valuable for students to have a lesson in the curriculum on error handling and what to do when an api returns an error message. just a thought.

**Comment by labiej** [comment]
I agree with the comment above.
Perhaps make it a bonus user story so the app doesn't break whenever a channel doesn't exist anymore. (I noticed it in my own app when a bunch of campers had issues earlier this week)

**Comment by QuincyLarson** [comment]
@labiej @cch5ng great suggestions. I will add these as known broken users and include a bonus user story :)
