### ISSUE TITLE
Unable to claim certifications even after adding a name on the portfolio

### ISSUE THREAD

**Issue by AlanMamphs** [freeCodeCamp/freeCodeCamp#17397]
#### Problem Description
When I try to view my certificate, it shows the message:
"This user needs to add their name to their account in order for others to be able to view their certification."
Although, I have updated my name, and tried to access my certificates afterwards.
This concerns both, legacy front end certificate and Javascript Algorithms and Data Structures certification. 
All of the projects's solutions for the certificate, were migrated from older freecodecamp account.
#### Link to the certicate
https://www.freecodecamp.org/certification/alanmamphs/javascript-algorithms-and-data-structures

#### Browser and Operating System

* Browser Name: Chromium
* Browser Version: 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Linux 18.04

#### Screenshots
![screenshot from 2018-06-03 00-58-55](https://user-images.githubusercontent.com/14315501/40879949-795f1baa-66ca-11e8-90b6-a028f9aaea36.png)

![screenshot from 2018-06-03 01-08-54](https://user-images.githubusercontent.com/14315501/40879959-ba327ae6-66ca-11e8-8863-4263e12c8a30.png)

**Comment by raisedadead** [comment]
Hi @AlanMamphs thanks for reporting this. Sorry about your experience. We are looking at this on priority.

**Comment by dudeguykid** [comment]
I am having the same issues: https://www.freecodecamp.org/portfolio/dudeguykid
![untitled](https://user-images.githubusercontent.com/18690468/40926552-76ddf20e-67ea-11e8-9faa-b455ae45b690.png)

**Comment by dudeguykid** [comment]
@raisedadead is this something you can help me with too?

**Comment by AlanMamphs** [comment]
Any updates on below?

**Comment by dudeguykid** [comment]
nothing

**Comment by mattszcz** [comment]
I guess my issue is part of this. I completed Responsive Web Design, but I can't find any button or any way to claim my certificate.

Just says, "No certifications have been earned under the current curriculum"

![screenshot 2018-06-12 at 2 28 27 pm](https://user-images.githubusercontent.com/17437264/41318408-1876063e-6e4d-11e8-99d3-b449a6bc0bd7.png)

**Comment by raisedadead** [comment]
> but I can't find any button or any way to claim my certificate.

They are on your settings page. Visit https://www.freecodecamp.org/settings

@QuincyLarson there have been lot of issues where campers are finding it difficult to understand where to claim their certs.

I think we would need to have an on boarding flow for this.

**Comment by dudeguykid** [comment]
@raisedadead thanks for the response, @QuincyLarson thanks in advance. Let me know if I can do anything, more than happy to help.

**Comment by mattszcz** [comment]
The settings page must have been fixed recently. It used to go from Academic Honesty Policy directly to Danger Zone. Now the certificate claim forms appear there. Confirmed, it is now working.

**Comment by dudeguykid** [comment]
i now get "has not yet agreed to our Academic Honesty Pledge." but I have.

**Comment by raisedadead** [comment]
Hi @dudeguykid can we connect over email, please drop me an email at `mrugesh at freecodecamp dot org`

**Comment by raisedadead** [comment]
Hi @dudeguykid I have fixed up your user record. Can you please try again? You seemingly had multiple accounts with the same email.

**Comment by dudeguykid** [comment]
All works now, certificates are all there! thanks for your help!

**Comment by AlanMamphs** [comment]
I still cannot view any certificates.

**Comment by normurod72** [comment]
me as well, ```No certifications have been earned under the current curriculum```

**Comment by diewo77** [comment]
I have the same problem even if my name is there, 

> This user needs to add their name to their account in order for others to be able to view their certification.
Username in freecodecamp is: diewo77

**Comment by leoprojects** [comment]
I have the same problem. Whenever i click the Show Certification button, i get the following mesage:
**fccd1499da0-f364-4934-a643-217a307a53db has chosen to make their certifications private. They will need to make their certifications public in order for others to be able to view them.**

**Comment by raisedadead** [comment]
Hi please follow through the FAQs, here: https://support.freecodecamp.org/ or reachout to the forum at https://www.freecodecamp.org/forum 

This is issue tracker is reserved for reporting confirmed bugs on the plaform.
