### ISSUE TITLE
Basic HTML and HTML5 - Create a Set of Checkboxes

### ISSUE THREAD

**Issue by Dave-Melia** [freeCodeCamp/freeCodeCamp#17393]
#### Describe your problem and - if possible - how to reproduce it
This might be a global problem and not isolated to the lesson itself.

On the lesson "Basic HTML and HTML5 - Create a Set of Checkboxes", I accidentally set an 'id' attribute as 'it' like this:

```
<label for="loving">
  <input it="loving" type="checkbox" name="personality">Loving
</label>
```

However, the the tests ran and returned the following:

```
// running test
Give your checkboxes the name attribute of personality.
// tests completed
```

It look me a while to figure out what the problem was because I was looking at the name attribute as per the test log.  This will be a showstopper for beginners as they might not know what to look out for.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-set-of-checkboxes

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66.0.3359.181
* Operating System: MacOS High Sierra.

#### If possible, add a screenshot here
https://imgur.com/a/JNrRg6F

**Comment by maheshwarLigade** [comment]
Give your checkboxes the name attribute of personality
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-set-of-checkboxes
