### ISSUE TITLE
Wrong description on basic css lesson use-css-variables-to-change-several-elements-at-once

### ISSUE THREAD

**Issue by anmolthedeveloper** [freeCodeCamp/freeCodeCamp#17394]
#### Describe your problem and - if possible - how to reproduce it
Please correct the wrong todo list as it says to change only --penguin-skin variable all three times
but we have to change 

 --penguin-skin: white;
    --penguin-belly: gray;
    --penguin-beak: yellow;
these three

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-variables-to-change-several-elements-at-once

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System: 

#### If possible, add a screenshot here
![freecodecamp](https://user-images.githubusercontent.com/25072658/40879030-991df1e0-66b7-11e8-8115-10691f9057e0.png)

**# you can see the description doesn't match and i got confused ....**

it should be like this

    --penguin-skin: white;
    --penguin-belly: gray;
    --penguin-beak: yellow;

and not just --penguin-skin

**Comment by akkatracker** [comment]
In addition `declar` is spelled wrong, which is mentioned in this issue: #17404

If you'd like to update your description, I'll close my issue.

**Comment by tensigh** [comment]
They still haven't fixed it.
