### ISSUE TITLE
Basic CSS Section: Issue with lesson content/instructions

### ISSUE THREAD

**Issue by rohitdwivedula** [freeCodeCamp/freeCodeCamp#17391]
#### Problem Description

There’s a mistake in the lesson (content) on using CSS variables to change several elements at once. The instructions there ask you to change the value of the same variable --penguin-skin thrice, from gray to white to orange. Doing that will cause your code to be rejected time after time after time.

What the assignment expects us to do:
-     change penguin-skin to gray
-     change penguin-belly to white
-     change penguin-beak to orange.

The instructions, however, tell us to:
-  change penguin-skin to gray
-  change penguin-skin to white
-  change penguin-skin to orange
(**Furthermore, "declare" is misspelt as "declar" in all three of the test cases.**)
I tried finding a “report an error” button or sending an email, but couldn’t find both. I posted on the FCC Forum as well. (link: https://forum.freecodecamp.org/t/how-do-i-report-an-error-in-the-lessons-to-freecodecamp/195550)

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-variables-to-change-several-elements-at-once

#### Browser and System Info

* Browser Name: Mozilla Firefox
* Browser Version: v60.0
* Operating System: Ubuntu (64 bit)

#### Screenshot

![screenshot from 2018-06-02 17-14-32](https://user-images.githubusercontent.com/25080952/40874888-642bd430-6693-11e8-9a3a-b991f9261c8c.png)

Screenshot also available here: https://ibb.co/njhiay

**Comment by tensigh** [comment]
Someone needs to fix this; I kept working on this until I found a post that reported the error.

**Comment by moT01** [comment]
Thank you for reporting this issue.

    This is a standard message notifying you that this issue is present in production, but it has been fixed in staging. Because of that, I’m closing this issue. When staging will be pushed to production again, your issue will be resolved.

    If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
