### ISSUE TITLE
ES6 - Use getters and setters to Control Access to an Object: Confusing?

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#17403]
#### Describe your problem and - if possible - how to reproduce it
The exercise can pass with just one line of code.
```js
  /* Alter code below this line */
  class Thermostat {}
  /* Alter code above this line */
```
It doesn't test what it should be testing.

I think the instructions can be made clearer. This is what I have in mind:

> Use the `class` keyword to create a `Thermostat` class. It should have a constructor that accepts a temperature in degrees Fahrenheit.
> 
> Now create a getter and a setter called `temperature` [or `celsius`, or `tempCelsius`, or `temperatureC`; they're clearer, but changing to any of these needs changes in the last few lines of the code as well] in the class. The getter should return the temperature in degrees Celsius. The setter should accept a temperature in degrees Celsius.
> 
> Remember that &deg;C = 5/9 * (&deg;F - 32) and &deg;F = &deg;C * 9/5 + 32.
> 
> Note that while the constructor requires a temperature in Fahrenheit, you can store the temperature internally in either Fahrenheit or Celsius. What's important is that the getter returns the temperature in Celsius and the setter accepts a temperature in Celsius.
> 
> This is the power of getters and setters - you are creating an API for another user, who would get the correct result, no matter how you implement them.
> 
> In other words, you are abstracting implementation details from the consumer.
> 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-getters-and-setters-to-control-access-to-an-object/

**Comment by Starrzan** [comment]
I encountered the same problem. The test passes even without having to create the getter or setter, even the constructor.  The only code that is needed for the test to pass appears to be the class declaration.

**Comment by RealDrale** [comment]
Same here.

**Comment by ryanmdoyle** [comment]
I think is not very clear what the expectations are either.  I have been trying to actually do it with declaring getters and setters, but I'm not really sure if I am not able to pass the test because my declarations are wrong, or this bug that's discussed.

I believe the description could be modified as in reading it, the understanding is to make an object that takes the temp in F and then you are able to access the temp in C by using the getter function.  That being said, other parts of the instruction make it seem like you should be able to assign the temperature in either F or C and then the setting function would turn that into the opposite.  At this point I'll just do what everyone else did to get it clear and assume I know what I'm doing...

**Comment by jcharnley** [comment]
I found this one really easy. 

function makeClass() {
  "use strict";
  /* Alter code below this line */
 class Thermostat {
   constructor(Fahrenheit) {
     this.Fahrenheit = Fahrenheit;
   }
   get temperature (){
     return this.temp;
   }

   set temperature (thermos) {
    this.temp = 5/9 * (thermos - 32);
   }
 }
  /* Alter code above this line */
  return Thermostat;
}
const Thermostat = makeClass();
const thermos = new Thermostat(76); // setting in Fahrenheit scale
let temp = thermos.temperature; // 24.44 in C
thermos.temperature = 26;
temp = thermos.temperature; // 26 in C


Just have to read the bottom variables and walk through the flow

**Comment by SoyDiego** [comment]
The same here, I have passed the challenge only writing:
```
  class Thermostat{
    constructor (temperature){
      this.temperature = temperature;
    }
  }
```
I think you should repair it, because the challenge is about Getters and Setters.

Thanks!

**Comment by mvravn** [comment]
This is still an issue, I just 'passed' with this:

function makeClass() {
  "use strict";
  /* Alter code below this line */
  class Thermostat {
    constructor(fahrenheit){
      this._fahrenheit = fahrenheit;
    }
    get b(){
      return this._fahrenheit;
    }
    set b(a){
      this._fahrenheit = a;
    }
  }
  /* Alter code above this line */
  return Thermostat;
}
const Thermostat = makeClass();
const thermos = new Thermostat(76); // setting in Fahrenheit scale
let temp = thermos.temperature; // 24.44 in C
thermos.temperature = 26;
temp = thermos.temperature; // 26 in C

**Comment by zdflower** [comment]
It is still happening. This code passed the test (it's wrong because the setter doesn't set anything):

```
/* Alter code below this line */
class Thermostat{
   constructor(fahrenheit){
    this._fahrenheit = fahrenheit;
  }

  get temperature(){
    return (5/9 * (this._fahrenheit - 32));
  }

// This doesn't set the temperature:
  set temperature(celsius){
    return celsius * 9.0 / 5 + 32;; 
  }
} 
  /* Alter code above this line */
```

**Comment by Freshi** [comment]
The issue still persists.

**Comment by nathanhannig** [comment]
I have no clue what this challenge description is even trying to have the user complete.

Why is there even code being used to set the temperature property when getter and setter are supposed to be used to avoid doing such things?
```
let temp = thermos.temperature; // 24.44 in C
thermos.temperature = 26;
temp = thermos.temperature; // 26 in C
```

The description seems to want the user to convert between C and F, but fails to provide any implementation details about method names

**Comment by andrew2033** [comment]
Hello)
```
function makeClass() {
  "use strict";
  /* Alter code below this line */
class Thermostat {
    constructor (F) {
      this.celsius = 5/9 * (F - 32);
    }

    get temperature() {
      console.log(`${this.celsius} in C`);
      return this.celsius;
    }

    set temperature(newTemp) {
      this.celsius = newTemp;
    }
  }
  /* Alter code above this line */
  return Thermostat;
}
const Thermostat = makeClass();
const thermos = new Thermostat(76); // setting in Fahrenheit scale
let temp = thermos.temperature; // 24.44 in C
thermos.temperature = 26;
temp = thermos.temperature; // 26 in C
```

**Comment by pantteri** [comment]
> #### Describe your problem and - if possible - how to reproduce it
> The exercise can pass with just one line of code.
> 
> ```js
>   /* Alter code below this line */
>   class Thermostat {}
>   /* Alter code above this line */
> ```

The issue still exists.

**Comment by RandellDawson** [comment]
@pantteri The issue is still open, so yes the issue still exists.

**Comment by eyeMNaughtReal** [comment]
After a year, this issue still exists?  I was able to pass this test with the following code, knowing it was not following the instructions:
``` javascript
function makeClass() {
  "use strict";
  /* Alter code below this line */
class Thermostat{
  constructor(temp) {
    this._temp = temp;
  }
  get thermos(){
    return this._temp;
  }
  set thermos(updateTemp){
    this._temp = updateTemp;
  }
}
  /* Alter code above this line */
  return Thermostat;
}
const Thermostat = makeClass();
const thermos = new Thermostat(76); // setting in Fahrenheit scale
let temp = thermos.temperature; // 24.44 in C
thermos.temperature = 26;
temp = thermos.temperature; // 26 in C
```

**Comment by adrozemog** [comment]
Hello all. How could one test the output for various temperature values using console.log? Thank you!

**Comment by adrozemog** [comment]
> After a year, this issue still exists? I was able to pass this test with the following code, knowing it was not following the instructions:
> 
> ```js
> function makeClass() {
>   "use strict";
>   /* Alter code below this line */
> class Thermostat{
>   constructor(temp) {
>     this._temp = temp;
>   }
>   get thermos(){
>     return this._temp;
>   }
>   set thermos(updateTemp){
>     this._temp = updateTemp;
>   }
> }
>   /* Alter code above this line */
>   return Thermostat;
> }
> const Thermostat = makeClass();
> const thermos = new Thermostat(76); // setting in Fahrenheit scale
> let temp = thermos.temperature; // 24.44 in C
> thermos.temperature = 26;
> temp = thermos.temperature; // 26 in C
> ```

How would you test this using console.log? Thanks

**Comment by IssamAth** [comment]
same here i passed the test only by when i thought i'm just starting . it got me so confused, so i'm not the only one . it's 2019 and they still didn't fix that problem ...

```
class Thermostat {
    constructor(Fahrenheit_temperature){
      return this.Fahrenheit_temperature = Fahrenheit_temperature;
    }
  }
```

**Comment by ojeytonwilliams** [comment]
@IssamAth it should have been fixed by https://github.com/freeCodeCamp/freeCodeCamp/pull/36620.  That's live on https://www.freecodecamp.dev/learn/javascript-algorithms-and-data-structures/es6/use-getters-and-setters-to-control-access-to-an-object if you want to try it out.

**Comment by IssamAth** [comment]
@ojeytonwilliams thanks i'll give it a try !

**Comment by certilremy** [comment]
The old issue is gone but there'are some new. 
Here is my code : 

```
class Thermostat {
    constructor(temperature){
      this._temperature = temperature
    }

    get writer() {
        return this._temperature;
      }

    set writer(f) {
        this._temperature = (5/9 * (f - 32));
      }

  }

  const thermos = new Thermostat(76);
  let temp = thermos.temperature;
  thermos.temperature = 26;
  temp = thermos.temperature;
```
got my test fails because of these errors. 

- [ ] Thermostat should be able to be instantiated.
- [ ] A getter should be defined.
- [ ] A setter should be defined. 

But my code works on vs code.

**Comment by RandellDawson** [comment]
@certilremy Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
