### ISSUE TITLE
Update the PropTypes challenge to use React 16

### ISSUE THREAD

**Issue by ooade** [freeCodeCamp/freeCodeCamp#17402]
#### Describe your problem and - if possible - how to reproduce it
Introduce the 'prop-types' package as regards the one from v15+

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react/use-proptypes-to-define-the-props-you-expect/

**Comment by lynxlynxlynx** [comment]
There's a note now:
> Note: As of React v15.5.0, PropTypes is imported independently from React, like this:
> 
> import React, { PropTypes } from 'react';

**Comment by ooade** [comment]
Okay. That seems valid.

**Comment by Vikas-KM** [comment]
Forgive for being naive,
I read the article here [TypeChecking with PropTypes](https://reactjs.org/docs/typechecking-with-proptypes.html) and here [PropTypes](https://www.npmjs.com/package/prop-types) seems like PropType is not part of react core library and the import statement has changed.
This is how they are importing in the articles mentioned above.
> import PropTypes from 'prop-types';

**Comment by ooade** [comment]
Yeah, @Vikas-KM It changed. It's still being managed by the React Team tho.
