### ISSUE TITLE
Basic HTML and HTML5 - Nest an Anchor Element within a Paragraph: First test tracks the href of the wrong <a> element

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#17406]
#### Describe your problem and - if possible - how to reproduce it
The first test ("You need an `a` element that links to `http://freecatphotoapp.com`.") is testing the first `a` element, not the one that the user is supposed to type. It is marked as correct even though the user typed the wrong `href` value.

Somehow this interferes with the 4th and 5th tests.

```html
<h2>CatPhotoApp</h2>
<main>
  
  <a href="http://freecatphotoapp.com" target="_blank">cat photos</a>
  
  <img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">
  
  <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  <p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
</main>

<p>View more <a href="http://www.catphotoapp.com">cat photos</a></p>
```

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph/

##### Relevant forum post
https://forum.freecodecamp.org/t/solved-nest-an-anchor-element-within-a-paragraph-dont-understand-step-4-and-5/195819

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 60.0.1
* Operating System: Manjaro

**Comment by bannon-tanner** [comment]
@kevcomedia The challenge did not want you to write your own `a` element. 
Instead it wanted you to just add the `p` tags with "View more " before it, like so...

```
<h2>CatPhotoApp</h2>
<main>
  
  <p>View more <a href="http://freecatphotoapp.com" target="_blank">cat photos</a></p>
  
  <img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">
  
  <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  <p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
</main>
```

Regardless, I have submitted PR #26441 that changes the wording to hopefully make this more clear to any other campers running in to the same issue

**Comment by RandellDawson** [comment]
@kevcomedia I concur with @bannon-tanner regarding the intent of the challenge.  The user is supposed to nest the existing anchor element in a new p element.   Hopefully, the change from `your` to `the` should make things clearer.  Once we merge @bannon-tanner's PR, we will close this issue.
