### ISSUE TITLE
Basic CSS - Use a custom CSS Variable - Typo in tests

### ISSUE THREAD

**Issue by akkatracker** [freeCodeCamp/freeCodeCamp#17405]
#### Describe your problem and - if possible - how to reproduce it
`penguin` is spelled incorrectly in the first two tests as `pengiun`

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-css/use-a-custom-css-variable

#### Tell us about your browser and operating system
Chrome Canary Windows 10

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/2032746/40882518-fa09efc0-6727-11e8-96c5-d41c7286708d.png)

**Comment by bogadodiegoh** [comment]
I will work on this issue.

**Comment by akkatracker** [comment]
Thanks @bogadodiegoh! Closing
