### ISSUE TITLE
Not passing test- Store Data with Sass Variables.

### ISSUE THREAD

**Issue by vikaschauhan** [freeCodeCamp/freeCodeCamp#17408]
#### Describe your problem and - if possible - how to reproduce it
On Sass Section: In Introduction to Sass Challenges. First Challenge - Sass - Store Data with Sass Variables. I feel i have created solution as per instruction by creating a Sass variable and replacing color for Class blogpost and element h2 from red to variable $text-color whose value set to red.

#### Add a Link to the page with the problem
front-end-libraries/sass/store-data-with-sass-variables

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66
* Operating System: Windows 10

#### If possible, add a screenshot here
![error_sass](https://user-images.githubusercontent.com/3263646/40885104-9a465c34-673d-11e8-8bc9-6e2afb9c6582.JPG)

**Comment by DonMatano** [comment]
Same with me using Chrome in Linux Mint

**Comment by urbanware** [comment]
same with Chrome.  Repeated error on macOS High Sierra and Linux Mint.  Details here and verified by another:  https://forum.freecodecamp.org/t/store-data-with-sass-variables-still-not-working/198013

**Comment by techneplus** [comment]
I am getting the same error too. https://learn.freecodecamp.org/front-end-libraries/sass/store-data-with-sass-variables

**Comment by StewartBenGardner** [comment]
I got this error too, in the tests box it has </code>color</code>. Should it be like <code>color</code>? Maybe there's just a stray "/".

**Comment by sourabh1031** [comment]
I am also facing the same situation .

**Comment by npellow** [comment]
Also having the same issue. I tried doing it as below as well, but it didn't pass either, even though it worked:

`.blog-post {
color: $text-color;
}
h2 {
color: $text-color;
}`

![sassproblem](https://user-images.githubusercontent.com/21061478/41499007-884f51f2-7147-11e8-89f0-c7b5eb5011d3.JPG)

**Comment by petercr** [comment]
Yes I'm having the same error. It seems either there's an error with the unit testing, or maybe the SASS compiler? Not sure but I checked the console and there **were not** any errors. 
I guess everyone should just move on for now

**Comment by mattszcz** [comment]
#12699 root issue

**Comment by mav1283** [comment]
Same here, what happens if you finished everything and can't get your certificate because of this?

**Comment by petercr** [comment]
@mav1283 You **don't need** to finish all of the challenges in order to get the certificate. You only need to  complete the _**final projects**_ at the end of any given section to receive the certificate of completion. 
I just wanted to make sure you knew this 👍 😃

**Comment by muratmer** [comment]
Same issue with Chrome and firefox

**Comment by GadhiMohamed** [comment]
I have the same issue with chrome and firefox ( latest versions )

**Comment by mav1283** [comment]
@GadhiMohamed try the brave browser, if it doesn't work it's ok cause you can go on finish the rest of the projects.

**Comment by moT01** [comment]
This appears to be fixed in [beta](https://www.freecodecamp.rocks/learn/front-end-libraries/sass/store-data-with-sass-variables), so I will close this. If you think it's still a problem feel free to reopen the issue.
