### ISSUE TITLE
Too many scroll bars

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#17415]
There is a lot of scroll bars - makes it feel a little cluttered, and a lot of them probably aren't needed

* Operating System: High Sierra 10.13.4
* Chrome  66.0.3359.181
and
* Firefox 60.0.1
chrome and firefox look and behave identical for me with 10 scroll bars when they are all displayed...

![scrollbars](https://user-images.githubusercontent.com/20648924/40888385-03311abc-671c-11e8-82e8-7f71d37e106d.png)

1. the text wraps - so not needed
2. needed only when the content is tall enough - doesn't disappear when not needed
3. the text wraps - so not needed
4. ... 
5. 4 and 5 both vertical scroll this area and only one would be needed (when the content is tall enough) - I would go with 4 for consistency
6. the text wraps - so not needed
7. needed only when the content is tall enough - doesn't disappear when not needed
8. ...
9. 8 and 9 behave the best - they both disappear when they aren't needed - and reappear when the content doesn't fit
10. this one scrolls the whole page - which would never be needed since each pane scrolls independent of the whole window

<hr>

* Safari 11.1
safari behaves a little differently and shows 13 scroll bars when they are all displayed....

![scrollbars2](https://user-images.githubusercontent.com/20648924/40888760-7ab8668a-6721-11e8-9d38-f66067f95680.png)

1. the text wraps - so not needed
2. needed only when the content is tall enough - doesn't disappear when not needed
3. the text wraps - so not needed
4. ... 
5. 4 and 5 both vertical scroll this area and only one would be needed (when the content is tall enough) - I would go with 4 for consistency
6. the text wraps - so not needed
7. needed only when the content is tall enough - doesn't disappear when not needed
8. ...
9. 8 and 9 like wrap the two sections there - Im not sure why those would ever be needed
10. ...
11. 10 and 11 behave the best - they both disappear when they aren't needed - and reappear when the content doesn't fit
12. ...
13. I think 12 and 13 wrap this area similar to 8 and 9 - I don't think those would ever be needed

<hr>

This is my experience - I think it's pretty accurate

**Comment by huyenltnguyen** [comment]
@moT01 Your Safari screenshot just gave me a heart attack! :scream: I don't even want to know how it looks on IE or Edge. Don't quote me on this, but I think FCC recommends using Firefox and Chrome for a better experience.

I noticed the scrollbars issue, too, and submitted a PR over the learn repo to get rid of the horizontal ones. I didn't really examine the vertical at the time, though, but now that thanks to your post, I think I'll need to take another look.

I'll work on a kind of related issue (#17293) later today, would you mind if I take this one too?

**Comment by moT01** [comment]
@huyenltnguyen Yea, go ahead and work on it - my first thought was to hide the overflow in the css (`overflow-y: hidden`/`overflow-x: hidden`)
