### ISSUE TITLE
Cannot add name to portfolio

### ISSUE THREAD

**Issue by JMVL64** [freeCodeCamp/freeCodeCamp#17410]
#### Describe your problem and - if possible - how to reproduce it
I want to add my name to the portfolio, but hitting save results in an error for me in the console.

#### Add a Link to the page with the problem
https://www.freecodecamp.org/settings

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66
* Operating System: MacOs

#### If possible, add a screenshot here

<img width="996" alt="screen shot 2018-06-03 at 14 02 01" src="https://user-images.githubusercontent.com/23399217/40886367-c2f1f5dc-6736-11e8-9026-cbdba499c662.png">
<img width="1273" alt="screen shot 2018-06-03 at 14 02 09" src="https://user-images.githubusercontent.com/23399217/40886368-c4d35300-6736-11e8-97ad-6c4f0b3a33cc.png">

**Comment by moT01** [comment]
@JMVL64 it seems to be working for me - perhaps its been fixed - is this still happening for you? - if it's working now you should close this issue

**Comment by JMVL64** [comment]
For me it still happens. I just tried. Sorry I did not respond very fast, I have had some busy times. In firefox I see an empty screen with this in the console. In chrome it loads but I cannot change it still.
<img width="1268" alt="screen shot 2018-06-12 at 21 48 37" src="https://user-images.githubusercontent.com/23399217/41313512-682f0d3c-6e8a-11e8-8c52-f58f7a649a7c.png">

**Comment by moT01** [comment]
@JMVL64 Not a problem - just trying to close some issues that have been resolved
