### ISSUE TITLE
Basic JavaScript - Record Collection: Broken Link

### ISSUE THREAD

**Issue by rohitdwivedula** [freeCodeCamp/freeCodeCamp#17416]
There's a broken link in this lesson: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/record-collection
The second line in the "Hints" section says
>Use bracket notation when [accessing object properties with variables](https://learn.freecodecamp.org/accessing-objects-properties-with-variables).
> You may refer back to [Manipulating Complex Objects](https://learn.freecodecamp.org/manipulating-complex-objects) Introducing JavaScript Object Notation (JSON) for a refresher. 

These links are broken, pointing to an error page (shown in screenshot).

* Browser Name: Mozilla Firefox 
* Browser Version: v60
* Operating System: Ubuntu
![screenshot from 2018-06-03 23-58-12](https://user-images.githubusercontent.com/25080952/40889760-01c111dc-678a-11e8-8d95-b8abecf8d6b2.png)

**Comment by hbar1st** [comment]
when will the fix be published?
