### ISSUE TITLE
Type issue in directions

### ISSUE THREAD

**Issue by KoniKodes** [freeCodeCamp/freeCodeCamp#17420]
#### Describe your problem and - if possible - how to reproduce it
penguin class should declar the --penguin-skin variable and assign it to gray.
penguin class should declar the --penguin-skin variable and assign it to white.
penguin class should declar the --penguin-skin variable and assign it to orange.

On all three statements, "declar" should read "declare"
Also notice the "--penguin-skin" variable does not change to reflect "--penguin-belly" or "--penguin-beak"

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-variables-to-change-several-elements-at-once

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System: 

#### If possible, add a screenshot here
![fcc-penguin](https://user-images.githubusercontent.com/18405001/40890884-c5fa9eb4-6731-11e8-9c2c-6f18e0620a1b.jpg)

**Comment by absolitudo** [comment]
> Also notice the "--penguin-skin" variable does not change to reflect "--penguin-belly" or "--penguin-beak"

I'm pretty sure that's intentional, but the variable name is not precise. I would suggest renaming the "--penguin-skin" variable to "--penguin-back" or "--penguin-dorsal-skin" or "--penguin-dorsal-feather", something along the lines. Although I don't think it's necessary.(penguins have feather btw)

**Comment by KoniKodes** [comment]
Really? The var name in the style section reads:
     /* change code below */
    --penguin-skin: black;
    --penguin-belly: gray;
    --penguin-beak: yellow;
    /* change code above */
 
But in the instructions it has all --penguin-skin. The instructions are usually fairly precise on what var should be changed to which assignment. 

Did not know that about penguins and feathers (but it makes sense if we are thinking they are birds)

**Comment by KoniKodes** [comment]
I think it should read:
penguin class should declare --penguin-skin variable and assign it to gray.
penguin class should declare --penguin-belly variable and assign it to white.
penguin class should declare --penguin-beak variable and assign it to orange.

**Comment by Vimal-Raghubir** [comment]
Hi @KoniKodes. I decided to check the link you sent above and this is a screenshot of what I see. I am not sure where you are getting this issue.

![tutorial](https://user-images.githubusercontent.com/25648267/40998217-0aa962e4-68d5-11e8-9fa1-bed34cdb44c1.PNG)

**Comment by absolitudo** [comment]
@KoniKodes you are right I misunderstood the problem, however, I think this issue has been fixed, for me it's correctly displayed. Is it still an issue on your part?

**Comment by KoniKodes** [comment]
Wonderful! It's been fixed.

Thank you so much!

**Comment by Phil12sk** [comment]
In this lesson, I don't know if I don't understand or there is an error. I just can't pass through!!
![image](https://user-images.githubusercontent.com/29265307/45727457-34344a80-bb9a-11e8-825c-7ed809781a64.png)

**Comment by Phil12sk** [comment]
The error continues when I add the "background"
![image](https://user-images.githubusercontent.com/29265307/45769404-e2310a80-bc15-11e8-86c3-3dfe8cf15c9d.png)

**Comment by KoniKodes** [comment]
This seems to be a problem both in Chrome and Firefox. Now on my page, the background stays the original pink color and does not change to #c6faf1 - and the message says to do what we are supposed to do.
![error](https://user-images.githubusercontent.com/18405001/45775566-f91b3100-bc04-11e8-968c-abb28fb92d07.png)

**Comment by moT01** [comment]
Perhaps the instructions aren't clear. You are supposed to `Change the value of --penguin-belly to white in the penguin class.`
like this...
```css
  .penguin {
    /* add code below */
    --penguin-belly: white;
    /* add code above */
```
Since the original issue here has been fixed, I am going to close this. Feel free to create a new issue if either of you think the instructions need to be reworded. Thanks!

**Comment by a-wip0** [comment]
doesn't work @moT01 your solution doesn't work, even after i change `background: var(--penguin-belly, pink);` to `background: var(--penguin-belly, white);`

**Comment by avery-windham** [comment]
I'm running into an issue where the correct answer is not allowing me to complete the segment.

Code:

<style>
  :root {
    --penguin-skin: gray;
    --penguin-belly: pink;
    --penguin-beak: orange;
  }

  body {
    background: var(--penguin-belly, #c6faf1);
  }

  .penguin {
    /* Only change code below this line */
    --penguin-belly: white;
    /* Only change code above this line */
    position: relative;

Check:
// running tests
The penguin class should reassign the --penguin-belly variable to white.
// tests completed

**Comment by miku86** [comment]
@avery-windham

If I do what the instructions say, I pass the tests.

Please go to the [FreeCodeCamp Forum](https://forum.freecodecamp.org/) and open a topic.

Github issues are only for technical issues, not for asking for lesson-specific help. :slightly_smiling_face:

**Comment by TharisikaSivaraja** [comment]
.penguin {

    **/* Only change code below this line */
    --penguin-skin: _gray_;
    --penguin-belly: _white_;
    --penguin-beak: _orange_;
    /* Only change code above this line */**

    position: relative;
    margin: auto;
    display: block;
    margin-top: 5%;
    width: 300px;
    height: 300px;
  }
![Screenshot from 2021-07-27 08-22-02](https://user-images.githubusercontent.com/86947734/127087704-78c40060-e5c8-45e5-ad49-eba43e34df41.png)
