### ISSUE TITLE
Navbar dropdown will not close after opening

### ISSUE THREAD

**Issue by JonDevOps** [freeCodeCamp/freeCodeCamp#17428]
#### Describe your problem and - if possible - how to reproduce it

When I click the menu button, the dropdown will open, then when i reclick the menu button, the drop-down menu refuses to close. 

#### Add a Link to the page with the problem

Freecodecamporg - Home/landing page

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: Firefox for Android. Version 60.0.1
* Operating System: Android version 70.1.1

**Comment by aditijoshi14** [comment]
@JonDevOps Are you still facing this problem? If not, we could close this issue.

**Comment by JonDevOps** [comment]
No i am not. Let's close it
