### ISSUE TITLE
Object Oriented Programming - Understand Own Properties: Can pass with Object['keys']

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#17427]
#### Describe your problem and - if possible - how to reproduce it
The exercise is not supposed to be solved using the `Object.keys` function, but it can be solved with bracket notation (`Object['keys']`).

```js
function Bird(name) {
  this.name = name;
  this.numLegs = 2;
}

let canary = new Bird("Tweety");
let ownProps = [];
// Add your code below this line
ownProps = Object['keys'](canary);
```

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/understand-own-properties

**Comment by HOTNFIT** [comment]
function Bird(name) {
  this.name = name;
  this.numLegs = 2;
}

let canary = new Bird("Tweety");
let ownProps = [];
// Add your code below this line
for (let property in canary) {
  if(canary.hasOwnProperty(property)) {
    ownProps.push(property);
  }
}

console.log(ownProps); // prints [ "name", "numLegs" ]
/////

Can i please get a commit for this as this is my first time using Github. I am disabled and need this done as part of my assignment for university. I am willing to do more if this is not enough as i must complete one programming exercise  of my choice. 

I hope this qualifies and i can get a commit. If not can you signpost me to where i can? 

Kind Regards 

Amit Sharma

**Comment by HOTNFIT** [comment]
![image](https://user-images.githubusercontent.com/44776731/49802846-106e4400-fd46-11e8-8b07-43fb05f42e98.png)


The above is the image of me completing exercise i hope you can give me a commit.

Kind Regards 

Amit Sharma
