### ISSUE TITLE
Fix typo in an Applied Visual Design Challenge

### ISSUE THREAD

**Issue by MGuadagno** [freeCodeCamp/freeCodeCamp#17421]
#### Describe your problem and - if possible - how to reproduce it

In the Applied Visual Design challenge named "Use a Bezier Curve to Move a Graphic" there is a typo. 
As you can see, in the paragraph: 
"Remember that all cubic-bezier functions start with p0 at (0, 0) and end with p3 at (1, 1). In this example, the curve moves faster through the Y-axis (starts at 0, goes to p1 y value of 0, then goes to p2 y value of 1) then it moves through the X-axis (0 to start, then 0 for p1, up to 0.58 for p2)."
there should be a "than it moves through" instead of a "then it moves through" because we are making a comparison.

I was going to edit the typo myself with a fork but I am fairly inexperienced with git and github, so I preferred to put an issue. I know it is just a stupid typo.

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-a-bezier-curve-to-move-a-graphic/

#### Tell us about your browser and operating system

* Browser Name:  Firefox
* Browser Version: 60
* Operating System: Windows 10

**Comment by agbales** [comment]
Thanks for catching this, @MGuadagno. I'll fix the typo.
