### ISSUE TITLE
Should clicking the Forum link on the navbar open a new tab?

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#17434]
#### Describe your problem and - if possible - how to reproduce it
The link to the forum on the upper right of the page opens the forum on the same tab. People going to the forum from that link might try looking for a link back to the main site from the forum.

Some suggestions:
* The forum opens in a new tab
* There's a link in the forum that goes back to the primary site

#### Relevant forum post:
https://forum.freecodecamp.org/t/how-do-you-leave-the-freecodecamp-forum-once-you-enter-it/196337

**Comment by RoniqueRicketts** [comment]
Possible fix for developers target="_blank" on that forum link

**Comment by raisedadead** [comment]
Yes. Agreed.

**Comment by EdwinCoding1001** [comment]
On Jun 4, 2018 1:35 PM, "mrugesh mohapatra" <notifications@github.com>
wrote:

Yes. Agreed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/freeCodeCamp/freeCodeCamp/issues/17434#issuecomment-394436118>,
or mute the thread

**Comment by brainlulz** [comment]
Please remind to add rel="noopener noreferrer" when adding a target="_blank"

**Comment by raisedadead** [comment]
> Please remind to add rel="noopener noreferrer" when adding a target="_blank"

I think that is irrelevant in this case? We are not linking to an external site but our own forum whose code we control? Unless I missed something?

**Comment by RoniqueRicketts** [comment]
I thought target="_blank" is ok for the current task.

**Comment by vikramnr** [comment]
@raisedadead Should we update the target to _blank is someother places since this is already in place the views [freeCodeCamp/server/views/partials/navbar.jade]
Also in the below target seems to updated from json file
[freeCodeCamp/common/app/Nav/Nav.jsx]

**Comment by brainlulz** [comment]
@raisedadead Ineed it's not an external site link but it's a good practice to add this. This may prevent security issues for future changes.
