### ISSUE TITLE
Completed Waypoint: Reuse Code with Decorators won't advance to next waypoint. 

### ISSUE THREAD

**Issue by dangm24** [FreeCodeCamp/FreeCodeCamp#1743]
When I check off all the boxes in the list and hit the "I've completed this challenge" green button, the page refreshes. My map doesn't indicate that the Waypoint has been completed. This bug is present even when the boxes are unchecked. The Congratulations alert pops up and then I can't advance onto the next way point.

**Comment by BerkeleyTrue** [comment]
Please give context to the issue. What browser/OS are you using? Are you on beta or on the main site?

**Comment by dangm24** [comment]
I'm on the main site, using Chrome Version 44.0.2403.130 m on Windows 7 Home Premium.

**Comment by benschenker** [comment]
Hey @dangm24 is this still an issue for you?

**Comment by awesomeaniruddh** [comment]
Closing this because it seems to be non-issue. Please feel free to reopen if it still is an issue :)
