### ISSUE TITLE
Lesson links in search failing

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#17439]
When you use the search feature and open **some** of the lesson results - they give a `Not Found` error... I think it's only lessons that no longer exist maybe? I didn't have a problem with any of the `guide` or `youtube` links I tried

* Browser Name: Firefox
* Browser Version: 60.0.1
* Operating System: High Sierra 10.13.4

<hr>

<img width="1195" alt="screen shot 2018-06-04 at 6 05 36 pm" src="https://user-images.githubusercontent.com/20648924/40946245-129f7c62-6822-11e8-9e1f-b6d89e1e158a.png">

<hr>

<img width="1199" alt="screen shot 2018-06-04 at 6 05 20 pm" src="https://user-images.githubusercontent.com/20648924/40946249-14e69352-6822-11e8-97b2-c2611b4613b5.png">

<hr>

It's about half of the lesson links here that take you to the `not found` page - the other half seem to work fine - same problem with the few other queries I tried.

**Comment by jonathan-grah** [comment]
Hey @moT01, this has already been reported over [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/17304) as part of the broader issue so I'm gonna close this as a duplicate.
