### ISSUE TITLE
Missing Error Message

### ISSUE THREAD

**Issue by sdabhi23** [freeCodeCamp/freeCodeCamp#17437]
#### Describe your problem and - if possible - how to reproduce it
Even when we successfully complete [Create Many Records with model.create()](https://learn.freecodecamp.org/apis-and-microservices/mongodb-and-mongoose/create-many-records-with-model-create) challenge there's no pop-up showing that I have completed it successfully. Also it does not show up in the curriculum either as completed.

All the tests are passing without any error, as you can see in the screenshot below:
![image](https://user-images.githubusercontent.com/25759344/40936171-1eeac040-6858-11e8-8184-d2138a86038a.png)

Also, the Ctrl+Enter shortcut isn't working on some of the pages.

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.62
* Operating System: Windows 10

**Comment by moT01** [comment]
There is a message there showing the test didn't pass. I'm not sure what more you are expecting, but I don't think this is an issue, so I am going to close it for now. If you think it's still a problem feel free to reopen it and add further details. Thanks and happy coding!
