### ISSUE TITLE
Sass resource

### ISSUE THREAD

**Issue by TheJaredWilcurt** [freeCodeCamp/freeCodeCamp#17438]
Hey there, I help run the Free Code Camp meetup group in Indianapolis, IN, USA. I'm also the maintainer for Scout-App. Scout-App is cross-platform (Win/Lin/OSX) desktop app for easily processing Sass files to CSS without needing any knowledge of the command line. It's a good tool for beginners, and has been translated to 26 languages.

Just thought I'd mention it as a resource in case you wanted to link to it. It's free and open source.

* http://scout-app.io

Or you can link to the Sass Language website's page for instructions on installing Sass (which also lists Scout-App).

* https://sass-lang.com/install

**Comment by thecodingaviator** [comment]
Thank you for the offer @TheJaredWilcurt , I don't see where we can fit this reference in a.t.m., maybe you can close the issue for now?

@QuincyLarson or @raisedadead I'd like to get your opinion on the same
