### ISSUE TITLE
"Get a Hint" button missing

### ISSUE THREAD

**Issue by ohdaisies** [freeCodeCamp/freeCodeCamp#17431]
#### Describe your problem and - if possible - how to reproduce it
Used to have a "Get a Hint" button on all the questions but now I have to post to the forum to find my answer by asking people, and I can only ask 3 questions a day. This slows down my learning speed a lot.

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by supuun** [comment]
"We are working on adding the hint buttons back in." - Quincy Larson
https://forum.freecodecamp.org/t/10-major-freecodecamp-improvements-that-are-live-now/192130

**Comment by moT01** [comment]
Thank you for reporting this issue.

    It looks like the `Get a hint` button is back so I am closing this issue.

    If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
