### ISSUE TITLE
Use React to Render Nested Components - Editor locks up and crashes browser

### ISSUE THREAD

**Issue by hagnerd** [freeCodeCamp/freeCodeCamp#17448]
#### Describe your problem and - if possible - how to reproduce it
Completed the challenge and clicked "Run The Tests", the editor locked up, and then the browser crashed. 
I reloaded the challenge and my code was still in there. 

This time the editor was locked up and crashed out as soon as I loaded the challenge page. 

I cleared my browser cache/cookies and restarted my computer, but the challenge is still locked up.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react/use-react-to-render-nested-components
#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Mac OS 10.13.4

**Comment by datsik34** [comment]
Works fine on my PC too.
Try with another explorer and see if it does the same. Chrome Extentions can also be the problem here. Deactivates all of them and try again. Good luck !

**Comment by hagnerd** [comment]
Cleared cache three times and then it worked in Chrome.
