### ISSUE TITLE
Bar Chart - Tooltip Testing

### ISSUE THREAD

**Issue by GlynL** [freeCodeCamp/freeCodeCamp#17440]
I have seen a similar issue opened which was closed without discussion. This is very confusing in the user story. The method taught in the FCC curriculum (appending a title for the tooltip) is not accepted as a solution and the user story does not provide any information that it shouldn't be done this way.

User Story #12: I can mouse over an area and see a tooltip with a corresponding id="tooltip" which displays more information about the area.
User Story #13: My tooltip should have a data-date property that corresponds to the data-date of the active area.

https://learn.freecodecamp.org/data-visualization/data-visualization-projects/visualize-data-with-a-bar-chart

**Comment by Fordco** [comment]
I don't think this is as much an issue as it is a misunderstanding. I think this post should be in the forum and not the issue tracker, unless you think more tutorials should be added concerning tooltips. 
Thoughts?

**Comment by RandellDawson** [comment]
@GlynL Without seeing the code you have tried, it is very difficult to answer your question.  Please take @Fordco's advice and post your question and a link to your code on the forum.  If you still think there is an issue with the challenge instructions or description, you can request this issue to be reopend, but please be prepared to tell us how best to present it.

Thank you.
