### ISSUE TITLE
typo in CSS Grid - Use Media Queries to Create Responsive Layouts

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#17449]
#### Challenge
https://learn.freecodecamp.org/responsive-web-design/css-grid/use-media-queries-to-create-responsive-layouts

![screen shot 2018-06-05 at 11 24 44 am](https://user-images.githubusercontent.com/20648924/40997062-14182e48-68c9-11e8-8ad0-5fbb87884ed1.png)

`grid-template-columns` should say `grid-template-areas`

this should be changed in the seed file in two spots - these two lines...
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/css-grid.json#L1330
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/css-grid.json#L1331

**Comment by mmhuntsberry** [comment]
Hello!  

First time contributor wanting to help.  Made the asked for changes and submitted a pull request.  Please let me know if it's incorrect.  Thanks

**Comment by Atik-Sarker** [comment]
how to solve this? please help me
