### ISSUE TITLE
freecodecamp using googleapis CDN which is blocked in China

### ISSUE THREAD

**Issue by naibaben** [freeCodeCamp/freeCodeCamp#17442]
#### Describe your problem and - if possible - how to reproduce it

Google Jquery is not accessible for China
https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js

#### Tell us about your browser and operating system

* Browser Name: Google chrome
* Browser Version: 66.0.3359.181
* Operating System: Windows 10

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/39952042/40975542-e92b9118-68fd-11e8-843d-6e391f4ff7fe.png)

**Comment by QuincyLarson** [comment]
Thanks for the feedback. We could refactor this to use a different font. Can you still pass the challenge without getting the CDN link to work?

**Comment by MartinKolarik** [comment]
@QuincyLarson the issue is about jquery, not fonts.

**Comment by AbdulrahmanEng** [comment]
This article might help: https://weblogs.asp.net/jongalloway/using-cdn-hosted-jquery-with-a-local-fall-back-copy. @QuincyLarson.

**Comment by AbdulrahmanEng** [comment]
@naibaben, have you tried using the site through a VPN (virtual private network).

**Comment by MartinKolarik** [comment]
I'd suggest using a China-friendly CDN like [jsDelivr](https://www.jsdelivr.com) instead. Using a local copy would be very slow for people in China and is unnecessary complicated.

**Comment by raisedadead** [comment]
Issue moved to [freeCodeCamp/learn #155](https://github.com/freeCodeCamp/learn/issues/155) via [**ZenHub**](https://www.zenhub.com/)
