### ISSUE TITLE
Issue with counter

### ISSUE THREAD

**Issue by orismanager** [FreeCodeCamp/freecodecamp#1744]
I am on Waypoint: Size your Images and the counter in the upper right hand corner says 78. Is that counter supposed to correspond to the number of exercise you are on? If so, then something isn't right because when I finish an exercise, it never moves. It just stopped at 78.

**Comment by cristianvnica** [comment]
Hi @orismanager. If this is the counter are you talking about:

<img width="428" alt="screen shot 2015-08-13 at 9 19 30 am" src="https://cloud.githubusercontent.com/assets/3229023/9243701/8d8acde6-419c-11e5-9421-1d5e72324bbc.png">

I believe it shows how many credits you got for completing the challenges, not the number of the exercise.

**Comment by orismanager** [comment]
Cristian, 

Thanks for the quick response. That makes me feel better to be certain.
Could you answer one more question? Someone asked me if I was on the production or beta site.
How would I know the difference and does it matter?
I guess that qualifies as 3 questions technically.

Thanks Again,

Tom

**Comment by cristianvnica** [comment]
There is the main website `www.freecodecamp.com` (i believe this is called production), where everything should be functional and stable, and where we are advised to learn coding..

..and a beta website `beta.freecodecamp.com` which means something like:
`
The beta site is a testing site, not complete, and certainly not replacing the previous site. During this beta phase, we are working hard to polish everything - the content, the navigation, the layout, and more. We are listening to feedback closely, trying to improve the site as quickly as possible.
`

**Comment by BerkeleyTrue** [comment]
@orismanager Hope that answers your question.

Happy Coding!
