### ISSUE TITLE
search bar

### ISSUE THREAD

**Issue by cmat27** [freeCodeCamp/freeCodeCamp#17453]
when user uses the search bar, it drops down multiple option/matches, but if user does not select one and clicks outside of it the drop down doesn't close unless the user deletes the search criteria. 

acceptance criteria > if user does not select one of the options and clicks outside the drop down. drop down should close 

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by jonathan-grah** [comment]
@cmat27, Hey this definitely needs sorting out, but this has already been reported so I'm gonna close it as a duplicate 👍
