### ISSUE TITLE
Weird extra drag line at extreme right of page

### ISSUE THREAD

**Issue by coolshaurya** [freeCodeCamp/freeCodeCamp#17458]
This weird extra drag line appears at the extreme right of  the page. It can be confused with the console drag line which changes the width of the console. When dragging this line , it fills the console with errors - <br>
![image](https://user-images.githubusercontent.com/32027323/41031171-a756cf50-699d-11e8-9625-b2dc4be5914b.png)

#### Browser and operating system -

* Browser Name:  Google Chrome
* Browser Version: 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Windows 10 Fall Creators Update

#### Screenshot - 
![2018-06-06 15_17_00-window](https://user-images.githubusercontent.com/32027323/41031414-30ee303c-699e-11e8-8979-7041949f06ab.png)

![image](https://user-images.githubusercontent.com/32027323/41030501-1c871246-699c-11e8-8d2d-4b625421b62d.png)

**Comment by raisedadead** [comment]
Issue moved to [freeCodeCamp/learn #152](https://github.com/freeCodeCamp/learn/issues/152) via [**ZenHub**](https://www.zenhub.com/)
