### ISSUE TITLE
Not enough padding on the curriculum page (mobile)

### ISSUE THREAD

**Issue by ayoisaiah** [freeCodeCamp/freeCodeCamp#17457]
[The curriculum page](https://learn.freecodecamp.org/) does not have enough on mobile browsers.

![](https://i.imgur.com/cmicise.png)

And I think the list of challenges should be centered with enough padding between the text and the edges of the screen

![](https://i.imgur.com/54vOccg.png)

**Comment by raisedadead** [comment]
Issue moved to [freeCodeCamp/learn #156](https://github.com/freeCodeCamp/learn/issues/156) via [**ZenHub**](https://www.zenhub.com/)
