### ISSUE TITLE
Auth0 - jQuery CDN needs to be replaced

### ISSUE THREAD

**Issue by Wood-Cube** [freeCodeCamp/freeCodeCamp#17456]
#### Describe your problem and - if possible - how to reproduce it
Can't sign in after update,while I can sign in fcc forum as well using my account.

#### Tell us about your browser and operating system

* Browser Name: chrome /edge 
* Browser Version: 
* Operating System: 

#### If possible, add a screenshot here
<img width="500" alt="_20180606151855" src="https://user-images.githubusercontent.com/38563904/41022830-4a9478e4-699d-11e8-9eb7-ea1f638618e3.png">

**Comment by raisedadead** [comment]
hi @Wood-Cube can you please send me an email `mrugesh at freecodecamp dot org` with all of the below details:

1. Screenshots of the Chrome DevTools (Press <kbd>F12</kbd> on Windows/Linux OR <kbd>Cmd + Options + I</kbd> on macOS) and check the console tab.

2. The general region where you are located.

3. Exact steps that you were trying to follow when you get this error.

**Comment by raisedadead** [comment]
![image](https://user-images.githubusercontent.com/1884376/41038213-20c7e65c-69b3-11e8-80f4-0e7a08cf2fd3.png)

**Comment by raisedadead** [comment]
Closed by https://github.com/freeCodeCamp/auth0-templates/pull/4

**Comment by raisedadead** [comment]
@Wood-Cube this should have been resolved now. Can you please try again?

**Comment by Wood-Cube** [comment]
@raisedadead  非常感谢

**Comment by raisedadead** [comment]
You are welcome @Wood-Cube
