### ISSUE TITLE
Page content hidden behind top navbar

### ISSUE THREAD

**Issue by numoonchld** [freeCodeCamp/freeCodeCamp#17455]
#### Describe your problem and - if possible - how to reproduce it

When progressing to a new challenge after completing the current one, when the new page loads, the title of the challenge and some of the content at the top of the page gets hidden behind the green navbar. 

This is counter UI-flow as it prevents the user from the seeing the title of the new challenge after the challenge auto loads and everything. 

This doesn't happen when accessing a challenge directly from the curriculum, only when progressing through challenges using Ctrl+Enter.

#### Add a Link to the page with the problem

I'm noticing this in the Applied Visual Design section. 

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 60.0.1
* Operating System: macOS

#### If possible, add a screenshot here

![screen shot 2018-06-06 at 11 55 11 am](https://user-images.githubusercontent.com/17598505/41020452-8efa1b64-6980-11e8-9b9a-a0f03f672bad.png)

**Comment by raisedadead** [comment]
Issue moved to [freeCodeCamp/learn #153](https://github.com/freeCodeCamp/learn/issues/153) via [**ZenHub**](https://www.zenhub.com/)

**Comment by numoonchld** [comment]
This issue was temporarily fixed (in the Applied Visual Design section) 
- however, now, I see it in the "Applied Accessibility" section as well.

**Comment by numoonchld** [comment]
This not fully resolved.

**Comment by Limonkufu** [comment]
Although issue is moved to https://github.com/freeCodeCamp/learn/issues/153 and is closed there. I am still having this issue with ctrl+enter.
