### ISSUE TITLE
Legacy projects should remain totally intact

### ISSUE THREAD

**Issue by misterhtmlcss** [freeCodeCamp/freeCodeCamp#17452]
We were told we'd be able to finish the curriculum as it was when we signed up, the new curriculum has many different pass criteria and this isn't fair to those of us. We are (most of us) deep into the curriculum and to change the pass criteria at this stage often forcing us to do remedial training so to speak isn't fair. We shouldn't have to do a different version of something that the rest of our peers had to do. 

Please roll back and allow us to click directly from our profile settings area to the projects that are relevant for our curriculum; it's not an unreasonable ask considering we were told we would be able to retain our curriculum and this is absolutely a necessary component to keep that promise.

**Comment by raisedadead** [comment]
Hi @misterhtmlcss 

I was checking this and actually you should still be able to claim all the certifications as would previously.

We are just calling them Legacy certifications.

On your settings page you should have a section for the legacy projects, when you enter the required project URLs you should be able to claim them.

I understand this can probably be made more clear to users.
