### ISSUE TITLE
The “real” privacy setting?

### ISSUE THREAD

**Issue by numoonchld** [freeCodeCamp/freeCodeCamp#17454]
#### Describe your problem and - if possible - how to reproduce it

Redundant entries for making profile completely private - slightly confusing. 

#### Add a Link to the page with the problem

Go to the "Privacy Settings" section of this page. 
https://www.freecodecamp.org/settings

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 60.0.1
* Operating System: macOS 10.13.5

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/17598505/41016381-915aefbe-696c-11e8-8008-2a97293b6fe4.png)

**Comment by jonathan-grah** [comment]
@numoonchld, the profile is the user page as a whole, whereas the portfolio is a part of the profile where there are addable elements for projects, pull requests and articles completed by a user (different things).

**Comment by numoonchld** [comment]
Thanks for the explanation.
