### ISSUE TITLE
Remove information redundancy challenge testing?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#17466]
![screen shot 2018-06-05 at 11 57 18 am](https://user-images.githubusercontent.com/20648924/41044240-6c56213a-696b-11e8-9c97-9683c83caa9d.png)

The information given in these two area seems redundant - In my opinion, the box on the right should be removed - it would make it look cleaner and most of the information there is given in the area on left - or possibly combine these two areas into one somehow - anyone else with thoughts on this?

* Browser Name: Firefox
* Browser Version: 60.0.1
* Operating System: High Sierra

**Comment by raisedadead** [comment]
I think that the console area need not be there on the HTML challenges where you would have NO logs.

That said, I would like to add this as a key on the seed side and render the UI based off that.
/cc @Bouncey

**Comment by moT01** [comment]
@raisedadead im curious what `logs` would show up down there that would be relevant? For the most part the rest of the challenges seem the same, just a repeat of what is shown on the left...  the `console.log()` stuff doesn't show up down there (for me anyway on firefox) - The react challenges were the only ones I noticed that we're slightly different but basically the same - perhaps there's other stuff I don't know about as I haven't done all the challenges or played with it too much - I do like the visual queues that show `running test` and `tests completed` so you know what is happening

**Comment by raisedadead** [comment]
Yup, we had a feature in mind to get the console.log to register and display the output on the panel as well for the javascript challenges.

**Comment by raisedadead** [comment]
This was the case before on the older platform and has been missing since in the new platform

**Comment by Bouncey** [comment]
It is on the roadmap to bring the functionality back. 

There is also to use case where a user places a console.log inside a script tag.

**Comment by moT01** [comment]
Yea, the logging functionality is nice - if it's decided to remove it for certain sections they would probly be the whole `Responsive Web Design Certification` and the `Bootstrap` and `SASS` challenges

**Comment by raisedadead** [comment]
Yes, thats why we want to be explicitly set in the challenge seed as a key, and render the UI on learn based on the key.

**Comment by moT01** [comment]
Closing, since it looks like this isn't going anywhere for the foreseeable future.
