### ISSUE TITLE
Optimize learn platform UX for mobile devices.

### ISSUE THREAD

**Issue by jsmolla** [freeCodeCamp/freeCodeCamp#17467]
#### Describe your problem and - if possible - how to reproduce it
Since the major update last week, FCC no longer appears optimized for mobile devices.  

The text needs left margins set, as it is flush against the left side of the screen and difficult to read. 

In addition, the code editor is extremely small on mobile devices, as it is sharing space with the five other panes, and is extremely difficult to expand.  

Prior to the update, the mobile view was much more functional.  

Aside from this, thanks for everything you've given us with the great new update!
 
![fcc - editor window](https://user-images.githubusercontent.com/39997520/41046130-d0caf846-6977-11e8-97fd-c14180a1ab09.png)

 
#### Tell us about your browser and operating system
I'm use Chrome on Android Marshmellow.  
* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by raisedadead** [comment]
Hi @jsmolla 

Thanks a lot for the issue report. And glad to know that you like the new curriculum. This new challenge platform has been written ground up and shares very little code from the previous version.

That said we know that it lacks support for a wide wide variety of platforms.

On a really honest note this might be a while when we are so focused on bringing the new platform to a stable state. There are a lot of competing support issues that still need to be addressed.

We are committed and doing our very best to get the platform to be highly performant.

So, I would request you to bear with us. We cant promise a date, but we will get there.
Until then we request using it on a desk device if you can as a work around.

Happy coding!

**Comment by supuun** [comment]
@jsmolla did you try landscape mode

**Comment by jsmolla** [comment]
Yes, although landscape mode is somewhat better, when I want to type in the
code editor, the keyboard display covers so much space, you can really only
see the line of code your typing, and not the code above or below it.

I do most of my coding on a desktop, so this is far from a deal breaker for
me.  I did enjoy being able to study a challenge on my phone on my lunch
break, but again, I'm not complaining, just reporting the issue because I
just love FCC and want to see it continue to thrive!

Cheers, it's almost Friday!! :)

**Comment by estebanborai** [comment]
For me the solution here is to be able to hide the panels. Let the user choose the panel they want to see just like JSBin. This way we can reuse the current layout and be able to use it with the phone using the whole screen the way the user spects to use it. Letting you "turn off" the panels you dont want to use.

**Comment by thisisabhinay** [comment]
@jsmolla Please assign this to me. I love to tackle this kind of UX problems and will also make changes in frontend code

**Comment by thisisabhinay** [comment]
I'll take this issue from here @QuincyLarson

**Comment by Nirajn2311** [comment]
@dmytroyarmak First of all I would like to say that the design you have made in the PR is 🔥 . Also is it possible to do the same design for tablets, maybe instead of displaying one tab you could display two tabs in the screen.
