### ISSUE TITLE
A lot slower now on my tablet

### ISSUE THREAD

**Issue by Shidigital** [freeCodeCamp/freeCodeCamp#17461]
#### Describe your problem and - if possible - how to reproduce it

I see nice improvements, but it makes the FreeCodeCamp very slow on my ASUS Transformer tablet, it was really good before the changes. 
Maybe add possibility to switch off some of the new features, like making all the windows smaller and bigger, which is nice but takes a lot ressources it seems. 
Also some corruption going on with the vertical scrollbar now, as shown in the picture below.

#### Tell us about your browser and operating system

* Browser Name: Firefox for Android
* Browser Version: 60.0.1
* Operating System: Android 4.4.2 on a ASUS Tablet K00C

#### If possible, add a screenshot here
The corruption on the scrollbar:
![screenshot_2018-06-06-15-44-09](https://user-images.githubusercontent.com/26897131/41042186-49f976ce-69a1-11e8-8d2c-5b997fbc2fb7.jpg)

**Comment by supuun** [comment]
have you tried another browser?

**Comment by Shidigital** [comment]
Now I did. On Chrome it works very good! Fast and good looking!
Did not expect that much of a difference. 
My mistake not trying it first. Maybe I use Chrome now more often. 
Thank you!

**Comment by supuun** [comment]
You're welcome. I love Firefox, but it's android browser needs some work. It may also be fcc's issue. I don't really know.

**Comment by juandesouza** [comment]
the scrollbar of the middle frame is a problem of the fCC website. It also presents problems when using chrome on the computer. the scroll bar stays static, no matter the amount of content we have inside the frame. The only way I found of moving down the content was using the scroll wheel of the mouse.

**Comment by thecodingaviator** [comment]
@Shidigital Is it fine now? If not, please reply with the issues you are still facing, if any, else close the issue

**Comment by moT01** [comment]
Thanks you for reporting this issue @Shidigital, these are some good suggestions. I am closing this for now since it does not cover specific issue. If any of these problems are still a concern you can open a new issue for each of them. Thanks and happy coding!
