### ISSUE TITLE
Unable to continue coding challenges

### ISSUE THREAD

**Issue by shabbas** [freeCodeCamp/freeCodeCamp#17460]
#### Describe your problem and - if possible - how to reproduce it
After signing in, when i click on "Go to the coding curriculum" button, it takes me to https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/add-images-to-your-website which always appear broken. I have tried this on Chrome, Safari and Firefox but the page did not load anywhere.

I dont use any proxies and do not work on this when i am connected on VPN but i still face this continuous error.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/add-images-to-your-website

#### Tell us about your browser and operating system

* Browser Name: Chrome | Safari
* Browser Version: 66.0.3359.181 (Official Build) (64-bit) | Version 11.0.3 (11604.5.6.1.1)
* Operating System: OS X El-Capitan 10.11.6

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/39991260/41035231-7493c5d4-69a5-11e8-81e1-830b1ab6398e.png)

**Comment by raisedadead** [comment]
See #17360
