### ISSUE TITLE
Problem with Debugging - Understanding the Differences between the freeCodeCamp and Browser Console

### ISSUE THREAD

**Issue by Saymon85** [freeCodeCamp/freeCodeCamp#17468]
#### Describe your problem and - if possible - how to reproduce it
I have a problem with a task Debugging - Understanding the Differences between the freeCodeCamp and Browser Console, i will write here my code and error I receive. I can't pass chalenge. 

`// Open your browser console
let outputTwo = "This will print to the browser console 2 times";
// Use console.log() to print the outputTwo variable
console.log(outputTwo);

let outputOne = "Try to get this to log only once to the browser console";
// Use console.clear() in the next line to print the outputOne only once
console.clear();

// Use console.log() to print the outputOne variable
console.log(outputOne);`

Error which I receive is:

// running test
invalid regexp group
// tests completed

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/debugging/understanding-the-differences-between-the-freecodecamp-and-browser-console/

#### Tell us about your browser and operating system

* Browser Name: Firefox DeveloperEdition 
* Browser Version: 56.0b3 (32-bit)
* Operating System: Windows 7 64bit SP1 with latest updates

**Comment by LTKills** [comment]
This was already addressed in #17387 (Debugging - Understanding the Differences between the freeCodeCamp and Browser Console / Firefox bug)
