### ISSUE TITLE
Javascript displayed in HTML output frame when editing HTML

### ISSUE THREAD

**Issue by camachado** [freeCodeCamp/freeCodeCamp#17476]
#### Describe your problem and - if possible - how to reproduce it
While editing HTML in the code edit frame, Javascript is displayed in the HTML output frame

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.62 (Official Build) (64-bit)
* Operating System: Windows 10 Pro

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/2438129/41074672-2d3d3148-69d7-11e8-8bbe-f4eaa976114a.png)

**Comment by raisedadead** [comment]
Issue moved to [freeCodeCamp/learn #159](https://github.com/freeCodeCamp/learn/issues/159) via [**ZenHub**](https://www.zenhub.com/)
