### ISSUE TITLE
Even with no syntax error internet explorer does not run test.

### ISSUE THREAD

**Issue by ianellison87** [freeCodeCamp/freeCodeCamp#17474]
#### Describe your problem and - if possible - how to reproduce it
i have tried to run tests on multiple challenges and none of them are working for me.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/chaining-if-else-statements

#### Tell us about your browser and operating system

* Browser Name: internet explorer 
* Browser Version: 
* Operating System: windows 10 version 1709

#### If possible, add a screenshot here

![2018-06-06](https://user-images.githubusercontent.com/38817240/41068522-d7e60842-69b7-11e8-8b51-451d935bee34.png)

**Comment by raisedadead** [comment]
@ianellison87 can you please share the screenshot of your browser's Dev tools console tab,

On Windows you can press <kbd>F12</kbd> and switch to the console tab. If you see any errors on the tab, please post a screenshot.

P.S: Can you also try and check on a different browser like Chrome or Firefox?

**Comment by moT01** [comment]
This has happened frequently for me as I'm going through the javascript challenges... there were some errors in the console a few times I checked - but much of the time, there are no errors and the test button just does nothing... not sure what the circumstances are to cause it, I will try and post more details if I can figure out a little more - it happens for me in firefox, chrome, and safari - seems to be when your javascript code is incomplete, maybe missing some syntax or something

**Comment by johnkennedy9147** [comment]
@raisedadead for better UX we should add a message in the freeCodeCamp console or a modal that advises there is a syntaxerror - at present the user sees nothing unless they check their browser console.  The editor is highlighting these sort of errors but its easy to miss a single character having a red underline. Could the test suite handle this?

**Comment by moT01** [comment]
<img width="638" alt="screen shot 2018-06-08 at 11 24 54 am" src="https://user-images.githubusercontent.com/20648924/41169447-a60f9a06-6b0e-11e8-8d98-449b5b234b09.png">

 screen shot from https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-operator-to-reassign-array-elements

the right is the console

**Comment by bradtaniguchi** [comment]
The
**ES6: Use Destructuring Assignment with the Rest Operator to Reassign Array Elements**
challenge sets the user up wrong from the start, where arr isn't assigned, which is very misleading. The previous challenges either provide `const` or provide nothing. 

I don't think this is a big problem, if there was better feedback for the syntax errors. 
Even something as simple as a message saying to check the browser's dev tools (which also gets the user more accustomed to-doing as such) would help, because as @raisedadead  said, the user is getting 0 feedback.

**Comment by ianellison87** [comment]
![2018-06-12 1](https://user-images.githubusercontent.com/38817240/41324784-9eede4c0-6e84-11e8-835f-0783ee53e35d.png)
@raisedadead 
everything works when I run it on google chrome but It doesn't have my code camp progress saved. possibly an out of date Internet Explorer browser? I will try to update and see if that works
