### ISSUE TITLE
Applied Accessibility - Improve Accessibility of Audio Content with the audio Element: Can't pass when other attributes are present in the <audio> element

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#17477]
#### Describe your problem and - if possible - how to reproduce it
Just as the title says. This code won't pass (even though it should pass all the tests) because of the `id` attribute:

```html


<body>
  <header>
    <h1>Real Coding Ninjas</h1>
  </header>
  <main>
    <p>A sound clip of Zersiax's screen reader in action.</p>

    <audio id="Zersiax" controls>
      <source src="https://s3.amazonaws.com/freecodecamp/screen-reader.mp3" type="audio/mpeg" /></audio>
    
    </main>
</body>
```

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/improve-accessibility-of-audio-content-with-the-audio-element/

**Comment by hctpscl** [comment]
Hi @kevcomedia! Thanks for reporting this. There is already a fix for this in staging (see https://github.com/freeCodeCamp/freeCodeCamp/pull/17401). I'm not sure when this will appear in production, but rest assured it's on its way,
