### ISSUE TITLE
when I go back to view solved lessons they are showed like they are unsolved

### ISSUE THREAD

**Issue by Ildorado** [freeCodeCamp/freeCodeCamp#17485]
#### Describe your problem and - if possible - how to reproduce it
While solving projects it's helpful for me to go back to solved lessons to remember some details, but after freeCodeCamp update despite the fact that lessons are solved they are showed in original way(like when the are unsolved) and it's takes much longer time to review lessons this way. Is there a way to change this?? If not I think it would be helpful to make this possible.

**Comment by s-Hale** [comment]
Same issue here. All of my 2016-2017 work shows as completed, but the code is gone, and the Redux challenges I've completed yesterday and today complete, but the code doesn't save.

**Comment by lasas** [comment]
Same issue here. I tried to resubmit few times "JavaScript Algorithms and Data Structures Projects: Palindrome Checker", but when I return, code is gone. And when I'm in "Welcome dashboar", I see "You have built 0 out of 30 projects." but when I check Curriculum Page ("JavaScript Algorithms and Data Structures Projects") there are two projects marked as completed.

**Comment by decadehew** [comment]
me too

**Comment by PolarisTLX** [comment]
Same issue. Also with recently completed react/redux challenges. Frustrating as it would be much more useful to be able to go back and see what my solutions were as a reference.

**Comment by extreme-developer** [comment]
This is quite a critical bug I think. Anyone can fix this and make a pull requesst?

**Comment by T1mL3arn** [comment]
It looks strange but some solutions are saved and some aren't. For example, my code for [Project Euler: Problem 1: Multiples of 3 and 5](https://learn.freecodecamp.org/coding-interview-prep/project-euler/problem-1-multiples-of-3-and-5) is saved, but not for [Project Euler: Problem 2: Even Fibonacci Numbers](https://learn.freecodecamp.org/coding-interview-prep/project-euler/problem-2-even-fibonacci-numbers).

After a little bit digging I've found ffc saves solution's code if `Download my solution` button is pressed.

**Comment by scissorsneedfoodtoo** [comment]
Closing as stale.
