### ISSUE TITLE
Applied Visual Design - illustrations for color theory

### ISSUE THREAD

**Issue by jooji-san** [freeCodeCamp/freeCodeCamp#17481]
Please, add illustrations to color theory exercises. Without them it's really hard to understand. :)

**Comment by carlosvigil** [comment]
_Applied Visual Design: Learn about Complementary Colors_
This challenge also uses outdated models of color theory.
Reference this site and various others that can be found with a search.
**http://www.huevaluechroma.com**

**Comment by scissorsneedfoodtoo** [comment]
Fixed on beta site: https://www.freecodecamp.rocks/learn/responsive-web-design/applied-visual-design/learn-about-complementary-colors
