### ISSUE TITLE
Applied Visual Design - Bezier Curves are confusing

### ISSUE THREAD

**Issue by jooji-san** [freeCodeCamp/freeCodeCamp#17489]
Yeah, they are. Please make explanations a little bit easier.

**Comment by juandesouza** [comment]
I think the fCC content already goes deep enough about cubic bezier. check this link and you'll understand a little more about it: http://www.css3beziercurve.net/

**Comment by supuun** [comment]
Yeah, I think they should not explain it so detailed. They should encourage use of your above linked kind of websites

**Comment by thecodingaviator** [comment]
@jooji-san If your issue has been resolved, please close this thread, else comment with what changed you'd like to see
