### ISSUE TITLE
Link to FCC's medium articles

### ISSUE THREAD

**Issue by jooji-san** [freeCodeCamp/freeCodeCamp#17487]
FreeCodeCamp's medium articles are insanely helpful. Why not link provide links to them in the exercises?

**Comment by jooji-san** [comment]
That will be beneficial, too, but I think it's different from my proposal.

**Comment by thecodingaviator** [comment]
The simple reason I think is that almost none of the articles is focused on one specific challenge and there is no point in putting links to the medium blog just for one or two challenges. Besides, the matter covered in the blog is mostly different from the FCC syllabus.

**Comment by thecodingaviator** [comment]
@jooji-san If this answers your question, please close the issue

**Comment by raisedadead** [comment]
If it helps we are linking medium as a resource in a footer link in our upcoming resources. We do not think there is any worth in linking them from the challenges themselves.

We do link guide articles in many of our challenges as a supplement.

**Comment by RandellDawson** [comment]
@jooji-san You might consider adding a Medium article link to the applicable Guide article (typically found under the `Resources` section of an article), if you you feel strongly about a specific Medium article.
