### ISSUE TITLE
Roadmap Question: Is there a plan of having Machine learning in curriculum? 

### ISSUE THREAD

**Issue by imvetri** [freeCodeCamp/freeCodeCamp#17486]
Hi,

I really appreciate how freecodeCamp's curriculum and currently its mostly about web development. Is there a plan to also have AI / ML in the curriculum just like how web development is taught ?

Thanks!

**Comment by thecodingaviator** [comment]
@QuincyLarson what about this? Seems interesting!

**Comment by moT01** [comment]
Closing as stale. The next iteration of the curriculum is in the works [here](https://github.com/freeCodeCamp/CurriculumExpansion/issues?page=2&q=is%3Aissue+is%3Aopen). I don't see a plan to add these. Feel free to create a new issue over there and it will probably get noticed. Thanks and happy coding!

**Comment by imvetri** [comment]
@thecodingaviator , @RandellDawson  @moT01  @QuincyLarson Thanks a lot for getting this done. I noticed youtube video about ML from freecodecamp. :) 
<img width="407" alt="Screenshot 2022-10-19 at 8 04 15 PM" src="https://user-images.githubusercontent.com/6542274/196721443-93b07cec-c206-4895-8613-3f8d951ec442.png">
