### ISSUE TITLE
Typo on 10 improvements page: "Lighting Fast"

### ISSUE THREAD

**Issue by kshoultz** [freeCodeCamp/freeCodeCamp#17483]
#### Describe your problem and - if possible - how to reproduce it
Grammar stuff on the page "10 improvements page":

1. Typo: "Improvement #7: Lighting Fast Learning Platform" should be "Improvement #7: Lighting-Fast Learning Platform
2. Headers should be grammatically consistent. Uppercase of all first letters in some headers, regular sentence structure on other headers.

#### Add a Link to the page with the problem
https://forum.freecodecamp.org/t/10-major-freecodecamp-improvements-that-are-live-now/192130

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by raisedadead** [comment]
Hi @kshoultz,
 
Please comment on the forum thread with a `@QuincyLarson` 
He would be able to fix it there.

Thanks.
