### ISSUE TITLE
Possible Capitalization Error on the Curriculum

### ISSUE THREAD

**Issue by PlasmaIntec** [freeCodeCamp/freeCodeCamp#17488]
#### Describe your problem and - if possible - how to reproduce it
I noticed that "Apis And Microservices Certification" did not have the "pi" capitalized. I realize that could interfere with the intended acronym of the certification (AMC). but I would suggest using a smaller size yet still capitalized HTML font.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: Chrome 66
* Operating System: Windows NT 10.0

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/12981557/41116881-6501a9a6-6a40-11e8-9609-64e3a9a79373.png)

**Comment by chaomt** [comment]
I can work on this!

**Comment by chaomt** [comment]
> I can work on this!

I'm trying to find "Apis" in the code, looking at client/.cache/redux-state.json. I don't think "Apis" having "pis" lowercase is actually a typo, they use this capitalization quite a bit in just the one document.
Any thoughts @PlasmaIntec @raisedadead

**Comment by RandellDawson** [comment]
We are closing this issue as it has already been fixed ([view on our beta](https://www.freecodecamp.rocks/learn)).  This change will be shipping to production soon.
