### ISSUE TITLE
Current-challenge button redirects to invalid URL

### ISSUE THREAD

**Issue by cmccormack** [freeCodeCamp/freeCodeCamp#17496]
#### Describe your problem and - if possible - how to reproduce it
Redirect to Current Challenge not working properly.

Example - working on problem with following URL:
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/set-the-font-size-of-paragraph-text/

Log out
Log in
Redirected to https://www.freecodecamp.org

Click button `Go to the coding cirriculum` (https://www.freecodecamp.org/challenges/current-challenge)

Redirected to the following URL:
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/set-the-fontsize-of-paragraph-text

Notice hyphen missing between font and size in URL.

#### Add a Link to the page with the problem
https://www.freecodecamp.org
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/set-the-fontsize-of-paragraph-text

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Windows 10

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/3016919/41129139-993dad94-6a65-11e8-81b2-66cafafb3db7.png)

**Comment by thearunster** [comment]
Confirmed that this is the case for any lesson that has a dash (-) in the title. 
Seems like there is some function that removes dashes in the URL while navigating through current challenges link. 
For example: The link,
[https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/add-a-box-shadow-to-a-card-like-element/](https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/add-a-box-shadow-to-a-card-like-element/)
becomes 
[https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/add-a-boxshadow-to-a-cardlike-element](https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/add-a-boxshadow-to-a-cardlike-element)
leading to an invalid URL.

**Comment by moT01** [comment]
Thank you for reporting this issue.

    This is a standard message notifying you that this issue appears to be very similar to issue #17463, so I am closing it as a duplicate.

    If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
