### ISSUE TITLE
README Project links aren't rendering correctly

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/freeCodeCamp#17491]
#### Describe your problem and - if possible - how to reproduce it

Project lists in the `README` aren't rendered correctly (see screenshot below).

#### Add a Link to the page with the problem

E.g. https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/README.md#1-responsive-web-design-certification

#### Solution

Just need to add a new line before the `Projects` list for the six certifications in the `README`.

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/2754821/41118209-1ec471b8-6a44-11e8-936d-4a4e63d610f1.png)

**Comment by mmhuntsberry** [comment]
Hello, 
First timer here wanting to contribute.  Made my first pull request for the issue.  Hope it helps!  Happy to make changes if it's incorrect. Thanks!
