### ISSUE TITLE
fix favicon meta data on the certification views to be same as home page

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#17493]
![image](https://user-images.githubusercontent.com/1884376/41119794-60acb028-6ab1-11e8-8695-0b4b40b7da9a.png)

**Comment by Mandihamza** [comment]
Hey @raisedadead, mind if I take this one?

**Comment by raisedadead** [comment]
@Mandihamza yes please! All yours.

**Comment by sdabhi23** [comment]
@raisedadead it looks like this issue has already been resolved, can you please confirm it?

Reference: www.freecodecamp.org/certification/sdabhi23/data-visualization

**Comment by keerthigaragu** [comment]
@raisedadead Is this about the favicon image on titlebar or the title bar's metadata description?

**Comment by raisedadead** [comment]
@sdabhi23 Yes this has been resolved. Thanks for letting us know.
