### ISSUE TITLE
Fix content on Applied accessibility

### ISSUE THREAD

**Issue by juandesouza** [freeCodeCamp/freeCodeCamp#17495]
I recommend checking the following content to analyse if this should be fixed (I’m using Chrome on Windows):

On the page[ Applied Accessibility - Avoid Colorblindness Issues by Using Sufficient Contrast](https://forum.freecodecamp.org/clicks/track?url=https%3A%2F%2Flearn.freecodecamp.org%2Fresponsive-web-design%2Fapplied-accessibility%2Favoid-colorblindness-issues-by-using-sufficient-contrast&post_id=436010&topic_id=197853) the text separates two types of colors: darker and lighter colors, being blue, violet, magenta and red the former, and green, yellow, orange, blue-green the latter. I don’t think this information is accurate. All hues have darker and lighter tones, tints and shades. The author of the text was probably trying to talk about warm and cold colors, being green, yellow and red the former, and violet and blue the latter. See the following image: http://www.aridglamor.com/wp-content/uploads/2014/03/tintsshades.jpg

On the page [Make Links Navigatable with HTML Access Keys](https://forum.freecodecamp.org/clicks/track?url=https%3A%2F%2Flearn.freecodecamp.org%2Fresponsive-web-design%2Fapplied-accessibility%2Fmake-links-navigatable-with-html-access-keys&post_id=436010&topic_id=197853) the text says that we should use the accesskey to use the keys to go direct to the element with the accesskey attribute, but it doesn’t say that we should type ALT + key (windows) to make it work. For exemple, a tag with the attribute accesskey=“a” will only work if you type ALT + a. I think this information should be added to the page. For more accurate information about the correct shortcut key to access this property, see this link: https://www.w3schools.com/tags/att_global_accesskey.asp

On the page [Applied Accessibility - Use tabindex to Specify the Order of Keyboard Focus for Several Elements](https://forum.freecodecamp.org/clicks/track?url=https%3A%2F%2Flearn.freecodecamp.org%2Fresponsive-web-design%2Fapplied-accessibility%2Fuse-tabindex-to-specify-the-order-of-keyboard-focus-for-several-elements&post_id=436010&topic_id=197853) the text says that if we use the attribute tabindex with the value of any positive numbers like 1, 2, 3, etc, the tab will first follow the order of these elements, and after this, they go the the other elements. This is not true, it doesn’t happen. Any value in the tabindex attribute that is different from 0, be it positive or negative, will make the tab jump over the element and ignore it. This is what happened to me using chrome on windows.

Bug on the last page of [Responsive Web Design - Make typography responsive](https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/make-typography-responsive)
After finishing the challenge, the page fails in trying to open the next challenge, which is the first page of the CSS Flexbox. Weirdly, the url of the adressbar of the browser changes to the url of the flexbox introduction page, but we remain in the Make Typography Responsive page.

**Comment by camachado** [comment]
I am also using Chrome and came across the issue with the `tabindex` attribute in the [Applied Accessibility: Use tabindex to Specify the Order of Keyboard Focus for Several Elements](https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/use-tabindex-to-specify-the-order-of-keyboard-focus-for-several-elements) exercise. Setting the value of `tabindex` attribute to '1' and '2' on the `input` fields respectively does not appear to result in the expected behaviour as described in the lesson - 

> Setting a tabindex="1" will bring keyboard focus to that element first. Then it cycles through the sequence of specified tabindex values (2, 3, etc.), before moving to default and tabindex="0" items.

**Comment by thecodingaviator** [comment]
@juandesouza as far as for the challenge switching problem after making typography responsive, I've tested it right now and it works. :)

**Comment by T1mL3arn** [comment]
:+1:  for info about shortcuts to navigate with `accesskey` attribute. There are [different shortucts for different browsers and operating systems](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey) though.

**Comment by RandellDawson** [comment]
@juandesouza @camachado Can you validate this is no longer an issue?
