### ISSUE TITLE
Goodbye World

### ISSUE THREAD

**Issue by RachelRodriguez** [FreeCodeCamp/FreeCodeCamp#1749]
Challenge http://beta.freecodecamp.com/challenges/waypoint-say-hello-to-html-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I changed Hello to Hello World like I was supposed to, and when I tried going to my next challenge it wouldn't go. Instead, "404: We couldn't find a challenge with the name `undefined` Please double check the name." that appeared on my screen and nothing else changed. Also, the side panel doesn't allow scrolling all the way down.

![image](https://cloud.githubusercontent.com/assets/13262688/9263462/32ad2802-41eb-11e5-9263-617be73bde90.png)

**Comment by BerkeleyTrue** [comment]
This has been fixed but has not made it up to beta yet. For now you will need to go back to the `/map` between challenges.

Happy Coding!

**Comment by RachelRodriguez** [comment]
Okay, thanks!

**Comment by BerkeleyTrue** [comment]
You're welcome!
