### ISSUE TITLE
Incorrectly Stated and Coded Accesssibility Example On Radio Basic HTML Buttons Lesson

### ISSUE THREAD

**Issue by jhomme** [freeCodeCamp/freeCodeCamp#17503]
#### Describe your problem and - if possible - how to reproduce it
In the lesson on radio buttons, the lesson text correctly states that you should link the id attribute of an input tag with a for attribute on a label tag. The code example that illustrates this has the input tag wrapped inside the label tag. This is not correct, even though it will work. The entire label tag should come after the input tag. Besides this, you should state that wrapping the input tag inside the label tag creates an implicit link for screen readers.

Finally, you should state that for best usability within accessibility that the learner should place the label tag after the radio button when they use the for and id attributes. You should also say that if they wrap the input tag inside the label tag, that for best usability within accessibility, the learner should place the label text after the input tag.

All of this applies to checkboxes, too, but I have not yet gotten to them in the learning.

Finally, for list fields and edit boxes, label text, whether or not you use a for attribute should come before the input tag in the HTML order. This is for best usability within accessibility.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-set-of-radio-buttons

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 60.0.2
* Operating System:  Windows 10

**Comment by moT01** [comment]
I noticed this a while back. There is quite a few challenges that have this problem. Do you think we should go through and fix all these @RandellDawson? It could involve rewriting a couple challenges, and changing seed code + solutions + tests to many. Along with making the guide articles out of sync.

**Comment by jhomme** [comment]
Hi,
Because my day job is working on accessibility, if someone is willing
to help me, I do not think I can write the code unless it is fairly
straight forward, but I would certainly be able to work on articles
and test for accuracy. I may need help setting up the system locally.
I apologize for needing so much hand holding, but my heart is in the
right place. I would be glad to read instructions and follow them to
the best of my ability and communicate along the way.

Jim

On 5/6/19, Tom <notifications@github.com> wrote:
> I noticed this a while back. There is quite a few challenges that have this
> problem. Do you think we should go through and fix all these @RandellDawson?
> It could involve rewriting a couple challenges, and changing seed code +
> solutions + tests to many. Along with making the guide articles out of sync.
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/freeCodeCamp/freeCodeCamp/issues/17503#issuecomment-489796210


-- 
==========

Jim Homme
http://www.jimhommewebdev.com
Twitter: @jimhomme
Facebook: http://www.facebook.com/jimhomme
LinkedIn: https://www.linkedin.com/in/jimhomme
Skype: jim.homme
FreeChess: jhomme

**Comment by lionel-rowe** [comment]
@jhomme Could you explain why it's less correct to have the `label` as a child of the `input`? Here's [what the W3C spec says](https://www.w3.org/TR/html52/sec-forms.html#the-label-element) regarding placement of `label`s:

> Phrasing content, but with no descendant labelable elements **unless it is the element’s labeled control**, and no descendant label elements. [Emphasis mine]

Regarding whether the `for` attribute is still required when nesting, [this W3C technique on associating label elements](https://www.w3.org/TR/2008/WD-WCAG20-TECHS-20080430/H44.html) suggests that it may still be worthwhile including for the benefit of old screen-reader/browser combinations. With that said, the article is from 2008 and I don't think it would apply to anything remotely modern. In any case, I can't find anything anywhere that suggests it's _incorrect_ to still include the `for` attribute.

Regarding the _best_ placement of the `label` in relation to various types of `input`, I did find [this technique on positioning](https://www.w3.org/TR/WCAG20-TECHS/G162.html), which is consistent with what you're saying, but it appears to be relevant only for _visual_ placement, rather than markup. It doesn't mention screen readers at all, but it does mention screen _magnifiers_.

**Comment by eschafer** [comment]
Explicit labels have better support. Implicit labels don't work in Dragon Naturally Speaking.

https://a11ysupport.io/tech/html/label_element

**Comment by jhomme** [comment]
Hi,
Maybe because I am still going through FreeCodeCamp, I'm
misunderstanding the relationship idea. Please feel free to correct
me.

From what I understand, if the label tag is around the input tag, that
makes the input tag the child of the label tag.

From what I understand about how the W3C wants to use for how field
labels get spoken by assistive technology, this arrangement forces the
screen reader to speak the field label.

The reason I advocate separating the label from the input tag and
using the for attribute is that no matter where you put the label tag,
that code forces the screen reader to speak the label. Realistically,
though, the best way to code the label for edit fields and list
fields, whether you use the for attribute and separate the label tag
or put the label tag around the input tag is to put the text of the
field label before the edit box or list box in the HTML order and
after radio buttons and check boxes in the HTML order.

This is because of how screen readers show the fields and how screen
reader users are trained to read. Screen readers have two modes:
Browse mode and Forms mode, called Focus mode by one popular screen
reader.

Jim

On 5/7/19, Elizabeth Schafer <notifications@github.com> wrote:
> Explicit labels have better support. Implicit labels don't work in Dragon
> Naturally Speaking.
>
> https://a11ysupport.io/tech/html/label_element
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/freeCodeCamp/freeCodeCamp/issues/17503#issuecomment-490090652


-- 
==========

Jim Homme
http://www.jimhommewebdev.com
Twitter: @jimhomme
Facebook: http://www.facebook.com/jimhomme
LinkedIn: https://www.linkedin.com/in/jimhomme
Skype: jim.homme
FreeChess: jhomme

**Comment by lionel-rowe** [comment]
> forces the screen reader to speak the field label

@jhomme Isn't that what you want, though? There's a necessary relationship between `label` and `input`, so you want them to be treated as a single atomic unit. That's the same reason they should always be visually adjacent on the page. Or am I misunderstanding your concern?

> how the W3C wants to use for how field labels get spoken by assistive technology

Can you find a relevant citation from W3C or (probably more importantly) a source that explains how various assistive technologies actually parse the different placements, regardless of spec?

> Explicit labels have better support. Implicit labels don't work in Dragon Naturally Speaking.
> 
> https://a11ysupport.io/tech/html/label_element

@eschafer That definitely suggests that _removing_ the `for` attribute isn't a good idea (I'm not sure how common the Dragon/IE combo is, but judging by the fact that their Chrome extension is riddled with bugs, it may be more common than you'd think).

@xersiax Any thoughts as to best practices here?

**Comment by zersiax** [comment]
Generally when a question like this comes up, I look at the examples on MDN . they tend to have the right of it. Generally, label for and an associated form field is the way, and I personally don't see an issue with the way the current lesson is coded

**Comment by jhomme** [comment]
Hi,
Unfortunately, and this frustrates me, it is not how assistive
technology computes the accessible name, which in our case is the
field label, it is the W3C has standardized on how to compute the
accessible name. It frustrates me because, as you can see from the
Dragon Naturally Speaking example, the makers of assistive technology
need to make sure they adhere to the standard. Because they do not
always do this, it makes those of us with disabilities look like
fools, and frustrates developers. Accessibility is seen as a necessary
evil enough as it is already.

Sorry for the rant. I'll see if I can find chapter and verse from the
W3C about computing the accessible name.

Jim

On 5/7/19, Florian Beijers <notifications@github.com> wrote:
> Generally when a question like this comes up, I look at the examples on MDN
> . they tend to have the right of it. Generally, label for and an associated
> form field is the way, and I personally don't see an issue with the way the
> current lesson is coded
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/freeCodeCamp/freeCodeCamp/issues/17503#issuecomment-490211604


-- 
==========

Jim Homme
http://www.jimhommewebdev.com
Twitter: @jimhomme
Facebook: http://www.facebook.com/jimhomme
LinkedIn: https://www.linkedin.com/in/jimhomme
Skype: jim.homme
FreeChess: jhomme

**Comment by thecodingaviator** [comment]
Since we've released the changes, this issue should have been fixed. I am, therefore, closing this issue. Please add more information if this still persists and I'll reopen it.
