### ISSUE TITLE
Bug in Responsive Web Design Projects - Build a Survey Form 

### ISSUE THREAD

**Issue by llamafluida** [freeCodeCamp/freeCodeCamp#17506]
#### Describe your problem and - if possible - how to reproduce it
First, I love the new page. Second, I think is more a typo more than a bug, but could cause confusion.

The problem is in the **Responsive Web Design Projects - Build a Survey Form** (link below), in the user story 13, that says: 

> Inside the form element, I can select a field from one or more groups of radio buttons. Each group should be grouped using the name attribute.

In this, just mention that require a name attribute, and if one doesn't use a name attribute in the input with type radio, doesn't approve it. With this all good.

The problem is that, if one doensn't use a value attribute in these inputs, it doesn't pass the test. One can see that the value attribute in needed where the test display the present error like it shows in the screenshot, but this doesn't shows in the user story that is required too.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-survey-form

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.79
* Operating System: Windows 10

#### If possible, add a screenshot here

This without a name attribute

![boceto 2](https://user-images.githubusercontent.com/37635593/41187169-e5f31ce8-6b71-11e8-954b-bd7dbeb0d7c4.png)

This without a value attribute

![boceto 4](https://user-images.githubusercontent.com/37635593/41187182-17edd4d6-6b72-11e8-9dee-b2e279f78330.png)

**Comment by Yonatanos** [comment]
Hi!
You should add value attribute where id="totally"

**Comment by llamafluida** [comment]
That was me recreating the present problem, the thing here is that isn't stated that one must use value in the group or radios, just name, but it requires value. One can pass the test using value and name, the thing is, isn't stated in the point. 

What I wanted with this request was to show that thats happens, and if is intended that it doesn't show that one must use value too in point 13, or was a Typo and the point 13 must be rewrited to include explicitly value and name, or is a thing that value isn't required, that is why point 13 doens't state that is required explicitly, and must be changed to not require the use of value to pass the test.

I know one reading the AssertionError can pass easily the test, but at the same time I see it anyway like a little bug (if it is) to be aware that exist (but that doens't generate much problems anyway).

**Comment by esotheriax** [comment]
I think that user story #13 should be changed to: 
"User Story #13: Inside the form element, I can select a field from one or more groups of radio buttons. Each group should be grouped using the name attribute and each radio button should must have a value attribute."

The reason I think this is because my attempt at the project passed test #13 when I included a value for each of the radio buttons (but it failed when I didn't include a value for each of the radio buttons).

![image](https://user-images.githubusercontent.com/34858647/46286755-30300180-c578-11e8-8dfc-951d7c8a565f.png)

**Comment by pixiewoman** [comment]
Had the same problem (for days ). Couldn't figure out what I was doing wrong and then I adedd "value" for each radio button and finally passed user story 13.
So I agree with all of you that this user story should be changed in a way to require a "value attribute".

**Comment by tbushman** [comment]
@QuincyLarson Thanks for informing us. We will need to update the radio button user story to clarify that the `value` attribute is required in addition to `name`.  
https://github.com/freeCodeCamp/testable-projects-fcc/issues/700

**Comment by RandellDawson** [comment]
@tbushman Was this ever fixed?

**Comment by tbushman** [comment]
@RandellDawson not yet.

**Comment by DarrylWilliams32** [comment]
Is anyone having issues with user story 10? That's the one that wont pass for me; it's stating I don't have a label with id="name-label" this isn't possible because story 12 says "have label with id="name-label" that is a child of survey"
