### ISSUE TITLE
Roadmap Question: Is there a plan for having progressive web app development in curriculam ?

### ISSUE THREAD

**Issue by StubRavi** [freeCodeCamp/freeCodeCamp#17500]
Hey, There is a section of Responsive Web Design Challenges. I think responsive web design is outdated. Is there a plan for having progressive web app development in curriculam ?

**Comment by QuincyLarson** [comment]
Yes - we're planning on covering PWAs in detail. Do you have any specific issues you'd like us to cover?

**Comment by icatat** [comment]
I noticed that this issue has been opened in June 8 and it seems inactive without addressing  any specific issue. Wouldn't it be a better idea to close it? @StubRavi
