### ISSUE TITLE
Error in 'Applied Accessibility: Give Links Meaning by Using Descriptive Link Text'

### ISSUE THREAD

**Issue by supuun** [freeCodeCamp/freeCodeCamp#17508]
#### Describe your problem and - if possible - how to reproduce it

`<a href=''></a>` doesn't work. it says 

> code.match(...) is null

 but `<a href=""></a>` works without a problem

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/give-links-meaning-by-using-descriptive-link-text

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 62
* Operating System: Windows 10

**Comment by bayronguti22hope** [comment]
I have the same problem, my code:

<a href="">Click here for information about batteries</a></p>

doesn't work? help pls?

**Comment by scissorsneedfoodtoo** [comment]
@bayronguti22hope, sorry that you're having a problem.

The description says to move the `<a>` tags form around "Click here" to "information about batteries." So here's the passing code:

`Click here for <a href=''">information about batteries</a></p>`
