### ISSUE TITLE
Feature Request : Add 'previous' and 'next' buttons for navigating challenges.

### ISSUE THREAD

**Issue by mpmaan** [freeCodeCamp/freeCodeCamp#17509]
#### Describe your problem and - if possible - how to reproduce it
I completed some of the challenges a few months ago. Now, I wanted to revisit those challenges to have a look at some of the concepts. My previously submitted solutions are not available anymore. So I can't move to next challenge without submitting a new solution again which I don't want to do. I can only go to next challenge from 'Curriculum' which is really inefficient.
The 'Next' button could be placed between the search bar and  'Curriculum'.

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 67
* Operating System: Ubuntu 18.04

**Comment by RandellDawson** [comment]
@moT01 I pulled it down and tested it.  The `next` button works fine, but the `prev` goes to `http://localhost:8000/undefined`.

**Comment by moT01** [comment]
Do you know what lesson were you on when the back button didn't work? I had that happen, and thought I fixed it up. Yea, all the buttons jump around, but that could be a possibility. Thanks for taking a look.

**Comment by RandellDawson** [comment]
It does not matter which section or lesson I start on, it will not go to the previous challenge.

**Comment by moT01** [comment]
hmm, I'm not having that problem
