### ISSUE TITLE
Discussion area for organizing the project into separate repos

### ISSUE THREAD

**Issue by tchaffee** [freeCodeCamp/freeCodeCamp#17504]
This is an issue where we can continue the conversation from Gitter about how to break up the source code into separate repos to make it less monolithic and easier to maintain.

We already know that keeping all the source code in one repo is too monolithic and mixes too many concerns. So the question is not whether we break the project up into seperate repos, but how far we go with that.

Specifically the most recent question is whether or not a new Challenge Seed Editor (still to be developed) should be included in the Curriculum repo.

My suggestion is that we don't do this. Let's discuss the pros and cons for each approach. I'm going to kick it off by discussing a con that I see with mixing the Editor code with the Curriculum. Here's a picture of the Curriculum repo as of today:

![selection_109](https://user-images.githubusercontent.com/148813/41180329-44c340e6-6b44-11e8-9aed-908090b6bf44.png)

Note there are already a lot of JavaScript files and other files. My concern is that as the code grows and we get more and more files, I have no idea which files belong with which functionality. As a developer it's more stuff to figure out. Is `repack.js` for the Editor? Or is it for the Challenges? As a new dev I have to guess, or ask, or break open the source code and try to figure it out.

Another con: I often look at package.json to understand what components are used in the project and if I have to learn anything new. With mixing concerns there is no way I can tell which components are needed by the Editor, which are needed by the Curriculum.

I'm going to leave it at that for now because I would like to give everyone a chance to talk about pros and cons and especially **it might be good to list out what our goals are before anything**.

**Comment by tchaffee** [comment]
@QuincyLarson @raisedadead @julianorafael @SaintPeter I am tagging everyone involved in the Gitter discussion plus a couple of people who should be involved. Please feel free to tag anyone else who I might have missed.

**Comment by tchaffee** [comment]
@Bouncey You'll probably be interested in this discussion too.

**Comment by tchaffee** [comment]
@raisedadead I have the same goal as you: make the developer experience as easy as possible.

For me that means not having to sift through code that is completely unrelated to what I'm working on.

I don't think it's really fair to say that breaking up the repos has proven that contributions will stop. You are in the middle of making huge changes and that takes time for people to get used to the new structure. And nothing is documented now. Both of those are factors that have little to do with things being in separate repos. 

One other advantage to breaking things up is that it will attract more developers. If the Challenge Editor is tied to the FCC curriculum it interferes with developers who have their own custom curriculum. If it's separated then you attract devs who are interested in improving the Challenge Editor but who aren't interested in the curriculum.

In terms of good documentation, no amount of documentation is going to tell me which files belong to Curriculum vs. Challenge Editor. But it takes two lines of documentation to say "If you want to update the Curriculum go to repo XYZ, if you want to improve the Challenge Editor, go to repo ABC".

I did take a closer look at React and Gatsby. The way they have done it is to have a `packages` dir and a separate subdirectory for every functionality. Take a look. 

https://github.com/gatsbyjs/gatsby/tree/master/packages

The `gatsby-cli` source is completely separated from the `gatsby` source and so are all the plugins. Only highly related source code is kept in the same directory. 

Same for React. There are only are only 10 JS files in the React package! Sweet. So easy to work on React core because the source is totally isolated.

https://github.com/facebook/react/tree/master/packages/react/src

It's not hugely different from having separate repos, and that approach could work for me. But we still have to have some logic around when something becomes a separate repo.

Facebook for example has many separate React related repos:

react-native
create-react-app
react-devtools
react-native-website
redux
react-native-applinks

It's not clear to me when something should be in the same repo but have a separate package directory and when something should be its own repo. If we can figure that out, then I think we could use the Facebook approach and have clear guidelines about how to keep unrelated source separate within the same repo, and when to create a new repo.

**Comment by julianorafael** [comment]
First of all, @tchaffee thanks for the issue.

I feel like the lerna approach is enough separation for now. The curriculum and it's translations and the editor can live in the same repo because they take care of the same concern, that being the fcc curriculum, and more important, they rely on each other. The facebook approach to different repos is clear. The tool must live on it's own and don't really need the other to work. Sure `create-react-app` uses `react`, but it doesn't need it to work on it's own. All the tools you listed are completely isolated from each other.

I feel like the biggest challenge we have to face is how are we going persist changes on the curriculum. Creating a UI on top of the current json files is straight forward. Persisting is a challenge on it's own. I thought about [json-server](https://github.com/typicode/json-server), but that isn't really meant for this. I didn't used gatsby before. Does it solve our problem? Can we parse the json into md files and get it back to json files after the changes? What do you guys think about this?

**Comment by tchaffee** [comment]
I'm happy with the Lerna approach for now, although I'm not convinced we have an easy to understand rule about when we create a separate repo. For me the decision might be mostly around developer experience. If you have to go across repos to fix one thing, they should probably be in the same repo. If there would never or rarely be a reason to do that, then it deserves a separate repo. Let's keep brainstorming around that, and maybe even reach out to Facebook to see if they can give us some input. I'll try a tweet first, and if that gets no response I have some contact there I can reach out to.

For the Challenge Seed Editor, I've created a separate issue so we can stay focused on code organization in this thread. @julianorafael, can you please repeat your questions concerns about the Editor at this issue? https://github.com/freeCodeCamp/freeCodeCamp/issues/17511

**Comment by raisedadead** [comment]
We have a monorepo now.
