### ISSUE TITLE
html challenge editor not saving user input after a refresh

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#1751]

**Comment by kennethmath** [comment]
Ty Idk

**Comment by kennethmath** [comment]
Sorry I ended up here cause IDK thank all of yall for trying I'm sick of it and dk

**Comment by kennethmath** [comment]
Is this what u want 
marc.CPU.did.com

**Comment by kennethmath** [comment]
Marc

**Comment by kennethmath** [comment]
msec

**Comment by kennethmath** [comment]
C it all changed but know I k.ow

**Comment by kennethmath** [comment]
msec.CPU.I can not write it.it will not let me

**Comment by kennethmath** [comment]
From what I do know is this program r whatever has some hellifiled security it pushed Google aid completely out of it they were like wow  and still wanted me to pay when they didn't even do nothing
