### ISSUE TITLE
Link Broken on Contributor's Guide page

### ISSUE THREAD

**Issue by rsangdoung** [freeCodeCamp/freeCodeCamp#17529]
Broken link on Contributor's Guide -- error 404:
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#challenge-template

Here's the broken link under "Challenge Types":
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/ap/utils/challengeTypes.js

**Comment by akkatracker** [comment]
And to clarify (for anyone who wants to have a crack at this one), the link has a typo in it (ap instead of app) and should say

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/utils/challengeTypes.js

**Comment by mpmaan** [comment]
@akkatracker I referenced this issue by mistake. I can combine the fix for this issue and issue #17530 if that is okay or submit a PR that fixes only #17530 . What should I do?

**Comment by akkatracker** [comment]
I would submit 2 separate PRs just to be safe (but I'm sure 1 would be fine too) :)

**Comment by mpmaan** [comment]
l will keep them separate for this time.
