### ISSUE TITLE
Introduction to JavaScript

### ISSUE THREAD

**Issue by profoundhub** [freeCodeCamp/freeCodeCamp#17520]
#### Describe your problem and - if possible - how to reproduce it

Just spotted a spelling mistake: "arithemtic" ... it should be "arithmetic"

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript

**Comment by renojvarghese** [comment]
I can make the quick fix

**Comment by profoundhub** [comment]
Thanks, I'll let you know if I find anything else.

**Comment by Nirajn2311** [comment]
If the issue is solve, please close it.
