### ISSUE TITLE
Issue to complete an applied visual design lesson

### ISSUE THREAD

**Issue by j0nl1** [freeCodeCamp/freeCodeCamp#17523]
#### Describe your problem and - if possible - how to reproduce it
I can't complete the exercise

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-texture-by-adding-a-subtle-pattern-as-a-background-image/

#### Tell us about your browser and operating system

* Browser Name:  Chrome
* Browser Version:  65.0.3325.181
* Operating System:  Windows 10 1803

#### If possible, add a screenshot here
![ffc](https://user-images.githubusercontent.com/15127473/41204805-9a6fb3de-6ce9-11e8-9138-c7f208f4b9d0.png)

**Comment by Nirajn2311** [comment]
The link should be in single or double quotes, then only it will work. So it should be:
`background: url("https://i.imgur.com/MJAkxbh.png");`
