### ISSUE TITLE
logo to link to home page?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#17533]
when on the learn website or any of the challenges - the `freecodecamp` button/logo at the top left links to the learn home page - should it redirect to the main homepage?

**Comment by Nirajn2311** [comment]
Can I work on it?

**Comment by moT01** [comment]
yes, this one I'm not as sure about - as they may want to keep it how it is, but it's probly somewhere over on the learn repo 
here I think https://github.com/freeCodeCamp/learn/blob/master/src/components/Header/index.js

**Comment by Nirajn2311** [comment]
If it’s on the learn repo, then isn’t it a issue for that repo and not this.

**Comment by Nirajn2311** [comment]
Can someone please check my PR on this issue?
