### ISSUE TITLE
Broken Link on freeCodeCamp github page

### ISSUE THREAD

**Issue by rsangdoung** [freeCodeCamp/freeCodeCamp#17530]
Main page:
https://github.com/freeCodeCamp/freeCodeCamp

Click on "Academic Dishonesty" link:
https://www.freecodecamp.org/academic-honesty-policy

**Comment by akkatracker** [comment]
To clarify for anyone willing to tackle this issue - the broken link is in the README

**Comment by mpmaan** [comment]
@akkatracker I can fix this issue. Should I create a pull request.

**Comment by akkatracker** [comment]
@mpmaan go for it! Make sure to follow the instructions given in the Contributing Guidelines :) 

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md
