### ISSUE TITLE
open curriculum in current tab

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#17532]
From the settings page, the curriculum button opens in a new tab - it should open in the current tab

**Comment by moT01** [comment]
yes - this one I think should be implemented for sure, but ultimately I'm not the one who decides - it may be tough to test at the moment since we cant sign in while developing - so we might need a way around that or wait for a fix which should be in the works I think

**Comment by Nirajn2311** [comment]
I’m sorry to say this but due to some problems in the local setup I can’t do anything for this issue and until it is resolved. I had thought of doing this first as it was a good start for a beginner and a place to practice my skills.

**Comment by moT01** [comment]
@Nirajn2311 it is a good place - there's just some issues with local sign in as I mentioned which makes it tough to do certain things until it's resolved - the other issue you wanted to try might be easier as I don't think you need to sign in

**Comment by Nirajn2311** [comment]
Will solve this issue once the problem of local sign is solved.
