### ISSUE TITLE
Prevent accidental duplicate accounts

### ISSUE THREAD

**Issue by johnkennedy9147** [freeCodeCamp/freeCodeCamp#17544]
At present when you are on login / signup page if you accidentally enter wrong email address a new ac is created and a sign in code for it sent. 

I think we should introduce a measure to prevent accidental creation of duplicate ids for users. 

Perhaps we could have a check to see if the email address matches an existing ac, if not then email a confirmation advising that a new ac will be created, asking user to confirm that is what they intended.

Clicking the confirmation link in this email would then trigger the create ac and email sign-in code.

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/26827682/41253872-91d05af0-6db9-11e8-90a2-3a1a0c03e0c1.png)

**Comment by moT01** [comment]
or perhaps create the account when the user enters the login number - if it's not already created

**Comment by raisedadead** [comment]
Thanks for the issue report @johnkennedy9147 

To be very honest I have had known of this use case from the initial implementation. This is a surprisingly complex problem.

1. The Sign in page is being served directly off the auth0 servers as a simple HTML page, to avoid CORS and CSP issues.
2. This just so happens to be the best way to avoid getting false negatives from pop up blocking, add blocking and 20,000 other ways that privacy controls from so many browser/device combinations can challenge you. Not to mention the auth is central across events, learn and www.

But that above flow brings the below complexity.

1. The API is being served off a Express(loopback) server from www.
2. Its User API can't have emails available over public (unauthenticated/unknown sources) calls for obvious reasons.
3. This API can't be accessed other than from servers that we control, these are currently (camperbot and www).

So, the way it is while that extra check is going to be useful, IMHO its NOT worth adding complex logic and even introducing security risks on the auth layer.

About the accidental accounts. We do not create an account on the freeCodeCamp DB as long as its not already verified on the Auth0 DB (they are separate). So in reality duplicates will be there on the Auth0 DB, which is fine. 

Auth0 essentially verifies the email for us.

Now coming to the concern that you have mentioned:

I think you were intending to state that users can forget what emails they have on records and in turn end up creating new accounts?

I am afraid, this is something that is really tough to check. But nonetheless avoidable. I guess we could actually update the email copy that we send out to the users stating the same?

I will have to do a little more investigation on the Auth0 config, but I guess its possible to send out conditional emails.

**Comment by johnkennedy9147** [comment]
@raisedadead 
"I think you were intending to state that users can forget what emails they have on records and in turn end up creating new accounts?" Yes, exactly.

If I follow your explanation correctly:

User enters email on sign up/in page.
Auth0 checks DB: 
- if email exits sends login code
- if not exists creates but only in Auth0 db and sends login code.

When login code entered on next user screen:
- if freeCodeCamp profile exits user is logged in
- if it did not exist one is created and user logged in.

That being the case having Auth0 send distinctly different emails that clearly state the user is logging into an existing ac versus creating a new account would suffice. 

Though there is still an opportunity for user to unintentionally create a new account - if they enter the wrong email a second time it will already be present in the auth0 db and hence the wrong email would be triggered. We could mitigate this somewhat by regularly cleaning up the auth0 db so any email without a matching freeCodeCamp profile would be cleaned up.

**Comment by raisedadead** [comment]
> ...  the wrong email would be triggered. 

I would incline on sending a separate welcome email to new users apart from the verification, with a little on boarding related details. This email will be triggered from the freeCodeCamp API Server. And hence, we control when its sent out.

> We could mitigate this somewhat by regularly cleaning up the auth0 db so any email without a matching freeCodeCamp profile would be cleaned up.

This is actually something we would have to implement separate of the Auth Flow and would ideally be CRON of some form that checks across all freeCodeCamp services before deleting the record.

**Comment by moT01** [comment]
This has become quite stale. Is it safe to close this @raisedadead, or is it something we still want to implement?

**Comment by raisedadead** [comment]
IDK. A lot has changed, and we will have to investigate if the original issue (or any potential side effects) still need to be addressed. Lets keep this open until after we have fully shipped.
