### ISSUE TITLE
Code blocks formatting: line breaks missing in 'Prevent Object Mutation' challenge

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#17541]
#### Describe your problem and - if possible - how to reproduce it
Line breaks are missing in the example code.

How to reproduce: Access the URL below

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/prevent-object-mutation

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.79
* Operating System: Windows 10

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/25644062/41245018-d04cf64e-6de1-11e8-81e6-c691f9d1717e.png)

**Comment by moT01** [comment]
to fix this replace all the `\n` with `<br>` on this line https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/es6.json#L242

**Comment by brdshw** [comment]
working on fixing this.

**Comment by scissorsneedfoodtoo** [comment]
Closed via #17547
