### ISSUE TITLE
Convert HTML Entities: I have test cases wrong, but my function returns expected outputs

### ISSUE THREAD

**Issue by Snip3rSVK** [freeCodeCamp/freeCodeCamp#17542]
#### Describe your problem and - if possible - how to reproduce it
I have most test cases wrong, but my function returns expected outputs in Convert HTML Entities challenge. I noticed that in "running test window" for example instead of
```
convertHTML("Hamburgers < Pizza < Tacos") should return Hamburgers &​lt; Pizza &​lt; Tacos.
``` 
it is showing
```
convertHTML("Hamburgers < Pizza < Tacos") should return Hamburgers &&#8203;lt; Pizza 
&&#8203;lt; Tacos.
```
My code:
```
function convertHTML(str) {
  const entities = { 
    "&": "&amp;", 
    "<": "&​lt;", 
    ">": "&​gt;", 
    "\"": "&​quot;", 
    "'": "&​apos;" 
  };
  let converted = "";

  for (const char of str) {
    if (entities[char]) {
      converted += entities[char];
    }
    else {
      converted += char;
    }
  }

  return converted;
}
```

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/convert-html-entities

#### Tell us about your browser and operating system

* Browser Name: Chrome 
* Browser Version: 67.0.3396.79 (64-bit)
* Operating System: Windows 10

#### If possible, add a screenshot here
![fireshot capture 8 - intermediate algorithm scripting_ conv_ - https___learn freecodecamp org_java](https://user-images.githubusercontent.com/28108707/41245935-c29ccb24-6da9-11e8-8aad-ce58fe92452d.png)

**Comment by Flarp** [comment]
It's the HTML being escaped twice, probably by some framework deep down there.

**Comment by johnkennedy9147** [comment]
`&#8203;` is unicode zero width space which seems to be inserted between the `&` and the rest of the unicode symbol.

**Comment by johnkennedy9147** [comment]
@raisedadead @Bouncey 
Hi guys,
Can you confirm this wasn't deliberate?

non-printing character inserted after `&` in tests for this challenge. (I suspect a copy-paste issue when test written)

Example:
```
{
          "text": "<code>convertHTML(\"Sixty > twelve\")</code> should return <code>Sixty &&#8203;gt; twelve</code>.",
          "testString": "assert.match(convertHTML(\"Sixty > twelve\"), /Sixty &gt; twelve/, '<code>convertHTML(\"Sixty > twelve\")</code> should return <code>Sixty &&#8203;gt; twelve</code>.');"
},
```
https://github.com/freeCodeCamp/curriculum/blob/master/challenges/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting.json

lines 840 - 920

NOTE: not affecting correctness of test, as not in the value or regex, its just in the message and the preceding text fields.
