### ISSUE TITLE
Bonfire: Mutations. Issue passing with wrong code

### ISSUE THREAD

**Issue by erratadei** [FreeCodeCamp/FreeCodeCamp#1754]
Hello.
Just to let you know that bonfire http://www.freecodecamp.com/challenges/bonfire-mutations needs another *expect to be false* in order to prevent the following code (the one I entered) from passing the test: 
```Javascript
function mutation(arr) {
  var arr2 = arr[1].split("");
  console.log(arr2);
  var match = -1; 
  for (i = 0; i < arr2.length ; i++){
  match = arr[0].indexOf(arr2[i]);
 }
  if(match === -1){
  return false;
  } else {
  return true;
}

}

mutation(['hello', 'hey']);
```
in this code, the 'false' value depends ONLY on the .indexOf result of the last character checked within the array. Maybe adding an **expect(mutation(['hello', 'hallo'])).to.be.false** makes the trick and will require some more changes if other users choose the same type of solution. 

Sorry if I'm not posting this in the correct place. Best Regards

**Comment by benschenker** [comment]
Looks like this has been fixed
