### ISSUE TITLE
Api projects not validating

### ISSUE THREAD

**Issue by janosimas** [freeCodeCamp/freeCodeCamp#17548]
#### Describe your problem and - if possible - how to reproduce it

1 - The api projects validation will approve any url, even google (https://www.google.com). 
2 - both glitch and github fields must be filled

#### Add a Link to the page with the problem

All api projects.
https://learn.freecodecamp.org/apis-and-microservices/apis-and-microservices-projects/file-metadata-microservice

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66
* Operating System: Ubuntu 16.04

**Comment by thecodingaviator** [comment]
It will, because this cannot be validated by tests and has to happen manually, we can't do this for every user and this is a project so we expect academic honesty from them. If you require more clarification on how this works reply over here or close the issue

**Comment by PortableStick** [comment]
Is this still true? Are there no automated tests for the API and microservices projects right now?

**Comment by RandellDawson** [comment]
@ValeraS I see tests written for these challenges.  Why do they not seem to work?

**Comment by ValeraS** [comment]
@RandellDawson for now, we do not run tests for projects. It's not so difficult to change. But I see tests written only for one project ([Timestamp Microservice](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/timestamp-microservice.english.md)). All other backend projects contain tests with empty `testString`s.

**Comment by RandellDawson** [comment]
@ValeraS Yeah after my last reply, I realized the only one which had tests was the Timestamp Microservices.     Shouldn't we implement the test functionality and then start writing applicable tests for these projects?

**Comment by christophrus** [comment]
@RandellDawson @ValeraS The tests are already written on [this glitch](https://narrow-plane.glitch.me). I guess they just need to be transitioned into the .md files?
