### ISSUE TITLE
Wrong link in URL Shortener Microservice

### ISSUE THREAD

**Issue by janosimas** [freeCodeCamp/freeCodeCamp#17550]
#### Describe your problem and - if possible - how to reproduce it

The link example of shortened url is to (I imagine) an old url.

current link: https://thread-paper.hyperdev.space/api/shorturl/3
should be: https://thread-paper.glitch.me/api/shorturl/3

#### Add a Link to the page with the problem

https://thread-paper.glitch.me

**Comment by anku255** [comment]
@Bouncey @raisedadead This seems like a very easy thing to fix. Who is the owner of the glitch projects?

**Comment by RandellDawson** [comment]
This appears to already be resolved on the beta site (https://www.freecodecamp.rocks/learn/apis-and-microservices/apis-and-microservices-projects/url-shortener-microservice).  I am closing this issue.  Please feel free to ask for it to be reopened, if you find this still to be a problem on the beta site.  The beta site will soon be moved to production.

**Comment by momozor** [comment]
@RandellDawson I think the wrong links only causing issues in https://thread-paper.glitch.me. It is still not fixed yet, unfortunately. So, I think this issue should be reopened.

**Comment by RandellDawson** [comment]
@momozor Which link is a problem and what is the problem you are experiencing when you click on the link?

**Comment by RandellDawson** [comment]
OK.  This is still a problem.  @raisedadead It appears there is a camperbot username which has access to make changes to this Glitch project.

Line 33 needs to be changed from:
```
        <a href="https://thread-paper.hyperdev.space/api/shorturl/3">
```
to:
```
        <a href="https://thread-paper.glitch.me/api/shorturl/3">
```

Who has access to the `camperbot` credentials to make this change?
