### ISSUE TITLE
JavaScript algorithms... projects are not counted as projects

### ISSUE THREAD

**Issue by psitronic** [freeCodeCamp/freeCodeCamp#17555]
#### Describe your problem and - if possible - how to reproduce it

I have created a new/fresh account to claim ONLY the JavaScript related certificate and finished all corresponding projects. However, the Welcome page shows that there are 5 challenges and 0 projects completed (see screenshots). So these projects are not counted as projects but rather as challenges which are not included in certification.

#### Add a Link to the page with the problem
https://www.freecodecamp.org/
https://www.freecodecamp.org/settings

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Linux

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/32975200/41282448-5fa01a18-6e34-11e8-82dc-dd7a4a586647.png)
![image](https://user-images.githubusercontent.com/32975200/41282455-6408ed00-6e34-11e8-9e93-19af5982e477.png)
![image](https://user-images.githubusercontent.com/32975200/41282466-6a2fe1de-6e34-11e8-8a70-16c4bec6f181.png)

**Comment by Nirajn2311** [comment]
No, they are not included. To get the certificate you need to complete every exercis for that certificate.

**Comment by psitronic** [comment]
@Nirajn2311 
Are you sure? [Here](https://forum.freecodecamp.org/t/10-major-freecodecamp-improvements-that-are-live-now/192130) it states opposite:
> Improvement #2: New Certifications
... And now we also offer 6 new certifications.
Each of these new certifications has **5 required projects** that you must complete. **All the other coding challenges are optional**, and serve to prepare you for these projects.
>

**Comment by Kornelijus** [comment]
This seems to be the same problem as #17334 and a fix is being discussed #17335 .
@Nirajn2311 You should be able to claim the certificate right after completing the 5 projects, the rest is there to teach you more about the subject. This might not be easy to do though, as there's currently a bug with the settings page.

**Comment by johnkennedy9147** [comment]
@psitronic FYI, the project count on front page is wrong per #17334 but you can actually claim the certificate, go to settings, scroll down about half way and you will see the 5 projects listed and a claim certificate button.

**Comment by psitronic** [comment]
@johnkennedy9147 Unfortunately, I still cannot claim the certificate. I cannot do it for my both accounts, old and new, assigned to different email addresses. 

![image](https://user-images.githubusercontent.com/32975200/41311502-beefb6e0-6e84-11e8-821e-cabb0d47f0da.png)

**Comment by johnkennedy9147** [comment]
@psitronic this looks like #17278. A fix was put in today but a database update is required before already affected users have their issue fully resolved but you can workaround the issue by resubmitting all of the JS projects.

**Comment by psitronic** [comment]
@johnkennedy9147  Great job! It works fine now! Thanks!

**Comment by johnkennedy9147** [comment]
@psitronic :+1: 
this issue can be closed
cc @raisedadead
