### ISSUE TITLE
Issue in Managing Packages with Npm - How to Use package.json, the Core of Any Node.js Project or npm Package

### ISSUE THREAD

**Issue by pradeshkumarg** [freeCodeCamp/freeCodeCamp#17558]
Getting the below error in console when I click I've completed this challenge(Ctrl + Enter)

```Failed to load https://***********.glitch.me/_api/package.json: No ‘Access-Control-Allow-Origin’ header is present on the requested resource. Origin ‘https://learn.freecodecamp.org 1’ is therefore not allowed access. The response had HTTP status code 404.```

https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package

Forum Link:

https://forum.freecodecamp.org/t/managing-packages-with-npm-how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package/198736

**Comment by anku255** [comment]
@pradeshkumarg Hi! Did you clone the `FCC starter project` using this [link](https://glitch.com/#!/import/github/freeCodeCamp/boilerplate-npm)?

I tried it just now and the tests pass. If you are still facing this issue then please post your glitch project link so that we can inspect the issue.

**Comment by pradeshkumarg** [comment]
Hi @anku255 ,

It worked wen I cloned the project but not when I created a new Project. Thanks.

**Comment by anku255** [comment]
@pradeshkumarg If you are no longer facing the problem then can you please close this issue?

**Comment by charisTheo** [comment]
I tried to clone the Github Repo and when I put the package.json file url in the solution I get:

```
// running tests
404: Not Found

// tests completed
```

**Comment by bruno-rodrigues** [comment]
Hi @pradeshkumarg, 

I believe this needs to be reopened because you are appending "/_api/package.json" when I try to submit a github link. (tried with the example repo and a repo I started to go through this course)

![Screen Shot 2019-12-31 at 1 14 19 am](https://user-images.githubusercontent.com/7862345/71585587-3b9f1d80-2b6b-11ea-969f-b86b02921bda.png)
