### ISSUE TITLE
Message "undefined challenge" in bootstrap exercise 1

### ISSUE THREAD

**Issue by ashi2014** [FreeCodeCamp/FreeCodeCamp#1755]
Challenge http://beta.freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

After completing the exercise and clicking on "go to my next challenge", the following message appears at the top:
![image](https://cloud.githubusercontent.com/assets/7401767/9267524/6067f438-4205-11e5-8eb0-4dc376197916.png) and the code reverts back to the original.

**Comment by BerkeleyTrue** [comment]
This has been fixed.

Happy Coding!
