### ISSUE TITLE
Wrap no user found Error

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#17559]
https://github.com/freeCodeCamp/freeCodeCamp/blob/4f77da02be4aa3ac8250c26dd5b6a32484d04e1e/common/models/user.js#L471-L490

The Error being thrown for `no user found` (line 485) should be wrapped in a `handledError` like we do for many other errors relating to user input.

**Comment by Manish-Giri** [comment]
@Bouncey I'd like to give this a shot. Were you referring to the `wrapHandedError` function declared [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/server/utils/create-handled-error.js#L11) and used to wrap errors, like [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/models/User-Identity.js#L62)?

**Comment by raisedadead** [comment]
@Manish-Giri yes to all of your queries!

**Comment by sdabhi23** [comment]
@raisedadead @Manish-Giri has this issue been resolved? If not, I am interested in taking it up.

**Comment by raisedadead** [comment]
Hi yes this has been resolved. Sorry, we forgot to close this. Thanks.
