### ISSUE TITLE
Open curriculum to current challenge

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#17557]
#### Describe your problem and - if possible - how to reproduce it
When you open the curriculum in a new session it opens like this...

<img width="494" alt="screen shot 2018-06-12 at 9 29 32 am" src="https://user-images.githubusercontent.com/20648924/41296785-4fb71ffe-6e23-11e8-8fe9-bee2b8e5cfef.png">

If you navigate to your current challenge and click on it, then go back to the curriculum (in the same session) - it will have the same section/sections open that you had open before but not scroll to where you were 

It would be nice if the curriculum/map navigated to your current challenge when you open it

**Comment by raisedadead** [comment]
Issue moved to [freeCodeCamp/learn #171](https://github.com/freeCodeCamp/learn/issues/171) via [**ZenHub**](https://www.zenhub.com/)
