### ISSUE TITLE
Basic CSS: Change the Color of Text

### ISSUE THREAD

**Issue by codewatzen** [freeCodeCamp/freeCodeCamp#17569]
![firefox_2018-06-13_15-26-20](https://user-images.githubusercontent.com/25915728/41376446-dee9c77a-6f1e-11e8-9117-2a3aa85a1a07.png)
![chrome_2018-06-13_15-27-15](https://user-images.githubusercontent.com/25915728/41376463-ea17548c-6f1e-11e8-8936-2f887df13bd3.png)
![firefox_2018-06-13_15-28-45](https://user-images.githubusercontent.com/25915728/41376466-ec125142-6f1e-11e8-8821-ed85a829b564.png)
![chrome_2018-06-13_15-29-06](https://user-images.githubusercontent.com/25915728/41376468-edb81a0e-6f1e-11e8-9bd7-4343e070cd64.png)

Doing the Basic CSS: Change the Color of Text practice, this code: 

`<h2 style="color:red;">CatPhotoApp</h2>`

is wrong in Firefox but in Chrome it works. In Firefox, you get a pass on the last challenge but not the red challenge. 

Update: Use CSS Selectors to Style Elements is having the same problem. 
This code: 
```
<style>
  h2 {color:blue;}
</style>
```
works in Chrome but when using Firefox all challenges but "Your h2 element should be blue." pass. 

Edit: Added the pictures of both challenges from Chrome and Firefox. 

Chrome version 67.0.3396.799
Firefox version 60.0.2

**Comment by Nirajn2311** [comment]
Could you please edit your issue to include your firefox version,steps to reproduce and screenshot of the error.

**Comment by codewatzen** [comment]
Updated my post.

**Comment by thatnini** [comment]
Can you try disabling the addon you are using in Firefox to make it dark? I'm wondering if that is interfering with the tests somehow?

**Comment by codewatzen** [comment]
Ah yep that fixed it. Should have checked that before posting.

**Comment by Nirajn2311** [comment]
Could you close this issue if your problem has been solve.

**Comment by maxdevjs** [comment]
I had the same issue. This should be, hopefully, made explicit in some place:

- searched in the forum and did not find references to this issue

- searched in Github and did find this issue after a while

Also, I use the `night mode`, so was not really straightforward to think about an extension :)
