### ISSUE TITLE
Project count includes legacy projects

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#17567]
It shows I have completed 30/30 projects 

<img width="446" alt="screen shot 2018-06-13 at 8 00 00 am" src="https://user-images.githubusercontent.com/20648924/41352908-53a56450-6ee0-11e8-8aa7-dcf099717b05.png">

<hr>

Even though I haven't done a number of the new projects...

<img width="447" alt="screen shot 2018-06-13 at 8 00 51 am" src="https://user-images.githubusercontent.com/20648924/41352922-61721588-6ee0-11e8-9dfd-e44b7fc34411.png">

<hr>

It must be counting the legacy projects in the `take home` section...

<img width="458" alt="screen shot 2018-06-13 at 8 00 36 am" src="https://user-images.githubusercontent.com/20648924/41352956-76afc260-6ee0-11e8-8dd9-1e8278670139.png">

<hr>

* Browser Name: Firefox
* Browser Version: 60.0.1
* Operating System: High Sierra

possibly related to https://github.com/freeCodeCamp/freeCodeCamp/issues/17334

### Possible Solutions
`Add all the projects to the project count`
`Don't include the take home projects in the count`

**Comment by raisedadead** [comment]
Yes, this is a duplicate.
