### ISSUE TITLE
"Escaping quotes in literal strings" test is still failing

### ISSUE THREAD

**Issue by aschalau** [freeCodeCamp/freeCodeCamp#17563]
Hello,

This doesn't seem to be fixed as the other issues are closed out regarding this issue.

I seen these and others about this that have been closed out:
#16344
#16476

I am running Chromium - Version 66.0.3359.181 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

![image](https://user-images.githubusercontent.com/1645250/41209311-b922b9e8-6cf8-11e8-9857-0806aa9846c3.png)

If I am mistaken, please let me know.

Thank you

**Comment by aschalau** [comment]
@Manish-Giri and @Nirajn2311  :disappointed: 

Thank you for pointing me in that direction.  I think I read that as don't change the line.  I need to slow down and comprehend what is put on the screen.  

Sorry to waste your time with this.

**Comment by Manish-Giri** [comment]
@aschalau It's all good, that's what we are here for! Happy Coding!
