### ISSUE TITLE
Test Error Expects Wrong Average Value for Ratings

### ISSUE THREAD

**Issue by matthew-t-smith** [freeCodeCamp/freeCodeCamp#17561]
#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 60.0.2 (up-to-date)
* Operating System: macOS High Sierra, v10.13.5

#### If possible, add a screenshot here

<img width="407" alt="screen shot 2018-06-13 at 11 16 17" src="https://user-images.githubusercontent.com/15874467/41322099-4c823516-6efb-11e8-86b4-728d072b6588.png">
<img width="227" alt="screen shot 2018-06-13 at 11 16 38" src="https://user-images.githubusercontent.com/15874467/41322100-4d1be5c6-6efb-11e8-969e-15ca71427906.png">

**Comment by thatnini** [comment]
While (8.8 + 8.6 + 9.0 + 8.3 + 7.9) / 5 = 8.52, the instructions say

> Use reduce to find the average IMDB rating of the movies directed by **Christopher Nolan**.

As Christopher Nolan didn't direct all of the movies listed, why do we need to find the average of all 5?

In other words, don't we need to find the average of the movies that only have `"Director": "Christopher Nolan"` listed, which does comes to 8.675?

**Comment by matthew-t-smith** [comment]
Good catch. I missed the “Nolan” qualification. I’ll see that it stays as/is. Thank you.

**Comment by scissorsneedfoodtoo** [comment]
@thatnini, thank you for pointing that out! I also missed that. I'll revert the PR now.

**Comment by raisedadead** [comment]
Reopened with https://github.com/freeCodeCamp/freeCodeCamp/pull/17568

**Comment by raisedadead** [comment]
Can someone confirm that no change is required? If yes please comment and close.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, no change is required for this challenge. Here's a working solution:

```
let nolanFilms = 0;

const averageRating = watchList.reduce((acc, obj) => {
  if (obj.Director === "Christopher Nolan") {
    nolanFilms++;
    return Number(obj.imdbRating) + acc;
  }

  return acc;
}, 0) / nolanFilms;
```

With that the original test, 8.675, passes.
