### ISSUE TITLE
React: Use the Lifecycle Method componentWillMount - method is deprecated in modern React

### ISSUE THREAD

**Issue by P1xt** [freeCodeCamp/freeCodeCamp#17574]
#### Describe your problem and - if possible - how to reproduce it
This React lesson is out of date. The React Lifecycle Method `componentWillMount` has been deprecated and use of it is actively discouraged in the official docs.

https://reactjs.org/docs/react-component.html#legacy-lifecycle-methods

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react/use-the-lifecycle-method-componentwillmount

**edited to add:**
The following page also uses deprecated methods (`componentWillReceiveProps()`)
https://learn.freecodecamp.org/front-end-libraries/react/manage-updates-with-lifecycle-methods

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 66.0.3359.181 (Official Build) (64-bit)
* Operating System: Manjaro 17.1.10

**Comment by thecodingaviator** [comment]
@ezioda004 / @P1xt this has been fixed by #19715 , please close

**Comment by ezioda004** [comment]
@thecodingaviator You've added in the guide not in the curriculum section.

**Comment by thecodingaviator** [comment]
Or, for now we can get rid of the challenge itself?

**Comment by ezioda004** [comment]
Getting rid of challenge isn't that easy. 
Besides, if we do get rid then lifecycle methods would be incomplete.

Regardless, this need to discussed with the core team.

**Comment by thecodingaviator** [comment]
We could also change it to ` UNSAFE_componentWillMount() ` i.e. how it is used now

**Comment by ezioda004** [comment]
@thecodingaviator And introduce new challenge while changing this to `UNSAFE_componentWillMount()`? 
There are 2 issue with that:
1. That'd require adding new challenge, which we're hoping to avoid.
2. Teaching deprecated methods should be avoided as much as possible. We'd like to keep the information in the challenges relevant.

**Comment by ezioda004** [comment]
@thecodingaviator It's not same. Every challenge has an associated unique ID with it - so even if the update may seem like a new challenge, it's simply replacing the old one.

**Comment by thecodingaviator** [comment]
Oh okay
