### ISSUE TITLE
Bonfire: Smallest Common Multiple Tests are incorrect

### ISSUE THREAD

**Issue by tamienne** [FreeCodeCamp/FreeCodeCamp#1757]
expect(smallestCommons([1,5])).to.equal(60);expected 5 to equal 60
expect(smallestCommons([5,1])).to.equal(60);expected 5 to equal 60
expect(smallestCommons([1,13])).to.equal(360360);expected 13 to equal 360360

**Comment by jmcduffie32** [comment]
@tamienne The tests are ok. I think you might be misreading the problem. The two numbers it is giving you are the end points of a range, so when it says smallestCommons([1,5]) it wants the smallest number that is evenly divisible by 1,2,3,4, and 5. I messed this one up to begin with as well, but the tests are correct.

**Comment by tamienne** [comment]
Could you include that example into the directions so people don't get confused? My pair partner had the same issue as me when we read the problem.
Thanks!Kathy

Date: Fri, 14 Aug 2015 11:23:17 -0700

**Comment by rtperson** [comment]
Please see my pull request for a suggested edit that makes this bonfire's instructions clearer. 

Thanks!

**Comment by tamienne** [comment]
Closed.

Looks great!
