### ISSUE TITLE
Audio element closing tag not accepted

### ISSUE THREAD

**Issue by camachado** [freeCodeCamp/freeCodeCamp#17577]
#### Describe your problem and - if possible - how to reproduce it
Audio element closing tag not being accepted. The error message below is produced:

"Make sure your audio element has a closing tag."

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/improve-accessibility-of-audio-content-with-the-audio-element/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version:  Version 67.0.3396.87 (Official Build) (64-bit)
* Operating System: Windows Pro 10 Build 17134

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/2438129/41387392-aaafba38-6f54-11e8-8b54-9158d5ef8d79.png)

**Comment by mpmaan** [comment]
Your code has a ```/``` before the closing bracket ```>``` of ```source``` tag. Also you should not give ```id``` attribute to ```audio``` tag. Run tests after fixing these.

**Comment by camachado** [comment]
Thanks. Yes the `/` before the closing bracket of the source tag was a typo. I removed the `id` attribute from the `audio` tag and the test passed.

The example used in the lesson needs to be updated as it has the `id `attribute in the `audio `tag.

![image](https://user-images.githubusercontent.com/2438129/41392455-8e297aba-6f6e-11e8-9649-ce3c75d40275.png)

**Comment by Nirajn2311** [comment]
So if we remove the id tag in the example, it's okay.
