### ISSUE TITLE
Person first language - Accessibility

### ISSUE THREAD

**Issue by rhuss623** [freeCodeCamp/freeCodeCamp#17579]
#### Describe your problem and - if possible - how to reproduce it
This isn't really a coding issue.  This has to do with using "person-first language" for the Applied Accessibility modules.  First, I want to say that I LOVELOVELOVE that you are teaching Applied Accessibility!  Thank you so much! I thought I was going to need to scour the web for good resources on building accessible sites.  Again, Thank You Thank You Thank You!!! 

It's possible that you know all about this and just let it slip, but I noticed the "Improve Accessibility of Audio Content with the audio Element" module has the sentence "Audio content also needs a text alternative to be accessible to _the deaf or hard of hearing_."  The only issue w/ this sentence is the use of "the deaf..." as opposed to "people who are deaf or hard of hearing."  

This may seem inconsequential, but it's important to many people w/ disabilities b/c it puts an emphasis on the person being... well... a person.  Saying "the deaf, the blind, or a paraplegic" is avoided because it reduces a person to their disability, whereas "a person who is deaf, a person with visual impairments, or a person with paraplegia" puts an emphasis on humanity first and the disability second. 

If you want any other tips on p.c. wording for accessibility, etc., that's my area!  Again, thanks so much for including this section!! 

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by moT01** [comment]
Thanks for pointing this out @rhuss623, let us know if you find anything else - the issue can be fixed here - https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/applied-accessibility.json#L476

**Comment by twhite96** [comment]
Got it. Will fix tonight.
