### ISSUE TITLE
Completed all algorithms but it did not save

### ISSUE THREAD

**Issue by JamesStaffordCoyte** [freeCodeCamp/freeCodeCamp#17572]
#### Describe your problem and - if possible - how to reproduce it
I completed all the JavaScript Algorithms and Data Structure Projects but the final two are not showing up as completed and my code is gone. Will this be corrected or do I have to redo the problems?

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 
* Operating System: MacOS

#### If possible, add a screenshot here
![screen shot 2018-06-13 at 1 15 06 pm](https://user-images.githubusercontent.com/26333632/41375746-d5af8cca-6f0b-11e8-9a18-5721745e2688.png)

**Comment by JamesStaffordCoyte** [comment]
![screen shot 2018-06-13 at 1 16 22 pm](https://user-images.githubusercontent.com/26333632/41375811-04f4f538-6f0c-11e8-9492-61d2cca922d0.png)

**Comment by luandy64** [comment]
I also have the same problem.
<img width="862" alt="screen shot 2018-06-13 at 5 50 59 pm" src="https://user-images.githubusercontent.com/19473996/41382688-ec1213e4-6f32-11e8-910d-87ade1d93116.png">
<img width="573" alt="screen shot 2018-06-13 at 5 51 06 pm" src="https://user-images.githubusercontent.com/19473996/41382689-ec308a4a-6f32-11e8-927d-0f9aa6513fcf.png">
<img width="757" alt="screen shot 2018-06-13 at 5 51 56 pm" src="https://user-images.githubusercontent.com/19473996/41382690-ec4bdbec-6f32-11e8-976b-a4bf2c16bcc9.png">

**Comment by DivineInfinity** [comment]
I have the same problem except it's only the last one that's showing up as incomplete
![screenshot 3](https://user-images.githubusercontent.com/19728508/41476736-09d7393c-70e0-11e8-8851-fd1d26d1d5c0.png)

**Comment by luandy64** [comment]
Hey @JamesStaffordCoyte and @DivineInfinity,

I know this may only be a temporary fix, but if you go and complete the challenges again, it corrects itself on the Settings page. I happened to have my Cash Register code and pasted it in again and hit Run Tests; now I just need to rewrite the Telephone Number Validator and I'll report back with my findings.

**Comment by luandy64** [comment]
On a different note, clicking on "Complete Project" on the Settings Page leads to a page that says
"Sorry, we couldn't find a page for that address.". I don't know if anyone else sees it.

**Comment by luandy64** [comment]
Resubmitting the challenges does work, I have my certificate now.

**Comment by thecodingaviator** [comment]
@JamesStaffordCoyte does this work for you too now, if so, please close this issue.

**Comment by thecodingaviator** [comment]
@ezioda004 I think a month was enough time for any of the users to reply if they were still interested. I think we should close this issue
