### ISSUE TITLE
Starter project for Node and Express lessons uses Node.js 4

### ISSUE THREAD

**Issue by P1xt** [freeCodeCamp/freeCodeCamp#17586]
#### Describe your problem and - if possible - how to reproduce it
https://glitch.com/#!/import/github/freeCodeCamp/boilerplate-express/

The boilerplate for these lessons has node engine explicitly set at 4.4.5 which reached eol in April and thus is no longer available within glitch.

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/apis-and-microservices/basic-node-and-express

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by ztickm** [comment]
Can confirm I noticed that while going through the project.  
Glitch automatically uses 8.11.2 though (see screenshot), so nothing breaking on Glitch. Yet it can be potentially a bit risky if someone uses the boilerplate on their local machine, as the version is un-maintained.
**But** I think that this isn't the correct repo for this issue.
I have opened an [issue](https://github.com/freeCodeCamp/boilerplate-npm/issues/9) and a [PR](https://github.com/freeCodeCamp/boilerplate-npm/pull/10) on the [repo](https://github.com/freeCodeCamp/boilerplate-npm) that contains the boilerplate
![screenshot](https://user-images.githubusercontent.com/7467165/41454577-36fdbc80-707a-11e8-9cfd-7fd85418e2d8.png)
