### ISSUE TITLE
Example missing in basic js - word blanks

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/freeCodeCamp#17580]
#### Describe your problem and - if possible - how to reproduce it
In the description of the exercise at the end of the first paragraph, I think there should be an example according to the last sentence.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/word-blanks

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 66.0.3359.181
* Operating System: Windows 10 Home 1803

#### If possible, add a screenshot here
![screenshot 2](https://user-images.githubusercontent.com/36357875/41413331-d00445fc-6ff3-11e8-8910-fb1a47a4e73e.png)

**Comment by Nirajn2311** [comment]
Yeah, it will work. If you’re free you may work on it.

**Comment by anku255** [comment]
@Nirajn2311 I was free so, I have created a PR [#19](https://github.com/freeCodeCamp/curriculum/pull/19). Let's see what maintainers think about this issue.
