### ISSUE TITLE
Email submit test for Build a Product Landing Page doesn't work

### ISSUE THREAD

**Issue by cmccormack** [freeCodeCamp/freeCodeCamp#17587]
#### Describe your problem and - if possible - how to reproduce it
When submitting a form with an `email` query to the following endpoint:
>https://www.freecodecamp.org/email-submit

using GET or POST I receive the following message:
>We could not find a user by the name of "email-submit"

The URL will look something like the following when the request is sent:
https://www.freecodecamp.org/email-submit?email=me%40email.com

#### Add a Link to the page with the problem
https://www.freecodecamp.org/email-submit?email=me%40email.com
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-product-landing-page/

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by P1xt** [comment]
@cmccormack I'm just wrapping up that project myself. The endpoint isn't what will make the submit test case fail, in fact you can set your action on the form to "#". What will cause that test to fail is if you don't give your email element an id, a type and a name (it's the name part that's the gotcha)

**Comment by cmccormack** [comment]
I do understand the tests will still pass if you configured them correctly, but if FCC is going to provide a URL to which we can test the email submission against I believe it should give some kind of positive confirmation instead of an error that may force the submitter to think they made a mistake.

**Comment by moT01** [comment]
There isn't exactly a good response, but it looks like something changed to where you don't get the error message anymore.

**Comment by ahmadabdolsaheb** [comment]
It seems that there is a user with email-submit username. : ).
