### ISSUE TITLE
Can't get this javascript situation to pass

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#1758]
http://localhost:3000/challenges/waypoint-nest-one-array-within-another-array 

https://www.evernote.com/l/AlzohqRj4RpG8LZ3nUkWZzeZnREeZ9ekkTcB/image.png

**Comment by benmcmahon100** [comment]
I think that just needs a small tweak to the regex. I'll sort it now!
