### ISSUE TITLE
Navigation Improvements - individual challenges should link to curriculum map in context

### ISSUE THREAD

**Issue by AdventureBear** [freeCodeCamp/freeCodeCamp#17582]
#### Describe your problem and - if possible - how to reproduce it
I was helping a user on the forum with a challenge in functional programming. I clicked on the link and was able to solve the challenge and wanted to provide in context help to the poster...meaning I wanted to see what was taught prior to that challenge about functional programming, so that I could help the poster work through topics they already knew. 

However, it was very challenging ot work backwards from that challenge to see what section the challenge was in and where in the functional programming section the exact challenge fell in order. 

A breadcrumb like navigation would be helpful so that individual challenges can be placed in context without resorting to the curriculum search and choosing randomly from the list hoping to find the "right" place.  

With the current navigation, if the user is doing challenges out of order (like me skipping to the new curriculum functional programming to help the poster), to get back to it, say I wanted to complete it, I have to click through each section of the curriculum to drill down again and find it. 

#### Add a Link to the page with the problem
https://forum.freecodecamp.org/t/how-to-get-tea4teamfcc/200015  

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.62 (Official Build) (64-bit)
* Operating System: High Sierra

**Comment by moT01** [comment]
Closing as stale. Thanks for the suggestion, I like it - but this hasn't gotten any attention. Feel free to create a new issue around this and maybe it will get some more traction. Thanks and happy coding!

**Comment by RandellDawson** [comment]
@raisedadead Is this something we would want to remain open and put on the road map?
