### ISSUE TITLE
Typo in "Set a Content Security Policy with helmet.contentSecurityPolicy()"

### ISSUE THREAD

**Issue by raditotev** [freeCodeCamp/freeCodeCamp#17594]
#### Describe your problem and - if possible - how to reproduce it
Typo in the description.

#### Add a Link to the page with the problem
[Set a Content Security Policy with helmet.contentSecurityPolicy()](https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-with-helmetjs/set-a-content-security-policy-with-helmet-contentsecuritypolicy)

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/5617443/41469519-676c3da8-70a5-11e8-95c8-9e06536e4731.png)

**Comment by anku255** [comment]
@raditotev Just to make it clear, you are suggesting to change `in` to `is`. Is there any other typos that you found in this challenge?

**Comment by raditotev** [comment]
Correct. That's the only typo I have found. I know it's minor issue but it will be a good opportunity to fix for beginners.

**Comment by anku255** [comment]
@moT01 I am a little confused about challenge files. What about this file in `curriculum` repo?

https://github.com/freeCodeCamp/curriculum/blob/6cb3732bd0bddf5177e121785c3b1a22ca2432ae/challenges/06-information-security-and-quality-assurance/helmetjs.json#L196

Where should one correct the mistakes?

**Comment by moT01** [comment]
@anku255 im confused at the moment as well - there's some changes in progress regarding where the challenges are so I'm not sure if we should be making PR's involving seed files to the main repo or the curriculum repo - I would guess it will be over there in future but at the moment I'm not sure what's best

**Comment by Nirajn2311** [comment]
For now I am solving all typos in curriculum, so if anyone finds any typo in the challenges please refer me.
