### ISSUE TITLE
Unable to Claim Certification of APIs and Microservices Projects

### ISSUE THREAD

**Issue by AndrewJBateman** [freeCodeCamp/freeCodeCamp#17595]
I completed all projects and subjects for APIs and Microservices Cert, but when I claim the cert the message "it looks like you have not completed the necessary steps. Please complete the required challenges to claim the APIs and Microservices. I have accepted our Academic Honesty Policy. I redid the projects to the new beta requirements. 

Please let me know what i have to do to get the certificate.

Link to the page with the problem:
https://www.freecodecamp.org/settings

Tell us about your browser and operating system
Browser Name: Chrome
Browser Version: Versión 67.0.3396.87 (Build oficial) (64 bits)
Operating System: Windows 10 Pro
![image](https://user-images.githubusercontent.com/27190679/41474753-2229f614-70bd-11e8-89f3-7c80e388a0fd.png)

Thanks

**Comment by raditotev** [comment]
This issue has been raised already #17522

**Comment by Asjas** [comment]
Hi @AndrewJBateman 

This issue is a duplicate of #17522. I would suggest closing this and typing a comment in issue #17522 so that the problem is contained in one issue and not spread out across multiple issues.

**Comment by AndrewJBateman** [comment]
This issue is a duplicate of #17522 so I have closed it.
