### ISSUE TITLE
Broken Link in Introducing Inline Styles of the React Front End Library curriculum

### ISSUE THREAD

**Issue by iarobinson** [freeCodeCamp/freeCodeCamp#17596]
The link in this paragraph needs to be like this:

"There are other complex concepts that add powerful capabilities to your React code. But you may be wondering about the more simple problem of how to style those JSX elements you create in React. You likely know that it won't be exactly the same as working with HTML because of <a target=\"_blank\" **href=\"front-end-libraries/react/define-an-html-class-in-jsx/\"**> the way you apply classes to JSX elements</a>.",

The href in the above JSON element is currently (define-an-html-class-in-jsx) and this creates a 404 error.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react/introducing-inline-styles

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 66.09
* Operating System: macOS Sierra

#### Solution

I have a forked repository with the broken link properly formatted (https://github.com/iarobinson/freeCodeCamp) - I just don't know how to do a pull request properly...

**Comment by Vimal-Raghubir** [comment]
Hi @iarobinson. Follow the steps below to submit a successful PR to this repo:
1. What you need to do is create a new branch from the staging branch. NOTE: This does not mean make your commit on the staging branch. Name the branch Fix/*shortdescription* such as Fix/Inline-Styles-Broken-Link.
2. add the commit to this branch. Prefrably make your commit message titled "Fix: broken link......"
3. Create the pull request
4. Tick the boxes that apply to your change. Hint: put an x inside the [] for the boxes you want to tick.
5. Add the issue title in the comment section like #17597.
6. Submit PR and you should be good to go :+1: .

Hope this helps :100: .

**Comment by raisedadead** [comment]
Hi @Vimal-Raghubir thanks a lot for chiming in, nice work.

**Comment by iarobinson** [comment]
I plan to submit a properly formatted PR today to fix this broken link. Thanks for the calm and patient support.
