### ISSUE TITLE
Request: Move wiki to a GH Pages site

### ISSUE THREAD

**Issue by onebree** [FreeCodeCamp/FreeCodeCamp#1759]
Looking at the FCC wiki, there are over 140 articles currently published. Some of them only say "coming soon" ([example](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/bonfire-check-for-palindromes)), while others are just a sentence. I do not see these as fruitful articles. I mean, why [explain that Gitter uses emoji](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/emoji), when you can read that information straight from Gitter.im?

**I am proposing that we move the wiki (with current articles) to a Github Pages project site.**

1. Continued use of Github-Flavored Markdown (with a static-site generator like [Jekyll](http://jekyllrb.com))
2. Those watching the repo will be notified of new wiki posts when submitted as pull requests
  - Help with proper translations (whether English or another language)
  - Decide whether the article should be improved, or submitted at all
  - More transparent community involvement
3. Organize articles into topic-related folders
  - Navbar link would point to a folder for, example, all Bonfire-related articles
  - Easier to navigate, rather than scrolling through a sidebar of 140+ articles (currently)
4. Properly attribute the article's author by including name, photo, and information.
  - This is possible on the current wiki, but is not formatted well.
5. Github contribution streaks do not include wiki edits... but they do include pull requests, issues, and repository commits!
6. Much of the the HTML/CSS on [FreeCodeCamp.com](http://freecodecamp.com/) can be reused for the Github site

I am suggesting Jekyll, mainly because I already have experience with it. I use it for [my personal blog](onebree.github.io), and find it very powerful. While it is written in Ruby, someone interested in contributing only needs to worry about Markdown. (Posts begin with some YAML FrontMatter, but this can be copied from another already-existing post.)

A great example of a site using Jekyll is the [Stack Exchange Blog](https://github.com/StackExchange/stack-blog). As you can see, while all posts are within a single folder, each point to a different layout (company, engineering, etc), which directs the article to a different section of the site. Now, StackExchange used a Jekyll start-up repository as a skeleton, but Jekyll is powerful enough to allow multiple folders for posts. 

I can help to setup and maintain the site using Jekyll. My strongest language is Ruby, so I understand Jekyll's source code. And since I already use it for my own site, I have experience and am already interested in learning more about it.

**Comment by QuincyLarson** [comment]
Hi @onebree Thank you for this well thought-out suggestion.
You've pointed out merits to having an external wiki.

**Comment by onebree** [comment]
I'm on my phone currently, so let me be brief. (I can elaborate later if needed.) Although Wikipedia itself is a set of unorganized articles, its child sites do have structure. For example, Wikibooks. Although each page stands alone, they are ultimately arranged in chapter format, like a textbook. This structure allows you to navigate and read articles on one subject.

My main issues with the wiki are that it is difficult to see all available entries, and there is no critique or comment system (that I'm aware of). The only list of entries is a very small sidebar. I think this could be improved with a Table of Contents page, either as a wiki article or as a markdown document in the repository. (I like the second idea, because then you can, possibly, render that ONE page on FCC to replace field guides. With stubs being in red like Wikipedia.)

If you want someone to manage such a TOC, I have no problem doing that.

My second point is critique and comment. On a repository you can comment on a commit. I don't THINK you can do that on a Github wiki. Although anyone can edit the page, comments mean fewer issues submitted for that article and gives a chance for someone to share their thoughts if they don't have the time to edit themselves.

My main concern is the quality of the articles. And with that, by "watching" the repository you are not alerted when new articles are submitted, so if someone wanted to check for quality, they would have to by hand

Okay I have to go now. Thank you for your reply btw
