### ISSUE TITLE
Style codemirror text area to match codemirror area

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/freecodecamp#176]
On first render, camper see's an unstyled textarea.

After, codemirror takes over and hides textarea and adds it's own box. This initial flash is hideous and makes puppies cry.

**Comment by BerkeleyTrue** [comment]
This has not been fixed on the Reactify branch. And I would prefer styling to be added to match codemirror instead of just hiding the text area, as this does not prevent flash to the user.

**Comment by jameskopacz** [comment]
Does styling it like that really not stop the flash? Everything I'm seeing online says it should.

I'm only an amateur though. My thought process on the fix was that codemirror is hiding the textarea through javascript and that the flash is be caused by the script running late/slow/delayed/ and is hiding it after the page has already displayed. So I thought since codemirror is hiding it anyway, why not just hide it from the start to prevent the flash.

**Comment by BerkeleyTrue** [comment]
> Does styling it like that really not stop the flash?

There are really two flashes, first the text area is shown then hidden by codemirror. The second flash is happening because codemirror does not render until it is loading in the DOM, which is intentional as codemirror relies heavily on DOM manipulation. While hiding the textarea does stop it from showing to the user on initial load, codemirror still needs to load and the user will see codemirror appear from nowhere, ie flash.

After thinking about it, hiding the text area might be the best route on the reactify branch as well. If we were to add classes to mimic the styling of codemirror in the text box, the text box is not codemirror and React will still need to re-render that section of the view which will cause a flash. 

Ultimately what I would like to get done is to completely rewrite codemirror into a self contained React component so that it can pre-render on the server. But that is neither here nor there.

I am willing to close this issue when the same styling is applied to the reactify branch that is currently on master.

@jameskopacz Would you like to give it a try? You can get some exposure to React at the same time.

> I'm only an amateur though.

We are all amateurs until we are not. My philosophy is `Fake it till you make it`

**Comment by jameskopacz** [comment]
Just to make sure, this is the branch your referring to? https://github.com/FreeCodeCamp/freecodecamp/tree/reactify

I tried to edit the .jade files in server/views/bonfire/ but nothing happened. Finally found that changes were being done from common/components/bonfires/ so it looks like the easiest way would just be to apply the style in public/css/main.less under bonfire styling?

```css
.codeMirrorView textarea {
    display: none;
}

I don't want to submit anything because I'm not sure if I would be submitting changes to the correct file.

**Comment by BerkeleyTrue** [comment]
Yes I think that should work just fine. Test locally to make sure it is hidden then submit the PR.

**Comment by jameskopacz** [comment]
I messed up and commited directly to the repo. Tested code locally and it worked. Sorry about that.

**Comment by BerkeleyTrue** [comment]
Looks like the text area hide is working! Thanks.
