### ISSUE TITLE
UX - Top toggle open by default...

### ISSUE THREAD

**Issue by RenaudGagne** [freeCodeCamp/freeCodeCamp#17603]
#### Describe your problem and - if possible - how to reproduce it

Hi, I finished every single exercise in the "Responsive Web Design Certification" module yet when I visit the curriculum page, that toggle is by default open and I have to close the toggle to go to where I'm at (which is the Javascript module). 

It's not a big thing but every time it bugs me that I have to close the tab to get to where I want to go. 

How about just having all the toggles closed by default and let us decide which one we want to open? 

#### Add a Link to the page with the problem

https://learn.freecodecamp.org

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Latest
* Operating System: Windows 10

#### If possible, add a screenshot here

![screenshot-learn freecodecamp org-2018 06 16-12-50-19](https://user-images.githubusercontent.com/14856170/41500651-e26c05ce-7163-11e8-97d1-1b8fda26d3dd.png)

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue https://github.com/freeCodeCamp/learn/issues/171, so I am closing it as a duplicate.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
