### ISSUE TITLE
Typo in Responsive Web Design > Applied Visual Design > Use a Bezier Curve to Move a Graphic

### ISSUE THREAD

**Issue by ericbakuladavis** [freeCodeCamp/freeCodeCamp#17607]
#### Describe your problem and - if possible - how to reproduce it
In this sentence, the emphasized "then" should be "than".
 

> In this example, the curve moves faster through the Y-axis (starts at 0, goes to p1 y value of 0, then goes to p2 y value of 1) **_then_** it moves through the X-axis (0 to start, then 0 for p1, up to 0.58 for p2).

#### Add a Link to the page with the problem
Link to file: https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/01-responsive-web-design/applied-visual-design.json
Link to page: https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-a-bezier-curve-to-move-a-graphic

**Comment by Nirajn2311** [comment]
Yes, it is a grammatical error. Thx for pointing it out.
If any newbie is free, they can take this up. If not I’ll do it.
