### ISSUE TITLE
Beta Site: Waypoint: Comment your JavaScript Code

### ISSUE THREAD

**Issue by poolemark** [FreeCodeCamp/FreeCodeCamp#1760]
After completing the Waypoint and clicking on "Go to my next challenge" the following error displays on the page: "404: We couldn't find a challenge with the name `undefined` Please double check the name.", and does not go to the next challenge.
![waypoint - comment your javascript code](https://cloud.githubusercontent.com/assets/13278995/9278496/1f8d1374-427f-11e5-92b7-0d7c4823724d.jpg)

**Comment by poolemark** [comment]
I just tested the next 2 Waypoints and the same thing is happening on those also, so it seems to be an issue across multiple Waypoints.

**Comment by benmcmahon100** [comment]
We have just fixed this it was due to an underlying script issue
