### ISSUE TITLE
Unclear communication in challenge: Make Typography Responsive

### ISSUE THREAD

**Issue by Daniel-Michael** [freeCodeCamp/freeCodeCamp#17617]
#### Describe your problem and - if possible - how to reproduce it
This is a communications issue, not a code issue. It is regarding the "Responsive Web Design Principles: Make Typography Responsive" challenge, located in the new curriculum 'Responsive Web Design Challenges'.

The problem as I see it is to do with an explanation of how to apply the viewport dimensions using CSS.

The description is given as such:

The four different viewport units are:

vw: 10vw would be 10% of the viewport's width.
vh: 3vh would be 3% of the viewport's height.
vmin: 70vmin would be 70% of the viewport's smaller dimension (height vs. width).
vmax: 100vmax would be 100% of the viewport's bigger dimension (height vs. 

The instructions are:

Set the width of the h2 tag to 80% of the viewport's width and the width of the paragraph as 75% of the viewport's smaller dimension

This lead me to believe that those units could be set this way in CSS:

h2 {
vw: 80vw;
}
p {
vmin: 75vmin;
}

It is simply a misunderstanding on my part but I believe the way the lesson is written lead me to think that was the syntax to use. I used the Read, Search, Ask method and someone on Twitter noted that the keyword 'width; was missing.

So the output should look like this:
h2 {
width: 80vw;
}
p {
width: 75vmin;
}

There is not much to document this on W3schools either, so I am thinking an example would be helpful.

Perhaps an example under the viewport descriptions would be helpful, perhaps:

p {
width: 3vh // would be 3% of the viewport's height.
}

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/make-typography-responsive 

#### Tell us about your browser and operating system

* Browser Name:  Chrome, Firefox, Safarir
* Browser Version:  tested on all modern versions and tablet
* Operating System:  Max OSX High Sierrra

#### If possible, add a screenshot here

![screenshot_20180618-192235](https://user-images.githubusercontent.com/5474330/41528281-fe0c0e30-732c-11e8-895b-4c4686f0ae04.png)

**Comment by Nirajn2311** [comment]
@moba2k sorry to inform you, but @Vimal-Raghubir has already made a PR for this.
