### ISSUE TITLE
Wrong test for JavaScript comments challenge

### ISSUE THREAD

**Issue by mpmaan** [freeCodeCamp/freeCodeCamp#17619]
#### Describe your problem and - if possible - how to reproduce it

The test requires a multi-line comment of the form `/*   */`. However, the test fails if additional `*` characters are present at the beginning or the end of the text contained within the comment.
Some examples :
```
   // this works
   /* this works too */
   /* *this won't work */
   /* this :( fails too **/
```
The regular expression for the corresponding test needs to be updated.
#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/comment-your-javascript-code

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 60+
* Operating System: Ubuntu 18.04

#### If possible, add a screenshot here
![screenshot from 2018-06-18 18-24-42](https://user-images.githubusercontent.com/34267628/41537085-0687c1ec-7325-11e8-8109-175a1a6e1a9b.png)

**Comment by gforce2k5** [comment]
Hi, I would like to have a go to fix this problem

**Comment by mpmaan** [comment]
@gforce2k5 That's good, please read [Contributing Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by johnkennedy9147** [comment]
Test fails if multiline style comment includes either `*` or `/`

File: `curriculum/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json`
Line: 33
this regex is the problem `"assert(code.match(/(\\/\\*)([^\\*\\/]{5,})(?=\\*\\/)/gm),`
