### ISSUE TITLE
 Your style declaration should end with a ; 

### ISSUE THREAD

**Issue by Darkir** [freeCodeCamp/freeCodeCamp#17615]
#### Describe your problem and - if possible - how to reproduce it
I already put the ;  ... And  yet it doesn't let me go to the next challenge. 

#### Add a Link to the page with the problem
freecodecamp.org

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.87
* Operating System: 64 

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/40346978/41515424-de48f3ca-727c-11e8-93f9-9d385dd205ce.png)

**Comment by mpmaan** [comment]
@Darkir You have modified text contained in the ```h2``` element. Originally it was ```CatPhotoApp```. The test checks the text contained in the ```h2``` element along with its color.

**Comment by Darkir** [comment]
thanks @mpmaan

**Comment by mpmaan** [comment]
Close this issue if you have no further doubt.

**Comment by Wakesnill** [comment]
@mpmaan how do I fix this problem. Am having the same problem and have no idea how to fix it

**Comment by mpmaan** [comment]
@Darkir Check if you haven't deleted/modified unnecessarily any pre-written code. You should ask for help related to challenges on [Gitter](https://gitter.im/FreeCodeCamp/YouCanDoThis?source=orgpage) or on the [forum](https://forum.freecodecamp.org/latest) or check out the [guide](https://guide.freecodecamp.org/certifications/).

**Comment by thecodingaviator** [comment]
@Darkir Please close this issue

**Comment by thecodingaviator** [comment]
@ezioda004 Please close this issue, it's fixed for the user, they forgot to close it

**Comment by lalov1** [comment]
Technically he did close it, but he changed the text in the h2. Should you leave it open, so someone could fix the error message?

**Comment by RandellDawson** [comment]
My first thought was to just close this issue.  However, since the main purpose of the challenge is to teach the camper to change the `h2` element's text color to red and force the camper to use `;` at the end of the property/value key, then one easy solution is just ignore the text of the `h2` element by changing the last part of the regex from:
```js
>\s*CatPhotoApp\s*<\/h2>/
```
to:
```js
>[\s\S]*<\/h2>/)
```
However, since the first test already validates the text color of the h2 element is red, the 2nd test assert's regular expression could be simplified to something like the following and still achieve the main goal of validating the semi-colon was used:
```js
/<h2\s+style\s*=\s*(\'|").*?;\s*\1\s*>[\s\S]+<\/h2>/
```

**Comment by moT01** [comment]
It looks like this is fixed in beta from [this pr](https://github.com/freeCodeCamp/freeCodeCamp/pull/35535/files) - So it's safe to close this. Thanks and happy coding!

**Comment by digitalhriday** [comment]
<h2 style= "color: red;"">CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>

  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>

  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>

  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>=

**Comment by digitalhriday** [comment]
<h2 style= "color: red;"">CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>

  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>

  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>

  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>=


[1. change-the-color-of-text.txt](https://github.com/freeCodeCamp/freeCodeCamp/files/4122856/1.change-the-color-of-text.txt)
