### ISSUE TITLE
login issues

### ISSUE THREAD

**Issue by wesgray76** [freeCodeCamp/freeCodeCamp#17614]
#### Describe your problem and - if possible - how to reproduce it
every time that I try to login, I get a message that says "oops. Something has gone wrong"

#### Add a Link to the page with the problem
www.freecodecamp.org

#### Tell us about your browser and operating system

* Browser Name: Google chrome
* Browser Version: 
* Operating System: Windows 10

**Comment by mpmaan** [comment]
@wesgray76 It will be helpful if you attach a screenshot or provide some more details about how this issue can be reproduced otherwise it will be difficult to solve this issue.

**Comment by wesgray76** [comment]
![image](https://user-images.githubusercontent.com/28853982/41518530-9785ff76-7288-11e8-87ed-268378612555.png)
![image](https://user-images.githubusercontent.com/28853982/41518548-b03e1774-7288-11e8-88ed-53589b3ad5f5.png)
![image](https://user-images.githubusercontent.com/28853982/41518556-bae1b190-7288-11e8-9fe2-5d606d829d54.png)

**Comment by wesgray76** [comment]
I have been fighting this all day

**Comment by mpmaan** [comment]
Did you try the other option : "If you previously signed in ....twitter or linkedin....add email address" ?

**Comment by wesgray76** [comment]
keeps kicking me back saying something went wrong

**Comment by wesgray76** [comment]
![image](https://user-images.githubusercontent.com/28853982/41519017-19893da6-728b-11e8-8401-188b5bac1dc8.png)
this is what happened when I tried to login via twitter

**Comment by wesgray76** [comment]
![image](https://user-images.githubusercontent.com/28853982/41519060-70cd2988-728b-11e8-93e7-f3c215a4499a.png)
![image](https://user-images.githubusercontent.com/28853982/41519075-8869ad6e-728b-11e8-9480-85cd68b5f826.png)
![image](https://user-images.githubusercontent.com/28853982/41519088-99fd9658-728b-11e8-9e79-e3b2e78c76d9.png)

**Comment by mpmaan** [comment]
I really don't know what's wrong. I am able to sign in and sign out. Hopefully someone else will look into it soon.

**Comment by mpmaan** [comment]
Why did you enter another email-id ?

**Comment by wesgray76** [comment]
to double check to see if it was an email issue.

**Comment by wesgray76** [comment]
the weird thing is, I can access it on my Android phone. However, it is difficult to complete the exercises.

**Comment by mpmaan** [comment]
So that should mean that you can't create a new account or can't login to any account if you have multiple accounts.

**Comment by mpmaan** [comment]
Look into issue #17475 . Hopefully @raisedadead can fix your account.

**Comment by wesgray76** [comment]
cleared the cookies. Did not work.

**Comment by wesgray76** [comment]
is there anyway I can bring this issue to his attention without creating a new issue?

**Comment by mpmaan** [comment]
He will get a notification whenever he will open github. You can also mail him regarding your problem at mrugesh@freecodecamp.org . I thought you could find his email-id in his comment on the issue #17475 .

**Comment by wesgray76** [comment]
I did email him. Thank you for your help.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by mstellaluna** [comment]
@freeCodeCamp/moderators Can someone please assist ?

**Comment by Ethan-Arrowood** [comment]
@wesgray76 are you using an VPN? Can you try logging in from another device on the same network and see if the problem persists? When it comes to network issues it can be extremely hard to debug exactly what’s going wrong, but there are a few things you can try. 
- shut down machine and restart it
- if you’re using WiFi try using Ethernet instead (and vice versa if you’re already using Ethernet)
- restart router

Aside from this, your problem could quite possibly be a bad server. There is never 100% up time so it could’ve just been an unlucky coincidence. 

Also maybe just give it 24hours and it’ll fix itself (or someone will fix your FreeCodeCamp account).

**Comment by wesgray76** [comment]
I don't know what a VPN is. I am able to access FCC from my Android phone. However, the text is so small that I have a hard time doing the challenges.

**Comment by wesgray76** [comment]
I did run a trouble shoot on my network. A problem was found and fixed. However, I still wasn't able to login.

**Comment by raisedadead** [comment]
Hi @wesgray76 thanks for the issue report. Sorry about the delay, I just returned from a long weekend. Looking into this. I'll revert on your email.

**Comment by raisedadead** [comment]
@Ethan-Arrowood @mstellaluna @mpmaan Thanks a lot for pitching in.
