### ISSUE TITLE
Challenge to set font-size to 10px will fail the test case under Chrome Chinese edition

### ISSUE THREAD

**Issue by tntC4stl3** [freeCodeCamp/freeCodeCamp#17629]
#### Describe your problem and - if possible - how to reproduce it
Chrome Chinese edition will adjust the text font size less than 12px to 12px, so the challenge to set font-size of p tag to 10px will always fail.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/create-a-media-query/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.62
* Operating System: macOS 10.13.5

#### If possible, add a screenshot here
<img width="1440" alt="2018-06-19 12 09 04" src="https://user-images.githubusercontent.com/1506238/41576403-c25b861c-73b9-11e8-87b8-b64fb01e1473.png">

**Comment by anku255** [comment]
This is a very browser specific issue. I can think of two ways to tackle this  - 
- Update the challenge to use a font size >= 12px.
- Add a warning to the challenge text saying 'tests will not pass on Chrome Chinese Edition'.

**Comment by tntC4stl3** [comment]
Yes, I think the first solution is much better.

**Comment by roshad** [comment]
I switched to Eng.

**Comment by waylent** [comment]
put "chrome://settings/fonts" in address box, and change settings item of "最小字号"(Minimum Font Size) to 10.

**Comment by RandellDawson** [comment]
@raisedadead Any thoughts?

**Comment by raisedadead** [comment]
Yep, we could go as higher as 18px on this one. Thanks for reporting.

**Comment by RandellDawson** [comment]
@raisedadead Could this be related to issue #34775?
