### ISSUE TITLE
Sass: Create Reusable CSS with Mixins - Won't pass if there's a space after the mixin name

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#17626]
#### Describe your problem and - if possible - how to reproduce it
If the mixin is declared with a space between the mixin name and the parameter list, it won't pass, like so:

```scss
  @mixin border-radius ($radius) {
    // ...
  }
```

This is a passing declaration:
```scss
  @mixin border-radius($radius) {
    // ...
  }
```

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/sass/create-reusable-css-with-mixins/

#### Tell us about your browser and operating system
[Reported to fail on Firefox, Chrome and Safari](https://forum.freecodecamp.org/t/create-reusable-css-with-mixins-failing-tests-when-it-should-not/201397).

**Comment by mattszcz** [comment]
Confirmed. Silly bug. Easy fix.
