### ISSUE TITLE
Testing too Narrow?-- Applied Visual Design: Adjust the Height of an Element

### ISSUE THREAD

**Issue by terryjreynolds** [freeCodeCamp/freeCodeCamp#17628]
Applied Visual Design: Adjust the Height of an Element Using the height Property

Problem: It is possible to pass this challenge by including a CSS height specification without a semi-colon. A missing semi-colon in a CSS class would impair any program. This sends a wrong message to the learner that it's okay to exclude the semi-colon.
e.g.
h4 {
    text-align: center;
    height: 25                      /*passes without a semi-colon*/
}

Curiously, though, when I changed the position of my height specification within the h4 class, it appropriately wouldn't pass without the semi-colon.
e.g.

h4 {
    height: 25;                    /*in this position, passes only with semi-colon*/
    text-align: center;
}

I've only been coding for just over a year, so I don't know how to fix this. I've examined the source code and I believe it appears that the node assert() test is passed a jquery selector for h4 that is set equal to '25px'

As seen here:

 "tests": [
        {
          "text": "Your code should change the <code>h4</code> <code>height</code> property to a value of 25 pixels.",
          "testString": "assert($('h4').css('height') == '25px', 'Your code should change the <code>h4</code> <code>height</code> property to a value of 25 pixels.');"
        }

I noticed also that in the prior challenge (Applied Visual Design: Adjust the Width of an Element Using the width Property), the test is regex-based. Could a possible fix be to create a suitable regex test instead of the assertion test? Or, maybe you could create a white space in which the student is directed to write the height spec. using those comments you typically use that say something like "place your code between these lines"?

Or, it's possible that this is a browser-specific issue. Or, perhaps it's not an issue at all. :)

Here's a link to the page--  https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-height-of-an-element-using-the-height-property

My operating system:

* Chrome: 
* Version 67.0.3396.87 (Official Build) (64-bit)
* Windows 10 

Screenshots
![image](https://user-images.githubusercontent.com/26657379/41571332-b2228558-7340-11e8-8f1b-2a31e9bce2be.png)

![image](https://user-images.githubusercontent.com/26657379/41571343-c0b7f9cc-7340-11e8-8727-3a662104cedc.png)

**Comment by mpmaan** [comment]
@terryjreynolds Generally , the `;`is necessary after every css property except for the last one. This should not cause any problem unless the RegExp test specifically asks for it.
For example 
```
   h4{
     height: 25px; //semi-colon required
     text-align: center; //semi-colon required
     color: blue //semi-colon is not required as it is the last property for this group / block (I don't know what to call it)
   }
```
Though it would be helpful to include additional details or clarification about this in the challenge.

**Comment by terryjreynolds** [comment]
@mpmaan you are right about the semi-colon. I put the h4 class selector through W3C validation without the semi-colon and it passed. However, I think the more important issue that I don't think I really made clear in my original post was that I can pass the test without including a semicolon or a unit (px).

The code below will pass the FCC challenge, and shouldn't as it lacks the pixel (px) unit and it will not pass W3C validation:

`h4 {
       text-align: center;
       height: 25	 						
       }`

Sorry I neglected to outline this in my original post ('twas late in the evening).
