### ISSUE TITLE
"Waypoint: Change the Font Size of an Element" Still has a problem (in live and beta)

### ISSUE THREAD

**Issue by Philomorph** [FreeCodeCamp/FreeCodeCamp#1762]
As described in issue #492, [this Waypoint](http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element) is still accepting incorrect code as correct, as does the [beta site](http://beta.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element).

The last requirement is "give your p elements the font size of 16px" but you only have to give the first one the correct size for it to be accepted. You don't need any sort of style at all on your second p:

![image](https://cloud.githubusercontent.com/assets/13068591/9284885/edc3bd96-4294-11e5-8fd4-99651fc38845.png)

**Comment by Philomorph** [comment]
It seems this issue may stretch through multiple waypoints, as the "Waypoint: Import a Google Font" also ignores whether the second p element meets the listed requirements:

![image](https://cloud.githubusercontent.com/assets/13068591/9284999/33cabc6c-4296-11e5-815a-79544d4b3599.png)

**Comment by benschenker** [comment]
Thanks @Philomorph,

I've confirmed this issue
