### ISSUE TITLE
the test does not work in this challenge 

### ISSUE THREAD

**Issue by zoaby** [freeCodeCamp/freeCodeCamp#17638]
the test have a bug and doesn’t pass

<style>
  img { height: 100px;  width: 100px; }
</style>

<img src="https://s3.amazonaws.com/freecodecamp/FCCStickers-CamperBot200x200.jpg" alt="freeCodeCamp sticker that says 'Because CamperBot Cares'">
Your browser information:

User Agent is: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36.

Link to the challenge:
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/use-a-retina-image-for-higher-resolution-displays

**Comment by mpmaan** [comment]
@zoaby I just copied your code and it passed in Google Chrome 67+ on Ubuntu. Can you provide some more detail or a screenshot (will be better).

**Comment by anku255** [comment]
@zoaby @mpmaan  Can confirm that the tests are passing in my Google Chrome v67 on Windows.

**Comment by zoaby** [comment]
the problem was in the code because the test doesn't accept spaces
