### ISSUE TITLE
regex challenge regression from  #16119

### ISSUE THREAD

**Issue by lynxlynxlynx** [freeCodeCamp/freeCodeCamp#17632]
#### Describe your problem and - if possible - how to reproduce it
The fix for #16119 obfuscated the success conditions:
https://github.com/freeCodeCamp/freeCodeCamp/commit/72fe47c609eb61da17e0af80f3b6a09c87e7861d#diff-9c53bb0f0b326a3ab63a565f77ff30e9

Since the challenge now asks to find a single character (upper or lower "a"), using the * for the most obvious solution ([aA]*) fails the tests, since it also matches nothing. Even a + is bad, since the new tests expect not to match non-repeating "a"s.

You have to use something convoluted as /[aA][aA][aA]*/, which new learners won't come up with nor is it really what the challenge instructions want you to do.

I suggest we remove the last test (extraneus) and change the one before it to hold a string with no "a"s.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/match-characters-that-occur-zero-or-more-times

https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/regular-expressions.json#L650

**Comment by mpmaan** [comment]
@lynxlynxlynx  It is unclear what the solution should do. Don't these lines contradict each other?

>Your regex chewieRegex should use the * character to match **zero or more** a characters.

>Your regex should **not match any** characters in "He made a fair move. Screaming about it can't help you."

If we have to write regex to specifically match `a` characters in `Aaaaaaaaaaaaaaaargh` then `/Aa*/` will work.

**Comment by lynxlynxlynx** [comment]
Yes, but that's just a regression. Previously the base string was longer (Star Wars) and didn't require checking for a specific char, so the solution was of the form /fixed string.*/.

**Comment by scissorsneedfoodtoo** [comment]
Fixed in https://github.com/freeCodeCamp/freeCodeCamp/pull/34800
