### ISSUE TITLE
(JS) For loop, not recognized in the tests

### ISSUE THREAD

**Issue by gburu98** [freeCodeCamp/freeCodeCamp#17634]
Hello freeCodeCamp team,

I am stuck in a problem in "basic Javascript", it seems that the tests expect a for loop, but do not accept the one I propose. I tried to delete the cache but it still does not work. In localhost the loop works without problems

**Link**: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-for-loops/

* Browser Name: **Google Chrome**
* Browser Version: **67.0.3396.87 (Build oficial) (64 bits)**
* Operating System: **Windows 10**

![fcc-1](https://user-images.githubusercontent.com/39672367/41597386-b6b2d3e4-73a3-11e8-9517-8a8ef23416ff.png)
![fcc-2](https://user-images.githubusercontent.com/39672367/41597392-b7f68354-73a3-11e8-9055-913249f8c6db.png)

**Comment by mpmaan** [comment]
@gburu98 Most probably it's failing because you deleted the example of the pre-written code. Reset the code and try again. I don't know why that pre-written code is required to pass this test.

**Comment by gburu98** [comment]
@mpmaan Thank you very much. You were very helpful!!!

**Comment by mpmaan** [comment]
@gburu98 Please close this issue is you have no further doubt.
