### ISSUE TITLE
regex search and replace challenge is trivial

### ISSUE THREAD

**Issue by lynxlynxlynx** [freeCodeCamp/freeCodeCamp#17645]
#### Describe your problem and - if possible - how to reproduce it
Instead of testing anything useful that is mentioned in the description, it requires a plaintext replacement, not even needing a capture group.

I suggest it is changed to a reordering exercise, since it is already mentioned in the example.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/use-capture-groups-to-search-and-replace/

**Comment by thecodingaviator** [comment]
Reordering exercise as in?

**Comment by lynxlynxlynx** [comment]
it's the second code example.

**Comment by thecodingaviator** [comment]
That is this one?:
`
"Code Camp".replace(/(\w+)\s(\w+)/, '$2 $1');
// Returns "Camp Code"
`

**Comment by raisedadead** [comment]
Curriculum issues are independent of releases.
