### ISSUE TITLE
React to render nested components page crashes after 35 seconds

### ISSUE THREAD

**Issue by urbanware** [freeCodeCamp/freeCodeCamp#17648]
#### Describe your problem and - if possible - how to reproduce it

In the Chrome browser the challenge was complete and I had gone back to review.
The page is continuously loading, and after about 35 seconds I receive a popup that the page is not responding to exit or wait.  Clicking Exit crashes the page immediately.  Clicking Wait crashes the page in a few more seconds.  

Challenge shows the code incorrectly and cannot be reset, no button response, no editor response.  TypeOfFood class should have Fruits component but says TypeOfFood instead.

Redid challenge in Firefox 60.0.2 and challenge worked.  Code is absent when looking back however.  

In Chrome previous code still locked in and cannot be reset.  

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/front-end-libraries/react/use-react-to-render-nested-components/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.87 (Official Build) (64-bit)
* Operating System: macOS High Sierra

#### If possible, add a screenshot here

![screen shot 2018-06-19 at 20 12 47](https://user-images.githubusercontent.com/16967/41630487-2d832b6e-73fd-11e8-9ccc-080115168762.png)

**Comment by anku255** [comment]
The challenge is working fine in Chrome Version  67.0.3396.87, Windows 10.

![image](https://user-images.githubusercontent.com/22813027/41649962-833b6d94-749a-11e8-9ea2-4ca0c7460c40.png)

And FreeCodeCamp doesn't save your code for challenges. It only saves the code for projects.

Can you please check again and tell us if you are still facing this issue?

**Comment by RyanHaire** [comment]
Same problem. 
Chrome Version 68.0.3440.106 (Official Build) (64-bit)
macOS Sierra 10.12.6

**Comment by huyenltnguyen** [comment]
@RyanHaire Could you check if there is any error in the browser console?

**Comment by carbonkitten** [comment]
Similar if not the same problem, input the correct code and click run tests, and the page just breaks. It is crashing because Chrome pauses execution of the main thread to stop itself from running out of memory.
![screenshot from 2018-10-04 21-06-41](https://user-images.githubusercontent.com/19364048/46511361-43fb9200-c81c-11e8-94e3-b8967d7edc37.png)

**Comment by thecodingaviator** [comment]
Works fine for me as of now. @urbanware if it's fixed for you, please close the issue

**Comment by RandellDawson** [comment]
@urbanware, @baliomega, @RyanHaire, @carbonkitten  Can we get you to test [this challenge on our beta site](https://www.freecodecamp.rocks/learn/front-end-libraries/react/use-react-to-render-nested-components) which incorporates many fixes to the React challenges?

Thank you.
