### ISSUE TITLE
regex: grouping missing from the curriculum

### ISSUE THREAD

**Issue by lynxlynxlynx** [freeCodeCamp/freeCodeCamp#17646]
We teach something obscure as lookahead, but not the more often used grouping for the sake of subexpression choice, eg. `a(bc|def)g`.

Grouping is indirectly taught for capture groups and lookahead, but plays the same general role in both, capturing or not. So this lesson would fit nicely before that, after character groups.

**Comment by TomerPacific** [comment]
@lynxlynxlynx ,
there is a [lesson ](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/match-a-literal-string-with-different-possibilities/ ) at the beginning teaching OR. Maybe we should consider revising the challenge's description to include a reference for it?

**Comment by lynxlynxlynx** [comment]
It's better to have it separate, so the lessons are sharper, but I'll update the title.

**Comment by TomerPacific** [comment]
@lynxlynxlynx ,
so what would you like to be done? I'm up for revising it.

**Comment by lynxlynxlynx** [comment]
Oh, if I wasn't clear: I believe an extra lesson is in order, right after the OR one. Maybe something like "find all the words that have 'foo' or 'bar' in them", just long enough to avoid character-list hacks.

**Comment by thecodingaviator** [comment]
@lynxlynxlynx If you haven't taken this, maybe I can create a new lesson?

**Comment by lynxlynxlynx** [comment]
Knock yourself out. :)
