### ISSUE TITLE
Error in "Create Strings using Template Literals" challenge example

### ISSUE THREAD

**Issue by udidol** [freeCodeCamp/freeCodeCamp#17641]
#### Describe your problem and - if possible - how to reproduce it
In the ES6 lesson/challenge: Create Strings using Template Literals
It looks like the variable representation in the template literals example is not right.
See attached screenshot.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/create-strings-using-template-literals

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.87
* Operating System: Windows 10

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/36724484/41615278-7afb08a2-7403-11e8-9a0a-25bf5382aacc.png)

**Comment by anku255** [comment]
Same MathJax problem as [#17620](https://github.com/freeCodeCamp/freeCodeCamp/issues/17620#issuecomment-398306890) .

I can try to fix these issues once I get a confirmation on which files to change.
