### ISSUE TITLE
Confusing example code in Sass challenges

### ISSUE THREAD

**Issue by GiaFil7** [freeCodeCamp/freeCodeCamp#17647]
- In the Sass challenges, when the $variable syntax is present the "$" is missing and the text changes font family. This can potentially be confusing for learners, since it may not be clear enough to them when they have to use the above syntax. (e.g in [Sass: Store Data with Sass Variables](https://learn.freecodecamp.org/front-end-libraries/sass/store-data-with-sass-variables) ,[Sass: Use @if and @else to Add Logic To Your Styles](https://learn.freecodecamp.org/front-end-libraries/sass/use-if-and-else-to-add-logic-to-your-styles/) and [Sass: Apply a Style Until a Condition is Met with @while](https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while/))
- In the example code of [Sass: Apply a Style Until a Condition is Met with @while](https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while/) there is a seemingly out of place box.
- In the example code of [Sass: Use @if and @else to Add Logic To Your Styles](https://learn.freecodecamp.org/front-end-libraries/sass/use-if-and-else-to-add-logic-to-your-styles/) the second line seems a bit confusing.
- The first 2 lines of the second block of example code in [Sass: Use @each to Map Over Items in a List
](https://learn.freecodecamp.org/front-end-libraries/sass/use-each-to-map-over-items-in-a-list) seem confusing.

The above mentioned example code blocks are a bit confusing, especially for beginners. So, I would suggest they are replaced with code that is more understandable for learners.

**Comment by Nirajn2311** [comment]
Will be working on all typos over the weekend.
