### ISSUE TITLE
make clear that plain css includes flexbox and css grid

### ISSUE THREAD

**Issue by jooji-san** [freeCodeCamp/freeCodeCamp#17640]
#### Describe your problem and - if possible - how to reproduce it
'Plain CSS is recommended because that is what the lessons have covered so far and you should get some practice with plain CSS.'
Some people don't know that flexbox and css grid are included in the plain css.

#### Add a Link to the page with the problem
e.g. https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-tribute-page

**Comment by thecodingaviator** [comment]
This is in my opinion a confusion with the user and not with our content.

**Comment by thecodingaviator** [comment]
@QuincyLarson Since the user has not yet got back to us, I think we should close this?
