### ISSUE TITLE
Guide content needs help

### ISSUE THREAD

**Issue by ScottPesetsky** [FreeCodeCamp/FreeCodeCamp#1764]
http://www.freecodecamp.com/field-guide/what-is-pair-programming-and-why-is-it-special

Second paragraph seems off. Suggest rewrite.

**Comment by BerkeleyTrue** [comment]
Hey @ScottPesetsky 

Long time no see! Hope all is well.

We have since moved our field guides to github wiki

You can edit them as well. Check out this one here https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/What-pair-programming-is-and-why-it-is-special

Is this version still off?

**Comment by ScottPesetsky** [comment]
Hey @BerkeleyTrue ,

That version is good! When will the website point here?

Good to see you're on-board here. Hope to hang out soon.
-Scott

**Comment by BerkeleyTrue** [comment]
Hopefully Tonight!
