### ISSUE TITLE
Confusing Test Assertion in ES6 Challenges

### ISSUE THREAD

**Issue by luandy64** [freeCodeCamp/freeCodeCamp#17642]
#### Describe your problem and - if possible - how to reproduce it
Problem 1: In "ES6: Declare a Read-Only Variable with the const Keyword", the first test checks for `var` in the code. If it finds it, it outputs `var does not exist in code`.

I believe this is confusing and it should be changed to match the second test and say ` var should not exist in code`.

Note: The challenge prior to this does the same thing.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/declare-a-read-only-variable-with-the-const-keyword

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.87 (Official Build) (64-bit)
* Operating System: macOS High Sierra 10.13.5

**Comment by anku255** [comment]
I agree with @luandy64. 

`var should not exist in code` gives a better understanding of the test. Also, it falls in line with the rest of two test statements.
