### ISSUE TITLE
Streak calendar not working

### ISSUE THREAD

**Issue by RenaudGagne** [freeCodeCamp/freeCodeCamp#17650]
#### Describe your problem and - if possible - how to reproduce it

I've been dedicating about 2h a day to FCC and I've been surprised that the calendar that shows how active I've been is plain white...even though the alt tag says that 

- less than 1 item = white
- more than 3 items = green

That feature seems to be broken. I've tested to see if it was because of dark mode, but it's not working either way.

#### Add a Link to the page with the problem

https://freecodecamp.org/cryptoctopus

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System: 

#### If possible, add a screenshot here

![screenshot-www freecodecamp org-2018 06 19-23-10-15](https://user-images.githubusercontent.com/14856170/41635311-1cd1041c-7416-11e8-82b6-8e29ed4c7b49.png)

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #17622, so I am closing it as a duplicate.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
