### ISSUE TITLE
Optional Advanced Data Structures lessons?

### ISSUE THREAD

**Issue by RenaudGagne** [freeCodeCamp/freeCodeCamp#17659]
#### Describe your problem and - if possible - how to reproduce it

In "[Basic Data Structures: Modify an Array Stored in an Object](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/modify-an-array-stored-in-an-object)" it mentions: 

> Additionally, the optional **Advanced Data Structures lessons later in the curriculum** also cover the ES6 Map and Set objects, both of which are similar to ordinary objects but provide some additional features.

I do not see those lessons anywhere. Is there an hidden module somewhere I don't know of?

Or is that text that is a legacy of the previous curriculum?

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by t3h2mas** [comment]
Check under **Coding Interview Prep (Thousands of hours of challenges)**

**Comment by thecodingaviator** [comment]
@moT01 I think that now with the new curriculum, this is fixed?

**Comment by RandellDawson** [comment]
The "advanced" section would be those challenge located in the Data Structure Questions in the Coding Interview Prep section.  @raisedadead I am thinking the easiest solution this is to rewrite the following sentence from:
> Additionally, the optional Advanced Data Structures lessons later in the curriculum also cover the ES6 Map and Set objects, both of which are similar to ordinary objects but provide some additional features. 

to something like:

> Additionally, the Data Structures lessons located in the `Coding Interview Prep` section of the curriculum also cover the ES6 Map and Set objects, both of which are similar to ordinary objects but provide some additional features.

**Comment by raisedadead** [comment]
Yes. That should be fine.

**Comment by ruchika90** [comment]
I'll take this up.

**Comment by RandellDawson** [comment]
@ruchika90 Go for it.  No one else has asked for it.

**Comment by maxiqboy** [comment]
I had the same question, so I came here,

So the answer is Advanced Data Structures located in  Coding Interview Prep (Thousands of hours of challenges) > Data Structures , am I right ?

Why doesn't any admin/mod rewrite as RandellDawson said so no one has this question and come here again ?

Thanks

**Comment by RandellDawson** [comment]
> Why doesn't any admin/mod rewrite as RandellDawson said so no one has this question and come here again ?

What exactly are you trying to do?

**Comment by maxiqboy** [comment]
> > Why doesn't any admin/mod rewrite as RandellDawson said so no one has this question and come here again ?
> 
> What exactly are you trying to do?

Same as OP, I cannot see the Advanced Data Structures lesson on FCC

**Comment by RandellDawson** [comment]
They are not called Advanced Data Structures lessons.  They are just called Data Structures and they are in the Coding Interview Prep section of the curriculum

![image](https://user-images.githubusercontent.com/5313213/61579834-3d928a00-aabf-11e9-9993-552078d7bc73.png)

**Comment by maxiqboy** [comment]
> They are not called Advanced Data Structures lessons. They are just called Data Structures and they are in the Coding Interview Prep section of the curriculum
> 
> ![image](https://user-images.githubusercontent.com/5313213/61579834-3d928a00-aabf-11e9-9993-552078d7bc73.png)

oh man, You didn't get me,

I said above : 

> So the answer is Advanced Data Structures located in Coding Interview Prep (Thousands of hours of challenges) > Data Structures , am I right ?
Why doesn't any admin/mod rewrite as RandellDawson said so no one has this question and come here again ?
Thanks

I read completely this issues and got the answer, just ask why admin/mod doesn't change as you said, so no one will get confused like me or OP again,

**Comment by RandellDawson** [comment]
@maxiqboy We decided to just modify the text of the `Basic Data Structures: Modify an Array Stored in an Object` challenge to the following:
>Additionally, the Data Structures lessons located in the Coding Interview Prep section of the curriculum also cover the ES6 Map and Set objects, both of which are similar to ordinary objects but provide some additional features.

This was done to minimize the need to update several other sections.  We feel it does not make any difference if it is renamed `Advanced Data Structures` or just remain `Data Structures under the Coding Interview Prep` section.  We hope to have the changes made deployed to the production site very soon.
