### ISSUE TITLE
Missing  Letter 's' !!

### ISSUE THREAD

**Issue by MoatazAbdAlmageed** [freeCodeCamp/freeCodeCamp#17657]
Hello Thanks for the awesome website FREECODECAMP
I noticed that there are missing 's' letter in this lesson 
https://learn.freecodecamp.org/front-end-libraries/react/pass-props-to-a-stateless-functional-component
 in the challenge description 
"There is a Calendar and CurrentDate component(s) in the code editor."

I'm not native speaker but I think it is missing.
Thanks from EGYPT !

**Comment by thecodingaviator** [comment]
@MoatazAbdAlmageed since this has been fixed, please close the issue

**Comment by MoatazAbdAlmageed** [comment]
Fixed #17657

**Comment by MoatazAbdAlmageed** [comment]
Fixed #17657
