### ISSUE TITLE
Typo in Basic JavaScript: Practice comparing different values

### ISSUE THREAD

**Issue by FinnPegler** [freeCodeCamp/freeCodeCamp#17654]
Apologies if this is not the correct way to report this.

The word equality is spelt as equalty in the problem page for **Basic JavaScript: Practice comparing different values**.

![image](https://user-images.githubusercontent.com/22868206/41651034-67960bda-7477-11e8-8ffd-83fb411fa1f3.png)

**Comment by Nirajn2311** [comment]
On it.

**Comment by Nirajn2311** [comment]
Can someone close this issue as it is solved.

**Comment by thecodingaviator** [comment]
> Can someone close this issue as it is solved.

@Nirajn2311 / @ezioda004
