### ISSUE TITLE
Campers Code of Conduct

### ISSUE THREAD

**Issue by NathanSQWing** [FreeCodeCamp/FreeCodeCamp#1765]
There is a small grammatical oversight on the Campers Code of Conduct page (http://www.freecodecamp.com/field-guide/what-is-the-free-code-camp-code-of-conduct?)

It says: "Free Code Camp is friendly place to learn to code."
when it should say: "Free Code Camp is a friendly place to learn to code."

Just thought I would mention it. So far I am really excited to be a part of this 'programmers bootcamp'. Here's to a long and industrious relationship.

**Comment by BerkeleyTrue** [comment]
Helllo @NathanSQWing 

We have since move our field guides to our wiki! Check them out here https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Code-of-Conduct

This change should be reflect on our site shortly.

Happy Coding!

**Comment by NathanSQWing** [comment]
Okie dokie. Thanks.

On Sat, Aug 15, 2015 at 4:57 PM, Berkeley Martinez <notifications@github.com
