### ISSUE TITLE
Dead link to reference problem (Basic JavaScript: Record Collection --> manipulating-complex-objects )

### ISSUE THREAD

**Issue by cafeTechne** [freeCodeCamp/freeCodeCamp#17652]
#### Describe your problem and - if possible - how to reproduce it
Dead link on this page ( https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/record-collection ) when trying to 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/manipulating-complex-objects

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 
* Operating System: Ubuntu 16.04LTS

**Comment by Nirajn2311** [comment]
@anku255 which version of @freecodecamp/curriculum module is your local using?

**Comment by anku255** [comment]
@Nirajn2311 I am using `"@freecodecamp/curriculum": "^1.0.4"`.

**Comment by Nirajn2311** [comment]
I want to know which one is installed. Check it in the node_modules folder.

**Comment by anku255** [comment]
@Nirajn2311 Ah, sorry! I forgot that the version listed in package.json can be different from the installed one.

I checked the node_modules folder and it is `1.2.0` which is the latest one. I tested it again, the **links are perfectly fine**.

**Comment by Nirajn2311** [comment]
So if there is a problem in the version of node_module then it is being fixed in my PR [learn/#188](https://github.com/freeCodeCamp/learn/pull/188).

**Comment by Nirajn2311** [comment]
@cafeTechne this issue has been fixed.
