### ISSUE TITLE
There is no settings to change login email address

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/freeCodeCamp#17660]
#### Describe your problem and - if possible - how to reproduce it
I created my account using GitHub, but the social authentication is deprecated now. When I sign in, it says "Next time we recommend using your email address: ********** to sign in instead." but the email address FCC has imported from my GitHub account is the old one. I want to change it to my current email.

#### Add a Link to the page with the problem
https://www.freecodecamp.org/settings
There is no setting to change the email address.
I have already changed the email address on GitHub, but FCC account does not follow that change.

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 67.0.3396.87 (Official Build) (64 bit)
* Operating System: Windows 10

#### If possible, add a screenshot here
![email_fcc](https://user-images.githubusercontent.com/25644062/41662193-8653673e-74db-11e8-91e1-7a045c117751.PNG)

**Comment by auntieBee** [comment]
Thanks for this, sidemt. I have to use an old email address that I want to delete permanently, so it would be great if I could switch to my github login email.

**Comment by moT01** [comment]
@sidemt it looks like there is a setting to change your email now, have you been able to change it? If so, could you close this issue please.

**Comment by sidemt** [comment]
Thank you @moT01 I can change my email now. Closing the issue.
