### ISSUE TITLE
Minor spelling error on personal portfolio example

### ISSUE THREAD

**Issue by Roninii** [freeCodeCamp/freeCodeCamp#17662]
Just a minor spelling error on the example for the personal portfolio example.
the "about" section says, "Hey i'am mimic"
Unless I'm just being silly and this was intentional, I believe it should say "I'm" (capital "i", remove the "a")

https://codepen.io/freeCodeCamp/full/zNBOYG

**Comment by thecodingaviator** [comment]
I'm working on this, you can close the issue in the meantime @Roninii
