### ISSUE TITLE
ES6: Use export to Reuse a Code Block - Naming Issue

### ISSUE THREAD

**Issue by yoscheherazade** [freeCodeCamp/freeCodeCamp#17666]
#### Describe your problem and - if possible - how to reproduce it
In the ES6: Use export to Reuse A Code Block challenge, the variables that should be exported are named foo and boo. The test suite shows that it is checking that "foo is exported" and "bar is exported". The test still passes if you add export in front of both variable declarations but I thought I'd mention it.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-export-to-reuse-a-code-block/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.87 
* Operating System: Windows 10

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/14932943/41687064-4b0c2d68-749b-11e8-928f-ab522c4d670d.png)

**Comment by udidol** [comment]
That's how it is supposed to pass. I don't see a problem.
Consider closing this issue

**Comment by scissorsneedfoodtoo** [comment]
@yoscheherazade, thank you very much for reporting this.

This challenge was recently updated and changed the variable names a bit. Did you happen to finish this challenge in the past? If so, you might be seeing your previous working solution there. Could you try pressing the "Reset All Code" button? You might see the updated variable names, then.

**Comment by yoscheherazade** [comment]
@scissorsneedfoodtoo I hadn't completed this problem yet, I just saw it this time and thought to mention it but I will go back now and use the "Reset All Code" button and see if the variable names are updated.

@udidol the problem is that the variable name in the exercise and the variable name in the testing suite are inconsistent, as the screenshot points out. There is no variable named bar. I'll close the issue though. Thanks.

**Comment by scissorsneedfoodtoo** [comment]
@yoscheherazade, I'm not seeing the problem on my end, but please feel free to reopen the issue if it persists! We definitely don't want the challenge to be showing the wrong variable names.
