### ISSUE TITLE
Run Tests doesn't work

### ISSUE THREAD

**Issue by samdoj** [freeCodeCamp/freeCodeCamp#17668]
#### Describe your problem and - if possible - how to reproduce it
I get the error message : TypeError: unknown: Cannot read property '0' of undefined
    at Function.e.get (babel.js:3632)
    at e.h [as unshiftContainer] (babel.js:42437)
    at t.<anonymous> (index.js:45)
    at r (babel.js:43256)
    at e.o [as _call] (babel.js:39993)
    at e.i [as call] (babel.js:39965)
    at e.a [as visit] (babel.js:40022)
    at e.visitQueue (babel.js:39553)
    at e.visitMultiple (babel.js:39506)
    at e.visit (babel.js:39593)
(anonymous) @ transformers.js:85
Run this code using the Run Tests button:

`function isPrime(n)
{
  let arr = [];
  for (let i = 2; i < n; i++)
    if (n % i === 0) return false;
    return true; 
}

function getPrimes(n)
{
  let arr = [];
  for (let i = 2; i <=n; i++)
    if (isPrime(i)) arr.push(i)
    return arr;
}

function primeFactorize(n)
{
  let factors = []
  let k = n;

  if (isPrime(n)) return [{base: n, pow:1}];
  for (let i = 0; i < PRIMES.length; i++)
  if( n % PRIMES[i] === 0 ) {
    console.log("new Prime found " + PRIMES[i]);
  factors.push({base:PRIMES[i], pow:1})}
  for (let i = factors.length; i--; i>-1)
  {
  let count  = 0;
  let j = factors[i].base;
  
  while (k % j === 0)
    {
      count++;
      k /= j;
    }
    k *= j;
  factors[i].pow = count;  
    }
 
    return factors;
}

function smallestCommons(arr) {
  const {min, max} = Math;
  const j = min(...arr);
  const k = max(...arr);
  let range = [];
  let lastI;
  let allFactors = []
  for (let i = j; i<=k; i++)
    {
      allFactors.push(primeFactorize(i))
      range.push(i);
    }
    console.log(allFactors)
  
}

const PRIMES = getPrimes(23);
smallestCommons([1,5]);`

The code works properly on the web console, so it has something to do with your backend?  Name collision?  

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/smallest-common-multiple/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.87 (Official Build) (64-bit)
* Operating System: Mac OsX 14

**Comment by luane91** [comment]
Any update on this issue?

**Comment by raisedadead** [comment]
Hey we have recently fixed this, however it will be a few more weeks before we can ship this to production site. 

We have confirmed this issue is no longer present on an upcoming test version of the platform [here](https://www.freecodecamp.rocks).

Thanks for your patience.
