### ISSUE TITLE
ES6: Use * to import Everything from a File

### ISSUE THREAD

**Issue by pahosler** [freeCodeCamp/freeCodeCamp#17665]
#### Describe your problem and - if possible - how to reproduce it
there is still a problem with this exercise.
the challenge states:

> The code below requires the contents of a file, "capitalize_strings", found in the same directory as it, imported. Add the appropriate import * statement to the top of the file, using the object provided.

which is fine, but it doesn't give complete information to complete the challenge, I had to look in 
>ES6: Use * to Import Everything from a File - import name ambiguity #16356 
to see what is ACTUALLY expected.

the code section has one line only:
`"use strict";`

there is absolutely nothing in the body of the explanation or the challenge description telling us what is actually required in the code!

if you do what it asks by adding:

`import * as myModule from "capitalize_strings";`

it gives an error<?> when you run the code that is less than helpful:

`uses import * as properly`

nowhere in the description does it say to use the module or what is in the module

for example:
```js
"use strict";
import * as myModule from "capitalize_strings";
myModule.capitalize("foo");
myModule.lowercase("Bar");
```
interestingly however, now that I've had a successful test it passes with only the import line added to the code. I tried to repeat the error in firefox, originally the test was done in chrome, but again it passes the test with only the `import * as myModule from "capitalize_strings";` line

This test would not pass previously until the code above created a successful result.

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use--to-import-everything-from-a-file

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.87 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by pahosler** [comment]
This may have been just a glitch. I followed along as someone else did this challenge today and the issue was not reproducible.

**Comment by aps120797** [comment]
Okay, for those facing problems with https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use--to-import-everything-from-a-file/
Remember two important things:
The syntax is:
```js
import * as object_with_name_of_your_choice from "file_path_goes_here";
```
In the above, the Double Quotes (`" "`) and the Line ending semi-colon (`;`) is *very important*.

**Comment by aps120797** [comment]
Oh, and I feel there's another bug. 🐛 
And this bug is not only with this problem, but with a few other previous problems.

To access file from the same location, we can use `"file_path_goes_here"` or `"./file_path_goes_here"`. The second case doesn't work in the problem and some previous problems. I personally prefer the second while actually producing an app.

Please let me know where can I make changes and open a PR for the same. 😄

**Comment by Freshi** [comment]
The code below requires the contents of a file, "capitalize_strings", found in the same directory as it, imported. Add the appropriate` import * `statement to the top of the file, _using the _object provided__.

The last statement saying _using the object provided_ is a bit confusing as none is.

**Comment by ZokiMar** [comment]
any idea why the following code below is not accepted?


task; 
The code below requires the contents of a file, "capitalize_strings", found in the same directory as it, imported. Add the appropriate import * statement to the top of the file, using the object provided.

my solution; (not accepted)

import { capitalizeString } from "capitalize_strings";
capitalizeString("hello!");

suggestions and help greatly appreciated! thx.

**Comment by nathanhannig** [comment]
@ZokiMar 
The file where this function lives is called "string_functions" not "capitalize_strings"

**Comment by nathanhannig** [comment]
@ZokiMar I think you are confusing two different challenges.

for https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use--to-import-everything-from-a-file
```
import * as myModule from "capitalize_strings";
myModule.capitalize("hello!");
```
and for https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/understand-the-differences-between-import-and-require
```
import { capitalizeString } from 'string_functions'
capitalizeString("hello!");
```

**Comment by PizzaPokerGuy** [comment]
Wanted to elaborate that the challenge does not pass when single quotes are used around the file name.

**Comment by JuanjoA** [comment]
+1 @nathanhannig : Allow single quotes around filename

**Comment by imi-tating** [comment]
This one was so frustrating... and I also agree that they need to either remove the statement "...using the object provided." or update the code to reflect that statement. 

The following did NOT pass: 
import * as capStrings from "capitalize_strings"
"use strict";

However, this did pass: 
import * as capStrings from "capitalize_strings";
"use strict";

**Comment by LaurelineP** [comment]
Hi there, I've been currently doing this exercise but I did encounter the single; double quotes issues which looks to be mentioned here and I don't know if it should still supposed to be the case today ?

**Comment by moT01** [comment]
fixed via https://github.com/freeCodeCamp/freeCodeCamp/pull/36144

**Comment by AnnStonely** [comment]
THE SOLUTION IS>> ./ 
Y'all are forgetting the file path!!!
