### ISSUE TITLE
Certification views have an unnecessary "projects" word in them

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17667]
Please see image below. This seems to affect all six of the new certifications.

![dgkd_vfvaaassmd](https://user-images.githubusercontent.com/985197/41687749-a7c755ce-74ae-11e8-9bfa-15d8cdb2f9c1.jpg)

**Comment by Nirajn2311** [comment]
You may go ahead with the editing.

**Comment by QuincyLarson** [comment]
@Dar0n Sure - please dig in and see if you can fix this :) Please keep us posted.

**Comment by Dar0n** [comment]
I've made the pull request. Please let me know if it worked or not - could not test the result locally.
