### ISSUE TITLE
Stuck in  basic js finding a remainder

### ISSUE THREAD

**Issue by BenEar50** [freeCodeCamp/freeCodeCamp#17677]
#### Describe your problem and - if possible - how to reproduce it
I'm going through basic js and when trying to run the tests in the finding a remainder section nothing happens. I have cleared my cookies, logged off, and various other things. The only thing I have not done is restart my progress but will that even solve the issue at this point?

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/finding-a-remainder-in-javascript/

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: Version 67.0.3396.87 (Official Build) (64-bit)
* Operating System: Windows pro 10 64 bit v1803, and MacOS High Sierra V10.13.5

**Comment by huyenltnguyen** [comment]
@BenEar50 Could you try it again and check if there is any error in the browser console? Screenshot of the error would be helpful.

**Comment by anku255** [comment]
Hi @BenEar50! The challenge is working well on my Chrome Version  67.0.3396.87 on Windows 10.

Can you please check again if you are still facing the issue? If you are, then take a look at the browser's console and see if there are any error messages.

**Comment by BenEar50** [comment]
I have tried again a few times since posting and there has been no changes.

**Comment by anku255** [comment]
Hi @BenEar50! Did you try to open the URL in the incognito mode? Can you please post some screenshots?

**Comment by thecodingaviator** [comment]
@BenEar50 please follow up or close this issue

**Comment by huyenltnguyen** [comment]
I'm closing this issue as it has gone stale. Please open a fresh one if it occurs again.
Thank you for reporting and happy coding!
