### ISSUE TITLE
Curriculum layout not responsive, like before

### ISSUE THREAD

**Issue by digilou** [freeCodeCamp/freeCodeCamp#17673]
#### Describe your problem and - if possible - how to reproduce it
The previous release of freecodecamp had a responsive layout for the text, code editor, and view. In other words, they'd stack on top of each other if I increase the browser zoom or worked on a tablet. This new release doesn't do that. It all squishes together in one row.

#### Add a Link to the page with the problem
learn.freecodecamp.org

#### Tell us about your browser and operating system

* Browser Name: Safari
* Browser Version: 11.1.1
* Operating System: macOS Sierra

**Comment by chaomt** [comment]
I didn't find this issue on my Safari (also version 11.1.1). Maybe this is not an issue any more. You could try it again and potentially close this issue if you don't find it.

**Comment by aditijoshi14** [comment]
I agree with @chaomt . I was not able to replicate this issue in my Safari 11.1.1, macOS Sierra. So this issue might have been fixed. Hence we could potentially close this issue. @digilou Are you still facing the issue?

**Comment by moT01** [comment]
Thanks for opening this PR @digilou - I'm not exactly sure where these problems were all occurring for you, but after navigating much of the website, I cannot find anywhere the text "squishes together" like you described. Perhaps it has all been resolved, or perhaps I couldn't find it. I believe this is no longer a problem, so I will close this issue for now. If you think I'm wrong feel free to reopen it and provide further details.

**Comment by digilou** [comment]
I guess I was thinking that sections should stack after a certain width happened? But that was a while ago since I reported this, and I haven't spent a lot of time here recently. If I encounter another issue, I'll open this again. Thanks!

<img width="616" alt="Functional Programming Lesson in a narrow width window with text squished." src="https://user-images.githubusercontent.com/8865558/52528828-12944680-2c94-11e9-82f5-6b1162777dd9.png">

**Comment by moT01** [comment]
Ahh, I see what you're saying now - the components or frames or whatever don't stack like you would expect on a phone or other small screen... for some reason, I was looking for text that squished together. This definitely makes for a bad experience.

**Comment by raisedadead** [comment]
This has been addressed in our upcoming release. It might be a while before you can see it on the main site.

**Comment by moT01** [comment]
Fixed in [beta](https://www.freecodecamp.rocks/) - Thanks for reporting @digilou.

**Comment by digilou** [comment]
Thanks, all!
