### ISSUE TITLE
challenge-setup-code: missing this. in create a stack class challenge

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#17675]
#### Describe your problem and - if possible - how to reproduce it
https://learn.freecodecamp.org/coding-interview-prep/data-structures/create-a-stack-class
the first line in the `stack()` function says `collection = [];` - it wont pass testing unless you change it to `this.collection = [];`

* Browser Name: Firefox
* Browser Version: 60.0.1
* Operating System: High Sierra

#### If possible, add a screenshot here
![screen shot 2018-06-21 at 7 46 50 am](https://user-images.githubusercontent.com/20648924/41720490-cf25266c-7528-11e8-8ab5-10f95d49475c.png)

<hr>

![screen shot 2018-06-21 at 7 46 37 am](https://user-images.githubusercontent.com/20648924/41720495-d3f5b378-7528-11e8-9a2d-a20e6bee4dba.png)

**Comment by ArielLeslie** [comment]
You don't have to `this` it, but because of strict mode it does need to be declared with `var`, `let`, or `const`.

**Comment by moT01** [comment]
so its missing the `let` then

**Comment by ArielLeslie** [comment]
That's how I would update it.
