### ISSUE TITLE
Use export to Reuse a Code Block - spaces issue

### ISSUE THREAD

**Issue by udidol** [freeCodeCamp/freeCodeCamp#17683]
In the ES6 challenge "Use export to Reuse a Code Block" the test doesn't pass if there is a space missing between the variable name and variable value. Since spaces do not matter in Javascript when it comes to variable assignment (and many other things), I believe this is an issue that could be corrected.

**Page link:** 
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-export-to-reuse-a-code-block/

**System info:**
* Browser Name: Chrome
* Browser Version: 67.0.3396.87
* Operating System: Windows 10

**Screenshot of the "foo" variable without space before the equal (=) sign, doesn't pass:**
![image](https://user-images.githubusercontent.com/36724484/41760207-01b3a964-75fb-11e8-9a39-af577056196d.png)

**Screenshot of the "foo" variable with space before the equal sign, passes:**
![image](https://user-images.githubusercontent.com/36724484/41760265-4785c832-75fb-11e8-8958-df3cb9ada2d6.png)

**Comment by scissorsneedfoodtoo** [comment]
@udidol, thank you for pointing this out. You're right, spaces for variable assignment don't matter. Would you be interested in submitting a PR to fix this? If so, please do it in the new [curriculum](https://github.com/freeCodeCamp/curriculum) repo.

**Comment by udidol** [comment]
I cloned the repo and found the problem.
Thing is, I tried to setup a local version of FCC according to the instructions provided here: https://forum.freecodecamp.org/t/how-to-clone-and-setup-the-free-code-camp-website-on-a-windows-pc/19366

And encountered problems. I opened an issue ([here](https://github.com/freeCodeCamp/freeCodeCamp/issues/17693)) in case other people encountered this and would know what to do.

Anyway, the problem is in the regular expression used to evaluate the challenge solution.

**Comment by scissorsneedfoodtoo** [comment]
@udidol, yes the regex for that challenge will need to be updated.

Sorry you're having problems with the `npm run only-once` command. A lot of users seem to be having problems with that recently. Thank you for opening an issue and describing the problem in such detail.

I saw that some users were able to work around the problem over on the [Gitter Contributor's chatroom](https://gitter.im/FreeCodeCamp/Contributors). Maybe you can find a solution in some of the old comments there!

**Comment by hbar1st** [comment]
just thought I should mention that many people hit this issue regularly because the starting code provided by the challenge doesn't have a space on the left side of the = sign and so if you just add the export statements, the challenge fails and you sit there wondering what you did wrong. (there's a 30 long  thread going on in the forum with people not able to figure this out)

**Comment by thecodingaviator** [comment]
@udidol / @scissorsneedfoodtoo I just checked and this problem has been fixed. Please close the issue
