### ISSUE TITLE
[Suggestion] Autofocus on text editor after completing the task

### ISSUE THREAD

**Issue by w96k** [freeCodeCamp/freeCodeCamp#17688]
#### Describe your problem and - if possible - how to reproduce it
I use mostly keyboard and its quite annoying to focus on text area after completing each task. After each task, I need to grab a mouse :(

#### Add a Link to the page with the problem
Any task

#### Tell us about your browser and operating system
Firefox 52
Debian 9

**Comment by Bouncey** [comment]
Issue moved to [freeCodeCamp/learn #192](https://github.com/freeCodeCamp/learn/issues/192) via [**ZenHub**](https://www.zenhub.com/)
