### ISSUE TITLE
Applied Visual Design: Adjust the Hue of a Color - Won't pass in Firefox ESR 52

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#17686]
#### Describe your problem and - if possible - how to reproduce it
The exercise won't pass in Firefox ESR (52.8.1), because of how it computes the cyan color in hsl. Using the hsl value in the instructions for cyan, the color is computed as `rgb(0, 255, 254)`, while the exercise is checking for `rgb(0, 255, 255)`.

Related forum thread: https://forum.freecodecamp.org/t/problem-with-adjust-the-hue-of-a-color/202568

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-hue-of-a-color/

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: ESR 52.8.1
* Operating System: Manjaro Linux

**Comment by thecodingaviator** [comment]
@kevcomedia I have done this challenge some days ago and afaik the problem has been fixed. Please close the issue
