### ISSUE TITLE
Login page loops with upgrade email message

### ISSUE THREAD

**Issue by tinydynamite00** [freeCodeCamp/freeCodeCamp#17680]
#### Describe your problem and - if possible - how to reproduce it

Logging into FCC using my GitHub credentials works. However, once in the FCC portal, I'm presented with an [Update your email](https://www.freecodecamp.org/update-email) page that I cannot circumvent to reach the curriculum. Also, I have tried logging in directly to FCC with an emailed code, but this presents another problem: The website doesn't recognize me as a returning user but as a new user, and none of the lessons I completed appear under the default username attached to my email account. I've used the same email address across both Github's and FCC's website.  

There are two recurring text/toast messages when attempting to update my email. The messages, paraphrased, are as follows:
* GDRP disclaimer regarding email retention,

* My email address shows up in the second message, which states the account is already in use.

#### Add a Link to the page with the problem
https://www.freecodecamp.org/update-email

#### Tell us about your browser and operating system

* Browser Name:  Chrome
* Browser Version:  67.0.3396.87 (64-bit)
* Operating System:  Windows 10 

#### If possible, add a screenshot here

![20180621_freecodecamp_screenshot_githubbugreporting_2](https://user-images.githubusercontent.com/6479505/41750484-6fdf6982-7579-11e8-9f7d-a5c603e0c864.png)

**Comment by xboudsady** [comment]
Yep, I'm running to the same problem...

**Comment by huyenltnguyen** [comment]
@tinydynamite00 @xboudsady You'll need to email team@freecodecamp.org with your account details (email address and github usernam) to get this fixed.

**Comment by tinydynamite00** [comment]
The flow from the login page to the FCC lessons has been updated since the issue was first submitted. 
Close #17680
