### ISSUE TITLE
Accepted answer is typo.

### ISSUE THREAD

**Issue by ilhamije** [freeCodeCamp/freeCodeCamp#17699]
### Problem
Answer code is not matched (typo) with instruction on _Basic CSS: Attach a Fallback value to a CSS Variable_

#### How to reproduce
Try to answer with `background: var(--penguin-skin, black);` on both penguin-top and penguin-bottom. It will tell you that the answers are wrong. But, when you change the answer line to `background: var(--pengiun-skin, black);` The answers would be right.

Accepted answer is `--pengiun-skin`. 
It should be `--penguin-skin`.
It's peng**UI**n, not peng**IU**n
It refers to variable `--penguin-skin` on class penguin.

#### The link
https://learn.freecodecamp.org/responsive-web-design/basic-css/attach-a-fallback-value-to-a-css-variable/

#### Browser and operating system

* Browser Name:  Firefox Quantum 
* Browser Version: 61.0b5 (64-bit)
* Operating System:  Ubuntu 16.04.4 LTS

#### Screenshot
![screenshot from 2018-06-23 14-13-54](https://user-images.githubusercontent.com/1570096/41807037-c34edfba-76f2-11e8-91d0-e251969bf8be.png)

**Comment by moT01** [comment]
I helped create these challenges - this was actually a deliberate typo to show how the fallback properties works

**Comment by amlagoda** [comment]
https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-variables-to-change-several-elements-at-once/

Error in current description:

![joxi_screenshot_1529830020780](https://user-images.githubusercontent.com/13574012/41817526-172bb656-77e0-11e8-810e-5fd729db1a8b.png)

Must be:
penguin class should declar the `--penguin-skin` variable and assign it to `gray`.
penguin class should declar the `--penguin-belly` variable and assign it to `white`.
penguin class should declar the `--penguin-beak` variable and assign it to `orange`.

**Comment by WizardOfAus** [comment]
^^ Yes there is a typo in description.

**Comment by pinduli** [comment]
As of July 6, 2018 @ 10:30pm CST there is no longer a typo in either .penguin-top or .penguin-bottom class. As a result, the lesson does not display correctly, but the tests still pass.

![untitled](https://user-images.githubusercontent.com/32426282/42406468-ff54c882-816d-11e8-85c2-ee56d7461ae3.jpg)
