### ISSUE TITLE
npm run develop fails

### ISSUE THREAD

**Issue by ktajpuri** [freeCodeCamp/freeCodeCamp#17695]
#### Describe your problem and - if possible - how to reproduce it

Follow the guide from scratch at [this link](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md)

reach till the below command
npm run develop

this command fails with below error
![image](https://user-images.githubusercontent.com/10725893/41788920-063428cc-766b-11e8-8992-6aea86e1cae8.png)

#### Tell us about your browser and operating system

* Browser Name: NA
* Browser Version: NA
* Operating System: macOS High Sierra 10.13.3

**Comment by paolaguarasci** [comment]
Same problem. [Here](https://github.com/nodejs/node/issues/20325) they say is a node v10 problem (my version is v10.10.0). I solved as write them with ``` npm i natives ```

**Comment by raisedadead** [comment]
We have refactored the repo since this issue. Please make a fresh clone and the instructions in the docs. You should be good to go.
