### ISSUE TITLE
Need certification help (wont give certification bug)

### ISSUE THREAD

**Issue by syne612** [freeCodeCamp/freeCodeCamp#17696]
its saying that i have not done the roman numeral converter but i have, and not only that it shows it as completed in my free code camp logs… i was wondering how to get this fixed so i could have that beautiful beautiful certification i have been working at. also let me just say… this is hands down the most amazing site ive ever used. Im actually mad there are not more places like this around (not even the free part, its the amount you guys have and the way you do the lessons, way better than learn by vid).

Profile Name: angelicarus

* Browser Name: chrome
* Operating System:  mac
(any info I'm missing for help?)

<img width="908" alt="screen shot 2018-06-22 at 2 53 58 am" src="https://user-images.githubusercontent.com/36472242/41790605-1bd65384-7621-11e8-8528-407a6d8011f7.png">
<img width="1033" alt="screen shot 2018-06-22 at 2 29 14 am" src="https://user-images.githubusercontent.com/36472242/41790606-1be5af64-7621-11e8-8f7f-d6ddc84ed41b.png">

**Comment by huyenltnguyen** [comment]
@syne612 If you go to the Settings page, scroll down to the `JavaScript Algorithms and Data Structures Projects` section, and click `Claim Certification`, is there any error message pops up on the screen? Please also check the browser console for error messages, if any.

**Comment by mattszcz** [comment]
> its saying that i have not done the roman numeral converter but i have
I had the same issue with the Palindrome Checker. I assume it's a bug from when they made the beta live. **I solved it by redoing the project.** You'll notice that FCC saves your code from your projects. If it doesn't have your code saved then it doesn't know you completed the project.

**Comment by syne612** [comment]
Yea but id rather not redo that thing it was a pain.

**Comment by syne612** [comment]
Did you get the most Recent email I sent you with the pictures?

**Comment by syne612** [comment]
Jk web surfed and grabbed online answer nbd

**Comment by thecodingaviator** [comment]
@syne612 / @Asjas please close this issue, seems fixed
