### ISSUE TITLE
Responsive Web Design Claim Certification Issue

### ISSUE THREAD

**Issue by golden-frog** [freeCodeCamp/freeCodeCamp#17698]
#### Describe your problem and - if possible - how to reproduce it
Cannot claim the Responsive Web Design Certification. All users stories are passed. Message: it looks like you have not completed the necessary steps. Please complete the required challenges to claim the Responsive Web Design

#### Add a Link to the page with the problem
https://www.freecodecamp.org/settings

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.87 (Official Build) (64-bit)
* Operating System: macOS 10.13.5

#### If possible, add a screenshot here
<img width="426" alt="screen shot 2018-06-22 at 23 52 38" src="https://user-images.githubusercontent.com/25009380/41802366-2f113048-7678-11e8-8a54-f562ab321260.png">
<img width="957" alt="screen shot 2018-06-22 at 23 53 09" src="https://user-images.githubusercontent.com/25009380/41802372-35e36404-7678-11e8-9a15-737315620e2d.png">
<img width="1256" alt="screen shot 2018-06-22 at 23 53 48" src="https://user-images.githubusercontent.com/25009380/41802386-43334322-7678-11e8-9ab4-1abb72c208bf.png">

**Comment by golden-frog** [comment]
Yes, there are. Don't see anything relevant, but I'm no expert. Here are the errors:

settings:1 Refused to load the stylesheet 'https://use.fontawesome.com/releases/v5.0.13/js/all.css' because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' *.gstatic.com *.googleapis.com *.bootstrapcdn.com https://*.bootstrapcdn.com *.cloudflare.com https://*.cloudflare.com https://*.optimizely.com 'self' https://search.freecodecamp.org https://*.algolianet.com".

createAlgoliasearch.js:107 Refused to connect to 'https://qmjyl5wyti-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%20(lite)%203.26.0%3Breact-instantsearch%205.0.1%3BJS%20Helper%202.24.0&x-algolia-application-id=QMJYL5WYTI&x-algolia-api-key=4318af87aa3ce128708f1153556c6108' because it violates the following Content Security Policy directive: "connect-src 'self' https://search.freecodecamp.org https://*.algolianet.com https://glitch.com https://*.glitch.com https://*.glitch.me https://*.cloudflare.com".
(anonymous) @ createAlgoliasearch.js:107

settings:1 Refused to load the stylesheet 'https://use.fontawesome.com/releases/v5.0.13/js/all.css' because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' *.gstatic.com *.googleapis.com *.bootstrapcdn.com https://*.bootstrapcdn.com *.cloudflare.com https://*.cloudflare.com https://*.optimizely.com 'self' https://search.freecodecamp.org https://*.algolianet.com".

**Comment by huyenltnguyen** [comment]
@golden-frog No I don't think those are relevant either. I have to pass this one to someone else then, since I'm not able to offer any further help :( Sorry about the inconvenience.

**Comment by huyenltnguyen** [comment]
Hi @Bouncey, could you take a look at this issue?
The same issue was reported in https://github.com/freeCodeCamp/freeCodeCamp/issues/17363 and was fixed via https://github.com/freeCodeCamp/freeCodeCamp/pull/17389, but looks like it still persists.
Could this somehow be related to https://github.com/freeCodeCamp/freeCodeCamp/issues/17522?

**Comment by golden-frog** [comment]
No worries. Thank you for your time.

**Comment by reggieds** [comment]
Same with me, still can not claim Responsive Web Design certificate.

**Comment by nathanielgecse** [comment]
Same issue here too, also completed and unable to claim Responsive Web Design certificate

**Comment by heidi37** [comment]
Yes,

Same issue for me. All my challenges are uploaded and they all pass the tests.

![image](https://user-images.githubusercontent.com/28228859/41811338-aee80888-76c2-11e8-8faa-13af3ec55d2c.png)

**Comment by VM-Deus** [comment]
Same here. All my projects pass the test. Super frustrating. 
![screen shot 2018-06-23 at 11 49 32 am](https://user-images.githubusercontent.com/34935667/41811391-a4c06372-76dc-11e8-864c-a45031e6a3df.png)

**Comment by aleksmn** [comment]
Same problem... Here is Google Chrome console:
![image](https://user-images.githubusercontent.com/18387112/41812188-30d475ca-7727-11e8-9c04-9f5429e33e43.png)

**Comment by Gogmazios** [comment]
I'm having the same issue.

**Comment by thehiddencheese** [comment]
Also having the same issue, hope you guys figure it out!

**Comment by abenjamin765** [comment]
Same

**Comment by IbrahimTarabay** [comment]
Same Unable to claim Responsive web design certificate

**Comment by PrvnToddy** [comment]
I'm having the same issue.

**Comment by johnkennedy9147** [comment]
@QuincyLarson @raisedadead @Bouncey 
I was able to recreate this on a fresh test id:

- created new id
- accepted TOC and privacy policy
- added urls to responsive design projects
- saved progress
- claimed certificate
- got error message 
- accepted academic honesty policy
- claimed certificate
- got error message


Further investigation:
- Tried clearing and resubmitting urls - same issue
- added name and location to profile - same issue
- signed up for quincy email - same issue
- made profile public - same issue
- added some text to about section - same issue
- updated username - same issue
- signed out and back in - same issue
- toggled night mode on - same issue
- added urls for github, twitter etc - same issue
- completed some challenges from responsive web design section - same issue

Downloaded my data multiple times and everything seemed OK. 
However, there is an empty `files` array for each challenge that I dont remember previously - not sure if thats related to the issue.

**Comment by huyenltnguyen** [comment]
@johnkennedy9147 I just submitted a PR over the curriculum repo to fix this. It would be great if you give it a review.

**Comment by huyenltnguyen** [comment]
Oh the `files` array is new, btw, that's the new change in the challenge schema. I read somewhere that we will implement multiple files (html, css, js) within a challenge in the future.

**Comment by heidi37** [comment]
This ticket says it is closed but I still can't claim the certificate. I have completed all the challenges and they pass all the tests. Is there something special I need to do to get it to go through?

**Comment by Asjas** [comment]
I'm suspecting the latest version might not be deployed yet. I'm having the same issue.

**Comment by Bouncey** [comment]
Hi @Asjas @heidi37 @PrvnToddy @IbrahimTarabay @abenjamin765 @thehiddencheese @Gogmazios @aleksmn @VM-Deus @nathanhannig @reggieds @golden-frog 

The fix has now been pushed to production, please try and claim the certification again :+1:

**Comment by VM-Deus** [comment]
It still won't work for me, projects all pass the test. Same error as above.

**Comment by nathanielgecse** [comment]
^same as VM-Deus, still not working for me

**Comment by craigandrewblair** [comment]
Hi, same as VM-Deus, attempted yesterday and today. Thanks

**Comment by Bouncey** [comment]
@VM-Deus @nathanielgecse Thank you for the quick response. I have reset the cache on the server, could you try again for me please?

**Comment by johnkennedy9147** [comment]
Working on my test id.

Initially saw same error. But might have been timing if deploy hadn't completed / was before cache reset.
I then resubmitted 1 of the projects and tried again and it worked.
So either:
I tried before deploy / cache reset finished then second time was after.
Or:
You need to resubmit project.

@VM-Deus @nathanielgecse @craigandrewblair 
Can you try again and if it still doesnt work try submitting one of the urls again then try once more.
thanks

**Comment by VM-Deus** [comment]
@johnkennedy9147 it worked after I resubmitted one of my projects!

Thanks!

**Comment by nathanielgecse** [comment]
@Bouncey working now!. I should also note that it worked for me before I resorted to trying to resubmit a project like @johnkennedy9147 recommended.

Thanks, appreciate the help immensely!

**Comment by craigandrewblair** [comment]
Thanks for quick response! Working now after resubmitting one of my projects and then reclaiming.

**Comment by golden-frog** [comment]
Thanks a lot @huyenltnguyen @Bouncey @johnkennedy9147 and others!

**Comment by FinQode** [comment]
It's working for me as well at the moment. Great job to all who fixed this! Thanks :-D

**Comment by Gogmazios** [comment]
Yes! This makes me so happy. Thank you for all the hard work. FCC is amazing.

**Comment by thehiddencheese** [comment]
Awesome job guys, got my cert now :)

**Comment by Yariandres** [comment]
Having some issues claiming the Responsive Web Design Projects Certicicate
Errors:
1)
yariandres has not yet agreed to our Academic Honesty Pledge. (Yes, I did  agreed).
2)
In order to view their freeCodeCamp certifications, they need to make their profile public. (I did make it public)

**Comment by raisedadead** [comment]
Hi @Yariandres you may have duplicate accounts. Can you send us an email `dev at freecodecamp dot org`
