### ISSUE TITLE
Mispelling in CSS coding section

### ISSUE THREAD

**Issue by austinphotog** [freeCodeCamp/freeCodeCamp#17697]
#### Describe your problem and - if possible - how to reproduce it
I noticed this as I was going back to complete the new sections of after the latest curriculum change, the but under the links "Run The Tests", "Reset All Code", and "Ask For Help" where it says the required changes to pass the test has a misspelling, it says "penguin class should declar the --penguin-skin variable and assign it to gray." where I believe it should be spelled "declare" with an E on the end ;)

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-variables-to-change-several-elements-at-once

#### Tell us about your browser and operating system

* Browser Name: Vivaldi
* Browser Version: 1.15.1147.47
* Operating System: Mac OS 10.13.3

#### If possible, add a screenshot here
<img width="1646" alt="screenshot 2018-06-22 16 41 21" src="https://user-images.githubusercontent.com/19712005/41798304-2b82863a-763b-11e8-8d56-184336d63432.png">

**Comment by alamathe1** [comment]
can i take it up pls?
