### ISSUE TITLE
Can't use <i> instead of <img> in 'Responsive Web Design Project'

### ISSUE THREAD

**Issue by supuun** [freeCodeCamp/freeCodeCamp#17690]
#### Describe your problem and - if possible - how to reproduce it
I want to use font awesome icon for my header logo and it requires i tag, but it doesn't pass, because  img tag is required. please, remove that requirement or add i tag as a possible choice. 

#### Add a Link to the page with the problem
User Story #2:
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-product-landing-page/
My website:
https://codepen.io/supuun/pen/vrjbWN

**Comment by anku255** [comment]
Hi @supuun! Changing the test suit for a specific case might not be as simple. We will have to wait for the project maintainers to discuss this and it may take some time.

In the meantime, I have a quick solution for you. You can use a [fontawesome-to-png](http://fatopng.com/fontawesome-to-png) converter to convert your icon to a png and then you can put it in the `img` tag. In fact, I have created one for you myself. [Check it out](https://i.imgur.com/We8hKUf.png).

**Comment by supuun** [comment]
Thank you so much, light

**Comment by supuun** [comment]
Love it. I should say my second fav anime. It was my first one.

**Comment by anku255** [comment]
@supuun I probably shouldn't be asking here but you have made me very curious. Which is your favourite anime? 😝

**Comment by supuun** [comment]
Steins;gate 😄
