### ISSUE TITLE
unable to claim responsive certification

### ISSUE THREAD

**Issue by IbrahimTarabay** [freeCodeCamp/freeCodeCamp#17708]
it looks like you have not completed the necessary steps. Please complete the required challenges to claim the Responsive Web Design

**Comment by DavidJamesAustin** [comment]
Duplicate of #17698 - It was marked as closed when a PR was submitted & merged http://[here](https://github.com/freeCodeCamp/curriculum/pull/43). You'll just have to wait for it to be deployed which is explained in the last post there.

**Comment by johnkennedy9147** [comment]
closed as duplicate of #17698
