### ISSUE TITLE
Code has been deprecated in "Implement the Serialization of a Passport User"

### ISSUE THREAD

**Issue by lieberscott** [freeCodeCamp/freeCodeCamp#17704]
#### Describe your problem and - if possible - how to reproduce it
Code in the instructions for "Implement the Serialization of a Passport User" has been deprecated in MongoDB versions 3.0.0+

Current instructions tell the student to use this code:

```
mongo.connect(process.env.DATABASE, (err, db) => {
    if(err) {
        console.log('Database error: ' + err);
    } else {
        console.log('Successful database connection');
        //serialization and app.listen
}});
```
This code "works" for this challenge, but only because the `db` object is not yet used. In subsequent challenges -- for example, the "Authentication Strategies" challenge -- the camper is supposed to use the `db` object. However, in MongoDB v3+, the camper will get unexpected errors. (This is on top of the fact that, as of this writing, none of the tests for the Advanced Node & Express tutorials are working anyway.)

What is returned in the latest version of MongoDB is a client object which contains the db object. Therefore, code needs to look something like this:

```
mongo.connect(process.env.DATABASE, (err, client) => { // change return object to client instead of db

    // add this line
    let db = client.db('nameOfDatabase');

    if(err) {
        console.log('Database error: ' + err);
    } else {
        console.log('Successful database connection');
        //serialization and app.listen
}});
```

This is explained by MikaS's answer here: https://stackoverflow.com/questions/47662220/db-collection-is-not-a-function-when-using-mongoclient-v3-0

The subsequent "Authentication Strategies" challenge will then work as is since the camper defines the `db` object correctly in this challenge.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/implement-the-serialization-of-a-passport-user

**Comment by anku255** [comment]
@lieberscott Freecodecamp's boilerplate uses mongodb [version ^2.2.22](https://github.com/freeCodeCamp/boilerplate-advancednode/blob/944fa6616529ef25e8ffa70125847e2225d96389/package.json#L17)

If I am not wrong then the code written for mongodb version 3.x won't be compatible with verison 2.x. So, we will have to make a decision whether to use the latest version or stick with the older one. In case of using latest version we will have to update both the boilterplate and challenges.
