### ISSUE TITLE
Curriculum lessons will not display

### ISSUE THREAD

**Issue by jr-55** [freeCodeCamp/freeCodeCamp#17702]
#### Describe your problem and - if possible - how to reproduce it

When I click on new or old lessons I get a blank white screen. I have refreshed, signed in/out and yet a white screen.

#### Tell us about your browser and operating system

* Browser Name: safari
* Browser Version: 9.3.5
* Operating System: IOS—IPad 2

**Comment by huyenltnguyen** [comment]
Hi @jr-55, could you try accessing the page using Firefox or Chrome? As far as I know, FCC page doesn't work well in Safari, Edge, or IE.

**Comment by emmanuelkant** [comment]
@jr-55, For me works in Mozilla, but not in Chrome. Try another browser.

**Comment by jr-55** [comment]
I appreciate your help huyenltnguyen, thanks!     Chrome—same results, the latest version of Firefox I was unable to download because my IPad2 is unable to support It. I’m able to see most of the latest FCC updates but strangely my lessons will not display.

**Comment by huyenltnguyen** [comment]
@jr-55 Sorry to hear that it still doesn't work for you. There are a number of reported issues regarding the page display on mobile devices. As far as I know, FCC doesn't support mobile devices yet and using a desk device is recommended.
