### ISSUE TITLE
Alt Attribute Issue 

### ISSUE THREAD

**Issue by ArtemSer** [freeCodeCamp/freeCodeCamp#17701]
In the task "Applied Accessibility: Add a Text Alternative to Images for Visually Impaired Accessibility".

When a person opens`alt` attribute, he can see a lot of code that he doesn't need for this task.

![deepinscreenshot_20180623222101](https://user-images.githubusercontent.com/22551739/41812881-1a90f6dc-7734-11e8-9ca9-a6601f3f1ccd.png)

**Comment by MThicklin** [comment]
If you place just '**<img alt="** ' at the top of, _Don't quote me on this as I haven't tested EVERY page_, pretty much any page and that good sized block of code appears in the result section.  I tried to add images but github wasn't a huge fan of them.  Here is an imgur link, The pictures have some additional information.

https://imgur.com/a/ZmL5yTi

#### Add a Link to the page with the problem
So far every page I have tried it on shows the code.
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements/

#### Tell us about your browser and operating system
* Browser Name: Chrome 
* Browser Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Linux Mint 18 XFCE

**Comment by Ieahleen** [comment]
it's not only with the alt attribute, but anytime you have only one quote there are strange changes to the things being shown.
Here I have only an open quote on setting a class for an element, and the formatting is all gone now

With the corret quotes: 
![image](https://user-images.githubusercontent.com/26656284/42578990-9bdeb552-8527-11e8-93ca-f92b275bdb9e.png)

With only one quote:
![image](https://user-images.githubusercontent.com/26656284/42578937-8c580f16-8527-11e8-8931-55072cd5b758.png)

**Comment by thecodingaviator** [comment]
@ArtemSer Afaik, this has been fixed. Please close the issue.

cc: @scissorsneedfoodtoo
