### ISSUE TITLE
Rosetta code tasks.

### ISSUE THREAD

**Issue by Paddy3118** [freeCodeCamp/freeCodeCamp#17700]
Full text here: https://forum.freecodecamp.org/t/use-of-rosetta-code-sites-examples/202558?u=paddy3118

I was then told that this is the place to submit...

**Comment by moT01** [comment]
Maybe something like one of these.... ?

```
link at bottom of description:
```

<img width="601" alt="Screen Shot 2019-07-09 at 7 08 39 AM" src="https://user-images.githubusercontent.com/20648924/60886766-680b5a00-a218-11e9-8280-cc12a3b9dee1.png">

```
link at bottom of instructions:
```

<img width="604" alt="Screen Shot 2019-07-09 at 7 05 14 AM" src="https://user-images.githubusercontent.com/20648924/60886569-f6cba700-a217-11e9-8595-442213c0ca1b.png">

**Comment by RandellDawson** [comment]
We typically try to avoid linking to external sites which we do not control in the curriculum.

**Comment by Paddy3118** [comment]
Hi @RandellDawson, this is more like being a good netizen and both acknowledging sources and allowing your students wider access..

**Comment by moT01** [comment]
We are using their content, so it might be a good place to make an exception. Although, we do have "Rosetta Code" in the title of every challenge and there is a link in the introduction.

**Comment by RandellDawson** [comment]
@Paddy3118 You can always create a guide article for each challenge which could have a link to other information for the challenge (in a More Information) section of each article.  However, you would also need to add an actual solution and/or hints and not just a link as we don't approve PRs which only add links to other sites in the guide.

**Comment by Paddy3118** [comment]
@RandellDawson, you misunderstand, its more about asking those who copy such tasks to, as a matter of course, also link to that source. References are a standard in academia and Wikipedia for example, an aids readers and authors alike.

**Comment by RandellDawson** [comment]
@Paddy3118 Like @moT01 already mentioned, the credit to the site is in the introduction to these challenges.  Other than that, you are free to create a PR which adds a relevant link in the corresponding guide articles for each Rosetta Code challenge as I have already mentioned in a previous reply.  You can reference this issue when creating the PR.

**Comment by moT01** [comment]
Yea, I think we are all for giving credit where it is due - but do we really need a link on every challenge? Seems like overkill - especially when we are trying to avoid using external links in the descriptions.

I'll ping @QuincyLarson - he's the one who will have the best input on this - maybe he can weigh in if he gets a chance.

**Comment by Paddy3118** [comment]
A link to just rosettacode.org is as bad as a link to the main page of Wikipedia when there is a lot of content then you link to the page of interest.

**Comment by QuincyLarson** [comment]
Hi @Paddy3118 First of all, thank you for your patience.

I apologize for the long lead time it took for your issue to come to my attention.

We love Rosetta Code and are excited to hear from you all. 

I reached out Mike Mol back in 2017 (the official contact from Rosetta Code's about page) through several different means, but never heard back from him. So we went forward crediting the Rosetta Code team and respecting your open source license.

I would love to talk with you and learn more about the project and how we can further team up to help as many people as possible learn to code. 

When you get a moment, could you send me an email at quincy@freecodecamp.org?

I'm going to close this issue and we can discuss this further through email and then hopefully a video call. I'm excited to meet you all.

**Comment by Paddy3118** [comment]
Hi Tom, unfortunately I can't work out where the green text links to, but
if it goes to the specific tasks page rather than the RC sites home page,
then that would be ace.

- Paddy.
