### ISSUE TITLE
News item missing and yet not mising

### ISSUE THREAD

**Issue by DarrenfJ** [FreeCodeCamp/FreeCodeCamp#1770]
Not sure if this is the right place to post this.. 

Basically, in the news section I wanted to post this: https://www.udacity.com/course/how-to-use-git-and-github--ud775

But it tells me it's already there AND that it doesn't exist...

I get these two messages at once: Someone's already posted that link. Here's the discussion.
404: We couldn't find a story with that name. Please double check the name.

If I search for the link it shows up but clicking discuss ten gives the warning that it doesn't exist

**Comment by benmcmahon100** [comment]
This was because of there was a migration in progress and some new stuff got lost. It should be there or at least possible to post it now!
