### ISSUE TITLE
Project Euler: Problem 7 tests won't pass, solution cuts off at 100ms

### ISSUE THREAD

**Issue by Kornelijus** [freeCodeCamp/freeCodeCamp#17715]
#### Describe your problem and - if possible - how to reproduce it

A reasonable solution to the problem (finding the 10001st prime) takes 2.5s to run, but freeCodeCamp cuts it off at 100ms.
The solution works fine on Node.js and in the Console.

To reproduce the issue, paste this code into the editor and run the tests.
```javascript
function nthPrime(n) {
  let found;
  for(let i = 2, count = 0; !found; i++) {
    let prime = true;
    for(let j = 2; j < i; j++) {
      if(i % j === 0) {
        prime = false;
        break;
      }
    }
    if(prime) count++;
    if(count === n) found = i;
  }
  return found;
}

let timeStart = performance.now();
let result = nthPrime(10001);
let timeStop = performance.now();

console.log('freeCodeCamp Editor');
console.log('time to run:', timeStop - timeStart);
console.log('result:', result ? result : 'did not finish');
console.log('should be: 104743');
```

#### Add a Link to the page with the problem

[Project Euler: Problem 7: 10001st prime](https://learn.freecodecamp.org/coding-interview-prep/project-euler/problem-7-10001st-prime/)
Possibly other challenges that take longer than 100ms to run.

#### Tell us about your browser and operating system

* Browser Name: Chromium
* Browser Version: 67.0.3396.62
* Operating System: Ubuntu 18.04 LTS

#### If possible, add a screenshot here

![](https://i.imgur.com/8XpmEWB.png)

Edit:
[Project Euler: Problem 4: Largest palindrome product](https://learn.freecodecamp.org/coding-interview-prep/project-euler/problem-4-largest-palindrome-product)
[Project Euler: Problem 5: Smallest multiple](https://learn.freecodecamp.org/coding-interview-prep/project-euler/problem-5-smallest-multiple)
These seem to be affected by the same issue.

**Comment by snehal96** [comment]
the issue still persists in the site, the code does not produce correct answer even though other online compilers produce correct results for the same code

**Comment by Bouncey** [comment]
As noted by the label added by @ValeraS, this issue has been resolved on the master branch and should be available for public test shortly. The idea is then to deploy master to production after a suitable burn-in period.
