### ISSUE TITLE
Build a Product Landing Page project should allow SVG on test #2

### ISSUE THREAD

**Issue by perezvon** [freeCodeCamp/freeCodeCamp#17718]
#### Describe your problem and - if possible - how to reproduce it
Test #2 on the Product Landing Page fails if I use raw SVG as the src. Looks like it's expecting the src string to begin with `http`, but the svg source begins with `data:image/svg+xml`. It's valid to use SVG in an image tag, right? So it should be valid to pass the test?

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-product-landing-page

#### Tell us about your browser and operating system

* Browser Name: Chrome 
* Browser Version: 67.0.3396.87
* Operating System: Windows 10

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/12534169/41867349-84e39018-7878-11e8-9b51-5bef90fe8415.png)

**Comment by RandellDawson** [comment]
@tbushman Is this an issue?

**Comment by tbushman** [comment]
@RandellDawson I would say close this. A dataURL would fail the test for any type of image. People can use SVG by saving in the cloud and using that URL in `src`.
