### ISSUE TITLE
Internal Link not working in CatPhotoApp (Basic HTML and HTML5 Tutorial)

### ISSUE THREAD

**Issue by DivyanshBatham** [freeCodeCamp/freeCodeCamp#17713]
#### Describe your problem and - if possible - how to reproduce it
The task requires you to link the anchor text "Jump to Bottom" to the footer having id="footer". After coding is done, if the student tries to click the anchor tag in the display at the right (to visually experience the internal links). Then, instead of redirecting to the bottom to Cat Photo App, it redirects to the footer of the freeCodeCamp website in the new tab.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/link-to-internal-sections-of-a-page-with-anchor-elements

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 67
* Operating System: Windows 10

**Comment by congociti** [comment]
Having the same issue.

**Comment by scissorsneedfoodtoo** [comment]
@DivyanshBatham, thank you for reporting this. @congociti, thanks for confirming this. We'll definitely have to look into the issue.

**Comment by DivyanshBatham** [comment]
@scissorsneedfoodtoo Can you tell me how can I contribute to the lecture notes, I have found a typo on this page(https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-set-of-radio-buttons/). Is the data being pulled from the database?

**Comment by scissorsneedfoodtoo** [comment]
@DivyanshBatham, great catch! Didn't notice that typo earlier.

To contribute, please submit a PR to the new [Curriculum repo](https://github.com/freeCodeCamp/curriculum) the challenges were recently moved to. You can find the seed file for all the basic HTML challenges at `curriculum/challenges/01-responsive-web-design/basic-html-and-html5.json`.

There's not contributing guide in that repo yet, but not much has changed from the old guide. Take a look at the [Forking the Project](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#forking-the-project) section, and [Make Changes](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#make-changes-1). There are some differences in both steps, and a bunch of unnecessary steps between them. We'll get a guide up in the Curriculum repo soon!

Please go to the [Contributor's Chatroom](https://gitter.im/FreeCodeCamp/Contributors) for any help you need along the way, or feel free to @mention me!

**Comment by DivyanshBatham** [comment]
@scissorsneedfoodtoo I see you have already fixed the typo, thanks for that and the info you provided.

Next time when I find an opportunity, I'll definitely submit a PR.
