### ISSUE TITLE
FCC Certificate being in HTML is editable and can be manipulated from inspect element.  

### ISSUE THREAD

**Issue by NadeemGorsi** [freeCodeCamp/freeCodeCamp#17710]
Just got my first FCC certification and and I found that the certificate page is an HTML page and can be edited for example I can edit my name into Some One.
Its not a technical issue but still feels little awkward. I think the certificate should be in image format so it won't be so easy to fool about FCC Certificate.
Happy Coding,

https://www.freecodecamp.org/certification/nadeemgorsi/legacy-front-end

![capture1](https://user-images.githubusercontent.com/22592265/41822444-1e158f5e-7809-11e8-800c-514fb716b027.PNG)

**Comment by DavidJamesAustin** [comment]
I see this as something that would be hard to provide a good solution to. At the bottom of the certificate, you can see a link to your own user certification link to verify it. That link is the best way to prove authenticity of the certificate. Anyone can easily re-produce the certificate in a design program if they want to work around that.

**Comment by thecodingaviator** [comment]
@raisedadead / @QuincyLarson If you want, I can develop a script that will screenshot the certificate and display it as an image, this would also help in ensuring all certificates are of the same size or we can have a numbering system

**Comment by raisedadead** [comment]
@NadeemGorsi Thanks for the issue report and the concern.

We have the certs verifiable at a given URL. That is a digital copy that is verifiable only and only by visiting a given link on the certificate. 

Sure, anyone can edit these at their will, print them and showcase them. However, anyone just can't insert these into the URL where these get verified, which is the crux of the certs that are earned by campers on freeCodeCamp.org.
