### ISSUE TITLE
This task does not be send. Maybe a bug.

### ISSUE THREAD

**Issue by emmanuelkant** [freeCodeCamp/freeCodeCamp#17716]
#### Describe your problem and - if possible - how to reproduce it

I can't send my exercice. I guess that I reach on the end of task, but when I click at "Run the Tests", it's not pass. Your console show that "Unexpected token ?". But I sure that this correct. Somebody can help me? Thank you for your work, it's amazing.

**Link to the challenge:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/declare-a-read-only-variable-with-the-const-keyword/

User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36</code>.
* Operating System: Windows 10 

#### If possible, add a screenshot here

![capturar](https://user-images.githubusercontent.com/22749707/41853131-649d8f44-7863-11e8-9d36-2ef44aef5c78.PNG)

**Comment by moT01** [comment]
Thank you for reporting this issue.

This issue appears to be fixed.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
