### ISSUE TITLE
Same Variable Names in instructions for "Basic CSS: Use CSS Variables to change several elements at once"

### ISSUE THREAD

**Issue by prateek18597** [freeCodeCamp/freeCodeCamp#17717]
#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-variables-to-change-several-elements-at-once
#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 
* Operating System: Ubuntu 16.04

#### If possible, add a screenshot here

![freecodecamp](https://user-images.githubusercontent.com/24530309/41859606-225a3bbc-78ba-11e8-9132-51859243429d.png)

**Comment by scwong93** [comment]
I would like to attempt this issue please.

**Comment by scwong93** [comment]
The curriculum content was not in this repo. I made the necessary changes and created the PR here: https://github.com/freeCodeCamp/curriculum/pull/54
