### ISSUE TITLE
Applied Accessibility: Improve Accessibility of Audio Content with the audio Element Bug

### ISSUE THREAD

**Issue by Romicodes** [freeCodeCamp/freeCodeCamp#17723]
#### Describe your problem and - if possible - how to reproduce it
Repeatedly shows make sure your audio element has  a closing tag, won't progress

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/improve-accessibility-of-audio-content-with-the-audio-element/

#### Tell us about your browser and operating system

* Browser Name:  Chrome
* Browser Version: 
* Operating System:  Windows 10

#### If possible, add a screenshot here

![screenshot 97](https://user-images.githubusercontent.com/26821653/41923419-5ccf4cb2-7935-11e8-94d9-a68fced1b547.png)

**Comment by TheSoulOfaLion** [comment]
Hi! The test doesn't pass validation because your tag <audio> have an id. After removing the id, the validation will be passed. Be careful you can skip extra space and the test will get stuck again.

**Comment by Romicodes** [comment]
Thanks @TheSoulOfaLion . I removed the tag and it worked perfectly !
