### ISSUE TITLE
Bonfire: Meet Bonefire - Unable to run code to submit

### ISSUE THREAD

**Issue by marpy** [FreeCodeCamp/FreeCodeCamp#1772]
Tried on multiple Chrome browsers, neither clicking run code nor hitting CTRL + Enter on the keyboard do anything. 

Edit: This seems to occur with any bonfire. <del>Is linking github as my login a cause of this?</del>
Edit 2: Running code for the same pages works in FF: Developer's Edition

**Comment by benmcmahon100** [comment]
The code is running but it's just slow. We're working on this now!
