### ISSUE TITLE
I’m Being bounced around the curriculum! is that normal?

### ISSUE THREAD

**Issue by BenjaminJenney** [freeCodeCamp/freeCodeCamp#17727]
#### Describe your problem and - if possible - how to reproduce it
I started from the top, the HTML section, and have been going from one challenge to the next. After putting many hours in I decided to look at the curriculum and noticed that I’ve only finished a portion of the CSS section, before ending up in the front end libraries section! Is it supposed to bounce me around like this! or did i screw something up? please let me know. thank you.

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by moT01** [comment]
@BenjaminJenney it is not supposed to bounce you around like that - has this problem continued or can anyone else confirm this?

**Comment by BenjaminJenney** [comment]
Hi, op here, it hasn’t happened to me again and   It’s possible I may have
messed up on my end.

**Comment by thecodingaviator** [comment]
@BenjaminJenney if it is fine now, please close this issue
