### ISSUE TITLE
Remember to Set the Constructor Property when Changing the Prototype: clarification needed

### ISSUE THREAD

**Issue by lynxlynxlynx** [freeCodeCamp/freeCodeCamp#17735]
#### Describe your problem and - if possible - how to reproduce it
The challenge says re-setting the constructor is crucial, but not why. There's no motivation provided to do it, especially if you heed the earlier advice of prefering the use of instanceof.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/remember-to-set-the-constructor-property-when-changing-the-prototype

**Comment by ezioda004** [comment]
@lynxlynxlynx I agree, the motivation can be explicitly mentioned.
And the example is wrong too:
```js
console.log(duck.constructor)
// prints ‘undefined’ - Oops!
```
When infact it returns:
```js
console.log(duck.constructor);
// ƒ Object() { [native code] }
```
Since all objects inherit from `Object.prototype` which have a `.constructor` property.
Making a PR to fix this.

**Comment by lynxlynxlynx** [comment]
This is the referenced previous challenge:
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/change-the-prototype-to-a-new-object/

I get a different printout (probably browser-specific), so the whole example is iffy. I think it would be better to show how `x.constructor !== Bird` like in the non-overriden examples.
```
function Dog(name) {
  this.name = name; 
}

// Modify the code below this line
Dog.prototype = {
  
  numLegs: 2, 
  eat: function() {
    console.log("nom nom nom"); 
  }, 
  describe: function() {
    console.log("My name is " + this.name); 
  }
};
Object { numLegs: 2, eat: eat(), describe: describe() }
> a = new Dog()
Object { name: undefined }
> a.constructor
function Object()
> typeof a.constructor
"function"
> a.constructor === Dog
false
> a instanceof Dog
true
> a.constructor === Object
true
```

**Comment by lynxlynxlynx** [comment]
I think the last three lines are plenty enough (and clearer) to fix the example. The first of these lines is what the exercise is about — making it work again. Just add an extra touchup on the description and I'll be satisfied.

**Comment by ezioda004** [comment]
@lynxlynxlynx How about this?
>There is one crucial side effect of manually setting the prototype to a new object. It erased the `.constructor` property! The `.constructor` property can be used to check which function constructor created the instance object but since the `.constructor` property is overwritten, it gives false results:
```
duck.constructor === Bird; // false -- Oops
duck.constructor === Object; // true, all objects inherits from Object.prototype
duck instanceof Bird; // true, still works
```

**Comment by lynxlynxlynx** [comment]
Cool, here's my amended version (grammar and simplification):

> There is one crucial side effect of manually setting the prototype to a new object. It erases the `constructor` property! That property can be used to check which function created the object instance, but since the property has been overwritten, it now gives false results:

 
 ```js
 duck.constructor === Bird; // false -- Oops
 duck.constructor === Object; // true, all objects inherit from Object.prototype
 duck instanceof Bird; // true, still works
 ```
