### ISSUE TITLE
Not able to run the code when I hit Ctrl+Enter

### ISSUE THREAD

**Issue by inarayan** [FreeCodeCamp/FreeCodeCamp#1773]
Challenge http://freecodecamp.com/challenges/bonfire-mutations has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
Steps to replicate the scenario:

1.Write any program and try submitting it.
2.It never runs irrespective of what the answer is.

Regards,
Indra

**Comment by saadanerdetbare** [comment]
maybe not the most elegant solution but 5 mins code results in a green tick
```
function mutation(arr) {
  var base = arr[0].toLowerCase();
  var searchString = arr[1].toLowerCase().split("");
  var isFound = true
  searchString.forEach(function(element){
    if(base.indexOf(element) === -1){
      isFound = false;
    }
  });
  return isFound;
}

mutation(['hello', 'hey']);
```

**Comment by benmcmahon100** [comment]
Hey we are currently working on this! Thanks for your patience.
