### ISSUE TITLE
Cloned repo but can't run 'npm run unpack'

### ISSUE THREAD

**Issue by JamesStaffordCoyte** [freeCodeCamp/freeCodeCamp#17738]
#### Describe your problem and - if possible - how to reproduce it
I am running a local repo of freeCodecamp and am on a new branch but when I run 'npm run unpack' I am getting error messages.

The Error says that it can't find /Desktop/FreeCodeCamp/freeCodeCamp/seed/unpack.js'

I am trying to fix the html on one of the challenges but can't seem to access the challenges this way. 

Any reason this is the case?

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System: OSX

**Comment by raisedadead** [comment]
We have refactored our repositories to be a mono repo now. Please re-clone this repo and make a fresh installation
