### ISSUE TITLE
wrap-reverse: wrong definition in CSS flexbox

### ISSUE THREAD

**Issue by antalmega** [freeCodeCamp/freeCodeCamp#17736]
#### Describe your problem and - if possible - how to reproduce it
In the challenge **CSS Flexbox: Use the flex-wrap Property to Wrap a Row or Column**, the value *wrap-reverse* is defined:

**wrap-reverse**: "wraps items from right-to-left if they are in a row, or bottom-to-top if they are in a column."

This definition is not correct. Actually *wrap-reverse* wrap content changing de cross-axis direction, bottom to top in a row, and left to right in a column.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/css-flexbox/use-the-flex-wrap-property-to-wrap-a-row-or-column

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by scwong93** [comment]
I'd like to take on this issue please

**Comment by scwong93** [comment]
Since the curriculum content is in the `curriculum` repo, I submitted the PR there. https://github.com/freeCodeCamp/curriculum/pull/70

**Comment by antalmega** [comment]
Ok, thanks Simon.
