### ISSUE TITLE
FCC accepts "{a: 'b'}" but not "{a: 'b',}" (with an extra comma)

### ISSUE THREAD

**Issue by azurvii** [freeCodeCamp/freeCodeCamp#17742]
#### Describe your problem and - if possible - how to reproduce it
In challenge "React: Review Using Props with Stateless Functional Components", my initial solution was:

```
class Camper extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return <p>{this.props.name}</p>;
  }
}

Camper.defaultProps = {
  name: 'CamperBot',
};

Camper.propTypes = {
  name: PropTypes.string.isRequired,
};
```
And it told me:
```
The Camper component should include default props which assign the string CamperBot to the key name.
The Camper component should include prop types which require the name prop to be of type string.
```
After a few dozens of minutes, I figured out that my extra commas made it unhappy, so instead of 
```
Camper.defaultProps = {
  name: 'CamperBot',
};

Camper.propTypes = {
  name: PropTypes.string.isRequired,
};
```
I should write
```
Camper.defaultProps = {
  name: 'CamperBot'
};

Camper.propTypes = {
  name: PropTypes.string.isRequired
};
```
to make it allow me to pass.

It's probably how the judger is implemented. Not a major issue. But I was really clueless where I got wrong.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react/review-using-props-with-stateless-functional-components/

#### Tell us about your browser and operating system

My user agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by moT01** [comment]
I don't think you can use commas there

**Comment by zsoltime** [comment]
@moT01 You can use commas there and it usually is a good practice to do so. Trailing commas are great to avoid noisy `git` diffs when you add or remove a line.

**Comment by thecodingaviator** [comment]
It is considered general practice to not use commas afaik and afai have seen. Please close the issue if it answers your question, we also at FCC do not teach afaik to use trailing commas

**Comment by azurvii** [comment]
@thecodingaviator Do you have any reference for the "general practice" you mentioned?

[This feature](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas) has a long history. And in places it's supported, it's generally the recommended practice AFAIK, e.g. [Google JavaScript Style Guide](https://google.github.io/styleguide/jsguide.html#features-arrays-trailing-comma), for the reason @zsoltime has mentioned.

**Comment by thecodingaviator** [comment]
@azurvii No, I don't, I'm speaking from the code which i have seen

**Comment by ozgunbal** [comment]
I also agree to @azurvii , trailing commas should be considered by the compiler.

**Comment by imprevo** [comment]
Same. Spent 10 minutes before I realized what was "wrong"
