### ISSUE TITLE
Create Top Contributor Badge

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17749]
We recently announced our [2018 Top Contributors](https://medium.freecodecamp.org/announcing-our-freecodecamp-2018-top-contributor-award-winners-861da08a77e1).

This award is based loosely off of Quora's Top Writers award. And we want to similarly recognize freeCodeCamp's Top Contributors with a badge on their profile:

![_684_1__quincy_larson_-_quora](https://user-images.githubusercontent.com/985197/42062707-038ae25e-7af4-11e8-9b57-a6af37984bae.png)

I can think of no better icon to represent Top Contributors than [GitHub's Pull Request Icon](https://octicons.github.com/icon/git-pull-request/), which happens to be MIT licensed.

Here's what we need to do:
1. Add a Top Contributor attribute to the user object. Something like this: 
```javascript
"yearsTopContributor": [
  "2018",
  "2019"
]
```

2. Then, if a user is a Top Contributor, render the badge on their public potfolio:

![profile___freecodecamp](https://user-images.githubusercontent.com/985197/42062872-cfd5a5ba-7af4-11e8-9f3b-4ec826b0bf13.png)

Note: we will want to include just the SVG for the individual pull request icon - not the entire icon library.

**Comment by raisedadead** [comment]
> Note: we will want to include just the SVG for the individual pull request icon - not the entire icon library.

We already have the FA library available to us. No changes are necessary to the packaging.

**Comment by bgrgndzz** [comment]
I'd like to give this a try!
@raisedadead I couldn't find the pull request icon in font awesome so I will just download the icon in the link that Quincy provided and use it in the user profile.

**Comment by raisedadead** [comment]
I think we could use https://fontawesome.com/icons/trophy-alt?style=solid (we have a pro licensing for font awesome)

**Comment by bgrgndzz** [comment]
Alright, I've got nearly everything down, but I can't seem to get font awesome to work. I tried to go the traditional i tag approach, then I found the FontAwesome component in one of the files and tried that, but no luck. Can you help? @raisedadead

**Comment by raisedadead** [comment]
Yes of course. Please throw in a PR (with whatever you have), I'll be advising further on the code on that thread.

**Comment by sdabhi23** [comment]
AFAIK the new site is built using react, and there's a better approach available than using the traditional i tags. I can help out with creating the relevant react components for the same!
