### ISSUE TITLE
Incomplete Instructions for Basic JavaScript: Return a Value from a Function with Return

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/freeCodeCamp#17745]
#### Describe your problem and - if possible - how to reproduce it
The instructions instruct us to create a function timesFive but it doesn't tell us to call the function after creating it. So when anyone does the challenge they will get an error.
I think that the instructions should be modified to include all steps.
@Bouncey @raisedadead  can I make a PR on this in the curriculum repo?

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/return-a-value-from-a-function-with-return

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 67.0.3396.99
* Operating System: Windows 10 Home 1803

**Comment by Bouncey** [comment]
Issue moved to [freeCodeCamp/curriculum #73](https://github.com/freeCodeCamp/curriculum/issues/73) via [**ZenHub**](https://www.zenhub.com/)
