### ISSUE TITLE
[Quality Assurance and Testing with Chai] Example functional test failing

### ISSUE THREAD

**Issue by raditotev** [freeCodeCamp/freeCodeCamp#17744]
#### Describe your problem and - if possible - how to reproduce it
When submitting my solution for **Run Functional Tests using a Headless Browser** all tests are passing except the first one - **All tests should pass**
After inspecting the glitch logs I found out that the example test is also failing:
```
 1) Functional Tests

       e2e Testing with Zombie.js

         "Famous Italian Explorers" form

           #example - submit the input "surname" : "Polo":

     TypeError: browser.fill(...).pressButton is not a function

      at Context.<anonymous> (tests/2_functional-tests.js:217:12)
```
This is the test function from the example:
```javascript
test('#example - submit the input "surname" : "Polo"', function(done) {
        
        browser
          .fill('surname', 'Polo')
          .pressButton('submit', function(){
            // pressButton is ## Async ##.  
            // It waits for the ajax call to complete...

            // assert that status is OK 200
            browser.assert.success();
            // assert that the text inside the element 'span#name' is 'Marco'
            browser.assert.text('span#name', 'Marco');
            // assert that the text inside the element 'span#surname' is 'Polo'
            browser.assert.text('span#surname', 'Polo');
            // assert that the element(s) 'span#dates' exist and their count is 1
            browser.assert.element('span#dates', 1);

            done();   // It's an async test, so we have to call 'done()''
          });
      });
```
And this is my solution:
```javascript
test('submit "surname" : "Colombo" - write your e2e test...', function(done) {

        // fill the form...
        // then submit it pressing 'submit' button.
        //
        // in the callback...
        // assert that status is OK 200
        // assert that the text inside the element 'span#name' is 'Cristoforo'
        // assert that the text inside the element 'span#surname' is 'Colombo'
        // assert that the element(s) 'span#dates' exist and their count is 1
        browser
          .fill('surname', 'Colombo')
          .pressButton('submit', function(){
            
            /** YOUR TESTS HERE, Don't forget to remove assert.fail() **/
            
            // assert that status is OK 200
            browser.assert.success();
            // assert that the text inside the element 'span#name' is 'Cristoforo'
            browser.assert.text('span#name', 'Cristoforo');
            // assert that the text inside the element 'span#surname' is 'Colombo'
            browser.assert.text('span#surname', 'Colombo');
            // assert that the element(s) 'span#dates' exist and their count is 1
            browser.assert.element('span#dates', 1);
                        
            done();   // It's an async test, so we have to call 'done()''
          });
      });
```

#### Add a Link to the page with the problem
[Quality Assurance and Testing with Chai - Run Functional Tests using a Headless Browser](https://learn.freecodecamp.org/information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-using-a-headless-browser)

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 10

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/5617443/42031075-dd442852-7acc-11e8-960d-0cbed55baec7.png)

**Comment by raditotev** [comment]
Thanks to @moigithub the problem was identified. Tests were failing because of the Zombie version (possible change of method or functionality of pressButton).  I have changed the dependency to 4.3.0 and now everything is working fine.

**Comment by moigithub** [comment]
on version 6.2.1
.fill method doesnt return the Browser object anymore soo its not possible to do method chain

and .element method only check if the element exist
to check for "count" element, there are another method named elements (plural) which accept a count parameter

**Comment by fcoteur** [comment]
Still having the issue, even after changing the dependency to 4.3.0

**Comment by fcoteur** [comment]
Hey @raditotev, Thanks for pointing me to the error log: I have found my mistake and it is not working as expected.

I made a copy-paste mistake from previous test and actually told Zombie to test with .fill('surname', 'Colombo') in stead of .fill('surname', 'Vespucci'). The result of the test (all green but one) lead me to think that the .fill was actually not the problem, as the output was correct. My mistake!
 
![image](https://user-images.githubusercontent.com/37238217/44311422-6d389e00-a3e7-11e8-8583-a71b6b1bde3b.png)

**Comment by MarkTriesCoding** [comment]
I'm actually experiencing this issue.


`      test('submit "surname" : "Vespucci" - write your e2e test...', function(done) {
        browser
          .fill('surname', 'Vespucci')
          .pushButton('submit', function(){
              browser.assert.success();
              browser.assert.text('span#name', 'Amerigo');
              browser.assert.text('span#surname', 'Vespucci');
              browser.assert.element('span#dates', 1);



          // fill the form, and submit.
          // assert that status is OK 200
          // assert that the text inside the element 'span#name' is 'Amerigo'
          // assert that the text inside the element 'span#surname' is 'Vespucci'
          // assert that the element(s) 'span#dates' exist and their count is 1

          done();
        });
      });`

![image](https://user-images.githubusercontent.com/32316214/52025042-356a7200-24c0-11e9-965d-d43437bb4c51.png)

**Comment by rockstarcreativestudio** [comment]
I found the solution online was to not chain browser.fill and .pressButton 

`browser.fill('surname', 'Colombo')
 browser.pressButton('submit', function(){`
passes the tests in the Log and on FCC.

**Comment by jmmarsan** [comment]
https://glitch.com/edit/#!/freecodecampqualiassurancetesting

**Comment by lucasarvelo** [comment]
I try every solution, even what zombiejs recomend.
`browser.fill("surname", "Colombo")then(() => {browser.pressButton("submit", function() {
          browser.assert.success();
          browser.assert.text('span#name', "Cristoforo");
          browser.assert.text('span#surname', "Colombo");
          browser.assert.element("span#dates", 1);
          done(); // It's an async test, so we have to call 'done()''
        }));
`
Local test pass

` e2e Testing with Zombie.js
      "Famous Italian Explorers" form
        ✓ #example - submit the input "surname" : "Polo" (233ms)
        ✓ submit "surname" : "Colombo" - write your e2e test... (114ms)
        ✓ submit "surname" : "Vespucci" - write your e2e test... (110ms)
  28 passing (3s)`

but challenge test fail


`// running tests
assert that the text inside the element 'span#name' is 'Cristoforo'
assert that the text inside the element 'span#surname' is 'Colombo'
assert that the element 'span#dates' exist and its count is 1
// tests completed`

My project: https://oily-durian.glitch.me/

**Comment by lucasarvelo** [comment]
Ok, I found the problem. The test in the challenge is testing for a single quotation. 
```
- text: You should assert that the text inside the element 'span#name' is 'Cristoforo'.
    testString: getUserInput => $.get(getUserInput('url') + '/_api/get-tests?type=functional&n=4').then(data => { assert.equal(data.assertions[1].method, 'browser.text'); assert.equal(data.assertions[1].args[0], '\'span#name\''); assert.equal(data.assertions[1].args[1], '\'Cristoforo\'');}, xhr => { throw new Error(xhr.responseText); })
```
Here  > '\'span#name\'' and here > '\'Cristoforo\''

I just replace the double quotations for single quotations and the local and challenge tests pass.

**Comment by mbsyaswanth** [comment]
Replacing double quotes(") with single quotes(') passed the test cases at FreeCodeCamp for me.

**Comment by ShaunSHamilton** [comment]
I believe this can be closed, now. With the latest round of updates, I did not experience any similar issue with the latest version of Zombie.js.

@moT01  Can you confirm?
