### ISSUE TITLE
Design the curriculum page view to be more dynamic

### ISSUE THREAD

**Issue by Arronk** [freeCodeCamp/freeCodeCamp#17741]
#### Describe your problem and - if possible - how to reproduce it

I would like the curriculum page, which shows all of your completed exercises, to save the state from when you last visited the page. I find myself referring to the page quite often and if the section I have expanded is: Javascript Algorithms And Data Structures Certification (300 hours) > ES6, I would want that to be what is expanded when I next navigate to the page. 

Currently every time I navigate to that page it always reverts back to having open:
- Responsive Web Design Certification (300 hours) > Introduction to Basic HTML and HTML5

Which means I am constantly having to close that section and reopen the section I am working on. It is not a big issue but would make the user experience better for me if it was addressed.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/ 

#### Tell us about your browser and operating system

* Browser Name: 
Chrome 67

* Browser Version: 
Operating system Windows NT 10.0
Javascript enabled Yes
Cookies enabled Yes
Flash version Not installed
Java version Not installed
Websockets supported Yes
Browser size 1903 x 947
Screen size 1920 x 1080
Color depth 24 bit

* Operating System: 
Windows 10

#### If possible, add a screenshot here
![default view](https://user-images.githubusercontent.com/29160134/42009800-47095364-7acf-11e8-9130-79f462e63602.PNG)
![desired view](https://user-images.githubusercontent.com/29160134/42009802-48f3a3d2-7acf-11e8-9efd-24bcc993604c.PNG)

The desired view is effectively just representing where i am up to and where I last left the page on my previous visit that I would like to return to when I revisit the page.

**Comment by Arronk** [comment]
When using Freecodecamp this evening my issue seems to be resolved and when i go back to the curriculum page it was where I left it.

**Comment by IvandCodes** [comment]
I experience the same issue.
Currently I am working through the "Javascript Algorithms And Data Structures Certification (300 hours)"

However, whenever I open the Curriculum page, I am always showed the "HTML and HTML5" section (expected to show the Javascript section).

Cleaning cookies, logging out and in, "Empty Cache and Hard Reload" do not work.

**Comment by raisedadead** [comment]
This is something we have already in works thanks for your report. See #35421
