### ISSUE TITLE
Exercises I haven't completed are showing up as complete

### ISSUE THREAD

**Issue by zshnr** [FreeCodeCamp/FreeCodeCamp#1774]
I have my freecodecamp profile linked with github and twitter (using this same username).

I only did a few HTML exercises before jumping to JS (because I needed JS practice for a task) and now after the migration to the new servers, most of the HTML, Bootstrap, and jQuery exercises are showing up as completed on my profile, whereas I had never attempted them.

Please help me fix this. :)

Thanks!

**Comment by benmcmahon100** [comment]
Hey we're working on this right now hopefully it'll be fixed soon

**Comment by benschenker** [comment]
I'm having the same issues, where challenges I never did are marked as done and challenges I've done look like I haven't done them yet.  Please let me know if I can be of assistance
