### ISSUE TITLE
"Run The Test" button not working

### ISSUE THREAD

**Issue by Christian-Fjord** [freeCodeCamp/freeCodeCamp#17740]
#### Describe your problem and - if possible - how to reproduce it
Throughout some of the JavaScript tutorials, It won't bring up that it is running the test. It doesn't matter
if I click the button or use CTRL + Enter. Neither one seems to work on some of the lessons.

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/write-reusable-javascript-with-functions

#### Tell us about your browser and operating system

* Browser Name: Google + Firefox
* Browser Version:  Google - Chrome 67
* Operating System: Windows NT 10.0

**Comment by thearunster** [comment]
Hi @TheChristianFjord , do you see any errors in the console?

**Comment by StubRavi** [comment]
I am also facing similar problem in another challenge.

**Add a Link to the page with the problem**

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-arrow-functions-to-write-concise-anonymous-functions/

**Tell us about your browser and operating system**

- Browser Name: Google Chrome
- Browser Version: Google Chrome Version 67.0.3396.99 (Official Build) (32-bit)
- Operating System: Windows 7 SP1

**screenshots:**

![iss1](https://user-images.githubusercontent.com/34769076/42028601-55563d0e-7aea-11e8-90a2-995c15c0853e.JPG)
![iss2](https://user-images.githubusercontent.com/34769076/42028638-6bafe12c-7aea-11e8-85f4-a79c1b29fc69.JPG)
![iss3](https://user-images.githubusercontent.com/34769076/42028646-745eec32-7aea-11e8-83e5-0bacb7545d22.JPG)

**Comment by TheChristianFjord** [comment]
I checked the console and figured it out. ( I had simply misplaced an = sign) Thank you for the feedback!

**Comment by conradkay** [comment]
I think there should be an "ERROR" message at the top of the screen(or just in the test boxes) as this can be confusing and annoying.

**Comment by RandellDawson** [comment]
Closing this issue as it is not an actual problem with the challenge, but instead is a problem with the user's code.
