### ISSUE TITLE
Design Top Contributor 2018 Name Badges for parties

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17750]
We recently announced [freeCodeCamp's 2018 Top Contributors](https://medium.freecodecamp.org/announcing-our-freecodecamp-2018-top-contributor-award-winners-861da08a77e1).

We are hoping to design a nice lanyard that Top Contributors can pick up when they arrive at the party with their names on them. 

We welcome your design ideas for these lanyards. You can base them off of the [freeCodeCamp Design Style guide](https://design-style-guide.freecodecamp.org/), though we do want them to be visually interesting (and not completely minimalistic like our general design is). So illustrations are also welcome.

**Comment by renojvarghese** [comment]
Hey @QuincyLarson Here are a few ideas I came up with for an illustration. They are more like wireframes, to help demonstrate the idea.

The first scene is two hikers on a trail. One is helping the other climb a particularly large steep. It represents how freeCodeCamp contributes help programmers learn new skills through curriculum, blogs, and forums. 
![badges_hike-07](https://user-images.githubusercontent.com/24216993/42318495-38640504-801d-11e8-958c-3741292bafab.png)

The second design is a person standing proudly with a Top Contributor T-shirt, showing how he or she wears the shirt as a badge of honor.
![badges_shirt-10](https://user-images.githubusercontent.com/24216993/42318497-387bc464-801d-11e8-933e-07e85a83b2d1.png)

The final one is a few people putting together a puzzle, similar to how open source contributors helped build freeCodeCamp into what it is now.
![badges_puzzle-19](https://user-images.githubusercontent.com/24216993/42318496-386fabfc-801d-11e8-874a-e79156193c04.png)

**Comment by haydmills** [comment]
I'm interested! Any examples from around the web that you like?

Also, will the lanyard just have their name or also other info like city, state, country, job, etc?

**Comment by renojvarghese** [comment]
Hey @QuincyLarson. I haven't heard anything about this in some time. Are there any updates to the issue? 

And @haydmills. If you're interested, do you want to work on this project together? We can collaborate to get an awesome badge rolled out.

**Comment by haydmills** [comment]
@renojvarghese yeah sure let's do it! I have a few ideas in mind. I'll post them once I get some time soon.

**Comment by QuincyLarson** [comment]
@PhoeniXAbhisheK Thanks for your patience! I just saw these. Wow - thank you for creating such a wide range of designs! 

@haydmills what do you think of these designs? 

Legibility is a high priority since people need to be able to glance at these and reliably read the name. 4, 5, 9, and 11 have pretty good contrast. 

I'm partial to 11 myself, since it is colorful and festive, and has good contrast. 

I think the last name could also have a heavier font weight to further improve legibility.

**Comment by PhoeniXAbhisheK** [comment]
Something like this..???
![4](https://user-images.githubusercontent.com/16290904/43438755-74425284-94ad-11e8-82f4-68cd7255a3cd.png)

**Comment by sdabhi23** [comment]
![sample](https://user-images.githubusercontent.com/25759344/43439039-be5755ee-94ae-11e8-9093-4767a8b08e8d.png)

**Comment by QuincyLarson** [comment]
@PhoeniXAbhisheK Wow - that was fast. Yes - something like that.

@sdabhi23 Thanks for creating that. I think the monospace font is cool looking and thematically appropriate, but there's no denying that @PhoeniXAbhisheK's typography looks more aesthetically pleasing.

**Comment by PhoeniXAbhisheK** [comment]
@QuincyLarson Thanks...
Actually, I was waiting for your comments. So as soon as I got them, I made sure you don't have to wait for the changes and got to work. 😄 
Glad you liked it 🙇

**Comment by Bouncey** [comment]
I like 9 and 11 looks pretty awesome. I would love to have 8's layout but without the yellow.

I think the function call logo is important.

Thanks @PhoeniXAbhisheK for mocking these up.

@QuincyLarson Could we have different designs for each event? I would love to collect them :laughing:

**Comment by PhoeniXAbhisheK** [comment]
Hey @Bouncey thanks for the comments...
Here you go... 😸 8's layout without the yellow

![5](https://user-images.githubusercontent.com/16290904/43498370-41767792-9564-11e8-996e-46f403317606.png)

**Comment by haydmills** [comment]
@QuincyLarson I think all these designs are great explorations! Nice work everyone. 

I would say the simple black and white design that @PhoeniXAbhisheK just posted would be my vote. The typography used creates a nice visual hierarchy that should make the badge readable when hanging around someones neck. 

As mentioned, you could do the same design on the fCC green or one of the [other primary colors](https://design-style-guide.freecodecamp.org/#brand-colors).

I haven't seen anyone try illustrations yet. Any fun ideas?

**Comment by QuincyLarson** [comment]
@haydmills Thanks for sharing your opinion on this. 

@PhoeniXAbhisheK I agree - this looks solid!

**Comment by AbbeyRenn** [comment]
@QuincyLarson these are all so great! I love number 11, too. I do like the plain black one @PhoeniXAbhisheK posted most recently as well if we want something simpler/less colorful. I agree with @Bouncey that the function call logo is important.

**Comment by QuincyLarson** [comment]
@PhoeniXAbhisheK these look amazing. I think we have a winner! Could you open a pull request to add the files necessary for us to go to a print shop and print these out to https://github.com/freecodecamp/assets? 

The dimensions of our lanyard's card holders are 3.65"(Height) x 2.6"(Length) - could you make sure these match those dimensions and are as high resolution as possible for sharp printing?

**Comment by PhoeniXAbhisheK** [comment]
@QuincyLarson Sure thing... 😄 
But just to confirm, which design/color exactly..???
These latest one I posted with 4 colors, or the original black one..???

**Comment by AbbeyRenn** [comment]
@PhoeniXAbhisheK these do look amazing! I'm partial to the freeCodeCamp green, myself, but I'll let @QuincyLarson weigh in :) Thanks so much for designing these!

**Comment by KoniKodes** [comment]
I like the freeCodeCamp green as well.

**Comment by PhoeniXAbhisheK** [comment]
@QuincyLarson I've made a pull request with the necessary files, I added the files with all 5 colors, and in both designs(normal and bold fonts for last name).

**Comment by QuincyLarson** [comment]
@PhoeniXAbhisheK Thank you for all your help! I've merged your pull request!
