### ISSUE TITLE
Typo in first lesson of Managing Packages with NPM

### ISSUE THREAD

**Issue by zeuslawyer** [freeCodeCamp/freeCodeCamp#17753]
#### Describe your problem and - if possible - how to reproduce it
Minor typo  in para 1 of the first npm exercise.   it says:
'It stores information about your project just like the -section in a HTML document describes the content of a webpage. '

the '-section' should presumably should refer to something else?

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package/

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by moT01** [comment]
this is the file with the typo - https://github.com/freeCodeCamp/curriculum/blob/dev/challenges/05-apis-and-microservices/managing-packages-with-npm.json#L10

**Comment by ravikishorethella** [comment]
@moT01 @zeuslawyer Can I work on this one?

**Comment by moT01** [comment]
@ravikishorethella yes

**Comment by ravikishorethella** [comment]
@moT01 The typo is already fixed in the cloned repo. What exactly should I do?

**Comment by moT01** [comment]
I dont see it being fixed - when you run learn locally does it still show the typo? ...it's where it says `<head>-section` this in the description, the `<` and `>` probly need to be escaped - try `\<head\>`

**Comment by ravikishorethella** [comment]
Okay. Thank you @moT01

**Comment by ravikishorethella** [comment]
@moT01 Please check the submitted PR
https://github.com/freeCodeCamp/freeCodeCamp/issues/17753

**Comment by ravikishorethella** [comment]
https://github.com/freeCodeCamp/curriculum/pull/200
