### ISSUE TITLE
React exercise pass-an-array-as-props test case not passing

### ISSUE THREAD

**Issue by ranavc32** [freeCodeCamp/freeCodeCamp#17758]
Hi, 

I was facing one problem while solving the exercise ( pass-an-array-as-props ) of React here is the link, [https://learn.freecodecamp.org/front-end-libraries/react/pass-an-array-as-props](url)

I followed every steps and able to render as per requirement of test case but test case ( The List component should render the value from the tasks prop in the p tag. ) failed, Please let me know if its a bug or there is some probelem in my code, 

Here is my code 

```
const List= (props) => {
  { /* change code below this line */ }
  return <p>{props.tasks.join(',')}</p>
  { /* change code above this line */ }
};

class ToDo extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <div>
        <h1>To Do Lists</h1>
        <h2>Today</h2>
        { /* change code below this line */ }
        <List tasks={["Hello","Hi","Hihih"]}/>
        <h2>Tomorrow</h2>
        <List tasks={["Hey","There","Yo"]}/>
        { /* change code above this line */ }
      </div>
    );
  }
}
```

Cheers to FreeCodeCamp <3

**Comment by Nirajn2311** [comment]
@ranavc32 You forgot to put a space after the comma on line 3, it should be:
`
return <p>{props.tasks.join(', ')}</p>
`

**Comment by ranavc32** [comment]
@Nirajn2311 , Thanks Man :) I wasn't able to notice this small typo. Thanks a lot 👍

**Comment by AnonymousLords** [comment]
Please try and post something like this on the FCC forums and confirm it is a actual issue before here.
--> https://forum.freecodecamp.org/

**Comment by ranavc32** [comment]
@AnonymousLords , I will keep this in mind.
