### ISSUE TITLE
Color-Hex mismatch

### ISSUE THREAD

**Issue by alexbrotman** [FreeCodeCamp/FreeCodeCamp#1775]
Challenge http://freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-shades-of-gray has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The challenge text reads, "Use hex code to make a light gray. For example body { color: #111111; }." Successful completion of the challenge expects the value #111111 which is definitely a (very) dark gray, not a light gray.

**Comment by QuincyLarson** [comment]
Nice catch! I'll fix this now.
