### ISSUE TITLE
Introduction to Sass Challenges is full of bugs?

### ISSUE THREAD

**Issue by mav1283** [freeCodeCamp/freeCodeCamp#17756]
#### Describe your problem and - if possible - how to reproduce it
There seems to be a lot of bugs in the Sass Challenges, i only manage to pass problems 2 to 4 even if correct answers were submitted, 
#### Add a Link to the page with the problem
**Lesson 1:**  https://learn.freecodecamp.org/front-end-libraries/sass/store-data-with-sass-variables/
**Lesson 5:**  https://learn.freecodecamp.org/front-end-libraries/sass/use-for-to-create-a-sass-loop/
**Lesson 6:**  
https://learn.freecodecamp.org/front-end-libraries/sass/use-each-to-map-over-items-in-a-list/
**Lesson 7:**  https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while/
#### Tell us about your browser and operating system

* Browser Name: Brave
* Browser Version: Latest
* Operating System: Windows 10

#### If possible, add a screenshot here

![sass_challenge_lesson1](https://user-images.githubusercontent.com/11674969/42074491-27183f54-7b9f-11e8-89de-7cd5a6b222f2.JPG)
![sass_challenge_lesson5](https://user-images.githubusercontent.com/11674969/42074493-27569aba-7b9f-11e8-957c-c7d0bda62eba.JPG)
![sass_challenge_lesson6](https://user-images.githubusercontent.com/11674969/42074494-27946ffc-7b9f-11e8-8ee4-5aeb68721a93.JPG)
![sass_challenge_lesson7](https://user-images.githubusercontent.com/11674969/42074495-27d3baae-7b9f-11e8-819c-55fe366d6723.JPG)

**Comment by mav1283** [comment]
@vandao288 Hey i just tweeted this problem on FCC and they're working on it :)

**Comment by vandao288** [comment]
Thank you Paolo.

**Comment by marissa-cleroux** [comment]
I'm doing it them on chrome and I'm having the exact same issue! Thank-you!

**Comment by lynxlynxlynx** [comment]
This is also tracked in #12699

**Comment by Dsturge777** [comment]
I thought it was just me

**Comment by flyfishingbarbara** [comment]
it's still an issue - same prob. w the challenges list above. 
troubleshoot with randall to NO AVAIL.
brower - chrome, tried clearing cache, reseting code, different spacing, look at chrome console - it's saying syntaxerror with first opening caret of style tag.
im moving on but would like to show for it that i have the correct answers in the curriculum. 
please fix,
thanks for fixing

**Comment by mav1283** [comment]
@flyfishingbarbara  Good thing is you can still continue and get your certificate once you're done with the challenges, try following freecodecamp on twitter and dm them :)

**Comment by JohnnyBizzel** [comment]
I have done the challenges you describe, and the only one I cannot complete is the @while loop which I don't have a clue how to do yet.

**Comment by thecodingaviator** [comment]
@JohnnyBizzel add ?run=disabled in the end of the url you are referring about, that will fix it from auto running and creating an infinite loop

**Comment by thecodingaviator** [comment]
Guys, are any of you still facing any issue in any challenge.

cc: @mav1283

**Comment by mav1283** [comment]
@thecodingaviator  Everything's working except for the last one now

**Comment by thecodingaviator** [comment]
@mav1283 You mean the while loop lesson? It's been fixed but the changes have not yet been pushed to production i.e. not yet implemented on the main website. You can close the issue

**Comment by RandellDawson** [comment]
Closing this issue, because it has been fixed on the `master` branch.  The fix will be in the next production release.
