### ISSUE TITLE
Use CDN for Data Visualization projects user stories urls

### ISSUE THREAD

**Issue by tbushman** [freeCodeCamp/freeCodeCamp#17755]
#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System: 

## Choropleth Map
https://learn.freecodecamp.org/data-visualization/data-visualization-projects/visualize-data-with-a-choropleth-map/  
<img width="959" alt="screen shot 2018-06-28 at 11 27 27 pm" src="https://user-images.githubusercontent.com/7049294/42074235-4e399d20-7b28-11e8-90bc-7957c75d02ab.png">  
### Change to: 
- US Education Data: `https://cdn.freecodecamp.org/testable-projects-fcc/data/choropleth_map/for_user_education.json`  
- US County Data: `https://cdn.freecodecamp.org/testable-projects-fcc/data/choropleth_map/counties.json`  
- CDN link: `https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js`
    

## Treemap Diagram
https://learn.freecodecamp.org/data-visualization/data-visualization-projects/visualize-data-with-a-treemap-diagram/
<img width="970" alt="screen shot 2018-06-28 at 11 25 28 pm" src="https://user-images.githubusercontent.com/7049294/42074183-0ff18f46-7b28-11e8-9f5c-6f5bff7770b1.png">
### Change to: 
- Kickstarter Pledges:  `https://cdn.freecodecamp.org/testable-projects-fcc/data/tree_map/kickstarter-funding-data.json`
- Movie Sales:  `https://cdn.freecodecamp.org/testable-projects-fcc/data/tree_map/movie-data.json`
- Video Game Sales: `https://cdn.freecodecamp.org/testable-projects-fcc/data/tree_map/video-game-sales-data.json`
- CDN link: `https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js`

**Comment by tchaffee** [comment]
@raisedadead This should be simple to set up on your side, no? We have an issue that's been open for about three months that is just waiting on this to be closed. If there is anything I can do to help, please let me know.
