### ISSUE TITLE
No CORS in socket.io glitch boilerplate

### ISSUE THREAD

**Issue by Beaglefoot** [freeCodeCamp/freeCodeCamp#17757]
#### Describe your problem and - if possible - how to reproduce it
Currently you have to edit fcctesting.js to pass tests, which explicitly tells you not to do so...

>        DO NOT EDIT THIS FILE
>        For FCC testing purposes!

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/set-up-the-environment

#### Tell us about your browser and operating system
Irrelevant

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/15833833/42090878-da075eae-7bab-11e8-94e5-99d8fd57658e.png)

**Comment by raditotev** [comment]
Just to make it clear for everyone else who might come accross this problem. Add https://learn.freecodecamp.org in the allowedOrigins array in `freeCodeCamp/fcctesting.js` file.

**Comment by sidemt** [comment]
It looks like this issue still exists. I had to add `'https://www.freecodecamp.org'` to make the tests pass.

**Comment by Sky020** [comment]
I am re-working these challenges, and boilerplates to update them. Thank you, for confirming this is still an issue.
