### ISSUE TITLE
Issue with Javascript Algorithms - ES6 - use destructuring

### ISSUE THREAD

**Issue by Matthew-Burfield** [freeCodeCamp/freeCodeCamp#17764]
#### Describe your problem and - if possible - how to reproduce it
There is a type in the description. Where the text says "In the example above, the variable start is assigned..." it should say, the variable "startX"

I also found it really confusing having LOCAL_FORECAST declared in the global scope. I was using that for destructuring, instead of the variable being passed in which is technically correct. Perhaps an additional test that you're using the right variable to destructure could make it more clearer?

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-nested-objects

#### Tell us about your browser and operating system

* Browser Name: Chome
* Browser Version: 67.0.3396.99
* Operating System: MacOS

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/5549728/42114605-f1ad1c1a-7c32-11e8-8433-c076e7362b35.png)

**Comment by jounsss** [comment]
The test name "nested destructuring was used" isn't very helpful in this case when a specific variable is also tested.

**Comment by Michael-Xie** [comment]
Maybe prompts or hints would be helpful in this case.

Usually you work with what is being passed into the function, in this case, `forecast`, unless otherwise specified.

Furthermore, it tests you about function calling and what is being passed in. So for this case, 

`LOCAL_FORECAST` is passed into ``getMaxOfTmrw()`

**Comment by nathanhannig** [comment]
related issue
https://github.com/freeCodeCamp/freeCodeCamp/issues/17855

**Comment by nathanhannig** [comment]
the typo is actually
`In the example above, the variable start is assigned the value of a.start, which is also an object.`

should become
`In the example above, the variable startX is assigned the value of a.start.x.`

`start `is never defined as a variable in the example. Only `startX `and `startY `are.

**Comment by scissorsneedfoodtoo** [comment]
Fixed in https://github.com/freeCodeCamp/freeCodeCamp/pull/34935
