### ISSUE TITLE
D3: Create a Scatterplot with SVG Circles - Test is Passing But Should Fail

### ISSUE THREAD

**Issue by mtrivera** [freeCodeCamp/freeCodeCamp#17767]
#### Problem
Test is passing but it should fail. Circles are not rendered.
#### Reproduce
Insert the code below to pass test:
```javascript
// Add your code below this line
       .data(dataset)
       .enter()
       .append('circle')
// Add your code above this line
```

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/data-visualization/data-visualization-with-d3/create-a-scatterplot-with-svg-circles

#### Tell us about your browser and operating system

* Browser Name: Firefox 
* Browser Version: 61.0 (64-bit)
* Operating System: Windows 10 Pro (64-bit)

#### If possible, add a screenshot here
[![scatterplot.png](https://s15.postimg.cc/jv96u1tjv/scatterplot.png)](https://postimg.cc/image/bpr4vw5av/)

**Comment by moT01** [comment]
I just did this challenge - the code that's shown in the picture is the default code and the tests pass without the user adding any additional code, I think the default code should have the three methods (.data, .enter, .append) removed - and have a note added at the bottom of the description saying something like...
"The circles wont be visible yet, because we haven't applied any style. We will do that in the next few challenges"

**Comment by moT01** [comment]
this is the file https://github.com/freecodecamp/curriculum/blob/dev/challenges/04-data-visualization/data-visualization-with-d3.json#L1866 - it looks like the methods have already been removed from the setup code and just not on the live site yet - So we just need to add that message

**Comment by nischaldutt** [comment]
I would like to work on this, if someone else has not picked it up yet.

**Comment by sdabhi23** [comment]
![image](https://user-images.githubusercontent.com/25759344/44049530-042a998e-9f52-11e8-983f-9935b1d06f14.png)

@moT01 @nischaldutt @mtrivera looks like the issue has already been resolved!

**Comment by nischaldutt** [comment]
@sdabhi23  methods issue has been resolved but the Note below the description has not been added, as suggested by @moT01

**Comment by sdabhi23** [comment]
@nischaldutt looks like no one has taken it up, so go right ahead!
