### ISSUE TITLE
Sass: Use @for to Create a Sass Loop Test Bug

### ISSUE THREAD

**Issue by BogdanDor** [freeCodeCamp/freeCodeCamp#17762]
#### Describe your problem and - if possible - how to reproduce it
Sass: Use @for to Create a Sass Loop

Tests don't passes in Google Chrome, but pass in Firefox.
It view correct.

My code: 
<style type='text/sass'>
  @for $j from 1 to 6 {
    .text-#{$j} {font-size: 10px * $j;}
  }
</style>

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/sass/use-for-to-create-a-sass-loop/

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version:  67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 10

#### If possible, add a screenshot here

![loop](https://user-images.githubusercontent.com/5732341/42107199-256e9d98-7bdf-11e8-81fc-d96257bc5bf0.png)

**Comment by numoonchld** [comment]
SAME ISSUE BUT IN FIREFOX:


**Describe your problem and - if possible - how to reproduce it**

Sass: Use @for to Create a Sass Loop

Results in the right most column look fine - but tests don't pass. 

My code:
```
<style type='text/sass'>
  
  @for $j from 1 to 6 {
    .text-#{$j} { font-size: $j  * 10px; }
  }
  
</style>

<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>
```

**Add a Link to the page with the problem**

https://learn.freecodecamp.org/front-end-libraries/sass/use-for-to-create-a-sass-loop/
Tell us about your browser and operating system

    Browser Name: Firefox
    Browser Version: 61.0 (Quantum)
    Operating System: macOS High Sierra 10.13.5

**If possible, add a screenshot here:**

![screen shot 2018-06-30 at 4 21 58 pm](https://user-images.githubusercontent.com/17598505/42124546-125a1c3e-7c82-11e8-90e1-b2c50e6b48b0.png)

**Comment by johnkennedy9147** [comment]
@BogdanDor @numoonchld can you try this and see if you get the same behaviour I did.

1st run - 5 failing tests, all of this type `Your .text-1 class should have a font-size of 10px`
Immediately click Run tests again.
2nd run - tests pass.

**Comment by lynxlynxlynx** [comment]
Clicking furiously worked here.

**Comment by thecodingaviator** [comment]
@BogdanDor This is now working correctly, please close the issue.

![image](https://user-images.githubusercontent.com/34807532/48837187-a861b900-edaa-11e8-9be8-5c106407b3bf.png)

cc: @ezioda004

**Comment by mrmorais** [comment]
Reporting same issue after closed! It's passing on Firefox but not in Chrome

**Comment by RandellDawson** [comment]
@mrmorais Which tests are you failing?  Can you show a screenshot of the tests section?  Also, can you copy/paste (not a screen shot) your exact code and post it in the same reply?  To post code make sure there is a separate line of 3 backticks before and after the code (see below for an example).

````
```
your code goes here
your code goes here
your code goes here
```
````

**Comment by mrmorais** [comment]
Here goes the print screen on Google Chrome

![image](https://user-images.githubusercontent.com/8071409/54620628-39892980-4a45-11e9-8c05-934ad5c5cb88.png)

**Comment by thecodingaviator** [comment]
@mrmorais Please copy/paste the *exact* code as @RandellDawson has requested above!

**Comment by RandellDawson** [comment]
@mrmorais Can you share a screenshot of what it shows when you go to chrome://settings/help ?

Also, what version of operating system are you using?

**Comment by mrmorais** [comment]
![image](https://user-images.githubusercontent.com/8071409/54622840-18c2d300-4a49-11e9-8878-08a81e74ee24.png)

My exact code:

```
<style type='text/sass'>
  @for $i from 1 to 6 {
    .text-#{$i} { font-size: 10px * $i; }
  }
</style>

<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>
```

**Comment by thecodingaviator** [comment]
It passes for me:
![image](https://user-images.githubusercontent.com/34807532/54623077-d58c5280-4a90-11e9-8b1f-6c9855465cea.png)

Are you seeing anything in the console. Press `F12` to open it

**Comment by RandellDawson** [comment]
What zoom setting are you currently using?  100% should be used in case you are using something different.

**Comment by RandellDawson** [comment]
One last question.  If you open up your console the Chrome Developer Tools (Ctrl+Shift+I in Windows), then click the circled button below:
![image](https://user-images.githubusercontent.com/5313213/54624225-33398400-4a2a-11e9-8d5a-60fb4435c04f.png)
and then mouseover the first `Hello` text, what do you see?  I see the following:

![image](https://user-images.githubusercontent.com/5313213/54624393-827fb480-4a2a-11e9-9f51-449a5af2f511.png)

**Comment by mrmorais** [comment]
Well, on Element Inspector appears 14px instead 10px (the CSS inspector says 10px). The zoom is 100%.

**Comment by RandellDawson** [comment]
@mrmorais If you click `Alt` + `F`, then select 'Settings` and scroll down to `Appearance`, make sure you have `Medium (Recommended)` for `Font size`.

Also, can you following the instructions for [To further customize the font size](https://mcmw.abilitynet.org.uk/google-chrome-for-windows-making-text-larger) and take a screenshot of what your settings look like?  Mine look like below:
![image](https://user-images.githubusercontent.com/5313213/54688769-84558080-4adb-11e9-8497-203552dfeb8c.png)

**Comment by mrmorais** [comment]
It worked (:tada:) using minimum font size on "Tiny". Maybe the 10px element was smaller than the minimum accepted
