### ISSUE TITLE
Lesson not loading

### ISSUE THREAD

**Issue by sharkeydavid** [freeCodeCamp/freeCodeCamp#17768]
#### Describe your problem and - if possible - how to reproduce it
Click to open task // OR // Progress from the previous task - opens page and nav bar appears with none of the lesson details showing. Profile card in corner loading constantly.

Console:

Bundle loading error true
loader.js:136 Loading the JSON for /responsive-web-design/applied-visual-design/create-a-more-complex-shape-using-css-and-html failed

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-a-more-complex-shape-using-css-and-html/

#### Tell us about your browser and operating system

* Browser Name: Google Chrome 
* Browser Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Macbook Pro Running OS V.10.13.5

#### If possible, add a screenshot here
![screenshot 2018-06-30 02 22 53](https://user-images.githubusercontent.com/19961868/42117647-e7206eb0-7c0e-11e8-8cfa-1e7a765a8858.png)

**Comment by raisedadead** [comment]
Hi there! 👋 

Thanks for reporting, this issue. Can you please share a screenshot of the console tab on your browser's DevTools. On a macOS you can open it with  <kbd>Cmd</kbd> +  <kbd>Option</kbd> +  <kbd>I</kbd> and then click on the console Tab.

**Comment by sharkeydavid** [comment]
Hi, Issue is been resolved as I checked it this morning.

Thanks for the speedy responses all ends!!
