### ISSUE TITLE
Advanced Node and Express - How to Use Passport Strategies - Bad Test

### ISSUE THREAD

**Issue by ivan3123708** [freeCodeCamp/freeCodeCamp#17769]
#### Describe your problem and - if possible - how to reproduce it
In the above mentioned challenge, test called "A POST request to /login correctly redirects to /" always fails, despite the correct code.

I've searched for that code in the curriculum repo and found that the reason for this is poorly written test, specifically this line: ```assert.match(data, /Home page/gi``` which checks if the ```index.pug``` contains string "Home page", although it doesn't, was never being said it should and shouldn't contain that string.

The only way to pass the test is to add the string "Home page" somewhere in the ```index.pug``` file.

P.S. I would be glad to contribute but I'm not sure where to start, since the challenges files are moved to curriculum repo and no longer exist in freeCodeCamp repo, and the Contributor's Guide is therefore a bit misleading.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/how-to-use-passport-strategies

#### Tell us about your browser and operating system

*Browser Name: Google Chrome
*Browser Version: 67.0.3396.87 (Official Build) (64-bit)
*Operating System: Ubuntu 18.04 LTS

**Comment by quintessentialArmory** [comment]
I had the same issue and I solved it the same way.

**Comment by huyenltnguyen** [comment]
@ivan3123708 You can raise a PR over the curriculum repo. Here is the repo's contributing guide: https://github.com/freeCodeCamp/curriculum/blob/dev/docs/CONTRIBUTING.md

**Comment by ivan3123708** [comment]
@huyenltnguyen thanks for the answer, that's what I was looking for
