### ISSUE TITLE
Screen Readers do not report the expanded and collapsed state of headings on the Corriculum Screen

### ISSUE THREAD

**Issue by jhomme** [freeCodeCamp/freeCodeCamp#17778]
#### Describe your problem and - if possible - how to reproduce it

Initially, when the user opens the curriculum screen, the page shows headings for the big sections of the site. If you click one, it displays content under that heading. I'm guessing that visually, it shows that clicking the headings will expand the content and contract it. 

For screen readers and other people with disabilities, these headings need to be made to work with the keyboard besides working with the mouse and for screen reader users, they need to report whether they are expanded when there  is content under them and collapsed when there is not content under them. Keyboard users also need to be able to use Space or Enter to activate these. 
#### Add a Link to the page with the problem
http://learn.freecodecamp.org/

#### Tell us about your browser and operating system

* Browser Name:  Firefox
* Browser Version:  62
* Operating System:  Windows 10

**Comment by conradkay** [comment]
Thank you very much for contributing! Feel free to reach out on small issues as they would be extremely helpful for campers who have just completed the "Accessibility" portion of the curriculum.

**Comment by skpupil** [comment]
哦

**Comment by ValeraS** [comment]
Fixed #35522 https://github.com/freeCodeCamp/freeCodeCamp/pull/35522/commits/47686feadaf4de619393c8c8b7f1209e595639ee
