### ISSUE TITLE
selected text color not working - Dark mode

### ISSUE THREAD

**Issue by MonikaPatelIT** [freeCodeCamp/freeCodeCamp#17789]
#### Describe your problem and - if possible - how to reproduce it

On right side - codding panel, It doesn't change color of  selected text just for dark mode. but It does copy across selected text. It's working perfectly fine with light mode.
#### Tell us about your browser and operating system

* Browser Name: google crome
* Browser Version:  67.0.3396.99 
* Operating System: Windows 10 (64-bit)

#### If possible, add a screenshot here
--- not working on dark mode ----
![image](https://user-images.githubusercontent.com/9668906/42138351-33973fcc-7dd0-11e8-8c32-64976a1beb95.png)

--- working on light mode ---- 

![image](https://user-images.githubusercontent.com/9668906/42138347-1499ab28-7dd0-11e8-9036-92db69094f45.png)

**Comment by Night-Walker-6** [comment]
Seems everything is working know!
![captura](https://user-images.githubusercontent.com/13293218/42412233-9800c8c2-81de-11e8-8def-f426e91a645d.PNG)
All selections visible!!!

**Comment by ezioda004** [comment]
Seems like it was fixed, closing.
