### ISSUE TITLE
Basic Node and Express - Use the .env File FreeCodeCamp Challenge

### ISSUE THREAD

**Issue by JuanFran928** [freeCodeCamp/freeCodeCamp#17787]
Hello everyone, I am stuck in this challenge of FreeCodeCamp related with Apis And Microservices Certification, it doesn't work for me.

**This is the message that appears to me on the screen when I am going to pass the test:** 

_// running test
The response of "/json" does not change according to MESSAGE_STYLE
// tests completed_

**This is my code of glitch:**
let messageObject = {"message":"Hello json"};

app.get("/json", jsonHandler);

function jsonHandler(req, res){
if(process.env.MESSAGE_STYLE==='uppercase') {
messageObject.message = messageObject.message.toUpperCase()
}
return res.json(messageObject);
};

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/apis-and-microservices/basic-node-and-express/use-the--env-file/

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version:  67.0.3396.99 (64 bits)
* Operating System: Windows 10

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/38920780/42137132-fc33e236-7d5e-11e8-87e5-c5d3dbb29a68.png)

Any help?

**Comment by clandau** [comment]
I think you may just have a problem with your code as I tried it and the tests seem to be working on my end.  Can you link your glitch project or email it to me at so.super@gmail.com?  I can try to take a look and help you troubleshoot.

**Comment by clandau** [comment]
I helped Juan figure out the problem with his code and now his project is working.  This can be closed or deleted.
