### ISSUE TITLE
Typo "autoatically" on Basic HTML and HTML5: Create a Set of Radio Buttons

### ISSUE THREAD

**Issue by IvandCodes** [freeCodeCamp/freeCodeCamp#17780]
#### Describe your problem and - if possible - how to reproduce it

Basically, it's just a typo in "Basic HTML and HTML5: Create a Set of Radio Buttons" challenge. The word "autoMatically" is misspelled as "autoatically"

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-set-of-radio-buttons

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by eyeMNaughtReal** [comment]
![image](https://user-images.githubusercontent.com/13009248/42130240-0eec7c10-7cad-11e8-979f-079187b35f9a.png)

**Comment by thatnini** [comment]
This has already been fixed in [freeCodeCamp/curriculum/#48](https://github.com/freeCodeCamp/curriculum/pull/48) and should be appearing in production soon.

**Comment by mpmaan** [comment]
@IvandCodes Please close this issue.

**Comment by IvandCodes** [comment]
Thank you, everyone! The issue is closed.
