### ISSUE TITLE
Malfunctioning test in Basic CSS: Attach a Fallback value to a CSS Variable

### ISSUE THREAD

**Issue by TadashiCZ** [freeCodeCamp/freeCodeCamp#17785]
In lesson: https://learn.freecodecamp.org/responsive-web-design/basic-css/attach-a-fallback-value-to-a-css-variable student can edit just the penguin-top style without touching the penguin-bottom style and the tests are OK with that.

* Browser Name: Opera
* Browser Version: 55.0
* Operating System: Windows 10

**Comment by mpmaan** [comment]
@TadashiCZ can you provide some more detail like a screenshot or code example?

**Comment by TadashiCZ** [comment]
This code passes the tests even though I didn't change anything in the penguin-bottom class:
`.penguin-top {
    top: 10%;
    left: 25%;
  
    /* change code below */
    background: var(--penguin-skin, black);
    /* change code above */
  
    width: 50%;
    height: 45%;
    border-radius: 70% 70% 60% 60%;
  }
  
  .penguin-bottom {
    top: 40%;
    left: 23.5%;
  
    /* change code below */
    background: var(--penguin-skin);
    /* change code above */
  
    width: 53%;
    height: 45%;
    border-radius: 70% 70% 100% 100%;
  }`
Original code is like this:
`.penguin-top {
    top: 10%;
    left: 25%;
  
    /* change code below */
    background: var(--penguin-skin);
    /* change code above */
  
    width: 50%;
    height: 45%;
    border-radius: 70% 70% 60% 60%;
  }
  
  .penguin-bottom {
    top: 40%;
    left: 23.5%;
  
    /* change code below */
    background: var(--penguin-skin);
    /* change code above */
  
    width: 53%;
    height: 45%;
    border-radius: 70% 70% 100% 100%;
  }`

**Comment by mpmaan** [comment]
@TadashiCZ this issue has been fixed in [curriculum repo](https://github.com/freeCodeCamp/curriculum) in dev branch and will be merged to master branch soon.
