### ISSUE TITLE
Bug in media query challenge

### ISSUE THREAD

**Issue by RReddVar** [freeCodeCamp/freeCodeCamp#17794]
#### Describe your problem and - if possible - how to reproduce it
Following the steps and typing in the correct answer needed to pass the challenge still
gives me an error. 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/create-a-media-query

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 
* Operating System: Windows 7

#### If possible, add a screenshot here

![opera snapshot_2018-07-01_221651_learn freecodecamp org](https://user-images.githubusercontent.com/25374005/42142347-d00bc5de-7d7c-11e8-9ae2-35e1c331c6f3.png)

**Comment by alhazen1** [comment]
@RReddVar 

I just tried this challenge and it worked for me.
> Add a media query, so that the p tag has a font-size of 10px when the device's height is less than or equal to 800px.

I believe that your media query is for 800px or greater not 800px or less.

I used this for my media query and passed
```@media (max-height: 800px)```

**Comment by RReddVar** [comment]
@alhazen1 Okay, I tried it and that did work. Thank you for helping me with that! Think the developers need to fix the instructions to show that a media query for 800px and max is required, and not the opposite. :P

**Comment by alhazen1** [comment]
@RReddVar  You're very welcome. 

When you have time come back to comments and select the button to close this issue.
