### ISSUE TITLE
NOT FOUND on click  "Go to the coding curriculum"

### ISSUE THREAD

**Issue by MonikaPatelIT** [freeCodeCamp/freeCodeCamp#17790]
#### Describe your problem and - if possible - how to reproduce it
on click "Go to the coding curriculum" button on my home page redirected to this,

"NOT FOUND
You just hit a route that doesn't exist... the sadness."

#### Add a Link to the page with the problem
This issue is same as https://github.com/freeCodeCamp/freeCodeCamp/issues/17463

Trying to route from button click is:
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/generate-an-array-of-all-object-keys-with-object.keys

Working link from curriculum link is
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/generate-an-array-of-all-object-keys-with-object-keys

#### Tell us about your browser and operating system

* Browser Name: Google Chrome 
* Browser Version: 67.0.3396.99
* Operating System: Windows 10 (64 - bit)

**Comment by moT01** [comment]
this seems to be a problem for any challenge with a `.` in the title - there's at least a couple others

**Comment by nnabuihegabriel** [comment]
I don't understand

**Comment by RandellDawson** [comment]
Closing this issue, because it has been fixed on the `master` branch.  The fix will be in the next production release.
