### ISSUE TITLE
React Lifecycle: e.onNext is not a function error

### ISSUE THREAD

**Issue by skywalker212** [freeCodeCamp/freeCodeCamp#17791]
#### Describe your problem and - if possible - how to reproduce it
I am currently working on React: Optimize Re-Renders with shouldComponentUpdate and I have modified the code to pass the tests. As the challange describes, we should increment count in state and the OnlyEvens component should update only when the state count is even. I pass all the tests but when I click the button to increment the state count, the app crashes and there is this error
```
TypeError: e.onNext is not a function
    at Object.t.window.__console.log (/commons-5b4c06b8837b206dafa4.js:28)
    at OnlyEvens.componentWillReceiveProps (<anonymous>:33:24)
    at Mf (<anonymous>:76:232)
    at wh (<anonymous>:100:228)
    at kg (<anonymous>:120:88)
    at lg (<anonymous>:120:384)
    at fc (<anonymous>:127:242)
    at vb (<anonymous>:126:226)
    at ub (<anonymous>:126:61)
    at interactiveUpdates (<anonymous>:189:399)
```
I encountered the problem in few other challanges also but I simply ignored the problem until now.

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/front-end-libraries/react/optimize-re-renders-with-shouldcomponentupdate/

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Ubuntu 18.04

**Comment by jascci** [comment]
Hi,
I get the same error on **React: Manage Updates with Lifecycle Methods** exercise.  My changes pass all the tests, yet I don't see the expected outputs in the console.  I get the same error on Chrome and FF.
Chrome: Version 67.0.3396.99 
Firefox: 60.0
MacOS High Sierra

Anybody else getting the same?  If so, is it a bug in the exercises?

**Comment by ezioda004** [comment]
Fixed in https://github.com/freeCodeCamp/learn/pull/219
Closing
