### ISSUE TITLE
Avatar image distorted

### ISSUE THREAD

**Issue by abenjamin765** [freeCodeCamp/freeCodeCamp#17797]
#### Describe your problem and - if possible - how to reproduce it
The top-right avatar image gets "stretched" if a rectangular avatar is used. This is due to a min-width style applied to all images in #top-nav. 

Adding `#top-right-nav img{min-width: 0;}` should resolve the issue. 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/

#### Tell us about your browser and operating system

* Browser Name: Chrome 
* Browser Version:  67
* Operating System: macOS

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/8422137/42146868-896fd2d4-7d7f-11e8-9464-6c89d024765b.png)

**Comment by thecodingaviator** [comment]
@abenjamin765 Please provide a bigger screenshot

**Comment by chaomt** [comment]
I could work on this!

**Comment by thecodingaviator** [comment]
@ahmadabdolsaheb Do you think this can be fixed?

@chaomt I'd say that you wait to do anything on this issue till we have some inputs

**Comment by chaomt** [comment]
@thecodingaviator Sounds good.

**Comment by moT01** [comment]
I tested this on beta with a wide image and tall image and there was no distortion. Can anyone else reproduce this problem?

tested on firefox 66.0.3

**Comment by ahmadabdolsaheb** [comment]
Avatars has been removed from the navbar and the updated version will be shipped soon.
Therefore, I am closing this issue.
