### ISSUE TITLE
ES6: Use export to Reuse a Code Block - Second test fails

### ISSUE THREAD

**Issue by fr4p** [freeCodeCamp/freeCodeCamp#17796]
#### Describe your problem and - if possible - how to reproduce it

The preloaded editor code contains the statement: 

const bar= "foo";

Unless a space is inserted between bar and the assignment operator, the second objective of this challenge fails.  I believe this is related to:

https://github.com/freeCodeCamp/freeCodeCamp/issues/17666

I think the variables used in this challenge have changed and an error has been left behind.

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-export-to-reuse-a-code-block

#### Tell us about your browser and operating system

* Browser Name:  Chrome
* Browser Version: 67.0.3396.99
* Operating System: Windows 10

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/40600551/42146665-7764a91a-7e0c-11e8-8e5d-25a3a9047d98.png)

![image](https://user-images.githubusercontent.com/40600551/42146685-966051f2-7e0c-11e8-82f4-2812bf55941e.png)

**Comment by pcatana** [comment]
Yep, Happened to me too.    
Fix needed +

**Comment by mpmaan** [comment]
@fr4p this has been fixed in curriculum repo and will be merged into master branch soon. Please close this issue.

**Comment by ezioda004** [comment]
Already fixed, closing.
