### ISSUE TITLE
[UI] Settings page: Colors of toggle buttons are the other way around in night mode

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#17795]
#### Describe your problem and - if possible - how to reproduce it
On Settings page, the colors of toggle buttons are the other way around in night mode.

#### If possible, add a screenshot here
![night-mode-before](https://user-images.githubusercontent.com/25715018/42143208-30f9a314-7dde-11e8-919f-8ca0a55bc863.png)

#### Desired result
![night-mode-after](https://user-images.githubusercontent.com/25715018/42143313-a8e05f94-7dde-11e8-9de9-7c169fe48e6a.png)

#### Suggested fix
The active (ON) buttons will be dark green just like how they look in day mode, so we don't need to worry about that. We just need to change the color of the OFF buttons, give them a grey background, grey border and black text. 

```
// just for demonstration
.toggle-container {
  .btn-primary {
    background-color: #999;
    border-color: #999;
    color: #333; 
  }
}
```

**Comment by chaomt** [comment]
I could work on it.

**Comment by chaomt** [comment]
It seems this is already fixed in freeCodeCamp.rocks.

**Comment by huyenltnguyen** [comment]
@chaomt Thanks for offering the help!

I'm closing this issue as it has been resolved in beta and will be shipped to production soon.
