### ISSUE TITLE
Cascade vs Inheritance

### ISSUE THREAD

**Issue by chrisbobek** [freeCodeCamp/freeCodeCamp#17804]
#### Describe your problem and - if possible - how to reproduce it
In "Basic CSS: Cascading CSS variables", the first paragraph ends with this sentence: "This effect is known as _cascading_." However, the effect being described in the paragraph is actually an instance of inheritance.

#### Add a Link to the page with the problem
`https://learn.freecodecamp.org/responsive-web-design/basic-css/cascading-css-variables
`
#### Tell us about your browser and operating system

* Browser Name: Safari
* Browser Version: 11.1.1
* Operating System: MacOS High Sierra (Version 10.13.5)

**Comment by moT01** [comment]
@chrisbobek After reading a few articles, I can't find definitively if cascading is wrong here

**Comment by nnabuihegabriel** [comment]
I am having issues with my task here "btn btn-primary " under bootstrap
:style text input as forms control

**Comment by moT01** [comment]
@nnabuihegabriel ?

**Comment by nnabuihegabriel** [comment]
Yes

**Comment by DanCouper** [comment]
@chrisbobek Yes, it is a form of inheritence. But CSS is called CSS, not ISS, the terminology is fine.

**Comment by moT01** [comment]
Closing as stale. Feel free to reopen if you think it's still a problem. Thanks and happy coding!
