### ISSUE TITLE
React: Create a Component with Composition Failure

### ISSUE THREAD

**Issue by PizzaPokerGuy** [freeCodeCamp/freeCodeCamp#17808]
#### Describe your problem and - if possible - how to reproduce it
The code does not detect that the correct code changes were made. In a passing case it is failing.

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/front-end-libraries/react/create-a-component-with-composition 

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version:  Latest
* Operating System: Windows 10

**Comment by ndeyerl** [comment]
When I submit what I believe is the correct code for the challenge, it crashes my browser.

<ParentComponent>
  <ChildComponent />
</ParentComponent>

**Comment by 4rturKania** [comment]
It works for me.

`const ChildComponent = () => {
  return (
    <div>
      <p>I am the child</p>
    </div>
  );
};

class ParentComponent extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <div>
        <h1>I am the parent</h1>
        { /* change code below this line */ }
        <ChildComponent />
        { /* change code above this line */ }
      </div>
    );
  }
};`

**Comment by 4rturKania** [comment]
It works for me

```
const ChildComponent = () => {
  return (
    <div>
      <p>I am the child</p>
    </div>
  );
};

class ParentComponent extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <div>
        <h1>I am the parent</h1>
        { /* change code below this line */ }
        <ChildComponent />
        { /* change code above this line */ }
      </div>
    );
  }
};
```

**Comment by ezioda004** [comment]
Challenge seems to be working fine, if the bug still persists please open a new issue with details.

**Comment by CosminPugnaOSF** [comment]
using this code inside h1 tag will still crash the browser..
<ParentComponent>
     <ChildComponent>
</ ParentComponent>
