### ISSUE TITLE
Test passes when it shouldn't on "Applied Visual Design: Use the del Tag to Strikethrough Text"

### ISSUE THREAD

**Issue by Chris2Brooks** [freeCodeCamp/freeCodeCamp#17802]
#### Describe your problem and - if possible - how to reproduce it
On the "**Applied Visual Design: Use the del Tag to Strikethrough Text**" challenge there's an instruction to add _Wrap the del tag around "Google" inside the h4 tag and then add the word Alphabet beside it, which should not have the strikethrough formatting._

If you add the del tag to the Google word inside the ```<p>``` INSTEAD of the ```<h4>``` the test still passes.

Incorrect but passes:
```<h4>Google</h4>```
      ```<em><p><del>Google</del> Alphabet was founded by Larry Page and Sergey Brin while they were <u>Ph.D. students</u> at <strong>Stanford University</strong>.</p></em>```

Should pass only when the del is inside the ```<h4>```:
```<h4><del>Google</del></h4>```
     ``` <em><p>Google was founded by Larry Page and Sergey Brin while they were <u>Ph.D. students</u> at <strong>Stanford University</strong>.</p></em>```

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-del-tag-to-strikethrough-text

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: Version 67.0.3396.87 (Official Build) (64-bit)
* Operating System: macOS High Sierra 10.13.15

#### If possible, add a screenshot here

![screen shot 2018-07-02 at 11 25 37](https://user-images.githubusercontent.com/2293301/42156214-bf2e09de-7dea-11e8-84cb-ced1c1be13dd.png)

**Comment by rembrandtreyes** [comment]
@Chris2Brooks I just tried repeating this issue and it seems to not pass. In your console it also states that you must include the word Alphabet.

This is in the latests google chrome on Windows 7

![image](https://user-images.githubusercontent.com/15057964/42226875-1fe4b606-7eae-11e8-85fe-276afca578d4.png)

I believe you meant that this is incorrect but passes:
`      <h4>Google Alphabet</h4>
      <em><p><del>Google</del> was founded by Larry Page and Sergey Brin while they were <u>Ph.D. students</u> at <strong>Stanford University</strong>.</p></em>`

![image](https://user-images.githubusercontent.com/15057964/42227266-1b0cba9c-7eaf-11e8-9298-f3a7e0f36109.png)

**Comment by thecodingaviator** [comment]
@Chris2Brooks I had checked recently and this has been fixed. Please close the issue :)

**Comment by RandellDawson** [comment]
This particular challenge was rewritten to use the `s` tag and not the `del` tag, so this issue is not relevant anymore.

**Comment by marshallike** [comment]
ANSWER !!!




<style>
  h4 {
    text-align: center;
    height: 25px;
  }
  p {
    text-align: justify;
  }
  .links {
    text-align: left;
    color: black;
  }
  .fullCard {
    width: 245px;
    border: 1px solid #ccc;
    border-radius: 5px;
    margin: 10px 5px;
    padding: 4px;
  }
  .cardContent {
    padding: 10px;
  }
  .cardText {
    margin-bottom: 30px;
  }
</style>
<div class="fullCard">
  <div class="cardContent">
    <div class="cardText">
      <h4><s>Google</s>Alphabet</h4>
      <p><em>Google was founded by Larry Page and Sergey Brin while they were <u>Ph.D. students</u> at <strong>Stanford University</strong>.</em></p>
    </div>
    <div class="cardLinks">
      <a href="https://en.wikipedia.org/wiki/Larry_Page" target="_blank" class="links">Larry Page</a><br><br>
      <a href="https://en.wikipedia.org/wiki/Sergey_Brin" target="_blank" class="links">Sergey Brin</a>
    </div>
  </div>
</div>

**Comment by 13-shivam** [comment]
my answer which has run is 
 <h4><s>Google</s>Alphabet</h4> <em><p>Google was founded by Larry Page and Sergey Brin while they were <u>Ph.D. students</u> at <strong>Stanford University</strong>.</p></em>

**Comment by dwarak-cmd** [comment]
The question is to strike-through Google and not Alphabet, below is the write answer to it:
  <h4><s>Google</s>Alphabet</h4>
