### ISSUE TITLE
Web page hang on "Run the test" button within Basic Javascript For Loop

### ISSUE THREAD

**Issue by ExitSec** [freeCodeCamp/freeCodeCamp#17807]
The web page hang occurs when clicking the "Run the Test" button on the page linked below with the specified code. The page hangs until the timeout factor kicks in. This happens on both Windows Firefox and MacOS Chrome.  If it is possible I would like to try and help fix the problem with some possible direction.

```
// Example
var ourArray = [];
 
for (var i = 0; i < 10; i += 2) {
  ourArray.push(i);
}
 
// Setup
var myArray = [];
 
// Only change code below this line.
for(var i = 0; i < 10; i %2 ){
  myArray.push(i);
}
```

The problem is when a moduler of 0 is run.

#### Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/iterate-odd-numbers-with-a-for-loop/ 

#### Tell us about your browser and operating system

* Browser Name: Firefox / Chrome
* Browser Version: 61.0 (64-bit) / 67
* Operating System: Windows / MacOS High Sierra

#### If possible, add a screenshot here
![bug](https://user-images.githubusercontent.com/11134179/42182830-7806e312-7e37-11e8-8352-ba87e11a26e6.png)

**Comment by ralomach** [comment]
Hello! There is no problem, you just created an infinite for loop and that's why it's hanging. 
Try a simpler solution, like starting with i = 1, and adding i += 2 until i < 10.

**Comment by ExitSec** [comment]
Oh I totally understand, that slipped my mind! Thanks for the response.
