### ISSUE TITLE
Misspelling on /10-major-freecodecamp-improvements-that-are-live-now/

### ISSUE THREAD

**Issue by mcshakes** [freeCodeCamp/freeCodeCamp#17806]
#### Describe your problem and - if possible - how to reproduce it
Simple misspelling. Needs to be "Lightning" instead of "Lighting" 

#### Add a Link to the page with the problem
https://forum.freecodecamp.org/t/10-major-freecodecamp-improvements-that-are-live-now/192130

#### Tell us about your browser and operating system

* Browser Name: Firefox Dev Edition (Don't ask...)
* Browser Version: 61.0b12 (64-bit)
* Operating System: OSX 10.13.4 

#### If possible, add a screenshot here

![error](https://user-images.githubusercontent.com/8164007/42171815-8c62cf0c-7dd7-11e8-8878-2c51fba09bbc.png)

**Comment by Nirajn2311** [comment]
Will work on it.

**Comment by mpmaan** [comment]
@mcshakes Check #17483. Follow the instructions in the comment.

**Comment by moT01** [comment]
Thank you for reporting this issue.

    It looks like this it has been fixed so I am closing this issue.

    If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
