### ISSUE TITLE
Lack of strings to test if provided pattern cover all requirements (regex)

### ISSUE THREAD

**Issue by 9064911** [freeCodeCamp/freeCodeCamp#17819]
#### Describe your problem and - if possible - how to reproduce it
One of the RegEX challenge(share the link) specifies 3 rules. But there are not about string match test to cover/test all rules(rules 1, and 3)
Rule no.1 as following

> 1) The only numbers in the username have to be at the end. There can be zero or more of them at the end.

And Rule no.3 specifies as following:

> 3) Usernames have to be at least two characters long. A two-letter username can only use alphabet letter characters.

Correct me if I'm wrong, but it asks the camper, the RegEx pattern should not pass something like `C4`(should be failed becasue of rule 3), and something like `Porsche911R`(could be failed becasue of rule 1).

Problem is, there is no any string to test patterns strictly if rules no 1 and 3 applied, like strings provided as example above.
The expected pattern could be something like `/\D{2,}\d*/i` , but also it's possible to pass all tests with a incorrect pattern like `/\D\d*/i` or worse `/ \D\w/` (check the second link)

You may either remove the Rules 1, and 3. Or bring more string match test to make sure user specified correct match.

Thanks.

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/restrict-possible-usernames/

https://forum.freecodecamp.org/t/regex-restrict-possible-usernames/198582

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67
* Operating System: Win7

**Comment by cazyw** [comment]
Pull Request added.
