### ISSUE TITLE
Add note to text expecting quotation marks on URL on Applied Visual Design: Create Texture by Adding a Subtle Pattern as a Background Image

### ISSUE THREAD

**Issue by Chris2Brooks** [freeCodeCamp/freeCodeCamp#17810]
#### Describe your problem and - if possible - how to reproduce it
On challenge **"Applied Visual Design: Create Texture by Adding a Subtle Pattern as a Background Image"** the test expects the URL to be in between quotation marks. Using it without quotation marks does pull the image through but doesn't pass the test. The test doesn't give an indication that it's the quotation marks. Maybe adding a not to the guide that the URL should be in quotation marks will help individuals troubleshoot their errors without having to search elsewhere.

Challenge teaches: `background: url(https://i.imgur.com/MJAkxbh.png)`
Test expects the correct form of: `background: url("https://i.imgur.com/MJAkxbh.png")`

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-texture-by-adding-a-subtle-pattern-as-a-background-image

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by wudifeixue** [comment]
This part is indeed confusing, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/url) quotation marks are not necessary either. 

Here is where the source code of this challenge is:
https://github.com/freeCodeCamp/curriculum/blob/dev/challenges/01-responsive-web-design/applied-visual-design.json#L2299-L2315

**Comment by thecodingaviator** [comment]
This was fixed long ago. @Chris2Brooks please close the issue.

**Comment by RandellDawson** [comment]
Closing this issue, because it has been fixed on the `master` branch.  The fix will be in the next production release.
