### ISSUE TITLE
Passes without changing code Perform a Subset Check on Two Sets of Data

### ISSUE THREAD

**Issue by alhazen1** [freeCodeCamp/freeCodeCamp#17815]
#### Describe your problem and - if possible - how to reproduce it
This challenge can be passed without changing the code in the editor at all. Just click "Run the Test" and it passes.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/coding-interview-prep/data-structures/perform-a-subset-check-on-two-sets-of-data/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Ubuntu Linux 16.04

**Comment by cazyw** [comment]
Pull request made

**Comment by RandellDawson** [comment]
Closing this issue, because it has been fixed in beta. Viewable at https://www.freecodecamp.rocks/
