### ISSUE TITLE
ES6: Create Strings using Template Literals NEVER passes tests

### ISSUE THREAD

**Issue by smlarkin** [freeCodeCamp/freeCodeCamp#17813]
#### Describe your problem and - if possible - how to reproduce it
If you look at he form for this section, this has been going on for a while now.  Basically, someone needs to rewrite the test.  it should not require a loop or array method to make it work.  After going through the forms for an hour, I realized no one can get it to pass.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/create-strings-using-template-literals/

#### Tell us about your browser and operating system

* Browser Name:  N/A
* Browser Version: N/A
* Operating System: N/A

**Comment by scissorsneedfoodtoo** [comment]
Thanks for taking the time to report this issue, @smlarkin. You're right, it's an ongoing issue. The regex test was updated recently, though, and it should be pushed to production soon.

I'm closing this in favor of #16358.
