### ISSUE TITLE
Add info on how infinite looks like to challenge "Applied Visual Design: Animate Elements Continually Using an Infinite Animation Count"

### ISSUE THREAD

**Issue by Chris2Brooks** [freeCodeCamp/freeCodeCamp#17811]
#### Describe your problem and - if possible - how to reproduce it
On challenge **"Applied Visual Design: Animate Elements Continually Using an Infinite Animation Count"** you are to change the value of the animation iteration to infinite, however, the guide doesn't teach you what infinite looks like. Would be great if the challenge guide could be expanded to also teach how infinite is used in CSS.

Perhaps just a visual representation or note that infinite is set as `animation-iteration-count: infinite;`

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/animate-elements-continually-using-an-infinite-animation-count

**Comment by thecodingaviator** [comment]
I think changing 3 to infinite automatically explains what is happening. @Chris2Brooks please close the issue

**Comment by RandellDawson** [comment]
@Chris2Brooks I agree with @thecodingaviator that once you change the value to `infinite`, it is very clear that the ball keeps bounced forever as opposed to just 3 seconds as the challenge code starts.  

I am closing this issue, but feel free to create a pull request for the current stub article that the `Get a Hint` button links and add any relevant information you would like to see there.
