### ISSUE TITLE
Search bar overhangs editor pane in Chrome

### ISSUE THREAD

**Issue by memilanuk** [freeCodeCamp/freeCodeCamp#17814]
#### Describe your problem and - if possible - how to reproduce it
Just started FCC, and found on the very first lesson that the search bar overhangs the editor pane, to the point where it obscures the first line of code - the one students are supposed to be editing!

The problem seems consistent on subsequent pages, and regardless of zoom level (I normally run between 130-150% zoom on my laptop, as a 1920x1080p display is good for movies, but makes text really tiny ;)

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements/

#### Tell us about your browser and operating system

* Browser Name: 
Google Chrome

* Browser Version: 
v.67

* Operating System: 
Linux

#### If possible, add a screenshot here
![Google Chrome v.67](http://i.imgur.com/j3xWUmT.png)

![Firefox v.60](http://i.imgur.com/YaW83QP.png)

**Comment by thecodingaviator** [comment]
@memilanuk since this has already been fixed: 
![image](https://user-images.githubusercontent.com/34807532/47154628-73bc9680-d300-11e8-923a-4e58e63378ce.png)
please close this issue

**Comment by memilanuk** [comment]
Doesn't look fixed to me as of:

Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by thecodingaviator** [comment]
@memilanuk in that case I’m not able to replicate your problem, can you please elaborate once again?

**Comment by thecodingaviator** [comment]
> Are the screen shots in the original post not showing?

They aren't working for me probably because I have a lesser resolution. Will leave this for someone else

**Comment by QuincyLarson** [comment]
@memilanuk Could you share a screen shot of what you're seeing? I'm seeing this, which is imperfect vertical centering: 

<img width="1300" alt="front_end_libraries_projects_-_build_a_markdown_previewer___learn_freecodecamp" src="https://user-images.githubusercontent.com/985197/48669866-41dd6080-eb48-11e8-9ebd-f64c7a18dfa3.png">

**Comment by RandellDawson** [comment]
@memilanuk Can you check out the [beta site](https://www.freecodecamp.rocks/) to see if this problem still exists?  If not, please close this issue.  If it does, please let us know.

**Comment by moT01** [comment]
Closing as stale, and looks to be fixed on beta. Feel free to reopen it if there's still a problem. Thanks and happy coding!
