### ISSUE TITLE
Stock Price Checker - Internal Server Error (500)

### ISSUE THREAD

**Issue by wawraf** [freeCodeCamp/freeCodeCamp#17818]
#### Describe your problem and - if possible - how to reproduce it
I've found two issues with this project.

First - dep `https://github.com/freeCodeCamp/boilerplate-project-stockchecker` contains incorrect call in `tests/1_unit-tests.js`. It requires stockHandler.js, whilst it simply does not exist and is completely redundant in this project.

Second - after removing unnecessary code, I try to run functional tests with `NODE_ENV=test`, but for all tests I receive 500 code response from the server. API at my website works OK and I cannot find out what's the roots cause for this error.

Error/response is quite long, but if required I can paste it here :)

#### Add a Link to the page with the problem
[Glitch project](https://glitch.com/edit/#!/stock-price-checker-fcc)

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 65.0.3325.181 
* Operating System: Win10 64-bit ver.1709

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/24981380/42266795-b0e2091e-7f77-11e8-92a2-d96fd14a7781.png)

**Comment by wawraf** [comment]
One thing i found out is that, when functional test are launched, I'am receiving request headers without `x-forwarded-for`, and cannot read ip address. 

Without this piece of code:
`const ip = req.headers['x-forwarded-for'].split(',')[0]`
tests are passing, however registering ip is disabled and app is not fully functional.

**Comment by scissorsneedfoodtoo** [comment]
Closed via https://github.com/freeCodeCamp/freeCodeCamp/pull/36801
