### ISSUE TITLE
ES6: Import a Default Export

### ISSUE THREAD

**Issue by smlarkin** [freeCodeCamp/freeCodeCamp#17816]
#### Describe your problem and - if possible - how to reproduce it
This only works with "double quotes" but should work with single too;

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/import-a-default-export/

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by mpmaan** [comment]
@smlarkin this issue has been fixed in the curriculum repo which stores all the challenges though it has not been updated in the main branch. Please close this issue.

**Comment by PizzaPokerGuy** [comment]
I just came across this issue so I don't think it has been fixed yet.

**Comment by RandellDawson** [comment]
Closing this issue, because it has been fixed in beta. Viewable at https://www.freecodecamp.rocks/
