### ISSUE TITLE
Help button should assign correct categories to forum posts

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#17817]
In our old platform, clicking "ask for help" would help you create a forum post with the category "JavaScript" or "HTML-CSS" depending on what type of challenge you were solving.

We want for the new platform to do this, too.

Currently it just labels all questions with the "help" label.

![basic_html_and_html5__say_hello_to_html_elements___learn_freecodecamp_](https://user-images.githubusercontent.com/985197/42253832-42d2f384-7f09-11e8-8648-da30413c0219.png)

![the_freecodecamp_forum_](https://user-images.githubusercontent.com/985197/42253818-2600c39e-7f09-11e8-8d13-d113041e9d94.png)

**Comment by bodhish** [comment]
@QuincyLarson, i am interested in taking this up.

**Comment by jeffersonnnn** [comment]
@quincylarson totally stoked! how can i help here

**Comment by apurva5297** [comment]
i want to help

**Comment by AT1452** [comment]
@QuincyLarson Any way I could take up this issue?

**Comment by QuincyLarson** [comment]
@AT1452 @apurva5297 @jeffersonnnn  Yes - we would welcome your help with it. Could one of you dive in and tackle it, then open a pull request?
