### ISSUE TITLE
Introduction to the React Challenges - better wording

### ISSUE THREAD

**Issue by Nei-V** [freeCodeCamp/freeCodeCamp#17812]
#### Describe your problem and - if possible - how to reproduce it
I don't know if this is the place, but the text on the first page of React has some grammatical mistakes.
Also, my English is not perfect, so the text might be improved further. 

**the original text:** 
"React, popularized by Facebook, is a open-source JavaScript library for building user interfaces. With JSX, it is used to create components, handle state and props, utilize event listeners and certain life cycle methods to update data as it changes.
React combines HTML with JavaScript functionality to create its own markup language, JSX. This section will introduce you to all of these concepts and how to implement them for use with your own projects."

**the improved text:** - "an" instead of "a" and removed JSX in the first paragraph (not need as it is better explained in the second one). 
 
"React, popularized by Facebook, is _an_ open-source JavaScript library for building user interfaces. _It is used_ to create components, handle state and props, utilize event listeners and certain life cycle methods to update data as it changes. 
React combines HTML with JavaScript functionality to create its own markup language, JSX. This section will introduce you to all of these concepts and how to implement them for use with your own projects."
 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react

#### Tell us about your browser and operating system

* Browser Name: all
* Browser Version: all
* Operating System: all

**Comment by Nirajn2311** [comment]
Yeah it’s a grammar mistake, thanks for pointing it out. Any beginners are free to work on this in the curriculum repo.

**Comment by kcurtet** [comment]
I can make a pull request for this issue?

**Comment by numoonchld** [comment]
The explanation for all React lessons are overly complicated to explain simple things, and confusing. 

There are a lot of words, but after reading it, I don't understand anything. 

I am going to work through the tutorials in the original Documentation for React instead. 

Maybe React documentation providers can collab with freeCodeCamp to put up their tutorial in this section.

**Comment by KoniKodes** [comment]
Hi @Nirajn2311 ,
I'd be happy to help with this. Can you please guide me in the right direction? How do I edit the document in the the curriculum repo?

**Comment by KoniKodes** [comment]
Hi @Nirajn2311 
How do I go on the branch to begin editing the file?
It's my first time trying to do this here.
Thank you.

**Comment by Nirajn2311** [comment]
@KoniKodes have you set up a local copy of learn repo by following the steps given in [contributing.md](https://github.com/freeCodeCamp/learn/blob/master/CONTRIBUTING.md)

**Comment by KoniKodes** [comment]
@Nirajn2311 I cannot set up locally. My machine causes issues...

**Comment by randelldawson** [comment]
I just created a PR with the changes suggested by @KoniKodes.

**Comment by KoniKodes** [comment]
Thank you @randelldawson 
Is it possible to submit a pull request without having to yarn to my computer? 
I thought that I used to be able to do that...

**Comment by bannon-tanner** [comment]
This issue was fixed before the move and shows up correct in the new curriculum
[https://github.com/freeCodeCamp/learn/commit/5faf8f2f4bd66507ee791767bce983d3af2e3633](url)

**Comment by RandellDawson** [comment]
Close via PR https://github.com/freeCodeCamp/learn/pull/228
