### ISSUE TITLE
Bug on ES6: Create Strings using Template Literals

### ISSUE THREAD

**Issue by mirkocoppola80** [freeCodeCamp/freeCodeCamp#17828]
#### Describe your problem and - if possible - how to reproduce it
I write the script as below but it returns this error test and in the hint section i have a X at “Template strings were used”

I can’t figure out which is the issue

#### Add a Link to the page with the problem
const result = {
  success: ["max-length", "no-amd", "prefer-arrow-functions"],
  failure: ["no-var", "var-on-top", "linebreak"],
  skipped: ["id-blacklist", "no-dup-keys"]
};
function makeList(arr) {
  "use strict";

  // change code below this line
  const resultDisplayArray = arr.map((x) => {
    return `<li class="text-warning">${x}</li>`});
  // change code above this line

  return resultDisplayArray;
}
/**
 * makeList(result.failure) should return:
 * [ <li class="text-warning">no-var</li>,
 *   <li class="text-warning">var-on-top</li>, 
 *   <li class="text-warning">linebreak</li> ]
 **/
const resultDisplayArray = makeList(result.failure);

#### Tell us about your browser and operating system

* Browser Name: Chrome/67.0.3396.99
* Browser Version: 67.0.3396.99
* Operating System: Windows 8.1

#### If possible, add a screenshot here

![issue](https://user-images.githubusercontent.com/20482337/42361996-ed58be1e-80f9-11e8-99d8-616e2a26f2aa.png)

**Comment by scissorsneedfoodtoo** [comment]
@mirkocoppola80, thank you for taking the time to report this. You're right--this is a long standing issue that has affected many users. Like @randelldawson mentioned, it was fixed recently and that fix should hopefully be reflected on the live site soon. Please hang tight and your solution should work soon!
