### ISSUE TITLE
Use Destructuring Assignment to Assign Variables from Nested Objects

### ISSUE THREAD

**Issue by Michael-Xie** [freeCodeCamp/freeCodeCamp#17829]
#### Describe your problem and - if possible - how to reproduce it

Strict requirement for the solution, requiring only `max: maxOfTomorrow`. 
This became more of an issue when the previous lesson was equally if not more confusing to understand.

Side issue: The console messages are confusing. There are two parts:
1. When there is a syntax error or the likes, Run Tests doesn't work. First reaction was to refresh page and see if things work. So I think a message that there is a syntax error would be helpful. 
2. Error message like `nested destructuring was used` was confusing to understand. My first thought was, is this an error or not when it first appear on the console, because I usually pass in one go. Second thought was, should nested destructuring be used of not. I think better wording should be used like using 'not' to indicate what not to do.

, especially when the previous lesson was equally if not more confusing.

#### Add a Link to the page with the problem
```js

const LOCAL_FORECAST = {
  today: { min: 72, max: 83 },
  tomorrow: { min: 73.3, max: 84.6 }
};

function getMaxOfTmrw(forecast) {
  "use strict";
  // change code below this line
  const {tomorrow: {min, max:maxOfTomorrow}} = forecast; // change this line
  // change code above this line
  return maxOfTomorrow;
}

console.log(getMaxOfTmrw(LOCAL_FORECAST)); // should be 84.6
```
nested destructuring was used

#### Tell us about your browser and operating system
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36</code>.

**Link to the challenge:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-nested-objects

**Comment by baluR220** [comment]
It works this way. 
`const LOCAL_FORECAST = {
  today: { min: 72, max: 83 },
  tomorrow: { min: 73.3, max: 84.6 }
};

function getMaxOfTmrw(forecast) {
  "use strict";
  // change code below this line
  const { tomorrow : {max : maxOfTomorrow}} = forecast; // change this line
  // change code above this line
  return maxOfTomorrow;
}

console.log(getMaxOfTmrw(LOCAL_FORECAST)); // should be 84.6`

**Comment by ezioda004** [comment]
Being worked on in #34257
