### ISSUE TITLE
Can't View Certificates even though I accepted Academic Privacy Policy

### ISSUE THREAD

**Issue by rperry99** [freeCodeCamp/freeCodeCamp#17826]
#### Describe your problem and - if possible - how to reproduce it
I am trying to view my certificates and when I click the "Show Certification" button, a red bar appears at the top of the screen telling me "rperry99 has not yet agreed to our Academic Honesty Pledge." On my settings page, it shows that I have accepted the Academic Honesty Policy.

#### Add a Link to the page with the problem
[https://www.freecodecamp.org/rperry99](https://www.freecodecamp.org/rperry99)

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 67.0.3396.99
* Operating System: Windows

**Comment by thornjad** [comment]
@rperry99 are you still experiencing this issue?

**Comment by rperry99** [comment]
Sorry I didn't reply to this sooner. For some reason, it was telling me I couldn't. Anyway, No, I am not experiencing this anymore. I was able to get my certificates. I completely forgot I posted here or I would have updated it.

I am not sure what I did to fix it. I think it was an issue with the way I connected the website to github or something.

**Comment by thecodingaviator** [comment]
@rperry99 In that case, please close the issue
