### ISSUE TITLE
Invalid username or password.

### ISSUE THREAD

**Issue by Pixelshot** [FreeCodeCamp/FreeCodeCamp#1782]
Hey guys

I currently can't log in because it keeps on saying "Invalid username or password."
I know you guys are really busy at the moment with all the new changes coming in to the site. I just wanted to know whether this is a common problem or am I doing something wrong. Appreciate your feedback

Thanks and keep up the excellent work! love this site!

**Comment by QuincyLarson** [comment]
Thanks for reporting this. This is a known issue and we're hard at work fixing it. Please read: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/August-2015-Improvements
