### ISSUE TITLE
Fetch API instead of XHR API

### ISSUE THREAD

**Issue by sxnaprkhr** [freeCodeCamp/freeCodeCamp#17827]
#### Describe your problem and - if possible - how to reproduce it
Fetch API should be added to the curriculum instead of the old XMLHttpRequest() as fetch uses promises which enables a cleaner and simpler API. 

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/get-json-with-the-javascript-xmlhttprequest-method/

#### Tell us about your browser and operating system

* Browser Name: Mozilla Firefox
* Browser Version: 61.0
* Operating System: Ubuntu 18.04

**Comment by RandellDawson** [comment]
@sxnaprkhr I think having them both would be OK.  Maybe start with XMLHttpRequest and then have a second challenge afterwords introducing fetch.

**Comment by scissorsneedfoodtoo** [comment]
@sxnaprkhr, this is on the roadmap for the new version of the curriculum.

**Comment by leodaher** [comment]
@RandellDawson I would like to contribute on this issue. I could create a second challenge introducing Fetch. Is that ok?

**Comment by RandellDawson** [comment]
Like @scissorsneedfoodtoo said, it is something that will be included with the new curriculum. 

@scissorsneedfoodtoo Would it be a problem to have a stand-alone version showing fetch in the current curriculum?

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, no, it shouldn't be a problem at all! Would be good to have something until the new curriculum hits. Looking forward to seeing your new challenge @leodaher :+1: :+1:
