### ISSUE TITLE
Username Bug

### ISSUE THREAD

**Issue by vebr** [freeCodeCamp/freeCodeCamp#17824]
#### Describe your problem and - if possible - how to reproduce it
Bug username:
if you change your username with word start with 0 (or number) you will not can see your profile page

I change my username to '0x56ed' and i got this bug, so i change again to alphabetical.

#### Add a Link to the page with the problem
https://www.freecodecamp.org/0

**Comment by cacho** [comment]
** MORE INFO NEEDED **
Testing with username "5inco" :
- i couldn't repeat this bug
- the user name  "5inco" worked, i can access to the public profile properly
  - review if this only related to user names that start with a 0

**Comment by RandellDawson** [comment]
@raisedadead Any thoughts?

**Comment by raisedadead** [comment]
Is it reproducible in the next release?

**Comment by RandellDawson** [comment]
@raisedadead I just validated in the `next release` that this has been resolved.  Closing this issue now.
