### ISSUE TITLE
Advanced Node and Express 11 - Tests should be done asynchronously

### ISSUE THREAD

**Issue by lucasMontenegro** [freeCodeCamp/freeCodeCamp#17820]
So, I thought I should report something I found. My [app](https://github.com/quintessentialArmory/advanced-node2)* was being accepted/rejected at random by [this challenge](https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/registration-of-new-users/). Apparently the tests are not waiting for the server to respond and that causes them to fail (since they depend on each other).

After adding some delays to my responses the probability to pass the test increased a lot (if a timeout doesn't occur).
``` javascript
// Enable to pass the challenge called "Advanced Node and Express - 
// Registration of New Users"
if (process.env.ENABLE_DELAYS) app.use((req, res, next) => {
  switch (req.method) {
    case 'GET':
      switch (req.url) {
        case '/logout': return setTimeout(() => next(), 500);
        case '/profile': return setTimeout(() => next(), 700);
        default: next();
      }
    break;
    case 'POST':
      switch (req.url) {
        case '/login': return setTimeout(() => next(), 900);
        default: next();
      }
    break;
    default: next();
  }
});
```

\*  [Here](https://glitch.com/#!/import/github/quintessentialArmory/advanced-node2) is a link for making a new app on Glitch. (You only have to complete the .env file.)

I also had issues with some of the following challenges.

**Comment by ivan3123708** [comment]
I get tests to pass randomly, but there's always one that fails, so it's impossible to complete this challenge.

**Comment by mattszcz** [comment]
I put `ENABLE_DELAYS=true` in my .env

Tried a bunch of different delays. still not passing the Login test. Manual login of the "freeCodeCampTester" user works fine. Manual everything works. :(

**Comment by joryschmidt** [comment]
I just pasted this in above my routes and it worked like a charm, thank you!

**Comment by ededals** [comment]
I also can verify that @lucasMontenegro workaround worked.

**Comment by lxdnz254** [comment]
@lucasMontenegro Thank you very much for the tip.. The last couple of test cases have been very poor from freeCodeCamp :disappointed:

**Comment by lmichaele** [comment]
This worked, thank you!

**Comment by br3ntor** [comment]
@lucasMontenegro Worked here as well. Thank you.

**Comment by huuugh18** [comment]
Thanks so much to @lucasMontenegro for this workaround. Great job.

**Comment by tanjiarui15** [comment]
After add ENABLE_DELAYS=true to .env file and enable delay control for every route,I founded that you should do more to pass the exercise.
Now ,you should adjust delay time for each route,make sure that all request  logs are in order of tests in
[test for this exercise](https://github.com/freeCodeCamp/curriculum/blob/dev/challenges/06-information-security-and-quality-assurance/advanced-express-tools.json#L325)
first, `/register`,
second, `/login`
third, `/logout`,
fourth, ` /profile`

**Comment by h15200** [comment]
I want to thank @lucasMontenegro for the help!

Just to have it all in one place:
  1. Use Lucas's helpful glitch link 
  2. set the env ENABLE_DELAYS=true along with your other settings
  3. In my case I had to change the profile.pug line 11 to:
         h1.border.center Profile Home FCC Advanced Node and Express
 4. Clear your database
 5. Restart the server on server.js (just hit return)
 6. Run the test and pray! 

It took me a long time but it finally worked..  good luck, all!

**Comment by steven7mwesigwa** [comment]
@h15200 How do you clear the database?

**Comment by jpvajda** [comment]
I've done all of this and still can't get it to work. The login test and registration test still fail.  Here is the [code](https://glitch.com/edit/#!/fcc-advanced-node-express-jv) if anyone has any suggestions.

**Comment by jpvajda** [comment]
Just an update I finally got it working after reading this [FCC Post](https://www.freecodecamp.org/forum/t/cannot-pass-advanced-node-and-express-registration-of-new-users/306351). It was the last change I needed to make after following all these suggestions

**Comment by kainesmicheal** [comment]
that worked for me!, thankyou
