### ISSUE TITLE
link is dead in 'Basic JavaScript'

### ISSUE THREAD

**Issue by supuun** [freeCodeCamp/freeCodeCamp#17823]
#### Describe your problem and - if possible - how to reproduce it
After clicking this link - 'Storing Values with the Assignment Operator' (https://learn.freecodecamp.org/storing-values-with-the-assignment-operator), it says 'NOT FOUND You just hit a route that doesn't exist... the sadness.'

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/assignment-with-a-returned-value

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 63
* Operating System: windows 10

**Comment by Nirajn2311** [comment]
Will work on it at the curriculum repo.
