### ISSUE TITLE
bug in 'basic code solution'

### ISSUE THREAD

**Issue by jooji-san** [freeCodeCamp/freeCodeCamp#17835]
#### Describe your problem and - if possible - how to reproduce it
Here's the code:
```
function updateRecords(id, prop, value) {
  if (prop === "tracks" && value !== "") {
   if(collection<a href='https://forum.freecodecamp.com/images/emoji/emoji_one/rocket.png?v=3 ":rocket:"' target='_blank' rel='nofollow'>id][prop]) {
    collection[id][prop].push(value);
   }
   else {
    collection[id][prop]=[value];
   }
  } else if (value !== "") {
    collection[id][prop] = value;
  } else {
    delete collection[id][prop];
  }

  return collection;
}
```
I don't think `<a href='https://forum.freecodecamp.com/images/emoji/emoji_one/rocket.png?v=3 ":rocket:"' target='_blank' rel='nofollow'>` should be there in the second if statement.
#### Add a Link to the page with the problem
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-javascript/record-collection

**Comment by fantome149** [comment]
@jooji-san Kindly Close this issue as the error has been patched.
