### ISSUE TITLE
Too much advice and motivation. 

### ISSUE THREAD

**Issue by numoonchld** [freeCodeCamp/freeCodeCamp#17837]
#### Describe your problem and - if possible - how to reproduce it

The quotes that show up upon log-on are distracting and unnerving at times. 

For example, when I opened up my page to do my challenges for the day, I see this quote: 

**"There is nothing permanent except change." - Heraclitus**

I'm sure for the people with the luxury and privilege of a great philosophical mindset, it makes a lot of sense. Not to me. 

It makes me go, will I die tomorrow? will someone I know die tomorrow? will the world end tomorrow? will JS be relevant tomorrow? Is anything I do relevant? nothing is permanent, right? 

The quotes were enlightening and motivating the first few times. After that, it is just intellectual sounding mumbo-jumbo.  

So, please, please, please, stick a button to turn off these quotes somewhere.

Hopefully, these quotes aren't a permanent fixture on free code camp and will be blessed with the change of a button. 

Thank you. 

#### Add a Link to the page with the problem

https://www.freecodecamp.org/

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 61
* Operating System: 

#### If possible, add a screenshot here

![screen shot 2018-07-08 at 1 12 01 am](https://user-images.githubusercontent.com/17598505/42414104-f550a020-824b-11e8-98c1-3ab436c72b66.png)

<img width="862" alt="screen shot 2018-07-09 at 3 54 21 pm" src="https://user-images.githubusercontent.com/17598505/42445361-886c6516-8390-11e8-9c68-865b3b229ee4.png">

<img width="584" alt="screen shot 2018-07-09 at 3 56 22 pm" src="https://user-images.githubusercontent.com/17598505/42445414-aab482e8-8390-11e8-8f72-93af756192af.png">

**Comment by numoonchld** [comment]
![image](https://user-images.githubusercontent.com/17598505/42414909-b9a4299a-825d-11e8-8a02-82141b3d73e0.png)

**Comment by numoonchld** [comment]
Anytime now is a great time.

**Comment by RandellDawson** [comment]
@QuincyLarson Any thoughts on this issue?

**Comment by moT01** [comment]
Thanks for the issue. But I am closing this as stale. Feel free to open a new issue and maybe it can gain some more attention.
