### ISSUE TITLE
Challenge(s) doesn't verify proper closing tags

### ISSUE THREAD

**Issue by bjorno43** [freeCodeCamp/freeCodeCamp#17833]
#### Describe your problem and - if possible - how to reproduce it
The challenge **"Applied Accessibility: Use Headings to Show Hierarchical Relationships of Content"** (and possibly other challenges as well) doesn't verify proper tag closing.

To reproduce: Replace all `<h5>` tags with `<h3>` tags, but leave the `</h5>` tags as they are. The challenge will pass.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/use-headings-to-show-hierarchical-relationships-of-content

#### Tell us about your browser and operating system

* Browser Name: Firefox Quantum
* Browser Version: 61.0
* Operating System: Windows 7 (64 bit)

#### If possible, add a screenshot here

![afbeelding](https://user-images.githubusercontent.com/29444287/42406465-8c8e042c-81a8-11e8-98d0-19585165b106.png)

**Comment by bjorno43** [comment]
Just verified that the same issue appears in different challenges as well.

**Comment by thecodingaviator** [comment]
@Nirajn2311 I guess this could be done to other challenges if the person in question can list them

**Comment by ezioda004** [comment]
A new issue can be opened if theres bug in other challenges.
Closing this.
