### ISSUE TITLE
Wrong link to the tests for projects

### ISSUE THREAD

**Issue by guryanov-a** [freeCodeCamp/freeCodeCamp#17839]
#### Describe your problem and - if possible - how to reproduce it
Link to the bundle with the tests in the description of the projects (`https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js`) gives 

> 404: Not Found

though link in the codepen examples (`https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js`) initializes the tests on the page.

#### Add a Link to the page with the problem
1. https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-markdown-previewer
2. https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-drum-machine

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 67.0.3396.99 (Official Build) (64-bit)
* Operating System: macOS High Sierra 10.13.5

**Comment by hollloh** [comment]
i noticed this was addressed in [#416](https://github.com/freeCodeCamp/testable-projects-fcc/issues/416).
the solution to the problem (atm) is to use [this link](https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js).
(the one you mentioned that's default if you fork the codepen).
