### ISSUE TITLE
Sass challenge, font-size of 5px, where minimum could be 6px(chrome).

### ISSUE THREAD

**Issue by ghost** [freeCodeCamp/freeCodeCamp#17838]
#### Describe your problem and - if possible - how to reproduce it
Challenge needs specify CSS rules, that starts from 5px as font-size. Google chrome coems with minimum 6px for now(V67), user may not pass this test.

FF has no limit for minimum font-size, but it seems test just refresh the result page once before the test begins. So it's possible test goes before any other stuffs do things(like SASS), it's a threading race issue I think.

Suggestion: instead of 5px as start font-size, this could be 10px, or better using em unit over pixel. or better adding padding/margin instead of font-size.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while/

https://forum.freecodecamp.org/t/apply-a-style-until-a-condition-is-met-with-while-test-case-failure/206947

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67
* Operating System: Win7

**Comment by thecodingaviator** [comment]
This has been fixed in the new curriculum . Please close the issue @9064911

**Comment by moT01** [comment]
Fixed in [beta](https://www.freecodecamp.rocks/learn/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while) as mentioned, the new minimum size is 15px - so this can be closed
