### ISSUE TITLE
Accept both background-color and background shorthand properties

### ISSUE THREAD

**Issue by dakshshah96** [freeCodeCamp/freeCodeCamp#17836]
#### Describe your problem and - if possible - how to reproduce it
The "Applied Visual Design: Adjust the background-color Property of Text" does not accept if the `background` shorthand property is used even though both `background` and `background-color` have the same effect.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-background-color-property-of-text

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 67.0.3396.99 (Official Build) (64-bit)
* Operating System: macOS High Sierra

#### If possible, add a screenshot here

<img width="1280" alt="screenshot 2018-07-07 22 41 15" src="https://user-images.githubusercontent.com/7896438/42413094-e5b33c00-8236-11e8-84f6-23ca0909d807.png">

**Comment by thecodingaviator** [comment]
Please refer to the discussion on PR #34275 and close this issue. @dakshshah96

**Comment by RandellDawson** [comment]
Closing this issue, because it has been fixed in beta. Viewable at https://www.freecodecamp.rocks/
