### ISSUE TITLE
uncaughtException.r.onerror (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:1:978)

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#17831]
#### Describe your problem and - if possible - how to reproduce it
Tried running the Portfolio test bucket in codepen and noticed an uncaught exception was being produced:

   3. The navbar should always be at the top of the viewport. Error: Script error. (:0)
       at uncaughtException.r.onerror 
   (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:1:978)

#### Add a Link to the page with the problem
https://codepen.io/hbar1st/pen/RJdQyp?editors=1100

#### Tell us about your browser and operating system

* Browser Name: google chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 10

#### If possible, add a screenshot here
![2018-07-06](https://user-images.githubusercontent.com/35541470/42376183-38757c88-80ec-11e8-9e41-ca7cc874bfda.png)

**Comment by calandraz** [comment]
Hi @hbar1st! I was able to look through your issue and found that the error is telling you that the test is expecting a value, specifically a link. To fix this you just need to create a link that points to your GitHub or FCC profile within a new tab. This should get you through that error. Good Luck!

**Comment by nnabuihegabriel** [comment]
Thanks I have linked my github  account to my freecodecamp profile.
Once more thanks

**Comment by calandraz** [comment]
@hbar1st were you able to fix the navbar error? I'm currently looking through it as well

**Comment by calandraz** [comment]
@hbar1st for the navbar situation you need to have a 'fixed' position. This can be addressed within your CSS.

**Comment by hbar1st** [comment]
The uncaught exception is a problem with the fcc code. Someone should check to see if the code has a problem.

**Comment by calandraz** [comment]
@hbar1st , so when you fixed the the profile link and the added position: fixed within your css the bug persisted? I made a copy of your project and once I added in those bits the errors were resolved.

**Comment by hbar1st** [comment]
The bug did not persist when I changed the code. But again, the bug is an exception that is triggered by the code. Therefore the fix must be in the fcc side in order for the test to not fail in response to the code. Exceptions should either be caught or ignored but you cannot ask the user to change their usage to avoid a bug.

**Comment by RandellDawson** [comment]
@tbushman Any thoughts on this issue? Is this still a problem?

**Comment by tbushman** [comment]
@RandellDawson The link is no longer functioning. I wasn't aware of this, sorry. I will say that I've seen uncaught exceptions coming from student projects that get reported as such by mocha, but that's unlikely here if there are no project scripts. It would be good to have the whole code to reproduce the issue.

**Comment by RandellDawson** [comment]
@hbar1st Can you provide a link to the code which caused this issue?

**Comment by moT01** [comment]
I'm thinking we can close this. It's been pretty stale for a while apart from a trickle of activity in February. We don't have the code that produced the error and the OP is pretty much completely inactive on github... if it's a problem, hopefully someone will create a new issue around it.
