### ISSUE TITLE
August 2015 Improvements - Completion record

### ISSUE THREAD

**Issue by FreeCodeCamperAustin** [FreeCodeCamp/FreeCodeCamp#1783]
I've got quite a few modules marked the wrong way (completed/not completed).  I can't identify all as there have been some things added and removed.  One example for my account is the jQuery module.  I had completed the entire thing and was working my way through the JavaScript module when it now shows that I have barely begun the jQuery module.  It also shows that I completed angular.JS but I haven't. If there is a way for you to come back with a list of which modules I had completed I would like to get moving forward in the code camp.   Thank you!

**Comment by matejhegedus** [comment]
I have the same issue with some sections marked as completed even though I haven't touched them.
Things that I haven't started yet that are marked as completed:
- some of the Basic Front End Development Projects
- Upper Intermediate Algorithm Scripting
- Advanced Algorithm Scripting
- AngularJS
- some of the Intermediate Front End Development Projects:
- some of the Basic Front End Development Projects
- Git
- some of Node.js and Express.js

**Comment by N-kay** [comment]
[Issue has been mentioned here](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/August-2015-Improvements#the-challenge-map-is-inaccurate-regarding-my-completed-challenges):
>__The challenge map is inaccurate regarding my completed challenges__
>Your data is fine - this is merely a problem with rendering and we are working on fixing it.

I'm just wondering if we could get some kind of ETA. Just got in the mood for learning, but since they added and removed so many challenges, the wrong rendering makes it impossible to know wich I should be doing now.

**Comment by FreeCodeCamperAustin** [comment]
Thanks N-kay!  I was looking for an ETA as well.

**Comment by jasminej90** [comment]
I got the same problem too! Thanks for the update N-Kay.

**Comment by QuincyLarson** [comment]
Tanks for reporting this. This is a known issue and we're hard at work fixing it. Please read: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/August-2015-Improvements
