### ISSUE TITLE
Instructions about using a local variable without braces don't seem to work

### ISSUE THREAD

**Issue by ammarasmro** [freeCodeCamp/freeCodeCamp#17832]
#### Describe your problem and - if possible - how to reproduce it
The instructions state that since we are using a local variable we don't need to use curly braces but I tried it and it's not passing the test case unless I add the braces. This only displays the text name which makes sense so I think the instructions should be corrected.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react/render-state-in-the-user-interface-another-way

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: MacOS

#### If possible, add a screenshot here

<img width="1192" alt="screen shot 2018-07-06 at 6 55 41 pm" src="https://user-images.githubusercontent.com/22536934/42405098-36ca442e-814e-11e8-8433-700a8d005270.png">

**Comment by ayerik** [comment]
In the next paragraph it explains that in the render portion of the code you need the curly braces.  Where you don't need them us in declaring the variable.
________________________________

**Comment by ammarasmro** [comment]
You're right I guess I just missed that part but I still think that it can be rephrased to be clearer for example both statements could be mentioned together as a note

**Comment by mpmaan** [comment]
@ammarasmro I think that the current text is okay.
> Because you can write JavaScript directly in this part of the code, you don't have to **enclose this reference** in curly braces.

It is referring to the reference made by the `name` variable.
Can you suggest some better sentence for the description?

**Comment by thecodingaviator** [comment]
Yeah, the current text is okay if the student reads the full thing. Please close the issue @ammarasmro
