### ISSUE TITLE
ES6: Understand the Differences Between import and require - Bad test

### ISSUE THREAD

**Issue by jan-koupil** [freeCodeCamp/freeCodeCamp#17845]
#### Describe your problem and - if possible - how to reproduce it
An extra whitespace in the import directive prevents the challenge from passing, e.g.
`import { capitalizeString  } from "string_functions";`
#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/understand-the-differences-between-import-and-require

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
* Operating System: Windows 10

**Comment by mpmaan** [comment]
@jan-koupil where is the extra whitespace?

**Comment by mpmaan** [comment]
@jan-koupil I can fix this but I'm not sure that it should be fixed or not because it will give the wrong message that we can put unnecessary space characters anywhere in the code.

**Comment by jan-koupil** [comment]
On the other hand, this is almost undetectable error - and if you use e.g. repl.it, you see, that it works, and most languages incl. JavaScript take any number of whitespaces as one...

 Is there some kind of "hinting" - "yeah, this works, however the proper style does not recommend using more whitespace" or "Check your spacing" or something like that...

Maybe ... if you had an additional test, so one would say "OK, this works" and the other "There are not required whitespaces where they should be"

**Comment by mpmaan** [comment]
@jan-koupil that seems reasonable..i'll look into it.
