### ISSUE TITLE
ES6 challenge test failing due to case error

### ISSUE THREAD

**Issue by Philosophist** [freeCodeCamp/freeCodeCamp#17841]
#### Describe your problem and - if possible - how to reproduce it
Tests for [this es6 challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/declare-a-read-only-variable-with-the-const-keyword/) are failing due to a case error. The original code says "sentence" for the variable being tested for, but the tests are testing for "SENTENCE." Campers can get passed this challenge if they change the javascript variable to "SENTENCE," but that really isn't part of the instructions nor relevant to the lesson.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/declare-a-read-only-variable-with-the-const-keyword/

**Comment by Philosophist** [comment]
This is such a simple fix that I decided to attempt to dig for the code here to fix it myself. However, I still don't know enough to find the error in the repository. Is there any chance I could get some guidance on how this was fixed to give me insight into contributing in the future? Everywhere I sought information on how to contribute was also going the long mile of installing things to do it. Couldn't a simple typo like this be fixed right here on Github rather than having to fork and update and download a bunch of things on my own computer?

**Comment by gforce2k5** [comment]
actually the requirements do require SENTENCE to be all caps:

> Change the code so that all variables are declared using let or const. Use let when you want the variable to change, and const when you want the variable to remain constant. Also, rename variables declared with const to conform to common practices, meaning constants should be in **all caps**

**Comment by Philosophist** [comment]
Oh. My bad. I don't recall that being there before.

**Comment by gforce2k5** [comment]
It's OK, I missed it as well on my first look

**Comment by mpmaan** [comment]
@gforce2k5 I think that we should not change/update it. That would make things easier but reading the problem statement carefully is a skill that everyone should develop.
@Philosophist  Can you close this issue?

**Comment by Philosophist** [comment]
@mpmaan Sure. Sorry, I'm still unfamiliar with how to contribute on Github. Though, I would be careful with the reasoning you laid out. There are always more enriching ways to encourage attention to detail than random and unrelated side tasks that don't teach the user anything else.
