### ISSUE TITLE
Adding Fallback Value to CSS var results in no change to CSS Image

### ISSUE THREAD

**Issue by emh1010** [freeCodeCamp/freeCodeCamp#17840]
#### Describe your problem and - if possible - how to reproduce it
Basic CSS: Attach a Fallback value to a CSS Variable, when you add black as a Fallback Value to var(--penguin-skin) there is no change in the CSS Penguin image.  The last note in the exercise states "This style will be applied because of a typo in the variable name." however there is no typo in the variable name.  if I add a typo to the variable name the penguin top and bottom background change to black.
I am not sure if the intent is for the penguin background to change black or to have the user add a typo to the css var name to have the penguin background change black.  Maybe a clarification on the instructions would be helpful.  Thank you.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-css/attach-a-fallback-value-to-a-css-variable

#### Tell us about your browser and operating system

* Browser Name: Safari
* Browser Version: 
* Operating System: macOS High Sierra ver 10.13.4

#### If possible, add a screenshot here
<img width="815" alt="image" src="https://user-images.githubusercontent.com/9804005/42420622-c70afb52-8296-11e8-8be3-342d4782c38c.png">

**Comment by huyenltnguyen** [comment]
@emh1010 Thanks for reporting the issue. If I recall correctly, the variable was `--pengiun-skin`. It had a typo on purpose, as stated in the description, but probably someone overlooked and corrected it.

@moT01 I believe you are the author of this section. Can you confirm the typo thing?

**Comment by moT01** [comment]
@huyenltnguyen yes, there is supposed to be a typo in the variable name for those two classes - the way it is on the live site now is correct, I believe - but it looks like one of the tests isn't passing unless the typo is corrected
