### ISSUE TITLE
Code works but test doesn't pass - [React: Use a Ternary Expression for Conditional Rendering]

### ISSUE THREAD

**Issue by numoonchld** [freeCodeCamp/freeCodeCamp#17844]
#### Describe your problem and - if possible - how to reproduce it

Code works in the preview pane, doesn't pass test - in both Chrome and Firefox. 

I type in a number and press that button after code initializes - and I get the right text change as required by the challenge, but when I run the tests, it says I haven't met two requirements.   

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/front-end-libraries/react/use-a-ternary-expression-for-conditional-rendering

Gist of code: https://gist.github.com/numoonchld/d4034aeed58637dccb3b02aa6d4c09ae

#### Tell us about your browser and operating system

* Browser Name: Firefox 
* Browser Version: 61.0.1
* Operating System: macOS

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/17598505/42441435-ce1c9f46-8385-11e8-8568-2b09a7370820.png)

**Comment by mpmaan** [comment]
@numoonchld Your code is surely incorrect.
Try this:
1) Input 18 and click on button // correct output
2) Input 18 and click on the button again // incorrect output
In case 1, button correctly reads `Submit` before input and `You may enter` after input is submitted.
In case 2, button reads `you shall not pass` before input and `You shall not pass` after input is submitted.

**Comment by numoonchld** [comment]
Thanks - My code was wrong.
