### ISSUE TITLE
no Higher Order Functions exercise

### ISSUE THREAD

**Issue by jooji-san** [freeCodeCamp/freeCodeCamp#17849]
#### Describe your problem and - if possible - how to reproduce it
In following exercise I'm forced to write higher order arrow functions with map, filter and reduce without knowing anything about them. This is pretty weird.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/write-higher-order-arrow-functions

**Comment by jooji-san** [comment]
duplicate of #14903

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #14903, so I am closing it as a duplicate.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by ayerik** [comment]
________________________________
