### ISSUE TITLE
[BUG] Applied Visual Design, background pattern

### ISSUE THREAD

**Issue by nickmansrob** [freeCodeCamp/freeCodeCamp#17847]
#### Describe your problem and - if possible - how to reproduce it
The right solution isn't accepted. Code:
<style> body { background: url(https://i.imgur.com/MJAkxbh.png); } </style>

The preview shows the image correctly.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-texture-by-adding-a-subtle-pattern-as-a-background-image/

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 67.0.3396.99
* Operating System: Win10

#### If possible, add a screenshot here
![image 1](https://user-images.githubusercontent.com/17934406/42471051-b1581430-83bc-11e8-9e2c-4da376be85ba.png)

**Comment by gforce2k5** [comment]
you got the answer wrong, you have to enclose the url with either single quotes or double quotes
for example: 'background: url("***enter url here***")

**Comment by nickmansrob** [comment]
#ashamed ofcourse I needed the quotes, thanks!

**Comment by mpmaan** [comment]
@nickmansrob You can always ask for help/feedback on Gitter regarding challenges. Can you close this issue?

**Comment by nickmansrob** [comment]
Thx for the hint!

**Comment by joseprograms** [comment]
I think you need to add qoutation marks around the URL.
