### ISSUE TITLE
ES6: Use getters and setters, lack of tests

### ISSUE THREAD

**Issue by 9064911** [freeCodeCamp/freeCodeCamp#17842]
#### Describe your problem and - if possible - how to reproduce it
The challenge ES6: Use getters and setters to Control Access to an Object

Comes with weak tests which won't cover if user came up with all expected input.
Following code passes the result(also find the second url specified) since it's not completed
```
function makeClass() {
  "use strict";
  /* Alter code below this line */
  class Thermostat {
    
  }
  /* Alter code above this line */
  return Thermostat;
}
```
No any check/test if user added getter and setter method as syntax check, instead all by output.
#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-getters-and-setters-to-control-access-to-an-object/

https://forum.freecodecamp.org/t/some-bug-use-getters-and-setters-to-control-access-to-an-object/206283

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67
* Operating System: Win7

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #17403, so I am closing it as a duplicate.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
