### ISSUE TITLE
problem with instructions in topic: Regular Expressions: Match Characters that Occur Zero or More Times

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#17846]
#### Describe your problem and - if possible - how to reproduce it
Please review the topic titled:
Regular Expressions: Match Characters that Occur Zero or More Times

I've pasted most of the text below for convenience. The problem I see is the line that says "//Returns ["g"] which is not correct as the regular expression /go*/ will not match anything in gPhrase.

Here's the text:
==================================================================
The last challenge used the plus + sign to look for characters that occur one or more times. There's also an option that matches characters that occur zero or more times.

The character to do this is the asterisk or star: *.

let soccerWord = "gooooooooal!";
let gPhrase = "gut feeling";
let oPhrase = "over the moon";
let goRegex = /go*/;
soccerWord.match(goRegex); // Returns ["goooooooo"]
gPhrase.match(goRegex); // Returns ["g"]
oPhrase.match(goRegex); // Returns null

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/match-characters-that-occur-zero-or-more-times
#### Tell us about your browser and operating system

* Browser Name:  chrome
* Browser Version:  latest (n/a to issue)
* Operating System:  windows 10

**Comment by mpmaan** [comment]
@hbar1st It seems correct to me.
>The last challenge used the plus + sign to look for characters that occur one or more times. There's also an option that matches characters that **occur zero or more times**.

Here `goRegex = /go*/` means that match a `g` and then match an `o` after `g`. `*` only applies to the selection that precedes it which is `o`.
You can use [regexr.com](https://regexr.com) for practice.
From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp)
>For example, /bo*/ matches "boooo" in "A ghost booooed" and "b" in "A bird warbled", but nothing in "A goat grunted".

If you are satisfied, then please close this issue.

**Comment by hbar1st** [comment]
Yes you are correct. Thanks for clarifying.
