### ISSUE TITLE
Link to Technical Page Test Suite CDN is Broken

### ISSUE THREAD

**Issue by doubleUTF** [freeCodeCamp/freeCodeCamp#17848]
#### Describe your problem and - if possible - how to reproduce it
The link to the test suite is broken in the Technical Page project.

#### Add a Link to the page with the problem
[Build a Technical Documentation Page](https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-technical-documentation-page)
[Provided URL to Test Suite in above linked page](https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js)

#### Tell us about your browser and operating system

* Browser Name: Chrome 
* Browser Version: 67
* Operating System:  Win7

**Comment by ChrisBrownie55** [comment]
The development link for the test suite is broken, however, if you switch to the production version it's still working just fine.

**Comment by doubleUTF** [comment]
@ChrisBrownie55 Got it thanks, just wanted to report the fact.
