### ISSUE TITLE
Correct answer tests false on Symmetric Difference Bonfire

### ISSUE THREAD

**Issue by KokkieH** [FreeCodeCamp/FreeCodeCamp#1784]
Challenge http://www.freecodecamp.com/challenges/bonfire-symmetric-difference has an issue. 

The first test is showing as failed even though it exactly matches the expected answer. All the other tests are showing as passed. Screenshot including my solution here: http://snag.gy/G1alY.jpg

I searched the chat rooms and couldn't find anyone mentioning this problem, and there doesn't appear to be an issue reported yet on Github for this.

**Comment by QuincyLarson** [comment]
Thanks for submitting this - we'll take a look at this.

**Comment by KokkieH** [comment]
I just tried this one again, and now it accepted my answer. Yesterday it still gave an error.

**Comment by BerkeleyTrue** [comment]
Closing as resolved. Please re-open if the issue persist.
