### ISSUE TITLE
Unclear instruction for JS Replacing If Else Chains with Switch Challenge

### ISSUE THREAD

**Issue by WizardOfAus** [freeCodeCamp/freeCodeCamp#17858]
#### Describe your problem and - if possible - how to reproduce it

Two of the tests are: 
chainToSwitch("John") should be "" (empty string)
chainToSwitch(156) should be "" (empty string)

These are confusing as the question asks Change the chained if/else if statements into a switch statement and by chainToSwitch for the above two, the return needs to be specifically "" as default has been "Ate Nine".

#### Add a Link to the page with the problem

For page: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/replacing-if-else-chains-with-switch

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.87
* Operating System: OSX

#### If possible, add a screenshot here

<img width="1411" alt="screen shot 2018-07-11 at 2 34 20 pm" src="https://user-images.githubusercontent.com/9751831/42575421-5356bfaa-8518-11e8-852c-29a44cd2723d.png">

**Comment by WizardOfAus** [comment]
Proposed fix with PR

**Comment by mpmaan** [comment]
@WizardOfAus If `val` is `John` or `156` then none of the `if..else` condition will be executed and since the variable `answer` has been initialized to be an empty string then after the statement `return answer;` gets executed, an empty string will be returned.
>These are confusing as the question asks Change the chained if/else if statements into a switch statement and by chainToSwitch for the above two, the **return needs to be specifically "" as default has been "Ate Nine"**.

`Ate Nine` will be returned only if `val` is `7`. What do you mean by default here?

**Comment by mpmaan** [comment]
@WizardOfAus If everything is fine then please close this issue otherwise suggest some changes to be made because I think that the instructions are okay.

**Comment by WizardOfAus** [comment]
I think the main issue is that from the follow up of the previous challenge using the default: as a case it can get confusing. But other than that it is ok.
