### ISSUE TITLE
Misuse of word `Refactor` in FP lesson

### ISSUE THREAD

**Issue by ChrisBrownie55** [freeCodeCamp/freeCodeCamp#17853]
#### Describe your problem and - if possible - how to reproduce it
In the sentence, **"Refactor (rewrite) the code so the global array bookList is not changed inside either function,"** the use of the word "refactor" is incorrect, and should simply be replaced with "rewrite". This is because to "refactor" is:

> Code refactoring is the process of restructuring existing computer code—changing the factoring—without changing its external behavior

But in this instance, you're going from mutability to immutability which does change the external behavior, so as such, I believe that "rewrite" is a better descriptor than "refactor", which are certainly not interchangeable in this case, as per the use of _"(rewrite)"_.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/refactor-global-variables-out-of-functions

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (32-bit)
* Operating System: Chrome OS

**Comment by scwong93** [comment]
You are correct, refactor is not the right word. 

Submitted a PR to correct in the curriculum repo
https://github.com/freeCodeCamp/curriculum/pull/132

**Comment by scwong93** [comment]
You are correct, refactor is not the right word.

Submitted a PR to correct in the curriculum repo
https://github.com/freeCodeCamp/curriculum/pull/133
