### ISSUE TITLE
Data Structures challenges accept every solution - even without any code

### ISSUE THREAD

**Issue by wawraf** [freeCodeCamp/freeCodeCamp#17856]
#### Describe your problem and - if possible - how to reproduce it
Challenges are accepted despite entered code (even without any).

#### Add a Link to the page with the problem
[Data Structures: Perform an Intersection on Two Sets of Data](https://learn.freecodecamp.org/coding-interview-prep/data-structures/perform-an-intersection-on-two-sets-of-data)
[Data Structures: Perform a Difference on Two Sets of Data](https://learn.freecodecamp.org/coding-interview-prep/data-structures/perform-a-difference-on-two-sets-of-data)
[Data Structures: Perform a Subset Check on Two Sets of Data](https://learn.freecodecamp.org/coding-interview-prep/data-structures/perform-a-subset-check-on-two-sets-of-data)
[Data Structures: Create and Add to Sets in ES6](https://learn.freecodecamp.org/coding-interview-prep/data-structures/create-and-add-to-sets-in-es6)
[Data Structures: Remove items from a set in ES6](https://learn.freecodecamp.org/coding-interview-prep/data-structures/remove-items-from-a-set-in-es6)
[Data Structures: Use .has and .size on an ES6 Set](https://learn.freecodecamp.org/coding-interview-prep/data-structures/use--has-and--size-on-an-es6-set)
[Data Structures: Use Spread and Notes for ES5 Set() Integration](https://learn.freecodecamp.org/coding-interview-prep/data-structures/use-spread-and-notes-for-es5-set-integration)

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 65.0.3325.181 64bit
* Operating System: Win10 64bit

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/24981380/42561835-72e78f7a-84fa-11e8-90fe-d6bdcce4b570.png)

![image](https://user-images.githubusercontent.com/24981380/42562358-de80c656-84fb-11e8-88dc-81604218a29d.png)

**Comment by mpmaan** [comment]
@wawraf  I'll look into it.

**Comment by Tchoukoualeu** [comment]
Still the same!

**Comment by coder077** [comment]
I can take a look at this!

**Comment by RandellDawson** [comment]
Closing this issue, because it has been fixed in beta. Viewable at https://www.freecodecamp.rocks/
