### ISSUE TITLE
Function parameter not recognized when using arrow function

### ISSUE THREAD

**Issue by ChrisBrownie55** [freeCodeCamp/freeCodeCamp#17852]
### Functional Programming: Pass Arguments to Avoid External Dependence in a Function
In this lesson, I found that if you use an arrow function, the test `Your incrementer function should take a parameter.` fails, as it doesn't recognize that the function accepts parameters (probably a regex problem).

**My function:**
```
const incrementer = value => value + 1
```

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/pass-arguments-to-avoid-external-dependence-in-a-function

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (32-bit)
* Operating System: Chrome OS

#### If possible, add a screenshot here

![screenshot 2018-07-10 at 9 07 01 pm](https://user-images.githubusercontent.com/19195374/42548612-3992be9a-8485-11e8-8283-0611bab5823c.png)

**Comment by ezioda004** [comment]
Gonna take a stab at it.
