### ISSUE TITLE
Sass: Use @for to Create a Sass Loop - Doesn't accept spaces

### ISSUE THREAD

**Issue by abenjamin765** [freeCodeCamp/freeCodeCamp#17854]
#### Describe your problem and - if possible - how to reproduce it
The test will only accept:
```
@for $j from 1 through 5 {
  .text-#{$j} {font-size:10px*$j;}
} 
```
But not:
```
@for $j from 1 through 5 {
  .text-#{$j} {font-size: 10px * $j;}
} 
```
#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/sass/use-for-to-create-a-sass-loop

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: ?
* Operating System: macOS 

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/8422137/42553529-1209d7e4-8496-11e8-9199-5ea11171903e.png)

**Comment by lynxlynxlynx** [comment]
This is also tracked in #12699

**Comment by siviuki** [comment]
bro same problem

**Comment by thecodingaviator** [comment]
@abenjamin765 it works fine now. Please close the issue

**Comment by Arkcoderunner21** [comment]
Close
