### ISSUE TITLE
Lack of syntax check of ES6 shorthand functions(default code passed the test)

### ISSUE THREAD

**Issue by 9064911** [freeCodeCamp/freeCodeCamp#17857]
#### Describe your problem and - if possible - how to reproduce it
The lesson about the ES6 shorthand function, the default syntax(no shorthand function) could pass the test

Seems the test is about output rather than syntax for this one.

#### Add a Link to the page with the problem
https://forum.freecodecamp.org/t/some-bug-write-concise-declarative-functions-with-es6/207819

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/write-concise-declarative-functions-with-es6/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67
* Operating System: Win7

**Comment by mpmaan** [comment]
@9064911 Thanks for opening this issue. I'll look into it.
