### ISSUE TITLE
If i write the code for the map and send a pr will it be accepted?

### ISSUE THREAD

**Issue by JonDevOps** [freeCodeCamp/freeCodeCamp#17850]
#### Describe your problem and - if possible - how to reproduce it

I want to bring the map back. I do not like having to click the curriculum link and having to go to a seperate page to go to the previous challenge or to view previous challenges (x) amount of challenges back or forward from the challenge i am completing. I think it was quicker and more convientient without leaving the page i am on to be able to view other challenges without going to other pages, it was like a nice glossary/index . It was more convenient. So what i am asking is if i create the map dropdown and send a pr will it be accepted or will it be in vain?
#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: Current
* Operating System: Linux Mint

**Comment by JonDevOps** [comment]
I believe it was because they worked so hard on the curriculum and the fact that all the new curriculum courses were not within the map  was the reason the map was discontinued...hopefully just for the time being, until they add all the new courses to it. Just my thoughts.

**Comment by stevpalmer** [comment]
I've thought a few times now that a quicker way to get back to older lessons for a refresh would be super helpful. This sounds like something that could achieve that. You'd then be able to quickly jump back to what you where you'd progressed.

**Comment by JonDevOps** [comment]
maybe in the settings there could be a switch to turn it on and off, i wonder how we could start building that? I'm honing css at the moment but maybe in a few days or a week i will be beginning javascript. It was especially useful on phones. Maybe if we could keep the content but just put it back into that kinda menu .

**Comment by RandellDawson** [comment]
@Bouncey @raisedadead Is this something that we are interested in pursuing?

**Comment by raisedadead** [comment]
I'll defer to @QuincyLarson

**Comment by QuincyLarson** [comment]
@JonDevOps The main thing we want to do is link to the old projects associated with the legacy certifications. Once we overhaul the settings page, it will be easier to link to those projects.

I enjoyed using the old map, too, but I think we should keep looking forward. We should improve the new map rather than trying to create a "classic mode" or something like that (it would be fun but difficult to maintain as we overhaul the codebase).
