### ISSUE TITLE
My profile was completely erased!

### ISSUE THREAD

**Issue by RenaudGagne** [freeCodeCamp/freeCodeCamp#17859]
#### Describe your problem and - if possible - how to reproduce it

I had an account connected to my github account: https://freecodecamp.org/cryptoctopus
Today, I was asked to sign-in since I cleared my cache this weekend. Now ALL MY PROFILE IS GONE.

I had finished all HTML/CSS + I was halfway through JAvascript...but since I was jumping around in the module, I no longer remember where I was at.

This is infuriating.

#### Add a Link to the page with the problem

https://freecodecamp.org/cryptoctopus

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by moT01** [comment]
@RenaudGagne did your progress come back? Or is it still missing?

**Comment by raisedadead** [comment]
Hi @RenaudGagne can you please send me an email: `mrugesh at freecodecamp dot org`
