### ISSUE TITLE
UI: Public portfolio button extends beyond the visual button

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#17867]
The clickable area of the `Show me my public portfolio` button extends beyond the visual button (the red area in the screen shot is clickable)

![screen shot 2018-07-12 at 12 03 45 pm](https://user-images.githubusercontent.com/20648924/42648221-e4cd67be-85cb-11e8-8ab0-013176c1e6f6.png)

https://www.freecodecamp.org/settings

* Browser Name: firefox 
* Browser Version: 60.0.1
* Operating System: high sierra

**Comment by Nirajn2311** [comment]
I’ll look into it.
