### ISSUE TITLE
Tests pass when <strong> is used to wrap entire <p> element in challenge Applied Visual Design: Use the strong Tag to Make Text Bold

### ISSUE THREAD

**Issue by richardse08** [freeCodeCamp/freeCodeCamp#17861]
#### Describe your problem and - if possible - how to reproduce it
Tests pass when <strong> is used to wrap entire <p> element in challenge "Applied Visual Design: Use the strong Tag to Make Text Bold"

The following will pass test:
`<p><strong>Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University</strong>.</p>`
Only the following should pass test:
`<p>Google was founded by Larry Page and Sergey Brin while they were Ph.D. students at <strong>Stanford University</strong>.</p>`

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-strong-tag-to-make-text-bold

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.99
* Operating System: macOS High Sierra 10.13.5

**Comment by clrobards** [comment]
![strongtag](https://user-images.githubusercontent.com/35350251/43995704-0c4bcc28-9d81-11e8-8174-889f2b1118ca.PNG)
I can not get this to pass. I even looked up a youtube video that had the same code and it passed. The last check mark stays unchecked. But clearly, the tags are wrapped around the right word.

**Comment by huyenltnguyen** [comment]
@clrobards It will pass if you move the `<strong>` one character to the right. In other words, you will need to add a space between the word `at` and the `<strong>`, and delete the space between `<strong>` and `Stanford University`.

```
... Ph.D students at <strong>Stanford University</strong>
```

Instead of:
```
... Ph.D students at<strong> Stanford University</strong>
```

**Comment by princeabhishek** [comment]
When you try to Wrap a strong tag around "Stanford University" inside the p tag
you not able to pass the challenge.

this is because of a little mistake that is (.).

so the correct solution is 

[https://myprogmaster.blogspot.com/2018/09/wrap-strong-tag.html](url)

![applied visual design_ use the strong _ - https___learn freecodecamp org_resp-myprogmaster](https://user-images.githubusercontent.com/43085397/45251217-04966e80-b360-11e8-9b67-214c1e184c96.png)

**Comment by zellesephir** [comment]
Actually I was able to pass by removing the . and putting a space between the word "at" so that the coding line looked like this.
 at <strong>Stanford University</strong>

**Comment by papanhere** [comment]
I was also stuck for a minute, be careful with space and full stop.

<strong>Stanford University</strong>.  This is the right form.
