### ISSUE TITLE
Typo in Basic JavaScript: Understanding Uninitialized Variables

### ISSUE THREAD

**Issue by JohnFlowerBouquet** [freeCodeCamp/freeCodeCamp#17862]
There is misstatement between challenge instuctions which says:  
Initialize the three variables **a**, **b**, and **c** with **5**, **10**, and **"I am a"** respectively so that they will not be undefined.  <--- Those values are accepted.
When challenge test suite(which is incorrect) says:
a should be defined and evaluated to have the value of **6**
b should be defined and evaluated to have the value of **15**
c should not contain undefined and should have a value of **"I am a String!"**
Do not change code below the line

Link:
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/understanding-uninitialized-variables/

* Chrome
*  67.0
* Windows 8.1

**Comment by aimenbatool** [comment]
Hi @JohnFlowerBouquet, Can you please explicitly tell about the typo as I didn't find any except "the" missing before "code" in "Do not change code below the line". 

Is this to fix?

**Comment by scwong93** [comment]
I've confirmed the challenge and it is correct. You add the values 5, 10, and "I am a" to the variables a, b, and c, respectively. Below the line "Do not change code below the line", you have:
a = a + 1;
b = b + 5;
c = c + " String!";
which will then lead to the test suite results.

**Comment by JohnFlowerBouquet** [comment]
![typo](https://user-images.githubusercontent.com/38252717/42738722-d737b860-8888-11e8-9d86-19157e179b8e.jpg)

Correct me if I'm wrong but I understand that both underlined tips sections to this task should indicate the same values?
This is silly little typo but im kinda pedant :)

**Comment by VictoryShoe** [comment]
Well the tests are:
```
a = a + 1;
b = b + 5;
c = c + " String!";
```
So the results are correct but the wording is confusing.
I could change it to something like:
"`a` should be defined and `a + 1` should evaluate to `6`"
