### ISSUE TITLE
"Update my Email" button does not do anything

### ISSUE THREAD

**Issue by real-MaRs** [freeCodeCamp/freeCodeCamp#17863]
#### Describe your problem and - if possible - how to reproduce it
Enter valid and matching email and press "Update my Email"

#### Add a Link to the page with the problem
https://www.freecodecamp.org/settings/update-email

#### Tell us about your browser and operating system
Google Chrome
67.0.3396.99
Windows 7

**Comment by LBWright** [comment]
Bug repeatable. I'll see what I can solve this weekend.

**Comment by thecodingaviator** [comment]
@LBWright any progress?

**Comment by LBWright** [comment]
@thecodingaviator I think I made the PR months ago.

**Comment by RandellDawson** [comment]
@LBWright What is the PR # you created for this issue?

**Comment by thecodingaviator** [comment]
@RandellDawson I see only one PR #17100 made by @LBWright over on this repo

**Comment by icatat** [comment]
I am able to change my e-mail from my Settings page. How do you get to that settings/update-email page?
