### ISSUE TITLE
CSS Variables - incorrect wording on clues

### ISSUE THREAD

**Issue by dlmvad** [freeCodeCamp/freeCodeCamp#17860]
#### Describe your problem and - if possible - how to reproduce it
The wording of the clues on the CSS Variable page is incorrect

**what it says:** 
penguin class should declare the **--penguin-skin** variable and assign it to gray.
penguin class should declare the **--penguin-skin** variable and assign it to white.
penguin class should declare the -**-penguin-skin** variable and assign it to orange.

**what it should say:**
penguin class should declare the --penguin-skin variable and assign it to gray.
penguin class should declare the --penguin-belly variable and assign it to white.
penguin class should declare the --penguin-beak variable and assign it to orange.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-variables-to-change-several-elements-at-once

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: version 61.0.1 (64 bit)
* Operating System: Windows 10

#### If possible, add a screenshot here
![screenshot_2018-07-11 basic css use css variables to change several elements at once learn freecodecamp](https://user-images.githubusercontent.com/5862100/42577293-f1341bca-851b-11e8-8636-043a0b6ea979.png)

**Comment by dlmvad** [comment]
I'm happy to do this small change

**Comment by mpmaan** [comment]
@dlmvad Thanks for being willing to contribute. However, this issue has been fixed in the *dev* branch of [curriculum repo](https://github.com/freeCodeCamp/curriculum) and will be merged to the *master* branch soon.
You can try to fix other issues.
Please close this issue.

**Comment by dlmvad** [comment]
@mpmaan thank you!
