### ISSUE TITLE
CSS Flexbox: Add Flex .follow-btn ISSUE 

### ISSUE THREAD

**Issue by kuhlekt1v** [freeCodeCamp/freeCodeCamp#17868]
#### Describe your problem and - if possible - how to reproduce it
The CSS Flexbox: Add Flex Superpowers to the Tweet Embed lesson will not pass. Specifically there is an issue with the .follow-btn test.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/css-flexbox/add-flex-superpowers-to-the-tweet-embed

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version:  67.0.3396.99  
* Operating System: Windows 7

#### If possible, add a screenshot here

![flexbox-issue](https://user-images.githubusercontent.com/37758062/42665322-1fa3ead4-860d-11e8-84ba-11c90bbb01d2.JPG)

**Comment by HadrienAllemon** [comment]
It's working on my end with windows 10 and chrome. Could you try again and paste the whole code ?

**Comment by kuhlekt1v** [comment]
Thanks for looking into it for me. I actually got it to run as well  simply by closing the browser and reopening it.
