### ISSUE TITLE
Constructor function not explained before ES6

### ISSUE THREAD

**Issue by jooji-san** [freeCodeCamp/freeCodeCamp#17865]
#### Describe your problem and - if possible - how to reproduce it
'ES6: Use class Syntax to Define a Constructor Function' talks about class syntax without we knowing anything about constructor functions, but I think, it's important to know about constructor functions first.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-class-syntax-to-define-a-constructor-function

**Comment by lynxlynxlynx** [comment]
It's just mentioned as an aside, but sure, it couldn't hurt to have a separate challenge somewhere.

**Comment by ezioda004** [comment]
We have function constructor challenges in OOP section. I suppose we can add a note saying where they could learn more about it?

**Comment by RandellDawson** [comment]
@ezioda004 Sounds like a plan.

**Comment by hilliarj** [comment]
@RandellDawson I want to work on this
