### ISSUE TITLE
Won't run tests

### ISSUE THREAD

**Issue by ghost** [freeCodeCamp/freeCodeCamp#17873]
#### 
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements

#### 

* Browser Name: Google Chrome
* Browser Version: Chrome 67
* Operating System: Windows NT 10.0

#### 
![image](https://user-images.githubusercontent.com/41130963/42700553-1bd3cef8-8692-11e8-8e3e-e1fc92bd6881.png)

**Comment by Nirajn2311** [comment]
I just checked it and it is working in safari iPad.

**Comment by zxjq** [comment]
Well, it's not working for me. Do you have any suggestions?

**Comment by zxjq** [comment]
There were in fact three error messages.
![image](https://user-images.githubusercontent.com/41130963/42716162-30f9cce8-86c8-11e8-9891-c373e9808e96.png)
I hope this helps you figure out the problem.

**Comment by zxjq** [comment]
I'm not sure what that means. JavaScript is allowed on my browser, although I believe that is not what you were referring to. Also, it still doesn't work with incognito mode.

**Comment by Nirajn2311** [comment]
@zxjq could you post a list of your browser addons and extensions.

**Comment by zxjq** [comment]
I'd rather not. Why?

**Comment by joker314** [comment]
@zxjq They think one of them might be interfering with freeCodeCamp.

Instead, could you, by method of binary search, determine whether an extension is the problem.

Disable all of your extensions. If that solves it, proceed with the below. If not, let us know.

CURRENT means all your extensions.

1. Disable half of CURRENT. Did that solve it? (***yes***: step 2, ***no***: step 3)
2. CURRENT is now the half you just disabled (***go to**: step 4)
3. CURRENT is now the half you didn't just disable (**go to**: step 4)
4. Is CURRENT only one extension? (***yes***: That's the faulty extension! ***no***: step 1)

**Comment by Nirajn2311** [comment]
@joker314 nice method, almost like a binary search.

**Comment by zxjq** [comment]
I disabled all of my extensions but it didn't work.
I still got this when I clicked Control-Shift-J.
![image](https://user-images.githubusercontent.com/41130963/42736745-2d5978d2-8839-11e8-9b1e-5bd48fe3bedd.png)

**Comment by joker314** [comment]
Interesting. Could you try to navigate to the grey links in the error messages?

If you get a warning about HTTPS not being secure, let us know.

But also, could you hit the padlock in the top left, and tell us which method of encryption it uses? (Or screenshot the entire thing)

**Comment by zxjq** [comment]
I am unable to copy an image of the expanded info (whenever I open the snipping tool it collapses again), but all it says is, "Your connection to this site is not secure..."

**Comment by zxjq** [comment]
In case it helps, although I doubt it will, here is the most recent set of errors that appear in the console.
![image](https://user-images.githubusercontent.com/41130963/42820538-6bbced18-89a4-11e8-8e59-8c2a937e09d7.png)

**Comment by zxjq** [comment]
There is no actual picture of a padlock. In its place is a red danger sign with the words "Not secure." The site I am on is the https one.

**Comment by joker314** [comment]
I am interested in the certificate: which encryption algorithm is being used?

**Comment by MaXFalstein** [comment]
All of the links appearing to have caused errors a no longer in the code for this task.
I get zero console errors in Ghost Browser 2.1.0.2 on macOS 10.13.6.

**Comment by joker314** [comment]
In which case, could @ghost try -- as well as determining the cryptographic algorithm those links are using -- press `Shift + Reload`?

**Comment by huyenltnguyen** [comment]
It looks like OP deleted their account. So... I think this issue can be closed then?

**Comment by joker314** [comment]
If they can't provide us with any additional information because their account is deleted, I suppose so. Let's wait a bit to confirm OP is no longer suffering from the issue.

**Comment by huyenltnguyen** [comment]
I'm closing this issue as it has gone stale and the OP deleted their account.
