### ISSUE TITLE
ES6 Proxies

### ISSUE THREAD

**Issue by Flarp** [freeCodeCamp/freeCodeCamp#17878]
#### Describe your problem and - if possible - how to reproduce it

The current ES6 curriculum covers how to implement getters and setters on ES6 classes, but not actual objects using [Proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy). I can't work on this now, I'm already tied up with generators and iterators, but it came to me while I was writing a lesson. 

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-getters-and-setters-to-control-access-to-an-object

#### Tell us about your browser and operating system

# all

#### If possible, add a screenshot here

Another tiny nit pick

![image](https://user-images.githubusercontent.com/11673881/42725840-a58fcb1c-8758-11e8-8a1f-deedadbca32b.png)

# is this seriously live

**Comment by Flarp** [comment]
@thornjad I've grown up now and realized that ES6 Proxies were probably a mistake, having an identical object property notation but possibly not being O(1) is dangerous

**Comment by RandellDawson** [comment]
As there has been no discussion on this issue and reading your last reply, it seems fine to close.  

Feel free to request this issue to be reopened if you still feel this is an issue.

Thank you.
