### ISSUE TITLE
Should we warn users after opening the developer console not to paste any text?

### ISSUE THREAD

**Issue by joker314** [freeCodeCamp/freeCodeCamp#17874]
#### Describe your problem and - if possible - how to reproduce it
This is a question, a little bit related to security. Other services, such as Discord and Facebook, create warning messages to deter users from needlessly pasting malicious content into their developer console -- which has full access to the current webpage's cookies. 

Do we want to follow this pattern, and add our own? 

This is done by [styling content in the console](https://developer.mozilla.org/en-US/docs/Web/API/console#Styling_console_output) to make it big, red, and noticeable.

Special care must be taken for Internet Explorer, where a `console` object is only formed once the console is opened, and the styling is not supported. Therefore, IE must be detected, and alternative ways of conveying the danger of the console must be utilised. For example, `console.warn` can be used -- or just the standard `console.log`. Microsoft Edge does not support the styling either. Given these obstacles, is it worth doing this? Will it protect users? Discuss!

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/18113170/42712268-e16b3a0c-86e2-11e8-8117-6b5cd0191ea9.png)

Image credits: Discord console

**Comment by thecodingaviator** [comment]
@QuincyLarson / @Bouncey , I think we should add this feature but I'm not really sure why someone would want to hack into my FCC account

**Comment by QuincyLarson** [comment]
@joker314 No - I don't think we need to worry about this. Facebook and other broad consumer websites may have things like this, but I agree with @thornjad that we aren't much of a target, and wouldn't have much data even if someone was able to trick someone into pasting something into their console.
