### ISSUE TITLE
Waypoint: Modify Array Data With Indexes

### ISSUE THREAD

**Issue by hansinla** [FreeCodeCamp/FreeCodeCamp#1787]
Challenge http://www.freecodecamp.com/challenges/waypoint-modify-array-data-with-indexes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Task says: Now modify the data stored at index 0 of myArray to the value of 3.

```
var ourArray = [1,2,3];
ourArray[1] = 3;
// ourArray[1] now equals [1,3,3].
var myArray = [1,2,3];
// Only change code below this line.
myArray[0] = 3;

// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
// You'll learn about functions soon.
if(typeof(myArray) !== "undefined"){(function(){return(myArray);})();}
```

returns an error.

**Comment by benmcmahon100** [comment]
This has just been fixed!
