### ISSUE TITLE
Accept Wrong answer

### ISSUE THREAD

**Issue by roshad** [freeCodeCamp/freeCodeCamp#17887]
#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/positive-and-negative-lookahead/

Wrong Answer Accepted
/\w+(?=\w{5,})(?=\D*\d{2,})/

**Comment by roshad** [comment]
Oh, match, not select, then it's my misunderstanding.
Sorry, cannot delete.

**Comment by Nirajn2311** [comment]
@roshad could you close the issue.

**Comment by roshad** [comment]
close #17887
