### ISSUE TITLE
Regex challenge - more strict Tests required

### ISSUE THREAD

**Issue by jooji-san** [freeCodeCamp/freeCodeCamp#17882]
#### Describe your problem and - if possible - how to reproduce it
the challenge below asks you to check usernames according to some rules. One of the rules is this: 
> The only numbers in the username have to be at the end. There can be zero or more of them at the end.

i wrote this code, which clearly violates this rule, but still passes all the tests:
```
let username = "JackOfAllTrades";
let userCheck = /^[\D].+$/; // Change this line
let result = userCheck.test(username);
```
'cause this regex also matches with i.e. 'user7name', which should not be the case according to the rule above.
Here are the test and not a single one is testing against this type of username: 

> Your regex should match JACK
Your regex should not match J
Your regex should match Oceans11
Your regex should match RegexGuru
Your regex should not match 007
Your regex should not match 9

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/restrict-possible-usernames

**Comment by ArielLeslie** [comment]
There are also no tests for the second part of third rule: "A two-letter username can only use alphabet letter characters."

**Comment by VukMNE** [comment]
I had a similar situation.
My solution was /[A-Za-z]{2,}/; And if the tests were more accurate, I wouldn't be able to pass the challenge.
There needs to be at least one test where the numbers are at the begining of the username, or in the middle of it. 
I think that the challenge is good, and we shouldn't get an easy pass.

**Comment by RandellDawson** [comment]
@moT01 Should we close this in favor of issue https://github.com/freeCodeCamp/freeCodeCamp/issues/17733 ?

**Comment by moT01** [comment]
This seems to have been fixed on [beta](freecodecamp.rocks) - those two solutions no longer work.
