### ISSUE TITLE
Advanced Node & Express Issues Tracker project boilerplate needs change

### ISSUE THREAD

**Issue by lieberscott** [freeCodeCamp/freeCodeCamp#17884]
#### Describe your problem and - if possible - how to reproduce it
The index.html file for the Glitch clone of the Issues Tracker project needs a change. The form for deleting an entry should have id="testForm3". Currently it's "testForm2" and therefore doesn't work with the rest of the project.

I submitted a pull request to the Github repo as well for this.

#### Add a Link to the page with the problem
Line 62 - https://glitch.com/edit/#!/protective-garage?path=views/index.html:62:6

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by nathanhannig** [comment]
You mentioned submitting a pull request. I do not see any in my search. Can you please post a link to it?

**Comment by nathanhannig** [comment]
I see that this is an issue with an existing open pull request on the boilerplate itself.
https://github.com/freeCodeCamp/boilerplate-project-issuetracker/pull/1

I think an admin should be made aware that the boilerplates are sitting with open PR that should be reviewed and see how this should be handled.

**Comment by lieberscott** [comment]
Yes, I'm not sure why but seems my pull request didn't get submitted (I'm still a bit new to Github) but the pull request you linked to seems to make the same correction anyway.

**Comment by nathanhannig** [comment]
It looked like you submitted a PR to your own project, but never to the fCC codebase.

But fCC codebase takes a bit of set up. If you ever want to help here are the steps https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md

**Comment by lieberscott** [comment]
Cool, thanks!

**Comment by scissorsneedfoodtoo** [comment]
Fixed with https://github.com/freeCodeCamp/boilerplate-project-issuetracker/pull/1.
