### ISSUE TITLE
ES6: Create Strings using Template Literals - "Invalid Regular Expression"

### ISSUE THREAD

**Issue by VirtuaBoza** [freeCodeCamp/freeCodeCamp#17885]
#### Describe your problem and - if possible - how to reproduce it
I "solved" ES6: Create Strings using Template Literals thusly:
```javascript
const result = {
  success: ["max-length", "no-amd", "prefer-arrow-functions"],
  failure: ["no-var", "var-on-top", "linebreak"],
  skipped: ["id-blacklist", "no-dup-keys"]
};
function makeList(arr) {
  "use strict";

  // change code below this line
  const resultDisplayArray = arr.map(entry => {
    return `<li class="text-warning">${entry}</li>`;
    });
  // change code above this line

  return resultDisplayArray;
}
/**
 * makeList(result.failure) should return:
 * [ <li class="text-warning">no-var</li>,
 *   <li class="text-warning">var-on-top</li>, 
 *   <li class="text-warning">linebreak</li> ]
 **/
const resultDisplayArray = makeList(result.failure);
```
Of the three tests, I pass "resultDisplayArray is a list containing result failure messages" and "resultDisplayArray is the desired output" but I cannot pass "Template strings were used" even though I obviously did use a template string. In the test console, the following message appears:

> Invalid regular expression flags

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/create-strings-using-template-literals/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 10 Education (64-bit)

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/22282010/42738010-89a22362-884a-11e8-8b91-19ca3ac96764.png)

**Comment by iamtirado** [comment]
Did it get resolved?

**Comment by VirtuaBoza** [comment]
Somebody informed me that this same issue has been worked to close already, but it just hasn’t made it to production yet.

**Comment by UnivesalOxygen** [comment]
const result = {
  success: ["max-length", "no-amd", "prefer-arrow-functions"],
  failure: ["no-var", "var-on-top", "linebreak"],
  skipped: ["no-extra-semi", "no-dup-keys"]
};
function makeList(arr) {
  // Only change code below this line
   const failureItems = arr.map(entry => {
    return `<li class="text-warning">${entry}</li>`;
    });
  // Only change code above this line

  return failureItems;
}

const failuresList = makeList(result.failure);
