### ISSUE TITLE
clear and vertical-aligned properties are referenced but wasn't introduced before in "CSS Flexbox: Use the align-self Property"

### ISSUE THREAD

**Issue by ivanduka** [freeCodeCamp/freeCodeCamp#17881]
#### Describe your problem and - if possible - how to reproduce it

The description of the "CSS Flexbox: Use the align-self Property" lesson references "float", "clear", and "vertical-align". However, only "float" was explained in the previous lessons (specifically in the "Applied Visual Design: Push Elements Left or Right with the float Property"), but "clear" and "vertical-align" were not explained before.

It creates a little bit of confusion as students might be searching the previous lessons for "clear" and "vertical-align" but cannot find them.

I see a couple of ways to solve it:
1. Add those properties to the "Applied Visual Design: Push Elements Left or Right with the float Property" lesson
2. Create separate lessons for them
3. Do not reference them in "CSS Flexbox: Use the align-self Property" at all
4. Add a remark like "those properties were not covered in the course, but you can search for them on your own"

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/responsive-web-design/css-flexbox/use-the-align-self-property

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Macos 10.13.6

#### If possible, add a screenshot here

<img width="424" alt="screen shot 2018-07-14 at 14 51 42" src="https://user-images.githubusercontent.com/39438519/42727961-771d721c-8775-11e8-9dc3-430f44bc2c9a.png">

Thanks!

**Comment by markodelgadillo** [comment]
It seems that freeCodeCamp has a couple of guides for each of the CSS properties that weren't previously covered in the curriculum. I'm thinking of adding links to those guides and mentioning a note like "If you want more information about these CSS properties, you can find them here <link>."

**Comment by thecodingaviator** [comment]
@ivanduka I think what we have is fine because we're anyways saying it does not work with Flexbox. Please close the issue and feel free to open for further discussion.

cc: @ezioda004
