### ISSUE TITLE
Basic CSS Penguin error messages

### ISSUE THREAD

**Issue by WuerfelDev** [freeCodeCamp/freeCodeCamp#17889]
#### Describe your problem and - if possible - how to reproduce it
I get following error messages:
```
penguin class should declare the --penguin-skin variable and assign it to gray.
penguin class should declare the --penguin-skin variable and assign it to white.
penguin class should declare the --penguin-skin variable and assign it to orange.
```
Should not always be `--penguin-skin` ;)

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-variables-to-change-several-elements-at-once

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 61.0.1
* Operating System: Ubuntu

#### If possible, add a screenshot here
![screenshot from 2018-07-16 23-12-11](https://user-images.githubusercontent.com/12686819/42781313-741c392e-894e-11e8-83b8-34471cb52109.png)

**Comment by Nirajn2311** [comment]
I’ll work on it.

**Comment by scissorsneedfoodtoo** [comment]
@WuerfelDev, thank you for reporting this. This problem was fixed in https://github.com/freeCodeCamp/curriculum/pull/117, but hasn't been pushed to production yet. Please hang tight and the fixes should be reflected on the live site, soon!
