### ISSUE TITLE
Waypoint: Modify Array Data With Indexes

### ISSUE THREAD

**Issue by deandersson** [FreeCodeCamp/FreeCodeCamp#1788]
Challenge http://www.freecodecamp.com/challenges/waypoint-modify-array-data-with-indexes has an issue. 

the assertion expects two `[0]` and two `=` when it should be one of each.

im guessing an earlier version of the challenge also set index 0 of `ourArray`

![image](https://cloud.githubusercontent.com/assets/9444040/9294890/003614e8-445b-11e5-9c7a-7e78337e76dc.png)

**Comment by deandersson** [comment]
Same issue was posted while I wrote this issue.. :smile:

#1787

**Comment by benmcmahon100** [comment]
On this now!
