### ISSUE TITLE
Feature Proposal: Users can enter a "class code" to join a classroom

### ISSUE THREAD

**Issue by utsab** [freeCodeCamp/freeCodeCamp#17899]
I'm a contributor to the new [classroom mode](https://github.com/freeCodeCamp/classroom-mode/) application for FreeCodeCamp.  Based on the discussion in this [thread](https://github.com/freeCodeCamp/open-api/issues/181#issuecomment-405049078), we would like to start tracking a user's number of attempts for each challenge.  

Quincy mentioned that he would like to ensure that this data is viewable only by the individual users and their designated teachers.    

The following wireframes propose a solution to this problem.  The idea is to allow a user to enter a "class code".   We can then use this "class code" to control access to their data in the open-api codebase and classroom mode.  

@QuincyLarson, please let me know if you approve of this feature.  If so, I'm happy to get started working on this with the rest of our classroom mode team. 

![coaching_input_unselected](https://user-images.githubusercontent.com/6780322/42920863-be70ca78-8acd-11e8-856b-8f3f572782d9.png)

![coaching_input_selected](https://user-images.githubusercontent.com/6780322/42920867-c488f516-8acd-11e8-87b9-463bbcbdea56.png)

**Comment by QuincyLarson** [comment]
Hi Utsab,

This is a cool feature idea. The settings view is the right place to put this. 

We would want this to be a separate area of the settings page - that space is just for editing/previewing the bio and I think most people would miss that if we put it there.

It could be a section with the heading "Join a class" where they can enter a classroom code and it would say something like "You're now part of Mr. Wagner's AP Computer Science class" or something like that, where each class would have both a name and an identifying number.

I agree that having them enter an alphanumeric code would be ideal, since it would reduce the discoverability of these classes.

**Comment by QuincyLarson** [comment]
This will involve updating our open API so I'm @-mentioning @ojongerius and @raisedadead here.

**Comment by thecodingaviator** [comment]
Guys I think that since this issue is more related to our Classroom project, it should be opened there and this one closed for now?

**Comment by utsab** [comment]
@thecodingaviator, sorry for the late reply on this.  It's true that this feature is related to the Classroom Mode project, but the class-code should be generated from within the learn codebase.  This class-code will serve as a key that the open-api will use to control access to the user's data.

**Comment by thecodingaviator** [comment]
Oh, I see

**Comment by QuincyLarson** [comment]
@utsab We can revisit this once we have our open API live. I agree that we want some prominent way to "enroll" in a class right from settings. We'll have a better idea of what that should look like once we have that code live.

**Comment by QuincyLarson** [comment]
I am closing this issue for now. We can revisit classroom mode in Q3 once we have rolled out our curriculum updates and other features.

**Comment by mirenbz** [comment]
Hi, I don't have any contribution to make, just would like to express that I'm using freeCodeCamp as a teacher in my (undergraduate level) class and would love to have some of the features you listed for this "Classroom setting".

For me, having the ability to check progress on a group of students would suffice. I used to achieve something similar by scraping public profiles with Yahoo! Pipes, but now that's gone I have no idea how to do it. In other words, a page were I can (manually, if necessary) add a number of public profiles and show a table with

- last update
- points
- progress in lessons?

...would do me a lot of service right now.

Thanks in advance!
