### ISSUE TITLE
Basic CSS: Use CSS Variables to change several elements at once - issue

### ISSUE THREAD

**Issue by Puritanic** [freeCodeCamp/freeCodeCamp#17897]
#### Describe your problem and - if possible - how to reproduce it
Description of the task is wrong, you can see in the screenshot that all three variables are specifying `--penguin-skin`, which is an error I guess. Task passes if I ignore the task description and pass this code as the solution:
```
   --penguin-skin: gray;
    --penguin-belly: white;
    --penguin-beak: orange;
```

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-variables-to-change-several-elements-at-once

#### Tell us about your browser and operating system

* Browser Name: Chromium
* Browser Version: 67
* Operating System: Manjaro Deepin

#### If possible, add a screenshot here

https://ibb.co/mEuvEJ

**Comment by im-ironclad** [comment]
This is the same as Issue #17901 (yours came first) but i'm taking a peek at it.
