### ISSUE TITLE
ES6: Use getters and setters to Control Access to an Object - can pass without proper validation

### ISSUE THREAD

**Issue by TheNewStyles** [freeCodeCamp/freeCodeCamp#17898]
#### Describe your problem and - if possible - how to reproduce it
With commented out code still passes tests

```
function makeClass() {
  "use strict";
  /* Alter code below this line */
  class Thermostat {
    // constructor(temperature) {
    //   this._temperature = temperature;
    // }

    // get temperature(){
    //   return 5/9 * (this._temperature - 32);
    // }

    // set temperature(newTemp){
    //   this.temperature = newTemp * 9.0 / 5 + 32;
    // }
  }
  /* Alter code above this line */
  return Thermostat;
}
```

const Thermostat = makeClass();
const thermos = new Thermostat(76); // setting in Fahrenheit scale
let temp = thermos.temperature; // 24.44 in C
thermos.temperature = 26;
temp = thermos.temperature; // 26 in C

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-getters-and-setters-to-control-access-to-an-object

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #17403, so I am closing it as a duplicate.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
