### ISSUE TITLE
ES6: Create Strings using Template Literals

### ISSUE THREAD

**Issue by jumar98** [freeCodeCamp/freeCodeCamp#17891]
#### Describe your problem and - if possible - how to reproduce it

3d Case not pass

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/create-strings-using-template-literals/

#### Tell us about your browser and operating system

* Browser Name: Google
* Browser Version: 67.0.3396.99 
* Operating System: Windows

**Comment by joker314** [comment]
Hi! Thanks for reporting this. However, this has actually already been covered in another issue, #17788. Here is the current official response:

> You're right, this is a recent problem that was caused by updating the regex to account for different solutions, but unfortunately we didn't escape that last forward slash. This was fixed recently and will hopefully be on the production site soon.

Let's keep the conversation in one place and discuss this over there.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #17788, so I am closing it as a duplicate.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
