### ISSUE TITLE
loopback error: Model not found ?

### ISSUE THREAD

**Issue by profoundhub** [freeCodeCamp/freeCodeCamp#17890]
#### Describe your problem and - if possible - how to reproduce it
After attempting to seed the database: 

/****/
Seeding Database
/****/

... \node_modules\loopback\lib\registry.js:317
  throw new Error(g.f('Model not found: %s', modelName));
  ^

Error: Model not found: flyer

**Comment by profoundhub** [comment]
Still no solution, anyone else having this problem?

**Comment by shootermv** [comment]
hi, im complete new to this repo, may be im missing something basic...
But can you please provide the details of reproduce the bug for newbies like me?
like:
1. clone this repo
2. run `npm i`
etc...

Thanks!

**Comment by scissorsneedfoodtoo** [comment]
Setting up fCC locally has changed quite a bit since this issue was opened. You can read the most recent guide here: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md
