### ISSUE TITLE
Sass challenges are browser dependant, some won't pass in Chrome(Version 67.0.3396.99), but will pass in Mozilla Firefox(Version 56.0)

### ISSUE THREAD

**Issue by PhoeniXAbhisheK** [freeCodeCamp/freeCodeCamp#17896]
#### Describe your problem and - if possible - how to reproduce it
For the following challenges, the correct codes do not pass in Google Chrome(Version 67.0.3396.99), but are successful when done the same in Mozilla Firefox(Version 56.0)

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/sass/store-data-with-sass-variables/
https://learn.freecodecamp.org/front-end-libraries/sass/use-for-to-create-a-sass-loop/
https://learn.freecodecamp.org/front-end-libraries/sass/use-each-to-map-over-items-in-a-list/
https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while/

#### Tell us about your browser and operating system

Google Chrome(Version 67.0.3396.99)
Mozilla Firefox(Version 56.0)

Windows 10 Pro(64-bit)

#### If possible, add a screenshot here

![1_chrome](https://user-images.githubusercontent.com/16290904/42862624-f78d5178-8a7d-11e8-9eb3-d4ba4aba31f3.PNG)
![1_firefox](https://user-images.githubusercontent.com/16290904/42862625-f8834a06-8a7d-11e8-90c3-a9f98be1937d.PNG)
![2_chrome for-loop](https://user-images.githubusercontent.com/16290904/42862626-f97d54f6-8a7d-11e8-9dea-494a0e9e70fd.PNG)
![2_firefox for-loop](https://user-images.githubusercontent.com/16290904/42862627-f9bf068a-8a7d-11e8-9695-8af9c62e1ae1.PNG)
![3_chrome each-loop](https://user-images.githubusercontent.com/16290904/42862628-fab84fd8-8a7d-11e8-9211-ae8d7a8c915d.PNG)
![3_firefox each-loop](https://user-images.githubusercontent.com/16290904/42862631-fbaed3e4-8a7d-11e8-89ca-3e7ffaf377e5.PNG)
![4_chrome while-loop](https://user-images.githubusercontent.com/16290904/42862632-fc1d044a-8a7d-11e8-8f79-20a2e6217269.PNG)
![4_firefox while-loop](https://user-images.githubusercontent.com/16290904/42862633-fc892c06-8a7d-11e8-8f9b-8da1147e76dc.PNG)

**Comment by CoderKlemen** [comment]
I have the same problem, these challenges are not passing tests with correct solution. Tried both in Firefox and Chromium.

My setup:
Debian 9.5 ( 32bit )

Firefox ( version 52.9.0 (32-bit) )
Chromium ( version 67.0.3396.87 )

**Comment by thecodingaviator** [comment]
All these SASS challenges have been fixed, the last of which will soon be pushed production. Please close the issue @PhoeniXAbhisheK / @ezioda004 . @PhoeniXAbhisheK if you still have an issue in any one feel free to reopen the issue

**Comment by Tanya-L** [comment]
29 Apr 2019
Issue still here
<img width="989" alt="Screen Shot 2019-04-29 at 15 16 06" src="https://user-images.githubusercontent.com/31630308/56898813-43fe0080-6a92-11e9-8599-8e3deeb46b8a.png">

**Comment by RandellDawson** [comment]
@Tanya-L This is a separate issue related to Chrome.  Can you create a new issue and I will respond there?
