### ISSUE TITLE
Feature Request: Combined/Complete Guide of A Certificate (without the challenge part) for people with slow or restricted internet connection

### ISSUE THREAD

**Issue by zrfrank** [freeCodeCamp/freeCodeCamp#17895]
I wish to request a feature which will benefit people with a slow, limited or restricted internet connection, that providing a downloadedbale, combined/complete guide of a certificate, in one HTML, pdf, epub, etc. So that people can study the complete guide whenever and wherever possible, and then when connected, return to the normal procedure of completing each test and challenges.

This also has the potential benefit for experienced developers who are transitioning to or interested in web development, who requires less step by step guide, that could save an enormous amount of time by reading a complete documented guide then practicing in all challenges.

Thank you for your time and consideration.

**Comment by RandellDawson** [comment]
@zrfrank Tecnhically, you could download the repo and set it up locally on your machine and work through all the challenges similar to how you would on the production site.

**Comment by moT01** [comment]
Closing this as stale. Thanks for the suggestion - like it was mentioned you can download and run this locally. It's not a single file, but it's the whole curriculum and guide - which is a lot. Feel free to open a new issue about this, and maybe it will get some more attention there. Thanks and happy coding!
