### ISSUE TITLE
Small mistake in the instructions of Basic CSS: Use CSS Variables to change several elements at once

### ISSUE THREAD

**Issue by Rapu786** [freeCodeCamp/freeCodeCamp#17901]
#### Describe your problem and - if possible - how to reproduce it
----penguin-skin has been mentioned in places where --penguin-belly & --penguin-beak should present.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-variables-to-change-several-elements-at-once
![error](https://user-images.githubusercontent.com/17670191/42962711-dcb625c2-8baf-11e8-834a-1447cd5157bf.jpg)

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by im-ironclad** [comment]
I'm going to take a crack at this. Will update when I've been either successful or unsuccessful. This is my first contribution 🤘🏻.

**Comment by ninadingole** [comment]
@im-ironclad I will get this fixed if that's ok ?

**Comment by im-ironclad** [comment]
@ninadingole You can look into it, i've forgotten to make a note but I think in the source code that I was looking at it seemed to be fixed and possibly just not pushed live yet. Feel free to take over though!

**Comment by ninadingole** [comment]
@im-ironclad Thanks! I will work on this.

**Comment by moT01** [comment]
this appears to be fixed in the curriculum repo and probably just not live yet - https://github.com/freeCodeCamp/curriculum/blob/dev/challenges/01-responsive-web-design/basic-css.json#L4555

**Comment by moT01** [comment]
Thank you for reporting this issue.

    This is a standard message notifying you that this issue is present in production, but it has been fixed in staging. Because of that, I’m closing this issue. When staging will be pushed to production again, your issue will be resolved.

    If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
