### ISSUE TITLE
Uncomment HTML: Typo in the first sentence of the given description

### ISSUE THREAD

**Issue by manankalra** [freeCodeCamp/freeCodeCamp#17900]
There's a typo in the **Basic HTML and HTML5: Uncomment HTML** section. The first sentence should contain _displayed **to** the end user_ instead of _displayed the end user_.

https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/uncomment-html

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 7 Professional

![issue](https://user-images.githubusercontent.com/12759088/42931108-74078942-8b5c-11e8-949c-c0ec6274671c.PNG)

**Comment by scissorsneedfoodtoo** [comment]
@manankalra, thank you for pointing this out. This was recently fixed in https://github.com/freeCodeCamp/curriculum/pull/163, so I'll close this issue.
