### ISSUE TITLE
Typo in MongoDB and Mongoose - Delete Many Documents with model.remove()

### ISSUE THREAD

**Issue by tingxuanz** [freeCodeCamp/freeCodeCamp#17904]
#### Describe your problem and - if possible - how to reproduce it
There is a typo in the first paragraph of 'MongoDB and Mongoose - Delete Many Documents with model.remove()' challenge page.  In the last sentence 'Pass to it a query ducument ...', 'ducument' should be 'document'.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/apis-and-microservices/mongodb-and-mongoose/delete-many-documents-with-model-remove

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System: 

#### If possible, add a screenshot here

![snip20180720_1](https://user-images.githubusercontent.com/17842286/42985838-72c2ee66-8c36-11e8-8b74-5149df326a1b.png)

**Comment by hilliarj** [comment]
Shouldn't this issue be closed? It is has already been fixed. 

@raisedadead

**Comment by Nirajn2311** [comment]
@tingxuanz @hilliarj This issue is being closed as it has been resolved by the PR shown above.
