### ISSUE TITLE
Bad English

### ISSUE THREAD

**Issue by Doug22** [freeCodeCamp/freeCodeCamp#17906]
First paragraph - needs a "to" inserted between "displayed '**_to_**' the end user." Full paragraph below.

Commenting is a way that you can leave comments for other developers within your code without affecting the resulting output that is displayed the end user.

https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/uncomment-html/

Is it a nitpick - sure. Do you have to change it ~ well, the idea is still conveyed.

**Comment by nathanhannig** [comment]
you are correct, thanks for bringing it to our attention.

**Comment by nathanhannig** [comment]
this is a duplicate report
#17900
#17904

**Comment by Nirajn2311** [comment]
@Doug22 can you close this issue as it has been solved.

**Comment by scissorsneedfoodtoo** [comment]
@Doug22, thank you for reporting this. This was recently fixed by @Nirajn2311, so I'll close this issue.

@nathanhannig, thanks for pointing out the duplicate issue. Will close that now.
