### ISSUE TITLE
Typo in MongoDB and Mongoose - Perform New Updates on a Document Using model.findOneAndUpdate()

### ISSUE THREAD

**Issue by tingxuanz** [freeCodeCamp/freeCodeCamp#17905]
#### Describe your problem and - if possible - how to reproduce it
There is a typo in the Hint paragraph. The second sentence 'o do that you need to pass ...'

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/apis-and-microservices/mongodb-and-mongoose/perform-new-updates-on-a-document-using-model-findoneandupdate

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System: 

#### If possible, add a screenshot here

![snip20180720_2](https://user-images.githubusercontent.com/17842286/42986091-9bdd2144-8c37-11e8-807e-e30303795ecb.png)

**Comment by renojvarghese** [comment]
I can take this one

**Comment by Nirajn2311** [comment]
@renojvarghese @tingxuanz this issue was fixed in [curriculum/#121](
https://github.com/freeCodeCamp/curriculum/pull/121), but it has not yet been shown up in the website as learn repo has to be updated to the recent version of curriculum repo.

**Comment by renojvarghese** [comment]
Sounds good. @tingxuanz Could you close this issue?
