### ISSUE TITLE
PERSONAL PORTOFOLIO PAGE CHALLENGE - UNITY TEST LINK NOT WORKING

### ISSUE THREAD

**Issue by Eidan78** [freeCodeCamp/freeCodeCamp#17918]
Page:
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage

The CDN link listed in the page challenge for the tests is not working: 
https://gitcdn.link/repo/freeCodeCamp/testable-projects-fcc/master/build/bundle.js

I found out this link is working fine insthead:
https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js

* Browser Name:  Google Chrome 
* Browser Version: v. 67.0.3396.99
* Operating System: Windows 10

**Comment by Nirajn2311** [comment]
On it.

**Comment by Nirajn2311** [comment]
This issue has been fixed in [curriculum/#138](
https://github.com/freeCodeCamp/curriculum/pull/138) but the website has still not yet been updated to the recent version, so some errors are still there like this one and the penguin css typos etc.

**Comment by moT01** [comment]
Thank you for reporting this issue.

    This is a standard message notifying you that this issue is present in production, but it has been fixed in staging. Because of that, I’m closing this issue. When staging will be pushed to production again, your issue will be resolved.

    If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
