### ISSUE TITLE
New Design....(Sigh)

### ISSUE THREAD

**Issue by therealmuffinman** [freeCodeCamp/freeCodeCamp#17916]
Let me start off by saying that I have learned a lot of good things at freeCodeCamp and my learning experience has always been enjoyable, until I logged in recently and noticed a couple of things.

So I'm not sure why the admins chose to redesign the website, (since it worked perfectly fine before). Having a new color scheme or layout on a website doesn't normally bother me, but the new design is HORRIBLE it looks like it was made by a 5 year old and why they would remove the community help page is beyond me.

Those things are stuff that I can still overlook, here's the kicker though.  When you finish a challenge the software wont tell you if you are right or wrong like before, it just says "running test" in the new bottom window and freezes. Which doesn't allow you to continue with the following lessons or even check the code for mistakes.

 I just hope that you guys can fix it back to the way it was before, because this new design doesn't even work properly and is an aesthetic eyesore.

**Comment by raisedadead** [comment]
Hi @therealmuffinman 

Thanks for the issue report and the feedback. We appreciate the gesture, however, please note that we have a [Forum](https://forum.freecodecamp.com) where you are more than free to discuss this. Some of your queries have already been answered by the community there.

This issue tracker is for reporting core development and technical discussions only. Also, we would like to point you towards our [CoC](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CODE_OF_CONDUCT.md), which can help us discuss constructively.

Thanks and happy contributing.
/cc @QuincyLarson
