### ISSUE TITLE
False Map Data

### ISSUE THREAD

**Issue by jasminej90** [FreeCodeCamp/FreeCodeCamp#1791]
Challenge http://www.freecodecamp.com/challenges/waypoint-get-set-for-ziplines has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Hello,

I opened my account today (after the changes you guys did), and suddenly it says that I've completed the following challenges in the pictures (which I did not). Also, it added a lot of new challenges (but I believe I've already completed some of them) However, my map doesn't show that. I'm really confused and frustrated as I feel like my effort has gone to waste. I'm not sure how to continue even or from where to start!

![screen shot 2015-08-16 at 10 30 36 pm](https://cloud.githubusercontent.com/assets/5523688/9294970/a55c69a8-4466-11e5-84c4-eded0d9bad67.png)
![screen shot 2015-08-16 at 10 31 06 pm](https://cloud.githubusercontent.com/assets/5523688/9294971/a5605c20-4466-11e5-9ae7-41bc2e4791b4.png)

**Comment by QuincyLarson** [comment]
@jasminej90 This is a known issue that we're fixing. Thanks for your patience. For more information, read: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/August-2015-Improvements
