### ISSUE TITLE
ES6: Use Destructuring Assignment to Pass an Object as a Function's Parameters

### ISSUE THREAD

**Issue by amcmullan** [freeCodeCamp/freeCodeCamp#17912]
#### Describe your problem and - if possible - how to reproduce it
I think the examples could be more descriptive of what is actually required. Both code examples involve variables which have totally different syntax from passing destructured objects to a function. And thus, at least in my case, only add confusion. 

I'm not suggesting excessive hand holding, but for challenges that specifically involve learning syntax it is imperative that the syntax is clear and understood. Or failing that, not muddied by the addition of syntax unrelated to the problem.

I'm definitely open to other ideas, this is just my experience, since I like what FCC is trying to do I wanted to give feedback on an issue I noticed. I'm happy to try my hand at an alternative description, if others see what I see as a problem as well.

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-pass-an-object-as-a-functions-parameters

**Comment by nathanhannig** [comment]
I agree, specifically...

- the example shows an arrow function while the code is set up with an anonymous function which I think can be confusing to beginners.
- the example doesn't show the contents of profileData and leaves it up to the user to imagine the contents originally contained at least: name, age, nationality, location. While the code helps show the contents of the stats object.

I also have the following opinion on the challenge. I think the term "argument" is being used incorrectly and the term "parameter" should be used instead. The destructuring is being performed in the function's parameter on the object being passed in as an argument.

**Comment by geecheeche** [comment]
I share the same sentiments. It is frustrating to say the least. The descriptions do nothing to help as they are misleading a great deal.

**Comment by moT01** [comment]
This looks like it's resolved in [beta](https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-pass-an-object-as-a-functions-parameters)

So I think it's safe to close this.
