### ISSUE TITLE
FCC: Survey Page

### ISSUE THREAD

**Issue by shvmsaini** [freeCodeCamp/freeCodeCamp#17919]
Hi,
I want you to know that there is a CSS selector in the FCC:Survey Page ( https://codepen.io/freeCodeCamp/full/VPaoNP ) that is #userAge , that is useless since there is no id with value userAge .
Thank you.

**Comment by thecodingaviator** [comment]
That @shvmsaini that selector does not matter afaik. Right now CodePen is offline, maybe someone will check when it goes online. I think this can be closed for now.

@raisedadead / @Bouncey
