### ISSUE TITLE
Basic JavaScript: Understanding Uninitialized Variables

### ISSUE THREAD

**Issue by carlawarde** [freeCodeCamp/freeCodeCamp#17913]
#### Describe your problem and - if possible - how to reproduce it
The challenge works fine, it's just that there's some errors in the text. 

> Initialize the three variables a, b, and c with 5, 10, and "I am a" respectively so that they will not be undefined.

Is the values you are required to initialise, but the challenge markers say something different:

> a should be defined and evaluated to have the value of 6
b should be defined and evaluated to have the value of 15
c should not contain undefined and should have a value of "I am a String!"

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/understanding-uninitialized-variables/

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Operating System: Windows 10

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/18583701/43045768-b486506e-8db6-11e8-8ff4-623e6bc44609.png)

**Comment by carlawarde** [comment]
I had searched for a similar issue to mine before posting this issue, but I just didn't use the correct search criteria, I guess. Tried something else after I posted the issue and then found it, lol

The older issue has still not been resolved, however.

**Comment by thoothie** [comment]
This is still an issue as well for osx. The directions on top do not match the directions on the bottom.
