### ISSUE TITLE
code / solutions to a challenge don't save / are erased

### ISSUE THREAD

**Issue by PolarisTLX** [freeCodeCamp/freeCodeCamp#17927]
#### Describe your problem and - if possible - how to reproduce it
After completing a challenge, your code / solution gets erased when you come back to the page later.  Even if you don't click "Reset All Code".

This prevents these challenges from bring a good resource to go back to.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react/write-a-simple-counter

#### Tell us about your browser and operating system

* Browser Name:  Chrome
* Browser Version:  67.0.3396.99 (Official Build) (64-bit)
* Operating System:  Windows 10
![fcc1](https://user-images.githubusercontent.com/26701119/43216519-3e9267e0-900d-11e8-9c8d-d3de884ed645.jpg)
![fcc2](https://user-images.githubusercontent.com/26701119/43216520-3ea886ec-900d-11e8-9a64-2291c99c3db0.jpg)

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue https://github.com/freeCodeCamp/freeCodeCamp/issues/17485, so I am closing it as a duplicate.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
