### ISSUE TITLE
Saas:Use @each to Map Over Items in a List

### ISSUE THREAD

**Issue by NiteshTyagi** [freeCodeCamp/freeCodeCamp#17922]
#### Describe your problem and - if possible - how to reproduce it
My code to the corresponding given problem statement is correct but it doesn't pass the test cases.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/sass/use-each-to-map-over-items-in-a-list

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Window 8

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/33661780/43195136-c885517e-9021-11e8-889d-27d32f52c72e.png)

**Comment by Nirajn2311** [comment]
There has been a lot of problems regarding sass challenges here and we are working quickly to resolve the issues.

**Comment by thecodingaviator** [comment]
@NiteshTyagi , I have just checked, this solution works-

![image](https://user-images.githubusercontent.com/34807532/47069331-4098db00-d20c-11e8-9231-4737a1eb671c.png)


@NiteshTyagi / @QuincyLarson / @raisedadead / @Bouncey this can be closed now

**Comment by ezioda004** [comment]
Issue has been resolve - closing.

**Comment by ShamimRahmanSam** [comment]
I'm having the same problems. I used your solutions though it's not working @thecodingaviator

**Comment by scissorsneedfoodtoo** [comment]
Hi @ShamimRahmanSam, I just checked this and the solution above is working in Chrome and Firefox on my end.

Please check your code for typos and check out the forum for help.

If you're still having issues after doing those things, please let us know and we can look further into this.
