### ISSUE TITLE
Basic JavaScript Instruction and Example Expect Wrong Value

### ISSUE THREAD

**Issue by CounterWiseClock** [freeCodeCamp/freeCodeCamp#17928]
#### Describe your problem and - if possible - how to reproduce it
Basic JavaScript: Assignment with a Returned Value says that the "processed" value should be 2. Given the instructions, I believe it should be 10. A similar issue exists for the example code.

If instructions are followed correctly, it still runs appropriately and the user can continue . However, the supposed expected results can lead to confusion.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/assignment-with-a-returned-value

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: Windows 10

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/40744921/43226692-61728980-9011-11e8-87d9-90e2b50f3d65.png)

**Comment by ByronCoder** [comment]
I think it should be 2 because you are passing 7 into the processArg function that returns (num +3) / 5. When you pass 7 it would be (7 + 3) / 5  = 10 / 5 = 2.  processArg returns 2 therefore assigning the function to the processed variable will set it's value to 2.

**Comment by CounterWiseClock** [comment]
Shoot, I mistook the single slash for a double slash. Didn't realize it was dividing. sorry for the mistake!
