### ISSUE TITLE
Challenge console doesn't escape single quotes

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#17925]
The single quote in the picture turns the rest of the text to red

![screen shot 2018-07-25 at 10 43 29 am](https://user-images.githubusercontent.com/20648924/43211724-d3e99a2c-8ff7-11e8-8283-65911fd298de.png)

* Browser Name: firefox
* Browser Version: 60.0.1
* Operating System: high sierra

**Comment by Nirajn2311** [comment]
@moT01 which challenge?

**Comment by moT01** [comment]
https://learn.freecodecamp.org/front-end-libraries/redux/send-action-data-to-the-store/

**Comment by RandellDawson** [comment]
@moT01 Is this still an issue on freecodecamp.rocks ?

**Comment by moT01** [comment]
It is, go to any challenge and console.log something with a single quote in it. `console.log("alsdkf'asdfasdf");` - the text after the `'` turns red. Not a huge problem, if you think it's not worth fixing, you can close this.

**Comment by RandellDawson** [comment]
@moT01 I understand the issue now.  I think it is worth fixing.

**Comment by chaomt** [comment]
Is there any update on this issue? I want to work on it.

**Comment by ojeytonwilliams** [comment]
@chaomt If you're still interested in working on this, go for it.  Otherwise, please let me know - it's something I've been meaning to look at for a while!

**Comment by chaomt** [comment]
@ojeytonwilliams Yes, I'm still interested in working on this issue. Thanks for referencing another issue!

**Comment by ojeytonwilliams** [comment]
@chaomt No problem.  I noticed this kind of thing kept turning up, so it seemed worthwhile to pull things together.

**Comment by chaomt** [comment]
@ojeytonwilliams Hi, are you still interested in working on this issue? I am so busy recently and do not have time to work on this.

**Comment by RandellDawson** [comment]
@chaomt I have added the `help wanted` label since you are no longer able to work on this one.  Someone will pick it up.
