### ISSUE TITLE
[Feature request] Disable ligatures for code in the instructions panel

### ISSUE THREAD

**Issue by adiabatic** [freeCodeCamp/freeCodeCamp#17921]
#### Describe your problem and - if possible - how to reproduce it

Ligatures for character sequences like "fi" and "ffl" look weird and distracting when they show up in monospaced text (see screenshots). 

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/write-higher-order-arrow-functions/ displays fi-ligatures in the instructions panel, both in a `<code>` element and in a `<blockquote>` element.

#### Tell us about your browser and operating system

* Browser Name: Safari
* Browser Version: 11.1.2
* Operating System: macOS 10.13.6 (High Sierra)

#### If possible, add a screenshot here

<img width="109" alt="F I ligature in a blockquote element" src="https://user-images.githubusercontent.com/101246/43182062-c0c3ba58-8f94-11e8-820e-36169360a8c3.png">

<img width="151" alt="filter in code element with a F I ligature" src="https://user-images.githubusercontent.com/101246/43182072-cc714cd0-8f94-11e8-803f-80b367b20cde.png">

#### Proposed fix

After digging around in the DOM inspector, I noticed that something like this was in the CSS:

```
body { font-feature-settings: "kern","liga","clig","calt","kern"; }
```

I'm not about to propose removing this, but it turns on ligatures in places that shouldn't have them. I propose adding the following line to a couple of selectors in the CSS:

```
font-feature-settings: "liga" 0;
```

and it'd go on

```
code, kbd, pre, samp
```

and

```
.challenge-instructions blockquote
```

**Comment by RandellDawson** [comment]
@raisedadead What do you think about this?

**Comment by raisedadead** [comment]
I'll defer this to @ahmadabdolsaheb . 

Please note that since we moved to the `.md` files, we maybe able to unify code snippets better. That's we should just be using two types one is inline with back ticks and then there are the blocks with three backticks.

**Comment by RandellDawson** [comment]
@raisedadead Now I remember you saying there the move to using only backticks for the inline and block sections.  So was @ahmadabdolsaheb working on that?

**Comment by raisedadead** [comment]
Not at the minute I guess. But I am suggesting we could unify this from both the UX and the content side, now that we are able to.

**Comment by moT01** [comment]
This looks to be resolved. Screen shot from [this lesson](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/use-the-filter-method-to-extract-data-from-an-array)...

<img width="664" alt="Screen Shot 2019-11-13 at 7 43 17 AM" src="https://user-images.githubusercontent.com/20648924/68769105-63511b00-05e9-11ea-9059-f5089d370a6a.png">

Same visuals on safari, chrome and firefox with osx. 

If anyone is still having issues with this, feel free to reopen the issue.
