### ISSUE TITLE
JS console on Mac OS X (Mavericks) + Chrome

### ISSUE THREAD

**Issue by alexbrotman** [FreeCodeCamp/FreeCodeCamp#1792]
The console for JS challenges does not respond in Chrome on Mac OS X Mavericks. I tried a hard refresh with no luck. It works fine in Safari.

**Comment by QuincyLarson** [comment]
Could you check your JavaScript console to see whether it shows a JavaScript error? A screenshot would also be helpful. Thanks!

**Comment by alexbrotman** [comment]
Refused to load the script 'http://freecodecamp.com/js/lib/jailed/_frame.js' because it violates the following Content Security Policy directive: "script-src *.optimizely.com *.aspnetcdn.com *.d3js.org https://cdn.inspectlet.com/inspectlet.js http://cdn.inspectlet.com/inspectlet.js http://beta.freecodecamp.com 'self' blob: 104.236.218.15 *.freecodecamp.com http://www.freecodecamp.com https://www.freecodecamp.com https://freecodecamp.com https://freecodecamp.org *.freecodecamp.org http://www.freecodecamp.org ws://freecodecamp.com/ ws://www.freecodecamp.com/ *.gstatic.com *.google-analytics.com *.googleapis.com *.google.com *.gstatic.com *.doubleclick.net *.twitter.com *.twitch.tv *.twimg.com 'unsafe-eval' 'unsafe-inline' *.bootstrapcdn.com *.cloudflare.com https://*.cloudflare.com localhost:3001 ws://localhost:3001/ http://localhost:3001 localhost:3000 ws://localhost:3000/ http://localhost:3000 *.ionicframework.com https://syndication.twitter.com *.youtube.com *.jsdelivr.net https://*.jsdelivr.net *.ytimg.com *.bitly.com http://cdn.inspectlet.com/ https://cdn.inspeclet.com/ wss://inspectletws.herokuapp.com/ http://hn.inspectlet.com/ *.googleapis.com *.gstatic.com https://hn.inspectlet.com/".

**Comment by alexbrotman** [comment]
The button has been clicked at this point.
<img width="1330" alt="screen shot 2015-08-16 at 3 13 40 pm" src="https://cloud.githubusercontent.com/assets/10069107/9295139/33c46530-4429-11e5-9dbc-82c25cb96456.png">

**Comment by benmcmahon100** [comment]
@alexbrotman this should be fixed by performing a hard refresh

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
