### ISSUE TITLE
UX: Challenge code editor prompts get cut off

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#17924]
In the code editor part of the challenges - the prompt/predictive text, whatever you want to call it, gets cut off

![screen shot 2018-07-25 at 10 39 09 am](https://user-images.githubusercontent.com/20648924/43211523-492738e0-8ff7-11e8-8c87-074aa4d0b9c0.png)

* Browser Name: firefox 
* Browser Version: 60.0.1
* Operating System: high sierra

**Comment by 1337M0nst3r** [comment]
I would like to help but unfortunately I can't reproduce it. After all the prompt is coded to move with the caret, try to make the editor bigger.
BTW, it's 18 days since you opened this issue 
do you still have this problem? if not could you close it so that this issue doesn't confuse people?

**Comment by thecodingaviator** [comment]
@moT01 Are you talking about this:
![image](https://user-images.githubusercontent.com/34807532/48851574-69932980-edd1-11e8-9688-5f87b992cc53.png)

This cannot be fixed with the way we currently run things using an `iframe` the only workaround is to make all the three pages display separately i.e. on separate browser tabs

**Comment by RandellDawson** [comment]
@moT01 Is this still an issue on the beta site for you?

**Comment by moT01** [comment]
It is still happening, but perhaps it's not worth fixing. It's most noticeable when you are working on a skinny window or frame. The only solution I can think of is to have the prompt thing hug the left of the window. You can close this if you think it doesn't need to be fixed.

**Comment by moT01** [comment]
Closing as stale and not worth fixing for now.
