### ISSUE TITLE
Basic CSS: Attach a Fallback value to a CSS Variable (no typo in class name)

### ISSUE THREAD

**Issue by ByronCoder** [freeCodeCamp/freeCodeCamp#17935]
#### Describe your problem and - if possible - how to reproduce it
Not sure if this is an issue, sorry if it isn't, but the instructions for this challenge seem to imply that there should be a typo in the variable as it says the style will be applied because of a typo in the variable name, but there are no typos so the style is not applied.  I know you can make the typo yourself to see the style applied though.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/basic-css/attach-a-fallback-value-to-a-css-variable/

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 61.0.1 
* Operating System: Linux Mint

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/18274891/43297843-6cdb976a-9121-11e8-92b4-8a49369aac5c.png)

**Comment by moT01** [comment]
@SubhrajyotiSen  @ByronCoder I believe this is already fixed in the curriculum repo, and probably just not live yet https://github.com/freeCodeCamp/curriculum/commit/3abf7adce5d0ed67662b971335205aa521a5b275 @scissorsneedfoodtoo you fixed this issue right?

**Comment by moT01** [comment]
Thank you for reporting this issue.

    This is a standard message notifying you that this issue is present in production, but it has been fixed in staging. Because of that, I’m closing this issue. When staging will be pushed to production again, your issue will be resolved.

    If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.

**Comment by scissorsneedfoodtoo** [comment]
@ByronCoder, thank you for reporting this.

@moT01, yes, this was fixed recently. It should be deployed soon!
