### ISSUE TITLE
Complementary Colors Test Incorrectly Implies Colors that are not Complementary

### ISSUE THREAD

**Issue by pickleat** [freeCodeCamp/freeCodeCamp#17934]
#### Describe your problem and - if possible - how to reproduce it
It is a content issue. 
The problem-set for this lesson implies that blue's complementary color is yellow, when blue's complement is ORANGE. 
If we are teaching people about complementary colors, they should probably use the right complements. :) I'm sure it was just an accident, but I wanted to bring it to your attention. 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/learn-about-complementary-colors

#### Tell us about your browser and operating system

* Browser Name: Safari
* Browser Version: 11.1.2
* Operating System: MaxOS 10.13.6

#### If possible, add a screenshot here

<img width="931" alt="screen shot 2018-07-26 at 7 50 24 pm" src="https://user-images.githubusercontent.com/39109475/43295849-502a3716-910d-11e8-9a3c-d5b8e9db792a.png">

**Comment by ByronCoder** [comment]
Taking a crack at this. This will be my first contribution to this project.

**Comment by ByronCoder** [comment]
Submitted a PR. Not sure if I did this right. But, can someone take a look at this. https://github.com/freeCodeCamp/curriculum/pull/184  Its on the curriculum repo because that is where the json files are for the challenges. Thanks!

**Comment by moT01** [comment]
@ByronCoder the PR should have a link to this page where is says replace XXXXX with the issue number, somewhere in there anyway - then moderators know what issue it fixes and they can close it once the PR is merged

**Comment by ByronCoder** [comment]
Added the link to the PR
