### ISSUE TITLE
HTTPS 301 redirects to invalid link

### ISSUE THREAD

**Issue by johnkennedy9147** [freeCodeCamp/freeCodeCamp#17937]
#### Describe your problem and - if possible - how to reproduce it
if you try to connect to `https://freecodecamp.org` you are redirected to an invalid url `https://www.freecodecamp.org&request_uri/`

![image](https://user-images.githubusercontent.com/26827682/43310717-47f08d84-9180-11e8-90d1-64d7a7fd783f.png)

using http works fine

![image](https://user-images.githubusercontent.com/26827682/43310727-50d54d22-9180-11e8-8b88-39cf9044838c.png)

this is breaking internal links
see https://github.com/freeCodeCamp/learn/pull/249

**Comment by johnkennedy9147** [comment]
@QuincyLarson @raisedadead @Bouncey 
I think this needs urgent attention

**Comment by Bouncey** [comment]
Thanks @johnkennedy9147

**Comment by Bouncey** [comment]
Resolved in the back end, thanks for bring it to our attention @johnkennedy9147 :+1:
