### ISSUE TITLE
Waypoint: Modify Array Data With Indexes

### ISSUE THREAD

**Issue by mschrauth** [FreeCodeCamp/FreeCodeCamp#1793]
Challenge http://www.freecodecamp.com/challenges/waypoint-modify-array-data-with-indexes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![fcc modify array data with indexes](https://cloud.githubusercontent.com/assets/13265618/9295134/0636af24-4429-11e5-9646-68a72c23f6c8.png)
myArray[0] = 3; is not an acceptable answer???

**Comment by MaryJoJo** [comment]
Ditto.

**Comment by BerkeleyTrue** [comment]
@mschrauth Can you retry this challenge? It seems to be working and may have been fixed.
