### ISSUE TITLE
Responsive Web Design Principles: Create a Media Query that cannot be passed

### ISSUE THREAD

**Issue by llllllllly** [freeCodeCamp/freeCodeCamp#17938]
#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.99
* Operating System: MacOS High Sierra

#### If possible, add a screenshot here
Responsive Web Design Principles: Create a Media Query that cannot be passed
![image](https://i.loli.net/2018/07/27/5b5b2f8de7a21.png)

**Comment by moT01** [comment]
@llllllllly It helps to add a short description and a link to the page with the problem - I was unable to reproduce this in firefox or chrome
