### ISSUE TITLE
Can't update URLs of projects after claiming certificate

### ISSUE THREAD

**Issue by Chris6077** [freeCodeCamp/freeCodeCamp#17932]
#### Describe your problem and - if possible - how to reproduce it

After claiming your certificate the "Save" button disappears. You can't update the links to moved websites without a save button. Therefore a few of the projects of my certification are unavailable on fcc. Please add a save button to certifications that are already 100% done.

#### Add a Link to the page with the problem

https://www.freecodecamp.org/settings

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.87
* Operating System: Windows 10 Education - Current Branch for Business

#### If possible, add a screenshot here

![6ed0601d20a3f19a1d4968b429de114c](https://user-images.githubusercontent.com/22944239/43290891-de85963c-912f-11e8-8611-113e20aacca0.png)

**Comment by nathanhannig** [comment]
yep, the only temp workaround is if you didn't finish a legacy cert and you can update that value and save and it will also update the modern cert url. But not a perfect workaround.  Definitely, need it to allow you to save a new url after a cert is claimed.

**Comment by moT01** [comment]
what about going to the project page with the description and resubmitting a new a solution as a temporary workaround - that might work

**Comment by raisedadead** [comment]
This was by design, a correct implementation to update the links to the projects would be to get the certification revoked first. Then add the links and finally claim the certification re-setting it to the new date. This is to avoid abuse of the system.
