### ISSUE TITLE
ES6 - Write Higher Order Arrow Functions - No negative integers included in seed

### ISSUE THREAD

**Issue by PrinceOfShapeir** [freeCodeCamp/freeCodeCamp#17942]
For the task: "Use arrow function syntax to compute the square of only the **positive integers** (fractions are not integers) in the array realNumberArray and store the new array in the variable squaredIntegers."

`const realNumberArray = [4, 5.6, -9.8, 3.14, 42, 6, 8.34];`

The above seeded array does not contain negative integers, causing solutions to pass that do not actually check for them. As the square of a negative number is a positive number, changing any of the integer values above to a negative number will still pass the equality test, eg. 4X4 = -4X-4 = 16, for the following test condition: squaredIntegers should be [16, 1764, 36]

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/write-higher-order-arrow-functions/

**Comment by nathanhannig** [comment]
I will claim this issue. 

Thank you for reporting it.

I also noticed there is a test `User did replace var keyword.` which should be removed as well.

**Comment by nathanhannig** [comment]
I also want to replace the word fraction with decimal number.
`Use arrow function syntax to compute the square of only the positive integers (fractions are not integers) in the array realNumberArray and store the new array in the variable squaredIntegers.`

fractions look like 1/4
decimal numbers look like 0.25

**Comment by nathanhannig** [comment]
I have created a issue in the curriculum repo that references this issue. This issue can be closed and the referenced issue can instead be followed.

**Comment by ziaongit** [comment]
`const squaredIntegers = arr.filter((arr) => Number.isInteger(arr) && arr > 0).map((arr) => arr = arr * arr);`
