### ISSUE TITLE
Night mode shows links as plain text

### ISSUE THREAD

**Issue by Myrmidonut** [freeCodeCamp/freeCodeCamp#17946]
#### Describe your problem and - if possible - how to reproduce it
When using night mode, links show up as plain text and cannot be distinguished from the rest of the description. It happens on every page that has a link. Even the ones without descriptions that just say it is a stub.

A simple underline is probably best, a different background for the link would make it stand out more, for better and worse.

#### Add a Link to the page with the problem
In the last line of the description:
https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm

In a stub:
https://learn.freecodecamp.org/data-visualization/data-visualization-projects

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: Version 68.0.3440.75 (Official Build) (64-bit)
* Operating System: Windows 10 Pro 1803

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/26467570/43358522-96ba1fde-9293-11e8-8243-69fa8ffa2477.png)

![image](https://user-images.githubusercontent.com/26467570/43358513-72ebd5d4-9293-11e8-807a-0a1a346bc2a7.png)

**Comment by Hzuni** [comment]
I'd be up for tackling this if no one else is?

**Comment by Nirajn2311** [comment]
@Hzuni I am already working on it.

**Comment by Nirajn2311** [comment]
@renojvarghese you didn’t have to close your PR, it’s perfect and anyway I am busy the next two weeks.

**Comment by Myrmidonut** [comment]
Good work guys! :-D
