### ISSUE TITLE
D3 Bar Chart Certificate Project User Story 11 TypeError: Cannot read property ‘length’ of null 

### ISSUE THREAD

**Issue by zrfrank** [freeCodeCamp/freeCodeCamp#17956]
The test reports,
>The data-gdp attribute and its corresponding bar element should align with the corresponding value on the y-axis.
```
TypeError: Cannot read property 'length' of null
    at https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:45:83400
    at NodeList.forEach (<anonymous>)
    at t.areShapesAlignedWithTicks (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:45:83275)
    at n.<anonymous> (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:147:260669)
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:7852)
    at r.run (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:8853)
    at i.runTest (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13553)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:14192
    at r (https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13024)
    at https://cdnjs.cloudflare.com/ajax/libs/mocha/3.0.2/mocha.min.js:2:13000
```

With the pen at, https://codepen.io/frankrui/pen/pZpmGP, 

To test it, I’ve offset the y-axis. i.e. 900 in x direction, as shown in screenshoot below, that the tick align perfectly with the bar.

![image](https://user-images.githubusercontent.com/27864196/43465582-3a702f8c-9510-11e8-8b6e-ea6f07f5e87c.png)

**Comment by frank-rui** [comment]
This pen avoided the flip method and used same method as in the tutorials, and failed the test with same error message,

https://codepen.io/frankrui/pen/bjLWxd

**Comment by frank-rui** [comment]
Strangely, after rewrite the code by removing all manual paddings, fixed the No.11 error message
>TypeError: Cannot read property 'length' of null

Then,  if the yaxis d3.linearScale reverse the range instead of domain, the test passed, i.e.

```js
  const yAxisScale = d3.scaleLinear()
                        .domain([0, ymax])
                        .range([H, 0]);
```

But reverse domain will cause No.11 fail with message:
> 11. The data-gdp attribute and its corresponding bar element should align with the corresponding value on the y-axis.

```js
const yAxisScale = d3.scaleLinear()
                        .domain([ymax, 0])
                        .range([0, H]);
```

**Comment by thecodingaviator** [comment]
It's passing at:
![image](https://user-images.githubusercontent.com/34807532/48851183-6c414f00-edd0-11e8-984c-cb2e3d0e6766.png)
So, @frank-rui / @ezioda004 please close the issue

**Comment by RandellDawson** [comment]
@zrfrank Closing this issue, because it appears to be something you resolved.  If you feel this is still an issue, please request us to reopen.
