### ISSUE TITLE
Internal link redirect to external link

### ISSUE THREAD

**Issue by Deepak8717** [freeCodeCamp/freeCodeCamp#17953]
Hi 

Basic HTML and HTML5: Link to Internal Sections of a Page with Anchor Elements. 

Everything looks fine and test is successfully passed with following code but when i click the internal link it redirects me to external link. I did a little research and someone else has discussed the same issue. 
here is the link [https://forum.freecodecamp.org/t/link-to-internal-sections-of-a-page-with-anchor-elements-5-30-2018/194070](url)

```
`<h2>CatPhotoApp</h2>
<main>
  
  <a href="#footer">Jump to bottom</a>
  
  <img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back.">
  
  <p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff. Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
  <p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff. Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
  <p>Meowwww loved it, hated it, loved it, hated it yet spill litter box, scratch at owner, destroy all furniture, especially couch or lay on arms while you're using the keyboard. Missing until dinner time toy mouse squeak roll over. With tail in the air lounge in doorway. Man running from cops stops to pet cats, goes to jail.</p>
  <p>Intently stare at the same spot poop in the plant pot but kitten is playing with dead mouse. Get video posted to internet for chasing red dot leave fur on owners clothes meow to be let out and mesmerizing birds leave fur on owners clothes or favor packaging over toy so purr for no reason. Meow to be let out play time intently sniff hand run outside as soon as door open yet destroy couch.</p>
  
</main>
  
<footer id="footer">Copyright Cat Photo App</footer>`

```

#### Add a Link to the page with the problem
[https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/link-to-internal-sections-of-a-page-with-anchor-elements/](url)

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by Deepak8717** [comment]
Links on this page are not working, kindly copy the above link and paste it in the browsers.

**Comment by thecodingaviator** [comment]
That is because the FreeCodeCamp rendering approach works on ` iframe ` and if you click on an internal link in a ` iframe ` afaik, it does not behave as expected.

**Comment by thecodingaviator** [comment]
@ezioda004 I think this can be closed!

**Comment by RandellDawson** [comment]
Closing this issue, because it has been fixed in beta. Viewable at https://www.freecodecamp.rocks/learn/responsive-web-design/basic-html-and-html5/link-to-internal-sections-of-a-page-with-anchor-elements
