### ISSUE TITLE
Projects with an element having an id="global" causes failure in testing script

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#17958]
#### Describe your problem and - if possible - how to reproduce it
I discovered this problem when a camper noticed the test menu was not appearing in the camper's Technical Documentation project even though it was properly added. After dissecting the camper's HTML code, I discovered the camper had used an id="global" on one of their div, which seems to be the only thing causing the test script to fail.  Once I changed this element id to something other than "global", everything worked fine.

The test script file used for the project was https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js which is the current version being used by all the projects.

#### Add a Link to the page with the problem
I created a simple example which shows what happens when an element has an id="global" in the following JSFiddle link.

https://jsfiddle.net/hy3t8po4/2/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 68.0.3440.75 (Official Build) (64-bit)
* Operating System: Windows 8.1

#### If possible, add a screenshot here
**HTML code along with error messages in the console**
![image](https://user-images.githubusercontent.com/5313213/43475076-74643a42-94a9-11e8-814e-980729355cae.png)

**Comment by thecodingaviator** [comment]
@RandellDawson I think it's fixed now, it's working for me:
![image](https://user-images.githubusercontent.com/34807532/48851296-aca0cd00-edd0-11e8-888a-8eb68d29aba7.png)

So maybe you can close the issue?

**Comment by RandellDawson** [comment]
This has been fixed, so I am closing this issue.
