### ISSUE TITLE
Seed Readme file links do not work

### ISSUE THREAD

**Issue by lacivert** [freeCodeCamp/freeCodeCamp#17952]
#### Describe your problem and - if possible - how to reproduce it
I see this text on Contributing page:

> For more about creating challenges, see seed/README and seed/challenge-style-guide.md.

But the links do not work (and I don't know where they are)

#### Add a Link to the page with the problem
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version:  67
* Operating System:  MacOSX

**Comment by Nirajn2311** [comment]
@lacivert the seed readme has been moved to curriculum repo, which is where all the freeCodeCamp’s challenges will be.
