### ISSUE TITLE
"Run the test" button not working.

### ISSUE THREAD

**Issue by alouisa** [freeCodeCamp/freeCodeCamp#17957]
#### Describe your problem and - if possible - how to reproduce it

"Run the test" button not working. The "Reset Code" button does work as well as "Get a hint" and "Ask for help." When I hit "Run the test" nothing happens and I am left with 
"/*** Your test output will go here.*/" which never changes. This has happened already on a few of the lesson. I've skipped others in the past for this reason, but seem to keep finding more lessons with the same problem.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/chaining-if-else-statements

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.99
* Operating System: Apple

#### If possible, add a screenshot here

![screen shot 2018-07-31 at 10 08 13 am](https://user-images.githubusercontent.com/41756295/43475151-abc84334-94a9-11e8-8e2e-0d4eb3b961c0.png)

**Comment by ValeraS** [comment]
@alouisa Your code has an error on line 15. 'if' statement is missing.

**Comment by Nirajn2311** [comment]
@alouisa you can do what @ValeraS posted above or you can remove the condition for the last else as the number will have to be greater than or equal to 20 to run the last else statement or else it won’t run.

**Comment by rohitjain00** [comment]
I think this could be closed now.

**Comment by alouisa** [comment]
Thank you everyone!
