### ISSUE TITLE
Error on:  Applied Visual Design: Create a Horizontal Line Using the hr Element

### ISSUE THREAD

**Issue by revisualize** [freeCodeCamp/freeCodeCamp#17951]
#### Describe your problem and - if possible - how to reproduce it
When working on Applied Visual Design: Create a Horizontal Line Using the hr Element
I reset the lesson and added an `<hr>` tag to line 31 and tried to complete the lesson and it doesn't complete.

Example code:
```js
<style>
  h4 {
    text-align: center;
    height: 25px;
  }
  p {
    text-align: justify;
  }
  .links {
    text-align: left;
    color: black;
  }
  .fullCard {
    width: 245px;
    border: 1px solid #ccc;
    border-radius: 5px;
    margin: 10px 5px;
    padding: 4px;
  }
  .cardContent {
    padding: 10px;
  }
  .cardText {
    margin-bottom: 30px;
  }
</style>
<div class="fullCard">
  <div class="cardContent">
    <div class="cardText">
      <h4><s>Google</s>Alphabet</h4>
      <hr>
      <p><em>Google was founded by Larry Page and Sergey Brin while they were <u>Ph.D. students</u> at <strong>Stanford University</strong>.</em></p>
    </div>
    <div class="cardLinks">
      <a href="https://en.wikipedia.org/wiki/Larry_Page" target="_blank" class="links">Larry Page</a><br><br>
      <a href="https://en.wikipedia.org/wiki/Sergey_Brin" target="_blank" class="links">Sergey Brin</a>
    </div>
  </div>
</div>
```

Also changing the text to:
```js
<h4><s>Google</s>Alphabet</h4><hr>
      <p><em>Google was founded by Larry Page and Sergey Brin while they were <u>Ph.D. students</u> at <strong>Stanford University</strong>.</em></p>
```

Doesn't complete either.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-a-horizontal-line-using-the-hr-element

#### Tell us about your browser and operating system

* Browser Name:  Chrome and Firefox
* Browser Version: Latest
* Operating System: Windows 10

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/1588399/43371050-de794916-933e-11e8-9377-5aab83207703.png)

**Comment by johnkennedy9147** [comment]
this is fixed in https://github.com/freeCodeCamp/curriculum/pull/189
the fix wont go live till the next release
