### ISSUE TITLE
Compose React Components Challenge freezes while trying to code

### ISSUE THREAD

**Issue by nirmalathapa** [freeCodeCamp/freeCodeCamp#17965]
#### Describe your problem and - if possible - how to reproduce it
Under the frontend libraries certification React challenge where we have to compose React components freezes page. I am unable to click or write any code in the editor.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react/compose-react-components

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System: macOS High Sierra

#### If possible, add a screenshot here

![screen shot 2018-08-01 at 14 07 27](https://user-images.githubusercontent.com/1160546/43520808-4b2beb16-9594-11e8-8e28-1cf931eca576.png)

**Comment by nirmalathapa** [comment]
Yes I understand there is a mistake in my code. However, I try to close the browser and restart the chrome the problem is still there and I cannot reset the code.

**Comment by Nirajn2311** [comment]
Try clea I get all browser cache and cookies.

**Comment by nirmalathapa** [comment]
Clearing all the browser cache and cookies works. But this solution is only temporary. Isn't there other way to show error in code instead of freezing the browser?

**Comment by LovelyEmma** [comment]
class TypesOfFood extends React.Component {
constructor(props) {
super(props);
}
render() {
return (
<div>
<h1>Types of Food:</h1>
{ /* change code below this line */ }
<Fruits />
{ /* change code above this line */ }
<Vegetables />
</div>
);
}
};

**Comment by thecodingaviator** [comment]
@nirmalathapa Going to https://learn.freecodecamp.org/front-end-libraries/react/compose-react-components?run=disabled should fix it. I think this can be closed now.

**Comment by nirmalathapa** [comment]
I have checked it with all the possible wrong answer and it works :)

**Comment by dverdin83** [comment]
I have the same problem even after cache clearing. I haven't had this issue with any other challenges and I'm about halfway through the challenges.

**Comment by nirmalathapa** [comment]
try to use the incognito browser and see if it works. Also I had tested myself it work perfectly couple of months ago but don't know if something broke now and does not work
