### ISSUE TITLE
Display your learning progress in numbers

### ISSUE THREAD

**Issue by yeugen1** [freeCodeCamp/freeCodeCamp#17964]
#### Describe your problem and - if possible - how to reproduce it
Hello team,
 
On the main page: https://learn.freecodecamp.org/ we have a topic list with done lessons, but unfortunately we can see a progress in numbers.
I decided to implement a user script (tampermonkey/greasemonkey).

The main behavior of the script is:
1) Minimize all opened lists.
2) Expand all closed lists.
3) Gather data of done lessons.
4) Create a block on the top-right.
5) Fill a block with gathered data.
6) Add id to all main topics
7) Add hyperlink to the created link list for quicker navigation through the page

#### Add a Link to the page with the problem
Here is forum topic of an idea: 
https://forum.freecodecamp.org/t/display-your-learning-progress-in-numbers/213065

Here is a source code of user script:
https://github.com/yeugen1/JS/blob/master/freeCodeCamp/freeCodeCamp_navigation.js

I will add continually features (buttons+localstorage for alternative UX)

#### Tell us about your browser and operating system

* Browser Name: Firefox DE
* Browser Version: 62.0b13
* Operating System: Windows 10

#### If possible, add a screenshot here
![Image of example](https://discourse-user-assets.s3.amazonaws.com/original/3X/5/e/5e86e6222c62edc64417f32e0f020a9196af9257.png)

Thank you and have a nice day,
Yeugen

**Comment by raisedadead** [comment]
Hi this looks similar to what we have in discussion at the minute, feedback and pull requests are welcome.

See https://github.com/freeCodeCamp/freeCodeCamp/issues/17869 for the related issue.
