### ISSUE TITLE
Curriculum: looping back to "Hello Camper ... Go to Curiculum."

### ISSUE THREAD

**Issue by Pastshelfdate** [freeCodeCamp/freeCodeCamp#17962]
#### Describe your problem and - if possible - how to reproduce it
From this page, "https://www.freecodecamp.org/" I click either "Curriculum" at top near right, or the "Go to the Coding Curriculum" button, and all that happens is I get looped back to the same page, 
https://www.freecodecamp.org/
Sometimes, for a matter of seconds, I see what looks like it might be a list of curriculum topics, or an actual challenge, but then back to https://www.freecodecamp.org/, and "Welcome Camper."

I don't feel welcome at all, and this is too representative of my past experiences, though usually you keep me happily progressing for minutes, or even hours, before I hit a wall of code.

#### Add a Link to the page with the problem
https://www.freecodecamp.org/

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 61.0.1
* Operating System: Windows 10, "ver 1803, OS build 17134.165

#### If possible, add a screenshot here
![curriculumfailfcc](https://user-images.githubusercontent.com/16636239/43493686-3b577d64-94fd-11e8-8eb8-cb7efdeb250e.PNG)

**Comment by Juneezee** [comment]
@Pastshelfdate Have you tried going to [`](https://learn.freecodecamp.org/)

**Comment by huyenltnguyen** [comment]
@bharatgupta99 Could you try going to the curriculum page (https://learn.freecodecamp.org) directly, see if it would redirect you somewhere?

**Comment by nathanhannig** [comment]
might be an odd issue with the ocde not taking you to the first cirriculium
try this link
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements

**Comment by paulywill** [comment]
@Pastshelfdate I was also experiencing the same issue in Chrome, just cleared my cache and decided to log in with Email option and my progress appears to be back to normal and I'm no longer looping.

**Comment by thecodingaviator** [comment]
Guys, is this fixed now? For me it's working fine. If so, please close it @Pastshelfdate
