### ISSUE TITLE
Pair programmer's name field doesn't appear in Google Chrome 

### ISSUE THREAD

**Issue by ayondot** [FreeCodeCamp/FreeCodeCamp#1796]
Please, I recently discovered that when using my google chrome browser to access FreeCodeCamp, the pair programmer's name text-field where we we are asked to input "Your pair's username if pairing" doesn't appear. You may want to look into that issue.

**Comment by benschenker** [comment]
Thanks @ayondot,

I have been unable to replicate this.  What browser/OS are versions are you using.  Which page don't you see that text field? Can you post a screenshot?
