### ISSUE TITLE
Waypoint: Modify Array Data With Indexes issue

### ISSUE THREAD

**Issue by ilikepi31415** [FreeCodeCamp/FreeCodeCamp#1797]
Challenge http://www.freecodecamp.com/challenges/waypoint-modify-array-data-with-indexes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![image](https://cloud.githubusercontent.com/assets/13755735/9295405/c9d00d3e-443a-11e5-8dea-140ab5d1e57e.png)

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1793

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
