### ISSUE TITLE
Broken glitch link in first NPM challenge

### ISSUE THREAD

**Issue by tchan** [freeCodeCamp/freeCodeCamp#17971]
#### Describe your problem and - if possible - how to reproduce it
Per title, link is broken

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/
https://glitch.com/#!/import/github/freeCodeCamp/boilerplate-npm
```
Project Not Found
Maybe a typo? Or maybe it's been renamed?
```

**Comment by moT01** [comment]
Seems to be working for me, perhaps it has been fixed - are you still having problems @tchan ?

**Comment by tchan** [comment]
Looks like it's temperamental. Works for me now.

**Comment by sporifolous** [comment]
I'm encountering this same issue right now. When clicking the link, Glitch opens up, but I get a little red message on glitch that says "Arg, something went wrong. Try again? :@"

**Comment by mscanza** [comment]
Same, doesn't work.  I'm really disappointed with FCC on this section.

**Comment by RandellDawson** [comment]
@sporifolous When you say you can not clone the repo directly, how are you trying to do it?

@mscanza Which link are you trying?  What error message do you see when you click on the link?

**Comment by mscanza** [comment]
There is an important point FCC needs to make in the instructions.  They need to clarify that you must log into Glitch from your Github account. Otherwise it will not correctly import the files.  Works great now.

**Comment by RandellDawson** [comment]
Would you like to help us update the instructions for that challenge?

**Comment by mscanza** [comment]
Sure!

**Comment by RandellDawson** [comment]
I have reopened this issue, so we can discuss and finalize what the instructions should say.  Also, is this particular challenge the only challenge where this kind of thing would be an issue?  If not, where is the first such challenge, because that might be the better place to put it.  We could make a note, that starting with that challenge, all proceeding challenges would require the user to be logged into Glitch from GitHub.

**Comment by mscanza** [comment]
No, this is an issue with all challenges in the first couple sections.  Therefore I think the best place to be would be in the introductions of both.

Introduction to the Managing Packages with npm Challenges.  In the paragraph that talks about Glitch.  
Introduction to the Basic Node and Express Challenges

**Comment by RandellDawson** [comment]
Here is the current verbiage I see:
>Most developers prefer to install packages local to each project to create a separation between the dependencies of different projects. Working on these challenges will involve you writing your code on Glitch on our starter project. After completing each challenge you can copy your public Glitch url (to the homepage of your app) into the challenge screen to test it! Optionally you may choose to write your project on another platform but it must be publicly visible for our testing.
Start this project on Glitch using this link or clone this repository on GitHub! If you use Glitch, remember to save the link to your project somewhere safe!

I agree it is a bit confusing, because it seems like you do not have to use Glitch, but then it gives you Glitch links.  I need to check with some other collaborators to see if anyone else is already working on improving these challenge instructions.  Let me get back with you, but we will leave this open.

**Comment by moT01** [comment]
I moved away from specifying glitch in the descriptions/instructions when I worked on this PR https://github.com/freeCodeCamp/freeCodeCamp/pull/35422/files - So often it said something like... "do this in your glitch project", which I would change to just "do this in your project"

**Comment by RandellDawson** [comment]
@moT01 Well, we need to take a hard look at this intro section to make it less confusing for users and also make sure we let users know they must log into Glitch via GitHub, so the project template will work properly.

**Comment by moT01** [comment]
I think most of the backend has an introduction page that says campers can use "this glitch link" or whatever - perhaps just adding another sentence there that says "You must sign in to glitch with github for this to work." or something like that.

**Comment by mscanza** [comment]
Have you guys taken a look at the MongoDB challenges.  I have spent the last few days attempting and cannot even connect to Mongoose.  The uri looks different now as you can no longer get the mlab URI.  The current URI is: 
mongodb+srv://mscanza:password@fcc-vcnna.mongodb.net/test?retryWrites=true

I keep getting the following message:
(node:6705) UnhandledPromiseRejectionWarning: MongoNetworkError: connection 4 to fcc-shard-00-00-vcnna.mongodb.net:27017 closed

I have searched all the forums and can't seem to find anything relating to the new URI.

**Comment by thecodingaviator** [comment]
I think the main issue here has been fixed. If anybody is still facing any issue, please add an explanation and we'll reopen this. If there's a different issue, I'd encourage you to open a different PR.
:)

**Comment by themagicbean** [comment]
I'm not sure if this is the right place, but I still can't get FCC to recognize my glitch link for Node.js challenges:
https://glitch.com/edit/#!/brassy-exuberant-sesame?path=myApp.js%3A15%3A40 is logging to the console "Hello World" (am viewing it on Glitch)
https://www.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/meet-the-node-console - still won't pass

**Comment by scissorsneedfoodtoo** [comment]
Hi @themagicbean. To submit backend challenges, you need to submit the actual page, for example, https://brassy-exuberant-sesame.glitch.me/. To open the page in Glitch, just click "Show", then "In a New Window". 

After that, just copy and paste the URL into the "Solution" text field on the challenge's page. Then our test suite should be able to run the tests correctly.

**Comment by themagicbean** [comment]
Thank you.  Classic problem of "It doesn't work because I am not using it correctly."
