### ISSUE TITLE
D3: Updating Height Dynamically - Tests Not Passing

### ISSUE THREAD

**Issue by Ozymandias9000** [freeCodeCamp/freeCodeCamp#17976]
#### Describe your problem and - if possible - how to reproduce it
Tests are not passing with correct code. Curiously, the "The fifth div should have a height of 25 pixels" test is passing, but none of the others. DOM elements are rendering correctly with appropriate inline style.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/data-visualization/data-visualization-with-d3/update-the-height-of-an-element-dynamically/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 68
* Operating System: Chrome OS

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/22988962/43679036-f60b6e68-97d2-11e8-84ae-0e370c1755f1.png)

**Comment by Ozymandias9000** [comment]
Oddly enough, no. I find it very strange that I can get the fifth test to pass, but none of the others, no matter what I do.

**Comment by moT01** [comment]
yea, im not sure - did you try resetting the code and doing it again? is there any errors in the console?

**Comment by Ozymandias9000** [comment]
Yes to reset, no to errors. If it's a browser problem, that's an issue for people using Chromebooks like myself.

**Comment by evedes** [comment]
try to employ .attr() instead of style()

**Comment by clarkngo** [comment]
I got the same scenario as @Ozymandias9000 . Only the fifth test is passing.

Browser Name: Chrome
Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)
Operating System: MacOS Mojave Version 10.14.2

I tried completing the challenge in Firefox and it passed.
Similar users are having problems:
https://www.freecodecamp.org/forum/t/update-the-height-of-an-element-dynamically-data-visualization-with-d3/199226

**Comment by MomchilDeus** [comment]
```
.style('height', d => `${d}px`) 
```
does not work on Chromium - Version 75.0.3770.100 (Official Build) Arch Linux (64-bit)
works on Firefox 67.0.3

**Comment by Ieahleen** [comment]
my browser: Versione 77.0.3865.120 (Build ufficiale) (a 32 bit) on Windows 10 Home v1803

no test passes with callback `d => d + "px"`

**Comment by moT01** [comment]
Pretty sure the problem is similiar to the problem on https://github.com/freeCodeCamp/freeCodeCamp/issues/18045

**Comment by lasjorg** [comment]
Yep looks like yet another zoom bug with Chrome. We can check the inline styles set instead for the test. I will make a PR.
