### ISSUE TITLE
Spelling Mistake - Mutatable instead of mutable

### ISSUE THREAD

**Issue by todorare** [freeCodeCamp/freeCodeCamp#17975]
#### Describe your problem and - if possible - how to reproduce it

In the challenge [React: Create a Controlled Input](https://learn.freecodecamp.org/front-end-libraries/react/create-a-controlled-input) mutatable should be mutable.

#### Add a Link to the page with the problem

[React: Create a Controlled Input challenge](https://learn.freecodecamp.org/front-end-libraries/react/create-a-controlled-input)

#### If possible, add a screenshot here

<img width="450" alt="screen shot 2018-08-04 at 12 18 24" src="https://user-images.githubusercontent.com/5732080/43675962-b68ca5dc-97e0-11e8-9660-30dd25824e74.png">

**Comment by edkahara** [comment]
I opened a pull request that addresses this issue [here](https://github.com/freeCodeCamp/curriculum/pull/219)
