### ISSUE TITLE
Spelling error in Basic Node and Express - Get Route Parameter Input from the Client

### ISSUE THREAD

**Issue by sheikheddy** [freeCodeCamp/freeCodeCamp#17991]
#### Describe your problem and - if possible - how to reproduce it
it says 'communicate us' instead of 'communicate to us'
How to reproduce it? Just go to the page :P

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/apis-and-microservices/basic-node-and-express/get-route-parameter-input-from-the-client

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.99
* Operating System: Windows 10

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/30148602/43837262-0119f56e-9b29-11e8-86d0-f7f85f29656b.png)

**Comment by moT01** [comment]
its missing an `m` in communicate as well, - this is where the problem is => https://github.com/freeCodeCamp/curriculum/blob/dev/challenges/05-apis-and-microservices/basic-node-and-express.json#L190

**Comment by RyanPisuena** [comment]
Hello all parties involved,

Below is a pull request for the grammar edit for you two.

**Comment by halcyondays22** [comment]
Is this issue still needing to be solved?  I'd like to work on it if so!

**Comment by fatimah5** [comment]
This is my first contribution, I would like to try to fix this problem by replacing the word 
"comunicte us" to "communicate us".

Thank you.

**Comment by krbrennan** [comment]
This is a duplicate of issue #244. I submitted changes to this one but some other zealot fixed 50 typos so this current issue is either fixed or will be fixed very shortly.
