### ISSUE TITLE
Apis and Microservices Projects - Exercise Tracker: User Stories missing

### ISSUE THREAD

**Issue by ezioda004** [freeCodeCamp/freeCodeCamp#17998]
#### Describe your problem and - if possible - how to reproduce it
There are no User Stories provided for this project neither in the [glitch example](https://fuschia-custard.glitch.me/) nor in the [github repo](https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/).

However, I found the User Stories in one of the [forum posts](https://forum.freecodecamp.org/t/exercise-tracker-project-with-testable-user-stories-guinea-pigs-needed/73232).
Other API projects have user stories in both glitch example as well as in the github repo.
Example [URL Shortener](https://learn.freecodecamp.org/apis-and-microservices/apis-and-microservices-projects/url-shortener-microservice) project - 
* [glitch](https://thread-paper.glitch.me/) example
* [github repo](https://github.com/freeCodeCamp/boilerplate-project-urlshortener/)

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/apis-and-microservices/apis-and-microservices-projects/exercise-tracker/

**Comment by energydev** [comment]
I can look into doing a pull request at https://github.com/freeCodeCamp/boilerplate-project-urlshortener/ to add the User Stories to the ReadMe

**Comment by energydev** [comment]
I submitted the below PR to add the user stories to the readme file in the github repo https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/pull/6

**Comment by RandellDawson** [comment]
@ezioda004 Is this still an issue?

**Comment by moT01** [comment]
It looks like the user stories were added to the github boilerplate, but have not been imported to the glitch project.

**Comment by moT01** [comment]
I don't think the user stories need to be in the example project. They have been added to the boilerplate repo and the boilerplate glitch project.
