### ISSUE TITLE
"Fork me on GitHub" ribbon is positioned wrongly when error notification is displayed

### ISSUE THREAD

**Issue by admhlt** [FreeCodeCamp/freecodecamp#18]
If I try to view a FCC user by entering a URL (freecodecamp.com/namehere) and the user isn't found, an error is displayed when I return to the FCC page ("We couldn't find a Code Camper with that username."). The error bubble pushes down the "Fork me on GitHub" ribbon so that it isn't flush with the top navbar of the page.

![fcc-github-ribbon-error](https://cloud.githubusercontent.com/assets/6955296/5704620/4a16c9b4-9a41-11e4-8f69-5532764c53b8.png)

**Comment by terakilobyte** [comment]
Thanks for bringing this to our attention, we'll get a fix in shortly.

**Comment by QuincyLarson** [comment]
The fix would involve moving the ribbon into layout.jade and conditionally showing it on the home.jade view (otherwise we'd have to move the flash notification element down into each individual view). But we've decided to remove this element from our forthcoming simplified landing page.
