### ISSUE TITLE
Accept Privacy Terms page styling issues

### ISSUE THREAD

**Issue by willgorham** [freeCodeCamp/freeCodeCamp#18000]
#### Describe your problem and - if possible - how to reproduce it

On https://www.freecodecamp.org/accept-privacy-terms, the checkboxes and submit button styling are broken.

In the JS console, it looks like a jQuery dependency is missing: `Uncaught ReferenceError: $ is not defined at accept-privacy-terms:11`

#### Add a Link to the page with the problem
https://www.freecodecamp.org/accept-privacy-terms

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 67.0.3396.99
* Operating System: macOS 10.13.6

#### If possible, add a screenshot here
Here's a GIF:
<a href="https://cl.ly/2O3O1Y0h3B1w" target="_blank"><img src="https://d3vv6lp55qjaqc.cloudfront.net/items/3K2O113W1v0t021D1y03/Screen%20Recording%202018-08-09%20at%2004.41%20PM.gif" style="display: block;height: auto;width: 100%;"/></a>

**Comment by epatr** [comment]
To add to this, when I clicked the button it sent me to a page that just said:

> {"message":"We have updated your preferences. You can now continue using freeCodeCamp."}

**Comment by Berkeley19** [comment]
I'll try and send a pr soon for this

**Comment by raisedadead** [comment]
Fixed in #18027
