### ISSUE TITLE
Ordered and Unordered list can be empty

### ISSUE THREAD

**Issue by davinderpalrehal** [freeCodeCamp/freeCodeCamp#18007]
Probably not a big deal, but in the ordered and unordered list session the tests pass even if the list items are empty

https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-bulleted-unordered-list

* Browser Name: Chrome
* Browser Version: 69.0.3497.32 (Official Build) beta (64-bit)
* Operating System: Mac OS High Seirra

![screen shot 2018-08-12 at 11 25 26](https://user-images.githubusercontent.com/1188871/44000133-1138ebc4-9e23-11e8-8cb0-475cd525cb48.jpg)

**Comment by coder077** [comment]
Can this be counted as an actual bug or is this acceptable? If this is a bug then I can possibly work on it.

**Comment by aditijoshi14** [comment]
I feel like it is a bug and should be fixed. What do you guys think about it? @davinderpalrehal @raisedadead

**Comment by raisedadead** [comment]
Hi @aditijoshi14 !

Yes, I could reproduce this with:

```html
<h2>CatPhotoApp</h2>
<main>
  <p>Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
<ul>
  <li></li>
  <li></li>
  <li></li>
</ul>
</main>
```

Let's get this tested locally, and confirm if the bug exists on the current `master` branch which is to be released in the upcoming weeks.

If it does, sure we need to update the tests to check this use case.

**Comment by aditijoshi14** [comment]
@raisedadead I will do that and work on it.

**Comment by aditijoshi14** [comment]
@raisedadead Thank you for the response. I was able to reproduce this bug locally. Would you like me to work on it?

**Comment by raisedadead** [comment]
Sure thing. All yours! Happy contributing!

**Comment by aditijoshi14** [comment]
@raisedadead Is it possible for you to assign this issue to me? This will save us from any duplicate work.

**Comment by co16353sidak** [comment]
Hi, is anyone currently working on this issue? or can I have a go at it?
@raisedadead @aditijoshi14 ?

**Comment by raisedadead** [comment]
Hey @co16353sidak there are several issues that we could use your help on. Have a look on the open issue. Feel free to tag me or others from the mods team for queries, including pointers to codebase.

Can you check back on this specific issue in a few days? If @aditijoshi14 has not requested more time by then you could look into next week.

Thanks a lot for you help. Happy contributing!

**Comment by aditijoshi14** [comment]
@co16353sidak Hi, thank you for checking. I am currently working on it!

**Comment by co16353sidak** [comment]
Awesome @aditijoshi14, do tell me how it pans out.

**Comment by aditijoshi14** [comment]
@co16353sidak sure!

**Comment by aditijoshi14** [comment]
@raisedadead I was thinking of using regex to match the text inside <li> tags. I was just wondering if we should just accept alphabets(A-Za-z) or should we accept numbers and symbols as well?

**Comment by RandellDawson** [comment]
@aditijoshi14 I say they should probably contain anything except only white space characters.

**Comment by aditijoshi14** [comment]
@RandellDawson Thank you so much for your response. I will work on that.

**Comment by RandellDawson** [comment]
@aditijoshi14 If you get stuck, let me know.  I have come up with an assert which I think will work well.

**Comment by aditijoshi14** [comment]
@RandellDawson Thank you so much for asking. I am making some progress but I will definitely let you know if I get stuck.
