### ISSUE TITLE
"Intermediate Algorithm Scripting: Sum All Primes" contradictory text

### ISSUE THREAD

**Issue by eald51893** [freeCodeCamp/freeCodeCamp#18008]
In the FCC assignment "Intermediate Algorithm Scripting: Sum All Primes" the following lines of text are included (but in a different order).

_The provided number may **not** be a prime._

_Sum all the prime numbers up to and including the provided number._  
(how can you can sum all the prime numbers up to and **including** the provided number if the provided number may not be a prime number?)

_sumPrimes(977) should return 73156._     
(In this mandatory test a prime number is the provided number while the assignment text clearly states "The provided number may not be a prime.")

**EDIT: New Proposed solution:** 
Change the following line of text in the assignment description:
NEW: "The provided number might be a prime"
OLD: "The provided number may not be a prime."

**Comment by HadrienAllemon** [comment]
I don't think removing the line "The provided number may not be a prime." is the right solution. The line states that the provided number **may** be a prime, it does not say that it _won't_ be a prime, aka the provided number may or may not be a prime. However, including a bit of text that precise the line "sum all the primes numbers up to and including the provided number" might be usefull, for exemple : 

_Sum all the prime numbers up to the provided number, including it if it is a prime_. It is a bit redundant, english is definitly not my strong point.

**Comment by eald51893** [comment]
Thanks for your feedback. What do you think about my new proposed solution to improve the text?

**Comment by thecodingaviator** [comment]
@eald51893 What do you propose if you still propose something? Else please close the issue

**Comment by ojeytonwilliams** [comment]
How about the following:


> A prime number is a whole number greater than 1 with exactly two divisors: 1 and itself. For example, 2 is a prime number because it is only divisible by 1 and 2.  In contrast, 4 is not prime since it is divisible by 1, 2 and 4.
> - - -
> 
> Rewrite `sumPrimes` to return the sum of all prime numbers that are less than or equal to `num`.
> 

I think it's worth expanding a little on what is and isn't prime.  Also, by referencing `num` directly, it should be clear which primes we're interested in.

**Comment by moT01** [comment]
Sounds good to me @ojeytonwilliams

So to be clear - it should look like this...
```
#description
A prime number is a whole number greater than 1 with exactly two divisors: 1 and itself. For example, 2 is a prime number because it is only divisible by 1 and 2. In contrast, 4 is not prime since it is divisible by 1, 2 and 4.

#instructions
Rewrite sumPrimes to return the sum of all prime numbers that are less than or equal to num.

Remember to use Read-Search-Ask if you get stuck. Try to pair program. Write your own code.
```
