### ISSUE TITLE
Can't edit code on Google Pixel, code box doesn't respond to keyboard. Haven't been able to test the run test button yet.

### ISSUE THREAD

**Issue by linkbub** [freeCodeCamp/freeCodeCamp#18002]
The section we're you edit the code will call up the keyboard the first time you click it, but I am unable to edit anything. If I remove the keyboard from the screen, I am unable to call it back again. Using an original Google Pixel with up to date Android system. I'm using Brave browser and if I request a desktop site it appears to let me edit.

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by 1337M0nst3r** [comment]
this is strange, does it do the same on other browsers?

**Comment by linkbub** [comment]
Chrome seemed more promising but when I tried to go back and edit the code
I had just wrote, it wouldn't let me. Firefox let me write a little then
started duplicating words multiple times and wouldn't let me delete
characters. When I tried to delete the duplicate characters, once the word
was gone it would reappear.

**Comment by linkbub** [comment]
I think a warning or something could be helpful. I had noticed right away
that there wasn't much space to work with on my phone. I agree that
learning to code should be done from laptops and desktops. That's a rather
good reference about the Indy 500, maybe use that on the warning. Thanks
for getting back to me so quickly. I'll be working on the curriculum from
my laptop from now on.

**Comment by ArielLeslie** [comment]
As per the [manaco editor FAQ](https://github.com/Microsoft/monaco-editor/blob/master/README.md#faq)

> ❓ Is the editor supported in mobile browsers or mobile web app frameworks?
>
>No.

>❓ Why doesn't the editor support TextMate grammars?
>
>all the regular expressions in TM grammars are based on oniguruma, a regular expression library written in C.
the only way to interpret the grammars and get anywhere near original fidelity is to use the exact same regular expression library (with its custom syntax constructs)
in VSCode, our runtime is node.js and we can use a node native module that exposes the library to JavaScript
in Monaco, we are constrained to a browser environment where we cannot do anything similar
we have experimented with Emscripten to compile the C library to asm.js, but performance was very poor even in Firefox (10x slower) and extremely poor in Chrome (100x slower).
we can revisit this once WebAssembly gets traction in the major browsers, but we will still need to consider the browser matrix we support. i.e. if we support IE11 and only Edge will add WebAssembly support, what will the experience be in IE11, etc.

**Comment by raisedadead** [comment]
Hi everyone,

Thanks for your comments. I totally agree that development on mobile devices is really tough challenge for us. We have have put some thoughts on this. There is a new layout in works that will help in this regard, that said the editor itself will not be compatible for the foreseeable future.

I am closing this issue for now. Will create fresh issues when the development picks up.

Thanks and happy coding.
