### ISSUE TITLE
Typo in Basic Data Structures: Combine Arrays with the Spread Operator

### ISSUE THREAD

**Issue by halcyondays22** [freeCodeCamp/freeCodeCamp#18003]
#### Describe your problem and - if possible - how to reproduce it
In second paragraph, there are two "more"s before the word complex.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/combine-arrays-with-the-spread-operator

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 68.0.3440.106 (Official Build) (64-bit)
* Operating System: macOS High Sierra Version 10.13.6

#### If possible, add a screenshot here
![screen shot 2018-08-10 at 10 00 46 pm](https://user-images.githubusercontent.com/38671948/43987613-e26f2ba4-9ce8-11e8-9cb6-d48addb640d7.png)

**Comment by TomerPacific** [comment]
I'd like to be able to fix this issue as a first time contributor to this repository, if no one has any reservations.

**Comment by Nirajn2311** [comment]
@TomerPacific You may start working on the fix. The challenges files can be found in the curriculum repo.

**Comment by TomerPacific** [comment]
@Nirajn2311 ,
I have found where to fix the mistake and have made the correct fix, but when I check the status of my branch, there are no differences. Meaning, nothing has been changed.

I have gone to
`freeCodeCamp\node_modules\@freecodecamp\curriculum\dist\challenges\02-javascript-algorithms-and-data-structures`

and made the fix there. Is that the right place?

Can you help me out in figuring out what I am missing?

Just to clarify, I have managed to run the FCC environment.

**Comment by Nirajn2311** [comment]
@TomerPacific the challenges files are stored at 
https://github.com/freeCodeCamp/curriculum.
The file you are looking for to edit is 
https://github.com/freeCodeCamp/curriculum/blob/dev/challenges/02-javascript-algorithms-and-data-structures/basic-data-structures.json#L396

**Comment by TomerPacific** [comment]
Hey @Nirajn2311 ,

thanks for the quick reply.

I just want to make sure that what I am about to do is correct.

Since I only forked the freeCodeCamp/freeCodeCamp repository, I need to fork the freeCodeCamp/curriculum repository, create a new branch there, fix the typo and open a pull request in that repository?

**Comment by Nirajn2311** [comment]
@TomerPacific Bullseye my friend.

**Comment by amar633** [comment]
how to get rid of these unnecessary emails? mute not working. thanks

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by amar633** [comment]
I Want to unduscriiiiiiiiibbbbbbeee!!!!

**Comment by TomerPacific** [comment]
Hi @Nirajn2311 ,
I have created a pull request.
[PR](https://github.com/freeCodeCamp/curriculum/pull/239)

Thank you for all your help.

**Comment by Nirajn2311** [comment]
Issue moved to [freeCodeCamp/curriculum #248](https://github.com/freeCodeCamp/curriculum/issues/248) via [**ZenHub**](https://www.zenhub.com/)
