### ISSUE TITLE
Run the tests button

### ISSUE THREAD

**Issue by LeiCorre** [freeCodeCamp/freeCodeCamp#18006]
Describe your problem and - if possible - how to reproduce it

I have found at least one JavaScript challenge where the "Run the Tests" button is not working/active.  It is the challenge titled **"Basic JavaScript: Escape Sequences in Strings"**.  I have tried the page in both the latest version of Chrome and Firefox with the same results.  When I click the button it simply triggers no response, the other buttons such as "Reset All Code" are working fine, as are the other challenges I have tried.

Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/escape-sequences-in-strings/

Tell us about your browser and operating system

Latest versions of Chrome and Firefox

Operating System

Windows 7 Professional

**Update**
This is also present on the challenge titled "Basic JavaScript: Constructing Strings with Variables" and "Appending Variables to Strings"

**Comment by ValeraS** [comment]
"Run The Tests" button does not work if you have syntax errors in your code.

**Comment by rmfranciacastillo** [comment]
Running on:  Chrome 68 on Ubuntu 17.10 

"Run The Tests" button returned feedback without any errors on the console.

**Comment by RandellDawson** [comment]
Closing this issue, because it has gone stale.  

@LeiCorre, @rmfranciacastillo If either you are still having problems with this, please request us to reopen the issue.  Also, you should post your code over on the [forum](https://freecodecamp.org/forum) to see if anybody can help you conclude if your code is correct or not.
