### ISSUE TITLE
Search text box covers first line of code.

### ISSUE THREAD

**Issue by luxaeterne** [freeCodeCamp/freeCodeCamp#18009]
#### Describe your problem and - if possible - how to reproduce it
Search textbox in lessons covers first line of code.

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 68.0.3440.106 (Official Build) (64-bit)
* Operating System: Windows 10

![capture](https://user-images.githubusercontent.com/36870093/44005454-982fea42-9e28-11e8-9005-96d66bbb8c90.PNG)

**Comment by luxaeterne** [comment]
@Nirajn2311 You can fix this? I messed around with the dev tools and it appears it to be css related to html. font: 112.5%/1.45em? When I change it to 100% the search text box shrinks to a more proper size.

**Comment by Carine07** [comment]
Just to let you know that I had the same problem: impossible to read the first line of code of the program. Since I have authorized the algolia.net script (as I am using noscript firefox add-one), I do not have any problem. Maybe, one of your chrome extensions is faulty.

**Comment by Carine07** [comment]
Just to let you know that I have sometimes the same problem (cannot read the first line of the program) on firefox quantum. If I reload/refresh the page, I can see the first line

![freecodecamp](https://user-images.githubusercontent.com/35906185/45044866-97d65800-b071-11e8-846f-a581405aaa97.GIF)

**Comment by RandellDawson** [comment]
This appears to be a duplicate issue of #17814.  Please refer to that issue and let us know if you are still seeing this problem.  

Thank you.
