### ISSUE TITLE
Academy Honesty Policy column should be removed from settings once accepted

### ISSUE THREAD

**Issue by sanchitbansal10** [freeCodeCamp/freeCodeCamp#18014]
#### Describe your problem and - if possible - how to reproduce it
On the settings page, once Academy Honesty Policy is accepted should not the column be removed as the setting page is already very long..

#### Add a Link to the page with the problem
https://www.freecodecamp.org/settings
 

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/16536741/44137717-044cf536-a08f-11e8-9b12-13b754c43d81.png)

**Comment by Nirajn2311** [comment]
@sanchitbansal10 I don’t think it is better to remove it once it is accepted but we can change it to drop down so that if anyone wants to read it they can do so without any trouble.

**Comment by RandellDawson** [comment]
@raisedadead Is this something that might be added to the road map?  I personally do not think this feature is a needed.

**Comment by raisedadead** [comment]
Yes, I agree. We do not want to remove this section. However, we might re-arrange this section to be the second last item on the page, that is just before the danger zone section.

**Comment by raisedadead** [comment]
In all fairness this is there to remind users when submitting the certifications that they are are bound by the policy. So, I believe its in its correct location already.
