### ISSUE TITLE
Managing Packages with Npm Lesson 1 - Bad link for "Get a Hint"

### ISSUE THREAD

**Issue by jodylecompte** [freeCodeCamp/freeCodeCamp#18010]
#### Describe your problem and - if possible - how to reproduce it
The "Get a Hint" button for the challenge Managing Packages with Npm - How to Use package.json, the Core of Any Node.js Project or npm Package leads to a 404 page. 

#### Add a Link to the page with the problem
Challenge URL: https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package/

404 URL: https://guide.freecodecamp.org/certifications/apis-and-microservices/managing-packages-with-npm/how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package
#### Tell us about your browser and operating system

* Browser Name:  Google Chrome 
* Browser Version:  Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System:  Windows 10

**Comment by moT01** [comment]
Fixed
