### ISSUE TITLE
Bad looks in accept privacy terms page

### ISSUE THREAD

**Issue by kevinprakasa** [freeCodeCamp/freeCodeCamp#18017]
I think this page looks pretty untidy. Gonna work on this PR to fix this little issue.

Here it is the screenshot: 
![screenshot from 2018-08-16 00-32-47](https://user-images.githubusercontent.com/23476276/44163354-5c3d1380-a0ed-11e8-940a-535b2323ffd4.png)

**Comment by JohnTendik** [comment]
Related: 
https://github.com/freeCodeCamp/freeCodeCamp/issues/18000

Someone is working on a PR I think.

**Comment by Stef733** [comment]
PR submitted
