### ISSUE TITLE
Typo: Children don't inherit backgrounds

### ISSUE THREAD

**Issue by thecalicoder** [freeCodeCamp/freeCodeCamp#18025]
#### Describe your problem and - if possible - how to reproduce it
Not really an issue but it threw me off. In the visual design challenge linked below, the second paragraph states that the navigation bar inherits its background from the header. Well I wondered so I set the position of the navigation to relative and the top to 20px (and the header text color black so you can see the white text against the white body) and clearly the background of the nav isn't cyan, it's white. 

Children have transparent backgrounds. That's why they seem cyan against a parent with a cyan background. 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-tone-of-a-color

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: MacOS

#### If possible, add a screenshot here
![screen shot 2018-08-18 at 5 46 27 pm](https://user-images.githubusercontent.com/28523039/44304345-989b8a00-a30e-11e8-90b9-19d583bb8349.png)

**Comment by vallode** [comment]
Interesting wording. It wouldn't be right to say the children of an element inherit its background color.
The initial value of `background-color` is `transparent`  [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color)

The simplest solution to this would just be a change of wording

> All elements have a default `background-color` of `transparent`. Our `nav` element currently appears to be cyan, because the element behind it has a `background-color` set to that color. Add a `background-color`to the `nav`element so it uses the same cyan hue, but has 80% saturation and 25% lightness values to change its tone and shade.

**Comment by thecodingaviator** [comment]
Fixed in #19512

**Comment by thecodingaviator** [comment]
This was fixed in #19512 . @Bouncey / @Asjas  / @thecalicoder please close it
