### ISSUE TITLE
impossible to pass the test 'The anchor tag color should remain black' even though I didn't change it

### ISSUE THREAD

**Issue by KemPavel** [freeCodeCamp/freeCodeCamp#18028]
Hello,
It seems impossible to pass a test "The anchor tag color should remain black, only add CSS rules for the :hover state." I just added a following strings below the existed link styling: 
`  a:hover {
    color: blue;
  }`
I didn't change anything existed. 

Challenge - https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-hover-state-of-an-anchor-tag

Here is a screenshot
![anchor issue](https://user-images.githubusercontent.com/15628822/44313791-64fc5500-a41f-11e8-955c-b7b0ebc2d2b9.png)

**Comment by ntrupin** [comment]
Maybe change the hexidecimal #000 to “Black”?

**Comment by bipox** [comment]
I had to use chromium to pass the test, it wouldn't work in firefox for the same reason as stated in the first post.

I did try changing #000 to black to no avail.

**Comment by pandichitra** [comment]
yes! i couln't solve this in firefox but i was able to run this in googl chrome!!

**Comment by SethFalco** [comment]
I can vouch I've done the entire Responsive Web Design course on Firefox, and could pass every challenge/project.
I've just tested this solution now, and it's working for me. 🤔 

@pandichitra If you have time, would you be able to elaborate on what actually failed for you?

**Comment by pandichitra** [comment]
@SethFalco yeah i really don't know why ? But I could find the same problem as mentioned by @KemPavel. Once I tried doing it in chrome it didn't mention any all Passed .
<img width="947" alt="solution didn't pass" src="https://user-images.githubusercontent.com/42309745/118588883-e9d95080-b7bc-11eb-8b78-3cd3e3c8a649.PNG">
<img width="942" alt="passed" src="https://user-images.githubusercontent.com/42309745/118589067-4472ac80-b7bd-11eb-93d8-8cafc4b155fa.PNG">

**Comment by ShaunSHamilton** [comment]
I am going ahead and locking this conversation, because this issue is old, and the platform/tests have changed a lot.

Please feel free to open a topic on the [forum](https://forum.freecodecamp.org), or a new issue. Thank you.
