### ISSUE TITLE
Challenge Description Wording

### ISSUE THREAD

**Issue by alexbrotman** [FreeCodeCamp/FreeCodeCamp#1802]
Challenge http://freecodecamp.com/challenges/waypoint-iterate-with-javascript-while-loops has an issue.

Text reads, "Let's try getting a for loop to work by pushing values to an array." It should instead read, "Let's try getting a while loop to work by pushing values to an array."

**Comment by bugron** [comment]
@alexbrotman thanks for posting this issue!
@BerkeleyTrue seems this issue is solved and can be closed.


Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
