### ISSUE TITLE
an object after sign in

### ISSUE THREAD

**Issue by boudlal** [freeCodeCamp/freeCodeCamp#18024]
after i signed in and i accept the new privacy terms ..  the website return an object like that : 

![sans titre](https://user-images.githubusercontent.com/13233658/44304286-d2d94b80-a34f-11e8-8636-598354ab476b.png)

**Comment by box3x4** [comment]
same happened with me

**Comment by nathanhannig** [comment]
can you tell us the url address

**Comment by boudlal** [comment]
i don't remember the url address.
but after i accepted the new privacy terms  the website return the object above instead of redirect me to the home page,

**Comment by box3x4** [comment]
![screenshot from 2018-08-20 08-28-31](https://user-images.githubusercontent.com/11823051/44499462-5057d100-a65a-11e8-9585-44822f3d1684.png)

**Comment by raisedadead** [comment]
Needs to be reproduced locally. I can't confirm yet.
