### ISSUE TITLE
Code vulnerabilities

### ISSUE THREAD

**Issue by snehansh** [freeCodeCamp/freeCodeCamp#18031]
#### Describe your problem and - if possible - how to reproduce it
There are 237 vulnerabilities (97 low, 99 moderate, 39 high, 2 critical).
I want to try to fix a few. 

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System: 

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/35124383/44377349-fd4b1600-a4c1-11e8-9fbc-d191f349faf4.png)

**Comment by thecodingaviator** [comment]
@snehansh Can you please either elaborate on this issue or close it if fixed?

**Comment by snehansh** [comment]
closed
