### ISSUE TITLE
pomodoro test suite is too strict when checking for break-length, session-length and reset content

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#18036]
#### Describe your problem and - if possible - how to reproduce it
in this sample codepen created for the pomodoro clock challenge, the test suite fails to identify input fields that are being used to hold the break-length, session-length and to house the reset button.
https://codepen.io/hbar1st/pen/XPJKKo?editors=1100

This tells me the suite checks are too narrow in scope as they do not allow the use of form input fields which seem to be a natural fit for the pomodoro clock requirements.

The error for break-length for eg. states it cannot find a value of 5 even though *literally* the value attribute of the input tag is set:
Here's the start of one of the errors:
I can see an element, with corresponding id="break-length", which by default (on load) displays a value of 5. A value of 5 is not displayed by default: expected '' to equal '5' 
AssertionError: A value of 5 is not displayed by default: expected '' to equal '5'
    at o.c (https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js:205:1134)

#### Add a Link to the page with the problem
https://codepen.io/hbar1st/pen/XPJKKo?editors=1100

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 68.0.3440.106
* Operating System: Windows 10

**Comment by ValeraS** [comment]
Issue moved to [freeCodeCamp/testable-projects-fcc #548](https://github.com/freeCodeCamp/testable-projects-fcc/issues/548) via [**ZenHub**](https://www.zenhub.com/)

**Comment by RandellDawson** [comment]
@ValeraS Should we keep this open here or close it now?
