### ISSUE TITLE
Build a Personal Portfolio Webpage user story 11 problem 

### ISSUE THREAD

**Issue by km-py** [freeCodeCamp/freeCodeCamp#18037]
This is the error am getting.
Everything is working fine on my page.

Error:
3.The navbar should always be at the top of the viewport.
Script error. (:0)
Error: Script error. (:0)
at uncaughtException.i.onerror (https://cdnjs.cloudflare.com/ajax/libs/mocha/5.2.0/mocha.min.js:1:865 1)

 code so far
https://codepen.io/km-py/pen/wxVpLz?editors=0100 1

browser information:

User Agent is: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 UBrowser/7.0.185.1002 Safari/537.36.

Link to the challenge:
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage 2

**Comment by Nirajn2311** [comment]
@km-py you have made two `nav ul` properties. The first one should use your navbar which is an id in your html.
