### ISSUE TITLE
hr element bug 

### ISSUE THREAD

**Issue by Tunde-James** [freeCodeCamp/freeCodeCamp#18030]
#### Describe your problem and - if possible - how to reproduce it

Hello, I’m having some trouble with the code editor not accepting my answer though I am almost certain it’s correct. The instructions are to add a horizontal rule between the h4 and p elements, but an error appears each time reading “the hr tag should appear between the title and the paragraph”. Am I doing something wrong?

The code below contains the hr element as I have entered it.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-a-horizontal-line-using-the-hr-element/

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by ayerik** [comment]
A screenshot showing your code would help people spot the error.
________________________________

**Comment by Asjas** [comment]
@Tunde-James This is a duplicate issue. There is already a issue opened a week ago in the [Curriculum Repo](https://github.com/freeCodeCamp/curriculum/issues/247). https://github.com/freeCodeCamp/curriculum/issues/247

The issue has been fixed but it needs to be pushed to production for the fix to be applied.

**Comment by kundankumar26** [comment]
there is a bug in that code. you just put "p" tag after the "em" tag and it will pass the run test.

**Comment by Ashera138** [comment]
Should this and #247 be closed? I understand the change isn't live yet, but it has been fixed.

**Comment by RaspberryLime** [comment]
Any idea when the fix will be released? The workaround encourages people to use invalid HTML, and most posts sharing the workaround don’t make that clear.

**Comment by RaspberryLime** [comment]
Looks like this just got fixed. :)

**Comment by thecodingaviator** [comment]
@Tunde-James Its been fixed. Please close this issue

**Comment by Asjas** [comment]
I'll close this. Re-open if it isn't fixed but it appears to be :+1:
