### ISSUE TITLE
Small syntax error in CSS grid section: repeat(3, minmax(60px, 1fr));

### ISSUE THREAD

**Issue by danielrlc** [freeCodeCamp/freeCodeCamp#18034]
#### Describe your problem and - if possible - how to reproduce it
The instructions on this page say this:

In the preview, grid-template-columns is set to
repeat(auto-fill, minmax(60px, 1fr));

But the code window has this:
`/* change the code below this line */
grid-template-columns: repeat(3, minmax(60px, 1fr));
/* change the code above this line */`

Can someone confirm if this is just an error in the instructions, or perhaps a bug instead? The error stops the preview window showing the nice CSS grid effect described in the instructions.

(If it's just a text error, I'd like to fix this myself if I can.)

#### Add a Link to the page with the problem
[CSS Grid: Create Flexible Layouts Using auto-fill](https://learn.freecodecamp.org/responsive-web-design/css-grid/create-flexible-layouts-using-auto-fill/)

#### Tell us about your browser and operating system
* Browser Name: Chrome
* Browser Version: Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: macOS Sierra (10.12.6)

#### If possible, add a screenshot here
<img width="1440" alt="screen shot 2018-08-21 at 15 54 00" src="https://user-images.githubusercontent.com/8128944/44402897-bad61780-a55b-11e8-85d5-f6acbfc21fed.png">

**Comment by Nirajn2311** [comment]
@danielrlc yeah, it is a typo error.

**Comment by danielrlc** [comment]
@Nirajn2311 Thanks for confirming. I'll get this corrected.

**Comment by RandellDawson** [comment]
@ahmadabdolsaheb I noticed you made the initial commit for this challenge and others when the curriculum was its own repo.  Can you shed some light on what the original intent was for the Challenge Seed code, challenge description, and instructions?  I just want to make sure the changes on PR #26088 are not changing the original purpose of this challenge.

Thanks.

**Comment by ahmadabdolsaheb** [comment]
@danielrlc thanks for catching this issue and @bannon-tanner for working on the PR. I looked into the challenges before and after this one, I think the best solution here would be to only replace "in the preview," with "Imagine". That being said, no one can shed more light on this than @moT01 who played a major role in designing these challenges. What would be a good fix here @moT01?

**Comment by moT01** [comment]
Thanks for the shout out, @ahmadabdolsaheb. I made a request for changes on the PR, if one of you want to go check out my suggestions and make sure that sounds like a good change, that would be great.

**Comment by RandellDawson** [comment]
@moT01 Sorry for now recognizing your contribution on this challenge.

**Comment by moT01** [comment]
That's alright, I didn't make the commits.

**Comment by danielrlc** [comment]
Thanks for fixing this @RandellDawson
