### ISSUE TITLE
It's also better to check the output as well

### ISSUE THREAD

**Issue by gvsrusa** [freeCodeCamp/freeCodeCamp#18035]
#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System: 

#### If possible, add a screenshot here

```
function makeClass() {
  "use strict";
  /* Alter code below this line */
  class Vegetable {
    constructor(name) {
      this.name = name;
    }
  }
  /* Alter code above this line */
  return Vegetable;

}
const Vegetable = makeClass();
const carrot = new Vegetable('carrot');
console.log(carrot.name); // => should be 'carrot'
```

**Comment by Nirajn2311** [comment]
@gvsrusa what exactly is your problem, also could you post more details?

**Comment by gvsrusa** [comment]
```
function makeClass() {
"use strict";
/* Alter code below this line /
class Vegetable {
}
/ Alter code above this line */
return Vegetable;

}
const Vegetable = makeClass();
const carrot = new Vegetable('carrot');
console.log(carrot.name); // => should be 'carrot'
```
It passes the test with the above code. i.e without even having the constructor. 
It will be great to have a test case for checking the output as well rather than only the syntax.

**Comment by ezioda004** [comment]
Hi @gvsrusa,

Thanks for opening this PR. Seems like its fixed in one of the previous PR's https://github.com/freeCodeCamp/curriculum/pull/190

Hence I'm closing this issue.

Feel free to open this issue again if you think its still a problem.

Happy coding!
