### ISSUE TITLE
Error: Cannot find module 'babel-register' while seeding database

### ISSUE THREAD

**Issue by Aks1610** [freeCodeCamp/freeCodeCamp#18039]
Getting below error while executing 
"npm run prelint-js && echo '/****/' && echo 'Seeding Database' && echo '/****/' && SEEDING=true node seed/index.js && echo '/****/' && echo 'Seeding Completed' && echo '/****/'"
in git BASH

![image](https://user-images.githubusercontent.com/13673447/44460861-559e2700-a62c-11e8-9ccf-e8d3248b0957.png)

**Comment by zolbayars** [comment]
Did you run all of the previous steps? (Such as `npm install`)

**Comment by Aks1610** [comment]
Yes I did.

**Comment by GursimarSinghChopra** [comment]
First wholly remove NodeJS and npm from your system.
Then install latest Node version 10.12.0 and npm 6.4.1
Then try if it doesn't work then delete nodesource.list file in your system and try again above steps

**Comment by raisedadead** [comment]
We have resolved this specific issue with local setup. Please re-clone and make a fresh installation. A few other issues in the setup are still being worked upon. We will post an update in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) when the local is 100% ready.

Thanks
