### ISSUE TITLE
"Responsive Web Design Principles: Create a Media Query" test is not forgiving.

### ISSUE THREAD

**Issue by psyperl** [freeCodeCamp/freeCodeCamp#18049]
#### Describe your problem and - if possible - how to reproduce it
"Responsive Web Design Principles: Create a Media Query" test is not forgiving.

the test wouldn't pass
```
  @media ( max-height: 800px ) {
    p {
      font-size: 10px;
    }
  }
```

it would only pass
```
  @media (max-height: 800px) {
    p {
      font-size: 10px;
    }
  }
```

difference is an extra spaces inside the parenthesis.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/create-a-media-query/

#### Tell us about your browser and operating system

* Browser Name: Safari
* Browser Version: Version 11.1.2 (13605.3.8)
* Operating System: macOS High Sierra Version 10.13.6

#### If possible, add a screenshot here

![screen shot 2018-08-24 at 22 38 24](https://user-images.githubusercontent.com/28307592/44593768-81690a80-a7ee-11e8-8e9b-dbd6f01877a6.png)

**Comment by psyperl** [comment]
I just realized that the learn repo is separated from main repo now..
So i created the corresponding issue in the learn repo.

**Comment by jel111** [comment]
It also will not pass in Safari no matter how it is formatted. I tried multiple ways and then decided to try FFDev Edition and it worked. Copy and Pasted the code from Safari to FF so was exactly the same in each browser.
