### ISSUE TITLE
Text conveying wrong information.Lock an Element to the Browser Window with Fixed Positioning

### ISSUE THREAD

**Issue by dsandeepchary** [freeCodeCamp/freeCodeCamp#18043]
[Lesson](https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/lock-an-element-to-the-browser-window-with-fixed-positioning) in the curriculum has a wrong typo which conveys wrong information, i.e, Written 'absolute' where it should be 'fixed' in the second paragraph.

**Comment by TomerPacific** [comment]
@dsandeepchary ,
I actually don't think this is a typo.
The first paragraph explains the use and meaning of the position attribute of fixed,
The second paragraph elaborates more on this issue by stating that as opposed to absolute positioning, the fixed positioning locks the element in it's place.

**Comment by joshalling** [comment]
@TomerPacific I think you are correct, however the wording is a little bit ambiguous. It might be good to clarify it like this:

> One key difference ~~from the~~ **between the fixed and** absolute positions is that ~~the~~ **an** element **with a fixed position** won't move when the user scrolls.

**Comment by TomerPacific** [comment]
@joshalling,
you mind if I go ahead and fix this issue?

**Comment by joshalling** [comment]
@TomerPacific Go right ahead! :+1: :+1:  

I'll keep an eye out for your pull request.

**Comment by TomerPacific** [comment]
@joshalling ,
I have created a [PR](https://github.com/freeCodeCamp/curriculum/pull/268)
