### ISSUE TITLE
Debugging: Use typeof to Check the Type of a Variable

### ISSUE THREAD

**Issue by lalov1** [freeCodeCamp/freeCodeCamp#18046]
There is a spelling error on the following page:
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/debugging/use-typeof-to-check-the-type-of-a-variable

The following sentence:
Especially take care when you're accessing and working with external data in the form of a JavaScript object (JSON).

Should read:
Especially ~~take care~~ when you're accessing and working with external data in the form of a JavaScript Object **Notation** (JSON).

I would love to fix this on my own if someone could tell me how....

**Comment by joshalling** [comment]
@lalov1 I think it is a little bit more clear if you say:

>**Be especially careful** when you're accessing and working with external data in the form of a JavaScript Object Notation (JSON).

The challenge seed code lives in the **freeCodeCamp/curriculum** repo. If you would like to make this change, then follow the steps in the [CONTRIBUTING.md](https://github.com/freeCodeCamp/curriculum/blob/dev/docs/CONTRIBUTING.md) guide to get yourself set up. If you have any questions, feel free to reach out to me on [gitter](https://gitter.im/joshalling).

**Comment by lightcowboy** [comment]
Is this available to fix. I wouldn't mind starting with something like this just to start looking into the code.

**Comment by Nirajn2311** [comment]
@joshalling I think it should be 
**Be careful especially**
