### ISSUE TITLE
ES6: Use Destructuring Assignment (Test does not recognize solution)

### ISSUE THREAD

**Issue by rmfranciacastillo** [freeCodeCamp/freeCodeCamp#18042]
#### Describe your problem and - if possible - how to reproduce it
On Problem: ES6: Use Destructuring Assignment to Assign Variables from Nested Objects

I've added the solution` const { tomorrow: { max: maxOfTomorrow } } = LOCAL_FORECAST;`

as explained in the hints but the second test: `nested destructuring was used` does not recognize the nested destructuring

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-nested-objects/

#### Tell us about your browser and operating system

* Browser Name: Chrome 
* Browser Version: 68.0.3440.106 (64-bit)
* Operating System: Ubuntu 17.10

**Comment by joshalling** [comment]
@rmfranciacastillo It looks like you are destructing the constant rather than using the passed parameter in your function. Change `LOCAL_FORECAST` to `forecast` and you should be good.

**Comment by rmfranciacastillo** [comment]
That makes sense. 

I was testing it following the hints in here: https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-nested-objects.

It was a little misleading though.

**Comment by joshalling** [comment]
You're right. The solution given in the hint is incorrect. I just created an issue in the guide repo to get that fixed (freeCodeCamp/guide#8416). Also, if anyone wants to add another test that passes a different object as the `forecast` that would be a welcome change.

**Comment by RandellDawson** [comment]
@joshalling Can you validate if this issue has been resolved on the freecodecamp.rocks beta site?

**Comment by joshalling** [comment]
@RandellDawson I think this should have been closed a long time ago, as the curriculum was always working as intended. The issue was that the guide article was wrong.

**Comment by RandellDawson** [comment]
@joshalling Has the guide article been fixed?

**Comment by joshalling** [comment]
Yes it has
