### ISSUE TITLE
"Resume curriculum" link on homepage results in 404 error

### ISSUE THREAD

**Issue by jdahdah** [freeCodeCamp/freeCodeCamp#18040]
#### Describe your problem and - if possible - how to reproduce it

The "Go to the coding curriculum" button on the homepage currently points to this non-existant page:

https://learn.freecodecamp.org/front-end-libraries/react/set-state-with-this.setstate

when it should be pointing here:

https://learn.freecodecamp.org/front-end-libraries/react/set-state-with-this-setstate/

Looks like the `.` in `this.setstate` is not properly being converted to a `-`.

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 68.0.3440.106
* Operating System: MacOS 10.13.6

**Comment by nathanhannig** [comment]
Nice find, this also impacts 
https://learn.freecodecamp.org/front-end-libraries/react/access-props-using-this-props

**Comment by nathanhannig** [comment]
Found the issue

freeCodeCamp and learn repos have dasherize functions that do not match.
**_\freeCodeCamp\server\utils\index.js_**
```
export function dasherize(name) {
  return ('' + name)
    .toLowerCase()
    .replace(/\s/g, '-')
    .replace(/[^a-z0-9\-\.]/gi, '')
    .replace(/\:/g, '');
}
```
**_\learn\utils\index.js_**
```
exports.dasherize = function dasherize(name) {
  return ('' + name)
    .toLowerCase()
    .replace(/\s/g, '-')
    .replace(/[^a-z0-9\-\.]/gi, '')
    .replace(/\./g, '-')
    .replace(/\:/g, '');
};
```
There also appear to be a **dashify** function in \freeCodeCamp\common\utils\index.js that appears like it needs to also be updated.

My concern is the periods are being turned to dashes, but they both repo's also have **unDasherize** functions that would turn dashes to spaces and not return the period. I am not sure of the impact of this.

**Comment by ojeytonwilliams** [comment]
I can take a look at this, if no one else is on the case.  Presumably the freeCodeCamp dasherize just needs to match learn, but I'll take a look at how unDasherize is used and see if there any side effects.

**Comment by raisedadead** [comment]
Hi @ojeytonwilliams 

We are looking forward to this with https://github.com/sindresorhus/slugify

What we would want, is to wait for us bring in the learn code over here as being done on `next` branch and then tackle this one go. You can update your PR #18059 once we are ready for you.

I am going to close the other PRs and Issues.
