### ISSUE TITLE
6

### ISSUE THREAD

**Issue by Glogang9** [freeCodeCamp/freeCodeCamp#18051]
#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by Nirajn2311** [comment]
@Glogang9 could you provide more details of your issue?

**Comment by ksaimohan2k** [comment]
Sir I'm interested in c language proficiency
I'm interested if u can  provide questions
On the above subject

**Comment by Asjas** [comment]
@ksaimohan2k The freeCodeCamp Github issues are used to report problems with the codebase and it is not used for questions on programming languages. Please use the [freeCodeCamp Gitter](https://gitter.im/FreeCodeCamp/HelpFrontEnd) for questions on programming languages.
