### ISSUE TITLE
Wrap Radio Buttons in a fieldset Element for Better Accessibility - Description need more code tags

### ISSUE THREAD

**Issue by nathanhannig** [freeCodeCamp/freeCodeCamp#18054]
#### Describe your problem and - if possible - how to reproduce it
The last description does not have code tags surrounding html elements like is done in most other challenges.

`"Camper Cat wants information about the ninja level of his users when they sign up for his email list. He's added a set of radio buttons, and learned from our last lesson to use label tags with <code>for</code> attributes for each choice. Go Camper Cat! However, his code still needs some help. Change the div tag surrounding the radio buttons to a fieldset tag, and change the p tag inside it to a legend."`

Should become in my opinion

`"Camper Cat wants information about the ninja level of his users when they sign up for his email list. He's added a set of radio buttons, and learned from our last lesson to use label tags with <code>for</code> attributes for each choice. Go Camper Cat! However, his code still needs some help. Change the <code>div</code> tag surrounding the radio buttons to a <code>fieldset</code> tag, and change the <code>p</code> tag inside it to a <code>legend</code>."`

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/wrap-radio-buttons-in-a-fieldset-element-for-better-accessibility

**Comment by Marijunjnja** [comment]
PR #289 fixes this

**Comment by nathanhannig** [comment]
https://github.com/freeCodeCamp/curriculum/pull/289

**Comment by nathanhannig** [comment]
great job
