### ISSUE TITLE
Fix heatmap on profile page.

### ISSUE THREAD

**Issue by sidshrivastav** [freeCodeCamp/freeCodeCamp#18053]
Heatmap on profile page showing nothing.

* Browser Name: Chrome 
* Browser Version: 68.0.3440.106 
* Operating System: Ubuntu 18.04

Right now it look like this..

![screenshot from 2018-08-28 01-20-21](https://user-images.githubusercontent.com/28773690/44682362-c85e3680-aa60-11e8-9c50-eeae638ccdac.png)

Is there any setting to enable this or just a bug?

**Comment by Asjas** [comment]
Hi @sidshrivastav.

There is already a issue open for this https://github.com/freeCodeCamp/freeCodeCamp/issues/17320. Can you please close this duplicate issue?
