### ISSUE TITLE
Add full stack certification to the profiles view.

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#18052]
We have added the ability to claim full stack certifications in #17968, this certification should also show up on the users profile page.

The changes need to be done in https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/routes/Profile/components/Certificates.jsx

**Comment by sanchitbansal10** [comment]
Working on it..

**Comment by Simon2828** [comment]
Hi @sanchitbansal10 could I help with this?
