### ISSUE TITLE
Broken icons (minor)

### ISSUE THREAD

**Issue by Mortiferr** [freeCodeCamp/freeCodeCamp#18064]
#### Describe your problem and - if possible - how to reproduce it
Missing breadcrumb icons.

#### Add a Link to the page with the problem
[https://guide.freecodecamp.org/certifications/front-end-libraries/react/manage-updates-with-lifecycle-methods](https://guide.freecodecamp.org/certifications/front-end-libraries/react/manage-updates-with-lifecycle-methods
)

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: Version 69.0.3497.72 (Official Build) beta (64-bit)
* Operating System: macOS High Sierra

#### If possible, add a screenshot here

<img width="643" alt="screen shot 2018-08-30 at 10 17 44 am" src="https://user-images.githubusercontent.com/13282318/44861355-f8166580-ac3d-11e8-8937-e120ea39c836.png">

**Comment by Nirajn2311** [comment]
@jude-lawson You may start working on this but you only have to remove the line `content: '\f105';`

**Comment by jude-lawson** [comment]
Hello 👋 

I've gone ahead and made the PR to freeCodeCamp's guide repo: https://github.com/freeCodeCamp/guide/pull/8451

Please let me know if there are any changes that I can make or additional steps I should take.

Thank you!
