### ISSUE TITLE
Basic JavaScript: Introducing Else If Statements

### ISSUE THREAD

**Issue by marciorblanco** [freeCodeCamp/freeCodeCamp#18068]
#### Describe your problem and - if possible - how to reproduce it

I know that this is not a big deal, but I was following the example and getting errors all the time. There is an extra bracket after the "else" statement in the example provided by FCC.

**ORIGINAL**
if (num > 15) {
  return "Bigger than 15";
} else if (num < 5) {
  return "Smaller than 5";
} else **{  // this extra bracket causes an error when testing** 
  return "Between 5 and 15";
}

**TESTING**
function testElseIf(num){
if (num > 15) {
  return "Bigger than 15";
} else if (num < 5) {
  return "Smaller than 5";
} else **{ // this extra bracket causes an error when testing**
  return "Between 5 and 15";
}
testElseIf(10)
Uncaught SyntaxError: Unexpected end of input

**SOLUTION**
if (num > 15) {
  return "Bigger than 15";
} else if (num < 5) {
  return "Smaller than 5";
} else **// delete extra bracket**
  return "Between 5 and 15";
}

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/introducing-else-if-statements

#### If possible, add a screenshot here

![capture](https://user-images.githubusercontent.com/42203461/44895277-edb6a300-acf3-11e8-829c-9ee4219c01dd.PNG)

**Comment by Nirajn2311** [comment]
@marciorblanco Your function code is missing a closing bracket, so the else opening bracket will cause an error. Also the example is working fine, maybe you might have missed a bracket somewhere.

**Comment by marciorblanco** [comment]
@Nirajn2311 Thanks. I forgot that bracket. Even I tested many times I couldn't see the problem. Thanks again.
