### ISSUE TITLE
Run test is not working

### ISSUE THREAD

**Issue by misacorn** [freeCodeCamp/freeCodeCamp#18063]
#### Describe your problem and - if possible - how to reproduce it
I put the code into the page and click "Run the tests", but nothing moves. I tried to erase the cache and reload the page but none of it works. 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/change-the-prototype-to-a-new-object/

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by Nirajn2311** [comment]
@misacorn could you post a screenshot of your browser console and the details of the browser you are using

**Comment by misacorn** [comment]
I attached the screenshot and I'm using Chrome 68 whatsmybrowser.org/b/PXWK8YL
![image](https://user-images.githubusercontent.com/35432501/44849402-a6cc9d00-ac62-11e8-863d-50557cf90763.png)

**Comment by Nirajn2311** [comment]
@misacorn Your numLegs property is not properly declared.
It should be 
>numLegs: 4,

**Comment by ojeytonwilliams** [comment]
@misacorn It's not exactly a feature, no.  What's going on is the user submitted code in the editor first gets evaluated.  This sets up the environment that the tests can be run in.  However, if there's a syntax error (as in this case) the evaluation throws an error and stops the test process before it really starts.

**Comment by ezioda004** [comment]
Hi @misacorn,

Thanks for opening this issue. As explained above, the code get evaluated for syntax before compilation and running the tests.

Since this is not a real issue, I'm closing this. 
Feel free to open a new one in future.

Happy coding!
