### ISSUE TITLE
Feature request: show certification progress from within each challenge

### ISSUE THREAD

**Issue by robinmetral** [freeCodeCamp/freeCodeCamp#18062]
This feature request is similar to #17869 but applies to the individual coding challenges (instead of the portfolio page).

As a learner, I often find myself going back to the Curriculum page to see whether I'm far or not from finishing my current certification section (for example "Basic Javascript" in "Javascript Algorithms And Data Structures ").

It would be very useful (and motivating) to know my progress while I'm solving coding challenges!

The simplest solution would probably be plain numbers (see the challenge's title):

![Show certification progress on coding challenge](https://user-images.githubusercontent.com/35560568/44840846-33c82400-ac6c-11e8-9f47-432a1898e545.png)

But eventually, a more visual progress bar would be amazing!

What do you think?

**Comment by zolbayars** [comment]
Great feature. I'm working on it.

**Comment by robinmetral** [comment]
Great @zolbayars, let me know if there's anything I can help with!

**Comment by robinmetral** [comment]
Any news @zolbayars ?

**Comment by DoviMaj** [comment]
Lets do it!!

**Comment by robinmetral** [comment]
Yes please 🎉

**Comment by moT01** [comment]
Any progress here @zolbayars?

**Comment by moT01** [comment]
I'm really not sure it would get approved to be merged as no core members gave the okay to add it.

**Comment by moT01** [comment]
Closing this as stale. And honestly, I'm not in favor of this feature. I think it will add more unnecessary clutter to an already limited space. If anyone disagrees, feel free to comment and we can reopen this.

**Comment by robinmetral** [comment]
@moT01 honestly, I disagree. I think that this would make the experience of learning on freeCodeCamp better.

About your comment on cluttering, I assume you're referring to the screenshot in the initial post. I am not suggesting we add the progress indicator in parentheses, this was an illustrative minimal example. This issue is about the general idea and feature request, the design for it is an implementation detail (and we can start thinking about it when we get a green light). I'm convinced that there are ways to build this feature without cluttering the interface.

It's definitely up for discussion, but I don't think that we should dismiss the idea just because no core members gave a green light, yet.

In my opinion, this deserves a discussion.

**Comment by moT01** [comment]
Alright, lets open it back up.

Here's a screenshot of something a little more streamlined...
<img width="607" alt="Screen Shot 2019-11-13 at 11 11 08 AM" src="https://user-images.githubusercontent.com/20648924/68787002-57c01d00-0606-11ea-87ff-ccc98ffdbb9c.png">

Anyone else want to weigh in on if this is a feature we want to add?

**Comment by RandellDawson** [comment]
So if I user skipped the first 10 lessons in the Basic JavaScript section and completed the 11th challenge, you all want it to show `(1 of 110)` or `(11 of 110)`?  

These are all optional challenges and have no bearing on obtaining the certifications.  I also don't like the idea of appending anything else to the already lengthy title.  I personally believe all this will do is have users going to the forum and saying "I am having trouble with challenge number 20".  If we go with a progress indicator (like the first one I posted above in the question), this is going to become a mess on the forum.  Beside, the progress can be found on the user's profile if it is that important to know.

**Comment by ojeytonwilliams** [comment]
One possibility to reduce clutter and maybe address @RandellDawson's concerns is to have it just be a linear progress bar.  So, if you've done half of it, it's half full.

Another reason to avoid a numeric display is that it might be off-putting to see just how many there are.  Even knowing that each one is pretty easy, the idea that you have to do 110 of them doesn't sound great.

**Comment by moT01** [comment]
What about a progress bar in the completion modal? There's plenty of room in there.

**Comment by ojeytonwilliams** [comment]
The completion modal is a great call.

I was also wondering if it would look good/unbearably cheesy to have an animated progress bar.  Something to visually indicate that you are getting somewhere.  I'm not sure, though, displaying a percentage might just be better.

**Comment by moT01** [comment]
![Nov-14-2019 19-22-38](https://user-images.githubusercontent.com/20648924/68909590-67c62280-0714-11ea-98c8-6fc90b43a8a1.gif)

Hey @raisedadead, before I go any further with this - is anything along these lines something we would consider adding? It needs some work yet so it would look better than this.

**Comment by raisedadead** [comment]
I am ok with the progress bar on the completion modal, but @QuincyLarson will have to sign off on this before you start work on this.

**Comment by QuincyLarson** [comment]
@moT01 I like your completion bar. It would be nice if we could animate it filling up like we've animated the checkmark.

1. We animate the checkmark
2. we animate the progress bar

Also, I would keep the checkmark centered. We don't need the name of the current challenge in the modal - just the name of the section.

And while you're in there, perhaps you could increase the font size of the congratulatory text up top.

**Comment by moT01** [comment]
Update: This is where I ended up yesterday...
![Nov-16-2019 19-06-32](https://user-images.githubusercontent.com/20648924/69001472-7a6f6180-08a4-11ea-85e9-478a6b564a5f.gif)

I'll post another gif here with the challenge name gone and some bigger text up top so we can see a comparison.

**Comment by moT01** [comment]
Still working on animating the progress bar...
![Nov-18-2019 08-37-26](https://user-images.githubusercontent.com/20648924/69061456-bd355480-09de-11ea-8a5a-7dbcde9b651f.gif)

**Comment by ahmadabdolsaheb** [comment]
@moT01 does the percentage of on progress bar refers to the percentage of the challenges completed in that section?

**Comment by moT01** [comment]
yes

**Comment by moT01** [comment]
close to finalized... I think
![Nov-19-2019 08-54-13](https://user-images.githubusercontent.com/20648924/69157985-5c278280-0aab-11ea-9ec3-449d5d400450.gif)

**Comment by raisedadead** [comment]
Nice work @moT01 !
