### ISSUE TITLE
The menu is opened when loading the Curriculum

### ISSUE THREAD

**Issue by SofianeDjellouli** [freeCodeCamp/freeCodeCamp#18061]
Hi,

The menu is always opened when loading [the Curriculum](https://learn.freecodecamp.org/) on the first title and the first subtitle. I think it's the first interaction I had with it. It happens even if I sign out and on mobile (Iphone).

* Browser Name:  Chrome
* Browser Version: Latest
* Operating System: Windows

![image](https://user-images.githubusercontent.com/38258952/44812243-ffeeef00-abd6-11e8-9535-fda4eac83b85.png)

**Comment by thecodingaviator** [comment]
@iamj4james Please go ahead

**Comment by ritute** [comment]
I think a good experience here would be to expand the section where you completed your most recent challenge, and in the case where you haven't completed any, none would open.

**Comment by ritute** [comment]
This PR might fix this issue: #35421

**Comment by moT01** [comment]
Closing as duplicate of https://github.com/freeCodeCamp/freeCodeCamp/issues/34236
