### ISSUE TITLE
Technical Documentation Project - Test Error

### ISSUE THREAD

**Issue by rachelnicole** [freeCodeCamp/freeCodeCamp#18070]
I've been streaming going through the freeCodeCamp curriculum, and came across a bug today. 

https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-technical-documentation-page 

During this project, the user story for `User Story #4: Each section element with the class of main-section should also have an id that corresponds with the text of each header contained within it. Any spaces should be replaced with underscores (e.g. The section that contains the header "Javascript and Java" should have a corresponding id="Javascript_and_Java").`

When adding in content for my sections, sometimes there was punctuation in the title. When the tests run, they fail if I've taken the punctuation out of the slugs I've created. 

![freecodecamp-responsiveweb](https://user-images.githubusercontent.com/228230/44935871-6b080500-ad40-11e8-935d-4be01461d6be.PNG)

It would probably be helpful to add some content to the user story letting people know not to use punctuation in class and id names, and to have the test parse out the punctuation when users are creating the url slugs for their links. 

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: Windows 10 Home

**Comment by TurtleWolf** [comment]
Similar, I had to rename my sections.. I had a `&` tag in one of my titles.

**Comment by akmalist** [comment]
Same thing here. Had to remove ** ? ** on my titles. 

https://codepen.io/akmalist/full/vzzdxp/

**Comment by RandellDawson** [comment]
@tbushman Are you aware of such issues?

**Comment by tbushman** [comment]
@RandellDawson @rachelnicole You should not need to omit special characters from your `id`s.  
Having tested:  
`<a class="nav-link" href="#Introduction!@#$%^&*()?&" rel="internal"><li>Introduction!@#$%^&*()?&</li></a>`  
with ``` <section class="main-section" id="Introduction!@#$%^&*()?&">
    <header>Introduction!@#$%^&*()?&</header>```

**Comment by RandellDawson** [comment]
@tbushman So maybe the challenge instructions and/or the project tests should give show this disclaimer?

**Comment by tbushman** [comment]
@RandellDawson OK

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
