### ISSUE TITLE
 npm run only-once not working

### ISSUE THREAD

**Issue by kartikpandey2** [freeCodeCamp/freeCodeCamp#18074]
I forked freecodeCamp and cloned to my pc. 
I followed steps in the section "Set Up freeCodeCamp" 
but on running npm run only-once it throws error

**"SEEDING' is not recognized as an internal or external command"**,
operable program or batch file.

then I googled and found a similar issue and found running "npm run prelint-js && echo '/****/' && echo 'Seeding Database' && echo '/****/' && SEEDING=true node seed/index.js && echo '/****/' && echo 'Seeding Completed' && echo '/****/'" will solve the problem.
But  same error is thrown  "'**SEEDING' is not recognized as an internal or external command**,
operable program or batch file."

I also tried running "node seed" command it also throws an error
"**Error: Connection strategy not found**"

node version: 8.11.4
npm version: 5.6.0
windows: 10

**Comment by zolbayars** [comment]
As I've mentioned [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/17693#issuecomment-416985050), you should try to run the command separately: 

> Run just the `npm run prelint-js`
Add `SEEDING=true` into your `.env` (Don't forget to remove it before running npm run develop)
Run `node seed/index.js`

**Comment by kartikpandey2** [comment]
Thanks@zolbayars
