### ISSUE TITLE
Fullstack certificate shows wrong link

### ISSUE THREAD

**Issue by frank-rui** [freeCodeCamp/freeCodeCamp#18076]
The fullstack certificate contain wrong link at the bottom.

> Verify this certification at: https://www.freecodecamp.org/certification/frank-rui/responsive-web-design

<img width="1499" alt="screen shot 2018-09-03 at 05 56 19" src="https://user-images.githubusercontent.com/27864196/44961146-6e68df80-af3e-11e8-9fb7-24452eb5c324.png">

**Comment by frank-rui** [comment]
On my certificate, its still shows responsive-web-design link.

**Comment by raisedadead** [comment]
Hi @frank-rui it sometimes takes us a couple days to deploy the fixes on the server. Thanks for your patience.

**Comment by frank-rui** [comment]
@raisedadead Thank you. I can confirm that It's now been displayed correctly.
