### ISSUE TITLE
News page link not in navigation bar on learn.freecodecamp.org

### ISSUE THREAD

**Issue by jarikmarwede** [freeCodeCamp/freeCodeCamp#18072]
#### Describe your problem and - if possible - how to reproduce it
The link to the news page that has been added to the navigation bar on www.freecodecamp.org is not added to the navigation bar on [learn.freecodecamp.org](https://learn.freecodecamp.org).

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 61.0.2
* Operating System: Windows 10

![screenshot_2018-09-01 welcome to learn freecodecamp](https://user-images.githubusercontent.com/33765260/44943777-7acd2b00-adcc-11e8-816b-d3a526bd82c8.png)

**Comment by zolbayars** [comment]
I think you should open this issue in the **learn**'s repo: https://github.com/freeCodeCamp/learn

**Comment by jarikmarwede** [comment]
Oh, right. I didn't know there were multiple repositories.
