### ISSUE TITLE
Fix stale data in freeCodeCamp search

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#18082]
freeCodeCamp's search has stale data. Currently it links to "applied" responsive web design projects, which results in a 404. If you remove the "applied-" from the URL it works fine. So we should update the index.

![page_not_found___freecodecamp_and_responsive_web_design_projects_-_build_a_tribute_page___learn_freecodecamp _](https://user-images.githubusercontent.com/985197/45001811-24134d00-af96-11e8-8f87-01a6e6ec2217.png)

**Comment by moT01** [comment]
Closing in favor of duplicate https://github.com/freeCodeCamp/freeCodeCamp/issues/17304
