### ISSUE TITLE
Wrong use of this.setState in "React: Use State to Toggle an Element"

### ISSUE THREAD

**Issue by JulienDemarque** [freeCodeCamp/freeCodeCamp#18084]
#### Describe your problem and - if possible - how to reproduce it
The test suite accepts the following when it shouldn't (because setState is asynchronous) and the instruction gives no hint of the correct way: 
toggleVisibility(){
    this.setState({visibility: !this.state.visibility});
  }
whenever the state is used to calculate the new state, the following syntax should apply:
toggleVisibility(){
    this.setState(state => ({visibility: !state.visibility}));
  }
for reference: https://reactjs.org/docs/state-and-lifecycle.html

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react/use-state-to-toggle-an-element

#### Tell us about your browser and operating system

* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by GiaFil7** [comment]
My solution, which passed all challenges, was this:
`toggleVisibility(){ 
    this.state.visibility = !this.state.visibility;
  }`
However, the button didn't work. When I used the solution suggested by @JulienDemarque , the button worked.

**Comment by JulienDemarque** [comment]
`toggleVisibility(){ this.state.visibility = !this.state.visibility; }` is definetly wrong. You should always use setState to change the state. Otherwise React won't know it should render. 
but
`this.setState({visibility: !this.state.visibility});` would in most case work but is wrong.
Here is the explanation from the official documentation:

"State Updates May Be Asynchronous
React may batch multiple setState() calls into a single update for performance.

Because this.props and this.state may be updated asynchronously, you should not rely on their values for calculating the next state.

For example, this code may fail to update the counter:

// Wrong
`this.setState({
  counter: this.state.counter + this.props.increment,
});`
To fix it, use a second form of setState() that accepts a function rather than an object. That function will receive the previous state as the first argument, and the props at the time the update is applied as the second argument:

// Correct
`this.setState((state, props) => ({
  counter: state.counter + props.increment
}));`
We used an arrow function above, but it also works with regular functions:

// Correct
`this.setState(function(state, props) {
  return {
    counter: state.counter + props.increment
  };
});`"

**Comment by joshalling** [comment]
It looks like we are using timeouts in the test suite, and it is giving enough time for the state to update before the next toggle happens. I'll look into this and see if I can get it fixed.

**Comment by u1001932** [comment]
Would like to take this on. I'm having trouble finding the test suite though (this is my first time contributing to FCC).

**Comment by awareness481** [comment]
A way to fix this issue without changing too much of the exercise would be by passing `this.state.visibility` as a value to the toggleVisiblity function

```js
import React from 'react'

class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      visibility: false
    };
    this.toggleVisibility = this.toggleVisibility.bind(this);
   }
  toggleVisibility(prev) {
    this.setState({
      visibility: !prev
    });
  }
  render() {
    if (this.state.visibility) {
      return (
        <div>
          <button 
            onClick={() => this.toggleVisibility(this.state.visibility)}
          >
            Click Me
          </button>
          <h1>Now you see me!</h1>
        </div>
      );
    } else {
      return (
        <div>
          <button onClick = {() => this.toggleVisibility(this.state.visibility)}>Click Me</button>
        </div>
      );
    }
  }
};
```

The if statement here becomes redundant however, so I would suggest refactoring to something like: 

```js
      return (
        <div>
          <button 
            onClick={() => this.toggleVisibility(this.state.visibility)}
          >
            Click Me
          </button>
          { this.state.visibility ? <h1>Now you see me!</h1> : "" }
          
        </div>
```

Reference: https://reactjs.org/docs/lifting-state-up.html

**Comment by awareness481** [comment]
@raisedadead if you or another collaborator agreed on my [suggested changes](https://github.com/freeCodeCamp/freeCodeCamp/issues/18084#issuecomment-489518168)  I could go ahead and submit a PR

**Comment by raisedadead** [comment]
Yes, let's get a PR in. Thanks for your work so far. Looking forward to the pull request.
