### ISSUE TITLE
Investigate loopback-connector-mongodb upgrade to latest version

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#18081]
This issue should be investigated on the `next` branch

**Comment by snehansh** [comment]
I want to take this issue.

**Comment by babyccino** [comment]
Hi I'm interested in helping out. Would I be able to take this issue?

**Comment by felivalencia3** [comment]
Hey. Its my first time working open source but I have worked a few times on loopback with a mongoDB so direct me to the issue and ill try my best

**Comment by felivalencia3** [comment]
So from what I see a large part of the freeCodeCamp Structure is built off loopback models so I am guessing that it was built either in Version 3 or an early Version 4 of loopback

**Comment by Bouncey** [comment]
@felivalencia this issue is on our `next` branch.

A brief overview of what we are doing is removing all rendering from loopback and is in it purely as an API server (gatsby/netlify will handle our client app). While sorting out our dependencies early on in the project I found that an upgraded version of the connector wasn't playing nice. Though I can't remember the error, sorry. 

A while ago we migrated from v2 to v3 of loopback. We have a pile of technical debt with respect to tests and "work-arounds" that completely negate the loopback framework. Both of these things I am trying to address on this branch. It may be more feasible yo tackle this once we have a test suite in place, but feel free to have a go.

Any help would be greatly appreciated :+1:

**Comment by SunflowerPKU** [comment]
@babyccino @artoodeeto  @felivalencia3  Hey. I am doing a research about helping newcomer make contribution to OSS projects. I found that you all show interested in solving this issue, but unfortunately it failed. Could you tell me why you didn't contribute successfully.  Your reply are important to me. Thanks.
