### ISSUE TITLE
Links on lesson pages appear as regular text. No visual cues that they are links

### ISSUE THREAD

**Issue by zberwaldt** [freeCodeCamp/freeCodeCamp#18087]
#### Describe your problem and - if possible - how to reproduce it

Links on lesson pages are the same as regular text and there is no visual indication that they are links.
So if you don't use a mouse to track your place while reading, or you just never wonder "I wonder if any of these words are links" and stumble across the link, you never know they are there.

#### Add a Link to the page with the problem
[Mongoose lesson as an example](https://learn.freecodecamp.org/apis-and-microservices/mongodb-and-mongoose/create-a-model)

#### Tell us about your browser and operating system

* Browser Name: Mozilla Firefox Nightly
* Browser Version: 63.0a1
* Operating System: Windows 10

**Comment by Nirajn2311** [comment]
The links are in green color.

**Comment by Nirajn2311** [comment]
There is a [PR(learn/#255)](https://github.com/freeCodeCamp/learn/pull/255) to fix this issue.
