### ISSUE TITLE
Enhancement request: remove title from Ask for Help forum template

### ISSUE THREAD

**Issue by ArielLeslie** [freeCodeCamp/freeCodeCamp#18088]
#### Describe your problem and - if possible - how to reproduce it
As a forum moderator, I would like to request that the forum template that users get when they click the Ask for Help button be modified. Currently, it puts the name of the challenge as the title. This is problematic for two reason. Firstly, we are trying to encourage users to create descriptive titles for their posts. Secondly, since the forum does not allow for duplicate posts with the same name, most users just button-mash some letters or numbers at the end of the title or just add variations of "<<<<<help" at the end.

**Comment by hilliarj** [comment]
Should this issue be closed since there is a merge already resolving the issue?

**Comment by hilliarj** [comment]
Shouldn't this issue be closed since there is already a resolution that is merged with the master branch?

**Comment by Nirajn2311** [comment]
@ArielLeslie @hilliarj This issue is being closed as the PR linked above resolved it.
