### ISSUE TITLE
Typo in OOP challenge

### ISSUE THREAD

**Issue by JohnnyBizzel** [freeCodeCamp/freeCodeCamp#18091]
**Challenge**: Remember to Set the Constructor Property when Changing the Prototype

**Problem**
For the Dog constructor is says
`numLegs: 2,`
Can we change it to say `numLegs: 4` ?
**Link**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/remember-to-set-the-constructor-property-when-changing-the-prototype/

**Comment by erictleung** [comment]
@JohnnyBizzel sounds like a reasonable change to me! :+1: 

The curriculum part of the site is in another repo, https://github.com/freeCodeCamp/learn, so changes/fixes for this will need to be made over there. I'd recommend closing this issue and opening this same issue over there.

**Comment by geeseyj** [comment]
I can tackle this one. 🙂

**Comment by erictleung** [comment]
@geeseyj now that the curriculum is within this main repository, the file you'll need to fix is here

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/object-oriented-programming/remember-to-set-the-constructor-property-when-changing-the-prototype.english.md

**Comment by annezhou920** [comment]
i'll take this on!

**Comment by Asjas** [comment]
There is a PR #18616 that is fixing it. @ezioda004 just needs to review and merge it. It's currently assigned to him.

**Comment by annezhou920** [comment]
Thanks for letting me know. @ezioda004 should assign himself to this issue then and claim it, otherwise, I wouldn't have known.

**Comment by Asjas** [comment]
Hey @annezhou920. No problem at all.

Just for future reference. To see if a PR has been opened for an issue you'd usually see a reference to it in an issue thread. 

Above in this issue thread, for instance, you'll see a message with the text `jefferson2z referenced a pull request that will close this issue`. That is how you can tell if there has already been a PR opened for an issue. 

@ezioda004 is a reviewer, like me. We don't assign ourselves the issues, only the PRs that we review.

Happy contributing :smile:
