### ISSUE TITLE
Cash Register Challenge - Weak Test Cases

### ISSUE THREAD

**Issue by jperbark** [freeCodeCamp/freeCodeCamp#18097]
#### Describe your problem and - if possible - how to reproduce it

The purpose for this thread is to notify that test cases for the Cash Register challenge might be considered weak, as the problem can be solved with a simple greedy algorithm (that would be taking the biggest currency available possible in every step until reaching the amount asked).

It would be a proper way to answer if each bigger currency is multiple of every smaller one, but not the case here (as we have both QUARTERs and DIMEs).

For example, a **_0.3 change_** is not reachable if my CID is **_[[DIME, 0.3], [QUARTER, 0.25]]_** and I start stacking the only quarter in the first step. It’s a fancy example, as it seems pretty obvious to catch in our minds, but it could be crazily different to approach the algorithm for covering it correctly (i.e.: recursion, dynamic programming).

A classic greedy approach is passing all the tests at this moment, and being a Project for JS Certification, would be important to strengthen these tests. It's not hard to imagine campers going through this kind of solution. Example above would make a great contribution.

> checkCashRegister(0.2, 0.5, [["PENNY", 0], ["NICKEL", 0], ["DIME", 0.3], ["QUARTER", 0.25], ["ONE", 0], ["FIVE", 0], ["TEN", 0], ["TWENTY", 0], ["ONE HUNDRED", 0]]) should return {status: "OPEN", change: [["DIME", 0.3]]}.

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/cash-register

**Comment by JohnnyBizzel** [comment]
I always thought one of the problems with this challenge is that there are 4 possible statuses instead of 3.
The 3 being "OPEN", "CLOSED", "INSUFFICIENT_FUNDS".
The 4th status I have is "Correct change not available" in the case where we have enough money in the till but don't have the correct denominations to give exact change.

**Comment by JESii** [comment]
It may be an "edge case" in real life (I ran a cash register at Walgreens when I was out of high school and we always had rolls of coins to deal with a situation like this). However, edge cases in software testing are what make for robust testing and -- eventually -- robust software. What @jperbark prop0sed is exactly what's needed.

**Comment by pmurph0305** [comment]
Given the specifications of the test, and the included denominations chart, it is incorrect for a solution to return INSUFFICIENT FUNDS in this case. If the challenge was to only pass the specific test cases as opposed to meet the specifications of the problem, one could check for each test case, and return the appropriate response.

The added difficulty would be making sure the nickle + penny cid is enough to make up the difference before using a quarter.

An appropriate test in this case could be:

`checkCashRegister(3.7, 5, [["PENNY", 0], ["NICKEL", 0], ["DIME", 0.3], ["QUARTER", 0.75], ["ONE", 5], ["FIVE", 0], ["TEN", 0], ["TWENTY", 0], ["ONE HUNDRED", 0]]) should return {status: "OPEN", change:[["ONE", 1], ["DIME", 0.3]]}`

The beginner solution would also have to be changed to something that passes the test as well, as currently it does not.

**Comment by Twaha-Rahman** [comment]
Any progress on this issue? If a PR needed, I'd gladly like to help!

**Comment by rmariac** [comment]
I’m having issues on the tribute challenge. I cannot get my images to load in the test browser on codepen, and I am having trouble understanding the user stories. Are they required or can I type it how I’d like? Should I follow the source code for the example tribute page or not?

-Reyna Cobb

**Comment by ShaunSHamilton** [comment]
As this issue has gone stale, and I have not seen anything similar come up on the forum or otherwise, I am going to close it as such.

Feel free to bring up the discussion again, and this can be reopened.
