### ISSUE TITLE
CSS Grid: Create Grids within Grids

### ISSUE THREAD

**Issue by theMillerCode** [freeCodeCamp/freeCodeCamp#18099]
#### Describe your problem and - if possible - how to reproduce it
Challenge: CSS Grid: Create Grids within Grids - Passes the test script without any code or any code  being entered.  To recreate, just reset the code and then run the test.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/css-grid/create-grids-within-grids

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 69.0.3497.81 (Official Build) (64-bit)
* Operating System: Windows 10

**Comment by deadndark** [comment]
Hey, if it still needs work I will be happy to do it.

**Comment by CodingSolo** [comment]
@theMillerCode , @pradhyumn94 

There is already a issue  in the Curriculum Repo.  [freeCodeCamp/curriculum#198](https://github.com/freeCodeCamp/curriculum/issues/198#issue-345617901)
The issue has been fixed but it needs to be pushed to production for the fix to be applied.

@theMillerCode could you close this issue.

Thank you.
