### ISSUE TITLE
Sass: Store Data with Sass Variables

### ISSUE THREAD

**Issue by ilhamjulianto** [freeCodeCamp/freeCodeCamp#18092]
#### Describe your problem and - if possible - how to reproduce it
```
<style>
  $text-color:red;
  
  .header{
    text-align: center;
  }
  .blog-post h2 {
    color: $text-color;
  }
</style>

<h1 class="header">Learn Sass</h1>
<div class="blog-post">
  <h2>Some random title</h2>
  <p>This is a paragraph with some random text in it</p>
</div>
<div class="blog-post">
  <h2>Header #2</h2>
  <p>Here is some more random text.</p>
</div>
<div class="blog-post">
  <h2>Here is another header</h2>
  <p>Even more random text within a paragraph</p>
</div>

Your .blog-post element should have a </code>color</code> of red.
Your h2 elements should have a </code>color</code> of red.
```

False or True? that's True but the system say that's "blablabla...."
Please fix that's, if I false, I apologize about my Report
And Thank You so Much

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/sass/store-data-with-sass-variables/

#### Tell us about your browser and operating system

* Browser Name: Mozilla, Chromium
* Browser Version: unknown
* Operating System: Tealinux

**Comment by SpiritusSancti5** [comment]
**Tell us what's happening:**
This doesn't make one tiny bit of sense.


**Your code so far**
Code that works:
```html

<style type='text/sass'>
  
  $text-color: red;
  .header{
```

Code that doesn't work:

```html

<style type='text/sass'>
  $text-color: red;

  .header{
```

I think the script should check for the colour value and not the regex.

I had a guess there's a check only for the regex so i looked at the layout of the code. For some unknown reason there's a bias to have a space between the style tag and the css styling, but no more spaces until the closing style tag. So i figured i need to leave first line blank and then type in the one liner, obviously with perfect tab count before the line.

So why is this checked based on regex? The challenge is how good i am at guessing your prefered code formatting and structuring. :/

**Comment by thecodingaviator** [comment]
These issues most probably have been fixed and would be pushed to production? @ilhamjulianto Please close the issue

**Comment by RandellDawson** [comment]
@ilhamjulianto Your `style` tag is missing `type='text/sass'`, so that is a coding issue on your end.

@SpiritusSancti5 Just tested having no space between the opening `style` tag and the `$text-color: red;` line and passes the applicable test. It seems your issue has been fix according to the latest [beta](https://www.freecodecamp.rocks/learn/front-end-libraries/sass/store-data-with-sass-variables)

I am closing this issue for now, but if you are still experiencing problems, please request it be opened again.
