### ISSUE TITLE
Bug in freecodecamp functional programming section

### ISSUE THREAD

**Issue by KravMaguy** [freeCodeCamp/freeCodeCamp#18104]
#### Describe your problem and - if possible - how to reproduce it

 I sat over this for a bit trying to figure out why the average wasn’t coming out to what the exercise required. So i messed around a bit. Only after the code passed realized it wanted the average of all the movies by a certain director, and I fixed it. however
this monstrosity did pass. even though it shouldn’t, because it doesnt do what the exercise requires… Just saying…

```js
var averageRating;

var arr=[];
var rating = watchList.map(function(obj){ return arr.push(parseFloat(obj.imdbRating));
})
console.log(arr);
var averageRating= Math.floor((arr.reduce(function(a,b){
return a+b;
},)/arr.length+0.1555)*1000)/1000;
```

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/use-the-reduce-method-to-analyze-data

#### Tell us about your browser and operating system
Chrome, Windows 10
* Browser Name: 
* Browser Version: 
* Operating System:

**Comment by jfitzsimmons** [comment]
I'm going to take stab at this as long as there aren't any objections.

**Comment by shabab477** [comment]
Hi it has been 21 days since then so I decided to fix the issue because I was having a slow work day. :smiley:. Hope you didn't mind.
