### ISSUE TITLE
Issue with CDN file.

### ISSUE THREAD

**Issue by TheMarco77** [freeCodeCamp/freeCodeCamp#18102]
![cdn_2018_september](https://user-images.githubusercontent.com/29189997/45259862-236b2400-b3a5-11e8-9456-5f22de56b397.png)
![cdn_2018_september](https://user-images.githubusercontent.com/29189997/45259869-367df400-b3a5-11e8-8194-ebb6058f351b.png)

#### Describe your problem and - if possible - how to reproduce it

(After discussing this issue with an experienced Dev the answer why I am having issues with my CDN is below)

` Tell them. Because their JS is minified, it's all on one line. 
The only thing I can tell you is that the error starts around character 585.`

#### Add a Link to the page with the problem
https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js

#### Tell us about your browser and operating system

* Browser Name: 
Chrome
Firefox

* Browser Version: 
69.0.3497.81 (Official Build) (64-bit)
61.0.1 (64-bit)

* Operating System: 
Windows 10

**Comment by TheMarco77** [comment]
Here is a screenshot. Hope it helps.
Thanks in advance 

![cdn_2018_september](https://user-images.githubusercontent.com/29189997/45259854-ea32b400-b3a4-11e8-84e5-656900e490c4.png)

**Comment by parramorej** [comment]
If you do a Google search using 
```
cdn bundle.js mocha not loaded yet site:forum.freecodecamp.org
```
you'll see a number of FCC forum posting on this warning as well.

**Comment by thecodingaviator** [comment]
@TheMarco77 Is it's just about the warnings, they'll happen, please close the issue otherwise please explain what you want to happen not just state screenshots

**Comment by RandellDawson** [comment]
Hi @TheMarco77 ,

As there has been no response from your end for a while, we are closing this issue.

Feel free to request this issue to be reopened if you have new information.

Happy Coding!
