### ISSUE TITLE
localhost://3000 returns: "Cannot GET /"

### ISSUE THREAD

**Issue by PreetSangha** [freeCodeCamp/freeCodeCamp#18101]
1. am trying to install freedcodecamp for standalone operation on windows 10 64bit following the instructions https://forum.freecodecamp.org/t/how-to-clone-and-setup-the-free-code-camp-website-on-a-windows-pc/19366

2.  Have installed and am running
 - **Node v10.8.0**
 - **Npm 6.4.1**
 - **mongodb  v4.0.2**
 - also have git running from the command line with no issues, so cloned the repo and started with **npm install**, which was fine.

3. First step that failed was the the seeding issue 
![image](https://user-images.githubusercontent.com/15098094/45244920-00615580-b34e-11e8-9c46-a8ad037045b6.png)
which I was able to correct with this commant **node seed/index.js**

4. I now have an issue running **npm run develop**
![image](https://user-images.githubusercontent.com/15098094/45244983-56ce9400-b34e-11e8-9bbf-eea5b33a6a85.png)
Looking at the log it seems to be a gulp issue: 
![image](https://user-images.githubusercontent.com/15098094/45245036-9f864d00-b34e-11e8-9295-f02f1e81d995.png)

5. Doing some googling led me to: https://github.com/blheli-configurator/blheli-configurator/issues/151 where they suggested that I needed to **npm install natives**, which then allowed **npm run develop** to run and start the services on port 3001 
![image](https://user-images.githubusercontent.com/15098094/45246209-27228a80-b354-11e8-80b4-cfed2381170d.png)

![image](https://user-images.githubusercontent.com/15098094/45246166-efb3de00-b353-11e8-9e08-601dbcb8eb63.png)

![image](https://user-images.githubusercontent.com/15098094/45245551-fb51d580-b350-11e8-8776-8bfb9e0ae0cf.png)

6. **But I couldn't get the FCC server working on localhost://3000**
![image](https://user-images.githubusercontent.com/15098094/45246250-5f29cd80-b354-11e8-92a0-88aa89aea44d.png)

**Comment by raisedadead** [comment]
We have resolved this specific issue with local setup. Please re-clone and make a fresh installation. A few other issues in the setup are still being worked upon. We will post an update in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) when the local is 100% ready.

Thanks.

PS: Please conform to the docs for correct versions of node.

**Comment by KirkhapAuto** [comment]
Thanks, are the instructions on  https://forum.freecodecamp.org/t/how-to-clone-and-setup-the-free-code-camp-website-on-a-windows-pc/19366 correct now?

**Comment by raisedadead** [comment]
@KirkhapAuto See [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md)

**Comment by KirkhapAuto** [comment]
Link is 404

**Comment by raisedadead** [comment]
Sorry new link: [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/master/CONTRIBUTING.md)

**Comment by KirkhapAuto** [comment]
Cool thank you. I can see there is a link in there called : https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md 

I shall follow the instructions therein. But I'm still slightly confused. I cannot see anything in those links that shows me how to seed the DB with an offline copy of https://www.freecodecamp.org/

**Comment by raisedadead** [comment]
Please reachout to [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors)?

**Comment by KirkhapAuto** [comment]
Thanks
