### ISSUE TITLE
[ES6: Create Strings using Template Literals] passes even if template literal is used in only one li

### ISSUE THREAD

**Issue by maxdevjs** [freeCodeCamp/freeCodeCamp#18105]
#### Describe your problem and - if possible - how to reproduce it

Challenge passes even if template literal is used in only one `li` (does not matter which one, important is that refers the right entry of the result object's failure array):

```js
const resultDisplayArray = [
    `<li class="text-warning">no-var</li>`,
    `<li class="text-warning">${arr[1]}</li>`, 
    `<li class="text-warning">linebreak</li>` ];
```

this will pass (and I suppose all three `li` should use template literal, instead)

#### Add a Link to the page with the problem

[ES6: Create Strings using Template Literals](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/create-strings-using-template-literals)

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: 68.0.3440.106 (Official Build) (64-bit)
* Operating System: Solus

#### If possible, add a screenshot here

![screenshot-2018-09-09_02 36 04_-03-03 00_1536471364](https://user-images.githubusercontent.com/22229196/45261454-34358d00-b3d9-11e8-82f9-3f6fef4e9fee.png)

**Comment by Chiouonthis** [comment]
I have been able to replicate this on 

- Browser Name: Chrome
- Browser Version: Version 69.0.3497.100 (Official Build) (64-bit)
- Operating System: macOs 10.13.16 (High Sierra)

It seems as if the assertion is based completely on the contents of resultDisplayArray matching the desired output, as submitting the below without using any template literals will also pass:

```
// change code below this line
  const resultDisplayArray = [
    `<li class="text-warning">no-var</li>`,
   `<li class="text-warning">var-on-top</li>`, 
    `<li class="text-warning">linebreak</li>`  ];
  // change code above this line`
```

**Comment by johnkennedy9147** [comment]
@maxdevjs @Chiouonthis Hi, you are both confusing template literals and placeholders.
You can have a valid template literal without using a placeholder.

There is a problem with this lesson as it does too much and there are many ways to produce the correct output and we need tests that pass for all valid.

Consider this solution for example
``` js
const resultDisplayArray = arr.map(el => `<li class="text-warning">${el}</li>`)
```
This would fail if we tested for the presence of 3 template literals, but is a perfectly valid solution and many campers have gone this or a similar route.

There have been discussions about this lesson before and replacing it with multiple lessons that introduce template literals and placeholders etc in bitesize chunks was suggested.
