### ISSUE TITLE
.map-challenge-title a /*<style> on the website; text color changed to #f8f8f8*/ 

### ISSUE THREAD

**Issue by chiliphrosting** [freeCodeCamp/freeCodeCamp#18114]
#### Describe your problem and - if possible - how to reproduce it

I just came across this situation where the text on the website has switched from "#006400" to "#f8f8f8". I'm not sure exactly when this happened but defaults when loading the website. I'm not sure if other people have encountered the same thing. I was able to change it back by disabling (in the chrome dev console) the
... .map-challenge-title a{color: #f8f8f8}

 I tested it out on different browsers on my laptop that I am using and the text color is "#f8f8f8".

<strike>I just tested it on another computer and the curriculum page is not loading</strike>. Maybe that has something to do with it.

Hope this helps!

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/

#### Tell us about your browser and operating system

* Browser Name: chrome
* Browser Version: Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: Windows 10
(same issue occurs on iphone safari, firefox on win10, edge)

#### If possible, add a screenshot here
this is running on edge:
![image](https://user-images.githubusercontent.com/43098131/45327587-1e81ae00-b526-11e8-9455-2da2382c5433.png)

#### below ".map-challenge-title a" is  disabled which is why you see the text on the left(chrome): 
![image](https://user-images.githubusercontent.com/43098131/45327700-96e86f00-b526-11e8-9ef1-10cc9383c584.png)

**Comment by Nirajn2311** [comment]
@chiliphrosting could you close the issue as it has been fixed.

**Comment by chiliphrosting** [comment]
Thanks @Nirajn2311
