### ISSUE TITLE
Typo in lesson: Basic CSS: Cascading CSS variables. Should refer to :root being in CSS not HTML document

### ISSUE THREAD

**Issue by tesla809** [freeCodeCamp/freeCodeCamp#18116]
#### Describe your problem and - if possible - how to reproduce it
The lesson states:
"You can think of the :root element as a container for your entire **HTML** document, in the same way that an html element is a container for the body element."

This should be CSS instead of HTML. It should read:
"You can think of the :root element as a container for your entire **CSS** document, in the same way that an html element is a container for the body element."

#### Add a Link to the page with the problem
Lesson: Basic CSS: Cascading CSS variables
Link: https://learn.freecodecamp.org/responsive-web-design/basic-css/cascading-css-variables

#### Tell us about your browser and operating system
* Browser Name: Chrome
* Browser Version: Version 68.0.3440.106 
* Operating System: Mac

**Comment by mul53** [comment]
Hi, i have written a fix for the code and i have a question. The issue is raised in the freeCodeCamp/freeCodeCamp repo but the fix occurs in the freeCodeCamp/curriculum repo. How should i handle this? This is my first time would love some help.

**Comment by moT01** [comment]
@mul53 make the PR over on the curriculum repo, which is where it needs to be fixed - put a link to this issue in the PR so whoever merges it knows to come close this issue

**Comment by Hassanraja447** [comment]
I have fixed this typo in curriculum repo and made PR.

**Comment by tesla809** [comment]
Thanks, @Hassanraja447!
