### ISSUE TITLE
Curriculum List Items Are Invisible in Chrome & Safari (iOS)

### ISSUE THREAD

**Issue by dylantyates** [freeCodeCamp/freeCodeCamp#18110]
#### Curriculum List Item Anchors Are Not Visible

There is styling on the index that has set `.map-challenge-title a` to `color: #f8f8f8` rendering them basically invisible. If you open Chrome > DevTools you can see the bootstrap styling to make the anchors green but it is being overridden by the index styling.

#### Relevant Link

https://learn.freecodecamp.org/

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: Version 68.0.3440.106 (Official Build) (64-bit) 
* Operating System: Mac OS X El Capitan Version 10.11.6

 

#### If possible, add a screenshot here

![screen shot 2018-09-10 at 11 19 57 am](https://user-images.githubusercontent.com/14165879/45310575-405e3f00-b4ec-11e8-8578-5b78168c1c3b.png)

**Comment by dylantyates** [comment]
I applied temporary fix by converting my theme to Night Mode

**Comment by Nirajn2311** [comment]
@dylantyates Looks like someone must have messed it up in one of the recent PRs. We have to make this a top priority.

**Comment by RaspberryLime** [comment]
It’s not just Chrome, it affects Safari in iOS too. Can the title be altered?

**Comment by Nirajn2311** [comment]
I have opened a PR to fix this issue.

**Comment by chris0715** [comment]
Yes, this is affecting the visual side of the web site..

**Comment by randelldawson** [comment]
With a problem of this magnitude, why can't everything be rolled back to the most current working version and release again after it is resolved?  Other stuff was also broken during this latest release in the past 24 hours.

**Comment by randelldawson** [comment]
This has been marked closed. How do I find out the fix that was put into place to resolve this issue?  Also, how long are we going to have to wait until this is pushed to production?

Thank you.

**Comment by Bouncey** [comment]
@randelldawson The fix contained in freeCodeCamp/Learn#289 has already been rolled out to production. I didn't see this issue when creating the PR so I closed it manually after the fact.

Here is a current screenshot of the production site 
![image](https://user-images.githubusercontent.com/18572518/45363826-6d841d80-b5d0-11e8-9601-c2bd7c46803f.png)

I hope this answers your questions

Happy coding!
