### ISSUE TITLE
All challenges which test if something is console.logged are broke as of the past 24 hours

### ISSUE THREAD

**Issue by randelldawson** [freeCodeCamp/freeCodeCamp#18115]
#### Describe your problem and - if possible - how to reproduce it
I assume a release which happened in the past 24 hours is responsible for the problem described below, because the challenge tests used to work fine.  

On challenges requiring the user to console.log something specific to the console such as in the case of **Basic JavaScript: Write Reusable JavaScript with Functions**, the test related to what should appear in the console is failing.  This new bug has been reported 10-15 times in the last 24 hours.

The following code should pass the challenge, but does not.
```
function reusableFunction() {
  console.log("Hi World");
}

reusableFunction();
``` 
Again, another challenge which is affected by the same problem is [Basic JavaScript: Passing Values to Functions with Arguments](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/passing-values-to-functions-with-arguments).

Can the current version rolled out be reversed?  There are also some site wide CSS problems which make it difficult to view the current curriculum.  See screenshot below.

![image](https://user-images.githubusercontent.com/5313213/45330247-59c9b000-b519-11e8-9c5a-ba1e7678f524.png)

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/write-reusable-javascript-with-functions/

#### Tell us about your browser and operating system

* Browser Name: various browsers
* Browser Version: n/a
* Operating System: n/a

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/5313213/45330015-22a6cf00-b518-11e8-844f-0c77b1d7142d.png)

**Comment by victorhazbun** [comment]
Confirmed. 

![screen shot 2018-09-11 at 2 30 03 pm](https://user-images.githubusercontent.com/1174604/45338243-66104480-b5cf-11e8-9525-77ac7e8943c1.png)

**Comment by ojeytonwilliams** [comment]
@Bouncey I'm pretty sure my PR, freeCodeCamp/learn/pull/232, is the culprit - at least for the failing tests.  Sorry about that!

I'll try to see what I changed to break things.

**Comment by Bouncey** [comment]
@ojeytonwilliams It may be we need to remove your `proxyLogger` until this issue is addessed.

@randelldawson we operate a CI/CD pipeline with TravisCI and Netlify. Currently we do not have any end-to-end tests that could have picked this up. I will create a project at the organisation level to see how we can address this. In the meantime, I will remove the breaking change personally until @ojeytonwilliams can find a fix for this.

**Comment by Bouncey** [comment]
Issue moved to [freeCodeCamp/learn #291](https://github.com/freeCodeCamp/learn/issues/291) via [**ZenHub**](https://www.zenhub.com/)
