### ISSUE TITLE
font almost invisible

### ISSUE THREAD

**Issue by Stephanevg** [freeCodeCamp/freeCodeCamp#18113]
#### Describe your problem and - if possible - how to reproduce its

simply go on the curiculm page

#### Tell us about your browser and operating system

* Browser Name: Internet explorer AND Chrome
* Browser Version: 
* Operating System: Windows 10

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/6302961/45326918-a0d59680-b555-11e8-8b39-e290ac08962f.png)

Also, It seems like I lost the section to 'request' the certificate.Is that something you guys don't provide anymore? I thought it was really a great idea. If yes,  Can you point me to the place where I can request it?

**Comment by Nirajn2311** [comment]
The font colour has been fixed. Your certificates can be found in settings page.

**Comment by scissorsneedfoodtoo** [comment]
Closing this as it was solved with https://github.com/freeCodeCamp/learn/pull/289. Please feel free to post another comment if you're still having trouble with your certificates!
