### ISSUE TITLE
Give Sibling Elements a Unique Key Attribute

### ISSUE THREAD

**Issue by JohnnyBizzel** [freeCodeCamp/freeCodeCamp#18127]
#### Describe your problem and - if possible - how to reproduce it
This challenge is passed by providing a key attribute. However, if the user does not supply the data, it still passes.
[Further details on the forum](https://forum.freecodecamp.org/t/give-sibling-elements-a-unique-key-attribute-is-this-a-bug/226182)

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react/give-sibling-elements-a-unique-key-attribute

I would recommend that the test still requires the correct data to appear.

**Comment by ezioda004** [comment]
I'm gonna tackle this one.
