### ISSUE TITLE
The hr tag should come between the title and the paragraph.

### ISSUE THREAD

**Issue by dougouverson** [freeCodeCamp/freeCodeCamp#18124]
#### Describe your problem and - if possible - how to reproduce it

Getting a message, "The hr tag should come between the title and the paragraph." - even though I got the challenge correct.

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-a-horizontal-line-using-the-hr-element

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: ersion 68.0.3440.106 (Official Build) (64-bit)
* Operating System: macOS 10.13.6

#### If possible, add a screenshot here

Tried both <hr> and <hr />

https://www.screencast.com/t/NMTuUdd3
https://www.screencast.com/t/WWCQEjGJy

**Comment by CodingSolo** [comment]
@dougouverson could you close this issue as it is a duplicate [#18030](https://github.com/freeCodeCamp/freeCodeCamp/issues/18030#issue-352216340)

Thank you

**Comment by dougouverson** [comment]
Was the issue fixed?

**Comment by ElGreetly** [comment]
<img width="217" alt="screenshot 2018-09-13 18 10 47" src="https://user-images.githubusercontent.com/38695215/45497404-60a62c00-b780-11e8-89dc-c110e64c4278.png">
The problem the check function checks for <hr> between h4 and em instead of h4 and p

**Comment by CodingSolo** [comment]
The issue has been fixed but it needs to be pushed to production for the [fix](https://github.com/freeCodeCamp/curriculum/pull/189#issue-204599027) to be applied.
**nathanhannig** create a [issue]( https://github.com/freeCodeCamp/learn/issues/297#issue-359732604) in learn repo to get it in production

**Comment by RaspberryLime** [comment]
Can someone close this as it's fixed? (@dougouverson)
