### ISSUE TITLE
have name and value attributes and still cannot pass Survey Form

### ISSUE THREAD

**Issue by theonlyjoeyouneedtoknow** [freeCodeCamp/freeCodeCamp#18125]
#### Describe your problem and - if possible - how to reproduce
I'm working in the Responsive Web Design Examples Section
And I'm working on the Survey form.

In my code I have a "name" attribute as well as a "value" attribute. I also have a "unique ID" for each radio button. Please refer to my screenshot below.

Yet I still cannot pass this Survey Form as per the forked copy with the JavaScript checker. 
It reports an error that says that I have not grouped my checkboxes with the name attribute.
Yet, my checkboxes are grouped, and surrounded with a border as if they are grouped.
I've used the Read-Search-Ask and have yet found another way to group a bunch of checkboxes.
I've even placed the "name" attribute so that it appears first - to no avail. 

#### Add a Link to the page with the problem
https://codepen.io/joemakestheweb/pen/VGrNJw?editors=1000

#### Tell us about your browser and operating system

* Browser Name:  Chrome
* Browser Version:  68
* Operating System: Windows 10

#### If possible, add a screenshot here

![2018-09-12 screen capture](https://user-images.githubusercontent.com/37629145/45428072-6f042300-b66e-11e8-98f3-9fb99a7a01e4.PNG)
![2018-09-12-02 screen capture](https://user-images.githubusercontent.com/37629145/45428080-73304080-b66e-11e8-9a8b-bfc2ba403ce5.PNG)

**Comment by Nirajn2311** [comment]
@theonlyjoeyouneedtoknow According to the challenge an instruction says
> User Story #13: Inside the form element, I can select a field from one or more groups of radio buttons. Each group should be grouped using the name attribute.

In your code you are missing radio buttons.

**Comment by theonlyjoeyouneedtoknow** [comment]
Thank you so much. I'm sorry. I feel silly. Maybe, I'm taking Free Code Camp too seriously? Still, no excuses. My apologies. I passed! I'm so happy, thank you for pointing out my error. Because of you, I passed!

**Comment by Nirajn2311** [comment]
@theonlyjoeyouneedtoknow could you close this issue as it has been solved?
