### ISSUE TITLE
Use a Retina Image for Higher Resolution Displays

### ISSUE THREAD

**Issue by tspeed90** [freeCodeCamp/freeCodeCamp#18129]
#### Describe your problem and - if possible - how to reproduce it
The 'Use a Retina Image for Higher Resolution Displays' challenge gives no context whatsoever about what a retina image is, what a retina display is, or what this challenge is really teaching you to do. I completed the challenge, but really had no idea what I'd just done or how that would effect a webpage I built and what benefits it would really provide. This platform caters to people of all levels of knowledge and I feel that this assumes a fairly high level of knowledge about screens/displays.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/use-a-retina-image-for-higher-resolution-displays

**Comment by RaspberryLime** [comment]
Agreed. There needs to be a brief description of what a “retina” display is, as not everyone pays attention to Apple’s marketing. (Do other manufacturers have similar terms for their high-density displays?)
