### ISSUE TITLE
Full Stack Cert - Shows current date(not claimed date) - Shows as legacy cert on profile page

### ISSUE THREAD

**Issue by nazarja** [freeCodeCamp/freeCodeCamp#18128]
#### Describe your problem and - if possible - how to reproduce it
1) The Full Stack Cert claimed date will only show as the current date and not the date it was claimed on. I claimed mine on the 7th of September and checking back regularly I noticed the claimed on date was always the current date.

2) The Full Stack Cert appears as the  Legacy Full Stack Cert on a users profile page, clicking this leads to an error as the legacy cert does not exist. It should be in with the new certificates.
That being said, on the settings page the link to view the certificate is linked correctly.

#### Add a Link to the page with the problem
https://www.freecodecamp.org/certification/       ${username-here}         /full-stack
https://www.freecodecamp.org/         ${username-here}

#### Tell us about your browser and operating system
N.A

#### If possible, add a screenshot here
1)
Just the claimed on date. No screenshot necessary.

2)
![issue2](https://user-images.githubusercontent.com/25235189/45452383-bd004180-b6d5-11e8-86fb-2fa8f0bd4c5d.png)

**Comment by moT01** [comment]
Similar to https://github.com/freeCodeCamp/freeCodeCamp/issues/17424

**Comment by adamdune** [comment]
I am having the same issue with my Full Stack Certificate

**Comment by mikeshort10** [comment]
Mine as well. Has this been addressed?

https://www.freecodecamp.org/certification/mikeshort10/full-stack

**Comment by raisedadead** [comment]
Related #34890

**Comment by ColorizeMySky** [comment]
Have the same problem: the date of Full Stack Certificate is always a current date. 
https://www.freecodecamp.org/certification/colorizemysky/full-stack

**Comment by ahmadabdolsaheb** [comment]
If there are no records for a fullstack certificate, a good fallback would be going thought the date of the modern certificates and displaying the date of latest claimed certificate.

**Comment by ahmadabdolsaheb** [comment]
optimally, we should add a completion timestamp and an id when campers claim a fullstack certificate with a fallback to the last earned cert if a timestamp is not found.

**Comment by Abbas-000** [comment]
My full stack certification also updates with the current date not the claimed date.

https://www.freecodecamp.org/certification/fcc4048a47e/full-stack

**Comment by SagirGarba** [comment]
The date on my full stack certificate is showing the date i claim my Responsive Web design certificate ( the first certificate ). and now if i want to see the certificate it is asking me to claim certificate when i claim  it will say is like u have claim the certificate and it will not show me the certificate.

**Comment by raisedadead** [comment]
Potential fixes: https://github.com/freeCodeCamp/freeCodeCamp/pull/37065#issuecomment-598303781 and https://github.com/freeCodeCamp/freeCodeCamp/pull/37065#issuecomment-598343732

**Comment by QuincyLarson** [comment]
Also related to the Full Stack cert – the date seems to be the date the first certification was claimed, not the date the full stack certification was claimed:

https://twitter.com/TevaHenry/status/1257475311375011841/

**Comment by ojeytonwilliams** [comment]
The fallback is not working properly and I should have caught that.  It's not a tricky fix, but I'll make sure it works this time!

**Comment by iansibindi** [comment]
Ok thenks
