### ISSUE TITLE
React and Redux: Manage State Locally First - Tests wrongfully pass

### ISSUE THREAD

**Issue by GiaFil7** [freeCodeCamp/freeCodeCamp#18120]
#### Describe your problem and - if possible - how to reproduce it
So, this code passes all tests:
```
class DisplayMessages extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      input: '',
      messages: []
    }
    this.handleChange = this.handleChange.bind(this);
    this.submitMessage = this.submitMessage.bind(this);
  }
  handleChange(event) {
    this.setState({
      input: event.target.value,
      messages: this.state.messages
    });
  }

  submitMessage() {
    this.setState({
      input: '',
      messages: this.state.messages.concat(this.state.input)
    });
  }

  render() {
    return (
      <div>
        <h2>Type in a new Message:</h2>
        <input onChange={this.handleChange} value={this.state.input}></input>
        <button onClick={this.submitMessage}>Add message</button>
        <ul></ul>
      </div>
    );
  }
};
```
While I haven't added anything regarding the rendering of the ```<li>``` elements, it still passes the 4th test: "The DisplayMessages component should render a div containing an h2 element, a button element, a ul element, **and li elements as children**."

#### Add a Link to the page with the problem
[React and Redux: Manage State Locally First
](https://learn.freecodecamp.org/front-end-libraries/react-and-redux/manage-state-locally-first)

**Comment by jfitzsimmons** [comment]
Just +1ing this issue.  I experienced the same thing.  I passed with an empty <ul> tag.  I added a comment so if I free up some time I might be able to fix it.

**Comment by fornsss** [comment]
this reposidory is go or onot good

**Comment by fornsss** [comment]
my comends is isfory way from polands

**Comment by louischrisorona** [comment]
@WillzMu an array is an "object"   i.e.:
`
let myArray = [1,2,3,4];
console.log(typeof myArray)
`
This outputs 'object'.

**Comment by WillzMu** [comment]
@louischrisorona , yeah, thats true. But you cant `.map()` an "object" now, can you?

**Comment by louischrisorona** [comment]
@WillzMu I think you misinterpreted my helpful tip... I was not trying to patronize you.
Have you since been able to correct your issue?
Was it perhaps that your object was not setup properly to access the array?

`this.state.messages.map((message, index) => {
  return <li key={index}>{message}</li>
})`
