### ISSUE TITLE
Investigate large page sizes

### ISSUE THREAD

**Issue by nsuchy** [freeCodeCamp/freeCodeCamp#18134]
A full page load of a freeCodeCamp Challenge is a compressed 16.15MB blob transfering around 4MB of data across the networking split across several requests. This is harmful to users on mobile networks with limited data plans as well as users in third world countries where data plans are often lower than 100MB per month. Lets investigate the root cause of large page sizes and see what can be done to keep page loads and network transfers as small as possible.

Example page: https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements

* Browser Name: Tor Browser
* Browser Version: 8.5 Alpha 1
* Operating System: macOS High Sierra 10.13.6

<img width="999" alt="screen shot 2018-09-13 at 9 32 15 pm" src="https://user-images.githubusercontent.com/8227641/45524436-87725b80-b79c-11e8-9261-bf8b0b8a5bbb.png">

**Comment by nathanhannig** [comment]
my browser was showing 1.8mb uncached load and 88kb cached. I think this is how React websites behave?

**Comment by CodingSolo** [comment]
I use Lighthouse under Chrome for a test :
Runtime settings
URL: https://learn.freecodecamp.org/
Fetch time: Sep 17, 2018, 6:26 PM GMT+4
Device: Emulated Nexus 5X
Network throttling: 150 ms TCP RTT, 1 638,4 Kbps throughput (Simulated)
CPU throttling: 4x slowdown (Simulated)
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/69.0.3497.81 Chrome/69.0.3497.81 Safari/537.36

the total size was 1920 KB. that is not so bad.
1600 KB = score 100/100
4000 KB = score 50/100
5000 KB = score 24/100
  
![freecodecamp 2018-09-17](https://user-images.githubusercontent.com/38612134/45635178-61f39380-bab5-11e8-9f7d-8036fef15f23.png)

But for the URL: https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements/ the total size was 2820 KB
![sayhello](https://user-images.githubusercontent.com/38612134/45638517-74be9600-babe-11e8-8482-7a7aacf82859.png)

**Comment by CodingSolo** [comment]
and now the bad news.The performance is very bad (1/100 and 4/100)
![opportunities](https://user-images.githubusercontent.com/38612134/45639170-522d7c80-bac0-11e8-9706-d654f1467e80.png)

**Comment by nsuchy** [comment]
When running tests please make sure that browser caches and cookies are completely cleared. Chrome's "guest sessions" and "incognito mode" are good at this :) or be like me and use Tor Browser if you prefer that level of privacy and anonymity.

**Comment by nsuchy** [comment]
@CodingSolo can you try Chrome's guest mode instead of incognito mode? Incognito mode handles a few things differently which might cause problems. Guest mode seems like a better use case here :)

<img width="354" alt="screen shot 2018-09-19 at 9 48 45 am" src="https://user-images.githubusercontent.com/8227641/45757387-38d81d80-bbf1-11e8-98fd-5dc30fbc3536.png">

**Comment by Nirajn2311** [comment]
I checked in guest mode(cleared cookies and cache) and it is still the same.

![screenshot 67](https://user-images.githubusercontent.com/36357875/45775751-cc493700-bc61-11e8-8f76-2de1d603e036.png)


![screenshot 66](https://user-images.githubusercontent.com/36357875/45775754-cd7a6400-bc61-11e8-9603-4b80157a3625.png)

**Comment by CodingSolo** [comment]
yes, the same 1932 KB and 2830KB

**Comment by RandellDawson** [comment]
@raisedadead Is this something that is still an issue on the new beta?

**Comment by nsuchy** [comment]
<img width="1280" alt="screen shot 2019-02-19 at 11 35 36 pm" src="https://user-images.githubusercontent.com/8227641/53066711-18add280-349f-11e9-8dde-e1a263036d98.png">
These new stats may be worth adding to the discussion.

**Comment by RandellDawson** [comment]
@nsuchy Have you checked the stats on https://freecodecamp.rocks?

**Comment by nsuchy** [comment]
<img width="1280" alt="screen shot 2019-02-20 at 2 45 34 pm" src="https://user-images.githubusercontent.com/8227641/53119773-3706e300-351e-11e9-8f75-6f0655d68bad.png">
It has a much larger page size.

**Comment by raisedadead** [comment]
Resolved to a great extent on the latest master, I am closing this for now. We may want to revisit this again in future after we launch
