### ISSUE TITLE
Extend Inifinite loop protection timeout

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#18132]
I've come across several people on the forum who have not been able to get their correct code to pass tests due to the infinite loop protection in the testing process - After console logging some dates, this seems to be set at 100ms, which seems awfully short for a challenge like the one where you need to find the `smallest common multiple` - even for the most efficient code. I'm not sure where this is set or what a better length of time would be before it timeouts, but I would suggest a lot more - maybe as much as 10000ms

this post https://forum.freecodecamp.org/t/free-code-camp-infinite-loop-protection/19550 describes the loop protection at 500ms, and gives a workaround by adding the `//noprotect` to your code, which doesn't seem to work since the new site

here's two posts of people having this issue...
https://forum.freecodecamp.org/t/help-problem-4-largest-palindrome-product/226359/2
https://forum.freecodecamp.org/t/smallest-common-multiple-cant-pass-the-last-two-tests/223679/3

So I would suggest to either fix `//noprotect` so it works again and/or extend the time limit before the loop protection kicks in

**Comment by randelldawson** [comment]
Since all the current FCC challenges can be solved with a more efficient algorithm, I think adding more time just promotes campers to only create brute force solutions instead of having to do some research on their own regarding what is a more a efficient algorithm to use.

**Comment by moT01** [comment]
I'm not convinced - What about the project euler challenges? A number of those look like they could need significantly more time to run - I'm not saying to promote the brute force method - but like I said before, 100ms (which is how long I think they get according to my quick test) seems short even for a good algorithm on some of the challenges.

**Comment by moT01** [comment]
closing this in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/15819
