### ISSUE TITLE
Reuse Patterns Using Capture Groups

### ISSUE THREAD

**Issue by JESii** [freeCodeCamp/freeCodeCamp#18138]
#### Describe your problem and - if possible - how to reproduce it
This challenge requests that we:

> Use capture groups in reRegex to match numbers that are repeated only three times in a string, each **_separated by a space_**.

However, the tests require that the numbers have **_two_** spaces (see screenshot below) and don't allow an actual space character. 

Thus, valid RegEx's such as /`^(\d+) \1 \1$/ `or `/^(\d+ )\1\1$/` fail.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/reuse-patterns-using-capture-groups

#### Tell us about your browser and operating system

* Browser Name:  chrome
* Browser Version: Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System: MacOS 10.13.6 High Sierra

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/486/45587598-baac0c00-b8bc-11e8-999c-de37a6fddccf.png)

**Comment by JESii** [comment]
Thanks @randelldawson for catching that error on my second expression and for fixing the text expression (all those backslashes make my eyes water :=) Are you merging this change?

**Comment by RandellDawson** [comment]
@JESii I had forgotten about his issue.  I just created a PR to hopefully resolve this bug.
