### ISSUE TITLE
Profile heatmap and timeline not showing progress etc

### ISSUE THREAD

**Issue by nohatnanoes** [freeCodeCamp/freeCodeCamp#18137]
The heatmap and timeline aren't showing progress on my profile

https://www.freecodecamp.org/nohatnanoes

* Browser Name: Google Chrome
* Browser Version: 68.0.3440.106
* Operating System: Windows 8

**Comment by moT01** [comment]
closing in favor of duplicate https://github.com/freeCodeCamp/freeCodeCamp/issues/17299
