### ISSUE TITLE
Clicking on 'Curriculum' doesn't focus/collapses the current projects tree

### ISSUE THREAD

**Issue by quantuumsnot** [freeCodeCamp/freeCodeCamp#18131]
#### Describe your problem and - if possible - how to reproduce it
For example if I'm working on 'Use tabindex to Add Keyboard Focus to an Element' and complete it and move to the next one, then clicking on 'Curriculum' collapses only 'Introduction to Basic HTML and HTML5' instead of collapsing only 'Applied Accessibility >  Introduction to the Applied Accessibility Challenges'

#### Add a Link to the page with the problem
[use-tabindex-to-add-keyboard-focus-to-an-element
](https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/use-tabindex-to-add-keyboard-focus-to-an-element)

#### Tell us about your browser and operating system

* Browser Name: Firefox Developer Edition
* Browser Version: 63.0b5 64bit
* Operating System: Windows 7 x64

**Comment by thecodingaviator** [comment]
@quantuumsnot Please either include a screenshot or video of what is happening or close the issue if fixed

**Comment by quantuumsnot** [comment]
So, as I stated already if the user completes a task and then clicks on the 'Curriculim' his or her currently reached task/project is not focused. Instead the 'Curriculum' is collapsed only on 'Introduction to Basic HTML and HTML5'. This UX problem is still here.

**Comment by thecodingaviator** [comment]
Ahh that problem, I see what you're talking about, I think we'll have to dive into local storage over here. Let's see what @freeCodeCamp/moderators have to say

**Comment by raisedadead** [comment]
Tons of thanks to @ojeytonwilliams and @ValeraS for working and implementing this. This will be shipped in the next version for freeCodeCamp in the upcoming weeks.
