### ISSUE TITLE
React: Create a Component with Composition hangs 

### ISSUE THREAD

**Issue by bentom03** [freeCodeCamp/freeCodeCamp#18146]
#### Describe your problem and - if possible - how to reproduce it
React: Create a Component with Composition hangs as soon as I click on the editor. 

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/front-end-libraries/react/create-a-component-with-composition/

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: Quantum
* Operating System: Windows 10

**Comment by randelldawson** [comment]
@bentom03 So you never entered any new code for the challenge previously before?  Have you tried on a different browser like Chrome?  If still having trouble on Chrome, then go to the forum and create a post and make sure to copy/paste your actual code and provide a link to the challenge.

**Comment by bentom03** [comment]
Thanks randelldawson! Worked well on Chrome.

**Comment by bentom03** [comment]
Tried again on Firefox. Now it works.

**Comment by randelldawson** [comment]
@bentom03 Can you close this issue then?
