### ISSUE TITLE
Having issue running FCC in production

### ISSUE THREAD

**Issue by stanleyyylau** [freeCodeCamp/freeCodeCamp#18145]
#### Describe your problem and - if possible - how to reproduce it

I have to run FCC in production because I’m one of the maintainers of FCC china website, we launch the new site on 15th, and through some offline activity, users are increasing, but they also report some bugs and performance issue.  I check the code and notice on production server ``npm run start-production`` don’t actually pass the ``env=production`` environment variables to the node app. and when I debug locally and manually pass the ``env=production`` and run ``npm run start-production`` again. all the routes don’t work, meaning not even hitting the routes.

#### Tell us about your browser and operating system

* Browser Name: chrome
* Browser Version:  Version 69.0.3497.92 (Official Build) (64-bit)
* Operating System: Mac os 10.12.6 (16G1510)

**Comment by stanleyyylau** [comment]
Passing environment variable like this works but it causes the route not working issue

![image](https://user-images.githubusercontent.com/16324279/45660495-9f930380-bb2b-11e8-8648-9f74fb47fb98.png)

**Comment by raisedadead** [comment]
Hi @stanleyyylau sorry about the delay in getting back to you. You should set the NODE_ENV in the `.env` file along with anything else that you would like to tweak in the pm2Start config. 

That's how we have done it for freeCodeCamp.org

I am not sure, what routes issues you are facing. But feel free to drop me a query with the details if you would like additional help `mrugesh at freecodecamp dot org`

**Comment by raisedadead** [comment]
I'll add further comments on the linked PR to better guide the workflow.
