### ISSUE TITLE
Feature Req: Projects: Allow User Stories to be checked off by student

### ISSUE THREAD

**Issue by Se7enSquared** [freeCodeCamp/freeCodeCamp#18144]
In the project pages, I would like to be able to check off what I've completed. It would save me time to not have to re-read to find out where I am. 

Link to a project page: https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-survey-form

* Browser Name: Chrome
* Browser Version: Latest
* Operating System: Windows 10

**Comment by wadeLove** [comment]
It's not optimal I agree, but you use the Test Suite as a way to know where you're at. Simply press the "Run Tests" button and it should tell you what you've passes successfully and what you haven't yet.

**Comment by stevenkuipers** [comment]
I wrote a small chrome extension that will make user stories clickable so you can check them off. You can find it here: https://github.com/stevenkuipers/checkboxFCC.

**Comment by moT01** [comment]
Closing this as stale. This is a good suggestion, but it didn't get much attention. Feel free to create a new issue and maybe it will get some more traction.
