### ISSUE TITLE
Search bar is not filling the entire navbar

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/freeCodeCamp#18150]
#### Describe your problem and - if possible - how to reproduce it
In the learn page and in any of the challenge page the search bar is moved to the left and its size has been decreased. Also when you search something you can't see any results as they have been moved to the left.

I can work on the fix for this issue.

#### Add a Link to the page with the problem
Learn home page and any challenges

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 69.0.3497.100
* Operating System: Windows 10 1803

#### If possible, add a screenshot here
![screenshot 64](https://user-images.githubusercontent.com/36357875/45756735-a6f10480-bc32-11e8-80a8-a75cc49c6538.png)

**Comment by JWillZ94** [comment]
I'll look into this issue.

**Comment by Nirajn2311** [comment]
@JWillZ94 Have a go at it. If you need any help, ask here.

**Comment by JWillZ94** [comment]
Cool, by the way I can't seem to find a way to work on the learn.freecodecamp.org site locally. In localhost, the link to the curriculum part of the site sends me to the live learn.freecodecamp.org. It seems that the curriculum section and the main site have different navbars as well. Also, I can't find the code that belongs to it within this repo. Where can I find the code for the curriculum section?

**Comment by scissorsneedfoodtoo** [comment]
@Nirajn2311, thank you for creating an issue about this. Unfortunately my recently accepted PR adjusting the Learn navbar lead to this bug. 

@JWillZ94, thanks for offering to fix this, but I've already submitted a fix here: https://github.com/freeCodeCamp/learn/pull/290

That said, please feel free to take a look at the code and improve on it if you can! The files that need to be edited can be found in the [Learn](https://github.com/freeCodeCamp/learn) repo.

**Comment by RandellDawson** [comment]
@Nirajn2311 I have tested this in the beta site and it appears to be resolved.  Let me know if you think this issue should still be left open.  If you find the beta site does not have this problem, but want to leave this issue open, please add the label `status: resolved \ shipping`.

Thank you.
