### ISSUE TITLE
CSS issue - Settings in Nav Links wraps under when window width is below 1100px

### ISSUE THREAD

**Issue by jfitzsimmons** [freeCodeCamp/freeCodeCamp#18154]
#### Describe your problem and - if possible - how to reproduce it
On a public profile page, when the window width is below 1100px, the settings link wraps under the rest of the links in the top right corner of the page.

`<li class="nav-avatar"><a href="/settings">Settings</a></li>`

wraps under the rest of the list items in nav-links

`<ul id="nav-links" class="nav navbar-nav navbar-right" data-reactid="30"> ... </ul>`

#### Add a Link to the page with the problem
https://www.freecodecamp.org/jfitzsimmons

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 69.0.3497.100 (Official Build) (64-bit)
* Operating System: Mac osx

#### If possible, add a screenshot here

![www freecodecamp org_jfitzsimmons](https://user-images.githubusercontent.com/8180747/45773486-1275aa80-bc10-11e8-9b19-9d4ed80c9a2e.png)

**Comment by jfitzsimmons** [comment]
This is my first PR to this project so if I'm way off base let me know. Just wanted to get my feet wet and help out.

**Comment by nischaldutt** [comment]
I would like to work on it if anyone else has not picked it up yet.
