### ISSUE TITLE
[Test Failing] Applied Visual Design - Applied Visual Design: Create a Horizontal Line Using the hr Element

### ISSUE THREAD

**Issue by adeelibr** [freeCodeCamp/freeCodeCamp#18156]
Test Failing when you hit run on adding the `<hr>` || `<hr />` tag in.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-a-horizontal-line-using-the-hr-element/

#### Tell us about your browser and operating system

* Google Chrome Version 69 
* Operating System: Windows 

#### 
![capture](https://user-images.githubusercontent.com/16651811/45808358-0f95bb00-bcdf-11e8-8c56-8af39b8f6e79.PNG)
Screenshot

**Comment by RaspberryLime** [comment]
There are multiple issues open for this already -- the title here doesn't match with the bug you're repoorting though?

**Comment by adeelibr** [comment]
Sorry, I didn't realize. The issue was open.
