### ISSUE TITLE
HelmetJS challenge helmet.hidePoweredBy() test failing always

### ISSUE THREAD

**Issue by jacobvarner** [freeCodeCamp/freeCodeCamp#18159]
In the second module of the HelmetJS section, the application will not pass the test despite having code fully correct. I even went to copy the code directly from the HelmetJS docs and it still will not pass. I have installed and required HelmetJS correctly in order to pass the test from the previous challenge and now the test for the second challenge fails and just says "expected 'Express' to not equal 'Express.'"

<img width="681" alt="screen shot 2018-09-20 at 9 59 24 am" src="https://user-images.githubusercontent.com/11962567/45827711-a735e200-bcbc-11e8-87a5-8b4b8a67324a.png">

If I just call app.use(helmet()) then I get a different error that seems to be more accurate as to what should return an error. I have not found any solution that satisfies the test case.

#### EDIT:
Upon inspecting the header in the Chrome Dev Tools, it appears that the code is working correctly and the x-powered-by has been set to 'PHP 4.2.0' like it should have been. This makes me assume that the test is just always failing and returning that error message regardless of the actual header.

<img width="358" alt="screen shot 2018-09-20 at 10 11 58 am" src="https://user-images.githubusercontent.com/11962567/45828349-f03a6600-bcbd-11e8-94c0-47a665864c5d.png">

[This challenge](https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-with-helmetjs/hide-potentially-dangerous-information-using-helmet-hidepoweredby) is the one that will not pass the test case.

* Browser Name: Google Chrome
* Browser Version: 69.0.3497.100 (Official Build) (64-bit)
* Operating System: MacOS 10.13.6 High Sierra

**Comment by rifkegribenes** [comment]
I'm having issues with passing these tests too, same browser and OS combo. 

it took many tries spaced over several hours to get the first and second tests to pass (code was not changed between attempts, it just didn't pass the first 3 or 4 times i tried to submit). the third challenge i've tried to submit multiple times over two days, and have also tried in firefox and safari.the one line of code i added to the file for this challenge is `helmet.frameguard({action: 'deny'}); `

the error message in the test results is

```
helmet.frameguard() middleware is not mounted correctly
expected { 'x-powered-by': 'PHP 4.2.0' } to have property 'x-frame-options'
```

**Comment by developing-coder** [comment]
Same exact situation here.

- Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
- Windows 10

**Comment by bharadwaj-pendyala** [comment]
Facing the same issue, I was like going crazy, thanks @jacobvarner for the thread.

**Comment by karikalanarun** [comment]
May I know, Is this reproduced in other browsers?.

**Comment by ojeytonwilliams** [comment]
The issue stems from the boilerplate - the api always returns 'Express' the first time it's called.  The work around is to submit your challenge twice as discussed above.  Waiting _should_ not be necessary. Not beyond waiting for the first submission to fail.

As for a solution - it's necessary to change server.js to use express.Router().  I have a PR ready to go, but first I need to check this doesn't break something elsewhere!

**Comment by NicksPatties** [comment]
I was also experiencing some trouble with this bug until I read this Issue. Waiting for a while to test the solution allowed me to move on.

@karikalanarun I was able to reproduce the error in Firefox 72.0.1. However, helmet updated the headers as expected when I call `app.use(helmet.hidePoweredBy({ setTo: 'PHP 4.2.0' }));`:

<img width="552" alt="ff-response-headers" src="https://user-images.githubusercontent.com/3261001/72671150-c781c800-39fa-11ea-988c-c686557502c2.png">

**Comment by this-isnt-me** [comment]
I had the same issue, you can resolve it by using a previous version. Go to your package.json file and use version 3.21.1 anything more recent has the same.issue.

**Comment by ChrisJabb21** [comment]
@this-isnt-me  You are a lifesaver. I was having the same issue to and what you did helped me out, what helped was changing the version from 4.0.0 to another previous version like 3.21.1 to fix the ```helmet.hidePoweredBy() middleware should be mounted correctly```. error i kept getting. my code was right but the FCC site was just not letting me submit my glitch project link url.

My browser details   
---
Browser Name: FireFox
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0

**Comment by moT01** [comment]
This should be fixed now via https://github.com/freeCodeCamp/freeCodeCamp/pull/39194 - so I am going to close this. If anyone is still having problems, feel free to make a comment and we can reopen it. Thanks and happy coding 🎉
