### ISSUE TITLE
Have done challenge but not acknowledging and moving forward to next challenge??

### ISSUE THREAD

**Issue by jtrevett** [FreeCodeCamp/FreeCodeCamp#1816]
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-color-of-text has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by AryanJ-NYC** [comment]
Try using CTRL+Enter. It takes a few seconds.

**Comment by klcrowder1** [comment]
Ensure that you have <body></body> tags at the end of your editor

**Comment by eabedrapo** [comment]
CTRL+Enter isn't working for me in any waypoint although I can still continue progressing by clicking on the green button.

I'm using WinChrome44.

I reached this issue while checking if CTRL+Enter bug has been already logged in here... if I don't find it already filed, I'll raise it so it stays properly documented.

**Comment by AryanJ-NYC** [comment]
CTRL+Enter should work. Press it and wait approximately one minute. It's just really slow.

**Comment by eabedrapo** [comment]
Hmm.. ok, thanks @AryanJ-NYC.

**Comment by QuincyLarson** [comment]
Sorry about this. Our app is running much faster now. That said, there is still a noticeable delay, and we are not satisfied with this. We'll make it faster.
