### ISSUE TITLE
Basic CSS challenge “Improve Compatibility with Browser Fallbacks“ not showing on timeline when completed

### ISSUE THREAD

**Issue by RaspberryLime** [freeCodeCamp/freeCodeCamp#18166]
#### Describe your problem and - if possible - how to reproduce it

I completed the new CSS basic challenge “Basic CSS: Improve Compatibility with Browser Fallbacks“ yesterday (September 22) but it doesn’t show up in my timeline on my profile. It does show as complete in the curriculum though.

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/responsive-web-design/basic-css/improve-compatibility-with-browser-fallbacks 
https://www.freecodecamp.org/raspberrylime

#### Tell us about your browser and operating system

* Browser Name: Safari
* Browser Version: iOS 12
* Operating System: iOS 12

#### If possible, add a screenshot here

![dd10fd8e-0155-473b-97d4-9c26089a2305](https://user-images.githubusercontent.com/25120737/45926723-ebc0b800-bf1e-11e8-974c-248f79c9ef8e.png)
![2b1e4d67-7076-4093-ab8a-a6c4678e3c30](https://user-images.githubusercontent.com/25120737/45926724-ebc0b800-bf1e-11e8-8e87-c80700d7a698.png)

**Comment by TutuPug** [comment]
Have you tried posting on freecodecamp forum? they are very helpful, i hope you can figure it out.

**Comment by RaspberryLime** [comment]
Yes, I tried posting there first, with no response from anyone. Then I went into Gitter chat where another user verified it’s not a cache issue on my device.

**Comment by RaspberryLime** [comment]
Someone has fixed this.
