### ISSUE TITLE
Applied Visual Design:  Adjust the Tone of a Color

### ISSUE THREAD

**Issue by adachenski** [freeCodeCamp/freeCodeCamp#18165]
#### Preconditions
1. Login to "https://learn.freecodecamp.org" with valid credentials
2. Navigate to "https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-tone-of-a-color/"

#### Steps To Reproduce
1.  See the HTML section on the right
2. From the Navigation Menu, click on the any of the links: "Home", "Classes", "Contact"

#### Expected Result
On step 2 Nothing should happen

#### Actual Result
After we click on any of the links from the Navigation Menu,
On our HTML section is open a brand new session of the same HTML page
#### Images
 [Image 1](https://drive.google.com/open?id=1yaLABYh_df2NjWwlLRWst1nKNvOXRxq1)
 [Image 2](https://drive.google.com/open?id=11iYBWyjwO1WwZJ2fdri6TPMRJt9sb5aB)

#### Operating system
* Browser Name: Chrome
* Browser Version: 69
* Operating System:  Windows 10

**Comment by siddharth1198** [comment]
put # in href of links : "home" , "classess" , "contact"

**Comment by prj1999** [comment]
@adachenski If u dont have any problem can I  solve this issue?
