### ISSUE TITLE
'Create a Bootstrap Headline' does not check for class 'text-center'

### ISSUE THREAD

**Issue by AryanJ-NYC** [FreeCodeCamp/FreeCodeCamp#1817]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-bootstrap-headline has an issue:

**Comment by AryanJ-NYC** [comment]
'Create a Bootstrap Headline' does not check for class 'text-center'

**Comment by labiej** [comment]
I haven't been able to reproduce this.
This happened during the updates so it might have been a temporary glitch
