### ISSUE TITLE
Array destructuring "easy" solution to the challenge

### ISSUE THREAD

**Issue by MattCrl** [freeCodeCamp/freeCodeCamp#18177]
#### Describe your problem and - if possible - how to reproduce it
I don't know if it's a "fixable" problem but i was surprised my solution without using array destructuring worked. Just had to write : 
"a = 6
b = 8"
Then submit and my solution was accepted !
So i don't know if it's a real issue but i wanted to share it, because in the challenge it's specified that you need to "Use array destructuring to swap a and b."

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-arrays

#### Tell us about your browser and operating system

* Browser Name: Mozilla Firefox
* Browser Version: 52.9.0 (64 bits)
* Operating System: Linux - Debian

#### If possible, add a screenshot here
![](https://image.ibb.co/cUTCU9/Capture_du_2018_09_25_12_22_22.png)

**Comment by geeseyj** [comment]
I've got this one 🙂

**Comment by thecodingaviator** [comment]
@geeseyj Try giving it another stab

**Comment by RandellDawson** [comment]
@geeseyj, @thecodingaviator I reopened PR #18909, resolved merge conflicts, and replaced the partial solution with a full solution and it seems to fix this issue.  I am awaiting feedback from other reviewers before we can merge it.
