### ISSUE TITLE
Applied Visual Design: Learn about Tertiary Colors

### ISSUE THREAD

**Issue by shaminzn** [freeCodeCamp/freeCodeCamp#18179]
#### Describe your problem and - if possible - how to reproduce it

Hello, I was just doing the Applied Visual Design- Learn about Tertiary Colors and the example seems a little off to me. Maybe it was a typo but it says, _"For example, red (primary) and yellow (secondary) make orange"_. **Yellow is a primary color and red and yellow make a secondary color orange but the example doesn't reflect the definition of a tertiary color unless you meant red(primary) and orange(secondary) makes red-orange (tertiary)**. Someone who really doesn't really know colors might get confused ^.^'...Thank you!

#### Add a Link to the page with the problem

[Applied Visual Design: Learn about Tertiary Colors](https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/learn-about-tertiary-colors)

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: latest
* Operating System: Windows 10

#### If possible, add a screenshot here

![tertiarycolorsproblem](https://user-images.githubusercontent.com/4651824/46046517-5f192400-c0ef-11e8-95ae-59d6b306c568.png)

**Comment by scrabill** [comment]
Yeah, that does seem like a typo. I'd like to give this update a try.

I have come color theory books laying around. I may be able to add some additional clarification.
