### ISSUE TITLE
Test Suite for projects being blocked (Failed to load resource: net::ERR_BLOCKED_BY_CLIENT)

### ISSUE THREAD

**Issue by nathanhannig** [freeCodeCamp/freeCodeCamp#18183]
#### Describe your problem and - if possible - how to reproduce it
I am in progress of completing the Responsive Web Design projects which require the use of the Test Suite on CodePen.

```
You can build your project by forking this CodePen pen. Or you can use this CDN link to run the tests in any environment you like: 
https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js.
```

However, the Test Suite is failing to load on CodePen, the Chrome browser console returns the following error.

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT - bundle.js
```

After searching for a solution, I determined the error is being caused by a very popular Google Chrome extension called Privacy Badger created by the EFF. (https://www.eff.org/privacybadger)

I opened the extension settings and set the slider for the file it was blocking to be allowed. The Test Suite then loaded.

I recommend we submit feedback though the extension letting the Privacy Badger team know they are blocking a file that is critical for freeCodeCamp users.

It might also be useful to add a note to all projects that require the Test Suite informing users that Chrome extensions may block the Test Suite from loading.

**Comment by jonathan-grah** [comment]
@raisedadead, @Bouncey: I'm not sure where we would add this, but maybe we could add like some sort of warning stating "Note: browser extensions may block our testing suite". But then again, some extensions could end up blocking all sorts of things, so maybe it's not worth it?

**Comment by tchaffee** [comment]
We should be able to find a place to add this warning. I opened https://github.com/freeCodeCamp/testable-projects-fcc/issues/618, which is the right place to track and fix this issue and am closing this one.
