### ISSUE TITLE
Use Inheritance So You Don't Repeat Yourself

### ISSUE THREAD

**Issue by JESii** [freeCodeCamp/freeCodeCamp#18195]
#### Describe your problem and - if possible - how to reproduce it
The challenge description and code make reference to Dog & Bird (Bear and Cat) being sub-types of Animal, but there's no description or code to actually do that so one can be left wondering "How did that happen?" Furthermore, the code example won't actually run if done stand-alone since there Bear & Cat aren't actually sub-typed from Animal.

I think it would be better to include the sub-typing so it's clear what's going on

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/use-inheritance-so-you-dont-repeat-yourself

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 69.0.3497.100 (Official Build) (64-bit)
* Operating System: MacOS 10.13.6

#### If possible, add a screenshot here
Taken after the code changes to meet the challenge...
![image](https://user-images.githubusercontent.com/486/46246261-a5040f80-c3af-11e8-9e20-3b0bbf982cb9.png)

**Comment by ezioda004** [comment]
Hi,

I agree that the code doesnt make a lot of sense and example standalone doesnt work. 
Though, these questions are answered in the next challenge when we connect the prototypes object for delegation inheritance. 

What do you think of adding a note about the code being incomplete and the function constructors arent connected yet.

**Comment by moT01** [comment]
Closing as stale. Feel free to reopen and provide a suggestion here anyone.
