### ISSUE TITLE
Understand the Immediately Invoked Function Expression (IIFE)

### ISSUE THREAD

**Issue by JESii** [freeCodeCamp/freeCodeCamp#18193]
#### Describe your problem and - if possible - how to reproduce it
Submitted this code:
```
(  () => {
  console.log("A cozy nest is ready");
})();
```
This is valid use of the new ES6 arrow syntax, but the problem says: "The function should be anonymous." and requires that we say something like:
```
( function() { ... }
```

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/understand-the-immediately-invoked-function-expression-iife

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: Version 69.0.3497.100 (Official Build) (64-bit)
* Operating System: Mac OS 10.13.6

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/486/46240498-66456980-c35d-11e8-9948-0ab33ae8e4fd.png)

**Comment by ZackWard** [comment]
I would be happy to work on this.

**Comment by xJuggl3r** [comment]
ES6 Solution still not working

![image](https://user-images.githubusercontent.com/50606269/60561243-e51e6700-9d20-11e9-819a-b4bdb6295960.png)
