### ISSUE TITLE
previous lesson about Object-Oriented Javascript

### ISSUE THREAD

**Issue by wendy0402** [FreeCodeCamp/FreeCodeCamp#1819]
All of this changes is awesome, eventhough it seems you are still fixing many bugs here. Actually, I quite miss the lesson from.
Your challenge its awesome because we learn by practice. However, several topic doesn't exists in your challenge, such as how to do inheritance.
my sugestion is keep the udacity link,it will be great! can we do that?

**Comment by benmcmahon100** [comment]
I am currently in the process of expanding the new in-house challenges and we wont ever be moving back to the old ones but if there are a list of topics that you miss from the old tutorials you can make them known and I'll be sire to include them in the next batch of challenges!

**Comment by wendy0402** [comment]
If you could please put:
* how to do inheritance in javascript
* behind the scene of how `new` method works to create new object
* topic about `this` (to which part it refers to).
I am not sure whether these all has been put  in the challenge list or not. However, it'll be great if you put it. It's fundamental, yet important.

**Comment by benmcmahon100** [comment]
We do have a section on instantiation(new) and scoping(this) but they may be too short! Be sure to take a look through them and tell me if you think that they have too little detail and i can expand them! Inheritance is also touched on but I have tried to keep the concepts to the minimum that's required for the later bonfires which will kinda build on these.

**Comment by BerkeleyTrue** [comment]
Closing. All these topics will be touched upon at some point.
