### ISSUE TITLE
[NEXT] Learna should build the curriculum on bootstrap

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#18198]
This issue is for the `next` branch

The curriculum needs to be built tin order for it to be available in the client app (package linking).

**Comment by dakebl** [comment]
I have completed and raised a pull request: https://github.com/freeCodeCamp/freeCodeCamp/pull/18216

**Comment by dakebl** [comment]
@raisedadead This is issue should be closed now.

**Comment by Bouncey** [comment]
Thanks @dakebl 👍
