### ISSUE TITLE
Applied Accessibility: Make Screen Reader Navigation Easier with the header Landmark

### ISSUE THREAD

**Issue by adachenski** [freeCodeCamp/freeCodeCamp#18191]
#### Preconditions
1. Login to "https://learn.freecodecamp.org" with valid credentials
2. Navigate to https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/make-screen-reader-navigation-easier-with-the-header-landmark/

#### Steps To Reproduce
1.  From the "tool-panel-group" on the left click on the "Watch a video" tab
2. Verify that the video is about the "header" element

#### Expected Result
Since the challenge is about the "header" element, the **video must be about the header element**

#### Actual Result
The video is about the "nav" element
#### Images
 [wrong video img](https://drive.google.com/file/d/1zqopCpElQ0sh1QD3JO4YJIZ9PHzEMTZu/view?usp=sharing)

#### Operating system
* Browser Name: Chrome
* Browser Version: 69
* Operating System:  Windows 10

**Comment by amar633** [comment]
raz ivu zuzu

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by huyenltnguyen** [comment]
Closing this issue as it has been resolved via https://github.com/freeCodeCamp/freeCodeCamp/pull/34892.
