### ISSUE TITLE
the task doesn't go through

### ISSUE THREAD

**Issue by kskotenko** [freeCodeCamp/freeCodeCamp#18194]
[Applied Visual Design: Adjust the Height of an Element Using the height Property](https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-height-of-an-element-using-the-height-property)

This task is super easy, but when done correctly - it does not allow to submit it.

**Comment by kskotenko** [comment]
![height_freecc](https://user-images.githubusercontent.com/14098621/46244115-fc6fa300-c3e2-11e8-91e0-01f198b6c73a.png)

**Comment by Nirajn2311** [comment]
@kskotenko could you post a screenshot of the browser console, you can find it in developer tools of your browser. Also could you give the details of which browser you are using?

**Comment by kskotenko** [comment]
> @kskotenko could you post a screenshot of the browser console, you can find it in developer tools of your browser. Also could you give the details of which browser you are using?

Here are the details about my browser: 

Vivaldi | 2.0.1309.29 (Stable channel) (32-bit)
-- | --
Revision | 9aa7f74440fd133ef536d2ca3eaeabb09e0685e2-refs/heads/master@{#588962}
OS | Windows
JavaScript | V8 6.9.427.23
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.102 Safari/537.36 Vivaldi/2.0.1309.29

**Comment by kskotenko** [comment]
![with the console output](https://user-images.githubusercontent.com/14098621/46572653-6adbd480-c992-11e8-971f-c52fe3aa822a.png)

**Comment by kskotenko** [comment]
![with the console output](https://user-images.githubusercontent.com/14098621/46572663-8cd55700-c992-11e8-962d-ee87db7188c8.png)

**Comment by kskotenko** [comment]
I tested it in Chrome, the same (Vivaldi has the same engine, as far as I know, so it doesn't matter actually).

**Comment by RandellDawson** [comment]
@kskotenko Would you mind testing this challenge again on our [beta site](https://www.freecodecamp.rocks/learn/responsive-web-design/applied-visual-design/adjust-the-height-of-an-element-using-the-height-property) which has many improvements over the existing production site?

**Comment by moT01** [comment]
Closing as stale. Feel free to reopen and provide further details.
