### ISSUE TITLE
Gitter embed not working

### ISSUE THREAD

**Issue by piecedigital** [FreeCodeCamp/freecodecamp#182]
I'm not sure why but the gitter chat embed is not working. My only guess is that they prevent embeds, but I know very little about iframes so I don't know.

![img](http://www.zimagez.com/miniature/screenshot-03102015-041815am.php)

I recommend removing it, or even considering replacing it with a simple proprietary chat.

###### P.S., One is already available by us. :)

**Comment by BerkeleyTrue** [comment]
The chat embed works for me. @piecedigital Are you still experiencing this issue?

**Comment by piecedigital** [comment]
Ok, it is working now.

**Comment by BerkeleyTrue** [comment]
@piecedigital It seems like it is not working on FF. Will keep this open.
