### ISSUE TITLE
[NEXT}: Curriculum - convert test suite to jest

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#18203]
This issue is for the `next` branch

We need to unify the test suites. We have a preference for `jest`, but an old test suit for the curriculum was written in `tape`.

Convert tests in `curriculum` from `tape` to `jest`

**Comment by honsq90** [comment]
hello @Bouncey, anyone working on this yet? Where should I start?

**Comment by Billmike** [comment]
@Bouncey I would love to take this up. Can't seem to find `curriculum` though.

**Comment by keremgocen** [comment]
Also happy to jump on this if you haven't started @Billmike

**Comment by Bouncey** [comment]
Closing this as I have found out the jest does not work in the browser, I will open another issue shortly.
