### ISSUE TITLE
Tests don't check tags' case sensitivity in "Basic HTML and HTML5: Inform with the Paragraph Element"

### ISSUE THREAD

**Issue by snakecase** [freeCodeCamp/freeCodeCamp#18209]
#### Describe your problem and - if possible - how to reproduce it
If you use uppercase `P` tags in this challenge, tests will output:
> Make sure your p element has a closing tag.

That took me a good few minutes of tinkering with the code here and there, refreshing the page and trying different placeholder texts to realize that I accidentally typed an uppercase `<P>` in the opening tag and autocompleted that with `TAB` to `</P>`.

Solution: either adjust autocompletion to convert tags to lowercase or include check for case sensitivity of tags in tests.

#### Add a Link to the page with the problem
[Basic HTML and HTML5: Inform with the Paragraph Element](https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/inform-with-the-paragraph-element/)

#### If possible, add a screenshot here

![error](https://user-images.githubusercontent.com/4579891/46290327-f7f2e800-c5a4-11e8-8f87-4b454355d72f.png)

**Comment by DarthOstrich** [comment]
I'd like to tackle this!

**Comment by DarthOstrich** [comment]
I am having difficulty getting the dev environment going, so I'm gonna wait until you guys push the next env, which according to the forum is next week? If someone else wants to tackle it before that, im cool with it.

**Comment by thecodingaviator** [comment]
@DarthOstrich seeing you're not up to this yet afaics I'm gonna give it a try

**Comment by DarthOstrich** [comment]
@thecodingaviator thanks! Yeah, I was having issues. Good work.

**Comment by thecodingaviator** [comment]
> @thecodingaviator thanks! Yeah, I was having issues. Good work.

Thanks
