### ISSUE TITLE
Character code instead of < symbol in tests' output in "Basic CSS: Specify How Fonts Should Degrade"

### ISSUE THREAD

**Issue by snakecase** [freeCodeCamp/freeCodeCamp#18211]
#### Describe your problem and - if possible - how to reproduce it
Running tests without commenting the call to Google for the Lobster font outputs a character code in instead of `<` symbol.

#### Add a Link to the page with the problem
[Basic CSS: Specify How Fonts Should Degrade](https://learn.freecodecamp.org/responsive-web-design/basic-css/specify-how-fonts-should-degrade/)

#### If possible, add a screenshot here
![error](https://user-images.githubusercontent.com/4579891/46292005-528e4300-c5a9-11e8-9ed9-9fe8a2052b4c.png)

**Comment by DarthOstrich** [comment]
I can try and sort this out.

**Comment by DarthOstrich** [comment]
Created a PR:
https://github.com/freeCodeCamp/freeCodeCamp/pull/18238

**Comment by DarthOstrich** [comment]
As per instructions [here](https://github.com/freeCodeCamp/freeCodeCamp/pull/18238#issuecomment-427980929), opened a new PR. #18289

**Comment by thecodingaviator** [comment]
@ezioda004 Please close the issue, fixed in #18289
