### ISSUE TITLE
Remove Option Bonus User Story from Build a Markdown Previewer project

### ISSUE THREAD

**Issue by nathanhannig** [freeCodeCamp/freeCodeCamp#18214]
https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-markdown-previewer

The Optional bonus User Story was removed from the testable suite because it is no longer relevant.
https://github.com/freeCodeCamp/testable-projects-fcc/pull/527

The User Story should also be removed from the web page.

**Comment by Ovio224** [comment]
I'll fix that

**Comment by scissorsneedfoodtoo** [comment]
Fixed in https://github.com/freeCodeCamp/freeCodeCamp/pull/18290/files
