### ISSUE TITLE
"Basic JavaScript: Use Multiple Conditional (Ternary) Operators": Indentation after return keyword fails parser even though it is valid JS

### ISSUE THREAD

**Issue by ZebulanStanphill** [freeCodeCamp/freeCodeCamp#18222]
#### Describe your problem and - if possible - how to reproduce it
In the "Basic JavaScript: Use Multiple Conditional (Ternary) Operators" challenge, the JS parser does not seem to consider the following valid:
```js
function checkSign(num) {
  return
    num > 0 ? "positive" :
    num < 0 ? "negative" :
    "zero";
}

checkSign(10);
```

If you change it to this, however, it passes:
```js
function checkSign(num) {
  return num > 0 ? "positive" :
    num < 0 ? "negative" :
    "zero";
}

checkSign(10);
```

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/use-multiple-conditional-ternary-operators

#### Tell us about your browser and operating system

* Browser Name: Firefox Beta
* Browser Version: 63.0b10
* Operating System: Antergos Linux

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/19592990/46314972-c7558300-c591-11e8-8332-3f5bba726d12.png)

**Comment by randelldawson** [comment]
It is not valid.  When you put a return on single line by itself, the function will return undefined.  Please close this, because it is not a bug. but instead a JavaScript feature.  The following would be valid (wrapping with parentheses).  

```
function checkSign(num) {
  return (
    num > 0 ? "positive" :
    num < 0 ? "negative" :
    "zero"
  );
}
```

**Comment by ZebulanStanphill** [comment]
Ah, you're right. Thanks. :smile: Closing this issue.

**Comment by ThembaniSt** [comment]
> function checkSign(num) {
>   return (
>     num > 0 ? "positive" :
>     num < 0 ? "negative" :
>     "zero"
>   );
> }

//just EPIC

**Comment by ThembaniSt** [comment]
THIS GUY DESERVES A ROUND OF APPLAUSE
