### ISSUE TITLE
Code disappeared in HTML waypoint: Give a Background Color to a Div Element

### ISSUE THREAD

**Issue by cyclehacker** [FreeCodeCamp/FreeCodeCamp#1822]
Challenge http://www.freecodecamp.com/challenges/waypoint-give-a-background-color-to-a-div-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I think this is my own fault but thought it would be useful to flag.

I'm experiencing very slow page load speeds this morning after submitting my code, so I followed the instructions below detailed in the recent update:

I can't submit my code on Waypoints/Bonfires

On Chrome: Open your dev console (F12) and click and HOLD the normal refresh button. Select 'Empty Cache and Hard Reload'.

Now the code console has disappeared or has been reduced to just the first, empty line, screen shot attached. I appreciate that these instructions were not intended for use with my particular problem, but perhaps others will do the same. Question is how do I get my code back?

![screenshot from 2015-08-17 08 33 20](https://cloud.githubusercontent.com/assets/11706144/9296597/bdbb40ba-44ba-11e5-9ef4-69957884a989.png)

**Comment by cyclehacker** [comment]
This resolved itself when I returned to the map screen selected the first waypoint in the Bootstrap section copied the code then returned to the HTML section. The code had already reloaded.

**Comment by benmcmahon100** [comment]
Yes sorry this was during a tetchy period for the server which we have now resolved! Thanks for your patience!
