### ISSUE TITLE
Your .red-box rule should include a fallback with the background set to red immediately before the existing background declaration.

### ISSUE THREAD

**Issue by Atulsinghm** [freeCodeCamp/freeCodeCamp#18231]
#### Describe your problem and - if possible - how to reproduce it
please help me regarding this issue 

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/responsive-web-design/basic-css/improve-compatibility-with-browser-fallbacks

#### Tell us about your browser and operating system

* Browser Name: chrome
* Browser Version: Version 69.0.3497.100 (Official Build) (64-bit)
* Operating System: 
![image](https://user-images.githubusercontent.com/27268962/46350776-453d8b00-c673-11e8-8f9e-478cbf26adc3.png)

**Comment by RaspberryLime** [comment]
This is not a bug with the site. You should ask for help on the forum or on chat at 
https://gitter.im/FreeCodeCamp/Help instead.

**Comment by ArielLeslie** [comment]
The forum is currently down for maintenance. You can get help from the community in the Gitter chat, our r/FreeCodeCamp subreddit, or your local FCC group.

**Comment by Darshan197** [comment]
You just need to add one line at the top on your  .red-box that is "background: red".
Try It

**Comment by Darshan197** [comment]
Did You Write Like This If NO Then Try This 
If YES Then I Don't Know Because It's Working For Me.....

<style>
  :root {
    --red-color: red;
  }
  .red-box {
    background:red;
    background: var(--red-color);
    height: 200px;
    width:200px;
  }
</style>
<div class="red-box"></div>

**Comment by Atulsinghm** [comment]
This is the right way to get it done .

<style>
  :root {
    --red-color: red;
  }
  .red-box {
    background: red;
    background: var(--red-color);
    height: 200px;
    width:200px;
  }
</style>
<div class="red-box"></div>

![image](https://user-images.githubusercontent.com/27268962/46475633-ab591800-c803-11e8-9d07-fdb474a49c65.png)


thanks a lot to all of you .

**Comment by laronis** [comment]
Thanks for sharing!

**Comment by thecodingaviator** [comment]
@Atulsinghm / @ezioda004 The solution has been given above please close

**Comment by anasansari157** [comment]
Thanks @Atulsinghm for sharing the  problem. I was stuck here too.

**Comment by r3klaw** [comment]
thanks got stuck there lol

**Comment by JanefrancessC** [comment]
Thanks. I was stuck too

**Comment by udidkl** [comment]
I was stuck too
