### ISSUE TITLE
"Basic Data Structures: Iterate Through the Keys of an Object with a for...in Statement": unnecessary semicolon in example code

### ISSUE THREAD

**Issue by ZebulanStanphill** [freeCodeCamp/freeCodeCamp#18237]
#### Describe your problem and - if possible - how to reproduce it
The "Basic Data Structures: Iterate Through the Keys of an Object with a for...in Statement" challenge contains the following code example:

```js
for (let user in users) {
  console.log(user);
};

// logs:
Alan
Jeff
Sarah
Ryan
```

Notice the semicolon after the `for` loop block. This semicolon is unnecessary and should probably be removed to avoid confusion.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/19592990/46375549-5a0d2500-c659-11e8-8f3f-71bfbed94380.png)

**Comment by erictleung** [comment]
Fixed by https://github.com/freeCodeCamp/freeCodeCamp/pull/18296
