### ISSUE TITLE
"Basic Data Structures: Combine Arrays with the Spread Operator": sentence structure mistake in challenge description

### ISSUE THREAD

**Issue by ZebulanStanphill** [freeCodeCamp/freeCodeCamp#18236]
#### Describe your problem and - if possible - how to reproduce it
The "Basic Data Structures: Combine Arrays with the Spread Operator" challenge contains a sentence that seems to be grammatically incorrect, and should be two separate sentences:

>We have defined a function spreadOut that returns the variable sentence<b>, m</b>odify the function using the spread operator so that it returns the array ['learning', 'to', 'code', 'is', 'fun'].

I think this should be:
>We have defined a function spreadOut that returns the variable sentence<b>. M</b>odify the function using the spread operator so that it returns the array ['learning', 'to', 'code', 'is', 'fun'].

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/combine-arrays-with-the-spread-operator

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/19592990/46372939-3abec980-c652-11e8-80bf-1ea3f68049c3.png)

**Comment by erictleung** [comment]
Fixed by https://github.com/freeCodeCamp/freeCodeCamp/pull/18296
