### ISSUE TITLE
Green Submit Button for Waypoints

### ISSUE THREAD

**Issue by TimCoding** [FreeCodeCamp/FreeCodeCamp#1823]
Hi! I'm working on the waypoints right now and the green submit button doesn't take me to the next lesson. I don't know if you're addressing this issue right now or if it's just an isolated problem that I need to deal with. Either ways could I have some assistance please?

Thank You,

Tim

**Comment by AryanJ-NYC** [comment]
This is similar to #1816. Use Ctrl+ENTER. Wait about a minute. The server is simply slow right now.

**Comment by benmcmahon100** [comment]
Hello this has been finally resolved! Thanks for your patience!
