### ISSUE TITLE
"Debugging: Use the JavaScript Console to Check the Value of a Variable": "Firefox" misspelled as "FireFox"

### ISSUE THREAD

**Issue by ZebulanStanphill** [freeCodeCamp/freeCodeCamp#18235]
#### Describe your problem and - if possible - how to reproduce it
The "Debugging: Use the JavaScript Console to Check the Value of a Variable" challenge contains a capitalization error:

>You can find Developer tools in your Chrome's menu or Web Console in <b>FireFox's</b> menu.

This should be <i>Firefox</i>, not <i>FireFox</li>.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/debugging/use-the-javascript-console-to-check-the-value-of-a-variable

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/19592990/46370208-9dac6280-c64a-11e8-8fab-efb4adf0aa54.png)

**Comment by ravikishorethella** [comment]
@ZebulanStanphill Hey, I would like to fix this. Shall I proceed?

**Comment by ZebulanStanphill** [comment]
@ravikishorethella It looks like someone else already jumped on it: #18241.

**Comment by ravikishorethella** [comment]
No problem @ZebulanStanphill

**Comment by Nirajn2311** [comment]
@ZebulanStanphill I am closing this issue as it has been resolved in PR #18296 but is yet to put into production.
