### ISSUE TITLE
"Object Oriented Programming: Iterate Over All Properties": description formatting typo

### ISSUE THREAD

**Issue by ZebulanStanphill** [freeCodeCamp/freeCodeCamp#18243]
#### Describe your problem and - if possible - how to reproduce it
In the "Object Oriented Programming: Iterate Over All Properties" challenge, there is the following text in the description:

>Here is how you add <code>duck’s</code> <code>own</code> properties to the array <code>ownProps</code> and <code>prototype</code> properties to the array <code>prototypeProps</code>:

"<code>duck’s</code>" should probably be "<code>duck</code>’s".

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/iterate-over-all-properties

#### If possible, add a screenshot here
![image](https://user-images.githubusercontent.com/19592990/46389014-3536a300-c695-11e8-89ed-81d5e5f041bd.png)

**Comment by Ashera138** [comment]
I would like to submit a pr for this, but I'm not sure how to do that now that [curriculum](https://github.com/freeCodeCamp/curriculum) is read-only. How should I make this change now?

**Comment by Nirajn2311** [comment]
In this repo there is another branch called `next`, it contains the curriculum. So you have to do the chnages in that branch and create a PR for that branch.

**Comment by Ashera138** [comment]
Thank you @Nirajn2311. I missed that. :) I'll go ahead and get the PR ready

**Comment by ezioda004** [comment]
Closing this issue as it got resolved in https://github.com/freeCodeCamp/freeCodeCamp/pull/18287
