### ISSUE TITLE
Next Challenge Button

### ISSUE THREAD

**Issue by Kitty-Meow** [FreeCodeCamp/FreeCodeCamp#1824]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue. The Go-to-my-next-challenge button takes me a lot of clicks just to activate it, and sometimes it just won't go to the next challenge at all. Is this a bug or is it my own computer problem?

**Comment by benmcmahon100** [comment]
We have fixed this. It was caused by the server wide slow down. Thanks for your patience!
