### ISSUE TITLE
Docs incorrectly refer to non-existent 'staging' branch, should instead refer to 'next' branch

### ISSUE THREAD

**Issue by benreckas** [freeCodeCamp/freeCodeCamp#18248]
CONTRIBUTING.md docs refer to `staging` branch which seems to have been replaced with the `next` branch.

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md#forking-the-project

* Browser Name: Firefox Dev Edition
* Browser Version: 61.0b8
* Operating System: MacOS Mojave 10.14

**Comment by arshadkazmi42** [comment]
Created PR.

**Comment by raisedadead** [comment]
Hi thanks for raising this issue. We are currently working on the contributing docs and will update the same to reflect the work flow. 

Thanks for you patience. This repository should be ready for contributions within this week
