### ISSUE TITLE
can't go to next challenge

### ISSUE THREAD

**Issue by ibiwan** [FreeCodeCamp/FreeCodeCamp#1825]
Challenge http://www.freecodecamp.com/challenges/waypoint-give-a-background-color-to-a-div-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

"go to my next challenge" was green but faded, even before I modified the code to complete the challenge.  completing the challenge didn't change anything in the UI.

**Comment by benmcmahon100** [comment]
Can you post a screenshot of this and preferably the code you used to complete the challenge so that we can just do a quick cross-reference. Thanks in advance!

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
