### ISSUE TITLE
React: Pass an Array as Props challenge clarify wording on test

### ISSUE THREAD

**Issue by peterjgrainger** [freeCodeCamp/freeCodeCamp#18256]
#### Describe your problem and - if possible - how to reproduce it
The last test in this challenge doesn't explain what is expected in enough detail.  I came across the same issue as in #17758 

I suggest fixing this by changing the text of the last test from:
The List component should render the value from the tasks prop in the p tag.
to
The List component should render the value from the tasks prop in the p tag as comma delimited text e.g. `walk dog, workout`

I'm happy to do the change if the wording looks correct

#### Add a Link to the page with the problem

https://learn.freecodecamp.org/front-end-libraries/react/pass-an-array-as-props

#### Tell us about your browser and operating system

n/a

**Comment by peterjgrainger** [comment]
@nirajn2311 you are absolutely right the instructions are very concise.  I am probably not clear enough in my communication.  I was referring to the tests for that challenge.  All of the other react challenges have tests that are very specific about what text is expected in the p tag, this seems the odd one out.  If `join(',')` is used instead of `join(', ')` then it's hard to figure out what is wrong as the test checks the exact format of the text and there is no feedback on what the issue is.

At least two people have been caught out so I can't see the harm in adding more specific text?

I don't mind doing the change myself

**Comment by Nirajn2311** [comment]
@peterjgrainger if you want to do the changes, you’ll have to do it in the “next” branch as that is where the curriculum contents is currently.

**Comment by peterjgrainger** [comment]
Added PR, let me know if I've done everything right!

**Comment by ezioda004** [comment]
Closing, as the issue got resolved in https://github.com/freeCodeCamp/freeCodeCamp/pull/18279
