### ISSUE TITLE
Intermediate Algorithm Scripting: Sorted Union: Does not adequately test nested arrays

### ISSUE THREAD

**Issue by alhazen1** [freeCodeCamp/freeCodeCamp#18265]
#### Challenge does not adequately test for cases with duplicate nested arrays. 
Using arr.includes or arr.indexOf appears to work as an adequate test for duplicates but really only pass all current tests on luck.

For instance
`uniteUnique([1, 3, 2], [1, [5]], [2, [4]])` passes as expected with `[1, 3, 2, [5], [4]]`

but
`uniteUnique([1, 2, 3, [5]], [5, 2, 2, 2,[5]])` 
would result in `[ 1, 2, 3, [ 5 ], 5, [ 5 ] ]` which would contain a duplicate.

It would be considerably more difficult to write a function that compared nested arrays. I don't believe that it was the intent for this challenge to be that difficult so maybe nested arrays should not be part of the test cases at all.

#### Intermediate Algorithm Scripting: Sorted Union
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sorted-union/

**Comment by geeseyj** [comment]
I'll take a stab at it.

**Comment by alhazen1** [comment]
@geeseyj Thank you.
