### ISSUE TITLE
Esta página web no está disponible  ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by corderogerardo** [FreeCodeCamp/FreeCodeCamp#1826]
Challenge http://www.freecodecamp.com/challenges/waypoint-style-the-html-body-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benmcmahon100** [comment]
Hi this was a temporary issue while we were making changes to the server it should be completely resolved now. If not please feel free to open a new issue
