### ISSUE TITLE
React: Render HTML Elements to the DOM Not Responding

### ISSUE THREAD

**Issue by Pheonix73** [freeCodeCamp/freeCodeCamp#18260]
#### https://learn.freecodecamp.org/front-end-libraries/react/render-html-elements-to-the-dom/

![screenshot 644](https://user-images.githubusercontent.com/36895007/46550037-c2633d00-c8cb-11e8-98f5-281792014aa5.png)

**Comment by sesn** [comment]
@Pheonix73 , You can see the error in ur screenshot. It is *ReactDOM* not *ReactDom*

**Comment by Nirajn2311** [comment]
@Pheonix73 it should be `ReactDOM.render(component, target)` with **DOM in capitals**.
Tip - Ask these questions in the forum and if it is an issue, then post it here.

**Comment by Pheonix73** [comment]
@sesn  and @Nirajn2311 thanks a lot, for your feedback it really helped and  noted.
