### ISSUE TITLE
Basic Data Structures: Modify an Array Stored in an Object does not allow a new array to be returned

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#18278]
#### Describe your problem and - if possible - how to reproduce it
In the challenge [Basic Data Structures: Modify an Array Stored in an Object](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/modify-an-array-stored-in-an-object), the following function passes the challenge.
```
function addFriend(userObj, friend) {
  // change code below this line
  userObj.data.friends.push(friend);
  return userObj.data.friends;  
  // change code above this line
}
```
The instructions state the following:

> Finish writing it so that it takes a user object and adds the name of the friend argument to the array stored in user.data.friends and returns **that** array.

Notice I emphasized the word that above.  My question is should it matter if the original array is mutated which this function does or should the function be allowed to return a new array with the correct elements?  For example, the following code returns an new array with the same elements, but does not mutate the original array.  I guess my secondary question is, should, we be teaching not to mutate the global object?
```
function addFriend(userObj, friend) {
  // change code below this line  
  return [...userObj.data.friends, friend];
  // change code above this line
}
```
Currently, this code passes the 1st and 3rd test, but fails the 2nd test, because the test is checking if the global object's friends array length is the same as the length of the array returned by the function.  Since my solution above does not mutate the original object's friends array, the length will be different.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/modify-an-array-stored-in-an-object

#### Tell us about your browser and operating system

* Browser Name: Chrome
* Browser Version: latest
* Operating System: Windows 8.1

#### If possible, add a screenshot here

![image](https://user-images.githubusercontent.com/5313213/46589571-0edf8180-ca60-11e8-900f-506f7d861830.png)

**Comment by TomLandis** [comment]
> the following code returns an new array with the same elements, but does not mutate the original array.

But the name of the challenge is : Modify an Array Stored in an Object.

So if you didn't modify the original Array, it seems like it should fail the test.
