### ISSUE TITLE
Some of my progress disapeared

### ISSUE THREAD

**Issue by FabioSeves** [FreeCodeCamp/FreeCodeCamp#1827]
Challenge http://www.freecodecamp.com/challenges/waypoint-divide-one-number-by-another-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benmcmahon100** [comment]
Can you provide your freecodecamp username and some more detail on this. Thanks in advance!

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
