### ISSUE TITLE
Comment in line 4 is wrong.

### ISSUE THREAD

**Issue by learnor** [FreeCodeCamp/FreeCodeCamp#1829]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Comment in line 4 should be 

// ourArray now equals [["happy", "joy"], "J", ["Cat"]]

**Comment by happyjunki3** [comment]
still seeing this error
