### ISSUE TITLE
[translation]: Update Spanish translations for contributing documentations

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#18307]
#### Update the following in Spanish from their English version available in [`/docs`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs) directory:

- [ ] [`/docs/spanish/CONTRIBUTING.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/spanish/CONTRIBUTING.md) from its english version at [`/CONTRIBUTING.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/CONTRIBUTING.md)

- [ ] [`/docs/spanish/README.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/spanish/README.md) from its english version at [`/docs/README.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/README.md)

- [ ] [`/docs/spanish/how-to-catch-outgoing-emails-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/spanish/how-to-catch-outgoing-emails-locally.md) from its english version at [`/docs/how-to-catch-outgoing-emails-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-catch-outgoing-emails-locally.md)

- [ ] [`/docs/spanish/how-to-setup-freecodecamp-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/spanish/how-to-setup-freecodecamp-locally.md) from its english version at [`/docs/how-to-setup-freecodecamp-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-setup-freecodecamp-locally.md)

- [ ] [`/docs/spanish/how-to-work-on-coding-challenges.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/spanish/how-to-work-on-coding-challenges.md) from its english version at [`/docs/how-to-work-on-coding-challenges.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-work-on-coding-challenges.md)

- [ ] [`/docs/spanish/how-to-work-on-guide-articles.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/spanish/how-to-work-on-guide-articles.md) from its english version at [`/docs/how-to-work-on-guide-articles.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-work-on-guide-articles.md)
 
#### Once you are ready please make a pull request, preferably one for each file.

When you make a PR for this particular issue, do not tag it with `Closes #XXXXX` instead just reference it with `#XXXXX`

**Comment by luisbd** [comment]
How could I claim `/docs/README.md` so we don't double work? Thanks

**Comment by raisedadead** [comment]
Hi @luisbd 👋!
 
Actually we just merge in the first PR for open issues. And your comment on this thread is enough. So, its yours.

Happy translating.

**Comment by luisbd** [comment]
I just open a PR for `/docs/README.md` 👉  https://github.com/freeCodeCamp/freeCodeCamp/pull/18314

**Comment by raisedadead** [comment]
@luisbd thanks a lot that was fast! Would you be interested in translating these in future as well? If yes, please keep a watch on this thread. We will be updating on the progress often

Happy contributing.

**Comment by atlc** [comment]
I'm working on /docs/spanish/CONTRIBUTING.md, I'll have a PR up later this morning.

**Comment by atlc** [comment]
I think that reference links my PR for `/docs/spanish/CONTRIBUTING.md`, but if not, I've got it at #18317 😎 👍

**Comment by atlc** [comment]
I think the above reference should link to my PR, but if not, it's available at #18317!

Thanks for all you do, freeCodeCamp 😎 👍

**Comment by Ajer1989** [comment]
I have sent a translation proposal for /docs/how-to-work-on-guide-articles.md. PR #18411

Hope it will help!

**Comment by raisedadead** [comment]
There is still work pending on this. When you make a PR for this particular issue, do not tag it with `Closes #XXXXX` instead just reference it with `#XXXXX`

**Comment by deathbystone** [comment]
Hello, I'm starting to help on the translation of the document /how-to-set-up-freecodecamp-locally.md

**Comment by annapinedo** [comment]
Working on >/docs/spanish/how-to-work-on-guide-articles.md

**Comment by mrcaste** [comment]
Hello, I've improved the CONTRIBUTING.md file #18684

**Comment by violetasdev** [comment]
Hello,

Working on _**docs/spanish/how-to-setup-freecodecamp-locally.md**_

And improving **/docs/spanish/how-to-catch-outgoing-emails-locally.md**

**Comment by violetasdev** [comment]
Improving docs/spanish/how-to-catch-outgoing-emails-locally.md

**Comment by mrcaste** [comment]
Hi, I'm improving docs/spanish/how-to-work-on-coding-challenges.md

**Comment by ordazgustavo** [comment]
Hi, can I help with /docs/spanish/how-to-setup-freecodecamp-locally.md?

**Comment by theogoulart** [comment]
Sorry, I opened a bad PR regarding README.md but already closed it. I found there was still an English part to be translated #21848

**Comment by Willibaur** [comment]
Hi there,
It would be good if `checkboxes` at the top are checked so we can see what is left to be translated.
Thanks

**Comment by hvaandres** [comment]
Where I can start helping?

**Comment by ericol** [comment]
@raisedadead sorry to put it in this issue, but is there any way somebody could help with the pull requests? I mean, there are 5K+ opened already, people are sending them in troves, and I suspect a lot of them are _a total crap_ (Like #28692) .

I guess you opened a Pandora Box with your articule about HacktoberFest.

**Comment by 3CatMax** [comment]
Hey all, not a translation, but fixes for the language bar of HTML links on the README file for Spanish, and markdown links to the How To guides that everyone has been translating. #28207. 

@MetCoder95 or anyone else looking to do translations in Spanish, you could make a copy of the 2 style guides to translate into Spanish from the English version in the doc folder. It looks like those weren't added in to the Spanish folder originally or included on this issue. Just leave the title the same, but put it in the Spanish folder😊

**Comment by tomaspozo** [comment]
Hola! to all. I believe we should have guidelines for Spanish translations, which include what treatment (formal or informal) to use when referring to actions or the user.  For example, Agregue (formal) or Agrega (informal). - I don't know if this kind of things are found in other languages.

In the last articles I've read I've seen a mix between formal and informal, and I think we should standardize (I have done it with some articles). I propose to always use informal.

Another thing that could be specified in the guidelines is: 

Challenges translations. Should they be translated?
Referrals to types and attributes (which need to be in English for proper coding). For example, type "date" not type "fecha".

If there is a guideline already, please let me know, if not, I would be happy to start one (just let me know where to put it).

Hey @raisedadead I would like to know your thoughts about this.

Thanks to you all and happy coding!

**Comment by QuincyLarson** [comment]
@tomaspozo I agree that we shouold standardize around informal. 

I agree with you that we should look out for words like "fecha" that have been accidentally translated during our automated translation process.

**Comment by hvaandres** [comment]
Hello guy,

I vote for yes, let’s do the change and I think will create a huge impact around of the world! 

Please let me know if you have more question questions or concerns.

Andres Haro
Cell: (619) 534-3190
Hvaandres@icloud.com

**Comment by QuincyLarson** [comment]
@dgrcode Thanks - I agree that these machine translations need improvement. I encourage you to dig in and start fixing them. Be sure to join gitter.im/freecodecamp/contributors if you need help getting set up 👍

**Comment by RandellDawson** [comment]
There is still work pending on this. When you make a PR for this particular issue, do not tag it with `Closes #XXXXX` instead just reference it with `#XXXXX`

**Comment by raisedadead** [comment]
Thanks for working on the translations for the "Contributing to freeCodeCamp". Here on we are making contributing to translations for contribution docs *ad hoc*. 

You are free to make pull-requests for improving these translations. We are closing the issue as these do not need tracking per se.

You can raise a fresh issue if you find something incorrect in the existing docs.
