### ISSUE TITLE
[translation]: Update Russian translations for contributing documentations

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#18308]
#### Update the following in Russian from their English version available in [`/docs`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs) directory:

- [x] [`/docs/russian/CONTRIBUTING.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/russian/CONTRIBUTING.md) from its english version at [`/CONTRIBUTING.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/CONTRIBUTING.md)

- [ ] [`/docs/russian/README.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/russian/README.md) from its english version at [`/docs/README.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/README.md)

- [ ] [`/docs/russian/how-to-catch-outgoing-emails-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/russian/how-to-catch-outgoing-emails-locally.md) from its english version at [`/docs/how-to-catch-outgoing-emails-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-catch-outgoing-emails-locally.md)

- [x] [`/docs/russian/how-to-setup-freecodecamp-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/russian/how-to-setup-freecodecamp-locally.md) from its english version at [`/docs/how-to-setup-freecodecamp-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-setup-freecodecamp-locally.md)

- [x] [`/docs/russian/how-to-work-on-coding-challenges.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/russian/how-to-work-on-coding-challenges.md) from its english version at [`/docs/how-to-work-on-coding-challenges.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-work-on-coding-challenges.md)

- [ ] [`/docs/russian/how-to-work-on-guide-articles.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/russian/how-to-work-on-guide-articles.md) from its english version at [`/docs/how-to-work-on-guide-articles.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-work-on-guide-articles.md)
 
#### Once you are ready please make a pull request, preferably one for each file.

**Comment by v1ktoryy** [comment]
Please, review https://github.com/freeCodeCamp/freeCodeCamp/pull/18482

**Comment by ckorobov** [comment]
- [x] /docs/russian/README.md 
- [x] /docs/russian/how-to-work-on-coding-challenges.md
[19345] (https://github.com/freeCodeCamp/freeCodeCamp/pull/19345)

**Comment by svitlana-galianova** [comment]
Hi, is anyone working on README translation? I'd like to help out here 😄

**Comment by 3CatMax** [comment]
#28207 Fixes the html links in the top language bar for all language README docs. Not a translation, but just link fixes. Once the Russian README files get merged, we can add the markdown style for links to all the articles in Russian too!

**Comment by sergeyradov** [comment]
started to review PRs. ping me if more help needed

**Comment by LeMarck** [comment]
Hi, guys! Please review my PR #35140

**Comment by raisedadead** [comment]
Thanks for working on the translations for the "Contributing to freeCodeCamp". Here on we are making contributing to translations for contribution docs *ad hoc*. 

You are free to make pull-requests for improving these translations. We are closing the issue as these do not need tracking per se.

You can raise a fresh issue if you find something incorrect in the existing docs.
