### ISSUE TITLE
[translation]: Update Arabic translations for contributing documentations

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#18311]
#### Update the following in Arabic from their English version:

- [ ] [`/docs/arabic/CONTRIBUTING.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/arabic/CONTRIBUTING.md) from its english version at [`/CONTRIBUTING.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/CONTRIBUTING.md)

- [ ] [`/docs/arabic/README.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/arabic/README.md) from its english version at [`/docs/README.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/README.md)

- [ ] [`/docs/arabic/how-to-catch-outgoing-emails-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/arabic/how-to-catch-outgoing-emails-locally.md) from its english version at [`/docs/how-to-catch-outgoing-emails-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-catch-outgoing-emails-locally.md)

- [ ] [`/docs/arabic/how-to-setup-freecodecamp-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/arabic/how-to-setup-freecodecamp-locally.md) from its english version at [`/docs/how-to-setup-freecodecamp-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-setup-freecodecamp-locally.md)

- [ ] [`/docs/arabic/how-to-work-on-coding-challenges.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/arabic/how-to-work-on-coding-challenges.md) from its english version at [`/docs/how-to-work-on-coding-challenges.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-work-on-coding-challenges.md)

- [ ] [`/docs/arabic/how-to-work-on-guide-articles.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/arabic/how-to-work-on-guide-articles.md) from its english version at [`/docs/how-to-work-on-guide-articles.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-work-on-guide-articles.md)
 
#### Once you are ready please make a pull request, preferably one for each file.

**Comment by Ventals** [comment]
Hi @raisedadead I can do this today)

**Comment by raisedadead** [comment]
Awesome, thanks for your help. Looking forward for a pull request.

**Comment by hananezlitni** [comment]
Can I also work on this? I can help.

**Comment by MicroDroid** [comment]
I'm working on this.

**Comment by 3CatMax** [comment]
Hi @MicroDroid, my Pull Request #28207 helps with having the README links in each language link to the correct language articles, as well as the top language links bar. Not sure that it conflicts with what you have going, although it looks like your Pull Request needs a bit of revising to merge. Awesome work!

**Comment by MicroDroid** [comment]
@3CatMax Yeah, I didn't pay attention to links, I just simply replaced `عربى` with `عربي` since it's more correct.

**Comment by raisedadead** [comment]
Thanks for working on the translations for the "Contributing to freeCodeCamp". Here on we are making contributing to translations for contribution docs *ad hoc*. 

You are free to make pull-requests for improving these translations. We are closing the issue as these do not need tracking per se.

You can raise a fresh issue if you find something incorrect in the existing docs.
