### ISSUE TITLE
Homepage images should not be in JPEG format.

### ISSUE THREAD

**Issue by ahstro** [FreeCodeCamp/FreeCodeCamp#1831]
A picture is worth a thousand words, right?
![png-vs-jpeg](http://lbrandy.com/assets/jpg_vs_png2.png)

If it's not worth a thousand words, let me explain. JPEG is a lossy format, which means that it's perfect for making big photographs smaller (in size) while still keeping them sort of good looking. However, it is not suitable for anything involving text, since its lossy algorithm, for lack of a better word, blends colors, as you can see in the image above.

**Comment by QuincyLarson** [comment]
Thanks. We'll consider this. The main reason we went with jpeg is we're using imgur for image hosting and that's what they use. I'm sure they're doing some optimization on them.

**Comment by ahstro** [comment]
@QuincyLarson Do you not have an Amazon server for hostage? I've seen a few images, e.g. the iPhone frame, hosted on amazonaws.com
