### ISSUE TITLE
[translation]: Update Chinese translations for contributing documentations

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#18310]
#### Update the following in Chinese from their English version available in [`/docs`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs) directory:

- [ ] [`/docs/chinese/CONTRIBUTING.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/chinese/CONTRIBUTING.md) from its english version at [`/CONTRIBUTING.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/CONTRIBUTING.md)

- [ ] [`/docs/chinese/README.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/chinese/README.md) from its english version at [`/docs/README.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/README.md)

- [ ] [`/docs/chinese/how-to-catch-outgoing-emails-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/chinese/how-to-catch-outgoing-emails-locally.md) from its english version at [`/docs/how-to-catch-outgoing-emails-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-catch-outgoing-emails-locally.md)

- [ ] [`/docs/chinese/how-to-setup-freecodecamp-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/chinese/how-to-setup-freecodecamp-locally.md) from its english version at [`/docs/how-to-setup-freecodecamp-locally.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-setup-freecodecamp-locally.md)

- [ ] [`/docs/chinese/how-to-work-on-coding-challenges.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/chinese/how-to-work-on-coding-challenges.md) from its english version at [`/docs/how-to-work-on-coding-challenges.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-work-on-coding-challenges.md)

- [ ] [`/docs/chinese/how-to-work-on-guide-articles.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/chinese/how-to-work-on-guide-articles.md) from its english version at [`/docs/how-to-work-on-guide-articles.md`](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/how-to-work-on-guide-articles.md)
 
#### Once you are ready please make a pull request, preferably one for each file.

**Comment by cccntu** [comment]
working on /docs/chinese/README.md

**Comment by aaronsum1102** [comment]
working on /docs/chinese/CONTRIBUTING.md

**Comment by dingjy94** [comment]
Hi @raisedadead ,
I plan to work on  /docs/chinese/how-to-work-on-coding-challenges.md. 

However, some of these contributing documentations are a mix of Traditional and Simplified Chinese. I can only do it in Simplified Chinese so I want to make sure which version of Chinese you actually prefer?

**Comment by dingjy94** [comment]
working on /docs/chinese/how-to-catch-outgoing-emails-locally.md

**Comment by frusagi** [comment]
working on /docs/chinese/how-to-work-on-guide-articles.md

**Comment by 3CatMax** [comment]
I went through (before finding this) and had fixed the markdown link and locations to go to all the correct files. Although I do not know Chinese, the patterns are the same.  #28207

**Comment by frusagi** [comment]
Oh, i didn't know... Because I edited the translation for the first half too. Thanks for informing, is there other files where you have already worked on?

**Comment by 3CatMax** [comment]
@frusagi I didn't edit the text, only the links and the top part with the links to other languages. I'm totally new to this (too?) and figuring it out as I go. Turns out I could see where my pull request had conflicts with any new code that has been merged in, and decide line by line what to change or what to keep. Keep doing awesome stuff 👍😜

**Comment by daorren** [comment]
working on /docs/chinese/how-to-setup-freecodecamp-locally.md

**Comment by raisedadead** [comment]
Thanks for working on the translations for the "Contributing to freeCodeCamp". Here on we are making contributing to translations for contribution docs *ad hoc*. 

You are free to make pull-requests for improving these translations. We are closing the issue as these do not need tracking per se.

You can raise a fresh issue if you find something incorrect in the existing docs.
