### ISSUE TITLE
[docs] Create translation guidelines for guide articles and coding challenges

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#18313]
@beaucarnes @QuincyLarson 

Can you please create a simple guideline for contributors explaining the workflow and maybe a couple tools in translating guide articles and coding challenges.

These should include instructions like the seed code should be left untouched, etc.

Thanks.

**Comment by RandellDawson** [comment]
@raisedadead Can this issue be closed?
