### ISSUE TITLE
Add a build test to check all file names maintain case.

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#18325]
Unix does not differentiate between different file names, bases on lowercase/capitalcase

https://twitter.com/raisedadead/status/1050495401252581376

This is a cause of frustration, we need a CI test to handle this, and let it be known on the PR builds

**Comment by eragon512** [comment]
hi, is this issue available? I'd like to take it up, if so

**Comment by Sathish-kumar-Subramani** [comment]
> hi, is this issue available/open? I'd like to take it up, if so

Hi eragon512,
Argh! I should have mentioned here before taking up the issue.
I've created a pull request for the same.

**Comment by eragon512** [comment]
hey @Sathish-kumar-Subramani , chill, no worries!

**Comment by raisedadead** [comment]
This is resolved.
