### ISSUE TITLE
False validation

### ISSUE THREAD

**Issue by youssefshb** [FreeCodeCamp/FreeCodeCamp#1833]
Challenge http://freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. 
With this code 
```javascript
  $(document).ready(function() {
  $("button").addClass("animated shake btn-primary");
  $("#target1").addClass("animated shake btn-primary");
  $("button").addClass("animated shake btn-primary");
  });
```
It validate the task "Use the $(".btn") selector." which as you can see in my code didn't use $(".btn").

**Comment by jbmartinez** [comment]
Created PR #1995
