### ISSUE TITLE
Hex code is wrong

### ISSUE THREAD

**Issue by tourn171** [FreeCodeCamp/FreeCodeCamp#1837]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-shades-of-gray has an issue. Please describe how to reproduce it, and include links to screenshots if possible. Text says to make the text light gray however, Hex code is 111111 this is a dark gray almost black.

**Comment by QuincyLarson** [comment]
Thanks for catching this. I've fixed this and we'll deploy it soon :)
