### ISSUE TITLE
Code scroll doesn't work

### ISSUE THREAD

**Issue by Toytradeadman** [FreeCodeCamp/FreeCodeCamp#1840]
Hello, 

The code scroll doesn't work on all challenges, I have to use page up and down to work through the code plus the undo(not the reset) doesn't work. 

Timothy J.

Challenge http://www.freecodecamp.com/challenges/waypoint-use-an-id-attribute-to-style-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benmcmahon100** [comment]
Hi @Toytradeadman what browser are you using. Challenges currently wont function on IE, EDGE and Safari

**Comment by Toytradeadman** [comment]
@benmcmahon100  I'm using Google Chrome

**Comment by benmcmahon100** [comment]
This is quite odd you should get a scroll bar just to the left of the code editor
Can you also post a screenshot for me?

**Comment by Toytradeadman** [comment]
it worked before they did all these updates to freecodecamp the only thing that didn't was the undo. it does have the scroll bar but it doesn't move

**Comment by benmcmahon100** [comment]
Then you should be able to see all the code! A screenshot would be really useful so that i can figure out what's going on

**Comment by Toytradeadman** [comment]
I get the picture of a cell phone with a circle showing it can't be move d

![freechrome](https://cloud.githubusercontent.com/assets/13581534/9305084/4568ffa6-44bc-11e5-9905-398b2a7d244b.jpg)

**Comment by Toytradeadman** [comment]
in full screen mode I almost see all the code

**Comment by benmcmahon100** [comment]
So it's the result window that's broken? The code there looks fine

**Comment by Toytradeadman** [comment]
correct

**Comment by benmcmahon100** [comment]
So the code scroll works perfectly and the preview does not
Okay so is it getting hidden behind the footer?
Or is the html overflowing past the end of the phone?

**Comment by Toytradeadman** [comment]
the code scroll is not working. If I hit the arrows or click and hold the scroll bar it doesn't move I don't why a picture of a cell phone is there when I do that.

**Comment by benmcmahon100** [comment]
Oooooooooooooh. That's not good... Thanks so much for finding this I know whats wrong now! :p

**Comment by Toytradeadman** [comment]
welcome
