### ISSUE TITLE
ES6: Use getters and setters to Control Access to an Object Passing Test Without Implementation

### ISSUE THREAD

**Issue by TomerPacific** [freeCodeCamp/freeCodeCamp#18400]
*Describe your problem and how to reproduce it:**
On the challenge ES6: Use getters and setters to Control Access to an Object, the challenge passes without creating a getter and a setter.

**Add a Link to the page with the problem:**
[Challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-getters-and-setters-to-control-access-to-an-object)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 69.0.3497.100 (Official Build) (64-bit)
* Operating System: Windows 7 64bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![fccbug](https://user-images.githubusercontent.com/23402988/46857980-eadec000-ce12-11e8-98fb-45fcfc921f1d.jpg)

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue appears to be very similar to issue #17403, so I am closing it as a duplicate.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you, and happy coding.
