### ISSUE TITLE
[Guides] Permanent "expand it" link on existing guide pages

### ISSUE THREAD

**Issue by AdrianSkar** [freeCodeCamp/freeCodeCamp#18410]
So, now that the Guide repo has been archived I'll bring [this issue](https://github.com/freeCodeCamp/guide/issues/8649) here as I think it might be helpful if solved:

> I've seen this link on every stub page for campers to add guides;
> 
> ![image](https://user-images.githubusercontent.com/12052430/46861847-e8c93100-ce13-11e8-9eb3-a8b0f579ab33.png)
> and I wonder if we should maintain that (like adding a "mini-footer") on existing ones so we all have easy access to them again if we want to add more content, fixes, improvements, etc.

Edit: I know we could all add the link when editing those guide pages but the idea would be to implement a "footer" on all of them to provide easy access (right know you have to search for the file in the Github repo and then edit it).
Edit 2: I also just realized that those links now lead to the archived repo so this could be a good time to rearrange them.

**Comment by moinshaikh** [comment]
+1, Adrian.

@QuincyLarson I got your notification via one of my past PR - regarding archiving the /guides repo and moving over to freeCodeCamp/freeCodeCamp repo.

However, I was wondering where can we look for the stub articles now? I tried to locate them under new repo but couldn't find any. Am I missing out on something?

**Comment by RandellDawson** [comment]
@raisedadead Is this an issue on which we should add the `help wanted` label?  It might not be a bad idea to link directly to the guide article on Github `master` branch using a footer component or if nothing else, maybe a link to [How to Work on Guide Articles](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-guide-articles.md) ?

**Comment by moT01** [comment]
This has been added with [this pr](https://github.com/freeCodeCamp/freeCodeCamp/pull/35567) and is viewable on [beta](https://www.freecodecamp.rocks/guide/accessibility)
