### ISSUE TITLE
Invisibile goals

### ISSUE THREAD

**Issue by andall1811** [FreeCodeCamp/FreeCodeCamp#1841]
Challenge http://www.freecodecamp.com/challenges/waypoint-override-class-declarations-with-inline-styles has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When in the middle of typing the inline style, the goals for the waypoint become invisible.
![bug](https://cloud.githubusercontent.com/assets/13506634/9304250/fbea84f6-44b3-11e5-85b0-2ff234a9fa8f.JPG)

**Comment by watsondr** [comment]
![image](https://cloud.githubusercontent.com/assets/8251511/9304717/755191a2-452e-11e5-89ca-7cf6d3382e50.png)

I am seeing a similar issue, goal #4 has disappeared but is giving an error.

**Comment by benmcmahon100** [comment]
These errors have popped up as there are errors in your code and we cannot prevent the error on our side

**Comment by benmcmahon100** [comment]
Please check in the main or help chat on gitter in future to make sure your code is correct before going to the github issues. It will also mean that you will get a response quicker which is always good! :p
