### ISSUE TITLE
Incorrect text

### ISSUE THREAD

**Issue by andall1811** [FreeCodeCamp/FreeCodeCamp#1844]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-shades-of-gray has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The description says we'll give the element a dark gray color with #111111.  The goal for the waypoint says light gray.  This is incorrect.
![bug](https://cloud.githubusercontent.com/assets/13506634/9304539/36a836a8-44b7-11e5-8b27-4449dade6349.JPG)

**Comment by QuincyLarson** [comment]
Thanks for catching this! I thought I'd fixed it. Will do now.
