### ISSUE TITLE
PHP syntax overview is outside of the PHP heading

### ISSUE THREAD

**Issue by shamamaz** [freeCodeCamp/freeCodeCamp#18450]
**Describe your problem and how to reproduce it:**
A PHP syntax overview article is outside of the PHP heading.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/php-syntax-overview/

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 69.0.3497.100 
* Operating System: Mac OS High Sierra 10.13.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="1248" alt="screen shot 2018-10-12 at 09 14 03" src="https://user-images.githubusercontent.com/11925430/46871364-32f3e780-cdff-11e8-8f68-cf6b8bf51329.png">

**Comment by Beth106** [comment]
Can I take this one? This would be my first ever pull request to a real issue.

To fix it I would drag the "PHP Syntax Overview" folder into the "PHP" folder here:
https://github.com/freeCodeCamp/freeCodeCamp/tree/master/client/src/pages/guide/english
