### ISSUE TITLE
Bonfire: Truncate a string

### ISSUE THREAD

**Issue by richyvk** [FreeCodeCamp/FreeCodeCamp#1845]
Challenge http://www.freecodecamp.com/challenges/bonfire-truncate-a-string has an issue.

Instructions no longer tell you that length that the string should be truncated to, i.e length provided by second parameter.

**Comment by bugron** [comment]
@richyvk thanks for posting this issue!
@BerkeleyTrue seems this issue is solved and can be closed, thanks.

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
