### ISSUE TITLE
misleading comments

### ISSUE THREAD

**Issue by benflinn** [FreeCodeCamp/FreeCodeCamp#1846]
Challenge http://www.freecodecamp.com/challenges/waypoint-build-javascript-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

there are no commas in the comments section, misleading the camper: 

//var ourDog = {
//   "name": "Camper"
//   "legs": 4
//   "tails": 1
//   "friends": ["everything!"]
//};

^no commas after each property.

**Comment by AryanJ-NYC** [comment]
This was fixed in pull request #1811.
