### ISSUE TITLE
text-danger

### ISSUE THREAD

**Issue by cove9988** [FreeCodeCamp/FreeCodeCamp#1847]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-spans-for-inline-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benmcmahon100** [comment]
Hello can you please explain what this is?

**Comment by cove9988** [comment]
Here's how you would do this with the "Top 3 things cats hate" element: <p>Top 3 things cats <span class"text-danger">hate</span></p>

should be class="text-danger"

**Comment by benmcmahon100** [comment]
Ah yes thanks for spotting this! Please be sure to include lots of detail when reporting issues otherwise we cant fix them!
