### ISSUE TITLE
Extra ">" at end of example

### ISSUE THREAD

**Issue by james-rose** [FreeCodeCamp/FreeCodeCamp#1848]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-an-id-attribute-to-style-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Should that '>' be there at the end of 
Here's an example of how you can take your element with the id attribute of cat-photo-element and give it the background color of green. In your style element: #cat-photo-element { background-color: green; }>
?

<img width="271" alt="screenshot 2015-08-17 14 56 24" src="https://cloud.githubusercontent.com/assets/2235103/9305250/28f6e566-44f0-11e5-8c9b-29b3034d437e.png">

**Comment by AryanJ-NYC** [comment]
No, it shouldn't. @benmcmahon100, I can take care of this if that's not a problem.

**Comment by benmcmahon100** [comment]
If you want to take a stab go for it!
