### ISSUE TITLE
Unclear instruction

### ISSUE THREAD

**Issue by james-rose** [FreeCodeCamp/FreeCodeCamp#1849]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-an-id-attribute-to-style-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

<img width="328" alt="screenshot 2015-08-17 14 58 06" src="https://cloud.githubusercontent.com/assets/2235103/9305278/713b2a62-44f0-11e5-98ea-25ec5074e0db.png">

"Make sure your form element has both an id attribute."   if you say 'both', it would mean an id attribute AND something else, right?

**Comment by AryanJ-NYC** [comment]
On it.
