### ISSUE TITLE
The automatically placed code is "return str;" while the function (according to the test) shall return boolean.

### ISSUE THREAD

**Issue by lladynski** [FreeCodeCamp/FreeCodeCamp#1852]
Challenge http://www.freecodecamp.com/challenges/bonfire-confirm-the-ending has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benmcmahon100** [comment]
This is not and issue it's just to ensure that the function returns something at the start. It is the students job to make it return a boolean
