### ISSUE TITLE
classname all lowercase still passes test

### ISSUE THREAD

**Issue by JayWIlsonJr** [FreeCodeCamp/FreeCodeCamp#1854]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

if I used the class name "fadeOut" or "fadeout" the challenge still passes either way. These are different class names  because one is camel cased the other is lower case.

**Comment by jbmartinez** [comment]
Chrome and Firefox seem to be case insensitive, so "fadeout", "fadeOut", "Fadeout" and even "fADeouT" have the same effect. I don't know if that's the way supposed to be or just a bug in the browsers.

**Comment by jbmartinez** [comment]
It passes tests even without using the target id, which is the objective
![jquery](https://cloud.githubusercontent.com/assets/4247923/9308213/977f2bd4-44cc-11e5-842a-26aa958669a0.png)

**Comment by jbmartinez** [comment]
Creadted PR #1866 which fixes the issue reported in my previous comment. However, I think that the test could be more robust if it checks only one case ("fadeOut")

**Comment by bugron** [comment]
Closing this issue as the PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/1866 is merged.
