### ISSUE TITLE
Waypoint: Use Hex Code to Color Elements Blue

### ISSUE THREAD

**Issue by saadanerdetbare** [FreeCodeCamp/FreeCodeCamp#1855]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-hex-code-to-color-elements-blue has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I think the test should not be casesensitive when the rules stylessheets is not

**Comment by benschenker** [comment]
I cannot replicate this issue: `background-color: #0000ff;` works fine for me
