### ISSUE TITLE
Passing tests depend on whitespace

### ISSUE THREAD

**Issue by labiej** [FreeCodeCamp/FreeCodeCamp#1858]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The working code (the enter inside the anonymous function is optional)
```
<script>
  $(document).ready(function(){

  });
</script>
```

However there are several _versions_ that do not satisfy the two last tests.

Fails test 3 (the space between `[...]ready(` and `function`)
```
<script>
  $(document).ready( function(){ 
  
  });
</script>
```

Fails test 4 (closing with `});`)
```
<script>
  $(document).ready(function(){ });
</script>
```

Given that javascript is a language where whitespace is (mostly) insignificant.

**Comment by benmcmahon100** [comment]
This is just down to the challenge creator using their personal style. I would argue as someone who has been using js for a while and not the challenge creator that the example has given the general practice answer as accounting for every possible permutation would create slow inefficient and un-readable tests

**Comment by labiej** [comment]
I understand that, but I can see a lot of questions coming on gitter regarding this.
http://www.freecodecamp.com/challenges/waypoint-delete-your-jquery-functions
has the same tests.

A solution might be to remove whitespace before checking.
Another one could be adding optional whitespaces in the test-cases.

`$(document).ready(\s*function(){`
would fix the first example I gave.

`\$\(document\).ready\(\s*function\(\)\{\s*\}\)\g;`
would catch the cases I introduced. [Example on regexr](http://regexr.com/3bjn0)
It would however break if anything is added inside the curly braces.

It's a minor change in my opinion. Of course there are still some cases where this regex fails.
For example if one use `function ()` or `function( )`.
So I get your point of every possible permutation.
Perhaps adding a warning that they should adhere to the whitespace from the code in the text is a better solution.

**Comment by benmcmahon100** [comment]
That would then create difficulty with tests the have strings with spaces. The easy fix is for people to follow the example and docs completely as we have tried to replecate them as close as possible

**Comment by catapixel** [comment]
Just giving a +1 to this as I just had to look it up because I was failing the 4th test for this very reason. Also noticed a typo in the 3rd test. It is missing a closing parentheses after "document".

![image](https://cloud.githubusercontent.com/assets/1958489/9333094/020a5b58-4596-11e5-9c43-531149cf0cea.png)

**Comment by BerkeleyTrue** [comment]
The best option is to add comments

```html
<script>
  $(document).ready(function(){
// do not modify code above

// do not modify code below.
  });
</script>
```

Regex is the reason a lot of test are so hard to get right, due to having to cover all the edge cases. Throwing more regex at the problem will only add more problems as @benmcmahon100 stated above.

**Comment by AKWintermute** [comment]
I agree with labiej. You should use something that normalizes the white space, like a code beautifier, before you check the solution if you're going to check on white space.

**Comment by junhaoyap** [comment]
Adding the script and the document ready defeats the purpose of the lesson though, so we might have to think of another way about this (like normalizing white space etc)
