### ISSUE TITLE
typo mistake. #111111 is dark grey, not light grey

### ISSUE THREAD

**Issue by eliberator** [FreeCodeCamp/FreeCodeCamp#1859]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-shades-of-gray has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![bugdarkgreytypo](https://cloud.githubusercontent.com/assets/7369989/9307881/4153122c-4501-11e5-98b0-bf72e77179d8.png)

**Comment by AryanJ-NYC** [comment]
Already fixed with merge #1821.
