### ISSUE TITLE
Courseware showJS completion modal - Ctrl+Enter shortcut doesn't work

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/freecodecamp#186]

**Comment by terakilobyte** [comment]
Ctrl enter seems to advance coursewares along. I thought we had agreed not to flash a modal except for on marked exercises (a flag will need to be passed) to not disrupt the flow since the coursewares are pretty quick.

**Comment by QuincyLarson** [comment]
To clarify, this is on the JavaScript challenges. CTRL + Enter will run the challenge, but if your answer is correct, pressing CTRL+Enter won't advance you to the next one, which is definitely the desired behavior (it even says that on the modal's next challenge button). This functionality seems to work on bonfires and video challenges, but not here.

**Comment by terakilobyte** [comment]
The twitter button also looks jacked up. It's probably a tabbing issue. I'll give it a look.
