### ISSUE TITLE
Counting points of realized waypoints

### ISSUE THREAD

**Issue by dokkillo** [FreeCodeCamp/FreeCodeCamp#1860]
Hi,

I did a waypoint again (waypoint 54) and it sums 1 point more to my account. I guess it is a bug.

**Comment by benmcmahon100** [comment]
Is that the third one?

**Comment by dokkillo** [comment]
what do you  mean?

**Comment by benmcmahon100** [comment]
You were saying in the chat that it had happened twice. Is it continuously
 adding points on each completion?

**Comment by dokkillo** [comment]
Yes, it adds points for each completion, and I did that waypoints last weekend, and this waypoints shows as finished in my map

**Comment by QuincyLarson** [comment]
This is a high priority issue. I'll ask @berkeleytrue to take a look at it. Thanks!

**Comment by dokkillo** [comment]
Hi,

Yesterday I installed a fresh FCC version in my computer, and this bug dont exist. But this bug exist in production version.

**Comment by BerkeleyTrue** [comment]
fixed
