### ISSUE TITLE
"Use the provided code three times. One for each slot" doesn't check as complete.

### ISSUE THREAD

**Issue by onegronm** [FreeCodeCamp/FreeCodeCamp#1862]
Challenge http://www.freecodecamp.com/challenges/waypoint-give-your-javascript-slot-machine-some-stylish-images has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I setup the random images for each slot and it works as intended when I click "Go". The first checkpoint "Use the provided code three times. One for each slot." is never marked as completed. The other three do get checked.

![slotmachine](https://cloud.githubusercontent.com/assets/5638902/9308597/04d11430-44d3-11e5-8f66-f787dc85f090.png)

**Comment by onegronm** [comment]
Never mind. It's working for me now. I think maybe the problem was that I was starting with double quotes rather than single ones.

**Comment by Faseehx** [comment]
can you tell me hows you achive that......? screen short please!!
