### ISSUE TITLE
Waypoint: Override All Other Styles by using Important

### ISSUE THREAD

**Issue by yuliyaskrip** [FreeCodeCamp/FreeCodeCamp#1863]
Challenge http://www.freecodecamp.com/challenges/waypoint-override-all-other-styles-by-using-important has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
followed all directions, however one check mark isn't turning green. 
![image](https://cloud.githubusercontent.com/assets/13720298/9309142/c3c191e2-44d5-11e5-8e02-464a9bd1251f.png)

**Comment by benmcmahon100** [comment]
You aren't able to add the new line before !important. Removing that should allow you to pass
