### ISSUE TITLE
The page for the Simon game is showing the tic tack toe video 

### ISSUE THREAD

**Issue by thepeted** [FreeCodeCamp/FreeCodeCamp#1864]
Challenge http://freecodecamp.com/challenges/zipline-build-a-simon-game has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by SaintPeter** [comment]
This is still true.

Ref:
#1906
#2063

**Comment by denmch** [comment]
Possibly related to #1800

**Comment by benmcmahon100** [comment]
Sorry I didn't mean to close this without a comment! There is no video for the simon game so i think the other one was stuck in so as not to break the view. This will be fixed as soon as @QuincyLarson or some enterprising individual creates a giff or a video to go with this challenge

**Comment by BerkeleyTrue** [comment]
fixed
