### ISSUE TITLE
Code box scrollbar doesn't work

### ISSUE THREAD

**Issue by diegomm77** [FreeCodeCamp/FreeCodeCamp#1865]
The scrollbar in the code box is not working (in the Waypoints). I'm using firefox 39 on Windows 10. It seems that the image of the cell phone is overlapping with the scrollbar,  because when I try to scroll it's like I'm dragging the cell phone.

**Comment by benmcmahon100** [comment]
This has been fixed but not deployed. Thanks for reporting this!
