### ISSUE TITLE
Type in myArray.shift(); on line 8, myRemoved variable also shifts. Pushing to myRemoved shows no user test.

### ISSUE THREAD

**Issue by srikinfin** [FreeCodeCamp/FreeCodeCamp#1867]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-shift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![shift](https://cloud.githubusercontent.com/assets/2540785/9309581/2eed860e-4528-11e5-81bd-9a188c1a94b2.png)

**Comment by benschenker** [comment]
Hey @srikinfin thanks for posting an issue!

In the future, please follow our bug reporting guidelines as that will help you resolve these problems quickly: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug

I don't completely understand the problem you are having, and am having difficulty replicating the issue.  After going through the steps above if you still have a bug to report in the site, reopen this issue.

This issue can be closed.

**Comment by BerkeleyTrue** [comment]
@srikinfin Try reseting your code and trying again.

Happy Coding!
