### ISSUE TITLE
Waypoint: Use Bracket Notation to Find the Last Character in a String - 2nd Test Incorrectly Passes

### ISSUE THREAD

**Issue by AryanJ-NYC** [FreeCodeCamp/FreeCodeCamp#1868]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-last-character-in-a-string has an issue.

Test 2 presumably checks that line 7 (var lastLetterOfLastName) uses String.length property.  The test returns true with the initial, unaltered code since it is used in line 3. This is probably not intentional.

**Comment by benschenker** [comment]
Thanks @AryanJ-NYC, 

Confirmed that on clean challenge load, test 2 passes incorrectly.

**Comment by bugron** [comment]
Closing this issue as it is [fixed](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/basic-javascript.json#L224).
