### ISSUE TITLE
Requirements in chall js-slot-machine

### ISSUE THREAD

**Issue by cookie-troll** [FreeCodeCamp/FreeCodeCamp#1869]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-javascript-slot-machine has an issue. Not precisely a bug, but I didn't know any other way how to report it. The point is, when boundaries are given, I think it's pointless requiring strict Math.random()*(max-min+1)+min, when you can insert certain values.

**Comment by benschenker** [comment]
Closing as #2278 has better description
