### ISSUE TITLE
README references Trello instead of waffle.io

### ISSUE THREAD

**Issue by barnettjw** [FreeCodeCamp/freecodecamp#187]
When FreeCodeCamp/freecodecamp#183 was closed by updating the link from Trello to waffle.io the text of the next sentence wasn't updated on *README.md*

> If your issue or feature isn't on the board, either open an issue on this GitHub repo or message Quincy Larson to request to be added to the Trello board

**Comment by BerkeleyTrue** [comment]
@barnettjw Thanks for point that out. Would you like to create a PR?

**Comment by QuincyLarson** [comment]
Thanks for pointing this out. I fixed and merged.
