### ISSUE TITLE
Incorrect instructions on Waypoint: Manipulate Arrays With pop

### ISSUE THREAD

**Issue by erik-lauridsen** [FreeCodeCamp/FreeCodeCamp#1870]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-pop has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The comments in the code instruct to only change code below line 9.  This is misleading, as the solution requires changing 

var removed = myArray

to

var removed = myArray.pop()

**Comment by erik-lauridsen** [comment]
The solution is just to move the comment up higher, I could/would do this myself, but I'm new to git and don't know how to find the file or submit the change.

**Comment by androszr** [comment]
agree, seemed so confusing google led me here.

**Comment by Cadence22** [comment]
Same issue. Thanks for clarifying.

**Comment by LookOnTheBrightSide** [comment]
confusing, should be looked into. thanks

**Comment by Desicri** [comment]
Agreed.

**Comment by MLichtenstern** [comment]
Googling is definitely part of the skill. I was having a hard time interpretting the instructions at first, but with this thread, I see that with the example in the comment lines 1-5, that numbers is analogous to myArray.

By adding the .pop() to myArray as in line 5 with numbers, it pops the last value, ["cat", 2], off the array.

**Comment by mgm0136** [comment]
yeah, i was wondering why my code didn't work. lol.

**Comment by undeadmonkey** [comment]
what exactly is supposed to be typed and where.  I'm at a total loss.
thnx in advance for the help
Monkey

**Comment by undeadmonkey** [comment]
go it.  just add 
  = myArray.pop(["cat", 2]);
to the end of var removedFromMyArray

so confusing

**Comment by OgunniyiOwamamwen** [comment]
THE CODE ANSWER
Manipulate Arrays With pop


// Example
var ourArray = [1,2,3];
var removedFromOurArray = ourArray.pop(); 
// removedFromOurArray now equals 3, and ourArray now equals [1,2]

// Setup
var myArray = [["John", 23], ["cat", 2]];

// Only change code below this line.
var removedFromMyArray = myArray.pop();

**Comment by Saif-Shines** [comment]
Thanks @OgunniyiOwamamwen  !
Your Solution Helped alot!
