### ISSUE TITLE
Project Euler challenges breaks Windows filename length restrictions

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/freeCodeCamp#18722]
**Describe the bug**
The Project Euler challenge filenames are larger than the limits specified by Windows 10 on filename lengths. I came across this while trying to get my local repo up to date with `master`, and it threw an error -

![err](https://user-images.githubusercontent.com/11348778/46903511-12ca3400-cea4-11e8-83a7-bae6e2600917.png)

**To Reproduce**
1. `git fetch upstream master`
2. `git reset --hard upstream/master`
3. See error

**Expected behavior**
Filename should be truncated to match the length restrictions on MS Windows.

**Screenshots**

![err1](https://user-images.githubusercontent.com/11348778/46903570-f8dd2100-cea4-11e8-88e5-789b74876d3a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 69

**Comment by raisedadead** [comment]
Hey @NitronR can you help us with this?


@Bouncey Can you confirm that we can name the files whatever we want because the titles are picked from the front matter?

If that is true, we can rename all the project euler files which are absurdly lengthy.

**Comment by NitronR** [comment]
@raisedadead Yeah I can help. If it turns out that files the file name and the titles are independent then I can rename the files using this pattern: problem-{number}{other stuff}. I think the initial part is sufficient and the other stuff can be removed. What do you think?

**Comment by raisedadead** [comment]
@NitronR I ll get back to you with the exact action to be taken, but can you give me more context about why we have a string like "Problem No" at all in the first place? 

Was this meant for ordering or this is something to do with the actual content requirement itself?

I really find these aesthetically un-appealing. :)

**Comment by BhaveshSGupta** [comment]
Hello,

**Comment by BhaveshSGupta** [comment]
Hello,
I think there is way to bypass the path length, I was trying to install python today on my windows today and I got this. I need to dig more. 
![image](https://user-images.githubusercontent.com/4209637/47358735-89e0a300-d6c2-11e8-9117-068852a5fcbf.png)

So I think there is way to do that.

**Comment by Nirajn2311** [comment]
@Manish-Giri The following command helped me get over this issue
```shell
git config --system core.longpaths true
```

I was using Git Bash, so I'm not sure if it will work in cmd.

**Comment by Manish-Giri** [comment]
@Nirajn2311 Thanks! I tried that command, but I removed the `--system` flag. I didn't want to affect the restriction on the system level just to get things up and running. Was able to get my local setup updated that way.

However, for the long run, I think it's unreasonable to ask users to alter their system restrictions (both project level & system level) to setup fcc on their machine.

**Comment by Bouncey** [comment]
@Manish-Giri The curriculum and guide have been moved to the project root. Does that solve this issue? I cannot test myself as I do not use windows

**Comment by scissorsneedfoodtoo** [comment]
@Manish-Giri, just took a look at this on my Windows machine and the filename lengths don't seem to be a problem anymore. Granted, my path is a couple of characters shorter than yours, but it seems safe to close this for now.
