### ISSUE TITLE
Manipulate Arrays with Shift - Incomplete Directions

### ISSUE THREAD

**Issue by AryanJ-NYC** [FreeCodeCamp/FreeCodeCamp#1875]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-shift has an issue:

![image](https://cloud.githubusercontent.com/assets/8263430/9311652/9c95ac92-44e5-11e5-8378-22643115e82d.png)
The directions should state that myRemoved should contain the first element of myArray.

**Comment by bugron** [comment]
Related to: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1867

**Comment by benschenker** [comment]
Thanks @AryanJ-NYC this should be an easy fix.

```
Set `myRemoved` to the first value of `myArray` using `shift()`.
```
