### ISSUE TITLE
Did not need a semi-colon at the end of the font-family:Monospace statement to go to next challenge. I thought each attribute had to end with a ";".

### ISSUE THREAD

**Issue by pguilbau** [FreeCodeCamp/FreeCodeCamp#1880]
Challenge http://freecodecamp.com/challenges/waypoint-set-the-font-family-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

To reproduce, add the statement "font-family:Monospace" and you will be able to go to next challenge.

I thought you needed a semi-colon at the end of each attribute.

![image](https://cloud.githubusercontent.com/assets/13837777/9311960/6932dfec-44df-11e5-91c1-6165ee238313.png)

**Comment by AryanJ-NYC** [comment]
A semi-colon isn't completely necessary for the last element in CSS. However, it's definitely good practice.

More information here:
http://stackoverflow.com/questions/11939595/leaving-out-the-last-semicolon-of-a-css-block

**Comment by pguilbau** [comment]
Thank you, AryanJ,

Paul
