### ISSUE TITLE
Code is not able to execute on internet explorer

### ISSUE THREAD

**Issue by manmohan24nov** [FreeCodeCamp/FreeCodeCamp#1882]
Challenge http://www.freecodecamp.com/challenges/bonfire-meet-bonfire has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by bugron** [comment]
Can't run this challenge too. Tried in IE 10 and 11.
And more than that neither Basic JavaScript challenges nor any of bonfires are working in IE (but jQuery challenges work). Clicking the Run button takes zero effect. It doesn't show even any error!

**Comment by BerkeleyTrue** [comment]
Challenges do not work in Explorer/Edge due to limitations of that browser. see: #1566


Happy Coding
