### ISSUE TITLE
Waypoint: Add your JavaScript Slot Machine Slots - Bug in Tests

### ISSUE THREAD

**Issue by AryanJ-NYC** [FreeCodeCamp/FreeCodeCamp#1883]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-your-javascript-slot-machine-slots has an issue.

![image](https://cloud.githubusercontent.com/assets/8263430/9312270/b134fe7e-44e9-11e5-9e7f-b8b8d888e58b.png)
I just wrote "if" and the test passed.

**Comment by jbmartinez** [comment]
I cannot reproduce this, I guess it's the same bug reported in #1503 and #1966

**Comment by benschenker** [comment]
Closing as duplicate
