### ISSUE TITLE
wrong code

### ISSUE THREAD

**Issue by HanzoCode** [FreeCodeCamp/FreeCodeCamp#1884]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-javascript-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

// ourDog.bark("arf!"); is it ok ?
shouldn't be 

ourDog.bark = "arf!";?

**Comment by BerkeleyTrue** [comment]
Fix is going up shortly.

Happy Coding!
