### ISSUE TITLE
dead links returned by search bar: Coding Interview Prep

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#18856]
**Describe the bug**
When searching for Coding Interview Prep challenges in the search bar, it returns results linked to URLs that 404. From what I can tell so far, the issue is mainly for interview practice challenges.

**To Reproduce**
1. Go to 'learn.freecodecamp.org' 
2. Type 'min heap' in the search bar
3. Click on the first link in the results list
![image](https://user-images.githubusercontent.com/18563015/46908052-a292d100-ceea-11e8-9eef-31965996932f.png)
4. See 404

**Expected behavior**
- The correct URL is: https://learn.freecodecamp.org/coding-interview-prep/data-structures/implement-heap-sort-with-a-min-heap
- The URL linked to the search result is: https://learn.freecodecamp.org/coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions/implement-heap-sort-with-a-min-heap

From several searches that I've done, it seems like this problem is true for every single item within the Coding Interview Prep section of the curriculum. It seems that when the URLs changed, they were not properly re-indexed for the search.

**Comment by no-stack-dub-sack** [comment]
@QuincyLarson  @Bouncey related to #18082

**Comment by moT01** [comment]
Thanks for reporting this issue @no-stack-dub-sack, I am closing it in favor of duplicate https://github.com/freeCodeCamp/freeCodeCamp/issues/17304

**Comment by RandellDawson** [comment]
@moT01 I see you closed this one.  Can you add this challenge to your list on issue #17304?

**Comment by moT01** [comment]
@RandellDawson the list there just includes one example from each section, and its each of those whole sections that has that issue

**Comment by RandellDawson** [comment]
So I would think we still do not want to lose track of this reported issue (since it is now closed) unless we add it to another open issue somewhere.

**Comment by moT01** [comment]
It's in the list I made, so it hasn't been lost. There's no need to keep issues open that have the same cause. It should get fixed with that.

**Comment by RandellDawson** [comment]
@moT01 Sorry, I must have missed it in the list.  I totally agree to close duplicate issues.  I am doing the same.
