### ISSUE TITLE
Incorrect text in the Use Hex Code for Specific Shades of Gray waypoint.

### ISSUE THREAD

**Issue by jumpy74** [FreeCodeCamp/FreeCodeCamp#1885]
Challenge http://freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-shades-of-gray has an issue.

The waypoint description reads "Make the body element's background color a dark gray by giving it the hex code value of #111111."

The waypoint checklist reads "Give your body element the background-color of a light gray.
Use hex code to make a light gray."

The color produced by #111111 is dark gray. Suggest changing "light" to "dark" in the checklist.

**Comment by AryanJ-NYC** [comment]
Fixed with merge #1821.
