### ISSUE TITLE
search bar funkiness on learn and search platforms

### ISSUE THREAD

**Issue by no-stack-dub-sack** [freeCodeCamp/freeCodeCamp#18861]
**Describe the bug**
I've noticed several oddities with the search feature:
- First, there is no typeahead on the main site: learn.freecodecamp.org
- then, when you type in a search query, you are redirected to a new page with results (many of them are dead links, but that's another issue (#18856). Here, you get your search query in the bar, with an odd trailing quotation mark.
- Now, when you perform another search (in this same new window), you DO have typeahead. BUT when you press enter (which was mandatory to see results when searching from learn.freecodecamp.org), your result set disappears. i.e. ONLY typeahead works here.
- Lastly, if you happen to follow one of the dead links you are shown a 404, with a search bar up top. Since you're back at the learn platform, this cycle starts over: typeahead doesn't work, so you have to hit enter to be redirected to the search platform with your results, if you click on another dead one, etc. etc. You end up with several learn, search, and 404 tabs open pretty quickly! 

**To Reproduce**
1. type in search query on learn platform, notice no typeahead
2. press enter, redirect to search platform - notice trailing quotation in query
3. enter new search in same tab (search platform), notice typeahead works
4. press enter when finished with query, notice query and results disappear
5. search for min heap and follow dead link, repeat!

**Expected behavior**
It seems like typeahead should work on the learn platform to avoid opening a series of tabs. Also, pressing return on a query on the search platform should probably just do nothing, instead of clearing your typeahead results. 

**Screenshots**

No typeahead on the learn platform:
![image](https://user-images.githubusercontent.com/18563015/46908200-8ba1ae00-ceed-11e8-8aa0-b0e506f6cf57.png)

Redirected to search platform, and typeahead works (also, trailing quotation)
![image](https://user-images.githubusercontent.com/18563015/46908207-a116d800-ceed-11e8-8a9e-b580f0c4532c.png)

After pressing return on the search platform, the query disappears, as well as the results:
![image](https://user-images.githubusercontent.com/18563015/46908219-c0ae0080-ceed-11e8-9742-f5a2307ca588.png)

**Comment by chrisdel101** [comment]
@1337M0nst3r Are U still working on this? If not I'll take it over since I'm looking for another here. Let me know

**Comment by coder077** [comment]
@chrisdel101  Are you still working on this too? I can take a look at it. Let me know!

**Comment by chrisdel101** [comment]
@coder077 I'm not. I never heard back after I made that comment so I never started it.

**Comment by 1337M0nst3r** [comment]
Sorry for late reply, feel free to take over.

**Comment by chrisdel101** [comment]
@coder077 I can do it but I won't get to it for a week or two so if you want to do it now let me know. That's cool. Otherwise I'll officially take this.

**Comment by coder077** [comment]
@chrisdel101 Yes, I'll work on this. Thanks!

**Comment by coder077** [comment]
@raisedadead Is it a good idea to split this into different issues before I start working on this?

**Comment by raisedadead** [comment]
Yes, it should however we need to revisit and see what needs to be in the individual issues since a lot has changed lately in the master.

**Comment by coder077** [comment]
@raisedadead Yes, I revisited all the individual issues and they are still there. So, should I split these into multiple new issues and work on them?

**Comment by scissorsneedfoodtoo** [comment]
@coder077, yes, please check if these are still issues on the [beta](https://www.freecodecamp.rocks/) site and create new issues when you can.

**Comment by scissorsneedfoodtoo** [comment]
Closed by https://github.com/freeCodeCamp/freeCodeCamp/pull/36524.
