### ISSUE TITLE
Basic JS: Iterate with do...while. Link to guide leads to 404

### ISSUE THREAD

**Issue by AdrianSkar** [freeCodeCamp/freeCodeCamp#18879]
**Describe your problem and how to reproduce it:**

The [link](https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-do---while-loops) to the guide page leads to a 404 page.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-do---while-loops

**Tell us about your browser and operating system:**
* Browser Name: Vivaldi
* Browser Version: 2.0.1309.37 (Stable channel) (64-bit)
* Operating System: Win 10 64

The correct link seems to be [this one](https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-do...while-loops/) but I can't find the page/file on this repo to fix it and make PR it myself.

**Comment by AdrianSkar** [comment]
@lalov1 That's odd. on my end that link leads to 
https://learn.freecodecamp.org/storing-values-with-the-assignment-operator
not
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/storing-values-with-the-assignment-operator/
resulting in:
![image](https://user-images.githubusercontent.com/12052430/46938783-e1e52d00-d064-11e8-8ad4-d12df35f547b.png)

**Comment by lalov1** [comment]
@AdrianSkar Try doing a hard refresh (Ctrl+F5)

**Comment by AdrianSkar** [comment]
@lalov1 I tried with no luck (even from my phone on a different browser), I think it's the link itself, which URL shows up on your status bar when you hover that link?

**Comment by RandellDawson** [comment]
The Guide repo will be moved to a final location in the next day or two.  Once it is moved, we can make sure the Get a Hint button links to the actual Guide article.
