### ISSUE TITLE
Pressing ctrl+enter enters a newline character in the editor

### ISSUE THREAD

**Issue by leonfeng** [FreeCodeCamp/FreeCodeCamp#1887]
When the `Go to my next challenge` button is enabled, using the keyboard shortcut `ctrl+enter` actually enters a newline character in the code editor. So if your cursor is in the middle of a line of code, the line will be broken into two and can cause the tests to fail again. Although the page is refreshed, users will find themselves back at the same challenge they just completed.

**Comment by benmcmahon100** [comment]
What browser + Os are you using? It's going to be hard to fixed this as i cant replicate the issue myself

**Comment by leonfeng** [comment]
Sorry, Chrome 44.0.2403.155 (64-bit) on OS X 10.10.5.

**Comment by BerkeleyTrue** [comment]
fixed
