### ISSUE TITLE
Passing Values to Functions with Arguments doesn't pass without semi column 

### ISSUE THREAD

**Issue by arnas** [freeCodeCamp/freeCodeCamp#18885]
**Describe your problem and how to reproduce it:**
The test "Call functionWithArgs with two numbers after you define it." doesn't passes if the function call doesn't end with semi column.   
As in js semi columns are not required it should pass even if user doesn't add semi column

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/passing-values-to-functions-with-arguments

**Tell us about your browser and operating system:**
* Browser Name:  Chrome
* Browser Version: latest
* Operating System:  windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![image](https://user-images.githubusercontent.com/13507001/46909629-2a55fb00-cf3e-11e8-9a8d-ef2f40ca59f9.png)

![image](https://user-images.githubusercontent.com/13507001/46909626-2033fc80-cf3e-11e8-8319-3c00cafae619.png)

**Comment by RandellDawson** [comment]
There has been an on and off discussion for a while about whether to enforce the use of end-of-line statement semi-colons.   W

FYI - This debate about semi-colons is not new to FCC.  This is a debate that has been going on for a long time.  See the following link how not using semi-colons could cause unexpected errors.

https://eslint.org/docs/rules/semi

This debate is similar to whether or not you should require { and } if there is only one statement in the code block.  For example:
```
if ( x < 5) {
  return x + y;
}
else {
  return x * y;
}
```
is the same as:
```
if ( x < 5) 
  return x + y;
else
  return x * y;
```
but FCC's current linter settings expect the { and } to be used.  Both are valid JavaScript, but it is thought using { and } makes it clear especially when you have a line after like below:
```
if ( x < 5) {
  x += 10;
}
x += y;
```
OR
```
if ( x < 5)
  x += 10;
x += y;
```
Both of the above accomplish the same thing, but reading the code could get confusing especially if indentation of the second line was accidentally written as:
```
if ( x < 5)
  x += 10;
  x += y;
```
Someone coming from Python might thing the second line is far of the if statement block when it is not.

As far as the semi-colon debate goes, I don't care which way it is done, just as long as it is consistent throughout the curriculum.  Currently, there are challenges which do not require the semi-colon and some which do (which you have observed).

**Comment by arnas** [comment]
Well this form is more for user to type the code. So it would make sense to treat the code same as regular javascripts treats it's. If the function returns correct result the code should pass the test.

**Comment by RandellDawson** [comment]
> Well this form is more for user to type the code. So it would make sense to treat the code same as regular javascripts treats it's. If the function returns correct result the code should pass the test.

Are you referring to semi-colons or the curly brackets now?

**Comment by arnas** [comment]
I have eleborate my answer. And I am taking about semicolons.

**Comment by RandellDawson** [comment]
I have asked those in charge to make a final decision about this issue.  Once I get some feedback, I will let you know the verdict.  This decision will affect many challenges.

**Comment by amusedberry** [comment]
Hi, @RandellDawson. By any chance have they took a decision about this issue? I can confirm that this is still an issue after 3 months.
When you get used to code using the standardJS style([standard/standard](https://github.com/standard/standard)), for example, it's not immediately obvious that the _"Call function"_ test is not passing due to a missing semicolon.
I don't mind whether you decide to keep the semicolons or let them be optional, as it comes to coding style. But a failing test should indicate the real problem, and I feel that failing a test named "Call function after you define it" when you actually called your function properly, can be confusing to new developers.

Cheers,
Mike

**Comment by RandellDawson** [comment]
@amusedberry Yes, would you be interested in making the semi-colon optional for this challenge to pass the tests?

**Comment by amusedberry** [comment]
@RandellDawson sure! Just let me get familiar with the code base and as soon as I have a better grasp, I will send the pr's for this challenge and the next one (that is under the same situation).

**Comment by moT01** [comment]
Any progress on this @amusedberry? I agree that the semi-colons should be optional - If a camper is failing a challenge with valid javascript, that seems like a problem that might confuse them.
