### ISSUE TITLE
Going to the next unsolved challenge

### ISSUE THREAD

**Issue by arnas** [freeCodeCamp/freeCodeCamp#18883]
Hello, 

I am not sure if this is a bug, but i can't find way to go the next unsolved challenge. It only gives me option to go to the next challenge.

http://prntscr.com/l5qoyp

I think it references this issue https://github.com/freeCodeCamp/freeCodeCamp/issues/5612

**Comment by JamyangLotus** [comment]
Go to curriculum and go to the next unsolved challenge.

**Comment by scissorsneedfoodtoo** [comment]
Closing as stale.
