### ISSUE TITLE
Bonfire: Symmetric Difference Test Bug

### ISSUE THREAD

**Issue by AryanJ-NYC** [FreeCodeCamp/FreeCodeCamp#1888]
Challenge http://www.freecodecamp.com/challenges/bonfire-symmetric-difference has an issue:

![image](https://cloud.githubusercontent.com/assets/8263430/9312784/0087899e-44ed-11e5-8808-06fd907f60b5.png)
Why do we include 5 in the return array if it is not unique?

Also, why do we include 1 and 5 in the array if it's in all three arrays? Shouldn't we only include unique numbers?

This looks like a test bug.

**Comment by abustamam** [comment]
Check out this video for explanation on symm diff: https://www.youtube.com/watch?v=PxffSUQRkG4 

It's not about uniqueness, it's about (non) intersecting nodes.

**Comment by AryanJ-NYC** [comment]
Ah. So in the second test listed, should 1 be in the return array? The third array does not have a 1 so it seems that is a mistake.

**Comment by AryanJ-NYC** [comment]
Mistake in my understanding of symmetric difference. Closing.

**Comment by abustamam** [comment]
Do you get it? When we do sym_diff(a,b,c) where a,b,c are the input arrays, we are essentially just taking the result of sym_diff(a,b) and doing sym_diff(A,c)...

So anything that was in common between a and b, but is also in c (i.e. present in all three sets) will be in that resulting array.
