### ISSUE TITLE
Will not run code just for comments

### ISSUE THREAD

**Issue by crazy7381** [FreeCodeCamp/FreeCodeCamp#1889]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. I type in both type of comment functions // and /**/ click run code and nothing happens it will not load the next step in the map.

**Comment by benmcmahon100** [comment]
I cannot replicate this right now i think it's fixed! Please open a new pull request if this persists. Thanks for reporting!

**Comment by crazy7381** [comment]
It happens in IE 11 google chrome fixed it

**Comment by benmcmahon100** [comment]
IE is completely broken with FCC we're working to fix it!
