### ISSUE TITLE
Comparison with the Inequality Operator and Comparison with the Strict Inequality Operator inconsistent formatting

### ISSUE THREAD

**Issue by arnas** [freeCodeCamp/freeCodeCamp#18893]
**Describe your problem and how to reproduce it:**
These task has inconsistent code where task is pretty much the same. I would believe that freecode camp should use same code style everywhere. If one task has comments, second should have them too.
Basic JavaScript: Comparison with the Inequality Operator
Basic JavaScript: Comparison with the Strict Inequality Operator

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-inequality-operator
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-strict-inequality-operator

![image](https://user-images.githubusercontent.com/13507001/46909850-f086f380-cf41-11e8-8315-2217583bb4b8.png)
![image](https://user-images.githubusercontent.com/13507001/46909852-f5e43e00-cf41-11e8-9cd0-b4a1539757cb.png)

**Comment by arnas** [comment]
Sorry If I wan't clear. But yes I am referring to the comments

**Comment by Nirajn2311** [comment]
@arnas I’ll work on this. Also I think that the first one is better.
