### ISSUE TITLE
Basic JavaScript: Introducing Else If Statements redundant else statement

### ISSUE THREAD

**Issue by arnas** [freeCodeCamp/freeCodeCamp#18896]
**Describe your problem and how to reproduce it:**
Basic JavaScript: Introducing Else If Statements tests requires to write redundant else statement, where you could just return value.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/introducing-else-if-statements

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/13507001/46909949-b4549280-cf43-11e8-8ae5-ab43d9a1b3ef.png)

**Comment by s-Hale** [comment]
You could, but at the end of the day it's for beginners to get comfortable with the concepts. You learn the shorthands later.

**Comment by arnas** [comment]
I agree, but nonetheless it shouldn't force to write else. It could be simply optional.

**Comment by RandellDawson** [comment]
There are 2 ways to deal with this.  

1) Leave the solution  to require the else, but change the instructions to reflect an else statement is expected.

2) Modify the tests to make the else { return...} optional.  

@arnas Would you like to attempt to work on one of these solutions by creating a fix with a commit and requesting a PR?  Let me know and I can assign it to you.  If you would like to work on it together, I can give you some guidance on how to create the correct test.  Just let me know.

**Comment by arnas** [comment]
Okay, I will look into it

**Comment by RandellDawson** [comment]
@arnas Is it ok if I assign this to you, so someone else does not work on the same solution?

**Comment by arnas** [comment]
Yes

**Comment by arnas** [comment]
@RandellDawson it seems can't get freecodecamp solution to work localy. It currently just throws an error if try to build client side project as there is too many files. 
error Plugin @freecodecamp/gatsby-source-filesystem returned an error
"

  Error: EMFILE: too many open files, open 'C:\Users\Arnas\Documents\freeCodeCamp\client\src\pages\guide\spanish\certifications\coding-interview-prep\project-euler\problem-451-modular-inverses\index.  md'

error Cannot read property 'filter' of undefined


  TypeError: Cannot read property 'filter' of undefined
"
I have checked gatsby-source-filesystem and it seems there is some user that encountered this problem in the pass, but coun't find any obvious solution. Also it might be that I am running on windows 10 instead of linux or mac.

**Comment by Nirajn2311** [comment]
@arnas there have been some problems in setting up FCC locally. @raisedadead has mentioned in the Contributors Gitter that local setup will be fixed in a weeks time.

**Comment by raisedadead** [comment]
>  will be fixed in a weeks time.

Hopefully, you should know that I can't work under stress. 😛

**Comment by RandellDawson** [comment]
@arnas After reviewing this issue again and looking at what the intent of the challenge is, I think it would be best to have the user write the extra `else if` or `else` as the lesson is about `else if`.  I do think the challenge instructions could be modified slightly to something like:

> Convert the logic to use one `else if`statement **AND** one `else` statement.

Doing the above makes it clearer what the expectation of the challenge is and does not involve modifying existing tests.

I believe it might be better to create a completely new challenge to show how an else statement could be optional in certain scenarios. If want to do that, then I suggest creating a separate issue so it can be discussed and agreed upon by other collaborators, before creating a PR.

I am going to close this issue for now, but if you would like to discuss further, it can be reopened later.  Just let me know.
