### ISSUE TITLE
Waypoint: Perform Arithmetic Operations on Decimals with JavaScript

### ISSUE THREAD

**Issue by saadanerdetbare** [FreeCodeCamp/FreeCodeCamp#1890]
Challenge http://www.freecodecamp.com/challenges/waypoint-perform-arithmetic-operations-on-decimals-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The test seed has the following 2 challenges:
```
var quotient = 4.4 / 0.5; // equals 2.2
var product = 2.0 * 2.5; // equals 5.0
```
but the test only checks hte last of the 2 operations

**Comment by benschenker** [comment]
Looks like this has been resolved.
