### ISSUE TITLE
Test isn't fulfilled with the required attribute.

### ISSUE THREAD

**Issue by eabedrapo** [FreeCodeCamp/FreeCodeCamp#1891]
The second test in Waypoint "Create a form element" (HTML track) reads "Your form element should have an action attribute" but after adding an "action" attribute to the form the test isn't marked as green (see screenshot below).

Although the problem isn't a big deal to pass the waypoint as adding "/submit-cat-photo" to the attribute (requirement for the 4th test) makes the 2nd test green, having that test doesn't make sense if it doesn't work until the 4th test is fulfilled.

Waypoint's URL:
http://www.freecodecamp.com/challenges/waypoint-create-a-form-element

Steps:
1. Open the Waypoint's URL.
2. Locate the <input> tag corresponding to the text field.
3. Nest the input tag into a `<form>` element.
4. Add "action" attribute to the form element leaving it's value empty.
5. Observe the second test at the left.

![image](https://cloud.githubusercontent.com/assets/1670763/9312600/fc839db8-44f3-11e5-906c-612a5bce661b.png)

**Comment by benschenker** [comment]
Thanks @eabedrapo,

I've confirmed this.  Solution is either remove the test or fix it to assert the presence of the attribute only and not the value

**Comment by bugron** [comment]
@eabedrapo thanks for posting this issue!
@benschenker I think I can handle this but which one is a better solution for you? Remove the test or fix it (search for "<form action", for example)?

**Comment by benschenker** [comment]
Either is fine from my perspective, though removing the test may be easier...
