### ISSUE TITLE
Basic JavaScript: Use the Conditional (Ternary) Operator teaches questionable practices?

### ISSUE THREAD

**Issue by arnas** [freeCodeCamp/freeCodeCamp#18925]
**Describe your problem and how to reproduce it:**
The exercise is teaches questionable practices!?
There were a discussion previously https://github.com/freeCodeCamp/freeCodeCamp/issues/14821 .
But i think it should be reviewed again as change could be fairly simple.
Instead of asking if numbers are equal, ask to return "Bigger" or "Smaller" or something. 
As currently the better solution would be to return a === b;

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/use-the-conditional-ternary-operator

**Comment by petern-sc** [comment]
👍I agree with this, it definitely is not good practice. 

As mentioned in that other issue, I think having it return the bigger number would be a good example.

**Comment by ezioda004** [comment]
I somewhat agree but then again it's introduction to ternary operator which can be a bit tricky to understand at first.
If it needs to be updated then I think returning "Equal" or "Not equal" seems like a good alternative.

**Comment by ozgunbal** [comment]
I came here to suggest what @ezioda004 already suggested. In my opinion, better use case of ternary would be more informative.

**Comment by chrisdel101** [comment]
I'll make these changes.
