### ISSUE TITLE
Wrong redirection when waypoint is completed

### ISSUE THREAD

**Issue by Megauap** [FreeCodeCamp/FreeCodeCamp#1892]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue. When you complete it and click the button to go to the next challenge, it redirects you to: http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-push 

Instead it should redirect you to the correct waypoint which is: http://www.freecodecamp.com/challenges/waypoint-size-your-images

**Comment by ahstro** [comment]
Can't reproduce, is this still a thing?

**Comment by Megauap** [comment]
No, it's fixed now.
Thanks anyways!
