### ISSUE TITLE
Doesn't recognize one of the requirements

### ISSUE THREAD

**Issue by amirhmk** [FreeCodeCamp/FreeCodeCamp#1894]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The waypoint doesn't recognize that I nested my elements with a div

http://postimg.org/image/pdvihmkxr/

**Comment by benmcmahon100** [comment]
You have a typo in the word class on the first well. Please check these kinds of issues in the help chat before posting here. Thanks for reporting!
