### ISSUE TITLE
Classes to add are not defined

### ISSUE THREAD

**Issue by roelver** [FreeCodeCamp/FreeCodeCamp#1896]
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The second assignment states: "Only use jQuery to add these classes to the element." It is not explained what classes should be added to which element. Tried class btn-default but that invalidated both assignments.

**Comment by benmcmahon100** [comment]
It gives you the code in the description. Please check these kinds of issues in the chat. Thanks for reporting!
