### ISSUE TITLE
Missing 'Waypoint' for 'Automated Testing and Debugging' exercises

### ISSUE THREAD

**Issue by AryanJ-NYC** [FreeCodeCamp/FreeCodeCamp#1897]
Challenge http://www.freecodecamp.com/challenges/-use-the-javascript-console has an issue
AND
Challenge http://www.freecodecamp.com/challenges/-using-typeof has an issue:

![image](https://cloud.githubusercontent.com/assets/8263430/9313929/d4b55916-44f3-11e5-9f2e-6a41bb88922a.png)
![image](https://cloud.githubusercontent.com/assets/8263430/9313941/e3dac282-44f3-11e5-9dd2-d9036b786ed1.png)

It should say Waypoint, I think.

**Comment by bugron** [comment]
Just followed that links, everything is OK.
