### ISSUE TITLE
Control Bug

### ISSUE THREAD

**Issue by harry9656** [FreeCodeCamp/FreeCodeCamp#1898]
Challenge http://freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![image](https://cloud.githubusercontent.com/assets/7223909/9313930/2008f742-4526-11e5-8ad7-82b8649935cc.png).

It has to control if the user has really removed the *btn-default* class. You can in the screenshot that it accepts the code even though i have not inserted *btn-default* in the *removeClass()* function

**Comment by benschenker** [comment]
Thanks @harry9656,

Confirmed, challenge is marked completed with incorrect answer `$('button').removeClass();`
