### ISSUE TITLE
Issue with adding Font Awesome Icons

### ISSUE THREAD

**Issue by francisngo** [FreeCodeCamp/FreeCodeCamp#1899]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-font-awesome-icons-to-our-buttons has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey @francisngo,

Take a look at our new [Bug Posting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug).

I'm going to close this issue for now but reopen if the above steps do not resolve the problem
