### ISSUE TITLE
something seems wrong

### ISSUE THREAD

**Issue by Hurlarious** [FreeCodeCamp/FreeCodeCamp#1900]
![screen shot 2015-08-17 at 12 14 26 pm](https://cloud.githubusercontent.com/assets/13294409/9313817/f3162e54-44d9-11e5-9565-6ff6536a411d.png)
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

--------

- the ourArray example is incorrect
- the last paragraph of the instructions should say 'start' and not 'end'  shift/unshift vs pop/push

my code should pass...?

**Comment by benmcmahon100** [comment]
The ouArray example unshifts and array into an array. The aim of a challenge is to unshift the string Paul into myArray as the description says. Hope this calrifies but please check these kinds of issues in help or the main chat before making them into github issues. Thanks for reporting this!

**Comment by AryanJ-NYC** [comment]
You're shifting an array that contains the string "Paul". You should be shifting JUST the string "Paul"
