### ISSUE TITLE
npm run bootstrap fails because of the path issues.

### ISSUE THREAD

**Issue by arnas** [freeCodeCamp/freeCodeCamp#19019]
**Describe your problem and how to reproduce it:**
superBlockInfoFromPath and getBlockNameFromPath functions in the getChallenges file cannot resolve correct path in windows. As windows uses \ instead of /.

Changing split to filePath.split('\\') fixes problem, but the solution should have correcet split function depending on the running environment

**Comment by raisedadead** [comment]
Hi, @eragon512 I higly recommend working on approved issues such "Help Wanted", others issues may not be ready for fix, or could be duplicates. 

Thanks a lot for taking the time to prepare the PR. We appreciate the effort

**Comment by eragon512** [comment]
okay, thanks!
