### ISSUE TITLE
Next Challenge Error HTML img to Arrays

### ISSUE THREAD

**Issue by Eiseldora** [FreeCodeCamp/FreeCodeCamp#1901]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
When I complete the challenge it takes me to this challenge: http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-shift

**Comment by ahstro** [comment]
This is a duplicate of #1892

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
