### ISSUE TITLE
Wrong Map Visualization

### ISSUE THREAD

**Issue by Em-Ant** [FreeCodeCamp/FreeCodeCamp#1902]
Challenge http://www.freecodecamp.com/challenges/zipline-build-a-simon-game has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I've not completed this one, but I have completed the tic-tac-toe. The Simon challenge is marked as complete, while the tic-tac-toe is not. Links and solutions on the portfolio page are correctly reported.

**Comment by bugron** [comment]
Dear camper, your issue is related to:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1800

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
