### ISSUE TITLE
Bug in test

### ISSUE THREAD

**Issue by hansinla** [FreeCodeCamp/FreeCodeCamp#1903]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-pop has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![screen shot 2015-08-17 at 12 39 57](https://cloud.githubusercontent.com/assets/373708/9314342/2ca0c4e2-44dd-11e5-9764-23493d0f5694.png)

**Comment by benmcmahon100** [comment]
That is not the correct ode you are meant to make the change to line 8 I'm fixing the comments now

**Comment by hansinla** [comment]
Thanks, yes I figured it out by looking at the errors, but a better description of the problem will definitely help. Thanks. 

Hans van Riet

**Comment by benmcmahon100** [comment]
Yeah i've moved the comments to make it more clear
