### ISSUE TITLE
ES6: Use Destructuring Assignment with the Rest Operator to Reassign Array Elements suggest to use questionable practices

### ISSUE THREAD

**Issue by arnas** [freeCodeCamp/freeCodeCamp#19044]
**Describe your problem and how to reproduce it:**
The correct answer  `const [a,b, ...arr] = list;` creates additional two variables (a, b) that are not used. Which usually is not good practice. I think it would be better to change task so all variables would be used.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-operator-to-reassign-array-elements

**Comment by ezioda004** [comment]
You do not need to add `[a, b]` to destructure.
`const [, , ...arr] = list; ` works.
This was mentioned in the [previous challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-arrays/) that you can omit indices with commas.

**Comment by arnas** [comment]
Ah, it's my mistake then. 

Closing
