### ISSUE TITLE
Waypoint: Generate Random Whole Numbers with JavaScript

### ISSUE THREAD

**Issue by TheHighPriestess** [FreeCodeCamp/FreeCodeCamp#1904]
The first paragraph needs fixing.

![untitled-1](https://cloud.githubusercontent.com/assets/9852102/9314477/db357882-4531-11e5-8caa-dddd407d3a07.jpg)

**Comment by TheHighPriestess** [comment]
Something else...

It isn't until the NEXT Waypoint (31) that the discussion about how to generate a random number between two numbers is introduced.

**Comment by benmcmahon100** [comment]
Yeah this is an ordering issue I'll take a look at this now!

**Comment by benmcmahon100** [comment]
It should be fixed now!
