### ISSUE TITLE
Confusing text for the 3rd test requirement.

### ISSUE THREAD

**Issue by eabedrapo** [FreeCodeCamp/FreeCodeCamp#1905]
The 3rd test in http://www.freecodecamp.com/challenges/waypoint-use-an-id-attribute-to-style-an-element reads "Make sure your form element has both an id attribute."

This text suggest there is something else to fulfill but the test actually passes by only having any attribute with the value of "cat-photo-form" (regardless if the attribute is id or anything else) which doesn't help students to catch errors when playing around the code.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/1670763/9314441/5c4a524a-44ff-11e5-8e7f-f6a75532ec71.png)

**Comment by jbmartinez** [comment]
That's already fixed. Thanks for reporting

**Comment by eabedrapo** [comment]
Cool! Closing it then. Thanks!
