### ISSUE TITLE
Simon game video

### ISSUE THREAD

**Issue by mutantspore** [FreeCodeCamp/FreeCodeCamp#1906]
Challenge http://www.freecodecamp.com/challenges/zipline-build-a-simon-game has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Shows the Tic-Tac-Toe video instead of the Simon Video

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1864

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
