### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by rammsteincrazy** [FreeCodeCamp/FreeCodeCamp#1907]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-push has an issue. 

Nothing happens when I push the submit button - the code doesn't run and I don't move on to the next challenge.

**Comment by benmcmahon100** [comment]
Hey @rammsteincrazy sorry about this issue but the button is slow ATM. What browser and OS are you using out of interest?

**Comment by rammsteincrazy** [comment]
hi @benmcmahon100 it seems to work alright when I'm home using Safari on my MacBook (it just updated the OS recently; I can't remember what it's called now but it's the latest one), but when I'm using my work computer, which uses Internet Explorer on Windows 7, I have this error on almost every challenge (I'm currently stuck on manipulate arrays with shift - I know my code is right but nothing at all happens when I push submit)

**Comment by benmcmahon100** [comment]
Hey we have known issues with both safari and IE. The only browsers that work at the moment are chrome and firefox. Using one of these should prevent any issues. Sorry for the inconvenience.

**Comment by benmcmahon100** [comment]
Closing as stale
