### ISSUE TITLE
It skipped to javascript out of no where

### ISSUE THREAD

**Issue by sekouperry** [FreeCodeCamp/FreeCodeCamp#1908]
I was working on the html/css course and all of the sudden it jumped to javascript.

Challenge http://freecodecamp.com/challenges/waypoint-manipulate-arrays-with-push has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Thanks @sekouperry,

This seems related to #2648 so keep an eye there for updates.
