### ISSUE TITLE
Application Error while accessing bonfires.

### ISSUE THREAD

**Issue by abdulhannanali** [FreeCodeCamp/freecodecamp#191]
I receive this message and have heard that some others also receive such message. 
![image](https://cloud.githubusercontent.com/assets/8170969/6612055/c1c5faec-c896-11e4-8749-779eb1cab249.png)

**Comment by BerkeleyTrue** [comment]
This happens when the app crashes. This has remedied. Thanks @abdulhannanali for reporting it!
