### ISSUE TITLE
myArray.pop()

### ISSUE THREAD

**Issue by tony72377** [FreeCodeCamp/FreeCodeCamp#1911]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-pop has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
 
Just tried to do the .pop lesson in javascript and it seems to be a bit broken. I'm not sure if it's actually broken or te instructions are lacking but I ran  myArray.pop()  in order to remove the last item of myArray[] and it only comes back as half correct. "myArray=[john, 23] & removed" is what is being returned

**Comment by airyz** [comment]
This is not a bug.  After reading teh documentation of pop I found that is actually removing the LAST part of an array, so we do not have to use 

myArray[2].pop(); 

but actually a simple 

myArray.pop();

**Comment by benschenker** [comment]
Hey @tony72377 thanks for posting!

As @airyz said, `myArray.pop()` is the correct answer and is working for me.  I'm going to close this issue as it seems stale, but please reopen it if you still have this issue.

**Comment by mehtab01** [comment]
Actually I try last line with myArray.pop() but not work out.

**Comment by benschenker** [comment]
Hey @mehtab01, lets chat in gitter. maybe I can figure out what wrong

**Comment by dht0my** [comment]
Hello 
I have the same issue. Please post the solution. I put myArray.pop(); and i get this: "myArray = [John,23] & removed = undefined" 

There is another X - assert((function(d){if(d[0] == 'cat' && d[1] == 2 && d[2] == undefined){return true;}else{return false;}})(removed), 'removed should only have the first two values left(["cat"], 2).');

you have to place the last element of the myArray into the removed var, how do you do that?
