### ISSUE TITLE
instruction change request

### ISSUE THREAD

**Issue by jack-acid** [FreeCodeCamp/FreeCodeCamp#1913]
Challenge http://freecodecamp.com/challenges/waypoint-override-class-declarations-by-styling-id-attributes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This is not a bug, but a request for clarification. The text "We just proved that browsers read CSS from top to bottom" seems too simplistic, even for this early stage. A little experimenting shows that a class property will override a body property even if the body property is listed last in the style section.

Also, the term "proved" is used in several waypoints. Please consider changing it "showed" or "demonstrated".

**Comment by jbmartinez** [comment]
Browsers read *and* apply CSS from top to bottom, but rules are subject to *specificity* which is a somewhat advanced topic that may be confusing for beginners
