### ISSUE TITLE
missing ) after argument list

### ISSUE THREAD

**Issue by ibiwan** [FreeCodeCamp/FreeCodeCamp#1914]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

First checklist item on this page just says "missing ) after argument list" no matter what's in the code window.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1912

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
