### ISSUE TITLE
Proposing an NVD3 article in the D3 section

### ISSUE THREAD

**Issue by StraubJones** [freeCodeCamp/freeCodeCamp#19142]
**Describe your problem and how to reproduce it:**
This is a proposal to build consensus about whether to and where to add a short article about NVD3, a library that builds on top of D3.js, which I have often found useful for beginners not sure where to jump in with D3. As they find edge cases they don't like or can't use in NVD3, they fiddle and dig under the hood, and thus slowly learn the D3 underneath.
NVD3's site is here: http://nvd3.org/
It uses D3 as it's base but just adds on top, so the D3 api is still always there as well. It covers basic use cases early developers might want, like bar charts and line charts, but in ways that come very full-featured and easy to configure outside of the box. In this way it's also a good introduction to using 3rd-party libraries generally, and finding that the solution for what you're trying to get, if it's a common solution, often has a library out there to help.

Thoughts?

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/d3

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 
* Operating System: OSX

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by lynxlynxlynx** [comment]
Can't see why not, the visualisation section is quite hard and off-putting as a consequence of how d3 is designed, so anything that makes people despise it less is good in my book.

**Comment by moT01** [comment]
So do we want to create a group of challenges around this? I'm thinking that with the plan of turning the curriculum into the project based curriculum - creating a new group of challenges is maybe not the way to go. I am not familiar with NVD3 - it sounds helpful. Perhaps a guide article?

**Comment by lynxlynxlynx** [comment]
One project would do, though in that format it begs the question why teach D3 itself at all then.

**Comment by StraubJones** [comment]
As an infrequent contributor, I missed the memo on the plan to shift to a project-based curriculum. Is it anything more complicated than a focus more on making small problems / projects for students and less on the article-based reference / reading material aspect?

I could set it up either way folks wanted, either as a short article or a small challenge (build this basic chart using NVD3!), though I'm super over-worked right now, so it wouldn't be until the fall probably that I could put it together for y'all.

**Comment by moT01** [comment]
Pretty much yes @StraubJones - just a bunch of small projects instead of challenges - https://www.freecodecamp.org/forum/t/help-us-build-version-7-0-of-the-freecodecamp-curriculum/263546

**Comment by moT01** [comment]
Closing as stale. The best place to discuss any further ideas on this would be the [project based curriculum repo](https://github.com/freeCodeCamp/CurriculumExpansion). Thanks and happy coding 🎉
