### ISSUE TITLE
Incorrect css style for popup alerts

### ISSUE THREAD

**Issue by shadowfool** [FreeCodeCamp/FreeCodeCamp#1915]
![wrong css](https://cloud.githubusercontent.com/assets/709295/9315047/c399b922-44fa-11e5-87ae-5104a529a175.jpg)

Challenge http://freecodecamp.com/challenges/waypoint-use-conditional-logic-with-ifelse-statements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Seems like there's an open style tag or something. Popup boxes for completed tasks/ bugs appear with the incorrect style (based on the style that appears on every other page.)

Also the footer is not rendering correctly.

**Comment by benschenker** [comment]
Hey @shadowfool, thanks for posting.

I can't replicate this on page: http://freecodecamp.com/challenges/waypoint-use-conditional-logic-with-ifelse-statements that was in your screenshot.

Closing this for now, but reopen if you still see this issue
