### ISSUE TITLE
Error in the test for waypoint-target-the-parent-of-an-elem...

### ISSUE THREAD

**Issue by Em-Ant** [FreeCodeCamp/FreeCodeCamp#1917]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The first test is an error, my code works and seems to be correct. I

![screenshot - 17082015 - 22 12 26](https://cloud.githubusercontent.com/assets/12955734/9315083/47814f0c-452d-11e5-8fd4-5c7082d61be1.jpg)

**Comment by alispencer** [comment]
I am having the same error.

**Comment by benmcmahon100** [comment]
This has been fixed
