### ISSUE TITLE
Waypoint: Label Bootstrap Wells - answer correct but still marked incorrect / incomplete

### ISSUE THREAD

**Issue by codeNameJKB** [FreeCodeCamp/FreeCodeCamp#1919]
Challenge http://freecodecamp.com/challenges/waypoint-label-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
Hi, 

The Task: Add an h4 element to each of your <div class="col-xs-6"> elements.
is correct but it is marked as incomplete / incorrect. I am unable to progress forward. 
I have attached a screenshot for visual clarification.

Thanks, 

J

![screen shot 2015-08-17 at 4 20 07 pm](https://cloud.githubusercontent.com/assets/13787549/9315346/ca8b9e92-44fc-11e5-9c89-7d02653fa92d.png)

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1548
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1544

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
