### ISSUE TITLE
Redaction.

### ISSUE THREAD

**Issue by misuta** [FreeCodeCamp/FreeCodeCamp#1920]
![redaction](https://cloud.githubusercontent.com/assets/4020178/9315202/147f7f4c-452e-11e5-9e5e-eb154a3032f7.JPG)
Challenge http://freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript has an issue. 

In the instructions of the of the Challenge you can read "It's great that we can create random decimal numbers, but it's even more useful if we lot more useful to generate a random whole number."

you can either leave "but it's even more useful to generate.." or "but it's even more useful if we generate..." 

Best regards.

misuta

**Comment by benschenker** [comment]
This has been fixed, thanks!
