### ISSUE TITLE
toLowerCase is not a valid function

### ISSUE THREAD

**Issue by crazy7381** [FreeCodeCamp/FreeCodeCamp#1921]
Challenge http://freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![image](https://cloud.githubusercontent.com/assets/10858943/9315385/2f0aae8c-44ec-11e5-8807-acf1c65f1ec4.png)
my code:

var ourArray = ["Stimpson", "J", ["cat"]];
ourArray.shift();
ourArray.unshift(["happy", "joy"]);
// ourArray now equals [["happy", "joy"], "Stimpson", "J"]

var myArray = ["John", 23, ["dog", 3]];
myArray.shift();

// Add "Paul" to the start of myArray
// Only change code below this line.

myArray.unshift(["Paul"]);
// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
// You'll learn about functions soon.
(function(y, z){return('myArray = ' + JSON.stringify(y));})(myArray);

Error message

assert((function(d){if(d[0].toLowerCase() == 'paul' && d[1] == 23 && d[2][0] != undefined && d[2][0] == 'dog' && d[2][1] != undefined && d[2][1] == 3){return(true);}else{return(false);}})(myArray), 'myArray should now have ["Paul", 23, ["dog", 3]])');d[0].toLowerCase is not a function

**Comment by ahstro** [comment]
The reason that `d[0].toLowerCase()` is not a function is because you've made the first argument of `myArray` another array instead of a string. Try removing the `[]`-characters from line 12 and see what happens. And don't forget to close this issue.

**Comment by crazy7381** [comment]
worked thank you,
