### ISSUE TITLE
Issue on Waypoint: Target the Parent of an Element Using jQuery

### ISSUE THREAD

**Issue by Jonatan-B** [FreeCodeCamp/FreeCodeCamp#1922]
Challenge http://freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
-----

I'm not sure why but even though I'm completing the challenge is not marking it as completed.

Here is my code:

![screenshot033](https://cloud.githubusercontent.com/assets/11668742/9315474/09066b32-44f5-11e5-9964-42ea89fda529.png)

![screenshot031](https://cloud.githubusercontent.com/assets/11668742/9315422/bc785bd6-44f4-11e5-9a5e-49cb128dac19.png)

As you can see on the screenshot the result is correct too, but 

![screenshot032](https://cloud.githubusercontent.com/assets/11668742/9315438/d2df279c-44f4-11e5-9761-1e2148a98049.png)

**Comment by benmcmahon100** [comment]
moving this here https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1943
