### ISSUE TITLE
Bug with waypoint remove-classes-from-an-element-with-jquery

### ISSUE THREAD

**Issue by shubham1996** [FreeCodeCamp/FreeCodeCamp#1923]
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue.
The Challenge is marked as complete even if the required tasks are not completed successfully.
Refer to the screenshot: 
![screenshot from 2015-08-18 01 54 52](https://cloud.githubusercontent.com/assets/4639594/9315320/40d34704-454c-11e5-82f3-85e007659cda.png)
Just adding the removeClass(without any parameters) on the jQuery selector marks the task as complete.
Thank you. :smile:

**Comment by thatsmiddi** [comment]
I have the same issue but for me i can go to the next challenge although not all tests passed.

![ScreenShot of Error](http://i.imgur.com/xGGuTja.png?1)

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1898
Fixed.
