### ISSUE TITLE
[Guides] Duplicate pages/files in the repo?

### ISSUE THREAD

**Issue by AdrianSkar** [freeCodeCamp/freeCodeCamp#19277]
**Describe your problem and how to reproduce it:**
I wanted to improve [this guide page](https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-javascript/generate-random-whole-numbers-within-a-range/) and searched for it within the repo when I found two identical files corresponding to the currently published one ([one inside the client/src/pages/guide/ dir](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/pages/guide/english/certifications/javascript-algorithms-and-data-structures/basic-javascript/generate-random-whole-numbers-within-a-range/index.md) and [other inside client/src/guide/](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/guide/english/certifications/javascript-algorithms-and-data-structures/basic-javascript/generate-random-whole-numbers-within-a-range/index.md))

- Which one should I edit? 
- Is there a need/purpose behind this or am I doing something wrong?

**Add a Link to the page with the problem:**
Find results at [this repo](https://github.com/freeCodeCamp/freeCodeCamp/find/master) for this query: generate-random-whole-numbers-within-a-range in order to edit [this guide page](https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-javascript/generate-random-whole-numbers-within-a-range/)

**Tell us about your browser and operating system:**
* Browser Name: Vivaldi
* Operating System: Xubuntu 16.10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![image](https://user-images.githubusercontent.com/12052430/46951572-ae1bfe80-d088-11e8-9b4a-032ab71b1927.png)

**Comment by ezioda004** [comment]
Hi @AdrianSkar,
I believe this issue is known and will be worked on by @QuincyLarson and @raisedadead.

**Comment by Nirajn2311** [comment]
@AdrianSkar could you close this as it has been solved. All guide files are now found in ‘/guide’

**Comment by AdrianSkar** [comment]
Sure @Nirajn2311. Thank you all!
