### ISSUE TITLE
Typo in the instructions of jQuery exercise

### ISSUE THREAD

**Issue by diegomm77** [FreeCodeCamp/FreeCodeCamp#1927]
http://freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery

In the instructions is says:
$(".target:nth-child(3)").addClass("animated bounce");

and it should be:
$(".target :nth-child(3)").addClass("animated bounce");

i.e., with a space before the semicolon. Otherwise it doesn't work.

**Comment by iisupreme** [comment]
Thanks @diegomm77 would not have completed this challenge without this update.

**Comment by ahstro** [comment]
I am not having this problem at all, and the [official jQuery example](http://api.jquery.com/nth-child-selector/) isn't using a space before the colon. Are you sure it's not just a broken test case or something?

**Comment by diegomm77** [comment]
I guess it may be a wrong test case.

**Comment by benschenker** [comment]
The difference is that the space makes it a css [descendant selector](https://api.jquery.com/descendant-selector/).

Both
 ```
$(".well :nth-child(3)").addClass("animated bounce");
```
and 
```
$(".target:nth-child(3)").addClass("animated bounce");
```
mean the same thing, but the wording of the instructions suggest the user to do #1 (IE target the children of the `.well`) without explaining the descendant selector.

**Comment by CodeDragoness** [comment]
I'm so glad I searched for help! I had been stuck on this for a while. Why has this typo not been fixed yet?

**Comment by hworth** [comment]
This STILL has not been fixed yet

**Comment by ahstro** [comment]
@hworth, if you read @benschenker's comment, they explain what's going on here :)
