### ISSUE TITLE
Manipulate arrays with unshift

### ISSUE THREAD

**Issue by bilocada** [FreeCodeCamp/FreeCodeCamp#1929]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. 
Just a little detail that may lead to confusion: in the description of the Waypoint it's written "to the end", when the unshift function adds the new value to the beginning of the array:
"Let's take the code we had last time and unshift this value to the 'END': "Paul"". (I've written it in uppercase so you can see it better).
That's all. Thanks for the work you're doing! ;)

**Comment by knifecake** [comment]
This appears to be fixed in  ae6746f
