### ISSUE TITLE
/challenges results in occasional 404 errors

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/freecodecamp#193]
https://twitter.com/gyaresu/status/576208410368192513

**Comment by BerkeleyTrue** [comment]
could be unhandled `err` in callback?

**Comment by QuincyLarson** [comment]
Possibly. I'll take a look

**Comment by QuincyLarson** [comment]
I haven't seen this much since, nor heard reports of it. It looks like errors are being handled in challenges.js (which is already removed from the Reactify branch anyway). So I'm going to close this.

**Comment by jameskopacz** [comment]
I had this happen earlier on the live server. I was visiting a profile page freecodecamp.com/test123456 and got the "Application Error" page (https://pbs.twimg.com/media/B_8afgiWoAAhBb7.png). I then tried to load the homepage. I didn't get an application error, the page just didn't load. It was like the app had crashed and was restarting.

Is there anything in the server logs that might be showing what might be happening?
