### ISSUE TITLE
Ctrl + Enter to progress to next challenge also adds a return to text

### ISSUE THREAD

**Issue by iBrooks** [FreeCodeCamp/FreeCodeCamp#1931]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-form-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Issue: ctrl+enter adds a return to the text in addition to moving to the next challenge

reproduce: have the challenge completed and the cursor still active in the text editor. Press ctrl+enter.

note, this issue appears across challenges, this is just the challenge I noticed it on

**Comment by bugron** [comment]
Related to: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1887

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
