### ISSUE TITLE
Incorrect instructions in challenge "Iterate with while loops"

### ISSUE THREAD

**Issue by thepeted** [FreeCodeCamp/FreeCodeCamp#1932]
Challenge http://www.freecodecamp.com/challenges/waypoint-iterate-with-javascript-while-loops has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

It says "Let's try getting a for loop to work by pushing values to an array." 

Should say "Let's try getting a while loop to work...."

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1802

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
