### ISSUE TITLE
[Guides] PHP duplicate variable pages

### ISSUE THREAD

**Issue by shamamaz** [freeCodeCamp/freeCodeCamp#19324]
There are multiple pages that detail php variables. These need to be consolidated.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/php/php-variables/
https://guide.freecodecamp.org/php/variable-basics/
https://guide.freecodecamp.org/php/#variables-panel

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 69.0.3497.100
* Operating System: Mac OS High Sierra

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="468" alt="screen shot 2018-10-15 at 12 49 55" src="https://user-images.githubusercontent.com/11925430/46965503-119e3000-d079-11e8-95c9-c2e108387762.png">

**Comment by chiffonsigh** [comment]
I will do this
