### ISSUE TITLE
 Regular Expressions: Find Characters with Lazy Matching html example

### ISSUE THREAD

**Issue by arnas** [freeCodeCamp/freeCodeCamp#19344]
**Describe your problem and how to reproduce it:**
Why the given example uses html snippet? Like it gives idea that regex is good for html parsing. Where is this  https://stackoverflow.com/a/1732454

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/find-characters-with-lazy-matching

**Comment by arnas** [comment]
Well it doesn't suggest explicitly. But it can give an idea that regex is good for searching in patterns in html. Well maybe it's just me,  if that the case I can close the issue.

**Comment by Nirajn2311** [comment]
@arnas we could put that in the introduction page of regex
[
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions](url)

**Comment by ezioda004** [comment]
@arnas Except it's indeed fine to search for patterns in HTML strings. See [this thread](https://stackoverflow.com/questions/7167279/regex-select-all-text-between-tags).
- Parsing regex in HTML 👎 
- Matching patterns in HTML strings 👍 

I hope this clears it up.

**Comment by arnas** [comment]
@ezioda004 Well in that thread most of the people just provided the answer how to do it. But there is not one and not two who recommended against the idea to do it with regex. 
Ofc in freecodecamp task regex is not used to get content between html tags. But like I said there should be at least a note that would say that regex is only valid in rare cases where you need to match pattern  in html string. Otherwise you should use dedicated html parser.

**Comment by ezioda004** [comment]
@arnas As long as we're clear that pattern matching != parsing. 

A cautionary note about parsing is fine by me. Something along the lines of:
> **Note** : Parsing HTML with regex should be avoided but pattern matching an HTML string with regex is completely fine.

**Comment by arnas** [comment]
@ezioda004 Yeah I agree with that. This note would suffice, but then maybe explanation is needed matching vs parsing? 😄

**Comment by RandellDawson** [comment]
It seems we have agreement on the note to add to this challenge's verbiage.  Anyone want to take a shot at fixing this?

**Comment by chaomt** [comment]
@RandellDawson I would like to work on it!

**Comment by RandellDawson** [comment]
@chaomt Sure go ahead and let us know if you need any help.  You can reply here or for more immediate feedback, checkout our [Contributors room on Gitter](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by chaomt** [comment]
> @chaomt Sure go ahead and let us know if you need any help. You can reply here or for more immediate feedback, checkout our [Contributors room on Gitter](https://gitter.im/FreeCodeCamp/Contributors).

@RandellDawson Thanks so much! I started working on it. I'm a beginner and I will try my best!

**Comment by chaomt** [comment]
@RandellDawson 
@hilliarj, @Fordco and I worked on this together. The pull request is above.
