### ISSUE TITLE
Waypoint: Target the Parent of an Element Using jQuery

### ISSUE THREAD

**Issue by vhdinh** [FreeCodeCamp/FreeCodeCamp#1935]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

i added the parent element and my left-well background is red but i'm not able to move on.

![image](https://cloud.githubusercontent.com/assets/13775747/9315852/8801675c-44e6-11e5-8349-7537148f79a3.png)

Thanks

**Comment by romeoSandbox** [comment]
Same thing for me as well...

**Comment by benmcmahon100** [comment]
This has just been fixed

**Comment by romeoSandbox** [comment]
Works!!! Thanks...
