### ISSUE TITLE
Confusing Waypoint: Write Reusable JavaScript with Functions

### ISSUE THREAD

**Issue by Daynewr** [FreeCodeCamp/FreeCodeCamp#1936]
http://www.freecodecamp.com/challenges/waypoint-write-reusable-javascript-with-functions

In this waypoint you learn functions but a few things are confusing to new people in my opinion:

**1)  Showing functions written two different ways without any explanation:**

On the code you see: 
```
ourFunction = function() {
  return a - b;
};
```
but the description shows  a function written like this:
```
function functionName (a, b) {

  return(a + b);

}
```
If this is your first time seeing this it could bring unnecessary confusion in my mind.

**2.) The function shown in the code does not pass any arguments.**
This code shown again does not have anything passed in and uses the global variables.  Being new this could cause unnecessary confusion without understanding how functions work:
```
ourFunction = function() {
  return a - b;
};
```

I suggest removing the ```ourFunction = function() { return a -b; };``` in the code or maybe explaining how the values are getting into the function by passing them or globally.

**Comment by ArgonCode** [comment]
Also, the task itself does not say clearly what to write inside `myFunction`.

**Comment by benschenker** [comment]
Thanks @Daynewr,

Confirmed!  Also the test does not actually run the function thus:
```
function(){
   return a+b;
}
```
will pass even though `a` and `b` aren't set
