### ISSUE TITLE
I think there is a bug in the Waypoint: Target the Parent of an Element Using jQuery. Either that or I am very tired.

### ISSUE THREAD

**Issue by rbtkarlsson** [FreeCodeCamp/FreeCodeCamp#1937]
$("#target1").parent().css("background-color", "red"); gives the #left-well a red background but it still complains that the waypoint isn't done...

![image](https://cloud.githubusercontent.com/assets/13721677/9315855/fa5b3cba-4531-11e5-8232-cefbcf892398.png)

**Comment by xz64** [comment]
I ran into this issue as well...

**Comment by AryanJ-NYC** [comment]
Refer to issue #1895.

**Comment by rbtkarlsson** [comment]
No i don't think so @AryanJ-NYC . Look into my code again. Doesn't reference the wrong parent I think... It is not the same error. Not sure how the user in #1895 fixed it though...

**Comment by AryanJ-NYC** [comment]
Ah, OK. I know @benmcmahon100 changed the test a bit. He'll have a better idea.

Apologies for assuming.

**Comment by SaintPeter** [comment]
I've been doing some investigating and what I've found is this:
```javascript
$("#left-well").css("background-color");
```
returns `rgb(255, 0, 0)`, not `red` as expected.

Here is a Codepen that illustrates the issue.
http://codepen.io/SaintPeter/pen/jPoGGX

**Comment by benmcmahon100** [comment]
Hey guys I fixed this a while ago! is this still an issue?

**Comment by AryanJ-NYC** [comment]
Yes. Check 7f4aa5487f573616f7f765fe948f667aad60af04. @SaintPeter pointed out a missing ||

**Comment by benmcmahon100** [comment]
That's been overwritten again

**Comment by benmcmahon100** [comment]
as per https://github.com/FreeCodeCamp/FreeCodeCamp/commit/f0f75eeae54ef194c534a0be74358b6845a5bc7c

**Comment by SaintPeter** [comment]
Not fixed.  

As per my comment above:
```javascript
$("#left-well").css("background-color");
```
returns `rgb(255, 0, 0)`, not `red` as expected.

Here is a Codepen that illustrates the issue.
http://codepen.io/SaintPeter/pen/jPoGGX

If you check for ```=== red``` it won't work.

**Comment by benmcmahon100** [comment]
@SaintPeter The commit is old I've made that new one since then

**Comment by SaintPeter** [comment]
@benmcmahon100 Ok, I was looking at the current status of the Staging branch and still see the old code.  I'll stop bugging you and let you get on with the fixing of the bug.

**Comment by benmcmahon100** [comment]
@SaintPeter Is it wrong on staging? It shouldn't be! :worried:

**Comment by benmcmahon100** [comment]
Moving this here https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1943
