### ISSUE TITLE
I cannot submit to complete any of the coding challenges

### ISSUE THREAD

**Issue by howestorm** [freeCodeCamp/freeCodeCamp#19385]
I researched online and it seems like the solution is just to refresh a bunch of times, but that isn't working for me. I may just be the victim of severe user error, but if I'm not, I'm not entirely sure how I submit after I complete each challenge. I select run all tests and it does nothing. Do I have to wait ten minutes or something? I suppose I could just continue on without the website acknowledging my accomplishments, but I digress. Any help would be mundo appreciated. 

https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements

Microsoft Edge

**Comment by ezioda004** [comment]
Hi @howestorm,
Edge is not supported by our platform, sorry for the inconvenience caused.

**Comment by RandellDawson** [comment]
I am closing this PR, because the challenge can be completed successfully with Chrome or Firefox.
