### ISSUE TITLE
Waypoint: Sift Through Text with RegExp has incorrect regex requirements

### ISSUE THREAD

**Issue by CrockAgile** [FreeCodeCamp/FreeCodeCamp#1938]
Challenge http://www.freecodecamp.com/challenges/waypoint-sift-through-text-with-regular-expressions has an issue.

The challenge is to search a string of text for occurrences of the word 'and'.

But currently the challenge requires the RegEx `/and+/gi` which is incorrect due to allowing 1 or more 'd's. This pattern would match and, anddddd, anddddddddd, etc.

The challenge currently rejects the correct RegEx `/and/gi`.

**Comment by evilputty** [comment]
Confirmed for me as well.

**Comment by DogCatWoof** [comment]
+1

**Comment by bugron** [comment]
Closing this issue as PR #2490 is merged.
