### ISSUE TITLE
Correct code does not get recognized

### ISSUE THREAD

**Issue by oscar84x** [FreeCodeCamp/FreeCodeCamp#1940]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I'm entering what I believe to be the right code for this exercise [$("#target1").parent().css("background-color","red");] with the right results which is the left well's background turning red, but it doesn't get recognized.

![2015-08-17 16_51_20-waypoint_ target the parent of an element using jquery _ free code camp](https://cloud.githubusercontent.com/assets/13351700/9315967/5734b362-4500-11e5-9b00-64da80f158ee.png)

**Comment by jbmartinez** [comment]
The first test has a somewhat random behavior

**Comment by gillettelevi5** [comment]
https://www.google.com/policies/technologies/cookies/

LG

Juan Martínez <notifications@github.com> wrote:

The first test has a somewhat random behavior

---

**Comment by jbmartinez** [comment]
I don't think cookies are the problem here

**Comment by gillettelevi5** [comment]
admin

**Comment by gillettelevi5** [comment]
admin

**Comment by benschenker** [comment]
I'm having trouble reproducing this, it may have been fixed.  @oscar84x is this still an issue for you?

**Comment by benschenker** [comment]
Closing as stale, reopen if issue still exists
