### ISSUE TITLE
Adding a new line does not scroll the text editor

### ISSUE THREAD

**Issue by iBrooks** [FreeCodeCamp/FreeCodeCamp#1941]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Issue: adding a new line at the bottom of the text editor does not scroll the editor to make the new line visible

reproduce: move the cursor to the bottom line of the text editor. press enter to add a new line. the cursor will now be on that new line but will not be visible without scrolling the text editor window to see it

**Comment by benschenker** [comment]
Hey @iBrooks, thanks for posting this!

Confirmed.  In my browser I can make it scroll the text editor if i place 4 newlines at the end of this challenge.  I think it has to do with making the div overlap with the footer.  Good catch!

**Comment by ltegman** [comment]
This was resolved when we updated to the newest version of codemirror recently. It will still let you put in one line without scrolling since the line will not be completely out of view, but as soon as the newest line is completely invisible it will scroll.
