### ISSUE TITLE
Potential Bug on JQuery Module 13. Target the Parent of an Element Using jQuery

### ISSUE THREAD

**Issue by lfbenson** [FreeCodeCamp/FreeCodeCamp#1943]
Challenge http://freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Screenshot:
![screen shot 2015-08-17 at 2 06 43 pm](https://cloud.githubusercontent.com/assets/3876746/9316435/df536872-44e9-11e5-877e-3e0bfd7738b4.png)

If the following code is correct, then there is a bug:
```javascript
<script>
  $(document).ready(function() {
    $("#target1").parent().css("background-color", "red");
  });
</script>
```

**Comment by Em-Ant** [comment]
It's the same for me. it's still not working ...

**Comment by roma0104** [comment]
The code is correct, it is a bug.

**Comment by mjbarnes17** [comment]
I'm having the same issue as well.

**Comment by deadwishd** [comment]
Ive got the same problem.
Its good to know im not alone.
I will be skipping this waypoint for now.

**Comment by Em-Ant** [comment]
I passed it right now. Seems to work.

**Comment by presleyatthereach** [comment]
I finally passed it as well :)
