### ISSUE TITLE
WayPoint: Iterate With JavaScript While Loops (typo & add MDN link)

### ISSUE THREAD

**Issue by Daynewr** [FreeCodeCamp/FreeCodeCamp#1945]
The following Waypoint asks you to use a **while** loop, but references a **for** loop at the bottom of the instructions.
Also, it would be helpful to add the MDN links for a lot of the Basic JavaScript WayPoints (such as https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/while for this one).  I found those extremely helpful previously and it caused me to use the MDN and understand how to read it.

http://www.freecodecamp.com/challenges/waypoint-iterate-with-javascript-while-loops

--------------------------------------------------------------------------------------------------

**Waypoint: Iterate with JavaScript While Loops**

You can run the same code multiple times by using a loop.

Another type of JavaScript loop is called a "while loop" because it runs "while" something is true, and stops once that something is no longer true.
```
var ourArray = [];

var i = 0;

while(i < 5) {

  ourArray.push(i);

  i++;

}
```
Let's try getting a **for loop** to work by pushing values to an array.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1932
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1802

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
