### ISSUE TITLE
It's not working for me to add borders

### ISSUE THREAD

**Issue by javamar** [FreeCodeCamp/FreeCodeCamp#1946]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey @javamar ,

Take a look at our new [Bug Posting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug).

I'm going to close this issue for now but reopen if the above steps do not resolve the problem
