### ISSUE TITLE
Lesson 31 - Javascript Generate random whole numbers within a range comment error

### ISSUE THREAD

**Issue by mlamont8** [FreeCodeCamp/FreeCodeCamp#1947]
Challenge http://freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-within-a-range has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Comment on line 4 of editor reads `Make myFunction return a random number between zero and nine instead of a decimal`

Should read `Make myFunction return a random number between min and max values instead of a decimal`

**Comment by benschenker** [comment]
Hey @mlamont8, thanks for posting this.

Confirmed!

**Comment by mquan86** [comment]
I think the lesson should be generate a range different with [0, 9]. It should be range [2, 9]. 
If not, the student may misunderstand why can't use Math.floor(Math.random() * max) instead of Math.floor(Math.random() * max-min) + min)
