### ISSUE TITLE
Waypoint: Iterate over Arrays with map - Exercise Not Given

### ISSUE THREAD

**Issue by AryanJ-NYC** [FreeCodeCamp/FreeCodeCamp#1950]
Challenge http://www.freecodecamp.com/challenges/waypoint-iterate-over-arrays-with-map has an issue.

![image](https://cloud.githubusercontent.com/assets/8263430/9317091/548c11ee-4507-11e5-9c0f-ec7b083fbe75.png)
Nowhere in the directions does it indicate we should add 3 to each element.

**Comment by Em-Ant** [comment]
Yeah, it's a little confusing.

**Comment by bugron** [comment]
That part is for common information and description on the challenge. 
The first test is: You should have added three to each value in the array: expected [ 1, 2, 3, 4, 5 ] to deeply equal [ 4, 5, 6, 7, 8 ].
So first you need to read **in right place** what you need to do to finish the challenge.

**Comment by benschenker** [comment]
Yeah, I'd say that the description does need to be updated, I can't find any other issues filed for this so lets keep this one open until the description changes to include something like:
```
Use the map function to add 3 to every value in the variable `array`
```
