### ISSUE TITLE
[ Curious ]  Where the guide folder on this repo  readable on freecodecamp website?

### ISSUE THREAD

**Issue by bauripalash** [freeCodeCamp/freeCodeCamp#19520]
I'm curious where the `guide` on this repo exactly readable on the FreeCodeCamp site

**Comment by jonathan-grah** [comment]
@bauripalash, currently at https://guide.freecodecamp.org. Please use the [forum](https://forum.freecodecamp.org) or [gitter](https://gitter.im/FreeCodeCamp/home) for asking questions like these. This is for code-base related bugs and issues only.
