### ISSUE TITLE
jQuery first waypoint does not pass last condition

### ISSUE THREAD

**Issue by tomsun100** [FreeCodeCamp/FreeCodeCamp#1953]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. 

The last condition does not pass with the correct code. 
```
<script>
$(document).ready(function(){});
</script>
```

**Comment by FedericoPonzi** [comment]
move }); in another line.

    <script>
     $(document).ready(function(){
    
    });
    </script>

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1858

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
