### ISSUE TITLE
Error on <p> tag contents

### ISSUE THREAD

**Issue by madhusudan1** [FreeCodeCamp/FreeCodeCamp#1954]
Challenge http://freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Error on:
Your p element should contain the first few words of the provided additional kitty ipsum text.

My Code: 

<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

OR

![p tag content error](https://cloud.githubusercontent.com/assets/8527624/9317899/716c229a-44f3-11e5-8b0d-df962d59027f.jpg)

**Comment by michael-krebs** [comment]
Your second <p> tag contains the wrong quote. Use the text provided in the instructions.

**Comment by madhusudan1** [comment]
Thanks for the help
