### ISSUE TITLE
Checker not working on Waypoint: Target the same element with multiple jQuery Selectors

### ISSUE THREAD

**Issue by kldickenson** [FreeCodeCamp/FreeCodeCamp#1956]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![screen shot 2015-08-17 at 6 20 29 pm](https://cloud.githubusercontent.com/assets/2073648/9317935/dbe2a090-450c-11e5-8fc2-2dc41ebe3ee2.png)
Checker is not accepting #target1 even though jQuery is correct:
<script>
  $(document).ready(function() {
    $("button").addClass(animated);
    $(".btn").addClass(shake);
    $("#target1").addClass(btn-primary);
  });
</script>

**Comment by jbmartinez** [comment]
Wrap your classes in quotes, i.e. `.addClass("animated")`

**Comment by jentrification** [comment]
@jbmartinez, thanks for the help. 

when we add the quotes, the activity works for "btn-primary" even though the exercise calls for #target1 to use animated, shake, and btn-primary.

**Comment by jbmartinez** [comment]
I've already created a pull request ( #1995) for that issue, @jentrification, hopefully it get merged soon. Thanks for reporting

**Comment by TanaLandis** [comment]
Suggestion below is for modifying learner instructions. 
Current - Now you know three ways of targeting elements: by type: $("button"), by class: $(".btn"), and by id $("#target1").
Suggested - Now you know three ways of targeting elements! Elements can be targeted by element type: $("button"), by class: $(".btn"), and by id $("#target1").
Current - Use each of these jQuery selectors to target your button element with the class btn and the id target1.
Suggested - Use each of these jQuery selectors to target your button element, the class btn, and the id target1.
Current - Use the addClass() jQuery function to give the element one new class for each selector: animated, shake, and btn-primary.
Suggested - Use the addClass() jQuery function to give the button element one new class through each selector. The classes to be used are animated, shake, and btn-primary.

The highlighted task below needs to be deleted to agree with current and suggested instructions.
![Waypoint: Target the same element with multiple jQuery Selectors](https://cloud.githubusercontent.com/assets/10489812/9443251/1190a14c-4a4e-11e5-939c-271c8f7487bd.png)

**Comment by benschenker** [comment]
Looks like this has been fixed! Closing.

**Comment by otherholli** [comment]
THANK YOU TanaLandis! I was confused about what exactly I was supposed to do on this WayPoint according to the "Current" instructions. Your "Suggested" instructions made it much more clear.

**Comment by TanaLandis** [comment]
@otherholli Glad they could help! Kudos to you for searching and finding what you needed :).

**Comment by creator2earth** [comment]
Can someone give an example how this is done. I seemed to have done the same thing, and I can't get the code to go thru.

**Comment by LisB2016** [comment]
@creator2earth There is no bug. Solution below in this post.

@jbmartinez or @benschenker or @whoevermightbeinterested in improving user-experience of Challenge #115

Still quite a **confusing** challenge for the combination task-checkpoints.
Description of the task leaves you without any example, which is nice to start thinking, but previous tasks got us used to copy examples.
It took me quite a while to figure out what my mistake was.(used . instead of - in btn-primary)
Checkpoint 5 red made my doubt whether I understood the challenge.

**Suggestion**: "Your #target1 button should **show** animated, shaking and blue."

**Correct=**
&lt;script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake")
    $("#target1").addClass("btn-primary");
  });
</script&gt;

**Comment by dkngumba** [comment]
Finally passed this level after three days of research..Good job to the team..it was a very simple error..

**Comment by Enkkee** [comment]
Hi, Could you explain this problem?
My code was like this but it was not working until when i made copy of LisB2016's code. What is it? What happened here? Should i make copy paste? I left my code here. Here is no difference at all.
<script>
$(document).ready(function() {
$("button").addClass("animated");
$(".btn").addClass("shake")
$("#target1").addClass("btn-primary");
});
</script>

**Comment by mejiaadonay** [comment]
This challenge is really confusing. I thought they meant to add all the functionality in a single line.
But What I noticed was they tried to explained how the element inhered the class. For example the first line
`$("button").addClass("animated"); ` Since all the button element received the class animated, it is not necessary to put the class again in the next line because it is already assigned to button.
```
$(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn-primary");
});
```

**Comment by lokirajagopal** [comment]
hi

**Comment by lokirajagopal** [comment]
i too have the same problem

**Comment by lokirajagopal** [comment]
```js
<script>
  $(document).ready(function() {
  $("button").addclass("animated");
  $(".btn").addclass("shake");
  $("#target1").addclass("btn-primary");

  });
</script>

**Comment by lokirajagopal** [comment]
please help me

**Comment by lokirajagopal** [comment]
@TanaLandis got correct how tell us i can't nderstand

**Comment by lokirajagopal** [comment]
i figured out capitalise C in Class

**Comment by texas2010** [comment]
@lokirajagopal 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
