### ISSUE TITLE
Selecting text and tab indenting it

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/freecodecamp#196]
I'm not sure how complicated this would be to implement, but it would be nice if users could select text in bonfire and hit tab to tab in all selected text. The current behavior is the tab overwrites all selected text.

**Comment by MrRenter** [comment]
Code mirror should have a built in option to do this and can be seen working here. http://codemirror.net/demo/markselection.html
I suggest taking a look into defaultTab option for code mirror

**Comment by MrRenter** [comment]
https://github.com/FreeCodeCamp/freecodecamp/pull/198
