### ISSUE TITLE
Chrome crashing

### ISSUE THREAD

**Issue by emaclean03** [FreeCodeCamp/FreeCodeCamp#1960]
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

after typing "$($", chrome crashes.

**Comment by jbmartinez** [comment]
Could campers live without auto closing brackets?

**Comment by zorfa** [comment]
![capture](https://cloud.githubusercontent.com/assets/8377726/9466875/e9c7cb9e-4b48-11e5-9fd7-09862477981d.PNG)
I am unable to complete the Waypoint: Bring your JavaScript Slot Machine to Life http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life 

My browser crashes each time I attempt to complete it. The attached screenshot shows the exact line I was typing when it happened.

**Comment by BerkeleyTrue** [comment]
$($) will throw as you are attempting to pass a function into itself. Since we autoload your last code from localStorage, you browser freezes.

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser's-Local-Storage

You need to remove this waypoint from localStorage.

**Comment by zorfa** [comment]
Thanks Berkeley! That solved my problem.

**Comment by BerkeleyTrue** [comment]
Fixed!

Happy Coding!
