### ISSUE TITLE
Challenge does not show correct problem

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#19608]
**Describe your problem and how to reproduce it:**
Type the code which I have(can be found in the picture)into the challenge and you will get an error that a normal learner cannot understand. I think it's with the internal checking system.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/data-visualization/data-visualization-with-d3/create-a-scatterplot-with-svg-circles

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 69.0.3497.100 (Official Build) (32-bit)
* Operating System: Windows 7 x32

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/34807532/47081045-359f7400-d227-11e8-9524-6b18d85b7797.png)

**Comment by rajurajvijay619** [comment]
The actual solution should be something like this : 
svg.selectAll("circle")
       .data(dataset)
       .enter()
       .append("circle")
       .attr("cx", (d) => d[0])
       .attr("cy", (d) => d[1])
       .attr("r", 10)

Kindly refer to this article : [https://www.dashingd3js.com/adding-an-svg-element](adding-an-svg-element)

**Comment by thecodingaviator** [comment]
@rajurajvijay619 that's not my point, my point is if I write wrong code that is not the solution, I should be told which part of the challenge do I not comply to not -
` Failed to execute 'insertBefore' on 'Node' : parameter 1 is not of type 'Node' `

What the hell does it even mean for a beginner?

**Comment by rajurajvijay619** [comment]
Yes. Agreed it doesn't tell you on which line the error is occurring and it's not informative enough.
But one simple google search about the "append()" function could lead you to the documentation and tell you what it expects :)
https://devdocs.io/d3~4/d3-selection#selection_append

**Comment by thecodingaviator** [comment]
@rajurajvijay619 Seems fine, but I think I'll leave this open for some more time and see if someone can respond as to why I'm getting that message

**Comment by ArielLeslie** [comment]
That's not a message generated by Free Code Camp. That's a true blue syntax error.

**Comment by thecodingaviator** [comment]
@ArielLeslie so from what I understand, it’s not correctable on our part. Right?

**Comment by ArielLeslie** [comment]
It doesn't really need correction. If you attempt to run that code in a real environment, you'll get that exact error. If we attempted to intercept error messages and print something else, not only are we setting ourselves up for a lot of work for little gain, but students wouldn't see standard error messages that they could google.

**Comment by thecodingaviator** [comment]
@ArielLeslie Ahh I see. Clears up my doubt
