### ISSUE TITLE
Can't seem to go past this. I guess it's a bug.

### ISSUE THREAD

**Issue by codebrew85** [FreeCodeCamp/FreeCodeCamp#1962]
Challenge http://freecodecamp.com/challenges/waypoint-manipulate-arrays-with-shift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by apositivejam** [comment]
What code are you entering? I'm able to get it to pass fine with the code

var myRemoved = myArray.shift();

on line 8.

**Comment by BerkeleyTrue** [comment]
closing. Please reopen with more information on how to reproduce issue.

Please see: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-help-when-you-get-stuck

**Comment by codebrew85** [comment]
ok. thanks.

fixed now.
