### ISSUE TITLE
Impossibility of passing this test

### ISSUE THREAD

**Issue by letal32** [FreeCodeCamp/FreeCodeCamp#1963]
Challenge http://freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

It's impossible to pass this challenge even if the code is correct.

**Comment by BerkeleyTrue** [comment]
Please provide more information on how to reproduce the issue.

**Comment by letal32** [comment]
If I copy the following code in the left column (the one with the instructions) 
$("#left-well").parent().css("background-color", "blue");
and I change blue with red, the left well backgroud changes color but the button go to my next challenge doesn't become active.

**Comment by dokkillo** [comment]
Hi, its not a bug.

You must use parent for change the background of left-well element, using parent. It means, you need call Target5, its a child of left-well. I had the same problem.

$("#target5").parent().css("background-color", "red");

![fcc1](https://cloud.githubusercontent.com/assets/920841/9325857/df269bec-4595-11e5-8dce-24e2eed12a4e.png)

**Comment by letal32** [comment]
It works. Thank you very much!
