### ISSUE TITLE
Lets you move on

### ISSUE THREAD

**Issue by ShelbyGT** [FreeCodeCamp/FreeCodeCamp#1966]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible. When doing this waypoint, before you do part 2 of 3, it allows you to click the go to next lesson.

**Comment by jbmartinez** [comment]
This seems to be a problem common to all of the basic waypoints. It happened to me in my local copy. See #1503 and (probably) #1351

**Comment by benschenker** [comment]
Hey @ShelbyGT thanks for posting!
I cannot replicate this, is it still an issue for you?
