### ISSUE TITLE
Add FAQ page to the homepage

### ISSUE THREAD

**Issue by chaomt** [freeCodeCamp/freeCodeCamp#19671]
**Describe the bug**
It’s a little difficult to find FAQ page which is very useful and includes many helpful links.

**To Reproduce**
Basically, we need to click “forum” and then click the menu image. Then from the drop-down list, we can see FAQ. 
<img width="1439" alt="screen shot 2018-10-17 at 17 24 42" src="https://user-images.githubusercontent.com/42958064/47117167-a2b80700-d231-11e8-9a0d-0b5345cda4b9.png">
https://www.freecodecamp.org/forum/

**Expected behavior**
Since we don’t need to sign up or sign in to view FAQ page and it is very helpful for beginners, it's better to also put it directly on the homepage of freeCodeCamp website so that people can see it easily. 

**Desktop:**
 - OS: iOS 10.13.5
 - Browser: chrome 69.0.3497.100

**Comment by albanmahmut** [comment]
Do you mean somewhere close to the 'sign in'?

![freecodecamp](https://user-images.githubusercontent.com/31076993/47134613-9090a400-d2d7-11e8-81a9-14025ee5d6f1.png)

Something like that? @chaomt

**Comment by Nirajn2311** [comment]
@chaomt I can take this up if no one has started working on it.

**Comment by mels065** [comment]
@Nirajn2311 I'm working on it

**Comment by jonathan-grah** [comment]
@QuincyLarson, is this a change we want to make?

**Comment by chaomt** [comment]
> Do you mean somewhere close to the 'sign in'?
> 
> ![freecodecamp](https://user-images.githubusercontent.com/31076993/47134613-9090a400-d2d7-11e8-81a9-14025ee5d6f1.png)
> 
> Something like that? @chaomt

**Comment by chaomt** [comment]
> Do you mean somewhere close to the 'sign in'?
> 
> ![freecodecamp](https://user-images.githubusercontent.com/31076993/47134613-9090a400-d2d7-11e8-81a9-14025ee5d6f1.png)
> 
> Something like that? @chaomt

Yes!

**Comment by mengzy2018** [comment]
This will be convenient for users

**Comment by QuincyLarson** [comment]
Thanks for the suggestion. We want to keep the navigation as simple as possible with as few options as absolutely necessary. If people want an FAQ they can google freecodecamp.
