### ISSUE TITLE
Cursor moves out of find and replace box after typing the character 'e'

### ISSUE THREAD

**Issue by MP7373** [freeCodeCamp/freeCodeCamp#19695]
I tried using the find and replace in the editor with Command + Option + F while doing a challenge and noticed that after typing the 'e' or 'E' character in the find or replace box my cursor would automatically move to the selected word on the page (out of the find or replace box and onto challenge editor section
![cursor moving out of find and replace](https://user-images.githubusercontent.com/11096661/47130091-01977380-d266-11e8-83c5-b70ca152ddb8.png)
).

Add a Link to the page with the problem:
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/declare-a-read-only-variable-with-the-const-keyword
(I think it's on all pages and is the editor but I noticed it here)

Browser Name: 
Google Chrome
Browser Version: 
Version 69.0.3497.100 (Official Build) (64-bit)
Operating System: 
macOS High Sierra
10.13.6

**Comment by freginold** [comment]
Happens to me too (Windows 7), runs the query when you type the `e`/`E` then moves out of the box on the next keypress.
