### ISSUE TITLE
Rosetta Code: Equilibrium index assertion tests not working

### ISSUE THREAD

**Issue by alhazen1** [freeCodeCamp/freeCodeCamp#19693]
**The assertion tests on this challenge don't appear to be working correctly.**
 I peeked into console on dev tools and it looks to me that the tests are not passing test arrays to the solution. When I log out the value of parameter a this is what is displayed

`{text: "<code>equilibrium([-7, 1, 5, 2, -4, 3, 0])</code> should return <code>[3,6]</code>.", testString: "assert.deepEqual(equilibrium(tests[0]), ans[0], '<…, 0])</code> should return <code>[3,6]</code>.');", err: "a.reduce is not a function↵TypeError: a.reduce is …camp.org/commons-19dd515e926e3ee50293.js:6:31129)", stack: "TypeError: a.reduce is not a function↵    at equil…camp.org/commons-19dd515e926e3ee50293.js:6:31129)", message: "a.reduce is not a function"}`

**Add a Link to the page with the problem:**
**https://learn.freecodecamp.org/coding-interview-prep/rosetta-code/equilibrium-index/**

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 69.0.3497.100 (Official Build) (64-bit)
* Operating System: Ubuntu 16.04.5

**This is result of `console.log(a)`**
![image](https://user-images.githubusercontent.com/9359321/47129052-584a8080-d259-11e8-8e39-b12102657681.png)

**Comment by ArielLeslie** [comment]
I'll take this.

**Comment by ArielLeslie** [comment]
I'll own this.

**Comment by ArielLeslie** [comment]
I would like to work this Issue.

**Comment by ezioda004** [comment]
Already fixed in master branch.
