### ISSUE TITLE
Unable to access challenges

### ISSUE THREAD

**Issue by keithdoyle9** [FreeCodeCamp/FreeCodeCamp#1971]
I've logged in via Google and LinkedIn on both Windows 7 Chrome/Firefox and OS X Chrome/Firefox but keep getting an error "Oops! Something went wrong. Please try again later" when trying to access challenges from the Map page. Then I'm redirected to the home page. I've also tried to link my Github account (all with the same email address) to "Unlock my profile" and it says it goes through after I authorize it but still no luck.

**Comment by BerkeleyTrue** [comment]
What is the username you used previously?

**Comment by keithdoyle9** [comment]
It was always keithdoyle9

**Comment by BerkeleyTrue** [comment]
Can you try again and let me know if you still have issues?

**Comment by keithdoyle9** [comment]
I can log in with Google and Github but all my progress is gone.

On August 20, 2015 11:31:39 PM EDT, Berkeley Martinez <notifications@github.com> wrote:
>Can you try again and let me know if you still have issues?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1971#issuecomment-133267780

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by keithdoyle9** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Everything seems to be working! Thanks!

On August 20, 2015 11:33:15 PM EDT, Keith <keithdoyle9@gmail.com> wrote:
>I can log in with Google and Github but all my progress is gone.
>
>On August 20, 2015 11:31:39 PM EDT, Berkeley Martinez
><notifications@github.com> wrote:
>>Can you try again and let me know if you still have issues?
>>
>>---
>>Reply to this email directly or view it on GitHub:
>>https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1971#issuecomment-133267780
>
>--
>Sent from my Android device with K-9 Mail. Please excuse my brevity.

- --
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----

iQJBBAEBCgArJBxLZWl0aCBEb3lsZSA8a2VpdGhkb3lsZTlAZ21haWwuY29tPgUC
VdcBRQAKCRCM16no2zjWPQWID/4zWys4p5sUCHtQA1e6XCUYt2XKEZEhQLAPYZ9b
3LZ4X3sV1Sex9dWr/rdF7QCaKkCLUc4MZaYG0naGuPOX4wVSASP3ygEGpxTg4eP7
SGYeyVqMOHW3qhcjynVdRe/WF+xuAAl4X0F5m+Mgt5LixllUFn74/dAGlGslnFoO
pexH2XfrQbqHaUCRaaZR8ZiE95PCKFqy6Rxm1dO+fofvVqnj8vN7G+aDd6qMnLC9
/9ZKJFydUWgTSJZkmgCJYCrTymjPOsDglo+pOdSrZXAZOUsttD4ttcuX3ewHi6Ss
EQ6Uyz9ys3AfLq5yeXgHFcMh5vdgqnlGoQCKFuGlHiEn3WTNNJ6afMuku4qDyrYc
rc1/B4h43LJfOTeCHPE0qWgruxC5HR06Fiic86ErsmMtxnRwhn27g0ky5pkxBfsf
eIFnwvQ9xIk7VBMcTbbcHTnlQQQhr4UF9Yzp/CQFoSSC6zT+Jj5HIPdX3FxHR3Vc
GwvNsYbxdgulHL6d8UaG1lqU7B7NYUapj0ulfNLk9NfSzo7bELbK2Vp17vpy0L1d
qelcHbCXgx1jo0zrBGRdOidkHwsfbb6eyg4l2h+hbZkphNCjwLWUZg0Un5yA9dDq
1TgDmSyWwfmddAozx+R4tIJHin1lxk8qshITfMU8Mntm9ebp1XHB+WyHB7E1OpL7
ujvBCw==
=L04g
-----END PGP SIGNATURE-----
