### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by 0x0936** [FreeCodeCamp/FreeCodeCamp#1972]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-first-character-in-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

"Use bracket notation to find the first character in a the firstLetterOfLastName variable."

probably should read as:

Use bracket notation to find the first character in the firstLetterOfLastName variable.

**Comment by issyl0** [comment]
Hi @0x0936! This issue has now been fixed, so if you'd like to mark it as fixed, just click the "Close" button at the bottom.
