### ISSUE TITLE
Waypoint: Use Conditional Logic with IfElse Statements fails at random

### ISSUE THREAD

**Issue by jbmartinez** [FreeCodeCamp/FreeCodeCamp#1974]
The first test case fails at random, even with a right solution. Reported in Gitter

**Comment by benschenker** [comment]
Yes it seems the test is wrong 50% of the time.

It tests: 

```
function(){
    if ( myFunction() === "heads" || myFunction() === "tails"){
        return(true);
    } else {
        return(false);
    }
}
```

It first runs the function and checks if the value is "heads" (50% chance),
then it runs the function again and checks if the value is "tails" (50% chance).

The test needs to store the value of one invocation of the function in a variable
and test that like:

```
function(){
    var result = myFunction(); // <---only one invocation
    if ( result === "heads" || result === "tails"){
        return(true);
    } else {
        return(false);
    }
}
```

**Comment by benschenker** [comment]
Sorry about the reference spam.  Looks like it was actually only wrong 25% of the time because the two expressions which each had a 50% chance of being correct were being ORed.

**Comment by jbmartinez** [comment]
@benschenker :+1:

**Comment by jschnei** [comment]
also, it is unclear to me why "Math.random() * (1 - 0 + 1)" is used instead of simply "Math.random() * 2" (in the starter code).
