### ISSUE TITLE
Vague

### ISSUE THREAD

**Issue by 0x0936** [FreeCodeCamp/FreeCodeCamp#1976]
Challenge http://www.freecodecamp.com/challenges/waypoint-write-reusable-javascript-with-functions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

"Create and call a function called myFunction."

probably should read similar to:

"Create and call a function called myFunction with parameters a and b that returns a + b."

**Comment by AryanJ-NYC** [comment]
Similar to #1936.

**Comment by benschenker** [comment]
Closing as duplicate
