### ISSUE TITLE
Can't complete Responsive Web Design Certification: CSS Flexbox - Create Grids within Grids

### ISSUE THREAD

**Issue by csnoke23** [freeCodeCamp/freeCodeCamp#19760]
![20181018 fcc](https://user-images.githubusercontent.com/17164144/47158356-b81c4800-d2a8-11e8-9513-8d355dbd026d.PNG)

**Describe your problem and how to reproduce it:**
The Responsive Web Design Certification: CSS Flexbox - Create Grids within Grids exercise will not complete and offers the message "item3 class should have a grid-template-columns property with auto and 1fr as values," on clicking *Run All Tests*.

I have gone so far as to copy the code example from the accompanying video and pasting it directly in the test area, and received the same message.

This issue occurs in both Chrome and Firefox

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/responsive-web-design/css-grid/create-grids-within-grids

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 69.0.3497.100 (Official Build) (64-bit)
* Operating System: Windows 10 Home

* Browser Name: Mozilla Firefox
* Browser Version: 62.0.3 (64-bit)
* Operating System: Windows 10 Home

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Nirajn2311** [comment]
@csnoke23 There is a spelling mistake in the css property. It should be **grid-template-columns** and not **grid-template-colums**.

Could you ask these kind of questions in the forum and cross check it first if it is a bug and then open an issue here.

**Comment by Asjas** [comment]
Hi @csnoke23 

As @Nirajn2311 noted, please use the [freeCodeCamp forum](http://forum.freecodecamp.org/) or [gitter helproom](https://gitter.im/FreeCodeCamp/HelpFrontEnd) to ask for help with the challenges.
