### ISSUE TITLE
Auto scroll issue on FreeCodeCamp forum post

### ISSUE THREAD

**Issue by StubRavi** [freeCodeCamp/freeCodeCamp#19794]
**Describe the bug**
When trying to read this forum post,
 https://www.freecodecamp.org/forum/t/freecodecamp-algorithm-challenge-guide-sum-all-primes/16085
, it gets auto scrolled to 
https://www.freecodecamp.org/forum/t/freecodecamp-algorithm-challenge-guide-sum-all-primes/16085/3 . I am unable to read that forum post because because web page auto scrolled upto a fixed position.

**To Reproduce**
1. Go to ' https://www.freecodecamp.org/forum/t/freecodecamp-algorithm-challenge-guide-sum-all-primes/16085 '
2. Scroll down to ' Hint 3 '
4. See error (it will auto scroll upto the position (see the screenshot))

**Screenshots**
![auto scroll error](https://user-images.githubusercontent.com/34769076/47170829-aaa4a380-d324-11e8-8f18-eb0e2595cfbf.JPG)

**Desktop (please complete the following information):**
 - OS: Windows7
 - Browser: chrome
 - Version : newest

**Comment by FranceJ** [comment]
It looks like this an issue with the repl.it iframe added in oshliaer's comment.
The search field is getting focus on page load which is causing the page to scroll it into view. The behaviour can be replicated in this toy model: https://jsfiddle.net/up240m93/

Removing that comment or at least the iFrame should fix this if it is something that needs to be fixed.

**Comment by RandellDawson** [comment]
This has been resolved.
