### ISSUE TITLE
Typo (Zipline: Build a Personal Portfolio Webpage)

### ISSUE THREAD

**Issue by oksas** [FreeCodeCamp/FreeCodeCamp#1980]
Challenge http://www.freecodecamp.com/challenges/zipline-build-a-personal-portfolio-webpage has a minor typo. Step 8 reads "[...] if you **don't** haven't built any websites before [...]" when it should simply read "[...] if you haven't built any websites before [...]". Additionally, the code styling from step 12 appears to be bleeding over into steps 13 - 16, so the text for those steps is improperly styled.

![ziplineissue](https://cloud.githubusercontent.com/assets/13337954/9321039/0250e4e0-4516-11e5-99bc-ae603947d8ee.PNG)

**Comment by zeffii** [comment]
Additional typo
```javascript
target="_blank">
```

not
```
<a target='_blank'&rt;.
```
