### ISSUE TITLE
Problem with the bottstrap challange #1

### ISSUE THREAD

**Issue by mangoser** [FreeCodeCamp/FreeCodeCamp#1983]
Challenge http://freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers has an issue.

We need to put all of our html codes in a div with a class container-fluid, but it doesn't matter where you put your code ...div class="container-fluid"></div... challange accept it everytime.

For example : ![bug](https://cloud.githubusercontent.com/assets/6990688/9321048/01bba660-456a-11e5-9497-d2d0075a9c68.png)

**Comment by esaky** [comment]
Adding a container-fluid to form element solves too. is that right ?
