### ISSUE TITLE
Incorrect mention of 'for loop' in a 'while loop' waypoint

### ISSUE THREAD

**Issue by 0x0936** [FreeCodeCamp/FreeCodeCamp#1987]
Challenge http://www.freecodecamp.com/challenges/waypoint-iterate-with-javascript-while-loops has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

"Let's try getting a for loop to work by pushing values to an array."

Should probably read as:

"Let's try getting a while loop to work by pushing values to an array."

**Comment by michael-krebs** [comment]
duplicate #1932

**Comment by BerkeleyTrue** [comment]
closing as duplicate.
