### ISSUE TITLE
Run code button not working

### ISSUE THREAD

**Issue by haasDev** [FreeCodeCamp/FreeCodeCamp#1989]
Challenge http://freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

when I attempt to run my code by hitting the button or hitting ctrl + enter the app is non-responsive.  The issue only presents itself in the basic javascript section.

**Comment by bugron** [comment]
What browser and OS are you using?

**Comment by haasDev** [comment]
It actually is fine now.
