### ISSUE TITLE
Issue with development server crash

### ISSUE THREAD

**Issue by MrRenter** [FreeCodeCamp/freecodecamp#199]

**Comment by MrRenter** [comment]
This will check whether or not were are in development mode and correct the problem

https://github.com/FreeCodeCamp/freecodecamp/commit/1d94e4448f6c9bf0c18323dc527d7adff4cb1747

**Comment by BerkeleyTrue** [comment]
Can you show the printout of the error when the dev server crashes?

**Comment by jameskopacz** [comment]
I'm not sure if it's the same errors he's running into but the ones I've run into are because a couple functions are using api keys that are invalid and the code isn't handing the errors. Both are in resources.js: trelloCalls and bloggerCalls.

**Comment by BerkeleyTrue** [comment]
We are aware of the unhandled errors slipping into the codebase. I believe the PR this issue is pointing to did not refer to these. @jameskopacz If you find any unhandled errors could you submit a PR? This could be one of the reasons the server crashes in production as well.

**Comment by jameskopacz** [comment]
Submitted a PR but it needs to be tested with valid API keys before being merged. #204
