### ISSUE TITLE
Adding An Applied Inclusiveness Section

### ISSUE THREAD

**Issue by VioletLain** [freeCodeCamp/freeCodeCamp#19901]
Note: This is a continuation of a previous discussion I had on the freeCodeCamp forums [1].

My suggestion is either to expand the scope of the Responsive Web Design Certification by adding section like the Applied Accessibility challenges, or to create a new section in the guide that focuses on this subject, similar to this link [2].

The goal of the section would be for teaching ways to make the web more inclusive for people of various backgrounds, especially while creating websites and apps such as social networks, medical services, dating websites and web surveys.

It could be used for teaching good practices for designing with translations and other cultures in mind, such as designing for right-to-left language [3], having full name fields rather than first and last name being separate [4], and similar issues.

It could also include a subsection for how to write questions [5] about ethnicity [6], sex [7, 8], gender [7, 9], sexual and romantic attractions [7], and other similarly sensitive topics. This could be done through challenges with html web survey examples, or if it is in the guide section by giving code examples.

There are also other guide posts [2, 10] that would be suited for inclusion in this section.

Links
[1] https://www.freecodecamp.org/forum/t/non-binary-gender-training-in-a-new-section-like-applied-inclusiveness/204736
[2] https://guide.freecodecamp.org/working-in-tech/women-in-tech/
[3] https://medium.muz.li/web-design-for-right-to-left-languages-the-basics-287329d508cf
[4] http://uxmovement.com/forms/why-your-form-only-needs-one-name-field/
[5] https://www.surveymonkey.com/curiosity/ask-sensitive-questions-surveys/
[6] https://www.smartinsights.com/online-brand-strategy/international-marketing/web-design-for-cultural-differences/
[7] https://www.okcupid.com/identity
[8] https://ccgsd-ccdgs.org/intersex-inclusion/
[9] https://uxdesign.cc/designing-forms-for-gender-diversity-and-inclusion-d8194cf1f51
[10] https://guide.freecodecamp.org/working-in-tech/unconscious-bias

**Comment by RandellDawson** [comment]
I am leaning toward most if not all of your ideas would be best placed into the Guide, but if you have an idea of how you would create a challenge for some of them, I would be interested to see how you envision it working.  The challenges tend to focus on syntax vs. concepts, so you can test it in some way.  Looking forward to what your ideas are on the subject matter presented here.

**Comment by VioletLain** [comment]
https://guide.freecodecamp.org/working-in-tech/unconscious-bias
I also found this in the guide already which may be well suited for the start of this section since many of the specific issues I mentioned all to some degree stem from this larger issue.

**Comment by RandellDawson** [comment]
@VioletLain Are you with us closing this issue now, since you can now attempt to create a PR to add/modify a guide article in which you feel this information would be best placed?

**Comment by VioletLain** [comment]
@RandellDawson Yes please; thanks. I still to write it yet but I'll be sure to make a pull request for it once I've finished writting it and citing all my sources.
