### ISSUE TITLE
Wrong comments - from previous waypoint

### ISSUE THREAD

**Issue by 0x0936** [FreeCodeCamp/FreeCodeCamp#1992]
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-within-a-range has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

"// Make myFunction return a random number between zero and nine instead of a decimal"

The above comment does not belong in this waypoint.

**Comment by benschenker** [comment]
This is a duplicate of #1947, see that issue for updates
