### ISSUE TITLE
waypoint make images mobile responsive: error when going to my next challenge

### ISSUE THREAD

**Issue by erratadei** [FreeCodeCamp/FreeCodeCamp#1996]
Challenge http://www.freecodecamp.com/challenges/waypoint-make-images-mobile-responsive has an issue. 
I'm not sure if it's just my case, but after clicking the button for going to next challenge I'm whisked away to a JS Array Waypoint: http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift. 
Keep up the good code!

**Comment by benschenker** [comment]
Thanks @erratadei,

This seems related to #2648 so keep an eye there for updates.
