### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by 0x0936** [FreeCodeCamp/FreeCodeCamp#1997]
Challenge http://www.freecodecamp.com/challenges/waypoint-sift-through-text-with-regular-expressions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

"Regular expressions are usually surrounded by / symbols."

In JavaScript, when are regular expressions **not** surrounded by forward slashes?

"We can do this by replacing the .+ part of our regular expression with the current regular expression with the word and."

... may be more clear as:

"We can do this by replacing the .+ part of our regular expression with the word and+."

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1938

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
