### ISSUE TITLE
errors on waypoint-comment-your-javascript-code

### ISSUE THREAD

**Issue by ScottPesetsky** [FreeCodeCamp/FreeCodeCamp#1999]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Left side error checking seems wrong

![comment your javascript code](https://cloud.githubusercontent.com/assets/6602253/9322092/8ff4273c-4523-11e5-8b61-72997748f789.png)

**Comment by vaticdart** [comment]
I couldn't get this to work until I entered the following:

//Not hello world
/*Still not hello world*/

Note that the /* and */, apparently, have to be on the same line.

Using Chrome 45.0.2454.85 on Mac OS 10.10.5.
