### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by 0x0936** [FreeCodeCamp/FreeCodeCamp#2000]
Challenge http://www.freecodecamp.com/challenges/waypoint-invert-regular-expression-matches-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

My regex is returning the value 7, but assert(test === 36)
![screenshot](http://i.imgur.com/K3GNWSv.jpg)

Second test is passing with an invalid test:

'You should be using the following expression /\+S/gi to find the spaces in the testString.'

This test is passing with the regex /\s/gi
/\+S/gi makes no sense - as it is searching for all matches of the literal '+' followed by a literal 'S'

**Comment by 0x0936** [comment]
In the last line, the backslash seems to have been parsed - instead of rendered. `/\+S/gi`

**Comment by 0x0936** [comment]
Ignoring the directions from testString, and instead going with the spirit of the waypoint to invert a regular expression, `/\S/gi` passes both tests, but the first test still complains "Your RegEx should have found seven spaces in the `testString`".

**Comment by bugron** [comment]
@0x0936 thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1522

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
