### ISSUE TITLE
nthChild test does not appear to work...

### ISSUE THREAD

**Issue by robwelan** [FreeCodeCamp/FreeCodeCamp#2005]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

CODE:
$(".well:nth-child(2)").addClass("animated bounce");

No nth-child works (have tried 0, 1, 2, 3). 2 visibly works, but "The second element in each of your well elements should bounce.

Visibly working (but not 'marked as correct'):
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
    $("#right-well").children().css("color", "green");
    $(".well:nth-child(2)").addClass("animated bounce");
  });
</script>

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

**Comment by n8sb** [comment]
I am experiencing this as well

**Comment by paulboardman** [comment]
This is how it works for me:

$(".well button:nth-child(2)").addClass("animated bounce");

from: [jQuery API](https://api.jquery.com/nth-child-selector/)

**Comment by paulboardman** [comment]
Or this:

$(".target:nth-child(2)").addClass("animated bounce");

**Comment by mygnu** [comment]
same code actually worked on the next challenge :)

**Comment by airyz** [comment]
I experienced the same bug, exercise need a fix.

**Comment by ngrandison** [comment]
I found that when I put a space between the class selector and :nth-child, the exercise worked. The instructions should be revised to include this space if that is the desired result. 

$(".well :nth-child(2)").addClass("animated bounce");

**Comment by benschenker** [comment]
Hey thanks for posting!

See #1927 for my explanation there (similar to what @paulboardman and @ngrandison said).  It is still open and will can remain as the main issue for this problem.  Feel free to close this as a duplicate.

Also, take a look at our [Bug Posting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help!-I've-Found-a-Bug) to see the best way to resolve a problem with the site.
