### ISSUE TITLE
can't seem to make challenge 22 work

### ISSUE THREAD

**Issue by ghost** [FreeCodeCamp/FreeCodeCamp#2007]
Challenge http://freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

i tried the `<p>..<a>..</a></p>` logic, but the website doesn't accept it as correct. 

please help.

**Comment by benschenker** [comment]
Thanks for reporting this!

The description needs to be edited to make it clearer that you need to place the new `<p>` tag around the existing `<a>` tag.

It says
```
Now nest your a element within a new p element
```
But it should be
```
Now nest your EXISTING a element within a new p element
```
