### ISSUE TITLE
Waypoint: Manipulate Arrays With Unshift - Error in Comment

### ISSUE THREAD

**Issue by ashi2014** [FreeCodeCamp/FreeCodeCamp#2008]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The comment on Line 4 says // ourArray now equals [["happy", "joy"], "Stimpson", "J"]
but should actually be // ourArray now equals [["happy", "joy"], "J", ["cat"]]

**Comment by michael-krebs** [comment]
duplicate #1829
