### ISSUE TITLE
Waypoint: Create a Bulleted Unordered List

### ISSUE THREAD

**Issue by brooks80** [FreeCodeCamp/FreeCodeCamp#2010]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by ahstro** [comment]
You have to explain what the bug is, otherwise we don't know what to fix.

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!
