### ISSUE TITLE
button "Go to my next challenge" waits 3 seconds to get activated.

### ISSUE THREAD

**Issue by IgnacioCorto** [FreeCodeCamp/FreeCodeCamp#2012]
Challenge http://freecodecamp.com/challenges/waypoint-manipulate-javascript-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Maybe this behaviour is on purpose. I believe it should have a countdown, or a "Wait a moment..." label.

**Comment by awesomeaniruddh** [comment]
Closing this because I can't replicate this. Feel free to reopen if this is still an issue for users.
