### ISSUE TITLE
Hi, I think there is a bug or a sort of catch 22 in the tutorial. We are asked to comment out the 'Lobster' font but when we do that the first two tasks change from being accomplished to being unaccomplished. If you take the comments out the last to change to being unaccomplished. There is no way to get through the task. 

### ISSUE THREAD

**Issue by michaelreinhard** [FreeCodeCamp/FreeCodeCamp#2013]
Challenge http://freecodecamp.com/challenges/waypoint-specify-how-fonts-should-degrade has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey @michaelreinhard thanks for posting.

I'm having trouble replicating this, I'll close this for now but feel free to reopen if you are still having this issue
