### ISSUE TITLE
No Steps to Move Forward

### ISSUE THREAD

**Issue by kendraforrest** [FreeCodeCamp/FreeCodeCamp#2015]
Challenge http://www.freecodecamp.com/challenges/waypoint-inherit-styles-from-the-body-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

There is no checklist of things to accomplish so after I completed each of the steps, it would not let me move forward.

**Comment by benschenker** [comment]
Hey @kendraforrest thanks for posting.

I'm having trouble replicating this, it works correctly for me.

I'll close this for now, but if it is still an issue for you please reopen
