### ISSUE TITLE
Wording is weird

### ISSUE THREAD

**Issue by drizzle00** [FreeCodeCamp/FreeCodeCamp#2016]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by saadanerdetbare** [comment]
dublicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1968

**Comment by awesomeaniruddh** [comment]
Closing this as it seems to be resolved. Why does it have `in progress` label still?
