### ISSUE TITLE
solutions for Slot Machine drills are not saved

### ISSUE THREAD

**Issue by IgnacioCorto** [FreeCodeCamp/FreeCodeCamp#2017]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-javascript-slot-machine has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey @IgnacioCorto thanks for posting!

Can you be more specific?  Where is it not saved? When you visit the page itself?

**Comment by IgnacioCorto** [comment]
After I solve the slot machine problems, the code I used is not stored. Is this the intented behaviour? Because all previous waypoints are keeping the code I type.
cc @benschenker  @BerkeleyTrue

**Comment by BerkeleyTrue** [comment]
@IgnacioCorto What browser are you using?

**Comment by IgnacioCorto** [comment]
Right now, Firefox 40 on OS X Yosemite 10.10.5

**Comment by BerkeleyTrue** [comment]
Can you take a screen cap of your localStorage? I suspect you have localStorage disabled or it is being disabled by some plugin.

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
