### ISSUE TITLE
Waypoint: Override Styles in Subsequent CSS does not pass first test BUG.

### ISSUE THREAD

**Issue by sok213** [FreeCodeCamp/FreeCodeCamp#2026]
Challenge http://www.freecodecamp.com/challenges/waypoint-override-styles-in-subsequent-css has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In this exercise, the user is instructed to apply the "blue-text" class in the h1 element along with the "pink-text" class. The result should change the text blue with both classes applied onto the h1 element, however the first test does not pass regardless of the correct code.

I have tried these codes and the result is correct, however the first test does not pass.
```
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 class="pink-text, blue-text">Hello World!</h1>
```
OR..
```
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 class="blue-text" class="pink-text">Hello World!</h1>
```

**Comment by michael-krebs** [comment]
CSS classes are separated by spaces, not commas. `class="pink-text blue-text` is the correct implementation
