### ISSUE TITLE
Waypoint: Iterate with JavaScript For Loops - easy to cheat

### ISSUE THREAD

**Issue by Stiino0** [FreeCodeCamp/FreeCodeCamp#2027]
Challenge http://www.freecodecamp.com/challenges/waypoint-iterate-with-javascript-for-loops has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The 2 assertions check for the letters "for" in the code, which is already there in the comment section and the second can be easily "faked" with just entering the values in the array itself. Does a better check exist? I used the for loop ofcourse as well but I sometimes check if I have a possiblity to "cheat" (why would anyone do this, but I still check it :) )

```
var myArray = [0,1,2,3,4];
//Push the numbers zero through four to myArray using a "for loop" like above.
```
This is code that worked for the waypoint!

**Comment by ahstro** [comment]
I don't think cheating should be too big of a worry. If someone is knowledgeable enough to figure out how to cheat the tests, they probably know what a for loop is. If not, their loss. ;)
