### ISSUE TITLE
Waypoint: Remove Classes from an element with jQuery - Typo?

### ISSUE THREAD

**Issue by n8sb** [FreeCodeCamp/FreeCodeCamp#2028]
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

"Only use jQuery to add these classes to the element."

I believe this should say "remove these classes" instead.

**Comment by benschenker** [comment]
This looks fixed already.
