### ISSUE TITLE
Code works but unable to pass

### ISSUE THREAD

**Issue by darrell1226** [FreeCodeCamp/FreeCodeCamp#2029]
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
```
    slotOne = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
    slotTwo = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
    slotThree = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
    $($('.slot')[0]).html(slotOne);
    $($('.slot')[1]).html(slotTwo);
    $($('.slot')[2]).html(slotThree);
```
This is exactly how the description says to do it. Yet I get the error: You should have used the the selector given in the description to select each slot and assign it the value of slotOne, slotTwo and slotThree respectively.

**Comment by benschenker** [comment]
Hey @darrell1226  thanks for posting this!

We have a few duplicate postings of this so see #2522 for updates on this issue.

I'll close this as a duplicate.
