### ISSUE TITLE
There should be a resource section where all sites that have been listed in challenges should be there in alphabetical order

### ISSUE THREAD

**Issue by techsin** [FreeCodeCamp/freecodecamp#203]
Regardless if the site was listed or mentioned in old course or recent. It should be there under the list with name, link, description/warnings etc. 

This will be very useful to beginners and returning users.

**Comment by BerkeleyTrue** [comment]
This might be a moot point as challenges are being removed in upcoming changes.

**Comment by QuincyLarson** [comment]
Also, it's worth pointing out that we started out with a big list of resources and people just jumped around and didn't actually finish anything. So I think this would actually harm user experience and reduce the likelihood of challenge completion.

**Comment by techsin** [comment]
well having a list of just sites shouldn't make users jump around, making list of challenges will make users jump around. Why i am asking this is because challenge was updated and site mentioned it was lost.. i had to go through git hub history from start. and finally find it after 40 mins... it's called bitballoon.com

so if there was a list it 'd be useful as a reference. YOu know how courses have all external resources listed in description...well that list would be just curated list of all those links.
