### ISSUE TITLE
Linkedin in the footer doesn't work

### ISSUE THREAD

**Issue by mangoser** [FreeCodeCamp/FreeCodeCamp#2030]
Challenge http://freecodecamp.com/ has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The Linkedin link on the footer of FCC doesn't work. When clicked, gives this error:

**404: We couldn't find path /linkedin**

**Comment by QuincyLarson** [comment]
Thanks for spotting this. I've updated it and will push the fix soon.
