### ISSUE TITLE
Test not recognizing correct answer

### ISSUE THREAD

**Issue by JanMP** [FreeCodeCamp/FreeCodeCamp#2033]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-a-negative-margin-to-an-element has an issue. I have entered the correct value of -15px but the test does not recognize it.

**Comment by dokkillo** [comment]
can you us send a screenshot of it?

**Comment by JanMP** [comment]
> Am 18.08.2015 um 10:49 schrieb Gabriel Madrid <notifications@github.com>:
> 
> can you us send a screenshot of it?
> 
> 

No, I can’t reproduce the Error. It’s working now.

**Comment by dokkillo** [comment]
thats a good new. i guess you must close the issue :+1:

**Comment by jtboing** [comment]
Here's a screenshot of the issue:
![issue](https://cloud.githubusercontent.com/assets/6265956/10397822/eed929be-6ea9-11e5-8fbf-324779f3e7a2.jpg)
