### ISSUE TITLE
Can you put the while loop challange before the for loop challenge?

### ISSUE THREAD

**Issue by snowy73** [FreeCodeCamp/FreeCodeCamp#2034]
It's just an idea: I think the while loop challenge should be before the for loop challenge. Therefore the campers can see that for loop is a shortcut of the while loop for iterating through arrays.

**Comment by awesomeaniruddh** [comment]
@FreeCodeCamp/owners any thoughts?

**Comment by BerkeleyTrue** [comment]
We'd actually like to hear other campers thoughts. Since no one else has chimed in it doesn't seem to be a huge issue for other campers.

**Comment by benmcmahon100** [comment]
The for loop is but a shortcut for a while look by meerely a different loop suited for a different task. For example

var array = [1,2,3,4,5]
while(array.length > 0) {
  console.log(array.shift());
}

That is an example of where the while loop is shorter than it's for alternative. The only real short cut way it doing it is map, filter, etc. but again those are also specialized tools for a certain task. Conversely you pretty much have to (for sanitys sake) use a for in loop for objects. There are other ways but that'd be one of the handiest. In summary I don't think swapping them is needed and really a for loop is a bit easier and less likely to go wrong in the form of an infinite loop

**Comment by awesomeaniruddh** [comment]
@FreeCodeCamp/owners So this is not happening?

**Comment by benmcmahon100** [comment]
No I don't see the need for it. I also believe that they should be recognized as distinctly different as there are cases where one would use a while instead of a for and vice versa so the order of them doesn't really matter.

**Comment by awesomeaniruddh** [comment]
I'll close the issue then. If someone else has any thoughts etc., please reopen. Thanks!
