### ISSUE TITLE
Invert Regular Expression Matches with JavaScript: A typo in the asserts?

### ISSUE THREAD

**Issue by snowy73** [FreeCodeCamp/FreeCodeCamp#2035]
Challenge http://www.freecodecamp.com/challenges/waypoint-invert-regular-expression-matches-with-javascript has an issue. 

The second assert says
>assert(editor.getValue().match(/\/\\S\/gi/gi), 'You should be using the following expression `/\+S/gi` to find the spaces in the `testString`.');

but I think the `/\+S/gi` part should be as `/\S/gi`

**Comment by souldreamer** [comment]
Fixed by #2127

**Comment by snowy73** [comment]
@souldreamer Thanks
