### ISSUE TITLE
[Bug] Data Visualization with D3: Learn About SVG in D3

### ISSUE THREAD

**Issue by ezioda004** [freeCodeCamp/freeCodeCamp#20384]
**Describe your problem and how to reproduce it:**
The following code doesn't pass the test.
```js
const svg = d3.select("body")
                  // Add your code below this line
        .append("svg")
        .style("width", w)
        .style("height", h)   
```
but the following does:
```js
const svg = d3.select("body")
                  // Add your code below this line
        .append("svg")
        .attr("width", w)
        .attr("height", h)    
```
### Why should the first snippet pass the test? 

Because `style()` and `attr()` method works the same way in case of `height` and `width`. The `style()` method has been taught in previous lesson and we shouldn't restrict the solution to just 1 way.

Although in the description of the challenge, it's explicitly mentioned to use `.attr()` method, I suppose we'll need to update this text as well.
>Give it a width attribute set to the provided w constant and a height attribute set to the provided h constant using the attr() method for each.

### Resolve:
This could be resolved by updating the text in the description and the test to something like:
```js
$("svg").attr("width") == "500" || $("svg").style("width") == "500"
```
Likewise for height.

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/data-visualization/data-visualization-with-d3/learn-about-svg-in-d3

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 70
* Operating System: Windows 10

**Comment by thecodingaviator** [comment]
` attr ` will make it ` <svg height="100px" width="100px"> ` while ` style() ` will make it ` <svg style="height: 100px; width: 100px;"> ` . See the difference?

**Comment by thecodingaviator** [comment]
@ezioda004 Mybe you can have a look at that PR, many users would be failing tests
