### ISSUE TITLE
change step 46 heroku addons:create mongolab to heroku addons:add mongolab

### ISSUE THREAD

**Issue by MitchDoogle** [FreeCodeCamp/FreeCodeCamp#2039]
Challenge http://www.freecodecamp.com/challenges/waypoint-get-set-for-basejumps has an issue. 

The create command is not used, add works though

**Comment by zeffii** [comment]
agreed: 
```
cd ~/workspace/dist && heroku config:set NODE_ENV=production && heroku addons:add mongolab
```
works.

**Comment by awesomeaniruddh** [comment]
Is there no way to *update* heroku-toolbelt instead?

```
sudo apt-get install heroku-toolbelt
```

That doesn't work for some reason.

**Comment by MichaelATang** [comment]
@awesomeaniruddh wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh
from https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3080

**Comment by BradenWhited** [comment]
Made the pull request for this as it was a really simple fix.  Should save some people some headaches.

**Comment by bugron** [comment]
Closing this issue as https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3642 is merged.
