### ISSUE TITLE
contradictory assignment

### ISSUE THREAD

**Issue by JanMP** [FreeCodeCamp/FreeCodeCamp#2046]
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-within-a-range has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

var min = 0;
var max = 12;
function myFunction() {
  // Make myFunction return a random number between zero and nine instead of a decimal
  // Only change code below this line.

should the max bei 12 or 9?

**Comment by bugron** [comment]
Nope, see third test's text and also https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1947.

**Comment by benschenker** [comment]
Hey thanks for posting an issue @JanMP 

It looks like this has been fixed in #2213.
