### ISSUE TITLE
challenges / waypoint-delete-your-jquery-functions

### ISSUE THREAD

**Issue by zeffii** [FreeCodeCamp/FreeCodeCamp#2048]
![image](https://cloud.githubusercontent.com/assets/619340/9328222/15e93d22-45a7-11e5-9174-78a817abe073.png)

`\})` I presume is a typo. it might cause confusion.

**Comment by bugron** [comment]
@zeffii thanks for posting this issue!
Closing this issue as it is fixed, see [L216](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/jquery.json#L216).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
