### ISSUE TITLE
output box = undefined

### ISSUE THREAD

**Issue by mesterum** [FreeCodeCamp/FreeCodeCamp#2049]
Challenge http://www.freecodecamp.com/challenges/waypoint-access-array-data-with-indexes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The last line in code is:
```javascript
if(typeof(myArray) !== "undefined" && typeof(data) !== "undefined"){(function(y,z){return('myArray = ' + JSON.stringify(y) + ', data = ' + JSON.stringify(z));})(myArray, data);}
```
but for output box to work should be: (`data` replaced by `myData`)
```javascript
if(typeof(myArray) !== "undefined" && typeof(myData) !== "undefined"){(function(y,z){return('myArray = ' + JSON.stringify(y) + ', myData = ' + JSON.stringify(z));})(myArray, myData);}
```

**Comment by jbmartinez** [comment]
Created PR #2074
