### ISSUE TITLE
Comment overflow in News.

### ISSUE THREAD

**Issue by gyaresu** [FreeCodeCamp/freecodecamp#205]
![comment_overflow](https://cloud.githubusercontent.com/assets/29263/6655296/2f386c7e-cab6-11e4-89ae-0651fe26a18a.png)
In Firefox 36.0.1 on OS X 10.9.5
Link: http://www.freecodecamp.com/stories/watch-people-code-interviewed-me-we-discuss-twitch-tv-agile-and-terakilobytes-energy-

**Comment by terakilobyte** [comment]
Firefox appears to be jamming the comment-list on top of the display area for the main story.

**Comment by jameskopacz** [comment]
#208
