### ISSUE TITLE
Page becomes unresponsive

### ISSUE THREAD

**Issue by 0x0936** [FreeCodeCamp/FreeCodeCamp#2052]
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When trying to write out the following code, the browser becomes unresponsive.
$($(".slot")[0]).html(slotOne);

It seems natural to start typing out `$($`. When the open paren is typed, the editor auto-completes the closing paren `$()` then when typing the second `$`, the browser stops responding: `$($)`

**Comment by gillettelevi5** [comment]
Json

**Comment by JustMD** [comment]
I have the same issue I think, but my page freeze when I type "function" on another challenge

**Comment by jbmartinez** [comment]
Duplicate of #1960
