### ISSUE TITLE
2nd assertion is wrong

### ISSUE THREAD

**Issue by mesterum** [FreeCodeCamp/FreeCodeCamp#2053]
Challenge http://www.freecodecamp.com/challenges/waypoint-sift-through-text-with-regular-expressions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I'm forced by 2nd assertion to write:
```javascript
var expression = /and+/gi;
```
which searches in testString for and or andd or anddd ... That's not the purpose of the exercise.
Also, the lesson is wrong about the regular expression: `/the+/gi`
> \+ means we want to find one or more occurrences of this pattern.

 `g` after `\`, not `+`, tells to function `match` to find all occurrences of this pattern in `testString`
If we have to find a repeating succession of 'the' word, the regular expression has to be `/(the)+/gi` at least.

**Comment by dokkillo** [comment]
I got the same problem, i wrote it in other issue, https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2095

I will close my issue and add my image here.

![screenshot from 2015-08-18 19 32 19](https://cloud.githubusercontent.com/assets/920841/9337928/68032b0a-45e2-11e5-921f-2c10814018a0.png)

**Comment by n8sb** [comment]
+1

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1997
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1938

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Comment by mesterum** [comment]
Ok
