### ISSUE TITLE
Browser Freeze

### ISSUE THREAD

**Issue by JustMD** [FreeCodeCamp/FreeCodeCamp#2054]
Challenge http://www.freecodecamp.com/challenges/bonfire-reverse-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Hi,
My browser freeze when I type in "function" on row 6 in editor,if I type it on other rows it is fine. On another computer it froze when I type "$" in diferent challenge.
![image](https://cloud.githubusercontent.com/assets/13839129/9329671/5f588f66-45bc-11e5-9089-e4470e00c1b1.png)

I tried on 2 differnt browsers (Chrome and Firefox) the result is the same

**Comment by BerkeleyTrue** [comment]
This is fixed now.

Happy Coding!
