### ISSUE TITLE
SlotMachine Select Complaining that the wrong selector is used.

### ISSUE THREAD

**Issue by whittenjaw85** [FreeCodeCamp/FreeCodeCamp#2055]
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

 // Only change code below this line.
    $($('.slot')[0]).html(slotOne);
    $($('.slot')[1]).html(slotTwo);
    $($('.slot')[2]).html(slotThree);

functions but does not report a pass

**Comment by iisupreme** [comment]
This challenge will pass if double quotes (") is used instead of single quotes (') for the selector. 
E.g. use $(".slot") instead of $('.slot'). 

Maybe a note could be placed on the challenge description to remind that double quotes be used.

**Comment by benschenker** [comment]
Hey @whittenjaw85 thanks for posting this!

We have a few duplicate postings of this so see #2522 for updates on this issue.

Please close this as a duplicate.

**Comment by whittenjaw85** [comment]
You got it. Is there a particular reason why specific styles of selectors
should be used?

"" versus ''?

On Sun, Aug 23, 2015 at 1:48 AM, Ben Schenker <notifications@github.com>
wrote:

> Hey @whittenjaw85 <https://github.com/whittenjaw85> thanks for posting
> this!
>
> We have a few duplicate postings of this so see #2522
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2522> for updates on
> this issue.
>
> Please close this as a duplicate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2055#issuecomment-133790336>
> .
>



-- 
Jonathan Whitten
Design Engineer
678.485.9450
jon.whitten@gmail.com

**Comment by benschenker** [comment]
No reason, thats why it's going to be fixed :smile:
