### ISSUE TITLE
Waypoint: Generate Random Whole Numbers Within A Range has confusing instructions

### ISSUE THREAD

**Issue by tsedlmeyer** [FreeCodeCamp/FreeCodeCamp#2057]
Challenge http://freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-within-a-range has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The instructions give formula for generating random numbers within a range. The code provides variables min and max set to 0 and 12. According to the code comments they shouldn't be changed. The comments in the code ask that myFunction should return a random number between 0 and 9. This may leave a camper confused regarding what you actually want them to do.

<img width="1201" alt="screen shot 2015-08-18 at 8 43 41 am" src="https://cloud.githubusercontent.com/assets/1650358/9330259/2fb2fbec-4586-11e5-8148-0957bb8c9857.png">

**Comment by michael-krebs** [comment]
duplicate #1992
