### ISSUE TITLE
Clicking next challenge doesn't work

### ISSUE THREAD

**Issue by SHSolomon** [FreeCodeCamp/FreeCodeCamp#2058]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
I completed this challenge, but neither clicking the button nor hitting ctrl-enter work to take me to the next challenge. If I click map then this challenge remains unchecked.

**Comment by benschenker** [comment]
Hey @SHSolomon thanks for posting,

Is this still an issue for you?  this one is hard to replicate.

**Comment by SHSolomon** [comment]
No it is not. Thank you. 

Sherry
