### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by terakilobyte** [FreeCodeCamp/freecodecamp#206]
Looking through Heroku logs we are getting **a lot** of R14 Memory errors.

**Comment by BerkeleyTrue** [comment]
An luck tracking this down?

**Comment by BerkeleyTrue** [comment]
Going to close this for now.  Hopefully this is related to error handling that is slowly being closed up..

**Comment by BerkeleyTrue** [comment]
Re opening. Just saw a memory error in the logs.

**Comment by QuincyLarson** [comment]
@terakilobyte @berkeleytrue We need to try your strong loop tool so we can isolate this. This is contingent on us spinning up a duplicate environment to play with (production shouldn't be touched!)

**Comment by terakilobyte** [comment]
The duplicate environment will take minutes to set up. I've further isolated the memory leak to revolve around the courseware, bonfire, and field-guide controllers.

**Comment by QuincyLarson** [comment]
This doesn't actually seem to be a memory leak, as it plateaus at around 800mb of ram usage. We think this is just how much ram our app needs once all our challenges are cached (hence the gradual increase up to 800mb).
