### ISSUE TITLE
Cannot proceed to next challenge

### ISSUE THREAD

**Issue by bakulcsingh** [FreeCodeCamp/FreeCodeCamp#2061]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-bootstrap-headline has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Despite following all instructions the Go to next challenge remains inactive.
![image](https://cloud.githubusercontent.com/assets/13549843/9330433/fb31481e-45d6-11e5-88d3-133f2fd20b87.png)

**Comment by DanielKerrigan** [comment]
Have you tried changing the text inside the tags from "Bakulesh" to "jQuery Playground"?

**Comment by bakulcsingh** [comment]
Nop. Let me try that and get back to you.

-----Original Message-----

**Comment by bakulcsingh** [comment]
Hey Daniel,

I have tried the text jQuery Playground. But still doesn't work.



-----Original Message-----

**Comment by DanielKerrigan** [comment]
Interesting. The following works for me: <h3 class="text-primary text-center">jQuery Playground</h3>
Do any of the requirements under the Reset, Help, Bug buttons have a red/white X next to them?

**Comment by bakulcsingh** [comment]
I tried a space after playground and it worked so the text required to
complete the challenge is "jQuery Playground ".

I guess it wasn't a bug after all but wouldn't it be better if the space
isn't required?

**Comment by benschenker** [comment]
Closing as stale.  Cannot replicate the requirement for an extra space.

Feel free to reopen if you can replicate this still
