### ISSUE TITLE
Simon Issue

### ISSUE THREAD

**Issue by VandheerMan** [FreeCodeCamp/FreeCodeCamp#2063]
Challenge http://freecodecamp.com/challenges/zipline-build-a-simon-game has an issue. It contains the video of Tic-Tac-Toe, and it shows that it's completed, although I didn't.
![1st](https://cloud.githubusercontent.com/assets/8385781/9330472/4bcc45c2-45c2-11e5-9735-9e8f13c5ca1e.jpg)
![2nd](https://cloud.githubusercontent.com/assets/8385781/9330473/4bce515a-45c2-11e5-92a2-f0f40db99a76.jpg)

**Comment by Em-Ant** [comment]
ithe same for me

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1906
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1864

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
