### ISSUE TITLE
console.log typeof

### ISSUE THREAD

**Issue by mullachv** [FreeCodeCamp/FreeCodeCamp#2064]
Challenge http://freecodecamp.com/challenges/-using-typeof has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Following give error:

console.log(typeof("") );
console.log(typeof(0) );
console.log(typeof([]) );
console.log(typeof({}) );

**Comment by benmcmahon100** [comment]
There is nothing wrong with this challenge. Since you haven't provided the error or any other info I'm going to close this issue. If you have more detail you can re-open it or create a new one.

**Comment by gillettelevi5** [comment]
Nupl

LG

benmcmahon100 <notifications@github.com> wrote:

Closed #2064.

---
Reply to this email directly or view it on GitHub:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2064#event-385355982

**Comment by benmcmahon100** [comment]
@gillettelevi5 What?

**Comment by mullachv** [comment]
Take a look at the attachments....
![console-type](https://cloud.githubusercontent.com/assets/4746033/9335677/5e082e28-45a3-11e5-899b-a7de36600250.png)

![err-typeof](https://cloud.githubusercontent.com/assets/4746033/9335666/52cca3cc-45a3-11e5-8eda-81a4c7464122.png)

**Comment by benmcmahon100** [comment]
Why are you adding the spaces? They shouldn't be there

**Comment by mullachv** [comment]
For visual clarity -
