### ISSUE TITLE
jQuery waypoints are not requiring semi colons to go to next challenge

### ISSUE THREAD

**Issue by TheHighPriestess** [FreeCodeCamp/FreeCodeCamp#2065]
I'm being allowed to go to the next challenge even though I am not entering the semi colons.

![untitled-1](https://cloud.githubusercontent.com/assets/9852102/9330588/efbf6542-45c2-11e5-82db-aa038dd52e74.jpg)

**Comment by TheHighPriestess** [comment]
Something else....

The text on the left says:

"Many HTML elements have children elements from which they inherit properties."

That's not right.  It's the children that inherit.

**Comment by awesomeaniruddh** [comment]
This is because JS doesn't mandate semi-colons. It's just good practice to put 'em. @BerkeleyTrue will have to look into this I guess.

I'll fix the description right away though.

**Comment by bugron** [comment]
I believe this is the behavior of JS interpreters. As @awesomeaniruddh mentioned it is a good practice to put a semicolon after every operator.
Closing this issue. Feel free to reopen if you still experience problems, thanks.
