### ISSUE TITLE
After server issues, much of my progress is now gone

### ISSUE THREAD

**Issue by benzod** [FreeCodeCamp/FreeCodeCamp#2066]
I was able to sign in this morning with my email, but a lot of the progress that I have made in the last month since I started is gone.  It says I'm at 93 but my progress is less on the map; it says I've only done 75% of the HTML and half the responsive course, but I just finished Regular Expressions after a 25 day streak of Javascript and jQuery.  The "Map" says I've missed several seemingly random lessons in the middle of HTML and Responsive, though I've always used the "Learn" link to get back to where I should have been.  Also, there is no "Learn" link in the menu anymore.

What is going on?  Other people have this issue in chat and have been referred here, but I don't see anyone's posts.  Is this something that's being worked on, or do I have to do something?

Thanks, FCC!

**Comment by benmcmahon100** [comment]
We have updated the curriculum so those challenges are all new. No progress has been lost. Please taje a look this https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/August-2015-Improvements

**Comment by benzod** [comment]
Ah, some of this makes a lot more sense now that I know things have been added.  However, it reports I've not done any jQuery or Javascript and like I said, I've been through them completely.  I guess I'll just pick something and go from there.
