### ISSUE TITLE
waypoint jQuery 15 allows to jump to next one without completion.

### ISSUE THREAD

**Issue by mygnu** [FreeCodeCamp/FreeCodeCamp#2068]
![screenshot from 2015-08-18 23 26 07](https://cloud.githubusercontent.com/assets/4723535/9331088/be7f8226-4600-11e5-8e1e-db6f7b1245f3.png)
Challenge http://www.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
$(".well:nth-child(2)").addClass("animated bounce"); makes the whole 'well' bounce not the second child.

**Comment by hallaathrad** [comment]
Add a space after *.well*, so it'll look through its children. 
Alternatively, try *.target:nth-child(2)* (as they advice in the instructions) which in turns looks for the second **sibling** of the wells —taking into account all *.target* are children of their respective *.well* parents.

Both options point to the same elements, but from different points of view.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2005
