### ISSUE TITLE
Feature: Board to find people to live pair with

### ISSUE THREAD

**Issue by MrRenter** [FreeCodeCamp/freecodecamp#207]
When someone is free and want to pair up to dual code they could go 'online'. They could either A)list what they were working on with 'tags' such as 'node', 'express', 'mongo', 'bonfires', etc so other people could see them or B) search/browse other people.

I feel like this would help stimulate the community and provide a catalyst for learning

**Comment by terakilobyte** [comment]
I like the idea a lot. Is this something you'd like to take on as a
project? I would also suggesting checking out camper practice projects and
seeing if anyone else is interested in collaborating.

**Comment by MrRenter** [comment]
Yes this is something I would be interested in doing

**Comment by aldraco** [comment]
@MrRenter are you still looking for help? This sounds quite interesting to me.

**Comment by MrRenter** [comment]
Working with @aldraco on this project

**Comment by terakilobyte** [comment]
Excellent. I'm closing this as an issue for you guys to track in your own repo. Looking forward to a pull request!
