### ISSUE TITLE
Json

### ISSUE THREAD

**Issue by gillettelevi5** [FreeCodeCamp/FreeCodeCamp#2071]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by AryanJ-NYC** [comment]
Please describe the bug or we will not know what to help with.

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
