### ISSUE TITLE
Creating bug reports is a bug too

### ISSUE THREAD

**Issue by mygnu** [FreeCodeCamp/FreeCodeCamp#2073]
After creating a couple of bug reports I notice that there is a lot of duplication of the same bugs/errors. I don't have a bug report but a suggestion that clicking on a bug button in one particular challenge should list all the previous bugs filed here at github, so people can see if this has already been filed or not. github api someone?? I'm new to web-dev but if someone can point me the direction I can try myself to look into this. 

if someone has already filed this bug, you get the point.

**Comment by jbmartinez** [comment]
:+1:

**Comment by jbmartinez** [comment]
Perhaps a wiki page could be useful meanwhile. I could write it this afternoon, but my English is awful

**Comment by BerkeleyTrue** [comment]
wiki entry created https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug

We discussed sending people to something other then a new issue, but we don't want to discourage people from filing issue's. The best bet is to create a few challenges that involve people reading the wiki on searching and filing issue's.

Closing this for now. We will revisit in the future.
