### ISSUE TITLE
Validation of comment being closed doesn't work

### ISSUE THREAD

**Issue by eiselems** [FreeCodeCamp/FreeCodeCamp#2075]
Challenge http://freecodecamp.com/challenges/waypoint-use-comments-to-clarify-code has an issue. 

![image](https://cloud.githubusercontent.com/assets/5188694/9332126/7ba37f94-45c3-11e5-8fac-5aa324fa60d5.png)

See screenshot

**Comment by dokkillo** [comment]
I am not sure if it is an issue, because in the line 23 it have a close comment, but maybe the issue is it, that close comment not must be here.

**Comment by benschenker** [comment]
Closing as stale, please reopen if this is still an issue for you
