### ISSUE TITLE
Parents do not inherit properties from children

### ISSUE THREAD

**Issue by jack-acid** [FreeCodeCamp/FreeCodeCamp#2076]
Challenge http://freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I believe the text "Many HTML elements have children elements from which they inherit properties" is incorrect. Many HTML elements have children elements to which they bequeath properties.

**Comment by bugron** [comment]
Already fixed: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2238.
