### ISSUE TITLE
Slash-start-start-slash multiple line issue

### ISSUE THREAD

**Issue by maxiedk** [FreeCodeCamp/FreeCodeCamp#2077]
In order to pass the test for this waypoint, the comment for the slash-start-start-slash type of commenting has to be on the same line as the first slash-star, otherwise it doesn't work.
![salsh-star](https://cloud.githubusercontent.com/assets/5831309/9332352/22615746-45bc-11e5-83c9-e7932b882df6.png)
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1999
