### ISSUE TITLE
Bad links

### ISSUE THREAD

**Issue by bordeltabernacle** [FreeCodeCamp/FreeCodeCamp#2078]
Challenge http://www.freecodecamp.com/challenges/waypoint-make-images-mobile-responsive` has an issue. Once completed, clicking `Go to my next challenge` takes you to http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-push rather than the next challenge.

**Comment by bordeltabernacle** [comment]
Also happens here:
http://www.freecodecamp.com/challenges/waypoint-center-text-with-bootstrap

**Comment by benschenker** [comment]
Hey, @bordeltabernacle are you still having this issue?

**Comment by BerkeleyTrue** [comment]
Closing as duplicate  #1778

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
