### ISSUE TITLE
if NaN is in an array it passes. 

### ISSUE THREAD

**Issue by raintan** [FreeCodeCamp/FreeCodeCamp#2079]
Challenge http://www.freecodecamp.com/challenges/bonfire-falsey-bouncer has an issue. 

I submitted this code:
```javascript
function bouncer(arr) {
   var newArr = [];
   for (i=0;i<arr.length;i++){
     if (arr[i] !== false && arr[i] !== 0 && arr[i] !== "" && arr[i] !== undefined && arr[i] !== null ) {
      newArr.push(arr[i]);
    }
   }
    return newArr;
}
```

Which passes, but if I call bouncer([NaN]); this function will return [NaN], which should fail the test according to the instructions

**Comment by awesomeaniruddh** [comment]
Closing as a recent PR by @abhisekp fixed this.

PR link: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3124
