### ISSUE TITLE
Free Code Camp Bonfire Challenge (Confirm the ending) issue

### ISSUE THREAD

**Issue by WebDevDani** [FreeCodeCamp/FreeCodeCamp#2080]
Challenge http://www.freecodecamp.com/challenges/bonfire-confirm-the-ending has an issue. It has a glitch. It accepts as a good solution this code:

function end(str, target) {
  
  var endLetter = str.substr(- 1);
  var endTarget = target.substr(-1);
  
if (endLetter === endTarget) {
  return true;
  } else {
  return false; 
};
}

But this code only analyze if the last letter of the string is equal the last letter of the target string.
So it would accept something like this also:
end('He has to give me a new name', 'fdsfsdfsefsfe');

Image:

![freecodecampbug](https://cloud.githubusercontent.com/assets/13763460/9332861/0d36e0a6-45c7-11e5-8522-be27c98aeae4.png)

**Comment by benschenker** [comment]
Thanks @WebDevDani good catch here.

The 3rd test is supposed to catch this case but has an extra period in it's first argument:
First arg
```
'Walking on water and developing software from a specification are easy if both are frozen.'
```
2nd
```
'specification'
```

If the period is removed then this test which is supposed to be false, will return true for the code above.
