### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by NigelDawson** [FreeCodeCamp/FreeCodeCamp#2081]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

the waypoint asks you to add the following script "  $(document).ready(function() { });"

The 4th test Close your $(document).ready(function() { function with }); will not pass unless the closing }); is on a separate line.  I know this is a java style thing but it was painful to find given I had done as asked and my script was closed correctly.

![image](https://cloud.githubusercontent.com/assets/13345461/9333141/81b2928a-45c8-11e5-943a-ccc30692e5dd.png)

![image](https://cloud.githubusercontent.com/assets/13345461/9333156/991af084-45c8-11e5-8e07-d8567c5a1e50.png)

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1953
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1858

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
