### ISSUE TITLE
Test Bugs

### ISSUE THREAD

**Issue by NigelDawson** [FreeCodeCamp/FreeCodeCamp#2083]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The 5th test won't pass.  Everything has been done as requested but it won't pass.

![image](https://cloud.githubusercontent.com/assets/13345461/9334282/5594e238-45ce-11e5-97f1-6dd54699561f.png)

**Comment by benmcmahon100** [comment]
You are missing quotes around btn-primary. This is not an issue, Please check this kind of stuff in the help chat first.

**Comment by NigelDawson** [comment]
thanks, sorry :(

**Comment by benmcmahon100** [comment]
No problem! Thanks for being pro-active to report issues!
