### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by haldav** [FreeCodeCamp/FreeCodeCamp#2086]
Challenge http://freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I believe there is a typo in the first paragraph of the tutorial:

"It's great that we can create random decimal numbers, but it's even more useful if we lot more useful to generate a random whole number."

**Comment by issyl0** [comment]
Thanks for reporting this! It's been fixed in https://github.com/FreeCodeCamp/FreeCodeCamp/commit/87c01aae522404a8c9879cd08357a5afc148be0c. :+1:
