### ISSUE TITLE
Example should have a space

### ISSUE THREAD

**Issue by LeanMC** [FreeCodeCamp/FreeCodeCamp#2088]
The help text at http://freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery gives an example that says:

`$(".target:nth-child(3)").addClass("animated bounce");`

This should say

`$(".target :nth-child(3)").addClass("animated bounce");`

per :nth-child's syntax.

**Comment by michael-krebs** [comment]
duplicate #1927
