### ISSUE TITLE
Wrong waypoints order in a challenge

### ISSUE THREAD

**Issue by cyberxndr** [FreeCodeCamp/FreeCodeCamp#2089]
Challenge http://freecodecamp.com/challenges/waypoint-manipulate-arrays-with-push has an issue. How to reproduce a bug:
1)Finish http://freecodecamp.com/challenges/waypoint-make-images-mobile-responsive waypoint.
2)press ctrl+enter
3)get waypoint that not belongs to the bootstrap part.

**Comment by benschenker** [comment]
I'm unable to replicate this, closing but feel free to reopen if you still experience this problem
