### ISSUE TITLE
waypoint-manipulate-javascript-objects bad example in code section

### ISSUE THREAD

**Issue by deadwishd** [FreeCodeCamp/FreeCodeCamp#2090]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-javascript-objects has an issue.

// ourDog.bark("arf!");
![www freecodecamp com](https://cloud.githubusercontent.com/assets/5685082/9335501/a9b066a2-45d4-11e5-83b7-40174520eef7.jpg)

needs to be
// ourDog.bark = "arf!";
![www freecodecamp com](https://cloud.githubusercontent.com/assets/5685082/9335515/b6a17cd4-45d4-11e5-9d41-79a0ddb19a88.jpg)

**Comment by happyjunki3** [comment]
Thank you for posting the fix! I got stuck on this

**Comment by BerkeleyTrue** [comment]
Fix is going live shortly


Happy Coding!
