### ISSUE TITLE
Wording error in instructions.

### ISSUE THREAD

**Issue by Enrique-Ruiz** [FreeCodeCamp/FreeCodeCamp#2091]
Challenge http://freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In the first paragraph of the instructions there is this grammatical error: "... but it's even more useful if we lot more useful to generate a random whole number."  I figured you may want to fix it for clarity.

Thanks!
Enrique

**Comment by issyl0** [comment]
Thanks for reporting this! It's been fixed in https://github.com/FreeCodeCamp/FreeCodeCamp/commit/87c01aae522404a8c9879cd08357a5afc148be0c. :+1:
