### ISSUE TITLE
Maybe not a bug....but

### ISSUE THREAD

**Issue by zildjianavedis** [FreeCodeCamp/FreeCodeCamp#2092]
Not really a bug, but more of a minor issue. 
I am no coder by any means (just starting this, so it might be this way by default) but when doing the beginning waypoints, i've noticed that the challenge will be marked as complete before i add the end ">".  I'm not sure if this is how the CSS really works or not, but if its not, I thought it might cause some to forget to add the end character to close a line if they dont do it routinely. 
Challenge http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
I'm having trouble replicating this, it may have been fixed.  Closing for now but reopen if this is still an issue for you
