### ISSUE TITLE
Incorrect attribute name in instructions

### ISSUE THREAD

**Issue by bapinney** [FreeCodeCamp/FreeCodeCamp#2093]
Challenge http://www.freecodecamp.com/challenges/waypoint-declare-javascript-objects-as-variables has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The instructions for this Waypoint ask the user to create a "wheels", "engine", and "seats" attribute for the motorBike object.  However, when you do that, the submission gets flagged as incorrect.  This is because it is looking for "engines" and not "engine" (as mentioned in the instructions).

![fcc js waypoint](https://cloud.githubusercontent.com/assets/11950942/9336570/24f39172-458f-11e5-8743-e3bb5bafea8b.png)

**Comment by benschenker** [comment]
Looks like this has been fixed, thanks!
