### ISSUE TITLE
Incorrect attribute name in instructions

### ISSUE THREAD

**Issue by bapinney** [FreeCodeCamp/FreeCodeCamp#2094]
Challenge http://www.freecodecamp.com/challenges/waypoint-construct-javascript-objects-with-functions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This is very similar to the bug I filed just a few minutes ago.  The instructions tell the user to use "engine" as the name for one of the attributes.  However, when you do that, your submission is flagged as incorrect.

![fcc wp js objs w fun](https://cloud.githubusercontent.com/assets/11950942/9336786/4d421850-4590-11e5-99d9-21908527e30d.png)

**Comment by benschenker** [comment]
Closing as fixed/duplicate
