### ISSUE TITLE
"Add Images to Your Website" link

### ISSUE THREAD

**Issue by bynumjj** [FreeCodeCamp/FreeCodeCamp#2096]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This Waypoint links to "Manipulate Arrays With Push" after completion.  Should link to "Size Your Images."

**Comment by benschenker** [comment]
Works correctly for me, it may have been fixed.  Reopen if you notice this issue again
