### ISSUE TITLE
Popup not coming on successful submission

### ISSUE THREAD

**Issue by syedsuhail** [FreeCodeCamp/FreeCodeCamp#2097]
Challenge http://freecodecamp.com/challenges/waypoint-understand-boolean-values has an issue. 

After I change the code and run it, the popup to take me to the next challenge is not coming even thought the tests pass and give correct result. I faced the same issue in other challenges. Sometimes in other challenges the popup might come but on clicking the button to the next challenge it does not move to the next challenge. 

Hope you can fix this.Thank you.

**Comment by benschenker** [comment]
Hey @syedsuhail is this still an issue for you? Even when you do a [hard refresh](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache) or open it incognito mode?

**Comment by syedsuhail** [comment]
@benschenker  After facing the popup problem I started using ctrl+enter to move to the next challenge . That worked all the time. I tried out a few challenges now and it seems to work.
