### ISSUE TITLE
Alt text waypoint allowed incorrect solution

### ISSUE THREAD

**Issue by bwyan** [FreeCodeCamp/FreeCodeCamp#2098]
Challenge http://freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements has an issue.

The green "go to my next challenge" button accepted my solution before I was finished typing it. I hadn't closed the quotes on my alt attribute when the button animated, indicating my solution was correct (even though it wasn't).

**Comment by benschenker** [comment]
This seems to be fixed
