### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by ulmas** [FreeCodeCamp/FreeCodeCamp#2099]
Challenge http://www.freecodecamp.com/challenges/waypoint-override-all-other-styles-by-using-important has an issue.

When editing the style, do not include ";" after !important, and the checklist will change "Your pink-text class should have the !important keyword to override all other declarations." to "Cannot read property 'length' of null"

Adding the ";" changes the checklist back.

Screenshot: http://screencast.com/t/TNalhp6su

**Comment by dokkillo** [comment]
working with this issue
