### ISSUE TITLE
Bonfire solutions of individuals show up on google search

### ISSUE THREAD

**Issue by osazemeu** [FreeCodeCamp/FreeCodeCamp#2101]
I noticed with a simple google search, bonfire solutions of everyone in freecodecamp shows up on google. Is this deliberate?

![freecodecamp](https://cloud.githubusercontent.com/assets/7466259/9338286/e7eefecc-45db-11e5-8427-33dd2a7fc9cc.JPG)

**Comment by benschenker** [comment]
Hey @osazemeu I believe this is on purpose, see https://github.com/FreeCodeCamp/freecodecamp/issues/356#issuecomment-96308878
