### ISSUE TITLE
Directed to incorrect lesson

### ISSUE THREAD

**Issue by zahn0311** [FreeCodeCamp/FreeCodeCamp#2102]
Challenge http://www.freecodecamp.com/challenges/waypoint-make-images-mobile-responsive has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When I complete "Waypoint: Make Images Mobile Responsive" the "Go to my next challenge" button takes me to "Waypoint: Manipulate Arrays With push".

![image](https://cloud.githubusercontent.com/assets/13563493/9338420/489a6914-45aa-11e5-94ec-765a054cd2ea.png)

![image](https://cloud.githubusercontent.com/assets/13563493/9338455/6b415d9c-45aa-11e5-99b0-f32173f68f79.png)

**Comment by benschenker** [comment]
Hey I'm having trouble replicating this.  I'll close it for now but if this is still a problem for you then reopen it
