### ISSUE TITLE
Wrong implementation is marked as correct

### ISSUE THREAD

**Issue by ulmas** [FreeCodeCamp/FreeCodeCamp#2103]
Challenge: http://www.freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers.

The task asks to next all of the HTML code in a <div>. However, simply adding and closing a <div> on top of the page marks the tasks as complete: http://screencast.com/t/ao2m2m8Vncx

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1983

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
