### ISSUE TITLE
Camper News comments should be editable by their author for at least some duration of time

### ISSUE THREAD

**Issue by CodeNonprofit** [FreeCodeCamp/freecodecamp#211]

**Comment by MrRenter** [comment]
Is this still a wanted feature if so I will write it up. @CodeNonProfit @QuincyLarson

**Comment by BerkeleyTrue** [comment]
This would also require adding the ability to search through own stories which is currently a feature not implemented.

**Comment by terakilobyte** [comment]
All the information required to allow editing the post is currently
presented in the view, I'm failing to see why searching through own stories
is required for this.

**Comment by BerkeleyTrue** [comment]
I tried to find a past story I posted and could not. While I can just do a ctrl + f 'berkeleytrue' to find my posted stories, imagine camper news has over a thousand stories? What if my story gets buried right away and I want to edit it?

As a camper, I want to hit a link to take me to all the stories that I have posted. Here I would like to edit my stories.

Granted I rarely go to hacker news so this might be functionality that is not required. It might be the case that if a story falls off we might not want to store and/or track it. In this case stories should be editable as long as they are still visible and my previous statement is moot.

**Comment by MrRenter** [comment]
We could just make it so the post id and the logged in author are passed
through and use them for an Ajax call. All secured up of course

**Comment by terakilobyte** [comment]
I'm not a fan of indefinite editing. At some point the message should be made permanent. I think any more than 10 minutes is plenty of time, personally.

**Comment by BerkeleyTrue** [comment]
Cool, @MrRenter you want to give this a go?

**Comment by MrRenter** [comment]
Yea. I'll get it done.

**Comment by BerkeleyTrue** [comment]
sweet.

**Comment by QuincyLarson** [comment]
Hi MrRenter can you give us a quick status update on this? I think if the comments are editable that is sufficient, as they can leave blank comments and we can just put <comment has been deleted> in the even to an empty comment.
We don't want to have to worry about handling subsequent comments.

**Comment by QuincyLarson** [comment]
@mrrenter any progress on this?

**Comment by aldraco** [comment]
@QuincyLarson there is a pull request in the hopper for it. #299

**Comment by QuincyLarson** [comment]
Awesome! I'll take a look when I come up for air :)


- Quincy Larson
"Anyone who has begun to think, places some portion of the world in
jeopardy." - John Dewey

**Comment by aldraco** [comment]
sorry, i actually misspoke. :( I thought this was a different issue as it came up in my feed. my bad.

**Comment by QuincyLarson** [comment]
No worries. This should be easy enough to fix on my own if need be.


- Quincy Larson
"Anyone who has begun to think, places some portion of the world in
jeopardy." - John Dewey

**Comment by QuincyLarson** [comment]
@mrrenter I think the fix would be simple: Campers should be able to edit their comments forever. Instead of being able to delete their comments, they should be able to simply blank them out.

**Comment by MrRenter** [comment]
Sorry this got put on the back burner but here is a working elegant solution to the issue #328
