### ISSUE TITLE
Typo in Waypoint: Nest one Array within Another Array

### ISSUE THREAD

**Issue by EncRyptEd77** [FreeCodeCamp/FreeCodeCamp#2110]
Challenge http://www.freecodecamp.com/challenges/waypoint-nest-one-array-within-another-array has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Typo in the comment line, should read as "Only change code above this line"
// Only change code below this line.

**Comment by benschenker** [comment]
Hey @EncRyptEd77 thanks for posting!

This loks fixed to me, closing
