### ISSUE TITLE
"Give your JavaScript Slot Machine some stylish images" - passing when it should not

### ISSUE THREAD

**Issue by ArgonCode** [FreeCodeCamp/FreeCodeCamp#2111]
The tests are not covering the task fully. One can pass it by updating only slot 0 three times:
![slot_zero_three](https://cloud.githubusercontent.com/assets/5458077/9340230/6d98125e-45a3-11e5-990d-11f572af3cd5.png)

**Comment by benschenker** [comment]
Hey @ArgonCode good catch!

Specifically 
```
    $($('.slot')[0]).html('<img src = "' + images[slotOne-1] + '">');
    $($('.slot')[0]).html('<img src = "' + images[slotTwo-1] + '">');
    $($('.slot')[0]).html('<img src = "' + images[slotThree-1] + '">');
```
passes when it should fail.

**Comment by ASidlinskiy** [comment]
Has anyone confirmed that the issue above was resolved ? This exercise still passes with the wrong value pointed out above. I personally don't think ticket should've been closed unless it was pushed to production with a valid bug fix.

**Comment by awesomeaniruddh** [comment]
@ASidlinskiy The issue has been resolved.
