### ISSUE TITLE
Waypoint: Add your JavaScript Slot Machine Slots: Completion Bug

### ISSUE THREAD

**Issue by Dephora** [FreeCodeCamp/FreeCodeCamp#2114]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-your-javascript-slot-machine-slots has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

If you place the cursor in the area to enter code and hit enter (without typing anything) - the lesson will mark as complete.

**Comment by benschenker** [comment]
Thanks for posting @Dephora 

It seems this has been fixed.
