### ISSUE TITLE
Waypoint: Use Comments to Clarify Code Q31- Bug: automatically comments all of the code

### ISSUE THREAD

**Issue by ItsAllMental** [FreeCodeCamp/FreeCodeCamp#2115]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-comments-to-clarify-code has an issue. 

When following the directions all of the code gets commented automatically.
1. go to the top of the line and create a space for entering the comment
2. In the new space, start typing in  then go back to the top and paste in the comment.  (I don't believe this is what was intended to happen).

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2075

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
