### ISSUE TITLE
Popup Dialog is missing textboxes for codepen link 

### ISSUE THREAD

**Issue by NigelDawson** [FreeCodeCamp/FreeCodeCamp#2116]
Challenge http://www.freecodecamp.com/challenges/waypoint-get-set-for-ziplines has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

EDIT: 19/08  Actually this probably is more useablity than a bug as it's an inconsistency between what is presented in the video and what you are required to do.  After looking ahead to the other ziplines their check lists on the left do mention that you are required to paste your codepen link..  You might consider adding a check item to the list for the first waypoint stating that even though it's mentioned in the video you don't need to link to the codepen.

Browser: Chrome Version 44.0.2403.155 m  (latest)
OS: Win7

issue 1
I've completed this challenge but when I click the <I've Completed this challenge (ctrl + enter)> button the resulting popup does not have the test field mentioned in the video.

issue 2
button doesn't respond to CTRL + Enter.  Has worked for previous challenges.

I get this
![image](https://cloud.githubusercontent.com/assets/13345461/9340968/5c5c2142-45f3-11e5-926c-dd5214c14ed0.png)

it is supposed to be this (courtesy of FCC user itsaga)
![image](https://cloud.githubusercontent.com/assets/13345461/9340993/7e33d526-45f3-11e5-8add-7a37d8919971.png)

**Comment by eabedrapo** [comment]
+1!

**Comment by benschenker** [comment]
This has been fixed, see #2199
