### ISSUE TITLE
Misspelled directory name. 

### ISSUE THREAD

**Issue by tjsullivan1** [freeCodeCamp/freeCodeCamp#21176]
**Describe your problem and how to reproduce it:**
The directory below is meant to say 'create-file-with-specific-size'. Specific is misspelled as 'sepcific'.

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/tree/master/guide/english/linux/create-file-with-sepcific-size

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by leoking-crey** [comment]
i am taking this issue

**Comment by charubansal12** [comment]
I can take this up
