### ISSUE TITLE
Second cat picture doesn't get counted

### ISSUE THREAD

**Issue by mihhix** [FreeCodeCamp/FreeCodeCamp#2118]
Challenge http://www.freecodecamp.com/challenges/waypoint-make-images-mobile-responsive has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Code in the code window: 
```
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
  
  <a href="#"><img class="smaller-image thick-green-border img-responsive" src="https://bit.ly/fcc-running-cats"></a>

  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>
```

OS: OS X, Browser: Chrome (last version)

Screenshot: https://www.dropbox.com/s/qr01n2swfc7y2tv/Screenshot%202015-08-18%2023.16.58.png?dl=0

**Comment by dokkillo** [comment]
Hi, the problem here is : the user add https://bit.ly/fcc-running-cats and not  http://bit.ly/fcc-running-cats.  He did it because he copied the other image that have https.

I will remove the https of the other image and change it for http

regards

**Comment by benschenker** [comment]
Looks like this is fixed, thanks!

**Comment by zdunda** [comment]
Hi,

if I got order images like this, the challenge won't validate:
<img class="smaller-image thick-green-border img-responsive" src="http://bit.ly/fcc-relaxing-cat">
<img class="img-responsive" src="http://bit.ly/fcc-running-cats">
  
if I change the images order to have the second picture first, then the validation passes:
<img class="img-responsive" src="http://bit.ly/fcc-running-cats">
<img class="smaller-image thick-green-border img-responsive" src="http://bit.ly/fcc-relaxing-cat">
