### ISSUE TITLE
Not recognizing both class color styles

### ISSUE THREAD

**Issue by bynumjj** [FreeCodeCamp/FreeCodeCamp#2119]
Challenge http://www.freecodecamp.com/challenges/waypoint-override-styles-in-subsequent-css has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The evaluator only recognizes the class that comes first in `<h1>`.  e.g. with `<h1 class="blue-text"  class="pink-text">`, it will respond that h1 needs pink text, and vice versa.  Also, the help button doesn't link.

![screen shot 2015-08-18 at 1 36 47 pm](https://cloud.githubusercontent.com/assets/13441998/9342070/a7cfc998-45ae-11e5-9265-0ddc28ba91a8.png)

**Comment by michael-krebs** [comment]
Your class declarations are incorrect. The correct code is `class="blue-text pink-text"`, please ask for help in the chat before submitting an issue

**Comment by saadanerdetbare** [comment]
It is the first time campers are asked to apply multiple classes to a HTML element and maybe it should be considered to give a hint as to how. There has been many questions in the chat about this challenge

**Comment by michael-krebs** [comment]
@saadanerdetbare Yes, you're correct, there's no indication as to what the correct syntax is. I've seen lots of commas and more than one `class=`per element.

**Comment by saadanerdetbare** [comment]
What do you think of adding this to the seed:

```
Applying multiple class attributes to a HTML element is done with a space between them like this: <code>class=\"class1 class2\"<\code>
```
