### ISSUE TITLE
Bug with email login

### ISSUE THREAD

**Issue by MrRenter** [FreeCodeCamp/freecodecamp#212]
Creating a new account via email you can enter an email such as mrrenter@fake 

This should be checked for a .com/org/etc

Also once this account is created it is bricked as well. If you log out of it you cannot log back in because the server says its not a valid email address. There is still an entry in the table

Solution: Update the regex used for email validation

**Comment by terakilobyte** [comment]
The decision was made to allow this behavior if a user so desired. Unless
Quincy wants to enforce valid emails (through confirmation, not regex imo)
I'm going to close this.

**Comment by MrRenter** [comment]
If the user uses this type of email though they will not be able to log back in. This will just fill the database with unusable accounts. If this an accepted format I suggest changing the login to accept this format as well

**Comment by QuincyLarson** [comment]
Ideally we should verify that it conforms to a legal email address pattern. I can't remember why we didn't do this originally (I'm sure we discussed it). I think Angular validation didn't allow for it.

**Comment by jameskopacz** [comment]
The sign up form checks /api/checkUniqueEmail/[email] to see that the email is unique. If the client side validation doesn't work couldn't we use checkUniqueEmail to validate the email server side?

**Comment by QuincyLarson** [comment]
I've fixed this. It will now send the user back to the form with a flash notification upon submission of an invalid email. I tested it and it will accept good emails.
