### ISSUE TITLE
d[0].toLowerCase is not a function

### ISSUE THREAD

**Issue by thebau5** [FreeCodeCamp/FreeCodeCamp#2120]
Challenge http://freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

within the challenge type in "myArray.unshift(["paul"])
![image](https://cloud.githubusercontent.com/assets/7886312/9342259/4dbfb0c8-45c0-11e5-83ac-7ae7be7767c4.png)
no matter what I do I keep getting the error "d[0].toLowerCase is not a function"

**Comment by saadanerdetbare** [comment]
The correct code for the challenge is
```
myArray.unshift("paul");
```
The challenge works as expected
