### ISSUE TITLE
"Data Structures: Perform a Subset Check on Two Sets of Data" passes with no coding whatsoever.

### ISSUE THREAD

**Issue by prosdkr** [freeCodeCamp/freeCodeCamp#21200]
**Describe your problem and how to reproduce it:**
Load up the "Data Structures: Perform a Subset Check on Two Sets of Data" challenge. Write NO code whatsoever. Reset the challenge if necessary to return to normal state.
The challenge will pass and be complete incorrectly.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/coding-interview-prep/data-structures/create-and-add-to-sets-in-es6

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 69.0.3497.100
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![bug](https://user-images.githubusercontent.com/16836749/47192922-cb193180-d315-11e8-946c-c74899689201.png)

**Comment by ezioda004** [comment]
Ah, seems like it's already reported https://github.com/freeCodeCamp/freeCodeCamp/issues/17856
Thanks for opening the issue. I'll close this since we're already tracking it.
