### ISSUE TITLE
Error seems to be in error

### ISSUE THREAD

**Issue by jmichb** [FreeCodeCamp/FreeCodeCamp#2128]
Challenge http://www.freecodecamp.com/challenges/waypoint-make-instances-of-objects-with-a-constructor-function has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

To reproduce it, run the correct code. Then you'll see that the error reported seems to be, well, in error:

assert(typeof(myCar.engines) === 'number', 'The property engine of myCar should be a number');The property engine of myCar should be a number

See the screenshot.

![screen shot 2015-08-18 at 6 36 33 pm](https://cloud.githubusercontent.com/assets/12019331/9344636/15bd19f0-45d8-11e5-8e10-1d3d63abdaa8.png)

**Comment by AryanJ-NYC** [comment]
engines, not engine. You used engine in your code.
