### ISSUE TITLE
User password hash in Stories

### ISSUE THREAD

**Issue by jameskopacz** [FreeCodeCamp/freecodecamp#213]
The Stories area is including the user object on the page which is including the password hash:

From stories/hot:
```javascript
<script>var challengeName = 'Camper News';
var user = {"_id":"5503ec8f58775dd01f72d4ce","email":"test@test.test","password":"$2a$05$GIGwNCnDHF5s5OeWTl2Zje4n6ZpicWkEWgTyWh7rF060gbFIMLaDS","__v":2,"completedCoursewares":[],"uncompletedCoursewares":[],"completedBonfires":[{"solution":"function meetBonfire(argument) {\n  // Good luck!\n  console.log(\"you can read this function's argument in the developer tools\", argument);\n\n  return true;\n}\n\n\n\nmeetBonfire(\"You can do this!\");","completedDate":1426320538,"completedWith":null,"_id":"ad7123c8c441eddfaeb5bdef"}],"uncompletedBonfires":["a202eed8fc186c8434cb6d61","a302f7aae1aa3152a5b413bc","aaa48de84e1ecc7c742e1124","a26cbbe9ad8655a977e1ceb5","ab6137d4e35944e21037b769","a789b3483989747d63b0e427","acda2fb1324d9b0fa741e6b5","afcc8d540bea9ea2669306b6","ac6993d51946422351508a41","a9bd25c716030ec90084d8a1","ab31c21b530c0dafa9e241ee","af2170cad53daa0770fabdea","adf08ec01beb4f99fc7a68f2","a8e512fbe388ac2f9198f0fa","a39963a4c10bc8b4d4f06d7e","a24c1a4622e3c05097f71d67","a3566b1109230028080c9345","a5de63ebea8dbee56860f4f2","af7588ade1100bde429baf20","a77dbc43c33f39daa4429b4f","a105e963526e7de52b219be9","a6b0bb188d873cb2c8729495","a103376db3ba46b2d50db289","a5229172f011153519423690","a3bfc1673c0526e06d3ac698","ae9defd7acaf69703ab432ea","a6e40f1041b06c996f7b2406","a5deed1811a43193f9f1c841","ab306dbdcc907c7ddfc30830","a8d97bd4c764e91f9d2bda01","a3f503de51cfab748ff001aa","a3f503de51cf954ede28891d","a10d2431ad0c6a099a4b8b52","a2f1d72d9b908d0bd72bb9f6","af4afb223120f7348cdfc9fd","aff0395860f5d3034dc0bfc9","aa2e6f85cab2ab736c9a9b24","a56138aff60341a09ed6c480","a7bf700cd123b9a54eef01d5"],"portfolio":{"website3Image":"","website3Title":"","website3Link":"","website2Image":"","website2Title":"","website2Link":"","website1Image":"","website1Title":"","website1Link":""},"profile":{"username":"hello123","twitterHandle":"","codepenProfile":"","coderbyteProfile":"","githubProfile":"","linkedinProfile":"","picture":"https://s3.amazonaws.com/freecodecamp/camper-image-placeholder.png","location":"","gender":"","name":""},"challengesHash":{"0":1426320545,"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0,"16":0,"17":0,"18":0,"19":0,"20":0,"21":0,"22":0,"23":0,"24":0,"25":0,"26":0,"27":0,"28":0,"29":0,"30":0,"31":0,"32":0,"33":0,"34":0,"35":0,"36":0,"37":0,"38":0,"39":0,"40":0,"41":0,"42":0,"43":0,"44":0,"45":0,"46":0,"47":0,"48":0,"49":0,"50":0,"51":0,"52":0,"53":0,"54":0,"55":0,"56":0,"57":0,"58":0,"59":0},"challengesCompleted":[{"0":1426320545,"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0,"16":0,"17":0,"18":0,"19":0,"20":0,"21":0,"22":0,"23":0,"24":0,"25":0,"26":0,"27":0,"28":0,"29":0,"30":0,"31":0,"32":0,"33":0,"34":0,"35":0,"36":0,"37":0,"38":0,"39":0,"40":0,"41":0,"42":0,"43":0,"44":0,"45":0,"46":0,"47":0,"48":0,"49":0,"50":0,"51":0,"52":0,"53":0,"54":0,"55":0,"56":0,"57":0,"58":0,"59":0}],"points":2,"tokens":[]};
var page = "hot";</script>
```

**Comment by MrRenter** [comment]
Just to add information this is happening at line 151 in controllers/story.js

**Comment by terakilobyte** [comment]
I don't see a huge issue with showing the user their own password hash, but I may be naive on this. We're using the same encryption scheme used widely elsewhere. The salt is in the source code, as well as the encryption algorithm.

**Comment by BerkeleyTrue** [comment]
We need a security expert here.  I don't think removing the password field before rendering will hurt anything.

**Comment by MrRenter** [comment]
http://goodmath.scientopia.org/2013/03/02/passwords-hashing-and-salt/

The only issue would possibly be if the user is able to recover another persons hash

**Comment by QuincyLarson** [comment]
It sounds like removing the password from the object before it's passed to the client will remove any chance of this of this happening.  This would be an inexpensive operation.

**Comment by BerkeleyTrue** [comment]
yes. SHould be as easy as delete `user.password` right before res.render. Anyone want to submit a PR?

**Comment by jameskopacz** [comment]
I'm not sure how to do this. The user variable is being set on all story pages. It's in the index and show template files (not sure why both).

Is there a onbefore or something similar that can be called once to clean req.user before render? Or would I have to put the cleanup code in every render call?

**Comment by BerkeleyTrue** [comment]
@jameskopacz  This is the only relevant one I see in stories. https://github.com/FreeCodeCamp/freecodecamp/blob/552af9ede8cebd9921e9dbaedd96c08bca2d01b5/controllers/story.js#L132

**Comment by jameskopacz** [comment]
If you remove that line, the user var is still written. It's like 'user' is global?

(did a search after writing that last line) It is! https://github.com/FreeCodeCamp/freecodecamp/blob/552af9ede8cebd9921e9dbaedd96c08bca2d01b5/app.js#L197

Also looks like the 'var user' can be removed from show.jade since index sets the var and is the only thing including show.jade.

**Comment by QuincyLarson** [comment]
I'm like 90% there on this but it doesn't seem to be actually work. Do you
have 5 mins to help me fix it? I'll be back on in 45 mins.

On Tuesday, March 17, 2015, Berkeley Martinez <notifications@github.com>
wrote:

> yes. SHould be as easy as delete user.password right before res.render.
> Anyone want to submit a PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/freecodecamp/issues/213#issuecomment-82629063>
> .
>


-- 

- Quincy Larson
"Anyone who has begun to think, places some portion of the world in
jeopardy." - John Dewey

**Comment by jameskopacz** [comment]
Submitted #222

Testing delete didn't work for some reason so I just set the password to null. Also added a check if the user is logged in.
