### ISSUE TITLE
Inaccurate checkpoint: div classes are mixed up

### ISSUE THREAD

**Issue by greenren** [FreeCodeCamp/FreeCodeCamp#2130]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Please note that the classes described in the first checkpoint are mixed up. The <div>'s with class "well" should go within the <div>'s with class "col-xs-6", instead of the other way around. Thank you!

Repro steps:
Go to http://www.freecodecamp.com/challenges/waypoint-create-bootstrap-wells
and observe the first checkpoint on the left.

![image](https://cloud.githubusercontent.com/assets/5858417/9344789/100ec872-45c0-11e5-80c7-7b443dae7a62.png)

**Comment by saadanerdetbare** [comment]
duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1968

**Comment by greenren** [comment]
Closing as duplicate.
