### ISSUE TITLE
Can't complete Zipline: Camper news

### ISSUE THREAD

**Issue by redhotlizzard** [FreeCodeCamp/FreeCodeCamp#2131]
Challenge http://www.freecodecamp.com/challenges/zipline-stylize-stories-on-camper-news has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Try to "Complete challenge", no response. Nothing in console. Tried again with all boxes checked, nothing

**Comment by benschenker** [comment]
Hey @redhotlizzard is this still an issue for you?  I'm having trouble replicating this, it may have already been fixed.  Reopen this if it is still problematic
