### ISSUE TITLE
code appearing next to X marks in un-completed steps 

### ISSUE THREAD

**Issue by HurricaneRunner** [FreeCodeCamp/FreeCodeCamp#2132]
Challenge http://freecodecamp.com/challenges/waypoint-manipulate-arrays-with-pop has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Looks like the code for an (X) sign (unfinished task) is showing up next to the un-finished (X).  e.g.

assert((function(d){if(d[0] == 'cat' && d[1] == 2 && d[2] == undefined){return(true);}else{return(false);}})(removed), 'myArray should only have the first two values left(["cat"], 2)');

![screen shot 2015-08-18 at 6 47 38 pm](https://cloud.githubusercontent.com/assets/13800610/9345763/f5d09e3a-45d9-11e5-944c-c2abe77ac5b9.png)

**Comment by bugron** [comment]
Dear camper, your issue is related to:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1911

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
