### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Cordycepss** [FreeCodeCamp/FreeCodeCamp#2133]
Challenge http://www.freecodecamp.com/challenges/waypoint-style-the-html-body-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Well, I just wanted to let you know that there is a grammatical derp on the page. There should be an "a" after "has" in the sentence, "Every html page has 'body' element. Okay, well.. Have an awesome day!

**Comment by dokkillo** [comment]
working in this issue
