### ISSUE TITLE
I think I have the correct code but it's not accepted. 

### ISSUE THREAD

**Issue by Marie000** [FreeCodeCamp/FreeCodeCamp#2134]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I think my code is correct, but it wont pass the test "Your #target1 element should have the classes animated‚ shake and btn-primary." 

![image](https://cloud.githubusercontent.com/assets/13281517/9345969/c1b0b576-45e4-11e5-9a90-a951e9d2e95f.png)

(I hope this screenshot works. I haven't used github before)

**Comment by apositivejam** [comment]
Not a bug. Your addClass arguments should be in quotes. 

```javascript
<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn-primary");
  });
</script>
```

This should pass.

**Comment by Marie000** [comment]
oops. thanks!
