### ISSUE TITLE
Bug on Waypoint: Target the Parent of an Element Using jQuery

### ISSUE THREAD

**Issue by cjg040103** [FreeCodeCamp/FreeCodeCamp#2135]
Challenge http://freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. It says it wants the left well to have a red background using ".parent()", so i put this:

    $("#left-well").parent().css("background-color", "red")

But it wouldn't work! The Lesson kept telling me:

```"Your left-well element should have a red background."```

Even though the background of the left well was red on the result screen!
I'm still trying to figure this out. But mostly I'm wondering if its not really a bug, I'm just screwing it up somehow.
Here's the code I have now:

```
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#left-well").parent().css("background-color", "red")

  });
</script>

<!-- You shouldn't need to modify code below this line -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4 id="#left-well">#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```

**Comment by benschenker** [comment]
@cjg040103 make sure to read the instructions carefully you are very close:

`Give the parent of the #target1 element background-color of red.`

**Comment by ahayder** [comment]
Is it fixed now? I have the same problem too.

**Comment by vivekranjan92** [comment]
perfect hint @benschenker  (Y)
