### ISSUE TITLE
Does not specify order

### ISSUE THREAD

**Issue by inukoblainc** [FreeCodeCamp/FreeCodeCamp#2136]
Challenge http://freecodecamp.com/challenges/waypoint-store-multiple-values-in-one-variable-using-javascript-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
Wants an array with a string and number. If you make the number the first element in array, it tells you that's wrong IE: var myArray = [12, "hi"];
The first item in myArray should be a string
The Directions make no mention of the string having to be first

**Comment by benschenker** [comment]
Thanks @inukoblainc 

Would "Now let's create a new array called myArray that contains both a string and a number **(in that order)**." make this clearer for you?  Or do you have a better suggestion?
