### ISSUE TITLE
Instructions panel jumps

### ISSUE THREAD

**Issue by ultrox** [FreeCodeCamp/FreeCodeCamp#2137]
As discussed on the chat there is two annoying things making me want to smash my mac. 
1. Everytime I change the code inside editor, left sidebar scroll up, and effectively making me scroll down as I want to see "objectives"

2. Exiting from the ""(quotes) could be easier then clicking left key, shortcut alt+space would be amazing, I have the same shortcut in my Sublime Text, and its time saver, also my left pinky love me.

 @benmcmahon100

**Comment by benmcmahon100** [comment]
The scrolling thing has a temp fix with a new one coming in version 2.0 of the code editor

**Comment by ultrox** [comment]
thanks, its better now :D

**Comment by benmcmahon100** [comment]
Ha Ha that's awesome! I wasn't sure it'd work! :p

**Comment by ultrox** [comment]
but.. I didn't want to be little bitch, it obviously not perfect, its like a person on MDMA its all over the place. Every time I change something in the code editor it jumps up and down, but again its better then before :D.

**Comment by coryb710** [comment]
Do you know when version 2.0 of the code editor will be coming out? Crazy scrolling also killing me

**Comment by benmcmahon100** [comment]
There is no ETA. We hope soon

**Comment by coryb710** [comment]
Ok, thanks for answering so quickly!

**Comment by BerkeleyTrue** [comment]
We are using this issue to track instruction panel jumping.

**Comment by benmcmahon100** [comment]
We've reverted to the old system of displaying the page
