### ISSUE TITLE
Incorrect "Next Challenge" after "Waypoint: Add Images to your Website"

### ISSUE THREAD

**Issue by ahtah** [FreeCodeCamp/FreeCodeCamp#2139]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The "Go to my next challenge (ctrl + enter)" button/function incorrectly links to "Waypoint: Manipulate Arrays With shift" instead of "Waypoint: Size your Images"

**Comment by benschenker** [comment]
Hey @ahtah hanks for posting!
We have a bunch of these reports from last week, but I haven't been able to reproduce most of them.  I'll close this for now but please reopen if you still notice this issue.
