### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by sonyakhan** [FreeCodeCamp/FreeCodeCamp#2141]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Code "assert(editor.getValue().match(/(\/\/)...../g)," appears on the left hand checklist.
 
After completing the challenge and running the code, section completion pop-up appears, and if you try to move on to the next section, the section completion pop-up will continuously appear instead of moving on to the next section.

Multi-line comments such as this do not pass the test:

/*

hello

*/

<img width="1440" alt="screen shot 2015-08-18 at 8 50 03 pm" src="https://cloud.githubusercontent.com/assets/10805390/9346442/c7ef449c-45ea-11e5-8bd1-d1ebf80add2d.png">

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2077
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1999
