### ISSUE TITLE
Waypoint: Manipulate Arrays With unshift

### ISSUE THREAD

**Issue by badjedi** [FreeCodeCamp/FreeCodeCamp#2142]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
I believe this is the correct answer but it will not let me move on.
![bug001](https://cloud.githubusercontent.com/assets/13355504/9346482/0eed6174-45e3-11e5-8a04-a5e74e522962.GIF)

**Comment by saadanerdetbare** [comment]
the correct answer is
```
myArray.unshift("Paul");
```

**Comment by badjedi** [comment]
ok thanks

**Comment by Python-git** [comment]
won't work I've tried multiple solutions

**Comment by Python-git** [comment]
not since beta 2018 july

**Comment by scissorsneedfoodtoo** [comment]
@Python-git, sorry to hear you're having trouble. I just tried the challenge and it seems to work fine. Do you have a screenshot? Also, what browser and version are you running?

**Comment by Python-git** [comment]
I fixed it. went from safari to chrome an Firefox

**Comment by scissorsneedfoodtoo** [comment]
@Python-git, glad it worked out! 

That's interesting. We'll have to do more testing with Safari. Thank you for reporting this.

**Comment by Python-git** [comment]
Thanks for reaching out
