### ISSUE TITLE
Javascript Waypoint 39

### ISSUE THREAD

**Issue by TimCoding** [FreeCodeCamp/FreeCodeCamp#2146]
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Hi!

When I'm working on this way point I can only get as far as entering $($('.slot')[0]).html(slotOne) before it freezes up and crashes. I tried making it work on Safari and Google but they both crashed.

**Comment by jbmartinez** [comment]
Possible duplicate of #1960

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
