### ISSUE TITLE
Only Suggestion (No Bug) - Mention Animate.css

### ISSUE THREAD

**Issue by Gmrpr7** [FreeCodeCamp/FreeCodeCamp#2147]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Suggestion: I think it would be helpful to mention that you are using Animate.css here or people might think the "animated" and "bounce" classes are part of JQuery.

**Comment by benschenker** [comment]
Hey @Gmrpr7, thanks for posting this!

Good catch, we need a blurb near the bottom of the description about this

**Comment by BerkeleyTrue** [comment]
It's mentioned here: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/a048049ca3dfe66362ab4bd2f7c4f39e0b82127e/seed/challenges/jquery.json#L62

**Comment by benschenker** [comment]
@BerkeleyTrue has that not been merged/deployed yet?

**Comment by BerkeleyTrue** [comment]
It will be shortly.

**Comment by BerkeleyTrue** [comment]
Its live! http://freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery
