### ISSUE TITLE
Unable to run code for first JavaScript exercise

### ISSUE THREAD

**Issue by rcachero** [FreeCodeCamp/FreeCodeCamp#2148]
Challenge http://freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Using Chrome on Mac OSX

Console shows error:

Refused to load the script 'http://freecodecamp.com/js/lib/jailed/_frame.js' because it violates the following Content Security Policy directive: "script-src *.optimizely.com *.aspnetcdn.com *.d3js.org https://cdn.inspectlet.com/inspectlet.js http://cdn.inspectlet.com/inspectlet.js http://beta.freecodecamp.com 'self' blob: 104.236.218.15 *.freecodecamp.com http://www.freecodecamp.com https://www.freecodecamp.com https://freecodecamp.com https://freecodecamp.org *.freecodecamp.org http://www.freecodecamp.org ws://freecodecamp.com/ ws://www.freecodecamp.com/ *.gstatic.com *.google-analytics.com *.googleapis.com *.google.com *.gstatic.com *.doubleclick.net *.twitter.com *.twitch.tv *.twimg.com 'unsafe-eval' 'unsafe-inline' *.bootstrapcdn.com *.cloudflare.com https://*.cloudflare.com localhost:3001 ws://localhost:3001/ http://localhost:3001 localhost:3000 ws://localhost:3000/ http://localhost:3000 *.ionicframework.com https://syndication.twitter.com *.youtube.com *.jsdelivr.net https://*.jsdelivr.net *.ytimg.com *.bitly.com http://cdn.inspectlet.com/ https://cdn.inspeclet.com/ wss://inspectletws.herokuapp.com/ http://hn.inspectlet.com/ *.googleapis.com *.gstatic.com https://hn.inspectlet.com/".

**Comment by gzcarlos** [comment]
Same here

**Comment by benschenker** [comment]
Interesting, thanks for posting your issue!

Have you tried a [hard reset](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache) or incognito mode?

**Comment by benschenker** [comment]
Also is this only on that one challenge or on multiple? 
I have been unable to reproduce this issue on my OSX/Chrome.

**Comment by rcachero** [comment]
Using Mac OS X 10.10.4 on a Macbook Pro and Chrome Version 44.0.2403.157 (64-bit)
 - Using incognito mode works and am able to submit an answer

**Comment by gzcarlos** [comment]
Yeah! incognito worked for me. Thanks!
