### ISSUE TITLE
Waypoint: Use RGB to Color Elements White & Red -- Missing semi-colon after "background-color" property

### ISSUE THREAD

**Issue by shaqueen** [FreeCodeCamp/FreeCodeCamp#2149]
Just some minute details...

The following exercises begin with a missing semi-colon after the "background-color" property, and they allow you to move onto the next challenge without correcting the syntax error:
- http://www.freecodecamp.com/challenges/waypoint-use-rgb-to-color-elements-white
- http://www.freecodecamp.com/challenges/waypoint-use-rgb-to-color-elements-red

These errors are not present in the Green & Blue exercises.

**Comment by bugron** [comment]
This is not an actual error because one can omit the final property's semi-colon, because that property does not need to be delimited. But this is mostly not recommended and is not a good practice.
