### ISSUE TITLE
Error on sample code

### ISSUE THREAD

**Issue by NeonViper** [FreeCodeCamp/FreeCodeCamp#2150]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The shift value on the "ourArray" sample is removing the last value of the array (["cat"]) instead of the first value ("Stimpson"). Not an actual bug, but can confuse someone.

![image](https://cloud.githubusercontent.com/assets/5242285/9348150/b6476a06-4600-11e5-8d27-9b10c8d2846c.png)

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2008
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1829
Already fixed.
