### ISSUE TITLE
JavaScript Waypoints Instructions bug.

### ISSUE THREAD

**Issue by ShortWaveLengthSubset** [FreeCodeCamp/FreeCodeCamp#2153]
Challenge http://www.freecodecamp.com/challenges/waypoint-declare-string-variables has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

All of the JavaScript waypoints instructions/requirements are showing up with the requirements code / missing plaintext descriptions it seems.
http://i.imgur.com/91Ph8wu.png for http://www.freecodecamp.com/challenges/waypoint-declare-string-variables

**Comment by airyz** [comment]
I reproduce the same issue.
