### ISSUE TITLE
Missing space between two words.

### ISSUE THREAD

**Issue by nardmacmke** [FreeCodeCamp/FreeCodeCamp#2154]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Was having trouble on getting the 5th item checked, experimented with the words and found it was a spacing issue.  Here is a screen shot with the correct code getting all green checks.

![image](https://cloud.githubusercontent.com/assets/13856495/9348430/3449a45a-45fc-11e5-9b98-c56c00265cb3.png)

Take a look at the #target1 code at the top.  There is no space between 'animated' and 'shake'.  Hope this helps anyone who got stuck like I was.

**Comment by dokkillo** [comment]
Hi, this code is created by you, maybe in other session, for fix this issue please press reset button

**Comment by benschenker** [comment]
It seems that this has been fixed, thanks!
