### ISSUE TITLE
Completing Bootstrap Waypoint: Make Images Mobile Responsive advances to wrong Waypoint

### ISSUE THREAD

**Issue by hurlsworth** [FreeCodeCamp/FreeCodeCamp#2155]
Hi FCC,

I am a new user and have just completed the HTLM5 and CSS waypoints and am starting the Bootstrap Waypoints. 

Impact: Minor

Expected result: After completing "Responsive Design with Bootstrap - 2. Waypoint: Make Images Mobile Responsive", I expect to be taken to the following waypoint, "Responsive Design with Bootstrap - 3. Waypoint: Center Text with Bootstrap" as per the Map. 

Experienced result: After completing "Responsive Design with Bootstrap - 2. Waypoint: Make Images Mobile Responsive", I was taken to "Basic JavaScript - 21: Waypoint: Manipulate Arrays with Push()"

I am using an updated copy of Chrome on a MacBook Air. When attempting to reproduce this behavior in an Incognito window with all Chrome extensions/plugins disabled, completing of the Waypoint was met with a timeout/no data received error, as it appears the site has gone down. Maybet his bug is moot? 

Anyhow, I appreciate the site and all the work that goes into it. Thank you much!

Tim
----
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-push has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey @hurlsworth thanks for posting this!

We got a bunch of similar issues posted last week about this and very few I've been able to replicate.

I'm going to close this for now but if you can replicate this please reopen.
