### ISSUE TITLE
HTML5 waypoint 16 completion leads to JavaScript waypoint 21

### ISSUE THREAD

**Issue by ordinaryxcentric** [FreeCodeCamp/FreeCodeCamp#2157]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-push has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Completed HTML5 waypoint 16, ctrl-enter or push button leads to this lesson. Tried twice.

**Comment by ordinaryxcentric** [comment]
Waypoint: add images to your website
Next challenge:
Waypoint: manipulate arrays with push

Expected: Size your images -- I was able to get into this waypoint through the map.

**Comment by Shufeng01** [comment]
I met this as well

**Comment by bordeltabernacle** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2078

**Comment by benschenker** [comment]
Hey @ordinaryxcentric, thanks for posting this!

I cannot replicate this.  We've had a bunch more reports like this around the same time as you posted which have been fixed.  I'm going to close this, but feel free to reopen if you are still experiencing this issue.
