### ISSUE TITLE
Beta version

### ISSUE THREAD

**Issue by undergroundfx** [FreeCodeCamp/FreeCodeCamp#2159]
Challenge http://www.freecodecamp.com/challenges/waypoint-give-a-background-color-to-a-div-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

HI, all of the challenges that I completed on the beta version are not completed on this version. That wouldnt be too bad as I can do them all again but it won't let me because I can't run the code, it's got the ''Go to the next challenge button but I can't even push that or run my code.

Please help, I don't won't to start all over. Thank you.

**Comment by benschenker** [comment]
Hey it seems like this is a stale issue.  I'm going to close this but feel free to reopen if you still see this problem.
