### ISSUE TITLE
Story replies messed up in Firefox?

### ISSUE THREAD

**Issue by jameskopacz** [FreeCodeCamp/freecodecamp#216]
Does anyone else see replies floating to the right in Firefox (36.0.1) when clicking Reply to a story? http://i.imgur.com/Bm3grxC.png

It looks correct in Chrome.

If it's not just me then the fix is to add the "row" class to ".hidden-element#initial-comment-submit" in views/stories/show.jade

**Comment by jameskopacz** [comment]
Can someone double check this in Firefox and let me know what you see.

**Comment by QuincyLarson** [comment]
Hi James, try it now. We identified some CDN calls that were blocked by Helmet and allowed them to go through. It looks fine on my side in Firefox now. Please confirm.

**Comment by jameskopacz** [comment]
I'm still seeing it. Redownloaded source and viewed in fresh profile of Firefox just to make sure.

It happens when i click the reply button in the circle in the attached image.
![untitled-1](https://cloud.githubusercontent.com/assets/1335422/6700425/eaac2b04-ccdb-11e4-8911-34b9d8df20b2.jpg)
