### ISSUE TITLE
jQuery Waypoint Issue

### ISSUE THREAD

**Issue by gregoryneal** [FreeCodeCamp/FreeCodeCamp#2160]
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue. You can complete the waypoint by simply calling removeClass() on all of the button elements without specifically removing "btn-default".
![capture](https://cloud.githubusercontent.com/assets/13123810/9349307/db50e7b0-4609-11e5-9dcc-7d521efaf852.PNG)

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1923
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1898
Fixed.

**Comment by bakomelinda** [comment]
Berkeley Martinez <notifications@github.com> ezt írta (2015. augusztus 23.,
vasárnap):
