### ISSUE TITLE
Challenge doesn't recognize solution 

### ISSUE THREAD

**Issue by gzatrader** [FreeCodeCamp/FreeCodeCamp#2161]
Challenge http://freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Challenge: "Give the parent of the #target1 element background-color of red."
Example provided: $("#left-well").parent().css("background-color", "blue")

Answer: $("#left-well").parent().css("background-color", "red");

![screen shot 2015-08-19 at 12 58 38 pm](https://cloud.githubusercontent.com/assets/7462368/9349603/871a169e-4672-11e5-914d-62d5843bcd33.png)

However:

![screen shot 2015-08-19 at 1 03 06 pm](https://cloud.githubusercontent.com/assets/7462368/9349611/aae72ca6-4672-11e5-8801-e3bef64b8cce.png)

:(

**Comment by benschenker** [comment]
See #2135

**Comment by gzatrader** [comment]
@benschenker Thank you and sorry for wasting your time.
