### ISSUE TITLE
error in comments

### ISSUE THREAD

**Issue by DmitriySatinaev** [FreeCodeCamp/FreeCodeCamp#2162]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Error in hint in comment:
![image](https://cloud.githubusercontent.com/assets/13708154/9349829/b3235468-4653-11e5-9aab-07345669e8cc.png)

it should be:
 // ourArray now equals [[happy,joy],J,[cat]]"

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2008
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1829
