### ISSUE TITLE
Incorrect information on the plus sign in RegEx

### ISSUE THREAD

**Issue by denmch** [FreeCodeCamp/FreeCodeCamp#2163]
Challenge http://freecodecamp.com/challenges/waypoint-sift-through-text-with-regular-expressions has an issue.

This waypoint is confused as the nature of the plus sign and the global modifier in regex. To pass, a camper needs to use this (incorrect) expression: `/and+/gi`. It works, but it really means "find any instance of the pattern of one A and one N followed by any number of Ds."

The solution should be `/and/gi`, but this doesn't pass.

Here's the relevant bit from the instructions:

> \+ means we want to find one or more occurrences of this pattern.

> g means that we want to search the entire string for this pattern.

This is incorrect. The plus sign applies only to an individual character, so that an expression like this:

`/and+/`

would select "and" or "andd" or "anddd", etc.

Likewise `/a+nd/` would select "and" or "aand", etc., and `/a+n+d+/` would select "and" or even "aaaaaaaaaannnnnddddddd".

It's not accurate to say that the global modifer (g) searches the entire string. (If that were the case, what part of the string would it be be limited to without the global modifier?)

The default behavior is to search until the pattern is found, and then to stop and say, "I found it!". If it isn't found, then the entire strong IS searched. The global modifier simply says "don't stop when you find the first one, but keep going and find all of them," which is what the instructions seem to think the plus sign is doing.

**Comment by denmch** [comment]
Duplicate of #1938

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2053
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1997
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1938

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
