### ISSUE TITLE
Current streak wrong

### ISSUE THREAD

**Issue by zorfa** [FreeCodeCamp/FreeCodeCamp#2165]
My account says that my current streak is 2 days. But its my third day today, so shouldn't it be displaying 3 days and not 2?
![screen shot 2015-08-19 at 12 35 09 pm](https://cloud.githubusercontent.com/assets/8377726/9352056/1cb12624-466f-11e5-81df-21f745b3b9fb.png)

**Comment by dokkillo** [comment]
Hello Zorfa,

I reported that bug https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1861

**Comment by zorfa** [comment]
Sorry! I did not see that. I will close this issue
