### ISSUE TITLE
Feature request: adding a way to fix wording and typos on the bonfire screen

### ISSUE THREAD

**Issue by Shufeng01** [FreeCodeCamp/FreeCodeCamp#2166]
Current there are a lot of issues opened for wording and typos which are kind of trivial for devs but still required a push. 

Wondering if we can introduce a self-edit dialog for each challenge and let learners fix these errors directly. If I understand the architecture correctly all the challenges are saved in json files and it's not too hard to update a single block.

**Comment by BerkeleyTrue** [comment]
Hello @Shufeng01 

Campers can edit challenges by filing PR's against the json files. Its important that campers get to know this process. We do not want to add another layer between this process.

Happy Coding!
