### ISSUE TITLE
Wrong color in the daily streak

### ISSUE THREAD

**Issue by dokkillo** [FreeCodeCamp/FreeCodeCamp#2167]
Hi,

its not an important issue, but is an issue. For example in my daily streak one day I did 78 Waypoints and I got a dark green box, and the next day I did 3 waypoints and I got another dark green box, and I guess it must be light green.

![errorgrade2](https://cloud.githubusercontent.com/assets/920841/9351763/671bffe4-465c-11e5-8df5-27bdc61e723a.png)
![errorgrade1](https://cloud.githubusercontent.com/assets/920841/9351764/671d5c9a-465c-11e5-8520-b351cbc7b689.png)

**Comment by benschenker** [comment]
This seems to have been fixed, I see different shades of green in my streak.  I'll close this for now, but reopen if this is still an issue for you.

**Comment by dokkillo** [comment]
Thanks to you guys, this is fixed :)

**Comment by ahstro** [comment]
I think 1 item gives you the lightest shade, 2 the medium, and 3 and above the darkest. Not sure if this should be changed to work similarly to how it works on GitHub or not?

**Comment by benschenker** [comment]
Hey @dokkillo I normally post the PR that fixed it but I cannot find it at all! It may be worth asking on gitter but either way a nice dive into the code should be helpful in figuring out where the relevant code is!
