### ISSUE TITLE
passes when image doesn't show

### ISSUE THREAD

**Issue by advancedclockwork** [FreeCodeCamp/FreeCodeCamp#2168]
Challenge http://www.freecodecamp.com/challenges/waypoint-make-images-mobile-responsive has an issue. Please describe how to reproduce i
![image](https://cloud.githubusercontent.com/assets/6707281/9352048/fc75e1bc-462b-11e5-8e70-dc8f625c6c24.png)
t, and include links to screenshots if possible.

**Comment by dokkillo** [comment]
Hi,

You forget the " " in the second image.

![fixissue](https://cloud.githubusercontent.com/assets/920841/9352180/711dffd0-465f-11e5-95c4-8cb1623aa4aa.png)

**Comment by advancedclockwork** [comment]
the > is missing but it passes. just an oversight, thanks though

**Comment by dokkillo** [comment]
ah yes true too hehe... you can close the issue
