### ISSUE TITLE
Can't complete challenge, mix up with Simon challenge

### ISSUE THREAD

**Issue by JanMP** [FreeCodeCamp/FreeCodeCamp#2169]
Challenge http://www.freecodecamp.com/challenges/zipline-build-a-tic-tac-toe-game has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Even though I submitted this challenge a little while ago, it was now marked as unfinished, while the new Simon game challenge is marked as completed. I wanted to correct that and enter the Url, but
pressing the "I've finished the challenge" Button does nothing.

**Comment by bugron** [comment]
Dear camper, your issue is related to:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1902
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1800

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
