### ISSUE TITLE
Change Font Size issue

### ISSUE THREAD

**Issue by Dphnis** [FreeCodeCamp/FreeCodeCamp#2171]
![screen shot 2015-08-19 at 3 06 43 am](https://cloud.githubusercontent.com/assets/13867565/9353721/675a1154-461f-11e5-899c-cb0e143da52e.png)
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Even though the font size is changed, it is not recognized as completed.

**Comment by vishdha** [comment]
your <p class="read-text"> here class is .right-text. you can't used p in style use class name which already mention as .read-text 
for eg:
<style>
  .red-text {
    color: red;
    font-size:16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>
  kitty ipsum text: Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.
</p>

try this

**Comment by bugron** [comment]
@Dphnis Of course you can use ```p``` in ```style``` element (even you would: "Then, inside your style element, set the font-size of **all** p elements to 16 pixels.").
![](http://i.imgur.com/OpHIINB.png?1)

**Comment by xiaji2** [comment]
iiiiiii

**Comment by cheyika** [comment]
**'Twas a bit confusing. Thank you for the help, @bugron!** 


![image](https://cloud.githubusercontent.com/assets/21285972/18031683/15ae703e-6d1f-11e6-9e67-f7ddd9829ba9.png)

**Comment by Cosmiin** [comment]
This is how I popped my github cherry! Thx for the tip!
