### ISSUE TITLE
Clicking I've completed this challenge doesn't do anything

### ISSUE THREAD

**Issue by fburada** [FreeCodeCamp/FreeCodeCamp#2174]
Challenge http://freecodecamp.com/challenges/zipline-build-a-random-quote-machine has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I've tried clicking I've completed this challenge in the latest versions of  google chrome, firefox and microsoft edge but I can't get the link to work.

**Comment by fburada** [comment]
I don't seem to be able to click "I've completed this challenge" in any of the ziplines. I'm running windows 10 and I've tried it in both firefox and chrome.

**Comment by benmcmahon100** [comment]
We fixed this just the other day
