### ISSUE TITLE
help sought out this guyz

### ISSUE THREAD

**Issue by Nickmbt** [FreeCodeCamp/FreeCodeCamp#2176]
Challenge http://freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey @Nickmbt thanks for posting.

I'm going to close this issue as there is no way to tell what exactly is the problem or how to reproduce it.  Take a look at our [Bug Posting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) and if you still experience your issue, reopen this with some more details/screenshots.
