### ISSUE TITLE
Portfolio page doesn't show most of my bonfire solutions

### ISSUE THREAD

**Issue by kmiasko** [FreeCodeCamp/FreeCodeCamp#2177]
I haven't logged in into FCC for two or three weeks. Today after logging in i had to connect my profile with github profile. After this i see only few last bonfire solutions i've done. 

Most of the bonfires was marked as done in 1970, maybe that's the problem.

**Comment by benschenker** [comment]
Hey @kmiasko thanks for reporting this!

Can you post a screenshot?

**Comment by kmiasko** [comment]
Sorry i was offline. Posting few screenshots of bonfires isn't really interesting i think. I can paste which ones are there.

All zipline solutions are in my profile.

Meet Bonfire	Apr 22, 2015
Bonfire: Title Case a Sentence	May 29, 2015
Bonfire: Title Case a Sentence	May 29, 2015
Bonfire: Title Case a Sentence	May 29, 2015
Bonfire: Symmetric Difference	Jul 15, 2015
Bonfire: Symmetric Difference	Jul 15, 2015
Bonfire: Exact Change	Jul 15, 2015
Bonfire: Exact Change	Jul 15, 2015
Bonfire: Friendly Date Ranges	Jul 15, 2015
Bonfire: Friendly Date Ranges	Jul 15, 2015
Bonfire: Friendly Date Ranges	Jul 15, 2015
Bonfire: Meet Bonfire	Jul 15, 2015

Rest of my solutions are gone after upgrade.

**Comment by benschenker** [comment]
@QuincyLarson any ideas?

**Comment by BerkeleyTrue** [comment]
@kmiasko Are you still having this issue?

**Comment by kmiasko** [comment]
@BerkeleyTrue yep, nothing changed

![Portfolio image]
(http://i.imgur.com/9yxmsIb.png)

**Comment by bugron** [comment]
@kmiasko is this still an issue for you?

**Comment by kmiasko** [comment]
@bugron I don't need it, but it hasn't changed. Still as in the picture.
