### ISSUE TITLE
test html basic

### ISSUE THREAD

**Issue by arpithumane** [FreeCodeCamp/FreeCodeCamp#2178]
Challenge http://freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by jbmartinez** [comment]
Can you give more details, please?

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!

**Comment by arpithumane** [comment]
Hey,

Sorry, I couldn't reply asap. Anyways I got the solution. The thing is,
multiple classes in a single tag was not introduced until and in that
exercise. Googled, sorted.
