### ISSUE TITLE
display error

### ISSUE THREAD

**Issue by cove9988** [FreeCodeCamp/FreeCodeCamp#2179]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
Code broken:
assert(editor.getValue().match(/(\/\/)...../g), 'Create a \/\/ style comment that contains at least five letters');
Create a // style comment that contains at least five letters

Should only show;
Create a // style comment that contains at least five letters

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2141
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2077
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1999
