### ISSUE TITLE
Design Flaw in Bonfires 

### ISSUE THREAD

**Issue by duttakapil** [FreeCodeCamp/freecodecamp#218]
When you click on Run Code in a Bonfire challenges with just the default code, it shows you all the tests that are run for that program and their expected output. This can be used to write a program that returns the expected output for all the tests and pass the challenge. 

I passed the [No Repeats Please](http://www.freecodecamp.com/bonfires/no-repeats-please) challenge by doing just this. Here is my code : 
```
function permAlone(str) {
  if(str == 'aab')
    return 2;
  if(str == 'abcdefa')
    return 3600;
  if(str == 'abfdefa')
    return 2640;
  if(str == 'zzzzzzzz')
    return 0;
  if(str == 'aabb')
    return 8;
  if(str == 'aaa')
    return 0;
}
```
![Passed the Challenge](http://i.imgur.com/QeSoSGP.png)
 
My solution for this design flaw is, instead of giving away the expected output, we say something like "Your code din't pass for this test" and give just the input of the test and not the expected output. 
That way the user would not know what the expected outputs are and would not be able to pass the challenge like I did.

**Comment by terakilobyte** [comment]
That's perfectly fine. The solutions are saved. If someone is caught doing this they'll most likely be uninvited from participating in non-profit projects.

I'm rather a fan of this, actually. I firmly believe in giving someone enough rope to hang themselves.

**Comment by FreeCodeCamp** [comment]
That's a great point, @duttakapil. We considered it at length, as @terakilobyte pointed out. We wanted to err on the side of transparency, as hidden failing conditions are frustrating and unecessary for the 99% of people who are interested in learning, rather than just blowing through these.

Just because someone can get away with something doesn't mean they will try to.
