### ISSUE TITLE
Repetative waypoints

### ISSUE THREAD

**Issue by jstoebel** [FreeCodeCamp/FreeCodeCamp#2180]
Challenge http://freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-shades-of-gray has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I'm not sure if this is intended or not but there are several new way points posted that ask the user to almost exactly the same thing.  Their names are as follows:

waypoint: Use Hex Code to Color Elements White
waypoint: Use Hex Code to Color Elements Red
waypoint: Use Hex Code to Color Elements Green
waypoint: Use Hex Code to Color Elements Blue
waypoint: Use Hex Code to Mix Colors
waypoint: Use Hex Code to Color Elements Gray
waypoint: Use Hex Code for Specific Shades of Gray

All of them are completed by simply changing the Hex value. This may be intentional, I don't know, but I thought I would point it out.

**Comment by benschenker** [comment]
Hey @jstoebel, thanks for posting this!

This does seem intentional, so as to drill this skill into campers.
I am going to close this issue, but feel free to reopen if you feel it is an issue (or annoying for campers)

**Comment by moycs777** [comment]
Hi, the site remains in the challenge: Use Hex Code to Mix Colors, and i have resolved it.
