### ISSUE TITLE
Asserts are visible

### ISSUE THREAD

**Issue by Harmitage** [FreeCodeCamp/FreeCodeCamp#2182]
Today I've started JS chunk and I can see every assert for every step. Asserts still have "grayed-out" class, but are visible.
For example here: http://freecodecamp.com/challenges/waypoint-declare-string-variables
![testest](https://cloud.githubusercontent.com/assets/9102888/9355725/064e4d0a-4695-11e5-8971-10962c9f56a1.png)

**Comment by michael-krebs** [comment]
This is intended behavior. It is useful to see the tests, especially later on in the bonfires.

**Comment by Harmitage** [comment]
Thanks for an explanation, I asked about that in chatroom, but people were too busy:)

Although, I think it could be more useful. Right now I see text duplication and messy code, which can and should be beautified.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2153

**Comment by BerkeleyTrue** [comment]
This is on purpose. 

>That should be showing up there. It's part of all the javascript based challenges that you are able to see the tests that are running against your code. See #2231 for a similar issue/explanation.

Also see: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github


Happy Coding!
