### ISSUE TITLE
has the beta been tested on opera

### ISSUE THREAD

**Issue by nicovanwyk** [FreeCodeCamp/FreeCodeCamp#2183]
I went back to complete a challenge I noticed that the beta has gone live ..... um it doesnt look like it has been tested on opera as I am not ale to complete challenges via opera ....

opera version : 31.0.1889.99
OS is a ground up build making use of  the debian stable repo

Challenge http://freecodecamp.com/challenges/zipline-wikipedia-viewer has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

update1: I can complete a challange in firefox but only when I CTRL-ENTER
update2: completing a wa point is compatible with opera

**Comment by benschenker** [comment]
Hey @nicovanwyk thanks for posting.

It looks like you've updated your comment suggesting this is no longer an issue so I'll close it.  Feel free to reopen if you still experience problems.
