### ISSUE TITLE
Target a Specific Child of an Element Using jQuery

### ISSUE THREAD

**Issue by pokica-hu** [FreeCodeCamp/FreeCodeCamp#2187]
According to the task second element of each "well" has to bounce while the code check whether "target" have "animated" and "bounce" classes added.
I added the following code and now I'm allowed to go to the next challenge:
    $(".target:nth-child(2)").addClass("animated bounce");

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2068
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2005
