### ISSUE TITLE
Picky test cases

### ISSUE THREAD

**Issue by jstoebel** [FreeCodeCamp/FreeCodeCamp#2188]
Challenge http://freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

For test criteria #5 (Your #target1 element should have the classes animated‚ shake and btn-primary.) It appears that the classes must appear in the exact order given. So $("#target1").addClass("animated shake btn-primary"); is accepted but $("#target1").addClass("animated btn-primary shake "); is not.

**Comment by benschenker** [comment]
Hey @jstoebel thanks for posting this!

It looks like the tests have been updated because `$("#target1").addClass("animated shake btn-primary");` is no longer accepted since it requires 3 separate selections like:
```
$("button").addClass('animated')
$("#target1").addClass('btn-primary')
$(".btn").addClass('shake')
```

Closing as stale

**Comment by rajeshjoshi12** [comment]
10Q
