### ISSUE TITLE
misleading criteria

### ISSUE THREAD

**Issue by jstoebel** [FreeCodeCamp/FreeCodeCamp#2189]
Challenge http://freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Since this is an exercise about the .removeClass function I believe the second criteria should read.

"Only use jQuery to remove this class from the element." 

instead of

"Only use jQuery to add these classes to the element."

**Comment by dokkillo** [comment]
working with this issue

**Comment by benschenker** [comment]
This seems to have been fixed....Closing
