### ISSUE TITLE
H1 Pink Text!

### ISSUE THREAD

**Issue by hudnoirhibtam** [FreeCodeCamp/FreeCodeCamp#2190]
Challenge http://www.freecodecamp.com/challenges/waypoint-override-class-declarations-by-styling-id-attributes has an issue. <img width="916" alt="fcc" src="https://cloud.githubusercontent.com/assets/13369538/9356971/e4f25090-46a1-11e5-8506-267d56b309fd.png">

**Comment by vysu** [comment]
Please observe the "Spelling mistake in your code" (pink-test)

**Comment by vysu** [comment]
Please observe the "Spelling mistake in your code" (pink-test)

**Comment by hudnoirhibtam** [comment]
Oh. Alrighty! Thanks :D
