### ISSUE TITLE
Instruction in Comments is wrong

### ISSUE THREAD

**Issue by ManuelNiederl** [FreeCodeCamp/FreeCodeCamp#2191]
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-within-a-range The comment in the Challenge tells me to make a random number between 0-9 but the max given is 12. The challenge tells me I'm correct even if I don't change the value of that variable. 

![freecodecamp](https://cloud.githubusercontent.com/assets/13767118/9357499/e6a5e9e2-464c-11e5-990c-c3fcc7cbf2e4.PNG)

.

**Comment by dokkillo** [comment]
ok, working in this one
