### ISSUE TITLE
Extra text in this challenge

### ISSUE THREAD

**Issue by chreyes** [FreeCodeCamp/FreeCodeCamp#2193]
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript has an issue. 

There is extra text in the challenge : "It's great that we can create random decimal numbers, but it's even more useful if we --- lot more useful to --- generate a random whole number."

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1920
Fixed.
