### ISSUE TITLE
jquery is right but showing is incorrect

### ISSUE THREAD

**Issue by vishdha** [FreeCodeCamp/FreeCodeCamp#2195]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![image](https://cloud.githubusercontent.com/assets/6947417/9358611/9ba04f38-46aa-11e5-9f72-64aea9ac8d54.png)

**Comment by vysu** [comment]
The challenge is : 
Your left-well element should have a red background. (using the parent() function).

Here  "left-well" is a "div" element, which does not include <h4>#left-well</h4> element.

Please try again/please ask for help in the Gitter chat.

**Comment by benschenker** [comment]
See #2135, just read the instructions a bit more carefully and you will get it.

**Comment by vishdha** [comment]
thanks guys
