### ISSUE TITLE
All progress is lost for me on FCC

### ISSUE THREAD

**Issue by Monoxide27** [FreeCodeCamp/FreeCodeCamp#2196]
Hello,

When I log into freecodecamp, all of my progress is gone. I was about 65% through JavaScript with every single lesson before it completed. Will I have to redo all of that? That would be weeks worth of time I have to redo. I haven't found anyone else with this problem, so hopefully it's just a glitch and it'll be up to date again.

**Comment by Monoxide27** [comment]
When I say every lesson, I mean legitimately every single thing on the map from the very beginning through almost 3/4's of JavaScript.

**Comment by dokkillo** [comment]
Hi,

Freecodecamp changed all jquery, javascript now it are leason by Freecodecamp and not codeacademy. 
Its new leassons, more teach and much more info.

regards

**Comment by Monoxide27** [comment]
Ok, I understand. For some reason I couldn't connect the dots. I see my progress now. Thank you, @dokkillo.
