### ISSUE TITLE
Challenge marked as completed before it's *Actually* completed

### ISSUE THREAD

**Issue by Waddah-JD** [FreeCodeCamp/FreeCodeCamp#2197]
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue. right now, whenever the camper write the removeClass() function -even before specifying the class he/she wants to be removed-. the application automatically marks the challenge as completed.

The reason: when the parameter isn't specified to removeClass() function it removes ALL classes of the selected element, which means that the "btn-default" class (as required by the challenge) is going to be removed but the problem is that it will remove all other classes at the same time.

I think the test should make sure that other classes still added to the element while "btn-default" is removed.
![screenshot from 2015-08-19 17-29-39](https://cloud.githubusercontent.com/assets/9061886/9359085/f410a694-4697-11e5-8c07-5af4017248fa.png)

**Comment by Nathandim** [comment]
Same thing happened to me just now, using Google Chrome on Windows 10.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2160
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1923
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1898
Fixed.
