### ISSUE TITLE
There is an Ambiguous reference

### ISSUE THREAD

**Issue by oshliaer** [FreeCodeCamp/FreeCodeCamp#2198]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The challenge has words:
> Use Clockwise Notation to give ***an element*** a margin of 40px on its top and left side, but only 20px on its bottom and right side.

But `green-box` is required. It should be:
> Use Clockwise Notation to give ***the ".green-box" class*** a margin of 40px on its top and left side, but only 20px on its bottom and right side.

<sub>**Disclamer: English is not my native language. I could be wrong.**</sup>

**Comment by benschenker** [comment]
Thanks @oshliaer!

This should be a straightforward fix.

**Comment by benschenker** [comment]
@bugron why did you close this?  I still see this issue?

**Comment by bugron** [comment]
@benschenker Sorry, I forgot to mention that there PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2959 is merged which actually fixes this issue.
