### ISSUE TITLE
Zipline finished button doesn't work

### ISSUE THREAD

**Issue by hansinla** [FreeCodeCamp/FreeCodeCamp#2199]
Challenge http://www.freecodecamp.com/challenges/zipline-build-a-personal-portfolio-webpage has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

complete-zipline-or-basejump-dialog doesn't open a dialog to enter link to finished work

**Comment by abbynormative** [comment]
I'm also having this problem. Clicking on the "I've Completed This Challenge" button does nothing. No dialogue box opens, and I can't move forward to the next exercise.

**Comment by benschenker** [comment]
@benmcmahon100 has this been resolved?

I can't seem to replicate this?

**Comment by benmcmahon100** [comment]
It should be i think we fixed it a while ago

**Comment by benschenker** [comment]
Awesome,  I'l close this and a few other related issues
