### ISSUE TITLE
Accepts attribute values without quotes

### ISSUE THREAD

**Issue by mm1729** [FreeCodeCamp/FreeCodeCamp#2200]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-bootstrap-row has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When I added this piece of code:

<div class=row>
  </div>

under h3 element, it accepts the solution even though row is not surrounded by quotes.

**Comment by benschenker** [comment]
This is actually not a bug.  HTML attributes do not need to be in quotes unless you have to represent space somehow. See https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Introduction#Attributes
