### ISSUE TITLE
Wording is off

### ISSUE THREAD

**Issue by senorsunday** [FreeCodeCamp/FreeCodeCamp#2201]
Challenge http://www.freecodecamp.com/challenges/waypoint-access-array-data-with-indexes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The code is wrong.
if(typeof(myArray) !== "undefined" && typeof(data) !== "undefined"){(function(y,z){return('myArray = ' + JSON.stringify(y) + ', data = ' + JSON.stringify(z));})(myArray, data);}

That implies that you're looking for the user to define 'data', when the challenge is looking for the user to define 'myData'.

**Comment by benschenker** [comment]
Hey @senorsunday thanks for posting this issue.

It looks like this has been fixed!
