### ISSUE TITLE
Typo I guess

### ISSUE THREAD

**Issue by rogierjh** [FreeCodeCamp/FreeCodeCamp#2202]
Challenge http://freecodecamp.com/challenges/waypoint-set-the-id-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

It requires you to set the id to cat-photo-form as opposed to "cat-photo-form", for you to go to the next challenge.

**Comment by Cadence22** [comment]
I am having an issue with this waypoint as well.

**Comment by BerkeleyTrue** [comment]
Not sure what the issue is. Can you clarify?

**Comment by benschenker** [comment]
@rogierjh those are actually equivalent in HTML attributes:
```
<form id=cat-photo-form></form>
```
and
```
<form id="cat-photo-form"></form>
```
are the same, see #2200
