### ISSUE TITLE
`Cannot read property ‘getTime’ of undefined` in profile heat map

### ISSUE THREAD

**Issue by eliandoran** [freeCodeCamp/freeCodeCamp#22031]
**Describe the bug**
After resetting the progress on my profile, my heat map section would no longer work. More specifically, the squares will not become colored, even if the tool tip for individual squares works correctly.

**To Reproduce**
1. Go to my public profile (https://www.freecodecamp.org/eliandoran/).
2. Notice the heat map does not contain any colored boxes, even if there is data on October 17th to 19th upon hovering.
3. Open the browser console and notice the error.

*See **Additional context** for more information on the error.*

**Expected behavior**
The heat map should render properly, displaying three blocks of different colors (as of writing this issue) instead of being empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/21236836/47204080-128dd500-d38b-11e8-98bd-8ff50ba6ff98.png)

**Additional context**
The problem, as displayed in the browser’s console is as follows:

```
cal-heatmap.min.js:9 Uncaught TypeError: Cannot read property 'getTime' of undefined
    at a.parseDatas (cal-heatmap.min.js:9)
    at u (cal-heatmap.min.js:9)
    at a.getDatas (cal-heatmap.min.js:9)
    at cal-heatmap.min.js:8
    at a._init (cal-heatmap.min.js:8)
    at a.init (cal-heatmap.min.js:8)
    at t.value (HeatMap.jsx:69)
    at t.value (HeatMap.jsx:47)
    at e.notifyAll (CallbackQueue.js:74)
    at f.close (ReactReconcileTransaction.js:78)
```

The error seems to be caused by an XHR request to https://www.freecodecamp.org/services/user which returns a JSON containing the following problematic data:

```
"calendar":{
   "1539791025":1,
   "1539791051":1,
   "1539791079":1,
   "1539791132":1,
   "1539791151":1,
   // More data
   "NaN":1
}
```

It seems that a NaN infiltrated among the calendar dates, most likely immediately after resetting the progress of my account.

**Comment by eliandoran** [comment]
Please note that the "My time line" section is also missing, probably as a direct consequence to the script error described above.

**Comment by pecey** [comment]
I can have a look at this.

**Comment by icatat** [comment]
Is this related to issue #17822 ?

**Comment by ayushshah2120** [comment]
> Is this related to issue #17822 ?

Kind Of..
My Issue is same as this issue as well as #17822 one.

**Comment by raisedadead** [comment]
We are waiting for the fix to be deployed to confirm this is fixed.
