### ISSUE TITLE
Problem iframe iphone background

### ISSUE THREAD

**Issue by aluzardo** [FreeCodeCamp/FreeCodeCamp#2203]
Challenge http://freecodecamp.com/challenges/waypoint-prioritize-one-style-over-another has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I detected a problem with the iframe iphone background in my Macbook Pro Retina + Chrome

Can you see a vertical white line in the right side of the iphone background?
<img width="1415" alt="captura de pantalla 2015-08-19 a las 16 37 24" src="https://cloud.githubusercontent.com/assets/11529571/9360934/095c9d84-4691-11e5-86d3-828bb9c0f8e7.png">

It is the CSS style

@media (min-width: 992px)
iframe.iphone {
    width: 280px;
    height: 500px;
    position: absolute;
    top: 70px;
    right: 25px;
    overflow-y: scroll;
}

I fix the problem

<img width="1420" alt="captura de pantalla 2015-08-19 a las 16 36 20" src="https://cloud.githubusercontent.com/assets/11529571/9361008/61346730-4691-11e5-9c3c-77b1b234a45f.png">

I override 

@media (min-width: 992px)
iframe.iphone {
    width: 283px;
    height: 500px;
    position: absolute;
    top: 70px;
    right: 23px;
    overflow-y: scroll;
}

It could not be the best solution, but I saw better the iphone.

I love FreeCodeCamp.

Thanks,
Adolfo

**Comment by benschenker** [comment]
Thanks @aluzardo I've confirmed your issue!

Feel free to put in a pull request for this

**Comment by BerkeleyTrue** [comment]
Is this still an issue?

**Comment by aluzardo** [comment]
I don't know but I not pull the solution. Sorry.
