### ISSUE TITLE
the guide is showing false code

### ISSUE THREAD

**Issue by pr0PM** [freeCodeCamp/freeCodeCamp#22040]
**Describe your problem and how to reproduce it:**
the code in guide uses ambiguous colors for UPPERCASE.

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: Mozilla
* Browser Version: 
* Operating System: Ubuntu

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Nirajn2311** [comment]
@pr0PM could you post a screenshot and the link to the guide artcile.

**Comment by johnkennedy9147** [comment]
I can see this when viewing the source in Github https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/python/for-loop-statements/index.md, but it is not present in the guide as published. So this appears to be an issue with githubs displaying of markdown and not the guides therefore closing this issue.
