### ISSUE TITLE
Use jQuery to remove your target4 element from your page.

### ISSUE THREAD

**Issue by appijumbo** [FreeCodeCamp/FreeCodeCamp#2204]
Just a tiny bug,  text says 
![bug](https://cloud.githubusercontent.com/assets/10559688/9361461/7c001a80-4693-11e5-9606-efb60236f1d3.jpg)

"Now let's remove an HTML element from your page using jQuery.
jQuery has a function called .remove() that will remove an HTML element entirely." but doesn't mention anything about target4, (thats below in the 'checks' notes)

**Comment by benschenker** [comment]
Thanks @appijumbo, it looks like this has been fixed!
