### ISSUE TITLE
Program failure execution

### ISSUE THREAD

**Issue by badjedi** [FreeCodeCamp/FreeCodeCamp#2205]
![bug002](https://cloud.githubusercontent.com/assets/13355504/9361560/8f16e54a-4661-11e5-9a7f-6949c3fe1d11.GIF)
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-javascript-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I checked it in another program it says its valid JavaScript yet I keep getting this.

**Comment by michael-krebs** [comment]
This isn't valid JS, please ask for help in the Gitter chat before submitting an issue

**Comment by badjedi** [comment]
Fixes #2205

**Comment by benschenker** [comment]
This has been fixed, Thanks!
