### ISSUE TITLE
'Longest Streak', 'Current Streak' counter  using 'No of waypoints solved' instead of day streak count

### ISSUE THREAD

**Issue by neeraj08** [FreeCodeCamp/FreeCodeCamp#2206]
I joined freecodecamp.com today (19 Aug ~8pm IST).
No doubt it's a wonderful site and I got a bit addicted and completed many waypoints mainly under bootstrap and Jquery. Now the funny part is when I see my current streak count in the profile page, it shows me:

Longest Streak: 49 days            Current Streak: 49 days

Also in the star image it shows me 48 which happens to be the "no of waypoints i have completed"
<img width="1680" alt="screen shot 2015-08-19 at 9 38 23 pm" src="https://cloud.githubusercontent.com/assets/5960743/9361812/e7b3fcf2-46ba-11e5-934a-467c8f53b85a.png">

**Comment by michael-krebs** [comment]
this should be fixed soon with PR #2023
