### ISSUE TITLE
Help Button Broken

### ISSUE THREAD

**Issue by CoderNurse** [FreeCodeCamp/FreeCodeCamp#2207]
Challenge http://www.freecodecamp.com/challenges/waypoint-sift-through-text-with-regular-expressions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The Help button doesn't take you to the help room.

**Comment by bugron** [comment]
Related to: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2038
