### ISSUE TITLE
#39 has and issue with correct div placement

### ISSUE THREAD

**Issue by creativehamlet** [FreeCodeCamp/FreeCodeCamp#2208]
```<div
<p>Click here for <a href="#">cat photos</a>.</p>

needs to be

<div>
<p>Click here for <a href="#">cat photos</a>.</p>
</div>

**Comment by benschenker** [comment]
Closing as stale, 
Please reopen this if you still experience this issue.

Take a look at our [Bug Posting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug).
