### ISSUE TITLE
Minor issue in  Waypoint 52

### ISSUE THREAD

**Issue by rodutty** [FreeCodeCamp/FreeCodeCamp#2209]
Challenge http://www.freecodecamp.com/challenges/waypoint-override-class-declarations-with-inline-styles has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Hi Guys, 

I think I completed the challenge, but I'm getting a "Cannot read property 'length' of null".

See attached screen shot. 

Cheers,
<img width="1480" alt="screen shot 2015-08-19 at 22 08 48" src="https://cloud.githubusercontent.com/assets/2548866/9362680/a1d6eae6-46bf-11e5-9a40-b440caa65f04.png">

Rob

**Comment by michael-krebs** [comment]
Your code reads `style="color :white"` and it should be `style="color: white"`. Please check with someone in the Gitter help chat before submitting an issue!

**Comment by rodutty** [comment]
Ah. Thanks, will check there next time...
