### ISSUE TITLE
Adding Comment Comments Out All Code

### ISSUE THREAD

**Issue by tpolcyn** [FreeCodeCamp/FreeCodeCamp#2210]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-comments-to-clarify-code has an issue.

If I create a new line at the top of the code block and add my comment tag () at the end of the code block, thus commenting out the entire code block.

![comment](https://cloud.githubusercontent.com/assets/13574165/9362923/ff960722-4668-11e5-8b16-4fd85805774a.png)

Typing in the requisite statement will then produce a success message, but when you go to the next lesson the comment is restricted to the single line (as I believe this lesson intends.)

Additionally, after typing the comment tag, the cursor moves to the first character at the top of the page, which is inconsistent with other tag character generation.

So, in my opinion, the done statement would include:

1. Fix comment tags such that the end tag is automatically placed one space after the open tag (on the same line) (may be a problem with comment tags in general)
2. Fix comment tags such that the cursor remains immediately following the open comment tag.  (may be a problem with comment tags in general)
3. (May not be necessary if 1 and 2 are fixed) Add another task such that all original code must remain uncommented.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2115
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2075

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
