### ISSUE TITLE
[Grammar] - "Waypoint: Generate Random Whole Numbers with JavaScript"

### ISSUE THREAD

**Issue by AlexWulkan** [FreeCodeCamp/FreeCodeCamp#2216]
The text says:
"It's great that we can create random decimal numbers, but it's even more useful *if we lot more useful* to generate a random whole number."

I think the text should be:
"It's great that we can create random decimal numbers, but it's even more useful to generate a random whole number."

**Comment by issyl0** [comment]
Thanks for reporting this. It's been fixed in https://github.com/FreeCodeCamp/FreeCodeCamp/commit/87c01aae522404a8c9879cd08357a5afc148be0c. :+1:
