### ISSUE TITLE
Bug on JS waypoint

### ISSUE THREAD

**Issue by Noblelynx** [FreeCodeCamp/FreeCodeCamp#2217]
Challenge http://freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In the second part of the challenge, where you're required to create a multi-line comment, if you were to spread that comment across multiple lines, the challenge would not allow you to pass even though the answer is technically correct.

Eg:

/*

This is a multi-line comment

*/
![bug](https://cloud.githubusercontent.com/assets/6572101/9364247/626cc470-4679-11e5-9d06-e408d54e0b41.PNG)

**Comment by benschenker** [comment]
Thanks for reporting! This issue has already been reported and is in the process of being fixed.  See PR #2185 which should fix the issue.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2179
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2141
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2077
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1999
