### ISSUE TITLE
Wrong tip

### ISSUE THREAD

**Issue by nikitin2009** [FreeCodeCamp/FreeCodeCamp#2218]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

After this code:
```javascript
var ourArray = ["Stimpson", "J", ["cat"]];
ourArray.shift();
ourArray.unshift(["happy", "joy"]);
```
`ourArray` should be equal to `[["happy", "joy"], "J", ["cat"]]`.
Not to `[["happy", "joy"], "Stimpson", "J"]`
![screenshot_3](https://cloud.githubusercontent.com/assets/9296248/9364518/67d4eece-46b5-11e5-99fa-9275c85784a3.png)

**Comment by dokkillo** [comment]
working in this issue

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2162
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2150
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2008
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1829
Fixed.
