### ISSUE TITLE
Wrong guideline in code comments

### ISSUE THREAD

**Issue by nikitin2009** [FreeCodeCamp/FreeCodeCamp#2219]
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-within-a-range has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In that waypoint we have to return a random number between **min** and **max** that we have, not between **zero** and **nine** (I suppose it is kept on from previous waypoint)
![screenshot_4](https://cloud.githubusercontent.com/assets/9296248/9365279/5e1f7b84-46b9-11e5-9eeb-38bd351bad1b.png)

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2218
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2162
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2150
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2008
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1829
Fixed.
