### ISSUE TITLE
Misleading formulation

### ISSUE THREAD

**Issue by AnselmeKotchap** [FreeCodeCamp/FreeCodeCamp#2223]
Challenge http://freecodecamp.com/challenges/waypoint-create-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I seems the first task should is not wrongly formulated:
Add two div elements inside your <div class="well"> element both with the class col-xs-6

It should rather be:
Add two div elements inside your <div class="col-xs-6">  element both with the class well

**Comment by benschenker** [comment]
It looks like this has been fixed, Thanks!
