### ISSUE TITLE
the output of set of symmetric difference should not have a prescribed order

### ISSUE THREAD

**Issue by alf808** [FreeCodeCamp/FreeCodeCamp#2224]
Challenge http://www.freecodecamp.com/challenges/bonfire-symmetric-difference has an issue.

The output set should be "equal" with same elements, e.g. [3, 4, 5] = [3, 5, 4] irrespective of order. This was discussed in issue #1402 with respect to this simple definition as defined in https://proofwiki.org/wiki/Definition:Set_Equality:
#### Two sets are equal iff they contain the same elements:  ∀x:(x∈A⟺x∈B)⟺A=B
which clearly indicates that ordering is not prescribed.

The code that I run to reproduce the output is the following:
```javascript
function clean(arr) {
  var unique = [];
  arr.forEach(function(elem) {
    if (unique.indexOf(elem) === -1) {
      unique.push(elem);
    }
  });
  return unique;
}

function sym(arr) {
  // eliminate dups and flatten combined array
var uniqueArr = [];
    uniqueArr = [].slice.call(arguments)
  .reduce(function(arr1,arr2){
    clean(arr2).forEach(function(elem){
      arr1.push(elem);
    });
    return arr1;
  }, []);
  // count frequencies of unique elements
  var howMany = uniqueArr.reduce(function (acc, curr) {
    if (typeof acc[curr] == 'undefined') {
      acc[curr] = 1;
    } else {
      acc[curr] += 1;
    }
    return acc;
  }, {});
  // if frequency is odd-numbered then part of symDiff set
  var symDiff = [];
  for (var obj in howMany) {
    if ((howMany[obj] % 2 !== 0) && !isNaN(obj)) symDiff.push(+obj);
  }
  return symDiff;
}
```
Unfortunately, I continue to get these assertion messages:
![screen shot 2015-08-19 at 20 57 15](https://cloud.githubusercontent.com/assets/79753/9366017/197516d2-46b5-11e5-8aeb-879d363ef2a9.png)

**Comment by ahstro** [comment]
Fixed in #2912; closing.
