### ISSUE TITLE
Pomodoro Clock Completion Button

### ISSUE THREAD

**Issue by Brad--** [FreeCodeCamp/FreeCodeCamp#2225]
'I've completed this challenge' button isn't responding!
![bug-1](https://cloud.githubusercontent.com/assets/7821335/9366756/77f13a0e-4676-11e5-855c-5f160301f581.png)

**Comment by benschenker** [comment]
Hey @Brad-- thanks for posting!

I can't replicate this... I'm going to close this issue but feel free to reopen if you keep experiencing this.
