### ISSUE TITLE
Bug in Chrome 44 in challenge 39 of Basic JavaScript

### ISSUE THREAD

**Issue by ramonhur** [FreeCodeCamp/FreeCodeCamp#2227]
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. 
Whenever i write $($) to begin the exercise, the browser crashes.
Im using Chrome 44.0.2403.155 an Windows 10.
When using Firefox 40.0, im not able to reproduce the bug.

![bug](https://cloud.githubusercontent.com/assets/7885755/9367350/274404f0-46bd-11e5-9b56-b8d50e959ad0.png)

**Comment by arxene** [comment]
Duplicate #2286

**Comment by benschenker** [comment]
Thanks for posting this issue @ramonhur!

As @arxene mentioned, this is a duplicate issue so we can go and close this one.

Take a look at our [Bug Reporting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) for future issues you encounter.
