### ISSUE TITLE
Not accepting closing tags for code

### ISSUE THREAD

**Issue by misterrorypond** [FreeCodeCamp/FreeCodeCamp#2229]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I can get all tests to pass but last - it will not accept my closing tags no matter what!
![scriptclose](https://cloud.githubusercontent.com/assets/11319764/9368776/ea353bd8-468a-11e5-9ae5-9cc5ca42d571.png)

FIX - i can only get it to work with odd spacings
![fix](https://cloud.githubusercontent.com/assets/11319764/9368841/5c5e4f2e-468b-11e5-8265-21899fae8d98.png)

**Comment by benschenker** [comment]
Thanks for reporting this! Confirmed: [this](https://regex101.com/r/kZ7vD5/1) shows that the regex is only matching when there is whitespace before the `});`

Is there any reason why it requires the whitespace to be there?  Why not just assert the presence of the `});` with a regex like: [`/\}\);/`](https://regex101.com/r/fR1bW4/1)?

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2081
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1953
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1858
