### ISSUE TITLE
Bug/waypoint-give-a-background-color-to-a-div-element 

### ISSUE THREAD

**Issue by oanaariana** [FreeCodeCamp/FreeCodeCamp#2230]
Challenge http://freecodecamp.com/challenges/waypoint-give-a-background-color-to-a-div-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
The button "Go to the next challenge" doesn't work, although i completed my challenge.

**Comment by benschenker** [comment]
Hey @oanaariana thanks for posting this!

We had a bunch of issues about this functionality a couple of weeks ago but most seemed to be fixed (and I cannot replicate this one) so I am going to close this as stale.  Feel free to reopen this if you can replicate
