### ISSUE TITLE
Javascript #1 shows some inner site code in instructions

### ISSUE THREAD

**Issue by maciejsartys** [FreeCodeCamp/FreeCodeCamp#2231]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. 

Instructions on left side have some texts that shouldn't be visible (assert(editor.getValue().match(/(\/\/)...../g), 'Create a \/\/ style comment that contains at least five letters');)

![screen shot 08-19-15 at 11 03 pm](https://cloud.githubusercontent.com/assets/1087713/9368982/b6627c94-46c6-11e5-8fc7-3f6d57d2d20a.PNG)

**Comment by benmcmahon100** [comment]
They should be showing up there. It's part of all the javascript based challenges that you are able to see the tests that are running against your code

**Comment by maciejsartys** [comment]
"undefined" field also ?

**Comment by benschenker** [comment]
Correct, `undefined` is the result of running your function (which happens to not return anything)

**Comment by maciejsartys** [comment]
Ok, I understand. But I think this should be described somehow, this looks confusing to me.
