### ISSUE TITLE
bug basic javascript waypoint #32

### ISSUE THREAD

**Issue by brian-peterson** [FreeCodeCamp/FreeCodeCamp#2232]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-conditional-logic-with-ifelse-statements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

``` bash
function myFunction(){
  var flip = Math.floor(Math.random() * (1 - 0 + 1)) + 0;
  // Create and if else statement here to return "heads" if flip is 0. Otherwise return "tails".
  if (flip === 0) {
    return("heads");
  } else {
    return("tails");
  }
  // Only change code below this line.

}

// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
(function(){return(myFunction());})();
```
If using double quotes for <b>heads</b> and <b>tails</b> the <i>if statement</i> will not pass.

![screen shot 2015-08-19 at 4 06 47 pm](https://cloud.githubusercontent.com/assets/10587305/9369036/5fb219e8-468c-11e5-9c63-8f9dd288f646.png)

Using single quotes for <b>heads</b> and <b>tails</b> the <i>if statement</i> will pass

```bash
function myFunction(){
  var flip = Math.floor(Math.random() * (1 - 0 + 1)) + 0;
  // Create and if else statement here to return "heads" if flip is 0. Otherwise return "tails".
  if (flip === 0) {
    return('heads');
  } else {
    return('tails');
  }
  // Only change code below this line.

}

// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
(function(){return(myFunction());})();
```
![screen shot 2015-08-19 at 4 11 50 pm](https://cloud.githubusercontent.com/assets/10587305/9369185/2df9abfe-468d-11e5-96c7-fad8336a5868.png)

**Comment by benschenker** [comment]
Hey thanks for reporting this!  This was already reported in #1974 so check out the explanation there, but the fix is pending in Pull Request #2158
