### ISSUE TITLE
Example issue | 9th jQuery challenge

### ISSUE THREAD

**Issue by Crysicia** [FreeCodeCamp/FreeCodeCamp#2233]
Challenge http://freecodecamp.com/challenges/waypoint-disable-an-element-using-jquery has an issue. 

Here's how you would disable all buttons: $('#button').prop('disabled', true);

Should be :
Here's how you would disable all buttons: $("button").prop('disabled', true);

**Comment by benschenker** [comment]
Hey thanks for submitting this!  Someone else posted this issue too: See #2014 for more info, it seems like this will be fixed with Pull Request #2018
