### ISSUE TITLE
Hi. In this chalenge you need "Your target6 element should have green text." but it is not correct because all child elements become green.

### ISSUE THREAD

**Issue by Acidsky** [FreeCodeCamp/FreeCodeCamp#2234]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey can you post a screenshot to show exactly what you have typed in?

Is it possible that you set the css for `background-color` to green instead of `color`?

**Comment by Acidsky** [comment]
here is.
![screenshot from 2015-08-20 16 15 29](https://cloud.githubusercontent.com/assets/13290212/9384145/056e9b02-4757-11e5-8890-4cec67975bc5.png)

**Comment by benschenker** [comment]
You got it right!
That should be showing up there. It's part of all the javascript based challenges that you are able to see the tests that are running against your code.  See #2231 for a similar issue/explanation.

**Comment by rowansen** [comment]
I think what he is trying to say is that all the text are green and not the"#target6" as in the challenge. It is a bit confusing
![right-well](https://cloud.githubusercontent.com/assets/13391111/9488572/5135a7dc-4bdb-11e5-9832-8b5c51120be7.PNG)

**Comment by benschenker** [comment]
I see, thanks for clarifying @rowansen!

I believe `#target6` is just meant to be one example to prove that the children are being selected.  How would you change this to be clearer?  Would you want the test to check 4, 5, and 6?

**Comment by Boolean-Operator** [comment]
Perhaps if the phrase 'Your target 6 element should...' was changed to 'Your right-well elements should...' it would be a bit more in line with the instructions in the upper paragraph.

**Comment by jwjb** [comment]
Still seeing the same issue per below screenshot.

![screen shot 2015-09-08 at 8 02 07 am](https://cloud.githubusercontent.com/assets/3523591/9738470/8d609ecc-5600-11e5-8739-d6b152236b73.png)

**Comment by benschenker** [comment]
Thanks @jwjb, this issue has not yet been closed so it is still on the backlog of items to be fixed.

**Comment by bugron** [comment]
Closing this issue because it is [fixed](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/jquery.json#L686) in staging.

**Comment by jwjb** [comment]
@benschenker and @bugron Awesome and thanks for posting [fixed](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/jquery.json#L686) as it not only helps in understanding the fixing of this issue, but gives a glimpse under-the-hood of the actual code and some great test examples using `assert` to help with our coding skills.
