### ISSUE TITLE
Here is screenshot.

### ISSUE THREAD

**Issue by Acidsky** [FreeCodeCamp/FreeCodeCamp#2236]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
https://drive.google.com/file/d/0B4BoAahPWxNCZmFhQk16WUtuMjQ/view?usp=sharing

**Comment by dokkillo** [comment]
what waypoint?

**Comment by benschenker** [comment]
It looks like you got it right!

Are you pointing out that it looks like an error message next to those checkmarks?  That is actually normal, as you should see what test you are actually passing.  See #2231 for more.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2231
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2217
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2179
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2141
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2077
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1999
