### ISSUE TITLE
Incorrect description of parent-child inheritance

### ISSUE THREAD

**Issue by jangeroo** [FreeCodeCamp/FreeCodeCamp#2238]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. The first sentence of the text is incorrect. `Many HTML elements have children elements from which they inherit properties` should read `Many HTML elements have children elements which inherit their properties`. Children inherit from parents, not the other way around.

**Comment by dokkillo** [comment]
working in it

**Comment by benschenker** [comment]
Thanks for posting this!

This is a duplicate of #2065 so keep an eye there for updates on this.
