### ISSUE TITLE
Unknown Windows/connect-mongo bug

### ISSUE THREAD

**Issue by jameskopacz** [FreeCodeCamp/freecodecamp#224]
When running the gulp command, the browser launches and I get an error:

> 500 Error: Error getting collection: sessions
> at \freecodecamp\node_modules\connect-mongo\lib\connect-mongo.js:160:19

Refreshing "fixes" the problem. If gulp auto reloads the project it's also fine. If I rerun the "gulp" command the error happens again.

What it looks like is happening is the browser is being launched before the following is actually ready:
```javascript
app.use(session({
    resave: true,
    saveUninitialized: true,
    secret: secrets.sessionSecret,
    store: new MongoStore({
        url: secrets.db,
        'auto_reconnect': true
    })
}));
```
MongoStore has a callback and If I move the following code into it, the problem is fixed:
```javascript
/**
 * Start Express server.
 */
app.listen(app.get('port'), function () {
    console.log(
        'FreeCodeCamp server listening on port %d in %s mode',
        app.get('port'),
        app.get('env')
    );
});
```

**Comment by BerkeleyTrue** [comment]
I have updated the title to better describe the issue. We have a good assumption that the issue stems from windows systems. It might be an issue with connect-mongo and windows or windows and mongodb driver. More investigation will need to be conducted to better understand the problem.

**Comment by jameskopacz** [comment]
What version of connect-mongo do you guys have?

**Comment by BerkeleyTrue** [comment]
0.7.0

**Comment by jameskopacz** [comment]
npm install is giving me "0.4.2". The package.json says "^0.4.1". How did you get 0.7.0?

But that's the fix. To update to 0.7.0.

**Comment by BerkeleyTrue** [comment]
I updated. Haven't committed.
