### ISSUE TITLE
bonfire-false-bouncer description is incorrect

### ISSUE THREAD

**Issue by lewallep** [FreeCodeCamp/FreeCodeCamp#2240]
In the description of the problem it says "Falsey values in javascript are false, null, 0, "", undefined, and NaN."  Remove all Falsey values.  The link to this is here, http://freecodecamp.com/challenges/bonfire-falsey-bouncer
In the first array provided to test there is a string, 'ate' which is supposed to be returned.  However a string is Not a Number so when it is tested this returns false and is discarded and the test fails. 
  I think this problem description needs to be reworded to keep strings and not discard all Not all Number values.  My code and the screen is attached.
![bug_001_screenshot](https://cloud.githubusercontent.com/assets/8976842/9370671/d14d4466-4686-11e5-9107-7b018ba5585c.jpg)

**Comment by benschenker** [comment]
Hey @lewallep thanks for posting this issue!

Read the [documentation on isNan](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN) carefully as it uses type coercion.

See the example there
```
// This is a false positive and the reason why isNaN is not entirely reliable
isNaN("blabla")   // true: "blabla" is converted to a number. 
                  // Parsing this as a number fails and returns NaN
```

Take a look at the [wiki page for this bonfire](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/bonfire-falsey-bouncer) for some help in the right direction.
