### ISSUE TITLE
Code editor missing <script> tags

### ISSUE THREAD

**Issue by jangeroo** [FreeCodeCamp/FreeCodeCamp#2242]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-javascript-slot-machine has an issue.

The four Javascript slot machine exercises all display the JS section of the code incorrectly. Presumably `fccss` is supposed to be `<script>`, and likewise `fcces` is supposed to be `</script>`.

<img width="1969" alt="screen shot 2015-08-19 at 7 11 54 pm" src="https://cloud.githubusercontent.com/assets/5023165/9371847/695d7f04-46a6-11e5-9ed0-8600b29b6c44.png">

**Comment by SaintPeter** [comment]
I am working this issue.  Pull Request coming soon.

**Comment by RobRoseKnows** [comment]
How could this even happen?

**Comment by SaintPeter** [comment]
The problem is that it's really hard to embed `</script>` into Javascript.  This is a non-trivial fix.

**Comment by RobRoseKnows** [comment]
I didn't realize that. I guess it makes sense since that could probably be used maliciously.

**Comment by benschenker** [comment]
This has been fixed, thanks!
