### ISSUE TITLE
Validator not accepting single quotes around selector

### ISSUE THREAD

**Issue by jangeroo** [FreeCodeCamp/FreeCodeCamp#2245]
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue.

Using `$($('.slot')[0]).html(slotOne);` with single quotes rather than double quotes is not accepted by the validator.

**Comment by benschenker** [comment]
Hey @jangeroo  thanks for posting this.

We have a few duplicate postings of this so see #2522 for updates on this issue.

Please close this as a duplicate, and take a look at our [Bug Report Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug).
