### ISSUE TITLE
Slash in <img> tag before closing angle bracket

### ISSUE THREAD

**Issue by padamson** [FreeCodeCamp/FreeCodeCamp#2246]
Challenge http://freecodecamp.com/challenges/waypoint-add-alt-text-to-an-image-for-accessibility has following issue:

There is a slash that shouldn't be there before the closing angle bracket in the example: `<img src="www.your-image-source.com/your-image.jpg" alt="your alt text"/>`.

**Comment by benschenker** [comment]
Hey @padamson thanks for posting this issue!

That slash is actually used to close the image tag as it has no closing tag `</img>`.

See http://stackoverflow.com/questions/14860492/how-to-close-img-tag-properly for more info
