### ISSUE TITLE
Instructions repeated from previous exercise

### ISSUE THREAD

**Issue by garysmeade** [FreeCodeCamp/FreeCodeCamp#2249]
Challenge http://www.freecodecamp.com/challenges/waypoint-iterate-with-javascript-while-loops has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The While Loop Waypoint directs the user to create a for loop rather than a while loop.

![image](https://cloud.githubusercontent.com/assets/13364192/9372621/fdbdbf74-4723-11e5-9ba9-3d9cfd6eb8b7.png)

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2112
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2107
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2087
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2040
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1987
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1958
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1945
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1932
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1802

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
