### ISSUE TITLE
Changes <script> and </script> to other characters 

### ISSUE THREAD

**Issue by markvjames** [FreeCodeCamp/FreeCodeCamp#2250]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When lessons in this section are loaded the <script> and </script> tags are changing to other characters.  Might just be a browser issue(?)  Safari 8.0.8 - OS X 10.10.5
![screen shot 2015-08-19 at 5 16 51 pm](https://cloud.githubusercontent.com/assets/13261325/9372687/5a01aeb4-4696-11e5-9942-6bbb3c362720.png)

**Comment by RobRoseKnows** [comment]
I'm having a similar issue on http://www.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery

**Comment by benschenker** [comment]
Hey thanks for filing an issue.  Take a look at #2242 which reports the same issue too.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate #2242
