### ISSUE TITLE
the script tag apears as fccss.

### ISSUE THREAD

**Issue by verdugoperez** [FreeCodeCamp/FreeCodeCamp#2251]
Challenge http://freecodecamp.com/challenges/waypoint-use-appendto-to-move-elements-with-jquery has an issue. Please describe how to repro
![fccss](https://cloud.githubusercontent.com/assets/8240234/9372872/f8adc98a-46a0-11e5-8003-4349fbb51bf7.jpg)
duce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Thanks for reporting this!  Looks like its already being worked on in #2242

**Comment by BerkeleyTrue** [comment]
Closing as duplicate #2242
