### ISSUE TITLE
There's a typo on this page.

### ISSUE THREAD

**Issue by calskin** [FreeCodeCamp/FreeCodeCamp#2252]
Challenge http://freecodecamp.com/challenges/waypoint-manipulate-javascript-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

"There are many ways to add and ****add and**** remove properties from objects."

**Comment by dokkillo** [comment]
Hi, this issue is fixed but its waiting for deployment in production.

Regards

**Comment by calskin** [comment]
Thanks

**Comment by dokkillo** [comment]
@calskin  can you close this issue? :)
