### ISSUE TITLE
Bonfire chunky monkey page freezes

### ISSUE THREAD

**Issue by cyclehacker** [FreeCodeCamp/FreeCodeCamp#2253]
Challenge http://freecodecamp.com/challenges/bonfire-chunky-monkey has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The way I reproduce it is to just select it from the map menu. I think it has something to do with the code I have entered to solve the task. When I originally ran the code the page crashed, now, every time I return to the page the code is still there and once the page loads it freezes. I have tried pressing the reset button to clear the code but the page freezes before the confirmation popup fully pops up, so I can confirm the reset.

I think I just need the code to be reset from you end and the page should work.

Many thanks,

Fraser

**Comment by jbmartinez** [comment]
Try clearing the cache in your browser.

This may be related to #1960

**Comment by SmikeyR** [comment]
I had similar problem. Clearing the cache solved it.
