### ISSUE TITLE
Waypoint: Remove Classes from an element with jQuery

### ISSUE THREAD

**Issue by FaithKent** [FreeCodeCamp/FreeCodeCamp#2254]
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The issues appeared as soon as I opened the waypoint. All the javascript text was white and it had FCCSS at the beginning and FCCES at the end. I tried removing the FCCSS and FCCES and then following the directions but the text remained all white and did not complete the waypoint. I reset things to the way I found them to get a screenshot.
![screen shot 2015-08-19 at 5 39 35 pm](https://cloud.githubusercontent.com/assets/13058060/9372990/f56e0c46-4699-11e5-83c8-25489dcbdb1b.png)
![screen shot 2015-08-19 at 5 45 44 pm](https://cloud.githubusercontent.com/assets/13058060/9373026/3bdc36da-469a-11e5-90b0-7b2bc94a7df5.png)
![screen shot 2015-08-19 at 5 46 41 pm](https://cloud.githubusercontent.com/assets/13058060/9373027/3d0e5f92-469a-11e5-8936-2e43e1509f09.png)

**Comment by benschenker** [comment]
Hey thanks for letting us know!  Looks liek this is already being worked on, follow the progress at #2242

**Comment by BerkeleyTrue** [comment]
Closing as duplicate #2242
