### ISSUE TITLE
I have even tried cutting and pasting the example and I get check marks 1,2 and 4 but even after chnging the wording of red to blue, check mark 3 won't turn green.

### ISSUE THREAD

**Issue by snipaw26** [FreeCodeCamp/FreeCodeCamp#2255]
Challenge http://freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey thanks for posting, can you post a screenshot of the issue and the code that produces it?

**Comment by benschenker** [comment]
Closing as stale, feel free to reopen with updates

**Comment by symolloy** [comment]
Same problem

<style>h2 {color: blue;}</style>
CatPhotoApp

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
 
#3 will not highlight even when I put in exactly the format indicated in the example
