### ISSUE TITLE
Previous waypoints as well as this one have the "fccss syndrome" whereby <(/)script> would be replaced by fccss

### ISSUE THREAD

**Issue by deaninous** [FreeCodeCamp/FreeCodeCamp#2259]
Challenge http://freecodecamp.com/challenges/waypoint-use-appendto-to-move-elements-with-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Thanks for posting an issue,

This is a duplicate of #2242 and others though in general try the following:

If you’re having trouble with JavaScript or jQuery challenges, do a hard refresh and it will fix them. (in Chrome: CTRL + Shift + R on Windows or CMD + Shift + R on mac)

**Comment by BerkeleyTrue** [comment]
Closing as duplicate #2242
