### ISSUE TITLE
waypoint use appendto to move elements with jQuery has script tag issue

### ISSUE THREAD

**Issue by patrickmac110** [FreeCodeCamp/FreeCodeCamp#2260]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-appendto-to-move-elements-with-jquery has an issue. 
script tags appear as fccss
![screenshot 2015-08-19 at 9 38 15 pm](https://cloud.githubusercontent.com/assets/5874812/9373649/b87437e0-46ba-11e5-8734-6e0ef4156892.png)

**Comment by benschenker** [comment]
Thanks for posting this issue!  Take a look at #2242 as it looks like someone is working on the problem there.  Also see if following these instructions help:

If you’re having trouble with JavaScript or jQuery challenges, do a hard refresh and it will fix them. (in Chrome: CTRL + Shift + R on Windows or CMD + Shift + R on mac)

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
