### ISSUE TITLE
Incorrect comparison symbol

### ISSUE THREAD

**Issue by garysmeade** [FreeCodeCamp/FreeCodeCamp#2261]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-conditional-logic-with-ifelse-statements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This waypoint displays the equals comparison sign as "==" which is see as incorrect by the editor.

![image](https://cloud.githubusercontent.com/assets/13364192/9373727/0244e1be-4731-11e5-9c6f-75eae06de79c.png)

**Comment by bugron** [comment]
Dear camper, it seems that this issue is resolved so you can close it.
