### ISSUE TITLE
Button does nothing

### ISSUE THREAD

**Issue by zkparks11** [FreeCodeCamp/FreeCodeCamp#2263]
Challenge http://www.freecodecamp.com/challenges/waypoint-understand-boolean-values has an issue. I'm using mircosoft edge as my browser, and the page doesn't give me any bulleted tasks to complete, and the run button is highlighted, but doesn't work.

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate and already solved:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1882

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
