### ISSUE TITLE
Page froze on me

### ISSUE THREAD

**Issue by ninjatc** [FreeCodeCamp/FreeCodeCamp#2264]
Challenge http://freecodecamp.com/challenges/bonfire-reverse-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Cannot reset code, page is frozen on me.

**Comment by benschenker** [comment]
Thanks for posting an issue,

Try the following:

If you’re having trouble with JavaScript or jQuery challenges, do a hard refresh and it will fix them. (in Chrome: CTRL + Shift + R on Windows or CMD + Shift + R on mac)

**Comment by ninjatc** [comment]
I tried refreshing / resetting code / signing out / closing Chrome, none worked.

**Comment by BerkeleyTrue** [comment]
Try opening 'freecodecamp.com' open your console and go to `resources` tab(chrome). There click on the localStorate link in the nav bar on the right. Delete all the entries on the right side. Then navigate to the challenge. This removes all your local stored challenges. 

![learn_to_code_javascript_and_get_a_coding_job_by_helping_nonprofits___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/9448820/911626ee-4a53-11e5-98c9-b2bf4ca50816.png)

**Comment by benschenker** [comment]
It seems that this has been resolved.  I'll close this but feel free to reopen if you still experience this issue.

**Comment by ninjatc** [comment]
Thank you!!

**Comment by Devcnn5** [comment]
just find the page of the challenge and modify the address a bit.
Add "#?solution=%0A%0A" in front of the challenge address.This won't remove the progress you've made on other challenges.
![chunky-monkey](https://cloud.githubusercontent.com/assets/10836749/24055129/e8ba54aa-0b64-11e7-8c9d-3d60d7be20da.jpg)

**Comment by Giveback007** [comment]
Thank you @Devcnn5 you just saved my life. I was actually frozen on that exact challenge.
