### ISSUE TITLE
Nit-picking grammar

### ISSUE THREAD

**Issue by JoeCool1971** [FreeCodeCamp/FreeCodeCamp#2265]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

"point to an specific image's URL"

Should be "point to a specific image's URL"

**Comment by dokkillo** [comment]
working in this issue

**Comment by benschenker** [comment]
This has been fixed, thanks!
