### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by daniel-chung** [FreeCodeCamp/FreeCodeCamp#2267]
Challenge http://www.freecodecamp.com/challenges/waypoint-iterate-with-javascript-while-loops has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The description asks users to use a for loop, rather than a while loop. See the text highlighted in blue below:

![screen shot 2015-08-19 at 10 35 24 pm](https://cloud.githubusercontent.com/assets/8076334/9374297/9c60e23a-46c2-11e5-87dc-7ecf5d4c1265.png)

**Comment by issyl0** [comment]
Thanks for the report! I fixed this issue in https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2505, so it should be live soon!

**Comment by BerkeleyTrue** [comment]
merged

**Comment by daniel-chung** [comment]
I'm glad I could (in a very minor way) help! I'll be keeping my eyes out for more bugs.
