### ISSUE TITLE
Entire basic javascript session is showing assertions in javascript

### ISSUE THREAD

**Issue by pedrobastosz** [FreeCodeCamp/FreeCodeCamp#2269]
Challenge http://www.freecodecamp.com/challenges/waypoint-store-multiple-values-in-one-variable-using-javascript-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The entire section 'Basic JavaScript' is showing the assertions code (ex: assert(typeof(myArray) ) on the left side of the textual assertion (see below):

![captura de tela 2015-08-19 23 45 08](https://cloud.githubusercontent.com/assets/11931753/9374469/a39fa8ec-46cc-11e5-9fb5-16441a1490ca.png)

**Comment by Harmitage** [comment]
As I've been told couple of hours ago, it's made on purpose, to make it more easy, to solve this tasks.

**Comment by pedrobastosz** [comment]
Actually it makes a lot of sense for me, but for people who has never witten javascript code, could be a little bit confusing (IMHO).
