### ISSUE TITLE
Wrong spelling

### ISSUE THREAD

**Issue by luis-fonseca** [FreeCodeCamp/FreeCodeCamp#2271]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-colors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Exercise has a wrong spelling in this part: "With CSS, we use 6 **hexidecimal** number to represent colors."

**Comment by dokkillo** [comment]
Ok!

Working with this issue!

**Comment by benschenker** [comment]
This has been fixed, thanks!
