### ISSUE TITLE
Page frozen and will not refresh

### ISSUE THREAD

**Issue by BillKroger** [FreeCodeCamp/FreeCodeCamp#2272]
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. The page is frozen and I can't refresh it. I'm using Chrome on a Mac so I tried the hard refresh (CMD + Shift + R) and nothing happens. I tried logging out and logging back in, using different browsers, etc. and the page is still frozen every time I open it up.

![waypoint-bring-your-javascript-slot-machine-to-life](https://cloud.githubusercontent.com/assets/12553015/9375012/bd6ba51c-46b0-11e5-817a-38d00a46d4df.png)

**Comment by bugron** [comment]
Dear camper, your issue is related to: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2264

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Comment by benschenker** [comment]
Hey @BillKroger thanks for posting this issue!

The main thread is actually #1960.  Chances are your unfinished solution (which is crashing your browser) is actually saved to you account.  I'm not sure there is any way to delete the saved solution yet, but you can probably just move on to the next challenge for now.

**Comment by benschenker** [comment]
Try hitting the Reset button on the page on the left

**Comment by BerkeleyTrue** [comment]
Try opening 'freecodecamp.com' open your console and go to resources tab(chrome). There click on the localStorate link in the nav bar on the right. Delete all the entries on the right side. Then navigate to the challenge. This removes all your local stored challenges.

![learn_to_code_javascript_and_get_a_coding_job_by_helping_nonprofits___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/9448854/d47b5e86-4a53-11e5-90dd-3b856d01a559.png)

@benschenker Could you relay this information to others that are running into this issue?

**Comment by benschenker** [comment]
@BerkeleyTrue I put it in a wiki page! https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser's-Local-Storage  Right now it only has your chrome instructions though.

**Comment by BerkeleyTrue** [comment]
FF is similar except you need to do it in the command line one by one which is a pain.
