### ISSUE TITLE
Waypoint: Target a Specific Child of an Element Using jQuery

### ISSUE THREAD

**Issue by tjkampa** [FreeCodeCamp/FreeCodeCamp#2273]
It seems the correct code for this exercise should be:
`$('.well:nth-child(2)').addClass('animated bounce');`
But the answer that gets the green check is:
`$('.target:nth-child(2)').addClass('animated bounce');`
with the example class ".target" used.

**Comment by clint74** [comment]
This is happening with me and it seems to be an malformed expression on assert.

**Comment by tjkampa** [comment]
I closed this a few minutes after opening it after I realized my misunderstanding of :nth-child(). I was thinking it should be called on the parent element, but it is called on the children, in this case `<button>` with the class `.target`, so the exercise is correct.

**Comment by arssonist** [comment]
This is a bitch of a question! They really don't make these questions easy. I mean the code is ridiculously simple, but the wording is why the frontend section is set at 50 hours! I never saw that target was a class! 

Thanks for posting this!!
