### ISSUE TITLE
Find Numbers with Regular Expressions

### ISSUE THREAD

**Issue by denmch** [FreeCodeCamp/FreeCodeCamp#2274]
Challenge http://freecodecamp.com/challenges/waypoint-find-numbers-with-regular-expressions has an issue.

Two issues here:

1. Unnecessary use of the ignore case flag
2. Lack of clarity regarding the use of the + operator

As for the ignore case flag, numbers don't have case, so it's superfluous.

As with the previous waypoint (addressed in other issues), the + operator is misunderstood. However, it's probably correctly used here (more below), but it isn't clear to campers why, and the `testString` doesn't contain any numbers that require the + operator.

In the previous waypoint teaches campers that the + operator searches for multiple occurrences of the pattern. This is incorrect, and when they reach this waypoint, they will assume that the + is necessary to find both 3 and 4 in `testString`. But, as in the previous waypoint, the global modifier takes care of this.

In point of fact, the plus operator is necessary to select multi-digit numbers as a single number.

For example, if we change the string to the following

`"There are 9 cats but 10 dogs."`

The expressions `/\d/g` would select three numbers (9, 1, 0), while `/\d+/g` would correctly select two (9, 10).

This is because `\d` says "select digit characters" and the + operator says "any number of them," i.e., if a series of digit characters follow one another without any intervening characters of another type (letters, punctuation, spaces), then they count as one match to the pattern.

If this isn't what's intended, then the + operator should be removed entirely and the instructions clarified to say that campers should write an expression that selects each individual digit character.

**Comment by benschenker** [comment]
Thanks @denmch for posting this!

Point 1 has been fixed already.

Point 2 is completely valid and the `+` operator needs to be explained (your words seem to do the trick)

**Comment by Rahul22587** [comment]
Why its result is coming 2 ?
