### ISSUE TITLE
Invert Regular Expression Matches

### ISSUE THREAD

**Issue by denmch** [FreeCodeCamp/FreeCodeCamp#2276]
Challenge http://freecodecamp.com/challenges/waypoint-invert-regular-expression-matches-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Spaces do not have case so the ignore case flag is superfluous.

**Comment by bugron** [comment]
Dear camper, your issue is related to: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2124 and https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2000.


Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
