### ISSUE TITLE
There is no parrots collection in the learnyoumongo

### ISSUE THREAD

**Issue by thanhacun** [FreeCodeCamp/FreeCodeCamp#2277]
Challenge http://freecodecamp.com/challenges/waypoint-store-data-in-mongodb has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In lesson 3 of the learnyoumongo there is no parrots collection.

![no collection](https://cloud.githubusercontent.com/assets/7599781/9375264/e070df8c-4728-11e5-93b1-1c4abd004101.png)

**Comment by michael-krebs** [comment]
You should submit learnyoumongo issues at https://github.com/evanlucas/learnyoumongo

**Comment by gbhojraj** [comment]
Just for anyone else dropping by and seeing this, the reason learnyoumongo/parrots is empty is because the test generates the database during runtime (learnyoumongo verify) and deletes it after the process ends.

**Comment by kristianjaeger** [comment]
That seems like a poor design for people who want to be able to debug their code and / or experiment with the mongo shell to see what's actually in the db...
