### ISSUE TITLE
Slot Machine fails unless you write redundant code

### ISSUE THREAD

**Issue by denmch** [FreeCodeCamp/FreeCodeCamp#2278]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-javascript-slot-machine has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The example in the first screenshot should pass, but fails because the last test checks to see if the random number formula appears exactly three times.

![screen shot 2015-08-19 at 8 51 21 pm](https://cloud.githubusercontent.com/assets/2019665/9375333/2d56f996-46b4-11e5-9d0a-3ba1f1f588c3.png)

It's more efficient to write a single function that returns a random number and then have each variable call that function.

In fact, it doesn't matter where the formula appears, as long as it appears three times. Here, I passed by repeating it twice in comments.

![screen shot 2015-08-19 at 8 56 47 pm](https://cloud.githubusercontent.com/assets/2019665/9375389/e201c1be-46b4-11e5-87c8-9a63dd181f7c.png)

**Comment by benschenker** [comment]
Thanks for posting this @denmch!

This is similar to #1869 but I think this explains the issue better so I'll close that one and leave this to be fixed.

Code that currently fails but shouldnt:
```
var genRandom = function(){
    return Math.floor(Math.random() * (3 - 1 + 1)) + 1;
};
slotOne = genRandom();
slotTwo = genRandom();
slotThree = genRandom();
```

**Comment by guylemon** [comment]
This still fails with: 

    function getRandom(){
      return Math.floor(Math.random() * (3 - 1 + 1)) + 1
    }
    slotOne = getRandom()
    slotTwo = getRandom()
    slotThree = getRandom()

**Comment by QuincyLarson** [comment]
I just checked @ltegman's pull request and it still doesn't pass with the code @guylemon proposed. I'm closing the PR. @ltegman please get this test case passing and resubmit.
