### ISSUE TITLE
Bring Your Slot Machine to Life requires double quotes to pass

### ISSUE THREAD

**Issue by denmch** [FreeCodeCamp/FreeCodeCamp#2279]
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

There's no syntactic reason to require double quotes. The following should pass, but fails.

```
    $($('.slot')[0]).html(slotOne);
    $($('.slot')[1]).html(slotTwo);
    $($('.slot')[2]).html(slotThree);
```

Switching to double quotes passes.

**Comment by jkulton** [comment]
I just had this happen to me as well. I couldn't figure out for the life of me what was wrong with what I had written.

**Comment by wildlifehexagon** [comment]
Just had the same thing happen to me. Thanks for opening this.

**Comment by benschenker** [comment]
Hey @denmch thanks for posting this.

We have a few duplicate postings of this so see #2522 for updates on this issue.

Please close this as a duplicate, and take a look at our [Bug Report Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug).

**Comment by denmch** [comment]
I know you mean well, but keep in mind that you're asking people who posted 3 or 5 days ago to check the guidelines because someone else who posted 2 days ago got a response. I know the guidelines and follow them. This isn't a perfect process, and we can't predict the future.
