### ISSUE TITLE
Just a little typo in the instructions

### ISSUE THREAD

**Issue by baenaeduardo** [FreeCodeCamp/FreeCodeCamp#2280]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-javascript-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

There are many ways to ****add and add and*** remove properties from objects.

**Comment by dokkillo** [comment]
Hi baenaeduardo

Its duplicated and fixed waiting for deploy in production!

Regards

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
