### ISSUE TITLE
Bug: Add your JavaScript Slot Machine Slots

### ISSUE THREAD

**Issue by Problemphile** [FreeCodeCamp/FreeCodeCamp#2281]
Challenge http://freecodecamp.com/challenges/waypoint-add-your-javascript-slot-machine-slots has an issue. It marks the challenge as completed as soon as I create an "If statement". It does not check whether the if statement is correct.
![bug](https://cloud.githubusercontent.com/assets/13109662/9375568/4e23ed2a-46d0-11e5-80a3-c582e0d2a24e.jpg)

**Comment by airyz** [comment]
I experienced the same.

**Comment by bugron** [comment]
@slackerBoy thanks for posting this issue!
And even more interesting. You don't need to write any code! Keep clicking on button Run code until you get three equal numbers of slots and you pass the test!

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by bugron** [comment]
Closing this issue. Check for any update https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3228, thanks.

**Comment by NelsonDaniel** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/13109662/15872499/a7dc6d46-2cae-11e6-81b2-48d1fb8a6a5c.jpg)


`Hello `
@
# Hello
