### ISSUE TITLE
Failed to Execute

### ISSUE THREAD

**Issue by NakedJack** [FreeCodeCamp/FreeCodeCamp#2282]
![screenshot 2](https://cloud.githubusercontent.com/assets/13881088/9375984/7644a3ce-474a-11e5-8f02-27b4430448f3.png)
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Failed to load and execute

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2236
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2231
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2217
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2179
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2141
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2077
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1999
