### ISSUE TITLE
There are closing tags on both my p elements yet saying there isn't

### ISSUE THREAD

**Issue by LBOS11** [FreeCodeCamp/FreeCodeCamp#2283]
![screenshot 1](https://cloud.githubusercontent.com/assets/13881243/9376138/fe7361d2-46d6-11e5-98d8-a9bee1f64cdc.png)
Challenge http://freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by michael-krebs** [comment]
`<p2>` is not a valid javascript tag. Please post in the Gitter help channel before submitting a bug report!
