### ISSUE TITLE
Suggestion: Waypoint: Use Clockwise Notation to Specify the Margin of an Element

### ISSUE THREAD

**Issue by fidelscodes** [FreeCodeCamp/FreeCodeCamp#2285]
Challenge http://freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue.

Just thought the instructions at the end would benefit from being a bit more specific to prevent the camper having to look at the tests. Something like:

"Use Clockwise Notation to give the element with a class of **green-box** a margin of 40px on its top and left side, but only 20px on its bottom and right side."

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2198

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
