### ISSUE TITLE
Saving feature may save infinite loop

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#2286]
![](https://www.evernote.com/l/AlypWicz0J5M2aPWkyomgpOI7o-DPlu0MtAB/image.png)

**Comment by benmcmahon100** [comment]
Well the simplest and easiest thing to do to fix this would be to move the save feature to the submit function or to add  a submit function to the save so that it will preform an infinite loop detection run. Although it can still miss stuff somtimes

**Comment by benmcmahon100** [comment]
The loop can be block be pausing it in the debugger and running editor.setValue(challengeSeed);

**Comment by benmcmahon100** [comment]
Really the loop should be caught by the editor

**Comment by arxene** [comment]
Workaround: clearing browser cookies may clear the user-entered code. On Chrome I wiped my browser history and I could then refresh the page without my old code showing up.

Reference: [DOM Storage: Storage location and clearing the data](https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Storage#Storage_location_and_clearing_the_data)

**Comment by BerkeleyTrue** [comment]
We now detect infinite loop (most of them anyway)

**Comment by RyanJHolland** [comment]
I had this happen in a few Bonfires. Clearing the cookies from the last day worked, but a faster workaround is to change something in the URL to make the code not work. The code is all contained in the URL. Change a variable name and reload. You may have to copy & paste the URL into a new tab to get it to reload.

**Comment by ezchx** [comment]
I had the same problem and clearing the browsing history worked.

Thanks to arxene!!!

Stupid infinite loops!!!

**Comment by bmorelli25** [comment]
Just had the same problem. Thank you @arxene for the workaround!
