### ISSUE TITLE
Missing test for Factorial Bonfire for factorial(0) to equal 1.

### ISSUE THREAD

**Issue by marksurnin** [FreeCodeCamp/FreeCodeCamp#2287]
<img width="1217" alt="screen shot 2015-08-20 at 11 44 44 am" src="https://cloud.githubusercontent.com/assets/5126685/9377297/e8cde94c-4730-11e5-89f3-36aedc562648.png">

**Comment by marksurnin** [comment]
Created a pull request.

**Comment by awesomeaniruddh** [comment]
OP said they created a pull request. Has this been resolved?

**Comment by marksurnin** [comment]
Yes, closing the issue now.
