### ISSUE TITLE
Go to my next challenge problem

### ISSUE THREAD

**Issue by Vyhnn** [FreeCodeCamp/FreeCodeCamp#2289]
When I was doing the HTML5 and css and responsive design waypoint, there are several times where the next challenge jump to Basic javascript. When I try to go back to previous page and press the next button, it jump to the next challenge of the wrong challenge, even though I haven't finish that challenge.

**Comment by benschenker** [comment]
Hey @Vyhnn thanks for posting!

A couple of weeks ago we had a bunch of issues like this but most were fixed.  I'm going to close this as resolved but feel free to reopen if you still have this issue.
