### ISSUE TITLE
Streak is still broken

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#2290]

**Comment by BerkeleyTrue** [comment]
details

**Comment by dokkillo** [comment]
I think the error is this: Streak says i have 4 days, but really now I only have 3.

![streakerrormin](https://cloud.githubusercontent.com/assets/920841/9378519/6c93f0b4-4722-11e5-960c-c3542a5fb97a.png)

**Comment by BerkeleyTrue** [comment]
got it. Its because I'm rounding up. Will fix

**Comment by dokkillo** [comment]
:+1:

**Comment by zorfa** [comment]
![capture](https://cloud.githubusercontent.com/assets/8377726/9435344/0f646cb4-4a58-11e5-9276-acb542829893.PNG)
The current streak shows 2 days even though I have coded for three days continuously.

**Comment by Rafase282** [comment]
![My Streak](http://i.imgur.com/FxCC22L.jpg)

As you can see mine shows 14 when it should be 35 for longest and current.

**Comment by mamun2015** [comment]
In my profile  showing Longest Streak: 9 days and Current Streak: 3 days.
But it should be both Longest/Current Streak= 13 days.
![screenshot_5](https://cloud.githubusercontent.com/assets/11602663/9751663/3dcd46a2-56c9-11e5-8c4f-d108df107b0a.png)

**Comment by BerkeleyTrue** [comment]
Thank you all for posting. We are aware that streaks are broken for some.

**Comment by terakilobyte** [comment]
Hey folks,

I just wanted to let everyone know we're working on this.

Currently all timestamps are stored on the server, and the streak is calculated there. The server is located in EST. So, based on time offsets it's possible to miss a day.

For example, if you live in PST:
I complete a challenge on Wednesday at 8 PM, which equates to Wednesday at 11PM EST
I complete a challenge on Thursday at 9:01 PM, which equates to Friday at 12:01 AM EST
This results in a Thursday being technically missed.

We're investigating the best way to address this issue and should have a fix soon.

**Comment by GregFoley** [comment]
Current and longest streak are 1 day less than they should be for me.

**Comment by ivancsicsmarkus** [comment]
![kepernyofoto 2017-04-01 - 19 18 39](https://cloud.githubusercontent.com/assets/22645197/24580843/06805c26-1710-11e7-9a1c-d21aa6072d68.png)
... it is still not OK.
