### ISSUE TITLE
Completed 'Waypoint: Build an Adventure Game', sent back to first Waypoint.

### ISSUE THREAD

**Issue by Kaereste** [FreeCodeCamp/FreeCodeCamp#2291]
Not sure what caused it, and I can't duplicate it.

Also, a pink notice popped up saying I had completed all the waypoints and was ready to work on non-profits, which is obviously erroneous.

**Comment by dokkillo** [comment]
Hi Kaereste,

FreeCodeCamp changed all the map and included a lot of new waypoints, Waypoint: Build an adventure Game dont exist anymore because FreeCodeCamp dont use CodeAcademy tutorials of Javascript anymore.

Regards

**Comment by Kaereste** [comment]
That still doesn't explain why it sent me back to the first waypoint rather than the first/most relevant JavaScript waypoint. Also, a pink notice popped up saying I had completed all the waypoints and was ready to work on non-profits, which is obviously erroneous.

**Comment by benschenker** [comment]
@Kaereste I believe this has to do with the algorithm that determined what challenge to go to next.  It has recently been updated and that should resolve your issue.

I'll close this but feel free to reopen if your issue is not resolved
