### ISSUE TITLE
Bonfire - Search and Replace - Testing Capitalization

### ISSUE THREAD

**Issue by Baron-Severin** [FreeCodeCamp/FreeCodeCamp#2297]
Challenge http://freecodecamp.com/challenges/bonfire-search-and-replace has an issue. 

Several test inputs and outputs are capitalized differently, as shown in screenshot.  Thank you!

![image](https://cloud.githubusercontent.com/assets/13170306/9379614/63fa75e2-46df-11e5-82a3-2ef9f037e324.png)

**Comment by dokkillo** [comment]
Working with this

**Comment by awesomeaniruddh** [comment]
```
NOTE: Preserve the case of the original word when you are replacing it. For example if you mean to replace the word 'Book' with the word 'dog', it should be replaced as 'Dog'
```

The tests expect you to detect the case and preserve it. Closing this because it is resolved. Feel free to reopen if you feel that it hasn't been resolved, or need clarification :)
