### ISSUE TITLE
Bug: Validating the answer as correct even with wrong information

### ISSUE THREAD

**Issue by ujwalbharatn** [FreeCodeCamp/FreeCodeCamp#2298]
Challenge http://freecodecamp.com/challenges/waypoint-add-your-javascript-slot-machine-slots has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The answer is being validated as correct even though the if condition is written incorrectly.

Just entering ``if(slotOne ===)`` within the commented lines is triggering validation.

![screen shot 2015-08-20 at 2 56 23 pm](https://cloud.githubusercontent.com/assets/8043780/9380179/1ee50126-474c-11e5-8da1-f0bc487234f5.png)

**Comment by fnky** [comment]
Could be a possible reference to #2306

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2281

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
