### ISSUE TITLE
UX bug. Checkbox is not checked after clicking on a step-text in a checklist.

### ISSUE THREAD

**Issue by nikitin2009** [FreeCodeCamp/FreeCodeCamp#2299]
Challenge http://www.freecodecamp.com/challenges/waypoint-get-set-for-ziplines has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Actual result:** checkbox is not checked when I am clicking on a list item text in step by step guide.
**Expected result:** checkbox is checked.

**Comment by benschenker** [comment]
Hey @nikitin2009 thanks for posting!

I'm having trouble replicating this.  Is it still an issue for you?

**Comment by benschenker** [comment]
Looks like this has been fixed, see #2199.  I'll close this for now but feel free to reopen if you still see this issue.

**Comment by nikitin2009** [comment]
I meant other problem. This http://codepen.io/nikitin88/pen/YyXpWv?editors=100. But I am not sure, maybe it isn't a problem?

**Comment by benschenker** [comment]
Ah yes, that is doing exactly what it is supposed to be doing.  See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label
