### ISSUE TITLE
Comment tags

### ISSUE THREAD

**Issue by ai3gtmc** [FreeCodeCamp/FreeCodeCamp#2300]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-comments-to-clarify-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Adding a <-- at the very first line of the code somehow added the --> at the very last line which triggered the "Go to my next challenge" button as if it was correctly completed.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2210
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2115
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2075

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
