### ISSUE TITLE
[jQuery Waypoint: Remove Classes from an element with jQuery] removeClass() passing

### ISSUE THREAD

**Issue by ckylee** [FreeCodeCamp/FreeCodeCamp#2301]
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Expected passing code:  $("button").removeClass("btn-default");

Exercise automatically passes with:  $("button").removeClass();

**Comment by souldreamer** [comment]
Well, technically `.removeClass()` removes the `btn-default` class. :)
> If a class name is included as a parameter, then only that class will be removed from the set of matched elements. **If no class names are specified in the parameter, all classes will be removed.**
> [jQuery docs](https://api.jquery.com/removeclass/)

**Comment by ckylee** [comment]
Yep technically it works but removeClass() removes all class whereas removeClass('btn-default') is more specific. Just a minor thing.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2197
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2160
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1923
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1898
Fixed.
