### ISSUE TITLE
removeClass marks as finished even though it's unfinished.

### ISSUE THREAD

**Issue by ai3gtmc** [FreeCodeCamp/FreeCodeCamp#2302]
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

the challenge was marked as finished even with just $("button").removeClass

it should be marked as finished with $("button").removeClass("btn-default");

**Comment by fnky** [comment]
Reference to #2306

Spec says specifically
> Remove the `btn-default` class from all of your **`button`** elements.

However this works as well
```js
$('.btn').removeClass()
```

According to spec `.btn` should not be possible, only `button`.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2301
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2197
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2160
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1923
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1898
Fixed.
