### ISSUE TITLE
Waypoint 1: Bootstrap Fluid Containers button not working

### ISSUE THREAD

**Issue by betsbillabong** [FreeCodeCamp/FreeCodeCamp#2303]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The "go to next challenge" button animated when I added the div, but it won't send me to the next page.

**Comment by fnky** [comment]
Reference to issue #2306 

This is a valid example that will complete the Waypoint:

```js
<div class="container-fluid">
  
</div>
```

**Comment by betsbillabong** [comment]
Yes, I know. It was marked as correct, animated and green - just wouldn't do anything when I hit the button.

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2103
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1983

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Comment by SasukeUchiha619** [comment]
Make sure you have nested all HTML elements in .container-fluid. this is not compleated

**Comment by SasukeUchiha619** [comment]
Your new image should be below your old one and have the class img-responsive.

**Comment by SasukeUchiha619** [comment]
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. "></a>
  <a href="#"><img class="image-responsive."src="https://bit.ly/fcc-running-cats" alt="running cats"></a>

  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

**Comment by texas2010** [comment]
@SasukeUchiha619 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!
