### ISSUE TITLE
No <h1>

### ISSUE THREAD

**Issue by vekkna** [FreeCodeCamp/FreeCodeCamp#2304]
Challenge http://freecodecamp.com/challenges/waypoint-center-text-with-bootstrap has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Task mentions a h1 tag but there is none.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1361

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
