### ISSUE TITLE
let's do it

### ISSUE THREAD

**Issue by elturky** [freeCodeCamp/freeCodeCamp#23042]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by elturky** [comment]
training

**Comment by ezioda004** [comment]
Hi @elturky,
This section is for issues regarding the fcc codebase.
If you have any questions please go to our forums or our contributors chatroom.
