### ISSUE TITLE
Waypoints should not run specs for syntax and implementation

### ISSUE THREAD

**Issue by fnky** [FreeCodeCamp/FreeCodeCamp#2306]
The waypoints, especially for the **Slot Machine**, runs syntax-specific specs, which introduces bad practices and bugs (most of which are reported) and it of itself is bad. This disallows DRY code and promotes bad practices.

### First example

The first waypoint requires you to specifically insert

```js
slotOne = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
slotTwo = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
slotThree = Math.floor(Math.random() * (3 - 1 + 1)) + 1;
```

While there are many workarounds of this, one of the easiest and the most approaching one would be to implement a function, that returns the above statement:

```js
function randomSlot() {
  return Math.floor(Math.random() * (3 - 1 + 1)) + 1;
}
```

Furthermore it disallows other legit workarounds:

```js
Math.floor(Math.random() * (3 - 1 + 1) + 1);
//                   moved bracket to end ^
```

The spec that fails if anything else but the first example is used

```
You should have used Math.floor(Math.random( * (3 - 1 + 1)) + 1; three times to generate your random numbers.)
```

#### Second example

**Waypoint: Give your JavaScript Slot Machine some stylish images** has some weird way of checking syntax the following will work just fine (copied from the description):

```js
$($(".slot")[0]).html("<img src = '" + images[slotOne-1] + "'>");
$($(".slot")[1]).html("<img src = '" + images[slotTwo-1] + "'>");
$($(".slot")[2]).html("<img src = '" + images[slotThree-1] + "'>");
```

But for some reason, the below statement doesn't work, which is exactly the same (_it has been diffed and found no malforming characters_):

```js 
  $($(".slot")[0]).html("<img src = '" + images[slotOne-1] + "'>");
    $($(".slot")[1]).html("<img src = '" + images[slotTwo-1] + "'>");
    $($(".slot")[2]).html("<img src = '" + images[slotThree-1] + "'>");
```

The above code will fail on spec

```
Use the provided code three times. One for each slot
```

Which is not only a wrong statement, but also an issue many users run in to.

### How to fix this?

Remove all spec that checks for syntax-specific and implementation-specific code. It's hard (if not entirely) to be certain of a random function returns the right values.

But one way to avoid this, as these examples only require a random between _1_ and _3_ is to make an asynchronous function that will iterate the given random function and atleast get `1`, `2` and `3` before proceeding.

It should be asynchronous because it shouldn't halt other specs from running for every interpretion/change of code.

---

> **Note:** These are only two examples of many. There are more waypoints suffering from these kinds of specs, that I have not tested yet.
  
###### Please reference this issue on other issues, by commenting `Reference to issue #2306` on issues that this bug might be the course of. If possible, also provide further information on the issue you post at (see examples below on references) to keep this organized in multiple issues, rather than a single one. This issue is only for discussion of writing specs that does not course bugs for waypoints.

**Comment by bugron** [comment]
Closing this issue as these challenges were removed from the curriculum.
