### ISSUE TITLE
syntax matching not working

### ISSUE THREAD

**Issue by AnselmeKotchap** [FreeCodeCamp/FreeCodeCamp#2307]
Challenge http://freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

the last matching for closing the document ready call with }); refuse to validate.

**Comment by fnky** [comment]
This is another example of the issue with running syntax-specific specs #2306

The actual should be

```js
$(document).ready(function() {

});
```

and not

```js
$(document).ready(function() { });
```

or

```js
$(document).ready(function() {
});
```

**Comment by AnselmeKotchap** [comment]
Yes it worked, but that's really an odd syntax matching there!

**Comment by fnky** [comment]
It is still a bug.

**Comment by AnselmeKotchap** [comment]
Thanks!
