### ISSUE TITLE
Waypoint: Center Text with Bootstrap typo

### ISSUE THREAD

**Issue by erratadei** [FreeCodeCamp/FreeCodeCamp#2308]
Challenge http://www.freecodecamp.com/challenges/waypoint-center-text-with-bootstrap has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

in instructions it says the class name is text-red while in code it says red text

**Comment by dokkillo** [comment]
working in it!

**Comment by issyl0** [comment]
@dokkillo Hi! Did you get anywhere with fixing this?

**Comment by dokkillo** [comment]
yes, sorry i didnt created the pull request
