### ISSUE TITLE
Incorrect Wording as part of the task

### ISSUE THREAD

**Issue by owencampbell** [FreeCodeCamp/FreeCodeCamp#2309]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

First target your **div** element with the id target3 by using the $("#target3") selector.

**div** needs changing to **button**.

**Comment by meecoder** [comment]
This is a duplicate of issue #2170.
