### ISSUE TITLE
waypoint-add-borders-around-your-elements

### ISSUE THREAD

**Issue by asdal** [FreeCodeCamp/FreeCodeCamp#2312]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue. 

First 2 requirements for the exercise are conflicting and confusing.

1. Your img element should have the class smaller-image.
2. Your img element should have the class thick-green-border.

**Comment by jbmartinez** [comment]
They're not conflicting, any element can have multiple classes. Add them using `class="class1 class2"`
