### ISSUE TITLE
All in screenshot. Waypoint: Manipulate Arrays With shift.

### ISSUE THREAD

**Issue by Acidsky** [FreeCodeCamp/FreeCodeCamp#2313]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-shift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![screenshot from 2015-08-20 16 03 47](https://cloud.githubusercontent.com/assets/13290212/9384056/1fa85efa-4756-11e5-8ab5-1ea64daf53f5.png)

**Comment by benschenker** [comment]
Thanks for posting!

It looks like you got it right!  Those green checkmarks mean you are good to go!
What exactly is the problem?

**Comment by Acidsky** [comment]
Mistake in first challenge. It must be "myArray should only have the first two values left <b>([23,["dog",3]])</b>"

**Comment by BerkeleyTrue** [comment]
fixed. Happy Coding!
