### ISSUE TITLE
Code is shown for the assertions - not readable. 

### ISSUE THREAD

**Issue by jk47** [FreeCodeCamp/FreeCodeCamp#2314]
Challenge http://freecodecamp.com/challenges/waypoint-manipulate-arrays-with-pop has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

All of the javascript challenges have assertions with long strings of code. I am not sure if it is by design but it seems odd to me. 

![image](https://cloud.githubusercontent.com/assets/2525359/9384083/459f057a-4713-11e5-8d93-b2dc2ce3e896.png)

**Comment by james-rose** [comment]
I see this too.  It also has the word "Undefined" right below the Reset button.  Also, if I click on Reset after completing and getting all checkmarks, it doesn't reset the checkmarks to red x's.

**Comment by bugron** [comment]
Dear camper, your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2182
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2153

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Comment by jk47** [comment]
Closing as duplicate
