### ISSUE TITLE
id instead of type

### ISSUE THREAD

**Issue by schmitzel90** [FreeCodeCamp/FreeCodeCamp#2316]
Challenge http://freecodecamp.com/challenges/waypoint-disable-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Code example on the left identifies element by id instead of type.
change 
    $('#button').prop('disabled', true); 
to 
    $('button').prop('disabled', true);

**Comment by benschenker** [comment]
Hey thanks for submitting this! Someone else posted this issue too: See #2014 for more info, it seems like this will be fixed with Pull Request #2018
