### ISSUE TITLE
error in description of waypoint "Use Bracket Notation"

### ISSUE THREAD

**Issue by mobesa** [FreeCodeCamp/FreeCodeCamp#2318]
description of waypoint is missing a few words [link] http://www.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-first-character-in-a-string

**Comment by meecoder** [comment]
what words are missing? the only error I see is "first character in a the..."

**Comment by mobesa** [comment]
that's it

**Comment by meecoder** [comment]
ok, fixing this issue now. thanks for reporting!

**Comment by meecoder** [comment]
this issue has been fixed, just not pushed to the site.

**Comment by mobesa** [comment]
thanks! closing issue.
