### ISSUE TITLE
Typo, I think...(From Taiwan, not good at English)

### ISSUE THREAD

**Issue by ChenYingYu** [FreeCodeCamp/FreeCodeCamp#2319]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-first-character-in-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Paragraph 4 : 
Use bracket notation to find the first character in "a the" firstLetterOfLastName variable.

(FreeCodeCamp is awesome!!!!!)

**Comment by meecoder** [comment]
this issue has already been fixed, just not pushed to the site yet. thanks for reporting though!
