### ISSUE TITLE
bonfire more info button arrow needs to change

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#232]
when bonfire more info pane is open, icon arrow should change to arrow up.

**Comment by MrRenter** [comment]
When I click it it changes. It works on both bonfires that actually have more info and ones that dont.
Doesnt have more info
http://www.freecodecamp.com/bonfires/diff-two-arrays 
http://puu.sh/gGqH2/7deb9d7e4a.png

Has more info
http://www.freecodecamp.com/bonfires/cash-register
http://puu.sh/gGqIx/20f4265c84.png

I am using chrome on windows 8.1

**Comment by BerkeleyTrue** [comment]
This is for the `reactify` branch of the project.

**Comment by QuincyLarson** [comment]
We've removed this button. I'm closing this.
