### ISSUE TITLE
I'm pretty sure there's a bug on this page

### ISSUE THREAD

**Issue by calskin** [FreeCodeCamp/FreeCodeCamp#2323]
Basic JavaScript: Waypoint: Generate Random Whole Numbers within a Range (http://freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-within-a-range)

I've tried this over and over for about an hour and I've looked it up on Google and from what I can see, I'm doing this right.

Here is my code which I believe is correct...

var min = 0;
var max = 12;
function myFunction() {
  // Make myFunction return a random number between zero and nine instead of a decimal
  // Only change code below this line.

 return Math.floor(Math.random() * (9 - 1 + 1)) + 1;
}

// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
(function(){return(myFunction());})();

Depending on the number that is generated, it's either correct on 2 out of 3 points none.

No matter what I do, I can't get the third point.  I'm pretty sure it's a bug because I've looked this up and the fact is that the results of my code give what the exercise is asking for.

Here is the readout...

assert(myFunction() >= min, 'The random number that\'s generated by myFunction should be greater than or equal to the minimum number');
assert(myFunction() <= max, 'The random number that\'s generated by myFunction should be less than or equal to the maximum number');
assert((function(){if(editor.getValue().match(/max/g).length >= 2 && editor.getValue().match(/min/g).length >= 2 && editor.getValue().match(/Math.floor/g) && editor.getValue().match(/Math.random/g)){return(true);}else{return(false);}})(), 'You should be using the function given in the description to calculate the random in number in a range');You should be using the function given in the description to calculate the random in number in a range

**Comment by benschenker** [comment]
Hey thanks for posting an issue!

Check out #2262 who had the same exact problem.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
