### ISSUE TITLE
"Add id attributes to bootstrap elements" test is too broad

### ISSUE THREAD

**Issue by Daeke** [FreeCodeCamp/FreeCodeCamp#2324]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-id-attributes-to-bootstrap-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Adding the id attributes to the buttons (instead of the well) results in a correct answer.

**Comment by jbmartinez** [comment]
The test cases say you should give `id`s to the `well`s:
![testcase](https://cloud.githubusercontent.com/assets/4247923/9400446/25cd3ff0-478b-11e5-98bc-2c83702722ef.png)

**Comment by Daeke** [comment]
Sorry, I guess I should have been more clear.

The test case labels are correct, but the actual tests themselves seem to be testing for the presence of "left-well/right-well" on the individual elements inside the wells (the buttons) rather than the div itself. The tests will pass if you add "left-well" to the first three buttons and "right-well" to the remaining three buttons, even if the divs are left id-less.

**Comment by saadanerdetbare** [comment]
PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2426

**Comment by m-duran** [comment]
I also encountered this. Here is a screenshot of the ids in the wrong spot, but the challenge passing.
![freecodecampbug](https://cloud.githubusercontent.com/assets/7898662/9460365/07459abe-4aba-11e5-8238-5293da9e579e.PNG)
