### ISSUE TITLE
inconsistency with semicolon

### ISSUE THREAD

**Issue by duanwalker** [FreeCodeCamp/FreeCodeCamp#2327]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-rgb-to-color-elements-red has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

there seems to be an inconsistency with the requirement of a semicolon to pass a challenge. 

this passed 
![image](https://cloud.githubusercontent.com/assets/7536426/9386911/d2a7397a-472b-11e5-8c12-f9bd6e09df10.png)

this also passed
![image](https://cloud.githubusercontent.com/assets/7536426/9386940/f8e9127a-472b-11e5-9bc3-3ffb4a060a5d.png)

**Comment by jbmartinez** [comment]
The semicolon is not required for the last rule, although it's a good practice to use it

**Comment by BerkeleyTrue** [comment]
yes, unfortunately this is not something we can enforce as it technically is valid html.

**Comment by duanwalker** [comment]
oh i see. ok thanks!
