### ISSUE TITLE
have have "double word

### ISSUE THREAD

**Issue by Key-Solution-Ghana** [FreeCodeCamp/FreeCodeCamp#2333]
Challenge http://freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

just have a double wording issue.[ our image should have have a src attribute that points to the kitten image. ] the word have is twice in the challenge text. "our image should have have ................

**Comment by dokkillo** [comment]
working with this!

**Comment by Key-Solution-Ghana** [comment]
Great good work. thanks
