### ISSUE TITLE
4th instruction in Waypoint: Override Class Declarations with Inline Styles

### ISSUE THREAD

**Issue by smellyd** [FreeCodeCamp/FreeCodeCamp#2334]
Challenge http://freecodecamp.com/challenges/waypoint-override-class-declarations-with-inline-styles has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When the page loads the fourth instruction description is NULL. When you complete the challenge, the instruction appears (when the button jumps with excitement). I guessed the instruction and it worked.

**Comment by benmcmahon100** [comment]
I'm not seeing this can you post a screen shot. Also what you'r browser os combo?

**Comment by smellyd** [comment]
I can't replicate it since I have completed the waypoint. I tried to remove the code but it didn't remove the description and replace with NULL (sorry).

Windows 7 Enterprise Service Pack 1
Chrome Version 44.0.2403.155 m

**Comment by benmcmahon100** [comment]
Hmm i think it was just a once off error. I'm going to close this issue but if you see it again try get a screen shot, open a new issue and feel free to @ me in it! Thanks for keeping an eye out for issues!
