### ISSUE TITLE
Waypoint 54

### ISSUE THREAD

**Issue by smellyd** [FreeCodeCamp/FreeCodeCamp#2335]
Challenge http://freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-colors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Map show this waypoint as complete but I have not completed it.

Windows 7 Enterprise Service Pack 1
Chrome Version 44.0.2403.155 m

![1](https://cloud.githubusercontent.com/assets/9628416/9390045/a3bec8d8-473c-11e5-890a-8d2541ef812b.png)
![2](https://cloud.githubusercontent.com/assets/9628416/9390046/a3c0bc7e-473c-11e5-9ef5-61be71d9cbe4.png)

**Comment by dokkillo** [comment]
change background-color:black for background-color:#000000;

**Comment by benmcmahon100** [comment]
Hmm it may have completed before hand. Sadly there's no real way to re-create this issue. Hopefully it's another one off. If it occurs again feel free to create a new issue and @ me

**Comment by Nelson53** [comment]
can someone me with lesson 54

**Comment by Nelson53** [comment]
help me

**Comment by Nelson53** [comment]
what is wrong with the code?

**Comment by texas2010** [comment]
@Nelson53 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

These GitHub Issues are for reporting bugs on the freeCodeCamp website only.

Happy Coding.
