### ISSUE TITLE
the page is acting weirdly, it's randomly scrolling on the left tab with the instructions, finding it hard also to type the code to finish the challange

### ISSUE THREAD

**Issue by accursedleaf** [FreeCodeCamp/FreeCodeCamp#2336]
Challenge http://www.freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Thanks for posting this issue!  This has been fixed
