### ISSUE TITLE
Bonfire: Smallest Common Multiple issue

### ISSUE THREAD

**Issue by ernestogonzalezmx** [FreeCodeCamp/FreeCodeCamp#2340]
Challenge http://www.freecodecamp.com/challenges/Bonfire: Smallest Common Multiple has an issue. Hi!

When I try to enter Bonfire: Smallest Common Multiple the browser crashes. I can´t delete the code in it, Neither I can reset the lesson.

**Comment by benschenker** [comment]
Hey @ernestogonzalezmx can you post a screenshot?
