### ISSUE TITLE
Instructions are showing the source code.

### ISSUE THREAD

**Issue by ai3gtmc** [FreeCodeCamp/FreeCodeCamp#2341]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The instructions are also showing the source code of the instructions.
I think the image speaks for itself.
![javascript comment](https://cloud.githubusercontent.com/assets/9110413/9391370/55949e60-47b1-11e5-9ed6-7d32395edd61.JPG)

**Comment by fnky** [comment]
There are a lot of waypoints that to this. I don't know wether this is on purpose.

**Comment by ai3gtmc** [comment]
Looking at it, it looks the the whole Javascript Waypoint is doing this.
(this is the only thing that I've checked so far)

**Comment by benschenker** [comment]
That should be showing up there. It's part of all the javascript based challenges that you are able to see the tests that are running against your code. See #2231 for a similar issue/explanation.

**Comment by fnky** [comment]
@benschenker The problem is that the asserts are written in a way that tells the user what to do, rather than just being descriptive of what is needed to pass, consider this:

> The `//` style comment contains at least five letters.

> The `/* */` style comment contains at least five letters.

> Comment should be closed with `*/`.

The key here is that you write as if the test is going to pass (even though it might not). This also helps people further, when they write their own tests as well.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2182
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2153
