### ISSUE TITLE
Waypoint: Declare Javascript Variables

### ISSUE THREAD

**Issue by ALINATSUI** [FreeCodeCamp/FreeCodeCamp#2346]
Small issue: The instructions should note that to create a variable a semicolon is needed to complete the challenge.

Challenge http://www.freecodecamp.com/challenges/waypoint-declare-javascript-variables has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by rsprice** [comment]
@ALINATSUI hmmm... I just completed the challenge without adding the semicolon to the end of my "myVar" declaration statement. I think that the JS lint suggests that you end your statement with a semicolon (hence the red x next to the current line number your working on if you don't introduce a semicolon), but I think you should be able to complete the challenge without it.

**Comment by ALINATSUI** [comment]
@rsprice You're right. Sorry about that. I saw the red x next to the "myVar" declaration statement and assumed it wouldn't go through without a semicolon.

**Comment by rsprice** [comment]
@ALINATSUI no worries. Happy coding! :smile:
