### ISSUE TITLE
Push Request To Add Articles

### ISSUE THREAD

**Issue by doeppler** [freeCodeCamp/freeCodeCamp#23480]
Hello,
I just wrote an article for freecodecamp and I don't want it to go to waste. It is about WordPress and how to get started with it.

**Comment by ezioda004** [comment]
Hi @doeppler,

Dont worry we'll look at your PR and if it follows our guideline, rest assured it'll be merged.
Please be patient as we have a lot of PR's as you can see (3300 and counting) it might take a while to get to yours.

I'm closing this issue as it's not regarding any issue or bug.

Thank you for your patience and happy coding.
