### ISSUE TITLE
Shorthand hex colors don't work 

### ISSUE THREAD

**Issue by voodoobettie** [FreeCodeCamp/FreeCodeCamp#2348]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-hex-code-for-specific-colors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![screenshot from 2015-08-20 12 26 13](https://cloud.githubusercontent.com/assets/8313503/9393429/b59659e6-4736-11e5-94af-a959cc468471.png)

Just wanted to point out that shorthand hex colors don't work for the color challenges waypoint and they should because they're valid CSS.

**Comment by benschenker** [comment]
Thanks for posting an issue!

I believe is specifically looks for the full hex notation here because in a future waypoint it shows the shorthand notation.

**Comment by voodoobettie** [comment]
Okay. I thought that would be why, I guess it's expecting the full input. Thought I would open it in case it was actually supposed to.

**Comment by tomByrer** [comment]
> because in a future waypoint it shows the shorthand notation.

yes
http://www.freecodecamp.com/challenges/waypoint-use-abbreviated-hex-code
