### ISSUE TITLE
Challenges marked as complete when they're not

### ISSUE THREAD

**Issue by thejonathangraham** [FreeCodeCamp/FreeCodeCamp#2349]
@QuincyLarson  When you complete a challenge correctly and then change it again, it is still marked as complete! Good Luck...

**Comment by benschenker** [comment]
Thanks for posting this issue!

Can you post a screenshot so we can see exactly what you mean?

**Comment by thejonathangraham** [comment]
@benschenker here you go!
Once you've completed the steps, it's marked as complete (as it's supposed to).
![fcc2](https://cloud.githubusercontent.com/assets/11198912/9404108/960d13d6-47e4-11e5-9420-761e4f2c5632.png)

However, if you go ahead and change something or even delete everything, it is still marked as correct and you can continue to the next challenge.
![fcc1](https://cloud.githubusercontent.com/assets/11198912/9404121/b7891f3c-47e4-11e5-9abf-eb9829d4902c.png)

**Comment by BerkeleyTrue** [comment]
That first test detects if you have removed the h1 element that initially renders with this challenge. Since there is no h1 element on the page the test is valid as expected.

Happy Coding!
