### ISSUE TITLE
Weird 404 error on unrelated Waypoint challenge

### ISSUE THREAD

**Issue by voodoobettie** [FreeCodeCamp/FreeCodeCamp#2351]
Challenge http://www.freecodecamp.com/challenges/waypoint-center-text-with-bootstrap has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Getting an error message on the waypoint "Center text with Bootstrap" which says "404: We couldn't find a challenge with the name `hike-computer-security` Please double check the name."

**Comment by BerkeleyTrue** [comment]
Can you give us some details to reproduce the error?

**Comment by voodoobettie** [comment]
It was just when I loaded the next waypoint challenge using ctrl+enter, from the previous waypoint. I can't seem to reproduce it by going back and loading it again, you might have trouble too. It was weird so I put in a bug report. I meant to attach a screenshot earlier, here it is: 

![screenshot from 2015-08-20 12 38 44](https://cloud.githubusercontent.com/assets/8313503/9395951/631006bc-4746-11e5-98da-a6c630c403f1.png)

**Comment by zjacreman** [comment]
I can confirm, I saw the same message on that challenge. I can't reproduce it easily right now either, but I saw it in the normal course of going through the lessons.

**Comment by BerkeleyTrue** [comment]
Not sure the cause, but you should be seeing those challenges. I'll have to look into the controller and see how they are leaking out.

**Comment by padamson** [comment]
Saw the same error in firefox on osx when clicking the "Go to my next challenge..." button from waypoint 2 of the responsive design with bootstrap lesson

**Comment by benschenker** [comment]
Hey are there any updates on this? I am unable to reproduce this, is anyone still having issues?

I'll close this as stale for now but please reopen if the issue remains.
