### ISSUE TITLE
Why are the arguments after the first argument not able to be accessed ?

### ISSUE THREAD

**Issue by VinodhThiagarajan86** [FreeCodeCamp/FreeCodeCamp#2353]
Challenge http://www.freecodecamp.com/challenges/bonfire-seek-and-destroy has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

if the argument is arr = [1,2,3,1,2,3],2,4 and I try to access the arr[2] , I'm expecting 4 but i get 3 instead. Am i missing something here ?

**Comment by ozydesign** [comment]
because the first argument is arr which is [1,2,3,1,2,3] (so third index of arr is 3). 2 and 4 are the second and third arguments respectively and are accessed trough the arguments object.

**Comment by benschenker** [comment]
Also see: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/js-arguments
