### ISSUE TITLE
not allowing me to move on when complete

### ISSUE THREAD

**Issue by brcent** [FreeCodeCamp/FreeCodeCamp#2354]
Challenge http://freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
For some reason it thinks the left-well background is not red and will not let me continue.
![image](https://cloud.githubusercontent.com/assets/13809531/9394508/d8b2aa22-4756-11e5-833a-d764b61173ab.png)
![image](https://cloud.githubusercontent.com/assets/13809531/9394525/e797e71e-4756-11e5-8bd6-b04b0c867318.png)
![image](https://cloud.githubusercontent.com/assets/13809531/9394536/f7f4f80e-4756-11e5-8892-d859bc6281c0.png)

**Comment by KleoPetroff** [comment]
The challenge is working perfectly. You must select the `left-well` element using the `parent()` method, not the parent element of `left-well`.

In your case you are giving a background-color to the bootstrap column, not the well.

**Comment by brcent** [comment]
Thanks
