### ISSUE TITLE
Curriculum Kicks me out

### ISSUE THREAD

**Issue by Danyl007** [freeCodeCamp/freeCodeCamp#23559]
When logging in i’m taken to a welcome page with my name, asking me to take part in a survey. When I click the ‘Go to the coding curriculum’ it take me to freecodecamp as if i’ve never logged in , no progress , no name, and the sign in button appears again. I hit sign in and it takes me to the start again. I’ve tried clearing cache, restarting computer, I’ve verified this is the correct email account that I’ve had since starting FCC and I have been logging in successfully for the last week. It's like my session is cleared when I try to view curriculum. Preference settings like dark mode also clear. Can someone help?

**Comment by Danyl007** [comment]
Troubleshooting:
Chrome: sign out, clear cache, flush dns, fresh re-install of chrome, all with restarts. 
Firefox: 'as above'
Create new FCC test account + all previous steps.
New Computer: All previous steps.
Same issue every time.

**Comment by dave-todd** [comment]
I also have the same issue.
I also have tried all steps mentioned above.
I have tried multiple browsers and devices with consistent results, so I believe it isn't device dependant.
There seems to have been approximately 10 people all with this issue all posting on forums on the same day.
I would assume there are many more that didn't take the time to post.
The severity of the bug is such that it disables 100% of web site functionality.

**Comment by zainafzal88** [comment]
Please solve this bug as soon as possible. 
It is slowing me down from my targets each day since yesterday.

**Comment by jellyskin** [comment]
Am also experiencing the same issue - I have also tested all the above solutions and troubleshooting steps.  Not sure if this is just limited to a small number of users.

**Comment by chestnuto** [comment]
I started using FCC a couple days ago and am now experiencing this problem.

Performed the same troubleshooting steps as everyone else which lead me to trying a brand new account where I hit the same issue immediately.

**Comment by ezioda004** [comment]
Hi everyone,

Thank you all for reporting this issue. 

I'm not sure whats causing this login issue, but I'll tag the members who handles this. 
We'll try to fix this ASAP.

Meanwhile, please be patient. 

Thank you.

Tagging @QuincyLarson @raisedadead @Bouncey for visibility.

**Comment by Chibi1** [comment]
Me too :(

**Comment by clickr** [comment]
Me too. Problem occurs across multiple browsers and devices (OSX - safari, chrome, firefox; iOS - safari).
1. Login successful
2. After navigating to the curriculum page, progress indicator on top RHS changes to a yellow button `<li class="sign-in-btn"><a href="https://www.freecodecamp.org/signin" target="_blank" class="btn-cta btn btn-default">Sign In</a></li>` with no history

**Comment by MattB1** [comment]
I'm also experiencing this issue!
I've tried all the steps from above as well.

**Comment by RandellDawson** [comment]
@Danyl007 You did not specify what operating system, browser, or browser version you are using when experiencing this.  When reporting an issue, those are sections which are very helpful to those investigating such issues.  Also, anyone else with the same issue should also reply with what their operating system, browser, and browser version is.

Thank you.

**Comment by rmklaus12** [comment]
I am experiencing it as well. I have tried on Chrome, Firefox, and Opera on a MacBook Pro as well as Firefox on a MacBook Air. I have cleared history/cache, rebooted, signed out and back in using email (not via GitHub). 
MBP: Mohave 10.14
Chrome: Version 69.0.3497.100 (Official Build) (64-bit)
Firefox: 62.0 (64-bit)
Opera: 56.0.3051.52

**Comment by ronalddtang** [comment]
@RandellDawson Sure no problem
Windows Version 10.0.16299 Build 16299
Chrome Version 70.0.3538.67 (Official Build) beta (64-bit)
firefox: 62.0.3 (64-bit) 

Like @Rajucec75 has quoted in his images, I also get the yellow sign-in button even though when I click on the homepage / sign in, I get taken to the landing page quoting my name.

Tried both github and email login methods.

![image](https://user-images.githubusercontent.com/6134351/47252398-654cb700-d487-11e8-921d-4a6214b84cda.png)

![image](https://user-images.githubusercontent.com/6134351/47252402-6f6eb580-d487-11e8-9534-89f0772ba689.png)

**Comment by Liight** [comment]
I have the same issue. 
When accessing the curriculum, at first it appears I am signed out. 
However I am not signed out, rather I am not signed into the curriculum. 
I cannot successfully sign into the curriculum. 
Other signed in areas operate as normal.
I have deleted browser cookies and cache, this has no effect.
The issue is common across Chrome, Firefox and Internet Explorer browsers.
This issue is common across multiple devices.

**Comment by clickr** [comment]
If this is not universal could there be a geographic component to this? At a meetup here in Perth Western Australia multiple people had this same problem.

**Comment by vbergaaa** [comment]
Coming here to report I have the same issue. I am also an Australian in Mascot, Sydney.

The sign out was more noticeable for me as the first page (saying I was logged in) was in night mode and the curriculum was showing a bright white background. As I completed challenges I was able to progress through the curriculum, however, when I re-logged in, I had to re-complete those challenges. (previous results were stored in the coding window so it was only a matter of hitting crtl+enter a few times).

Windows 10 home, Chrome v70

**Comment by rmklaus12** [comment]
I am also in Australia, Melbourne. I reported the issue earlier, but seen
these posts from fellow Australians and wanted to chime in.

**Comment by clickr** [comment]
OK. It's a geographic issue. Problem solved if I use a VPN to the US. Reoccurs if I revert back to Australia.

**Comment by clickr** [comment]
Works with Singapore and Indonesia VPNs. Fails with Australia and New Zealand.

**Comment by ronalddtang** [comment]
that might be the case, as I am also from Brisbane, Australia

**Comment by raisedadead** [comment]
Hi All. 

Thanks a lot for the issue report. 

We are working with https://netlify.com (our CDN partner) to understand this better. Meanwhile I recommend keeping this thread **for potential solutions only**.

**Comment by raisedadead** [comment]
The current workaround stands at using a VPN.

**Comment by zainafzal88** [comment]
Thanks for the update and this workaround. Hope admins for FCC, will soon find a proper fix for it.

On 20 Oct 2018, at 11:46 pm, mrugesh mohapatra <notifications@github.com<mailto:notifications@github.com>> wrote:


The current workaround stands at using a VPN.

**Comment by Kyle-S-Thompson** [comment]
I wanted to provide a link to this post from Quincy through FCC, detailing how to set up a VPN in just a few minutes (as well as some privacy info.)

**For those that are not sure where to start with a VPN**: https://medium.freecodecamp.org/how-to-set-up-a-vpn-in-5-minutes-for-free-and-why-you-urgently-need-one-d5cdba361907

_(delete if not allowed)_

**Comment by rmklaus12** [comment]
Yes! It works to use the free Opera VPN. Thank you for this!

**Comment by zainafzal88** [comment]
For users who prefer to use Chrome:


  1.  Install SetupVPN extension from Chrome web store
  2.  Create an account
  3.  Choose your country(I used UK)
  4.  Access FCC


Should work (mine does)
If it doesn’t let me know, I’ll do what I can to help

**Comment by raisedadead** [comment]
Hi Everyone. 

#### Update:

#### We have deployed fresh instances in the AU/NZ region to resolve these issues. Everything should be normal now.

Please let us know if you are still getting any issues. Before you report, its recommended that you hard refresh your browser / clear cookies / sign in again.

Thanks for your patience and sincerest apologies about the inconvenience and the delay during this outage. 

Happy coding!

**Comment by rmklaus12** [comment]
Yes! Thank you. Working for me here in Melbourne :-)
