### ISSUE TITLE
Waypoint showing that it's complete when it's not

### ISSUE THREAD

**Issue by thejonathangraham** [FreeCodeCamp/FreeCodeCamp#2355]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers has an issue.

The Waypoint is marked as complete, however, I still haven't nested all my html into the div.

![fccissue](https://cloud.githubusercontent.com/assets/11198912/9394698/d325f85e-4781-11e5-86cd-3d721303a3cc.png)

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2103
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1983

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
