### ISSUE TITLE
Waypoint: Generate Random Whole Numbers with JavaScript

### ISSUE THREAD

**Issue by fcc-gpwin** [FreeCodeCamp/FreeCodeCamp#2356]
![random](https://cloud.githubusercontent.com/assets/13419079/9394878/85febace-4750-11e5-9c63-b317d5b20733.jpg)
This paragraph makes no sense: "It's great that we can create random decimal numbers, but it's even more useful if we lot more useful to generate a random whole number."

**Comment by issyl0** [comment]
Thanks for reporting this. It's been fixed in https://github.com/FreeCodeCamp/FreeCodeCamp/commit/87c01aae522404a8c9879cd08357a5afc148be0c. :+1:
