### ISSUE TITLE
Oops! Something went wrong. Please try again later .

### ISSUE THREAD

**Issue by Cheshire89** [FreeCodeCamp/FreeCodeCamp#2359]
I keep on trying to do courses but seem to be unable to open any section. (JavaScript, Html j Query and so on) . Keep on getting the same error "Oops! Something went wrong. Please try again later"

**Comment by BerkeleyTrue** [comment]
@Cheshire89 I saw you username come up in our error logs. It seems you where one of the case of duplicate usernames. I've gone and cleaned it up. You should be fine now.

**Comment by BerkeleyTrue** [comment]
Please feel free to re-open if you continue to have problems.

**Comment by bennynis** [comment]
Hi, I am experiencing a similar problem. I get this error message almost every time I finish a challenge, but after a few clicks for the next challenge (in 'map'), it works

**Comment by nicodemusg4** [comment]
me too

**Comment by suhasdarsi** [comment]
I have a similar problem too

**Comment by pmanolak** [comment]
Me too.....
Στις 13 Φεβ 2016 12:58, ο χρήστης "suhasdarsi" <notifications@github.com>
έγραψε:

**Comment by gokhanefe** [comment]
Hello,

 I am facing the same problem also. Is anything I can do for it?

**Comment by akainurev** [comment]
Hello, i'm also getting this message. I can still load the challenges but it usually takes 5-6 tries

**Comment by iwanjunaid** [comment]
i am experiencing the sampe problem too. it's been 5 hours

**Comment by anabol322** [comment]
Same thing happens to me, wat do

**Comment by aahmyu** [comment]
Me 3 i cant access some pages in fcc

**Comment by jorisrood** [comment]
Same here :(

**Comment by JBindi** [comment]
Experiencing this as well. It seems there has suddenly been a sharp increase of people getting this error.

**Comment by bitblitter** [comment]
Same thing happened to me, I set up a user before with my email but forgot the password, so I decided to use github instead. I deleted the old account with my email to see if that could help, but didn't work.

**Comment by BerkeleyTrue** [comment]
Please comment on #6960, this issue is closed.
