### ISSUE TITLE
Comment waypoint showing assertions instead of validating input

### ISSUE THREAD

**Issue by voodoobettie** [FreeCodeCamp/FreeCodeCamp#2362]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Errors showing on waypoint "Comment your JavaScript code" - showing assertions instead of using them for validating user entry. 

"assert(editor.getValue().match(/(\/\/)...../g), 'Create a \/\/ style comment that contains at least five letters');
Create a // style comment that contains at least five letters
assert(editor.getValue().match(/(\/\*)...../g), 'Create a /\* \*/ style comment that contains at least five letters.');
Create a /* */ style comment that contains at least five letters.
assert(editor.getValue().match(/(\*\/)/g), 'Make sure that you close the comment with a \*/');
Make sure that you close the comment with a */" 

User input box can be empty or filled and it makes no difference. 
![screenshot from 2015-08-20 14 01 49](https://cloud.githubusercontent.com/assets/8313503/9395625/63940194-4744-11e5-80dc-249ffb0b9ea7.png)
 

You can pass the waypoint with the correct input, so the problem appears to be cosmetic.

**Comment by benschenker** [comment]
Hey thanks for posting this!

Confirmed.  I know there have been some recent changes to the way those tests work, so that may be why they aren't working properly.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2282
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2236
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2231
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2217
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2179
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2141
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2077
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1999
