### ISSUE TITLE
Waypoint: Give your JavaScript Slot Machine some stylish images

### ISSUE THREAD

**Issue by KleoPetroff** [FreeCodeCamp/FreeCodeCamp#2364]
Challenge http://freecodecamp.com/challenges/waypoint-give-your-javascript-slot-machine-some-stylish-images has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The first test case (**Use the provided code three times. One for each slot**) cannot be completed. Tried several different ways, non of them worked.

![Challange Bug](http://i.imgur.com/W6VyO0r.png)

- Possible duplicate of #1862

**Comment by benmcmahon100** [comment]
You are using " instead of ' in the first two jquery selectors which is why the test fails

**Comment by KleoPetroff** [comment]
@benmcmahon100 Just figured this out. It's kind of strange, taking that both single and double quotes can be used.

**Comment by benmcmahon100** [comment]
This is true but our test only allows one. I'm modifying this now

**Comment by KleoPetroff** [comment]
Sounds good.

**Comment by benmcmahon100** [comment]
Just pushed the change now. The only thing you have to do now is to consistently use one type for all three

**Comment by JessicaBrown** [comment]
I am having the same issue but do not see any errors in my quotations? 

    
    // Only change code below this line.
     $($('.slot')[0]).html('<img src = "' + images[slotOne -1] + '">');
     $($('.slot')[1]).html('<img src = "' + images[slotTwo -1] + '">');
     $($('.slot')[2]).html('<img src = "' + images[slotThree -1] + '">');
    
    // Only change code above this line.

**Comment by JessicaBrown** [comment]
// Only change code below this line.
     $($(".slot")[0]).html("<img src = "" + images[slotOne -1] + "">");
     $($(".slot")[1]).html("<img src = "" + images[slotTwo -1] + "">");
     $($(".slot")[2]).html("<img src = "" + images[slotThree -1] + "">");
    
    // Only change code above this line.


when i change all to "  the error reads  missing ) after argument list

**Comment by KleoPetroff** [comment]
Hi Jessica, your first example should work, just remove the spaces between the slot variables and `-1`(i.e `images[slotOne-1]`).

**Comment by gonzoblasco** [comment]
I'm using the exact same code that @JessicaBrown  but with our the spaces but still not working.

    $($('.slot')[0]).html('<img src = "' + images[slotOne-1] + '">');
    $($('.slot')[1]).html('<img src = "' + images[slotTwo-1] + '">');
    $($('.slot')[2]).html('<img src = "' + images[slotThree-1] + '">');

**Comment by KleoPetroff** [comment]
@gonzoblasco I've just used your code and it passed all tests. Have you tried running the tests? (clicking on "Run the tests" button) Keep in mind that if you are copy/pasting your code, the test cases won't update automatically.

**Comment by gonzoblasco** [comment]
@KleoPetroff it was the browser. I was using Chrome. When I tried Safari, it works.
