### ISSUE TITLE
Issue: Unclear / Incorrect Code in Directions

### ISSUE THREAD

**Issue by jjordan88** [FreeCodeCamp/FreeCodeCamp#2367]
Challenge: http://www.freecodecamp.com/challenges/waypoint-manipulate-javascript-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Hey guys, just a quick heads up: When deleting properties from a Javascript object, you don't need the parentheses that currently muddle up the instructions of this challenge. Try this instead:

>'We can also delete them like this:

>delete myObject.myProperty;

 

After Googling, I get what you're trying to say with the parentheses - and others will, too, probably - but why use them? They confuse things, plus the correct notation matches up on an intuitive level with what you use to add properties. Anyway, you guys get the idea at this point, so... back to coding! 

Thanks for all your hard work - FCC is great.

**Comment by benschenker** [comment]
Thanks! This has been fixed.
