### ISSUE TITLE
[General suggestion] Typing text in the editor causing jarring effect on the context text on the left

### ISSUE THREAD

**Issue by vgvenkat** [FreeCodeCamp/FreeCodeCamp#2368]
This is just a suggestion for improvement, when the code is edited in exercises 20s and 30s of HTML5 and CSS, the context text ( the content in the left hand side ) keeps scrolling up and down, probably because of the check to see if the code entered answers the current exercise. This does not provide a good user experience to see something scrolling for every keystroke. It would be great if the validation happens without the context text scrolling up and down. 

I am using a 15" MBP and chrome.

**Comment by BerkeleyTrue** [comment]
Duplicate of #2137
