### ISSUE TITLE
Bug/clarification needed

### ISSUE THREAD

**Issue by hajrovica** [FreeCodeCamp/FreeCodeCamp#2369]
Challenge http://freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

*Select the __button element with the id of target3__ and use the jQuery addClass()function to give it the class of animated.;*

Following previous chapter this goal is already marked as complete because we had selected all button elements with jquery - using button selector not id target3

**Comment by benschenker** [comment]
Hey @hajrovica thanks for posting!

It looks like this has been resolved....Closing
