### ISSUE TITLE
Does it really make sence? :: (3 - 1 + 1)

### ISSUE THREAD

**Issue by bogvak** [FreeCodeCamp/FreeCodeCamp#2370]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-your-javascript-slot-machine-slots has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Thanks for posting an issue!

Can you post a screenshot and explain exactly what the issue is?

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
