### ISSUE TITLE
Waypoint: Learn how JSON Works

### ISSUE THREAD

**Issue by willbonds** [FreeCodeCamp/FreeCodeCamp#2371]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-json-works has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

There are no real instructions. What is the student supposed to do?

I also can't get to the Help Room from there.

**Comment by rsprice** [comment]
@willbonds I tried to follow the link you provided and I got this message:

"404: We couldn't find a challenge with the name `waypoint-learn-how-json-works` Please double check the name."

Maybe if you provide some more information we could help you. Best of luck!

**Comment by willbonds** [comment]
As soon as I mentioned it on Gitter, the JSON waypoints were taken down off
the MAP.

On Thu, Aug 20, 2015 at 8:39 PM, Ryan Price <notifications@github.com>
wrote:

> @willbonds <https://github.com/willbonds> I tried to follow the link you
> provided and I got this message:
>
> "404: We couldn't find a challenge with the name
> waypoint-learn-how-json-works Please double check the name."
>
> Maybe if you provide some more information we could help you. Best of luck!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2371#issuecomment-133240996>
> .
>



-- 
Richard Gay -- Austin, TX

**Comment by rsprice** [comment]
@willbonds spooky! :ghost:

**Comment by willbonds** [comment]
Well, the guy said he was still working on them. Not really cool, to post
before done and tested, but there you go.

On Thu, Aug 20, 2015 at 8:47 PM, Ryan Price <notifications@github.com>
wrote:

> @willbonds <https://github.com/willbonds> spooky! [image: :ghost:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2371#issuecomment-133243343>
> .
>



-- 
Richard Gay -- Austin, TX

**Comment by rsprice** [comment]
@willbonds hey it's still free right? Those folks are doing the best they can. Sorry for the annoyance though. I can see how that would be frustrating.

Happy coding! :smile:

**Comment by willbonds** [comment]
Can't argue with free unless it's a free bullet to the head.

On Thu, Aug 20, 2015 at 8:53 PM, Ryan Price <notifications@github.com>
wrote:

> @willbonds <https://github.com/willbonds> hey it's still free right?
> Those folks are doing the best they can. Sorry for the annoyance though. I
> can see how that would be frustrating.
>
> Happy coding! [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2371#issuecomment-133244691>
> .
>



-- 
Richard Gay -- Austin, TX

**Comment by BerkeleyTrue** [comment]
Sorry about that. Looks like they where accidentally released before they where ready.
