### ISSUE TITLE
Missing Waypoint completion option

### ISSUE THREAD

**Issue by voodoobettie** [FreeCodeCamp/FreeCodeCamp#2372]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-json-works has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This challenge has no way to mark it completed.
![screenshot from 2015-08-20 16 07 27](https://cloud.githubusercontent.com/assets/8313503/9397847/9edd460a-4755-11e5-9120-a53cbac46870.png)

**Comment by voodoobettie** [comment]
The rest of the Waypoints in this section seem to all have missing instructions and completion options.

**Comment by BerkeleyTrue** [comment]
Sorry about that. Looks like they where accidentally released before they where ready.
