### ISSUE TITLE
Assert function code displaying during challenges

### ISSUE THREAD

**Issue by anthonymi4** [FreeCodeCamp/FreeCodeCamp#2373]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-nthtolast-character-in-a-string has an issue. 

![image](https://cloud.githubusercontent.com/assets/2571765/9397892/1b044600-4799-11e5-8c4d-34e8aae85119.png)

Thanks

**Comment by benschenker** [comment]
Thanks for posting an issue!
That should be showing up there. It's part of all the javascript based challenges that you are able to see the tests that are running against your code. See #2231 for a similar issue/explanation.
