### ISSUE TITLE
continue to next lesson console doesn't recognize my code has been entered

### ISSUE THREAD

**Issue by JAWs41493** [FreeCodeCamp/FreeCodeCamp#2374]
Challenge http://www.freecodecamp.com/challenges/waypoint-give-a-background-color-to-a-div-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![freecodecamp](https://cloud.githubusercontent.com/assets/13168836/9397832/a1b1fcf4-476e-11e5-9d20-c9b901f6b15f.png)

this was done on August 20th, maybe i'm missing something, but based on previous people's reports of this link I don't think it's the same.

**Comment by benschenker** [comment]
Thanks for posting an issue!

Read very carefully, it looks like it is asking you to create a css class selector called `gray-background` and then give the `<div>` element that class.
