### ISSUE TITLE
Console Only Prints Final Pushed Value in For Loop

### ISSUE THREAD

**Issue by jjordan88** [FreeCodeCamp/FreeCodeCamp#2375]
Challenge http://www.freecodecamp.com/challenges/waypoint-iterate-with-javascript-for-loops has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Hey guys, just letting you know that on JavaScript Challenge #27, Looping w/ For, you only see the last pushed value no matter which code you use. Even copy & pasting the example code and changing "ourArray" to "myArray" so it fits the instructions doesn't fix it. It greenlights you, too, which is problematic (I suppose you might be *technically* correct, but...).

Anyway, back to work. Thanks for listening!

P.S.: The same issue exists in the next challenge (the one dealing w/ while loops).

**Comment by benschenker** [comment]
Hey thanks for posting an issue!

Can you post a screenshot here?

**Comment by jjordan88** [comment]
Sure! Here you go. 

![fcc_help_capture](https://cloud.githubusercontent.com/assets/13579618/9398811/6bb8b0f6-4779-11e5-8115-9c085412f2cf.PNG)

By the way, I'm one of those users who happen to be getting source code in their module instructions. It's not a big deal or anything, but I imagine you guys didn't intend for it to happen.

Let me know if I can do anything else to help. Have a good night!

**Comment by rsprice** [comment]
@jjordan88 I really don't see an issue here personally. To my knowledge the console really shouldn't be printing anything. Furthermore, it looks like you passed all the tests and received the exact same results as I did.

Not really sure what went wrong for you, but it looks like you passed the exercise and you're back to coding. GL to you, and happy coding. :)

**Comment by benschenker** [comment]
Looks like you got it right!

You are referring to the black bar that has the number `5` on the right.  That just outputs the result of the last command which happens to be `myArray.push(5)`.  The `.push` command returns the new length of the array that it just modified (see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push#Returns).


Which source code are you referring to? The example with `ourArray` or the tests next to those checkmarks?

**Comment by jjordan88** [comment]
Hey @benschenker 

Sorry for the late reply! Yeah, the test / module passed because the code was correct, but should the output not have been all the numbers (0 - 4) rather than just 5? 

Actually, it looks like you may've just answered that question....  the array *contains* the numbers, but .push simply outputs the newly modified array's length. Got it! 

As for source code, it's kinda fuzzy, but it's the Javascript next to the checkmarks in the screenshot. The first bit starts with:

> assert(editor.getValue().match

...and continues on from there.

Hope this helps! Thanks again. Have a good night, all.

**Comment by benschenker** [comment]
Yes exactly that `assert...` code is there on purpose to show you how your code is being tested.  You can ask more questions about the specifics of this in gitter.  Good night.

This issue can now be closed.

**Comment by jjordan88** [comment]
:+1:
