### ISSUE TITLE
JavaScript code for processing student input in editor is visible

### ISSUE THREAD

**Issue by boby2** [FreeCodeCamp/FreeCodeCamp#2376]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The JS instructions for processing the lesson are visible in the instructions.
![image](https://cloud.githubusercontent.com/assets/10733494/9398326/a678a772-476b-11e5-8cd7-08178bdf9b6a.png)

**Comment by benschenker** [comment]
Thanks for posting this issue!
That should be showing up there. It's part of all the javascript based challenges that you are able to see the tests that are running against your code. See #2231 for a similar issue/explanation.

**Comment by boby2** [comment]
You're welcome and I was interested in what I was seeing....the test code that is.  It does make the test instructions difficult to read though.  Just an opinion, but nothing that deters me. :)
