### ISSUE TITLE
waypoint-nest-an-anchor-element-within-a-paragraph

### ISSUE THREAD

**Issue by ataraxiax** [FreeCodeCamp/FreeCodeCamp#2377]
Challenge http://freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I have clearly nested my anchor link inside of of a paragraph <p> and </p> yet the waypoint wont complete. 
![waypoint-nest-an-anchor-element-within-a-paragraph](https://cloud.githubusercontent.com/assets/13895370/9398823/4b1ee674-4771-11e5-82c3-ef1e84e281b5.jpg)

**Comment by benschenker** [comment]
Hey thanks for posting an issue!

You need to delete your `<a>` tag on line 30 because it is trying to find the `<p>` around that tag instead of the one you added below.

**Comment by ataraxiax** [comment]
Thank you very much! I was wondering why it wouldn't complete when I was
reasonably sure my code was correct. Super helpful!
