### ISSUE TITLE
Page will not load completely

### ISSUE THREAD

**Issue by luis-fonseca** [FreeCodeCamp/FreeCodeCamp#2378]
Challenge http://freecodecamp.com/challenges/waypoint-declare-javascript-variables has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Both the code editor on the right side as the small challenges on the left are strangers.I have changed my browser to try and they do not carry through.
![captura_de_tela](https://cloud.githubusercontent.com/assets/5729008/9398876/c2d499f0-4782-11e5-8b97-b394b76c7f7d.png)

**Comment by benschenker** [comment]
Thanks for posting an issue!
Can you explain what you mean?  It is asking you to declare a variable `myName` and set it equal to a string containing your name on line 2.

**Comment by luis-fonseca** [comment]
Hello!

In the exercises about jQuery, each lesson proposed some steps to complete it. The screen was as the picture 1, showing all fully loaded and each completed step showed a "check"::
![captura_de_tela](https://cloud.githubusercontent.com/assets/5729008/9399886/e774d9ec-4790-11e5-91fe-07eaba3b62f7.png)

In Javascript exercises, the screen both the right and left are not fully loaded. In place of "checks" there javascript code.

**Comment by benschenker** [comment]
Yes that is correct, it shows you the exact code that it runs to test your JS exercises.

This is on purpose to help you see better what test is failing and why.

**Comment by luis-fonseca** [comment]
Got it. Thank you for the answer!
