### ISSUE TITLE
Can you please add back my Way points for basic Javascript I completed before the system updated?

### ISSUE THREAD

**Issue by cobunny** [FreeCodeCamp/FreeCodeCamp#2379]
Hello,
Can you please add back my Way points for basic Javascript I completed before the system updated?
I really don't want to spend more time on it.  I am on the tight schedule for other things.

**Comment by BerkeleyTrue** [comment]
> If the challenge you were last doing disappeared, don't worry - you can just keep going. If you have time to go back and try our new challenges, they should be a quick review for you. Otherwise, keep moving forward.

@cobunny Just keep moving forward. No need to go back.
