### ISSUE TITLE
Inability to login

### ISSUE THREAD

**Issue by Buzzlightyear90** [FreeCodeCamp/freecodecamp#238]
When I was logging in today, I know my username and password because I saved it but it keeps saying invalid. When I click on the reset password link it says: "Password reset token is invalid or has expired." every time. I know it is not me and I am wondering if something is wrong.

**Comment by BerkeleyTrue** [comment]
Can you try clearing your cookies?

**Comment by Buzzlightyear90** [comment]
I did and that didn't work

**Comment by BerkeleyTrue** [comment]
Ok thanks, we are looking into it at this very moment.

**Comment by BerkeleyTrue** [comment]
What email are you using.

**Comment by BerkeleyTrue** [comment]
Looks like we are able to reproduce the issue and are looking into it.

**Comment by Buzzlightyear90** [comment]
I would give you my email but I don't want to share it on here.

**Comment by QuincyLarson** [comment]
@Buzzlightyear90 No worries - we've fixed the issue. Thank you for reporting it. In order to log into your account, just click "forgot my password" and it will reset your password. You shouldn't have this issue again.
