### ISSUE TITLE
No GitHub Login on Desktop

### ISSUE THREAD

**Issue by xchelm** [FreeCodeCamp/FreeCodeCamp#2380]
Hi,

I recently signed up for FreeCodeCamp through mobile, but when I tried to access through my desktop, I could not sign in. The desktop login page does not have a GitHub sign in. I would like to avoid making two profiles on your site. Let me know, thanks!

**Comment by BerkeleyTrue** [comment]
Can you take some screen caps.

**Comment by xchelm** [comment]
Mobile Log In
![img_0933](https://cloud.githubusercontent.com/assets/12617550/9414949/dee1cfb4-47f0-11e5-9f05-1488906cba4d.PNG)

Desktop Log In
![screen shot 2015-08-21 at 10 39 52 am](https://cloud.githubusercontent.com/assets/12617550/9414977/11660d88-47f1-11e5-9905-bc302f691e0b.png)

**Comment by benschenker** [comment]
Have you tried doing a hard refresh in your browser? CMD + R on Mac and CTRL + F5 on Windows

**Comment by xchelm** [comment]
Tried a hard refresh and I get the same page. I am on a MAC.

**Comment by xchelm** [comment]
I can see it when I 'inspect element', but it does not show up. I am on Chrome.

![screen shot 2015-08-21 at 11 00 29 am](https://cloud.githubusercontent.com/assets/12617550/9415390/e480493e-47f3-11e5-8929-63ba253c0f35.png)

**Comment by xchelm** [comment]
I went ahead and added /auth/github to the end of my url and signed in.

**Comment by benschenker** [comment]
Can you open the console tab to see what those errors are?

**Comment by xchelm** [comment]
![screen shot 2015-08-21 at 11 11 26 am](https://cloud.githubusercontent.com/assets/12617550/9415620/72482ae2-47f5-11e5-8222-abceece3c292.png)

For your information, I have an Adguard for Chrome.

**Comment by BerkeleyTrue** [comment]
Can you try opening the same page using an incognito browser tab. It could be an extension messing with the page. These buttons are there in the html as can be seen in your screen cap. There is no  reason on our end why these wouldn't show up as this page is always served the same. Even if the css wasn't delived the buttons would still be there, just with no style.

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
