### ISSUE TITLE
Incorrect code listed for selecting all buttons

### ISSUE THREAD

**Issue by hanginglanterndesign** [FreeCodeCamp/FreeCodeCamp#2381]
Challenge http://www.freecodecamp.com/challenges/waypoint-disable-an-element-using-jquery has an issue. Looks like the selector here should be $('button') rather than $('#button')?

![image](https://cloud.githubusercontent.com/assets/13269193/9399433/10969f4a-4769-11e5-832d-b8b109599c14.png)

**Comment by benschenker** [comment]
Hey thanks for submitting this! Someone else posted this issue too: See #2014 for more info, it seems like this will be fixed with Pull Request #2018

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
