### ISSUE TITLE
Although I accomplished the task, it wont be accsepted

### ISSUE THREAD

**Issue by GFrozoni** [FreeCodeCamp/FreeCodeCamp#2382]
Challenge http://freecodecamp.com/challenges/bonfire-factorialize-a-number has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

As described in the text, I made my way through the task. The answer which I might have found may not have been expected, but I do believe it is right.

The code I proposed is in the image.
![screen shot 2015-08-20 at 10 35 30 pm](https://cloud.githubusercontent.com/assets/13526868/9399515/da47b6b8-478b-11e5-8751-dce3365bd6e1.png)

Here is what I wrote:
var x=2;
function factorialize(num) {
  var y=num;
  while (x<y){
    num = num * x;
    x= x +1 ;
  }
  return num;
}

factorialize(20);

The results sums to match what was expected.

**Comment by benschenker** [comment]
Thanks for posting an issue.

It looks like your function will only work the first time it is called (as `x` will be equal to `num).  Keep at it and feel free to post on gitter for more help.
