### ISSUE TITLE
Typo in "disable an element using jquery"

### ISSUE THREAD

**Issue by AlexFromOmaha** [FreeCodeCamp/FreeCodeCamp#2383]
Current text: Here's how you would disable all buttons: $('#button').prop('disabled', true);

Actual solution wouldn't include the id marker.

Challenge http://www.freecodecamp.com/challenges/waypoint-disable-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey thanks for submitting this! Someone else posted this issue too: See #2014 for more info, it seems like this will be fixed with Pull Request #2018

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
