### ISSUE TITLE
Unnecessary lines in instruction

### ISSUE THREAD

**Issue by nguyenthethong1996** [FreeCodeCamp/FreeCodeCamp#2385]
Challenge http://freecodecamp.com/challenges/waypoint-declare-javascript-variables has an issue.
![capture](https://cloud.githubusercontent.com/assets/8380567/9400054/b3feb76c-47e6-11e5-941e-752eb2140783.PNG)

**Comment by benschenker** [comment]
Thanks for submitting an issue!
That should be showing up there. It's part of all the javascript based challenges that you are able to see the tests that are running against your code. See #2231 for a similar issue/explanation.  Also feel free to post in gitter if there is something that you don't understand.

**Comment by rsprice** [comment]
@nguyenthethong1996 I'm sorry, I don't follow. What exactly is the issue?

**Comment by nguyenthethong1996** [comment]
@benschenker: I'm understanding. Many thanks for your fast response. 
@rsprice: It's ok now. Thanks

**Comment by rsprice** [comment]
@nguyenthethong1996 No problem. Have a good one! :smile:
