### ISSUE TITLE
Editor is blank

### ISSUE THREAD

**Issue by ShannonCasillas** [FreeCodeCamp/FreeCodeCamp#2386]
Challenge http://freecodecamp.com/challenges/waypoint-ditch-custom-css-for-bootstrap has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
<img width="1411" alt="screen shot 2015-08-20 at 10 34 42 pm" src="https://cloud.githubusercontent.com/assets/12515269/9400134/c4b4194a-478b-11e5-9dfb-0650b6882421.png">

Code is not preloading into exercises.

**Comment by benschenker** [comment]
Hey thanks for posting this issue!

I'm having trouble replicating it.  Can you do a hard refresh of your browser (CMD + R in Mac, CTRL + F5)

**Comment by ShannonCasillas** [comment]
I did the CMD + R and it is still coming up blank

**Comment by BerkeleyTrue** [comment]
@ShannonCasillas Which browser are you using?

**Comment by ShannonCasillas** [comment]
I figured out the issue. I had a private window open, I tried it using a regular window and it worked. Thanks!

**Comment by benschenker** [comment]
Hmm, is that something that freecodecamp wants to support?
