### ISSUE TITLE
waypoint find the nthtolast character unit test message

### ISSUE THREAD

**Issue by Jassade** [FreeCodeCamp/FreeCodeCamp#2387]
Challenge http://freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-nthtolast-character-in-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The second unit test message claims that we need to find the third last letter, but the instructions want the second to last.
assert(editor.getValue().match(/\.length/g), 'You have to use .length to get the third last letter.');

**Comment by benschenker** [comment]
Thanks for posting!
It looks like the message is incorrect but the test still works.  Is it showing up as passing for you?

**Comment by Jassade** [comment]
Indeed, I should have added that it was only cosmetic.
