### ISSUE TITLE
Error "Program Execution Failure - No user tests were run."

### ISSUE THREAD

**Issue by ScottPesetsky** [FreeCodeCamp/FreeCodeCamp#2388]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-last-character-in-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Got this error "Program Execution Failure - No user tests were run."

![waypoint use bracket notation to find the last character in a string free code camp](https://cloud.githubusercontent.com/assets/6602253/9400287/a89f632a-4774-11e5-97cd-50a6aeb7f8bf.png)

**Comment by benschenker** [comment]
Hey thanks for posting this issue!

I'm having trouble replicating it. Can you do a hard refresh of your browser (CMD + R in Mac, CTRL + F5 in Windows)

Your code looks right though, so great job with that!

**Comment by benschenker** [comment]
Scratch that, I see a bug.  Remember that the case of your letters matter in variables.  Check out line 7 and look very closely for the error.

**Comment by ScottPesetsky** [comment]
Ahh, I got it, and passed. Thanks for your help!
