### ISSUE TITLE
Question needs rewrite

### ISSUE THREAD

**Issue by ScottPesetsky** [FreeCodeCamp/FreeCodeCamp#2389]
Challenge http://www.freecodecamp.com/challenges/waypoint-write-reusable-javascript-with-functions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I got the right answer, but the question wasn't a good guide. I suspect the question can be tightened up. Should I  propose replacement text? You 'issue readers' likely know better.

**Comment by benschenker** [comment]
Yes that description of functions could definitely be more robust and explanatory.
You can propose replacement text here or preferably in a pull request.

**Comment by benschenker** [comment]
Looks like in #2166 it was made clear that a pull request is the best way to do it.  Feel free to ask in gitter about that.

**Comment by benschenker** [comment]
Seems like this is a duplicate of #1936.  Please follow that issue for updates
