### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by Daavid** [FreeCodeCamp/freecodecamp#239]
I joined last night and everything was fine. Today I was unable to login using my email address. It said email not associated yet when I went to sign up again it said email address is already being used. something like that. That is true because I already signed up. Please help so I can log back in.
email address: Daavid2077@gmail.com

**Comment by BerkeleyTrue** [comment]
Thanks for reporting. Can you try clearing your cookies?

**Comment by BerkeleyTrue** [comment]
Going to close this as it seems to be related to https://github.com/FreeCodeCamp/freecodecamp/issues/238 

if we find that their is two different causes we will re-open your issue.

Please follow up here https://github.com/FreeCodeCamp/freecodecamp/issues/238

**Comment by Daavid** [comment]
Yes I did and then had to reset my password, and now I'm back in- yeah...
thanks!

On Thu, Mar 19, 2015 at 5:02 PM, Berkeley Martinez <notifications@github.com

**Comment by QuincyLarson** [comment]
I'm glad you were able to reset your password. We've fixed the issue. You might have to reset your password next time you try to log in.
