### ISSUE TITLE
WP Bootstrap Wells: Conflict/Confusion in instructions

### ISSUE THREAD

**Issue by webdevjeffus** [FreeCodeCamp/FreeCodeCamp#2391]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

There seems to be a conflict between the last paragraph above the "Go to Next Challenge" button, and the first test-item below the "Reset/Help/Bug" buttons (see screenshot, below). It is not clear if the \<div class="well">'s should go inside the \<div class="col-xs-6">'s, or vice versa. If I were to follow ALL the directions to the letter, I'd have two \<div class="col-xs-6">'s nested inside each of two \<div class="well">'s, each of which is inside an outer \<div class="col-xs-6">.

I think this is just a text-editing problem, because my code passes when I did what I expected the waypoint to be looking for: an empty \<div class="well"> inside each of the previously-placed \<div class="col-xs-6">'s; this is included in the screenshot, as well.

Also, I am fairly the text is missing a "<", where I've sloppily drawn it in on my screenshot.

![create_bootstrap_wells](https://cloud.githubusercontent.com/assets/12986672/9401238/4c9ae31c-479a-11e5-9f26-7c2878bafae7.PNG)

**Comment by matchingtragedy** [comment]
I ran into this also. The challenge validates when you follow the instructions in the explanatory text. It does not validate when you only follow the instructions in the checkpoints.
