### ISSUE TITLE
WP Target Parent jQuery: Typos

### ISSUE THREAD

**Issue by webdevjeffus** [FreeCodeCamp/FreeCodeCamp#2392]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

There are two typos in this waypoint, as indicated in the screenshot:

![target_parent_jquery](https://cloud.githubusercontent.com/assets/12986672/9401660/de23eda0-47a0-11e5-8ac0-794b65bfd392.PNG)

In the first paragraph, remove the "s" from the word "elements."

In the second test, the close-paren needs to immediately follow the open-paren, and should not appear at the end of the sentence.

**Comment by issyl0** [comment]
Thanks for reporting this! The referenced commit fixes one of your issues, and the other (closing parenthesis) had already been fixed!
