### ISSUE TITLE
Confusing Question

### ISSUE THREAD

**Issue by Eiseldora** [FreeCodeCamp/FreeCodeCamp#2393]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Bootstrap has a class called well that can create a visual sense of depth for your columns.
Nest one div element with the class well within each of your col-xs-6 div elements.

Nest both of your div class="col-xs-6" elements within your div class="row" element.

I tried to solve by creating additional div tags but it continued to indicate that the challenge had not been completed.

Code:
```html
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well"></div>
    </div>
    <div class="col-xs-6">
      <div class="well"></div>
    </div>
  </div>
<div class="row">
    <div class="col-xs-6">
    </div>
    <div class="col-xs-6">
    </div>
  </div>
</div>
```

**Comment by BerkeleyTrue** [comment]
Hello @Eiseldora 

This code seems to work for me. Can you take a screen cap?

**Comment by Eiseldora** [comment]
![create bootstrap wells](https://cloud.githubusercontent.com/assets/8946787/9402712/c4ede1ee-4794-11e5-99cc-5a51f409033c.jpg)

**Comment by AEA2002** [comment]
I believe one div, not two, has the class of "row"

**Comment by benmcmahon100** [comment]
@Eiseldora you have an extra row with extra col-xs-6's inside of them

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.

**Comment by sol687** [comment]
had trouble with this challenge too! thanks for the help

**Comment by mahrukh-malik-1003** [comment]
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well"></div>
   
    <div class="col-xs-6">
      <div class="well"></div>
    </div>
  </div>
 <div class="row">
    <div class="col-xs-6">
      <div class="well"></div>
   
    <div class="col-xs-6">
      <div class="well"></div>
    </div>
  </div>
  </div>
</div>

**Comment by Saladg** [comment]
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    
    <div class="col-xs-6 well"><div class="well"></div>

    </div>
    
    <div class="col-xs-6 well"><div class="well"></div>
    
    </div>
    
  </div>
</div>

**Comment by geecheeche** [comment]
This is what worked, if it still is giving you trouble:

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6"><div class="well"></div>

    </div>
    <div class="col-xs-6"><div class="well"></div>

    </div>
  </div>
</div>

**Comment by kulkarnionkar** [comment]
![error](https://cloud.githubusercontent.com/assets/13956185/14519452/983dbdb4-023c-11e6-847e-80b953664105.PNG)
find my snapshot for same provlem

code as per below 

`<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">

    </div>
    <div class="col-xs-6">

    </div>
  </div>
</div>`

**Comment by kulkarnionkar** [comment]
got the solution

use this code 

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
<div class="well">
    </div>
    </div>
    <div class="col-xs-6">
<div class="well">
      </div>
    </div>
  </div>
</div>

**Comment by kulkarnionkar** [comment]
(
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
<div class="well">
    </div>
    </div>
    <div class="col-xs-6">
<div class="well">
      </div>
    </div>
  </div>
</div>

)

**Comment by faioc** [comment]
This one work

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">



      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">



      </div>
    </div>
  </div>
</div>

**Comment by faioc** [comment]
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">



      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">



      </div>
    </div>
  </div>
</div>

**Comment by msweeneys** [comment]
have trouble with this one


Nest all of your radio buttons inside one div with the class row.
Nest each of your radio buttons inside its own div with the class col-xs-6.
Make sure each of your div elements has a closing tag.

**Comment by texas2010** [comment]
@msweeneys 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by Srivanipatha** [comment]
<div class="row">
    <div class="col-xs-6">
    </div>
    <div class="col-xs-6">
    </div>
  </div>
</div>

**Comment by Srivanipatha** [comment]
the above code of the issue should be written

**Comment by balajichari31** [comment]
<! the right answer. You have to take one <!div> from the middle and place it in the end to get the answer>
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  
    <div class="row">
   <div class="col-xs-6">
     <div class="well">
   </div>
      </div>
    
  <div class="col-xs-6">
    <div class="well">  
    </div>
  </div>
  </div>
    </div>
