### ISSUE TITLE
Mutations, one of the tests has invalid text

### ISSUE THREAD

**Issue by Harmitage** [FreeCodeCamp/FreeCodeCamp#2397]
http://freecodecamp.com/challenges/bonfire-mutations

expect(mutation(['zyxwvutsrqponmlkjihgfedcba', 'qrstu'])).to.be.true;
expected [ Array(2) ] to be true

instead of

expected mutation(['zyxwvutsrqponmlkjihgfedcba', 'qrstu']) to be true

**Comment by Harmitage** [comment]
http://freecodecamp.com/challenges/bonfire-where-art-thou
Same for Where art thou first test:
should return an array of objects: expected [] to deeply equal [ Array(1) ]

**Comment by BerkeleyTrue** [comment]
That is how Arrays are `console.log` logged out. We choose to display the exact output of tests as this most closes fits real world debugging.


Happy Coding!
