### ISSUE TITLE
Early Completion

### ISSUE THREAD

**Issue by Eiseldora** [FreeCodeCamp/FreeCodeCamp#2398]
Challenge http://www.freecodecamp.com/challenges/waypoint-label-bootstrap-buttons has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The instructions were to add text to buttons, but it let me complete the challenge before the code had been completely finished. I got credit and points.

I started out by adding text to each button and planned to go back and update the numbers, but the Green go to my next challenge started to wiggle before I was done. I clicked on it to see if it would give me an error and it advanced me to the next challenge.

Instructions:
Waypoint: Label Bootstrap Buttons

Just like we labeled our wells, we want to label our buttons.

Give each of your button elements text that corresponds to their id.

Code that let me pass:
```html
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target1</button>
        <button class="btn btn-default target" id="target3">#target1</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```
![label bootstrap buttons](https://cloud.githubusercontent.com/assets/8946787/9402930/18009bf4-4797-11e5-8f6c-57ce114fe5b3.png)

**Comment by bugron** [comment]
Dear camper, your issue is related to:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2393

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
