### ISSUE TITLE
typo on http://www.freecodecamp.com/about

### ISSUE THREAD

**Issue by darrenburgess** [FreeCodeCamp/freecodecamp#24]
Last paragraph - 'persevere' is spelled incorrectly as 'perservere'
![about_free_code_camp_and_our_team_of_volunteers___free_code_camp](https://cloud.githubusercontent.com/assets/7114602/5740592/cfcbe6c4-9bd2-11e4-8cc8-ed3c319ad01e.jpg)

**Comment by terakilobyte** [comment]
Good catch, thanks! I've gone ahead and committed a fix correcting the typo. In the future, if you notice something small like this you can actually find the file in our repository (in this case it was in /partials/faq.jade) click the little icon in the top right of the window that looks like a pencil, and fix it yourself. Then just click on commit changes and submit a pull request.

**Comment by darrenburgess** [comment]
Thanks Nathan

I did fork the repo and tried to submit a pull request, but could not figure out how. Will save that for another day.

Curious question (because I am interested in general in business models):

How will freecodecamp make money? Or is it just pure open source all the way through to the business model?  At first I thought perhaps the non profits were being charged something.

Darren

**Comment by terakilobyte** [comment]
You will have to ask Quincy that question, I don't really feel at liberty
sharing the planning details.

**Comment by QuincyLarson** [comment]
Hi Darren, you can read about our plans here: http://blog.freecodecamp.com/2014/10/free-code-camp-doesnt-make-money-and.html
