### ISSUE TITLE
Answer Not Completed, but system says OK

### ISSUE THREAD

**Issue by Mashadim** [FreeCodeCamp/FreeCodeCamp#2402]
Challenge http://freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue. 

The instructions were:

"Let's remove the btn-default class from all of our button elements.
Here's how you would do this for a specific button, add $("#target2").removeClass("btn-default");"

But even before I typed in "btn-default", it said my answer was already correct:
http://postimg.org/image/4sts8kj5f/

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2302
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2301
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2197
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2160
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1923
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1898
Fixed.
