### ISSUE TITLE
Object Oriented Programming: Understand the Constructor Property returns boolean values in example

### ISSUE THREAD

**Issue by mail-liam** [freeCodeCamp/freeCodeCamp#24026]
**Describe your problem and how to reproduce it:**
Following the discussion in [#18925](https://github.com/freeCodeCamp/freeCodeCamp/issues/18925), here is another instance of an example (`joinBirdFraternity`) returning boolean values instead of using a boolean expression. Do we want this to be brought in line similar to the changes being made there?

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/understand-the-constructor-property

**Comment by tfantina** [comment]
Based on what I've read from  [#18925](
https://github.com/freeCodeCamp/freeCodeCamp/issues/18925), @mail-liam are you thinking of something like: `return "Can Join"
} else {
return "Can not join?"}
`
Do you want to use the ternary operator?
If that's what your thinking and there is a consensus I'd be happy to make this little change.

**Comment by mail-liam** [comment]
Sounds good to me! "Birds are welcome!" and "Sorry, only birds may join." are what I was thinking of, but shorter is probably better as far as the examples are concerned.

**Comment by moT01** [comment]
Closing as stale. Thanks and happy coding!
