### ISSUE TITLE
Very Confused

### ISSUE THREAD

**Issue by JAWs41493** [FreeCodeCamp/FreeCodeCamp#2403]
![untitled](https://cloud.githubusercontent.com/assets/13168836/9404935/9687932c-47c1-11e5-8862-d308cc17eea1.png)
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by KleoPetroff** [comment]
You can check this thread, as the person had the same issue like you - #2354.

You must select the `left-well` element using the `parent()` method, not the parent element of the `left-well`.

**Comment by BerkeleyTrue** [comment]
closing as duplicate. Please feel free to reopen with steps to replicate your issue if it still persists.
