### ISSUE TITLE
create css class error

### ISSUE THREAD

**Issue by agusalay** [FreeCodeCamp/FreeCodeCamp#2405]
Challenge http://freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

if camper not delete h2 in style, i think they can't move to the next challenge.

![image](https://cloud.githubusercontent.com/assets/8485780/9405331/2192ddbe-4821-11e5-9bb5-a907f571eb89.png)

**Comment by benschenker** [comment]
Thanks for pointing this out!

The code that should fail:
```
<style>
  h2 {
    color: red;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
```
