### ISSUE TITLE
Instructions not clear

### ISSUE THREAD

**Issue by PhillFlippy** [FreeCodeCamp/FreeCodeCamp#2406]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-pop has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The instructions of this waypoint are not clear, it has some code and it has the wrong array name 
![asd](https://cloud.githubusercontent.com/assets/13272639/9406365/47586132-4843-11e5-8f64-04fd232c8434.png)

**Comment by bugron** [comment]
Dear camper, your issue is related to:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2132
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1911

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
