### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by linuxthings** [FreeCodeCamp/FreeCodeCamp#2408]
Challenge http://freecodecamp.com/challenges/waypoint-size-your-images has an issue.
![Screenshot](http://i.imgur.com/Yi3d41x.png)

**Comment by fnky** [comment]
Please explain how to reproduce this issue, so it can be confirmed as a real issue, rather than a mistake :-)

**Comment by linuxthings** [comment]
Error appeared when the challenge page was loaded (Firefox 40.0/Ubuntu 14.04). I've tried to reproduce the issue but the error is gone :)

**Comment by BerkeleyTrue** [comment]
Closing as duplicate #2351
