### ISSUE TITLE
Add code execute button

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/freecodecamp#241]

**Comment by terakilobyte** [comment]
Berkeley, I'm getting a strange assertion error. Are you seeing this on your end? It happens whenever I try to load a bonfire, and is preventing any other effort on my side as it just blocks any event handlers, properties, state, the whole shebang from being rendered
https://www.evernote.com/shard/s550/sh/c2740c2c-9766-435f-9cf4-e4647cc9992e/c0a439b3415d5454f318eae78706fe88

**Comment by BerkeleyTrue** [comment]
Nope. Geez, that is the most helpful error message in the world.
