### ISSUE TITLE
Javascript exercises won't advance upon completion

### ISSUE THREAD

**Issue by redhotlizzard** [FreeCodeCamp/FreeCodeCamp#2412]
"Go to my next challenge" button in dialog does not do anything

**Comment by asandyz** [comment]
Please give us more details like the scenario in which it's causing the issue or screenshot etc.

Thanks :)

**Comment by Noblelynx** [comment]
A quick fix would be to press "ctrl+enter" when the pop-up screen shows up.

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!
