### ISSUE TITLE
Not Plagiarized from https://www.cs.rit.edu/~vcss242/Lectures/04/dijkstra-stu.pdf

### ISSUE THREAD

**Issue by shahzaib919** [freeCodeCamp/freeCodeCamp#24137]
_Originally posted by @Manish-Giri in https://github.com/freeCodeCamp/freeCodeCamp/pull/23383#issuecomment-431540703_

**Comment by shahzaib919** [comment]
It isn't at all plagiarised from the mentioned website none of the words matched with mine.

**Comment by Manish-Giri** [comment]
@shahzaib919 
> none of the words matched with mine

Really?

These are your changes -

<img width="983" alt="screen shot 2018-10-23 at 10 31 07 pm" src="https://user-images.githubusercontent.com/11348778/47402428-8590a600-d713-11e8-89bb-293bd9e8a598.png">

This is from the website -

<img width="762" alt="screen shot 2018-10-23 at 10 31 24 pm" src="https://user-images.githubusercontent.com/11348778/47402436-8d504a80-d713-11e8-8333-bfbcfff48260.png">
