### ISSUE TITLE
page doesn't load right

### ISSUE THREAD

**Issue by davidpetrey** [FreeCodeCamp/FreeCodeCamp#2414]
Challenge http://freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This shows:
assert(editor.getValue().match(/(\/\/)...../g), 'Create a \/\/ style comment that contains at least five letters');Create a // style comment that contains at least five letters

**Comment by benschenker** [comment]
Thanks for posting an issue!
That should be showing up there. It's part of all the javascript based challenges that you are able to see the tests that are running against your code. See #2231 for a similar issue/explanation.
