### ISSUE TITLE
 Waypoint: Bring your JavaScript Slot Machine to Life not responding

### ISSUE THREAD

**Issue by terencelimzhengwei** [FreeCodeCamp/FreeCodeCamp#2415]
This waypoint exercise is not responding after I entered $($). Everytime i refresh the page, it still does not respond

**Comment by BillKroger** [comment]
I also ran into this same exact problem, opened an issue a couple days ago for it https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2272

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
