### ISSUE TITLE
Basic JavaScript

### ISSUE THREAD

**Issue by davidpetrey** [FreeCodeCamp/FreeCodeCamp#2416]
Challenge http://freecodecamp.com/challenges/waypoint-check-the-length-property-of-a-string-variable has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I just started the Basic Javascript section and all the lessons are a little messed up.

**Comment by danrauf** [comment]
What do you mean by "messed up"?

**Comment by benschenker** [comment]
Thanks for posting an issue!

Can you post a screenshot and describe the problem?

Also feel free to post in the gitter chat if something is just confusing to you.

**Comment by davidpetrey** [comment]
The screen on the right. Is it supposed to have this code:

assert(editor.getValue().match(/(\/\/)...../g), 'Create a \/\/ style comment that contains at least five letters');
assert(editor.getValue().match(/(\/\*)...../g), 'Create a /\* \*/ style comment that contains at least five letters.');
assert(editor.getValue().match(/(\*\/)/g), 'Make sure that you close the comment with a \*/'); 

I thought it was a mistake because the red x's weren't changing to green check marks when I completed that requirement like they did with previous exercises. 

![image](https://cloud.githubusercontent.com/assets/13895170/9419440/499597fc-4821-11e5-8c3c-63f84cc690c6.png)

**Comment by benmcmahon100** [comment]
These are intentional. They are showing you the tests we are running against your code so that you can better figure out why your code is (not) passing

**Comment by davidpetrey** [comment]
ok.
