### ISSUE TITLE
Waypoint: Add Elements within your Bootstrap Wells

### ISSUE THREAD

**Issue by danrauf** [FreeCodeCamp/FreeCodeCamp#2417]
Challenge http://freecodecamp.com/challenges/waypoint-add-elements-within-your-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The challenge says "Nest three button elements within each of your well div elements.", but the tests pass even when you place all your buttons inside one div. It also passes tests if you've got more than 6 buttons, but I'm not sure if that should be failing tests.

Example:

```
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <button></button>
        <button></button>
        <button></button>
        <button></button>
        <button></button>
        <button></button>
        <button></button>
        <button></button>
        <button></button>
        <button></button>
      </div>
    </div>
  </div>
</div>
```

**Comment by bugron** [comment]
Dear camper, your issue is related to:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2399
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2398
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2393

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Comment by Mohab17** [comment]
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <div class="well">
        <button></button>
        <button></button>
        <button></button>
      </div>
    </div>
    <div class="col-xs-6">
      <div class="well">
        <button></button>
        <button></button>
        <button></button>
      </div>
    </div>
  </div>
</div>
