### ISSUE TITLE
Unable to go to the Next challenge

### ISSUE THREAD

**Issue by JGrummell** [FreeCodeCamp/FreeCodeCamp#2418]
Something appears to be wrong with the registering of "Next Challenge" button on the jQuery exercises. I type the proper information in for this challenge and the button is still disabled. To check, I copied the completed code in the next exercise to confirm and it is still disabled. This seems to be occurring for at least the first 4 jQuery exercises.
Challenge http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by JessZanewich** [comment]
I just did these exercises yesterday and I only had problems because of my own syntax errors. Maybe you could post a screenshot of your code? These all work, I just did the one you linked to again and it worked for me.

**Comment by JGrummell** [comment]
Good afternoon Jess,
Attached is a copy of one of the jQuery 1st exercise showing the next
challenge button disabled despite the code being entered. I should point
out that I am unfortunately forced to use IE10 so I am not sure if that is
related. Still, I did these jQuery exercises and they were updating and
occurring fine before the patch went in August and I am still able to
complete the bootstrap and HTML5 exercises. Also, if I apply the classes
directly to the buttons they animate and bounce, but the jQuery addClass
command seems to do nothing.

**Comment by benschenker** [comment]
Hey @JGrummell it is possible that this is an IE10 issue.  Are you still experiencing this? Can you post screenshots here?  I cannot see your above mentioned attachments
