### ISSUE TITLE
Bonfire: Title Case a Sentence

### ISSUE THREAD

**Issue by Problemphile** [FreeCodeCamp/FreeCodeCamp#2424]
Challenge http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence has an issue. The Bonfire asks to "Return the provided string with the first letter of each word capitalized".The sentence should be worded differently because it should specify that all the letters remaining should be lower case. I realized this just at the moment of my submission looking at the tests.

**Comment by benschenker** [comment]
Thanks for posting this issue!

Confirmed that there is a test checking that the other letters are lower cased but this criteria is not mentioned in the description.  Is this on purpose?

**Comment by avastu** [comment]
Submitted fix: https://github.com/FreeCodeCamp/FreeCodeCamp/commit/f0c025d66a334bc06f9029fb865a559e3ae8918a
