### ISSUE TITLE
there lacks a right bracket in this.

### ISSUE THREAD

**Issue by younisd** [FreeCodeCamp/FreeCodeCamp#2425]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work
At first, the text in the third instruction is right. But after add the '$(document).ready(function() {', it lost a right bracket after document. In addition, i can't get the last instrcution of 'close' right, this may be my personal fault.

**Comment by benschenker** [comment]
Thanks for posting this!

See #2394 for a duplicate issue that was filed.  I am able to get the last test to pass so it may be something that you are doing wrong...feel free to post screenshot in gitter and someone can help you out.

**Comment by benschenker** [comment]
I think i was able to replicate this.  I believe it wants you to have the `});` on a new line

**Comment by younisd** [comment]
yeah! my code was just one line, after i make a new line, it worked perfectly! thank you a lot! :)

**Comment by benschenker** [comment]
No problem.

This does seem to be a bug in the test as it should be passing without the newline.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
