### ISSUE TITLE
waypoint-learn-how-script-tags-and-document-ready-work has an issue

### ISSUE THREAD

**Issue by sainathchalluri** [FreeCodeCamp/FreeCodeCamp#2428]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

-- Even after this task : 'Close your $(document).ready(function() { function with });' is completed the error does not go away.
![waypoint-learn-how-script-tags-and-document-ready-work](https://cloud.githubusercontent.com/assets/6539669/9413166/3a641b96-47fe-11e5-9f21-d1ae1c9843f7.jpg)

**Comment by benschenker** [comment]
Hey thanks for posting this!

It looks like someone else had the same issue, take a look at #2425.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
