### ISSUE TITLE
nth-child answer acceptance.

### ISSUE THREAD

**Issue by ulmas** [FreeCodeCamp/FreeCodeCamp#2429]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue

The correct way to complete the code is:
```
$(".btn:nth-child(2)").addClass("animated bounce")
```

However, writing the code like this also marks the task as completed:
```
$(":nth-child(2)").addClass("animated bounce")
```

While the 2nd version is also technically correct, it does not necessarily answers the task.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2187
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2068
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2005
