### ISSUE TITLE
Slasher Flick weird test wording

### ISSUE THREAD

**Issue by JustMD** [FreeCodeCamp/FreeCodeCamp#2431]
Challenge http://www.freecodecamp.com/challenges/bonfire-slasher-flick has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
```
function slasher(arr, howMany) {
  // it doesn't always pay to be first
  var a=arr.slice(howMany);
  return a;
}

slasher([1, 2, 3], 2);
```
I passed this challenge without assigning the condition n>=array.length

**Comment by benschenker** [comment]
Hey thanks for posting!

Not sure if this is a bug though....the code that you wrote shouldn't need that check because when `howMany >= arr.length`, `arr.slice(howMany)` correctly returns an empty array.

**Comment by BerkeleyTrue** [comment]
You code is correct. The wording on the tests are weird. They should say exactly the expected output not what is should be when n meets some condition.

Anyone want to submit a PR to fix the test wording?

**Comment by bugron** [comment]
Closing this issue as https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2454 is merged.
