### ISSUE TITLE
Description of waypoint challenge "waypoint-manipulate-arrays-with-unshift" is not correct

### ISSUE THREAD

**Issue by asandyz** [FreeCodeCamp/FreeCodeCamp#2433]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Although the comment conveys the correct message as below 
`// Add "Paul" to the start of myArray`
`// Only change code below this line.`

The description says the following :
_Let's take the code we had last time and unshift this value **to the end** : "Paul"_
It should be **to the first**

**Comment by asandyz** [comment]
![image](https://cloud.githubusercontent.com/assets/5192613/9414276/d21e15da-4854-11e5-9a29-a9c5fa46629c.png)

**Comment by saadanerdetbare** [comment]
duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1929

**Comment by asandyz** [comment]
oh I see, thanks for pointing out :)

**Comment by dokkillo** [comment]
@asandyz  if it duplicate please close this issue :)

**Comment by asandyz** [comment]
Closing this issue.
