### ISSUE TITLE
Add properties to objects

### ISSUE THREAD

**Issue by matthew02** [FreeCodeCamp/FreeCodeCamp#2434]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-javascript-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In the remarked example code above the location where we are asked to input our new code, there is the statement `ourDog.bark("arf!");` which attempts to execute the `bark` method of the object `ourDog`. I believe the statement should read `ourDog.bark = 'arf!';`.

**Comment by benschenker** [comment]
Thanks for posting this!

Good catch here, that is a bug!

**Comment by BerkeleyTrue** [comment]
There is also another issue, delete is not a function it's a keyword, like `new` or `var`. The examples given are confusing and will make the challenge impassible.

correct usage

```
delete ourDog.tails;
```

@benmcmahon100 This is a major issue.

**Comment by BerkeleyTrue** [comment]
Fix is going up shortly.

Happy Coding!

**Comment by BerkeleyTrue** [comment]
Fix is going up shortly.

Happy Coding!
