### ISSUE TITLE
Instructions keep scrolling up

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/FreeCodeCamp#2435]
Challenge http://www.freecodecamp.com/challenges/waypoint-inherit-styles-from-the-body-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The instructions window keeps scrolling when I start typing. It's especially frustrating when I'm reading instructions.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate #2137
