### ISSUE TITLE
Should be pink.

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/FreeCodeCamp#2436]
![screen shot 2015-08-21 at 1 37 25 pm](https://cloud.githubusercontent.com/assets/13191387/9414907/dcc6e1ba-4809-11e5-97a8-8603fb0bd786.png)
Challenge http://www.freecodecamp.com/challenges/waypoint-override-styles-in-subsequent-css has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Allowed to move on to next challenge, but it shouldn't. It is supposed to be showing pink-text in the console, but it shows blue text instead. Pink should be taking precedence over blue.

**Comment by benschenker** [comment]
Thanks for posting an issue!

It looks like this is exactly the desired outcome.  If you look at the description/tests it wants the text to be blue.  The point is that the last css style (`blue-text`) takes precedence over earlier styles (`pink-text`)

**Comment by dokkillo** [comment]
@benschenker  is true.

I think this is not a bug, @SEGrooms when you are ready close this issue :)

**Comment by SEGrooms** [comment]
![screen shot 2015-08-21 at 1 55 52 pm](https://cloud.githubusercontent.com/assets/13191387/9415312/61052b38-480c-11e5-9da7-7059df584472.png)
![screen shot 2015-08-21 at 1 55 46 pm](https://cloud.githubusercontent.com/assets/13191387/9415313/61086762-480c-11e5-8c66-01567f3686a3.png)
I don't understand why these would both yield the same result.

**Comment by dokkillo** [comment]
change this:

  .blue-text {
    color: blue;
  }
  .pink-text {
    color: pink;
  }

**Comment by SEGrooms** [comment]
@dokkillo Thank you!
