### ISSUE TITLE
FreeCodeCamp not working properly on Chromebook

### ISSUE THREAD

**Issue by keishathelibrarian** [FreeCodeCamp/FreeCodeCamp#2437]
Noticed this issue the other day. The instructions panel on the left-hand side of the screen isn't working properly, so I can't verify my work and advance to the next lesson (I know I can just go to the Map and click on the next lesson, but I like the verification part to make sure my work is correct). I've been working on an Acer Chromebook 11, within the Chrome browser (obvs). Having tried refreshing the page, restarting the computer etc. to no avail. 
![screenshot 2015-08-21 at 12 37 19 pm](https://cloud.githubusercontent.com/assets/13394554/9414969/be7913b6-4801-11e5-94b3-29e9e742ff99.png)
Please advise.

Challenge http://www.freecodecamp.com/challenges/waypoint-declare-javascript-variables has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by BerkeleyTrue** [comment]
Hello @keishathelibrarian 

What version of Chrome are you using?

**Comment by benmcmahon100** [comment]
You are meant to create a variable called myName . In the screen shot you've modified a function below the comment that says "Do not modify below this line" that is responsible for making your variable's value pop up in the black box beneath the run button.

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
