### ISSUE TITLE
Some jQuery tests randomly pass and fail

### ISSUE THREAD

**Issue by izybit** [FreeCodeCamp/FreeCodeCamp#2439]
While going through jQuery there were several cases were only one of the tests would pass and fail randomly with each "redraw".

For example, I am now at waypoint 13 and the 1st test most often than not will not pass even though the code is correct.

The same thing has happened several times before and now I just move the cursor around until the test passes. I have tested it with incorrect code many times but never passes so for some reason the correct answer is most often than not considered incorrect.

This happens on Windows 10 (10525), Waterfox 39 with not adblockers running on FCC.

Any ideas?

**Comment by benschenker** [comment]
Hey @izybit are you still having this issue? Can you post a screenshot?

**Comment by izybit** [comment]
Sorry, don't check GitHub often.

Tested again on same waypoint and even though now things work much better there are still some issues.
If I run tests multiply times the first one will fail about 1 in 10 as you can see in the screenshot.

![issue 2439 - screenshot 1](https://cloud.githubusercontent.com/assets/13612952/9833507/dc8ed6b8-59a1-11e5-8b68-8dc4755b1023.PNG)

**Comment by benschenker** [comment]
Hey @izybit, Can you see if this works correctly in incognito mode in chrome?

Also can you try setting `background-color` instead of `background` to `red`?

**Comment by izybit** [comment]
@benschenker Changed the background to background-color and did the tests again.
On Waterfox 40.0.2 (portable, heavily modified) the issue remains and probably is a bit worse now.
On Firefox 40.0.3 (portable, fresh) the issue appears but much less frequently.
On Chrome 45.0.2454.85 (portable, fresh) I cannot reproduce this issue.

**Comment by BerkeleyTrue** [comment]
@izybit We only officially support Chrome at the moment.

Happy Coding.
