### ISSUE TITLE
Code comment is in incorrect place

### ISSUE THREAD

**Issue by plasticfridge** [FreeCodeCamp/FreeCodeCamp#2440]
Challenge http://freecodecamp.com/challenges/waypoint-nest-one-array-within-another-array has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

var ourArray = [["the universe", "everything", 42]];
var myArray = [];
// Only change code below this line.

// Only change code above this line.

Comment should be moved above code

**Comment by catapixel** [comment]
The comments are fine where they are. One correct solution between the comments is:
```
myArray.push(ourArray);
```
