### ISSUE TITLE
External link using anchor tag is not working

### ISSUE THREAD

**Issue by mounikagv** [FreeCodeCamp/FreeCodeCamp#2442]
Challenge http://freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey thanks for posting!

Not sure what your issue is, but the best place to ask about that is in gitter.  I'd recommend posting a screenshot there of your code.  If there is an actual problem with the challenge then post a screenshot here

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!
