### ISSUE TITLE
Code comment does not match correct implementation of solution

### ISSUE THREAD

**Issue by plasticfridge** [FreeCodeCamp/FreeCodeCamp#2443]
Challenge http://freecodecamp.com/challenges/waypoint-manipulate-javascript-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

// ourDog.bark(“arf!");

should be 

// ourDog.bark = “arf!”;

**Comment by BerkeleyTrue** [comment]
Closing as duplicate #2434
