### ISSUE TITLE
There is no loop above comment

### ISSUE THREAD

**Issue by plasticfridge** [FreeCodeCamp/FreeCodeCamp#2444]
Challenge http://freecodecamp.com/challenges/waypoint-iterate-with-javascript-for-loops has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

var myArray = [];
//Push the numbers zero through four to myArray using a “for loop" like above.

As per bug title

**Comment by ahstro** [comment]
Isn't the point of the bonfire to create the loop yourself?
