### ISSUE TITLE
Help Buttons Don't Work on Bonfire

### ISSUE THREAD

**Issue by misfist** [FreeCodeCamp/FreeCodeCamp#2445]
When on the Bonfire, clicking the Help button produces a pop-up that reads:

Need some help?
Remember to use  Read-Search-Ask.
If you've already read the errors and searched Google, you should ask for help.
This will take you to our help room.

The Take Me to the Room button has no affect.

![bonfire seek and destroy free code camp 2015-08-21 14-42-54](https://cloud.githubusercontent.com/assets/709248/9416322/f12c556e-4812-11e5-817d-ced9a431c96d.png)

Challenge http://freecodecamp.com/challenges/bonfire-seek-and-destroy has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by BerkeleyTrue** [comment]
@benschenker 
> if I remove the data-dismiss="modal" from the element it loads the help page in a new tab as it should (but it doesn't close the modal).
