### ISSUE TITLE
Rephrasing ES6: Use * to Import Everything from a File

### ISSUE THREAD

**Issue by TomerPacific** [freeCodeCamp/freeCodeCamp#24455]
**Describe your problem and how to reproduce it:**
The last 2 paragraphs of the exercise could use a rewording and some adjustments as they do not get the point across.

I.E. 

> The code below requires the contents of a file, "capitalize_strings", found in the same directory as it, imported.

The above line could use a refactoring of the statement for better readability.

> In order to utilize this method, it requires an object that receives the imported values. From here, you will use the dot notation to call your imported values.

Maybe consider saying, **In order to utilize this method, an object is required**

**Add a Link to the page with the problem:**
[Challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use--to-import-everything-from-a-file/)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 70.0.3538.67 (Official Build) (64-bit)
* Operating System: Windows 7 64bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![fccbug2](https://user-images.githubusercontent.com/23402988/47258265-786c8080-d4a1-11e8-8666-789e86565d83.jpg)

**If there is a possibility, after a clear rewording is selected, I would like to fix this issue.**

**Comment by ezioda004** [comment]
Hi @TomerPacific,

Thank you for opening this issue.
I agree the verbiage can be improved in this challenge. 

Can you explain this sentence?
>In order to utilize this method, it requires an object that receives the imported values. 

Which method are you referring to? If you meant `import * as` then it's a statement.
I think something like:
>In this challenge you need to import all the contents from `"capitalize_strings"` file. To do so, you have to use `import * as` statement and use any namespace to refer to the imported module.

Its not perfect but certainly more clear as to what needs to be done relative to the current challenge's text.

**Comment by TomerPacific** [comment]
@ezioda004 ,
The following sentence:

> In order to utilize this method, it requires an object that receives the imported values.

Was an example of a sentence that in my mind, could use some rephrasing.

**I think you are reading my comment the wrong way. The quoted text is copied directly from the challenge's description. I gave excerpts to emphasize where the description could use some polish.**

You can see the entire paragraph in the screenshot I took.

What I suggested was referring to the first part of the second paragraph and how to reword it.

**Comment by ezioda004** [comment]
Right, what I suggested was to replace the whole instruction text because:
>The code below requires the contents of a file, "capitalize_strings", found in the same directory as it, imported. Add the appropriate import * statement to the top of the file, using the object provided.

Doesnt make a whole lot of sense. There is no "code below" and there is no "object provided". The namespace object used is arbitrary (as long as its a valid identifier and is not a reserved keyword).

**Comment by TomerPacific** [comment]
@ezioda004 ,
I agree with you.
Too bad someone snatched this fix from me...

**Comment by RandellDawson** [comment]
@TomerPacific , @ezioda004 Are you satisfied with the PR's verbiage?

**Comment by TomerPacific** [comment]
@RandellDawson ,
I added a comment to the PR.
