### ISSUE TITLE
Waypoint: Manipulate Arrays With unshift

### ISSUE THREAD

**Issue by marcoshuet** [FreeCodeCamp/FreeCodeCamp#2446]
What is wrong with this code?

var myArray = ["John", 23, ["dog", 3]];
myArray.shift();
myArray.unshift(["Paul"]);

It's returning:
d[0].toLowerCase is not a function

**Comment by BerkeleyTrue** [comment]
You are adding an array to the beginning or myArray. The instructions state to add a string 'Paul'.

Please see:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-help-when-you-get-stuck

Happy Coding!
