### ISSUE TITLE
JS stating my object is not defined

### ISSUE THREAD

**Issue by HKatcrew** [FreeCodeCamp/FreeCodeCamp#2448]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-javascript-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
I am unable to drag and drop the screen shot, but here is the coding:
var myDog = {
   "name": "Camper",
   "legs": 4,
   "tails": 1,
   "friends": []
};

// Only change code below this line.

// Let's add the property bark to myDog
myDog.bark="arf!";

// Now delete the property tails
delete(mydog.tails);

**Comment by BerkeleyTrue** [comment]
Apologies for the inconvenience, but the challenge gives incorrect examples.

delete is actually a keyword, just like `var` and `new`. It's correct usage is 

```js
delete myDog.tails
```

A correction is going up soon.


Happy Coding!
