### ISSUE TITLE
"Target a Specific Child of an Element Using jQuery" detail

### ISSUE THREAD

**Issue by hallaathrad** [FreeCodeCamp/FreeCodeCamp#2449]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue. 

The instructions say to input *$(".well :nth-child(2)").addClass("animated bounce");* or *$(".target:nth-child(2)").addClass("animated bounce");* —and in fact, both work well—, but I doubt most beginners will gather this nuance from the text.

I believe an explanation is due on how the one with space searches for the second child inside, whereas the one without searches for the second sibling.

**Comment by hallaathrad** [comment]
Also, I need coffee haha

**Comment by benschenker** [comment]
Hey thanks for posting!

See #1927 for my explanation there.  It is still open and will can remain as the main issue for this problem.  Feel free to close this as a duplicate.

Also, take a look at our [Bug Posting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help!-I've-Found-a-Bug) to see the best way to resolve a problem with the site.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate
