### ISSUE TITLE
Challenge waypoint-create-bootstrap-wells has an issue

### ISSUE THREAD

**Issue by 4mifix** [FreeCodeCamp/FreeCodeCamp#2450]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

<script src="https://gist.github.com/4mifix/e93a335ed623856d3ebd.js"></script>

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!
