### ISSUE TITLE
doesn't send me to the next challenge.

### ISSUE THREAD

**Issue by roncodingenthusiast** [FreeCodeCamp/FreeCodeCamp#2452]
Challenge http://freecodecamp.com/challenges/waypoint-declare-javascript-variables has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When I completed the challenge, it showed a modal box to tell me I completed but never actually redirected me to the new page/challenge/ lesson.

**Comment by benschenker** [comment]
Hey @roncodingenthusiast thanks for reporting this!

A couple of weeks back we had a bunch of these issues, but they all seem to be fixed now.

I'm closing this as fixed but feel free to reopen if you still experience issues.
