### ISSUE TITLE
Moving all external images into the repository

### ISSUE THREAD

**Issue by ggurbet** [freeCodeCamp/freeCodeCamp#24526]
Some challenges use links to external images. These images are subject to change and can be unreachable at some point. Also some of the websites are blocked for some people (I am from Turkey and imgur is blocked here for example). Can we create an images folder and instead of linking to these external sources, link them from inside the repository?

An example challenge is: [Applied Visual Design: Create Texture by Adding a Subtle Pattern as a Background Image](https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-texture-by-adding-a-subtle-pattern-as-a-background-image/)

**Comment by parthparth** [comment]
We can host them on GitHub for one solution

**Comment by thecodingaviator** [comment]
@ezioda004 / @QuincyLarson Your thoughts on this?

**Comment by QuincyLarson** [comment]
@ggurbet @Parth-Agarwal @thecodingaviator Yes - I would like to host these on GitHub. 

Once they're hosted on GitHub, our CDN (Netlify) should pick them up, and they will be fast anyway. 

Would one of you be interested in going through and moving these images over? Where would be the best place to put these images in the file hierarchy?

**Comment by ggurbet** [comment]
Since there can be localized versions of some images, it would be better to have multiple copies in multiple locales. Here is a challenge which contains a localizable image: https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/move-a-relatively-positioned-element-with-css-offsets/ (in addition, this image is hosted on imgur which is unfortunately blocked in Turkey).

There is a tremendous amount of content but there are only a few images throughout the challenges. Maybe we can move them to the curriculum's specific localized page. For example for English we can put it under /curriculum/challenges/english/images/

What are your thoughts on this? @QuincyLarson @parthparth @thecodingaviator

**Comment by thecodingaviator** [comment]
Yes, that is a viable option, however I'm not sure how we'll import the images as React causes rendering problems and I'm not really sure how we'd integrate our markdown articles with React

**Comment by QuincyLarson** [comment]
@ggurbet Yes - I agree. Would you be interested in getting all these files together with the appropriate file names, then sending me a link to them (maybe in something like Google Drive)? I can push them to Amazon AWS S3. Then we can update the URLs in the project to use those. We could do this across all of the language forks as well.

**Comment by ggurbet** [comment]
@QuincyLarson OK, I would like do that. But it would take a while to gather them together. Then I will mail them the link to you.
And just a curious question, isn't it possible to put them inside the GitHub repository and load the pictures from inside it?

**Comment by QuincyLarson** [comment]
@ggurbet Thanks for your patience. GItHub's terms of service seem to forbid hosting images through GitHub repositories so we shouldn't do this. Instead, we will need to use S3, which is a bit more work.

**Comment by QuincyLarson** [comment]
A quick update everyone - I just spoke with the founders of Netlify and they pointed out that they now have a service specifically for this called Netlify Large Media https://www.netlify.com/blog/2019/02/26/manage-your-code-and-assets-together-with-netlify-large-media/

This may be a better solution than trying to put everything in S3 since we're already using Netlify for a lot of things.

**Comment by thecodingaviator** [comment]
As far as I understand, this requires our site being hosted via Netlify. I'm not sure we host through Netlify, do we @QuincyLarson ?

**Comment by raisedadead** [comment]
Guide has taken a different directions and we will not be needing storage solutions anymore.
