### ISSUE TITLE
Waypoint: Create a Bootstrap Headline -- accepts 1 class or the other, but not both

### ISSUE THREAD

**Issue by brooksofmaine** [FreeCodeCamp/FreeCodeCamp#2453]
Couldn't use two classes in the <h3> tag.  Got around the bug by printing the heading twice:

<h3 class = "text-primary" >jQuery Playground</h3> <h3 class = "text-center" >jQuery Playground</h3>

**Comment by brooksofmaine** [comment]
Maybe it's not a bug.  Figured out that it wants only one set of quotes, as in: class = text-primary text-center"

**Comment by allan-hernandez** [comment]
This isn't a bug, but maybe it should be made more clear in it's own Waypoint or as a hint/description. I (think) it is first shown in this Waypont - http://freecodecamp.com/challenges/waypoint-add-rounded-corners-with-a-border-radius 

The line - 

<code>
img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"
</code>

has both the <code>smaller-image</code> and <code>thick-green-border</code> classes. It is then common from that point on.

**Comment by brooksofmaine** [comment]
Hi Allen... Yes, it's my mistake.  I didn't pick up on the syntax,
even though I had used it in several Waypoints.  I suppose it could be
made more explicit, i.e., "Note that you can combine classes within
one set of quotes."  But on the other hand, I could be more observant,
too!
....Malcolm

On 21/08/2015, Allan Hernandez <notifications@github.com> wrote:
> This isn't a bug, but maybe it should be made more clear in it's own
> Waypoint or as a hint/description. I (think) it is first shown in this
> Waypont -
> http://freecodecamp.com/challenges/waypoint-add-rounded-corners-with-a-border-radius
>
>
> The line -
>
> <code>
> img class="smaller-image thick-green-border"
> src="https://bit.ly/fcc-relaxing-cat"
> </code>
>
> has both the <code>smaller-image</code> and <code>thick-green-border</code>
> classes. It is then common from that point on.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2453#issuecomment-133575729


-- 
Malcolm and Barbara Brooks
191 Beauchamp Point Rd
Rockport, Maine 04856 USA
207 701 1441
brooksofmaine@gmail.com
