### ISSUE TITLE
Guide: Let and Const - Unwanted underscores in search result and incorrect URL

### ISSUE THREAD

**Issue by alanpaulprice** [freeCodeCamp/freeCodeCamp#24573]
**Describe your problem and how to reproduce it:**
* Visit [https://search.freecodecamp.org](https://search.freecodecamp.org)
* Search "let const"
* Note how there is a result named "Guide: Let_and_const", instead of "Guide: Let and const"
* Click on the "Guide: Let_and_const" search result
* The resulting page displays a "404 - Page not found"

If you edit the URL, replacing the `_` with `-`, it works:
**Broken** - "https://guide.freecodecamp.org/javascript/es6/let_and_const"
**Working** - "https://guide.freecodecamp.org/javascript/es6/let-and-const"

**Add a Link to the page with the problem:**
[https://search.freecodecamp.org/?q=let%20const](https://search.freecodecamp.org/?q=let%20const)
[https://guide.freecodecamp.org/javascript/es6/let_and_const](https://guide.freecodecamp.org/javascript/es6/let_and_const)

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 70.0.3538.67 (Official Build) (64-bit)
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/23743415/47259254-c03dd880-d49e-11e8-9436-735646a18f2c.png)
![image](https://user-images.githubusercontent.com/23743415/47259264-e499b500-d49e-11e8-8426-f81a560b066c.png)
![image](https://user-images.githubusercontent.com/23743415/47259269-ef544a00-d49e-11e8-8dd8-afbf8dbe0d85.png)

If it's an easy fix, I'd be happy to have a go at resolving the issue.

**Comment by tom-raley** [comment]
I'd like to work on this if no one has been assigned yet!

**Comment by prateekgoel** [comment]
@alanpaulprice Go ahead with the fix.
@tom-raley In case @alanpaulprice is not working on it, you can proceed. Meanwhile, you can contribute to other issues. Your contributions are much appreciated. :)

**Comment by alanpaulprice** [comment]
@tom-raley I'm going to try fixing it, but if I can't figure it out, I'll pass it on to you!
