### ISSUE TITLE
symmetric-difference - inconsistent instructions

### ISSUE THREAD

**Issue by piecedigital** [FreeCodeCamp/freecodecamp#246]
The bonfire challenge states here:
>Create a function that takes **two or more arrays** and returns an array of the symmetric difference of the provided arrays.

However, one of the test cases submits *only 1* array as an argument.

**Comment by terakilobyte** [comment]
Arguably, a function that expects certain conditions to be met should test
for these conditions. A consumer may not always invoke the function
correctly and providing either an error or some other graceful handling of
the situation is required.

**Comment by QuincyLarson** [comment]
I agree with @terakilobyte. This is just a sanity check test. I think we should keep it. It's been almost a month, so I'm going to close this.
