### ISSUE TITLE
"document" must be enclosed by ()

### ISSUE THREAD

**Issue by clint74** [FreeCodeCamp/FreeCodeCamp#2460]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. 
** "document" must be enclosed by ().
The list of steps says on third item:
Add $(document.ready(function() {

and the correct is $(document).ready(function() {

**Comment by jbmartinez** [comment]
Seems already fixed

**Comment by BerkeleyTrue** [comment]
@clint74 I can't find this on that page. It may have been fixed between the time you posted and now. Please reopen if you are still seeing this with some screen captures.

Happy Coding!

**Comment by benschenker** [comment]
I see it in the 3rd test it says: 
```
Add $(document.ready(function() { to the beginning of your script element.)
```
I think this should be reopened

**Comment by BerkeleyTrue** [comment]
This is what I see.
![waypoint__learn_how_script_tags_and_document_ready_work___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/9419908/cddab2de-4814-11e5-9488-31568a797a02.png)

**Comment by jbmartinez** [comment]
I also see it fine
![docu](https://cloud.githubusercontent.com/assets/4247923/9419954/40c505d2-482a-11e5-80ef-7242ce5a89a5.png)

**Comment by BerkeleyTrue** [comment]
It may be that one of the servers is holding on to an old version. @benschenker  Can you paste screen cap?

**Comment by benschenker** [comment]
<img width="1437" alt="codecamp_document_ready_screencap" src="https://cloud.githubusercontent.com/assets/2434612/9420072/5cca28d2-4827-11e5-829c-687891b85840.png">

**Comment by benschenker** [comment]
Hmm, when I open it up in incognito mode it doesn't have this issue...

**Comment by clint74** [comment]
Weird! Shows wrong in  **chrome** but its ok in **Firefox**.

**Chrome**
![2-screenshot - 21-08-2015 - 19 09 38](https://cloud.githubusercontent.com/assets/2698441/9420086/46eea450-4838-11e5-81b2-f30200e676e2.png)

**FF**
![ff-screenshot - 21-08-2015 - 19 14 07](https://cloud.githubusercontent.com/assets/2698441/9420163/d9f03516-4838-11e5-8573-f2869472f0c4.png)

**Comment by jbmartinez** [comment]
Perhaps the old version persists in the cache even when a new version is available

**Comment by BerkeleyTrue** [comment]
@jbmartinez This may be a caching issue. I've open up FF and Chome in incognito and it does not show up.

**Comment by clint74** [comment]
It seems a cache issue. #closing
