### ISSUE TITLE
http://www.freecodecamp.com/challenges/waypoint-inherit-styles-from-the-body-element

### ISSUE THREAD

**Issue by Majeye** [FreeCodeCamp/FreeCodeCamp#2464]
I completed this waypoint, but I didn't have to assign the body class to my h1 element before everything was completed.   I have included a screenshot of the syntax I used.

![Screenshot via Imgur](http://i.imgur.com/bpWHwkg.png)

**Comment by suhussai** [comment]
To select and edit classes in CSS, the following format is used:
```css
.exampleClass {
    /* css stuff */
}
```

The CSS snippet in the screen shot is targeting the main body tag in a typical html page. If you wanted to create select and style a class using CSS, you would need to use the format shown in the example above. The corresponding html would look something like this:

```html
<p class="exampleClass"> 
    This is a paragraph tag styled by the class exampleClass 
 </p>
```
