### ISSUE TITLE
Lesson completion, missing semi colon

### ISSUE THREAD

**Issue by mdhemphill** [FreeCodeCamp/FreeCodeCamp#2465]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-rgb-to-color-elements-white has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I changed the rgb values from zero's to 255, 255, 255. Once that was entered the "Goto Next Challange" button became active and I was able to move on to the next lesson. The semi colon was missing from the end of the style attribute.

**Comment by suhussai** [comment]
As it turns out, the last CSS declaration does not require a semicolon. So even without it, I think the solution is correct. Having said that, according to this stackoverflow question:

http://stackoverflow.com/questions/11939595/leaving-out-the-last-semicolon-of-a-css-block 
> It's not good practice to manually exclude semi-colons. This is purely because it's easy to overlook when adding more styles, especially if you're working in a team

**Comment by BerkeleyTrue** [comment]
@suhussai is correct. We cannot test for semicolon html interpreter auto corrects for it.

Happy Coding!
