### ISSUE TITLE
My Jittery Info Box

### ISSUE THREAD

**Issue by AshiaNTFB** [FreeCodeCamp/FreeCodeCamp#2466]
Any time I type into the editor the info box moves around as if it is refreshing with every key hit. 

![jitters](https://cloud.githubusercontent.com/assets/13361095/9421738/a5144d18-483e-11e5-8c3a-0ece744ad770.gif)

**Comment by zshnr** [comment]
Facing the same issue on Safari.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate #2137 

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help!-I've-Found-a-Bug
