### ISSUE TITLE
Account Issue

### ISSUE THREAD

**Issue by rencemontanes** [FreeCodeCamp/FreeCodeCamp#2468]
Hi,

Encountered an issue on accessing my account today..

When I login, It did not recognize where did I left of..
I cant manage my account..
My map misses some of my waypoints that I already done...

Hope we can do something about it.. :(

**Comment by benschenker** [comment]
Hey @rencemontanes are you still experiencing this?  A couple of weeks ago, a bunch of changes were pushed to the site which may affect the map and your account.  See [this](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/August-2015-Improvements) for more information
