### ISSUE TITLE
Restart CI for failed jobs

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#24688]
I am helping out with the QA process and applied a filter using status:failure and see over 1500 open PRs with red Xs indicating something failed.  The following types of errors are showing up in this list.

**Unable to find './azure-pipelines.yml'**
![image](https://user-images.githubusercontent.com/5313213/47260262-c3b86c00-d46c-11e8-991d-012c713523aa.png)

Travis CI errors involving folder names with upper case letters.
**Example:** 
> Warning: TODO - Define Testing.
> Error: 
> Upper case characters found in 3D, all folder names must be lower case
>   Found in :
>     /home/travis/build/freeCodeCamp/freeCodeCamp/guide/english/3D

I know the one Travis CI error involving the folder issue can be resolved by manually restarting the build, because @Bouncey fixed the offending folders, but the sheer volume of these would be a pain to do manually.  Is there an automated solution to rebuild these?

**Comment by RandellDawson** [comment]
Here is another error I am seeing:
![image](https://user-images.githubusercontent.com/5313213/47261579-d5a70880-d486-11e8-906b-0cf5d13eef15.png)

**Comment by QuincyLarson** [comment]
@Bouncey @raisedadead Do you have any ideas for how we could do an automatic rebuild of these failing PRs? I think it would be worth the time to figure out such a way since this has come up a lot in the past and manually triggering these builds isn't a great use of our contributors' scarce time.

**Comment by RandellDawson** [comment]
@Bouncey , @raisedadead I found travis-ci/travis.rb#344 on how to restart the build process for PRs which failed. This would make it so that no one has to manually restart the 1500+ PRs which have failed in the last 2 days due to the uppercase folder issues @Bouncey fixed earlier today. Not sure if this particular solution will work, but it gives me hope there is a way to automate these. Another option uses Python.

**Comment by RandellDawson** [comment]
I manually restarted about 50 a few hours ago and about 20-30 this morning.  I finally decided to give up in hopes of an automated solution.

**Comment by leebut** [comment]
Sorry, I contributed to one of them by not having the file named index.md, which I think I understood after reading the log a second time. I was responding to the Hactoberfest mailing. I was perhaps being to hasty.

**Comment by raisedadead** [comment]
I have left a cron job running on a VM. The output from the machine is available over stream here: <https://seashells.io/v/xQUVgC5E> This might take a long long time.

**Comment by raisedadead** [comment]
The output may not make much sense, but I did use the Python script. It should be able to restart the builds. Let's see how it goes.

**Comment by raisedadead** [comment]
That said, I am afraid of hitting some limit or the other over 2000+ restarts.

**Comment by raisedadead** [comment]
The jobs are restarting. I hope in a few hours everything will be queued.

**Comment by raisedadead** [comment]
The restart of most buils is complete. 575 of them did not go thru.

**Comment by RandellDawson** [comment]
@raisedadead What criteria was used to chose which of the 1500+ to rebuild?  I ask, because I am still seeing serveral which original failed for having uppercase names (i.e. the 3D and Tableau folders) which was fixed by @Bouncey.  It does not appear the builds for these PRs were restarted.

Here are two such examples:

https://github.com/freeCodeCamp/freeCodeCamp/pull/23772

https://github.com/freeCodeCamp/freeCodeCamp/pull/23771

Maybe another script could restart the build for these types?

**Comment by raisedadead** [comment]
Hi @RandellDawson 

**Firstly thanks a ton for spending so much time and efforts on the manual audit. 👏!** 

I'll try to clarify as much as I can for the benefit of all the @freeCodeCamp/moderators 

> ...seeing several which original failed for having uppercase names...

These indeed need restarts or fixes as you already figured out. We have a test now, that will fail these for lack of correct naming of the files. This is a VALID failure. Lets discuss on the automation in our meeting later today.

> ...cancelled because the "Auto Cancellation" feature is currently enabled,...

I have enabled auto cancellation for PRs and branches to avoid the strain on the CI.

Two scenarios will cancel the builds on PR:

- If a PR is closed without merge. 
- Fresh commits were added to the PR, 

The previous build **if pending to run** will get cancelled. If additional commits are added the last job in the queue is run, which will correspond to the latest commit on the PR. This reduces the no of jobs on the CI.

A rare side-effect of this is: If a PR is accidentally closed and re-opened, then a restart is required. A moderator can do so when they notice it.

> ...Error: One or more locations are missing, all are required...

You would notice this is most likely to happen on PRs that have a merge conflict. We have merged a fix that will for the error. These PRs may have been made before the fix: https://github.com/freeCodeCamp/freeCodeCamp/pull/24587 and hence need a rebase. Which basically means either getting the conflicts to be resolved.

The best way to address this, is to ask the OP of the PR to close and re-open, since the files are conflicted anyways.

**Comment by Nirajn2311** [comment]
@raisedadead the following error has started popping up in some of the recent Travis failures:

>	Failed Tests: There were 6 failures
    Use @each to Map Over Items in a List
      ✖ Your <code>.blue-bg</code> class should have a <code>background-color</code> of blue.
      ✖ Your <code>.black-bg</code> class should have a <code>background-color</code> of black.
      ✖ Your <code>.red-bg</code> class should have a <code>background-color</code> of red.
      ✖ Your <code>.blue-bg</code> class should have a <code>background-color</code> of blue.
      ✖ Your <code>.black-bg</code> class should have a <code>background-color</code> of black.
      ✖ Your <code>.red-bg</code> class should have a <code>background-color</code> of red.
  total:     4015
  passing:   4009
  failing:   6
  duration:  2m 29.6s

**Comment by ValeraS** [comment]
@Nirajn2311 @raisedadead recently solution for SASS challenge was added, but tests can't check a solution for SASS, only pure HTML/CSS/JS. I work on it and going to make PR soon.

**Comment by jagzmz** [comment]
As @Nirajn2311 commented I am getting same error for Travis CI

>     Use @each to Map Over Items in a List
>       ✖ Your <code>.blue-bg</code> class should have a <code>background-color</code> of blue.
>       ✖ Your <code>.black-bg</code> class should have a <code>background-color</code> of black.
>       ✖ Your <code>.red-bg</code> class should have a <code>background-color</code> of red.
>       ✖ Your <code>.blue-bg</code> class should have a <code>background-color</code> of blue.
>       ✖ Your <code>.black-bg</code> class should have a <code>background-color</code> of black.
>       ✖ Your <code>.red-bg</code> class should have a <code>background-color</code> of red.

PR #27608

**Comment by jagzmz** [comment]
> @raisedadead the following error has started popping up in some of the recent Travis failures:
> 
> > Failed Tests: There were 6 failures
> > Use @each to Map Over Items in a List
> > ✖ Your `.blue-bg` class should have a `background-color` of blue.
> > ✖ Your `.black-bg` class should have a `background-color` of black.
> > ✖ Your `.red-bg` class should have a `background-color` of red.
> > ✖ Your `.blue-bg` class should have a `background-color` of blue.
> > ✖ Your `.black-bg` class should have a `background-color` of black.
> > ✖ Your `.red-bg` class should have a `background-color` of red.
> > total:     4015
> > passing:   4009
> > failing:   6
> > duration:  2m 29.6s

Same error for CI for me

**Comment by ValeraS** [comment]
made a PR #27716

**Comment by thecodingaviator** [comment]
Guys, if the script has been run fully, #21951 hasn't rebuilt

**Comment by QuincyLarson** [comment]
@RandellDawson I noticed many of the PR's I've been removing have already been restarted to fix broken builds, which is awesome! Thanks for writing this script. 

Do we still need this issue to stay open or can we close it?

**Comment by RandellDawson** [comment]
@QuincyLarson I believe this issue has been resolved by [this PR](https://github.com/freeCodeCamp/github-tools/pull/20).  I will let @raisedadead make the final determination.
