### ISSUE TITLE
Waypoint: Use Clockwise Notation to Specify the Margin of an Element

### ISSUE THREAD

**Issue by ALINATSUI** [FreeCodeCamp/FreeCodeCamp#2469]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Not sure if this has been reported but I was not able to get past this challenge and I believe what I've inputted is correct:

![screen shot 2015-08-21 at 10 04 39 pm](https://cloud.githubusercontent.com/assets/7786266/9422044/042f0830-4851-11e5-836b-5325d8a9d621.png)

**Comment by suhussai** [comment]
You're specifying padding. The question asks to set the margin. If you replace "padding", with "margin", it will work.

**Comment by BerkeleyTrue** [comment]
@suhussai is correct. 

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-help-when-you-get-stuck

Happy Coding!

**Comment by JS-Taiyou** [comment]
Actually I'm on the same challenge and, certainly I wasn't caught by the same mistake.
I've noticed that if you do use Clockwise notation it doesn't work, but if you go for the four margin-top, ...-right, etc, then it's correct. It's the same for the previous  challenge with the padding
![captura de pantalla 3](https://cloud.githubusercontent.com/assets/16000161/11458639/cf49a1ca-9689-11e5-81ff-bd3389e1a7e7.png)
![captura de pantalla 4](https://cloud.githubusercontent.com/assets/16000161/11458638/cf490aa8-9689-11e5-9b7d-e6b0c6890898.png)

**Comment by bugron** [comment]
@JS-Taiyou try removing colons.

**Comment by JS-Taiyou** [comment]
Beg your pardon for such idiotistic post.

**Comment by bugron** [comment]
That's OK @JS-Taiyou. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

**Comment by JS-Taiyou** [comment]
Then the bug on both challenges would be accepting as correct both notations when the required one is Clockwise

**Comment by bugron** [comment]
@JS-Taiyou that's not an issue, you can do the same thing in different ways. This challenge is about how to specify margins using Clockwise notation.

**Comment by JS-Taiyou** [comment]
Of course but I'm not sure if it is right to pass the challenge without following the specified instuctions
