### ISSUE TITLE
Broken Checkmarks and extra text on JavaScript exercise

### ISSUE THREAD

**Issue by jordan-carlile** [FreeCodeCamp/FreeCodeCamp#2470]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Please refer to the screenshot for the bug. There seems to be extra text in the bar to the right. The check marks also seem not to work for this exercise. 

screenshot: https://gyazo.com/9426a0e752519b1e605c66be9fc89fcc

**Comment by BerkeleyTrue** [comment]
If you mean the bar on the left, then that is correct. Those are the test used to evaluate your code and are displayed for your information.

The test do seem to be broken for this challenge.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2362
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2282
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2236
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2231
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2217
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2179
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2141
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2077
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1999

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
