### ISSUE TITLE
Bug - code doesn't get approved

### ISSUE THREAD

**Issue by tkdblake93** [FreeCodeCamp/FreeCodeCamp#2471]
![waypoint-split-your-bootstrap-row-bug](https://cloud.githubusercontent.com/assets/7482091/9422103/ea920c1a-484b-11e5-8fd2-8b8b5186f73e.PNG)
Challenge http://www.freecodecamp.com/challenges/waypoint-split-your-bootstrap-row has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by jbmartinez** [comment]
Try something like this:
```html
<div class="row">
  <div class="col-xs-6"></div>
  <div class="col-xs-6"></div>
</div>
```

**Comment by BerkeleyTrue** [comment]
You code is incorrect as @jbmartinez points out.

Please read https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-help-when-you-get-stuck
and 
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!
