### ISSUE TITLE
Background-color required twice to pass

### ISSUE THREAD

**Issue by MsAleia** [FreeCodeCamp/FreeCodeCamp#2473]
Challenge http://freecodecamp.com/challenges/waypoint-use-rgb-values-to-color-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The waypoint will not pass unless the background-color is set twice (once with the word "black" and once with the rgb value).

<img width="1392" alt="screen shot 2015-08-21 at 11 41 47 pm" src="https://cloud.githubusercontent.com/assets/12538689/9422352/3a960a1a-485e-11e5-9a0d-674f41e0e3ce.png">

**Comment by jbmartinez** [comment]
I didn't have to set it twice
![bg-black](https://cloud.githubusercontent.com/assets/4247923/9422561/9581ee18-4862-11e5-96fd-8fd33cdc10dc.png)

**Comment by BerkeleyTrue** [comment]
Yes, the tests are misleading.  The first test should be either be removed or reworded.

**Comment by jbmartinez** [comment]
That test is necessary, I'm going to reword it. What about "your `body` should have a  black background"?

**Comment by MsAleia** [comment]
It's just that this one requires the black background being set twice when the subsequent tests for different colors require only a hex code. 

If both are necessary it should say so. 

Aleia

**Comment by jbmartinez** [comment]
Setting it once is enough, @MsAleia. Perhaps you found a bug that it's solved now. The wording may be clearer, though.

**Comment by jbmartinez** [comment]
@BerkeleyTrue All RGB and hex colors waypoints have similar tests and wording, should we change all of them?

**Comment by BerkeleyTrue** [comment]
@jbmartinez Has this been resolved?

**Comment by jbmartinez** [comment]
It is now @BerkeleyTrue. I changed the wording in all the RGB waypoints for consistency to "your `body` should have a xxx background", where xxx is the color used in the challenge (I noticed other waypoints have a similar wording to what I used).

**Comment by BerkeleyTrue** [comment]
Awesome! Thanks for the hard work @jbmartinez 

Happy Coding!
