### ISSUE TITLE
All "Help" and "Pair" links broken

### ISSUE THREAD

**Issue by CoderNurse** [FreeCodeCamp/FreeCodeCamp#2474]
All of the "Help" and "Pair" links in all Waypoints and Bonfires (as far as I've seen) are dead links. If you click either, you get a pop up window and then if you click on the "Take me to the help room" or "Take me to the pair programming room" the link is dead.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate of #2445

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
