### ISSUE TITLE
Waypoint not showing that I have completed it when I have. Please fix as it might be a bug. Thank you.

### ISSUE THREAD

**Issue by codebrew85** [FreeCodeCamp/FreeCodeCamp#2480]
Challenge http://freecodecamp.com/challenges/waypoint-target-even-numbered-elements-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by dokkillo** [comment]
@codebrew85  can you add some screenshot and a bit more information?

**Comment by codebrew85** [comment]
it fixed now. thanks for your quick response.

**Comment by dokkillo** [comment]
@codebrew85 np, close the issue :)
