### ISSUE TITLE
Waypoint: Generate Random Fractions with JavaScript...no responding.....i can't delete

### ISSUE THREAD

**Issue by bimbo1991** [FreeCodeCamp/FreeCodeCamp#2481]
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-fractions-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by ahstro** [comment]
You're going to have to explain a bit more than that. What code do you currently have that's not working? How is it not responding? What happens if you reload the page?

**Comment by benschenker** [comment]
Hey @bimbo1991, thanks for posting an issue!

Take a look at: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug for steps you should take before submitting a new issue.  After you've gone through that feel free to reopen this issue and update it with relevant information.

This issue can be closed.
