### ISSUE TITLE
page not responding

### ISSUE THREAD

**Issue by Polshe** [FreeCodeCamp/FreeCodeCamp#2485]
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. 
This page isn't responding and isn't works.
I cant make anything on it and complete task

**Comment by issyl0** [comment]
Hi @Polshe! Thanks for reporting this. :sunny: If you haven't managed to get through this yet, what happens if you refresh your browser and try again?

**Comment by benschenker** [comment]
Take a look at [How to refresh your browser](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache) for a quick rundown of how to do that.

**Comment by BerkeleyTrue** [comment]
This should be fixed now. Do a hard refresh and try again. Feel free to re-open if the issue persist.

Happy Coding!
