### ISSUE TITLE
Waypoint tasks showing 'undefined' functions

### ISSUE THREAD

**Issue by swight** [FreeCodeCamp/FreeCodeCamp#2488]
Challenge http://freecodecamp.com/challenges/waypoint-declare-string-variables has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In the Javascript waypoints so far, all the tasks are showing a box that say "undefined" and below it some code is showing where it should not be. (see screenshot)
![image](https://cloud.githubusercontent.com/assets/11048669/9424099/5ffbca72-48ba-11e5-9d4e-814c2da665e2.png)
Doing the tasks and reloading the page does allow to get through the way points.

**Comment by BerkeleyTrue** [comment]
The box with `undefined` is where the results of running your script will display. 

The code below is the test used to determine the validity of your code. They are there to help guide you to the correct answer.

Happy Coding!
