### ISSUE TITLE
Exercise not validating

### ISSUE THREAD

**Issue by blemaire** [FreeCodeCamp/FreeCodeCamp#2489]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The exercise seems broken:

Objectives:
- [ ] The second element in each of your well elements should bounce.
- [x] You should use the :nth-child() function to modify these elements.
- [x] Only use jQuery to add these classes to the element.

```HTML
<script>
  $(document).ready(function() {
    $(".well:nth-child(2)").addClass("animated bounce");
  });
</script>

<!-- You shouldn't need to modify code below this line -->
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```

I have also tried the below:
```HTML
<script>
  $(document).ready(function() {
    $("#left-well:nth-child(2)").addClass("animated bounce");
    $("#right-well:nth-child(2)").addClass("animated bounce");
  });
</script>
```

Neither validates the first objective of the exercise.

**Comment by blemaire** [comment]
Sorted thanks, there must be a space before the `:`.

**Comment by keponk** [comment]
I think this should be re-opened (or maybe someone can instruct me where to report this), since the example on the left pane doesn't use that space. It also took me a while of searching and luckily found this thread.

**Comment by ltegman** [comment]
@keponk This challenge will pass fine without the space. If you're having trouble with it you should check out the [Help Chat](https://gitter.im/FreeCodeCamp/Help). Happy coding!

**Comment by pd1309** [comment]
$("#left-well:nth-child(2)").addClass("animated  bounce"));
     $("#right-well:nth-child(2)").addClass("animated bounce"));

not working for me.

**Comment by texas2010** [comment]
@pd1309 
Please use the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding.
