### ISSUE TITLE
Errors beneath where you reset code

### ISSUE THREAD

**Issue by fullstackquest** [FreeCodeCamp/FreeCodeCamp#2491]
Challenge http://freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Can get thru Basic Javascript 1 thru 8 , but the all have these kins of errors under where you reset the code. 

![screen shot 2015-08-22 at 6 55 20 am](https://cloud.githubusercontent.com/assets/13633227/9424263/1b03315e-489b-11e5-87d7-27c2b3ff767e.png)

thanks!

**Comment by BerkeleyTrue** [comment]
What is the issue you are having?

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2470
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2362
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2282
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2236
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2231
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2217
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2179
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2141
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2077
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1999

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

**Comment by fullstackquest** [comment]
Thanks for your help.
