### ISSUE TITLE
Waypoint: Manipulate Arrays With unshift

### ISSUE THREAD

**Issue by olibotka49** [FreeCodeCamp/FreeCodeCamp#2494]
Challenge http://freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
Think its bugged. toLowerCase is a function i cant change from the code editor given. Plus i assume thats not even the intended task back there.

**Comment by olibotka49** [comment]
Or maybe im just dumb LEL

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!
