### ISSUE TITLE
Not responding step 5 for a jQuery checkpoint

### ISSUE THREAD

**Issue by cenjennifer** [FreeCodeCamp/FreeCodeCamp#2495]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

There is an issue with this step: Your #target1 element should have the classes animated‚ shake and btn-primary.

I have created that step and the step wouldn't check off and respond for me to move forward. Thanks!

![screen shot 2015-08-22 at 12 05 10 pm](https://cloud.githubusercontent.com/assets/6467349/9424757/7b189aae-48c6-11e5-91e4-aa80a2be9c11.png)

**Comment by BerkeleyTrue** [comment]
Your code is incorrect. You should pass in strings to the addClass method.

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue

Happy Coding!
