### ISSUE TITLE
How do you change your profile settings?

### ISSUE THREAD

**Issue by thejonathangraham** [FreeCodeCamp/FreeCodeCamp#2497]
Here is what the profile settings page looks like...
![das](https://cloud.githubusercontent.com/assets/11198912/9424979/51e32384-48f8-11e5-93d1-beb1260e5129.png)

**Comment by BerkeleyTrue** [comment]
At the moment you can only pull in information from github. There is an update soon to pull in information from other auths. The only effect these will have is adding social buttons to your profile.

Happy Coding!

**Comment by thejonathangraham** [comment]
@BerkeleyTrue no information apart from my avatar seems to be pulled in, is this corrrect?
![image](https://cloud.githubusercontent.com/assets/11198912/9425006/cdba8a56-48f8-11e5-9b94-d3959559d552.png)

**Comment by BerkeleyTrue** [comment]
Yes. We are working on pulling in more information from github to display. There should be a github button there in the near future as well.

**Comment by thejonathangraham** [comment]
cool, just checking ;)

On Sat, Aug 22, 2015 at 6:16 PM, Berkeley Martinez <notifications@github.com
> wrote:

> Yes. We are working on pulling in more information from github to display.
> There should be a github button there in the near future as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2497#issuecomment-133727961>
> .
>



-- 
Jonathan Graham

**Comment by branko-stankovic** [comment]
What about changing the information about my GitHub profile? I changed a name there on GitHub, how can I change the link to it in my FreeCodeCamp profile, if possible?
Thank you!
