### ISSUE TITLE
Broken test on "Waypoint: Bring your JavaScript Slot Machine to Life"

### ISSUE THREAD

**Issue by hallaathrad** [FreeCodeCamp/FreeCodeCamp#2499]
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. 
<img width="1238" alt="screen shot 2015-08-22 at 13 15 27" src="https://cloud.githubusercontent.com/assets/2107110/9425080/56d34f58-48d1-11e5-8593-bd4231ebd9a3.png">

My browser crashed because of an automatically run endless loop, which can be reproduces as follows:
As I was typing a *for* to solve the waypoint without repeating myself —See the prompt in my screen capture—; inspectlet, in its constantly running nature and without me asking it to run the obviously unfinished code, executed it before I could type the necessary *i++*, and jumped into the dreaded endless loop which crashed my browser.

**Comment by benmcmahon100** [comment]
You aren't mean to use a loop for this due to this error. There is also only three boxes

**Comment by hallaathrad** [comment]
By DRY principle, this is a better response than a line being repeated almost identically, but you're right:
I understand it is not the expected response to the exercise, yet I thought the inspectlet behaviour and it crashing the student's browser was a bug you'd want someone to report about. 

@Kallaway Just made me realise I may not have been clear enough on the bug definition:
The issue happened because inspectlet runs constantly as you type, so I didn't even get to finish typing the *for* statement (meaning, I didn't get to type *i++*), so it executed the code before it was done and thus went endlessly loopy.  Will edit the OP accordingly.

**Comment by Kallaway** [comment]
I've tested it and I ran into the same bug. Though for loop might not be a part of the solution in this case, writing it in the editor should not freeze it.

**Comment by BerkeleyTrue** [comment]
Try adding curly braces.

**Comment by hallaathrad** [comment]
I didn't get to type those either. I pasted the example and was building around it, but inspectlet was quicker than my typing LOL. I didn't run the code (as in I didn't press "Go to my next challenge" button), the thing does it by itself as you type.

**Comment by benmcmahon100** [comment]
The code auto runs when you stop typing for a few miliseconds. The issue is that these challenge types were never meant to run js. It is also perfectly acceptable to use the same thing three times when the important parts of the function always change. That said if your heart was set on using a loop you should check out the .map function.

**Comment by hallaathrad** [comment]
Will do, thanks.

**Comment by BerkeleyTrue** [comment]
@hallaathrad We pushed up a fixed. Can you give it a try now?

**Comment by hallaathrad** [comment]
Great, not only does it not get stuck that way... it also ends that annoying "clear your cache and cookies" pseudo-fix.
I like it! Thank you! Wanna close this?

**Comment by BerkeleyTrue** [comment]
Great! 

Happy Coding!
