### ISSUE TITLE
Javascript Waypoint Instructions not displaying correctly

### ISSUE THREAD

**Issue by thejonathangraham** [FreeCodeCamp/FreeCodeCamp#2502]
This doesn't look right?

![image](https://cloud.githubusercontent.com/assets/11198912/9425259/636ed0b2-4902-11e5-86e9-817b7f12baa7.png)

**Comment by jbmartinez** [comment]
It looks normal

**Comment by BerkeleyTrue** [comment]
Yes those are the test that are used to run your code.

Happy Coding!
