### ISSUE TITLE
Does not work - Waypoint: Target HTML Elements with Selectors Using jQuery 

### ISSUE THREAD

**Issue by happyholly11** [FreeCodeCamp/FreeCodeCamp#2503]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I inserted the line of code exactly as specified in the instructions to make the buttons bounce, but the page is not allowing me to get past this challenge for some reason. See screenshot. I have the same problem with subsequent jQuery challenges as well.

![screen shot 2015-08-22 at 3 15 17 pm](https://cloud.githubusercontent.com/assets/8216088/9425502/d420894e-48e0-11e5-9df5-0ce51d19cf58.png)

**Comment by wildlifehexagon** [comment]
I had the same problem. I was able to get it to work after refreshing the page and typing the button selector code back in.

**Comment by happyholly11** [comment]
I just tried that, unfortunately it didn't work for me. Thanks for the suggestion though.

**Comment by wildlifehexagon** [comment]
I think I used CTRL + F5 if that makes a difference. Others have suggested clearing the cache to fix it as well. Hope you're able to get it to work.

**Comment by happyholly11** [comment]
Clearing the cache worked. Thanks!
