### ISSUE TITLE
waypoint: iterate with javascript while loops

### ISSUE THREAD

**Issue by aintit** [FreeCodeCamp/FreeCodeCamp#2504]
Challenge http://freecodecamp.com/challenges/waypoint-iterate-with-javascript-while-loops has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The waypoint says, "Let's try getting a for loop to work by pushing values to an array." when it clearly means "while loop". Minor bug.
![screenshot from 2015-08-22 15 21 13](https://cloud.githubusercontent.com/assets/13371389/9425533/93c9e380-48e1-11e5-9f51-1f354d90383b.png)

**Comment by issyl0** [comment]
Thanks a lot for reporting this! I submitted a pull request to fix it. :+1:
