### ISSUE TITLE
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes promotes bad practice?

### ISSUE THREAD

**Issue by razvan-tache** [FreeCodeCamp/FreeCodeCamp#2506]
Hi,

In the Way point: Create a Set of Check-boxes challenge, we are requested to build 3 check-boxes with the name of "personality". This is a bad practice as the request created by the browser will not differentiate the check-boxes selected by the user. The server will only receive only one personality param saying true, even if all the 3 check-boxes were selected.

Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey @razvan-tache thanks for posting this issue!

I vaguely remember what you are saying to be true but I am having trouble finding the relevant documentation or a link that explains it clearly.  Can you find a relevant link and post it here?

**Comment by razvan-tache** [comment]
I build a gist with an example and explanations in comments. I quick searched the w3 specifications really quickly, but beside the default definitions for check-boxes and radio buttons which were relevant.
I couldn't find the specifications for the request data.

https://gist.github.com/razvan-tache/2f99ac2600c5d2a6ed2a

**Comment by ltegman** [comment]
This is actually a common and correct way to use checkboxes (particularly within the JS world). The identical names indicate that all the checkboxes are referring to the same type of value and the value attribute is used to differentiate between the values of each checkbox. How this is handled is up to the tool processing the form, but there is nothing about the same name pattern that breaks spec. From what I can see the `[]` syntax is not widely supported outside of PHP and Apache, and given that FCC deals with the MEAN stack I don't think this should have any bearing on the curriculum.

**Comment by BerkeleyTrue** [comment]
@ltegman Is correct. The name property defines a group of radio buttons. All radio buttons within a form with the same name property are part of the same group and define which property to set the value of. The value of the property is defined by the value attribute on the individual radio buttons within a group.

Happy Coding!
