### ISSUE TITLE
Solution was filled in already, only had to close the script tag.

### ISSUE THREAD

**Issue by Offloads** [FreeCodeCamp/FreeCodeCamp#2507]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![screen shot 2015-08-22 at 21 34 21](https://cloud.githubusercontent.com/assets/11233306/9425585/9ef9388a-4915-11e5-849d-e591b2241650.png)

**Comment by issyl0** [comment]
Thanks for the report. Interesting! I can't reproduce this as partially filled in by default.

Have you tried refreshing the page? Maybe it has cached a previous attempt?

**Comment by Offloads** [comment]
When I went to the next challenge, it wasn't working right so I refreshed then and it worked so could have been an issue on my end.

**Comment by Offloads** [comment]
Think I found it, I checked my map and for some reason one Challenge 2 wasn't completed. Which means when I went to next challenge (either load error or I pressed twice somehow(?) and it went to the following challenge which had already filled in the script.
