### ISSUE TITLE
jQuery assignments

### ISSUE THREAD

**Issue by NathanSQWing** [FreeCodeCamp/FreeCodeCamp#2509]
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-css-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![jquery-bug](https://cloud.githubusercontent.com/assets/13779993/9425603/c13d8a7c-48e3-11e5-9bd4-0338d00ac9f1.png)

Anytime my cursor moves out of the function the app replicates itself three more times. It doesn't prevent the user from completing the assignment, but there have been a few other bugs in the previous assignments. While the assignments are saying to place the new line of code into the document ready function, they have only worked when placing them outside the function. However, when moving on to the next assignment the code from the last assignment is placed inside the document ready function as requested.

I hope that helps. Please feel free to message me with questions or concerns.

sincerely, 
Nathan

**Comment by benschenker** [comment]
Hey @NathanSQWing thanks for posting this issue!

I was unable to replicate your exact issue, though I see that you didn't `Delete your jQuery selectors, leaving an empty document ready function.` as it says in the description, try that and then try placing your solution inside the `document ready function` like:
```
$(document).ready(function(){
///CODE HERE
});
```

**Comment by benschenker** [comment]
Closing as stale.  Please reopen if you still have these issues
