### ISSUE TITLE
Waypoint: Target Elements by Class Using jQuery has a bug

### ISSUE THREAD

**Issue by MysticRiver** [FreeCodeCamp/FreeCodeCamp#2510]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-elements-by-class-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When I enter the correct code to solve this challenge it doesn't recognize my code as valid and promote me to the next challenge.

Here's a screenshot:
![bugs](https://cloud.githubusercontent.com/assets/2208459/9425655/4c736ee2-48dd-11e5-9a1b-4bc9674fefd4.PNG)

**Comment by benschenker** [comment]
Hey @MysticRiver, thanks for posting this issue!

I'm having trouble replicating this locally.  Have you gone through our [Bug Reporting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) yet?  That may help you resolve this issue quickly.

This issue should be closed for now, but feel free to open it after completing the above steps if you belive there is still a problem with FreeCodeCamp.

**Comment by BerkeleyTrue** [comment]
@MysticRiver I'm also unable to reproduce. Can you try reseting your code and trying again?

**Comment by denmch** [comment]
I tested this myself and was surprised that I had the same experience, even after resetting the code. However, after a hard refresh in Chrome (Cmd+Shift+R on Mac, or Ctrl+Shift+R on a Windows machine), all tests showed as passed.

**Comment by KristenWilde** [comment]
Hi, I'm having this very same problem. Refreshing the page isn't helping.

**Comment by ltegman** [comment]
@KristenWilde, would you mind posting the code you have that is not passing?

**Comment by KristenWilde** [comment]
After taking a break and coming back to it, I realize I didn't put the addClass function inside the document ready function. Oops.  Thank you @ltegman.

**Comment by ltegman** [comment]
@KristenWilde Glad to hear you got it figured out. Happy coding!
