### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sungjp** [FreeCodeCamp/FreeCodeCamp#2513]
<img width="1641" alt="error" src="https://cloud.githubusercontent.com/assets/8159855/9425707/79722f8e-48e0-11e5-848f-093f82d2606d.png">

Challenge http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by ahstro** [comment]
Try a [hard refresh](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache). :)
