### ISSUE TITLE
jQuery assignments part deux

### ISSUE THREAD

**Issue by NathanSQWing** [FreeCodeCamp/FreeCodeCamp#2514]
Challenge http://www.freecodecamp.com/challenges/waypoint-clone-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![jquery-bug001](https://cloud.githubusercontent.com/assets/13779993/9425699/7615b240-48e8-11e5-997f-59e55a174915.png)

In this assignment the line of code still has to be placed outside of the function to work, but this time the function of clone and append has caused a duplication process that I cannot truly place into words. It simply has duplicated the element 10 times in the right well and an extra time in the left well.

**Comment by benschenker** [comment]
Hey @NathanSQWing  thanks for posting an issue!

In the future, please follow our bug reporting guidelines as that will help you resolve these problems quickly: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug

I don't completely understand the problem you are having, and am having difficulty replicating the issue.  After going through the steps above if you still have a bug to report in the site, reopen this issue.

This issue can be closed.

**Comment by BerkeleyTrue** [comment]
I'm also not able to replicate. Looking at your code there doesn't seem to be anything to explain the multiplication.

@NathanSQWing Can you replicate it again or was this a one time thing?

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
