### ISSUE TITLE
Frozen tab in Chrome

### ISSUE THREAD

**Issue by matthew02** [FreeCodeCamp/FreeCodeCamp#2516]
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue.

I typed `$(` which autocompleted the matching`)` leaving the caret between the parens. When I typed the next `$` making the statement `$($)`, the chrome tab froze hard and my CPU usage redlined. I eventually had to manually edit the browser's local storage using a Chrome extension and change the code there to be able to get back to the challenge without freezing my browser tab.

**Comment by michael-krebs** [comment]
Hi @matthew02,
This issue has been found and is being worked on. #2286

**Comment by bugron** [comment]
Dear camper, your issue is related to:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2244
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2054

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
