### ISSUE TITLE
Terminal is not picking up that code is correct (or my code is incorrect!)

### ISSUE THREAD

**Issue by reimarus** [FreeCodeCamp/FreeCodeCamp#2517]
Challenge http://www.freecodecamp.com/challenges/waypoint-make-images-mobile-responsive has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Not sure how to reproduce it exactly, but the terminal does not seem to be reading my code correctly.

http://screencast.com/t/onc9C4vKu1Ie

**Comment by ahstro** [comment]
I can't reproduce this, the code passes fine for me. Have you tried a [hard refresh](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache)? Oh, and in the future, if you're not sure your code is correct, please get help in the chat room first. :)

**Comment by reimarus** [comment]
I didn't try a hard refresh and I was pretty darn sure that the code was right.  I'll keep both the hard refresh as well as the chatroom in mind for the future.

Thank you

**Comment by ahstro** [comment]
If it's not an issue, remember to close :)
