### ISSUE TITLE
Challenge fail using jQuery selector with single quotes

### ISSUE THREAD

**Issue by matthew02** [FreeCodeCamp/FreeCodeCamp#2522]
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue.

The second condition for this challenge:
>You should have used the the selector given in the description to select each slot and assign it the value of slotOne, slotTwo and slotThree respectively

The selector in the description: 
>`$($(".slot")[0]).html(slotOne);`

The condition passes when you use double quotes in the selector per the description:
<pre><code>$($(".slot")[0]).html(slotOne);
$($(".slot")[1]).html(slotTwo);
$($(".slot")[2]).html(slotThree);</code></pre>

It fails with single quotes:
<pre><code>$($('.slot')[0]).html(slotOne);
$($('.slot')[1]).html(slotTwo);
$($('.slot')[2]).html(slotThree);</code></pre>

Maybe we are trying to conform to the [jQuery JavaScript Style Guide](https://contribute.jquery.org/style-guide/js/#quotes)? Still, both seem to be valid JavaScript. Indeed, the challenge immediately following this one uses single quotes for the selector in the description and passes with either single or double quotes.
>Waypoint: Give your JavaScript Slot Machine some stylish images
>
>`$($('.slot')[0]).html('<img src = "' + images[slotOne-1] + '">');`

![39-fail](https://cloud.githubusercontent.com/assets/416065/9425864/a9082620-48e7-11e5-889b-d501aabc1d4f.png)
![39-pass](https://cloud.githubusercontent.com/assets/416065/9425863/a907b776-48e7-11e5-86d7-a1e81552de41.png)

**Comment by benschenker** [comment]
Hey @matthew02 thanks for posting this!

There are a few duplicate issues here but yours looks like it is the most detailed so I'll leave it as the main one.

The fix will have to be similar to the fix that closed #2364.

**Comment by bugron** [comment]
Closing this issue as https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3125 is merged.
