### ISSUE TITLE
waypoint: Target the Parent of an Element Using jQuery

### ISSUE THREAD

**Issue by NathanSQWing** [FreeCodeCamp/FreeCodeCamp#2523]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In this assignment there are the same outside/inside the document ready function as in all previous assignments (please see "#2509 jQuery assignments" and "#2514 jQuery assignments part deux")

However, the assignment never asks the user to assign a text color to #target6 yet it is listed as a prerequisite to completing the assignment. However, the user does not need to complete this request without moving to the next assignment.

![jquery-bug003](https://cloud.githubusercontent.com/assets/13779993/9425875/938c6780-48f0-11e5-8ca5-eadb6d9d729d.png)

![jquery-bug004](https://cloud.githubusercontent.com/assets/13779993/9425890/ee1effd2-48f0-11e5-8b0b-90c43a33157a.png)

**Comment by benschenker** [comment]
Hey @NathanSQWing thanks for posting this.

The instructions say to target the children of `#right-well` not `#left-well`.  It tests that by checking `#target6`, a child of `#right-well`.

The wording is a bit confusing, see #2241 and possibly #2234, for issues suggesting fixes to the description/tests.
