### ISSUE TITLE
Sample given in the question appears incorrect

### ISSUE THREAD

**Issue by mullachv** [FreeCodeCamp/FreeCodeCamp#2524]
Challenge http://freecodecamp.com/challenges/bonfire-no-repeats-please has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The problem states: 
"For example, 'aab' should return 2 because it has 6 total permutations, but only 2 of them don't have the same letter (in this case 'a') repeating."

'aab' has 3 only permutations, not 6 as stated in the question. And the number of permutations that do not repeat any alphabet is 1.

**Comment by benschenker** [comment]
Hey @mullachv thanks for posting!

This bonfire is quite confusing and you are not the first to point it out (see: #1418).

Anyone have any ideas?

**Comment by stt106** [comment]
how can this question be left as it is for so long? More and more people are to be confused with this...
