### ISSUE TITLE
Help Link not working

### ISSUE THREAD

**Issue by bwalt42** [FreeCodeCamp/FreeCodeCamp#2525]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Clicked on the "help" button. When I click on the "take me to the help room" button in the pop up window, it doesn't go anywhere.

**Comment by BerkeleyTrue** [comment]
They should be working now.

Happy Coding!
