### ISSUE TITLE
Waypoint: Target Elements by ID Using jQuery - Not passing

### ISSUE THREAD

**Issue by WillisCoding** [FreeCodeCamp/FreeCodeCamp#2526]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery has an issue.

Completed the waypoint as instructed, yet it doesn't pass the code I've written. 
![codecamp-waypoint-target-elements-by-id-using-jquery](https://cloud.githubusercontent.com/assets/13296062/9425926/d9fa3f0c-48d8-11e5-82d5-e11942f31ed6.png)

No script-blocking extensions or other extensions on my browser(Chrome) that I can imagine are interfering. 

Thanks.
(Hopefully didn't just type incorrectly)

**Comment by WillisCoding** [comment]
Had issues with a few other Waypoints soon after that one as well. Though seems to work fine on Firefox, maybe some compatibility issues with Chrome are occurring?

**Comment by rsavage-urquad** [comment]
Had same issue on Mac/Chrome.  Worked fine on PC/Chrome.  I tried again a few hours later on Mac/Chrome and it worked.  Not sure if the Browser restart cleared it up or maybe there is a bad instance of the site running and we were unfortunate enough to be using the instance.

**Comment by benschenker** [comment]
@WillisCoding, take a look at #2587 as @rsavage-urquad mentioned above.

**Comment by benschenker** [comment]
Closing as stale, please reopen if this is still an issue for you.

**Comment by VanTudor** [comment]
I have exactly the same issue. Firefox 42.0
