### ISSUE TITLE
Waypoint: Target Even Numbered Elements Using jQuery

### ISSUE THREAD

**Issue by NathanSQWing** [FreeCodeCamp/FreeCodeCamp#2528]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-even-numbered-elements-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Small typo, the instructions display the use of apostrophes instead of quotations.

![jquery-bug005](https://cloud.githubusercontent.com/assets/13779993/9425953/72cf78a4-48f3-11e5-98bc-87025cc6493e.png)

**Comment by issyl0** [comment]
Thanks for the report! Indeed, we should probably be consistent! I've submitted a fix.
