### ISSUE TITLE
These challenges aren't working.

### ISSUE THREAD

**Issue by 1Deanna** [FreeCodeCamp/FreeCodeCamp#2531]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-elements-by-class-using-jquery has an issue. 
Challenge http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. 
Challenge http://www.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery has an issue. 
These challenges aren't updating my progress.  The buttons don't seem to work.  "Reset" brings up the option to "clear my code," but doesn't clear anything.  The "Help" button brings up the option to "Take me to the help room," but doesn't. The biggest issue, though, is that the "Go to my next challenge" button never opens up to move forward.  I don't think it's a problem with my code, because they are the same as the codes from the subsequent challenges.

![jquery bugs](https://cloud.githubusercontent.com/assets/13208194/9426028/4b16d3b8-48dd-11e5-83aa-0a5f53e6255c.PNG)

**Comment by jbmartinez** [comment]
They're working here. Please, try again after clearing your browser's cache

**Comment by 1Deanna** [comment]
Clearing the cache seems to have worked.  Thank you, Juan.  Deanna Sy      


     On Saturday, August 22, 2015 3:42 PM, Juan Martínez <notifications@github.com> wrote:
   

 They're working here. Please, try again after clearing your browser's cache—
