### ISSUE TITLE
Example image is a broken link. Waypoint: Use the Bootstrap Grid to Put Elements Side By Side

### ISSUE THREAD

**Issue by Cadence22** [FreeCodeCamp/FreeCodeCamp#2532]
![screen shot 2015-08-22 at 5 31 04 pm](https://cloud.githubusercontent.com/assets/13908810/9426155/a5c6da72-48f3-11e5-92c2-8760d406c26e.png)

Challenge http://freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by QuincyLarson** [comment]
Thanks for catching this. I've fixed this and will deploy it to production soon.
