### ISSUE TITLE
Bonfire Drop it has a bug

### ISSUE THREAD

**Issue by nscott** [FreeCodeCamp/FreeCodeCamp#2533]
Challenge http://freecodecamp.com/challenges/bonfire-drop-it has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

-------
It describes only eating the head of the array and then stopping, returning the rest of the array. This is not what is tested. 

All of the tests can be passed using `return arr.filter(func);` which will filter ALL items from the array, not just from the head.

There needs to be an additional test case, like `expect(drop([1, 2, 3, 7, 4], function(n) {return n > 5; })).to.eqls([7, 4]);`

**Comment by benschenker** [comment]
Thanks @nscott great catch!

**Comment by benschenker** [comment]
Fixed in 20c45e7

**Comment by ltegman** [comment]
Reopening this bug since the tests have been reverted to tests that could be solved by filter.

**Comment by ArgonCode** [comment]
Now the problem description and the tests do not match. This would not pass `drop([1, 2, 3, 5, 2], function(n) {return n < 3; });` when done with filter function. Filter function should not be an accepted solution for the current problem statement.

**Comment by SaintPeter** [comment]
I'll fix this one.

**Comment by koouty** [comment]
But if I understand filter is no good because the last 2 will be skipped in drop([1, 2, 3, 9, 2], function(n) {return n > 2;}) should return [3, 9, 2].
The good method is not with filter we need a while loop as this 
```
function drop(arr, func) {
  while(arr.length > 0)
    {
      if(!func(arr[0])) {arr.shift();}
      else {break;}
    }
  // Drop them elements.
  return arr;
}

drop([1, 2, 3], function(n) {return n < 3; });
```
no?

**Comment by Phajava** [comment]
drop([1, 2, 3, 9, 2], function(n) {return n > 2;}) should return [3, 9, 2]

This last challenge point must only changed in n >= 2 and than it is fixed.
