### ISSUE TITLE
All Contributors

### ISSUE THREAD

**Issue by MatheusRV** [freeCodeCamp/freeCodeCamp#25335]
I believe that a good way to value project developers is to use https://github.com/kentcdodds/all-contributors that allows all employees to be rewarded for any task they may perform. What do you think? Can we implement this here?

**Comment by SaurishS** [comment]
I believe that this could work.

**Comment by ArielLeslie** [comment]
https://www.freecodecamp.org/forum/t/announcing-our-freecodecamp-2018-top-contributor-award-winners/201353

FCC has literally thousands of people who contribute to our community by leading discussions, helping each other, sharing resources, reporting bugs, and so on. A running list of them would be totally unmanageable. However, FCC has begun naming "Top Contributors" annually and they do not consider code contributions alone. Community moderators, video creators, and article writers and editors were included in the 2018 Top Contributors list.

**Comment by raisedadead** [comment]
Hi @MatheusRV 

Thanks for the feedback.

@ArielLeslie is right. There are tens of thousands of contributors, who help us with our publications, forum, youtube channels, study groups and chat rooms.

As much as we would love to reward every contribution, the scale of the contribution has lead us to take certain rationale.

We have already broken the pull request tab of this repository that simply says `5000+`. Adding a PR for each contributor increases the complexity to a scale that is beyond what we can comprehend here.

We could never, confirm each addition for their involvement without a misjudgement, hence making the effort somewhat futile.

The best way we have found to reward is by recognising hundreds of top contributors across the entire community and not just code, who have spent time and efforts continuously for a certain period of time.

We have started a series of top contributors parties, as a gesture for their sincere efforts in making the community what it is.

You can read more about it in the announcement linked in the previous post.

This recognition of top contributors is yearly. We award them with a badge like so:
![image](https://user-images.githubusercontent.com/1884376/47347308-9669f900-d6cc-11e8-823d-1514334e54fc.png)


Thanks a lot for your feedback.

**Comment by MatheusRV** [comment]
@raisedadead there is a CLI for that (https://github.com/jfmengels/all-contributors-cli)

**Comment by raisedadead** [comment]
Any tooling will not serve the purpose of adding all the contributors across all our communities, a large no of whom are not even working on GitHub in any way. Offline Study groups, Youtube, Reddit etc.

Again, the spec will just add them on GitHub, which is just one small part of the entire community.
