### ISSUE TITLE
HTML Waypoint 43 does not lead to 44

### ISSUE THREAD

**Issue by dgoran** [FreeCodeCamp/FreeCodeCamp#2534]
Challenge http://freecodecamp.com/challenges/waypoint-add-different-padding-to-each-side-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
CTRL+ENTER takes me to JS Bonfire (http://freecodecamp.com/challenges/bonfire-factorialize-a-number) and NOT next HTML waypoint

**Comment by QuincyLarson** [comment]
This is related to #1778. Thank you for submitting this issue. We will fix this soon.
