### ISSUE TITLE
Waypoint: Target HTML Elements with Selectors Using jQuery - Something is wrong - Please check !!!!

### ISSUE THREAD

**Issue by syosoh06** [FreeCodeCamp/FreeCodeCamp#2535]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![image](https://cloud.githubusercontent.com/assets/11453269/9426250/76f764dc-4902-11e5-89b0-6868621091c2.png)

**Comment by syosoh06** [comment]
My solution is above - yet the editor doesnt accept it - 
I dont know why?

**Comment by benschenker** [comment]
Hey @syosoh06 thanks for posting an issue!

Please take some time to read our [Bug Posting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) as they should help you resolve any issues.  

I was unable to replicate this so I think this issue should be closed, but if you follow the above steps and still have issues, please update this thread!

**Comment by 4mifix** [comment]
@syosoh06  I got this to work after cutting and pasting the exact code from the example.

**Comment by syosoh06** [comment]
Yes I had to do a hard refresh ( command + r ) and got it to work - thank you so much !!!!
