### ISSUE TITLE
Bootstrap Waypoint Images 

### ISSUE THREAD

**Issue by r00tl0gin** [FreeCodeCamp/FreeCodeCamp#2536]
Challenge http://freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I am not able to view any images which are added with the instructions for illustration of the concept.
On clicking the image it goes to a evernote page which also shows an error.

Not sure though if it is happening only for me.

Please verify it.

Thanks,
Nimit

**Comment by michael-krebs** [comment]
Evernote appears to be down right now. It's weird that Evernote is being used as an image host at all, though...

**Comment by r00tl0gin** [comment]
Yea I cannot see any images on there now. I thought earlier it was happening for only a single lesson but its on all of them.
