### ISSUE TITLE
It cant read my <img>

### ISSUE THREAD

**Issue by dzunik91** [FreeCodeCamp/FreeCodeCamp#2537]
I think that there is a problem with this task because the syntax of <img> tag seems to be good but it won't let me move forward.  
![error](https://cloud.githubusercontent.com/assets/6382429/9426318/03f7f83e-4939-11e5-86b5-c50153461e67.PNG)

**Comment by QuincyLarson** [comment]
Thanks for reporting this. Which browser and version are you using on which operating system?

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.

**Comment by dzunik91** [comment]
Thank you for your help. Just for the record i'm using windows 8.1 and newest firefox

**Comment by benmcmahon100** [comment]
The issue is with the s if memory serves me right and i think it has since been removed
