### ISSUE TITLE
Waypoint: Remove an Element Using jQuery missing id in explanation

### ISSUE THREAD

**Issue by srodman7689** [FreeCodeCamp/FreeCodeCamp#2538]
Challenge http://freecodecamp.com/challenges/waypoint-remove-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

On this challenge, it doesn't tell you what to use the remove class on. The only way to tell is to look at the text of the tests. If this is the intention please let me know and just close this issues. Just wanted to let you guys know.

**Comment by BerkeleyTrue** [comment]
Yes, the description works in conjunction with the tests.

Happy Coding!
