### ISSUE TITLE
Bug "js code is shown"

### ISSUE THREAD

**Issue by Ruzon** [FreeCodeCamp/FreeCodeCamp#2539]
Challenge http://www.freecodecamp.com/challenges/waypoint-check-the-length-property-of-a-string-variable has an issue. 

The js code is shown.
![bug js code is shown](https://cloud.githubusercontent.com/assets/4185590/9426343/57f0473e-4943-11e5-9a74-ff46b93608d2.JPG)

**Comment by BerkeleyTrue** [comment]
This is on purpose. 

>That should be showing up there. It's part of all the javascript based challenges that you are able to see the tests that are running against your code. See #2231 for a similar issue/explanation.

Also see: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github


Happy Coding!

**Comment by Ruzon** [comment]
Thank you for link!

**Comment by Ruzon** [comment]
Thank you for the link!
