### ISSUE TITLE
Advanced too far ahead

### ISSUE THREAD

**Issue by GitSummm** [FreeCodeCamp/FreeCodeCamp#2540]
Challenge http://freecodecamp.com/challenges/waypoint-size-your-images has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Not too much of an iussue but I completed challenge 16 and then was taken to an intermediate project of reverse engineering tic tac toe, like geez calm down I barely learned how to add a kitten to my app!

**Comment by QuincyLarson** [comment]
Thanks for reporting this. This is a known issue and we're hard at work fixing it.
