### ISSUE TITLE
Waypoint: Label Bootstrap Buttons

### ISSUE THREAD

**Issue by 8lcarte** [FreeCodeCamp/FreeCodeCamp#2541]
See code below, believe it is all true, not passing the tests for "Waypoint: Label Bootstrap Buttons"

```
<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target1">#target4</button>
        <button class="btn btn-default target" id="target2">#target5</button>
        <button class="btn btn-default target" id="target3">#target6</button>
      </div>
    </div>
  </div>
</div>
```

**Comment by benschenker** [comment]
Hey @8lcarte thanks for posting this.

Please take a look at our [Bug Report Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug), that will explain the process you should go through before posting an issue here.  You will get much faster help with code issues in [Gitter](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter).

I think this can be closed for now, but feel free to add to this thread after following the steps above.

**Comment by bugron** [comment]
Dear camper, your issue is related to:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2417
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2399
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2398
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2393

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Comment by munga4** [comment]
The bug is fixed.
