### ISSUE TITLE
Minor code parsing bug

### ISSUE THREAD

**Issue by joef-3** [FreeCodeCamp/FreeCodeCamp#2542]
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The challenge showed as completed as soon as I typed:

$("button").removeClass

It did not wait for an argument to be given to the removeClass function.  Kept typing past it before I thought to submit a bug so no screenshot, but should be easy enough to reproduce.

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2402
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2302
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2301
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2197
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2160
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1923
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1898
Fixed.
