### ISSUE TITLE
Showing lots of output when pressing any button

### ISSUE THREAD

**Issue by hardannyhw** [FreeCodeCamp/FreeCodeCamp#2549]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When you press any button the iPhone simulator keeps showing lots of repeated output. 
![screen shot 2015-08-23 at 10 25 23 am](https://cloud.githubusercontent.com/assets/3524560/9426633/82d1cb88-4981-11e5-9bae-cd62bc8c25cf.png)

**Comment by benschenker** [comment]
Hey @hardannyhw thanks for posting an issue!

I'm having trouble replicating this, can you take a look at our [Bug Reporting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) and see if those steps can help resolve your issue.

I think this can be closed, but if you still have problems after going through those steps then just comment on this thread and we can reopen it.

**Comment by hardannyhw** [comment]
Yes, it solved my problem. Thanks anyway. 

Cheers
