### ISSUE TITLE
Typo: "for" instead of "while" loop

### ISSUE THREAD

**Issue by dehydratedsquash** [FreeCodeCamp/FreeCodeCamp#2550]
Challenge http://www.freecodecamp.com/challenges/waypoint-iterate-with-javascript-while-loops has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Text:  "Let's try getting a for loop to work by pushing values to an array."

Should probably say "...while loop to work..."

**Comment by bugron** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2249
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2112
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2107
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2087
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2040
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1987
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1958
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1945
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1932
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1802
