### ISSUE TITLE
Wrong information in step 9

### ISSUE THREAD

**Issue by srodman7689** [FreeCodeCamp/FreeCodeCamp#2552]
Challenge http://freecodecamp.com/challenges/waypoint-save-your-code-revisions-forever-with-git has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

step 9 says Install how-to-npm with this command: npm install -g git-it. it looks like we are installing something called git-it instead of how-to-npm. As before, if I am incorrect please disregard this issue and just close. Just trying to do what I can for you guys. Love this site!

**Comment by benschenker** [comment]
Hey @srodman7689 thanks for posting an issue!

It looks like you are right!  I believe the step should say
```
Install `git-it` with this command: `npm install -g git-it`
```

**Comment by srodman7689** [comment]
That's what it looked like to me to. It seems that the command was copied from the next page when you do actually have to install how-to-npm. Btw, now that I have done a lot of the free code camp challenges, how would I go about starting to contribute to the project? I would love to help out with the code or issues or anything really.

**Comment by benschenker** [comment]
Awesome! Just jump right in :smile:!

Maybe start with putting in a pull request for this issue?  Feel free to ping me in gitter if you want to chat about this further (so as to not pollute this issue with conversation)

**Comment by bugron** [comment]
Dear camper, your issue is related to:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1317

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Comment by srodman7689** [comment]
bugron I checked when I was creating the pull request to fix this issue nad it seems that the how-to-npm part of it is already fixed.
