### ISSUE TITLE
 guidelines for contributing  link seems to go to incorrect page

### ISSUE THREAD

**Issue by AEA2002** [FreeCodeCamp/FreeCodeCamp#2553]
Was entering a bug? and clicked on "guidelines for contributing," link sent me to:
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md
On that page clicked on: "Help! I've Found a Bug" link that sent me to a page with text about paragraphs, buy nothing about bugs
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help!-I've-Found-a-Bug

**Comment by benschenker** [comment]
Thank you for reporting this issue! 
It looks like the name of the wiki page was changed which broke the link.

The real page is here: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug
