### ISSUE TITLE
It does not go to the next waypoint

### ISSUE THREAD

**Issue by ram535** [FreeCodeCamp/FreeCodeCamp#2555]
Challenge http://www.freecodecamp.com/challenges/waypoint-divide-one-number-by-another-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

It does not go to the next waypoint after run the code succefully.

**Comment by benschenker** [comment]
Hey thanks for posting @ram535!

We had a bunch of issues related to this in the last few weeks, but most have been fixed (and there is a workaround to click on the `run tests` button twice).  I am going to close this as a duplicate but feel free to reopen if you are still having issues.
