### ISSUE TITLE
Waypoint: Change the CSS of an Element Using jQuery freezing every time I try to load the page. 

### ISSUE THREAD

**Issue by doudeman** [FreeCodeCamp/FreeCodeCamp#2556]
I'm using Chrome browser and every time I try to load this challenge the page crashes. I have done all of the way points before this one and a few after with out any problem.

**Comment by benschenker** [comment]
Hey @doudeman thanks for posting an issue!

Take a look at our [Bug Posting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) as I think following those steps may resolve your issue expediently.

If those don't work, feel free to reopen this issue.

**Comment by doudeman** [comment]
I have reproduced this error on another challenge. What happens is that I type $($) and before I can finish the jQuery selector it freezes. Every time I reload the page it is frozen because it is loading the $($) before I can delete or keep typing. This is the same thing that made the original problem occur. For some reason the orignal problem went away after an hour or so.

**Comment by benschenker** [comment]
Thanks for clarifying!

That is a known issue. See: #2609 and #1960 for workarounds.
