### ISSUE TITLE
Add link to more information about roman numerals

### ISSUE THREAD

**Issue by 0x0936** [FreeCodeCamp/FreeCodeCamp#2557]
Challenge http://www.freecodecamp.com/challenges/bonfire-roman-numeral-converter has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I've noticed some other bonfires provide a wikipedia (or external) link with useful information on solving the challenge (i.e. Bonfire - Map the Debris). I feel this bonfire could benefit by adding the wikipedia link to roman numerals: https://en.wikipedia.org/wiki/Roman_numerals

**Comment by issyl0** [comment]
Thanks for this! Should we instead link to https://simple.wikipedia.org/wiki/Roman_numeral, which more concisely explains the numbering system straight away? Or even a specific section of the main Wikipedia article: https://en.wikipedia.org/wiki/Roman_numerals#Roman_numeric_system, for example?

All that said, I just noticed that the explanatory text on that Bonfire does link to http://www.mathsisfun.com/roman-numerals.html—is that not very good?

**Comment by 0x0936** [comment]
I missed that link. On my screen, with the font-size being relatively small (14px) the green link text blends a bit with the surrounding black text.

Since it's not with the 'helpful links' section at the bottom, it was easy to miss.
