### ISSUE TITLE
Duplicate challenge solutions on profile page due to auto-running old code

### ISSUE THREAD

**Issue by jedpimentel** [FreeCodeCamp/FreeCodeCamp#2559]
When opening a completed Bonfire, the IDE automatically loads and runs the last submitted solution, causing a duplicate entry in the profile page.When checking a completed Bonfire (ex: to read the problem statement), it will automatically show the success message and make a duplicate profile entry for the old code.

I assume this could be avoided by not automatically running IDE code when the page loads.

Thanks for reading,

**Comment by benschenker** [comment]
Hey @jedpimentel thanks for posting this issue!

Confirmed on my profile.  This is very similar to #1179, but that is a fairly old issue and I'm not sure if things have changed since.  @BerkeleyTrue, any thoughts?

**Comment by BerkeleyTrue** [comment]
cc @benmcmahon100 Not sure what we can do here. I know we definitely cannot remove auto execute. How about sending in a bool to `bonfireExecute(true)` that keeps the bonfire from being sent to the server?

**Comment by BerkeleyTrue** [comment]
Closing as duplicate.

Lets keep the conversation going on #1179

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

**Comment by BerkeleyTrue** [comment]
opps I take it back. This is different.
