### ISSUE TITLE
jQuery Waypoint 1 - Bug

### ISSUE THREAD

**Issue by xchelm** [FreeCodeCamp/FreeCodeCamp#2560]
Challenge http://freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Hi, I am entering the correct code to pass the first jquery waypoint, but the program does not register. In order to recreate the problem, you fill in the information the program requests.

![screen shot 2015-08-22 at 9 48 50 pm](https://cloud.githubusercontent.com/assets/12617550/9427006/0e455dba-4919-11e5-9755-9fa3b0d42f0e.png)

Thank You!

**Comment by benschenker** [comment]
Hey @xchelm thanks for taking the time to file an issue!

It looks like the second class that you are adding has a typo, take a look at that and it should fix this.

**Comment by benschenker** [comment]
Fof the future, you can get help with these kinds of issues much faster in our [Gitter Chat Room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter).

**Comment by xchelm** [comment]
Sorry about the confusion - that photo was from adding anything to make it move. Here is the a non passing photo with the right code
![screen shot 2015-08-23 at 12 32 56 am](https://cloud.githubusercontent.com/assets/12617550/9427358/b3fb228e-492e-11e5-895e-05569cc205cf.png)

**Comment by dokkillo** [comment]
Is button not buttton  😀

**Comment by xchelm** [comment]
I hate myself right now... I got it.

**Comment by benschenker** [comment]
Ha don't hate yourself! We all feel silly when we make mistakes but it is a real part of the learning process.  Take a look at the gitter chat room and you will see things like this every 5 minutes.

It looks like this is resolved and can be closed.

**Comment by dokkillo** [comment]
@xchelm i have a lot of problems with lenght and length.....
