### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Zibann** [FreeCodeCamp/FreeCodeCamp#2561]
Challenge http://freecodecamp.com/challenges/waypoint-ditch-custom-css-for-bootstrap has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey @Zibann thanks for taking the time to report an issue.

Please take a look at our [Bug Report Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) as that should help you resolve most issues in the fastest way possible.

This should be closed for now, but if the above steps don't solve your problem then reopen this issue with some more details.

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!
