### ISSUE TITLE
Linking to git hub to unlock profile...good for viewing others profiles but own profile should be unlocked

### ISSUE THREAD

**Issue by AdventureBear** [FreeCodeCamp/FreeCodeCamp#2563]
It feels manipulative to have to link the github account to unlock your own profile/saved solutions. 

It would make a lot of sense depending on the motive for linking to github, to require that to view others solutions.

**Comment by benschenker** [comment]
Hey @AdventureBear thanks for posting this.

I'm not sure I understand your concern, could you clarify?  What do you mean by unlock?

**Comment by bugron** [comment]
Now you can view your solutions in your code portfolio (profile page) without linking GitHub account. Closing this issue.
