### ISSUE TITLE
Success Before Challenge Complete

### ISSUE THREAD

**Issue by eyeMNaughtReal** [FreeCodeCamp/FreeCodeCamp#2564]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-hex-code-to-color-elements-red has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

As I was typing in the body element, I only got as far as the first open bracket (<), when it allowed me to go to the next challenge.

![image](https://cloud.githubusercontent.com/assets/13009248/9427068/3e81c988-4936-11e5-9ef3-0cc4749b04e2.png)

**Comment by benschenker** [comment]
Hey @eyeMNaughtReal thanks for posting!

I think the `body` element here is inferred and you don't actually need to add the `<body>` tag to the html.
