### ISSUE TITLE
JQuery Waypoint nth-child() error

### ISSUE THREAD

**Issue by r00tl0gin** [FreeCodeCamp/FreeCodeCamp#2566]
Challenge http://freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I am seeing this error in the console on using the nth-child selector with the .well class for applying the animated bounce class as per the exercise 

"Syntax error, unrecognized expression: :nth-child()"

I have rechecked my syntax multiple times and it seems to follow the right way to call this selector but its passing through the test as that error keeps popping up on the developer console.

Is this a bug with my code alone ?

**Comment by ahstro** [comment]
Could you post your code wrapped in ``` so we can test it?

**Comment by r00tl0gin** [comment]
This was the code that I wrote
```$(".well:nth-child(2)").addClass("animated bounce");```

**Comment by ahstro** [comment]
I'm not getting the error message you mentioned above. Where do you find it and could you possibly screenshot it?

**Comment by r00tl0gin** [comment]
![freecodecamp](https://cloud.githubusercontent.com/assets/13740719/9432177/9365389a-49db-11e5-9cee-47d697398f51.JPG)

Here is a screenshot of that page. I am not able to complete that waypoint as it says :nth-child() is not recognized.

**Comment by noahrubin** [comment]
I was able to reproduce the error with the code:

$(".well:nth-child(2)").addClass("animated bounce");

If you refer to the CSS docs (http://www.w3schools.com/cssref/css_selectors.asp) it says that p:nth-child(n) selects all p's that are the nth child of their parent, so selecting .well:nth-child() is invalid. Working code is:

$("button:nth-child(2)").addClass("animated bounce");

**Comment by ahstro** [comment]
@r00tl0gin The immediate error I can see is that you're trying to call `:nth-child()` on `#well`, which points to a non-existing element with the id of `well`.
`:nth-child()` is a bit strange, but keep trying and you'll get there, but for now, close this as it's not an error with FCC. :)

**Comment by r00tl0gin** [comment]
@noahrubin  @ahstro  It got fixed by putting a space between .well and :nth-child(). I think the test case checks for a space between them to make it work. I am closing this one for now. Thanks for your prompt response guys !! :)

**Comment by ahstro** [comment]
@r00tl0gin It doesn't check for a space, the space makes it apply to the decendants of `.well`. Check out [this comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1927#issuecomment-132369084) for a bit of an explanation.
