### ISSUE TITLE
Regex Specify matches is used before it is taught

### ISSUE THREAD

**Issue by empty-god** [freeCodeCamp/freeCodeCamp#25676]
**Describe your problem and how to reproduce it:**
The Regex Challenge Restrict Possible Usernames uses the knowledge gained from Specify Upper and Lower Number of Matches and its following challenge. They should probably placed before or the Restrict Usernames challenge be placed after.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 69.0.3497.100
* Operating System: MacOS 10.13.3

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@empty-god Can explain in detail why you think the challenge `The Regex Challenge Restrict Possible Usernames` requires knowing `Specify Upper and Lower Number of Matches` information to solve the former?

**Comment by RandellDawson** [comment]
Hi @empty-god 

As there has been no response from your end for a while, we are closing this ixxud.

Feel free to request this issue to be reopened, if you can answer the question I last posed.

Thank you.
