### ISSUE TITLE
bug in bonfire-seek-and-destroy 

### ISSUE THREAD

**Issue by Abdelaziz18003** [FreeCodeCamp/FreeCodeCamp#2572]
![fireshot screen capture 006 - bonfire_ seek and destroy i free code camp - www_freecodecamp_com_challenges_bonfire-seek-and-destroy](https://cloud.githubusercontent.com/assets/11301627/9427878/0b549d56-498b-11e5-8d1a-59f67ed0ec67.jpg)
I tried the code provided in the screenshot above and it worked well in the browser console. But it always return the original array in the challenge and doesn't make any changes on it.

**Comment by ahstro** [comment]
Are you sure it's working in the console, because I can't get it to work.

**Comment by Abdelaziz18003** [comment]
thanks @ahstro for your time. forget about it, it was my fault the argument inside the anonymous function is not the same outside. but although I did not understand how it worked once in the console. 
thanks a lot.
