### ISSUE TITLE
Instead of targeting element 6 all the elements are getting targeted. 

### ISSUE THREAD

**Issue by daksh844** [FreeCodeCamp/FreeCodeCamp#2573]
Hi using the jQuery function the challenge is to change the element 6 color to Green which would be achieved by this code:
$("#right-well").children("#target6").css("color", "green");  
but this above mentioned code isn't working and its accepting this below code instead-
$("#right-well").children().css("color", "green");  

I'm also including the screenshot for your reference:
![image](https://cloud.githubusercontent.com/assets/8793646/9427979/3b6a09f6-49b6-11e5-8c3d-a9c6d2573a8b.png)

Challenge http://freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by arya45** [comment]
Hi! From the instructions, the goal is to target ALL children of right-well, not just #target6. I agree that the first checkmark is confusing, as it makes you think that you should change the color for #target6 only. Obviously #target6 should be green, but it should not be put as a separate objective: when the code is run, FCC will check if #target5, #target6 and #target7 are green.
