### ISSUE TITLE
Adding LinkedIn account not working

### ISSUE THREAD

**Issue by Gelio** [FreeCodeCamp/FreeCodeCamp#2576]
When trying to add a LinkedIn account to my profile I get redirected but there seems to be an invalid redirect_uri parameter in there. I can provide a screenshot if needed.

**Comment by issyl0** [comment]
A screenshot would be useful, please. I just tried to add a LinkedIn account and succeeded. :confused:

**Comment by Gelio** [comment]
I do not know what to expect, I guess a simple notification that it succeeded would be nice.

Here's the screenshot: 

![](https://i.gyazo.com/dc5622c0180072ef115a2fbba7d02a8d.png)

That can't be a success.

**Comment by issyl0** [comment]
Sorry! I misunderstood your issue. I just successfully replicated the bug when adding LinkedIn to an existing account, not signing in for the first time with LinkedIn. So this is confirmed now. I'll attempt to fix it. :+1:

**Comment by Gelio** [comment]
No problem with that, thank you for looking into my issue. I have no experience working with OAuth (which I'm guessing this API uses) so it will be a good opportunity for me to also check it out and possibly find a solution.

**Comment by issyl0** [comment]
Feel free to have a go!

**Comment by BerkeleyTrue** [comment]
arg... ok, this should be fixed later today.

**Comment by QuincyLarson** [comment]
Thanks for reporting this. we've now fixed it.
