### ISSUE TITLE
Handle uncaught expressions

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/freecodecamp#258]
@QuincyLarson 

We need to add a process like foreverjs in production and handle uncaught exceptions. This will allow server to crash fast and restart. This is typically what people do.

```js
process.on('uncaughtException', function (err) {
  console.error((new Date).toUTCString() + ' uncaughtException:', err.message)
  console.error(err.stack)
  process.exit(1)
});
```

**Comment by terakilobyte** [comment]
We are using nodemon to currently keep the server spun up, or we were

**Comment by BerkeleyTrue** [comment]
In production?

**Comment by BerkeleyTrue** [comment]
I see forever in production we just need to add the above
