### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by gagandeep1410** [FreeCodeCamp/FreeCodeCamp#2580]
Challenge http://freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by gagandeep1410** [comment]
![screenshot from 2015-08-20 09 46 57](https://cloud.githubusercontent.com/assets/11147985/9428365/277aa21c-49c9-11e5-8ed7-27ae642ad13c.png)

**Comment by gagandeep1410** [comment]
![screenshot from 2015-08-23 18 58 29](https://cloud.githubusercontent.com/assets/11147985/9428367/461900ba-49c9-11e5-9103-7717be5842eb.png)

**Comment by ahstro** [comment]
Does a [hard refresh](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache) do the trick?
