### ISSUE TITLE
http://freecodecamp.com/challenges/waypoint-use-hex-code-to-color-elements-green

### ISSUE THREAD

**Issue by dgoran** [FreeCodeCamp/FreeCodeCamp#2581]
Challenge http://freecodecamp.com/challenges/waypoint-use-hex-code-to-color-elements-green has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

As I was going through it did not five me credit for completion in the MAP (not checked as completed)

**Comment by benschenker** [comment]
Hey @dgoran thanks for posting this issue.

Its been a couple of weeks, has this been resolved?  If not can you post a screenshot and maybe the code that is not passing for that challenge?
