### ISSUE TITLE
Skipped this for whatever reason

### ISSUE THREAD

**Issue by dgoran** [FreeCodeCamp/FreeCodeCamp#2582]
Challenge http://freecodecamp.com/challenges/waypoint-add-different-margins-to-each-side-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

As I was going through HTML Waypoint No 44 was skipped I just noticed it by reviewing my progress in the MAP and wondering why is HTML not showing as completed

**Comment by benschenker** [comment]
Hey @dgoran thanks for posting this!

I was not able to replicate this.  Is it still an issue for you?
