### ISSUE TITLE
iOS asks if I want to log in even though I already am logged in

### ISSUE THREAD

**Issue by RaspberryLime** [freeCodeCamp/freeCodeCamp#25835]
![543f99a2-a859-4e13-971f-44649bbe74a2](https://user-images.githubusercontent.com/25120737/47287178-5120cb00-d5e9-11e8-986b-3d1b23dcfa65.png)

I'm using an iPad, with iOS 12.0.1, and Safari. Landscape mode, though it happens in portrait mode too.

Steps to reproduce.

1. Log in to freeCodeCamp.org (I use GitHub).
2. Click on the Settings link at the top.

I can't view the source code to check what I think is happening, but I think iOS is picking up on the name or type of the Username input field and then just automatically offering to log in. If this is the case a way around it might be to load the input field disabled, with a different name or type, and with a "change username" button. When the button is clicked it enables the input field and changes the name/type to whatever it is now.

**Comment by scissorsneedfoodtoo** [comment]
@RaspberryLime, can you check if this is still and issue on the [beta](https://www.freecodecamp.rocks/) site?

**Comment by RaspberryLime** [comment]
@scissorsneedfoodtoo I can’t log in to the beta site. Do I need to create a new account there?

**Comment by scissorsneedfoodtoo** [comment]
Yes, you'll need to make a new account. Could you make one and report back if this is still and issue?

**Comment by RaspberryLime** [comment]
I’m having trouble with the beta site. I can only log in via email not via Github, and the email route doesn’t involve iOS’ password manager at all.

I’ll mark this as fixed because I can’t replicate it on the live site either now — if it reoccurs I’ll re-open it.

**Comment by scissorsneedfoodtoo** [comment]
@RaspberryLime, sorry to hear that. I usually use my email to log in, so I didn't realize the GitHub or other routes aren't available on the beta site now.

Thank you for checking, and please reopen this issue if you run into this problem again.
