### ISSUE TITLE
iOS - visual glitch - Save button truncated on Settings page

### ISSUE THREAD

**Issue by RaspberryLime** [freeCodeCamp/freeCodeCamp#25838]
**Describe the bug**
The "Save" button is truncated next to  the "Username" input field.

**To Reproduce**
1. Log in to freeCodeCamp.
2. Go to the "Settings" page.
3. See the "Save" button is truncated next to the "Username" field.

**Expected behavior**
Button should be fully readable.

**Screenshots**
![9a093754-ce1d-4e9f-a658-5d87da9d288f](https://user-images.githubusercontent.com/25120737/47288176-e40f3480-d5ec-11e8-96dd-4ad6d2662283.png)

**Desktop (please complete the following information):**
 Not tested, no access.

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: 12.0.1
 - Browser: Safari
 - Version: whatever is installed with iOS 12.0.1.

**Additional context**
This only happens in portrait mode. Landscape mode is fine.

**Comment by revolter** [comment]
It looks like this is already fixed in `master`.

**Comment by RaspberryLime** [comment]
It's displaying properly for me now. 🙂

**Comment by RaspberryLime** [comment]
Thank you, I'll close this as soon as the fix is released on the live site.

**Comment by scissorsneedfoodtoo** [comment]
@RaspberryLime, can you check if this is still and issue on the [beta](https://www.freecodecamp.rocks/) site?

**Comment by RaspberryLime** [comment]
I’m unable to log in on the beta site — do I need to create a new account there?

**Comment by scissorsneedfoodtoo** [comment]
Yes, you'll need to make a new account. Could you make one and report back if this is still and issue?

**Comment by RaspberryLime** [comment]
This is indeed fixed on the beta (the save button is now underneath the field instead of alongside it).

**Comment by RaspberryLime** [comment]
It’s also fixed on the live site too — the button hasn’t been moved there, but it’s no longer truncated. :)

**Comment by scissorsneedfoodtoo** [comment]
@RaspberryLime, great! Thank you for checking this out.
