### ISSUE TITLE
JQUERY waypoint seems to have an issue.

### ISSUE THREAD

**Issue by oluwatimilehinn** [FreeCodeCamp/FreeCodeCamp#2584]
Challenge http://freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Here's my code:
```html
 <script>
  $(document).ready(function() {
    $("button").addClass(animated);
    $(".btn").addClass( animated shake );
  $("#target1").addClass( animated shake btn-primary)

  });
</script>
 ```
I have no idea why I can't move to the next page.

**Comment by benschenker** [comment]
Hey @oluwatimilehinn thanks for posting an issue!

Check out our [Bug Posting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) for some steps to go through if you are having issues with the site.  That is the fastest way to get help.

I cannot see your code so I can't really help you...This should be closed for now but feel free to respond to this thread if the above steps are not helpful in resolving your problem.

**Comment by BerkeleyTrue** [comment]
I've added the backticks.

**Comment by benschenker** [comment]
Thanks @BerkeleyTrue!

@oluwatimilehinn, the `addClass` function accepts a string but you are not putting in strings (those look like undefined variables).  Does that help?

**Comment by BerkeleyTrue** [comment]
@benschenker Is correct. 

Happy Coding!
