### ISSUE TITLE
Waypoint: Target HTML Elements with Selectors Using jQuery Issue

### ISSUE THREAD

**Issue by fkalkhalidi** [FreeCodeCamp/FreeCodeCamp#2585]
Challenge http://freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. 

I enter the correct code for this waypoint, but it's not recognizing it's correct.

**Comment by benschenker** [comment]
Hey @fkalkhalidi thanks for submitting an issue!

Take a look at our [Bug Reporting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) for some steps to go through before posting an issue here.  We specifically need a way to try to reproduce the issue: screenshots, code samples, etc.

This issue can be closed for now, but feel free to comment on this thread if the above steps are not helpful in resolving your problem

**Comment by fkalkhalidi** [comment]
@benschenker I managed to complete the challenges in Safari. Seems the issue was in Chrome.
