### ISSUE TITLE
Waypoint: Target HTML Elements with Selectors Using jQuery

### ISSUE THREAD

**Issue by rsavage-urquad** [FreeCodeCamp/FreeCodeCamp#2586]
Running Chrome [Version 44.0.2403.155 (64-bit)] on Mac [Version 10.10.5 (14F27)].  Solution appears to be correct, but is not being accepted.  Entered manually and also cut & paste from example.

![screen shot 2015-08-23 at 10 32 17 am](https://cloud.githubusercontent.com/assets/7781587/9428615/4bab1276-4982-11e5-8019-1064ab0f01c3.png)

Challenge http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey @rsavage-urquad thanks for submitting an issue!

I'm having trouble replicating your issue though it seems to be a duplicate of #2352 so keep an eye there for any updates.

Take a look at our [Bug Reporting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) for some steps to go through before posting an issue here.

This issue can be closed as a duplicate.

**Comment by rsavage-urquad** [comment]
Thanks Ben, after having the same issue on several Waypoints, I submitted another item (#2587).  The issue seems to be with a Mac/Chrome combination as I had no issues with the Waypoints on a PC using Chrome.

**Comment by rsavage-urquad** [comment]
Resubmitted on another item (#2587).  Will close this.
