### ISSUE TITLE
jQuery Waypoint Issues on Mac/Chrome (No Issues on PC/Chrome)

### ISSUE THREAD

**Issue by rsavage-urquad** [FreeCodeCamp/FreeCodeCamp#2587]
Mac Version: 10.10.5 (14F27)
Chrome Version: Version 44.0.2403.155 (64-bit)
Had issues with jQuery Waypoints on Mac/Chrome.  Tried them on PC/Chrome and had no issues

Waypoint: Target HTML Elements with Selectors Using jQuery
Waypoint: Target Elements by Class Using jQuery
Waypoint: Target Elements by ID Using jQuery
Waypoint: Target the same element with multiple jQuery Selectors
Waypoint: Remove Classes from an element with jQuery
Waypoint: Change the CSS of an Element Using jQuery
Waypoint: Disable an Element Using jQuery
... (gave up here and tried, successfully, on PC)

![screen shot 2015-08-23 at 10 46 14 am](https://cloud.githubusercontent.com/assets/7781587/9428730/45be1954-4986-11e5-8220-d701a620489b.png)

Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by ObaPeter** [comment]
I'm having the same issue.

**Comment by benschenker** [comment]
Hey @rsavage-urquad thanks for posting another issue!

I'm having trouble replicating on an almost identical system (MAC/Chrome), have you tried resetting the lesson with the `reset` button or opening it up in an incognito window?

**Comment by rsavage-urquad** [comment]
Tried "Reset" with no success.  I just tried again on Mac/Chrome (after Chrome restart) and code is now working (being accepted).

Thanks

**Comment by danielmdesigns** [comment]
I was having issues on MAC and is now working for me as well. Thanks!
