### ISSUE TITLE
Create indicator where learner/student is in the Map

### ISSUE THREAD

**Issue by dgoran** [FreeCodeCamp/FreeCodeCamp#2589]
![proposed edit](https://cloud.githubusercontent.com/assets/2241367/9428851/683862e2-498a-11e5-8fda-71b60af790df.jpg)
Challenge http://freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I realized that I feel "lost" while learning and being slightly buggy I think it is because I lost trust in navigation to take me to next waypoint SO I propose small change that would indicate where we are in the learning process...

**Comment by ahstro** [comment]
+1, but I think this might be better implemented when FCC is Reactified?

**Comment by dgoran** [comment]
There is a new version coming that will use react?

Goran Draskovic

**Comment by ahstro** [comment]
@dgoran It's [one](https://github.com/FreeCodeCamp/FreeCodeCamp/milestones/Reactify%20FCC) of the [milestones](https://github.com/FreeCodeCamp/FreeCodeCamp/milestones) as well as mentioned in [a blog post](http://blog.freecodecamp.com/2015/08/rebuilding-the-747-at-35000-feet.html) (search for `single-page`).

**Comment by BerkeleyTrue** [comment]
Yes, in the coming weeks. Other features are pending at the moment.

**Comment by awesomeaniruddh** [comment]
I think this can be closed now. CC: @FreeCodeCamp/issue-moderators
