### ISSUE TITLE
Clicking "Reply" in Camper News, when logged out, should bring up the login page.

### ISSUE THREAD

**Issue by CodeNonprofit** [FreeCodeCamp/freecodecamp#259]
Right now clicking "reply" does nothing while not logged in.

**Comment by BerkeleyTrue** [comment]
Thanks @CodeNonProfit. Any campers out their want to tackle this?

**Comment by BerkeleyTrue** [comment]
Will also add upvote button to this ticket.

**Comment by terakilobyte** [comment]
What should it do? A popover?

**Comment by BerkeleyTrue** [comment]
Unauthenticated campers clicking on `reply` or `upvote` should be redirected to login page. Once logged in they should be redirected back to the page they were on before.

**Comment by jameskopacz** [comment]
Is this worth fixing since you guys are moving away from this branch?

**Comment by terakilobyte** [comment]
It is worth fixing, we're keeping the ux-improvements feature branch patched with the latest changes from master and camper news lives separate from 99% of the changes we're making

**Comment by jameskopacz** [comment]
#271 

Also while checking this out, the Story ```user = ;``` JS error is back. I think the previous fix caused login problems? That's the reasoning for using ```typeof``` in the updated code since just doing ```!user``` would cause an error.
