### ISSUE TITLE
New Language for the Guides?

### ISSUE THREAD

**Issue by b3u** [freeCodeCamp/freeCodeCamp#25907]
Hey all,
I would love to contribute to freeCodeCamp and give back from the knowledge I've learned. I'm most comfortable in html and css, not so much javascript, so I can't fix the bugs. I know a foreign language, Hebrew, and although it's not listed in the languages freeCodeCamp is working on, I figured, why not? @QuincyLarson How should I go about introducing this language to the guides/curriculum? Thanks! Happy Hacktober.

**Comment by ezioda004** [comment]
Hi @b3u,

Thank you for opening this issue.
Please refer to this thread https://github.com/freeCodeCamp/freeCodeCamp/issues/18966 for further discussion.

Thank you.
