### ISSUE TITLE
Typo correction and weird display in chrome

### ISSUE THREAD

**Issue by bcatubig** [FreeCodeCamp/FreeCodeCamp#2592]
Challenge http://freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript has an issue. 

"You should have multiplied the result of Math.random **but** 10 to make it a number that's greater then zero"

But I believe is a typo for 'by'

![image](https://cloud.githubusercontent.com/assets/1383904/9429029/36a1739c-4988-11e5-8da0-b371a4bb457d.png)

**Comment by jbmartinez** [comment]
Also, it should be "greater *than*" zero
