### ISSUE TITLE
Wondering about this formula

### ISSUE THREAD

**Issue by infoalisaa** [FreeCodeCamp/FreeCodeCamp#2595]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-javascript-slot-machine has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Hello,

 I was working on this problem, and I was just wondering about the formula that was used in order to solve this problem:

Math.floor(Math.random() * (3 - 1 + 1)) + 1;

Doesn't this just mean the same thing as:

Math.floor(Math.random() * (3)) + 1;

I tried to use this formula, but it would not let me pass the level without using the example provided.

Also, it might be useful to other campers to give a detailed explanation as to how this works and why it does work.

Thanks!!
Alisa

**Comment by jbmartinez** [comment]
Hello, I was going to write an explanation for this here and I thought someone should already have explained somewhere, and here it is: http://stackoverflow.com/a/1527820

I agree, that formula should be explained in the curriculum.

**Comment by benschenker** [comment]
Good point!  I think if we link to that it should be where we first see the formula: http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-within-a-range

**Comment by abhisekp** [comment]
@infoalisaa The explanation is in the FCC wiki. https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Waypoint-Generate-Random-Whole-Numbers-within-a-Range#explanation

**Comment by awesomeaniruddh** [comment]
Oh. I'll update my PR then. Prefer Wiki to external sources :D
