### ISSUE TITLE
Spaces are considered to validate the chalenge

### ISSUE THREAD

**Issue by felipecaputo** [FreeCodeCamp/FreeCodeCamp#2597]
Challenge http://freecodecamp.com/challenges/waypoint-give-your-javascript-slot-machine-some-stylish-images has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

It is considering spaces to validate code in:

```javascript
 $($('.slot')[0]).html('<img src = "' + images[slotOne-1] + '">');
    $($('.slot')[1]).html('<img src = "' + images[slotTwo-1] + '">');
    $($('.slot')[2]).html('<img src = "' + images[slotThree-1] + '">');
```
is validated, but the code below with spaces in `slotOne - 1` for example do not validate

```javascript
 $($('.slot')[0]).html('<img src = "' + images[slotOne - 1] + '">');
    $($('.slot')[1]).html('<img src = "' + images[slotTwo - 1] + '">');
    $($('.slot')[2]).html('<img src = "' + images[slotThree - 1] + '">');
```

**Comment by benschenker** [comment]
Thanks for posting @felipecaputo!

Confirmed, I was able to replicate this.

Its actually hard to find the differences between those two code blocks so I'll highlight them here:

`slotOne-1` vs
`slotOne - 1`

**Comment by felipecaputo** [comment]
You're welcome... Another thing that happened today was sometimes it didn't validate double quotes instead of single quotes when I see it happening again, I'll post here.... And congratulations for the amazing tool.

**Comment by h4r1m4u** [comment]
I don't know if this is the right place to post, but this is not yet resolved. The whitespaces around the minus sign (' - ') still invalidate the code and it doesn't pass the test.

**Comment by minustehbare** [comment]
+1 as I also just encountered this problem; it does not appear to be resolved.

**Comment by theroncross** [comment]
+1. I did notice that the given code has spaces around the src attribute: src = "'. That seems odd to me - shouldn't it read: src="'? Either way it didn't get me to pass that first test. Copied/pasted code, reset page, etc. All other tests passed.

$($('.slot')[0]).html('<img src = "' +  images[slotOne-1] + '">');
    $($('.slot')[1]).html('<img src = "' +  images[slotTwo-1] + '">');
    $($('.slot')[2]).html('<img src = "' +  images[slotThree-1] + '">');

AND 

$($('.slot')[0]).html('<img src="' +  images[slotOne-1] + '">');
    $($('.slot')[1]).html('<img src="' +  images[slotTwo-1] + '">');
    $($('.slot')[2]).html('<img src="' +  images[slotThree-1] + '">');
