### ISSUE TITLE
Run Code Popup Window Auto-Enabled On All Completed Challenges

### ISSUE THREAD

**Issue by CoderNurse** [FreeCodeCamp/FreeCodeCamp#2600]
If one has successfully completed a challenge, ie any waypoint/bonfire, etc, if you go to "Map" and click back to any of your old completed challenges, say, to check your earlier code for reference on a new problem, the "Run code" is automatically enabled and throws up the pop up window with "Go to my next challenge". It's not a huge issue. Just kind of distracting, as you have to close this window each time just to see your earlier code.

**Comment by benschenker** [comment]
Yeah I agree this is kind of a pain.  Though I see a bit of value in having a visual indicator that the solution is correct

**Comment by CoderNurse** [comment]
There already is a visual indicator: all the green checked circles indicate you've successfully completed it. I can understand the need for the pop up if you click on the "Run code" button again, but not if you're simply returning to the page.

**Comment by benschenker** [comment]
Looks like this has been fixed as now you need to press `run code` before the code is evaluated.
