### ISSUE TITLE
step 18 doen't exist in expressworks and skipped step

### ISSUE THREAD

**Issue by srodman7689** [FreeCodeCamp/FreeCodeCamp#2603]
Challenge http://freecodecamp.com/challenges/waypoint-build-web-apps-with-expressjs has an issue. 
Session and Cookie is no longer in expressworks. the two that seem to be the replacement for this are called PARAM PAM PAM and WHAT'S IN QUERY. Also, after Hello World, expressworks has a Static step that helps with the Stylish CSS step done right before the PARAM PAM PAM step. I can create a pull request with the new suggested setup if you guys want. Or if there is something that I am not seeing or the page needs to be setup in a different way please let me know.

**Comment by zeffii** [comment]
Good, somebody else spotted this too..  "Session and Cookie" is no longer an expressworks step.

**Comment by srodman7689** [comment]
I don't mind creating a pull request for this at all, I just need to know if I should add in the Static step After Hello World and change Session and Cookie to PARAM PAM PAM and add WHAT'S IN QUERY (these are all steps in expressworks). Also long as this is the case I can have a pull request created and ready to go in about 5 mins.

**Comment by CharlesMilam** [comment]
The expressworks does not appear to be part of FCC's repo. Not sure if expressworks was created just for FCC or is used elsewhere. They might have changed the steps for their own purposes. 

I was just doing all of the steps in expressworks, then reviewed the waypoint again when I noticed the steps were different. I ran into a bug with the What's in Query. No solution I could find would pass the verify test. Even their own solution fails the test.

**Comment by AdventureBear** [comment]
I would just  have the FCC instructions allow the studen tto complete all the steps without naming them, since it's likely future updates of expressworks may change the steps again. 

Alos, seeing as I posted this issue in another request, something added to the FCC "report a bug" button that could automatically flag prior issues created using the same button.  That would save work from the moderators.

**Comment by bugron** [comment]
@AdventureBear that feature is coming https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2943.

**Comment by AdventureBear** [comment]
yay!  good work. :)
