### ISSUE TITLE
Basic Java lesson 39 script error

### ISSUE THREAD

**Issue by Tshebade** [FreeCodeCamp/FreeCodeCamp#2604]
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

when following the directions you are prompted to enter some code.

$($(".slot")[0]).html(slotOne);

When you type an opening parenthesis it auto populates the closing parenthesis causing the code to become // $($) // when getting to this point it freezes the entire page. I am pretty sure it has to do with the page refreshing and creating a scripting error. browser used was Safari 7.1.8. same problem happens in other browsers, at least when using firefox it will prompt you to quit running scripts on the page allowing you to move beyond the problem.

**Comment by benschenker** [comment]
Hey @Tshebade thanks for posting an issue!

Take a look at #2286 and #1960 for more info about these issues.

You may need to clear your cache/reset the lesson.

This can be closed as a duplicate.
