### ISSUE TITLE
Checkboxes have wrong info

### ISSUE THREAD

**Issue by AshleyMSherwood** [FreeCodeCamp/FreeCodeCamp#2605]
Challenge http://freecodecamp.com/challenges/waypoint-manipulate-arrays-with-shift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Please see screenshot: 
![screenshot from 2015-08-23 18 08 10](https://cloud.githubusercontent.com/assets/9452459/9430610/0ac05934-49c2-11e5-9d03-25843dfe9a05.png)

**Comment by benmcmahon100** [comment]
I can't see the problem here. Are you referring to the tests?

**Comment by AshleyMSherwood** [comment]
Yes,  I think so.  They say 'myArray should only have the first two values left(["John", 23])' and 'myRemoved should contain "John"' but  actually the tutorial wants you to shift off "John" and the array should be [23, {"dog", 3]] which is shown correctly in the comments in the editor.  Does that make sense?

**Comment by benmcmahon100** [comment]
Ah yes i see the messages are copied and pasted from the last challenge I'll sort that now!
