### ISSUE TITLE
Waypoint: Manipulate Arrays With unshift

### ISSUE THREAD

**Issue by FreecodecamperSLV** [FreeCodeCamp/FreeCodeCamp#2608]
I need help won't let me go to next challenge  

![screenshot 2015-08-23 18 26](https://cloud.githubusercontent.com/assets/13788908/9430687/c041a888-49c4-11e5-8feb-a3b842c795cb.jpg)

**Comment by benmcmahon100** [comment]
You should be unshifting the string paul. you are trying to unshift an array containing paul so:
this
```javascript
myArray.unshift("Paul")
```
instead of this
```javascript
myArray.unshift(["Paul"]);
```

**Comment by FreecodecamperSLV** [comment]
Omg!
