### ISSUE TITLE
Browser Freeze on JavaScript Challenge

### ISSUE THREAD

**Issue by flamechamp** [FreeCodeCamp/FreeCodeCamp#2609]
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I'm just beginning the challenge and typed $($) when suddenly my browser freeze and I can't do anything. I tried refreshing and it won't work. I tried opening new window and it still freeze.

**Comment by asandyz** [comment]
I also am experiencing the same issue, Please consider this  as it makes that waypoint module  not to complete succesfully.

Thanks and Regards,
Sandeep Lakka

**Comment by benmcmahon100** [comment]
We are currently unable to fix this as it is a tricky issue to pin down. You are able to pass the challenge by copying and pasting the code from the description.

**Comment by asandyz** [comment]
But as the script $($) will already be there after the first freeze, It's not possible for us to modify anything as it's freezes as soon as it loads up. :frowning:

**Comment by jbmartinez** [comment]
There are two (or more) workarounds:

1. You can log in from an incognito window, solve that challenge and then continue in a normal window.

2. You can clear your browser's local storage, but you will loose the solution to all the waypoint challenges (your progress in the map won't be lost).

**Comment by asandyz** [comment]
@jbmartinez  thanks dude! :+1:

**Comment by benmcmahon100** [comment]
Good news people! We will soon(hopefully) be deploying a new version of the test suite that we use for the challenges that will fix this and the function issue!

**Comment by BerkeleyTrue** [comment]
fixed!
