### ISSUE TITLE
http://freecodecamp.com/challenges/ causes redirect loop

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#2612]

**Comment by BerkeleyTrue** [comment]
Can't replicate. Seems to work fine at the moment.

**Comment by beefnog** [comment]
I experienced this same redirect loop today, around 0940 PDT.

**Comment by ahstro** [comment]
`Firefox has detected that the server is redirecting the request for this address in a way that will never complete.`
Seems to be happening to me as well.
Let the record show that a similar error occurs in Chromium.

**Comment by awesomeaniruddh** [comment]
Seems like `challenges` is someone's username?
![screenshot 8](https://cloud.githubusercontent.com/assets/5279150/9835557/c02bdfe8-5a23-11e5-93b8-a18e066f06aa.png)

**Comment by BerkeleyTrue** [comment]
I'm 100% positive that is not what causes the redirect loop. That being said, challenges should be a blacklisted name.

**Comment by awesomeaniruddh** [comment]
Yep

**Comment by awesomeaniruddh** [comment]
Closing this because `/challenges/` now gives a 404.
