### ISSUE TITLE
Waypoint: Target the Parent of an Element Using jQuery

### ISSUE THREAD

**Issue by EllieAdam** [FreeCodeCamp/FreeCodeCamp#2613]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![screen shot 2015-08-23 at 9 24 41 pm](https://cloud.githubusercontent.com/assets/7389754/9432803/810b00c4-49dd-11e5-9af1-45c7147c084e.png)

**Comment by noahrubin** [comment]
If I'm understanding your issue correctly, your code here sets the entire left-well div background, including the header text "left-well" to red, when in fact you should be targeting the parent of "#target1" and setting the background color.

**Comment by bugron** [comment]
@EllieAdam thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2337
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1934

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Comment by EllieAdam** [comment]
```
 $(document).ready(function() {
    $("#target1").css("color", "red");

    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
     $("#target1")parent().css("color", "red");
```

I tried this to target the immediate parent but didn't pass.

**Comment by EllieAdam** [comment]
just disregard my issue :)

**Comment by benschenker** [comment]
You may close this issue if your problem has been fixed.
