### ISSUE TITLE
Typo on Waypoint: Generate Random Whole Numbers with JavaScript

### ISSUE THREAD

**Issue by leftynaut** [FreeCodeCamp/FreeCodeCamp#2614]
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript has an issue.

Typo - "You should have multiplied the result of Math.random but 10 to make it a number that\'s greater then zero');"

Correction - "You should have multiplied the result of Math.random by 10 to make it a number that\'s greater then zero');"

**Comment by michael-krebs** [comment]
Thanks for reporting, but this is a duplicate of #2592 and has since been fixed
