### ISSUE TITLE
Issue with the Jquery Challenge 15

### ISSUE THREAD

**Issue by pushkardakle** [FreeCodeCamp/FreeCodeCamp#2615]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue. 

The challenge will not allow the user to proceed even after posting the right solution i.e.
```javascript
$('.well:nth-child(2)').addClass("animated bounce");
```
Currently the workaround to get ahead is to add a space after before and after the colon(Thanks to user **@saadmehmood233** for pointing it out). The use of these spaces should not be binding as they are not required as per the syntax and it should be removed.

**Comment by noahrubin** [comment]
Try the following:

$("button:nth-child(2)").addClass("animated bounce");

Refer to: http://www.w3schools.com/cssref/css_selectors.asp

**Comment by benschenker** [comment]
Hey @pushkardakle thanks for posting an issue!

Take a look at [my comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1927#issuecomment-132369084) on duplicate issue #1927, that may help clear things up a bit.  `:nth-child(n)` just specifies that the **current element** has to be the nth child of its parent.
