### ISSUE TITLE
The run code button does nothing

### ISSUE THREAD

**Issue by Dadsaster** [FreeCodeCamp/FreeCodeCamp#2616]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I typed in both example comments but nothing happens when attempting to submit it.

**Comment by benschenker** [comment]
Hey @Dadsaster thanks for posting!

Have you seen our [Bug Posting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)? They may help you clarify exactly the problem you are having.  We specifically need screenshots and code samples to attempt to diagnose the issue.

**Comment by Dadsaster** [comment]
I understand the guidelines but in an instance where nothing happens a screenshot or code samples won't help troubleshoot the problem.  I will include them in the future.

**Comment by benschenker** [comment]
We just want to make sure we can replicate by doing exactly what you did

**Comment by Dadsaster** [comment]
I totally understand.  Hope this helps.
![screen shot 2015-08-24 at 9 58 32 am 2](https://cloud.githubusercontent.com/assets/10624757/9446489/e39bfa36-4a46-11e5-8bfd-f3d947562e00.png)

**Comment by Dadsaster** [comment]
I just tried writing a function just to see if the button would run the code.  When I complete the word function my browser freezes (I've repeated it 3 times).

![screen shot 2015-08-24 at 10 06 57 am 2](https://cloud.githubusercontent.com/assets/10624757/9446711/e6c0ee14-4a47-11e5-89de-19f70d16230d.png)

**Comment by benschenker** [comment]
Thanks for the screenshot that actually helps a lot, does this same bug appear when you open the challenge in an incognito window in chrome?

**Comment by Dadsaster** [comment]
I was able to execute the challenge in incognito although typing function still causes the site to crash.

**Comment by benmcmahon100** [comment]
The typing of function is a known issue that causes a crash. I am working on finding a solution to this.

**Comment by BerkeleyTrue** [comment]
This is now fixed.

Happy Coding!
