### ISSUE TITLE
"Go to my next challenge" button not working

### ISSUE THREAD

**Issue by westonludeke** [FreeCodeCamp/FreeCodeCamp#2622]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-nthtolast-character-in-a-string has an issue. 

When completing the page and getting the green checkbox screen, the button that says, "Go to my next challenge" is not clickable. I can "x" out of the entire box, but not click to continue to the next challenge. Screenshot: http://screencast.com/t/clrQ0P8pq9um

**Comment by benschenker** [comment]
Hey thanks for posting this @westonludeke!

I'm having trouble replicating this issue, is it still problematic for you?

**Comment by westonludeke** [comment]
Hmm, it might just be that sometimes there's a lag when clicking the
button. It might've just been slow going to the next lesson verses
completely broken.

**Comment by benschenker** [comment]
Ok, that functionality has been modified in the last few weeks so it may have been fixed.

I'll close this for now, but if you find that you can replicate this then reopen it.

**Comment by westonludeke** [comment]
Ok, sounds good!
