### ISSUE TITLE
Using conditional logic with if statements challenge doesn't remain passed

### ISSUE THREAD

**Issue by zersiax** [freeCodeCamp/freeCodeCamp#26243]
**Describe your problem and how to reproduce it:**
Try to complete the challenge. Submit the correct solution and click the button to take you to the next challenge.
Then, go back to the curriculum. Issue is still set to "Not passed".

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/use-conditional-logic-with-if-statements

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 69 
* Operating System:  Windows 10 1809

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by hijacker5** [comment]
![ccs1](https://user-images.githubusercontent.com/35338247/47314880-8fa59c80-d660-11e8-8be1-08e857cc7423.PNG)

Browser:Chrome
Browser Version: 69
Operating System:Windows 10 Pro

**Comment by hijacker5** [comment]
I didn't encountered any such issue. It shows passed.

**Comment by zersiax** [comment]
I'm not sure what to tell you ... I just did it three times in a row and it still says not passed here.

**Comment by RandellDawson** [comment]
@zersiax Can you provide some screenshots to show us the various screens as you complete the challenge?  That could help us identify what you are experiencing.

Thank you

**Comment by klassynihal** [comment]
![screenshot from 2018-10-29 02-23-00](https://user-images.githubusercontent.com/20780979/47621888-faa11880-db23-11e8-918d-a1771ec9880c.png)
done

**Comment by moT01** [comment]
Is this still a problem @zersiax?
