### ISSUE TITLE
'Iterate With While Loops' Typo 

### ISSUE THREAD

**Issue by bigwinters** [FreeCodeCamp/FreeCodeCamp#2626]
Challenge http://www.freecodecamp.com/challenges/waypoint-iterate-with-javascript-while-loops has an issue. 

In the sidebar, beneath the code, it says: "Let's try getting a __for loop__  to work by pushing values to an array." when I believe it should say __while loop__.

**Comment by Daeke** [comment]
Looks like this got fixed here:
#2505
