### ISSUE TITLE
redundancy

### ISSUE THREAD

**Issue by duanwalker** [FreeCodeCamp/FreeCodeCamp#2628]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

not sure if this is a bug or typo but the 2 challenge tasks are repeated here.

**Comment by benschenker** [comment]
Hey @duanwalker thanks for posting!

I don't see this issue.  I'm going to close this now but feel free to reopen if you still notice it and provide some screenshots.
