### ISSUE TITLE
Create Booststrap Wells: Confusing Instructions

### ISSUE THREAD

**Issue by MtRtMk** [FreeCodeCamp/FreeCodeCamp#2629]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-bootstrap-wells has an issue. 

I can pass the waypoint by nesting a div element (each) with "well" class within both of the already existing "col-xs-6" div elements. This is what we are instructed to do in the two paragraphs above the "Go to my next challenge".

But the instructions with the checkmarks below the "Go to my next challenge" button seem to be confusing and contradictory.  These instructions seem to be asking for nesting the col-xs-6 elements within a "well" div element. Something seems off.

When I nested the first div "well" element within the first "col-xs-6" element, the first checkmark went green. When I nested the second "well" div element within the other "col-xs-6" element, the second checkmark went green and I passed the waypoint. It's just that the instructions seem confusing.

**Comment by kettultim** [comment]
(not being rude, just trying to clarify) - I don't see what's confusing about the wording on this waypoint - could you perhaps offer a suggestion for a change @MtRtMk?

**Comment by MtRtMk** [comment]
The issue has been fixed. The current wording is fine. 

Earlier, the wording was incorrect. That earlier confusing & contradictory wording can be seen in eabedrapo's screenshot. https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2438

The issue was reported in earlier threads by other students. This was my first time here, so I didn't search if the issue had been reported already. I was directed here by the "Bug" button in the waypoint. 

I will close this thread as the issue has already been resolved.
