### ISSUE TITLE
Incorrect Exercise Instructions for "shift()"

### ISSUE THREAD

**Issue by rsavage-urquad** [FreeCodeCamp/FreeCodeCamp#2630]
Exercise instruction states:

'myArray should only have the first two values left(["John", 23])')

However correct answer should be:

myArray = [23, ["dog", 3]] 

Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-shift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![2015-08-24_15-12-04](https://cloud.githubusercontent.com/assets/7781587/9449827/22b076ee-4a73-11e5-8b4f-35363c9da8fb.png)

**Comment by rsavage-urquad** [comment]
Side Note - The "asserts" statements are interesting, however I feel that obscure the exercise's goal.  Perhaps a hover or popover would be a better choice?

**Comment by benschenker** [comment]
Looks like this has been fixed.  If you want to discuss the asserts more, gitter may be a better place for that discussion
