### ISSUE TITLE
Waypoint: Use Bracket Notation to Find the NthtoLast Character in a String | Wrong Question

### ISSUE THREAD

**Issue by ahayder** [FreeCodeCamp/FreeCodeCamp#2631]
Challenge http://freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-nthtolast-character-in-a-string has an issue.
Here the question is wrong. The question asks for the last charecter of the "lastName" variable but it should be the 2nd-to-last.

**Comment by bugron** [comment]
@ahayder thanks for posting this issue!
@BerkeleyTrue seems this issue is solved and can be closed, thanks.

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
