### ISSUE TITLE
I can't seem to repeat it

### ISSUE THREAD

**Issue by georgiel** [FreeCodeCamp/FreeCodeCamp#2632]
Challenge http://freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
Challenge http://freecodecamp.com/challenges/waypoint-add-images-to-your-website has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I can't seem to repeat it when go back to the page but when I did the usual ctrl+enter, a zipline (TICTACTOE) loaded up which should apparently be far further down the track.

**Comment by benschenker** [comment]
Hey @georgiel thanks for reporting this!

We had a bunch of these issues a couple of weeks ago but they all seem to have been fixed.  If you find that you can replicate it please reopen this issue.
