### ISSUE TITLE
discrepancy in selector item

### ISSUE THREAD

**Issue by duanwalker** [FreeCodeCamp/FreeCodeCamp#2634]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

challenge says to make the "left-well" element red but only allows user to advance if you make the target1 element red.

![image](https://cloud.githubusercontent.com/assets/7536426/9451265/a856cf5c-4a7b-11e5-9130-c6b343001d58.png)

**Comment by bugron** [comment]
@duanwalker thanks for posting this issue!
If you still need help with this see my [comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2877#issuecomment-136131970).
@BerkeleyTrue this issue can be closed, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
