### ISSUE TITLE
Typo in description ("use" word duplicated in first line)

### ISSUE THREAD

**Issue by kanadgodse** [FreeCodeCamp/FreeCodeCamp#2636]
Challenge http://freecodecamp.com/challenges/waypoint-use-spans-for-inline-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

First line of the challenge has a typo where the word "use" comes twice:
*You can use use spans to create inline elements.*

**Comment by srodman7689** [comment]
I have created a pull request that should close this issue. I can't merge it in myself though so we will have to wait until someone with write access to this repository can approve the pull request. Then this issue will be fixed in staging.
