### ISSUE TITLE
Placeholder attribute issue

### ISSUE THREAD

**Issue by eionut** [FreeCodeCamp/FreeCodeCamp#2639]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-placeholder-text-to-a-text-field has an issue. 
I think I wrote the correct code, but I keep recive this error: _Set the value of your placeholder attribute to "cat photo URL"._
![add placeholder text to a text field](https://cloud.githubusercontent.com/assets/12986499/9454643/416e5390-4acc-11e5-9c6b-a0307c3f0f02.png)

**Comment by Shufeng01** [comment]
You do not need to create a new input; just add the placeholder attribute to the existing one.

**Comment by eionut** [comment]
Thank you!

**Comment by frichardben** [comment]
thanks
