### ISSUE TITLE
Issue with basic javascript waypoint 39

### ISSUE THREAD

**Issue by j-farkas** [FreeCodeCamp/FreeCodeCamp#2640]
Challenge http://freecodecamp.com/challengeswaypoint-bring-your-javascript-slot-machine-to-life has an issue. 

While beginning to type in the code, I typed the line "$($)" in. The page now constantly crashes and no longer allows me to edit or reset it.

**Comment by suhussai** [comment]
I tried running "$($)" in JSFiddle and in TutorialsPoint's online JQuery compiler and noticed a similar response. It doesn't seem to be an issue with the waypoint itself. From (trying to) debug the issue, It seems that "$($)" causes JQuery to malfunction and causing the browser to hang, seems to be some sort of an infinite loop.
 
Setting up a delay between the user writing code and the browser verifying/executing it might be worth a shot, as it would give the user a chance to complete writing the necessary JQuery code.

**Comment by pathyl** [comment]
Using the noscript extension in firefox allowed me to load the page without freezing. I could then allow javascript and quickly use the clear code button. I had to complete the challenge in firefox however, because loading the page in chrome would bring up the old code containing the "$($)".

**Comment by benschenker** [comment]
Closing as fixed.  Loop detection was added.  Reopen if this is still an issue for you.
