### ISSUE TITLE
Unclear directions

### ISSUE THREAD

**Issue by jeffvk** [FreeCodeCamp/FreeCodeCamp#2641]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Directions are unclear. Top asks one thing, bottom asks another.
Placement of the "well" class is unclear. Placement of col-xs-6 is unclear.

**Comment by benschenker** [comment]
Hey @jeffvk thanks for posting this!

It looks like this has been fixed recently.  Feel free to reopen this if you still have issues with it.
