### ISSUE TITLE
Wrong html preloaded in "Waypoint: Remove Classes from an element with jQuery"?

### ISSUE THREAD

**Issue by nickbarry** [FreeCodeCamp/FreeCodeCamp#2642]
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I think this waypoint has the wrong preloaded html. I believe it should have the html that results from completing the previous waypoint ( http://www.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors ), and not from two or three waypoints back. 

<img width="432" alt="wrong html" src="https://cloud.githubusercontent.com/assets/8515899/9455363/6b3101d4-4a7f-11e5-9cb7-a12f5cef89f2.png">

This might also solve some of the other bugs recorded for this waypoint, for example:
* https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2627
* https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1898

**Comment by nickbarry** [comment]
I'm guessing that the wrong html is preloaded, because of this waypoint...
http://www.freecodecamp.com/challenges/waypoint-delete-your-jquery-functions

...which has us delete several functions, which show up in subsequent Waypoints, including "Waypoint: Remove Classes from an element with jQuery", but also including the following Waypoint ( http://www.freecodecamp.com/challenges/waypoint-change-the-css-of-an-element-using-jquery ), and perhaps more - I haven't checked yet.

**Comment by benschenker** [comment]
Hey @nickbarry thanks for posting this!

I am not sure I understand the issue with this challenge.  It seems to be working/looking fine for me, it may have been fixed recently.  Feel free to reopen this issue if you still experience the problems stated here

**Comment by mmdock** [comment]
No one seems to have cared about this for over a year, but I feel like I should bring this back up.
@benschenker I feel like I have to agree with @nickbarry on this.  I was genuinely confused for a moment as two waypoints has you delete those three addclass function calls, then the waypoint prior has you add a different three addclass function calls.  They exist for a few more waypoints until the waypoint after you call the css function to make the text red, then suddenly they are gone again, with only the css function remaining.  Why even have a waypoint specifically delete them, only to bring them back, and then suddenly remove them a few wavepoints down again?  It seems really inconsistent to me.  Not that it really matters in the long run but still consistency is key.
