### ISSUE TITLE
Several Waypoints with extraneous success criterion

### ISSUE THREAD

**Issue by nickbarry** [FreeCodeCamp/FreeCodeCamp#2643]
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This and several other waypoints have this success criterion, which I believe is irrelevant:
"Only use jQuery to add these classes to the element."

Here are a few waypoints that include this criterion. I haven't checked to see if this list is exhaustive:
* http://www.freecodecamp.com/challenges/waypoint-remove-an-element-using-jquery
* http://www.freecodecamp.com/challenges/waypoint-change-the-css-of-an-element-using-jquery
* http://www.freecodecamp.com/challenges/waypoint-disable-an-element-using-jquery

**Comment by benmcmahon100** [comment]
It is necessary to make sure people don't just go ahead and add class = "something" so as to paddy the tests
