### ISSUE TITLE
Waypoint: Manipulate Arrays With unshift  |   error message d[0].toLowerCase is not a function

### ISSUE THREAD

**Issue by basiccreation** [FreeCodeCamp/FreeCodeCamp#2644]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I entered myArray.unshift(["Paul"]);
the error message d[0].toLowerCase is not a function

![unshift](https://cloud.githubusercontent.com/assets/12203531/9456073/cc6dc8b2-4a87-11e5-90b1-18fe034d5a3d.jpg)

Thanks

**Comment by AryanJ-NYC** [comment]
You're adding an array that has the string element "Paul."  The exercise is not asking you to add an array; it's asking you to add a string element.

**Comment by basiccreation** [comment]
thanks for getting back to me. I thought I'd tried to add the string and it
didn't accept it. Oh well. it's all good.

**Comment by bugron** [comment]
@basiccreation thanks for posting this issue!
Closing this issue as the problem if solved.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
