### ISSUE TITLE
Poorly written exercise with no useful information

### ISSUE THREAD

**Issue by mlswartz** [FreeCodeCamp/FreeCodeCamp#2645]
for exercise: http://www.freecodecamp.com/challenges/waypoint-declare-javascript-variables

This is a poorly written exercise that gives absolutely no indication as to how the objective is to be achieved. And the grayed out code only adds confusion to those that are new to coding. So how about making the exercising right and informative before posting them?

**Comment by QuincyLarson** [comment]
Sure, we can work on the wording on this challenge.

**Comment by AryanJ-NYC** [comment]
Any suggestions for text, @mlswartz?
