### ISSUE TITLE
Clicking back in browser to view previous exercise, then clicking 'Go to next challenge' skips ahead to the following exercise

### ISSUE THREAD

**Issue by rharmaning** [FreeCodeCamp/FreeCodeCamp#2648]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-text-field has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

1. Complete 'alt text' exercise
2. Proceed to 'Unordered List Exercise', get stuck, click back-button
3. Reset 'alt text' exercise, complete successfully, click continue

expected: 'Unordered' List exercise presented again

actual: 'Ordered' List exercise presented

**Comment by benschenker** [comment]
Thanks @rharmaning for the specific replication instructions!

Confirmed! I'll note the link to the alt text challenge is: http://www.freecodecamp.com/challenges/waypoint-add-alt-text-to-an-image-for-accessibility

**Comment by benschenker** [comment]
It looks like this is fixed, thanks!
