### ISSUE TITLE
Bug "$($)"

### ISSUE THREAD

**Issue by kennywg700** [FreeCodeCamp/FreeCodeCamp#2649]
Challenge http://freecodecamp.com/challenges/waypoint-use-appendto-to-move-elements-with-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

If you type "$($)" without the quotations into any of the jQuery practices, the page freezes up. There is no way to reset the code because the page freezes up whenever you return to the page.

**Comment by benmcmahon100** [comment]
You can clear your browsers storage to get around this issue and instead of writing it out you can copy and paste the code or write it up with the brackets first. I have built a new version of the testing system that fixes this. Sorry about the inconvenience this causes.
