### ISSUE TITLE
"Your image should be 100 pixels wide"  error

### ISSUE THREAD

**Issue by alyzeia** [FreeCodeCamp/FreeCodeCamp#2651]
Help!
I've entered the necessary code but I still can't pass task 17.

"Your image should be 100 pixels wide" is still crossed out even though the preview image is smaller. 

![image](https://cloud.githubusercontent.com/assets/13956156/9458154/aafda40e-4b1d-11e5-8b43-7dee06fce215.png)

**Comment by bugron** [comment]
@alyzeia thanks for posting this issue!
I've just passed test with you code.

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
