### ISSUE TITLE
Add language support for French

### ISSUE THREAD

**Issue by ashwoodall** [freeCodeCamp/freeCodeCamp#26529]
There are many campers whose native language is French, and it would be great to see this enhancement on the product roadmap. Additionally, as a developer who is learning French, it would be immensely helpful to see how common web development topics are described and discussed in French.

**Comment by konpyuta** [comment]
Is there currently a process for translation? J'ai étudié un peu, so I'd love to help contribute, however I'm not fluent enough to translate whole pages.

**Comment by ezioda004** [comment]
Hi @ashwoodall and @konpyuta,

Thank you both for showing interest in translation.
Please continue further discussion in this thread https://github.com/freeCodeCamp/freeCodeCamp/issues/18966

Thank you.
