### ISSUE TITLE
Confusing example in Challenge

### ISSUE THREAD

**Issue by MarkHargrove** [FreeCodeCamp/FreeCodeCamp#2653]
Challenge http://freecodecamp.com/challenges/waypoint-center-text-with-bootstrap has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The example for this waypoint is shown as

`<h2 class="text-red text-center">your text</h2>`

...which is a perfectly fine example, but could be very confusing to true beginner because all previous exercises have a class named 'red-text' (instead of 'text-red').  Since we don't actually define the class 'text-center' (it's apparently defined by Bootstrap for us) but using it "just works", a beginner might be misled into thinking "text-red" should also "just work" (but, of course, it doesn't).

The instruction makes the point that you can list multiple classes for an element, but doesn't say anything about how you're supposed to know what classes are "magically" available via Bootstrap and which have to be defined by the developer.  Choosing an example that has one of each with a naming convention that fools you into thinking that "text-red" might be like "text-center" was momentarily confusing even to me (and I'm moderately experienced with CSS)

**Comment by AryanJ-NYC** [comment]
Merge #2570 took care of this problem. You should see this fix live in the near future.
