### ISSUE TITLE
Misleading example

### ISSUE THREAD

**Issue by MarkHargrove** [FreeCodeCamp/FreeCodeCamp#2654]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-block-element-bootstrap-button has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The example image shows:

![image](https://cloud.githubusercontent.com/assets/8140724/9458575/02fb7d14-4aad-11e5-9045-0d7b5332ce17.png)

What appears to be the block-level button elements class name is depicted as **.btn.btn-block**  (note the period between 'btn' and 'btn-block'.  Attempting to use this class name for the element fails -- the correct class markup is **class = "btn btn-block"** (with a space between btn and btn-block).  The example is going to frustrate some beginners.

**Comment by bugron** [comment]
@MarkHargrove thanks for posting this issue!
You are absolutely right! And there is no any conflict! The dots in ```.btn.btn-block``` mean this is a CSS selector.
In HTML you add ```class="btn btn-block"``` attribute to you element(s) (in this case a button) so now it has **both** classes ```btn``` and ```btn-block```. CSS selecor ```.btn.btn-block``` points to a button(s) which has **both** classes ```btn``` and ```btn-block```.

Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).

**Comment by BerkeleyTrue** [comment]
@bugron Is correct. That is the proper way to display multi class selector.


Happy Coding!

**Comment by MarkHargrove** [comment]
I'm not disputing that the class selector is DEFINED correctly.  I'm just noting that a beginner who looks at the example and thinks that 'btn.btn-block' can be used in a "class" markup is going to be surprised that it doesn't work.   I don't recall any previous explanation in an earlier waypoint that shows that the way some selectors are defined doesn't have to exactly matched the way they are invoked.

If I'm the only one to ever mention this, though, maybe there is no such confusion  :-)

**Comment by wundertunge** [comment]
Yeah, this confused me at first, too. It didn't take long to figure it out. Then again, I'm not a total beginner. Also of note, having the class="btn btn-block" vs. "btn-block" does make it appear different.
