### ISSUE TITLE
Browser crashes when typing $($(

### ISSUE THREAD

**Issue by suzerice** [FreeCodeCamp/FreeCodeCamp#2655]
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Okay typing $($( into the code editor crashes it. The tab hangs; I can't click any of the buttons in the left sidebar like reset, and I can't type any more into the code editor.

There were three other people in the chat with the same problem, so it's not just me. I'm using the latest Opera on Mac OSX; one of them said she was using Chrome and the other said he was using Firefox. So it's everyone and every browser!

The fix that worked for all of us was to clear the browser cache and reload the page, and then copy and paste the 

And we are all afraid to try typing it in any of the other lessons and are just copy/pasting it from here on out. So in my screenshot it's there because I copied and pasted it over three times, but actually when I typed the very first $($( at the top it froze.

![screen shot 2015-08-25 at 12 22 45 am](https://cloud.githubusercontent.com/assets/13206606/9458730/2306da6e-4ac0-11e5-82e0-cf2c3dd648da.png)

**Comment by suzerice** [comment]
Update: I tried it on another one. The next (and last) thing in Javascript, 40. Waypoint: Give your JavaScript Slot Machine some stylish images, you can type in the $($( syntax there are it works fine. So it's only 39 that's broken as far as I can see.

**Comment by bugron** [comment]
@suzerice thanks for posting this issue!
Take a look to [Refresh Your Browser Cache](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache) wiki page.

Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2640


Please see [Help I've Found a Bug](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I%27ve-Found-a-Bug).
