### ISSUE TITLE
'Go to my next challenge' link sometimes needs to be clicked twice

### ISSUE THREAD

**Issue by neeraj08** [FreeCodeCamp/FreeCodeCamp#2659]
At least in part 4-'Basic JavaScript' & 5-'Basic Algorithm Scripting'
sometimes when I have solved an 'unsolved' correctly the dialog pops up saying 'Go to my next challenge'
I click/(ctrl+enter) it. Sometimes that takes me to my next challenge as expected but other times I just wait for 10 secs and nothing happens. So I do ctrl+enter again and the dialog pops up again. The second time it always works and takes me to my next challenge.

Before that I solved whole of part 2-'Responsive Design with Bootstrap' and this problem wasn't there.
Also, this issue seems not to occur with pre-solved problems.
<img width="1680" alt="screen shot 2015-08-25 at 11 33 34 am" src="https://cloud.githubusercontent.com/assets/5960743/9459796/2485b1c8-4b1d-11e5-9a7b-66bc6b50444f.png">

**Comment by warkentien2** [comment]
Was gonna post same issue.

**Comment by BerkeleyTrue** [comment]
We will be tracking this issue at #2772 


Happy Coding!
