### ISSUE TITLE
Delete button not rendered properly

### ISSUE THREAD

**Issue by sravin** [FreeCodeCamp/FreeCodeCamp#2662]
![screen shot 2015-08-25 at 2 30 04 pm](https://cloud.githubusercontent.com/assets/8336693/9462816/df6db040-4b35-11e5-9244-a5d46fa30718.png)

Challenge http://freecodecamp.com/challenges/waypoint-style-text-inputs-as-form-controls has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by Rollascriptings** [comment]
<input type="text" placeholder="cat photo URL" required class="form-control">
    <button type="submit" class="btn btn-primary"><i class="fa fa-paper-plane">Submit</i></button>

**Comment by Rollascriptings** [comment]
![form](https://cloud.githubusercontent.com/assets/13922667/9465444/870f414a-4b24-11e5-891f-d5a9d3cd15b6.png)

I hope this is well understood? If there is any other way I can help please let me know.

**Comment by BerkeleyTrue** [comment]
@sravin Does that fix your issue?
