### ISSUE TITLE
Does not recognize second image with said src attribute

### ISSUE THREAD

**Issue by wohfab** [FreeCodeCamp/FreeCodeCamp#2663]
![screenshot](https://cloud.githubusercontent.com/assets/4539234/9463255/c2d23d4e-4b1b-11e5-8467-e78496c5cca8.png)
Challenge http://freecodecamp.com/challenges/waypoint-make-images-mobile-responsive has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by Mansuro** [comment]
You have to add both the class and src for the challenge to work. I don't know if they should be related though

**Comment by georgiel** [comment]
@Mansuro 
well of course they should be, this step is to introduce bootstrap classes, the class makes the image scale to the width of device.

**Comment by bugron** [comment]
@wohfab thanks for posting this issue!

This is from challenge description.
>It would be great if this image could be exactly the width of our phone's screen.
>Fortunately, with Bootstrap, all we need to do is add the img-responsive class to your image. Do this, and the image should perfectly fit the width of your page.

And this is from tests' section 
>Your new image should have the class `img-responsive`.
>Add a second image with the src of http://bit.ly/fcc-running-cats.

So you definitely need to add both `class` and `src` attributes to your new image.

@BerkeleyTrue I think this issue can be closed, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
