### ISSUE TITLE
http://www.freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery

### ISSUE THREAD

**Issue by mmmjkerouac** [FreeCodeCamp/FreeCodeCamp#2664]
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I accidentally typed $($) and it crashes my computer if I'm on the page so I can't produce a screenshot.

**Comment by LynneSS** [comment]
I had a similar problem on the page before this, http://www.freecodecamp.com/challenges/waypoint-change-the-css-of-an-element-using-jquery.

I accidentally typed $($) and the window became unresponsive, though other browser windows were still responsive. I tried reloading (command-R), quitting & re-opening the page, and emptying caches, and now the console is blank as well as unresponsive (see attached image).
<img width="1440" alt="screen shot 2015-08-25 at 8 19 09 am" src="https://cloud.githubusercontent.com/assets/13277131/9467718/405560e8-4b03-11e5-99d7-784570077b03.png">

**Comment by bugron** [comment]
@mmmjkerouac thanks for posting this issue!
See @benmcmahon100's [comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2649#event-391484202).
Also try to [Refresh Your Browser Cache](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache) and [Clear Your Browser's Local Storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser%27s-Local-Storage).


Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by LynneSS** [comment]
Thanks for the help.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Fix is on the way

**Comment by revathynair** [comment]
![2](https://cloud.githubusercontent.com/assets/13557418/10392736/7c4908bc-6ea7-11e5-9f0c-e3fa27e7ae39.JPG)

I cannot seem to find a solution to this issue.
I've tried deleting local cache, tried using separately and together the required elements but no result.
