### ISSUE TITLE
Site won't check off completed lesson steps

### ISSUE THREAD

**Issue by direclown** [FreeCodeCamp/FreeCodeCamp#2666]
Challenge http://freecodecamp.com/challenges/waypoint-style-text-inputs-as-form-controls has an issue.  Hey guys!  As far as I know, I followed all of the steps to complete this lesson. However, the site wasn't "checking off" each time I completed one of the steps, and I can't officially complete the lesson unless it does. 

For example, I did step 1, "Give the submit button in your form the classes btn btn-primary," and I also added the paper plane icon, but the site wouldn't say it was done.  I did show this to some other campers, and they couldn't figure out what the problem was either.  Is there something I'm doing wrong, or is this a true site bug? 

Thanks for your help,
Eric
![freecodecamp bug](https://cloud.githubusercontent.com/assets/13476456/9466466/139cc096-4b03-11e5-8cc1-cc295d051b08.png)
![freecodecamp bug2](https://cloud.githubusercontent.com/assets/13476456/9466461/0d16b0ba-4b03-11e5-85ba-1953b3593b01.png)

**Comment by bugron** [comment]
@direclown thanks for posting this issue!
Try to [Refresh Your Browser Cache](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache) and [Clear Your Browser's Local Storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser%27s-Local-Storage).

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by benschenker** [comment]
Hey @direclown are you still experiencing this issue?

**Comment by direclown** [comment]
Actually, no.  What I thought was an issue was actually part of the
redesign you guys did recently.  I wasn't used to using the "Run Code"
button, so that's why I thought there was some kind of error.  But thank
you for checking up on it, anyway!

On Sun, Sep 6, 2015 at 2:03 AM, Ben Schenker <notifications@github.com>
wrote:

> Hey @direclown <https://github.com/direclown> are you still experiencing
> this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2666#issuecomment-138043995>
> .
>



-- 
Eric Pudalov

Eric Pudalov
Printing Clerk at Georgia Community Support and Solutions
<http://www.gacommunity.org>
Freelance Writer and Editor
Eric Pudalov on The Yahoo! Contributor Network
<http://contributor.yahoo.com/user/192177/eric_pudalov.html>
<http://contributor.yahoo.com/user/192177/eric_pudalov.html>Eric Pudalov:
Atlanta Events Examiner
<http://www.examiner.com/events-in-atlanta/eric-pudalov>
Eric Pudalov (Direclown) on WordPress <http://direclown.wordpress.com>

**Comment by bugron** [comment]
@direclown thanks for your reply. Seems your problem is solved so I'm closing this issue. Feel free to reopen if you still experience problems, thanks.
