### ISSUE TITLE
Bootstrap Waypoint Completion

### ISSUE THREAD

**Issue by carefreetoast4** [FreeCodeCamp/FreeCodeCamp#2668]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-bootstrap-headline has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Despite having entered an incorrect solution during the Waypoint lesson I am still able to click the "Go to my next challenge button" which then takes me to the next challenge and shows the correct code for the previous lesson. This was repeatable for as many Waypoints as I tried.

**Comment by bugron** [comment]
@smarshy thanks for posting this issue!
Try to [Refresh Your Browser Cache](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache) and [Clear Your Browser's Local Storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser%27s-Local-Storage).

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by benschenker** [comment]
Closing as stale, please reopen if this is still an issue for you.
