### ISSUE TITLE
$(".well:nth-child(2)").addClass("animated bounce") doesn't work

### ISSUE THREAD

**Issue by husamp** [FreeCodeCamp/FreeCodeCamp#2669]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue. 

I add $(".well:nth-child(2)").addClass("animated bounce"); code into document.ready in jQuery. Buttons bounce, but the challenge is not considered completed.

**Comment by husamp** [comment]
I've understood my mistake :-) Closing the issue.

**Comment by Destinydemo** [comment]
@husamp: Could you tell me how you resolve this  problem?
I tried  $("#left-well:nth-child(2)").addClass("animated bounce"); but it still not work.

**Comment by Joebbrien** [comment]
am stuck at that same point mind sharing the solution
