### ISSUE TITLE
Waypoint: Create a Bulleted Unordered List no recognizing the closing </li> element

### ISSUE THREAD

**Issue by eggtimer** [FreeCodeCamp/FreeCodeCamp#2670]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Just work through the exercise and at the end the last requirement (Make sure your li element has a closing tag) even when all 3 are closed out. I actually got this to then work only after removing the "class="red-text"" from the tags that had been <p>, and that the lesson had wanted changed from <p> to Unordered lists. The thing is that the instructions did explicitly ask that this class reference be removed, yet the lesson completion criteria included this.

**Comment by benschenker** [comment]
Hey @eggtimer, thanks for posting this issue!

Can you post some code/screenshots so we can try to replicate this?

Take a look at our [How to Create a Github Issue](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue) wiki page for some tips
