### ISSUE TITLE
Generate random whole numbers challenge not evaluating

### ISSUE THREAD

**Issue by jamesagwa** [FreeCodeCamp/FreeCodeCamp#2671]
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-within-a-range has an issue. 

I ran this Code, which i believe its correct, but the editor is not evaluating it::
![fccrandomnumerror](https://cloud.githubusercontent.com/assets/11221356/9467998/27a75fea-4b37-11e5-9886-fbdcc7a71878.jpg)

```
function myFunction() {
  // Make myFunction return a random number between zero and nine instead of a decimal
  // Only change code below this line.

  return Math.floor(Math.random() * (9 - 0 + 1)) + 0;
}
```

**Comment by bugron** [comment]
@jamesagwa thanks for posting this issue!
I guess you didn't pass third test? Yes your code is definitely correct. But you can see your test's ```assert``` function contents and according to those you **have** to use ```min``` and ```max``` variables minimum twice. This is the situation when the JavaScript instructions for processing challenge can help you to solve the challenge. (check [Waypoint: Comment your JavaScript Code](http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code) - the last paragraph of the challenge description clarifies this.)


Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
