### ISSUE TITLE
passes even if instructions not followed

### ISSUE THREAD

**Issue by smarshy** [FreeCodeCamp/FreeCodeCamp#2673]
Challenge http://freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

instruction mentions rest of paragraph text to be plain
correct  :   `<p>click here for <a href="http://www.catphotoapp.com">cat photos</a></p>`

However,this works as well:
`<p><a href="http://www.catphotoapp.com">click here for cat photos</a></p>`

**Comment by benschenker** [comment]
Hey @smarshy thanks for posting this!

Confirmed!
