### ISSUE TITLE
Waypoint: Comment your JavaScript Code, 2nd test bug

### ISSUE THREAD

**Issue by matszym** [FreeCodeCamp/FreeCodeCamp#2674]
Challenge http://www.freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Second test doesnt account for multi line comments. Becouse of that, this, valid comment:

/*
This is mutiline comment
*/

Doesnt pass the test.

**Comment by erictleung** [comment]
I can't reproduce that error. Maybe this was fixed since this issue was made. I'm running on Chrome on a Windows machine, if that makes any difference.

![capture](https://cloud.githubusercontent.com/assets/2754821/11412742/3deed836-9395-11e5-939a-a08259fe9fb2.PNG)

**Comment by ltegman** [comment]
Thanks for looking into this @erictleung. I confirm the same thing as well. Must have been fixed since this bug was filed!
