### ISSUE TITLE
Button text not checked

### ISSUE THREAD

**Issue by smarshy** [FreeCodeCamp/FreeCodeCamp#2675]
Challenge http://freecodecamp.com/challenges/waypoint-add-a-submit-button-to-a-form has an issue. 
Specified:Your submit button should have the text "submit"

edit:check for this
<button type="submit">this button submits the form</button>

it is checking for substring 'submit' probably

**Comment by bugron** [comment]
@smarshy thanks for posting this issue!
I've just tried ```<button type="submit">hello</button>``` and didn't pass the test.

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by BerkeleyTrue** [comment]
@smarshy What exactly is the issue you are having?

**Comment by bugron** [comment]
@smarshy ```<button type="submit">this button submits the form</button>``` passed the test. Test description says that "Your submit button should have the text "submit"." so it doesn't say **exactly** or I'm wrong? Notice that I'm not a native English speaker so I can simply mix up the meaning of word "should". Thanks.

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by BerkeleyTrue** [comment]
The test is lenient. It only test for the existence of `submit` in the text of the button and the test text does not specify that it should only be `submit`. Not sure if this is an issue. Does this confuse users?
