### ISSUE TITLE
Colours Section is far too big. 

### ISSUE THREAD

**Issue by georgiel** [FreeCodeCamp/FreeCodeCamp#2681]
Challenge http://freecodecamp.com/challenges/waypoint-use-rgb-to-color-elements-green has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I don't need to repeat the same task six times with slightly different colours, simpler option is far better. Once for each colour type and mention the cheat sheet for colour values. http://www.pagetutor.com/common/bgcolors1536.html http://www.zoology.ubc.ca/~alathea/howto_html/colorchart.png
http://www.visibone.com/color/hexagon_800.gif

and mention that there are tiny utilities which do colour picking.

**Comment by BerkeleyTrue** [comment]
Hello @georgiel 

You can always skip challenges you find repetitive. While it may seem arbitrary and annoying for some, we want to make sure all Campers understand the various ways colors are made in html/css and the only sure fire way to do that is through repetition.

Happy Coding!

**Comment by georgiel** [comment]
It seems that way to a great many, there's not a lot to understand.

Kind Regards

George W Langham
