### ISSUE TITLE
Waypoint: Line up Form Elements Responsively with Bootstrap

### ISSUE THREAD

**Issue by psykobilliethekid** [FreeCodeCamp/FreeCodeCamp#2682]
Challenge http://freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap has an issue. 

Working on completing this challenge, and I noticed the third bullet showing the submit button should be nested in a div with .col-xs-5 was not being completed. But the next challenge button is highlighted as if the challenge is complete. 

![bootstrap-error](https://cloud.githubusercontent.com/assets/4343088/9477075/4c99b346-4b3e-11e5-8c1c-aea691556adf.png)

**Comment by benschenker** [comment]
Hey @psykobilliethekid thanks for posting!

Is this still an issue for you?

Have you tried doing a [Hard Refresh](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache)?

**Comment by psykobilliethekid** [comment]
Hi @benschenker! Sorry for the late reply - dealing with bad allergies and a broken foot. (Welcome to my life...) I just checked the issue and it's resolved. Thanks for getting back to me! :)

**Comment by benschenker** [comment]
No problem!
