### ISSUE TITLE
Basic JavaScript Waypoint 39 freezes up.

### ISSUE THREAD

**Issue by Jonboy1138** [FreeCodeCamp/FreeCodeCamp#2683]
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life freezes up when trying to enter code. I had started entering my code and got $($) entered when I could no longer enter anything. I also cannot reset my code or anything. I have to kill the page and get back in. If I try to go back to that page it freezes up again during loading.

**Comment by Jonboy1138** [comment]
I am closing this issue as it is the same as issue #2640.

**Comment by BerkeleyTrue** [comment]
Hello @Jonboy1138 

This is a duplicate. Also, we have a fix on the way.

In the meantime, try [clearing your localStorage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser's-Local-Storage) or alternatively if you know the name of the challenge that is freezing you can just delete that single challenge from localStorage.

Let me know if that works.

Happy Coding!

**Comment by BerkeleyTrue** [comment]
You beat me to it ;)
