### ISSUE TITLE
confusing logic..

### ISSUE THREAD

**Issue by samscripts** [FreeCodeCamp/FreeCodeCamp#2684]
Challenge http://www.freecodecamp.com/challenges/bonfire-everything-be-true has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Hi the 2nd and 3rd assert will test always 'false' using Object.hasOwnProperty() since {'sex': 'female'} is not just a property name but an object. Or either the question or assert should be formulated in a way to require the usage of Object.getOwnPropertyNames() in case the pre is an object like {'sex': 'female'}.

**Comment by benschenker** [comment]
Thanks @samscripts for catching that!

I agree, tests 2 and 3 add very little.  We should probably be testing for a real negative result instead like:
```
every([
    {'user': 'Tinky-Winky', 'sex': 'male'},
    {'user': 'Dipsy', 'sex': 'male'},
    {'user': 'Laa-Laa', 'sex': 'female'},
    {'user': 'Po'}
], 'sex')
```
That should return false on account of `Po`.

**Comment by BerkeleyTrue** [comment]
Lets keep the discussion in #3394 

Happy Coding!
