### ISSUE TITLE
Need to add implementation for counting sort in Swift

### ISSUE THREAD

**Issue by thumpshere** [freeCodeCamp/freeCodeCamp#26859]
**Describe your problem and how to reproduce it:**
demonstration of counting sort is available but the implementation in specific languages is missing.

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/algorithms/sorting-algorithms/counting-sort/index.md

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@thumpshere Would you be interested in helping create such a solution for the Guide article?

Would anyone like to contribute a counting sort solution for Swift?

**Comment by DMZ011** [comment]
@RandellDawson @cmccormack I'll take this one

**Comment by nellybaz** [comment]
yes, I am interested

**Comment by RandellDawson** [comment]
@nellybaz Go for it.  It is all yours.

**Comment by Ayushjain9501** [comment]
Hi,
I have implemented it in Swift!
Can I make a pull request now?

**Comment by moT01** [comment]
Thanks for the issue and PR - we typically don't need to open issues or keep them open for guide article additions. For the most part, you can just make the changes you want. I am going to close this and the PR will be reviewed when someone gets to it. Thanks and happy coding!

**Comment by RandellDawson** [comment]
@moT01 I don't see the harm in leaving this open.  If after reviewing the PR we merge it, then it will close anyway.  Just my two cents worth.

**Comment by moT01** [comment]
merged
