### ISSUE TITLE
Waypoint shows as incomplete on mobile device

### ISSUE THREAD

**Issue by Philosophist** [FreeCodeCamp/FreeCodeCamp#2685]
On Waypoint Create Bootstrap Wells, using Chrome on a Samsung Galaxy S5, after completion, the animation shows that I've completed, but the buttons don't work. then upon inspecting the Map page, it shows the exercise as not completed. Returning to the Waypoint from the Map shows my work save and it still completed AND the buttons still won't work.
![screenshot_2015-08-25-12-58-13](https://cloud.githubusercontent.com/assets/12451365/9478340/081ae666-4b2c-11e5-90ee-f47bab62c519.png)
![screenshot_2015-08-25-12-57-57](https://cloud.githubusercontent.com/assets/12451365/9478339/081acd8e-4b2c-11e5-96bf-c84fe7b275fa.png)

**Comment by benschenker** [comment]
Hey @Philosophist thanks for posting this!

This is very similar to #1103, but seems slightly different so I'll keep it open.  Keep an eye there for changes anyway.

**Comment by bugron** [comment]
@Philosophist is this still an issue for you?

**Comment by ltegman** [comment]
I can still repro this on a Galaxy S6 using the latest Chrome app.

**Comment by ltegman** [comment]
False alarm -- I forgot to login on my mobile device! This is solved :+1:
