### ISSUE TITLE
waypoint-style-the-html-body-element completed before correct code entered 

### ISSUE THREAD

**Issue by AEA2002** [FreeCodeCamp/FreeCodeCamp#2686]
Challenge http://www.freecodecamp.com/challenges/waypoint-style-the-html-body-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This waypoint was *completed* before correct code completely entered.
```
<style>
  body {
    background-color: black;
  
</style>
```

The closing bracket is missing.
Thank You

**Comment by benschenker** [comment]
Thanks @AEA2002 for pointing this out!

**Comment by AEA2002** [comment]
I tested this waypoint and the issue is not fixed:

![9](https://cloud.githubusercontent.com/assets/7269693/9978652/8bf254c2-5f0b-11e5-996a-f0cbe54cd045.png)
