### ISSUE TITLE
Translations of Brazilian Portuguese vs Portuguese

### ISSUE THREAD

**Issue by thefrontendwizard** [freeCodeCamp/freeCodeCamp#26862]
So, there is a confusion about wether the Portuguese should be the Brazilian Portuguese or the actual Portuguese spoken on Portugal. Both of them overlap a lot, but they still have a lot of differences. Currently some people are translating to Portuguese (#24311) and other are translating to Brazilian Portuguese (#26113). I believe there's a need for a separate translation for both of them. What do y'all think?

**Comment by diogocampos** [comment]
According to Wikipedia ([Portuguese language](https://en.wikipedia.org/wiki/Portuguese_language), [Brazilian Portuguese](https://en.wikipedia.org/wiki/Brazilian_Portuguese)), the vast majority (~90%) of the world's Portuguese speakers are in Brazil.

As a native speaker of Brazilian Portuguese, I think the situation is similar to the differences between UK English and US English, where the differences are small enough to not hinder comprehension between countries.

**Comment by thefrontendwizard** [comment]
Fair enough. I'll close the issue then.
