### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by suzyelbow** [FreeCodeCamp/FreeCodeCamp#2687]
Hi,

I can't login to my existing FreeCodeCamp account with my e-mail address, reset my password, or sign in via any social network. 

I've seen that other users have had this dilemma in the past (and noted the post saying that this issue has been fixed in the past week or two?), but this has been an ongoing issue for me, and has kept me from getting started. :[

Any ideas about what may be going on here? 

![screen shot 2015-08-25 at 1 36 51 pm](https://cloud.githubusercontent.com/assets/6876872/9479157/d0c6770c-4b30-11e5-8cfb-5508905d641e.png)

**Comment by BerkeleyTrue** [comment]
Hello @suzyelbow 

Apologies for the inconvenience. Can you PM on Gitter and I can go in and see whats going on when you sign in?

**Comment by BerkeleyTrue** [comment]
Fixed
