### ISSUE TITLE
Javascript Math tutorials not working in Chrome

### ISSUE THREAD

**Issue by ClarkGH** [FreeCodeCamp/FreeCodeCamp#2688]
Challenge http://beta.freecodecamp.com/challenges/waypoint-subtract-one-number-from-another-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The math problems do not work with google chrome, however they work just fine with safari/firefox.

Not working on Chrome
![screen shot 2015-08-25 at 2 01 09 pm](https://cloud.githubusercontent.com/assets/3911946/9479266/7dbb4adc-4b31-11e5-8e96-a0aa48c3a3bb.png)

Working on Safari
![screen shot 2015-08-25 at 2 01 20 pm](https://cloud.githubusercontent.com/assets/3911946/9479268/80a479da-4b31-11e5-801b-c0f4e6bef186.png)

**Comment by benmcmahon100** [comment]
Hey @ClarkGH this has been fixed just a few minutes ago! Also just as a heads up safari is incompatible with our test suite so it's likely to encounter issues

**Comment by BerkeleyTrue** [comment]
Closing. @ClarkGH Please feel free to re-open if the issue still persist.

Happy Coding!
