### ISSUE TITLE
Bonfire Challenges

### ISSUE THREAD

**Issue by yaskyj** [FreeCodeCamp/freecodecamp#269]
Bonfires show completely done, but not all points were accounted for. This could have stemmed from using Bonfires when it was first live and the bug at [#53](https://github.com/FreeCodeCamp/freecodecamp/issues/53) and fixed in [#55] (https://github.com/FreeCodeCamp/freecodecamp/pull/55).
I doubt this is a pervasive issue. It could just be isolated to me.

**Comment by QuincyLarson** [comment]
There's a good chance this is already fixed on our UX-improvement branch. There were a number of issues with our old point system that we've since remedied.
