### ISSUE TITLE
Directions not initially complete in .remove() exercise

### ISSUE THREAD

**Issue by loretod** [FreeCodeCamp/FreeCodeCamp#2692]
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When loading, there are no direction to remove the target. Only after you hit run do you get the instructions to .remove().
![screen shot 2015-08-25 at 5 56 12 pm](https://cloud.githubusercontent.com/assets/8517379/9480734/bc8ff3cc-4b52-11e5-8702-f0b166dd80ef.png)

**Comment by BerkeleyTrue** [comment]
Hello @loretod 

Thanks for pointing this out. The actual task needs to be in the description.
Anyone up for a PR?

**Comment by loretod** [comment]
Anytime! Having great fun and learning with the exercises… Thank you!

ld

**Comment by BerkeleyTrue** [comment]
cc @benmcmahon100

**Comment by BerkeleyTrue** [comment]
actually this is a bug. Auto-run is not working on some challenges....

**Comment by benmcmahon100** [comment]
Fixed in the latest commit! (I hope)

**Comment by BerkeleyTrue** [comment]
fixed!
