### ISSUE TITLE
Directions not complete for waypoint

### ISSUE THREAD

**Issue by psykobilliethekid** [FreeCodeCamp/FreeCodeCamp#2693]
Challenge http://freecodecamp.com/challenges/waypoint-remove-an-element-using-jquery has an issue.

Starts of the challenge showing the .remove() method, but does not tell you what to remove unless you run the code. 

Screen after attempt at running the code: 
![jquery-remove](https://cloud.githubusercontent.com/assets/4343088/9481160/f179f7c4-4b55-11e5-9185-5b7cb41fcf4b.png)

**Comment by BerkeleyTrue** [comment]
Closing as duplicate #2692 

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
