### ISSUE TITLE
says no div closing tag

### ISSUE THREAD

**Issue by sjohnson1131** [FreeCodeCamp/FreeCodeCamp#2694]
![button](https://cloud.githubusercontent.com/assets/13266395/9481526/14f2feb4-4b59-11e5-9e87-c54b2a6b4f46.png)

It is not giving me a checkmark for the objective for all button tags to have a closing tag, but they all do.

**Comment by benmcmahon100** [comment]
Is that all of your code? That test just checks the number of times <div occurs and makes sure that there is the same number of </div> there could be a closing tag with white space that's causing an issue

**Comment by sjohnson1131** [comment]
No, that's not all of it, I wasn't sure how to upload all of it. But nothing else was changed since the last step except the bit with the button div classes.

**Comment by benmcmahon100** [comment]
you can copy and paste it here like this
\`\`\`
   code here
\`\`\`

**Comment by benmcmahon100** [comment]
It may be that your code contains an edge case that we aren't accounting for

**Comment by sjohnson1131** [comment]
Well I didn't change anything but I tried to run code again and it took it. no idea what happened. thanks!

**Comment by benmcmahon100** [comment]
Ha Ha cool! Sorry about the weirdness :p Please reopen if the issue comes back!
