### ISSUE TITLE
You don't tell us which element to remove in the instructions

### ISSUE THREAD

**Issue by marnibrewster** [FreeCodeCamp/FreeCodeCamp#2695]
You do not specify which html element you want us to remove in the instructions.
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
