### ISSUE TITLE
Assigment is missing

### ISSUE THREAD

**Issue by eionut** [FreeCodeCamp/FreeCodeCamp#2696]
Challenge http://freecodecamp.com/challenges/waypoint-remove-an-element-using-jquery has an issue. You didn't write the assigment for this waypoint, so first you have to run the code to see what you have to do for this waypoint.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
