### ISSUE TITLE
seems  to create an infinite loop?

### ISSUE THREAD

**Issue by duanwalker** [FreeCodeCamp/FreeCodeCamp#2698]
Challenge http://www.freecodecamp.com/challenges/waypoint-understand-boolean-values has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

1. user notices only 2 challenges and the first challenge is complete 
2. user copies and pasts the second challenge as: 

assert(welcomeToBooleans() === true

to the code and then adding ); at the end. after clicking run the code it seemed to create more of the same challenge.

3. user comments out line 5 "return false". after clicking run the code user receives error in 2nd pic.

![boolean1](https://cloud.githubusercontent.com/assets/7536426/9482785/ceb52f28-4b65-11e5-9af1-86dbe7257dc3.JPG)
![boolean2](https://cloud.githubusercontent.com/assets/7536426/9482784/ceb279c2-4b65-11e5-884b-1534f70de764.JPG)

**Comment by BerkeleyTrue** [comment]
This is a recursive function

```js
function foo() {
  foo();
}
```

It will call itself infinitely until the browser runs out of room in the call stack. This is what your code is doing. Its calling itself until it dies a horrible death by implosion.

![tohi-03](https://cloud.githubusercontent.com/assets/6775919/9483182/8bd60e3e-4b51-11e5-9276-480cbaea456c.jpg)

Your code is also incorrect. Remove the self calling and you should be fine.

Happy Coding!
