### ISSUE TITLE
No code area

### ISSUE THREAD

**Issue by mikevarela** [FreeCodeCamp/FreeCodeCamp#2700]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by BerkeleyTrue** [comment]
Can you elaborate?

**Comment by mikevarela** [comment]
my apologies, my browser was white in the middle, no code area and the
screen was flashing relentlessly. it's calmed down now and seems to be
working. thanks

On Tue, Aug 25, 2015 at 5:40 PM, Berkeley Martinez <notifications@github.com

**Comment by BerkeleyTrue** [comment]
Alright. Let me know if it crops up again. 

Happy Coding!
