### ISSUE TITLE
broken link: Use the d3.max and d3.min Functions to Find Minimum and Maximum Values in a Dataset

### ISSUE THREAD

**Issue by bannon-tanner** [freeCodeCamp/freeCodeCamp#27001]
**Describe your problem and how to reproduce it:**
Link to the guide on the challenge Data Visualization: Data Visualization with D3: Use the d3.max and d3.min Functions to Find Minimum and Maximum Values in a Dataset is pointing to the wrong place

Incidentally, the challenge page uses the d3-max and d3-min in the url while the guide page uses d3.max and d3.min

**Add a Link to the page with the problem:**
[https://learn.freecodecamp.org/data-visualization/data-visualization-with-d3/use-the-d3-max-and-d3-min-functions-to-find-minimum-and-maximum-values-in-a-dataset/](url)

Get a Hint button brings the camper to 
[https://guide.freecodecamp.org/certifications/data-visualization/data-visualization-with-d3/use-the-d3-max-and-d3-min-functions-to-find-minimum-and-maximum-values-in-a-dataset](url)
which is 404 - Page not found

Correct link is 
[https://guide.freecodecamp.org/certifications/data-visualization/data-visualization-with-d3/use-the-d3.max-and-d3.min-functions-to-find-minimum-and-maximum-values-in-a-dataset/](url)

**Tell us about your browser and operating system:**
* Browser Name: Mozilla Firefox for Ubuntu canonical - 1.0
* Browser Version: 62.0.3
* Operating System: Ubuntu 18.04

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by thecodingaviator** [comment]
@moT01 / @scissorsneedfoodtoo If you can guide me to where this file might be located. I can check....

**Comment by warren1986** [comment]
Solution 
<body>
  <script>
    const positionData = [[1, 7, -4],[6, 3, 8],[2, 9, 3]]
    // Add your code below this line

    const maxX = d3.max (positionData, (d) => d[2]);
const output = maxX ; 
// Change this line

    // Add your code above this line

    d3.select("body")
      .append("h2")
      .text(output)
  </script>
</body>
