### ISSUE TITLE
Add ?run=disabled for SASS while loop challenge

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#27015]
I've found atleast 3-4 issue in this repo in the past week about the page hanging in the SASS ` @while ` loop challenge, this can be fixed by adding ` ?run=disabled `, is there a way to add it for just that one challenge?

**Comment by thecodingaviator** [comment]
If it helps, people have reported this happening on Chrome but not happening on Firefox

**Comment by Nirajn2311** [comment]
@thecodingaviator this usually happens when the code a user enters ends up in an infinite loop. Unfortunately Chrome crashes when this happens but not Firefox.

**Comment by ArielLeslie** [comment]
Duplicate of #26252

**Comment by procode200** [comment]
These issues related to this topic need to be closed. just forget about it. Please close these issues.

**Comment by nathanhannig** [comment]
It is best practice to have one issue for each problem. We need to close all duplicate issues that reference the same problem. Do we want to make this the main issue that will be tracked?

**Comment by thecodingaviator** [comment]
The other issues are about the problem, this one is ablout adding run disabled to the url so more people don’t encounter it. Hope that clears it up for everyone

**Comment by thecodingaviator** [comment]
@QuincyLarson / @scissorsneedfoodtoo Is there any way to add it?

**Comment by scissorsneedfoodtoo** [comment]
@thecodingaviator, just tried adding `?run=disabled` to the end of the SASS @while loop challenge, but wasn't able to get it working. Chrome still froze while I was writing out the loop. Were you able to get it working on your end?

**Comment by thecodingaviator** [comment]
@scissorsneedfoodtoo Using the code:
```html
<style type='text/sass'>
    $x: 1;
    @while $x < 11
    {
        .text-#{$x} {font-size: 5px * $x;}
        $x: $x + 1;
    }
</style>

<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>
<p class="text-6">Hello</p>
<p class="text-7">Hello</p>
<p class="text-8">Hello</p>
<p class="text-9">Hello</p>
<p class="text-10">Hello</p>
```
On https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while/?run=disabled](https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while/?run=disabled) works for me@scissorsneedfoodtoo Using the code:
```html
<style type='text/sass'>
    $x: 1;
    @while $x < 11
    {
        .text-#{$x} {font-size: 5px * $x;}
        $x: $x + 1;
    }
</style>

<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>
<p class="text-6">Hello</p>
<p class="text-7">Hello</p>
<p class="text-8">Hello</p>
<p class="text-9">Hello</p>
<p class="text-10">Hello</p>
```
On https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while/?run=disabled](https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while/?run=disabled) works for me

**Comment by scissorsneedfoodtoo** [comment]
@thecodingaviator, yes, with that code it passes just fine in both browsers. But I think the issue has more to do with the code being executed as the user is typing, causing the infinite loop and the page to hang. I tried adding `?run=disabled` to the URL in both browsers and typing the following: 

```
$x: 1;

@while $x < 11 {

}
```

And the page would hang before I could finish typing.

Rather than mess with the way the code is autorendered, maybe the easiest way to get around this is to add some code to the seed files for these kinds of challenges to help prevent infinite loops. Something like:

```
    $x: 1;
    @while $x < 11
    {
        /* Change code below */

        /* Change code above */
        $x: $x + 1;
    }
```

What do you all think?

**Comment by thecodingaviator** [comment]
@scissorsneedfoodtoo That looks good but I think it would defeat the purpose of the challenge, that is to get the user to create a full while loop themselves. Of course, if adding run?=disabled is not possible then to change the seed should be our next alternative

**Comment by scissorsneedfoodtoo** [comment]
@thecodingaviator, I agree. It would be much better to have the user write out the whole loop, or at least at much of it as possible. With the way the website works now, I don't see that happening without changing the way the SASS challenges are rendered, maybe increasing the time between what the user types and their code is rendered. My concern is that such a change might have some unintended effects elsewhere on the site.

How about something in between? This looks a bit messy, but would require the user to do more to pass the challenge and should prevent most infinite loops:

```
    $x: 1;

    /* Change code below */
    @while $x < __
    /* Change code above */
    {
        /* Change code below */

        /* Change code above */
        $x: $x + 1;
    }
```

So long as they don't delete the operator the browser shouldn't hang. We could even require users to initiate the x variable, but that would make the seed code look even messier.

**Comment by thecodingaviator** [comment]
@scissorsneedfoodtoo I see the problem with that, maybe do this and ask the user to fix the loop?
```css
/* Change code below*/
@while $x
    {
        $x: $x + 1;
    }
/* Change code above */
```

**Comment by scissorsneedfoodtoo** [comment]
@thecodingaviator, that's definitely a start, but I think we would still need a bit more to prevent infinite loops. In your example, if `$x: 1;` is in the seed or is added by the user, the page will still hang due to an infinite loop. Might be best to at least have the `<` operator so the page doesn't hang immediately.

**Comment by parthparth** [comment]
That sounds better. Should I go ahead and do it?

**Comment by scissorsneedfoodtoo** [comment]
Sure, go for it! Maybe with just a bit more spacing and an underscore for the user to replace?

```
/* Change code below*/
@while $x < _
    {

        $x: $x + 1;
    }
/* Change code above */
```

Does that look okay to you?

**Comment by scissorsneedfoodtoo** [comment]
That's true. Just do what you feel is best and we can review your PR as it comes in! I'm sure another reviewer will be able to offer more insight and maybe suggest an alternative we didn't think of.

**Comment by thecodingaviator** [comment]
@scissorsneedfoodtoo these guys did real work. See #34298
