### ISSUE TITLE
Wiki request - How to get the MEAN stack running locally on Windows 10

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#2701]

**Comment by awesomeaniruddh** [comment]
I can do this.

**Comment by saadanerdetbare** [comment]
there is not much difference to get it running on 7, 8.1 and 10.
If you get a good article on this subject then you should maybe delete the article https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clone-the-FreeCodeCamp-website-on-a-Windows-pc i wrote to not clutter up the wiki on the subject.

**Comment by awesomeaniruddh** [comment]
Oh, I wasn't aware that someone has already written an article. I'll just edit that one then. Some steps could be covered in more detail.

**Comment by saadanerdetbare** [comment]
yes, and it need something on the msbuild environment.
I have run into some problems on node-gyp that i have not been able to solve (on Windows 10 x64 Enterprise with VS Enterprise 2015) with the result that some dependencies gets build, not with errors, but they get build wrong. That in turn results in gulp less fails and the stylesheets do not get build

**Comment by awesomeaniruddh** [comment]
I've run into the same errors...but I've been ignoring them and everything is running fine for me so far.

**Comment by saadanerdetbare** [comment]
The thing that makes gulp less fail has actually been fixed in the less package. I believe it is this
https://github.com/less/less.js/pull/2519
But it requires the package to be updated. When i update and run with the newest version of less then gulp works fine.

**Comment by bugron** [comment]
Closing this issue. See this [article](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clone-the-FreeCodeCamp-website-on-a-Windows-pc).
