### ISSUE TITLE
Wiki request - How to get the MEAN stack running locally on Ubuntu

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#2702]

**Comment by erictleung** [comment]
Could we point people to this repository? https://github.com/meanjs/mean 

I haven't tested it out but it looks promising on implementing and getting started on using a MEAN stack.

**Comment by W12S12E12** [comment]
for linux 
http://unix.stackexchange.com/questions/17779/how-can-i-build-a-custom-distribution-for-running-a-simple-web-browser
for linux: http://wiki.linuxcnc.org/cgi-bin/wiki.pl?Installing_EMC2
for ubuntu: http://ubuntuforums.org/showthread.php?t=1346642   


andhttps://github.com/openresty/openresty.org/blame/4a4b57984ea203908ecb5b58c115fc7a883dfd9d/index.html

**Comment by ltegman** [comment]
I don't know if this is even a relevant issue anymore since we don't use the `A` in `MEAN` now.

**Comment by thejonathangraham** [comment]
@BerkeleyTrue Because we're not using angular anymore this is not relevant. We should close this issue

**Comment by AkiraLaine** [comment]
Closing this as it's not relevant any more.
