### ISSUE TITLE
Wiki request - How to get the MEAN stack running locally on OSX

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#2703]

**Comment by leonfeng** [comment]
Request fulfilled: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-the-MEAN-stack-running-locally-on-OSX

**Comment by bugron** [comment]
Closing this issue as the [requested article](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-the-MEAN-stack-running-locally-on-OSX) is created, @leonfeng thanks.
