### ISSUE TITLE
When this page is first loaded, the code only shows up to line 11.

### ISSUE THREAD

**Issue by LuckyOreo** [FreeCodeCamp/FreeCodeCamp#2707]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-javascript-slot-machine has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When this page is first loaded, it only shows code up to line 11.  The rest of the code shows up when the blank space below line 11 is clicked, or when the code area is scrolled.

**Comment by BerkeleyTrue** [comment]
I cannot replicate. Can you post screen shots of the issue?

**Comment by LuckyOreo** [comment]
![fccslotmachinebug](https://cloud.githubusercontent.com/assets/13142234/9483913/4b86cc0c-4b73-11e5-9ccd-c4584f3fd7b6.jpg)

this was present on all slot machine challenges.  This was present on Chrome Version 44.0.2403.157 m as well as IE11.

**Comment by BerkeleyTrue** [comment]
Can you try reseting your code? (your current code will be lost)

**Comment by LuckyOreo** [comment]
yeah resetting the code will display the rest of the code but if I do a refresh of the page it will behave the same where only code upto line 11 will show.

**Comment by souldreamer** [comment]
I can confirm the issue:
![screenshot 1](https://cloud.githubusercontent.com/assets/1394436/9508504/a492f29e-4c5e-11e5-93fc-b68f94f2a9a1.png)

However, for me the text reappears if I scroll or I click on the editor where the missing code should be (but doesn't reappear if I click on the code I *can* see) or if I move the cursor downwards until I reach the missing code.

**Comment by bugron** [comment]
I experience this issue too!

**Comment by Daynil** [comment]
Same issue here, seems to happen when the editor has a scrollbar for overflow text.
When page first loads:

![image](https://cloud.githubusercontent.com/assets/4650666/9558625/7870ab34-4dad-11e5-8a0a-6120f265ec15.png)

After scrolling around the editor or clicking on it:
![image](https://cloud.githubusercontent.com/assets/4650666/9558644/b74702f4-4dad-11e5-8d05-a6d42ee17b80.png)

**Comment by dawnvoh** [comment]
I also have seen this in Waypoints 18 through 21, using Chrome.  I was able to press "Reset" as a workaround.
![incomplete code](https://cloud.githubusercontent.com/assets/8917154/9570059/415050c8-4f4c-11e5-9f67-188853b65bd1.jpg)

**Comment by BerkeleyTrue** [comment]
Thank you all for reporting. We no longer need anymore screen caps.

We need to find out where the bug lies. Could someone who is experiencing this issue spin up a local copy and step through the code in `commonFramework` on page load in order to pinpoint the actual cause of the issue. 

It is difficult for us to actually fix something we cannot replicate.

I suspect its could be one of two things, but it may also be something else entirely.

a. It could be the codeStorage code in the begging of the commonFramework file (the code responsible for saving and pulling code out of localStorage). This would explain why `reset` code resolves the issue.
b. It could be a known bug in CodeMirror. We are currently using an outdate version. Could a camper search through CodeMirrors repository and find anything that might explain this?

**Comment by jbmartinez** [comment]
The rest of the code appears after a repaint (resizing the viewport makes it appear), I guess it may be a CodeMirror problem

**Comment by BerkeleyTrue** [comment]
It would be great if we could be certain.

**Comment by bugron** [comment]
@BerkeleyTrue try this.
commonFramework.js -> `editor = CodeMirror.fromTextArea(document.getElementById('codeEditor')`, change `lineWrapping: true` to `lineWrapping: false` and magic will happen... well happened at least for me.

**Comment by dawnvoh** [comment]
I will tell you what I see, I hope it is helpful…

I’m in commonframework, and when I step from line 757, to line 759, that’s when the code gets displayed up to line 11.

Ok, so I started stepping INTO the functions that are being invoked between lines 757 and 759.  
I’m taken to lines 2268, 2111, 2122, and eventually end up in function updateDisplayIfNeeded.  

Somewhere between lines 709 and 713, the code gets displayed up to line 11.  I noticed that the variable toUpdate has value 11.

**Comment by QuincyLarson** [comment]
@bugron and I looked into fixing this with wordwrap, but it didn't work.

We think the issue is that our version of Codemirror is stale. 

We need to switch to using the NPM version of Codemirrror instead of vendorizing Codemirror in our app. @BerkeleyTrue I know you mentioned your desire to do this. I think this is a priority.

**Comment by BerkeleyTrue** [comment]
Can someone test against a newer version CodeMirror and report their findings?

**Comment by bugron** [comment]
@BerkeleyTrue I tried v5.6.1 and this is [the result](http://prntscr.com/8e0oqw).

**Comment by BerkeleyTrue** [comment]
Anyone have any insight on the root cause?

**Comment by bugron** [comment]
http://stackoverflow.com/questions/7772469/codemirror-with-a-few-lines-dont-show-up-until-something-triggers-a-repaint

**Comment by awesomeaniruddh** [comment]
^ didn't work for me on localhost. Added `editor.refresh()` to line 196 in the `commonFramework.js` file. That's where it is supposed to go right?

**Comment by dawnvoh** [comment]
Interesting, this issue does not happen for me in the JavaScript waypoints.  Just FYI in case it provides a clue.

**Comment by jmtaber129** [comment]
+1

**Comment by bugron** [comment]
@BerkeleyTrue , @ahstro , @awesomeaniruddh try this. ![](http://i.imgur.com/sT2eKUt.png). Worked for me. The code:
```javascript
$(document).ready(function() {
   editor.setOption("mode", "text/html");
   editor.refresh();
 });
```

**Comment by BerkeleyTrue** [comment]
Looks like we just need to add the editor.refresh() to the end of commonFramework. I remember this being somewhere in the code before but I may have been removed accidentally.

Anyone want to submit a PR?

**Comment by BerkeleyTrue** [comment]
Looks like we just need to add the editor.refresh() to the end of commonFramework. I remember this being somewhere in the code before but I may have been removed accidentally.

Anyone want to submit a PR?

**Comment by finger563** [comment]
I'm getting this issue after moving from an older, vendorized version of CM to using the packaged version off npm.  Is there any known workaround?  I'm getting issues with
*  not loading all of the code/document,
*  gutter not drawing past certain line numbers when scrolling,
*  CM not scrolling when using pg-up/pg-down, and resetting the view (but not moving the cursor) when scrolling the cursor with the arrow keys past certain points (the same points which didn't initially have loaded code)

**Comment by finger563** [comment]
As an addendum, it seems to only happen when i'm placing it within a div that's configured to have `height: 100%`

**Comment by scipper** [comment]
old topic, but still a problem, as I determined. 

My solution was to set lineWrapping to false when mode is text/html:

before
`this.htmlOptions = {
  lineWrapping: true
}`

after
`this.htmlOptions = {
  lineWrapping: false
}`

that was all I had to change.
