### ISSUE TITLE
Error: while running on npm run develop 

### ISSUE THREAD

**Issue by GursimarSinghChopra** [freeCodeCamp/freeCodeCamp#27083]
Getting errors while executing 'npm run develop'

![screenshot from 2018-10-23 21-09-32](https://user-images.githubusercontent.com/31305427/47372853-46a92300-d708-11e8-8c1c-1effc72f3129.png)

![screenshot from 2018-10-23 21-17-27](https://user-images.githubusercontent.com/31305427/47373388-5aa15480-d709-11e8-8d9e-a794437de1a2.png)

Error generating due to the const path:
1. Go to freeCodeCamp/client/plugins/fcc-create-nav-data/create-navigation-node.js
2. Scroll down to Line No 26 and you can see const [,path] and this comma is generating an error as it can not get the path

 - OS: Ubuntu 18.04 LTS
 - Browser chrome
 - Version 70.0.3538.67 (Official Build) (64-bit)

As you remove the comma from the const[path] variable the 'npm run develop' command works fine.

**Comment by raisedadead** [comment]
We have resolved this specific issue with local setup. Please re-clone and make a fresh installation. A few other issues in the setup are still being worked upon. We will post an update in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) when the local is 100% ready.

Thanks
