### ISSUE TITLE
Create a Script Element stays a red X error

### ISSUE THREAD

**Issue by 4CesliV** [FreeCodeCamp/FreeCodeCamp#2708]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
I put in the script tag and the jQuery function, but the instructions continued to say "Create a script element." It wouldn't go away.
The code works, when "Run Code" button is hit; however, the red X image remains next to "Create a script element."
![image](https://cloud.githubusercontent.com/assets/12461914/9483344/dd7c663c-4b53-11e5-9329-4faae839b507.png)

**Comment by BerkeleyTrue** [comment]
Hello @4CesliV 

You code is incorrect. Remove the src attribute. 

see: http://stackoverflow.com/questions/19987269/script-tag-src-attribute

And in the future please follow these steps. https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-help-when-you-get-stuck

Happy Coding!
