### ISSUE TITLE
Jquery lessons malfunctioning

### ISSUE THREAD

**Issue by BVegan** [FreeCodeCamp/FreeCodeCamp#2710]
Challenge http://freecodecamp.com/challenges/waypoint-target-elements-by-class-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When doing the jquery lessons, the page continues to reload and a popup shows that tells me to go on to the next lesson BEFORE I do the current lesson.

**Comment by BerkeleyTrue** [comment]
We will be tracking this issue on #2709
