### ISSUE TITLE
Allows to proceed even on completing incorrect challenge

### ISSUE THREAD

**Issue by smarshy** [FreeCodeCamp/FreeCodeCamp#2715]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-block-element-bootstrap-button has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![image](https://cloud.githubusercontent.com/assets/13931206/9484242/55e3db46-4bc7-11e5-81d5-c0ace6c34dea.png)

or is this not an issue?

**Comment by benschenker** [comment]
Hey @smarshy thanks for posting this!

It looks like this may have been fixed.  I cannot replicate it and it seems to be working properly.  Feel free to reopen this if you still see this problem.
