### ISSUE TITLE
Grader not recognizing single quotes

### ISSUE THREAD

**Issue by stwaldo** [FreeCodeCamp/FreeCodeCamp#2716]
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue. When entering the three lines required for the code to execute: 
```
    $($(".slot")[0]).html(slotOne);
    $($(".slot")[1]).html(slotTwo);
    $($(".slot")[2]).html(slotThree);
```

If you use single quotes (') instead of double (") the code will pass, but the grader will fail you for:

`You should have used the the selector given in the description to select each slot and assign it the value of slotOne, slotTwo and slotThree respectively`

**Comment by benschenker** [comment]
Hey @stwaldo   thanks for posting this!

We have a few duplicate postings of this so see #2522 for updates on this issue.

I'll close this as a duplicate.
