### ISSUE TITLE
Disappearing instructions

### ISSUE THREAD

**Issue by JoeCool1971** [FreeCodeCamp/FreeCodeCamp#2717]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Code below "You shouldn't need to modify code below this line" initially missing, then once it appears, instructions disappear.  Reloading page sometimes causes scrollbar next to instructions to disappear as well.  Requires reloading page 4-5 times for everything to return, so maybe it's just me?

![image](https://cloud.githubusercontent.com/assets/13267050/9484517/4feb513e-4b62-11e5-9ebf-b184a4062c4b.png)

**Comment by Rich-Hopkins** [comment]
No, it is not just you, but the issue I created was also closed. Irresponsible, in my opinion, to close an issue just because the person at the other end doesn't experience the same issue.

**Comment by Rich-Hopkins** [comment]
And I see that for you it is in Chrome. For me it is in IE 11. So it is not a specific browser problem.

**Comment by abhisekp** [comment]
@JoeCool1971 Please close this issue if this is resolved.

**Comment by DBaldwin107** [comment]
Why is this issue closed? I am still having this problem.

My code:
<script>
  $(document).ready(function() {

  });
</script>

Will not go through.
