### ISSUE TITLE
Error on Script tag lesson

### ISSUE THREAD

**Issue by yogonwa** [FreeCodeCamp/FreeCodeCamp#2718]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The checkbox/instructions div disappears when I create the <script> tag in the code editor.

Using Chrome44
![script_error](https://cloud.githubusercontent.com/assets/10161512/9484663/483df048-4b7d-11e5-803d-4de555404c34.png)

**Comment by sashashakun** [comment]
Hi!
I made this lesson and don't see any problems (OS X 10.10.5, Chrome 44). Please add details, what browser and OS you use?

**Comment by yogonwa** [comment]
I can no longer replicate. It was likely a problem with browser caching or something. For the record I was using Chrome 44.  

I'm closing this for now.
