### ISSUE TITLE
Change font size issue

### ISSUE THREAD

**Issue by arkydon** [FreeCodeCamp/FreeCodeCamp#2719]
Challenge http://freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue.
 Keeps telling me to change all p elements to font-size 16px even though I already did
![untitled](https://cloud.githubusercontent.com/assets/7901865/9484850/60492408-4bcf-11e5-960f-c439b8c1e878.png)

**Comment by bugron** [comment]
@arkydon thanks for posting this issue!
I [still](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2171#issuecomment-133770565) pass this challenge.
Try to [Refresh Your Browser Cache](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache) and [Clear Your Browser's Local Storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser%27s-Local-Storage).

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by arkydon** [comment]
Clearing browser cache did'nt help but I just remembered that I had set the browser's minimum font size to 20.After setting it to smaller than 16 it finally works.
