### ISSUE TITLE
emmet not working

### ISSUE THREAD

**Issue by dgoran** [FreeCodeCamp/FreeCodeCamp#2720]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-custom-heading has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

just messing on my windows 10 tablet (torture by the way) and realized emmet is not working as it was on my mac using chrome on both...

**Comment by dallanlee** [comment]
I'm having the same frustration with emmet not working.

**Comment by BerkeleyTrue** [comment]
It was in fact removed accidently. Can someone add it back? All you need to do is add this line
```js
emmetCodeMirror(editor); // NOTE: not sure if the editor is stored in an var called `editor`. It might be something else.
```
After the editor is created in client/commonFramework.js
