### ISSUE TITLE
Waypoint: Basic Javascript 37

### ISSUE THREAD

**Issue by eblosch** [FreeCodeCamp/FreeCodeCamp#2721]
Challenge http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue.

The performance is incredibly slow for waypoints 37-40, making it difficult to complete the exercise. This is on Chrome 44.0.2403.157.

**Comment by benschenker** [comment]
Hey @eblosch thanks for posting this issue!

I'm having trouble replicating this.  Are you still experiencing this issue?
