### ISSUE TITLE
Javascript tests disappear on challenges with iFrame

### ISSUE THREAD

**Issue by jpayne0810** [FreeCodeCamp/FreeCodeCamp#2723]
Challenge http://freecodecamp.com/challenges/waypoint-use-appendto-to-move-elements-with-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
Several of the jQuery Waypoint challenges don't show the checkmarks unless you hit the run code, so you don't always have the instructions on what to code unless you hit the run code box and then they they are gone again.

**Comment by BerkeleyTrue** [comment]
This should be fixed in production now. Please re-open if it is still an issue for you.

Happy Coding!
