### ISSUE TITLE
Page went into some kind of infinite page refresh loop

### ISSUE THREAD

**Issue by AKWintermute** [FreeCodeCamp/FreeCodeCamp#2729]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by Stiino0** [comment]
Some extra data: the playground refreshes a dozen times and then the completed message is shown. This is apparently with (almost?) all JQuery waypoints.

**Comment by Mansuro** [comment]
Same issue seems to happen in #2732

**Comment by BerkeleyTrue** [comment]
Closing as duplicate of #2709 
 
Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
