### ISSUE TITLE
Jquery Challenge bugs

### ISSUE THREAD

**Issue by fevzicakmak** [FreeCodeCamp/FreeCodeCamp#2731]
Challenge http://freecodecamp.com/challenges/waypoint-target-elements-by-class-using-jquery has an issue. 

While studying on Jquery lesson, Waypoint page is starting to refresh itself continously and success popup is appearing before finishing code and running code. 

Mozilla Firefox 40.0 with Ubuntu 14.04 LTS

**Comment by bugron** [comment]
@mohessaid thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2729

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
