### ISSUE TITLE
Reload loop 

### ISSUE THREAD

**Issue by rhshah123** [FreeCodeCamp/FreeCodeCamp#2732]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-javascript-slot-machine has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This challenge is going into reload loop for some reason, please check

**Comment by BerkeleyTrue** [comment]
Closing as duplicate #2709

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
