### ISSUE TITLE
 27 appearing in second array set as largest number rather than 5

### ISSUE THREAD

**Issue by codeNameJKB** [FreeCodeCamp/FreeCodeCamp#2735]
Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The second set of arrays is producing [ 27, 27, 39, 1001 ] rather than  [ 27, 5, 39, 1001 ] when there is not a number 27 in the array arr[1] so number 5 should be the largestNumber. I've tried using an if statement to test and replace 27 to 5 using if statements  (arr[1][1] === 27) { arr[1][1] = 5; }  as well as if (arr[1][1] !== 5) { arr[1][1] = 5; }
neither attempt work. 

[[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]
![screen shot 2015-08-26 at 8 46 49 am](https://cloud.githubusercontent.com/assets/13787549/9493782/2670189e-4bd0-11e5-9e86-2be7e1b53dbe.png)

**Comment by Mansuro** [comment]
You are comparing largestNum of the first array ( 27), with the elements of the second array.
You should reinitialize largestNum to 0 after every inner loop iteration

    for (var i = 0; i < arr.length; i++) {
        for (var j = 0; j < arr[i].length; j++) {
            if (largestNum > arr[i][j]) {
                largestNum = arr[i][j];
             } 
             largestArray[i] = largestNum;
             largestNum = 0;
        }
    }

**Comment by codeNameJKB** [comment]
the shorter version was successful. but the longer version was returning [0, 0, 0, 0]. 

 In the code is  max[i] represents the outer array and arr[i][j] represents the inner array, and is comparing the outer and inner array to determine which number is largest? @Mansuro  - Thank You
 
function largestOfFour(arr) {
  // You can do this!
var max = [0, 0, 0, 0];
    for (var i = 0; i < arr.length; i++) {
        for (var j = 0; j < arr[i].length; j++) {
            if (arr[i][j] > max[i]) {
                max[i] = arr[i][j];
            } 
        }
    }
    return max;
}

**Comment by Mansuro** [comment]
max is filled by looping on the inner array and checking the max value in it.
Btw, the longer version worked for me as well.

**Comment by benschenker** [comment]
Closing this as it seems resolved.  Feel free to reopen if issues remain
