### ISSUE TITLE
Auto complete on comments inaccurate. 

### ISSUE THREAD

**Issue by Bshally** [FreeCodeCamp/FreeCodeCamp#2736]
Challenge http://freecodecamp.com/challenges/waypoint-comment-out-html has an issue. Auto complete on commenting is frustratingly inputting closing comment tags at the end of the document, even when I erase them. 

This results in wasted time trying to remove the unneeded closing comment and may be confusing to people newer to HTML.

**Comment by benschenker** [comment]
Hey @Bshally thanks for posting this!

It looks like this is a duplicate of #1973 so keep an eye there for updates.
