### ISSUE TITLE
Waypoint: Add your JavaScript Slot Machine Slots runs constantly not allowing one to add code

### ISSUE THREAD

**Issue by pwolter** [FreeCodeCamp/FreeCodeCamp#2743]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-your-javascript-slot-machine-slots has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This Waypoint JavaScript's exercise code runs constantly (even the previous one does it but you still can add your code on that one) so you can't add your code and gives you a succesful screen/window without doing anything.

**Comment by pwolter** [comment]
Just get to that waypoint. To reproduce you don't need to do anything, I'm using Mac Yosemite, Firefox 39.0.3

**Comment by Mansuro** [comment]
This issue has been fixed
