### ISSUE TITLE
Completing jQuery without successfuly writing any code

### ISSUE THREAD

**Issue by BenDuncan1** [FreeCodeCamp/FreeCodeCamp#2744]
Challenge http://freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey @BenDuncan1 thanks for posting! 
I can't reproduce this, it may have been fixed.  Feel free to reopen this if this is still an issue for you.
