### ISSUE TITLE
Potential issue : JavaScript : test is failing even if answer looks correct.

### ISSUE THREAD

**Issue by hussainssabir** [FreeCodeCamp/FreeCodeCamp#2747]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-first-character-in-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Tried : (function(v){return(v);})(firstLetterOfLastName[0]);
Test Failed: Please check screenshot.

![image](https://cloud.githubusercontent.com/assets/2824862/9503046/9f78cdc4-4c2c-11e5-88ec-71e18fbd1fdc.png)

**Comment by hussainssabir** [comment]
Sorry, this is not an issue.

**Comment by djsirena** [comment]
Grammatically it should state "should be 'an L' ".
