### ISSUE TITLE
<script> code bugging out

### ISSUE THREAD

**Issue by zWarMob** [FreeCodeCamp/FreeCodeCamp#2749]
Since the first challenge containing the tags <script></script> the page is going crazy
I believe your code is reloading every time you make an edit ? well with those script tags it is reloading constantly! and after a few seconds it says I completed this challange and to go to the next one
using Firefox 40.0.2 

don't know what else I should include in this
maybe my windows ? 8.1 Pro

**Comment by Mansuro** [comment]
I think this issue is fixed

**Comment by benschenker** [comment]
Yes @zWarMob it looks like this is a duplicate of #2729 which has been fixed.

Thanks@
