### ISSUE TITLE
It should be correct only after the three checkboxes received the same name

### ISSUE THREAD

**Issue by weidmaster** [FreeCodeCamp/FreeCodeCamp#2750]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes has an issue. 

To reproduce: try the challenge and when you are going to name the checkboxes the challenge will be correct if you only type one name.

Expected: The challenge will only mark as complete if all three checkboxes have the same name.

![issue-challenge-checkboxes](https://cloud.githubusercontent.com/assets/9614642/9503734/26254bb8-4c0f-11e5-9ab4-6babeae95cb8.jpg)

**Comment by bugron** [comment]
@weidmaster thanks for posting this issue!
Note that your issue is a duplicate:
#2067
#1323
#1018
Also there is a PR #2728 which is waiting for approvement.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
