### ISSUE TITLE
Broken at start

### ISSUE THREAD

**Issue by weidmaster** [FreeCodeCamp/FreeCodeCamp#2752]
Challenge http://freecodecamp.com/challenges/waypoint-check-radio-buttons-and-checkboxes-by-default has an issue. 

To reproduce: open the challenge. It is broken. No checkmarks and no default code.

Expected: The same behaviour as other challenges. A code editor with previous code and the checkmarks of completion.

![issue-challenge-checking-default](https://cloud.githubusercontent.com/assets/9614642/9503936/3c14bd7c-4c10-11e5-8f32-e82902b7255d.jpg)

**Comment by BerkeleyTrue** [comment]
Fixed. Please re-open if the issue persist!

Happy Coding!
