### ISSUE TITLE
Correct answer not accepted

### ISSUE THREAD

**Issue by Ogodei** [FreeCodeCamp/FreeCodeCamp#2753]
Challenge http://www.freecodecamp.com/challenges/bonfire-sum-all-primes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
----------------------------------------------------------------------------------------------------

I was able to successfully pass this challenge using a naive solution (using simple loops); however, when executing a more complex solution a bug arises:

![bugged_solution](https://cloud.githubusercontent.com/assets/9529211/9504126/d3c90fae-4c08-11e5-98c1-c35cb6b171e9.jpg)

Notice that the function returns the correct solution; yet, the challenge fails to accept it. Notice as well that the test suite [on the left] prints `expected 32 to equal 17` -- which should not be the case. 

Here is the full code (which elicits the bug):
```
var arrayOfPrimes = [];
var sum_ = 0;

function isPrime(x){
  /*if x is prime return true, else return false */
  
  // check for primality:
  for(var i = 0; i < arrayOfPrimes.length; i++){
    if(x % arrayOfPrimes[i] === 0){
      return false;
    }
    //sieve of eratosthenes property:
    if(arrayOfPrimes[i] > Math.sqrt(x)){
      break;
    }
  }
  return true;
}

function sumPrimes(num) {
  for(var i = 2; i <= num; i++){
    if(isPrime(i)){
      arrayOfPrimes.push(i);
      sum_ += i;
    }
  }
  return sum_;
}

sumPrimes(10);
```

**Comment by denmch** [comment]
I can't figure out what's going on here, but I can confirm.

My code passes, but this code does not, even though it produces the right values when run in the console. Something about this solution seems to be causing the test cases to add 15 to value returned.

**Comment by Mansuro** [comment]
if we remove the following code
    if(arrayOfPrimes[i] > Math.sqrt(x)){
        break;
    }
the tests pass, I don't know why though

**Comment by Ogodei** [comment]
You are correct in that modifying
```
if(arrayOfPrimes[i] > Math.sqrt(x)){
	break;
}
```
to compare only the index value, `i`, circumvents the error. However, the original solution returns the correct result, and therefore the issue isn't really solved as to why the bug arises. 

> loop index i should be compare to sqrt(x)

Also, as an aside, the correct (i.e. optimal) solution should be using `arrayOfPrimes[i]`, not the loop index, `i`, for the conditional statement. C.f. [Sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes). Both will return the same answer, but using `arrayOfPrimes[i]` will return the answer quicker because it is iterating through the list of prime numbers and checking if any of the known primes are divisors.

**Comment by benschenker** [comment]
Hey @Ogodei it looks like this is a scoping issue.

You declare and initialize:
```
var arrayOfPrimes = [];
var sum_ = 0;
```
before the functions run, so it works for the first test but when the second test runs, those variables need to be reinitialized.

The following is a slightly modified version of your code that passes all tests.  Notice the variables are declared at the top but initialized in the main sumPrimes function (this function is what the tests are calling):
```
var arrayOfPrimes;
var sum_;

function isPrime(x){
  /*if x is prime return true, else return false */

  // check for primality:
  for(var i = 0; i < arrayOfPrimes.length; i++){
    if(x % arrayOfPrimes[i] === 0){
      return false;
    }
    //sieve of eratosthenes property:
    if(arrayOfPrimes[i] > Math.sqrt(x)){
      break;
    }
  }
  return true;
}

function sumPrimes(num) {
  arrayOfPrimes = [];
  sum_ = 0;
  for(var i = 2; i <= num; i++){
    if(isPrime(i)){
      arrayOfPrimes.push(i);
      sum_ += i;
    }
  }
  return sum_;
}

sumPrimes(10);
```
