### ISSUE TITLE
regular expression use not clear

### ISSUE THREAD

**Issue by iuza83** [FreeCodeCamp/FreeCodeCamp#2754]
Challenge http://www.freecodecamp.com/challenges/waypoint-sift-through-text-with-regular-expressions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
The challenge ask to find all occurrences of the word 'and' expecting '/and+/gi' as solution, but the use of '+' is unnecessary and not clear.

**Comment by bugron** [comment]
@iuza83 thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1938

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by iuza83** [comment]
@bugron sorry, my bad!
next time I'll make sure to check it first.
