### ISSUE TITLE
waypoint-sift-through-text-with-regular-expressions regular expression incorrect

### ISSUE THREAD

**Issue by UziTech** [FreeCodeCamp/FreeCodeCamp#2755]
Challenge http://freecodecamp.com/challenges/waypoint-sift-through-text-with-regular-expressions has an issue.

it wants a regular expression `/and+/gi` but should check for `/and/gi`

the plus means it would match `andd` or `anddddddddddddddd` instead of just `and`

**Comment by bugron** [comment]
@iuza83 thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2754
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1938

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
