### ISSUE TITLE
Page does Not appear - Waypoint: Use Bracket Notation to Find the First Character in a String

### ISSUE THREAD

**Issue by badbabykosh** [FreeCodeCamp/FreeCodeCamp#2756]
Challenge http://freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-first-character-in-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The code screen for this page does not apear
Waypoint: Use Bracket Notation to Find the First Character in a String

**Comment by denmch** [comment]
I couldn't reproduce this. Can you give more information or a screenshot?

**Comment by badbabykosh** [comment]
Oddly enough the page reappeared. Strange
