### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by chipymunk** [FreeCodeCamp/FreeCodeCamp#2761]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-javascript-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I'm working on this challenge and I cant seem to figure out what I'm doing wrong.  I'm looking to add a property to an array, in line.  So I have

myDog.sound = "bark";

But it continues to give me errors.  I cant see whats wrong with my code...  Maybe a bug?

**Comment by denmch** [comment]
Hi chpymunk. This isn't a bug. Notice that you're asked to add a _property_ called "bark", not a _value_ of "bark." The value is not specified, so that's up to you.

**Comment by chipymunk** [comment]
Thanks...  Yeah, I saw that this morning..  Chemo brain..  Thanks again..
