### ISSUE TITLE
Monospace Font Family

### ISSUE THREAD

**Issue by aalasolutions** [FreeCodeCamp/FreeCodeCamp#2763]
Challenge http://www.freecodecamp.com/challenges/waypoint-set-the-font-family-of-an-element has an issue. 

I am using 

```
 p {
    font-size: 16px;
    font-family: "courier";
  }
```
And I can see the output on the right is changed to monospace but it dosnt solve the question

**Comment by Mansuro** [comment]
You should use the font **Monospace** not **courier**
