### ISSUE TITLE
Waypoint doesn't accept JQuery selector surrounded by single quotes

### ISSUE THREAD

**Issue by prashcr** [FreeCodeCamp/FreeCodeCamp#2764]
http://www.freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life  
  
e.g.  
```  
$($('.slot')[0]).html(slotOne);
```  
Doesn't work

**Comment by oab00** [comment]
the file: [basic-javascript.json](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/basic-javascript.json#L1448) (line 1448) branch Staging

seems like the matching is fixed to the usage of double quotes `"` only and not passing single quotes `'`.

**Comment by bugron** [comment]
@prashcr thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2522

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
