### ISSUE TITLE
submit method

### ISSUE THREAD

**Issue by j113203** [FreeCodeCamp/FreeCodeCamp#2768]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-a-submit-button-to-a-form has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

submit button can use as input

**Comment by mtargiel** [comment]
<form action="/submit-cat-photo">
  <input name="action" type="text" placeholder="cat photo URL">
  <button type="submit">SUBMIT</button>
</form>

**Comment by mtargiel** [comment]
![bez tytulu](https://cloud.githubusercontent.com/assets/8327212/9518491/4d22a3d4-4cb7-11e5-9da8-810c2e9ee378.png)

**Comment by j113203** [comment]
i mean <input type=sumbit> should acceptable

**Comment by j113203** [comment]
<input type=button

**Comment by BerkeleyTrue** [comment]
@j113203 Can you describe the issue you are having?

Please read: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue
