### ISSUE TITLE
Can't Progress

### ISSUE THREAD

**Issue by mikepitts25** [FreeCodeCamp/FreeCodeCamp#2769]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

A colleague of mine mentioned that he was trying to do this particular Waypoint last night and it wasn't allowing him to submit his code. I tried it on mine, and after putting in ```<script>$(document).ready(function() {});</script>``` at the top of the document, the phone screen turns white and nothing happens when you click run.

**Comment by iTypeSlow** [comment]
What kind of phone are you using?

**Comment by 4mifix** [comment]
@mikepitts25 copy and paste the code in the instructions into the exercise it will work. I had the same issue and once I copied and pasted it everything was gravy. Got stuck on this for days until I tried the copy and paste.

**Comment by iTypeSlow** [comment]
Oh! I thought you were using an actual mobile device to test the code. My bad :(
