### ISSUE TITLE
Courseware Change the Color of Text

### ISSUE THREAD

**Issue by yaskyj** [FreeCodeCamp/freecodecamp#277]
Using style="color: red" or style="color: #ff0000" on the h2 tag for the Change the Color of Text courseware will not give a passing test. I'm using Chrome on Mac.

**Comment by aldraco** [comment]
I can confirm this problem, using Chrome on a mac as well.

**Comment by aldraco** [comment]
I found a fix for this, I'll be able to make a PR soon.

**Comment by aldraco** [comment]
This is addressed in #298
