### ISSUE TITLE
My code is correct but script dont works

### ISSUE THREAD

**Issue by mhbm** [FreeCodeCamp/FreeCodeCamp#2771]
function diff(arr1, arr2) {
  var newArr = [];
  var aux =[];
  if (arr1.length <= arr2.length){
     aux = arr1;
     arr1 = arr2;
     arr2 = aux;
  }
  var controlador ;
  // Same, same; but different.
  for (var i = 0; i < arr1.length ; i++){
    for (var j = 0 ; j < arr2.length ; j++){
        if (arr1[i] === arr2[j]) {
          controlador = 0;
          break;
        } else controlador = arr1[i];
          
    }
    if (controlador != 0){
      newArr.push(controlador)
    }
  }
  var x = 0;
  var k = 0;
  for (var x = 0; x < newArr.length ; x++){
    for (var k = 0 ; k < arr2.length ; k++){
        if (newArr[x] === arr2[k]) {
          controlador = 0;
          break;
        } else controlador = arr2[x];
    }
    if (controlador != 0){
      newArr.push(controlador)
    }
  }
 
  
  return newArr;
}

diff([1, 2, 3, 5], [1, 2, 3, 4, 5]);

Challenge http://freecodecamp.com/challenges/bonfire-diff-two-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by iTypeSlow** [comment]
Hello mhbm, How did you test your code to check it's validity?
