### ISSUE TITLE
You have to press the "Run Code" button twice to advance

### ISSUE THREAD

**Issue by LegitStudent** [FreeCodeCamp/FreeCodeCamp#2772]
Challenge http://www.freecodecamp.com/challenges/waypoint-iterate-over-arrays-with-map has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Even though the assertions are right, you need to hit the run code button twice to advance in the waypoints in the "Object Oriented and Functional Programming" section. It isn't really  a major issue, just a mild annoyance.

**Comment by 4mifix** [comment]
@LegitStudent  I started this Waypoint section this week and found having to hit the <button>Run code (ctrl + enter)</button> twice as a pain. Not a complaint just an annoyance as stated by @LegitStudent

**Comment by bugron** [comment]
I've just started Basic JavaScript section and I experience this too.

**Comment by 4mifix** [comment]
The first click tests the code and the second records your points and gives you credit.

**Comment by supercuteboy** [comment]
I'm running freecodecamp in an environment of pretty bad internet, and for me it is pretty painful and feels very wasteful having to click 2 times to advance. #2836 
#### My suggestion:
I think in most cases people want to go ahead with the lessons and in just a few cases, people would want to go back to the last lesson to review the code. (I'm limiting this comment for the beginner html and css chapter, as I haven't progressed further than that yet. Maybe it stays true for the whole content, that in most cases people want to progress to the next lesson once "correct")
* When you click "Run code" and the code is accepted as correct, jump to the next lesson right away, without delay or any further need for clicking. (There could be a pop up for 0.5 seconds saying "Good job !!!" once the new page has loaded, and fading away while already being able to read the text on the left)
* Add a "Review code for last waypoint" link for people to go back to the old lesson, with the code that they have submitted being displayed.

**Comment by BerkeleyTrue** [comment]
> feels very wasteful having to click 2 times to advance.

> This a regression due to patching used to solve several other issues. We would never intent to have a user click a button twice for no reason.

**Comment by stx146** [comment]
Building on simonkrausgit 's solution:
How about having a drop-down menu of the sections on-hover? (mockup images included) You might need to go back to a much old lesson to recall some commands (ie: when working with Bootstrap after just finishing HTML/CSS). The drop-down menu can make it easier to access these lessons.
(This might affect performance on some computers though; any thoughts?)

Mockups:
Actual Mockup:
![freecodecamp map menu explained](https://cloud.githubusercontent.com/assets/5562153/9675729/7460191c-528f-11e5-88d0-3d98ceb38f20.jpg)
Mockup Explained:
![freecodecamp map menu](https://cloud.githubusercontent.com/assets/5562153/9675730/74607cf4-528f-11e5-8f7d-9d53e8cb4faa.jpg)

**Comment by QuincyLarson** [comment]
@stx146 Thank you for posting these mockups. I am not personally a fan of dropdown menus. I prefer the full screen Map view. We do plan to re-implement the learn button which will basically take you to whichever challenge you should be doing next.

**Comment by stx146** [comment]
That sounds good; thanks :D 
(Btw, is there a reason why you don't prefer drop-down menus? Curious from a design perspective :) )
