### ISSUE TITLE
Testing for wrong number of characters

### ISSUE THREAD

**Issue by reitmanj** [FreeCodeCamp/FreeCodeCamp#2773]
Challenge http://www.freecodecamp.com/challenges/waypoint-invert-regular-expression-matches-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The variable `testString` contains 36 non-space characters. The test asserts 49 non-space characters. 
![screen shot 2015-08-27 at 8 59 00 am](https://cloud.githubusercontent.com/assets/9022594/9522659/71e11488-4c9b-11e5-907a-5fd4b0788f15.png)

The test can be passed by inserting extra characters in the variable `testString`.
![screen shot 2015-08-27 at 8 59 41 am](https://cloud.githubusercontent.com/assets/9022594/9522742/e1feaed8-4c9b-11e5-8feb-dff9514cf065.png)

**Comment by bugron** [comment]
@reitmanj thanks for posting this issue!
Try to [Refresh Your Browser Cache](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache) and [Clear Your Browser's Local Storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser%27s-Local-Storage).

Please review the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.

**Comment by benschenker** [comment]
Closing as stale, please reopen if the issue persists.
