### ISSUE TITLE
Won't move on to next waypoint

### ISSUE THREAD

**Issue by ewreck** [FreeCodeCamp/FreeCodeCamp#2775]
Challenge http://www.freecodecamp.com/challenges/waypoint-responsively-style-checkboxes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Code is complete - confirmed with green check markers under "objectives" section.  However both clicking ctrl + enter and clicking on the actual "run code" box don't take you to the next waypoint.

**Comment by benmcmahon100** [comment]
What browser are you in?

**Comment by ewreck** [comment]
I was using Chrome Version 44.0.2403.156 (64-bit)

**Comment by ewreck** [comment]
Tried it again today and it worked.  Thanks!

**Comment by benmcmahon100** [comment]
Awesome!
