### ISSUE TITLE
Minor Wording in 'Use Hex Code to Color Elements Red'

### ISSUE THREAD

**Issue by amyevans** [FreeCodeCamp/FreeCodeCamp#2779]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-hex-code-to-color-elements-red has an issue. 

In the sentence: "16 colors and 6 positions means we have 16 to the 6th power, or more than 16 million possible colors," it would be more accurate to say "16 values" instead of "16 colors."

**Comment by abhisekp** [comment]
@amyevans You're right. It should be "16 values".

And I guess in the first para,
> You may be wondering why we use **6 digits** to represent a color instead of just one or two. The answer is that using **6 digits** gives us a huge variety.

It should be **"6 characters"** or **"6 positions"** instead of "6 digits".


cc: @QuincyLarson @benmcmahon100
