### ISSUE TITLE
Challenge description unclear.

### ISSUE THREAD

**Issue by the13thdev** [FreeCodeCamp/FreeCodeCamp#2780]
Challenge http://freecodecamp.com/challenges/waypoint-target-even-numbered-elements-using-jquery has an issue. **The challenge description does not specify the class** for which we need to select even  numbered elements. It **currently says** :"*Try selecting __all the even-numbered elements__ - that is, what your browser will consider even-numbered elements - and giving them the classes of animated and shake.*" It **should actually say**: "*Try selecting __all the even-numbered elements with class target__ - that is, what your browser will consider even-numbered elements - and giving them the classes of animated and shake.*"
![screenshot 2015-08-27 23 32 56](https://cloud.githubusercontent.com/assets/13356152/9528831/7412f2d4-4d14-11e5-896c-88c5bf4c9708.png)

**Comment by Mansuro** [comment]
IMHO, it is clear in the context that the class target is the one that needs to be modified

**Comment by abhisekp** [comment]
@the13thdev Please close this issue if it has been resolved.
