### ISSUE TITLE
Meet Bonfire: All about the algorithm.

### ISSUE THREAD

**Issue by TrishSnyder** [FreeCodeCamp/FreeCodeCamp#2782]
Challenge http://freecodecamp.com/challenges/bonfire-meet-bonfire has an issue. 

I suggest there be a waypoint before the first bonfire that discusses algorithms and how to write them. The title of this section is Basic Algorithm Scripting, but there is nothing about writing algorithms.

**Comment by abhisekp** [comment]
@TrishSnyder You are correct. There must be some waypoint that talks about algorithms in general.

cc: @benmcmahon100

**Comment by benmcmahon100** [comment]
The copy has been changed so that it no longer mentions algorithms. It now just introduces to the concept of bonfires.
