### ISSUE TITLE
I can't move on past this page

### ISSUE THREAD

**Issue by JoshWinnes** [FreeCodeCamp/FreeCodeCamp#2783]
Challenge http://freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I am working on this Waypoint and normally there are red x's that turn green when you finish a task but there are no tasks or red x's on my waypoint.

**Comment by junhaoyap** [comment]
@JoshWinnes try "ctrl + enter" and see if they appear, I think FreeCodeCamp recently changed it to not show until it's been run at least once.
