### ISSUE TITLE
Replace instances of `return(someVal)` with `return someVal`

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#2784]
Some challenges incorrectly depict `return` as a function call. While `return(val)` does evaluate correctly, it is not because `return` can be called as a function. These should be changed to eliminate the parentheses and add a space between the value being returned and the return keyword.

All keywords must be separated by a space after itself.

**Comment by BerkeleyTrue** [comment]
example: 
![waypoint__iterate_over_arrays_with_map___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/9530003/441a6b3c-4cb2-11e5-9ded-525d7d87a44d.png)

**Comment by ahstro** [comment]
I can get on this as I've been moderately annoyed about it ;) Shouldn't be too hard with a `sed` call or two.

**Comment by BerkeleyTrue** [comment]
@ahstro Thanks!

**Comment by ahstro** [comment]
Pray for regex magic. :pray:
