### ISSUE TITLE
The last test won't pass even though the three li's are closed

### ISSUE THREAD

**Issue by erikiva** [FreeCodeCamp/FreeCodeCamp#2791]
<img width="983" alt="screen shot 2015-08-27 at 23 07 53" src="https://cloud.githubusercontent.com/assets/13215331/9533172/92f6c0f8-4d10-11e5-9d5f-42d2c99f1ba3.png">
Challenge http://freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by Mansuro** [comment]
The challenge is asking you to create an unordered list of three things cat love, so you should remove the two paragraph elements with an unordered list. However, this remains an issue as all the li's are closed but the challenge doesn't pass

**Comment by benschenker** [comment]
@AryanJ-NYC Are you referring to the regex inside the freecodecamp tests?  Those are actually inside strings and backslashes need to be escaped inside string so 
```
/<\\/li>/g
```
inside a string will translate to 
```
/<\/li>/g
```

**Comment by Kiran-Vemuri** [comment]
+1
