### ISSUE TITLE
Clicking the buttons on pop ups too quickly closes the pop up

### ISSUE THREAD

**Issue by prykor** [FreeCodeCamp/FreeCodeCamp#2792]
![bug](https://cloud.githubusercontent.com/assets/13267481/9533462/22f626c0-4cc7-11e5-9de0-e4607798a4fb.PNG)

When finishing a Waypoint, after clicking "run code" and moving my cursor to the "submit" button on the pop up window, I noticed that a lot of the time when I click submit it just closes the pop up instead of submitting it, so then I have to click "run code" again, then "submit". I figured out that if my cursor is over the submit button before the pop up is done loading, my cursor stays the arrow shape and not the finger shape you would get when hovering a link. 

All in all this isn't a huge deal, just something I observed and thought you might want to know about!

Thanks,

Daniel Creutz

Daniel.l.creutz@gmail.com

**Comment by BerkeleyTrue** [comment]
This could probably be fixed by adding focus to the button on pop up using jQuery.

**Comment by AEA2002** [comment]
@BerkeleyTrue  What file would that be in?

**Comment by BerkeleyTrue** [comment]
I believe this may have been fixed. Please try out beta.freecodecamp.com and report whether this is an issue still.

**Comment by mazer-rakham** [comment]
Can we add focus and type="submit" so that we can just hit enter instead of clicking with mouse?

**Comment by AEA2002** [comment]
@BerkeleyTrue Thanks, could you tell me where I can find it for future reference?

**Comment by BerkeleyTrue** [comment]
Its in client/commonFrame.js

**Comment by AEA2002** [comment]
@BerkeleyTrue Thanks, again.:smiley:
