### ISSUE TITLE
Need more assertion examples

### ISSUE THREAD

**Issue by HexORSist** [FreeCodeCamp/FreeCodeCamp#2793]
Challenge http://www.freecodecamp.com/challenges/bonfire-where-art-thou has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

There are not enough assertion examples for someone to understand what they're supposed to do.

**Comment by abhisekp** [comment]
@bugron please close this issue as #1756 resolves this issue.

@HexORSist Thanks.

**Comment by bugron** [comment]
@HexORSist thanks for posting this issue!
Closing this issue as the PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/1756 is merged.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
