### ISSUE TITLE
Waypoint: Nest an Anchor Element within a Paragraph

### ISSUE THREAD

**Issue by psaradhi** [FreeCodeCamp/FreeCodeCamp#2794]
Challenge http://freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I used  the following.

<p>click here for <a href="http://catphotoapp.com">cat photos</a></p>

But, freecodecamp says my answer has the following error:

**Your a element should be nested within your new p element.**

**Comment by Mansuro** [comment]
You need to paste your code, the way you've written it isn't displaying how you've written your code in the challenge.

**Comment by shaikhatik0786** [comment]
@psaradhi well, the error says it all. the "a" should come inside the "p" tag.

So probably it should be <p><a href="#"></a></p>

Example: 

<p> This is a <a href="http://www.yoursite.com">link</a></p>

P.S. : I am not gonna put the exact ans of the problem you are facing, it spoils the fun of solving the code on FCC. You should get the idea of your error. Still if you don't get it, post back here. I'll post the complete ans.

Best of luck. :+1:

**Comment by CuMoose** [comment]
I am having the same problem.

![screen shot 2015-08-29 at 2 45 51 pm](https://cloud.githubusercontent.com/assets/13509797/9563995/fafdeaee-4e5c-11e5-945a-ed15a7449d5f.png)

I have tried different variations but with no luck.

**Comment by shaikhatik0786** [comment]
@CuMoose 

```
<p>Click here for <a href="http://www.freecatphotoapp.com"> cat photos</a></p>
```

**Comment by CuMoose** [comment]
@shaikhatik0786 

Thank you. I thought I had tried that earlier but I guess not.

**Comment by shaikhatik0786** [comment]
@CuMoose no probs, just happy to be helpful

**Comment by dloret** [comment]
For any people visiting this page, the error is perhaps not related to the nesting in itself but to the url to the CatPhotoApp...
My wrong tags (but correctly nested):
<p>Click here for <a href="http://freecatphotoapp.com">cat photos</a></p>

The correction proposed above:
<p>Click here for <a href="http://www.freecatphotoapp.com"> cat photos</a></p>

**Comment by MollyOwl27** [comment]
Thanks so much @dloret ! That was my problem and the only error read that I wasn't nesting properly. Saved my sanity ;)

**Comment by rockie667** [comment]
Just in case anybody else faces the same problem. For me the order of the three paragraphs was important: the one with the link has to be the first one.

**Comment by kellymccain140** [comment]
Hi all,

Per rockie667, I placed the link paragraph first and still getting an error.  Can anyone offer any other suggestion?  The only one that I have checked off as an error is "Your p element should have the text "View more " (with a space after it) and it does, but...

![fcc error](https://cloud.githubusercontent.com/assets/16712668/12666254/9484da50-c604-11e5-82aa-83bad652e556.PNG)

**Comment by ltegman** [comment]
@kellymccain140 Github issues are not for challenge help. Please visit the [Help Chat](https://gitter.im/FreeCodeCamp/Help) for assistance. Thanks and happy coding!

**Comment by kellymccain140** [comment]
ok

**Comment by frolovdjd** [comment]
HEy guys. 
Works well if you simply enclose existing a element in p element 
can pm example

**Comment by xiaji2** [comment]
Is there anybody able to help me with Nest an Anchor Element within a Paragraph?

Thanks!

**Comment by xiaji2** [comment]
Help!

**Comment by rohangowthami** [comment]
<h2><p>view more <a href="http://www.freecatphotoapp.com">cat photos</a></p>

**Comment by akashramesh13** [comment]
Here is the code that works:


<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<p>View More 
  <a href="http://www.freecatphotoapp.com">cat photos</a></p>
<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by akashramesh13** [comment]
Here is the code that worked:
```

<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<p>View More 
  <a href="http://www.freecatphotoapp.com">cat photos</a></p>
<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back. ">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by texas2010** [comment]
@akashramesh13 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by Harrynotwizard** [comment]
I finally solve it! thanks 👍

**Comment by jinchang1994** [comment]
Fuck this mod guy you guys are bitches
