### ISSUE TITLE
typo: represent instead of represents

### ISSUE THREAD

**Issue by andreagoulet** [FreeCodeCamp/FreeCodeCamp#2795]
Challenge http://www.freecodecamp.com/challenges/waypoint-build-javascript-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The instructions currently state: "Objects are useful for storing data in a structured way, and can *represents* real world objects, like a cats."

It should be *represent* instead of *represents*.

**Comment by dokkillo** [comment]
Ok I will Fix it :)

**Comment by benschenker** [comment]
Hey @andreagoulet, it looks like this has been fixed, 
Thanks for reporting the issue!
