### ISSUE TITLE
Sequence of numbers in a set

### ISSUE THREAD

**Issue by carnivean** [FreeCodeCamp/FreeCodeCamp#2797]
Challenge http://freecodecamp.com/challenges/bonfire-symmetric-difference has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The deepEqual test for the array needs the numbers in the same sequence, but for a set of numbers, the sequence doesn't matter. My solution was getting the right answer in the wrong order, so it didn't count. In the end I had to hack my solution so that it changed the order of the numbers, which is extremly bad style....

Maybe make more than one deepEqual test one for every possible permutation of the numbers and it is correct if one of the deepEqual tests is correct?

**Comment by dmytroyarmak** [comment]
I agree that order of numbers in answer shouldn't matter. I'll try to fix this issue.
