### ISSUE TITLE
aypoint-build-javascript-objects: 'run code' issue

### ISSUE THREAD

**Issue by JamesdashTaylor** [FreeCodeCamp/FreeCodeCamp#2799]
Challenge http://www.freecodecamp.com/challenges/waypoint-build-javascript-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I can't move on from the above - the code is validated but the next waypoint doesn't load. Please see screenshot.
<img width="744" alt="waypoint-build-javascript-objects" src="https://cloud.githubusercontent.com/assets/10012353/9540933/7c09025c-4d5b-11e5-8e9e-ab6ae97bde9c.png">

**Comment by benschenker** [comment]
Hey @JamesdashTaylor thanks for posting!

When I run that code it does not pass all tests.  One failing test:
>myDog should contain the property friends and it should be an array

This should make it clear how to fix your code!  Reopen this (or post on [gitter](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter)) if you still cannot complete this challenge.
