### ISSUE TITLE
Bad condition for succeed - bug

### ISSUE THREAD

**Issue by Harpner** [FreeCodeCamp/FreeCodeCamp#2803]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-conditional-logic-with-ifelse-statements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

"Create an if-else statement to return heads if the flip var is zero, or else return tails if it's not."

The condition is exactly opposite. If the flip var is zero, it has to return "tails" for the test to succeed.

![flip-tails-heads](https://cloud.githubusercontent.com/assets/4094780/9545789/43405d6c-4d8d-11e5-942b-5117d48abe19.png)

**Comment by Mansuro** [comment]
It works both ways

**Comment by bugron** [comment]
@Harpner thanks for posting this issue!
I've just opened a PR which fixes this issue. Thank you for your contribution!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
