### ISSUE TITLE
On Loading of all tutorials

### ISSUE THREAD

**Issue by Justintlai** [FreeCodeCamp/FreeCodeCamp#2804]
Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-pop has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Everytime I load into a screen I cannot edit the text-editor on any of the pages. I must always hit the "Run-Code" button before I am able to type in the text editor. 

hope you can replicate this too and fix it.

I am working in Chrome - windows 7

**Comment by benschenker** [comment]
Hey @Justintlai thanks for posting!

Is this still an issue for you?  Could you post a screenshot?

**Comment by awesomeaniruddh** [comment]
Closing this for now. OP is welcome to reopen the issue with more details regarding it.

**Comment by Justintlai** [comment]
Sorry only just saw this. Yes its patial solve depending on the tutorials. Difficult to post a screenshot since nothing visually changes. The cursor still appears in the Text-editor but just doesn't type anything unless I "Run-Code" to refresh everything.

**Comment by benschenker** [comment]
Hey @Justintlai could you try opening the Chrome Developer Console when you next experience this issue and paste in any errors you see there?
