### ISSUE TITLE
Broken link of "Get a Hint" in certificate of "Api and Microservices"

### ISSUE THREAD

**Issue by ows-ali** [freeCodeCamp/freeCodeCamp#28059]
**Describe your problem and how to reproduce it:**
A broken link to .env guide page on Certification of "Api and Microservices", question "Use the .env file". 
Clicking on 'Get a Hint'  takes to this link (which is broken):
https://guide.freecodecamp.org/certifications/apis-and-microservices/basic-node-and-express/use-the--env-file
(Already present file could be renamed for this link to work properly.)

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/apis-and-microservices/basic-node-and-express/use-the--env-file/

**Tell us about your browser and operating system:**
* Browser Name: Chrome/any
* Browser Version: 69.0.3497.100/any
* Operating System: Windows/any

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/16830711/47447445-f64cc680-d7d6-11e8-870c-968dce634c50.png)

**Comment by RandellDawson** [comment]
@ezioda004 Can I close this with reference to PR #28069?

**Comment by ows-ali** [comment]
> @ezioda004 Can I close this with reference to PR #28069?

@RandellDawson the PR you mentioned above reolves issue for one language only, however my PR is fixing paths for other files as well.

**Comment by SinanKamil** [comment]
It is a badge in the program that is causing the website to crash!

**Comment by RandellDawson** [comment]
@SinanKamil Not sure what you are referring to.  What badge?

**Comment by SinanKamil** [comment]
I think the way the program was set up made it crash!

**Comment by ows-ali** [comment]
@RandellDawson  I think @SinanKamil is referring the 'Get a Hint' button as badge. I assume that he is saying that this button should redirect to the url with '.env' and not '-env' like this:
https://learn.freecodecamp.org/apis-and-microservices/basic-node-and-express/use-the.-env-file/
But this will not work as a url and won't follow the convention too

**Comment by jagzmz** [comment]
Link still broken
