### ISSUE TITLE
type or copy-paste src element and run code and doesn't show it completed correctly

### ISSUE THREAD

**Issue by ilee300** [FreeCodeCamp/FreeCodeCamp#2806]
Challenge http://www.freecodecamp.com/challenges/waypoint-make-images-mobile-responsive has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Copy-paste or type directly the source uri and doesn't recognize completion of challenge. Similar issue with nesting link in p element.

**Comment by benschenker** [comment]
Hey @ilee300 thanks for posting.

I'm having trouble understanding/replicating this issue, check out our [Bug Reporting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) for some tips on submitting issues.

I'm going to close this for now, but feel free to reopen after completing the above steps.
