### ISSUE TITLE
no instruction on Waypoint: Iterate over Arrays with map

### ISSUE THREAD

**Issue by scutdk** [FreeCodeCamp/FreeCodeCamp#2807]
Challenge http://www.freecodecamp.com/challenges/waypoint-iterate-over-arrays-with-map has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

>The map method is one of the easiest ways to iterate through an array or object there is. Let's use it now.

There's no instruction on what need to be implemented. Only when you submit the code, it will tell you that you need to map a add function.

**Comment by awesomeaniruddh** [comment]
The next line is "Use the map function to add 3 to every value in the variable array". Is that not clear enough?

**Comment by scutdk** [comment]
I didn't see that when I submitted this issue. But it's there now. Maybe I  just didn't see it.
