### ISSUE TITLE
Disappearing Instructions

### ISSUE THREAD

**Issue by genesisjoec** [FreeCodeCamp/FreeCodeCamp#2808]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When I typed in : 
script>
$(document).ready(function();
</script>
![errors](https://cloud.githubusercontent.com/assets/11507581/9551357/53979278-4d76-11e5-9eab-fc344b701be1.JPG)

and hit run code, the instructions disappeared and gave me the message 'Unexpected token; '

**Comment by BerkeleyTrue** [comment]
Your code has a syntax error and crashes the test suite, hence the error message.

Please complete the function declaration and rerun the test suite.

See: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-help-when-you-get-stuck

Happy Coding!
