### ISSUE TITLE
Using lower case 'world' leads to lack of 'go to next challeng' button, but displays checkmark

### ISSUE THREAD

**Issue by Canterrain** [FreeCodeCamp/FreeCodeCamp#2809]
Challenge http://www.freecodecamp.com/challenges/waypoint-say-hello-to-html-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I used word for my Hello world string and ran the code.  The check mark turned green suggesting code was good, but I did not get a 'go to next challenge' button or congrats pop up.  When I reran code with World everything worked correctly.

![hello world](https://cloud.githubusercontent.com/assets/13053825/9552131/bbc6a9d0-4d83-11e5-9af5-0b7177368664.jpg)

**Comment by Canterrain** [comment]
Update:

I'm seeing this on a lot of pages, but it's not what I thought it was at all.  Often times, the first time I run the code I see everything turn green.  But then I'm stuck.  I have to run code again to get the 'go to next page' button to pop up.  Unintuitive.  But I have a feeling unintentional since I don't always see this behavior.

**Comment by shaikhatik0786** [comment]
@Canterrain dont mind, but it looks like you just started out with HTML, then how do you already have 83points in your profile?

**Comment by Canterrain** [comment]
I had made it all the way to jquery, and got completely stuck and didn't get code academy.  Was trying to get some help, took some time off for about three weeks.  Then the great reset happen with new lessons! So I decided to start over and get refreshed on what I learned.

**Comment by shaikhatik0786** [comment]
@Canterrain Aah, I thought so, the same thing happened with me.

**Comment by bugron** [comment]
@Canterrain thanks for posting this issue!
Note that your issue is related to:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2772

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by fengjuan** [comment]
I have wrote :<h1>Hello World</h1>
but always note:$ is not defined, can not go to my next challenge
![image](https://cloud.githubusercontent.com/assets/4216889/9930093/cd9aedac-5d63-11e5-9f7e-9de1c2f9099d.png)
