### ISSUE TITLE
Problem in editor

### ISSUE THREAD

**Issue by nuronialBlock** [FreeCodeCamp/FreeCodeCamp#2810]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-block-element-bootstrap-button has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

As soon as, a new challenge appears, previous code doesn't load perfectly in editor. But, as soon as, I click on the editor it shows the full code. 
![prob_1](https://cloud.githubusercontent.com/assets/6963262/9552253/667a09cc-4dd8-11e5-84e8-03c612955646.png)
![prob_2](https://cloud.githubusercontent.com/assets/6963262/9552255/67f78db0-4dd8-11e5-99ca-3b76ea3aabea.png)

**Comment by shaikhatik0786** [comment]
@nuronialBlock yup its happening for me as well, guess some issue is going on

**Comment by bugron** [comment]
@DogCatWoof thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2707

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
