### ISSUE TITLE
Error message when moving to next challenge

### ISSUE THREAD

**Issue by Canterrain** [FreeCodeCamp/FreeCodeCamp#2811]
Challenge http://www.freecodecamp.com/challenges/waypoint-size-your-images has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Was moving forward to "Waypoint Size your Images" when I encountered error message in screenshot.  I was, much further at one point, (just started jquery) and decided to start over when new website/lessons came out.  Not sure if that contributed.

![404error](https://cloud.githubusercontent.com/assets/13053825/9552739/4dea2ed2-4d88-11e5-9c15-7fa57c8b5854.jpg)

**Comment by bugron** [comment]
@Canterrain thanks for posting this issue!
Very interesting. As I know at this moment Hikes are under construction.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by benschenker** [comment]
I am unable to replicate this.  Is it still an issue for you @Canterrain?

I will close this for now but please reopen if this is not resolved.
