### ISSUE TITLE
can't get jQuery to accept my code

### ISSUE THREAD

**Issue by robdogg13** [FreeCodeCamp/FreeCodeCamp#2813]
the program won't run my code. I can put my code in and nothing happens. I completed jQuery when it was linked to code academy but its not working through waypoint.

Challenge http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by shaikhatik0786** [comment]
@robdogg13 : there are some issues going on. Try clicking on the run code button a few times, it should work. I am in the same jQuery section, and facing the same error too.

**Comment by benschenker** [comment]
Hey @robdogg13 and @shaikhatik0786 thanks for posting.

This is working for me.  I'll close this for now, but please reopen if you still experience this issue.

**Comment by LeanieBean** [comment]
I am experiencing the same issue :(

**Comment by subodh737** [comment]
I am also experiencing the same issue. 
I have written my script tag like this:--

<script>
  $(document).ready(function() {
    $("button").addClass("animated bounce");
  });
</script>
