### ISSUE TITLE
Evaluation Issue

### ISSUE THREAD

**Issue by teomara** [FreeCodeCamp/FreeCodeCamp#2814]
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

You can still pass the test without properly setting p{font-size:16px}.
I defined font-size within .red-text and it passed.
![error1](https://cloud.githubusercontent.com/assets/5858257/9553615/e62e8392-4dc8-11e5-9be1-e3c69c0172d5.jpg)

**Comment by shaikhatik0786** [comment]
Umm, guess you only read the challenges provided and not the description properly.

![screenshot_2](https://cloud.githubusercontent.com/assets/4403762/9553917/e28b4402-4ddf-11e5-841a-cb7ab1642c9a.png)

It clearly tells you here that you can do it in the same red-text class

**Comment by teomara** [comment]
Noted. thanks

**Comment by shaikhatik0786** [comment]
@teomara sure thanks
