### ISSUE TITLE
Not showing all lines in editor

### ISSUE THREAD

**Issue by DogCatWoof** [FreeCodeCamp/FreeCodeCamp#2815]
Challenge http://freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![image](https://cloud.githubusercontent.com/assets/14015495/9553898/0f072dac-4d90-11e5-988f-0ebba95cd259.png)

When page is 1st shown, only lines 1-11 shown.  After any screen movement, it shows all the lines.

Chrome: Version 44.0.2403.157 m

**Comment by shaikhatik0786** [comment]
@DogCatWoof ya this error is getting more common, I hope they see this and solve it soon.

**Comment by bugron** [comment]
@DogCatWoof thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2707

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
