### ISSUE TITLE
Should <li  class="red-text"> be valid?

### ISSUE THREAD

**Issue by DogCatWoof** [FreeCodeCamp/FreeCodeCamp#2816]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Replaced my &lt;p  class="red-text"&gt; with &lt;li  class="red-text"&gt;.  It didn't like that and said it was missing closing &lt;/li&gt;

**Comment by shaikhatik0786** [comment]
@DogCatWoof use ``` for codes or else they wont get displayed here.

**Comment by shaikhatik0786** [comment]
@DogCatWoof you only need to add these 5 lines

```<ul>
  <li></li>
  <li></li>
  <li></li>
</ul>```

the ul tag and three li tags inside

**Comment by bugron** [comment]
@DogCatWoof thanks for posting this issue!
Instructions of the challenge are very clear and @shaikhatik0786 gave you the right answer.
@BerkeleyTrue seems this issue can be closed, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
