### ISSUE TITLE
Error in the code evaluation system

### ISSUE THREAD

**Issue by shaikhatik0786** [FreeCodeCamp/FreeCodeCamp#2817]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-even-numbered-elements-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Well, I had to add the "animeted shake" class to an even elements
(Note : only elements #target1(no.1) & #target5(no. 3) & #target6(no. 5)
I did a type error, see the screen
![screenshot_3](https://cloud.githubusercontent.com/assets/4403762/9554012/88ccdde4-4de0-11e5-828a-e8b792885bff.png)

1) I made the type error in "animated" as "animted" still it shows the code is correct
2) Even though I made an error in the script, it still shakes the element no #target6 
3) I have selected even nos, but still as I mentioned above it selects and shakes all odd nos (1,3,5)

**Comment by benschenker** [comment]
Hey @shaikhatik0786 thanks for posting this issue!

I cannot replicate 1.  It may have been fixed.

As far as 2 and 3, this is actually the desired result.  See the documentation for [:even](https://api.jquery.com/even-selector/), specifically:
>In particular, note that the 0-based indexing means that, counter-intuitively, :even selects the first element, third element, and so on within the matched set.
