### ISSUE TITLE
bug Basic Javascript 30

### ISSUE THREAD

**Issue by Rudeclis** [FreeCodeCamp/FreeCodeCamp#2819]
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I typed in return(Math.floor(Math.random()*10));
without the *10, to figure out exactly what Math.floor does  (I'm still not sure) and I still cleared the waypoint, Eventhough that's not what you're supposed to do.

**Comment by bugron** [comment]
@Rudeclis thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2256

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
