### ISSUE TITLE
instructions issue

### ISSUE THREAD

**Issue by Nathan-Wind** [FreeCodeCamp/FreeCodeCamp#2824]
Challenge http://www.freecodecamp.com/challenges/waypoint-remove-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

the instructions are not compelete

**Comment by bugron** [comment]
@Nathan-Wind thanks for posting this issue!
There is a merged pull request https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2734 which clarifies instructions of this challenge. Hopefully if will be in production soon.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
