### ISSUE TITLE
Cannot find anchor text in cat photos

### ISSUE THREAD

**Issue by madhusudan1** [FreeCodeCamp/FreeCodeCamp#2829]
Challenge http://freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Its not clear what does it mean please be clear.
What is the anchor text in cat photos?
If I find the text, should it go within opening and closing tags like this:
<a href="http://catphotoapp.com">Anchor Text</a>
Your a element should have the anchor text of "cat photos"

**Comment by madhusudan1** [comment]
Found other people posted this same question within chat on help page.

**Comment by BerkeleyTrue** [comment]
The anchor(html `a` element) text is the text that is within the opening and closing anchor tags.

Does that answer your question?
