### ISSUE TITLE
Inconsistent wording in first waypoint's instructions

### ISSUE THREAD

**Issue by dawnvoh** [FreeCodeCamp/FreeCodeCamp#2830]
Challenge http://freecodecamp.com/challenges/waypoint-say-hello-to-html-elements has an issue. 

The text for the first HTML waypoint references a "Go to my next challenge" button.  With the new rollout, "Go to my next challenge" appears to have been replaced with a "Submit" button. (And, pressing "Submit" automatically advances the user to the next challenge.) I suggest updating the text, or re-renaming the button.

p.s. I have to press the "Run code" button twice to receive the success message and "Submit" button, but that issue is already open.
p.p.s. I love the fact that our code is saved now. (I came back to this waypoint simply to see if my old code was there and/or my new code would be saved.) Thanks for all of your work!

![firstwaypoint](https://cloud.githubusercontent.com/assets/8917154/9559717/1c67c584-4dc6-11e5-89c1-02c76b5acb22.jpg)

**Comment by bugron** [comment]
@dawnvoh thanks for posting this issue!
Closing this issue because https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2903 is merged. @jameskopacz thanks for fixing this..

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
