### ISSUE TITLE
Incorrect text on module

### ISSUE THREAD

**Issue by elattanzio** [FreeCodeCamp/FreeCodeCamp#2831]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

You say to select #target6 in the top section but down below you then say #target3. #target3 is the correct div when compiling the code. Screen shot attached. 
<img width="1203" alt="screen shot 2015-08-28 at 6 08 17 pm" src="https://cloud.githubusercontent.com/assets/7574806/9559816/f155f912-4daf-11e5-9b85-f0856d84a856.png">

**Comment by bugron** [comment]
@elattanzio thanks for posting this issue!
>First target your button element with the id target3 by using the $("#target3") selector.
>Then use jQuery's .addClass() function to add the classes animated and fadeOut.

So your code should be, as you mentioned, `$("#target3").addClass("animated faseOut");`
Note that instructions don't tell you to **select** element with `target6` ID.
>Here's how you'd make the button element with the id target6 fade out: $("#target6").addClass("animated fadeOut").

This is just an **example** how to make the button element with the id target6 fade out and that's all.

@BerkeleyTrue if @elattanzio is satisfied with my answer this issue can be closed, thanks.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
