### ISSUE TITLE
Typo on this page.

### ISSUE THREAD

**Issue by elattanzio** [FreeCodeCamp/FreeCodeCamp#2832]
Challenge http://www.freecodecamp.com/challenges/waypoint-delete-your-jquery-functions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Screenshot attached.
![screen_shot_2015-08-28_at_6_10_31_pm](https://cloud.githubusercontent.com/assets/7574806/9559822/407a3454-4db0-11e5-9366-72eb37b4936e.jpg)

**Comment by bugron** [comment]
@elattanzio thank you so much for pointing this issue!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by natac13** [comment]
I created a pull request for removing the double "your". I did not change the back-slash because the linter did not like it and I was not confident enough as this would be my first pull request!

**Comment by bugron** [comment]
@natac13 thanks for posting this issue!
Great! Would you mind to delete that backslash on which points the red arrow too, thanks?

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by natac13** [comment]
@bugron After figuring out how to run FCC locally with mongdb and gulp crash courses I have submitted a PR to remove the extra back slash!
