### ISSUE TITLE
Reset Button

### ISSUE THREAD

**Issue by irmattg** [FreeCodeCamp/FreeCodeCamp#2833]
Challenge http://freecodecamp.com/challenges/waypoint-target-elements-by-class-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I write the code and if I accidentally erased a line and I want to reset my code, I click on the "Reset" button and it asks if I would like to return my editor to its original state. When I do that nothing happens. The code remains the same and the challenge isn't restarted.

**Comment by bugron** [comment]
@irmattg thanks for posting this issue!
That button worked for me.
See my [comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2773#issuecomment-135506542).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by BerkeleyTrue** [comment]
Hello @irmattg,

Can you post screenshots?

**Comment by benschenker** [comment]
Closing as stale, please reopen if the issue is not resolved (and post the screenshots).
