### ISSUE TITLE
Lesson will not allow to progress after it is completed

### ISSUE THREAD

**Issue by w00dStok** [FreeCodeCamp/FreeCodeCamp#2834]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

1) Load the page (it should have the previous lesson's code still in it)
2) Delete the style from the h2 element
3) Add the style block
4) Add h2 { color: red; }
5) Click either run or Ctrl + Enter

It will show you have completed it correctly, but the pop-up does not show to allow you to progress to the next lesson.

![image](https://cloud.githubusercontent.com/assets/4142474/9560040/2123680c-4dc7-11e5-9a93-61c26e477d04.png)

**Comment by bugron** [comment]
@w00dStok thanks for posting this issue!
In order to proceed to next challenge you either need to click on Run code button twice or press Ctrl + Enter twice.
Related to: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2772 and https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2659.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by w00dStok** [comment]
I did. It didn't matter. It was completely stuck. It happened on a few other lessons as well.

**Comment by BerkeleyTrue** [comment]
@w00dStok Which browser are you using?

**Comment by w00dStok** [comment]
Chrome

**Comment by jmanders85** [comment]
I have the same problem also using Chrome.  If I click on the "run" button, it will tell me I succeeded but won't submit.  If I click on the coding area and then ctrl+enter it seems to work.  The key is having your cursor in the coding area I guess.

**Comment by w00dStok** [comment]
I have tested your work around and it seems to not work for me. This issue is also happening in "Change the Font Size of an Element".

**Comment by w00dStok** [comment]
Just on a hunch I tested this in other browsers getting the same issue. I have tried in Edge, Firefox, and Chrome with the same result.

**Comment by jameskopacz** [comment]
This looks like an error in the way point itself.

The instructions say to use red but the test is checking for blue.

https://github.com/FreeCodeCamp/FreeCodeCamp/blob/717c56edb7bd07194328b97fa513690fc6807091/seed/challenges/html5-and-css.json#L385

Just to double check, @w00dStok what happens if you use this code:
```
<style>
   h2 { color: blue; }
</style>
<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
```

**Comment by bugron** [comment]
@jameskopacz  the only instruction in this challenge's description section which asks to change any color is:
>Delete your h2 element's style attribute and instead create a CSS style element. Add the necessary CSS to turn all h2 elements **blue**.

And this text is from tests' section:

>Your h2 element should be **blue**.

Everything that relates to **red** color here is just an **example** i.e.:

>When you entered `<h2 style="color: red">CatPhotoApp</h2>`, you were giving that individual h2 element an inline style.

and

>Inside that style element, you can create a CSS selector for all h2 elements. **For example**, if you wanted all h2 elements to be red, your style element would look like this: <style>h2 {color: red;}</style>.

**Comment by w00dStok** [comment]
I changed it to blue and it now allowed me to pass the waypoint.

@bugron My apologies. I obviously missed that instruction.

**Comment by bugron** [comment]
@w00dStok That's OK. You can now close this issue if you solved your problem, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by JenFanz** [comment]
I've tried it with red and blue and cannot get past this point. I've also tried running it twice using both methods.

**Comment by Lucala2016** [comment]
I have same issue here. Tried everything.
although the h2 color is as requested, blue, cannot pass this challenge.
Please, Help.
Thanks

**Comment by abhi0111** [comment]
Use this
h2 {
    font-family: Lobster;
  }

**Comment by leeteesian** [comment]
Finally i found that the colon after font-family should not have space.
font-family: Lobster; is working.
font-family : Lobster; is not working.

**Comment by ninjacoder12** [comment]
Finally i did by disabling my dark mode 
i guess you all should disable dark mode extension in your brouser during css test
