### ISSUE TITLE
Misleading definition of \s regex

### ISSUE THREAD

**Issue by AKWintermute** [FreeCodeCamp/FreeCodeCamp#2838]
Challenge http://www.freecodecamp.com/challenges/waypoint-find-white-space-with-regular-expressions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

\s - captures much more than spaces as the lesson implies, a better description that talks about what characters white space, as the title hints at, includes should be used.

**Comment by benschenker** [comment]
Thanks @AKWintermute for pointing this out.  I agree, feel free to [submit a PR](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute) for this.
