### ISSUE TITLE
Run code doesnt work for jQuery script tag. 

### ISSUE THREAD

**Issue by vraoot** [FreeCodeCamp/FreeCodeCamp#2839]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
Just added the following lines of code at the beginning of the file as instructed by the challenge steps:
<script>
 $(document).ready(function() {
 });
</script>

After this when I hit the "Run Code" button,  I don't see any results- nor fail nor pass. the challenge steps below the 'Reset' 'Help' 'Bug' line are not visible as well.
![error](https://cloud.githubusercontent.com/assets/13652812/9560766/ee8a2de4-4ddb-11e5-9dce-0315bd9fef8e.JPG)

**Comment by bugron** [comment]
@vraoot thanks for posting this issue!
I've just passed the test with your code without any problems.See my [comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2773#issuecomment-135506542), it might help you.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by vraoot** [comment]
thanks- I tried those options in IE but it doesn't work. I found that Chrome works perfectly fine. - so going with that at the moment :)..thanks for your response!
brVikas 


     On Friday, August 28, 2015 11:31 PM, Arsen Melikyan <notifications@github.com> wrote:
   

 @vraoot thanks for posting this issue!
I've just passed the test with your code without any problems.See my comment, it might help you.
Please review the Guidelines for Contributing, thank you!.

**Comment by bugron** [comment]
@vraoot you're welcome. IE is the most inappropriate browser for passing through FCC challenges. Also if your problem is solved, feel free to close this issue, thanks.
