### ISSUE TITLE
Check list disappearing, can't Submit code

### ISSUE THREAD

**Issue by giant995** [FreeCodeCamp/FreeCodeCamp#2840]
Challenge http://freecodecamp.com/challenges/waypoint-make-dead-links-using-the-hash-symbol has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When I entered my # in the href, the check list disappeared and I can't submit my code and do the next challenge.

**Comment by shaikhatik0786** [comment]
@giant995 :could you provide a screenshot for the same

**Comment by alan1001110** [comment]
Works fine for me, but I also can't submit code, press buttons, etc if I re-size my chrome browser window much smaller than full-screen

**Comment by despinam** [comment]
Good evening,
i have an issue to fulfill this lesson.  Although I had replaced the a element's attribute href with the hash symbol #, I cannot continue.  Please see the attached screenshot.
Thank you
![issue_dead_link](https://cloud.githubusercontent.com/assets/15333740/10830790/53031662-7e8a-11e5-8169-44ddc3ef856c.jpg)

**Comment by despinam** [comment]
No worries!!! I have just found the solution.  When it says "Replace your a element's href attribute with a #, it means replace the link with #.
For instance:
<a href="#">cat photos</a>
I saw it in the following lesson.
