### ISSUE TITLE
Nesting an 'a' element in a 'p' element. 

### ISSUE THREAD

**Issue by rinyfo4** [FreeCodeCamp/FreeCodeCamp#2841]
Challenge http://freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph has an issue. The challenge requires that we nest an a element in a p element. It's not working and I'm sure I have done it right. 

This is the snippet that apparently doesn't work: 

    <p>click here for
        <a href="freecatphotoapp.com">cat photos</a>.
     </p>

It is saying that I need to add an a element in the p element. Which i have done. 

Thanks a lot

**Comment by shaikhatik0786** [comment]
@rinyfo4 it would be better if you provide the code, or a screenshot.
Coz according to you, you have done it right. But we need to have a look too.

**Comment by rinyfo4** [comment]
Hey, just updated it. Sorry about that. I'm pretty sure this part is enough but i'm not sure how and where to post all the code... Thanks in advance...

**Comment by shaikhatik0786** [comment]
@rinyfo4 the problem is with your link, the description says you to enter http:www.freecatphotoapp.com
and you entered only freecatphotoapp.com. So it gives you error. Do it this way

```
<p>click here for <a href="http://www.freecatphotoapp.com">cat photos</a></p>
```

**Comment by rinyfo4** [comment]
Stupid errors... Thanks a lot!

**Comment by KhalilNiser** [comment]
Can someone tell me why this code is not executing at all, what is it I'm doing wrong, please? <p>click here for <a href="https://www.freecatphotoapp.com">cat photos</a></p>

**Comment by texas2010** [comment]
@KhalilNiser 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.

Happy Coding.

**Comment by Nardiy** [comment]
where do you add target"_blank"
