### ISSUE TITLE
Where-art-thou: Add example(and perhaps reword) to increase readability

### ISSUE THREAD

**Issue by dshgna** [FreeCodeCamp/FreeCodeCamp#2842]
Challenge http://freecodecamp.com/challenges/bonfire-where-art-thou has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

It is hard to understand the exact requirement of this challenge. Providing an example(and perhaps rewording) will help increase readability. Its specially hard to understand that having just one equal key-value pair will match the object.

For instance something like:

When the collection is [{ first: 'Romeo', last: 'Montague' }, { first: 'Mercutio', last: null }, { first: 'Tybalt', last: 'Capulet' }] and the source is { last: 'Capulet' } the array returned will be [{ first: 'Tybalt', last: 'Capulet' }] because in the third collection element both the key and value for "last" are equal to that of the source.

**Comment by awesomeaniruddh** [comment]
Ok, on it!

**Comment by awesomeaniruddh** [comment]
There have been quite a few campers asking for clarification regarding that bonfire, so I guess clarification is required.

**Comment by bugron** [comment]
Closing this issue as the PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2850 is merged.
@abhisekp thanks. Please be as polite as you can in your comments, thank you.

**Comment by abhisekp** [comment]
@bugron sorry!
