### ISSUE TITLE
Incorrect code passes the challenge

### ISSUE THREAD

**Issue by cmjchrisjones** [FreeCodeCamp/FreeCodeCamp#2843]
Challenge http://freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

To pass this challenge the code used needs to be 

 ```
$('.target:nth-child(2)').addClass('animated bounce');
```

however that are no 'target' classes in the HTML so not sure why this passes when I would expect the correct code to work would be

```
$('.well:nth-child(2)').addClass('animated bounce');
```

**Comment by bugron** [comment]
@cmjchrisjones thanks for posting this issue!
Note that your issue is a related to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1927:

See @benschenker's comment [here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1927#issuecomment-132369084).
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
