### ISSUE TITLE
Capitalisation of the word api

### ISSUE THREAD

**Issue by GursimarSinghChopra** [freeCodeCamp/freeCodeCamp#28446]
In the curriculum page, the apis and Microservices Certification link should be APIs and Microservices Certification.

![screenshot from 2018-10-25 12-26-12](https://user-images.githubusercontent.com/31305427/47481688-03f36200-d852-11e8-8d1e-0fe92801d89c.png)

* Browser Name: chrome
* Browser Version: 70.0.3538.67 (Official Build) (64-bit)
* Operating System: Ubuntu 18.04 LTS

**Comment by GursimarSinghChopra** [comment]
@amogh-gulati Sure

**Comment by erictleung** [comment]
@GursimarSinghChopra thanks for the issue! I've noticed this in the past and it has always bothered me.

I think to fix this is to edit the [`preFormattedBlockNames` constant](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/utils/blockNameify.js#L1-L14) with

```js
  'apis-and-microservices-certification': 'APIs and Microservices Certification',
  'apis-and-microservices-projects': 'APIs and Microservices Projects',
```

This will need to be tested and tried. This is just my guess from briefly searching around.

**Comment by ho-dor** [comment]
is this assigned? Can I work on this?

**Comment by dyllper** [comment]
Hello! Is someone else already working on this? Or could I take a crack at it?

**Comment by bhansa** [comment]
Please update the issue, if it's already completed.

**Comment by erictleung** [comment]
@bhansa although there are several commits referencing this issue, this particular hasn't been fixed yet.

@dyllper feel free to try and fix this. If you or anyone else needs assistance, please check the [Contributors chat room](https://gitter.im/freeCodeCamp/Contributors). Things are a bit hectic with the mass influx of Guide PRs, so this issue is probably low priority at the moment.

**Comment by Davidcreador** [comment]
Hi! Is this still open? I want to take a crack at it?

**Comment by tracer223** [comment]
Decided to take a stab at this last night/this morning... here's my local code ```blockNameify.js``` file in ```freeCodeCamp/client/utils``` :

```
const preFormattedBlockNames = {
  'apis-and-microservices-certification': 'APIs and Microservices Certification',
  'apis-and-microservices-projects': 'APIs and Microservices Projects',
  'api-projects': 'API Projects',
  'basic-css': 'Basic CSS',
  'basic-html-and-html5': 'Basic HTML and HTML5',
  'css-flexbox': 'CSS Flexbox',
  'css-grid': 'CSS Grid',
  devops: 'DevOps',
  es6: 'ES6',
  'information-security-with-helmetjs': 'Information Security with HelmetJS',
  jquery: 'jQuery',
  'json-apis-and-ajax': 'JSON APIs and Ajax',
  'mongodb-and-mongoose': 'MongoDB and Mongoose',
  'the-dom': 'The DOM'
};

const noFormatting = ['and', 'for', 'of', 'the', 'up', 'with'];

exports.blockNameify = function blockNameify(phrase) {
  const preFormatted = preFormattedBlockNames[phrase] || '';
  if (preFormatted) {
    return preFormatted;
  }
  return phrase
    .split('-')
    .map(word => {
      if (noFormatting.indexOf(word) !== -1) {
        return word;
      }
      if (word === 'javascript') {
        return 'JavaScript';
      }
      if (word === 'apis') {
        return 'APIs';
      }

      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(' ');
}
```
I tried adding a second if statement as well as a change to the ```const preFormatted Block Names``` to see if I could somehow 'force' a change and see if anything would change locally in my test environment.

This compiles and passes tests but doesn't change anything. Screenshot below with compiled code running on my local machine:

![fcc-snip1](https://user-images.githubusercontent.com/5696003/48665617-3cf8ae00-ea6f-11e8-84a8-1cfaecb30ba1.PNG)

Running Windows 10 and Chrome on the latest releases. 

I've recompiled several times and I'm not sure why it's not making the necessary changes. Noticed that 'Introduction to the APIs and Microservices Projects' shows 'APIs' correctly in the second dropdown, but both the parent dropdowns don't. Could it be something to do with a formatting file that's not in this directory? What seems like a simple issue seems a bit more complicated. I'm assuming this is why it hasn't been fixed yet?

**Comment by akhileshh** [comment]
I think that should fix it but the build failed!
