### ISSUE TITLE
Conditions a little bit unclear, Bonfire: Sorted Union

### ISSUE THREAD

**Issue by bogvak** [FreeCodeCamp/FreeCodeCamp#2845]
Challenge http://www.freecodecamp.com/challenges/bonfire-sorted-union has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Is it assumed that all arguments including values in nested arrays already contain only unique values as it comes from assertion test?
Final solutions strongly depends on such assumption so it better to describe such point explicitly.
Thanks a lot in advance!

**Comment by awesomeaniruddh** [comment]
I'm not sure I understand. If the arrays only contained unique values, then there is no point of the bonfire?

**Comment by bogvak** [comment]
Dear Aniruddh,

Ok, sorry, I found another solution.
Actually, I just meant that if it's necessary to test exact condition of bonfire it's probably better to include test something like that

unite([1, 3, 2], [1, [5, 1]], [2, [4, 3]])

because with current test it's easy to write code that passed test but won't fit exact bonfire condition - current tests contain in nested arrays values that already unique comparing to all other values.

**Comment by benschenker** [comment]
Hey @bogvak thanks for posting this!

Can you provide code that currently passes the tests but shouldn't (and that won't pass your new test)?

That will be helpful for testing.

**Comment by ltegman** [comment]
Closing as stale. Please feel free to reopen if you feel there are still problems with this bonfire.

Thanks and happy coding!
