### ISSUE TITLE
Doesn't recognize img src

### ISSUE THREAD

**Issue by Miguel-Arribas** [FreeCodeCamp/FreeCodeCamp#2848]
Challenge http://freecodecamp.com/challenges/waypoint-make-images-mobile-responsive has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I create the new image, I get correct checks about having 2 images, and having correct bootstrap tag, but keeps saying that the src is not right; I havre tried copying and pasting it, typing it... Doesn't seem to work. I havre tried also placing the img element in different places... And the image shows up right! So I am actually accessing an image stored in bit.ly.

Thanks,

![error](https://cloud.githubusercontent.com/assets/7231312/9563208/21203afe-4e7d-11e5-9645-47fca2404833.png)

**Comment by benmcmahon100** [comment]
Hi there @Miguel-Arribas I am unable to replicate this myself. Can you check that you are still unable to pass this challenge and report back? Also what browser are you using?

**Comment by jameskopacz** [comment]
Problem appears to be **both** images having the "img-responsive" class.

Fail:
[code]
  <a href="#">
    <img class="smaller-image thick-green-border **img-responsive**" src="http://bit.ly/fcc-relaxing-cat">
    <img class="**img-responsive**" src="http://bit.ly/fcc-running-cats">
  </a>
[/code]
Pass:
[code]
  <a href="#">
    <img class="smaller-image thick-green-border" src="http://bit.ly/fcc-relaxing-cat">
    <img class="**img-responsive**" src="http://bit.ly/fcc-running-cats">
  </a>
[/code]

**Comment by cpstephens** [comment]
@jameskopacz, thanks for the help, that worked for me!

**Comment by Miguel-Arribas** [comment]
@jameskopacz Thanks, James. (sorry for being so late acknowledging your help).

**Comment by VonRichtoffen** [comment]
I get passing marks but none of the images display on the simulated phone display.

images code:
 <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

  <img src="http://bit.ly/fcc-running-cats" class="img-responsive">

Running Chrome on Win7

**Comment by VonRichtoffen** [comment]
I get passing marks but images don't display on Chrome/Windoze7

code for the images:

**Comment by VonRichtoffen** [comment]
hmmm

**Comment by pronouncedOwl** [comment]
@jameskopacz , thanks for the help, that worked for me.

**Comment by QuintonRivera** [comment]
The solution is not list the period:  correct is https://bit.ly/fcc-running-cats and incorrect is https://bit.ly/fcc-running-cats.
