### ISSUE TITLE
Links on map redirect to home page, logged in with Twitter

### ISSUE THREAD

**Issue by iheartkode** [FreeCodeCamp/FreeCodeCamp#2852]
I logged in with Twitter and went to the map then I click on a course and it redirects to the Homepage. 
No matter what course on the map they all took me back. 

I came back after awhile to try and reproduce it... I logged in with Twitter it asked for auth, then redirects to the homepage and gives: Oops! Something went wrong. Please try again later.

Maybe someone else can log into Twitter and see if you can reproduce it?

**Comment by iheartkode** [comment]
I logged in with Facebook and all is well.

**Comment by jasonfavors** [comment]
Unable to reproduce by logging in with Twitter.  Steps I followed:

1. Log out
1. Sign in using Twitter (redirects to oauth page)
1. Directed to home page (no errors)
1. Click on Map
1. Click on any challenge
1. Directs to challenge page as expected.

Maybe this has been resolved?

**Comment by BerkeleyTrue** [comment]
@iheartkode I have fixed the issue with your account. It should be working now. Please PM on Gitter if you are still having issues.

Happy Coding!

**Comment by iheartkode** [comment]
All is well in the galaxy, thanks :)
