### ISSUE TITLE
small typo

### ISSUE THREAD

**Issue by LookOnTheBrightSide** [FreeCodeCamp/FreeCodeCamp#2853]
Challenge http://freecodecamp.com/challenges/waypoint-build-javascript-objects has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

represents should be represent

**Comment by natac13** [comment]
I have submitted a pull request for this

**Comment by iheartkode** [comment]
So we can close this @natac13 ?

**Comment by natac13** [comment]
You bet @iheartkode

**Comment by natac13** [comment]
Or am I suppose to do something and I am missing the point here lol?

**Comment by iheartkode** [comment]
Lol, I think @LookOnTheBrightSide needs to close it :)  My bad!
