### ISSUE TITLE
Code won't run.

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/FreeCodeCamp#2858]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by benmcmahon100** [comment]
@SEGrooms we cannot fix an issue with this description as you have not provided any information and I was able to run my code. Unless you can give us more detail we will be unable to fix this. Things you can try is disable any adblock or antivirus extensions you have and Safari, IE and Edge are not compatible with our testing suite

**Comment by SEGrooms** [comment]
The code simply wouldn't run. I think there was an error with the page loading. I reloaded it for a third time and it ran with no problems.

**Comment by benmcmahon100** [comment]
Okay I glad the issue got resolved. In future please provide as much detail as possible including your browser, a screenshot, any errors in the browser console etc. There are also guidelines if you are ever unsure about what to include on the wiki
