### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by ChristianLe87** [FreeCodeCamp/FreeCodeCamp#2859]
The: "Add the img-responsive class to your top image." doesn't work

**Comment by jasonfavors** [comment]
Unable to reproduce.  Can you provide more specifics as to what isn't working?

Assuming you're referring to the following challenge: http://freecodecamp.com/challenges/waypoint-ditch-custom-css-for-bootstrap

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!
