### ISSUE TITLE
run code bug

### ISSUE THREAD

**Issue by CEO2415** [FreeCodeCamp/FreeCodeCamp#2861]
Challenge http://freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
once I typed the code and hit the run code button the checked instructions disappeared and it wont submit and allow me to complete it and move forward 

![screenshot 1](https://cloud.githubusercontent.com/assets/9069070/9564749/ea012f7c-4e74-11e5-9525-324ad8eb1e00.png)

**Comment by benmcmahon100** [comment]
Edge, IE and safari don't play well with out tests suite. It'll work properly in chrome! Happy coding
