### ISSUE TITLE
Curriculum request: testing

### ISSUE THREAD

**Issue by leonfeng** [FreeCodeCamp/FreeCodeCamp#2863]
I've often heard that testing shouldn't be an after thought and that Test-Driven Development produces higher quality code. It would be really nice if Free Code Camp could incorporate testing into the various sections of its curriculum.

A few ideas:
* What is unit testing and why should you care
* Popular JavaScript testing frameworks and when to use them
* Unit testing full stack apps
* Cross-browser testing
* How Free Code Camp developers utilise testing in their workflows

cc: @benmcmahon100

**Comment by benmcmahon100** [comment]
Hey @leonfeng We have a tiny section (two challenges) with the basic - everyone needs to know these - topics that would fall under testing. I do plan to expand these but I have a fairly large backlog of challenges i need to do but i can guarantee that it's in the list.

**Comment by leonfeng** [comment]
Awesome! :+1:
