### ISSUE TITLE
no red color

### ISSUE THREAD

**Issue by robooo** [FreeCodeCamp/FreeCodeCamp#2864]
![screenshot from 2015-08-30 01 43 43](https://cloud.githubusercontent.com/assets/7584540/9565020/9de46dfe-4eb8-11e5-9ab1-0f0174fa5b3c.png)
Challenge http://freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element has an issue.
-No red color
-using mozilla 39

**Comment by benmcmahon100** [comment]
Hey @robooo Can you try rgb and hex for me? Just a curiosity in case that'd fix it. It's rgb(255,0,0) and #FF0000

**Comment by robooo** [comment]
Hi tried but still doesn't work for me

**Comment by benmcmahon100** [comment]
okay sorry about this! I'm not sure how to proceed unless by some miracle a refresh works.

**Comment by jameskopacz** [comment]
What happens if all Firefox addons are disabled? I wonder if it's a Firefox issue or maybe an addon is interfering some how?

**Comment by robooo** [comment]
Tried on chrome but same problem... on next waypoint it works.
my system is ubuntu 14.04

**Comment by benschenker** [comment]
Hey @robooo is this still an issue for you?

Have you tried hitting the reset button on the page?  The challenge starts off with that text being blue, is that true for you after hitting reset?

**Comment by robooo** [comment]
@benschenker Sorry didn't try reset, I just started clicking on run like crazy :) and after 5 sec window with submit shows up. I know it's not good way but worked for me.

**Comment by benschenker** [comment]
Awesome!
