### ISSUE TITLE
Multiple failed attempts to be directed Github when clicking on 'Debug' button. 

### ISSUE THREAD

**Issue by JesseNoBata** [FreeCodeCamp/FreeCodeCamp#2866]
Challenge http://freecodecamp.com/challenges/waypoint-use-hex-code-to-color-elements-blue has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by BerkeleyTrue** [comment]
Do you mean the Bug button? 

If so, what browser are you using?

Also, please read https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue

![waypoint__use_hex_code_to_color_elements_blue___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/9565920/89d29352-4ea1-11e5-9195-84cb96a55ab4.png)
