### ISSUE TITLE
Doesn't run the tests, or give useful feedback

### ISSUE THREAD

**Issue by AmeBel** [FreeCodeCamp/FreeCodeCamp#2869]
![screenshot from 2015-08-30 16 23 01](https://cloud.githubusercontent.com/assets/2135577/9566311/80ae79e8-4f33-11e5-9d84-8288d25a0225.png)
Challenge http://www.freecodecamp.com/challenges/bonfire-chunky-monkey has an issue. 

* Issue = clicking run has no usefule response
* Tried the solution suggested @ https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser's-Local-Storage, no change

**Comment by jameskopacz** [comment]
Do you get any response at all?

I'm seeing this after running the code in the screen shot:
> ["a","b","c","d"]

---

Console is outputting: 
> resetting on fatal plugin error
> commonF...8931.js (line 151)

https://github.com/FreeCodeCamp/FreeCodeCamp/blob/a737466e6856f63fdb39dfd42231b7283125e281/client/commonFramework.js#L151

---

Running the function in console freezes the browser. Using this code causes the same "["a","b","c","d"]" and console output:
```
function chunk(arr, size) {
  while (true) {
    // do nothing
  }
}
```

---

It appears the problem is caused by code that causes an endless loop. Only tests with challengeType set to 0 will output an error saying the code caused an endless loop. This one and it looks like all bonfires are set to challengeType 5.

**Comment by AmeBel** [comment]
no response

**Comment by jameskopacz** [comment]
@AmeBel, what happens if you try this code:
```
function chunk(arr, size) {
  var newArr = [];
  for(x=0; x<arr.length; x+=size) {
    var add = arr.slice(x, x+size);
    newArr.push(add);
  }
  return newArr;
}
chunk(['a', 'b', 'c', 'd'], 2);
```

**Comment by BerkeleyTrue** [comment]
Which browser are you using?

**Comment by AmeBel** [comment]
@jameskopacz it passes
@BerkeleyTrue chrome

**Comment by jameskopacz** [comment]
@BerkeleyTrue , I believe the code he used caused an infinite loop which causes no feedback to the user when it fails. Since he tested code that does pass the bonfire it doesn't appear to be his browser.

**Comment by AmeBel** [comment]
you mean an infinite loop in the freecodecamp code?

**Comment by jameskopacz** [comment]
In the code you used in the screen shot.
```
function chunk(arr, size) {
    // Break it up.
    var result = [];
    for(i = 0 ; i < Math.floor(arr.length/size) ; i + size) {
        result.push(arr.slice(i, i + size));
    }
    return result;
}

chunk(['a', 'b', 'c', 'd'], 3);
```
In the ```for``` loop ```i```i will never be less than ```Math.floor(arr.length/size)``` (which is 1 in this case) since every time it loops ```size``` is added to ```i```.

**Comment by AmeBel** [comment]
@jameskopacz thanks

**Comment by jameskopacz** [comment]
Np

**Comment by Joqr** [comment]
I'm experiencing this exact problem. I run my code and no tests are run, eventually my browser freezes, and I have to close everything out and try again. It's obviously a memory leak in the code, but even more interesting is Freecodecamp's official solution number 2 for this challenge also causes the same problem. 

I'm not sure where to go from here, but Im going to look at the source code for this challenge and see what's going on.

**Comment by jacob4** [comment]
I'm having the same issue; has a solution been found yet?
![capture](https://cloud.githubusercontent.com/assets/10079209/11130609/32be2270-8943-11e5-9fcf-438866014308.JPG)
