### ISSUE TITLE
Cannot read property 'eql' of undefined

### ISSUE THREAD

**Issue by kamiranoff** [FreeCodeCamp/FreeCodeCamp#2876]
Challenge http://freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue.
The console outputs 'Cannot read property 'eql' of undefined' and the user cant run the code.
I am using chrome.

![capture d ecran 2015-08-30 a 13 52 05](https://cloud.githubusercontent.com/assets/5861100/9567085/67bd4b04-4f1e-11e5-9a72-8e012e274375.png)

**Comment by bugron** [comment]
@kamiranoff thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2874

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by kamiranoff** [comment]
I have been looking around and I believe this test is causing the bug : 
"(largestOfFour([[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]])).should.eql([27,5,39,1001]);",

In basic-bonfires.json

**Comment by kamiranoff** [comment]
@bugron Sorry for the duplicate.
I believe it should be : 
"assert(largestOfFour([[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]).should.eql([27,5,39,1001]));",

I am creating a pull request.

**Comment by bugron** [comment]
@kamiranoff ok, then write something like "closes #2874" in your pull request's description to close that issue too.

**Comment by BerkeleyTrue** [comment]
Fixed
