### ISSUE TITLE
Unchecked goal in Waypoint 13 for jQuery

### ISSUE THREAD

**Issue by aryasaatvik** [FreeCodeCamp/FreeCodeCamp#2877]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Your left-well element should have a red background. is unchecked even though the requirements are fulfilled

![image](https://cloud.githubusercontent.com/assets/5666379/9567153/5d25ead2-4f3e-11e5-9eb0-d962f56a96f5.png)

**Comment by bugron** [comment]
@UserName thanks for posting this issue!
Your code is incorrect. I mean `$("#left-well").parent().css("background-color", "red");` Your code says "Hey, you, browser, make #left-well element's **parent's** background color red, but you actually need to set background color to red of your `#left-well` element and **not** it's parent's. So proper code looks like this:  `$("#target1").parent().css("background-color", "red");` or `$("#target3").parent().css("background-color", "red");` or `$("#target5").parent().css("background-color", "red");`

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
