### ISSUE TITLE
Waypoints deleted

### ISSUE THREAD

**Issue by mitziw** [FreeCodeCamp/FreeCodeCamp#2878]
I only noticed yesterday because i was trying to go back and see what i had done for seek and destroy. all gone. this is the second time but the first was when i just started and i did the cat app twice. but this is too much work gone to do that. i hope someone can restore it.

**Comment by bugron** [comment]
@mitziw thanks for posting this issue!
If you have such a problem try sending an e-mail to team@freecodecamp.com.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by benschenker** [comment]
Closing as stale, please reopen if this is not resolved
