### ISSUE TITLE
Selector does not register with single quotes.

### ISSUE THREAD

**Issue by rheajt** [FreeCodeCamp/FreeCodeCamp#2881]
Challenge http://freecodecamp.com/challenges/waypoint-bring-your-javascript-slot-machine-to-life has an issue.

This challenge only accepts $($(".slot")[0]) and not $($('.slot')[0]). I think it should probably accept both single and double quotes.

**Comment by bugron** [comment]
@rheajt thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2522
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by iheartkode** [comment]
@rheajt Can you please close this as it's a duplicate? Thank you very much :)

**Comment by rheajt** [comment]
I would have closed it, but it looks like it has been taken care. Sorry for
the duplicate!
