### ISSUE TITLE
Can't run this challenge :(

### ISSUE THREAD

**Issue by dalebulbrook** [FreeCodeCamp/FreeCodeCamp#2882]
Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

It doesn't matter what code you write, your get the same error:
Cannot read property 'eql' of undefined

Even chopping the function call to a straight text string gives the same error.

![screenshot 2015-08-30 16 52 24](https://cloud.githubusercontent.com/assets/3133884/9568090/f786ab18-4f37-11e5-8bcb-8c4db2c39af5.png)

**Comment by bugron** [comment]
@dalebulbrook thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2876
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2874

There is a PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2879 which is waiting for approvement. 

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by BerkeleyTrue** [comment]
Fixed
