### ISSUE TITLE
Cannot run code on Bonfire: return largest number in arrays

### ISSUE THREAD

**Issue by walent021** [FreeCodeCamp/FreeCodeCamp#2883]
Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. 
The code just outputs: "Cannot read property "should" of undefined. My code is ok.
![image](https://cloud.githubusercontent.com/assets/1339394/9568094/85c1bb18-4f40-11e5-8e7f-08b97464b59e.png)

**Comment by bugron** [comment]
@UserName thanks for posting this issue!
Note that your issue is related to
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2882
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2876
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2874:

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
