### ISSUE TITLE
UX Issue: The big tick feels to slow the process down unnecessarily 

### ISSUE THREAD

**Issue by georgiel** [FreeCodeCamp/FreeCodeCamp#2884]
http://imgur.com/qoUr74o

I remember that did not used to be a part of the design, and it really is not a good UX in my opinion. It feels like one has to wait when I want to charge ahead with only using my keyboard.

I think that if not removed, the tickbox option to opt-out of that part in settings would be excellent.

**Comment by benmcmahon100** [comment]
The tickbox has always been there. We intend on adding the ctrl+enter to move to the next challenge back in soon

**Comment by georgiel** [comment]
why was it removed anyhow?

**Comment by benmcmahon100** [comment]
It was removed in the process of fixing an another issue and we'd like to add it back in
