### ISSUE TITLE
Regular Expressions: Find More Than the First Match Missing Instructions

### ISSUE THREAD

**Issue by TomerPacific** [freeCodeCamp/freeCodeCamp#28841]
**Describe your problem and how to reproduce it:**
In this challenge, the user is first introduced to flags in regular expression. Thing is, the global, g flag, is the only one discussed, but the solution requires the use of the i flag as well.

To someone who is not familiar with regular expression at all, this does not provide any learning whatsoever. More so, the note at the bottom doesn't even explain the i flag at all and doesn't provide any clue on why it is even needed.

**Add a Link to the page with the problem:**
[Challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/find-more-than-the-first-match)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 70.0.3538.67 (Official Build) (64-bit)
* Operating System: Windows 7 64bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![fccbug](https://user-images.githubusercontent.com/23402988/47527661-b9063880-d8ab-11e8-8796-0e78019085c9.jpg)

**Comment by Nirajn2311** [comment]
@TomerPacific the user is introduced to the `i` flag two challenges before the one mentioned by you. So the user already has knowledge of the `i` flag by the time they reach this challenge.
