### ISSUE TITLE
Bonfire:  Where art thou misquote

### ISSUE THREAD

**Issue by breyn407** [FreeCodeCamp/FreeCodeCamp#2886]
http://freecodecamp.com/challenges/bonfire-where-art-thou

Upon examining the bonfire, it appears to be based on Shakespeare's "Romeo and Juliet."  In this case, the title of the bonfire is incorrect.  The quote as spoken from "Romeo and Juliet," Act II, Scene II is "Wherefore art thou Romeo."  Should not the title of this bonfire then be "Wherefore art thou" ?

The difference between "Where" and "Wherefore" is significant.  They have two totally different meanings.  "Where" eludes to a question of location or geography.  "Wherefore" roughly means "Why?"

Juliet (thinking she is speaking to herself) asks aloud "Wherefore art thou Romeo?"  In other words, asking why is her love have to be named "Romeo," referencing his name as part of the family for which hers is rival.

My request is to please correct the name on the Bonfire.  I don't yet know how to do anything other than point out the issue.  Thanks!

**Comment by iheartkode** [comment]
Thank you for the wonderful explanation and suggestion :)

**Comment by michael-krebs** [comment]
I think the "where" is a deliberate pun. The bonfire is supposed to search through an array for a matching property, so it makes sense.

**Comment by AryanJ-NYC** [comment]
@michael-krebs Good explanation as to wherefore we use where.

**Comment by breyn407** [comment]
I can see the pun and why it may be deliberate.  I don't agree that's an unequivocal pun, however.  The comment points right to the scene I mentioned, which to me screams butchery of the quote, especially since this is a common misinterpretation.  I would vote ambiguous at best.  In any case, no reason to keep this open.  Thanks for the alternate theory.
