### ISSUE TITLE
There is no user test defined to run the code

### ISSUE THREAD

**Issue by asglasby** [FreeCodeCamp/FreeCodeCamp#2889]
![numberinarrays](https://cloud.githubusercontent.com/assets/4098109/9569280/2659b9de-4f34-11e5-8309-d3a36dad25d9.png)
Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by bugron** [comment]
@asglasby  thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2882
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2876
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2874

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
