### ISSUE TITLE
Cannot read property 'eql' in undefined - Bonfire: Return Largest Numbers in Arrays

### ISSUE THREAD

**Issue by aizz88** [FreeCodeCamp/FreeCodeCamp#2890]
Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. 

This issue occurs no matter what code I put in. Believe something in the background may be broken. I was told in the Helproom that a few others are getting this too.

**Comment by natac13** [comment]
@aizz88 Thanks for posting the issue. 
You are correct about other campers getting it.
Related to:
#2887 
#2882
#2876
#2874

**Comment by bugron** [comment]
@dalebulbrook thanks for posting this issue!

There are a few PRs (https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2879, https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2887) which are waiting for approvement. 

*Dear campers, if anyone of you is reading this, please use the link below to avoid opening* **duplicate** *issues*. This one is already **4th** duplicate issue on this subject only today and there are another two similar ones. Thank you for investing you time and energy contributing to FCC. 

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by dting** [comment]
I think the main problem is that on the actual challenge page there is a button that takes you directly to filing an issue. The popup should probably tell the user to look for duplicate issues.

**Comment by bugron** [comment]
@dting exactly! I've realize that in my local copy of FCC.
Feature 1
http://sendvid.com/nfacn6i1
Feature 2
http://sendvid.com/t2xda18l
I messaged @QuincyLarson via Gitter and I'm waiting for his response to create a PR.

**Comment by BerkeleyTrue** [comment]
Fixed
