### ISSUE TITLE
Unable to create a script element

### ISSUE THREAD

**Issue by sarita3** [FreeCodeCamp/FreeCodeCamp#2891]
Challenge http://freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

It will not accept my script element
![error](https://cloud.githubusercontent.com/assets/12984339/9569465/3276ad70-4f21-11e5-8859-6896cc554a1c.jpg)

**Comment by benmcmahon100** [comment]
Hey @sarita3 our test suite doesn't play well with Edge, IE, Safari or Opera. This challenge will work properly with chrome or firefox.

**Comment by sarita3** [comment]
Thank you

**Comment by iheartkode** [comment]
@sarita3 Can we close this issue? Thanks :)
