### ISSUE TITLE
Editor retains original version, does not retain updates

### ISSUE THREAD

**Issue by cmdaniel04** [FreeCodeCamp/FreeCodeCamp#2894]
Challenge http://www.freecodecamp.com/challenges/bonfire-find-the-longest-word-in-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The code editor does not update with the code changes.

The editor retains the code I originally entered, which is not correct.  I corrected my code, and passed the challenge. It gave me the success message, and incremented my task counter, but when I return to this page, it still has my original, incorrect code.

**Comment by happpyier** [comment]
I submitted a bug 
When i hit run code it does not save my code. (#2937) for the chunky monkey bonfire and was referenced to this bug and it is still not fixed. so I am reopening the issue here.

**Comment by cmdaniel04** [comment]
It's not saving this one either:
http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence

**Comment by cmdaniel04** [comment]
This appears to be happening on every exercise I complete.
