### ISSUE TITLE
It keeps producing error "cannot read property 'eql' of undefned" no matter what code I type 

### ISSUE THREAD

**Issue by Tarek-Mostafa** [FreeCodeCamp/FreeCodeCamp#2895]
Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![a](https://cloud.githubusercontent.com/assets/13671211/9570296/bf54039e-4f87-11e5-84b2-a72e6ba2088f.JPG)

**Comment by natac13** [comment]
@Tarek-Mostafa Thanks for posting this issue
It happens to be similar to these:
#2887 
#2882 
#2876 
#2874
