### ISSUE TITLE
GOOOD LORD...

### ISSUE THREAD

**Issue by Kpez16** [FreeCodeCamp/FreeCodeCamp#2896]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

img element will not recognize multiple classes. Bug menu is ....bugged. Had to refresh and click multiple places in order to reach this input.

**Comment by iheartkode** [comment]
Could you use a more descriptive title and some more information besides "bugged"?

**Comment by iheartkode** [comment]
I tried out the waypoint and it worked for me, can you post your code?

**Comment by iheartkode** [comment]
![class](https://cloud.githubusercontent.com/assets/7018580/9570335/7a61aa4c-4f3d-11e5-8cce-b55ef22b40f8.png)

**Comment by natac13** [comment]
@iheartkode Worked for me as well

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!

**Comment by iCityWork** [comment]
I have the same issue! says that it isn't passing Your img element should have the class thick-green-border.
Give your image a border width of 10px. yet in preview it works fine.

```
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
  .smaller-image {
    width: 100px;
  }
  
  .think-green-border{
    border-color: green;
    border-width: 10px;
    border-style: solid;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image think-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by natac13** [comment]
@iCityWork your class is `thiNk-green-border` and not `thiCk-green-border`

I capitalized the problematic character. Hope that helps. 
I did copy paste your code and made that change and all tests pass
