### ISSUE TITLE
'cannot read property 'EQL' of undefined

### ISSUE THREAD

**Issue by Benjmhart** [FreeCodeCamp/FreeCodeCamp#2897]
Challenge http://freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

On this exercise,  the 'cannot read property 'eql' of undefined' error  happens regardless of what the function does.

when I replaced the inputs with a more basic array,  the error changes to 'largestOfFour is not a function' when it is clearly defined as a function.

**Comment by bugron** [comment]
@Benjmhart thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2874

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
