### ISSUE TITLE
cannot read property 'eql' of undefined

### ISSUE THREAD

**Issue by gitmihalis** [FreeCodeCamp/FreeCodeCamp#2898]
Challenge http://freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

No matter what, it does not pass!

<img width="1390" alt="screen shot 2015-08-30 at 8 28 43 pm" src="https://cloud.githubusercontent.com/assets/10368363/9571662/c11ad202-4f55-11e5-874b-75d68334e3aa.png">

**Comment by iheartkode** [comment]
This issue is already posted.
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2897
