### ISSUE TITLE
div

### ISSUE THREAD

**Issue by mwandama** [FreeCodeCamp/FreeCodeCamp#2899]
Challenge http://freecodecamp.com/challenges/waypoint-give-a-background-color-to-a-div-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

.background-color{
background-color:gray;
}

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!

**Comment by shaikhatik0786** [comment]
@mwandama you first need to give your div the class of gray-background

` <div class="gray-background" `

then you need to work with css

```
.gray-background{
    background-color:gray;
  }

**Comment by mwandama** [comment]
I tried what you have shown me defining the <div class as you have shown me it didn't work

**Comment by shaikhatik0786** [comment]
@mwandama you have to check your css class too, in the description above, you gave the wrong class name

**Comment by denied0311** [comment]
I am trying to give a background color to a <div> element. What i did worked and it changed the background color to "silver" as it was supposed to. yet it tells me it is wrong. my code is below: help please?

<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
  
  div
   {
    background-color: silver;}
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" alt="A cute orange cat lying on its back. " src="https://bit.ly/fcc-relaxing-cat"></a>

<div>
  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
</div>

<form action="/submit-cat-photo">
  <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
  <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
  <label><input type="checkbox" name="personality" checked> Loving</label>
  <label><input type="checkbox" name="personality"> Lazy</label>
  <label><input type="checkbox" name="personality"> Energetic</label>
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>

**Comment by BerkeleyTrue** [comment]
The issue tracker is for reporting bugs only. If this is an issue for help with a challenge, please use the [help chat room](https://gitter.im/FreeCodeCamp/Help) or try looking through the [forum](http://forum.freecodecamp.com/c/free-code-camp) for help with a specific challenge.

Happy Coding.
