### ISSUE TITLE
margin

### ISSUE THREAD

**Issue by mwandama** [FreeCodeCamp/FreeCodeCamp#2900]
Challenge http://freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
.green-box{
margin: 40px 20px 20px 40px;

}

**Comment by shaikhatik0786** [comment]
@mwandama: well your code is correct

```
.green-box {
    background-color: green;
    margin: 40px 20px 20px 40px;
  }
```

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!
