### ISSUE TITLE
Hints do not always appear

### ISSUE THREAD

**Issue by frankmoisan** [FreeCodeCamp/FreeCodeCamp#2904]
Waypoint hints do not always appear after the page has loaded. Refreshing the page does not always seem to work. Closed & reopened browser does not seem to change behaviour. Issue is not specific to certain waypoints but started to occur in the jQuery section.

Issue experienced on Chrome 44.0.2403.55 on Windows 8.1. Attached screenshot for clarity.

![image](https://cloud.githubusercontent.com/assets/14047456/9572289/72b58b36-4f7b-11e5-98ed-a44133dd9331.png)

**Comment by shaikhatik0786** [comment]
@frankmoisan this too is an issue coming up for a lot of people. Infact it comes for me too. All I do is click on the run code button, it reloads the contents, and thus adds the hints too.
Try that

**Comment by BerkeleyTrue** [comment]
This happens when you code crashes the test suite (incorrect syntax, infinite loop, open script tag with no closing, etc...). Try fixing issues with your code and re-running test suite.

**Comment by frankmoisan** [comment]
This screenshot was taken before anything was ran. The hints sometimes appear after clicking the "Run" button, but not always.

**Comment by benschenker** [comment]
@frankmoisan and @shaikhatik0786 , I am unable to replicate this.  Is this still a problem for you?

**Comment by frankmoisan** [comment]
@benschenker I can't seem to be able to replicate at the moment. Every page I checked shows hints both before and after clicking the Run button. Tests performed with Internet Explorer 11 did not show the code hints, but I believe issue #1566 applies here.

**Comment by BerkeleyTrue** [comment]
I've just run into this while debugging another issue. Seems that in some situations the web worker we use does not properly setup so that it crashes on its own and does not run test. This happens sporadically and is hard to pin down the exact cause. But that is definitely the reason tests do not show up for some on init.

**Comment by ltegman** [comment]
I suspect this was resolved in the recent refactor and am closing as stale. Please feel free to reopen if you are still able to repro this.
