### ISSUE TITLE
Error on Publish Again

### ISSUE THREAD

**Issue by debugpoint136** [FreeCodeCamp/FreeCodeCamp#2905]
Hi I am receiving this error in this Challenge :- 
http://www.freecodecamp.com/challenges/waypoint-manage-packages-with-npm

**Step 10** Publish Again
![error_screenshot](https://dl.dropboxusercontent.com/spa/ry0atqxaxd315xf/rgfvw_ve.png)

Kindly help in resolving this.

Many thanks!

**Comment by bugron** [comment]
@debugpoint136 thanks for posting this issue!
Take a look at this [comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1326#issuecomment-135263584), thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
