### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by jozomk** [FreeCodeCamp/FreeCodeCamp#2907]
Challenge http://freecodecamp.com/challenges/waypoint-use-css-selectors-to-style-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The instructions say that the h2 header should be red, but the requirements are saying it should be blue. The previous exercise has the same problem, but the colors are swapped, the instructions say red, the requirements say blue. 

![css](https://cloud.githubusercontent.com/assets/14050034/9573449/ed7a1b34-4fbc-11e5-80f5-ab75693d7f06.png)

**Comment by shaikhatik0786** [comment]
@jozomk the first two boxes aren't instructions but actually examples, the waypoints are your instructions and requirements, so yes you ahve to make it blue

**Comment by jozomk** [comment]
Thanks, so far (and in the exercises that follow) the examples were identical to the requirements, so I thought that there is a mix-up with the colors, but all is well :)
