### ISSUE TITLE
freecodecamp.com/challenges/bonfire-check-for-palindromes has an issue

### ISSUE THREAD

**Issue by MangeshCodeCamp** [FreeCodeCamp/FreeCodeCamp#2908]
Challenge http://freecodecamp.com/challenges/bonfire-check-for-palindromes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
I am not able to run my code as given in screen shot please help.
This code runs fine in browser console but fails in fcc editor.
![bugfcc](https://cloud.githubusercontent.com/assets/13926540/9573666/a186b2ee-4fdc-11e5-83c3-dffbafc21728.png)

**Comment by Mansuro** [comment]
Your code doesn't take spaces into account

**Comment by abhisekp** [comment]
@benmcmahon100 Please close this issue as it's irrelevant.

**Comment by MangeshCodeCamp** [comment]
Hi ,
I am now facing no issues please close this issue.

**Comment by bugron** [comment]
@MangeshCodeCamp actually you can close this issue yourself. Push the button **Close issue**.
