### ISSUE TITLE
Errors in page causing asserts to show as text on page

### ISSUE THREAD

**Issue by psabo** [FreeCodeCamp/FreeCodeCamp#2909]
Challenge http://freecodecamp.com/challenges/waypoint-declare-string-variables has an issue. 

Browser: Version 44.0.2403.157 (64-bit)
OS: OS X 10.9.5

Description:
JavaScript errors causing assert function to display in tasks to complete section of page.

Image:
![Screen shot]
(http://new.tinygrab.com/5be59a8681200a79680d1c65c198d2f658515666db.png)

Steps to reproduce:
1.  Load challenge at http://freecodecamp.com/challenges/waypoint-declare-string-variables

**Comment by Mansuro** [comment]
That is normal behavior.

**Comment by bugron** [comment]
@psabo thanks for posting this issue!
This is neither an error nor a bug. See my [comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2818#issuecomment-135908153), thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
