### ISSUE TITLE
Corner case not validate

### ISSUE THREAD

**Issue by harshitanand** [FreeCodeCamp/FreeCodeCamp#2910]
Challenge http://freecodecamp.com/challenges/bonfire-truncate-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by iheartkode** [comment]
Could you explain this in more detail maybe include a screen shot? Thanks :)

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!
