### ISSUE TITLE
regexp "+" quantifier not properly explained and used

### ISSUE THREAD

**Issue by elmojito** [FreeCodeCamp/FreeCodeCamp#2911]
Challenge http://www.freecodecamp.com/challenges/waypoint-sift-through-text-with-regular-expressions has an issue. 

in this challenge explanation of regexp matching basics looks like on the screenshot below.

in the example it sounds rather misleading, that "+" quantifier relates to whole "the" / "and" word. in fact, it relates to "d" letter only.

regards,
moshe

![waypoint sift through text with regular expressions free code camp](https://cloud.githubusercontent.com/assets/317336/9574112/e129ec04-4fc3-11e5-9650-45d92d421839.png)

**Comment by dmytroyarmak** [comment]
I agree, `+` in this case doesn't make sence and finding words is a bad example of using it. So I prefer to remove it from this challange.
I'll create PR

**Comment by dmytroyarmak** [comment]
Wow, it has been already fixed in `staging`: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2490

**Comment by bugron** [comment]
@elmojito thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1938
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by bugron** [comment]
Closing this issue as PR #2490 is merged.
