### ISSUE TITLE
Bug I found

### ISSUE THREAD

**Issue by Tzahile** [FreeCodeCamp/FreeCodeCamp#2913]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. 

description:
first of all, in the end of the code it is written "<--" that came out of nowhere
second, if I have a typo (in the screenshot I wrote "documet" instead of "document"), all the missions' levels disappear, untill the typo is gone..

![image](https://cloud.githubusercontent.com/assets/13683050/9574847/5174b8ea-4fd3-11e5-8e07-0b49af82e2fd.png)

Sincerely,
Tzahi

**Comment by bugron** [comment]
@Tzahile thanks for posting this issue!
I can't find that "<--" neither in [source code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/jquery.json#L47) nor in [production](http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work) (I've tried in FF and Chrome Incognito modes).
**But** I can't modify any line of code below 20. As I remember this was mentioned somewhere and it could a bug in CodeMirror.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by Tzahile** [comment]
![image](https://cloud.githubusercontent.com/assets/13683050/9576189/4f2c7310-4fde-11e5-92eb-ab7fe27e18c7.png)

well, I did "Inspect elements" (I'm using Chrome)
and there it is.

Anyway, it's a minor problem..
more important problem is about what I mentioned - the missions on the left side disappear if you do something like typo.
Another bug I noticed is that sometimes when starting a new mission, part of the code is (probably) invisible, and you need to click on the code-window or write something, and then the rest of the code reappears..

**Comment by bugron** [comment]
@Tzahile you typed **documet** but it should be **document** in your `script` tag.. This error is caused by you typo. Editor tries to **execute** the code you wrote but there is no **documet** object in jQuery so it gives you an error.
