### ISSUE TITLE
Bug in "Give a Background Color to a Div Element"

### ISSUE THREAD

**Issue by jasellis** [FreeCodeCamp/FreeCodeCamp#2914]
Challenge http://www.freecodecamp.com/challenges/waypoint-give-a-background-color-to-a-div-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Created a class called .gray-background as instructed, gave this class to div element. Doesn't work when I click the Run Code button but works in the preview.

![screenshot from 2015-08-31 18 42 46](https://cloud.githubusercontent.com/assets/8603634/9575118/5737904e-5010-11e5-8400-88d28fee3e47.png)

**Comment by bugron** [comment]
@jasellis  thanks for posting this issue!
I've just passed the tests with your code both in FF and Chrome (in Incognito mode).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by awesomeaniruddh** [comment]
Works for me too. Seems to be an issue on your end.

Please check your ChromeDevTools console and report with any errors on there.

**Comment by jasellis** [comment]
Okay turns out it was an extension called Privacy Badger. I disabled it for FCC and everything seems to be working now. :+1:

**Comment by bugron** [comment]
@jasellis if you can now close this issue if you solved your problem, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by eugene-finn** [comment]
Doesn't work
![2015-10-30 15 51 19](https://cloud.githubusercontent.com/assets/9496944/10846120/2f610a0e-7f1e-11e5-8b6b-b5982c3cdf3d.png)

**Comment by Pretenderr** [comment]
![GitHub Logo](https://sc-cdn.scaleengine.net/i/8766a129812926f4a7425a11cf201726.png)

Invalid property value.

Ubuntu 15.10
Google Chrome Version 46.0.2490.80 (64-bit)

**Comment by Mickey0001** [comment]
I had the same issue in chrome, the workaround did the trick!

**Comment by Deryckaus** [comment]
turns out i had left a space between the SILVER- BACKGROUND

Jeez i am a newb

**Comment by jmanny1** [comment]
Big Tip!!!!! disable ad blocker or pause it. everything working right way!!!
