### ISSUE TITLE
Waypoint: Make Images Mobile Responsive

### ISSUE THREAD

**Issue by Morifen** [FreeCodeCamp/FreeCodeCamp#2915]
Challenge http://freecodecamp.com/challenges/waypoint-make-images-mobile-responsive has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The instruction is:
*First, Add a new image* **below** *the existing one. Set it's src attribute to http://bit.ly/fcc-running-cats.*

But the third validator accept only an new image **upper** the first one

**Comment by Mansuro** [comment]
Did you set the class to img-responsive?

**Comment by bugron** [comment]
@Morifen thanks for posting this issue!
I've just passed the test by placing 
`<img class="img-responsive" src="http://bit.ly/fcc-running-cats">` **below** 
`<a href="#"><img class="smaller-image thick-green-border" src="http://bit.ly/fcc-relaxing-cat"></a>` , so it worked for me.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by benschenker** [comment]
Closing this as stale, please reopen if this is not resolved.
