### ISSUE TITLE
Won't pass working code.

### ISSUE THREAD

**Issue by justinboden** [FreeCodeCamp/FreeCodeCamp#2918]
Challenge http://freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![screenshot 2015-08-31 21 03 37]

Goal: "Your left-well element should have a red background."
Result: See screenshot: left-well element has a red background, and yet I'm still given a fail.
Code: $("#left-well").parent().css("background-color", "red"); [syntax reads correctly to me]

Note: using parent() element as per requirement of the challenge.

(https://cloud.githubusercontent.com/assets/5818930/9577806/d4fed556-5023-11e5-80d5-18316c56aa5f.png)

**Comment by justinboden** [comment]
Never mind: I think I was just confused by the instructions, which wanted me to complete the challenge in a particular way – that I specifically had to modify the target#1 element to get the desired result. Sorry for the false report.

**Comment by bugron** [comment]
@justinboden thanks for posting this issue!
If you can now close this issue if you solved your problem, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
