### ISSUE TITLE
Bonfire tests not executing.

### ISSUE THREAD

**Issue by samirprakash** [FreeCodeCamp/FreeCodeCamp#2919]
Challenge http://freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

1. GO to http://freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays

2. Check the unit test section. Script error being reported.

3. Not able to proceed with the test.

![image](https://cloud.githubusercontent.com/assets/4006402/9578086/c58e44fe-5004-11e5-8cde-d149fec99de3.png)

**Comment by dokkillo** [comment]
i Confirm its a bug, i test with the code that helpme to pass the bonfire and it dont works.

**Comment by awesomeaniruddh** [comment]
If I remember correctly, this error is appearing on other challenges as well. Definitely weird.

https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2874

This is a duplicate issue, so please close this one and post your problem on the link above ^.

It seems that there are already a couple of pull requests for this issue and it is likely that someone from the core dev team is working on it.

Please take a look at https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md before posting issues!

**Comment by samirprakash** [comment]
@awesomeaniruddh thanks for the detailed information. 

I have gone through the contribution process before posting the issue. The earlier issue does not have a screen shot and for any UI related app, a screen shot is required for client side debugging. 

I would wait for the issue #2874 to be closed before I close this one. I would mark this a duplicate.

samir

**Comment by zoorz** [comment]
Maybe can help you! https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2879

**Comment by BerkeleyTrue** [comment]
Fixed
