### ISSUE TITLE
Should sign up email be moved to user.save callback?

### ISSUE THREAD

**Issue by jameskopacz** [FreeCodeCamp/freecodecamp#292]
https://github.com/FreeCodeCamp/freecodecamp/blob/master/controllers/user.js#L161-L183

If an error occurred on the user.save would it still send them an email welcoming them to the site?

Still learning so I'm not totally sure.

**Comment by QuincyLarson** [comment]
Let me verify this real quick (since I have a Mandrill key)

**Comment by QuincyLarson** [comment]
I've done this and it seems to work.
