### ISSUE TITLE
Automatic Pass

### ISSUE THREAD

**Issue by geriesc** [FreeCodeCamp/FreeCodeCamp#2923]
Challenge http://freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-nth-character-in-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible."

I started with the first bonfire (Meet Bonfire) and I was working on it for a while. I typed some code and then the output said "undefined" but I still passed. The site loaded the next challenge but with the answer already written there. I clicked on "Run code" and brought me to the next challenge, again, with the answer already there.  Please help.

![screenshot from 2015-08-31 22 49 30](https://cloud.githubusercontent.com/assets/13535428/9581525/9c326ce2-5032-11e5-85c0-a111b1679620.png)

**Comment by natac13** [comment]
@geriesc I am not sure how to go about reproducing this. The test you link to seem to be working fine for me. There is no code already loaded

**Comment by benschenker** [comment]
@geriesc thanks for posting.

it sounds like your browser has saved your previous solutions (this is a feature of FreeCodeCamp)

You can delete them by clearing your cache or [Clear your LocalStorage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser's-Local-Storage), but this won't delete your progress on FCC.

Closing this, but feel free to reopen if this is not resolved
