### ISSUE TITLE
Nesting an anchor within a paragraph

### ISSUE THREAD

**Issue by AMF1979** [FreeCodeCamp/FreeCodeCamp#2925]
Challenge http://freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

1. I keep getting the error: "Your 'a' element should be nested within your new 'p' element."
2. 6/7 challenges are checked green except for the above.

The code in question: 
<p class="red-text">Click here for <a href="http://freecatphotoapp.com">Cat Photos</a></p> 

I have nested the 'a' element within the 'p' element to create the sentence: Click here for CAT PHOTOS where CAT PHOTOS is a link. Not sure what error I am making.

**Comment by bugron** [comment]
@AMF1979 thanks for posting this issue!
Note that your issue is related to:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2794
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2673
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2007

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by shaikhatik0786** [comment]
@AMF1979 its the most common error everyone is facing, the code you need to put is:
```
<p>click here for <a href="http://www.freecatphotoapp.com">cat photos</a></p>
```

you must have not added the www. to the link.
Not your mistake, they haven't mentioned it there.

**Comment by bugron** [comment]
Closing this issue as a duplicate.
