### ISSUE TITLE
jQuery waypoints don't pass even when code correct

### ISSUE THREAD

**Issue by aw1231** [FreeCodeCamp/FreeCodeCamp#2927]
Hi,
I have correct code in the first five jQuery waypoints.  If I press control+enter, it still has multiple red Xs.  However, if I press control+enter multiple times, it eventually detects the correct code and passes.

**Comment by BerkeleyTrue** [comment]
Please read: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue

Could you paste you code here?

**Comment by aw1231** [comment]
This is for disable an element using jQuery:
```<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled",true);

  });
</script>

<!-- You shouldn't need to modify code below this line -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>
```

**Comment by BerkeleyTrue** [comment]
You are missing a script tag. Looks like a bad copy paste. Can you edit?

**Comment by aw1231** [comment]
Done.

**Comment by natac13** [comment]
That code ran fine for me on that challenge

**Comment by aw1231** [comment]
I'm using firefox 40.0.3 on Windows 10 with no addons/blockers.

**Comment by aw1231** [comment]
The problem is sometimes it runs fine, but sometimes I have to submit 5-6 times for it to go through.

**Comment by BerkeleyTrue** [comment]
Do you have the same issue doing this challenge in Chrome? Do you see any errors outputted in chrome?

**Comment by aw1231** [comment]
Chrome works fine.

**Comment by BerkeleyTrue** [comment]
Alright so this is a FF issue. Where you able to complete any challenges on FF?

**Comment by aw1231** [comment]
Yes, all of the other challenges work fine.  It is just the jQuery ones so far.  I just got to the bonfires.

**Comment by aw1231** [comment]
It is ok to use FF right?

**Comment by BerkeleyTrue** [comment]
We only officially support Chrome at the moment.

Is anyone else experience this that is willing to do some source diving and find the root of the issue jQuery challenges have in FF?

**Comment by aw1231** [comment]
I have developed for Mozilla before.  I just thought it was a FCC issue.  I can look into it, but if someone wants to help, it might get done faster.

**Comment by ltegman** [comment]
This is resolved in a version of the site that is currently live in beta and should get pushed into production soon. Thanks and happy coding!
