### ISSUE TITLE
Navbar is not proper align in the night mode

### ISSUE THREAD

**Issue by GursimarSinghChopra** [freeCodeCamp/freeCodeCamp#29296]
Navbar is not proper align in the curriculum page as compared to other pages. There is a white line coming below the navbar.
![screenshot from 2018-10-25 17-58-19](https://user-images.githubusercontent.com/31305427/47548116-91e45100-d915-11e8-8822-b42bd0d6d9e8.png)

![screenshot from 2018-10-25 18-00-06](https://user-images.githubusercontent.com/31305427/47548101-855ff880-d915-11e8-8e7d-2323ddba4de2.png)

* Browser Name: chrome
* Browser Version: 70.0.3538.67 (Official Build) (64-bit)
* Operating System: Ubuntu 18.04 LTS

**Comment by lewmoore** [comment]
I can look at this?

**Comment by thecodingaviator** [comment]
@giulianovarriale Have you gotten around?

**Comment by giulianovarriale** [comment]
Noup. Actually, when I ran the master branch locally, the bug was not there anymore.

**Comment by Casva** [comment]
Actually I'm able to see it. I can work on this!

**Comment by mengzy2018** [comment]
That could be the offset，Please check the relevant styles
