### ISSUE TITLE
Seek & Destroy Instructions Unclear

### ISSUE THREAD

**Issue by KidLogic** [FreeCodeCamp/freecodecamp#293]
source: http://www.freecodecamp.com/bonfires/seek-and-destroy

Currently Reads: "Remove all values (last argument(s)) from an array (first argument) and return as a new array."

Issue: From my understanding, the user is all the values from an array. However, the information in the parentheses (e.g "last argument(s) and "first argument") seem confusing. Can you please ellaborate further?

**Comment by brndnb** [comment]
Here's another way of saying it:

You will be provided with an array (the first argument in the `destroyer` function) and one or more values (the remaining arguments in the `destroyer` function) that must be removed from that array.

If you look at the current tests, the arguments are similar: 1 array and 2 values. The instructions are asking you to remove as many values as are provided, but you will pass the tests if you only account for two (this will most likely be updated in the future).

Does that help?

**Comment by duttakapil** [comment]
In the more information section we should mention about the `Arguments` object of JavaScript, and also perhaps link to the MDN page of it. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments

**Comment by QuincyLarson** [comment]
@duttakapil @brndnb See updated copy: https://www.evernote.com/shard/s116/sh/6fbbab71-ce38-4fa0-b1e1-7b80b8a69b6b/861bee4d37ab481d0860e0690addad98/deep/0/Seek-and-Destroy---Free-Code-Camp.png and pull request #311
