### ISSUE TITLE
Move static assets to CDN

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#2930]
This will greatly improve page load performance, especially for those of our campers oversees.

**Comment by leonfeng** [comment]
Please note that many western CDN's are blocked in China. I often have trouble loading Gitter because of that.

Here's a Quora post on this topic: https://www.quora.com/Which-are-the-CDN-services-available-for-users-from-China-as-of-2015

**Comment by bugron** [comment]
@BerkeleyTrue what's the progress on this issue?

**Comment by BerkeleyTrue** [comment]
This is on hold until I hear back from cloudFlare on China support.

**Comment by bugron** [comment]
cc @QuincyLarson

**Comment by BerkeleyTrue** [comment]
We now use CloudFlare! Woot!
