### ISSUE TITLE
Waypoint: Write Reusable JavaScript with Functions

### ISSUE THREAD

**Issue by 0-cool** [FreeCodeCamp/FreeCodeCamp#2932]
Challenge http://www.freecodecamp.com/challenges/waypoint-write-reusable-javascript-with-functions has an issue. 

My code does exactly what the job calls and still not completed the task.
Even in the compiler works fine but also the task is not completed.

var a = 4;
var b = 5;

function ourFunction() {
  return (a + b);
};

**Comment by bugron** [comment]
@0-cool thanks for posting this issue!
Instruction says:
>Create and call a function called **myFunction** that returns the sum of a and b.

So your code is correct and you function's name (**ourFunction**) not. Just replace **ourFunction** by **myFunction** and you'll be able to pass the test.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by 0-cool** [comment]
thank youu!

**Comment by bugron** [comment]
@0-cool thanks for posting this issue!
You're welcome. You can close this issue now, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
