### ISSUE TITLE
error in largest of four bonfire

### ISSUE THREAD

**Issue by dogbert831** [FreeCodeCamp/FreeCodeCamp#2933]
Challenge http://freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible. My code is below and runs fine in Firebug console:
function largestOfFour(arr) {
    var matrix = arr;
    var longestNum = 0;
    var longestArray = [];
    for (var i = 0; i < matrix.length; i++) {
        longestNum = 0;
        for (var j = 0; j < matrix[i].length; j++){
          if (longestNum < matrix[i][j]) {
              longestNum = matrix[i][j];
          }
        }
        longestArray.push(longestNum); // push highest value in first sub array       
   }
   return longestArray;
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

In Firefox, it gives the error largestOfFour(...). should is undefined.
In Chrome, it gives the error cannot read propery 'eql' of undefined.

**Comment by BerkeleyTrue** [comment]
Closing as there are many duplicates of this and a couple of PR's to fix. See https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2928

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github
