### ISSUE TITLE
My solution works in node.js but not in FCC

### ISSUE THREAD

**Issue by mlswartz** [FreeCodeCamp/FreeCodeCamp#2935]
Challenge http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

My solution for the 'check for palindromes' works in node.js but not in FCC. Included is my code which I would like for you to run in node.js and also two screenshots, one is the FCC screen showing one red error and the other is from my command prompt showing the results. Please fix the error on your side so that my working solution will pass your test. Thank you.

`// Check for Palindromes`

`function palindrome(str) {`
`    // load only chars into the string`
`    var newString = "";`
`    for (var i = 0; i < str.length; i++) {`
`        if (str[i].match(/[a-z]/i)) {`
`            newString = newString + str[i];`
`        }`
`    }`

`    console.log(newString);`

`    // reverse 'newString'`
`    var tmp = "";`
`    for (var i = newString.length; i > 0; i--) {`
`        if (newString[i - 1].match(/[a-z]/i)) {`
`            tmp = tmp + newString[i - 1];`
`        }`
`    }`

`    console.log(tmp);`

`    // test if the passed in string is a palindrome`
`    if (tmp === newString) {`
`        return true;`
`    }`

`    else {`
`        return false;`
`    }`
`}`

`console.log(palindrome("A man, a plan, a canal. Panama".toLowerCase()));`

![screenshot-1](https://cloud.githubusercontent.com/assets/13187455/9588125/be3633c2-4fe3-11e5-8f8a-7ba8210b7c5b.jpg)
![screenshot-2](https://cloud.githubusercontent.com/assets/13187455/9588129/c4111546-4fe3-11e5-8998-8cbb0d1f8c3b.jpg)

**Comment by Mansuro** [comment]
In the first loop you are only loading lowercase chars, uppercase chars have to be loaded as well

**Comment by abhisekp** [comment]
@benmcmahon100 Irrelevant issue. Please close it.

**Comment by benmcmahon100** [comment]
Closing as stale
