### ISSUE TITLE
Use basket.js to cache static assets in localStorage

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#2936]
http://addyosmani.github.io/basket.js/

This should help speed up page loads.

**Comment by bugron** [comment]
Sounds good. @BerkeleyTrue are you working on this issue?

**Comment by ltegman** [comment]
@BerkeleyTrue Is this still something we're planning on doing?

**Comment by BerkeleyTrue** [comment]
Yes

**Comment by BerkeleyTrue** [comment]
We'll be using service workers now that we are full SSL!

**Comment by ooade** [comment]
@BerkeleyTrue I can take this anytime you're ready :)
