### ISSUE TITLE
When i hit run code it does not save my code.

### ISSUE THREAD

**Issue by happpyier** [FreeCodeCamp/FreeCodeCamp#2937]
Challenge http://www.freecodecamp.com/challenges/bonfire-chunky-monkey has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by happpyier** [comment]
If I hit run code it runs the code to test it, but if i leave the page the code is not saved so when i go back to it i can just pick right back up on where i started.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate #2894

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!
