### ISSUE TITLE
Code won't save in editor even after clicking submit

### ISSUE THREAD

**Issue by ghost** [FreeCodeCamp/FreeCodeCamp#2938]
Challenge http://www.freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Hi, from #7 and onwards, none of the code I submitted have been saved in the editor. I submitted my finished code a few times to see if it would save, but it hasn't. There's a check mark next to #7 - #10, but when I click on it, the only code that's there is the stuff you provided us like the function, the function call and arguments. 

Also, if I accidentally hit the back button, none of the code I write gets saved. So if I leave the page and come back, I have to start over. Usually it's okay since I get extra practice, but other times I want to move onto the next exercise. 

Thanks!

**Comment by benschenker** [comment]
Hey I can't replicate this issue.  I'm going to assume it has been fixed and close this.  Feel free to reopen if it has not been resolved.
