### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by vakalacom** [FreeCodeCamp/FreeCodeCamp#2939]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-first-character-in-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by awesomeaniruddh** [comment]
Please provide more details regarding your issue with the challenge?

**Comment by natac13** [comment]
This challenge works fine for me

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!
