### ISSUE TITLE
An Array, not And Array

### ISSUE THREAD

**Issue by danieldrasdo** [FreeCodeCamp/FreeCodeCamp#2940]
Challenge http://freecodecamp.com/challenges/waypoint-condense-arrays-with-reduce has an issue. It should state 'an array', not 'and array'.
![cap](https://cloud.githubusercontent.com/assets/11982758/9593491/0bfdc6ae-5004-11e5-858a-01735bf0dad3.png)

**Comment by awesomeaniruddh** [comment]
Thanks for the catch, on it!

**Comment by iheartkode** [comment]
@danieldrasdo Can we close this as there is a fix in place? Thanks :)

**Comment by bugron** [comment]
@danieldrasdo thank you for pointing this out! The patch was merged so I'm closing this issue,
