### ISSUE TITLE
Edge Browser Compatibility?

### ISSUE THREAD

**Issue by austintford** [FreeCodeCamp/FreeCodeCamp#2942]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![image](https://cloud.githubusercontent.com/assets/13974187/9595537/4f563cfa-502d-11e5-954c-7175855d4055.png)
While working through the jQuery waypoints in the Edge Browser the submit button and shortcut key do not work and the task list disappears or goes invisible.  It seems to begin as soon as the jQuery script code is added and interpreted by the browser.  This does not happen in FireFox.

**Comment by iheartkode** [comment]
There is no edge browser support yet, can anyone confirm this? @BerkeleyTrue ?

**Comment by BerkeleyTrue** [comment]
Edge does not support shared web workers and we require it for testing.

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Unfortunately, at the moment we only officially support Chrome. (Chromium should also work).

Happy Coding!
