### ISSUE TITLE
Challenge test is failing for what seems correct code.

### ISSUE THREAD

**Issue by netnacool** [FreeCodeCamp/FreeCodeCamp#2947]
Challenge http://freecodecamp.com/challenges/waypoint-size-your-images has an issue.
The challenge is failing the second test "Your image should be 100 pixels wide", for code that is working as required. 

Here is a screenshot : 

![freecodecamp_bug](https://cloud.githubusercontent.com/assets/4660469/9599018/e5794954-50ad-11e5-8ea8-86b4b70f9b95.png)

Below is my code for the challenge.
```
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }
  
  .smaller-image {
    width:  100px;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class = 'smaller-image' src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by awesomeaniruddh** [comment]
The challenge is successfully passing for me?

**Comment by bugron** [comment]
@netnacool thanks for posting this issue!
I passed the tests with you code too. I've tried in FF 38 Incognito mode. [Proof](http://prntscr.com/8bdtfn). Try to [Refresh Your Browser Cache](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache) and [Clear Your Browser's Local Storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser%27s-Local-Storage), this may help you.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by netnacool** [comment]
I am using **Chrome version 44.0.2403.155 (64-bit)** in normal mode. I tried the following on it to get this to work. 
* Refresh Cache -> *Did not work*
* Clear Local Storage -> *Did not work*
* Restart Machine -> *Did not work*

I then switched to **FF 40.0** normal mode and it worked on first try.

So it seems the problem is with the browser but I can't figure out what.

**Comment by bugron** [comment]
@netnacool if your problem is solved feel free to close this issue, thanks.
