### ISSUE TITLE
Confusing waypoint output

### ISSUE THREAD

**Issue by ozjohnson** [FreeCodeCamp/FreeCodeCamp#2948]
Challenge http://freecodecamp.com/challenges/waypoint-iterate-with-javascript-for-loops has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Reproduce by completing lesson correctly.

Output message is showing the last value of the array (5) rather than the lesson objective as stated in the assert: 'myArray should equal [0,1,2,3,4]').  Could be confusing for new programmers.

![image](https://cloud.githubusercontent.com/assets/613644/9599894/a0f3a6c6-50da-11e5-8313-717ae50a15e4.png)

**Comment by dmytroyarmak** [comment]
I'm going to add the same thing as for http://freecodecamp.com/challenges/waypoint-modify-array-data-with-indexes. So user will be able to see content of actual array.

**Comment by bugron** [comment]
@ozjohnson thanks for posting this issue!
@dmytroyarmak I don't have such [a problem](http://prntscr.com/8bfbmg).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
