### ISSUE TITLE
Not working short hex code

### ISSUE THREAD

**Issue by sprihozhiy** [FreeCodeCamp/FreeCodeCamp#2951]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-hex-code-to-color-elements-white has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
----------------------------------------------------------
Short hex code not supported.

**Comment by sersy** [comment]
<style>
  body { color: #FFFFFF; }
</style>

**Comment by sprihozhiy** [comment]
#FFFFFF - it's not short hex code. I mean #fff

**Comment by awesomeaniruddh** [comment]
This is not a bug. It is intended. Short hex codes come a couple waypoints later.

**Comment by sprihozhiy** [comment]
thanks!
