### ISSUE TITLE
Grammatical error in the description.

### ISSUE THREAD

**Issue by vikrantnegi007** [FreeCodeCamp/FreeCodeCamp#2952]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

There is a grammatical error in the description in the line 2. 
Current line: from which inherit their properties.
Correction: from which **they** inherit their properties.

**Comment by awesomeaniruddh** [comment]
Nice catch. Fixing this.

**Comment by natac13** [comment]
Submitted PR for this #2954

**Comment by natac13** [comment]
@awesomeaniruddh oh sorry I must of been fixing when you posted sorry!

**Comment by awesomeaniruddh** [comment]
It's okay! I just discovered that I already have a pending PR which will cause issues.

**Comment by bugron** [comment]
@vikrantnegi007 thank you for pointing this out! The patch was merged so I'm closing this issue,
