### ISSUE TITLE
Waypoint "Target a Specific Child of an Element Using jQuery" has ambiguous instructions

### ISSUE THREAD

**Issue by awesomeaniruddh** [FreeCodeCamp/FreeCodeCamp#2955]
Link to waypoint: http://freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery

There have been quite a few people asking for help regarding this waypoint in the Help channel.

It turns out that their code doesn't work because instead of targeting the `nth-child` of the `target` class, they are targeting the `nth-child` of the `well` class or the `left-well`/`right-well` IDs. The reason for this seems to be the previous waypoint, where the campers target the parent of the `left-well` ID.

The code sample in the waypoint's description uses the `target` class, but I believe that this is not clear enough. The test cases also do not mention the `target` class (but rather the `well` class). As a camper, I myself struggled with this for quite a while before I figured out that I had to use the `target` class.

 The description of the waypoint could be edited to explicitly state that the user must use the `target` class. The test cases must also be edited to mention the `target` class.

**Comment by inkleind** [comment]
Thank you for clarifying this for me. I've been stuck on it trying well left-well right-well, all kinds of wells.
