### ISSUE TITLE
Bonfire: how to display a value of variable in a function

### ISSUE THREAD

**Issue by AmeBel** [FreeCodeCamp/FreeCodeCamp#2958]
I would like to see the varaible value in the side panel , how can i do that. I tried using `alert` & `console.log` to no effect.

Thanks

**Comment by awesomeaniruddh** [comment]
return the variable.

This is not really an issue, but something that should be asked in the FCC Help Chat: https://gitter.im/FreeCodeCamp/Help

Please avoid making an issue for anything that is not a bug with FCC itself. The reporting guidelines: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug

**Comment by AmeBel** [comment]
i did ask didn't get a response thus i asked here

**Comment by AmeBel** [comment]
my bad i asked on https://gitter.im/FreeCodeCamp/FreeCodeCamp
