### ISSUE TITLE
error

### ISSUE THREAD

**Issue by vishdha** [FreeCodeCamp/FreeCodeCamp#2961]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-conditional-logic-with-ifelse-statements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![image](https://cloud.githubusercontent.com/assets/6947417/9610071/d3bc5246-50f4-11e5-8bb8-3294e7370128.png)

**Comment by bugron** [comment]
@vishdha thanks for posting this issue!
Take a look [at this](http://prntscr.com/8bfgoa).
And next time, please, provide a description of your issue, thanks.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
