### ISSUE TITLE
No Session & Cookie exercise listed in the menu for wp web apps with express - expressworks

### ISSUE THREAD

**Issue by CharlesMilam** [FreeCodeCamp/FreeCodeCamp#2963]
Challenge http://freecodecamp.com/challenges/waypoint-build-web-apps-with-expressjs has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Run expressworks and no listing in the menu for Session and Cookie.

![expresscode9bug-nocookies](https://cloud.githubusercontent.com/assets/9435571/9612720/c6da4008-50ac-11e5-9d97-efd630788fe9.png)

**Comment by bugron** [comment]
@CharlesMilam thanks for posting this issue!
I'm closing this issue as a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2603. You can continue further discussion there.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by CharlesMilam** [comment]
Ah, sorry, should have done my due diligence and checked for existing
issue, but had already submitted before doing so.

My apologies.
