### ISSUE TITLE
JSON challenge object to Markdown

### ISSUE THREAD

**Issue by NitronR** [freeCodeCamp/freeCodeCamp#29630]
@raisedadead I have some Rosetta Code challenges ready to be pushed but they are in JSON format. Is there a tool for converting JSON challenge object to Markdown? Thanks for the help!!

**Comment by sdabhi23** [comment]
I would like to help on this one. Can you please share the exact format of the JSON object?

**Comment by NitronR** [comment]
Sure! Here you go:
```
{
    "title": "title here",
    "description": [
       "multi",
       "line",
       "description"
    ],
    "solutions": [
      "solution here".
      "can be multiline"
    ],
    "tests": [
      {
        "text": "'",
        "testString": ""
      }
    ],
    "id": "id here",
    "challengeType": 5,
    "files": {
      "indexjs": {
        "contents": [
            "challenge",
            "seed",
            "here"
        ],
        "head": [ 
              "head",
              "section" 
         ],
        "tail": [ 
             "tail",
             "section"
         ]
      }
    }
  }
```

**Comment by sdabhi23** [comment]
@raisedadead can I start working on this?

**Comment by NitronR** [comment]
@raisedadead I have made a script for this. I will push the rest of the Rosetta Code problems and then move onto Project Euler.
@sdabhi23 Got some free time recently and decided to make this. Thank you for your interest in this issue.
