### ISSUE TITLE
Last test fails to recognize 3 required calls to random number code

### ISSUE THREAD

**Issue by timsatterfield** [FreeCodeCamp/FreeCodeCamp#2964]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-javascript-slot-machine has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I am unclear on why this is not passing the final test case, as all three slots are correctly populated with a random number

<code>
 slotOne = Math.floor(Math.random() * (3-1+1) + 1);
  slotTwo = Math.floor(Math.random() * (3-1+1) + 1);
  slotThree = Math.floor(Math.random() * (3-1+1) + 1);
    
</code>

**Comment by timsatterfield** [comment]
I reset the challenge and now it passes all tests. 

There must be some underlying bug in the validation code that was stuck in a non-passing state.

**Comment by Dylan323i** [comment]
Oddly enough I'm having this problem on my mobile phone...my best guess for my situation is that the browser doesn't support .floor
