### ISSUE TITLE
Spelling Error DNA Pairing

### ISSUE THREAD

**Issue by danieldrasdo** [FreeCodeCamp/FreeCodeCamp#2966]
Challenge http://freecodecamp.com/challenges/bonfire-dna-pairing has an issue. The word 'charater' should be 'character'.

**Comment by bugron** [comment]
@danieldrasdo thanks for pointing this out!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
