### ISSUE TITLE
HTML challanges are not advanced automatically or manually

### ISSUE THREAD

**Issue by ASidlinskiy** [FreeCodeCamp/FreeCodeCamp#2969]
After I complete html challenge it's not going to the next challenge and it's not providing me a way to go to the next challenge unless I exit my current(completed) challenge and navigate to "Map" page listing all the challenges.

**Comment by benschenker** [comment]
Hey @ASidlinskiy thanks for posting this issue!

I'm unable to replicate this, it may have been fixed.

I'll close this for now, but please reopen if this is not resolved for you.
