### ISSUE TITLE
Courseware Color a Bootstrap Button with Button Primary worded incorrectly  

### ISSUE THREAD

**Issue by yaskyj** [FreeCodeCamp/freecodecamp#297]
Instructions are the same for the btn-block course: "Add Bootstrap's btn-block class to both of your buttons."

**Comment by QuincyLarson** [comment]
Thanks for QA'ing our first-party courseware. We've put development of these courseware on hold for the next few months while we focus on lower-hanging fruit (Bonfires, Ziplines and Basejumps), along with refining our Nonprofit projects. We'll QA these courseware later.
