### ISSUE TITLE
Bonfire: Where do I belong tests disappear after running code

### ISSUE THREAD

**Issue by mmayes098** [FreeCodeCamp/FreeCodeCamp#2971]
Challenge http://www.freecodecamp.com/challenges/bonfire-where-do-i-belong has an issue. After I wrote my code for Where do I belong, I clicked on run code. All the tests (below the buttons) then disappeared, and the output window did not update to show the correct value being returned (as you can see in the screenshot). I am using Safari 8.0.8 in Mac OS X 10.10.5. Also after a couple of minutes, the bonfire page reloaded with a Safari error saying "A problem occurred with this webpage so it was reloaded.
![screen shot 2015-09-01 at 4 51 33 pm](https://cloud.githubusercontent.com/assets/13262298/9616070/25e5b13c-50ca-11e5-93e4-6ce09780706e.png)

**Comment by jameskopacz** [comment]
@mmayes098 This is being caused by an infinite loop in your code.

```
  for(var i=0;i<arr.length;i++) {
    if (num >= arr[i] && num <= arr[i+1]) {
      arr.splice(i,0,num);
    }
  }
```
```arr.splice(i,0,num);``` is adding ```num``` to ```arr``` so even with ```i++``` ```arr.length``` never gets less than ```i```.
