### ISSUE TITLE
Bonfire: Sum All Odd Fibonacci Numbers -  sumFibs(75025);

### ISSUE THREAD

**Issue by nkhoshaf** [FreeCodeCamp/FreeCodeCamp#2973]
![screen shot 2015-09-01 at 5 28 20 pm](https://cloud.githubusercontent.com/assets/9994709/9617093/e9696a50-50ce-11e5-858c-1e4743fd11a5.png)
All the inputs works except for sumFibs(72025).  

What am I missing here?

**Comment by vanblargan** [comment]
I ran into this same problem, but fixed it. The directions were misleading, it implies the numbers that you add should be strictly less than num, but it turns that you add numbers that are "at most" num.
