### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by psteger** [FreeCodeCamp/FreeCodeCamp#2974]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-bootstrap-wells has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The first test case has a typo. The text "div class="col-xs-6"> elements" shouldn't have the '>' character.

**Comment by natac13** [comment]
I can work on this

**Comment by bugron** [comment]
@psteger thanks for pointing this out!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
