### ISSUE TITLE
Unable to install FCC locally

### ISSUE THREAD

**Issue by jameskopacz** [FreeCodeCamp/FreeCodeCamp#2976]
Following the "Getting Started" instructions. Using Windows 7.

When running ```npm install`` I get these errors:

> npm WARN package.json Dependency 'babel-eslint' exists in both dependencies and devDependencies, using 'babel-eslint@^4.0.5' from dependencies
> npm WARN package.json Dependency 'eslint' exists in both dependencies and devDependencies, using 'eslint@^1.1.0' from dependencies
> npm WARN package.json Dependency 'eslint-plugin-react' exists in both dependencies and devDependencies, using 'eslint-plugin-react@^3.2.1' from dependencies
> npm ERR! fetch failed https://github.com/BerkeleyTrue/react-router#freecodecamp
> npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
> npm ERR! fetch failed https://github.com/FreeCodeCamp/loopback.git#fix/no-password
> npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
> npm WARN deprecated gulp-webpack@1.5.0: Renamed to https://www.npmjs.com/package/webpack-stream
> npm ERR! fetch failed https://github.com/FreeCodeCamp/loopback-component-passport.git#feature/flashfailure
> npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
> npm ERR! fetch failed https://github.com/BerkeleyTrue/react-router#freecodecamp
> npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
> npm ERR! fetch failed https://github.com/FreeCodeCamp/loopback.git#fix/no-password
> npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
> npm ERR! fetch failed https://github.com/FreeCodeCamp/loopback-component-passport.git#feature/flashfailure
> npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
> npm ERR! fetch failed https://github.com/BerkeleyTrue/react-router#freecodecamp
> npm ERR! fetch failed https://github.com/FreeCodeCamp/loopback.git#fix/no-password
> npm ERR! fetch failed https://github.com/FreeCodeCamp/loopback-component-passport.git#feature/flashfailure
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "E:\\Program Files\\nodejs\\\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
> npm ERR! node v0.12.0
> npm ERR! npm  v2.5.1
> 
> npm ERR! fetch failed with status code 406

**Comment by bugron** [comment]
@jameskopacz while installing FCC locally I was ignoring all errors that I was getting from `npm install` or `bower install`. It's more important to make sure that you've correctly installed and configured MongoDB.

**Comment by jameskopacz** [comment]
@bugron I kept going through the instructions and ran into these errors:

> node seed/
> module.js:338
>    throw err;
>          ^
> Error: Cannot find module 'babel/register'

> gulp
> module.js:338
>    throw err;
>          ^
> Error: Cannot find module 'babel-core/register'

:(

**Comment by bugron** [comment]
>Error: Cannot find module 'rx'
Error: Cannot find module 'gulp-plumber'
Error: Cannot find module 'gulp-notify'
Error: Cannot find module 'gulp-reduce-file'
Error: Cannot find module 'sort-keys'

Install all these modules then try to run `gulp` and report to me, thanks.

**Comment by jameskopacz** [comment]
Going through it now. Adding to this list as I get errors saying the module cannot be found:

> debug
> gulp-webpack
> webpack
> gulp-nodemon
> browser-sync
> gulp-less
> gulp-rev
> gulp-rev-replace
> gulp-jsonlint
> gulp-eslint
---
```gulp``` finally worked:

> E:\www\public_html\github\freecodecamp>gulp
> [04:52:03] Using gulpfile E:\www\public_html\github\freecodecamp\gulpfile.js
> [04:52:03] Starting 'less'...
> [04:52:03] Starting 'serve'...
> [04:52:03] Starting 'js'...
> [04:52:03] Starting 'pack-client'...
> [04:52:03] Starting 'pack-watch'...
> [04:52:03] Version: webpack 1.12.1
> 
> ERROR in Entry module not found: Error: Cannot resolve module 'babel-loader' in E:\www\public_html\github\freecodecamp
> [04:52:03] Finished 'pack-client' after 374 ms
> [04:52:03] Version: webpack 1.12.1
> 
> ERROR in Entry module not found: Error: Cannot resolve module 'babel-loader' in E:\www\public_html\github\freecodecamp
> [04:52:03] webpack is watching for changes
> [04:52:04] [nodemon] v1.4.1
> [04:52:04] [nodemon] to restart at any time, enter `rs`
> [04:52:04] [nodemon] watching: *.*
> [04:52:04] [nodemon] starting `E:\www\public_html\github\freecodecamp\node_modules\.bin\babel-node ./server/server.js`
> 'E:\www\public_html\github\freecodecamp\node_modules\.bin\babel-node' is not recognized as an internal or external command,
> operable program or batch file.
> [04:52:06] [nodemon] app crashed - waiting for file changes before starting...
> [04:52:06] Finished 'serve' after 2.64 s
> [04:52:06] [nodemon] restarting due to changes...
> [04:52:06] [nodemon] starting `E:\www\public_html\github\freecodecamp\node_modules\.bin\babel-node ./server/server.js`
> 'E:\www\public_html\github\freecodecamp\node_modules\.bin\babel-node' is not recognized as an internal or external command,
> operable program or batch file.
> [04:52:06] [nodemon] restarting due to changes...
> [04:52:06] Finished 'js' after 2.69 s
> [04:52:06] Starting 'dependents'...
> [04:52:06] [nodemon] starting `E:\www\public_html\github\freecodecamp\node_modules\.bin\babel-node ./server/server.js`
> [04:52:06] [nodemon] restarting due to changes...
> 'E:\www\public_html\github\freecodecamp\node_modules\.bin\babel-node' is not recognized as an internal or external command,
> operable program or batch file.
> [04:52:06] [nodemon] restarting due to changes...
> [04:52:06] [nodemon] starting `E:\www\public_html\github\freecodecamp\node_modules\.bin\babel-node ./server/server.js`
> [04:52:06] [nodemon] restarting due to changes...
> 'E:\www\public_html\github\freecodecamp\node_modules\.bin\babel-node' is not recognized as an internal or external command,
> operable program or batch file.
> [04:52:06] Finished 'less' after 2.81 s
> [04:52:06] [nodemon] starting `E:\www\public_html\github\freecodecamp\node_modules\.bin\babel-node ./server/server.js`
> [04:52:06] [nodemon] restarting due to changes...
> [04:52:06] [nodemon] restarting due to changes...
> 'E:\www\public_html\github\freecodecamp\node_modules\.bin\babel-node' is not recognized as an internal or external command,
> operable program or batch file.
> [04:52:06] [nodemon] starting `E:\www\public_html\github\freecodecamp\node_modules\.bin\babel-node ./server/server.js`
> [04:52:06] [nodemon] restarting due to changes...
> [04:52:06] Finished 'dependents' after 212 ms
> [04:52:06] Starting 'build-manifest'...
> [04:52:06] [nodemon] restarting due to changes...
> 'E:\www\public_html\github\freecodecamp\node_modules\.bin\babel-node' is not recognized as an internal or external command,
> operable program or batch file.
> [04:52:06] [nodemon] starting `E:\www\public_html\github\freecodecamp\node_modules\.bin\babel-node ./server/server.js`
> 'E:\www\public_html\github\freecodecamp\node_modules\.bin\babel-node' is not recognized as an internal or external command,
> operable program or batch file.
> [04:52:06] Finished 'build-manifest' after 78 ms
> [04:52:06] Starting 'sync'...
> [04:52:06] Finished 'sync' after 105 ms
> [04:52:06] Starting 'watch'...
> [04:52:06] Finished 'watch' after 42 ms
> [04:52:06] [nodemon] app crashed - waiting for file changes before starting...
> [BS] Reloading Browsers...
> [BS] Reloading Browsers...
> [BS] Reloading Browsers...
> [BS] Reloading Browsers...
> [BS] Reloading Browsers...
> [BS] Reloading Browsers...
> [BS] Reloading Browsers...
> [BS] Reloading Browsers...
> [BS] Reloading Browsers...
> [BS] Proxying: http://localhost:3000
> [BS] Access URLs:
>  --------------------------------------
>        Local: http://localhost:3001
>     External: http://192.168.0.109:3001
>  --------------------------------------
>           UI: http://localhost:3002
>  UI External: http://192.168.0.109:3002
>  --------------------------------------
> [BS] Watching files...

**Comment by abhisekp** [comment]
I was also getting the rev-manifest missing error.

I first ran `gulp`. While it was running, then I did `node seed/`.
After that I didn't get any errors.

After that I stopped and restarted `gulp`.

Then browsed to http://localhost:3001/

Works perfectly. :+1:
