### ISSUE TITLE
Not able to submit

### ISSUE THREAD

**Issue by KcirdnekC** [FreeCodeCamp/FreeCodeCamp#2977]
Challenge http://www.freecodecamp.com/challenges/waypoint-responsively-style-checkboxes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When I click "run" it runs correctly but does not allow me to submit.

**Comment by bugron** [comment]
@KcirdnekC thanks for posting this issue!
Please, provide your code and a screenshot, thank you.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by GadgetAddict** [comment]
I'm having same issue and this is tied to issue that was closed prematurely / 1103
Link: https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1103#issuecomment-137599270

**Comment by benschenker** [comment]
Hey @KcirdnekC, is this still an issue for you?  If so can you provide some more details/screenshots to aid us in tracking this down?
