### ISSUE TITLE
Am not able to sumbit my code for a challenge

### ISSUE THREAD

**Issue by mini-man** [FreeCodeCamp/FreeCodeCamp#2978]
Challenge http://freecodecamp.com/challenges/bonfire-meet-bonfire has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

All I did was change the line 'return false' to 'return true' and was not able to submit the code.

Have reproduced the issue on different computers.

**Comment by natac13** [comment]
I have tried this on Chrome on windows and it is working fine for me.

**Comment by bugron** [comment]
@mini-man thanks for posting this issue!
I am able to pass this challenge too. Please, provide your code and a screenshot.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by mini-man** [comment]
Have fixed it. It was the computer I was working on
