### ISSUE TITLE
Search autocomplete display out of screen

### ISSUE THREAD

**Issue by sureemo** [freeCodeCamp/freeCodeCamp#29806]
**Describe the bug**
Auto-complete dropdown in Quick search in top navigation bar is out of screen.

**To Reproduce**
1. Go to 'https://learn.freecodecamp.org/'
2. Type text in Search Input at the top navigation bar
3. See the auto-complete dropdown, the block width is out of screen

**Expected behavior**
The search auto-complete dropdown should be displayed properly

**Screenshots**
![search](https://user-images.githubusercontent.com/1849256/47589599-d6aecd00-d993-11e8-8d71-6294ab016bbe.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Chrome

**Comment by RandellDawson** [comment]
I am closing this issue, because it has already been reported on issue #18150.
