### ISSUE TITLE
waypoint 13 of jQuery

### ISSUE THREAD

**Issue by x34passenger** [FreeCodeCamp/FreeCodeCamp#2980]
Challenge http://freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
left-well element is red but still says not correct

**Comment by bugron** [comment]
@x34passenger thanks for posting this issue!
Please, provide your code and screenshot, thanks you.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by natac13** [comment]
@x34passenger do you have ?
```javascript
$("#target1").parent().css("background-color", "red")
```
or 
```javascript
("#left-well").parent().css("background-color", "red")
```
because from your description I believe you have the second which target the div element arond the left well and not the left well itself like the instructions say
