### ISSUE TITLE
Double CatPhoto App

### ISSUE THREAD

**Issue by vgibson15** [FreeCodeCamp/FreeCodeCamp#2981]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Hi this double output or imaging of the programming code has occurred since the upgrade. I have attached the images to the message.

**Comment by vgibson15** [comment]
![bug](https://cloud.githubusercontent.com/assets/13035720/9622214/0c446910-50e5-11e5-8dda-381317ee665d.png)

**Comment by vgibson15** [comment]
![bug2](https://cloud.githubusercontent.com/assets/13035720/9622227/377ae690-50e5-11e5-8e86-9a9318c4d439.png)

**Comment by bugron** [comment]
@vgibson15 thanks for posting this issue!
That was before the upgrade too.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by benschenker** [comment]
Hey @vgibson15,

I'm unable to replicate this, it may have been fixed.  I'll close this issue but please reopen if this is not resolved for you.
