### ISSUE TITLE
Broken "Get a hint" link in "Basic Node and Express - Use the .env File"

### ISSUE THREAD

**Issue by t5krishn** [freeCodeCamp/freeCodeCamp#29831]
**Describe your problem and how to reproduce it:**
The "Get a hint" link in "Basic Node and Express - Use the .env File" coding challenge is incorrect.

Page with get a hint link is : https://learn.freecodecamp.org/apis-and-microservices/basic-node-and-express/use-the--env-file/

It leads to: https://guide.freecodecamp.org/certifications/apis-and-microservices/basic-node-and-express/use-the--env-file

While the guide doc is actually in: https://guide.freecodecamp.org/certifications/apis-and-microservices/basic-node-and-express/use-the-.env-file

There should be a period before the "env-file" instead of a hyphen.

In addition, the "Ask for help" button is non-responsive.

Best,
Thilina

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/apis-and-microservices/basic-node-and-express/use-the--env-file/

**Tell us about your browser and operating system:**
* Browser Name:  Chrome
* Browser Version: 69.0.3497.100
* Operating System: Windows 10 x64

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ezioda004** [comment]
Hi @t5krishn,

Thank you for opening this issue.
We've fixed this issue in a previous PR from this issue https://github.com/freeCodeCamp/freeCodeCamp/issues/28059.
It'll be pushed to production soon.

I'm closing this issue.

Happy coding!

**Comment by mscanza** [comment]
Still doesn't work...

**Comment by RandellDawson** [comment]
@mscanza It has been fixed, but it has not been pushed to production yet.  You can see the fix on the beta site (https://www.freecodecamp.rocks/learn/apis-and-microservices/basic-node-and-express/use-the-.env-file).
