### ISSUE TITLE
Some kind of issue in a waypoint

### ISSUE THREAD

**Issue by kairatomurbek2** [FreeCodeCamp/FreeCodeCamp#2985]
Challenge http://www.freecodecamp.com/challenges/waypoint-make-object-properties-private has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by kairatomurbek2** [comment]
//Let's create an object with a two functions. One attached as a property and one not.
var Car = function() {
  this.gear = 1;
  function addStyle(styleMe){
    return 'The Current Gear Is: ' + styleMe;
  }
  this.getGear = function() {
    return addStyle(this.gear);
  };
};

var Bike = function() {
  // Only change code below this line.
  this.speed = 100;
  function addUnit(value) {
    return value + "KM/H";
  }
  
  this.getSpeed = function () {
    return addUnit(this.speed);
  };
  
};

// Only change code above this line.
var myCar = new Car();
var myBike = new Bike();

if(myBike.hasOwnProperty('getSpeed')){(function() {return JSON.stringify(myBike.getSpeed());})();};

**Comment by bugron** [comment]
@kairatomurbek2 thanks for posting this issue!
Please change the title to a readable one. You **shouldn't** write you whole message in title.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by natac13** [comment]
The bike constructor function is still making the speed variable public in your code @kairatomurbek2... if you are wondering why it doesn't pass....

**Comment by benschenker** [comment]
Closing as stale.  Please reopen if this issue is unresolved.
