### ISSUE TITLE
Example given in the description is missing "=" 

### ISSUE THREAD

**Issue by vikrantnegi007** [FreeCodeCamp/FreeCodeCamp#2988]
Challenge http://www.freecodecamp.com/challenges/waypoint-write-reusable-javascript-with-functions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In the description where there is an example of the function there is a missing "=" sign.

Here is the code: 
Here's an example of a function:
```javascript
function functionName (a, b) {
  return a + b;
}
```

which should be corrected as like this: 
```javascript
function = functionName (a, b) {
  return a + b;
};
```
Thank you.

**Comment by awesomeaniruddh** [comment]
Uh, that is not correct. You only use the '=' sign when creating functions like this:

```
var functionName = function(a, b) {
    return a + b;
}
```

So the following piece of code is correct.
```
function functionName (a, b) {
    return a + b;
}
```

**Comment by vikrantnegi007** [comment]
Okay. My mistake. Thanks.
