### ISSUE TITLE
css color class not working

### ISSUE THREAD

**Issue by pepsifraek** [FreeCodeCamp/FreeCodeCamp#2991]
Challenge http://freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![image](https://cloud.githubusercontent.com/assets/14063289/9626506/47fd427a-511b-11e5-9783-74e3c2d2c720.png)

**Comment by awesomeaniruddh** [comment]
While you have assigned the red-text class to the element, you do not have any `style` tags which contain CSS to style that red-text class.

**Comment by pepsifraek** [comment]
thanks
