### ISSUE TITLE
scr http://bit.ly/fcc-running-cat is not found.

### ISSUE THREAD

**Issue by johnthomascookii** [FreeCodeCamp/FreeCodeCamp#2994]
Challenge http://www.freecodecamp.com/challenges/waypoint-make-images-mobile-responsive has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In the problem, the image http://bit.ly/fcc-running-cat is not found.

**Comment by bugron** [comment]
@johnthomascookii thanks for posting this issue!
@BerkeleyTrue I can confirm that image is not found. @johnthomascookii thanks for pointing this out!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by Mansuro** [comment]
@bugron the image is http://bit.ly/fcc-running-cats not http://bit.ly/fcc-running-cat

**Comment by bugron** [comment]
@Mansuro thanks! http://prntscr.com/8c41d9. Closing this issue.
