### ISSUE TITLE
Waypoint: Build Web Apps with Express.js - JSON me exercise fails to verify - expressworks

### ISSUE THREAD

**Issue by CharlesMilam** [FreeCodeCamp/FreeCodeCamp#2995]
Per Ben Schenker, was asked to create a new issue concerning this waypoint.

JSON me, the final exercise fails to verify. I attempted to format the answer in multiple ways to satisfy the test, all of which failed. I then researched the Expressworks repo. I examined their solution to the exercise, it was nearly identical to mine. I then entered their solution into the exercise, it too failed to verify.

Currently their appears not a way to have the exercise answer formatted in a way that passes the exercises test. 

The issue appears to be that the test wants the output to all appear on one line. I have not been able to figure out a way to format the answer so that it passes this test. The repo's own solution formats its answer in the same way as mine, and it also fails to pass the test. 

Below is the output of the test
![expresscode9bug-nocookies](https://cloud.githubusercontent.com/assets/9435571/9635843/f285301c-515d-11e5-8c96-761a2f08297f.png)

**Comment by CharlesMilam** [comment]
Correction: here is the correct screen shot of output
![jsonme-solution-output](https://cloud.githubusercontent.com/assets/9435571/9635918/516b22d0-515e-11e5-83d5-1f542dd8edeb.png)

**Comment by prashcr** [comment]
Try
```
res.send(JSON.stringify(query));
```

**Comment by su6a12** [comment]
@prashcr That didn't work for me.
<img width="1201" alt="screen shot 2015-09-05 at 9 24 56 am" src="https://cloud.githubusercontent.com/assets/6955254/9700219/22fea58a-53b0-11e5-9d6f-110f9b5c05e6.png">

**Comment by jonslucas** [comment]
@su6a12 I had this same issue with this one.  I think that it has something to do with cloud9, since I was unable to replicate the issue on my local ubuntu machine.
Try using this:
`res.send(JSON.stringify(JSON.parse(data.toString())));`

**Comment by su6a12** [comment]
@jonslucas Thanks!  It worked!

**Comment by BerkeleyTrue** [comment]
@CharlesMilam Expressworks is an open source project. If you are experiencing issues with expressworks they should be filed against that repo here https://github.com/azat-co/expressworks. Also, in the future please read https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-help-when-you-get-stuck

Happy Coding!

**Comment by bheavner** [comment]
I think @jonslucas is right - it may be that cloud9 has express installed globally. the JSON.stringify workaround does work, but doesn't address the underlying cloud9 issue. See these issues on Expressworks: [70](https://github.com/azat-co/expressworks/issues/70), [90](https://github.com/azat-co/expressworks/issues/90), [82](https://github.com/azat-co/expressworks/issues/82) (and there are others)

**Comment by BerkeleyTrue** [comment]
> - it may be that cloud9 has express installed globally

Express isn't a cli (meaning it would do nothing as a command line tool). Even if it was installed globally, doing `var express = require('express');` would not work. It would throw as express needs to be installed locally to the project root. 

Maybe you meant C9 has ExpressWorks installed globally?

**Comment by jonslucas** [comment]
@bheavner @BerkeleyTrue It's not so much that express is installed globally (by npm), but that the default version pre-installed by cloud9 is version is v3.2.6, instead of the current version (v4.13.3 at this time).  Looking at the ExpressWorks issue 70 that you reference, there is an excellent breakdown by meowfcc who asserts that the different versions of express have different default values for `json spaces`.

Best working solution is not to use the hack that I suggested above but to correct the version mismatch by using the following two commands:
`npm uninstall express && npm install express@'>=4.0.0'`
Once you've installed the latest version of express, then the 'official solution', which uses `res.json(books)`, will pass.

For those more adventurous, it may be worthwhile to add that line to @reddock's bash script and submit a pull request with that edit.

**Comment by SaintPeter** [comment]
@BerkeleyTrue Please advise if we should add the above workaround to the setup steps.

**Comment by BerkeleyTrue** [comment]
@SaintPeter Have you gotten that far?

**Comment by bheavner** [comment]
Seems like it would be good to file an issue with C9, but they have so many repositories, I'm not sure where the issue would go - any ideas? https://github.com/c9

**Comment by BerkeleyTrue** [comment]
This is fixed with the new install script included in the instructions.

**Comment by bheavner** [comment]
Sweet. Thanks.
