### ISSUE TITLE
long cargo

### ISSUE THREAD

**Issue by kairatomurbek2** [FreeCodeCamp/FreeCodeCamp#2996]
Challenge http://www.freecodecamp.com/challenges/bonfire-inventory-update
Hi!I made the decision all right, press "Run code"  5 minutes ship

**Comment by bugron** [comment]
@kairatomurbek2 thanks for posting this issue!
I don't get it, do you have any problems? If so, please provide more information about issue, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by kairatomurbek2** [comment]
function inventory(arr1, arr2) {
  return arr2.reduce(update,arr1.reduce(update,{})).toArray().sort(invSort);
}

function update(acc,e){
  var ans=acc;
  if (ans[e[1]]===undefined) ans[e[1]]=e[0];
  else ans[e[1]]+=e[0];
  return ans;
}

Object.prototype.toArray = function(){
  var ans=[];
  for (var key in this){
    ans.push([this[key],key]);
  }
  return ans.slice(0,-1);
};

function invSort(a,b){
  if (a[1]<b[1]) return -1;
  if (a[1]===b[1]) return 0;
  return 1;
}

// Example inventory lists
var curInv = [
    [21, 'Bowling Ball'],
    [2, 'Dirty Sock'],
    [1, 'Hair Pin'],
    [5, 'Microphone']
];

var newInv = [
    [2, 'Hair Pin'],
    [3, 'Half-Eaten Apple'],
    [67, 'Bowling Ball'],
    [7, 'Toothpaste']
];

inventory(curInv, newInv);
"this is my code"

On Wed, Sep 2, 2015 at 11:19 PM, Arsen Melikyan <notifications@github.com>
wrote:

> @kairatomurbek2 <https://github.com/kairatomurbek2> thanks for posting
> this issue!
> I don't get it, do you have any problems? If so, please provide more
> information about issue, thanks.
>
> ------------------------------
>
> Please review the *Guidelines for Contributing*
> <https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md>,
> thank you!.
> ------------------------------
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2996#issuecomment-137176989>
> .
>



-- 
С уважением !
Омурбек уулу Кайрат
+996(0700)13-96-80
e-mail: kairatomurbek2@gmail.com
skype: lolakt1

**Comment by benschenker** [comment]
Hi @kairatomurbek2.

As @bugron mentioned, please take a look at the our [Bug Report Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) as it is hard to tell what issue you are experiencing right now and it is difficult to replicate without more information.

**Comment by kairatomurbek2** [comment]
Georgia's debt is the solution, as the press of a button "submit". Prior to
this decision have been

On Thu, Sep 3, 2015 at 11:16 AM, Ben Schenker <notifications@github.com>
wrote:

> Hi @kairatomurbek2 <https://github.com/kairatomurbek2>.
>
> As @bugron <https://github.com/bugron> mentioned, please take a look at
> the our Bug Report Guidelines
> <https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug>
> as it is hard to tell what issue you are experiencing right now and it is
> difficult to replicate without more information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2996#issuecomment-137334383>
> .
>



-- 
С уважением !
Омурбек уулу Кайрат
+996(0700)13-96-80
e-mail: kairatomurbek2@gmail.com
skype: lolakt1

**Comment by benschenker** [comment]
Hey @kairatomurbek2, I believe there may be a language barrier here.

I was able to pass the bonfire by running your solution posted above...What is the problem?
