### ISSUE TITLE
myRemoved

### ISSUE THREAD

**Issue by vakalacom** [FreeCodeCamp/FreeCodeCamp#2997]
Hello,

the var myRemoved contain the string [John], but impossible to validate the challenge...

Challenge http://www.freecodecamp.com/challenges/waypoint-manipulate-arrays-with-shift has an iss
![john](https://cloud.githubusercontent.com/assets/13788882/9639335/9de4ca7e-5179-11e5-93f5-16422a264923.jpg)
ue. Please describe how to reproduce it, and include links to screenshots if possible.

I looking forward to hearing from you,

Kind regards,
PVA

**Comment by vakalacom** [comment]
Hello,

the var "myRemoved" contain the string [John], but impossible to validate the challenge... 
I looking forward to hearing from you,

Kind regards,
PVA

**Comment by natac13** [comment]
@vakalacom can I ask why there are still `.pop()` methods in your code? Challenge is about `.shift()`

**Comment by vakalacom** [comment]
Hi, sorry i didnt send the right print screen, i've trying so many things...
find attached the right one.
![john1](https://cloud.githubusercontent.com/assets/13788882/9645659/1641d0e0-519b-11e5-9416-a05cc29a3b34.jpg)

**Comment by natac13** [comment]
@vakalacom still doing way more than needed to complete the challenge.... the challenge works fine for me...

**Comment by benschenker** [comment]
Hey @vakalacom, I'd recommend you try [Asking for Help on Gitter](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter).  Remember that each line is executed one after the other, so when you have a bunch of similar lines, they can actually conflict.  I'm going to close this as it is easier to explain in the chat room.  Feel free to reopen if you can't get any help there.
