### ISSUE TITLE
Javascript Challenge Works But Doesn't Check Proper Conditional

### ISSUE THREAD

**Issue by rexmorgan89** [FreeCodeCamp/FreeCodeCamp#2999]
Challenge http://www.freecodecamp.com/challenges/waypoint-generate-random-whole-numbers-within-a-range has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
The code input below:
![image](https://cloud.githubusercontent.com/assets/13738161/9639541/3382352e-5172-11e5-9e0f-61b200a9efcd.png)
produces the following output:
![image](https://cloud.githubusercontent.com/assets/13738161/9640190/efbd4fa0-5175-11e5-9924-896dc8657877.png)

which meets the criteria set out in the challenge but doesn't actually produce the proper integer output. 
I've been trying to experiment with the programming practices I know of and I declare a variable to assign the Math.floor(Math.random())*(max - min +1)) + min to a variable called "randomRange" and that's the variable I call. 
![image](https://cloud.githubusercontent.com/assets/13738161/9640334/ba8d1508-5176-11e5-953a-659528aef7f5.png)

Result: 
![image](https://cloud.githubusercontent.com/assets/13738161/9640276/7f5b2402-5176-11e5-9f65-a5a553c16e80.png)

**Comment by dmytroyarmak** [comment]
Thank you for your report. I'll improve test cases to actualy check that random value is returned.
