### ISSUE TITLE
Code not recognized

### ISSUE THREAD

**Issue by maikelsperandio** [FreeCodeCamp/FreeCodeCamp#3000]
Challenge http://freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I put the code of the "a" element nested on the "p" element but it wasn't recognized by interpreter.
![bug](https://cloud.githubusercontent.com/assets/534558/9639484/a01d03ac-5182-11e5-8653-8be0bd1b4e28.JPG)

**Comment by bugron** [comment]
@maikelsperandio thanks for posting this issue!
I am able to pass that test with your code Tried both in FF 38 and Chrome 43.
Note that you need to nest **your** `a` element in a new `p` element, which means your **exciting**  
>Now nest **your** a element within a new p element so that the surrounding paragraph says "click here for cat photos", but where only "cat photos" is a link, and the rest of the text is rest is plain text.

There is a merged PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/2880 hopefully soon it will be in production. 
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
