### ISSUE TITLE
WayCat

### ISSUE THREAD

**Issue by Talcim** [FreeCodeCamp/FreeCodeCamp#3001]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-a-submit-button-to-a-form has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by bugron** [comment]
@Talcim thanks for posting this issue!
Please, provide description of the problem you have, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by benschenker** [comment]
Closing as stale.  Please reopen if this is not resolved.
