### ISSUE TITLE
No documents in parrots collections

### ISSUE THREAD

**Issue by debugpoint136** [FreeCodeCamp/FreeCodeCamp#3004]
Challenge http://www.freecodecamp.com/challenges/waypoint-store-data-in-mongodb has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I wrote this script for this challenge -

```
var url = "mongodb://localhost:27017/learnyoumongo"
var db = "learnyoumongo"
var arg = parseInt(process.argv[2])

var mongo = require('mongodb').MongoClient
    mongo.connect(url, function(err, db) {
      // db gives access to the database
    db.collection('parrots')
        .find({
           age: { $gt: arg }
           }).toArray(function(err, documents) {
                console.log(documents)
            })
        db.close()
      })
```

But I keep getting this error -
![](https://dl.dropboxusercontent.com/spa/ry0atqxaxd315xf/s29rf-zr.png)

I checked from mongo console and noticed that db.parrots.find() doesn't return anything. What am I missing?

Thanks!

**Comment by su6a12** [comment]
You declared a variable "db" and are also using the same name as the parameter in your mongo.connect callback function.  Maybe change the name to something else and try?

**Comment by debugpoint136** [comment]
Thanks for such speedy response!
Tried that. Still no luck.

**Comment by ahstro** [comment]
Did you perhaps run any code that might've emptied the collection at some point?

**Comment by leonfeng** [comment]
You need to move `db.close()` inside `toArray()`:
```js
           }).toArray(function(err, documents) {
                console.log(documents)
                db.close()
            })
      })                
```

**Comment by benschenker** [comment]
Closing as stale/resolved.  Please reopen/comment if this in not resolved for you.
