### ISSUE TITLE
wrote this line of code:

### ISSUE THREAD

**Issue by dmintercept** [FreeCodeCamp/FreeCodeCamp#3008]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

//<script>
//$(document).ready(function(){
//});
//</script>

couldn't submit exercise. 

Using internet explorer version 10.

**Comment by bugron** [comment]
@dmintercept thanks for posting this issue!
FCC's challenge's **are not** working in **any** IE. Please, use another browser, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
