### ISSUE TITLE
Bonfire: Return Largest Numbers in Arrays  - Issue with testing

### ISSUE THREAD

**Issue by infoalisaa** [FreeCodeCamp/FreeCodeCamp#3010]
Hello,

 I am trying to complete this Bonfire, and I am pretty sure I have the right answer. I even tested it out in Chrome, and It seem to be returning the test case just fine.

Here is my code:

function largestOfFour(arr) {
arrResult = [];
var biggest = 0;
for(var i = 0;i for(var j = 0; j if(arr[i][j]>biggest){
biggest = arr[i][j];
}
else{
biggest = biggest;
}
}
arrResult.push(biggest);
}
return arrResult;
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);

I think the problem may be with the second test:

assert.deepEqual( largestOfFour( [[13, 27, 18, 26], [4, 5, 1, 3], [32, 35, 37, 39], [1000, 1001, 857, 1]]), [27,5,39,1001], 'arrays should match.');
arrays should match.: expected [ 27, 27, 39, 1001 ] to deeply equal 

It might be trying to match the final array on [ 27, 5, 39, 1001 ] instead of [ 27, 27, 39, 1001 ].

This is the results of my test in Chrome when I plugged in the test case:

![screen shot 2015-09-02 at 7 52 19 pm](https://cloud.githubusercontent.com/assets/12887861/9649029/6767ea66-51ac-11e5-8113-4ac848e334b8.png)

I hope someone can look into this soon!
If I did do something wrong, please let me know.

Thank you!!

**Comment by suhussai** [comment]
I think your variable "biggest " needs to be set to zero when you move on to the next array.

**Comment by prashcr** [comment]
Yeah, you need to reset biggest to zero after every input array

**Comment by infoalisaa** [comment]
Thanks! I changed my code to reset biggest = 0; after I push the biggest number to the array, and I passed!! :100: 
Really appreciate the help!!! :+1:

**Comment by bugron** [comment]
@infoalisaa if your problem is solved feel free to close this issue, thanks!
