### ISSUE TITLE
GitHubbin - Requires SSH key if two step authentication (2SA) is active on your GitHub account

### ISSUE THREAD

**Issue by thpang67** [FreeCodeCamp/FreeCodeCamp#3011]
Challenge http://freecodecamp.com/challenges/waypoint-save-your-code-revisions-forever-with-git has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

If you have 2SA turned on and you are trying to 'push' your items back to GitHub, without the public ssh key from your home directory on cl9 you will not be able to complete the task.

You will need to simply add the id_rsa.pub contents to your 'hello-world' GitHub repo to have access.

This is done with the following:

1. Got to 'Settings' for your account
2. Under 'Personal Settings' on the left choose 'SSH Keys'
3. Click 'Add SSH key'
4. Add your 'Title' - I used : FreeCodeCamp
5. Paste in the contents of the : id_rsa.pub file in your .ssh directory found on your cl9 account
6. Have fun with the rest of the module!!

Not noted in the following 'GitHubbin' page:

http://jlord.us/git-it/challenges/githubbin.html

**Comment by UziTech** [comment]
This should be added as a step for the waypoint.

**Comment by ltegman** [comment]
I think adding a step that links to [this Github resource](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/) (or writing a new wiki article and linking to that) should be sufficient, rather than describing all the steps on the page.
