### ISSUE TITLE
Waypoint: Store data in mongodb - Exercise Insert - will not verify

### ISSUE THREAD

**Issue by CharlesMilam** [FreeCodeCamp/FreeCodeCamp#3012]
Challenge http://freecodecamp.com/challenges/waypoint-store-data-in-mongodb has an issue. 

Similar to what I experienced with issue #2995 Attempted to verify my code, received fail messages. Unlike other learnyou-type exercises, all I received was an error message; comparison of data returned was not displayed. After several different attempts to format the data to pass tests, was unsuccessful. Went to the repo for the learnyoumongo. Same as in #2995, my solution was very similar to the repo's solution, and as in #2995 I pasted in their solution and it too failed to verify.

I am also not seeing any console.logs printing for this exercise.

Screenshot attached of results of running repo's solution.

![image](https://cloud.githubusercontent.com/assets/9435571/9650549/3dd7ab28-51ca-11e5-974e-fc1dd47ed7e9.png)

**Comment by leonfeng** [comment]
Just tried the uncommented code from your screenshot on Cloud9. Passed without issue.

Are you using the latest `node`? To be safe:
```sh
nvm install 0.12.7 && npm update -g learnyoumongo && npm update mongodb
```
And try again. Let me know how it goes.

**Comment by BerkeleyTrue** [comment]
@CharlesMilam Learnyoumongo is an open source project. If you are experiencing issues with Learnyoumongo they should be filed against that repo here https://github.com/evanlucas/learnyoumongo. Also, in the future please read https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-help-when-you-get-stuck

Happy Coding!

**Comment by jocarosa** [comment]
i have the same problem, please help here!

**Comment by crespoter** [comment]
I am having the same issue too . None of the console logs aren't being shown either .
