### ISSUE TITLE
Codepen isn't working

### ISSUE THREAD

**Issue by gregorysl** [FreeCodeCamp/FreeCodeCamp#3014]
Challenge http://www.freecodecamp.com/challenges/zipline-show-the-local-weather has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

1. Go to challenge: http://www.freecodecamp.com/challenges/zipline-show-the-local-weather
2. Click link to codepen from first checkmark (http://codepen.io/AdventureBear/full/yNBJRj) 
3. Codepen doesn't show any temerature
![image](https://cloud.githubusercontent.com/assets/3129241/9653694/a652fa08-5225-11e5-86a8-a8a384f4f471.png)

**Comment by Mansuro** [comment]
works fine for me

**Comment by gregorysl** [comment]
Yeah, you're right. It was because of uBlock.
