### ISSUE TITLE
Cannot submit the code

### ISSUE THREAD

**Issue by andrein05** [FreeCodeCamp/FreeCodeCamp#3018]
Challenge http://www.freecodecamp.com/challenges/waypoint-create-a-bootstrap-headline has an issue. 
![free code camp bug](https://cloud.githubusercontent.com/assets/13271347/9656990/a693944e-5245-11e5-8ec9-0b1374b4a1a5.PNG)

**Comment by bugron** [comment]
@andrein05 thanks for posting this issue!
I don't know what is your actual problem (please, provide the description of your issue next time) but I can't pass the last test with your code which I can't see in your screenshot. [Proof](http://prntscr.com/8c3t5c).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
