### ISSUE TITLE
I didnt understand why this exercise is there

### ISSUE THREAD

**Issue by Smallworldz** [FreeCodeCamp/FreeCodeCamp#3019]
Challenge http://freecodecamp.com/challenges/waypoint-fill-in-the-blank-with-placeholder-text has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by Mansuro** [comment]
What's your issue?

**Comment by Smallworldz** [comment]
i didnt understand that lorem ipsum part

**Comment by Mansuro** [comment]
It's just a placeholder text. You just use it as an example to fill the **p** tags

**Comment by Smallworldz** [comment]
kkkk.....thanks
it confusing me but thanks for help

**Comment by bugron** [comment]
@Smallworldz if your problem is solved feel free to close this issue, thanks!
