### ISSUE TITLE
target2 in the first verification point should be target4

### ISSUE THREAD

**Issue by zovsky** [FreeCodeCamp/FreeCodeCamp#3020]
![2015-09-03_15-58-05](https://cloud.githubusercontent.com/assets/7656886/9658818/ee0bd96c-5254-11e5-9d1a-702899e3e23a.png)
Challenge http://freecodecamp.com/challenges/waypoint-use-appendto-to-move-elements-with-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by bugron** [comment]
@zovsky thanks for posting this issue!
I couldn't find any problem in your screenshot. The only instruction in challenge description section says:
>Move your **target2** element from your left-well to your right-well.

Everything related to **target4** is just an example:
>**For example**, if we wanted to move **target4** from our right well to our left well, we would use `$("#target4").appendTo("#left-well");`

Next time, please, provide the description of your issue, thanks. 

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by zovsky** [comment]
Oh, I misread the verification point which says "Your target2 element should NOT be inside your left-well"
Sorry about that.
