### ISSUE TITLE
Site width is increases for no reason - Apis and Microservices Certification

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/freeCodeCamp#30216]
**Describe the bug**
In [Managing Packages with Npm](https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm), [Basic Node and Express](https://learn.freecodecamp.org/apis-and-microservices/basic-node-and-express) and [MongoDB and Mongoose](https://learn.freecodecamp.org/apis-and-microservices/mongodb-and-mongoose) challenges the site width is unnecessarily increased, also you can see a horizontal scroll bar which shouldnt be there.

**To Reproduce**
1. Go to challenges linked above
2. See error, also you can see horizontal scroll bar

**Expected behavior**
There shouldn't be a horizontal scroll bar and site width should be reduce

**Screenshots**
![screenshot 7](https://user-images.githubusercontent.com/36357875/47602098-c118c200-d9ea-11e8-9805-123b99026b1a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - Browser: Google Chrome
 - Version: 70.0.3538.77 (Official Build) (64-bit)

**Additional context**

**Comment by zybex86** [comment]
I can have a looksee :)

**Comment by thecodingaviator** [comment]
@zybex86 Did you get the PR in yet?

**Comment by zybex86** [comment]
Sorry  no. Didn't set up the site locally and later had no time to work on
it so go ahead and take care of it. I'll happily help when I get more free
time

**Comment by Nirajn2311** [comment]
@thecodingaviator you can take this up, and if you need any help just ask over here.

**Comment by zybex86** [comment]
Really won't have time for the next month

**Comment by thecodingaviator** [comment]
@Nirajn2311 I would gladly, can you guide me as to where this file can be found?
