### ISSUE TITLE
Bonfire: Where do I belong

### ISSUE THREAD

**Issue by asdal** [FreeCodeCamp/FreeCodeCamp#3022]
Challenge http://www.freecodecamp.com/challenges/bonfire-where-do-i-belong has an issue.

Way back I cleared the challenge and all tests passed. While revisiting/ code review test# 4,5,6 fail.

please check last three tests as values seem misplaced. This is the code which passed initially and seems right.

function where(arr, num) {
 arr.sort(sortNumber);
  var index;
  for(i=0; i<arr.length; i++)
  {
    if (num >= arr[i] && num <= arr[i+1])
    {
      if(arr[i] == num)
      { index = i; }
      else {
        index = i + 1;
      }
    }
  }      
  return index;
}
function sortNumber(a,b) {
 return a - b;
}

**Comment by dmytroyarmak** [comment]
@asdal Thank you for your report.

Tests cases are right. The problem that your function return `undefined` when `num` is bigger or smaller than all elements in `arr`.

**Comment by asdal** [comment]
Thanks a  lot @dmytroyarmak. I have fixed my code. 

But still wondering why did the tests pass previously ? 
Only thing I can think of is if test cases been revised//updated ?

Does FreeCodeCamp revise / improve its previous challenges / tests requirement ?

**Comment by bugron** [comment]
@asdal if your problem is solved feel free to close this issue, thanks!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
