### ISSUE TITLE
Ctrl+Enter keyboard shortcut doesn't let you move to next challenge

### ISSUE THREAD

**Issue by stx146** [FreeCodeCamp/FreeCodeCamp#3023]
About 3 weeks ago, the UI for Free Code Camp Waypoints allowed the user to press Ctrl+Enter to check the current waypoint, and move on to the next waypoint. Now, Ctrl+Enter only executes and checks code, you still have to use your mouse to move onto the next challenge. Allowing Ctrl+Enter to move to the next challenge greatly improves efficiency for the user.

**Comment by stx146** [comment]
*EDIT: using Chrome 45.0.2454.85

**Comment by bugron** [comment]
@stx146 thanks for posting this issue!
I'm closing this issue as a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2772

For more info [see here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2836#issuecomment-136091457).
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
