### ISSUE TITLE
Typo '/' in example code.

### ISSUE THREAD

**Issue by jwjb** [FreeCodeCamp/FreeCodeCamp#3024]
Challenge http://freecodecamp.com/challenges/waypoint-add-alt-text-to-an-image-for-accessibility has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![screen shot 2015-09-03 at 8 19 55 am](https://cloud.githubusercontent.com/assets/3523591/9662723/a3bd8ebc-5215-11e5-84d8-6a9f8b4719ee.png)

**Comment by bugron** [comment]
@jwjb thanks for posting this issue!
Actually I don't think that this is a typo. But in HTML5 there's no need or it's not required to terminate self-closing tags (in this case `img` tag) by slash, so you can create a PR to remove this slash.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by natac13** [comment]
I can get submit one

**Comment by bugron** [comment]
@natac13 then I'll merge your PR, Remember to push your PR to **staging** not to **master**, thanks.

**Comment by jwjb** [comment]
@bugron @natac13 very cool and thanks for the additional explanation and such.
