### ISSUE TITLE
Submit Button

### ISSUE THREAD

**Issue by Cenl** [FreeCodeCamp/FreeCodeCamp#3026]
Challenge http://freecodecamp.com/challenges/waypoint-inherit-styles-from-the-body-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

It seems as I go from lesson to lesson the submit button doesn't want to move me to the next lesson it just closes.

**Comment by mcunha** [comment]
This happens on other challenges [all the HTML starter ones too]. Tested with Chrome. If you wait for animations to complete, it seems to work however.

On FireFox unable to repro.

**Comment by benschenker** [comment]
Hey @Cenl thanks for posting this issue!

I'm also having issues reproducing this (Chrome).  Please reopen this issue if this is not resolved for you.
