### ISSUE TITLE
Sass - Apply a Style Until a Condition is Met with @while correct code can not pass!

### ISSUE THREAD

**Issue by lwy1010** [freeCodeCamp/freeCodeCamp#30289]
**Describe your problem and how to reproduce it:**

Here is my code in Sass - Apply a Style Until a Condition is Met with @while section. It can not pass by using chrome 70 version in win10. However It can be pass by using firefox in win10.
```
<style type='text/sass'>
  $x: 1;
  @while $x < 11{
    .text-#{$x} {font-size: 5px * $x;}
    $x: $x + 1;
  }
</style>
...
```

**Add a Link to the page with the problem:**
[Apply a Style Until a Condition is Met with @while](https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while/)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![](https://github.com/lwy1010/blog/blob/master/md_img/fcc-sass-bug.PNG?raw=true)

**Comment by wadleo** [comment]
Yes I had this issue too

**Comment by mqdev** [comment]
![captura de tela 2018-11-06 as 00 50 19](https://user-images.githubusercontent.com/8003445/48039911-01e8a780-e15e-11e8-9c96-8aca9efab065.png)
Here is working well.

Can you attach a copy of the page's source, so we can have a look on what the ide produced?

**Comment by thecodingaviator** [comment]
What's happening is @lwy1010 is entering an infinite loop. Adding ?run=disabled to the end of the link would solve this

**Comment by lwy1010** [comment]
@mqdev Maybe it is working on Safari. Because it is working on Firefox on win10, too. It just not working on Chrome on win10.

page's source? It's this one?: [page-source](https://github.com/lwy1010/blog/blob/master/md_img/page-source.html)

**Comment by mqdev** [comment]
I mean the source generated by the browser after the sass code das typed.

**Comment by thecodingaviator** [comment]
@lwy1010 Yes, it is a problem that exists only in Chrome, we have faced this issue multiple times and are working on it

**Comment by ValeraS** [comment]
duplicate #17195
