### ISSUE TITLE
"A man, a plan, a canal. Panama" is palindrome, bonfire expects false

### ISSUE THREAD

**Issue by hselbie** [FreeCodeCamp/FreeCodeCamp#3028]
Challenge http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Using this code
function palindrome(str) {
str = str.toLowerCase();
str = str.replace(/\s/g, '');
str = str.replace(/[.,'-\/#!$%\^&*;:{}=-_`~()]/g,"");
var strRev = str.split('').reverse().join('');
return str === strRev;
}
 

palindrome("A man, a plan, a canal. Panama");

**Comment by natac13** [comment]
@hselbie It maybe a good idea to look over your regex again using this site [REGEX](http://regexr.com/) 
I placed in your regex and I do not think it is doing what you think it is....

**Comment by abhisekp** [comment]
@hselbie Please read contribution guidelines before postins issues. Always ask others in chat room for if this is an actual issue.

**Comment by bugron** [comment]
@hselbie thanks for posting this issue!
Please, check the regexp you're using for this challenge. You can find explanation of this bonfire in our [Wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki).
Closing this issue. Feel free to reopen if you still experience problems.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
