### ISSUE TITLE
Code junk in instructions

### ISSUE THREAD

**Issue by georgiel** [FreeCodeCamp/FreeCodeCamp#3029]
Challenge http://freecodecamp.com/challenges/waypoint-comment-your-javascript-code has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

If you look in the code validations, I don't believe that the statement 

"assert(editor.getValue().match(/(\/\/)...../g), 'Create a // style comment that contains at least five letters');" 

should be a visible element to users, it isn't meant to be there.
![image](https://cloud.githubusercontent.com/assets/5931143/9666005/7cf96606-526b-11e5-8132-f48541c57711.png)

**Comment by bugron** [comment]
@georgiel please, provide the description of your issue, thanks!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by georgiel** [comment]
sorry, yeah specifically obvious, if you look in the code validations, I don't believe that the statement "assert(editor.getValue().match(/(\/\/)...../g), 'Create a // style comment that contains at least five letters');" should be a visible element to users, it isn't meant to be there.

**Comment by bugron** [comment]
@georgiel thanks for posting this issue!
Closing this issue as a duplicate.
For more info [see here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2818).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
