### ISSUE TITLE
Challenges require click "Run Code" twice to move to next challenge

### ISSUE THREAD

**Issue by mcunha** [FreeCodeCamp/FreeCodeCamp#3030]
Expected behavior: Clicking "Run Code" after completing all goals on first attempt should immediately offer submit result popup. 

Behavior seen: On submitting correct solution, goals turn green but popup doesn't come up. Clicking a second time changes nothing in the UI but then shows the popup.

Affected sample URL's:
http://freecodecamp.com/challenges/waypoint-say-hello-to-html-elements
http://freecodecamp.com/challenges/waypoint-headline-with-the-h2-element
http://freecodecamp.com/challenges/waypoint-inform-with-the-paragraph-element

Repro steps:
- Start challenge, complete it
- Use mouse to click "Run Code"
- Notice all goals are green and no popup
- Click "Run Code" again, popup comes up

Browsers tested:
Chrome 45.0.2454.78 beta (64-bit)
Firefox 40.0.2

**Comment by bugron** [comment]
@mcunha thanks for posting this issue!
I'm closing this issue as a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2772

For more info [see here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2836#issuecomment-136091457).
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
