### ISSUE TITLE
The following example code in the waypoint is incorrect.

### ISSUE THREAD

**Issue by racpa** [FreeCodeCamp/FreeCodeCamp#3031]
Challenge http://freecodecamp.com/challenges/waypoint-filter-arrays-with-filter has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

filter is a useful method that can filter out values that don't match a certain criteria
Let's remove all the values greater than five

array = array.filter(function(val) {

  return val<4;

});

I was trying to find the way to edit it in github, but it's an endless pit of content to me.

Code should be:
array=array.filter(function(val){
return val <=5;
//or return val < 6;
});

**Comment by bugron** [comment]
@racpa thanks for pointing this out!
@natac13 do you want to fix this?

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by natac13** [comment]
@bugron You bet!

**Comment by bugron** [comment]
@natac13 sure, I'll QA and merge.

**Comment by natac13** [comment]
@bugron Could I maybe add more to the description.. was thinking to add after criteria

> ; filter does this by creating a new array of the items that pass the conditional statement, which gets returned

Just a thought to add more of a description

**Comment by bugron** [comment]
@natac13 I think that would be an improvement of the description but I don't know if we should do that. Maybe @benmcmahon100 can help us?
