### ISSUE TITLE
Waypoint: Store data in mongodb - Exercise Aggregate - no data in collection

### ISSUE THREAD

**Issue by CharlesMilam** [FreeCodeCamp/FreeCodeCamp#3032]
Challenge http://freecodecamp.com/challenges/waypoint-store-data-in-mongodb has an issue. 

There appears to be no data in the prices collection of the learnyoumongo db. My solution returns nothing, and querying from the mongo shell shows no documents in the collection.

Have restarted mongod with no change.

![image](https://cloud.githubusercontent.com/assets/9435571/9665891/c057cfec-5238-11e5-9a97-11d5512ff755.png)

**Comment by ahstro** [comment]
`learnyoumongo` is not something freeCodeCamp created, so you might want to take it up with its developers. I personally haven't done this challenge yet, but ask around the chat to see if anyone else experiences the same problem.

**Comment by benschenker** [comment]
Closing as external to FCC.  Feel free to reopen if you are unable to resolve this with learnyoumongo.
