### ISSUE TITLE
express works doesnt install

### ISSUE THREAD

**Issue by kryuchkova** [FreeCodeCamp/FreeCodeCamp#3034]
Challenge http://freecodecamp.com/challenges/waypoint-build-web-apps-with-expressjs has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The expressworks/ module doesn't install, it throws an error that reads:

operation not permitted, fcc_express.sh

**Comment by ahstro** [comment]
Strange, I don't think there's a file called `fcc_express.sh` involved at any point, just a `setup.sh` inside a folder called `fcc_express`.
Try creating a new c9 workspace and run the commands one at a time to see where the error occurs.
The commands are:
* `git clone http://github.com/reddock/fcc_express`
* `chmod 744 fcc_express/setup.sh`
* `fcc_express/setup.sh`
* `source ~/.profile`

**Comment by benschenker** [comment]
Hey @kryuchkova any updates?  Did @ahstro's comments resolve this for you?
