### ISSUE TITLE
Run code button issue

### ISSUE THREAD

**Issue by alirajt** [FreeCodeCamp/FreeCodeCamp#3035]
Challenge http://freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Several fast clicks on "Run code" button enables you to pass in the next exercise even thought the solution submit-ed is not the right one.

**Comment by Gelio** [comment]
Do you mean the next or this exercise? The *nest an anchor element within a paragraph*? In the link you provided I tried my best clicking the button as fast as I could and it still said it's an invalid solution, so please give more information and possibly include the source code you have that got the job done when it shouldn't.

**Comment by alirajt** [comment]
In order to reproduce it: go to the link I provided, reset the code by pressing the reset button, click the run code button once, it should say that the solution is invalid, after that make three fast clicks (or hold pressed Ctrl and press enter three times fast). 

Here's the code:

```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<a href="http://www.freecatphotoapp.com">cat photos</a>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```

**Comment by Gelio** [comment]
Sorry for the long wait and lack of activity on my part.

I've tested it, done as you told me, with the reset and fast clicks and I still get an incompletion message like I should. Then I copied your code and tried that - still an error. I don't seem to be able to reproduce the bug. Try it again on your machine, maybe it was a one-time thing (which, don't get me wrong, is still a bug of course).

**Comment by benschenker** [comment]
Hey @alirajt, any updates on this?

**Comment by alirajt** [comment]
I finally managed to do some more tests. On my computer which runs linux mint 17, i can always reproduce the bug, tested with two different accounts, the result is the same. On a windows powered computer instead I was unable to reproduce the bug. Seems like this is a chrome + linux mint issue

**Comment by BerkeleyTrue** [comment]
@alirajt Interesting... Would love to see some debugging. You down for some source diving? The issue is most likely located in the commonFramework file. 

Chrome is pretty good about being the same across platforms, but v8 (Chrome and Nodes JavaScript engine) is built in C++ so they need to be compiled on each system.

**Comment by bugron** [comment]
This issue if fixed and, hopefully, will be live soon.
