### ISSUE TITLE
none of the jQuery lessons will work, i run the script and nothing happens. 

### ISSUE THREAD

**Issue by TrinityKazahana** [FreeCodeCamp/FreeCodeCamp#3039]
![bug](https://cloud.githubusercontent.com/assets/14056720/9671975/b8fd1ec4-524b-11e5-818f-84ca29ba3af7.png)
Challenge http://freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by bugron** [comment]
@TrinityKazahana thanks for posting this issue!
 We officially support only [Chrome browser](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2942#issuecomment-136591448).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
