### ISSUE TITLE
Waypoint: Give a Background Color to a Div Element

### ISSUE THREAD

**Issue by CaBra503** [FreeCodeCamp/FreeCodeCamp#3044]
Hello, I cant go further in this waypoint challenge, I remember someones other thread was just closed not too long ago and it is giving a background color to a div, Clearly in the screenshot i have the correct code, and the background-color is red. so. idk.
![image](https://cloud.githubusercontent.com/assets/12191827/9676886/0a521f14-5287-11e5-9249-ec39f540a7fa.png)
v element.

**Comment by ahstro** [comment]
I'm sorry, but you just have the incorrect code I'm afraid. Please close this and try again. If you're stuck, check out either [this](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-help-when-you-get-stuck) or [this](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) wiki page, or both. Good luck :)

**Comment by CaBra503** [comment]
omg so true ugh how embarassing.. lol. im so sorry guys. wont happen again
