### ISSUE TITLE
Tests for Project Euler: Problem 10: Summation of primes needs to be updated

### ISSUE THREAD

**Issue by ezioda004** [freeCodeCamp/freeCodeCamp#30462]
**Describe your problem and how to reproduce it:**

The last test for this challenge needs additional time.
I'm using optimized version of Sieve of Eratosthenes algorithm but the last case still times out:
Here's the [repl](https://repl.it/@ezioda004/Project-Euler-Problem-10-Summation-of-primes) link to the code.

The solution provided in the challenge's [seed](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-coding-interview-prep/project-euler/problem-10-summation-of-primes.english.md) doesnt even pass the third test.

I believe the tests are set to timeout after 100ms, if it could be increased to 200ms or 300ms, it should be doable.

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/coding-interview-prep/project-euler/problem-10-summation-of-primes

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 70
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ValeraS** [comment]
It is caused by babel transform with loop-protect, which is set to 100 ms.

Test timeout is set to 5 sec.

@ezioda004 Will you make a PR to replace a solution in the curriculum? It'll decrease the time of testing in Travis/CI. And in your solution `if` at line 12  is not needed.

**Comment by ezioda004** [comment]
@ValeraS Thanks for replying. I'll make a PR updating the solution in curriculum and you're right line 12 is not required, I was trying to optimize the solution more by making the loop skip if that value is already `0` but theres no point since accessing and assigning a value to an array is of `O(1)` anyway.

I understand that it'll decrease the CI testing time.
 
But updating the solution in curriculum would also update the test timeout for this challenge? Or something else would also need to be updated? Sorry, just trying to understand.

**Comment by ValeraS** [comment]
Update solution does not solve the problem with the test timeout.

In addition, we have non-optimal solutions for problems 35 and 47.

**Comment by ezioda004** [comment]
Update solution does not solve the problem with the test timeout.

@ValeraS Thats what I assumed too. How'd the timeout problem be solved?

>In addition, we have non-optimal solutions for problems 35 and 47.

I'll update the PR with optimal solution of those.

**Comment by ValeraS** [comment]
need to increase this timeout:
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/templates/Challenges/rechallenge/transformers.js#L20

**Comment by ezioda004** [comment]
I reckon changing that would increase for all challenges? If so, is there a way to only increase for this challenge or others (presuming we find more challenges that require it)?

**Comment by ezioda004** [comment]
@ValeraS Problem 35 have 3 wrong assertion tests. I've created a new solution for Problem 35 (current one is wrong) and optimized 47 solution to be 4x times faster. However we'd still need to add additional time. Since the inputs are quite big in both tests.

```
circularPrimes(100000) 
circularPrimes(250000) 
circularPrimes(500000)
circularPrimes(750000)
circularPrimes(1000000)
```

Shall I update the PR to add correct test and solution for 35 and optimized solution for 47?

**Comment by ValeraS** [comment]
Let's do it in separate PRs
