### ISSUE TITLE
typeof is an operator and should be described as such

### ISSUE THREAD

**Issue by prashcr** [FreeCodeCamp/FreeCodeCamp#3047]
In this waypoint: http://www.freecodecamp.com/challenges/waypoint-using-typeof  
  
#3016

**Comment by ahstro** [comment]
In the future, please comment in the relevant issue instead of creating a new one :)

**Comment by prashcr** [comment]
Oh...I thought PRs and issues were two different things. I was just looking at the Contributing section of the readme, and it mentioned making an issue then a PR. And I see people linking issues in PRs and vice versa...so I'm slightly confused.

**Comment by ahstro** [comment]
Essentially, no, they're really quite similar. I didn't notice that yours was a PR though so I created my own, sorry about that.

**Comment by ahstro** [comment]
This should've been closed by #3071

**Comment by bugron** [comment]
@ahstro thanks. Closing this issue as PR #3071 is merged.
