### ISSUE TITLE
Suggestion: Challenge - ES6: Use * to Import Everything from a File - ideas for improving the challenge

### ISSUE THREAD

**Issue by alanpaulprice** [freeCodeCamp/freeCodeCamp#30498]
[ES6: Use * to Import Everything from a File](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use--to-import-everything-from-a-file)

**Issue**
I believe it would be an improvement to this challenge if the user were tasked to do something with the imported object, using the dot notation mentioned in the description.
The challenge isn't showcasing any real use of import 'everything', when the import is only one function.

**Suggestion**
The import file would contain a set of string methods, one of them being `capitalizeString`. 
The user would be tasked with importing everything and using one of the imported functions.
The string and function call would be included in the challenge seed:
```
"use strict";
stringMethods.capitalizeString("hello");
```

I would be interested in working on this.

**Comment by RandellDawson** [comment]
Take the first pass at it.  Once the challenge and instructions are finalized, I will revise my PR for the testString.

**Comment by alanpaulprice** [comment]
Will do!

**Comment by alanpaulprice** [comment]
@RandellDawson I've hit a roadblock with allowing a dynamic object name in the test. I was wondering if you could help me figure it out.

The seed will be:

```
"use strict";
stringFunctions.capitalizeString("howdy!");
```

The straightforward solution will be:

```
"use strict";
import * as stringFunctions from "stringFunctions";
stringFunctions.capitalizeString("howdy!");
```

However, I'd like to make it so that the user can select a different object name and still have it work. For example, this solution would be accepted:

```
"use strict";
import * as aDifferentObjectName from "stringFunctions";
aDifferentObjectName .capitalizeString("howdy!");
```

Is this possible?

**Comment by ezioda004** [comment]
@alanpaulprice That should be possible with regex albeit a complicated one.
This arises a new problem - currently we're checking for the whole solution as a string and matching a certain pattern.

One way I can think of is by asking the user to assign that object to our provided variable.
Such as:

```
const ourStringObject = whateverImportedObjectName;
```
And then we can check if `ourStringObject` is passing all the tests correctly.

**Comment by alanpaulprice** [comment]
@ezioda004 

>That should be possible with regex albeit a complicated one.

Maybe we could use a capture group to compare the name of the object used to store the imported data vs the object that is having the `.capitalizeString` method called on it? I think I could write the test for that.

>One way I can think of is by asking the user to assign that object to our provided variable.

Would the code solution to this approach be something like this?

```
"use strict";
import * as stringFunctions from "string_functions";
const ourStringObject = stringFunctions;
```

It'd work, but I think it'd be useful to have dot notation used to access a method on the imported object, just to make things explicit. Maybe they could import everything, then store a single method from that imported object in our given variable?

```
"use strict";
import * as stringFunctions from "string_functions";
const capitalizeString = stringFunctions.capitalizeString;
```

I guess the test for this approach would be to pass a string into the `ourStringObject`/`capitalizeString` function and see if it returned a capitalized string?

The only issue I can see with this approach is that this solution would pass:

```
"use strict";
const capitalizeString = str => str.toUpperCase();
```

I'm not sure if this is worth taking into account, or I'm just being picky. Either approach will work though! I'm happy to go with whichever you think is best.

**Comment by ezioda004** [comment]
@alanpaulprice 
>Maybe we could use a capture group to compare the name of the object used to store the imported data vs the object that is having the .capitalizeString method called on it? I think I could write the test for that.

Not sure if I fully understand that but the object that have `capitalizeString` method could very well be of different name, so how'd you compare that? With `import * as <arbitary name>`, the object name can be anything.

>The only issue I can see with this approach is that this solution would pass:

Ok - then we should definitely have 2 tests. One which checks if the correct import syntax is used (similar to what we already have currently) and another test if `const capitalizeString = stringFunctions.capitalizeString();` matches our expectations.

I think both of these tests are robust and should prevent hacky solutions.

**Comment by RandellDawson** [comment]
Sounds like you have everything figured out?  Let me know, so I can update the other PR with changes for the import * challenge.

**Comment by alanpaulprice** [comment]
@ezioda004 

> Not sure if I fully understand that but the object that have capitalizeString method could very well be of different name, so how'd you compare that? With import * as <arbitary name>, the object name can be anything.

The plan is to create a capture group from `<arbitrary name>`, then use that reference to compare the import to the call to the statement that follows. Sorry if I'm not explaining this well, it's a tricky one to put into words! I have it working in the regex below:

`import\s+\*\s+as\s+([a-zA-Z0-9_$]+)\s+from\s*('|")\s*string_functions\s*\2\s*;?\s*(?:const|let|var)\s+capitalizeString\s*=\s*\1\.capitalizeString\(('|")[a-zA-Z0-9_$]+\3\)\s*;?`

This works for the following solution:

```
"use strict";
import * as stringFunctions from "string_functions";
const capitalizeString = stringFunctions.capitalizeString("string");
```

A detail I'm currently stuck on is making sure their is either a semi colon (with optional whitespace), or a new line character seperating the import statement from the `const capitalizeString =` line.

```
// should pass
"use strict";
import * as stringFunctions from "string_functions";
const capitalizeString = stringFunctions.capitalizeString("string");

// should pass
"use strict";
import * as stringFunctions from "string_functions";const capitalizeString = stringFunctions.capitalizeString("string");

// shouldn't pass
"use strict";
import * as stringFunctions from "string_functions" const capitalizeString = stringFunctions.capitalizeString("string");
```

I'm working on this now,

>another test if const capitalizeString = stringFunctions.capitalizeString(); matches our expectations.

Once the regex is sorted, we can tackle this 2nd test!

**Comment by Nirajn2311** [comment]
@alanpaulprice Thats way too much regex, isn't there a simpler method.

**Comment by alanpaulprice** [comment]
@Nirajn2311 It is a lot indeed!

We could just go with the idea propsed by @ezioda004. We could make it more robust by having the `value` that has to be stored in the variable be something random, not a capitalize string function:

* Have a random `value` stored on a provided object.
* Have the user import that object, then store the `value` in a given variable, accessing it via dot notation.
* Test if the variable's value matches the one provided by the object.

Having it be random would make it impossible for someone to provide a cheap solution, like the example I provided at the bottom of [this comment](https://github.com/freeCodeCamp/freeCodeCamp/issues/30498#issuecomment-436711166).

**Comment by moT01** [comment]
Closing as stale.
