### ISSUE TITLE
Challenge Issue: CSS Grid: Limit Item Size Using the minmax Function

### ISSUE THREAD

**Issue by jstodd42** [freeCodeCamp/freeCodeCamp#30517]
**Describe your problem and how to reproduce it:**
My issue was found on the CSS Grid: Limit Item Size Using the minmax Function. When I submit the answer on the "grid-template-columns:" my results are different from the youtube tutorial I used. Admittedly, I did have to search for help after I wasn't able to understand the orginal challenge in the first place. Still don't, to be honest. I have attached my results with the correct answer and the youtube link of the video that also has the same "correct answer" with a different end result.

Can anyone help on this one? I just want other FCC campers to understand, as well as add to this great open source project.

Thanks!

**Add a Link to the page with the problem:**
My results: [https://learn.freecodecamp.org/responsive-web-design/css-grid/limit-item-size-using-the-minmax-function](url)

YouTube Link to the same question and answer: [https://youtu.be/zIEwl1ZQdQI](url)

**Tell us about your browser and operating system:**
* Browser Name:  Google Chrome
* Browser Version: Version 70.0.3538.67 (Official Build) (64-bit)
* Operating System: Windows 10/ Same on Mac iOS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Again, this is my screen shot of the same problem, done several weeks later, with the same results and a different outcome for the same answer.

[![0](https://user-images.githubusercontent.com/43625763/47607421-66c93280-d9e5-11e8-8e1c-0a0cc4239826.png)](url)

**Comment by vanditbhatt** [comment]
@jstodd42 From the above screenshot the issue looks to be extra spaces between functions and its declarations.

Just change `repeat (3, minmax (90px, 1fr));` to 
```css
grid-template-columns: repeat(3,minmax(90px,1fr);
```
and try to run the tests again.
![47607421-66c93280-d9e5-11e8-8e1c-0a0cc4239826](https://user-images.githubusercontent.com/24377767/47679571-91d0a380-dbea-11e8-9509-e6c5c57a5f90.png)

**Comment by vanditbhatt** [comment]
@jstodd42 You're very welcome. I made the same mistake and went through the same figuring it out.

Keep learning and happy coding.

**Comment by Nirajn2311** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that this issue seems to be a request for help. Instead of asking for help here, please click the **“Help”** button on the challenge on freeCodeCamp, which will help you create a question in the right part of the forum. Volunteers on the forum usually respond to questions within a few hours.

If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you and happy coding
