### ISSUE TITLE
Problems with Pull Request

### ISSUE THREAD

**Issue by jovsantos** [freeCodeCamp/freeCodeCamp#30537]
Hi everyone, I need help, I changed the "while" tab in the csharp folder and I did not see in the guide that I would have to create a branch to send the changes in a pull request, the photo is below, how can I cancel these changes and create a branch? I apologize for my mistake.

**Comment by huyenltnguyen** [comment]
Hi @jovsantos, the issue tracker is for bug reporting. Please use the Gitter [Contributors Chatroom](https://gitter.im/FreeCodeCamp/Contributors) instead.
