### ISSUE TITLE
Zipline: Stylize Stories on Camper News -- Refers to depreciated features

### ISSUE THREAD

**Issue by ArielLeslie** [FreeCodeCamp/FreeCodeCamp#3053]
Challenge http://freecodecamp.com/challenges/zipline-stylize-stories-on-camper-news has an issue. 

>User Story: As a user, I can click a link to go directly to the post's discussion page.

News posts no longer have a discussion page.

**Comment by ahstro** [comment]
You might need to do a [hard refresh](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache), because this was fixed 4 days ago in 9abac81db5a01be223088bca197065143f5f6daf ;)
Thank you for reporting though! Remember to close this issue.

**Comment by bugron** [comment]
Closing this issue as it is solved in 9abac81. @ahstro thanks.
