### ISSUE TITLE
Found a bug

### ISSUE THREAD

**Issue by wounttellyou** [FreeCodeCamp/FreeCodeCamp#3059]
Challenge http://freecodecamp.com/challenges/waypoint-size-your-images has an issue.
Even when i enter the correct code, the challenge doesn't finish and the image doesn't change the size.
![screen](https://cloud.githubusercontent.com/assets/14130747/9692110/8889519a-534f-11e5-9511-646206320579.png)

**Comment by bugron** [comment]
@wounttellyou thanks for posting this issue!
You can't pass the test because
>Your img element **should have** the **class smaller-image**.

So your `img` element should look like this `<img class="smaller-image" src="https://bit.ly/fcc-relaxing-cat">`.
If your problem is now solved feel free to close this issue, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by wounttellyou** [comment]
thank you
