### ISSUE TITLE
Can't run code

### ISSUE THREAD

**Issue by cherriblssm** [FreeCodeCamp/FreeCodeCamp#3060]
Challenge http://freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
Everytime I try to run the code the page just sits there. I've tried multiple browsers and the issue continues. All the info with the red X's and green checks disappears when I have the code entered correctly. But when the code is wrong the info comes back. Everything is green except for Create a script element.

**Comment by bugron** [comment]
@cherriblssm thanks for posting this issue!
Please, provide the description of your issue/code/screenshot, thanks!.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by cherriblssm** [comment]
@bugron Description is updated. Sorry about that I hit the wrong key and had to go back in and add it.

**Comment by bugron** [comment]
@cherriblssm actually I'm able to [pass the tests](http://prntscr.com/8cm8ip).

**Comment by cherriblssm** [comment]
This is what it does every time I try. 

![capture1](https://cloud.githubusercontent.com/assets/14058415/9692518/cc6f79e6-5306-11e5-83aa-a562dea5f148.PNG)

**Comment by cherriblssm** [comment]
Am I doing something wrong that I'm just not seeing?

**Comment by bugron** [comment]
@cherriblssm what browser are you using?

**Comment by cherriblssm** [comment]
@bugron Internet Explore and Microsoft Edge

**Comment by bugron** [comment]
@cherriblssm [we officially support only Chrome browser](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2942#issuecomment-136591448) but FF should work fine in most cases. IE/Edge is **not** supported.

**Comment by cherriblssm** [comment]
@bugron I will go download Chrome. Thank you for your help.

**Comment by bugron** [comment]
@cherriblssm you're welcome but please, try in Chrome or FF now to ensure that everything is OK in that browsers, thanks.

**Comment by cherriblssm** [comment]
@bugron Just tried in Chrome and it's working beautifully. Thanks again.
