### ISSUE TITLE
Error Program Execution Failure No user tests were run.

### ISSUE THREAD

**Issue by tiagomf1** [FreeCodeCamp/FreeCodeCamp#3061]
Challenge http://freecodecamp.com/challenges/waypoint-iterate-with-javascript-for-loops has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by bugron** [comment]
@tiagomf1 thanks for posting this issue!
Please, provide the description of your issue/code/screenshot, thanks!.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by tiagomf1** [comment]
I open again and run normaly... thanks :)

**Comment by bugron** [comment]
OK, closing this issue, feel free to reopen it if you still have a problem.
