### ISSUE TITLE
Missing '70. Waypoint: Use RGB to Color Elements Gray'.

### ISSUE THREAD

**Issue by jwjb** [FreeCodeCamp/FreeCodeCamp#3062]
Challenge http://freecodecamp.com/challenges/waypoint-use-rgb-to-color-elements-gray has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![screen shot 2015-09-04 at 11 55 41 am](https://cloud.githubusercontent.com/assets/3523591/9692548/88afa21a-52fe-11e5-8bd6-4b9af7a0ff91.png)
![screen shot 2015-09-04 at 11 56 58 am](https://cloud.githubusercontent.com/assets/3523591/9692547/88ae9c58-52fe-11e5-82da-50c6db4a80bb.png)
![screen shot 2015-09-04 at 11 57 30 am](https://cloud.githubusercontent.com/assets/3523591/9692549/88b26e0a-52fe-11e5-857f-9538d5c738ed.png)

**Comment by bugron** [comment]
@jwjb thanks for posting this issue!
You'll be surprised but there isn't actually 70th waypoint. The points in the last screenshot are called [Brownie Points](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Brownie-Points).
If your problem is solved now feel free to close this issue, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by jwjb** [comment]
@bugron awesome and thanks for clearing that up and this issue is now closed.
