### ISSUE TITLE
Issue with "Bonfire: Make a Person"

### ISSUE THREAD

**Issue by thefuzzy0ne** [FreeCodeCamp/FreeCodeCamp#3063]
Challenge http://freecodecamp.com/challenges/bonfire-make-a-person has an issue.

The full name is passed through the constructor as "Bob Ross"

One of the tests is:

````expect(bob.getFullName()).to.eql('Bob Ross');````

which I pass. But at the end is another test:

````expect(bob.getFullName()).to.eql('George Carlin');````

Is that really the intention? Given the constructor, I can't see why the output from ````bob.getFullName()```` should ever be 'George Carlin'.

**Comment by catapixel** [comment]
@thefuzzyOne The purpose of the test is to test your setter's ability to rename your person. I know it looks strange but effectively the test tries to reset the person's name to George Carlin and then tests to see if it happened successfully. Hope that helps.

**Comment by thefuzzy0ne** [comment]
You're absolutely right. Sorry for being such a muppet. I'd best go back and "unslime" it. :)
