### ISSUE TITLE
Bug: Error with email login when hitting return key

### ISSUE THREAD

**Issue by quatridunull** [FreeCodeCamp/FreeCodeCamp#3064]
If you try to sign in using a regular email address, type the email address, tab to the password, and press return while the cursor is still in the password field, the site will say the username or password was invalid.

It only works correctly if you manually move the mouse and click the login button with the mouse. (To make sure I wasn't just typing my password wrong, I tried this several times and got the same error with the return key.)

**Comment by bugron** [comment]
@quatridunull thanks for posting this issue!
I don't have such a problem with logging in so I'm closing this issue. Please, discuss problems like this in our [Gitter channel](https://gitter.im/FreeCodeCamp/FreeCodeCamp), thanks.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
