### ISSUE TITLE
Make all challenges test cases accept either single or double quote input for jQuery

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3069]

**Comment by QuincyLarson** [comment]
This will involve improving any regex tests we're using.

**Comment by natac13** [comment]
I believe I can tackle this.

**Comment by natac13** [comment]
maybe... lol

**Comment by ahstro** [comment]
Let me know how it goes @natac13. I'm willing to try if you decide not to :)

**Comment by natac13** [comment]
@ahstro Please do not let me get in your way! I do not think I will be able to get it

**Comment by ahstro** [comment]
You're not getting in my way at all :) More people hacking on issues is great, but I'll look at it since you said so.

**Comment by ahstro** [comment]
What did I get myself into...?

**Comment by bugron** [comment]
I think one should do that like in @benmcmahon100's https://github.com/FreeCodeCamp/FreeCodeCamp/commit/4de75fc9e71d4e86f0d071d85f8ee5fa839bf66d commit.

**Comment by natac13** [comment]
@bugron yep ill give that I try! Thanks

**Comment by natac13** [comment]
I am going to be starting at the bottom of the basic-javscript.json file

**Comment by bugron** [comment]
@natac13 please, don't start from basic-javscript.json because https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3083 and https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3084 and https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3086. You'll broke my PRs.

**Comment by natac13** [comment]
@bugron ok no problem, do you have a suggested spot for me to begin?

**Comment by bugron** [comment]
@natac13 I have 5-6 PRs now for basic-javscript.json, any change will cause merge conflicts, thanks for understanding. You can start from **jquery.json**. There are a lot of single and double quotes used in these challenges.

**Comment by natac13** [comment]
@bugron yeah the one I was going to fix was the tests that just got added to [Give your JavaScript Slot Machine some stylish images
](http://www.freecodecamp.com/challenges/waypoint-give-your-javascript-slot-machine-some-stylish-images). Reason was I just submitted them in a recent PR and they will only work with single quotes... they are in your #3086... I will work on the jquey part... however I have to ask I only need to fix the `editor.match()` ones right? Since the asserts running jquery already pass with either signle or double quotes?

**Comment by bugron** [comment]
@natac13 I apologize for the inconvenience. I think yes, you only need to change `editor.match()`'es. That fix looks like this for example: `editor.match(/search code with double quotes/gi) || editor.match(/search code with single quotes/gi)`,

**Comment by natac13** [comment]
@bugron no need for the apology! I will simple help somewhere else.. It seems like this will be an easy file to fix up!

**Comment by natac13** [comment]
Most of the challenges in the jQuery section are 'quote neutral' @QuincyLarson would you like tests added that directly check for this?

**Comment by bugron** [comment]
@natac13 My PRs already have conflicts so you can start working on the **basic-javscript.json**. I'll resolve them after your PR will be merged!

**Comment by natac13** [comment]
@bugron Sounds like a plan Ill start working on that one today!

**Comment by bugron** [comment]
@natac13 OK, then I'm waiting for your PR. And as always, I'll QA.

**Comment by natac13** [comment]
@bugron Sweet! and it shows that we do **not** have to escape the single quotes!!! Ill test to confirm but from looking at that code you directed me to it looks that way... also I think I remember reading somewhere that non-capture groups are faster than capture groups... If it is the same to you I would like to use `(?:'|\"   )` instead of `('|\")`

**Comment by bugron** [comment]
@natac13 I think `('|\")` is fine. Would you mind to try both? It's interesting which one will work.

**Comment by natac13** [comment]
@bugron yeah they both work as expected.

**Comment by bugron** [comment]
@natac13 Excellent, then use which one you want. Actually I've never seen `(?:'|\")` in FCC's code.

**Comment by natac13** [comment]
@bugron If you do not want me to use `(?:'|\")` then thats fine but I did fine [this by Kyle Simpsons](https://jsperf.com/regex-capture-vs-non-capture)

**Comment by natac13** [comment]
@bugron I just want to make sure your happy before I start changing the 40 challenges lol

**Comment by bugron** [comment]
@natac13 Wow, `(?:'|\")` is faster a lot. As I said use which one you want. I'm a camper just like you so I shouldn't tell you which way you need to go. If you're in a doubt maybe Quincy can help you? In my opinion if `(?:'|\")` works, then we should use it because it is faster. 
P.S. I'm happy :)

**Comment by natac13** [comment]
@bugron Sweet! man glad to hear and thank you for all the feedback it really helps!!

**Comment by bugron** [comment]
@natac13 You're welcome. Thank you for your contributions!

**Comment by natac13** [comment]
@bugron Alright the javscript file was not too bad either... however I have a speed bump. Before I commited these changes I did a `git fetch upstream` and there was a change. so do I jsut merge this in with the changes I have made in the working branch or should I do a `git stash` ad then merge in changes then `git stash apply`??

**Comment by bugron** [comment]
@natac13 i think you should `git stash`, it is safer then just merge. Do the stash, if everything is OK, apply, otherwise resolve conflicts, and then apply.

**Comment by natac13** [comment]
Ok I hope to get back to you with success!! lol

**Comment by awesomeaniruddh** [comment]
So has this been resolved, or do the challenges still need improvement?

**Comment by bugron** [comment]
I think this is resolved. Feel free to reopen if still there are challenges which tests accept only one type of quotes.
