### ISSUE TITLE
Adopt a styleguide

### ISSUE THREAD

**Issue by terakilobyte** [FreeCodeCamp/freecodecamp#307]
With more contributors we need a style guide to adhere to.

I personally vote for https://github.com/airbnb/javascript as it is sensible, with the addition of specifying a limit of either 80 or 120 characters per line maximum.

**Comment by StewartJarod** [comment]
:+1:

**Comment by QuincyLarson** [comment]
+1 I propose we adopt AirBnB's style guide wholesale and plan to stay up to date with changes in their style guide. As you noted, it doesn't say anything about character-per-line maximums. This is probably because any decent editor/IDE will have wordwrap, so character limits are unnecessary.

**Comment by QuincyLarson** [comment]
We have 3 yeses, and I believe @berkeleytrue also likes this style guide. I've gone ahead and updated our README.md to reflect that contributions should conform with the AirBnB style guide (and omitted any max characters per line for now).

**Comment by QuincyLarson** [comment]
See PR #310
