### ISSUE TITLE
Hikes: Binary Numbers

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#3074]
Watching Hikes 3 and 4 on Binary numbers, I think there is some more baseline information that should be included:
1) Computers MUST represent everything in binary.
* Possibly discuss digital vs. analog
This is relevant to a number of topics, including sound (8bit/16bit audiot) and video (8bit/16bit/32bit color).
* mention sampling errors as a prelude to accuracy issues

2) Note that binary is Base 2 (as opposed to Base 10).  
Show a comparison between the "ones, tens, hundreds, thousands" places (10^0, 10^1, 10^2, 10^3) and "ones, twos, fours, eights" (2^0, 2^1, 2^2, 2^3).

This is foundational information for understanding bitmasks and the "magic numbers" that bitmasks use.

3) Possible digression on byte, kilobyte, megabytes?

**Comment by SaintPeter** [comment]
Also, 2^8, byte = 256

**Comment by prashcr** [comment]
2^8 is 256 but a byte is 2^3 = 8.

**Comment by SaintPeter** [comment]
@prashcr Not sure what you mean.  A byte is 8 bits, 2^8 = 256.

**Comment by jbmartinez** [comment]
Definitely a byte has 8 bit, which gives a maximum value of 256 as @SaintPeter mentioned.

Anyway, I'm curious of the hikes because there's no hikes in my map. Do they appear after completing the basejumps?

**Comment by brianamarie** [comment]
I will look into writing a script for a video to preceed the existing binary videos. 

@jbmartinez, the hikes are not on the map yet. I'm not certain they'll ever be required as a part of Free Code Camp, but they may be supplimental material for people looking to keep progressing during their commute on a mobile device. Join the chat room here: https://gitter.im/FreeCodeCamp/hikes

**Comment by brianamarie** [comment]
@SaintPeter I'm looking at these suggestions in context of the current videos. Here's what I'm seeing and how to improve what we already have: 

1. Computers break everything into binary - This could be touched on in "intro to binary". Instead of creating an entire new video, possible addition of snippet within "intro to binary" that clarifys not only can all things be broken down, all computers must break all things into binary.

2. Binary is base 2 - In "decoding binary" at 33 seconds, insert snippit of text or video explaining that we multiply by 2 because binary is a base 2 numeral system instead of a base 10 numeral system that we're probably used to.

3. Byte/megabyte/kilobyte - Covered in "How to Measure data size".

What are your thoughts on these inclusions?

**Comment by SaintPeter** [comment]
I think the decoding binary video is fundamentally flawed.  I would encourage you to re-do it with a comparison to Base 10 place values as compared to Base 2 place values.  This chart is pretty much exactly how I'd show it:
![Base 10 vs Base 2 Number](https://i-msdn.sec.s-msft.com/dynimg/IC467115.png)

The idea is that every Base 10 digit has an underlying values based on its place.  You have the ones, tens, hundreds, and so on.   Similarly, in Base 2, you have the ones, twos, fours, eights, sixteens, and so on place.   A digit in each space (for either base) is multiplied by its corresponding place value.

Base 10:  
`302 === 3 * 100 + 0 * 10 + 2`

Base 2:
`100101110 === (1 * 256) + (0 * 128) + (0 * 64) + (1 * 32) + (0 * 16) + (1 * 8) + (1 * 4) + (1 * 2) + 0 === 302`

BTW, and this is more of an aside than anything, but may be relevant:
Have you ever wondered why we use Hex values (base 16)?
The answer is because each hex digit decodes into a nibble.

    0x0  = 0000
    0x1  = 0001
    0x2  = 0010
    ...
    0xA = 1010
    0xB = 1011
    0xC = 1100
    0xD = 1101
    0xE = 1110
    0xF = 1111

That means you can easily decompose multi-digit Hex numbers into their corresponding binary code/bytes:
`0xFFAA00 ==  1111 1111 1010 1010 0000 0000`

**Comment by SaintPeter** [comment]
@brianamarie Thinking more about the "Intro to binary code".
Right now this video doesn't seem to contain much information other than the unsupported assertion that everything computers do it "in binary" and there is no explanation of why that is.

To a large degree, the reason is that the technology that makes computer possible are transistors, and transistors are little electrical switches.  While you can use them for analog things, like the (old fashioned) "transistor radio", or almost all amplifies, they way they are used in a computer is to represent a one or zero.

The cool thing is that, by the application of logic gates (AND/OR/XOR/etc) and Boolean Algebra, you can represent "Finite State Machines" (of which a general purpose computer is a special case) which can, in turn make deterministic calculations.

Which is all very complex and probably too much.  But I think we need to get across this idea that all data stored and manipulated in a computer is in binary because of fundamental limitations in technology.
http://nookkin.com/articles/computer-science/why-computers-use-binary.ndoc
> We only use binary because we currently do not have the technology to create "switches" that can reliably hold more than two possible states. (Quantum computers aren't exactly on sale at the moment.) The binary system was chosen only because it is quite easy to distinguish the presence of an electric current from an absense of electric current, especially when working with trillions of such connections. And using any other number base in this system ridiculous, because the system would need to constantly convert between them. That's all there is to it.

Another fun fact:
Charles Babbages "[Difference Engine](https://en.wikipedia.org/wiki/Difference_engine)" actually uses base-10 storage.  The cogs that represent the registers have 10 different positions.  This is true, I believe, for most [mechanical calculators](https://en.wikipedia.org/wiki/Mechanical_calculator).

Anyway . . . I don't know how this turns into a video.  I just feel like the current video doesn't add a lot of value or understanding to the underlying reasons for computers to be binary or why we should even care.

**Comment by SEGrooms** [comment]
A good place to start before introducing binary (base-2), is the concept that numbers can be expressed in any base-n form. This is most naturally explained by mentioning the division algorithm. It becomes visibly clear that all numbers can be expressed in the form 2q+r, where q & r are integers and 0 <= r < 2. It is also just as clear that all numbers can be expressed as 10q+r, where q & r are integers and 0 <= r < 10. It should become clear that this works for all nq+r, where n,q,r are integers and 0 <= r < n.

**Comment by BerkeleyTrue** [comment]
https://github.com/FreeCodeCamp/hikes/issues/147
