### ISSUE TITLE
Hikes: Computer Security

### ISSUE THREAD

**Issue by benmcmahon100** [FreeCodeCamp/FreeCodeCamp#3075]
Small issue with the computer security video. Just a heads up that SSL is not 100% safe

https://wirewatcher.wordpress.com/2010/07/20/decrypting-ssl-traffic-with-wireshark-and-ways-to-prevent-it/

**Comment by brianamarie** [comment]
I have uploaded a revised version which addresses this.

**Comment by bugron** [comment]
Sound like the issue is resolved. Feel free to reopen if it's not, thanks.
