### ISSUE TITLE
targeting bug

### ISSUE THREAD

**Issue by impaler1** [FreeCodeCamp/FreeCodeCamp#3076]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
![screen shot 2015-09-04 at 6 18 49 pm](https://cloud.githubusercontent.com/assets/13444483/9697011/02bd9f5c-5332-11e5-8868-2002216b32b4.png)

**Comment by bugron** [comment]
@impaler1 thanks for posting this issue!
Actually your code is incorrect because:
>Use **each** of these jQuery selectors to target your **button** element with the class **btn** and the id **target1**.
>Use the addClass() jQuery function to give the element **one new class for each selector**: animated, shake, and btn-primary.

So the correct code looks like this:
```javascript
$('.btn').addClass('animated');
$('button').addClass('shake');
$('#target1').addClass('btn-primary');
```
or another five combinations.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
