### ISSUE TITLE
Expectations are wrong for this exercise

### ISSUE THREAD

**Issue by dptesta** [FreeCodeCamp/FreeCodeCamp#3077]
Challenge http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The exercise calls for capitalizing the first letter of each word in a string, which is what I did and it passes the test for that (I'm A Little Teapot).  However, there are a couple of additional tests that don't appear to belong to this exercise that are failing.  This is preventing me from completing the challenge.

expect(titleCase("sHoRt AnD sToUt")).to.equal("Short And Stout");expected 'SHoRt AnD SToUt' to equal 'Short And Stout'
expect(titleCase("HERE IS MY HANDLE HERE IS MY SPOUT")).to.equal("Here Is My Handle Here Is My Spout");expected 'HERE IS MY HANDLE HERE IS MY SPOUT' to equal 'Here Is My Handle Here Is My Spout'

**Comment by awesomeaniruddh** [comment]
The exercise calls for capitalising the first letter of a word in a *string*, not in *the* string. I hope you understand the difference? You need to be able to capitalise the first word of a letter of *any* string, not just the one provided to you. The one provided only serves as an example.

The additional tests are there to ensure that you are able to capitalise the first letter of a word of *any* string.

**Comment by asdal** [comment]
Rule states "Return the provided string".
As we are a dealing with a function here which takes an argument (any string), It should be able to work on "any" string, regardless.

**Comment by abhisekp** [comment]
@dptesta Please read the contribution guidelines before posting. Always ask others in chat room if this is an actual issue.

@QuincyLarson Please close this issue as it's irrelevant.

**Comment by benschenker** [comment]
Thanks for posting this @dptesta!

I think others have cleared this up a bit.  I am going to close this as resolved but feel free to reopen if this has not resolved your issue.

**Comment by dptesta** [comment]
Yes, I'm clear now.  Thanks.

Dan

From: Ben Schenker
Reply-To: FreeCodeCamp/FreeCodeCamp
Date: Tuesday, September 8, 2015 at 7:57 PM
To: FreeCodeCamp/FreeCodeCamp
Cc: daniel testa
Subject: Re: [FreeCodeCamp] Expectations are wrong for this exercise (#3077)


Thanks for posting this @dptesta<https://github.com/dptesta>!

I think others have cleared this up a bit. I am going to close this as resolved but feel free to reopen if this has not resolved your issue.
