### ISSUE TITLE
<p>Click here for <a href="freecatphotoapp.com">cat photos</a>.</p>

### ISSUE THREAD

**Issue by jnatrasevschi** [FreeCodeCamp/FreeCodeCamp#3078]
Challenge http://freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

the directions say to nest the element and that is what i did but it reads like this

![screen shot 2015-09-04 at 11 30 51 pm](https://cloud.githubusercontent.com/assets/14061530/9697690/1a87f102-535d-11e5-9f52-4e84f25b0f84.png)

**Comment by bugron** [comment]
@jnatrasevschi thanks for posting this issue!
I'm able to pass that test even with your code which is incorrect because:
>Now nest your **existing** a element within a new p element so that the surrounding paragraph...

You've actually nested a **new** `a` element.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by punyas25** [comment]
![image](https://cloud.githubusercontent.com/assets/14279168/9883595/98702884-5bf8-11e5-9af3-5ba06f876d21.png)



This issue is still occuring

**Comment by bugron** [comment]
@punyas25 I've just passed that test with [your code](http://prntscr.com/8goals).

**Comment by punyas25** [comment]
@bugron  I am still unable to do it

**Comment by 4mifix** [comment]
@punyas25 <https://github.com/punyas25> refresh the browser and try it
again. If that does not work clear the browser cash of the FCC links and
try it again.

On Tue, Sep 15, 2015 at 1:14 PM, punyas25 <notifications@github.com> wrote:

> @bugron <https://github.com/bugron> I am still unable to do it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3078#issuecomment-140468619>
> .
>



-- 
Brian L. Mayers
917-459-3517

**Comment by 4mifix** [comment]
@punyas25 <https://github.com/punyas25> sorry not you.

@bugron refresh the browser and try it again. If that does not work clear
the browser cash of the FCC links and try it again.

On Tue, Sep 15, 2015 at 1:58 PM, B Lloyd <4mifix@gmail.com> wrote:

> @punyas25 <https://github.com/punyas25> refresh the browser and try it
> again. If that does not work clear the browser cash of the FCC links and
> try it again.
>
> On Tue, Sep 15, 2015 at 1:14 PM, punyas25 <notifications@github.com>
> wrote:
>
>> @bugron <https://github.com/bugron> I am still unable to do it
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3078#issuecomment-140468619>
>> .
>>
>
>
>
> --
> Brian L. Mayers
> 917-459-3517
>



-- 
Brian L. Mayers
917-459-3517

**Comment by workerhn** [comment]
I understand check line 30 of your editor. You've already have a code there to continue!!

**Comment by punyas25** [comment]
I know. But that same piece of code wasn't working earlier. Cleared the cache and tried again. It worked after that. But thanks


Sent from Samsung Mobile

-------- Original message --------

**Comment by akshay231** [comment]
you can try refreshing, i just checked - your code is working

**Comment by KhalilNiser** [comment]
You are the "s in https:", you have it as "http://"

**Comment by KhalilNiser** [comment]
You are missing the "s", my mistake

**Comment by priyaoj** [comment]
does it work
