### ISSUE TITLE
Coding is correct but still not accepting 

### ISSUE THREAD

**Issue by aslamweb** [FreeCodeCamp/FreeCodeCamp#3079]
![image](https://cloud.githubusercontent.com/assets/14052934/9697895/8b192168-53ba-11e5-9da0-372e8dbced13.png)
Challenge http://freecodecamp.com/challenges/waypoint-size-your-images has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by bugron** [comment]
@aslamweb thanks for posting this issue!
Note that your issue is a duplicate so I'll close it. For more info [see here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3059#issuecomment-137824447).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by aslamweb** [comment]
This one is different , check out everything is correct but still not submitting , in mentioned issue there was mistake in coding.

**Comment by bugron** [comment]
@aslamweb please, be attentively, http://prntscr.com/8cs3h0, thanks.

**Comment by aslamweb** [comment]
Sorry , I got it thanks : )

**Comment by ashishga** [comment]
hi i am getting same issue but code is correct

![image](https://cloud.githubusercontent.com/assets/10413525/9881585/472287ce-5bee-11e5-9370-941e956448d5.png)

**Comment by Badonis109** [comment]
Having the same Issue with correct code... 
![image](https://cloud.githubusercontent.com/assets/13454064/10037493/ee0b35a4-6184-11e5-98cc-936a7370d124.png)

**Comment by bugron** [comment]
@Badonis109, actually your code is incorrect. You gave your image a class of '.smaller-image'. Remove that dot before the word 'smaller'.
