### ISSUE TITLE
Solution isn't working?

### ISSUE THREAD

**Issue by florianpnn** [FreeCodeCamp/FreeCodeCamp#3082]
Challenge http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Here is what I enter :
```
function palindrome(str) {
  var newStr = str.replace(/[\W_]/g).toLowerCase;
  var reverseStr = newStr.split('').reverse().join('');
  return newStr === reverseStr
}
```

The message I get : "newStr.split is not a function"

**Comment by florianpnn** [comment]
The solution from the wiki :
```
function palindrome(str) {
  var normalizedStr = str.replace(/[\W_]/g, '').toLowerCase();
  var reversedStr = normalizedStr.split('').reverse().join('');
  return normalizedStr === reversedStr;
}
```

**Comment by mannabarapu** [comment]
function palindrome(str) {
  var str1 = str.replace(/[\W_]/g,'').toLowerCase();
  var str2=str.replace(/[\W_]/g,'').toLowerCase().split('').reverse().join('');
  
  return str1===str2;
}
palindrome("B_e!y_e_");
