### ISSUE TITLE
editor.match(...) is null

### ISSUE THREAD

**Issue by mohitkr05** [FreeCodeCamp/FreeCodeCamp#3085]
Challenge http://freecodecamp.com/challenges/waypoint-nest-many-elements-within-a-single-div-element has an issue.  The last challenge shows an editor.match(...) is null

**Comment by bugron** [comment]
@mohitkr05 thanks for posting this issue!
Everything is fine for me. Please, provide your code and screenshot, thanks!.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by benschenker** [comment]
Closing as stale.  Please reopen/comment if the issue has not been resolved for you.
