### ISSUE TITLE
Waypoint use spans for inline elements reverts to previous waypoint styling

### ISSUE THREAD

**Issue by duffn** [FreeCodeCamp/FreeCodeCamp#3089]
Challenge http://freecodecamp.com/challenges/waypoint-use-spans-for-inline-elements has an issue. 

This waypoint reverts back to a previous waypoint styling.
* It still contains the `smaller-image` class on the `https://bit.ly/fcc-relaxing-cat` image, though the class was removed and replace with `img-responsive` in the previous waypoint. 
* It contains the dead link `Click here for cat photos.`
* The h2 heading still contains the `red-text` class.

```html
<h2 class="red-text text-center">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>
<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
```

<img width="333" alt="screen shot 2015-09-05 at 8 23 29 am" src="https://cloud.githubusercontent.com/assets/3457341/9699640/0f29a756-53a8-11e5-8ac3-b8c64612f190.png">

It should be
 ```html
<h2 class="text-primary text-center">CatPhotoApp</h2>
<a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
```

<img width="329" alt="screen shot 2015-09-05 at 8 28 51 am" src="https://cloud.githubusercontent.com/assets/3457341/9699649/2f1fb9b0-53a8-11e5-8cfd-de3bf508ab3a.png">

**Comment by awesomeaniruddh** [comment]
Fixing this.

**Comment by awesomeaniruddh** [comment]
The PR fixes the incorrect styling, but the dead link seems to be there on every waypoint so I guess it is intended?

**Comment by duffn** [comment]
The previous Waypoint (http://freecodecamp.com/challenges/waypoint-ditch-custom-css-for-bootstrap), says to:
> ...delete the p element that contains a dead link.

**Comment by awesomeaniruddh** [comment]
Crap, missed it. Let me update the PR. Thanks for the catch!
