### ISSUE TITLE
Bonfire: Title Case a Sentence

### ISSUE THREAD

**Issue by berzo90** [FreeCodeCamp/FreeCodeCamp#3090]
![schermata 2015-09-05 alle 17 22 53](https://cloud.githubusercontent.com/assets/11093291/9699921/c7e63d82-53f2-11e5-9e08-59dbd6432169.png)
Challenge http://www.freecodecamp.com/challenges/bonfire-title-case-a-sentence has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by berzo90** [comment]
![schermata 2015-09-05 alle 17 24 54](https://cloud.githubusercontent.com/assets/11093291/9699930/0d9eabca-53f3-11e5-9445-7418f9da3f5e.png)

**Comment by bugron** [comment]
@berzo90 thanks for posting this issue!
Actually the error message is quite informative. Is says:
>**str.charAt** is not a function

After this line of your code: `str = str.toLowerCase().split(" ");` your `str` variable becomes an **array** and arrays **don't** have **charAt** method. You can find correct solution in our [Wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by asdal** [comment]
@berzo90 : you are have way through already. We have sentence split as individual word. Now we can capitalize first letters for all. This would help hopefully 

<code> str.slice() </code>
<code> str[i].charAt(0) </code>

**Comment by abhisekp** [comment]
@berzo90 When you find an issue, first ask in the https://gitter.im/FreeCodeCamp/FreeCodeCamp chat room if it's an actual issue. Then only post your issue here.

**Comment by benschenker** [comment]
Closing this as stale.  Please reopen/comment if this has not been resolved for you.

**Comment by arulbenjaminchandru** [comment]
![freecodecamp](https://cloud.githubusercontent.com/assets/3948944/11669152/2b968a76-9e21-11e5-94cb-1d8758963765.jpg)

**Comment by arulbenjaminchandru** [comment]
My return statement is exactly matching the expected output in test case but not processed.

**Comment by arulbenjaminchandru** [comment]
please do the needful

**Comment by SaintPeter** [comment]
@arulbenjaminchandru Without a link to your code (copy your solution URL), there is not much we can do.

Did you do as requested and ask for assistance in https://gitter.im/FreeCodeCamp/Help or https://gitter.im/FreeCodeCamp/HelpBonfires ? 

Also, did you know that you can reuse variables?  That's why they're called variables.  I can't understand why you have soooo many variables.

**Comment by arulbenjaminchandru** [comment]
I solved it. Actually my code is adding an extra space after the output. This caused the issue. @SaintPeter Thank you :)

**Comment by nethajireddy** [comment]
`function titleCase(str) 
{
return str.split(' ').map(function(a){return a.toLowerCase();}).map(function(a){return a.replace(a[0],a[0].toUpperCase());}).join(' ');
}`
