### ISSUE TITLE
Directions not showing at all.

### ISSUE THREAD

**Issue by Rich-Hopkins** [FreeCodeCamp/FreeCodeCamp#3093]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by bugron** [comment]
@Rich-Hopkins do not duplicate your issues!

**Comment by Rich-Hopkins** [comment]
Wow - how irresponsible is it to close an issue just because you can't duplicate it. Your not duplicating it doesn't mean it isn't an issue.

**Comment by bugron** [comment]
@Rich-Hopkins yes, but that doesn't mean than you should duplicate the same issue three times.
