### ISSUE TITLE
Code Challenge doesn't accept two classes in the same element

### ISSUE THREAD

**Issue by DitriAhmetaj** [FreeCodeCamp/FreeCodeCamp#3096]
Challenge http://freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

This is my code and yet the challenge doesn't pass : 

<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image" class="thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }
  
  .smaller-image {
    width: 100px;
  }
  
  .thick-green-border {
    border-width: 10px;    
    border-style: solid;
    border-color: green;
  }
  
  p {
    font-size: 16px;
    font-family: Monospace;
  }

Apparently the challenge doesn't accept two classes in the same element. 
How to fix this ?

Thanks,

Ditri

**Comment by bugron** [comment]
@DitriAhmetaj thanks for posting this issue!
First of all your `style` tag should go after `link` element and **not** at the bottom of you HTML. Second point is that you should add second `class` to your image like this `class="smaller-image thick-green-border"` and **not** `class="smaller-image" class="thick-green-border"`.
And finally, please, add your code in GitHub issues in special blocks, for more info [see here](https://guides.github.com/features/mastering-markdown/), thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
