### ISSUE TITLE
Add Footer with links to FCC

### ISSUE THREAD

**Issue by Chris2Brooks** [FreeCodeCamp/freecodecamp#31]
None of the FCC pages (logged in or out) has a footer bar or footer menu with relevant links for users to follow.

Adding a footer bar with links to more info about FCC:
* Blog link (currently no link anywhere), 
* Creative Commons/ Open Source License/ Copyright, 
* Github and Social Media links, 
* Privacy Policy, 
* Forum and Chat links

Not only will this make exploring FCC much easier but will be great for SEO as well.

**Comment by iheartkode** [comment]
I agree but only on the logged in page, we don't want any distractions from our conversions.

**Comment by Chris2Brooks** [comment]
Good point

**Comment by terakilobyte** [comment]
Closing this as the footer is now integrated, and all links can be found either there or in the header. Please open a new issue to suggest changes to those elements.
