### ISSUE TITLE
the tests are order sensitive for the returned arrays

### ISSUE THREAD

**Issue by prjahelka** [FreeCodeCamp/FreeCodeCamp#3101]
Challenge http://www.freecodecamp.com/challenges/bonfire-symmetric-difference has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I forced a sorted result to match the expected results for all but the first test.
My algorithm exactly matches the first test with [3,5,4], but the expect results
for the next two tests are in sort order, not as they appear in the arrays.
tests 2 and 3 should expect [1,5,4] or the results shouldn't be order dependent.

**Comment by bugron** [comment]
@prjahelka thanks for posting this issue!
Please, provide your code and a screenshot, thanks!.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
