### ISSUE TITLE
could use a better test for checking .length usage

### ISSUE THREAD

**Issue by CGDS** [FreeCodeCamp/FreeCodeCamp#3105]
Challenge http://freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-last-character-in-a-string has an issue.

test asserting `.length` is used will always be true, as the example code in the editor uses it.

**Comment by bugron** [comment]
@CGDS thanks for pointing this out!
You're right. Actually that assert should check if there are **minimum** two `.length`'s in the code.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
