### ISSUE TITLE
Hikes:  Video 11, How IP Address Works, Ends Abruptly

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#3111]
Video 11 ends very abruptly and with Briana turning her head to one side.  It doesn't have the "quick review" that the other videos have.  It seems like there might have been an editing error?

https://www.youtube.com/watch?v=zdNhDDSbMLE&list=PLWKjhJtqVAbmfoj2Th9fvxhHIeqFO7wOy&index=11

**Comment by brianamarie** [comment]
The updated version with a new ending is uploaded to both vimeo and youtube. Thank you SaintPeter!
