### ISSUE TITLE
[Suggestion] Reduce the number of clicks needed to move on to next challenge.

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/FreeCodeCamp#3113]
Going thought the Waypoints I realized that once we wrote our code, we had to click "Run code" then "Run tests" then "Submit" to go to the next challenge.

I think it would be better if after clicking "Run tests" - we get redirected to the next challenge. I'm not sure how everyone else feels about this. But I feel that the number of clicks to move on should be limited to 2.

**Comment by bugron** [comment]
@AkiraLaine thanks for posting this issue!
Thank you for your suggestion! Actually there is a similar one in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2772, so I'll close this issue. You can continue further discussion there, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
