### ISSUE TITLE
CTRL+Enter no longer advances to the next challenge

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3117]
@benmcmahon100 Usually when completing a challenge, I'm able to hit control+enter to advance to the next challenge. But now I actually need to click the "submit" button manually. I think this may be related to the jsframework refactor.

**Comment by benschenker** [comment]
The CTRL + Enter just worked for me on http://freecodecamp.com/challenges/waypoint-iterate-over-arrays-with-map.  Is there a specific challenge that this doesn't work on?
