### ISSUE TITLE
Unable to view the tests to pass the Waypoint 

### ISSUE THREAD

**Issue by avikghosh** [FreeCodeCamp/FreeCodeCamp#3122]
Challenge http://freecodecamp.com/challenges/waypoint-delete-your-jquery-functions has an issue. 

I am not able to view the instructions/tests in the bottom left pane. I am using chrome 45.0.2454.85 m. Screenshot attached below.
![image](https://cloud.githubusercontent.com/assets/6515462/9705139/0d9b53cc-54d8-11e5-90e0-34901b30aab6.png)

**Comment by bugron** [comment]
@avikghosh thanks for posting this issue!
We are aware of this issue. It is a global problem (https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2717 and https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1081) so I'll close this issue. You can continue further discussion there, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
