### ISSUE TITLE
Only allow campers who are github cool to post news articles.

### ISSUE THREAD

**Issue by wildlifehexagon** [FreeCodeCamp/FreeCodeCamp#3126]
It looks like the FCC News page is starting to get spammed. User fcc462daf56 is linking to some really shady looking sites, many of which aren't related to web development.

It's disappointing that this is happening, but maybe we can get a way to flag submissions like this?

**Comment by BerkeleyTrue** [comment]
Doesn't seem like spam, just unrelated to programming.

**Comment by BerkeleyTrue** [comment]
We are removing those stories.

**Comment by wildlifehexagon** [comment]
Nah, they are definitely spam. The "Best Laptop For Programming" article is loaded with affiliate links, and the sports pages have keyword stuffing. I'm not sure what this user is trying to accomplish since I'm not seeing much for actual ads on those pages, but they are of dubious quality.

I haven't noticed anything since this batch of weird submissions so hopefully it's not something that comes up again. But maybe it's worth setting up a 'flag' option or a quality check system in the future.

**Comment by BerkeleyTrue** [comment]
I've changes the title of this issue. We will be requiring users be authenticated through Github (isGithubCool) to post in news. We will track progress of that here. 

@wildlifehexagon Thanks for bringing this to our attention. When this gets implemented it should be enough to prevent spam. If the issue persist after we will look into a flag option.

**Comment by wildlifehexagon** [comment]
Cheers! I do search engine evaluation work as my full-time gig right now so I can spot spam from a mile away. Just don't want it to infiltrate FCC.

I think requiring Github authentication will be enough to deter posts like those. Thanks for looking into it!

**Comment by bugron** [comment]
Closing this issue as https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3849 is merged.
