### ISSUE TITLE
Not really a bug, just a comment on test wording

### ISSUE THREAD

**Issue by rhyspowell** [FreeCodeCamp/FreeCodeCamp#3130]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-different-padding-to-each-side-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Might have already been suggested but the wording for the actual tests isnt amazingly clear.

Dont mind taking a look if you think it is something that might need fixing

**Comment by awesomeaniruddh** [comment]
It looks clear enough to me?

What changes might you suggest?

**Comment by rhyspowell** [comment]
looking back when not so tired, its not quite as bad possibly missing "the" from the sentences.

Your green-box class should give the top of _the_ elements 40px of padding.

Not sure if the ext is auto generated in any way and needs to fit in multiple locations...
