### ISSUE TITLE
me

### ISSUE THREAD

**Issue by samuel1290** [FreeCodeCamp/FreeCodeCamp#3132]
Challenge http://freecodecamp.com/challenges/waypoint-change-the-color-of-text has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by awesomeaniruddh** [comment]
Please describe your issue with the waypoint?

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!
