### ISSUE TITLE
Received ‘missing ) after argument list’ error, but passes tests.

### ISSUE THREAD

**Issue by jwjb** [FreeCodeCamp/FreeCodeCamp#3133]
Challenge http://freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![screen shot 2015-09-06 at 4 18 29 pm](https://cloud.githubusercontent.com/assets/3523591/9707180/d4f02c24-54b3-11e5-994d-26b705391e4a.png)
![screen shot 2015-09-06 at 4 19 06 pm](https://cloud.githubusercontent.com/assets/3523591/9707179/d4ec6e68-54b3-11e5-9e5b-8a694e79d8ea.png)

**Comment by awesomeaniruddh** [comment]
Yep, I got the same error.

**Comment by natac13** [comment]
I can pass this test fine....
![d](https://cloud.githubusercontent.com/assets/10660283/9707350/71c3a426-54d3-11e5-9bdc-94b79182d516.png)

**Comment by natac13** [comment]
So I am able to pass the test and will fix the parentheses
![d](https://cloud.githubusercontent.com/assets/10660283/9707360/e64273b8-54d3-11e5-8e80-d134eb659f7d.png)

**Comment by awesomeaniruddh** [comment]
Passing the test fixes the parenthesis, but I think the editor checks for any syntax in real-time because it gave me errors as I was writing code.

If that is the case, then I would expect the editor to also detect a *lack* of any syntax errors in real-time, without me having to click Run Code.

**Comment by natac13** [comment]
There are `()` in the description part of the test and there cannot be in the json files... I have fixed a few of these

**Comment by natac13** [comment]
I do think you are right about it checking while you type in the code... I am not sure how it does that though

**Comment by jwjb** [comment]
@awesomeaniruddh I think you are right on this as I just saw this happen as detailed in the third screenshot below and @natac13 I too would like to know how this happens with some screenshots below from other Waypoints for your reference.

![screen shot 2015-09-07 at 8 07 54 am](https://cloud.githubusercontent.com/assets/3523591/9719748/810bb9f0-553c-11e5-881b-7bb2bdd545d8.png)
![screen shot 2015-09-07 at 8 08 01 am](https://cloud.githubusercontent.com/assets/3523591/9719749/810eefb2-553c-11e5-8f6d-8837f0006fc2.png)
![screen shot 2015-09-07 at 8 12 57 am](https://cloud.githubusercontent.com/assets/3523591/9719751/8111df2e-553c-11e5-8be9-d50ff6d9c6bc.png)
![screen shot 2015-09-07 at 8 13 04 am](https://cloud.githubusercontent.com/assets/3523591/9719750/8110ed4e-553c-11e5-9d93-96afdbad18e8.png)

**Comment by natac13** [comment]
@jwjb Working on that blog now I hope to have it done by days end!

**Comment by jwjb** [comment]
@natac13 Awesome and cannot wait to read it, thanks.

**Comment by natac13** [comment]
@jwjb Here we go https://natacseanc.wordpress.com/2015/09/07/beginners-guide-to-easy-contributions-to-free-code-camp/ You are the first one to read so any feedback can only help me improve! Thank you for the inspiration and I really hope you after you will be able to fix these issue as well!

**Comment by jwjb** [comment]
@natac13 Posted a variationn on this comment after reading your blog post [BEGINNER’S GUIDE TO EASY CONTRIBUTIONS TO FREE CODE CAMP](https://natacseanc.wordpress.com/2015/09/07/beginners-guide-to-easy-contributions-to-free-code-camp/) which is really a great read that I will refer to often and hope to use in the future to fix these issues too so thanks a million for documenting your process. Unfortunately, I am unable to give any specific feedback other than to say it looks great and it makes sense, until I become more knowledgeable, but reading through your post and understanding you are a fc3 (Free Code Camp Camper) too, I am inspired to contribute to fcc as well, so thanks for all your efforts and happy coding!
