### ISSUE TITLE
Unclear Instructions

### ISSUE THREAD

**Issue by akjellis** [FreeCodeCamp/FreeCodeCamp#3134]
For the jquery class: is it "animate or animated?  According to google, the class is animate.  Yoiur instructions say "animated" I have been playing around with the classes but not making sense.

<script>
$(document).ready(function() {
$("button").addclass("animate");
$(".btn").addclass("shake"); 
$("#target1").addclass("btn-primary");    
    
    
    
    
    
  });
</script>

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by awesomeaniruddh** [comment]
I believe you are referring to the `animate()` *function* or *method* that jQuery provides. There is no `animate` class provided by jQuery that I'm aware of.

The purpose of the exercise is to teach you how to add and remove classes, not animate elements. FreeCodeCamp has JS and CSS files attached to the page of the waypoint that take care of the animation for you. Simply adding the `animated` class to any random element on a page with jQuery attached will not animate the object: you must target that class and animate it, either using CSS or using jQuery.

The instructions on how to add/remove classes are clear enough, which serves the purpose of the waypoint.

**Comment by Mansuro** [comment]
The class is **animated**, it's not a jQuery class, it's coming from the css framework animate.css https://github.com/daneden/animate.css/blob/master/source/_base.css

**Comment by bugron** [comment]
@akjellis thanks for posting this issue!
>Use the `addClass()` jQuery function to give the element one new class for each selector: **animated**, shake, and btn-primary.

In my opinion instructions are very clear. As @Mansuro mentioned **animated** class is from Animate.css. Also this is mentioned in [source code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/jquery.json#L62). Unfortunately, this is not in production yet.
Closing this issue.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
