### ISSUE TITLE
Received ‘Unexpected token }’ error, but passes tests.

### ISSUE THREAD

**Issue by jwjb** [FreeCodeCamp/FreeCodeCamp#3135]
Challenge http://freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

![screen shot 2015-09-06 at 4 46 05 pm](https://cloud.githubusercontent.com/assets/3523591/9707282/500f04ae-54b7-11e5-924f-0fcda46a9963.png)
![screen shot 2015-09-06 at 4 46 30 pm](https://cloud.githubusercontent.com/assets/3523591/9707283/5021dbc4-54b7-11e5-9465-79b67b940622.png)

**Comment by awesomeaniruddh** [comment]
Please don't create another issue for a similar error. This can very well be merged with the previous issue you opened :)

**Comment by natac13** [comment]
@jwjb @awesomeaniruddh On this on you are missing a `;` at the end of your line giving that error.... it still passes since the test does not account for a missing `;`

**Comment by jwjb** [comment]
@natac13 Great point and I am missing a `;`. Interestingly, I get a similar error which I will not create another issue for since it is similar to #3133 (and probably to #3135) per @awesomeaniruddh which I did not know being a newbie to jQuery and freeCodeCamp too, but have included this issue in the below screenshots for your reference where I do have a `;` at the end of the two jQuery statements.

![screen shot 2015-09-06 at 5 02 12 pm](https://cloud.githubusercontent.com/assets/3523591/9707419/f50ef950-54bc-11e5-84f6-30474b30895b.png)
![screen shot 2015-09-06 at 5 02 26 pm](https://cloud.githubusercontent.com/assets/3523591/9707420/f51128c4-54bc-11e5-8c33-79baa9dca781.png)

Regardless, I will close this issue and not open similar issues henceforth although I feel it would be best to err on the side of caution and report any and all issues which could then be closed on a case-by-case basis after ensuring they are indeed the same issue as these kinds of errors or any errors for that matter for a newbie like me leave me to question my code even when it passes all the tests.

Along these lines it is interesting to note that in [Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp#contributing) item 6 in the [README.md](https://github.com/FreeCodeCamp/FreeCodeCamp) this statement **Please do not ignore any linting errors, as they are meant to help you.** excerpted from below where I would it would seem these are 'linting errors' of some sort and should not be ignored and if they are not all reported it seems to me they could be ignored and remain within the particular Waypoint, etc to cause confusion for Free Code Camp campers (students) and seasoned JavaScript developers alike, IMHO.

> You should have ESLint running in your editor, and it will highlight anything doesn't conform to AirBnB's JavaScript Style Guide. **Please do not ignore any linting errors, as they are meant to help you.** Make sure none of your JavaScript is longer than 80 characters per line.

**Comment by natac13** [comment]
@jwjb I agree with you completely on the linting thing! However from what I can tell the linter does not pick this up... 
I would also say keep making issues for **anything** you see wrong!! Obviouvsly do a search for a similar issue.... I really thank you for finding this since it an issue that I am able to fix! lol

**Comment by jwjb** [comment]
@natac13 Just awesome and maybe you could write a blog post on how exactly you fix such an issue as it would not only be great reading, but a great learning resource for us fc3s (Free Code Camp campers) too. By the way, is there a better acronym for Free Code Camp campers than the off the cuff one **fc3s** I just came up with?

**Comment by natac13** [comment]
@jwjb That is a fantastic idea! And I will do just that! I will send you the link once I get finished and I should try to remember to post in the camper news sections for the rest of the **fc3s**.
Not seen any other acronym so I went with the one you came up with!!
