### ISSUE TITLE
Waypoint only shows full code on scroll

### ISSUE THREAD

**Issue by LauraNK** [FreeCodeCamp/FreeCodeCamp#3138]
http://www.freecodecamp.com/challenges/waypoint-make-object-properties-private

Only the code up to line 10 is shown until I scroll the window, then all of the code appears.
http://i.imgur.com/mZgRdxR.png
http://i.imgur.com/IAilUT0.png

It's a small bug, but it really threw me off at first as I couldn't figure out if I was supposed to be writing the methods myself that the question was referring to.

**Comment by awesomeaniruddh** [comment]
I'm not fully aware whether this is a design choice or a bug, but I would definitely prefer the entire code to be shown without the camper having to click or scroll the code editor. It is definitely confusing.

**Comment by bugron** [comment]
@LauraNK thanks for posting this issue!
Note that your issue is a duplicate:
https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2707
Closing this issue as a duplicate. You can continue further discussion there, thanks.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
