### ISSUE TITLE
Waypoint Responsive 9

### ISSUE THREAD

**Issue by smashzen** [FreeCodeCamp/FreeCodeCamp#3140]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side has an issue.
Coding area shows the sample CSS when it should show the sample HTML. Challenge asks student to edit the HTML.
![fcc-error](https://cloud.githubusercontent.com/assets/13346385/9708737/dfcad374-54e5-11e5-86a0-e843cd201948.jpg)

**Comment by awesomeaniruddh** [comment]
Please click inside the editor. That will display the rest of the code.

I'm not entirely sure why only part of the code is displayed initially. It is definitely confusing. Maybe @BerkeleyTrue or @QuincyLarson can comment on the design choice? It might be a bug.
