### ISSUE TITLE
Feature: Quick way to copy tests from Bonfires

### ISSUE THREAD

**Issue by clintoncampbell** [FreeCodeCamp/FreeCodeCamp#3144]
As I've spent a bit more time helping campers, I've realized theres a bit of a need to make it easier for newbies to troubleshoot outside of the Bonfire screen. I often send them to jsfiddle or codepen and instruct them on how to bring in firebug-lite so that they can see their code without any extra cruft, but I'd love a convenient way to copy the tests to the pasteboard so that they can also insert within the fiddle/pen and ensure that everything is working before switching back into FCC.

**Comment by bugron** [comment]
I think this is not required now because campers can easily share solutions by sending to others links of the solutions (can be found in the user's code portfolio page). Closing.
