### ISSUE TITLE
"Get Set for Basejumps" Cloud9 configuration issues

### ISSUE THREAD

**Issue by anjanjanj** [FreeCodeCamp/FreeCodeCamp#3146]
Challenge http://www.freecodecamp.com/challenges/waypoint-get-set-for-basejumps has an issue.

Today I was following this waypoint and found that the provided instructions to configure the environment causes the Yeoman wizard to crash on its second step with this message:
```
/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/app/generator.js:3
import fs from 'fs';
^^^^^^
SyntaxError: Unexpected reserved word
...
```

I was able to get it to work by updating node to v0.12.7 before running Yeoman:
```
nvm install v0.12.7
nvm alias default v0.12.7
```

So **step 7** of the waypoint instructions can be changed to use:
```
rm -rf * && nvm install v0.12.7 && nvm alias default v0.12.7 && echo "export NODE_PATH=$NODE_PATH:/home/ubuntu/.nvm/versions/node/v0.12.7/lib/node_modules" >> ~/.bashrc && source ~/.bashrc && npm install -g yo grunt grunt-cli generator-angular-fullstack && yo angular-fullstack
```

Later on, at **step 46**, it seems like Cloud9 uses an outdated version of heroku-toolbelt so addons:create doesn't work. addons:add can be used instead:
```
cd ~/workspace/dist && heroku config:set NODE_ENV=production && heroku addons:add mongolab
```

Everything else seems to be ok so far. Hope that helps!

**Comment by jbmartinez** [comment]
It worked for me several times without updating node.js, it's important to update npm though

**Comment by anjanjanj** [comment]
That's odd, when did you try it? It wasn't working yesterday. I guessed the Yeoman script changed perhaps. I tested it a few times with different methods and found I just needed to update node to make it work.

**Comment by jbmartinez** [comment]
I use it two days ago, perhaps it was updated yesterday

**Comment by awesomeaniruddh** [comment]
Instead of using addons:add, why not update heroku-toolbelt?

**Comment by carnivean** [comment]
I tried to get it working today and it just won't...

Following the commands on step 7 as written in the OP I could finish that step.
But on step **27** it kills the 
```javascript
npm install 
```
If I rerun it several times, it will work but the cache is corrupted or something else is seriously gone wrong, because on step **29** when I execute **grunt serve** it gives me some error
```javascript 
carnivean@fcc-base:~/workspace $ grunt serve
/home/ubuntu/workspace/node_modules/grunt/node_modules/async/lib/async.js:339
});
 ^
SyntaxError: Unexpected token )
  at exports.runInThisContext (vm.js:73:16)
  at Module._compile (module.js:443:25)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/home/ubuntu/workspace/node_modules/grunt/node_modules/async/index.js:3:18)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/home/ubuntu/workspace/node_modules/grunt/node_modules/grunt-legacy-util/index.js:24:14)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/home/ubuntu/workspace/node_modules/grunt/lib/grunt.js:26:12)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v0.12.7/lib/node_modules/grunt-cli/bin/grunt:45:1)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

The error is different each time, sometimes it is async, on another try (completly new instance where I redid the whole procedure) ..

When I do 
```javascript
npm cache clean
rm -rf node_modules
npm install 
```
to clean it, it will kill the install process the next time its run and get corrupted again..

I have no idea, how I can progress using C9 and the free instance, it seems impossible for me, something always goes wrong, when I try to do the **npm install**...

**Comment by jbmartinez** [comment]
I used the generator on c9 today. Definitely it has been updated, but it's still working. It now installs more development dependencies and eats a lot more disk space, though. After cleaning some npm files in `/tmp` and running the server once, which creates the development database, I have less than 100MB of free space. With the old version I usually had nearly 300MB free.

What I did to run it:

1. Update npm: `npm install npm -g`. It throws some warnings, but works
2. Run step 11 from the waypoint *without* the last bit (without `&& yo angular-fullstack`)
3. Clean `/tmp` directory: `rm -rf /tmp/npm-*`
4. Run `yo angular-fullstack` and answered questions
5. Wait some minutes. The screen is filled with warnings and compiling output
6. Run command from step 28
7. Open new terminal and run command from step 29
8. Have fun

I also uninstalled some dependencies, like `karma-firefox-launcher` and `karma-chrome-launcher` which are not useful on c9.

**Comment by joshalling** [comment]
This still isn't working for me. I have tried about 10 separate time including all the ways shown in this thread https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2722. Every time I try cloud9 runs out of memory and kills my terminal midway through 'bower install & npm install'. When I run it again, I just get a bunch of dependency errors but it never finishes.

**Comment by atymchuk** [comment]
I tried and retried everything, including advices on the other threads related to the same thing - nothing worked. The errors vary depending on the version of node & npm, but the result is the same: you can't run `grunt serve` without errors. 

The issue has been outstanding for quite some time now, and some people just can't advance.

Question: can this be done on one's own virtual machine to fulfil the basejump?

**Comment by awesomeaniruddh** [comment]
Yep.

**Comment by awesomeaniruddh** [comment]
Yep.

**Comment by j4ckcyw** [comment]
nvm install 0.12 worked to solve the isAbsolute error for me. See this issue in yeoman: https://github.com/clnhll/guidetobasejumps/issues/2

**Comment by richchurcher** [comment]
Yeah there's some definite version mismatch here. Yeoman wants node >= 0.12.0, so does generator-angular-fullstack. Version installed with c9 is 0.10.35. A number of other minor packages within the stack want higher node versions too.

I've been experimenting with c9 after reading this... I don't use it for FCC development, but I can see why Windows users in particular might find it useful. I've managed to make it hit a memory limit during npm install at the end of angular-fullstack generation. Perhaps it's time to start deploying a custom build straight from Git without all the dependencies angular-fullstack installs but doesn't need?

**Comment by dannytpeck** [comment]
Glad to hear I'm not the only one having this issue! It consistently kills the npm process and displays "memory limit hit" every time during npm install.

**Comment by jbmartinez** [comment]
I ran out of luck, I cannot use the generator with the new version of npm. While I've been avoiding updating node, it is a must now. I like @richchurcher's idea, some dependencies are useless in c9 and others can be installed later in the development process

**Comment by BerkeleyTrue** [comment]
If you are running out of RAM try setting `npm config set jobs 1`. This forces npm to use only one download thread reducing the amount of RAM required for it to run at the cost of a slower download.

**Comment by dannytpeck** [comment]
That sounded like a solid plan, so I gave it a shot, but unfortunately Cloud 9 still kills it at around the same point in the process!

**Comment by smashzen** [comment]
Will this get fixed at some point? Are basejumps just on hold until this gets worked out?

**Comment by joshalling** [comment]
You can just do it locally. I gave up on getting it to work on Cloud9 after a few hours of frustration, then got it all set up locally on my Mac. I posted all of the Mac steps here if anyone is interested in that: http://joshalling.com/2015/09/18/get-set-for-local-basejumps/

**Comment by awesomeaniruddh** [comment]
Clementine JS should be ready soon. It will be the new recommendation and
*should* fix the issues with C9.

**Comment by richchurcher** [comment]
http://johnstonbl01.github.io/clementinejs/versions/fcc.html#about cool, that's great to hear there'll be something specific to FCC's needs.

**Comment by dannytpeck** [comment]
This looks fantastic! I use a lot of different computers for my work, so I really need something like C9. Any reason not to just go straight to using Clementine JS?

**Comment by tomtom87** [comment]
Hi guys, I'm trying to run the Waypoint: Get set for basejumps and I'm at the yo angular-fullstack command when it gives this output

```javascript
? What would you like to write tests with? Jasmine
You're using the fantastic NgComponent generator.

Initializing yo-rc.json configuration.


events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Object [object Object] has no method 'isAbsolute'
    at Generator.processDirectory (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/util.js:110:19)
    at Generator.generateProject (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/app/generator.js:399:14)
    at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/generator-angular-fullstack/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

What can I do?

**Comment by jbmartinez** [comment]
This is crazy, it seems that everyone is getting a different error. I guess that error is due to an unsupported node version, @tomtom87 . Try updating node with this commands, as stated in the first comment:

```
nvm install 0.12
nvm use 0.12
nvm alias default v0.12
```

If you get errors again, try updating npm:
```
npm install npm -g
```

And try again. Tell us if you get another error (I guess you will get it).

**Comment by atymchuk** [comment]
This is a rather disappointing experience for coders to run errors during setup. Not their job really. Event if you install the MEAN stack, as suggested by @joshalling, you still might run into trouble.
There should be a much simpler solution. A `docker container` (which I ultimately used after hours of fighting with c9.io) or a `vagrant box` comes to mind - there you are almost guaranteed not to run into issues. But, I'm afraid, not to many of us really use them.

**Comment by jbmartinez** [comment]
You can set up and use any environment you prefer, c9 and fullstack-angular generator are not requirement. C9 is convenient and used to work fine with fullstack-angular, though.

It would be helpful to have a wiki entry for the different options to setup the development environment, locally and on line.

**Comment by tomtom87** [comment]
@jbmartinez  your solution works - thank you very much!

**Comment by tomtom87** [comment]
Just a FYI - the yeoman fails and doesn't put bower on. Then the memory on the c9 also runs out.

**Comment by nalexiou** [comment]
I have tried to install the MEAN stack locally on my Mac (per @joshalling suggestion) and I am still running into issues when I run 
`bower install && npm install`

I get the following error: 

```
> node-pre-gyp install --fallback-to-build

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
...
...
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.

```

Do I need to install XCode? Been stuck on this for days now. Any assistance would be appreciated.

Thank you.
Nikolaos

**Comment by tomtom87** [comment]
Yes you need the xcodebuild tool available for the build to work it 
appears. Haven't done this myself yet but that is what the error 
surmises.. good luck on it hope xcode fixes it

On 29/09/2558 BE 22:22, Nikolaos Alexiou wrote:
>
> I have tried to install the MEAN stack locally on my Mac (per 
> @joshalling <https://github.com/joshalling> suggestion) and I am still 
> running into issues when I run
> |bower install && npm install|
>
> I get the following error:
>
> |> node-pre-gyp install --fallback-to-build xcode-select: error: tool 
> 'xcodebuild' requires Xcode, but active developer directory 
> '/Library/Developer/CommandLineTools' is a command line tools instance 
> xcode-select: error: tool 'xcodebuild' requires Xcode, but active 
> developer directory '/Library/Developer/CommandLineTools' is a command 
> line tools instance ... ... npm ERR! Failed at the v8-debug@0.4.6 
> install script 'node-pre-gyp install --fallback-to-build'. npm ERR! 
> This is most likely a problem with the v8-debug package, npm ERR! not 
> with npm itself. |
>
> Do I need to install XCode? Been stuck on this for days now. Any 
> assistance would be appreciated.
>
> Thank you.
> Nikolaos
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3146#issuecomment-144092800>.
>

-- 
--

Tom Whitbread
Gript.co.uk

**Comment by nalexiou** [comment]
@tomtom87 Ok. Had to upgrade to MacOS Mavericks to get xcode installed. Now, I am getting these errors:

```
> node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/debug/src/debug.o
In file included from ../src/debug.cc:2:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
...
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.
```

Any clue what else I need to do?

**Comment by JordiCruells** [comment]
In my case, at step 27, before running bower install, don't know why bower had not been installed so I needed to manually run npm install -g bower

**Comment by nalexiou** [comment]
Sorry for the continuous comments..

I installed bower, node-gyp, and node-pre-gyp. I am still getting these errors for` npm install`:

```
9 errors generated.
make: *** [Release/obj.target/bson/ext/bson.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/basejumps/node_modules/bson-ext/build/Release/bson.node" "--module_name=bson" "--module_path=/usr/local/lib/node_modules/basejumps/node_modules/bson-ext/build/Release"
gyp ERR! cwd /usr/local/lib/node_modules/basejumps/node_modules/bson-ext
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/4.1.1/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/basejumps/node_modules/bson-ext/build/Release/bson.node --module_name=bson --module_path=/usr/local/lib/node_modules/basejumps/node_modules/bson-ext/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/basejumps/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/lib/node_modules/basejumps/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/basejumps/node_modules/bson-ext
node-pre-gyp ERR! node -v v4.1.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/4.1.1/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/basejumps/node_modules/bson-ext/build/Release/bson.node --module_name=bson --module_path=/usr/local/lib/node_modules/basejumps/node_modules/bson-ext/build/Release' (1)
  CXX(target) Release/obj.target/bson/ext/bson.o

> kerberos@0.0.14 install /usr/local/lib/node_modules/basejumps/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/kerberos.node
/usr/local/lib
└── basejumps@0.0.0 
```

**Comment by anjanjanj** [comment]
nalexiou, I believe this is because you're running node 4. The generator only seems to work with 0.12:
```
brew unlink node
brew install node012
```
You might need to install yeoman, generator-angular-fullstack etc. again in npm, and you should be good to go.

**Comment by nalexiou** [comment]
@anjanjanj thanks for your suggestion. I actually decided to run the next steps (despite the errors) with node 4 and `grunt serve` run successfully bringing up the Angular site.

```
$ grunt serve
Running "serve" task

Running "clean:server" (clean) task

Running "env:all" (env) task

Running "concurrent:server" (concurrent) task

Running "injector:scripts" (injector) task
Missing option `template`, using `dest` as template instead
Injecting js files (13 files)

Running "injector:css" (injector) task
Missing option `template`, using `dest` as template instead
Injecting css files (5 files)

Running "wiredep:target" (wiredep) task
client/index.html modified.

Running "autoprefixer:dist" (autoprefixer) task

Running "express:dev" (express) task
Starting background Express server
Debugger listening on port 5858
Express server listening on 9000, in development mode

Running "wait" task
>> Waiting for server reload...
finished populating users
Done waiting!

Running "open:server" (open) task

Running "watch" task
Waiting...
GET /api/things 200 29ms
```
Do the above messages look acceptable, or should I still switch to node 0.12?

**Comment by tomtom87** [comment]
@nalexiou  got further then me man nice! Looking good. Hope I can get it working today

**Comment by anjanjanj** [comment]
@nalexiou Looks ok! Maybe test the Heroku deployment now to be completely sure. Just incase you get the whole project coded then end up being unable to deploy it!

**Comment by nalexiou** [comment]
@tomtom87 Thanks! Maybe I just got lucky!! Good luck to you! Hope it works out for you as well.
@anjanjanj  Thanks again. Yes, Heroku is next on my list for tomorrow - drained for today.

**Comment by nalexiou** [comment]
Just wanted to give an update on the status of my configuration. When I did try to push to Heroku, it didn't work. So, following @anjanjanj suggestion, I downgraded my node version and went through the steps again. I finally got it to work and push to Heroku! Thank you!

**Comment by nalexiou** [comment]
Hi everyone...again! Sorry to be adding to this page. My Heroku side is up but MongoDB is missing the collection. Here's my site: https://basejumps-na.herokuapp.com As you see, there is nothing listed under Features but when I run this locally, I do. MongoLab in under my Resources in Heroku but when I go into it there are no collections listed. How do I migrate my local dataset to Heroku?

**Comment by harshitanand** [comment]
just start a new workspace and in the terminal check node version using "node -v"
after that go through following steps for successful env setup

source ../.nvm/nvm.sh
nvm install v0.12.7
nvm use v0.12.7

after that use following command

echo "export NODE_PATH=$NODE_PATH:/home/ubuntu/.nvm/v0.12.7/lib/node_modules" >> ~/.bashrc && source ~/.bashrc

then type

rm -rf * && npm install -g yo grunt grunt-cli generator-angular-fullstack && yo angular-fullstack

it will give you an error try following again

yo angular-fullstack

once it is successful try following comands

npm install -g bower
bower install
npm install

then install mongodb using

mkdir data && echo 'mongod --bind_ip=$IP --dbpath=data --nojournal --rest "$@"' > mongod && chmod a+x mongod && ./mongod

then try running following in another terminal

grunt serve

I have tested above method many times and it works

**Comment by awesomeaniruddh** [comment]
I'm closing this because we have moved to Clementine, which should have fixed most of these issues. If anyone is facing any config issues with Clementine, please open a new issue. Thanks!
