### ISSUE TITLE
mispelling

### ISSUE THREAD

**Issue by activechild** [FreeCodeCamp/FreeCodeCamp#3149]
Challenge http://freecodecamp.com/challenges/bonfire-falsey-bouncer has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

you spelled falsy wrong. you have it spelled falsey

**Comment by bugron** [comment]
@activechild thanks for posting this issue!
I actually can't find the word "falsy" in that page. Would you mind to provide more info/screenshot, please? Thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by natac13** [comment]
I think he meant the other way around (https://www.andrewzammit.com/blog/falsy-vs-falsey-im-making-the-call/) I can do this as I need screen shot for a blog post on a step by step guide on doing this kind of stuff
