### ISSUE TITLE
map doesn't show check mark

### ISSUE THREAD

**Issue by mmcconchie** [FreeCodeCamp/FreeCodeCamp#3151]
Challenge http://www.freecodecamp.com/challenges/waypoint-give-a-background-color-to-a-div-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When I run the test, It shows that I've done the task correctly, but it won't show in the map that I've completed the waypoint.

**Comment by arya45** [comment]
It could be because at the moment, you need to click on "run tests" twice before your challenge is validated.
See thread #2772

**Comment by benschenker** [comment]
Closing as a duplicate.  Please reopen if this issue has not been resolved for you.
