### ISSUE TITLE
Usability issue Waypoint: Use Conditional Logic with IfElse Statements

### ISSUE THREAD

**Issue by jedpimentel** [FreeCodeCamp/FreeCodeCamp#3152]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-conditional-logic-with-ifelse-statements has an issue.

the "code space" where students are meant to put their if/else code contains (by default) a closing bracket which is part of the test code and shouldn't be edited/removed:
<a href="http://s213.photobucket.com/user/ramboman88/media/Untitled.png.html" target="_blank"><img src="http://i213.photobucket.com/albums/cc69/ramboman88/Untitled.png" border="0" alt=" photo Untitled.png"/></a>
I think this closing bracket should be moved under the ```// Only change code above this line.``` comment to avoid students using it inside their if/else statement (and breaking the function). (someone was stuck on this earlier today)

**Comment by ahstro** [comment]
Thank you for reporting! :)
