### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by wsroberts** [FreeCodeCamp/FreeCodeCamp#3156]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

For this problem, I used the following code:
```html
<script type="text/javascript">
$(document).ready(function(){
});</script>
```
The last 3 learning 'goals' will show checked and complete, but the first one: "Create a script element" will not for some reason. Not sure why. Thanks for your time

williamroberts643@hotmail.com

**Comment by awesomeaniruddh** [comment]
The test check for `<script>`, not `<script type="text/javascript">` using regex. Hence, the test fails.

Removing `type="text/javascript"` will allow the code to pass.

If this helped, please close the issue :)

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!
