### ISSUE TITLE
No next or error button.

### ISSUE THREAD

**Issue by ux4u** [FreeCodeCamp/FreeCodeCamp#3157]
Challenge http://www.freecodecamp.com/challenges/waypoint-iterate-with-javascript-for-loops has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

To my best knowledge, i didn't create an infinite loop.  I can't get a prompt that I've made an error or to go to the next screen or that I am correct.  

![image](https://cloud.githubusercontent.com/assets/10198376/9727630/9c039c7c-55b5-11e5-9a51-0470d5833934.png)

**Comment by ux4u** [comment]
I successfully completed the While Loops doing exactly the same thing and received a prompt to get to the next screen showing a completion.  I'm pretty sure it's a bug.  I has experience in loops from C++ and it's exactly the same

**Comment by awesomeaniruddh** [comment]
Hmm, it is working fine for me.
Do you have any errors in the console (press F12 and click on `Console`)

**Comment by AEA2002** [comment]
@ux4u
In your for loop, you wrote:
```
1 < 5
```
instead of 
```
i < 5
```

**Comment by ux4u** [comment]
uhhg, sorry, everyday is a new ahah moment in life and code.

On Tue, Sep 8, 2015 at 12:39 PM, AEA2002 <notifications@github.com> wrote:

> @ux4u <https://github.com/ux4u>
> In your for loop, you wrote:
>
> 1 < 5
>
> instead of
>
> i < 5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3157#issuecomment-138678861>
> .
>



-- 
Sincerely,

A Peterson

**Comment by bugron** [comment]
@ux4u thanks for posting this issue!
Feel free to close this issue if your problem is solved, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
