### ISSUE TITLE
Followed the rules...exactly. Seems like this should of worked.

### ISSUE THREAD

**Issue by edson1115** [FreeCodeCamp/FreeCodeCamp#3158]
Challenge http://freecodecamp.com/challenges/waypoint-use-the-bootstrap-grid-to-put-elements-side-by-side has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!
