### ISSUE TITLE
Issue within nesting anchor within paragraph

### ISSUE THREAD

**Issue by Naveedy** [FreeCodeCamp/FreeCodeCamp#3159]
Challenge http://freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

see code below. it is correct. but the run test option is still showing error.

<p>click here for <a href="http://freecatphotoapp.com">cat photos</a></p>
![image](https://cloud.githubusercontent.com/assets/14126677/9727925/a04ad4fe-561d-11e5-915a-bd05dc51d0a3.png)

**Comment by Naveedy** [comment]
resolved. understood now. the message was incorrect. it was Existing anchor to be nested within new p

**Comment by moxilla3** [comment]
Not working for me either

**Comment by djdrysdale** [comment]
I am also having this issue. The wording is not clear. They want you to create a paragraph around the existing anchor, not create a new anchor with a paragraph around it.

**Comment by Naveedy** [comment]
check the code again. 
there is already a anchor element in the code which is above the img element.
what the program has done that it has moved your line of code in the previous lession above.
so when you try to create a new <p> with <a> it gives the error.
