### ISSUE TITLE
Have to submit three or four times after completing before going on to next

### ISSUE THREAD

**Issue by crowesam** [FreeCodeCamp/FreeCodeCamp#3160]
Challenge http://freecodecamp.com/challenges/waypoint-add-two-numbers-with-javascript has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When completing the exercise on this and previous several Waypoints one must submit several times (two or three at least) before it advances to next way point.

**Comment by bugron** [comment]
@crowesam thanks for posting this issue!
Note that your issue is related to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2772 and this issue seem global so I'm closing this issue. You can continue further discussion there, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by crowesam** [comment]
Glad to help. I think it may be intermittent fromone excercise ot the next
based on whether the submit is done using the "ctrl + return" method on the
keyboard vs click with the mouse. I tried both and a waypoint  after the
one I reported this on took five tries to go through and I was alternating
with the keyboard and mouse. Hope that helps.

On Tue, Sep 8, 2015 at 12:54 PM, Arsen Melikyan <notifications@github.com>
wrote:

> @crowesam <https://github.com/crowesam> thanks for posting this issue!
> Note that your issue is related to #2772
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2772> and this issue
> seem global so I'm closing this issue. You can continue further discussion
> there, thanks.
>
> ------------------------------
>
> Please review the *Guidelines for Contributing*
> <https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md>,
> thank you!.
> ------------------------------
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3160#issuecomment-138632047>
> .
>



-- 
Best Regards,

Sam Crowe
President/Designer/Developer
The Creative Crowe, LLC
P.  804-596-0692
M. 804-721-7032
E.  sam@thecreativecrowe.com
