### ISSUE TITLE
Waypoint: Change the Font Size of an Element

### ISSUE THREAD

**Issue by StudioSwift** [FreeCodeCamp/FreeCodeCamp#3161]
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue.

I think I've completed the challenge correctly, but the system does not recognize it?
![p](https://cloud.githubusercontent.com/assets/6464047/9730722/413007b4-55cd-11e5-8ba2-1ca11a8fe604.png)

**Comment by awesomeaniruddh** [comment]
Your code looks alright to me too. Are you sure you clicked the "Run tests" button?

**Comment by StudioSwift** [comment]
yes, several times. i'd skipped this challenge and continued with the rest..

**Comment by awesomeaniruddh** [comment]
Okay, any errors in the Console?

**Comment by StudioSwift** [comment]
no. i reset and typed the answer again still didnt work.

**Comment by benschenker** [comment]
@StudioSwift have you tried this in incognito mode? Or have you done a [Hard Reset](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache)?

**Comment by StudioSwift** [comment]
Incognito, cleared browser cached.  Problem exists. Probably a BUG?

**Comment by awesomeaniruddh** [comment]
Would you be up for a ScreenHero session to figure this out?

**Comment by bugron** [comment]
@StudioSwift thanks for posting this issue!
I can't reproduce this issue and I'm able to pass that test with your code. Try to [Refresh Your Browser Cache](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache) and [Clear Your Browser's Local Storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser%27s-Local-Storage).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by StudioSwift** [comment]
@awesomeaniruddh thanks for your offer to help.  I'd completed all the other challenges and moved on to Javascript, so I'll just let this one go.

**Comment by Rozelin** [comment]
for ghost : you should  code like this:
.red-text {
color:red;
font-size:16px;
}
and than add class .red-text to the "p" tag.
Good luck! ))))
