### ISSUE TITLE
Not saving progress for OO and FP Section

### ISSUE THREAD

**Issue by StephenMayeux** [FreeCodeCamp/FreeCodeCamp#3162]
Challenge http://freecodecamp.com/challenges/waypoint-declare-javascript-objects-as-variables has an issue. 

I completed a challenge in the Object Oriented and Functional Programming section. I wrote my code, ran the tests, and it passed all three tests (screenshot shared here). I didn't get the usual congratulatory pop-up message to continue to the next challenge. In addition, when I clicked map, my progress wasn't saved. I've repeated the same exercise several times in different browsers and also cleared my cache, but to no avail. 

![fccissue](https://cloud.githubusercontent.com/assets/13535545/9730824/105195b8-5654-11e5-88ba-6c4bc5d5f639.png)

**Comment by arya45** [comment]
Hi,
It is a confirmed issue that you have to click twice on "run tests" (or twice Ctrl+Enter), several issue logs have been created already. #2772 

So you might want to close this issue and follow the discussion on the other thread (all the raised issues concerning this topic will anyway be closed by the admin and referenced to that one)

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!
