### ISSUE TITLE
WayPoint asks for #target1 but the Test asks for left-well

### ISSUE THREAD

**Issue by ccakinsfcc** [FreeCodeCamp/FreeCodeCamp#3165]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-the-parent-of-an-element-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

WayPoint
Give the parent of the<b> #target1 </b> element a background-color of red.

Run Test
Your <b>left-well</b> element should have a red background.

**Comment by bugron** [comment]
@ccakinsfcc thanks for posting this issue!
WayPoint
Give **the parent** of the **#target1** element a background-color of red.

Run Test
Your **left-well** element should have a red background.

So the parent of **#target1** actually is **left-well**. 

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
