### ISSUE TITLE
Waypoint Criteria Don't Appear

### ISSUE THREAD

**Issue by nickpalmer789** [FreeCodeCamp/FreeCodeCamp#3166]
On some of the waypoints you cannot see the criteria for completion until you attempt to run the tests. After that you can see the criteria with their associated checkmarks and Xs. This can be replicated at this waypoint. 
http://freecodecamp.com/challenges/waypoint-clone-an-element-using-jquery

**Comment by bugron** [comment]
@nickpalmer789 thanks for posting this issue!
We are aware of this issue and it is related to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2717. I'll close this issue, thanks for reporting.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
