### ISSUE TITLE
Minor issue - error 404

### ISSUE THREAD

**Issue by CandiW** [FreeCodeCamp/FreeCodeCamp#3167]
Hi - logged in today to get started with some projects and upon the Map page load, an error appeared at the top of the page that said:

```404: We couldn't find path /dribbble-websites.jpg```

I refreshed the page and it went away....but thought I would post here in case there was an issue.

Thanks and keep up the good work :)

**Comment by CandiW** [comment]
I forgot to mention that the page seemed to load properly....everything was there and when I refreshed the error disappeared....

**Comment by BerkeleyTrue** [comment]
I don't think this is related to us as we do not have such a file associated with the map page (or any page other then maybe /news). This might have been left over from a previous site you where on.

Happy coding!
