### ISSUE TITLE
Bonfire: Mutations does not understand Sets.

### ISSUE THREAD

**Issue by sandsong** [FreeCodeCamp/FreeCodeCamp#3168]
Webpage does not understand Sets, returning only an empty set.

e.g.

```javascript
function mutation(arr) {
  var testSet = new Set(); testSet.add(1);
  return testSet;
}
```

returns `{}`

**Comment by BerkeleyTrue** [comment]
We currently have no way of supporting es6 collections. They are either supported or not depending on your browser. Also, you cannot simply console.log an es6 collection as it will just print an empty object (which is the default behavior).

Please stick to es5 and plain Array's for the time being.

Happy Coding!
