### ISSUE TITLE
. instead of ...

### ISSUE THREAD

**Issue by thomasvaeth** [FreeCodeCamp/FreeCodeCamp#3169]
Challenge http://www.freecodecamp.com/challenges/waypoint-sift-through-text-with-regular-expressions has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

<img width="1440" alt="screen shot 2015-09-08 at 1 35 24 pm" src="https://cloud.githubusercontent.com/assets/10190995/9746749/8c75cc02-562e-11e5-844e-aa5c59a7b59b.png">

Directions:
We can do this by replacing the ... part of our regular expression with the current regular expression with the word and.
Image:
Only has . and not ...

**Comment by bugron** [comment]
@thomasvaeth thanks for pointing this out!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
