### ISSUE TITLE
wrong test text

### ISSUE THREAD

**Issue by arya45** [FreeCodeCamp/FreeCodeCamp#3172]
Challenge http://freecodecamp.com/challenges/waypoint-declare-javascript-objects-as-variables has an issue.

![image](https://cloud.githubusercontent.com/assets/13393572/9747977/310dadc6-5679-11e5-9160-d10c57c2cba4.png)

The tests should read:
    ... 'motorbike should have a "engines" attribute set to a number.'
    ... 'motorbike should have a "wheels" attribute set to a number.'
    ... 'motorbike should have a "seats" attribute set to a number.'

**Comment by benschenker** [comment]
Thanks for posting this @arya45!

This should be a simple fix.  Feel free to [submit a pull request](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute).
