### ISSUE TITLE
Bonfires not saving after "Repeat a String repeat a string"

### ISSUE THREAD

**Issue by ninjatc** [FreeCodeCamp/FreeCodeCamp#3173]
I noticed my Bonfires have stopped saving my work after Basic Algorithms #9 

Challenge http://freecodecamp.com/challenges/bonfire-repeat-a-string-repeat-a-string has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by BerkeleyTrue** [comment]
Closing as duplicate of #2894

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!
