### ISSUE TITLE
Error in instructions

### ISSUE THREAD

**Issue by chrisdziewa** [FreeCodeCamp/FreeCodeCamp#3175]
Challenge http://www.freecodecamp.com/challenges/waypoint-headline-with-the-h2-element has an issue. It says to create an h2 element that says "CatPhotoApp" but the test wants it to say "Cat Photo App".

**Comment by awesomeaniruddh** [comment]
Uh, no? 'CatPhotoApp' without the spaces passes the test? The spaces are optional in the waypoint.

I believe that solves the issue. If it does, please close it :)

**Comment by chrisdziewa** [comment]
Yes, it seems to be working now. Must be a browser glitch. I noticed before it was taking two clicks to pass everything as well.

**Comment by awesomeaniruddh** [comment]
@chrisdziewa The first-click validates your code and the second click goes to the next challenge. That is by design, but there is an issue regarding that if you'd like to voice your concerns :)

**Comment by chrisdziewa** [comment]
I mean that it was taking two clicks just to pop up the window that I had passed and a third click to submit it. I started a few months after FCC was created and the submission process is still basically the same. Just a glitch I'm sure, and an isolated case at that ha.
