### ISSUE TITLE
symmetric-difference Bonfire

### ISSUE THREAD

**Issue by srpanall** [FreeCodeCamp/FreeCodeCamp#3176]
The final functionality test of the sym function is based on a condition that should never occur. You can't find the symmetric difference of 1 set of items. This is called out in your statement of conditions as well as the mathematical definition of symmetric difference you linked to. If a program does return the value specified, it contains a bug. The correct program should probably output a string when only one set is passed. stating something along the lines of "The symmetric difference of one set cannot be found." 

The expected value of the function for sym([1,1]) would be the symmetric difference of [1,1] and []. But, that doesn't make sense. This would be the same as asking for a function that returns the product of at least 2 numbers and returning 0 if only one value is entered. e.g. product(2,3)=6 but product(2)=0.

Challenge http://www.freecodecamp.com/challenges/bonfire-symmetric-difference has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by srpanall** [comment]
![symdiffcapture](https://cloud.githubusercontent.com/assets/13695349/9749083/b878d546-5657-11e5-8f19-8d4987018aea.PNG)
![symdiffcapture2](https://cloud.githubusercontent.com/assets/13695349/9749084/b87b2e72-5657-11e5-8abc-aea3255315f5.PNG)

**Comment by benschenker** [comment]
Thanks @srpanall for pointing this out!

It also says that the function only takes 2 arrays and then tests with three....

**Comment by bugron** [comment]
Closing this issue as the changes from https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3362 are pulled in by this commit: https://github.com/FreeCodeCamp/FreeCodeCamp/commit/d5ddb10b7a3526059408510a660fbf1067571f49.
