### ISSUE TITLE
[BUG/TYPO]: Tests failing on Portfolio Project because of typo/class name change.

### ISSUE THREAD

**Issue by vipatron** [freeCodeCamp/freeCodeCamp#31785]
**Describe your problem and how to reproduce it:**
I am running the new test suite on a portfolio project I created for the Beta, which passed 12/12 tests then, but only passes 11/12 now. The issue is that the `<section id="projects">` (user story 3) is supposed to contain "at least one element with a class of **project-tile**" (user story 4). All the project `<figure>`s in [my portfolio project - forgive the broken links, need a new webhost](https://codepen.io/vipatron/pen/ZxeJmq?editors=1010) are classed `.project-tile` because that is what the instructions on that challenge were previously and are currently. The test suite is giving me an error because it is looking for elements whose class is **.project-title**. I believe this is just a typo that entered the test suite. Since the public-facing challenge still says "tile", not "title", and it makes semantic sense, I propose we change it back to ".project-tile" in the two places in the testing suite.

**Add a Link to the page with the problem:**
Challenge for the project: [build a personal portfolio webpage](https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage/)

New test suite: [v1/bundle.js]( https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js)

Problematic Line of code to use as search string, followed by relevant testing function code:
Search (".project-title")
```
function(){o.assert.isNotNull(document.getElementById("projects"))}),it('The projects section should contain at least one element\n      with a class of "project-title" to hold a project.',function(){o.assert.isAbove(document.querySelectorAll("#projects .project-title").length,0)})
```

**Tell us about your browser and operating system:**
* Browser Name: Firefox Quantum
* Browser Version: 63.0
* Operating System: Windows 10, 64-bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/36994955/47657071-c3a02680-db66-11e8-9b56-35c531e2e187.png)

**Comment by RandellDawson** [comment]
@tbushman Has this been resolved?  Has this been reported on the other repo?

**Comment by tbushman** [comment]
@RandellDawson There was some confusion at the time, but the test uses `.project-tile` now.  
@vipatron Let me know if you're still having an issue.

**Comment by moT01** [comment]
I tested your project and this issue appears to have been fixed. Therefore, I think this can be closed. Let us know if you are still have problems. Thanks and happy coding!
