### ISSUE TITLE
Feature Suggestion: Learning by spaced repetition

### ISSUE THREAD

**Issue by NTPfun** [FreeCodeCamp/FreeCodeCamp#3180]
Thanks to Dr. Ebbinghaus, psychology knows about the spacing effect, a phenomenon whereby humans more easily remember or learn items when they are studied a few times spaced over a long time span rather than repeatedly studied in a short span of time. 

As a beginner in Free Code Camp, I have noticed that the site currently has no feature that involves learning by spaced repetition, and thus I have come here in hopes that we can implement a similar feature to the one used by the Anki program, easily found in Ankisrs.net. 

They use a flashcard system with a question in front, and one in the back, spacing the repetition according to one's proficiency in the subject matter. I am currently designing some basic flashcards for Anki to use, based on questions and answers, to help myself learn html better, but it would be cool to have something like that to be able to review in case you haven't been on site for some time on FCC. 

Some links if you feel like reading more about spaced repetition:

http://www.gwern.net/Spaced%20repetition

http://archive.wired.com/medtech/health/magazine/16-05/ff_wozniak?currentPage=all

http://lifeinthefastlane.com/learning-by-spaced-repetition/

![image](https://cloud.githubusercontent.com/assets/14183493/9750108/229c67c0-5659-11e5-85be-6be2e93199fd.png)

![image](https://cloud.githubusercontent.com/assets/14183493/9750119/576c2e72-5659-11e5-929f-28650b14976b.png)

**Comment by jwjb** [comment]
@NTPfun We have chatted privately on this and I think this is a great suggestion. As a bare minimum it would be great if FCC kept our responses in our account like other sites such as CodeAcademy, Udacity, etc.

**Comment by QuincyLarson** [comment]
@NTPfun @jwjb I'm familiar with Spaced repetition, but am unsure of how relevant it is when applied to skills (coding), rather than bodies of knowledge (foreign language vocabulary).

We do store every solution to every challenge you complete on Free Code Camp, and may make these publicly accessible through our API in the coming months. So you could potentially create a 3rd party spaced repetition app around these data.

We'll keep you all posted on the development of our public API.

**Comment by jwjb** [comment]
@QuincyLarson Awesome news that all of our solutions are kept where it would be great to have access to them at some point.

Having our solution for each challenge available would really make it easier for review much like what is possible with CodeAcademy, Udacity and other sites where a user can come back later to refresh their memory on a certain concept that might have taken many challenge steps to build without having to redo these challenges from the start just to be able to see the end result.

In the interim, I am recreating a personal 'Free Code Camp' Evernote stack with the solution for each challenge including the code, output, assert tests, etc to use for my review like in the screenshot below.

![screen shot 2015-09-15 at 1 29 42 pm](https://cloud.githubusercontent.com/assets/3523591/9889402/20802e44-5baf-11e5-837f-bf8470e95c61.png)

Kudos for building 'Free Code Camp' which is such an awesome open source community which I am so thankful to have recently stumbled upon which really makes learning to code an enjoyable and effective experience like no other and I hope to see you around at the AWS Pop-up Loft.

**Comment by studenton** [comment]
@jwjb Can you share your flashcards?

**Comment by jwjb** [comment]
@studenton Sorry for the late response as I did not get a notification, but as you probably know this is a moot point now that all of our solutions are available making these flashcards dated.
