### ISSUE TITLE
Cannot read property 'length' of null - #22 Waypoint: Nest an Anchor Element within a Paragraph

### ISSUE THREAD

**Issue by gzpaitch** [FreeCodeCamp/FreeCodeCamp#3186]
Hello, 

Something is going wrong and I can't move forward on challenge #22 Waypoint: Nest an Anchor Element within a Paragraph.

The name of the problem that is holding me is "Cannot read property 'length' of null". All other requisites are right (green check mark). 

This is my code: 
-----------------------------------
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }

</style>

<h2 class="red-text">CatPhotoApp</h2>
<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">
<p>
  Hey! <a href="http://www.freecatphotoapp.com">Click here for</a> go to the website.
</p>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>
```
-------------------------

Please let me know what I need to change because I really want to move on but this issue is being very annoying.

Thank you guys!

Challenge http://freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph

**Comment by gzpaitch** [comment]
Ouch.. Seems that something went wrong in my post. How can I post the code without do that?

**Comment by awesomeaniruddh** [comment]
I fixed the code ^
Can you please post a screenshot? Seems to be an issue with FCC

**Comment by gzpaitch** [comment]
![code](https://cloud.githubusercontent.com/assets/13314191/9753999/37d0b6f8-5692-11e5-9f82-23ff2abf13bf.jpg)


Thank you for you fast response! That's awesome!

**Comment by awesomeaniruddh** [comment]
Not just of the code, the entire window please, especially where it says "Cannot read property 'length' of null".

**Comment by gzpaitch** [comment]
![code](https://cloud.githubusercontent.com/assets/13314191/9754053/f813ba6e-5692-11e5-8d09-22142a07c115.jpg)

I fixed the link (http://freecatphotoapp.com) and now there is another problem.

**Comment by awesomeaniruddh** [comment]
Can you edit the text inside your `a` tags to say "cat photos"? Without the quotes. If the `length` problem persists, then try clearing your cache and reopening the browser.

**Comment by gzpaitch** [comment]
Did not work. I will clear my cache then I let you know!

Thanks!

**Comment by gzpaitch** [comment]
I cleaned and still not working. 

Actually, I didn't uderstand what you mean with: 

"Can you edit the text inside your a tags to say "cat photos"? Without the quotes."

What I tried was write without quotes as well with (" ") and (' ').

**Comment by awesomeaniruddh** [comment]
Delete the code from line 32-34 and instead paste this in:
`<p>click here for<a href="http://www.freecatphotoapp.com">cat photos</a></p>`

**Comment by awesomeaniruddh** [comment]
Also

**Comment by gzpaitch** [comment]
"Keep calm and code on!"

YOU ARE THE BEST!

Thank you for your amazing help! 

I wish you the best my friend!

Regards, 
Gustavo
