### ISSUE TITLE
Failing test of waypoint results in 'Cannot read property 'length' of null' error

### ISSUE THREAD

**Issue by awesomeaniruddh** [FreeCodeCamp/FreeCodeCamp#3188]
Waypoint link: http://freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph

If you fail the second test of the waypoint, that is the text inside the `anchor` element is not 'cat photos', the test throws an `Cannot read property 'length' of null` error.

![screenshot 3](https://cloud.githubusercontent.com/assets/5279150/9754535/bd6aed6e-56fc-11e5-8131-c33b200ea774.png)

If the test is passed, then it behaves as expected.

**Comment by bugron** [comment]
@awesomeaniruddh a quick fix of this is removing `.length > 0` from line [1140](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/html5-and-css.json#L1140).

**Comment by awesomeaniruddh** [comment]
Yep, that should fix it
