### ISSUE TITLE
it's not working for me HTML & CSS 18

### ISSUE THREAD

**Issue by OsamaNoori** [FreeCodeCamp/FreeCodeCamp#3192]

**Comment by bugron** [comment]
@OsamaNoori thanks for posting this issue!
Please, provide the description of your issue/code/screenshot, thanks!
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
