### ISSUE TITLE
design problem

### ISSUE THREAD

**Issue by rigox** [FreeCodeCamp/FreeCodeCamp#3193]
Challenge http://freecodecamp.com/challenges/waypoint-responsively-style-checkboxes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

okay the col-xs-4 should be col-xs-3 because the word loving goes down, i think it will fit in a different screen size but for the example it looks ugly

**Comment by benschenker** [comment]
Hey @rigox thanks for posting!

I am unable to reproduce this.  It looks fine for me with the following code:
```
<div class="row">
    <div class="col-xs-4">
        <label><input type="checkbox" name="personality">Loving</label>
    </div>
    <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Lazy</label>
    </div>
    <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Crazy</label>
    </div>
</div>
```
And it looks like:


<img width="338" alt="loving" src="https://cloud.githubusercontent.com/assets/2434612/9778905/f5bfd51e-573b-11e5-8d5a-fd7be797388e.png">

Does it look different for you?

**Comment by feedthebob** [comment]
Try putting a space between the input tag and "Loving" and this is what happens 
![capture2](https://cloud.githubusercontent.com/assets/13381437/10774296/fd0fee10-7d08-11e5-81e7-3cd6d2b1dc8b.JPG)
