### ISSUE TITLE
Challenge completed?

### ISSUE THREAD

**Issue by katredmond** [FreeCodeCamp/FreeCodeCamp#3197]
Challenge http://freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I think I have completed a challenge although it says my h2 element should be red - it is red and I think the coding is correct.. screen print attached. 

![capture](https://cloud.githubusercontent.com/assets/14172438/9767726/7c907fc0-56d4-11e5-8608-0eedb0f6a5e2.JPG)

**Comment by bugron** [comment]
@katredmond thanks for posting this issue!
[Here is the solution](http://prntscr.com/8efjho).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
