### ISSUE TITLE
Just add the <div class="container-fluid"></div> and run it

### ISSUE THREAD

**Issue by kostisJP** [FreeCodeCamp/FreeCodeCamp#3198]
Challenge http://freecodecamp.com/challenges/waypoint-house-our-page-within-a-bootstrap-container-fluid-div has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by kostisJP** [comment]
A reset fixed the issue. Sorry for any inconvenience.

**Comment by benschenker** [comment]
No problem @kostisJP!

Take a look at the [Bug Posting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug) for the future.  Resetting is the first recommended step :smile:
