### ISSUE TITLE
Twitter requests permission each time user authenticates

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/freecodecamp#32]
@figitalboy originally reported: Each time I log in with Twitter, I still have to authorize the app to allow FCC access to my profile.

**Comment by terakilobyte** [comment]
PR #33 resolves this issue successfully.

**Comment by figitalboy** [comment]
Twitter API documentation for GET oauth/authenticate distinguishes the difference between authorize and authenticate in paragraph four [here](https://dev.twitter.com/oauth/reference/get/oauth/authenticate).

**Comment by ESOComputing** [comment]
I believe this is still an issue. I've already authorized FCC to interact with my twitter account, yet every time  I attempt sign-in with twitter it still wants permission to authorize account interaction. Rather than just logging in.

**Comment by terakilobyte** [comment]
Angelica,

The pull request hasn't been merged into the main branch and pushed live to
the servers. As soon as the team has a chance to review my changes we'll
get it going live for you to enjoy the ease of use!
