### ISSUE TITLE
Lesson was already completed

### ISSUE THREAD

**Issue by glk101** [FreeCodeCamp/FreeCodeCamp#3200]
Challenge http://www.freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

I got to this lesson, Waypoint: Change the Font Size of an Element, and it was already completed for me.  The previous lesson was also completed as well when I got to it, too.  I'm not sure if it was something I did the first time, but since it's happened twice now, I don't think it's something I'm doing.  Hitting the reset button did reset the code, at least.  I'll go back and redo the previous lesson, so I'll have done it at least once.  Thanks.

**Comment by AkiraLaine** [comment]
@glk101 Hey! If the Waypoint's are already completed, it means you already did them :D

**Comment by awesomeaniruddh** [comment]
@AkiraLaine I think he meant that he didn't complete the waypoints, yet they were marked as completed for him.

@glk101 Please check the map to see if their are any other waypoints/challenges that are marked complete for you?

**Comment by AkiraLaine** [comment]
@awesomeaniruddh Maybe. But it's more likely that he already did them before.

**Comment by awesomeaniruddh** [comment]
>I'll have done it at least once

^ That suggests that he didn't do the waypoints :)
