### ISSUE TITLE
Sample text on the right is there twice...

### ISSUE THREAD

**Issue by glk101** [FreeCodeCamp/FreeCodeCamp#3201]
![firefox_screenshot_2015-09-09t17-38-50 565z](https://cloud.githubusercontent.com/assets/14199479/9769438/d0b499ea-56ef-11e5-8260-a057c9d726e5.png)
Challenge http://www.freecodecamp.com/challenges/waypoint-override-styles-in-subsequent-css has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

When I loaded the page for this lesson, the 'Hello World" text on the right side of the screen is displayed twice for some reason.  If I reset the page, or even start editing the code, the second copy of the text disappears.  It's more of a weird error than a bug, but I thought I'd report it since I took a screenshot of it.

**Comment by glk101** [comment]
![firefox_screenshot_2015-09-09t17-45-05 129z](https://cloud.githubusercontent.com/assets/14199479/9769616/cfa29948-56f0-11e5-9043-9b29e249cfa6.png)

I also had the same thing happen on the next lesson, as well.  Here's another screenshot, in case it helps someone figure out how I broke it, lol.

**Comment by benschenker** [comment]
Hey @glk101 thanks for posting this!

I've seen other people complain about this same issue (see #2706 and #3194).  Does it help to try the same lesson in incognito mode?

**Comment by BerkeleyTrue** [comment]
Closing as duplicate

Please see https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Searching-for-Your-Issue-on-Github

Happy Coding!
