### ISSUE TITLE
Waypoint: Create a Bulleted Unordered List

### ISSUE THREAD

**Issue by jenvyn** [FreeCodeCamp/FreeCodeCamp#3202]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list has an issue. 

"Make sure your li element has a closing tag." 

All elements in screenshot have closing tag. Does not recognize. 
<img width="1280" alt="screen shot 2015-09-09 at 3 17 22 pm" src="https://cloud.githubusercontent.com/assets/14183463/9771725/effb5f12-5705-11e5-81e0-3845180e6e0d.png">

**Comment by suhussai** [comment]
For some reason if you replace this:

    <li class="red-text"> ... </li>

with 

    <li> ... </li>

The tests run successfully.

**Comment by benschenker** [comment]
Hey @jenvyn thanks for posting this!

Good point @suhussai that should work as a workaround until #2791 is resolved.

Closing this as a duplicate, feel free to reopen this if it is not resolved for you.
