### ISSUE TITLE
Waypoint: Manipulate Arrays With unshift....Wrong example, description is vague.

### ISSUE THREAD

**Issue by guavajellyf1sh** [FreeCodeCamp/FreeCodeCamp#3208]
Challenge http://freecodecamp.com/challenges/waypoint-manipulate-arrays-with-unshift has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

The example shown here: 
```
var ourArray = ["Stimpson", "J", ["cat"]];
ourArray.shift();
ourArray.unshift(["happy", "joy"]);
// ourArray now equals [["happy", "joy"], "J", ["cat"]]
```
Is wrong. When I try to do as shown it results in error.

myArray.unshift("Paul"); this is correct, and not shown in the example, yet neither description nor example shows this.

Please fix.

**Comment by benschenker** [comment]
Hey @guavajellyf1sh thanks for posting this!

The example you mentioned is in the comments just to show you how you might use the `unshift` function, however it is not the answer as you have pointed out.

I see why the wording of the example might be confusing, do you have any suggestions that might make it easier to understand?

**Comment by guavajellyf1sh** [comment]
Yes instead of showing the incorrect example ourArray.unshift(["happy", "joy"]); 

Can you please show the correct way ourArray.unshift("happy", "joy"); ?

**Comment by vizz0r** [comment]
Yeap, no square brackets when adding values at the beginning of an array, which is confusing, since when you declare an array, you use square brackets but there you go... Example tricks people (line 4). It made me go round in circles for a while before I realised what it was.

**Comment by guavajellyf1sh** [comment]
Same here. I had to look it up on W3schools.com for their example and viola it worked. More of a typo than a bug.

**Comment by benschenker** [comment]
The example is not incorrect, just confusing.  I think the confusion is that it adds an array as an element to an array of strings so it goes from:
`[STRING, STRING]`
to
`[ARRAY, STRING, STRING]`.

This is definitely confusing to a beginner, I would suggest that the lesson just add a string instead.

**Comment by guavajellyf1sh** [comment]
var ourArray = ["Stimpson", "J", ["cat"]];
ourArray.shift();
ourArray.unshift(["happy", "joy"]);
// ourArray now equals [["happy", "joy"], "J", ["cat"]]

Hi Ben,

Why is it when I copy the same exact example code for code it doesn't show up as it should? It only works when remove the square brackets. Yet the example shows it with the the string with the square brackets [()]?

**Comment by benschenker** [comment]
Hi @guavajellyf1sh, 

Where are you copying it such that it doesn't work?

**Comment by guavajellyf1sh** [comment]
I copied the form myArray.unshift(["string"]); which didn't work. myArray.unshift("string") worked as it is without the square brackets.

This has the ([""]) brackets in the example which I copied, and apparently wasn't correct.
ourArray.unshift(["happy", "joy"]);

**Comment by benschenker** [comment]
Hey @guavajellyf1sh, I'm going to try to chat with you on Gitter to see if we can figure this out

**Comment by guavajellyf1sh** [comment]
Alright cool. What's your chat username?

**Comment by benschenker** [comment]
Okay, so after working through it with @guavajellyf1sh , we've confirmed that the instructions are correct but confusing since it prepends a nested array in the example and just asks the user to prepend a string in the challenge.

I propose changing the example to prepend a string or a number to remove this confusion (or adequately explain nested arrays/objects).
