### ISSUE TITLE
Same code, to the letter and whitespace fails on waypoint 9 of html

### ISSUE THREAD

**Issue by drdaveg** [FreeCodeCamp/FreeCodeCamp#3212]
perhaps a plugin is the problem
Challenge http://freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

**Comment by drdaveg** [comment]
Another person and I have the same code.  Mine does not make the text red

**Comment by benschenker** [comment]
Hey @drdaveg thanks for posting!

Check out [Creating a Github Issue](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Creating-a-New-Github-Issue) for some tips to make it easier to respond to your issue.  Can you post some screenshots and examples of the code so that I can try to replicate this?
