### ISSUE TITLE
Conflick in test case

### ISSUE THREAD

**Issue by thanhdd** [FreeCodeCamp/FreeCodeCamp#3213]
Challenge http://www.freecodecamp.com/challenges/waypoint-use-an-id-attribute-to-style-an-element has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Image Link: 
https://www.dropbox.com/s/fhtvhsma0kjkwvl/Screen%20Shot%202015-09-10%20at%2008.29.41.png?dl=0

**Comment by benschenker** [comment]
Hey @thanhdd thanks for posting!

On line 55 your `<form>` element has a class, but the test requires that there be no class.  Remove the class attribute and it should pass.

Check out our wiki page for [Bug Posting Guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug).
