### ISSUE TITLE
Problem running the test cases.

### ISSUE THREAD

**Issue by priyansh1990** [FreeCodeCamp/FreeCodeCamp#3219]
![codeissue](https://cloud.githubusercontent.com/assets/6958908/9779198/f9d62418-5796-11e5-8d04-b9ff9c2b1079.png)
Challenge http://freecodecamp.com/challenges/waypoint-target-even-numbered-elements-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible.
1). Run test never give the right results for the first time. You just have to re-run it again and again to satisfy the conditions.
2). The conditions in above image are satisfied and resolved but we can see this cross sign on particular condition. 
3). The same condition are shown twice

**Comment by benschenker** [comment]
Hey @priyansh1990 thanks for posting this!

Can you post the code you are using on this page so I can try to replicate this? Take a look at [Code Formatting](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/code-formatting) for how to do that.

Also have you tried [a Hard Refresh](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache), or incognito mode?  This helps us confirm that you have the latest code and not an old cached version.

**Comment by priyansh1990** [comment]
Problem persists with Mozrilla, Works like charm in chrome

**Comment by ahstro** [comment]
I'm not having any trouble with the latest version of Firefox. Would you mind posting your code like @benschenker asked and let us know which version of FIrefox you're running? :)

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
