### ISSUE TITLE
Need to update all broken image links and resize images for guide/english/tools/source-code-editors/index.md

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#32207]
**Describe your problem and how to reproduce it:**
There are many broken image links and the Visual Studio Code icon is way too large.

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/tools/source-code-editors/index.md

**Tell us about your browser and operating system:**
* Browser Name: n/a
* Browser Version: n/a
* Operating System: n/a

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/5313213/47684577-97010480-db90-11e8-8240-4c4936141c33.png)

**Comment by CodeB9** [comment]
I can work on this.

**Comment by RandellDawson** [comment]
@CodeB9 has already submitted a PR which will most likely be accepted to resolve this issue.  We have a backlog of PRs, so it will be a while before it gets merged.  There is no need to create any additional PRs for this issue at this time.

PRs are merged in the order they are received.

Thank you.
