### ISSUE TITLE
Virtual box Issue

### ISSUE THREAD

**Issue by Deducts** [freeCodeCamp/freeCodeCamp#32228]
https://gyazo.com/adaf7338ca355caf5f055a9587dd924b

issue is happening so much. I have tried to change version multiple times, followed about 15 different ways as to how you could fix and still nothing is working.

Any suggestions for this it will be extremely appreciated.

**Comment by guido97** [comment]
Intentaste esto?  (you tried it?)
https://forums.virtualbox.org/viewtopic.php?f=6&t=82277

**Comment by Deducts** [comment]
> Intentaste esto? (you tried it?)
> https://forums.virtualbox.org/viewtopic.php?f=6&t=82277

Yep

**Comment by RandellDawson** [comment]
What exactly does this have to the with this repo?
