### ISSUE TITLE
Visible Unit Tests

### ISSUE THREAD

**Issue by CourtneyJooste** [FreeCodeCamp/FreeCodeCamp#3224]
Challenge http://beta.freecodecamp.com/challenges/waypoint-declare-javascript-variables has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 10.0, WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>. 

I can see the unit tests eg: "<code>assert((function(){/**/if(typeof(myName) !== "undefined" && typeof(myName) === "string" && myName.length > 0){return true;}else{return false;}/**/})(), 'myName should be a string that contains at least one character in it');</code>"
for each checkbox on the Javascript challenges.
Unsure of how to reproduce this error.

**Comment by ahstro** [comment]
I'm pretty sure that this is the normal functionality - whether it should be altered or not is another question - but could you provide a screenshot just to be sure?

**Comment by CourtneyJooste** [comment]
Sure, here is a screenshot

![unit-tests](https://cloud.githubusercontent.com/assets/1292406/9786874/b6116bc6-57bd-11e5-8b2a-69cf14274764.png)

**Comment by awesomeaniruddh** [comment]
Tests didn't used to be self-invoked functions if I remember correctly.

**Comment by ahstro** [comment]
@CourtneyJooste That's how it looks for me, and has always done, but maybe I'm just being oblivious because of habit. Could someone else confirm whether this is intended or not?

@awesomeaniruddh What do you mean?

**Comment by CourtneyJooste** [comment]
Just for reference; comparing to a jQuery challenge:

![jquery-tests](https://cloud.githubusercontent.com/assets/1292406/9787126/1525538c-57c0-11e5-8bf0-bd9b08210529.png)

The actual unit test is hidden in the above image.

**Comment by ahstro** [comment]
Now that you mention it.. Strange.

**Comment by awesomeaniruddh** [comment]
@ahstro 

If you look at the seeds for the affected JS sections, the test is:
```js
"tests": [
        "assert((function(){/**/if(typeof(myName) !== \"undefined\" && typeof(myName) === \"string\" && myName.length > 0){return true;}else{return false;}/**/})(), 'myName should be a string that contains at least one character in it');"
      ],
```
^^ That's for the `Declare JS Variable` javascript challenge.

What I mean is that this suggests that someone manually put that up in the seed and it is either intended (unlikey) or an error. I am not sure about this though, and will have to wait for someone with more knowledge to comment on this.

**Comment by benschenker** [comment]
This is on purpose starting in the JS challenges, so that the users can see the exact testing code and figure out why the test failed. See https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2231#issuecomment-132786670
