### ISSUE TITLE
Can continue without solving problem.

### ISSUE THREAD

**Issue by mazer-rakham** [FreeCodeCamp/FreeCodeCamp#3228]
![waypointbug](https://cloud.githubusercontent.com/assets/11220261/9790623/0c333c8c-57a5-11e5-92c7-c76034de32f2.jpg)
Challenge http://www.freecodecamp.com/challenges/waypoint-add-your-javascript-slot-machine-slots has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 6.2, WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

Can hit ctrl + enter to advance without solving the problem.

**Comment by awesomeaniruddh** [comment]
This is weird: sometimes it accepts (without any code), sometimes it doesn't (without any code).

**Comment by ahstro** [comment]
The tests seem to pass if all the slot numbers are equal. I'll see if I can find a solution.

**Comment by ahstro** [comment]
Okay, I've created a PR with a solution, but it's not ready to be merged yet.

**Comment by BerkeleyTrue** [comment]
@ahstro @awesomeaniruddh An issue cannot be `confirmed`, `in progress`, and `discussing` at the same time.

**Comment by Nathandim** [comment]
Issue still persists. I could click complete and proceed without solving the problem.
