### ISSUE TITLE
Link for documentation: use-proptypes-to-define-the-props-you-expect 

### ISSUE THREAD

**Issue by paulywill** [freeCodeCamp/freeCodeCamp#32286]
There should be a link to the documentation mentioned.

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/front-end-libraries/react/use-proptypes-to-define-the-props-you-expect

![image](https://user-images.githubusercontent.com/602422/47692401-def14d00-dbcb-11e8-9e08-b555d1c1a8b8.png)

**Comment by TomerPacific** [comment]
@paulywill ,
willing to take this on if no one has claimed it.

**Comment by Nirajn2311** [comment]
@TomerPacific no one has claimed it, so if you are interested I can assign this to you.

**Comment by TomerPacific** [comment]
I have created a [PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/32635)
