### ISSUE TITLE
dependency on fbgraph is missing

### ISSUE THREAD

**Issue by aldraco** [FreeCodeCamp/freecodecamp#323]
When the controllers/api.js file is used (which it seems not to be in normal use of the app) there is a missing dependency on fbgraph. it's not in the package.json.

line 8 in controllers/api.js
used in the getFacebook call.

Also node-linkedin and twit.

This may shed light on issue #295 where linkedin emails aren't sending.

**Comment by QuincyLarson** [comment]
Hi @aldraco none of these API functions were being called anywhere in the codebase. I've deleted the API controller.
