### ISSUE TITLE
Is this correct. Either I am not understanding what is being asked of me or there is a problem. 

### ISSUE THREAD

**Issue by BaxterMoneflakes** [FreeCodeCamp/FreeCodeCamp#3230]
Challenge http://freecodecamp.com/challenges/waypoint-make-instances-of-objects-with-a-constructor-function has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 10.0, WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey @BaxterMoneflakes thanks for posting!

Take a look at our [Bug Posting Instructions](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug).  Feel free to reopen this after you go through those steps, as there is not enough information here to replicate/resolve this.
