### ISSUE TITLE
HTML5 & CSS #52 - Error with completion of Waypoint: Override Class Declarations with Inline Styles

### ISSUE THREAD

**Issue by TiffanyECook** [FreeCodeCamp/FreeCodeCamp#3231]
When the code is correct, this waypoint does not provide a completion pop-up, nor does it mark the waypoint completed in the user's map.

![screen shot 2015-09-10 at 3 57 17 pm](https://cloud.githubusercontent.com/assets/13739292/9801159/6639fc36-57df-11e5-95b1-99ebbf64e027.png)

**Comment by benschenker** [comment]
Hey @TiffanyECook, I believe this is about: http://freecodecamp.com/challenges/waypoint-override-class-declarations-with-inline-styles

Can you post a screenshot of the rest of the tests (on the left side) that got cut off?  Also can you [paste in the code](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/code-formatting) you are using?

**Comment by TiffanyECook** [comment]
That's the only test for this challenge, at least according to my screen. 
![screen shot 2015-09-10 at 6 04 25 pm](https://cloud.githubusercontent.com/assets/13739292/9802183/6e632192-57e6-11e5-8be7-659a45760456.png)

 Here's the code I was using:

<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  #orange-text {
    color: orange;
  }
  .pink-text {
    color: pink;
  }
  .blue-text {
    color: blue;
  }
</style>
<h1 style="color: white" class="pink-text blue-text">Hello World!</h1>

**Comment by awesomeaniruddh** [comment]
Hmm, I can see five tests on my screen and your code only passes 4 of them.

![screenshot 5](https://cloud.githubusercontent.com/assets/5279150/9803271/6dec0202-5853-11e5-84f6-62512b716cea.png)

There are several things you can do at this point to try and fix this:

1. Doing a Hard-Refresh: instructions [here](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache)
2. Reopening the browser window (not the tab)
3. If both of the steps don't fix it, then try using another browser

Please report back with the results. Hopefully they fix the issue :)

**Comment by BerkeleyTrue** [comment]
closing as stale. Please feel free to reopen if issue still persists.
