### ISSUE TITLE
npm run bootstrap is failing due to Certificate expired issue with pm2

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/freeCodeCamp#32336]
**Describe the bug**
The `npm run bootstrap` step is failing, leading to [failed Travis builds](https://travis-ci.org/freeCodeCamp/freeCodeCamp/builds/448155115?utm_source=github_status&utm_medium=notification) across several recent PRs.
This is due to "certificate expired" issue with `pm2` - https://github.com/Unitech/pm2/issues/3991
```
 lerna bootstrap && lerna run build --scope @freecodecamp/curriculum
lerna notice cli v3.4.0
lerna info versioning independent
lerna info Bootstrapping 5 packages
lerna info Installing external dependencies
lerna ERR! npm ci exited 1 in '@freecodecamp/api-server'
lerna ERR! npm ci stderr:
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! errno UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! request to https://tgz.pm2.io/gkt-1.0.0.tgz failed, reason: unable to verify the first certificate
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-10-30T04_33_01_135Z-debug.log
lerna ERR! npm ci exited 1 in '@freecodecamp/api-server'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
```

**To Reproduce**
1. Execute `npm run bootstrap`

/cc @raisedadead

**Comment by raisedadead** [comment]
See: https://github.com/Unitech/pm2/issues/3992 We would need to restart all of those newly failing builds.

**Comment by Nirajn2311** [comment]
@raisedadead I will start restarting the builds.

**Comment by vanditbhatt** [comment]
I made two PRs and both of them failed due to expired certificate as well.

**Comment by Nirajn2311** [comment]
@Manish-Giri @raisedadead  All PRs from 31908 to 32432 (both included) should be restarted.
