### ISSUE TITLE
My Waypoint progress is shown on m phone, but when I login to a computer, it shows no progress completed. I have tried logging in and out, and yes, it is the same account.

### ISSUE THREAD

**Issue by IgnisCerebrum** [FreeCodeCamp/FreeCodeCamp#3234]
Challenge http://freecodecamp.com/challenges/waypoint-say-hello-to-html-elements has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 6.1, WOW64

**Comment by awesomeaniruddh** [comment]
Thanks for reporting the issue @IgnisCerebrum!

Can you please do a hard-refresh on your computer's browser: instructions [here](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache)

That should fix the issue.

**Comment by moigithub** [comment]
as i know all exercises are saved on browser LocalStorage.. so if u running different browsers/computers LocalStorage will be different which will reflect on your progress report

**Comment by BerkeleyTrue** [comment]
@moigithub Is correct, we do not carry your progress between browsers.

Happy Coding,

-Berks
