### ISSUE TITLE
Typo in challenge

### ISSUE THREAD

**Issue by larkfairy** [FreeCodeCamp/FreeCodeCamp#3235]
Should be "Run tests", and not "Run code"... Just a little typo. Thanks!!!
Challenge http://www.freecodecamp.com/challenges/bonfire-meet-bonfire has an issue. User Agent is: <code>Mozilla/5.0 (Macintosh, Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.22 Safari/537.36</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by awesomeaniruddh** [comment]
Thanks for reporting the issue @larkfairy :). That's a nice catch. PR on the way!
