### ISSUE TITLE
document.write() cause problems

### ISSUE THREAD

**Issue by lee5214** [FreeCodeCamp/FreeCodeCamp#3238]
I just start self-testing on FCC and I found one small problem which is the document.write()

When practice, I wrote this function to see the output, it's like this:

http://freecodecamp.com/challenges/bonfire-confirm-the-ending
```
function end(str, target) {
  str.split("");
  target.split("");
  for(var i=target.length;i>0;i--){
      if(str[str.length-i]===target[i-1]){
       // return true;
       document.write(str[str.length-i]);
      }
      else{ return false};   
  }
}
end('Connor', 'n');
```
It will refresh the whole webpage to a white one, and then print output on it. Since the codes are saved automatically and it will run every time I reload the page, so I have to double click the refresh button really quick to stop the loading. But coding area didn't show up for rewrite, so I had to reset the code.

**Comment by awesomeaniruddh** [comment]
Thanks for opening the issue @lee5214!
