### ISSUE TITLE
the spinning ball or its variant

### ISSUE THREAD

**Issue by eismont** [FreeCodeCamp/FreeCodeCamp#3239]
Challenge http://freecodecamp.com/challenges/waypoint-create-a-set-of-checkboxes has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

Not sure how to reproduce it, but although I've gotten all the checks in a positive light, the next level refuses to become a reality. Is this  a bug or my own ignorance of what to do to reach the next level. I admit to code ignorance, thats why I'm here... 

I am not attaching an image since it isn't an issue with the code as it exists. Its an issue with the transition to the next step. I've waited patiently, stopped and reset the code review. All to no avail. I cannot proceed.

**Comment by AkiraLaine** [comment]
@eismont It seems that the Waypoint "Check Radio Buttons and Checkboxes by Default" has the same test twice (probably a mistake), hence the reason you can't pass. I suggest you move on for now :D

**Comment by benschenker** [comment]
@eismont thanks for posting! Does this still happen in an incognito window of chrome?  Is it on every challenge or just this one?

**Comment by eismont** [comment]
well it seems to have cleared and I am on to the next challenge, but am now confronted by a more confounding problem on challenge 37, set the id of an element. I have followed the instructions, I have asked a developer for help. i have searched the web for clues and yet, nothing seems to result in a satisfactory transition to the next level. Am I too dense to get it? Attached is an image of what I input and the persistent red X! which indicates my failure. I am here waiting for the tooth fairy!

![cahallenge37](https://cloud.githubusercontent.com/assets/11192022/9842149/f2265830-5a77-11e5-9269-955beccc55ae.png)

**Comment by bugron** [comment]
@eismont thanks for posting this issue!
The challenge wants you to give `id="cat-photo-form"` to your `form` element and **not** `h2` (or any other element) as you did.
This is from challenge's description: 
>Give your **form** element the id cat-photo-form.

And this is from tests' section:
>Give your **form** element the id of cat-photo-form.

Also remove this from your code: 
![](http://i.imgur.com/zjtAKLO.png)

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by Acke83** [comment]
Sorted?
try this...replace <form action="/submit-cat-photo"> with <form id="cat-photo-form"> . I was on it one hour :D
