### ISSUE TITLE
Inconsistent test cases for bonfire-diff-two-arrays

### ISSUE THREAD

**Issue by dting** [FreeCodeCamp/FreeCodeCamp#3241]
Challenge http://www.freecodecamp.com/challenges/bonfire-diff-two-arrays has an issue. User Agent is: <code>Mozilla/5.0 (Macintosh, Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

Some of the tests use `includeMembers` while others use `deepEqual`. They should probably be consistent in whether order matters or not.

![screen shot 2015-09-11 at 2 56 16 am](https://cloud.githubusercontent.com/assets/394393/9812237/c2caa116-5830-11e5-8bde-4c7ba4267e8a.png)

**Comment by awesomeaniruddh** [comment]
Thanks for reporting the issue @dting!

**Comment by QuincyLarson** [comment]
I'll make these consistent with my forthcoming refactor of all Bonfire tests.

**Comment by ddeveloperr** [comment]
Hi there, 

My code is:
```
function diff(arr1, arr2) {

  return arr1.filter(function(item) { return arr2.indexOf(item) === -1; }).
  concat(arr2.filter(function(item) { return arr1.indexOf(item) === -1; }));

}

diff([1, 2, 3, 5], [1, 2, 3, 4, 5]);
```

I tried a lot of examples, different code and always stuck on the last test

[1, 2, 3, 3], [1] should return [2, 3].

Can you Help here and tell me how can I go forward?
