### ISSUE TITLE
Can't Run locally

### ISSUE THREAD

**Issue by lightify97** [freeCodeCamp/freeCodeCamp#32411]
Hi, I'm trying to build freecodecamp offline but having this issue.
What is happening here.
![fcc](https://user-images.githubusercontent.com/16276964/47701904-2d8aff80-dc3d-11e8-93b5-3a17bc55190f.png)

 - OS: Ubuntu
 - Version 18.04

**Comment by raisedadead** [comment]
This is a common error with Unix like systems, and not specific to freeCodeCamp setup. @Bouncey do you agree?

**Comment by Bouncey** [comment]
I thought we had moved off of our fork of `gatsby-source-filesystem`.

@lightify97 try updating your local fork, we recently fixed a bug with memory usage when developing locally.

```sh
# This adds the freeCodeCamp repository as an upstream repository
git remote add upstream https://github.com/freeCodeCamp/freeCodeCamp.git

# This pulls down the latest changes form the upstream repository
# then replays your local changes (if any) over the top of it
git pull --rebase upstream master
```

**Comment by raisedadead** [comment]
Closing because this is a support thread, comments are still welcome.
