### ISSUE TITLE
Weird text in tasks

### ISSUE THREAD

**Issue by Bravo13** [FreeCodeCamp/FreeCodeCamp#3246]
Challenge http://freecodecamp.com/challenges/waypoint-check-the-length-property-of-a-string-variable has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 10.0, WOW64
![screenshot](http://content.screencast.com/users/Bravo13/folders/Jing/media/631c297b-1d46-467d-bb7c-3d04032c79de/2015-09-11_1738.png)
All works, but looks weird

**Comment by awesomeaniruddh** [comment]
Thanks for reporting the issue @Bravo13, but the text is not `weird` :)

**Comment by bugron** [comment]
@Bravo13 By saying not weird @awesomeaniruddh meant that it is normal that you are able to see the contents of `assert`s. For more info [see here](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2818).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by seewhen** [comment]
I was going to report the same issue - Maybe it is not entirely clear that it's supposed to show up?

**Comment by bugron** [comment]
@seewhen there is a mention about this in [Waypoint: Comment your JavaScript Code](http://freecodecamp.com/challenges/waypoint-comment-your-javascript-code). See the last paragraph of the challenge's description.
