### ISSUE TITLE
accepted answer incorrect

### ISSUE THREAD

**Issue by leftfieldhero** [FreeCodeCamp/FreeCodeCamp#3247]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-a-specific-child-of-an-element-using-jquery has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 6.3, WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

$(".target:nth-child(2)").addClass("animated bounce"); is not the correct jQuery/JavaScript for this answer and is very confusing to new people. target is merely the palce holder for a class.The answer should be:

$(".well:nth-child(2)").addClass("animated bounce");

Please also update the sample.

**Comment by leftfieldhero** [comment]
I guess I just don't quite understand the nth-child notation.

**Comment by benschenker** [comment]
Hey @leftfieldhero take a look at https://github.com/FreeCodeCamp/FreeCodeCamp/issues/1927#issuecomment-132369084
