### ISSUE TITLE
Chai is not Defined: Make Object Properties Private Exercise 

### ISSUE THREAD

**Issue by varuniyer** [FreeCodeCamp/FreeCodeCamp#3249]
Challenge http://freecodecamp.com/challenges/waypoint-make-object-properties-private has an issue. User Agent is: <code>Mozilla/5.0 (Macintosh, Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36 OPR/31.0.1889.174</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by benschenker** [comment]
Hey @varuniyer thanks for posting this!

Have you seen [our Bug Reporting Steps](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Help-I've-Found-a-Bug)?  Following those makes it much easier for us to replicate and fix any issues.

Can you post any code you input and a screenshot of the whole page including the error?

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!
