### ISSUE TITLE
Make some of the challenge seed read only

### ISSUE THREAD

**Issue by ahstro** [FreeCodeCamp/FreeCodeCamp#3250]
On the basic JavaScript challenges, maybe some others as well, there is code that shouldn't be edited by the camper. Where code should be inserted is signaled with comments `// Only change code below this line.` and `// Only change code above this line.`, however, code outside those lines are still editable.
The editor that freeCodeCamp uses - CodeMirror - supports setting text to read only. This seems like an intricate process, and I'm sure it's not needed, but I just thought I'd let everyone know that it is a possibility. Maybe someone is masochistic enough to spend a weekend manually punching in the line numbers that should be read only for each waypoint?

Relevant links:
* [Official docs on `markText`, which is used to set the `readOnly` property](http://codemirror.net/doc/manual.html#markText)
* [A StackOverflow example showing how to set the value. `word` would be replaced with `editor` for FCC](http://stackoverflow.com/a/25716648/3962001)

**Comment by ltegman** [comment]
Closing this since the addition of head/tail sections to challenge seed should mostly resolve the need for this.
