### ISSUE TITLE
H4 element does not pass. 

### ISSUE THREAD

**Issue by johndsykes86** [FreeCodeCamp/FreeCodeCamp#3251]
Challenge http://www.freecodecamp.com/challenges/waypoint-label-bootstrap-wells has an issue. User Agent is: <code>Mozilla/5.0 (Macintosh, Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

Unable to get h4 test condition 1 to pass.

typed in first H4 manually. Copied that into second col-xs-6 div. 
hit ctrl-enter, doesn't pass
clicking on button doesn't pass
hard refresh + clearing history and cache doesn't work.

I did use copy and paste in the previous lessons to create buttons. 

Attached screenshot of code is below 
![w03gl2uegsmg5frlapwnwlpgvcjky8iotma8xf3j4sc](https://cloud.githubusercontent.com/assets/9035479/9829354/0d74790a-58b6-11e5-8e6c-9181cf724636.png)

**Comment by johndsykes86** [comment]
It seems doing a hard reset for the code and retyping the h4's manually resolved the issue.

**Comment by munga4** [comment]
Their is still a bug
