### ISSUE TITLE
The "Run Test" button is not working.

### ISSUE THREAD

**Issue by tashfeenMustafa** [FreeCodeCamp/FreeCodeCamp#3252]
Challenge http://freecodecamp.com/challenges/waypoint-declare-javascript-objects-as-variables has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 10.0, Win64

**Comment by bugron** [comment]
@tashfeenMustafa thanks for posting this issue!
@tashfeenMustafa please, provide your code and a screenshot, thanks

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding.

**Comment by iallfree** [comment]
![screenshot 2](https://cloud.githubusercontent.com/assets/16330271/11916244/743ec3fe-a693-11e5-9561-8f9baaad43df.png)

I think I've got the same error going. 
I feel that I did the code correctly -exactly.. and think that the run test failed to recognize that it was written correct

**Comment by iallfree** [comment]
It is the closing bracket that is causing the problem.. I found the issue... I did not see that there was already a closing };  down at the bottom
