### ISSUE TITLE
Option to auto-paste code into issue when created with the `Bug` button

### ISSUE THREAD

**Issue by awesomeaniruddh** [FreeCodeCamp/FreeCodeCamp#3258]
This *should* improve the quality of the issues as a lot of issues could be solved immediately if the user posted the code when he opened the issue.

Could be implemented as a checkbox (that is checked by default) maybe?

**Comment by ahstro** [comment]
I'm looking into this.

**Comment by ahstro** [comment]
This looks like it will be hard to implement without changing how we create issues. I'm looking into using the GitHub API instead of a POST request.
