### ISSUE TITLE
color doesn't change after using a CSS class

### ISSUE THREAD

**Issue by prashantcare** [FreeCodeCamp/FreeCodeCamp#3259]
![bugwith color change](https://cloud.githubusercontent.com/assets/14246065/9830609/36d13c8c-5953-11e5-85e8-220a7b0525f1.PNG)
Challenge http://freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 6.1, WOW64

**Comment by bugron** [comment]
@prashantcare thanks for posting this issue!
This challenge works fine for me. Click **Reset** button and try again. If that won't help try to [Refresh Your Browser Cache](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache) and [Clear Your Browser's Local Storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Clear-Your-Browser%27s-Local-Storage).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
