### ISSUE TITLE
Learn Button does not go to the first item in the Map Not Completed

### ISSUE THREAD

**Issue by ericcgu** [FreeCodeCamp/FreeCodeCamp#3265]
Challenge http://www.freecodecamp.com/challenges/bonfire-where-do-i-belong has an issue. User Agent is: <code>Mozilla/5.0 (Macintosh, Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by BerkeleyTrue** [comment]
Correct, It does not. It goes to the next challenge based on the last challenge you opened. This is intentional.

Happy Coding.
