### ISSUE TITLE
 Bootstrap should be added also to JavaScript...

### ISSUE THREAD

**Issue by samscripts** [FreeCodeCamp/FreeCodeCamp#3268]
Challenge http://www.freecodecamp.com/challenges/waypoint-get-set-for-ziplines has an issue. User Agent is: <code>Mozilla/5.0 (X11, Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

Hi, Bootstrap should be added also to JavaScript in addition to  jQuery in codepen.io. If not, some functionality problem occurs like in the case of using navbar-collapse which won't work.

**Comment by awesomeaniruddh** [comment]
Thanks for posting the issue, @samscripts.

I'll look into this :)
