### ISSUE TITLE
I can post a story/comment as another user

### ISSUE THREAD

**Issue by MrRenter** [FreeCodeCamp/freecodecamp#327]
Its known we pass the User object with each page. Well when we do something like submit a story or comment we pass that same user object back to the server and use that when saving to the db. If before I hit submit I edit the values used I can appear as a different user. I dont believe these are sanitized either meaning I could probably do something naughty. Here is an example as me posing as quincy. http://www.freecodecamp.com/stories/what-is-the-xy-problem-meta-stack-exchange

**Comment by terakilobyte** [comment]
This is now resolved on the beta, aka master branch. Please continue testing at http://beta.freecodecamp.com for further vulnerabilities.

I'm closing this issue for now as it's too broad. Please open specific issues for new vulnerabilities.
