### ISSUE TITLE
Page frozen

### ISSUE THREAD

**Issue by ktakats** [FreeCodeCamp/FreeCodeCamp#3270]
One of the pages (Bonfire: Seek and Destroy) is completely "frozen" for me. I mean I can move the mouse, but can't click on anything, can't reset or edit my code or do anything, and if I close the tab and return later I still see my old code and the page is frozen.

**Comment by ahstro** [comment]
Possible duplicate of #2264, #2272 and/or #2556. Try following [this](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2264#issuecomment-134329750) and see if it resolves the issue.

**Comment by ktakats** [comment]
Yep, that solved it, thanks.
