### ISSUE TITLE
Rename replace function - Bonfire: Search and Replace

### ISSUE THREAD

**Issue by Gmrpr7** [FreeCodeCamp/FreeCodeCamp#3271]
Challenge http://www.freecodecamp.com/challenges/bonfire-search-and-replace has an issue. User Agent is: <code>Mozilla/5.0 (X11, Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

Just wanted to suggest renaming the function in this challenge. It is a bit confusing to suggest using a javascript String method named replace() inside our own function named replace(). Something simple like myReplace() or SearchAndReplace() would work.

**Comment by BerkeleyTrue** [comment]
I would like to hear from other Campers on this topic as well before we make any changes.

**Comment by ahstro** [comment]
@BerkeleyTrue Personally, I'm not really affected by this, but I have a hard time looking at things from others' perspectives; I assume it can be confusing to newer programmers.

**Comment by bugron** [comment]
Closing this issue as https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3326 is merged.
