### ISSUE TITLE
Travis CI Builds: SecurityError: localStorage is not available for opaque origins    

### ISSUE THREAD

**Issue by paulywill** [freeCodeCamp/freeCodeCamp#32724]
**Describe the bug**

PR builds for freeCodeCamp / freeCodeCamp are failing in Travis CI with the following:

**To Reproduce**
1. Submit a minor PR change
2. Check build in Travis CI (ie: https://travis-ci.org/freeCodeCamp/freeCodeCamp/builds/448319658)

**Expected behavior**
PR should pass all the builds to allow QAs to merge PRs to repo.

**Screenshots**
![image](https://user-images.githubusercontent.com/602422/47735473-f586bb00-dc42-11e8-88e9-520df207d13c.png)

**Additional context**
ref:jsdom/jsdom#2304

**Comment by paulywill** [comment]
@ValeraS @raisedadead Correct me if I'm wrong but 'unpacked.js' is asking for: 

`window.addAssertsToTapTest = require('./addAssertsToTapTest');`

If this file was missing would that not trip something?

**Comment by raisedadead** [comment]
Did you mean this file: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/unpacked.js ?
I believe all this is unused completely. And some of the files around that as well.

If you are investigating, I recommend you look https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/test/test-challenges.js

The challenge-markdown-parser is something worth looking at as well. It's in the tools.
