### ISSUE TITLE
Waypoint 1.18 needs to explain how to add multiple classes

### ISSUE THREAD

**Issue by rclai** [FreeCodeCamp/FreeCodeCamp#3276]
[This lesson](http://freecodecamp.com/challenges/waypoint-add-borders-around-your-elements) has no explanation of how to add both the class names `smaller-image` and `thick-green-border` to the image. A CSS noob would be forced to assume that you're supposed to just add another `class=".."` to the image tag.

It isn't until somewhere in waypoint 1.5x that it explains using a space to add multiple class names to the class attribute.

**Comment by awesomeaniruddh** [comment]
Thanks for posting the issue @rclai.

Agreed. I'll fix the issue right away.

**Comment by rclai** [comment]
I wanted to do a PR, but then realized you guys have a bunch of other languages (wow).

**Comment by awesomeaniruddh** [comment]
Shit I didn't realize that! It seems that the other languages are not being updated though...the code does not correlate with the English code.

**Comment by awesomeaniruddh** [comment]
Shit I didn't realise that!

I'll open a PR for the updated description in English, but we'll need someone to update the description in the other language (which looks like German, not sure) as well.

**Comment by bugron** [comment]
Closing this issue as https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3278 is merged.

**Comment by rclai** [comment]
Cool, thanks.
