### ISSUE TITLE
Waypoint: Learn how Script Tags and Document Ready Work

### ISSUE THREAD

**Issue by orkist** [FreeCodeCamp/FreeCodeCamp#3279]
Challenge http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 10.0, Win64

The run code button or using CTL Enter  is not working.  I refreshed my page and tried in a different browser.

**Comment by awesomeaniruddh** [comment]
Have you tried `hard-refreshing`?

Here's how to do it: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache

**Comment by orkist** [comment]
yes, and logging in and back out.  I am only having the issue with that one
exercise.


On Sun, Sep 13, 2015 at 12:50 AM, Aniruddh Agarwal <notifications@github.com

**Comment by BerkeleyTrue** [comment]
Can you paste the code that is causing the issue?

**Comment by orkist** [comment]
It was most likely my browser (MS Edge) that was causing the issue.  It works in a different browser.

**Comment by AndrewMDuke** [comment]
It was the browser for me as well. IE11 no good. Chrome works fine.

**Comment by krstikiv** [comment]
Yup, same issue with MEdge(IE) browser. Chrome is fine.
