### ISSUE TITLE
Not loading all code when page loads

### ISSUE THREAD

**Issue by DarrenfJ** [FreeCodeCamp/FreeCodeCamp#3280]
Challenge http://freecodecamp.com/challenges/waypoint-use-responsive-design-with-bootstrap-fluid-containers has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 6.3, WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

When the page initially loads it only has this much code
```javascript
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
```

When you click anywhere on the page t loads the rest. Refresh brings it back to a 'partially' loaded page

**Comment by bugron** [comment]
@DarrenfJ thanks for posting this issue!
We are aware of this issue. You can continue further discussion [here](https://github.com/FreeCodeCamp/freecodecamp/issues/2707), thanks.
Closing as a duplicate.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
