### ISSUE TITLE
Challenges showing complete/incomplete incorrrectly

### ISSUE THREAD

**Issue by zoltanbiber** [FreeCodeCamp/FreeCodeCamp#3282]
I'm doing my challenges in order and doing the section 7 (Basic Front End Development Projects), waypoint 5 (Pomodoro Clock).
Recently the map started showing the complete/incomplete waypoints incorrectly. 

The whole section 5. Object Oriented and Functional Programming shows as incompleted
Section 8 (Intermediate Algorithm Scripting), waypoint 4 (Bonfire: Where art thou) shows as complete.

I've heard there was an update which introduced the bug (or fixed it?) but haven't found anyone else with the exact same bug.

**Comment by benschenker** [comment]
Hey @zoltanbiber thanks for posting an issue!

Is this still problematic for you?

Can you clarify the exact issue?  Is it that you completed the Object/Functional Programming section but the map says that it is incomplete?

**Comment by zoltanbiber** [comment]
Yes, I have completed section 5 but now it shows up correctly as completed.
The core issue is still there though, not everything shows up correctly as completed/uncompleted.
Section 1: completed but shows as uncompleted
Section 9: all completed, shows up as only partially completed.
Section 4: shows as uncompleted but that section was added recently I guess so it is uncompleted by me.
