### ISSUE TITLE
how declare to classes on same element img

### ISSUE THREAD

**Issue by vvkgdm** [FreeCodeCamp/FreeCodeCamp#3283]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-borders-around-your-elements has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 10.0, WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by awesomeaniruddh** [comment]
Thanks for reporting the issue @vvkgdm.

You can add multiple classes to the same element by separating them with a space inside the class attribute. For instance:
```html
<element class="class1 class2"></element>
```

I'm closing the issue as these kind of issues are really meant to be asked at the Help room (link: gitter.im/FreeCodeCamp/Help) and I believe that this resolves your issue. Feel free to reopen for additional clarification (and also give our help chat room a whirl!).

Happy coding!
