### ISSUE TITLE
Suggestion: Add links to MDN pages for Basic JavaScript, Object Oriented and Functional Programming, etc Waypoints

### ISSUE THREAD

**Issue by izybit** [FreeCodeCamp/FreeCodeCamp#3284]
Because many Waypoints in Basic JavaScript, Object Oriented and Functional Programming, etc are about a single method it would be a good idea to add a link to the specific MDN page (or some other resource) that discusses that method (and maybe some related ones, such as shift/unshift).

This way a camper can jump directly to the page and learn exactly how to use the method.

(This happens already for some Bonfires for example.)

**Comment by ahstro** [comment]
This is a great idea. I didn't know that we were lacking links in some parts of the new curriculum.
I'm not going to assign myself just yet, so if someone wants to snatch it, feel free. I'll hopefully be able to look at this later tonight or tomorrow if no one else has fixed it by then.

**Comment by izybit** [comment]
I would do this myself but unfortunately I lack the knowledge to do it correctly.

**Comment by ahstro** [comment]
@izybit Then this is a great opportunity to gain that knowledge!
Getting a local copy of freeCodeCamp is pretty well documented [here](https://github.com/FreeCodeCamp/FreeCodeCamp#getting-started).
To add MDN links to a site, just add the key from `seed/bonfireMDNlinks.js` to the `MDNLinks`-array of the challenge in the appropriate `seed/challenges/*.json`-file.
If a link i s missing in `seed/bonfireMDNlinks.js`, just add it.
If you run into any problems, you can @ me either here or on Gitter.

**Comment by izybit** [comment]
@ahstro This looks doable. I will spend some time on it and confirm I can do it.

**Comment by ahstro** [comment]
Good luck! :+1:

**Comment by BerkeleyTrue** [comment]
> Please note - we aren't adding MDN links to Waypoints - only bonfires. The point of the Waypoints is to be fast paced. If there's content on the MDN page that we need to communicate it, we should communicate it in the waypoint itself.

[ref](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3286)
