### ISSUE TITLE
Should explain .map() better.

### ISSUE THREAD

**Issue by tesla809** [FreeCodeCamp/FreeCodeCamp#3289]
Challenge http://freecodecamp.com/challenges/waypoint-iterate-over-arrays-with-map has an issue. User Agent is: <code>Mozilla/5.0 (Macintosh, Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

I didn't come across with a deep understanding of .map(). 
The lesson should address .map() a bit better such as: the reason for its notation, the difference between it and a for loop, etc.

**Comment by awesomeaniruddh** [comment]
Since this issue is very similar to the one you opened on `reduce`, I'm closing this and editing that one. Happy Coding!
