### ISSUE TITLE
Challenge Syllabus

### ISSUE THREAD

**Issue by KidLogic** [FreeCodeCamp/freecodecamp#329]
The Challenges are great because they take an inexperienced developer, such as myself, through various courses in a cohesive and chronological order.

To help assist with understanding the "Challenges" course structure, can we have some high-level overview/syllabus that will show which courses/materials are covered in the challenges? Furthermore, this will help me, and other new Campers, gauge their progress.

**Comment by terakilobyte** [comment]
@KidLogic, our new challenge map should help address a lot of your concerns. Let us know what you think by visiting http://beta.freecodecamp.com
