### ISSUE TITLE
Run Test action get stuck on this waypoint

### ISSUE THREAD

**Issue by anissat** [FreeCodeCamp/FreeCodeCamp#3295]
Challenge http://freecodecamp.com/challenges/waypoint-add-id-attributes-to-bootstrap-elements has an issue. User Agent is: <code>Mozilla/5.0 (Macintosh, Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

**Comment by bugron** [comment]
@anissat thanks for posting this issue!
Please, provide the description of your issue/code/screenshot, thanks!
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by anissat** [comment]
My apologies! After trying it out on another computer, it seems to work fine... please disregard!

**Comment by bugron** [comment]
Closing this issue, Feel free to reopen if you still experience problems.
