### ISSUE TITLE
Curriculum list should show incomplete blocks and sub-blocks

### ISSUE THREAD

**Issue by xeoneux** [freeCodeCamp/freeCodeCamp#32960]
It'd be easier to know the remaining lessons if they're shown directly in the curriculum list...

**Comment by xeoneux** [comment]
Something like this... Bold titles for lessons that are still pending with count on the right and normal titles for completed lessons.

![noname](https://user-images.githubusercontent.com/3099626/47776459-78c61080-dd18-11e8-913b-3b79654eb884.png)

**Comment by RaspberryLime** [comment]
This is the same as [
https://github.com/freeCodeCamp/freeCodeCamp/issues/17869](url) I think?

**Comment by xeoneux** [comment]
@RaspberryLime this is for the profile page, yes. I think #25750 will fix this issue...

**Comment by matthewchase** [comment]
fix now at https://github.com/freeCodeCamp/freeCodeCamp/pull/34331

**Comment by moT01** [comment]
I believe this is resolved to you satisfaction @xeoneux? I am going to close it then. Feel free to reopen and describe more what you were thinking. 

FYI - this is what the current beta looks like...
<img width="585" alt="Screen Shot 2019-05-05 at 6 30 27 PM" src="https://user-images.githubusercontent.com/20648924/57201848-f129ba80-6f63-11e9-9ee2-71a4aa33488f.png">
