### ISSUE TITLE
Paragraph framed incorrectly 

### ISSUE THREAD

**Issue by amarsuchak** [FreeCodeCamp/FreeCodeCamp#3299]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 10.0, WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

Hello there, in the following paragraph, the function is not understandable. I figured it out but it took me about 10 minutes and I think it could have been avoided if the sentence was framed better.

"For example, let's make all of your button elements bounce. Just add this code inside your document ready function: $("button").addClass("animated bounce")."

The "document ready function: " is all written in purple aswell so I thought it was part of what I had to put into the code.

![capture](https://cloud.githubusercontent.com/assets/11834074/9853914/30038d18-5b17-11e5-9921-1e9c36873b25.JPG)

**Comment by bugron** [comment]
@amarsuchak thank you for pointing this out!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by awesomeaniruddh** [comment]
Closing because issue has been resolved by PR.
