### ISSUE TITLE
"Target the Children of an Element Using jQuery" example "background color of blue"

### ISSUE THREAD

**Issue by vmackey** [FreeCodeCamp/FreeCodeCamp#3306]
http://www.freecodecamp.com/challenges/waypoint-target-the-children-of-an-element-using-jquery

On "Here's an example of how you would use the children() function to give the children of your left-well element the **background color of blue** : $("#left-well").children().css(**"color"**, "blue")"

Shouldn't it just be **color of blue** instead of **background color of blue**?

**Comment by bugron** [comment]
@vmackey thank you for pointing this out!!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
