### ISSUE TITLE
Nth to last character in a String

### ISSUE THREAD

**Issue by michelleqho** [FreeCodeCamp/FreeCodeCamp#3307]
Challenge http://freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-nthtolast-character-in-a-string has an issue. User Agent is: <code>Mozilla/5.0 (Windows NT 6.1, WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>. Please describe how to reproduce this issue, and include links to screenshots if possible.

If finding the last character in a string is the length of the string minus 1, wouldn't finding the nth to last character in a strength be subtracting quantity (n+1)?

**Comment by avastu** [comment]
You can look at it like the last character in a string is the "first to last" character, and therefore n-1. The second to last character in a string is n-2. And thus finding the nth to last character in a string is not (legnth-(n+1)), but (length-n). In the future, I'd recommend using the [Help Room]( https://gitter.im/FreeCodeCamp/Help) to understand concepts like these!
