### ISSUE TITLE
Suggestion: Adding new translation version for Traditional Chinese

### ISSUE THREAD

**Issue by huanyichuang** [freeCodeCamp/freeCodeCamp#33080]
It's just like Portuguese in Brazil is different from Portuguese in Portugal. Chinese used in China and the one used in other regions are also different (from phrases to characters); thus, I wonder if it is possible to start another localization project for Traditional Chinese.

**Comment by wanga815** [comment]
There are differences in meaning and wording come to understanding.

**Comment by moT01** [comment]
Thanks for the suggestion @huanyichuang, we currently only support the six current languages and any additional languages will be added if it deemed appropriate. I don't think this issue needs to remain open. Thanks and happy coding!
