### ISSUE TITLE
Chrome 45 on a surface... the code lines dont all show up

### ISSUE THREAD

**Issue by codeguy2015** [FreeCodeCamp/FreeCodeCamp#3309]
![image](https://cloud.githubusercontent.com/assets/13212966/9868873/6c07aec6-5b43-11e5-8a31-0fdea1735f03.png)

Now when I click in the code area.. now all of the lines of the example show up. Why does it do this? Seems like a bug. Thanks

![image](https://cloud.githubusercontent.com/assets/13212966/9868879/8a1e2430-5b43-11e5-803d-3f880fc4b076.png)

**Comment by avastu** [comment]
It's a known issue (#3294), fix should be implemented soon!

**Comment by bugron** [comment]
@codeguy2015 thanks for posting this! We are aware of this issue and this is a duplicate so I'll close it, thanks.
