### ISSUE TITLE
Refactor Intermediate Bonfires to use Assert instead of Expect

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3314]
Please see basic-bonfires.json where I have refactored all the old expect-style tests into assert-style tests. Please do your best to make the test style match no-nonsense style I used here.

**Comment by awesomeaniruddh** [comment]
I can give this a try.

**Comment by natac13** [comment]
@awesomeaniruddh are you doing the entire file? Just wondering where to start with 
#3315

**Comment by awesomeaniruddh** [comment]
I'll likely be doing the entire file (probably tomorrow). If it ends up being too much work, or I run into any issues, I'll ping you :)
