### ISSUE TITLE
Refactor Advanced Bonfires to use Assert instead of Expect

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3316]
Please see basic-bonfires.json where I have refactored all the old expect-style tests into assert-style tests. Please do your best to make the test style match no-nonsense style I used here.

**Comment by natac13** [comment]
I can try this one out... I did also want to inquire if there was a way to fix how on some challenges the string part of the test is displayed and then on some the whole assert() statement is displayed aswell... I have noticed that on challenges that only have the proper text that there is no `;` at the end of the test but when I have tried to remove this on testing it breaks a lot more then I can understand... so I was just curious on an thoughts as I think #3319 talk about it.

I will keep this updated on my status of completion.

**Comment by natac13** [comment]
Umm embarrassing but when I run gulp now I get some `Segmentation fault (core dumped)` any thoughts?
