### ISSUE TITLE
Falsy bouncer - incorrect solution passes

### ISSUE THREAD

**Issue by richyvk** [FreeCodeCamp/FreeCodeCamp#3317]
Challenge [Bonfire: Falsy Bouncer](http://freecodecamp.com/challenges/bonfire-falsy-bouncer) has an issue.

My code:
```
function bouncer(arr) {
  // Don't show a false ID to this bouncer.
  function value(val) {
    return val != false && typeof val != undefined && val != 0 && val != null;
  }
  
  arr = arr.filter(value);
  return arr;
}

bouncer([7, "ate", "", false, 9], "");

```

My code passed but as you can see does not deal empty strings or NaNs.

**Comment by awesomeaniruddh** [comment]
That's because you are not strictly comparing `false` with `false`.

**Comment by ahstro** [comment]
@awesomeaniruddh Exactly, @richyvk's code shouldn't pass, but does.

This is really strange, since `NaN`s, empty strings, and `undefined`s were added to the tests by @abhisekp in #3124. Must've gotten lost somewhere along the line.. I'll create a PR that fixes it again.

**Comment by MiniGunnR** [comment]
Also this following code also passes. I wrote nothing to filter the values.
```
function bouncer(arr) {
  function valid(data) {
    return data;
  }
  return arr.filter(valid);
}
```
