### ISSUE TITLE
result display affected by console.log()

### ISSUE THREAD

**Issue by lee5214** [FreeCodeCamp/FreeCodeCamp#3318]
I just find a weird problem, and tried several ways including ask on gitter and check the source code, but still couldn't get the reason, so I'm showing the problem hope someone knows why.

in Bonfire: Smallest Common Multiple (http://freecodecamp.com/challenges/bonfire-smallest-common-multiple)
I finished my code, and it passed the tests. But during debug, one thing I noticed is that if I replace the line 13 ```rec(i,arr1,1,position);```with line 14 ```console.log(rec(i,arr1,1,position));```, the result still display the correct answer while the tests showing the results(which are the results should be shown) don't match.
I'm new to JS so I have no idea if it's a bug or just some JS magic or I did something wrong.

![image](https://cloud.githubusercontent.com/assets/13610499/9872559/f2d101b8-5b4e-11e5-9ef0-56bb525d11aa.png)

```
function smallestCommons(arr) {  
  arr.sort(function(a, b){return a-b;});//sort in numerical order

  //all numbers into arr1
  var arr1=[];
  arr1.push(arr[0]);
  for(var i=arr[0]+1;i<=arr[1]-arr[0];i++){arr1.push(i);};
  arr1.push(arr[1]);
  
  // to call rec() to get the array of multipliers
  for(var i=1;i<arr1.length;i++){
    position=i-1;
      rec(i,arr1,1,position);
    //console.log(rec(i,arr1,1,position));
  }
  
  //multiple all numbers through the array, return value
  var multiUp=arr1[0];
  for(var i=0;i<arr1.length;i++){
    multiUp *= arr1[i];
  }
  return multiUp;
  
 //recusive fn checks position(range:[arr[first]-arr[last]]) if the num can be divided, return the answer back to argument (num), 
 //then continue checking from the last position.if done, return the array as final result
  function rec(num,array,index,position){
    for(var i=index;i<position;i++){
      if(num%array[i]==0){
        var div=array[i];
        array.splice(position,1,num/div);
        console.log(array +  "  index:  "+arr.indexOf(arr[i])+"  div:  "+div);
       return rec(num/div,array,i+1,position);
      }
    }return array; 
  }
  //
}
smallestCommons([5,1]);
```

**Comment by awesomeaniruddh** [comment]
I think it must be because your code needs the `rec` function to return something but by putting it inside console.log you are actually returning undefined, because console.log returns undefined. Just a little theory. No JS wizard either :P

**Comment by lee5214** [comment]
@awesomeaniruddh 
I think maybe I got it.
Because the rec() function actually would manipulate the array in its arguments
Once I use console.log(), the rec() will run and return the results back to the array, the rec() and console.log(rec()) work the same in my case .
Thank you very much for the help.

**Comment by awesomeaniruddh** [comment]
So is the problem solved? If it is, please close the issue :)

**Comment by garyc60674** [comment]
What's going on?
