### ISSUE TITLE
Problem in the test to create a style class?

### ISSUE THREAD

**Issue by rmcvicar** [FreeCodeCamp/FreeCodeCamp#3322]
Challenge [Waypoint: Use a CSS Class to Style an Element](http://freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux i686 (x86_64)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>

  .blue-text {

    color: blue;

  }

</style>

<h2 class="blue-text">CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by bugron** [comment]
@rmcvicar thanks for posting this issue!
Please, provide the description of your issue/code/screenshot, thanks!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by ahstro** [comment]
@rmcvicar I can pass this challenge with no problem, and since your code makes the `h2`-text blue instead of red, I'm going to assume you just misread the instructions.
I'll close this, but feel free to reopen it once you've read the guidelines that @bugron linked to and if there's an actual bug.

**Comment by rmcvicar** [comment]
Yeah, the heading didn't seem to change colour for me.  No big deal, just
moved on anyway

**Comment by pbolfan** [comment]
Hmmm I just started doing these and it didn't work for me if I copied and modified the example code, but if I typed it out, it accepted it....Weird.
