### ISSUE TITLE
Waypoint: Learn how Script Tags and Document Ready Work

### ISSUE THREAD

**Issue by alan1001110** [FreeCodeCamp/FreeCodeCamp#3327]
There is nothing in this Waypoint that teaches you how document.ready works, but there is a brief explanation in the Waypoint after.  

I suggest adding the following text to the first jQuery waypoint instructions (and deleting the document ready explanation from the second jQuery waypoint):

"Code you put inside the document ready function will run as soon as your browser has loaded your page.

This is important because without your document ready function, your code may run before your HTML is rendered, which would cause bugs."

**Comment by benschenker** [comment]
Hey @alan1001110 thanks for posting!

This is definitely a question of style, so it is hard to respond decisively.  I see your point and am marking this appropriately.  I'd recommend @benmcmahon100 chiming in before we move forward with the suggested fix though.

**Comment by benmcmahon100** [comment]
We can add it if it's really needed but document ready does very little and it's completely self explanatory.

**Comment by alan1001110** [comment]
It's actually not completely self-explanatory to beginners.  I read it and wondered, "what document am I getting ready? I don't understand and this doesn't explain anything". I spent 30 minutes researching, and learned essentially what is said in two sentences in the following lesson, (where it's out of place):

"Code you put inside the document ready function will run as soon as your browser has loaded your page. This is important because without your document ready function, your code may run before your HTML is rendered, which would cause bugs."

**Comment by benmcmahon100** [comment]
Okay so we just need to move it back a lesson. Okay will do!
