### ISSUE TITLE
Run Tests is not working

### ISSUE THREAD

**Issue by varungn** [FreeCodeCamp/FreeCodeCamp#3328]
Challenge [Waypoint: Declare JavaScript Objects as Variables](http://freecodecamp.com/challenges/waypoint-declare-javascript-objects-as-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//Here is a sample Object
var car = {
  "wheels":4,
  "engines":1,
  "seats":5
};

//Now Let's make a similar Object called motorBike
//Give it two wheels, one engine and one seat
var motorBike = {
  // Only change code below this line.

  "wheels":2,
  "engines":1,
  "seats":1


  // Only change code above this line.
};

(function() {return JSON.stringify(motorBike);})();

```

**Comment by bugron** [comment]
@varungn thanks for posting this issue!
Please, provide the description of your issue/screenshot, thanks!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by avastu** [comment]
Could you elaborate on what errors you're getting? Your code runs fine with no issues on my end.

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps to reproduce the issue.

Happy Coding!

**Comment by rohitchugh9** [comment]
Run test button is not working.
------------------------------------------------
// Example
var ourName = "Free Code Camp";
// Only change code below this line
var myName = "Rohit";
------------------------------------------------
Above is the sample code.

Same problem persists with every exercise.
Nothing happens when i click on run test button.
