### ISSUE TITLE
two radio button elements should be nested in its own label element. but how? thanks

### ISSUE THREAD

**Issue by vvkgdm** [FreeCodeCamp/FreeCodeCamp#3329]
Challenge [Waypoint: Create a Set of Radio Buttons](http://www.freecodecamp.com/challenges/waypoint-create-a-set-of-radio-buttons) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p>Click here for <a href="#">cat photos</a>.</p>

<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<form action="/submit-cat-photo">
  <input type="text" placeholder="cat photo URL" required>
  <button type="submit">Submit</button>
</form>
<label>
  <input type="radio" name="indoor-outdoor" >indoor
  <input type="radio" name="indoor-outdoor" >outdoor
</label>

```

**Comment by bugron** [comment]
@vvkgdm thanks for posting this issue!
This is the description of that test:
>**Each** of your two radio button elements should be nested in **its own** label element.

This means that you should create **two** labels for your radio buttons. This is how you should do that.
```html
<label><input type="radio" name="indoor-outdoor">indoor</label>
<label><input type="radio" name="indoor-outdoor">outdoor</label>
```
If you have such questions/problems, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by nazmul202101** [comment]
Thanks

**Comment by ninopaolo** [comment]
I was stuck here for a long time! Thank you!

**Comment by pseud0nyms** [comment]
thank you...

**Comment by Kangroo111999** [comment]
Could anyone tell me why this is so ? Because I don't see the difference.

**Comment by David-Coyne** [comment]
Cheers! I was stumped on this one.

**Comment by w-ak9** [comment]
<label>
    <label>
    <input type="radio" name="indoor-outdoor">indoor
    </label><br>
    <label>
      <input type="radio" name="indoor-outdoor">outdoor
    </label><br>

**Comment by w-ak9** [comment]
Put both the inputs in separate <label> tag!
 `<label>
 <input type="radio" name="indoor-outdoor">indoor </label><br> 
</label>`
`<label>
<input type="radio" name="indoor-outdoor">outdoor </label><br> 
</label>`
