### ISSUE TITLE
Error: "You should have made use of the reduce/filter method"

### ISSUE THREAD

**Issue by rollingdice** [FreeCodeCamp/FreeCodeCamp#3331]
Challenge [Waypoint: Condense arrays with reduce](http://freecodecamp.com/challenges/waypoint-condense-arrays-with-reduce) has an issue.
Challenge [Waypoint: Filter Arrays with filter](http://freecodecamp.com/challenges/waypoint-filter-arrays-with-filter) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>.
A space between 'array.reduce' and '(' will make the reduce method undetectable. When I remove the space, everything goes well.
The same error also exist in "Filter array with filter" waypoint, with slightly different error message.

My code:
```javascript
var array = [4,5,6,7,8];
var singleVal = 0;
// Only change code below this line.
var singleVal = array.reduce (function (previousVal,currentVal){
  return previousVal+currentVal;
});


// Only change code above this line.
(function() {return singleVal;})();

```

**Comment by natac13** [comment]
I can add in the optional space like before @bugron
