### ISSUE TITLE
Test cases need to be extended

### ISSUE THREAD

**Issue by smarshy** [FreeCodeCamp/FreeCodeCamp#3338]
Challenge [Bonfire: Roman Numeral Converter](http://freecodecamp.com/challenges/bonfire-roman-numeral-converter) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

ISSUE:
The test cases that you have listed range from 1 to 30.My code clears it logically.However ,i referred to the link you posted about roman numerals and the same code wouldn't work for numbers beyond 40.(refer to the part where  i just keep appending X if number divisible by 10).You could probably check for more numbers so as to ensure that the logic is perfect.

My code:
```
function convert(num) {
  //for range 1 to 30 roman numbers.has to considerably be modified for complete range
  var digits=[];
  while(num>0)
    {
      var digit=num%10;
      digits.push(digit);
      num=Math.floor(num/10);
    }
  var obj1={1:'I',2:'II',3:'III',4:'IV',5:'V',6:'VI',7:'VII',8:'VIII'',9:'IX'};  
  var evalua=0;var midans="";var ans=[];var divi=0;var mult=0;
  for(var i=0;i<digits.length;i++)
    { midans="";
      mult=Math.pow(10,i);
      evalua=digits[i]*mult;
      if (evalua==0)
        {
          continue;
        }     
      if (evalua%10==0)
        {
          divi =Math.floor(evalua/10);
          for(var j=0;j<divi;j++)
            {
              midans=midans+"X";
            }
        }
      
      else{
        
        midans=midans+obj1[digits[i]];
      }    
      ans.push(midans);     
    } 
 ans.reverse();
 return ans.join("");
  
}

convert(36);

```

**Comment by benschenker** [comment]
Hey @smarshy thanks for posting this!

Yes it looks like we are only testing numbers under 30.  I see why you might want more more numbers to be tested.  I'll tag this as a test improvement issue.
