### ISSUE TITLE
Not a bug, but a grammatical error in the description

### ISSUE THREAD

**Issue by flossless** [FreeCodeCamp/FreeCodeCamp#3339]
Not sure if this is the right place to make a comment about this, but the second paragraph beginning
with:
"JavaScript uses **use** the * symbol..."

The additional word 'use' is unnecessary. I'm noticing the same error in several of the following waypoints. Just FYI :)

**Comment by avastu** [comment]
>several of the following waypoints

Sorry--which waypoints? Could you link to them please? Thanks for creating the issue!

**Comment by flossless** [comment]
Not sure how to link them, but these are the few I have found:

Waypoint: Subtract One Number from Another with JavaScript
Waypoint: Multiply Two Numbers with JavaScript
Waypoint: Divide One Number by Another with JavaScript

Hope this helps.

**Comment by avastu** [comment]
Thanks! Fixed it, should be merged soon.
