### ISSUE TITLE
Basic Javascript #40 Quotation Explosion

### ISSUE THREAD

**Issue by digitalstephen** [FreeCodeCamp/FreeCodeCamp#3340]
The code snippet that students are asked to use introduces the double use of quotation marks for the first time, and does not discuss it.  To my knowledge, the use of quotation marks in this way is not discussed in any prior lesson either.

The code snippet is 

`$($('.slot')[0]).html('<img src = "' + images[slotOne - 1] + '">');`

In all of the previous examples, double quotes were used, for example $(".slot") to select the slot class.  We can assume that the sudden change to single quotes at the beginning indicates that single quotes and double quotes are functionally identical, but the second half gets far more complicated.

It was explained to me by gitter chat that the desired end result is something like:
`<img src = "someurl" > `, which made me think that maybe the other quotes acted like a sort of escape character.  However, reversing the order of the quotation marks appears to make a fully functioning demo.

From this I conclude that the first type of quotation mark in use within a sub-expression is the dominant one that can be used to close out strings, even if they include the other type of quotation mark.

Anyway, I thought that this particular expression:
`$($('.slot')[0]).html('<img src = "' + images[slotOne-1] + '">');`
was a sudden leap in difficulty if you really want to understand the provided code snippets that we are pasting into the examples with small modifications.  

I recommend either a short paragraph explaining the use of the quotation marks in this case (we do it to render a final expression that looks something like `<img src="someurl">` as an end result), or a quick lesson prior to this one discussing how quotation marks are sometimes interchangeable and can be used to  encapsulate each other (with an example), or as a third possibility a different way of finishing this lesson off which doesn't present unexplained use of syntax for the newbie student to try and figure out in addition to the underlying lesson of adding graphics to an element from an array via javascript.

I'm a complete beginner, so am not sure how to  contribute suggested solutions via github (I had to be pointed here via gitter chat) since I'm unsure about the pull suggestion that was made, but I'm glad to try and help if an instruction on how best to do so is emailed or messaged to me.

**Comment by benschenker** [comment]
Hey @digitalstephen thanks for posting this.

You are totally correct! I think the assumption is that users should copy and paste that line but they should at least understand what they are copying and pasting.

**Comment by benschenker** [comment]
Anyone have any ideas on the exact language that should be added?

**Comment by digitalstephen** [comment]
---
Note that the use of the two types of quotation marks in the second part of this expression allows the argument of the .html() to resolve in the form <img src = "someurladdress"> .  The first type of quotation mark used in an expression makes it the dominant type which will then open or close out a string, even if that string contains the other type of quotation mark.
---
The second sentence could be left out in the interest of brevity if desired.  Also, as a beginner, I'm not sure of my vocabulary.  Is argument correct in this instance?

**Comment by ltegman** [comment]
The slot machine challenge this line comes from is no longer in the curriculum. Thanks and happy coding!
