### ISSUE TITLE
Throws an error

### ISSUE THREAD

**Issue by Klu6ok** [FreeCodeCamp/FreeCodeCamp#3344]
Challenge [Waypoint: Uncomment HTML](http://freecodecamp.com/challenges/waypoint-uncomment-html) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--Привет Мир-->
<h1>Hello World</h1>
<!--Фото кота-->
<h2>CatPhotoApp</h2>
<!--P сокращенное от слова Параграф-->
<p>Hello Paragraph</p>
```
I took not needed -->. And still gives an error Be sure to delete all trailing comment tags, i.e. -->.

**Comment by bugron** [comment]
Здравствуйте, @Klu6ok!
Дело в том, что нужно удалить **все** комментарии из Вашего кода. Это следует из:
>Be sure to delete **all** trailing comment tags, i.e. -->.

Поскольку я уверен, что мой ответ решит Вашу проблему, я закрываю этот пост. Вы можете открыть его, если у Вас все еще есть проблемы. Спасибо.

Almost the same in English:
Hello @Klu6ok!
Actually you should remove **all** comments from your code as it is said in corresponding test's description:
>Be sure to delete **all** trailing comment tags, i.e. -->.

Closing this issue. Feel free to reopen if you still experience problems. Thanks.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by Klu6ok** [comment]
Вы мне писали?

-----Исходное сообщение-----
От: "Arsen Melikyan" <notifications@github.com>
Отправлено: ‎17.‎09.‎2015 21:39
Кому: "FreeCodeCamp/FreeCodeCamp" <FreeCodeCamp@noreply.github.com>
Копия: "Klu6ok" <klu6ok@gmail.com>
Тема: Re: [FreeCodeCamp] Throws an error (#3344)

Closed #3344.

**Comment by Klu6ok** [comment]
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>

Сделал такой код. Все равно не пускает. Или я не правильно понимаю, что значит удалить все Коментарии.

**Comment by Klu6ok** [comment]
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>

**Comment by Klu6ok** [comment]
![default](https://cloud.githubusercontent.com/assets/14333572/9957753/827b0ebc-5e0b-11e5-8bdb-cf5b95d9a99c.jpg)

**Comment by Klu6ok** [comment]
Все понял. Удалил все  - Спасибо вам

**Comment by bugron** [comment]
@Klu6ok рад, что решили проблему. Закрываю данный пост.

Closing this issue as the problem is solved.

**Comment by Klu6ok** [comment]
Доброе время суток. Не совсем понял задачу 38. Вставил код по моему в ту строку которую нужно. Помогите пожалуйста разобраться 
![default](https://cloud.githubusercontent.com/assets/14333572/10104131/8c1d4c6e-63b0-11e5-9e93-532cc9f1ca78.png)

**Comment by bugron** [comment]
@Klu6ok здравствуйте!
Дело в том, что Вы задали атрубут `id="cat-photo-form"` элементу `h2`, а нужно было задать для элемента `form`. Вот описание, того, что нужно было делать:
>Give your **form** element the id cat-photo-form.

и еще

>Give your **form** element the id of cat-photo-form.

Если у Вас есть вопросы по поводу кода, пожалуйста, сперва обратитесь с вашим вопросом в нашу [чат-комнату](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter), спасибо.

**Comment by Klu6ok** [comment]
Арсен. Скажите, возможно ли в дальнейшем русифицировать все задания? Ведь
не мало русских хотят заниматься и обучаться.

25 сентября 2015 г., 18:38 пользователь Arsen Melikyan <
notifications@github.com> написал:

**Comment by Klu6ok** [comment]
Спасибо за помощь в разъяснении. Все работает.

25 сентября 2015 г., 18:50 пользователь Биометрик Солюшнс <klu6ok@gmail.com>
написал:

**Comment by bugron** [comment]
@Klu6ok, не за что. В данный момент @alnero занимается переводом заданий. Есть даже открытый PR https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3398, можете поучаствовать в дискуссии.
