### ISSUE TITLE
When I log in it brings me back here

### ISSUE THREAD

**Issue by Lincxx** [FreeCodeCamp/FreeCodeCamp#3349]
Challenge [Waypoint: Use Clockwise Notation to Specify the Margin of an Element](http://freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
When I log back in, it brings me back to this page after I have completed the task. For some odd reason it pulls back in my old answer(margin-top: 40px 20px 20px 40px;) which is wrong and not my current margin: 40px 20px 20px 40px;
My code:
```html
<style>
  .injected-text {
    margin-bottom: -25px;
    text-align: center;
  }

  .box {
    border-style: solid;
    border-color: black;
    border-width: 5px;
    text-align: center;
  }

  .yellow-box {
    background-color: yellow;
    padding: 20px 40px 20px 40px;
  }
  
  .red-box {
    background-color:red;
    margin: 20px 40px 20px 40px;
  }

  .green-box {
    background-color: green;
    margin-top: 40px 20px 20px 40px;
    
    
    
  }
</style>
<h5 class="injected-text">margin</h5>

<div class="box yellow-box">
  <h5 class="box red-box">padding</h5>
  <h5 class="box green-box">padding</h5>
</div>

```

**Comment by ltegman** [comment]
Closing as stale. If you are still experiencing this issue feel free to let us know and someone can reopen.
