### ISSUE TITLE
Bug with Waypoint: Remove an Element Using jQuery

### ISSUE THREAD

**Issue by ezlateva** [FreeCodeCamp/FreeCodeCamp#3352]
Issue with: http://freecodecamp.com/challenges/waypoint-remove-an-element-using-jquery

Getting this error in the console when hitting 'Run tests..'
Uncaught TypeError: Cannot read property 'run' of null

![image](https://cloud.githubusercontent.com/assets/1482216/9970153/7be5d602-5e21-11e5-8641-a3dc957270b2.png)

**Comment by awesomeaniruddh** [comment]
Thanks for posting the issue @ezlateva. I am unable to reproduce the error.

I was able to reproduce the errors The error seems to with this line (line 91) of the commonFramework.js file:

```js
plugin.remote.run(code);
```

Any ideas, @BerkeleyTrue?

**Comment by ltegman** [comment]
Are you still able to repro this @ezlateva or @awesomeaniruddh? I was trying to look into this but can't repro it myself.

**Comment by ezlateva** [comment]
I can't reproduce anymore either. I'm going to close this then :)
