### ISSUE TITLE
If a user forgets a comma the interpreter doesn't notice it just gives this exception: in comments

### ISSUE THREAD

**Issue by RobinsonKameron** [FreeCodeCamp/FreeCodeCamp#3354]
Challenge [Waypoint: Declare JavaScript Objects as Variables](http://www.freecodecamp.com/challenges/waypoint-declare-javascript-objects-as-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
//Here is a sample Object
var car = {
  "wheels":4,
  "engines":1,
  "seats":5
};

//Now Let's make a similar Object called motorBike
//Give it two wheels, one engine and one seat
var motorBike = {
  // Only change code below this line.
  "wheels":2,
  "engines":1,
  "seats":2
  // Only change code above this line.
};

(function() {return JSON.stringify(motorBike);})();

```

**Comment by RobinsonKameron** [comment]
If a user forgets a comma the interpreter doesn't notice it just gives this exception ://Here is a sample Object var car = { "wheels":4, "engines":1, "seats":5 }; //Now Let's make a similar Object called motorBike //Give it two wheels, one engine and one seat var motorBike = { // Only change code below this line. "wheels":2 "engines":1 "seats":2 // Only change code above this line. }; (function() {return JSON.stringify(motorBike);})();

**Comment by bugron** [comment]
@RobinsonKameron thanks for posting this issue!
Actually your code is correct. There is no need for a comma after the last key/value pair (in your case `"seats":2`) so I'm closing this issue. If I misunderstood your issue, please feel free to reopen if you still experience problems, thanks. 

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
