### ISSUE TITLE
Google assets hinder front page loading in China

### ISSUE THREAD

**Issue by leonfeng** [FreeCodeCamp/FreeCodeCamp#3355]
I just ran a batch of tests on Free Code Camp's front page loading time in Safari (history and cookies cleared, all extensions disabled, DNS cache flushed, Ethernet connection). The average was 76.338 seconds (5 total attempts).

The cause of such unresponsiveness is the Google-hosted JavaScript libraries. Eventually the browser gives up on fetching them and displays the front page as-is, but most users probably don't have the patience.
![screen shot 2015-09-19 at 9 23 20 am](https://cloud.githubusercontent.com/assets/241553/9974009/efaa3458-5eb1-11e5-98ec-fc109974cc9a.png)

I am opening a pull request to replace Google with cdnjs.com, which is not blocked in China. However, various components of Free Code Camp also rely on other Google assets, such as Google Analytics and Google Forms.

One potential solution is to replace Google Analytics with self-hosted [Piwik](http://piwik.org/) analytics package. As for Google Forms, maybe typeform.com will serve?

**Comment by bugron** [comment]
Closing this issue as https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3356 is merged. Feel free to reopen if you still experience problems and/or there are more things need to be fixed related to this issue, thanks.
