### ISSUE TITLE
Importing Google font for h2 element not working

### ISSUE THREAD

**Issue by katieroo** [FreeCodeCamp/FreeCodeCamp#3357]
Challenge [Waypoint: Import a Google Font](http://freecodecamp.com/challenges/waypoint-import-a-google-font) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }

p {
    font-size: 16px;
    font-family: Monospace;
  }
  
  <link 
      href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

 h2 {
  font-family: "Lobster", cursive;
}
  
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by yagoferrer** [comment]
Hey @katieroo you have a syntax error. Move the <link> tag to the first line of your code. That will fix the problem.

**Comment by bugron** [comment]
@yagoferrer is correct, `link` shouln't be in `style` tag. Closing this issue.
If you have such questions/problems, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

**Comment by Aqleem** [comment]
![image](https://user-images.githubusercontent.com/26087895/33260879-0fd9ba12-d383-11e7-9264-6baaa41a03f6.png)

**Comment by Aqleem** [comment]
those red x’s are talking about line 2 in your code

**Comment by Hacky09** [comment]
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text{
    font-size: 16px;
    font-family: monospace;
  }
   h2{
    color: red;
    font-family: Lobster;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<main>
  <p class="red-text">Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div>
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

**Comment by Milan-Varghese** [comment]
<link 
      href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
      <style>
  .red-text {
    color: red;
  }

p {
    font-size: 16px;
    font-family: Monospace;
  }



 h2 {
  font-family: "Lobster", cursive;
}

</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

**Comment by RandellDawson** [comment]
@katieroo Please stop posting code with no context to closed issues.  If you have questions, please use [our forum](https://www.freecodecamp.org/forum).

**Comment by Milan-Varghese** [comment]
> @Milan-Varghese Please stop posting code with no context to closed issues. If you have questions, please use [our forum](https://www.freecodecamp.org/forum). You were already instructed on another thread to use the forum. Thank you.

@RandellDawson very sorry about that.I'm new to github.By the way thanks for your concern
