### ISSUE TITLE
Suggestions for Make a Person Bonfire

### ISSUE THREAD

**Issue by ltongues** [FreeCodeCamp/freecodecamp#336]
Make tests more friendly. Until you write the six functions you don't even get to see any tests. All you see is something like:

`bob.setFullName` is not a function. Program Execution Failure. No user tests were run.

Rewrite the spec to be more exact. For example, you don't know the arity of `setFullName`. Is it one parameter or two? Turns out it's one. I think little things like that will just slow people down.

**Comment by terakilobyte** [comment]
I'm not against specifying the arity of the functions but the tests shouldn't change. The error enforces the instructions by stating which function a user forgot to implement.
