### ISSUE TITLE
Suggestions for Symmetric Difference Bonfire

### ISSUE THREAD

**Issue by ltongues** [FreeCodeCamp/freecodecamp#337]
Specify unambiguously that the symmetric difference of a variable number of arrays is meant to be done reduce-style: do a symmetric difference of the first two arrays, then do an SD of the result of first SD with the third array, etc. Right now it's hard to figure out why tests work the way they do.

**Comment by terakilobyte** [comment]
I agree the challenge could use a rewrite. Pr welcome if you have the time. Please don't use "reduce style" in the new wording though.
