### ISSUE TITLE
Unclear explanation

### ISSUE THREAD

**Issue by Luomint** [FreeCodeCamp/FreeCodeCamp#3373]
Challenge [Bonfire: Slasher Flick](http://freecodecamp.com/challenges/bonfire-slasher-flick) has an issue.

Please describe how to reproduce this issue, and include links to screenshots if possible.

It's unclear what the "head" is when talking about an array, at least to me... I assumed that the head is at the end of an array but it looks like the author thinks that the array starts with the head

**Comment by natac13** [comment]
I can add in a line to say that.
