### ISSUE TITLE
Wrong code passes for Bonfire - Where do I belong 

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/FreeCodeCamp#3381]
The following code for Bonfire - Where do I belong passes the tests but it's not the correct code.
The tests need modifications to ensure that.

```js
function where(arr, num) {
  // Find my place in this sorted array.
  for (var i = 0; i < arr.length; i++) {
    if (num <= arr[i]) {
      return i;
    }
  }
  return arr.length;
}
```

**Comment by abhisekp** [comment]
Currently working on this issue.

**Comment by xpkc34** [comment]
Hi abhisekp. I wrote the following code for this Bonfire which also passes but is also incorrect:

```js
function where(arr, num) {
  arr = arr.sort()
  count = 0
  for (i = 0; i < arr.length; i++) {
    if (num > arr[i]) {
      count = count + 1
    }
  }
  return count
}
```
Using arr = arr.sort() is incorrect because it sorts numbers like 1, 10, 2, 3 etc. etc, a compare function should be used instead. But this incorrect sort still allows you to pass the tests.

**Comment by abhisekp** [comment]
@xpkc34 yes. That's fixed in this PR.
cc: @QuincyLarson @benmcmahon100
