### ISSUE TITLE
FreeCodeCamp Down

### ISSUE THREAD

**Issue by avastu** [FreeCodeCamp/FreeCodeCamp#3389]
![image](https://cloud.githubusercontent.com/assets/8085410/9986423/4ed792e6-5ff1-11e5-925b-1624e7c3e31a.png)

It looks like FreeCodeCamp is down.

**Comment by bugron** [comment]
Seems now everything is OK.
![](http://i.imgur.com/aqR6v9y.png)

**Comment by BerkeleyTrue** [comment]
The best thing to do is to send me a message on Gitter when this happens.
