### ISSUE TITLE
Bonfire: Everything Be True, need more tests??

### ISSUE THREAD

**Issue by tva10** [FreeCodeCamp/FreeCodeCamp#3394]
Challenge [Bonfire: Everything Be True](http://www.freecodecamp.com/challenges/bonfire-everything-be-true) has an issue.

I got all (three) test cases using this code. (Unfortunately, I just did not read the task completely, and passed it.)
But I think this bonfire needs more test cases to check `true` value for `{'someProp':'someVal'}`

My code, which passed :
```
function every(collection, pre) {
  return collection.every(function(e){
    return e.hasOwnProperty(pre);   //checks only definition
  });

}

//some test cases:

every([{'user': 'Tinky-Winky', 'sex':'female'}, {'user': 'Po', 'sex':'female'}], {'sex':'female'}); 
//is false, but should be true in this task, because we have objects with 'sex' property with 'female' value, Isn't it?


every([], 'someProp'); //is true, but may be should be false, because there are no Objects which has someProp

```
upd.1: Just looked solution in [Wiki](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/bonfire-everything-be-true) and I am even more confused.
Most alarmed that's this line in the solution: `if (collection[c].hasOwnProperty(pre) || collection[c][pre] == pre) {`

ps: Sorry for my broken English :D

**Comment by manos19** [comment]
Hello tva10 , i agree with you. It might have a bug , because in the test, if you just type : 
return collection[0].hasOwnProperty(pre);
the test is passed.

**Comment by ltegman** [comment]
I think the verbal description for this challenge is also somewhat unclear. The first paragraph would seem to indicate that we only need to check if the given property exists, however the second paragraph (and second and third test case) would seem to require that we also test that the property has a given value.

**Comment by BerkeleyTrue** [comment]
Yes the tests are incorrect except for the first. The predicates should always be a key('string') and not an object.

The MDN links should also be removed as they are not relevant to the challenge.

This challenge also needs more test cases.

**Comment by BerkeleyTrue** [comment]
I also just noticed that the MDN links incorrectly state `hasOwnProperty()` and `getOwnPropertyNames()`
are static properties when in fact they are prototype methods.

it should be
```js

Object.prototype.hasOwnProperty()
Object.prototype.getOwnPropertyNames()
```

**Comment by ltegman** [comment]
@BerkeleyTrue So, just to clarify, you would like the MDN links left but cleaned up to reflect that they are prototype methods?

**Comment by BerkeleyTrue** [comment]
No they should be removed. The challenge is to understand truthy vs falsey (ridiculous names but this is JavaScript). Those methods are related to checking whether a property exist on the object or its prototype.

**Comment by BerkeleyTrue** [comment]
There also needs to be tests that have falsey values such as 0, and "" (empty strings are falsey but still count as defined).

**Comment by ltegman** [comment]
Sounds good. The MDN links had made me go the complete opposite direction with my PR (checking if the property is defined only), but I can swing it back the other way.

**Comment by BerkeleyTrue** [comment]
awesome!
