### ISSUE TITLE
The text in the phone does change to Monospace, yet it won't allow me to continue

### ISSUE THREAD

**Issue by kjhg76** [FreeCodeCamp/FreeCodeCamp#3397]
Challenge [Waypoint: Set the Font Family of an Element](http://www.freecodecamp.com/challenges/waypoint-set-the-font-family-of-an-element) has an issue.
User Agent is: <code>Opera/9.80 (X11; Linux x86_64; Edition Linux Mint) Presto/2.12.388 Version/12.16</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  .red-text {
    color: red;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p>Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by bugron** [comment]
@kjhg76 thanks for posting this issue!
I am able to pass that test with your code. Note that [we officially support only Chrome browser](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2942#issuecomment-136591448). I believe that your Opera is outdated and that is why you can't pass the test. Try the latest version of Chrome (or FireFox). 
Closing this issue. Feel free to reopen if you still experience problems, thanks.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
