### ISSUE TITLE
Why it is set to true ?

### ISSUE THREAD

**Issue by dzunik91** [FreeCodeCamp/FreeCodeCamp#3399]
Challenge [Bonfire: Confirm the Ending](http://freecodecamp.com/challenges/bonfire-confirm-the-ending) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
![error](https://cloud.githubusercontent.com/assets/6382429/10023220/39be73dc-6151-11e5-8878-93c75350e6c3.PNG)

My code:
```
function end(str, target) {
 
  var newStr = str.slice(-1);
  
  
  if(newStr != target){
      return false;
  }else
  return true;
}

end("He has to give me a new name", "name", "");

Am I missing something ? This phrase with error should by set to false Right ?

**Comment by ahstro** [comment]
Please read the [contribution guidelines](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

**Comment by awesomeaniruddh** [comment]
Thanks for posting the issue @dzunik91, but there is no error in the phrase. It ends with the word 'name' which is also the second argument.
