### ISSUE TITLE
Field Guide appearance should match "Map" appearance

### ISSUE THREAD

**Issue by AdventureBear** [FreeCodeCamp/freecodecamp#340]
in the recent release (todays)  the Map looks great, very organized and easy to see.  The field guide requires a popup to see other articles.  It would look good if it matched the layout of the "Map" page.

**Comment by QuincyLarson** [comment]
Considering that we will soon have maybe hundreds of entries in our field guides, I think it will look a lot nicer if we stack them in a modal so they're out of site of normal browsing. Also, this means that the footer is still accessible without a ton of scrolling. We will definitely consider doing a map-like presentation in the future though. I hadn't even thought of this possible approach.
