### ISSUE TITLE
the Check for Palindromes does not pass

### ISSUE THREAD

**Issue by ProSerg** [FreeCodeCamp/FreeCodeCamp#3400]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
function replacer(match, p1, p2, p3, p4, offset, string) {
	console.log("P2:" + typeof(p2));
	buff = p2.split('');
	for(var i =0 ; i < buff.length; i++) {
		console.log("indx: " + buff[i] + " " + buff.length);
		if (i == Math.floor( buff.length/2 ) )
			continue;
		switch (buff[i]) {
			case '/' :
				console.log("befor  replece: " + buff[i]);
				buff[i]='\\';
				console.log(" after replece: " + buff[i]);
				break;
			case '\\':
				buff[i]="/";	
				break;	
			case '(' :
				buff[i]=")";
				break;
			case ')' :
				buff[i]="(";
				break;
			case '_' :
				buff[i]="-";
				break;
			case '-' :
				buff[i]="_";
				break;	
		}
	}
	console.log("P2:" + buff.join(''));
	return buff.join('');
}

function palindrome(str) {
  // Good luck!
  var buff ="";
  var re=/[\s,.]/gi;
  
  var array = Array.prototype.slice.apply( str.replace(re,'').split('') );
      
	
  var newstr = array.join('').toLowerCase();	
  var revstr = array.reverse().join('').toLowerCase().replace(/^.*/gi,replacer);	
	
	if (revstr == newstr) {
		return true;
	}
	
  return false;
}



palindrome("0_0 (: /-\\ :) 0-0");

```
Hello, I had created a test http://codepen.io/ProSerg/pen/WQxWxr that confirms that the text "0_0 (: /-\\ :) 0-0" is a palindrome , but it's not pass here http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes. Could you say why? Thanks.
![palindrome](https://cloud.githubusercontent.com/assets/13997176/10029526/111f81e4-617b-11e5-8ce1-11b1fb518411.png)

**Comment by awesomeaniruddh** [comment]
Thanks for posting the issue @ProSerg.

> A palindrome is a word or sentence that's spelled the same way both forward and backward, ignoring punctuation, case, and spacing.

>You'll need to remove punctuation and turn everything lower case in order to check for palindromes.

^ According to the instructions, you will need to remove *any* punctuation. You must essentially remove everything from the string besides alphanumeric characters. The challenge therefore expects you to strip everything but the four 0s in the string.

I am closing the issue because I believe this resolves it. Feel free to reopen if you feel that it didn't :)
