### ISSUE TITLE
ES6: Use getters and setters to Control Access to an Object can be passed with an empty class

### ISSUE THREAD

**Issue by MP7373** [freeCodeCamp/freeCodeCamp#34009]
On the challenge "ES6: Use getters and setters to Control Access to an Object" you can pass the challenge by simply making a class with the name "Thermostat" that contains nothing.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-getters-and-setters-to-control-access-to-an-object

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 70.0.3538.77 (Official Build) (64-bit)
* Operating System: macOs Mojave Version 10.14

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![screen shot 2018-10-31 at 9 12 21 pm](https://user-images.githubusercontent.com/11096661/47827102-37eaed80-dd52-11e8-8647-85e691bb429d.png)

**Comment by ezioda004** [comment]
We need to add additional tests to check if the class have a getter and setter and those getter and setter return correct values.

**Comment by HugoLiconV** [comment]
I'll work on that!
