### ISSUE TITLE
Example parameters in many basic bonfires contains an extra empty string

### ISSUE THREAD

**Issue by michael-krebs** [FreeCodeCamp/FreeCodeCamp#3401]
For example, the example function call at the end of Confirm the Ending is:
`end("Bastian", "n", "");`
when that function should only take two parameters. This is the case for most of the basic bonfires from Title Case a Sentence onwards.

**Comment by whereissql** [comment]
+1

**Comment by bugron** [comment]
Closing this issue as https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3699 is merged>
