### ISSUE TITLE
Unexpected Token ) but passes test

### ISSUE THREAD

**Issue by KingDad** [FreeCodeCamp/FreeCodeCamp#3402]
Challenge [Waypoint: Target HTML Elements with Selectors Using jQuery](http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
  $(document).ready(function($("button").addClass("animated bounce")) {

  });
</script>

<!-- You shouldn't need to modify code below this line -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```
![image](https://cloud.githubusercontent.com/assets/10761356/10033387/4489c8ce-6157-11e5-95aa-e065cc8dd9bc.png)

As you can see, the tests are passed and in this picture I copy pasted to make sure there wasn't an error from me writing the code myself. I checked similar problems and tried putting in ; where it might be appropriate according to javascript but the same error keeps occuring. Thanks guys!

**Comment by michael-krebs** [comment]
The `$(button)`code should be within the body of the function, not the parameters. Please ask for help in the Gitter chat before opening an issue!

**Comment by BerkeleyTrue** [comment]
@KingDad The test are not passing in your photo.

**Comment by bugron** [comment]
@KingDad thanks for posting this issue!
Your code in the script tag is incorrect:
```javascript
$(document).ready(function($("button").addClass("animated bounce")) {

});
```
it should be:
```javascript
$(document).ready(function() {
    $("button").addClass("animated bounce");
});
```

If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.
Closing this issue.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
