### ISSUE TITLE
It won't recognize both classes.

### ISSUE THREAD

**Issue by JasperWW** [FreeCodeCamp/FreeCodeCamp#3404]
Challenge [Waypoint: Create a Bootstrap Headline](http://freecodecamp.com/challenges/waypoint-create-a-bootstrap-headline) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h3 class='text-center, text-primary'>jQuery playground</h3>



```

**Comment by emaclean03** [comment]
There is no comma. It's just a space when seperating classes.

**Comment by bugron** [comment]
@JasperWW thanks for posting this issue!
@emaclean03 is correct. Multiple classes are separated by **space**. For example `<a href="#" class="btn btn-primary negative-10"></a>`. Closing this issue.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by JasperWW** [comment]
Thanks a lot. I haven't done this in a while.
