### ISSUE TITLE
After I complete a challenge, I can compare my solution with FCC's recommended solution

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3406]
Ideally this would be a button like the one below (on the congratulations modal).
![](https://www.evernote.com/l/Alz42nKnoXhIVK3o04P36IyuIRaHctN5fbwB/image.png)

Edited by @bugron.
It would be great if we could have two code editors pop up side by side - one with the camper's solution and one with our recommended solution.

**Comment by evaristoc** [comment]
Following this one

**Comment by meredithmatthews** [comment]
This looks interesting, but often wiki articles have more than one code solution. Is there a "most-preferred" solution solution?

**Comment by Jago-Kosolosky** [comment]
Right now I feel this button would be a great idea even if it just opens the wiki in a new tab. Most users don't know the wiki and if we want more people to contribute they should first get to know it...

**Comment by vcooley** [comment]
I created a button in #8373 that links to the wiki on the congratulations modal.

Is this something we want until we can get a code editor to pop up side by side with a camper's solution?

**Comment by raisedadead** [comment]
/cc @FreeCodeCamp/issue-moderators 

Should we go with a initial proposal of showing two editors side by side, or go for linking just the wiki article to show up in the aside as proposed above by @vcooley 

I am in favor of two windows side by side. With the actual solution from the challenge seed and not the wiki. This should be cleaner approach as against showing the solution against which we run the `npm run test-challenges`

**Comment by theflametrooper** [comment]
@raisedadead Yeh, let's go with the two windows side by side. :shipit:
