### ISSUE TITLE
Hint button that will progressively reveal hints from wiki

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3407]
This would be similar functionally to the hint command used in our chat rooms:

![](https://www.evernote.com/l/AlwOnsotU1xEk6irl8q9zwv9tltaa0PXEz0B/image.png)

Except that it would be a button clicked within Free Code Camp.

![](https://www.evernote.com/l/AlwnZv2UWQBNAJeEfsIleJOCGJUXzM9nMSkB/image.png)

Each time you click the hint button, it would pop up the subsequent hint in a modal, until the last time, which would actually show the solution.

**Comment by bugron** [comment]
Closing this issue. Let's keep the discussion in #4119.
