### ISSUE TITLE
Way to fetch hints and solutions from our Wiki and make them usable on FreeCodeCamp.com

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3408]
#3406 and #3407 will require a reliable way to pull data from our wiki into FreeCodeCamp.com. Perhaps this could be done with AJAX using GitHub's API: http://stackoverflow.com/questions/27654854/is-it-possible-to-get-github-wiki-content-by-github-api

**Comment by bugron** [comment]
Closing this issue as we'll get hints and solutions from the respective arrays and not from the wiki.
