### ISSUE TITLE
CI: test-ci script is missing

### ISSUE THREAD

**Issue by paulywill** [freeCodeCamp/freeCodeCamp#34150]
**Describe the bug**
Builds are failing due to 'test-ci- script missing.

**To Reproduce**
1. Submit PR
2. Check the Travis CI build.

**Expected behavior**
Testing scripts should run.

**Screenshots**
![image](https://user-images.githubusercontent.com/602422/47862290-30b3f600-ddcb-11e8-8088-342c29656c11.png)

**Comment by RandellDawson** [comment]
@raisedadead Here is that error I mentioned to you earlier.

**Comment by Nirajn2311** [comment]
The PRs are failing due to command `test-ci` being remove in 4d3641ad889dd914f154ab288fa946edcd48a58f.

**Comment by paulywill** [comment]
Thank you @Nirajn2311.

**Comment by RandellDawson** [comment]
@paulywill Why did you close the issue, since it has not been resolved yet?

**Comment by raisedadead** [comment]
The resolution is to rebase the PRs that are failing. Do we have a count on those?

**Comment by paulywill** [comment]
@raisedadead @RandellDawson Sorry I thought the failed PRs were expected with the https://github.com/freeCodeCamp/freeCodeCamp/commit/4d3641ad889dd914f154ab288fa946edcd48a58f
