### ISSUE TITLE
Challenge template incorrect

### ISSUE THREAD

**Issue by NitronR** [freeCodeCamp/freeCodeCamp#34208]
**Describe your problem and how to reproduce it:**
I think the challenge template in the "How to work on coding challenges" guide [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-coding-challenges.md) is incorrect . I think there should be these lines:
```
## Challenge Seed
<section id='challengeSeed'>
```
Before this:
```
<div id='js-seed'>
```
Also there are closed section tags without corresponding open tags:
````
### Before Test
<div id='js-setup'>

```js
Test setup code.
 ```
</div>

</section>

### After Test
<div id='js-teardown'>

```js
Test tear down code.
```

</div>

</section>
````
**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-coding-challenges.md

**Comment by trilemaestro92** [comment]
I can make these changes.
