### ISSUE TITLE
Fallback challenge doesnt accept what seems to be right answer

### ISSUE THREAD

**Issue by ricardoopinto** [freeCodeCamp/freeCodeCamp#34214]
.penguin-top {
    top: 10%;
    left: 25%;
  
    /* change code below */
    background: var(--penguin-skin, black); <== what is wrong here?
    /* change code above */
  
    width: 50%;
    height: 45%;
    border-radius: 70% 70% 60% 60%;
  }
  
  .penguin-bottom {
    top: 40%;
    left: 23.5%;
  
    /* change code below */
    **background: var(--penguin-skin, black);**  <== what is wrong here?
    /* change code above */
  
THE RUNNING TESTS ANALYSIS SAY:
// running tests
Apply the fallback value of black to the background property of the penguin-top class.
Apply the fallback value of black to the background property of the penguin-bottom class.
// tests completed

**Comment by huyenltnguyen** [comment]
Hi @ricardoopinto, thanks for reporting! Please add the link of the challenge to your post so it's easier for others to follow.

**Comment by meda123** [comment]
Hi- I would love to work on this issue once @ricardoopinto shares the link to the challenge.

**Comment by ArielLeslie** [comment]
@ricardokojo The code above does not satisfy the challenge requirements. For help finding a solution to challenges, please create a post in [the FCC forum](https://www.freecodecamp.org/forum/) rather than opening an GitHub Issue.

**Comment by ricardokojo** [comment]
> @ricardokojo The code above does not satisfy the challenge requirements. For help finding a solution to challenges, please create a post in [the FCC forum](https://www.freecodecamp.org/forum/) rather than opening an GitHub Issue.

I believe I was mentioned by mistake :)

**Comment by ArielLeslie** [comment]
Sorry about that. Bad autocomplete. I was trying to mention @ricardoopinto

**Comment by RandellDawson** [comment]
I am closing this issue, due to it not actually being a bug.
