### ISSUE TITLE
Wiki request - rewrite and simplify explanation of Arguments object

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3421]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments

**Comment by abhisekp** [comment]
Close this issue as resolved https://github.com/freecodecamp/freecodecamp/wiki/js-arguments

> NOTE: I've not written the wiki page.

**Comment by bugron** [comment]
@abhisekp thanks. Closing as the article is created.
