### ISSUE TITLE
Basic Algorithm Scripting - Truncate a String

### ISSUE THREAD

**Issue by gxcad** [freeCodeCamp/freeCodeCamp#34239]
**Describe your problem and how to reproduce it:**
The solutions in the guide do not appear to work. The logic is questionable, as the solutions speak of subtracting 3, which doesn't seem to make any sense. Perhaps the solution is to a variation of this problem that has since been modified.

If I may suggest an alternative solution that I find actually works:
function truncateString(str, num) {
  return str.length > num ? str.slice(0, num) + '...' : str;
}

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-algorithm-scripting/truncate-a-string/

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 63.0.1
* Operating System: MacOS Mojave 10.14.1

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ezioda004** [comment]
Hi @gxcad,

Thanks for opening this issue. 
This problem has been fixed in one of the latest PR https://github.com/freeCodeCamp/freeCodeCamp/pull/34228. The updated solution will be pushed to production soon.

Closing this issue.

Happy coding.
