### ISSUE TITLE
Referring to ... as an operator

### ISSUE THREAD

**Issue by kinopotato** [freeCodeCamp/freeCodeCamp#34240]
so the rest or spread is referred to as an operator but I've been informed that it's not.
You can see it in the following places (both coding challenges and guides)
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-the-rest-operator-with-function-parameters/
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/es6/use-the-rest-operator-with-function-parameters/
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-the-spread-operator-to-evaluate-arrays-in-place/
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/combine-arrays-with-the-spread-operator/

There's probably some more, I stopped checking there.

**Comment by thecodingaviator** [comment]
The `...` is in fact an operator only afaik and those places have the correct terms. Check here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**Comment by ezioda004** [comment]
Spread is fine, but in the ECMAScript specification, rest is refereed as "Rest Parameter".
Also, in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) Rest isnt under "operators".

With Object/Array destructuring they both are referred as "Spread/Rest properties". [Source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Rest_in_Object_Destructuring).

Perhaps updating "Rest Operator" to "Rest Parameter" would be better.

**Comment by martendegroot** [comment]
MDN seems to call it a spread operator as well: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators#Spread_operator .

I think this name is perfectly legal to use. To me, starting to call it a parameter would be more confusing (it's being used as a function -> operator).

**Comment by ezioda004** [comment]
Spread and Rest are different things (albeit denoted by same token).

In functions `...args` is used as a parameter and hence Rest *parameter*.

**Comment by martendegroot** [comment]
Yes, with the rest parameter I'm on the same page. Perhaps replace those and keep the spread as is? I could write a PR for that I think

**Comment by ezioda004** [comment]
Yes, I'm fine with keeping spread as is and updating the "Rest Operator" to "Rest Parameter".

Lets get some more discussion on this then you can open a PR.

**Comment by Nwachuks** [comment]
Pls, the last assertion test still fails to pass even after naming the parameter (...args).

**Comment by ezioda004** [comment]
@nwachuks Can you give the whole code and which challenge you're unable to pass the test?

**Comment by RandellDawson** [comment]
We are currently seeking assistance from contributors (first timers are welcome) to help change the wording from "Rest Operator" to "Rest Parameter" for this challenge.

**Comment by dnntrn** [comment]
Hi! If someone isn't already working on this, I would like to take it.

**Comment by alialooooosh055455** [comment]
1.577287066246057

**Comment by alialooooosh055455** [comment]
@alialooooosh055455

**Comment by ezioda004** [comment]
@dnntrn Doesnt seem like, you're good to go!
If you need help, feel free to ask here or visit our [contributors room](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by alialooooosh055455** [comment]
IMEI: 354737082070508
SV: 01
Phone Number: 
ICCID: 89962011000185464544
IMSI: 416011018546454
Mac Address: 8C:F5:A3:2F:0F:6C

**Comment by dnntrn** [comment]
@ezioda004 Hey! I think I got them all. Not sure if I missed some, but I checked the guides and challenges under ES6, projects, and certifications. Pull Request submitted.

**Comment by thecodingaviator** [comment]
@dnntrn Check [this link](https://github.com/freeCodeCamp/freeCodeCamp/search?q=%22rest+operator%22&unscoped_q=%22rest+operator%22) . There are 28 files in this repo where `rest operator` comes up

**Comment by nicholastka** [comment]
@dnntrn Nicely done. I have no idea what you guys are talking about.

**Comment by theproactivedev** [comment]
Hi! I'm a first timer hoping I can contribute here. Is this already taken including the 28 files? Thanks.

**Comment by dnntrn** [comment]
@theproactivedev Hey! I'm still working on this, but I'll let you know if I need help. Thanks!

**Comment by theproactivedev** [comment]
@dnntrn Oh, sure! :D Thanks.

**Comment by Drithyl** [comment]
@dnntrn Still working on this?

**Comment by dnntrn** [comment]
@Drithyl yup!

**Comment by RandellDawson** [comment]
This issue was fixed with PR #35496, so I am closing it.  If anyone feels the issue has not been fixed on the master branch, feel free to request this issue be reopened.
