### ISSUE TITLE
Feature Request:  Add a 'save lesson' button

### ISSUE THREAD

**Issue by username1001** [freeCodeCamp/freeCodeCamp#34246]
Hey! :smile: 

Sometimes during a lesson, I'll think to myself: "I should return to this later". I usually forget which lesson that was, and that's my mistake, but I think it'd be great to have a "save lesson" button somewhere. Perhaps even an icon, like a star, which then appears next to the link on the curriculum menu. 
(Of course I could just remember to write it down, but it may be a useful feature for others as well).

Looking forward to hearing your thoughts. Thanks!

**Comment by thoothie** [comment]
I second this! Here's an example of what's happening and what is frustrating: http://somup.com/cFXiXhn1Nm

**Comment by moT01** [comment]
Is this still an issue @ariellehale / @username1001 - It looks like there's been somewhat of an implementation of what you two are talking about.

**Comment by username1001** [comment]
I forgot all about this. Haven't really used FCC in awhile. Just realized it was updated! This implementation seems more like a progress tracker. What I meant was more along the lines of a bookmarker/lesson saver which can be viewed by the user on their profile (or within a new route). But now that I think about it, it might be useful to just use the browser's bookmarker, or even use note-taking application. :smile:
