### ISSUE TITLE
Escape Sequences Lesson Re-write

### ISSUE THREAD

**Issue by 7heM1sf3t** [freeCodeCamp/freeCodeCamp#34248]
**Describe your problem and how to reproduce it:**
Instructions are somewhat unclear, not concerning what's being taught but rather the format in which the solution is supposed to be in upon submission.  

I've edited a copy of the lesson, but in doing so, I reworded the solutions and now I don't know enough about unit tests to fix that part of it.  I think I did the "text" lines correctly but I'm not sure whether the lines containing "assert" should be edited in that file or that those lines are links and I need to be looking around for a file in the "test" folder.  

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/escape-sequences-in-strings

https://github.com/7heM1sf3t/freeCodeCamp/blob/7heM1sf3t-patch-1/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/escape-sequences-in-strings.english.md

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: no idea
* Operating System: mac high sierra

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
Almost all the `testString`s would have to be rewritten and even a few of the existing `text` with the way you have tried to restructure the instructions and tests.  For example, the first test (below) would  not make any sense if you are going to use strings like `Some text on the first line` which has spaces in the string.  
>`<code>`myStr`</code>` should not contain any spaces 

This is why the challenge author originally created the text on each line not to have any spaces.  It makes the challenge simpler and the tests simpler.

> Assign the following three lines of text to a variable using a single line of code.

How else would you write the solution if it was not in a single line of code anyway.

Also, you addition (below) is hard for me to figure out what you mean in that first sentence.
> Then use escape sequences to format the string back into its original form. There should be no spaces between escape sequences and the words they separate. Don't forget to tab over and escape the backslash character on line 2.

Why don't you see if you can reword the instructions or modify the description section in such a way that the original seen in the Instructions and the existing tests can still be used.  

Maybe the best way to figure out what to write in the instructions is to try an articulate exactly what part of the description and/or instructions confused you when you first attempted this challenge.  What pieces did you think were missing once you finally figured out what a correct solution was?

**Comment by moT01** [comment]
There is a number of posts on the forum about this challenge. Perhaps adding an example in there would help - something like...
here's how to put double quotes around something: `\"Hello World\"`

**Comment by RandellDawson** [comment]
I think this can be closed for now as the OP has not responded.
