### ISSUE TITLE
Rosetta Code: IBAN - wrong test arguments

### ISSUE THREAD

**Issue by iiiked** [freeCodeCamp/freeCodeCamp#34254]
**Describe your problem and how to reproduce it:**
`isValid()` is receiving incorrect arguments on tests. Try:
```
function isValid (iban) {
  console.log(iban);
  console.log(typeof iban);
}
```

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/coding-interview-prep/rosetta-code/iban/

**Comment by ezioda004** [comment]
Unable to produce locally. The tests seem to work fine.
![screenshot from 2018-11-10 04 56 57](https://user-images.githubusercontent.com/20020273/48293484-5913b280-e4a5-11e8-9120-91ec957ec7a4.png)


cc: @nikrb @ValeraS

**Comment by RandellDawson** [comment]
Closing this issue, because it has been fixed in beta. Viewable at https://www.freecodecamp.rocks/
