### ISSUE TITLE
D3: Scatterplot Example fails tests

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#34259]
**Describe the bug**
The example given for the D3 scatter plot challenge on CodePen is failing certain tests which it should not have. Only 14 out of the required 16 tests are passing.
The failing tests are namely:
`
6. The data-xvalue and data-yvalue of each dot should be within the range of the actual data and in the correct data format. For data-xvalue, integers (full years) or Date objects are acceptable for test evaluation. For data-yvalue (minutes), use Date objects.
`
and
`
12. I can see that the range of the y-axis labels are within the range of the actual y-axis data.
`

**To Reproduce**
1. Go to 'https://codepen.io/freeCodeCamp/full/bgpXyK'
2. Click on 'Run Tests'
3. Wait till the tests are completed
4. See that only 14 out of 16 tests are passing.

**Expected behavior**
Since it is an example for the campers to follow, they should be shown something in which all tests pass

**Screenshots**
![image](https://user-images.githubusercontent.com/34807532/48188766-8a389980-e364-11e8-8f1f-448b31b13d99.png)
![image](https://user-images.githubusercontent.com/34807532/48188790-94f32e80-e364-11e8-968d-3b5e2390ff71.png)

**Desktop (please complete the following information):**
 - Windows 7 x32
 - Google Chrome
 - Version 70.0.3538.77 (Official Build) (32-bit)

**Comment by username1001** [comment]
There is a slight delay in the last two tests, but they did pass for me. I'm seeing 16/16.

**Comment by moT01** [comment]
I was unable to reproduce this on Chrome or firefox - the last two tests do take an extra couple seconds. Want to give it one more try @thecodingaviator? Maybe try on another browser, there could be some zoom or extension settings messing with some on your browser perhaps.

**Comment by thecodingaviator** [comment]
Still failing on both Firefox and Chrome for me. Maybe someone else can have a look and this might be an issue with only me, although I'm still not sure why they're failing

**Comment by KaustubhD** [comment]
Hi,
I finally completed this challenge today and the cases were failing for me too. (14/16 passed)
The reason is difference in timezones.
The Date object taken here although made through UTC, changes to local timezone and thus producing different times as compared to the dataset.
![Screen Shot 2019-05-17 at 23 40 37](https://user-images.githubusercontent.com/22456687/57947699-3901f780-78fd-11e9-842e-2513909eea19.png)

Proposal: 
I made it so it is timezone free (hopefully)
[Pen Link](https://codepen.io/KaustubhD/full/NVdmLY)

**Comment by thecodingaviator** [comment]
@KaustubhD Can you have a look at tests in https://github.com/freeCodeCamp/testable-projects-fcc and update the tests there to get this to work?

**Comment by KaustubhD** [comment]
Sure i can. But can you tell me how would i run/test these tests ?

**Comment by thecodingaviator** [comment]
@KaustubhD I guess that's the best way to do it without breaking all the previous projects

**Comment by KaustubhD** [comment]
Alright then, i'll give it a shot.

One more thing, how do i test the tests ?

**Comment by thecodingaviator** [comment]
I think you should get in touch with @raisedadead about that. You'll find him on the [Gitter chat room](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by thecodingaviator** [comment]
@lasjorg I guess you’re looking after updating the CodePens too. Could you please chime in?

**Comment by lasjorg** [comment]
I can't reproduce it, the example project is passing all the tests for me.

**Comment by KaustubhD** [comment]
@lasjorg You can just change your system timezone and reload.

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo can you validate the pen proposed here. We could update ours (to not break the links from this updated pen)?

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, sure thing! I'll get right on it.

**Comment by scissorsneedfoodtoo** [comment]
@thecodingaviator, thank you for bringing this to our attention. This seems to be a problem for IST and other timezones that are offset by 30 or 45 minutes. Also, thank you @KaustubhD for your investigation. Fortunately I was able to use your pen above as inspiration for a fix here: https://codepen.io/scissorsneedfoodtoo/pen/NVvBYe

All I did was remove the conversion to UTC so the data isn't affected by time zones. After doing that and changing my system's time zone the graph data remains the same after reloading the page.

**Comment by thecodingaviator** [comment]
@scissorsneedfoodtoo I guess it works now
![image](https://user-images.githubusercontent.com/34807532/58044424-533a1080-7b5d-11e9-8ab6-3099625421c4.png)

I'm closing the issue. I guess there's no further clarification need. Right @scissorsneedfoodtoo ?

**Comment by scissorsneedfoodtoo** [comment]
@thecodingaviator, yes, I think this is safe to close for now. Great catch here! Thank you again for reporting it.

**Comment by ManasMahanand** [comment]
I came across this same problem while working on #41967

And as mentioned, changing timezone fixes it. But I think there should be a proper fix.

**Comment by ManasMahanand** [comment]
I run into this issue when running yarn test locally.

![image](https://user-images.githubusercontent.com/41644157/117946029-89659180-b32c-11eb-87e9-e2a7183af2c5.png)

**Comment by ManasMahanand** [comment]
Seems like @scissorsneedfoodtoo's fix has been removed. When I made the same fix as was mentioned by him, it works!

Removed conversion to UTC on line 57, and no errors popup.
