### ISSUE TITLE
Javascript Algorithms and Data Structures: Solution is wrong

### ISSUE THREAD

**Issue by lauras5** [freeCodeCamp/freeCodeCamp#34270]
Solution to 'Truncate a String' Challenge in Javascript Algorithms and Data Structures >Basic Algorithm Scripting>Truncate a String should be below:

`function truncateString(str, num) {`
   `if(str.length <= num) {`
    `return str;`
  `} else {`
   ` return str.slice(0, num) + '...'`
  `}`
`}`

The above works, but when you click on the 'HINT' link and see the solution, it gives you two incorrect solutions. I propose changing it to the above since it is what is in the actual solution in the documentation. I wasn't able to find the source file to fix it myself.

**Comment by RandellDawson** [comment]
Hi @lauras5, 

Thanks for opening this issue.

This issue has been reported. #34216

The problem has been fixed in one of the latest PR #34228. The updated solution will be pushed to production soon.

Closing this issue.

Happy coding.
