### ISSUE TITLE
Certain guide articles do not show up even though they have complete files

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#34286]
**Describe your problem and how to reproduce it:**
Certain guide articles like this one: https://guide.freecodecamp.org/certifications/front-end-libraries/react do not show in the guide even though they have fully complete description files like at here: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/certifications/front-end-libraries/react/index.md

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 70 (x32)
* Operating System: Windows 7 (x32)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/34807532/48299844-20052d80-e4f9-11e8-9f18-8f56c846f0c0.png)

![image](https://user-images.githubusercontent.com/34807532/48299847-285d6880-e4f9-11e8-812a-2af8251fff26.png)

**Comment by Nirajn2311** [comment]
@thecodingaviator these files have data in them, but they still haven’t been pushed to production yet.

**Comment by ezioda004** [comment]
As @Nirajn2311  said it will be added to production soon.
