### ISSUE TITLE
Side menu of guide not working properly

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#34288]
**Describe your problem and how to reproduce it:**
The side nav menu of the guide.freecodecamp.org does not work properly, for example, over here, there are two issues,

1. All subsections of the certifications folder below Data Visualization are not visible, the link to them is not there.

2. Even though, I'm on the Chef page as indicated by the link in the address bar and the article, the nav menu is still stuck on the article folder I was viewing before, i.e. Data Visualization.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 70.0.3538.77 (Official Build) (32-bit)
* Operating System: Windows 7 x32

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/34807532/48299940-67d88480-e4fa-11e8-8ea7-97fd4977d083.png)

**Comment by saravannann** [comment]
Does that mean whenever you click on a side menu, you expect the other opened side menus to toggle-off to get closed and only the clicked sub-menu to be active at any point of time?

**Comment by thecodingaviator** [comment]
> Does that mean whenever you click on a side menu, you expect the other opened side menus to toggle-off to get closed and only the clicked sub-menu to be active at any point of time?

Yes, I think that's hoe every normal Nav menu should work

**Comment by icatat** [comment]
I am not really able to reproduce this issue, or I might not get it. @thecodingaviator do you think this issue has been fixed?

**Comment by thecodingaviator** [comment]
See the problem is that I'm on the chef article but the nav is still on data visualization . its still on my side

**Comment by icatat** [comment]
@thecodingaviator I think now I understand what you are talking about.

**Comment by thecodingaviator** [comment]
The issue seems to be fixed now. As I can see on freecodecamp.rocks today (28/02/2019), I'm not able to replicate the issue any longer, so am closing it
