### ISSUE TITLE
Wiki request - rewrite and simplify explanation of String.concat()

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3429]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/concat

**Comment by anusahu13** [comment]
String.concat() method combines the text of two strings and returns a new string.

Example : 
var str1 = "Hello";
var str2 = "World";
var str3 = str1.concat( str2 );
document.write("Concatenated String :" + str3); 

OUTPUT =>  Concatenated String : Hello World

**Comment by faizaanceg** [comment]
Can I take this?

**Comment by abhisekp** [comment]
@faizaanceg to where? :stuck_out_tongue: 

Feel free to. :smiley:

**Comment by Rafase282** [comment]
This is a template for the task https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/wiki-js-template

Feel free to look at other similar pages to the one you would create.
