### ISSUE TITLE
Edit zipline instructions

### ISSUE THREAD

**Issue by sfrapoport** [FreeCodeCamp/freecodecamp#343]
Some of the instructions have duplicate information (e.g. link to twitch API), others have broken links.

**Comment by DoRm** [comment]
The twitch API zipline also has the Get setup for ziplines video instead of the Twitch API one.

**Comment by ChillTrain** [comment]
@sfrapoport Can you reference specifically where the duplicate information and broken links are?

**Comment by sfrapoport** [comment]
Sorry about that, I was going to offer to fix it myself tomorrow, so I didn't bother to list them, if that's ok, I'll make a pull request tomorrow?

**Comment by QuincyLarson** [comment]
I can go ahead and fix them. I'm checking now.
