### ISSUE TITLE
Guides are still deployed from freecodecamp/guide

### ISSUE THREAD

**Issue by bmackinney** [freeCodeCamp/freeCodeCamp#34307]
This may be known/tracked somewhere but I could not locate it. 
**Describe your problem and how to reproduce it:**
https://guide.freecodecamp.org reflects https://github.com/freeCodeCamp/guide repository

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/wordpress is https://github.com/freeCodeCamp/guide/blob/master/src/pages/wordpress/index.md
instead of https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/wordpress/index.md

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: latest
* Operating System: Mac

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/646061/48361922-bd7a7180-e65f-11e8-8e76-b4808f03ffda.png)

**Comment by thecodingaviator** [comment]
No, afaik the guide is nor being deployed from this repo but the new changes have not yet been pushed to production. They soon would be. This issue can be closed :)
