### ISSUE TITLE
Make formatting for guide articles compulsory

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#34319]
What I have been seeing is that we are accepting PRs which are not following the template given at https://www.freecodecamp.org/forum/t/freecodecamp-algorithm-challenge-template-guide/14272 . I think for new PRs maybe all those submitted starting from 20/11/2018, if not following this template should be rejected.

**Comment by thecodingaviator** [comment]
I agree that the template is only for the JS algorithm challenges, but uniformity over the whole guide would be really good.  In the meantime, I am manually porting over as many of these articles as I can to the template. Working on the React section right now.

**Comment by ezioda004** [comment]
I believe this has been discussed in the past with Quincy and the gist was that we're for now, not following any templates for the guide articles, including the solution.

The template mentioned in the forum article was done by one person only, thats why they are similar and have same format.

**Comment by thecodingaviator** [comment]
Okay, but I think that now after this Hacktoberfest should be a nice time to reconsider this, delaying it would mean that later more articles would have to be ported over manually by a fewer number of people

**Comment by ezioda004** [comment]
Closing as per https://github.com/freeCodeCamp/freeCodeCamp/pull/34320#issuecomment-438498667.
