### ISSUE TITLE
ES6: Write Concise Declarative Functions with ES6 Will faill if normal functions are used in commented code

### ISSUE THREAD

**Issue by MisanthropeMurphy** [freeCodeCamp/freeCodeCamp#34333]
**Describe your problem and how to reproduce it:**
I commented out the code and then followed the new syntax for the challenge, but because the commented out code had normal function declaration it didn't pass. 

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/write-concise-declarative-functions-with-es6

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome 
* Operating System: Mac OS High Sierra

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
// change code below this line

const bicycle = {
  gear: 2,
  setGear(newGear) { 
    "use strict" 
    this.gear = newGear
  }
}

/*
const bicycle = {
  gear: 2,
  setGear: function(newGear) {
    "use strict";
    this.gear = newGear;
  }
};
// change code above this line
bicycle.setGear(3);
console.log(bicycle.gear);
*/

**Comment by ezioda004** [comment]
Hi,

We used regex to match "function" keyword in the code but this instance can be fixed.
I'll take a stab at it.

**Comment by dnntrn** [comment]
@ezioda004 I think this issue occurs with a lot of the challenges. For an example, [https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/explore-differences-between-the-var-and-let-keywords](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/explore-differences-between-the-var-and-let-keywords) and [https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-operator-to-reassign-array-elements](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-operator-to-reassign-array-elements)

Can a statement just be left in the description saying to not use the keyword even as a comment?

**Comment by RandellDawson** [comment]
@dnntrn A better way is how we solved other such problems.  We stripped all the comments out with a regular expression and then validated the user did not use what they were not supposed to.  I just created 
 PR #35906 to fixed this issue,
