### ISSUE TITLE
Confusing Instructions in Applied Visual Design Challenge

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#34357]
**Describe your problem and how to reproduce it:**
In the Applied Visual Design challenge - Learn about tertiary colors, the instructions state that orange and raspberry are not browser recognized color names, even though orange is in fact, identifiable by modern major browsers, the problem I think, lies in the fact that the hex code given for orange i.e. `#FF7D00` and `orange` are different colors, which means that `orange` leads to a color which is visually orange, but different to a computer.

There can be 2 things we can do to solve this:

1. Change the challenge instruction, or,
2. Change the tests for the challenge

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/learn-about-tertiary-colors

**Comment by RandellDawson** [comment]
@beaucarnes Would you have any input on this issue?

**Comment by beaucarnes** [comment]
This does need to be fixed. It should be clarified that while 'orange' is a color name recognized by browsers, the shade of orange does not exactly correspond to the official tertiary orange color. After a little research, it seems that our hex code for the tertiary orange could be off a little. According to this [wikipedia entry](https://simple.wikipedia.org/wiki/Color_wheel), it should be #FF7F00. Though the exact hex code does not impact the actual lesson of this challenge.

I can fix this.

**Comment by beaucarnes** [comment]
Both the orange color and raspberry colors were incorrect.
Orange was `rgb(255, 125, 0)`. But since 255/2 = 127.5, it should be `rgb(255, 127, 0)`. Same for the raspberry color.

I fixed this in my PR.
