### ISSUE TITLE
Bad UX for splitter of description's and code's panels

### ISSUE THREAD

**Issue by T1mL3arn** [freeCodeCamp/freeCodeCamp#34358]
**Describe the bug**
It is hard to catch the splitter between panels to drag it. Scrolling controls on the splitter makes a bad user experience if one tries to drag it.

**To Reproduce**
1. Go to challenge page like this - https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/record-collection/
2. Try to drag separator (which is between a code panel and a description)
3. Very hard to catch it by mouse because FF draws a scroll-related ui controls.

**Expected behavior**
The separator should be clicked very easy.

**Screenshots**
Here are screenshots which demonstrate cursor style on top of the scroll controls and on top of the separator. 
Note: width of the separator is set to 25px for convenience.
![no resize on top of scroll controls](https://user-images.githubusercontent.com/9349164/48658554-ce781800-ea8f-11e8-9ba0-f51306f9efe7.jpg)
![resize cursor](https://user-images.githubusercontent.com/9349164/48658557-d59f2600-ea8f-11e8-8018-7872505243f2.jpg)

**Desktop:**
 - OS: Win7
 - Browser: Firefox 63

**Additional context**
The separator can be dragged even if scroll-controls on top of it (FF only). But this is not obviously since user will be looking for resize-cursor style and that style won't appear if the mouse is over scroll-controls. In Opera(v56) this even worse - the separator cannot be dragged with scroll controls.

**Comment by thecodingaviator** [comment]
I think the trade-off of making it easier to hold has been made to make it uniform with the rest of the website and other websites and in favor of not making it so 'ugly'.
