### ISSUE TITLE
Inconsistent Indentation in Understanding Boolean Values

### ISSUE THREAD

**Issue by akkatracker** [freeCodeCamp/freeCodeCamp#34367]
**Describe your problem and how to reproduce it:**
I feel as though this question's starter code is inconsistent with all the surrounding questions, where the body of functions are indented. 

The `return false` (and potentially the comments above and below it) should be indented to make the challenge consistent, and encourage good style. 

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/understanding-boolean-values

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 72.0.3613.0 (Official Build) canary (32-bit)
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/2032746/48669603-4f044a80-eb5c-11e8-9ce0-231857fd058a.png)

**Comment by ezioda004** [comment]
Hi @akkatracker,

I agree, this is small bug. Would you be interested in fixing this?

**Comment by akkatracker** [comment]
I'm happy to leave it open for a first timer ☺

**Comment by mikeattara** [comment]
Hi @ezioda004 

I will like to take up the task

**Comment by ezioda004** [comment]
@akkatracker Go ahead. Feel free to ask any questions if you get stuck.

**Comment by mikeattara** [comment]
Hi @akkatracker and @ezioda004  I have fixed the inconsistency

**Comment by ezioda004** [comment]
Fixed via #34373
