### ISSUE TITLE
Run the Tests not working

### ISSUE THREAD

**Issue by mccoymap** [freeCodeCamp/freeCodeCamp#34368]
**Describe your problem and how to reproduce it:**
Hi all. The 'Run the Tests' button doesn't appear to be working. I have entered <h1>Hello World</h1> but when I click the Run the Tests button, I get the '// running tests' message. I tried to clear the cache but this does not seem to have worked. Does anyone have any suggestions? Thanks and all the best.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements/

**Tell us about your browser and operating system:**
* Browser Name: Microsoft Edge
* Browser Version: 42.17134.1.0
* Operating System: Windows

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Nirajn2311** [comment]
@mccoymap could you put a screenshot of your code?

**Comment by ezioda004** [comment]
Hi @mccoymap,

Thanks for opening this issue.
We currently do not support Edge. Please use Chrome or Firefox.

**Comment by mccoymap** [comment]
Thanks guys! All working in Chrome as you suggested. All the best
