### ISSUE TITLE
Wiki request - rewrite and simplify explanation of String.split()

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3436]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split

**Comment by matty22** [comment]
Wiki page for str.split() now exists.

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/String.split%28%29

**Comment by ltegman** [comment]
Thanks!
