### ISSUE TITLE
Update the standard email sent upon completing all certifications

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#34380]
**Describe the bug**
Currently when a camper completes all the certifications, we send them an email from team@freecodecamp.org. We can now simplify this logic to just send the email once they've claimed the Full Stack Developer Certification, since that means they will have completed all 6 of the non-legacy certifications.

Also, could we have this email come from quincy@freecodecamp.org instead - that way I will be able to respond to the email much faster.

The email looks fine.

**Comment by thecodingaviator** [comment]
@QuincyLarson My 2 cents on that- maybe we could have the replies forwarded to your email. In my opinion, having them sent from your email address seems a bit unprofessional.

**Comment by Bouncey** [comment]
@thecodingaviator As Quincy is the founder of freeCodeCamp.org, it seems fitting for a congratulatory email to come from him. It seems more personable in my opinion.

**Comment by Nirajn2311** [comment]
@thecodingaviator when you get the mail from the founder himself, you get that sense of achievement or accomplishment. So I think it is better if the mail itself can from Quincy.

**Comment by RA9** [comment]
@Nirajn231 I agree with you , it feel more idea and personal when you've been congratulated by the founder.
I think it will be more professional if  you guys will combine the congratulatory message like "On behalf of the FreeCodeCamp community and team we congratulate you on your success for completing the fullstack certification".

**Comment by thecodingaviator** [comment]
When you put it that way, it makes more sense.

**Comment by thecodingaviator** [comment]
So yeah, I think that te proposal is great

**Comment by HugoLiconV** [comment]
I'm working on it!

**Comment by farisoft** [comment]
@HugoLiconV - thanks for your contribution!
