### ISSUE TITLE
Wiki request - rewrite and simplify explanation of String.toLowerCase()

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3439]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase

**Comment by matty22** [comment]
Wiki page now exists: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/String.toLowerCase%28%29
