### ISSUE TITLE
In the Rosetta Code challenges, the "General FizzBuzz" challenge has broken tests

### ISSUE THREAD

**Issue by alexch** [freeCodeCamp/freeCodeCamp#34407]
**Describe your problem and how to reproduce it:**

the General Fizzbuzz challenge has broken tests, including some ugly `JSON.stringify` code instead of readable, functional tests.

(It seems to be some over-generalized code that worked on the old platform but no longer works inside the "learn" app. I think I can fix it -- please feel free to assign it to me.)

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/coding-interview-prep/rosetta-code/general-fizzbuzz/

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 70.0.3538.102 (Official Build) (64-bit)
* Operating System: MacOS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![screen shot 2018-11-20 at 4 01 40 pm](https://user-images.githubusercontent.com/8524/48803541-3fae0a00-ece0-11e8-983c-ebc6b5b7e725.png)

**Comment by scissorsneedfoodtoo** [comment]
@alexch, great catch! Thanks for pointing this out. freeCodeCamp/curriculum#277 was merged just before the major restructuring that's been going on, so it may not have made it into the new npm package / production. This is a great reminder for me to check this and the other problems out locally now that they've been moved here.

**Comment by ezioda004** [comment]
@scissorsneedfoodtoo Tested it locally, its fixed it master.

**Comment by scissorsneedfoodtoo** [comment]
Checked this out and it seems the changes from freeCodeCamp/curriculum#277 carried over to master. Hopefully they make their way to production soon

**Comment by alexch** [comment]
https://learn.freecodecamp.org/coding-interview-prep/rosetta-code/general-fizzbuzz/
is still busted :-(

**Comment by crossjames934** [comment]
Is this being addressed? I too would be happy to help fix it but sounds like alexch has already got the solution.

**Comment by RandellDawson** [comment]
@crossjames934 See @scissorsneedfoodtoo's comment above.  Whenever you see the label `status: resolved \ shipping`, it means it has been fixed, but not released to production.
