### ISSUE TITLE
add introductory text to intermediate algorithm scripting

### ISSUE THREAD

**Issue by nemanjajeremic** [freeCodeCamp/freeCodeCamp#34401]
**Describe your problem and how to reproduce it:**
There is no introductory test to this part of the challenges, only a stub. 

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting

**Tell us about your browser and operating system:**
* Browser Name:  Mozilla Firefox
* Browser Version: 63.0.3
* Operating System: Win10 64-bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![gg](https://user-images.githubusercontent.com/4604310/48771904-03b87c00-ecc3-11e8-8fb4-58a91b724eb3.png)

**Comment by nemanjajeremic** [comment]
Very well, closing this issue.

**Comment by thecodingaviator** [comment]
Let this issue remain open till the PR fixing it is merged
