### ISSUE TITLE
Wiki request - rewrite and simplify explanation of String.toUpperCase()

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3441]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toUpperCase

**Comment by matty22** [comment]
Wiki page now exists: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/String.toUpperCase%28%29
