### ISSUE TITLE
The page becomes unresponsive.

### ISSUE THREAD

**Issue by irshadjsr21** [freeCodeCamp/freeCodeCamp#34428]
**Describe your problem and how to reproduce it:**
Whenever I write a few lines of code (Almost 3) in the provided area the page becomes unresponsive and after a while chrome displays a message saying "Aw, Snap! Something went wrong while displaying this webpage."

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/react/create-a-component-with-composition/

**Tell us about your browser and operating system:**
* Browser Name:  Google Chrome
* Browser Version: 70.0.3538.102
* Operating System:  Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![untitled](https://user-images.githubusercontent.com/40335357/48921345-40ec5c00-eec5-11e8-98a5-61bc340fcb39.png)

**Comment by Cyb3rN4u7** [comment]
I have tried to reproduce the described problem but did not found any weird behavior.
Perhaps you could share what you have typed to further test this out

### Tested in:
- OS: Windows 10 👍 
- Chrome 70.0.3538.102 👍 
- Firefox 63.0.3 👍

**Comment by Nirajn2311** [comment]
@Cyb3rN4u7 when you try to put the correct answer, the browser hangs and crashes.

**Comment by irshadjsr21** [comment]
@Nirajn2311 Exactly!!

**Comment by ezioda004** [comment]
Hi @irshadjsr21,
I tested and seems to worked fine for me. Can you tell what were you typing when the browser crashed?

**Comment by Cyb3rN4u7** [comment]
@Nirajn2311 i didn't experience any problems by typing it.
That's weird

**Comment by irshadjsr21** [comment]
![untitled](https://user-images.githubusercontent.com/40335357/48937366-daeaed80-ef33-11e8-953d-61f9a9341ad2.png)
