### ISSUE TITLE
Prevent users from copying and pasting the code for "Manipulating Complex Objects"

### ISSUE THREAD

**Issue by akkatracker** [freeCodeCamp/freeCodeCamp#34440]
**Describe your problem and how to reproduce it:**
Open for discussion, but I feel as though being able to copy and paste the previous object in the array and pass the tests defeats the purpose of this challenge

Perhaps there should be another test(s) to check that the new album added is unique or at lease somewhat different

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/manipulating-complex-objects/

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by thecodingaviator** [comment]
As far as I understand, even if the student copy-pastes, it isn't defeating the purpose because they still understand what they are doing and how it is working. As for the instructions, it requires the album to be new and not unique so the current instructions are designed like that too

**Comment by RandellDawson** [comment]
I concur with @thecodingaviator regarding the challenge intent.  If the instructions would have stated for the new album to be unique, then there would be an issue and the tests would need to be re-written. 

I am closing this issue, as there currently is no problem with the current challenge tests as it relates to the challenge intent/instructions.
