### ISSUE TITLE
Wiki request - rewrite and simplify explanation of Array.filter()

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3444]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

**Comment by abhisekp** [comment]
Close this issue as resolved https://github.com/freecodecamp/freecodecamp/wiki/js-array-prototype-filter

> NOTE: I've not written the wiki page.

**Comment by bugron** [comment]
@abhisekp thanks. Closing as the article is created.
