### ISSUE TITLE
Vague instructions in Rest Operator challenge

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#34443]
**Describe your problem and how to reproduce it:**
On this challenge, the instructions are vague, I mean what does `work in the same way` even mean? We should make the 'way' clear to the student

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-the-rest-operator-with-function-parameters

**Comment by erictleung** [comment]
Thanks for bringing this up. Yes, the wording is a bit vague.

A better one may be (emphasis added on changes)

> Modify the function `sum` with the rest operator so that **the `sum` function is able to take any number of arguments and return their sum**.

**Comment by abhishekakade** [comment]
Can I work on this one?

**Comment by ezioda004** [comment]
Sure, its all yours!
