### ISSUE TITLE
Profile HeatMap is messing up streak

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#34445]
In the screenshot below, my streaks are clearly 16 days but the counter is counting them as 14 and 1:

![image](https://user-images.githubusercontent.com/34807532/48979328-5dfc7700-f0df-11e8-93dc-39590702ba20.png)

**Comment by moT01** [comment]
closing in favor of duplicate https://github.com/freeCodeCamp/freeCodeCamp/issues/17299
