### ISSUE TITLE
Spelling Error in "wrong OTP" message

### ISSUE THREAD

**Issue by akkatracker** [freeCodeCamp/freeCodeCamp#34450]
**Describe the bug**
Received is misspelled as recieved

**To Reproduce**
Enter a wrong (or no) OTP

**Expected behavior**
Recieved should be spelled received

**Screenshots**
![image](https://user-images.githubusercontent.com/2032746/49000584-26a8cb80-f1ae-11e8-9c36-1e623146a6f3.png)

**Additional context**

**Comment by akkatracker** [comment]
I don't think this can be changed on this codebase, but I did note 4 instances where received was misspelled in the code (so maybe a first timer wants to change those)

**Comment by jeffslofish** [comment]
It appears this spelling error is coming from: https://github.com/freeCodeCamp/auth0-templates/blob/master/pages/login.html

**Comment by MMahendra001** [comment]
Can i take this one?

**Comment by akkatracker** [comment]
Sure thing go for it! Also fix the other misspellings in the source too if
you'd like
