### ISSUE TITLE
Oauth issues

### ISSUE THREAD

**Issue by 7heM1sf3t** [freeCodeCamp/freeCodeCamp#34454]
**Describe the bug**
Ok so this is probably going to be as confusing to explain as it was to navigate but here it goes.  The dual login/signup window can create a problem with retrieving an account when someone has multiple oauths from the same provider.  I probably just created & deleted half a dozen accounts because I swapped browsers and forgetting which google profile I used, I signed into the wrong initially.  This created a new account automatically.  Deleting it, I tried to sign in again and it automatically sign me in to the same gmail account, creating another profile for that email.  Deleting it again, I next tried both signing in with a different Oauth provider and clearing my cache.  It wasn't until I navigated to google's home page and swapped profiles there that I was given the option here to sign in with a different google account.  That wouldn't have been so hard to figure out on chrome, but I switched back to safari and I haven't heard of any other way to swap profiles.  Other sites that have the login and signup separate seem to get by because once the server figures out that there's no account by that profile it asks whether the user wants to create one or use a different account.  

**To Reproduce**
1. Create two accounts from Google
2. Sign in with account
3. Swap to browser other than chrome
4. Sign in with other account
5. Delete account and attempt to sign in to the account initially created.

**Expected behavior**
One would think that deleting the second account, trying to login again would either give you the option to pick which google account again or recognize there isn't an account and then ask.  Part of that is most likely an issue with google's authorizations but having run into it before on other websites, it didn't seem quite so tasking to mediate.   

**Desktop (please complete the following information):**
 - HighSierra 10.13
 - Safari 12.0

**Comment by raisedadead** [comment]
Unfortunately we do not control the behaviour of the third party auth providers like Google. We simply use the the OAuth flow, its upto the provider to present the account to the user. 

For us, its simply the validated email that is returned to us, which we use to identify the user record.

I don't think we can differentiate between these flows, before hand.
