### ISSUE TITLE
Wiki request - rewrite and simplify explanation of Array.indexOf()

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3446]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

**Comment by abhisekp** [comment]
Close as issue is resolved https://github.com/freecodecamp/freecodecamp/wiki/js-array-prototype-indexof

> NOTE: I've not written the wiki

**Comment by bugron** [comment]
@abhisekp thanks. Closing as the article is created.
