### ISSUE TITLE
[Discuss] saving code on the fly in our database

### ISSUE THREAD

**Issue by jimages** [freeCodeCamp/freeCodeCamp#34476]
Many user complain that their code get lost when they close their broswers. Shall we consider save user code on the fly? My opinion is that we can set a demand (2000 read/write per seconds for example) and fork a new branch to experiment with other powerful programming language and tools. Only can we merge when our performance meet our demands.

## assumption

1. the string is less than 10KB for each snippet
2. It doesn't matter if user's code will be save later after they save code in server case the lastest code is saved in the browser. we should keep. That means we should only keep the eventually consistent with the latest code.
3. Code maybe not as important as the other data and can save in user local database. We can suffer bit loss of code.

## Proposal on the architecture

We should try to save users code only when they try to test their code. After the website receive the requests, it save the code in the MQ and responded with OK. So the browsers can run very fast. and we have consumers to save the codes in our databases.

## Optimization

Since we have a MQ in our cluster. We can upsert many records at the same time. We can also delay the [Journaling](https://docs.mongodb.com/manual/core/journaling/) and turn off the [locking](https://docs.mongodb.com/manual/administration/analyzing-mongodb-performance/)

**Comment by jimages** [comment]
https://github.com/freeCodeCamp-China/learn/issues/26

**Comment by dgisser** [comment]
@jimages I think it would be good to work on #34540, which does this locally but not on the fly. Then we can work on making it save on the fly, then on server if necessary.

**Comment by Bouncey** [comment]
The current state of `learn`, even before we retired the `learn` repository has this feature enabled. 

I think the confusion is coming from that, when a user submits the completed challenge to the database (and that request is successful), we remove the stored code from `localStorage`.

```js
// client/src/templates/Challenges/redux/code-storage-epic.js

/*
  store is a package for interacting with localStorage
  Code omitted for brevity 
*/

function clearCodeEpic(action$, state$) {
  return action$.pipe(
    ofType(types.submitComplete, types.resetChallenge),
    tap(() => {
      const { id } = challengeMetaSelector(state$.value);
      store.remove(id);
    }),
    ignoreElements()
  );
}

function saveCodeEpic(action$, state$) {
  return action$.pipe(
    ofType(types.executeChallenge),
    // do not save challenge if code is locked
    filter(() => !isCodeLockedSelector(state$.value)),
    tap(() => {
      const state = state$.value;
      const { id } = challengeMetaSelector(state);
      const files = challengeFilesSelector(state);
      store.set(id, files);
    }),
    ignoreElements()
  );
}

function loadCodeEpic(action$, state$) {
  return action$.pipe(
    ofType(types.challengeMounted),
    switchMap(({ payload: id }) => {
      let finalFiles;
      const state = state$.value;
      const challenge = challengeMetaSelector(state);
      const files = challengeFilesSelector(state);
      const fileKeys = Object.keys(files);
      const invalidForLegacy = fileKeys.length > 1;
      const { title: legacyKey } = challenge;

      const codeFound = getCode(id);
      if (codeFound && isFilesAllPoly(codeFound)) {
        finalFiles = codeFound;
      } else {
        const legacyCode = getLegacyCode(legacyKey);
        if (legacyCode && !invalidForLegacy) {
          finalFiles = legacyToFile(legacyCode, files, fileKeys[0]);
        }
      }
      if (finalFiles) {
        return of(storedCodeFound(finalFiles));
      }
      return of(noStoredCodeFound());
    })
  );
}

export default combineEpics(saveCodeEpic, loadCodeEpic, clearCodeEpic);
```

Removing `type.submitComplete` from `clearCodeEpic` would persist users code in local storage indefinitely.

**Comment by Bouncey** [comment]
It could also be that your users are using a 'private browsing' feature in their browser, which could negate `localStorage` all together

**Comment by dgisser** [comment]
@Bouncey that code would save on submit, but wouldn't it be better to save to local storange on the fly? Also is there a gitter or something that allows more direct communication?

**Comment by raisedadead** [comment]
@dgisser sure here [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by DzmitryUr** [comment]
Currently the code is saved into `localStorage` after pressing 'Run the Tests' button. Probably it would be better to save the code into `localStorage` on change `textarea` event? That can save the data if the user does not press the button and closes the browser.
I do not see big advantage in saving code into DB on the fly. Probably it can be useful in some cases, but it causes a lot of requests to the server and DB.

**Comment by raisedadead** [comment]
We are not going to be implementing any solution storage related features any time soon. A PR is welcome however, thanks for reporting and discussion.
