### ISSUE TITLE
Feature request: Option to store progress and solutions offline

### ISSUE THREAD

**Issue by prahaladbelavadi** [freeCodeCamp/freeCodeCamp#34479]
With the inclusion of the download completed challenge button, It becomes tedious to download each one manually. An option to download all previously completely challenges at once compared to downloading them manually would be invaluable to those intending on saving their progress offline.

**Comment by ArielLeslie** [comment]
FCC does not store non-project solutions. Given the sizes of the curriculum and the user base, storing all submitted challenges would require more resources than FCC can support.

**Comment by prahaladbelavadi** [comment]
Thank you @ArielLeslie 
I was not aware of this.

Would a toggle switch that automatically downloads the completed solution upon successful submission for challenges be a suitable alternative ?

**Comment by ArielLeslie** [comment]
You can certainly float the idea and see what The Powers That Be think :D

**Comment by prahaladbelavadi** [comment]
That's a possibility @ArielLeslie 
I'll leave the [feature request] open to garner more thoughts,opinions and improvisations on it being a necessary/viable addition to freecodecamp.

Based on the discussion at https://github.com/freeCodeCamp/freeCodeCamp/issues/3855
I presume the offline mode has been put on hold until further notice.

**Comment by raisedadead** [comment]
I do not think we would have any additional ability to download solutions other than the button that you can use on each challenge.

Thanks for the request though.
