### ISSUE TITLE
Use the Reduce Method to Analyze Data

### ISSUE THREAD

**Issue by PedroS5499** [freeCodeCamp/freeCodeCamp#34505]
**Describe your problem and how to reproduce it:**
in challenge The averageRating should equal 8.675. but the array given will never do average of 8.675.
but 8.52.
there is a serial issues closed about that point, but all closed, and problem persists.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/use-the-reduce-method-to-analyze-data

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version:  70.0.3538.110 64bit
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![freecodecampissue](https://user-images.githubusercontent.com/11250367/49331210-72ce8400-f591-11e8-85af-795017b45e75.png)

**Comment by ezioda004** [comment]
Hi @PedroS5499,

Thank you for opening this issue. 

The average is indeed `8.675`. 
Note: you only need to find the average of "Christopher Nolans" movies.
There are 4 Nolans movie whose average is equal to `8.675`.

**Comment by PedroS5499** [comment]
Ohh, miss that part xD
