### ISSUE TITLE
Wiki request - rewrite and simplify explanation of Array.pop()

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3451]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/pop

**Comment by matty22** [comment]
Wiki page for array.pop() now exists.

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Array.pop%28%29

**Comment by ltegman** [comment]
Thanks for working on this! :smile: Closing since this article has been created.
