### ISSUE TITLE
Basic Node and Express - Meet the Node console Confusing Instructions For Beginners

### ISSUE THREAD

**Issue by kinopotato** [freeCodeCamp/freeCodeCamp#34518]
**Describe your problem and how to reproduce it:**
The challenge wants the user to do a console.log("Hello World"); which sounds simple enough but it doesn't specify that it has to be in the server.js but it eventually does with the error "hello world is not in the server.js" or a similar error but when you go to the server.js you see this:

/******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

It's jarring for someone who doesn't know about this language or system yet. I suggest changing "file" into "file section" or "section of the file" just to prevent confusion. As one material (the challenge page) is telling me to edit the file while the other material (the glitch material) is telling me NOT to edit the file.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/apis-and-microservices/basic-node-and-express/meet-the-node-console

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ezioda004** [comment]
I agree, we can clarify the instructions to something like:
>To get started, just print the classic "Hello World" in the console. You need to modify the `myApp.js` file.

**Comment by Good-Will-Coding** [comment]
Can I take this issue?

**Comment by kinopotato** [comment]
> I agree, we can clarify the instructions to something like:
> 
> > To get started, just print the classic "Hello World" in the console. You need to modify the `myApp.js` file.
> 
> @kinopotato The `server.js` file shouldnt be modified at all. There is `myApp.js` in which you can add `console.log()` and the latter challenges code.

If I remember correctly, that's what I did first. I did the console.log on the myApp.js and it gave me the error of "log isn't in the server"(paraphrased). Just to clarify that that's what happened. If you mean that the challenge should instead change so that it's the myApp.js that should be manipulated, then I think that's better.

**Comment by kinopotato** [comment]
> Can I take this issue?

Sure! I'm still very new and inexperienced so I leave it to your more capable hands! 8D

**Comment by sidgujrathi** [comment]
I have started course and in my Glitch app there is no myapp.js file, also putting console log in server.js is also not working

**Comment by Tameshiwari** [comment]
Okay just to make it clear... First I cloned the Github boilerplate-express-gomix template... 
I'm not a big fan of **Glitch**...
So if I have a project on **Github** at similar URL

`https://github.com/Tameshiwari/boilerplate-express-gomix/`

then logically  **myApp.js**  file would be located at

`https://github.com/Tameshiwari/boilerplate-express-gomix/blob/master/myApp.js`   

Now my question is pretty simple... JUST WHICH EXACT URL should I use in this case... this is a bit confusing...
I managed to pass the whole previous **Managing Packages with Npm**   section, still I had a bit of of hard time finding the proper URL to point to **package.json**. I found the main way to make it work in my case was to select the **package.json** file, then click on **Raw**  button. That would give me a similar URL 
`https://raw.githubusercontent.com/Tameshiwari/boilerplate-express-gomix/master/`
which I later passed in the **URL**.
Any hint on how to make the boilerplate project URL work with **Github**
Thank you...

**Comment by lacivert** [comment]
I think this should be added to the Hint: "Use the new Glitch link for this episode"
