### ISSUE TITLE
Wiki request - rewrite and simplify explanation of Array.push()

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3452]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push

**Comment by matty22** [comment]
Wiki Page now exists for Array.push()

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Array.push%28%29

**Comment by ltegman** [comment]
Looks great, thanks again for working on these! Closing this one as completed.
