### ISSUE TITLE
test: shallow tests for missing/incorrect front matter on coding challenges

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#34535]
**Describe the bug**
A [PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/25172/files#diff-30158e67be249b214c99cbfd9178ff60) was recently merged which changed the `videoUrl` key value to a Youtube video url.   
Only freeCodeCamp.org videos (recorded with scrimba by @beaucarnes) are allowed currently. 

**Resolution**
 Since there is no Russian video for the challenge yet, it needs to be changed back to a blank string like:
```
videoUrl: ''
```
Please edit [the file on Github](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/russian/08-coding-interview-prep/algorithms/implement-merge-sort.russian.md) to make the changes.

**Screenshots**
![image](https://user-images.githubusercontent.com/5313213/49455015-3e2e1880-f79b-11e8-974b-a59c024d9913.png)

**Desktop (please complete the following information):**
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Additional context**

**Comment by raisedadead** [comment]
Additionally we want tests to catch this in the CI. @Bouncey @ValeraS please share your thoughts for the best place to add these.

**Comment by Bouncey** [comment]
We have a `frontmatter` check [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/4ac31ad5a73f3f0c7d5b1e3edfd06173af556f21/tools/scripts/ci/ensure-guide-page-naming.js#L110). No harm in expanding that.

I think the actual  file should be renamed though, as it is not just checking the guide page naming any more.

**Comment by Bouncey** [comment]
Oh wow, my context was all out of whack. Anywhoo, I have a PR cooking
