### ISSUE TITLE
Wiki request - rewrite and simplify explanation of Array.reverse()

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3454]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse

**Comment by matty22** [comment]
Tried to go and write up some more of these pages, but the buttons for adding a new page or editing existing pages no longer appear in the wiki.

**Comment by SaintPeter** [comment]
@matty22, unfortunately we were beset by spammers and had to lock down the Wiki.  

We've moved all of the content here:
https://github.com/FreeCodeCamp/wiki

You're welcome to fork the Wiki Repo and make changes, then submit a pull request.  We'll happily accept your changes!

**Comment by matty22** [comment]
This issue should be closed. Added this wiki page with commit 07b3e5e on wiki branch.

**Comment by ltegman** [comment]
Awesome! :smile:
