### ISSUE TITLE
Demo Project of Metric-Imperial Converter is not working

### ISSUE THREAD

**Issue by bauripalash** [freeCodeCamp/freeCodeCamp#34551]
The demo project of **Metric-Imperial Converter** of **Information Security and Quality Assurance Projects** from FCC curriculum is not working.
And upon investigation I found out that the glitch project is empty.

Demo link : <https://hard-twilight.glitch.me/>
Glitch project : <https://glitch.com/~hard-twilight>

**Comment by ezioda004** [comment]
Hi @bauripalash,

Thank you for opening this issue. 
We have tracked this issue previously on https://github.com/freeCodeCamp/freeCodeCamp/issues/34504 and are working on a fix.

Closing this.

Happy contributing!
