### ISSUE TITLE
Wiki request - rewrite and simplify explanation of Array.shift()

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3455]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/shift

**Comment by matty22** [comment]
Should I just go to the wiki and add a new page if one does not exist for these issues?

**Comment by BerkeleyTrue** [comment]
Yes

**Comment by matty22** [comment]
The array.shift() page has been created and added to the wiki.

https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Array.shift%28%29

**Comment by BerkeleyTrue** [comment]
Awesome! Thanks @matty22
