### ISSUE TITLE
Wiki request - rewrite and simplify explanation of Array.slice()

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3456]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

**Comment by abhisekp** [comment]
Close as issue is resolved https://github.com/freecodecamp/freecodecamp/wiki/js-array-prototype-slice

> NOTE: I've not written the wiki

**Comment by bugron** [comment]
@abhisekp thanks. Closing as the article is created. https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/js-slice

**Comment by abhisekp** [comment]
@bugron someone reverted the title change I did. The **js array prototype slice** title is more appropriate or maybe **js array slice**.

**Comment by bugron** [comment]
@abhisekp I think **Array.prototype.slice** is better. You can change the title to which one you want.

**Comment by abhisekp** [comment]
@bugron **Array.prototype.slice** has some issues with url which is problematic for camperbot. So either it has to be **js array prototype slice** or **js array slice**. It's good for camperbot for finding using gitter.im.

**Comment by abhisekp** [comment]
@bugron I changed the title to **js array prototype slice** https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/js-array-prototype-slice

**Comment by bugron** [comment]
@abhisekp :+1:
