### ISSUE TITLE
Unable to view users link on forum

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#34573]
Just getting around to posting about this issue which has been present for about 2 weeks on the forum.  Currently, when I try to visit https://www.freecodecamp.org/forum/u, the page just keeps trying to load and finally I get:

![image](https://user-images.githubusercontent.com/5313213/49609885-be967a00-f951-11e8-85c1-b0e26e6ce8cc.png)

I am on Windows 8.1 and using the latest version of Chrome.

**Comment by Nirajn2311** [comment]
Woah, something's trying to be loaded in that page.

Also the site keeps on loading until the pc runs out of memory and then the page crashes.

**Comment by RandellDawson** [comment]
I don't think there is a link in the forum about this issue that I am aware of.

**Comment by Nirajn2311** [comment]
@RandellDawson sry, I interpreted your post in a different way.

**Comment by raisedadead** [comment]
> **What caused it to break?**

We do not have any root cause, other than the events that have led to it:

1. We moved to `/forum` from `forum.freecodecamp.org` 

	>	As per the OP it was still working at this point I believe.

2. We removed redundant nginx on the forum VM. 
	
	- Currently the www nginx is reverse proxying the forum.  
	- The forum has its own internal nginx within the docker container.
	- Some URL rewrites are configured in the container nginx, some are on the root level www nginx.

	>	As per the OP it was still working at this point I believe.

3. The forum completely went down for hours a couple weeks ago. 

	- We were having a disk space issue on the forum VM
	- This led to it crashing itself down during the automated backups.
	- This was resolved by completely purging the instance, nuking everything (old backups, images) etc. and building the containers from scratch.

	>	Most likely this is where the issue described in the OP has started popping up.

**Comment by procode200** [comment]
Same here. I have Windows 10 Pro with latest version of Chrome.

Now that part of the forum is not very essential as it is just the Users section, so this issue does not matter that much.

Now this issue might be a little more persistent on 8.1 as that os can be a rough runner sometimes.

I would love to help on this issue.


Hang 10 ;) - procode200

**Comment by raisedadead** [comment]
After investigating a bit and updating all the plugins and components, and troubleshooting here are some more results:

This `/users` or otherwise `/u` paths are actually defined in a theme that we use. Disabling the theme in safe mode seems to make this work again.

So the current workaround is to disable the theme and visit the users page.

https://www.freecodecamp.org/forum/users?safe_mode=no_custom

**Comment by QuincyLarson** [comment]
@raisedadead Do you know which theme it is? We should definitely disable it. We want this leaderboard to be visible - it's a high priority, as it gives people helping out on the forum something to strive for. 

Also the /users path is very prominent in our navigation, and I be a LOT of people are hitting that route. We should fix this ASAP.

**Comment by QuincyLarson** [comment]
@RandellDawson @raisedadead Until we can figure out a fix for this, I've hidden the "leaderboard" nav element by commenting it out from the template.

**Comment by tbushman** [comment]
@raisedadead I could be missing it, but I don't see the `/users` route in the api. You can use res.redirect on that route with a pattern if needed, in addition to your njinx redirects / rewrites. Maybe in api-server/server/boot/randomAPIs

**Comment by QuincyLarson** [comment]
@raisedadead The codebase isn't version controlled. We've never made any changes to the code directly - you can make significant changes through Discourse's admin panel. I would prefer if we figured out a way to do that instead of trying to maintain a fork of the project.

**Comment by raisedadead** [comment]
Resolved. 

Root cause:

We manually had edited and added code from a theme component that enabled the leaderboard, which had made it difficult for us to track down the buggy code.

I have now forked and updated a tweaked version of the original component now available here:
https://github.com/freeCodeCamp/discourse-users-nav

This is automatically deployed for updates to its master.

**Comment by QuincyLarson** [comment]
@raisedadead Thanks for fixing this. I didn't realize it was this trivial to create a script and have it included automatically as part of the build process.

**Comment by RandellDawson** [comment]
@raisedadead Thanks for resolving this.  This has been driving me crazy for a while.
