### ISSUE TITLE
Wiki request - rewrite and simplify explanation of Array.some()

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3457]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

**Comment by natac13** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Array.some()

**Comment by bugron** [comment]
Closing this issue as the article is created.
