### ISSUE TITLE
Code still running without correct closing tags

### ISSUE THREAD

**Issue by saslamp** [freeCodeCamp/freeCodeCamp#34589]
**Describe your problem and how to reproduce it:**
I noticed that the code in this section runs without the proper closing tags - example ```<h3>some text</h5>``` still runs fine.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/use-headings-to-show-hierarchical-relationships-of-content

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: version 70.0.3538.110
* Operating System: Windows 64bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/25648980/49651443-7b123d80-fa2f-11e8-9af9-dca8ffe9d524.png)

**Comment by ezioda004** [comment]
Hi @saslamp,

Thank you for opening this issue. This has been fixed in the PR https://github.com/freeCodeCamp/freeCodeCamp/pull/19590 and will be shipped soon!

Closing this.

Happy coding!
