### ISSUE TITLE
Can't login `ERR_TOO_MANY_REDIRECTS`

### ISSUE THREAD

**Issue by parthppanchal** [FreeCodeCamp/freecodecamp#346]
I had created the account long back when FreeCodeCamp still used Gitter. Now, I was motivated to complete some challenges today, but I just can't login due to `ERR_TOO_MANY_REDIRECTS`. I tried on Chrome, Chromium, Firefox & Safari. I tried the solution suggested by Chrome/Chromium but to no avail.
![ERR_TOO_MANY_REDIRECTS](https://cloud.githubusercontent.com/assets/4395122/7302259/b6e8afee-ea05-11e4-9baf-57ed2f60373c.png)

**Comment by QuincyLarson** [comment]
What's your account on Free Code Camp?

**Comment by parthppanchal** [comment]
@QuincyLarson, it's `username` AT _ymail_ DOT _com_

**Comment by terakilobyte** [comment]
I've looked this user record up in the database and it's extremely malformed. Can you verify how many challenges you completed?

**Comment by QuincyLarson** [comment]
@parthppanchal I've fixed your user account. You should be able to log in with your email and password (you may have to reset your password though). Thanks for your patience!

**Comment by parthppanchal** [comment]
Thanks @QuincyLarson, but I lost all my progress till 12 Waypoints.
