### ISSUE TITLE
Wiki request - rewrite and simplify explanation of Array.toString()

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3460]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toString

**Comment by natac13** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Array.toString()

Hope this is what you are looking for!
Thanks

**Comment by abhisekp** [comment]
@natac13 I think the wiki should be `Array.prototype.toString` instead of `Arrray.toString` (because it doesn't exist).

**Comment by abhisekp** [comment]
I think the wiki should be `Array.prototype.toString` instead of `Array.toString` because that's not the method being referred here.

`Array.toString` is `static` method. But the wiki is for the instance method `Array.prototype.toString`

**Comment by bugron** [comment]
Closing this issue as [the article](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Array.prototype.toString) is created.
