### ISSUE TITLE
Change all Coding Interview Prep/Data Structure challenges from Function to Class syntax

### ISSUE THREAD

**Issue by ezioda004** [freeCodeCamp/freeCodeCamp#34606]
Currently all* the challenges in the [data structure](https://learn.freecodecamp.org/coding-interview-prep/data-structures) section use constructor function syntax, I propose we change it to `class` syntax.

Reasons are as below:
- `class` syntax is same in most popular language and in coding interview you can most of the time pick up any language to solve the question.
- `class` syntax is more peculiar. Its associated with the blueprint of the data structure.
- DS topic is universal across every language, so anyone doing DS course on python, C++, Java can easily write the same in JS since the syntax is similar and hence more ergonomic to the programmer. This would also open up FCC to a larger programmers.
- If you search for data structures online, you'll get class syntax as pseudo code almost everywhere.

### But classes in JS arent classes!

You're correct, they arent "classes" as they are syntactic sugar for functions but does it matter here? There is no downside in using classes here since we've already taught the difference between both in our OOP section and this section is about implementing *data structures* and not constructor function or classes.

Oddly, [this challenge](https://learn.freecodecamp.org/coding-interview-prep/data-structures/create-a-circular-queue) have class syntax. So if we dont decide to change them all to class, we should then change this challenge to use constructor function syntax to match the other challenges.

**Comment by Nirajn2311** [comment]
@ezioda004 I like the idea, and also I think that we could put the constructor function to the functional programming section or OOP. I’m ready to help out with this.

**Comment by ezioda004** [comment]
@Nirajn2311 We do have constructor function challenges in the [OOP](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/define-a-constructor-function) section but yes if we update the syntax then it'd be great to have your help!

**Comment by mikeattara** [comment]
@ezioda004 I would love to work on this as well, if not done  yet already

**Comment by moT01** [comment]
Closing as stale and a [duplicate issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/37820) exists with more discussion.
