### ISSUE TITLE
Create landing page for people coming from Grasshopper

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#34614]
Long time freeCodeCamp supporter and Googler Laura Holmes and her team have built a pretty amazing mobile app for learning to code called Grasshopper. She [writes about the platform here](https://medium.freecodecamp.org/zero-to-1-5-million-coders-nine-lessons-learned-while-building-grasshopper-3f8fc96acff7).

She is planning to send people who reach a certain point in Grasshopper's curriculum over to freeCodeCamp to continue their studies.

Rather than just send them to our normal landing page, it would be cool if we had a simple landing page that welcomed them and congratulated them on their progress through Grasshopper. Ideally, this would be a single page variation of our sign-in page (with one-click sign-in buttons), and it could be at the URL https://www.freecodecamp.org/grasshopper

**Comment by demangejeremy** [comment]
Good idea. I will try to post a PR soon to integrate this landing page.

**Comment by ezioda004** [comment]
The link https://www.freecodecamp.org/grasshopper redirects to a campers profile, maybe something like https://www.freecodecamp.org/promos/grasshopper would be better?

**Comment by demangejeremy** [comment]
Thanks for the information @ezioda004. I've seen it. @QuincyLarson, we change the path to https://www.freecodecamp.org/promos/grasshopper or an other?

**Comment by EladKarni** [comment]
Is this issue still available for a noob to take on?

**Comment by kartikeytripathi** [comment]
@QuincyLarson the link https://www.freecodecamp.org/promos/grasshopper shows 404 and link https://www.freecodecamp.org/grasshopper redirects to a profile. This means that the issue is not resolved yet. Will I make a PR for the same.

**Comment by QuincyLarson** [comment]
@karanbhomiagit Ah - thanks for pointing this out. Yes - if you can make a PR, we can merge this ASAP. Note that we are getting very close to pushing our master branch to production (currently it's live on freecodecamp.rocks but not on freecodecamp.org). So even after we merge your PR it may still be a few days before the new grasshopper pages go live.

**Comment by kartikeytripathi** [comment]
@QuincyLarson I think you referenced someone else. No Problem. I am working on the Landing Page. 
Will shoot a PR when it is done.

**Comment by brianRey2017** [comment]
Can i still help you @kartikeytripathi ?.
I work as Web UI Developer and i would like to contribute :smile_cat: .

**Comment by brianRey2017** [comment]
@QuincyLarson Still this issue active :thinking: ?

**Comment by jatin33** [comment]
Is this issue still open? 
I would like to help out.
