### ISSUE TITLE
Understanding Case Sensitivity in Variables- properCamelCase

### ISSUE THREAD

**Issue by mnm353** [freeCodeCamp/freeCodeCamp#34624]
**Describe your problem and how to reproduce it:**
In the challenge it asks to fix the variable declarations and assignments so their names use camelCase. the second line of the challenge is "properCamelCase" and though it looks correct to me it is still coming up as an error and not accepting the answer. Am I missing something or is this an issue with the challenge?

**Add a Link to the page with the problem:**
http://precourse.devmountain.com/challenges/understanding-case-sensitivity-in-variables#?solution=%0A%2F%2F%20Declarations%0Avar%20StUdLyCapVaR%3B%0Avar%20properCamelCase%3B%0Avar%20TitleCaseOver%3B%0A%0A%2F%2F%20Assignments%0ASTUDLYCAPVAR%20%3D%2010%3B%0APRoperCAmelCAse%20%3D%20%22A%20String%22%3B%0AtITLEcASEoVER%20%3D%209000%3B%0A%0A%0A%2F%2F%20Declarations%0Avar%20studlyCapVar%3B%0Avar%20properCamelCase%3B%0Avar%20titleCaseOver%3B%0A%0A%2F%2F%20Assignments%0AstudlyCapVar%20%3D%2010%3B%0AproperCamelCase%20%3D%20%22A%20String%22%3B%0AtitleCaseOver%20%3D%209000%3B

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![screen shot 2018-12-10 at 2 38 01 pm](https://user-images.githubusercontent.com/45773074/49763258-5f09d880-fc89-11e8-9f39-ac90eb466a1f.png)

**Comment by RandellDawson** [comment]
Sorry you are having trouble, but your question is not related to Free Code Camp and is not an issue with the Free Code Camp platform, so we are closing this issue.

You should pose your question to Devmountain. 

FYI - Your line 3, 8, 9, and 10 are not camelCase, which is probably the issue you need to resolve.
