### ISSUE TITLE
Data Structures: Insert an Element into a Max Heap

### ISSUE THREAD

**Issue by mikeshort10** [freeCodeCamp/freeCodeCamp#34635]
**Describe your problem and how to reproduce it:**
The code works fine, but there is a small typo in this challenge. The math to find the parent elements in a max heap is actually:

Math.floor((i-1)/2)

or in the second example where null is the root:

Math.floor(i/2)

Without using Math.floor(), one of the children's parents will always be undefined.

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/coding-interview-prep/data-structures/insert-an-element-into-a-max-heap

**Tell us about your browser and operating system:**

* Browser Name: Chrome
* Browser Version: 70.0.3538.110
* Operating System: macOS: 10.14.1

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="1033" alt="screen shot 2018-12-11 at 09 30 58" src="https://user-images.githubusercontent.com/17756888/49814825-a8106a00-fd27-11e8-81de-f1525a5f5da7.png">

**Comment by ezioda004** [comment]
Hi @mikeshort10,

Thank you for opening this issue. 
You are correct, parent node can be find by using `Math.floor((i-1)/2)`.

Would you like to open a PR to fix this?
