### ISSUE TITLE
mismatch of number of people who donate 

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#34632]
**Describe the bug**
My homepage shows `3,890 supporters out of 10,000 goal.`, but when I complete a challenge and get the popup to ask me to donate it says there is `3926 people who donate`. So I'm guessing the homepage one isn't getting updated. 

**Screenshots**
home page:
<img width="854" alt="screen shot 2018-12-11 at 7 39 16 am" src="https://user-images.githubusercontent.com/20648924/49804363-003f7000-fd18-11e8-91cb-99d33ee41d0e.png">

popup:
<img width="592" alt="screen shot 2018-12-11 at 7 39 00 am" src="https://user-images.githubusercontent.com/20648924/49804399-10574f80-fd18-11e8-97eb-228686a51add.png">

**Desktop (please complete the following information):**
 - OS: high sierra
 - Browser: firefox
 - Version 63.0.3

**Comment by QuincyLarson** [comment]
@moT01 Thanks for spotting this discrepancy. We haven't had time to pull these values in dynamically from Stripe / PayPal so we're currently hard-coding them and updating them once every few days. 

@raisedadead could you fix this?

**Comment by raisedadead** [comment]
Updated to latest stats.
