### ISSUE TITLE
Testing non-english challenges

### ISSUE THREAD

**Issue by lynxlynxlynx** [freeCodeCamp/freeCodeCamp#34641]
Maybe I'm misreading the code, but it looks like we're running the curriculum tests only over the English version, as no locale is specified for travis.

https://github.com/freeCodeCamp/freeCodeCamp/blob/5aa27ee364ea9567c86476caf59b6f217be9563c/curriculum/test/test-challenges.js#L28

With #30709 in mind, the tests should do some introspection first to see which language needs testing in the first place. Unfortunately in some cases PRs fix tests in all languages, so it would ideally need to loop and test all.

Basics are handled by this PR: #34559

**Comment by moT01** [comment]
Closing as stale. If anyone wants to continue the conversation, feel free to make a comment and we can reopen this. Thanks and happy coding 🎉
