### ISSUE TITLE
rewrite and simplify explanation of Arithmetic Operators

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3465]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators

**Comment by awesomeaniruddh** [comment]
On this.

**Comment by awesomeaniruddh** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Arithmetic-Operators-**Work-in-Progress*

**Comment by BerkeleyTrue** [comment]
Keep up the good work @awesomeaniruddh

**Comment by awesomeaniruddh** [comment]
The article is mostly done. Should I cover the increment (++) and decrement (--) operators as well?

**Comment by natac13** [comment]
@awesomeaniruddh I was just curious if you were working on the remainder examples? I only ask because in the wiki on [`.some()`](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Array.some()) refers to this one. If not I can happily write it in.

**Comment by awesomeaniruddh** [comment]
Yep, I'll finish the article today.

**Comment by awesomeaniruddh** [comment]
The article's done. Let me know if I missed something or the article needs more elaboration (I tried to keep at as short as possible. Has a couple of links to MDN).

**Comment by BerkeleyTrue** [comment]
Fantastic work as usual @awesomeaniruddh

**Comment by awesomeaniruddh** [comment]
Thanks :)
