### ISSUE TITLE
Understand the Immediately Invoked Function Expression (IIFE)

### ISSUE THREAD

**Issue by VinceB56** [freeCodeCamp/freeCodeCamp#34654]
**Describe your problem and how to reproduce it:**
In this chapter, the code example given is:
`
(function () {
  console.log("Chirp, chirp!");
})();`

I'm learning so I'm not sure if I'm right or not, but if I understand correctly the correct syntax should be  "function() " without a space? Both are working.
If I'm right, this was quite misleading to me, as I'm trying to learn correct syntaxes and already mixing things up between function declaration and function operator

If I'm making a mistake please tell me and I'll remove this post.

Thanks in advance
**Add a Link to the page with the problem:**
[https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/understand-the-immediately-invoked-function-expression-iife](url)

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ezioda004** [comment]
Hi @VinceB56,

Thank for opening this issue. 
In JS and most languages, whitespace isnt usually eliminated during the compilation of the code. So whitespace have no relevancy except for making the code more cleaner and readable. 
Popular style guides usually have whitespace after function declaration like `function ()` but using `function()` is completely fine too. Its matter of taste and subjective.

Hope this clears it up, closing this as its not an issue.

Happy coding!
