### ISSUE TITLE
Typo in message (the word received is mispelled)

### ISSUE THREAD

**Issue by cianetech** [freeCodeCamp/freeCodeCamp#34656]
**Describe your problem and how to reproduce it:**
After entering an invalid code on the login page, a message box pops up with the following message "The code you entered is not valid. Please check the latest OTP that you have recieved."

The word received is mispelled. 

**Add a Link to the page with the problem:**
https://auth.freecodecamp.org/login

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/26718554/49878764-84285380-fe0f-11e8-968b-e70cb6676a45.png)

**Comment by ezioda004** [comment]
Hi @cianetech,

Thanks for opening this issue. 
We're tracking this issue at https://github.com/freeCodeCamp/freeCodeCamp/issues/34450

Closing this in favor of that.

Happy coding!
