### ISSUE TITLE
rewrite and simplify explanation of Comparison Operators

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3466]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators

**Comment by DistractedMagpie** [comment]
I have a question. I was wondering where exactly do I start? I enrolled in
July but became way too busy & had family drama, UUUGH! Anyway I want to
commit this time & just need to start at the beginning. Any help, whenever
you aren't busy would be very appreciated.

                                Eternally Grateful,
                                DistractedMaggie

On Wednesday, September 23, 2015, Quincy Larson <notifications@github.com>
wrote:

>
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3466>.
>


-- 
Sent from Gmail Mobile

**Comment by Rafase282** [comment]
@DistractedMagpie you can start [here.](http://freecodecamp.com/map)

@QuincyLarson I have been taking a look at the wiki request, it looks like you want us to create pages with rewritten definitions from the links posted, is that correct?

**Comment by bugron** [comment]
Moved this issue to Wiki repository, see https://github.com/FreeCodeCamp/wiki/issues/362.
