### ISSUE TITLE
Information Security with HelmetJS - Understand BCrypt Hashes: challenge require('bcrypt') 'error'

### ISSUE THREAD

**Issue by JonathanJamesRasmussen** [freeCodeCamp/freeCodeCamp#34663]
**Describe your problem and how to reproduce it:**
Within the challenge within the title of this issue, the require method for bcrypt isn't working properly.  I have written `const bcrypt = require('bcrypt');` in the top of `myApp.js` within Glitchand I get `error` below the submit button.  The dependency is being set correctly according to the tests, but the require portion is failing.

**Add a Link to the page with the problem:**
[Link to freeCodeCamp Challenge](https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-with-helmetjs/understand-bcrypt-hashes)

[Link to glitch](https://info-security-helmet-js.glitch.me/)

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: v70.0.3538.110
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by moT01** [comment]
I think there's a new glitch project to clone when you get to the bcrypt stuff

**Comment by JonathanJamesRasmussen** [comment]
Hey there, thanks for the help.  You're correct, I just didn't see the link up top.  I wrongly assumed and that's on me.  Thanks for the prompt response, and loving all the trainings/challenges!
