### ISSUE TITLE
Add Comments in JSX

### ISSUE THREAD

**Issue by MarkMilfordMe** [freeCodeCamp/freeCodeCamp#34697]
**Describe your problem and how to reproduce it:**
On the "React: Add Comments in JSX" page instructions are: 
"Add a comment somewhere within the provided div element, without modifying the existing h1 or p elements."

And So I entered
```
const JSX = (
  <div> {/*test*/}
    <h1>This is a block of JSX</h1>
    <p>Here's a subtitle</p>
  </div>
);
```

This doesn't affect the h1 or p tags, and yet it fails to pass the test.  

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/react/add-comments-in-jsx

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Latest
* Operating System: MacOSX

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/1155953/50084570-66555700-0232-11e9-9bd3-75a673f59be0.png)

**Comment by richb999git** [comment]
It appears that if you add a comment on the same line as a tag with a space before it it adds it as a child. This means the tests then are looking at the wrong children.
If you add a comment on a new line it's ok. If you add a comment after a tag without a space between the tag and the comment it's ok.
I think you could test for <h1> being child 0 or 1 and <p> being child 1, 2 or 3. Is that an acceptable test?

**Comment by richb999git** [comment]
Like this:

 - text: The <code>div</code> should contain an <code>h1</code> tag as the first element.
    testString: assert(JSX.props.children[0].type === 'h1' || JSX.props.children[1].type === 'h1', 'The <code>div</code> should contain an <code>h1</code> tag as the first element.');
  - text: The <code>div</code> should contain a <code>p</code> tag as the second element.
    testString: assert(JSX.props.children[1].type === 'p' || JSX.props.children[2].type === 'p' || JSX.props.children[3].type === 'p', 'The <code>div</code> should contain a <code>p</code> tag as the second element.');

In the challenge files (this is the English version):
\freeCodeCamp\curriculum\challenges\english\03-front-end-libraries\react\add-comments-in-jsx.english.md

**Comment by wanzulfikri** [comment]
> It appears that if you add a comment on the same line as a tag with a space before it it adds it as a child. This means the tests then are looking at the wrong children.
> If you add a comment on a new line it's ok. If you add a comment after a tag without a space between the tag and the comment it's ok.
> I think you could test for h1 tag being child 0 or 1 and p tag being child 1, 2 or 3. Is that an acceptable test?

I wonder why it considers comments as a child? Is that a normal behaviour for JSX?

Then again, if we put the comments in between the h1 and div, it still works so it's not a child as long as it is not in the same line as div

**Comment by richb999git** [comment]
@wanzulfikri I don't know why, seems strange...perhaps it's a bug!
Please go ahead and submit your PR based on my suggestion.
