### ISSUE TITLE
Single Sign-in auth is creaating multiple usernames with the same email address

### ISSUE THREAD

**Issue by hvaandres** [freeCodeCamp/freeCodeCamp#34699]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
If you use the single sign-in as Github or Google will create multiple accounts or multiple users. We shouldn't have two different accounts with the same email address.

**To Reproduce**
1. Go to [Free Code Camp](https://auth.freecodecamp.org/login?state=g6Fo2SB3TzJWLXNXcndXOVdUdzFVWjRrdEh4cGJBSGlFYm9mRaN0aWTZMmdhRm8yU0E0VVdzNVoxTmFWbTlKWXpZMmJXTmpWV2RQZVZSdFpFSlpkSGcxWkhWUE1Ro2NpZNkgYVVEdjlqVnFUZnhCUkUxbDYwTkE1QWY3eVRDR0U0Y3k&client=aUDv9jVqTfxBRE1l60NA5Af7yTCGE4cy&protocol=oauth2&response_type=code&redirect_uri=http%3A%2F%2Fwww.freecodecamp.org%2Fauth%2Fauth0%2Fcallback&scope=openid%20profile%20email) 
2. Click on 'sign in with google or github'
3. You will see that my account is not the correct one and you will see that I still have the old and new username.

**Expected behavior**
We should have only one username per email address

**Screenshots**
https://screencast.com/t/RUf99p2UAM

**Desktop (please complete the following information):**
- Google Chrome
- Mozilla Firefox
- Safari

**Additional context**
-The only two email address that I used are: hvaandres@icloud.com & ithvaandres@gmail.com
- Username URL: https://www.freecodecamp.org/hvaandres & https://www.freecodecamp.org/aaharo

**Comment by hvaandres** [comment]
I received an email that someone else confirmed this issue. Could we have someone to help us with this issue? @QuincyLarson

**Comment by QuincyLarson** [comment]
@hvaandres Thanks for reporting this to the security email and for creating such a comprehensive issue.

Yes - we will fix this ASAP. I'm assigning this to @raisedadead since he's most familiar with the authentication system.

**Comment by hvaandres** [comment]
Can I have an update on this issue?

**Comment by QuincyLarson** [comment]
@hvaandres I don't know whether @raisedadead has had time to look at this yet.

If your account is personally affected by this and you aren't able to get into it, please email team@freecodecamp.org and I can fix this for you in the database.

**Comment by raisedadead** [comment]
I am waiting on getting this tested on the next release, where I believe this has been fixed. For a immediate resolution to your profile, I recommend reaching to the support email that Quincy has suggested in the previous comment.

**Comment by hvaandres** [comment]
Thank you for this information!

**Comment by hvaandres** [comment]
I would like to know what can I do to help with this issue since it's been too long, and I would like to participate more... @QuincyLarson @raisedadead

**Comment by raisedadead** [comment]
Hi @hvaandres as for the code, it still needs to be tested on the latest master. We do not have and ETA on that. And for fixing up your account, please drop me an email `mrugesh at freecodecamp dot org`. I will fix it up for your account on production.

**Comment by hvaandres** [comment]
I sent you an email

**Comment by ahmadabdolsaheb** [comment]
@hvaandres, we looked into the issue with your accounts and resolved it.
Could you please double check? Thank you
