### ISSUE TITLE
Broken test for "Functional Programming: Use the map Method to Extract Data from an Array"

### ISSUE THREAD

**Issue by RobertP3469** [freeCodeCamp/freeCodeCamp#34696]
I created a solution for this exercise, and it failed.  When I looked at the hint solution, my code was basically the same. When I plug the hint solution into the code and run the test, it fails, also.  The output window displays 'rating is not defined' four times.  When I copy everything to JS Fiddle and run the code, it works as expected.

**Comment by RandellDawson** [comment]
Did you ask this question on the forum and present the code you tried?

**Comment by ojeytonwilliams** [comment]
The problem is just that 'rating' has not been declared.  The challenge code seems to be fine, but the guide should perhaps be a little stricter.
