### ISSUE TITLE
Create the “step-by-step” style challenge view to replace our video challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3469]
Note that we plan to promote our onboarding flow to a challenge with this type of interface (the page you see at freecodecamp.com/ when you're logged in).

Basically, we want to have a deck of "slides" that the camper advances through (as opposed to our scrolling-style onboarding flow). 

This should be written in React.js, since we're planning to move all our views into React web components soon anyway.

**Comment by jakeoverall** [comment]
How about a tool that allows you to write html and markdown to create slides decks. 

The tool is written in react.js and the individual slides are rendered using react.js as well. 

I wrote this app as a weekend challenge just to learn react so it might take a bit of tweaking to get it just right for FreeCodeCamp's purposes. You can checkout the repo here

https://github.com/jakeoverall/BlogSlide

Also I just wanted to say that we at BoiseCodeWorks think FreeCodeCamp is awesome and we fully support its intentions. We often point our students to FCC as an additional learning resource. That being said I would love to collaborate with FCC on this. 

Let me know your thoughts. 

Thanks



![freecodecamp-slides](https://cloud.githubusercontent.com/assets/7350663/10084978/6ac330b2-62c3-11e5-91d1-b4158606ab13.png)

**Comment by BerkeleyTrue** [comment]
done
