### ISSUE TITLE
the Check for Palindromes does not pass v2

### ISSUE THREAD

**Issue by ProSerg** [FreeCodeCamp/FreeCodeCamp#3470]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
function replacer(match, p1, p2, p3, p4, offset, string) {
	console.log("P2:" + typeof(p2));
	buff = p2.split('');
	for(var i =0 ; i < buff.length; i++) {
		console.log("indx: " + buff[i] + " " + buff.length);
		if (i == Math.floor( buff.length/2 ) )
			continue;
		switch (buff[i]) {
			case '/' :
				console.log("befor  replece: " + buff[i]);
				buff[i]='\\';
				console.log(" after replece: " + buff[i]);
				break;
			case '\\':
				buff[i]="/";	
				break;	
			case '(' :
				buff[i]=")";
				break;
			case ')' :
				buff[i]="(";
				break;
			case '_' :
				buff[i]="-";
				break;
			case '-' :
				buff[i]="_";
				break;	
		}
	}
	console.log("P2:" + buff.join(''));
	return buff.join('');
}

function palindrome(str) {
  // Good luck!
  var buff ="";
  var re=/[\s,.]/gi;
  
  var array = Array.prototype.slice.apply( str.replace(re,'').split('') );
      
	
  var newstr = array.join('').toLowerCase();	
  var revstr = array.reverse().join('').toLowerCase().replace(/^.*/gi,replacer);	
	
	if (revstr == newstr) {
		return true;
	}
	
  return false;
}



palindrome("0_0 (: /-\ :) 0-0");

```
I think that the problem is not solved. I know what a palindrome. Yes, I agree that this "0_0 (: /-\ :) 0-0" is  a palindrome. The problem occurs as follows. JS interprets this line “0_0 (: /-\ :) 0-0"  as "0_0 (: /- :) 0-0" ". This is because the \ character is special. For the system perceived it as a char, it must be tag with "\\\". Consider the function call. If you put “0_0 (: /-\ :) 0-0” , you get “0_0 (: /- :) 0-0”. This happens due to the fact that JS translates a char array in a String object. I conclude that in this task an error in assert(palindrome( "0_0 (: /-\ :) 0-0" )) . This test sends a string "0_0 (: /- :) 0-0" , not  "0_0 (: /-\ :) 0-0" . Because it is necessary "\\\" to be taged.
So : assert(palindrome( "0_0 (: /-\\\ :) 0-0" )) is rightly! 
       assert(palindrome( "0_0 (: /-\ :) 0-0" )) is not right!

**Comment by awesomeaniruddh** [comment]
Please don't open another issue! The discussion could have been continued in the same issue.

This is the test as it appears in the FCC files:
```
"assert(palindrome(\"0_0 (: /-\\ :) 0-0\") === true, '<code>\"0_0 (: /-\\\\ :) 0-0\"</code> should return true.');"
```

So it *is* right :)

**Comment by ProSerg** [comment]
A funny case! Let's watch how it works. 
1 step  "assert(palindrome(\"0_0 (: /-\\ :) 0-0\") === true"  
2 step palindrome("0_0 (: /-\ :) 0-0")  
3 step 0_0 (: /- :) 0-0 
we have this line '0_0 (: /- :) 0-0'  inside the function.
