### ISSUE TITLE
ES6: Use * to Import Everything from a File  [Single quotes]

### ISSUE THREAD

**Issue by Ronnehag** [freeCodeCamp/freeCodeCamp#34714]
**Describe your problem and how to reproduce it:**
Writing with single quotations will fail the test.

`import * as str from 'capitalize_strings';`

 To pass you have to use double quotations,

`import * as str from "capitalize_strings";`

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use--to-import-everything-from-a-file

**Tell us about your browser and operating system:**
* Browser Name:  Google Chrome
* Browser Version:  70.0.3538.110
* Operating System:  Windows 10 64-bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ezioda004** [comment]
Hi @Ronnehag,

Thank you for opening this issue.
We're aware of this bug and currently tracking it at https://github.com/freeCodeCamp/freeCodeCamp/issues/17665. Closing this in favour of that.

Happy coding!
