### ISSUE TITLE
Lets improve the design!!

### ISSUE THREAD

**Issue by DoviMaj** [freeCodeCamp/freeCodeCamp#34712]
Should we work on improving the whole plataform design? 

i think its lacking in **design**. so many people are using it and it should have a more **professional** look and UI...

Any thoughts?

**Comment by DeNance007** [comment]
aye take me off this shit!

**Comment by erictleung** [comment]
@DeNance007 Looks like you may have accidentally subscribed to all notifications for the [freeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for the inconvenience!

**Comment by ascii-dev** [comment]
@DoviMaj I would be glad if you can help narrow down what you mean by `it's lacking in design` and `more professional look and UI`. I would be glad to work this journey with you. 

Thanks

**Comment by DoviMaj** [comment]
Check this article out. Im not a designer so im not sure how to define the
improvements. Stuff like gradient colors, shadows, makes the website look
much more modern and beautiful.

I would appreciate input from real designers who see the necessity to
improve the quality of the design of the whole plataform. Thanks for
wanting to help.


https://medium.muz.li/beautiful-ui-inspiration-by-dennis-sevryukov-d61dcb87e10

**Comment by raisedadead** [comment]
> i think its lacking in **design**. ...

How do you define **design**? 

> it should have a more **professional** look and UI... ...

It can, but doesn't need to. 

We would rather focus on making it more functional than anything else. 
And most importantly `functional !== beautiful`

The best example I can give you is Wikipedia.
