### ISSUE TITLE
Small fix needed in Binary Search Tree Min/Max Height challenge

### ISSUE THREAD

**Issue by jaytula** [freeCodeCamp/freeCodeCamp#34725]
**Describe your problem and how to reproduce it:**
This last test for method isBalanced is incorrect.  It should return the negation because the tree is unbalanced with min height of 1 and max height of 5.  Should be like:

`- text: The <code>isBalanced</code> method returns true if the tree is a balanced binary search tree.
    testString: assert((function() { var test = false; if (typeof BinarySearchTree !== 'undefined') { test = new BinarySearchTree() } else { return false; }; if (typeof test.isBalanced !== 'function') { return false; }; test.add(4); test.add(1); test.add(7); test.add(87); test.add(34); test.add(45); test.add(73); test.add(8); return !test.isBalanced(); })(), 'The <code>isBalanced</code> method returns true if the tree is a balanced binary search tree.');`

Also the add method in the After Test section should be included in the Challenge Seed because it is necessary for the test.

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-coding-interview-prep/data-structures/find-the-minimum-and-maximum-height-of-a-binary-search-tree.english.md

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 72
* Operating System: Chrome OS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Fordco** [comment]
I agree with you. I replicated this issue and the last test case fails when it should pass. I can work on fixing this.
