### ISSUE TITLE
QA: example code on instructions should not wrap around

### ISSUE THREAD

**Issue by rclai** [FreeCodeCamp/FreeCodeCamp#3473]
When instruction code wraps around, due to the limited space, it makes the learner think that you actually have to put a line break in the code, and they're left wondering why their code is not working. In most cases, putting a line break will keep things functioning, but sometimes it doesn't work.

**Comment by jhealy86** [comment]
Can you give an example of a page where this occurs?

**Comment by rclai** [comment]
For example, one-liner code that ends up wrapping over like in [this lesson](http://freecodecamp.com/challenges/waypoint-give-your-javascript-slot-machine-some-stylish-images).

The reason I'm reporting this is because I was helping my wife with this and noticed her putting a line break as she typed the code.

**Comment by abhisekp** [comment]
@rclai I think this can't be solved due to small width of the sidebar and long example. The font-size can't be made smaller.

**Comment by rclai** [comment]
What if we wrapped in an overflow hidden container, and when someone hovers over it, it will expand in place?

**Comment by abhisekp** [comment]
I guess, the decision has to be taken by @QuincyLarson

**Comment by erictleung** [comment]
The example link @rclai gave is no longer valid. Here are some other challenges that have this code overflow issue: [Waypoint: Turn an Image into a Link](http://www.freecodecamp.com/challenges/waypoint-turn-an-image-into-a-link) and [Waypoint: Add Images to your Website](http://www.freecodecamp.com/challenges/waypoint-add-images-to-your-website).

**Comment by rclai** [comment]
Would it be better to have it wrapped in a code container that does horizontal scrolling?

**Comment by erictleung** [comment]
Maybe really wide code blocks can be put into `<blockquote>` tags like in [Waypoint: Passing Values to Functions with Arguments](http://www.freecodecamp.com/challenges/waypoint-passing-values-to-functions-with-arguments) (you can scroll a little left and right to see all of the code). Here's a [link to the exact line of code](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L1748).

**Comment by SaintPeter** [comment]
Sounds good to me.  That's why I made them.

**Comment by erictleung** [comment]
@SaintPeter sounds good. I can work on changing overflowing example code in as many challenges as I can or any you know should/need be changed. Any rules of thumb on which code to surround with the `<blockquote>` tag?

I noticed in [Waypoint: Passing Values to Functions with Arguments](http://www.freecodecamp.com/challenges/waypoint-passing-values-to-functions-with-arguments) that one line of example code was only surrounded by `<code>` tags (i.e. `testFun("Hello", "World");`). Is it because it is already short enough to fit on the screen without overflowing?

**Comment by SaintPeter** [comment]
I think that there needs to be at least 2 lines of code before you wrap them.  My intent was to visually set off the code as well as reduce the extra spacing between lines.  For a single line of code, it's probably fine to leave it with the <code> tags.

**Comment by erictleung** [comment]
This is probably another small issue, but in the future, should multiline code blocks like this be put in `<blockquote>` tags? I feel like there's awkward spaces in between each line.

![image](https://cloud.githubusercontent.com/assets/2754821/12255038/4cca35d8-b8a4-11e5-977d-970c67fbd872.png)

**Comment by SaintPeter** [comment]
Yes, I think multi-line code blocks like this would be perfect for the blockquote.  That's precisely what it was made for.

**Comment by erictleung** [comment]
Ah okay, I may have misunderstood you if you were originally referring to those kind of multi-line code blocks.

From what I understand, this issue (#3473) is essentially about single lines of code that overflow and unintentionally look like they have line breaks. Another issue that might need to be made is changing the existing multi-line code blocks to using `<blockquote>` tags.

**Comment by robjloranger** [comment]
should this be closed?

**Comment by BerkeleyTrue** [comment]
@robjloranger Thanks
