### ISSUE TITLE
Dead link on search results (python map filter reduce)

### ISSUE THREAD

**Issue by AdrianSkar** [freeCodeCamp/freeCodeCamp#34730]
**Describe your problem and how to reproduce it:**
A link to a specific guide leads to a 404 page

**Add a Link to the page with the problem:**
[Search results page](https://search.freecodecamp.org/?q=reduce%22%0A)
Linked page: Guide: [List map filter reduce](https://guide.freecodecamp.org/python/list-map-filter-reduce)

**Tell us about your browser and operating system:**
* Browser Name: Brave
* Browser Version: Version 0.58.16 Chromium: 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Ubuntu 18.04

**Comment by Nitin96Bisht** [comment]
I would like to work on this isssue. Please let me know the correct link.

**Comment by thesidbatra** [comment]
I can work on this!

**Comment by Nitin96Bisht** [comment]
@thesidbatra Please go ahead. Kindly do not forget to read [contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
