### ISSUE TITLE
Unable to fork FCC Technical Documentation in CodePen

### ISSUE THREAD

**Issue by magnusram05** [freeCodeCamp/freeCodeCamp#34735]
**Describe your problem and how to reproduce it:**
Unable to fork FCC Technical Documentation in CodePen

Found this error in console log:
https://rawgit.com/freeCodeCamp/testable-projects-fcc/master/build/bundle.js 403

This could be because rawgit has stopped serving resources because it is on sunset phase.

**Add a Link to the page with the problem:**
https://codepen.io/freeCodeCamp/full/NdrKKL

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ArielLeslie** [comment]
To clarify: you can still fork the project, but you don't get the testing suite.

**Comment by RandellDawson** [comment]
@tbushman Can you provide some guidance on this issue?  What is with the rawgit reference anyway?  Is this an issue or does the user just not have the correct link?

**Comment by tbushman** [comment]
Thanks fyi @tchaffee @raisedadead : This involves editing the codepen. The Technical Documentation example project is using the rawgit bundle url. I don't have access.

**Comment by raisedadead** [comment]
I have updated the pen to use:

```
https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js
```

Can anyone confirm and close the issue as resolved?

**Comment by RandellDawson** [comment]
I can confirm the console is clear of this error after you changed the tests link.  Closing this issue.
