### ISSUE TITLE
FreeCodeCamp editor and console don't work as expected

### ISSUE THREAD

**Issue by kevindelsh** [freeCodeCamp/freeCodeCamp#34731]
**Describe the bug**
For a certain implementation of the smallest common multiple the editor and console don't work as expected.

**PLEASE NOTE:** This isn't about my code not working. I know you guys have all hands full and I really appreciate the great job you do. I made some tests before raising the issue.

**To Reproduce**
1- Go to https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/smallest-common-multiple/ (This is where I found it but it's not strictly necessary to reproduce it)
Paste the following code in the editor:
```
function smallestCommons(arr) {

  // Extract min/max boundaries of the sequence
  const [min, max] = arr.sort((a, b) => a - b);
  // Creating array with sequence of min/max bounderies
  const arrSeq = Array.from({length: max-min+1}, (_, i) => i + min)
  
  // starting with max
  let i = max;
  while(true) {
    if (arrSeq.every(el => {return i % el === 0})) {
      // Found! i was divisible by every member of the sequence!
      return i;
    }
    // Not found! Increment i!
    i++
  }
}


console.log(smallestCommons([23, 18]));
```
It works in [codepen.io](https://codepen.io), [jscomplete.com](https://jscomplete.com), [jsfiddle.net](https://jsfiddle.net), and the native Chrome console.

**Expected behavior**
It should return 6056820.
Instead it returns 'undefined'.

I've tested it on both Chrome  71.0.3578.98 (Official Build) (64-bit) and Firefox 64.0 (64-bit)

**My system **
 - OS: Windows 10 (Build 17134)
 - Browser: 71.0.3578.98 (Official Build) (64-bit)

**Additional context**

1. I've tested the code on the above mentioned platforms and it works.
2. I've tested this same code on FreeCodeCamp with smaller input numbers and it works fine.
3. I've cleared my cache, etc.

Thanks!

**Comment by ArielLeslie** [comment]
What you're probably running into is the inifite loop protection. FCC uses a timeout to protect campers from browser crashes when they accidentally write an infinite loop or infinite recursion. If your solution is slow, then for very large numbers the timeout will stop it from running before it is finished.

**Comment by kevindelsh** [comment]
While the code is not efficient, testing in Chrome's native console on a i7-7700HQ @ 2.8 GHz machine it takes around one second.
I don't have much experience, but it occurred to me that this could be a clue of an underlying bottleneck or maybe the protection threshold needs a little bit of increasing.

**Comment by ezioda004** [comment]
@kevindelsh The issue you're facing is because of what@ArielLeslie described.
This challenge in particular is the first one where you have to think about algorithm complexity and make your algorithm more efficient.

There are few more challenges where you'll face the same issue and a lot more in Rosetta and Project Euler section.

That being said, it isnt a bug and something that doesnt need to be fixed (atleast for this challenge).

Closing.

**Comment by kevindelsh** [comment]
OK, thanks!
