### ISSUE TITLE
Some of the initial bonfires have an additional blank argument passed into the function

### ISSUE THREAD

**Issue by rclai** [FreeCodeCamp/FreeCodeCamp#3474]
http://freecodecamp.com/challenges/bonfire-reverse-a-string

**Comment by awesomeaniruddh** [comment]
Thanks for reporting the issue, @rclai, but it's a duplicate of https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3401. Closing this issue, but you can continue the discussion there :)
