### ISSUE TITLE
Possible Typo in "SASS Challenge: Use @if and @else to Add Logic to your Styles"

### ISSUE THREAD

**Issue by WillzMu** [freeCodeCamp/freeCodeCamp#34743]
**Issue Description**
Following the given instructions. The test will fail for the @else 
`  @mixin border-stroke($val) { 
  @if $val === light { border: 1px solid black; 
                      }
@else if $val === medium { border: 3px solid black; 
                          }
@else if $val === heavy { border: 6px solid black; 
                          }
@else { border: none; 
      }
}`

The checkmark at the bottom left says: "Your mixin should have an @else statement to set the border to none." and it will pass if using "none" but not "no border" as suggested. 

My suggestion is to replace "no border" from the instructions with "none"

**Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/sass/use-if-and-else-to-add-logic-to-your-styles

**browser and operating system:**
* Browser Name: Chrome
* Browser Version:  Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: MacOs Sierra Version 10.12.6

**Comment by aditijoshi14** [comment]
@WillzMu Are you still facing this problem because on my end the code is working fine?

**Comment by WillzMu** [comment]
Hi @aditijoshi14, yes. I still have the same issue. 

Following the instructions, the last test doesnt pass
![image](https://user-images.githubusercontent.com/16624002/51937107-67bd9600-2412-11e9-9022-db25e6545cda.png)


If I put 'border: none' in the @else statement it passes
![image](https://user-images.githubusercontent.com/16624002/51937142-7f951a00-2412-11e9-8c4e-5575b86d7919.png)

**Comment by aditijoshi14** [comment]
@WillzMu I believe the instruction is little misleading. It should have been 'no border - none' instead of 'none - border' as border doesn't doesn't have a property called "no border" but does have a property called "none". I could change the description of it to reduce confusion.

**Comment by WillzMu** [comment]
yes, it has clarified my issue. Thank you for your help.
