### ISSUE TITLE
Pig Latin Chllenge - Test for vowel at end of the word.

### ISSUE THREAD

**Issue by BrBearOFS** [freeCodeCamp/freeCodeCamp#34755]
**Describe your problem and how to reproduce it:**
I have an issue with the challenge where the last letter of the word is a vowel.   
I have created code in codepen that produces the correct result, however does not pass the test  - 
I submitted to question in the forums and no one there can answer the question as to why it does not pass.  Please note I am aware that this can be refactored into a clearer process by doing the variable declarations above the individual for loops..   

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/pig-latin

**Tell us about your browser and operating system:**
* Browser Name:  Google Chrome 
* Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Windows 10  Build 1803

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Here is a link to the codepen that shows the code working : 
https://codepen.io/BrBearOFS/pen/mardvg

**Comment by ezioda004** [comment]
Hi @BrBearOFS,

You can see the test input file [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/pig-latin.english.md).

The test that you arent able to pass is for the string `"schwartz"`, whose output should be `"artzschway"`.
Whereas your code outputs `"zschwartay"`.

Its an error in your code and something you need to fix.

Closing this as its not an issue with the challenge.

Happy coding!
