### ISSUE TITLE
Dev Setup: npm run develop needs CTRL+C to be pressed twice for an exit

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#34752]
`npm run develop` needs <kbd>CTRL</kbd> + <kbd>C</kbd> to be pressed twice for an exit

**Comment by thecodingaviator** [comment]
I don't think this is a problem with our project. I am working with a personal project which uses React without using any dependencies, complexities, etc. and it requires  CTRL + C to be pressed twice to exit `npm start`. I'm on the latest VSCode on Windows using the inbuilt terminal

**Comment by RandellDawson** [comment]
@raisedadead Can we close this now due to the fact that PR #34840 has been merged, or is this still an ongoing issue?
