### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by testnar2019** [freeCodeCamp/freeCodeCamp#34765]
I would like to be able to reform the FreeCodeCamp design in some specific sites. Could this be viable through opensource?

**Comment by RandellDawson** [comment]
Can you be a little more specific about what you believe the issue is that you want to help with?

**Comment by raisedadead** [comment]
Hi @testnar2019 we welcome your feedback and suggestions. I recommend discussing this over on our forum first though. You will get more interest and comments from the community that way. Then you can always come back and log an issue with the specifics.

Thanks and happy contributing.
