### ISSUE TITLE
Some of the tests are buggy.

### ISSUE THREAD

**Issue by tdtrung17693** [freeCodeCamp/freeCodeCamp#34767]
Some of the tests are, in my opinion, a little bit buggy. Take the test of "Advanced Node and Express - Implementation of Social Authentication" for example. This code isn't accepted:

```javascript
app.route('/auth/github')
  .get(
    passport.authenticate('github'),
    (req, res)  => {

  })

app.route('/auth/github/callback')
  .get(
    passport.authenticate('github', { failureRedirect: '/' }),
    (req, res) => {
      res.redirect('/profile')
    }
  )
```

While this code is accepted:

```javascript
app.route('/auth/github')
  .get(passport.authenticate('github'),
    (req, res)  => {

  })

app.route('/auth/github/callback')
  .get(passport.authenticate('github', { failureRedirect: '/' }),
    (req, res) => {
      res.redirect('/profile')
    }
  )
```
And there are more of buggy tests like this all around. These kind of buggy tests are so annoying. They make us waste our times just to hack the code for making the tests passed.

**Comment by RandellDawson** [comment]
This is the same issue reported in issue #34344, so I am closing this one as a duplicate in favor of keeping the other one open.
