### ISSUE TITLE
Multiple versions of sorting algorithm challenges

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#34776]
A little while ago I reviewed some new Rosetta Code challenges for the Coding Interview Prep section. Some of the new challenges were sorting challenges (bubble, insertion, and so on) that already exist in another part of the Coding Interview Prep section, and @ezioda004 brought up a good point about the duplicate challenges being excessive.

Here's the PR for reference where we discuss some possible solutions: https://github.com/freeCodeCamp/freeCodeCamp/pull/34634

What do you all think? Would be great to get some feedback about what everyone thinks is best to do in this situation.

**Comment by Nirajn2311** [comment]
I think that it’s better if the challenges were kept in one place.

**Comment by thecodingaviator** [comment]
It’s good if we can have everything at one place. Maybe in the coding practice module

**Comment by nikrb** [comment]
coding interview prep section maybe used by someone who hasn't done the whole curriculum? So they might miss the sorts. I think a link (as suggested by @ezioda004) to the sorts would be better than duplicating them.

**Comment by ahmadabdolsaheb** [comment]
keep the classic sorting algos in intro to algorithms. you can delete the duplicates and add a link if you have to.

**Comment by scissorsneedfoodtoo** [comment]
Sorry all, I think I could have worded things a bit better. While these challenges aren't exact duplicates, they do require users to implement the same basic sorting algorithm, though maybe with some slight changes regarding I/O. Here's a link to [Bubble Sort](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-coding-interview-prep/algorithms/implement-bubble-sort.english.md) in the Coding Interview Prep Algorithms section, and the [Rosetta Code](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-coding-interview-prep/rosetta-code/sorting-algorithms-bubble-sort.md) version of Bubble Sort.

So are we thinking that it would be best to remove the text from the Rosetta Code versions of the sorting challenges that already exist in the Coding Interview Prep Algorithms section, and replace it with a link to the first challenge I linked to above? 

Cc @NitronR.

**Comment by ezioda004** [comment]
>So are we thinking that it would be best to remove the text from the Rosetta Code versions of the sorting challenges that already exist in the Coding Interview Prep Algorithms section, and replace it with a link to the first challenge I linked to above?

Thats the best option - classic sorting algorithms should be kept in the `/algorithms` section because those are the most common and most asked algorithms. If someone wants to do more sorting algorithms, a link to the Rosetta challenge should do it.
