### ISSUE TITLE
Sass: Apply a Style Until a Condition is Met with @while Text-1 not passing test

### ISSUE THREAD

**Issue by mstachalski** [freeCodeCamp/freeCodeCamp#34775]
**Describe your problem and how to reproduce it:**
On the Sass task called "Sass: Apply a Style Until a Condition is Met with @while" the test does not pass for text-1

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 71.0.3578.98
* Operating System: Windows 10 64bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="960" alt="example" src="https://user-images.githubusercontent.com/9536352/50547457-1ee0b900-0c7d-11e9-811c-d3f035b8fd0c.png">

**Comment by RandellDawson** [comment]
Can you post your actual code, vs. a screenshot, because it appears as if your code is correct, but maybe you have some hidden characters which are throwing off the tests.  Also, did you bring this issue up on the forum first?

**Comment by mstachalski** [comment]
Sure:

`<style type='text/sass'>
  
  $x: 1;
  @while $x < 11 {
    .text-#{$x} { font-size: 5px * $x;}
    $x : $x + 1;
    }
  
</style>

<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>
<p class="text-6">Hello</p>
<p class="text-7">Hello</p>
<p class="text-8">Hello</p>
<p class="text-9">Hello</p>
<p class="text-10">Hello</p>`

**Comment by mstachalski** [comment]
Sure
```<style type='text/sass'>
  
  $x: 1;
  @while $x < 11 {
    .text-#{$x} { font-size: 5px * $x;}
    $x : $x + 1;
    }
  
</style>

<p class="text-1">Hello</p>
<p class="text-2">Hello</p>
<p class="text-3">Hello</p>
<p class="text-4">Hello</p>
<p class="text-5">Hello</p>
<p class="text-6">Hello</p>
<p class="text-7">Hello</p>
<p class="text-8">Hello</p>
<p class="text-9">Hello</p>
<p class="text-10">Hello</p>```

**Comment by RandellDawson** [comment]
Your code passes when I use it.  You may just need to refresh your browser or clear your cache and try again.  If you would have posted this to the forum, you would have received the same instructions and a much faster response.

**Comment by mstachalski** [comment]
I already closed and restarted my browser multiple times however. I am aware that this issue was opened some times earlier on here as well and has since been closed. I tried all the instructions however and it still does not work for me.

What I have not done yet is clearing my cache, however since I am in incognito mode (I am using someone elses notebook for the moment) this should not be much of an issue right?

**Comment by thecodingaviator** [comment]
@RandellDawson I don't think the PR fixing it hasn't been shipped yet. When did we last push the repo to production ?

**Comment by RandellDawson** [comment]
@mstachalski I am wondering if you have a browser setting which is affecting your ability to go below `6.6667px`.  I will ask some others for some more feedback on why you maybe seeing that one specific test related to the `text-1` class.

 As far as the 2nd issues regarding the increment error, that is a bug in the tests which has yet to be fixed (@thecodingaviator I tested this same code locally on the latest version of the `master` branch` and it still fails.  I have created PR #35100 to deal with the spacing issues related to incrementing the index.

**Comment by moT01** [comment]
I was able to get a similar error when my browser was zoomed to 80%. Try making the zoom 100% or other zoom levels and run the tests again @mstachalski.

**Comment by PongtheGreat** [comment]
@RandellDawson Chrome's minimum font size is 6px.

**Comment by RandellDawson** [comment]
@mstachalski What zoom percentage are you using when you experience this issue.  If you change to 100% zoom, do you still experience the problem?

**Comment by mstachalski** [comment]
Hey, sorry for my late reply.

I don't remember anymore since it was quite some time ago. I'm pretty sure it was on 100%. However I was programming on a convertible laptop , alike Microsoft surface. Maybe the screen size / resolution / ratio of that might be the issue?

**Comment by RandellDawson** [comment]
To anyone who has had problems with this challenge using Chrome, if you go to chrome://settings/fonts and make sure you set minimum font size to the lowest setting, does that allow you to pass all the tests?

![image|689x224](upload://unyOF7q6jWBOHx6plEscng2f8A2.png)

**Comment by akiko-pusu** [comment]
@mstachalski  and @RandellDawson 
Thank for your reporting and handling this issue. You saved my day!
