### ISSUE TITLE
Duplicate articles in /javascript folder

### ISSUE THREAD

**Issue by ezioda004** [freeCodeCamp/freeCodeCamp#34783]
We need to find a solution for ES6+ articles. Currently we do have an ES6 folder in the `/javascript` folder but no other folder for further releases. With a quick glance someone creating a new articles won't know where to add a new articles and hence we have PR's such as https://github.com/freeCodeCamp/freeCodeCamp/pull/24571

The 2 options I see are:
1. Rename ES6 folder to ES6+ so we can have previous/future release articles there.
2. Unpack all the ES6 articles into JS folder.

We can pick either of these option and clean up the JS folder accordingly.

**Comment by thecodingaviator** [comment]
I suggest option 1. Easier to maintain in the long term

**Comment by ShawnToubeau** [comment]
Hello all!
I agree, option 1 sounds like the better one.
I can provide help with cleaning up the JS folder if needed?

**Comment by raisedadead** [comment]
See https://github.com/freeCodeCamp/freeCodeCamp/issues/36729 for refrence
