### ISSUE TITLE
Broken Link on specific challenge page

### ISSUE THREAD

**Issue by dgandhi98** [freeCodeCamp/freeCodeCamp#34782]
**Describe your problem and how to reproduce it:**
This is in reference to the "iterate through the keys of an object with a for... in statement" challenge in basic data structures for js.

The "Get a Hint" link to the guide page is broken.
The broken link:
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement

The correct link:
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for...in-statement/

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 71.0.3578.98 64-bit
* Operating System: MacOs Mojave

**Comment by sararuth** [comment]
<a href="https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for...in-statement/" class="btn-primary-invert btn btn-primary btn-block">Get a hint</a>

**Comment by chaomt** [comment]
I can work on this!

**Comment by moT01** [comment]
I have created an issue to consolidate all of the broken "get a hint" link issues https://github.com/freeCodeCamp/freeCodeCamp/issues/35155

**Comment by moT01** [comment]
Fixed in [beta](https://www.freecodecamp.rocks/learn)
