### ISSUE TITLE
Can't claim my certificate although the profile is public and I accepted the Academic Honesty Pledge

### ISSUE THREAD

**Issue by MahmoudAFawzy** [freeCodeCamp/freeCodeCamp#34795]
- I'm logged in to my profile and finished the responsive web design projects

- Clicked on "Claim certificate"

- Then clicked on "Show responsive web design certificate"

Although that I accepted the Academic honesty pledge, the website keeps telling me "mahmoudafawzy has not yet agreed to our Academic Honesty Pledge."

The version of Google chrome I'm using is: Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by lasjorg** [comment]
If you log in and click the settings link in the top right, then scroll down to the section that says Academic Honesty Policy, does it say you have accepted? If _not_ can you accept it there? (i don't remember how it looks before accepting).

**Comment by darrylmorley** [comment]
I have the same issue here...

**Comment by thecodingaviator** [comment]
@MahmoudAFawzy Has the issue been fixed on your side?

**Comment by MahmoudAFawzy** [comment]
@thecodingaviator yes it has

**Comment by thecodingaviator** [comment]
@RandellDawson How is that possible? Have we pushed master to production?

> @thecodingaviator yes it has

**Comment by RandellDawson** [comment]
@thecodingaviator The core team can selectively push emergency fixes to production and not the entire master branch.  It is possible this was done.  @raisedadead or @Bouncey would probably know.

**Comment by raisedadead** [comment]
We did not push any fixes. The underlying problem was, the OP had accidentally created two different accounts. They deleted one of them and that has resolved their issue. More often than not that is the case for these issues, where the users accidentally create secondary accounts, and end up with this issue.

**Comment by Nightro-Fx** [comment]
RIP
