### ISSUE TITLE
Unclear instruction in Tests to pass

### ISSUE THREAD

**Issue by jasmeetsohal** [freeCodeCamp/freeCodeCamp#34791]
Hey I found an unclear instruction in challenge `Data Structures: Perform a Subset Check on Two Sets of Data` fall into `Coding Interview Prep` it has  written `union` Tests context which should be 

> Your `Set` class should have a `subset` method.

in that place.
Underneath is the snapshot of the challenge.
![image](https://user-images.githubusercontent.com/20149200/50581530-86b32180-0e80-11e9-81d2-234e21e65f2c.png)

The issue has solved by following  PR #34788.

**Comment by thecodingaviator** [comment]
@jasmeetsohal Please close this issue then

**Comment by jasmeetsohal** [comment]
Alright I'm closing this issue @thecodingaviator
