### ISSUE TITLE
Need Regex to escape comments while validating the solution

### ISSUE THREAD

**Issue by Vikas-KM** [freeCodeCamp/freeCodeCamp#34809]
**Describe your problem and how to reproduce it:**
The solution validates the comments which checking for "for" keyword. I think it should escape the comments.
I have added a small screenshot with solution. not sure if its 100% correct. but hopefully something to start with.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/use-the-map-method-to-extract-data-from-an-array/

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Windows 10 pro

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![screenshot 93](https://user-images.githubusercontent.com/743498/50675663-77191180-1015-11e9-8170-01344d59da97.png)
![screenshot 92](https://user-images.githubusercontent.com/743498/50675668-84ce9700-1015-11e9-8ea1-566aca83293f.png)

**Comment by thecodingaviator** [comment]
I see the issue. I think we’ll maybe use your solution. Make a PR with what you think is fine. We can then discuss there

**Comment by Vikas-KM** [comment]
> I see the issue. I think we’ll maybe use your solution. Make a PR with what you think is fine. We can then discuss there

Sure.. working on it

**Comment by Vikas-KM** [comment]
Clicked by Mistake
