### ISSUE TITLE
npm wrong name of node_modules folder

### ISSUE THREAD

**Issue by malbarmawi** [freeCodeCamp/freeCodeCamp#34814]
**Describe your problem and how to reproduce it:**
In this chalange the said `node_modules` folder name  is `nodemodules` and next `node module`  the correct folder name locally and globally is `node_modules`

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm

**Comment by Nirajn2311** [comment]
@malbarmawi this issue has been fixed but the corrected file hasn’t been pushed to production yet, until then this issue will show up in the site.

**Comment by GMTernence** [comment]
#13774
