### ISSUE TITLE
Update Bootstrap to v4 from v3.3.7

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/freeCodeCamp#34815]
**Describe your problem and how to reproduce it:**
Currently FCC is teaching Bootstrap `v3.3.7`, I think that it is better if the Bootstrap curriculum was updated to the current version `v4.1.x`. Also some of the like 'wells' are not there in `v4.1.x`.

Currently I have changed the CDN link and updated one challenge. The changes are in my fork - https://github.com/Nirajn2311/freeCodeCamp/tree/feature/update-bootstrap

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/bootstrap

**Comment by lasjorg** [comment]
Should the changes be visually similar, or should they follow the bootstrap migration page suggestions?
E.g. The old btn-default looks more like the new btn-light but the migration page suggests using btn-secondary, which is a gray/darker color.


I'm kind of new to github collaboration.
How would this be handled? Is it a one man job? If not, would we just work off our own fork/branch and do pull requests, challenge by challenge?

**Comment by lasjorg** [comment]
By complete makeover I assume you just mean the text and bootstrap classes, and not the app that is being worked through in the challenges?

A few observations:

1. In the intro section, how about we just link to the getbootstrap front page.

2. Considering the comprehension level needed for the other sections of the Front End Libraries Certification, I assume we can "up" the difficulty of the text in this section just a bit without causing too much trouble.

3. None of the challenges I have looked at uses the "instructions" section. Some of the instructions need to be rewritten as actual instructions.

4. Some of the challenges use bootstrap in the challenge text, however, that is using the version of bootstrap the site uses and not the one in the _meta folder meta.json file. Not sure what to do about that.

I have updated about 5 challenges so far btw, I have not yet pushed my branch as I'm still not sure how I should be making the commits (per challenge or all in one).

**Comment by dnntrn** [comment]
Hi @lasjorg, are you still working on this? I also would like to update the bootstrap curriculum v4 and make it more extensive with lessons on cards, alerts, jumbotrons, etc. It's really really short right now.

**Comment by lasjorg** [comment]
@dnntrn 
No, I'm not really working on it. I didn't get what the plan was for the update. It felt wrong just doing a pure refactoring of the old curriculum to use Bootstrap 4.

Also, looking at the plan for v7 of the curriculum, I'm not sure if the plan is to ditch Bootstrap or if it was just unintentionally left out on the list.

https://www.freecodecamp.org/forum/t/help-us-build-version-7-0-of-the-freecodecamp-curriculum/263546

I know the curriculum update isn't exactly right around the corner but it still wouldn't be very cool to make a totally new Bootstrap 4 curriculum if it is just going to be dropped anyway.

I guess I should figure out what the plan is.

**Comment by dnntrn** [comment]
@Nirajn2311 Should we work on updating the current Bootstrap version to V4 + adding more Bootstrap challenges? It doesn't seem that Bootstrap will be in v7 of the curriculum, but it's also not too difficult to do, and I don't mind taking it on! @lasjorg

**Comment by moT01** [comment]
Closing at stale. I don't think we will be changing these challenge at the moment in favor of the project based curriculum. Thanks and happy coding everyone 🎉
