### ISSUE TITLE
the Check for Palindromes does not pass v3

### ISSUE THREAD

**Issue by ProSerg** [FreeCodeCamp/FreeCodeCamp#3482]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
function replacer(match, p1, p2, p3, p4, offset, string) {
	buff = p2.split('');
	for(var i =0 ; i < buff.length; i++) {
		if (i == Math.floor( buff.length/2 ) )
			continue;
		switch (buff[i]) {
			case '/' :
				buff[i]='\\';
				break;
			case '\\':
				buff[i]="/";	
				break;	
			case '(' :
				buff[i]=")";
				break;
			case ')' :
				buff[i]="(";
				break;
			case '_' :
				buff[i]="-";
				break;
			case '-' :
				buff[i]="_";
				break;	
		}
	}
	console.log("P2:" + buff.join(''));
	return buff.join('');
}

function palindrome(str) {
  // Good luck!
  var buff ="";
  var re=/[\s,.:;?!]/gi;
  console.log("str:" + str);
  var array = Array.prototype.slice.apply( str.replace(re,'').split('') );
      
	
  var newstr = array.join('').toLowerCase();	
  var revstr = array.reverse().join('').toLowerCase().replace(/^.*/gi,replacer);	
  console.log( revstr + " <> " + newstr );	
	if (revstr === newstr) {
      console.log("Vasy!");
		return true;
	}
	
  return false;
}



palindrome("0_0 (: /-\\ :) 0-0");

```
I think this exercise has a bug. My palindrome function returns true. But the test asserts that false. This means that in the exercise are we talking about different lines. I mean the following :
palindrome("0_0 (: /-\\\ :) 0-0"); or palindrome("0_0 (: /-\ :) 0-0"); 
![assert](https://cloud.githubusercontent.com/assets/13997176/10067938/14a1f9e4-62a9-11e5-8e73-54a8238148e1.png)

**Comment by awesomeaniruddh** [comment]
I think I finally understand your issue.

IMHO `palindrome("0_0 (: /-\ :) 0-0");` or `palindrome("0_0 (: /-\\ :) 0-0");` should make *no* difference anyway because you are supposed to ignore all punctuation. The presence of the `\` should not matter.

My code works perfectly fine with the challenge.

**Comment by ProSerg** [comment]
I finally understand your answer. I had not considered this characters as punctuation marks. Thanks for help )

**Comment by awesomeaniruddh** [comment]
That's great :) closing the issue

**Comment by awesomeaniruddh** [comment]
That's great :) closing the issue
