### ISSUE TITLE
Contributing to freecodecamp using Paypal but there is no way to update that I am contributing 

### ISSUE THREAD

**Issue by deepikagunda** [freeCodeCamp/freeCodeCamp#34825]
I have been contributing to freecodecamp using paypal. There is no way to update that I am contributing .Every time I use freecodecamp , it prompts me to support freecodecamp.Is there a way to update my name and not show these pop ups .

**Comment by ArielLeslie** [comment]
If you donate via PayPal or cryptocurrency, you can email a donation receipt to team@freecodecamp.org and your account will be manually updated. Unfortunately, only the credit card donations through swipe can automatically update your account.

**Comment by deepikagunda** [comment]
Sent email .Will close this issue and hope this is resolved.
