### ISSUE TITLE
When clicking get help, I get a 404

### ISSUE THREAD

**Issue by benschac** [freeCodeCamp/freeCodeCamp#34832]
**Describe your problem and how to reproduce it:**
404 on `get help` link here `https://learn.freecodecamp.org/apis-and-microservices/mongodb-and-mongoose/use-model-findone-to-return-a-single-matching-document-from-your-database`

**Add a Link to the page with the problem:**
`https://guide.freecodecamp.org/certifications/apis-and-microservices/mongodb-and-mongoose/use-model-findone-to-return-a-single-matching-document-from-your-database` gets a 404

**Tell us about your browser and operating system:**
* Browser Name: chrome
* Browser Version: 
* Operating System: mac

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by benschac** [comment]
Great, someone need to update the link? We’re you able to reproduce?

**Comment by 4M3L** [comment]
I think he's already updated.

**Comment by benschac** [comment]
should I close this issue? Is there a PR that fixed it?

**Comment by Bouncey** [comment]
@benschac Thank you for reporting this issue, it is something we are aware of and currently working towards a fix.

@RandellDawson This is another instance of the issue we discussed yesterday.

**Comment by Nitin96Bisht** [comment]
@benschac @Bouncey @4M3L Let me know whether it has been done now or not. I would like to work on this issue.

**Comment by RandellDawson** [comment]
@Nitin96Bisht This has been fixed and is awaiting a deployment to production.

**Comment by moT01** [comment]
I have created an issue to consolidate all of the broken "get a hint" link issues https://github.com/freeCodeCamp/freeCodeCamp/issues/35155

**Comment by moT01** [comment]
Fixed in [beta](https://www.freecodecamp.rocks/)
