### ISSUE TITLE
Donation pop-up keeps appearing after making a donation

### ISSUE THREAD

**Issue by Dayfiri** [freeCodeCamp/freeCodeCamp#34845]
**Describe the bug**
I've made a constant monthly donation via paypal which was activated yesterday when was the first time I did it. The donation was made with paypal account that doesn't share the same e-mail address as my FCC account. So now, even though the donation has been proceeded I'm still receiving the pop-ups when using the FCC page for learning.

**To Reproduce**
1. Go to FCC page and log in
2. Click on any challenge and start solving it
3. After solving [1 || 2 || 3] challenges, the pop-up will be visible
4. This is repeating problem ( More challenges, same pop-up  )

**Screenshots**
I've got a screenshot from PayPal and I'm able to send it via e-mail if needed

**Comment by deepikagunda** [comment]
I had the same issue and I received an email to do this ..quoting the Freecodecamp team .. 
"If you donate via PayPal or cryptocurrency, you can email a donation receipt to team@freecodecamp.org and your account will be manually updated. Unfortunately, only the credit card donations through swipe can automatically update your account."

**Comment by Dayfiri** [comment]
@deepikagunda Thanks for the reply. I've send them an e-mail and all I gotta do now is wait for response.

**Comment by raisedadead** [comment]
Hi @Dayfiri @deepikagunda 

Yes, you are correct. Thanks for sending us the emails. Once @QuincyLarson (who monitors the team@freecodecamp.org email) validates.

We will update the user record for you, so that you do not see the modal.

Thanks for supporting freeCodeCamp.org

**Comment by raisedadead** [comment]
Meanwhile I am closing this in favor of handling over our support email.

**Comment by Dayfiri** [comment]
hey @raisedadead,
It's been 6 days and still no answer. Should I try other method with this or does Quincy has a lot of work and I need to wait more ?

**Comment by raisedadead** [comment]
May be he somehow missed you email. I'll ping him about this on priority. Thanks for your patience.
