### ISSUE TITLE
Using double quotes doesn't work with Challenge #117

### ISSUE THREAD

**Issue by IshMary** [FreeCodeCamp/FreeCodeCamp#3485]
Challenge [Waypoint: Use jQuery to Modify the Entire Page](http://freecodecamp.com/challenges/waypoint-use-jquery-to-modify-the-entire-page) has an issue.
Please I want to know why double quotes don't work in the line while they work on the previous lines. Just curious really.
My code:
<script>
  $(document).ready(function() {
    $("#target1").css("color", "red");
    $("#target1").prop("disabled", true);
    $("#target4").remove();
    $("#target2").appendTo("#right-well");
    $("#target5").clone().appendTo("#left-well");
    $("#target1").parent().css("background-color", "red");
    $("#right-well").children().css("color", "green");
    $("#left-well").children().css("color", "green");
    $(".target:nth-child(2)").addClass("animated bounce");
    $(".target:even").addClass("animated shake");
    $("body").addClass("animated hinge"); //This line seems to have issues
  });
</script>

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

**Comment by jhealy86** [comment]
Hi IshMary-

I can't seem to duplicate the issue when using Chrome or Firefox. Please provide more information about what's happening. Also, if you could please repost your code using the code tags, like this:
\`\`\`
Code goes here
\`\`\`

**Comment by IshMary** [comment]
I've actually fixed it. In that challenge, for some reason, enclosing
the targets and classes in double quotes doesn't seem to work. I use
Firefox. It's a bit of a peuliar problem because the other challenges
before and after that do not present the issue. Thanks for looking at
it anyway.

**Comment by bugron** [comment]
@IshMary thanks for posting this issue!
Closing this issue as it is fixed. Feel free to reopen if you still experience problems, thanks. And keep in mind that [we officially support only Chrome browser](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2942#issuecomment-136591448).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by IshMary** [comment]
Oh! My bad. I'm addicted to Firefox. Will keep that in mind though.
Thank you very much.
