### ISSUE TITLE
CSS variable colours: Gray is accepted but Grey is not

### ISSUE THREAD

**Issue by T4JC** [freeCodeCamp/freeCodeCamp#34862]
On the Basic CSS: Use CSS Variables to change several elements at once lesson.
Following the task and setting one of the CSS variables colour to 'Grey' fails the test even though the colour changes successfully.

This is due to spelling differences in different English speaking countries in the USA 'Gray' is the common spelling where as in some other countries such as the UK 'Grey' is the accepted spelling. Therefore both are correct and both should pass the test.

Recommendation: Allow 'Grey' as a correct answer and allow tests to pass.

https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-variables-to-change-several-elements-at-once

**Comment by charliearlie** [comment]
Even in countries where we use the English "grey", it should still not be accepted. One thing you have to get used to is using American English while programming. `background-color`, `gray`, etc.

**Comment by RandellDawson** [comment]
css
```css
.gray {
  background-color: gray;
}

.grey {
  background-color: grey;
}
```
```html
<div class="gray">
   gray
</div>
 <div class="grey">
   grey
</div>
```
When I put both of these in a document and inspect the `div` elements using Chrome's Developer Tools, under Computed, they both have the value `rgb(128, 128, 128)`, so they do appear to be the same and they do look the same to me.

**Comment by charliearlie** [comment]
Yeah, I learned CSS a long time ago. Grey should be accepted. 😭

**Comment by RandellDawson** [comment]
@charliearlie Actually, regardless if the two are identical, I concur with your original assessment that it should be `gray` and not allow `grey`, because the instructions are very specific on what the colors should be.  I am going to close this issue, because there is nothing wrong with the existing tests per the instructions.
