### ISSUE TITLE
[FIREFOX] Unable to pass Basic CSS: Add Rounded Corners with border-radius

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#34867]
**Describe your problem and how to reproduce it:**

Unable to pass challenge in fiefox, chrome is OK

**Add a Link to the page with the problem:**

http://localhost:8000/learn/responsive-web-design/basic-css/add-rounded-corners-with-border-radius

**Tell us about your browser and operating system:**

* Browser Name: FireFox
* Browser Version: 64.0.2 (64-bit)
* Operating System: Mac 10.14.2

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![image](https://user-images.githubusercontent.com/18572518/51116591-78abbc00-1803-11e9-89e0-6f3fef75fe9e.png)

**Comment by Bouncey** [comment]
From @ValeraS:
> It is an issue with the test in Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=137688
In Firefox:
`getComputedStyle(document.getElementsByTagName('img')[0])["border-radius"] === "" `
but
`getComputedStyle(document.getElementsByTagName('img')[0])["border-top-left-radius"] === "10px"`
`JQuery` uses `getComputedStyle`

This specific test uses `jQuery`

**Comment by thecodingaviator** [comment]
Passes for me:
![image](https://user-images.githubusercontent.com/34807532/51119483-f76f1c00-1838-11e9-8d5e-cd8843d5336b.png)

FireFox 64.0.2 (64-bit) Windows 10

**Comment by Bouncey** [comment]
Maybe Mac only?

**Comment by thecodingaviator** [comment]
Or maybe we're getting it on localhost only. Who knows what the problem might be? Try it online once

**Comment by ValeraS** [comment]
In production, the test checks `border-top-left-radius`.

**Comment by ValeraS** [comment]
😀 it's my changes introduced it.

**Comment by thecodingaviator** [comment]
@ValeraS So it's fixed already. Right?

**Comment by ShawnToubeau** [comment]
Hello all! 
@ValeraS Not 100% sure how FCC performs their tests but from looking at this challenge's file it looks like its checking for "border-radius"? 
![image](https://user-images.githubusercontent.com/22332636/51291687-fa534380-19d5-11e9-8239-357408af92a1.png)

Is that not right?

**Comment by thecodingaviator** [comment]
Okay, no I was wrong @ValeraS . It worked on learn.freecodecamp.org on Firefox, the same version as Stuart. But I do not understand if it works for someone in production, why are we bothering with it right now?

**Comment by Bouncey** [comment]
@thecodingaviator because we are trying to publish the next version of freeCodeCamp, which is currently on `master`, and there has been a regression in the challenge tests which needs to be resolved.

Learn to currently many iterations behind the current master branch, they may look and feel similar, but the are worlds apart in terms of usability and performance.

**Comment by thecodingaviator** [comment]
Okay, I'll try taking it old school. Lemme see what I can do. I'll give plain old JS a try

**Comment by thecodingaviator** [comment]
Okay, I've tried multiple things now:

1. Using `getElementsByClassName()`
2. Using `getElementsByTagName()`
3. Using a combination of jQuery and plain JS
4. Using `document.images`

And nothing works. The two option we now have are:

1. We test user code
2. We check for all 4 long forms of `border-radius` individually using an && on the same test

What do you guys suggest?

**Comment by thecodingaviator** [comment]
I guess the learn repo is right now checking for border tip left radius only atm. The master branch here is checking for all but we know the problem with that

**Comment by ojeytonwilliams** [comment]
I tested out @thecodingaviator's second option on my machine and it does the trick.  It seems like the better option since it directly checks if the user has met the requirements.

I'd submit a PR, but it doesn't seem quite right as I only checked other people's work.

**Comment by thecodingaviator** [comment]
@ojeytonwilliams Please feel free to make a PR :)
