### ISSUE TITLE
ER_ACCESS_DENIED_ERROR on freeCodeCamp news

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#34863]
**Describe the bug**
On visiting [freeCodeCamp news](https://www.freecodecamp.org/news/) error 500 is shown. It doesn't matter you are signed in or not, the error persists.  

**To Reproduce**
1. Go to https://www.freecodecamp.org/news/

**Screenshots**
![image](https://user-images.githubusercontent.com/26724128/51082276-f602fe00-1729-11e9-95ee-9995b4bb6015.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (32 bit)
 - Browser: Google chrome
 - Version: Latest stable release

**Comment by raisedadead** [comment]
Hi Thanks for reporting. We are moving some servers around, to make the site more faster. This is a quick maintenance run.

Thanks for reporting.
