### ISSUE TITLE
ES6 Challenge requiring const does not require the variable to be in all caps

### ISSUE THREAD

**Issue by adambrikman** [freeCodeCamp/freeCodeCamp#34888]
**Describe your problem and how to reproduce it:**

Best practice in ES6 for const is to name the variable in all caps. However, the exercise this variable is in all lowercase in order to pass.

**Add a Link to the page with the problem:**

Here is the link to the exercise: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-arrow-functions-to-write-concise-anonymous-functions

**Tell us about your browser and operating system:** 
* Browser Name: Chrome
* Browser Version: 
* Operating System: OS Sierra

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ezioda004** [comment]
Hi @adambrikman,

Thank you for opening this issue. 
We've previously discussed this in https://github.com/freeCodeCamp/freeCodeCamp/issues/19037

Please refer to that discussion.
Closing this issue but feel free to open if you're proposing something else.

Happy contributing!
