### ISSUE TITLE
decodeHTMLEntities causes build failure

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#34889]
The `decodeHTMLEntities` utility (`client/utils/decodeHTMLEntities.js`) currently interacts with the DOM to carry out it's function. In a client build, there is no DOM available so this process throws an error.

We need to investigate changing the implementation of `decodeHMTLEntities` to use a package like [`entities`](https://www.npmjs.com/package/entities). I would also like a `jest` test suite to perform unit tests of this utility.

**Comment by raisedadead** [comment]
Removing the first timers issue, those are only for good first time trivial issues with open source.

**Comment by ValeraS** [comment]
@Bouncey We can use [`he`](https://www.npmjs.com/package/he) package instead of `decodeHTMLEntities`. And we do not need to test it.

**Comment by Bouncey** [comment]
I would like a test just to ensure the implementation does not rely on the DOM. I do not mind which package is used, preferably the smaller one.
