### ISSUE TITLE
 Storing Values with the Equal Operator show error 404

### ISSUE THREAD

**Issue by frodriguez20H** [freeCodeCamp/freeCodeCamp#34895]
**Describe your problem and how to reproduce it:**
In section: "_Basic JavaScript: Generate Random Fractions with JavaScript_" when click on **Storing Values with the Equal Operator show error 404**.

**Add a Link to the page with the problem:**
[Storing Values with the Equal Operator](https://learn.freecodecamp.org/storing-values-with-the-assignment-operator)

**Tell us about your browser and operating system:**
* Browser Name: _Chromium_
* Browser Version: _71.0.3578.98_
* Operating System: _Ubuntu 18.04.1 LTS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![fireshot capture 12 - page not found i freecodecamp_ - https___learn freecodecamp org_sto](https://user-images.githubusercontent.com/30240505/51379743-063f2280-1b08-11e9-8ee5-27c06d78be8b.png)

**Comment by thecodingaviator** [comment]
That is happening because the correct link is : https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/storing-values-with-the-assignment-operator ans the challenge is called: Storing Values with the Assignment Operator

**Comment by thecodingaviator** [comment]
@frodriguez20H You also need to make a Pull Request to the main FreeCodeCamp master branch for your commits to be merged. Or, if you want, I'll take this up
