### ISSUE TITLE
Legacy Data Vis certification id has migrated

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#34890]
There is a disparity between the current Legacy Data Vis Cert ID and what was once the Data Vis Cert at the beginning of 2018.

Legacy Cert id for Data Viz: 561add10cb82ac39a17513bc (on master)
Legacy Data Vis Cert id found in some user records: 561add10cb82ac38a17513b3

**Comment by moT01** [comment]
I did some related investigating on this...
https://github.com/freeCodeCamp/freeCodeCamp/issues/17424

**Comment by ahmadabdolsaheb** [comment]
@Bouncey, I think there is a similar problem with fullstack certs. I am curious, how did you find out they were different?
