### ISSUE TITLE
The folder has an error in spelling

### ISSUE THREAD

**Issue by andreystar** [FreeCodeCamp/FreeCodeCamp#3489]
remvoe old passport file, looks like it was intended to be "remove old passport file".

**Comment by BerkeleyTrue** [comment]
Can you point me to the folder in question?

**Comment by erictleung** [comment]
I think he's referring to the commit message being misspelled.
![error](https://cloud.githubusercontent.com/assets/2754821/10111867/d9b254f8-638b-11e5-8048-ac37202094aa.png)

**Comment by BerkeleyTrue** [comment]
That is the last commit message that touched that folder. It was probably me, I often switch letters around when I'm typing in a hurry. 

Happy Coding!
