### ISSUE TITLE
Streak Count reset if doing more than 20 challenges in a day?

### ISSUE THREAD

**Issue by michaelwright74** [freeCodeCamp/freeCodeCamp#34898]
Firstly here is my profile - https://www.freecodecamp.org/michaelwright74

Although I have completed challenges every day since January 1st it is showing my Longest Streak as 8 Days and my Current Streak as 5 Days. It seems to be related to doing more than 20 challenges in a day as I show below.

Date - No. of Challenges
---------------------------
Jan 1 - 6
Jan 2 - 8
Jan 3 - 12
Jan 4 - 5
Jan 5 - 5
Jan 6 - 6
Jan 7 - 6
Jan 8 - 19
Jan 9 - 22* - Streak breaks and previous 8 days are shown as my longest streak
Jan 10 - 4
Jan 11 - 5
Jan 12 - 12
Jan 13 - 22* Streak breaks again and following 5 days represent my Current Streak number
Jan 14 - 2
Jan 15 - 5
Jan 16 - 5
Jan 17 - 5
Jan 18 - 5

As you see both times the streak count reset were on days I completed 22 challenges. Note also that on Jan 8th I completed 19 challenges without it causing this issue so it could be that anything 20 or over could be the break point maybe, but certainly 22 for sure.

**Comment by raisedadead** [comment]
Some fixes are underway in our next release. We can revisit if this exists post that. I am closing this for now
