### ISSUE TITLE
A test case is missing from challenge "Object Oriented Programming: Inherit Behaviors from a Supertype"

### ISSUE THREAD

**Issue by rupali317** [freeCodeCamp/freeCodeCamp#34905]
**Describe your problem and how to reproduce it:**
In the challenge: "Object Oriented Programming: Inherit Behaviors from a Supertype", the exercise states that we have to use Object.create to make 2 instances of Animal.

However, if we do not use Object.create and instead use new Animal(), all the test cases will still work. 

We should have another test case which checks if we are using Object.create, as the instruction states so.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/inherit-behaviors-from-a-supertype

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Windows 10 Home

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![inherit_behaviour_from_supertype_oop](https://user-images.githubusercontent.com/5875663/51425550-5c02f000-1c18-11e9-96cf-87ecb1f72a72.JPG)

**Comment by thecodingaviator** [comment]
We can test user code using a regex

**Comment by ezioda004** [comment]
I cant think of another way of fixing it aside from having an additional test with regex.

**Comment by rupali317** [comment]
Can I take up this task, if no one has started on it? Would like to contribute

**Comment by thecodingaviator** [comment]
Aditya I think Id like to see more discussion on this. Adding a reflex test isn’t the only possible solution. The challenge is to create an object so we can have the user doing it both the ways and check both using a regex

**Comment by ezioda004** [comment]
@thecodingaviator The challenge is to create a new object with its `__proto__` delegating to `Animal.prototype`. We've already taught how to create an instance with `new` operator, this challenge is about using `Object.create()` to do the same. Therefore we cannot have the camper use `new` operator since the challenge is not about that.
```js
const cat = new Animal();
```
Or
```
const cat = Object.create(Animal.prototype);
```
Results in the same object, so regex is or best way of limiting it.

**Comment by rupali317** [comment]
@ezioda004 @thecodingaviator I am able to setup my local dev environment now. So for this issue, I am thinking of having these 2 test cases:
**Test case 1:**  Instances should be created using **Object.create**. 
     A regex will be done to see that Object.create(Animal.prototype) has been used
**Test case 2:**  Solve this challenge without using **new Animal()** way.
     A regex will be done to check that new Animal() is not used anywhere

Is it fine? What do you think?

**Comment by rupali317** [comment]
Ok there is already a PR on this, which works
