### ISSUE TITLE
Capitalize test text for Cascading CSS variables

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/freeCodeCamp#34904]
**Describe your problem and how to reproduce it:**
Challenge test text typically capitalized, but the one for Cascading CSS Variables is not.

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-css/cascading-css-variables.english.md

Live: https://learn.freecodecamp.org/responsive-web-design/basic-css/cascading-css-variables

**Suggested Change:**

```diff
tests:
- - text: declare the <code>...
+ - text: Declare the <code>...
```

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Chrome
* Operating System: Chrome OS

**Comment by techednelson** [comment]
Hello @erictleung  can I work on this issue?


kind regards!

**Comment by huyenltnguyen** [comment]
@techednelson Go for it! Thanks for giving us a hand!

You will need to follow the [Contribution Guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md) to set up freeCodeCamp locally. Also, we are hanging out in [Gitter's Contributors chatroom](https://gitter.im/FreeCodeCamp/Contributors). You can ask for help there, or just come say hi :)

**Comment by techednelson** [comment]
@erictleung  Thanks, yeah sure, see you at Glitter's Contributors chatroom 👍

**Comment by rushic24** [comment]
is it fixed ? i would like to contribute ?

**Comment by erictleung** [comment]
@rushic24 there has been a pull request already submitted https://github.com/freeCodeCamp/freeCodeCamp/pull/34910. Thanks for your interest! Please take a look at the other issues. Happy coding!

**Comment by GiacomoLaw** [comment]
Hello

**Comment by theREALaltoid** [comment]
Close the issue?
