### ISSUE TITLE
Basic JavaScript: Local Scope and Functions, global variable declaration passes the test

### ISSUE THREAD

**Issue by co16353sidak** [freeCodeCamp/freeCodeCamp#34909]
**Describe your problem and how to reproduce it:**
While working inside the coding challenge "Basic JavaScript: Local Scope and Functions", I found out that while the challenge works fine if you declare a local 'var' variable inside the function 'myLocalScope' and then deleting the log out at the end. **as usual.**

But, initially accidentally I wasn't paying attention and declared the 'myVar' outside of the function scope just below its call, and the challenge validated it as correct and completed the test.
Not being a complete beginner I was able to recognize the problem, but I am aware most beginners maybe stumble upon this problem and accidentally may learn the wrong thing or **may NOT learn this properly.**
The test looks out for global variables as variables not being declared by any 'var' keyword but it misses out variable declarations outside of the scope of the function but using the 'var' keyword, which are **also global variables** and shouldn't be validated.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/local-scope-and-functions

**Tell us about your browser and operating system:**
* Browser Name: Safari
* Browser Version: 12.0.2 (14606.3.4)(Latest)
* Operating System: MacOS Mojave 10.14.2

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="1388" alt="screenshot 2019-01-19 at 8 31 05 pm" src="https://user-images.githubusercontent.com/35738138/51428442-a6409d00-1c29-11e9-8d6a-9bc877ddb3e5.png">
<img width="1214" alt="screenshot 2019-01-19 at 8 33 06 pm" src="https://user-images.githubusercontent.com/35738138/51428444-accf1480-1c29-11e9-9e42-fa16778fd3d7.png">

**Comment by rupali317** [comment]
I have opened a PR, which modifies the test case for checking if the variable is a local scope of the function. Did a regex test

**Comment by co16353sidak** [comment]
Hopefully this fixes the issue. @rupali317 
Even though I think it was already throwing an error if we declare a global variable (by not using var keyword)
But the bug came when we used the var keyword.
