### ISSUE TITLE
Palindrome Challenge (Returns correct boolean value but won't mark them as passed).

### ISSUE THREAD

**Issue by sreimer15** [FreeCodeCamp/FreeCodeCamp#3490]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
newArray = []
function palindrome(str) {
  str = str.replace(/\W/g, '');
  str = str.replace(/[.,-\/#!$%\^&\*;:{}=\-_`~()]/g, '');
  
  var length = str.length;
  var lowerstring = str.toLowerCase();
  var arrayString = lowerstring.split("");
  var oldArrayCount = arrayString.length-1;
  for (var letter = 0; letter < length; letter++)  {
    var lastLetter = arrayString[oldArrayCount];
    newArray.push(lastLetter);
    oldArrayCount = oldArrayCount - 1;
    
  }
  var arrayLength = newArray.length;

  for (var count = 0; count < arrayLength; count++) {

    if( newArray[count] === arrayString[count] ) {
        continue;
    }
    else {
      return false;
    }
  }
  
  return true;
}



palindrome("nope");

```

**Comment by gt50** [comment]
Move newArray inside your palindrome function and all tests will pass. The global variable value is not being reset between successive calls to palindrome.

**Comment by bugron** [comment]
@sreimer15 thanks for posting this issue!
@gt50 is correct. Move `newArray = []` into your `palindrome` function. Closing this issue. Feel free to reopen if you still experience problems, thanks.

 >***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
