### ISSUE TITLE
Radio buttons challenge missing value attributes

### ISSUE THREAD

**Issue by Bubsy3D** [freeCodeCamp/freeCodeCamp#34901]
<p style="font-size:12px">
In the <a href="https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-set-of-radio-buttons">create-a-set-of-radio-buttons and the following create-a-set-of-checkboxes</a> challenge the buttons are missing the <strong>value</strong> attribute. If you send a form you wouldn't get what button was chosen but "radio-group=on" instead.
I think this is something to fix because beginners like myself could assume that either the id, label or inner text of the input determine the value that is sent, but I don't have the fluency in JavaScript needed to do that
<br>
You can try submitting the form in this html to see what I'm saying.
[radioValue.html.txt](https://github.com/freeCodeCamp/freeCodeCamp/files/2774263/radioValue.html.txt)

</p>

**Comment by zainulabidin302** [comment]
Hey, The link in the comment is broken.
<img width="810" alt="screen shot 2019-02-05 at 8 36 48 pm" src="https://user-images.githubusercontent.com/7473349/52284218-c9877e00-2985-11e9-9d8f-a4e5433c33cf.png">

**Comment by Bubsy3D** [comment]
> 
> 
> In the [create-a-set-of-radio-buttons and the following create-a-set-of-checkboxes](https://www.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-set-of-radio-buttons challenge) challenge the buttons are missing the **value** attribute. If you send a form you wouldn't get what button was chosen but "radio-group=on" instead. I think this is something to fix because beginners like myself could assume that either the id, label or inner text of the input determine the value that is sent, but I don't have the fluency in JavaScript needed to do that
> You can try submitting the form in this html to see what I'm saying. [radioValue.html.txt](https://github.com/freeCodeCamp/freeCodeCamp/files/2774263/radioValue.html.txt)

**Comment by Bubsy3D** [comment]
should work now

**Comment by co16353sidak** [comment]
Hi, has this been fixed or can I have a go at it?
@Bubsy3D @ahmadabdolsaheb

**Comment by Bubsy3D** [comment]
yes it has, the link works now. But you could also easily find it in the freecodecamp curriculum / responsive web design / basic html and html 5

**Comment by Bubsy3D** [comment]
no it hasn't

**Comment by RandellDawson** [comment]
@Bubsy3D, @co16353sidak  What are your suggestions for the challenge description and example code that users should see?

Let's get the content agreed upon, so @co16353sidak or someone else can help create a PR with what is decided here.

**Comment by co16353sidak** [comment]
@RandellDawson
1. How about adding another test that ensures the presence of a value attribute
2. Or if that seems too extreme, we could just include the value attribute in our challenge’s example.
3. Or/And add a note describing the importance of the value attribute

**Comment by RandellDawson** [comment]
The challenge information is supposed to be short and concise and teach something specific.  The intent of this challenge is not have the user create a form which would be used to submit capture the `value` attribute.  I believe this type of information is better served as additional information in the Guide instead.   

@co16353sidak My thought on your 3 suggestions is as follows:

1. Seems beyond the scope of this challenge.

2. I think this is fine as long as somewhere in the challenge description there is a short mention of its importance.

3. This could be a nice add-on

Maybe there is another place in the curriculum where something like this could fit in.  If you find a place where it could be worked into an existing challenge or be added as a new challenge, then we can definitely discuss that as a possiblity.

**Comment by vineshSwargam** [comment]
Hi @RandellDawson,
If adding the value attribute in our challenge example is fine, can I have a go at it?
Would be my first OS project.

**Comment by RandellDawson** [comment]
Let's see if there are some other collaborators who have an opinion on this.

**Comment by co16353sidak** [comment]
@RandellDawson 

Would it be viable if we create a separate challenge towards adding a value attribute and mentioning its significance, implementing the value attribute in another challenge won't serve as a proper justification towards its use.
Other than that, adding the value attribute to examples would then mean editing all form examples in many challenges. that too doesn't seem too viable.

**Comment by cartagenae** [comment]
I don't understand what the problem is. I ran the code here just fine on the webpage. The labels and the radio buttons displayed properly on the view (web page) and embedded within the form tags.

    <label for="indoor">
      <input id="indoor" type="radio" name="indoor-outdoor" /> Indoor
    </label>
    <label for="outdoor">
      <input id="outdoor" type="radio" name="indoor-outdoor" /> Outdoor
    </label>

**Comment by co16353sidak** [comment]
@cartagenae There is as such no problem with the challenge but the use of value attribute is being discussed here

**Comment by bdwolff** [comment]
I have the solution but am trying to figure if this is an exercise or a real problem.

**Comment by lasjorg** [comment]
This applies to grouped checkboxes as well (i.e. checkboxes with the same name attribute value). In the following challenge for input of type checkbox, 3 grouped checkboxes are made.

I think the best option is to make a new challenge after the radio-buttons and checkbox challenges which introduces the value attribute. I actually had a PR ready for this but was never super happy about it so I didn't push it. I had forgotten all about it. Should I push it to get some feedback on it?

Note: The next challenge after this new challenge will need it's Challenge Seed updated as well to include the new form with the value attributes added.

**Comment by RandellDawson** [comment]
@lasjorg I say go ahead and submit your PR.

**Comment by AlexanderMike2018** [comment]
How can I solved that problem, **Use the value attribute with Radio Buttons and Checkboxes**?

**Comment by ShaunSHamilton** [comment]
Hello @AlexanderMike2018 ,

If you need any assistance, feel free to reach out on the [forum](https://forum.freecodecamp.org/)

Happy coding 😃

---

This issue is old and resolved. As such, I am going ahead and locking it.
