### ISSUE TITLE
Use React to Render Nested Components - crashes browser

### ISSUE THREAD

**Issue by kthurman59** [freeCodeCamp/freeCodeCamp#34911]
**Describe your problem and how to reproduce it:**
When I get to the bottom of this challenge it crashes both Chrome and Firefox.  All extensions/add-ons are off and cached cleared several times.  Despite all this, it freezes the site, then eventually crashes. 

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/front-end-libraries/react/use-react-to-render-nested-components

**Tell us about your browser and operating system:**
* Browser Name:  Chrome and Firefox
* Browser Version: Latest on both
* Operating System:  Windows 7

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ldaws003** [comment]
Could you show me the code that you put on the challenge?

**Comment by kthurman59** [comment]
const TypesOfFruit = () => {
return (
<div>
<h2>Fruits:</h2>
<ul>
<li>Apples</li>
<li>Blueberries</li>
<li>Strawberries</li>
<li>Bananas</li>
</ul>
</div>
);
};

const Fruits = () => {
return (
<div>
{ /* change code below this line */ }
<TypesOfFood />
<Fruits />
{ /* change code above this line */ }
</div>
);
};

class TypesOfFood extends React.Component {
constructor(props) {
super(props);
}

render() {
return (
<div>
<h1>Types of Food:</h1>
{ /* change code below this line */ }
<Fruits /> ----- THIS IS WHERE THINGS GO BAD. AS SOON AS I TYPE 'FRUITS'
THE BROWSER HANGS AND THEN CRASHES AFTER A FEW MINUTES.
{ /* change code above this line */ }
</div>
);
}
};
Kevin Thurman


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by saranshkataria** [comment]
const Fruits = () => {
return (
<div>
{ /* change code below this line */ }
<TypesOfFood />
<Fruits />
{ /* change code above this line */ }
</div>
);
};

You are calling <Fruits /> inside Fruits() making it a recursive nested call to itself which leads to the crash

**Comment by ldaws003** [comment]
saranshkataria is right. Having ```<Fruits />``` nested in ```Fruits()``` isn't required and will cause an infinite recursion leading to a crash. Removing it will make your code work without any problems. Maybe there should be callstack limitations in the future for react challenges like there is for javascript challenges?

**Comment by kthurman59** [comment]
You are correct.  This was my bad entirely.  Everything worked.  Thank you!

**Comment by ezioda004** [comment]
Thank you @saranshkataria and @ldaws003 for helping out.
Closing as its not an issue.

Happy contributing all!
