### ISSUE TITLE
'Run tests' button not responding

### ISSUE THREAD

**Issue by Khoshekh** [FreeCodeCamp/FreeCodeCamp#3491]
jQuery challenges/waypoints 'run tests' button is not functioning for me. It's still working for all the other waypoint challenges up until the jQuery series. I was working on them earlier today and it was fine, but now I'm on a different computer. Any suggestions?

**Comment by maciejsartys** [comment]
Which browser do You use? Only Chrome is officially supported.
25 wrz 2015 04:58 "Khoshekh" <notifications@github.com> napisał(a):

**Comment by Khoshekh** [comment]
Thanks for getting back to me so fast! I was working on explorer when I
encountered the problem with the 'run tests' button. I am usually on
chrome, though. Appreciate it.

**Comment by bugron** [comment]
@Khoshekh  thanks for posting this issue!
[We officially support only Chrome browser](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2942#issuecomment-136591448) (but latest Firefox should work too). Closing this issue. Feel free to reopen if you still experience problems, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
