### ISSUE TITLE
Basic Javascript 

### ISSUE THREAD

**Issue by evertalbers** [freeCodeCamp/freeCodeCamp#34924]
I notice that one specific assignment, “Word Blanks”, comes too early - it uses a function before functions have been explained.  Link: 
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/word-blanks

Anyway, I skipped this assignment, and am now about twice as far into the course - I think this is about the place where the assignment should go.

**Comment by inh556** [comment]
Hi Evert, 

This assignment is able to be solved without any function knowledge. Here what you need to do is to make up a sentence with the passed in parameters and assign it to result. Just give it a shot to see if you can solve it.

**Comment by evertalbers** [comment]
Thanks!
OK, I'll close this issue then. A factor that did not help is that I'm not familiar with the words for English grammar mentioned in in the assignment. (back in highschool my grades for English went up significantly when I stopped trying to understand the grammar and just used the sentences that felt best - don't tell your kids)

**Comment by fadaile** [comment]
OK
