### ISSUE TITLE
Code not passing simple exercise. 

### ISSUE THREAD

**Issue by daputnam** [FreeCodeCamp/FreeCodeCamp#3492]
**I reloaded the code in a different window and it worked. **

Challenge [Waypoint: Change the Font Size of an Element](http://freecodecamp.com/challenges/waypoint-change-the-font-size-of-an-element) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  p {
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

<p> kitty ipsum text: Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched. </p>

```

**Comment by awesomeaniruddh** [comment]
I believe the issue has thus been resolved? Closing this. Feel free to reopen if the issue has *not* been resolved :)
