### ISSUE TITLE
Hex Code not allowed in "Applied Visual Design: Adjust the Hover State of an Anchor Tag".

### ISSUE THREAD

**Issue by Hahlh** [freeCodeCamp/freeCodeCamp#34932]
Good day, everybody!

Hopefully you have had a great day so far :)

I want to mention a possibility for improvement.

In the lesson ["Applied Visual Design: Adjust the Hover State of an Anchor Tag"](https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/adjust-the-hover-state-of-an-anchor-tag) the task is:

_The code editor has a CSS rule to style all `a` tags black. Add a rule so that when the user hovers over the `a` tag, the `color` is blue._

The code window shows:

```
<style>
  a {
    color: #000;
  }
  
  
  
</style>
<a href="http://freecatphotoapp.com/" target="_blank">CatPhotoApp</a>
```

The lesson doesn't allow to solve this task using HexCode:

```
<style>
  a {
    color: #000;
  }
  a:hover {
    color: #00F;
  }
   
  
  
</style>
<a href="http://freecatphotoapp.com/" target="_blank">CatPhotoApp</a>
```

I think that this solution (and others; I tested rgb and rgba and both don't work as well) should be allowed as the code already entered suggests using this way of expressing "blue" and the task itself doesn't state anything about how to express it. 
Hex code and other ways of expressing "blue" were taught already at this point.

![screenshot from 2019-01-22 21-35-16](https://user-images.githubusercontent.com/45669613/51560706-f9b32500-1e8d-11e9-9492-bbbc3e7194b6.png)

michael-wise pointed this already out in the FCC forum. A bot referred him to GitHub, but I was unable to locate the issue here.

Of course, this is just a minor issue, but I hope this nevertheless helps!

All the best,

Leo

**Comment by ojeytonwilliams** [comment]
I see what you mean - the test checks if the solution contains 'a:hover {color: blue}', not if the link actually turns blue.  I'll see what I can do.
