### ISSUE TITLE
Bad solution to the problem- sloppy code passes, but simple clear code doesn't

### ISSUE THREAD

**Issue by daputnam** [FreeCodeCamp/FreeCodeCamp#3493]
Challenge [Waypoint: Add Borders Around your Elements](http://freecodecamp.com/challenges/waypoint-add-borders-around-your-elements) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This Sloppy code works: 
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }
  
  thick-green-border {
  /* nothing in here */
  }
  
  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .smaller-image {
     /*stuff that should be in thick-green-border here */    
     width: 100px;
     border-style: solid;
     border-color: green;
     border-width: 10px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```
and this better code does not:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }
  
  thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
  }
  
  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

What is going on? Is this because I'm using Safari? How is a person supposed to learn coding this way?

**Comment by whiteknightjanus** [comment]
Check your code - your class for thick-green-border is missing the period
in the CSS

**Comment by awesomeaniruddh** [comment]
Yep. I believe this can be fixed by replacing `img` in the tests by `thick-green-border`. Testing it right now.

**Comment by awesomeaniruddh** [comment]
Ok it can't. I'll have to mess with some regex for this it seems.

**Comment by Deftwun** [comment]
works for me after prefixing the period to `thick-green-border`

**Comment by tva10** [comment]
Today I founded this problem too in GoogleChrome (so I passed this task few weeks ago):
I decided to add a script using testcase from task `<script type="text/javascript">
  console.log($('img.smaller-image').css('border-top-width'));
</script>
`
to check the size and got `9.333px` because I use `scale 75%`. 

![image](https://cloud.githubusercontent.com/assets/14250295/10171902/0752ab18-66e5-11e5-859d-f15d665b8a74.png)

When I set it on `100%` it is becomes `10px`.
![image](https://cloud.githubusercontent.com/assets/14250295/10171788/85861b60-66e4-11e5-8340-5e63afbd9159.png)
When I set scale on `125%` it becomes 9.6px. 
![image](https://cloud.githubusercontent.com/assets/14250295/10171866/e5f04bba-66e4-11e5-9023-aa557cb78716.png)

**Comment by jbmartinez** [comment]
I think a CSS parser is the better way to check if the styles are correctly written, but it might require to rewrite some (many?) waypoints.

In any case, the problem here is the missing period in front of the `thick-gree-border` class selector in the CSS rule.

**Comment by ltegman** [comment]
Closing this as the issue was related to the missing `.` before `thick-green-border` in the answer and not the tests.

Feel free to reopen if you have any further concerns.

Thanks and happy coding!
