### ISSUE TITLE
Using bracket notation breaks this.

### ISSUE THREAD

**Issue by NicolasVsa** [freeCodeCamp/freeCodeCamp#34930]
[https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/updating-object-properties/](url)

using dot notation works just fine though.

**Comment by thecodingaviator** [comment]
The link is inaccessible. Try clicking on it and see where it redirects you

**Comment by ezioda004** [comment]
Hi @NicolasVsa,

I've tested the above challenge and both bracket and dot notation works fine. 
I'm closing this as I cant find any bugs on this but feel free to open it if the problem persists.

Happy coding!

**Comment by NicolasVsa** [comment]
what do you mean it still doesnt work with bracket notation lol i just tested it

**Comment by NicolasVsa** [comment]
try this code // Example
var ourDog = {
  "name": "Camper",
  "legs": 4,
  "tails": 1,
  "friends": ["everything!"]
};

ourDog.name = "Happy Camper";

// Setup
var myDog = {
  "name": "Coder",
  "legs": 4,
  "tails": 1,
  "friends": ["freeCodeCamp Campers"]
};

// Only change code below this line.

myDog[name] = "Happy Coder"

**Comment by ezioda004** [comment]
myDog[name] is incorrect. It should be myDog["name"]. 

Please use our forums if you need help with challenges.
