### ISSUE TITLE
DOC: Style for challenges does not include any information about solution format.

### ISSUE THREAD

**Issue by paulywill** [freeCodeCamp/freeCodeCamp#34957]
As per the [sytle guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-curriculum-challenges.md#writing-tests), there is not mention about placing the solution in proper markdown tags.

ie 
```
<section id='solution'>
three backticks + html or js

 [ SOLUTION CODE]

three backticks
</section>
```
The result renders differently on Github markdown pages altough the CI tests pass regardless.

**Comment by Dana94** [comment]
@paulywill Are you suggesting instructions in `style-guide-for-curriculum-challenges.md` for how to properly write the solution?

**Comment by paulywill** [comment]
@Dana94 yes.

**Comment by Dana94** [comment]
@paulywill I could work on this. I've been meaning to try to contribute more to the docs.
