### ISSUE TITLE
A test case is missing from challenge "Intermediate Algorithm Scripting: Missing Letters"

### ISSUE THREAD

**Issue by ChiselD** [freeCodeCamp/freeCodeCamp#34958]
**Describe your problem and how to reproduce it:**
The test cases for this algorithm don’t cover a certain scenario: What if the string passed to the function is a substring of the alphabet (i.e. less than 26 characters long) but includes all characters of that substring in order? For example:
`fearNotLetter("bcdef")`
At present, code passes the challenge even without taking account of this potential input.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/missing-letters

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Mac OS Sierra version 10.12.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
This code passes, even with the final "return undefined" commented out:
<img width="492" alt="missing-test-case" src="https://user-images.githubusercontent.com/3756776/51771992-1d26db80-20eb-11e9-8b48-aa96b12d5ece.png">

**Comment by RandellDawson** [comment]
In JavaScript, if a function does not explicitly return a value, it returns `undefined` by default, so your function would still return `undefined` if the test case of `fearNotLetter("bcdef")` were to be added (which is not necessary).

In fact, you do not even need the following code:
```
  if (str === ALPHABET) {
    return undefined;
  }
```
I am closing this a non-issue.  If you still believe there is a problem, please reply back to this issue and we can look at reopening it.

Thank you

**Comment by tb47** [comment]
Good morning Randell,

sorry for replying to this topic. I was proud to have a own solution, but then I figured out that it just passes the test, but does not solve the task. Reasons are mentioned by ChiselD:

`function fearNotLetter(str) {
  let abc = 'abcdefghijklmnopqrstuvwxyz';
  let test = abc.slice(abc.indexOf(str[0]))
  if (str === abc) { return undefined }
  for (let i = 0; i < str.length+1; i++) {
    if (str.indexOf(test[i]) < 0) {
      return test[i];
    }
  }
}`

**Comment by RandellDawson** [comment]
> but then I figured out that it just passes the test, but does not solve the task. 

Why do you believe your code does not solve the task?
