### ISSUE TITLE
[Guide] Update tutorial - Debugging JavaScript with Browser Devtools 

### ISSUE THREAD

**Issue by cc189** [freeCodeCamp/freeCodeCamp#34960]
FCC update code editor from `CodeMirror` to `Monaco Editor`, document need to be updated.

Edit by `@raisedadead`:

These files need to be updated:

https://github.com/freeCodeCamp/freeCodeCamp/blob/da0df12ab7b3bae46c2a376da246a6c499afd88b/guide/russian/javascript/tutorials/debugging-javascript-with-browser-devtools/index.md

**Comment by thesidbatra** [comment]
Could you please add a link to the specific document? Thanks!

**Comment by RandellDawson** [comment]
@raisedadead What are your opinions on this?

**Comment by rituteb** [comment]
To confirm, @cc189 & @raisedadead, you're suggesting to change all references of CodeMirror to Monaco Editor in this guide (should it point to https://microsoft.github.io/monaco-editor/)? Assuming this should be done in all translations. I can go ahead and make this change once this is confirmed.

**Comment by raisedadead** [comment]
Yes. that is correct @rituteb

**Comment by cc189** [comment]
Sounds good @rituteb
