### ISSUE TITLE
On completing a challenge, pressing "Ctrl + Enter" after downloading solution, downloads the solution again 

### ISSUE THREAD

**Issue by rupali317** [freeCodeCamp/freeCodeCamp#34967]
**Describe the bug**
After downloading the solution, pressing the shortcut (Ctrl +  Enter) should take us to the next challenge. However, it also downloads the solution.

**To Reproduce**
1. Complete a challenge
2. Click on "Run the Tests"
3. (Assuming you have passed the test cases), a modal window appears with 2 options - "Submit and go to next challenge(Ctrl + Enter)" and "Download my solution"
4. Click on "Download my solution", which will download the solution in json format
5. Press Ctrl + Enter
6. Solution is downloaded again
7. We are taken to the next challenge

**Expected behavior**
On pressing Ctrl + Enter after downloading the solution, we should be taken to the next challenge as it is the shortcut for "Submit and go to next challenge(Ctrl + Enter)". It should not download the solution again.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome
 - Version: 71.0.3578.98

**Comment by monmanuela** [comment]
I could reproduce the bug, and I'd like to try to fix this. Could someone help point me in the right direction?

**Comment by rupali317** [comment]
@monmanuela i was also thinking of working on this issue. Would you like to work on this together? I am new to this repository as well

**Comment by monmanuela** [comment]
@rupali317 sure! That'll be great.

**Comment by rupali317** [comment]
This issue happens provided the person is signed in to FCC. This bug does not happen when the user is signed out
