### ISSUE TITLE
Bonfire: Make a Person Description and Tests

### ISSUE THREAD

**Issue by guipsamora** [FreeCodeCamp/FreeCodeCamp#3496]
In the description there is a term called arity that is labeled as obsolete at [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/arity). If the term is obsolete and deprecated wouldn't it be better to take it off?

Furthermore in the tests you have the methods duplicated, whereas it should be like this:

* expect(bob.getFirstName()).to.eql('Bob');
* expect(bob.getLastName()).to.eql('Ross');
* expect(bob.getFullName()).to.eql('Bob Ross');
* expect(bob.getFirstName()).to.eql('Happy'); -> should be bob.**set**FirstName()).to.eql('Happy');
* expect(bob.getLastName()).to.eql('Trees'); -> should be bob.**set**LastName()).to.eql('Happy');
* expect(bob.getFullName()).to.eql('George Carlin'); -> should be bob.**set**FullName()).to.eql('Happy');

Thanks!! ;)

**Comment by BerkeleyTrue** [comment]
The term `arity` is used but does not refer to `Function.arity` which is a deprecated property of a function. 

See [arity](https://en.wikipedia.org/wiki/Arity)

Happy Coding

**Comment by guipsamora** [comment]
Hi, 

Thank you Berkeley!!

I still think it can confuse other campers as I was. What about attaching this link or a better source to the bonfire? Or simply writing "All functions that take an argument have an arity**(number of arguments give to a function)** of 1, and the argument will be a string."

I think is really important to know the terms but as it is the user can 1- ignore it (thus not learning), 2 - go easily to wrong sources (like I did, which is even worse).

Have you read about the tests methods names? Should they be get... or set...(as it is in the description)?

Thanks!! ;)
