### ISSUE TITLE
Dead link on search results (Sorted Union)

### ISSUE THREAD

**Issue by Nitin96Bisht** [freeCodeCamp/freeCodeCamp#34970]
**Describe your problem and how to reproduce it:**
A link to specific guide leads to 404 page.

**Add a Link to the page with the problem:**
In the [Search Result Page](https://search.freecodecamp.org/?q=sorted%20union%22%0A). Linked page: Guide: [Sorted Union](https://guide.freecodecamp.org/certificates/sorted-union)

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 71.0.3578.98
* Operating System: Windows 7 Professional

![capture](https://user-images.githubusercontent.com/23516674/51815447-f8975300-22e6-11e9-95b3-18d0d1ac04ca.PNG)

**Comment by aditijoshi14** [comment]
@Nitin96Bisht Do you happen to know the link for this guide or is this something we should be creating from scratch?

**Comment by Wishnia** [comment]
I would love to fix that issue, could I?

**Comment by Nitin96Bisht** [comment]
@aditijoshi14 There must be an existing link definitely. However It may be incorrect or wrong link. You need to check and correct it.

**Comment by Nitin96Bisht** [comment]
@Wishnia Yes, go ahead. 

Don't forget to read [contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md) before fixing it.

**Comment by ahmadabdolsaheb** [comment]
Hi @Wishnia, I was wondering if you are still working on this issue? Please let us know If we could help in any way.

**Comment by Wishnia** [comment]
@ahmadabdolsaheb Yep, I'm working on this issue right now. I figured out that the source of this bug is probably in [search-assets ](https://github.com/freeCodeCamp/search-assets) repo.

**Comment by Nitin96Bisht** [comment]
Hi @Wishnia, Are you still working on this issue?

**Comment by Wishnia** [comment]
@Nitin96Bisht No, I was trying, but at this moment I can't solve that issue.

**Comment by Nitin96Bisht** [comment]
@ahmadabdolsaheb If you want then you can work on this.

**Comment by Suyash2810** [comment]
Is anyone working on this? It still shows the same message as @Nitin96Bisht has shown. 
![Screenshot (250)](https://user-images.githubusercontent.com/42000949/54638097-38411680-4ab0-11e9-9086-2bf6310547b5.png)

**Comment by RandellDawson** [comment]
Actually this seems to be a non-issue on the beta site which will soon be moved to production.

https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sorted-union

When I click on the `Get a Hint` button, I am taken to the applicable guide article.

I am closing this for now, since it has been fixed but just not moved to production.

**Comment by RandellDawson** [comment]
This issue will be resolved once https://github.com/freeCodeCamp/freeCodeCamp/pull/35540 has been merged and the search index has been updated.

**Comment by Suyash2810** [comment]
Okay.
