### ISSUE TITLE
Clicking on link in the code preview opens up the web page within the web page

### ISSUE THREAD

**Issue by Hahlh** [freeCodeCamp/freeCodeCamp#34988]
Clicking on link in the code preview (for example on "The Garfield Files") opens up web page with all three modules again (Coding Challenge, Code field, Code preview).

![the garfeld files](https://user-images.githubusercontent.com/45669613/51849040-885cf180-2327-11e9-913e-31b392166a98.png)

![garfield2](https://user-images.githubusercontent.com/45669613/51849058-927ef000-2327-11e9-850b-016d1cc91218.png)

I don't know, if this is challenge specific. 

[
**Link to the page with the problem:**](https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/make-links-navigatable-with-html-access-keys/)

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: Firefox for Linux Mint 1.0
* Operating System: Linux Mint 18.3

**Comment by thecodingaviator** [comment]
This is due to how the rendering engine for our curriculum works. If you try this on a stand alone webpage, it won't happen.

**Comment by Hahlh** [comment]
Thank you for the explanation @thecodingaviator. 
May I ask, how I could open it on a stand alone web page? 
Could we maybe improve the issue, by inserting a dead link instead of leaving it empty?

**Comment by thecodingaviator** [comment]
When I say stand alone web page I mean the you copy the html part out from the FCC paste it in another new file on you PC and run.

What we can do is make a PR so that the href contains `"#"` and not `""`, that fixes it

**Comment by Hahlh** [comment]
@thecodingaviator 

That is a valuable piece of information, thank you!
I will create the PR immediately.
