### ISSUE TITLE
A bug or typo mistake

### ISSUE THREAD

**Issue by BabarKhann** [freeCodeCamp/freeCodeCamp#34993]
![1](https://user-images.githubusercontent.com/15844043/51904109-a0904780-23df-11e9-9ac5-f89fd84bd69f.png)
![2](https://user-images.githubusercontent.com/15844043/51904123-aa19af80-23df-11e9-85f4-f1c9a1199307.jpg)

**Comment by RandellDawson** [comment]
It is always best if you post an actual link to the challenge also.

Thank you.

**Comment by BabarKhann** [comment]
Here is the URL.

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/returning-boolean-values-from-functions/

*Babar Khan*

**Comment by Wishnia** [comment]
I would love to fix that issue, could I?

**Comment by RandellDawson** [comment]
@Wishnia Sure.  You will need to setup and test your changes locally.

**Comment by BabarKhann** [comment]
How to setup ?

**Comment by RandellDawson** [comment]
Start by taking a look at [these instructions](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md).  If you have further questions or run into any problems, check out our [Contributors' Channel on Gitter](https://gitter.im/FreeCodeCamp/Contributors). You can post your questions there and someone will get back with you.

**Comment by ahmadabdolsaheb** [comment]
Thank you all for reporting and helping to resolve this issue.  👍

**Comment by BabarKhann** [comment]
😊


*Babar Khan*
