### ISSUE TITLE
Create challenges for Projects

### ISSUE THREAD

**Issue by Ronkiro** [freeCodeCamp/freeCodeCamp#35029]
**PROBLEM:** As reported on Issue #34763, one can pass under a Project challenge without having to do any real test.

**PURPOSE:** As a way to solve this, i think that creating basic questions and/or challenges that can acknowledge that you did it would be nice. It's just a step more to get the exercise completed, and can also help making one learn/consolidating what he learnt.

**Comment by raisedadead** [comment]
@Ronkiro Thanks. Let's continue this on #35015. The less fragmented the conversation, the better
