### ISSUE TITLE
Navbar buttons in local are not properly highlighted

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/freeCodeCamp#35028]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
In thelocal setup of fcc, the navbar buttons for curriculum, forum and news have a small white dash popping out of the white box.

**To Reproduce**

**Screenshots**
![screenshot 19](https://user-images.githubusercontent.com/36357875/52128311-0da91480-264e-11e9-9192-058342c3df52.png)

![screenshot 20](https://user-images.githubusercontent.com/36357875/52128315-0f72d800-264e-11e9-93cf-464fa8bda693.png)

![screenshot 21](https://user-images.githubusercontent.com/36357875/52128320-10a40500-264e-11e9-905d-e7c89eb9895b.png)

**Comment by ahmadabdolsaheb** [comment]
could not reproduce :(
<img width="436" alt="screen shot 2019-02-01 at 11 03 27 pm" src="https://user-images.githubusercontent.com/4591597/52146706-a010de80-2675-11e9-8923-ecf973191f53.png">

**Comment by Nirajn2311** [comment]
@ahmadabdolsaheb I meant it happens when you hover the cursor over the buttons, sry if I was not clear before.

**Comment by ronaldcs** [comment]
Couldn't repro either on a Windows 10 VM using Chrome, although I do see a border on the bottom when you hover.
<img width="1172" alt="screen shot 2019-02-05 at 11 14 44 pm" src="https://user-images.githubusercontent.com/4138434/52320213-0a8a8d00-299c-11e9-933d-d12fe3a60578.png">

**Comment by rupali317** [comment]
@Nirajn2311 which OS and browser are you using?
I tried to reproduce in local as well as the production site, I was unable to reproduce. I am on Windows 10 Home and using Chrome 71.0.3578.98

**Comment by Bouncey** [comment]
I cannot reproduce @Nirajn2311, feel free to raise a PR though. If it is effecting you, it will be the same for others

**Comment by Nirajn2311** [comment]
@ahmadabdolsaheb Strange, I could reproduce this only in Chrome(v72.0.3626.96).

**Comment by ahmadabdolsaheb** [comment]
@Nirajn2311 it might be a webkit specific styling. I wonder if you could track down that dash in the devtools by selecting the that element and moving up and down the dom tree and checking out the styles at the same time. That might be helpful :/

**Comment by ValeraS** [comment]
@Nirajn2311 Are you working on it? If needed, I can help.

**Comment by Nirajn2311** [comment]
@ValeraS Were you able to reproduce the issue?

**Comment by ValeraS** [comment]
@Nirajn2311 I can reproduce it when zooming page.

**Comment by Nirajn2311** [comment]
@ValeraS I couldn't figure out how to fix it, so you can start working on it.
