### ISSUE TITLE
Use the Spread Operator to Evaluate Arrays In-Place: Proper solution not given

### ISSUE THREAD

**Issue by co16353sidak** [freeCodeCamp/freeCodeCamp#35022]
**Describe your problem and how to reproduce it:**

Going through the problem, after being quickly introduced to the spread operator, it becomes kind of difficult to understand how to use it to copy an array into another.
**In the guide it could be useful to understand how the spread operator works in various ways instead of just using the math functions.**
I could open a pull request to modify the guide.
Also linking videos fails the main purpose of freecodecamp training which doesn't involve watching videos to learn but to learn with practice.

**Add a Link to the page with the problem:**

https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/es6/use-the-spread-operator-to-evaluate-arrays-in-place/

**Tell us about your browser and operating system:**
* Browser Name: Safari
* Browser Version: 12.0.3 (14606.4.5)
* Operating System: MacOS 10.14.3
 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="838" alt="screenshot 2019-02-01 at 11 53 15 am" src="https://user-images.githubusercontent.com/35738138/52106397-a1f88480-2618-11e9-98ed-6a297306728c.png">

**Comment by RandellDawson** [comment]
Did you have a look at the video shown in the Guide?  It goes into greater details there.

**Comment by co16353sidak** [comment]
Yes, but the format of this solution/hint should follow the format of other hints: firstly, containing a few hints and after that the final solution of the problem.

for example:-
<img width="730" alt="screenshot 2019-02-01 at 3 44 15 pm" src="https://user-images.githubusercontent.com/35738138/52116932-74bbce80-2638-11e9-9bdd-fac2cb3a3eae.png">

**Comment by RandellDawson** [comment]
You are more than welcome to add some hints if you like.  The hint/solution format you see in some of these older changes is not being used on new challenges, so it has not been a priority to make such changes.
