### ISSUE TITLE
Issue: docker-compose error for freecodecamp service

### ISSUE THREAD

**Issue by mmeyers00** [freeCodeCamp/freeCodeCamp#35030]
**Describe the bug**
`docker-compose` not working for the web app

**To Reproduce**
Run `docker-compose run --rm freecodecamp npm run only-once`

**Expected behavior**
Container to be created for **freecodecamp_freecodecamp_1**

**Screenshots**
![freecodecamp_error](https://user-images.githubusercontent.com/2049932/52138361-f0a71e00-261a-11e9-916c-e8760e16cd77.png)

**Comment by raisedadead** [comment]
The docker setup is outdated with the recent changes towards making the repo a mono repo. Pull request welcome.

**Comment by moT01** [comment]
@mmeyers00 @ahmadabdolsaheb, did that merge fix this? If so, we can close this.

**Comment by raisedadead** [comment]
Nope. As I mentioned in the PR, its unrelated to this.

**Comment by raisedadead** [comment]
We have a docker installation guide that is now quite stable. Closing.
