### ISSUE TITLE
Guide ES6: Use class Syntax to Define a Constructor Function, duplicate wrong solution given

### ISSUE THREAD

**Issue by co16353sidak** [freeCodeCamp/freeCodeCamp#35036]
**Describe your problem and how to reproduce it:**

Basically, there seems to be a wrong duplication in the guide and the latter one seems to suggest a solution which won't work.
The first one works fine and the last one should be deleted to avoid confusion and problems.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/es6/use-class-syntax-to-define-a-constructor-function/

**Tell us about your browser and operating system:**
* Browser Name: Safari
* Browser Version: 12.0.3 (14606.4.5)(Latest)
* Operating System: MacOS Mojave 10.14.3

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="834" alt="screenshot 2019-02-02 at 1 46 47 pm" src="https://user-images.githubusercontent.com/35738138/52161924-6fbb5580-26f2-11e9-9a9d-39df14476261.png">
<img width="442" alt="screenshot 2019-02-02 at 1 59 15 pm" src="https://user-images.githubusercontent.com/35738138/52161957-c6289400-26f2-11e9-91a8-6af35af6744c.png">

**Comment by ahmadabdolsaheb** [comment]
Thanks @co16353sidak for reporting this.
Here is the file to be changed if anyone is interested.
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/certifications/javascript-algorithms-and-data-structures/es6/use-class-syntax-to-define-a-constructor-function/index.md

just change the 'Vegetable' instances in the constructor to 'name'.

**Comment by co16353sidak** [comment]
I will create the pull myself, please wait for a few minutes

**Comment by co16353sidak** [comment]
Please review and check accordingly, I have fixed the solution to display the complete correct solution.

**Comment by ahmadabdolsaheb** [comment]
I merged your second PR; please let me know if further modifications are needed.
