### ISSUE TITLE
Firefox - Add Flex Superpowers - failing .follow-btn test.

### ISSUE THREAD

**Issue by leebut** [freeCodeCamp/freeCodeCamp#35049]
I completed the challenge [Add Flex Superpowers to the Tweet Embed](https://learn.freecodecamp.org/responsive-web-design/css-flexbox/add-flex-superpowers-to-the-tweet-embed) 

It states to **add display: flex; to**:

header, the header's .profile-name, the header's .follow-btn, the header's h3 and h4, the footer, and the footer's .stats.

However upon completing the challenge, it fails when using Firefox on Manjaro Linux and windows 10, but works okay using Opera on Windows 10.

Here's the failing tests output:
```
// running tests
Your .follow-btn should have a display property set to flex.
// tests completed
```
At first I thought that uMatrix was blocking an essential script, but it was only blocking Google's stalkerware/spyware scripts and requests. I did run the challenge again in Firefox in incognito with uMatrix disabled, but that didn't help. I also removed all browser history, cache and data.

Here is my code to the challenge:
```
<style>
  body {
    font-family: Arial, sans-serif;
  }
  header {
    display: flex;
  }
  header .profile-thumbnail {
    width: 50px;
    height: 50px;
    border-radius: 4px;
  }
  header .profile-name {
    display: flex;
    margin-left: 10px;
  }
  header .follow-btn {
    display: flex;
    margin: 0 0 0 auto;
  }
  header .follow-btn button {
    border: 0;
    border-radius: 3px;
    padding: 5px;
  }
  
  header h3, header h4 {
    display: flex;
    margin: 0;
  }
  #inner p {
    margin-bottom: 10px;
    font-size: 20px;
  }
  #inner hr {
    margin: 20px 0;
    border-style: solid;
    opacity: 0.1;
  }
  footer {
    display: flex;
  }
  footer .stats {
    display: flex;
    font-size: 15px;
  }
  footer .stats strong {
    font-size: 18px;
  }
  footer .stats .likes {
    margin-left: 10px;
  }
  footer .cta {
    margin-left: auto;
  }
  footer .cta button {
    border: 0;
    background: transparent;
  }
</style>
```

**Comment by lasjorg** [comment]
Do you see the follow button in the output on the right?

I know Adblock on Firefox has caused issues with this challenge. If you have Adblock installed, try to disable it and run the test (I think its an issue with a filter list, not the extension).

**Comment by leebut** [comment]
Thank you for your reply.
I don't run Adblock, but uBlock Origin was blocking .follow-btn and .share-btn.
