### ISSUE TITLE
Not getting a short-code email?

### ISSUE THREAD

**Issue by dharmabumzee** [freeCodeCamp/freeCodeCamp#35050]
Was learning to code on FCC a few years ago, liked it. Been on the mailing list ever since, too. Trying to login again and I'm not getting an email with a short code. It's not in the spam folder, I've checked. Any suggestions?
Thanks in advance!

**Comment by raisedadead** [comment]
Can you check if you are getting any errors on your browser's dev console? You can look up the instructions to do so on Google based on the OS and the browser that you have.
