### ISSUE TITLE
Typo in first test

### ISSUE THREAD

**Issue by xpkc34** [FreeCodeCamp/FreeCodeCamp#3505]
Challenge [Bonfire: Slasher Flick](http://freecodecamp.com/challenges/bonfire-slasher-flick) has an issue.

The first test
```
[1, 2, 3], 2, [3] should return [3]
```
I presume should read:
```
[1, 2, 3], 2, should return [3]
```
I found this to be confusing for a newbie such as myself.

(Also as mentioned in another issue, it would be good if it was clear that the "head" means the beginning of the array. I see this hasn't been fixed yet)

**Comment by natac13** [comment]
I am looking into this
