### ISSUE TITLE
ES6 'Mutate an Array Declared with Const' shows lowercasse not uppercase const names

### ISSUE THREAD

**Issue by leebut** [freeCodeCamp/freeCodeCamp#35059]
I am on the challenge, [Mutate an Array declared with Const](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/mutate-an-array-declared-with-const)

On the previous challenge, we are informed us to use uppercase to declare const variables, but this challenge seems to use lowercase 's', both in the examples and the code editor.

![fcc-const](https://user-images.githubusercontent.com/20357639/52263967-756fa000-296b-11e9-84f5-b9faa0f7ea51.png)

**Comment by ezioda004** [comment]
See previous discussion: https://github.com/freeCodeCamp/freeCodeCamp/issues/19037

**Comment by leebut** [comment]
Okay, thank you.
Perhaps all of that should be explained in the challenge rather than the code appearing as a contradiction in conventions.

**Comment by cmccormack** [comment]
@ezioda004 unless I'm missing something the link you shared explained why @leebut issue is valid.  @leebut are you interested in submitting a PR to modify the variable name?  Perhaps we can make the example a little more interesting by making it a real-life example.

**Comment by ezioda004** [comment]
@cmccormack The convention is to use lowercase for non-primitive values. The challenge is following the correct convention since array is a non-primitive value hence the lowercase use.
A note regarding (uppercase/lowercase with `const`) would be sufficient.

**Comment by co16353sidak** [comment]
Agree with @ezioda004 here, muting objects shouldn't be uppercase as it would confuse the third party to think of it as an unchangeable variable but in reality here we do change s in the sense that we mutate it.
So the use of const here just remains to prevent re-assignment of s and so lowercase can prevail.
We could add a few extra lines in the challenge description to make it more clear.

**Comment by leebut** [comment]
I have created a pull request to update the first challenge on const variables, but it is pointing to the master of my fork, not freecodecamp.

**Comment by co16353sidak** [comment]
You are here comparing across branches of your forked repo, you will have to make a pull request across forks and make sure that the base repository is freeCodeCamp's master branch and the head repository is your fork.
