### ISSUE TITLE
Clicking on "Sign In" button or "Start coding (it's free)" button leads to 500 error in local setup

### ISSUE THREAD

**Issue by rupali317** [freeCodeCamp/freeCodeCamp#35068]
**Describe the bug**
This happens in the local setup. So in the welcome page, if you click on "Start coding (it's free)" button or on "Sign In" button on the navbar, we are shown "500 Internal Server Error"

Not sure if I am missing any configuration

**To Reproduce**
1. Go to welcome page
2. Click on "Start coding (it's free)" button or "Sign In" button on the navbar
3. A "500 Internal Server Error" message is shown

**Expected behavior**
After clicking the buttons on step 2, we should be redirected to a page where we are given options to login via: Google, GitHub, Facebook, Email (which happens in the production site)

**Screenshots**
![freecodecamp_local_dev_signin](https://user-images.githubusercontent.com/5875663/52325182-123f4580-2a1f-11e9-92e5-987cc32c914e.JPG)
![500internalservererror](https://user-images.githubusercontent.com/5875663/52325186-153a3600-2a1f-11e9-95de-2128ce87a1dd.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Google Chrome
 - Version: 72.0.3626.81 (Official Build) (64-bit)

**Comment by rupali317** [comment]
Here is the error message:

![error_logs_signin](https://user-images.githubusercontent.com/5875663/52325497-2c2d5800-2a20-11e9-94eb-69987aef7007.JPG)

**Comment by thecodingaviator** [comment]
Okay, I'm not sure if we really want to fix this right now since we don't really have a problem on the client side, but let's see what the other have to say

**Comment by raisedadead** [comment]
Could not reproduce.

Have you followed the local setup guide? Is your MongoDB running (separately)? Have you seeded the Database (`npm run seed`) like in the instructions?

**Comment by rupali317** [comment]
I ran the commands again from the beginning. I am not able to reproduce this issue.

I made a mistake. At some point, I had closed the console which was running the **mongod** command. 

I will close this issue

**Comment by raisedadead** [comment]
No worries, glad you figured it out. It helps if you check that someone else is getting the same issues. We have a friendly [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) which you should checkout.
