### ISSUE TITLE
Sass: Apply a Style Until a Condition is Met with @while

### ISSUE THREAD

**Issue by reyesvicente** [freeCodeCamp/freeCodeCamp#35069]
**Describe your problem and how to reproduce it:**

Google Chrome: 

Your .text-1 class should have a font-size of 5px 

Safari:

Your .text-1 class should have a font-size of 5px. 
Your .text-2 class should have a font-size of 10px.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while

**Tell us about your browser and operating system:**
* Browser Name: Safari / Google Chrome
* Browser Version: Version 12.0.2 (14606.3.4) / Version 71.0.3578.98
* Operating System: macOS 10.14.2 / macOS 10.14.2 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![screen shot 2019-02-06 at 4 20 56 pm](https://user-images.githubusercontent.com/45283313/52328694-7405ac80-2a2b-11e9-835e-e6d27852b7db.png)
![screen shot 2019-02-06 at 4 21 06 pm](https://user-images.githubusercontent.com/45283313/52328695-7405ac80-2a2b-11e9-985c-02c031065f8d.png)

**Comment by co16353sidak** [comment]
Hi, @reyesvicente 

Can't Seem to reproduce your problem when I run it on my browser, can you please be more descriptive about this problem?
1. Did you also try following the 
[Read-Search-Ask System](https://www.freecodecamp.org/forum/t/the-read-search-ask-methodology-for-getting-unstuck/137307) to find out about the problem you are facing here?
2. Also did you try refreshing the browser page and running it again?

<img width="646" alt="screenshot 2019-02-07 at 11 54 22 pm" src="https://user-images.githubusercontent.com/35738138/52433722-b4505200-2b33-11e9-8873-8b36a117a036.png">

**Comment by reyesvicente** [comment]
Hi @co16353sidak, yes I've refreshed and read search asked but you are the only one that replied. I tried it again now but still received the error.

**Comment by RandellDawson** [comment]
@reyesvicente Can you paste your actual code instead of a screenshot?  Also, did you ask this same question on the forum first?

**Comment by co16353sidak** [comment]
Same as #34775

**Comment by reyesvicente** [comment]
> @reyesvicente Can you paste your actual code instead of a screenshot? Also, did you ask this same question on the forum first?

I asked also on the forum but no reply.

**Comment by RandellDawson** [comment]
@reyesvicente Can you post your exact code?  Use 3 backticks on the line before and after the code you paste.  I believe it is a spacing issue that the tests are having trouble with, but I need to see your exact code to try an duplicate the problem.  Screenshots don't always convey spaces well.

Thank you.

**Comment by moT01** [comment]
Closing in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/34775 - There's a potential solution I posted on that issue @reyesvicente.
