### ISSUE TITLE
Whitespacing on footer

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#35061]
The footer is crammed on the Curriculum and the Guide pages:

![image](https://user-images.githubusercontent.com/1884376/52297916-ca310c00-29a7-11e9-99ea-f17ed3165673.png)

This needs to be uniform with whitespace like on th welcome page:
![image](https://user-images.githubusercontent.com/1884376/52297944-d9b05500-29a7-11e9-8115-d5bcbb5e5276.png)

**Comment by ValeraS** [comment]
@raisedadead do you think this is better?

![image](https://user-images.githubusercontent.com/10867286/52335843-71e42380-2a14-11e9-989a-8f078dbb0a92.png)

**Comment by ahmadabdolsaheb** [comment]
@raisedadead @ValeraS this PR is gonna add an hr that makes learn look a bit better than just a spacer, but it will hurt the aesthetics on all other templates. In the footer issue, we discussed having custom footers for each template so it could reduce distraction in learn.  Maybe we could explore spacing as an addition to the footer so it could customize the space and the length of the hr tag depending on each page. it would probably be a bit time consuming.

**Comment by raisedadead** [comment]
Hi @ValeraS 

I think the long term solution that we are looking at should be to get rid of the internal scroll bars.

Here is what I think would be a good UX (**taking cues from our mobile layout**):

![image](https://user-images.githubusercontent.com/1884376/52338957-cea20700-2a31-11e9-8a61-c9f517e6bbfa.png)

Instructions Panel with tests stings checkbox (1) : Should have the full height of its content. We would still scroll using the page's main scroll bar.
Console Panel (3): Should have a fixed height with a internal scroll. 
Code Panel (2) : The height should be equal to 1 - 3. Will also have a scroll.
Preview Panel (4): No scrolls. Should just be same as 1.

Finally the buttons should be extracted and brought into a bottom panel just above the footer.

**Comment by raisedadead** [comment]
I know this is difficult to achieve, we have thought of some more cleaner layout that will have tabs, which we will add later after we ship.

**Comment by ValeraS** [comment]
@raisedadead Beside buttons and fixed height of the console panel, it works as you describe. Or did I misunderstand something?

**Comment by ahmadabdolsaheb** [comment]
If I understood you correctly @raisedadead, you want 1 and 4 to have the same height and both scroll together? if that is the case, we could achieve that with some JS. There are cases where users need to  read from the end of the  instructions panel, implement changes in the editor and see their changes which takes place at the top of the preview. so the user will be scrolling up and down if that makes sense.

**Comment by raisedadead** [comment]
> There are cases where users need to read from the end of the instructions panel, implement changes in the editor and see their changes which takes place at the top of the preview. so the user will be scrolling up and down if that makes sense.

Hmm.. now having read your comments, I think that we would need the individual scrolls (like it is currently).

UX is hard.

I still believe that extracting the buttons would be a good idea though. And having them as a fixed just below the panels would be neat. However, I agree this is not trivial.

**Comment by Nirajn2311** [comment]
Do we really need all 5 buttons? I think just 3(Run tests, guide, and Ask for help) are enough.
