### ISSUE TITLE
-SOLVED- disappearing check list

### ISSUE THREAD

**Issue by re4ect** [FreeCodeCamp/FreeCodeCamp#3506]
html5 css lesson 35 check list bug (firefox 41.0) Linux --> http://freecodecamp.com/challenges/waypoint-create-a-text-field

After typing the web form I clicked run tests and all of a sudden the check list disappears, now I can't proceed to the next lesson.

![waypoint create a text field free code camp 2015-09-26 09-45-10](https://cloud.githubusercontent.com/assets/14848245/10117835/4f6ac1e2-6433-11e5-8eb5-70859136a7eb.png)

**Comment by re4ect** [comment]
Okay so it seems I had to type it all and not copy and paste the command, THEN click start tests.

PS. I still think its a bug because I should be able to finish by copying and pasting the command.

**Comment by bugron** [comment]
Closing this issue as it is solved. Feel free to reopen if you still experience problems, thanks.
