### ISSUE TITLE
project euler problem 9

### ISSUE THREAD

**Issue by snehal96** [freeCodeCamp/freeCodeCamp#35070]
**Describe your problem and how to reproduce it:**
The answer to the project euler problem 9 special pythagorean triplet for n=120 should be 60000 but instead it says 49920 to be the answer

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/coding-interview-prep/project-euler/problem-9-special-pythagorean-triplet
**Tell us about your browser and operating system:**
* Browser Name: chrome
* Browser Version: Version 72.0.3626.81 (Official Build) (64-bit)
* Operating System: centos 7

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ronaldcs** [comment]
Just validated this and the product of a, b, c should be 49,920 where n = 120.

**Comment by hilliarj** [comment]
I think this issue could be closed, I produced a solution to this and the original test case was correct in the fact that `specialPythagoreanTriplet(120);` should return 49920. `a*b*c = 120` when `a=20, b=48, c=52`.

**Comment by ojeytonwilliams** [comment]
Turns out there are three solutions for `n = 120` and the one you land on depends on how you explore the space: `[30,40,50]`, `[24,45,51]` and `[20,48,52]`.

I'll update the tests to accept all three.  Thanks for looking into this, everyone!
