### ISSUE TITLE
Pass even if it's not correct

### ISSUE THREAD

**Issue by pumalove** [FreeCodeCamp/FreeCodeCamp#3509]
The test should test if the class ".smaller-image" is removed. Else the image is not width of the screen and the test passes anyway.

**Comment by bugron** [comment]
@pumalove thanks for posting this issue!
Please, provide the link to the challenge, a screenshot and your code, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by pumalove** [comment]
![image](https://cloud.githubusercontent.com/assets/1349688/10121884/3cb052ea-6502-11e5-9df9-44bc48f1e8e4.png)

http://freecodecamp.com/challenges/waypoint-make-images-mobile-responsive

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<div class="container-fluid">
  <h2 class="red-text">CatPhotoApp</h2>

  <p>Click here for <a href="#">cat photos</a>.</p>

  <a href="#"><img class="smaller-image thick-green-border" src="http://bit.ly/fcc-relaxing-cat"></a>
    <a href="#"><img class="smaller-image thick-green-border img-responsive" src="http://bit.ly/fcc-running-cats"></a>

  <p>Things cats love:</p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>

**Comment by pumalove** [comment]
I copypasted the img-tag that I've created earlier. And forgot to remove the other classes. I'm aware of my mistake in this, but I think the test should check for this.

**Comment by bugron** [comment]
@pumalove, confirmed. Please, take a look at [Mastering Markdown](https://guides.github.com/features/mastering-markdown/) and our [code formatting](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/code-formatting) Wiki article to know how to share code in GitHub, thanks.

**Comment by abhisekp** [comment]
I guess, it doesn't need to check removal of any classes. Because the instruction clearly mentions this
> First, add a new image below the existing one. Set it's `src` attribute to `http://bit.ly/fcc-running-cats`.
Then all we need to do is add the `img-responsive` class to your image. 

It doesn't asks to copy-paste anything or add any random classes to the new `img` tag.

**Comment by jbmartinez** [comment]
I agree with @abhisekp, the waypoint is about responsive images and it's common to have other classes in addition to `img-responsive`, so it seems logical that the tests only check for the correct use of the `img-responsive` class.

**Comment by ltegman** [comment]
The reason I would say this still does need a fix is that if the user also adds a class of `smaller-image` as is used the the previously included image it will apply a style that overrides the `smaller-image` one and the image will not be the width of the screen. That code will pass despite not giving the desired effect to the image.

**Comment by kaiogyn** [comment]
<img class="img-responsive" src="https://bit.ly/fcc-running-cats">

**Comment by QuintonRivera** [comment]
The solution is not list the period:  correct is https://bit.ly/fcc-running-cats and incorrect is https://bit.ly/fcc-running-cats.
