### ISSUE TITLE
Tests for various challenges are too strict about line breaks before method calls

### ISSUE THREAD

**Issue by ZebulanStanphill** [freeCodeCamp/freeCodeCamp#35090]
## The problem
The tests for the ["JSON APIs and Ajax: Handle Click Events with JavaScript using the onclick property"](https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/handle-click-events-with-javascript-using-the-onclick-property) challenge do not allow a line break before the `getElementById` method call.

When my code looks like this, the tests pass:

```js
document.getElementById( 'getMessage' )
      .onclick = function() {};
```

But this causes the tests to fail:

```js
document
      .getElementById( 'getMessage' )
      .onclick = function() {};
```

**This same kind of issue also affects the following challenges:**
- ["JSON APIs and Ajax: Change Text with click Events"](https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/change-text-with-click-events):
```js
document
  .getElementsByClassName( 'message' )[0]
  .textContent = "Here is the message";
```
- ["JSON APIs and Ajax: Get JSON with the JavaScript XMLHttpRequest Method"](https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/get-json-with-the-javascript-xmlhttprequest-method):
```js
const apiRequest = new XMLHttpRequest();
  apiRequest.open( 'GET', '/json/cats.json', true );
  apiRequest.send();
  apiRequest.onload = function() {
    const json = JSON.parse(apiRequest.responseText);
    document
      .getElementsByClassName( 'message' )[0]
      .innerHTML = JSON.stringify( json );
  };
```
- ["JSON APIs and Ajax: Access the JSON Data from an API"](https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/access-the-json-data-from-an-api):
```js
console.log(
  json[2]
    .codeNames[1]
);
```
- ["JSON APIs and Ajax: Get Geolocation Data to Find A User's GPS Coordinates"](https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/get-geolocation-data-to-find-a-users-gps-coordinates):
```js
if ( navigator.geolocation ) {
  navigator.geolocation.getCurrentPosition(
    pos => {
      document.getElementById( 'data' )
        .innerHTML =
          'latitude: ' +
          position.coords.latitude +
          '<br />longitude' +
          position.coords.longitude;
      }
    );
}
```
- ["JSON APIs and Ajax: Post Data with the JavaScript XMLHttpRequest Method"](https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/post-data-with-the-javascript-xmlhttprequest-method):
```js
const xhr = new XMLHttpRequest();
xhr.open( 'POST', url, true );
xhr.setRequestHeader( 'Content-Type', 'text/plain' );
xhr.onreadystatechange = () => {
  if (
    xhr.readyState === 4 &&
    xhr.status === 200
  ) {
    document
      .getElementsByClassName( 'message' )[0]
      .innerHTML = xhr.responseText;
  }
};
xhr.send( userName );
```

## Browser and OS info
* Browser Name: Firefox Developer Edition
* Browser Version: 66.0b5
* Operating System: Antergos Linux

**Comment by ZebulanStanphill** [comment]
@RandellDawson I have not completed the entire section. I'm just reporting these bugs as I find them while going through the challenges.

**Comment by RandellDawson** [comment]
It would be best to report one issue per the same set challenges which have one or more of the same issues.  If you find any more for this section, please put them on the same issue.

Thank you.

On a side note, even though the code should technically work with the spaces in the function calls, it is not typical coding practice to do so.  We may or may not fix all of these types of issues which are outside the standard best practices.

**Comment by ZebulanStanphill** [comment]
@RandellDawson I have closed the similar tickets in favor of this ticket being the single one for issues like this. I have updated the description and title to reflect this. Thank you for pointing out the unnecessary duplication to me. :+1:

Also, my decision to put line breaks before the method calls is not really what I would consider weird. As far as I am aware, it is standard practice to avoid chained method calls becoming too long. I am mainly following the [WordPress JavaScript Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#chained-method-calls). Even some of the example or pre-filled code in some of the challenges do this.

Similarly, my choice to put spaces around function arguments [also comes from those standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#spacing).

**Comment by RandellDawson** [comment]
@ZebulanStanphill Thanks for putting all of the challenges for the same issue in a single issue.  That makes it much easier for everyone involved.  I will update my existing PRs and create new PRs to deal with the line break issues you have pointed out.  You are welcome to create the separate issue regarding the argument spacing, so other collaborators can have a say beyond my opinions on this issue.  In general, I think we probably should rewrite the tests to focus on what the function would actually return vs on the exact syntax used.  The tests currently are using regular expressions, but I think there is a better way (even for the line break issue).

**Comment by ZebulanStanphill** [comment]
@RandellDawson Here is the ticket I am now using for whitespace-around-function-arguments issues: #34344.

**Comment by ZebulanStanphill** [comment]
@RandellDawson #35093 fixed several of the challenges, but there are some still affected (see original post, which has been edited to reflect this). Should this issue be reopened or should I create a new issue?

**Comment by RandellDawson** [comment]
If you don't mind, can you create a separate issue for oustanding issues you feel the PR did not address, so we can discuss there?  There may be some things we just decide not to implement, but at least want to have the discussion.  Thanks for helping bring these issues to us.

**Comment by ZebulanStanphill** [comment]
@RandellDawson Just to be clear, the PR did not address them because I added the challenges to the list after the PR was made. The type of issues are the same one that the PR fixed for the other challenges. I have created #35368 for the remaining challenges.
