### ISSUE TITLE
How's 0_0 (: /-\\ :) 0-0 a palindrome?

### ISSUE THREAD

**Issue by alayek** [FreeCodeCamp/FreeCodeCamp#3510]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
function palindrome(str) {
  // Good luck!
  str = str.toLowerCase()
           .replace(/ /g, '')
           .replace(/[.,-\/#!$%\^&\*;:{}=\-_`~()]/g,"");
  for(var i = 0; i < str.length / 2; i++){
    if (str[i] !== str[str.length -i -1]){
      return false;
    }
  }
  return true;
}



palindrome("eye");

```
This code works, but check the last test case.

How's `0_0 (: /-\\ :) 0-0` a palindrome? We are ignoring underscore as a punctuation as well?

**Comment by maciejsartys** [comment]
Yes,  after ignoring punctation this string is just "0000". Please, use
help room in gitter for this kind of questions.
27 wrz 2015 11:47 "Arijit Layek" <notifications@github.com> napisał(a):

**Comment by alayek** [comment]
Thanks for your response, but my question is, should we be considering `_` a punctuation?

**Comment by awesomeaniruddh** [comment]
You must consider everything besides alphanumeric characters as punctuation.

Since I believe this resolves the issue, closing this. Feel free to reopen for additional clarification :)

**Comment by gianluca10** [comment]
Maybe this should be spelled out in the problem statement?

**Comment by bugron** [comment]
>You'll need to remove **all non-alphanumeric characters** (punctuation, spaces and symbols) and turn everything lower case in order to check for palindromes.

@gianluca10 isn't this clear enough?

**Comment by gianluca10** [comment]
Ops. thanks.
