### ISSUE TITLE
Improve search UI

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#35103]
Please see below image with suggested improvements:

<img width="1155" alt="echo_and_print___freecodecamp_guide" src="https://user-images.githubusercontent.com/985197/52471394-c54ca200-2bcb-11e9-8c4f-e1e900380b7c.png">

**Comment by ahmadabdolsaheb** [comment]
only the width of the suggestions list should be adjusted.

**Comment by ahmadabdolsaheb** [comment]
@QuincyLarson Would you still like the suggestions box to be the same size as the search bar in smaller screens?

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb Based on my testing, I think the right UX would be for when the display is narrow enough, the search result suggestion box should be the full width of the screen. This may be "xs" or "sm" in Bootstrap.

**Comment by ahmadabdolsaheb** [comment]
@QuincyLarson The PR is ready. here are some screenshots.

<img width="1552" alt="screen shot 2019-02-14 at 5 15 12 pm" src="https://user-images.githubusercontent.com/4591597/52793687-4b129680-307f-11e9-9793-bfc8b17956f2.png">
<img width="1552" alt="screen shot 2019-02-14 at 5 14 58 pm" src="https://user-images.githubusercontent.com/4591597/52793688-4bab2d00-307f-11e9-92f8-f60006e6a2b5.png">
<img width="1552" alt="screen shot 2019-02-14 at 5 14 43 pm" src="https://user-images.githubusercontent.com/4591597/52793689-4bab2d00-307f-11e9-8e0a-f82b5f204ee3.png">
<img width="1552" alt="screen shot 2019-02-14 at 5 14 26 pm" src="https://user-images.githubusercontent.com/4591597/52793690-4bab2d00-307f-11e9-9e31-10b67b7db125.png">

**Comment by hilliarj** [comment]
@ahmadabdolsaheb Did you address issue #17267 with this PR as well? Or was it just issue #35146 ?

**Comment by ahmadabdolsaheb** [comment]
hi #17267 was not addressed

**Comment by hilliarj** [comment]
@ahmadabdolsaheb Ok thanks for letting me know!
