### ISSUE TITLE
When I log in via chrome on desktop, freecode camp logs me out when I click curriculum tab. But I can log in fine under firefox.

### ISSUE THREAD

**Issue by kdmino** [freeCodeCamp/freeCodeCamp#35101]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
When I log in via chrome on desktop, freecode camp logs me out when I click curriculum tab. But I can log in fine under firefox.

**To Reproduce**
1. Go to 'freecodecamp.org'
2. Click on 'sign in'
3. Scroll down to 'curriculum'
4. See error when you click on curriculum.

**Expected behavior**
Keep me logged in. 

**Screenshots**

**Desktop (please complete the following information):**
 - Windows10
 - Browser [chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ronkiro** [comment]
Hello @kdmino!

Do you have your cookies enabled?

Here's a little guide on how to check.
[Google - Turn cookies on or off](https://support.google.com/accounts/answer/61416?co=GENIE.Platform%3DDesktop&hl=en)

**Comment by raisedadead** [comment]
Have you tried this trouble shooting step:

https://www.freecodecamp.org/forum/t/how-to-troubleshoot-sign-in-issues-on-curriculum-and-setting-pages/252012

Closing, may reopen once confirmed bug.
