### ISSUE TITLE
Introduction to the Data Visualization Projects Contains Stub

### ISSUE THREAD

**Issue by TomerPacific** [freeCodeCamp/freeCodeCamp#35117]
**Describe your problem and how to reproduce it:**
In the page, Introduction to the Data Visualization Projects, instead of a description about the projects the user will need to do, the user sees this:
"This introduction is a stub. Help us make it real on GitHub."

There should be a description, like in [Introduction to the JavaScript Algorithms and Data Structures Projects](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects).

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/data-visualization/data-visualization-projects

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 72.0.3626.96
* Operating System: Windows 7 64bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![fcc](https://user-images.githubusercontent.com/23402988/52524819-01563480-2caa-11e9-9eb2-bf7383e0716b.jpg)

**Comment by co16353sidak** [comment]
Originally there was no need to describe the projects under this category as any user reaching here would already have experience in building freeCodeCamp projects
You are free to open a PR to suggest additions.

**Comment by TomerPacific** [comment]
@co16353sidak ,
I went over the repository looking for a file for this page or a similar one for a different projects page, but could not find one. I looked under curriculum/challenges/english/04-data-visualization/data-visualization-projects. Is there a need to create one in that directory?

**Comment by co16353sidak** [comment]
Please check this out @TomerPacific 

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/pages/learn/data-visualization/data-visualization-projects/index.md

this page will be a part of client render as it doesn't contain any curriculum related content this remains in this directory.
although I think someone has already changed the contents for it to be more descriptive.
there will be no need for a PR here 😄

**Comment by TomerPacific** [comment]
@co16353sidak ,
yeah it seems like there isn't one required. I am going to close this issue by tomorrow.
