### ISSUE TITLE
Zooming out with safari cuts off content in lessons

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35116]
When zooming out in safari, the content gets cut off when doing challenges. 

**Initial load of challenge:**
<img width="1055" alt="screen shot 2019-02-09 at 11 53 44 am" src="https://user-images.githubusercontent.com/20648924/52524338-7ea98700-2c61-11e9-8ad2-6371cac2cfe1.png">

**After zooming out:**
<img width="1031" alt="screen shot 2019-02-09 at 11 54 10 am" src="https://user-images.githubusercontent.com/20648924/52524342-80734a80-2c61-11e9-8874-2969438a0eb8.png">

**Desktop (please complete the following information):**
 - High Sierra
 - Safari 
 - 12.0.3
 
**Additional context**
This seems to happen on all the challenges/lessons when using safari. This problem did not happen on firefox or chrome.

**Comment by RandellDawson** [comment]
@moT01 Did you check if the same thing happens locally using the latest `master` branch?

**Comment by moT01** [comment]
no

**Comment by ronaldcs** [comment]
@RandellDawson @moT01 Tested locally using latest `master` and the issue is **not** happening; when I go to prod, however, the issue exists.

**Comment by RandellDawson** [comment]
@ronaldcs Are you using Safari for your testing?

@moT01 Can you please check if you see the same problem when running the latest version of the `master` branch locally?  If it is not present in the local testing, then you should be able to close this issue.

**Comment by ronaldcs** [comment]
@RandellDawson Yes, I was on Safari 12.0.3 on Mojave.

**Comment by moT01** [comment]
It does the same thing while running locally on the latest master

**Comment by RandellDawson** [comment]
OK that is interesting.  Two people using the same version of Safari have two different experiences when testing locally?

**Comment by ronaldcs** [comment]
Correct, I used the ⌘ key and the - and + to zoom in/out and ⌘ 0 (command-zero) to zoom back to normal. For local, the UI kept the same size as the viewport when zooming in/out, but with prod, the UI would get cut off when zooming out, as described in this issue.

**Comment by moT01** [comment]
This appears to be fixed in [beta](https://www.freecodecamp.rocks/)
