### ISSUE TITLE
Broken "Get a Hint" links for most of Information Security with HelmetJS

### ISSUE THREAD

**Issue by orangegrove1955** [freeCodeCamp/freeCodeCamp#35112]
**Describe your problem and how to reproduce it:**
The "Get a hint" links for most of the Information Security with HelmetJS challenges are broken, returning a 404 error when clicked. 

It seems to be the challenges that end in helmet.xxxx() format in their title, as the pages that do not have this link to the guide correctly. From brief inspection of the links attempted to be accessed, compared to the links in the guide, some '.' values are missing which seems to be the cause of the problem.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-with-helmetjs/hide-potentially-dangerous-information-using-helmet-hidepoweredby/
https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-with-helmetjs/mitigate-the-risk-of-clickjacking-with-helmet-frameguard/
https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-with-helmetjs/mitigate-the-risk-of-cross-site-scripting-xss-attacks-with-helmet-xssfilter/
https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-with-helmetjs/avoid-inferring-the-response-mime-type-with-helmet-nosniff/
https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-with-helmetjs/prevent-ie-from-opening-untrusted-html-with-helmet-ienoopen/
https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-with-helmetjs/ask-browsers-to-access-your-site-via-https-only-with-helmet-hsts/
https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-with-helmetjs/disable-dns-prefetching-with-helmet-dnsprefetchcontrol/
https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-with-helmetjs/disable-client-side-caching-with-helmet-nocache/
https://learn.freecodecamp.org/information-security-and-quality-assurance/information-security-with-helmetjs/set-a-content-security-policy-with-helmet-contentsecuritypolicy/

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 71.0.3578.98 (Official Build) (64-bit)
* Operating System: macOS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="1440" alt="screen shot 2019-02-09 at 6 24 39 pm" src="https://user-images.githubusercontent.com/38221472/52518016-3ce80300-2c98-11e9-99d3-ada5bdb9a95a.png">
<img width="1255" alt="screen shot 2019-02-09 at 6 24 47 pm" src="https://user-images.githubusercontent.com/38221472/52518017-3eb1c680-2c98-11e9-916b-82bfc0bacb63.png">

**Comment by moT01** [comment]
I have created an issue to consolidate all of the broken "get a hint" link issues https://github.com/freeCodeCamp/freeCodeCamp/issues/35155

**Comment by moT01** [comment]
Fixed in beta. Viewable at https://www.freecodecamp.rocks/
