### ISSUE TITLE
html/css Lesson # 38 Add a Submit Button to a Form won't let me finish

### ISSUE THREAD

**Issue by re4ect** [FreeCodeCamp/FreeCodeCamp#3511]
The lesson says that the form should have a button inside it. Well it does have a button inside but it will not me finish the task, this happens in google chrome.

![waypoint add a submit button to a form free code camp](https://cloud.githubusercontent.com/assets/14848245/10122838/bc7f4cc8-64f4-11e5-9e94-54bc2cd6f9f9.png)

**Comment by bugron** [comment]
@re4ect thanks for posting this issue!
Actually your code is incorrect. You `button` should be in `form` element in other words move line 50 before line 48.
Closing this issue. Feel free to reopen if you still experience problems, thanks. And next time provide the link to the challenge and your code too, please.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by re4ect** [comment]
@bugron Okay I fixed it thank you

**Comment by abumregha** [comment]
@bugron  same here, fixed it the same way :P
