### ISSUE TITLE
Minor explanation correction

### ISSUE THREAD

**Issue by Hiyorimi** [freeCodeCamp/freeCodeCamp#35114]
**Problem:**
I think that it might be  not clear why separate function is used to wrap the class declaration, and it might confuse some people. I would like to purpose adding some explanation, like, `class declaration in  the example is wrapped into makeClass function, because we need to maintain  ES6 space in the closure`.

**Links:**
[FCC link](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-class-syntax-to-define-a-constructor-function)
[Github link](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-class-syntax-to-define-a-constructor-function.english.md)

**Comment by icatat** [comment]
I would like to help with this issue.

**Comment by Hiyorimi** [comment]
I think that using function is a great idea. It is only text of the exercise, not giving  clear explanation, why is it used like this, that might need improving.

**Comment by RandellDawson** [comment]
FYI - There is a pull request (https://github.com/freeCodeCamp/freeCodeCamp/pull/34538) which remove the function wrapper.  

To other moderators: Once it has been merged, the label `status: resolved \ shipping` should be added until it has been moved to production.  Once in production, this issue can be closed.

**Comment by moT01** [comment]
Closing as this has been fixed.
