### ISSUE TITLE
Exact Change - Nickel:2.05 returns fraction on one test

### ISSUE THREAD

**Issue by simplyomusic** [FreeCodeCamp/FreeCodeCamp#3512]
Here is the code I'm using:

function drawer(price, cash, cid) {
  var total = cash - price;
  var holdTotal = total
  var returner = 0;
  var change = [];
  var drawer = 0
  var x = 8;
  while (x >= 0){
    console.log(cid[x][1]);
    drawer = drawer + cid[x][1];
    console.log(drawer);
    if (x == 8){
      var money = 100;
    } else if (x == 7){
      var money = 20;
    } else if (x == 6){
      var money = 10;
    } else if (x == 5){
      var money = 5;
    } else if (x == 4){
      var money = 1;
    } else if (x == 3){
      var money = .25;
    } else if (x == 2){
      var money = .1;
    } else if (x == 1){
      var money = .05;
    } else if (x == 0){
      var money = .01;
    }
    var holder = (Math.floor(total / money)) * money;
    if (holder > 0 && cid[x][1] > 0){
      if (holder - cid[x][1] <= 0){
        cid[x][1] = holder;
      } else if (holder - cid[x][1] > 0){
        //nothing happens we give her all the monies
      }
      returner = returner + cid[x][1];

      change.push(cid[x]);
      total = total - cid[x][1];
    }
    x--;
  }

  if (returner == holdTotal && returner == drawer){
    return "Closed";
  } else if (returner == holdTotal){
    return change
  } else {
    return "Insufficient Funds";
  }
  
}

drawer(3.26, 100.00, [['PENNY', 1.01], ['NICKEL', 2.05], ['DIME', 3.10], ['QUARTER', 4.25], ['ONE', 90.00], ['FIVE', 55.00], ['TEN', 20.00], ['TWENTY', 60.00], ['ONE HUNDRED', 100.00]]);

When I run this on Chrome I can see in the console.log that when it logs the drawer balance after adding in the nickels, it creates an odd fraction. I can see the amount before is not a fraction, and the amount it is adding is also not a fraction. Screenshot is attached for clarification.
![screen shot 2015-09-26 at 5 29 33 pm](https://cloud.githubusercontent.com/assets/13602768/10123529/cb4a3a5a-6509-11e5-9b5b-87d6d1b17667.png)

**Comment by Deftwun** [comment]
I think this i just the nature of floating point arithmetic in Javascript. Open your console and type `.1+.2` and you'll see what I mean. I had the same issue but ended up formatting my numbers to only 2 decimal places if I remember correctly.

**Comment by ltegman** [comment]
As @Deftwun pointed out, this is the nature of floating point operations in javascript and an important part of learning how to correctly deal with mathematical operations on monetary values in javascript.

[Here](http://stackoverflow.com/questions/1458633/how-to-deal-with-floating-point-number-precision-in-javascript) is a discussion of this problem on StackOverflow.

Closing this as not an issue with the challenge, but please let me know if you have any further concerns!

Thanks and happy coding!
