### ISSUE TITLE
Coding Challenge getting blocked by padding on Safari

### ISSUE THREAD

**Issue by hilliarj** [freeCodeCamp/freeCodeCamp#35120]
**Describe your problem and how to reproduce it:**
Launching any challenge on the curriculum on Safari causes this issue. It may be specific to Safari or just specific versions. Also does not matter if it is in day/night mode.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/responsive-web-design/basic-css/change-the-color-of-text
(Could be any challenge)

**Tell us about your browser and operating system:**
* Browser Name: Safari 
* Browser Version:  Version 11.1.1 (13605.2.8)
* Operating System: MacOS High Sierra 10.13.5 (17F77)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![screen shot 2019-02-09 at 3 32 38 pm](https://user-images.githubusercontent.com/21319186/52526251-c80ace00-2c83-11e9-8f7e-5b6ed48b9045.png)

**Comment by hilliarj** [comment]
[Could be similar to this issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/35116)

**Comment by RandellDawson** [comment]
@hilliarj Have you tried adjusting your Zoom level?

**Comment by hilliarj** [comment]
> @hilliarj Have you tried adjusting your Zoom level?

Yes. Changing the zoom level makes it stop. Should I close this issue since it is essentially the same as #35116?

**Comment by RandellDawson** [comment]
If it is the same as the earlier issue, then please close this one.
