### ISSUE TITLE
Free Code Camp should never sign campers out unless they click the sign out button

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3513]
Facebook and many other services essentially have sessions that last forever, and we should too. Campers frequently forget their passwords and have to reset them. We need to figure out exactly where this is set in our app (Passport?) and configure it to the maximum.

**Comment by abhisekp** [comment]
there should be a default unchecked Remember Me checkbox.

**Comment by sanspace** [comment]
This would really be great. I was about raise a request. But, a quick check got me here.

I close my browser windows often. Whenever, I reopen I start working on the challenges without realizing I haven't logged in (Got used to Github, FB etc). After a few challenges I realize this and I had to do it all over again to have it recorded in my account. The answers were there though. But, the progress was not recorded.

I'd say it should be a part of the site. IMHO, it shouldn't be called an enhancement.

**Comment by Em-Ant** [comment]
I agree !

**Comment by bugron** [comment]
@BerkeleyTrue, is this fixed?

**Comment by termet2009** [comment]
Good deal

**Comment by bugron** [comment]
@BerkeleyTrue are we going to implement this?

**Comment by BerkeleyTrue** [comment]
This is already so.

**Comment by bugron** [comment]
@BerkeleyTrue every time I open freecodecamp.com I have to log in.

**Comment by BerkeleyTrue** [comment]
Are you in incognito?

**Comment by bugron** [comment]
No, of course.

**Comment by BerkeleyTrue** [comment]
We don't expire sessions. And this issue was a result of some users switching back and forth with the www subdomain and the root domain. We now only use the www subdomain and that has solved the issue.

What would make your case unique?

**Comment by BerkeleyTrue** [comment]
We store accessToken and user id in cookies. Are you clearing your cookies when you close your browser?

**Comment by bugron** [comment]
No, I do not remove cookies before closing (just checked settings). I'll check if restarting the browser makes sense.

**Comment by bugron** [comment]
I've restarted and I'm still logged out. Maybe there is some timeout. I'll comment when will be able to repro next time.

**Comment by BerkeleyTrue** [comment]
This are the important bits. There should also be GA stuff as well.
![sum_all_primes___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/12426673/baafc950-be8f-11e5-979d-8230836ddc5c.png)

**Comment by bugron** [comment]
They are in place and not touched.

**Comment by abhisekp** [comment]
I've to login sometimes too. The session expires.

**Comment by bugron** [comment]
@BerkeleyTrue I'm logged out today. I can see `access_token`, `connect.sid` and `userId` cookies, though.

**Comment by pradeepce** [comment]
+1

Closing the browser window logs me out, even if I keep my cookies for all sub-domains of FCC (`[*.]freecodecamp.com`).

Also, the `expires` value of all cookies is set to what appears to be the server's time. I am ahead in timezone and as a result, the cookies are cleared when I close my browser (owing to my computer's time being ahead of the server's time). Shouldn't this value be a point of time sufficiently in the future? For example, Github keeps `user_session` for what looks like 15 days.

**Comment by noinkling** [comment]
+1

My login never persists longer than my browser session.

**Comment by MeowApp** [comment]
@BerkeleyTrue agree to @pradeepce  hope this can solve soon

**Comment by colorblueiswaycool** [comment]
Good stuff

**Comment by Kalcode** [comment]
Same issue here. Always logged out and my cookies for currentChallengeId expires {session}.

**Comment by dbess1** [comment]
Where are we on this? Probably one of the only annoying issues on the site. Love it otherwise.

**Comment by BerkeleyTrue** [comment]
So far no one has stepped up to take this one.

**Comment by Kalcode** [comment]
Alright i have sent in a pull request, but i dont have much time to set-up an environment to test it, i am sorry. But examining the code seems to be a oversight of not setting an expire for currentChallengeId, i just used express documentation to set it to far in the future. 

I hope this helps, i tested changing the cookie in browser and its works. But that is a far cry from testing the res.cookies() function.
