### ISSUE TITLE
Typo with print(): Should be printf() instead of print()

### ISSUE THREAD

**Issue by cindydhy** [freeCodeCamp/freeCodeCamp#35141]
**Describe your problem and how to reproduce it:**
In the Hello World example in guide, there is a typo when explaining the stdio library. Instead of print(), it should be printf().

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/c/hello-world/index.md

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 71.0.3578.98
* Operating System: MacOS Mojave 10.14.3

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![screen shot 2019-02-11 at 1 24 20 am](https://user-images.githubusercontent.com/38956884/52548467-dcda8500-2d9b-11e9-88a8-933289a0cd3f.png)

**Comment by moT01** [comment]
There's no need to create issues for the guide articles at the moment, as @RandellDawson described on your PR - so I will close it. There's plenty of things that can improved like this in the guide articles and elsewhere if you're feeling ambitious - thanks!
