### ISSUE TITLE
Missing hints in React challenges

### ISSUE THREAD

**Issue by lucassorenson** [freeCodeCamp/freeCodeCamp#35148]
**Describe your problem and how to reproduce it:**

At least one of the challenges for React (Use the Lifecycle Method componentWillMount) has a link to an empty guide stub, when there is a guide article in the freeCodeCamp files. Clicking "Get a hint" takes you to an empty page, when it should take you to the relevant hint.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/react/use-the-lifecycle-method-componentwillmount

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/18340731/52583146-e6e0a000-2dfc-11e9-94b3-ee65d2145a75.png)

This is the page for the challenge. Clicking "Get a hint" takes you to an empty stub

![image](https://user-images.githubusercontent.com/18340731/52583171-f364f880-2dfc-11e9-91da-bbd836e59acd.png)

Empty Stub

![image](https://user-images.githubusercontent.com/18340731/52583183-fd86f700-2dfc-11e9-9aef-3b68d3caac21.png)

FreeCodeCamp files, with an article for the challenge in question. The hint button should send users here.

**Comment by moT01** [comment]
Thank you for reporting this issue.
This is a standard message notifying you that the problem you mentioned here is present in production, but that it has already been fixed. This means that the next time we push our master branch to production, this problem should be fixed. Because of this, I’m closing this issue.
If you think I’m wrong in closing this issue, please reopen it and add further clarification. Thank you and happy coding.

**Comment by RandellDawson** [comment]
@moT01 I believe we have been adding a new label instead of closing these, so that people know that it is fixed and when searching for open issues, they can find the open issue when searching.

**Comment by lucassorenson** [comment]
Thank you for the clarification. I'm new here and not sure how this all works. Please let me know if anything else about the issue was done incorrectly so I can participate more effectively.

**Comment by moT01** [comment]
Fixed in [beta](https://www.freecodecamp.rocks/)
