### ISSUE TITLE
Differentiating New User Login's 

### ISSUE THREAD

**Issue by organicdude** [freeCodeCamp/freeCodeCamp#35150]
Hi there,

FCC has earned a Google Grant to promote FCC on Google ads.

To make sure our ads are being effective in getting new campers to sign up, we need to differentiate between 2 types of sign in's:

1. New campers, who just signed up.
2. Returning campers, who already signed up previously.

I believe the easiest way to track a new camper signing up in Google Ads/Analytics is with a GET parameter in the URL.

Can we have it so when a new camper completes the sign up process, then he/she lands at:
https:://www.freecodecamp.com/?new-sign-up=1

Thank you,

**Comment by QuincyLarson** [comment]
@organicdude Thanks for creating this issue. 

@raisedadead You know the most about our authentication flows. How would we best track new signups VS returning users for the purpose of analytics? This is for us to improve our Google Ads (the ones Google gives us for free as a nonprofit).
