### ISSUE TITLE
Repetitive Link 

### ISSUE THREAD

**Issue by americanSammy** [freeCodeCamp/freeCodeCamp#35163]
**Describe your problem and how to reproduce it:**
If you click "Contact" on the nabar, it duplicates the current page in the smaller window.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/lock-an-element-to-the-browser-window-with-fixed-positioning/

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 72
* Operating System: Windows 10

![freecodecamp error](https://user-images.githubusercontent.com/34145581/52645031-f79d1e80-2ead-11e9-88b4-24780367405a.PNG)

**Comment by co16353sidak** [comment]
Was able to replicate this.

@americanSammy 
This is the navbar that is being designed by you in the challenge and the href given to it must be the link to the whole current page, so when we click on the page, it then open's up the page inside the preview window where we see the page being designed.

I don't think it was a problem to begin with.

**Comment by moT01** [comment]
I found about 50 challenges with an issue like this. A few of them are simple anchor tags with an empty `href`, where adding `#` in the `href` would fix it. But most of them have a form in the challenge like [this one](https://learn.freecodecamp.org/responsive-web-design/basic-css/change-the-color-of-text). My idea for a fix was to put `javascript:void(0)` as the form action for all of them. This would fix it, but I'm not sure if this is the best approach. There is the original challenge where you learn how to create a form, and some of the tests would have to be re-written for that one. Not a big deal, but there also might be some issues about code lining up with the video's or solution code or maybe elsewhere.

**Comment by ValeraS** [comment]
@moT01 IMO, we can handle it on preview engine level, no need to change challenges.
