### ISSUE TITLE
the checklist is saying I don't have pink text in h1

### ISSUE THREAD

**Issue by re4ect** [FreeCodeCamp/FreeCodeCamp#3518]
html/css Override Styles in Subsequent CSS number 57
-->http://freecodecamp.com/challenges/waypoint-override-styles-in-subsequent-css

I must be overlooking something but I just don't know what.

![waypoint override styles in subsequent css free code camp](https://cloud.githubusercontent.com/assets/14848245/10125423/6b75812e-6541-11e5-9115-c604d23d9dce.png)

**Comment by avastu** [comment]
The correct syntax for classifying an element as multiple classes is separating the classes by a space, e.g.:

```<h2 class="class1 class2">```

**Comment by re4ect** [comment]
@avastu it does not work it won't accept the space between the two classes.

![waypoint override styles in subsequent css free code camp](https://cloud.githubusercontent.com/assets/14848245/10125599/92d31ea0-6548-11e5-8cdf-6e1437bb783c.png)

**Comment by avastu** [comment]
You are doing ```class="blue-text" class="pink-text"```

I suggested doing ```class="class1 class2"```

See the difference? Also, if you want the blue text class to override the pink text class, you'd want to put the blue text class after the pink text class.

**Comment by re4ect** [comment]
@avastu thank you, its been a long day, lol

**Comment by re4ect** [comment]
#3518 close

**Comment by re4ect** [comment]
close #3518

**Comment by re4ect** [comment]
Fixes #3518
