### ISSUE TITLE
IE11 Page not responding when challenge completed successfully.

### ISSUE THREAD

**Issue by joekershner** [FreeCodeCamp/FreeCodeCamp#3519]
Switching to Chrome browser worked for me.

**Comment by bugron** [comment]
@joekershner thanks for posting this issue!
Closing this issue as we don't support IE or Edge at all. [We officially support only Chrome browser](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2942#issuecomment-136591448). Feel free to reopen if you still experience problems, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
