### ISSUE TITLE
getUserInput is not defined in test-evaluator

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#35194]
**Describe the bug**

`getUserInput` is not defined in `test-evaluator`

**To Reproduce**
1. Go to [write-concise-declarative-functions-with-es6](https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/es6/write-concise-declarative-functions-with-es6 )
2. Click on Run Tests
3. Open console

**Expected behavior**
The test suite  should run

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser FireFox
 - Version @latest

**Additional context**

**Comment by ValeraS** [comment]
@Bouncey It's here
https://github.com/freeCodeCamp/freeCodeCamp/blob/0dc0edcded1dd6aa2c57cc408b57ea0064e607a6/client/src/client/workers/test-evaluator.js#L36
