### ISSUE TITLE
"Basic Data Structures: Iterate Through the Keys of an Object with a for...in Statement": missing dot in example code

### ISSUE THREAD

**Issue by samuel-2018** [freeCodeCamp/freeCodeCamp#35196]
"Example 2" is missing a dot after "[user]":

```
for (let user in obj) {
    if(obj[user]online === true) {
      //code
    }
  }
```

https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for...in-statement

![image](https://user-images.githubusercontent.com/45561451/52754993-6a032100-2fca-11e9-9d33-55bb1073a9f7.png)

**Comment by RandellDawson** [comment]
@samuel-2018 I created a pull request which will fix it in all the languages.  Thank you for reporting this issue.  Once it is merged, we marked it here.
