### ISSUE TITLE
the backed project pages have a double hr tag and buttons need resizing

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#35190]
The conditional rendering in the challenge description for the backend projects renders an empty section although there is no instructions in the markdown file resulting in a double hr.

additionally the buttons are almost as wide as the screen that need to be smaller.

**Screenshots**
![image](https://user-images.githubusercontent.com/4591597/52716460-dfadc380-2faf-11e9-9a3f-eb2d99f8bcb6.png)

**Comment by RandellDawson** [comment]
This issue is present on many challenges actually, but I have noticed a lot of the time, that it is simply a matter that the instructions have not been separated from the description section.

**Comment by ahmadabdolsaheb** [comment]
@raisedadead probaby I fit two issues at once, please review and let me know.

**Comment by ahmadabdolsaheb** [comment]
@RandellDawson so challenge description used to check if is null or and empty string. however in the markdown the instruction is set as an empty section tag that causes the challenge description to render it and wrap it in two hr tags.
