### ISSUE TITLE
Email notification Camper News

### ISSUE THREAD

**Issue by Maximization** [FreeCodeCamp/freecodecamp#352]
The email notification that the user receives upon a new comment on one of his stories on Camper News is a little off. Here's what's wrong:

1. The author of the comment is not the actual author but the user itself. Basically it's saying that you've replied to your own post.
2. The link to the particular story is broken.
3. Email gets sent out to both the comment author and story author although it's specifically addressing the story author. Either change the email content or send the email to the story author only.

I'd be happy to issue a PR if you agree with the above. Point 3 needs clarification.

**Comment by QuincyLarson** [comment]
The desired behavior is this:

**Comment by QuincyLarson** [comment]
@maximization how is coming along? Fixing this is a high priority. @terakilobyte designed Camper News and is a good resource if you need help.
