### ISSUE TITLE
Modal header styling is incorrect

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#35213]
The header of our modals have no background colour. They should have a background-color of `#006400`

![image](https://user-images.githubusercontent.com/18572518/52810854-7b603200-308b-11e9-8b11-6058398a056e.png)

**Comment by chaomt** [comment]
We could work on it! @Fordco

**Comment by Fordco** [comment]
Yeah, that'd be great if its alright.

**Comment by Fordco** [comment]
@Bouncey  Can you tell us where this occurs?

**Comment by vireakpanha** [comment]
Can I still work on this issue?

**Comment by DzmitryUr** [comment]
@vireakpanha There is 'pull request' above your comment. PR probably fixed this issue already.

**Comment by vireakpanha** [comment]
Okay!
