### ISSUE TITLE
Favicons are missing

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#35219]
The current master does not have any favicons.

The likely culprit is my configuration of `gatsby-plugin-manifest`

https://github.com/freeCodeCamp/freeCodeCamp/blob/5f228f9b441d3664a60a6bb6106017d6bd156930/client/gatsby-config.js#L136-L149

**Comment by ahmadabdolsaheb** [comment]
related: https://github.com/freeCodeCamp/search-assets/pull/9 .

**Comment by Ensive** [comment]
On the latest master favicons look good to me locally.

**Comment by thecodingaviator** [comment]
@Bouncey Which pages are you getting that on? I cannot find it on rocks a.t.m. maybe I'm looking at the wrong places

**Comment by Bouncey** [comment]
I cannot see them locally or on .rocks?

**Comment by raisedadead** [comment]
Chrome will cache it. Or make an icon available from other  equivalent resources defined in the manifest.

![image](https://user-images.githubusercontent.com/1884376/53564561-3e149d80-3b7d-11e9-9044-82b94699f1e3.png)

The actual icon is a 404.

**Comment by thecodingaviator** [comment]
We were porting over our assets to the fCC CDN. Could this be related to that?

**Comment by ahmadabdolsaheb** [comment]
I believe #35568 resolved this issue since I could not reproduce it.

**Comment by thecodingaviator** [comment]
I can confirm that this issue is reproducible on the currently deployed version of rocks

**Comment by ahmadabdolsaheb** [comment]
@thecodingaviator, rocks might be a little bit behind at the moment. Could you please try it reproduce it?

**Comment by thecodingaviator** [comment]
@ahmadabdolsaheb Sure can, will get back here soon

**Comment by thecodingaviator** [comment]
Issue tested locally. The issue is fixed on latest master. Would ship soon
