### ISSUE TITLE
Nav styling on freecodecamp.auth0.com does not match production or beta site

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#35229]
While testing the beta site for something else, I noticed the styling for freecodecamp.auth0.com does not match for at least the nav bar at the top.

**freecodecamp.auth0.com**

![authsite](https://user-images.githubusercontent.com/5313213/52868545-856c4a00-30f8-11e9-82e5-94cc5942d09d.gif)

**Production**

![production](https://user-images.githubusercontent.com/5313213/52868523-77b6c480-30f8-11e9-99f4-70e421ad5053.gif)

**Comment by raisedadead** [comment]
Thanks for reporting.

However, this issue an indirect side-effect of a different issue.

**Limitation with Auth0 and one of our social providers:** 

While we could have multiple domains for the current tenant (subscription), we can't use multiple domains with the same OAuth app for GitHub. GitHub allows only one callback URL. We could have a separate tenant and hook it up to `.rocks` domain, but we would end up paying for it.

The potential gain is not worth the time and efforts spent on these apps/configs. Also there is a high chance of potential for breaking things when we duplicate configs.

**That said, the production auth page will work normally.**

Closing as a won't fix.
