### ISSUE TITLE
Rocks: Buttons not redirecting properly

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#35226]
**Describe the bug**
If on https://www.freecodecamp.rocks/ :
![image](https://user-images.githubusercontent.com/34807532/52854651-1701a900-3145-11e9-8fe3-bfab7badd4f0.png)

![image](https://user-images.githubusercontent.com/34807532/52854722-5af4ae00-3145-11e9-8b72-981abaaebf1e.png)

Any links after that lead to links on the main website

![image](https://user-images.githubusercontent.com/34807532/52854793-aad37500-3145-11e9-9d17-d1d87a8894f3.png)

**Comment by raisedadead** [comment]
I believe this is fixed? Can someone check and close. We did break this temporarily.

**Comment by raisedadead** [comment]
You may have to clear the cookies for all `*.freecodecamp.rock` domains 

For example on Chrome you should be able to visit `chrome://settings/siteData` and lookup `freecodecamp.rocks`. Then on you should be able to remove only cookies for this domain.

**Comment by raisedadead** [comment]
Resolved.
