### ISSUE TITLE
Problem in Waypoint #4 in the jQuery track

### ISSUE THREAD

**Issue by otamm** [FreeCodeCamp/FreeCodeCamp#3523]
Challenge [Waypoint: Target Elements by ID Using jQuery](http://www.freecodecamp.com/challenges/waypoint-target-elements-by-id-using-jquery) has an issue.

Not really a 'software bug', but a mistake in the instructions. While the second paragraph instructs the student to add the class to the button with id 3, the 5th asks the student to manipulate the button with id 6 (
![screen shot 2015-09-27 at 9 20 43 pm](https://cloud.githubusercontent.com/assets/6130761/10125977/a5ae9ef4-655d-11e5-831f-6a7a049e4681.png)
3 is actually the correct one to complete the waypoint).

**Comment by bugron** [comment]
@otamm thanks for posting this issue!
>**Here's how** you'd make the button element with the id target6 fade out: $("#target6").addClass("animated fadeOut").

This means that this is **an example** how to fade out element with id `target6`. You should understand how this code works, what it does and then use it for `target3`.
Closing this issue. Feel free to reopen if you still experience problems, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
