### ISSUE TITLE
[beta] remove <hr>'s above footer?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35232]
In my opinion, I don't like the hr's above the footer - specifically on the curriculum page, but it might look better without it all around. It just looks a little out of place or something to me.

<img width="1411" alt="screen shot 2019-02-15 at 10 36 43 am" src="https://user-images.githubusercontent.com/20648924/52874048-19004380-3116-11e9-84d2-f4ff24474a0a.png">
<img width="1389" alt="screen shot 2019-02-15 at 10 36 14 am" src="https://user-images.githubusercontent.com/20648924/52874092-346b4e80-3116-11e9-9a27-688d316cf688.png">

**Comment by ahmadabdolsaheb** [comment]
I agree, the thing is, without it the lessons would look strange. it looks like the instructions fade into space. so the best way would be to add lower border to the challenges on learn and completely remove the hr tag.

**Comment by ahmadabdolsaheb** [comment]
There was a new addition to the lessons and all of the buttons are placed at the bottom of the view. So it would probably be safe to just remove the hr. But be wary of how it would look on the guide.

**Comment by raisedadead** [comment]
I have something in works about this. See linked PR.

**Comment by ahmadabdolsaheb** [comment]
the above-mentioned pr (#35235) closes this issue.
