### ISSUE TITLE
Set .rocks robot.txt to block all indexing

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#35248]
freecodecamp.rocks needs to have a separate robot.txt file that is different from master that prevents crawlers from crawling it. 

Multiple SEO experts have suggested we do this to prevent the accidental indexing of duplicate content.

What do you think the best way of going about this is, @Bouncey and @raisedadead?

**Comment by raisedadead** [comment]
Nice catch. I believe we are able to do this by updating the config during build with Gatsby conditionally.

**Comment by Bouncey** [comment]
I set this at the nginx level

**Comment by QuincyLarson** [comment]
@Bouncey @raisedadead awesome! Thanks for handling this so quickly.
