### ISSUE TITLE
Reimplement the Danger Zone on the setting page

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#35242]
The Danger Zone is missing on the settings page. It should be a clone of what we have in production.

**Comment by hemakshis** [comment]
Hi @Bouncey, I would like to take up this issue as my first contribution to FCC :smiley:. Could you please guide me further on how it should look?
Thank you!

**Comment by Naaman-Saif** [comment]
@hemakshis Would you like to pair on this? I think I have an idea what this is about.

**Comment by Nirajn2311** [comment]
@hemakshis @Naaman-Saif This is what the Danger Zone looks like in the production -

![screenshot 52](https://user-images.githubusercontent.com/36357875/52915807-b06dbe00-32f1-11e9-9e73-039eba32c0b8.png)

**Comment by hemakshis** [comment]
> @hemakshis Would you like to pair on this? I think I have an idea what this is about.

I think I'm good working on this issue by myself.

**Comment by andre1011green** [comment]
This information is incorrect, I followed the instructions and there is no Danger Zone, is there another way I can delete one of my repositories?
