### ISSUE TITLE
ES6 challenge has poor wording: Use Destructuring Assignment to Assign Variables from Objects

### ISSUE THREAD

**Issue by chuckadams** [freeCodeCamp/freeCodeCamp#35246]
The text of the challenge reads: 

> Use destructuring to obtain the average temperature for tomorrow from the input object AVG_TEMPERATURES, and assign value with key tomorrow to tempOfTomorrow in line.

Except `AVG_TEMPERATURES` is not the input object, `avgTemperatures` the parameter is.  Anyone trying to destructure the global constant will not pass  the challenge.  The simple fix is just to change the one word, from AVG_TEMPERATURES to avgTemperatures.  Alternatively, maybe just pass the object in-line and not use a global constant at all.

**Comment by chuckadams** [comment]
Also, the challenge "ES6: Use Destructuring Assignment with the Rest Operator to Reassign Array Elements" suffers from the same issue, with the text referring to the global `source` rather than the parameter `list` as it should.

**Comment by chuckadams** [comment]
Note this is a duplicate of #34257 which was closed without any resolution.  Doesn't encourage me to make a PR for it...

**Comment by RandellDawson** [comment]
@chuckadams As the comments on the PR suggested, you are fine creating another issue for this and another PR, because the other one went stale.
