### ISSUE TITLE
View certificate text bleed outside the button

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#35265]
![image](https://user-images.githubusercontent.com/1884376/52918773-dfe7ef00-3320-11e9-9df7-4329ba58e23a.png)

**Comment by Nirajn2311** [comment]
@raisedadead Could you give a link to the page as then it might be easier to solve the issue?

**Comment by raisedadead** [comment]
This should be the case on the user's profile page. You can reproduce by setting the certificate keys to true in the user object.

**Comment by chaomt** [comment]
I could work on this!

**Comment by Nirajn2311** [comment]
@chaomt I am already working on it.

**Comment by chaomt** [comment]
> @chaomt I am already working on it.

@Nirajn2311 Thanks for letting me know!

**Comment by ahmadabdolsaheb** [comment]
a reasonable fix would be to give the grid that contains the profile a class and on the css, change the button under that class and have ` white-space: nowrap; `. you will end up with something like this.
<img width="681" alt="screen shot 2019-02-22 at 2 18 10 pm" src="https://user-images.githubusercontent.com/4591597/53239365-e07bdf00-36ac-11e9-93b7-ea307a805a1a.png">
<img width="1095" alt="screen shot 2019-02-22 at 2 17 53 pm" src="https://user-images.githubusercontent.com/4591597/53239367-e2de3900-36ac-11e9-8315-415417462834.png">

**Comment by ahmadabdolsaheb** [comment]
Similar solution could be applied to these donate buttons probably. but the selectors should be very specific not to change the styling on other buttons in the platform.
<img width="669" alt="screen shot 2019-02-23 at 2 09 14 pm" src="https://user-images.githubusercontent.com/4591597/53285698-afff7800-3774-11e9-8b8c-1d4ad751a7c9.png">
<img width="502" alt="screen shot 2019-02-23 at 2 08 51 pm" src="https://user-images.githubusercontent.com/4591597/53285699-afff7800-3774-11e9-80e6-b4e80d6ec032.png">

**Comment by raisedadead** [comment]
Hey @ahmadabdolsaheb or @chaomt Can you take this up? @Nirajn2311 just updated us that he will be a bit busy with other things.

**Comment by ahmadabdolsaheb** [comment]
I'm on it @raisedadead
