### ISSUE TITLE
Master font-sizes does not match production.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#35273]
here is a side-by-side screenshot of production(left) and master(right). Although the font size is the same on both, the size of the rendered characters is different.      ¯\\_(ツ)_/¯
 
<img width="1439" alt="screen-shot-2019-02-13-at-11 10 43-am 1" src="https://user-images.githubusercontent.com/4591597/52951116-fa0de580-3391-11e9-9e19-b43012a78878.png">

**Comment by hemakshis** [comment]
Hi @ahmadabdolsaheb, I encountered this same while working on the master. What I saw was that the font-sizes for `btn-lg` don't match for `master` and `production` branches.

![screenshot from 2019-02-18 20-22-53](https://user-images.githubusercontent.com/22373452/52958919-1eca8300-33bb-11e9-92aa-9a0293b24b64.png)
`master` has `font-size` of `23px` for `btn-lg`

and
![screenshot from 2019-02-18 20-23-25](https://user-images.githubusercontent.com/22373452/52958958-3275e980-33bb-11e9-8e17-4fb517112be7.png)
`production` has a `font-size` of `19px` for `btn-lg`.

**Comment by ahmadabdolsaheb** [comment]
I just realized the issue was to related to my browser. 

Thank you @hemakshis for bringing it up the issue with the buttons.

I will close this issue for now to avoid confusion for other contributors but I will make sure the buttons issue is addressed.

**Comment by hemakshis** [comment]
@ahmadabdolsaheb should I open an issue for this?

**Comment by ahmadabdolsaheb** [comment]
Yes please that would be great.
