### ISSUE TITLE
Some slow tests

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#35276]
**Describe your problem and how to reproduce it:**

Some of the challenge tests take upward of a second to run.  This is typically due to lengthy timeouts or, typically for interview prep challenges, genuinely long calculations.

Below are examples where the tests are slow and include timeouts.  These tests involve simulating an event with Enzyme (or setting a component's state) and then waiting to see if the component changes appropriately.  However, it doesn't seem to be necessary to wait. As far as I can see, ReactWrapper.simulate executes synchronously.

- https://github.com/freeCodeCamp/freeCodeCamp/blob/0d787ceeecb164ea09c12a35d768bbc6831c42e6/curriculum/challenges/english/03-front-end-libraries/react/create-a-controlled-input.english.md

- https://github.com/freeCodeCamp/freeCodeCamp/blob/0d787ceeecb164ea09c12a35d768bbc6831c42e6/curriculum/challenges/english/03-front-end-libraries/react/optimize-re-renders-with-shouldcomponentupdate.english.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/0d787ceeecb164ea09c12a35d768bbc6831c42e6/curriculum/challenges/english/03-front-end-libraries/react/render-conditionally-from-props.english.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/0d787ceeecb164ea09c12a35d768bbc6831c42e6/curriculum/challenges/english/03-front-end-libraries/react/use-a-ternary-expression-for-conditional-rendering.english.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/0d787ceeecb164ea09c12a35d768bbc6831c42e6/curriculum/challenges/english/03-front-end-libraries/react/use-advanced-javascript-in-react-render-method.english.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/0d787ceeecb164ea09c12a35d768bbc6831c42e6/curriculum/challenges/english/03-front-end-libraries/react/use-array.filter-to-dynamically-filter-an-array.english.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/0d787ceeecb164ea09c12a35d768bbc6831c42e6/curriculum/challenges/english/03-front-end-libraries/react/write-a-simple-counter.english.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/ccd45f77ff65d8ac8b452f8d8031288c53171e1c/curriculum/challenges/english/03-front-end-libraries/react-and-redux/manage-state-locally-first.english.md

The interview prep challenges are different.  The problem here is that it can take a while for the solution function to compute the result for each of the tests i.e. finding large primes isn't a quick operation.  Instead, perhaps we could provide a look-up table as a solution, rather than re-computing them each time the test runs.  This provides the sanity check we need, but is quick.

Anyway, here are some examples which are a bit slow.

- https://github.com/freeCodeCamp/freeCodeCamp/blob/ccd45f77ff65d8ac8b452f8d8031288c53171e1c/curriculum/challenges/english/08-coding-interview-prep/project-euler/problem-14-longest-collatz-sequence.english.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/ccd45f77ff65d8ac8b452f8d8031288c53171e1c/curriculum/challenges/english/08-coding-interview-prep/project-euler/problem-7-10001st-prime.english.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/ccd45f77ff65d8ac8b452f8d8031288c53171e1c/curriculum/challenges/english/08-coding-interview-prep/rosetta-code/heronian-triangles.english.md

Finally, there are some tests which are delayed because they need to download css or images.  It's less obvious how to deal with that problem.  Example tests are:

- https://github.com/freeCodeCamp/freeCodeCamp/blob/63d15e0d985a43f9e39345db8816c435658194d4/curriculum/challenges/english/03-front-end-libraries/bootstrap/add-font-awesome-icons-to-all-of-our-buttons.english.md
- https://github.com/freeCodeCamp/freeCodeCamp/blob/63d15e0d985a43f9e39345db8816c435658194d4/curriculum/challenges/english/01-responsive-web-design/basic-css/add-borders-around-your-elements.english.md

**Tell us about your browser and operating system:**
* Operating System: Ubuntu 18.04.1 LTS

**Comment by raisedadead** [comment]
Please reopen if closed incorrectly
