### ISSUE TITLE
Mention values of denominations

### ISSUE THREAD

**Issue by alayek** [FreeCodeCamp/FreeCodeCamp#3527]
Challenge [Bonfire: Exact Change](http://www.freecodecamp.com/challenges/bonfire-exact-change) has an issue.

// Example cash-in-drawer array:
// [['PENNY', 1.01],
// ['NICKEL', 2.05],
// ['DIME', 3.10],
// ['QUARTER', 4.25],
// ['ONE', 90.00],
// ['FIVE', 55.00],
// ['TEN', 20.00],
// ['TWENTY', 60.00],
// ['ONE HUNDRED', 100.00]]

drawer(19.50, 20.00, [['PENNY', 1.01], ['NICKEL', 2.05], ['DIME', 3.10], ['QUARTER', 4.25], ['ONE', 90.00], ['FIVE', 55.00], ['TEN', 20.00], ['TWENTY', 60.00], ['ONE HUNDRED', 100.00]]);

```
It would be worthwhile mentioning the exact values in US Dollar for penny, nickel, dime and quarter. Not every student would be from US.

**Comment by abhisekp** [comment]
@alayek you're correct but maybe researching a bit is part of web development. Not everything that you come across in real world web development is pre-defined by the client. Sometimes, one has make some effort in searching.

> P.S. I'm not from US.

**Comment by koustuvsinha** [comment]
+1 I also feel it should be mentioned in the problem statement.

**Comment by ltegman** [comment]
The names of the denominations are clearly stated and can be quickly researched if the user is not familiar with US currency. Needing to research further information or concepts is a common occurrence in programming.

Thanks and happy coding!

**Comment by alayek** [comment]
Depends on what it is you are researching. If it is related to Web development, like documentation of certain function in Python, fine. You do have to Google it. An error message? Yes of course!

But if you have to Google stuff not relevant to your domain - like you are asked to build a currency converter and you have to Google origin of Japanese Yen - then yes, the client or Product Manager should have mentioned it in the specs.

With that logic ("You have to research stuff - we cannot give you all info"), you might as well remove all questions from your site and just tell people to Google and learn on their own. There has to be a line somewhere. Or what is the point of even framing problem statements?

Just for fun, replace that problem with, say, Indian currency; and see how many non-Indian people crib about it in the Gitter chat-room.

**Comment by abhisekp** [comment]
@alayek I'm with you now after the long description. :stuck_out_tongue_winking_eye: 

@ltegman please re-open this issue. The issue must be addressed with the required changes to the instructions.
> or let's switch to Chinese currency *Yuan*.
