### ISSUE TITLE
Text bleed on learn welcome page

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#35288]
the text is touching the edges of the screen when the screen is between 650 and 750 pixels.
Probably needs to wrapped in a grid container but not sure.

<img width="706" alt="screen shot 2019-02-19 at 9 10 15 am" src="https://user-images.githubusercontent.com/4591597/52993798-82d66100-3426-11e9-96d7-4c4495172257.png">

**Comment by DzmitryUr** [comment]
I have created PR to fix this.
There was a media query that sets padding for small sizes (<630px device width). So I just added padding for larger devices.
