### ISSUE TITLE
Confusing Wording on Bonfire: Diff Two Arrays

### ISSUE THREAD

**Issue by dougBelcher** [FreeCodeCamp/FreeCodeCamp#3529]
The Bonfire says "Compare two arrays and return a new array with any items not found in both of the original arrays.".  If you can't find an item in *both* arrays then the result will be infinite.  The wording may be less confusing if it says:

"Compare two arrays and return a new array with any items in the second array that are not found in the first."

**Comment by avastu** [comment]
Working on this!

**Comment by abhisekp** [comment]
"Compare two arrays and return a new array with any items in the second array that are not found in the first or any items in the first array that are not found in the second."

i.e.

"Return any items which doesn't exist in both the arrays."
