### ISSUE TITLE
fadail2

### ISSUE THREAD

**Issue by fadaile** [freeCodeCamp/freeCodeCamp#35309]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by fadaile** [comment]
my browser fir fox link
operating system windws 7

**Comment by thecodingaviator** [comment]
Your PR is missing any description about the bug whatsoever. Please check
