### ISSUE TITLE
Basic JavaScript: Count Backwards With a For Loop

### ISSUE THREAD

**Issue by jannilonline** [freeCodeCamp/freeCodeCamp#35308]
**Describe your problem and how to reproduce it:**
run the test***
this code pass**( " i >")is missing
for ( var i = 9;  1; i -= 2){myArray.push(i);}
var myArray =[9,7,5,3,1]

this code pass too**
for ( var i = 9; i > 1; i -= 2){myArray.push(i);}
var myArray =[9,7,5,3,1]
![capture](https://user-images.githubusercontent.com/47098383/53068912-10907a00-3515-11e9-8b06-d33a5adda838.PNG)

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-count-backwards-with-a-for-loop/16808
**Tell us about your browser and operating system:**
* Browser Name: chrome
* Browser Version:Google Chrome
Nearly up to date! Relaunch Google Chrome to finish updating.
Version 61.0.3163.100 (Official Build) (32-bit)

* Operating System: windows

**Comment by Nirajn2311** [comment]
@jannilonline why are you defining myArray again? The test check is myArray contains `[9,7,5,3,1]` and due to the redefinition the challenge passes.

**Comment by thecodingaviator** [comment]
I'm not sure this has something to do with the curriculum rather is an incorrect solution on the user's part. I'm closing this. If you think that it should remain open, add clarification and reopen the issue
