### ISSUE TITLE
Free Code Camp login sessions saving

### ISSUE THREAD

**Issue by petercrackthecode** [freeCodeCamp/freeCodeCamp#35300]
**Challenge Name:** Javascript Algorithms And Data Structures Certification- Intermediate Algorithm Scripting
**Issue Description: ** Cannot save login session when switching to challenges after successfully logging in.
**Browser Information: ** Google Chrome **Version 72.0.3626.109 (Official Build) (64-bit)**

Descriptive video: https://vimeo.com/317925080

**Comment by raisedadead** [comment]
Have you tried this troubleshooting step?

https://www.freecodecamp.org/forum/t/how-to-troubleshoot-sign-in-issues-on-curriculum-and-setting-pages/252012
