### ISSUE TITLE
Certification and all challanges blank

### ISSUE THREAD

**Issue by ineslaram** [freeCodeCamp/freeCodeCamp#35306]
Hello ! 

I have finished today the Responsive Web Design Certification: I had all the challanges done and i had just one project left which i finish today , but i dont know what it have happened because now everything is blank, there are only checked the projects and i can not access to the certification because it appers the follow:

![captura de pantalla 2019-02-19 a las 23 03 31](https://user-images.githubusercontent.com/34488859/53051221-996acf80-349b-11e9-86c3-02a250fd0349.png)

it says that my profile isn't public . 

i had also some of the challanges of javascript done.

Could someone help me ?

Thank you very much in advance

**Comment by ineslaram** [comment]
Sorry, i have already fix it ! thanksssss

**Comment by RandellDawson** [comment]
@ineslaram How did you resolve your issue?

**Comment by ineslaram** [comment]
It was my fault sorry ! I didnt know i had two differents accounts with 2 differents emails 

Thanks for your replay

**Comment by fadaile** [comment]
+You can also use a predefined generic empty class `strClass`. It's
usefull for anonymous objects, dynamic properties or casting other
types to object.
