### ISSUE TITLE
Last test of palindrome has typos, which causes incorrect answer. 

### ISSUE THREAD

**Issue by mfcastro** [FreeCodeCamp/FreeCodeCamp#3531]
Challenge [Bonfire: Check for Palindromes](http://freecodecamp.com/challenges/bonfire-check-for-palindromes) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
function palindrome(str) {
  // Good luck!
   s = str.toLowerCase().replace(/\s+/g,"").replace(/\s+|,|\./g,"");
  r = str.toLowerCase().split("").reverse().join("").replace(/\s+|,|\./g,"");
  if (s === r){
    return true;
  }
  else{
    return false;
  }
  
}



palindrome("A man, a plan, a canal. Panama");

```

The last test test if "0_0 (: /-\\ :) 0-0" is a palindrome. But the checking program wants an answer of true, but this will never be a palindrome .  The palindrome should be 0_0 (: /-\ :) 0_0 instead of 0_0 (: /-\\ :) 0-0

The test code says: 
assert(palindrome("0_0 (: /-\ :) 0-0") === true, '"0_0 (: /-\\ :) 0-0" should return true.');"0_0 (: /-\ :) 0-0" should return true.

**Comment by code402b** [comment]
I think you're correct and that the question is assuming that an underscore should be considered a punctation mark, despite this not technically being the case in English.

**Comment by abhisekp** [comment]
@code402b @mfcastro the last case is absolutely correct. Because after ignoring the punctuation marks i.e. anything other than alphabets and numbers, it becomes a palindrome.

https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3115#commitcomment-13110551

**Comment by mfcastro** [comment]
Thanks for clarifying that for me. I was able to fix my code and get it to work!

**Comment by Navankur94** [comment]
function palindrome(str) {
  // Good luck!
  str = str.toLowerCase();
  str=str.replace(/[^\w*]/g, "");
 
    function reverseString(str1) {
    return str1.split('').reverse().join('');
    }
  var str2 = reverseString(str);
if(str===str2){
  return true;
}
  else{
    return false;
  }
}


palindrome("0_0 (: /-\ :) 0_0");
//the last test should be (0_0 (: /-\ :) 0_0) instead of (0_0 (: /-\ :) # 0-0)
