### ISSUE TITLE
404 on the link ” Comparison with the Equality Operator ” in JS course 

### ISSUE THREAD

**Issue by randomSveta** [freeCodeCamp/freeCodeCamp#35338]
**Description:**
404 error when I click on the link " Comparison with the Equality Operator" on
“Basic JavaScript: Returning Boolean Values from Functions” page

**Where to find:**
JS course page “Basic JavaScript: Returning Boolean Values from Functions”:
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/returning-boolean-values-from-functions

**Steps:**
1. Go to the page https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/returning-boolean-values-from-functions
2. Find the text “Comparison with the Equality Operator” in the first paragraph
3. Click the text-link “Comparison with the Equality Operator”

**Actual result:**
There is a link to URL https://learn.freecodecamp.org/waypoint-comparison-with-the-equality-operator.
This link has a 404 error. You can see “Page Not Found” or 404 error on the open page.
![page not found freecodecamp 2019-02-20 11-43-20](https://user-images.githubusercontent.com/38963057/53200383-4d459980-3619-11e9-8f47-5e75b2d00674.png)
![page not found freecodecamp 2019-02-20 11-45-07](https://user-images.githubusercontent.com/38963057/53200384-4d459980-3619-11e9-8cdd-1153091929df.png)
![page not found freecodecamp 2019-02-20 11-45-20](https://user-images.githubusercontent.com/38963057/53200385-4d459980-3619-11e9-8b22-afdcb1455c08.png)

**Expected result:** 
I think it should be: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-equality-operator
(If someone knows better, please, write the comment)

**Comment by RandellDawson** [comment]
Hi @randomSveta Thank you for reporting this issue.   I am closing this issue, because it has already been reported and fixed on the `master` branch of our repo and will show up in production during the next release (coming soon).

**Comment by randomSveta** [comment]
Hi! @RandellDawson! 
Could you help, please? 

I have the same problem 404 with the link "Storing Values with the Equal Operator", 
 https://learn.freecodecamp.org/storing-values-with-the-assignment-operator

on the page  "Basic JavaScript: Generate Random Fractions with JavaScript" https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/generate-random-fractions-with-javascript 

I found a closed issue : 
https://github.com/freeCodeCamp/freeCodeCamp/issues/34895

Should I create a new one?

**Comment by RandellDawson** [comment]
@randomSveta PR #35125 has already been created to fix not only the link in the challenge you found above, but also 3 other challenges.  I have approved the PR already, but I am still awaiting one other reviewer to approve before it gets merged into the `master` branch.  Even after it is merged, the changes will be moved to our beta site first and then finally to production.  It is not necessary to create a new issue for this.

Thank you.

**Comment by randomSveta** [comment]
@RandellDawson,  Thank you so much for your help!
Also, big Thanks for the super detailed answers :)
