### ISSUE TITLE
Search results are cut off

### ISSUE THREAD

**Issue by rituteb** [freeCodeCamp/freeCodeCamp#35330]
**Describe the bug**
When searching for something in the search box at the top, the results box shown is cut off the screen.

**To Reproduce**
1. Go to https://learn.freecodecamp.org/
2. Click on the search box
3. Type in something to search "e.g. testing"
4. View the results

**Expected behavior**
The results box should be in the view, not cut off.

**Screenshots**
![screen shot 2019-02-21 at 10 30 56 am](https://user-images.githubusercontent.com/47578527/53180666-109b8300-35c4-11e9-98a7-a8fa102a0e6d.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 72.0.3626.109

**Additional context**
Related: #35146

**Comment by RandellDawson** [comment]
Closing this issue, because it has been resolved and the beta site does not exhibit this issue.  Once the beta site is moved to production, you will not experience this issue anymore.

**Comment by rituteb** [comment]
What's the URL for the beta site? Also, curious how soon the beta moves to production as this is a pretty big issue?

**Comment by RandellDawson** [comment]
Beta is at freecodecamp.rocks 

There is has been no date set yet on when it will be moved to production, but we are testing it extensively and could use your help in finding any new issues that may have popped up.

Over 9000+ PRs have been merged, so many bugs which were originally reportedvia GitHub issues have been fixed on the master branch and are live on the beta site.

**Comment by rituteb** [comment]
Great, thanks.
