### ISSUE TITLE
React: Create a Controlled Form Bug

### ISSUE THREAD

**Issue by darryn11** [freeCodeCamp/freeCodeCamp#35335]
**Describe your problem and how to reproduce it:**
Every time I click the submit button, an entirely new freecodecamp window opens within the challenge-preview-frame. 

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/react/create-a-controlled-form

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Chrome 68 
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![codecamp bug](https://user-images.githubusercontent.com/35150825/53196570-409b5400-35cd-11e9-9ff4-aa8ef8ce1a1c.jpg)

**Comment by RandellDawson** [comment]
Thank you for reporting this issue.  However, this issue has already been fixed on the master branch and can be validated on our [beta site](https://www.freecodecamp.rocks/learn/front-end-libraries/react/create-a-controlled-form) which will be moved to production in the near future.
