### ISSUE TITLE
The search bar and the search list are not proportional

### ISSUE THREAD

**Issue by lilia97** [freeCodeCamp/freeCodeCamp#35339]
<img width="1440" alt="screen shot 2019-02-21 at 11 38 12 pm" src="https://user-images.githubusercontent.com/34647698/53206639-cc46cc00-3631-11e9-8b3a-27e04b9b825f.png">

**Comment by RandellDawson** [comment]
@lilia97 This is a known issue on production which has already been resolved on our `master` branch and will be moved production soon.  Feel free to checkout the same challenge on our newest beta site located at https://freeCodeCamp.rocks

I am closing this as an issue that has already been addressed and is awaiting deployment to production.

Thanks for understanding.
