### ISSUE TITLE
Unable to use js-teardown section in Responsive Web Design curriculum challenge files

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#35349]
Today, I discovered that I could write a helper function in a `js-teardown` section of a Responsive Web Design challenge and reference it in the assert statement with the test working correctly when running `npm run develop` locally.  However, when I ran `npm run test:curriculum` It would fail with a message like:
```
\ Testing

 565 passing (6s)
  74 pending
  1 failing

  1) Check challenges
       Check challenges (english)
         Use Clockwise Notation to Specify the Margin of an Element
           Check tests.:
     Error: Seed file should be only the one.
      at Context.it (test\test-challenges.js:209:19)



npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @freecodecamp/freecodecamp@0.0.1 test:curriculum: `cd ./curriculum && npm test && cd ../`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @freecodecamp/freecodecamp@0.0.1 test:curriculum script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\OPT\AppData\Roaming\npm-cache\_logs\2019-02-22T05_22_47_354Z-debug.log
``` 
I finally gave up and moved the helper function to the `testString` directly in front of the assert statement in which I was referencing it.  After moving it and deleting my created `js-teardown` sectin, everything worked fine for both `npm run develop` and `npm run test:curriculum`.

It would be nice if any of the challenge section files could make use of a `js-teardown` section, because it would have made my `testString` much cleaner and easier to read.

**Comment by ValeraS** [comment]
@RandellDawson 
For html challenges you can do something like this:
````
<div id="html-teardown">

```html
<script>
window.removeCssComments = str => str
    .replace(/<style>|<\/style>/g,'')
    .replace(/\/\*[\s\S]+?\*\//g,'');
</script>
```

</div>
````

**Comment by RandellDawson** [comment]
@ValeraS It is not that the code I wrote in the `js-teardown` section did not work with my assert, it is that the test runner threw an error. 

When I wrote:
````
<div id="js-teardown">

```js
const removeCssComments = str => str
    .replace(/<style>|<\/style>/g,'')
    .replace(/\/\*[\s\S]+?\*\//g,'');
```

</div>
````
and had the following test, everything worked as I expected using `npm run develop`.
```yml
  - text: You should use the clockwise notation to set the margin of <code>blue-box</code> class.
    testString: assert(/\.blue-box\s*{[\s\S]*margin:\s*\d+px\s+\d+px\s+\d+px\s+\d+px(;[\s\S]*}|\s*)/.test(removeCssComments(code)));
```

**Comment by ValeraS** [comment]
@RandellDawson The code you write works not because you do it right, but because you are lucky. At the moment, the behavior of which file will be shown in the editor, if you have two files, is not defined. So you should do as suggested in my previous comment.

**Comment by RandellDawson** [comment]
I guess I am not understanding what you mean by two files.  What two files?  There is just a single file with multiple sections.  I must be misunderstanding. 

When you say I got lucky, are you referring to the code I show in my last post or what I ended doing on PR #35342 which passed the Travis build?

**Comment by ValeraS** [comment]
Each `{ext}` in the `challengeSeed` section transforms in a separate file, e.g. index.html, index.js. One of this file will be shown in the editor in the client app.

**Comment by RandellDawson** [comment]
OK

**Comment by Bouncey** [comment]
We could expand the challenge writing docs to cover this.

**Comment by RandellDawson** [comment]
@Bouncey That would really be great!
