### ISSUE TITLE
Text overflows out of button / button does not expand on homepage

### ISSUE THREAD

**Issue by PhoeniXAbhisheK** [freeCodeCamp/freeCodeCamp#35351]
**Describe the bug**
When accessing [freecodecamp.rocks](freecodecamp.rocks) via mobile, the 'Start coding(it's free)' button does not expand with respect to text.
As a result, the  text overflows the button area.

**To Reproduce**
1. Go to [freecodecamp.rocks](freecodecamp.rocks) via mobile
2. Scroll down to '....'
3. See error

**Expected behavior**
The button should expand appropriately and text should not overflow

**Screenshots**
![screenshot_20190222-113920](https://user-images.githubusercontent.com/16290904/53233347-3784b280-36b3-11e9-9b05-bbe4bb19f99d.png)
![screenshot_20190222-113933](https://user-images.githubusercontent.com/16290904/53233354-3a7fa300-36b3-11e9-8da4-d43fa5007288.png)

**Smartphone (please complete the following information):**
 - OS: Android
 - Browser Chrome
 - Version 72.0.3626.105

**Comment by Ensive** [comment]
I am currently looking into this issue. I will keep you posted

**Comment by Ensive** [comment]
I've found that there is one more place where this issue happens, on welcome page:
<p align="center"><img src="https://user-images.githubusercontent.com/3208083/53288924-87d54080-3797-11e9-9af0-5a997603bf0a.png" width="200" /></p>
These are the only places issue occurs, so I gonna apply an ultimate fix for such cases using a mobile first media query.

**Comment by Ensive** [comment]
PR is ready for review https://github.com/freeCodeCamp/freeCodeCamp/pull/35378
