### ISSUE TITLE
Only two subchallenges resolve - Waypoint: Specify How Fonts Should Degrade

### ISSUE THREAD

**Issue by maddymaster** [FreeCodeCamp/FreeCodeCamp#3535]
Challenge [Waypoint: Specify How Fonts Should Degrade](http://freecodecamp.com/challenges/waypoint-specify-how-fonts-should-degrade) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style> -->
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
    
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by ustafurkn** [comment]
what is problem ?

**Comment by bugron** [comment]
@maddymaster thanks for posting this issue!
You've commented your opening `style` tag: `<style> -->`. Remove `-->` and you'll be able to pass this challenge. Closing this issue. Feel free to reopen if you still experience problems.
If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
