### ISSUE TITLE
Test methods displayed (source) in the challenge view.

### ISSUE THREAD

**Issue by 4lador** [FreeCodeCamp/FreeCodeCamp#3536]
There is a bug in javascript challenges (at least the first ones). 

The objectives are 'undefined' and there's the source code of the test methods in place of the todo list.

![5cded5904f176c2889d1f7ecd8e33e43](https://cloud.githubusercontent.com/assets/5941435/10171008/13f99104-66d8-11e5-82f5-84d6a886ee58.png)

**Comment by bugron** [comment]
@4lador thanks for posting this issue!
It's part of the challenges that you are able to see the tests that are running against your code. For more information take a look at [this comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/2818#issuecomment-135908153). Closing this issue.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by 4lador** [comment]
Hi Arsen,

My bad,  sorry :)
Thanks for fast answer.

Have a nice day,
Damien
Le 29 sept. 2015 18:41, "Arsen Melikyan" <notifications@github.com> a
écrit :
