### ISSUE TITLE
ajax challenges: seed code doesn't match description

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35361]
In the `JSON APIs and Ajax` section, the seed code uses the class `message box`, but the instructions tell you to change the item with class `message` - This doesn't affect the ability to complete the challenges, but might be confusing.

![screen shot 2019-02-22 at 11 00 33 am](https://user-images.githubusercontent.com/20648924/53258142-83266480-3691-11e9-8e5c-7062515cac6e.png)

All the challenges in this section, except the geolocation one, use this class and it is not used in any of the instructions or tests.

**Solution:**  The class for that element should be changed to just `"message"` in the seed code for all of those challenges.

**PR created:**
- [x] arabic
- [x] chinese
- [x] english
- [x] portuguese
- [x] russian
- [x] spanish

**PR merged:**
- [x] arabic
- [x] chinese
- [x] english
- [x] portuguese
- [x] russian
- [x] spanish

**Comment by sreysa** [comment]
Can I do this one????

**Comment by moT01** [comment]
Sure, @sreysa. Let us know if you need anything.

**Comment by RandellDawson** [comment]
It appears out of the 9 challenges in that section, only `Get Geolocation Data to Find A User's GPS Coordinates` does not use `class="message box"`.

**Comment by Nitin96Bisht** [comment]
Hi @moT01 @RandellDawson, I have created my first PR. This is only for **JSON APIs and Ajax** section for all languages. Please have a look and let me know If anything needs to be improved. 

I will create a separate PR for all other sections except **Get Geolocation Data to Find A User's GPS Coordinates** once It gets resolved.

**Comment by moT01** [comment]
@Nitin96Bisht, you should make changes to all 8 files for one language in a PR, and make a separate PR for each language. Similar to what I did [here](https://github.com/freeCodeCamp/freeCodeCamp/issues/35155). I'll add check-boxes to this issue. If you and @sreysa want to split them up or something.

**Comment by Nitin96Bisht** [comment]
Hi @moT01, Thanks for your suggestions! I have created PR for English only for all 8 files. Please check and let me know If any changes required. Meanwhile, I am creating another PR for all languages.

**Comment by RandellDawson** [comment]
@Nitin96Bisht Make sure you create a separate PR for each language which will have the 8 files each.

**Comment by Nitin96Bisht** [comment]
Ok @RandellDawson

**Comment by RandellDawson** [comment]
@Nitin96Bisht One other thing.  Make sure you create each new branch from master, so that the other changes you made in the other languages will not also be on the next PR.  Your Chinese version also has English files on it.

**Comment by Nitin96Bisht** [comment]
Ok @RandellDawson, Thanks for your suggestions. I will take care of this.

**Comment by Nitin96Bisht** [comment]
Hi @RandellDawson, I have created PR for all languages. Kindly review it and let me know If anything needs to be improved.
