### ISSUE TITLE
Tests for various challenges are too strict about line breaks before method calls (part 2)

### ISSUE THREAD

**Issue by ZebulanStanphill** [freeCodeCamp/freeCodeCamp#35368]
_Not all of the challenges listed in #35090 were fixed by #35093. This issue is for the remaining challenges that the aforementioned PR did not modify._

## The problem
The tests for various challenges are too strict about line breaks before method calls.

E.g. something like this passes:

```js
document.getElementById( 'getMessage' )
      .onclick = function() {};
```

But this causes the tests to fail:

```js
document
      .getElementById( 'getMessage' )
      .onclick = function() {};
```

## Affected challenges
- ["JSON APIs and Ajax: Access the JSON Data from an API"](https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/access-the-json-data-from-an-api):
```js
console.log(
  json[2]
    .codeNames[1]
);
```
- ["JSON APIs and Ajax: Get Geolocation Data to Find A User's GPS Coordinates"](https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/get-geolocation-data-to-find-a-users-gps-coordinates):
```js
if ( navigator.geolocation ) {
  navigator.geolocation.getCurrentPosition(
    pos => {
      document.getElementById( 'data' )
        .innerHTML =
          'latitude: ' +
          position.coords.latitude +
          '<br />longitude' +
          position.coords.longitude;
      }
    );
}
```

## Browser and OS info
* Browser Name: Firefox Developer Edition
* Browser Version: 66.0b9
* Operating System: Antergos Linux

**Comment by Ensive** [comment]
I am looking into it

**Comment by Ensive** [comment]
@RandellDawson 
Hi Randel,
Do you think something like `assert(code.replace(/(?:\r\n|\r|\n|\s+)/g, '').match(), 'message')` would help? My concern is, that it would remove spaces in actual strings (if any inside of the code).
Shall we move in this direction (means `replace`) or different?

**Comment by RandellDawson** [comment]
@Ensive Yes, that is more like what I am thinking.  You have valid concerns concerning removing spaces in actual strings.  In challenges that do not have specific code strings in the `script` element, we should be fine, so for these specific challenges we could maybe use a helper function like:
```
const removeWhiteSpace = str => str.replace(/\s/g, '');
```
Then we could use it in the `testString` like the following for the `Access the JSON Data from an API`
```
  - text: Your code should use bracket and dot notation to access the proper code name, and print "Loki" to the console.
    testString: const removeWhiteSpace = str => str.replace(/\s/g, '');assert(removeWhiteSpace($('script').text()).match(/console\.log\(json\[2\](?:\.codeNames|\[('|")codeNames\1\])\[1\]\)/));
```
or better yet, move the helper function into a special `div` within the `section` with id="html-teardown" like:
````
<div id="html-teardown">

```html
<script>
  window.removeWhiteSpace = str => str.replace(/\s/g, '');
</script>
```

</div>

</section>
````
and then the test would look cleaner:
```
  - text: Your code should use bracket and dot notation to access the proper code name, and print "Loki" to the console.
    testString: assert(removeWhiteSpace($('script').text()).match(/console\.log\(json\[2\](?:\.codeNames|\[('|")codeNames\1\])\[1\]\)/));
```

Lastly, most of the challenges are missing a valid full working solution in the `solution` section of the challenge file, which are used to validate the tests still allow a valid solution to pass.

**Comment by Ensive** [comment]
@RandellDawson 
Shall I create PR with changes based on your suggestion for these two specific challenges?
Shall we consider to apply the same fix for other challenges?
Do you think putting a helper `removeWhiteSpace` function into `html-teardown` section is robust enough at the current moment?

**Comment by RandellDawson** [comment]
Let me check with a few other collaborators, because I think we might already have minifier library we could use instead.  If that is the case, then I will let you know how we can use it instead.  Then we would not have to worry about accidentally removing white space from code which actually needs to be a part of a string or something.  Again, this is not an issue for these particular challenges, but I would rather use something that could be a model for how to best write tests for these types of challenges in the future.  Give me a day to get back with you.

**Comment by Ensive** [comment]
@RandellDawson 
I agree. Thanks for the updates. Looking forward to hearing from you

**Comment by RandellDawson** [comment]
I have asked @ValeraS who has a very solid understanding of what helper utilities to which we have access.

**Comment by Ensive** [comment]
@ValeraS 
Any updates on this or shall we use approach described above?

**Comment by RandellDawson** [comment]
@Ensive We have concluded for now, we will  have to write our own as they do not want to add another package to the library.
