### ISSUE TITLE
Find the Longest Word Challenge - error when using a for loop without brackets

### ISSUE THREAD

**Issue by bravas** [freeCodeCamp/freeCodeCamp#35370]
**Describe your problem and how to reproduce it:**
On challenge 'Find the Longest Word' if I try to use a for loop without curly brackets I'm getting the following error:

```
'TypeError: unknown: Cannot read property '0' of undefined

transformers.js:66 TypeError: unknown: Cannot read property '0' of undefined
    at Function.e.get (babel.js:3632)
    at e.h [as unshiftContainer] (babel.js:42437)
    at t.<anonymous> (index.js:45)
    at r (babel.js:43256)
    at e.o [as _call] (babel.js:39993)
    at e.i [as call] (babel.js:39965)
    at e.a [as visit] (babel.js:40022)
    at e.visitQueue (babel.js:39553)
    at e.visitMultiple (babel.js:39506)
    at e.visit (babel.js:39593)
```
I tried a for loop in other challenges the same way and seems to work.

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-algorithm-scripting/find-the-longest-word-in-a-string/

**Tell us about your browser and operating system:**
* Browser Name: Chrome 
* Browser Version: Version 72.0.3626.109 (Official Build) (64-bit)
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![img](https://user-images.githubusercontent.com/21130805/53283225-3bf8ac00-3743-11e9-858f-060e70d646e9.png)

```js
function findLongestWordLength(str) {
  var words = str.split(' ');
  var maxLength = 0;
  for (let i = 0; i < words.length; i++) 
    if (words[i].length > maxLength) maxLength = words[i].length
  
  return maxLength;
}

findLongestWordLength("The quick brown fox jumped over the lazy dog");
```

**Comment by raisedadead** [comment]
Thanks. Can you post the code in the screenshot in here? 

You can format code with 
<code>```js</code> 

```Your code here```

<code>```</code> 
in the comment box below.

**Comment by bravas** [comment]
Thanks for the prompt reply. Just updated it.

**Comment by raisedadead** [comment]
Thanks for sharing your code. I can confirm this is indeed a bug on the platform. 

We have recently fixed this issue that is shipping soon. You can confirm this by testing it out on [our beta testing site](freecodecamp.rocks).

We plan to be able to release this fix in the upcoming weeks.

Thanks for patience.
