### ISSUE TITLE
Missing image on freecodecamp.rocks/news/

### ISSUE THREAD

**Issue by vcc-LG** [freeCodeCamp/freeCodeCamp#35377]
![image](https://user-images.githubusercontent.com/22344951/53288843-a4687d00-3785-11e9-824a-6aec9e1bb068.png)

File should live at "/news/content/images/2018/12/FCC-logo-white.png" but appears to be missing.

**Comment by Nirajn2311** [comment]
Even Quincy's avatar photo is not there next to the news articles.

**Comment by huyenltnguyen** [comment]
The image URLs are pointing to `freecodecamp.rocks`, I'm guessing we are not hosting images there, hence the 404 error.

Making them point to `freecodecamp.org` should resolve the issue.

![untitled](https://user-images.githubusercontent.com/25715018/53290539-094cc300-37d8-11e9-8b00-b205bc6be06a.png)

**Comment by Bouncey** [comment]
We spun up a test instance of news for `.rocks` to point at. More so for us to test infrastructure and to ensure we could proxy it correctly.

I wouldn't worry too much about this.

**Comment by raisedadead** [comment]
Thanks for reporting. I have update this in the overview PR linked above.
