### ISSUE TITLE
Error in solution for "Basic JavaScript: Use the Conditional (Ternary) Operator"

### ISSUE THREAD

**Issue by erwncmps** [freeCodeCamp/freeCodeCamp#35386]
The solution for "Basic Javascript: Use the Conditional (Ternary) Operator", linked below, contains a an error:

Challenge: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/use-the-conditional-ternary-operator

Solution: https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-javascript/use-the-conditional-ternary-operator/

Indeed, the working solution is not: return (a = b ? true : false ).
It's return (a == b ? true : false ).

**Comment by RandellDawson** [comment]
@erwncmps Thank you for reporting this issue found on production.  The challenge has been recently rewritten, but the changes have not been pushed to production.  You can view the new version of the challenge on our [beta testing site](https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/basic-javascript/use-the-conditional-ternary-operator).

That being said, I noticed the [guide article on the beta](https://www.freecodecamp.rocks/guide/certifications/javascript-algorithms-and-data-structures/basic-javascript/use-the-conditional-ternary-operator/) has not been updated to match the change the revision of the challenge shown on the beta site above.  

This means there is still an issue which needs resolution here.

**Comment by RandellDawson** [comment]
For anyone who wants to correct the guide article, the [Guide article file is located here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/certifications/javascript-algorithms-and-data-structures/basic-javascript/use-the-conditional-ternary-operator/index.md).

If you have questions about how to contribute, please see [How to work on Guide articles](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-guide-articles.md).  If you have any questions, you can visit our [Contributors room on Gitter](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by erwncmps** [comment]
Thanks, Randell. Looks good to me!

**Comment by Snowcat8** [comment]
I can contribute to this

**Comment by RandellDawson** [comment]
@Snowcat8 Looks like @rupali317 created a PR (#35388) to solve the issue.  Feel free to look at the changes @rupali317 made and comment on that PR if you find it does not work.
