### ISSUE TITLE
code is correct refuses to let me go to nest challenge have validated on code pen 

### ISSUE THREAD

**Issue by bigkatspence** [FreeCodeCamp/FreeCodeCamp#3538]
Challenge [Waypoint: Size your Images](http://freecodecamp.com/challenges/waypoint-size-your-images) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }
</style>

<h2 class="red-text" CatPhotoApp </h2>

<style>
  . smaller- image { width: 100px; }
</style>

<img src="https://bit.ly/fcc-relaxing-cat">

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

```

**Comment by bugron** [comment]
@bigkatspence thanks for posting this issue!
Your `img` misses `class` of `smaller-image`, `. smaller- image ` should be `.smaller-image` and your opening `h2` tag is not closed: `<h2 class="red-text" CatPhotoApp </h2>`, should be `<h2 class="red-text"> CatPhotoApp </h2>`.

Closing this issue. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
