### ISSUE TITLE
Remove helpful links from about page

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#35397]
since the helpful links are included in the footer, the helpful links section in the about page should be removed. 

<img width="1438" alt="screen shot 2019-02-22 at 5 29 24 pm" src="https://user-images.githubusercontent.com/4591597/53327909-e61a3480-38f9-11e9-81ca-6d52f35154df.png">

**Comment by yehia67** [comment]
Could I help?

**Comment by ahmadabdolsaheb** [comment]
yes, please. Could you please delete the row that has the column with the following class `helpful-links col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1 col-xs-12` while at it could you please also change the class to for the about page to `questions col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12` so the about page would look wider on larger screens. 🙏

**Comment by yehia67** [comment]
Yeah sure :dancer:

**Comment by yehia67** [comment]
okay done I will make the PR

**Comment by yehia67** [comment]
![image](https://user-images.githubusercontent.com/21314724/53338727-13bca900-390d-11e9-91c5-b6aa04b52a02.png)
Could you please tell me why checks failed? I am new just don't understand why?

**Comment by raisedadead** [comment]
@yehia67 

![image](https://user-images.githubusercontent.com/1884376/53363259-067dd980-3962-11e9-9583-43d434c8b86b.png)


If you click the details, you will get to the CI build logs.

**Comment by yehia67** [comment]
@raisedadead   Thank you

**Comment by Grantlyk** [comment]
Hey, has this been resolved? if not I can take over

**Comment by JamieVaughn** [comment]
It looks like the footer with the links has been removed so perhaps the list of helpful links should not be removed at this point.

**Comment by uncblythe1** [comment]
The helpful links are now at the bottom of the FAQ page.  Is this where they should be?  It looks like they would be more useful at the About page or as a footer for the home page?

**Comment by aenon** [comment]
As of now (June 13 2019), the useful links are still showing on the [about page](https://about.freecodecamp.org/), and one of the links is still "Our Medium publication". This needs to change. Either this link gets updated, or this section gets removed.

**Comment by aenon** [comment]
Adding https://github.com/freeCodeCamp/freeCodeCamp/pull/36288 for this.
