### ISSUE TITLE
Hint link on "Basic Node and Express - Use the .env File" is incorrect

### ISSUE THREAD

**Issue by jianga** [freeCodeCamp/freeCodeCamp#35396]
**Describe your problem and how to reproduce it:**
Clicking "Get a hint" at https://learn.freecodecamp.org/apis-and-microservices/basic-node-and-express/use-the--env-file gives a 404. The link is incorrect and should be /use-the-.env-file instead of /use-the--env-file.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/apis-and-microservices/basic-node-and-express/use-the--env-file

**Tell us about your browser and operating system:**
* Browser Name: n/a
* Browser Version: n/a
* Operating System: n/a

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
Hi @jianga Thank you for reporting this issue. 

I can also confirm this is also an issue on the beta site (https://freecodecamp.rocks).
