### ISSUE TITLE
[Beta] Setting page update modal should be removed

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#35405]
## Describe the bug
On updating preferences on the settings page. There's a modal which shows up on the top of the page which I think is of no use as they are not visible until we scroll to the top. If we change multiple preferences then the modals stack up. 

## Screenshots
![screenshot 23](https://user-images.githubusercontent.com/26724128/53358259-d2042080-3955-11e9-951e-08bd71c9eb7a.png)

## Solution proposal
We should show a side modal and then it should get closed automatically after a few seconds. Something like:
![screenshot 24](https://user-images.githubusercontent.com/26724128/53358485-82722480-3956-11e9-89a8-8577dcc0c4b0.png)

## Desktop (please complete the following information):
 - OS: Windows 10 Pro 32 bit
 - Browser: Chrome
 - Version: Latest stable

**Comment by Bouncey** [comment]
I'm open to toast messages for this type of notification.


cc/ @QuincyLarson

**Comment by Ensive** [comment]
@Bouncey 
@raisedadead 
Is it under discussion?

**Comment by Ensive** [comment]
I am thinking about taking this, but this needs to wait until the weekend

**Comment by Bouncey** [comment]
@Ensive we used to use `react-notification`, but that hasn't had an update in 2 years, so I am against using it again.

A quick search finds [`react-toastify`](https://github.com/fkhadra/react-toastify) and despite the colourful language in the README, it looks well documented and recently maintained.

**Comment by ritute** [comment]
Is this the only location where such notifications are used?

**Comment by Bouncey** [comment]
@ritute The notifications are controller by the `Flash` component (`client/src/components/Flash/index.js`)

**Comment by Ensive** [comment]
@Bouncey 
I will take a look this Saturday morning. Feel free to assign and keep it on me through the weekend.
I will keep you posted.

**Comment by hemakshis** [comment]
Hi!
If @Ensive is not working on this issue anymore I'd like to take it up :)

**Comment by Ensive** [comment]
@hemakshis I do not mind
I have something stashed. But if you deliver it quick, would be nice!

**Comment by hemakshis** [comment]
@Ensive thanks!
@Bouncey, I have a few questions:- 
1. Which position seems the best of all the available 6 options?
2. After how many seconds of delay the notification should close?

**Comment by QuincyLarson** [comment]
@hemakshis Thanks for your patience. Great questions.

> Which position seems the best of all the available 6 options?

We should keep the notification always fixed at the top of the viewport. Instead of adding another notification, we should have a subtle animation where the old notification goes away and the new notification appears.

> After how many seconds of delay the notification should close?

These notifications shouldn't close until the user closes them.

Is that enough information for you to get started on this? Let me know if I can be of any further help. Thanks again for contributing to this.

**Comment by hemakshis** [comment]
Thanks, @QuincyLarson! I think this much of info is enough. I'll soon send a PR.
