### ISSUE TITLE
Sass: Apply a Style Until a Condition is Met with @while - Page hangs

### ISSUE THREAD

**Issue by tnharvey** [freeCodeCamp/freeCodeCamp#35408]
**Describe your problem and how to reproduce it:**
As I began typing out my solution, the page kept hanging, and I figured it had to do with an infinite loop that would occur as I typed my solution, since the page is auto-rendering my code as I type it. Each time, I would have to reopen the page in a new tab to type the code, as it would hang. I even tried creating the incrementation line first, still hung. I eventually just typed the solution in notepad and pasted it in, and that worked fine.

I don’t know if it’s possible to have this page use a longer delay before auto-rendering (I think it's set to 200ms), or if there is a way to have people enter their solution in a particular order that would avoid an infinite loop, but it seemed buggy, so I thought I’d mention it.  :smiley:
**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 72.0.3626.109 (Official Build) (64-bit)
* Operating System: Windows 10 64 Pro Version 10.0.17134 Build 17134

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ValeraS** [comment]
Resolved. You can check it on beta site https://www.freecodecamp.rocks/
