### ISSUE TITLE
[Challenge descriptions] - Move punctuation inside code blocks/tags?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35401]
#### At certain widths, punctuation next to a code block gets pushed to its own line because it treats it like there's a space there, or like it's it's own element or something....

![screen shot 2019-02-25 at 8 24 57 am](https://user-images.githubusercontent.com/20648924/53343862-f40a8e00-38d6-11e9-8d5a-313409b2b542.png)

### A few more examples... 
![screen shot 2019-02-25 at 8 16 52 am](https://user-images.githubusercontent.com/20648924/53343513-28317f00-38d6-11e9-87ef-7178462fdc9b.png)

<hr>

![screen shot 2019-02-25 at 8 18 02 am](https://user-images.githubusercontent.com/20648924/53343519-2b2c6f80-38d6-11e9-802d-c9a989afc146.png)

**Comment by thecodingaviator** [comment]
I'd say that's because to HTML, those two are different things. I don't really think that there's a workaround other than wrapping them up in a wrapper and making its width `fit-content`.

**Comment by moT01** [comment]
I was thinking to change it to something like `<code>1fr.</code>` instead of `<code>1fr</code>.` in the descriptions.

**Comment by Nitin96Bisht** [comment]
Hi @moT01, Let me know whether It needs to be changed or not. I would like to work on this.

**Comment by moT01** [comment]
Keep your eye on the conversation here. This would pretty much touch every challenge file across all languages, and might be more of a hassle than it's worth.

**Comment by thecodingaviator** [comment]
That would make it look like `1fr.` and cause widespread confusion, not really a good idea IMO

**Comment by moT01** [comment]
Good point @thecodingaviator, that's probably not the way to go - something like you suggested then is probably best. Maybe just wrapping them in a span tag - `<span><code>1fr</code>.</span>`

**Comment by thecodingaviator** [comment]
We'll also need to make the `span` have `width: fit-content` so it does not snap to the next line

**Comment by ojeytonwilliams** [comment]
I think this is primarily a css issue.  The code elements are styled with
```
code:after {
    letter-spacing: -.2em;
    content: " ";
}
```
This puts a breaking space after the code block allowing punctuation to dangle.  Replacing the content with a non-breaking space stops that.  The following should solve the problem:

```
code:after {
    letter-spacing: -.2em;
    content: "\00a0";
}
```
