### ISSUE TITLE
generators don't work: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by chuckadams** [freeCodeCamp/freeCodeCamp#35409]
I used to be able to use generator functions to solve ES6 challenges, but a recent change has rendered this impossible.  The following code does work in jsfiddle, but not in the FCC challenge.  Googling around suggests that there's a babel plugin missing, specifically `@babel/plugin-transform-runtime`

```
function* oddFibsUpTo(n) {
  let i = 1;
  let j = 1;
  while (true) {
    if (i % 2) yield i;
    [i, j] = [j, i + j];
    if (i > n) return;
  }
}

console.log(Array.from(oddFibsUpTo(100)).reduce((sum, n) => sum + n, 0))
```

What I get in the output window: 
```
// running tests
regeneratorRuntime is not defined
regeneratorRuntime is not defined
regeneratorRuntime is not defined
regeneratorRuntime is not defined
regeneratorRuntime is not defined
regeneratorRuntime is not defined
// tests completed
```

**Comment by chuckadams** [comment]
Oops, by "not in the browser", I meant not in the code challenge editor.  I've attempted this on the latest versions of both Firefox and Chrome and get the same error in each.

**Comment by RandellDawson** [comment]
Do you have a link to the specific challenge?

**Comment by chuckadams** [comment]
It happens on any challenge at all, but the specific one I was applying it to was this one: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sum-all-odd-fibonacci-numbers/

**Comment by raisedadead** [comment]
We do not have these on https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sum-all-odd-fibonacci-numbers

So the runtime issue is probably fixed??

**Comment by chuckadams** [comment]
I can verify that this issue doesn't occur on the beta site, so I'll go ahead and close this.
