### ISSUE TITLE
ES6: Use Destructuring Assignment to Assign Variables from Arrays - Testing Incorrect Concept

### ISSUE THREAD

**Issue by tnharvey** [freeCodeCamp/freeCodeCamp#35407]
**Describe your problem and how to reproduce it:**
While I was able to get this working eventually, I was disappointed to discover that, rather than testing my understanding of how destructuring can be used to assign variables from arrays, it appears to actually be testing my understanding of variable scope. I correctly understood that assignment could be switched using `[a,b]=[b,a]`, however, it did not work because I included `const` from the instructions. That issue should be explicitly taught or the examples in the instructions changed, so as not to prime the learner incorrectly. The coding challenge should focus on destructuring rather than scope. I say this as an expert on training and curriculum design, not just as someone complaining. A simple reminder about scope in the instructions could solve this, but the challenge itself might become too easy. If that is the case, the challenge would need to be rewritten.  :D

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-arrays

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 72.0.3626.109 (Official Build) (64-bit)
* Operating System: Windows 10 64-bit Pro Version 10.0.17134 Build 17134

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Didn't seem like a screenshot was needed, as I was not having that type of problem.

**Comment by lasjorg** [comment]
I might be wrong but I think, at least the scope part, won't be a problem after https://github.com/freeCodeCamp/freeCodeCamp/pull/34538 that removes the unnecessary IIFEs is ready.

But just to be clear, and if I understood you correctly, you can't use const like this.

```
let a = 8, b = 6;
const [a, b] = [b, a];
Uncaught SyntaxError: Identifier 'a' has already been declared
```

**Comment by tnharvey** [comment]
Correct, I was not able to use it as you described, with const.
If #34538 resolves it, then no worries, thanks!

**Comment by RandellDawson** [comment]
@tnharvey #34538 will still not allow you to write `const [a, b] = [b, a];`

**Comment by lasjorg** [comment]
@tnharvey I might not have been very clear about it now that I re-read my post. What I meant is.

1. When the IIFE is removed there is no longer scope consideration as everything will be top-level.

2. As pointed out, the reason why you can't use `const` is not because of scope, but because you can't re-declare a variable declared with let. I thought posting the console error made that clear.

Simpler example:
```
let a;
const a = 42;
Uncaught SyntaxError: Identifier 'a' has already been declared
```

**Comment by tnharvey** [comment]
Sorry, yes, I thought the example you gave was a copy of what was there,
but reading it I see the two declarations, and understand what you mean.
Thanks!

**Comment by RandellDawson** [comment]
@tnharvey Are you ok with us closing this issue?

**Comment by tnharvey** [comment]
Yes, thank you.
