### ISSUE TITLE
Change code tags to blockquote tags for backend challenges

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35413]
The `code` tags on the backend style challenges should be changed to `blockquote` tags with `<br>`'s for line breaks.
#### code tag example:
<img width="808" alt="screen shot 2019-02-25 at 7 18 42 pm" src="https://user-images.githubusercontent.com/20648924/53380207-2eeddf80-3932-11e9-8ba9-edf85e211f9e.png">

#### blockquote tag example:
<img width="662" alt="screen shot 2019-02-25 at 7 19 25 pm" src="https://user-images.githubusercontent.com/20648924/53380234-4b8a1780-3932-11e9-8919-09740a291cbd.png">

Single lines of code, that are on their own line, should also be changed to use the blockquote tags. Since we are going through these, we should also move any challenge instructions found in the `section` element with `id='description'` to the `section` element with `id='instructions'`. And feel free to clean up anything else you find.

**PR created:**
- [x] Managing Packages with NPM - @moT01
- [x] Basic Node and Express - @moT01 
- [x] MongoDB and Mongoose - @RandellDawson 
- [x] Information Security with HelmetJS - @thecodingaviator 
- [x] Quality Assurance and Testing with Chai - @Nitin96Bisht 
- [x] Advanced Node and Express - @thecodingaviator 

**PR merged:**
- [x] Managing Packages with NPM
- [x] Basic Node and Express
- [x] MongoDB and Mongoose
- [x] Information Security with HelmetJS
- [x] Quality Assurance and Testing with Chai
- [ ] Advanced Node and Express

**Comment by RandellDawson** [comment]
@moT01 Use the Moderator Tools app and search for any existing PRs on each challenge file by using the `Filename` `Search` feature.  You may find PRs already exist for a file making similar changes.

**Comment by RandellDawson** [comment]
I will start with making a PR for the `MongoDB and Mongoose` section challenges.

**Comment by thecodingaviator** [comment]
I don't think there are any challenges in `Basic Node and Express` which requires this

**Comment by thecodingaviator** [comment]
I'm making a Pr for the `Information Security with HelmetJS` challenges

**Comment by RandellDawson** [comment]
@thecodingaviator Just don't forget to look up each file using the Moderator's tools to validate similar changes do not already exist in an earlier PR.

**Comment by Nitin96Bisht** [comment]
I will start by making a PR for the `Quality Assurance and Testing with Chai` section challenges.

**Comment by moT01** [comment]
@RandellDawson, this PR https://github.com/freeCodeCamp/freeCodeCamp/pull/35020 touches 3 of the mongod files - just a heads up if you didn't already check

**Comment by moT01** [comment]
@Nitin96Bisht, this PR https://github.com/freeCodeCamp/freeCodeCamp/pull/31874 touches one of the chai files - if you haven't already started we can maybe review that quick and you can pull in changes so it doesn't create conflicts later - if you have started, not a big deal.

**Comment by Nitin96Bisht** [comment]
@moT01 Please review this PR #31874 and let me know so that I can start. I have not started yet.

**Comment by moT01** [comment]
@Nitin96Bisht, you can just get started if you want - It might only create a conflict with one file, so it wouldn't be too bad. I looked through those lessons, and the descriptions aren't very good - so I'm thinking that someone needs to go through that sections and give it a makeover.

**Comment by Sumer16** [comment]
Can I help with the Advanced Node and Express section?

**Comment by thecodingaviator** [comment]
@Sumer16 Since no has asked for it yet, go ahead and make a PR

**Comment by thecodingaviator** [comment]
@Sumer16 We are waiting for you PR, any progress?

**Comment by Sumer16** [comment]
Yes, I'll make the PR. Just need to take a look at the final changes.

**Comment by thecodingaviator** [comment]
@Sumer16 Are you still on it or should it be put out there for someone else to pick?

**Comment by thecodingaviator** [comment]
@Sumer16 Since, we've not heard from you in some time now, I'm un-assigning you and making the PR myself
