### ISSUE TITLE
[Beta] freeCodeCamp logo directs to homepage

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#35412]
### Describe the bug
Clicking on freeCodeCamp logo directs to the homepage. 

### To Reproduce
1. Go to any challenge
2. Click on freeCodeCamp logo

### Expected behavior
It should direct me to welcome page.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 32 bit
 - Browser: Chrome
 - Version: Latest stable

**Comment by RandellDawson** [comment]
Are you on production site or beta?

**Comment by vkWeb** [comment]
@RandellDawson Beta: https://www.freecodecamp.rocks/

**Comment by raisedadead** [comment]
Duplicate of #35347.  Please search through open issues before reporting.

**Comment by RandellDawson** [comment]
@vkWeb Do you have an animated gif video showing clicking on the freeCodeCamp logo located in the upper left-hand corner which takes you somewhere other than the main welcome page?  You did not mention which page it took you to instead.
