### ISSUE TITLE
Legacy Certification Settings Section to be implemented

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#35410]
Need to port over the legacy certificate section on Settings page from the production

**Comment by benschac** [comment]
I was poking around this issue a bit @raisedadead.  Curious, you know if there API / reducers still work from what's in production or how I'd mock the legacy data?

**Comment by ahmadabdolsaheb** [comment]
@benschac, the legacy cert's data is available now. We just need to check if the user has completed the challenges and conditionally render the cert button.

let me know if you are interested in pairing for this.

**Comment by Nirajn2311** [comment]
@ahmadabdolsaheb I can pair up for this.

**Comment by benschac** [comment]
I’m around

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ahmadabdolsaheb** [comment]
@benschac, @Nirajn2311 I somehow missed your messages, sorry about that. However, I would really appreciate it if you could check out the functionality and see if it works as intended.

**Comment by k-mayur** [comment]
hi testing comment api post

**Comment by amrithakrishnan** [comment]
Me too

**Comment by amrithakrishnan** [comment]
Test

**Comment by amrithakrishnan** [comment]
Hello mayur :p
