### ISSUE TITLE
[Beta] Reset progress and delete account needs to be implemented

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#35417]
### Describe the bug
@Bouncey, @raisedadead There's no option to reset progress and delete an account on the beta version of freeCodeCamp. 

### Desktop (please complete the following information):**
 - OS: Windows 10 Pro 32 bit
 - Browser: Chrome
 - Version: Latest stable

**Comment by ValeraS** [comment]
duplicate #35242
