### ISSUE TITLE
[Beta] Curriculum map performance is not smooth 

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#35418]
### Describe the bug
The performance of the curriculum map is not smooth on beta. 

To experience this, go to freeCodeCamp's production version curriculum, expand the project Euler section and keep on scrolling. Repeat the same with the beta version. You will notice that the beta version is a bit laggy. 
### Desktop (please complete the following information):
 - OS: Windows 10 Pro 32 bit
 - Browser: Chrome
 - Version: Latest stable

**Comment by ojeytonwilliams** [comment]
This is a bit of a weird one.  Chrome lags when you drag the scrollbar or click to scroll.  Firefox lets you drag smoothly, but delays rendering the links.  It also lags if you click on the scrollbar.  Edge is as smooth as butter when scrolling but takes a rather long time to open the links when you click on them.

It feels like a problem with Gatsby Link, but for the fact that the problem only seems to be on rocks.

I'll take a look, regardless.

**Comment by raisedadead** [comment]
We have deployed a few updates to the version of Gatsby that we use. I could not reproduce. A recorded version if this is still reproducible is welcome.

**Comment by ojeytonwilliams** [comment]
@raisedadead I managed to reproduce it locally with today's commit, but the problem only appears in production - the dev server seems fine.

I'll make some videos in a sec and edit them in here.

**Comment by raisedadead** [comment]
> but the problem only appears in production - the dev server seems fine.

Do you mean `gatsby build dev` and then `gatsby serve` ?

**Comment by ojeytonwilliams** [comment]
Exactly that, yeah.  I also ran the development api server in the background, for what it's worth.  Doing it that way results in very jerky scrolling.
![prod](https://user-images.githubusercontent.com/15801806/53520223-6e086600-3ad5-11e9-8c40-1c10d857e2e3.gif)

In contrast `npm run develop` produces the following:
![dev](https://user-images.githubusercontent.com/15801806/53520309-a314b880-3ad5-11e9-9c0d-81a7aefde730.gif)

There are some error messages in the first approach, which I don't really understand.  Here they are, anyway.
![console](https://user-images.githubusercontent.com/15801806/53520379-d22b2a00-3ad5-11e9-82f6-999d07ce980a.png)

**Comment by raisedadead** [comment]
Thanks for these screen caps.

> There are some error messages in the first approach [...]

The second and the fourth messages can be ignored in development. They are calls to Stripe and Rollbar services.

The third one about `get-session-user` is sort of expected because the gatsby is serving the app from port `9000` and also, it does not have the proxying abilities like in dev mode to hit the backend api.

The first one is a bit cryptic for me. Can you expand see the details?

**Comment by ojeytonwilliams** [comment]
It is a bit cryptic since that's all it says - there's nothing to expand.  However, I don't think it's relevant to this problem since it doesn't appear when I run chrome in incognito mode i.e. when I'm not signed in to fcc.  The jerky scrolling does still appear, though.

**Comment by raisedadead** [comment]
Looks like we will have to dig in existing gatsby issues. /cc @freeCodeCamp/dev-team

**Comment by Bouncey** [comment]
This could be due to some lazy-loading. To keep bundle sizes down, not everything is loaded what you visit a page, as you scroll past a certain point, things that were not 'above the fold' are loaded in. This can be seen by having your network tab open whilst scrolling. The same thing happens when you start to hover over links, the 'abaove-the-fold' js required for that link is lazy-loaded in anticipation of a click.

I think this is hitting an edge case for `(number of links)*(scroll speed)*(network speed/latency)`.

**Comment by ValeraS** [comment]
It's caused by Gatsby prefetching behavior when links become visible. We can disable core prefetching.

**Comment by raisedadead** [comment]
Yeah, I would be happy if we showed:


- List item number on on the list of items for list.
- List item number on on the list of items for list.
- List item number on on the list of items for list.
- List item number on on the list of items for list.
- List item number on on the list of items for list.
- List item number on on the list of items for list.

`... loading more lessons ....`

Or something

**Comment by ojeytonwilliams** [comment]
Am I right in thinking production uses the old learn repo?   If it's using this version of Block https://github.com/freeCodeCamp/learn/blob/cea075362e7deb7eafe2d339b2f578adedb77e84/src/components/Map/components/Block.js
then it still uses Gatsby's Link component, albeit an older version.  Perhaps the newer versions of Link have acquired a bug.

When I get the chance, I'll see if I can reproduce this on fresh Gatsby site, so we at least know whether it's a fcc thing or a Gatsby thing.

**Comment by raisedadead** [comment]
You are right the 'production' at `learn.freecodecamp.org` uses the archived learn repo.

The upcoming version which will replace it available for now at `www.freecodecamp.rocks/learn` and is the current `master` branch of this repo. We have already moved to Gatsby V2 here.

This is under a beta testing phase and will be rolled out to the main `.org` site soon.

Effectively `learn.freecodecamp.org` will become `www.freecodecamp.org/learn`.

You can learn more about it on #34872

**Comment by ojeytonwilliams** [comment]
Ah, thanks, I'd missed that one.
