### ISSUE TITLE
Nested scroll bar on the right; is scrolled down on page load

### ISSUE THREAD

**Issue by tplive** [freeCodeCamp/freeCodeCamp#35456]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
Whenever I progress to a new challenge, the page loads scrolled down about two lines. It's annoying, as the first line or two of the task is hidden, and so I have to scroll up to see it. Even if I maximize the page, the scrollbar to the right never goes away.
If I reload the page, there is no scrollbar.

**To Reproduce**
1. Go to any challenge and complete it
2. Click the Submit button or use Ctrl-Enter to submit.
3. Observe the error.

**Expected behavior**
The page should not scroll down when loading. The scrollbar should go away when not needed.

**Screenshots**
![freecodecamp scroll bug](https://user-images.githubusercontent.com/1882635/53552495-b5294200-3b3b-11e9-9986-390b14b75102.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 and 10, Ubuntu Linux
 - Browser: Firefox
 - Version: 64 (and others)

**Comment by thecodingaviator** [comment]
Check freecodecamp.rocks , I'm having trouble replicating this on that. It might have been fixed

**Comment by Lehmax** [comment]
Does anyone know a temporary fix I could use until freecodecamp.rocks moves to stable? This issue is annoying me more than it should, but I don't know what's causing it.

**Comment by RandellDawson** [comment]
@Lehmax You can use freecodecamp.rocks, but nothing you do on it will be saved when it moves to production.  It has a completely separate database and it strictly for testing.

**Comment by tplive** [comment]
> 
> 
> Check freecodecamp.rocks , I'm having trouble replicating this on that. It might have been fixed

I think you're right!

**Comment by ojeytonwilliams** [comment]
@tplive I've confirmed that this issue is fixed on rocks, so I'm closing this issue.  Thanks for the report!

**Comment by ojeytonwilliams** [comment]
I closed this in error - I should have just applied the label.  Thanks @thecodingaviator!

**Comment by RandellDawson** [comment]
@ojeytonwilliams It is fine to close it and add the `status: resolved/shipping` label.  Either way works.
