### ISSUE TITLE
Sponsor page logo images don't load with ad blocker active

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#35450]
For some reason my ad blocker is blocking our S3 images of these sponsor's from loading.

<img width="1207" alt="sponsors_who_help_freecodecamp_through_financial_and_in-kind_sponsorship___freecodecamp_org" src="https://user-images.githubusercontent.com/985197/53505776-884f3d80-3aef-11e9-943f-9725c219987c.png">

Also note that some of the images are not transparent but rather have white backgrounds - which means they look bad in night mode. Even if they were transparent, their colors would look bad in night mode, so we might want to redesign how this page looks in night mode.

<img width="1207" alt="sponsors_who_help_freecodecamp_through_financial_and_in-kind_sponsorship___freecodecamp_org" src="https://user-images.githubusercontent.com/985197/53505776-884f3d80-3aef-11e9-943f-9725c219987c.png">

**Comment by raisedadead** [comment]
We could make an exception and make this page to be served from our cdn instead. Also it maybe worth updating the url `/sponsors` to something else. 

Of course we would 301 our sponsors page to the new page.

BTW. Does your ad blocker pick up on the original version of the page? `https://sponsors.freecodecamp.org`

**Comment by raisedadead** [comment]
As for the night mode, I think we would have look into their brand guidelines and use the alternative logo the recommend on dark pages.

**Comment by lasjorg** [comment]
It blocks them for me on the main site as well.

As far as I can tell (at least for me) it is caused by the easylist filter, specifically, it looks like the class `.sponsor-logos` is being targeted.

I'm not really that familiar with the filter rules, but this line looks like the potential offender.

`f1today.net,newsroom.co.nz,techwire.net##.sponsor-logos`


Info on filters:
https://adblockplus.org/en/filters

Easylist
https://easylist.to/#easylist

Easylist forum: Report incorrectly removed content
https://forums.lanik.us/viewforum.php?f=64&sid=d0dbb0110d4b33278dc5888c670bf5d2

**Comment by ahmadabdolsaheb** [comment]
Thanks for the valuable information @lasjorg, I removed .sponsor-logo and .sponsor-logos and I got it to work. I will prepare a PR accordingly.

**Comment by ahmadabdolsaheb** [comment]
yes @raisedadead this is how it looks like on 
https://sponsors.freecodecamp.org, the above PR should fix it.
<img width="1437" alt="screen shot 2019-03-01 at 7 31 48 am" src="https://user-images.githubusercontent.com/4591597/53616576-5378de80-3bf4-11e9-8392-36ba2deb5d38.png">

**Comment by ahmadabdolsaheb** [comment]
@QuincyLarson, I completely agree with @raisedadead regarding the brand guidelines. However to save time, how about the following?
<img width="1423" alt="screen shot 2019-03-01 at 8 07 20 am" src="https://user-images.githubusercontent.com/4591597/53617765-b0c35e80-3bf9-11e9-8446-a6f0b94d5505.png">

**Comment by ahmadabdolsaheb** [comment]
We could crop the photos if needed so they all have similar padding.

**Comment by thecodingaviator** [comment]
@ahmadabdolsaheb That looks better than what we have but If we can have everything centered, it'd be a lot better

**Comment by ahmadabdolsaheb** [comment]
@thecodingaviator, you mean centered in the white box? yes, some of the logos come with white space around them. we could crop them and add padding evenly to center them.

@QuincyLarson any thoughts?

**Comment by thecodingaviator** [comment]
No, I was meaing something like this:
![image](https://user-images.githubusercontent.com/34807532/53643179-6d004180-3c59-11e9-9cc3-6efce7b9cb25.png)

All of them arranges in the center in the red boxes. This can easily be done using grid
