### ISSUE TITLE
Stuck grunt serve

### ISSUE THREAD

**Issue by cybot1711** [FreeCodeCamp/FreeCodeCamp#3545]
cybot1711@base_jumps:~/workspace $ grunt serve
Running "serve" task

Running "clean:server" (clean) task

Running "env:all" (env) task

Running "concurrent:server" (concurrent) task

Running "injector:scripts" (injector) task
Missing option `template`, using `dest` as template instead
Injecting js files (13 files)

Running "injector:css" (injector) task
Missing option `template`, using `dest` as template instead
Injecting css files (5 files)

Running "wiredep:target" (wiredep) task
Warning: Cannot find module './lang/clone' Use --force to continue.

Aborted due to warnings.

Execution Time (2015-09-30 15:45:43 UTC)
loading tasks                91ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 49%
serve                         3ms  ▇▇▇ 2%
loading grunt-contrib-clean   7ms  ▇▇▇▇▇▇▇ 4%
clean:server                  6ms  ▇▇▇▇▇▇ 3%
loading grunt-env            19ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 10%
env:all                       2ms  ▇▇ 1%
loading grunt-concurrent      7ms  ▇▇▇▇▇▇▇ 4%
concurrent:server             4ms  ▇▇▇▇ 2%
loading grunt-injector        3ms  ▇▇▇ 2%
injector:scripts             24ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 13%
injector:css                  7ms  ▇▇▇▇▇▇▇ 4%
wiredep:target                9ms  ▇▇▇▇▇▇▇▇ 5%
Total 184ms

**Comment by BerkeleyTrue** [comment]
We don't use grunt with Free Code Camp. If this is related to a generator please open an issue in that projects repository.

Happy Coding
