### ISSUE TITLE
No line breaks in quote machine description

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35459]
I'm not sure what happened to the instructions of [this project](https://www.freecodecamp.rocks/learn/front-end-libraries/front-end-libraries-projects/build-a-random-quote-machine), but there aren't any line breaks between the user stories. None of the other front end projects have this problem, but I didn't check any of the other areas.

<img width="1133" alt="screen shot 2019-02-25 at 8 03 27 pm" src="https://user-images.githubusercontent.com/20648924/53584305-ee1be380-3b48-11e9-8b57-0eb2f3f115f9.png">

**Comment by BA1RY** [comment]
I would like to work on this issue.

**Comment by RandellDawson** [comment]
@BA1RY Before starting to work, let's determine what is causing it and then you can create a PR to fix it.

**Comment by BA1RY** [comment]
Sure @RandellDawson

**Comment by RandellDawson** [comment]
I figured it out.  The problem is in line 17. The invalid `<code>` tag (seen below) was the culprit.
```
<codea</code>
```
Just need to change it to:
```
<code>a</code>
```

**Comment by BA1RY** [comment]
Got it... Will do @RandellDawson

**Comment by BA1RY** [comment]
@RandellDawson Please have a look at it now. Thanks

**Comment by RandellDawson** [comment]
@moT01 Let me know what you think about the PR created.  I added a small tweak also, which you should check locally to see what I am talking about.  If you are ok with the changes, then merge it.

**Comment by BA1RY** [comment]
@moT01 Please have a look at it now. Thank you.
