### ISSUE TITLE
Link in /parallel-computing leads to wrong destination

### ISSUE THREAD

**Issue by juniorbuba** [freeCodeCamp/freeCodeCamp#35461]
**Describe your problem and how to reproduce it:**
Link referenced by "Help our community expand it" in /computer-science/parallel-computing leads to /computer-science/databases/index.md instead of /computer-science/parallel-computing/index.md

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/computer-science/parallel-computing

**Tell us about your browser and operating system:**
* Browser Name: UC browser
* Browser Version: 7.0
* Operating System: windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
Hi @juniorbuba Thanks for reporting this.  This issue has already been resolved but not moved to production.  You can visit are [beta site](https://www.freecodecamp.rocks/guide/computer-science/parallel-computing) which shows this guide article is no longer a stub, so the link no longer appears anyway.  The beta site shows all the current changes available on the master branch, but may not have been shipped to production.  

I am closing this issue for now.  If you have any questions, let me know.
