### ISSUE TITLE
Basic JavaScript: Understanding Uninitialized Variables - Wrong error message 

### ISSUE THREAD

**Issue by cstpk** [freeCodeCamp/freeCodeCamp#35465]
*misinterpretation/ solved

**Comment by RandellDawson** [comment]
The error message is not wrong.  It is just telling you two conditions which must be met for the variable `c`.  In your case, you are not fulfilling the latter.

The key word is `and`.  If I said your named can not be 'Randell' and must start with the letter `N` and your name is `Nataly`, does that mean I said your name is `Randell`?
