### ISSUE TITLE
Remove plug.dj link from Gitter / camperbot / elsewhere

### ISSUE THREAD

**Issue by michael-krebs** [FreeCodeCamp/FreeCodeCamp#3547]
http://plug.dj has sadly shut down for good. Lots of campers are confused as to why the link is not working.

**Comment by abhisekp** [comment]
@michael-krebs I don't see any good in shutting down plug.dj but I've filed an issue for removal in camperbot dcsan/gitterbot#180

**Comment by michael-krebs** [comment]
Thanks @abhisekp , I forgot camperbot had its own repo. I will close this one.
