### ISSUE TITLE
Basic Algorithm Scripting: Slice and Splice - valid solution does not pass tests

### ISSUE THREAD

**Issue by TimAndreJacobsen** [freeCodeCamp/freeCodeCamp#35473]
### Can't pass Basic Algorithm Scripting: Slice and Splice with valid solution.
Tests do not pass. Console logging and typeof() shows both answers to produce the same result, but only the hinted solution will work.

```
function frankenSplice(arr1, arr2, n) {
  let output = arr2.slice();
  output.splice(n, 0, [...arr1]);
  console.log((output));
  return output;
}
```

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-algorithm-scripting/slice-and-splice

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 72.0.3626.119 (Official Build) (64-bit)
* Operating System: Windows 10 64bit

### Code solution that gives the correct answer, but does not pass tests.
![slice-and-splice-not-valid](https://user-images.githubusercontent.com/35067641/53631225-5b477b80-3c12-11e9-9cc5-75c1ee46e8cc.png)

### Solution from hint section passes tests and console.log(return value) is shown here
![slice-and-splice-hint-solution](https://user-images.githubusercontent.com/35067641/53631160-33581800-3c12-11e9-997d-94a961e74f5a.png)

As seen in the console window in the bottom right corner, both functions provide the same output when logged. Expected behaviour would be for both solutions to pass.

**Comment by ValeraS** [comment]
Hi @TimAndreJacobsen 

Thanks for reporting this issue.

Please use the [Chat Rooms](https://www.freecodecamp.org/forum/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](https://www.freecodecamp.org/forum) for help with a specific challenge and any coding assistance.

**IMPORTANT:**
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!

It's a bug in your code in line 3 should be:
```js
output.splice(n, 0, ...arr1);
```
