### ISSUE TITLE
Next Release QA Checklist

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#35475]
The time is approaching for a final QA. Below is a list of things that need to be checked for both new and existing users. To test as an existing user, we would require the permission of a user to essentially copy/paste their production account in to the `.rocks` database. It should remain that only that user will have access to the clone of their account on `.rocks`

#### Scenarios ready for test
- Sign up for a new account
- Log out of your account
- Sign in to an existing account
- Change your account details
  - name 👍 @moT01 
  - username 👍 @moT01 
  - location 👍 @moT01 
  - about 👍 @moT01 
  - email
  - theme 👍 @moT01 
  - privacy settings 👍 @moT01 
  - academic honesty 👍 @moT01 
- complete a coding challenge
  - frontend 👍 @moT01 
  - backend 👍 @moT01 
  - project 👍 @moT01 
- claim a certification 👍 @moT01 
- interact with the curriculum UI 👍 @moT01 
  - buttons 👍 @moT01 
    - run tests 👍 @moT01 
      - with good code 👍 @moT01 
      - with bad code 👍 @moT01 
      - bonus points for breaking code
    - reset code 👍 @moT01 
    - get a hint 👎 @moT01 
    - watch a video 👍 @moT01 
    - ask for help (should point to the `.rocks` forum)
  - editor
  - console
  - preview
~~- navigate the guide~~

#### Scenarios with known issues (can still be tested, PR's are raised or in progress)
- Search
  - links may be broken
  - styling is funky
  - expand/collapse of search suggestions isn't intuative

**Comment by Sumer16** [comment]
Can I help you in completing all the QA Testing?

**Comment by moT01** [comment]
Are we still wanting to test all this stuff @Bouncey? My account was recently added to the beta site db, and I can test a number of these.

**Comment by vkWeb** [comment]
@raisedadead Do you need any help QA'ing the platform? `.rocks` is down, I'll run it locally and QA if you say.

**Comment by QuincyLarson** [comment]
Note: @bouncey took a job at a local Irish tech company, and probably won't be contributing for a while. But his notes here are still helpful. We should build a comprehensive test plan that several of us can go through before we ship Next to production.

**Comment by raisedadead** [comment]
**Note:** 
This is a document only issue. Please open fresh issues for discussions and reporting bugs. You can label them as **[`release: next/beta`](https://github.com/freeCodeCamp/freeCodeCamp/labels/release%3A%20next%2Fbeta)** for triage.

**Comment by raisedadead** [comment]
I am going to close this. This biases the QA to certain elements and defeats the purpose of going thru all things
