### ISSUE TITLE
Navigation tree items disappear

### ISSUE THREAD

**Issue by WofWca** [freeCodeCamp/freeCodeCamp#35489]
**Describe your problem and how to reproduce it:**
1. In the main tree list, open an item containing other trees (nested) (e.g. "Certifications").
2. Open a level 2 item (e.g. "Certifications"->"APIs and Microservices")
3. Open a level 2 item going after the item that you unfolded in the second step. It will disappear.

**Add a Link to the page with the problem:**

https://guide.freecodecamp.org

**Tell us about your browser and operating system:**
* Browser Name: Chrome; Firefox
* Browser Version: 72.0.3626.119; 65.0.2 (64-bit)
* Operating System: Win 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

1.
![image](https://user-images.githubusercontent.com/39462442/53681246-d186d380-3d21-11e9-98dc-c5e5efcf5c1b.png)
2.
![image](https://user-images.githubusercontent.com/39462442/53681258-e95e5780-3d21-11e9-9062-5951d9f83693.png)
3.
![image](https://user-images.githubusercontent.com/39462442/53681270-05fa8f80-3d22-11e9-9da7-0d46d2fe868a.png)

**Comment by WofWca** [comment]
Related: #34962

**Comment by thecodingaviator** [comment]
This has been fixed in the repo and is awaiting shipment to production along with the next release. You can find the fixed version at [freecodecamp.rocks](https://freecodecamp.rocks/learn).

I'm closing this issue, if you think that this has not been fixed, add further clarification and reopen the issue.

**Comment by WofWca** [comment]
Sorry about that.
