### ISSUE TITLE
Remove quotes from challenges where not needed

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#35481]
In some curriculum articles, some of the code-bits highlighted by the `<code></code>` are enclosed by a pair of quotes which are not necessary.

Since the `<code>` tags already highlight code, there is no need for the quotes to be there.

That is, instead of:
```markdown
"<code>stuff</code>"
```
It should be:
```markdown
<code>stuff</code>
```

One example can be found in [this file](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-do...while-loops.english.md) 

PRs:

[x] English
[x] Chinese - No instances found
[] Russian
[x] Arabic
[] Portuguese
[x] Spanish

**Comment by RandellDawson** [comment]
Do we have a list of such challenges?

**Comment by thecodingaviator** [comment]
I do not have a list of these challenges a.t.m.

In the P.R. from where this originated, @cmccormack has said something about there being other files where we had this, he might have a lead on it, otherwise a repo wide search for `"<code>` can be run

**Comment by RandellDawson** [comment]
OK.

**Comment by RandellDawson** [comment]
@thecodingaviator If you do a quick search of the repo to see how many files might be affected by this, then I will query the open PRs to check all existing open PRs which might have such changes.

**Comment by Nitin96Bisht** [comment]
@thecodingaviator @RandellDawson I would like to start from `/curriculum/challenges/english`. Kindly let me know May I start now to avoid file merge conflict.

**Comment by cmccormack** [comment]
@Nitin96Bisht we can take care of the merge conflicts if you want to submit the PR.  Make sure you're working from the latest commit of the freecodecamp master branch.

Please try to limit the changes in this PR to only removing the quotes so it doesn't make conflict resolution more difficult.

Thanks!

**Comment by Manish-Giri** [comment]
I think it's better to allow a first-time contributor to work on the issue.

@Nitin96Bisht Please feel free to look through the other `help wanted` issues. There are many of them we could use your help on! 
In case this one is still not picked up in a few days, you can then work on this.

**Comment by Nitin96Bisht** [comment]
@Manish-Giri I was already working on this. I will look for `help wanted` issues also. 👍

**Comment by Sumer16** [comment]
Is this issue still on? If yes, can I help you?

**Comment by RandellDawson** [comment]
@Sumer16 This one already has an open PR (see above #35493).

**Comment by Sumer16** [comment]
Okay No problem!! @RandellDawson

**Comment by randjanas** [comment]
Is this issue closed ? I am a first time contributor and would like to work on it.

**Comment by thecodingaviator** [comment]
@randjanas Not yet, only the PR for English language has been merged. Check with @Nitin96Bisht for what languages he is making a PR for

**Comment by Nitin96Bisht** [comment]
@randjanas You can start with any of the language except English language. @thecodingaviator I am not working as of now for any other language. It would be great if we allow first timer to work on this.

**Comment by nellybaz** [comment]
hello, I would like to do this as a first timer. 
Where should I start?

**Comment by thecodingaviator** [comment]
@nellybaz check with @randjanas for what languages they are working on, you can pick up the other languages and use the search and replace functionality of your code editor to make changes as discussed above

**Comment by LifeVirus** [comment]
Hi, I'm new to freecodecamp but I'm wondering if you guys still need help on this? If so, what languages should I work on? Thanks!

**Comment by ageebc137** [comment]
Hello, I'd like to help with this issue as well. Which language folders are available? @nellybaz @randjanas Thanks!

**Comment by Manish-Giri** [comment]
@LifeVirus @ageebc137 Thanks for helping out with this! AFAIK, so far only @roshni-b [has claimed the Russian files](https://github.com/freeCodeCamp/freeCodeCamp/pull/35493#issuecomment-479366913). 

Since we haven't heard from @randjanas and @nellybaz yet, you both are welcome to pick one language each from the available four (Arabic, Chinese, Portuguese and Spanish), and start working on the corresponding files. 

Considering that @randjanas and @nellybaz asked first, we'll wait for them to claim the other two language versions if they're still interested. In case they (or @roshni-b) aren't, you can then continue with these versions too (if you prefer).

**Comment by ageebc137** [comment]
Thanks @Manish-Giri. I'll volunteer to do the Spanish folder.

**Comment by LifeVirus** [comment]
Thanks @Manish-Giri! I'll take the Portuguese folder!

**Comment by LifeVirus** [comment]
Hi, @Manish-Giri, after taking a cursory look in /curriculum/challenges/portuguese, and searching for
 "<code> , </code>", and &quot, I haven't found any examples of "<code>stuff</code>", and the only places where "<code> or </code>" pop up are in Tests, in assert fields, where it's unrelated I think. Am I missing something? Sorry for the bother!

**Comment by ageebc137** [comment]
Hi @LifeVirus. Try searching "</code> &quot;", making sure there is a space in between. I noticed there were a lot of false positives when I did my search. When I searched, I was able to find "&quot; <code>...</code> &quot;" in the Portuguese folder at declare-the-doctype-of-an-html-document.portuguese.md.

**Comment by LifeVirus** [comment]
Hi @ageebc137, I looked in declare-the-doctype-of-an-html-document.portuguese.md, and I didn't see any examples of "\<code> \</code>". I thought that was what we were looking for? I am not sure what "" ... "" means.

**Comment by ageebc137** [comment]
Hi @LifeVirus. Try searching `</code> \&quot;\` making sure there is a space in between. I noticed there were a lot of false positives when I did my search. When I searched, I was able to find `\&quot; <code>...</code> \&quot;` in the Portuguese folder at declare-the-doctype-of-an-html-document.portuguese.md.

**Comment by ageebc137** [comment]
@LiveVirus. Sorry for the confusion. I forgot to add template literals. What I meant was `&quot; <code>…</code> &quot;`. I saw that example located within the section tag element in the same file I cited.

**Comment by LifeVirus** [comment]
@ageebc137 Thank you! I removed all the instances of `&quot; <code>…</code> &quot;`, and I think that that may be all of the instances in the Portuguese files. Would it be possible for me to work on the other untaken languages as well, or should I wait on @randjanas and @nellybaz to see if they are picking up Arabic/Chinese?

**Comment by thecodingaviator** [comment]
Guys, try searching for `"<code>` and `</code>"` separately

**Comment by ageebc137** [comment]
I made sure to search `"<code>`, `</code>"`, `" <code>`, `</code> "`, `&quot; <code>`, `&quot;<code>`, `</code>&quot;`, and `</code> &quot;`, all separately.

**Comment by LifeVirus** [comment]
Do we still need help for Arabic/Chinese? @Manish-Giri @thecodingaviator? I wouldn't mind picking up those as well!

**Comment by Manish-Giri** [comment]
@LifeVirus Sure! Go ahead!

**Comment by ageebc137** [comment]
Hi @LifeVirus, are you doing both Arabic/Chinese? Do you mind if I do one of the folders?

**Comment by LifeVirus** [comment]
@ageebc137 Go for it! I'll take Chinese and you can have Arabic?

**Comment by ageebc137** [comment]
Thanks @LifeVirus. I'll move forward with the Arabic folder.

**Comment by ConiWright** [comment]
Hey, Would like to give a hand as its my first contribution. Where should i start? is the quote issue resolved or are there more languages where help is needed? 
Thanks in advance

**Comment by RandellDawson** [comment]
@ConiWright - It appears you can choose between Spanish and Portuguese.  If you have not contributed before, I suggest starting with [How to Setup Free Code Camp locally](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md#set-up-freecodecamp-locally) and [How to Work on Coding Challenges](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-coding-challenges.md).  If you have any questions, then ask in our [Contributors Room on Gitter](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by LifeVirus** [comment]
@ConiWright Actually I think that all files currently are accounted for. Me and @ageebc137 have created PR's for Portuguese/Spanish, and now we're working on Chinese/Arabic. I think Russian and English were already taken before us.

**Comment by LifeVirus** [comment]
After looking for `"<code>`, `</code>"`, `" <code>`, `</code> "`,  `&quot; <code>`, `</code> &quot;`, `&quot;<code>`, and `</code>&quot;`, I couldn't find any instances of any of these in the Chinese folder. Somebody else can verify if they wish, but as far as I've searched, I can't find anything in the Chinese folder specifically, even though they exist in my local (non-fixed) Arabic, Portuguese, Spanish, etc. folders, so I don't think a PR needs to be made for the Chinese folder specifically.

**Comment by UNnamed66** [comment]
Hi, this will be my first contribution. I'm wondering if Chinese is still up for grab. If not, which one can I choose? Thanks.

**Comment by RandellDawson** [comment]
@UNnamed66 It appears @LifeVirus  is already working on the Chinese version.

**Comment by UNnamed66** [comment]
> @UNnamed66 It appears @LifeVirus is already working on the Chinese version.

Alright, it seems like every one of them is taken. Let me know if any one of them needs help in the future. Thanks.

**Comment by LifeVirus** [comment]
@UNnamed66 @RandellDawson, I've taken a look at the Chinese version, and it seems like the quotes are already removed. I won't be submitting a PR for it, so if you want to take a look and find something that I missed then feel free to make the PR yourself!

**Comment by thecodingaviator** [comment]
Had this been fixed in the Portuguese and Russian folders? Someone needs to have a look

**Comment by RandellDawson** [comment]
@thecodingaviator Even if those languages were not translated, it is fine.  We are no longer accepting translations for the current curriculum.  We do not need any further PRs for the the non-English curriculum files.

**Comment by thecodingaviator** [comment]
I see. Alright
