### ISSUE TITLE
Stub links point to the freeCodeCamp/guide repo

### ISSUE THREAD

**Issue by WofWca** [freeCodeCamp/freeCodeCamp#35490]
**Describe your problem and how to reproduce it:**

Go to a stub page e.g. [this](https://guide.freecodecamp.org/certifications/information-security-and-quality-assurance). The "Help our community expand it." link points to a currently archived repo whereas it should be pointing to `freeCodeCamp/freeCodeCamp/guide`. Same with the "This quick style guide will help ensure your pull request gets accepted." link.

**Add a Link to the page with the problem:**

https://guide.freecodecamp.org/certifications/apis-and-microservices
https://guide.freecodecamp.org/certifications/apis-and-microservices/apis-and-microservices-projects

etc

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by moT01** [comment]
I think the "Help our community expand it." links should take you to https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-guide-articles.md - and the second link should take you to https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md. For some reason the "help our community expand it" link in the article posted takes you to the "mathematics/quadratic-equations" file - I thought that was kinda funny.

**Comment by moT01** [comment]
So I will replace all the stubs to look like this...?
```
This is a stub. [Help our community expand it.](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-guide-articles.md)

[This quick style guide will help ensure your pull request gets accepted.](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md)

<!-- The article goes here, in GitHub-flavored Markdown. Feel free to add YouTube videos, images, and CodePen/JSBin embeds  -->

#### More Information:
<!-- Please add any articles you think might be helpful to read before writing the article -->
```
Do we want to keep the more information heading in the stubs? Is there anything else we want to add to the stubs if I am going through them? I could make the first line look like this instead...
```
This is a stub. [Help our community expand it.](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-guide-articles.md) by editing [this file](link to actual file here)
```

**Comment by WofWca** [comment]
I think a link to the actual file here should be available on the page.

**Comment by WofWca** [comment]
I think including a link to the actual file is a matter of a different issue.

**Comment by thecodingaviator** [comment]
@moT01 The second version looks better. I don't personally think there is any need for the More Information section

**Comment by RandellDawson** [comment]
@moT01 Be careful changing the stub content.  @raisedadead I was thinking there was something in the Guide logic which does something special when it encounters stub content in an article.  Is it ok to just change the stubs to whatever we think is best?

Also, it would be nice if the system would just automatically post something in a Guide article which does not have any content.  Also, I believe I discussed with @raisedadead that we should probably have a footer attached to every Guide article which automatically creates the links to the master branch file has the link to the "How to Work on Guide Articles" doc. This way, no one has to manually update this information.

**Comment by moT01** [comment]
Be careful for what? I would just be changing the stubs to something almost identical to what is already there - just with proper links and maybe a few more words. 

Perhaps there is a way for the guide to automatically fill in something when it finds a stub or no content or whatever... I would bet that there is a way, in fact - maybe that's the way to go.

The beta guide already has the new footer added... what would a second footer look like? I actually like that idea, some default content at the bottom of every article that does what you say... links that tell how to contribute/change the article and such (kinda like how a stub is now, just on every article) - but more like part of the content than a standard footer maybe?

I will hold off on this until we hear some more.

**Comment by RandellDawson** [comment]
@moT01 I could be wrong, but I believe the way the Guide logic works (or used to) was if it found specific stub text, then it would not render the content of the article as a precaution.  Again, I will let @raisedadead correct me on my assumption.  If it is looking for specific stub text and we change it, then something may not work as intended.

**Comment by raisedadead** [comment]
We just need a simple stub component, which can be rendered on stub articles, that will lead to the corresponding guide article on GitHub.

Here is an example:

https://www.gatsbyjs.org/docs/preparing-your-environment/

![image](https://user-images.githubusercontent.com/1884376/53686345-b5982780-3d4b-11e9-80f0-d0aaf8d6f555.png)

**Comment by raisedadead** [comment]
Hi @moT01 if you are interested in working on the stub component, please leave your assignment as it is, else I recommend you revert the assignment and help wanted labels.

**Comment by genevieveloreal** [comment]
It would be great to resolve this issue. Currently it is very confusing trying to work out how to contribute to the help/hint sections of challenges.

**Comment by moT01** [comment]
I'm confused as to what we actually want here. Is this component going to replace the current stubs? If not, then it doesn't really fix the issue of the bad links. And do we only want the component on stub articles, or do we want it on all the articles. I personally, like the idea of having something at the bottom of all the articles with the links on how to change the article.

I think you are right about being careful @RandellDawson - I'm not sure, but I think it's for rendering the navigation (gray's out stubs and probably more)- but I think changing stub text would break that. Thanks for the heads up, I would have missed that for sure.

**Comment by RandellDawson** [comment]
> And do we only want the component on stub articles, or do we want it on all the articles. I personally, like the idea of having something at the bottom of all the articles with the links on how to change the article.

I am hoping it is on all articles.  However, for articles which have no info yet, then there probably needs to be an automatically place message, so we are not trying to maintain those links ourselves.

**Comment by moT01** [comment]
Well, this is what I have so far...
<img width="1271" alt="screen shot 2019-03-03 at 3 24 35 pm" src="https://user-images.githubusercontent.com/20648924/53702179-a8218280-3dc9-11e9-83d1-9a161136b692.png">
Everything below the `<hr>` is part of the component. It is rendered on **every** article. Not sure if this is what we want but it maybe gives us something to start with. It still doesn't address the issue of the bad links in the stubs.

**Comment by RandellDawson** [comment]
Good start!  Maybe `Edit this file on GitHub` should be the first bullet.

**Comment by ryantimjohn** [comment]
I updated all the links to the old version of the guide here:
https://github.com/freeCodeCamp/freeCodeCamp/pull/35600/

**Comment by moT01** [comment]
The PR to add the footer to the guide was merged. But it doesn't exactly fix the issue here...
current beta article with a stub... https://www.freecodecamp.rocks/guide/certifications/apis-and-microservices/

I'm wondering if we should change the stubs... both links in the stub are no longer active, and are now basically repeated in the footer.

Possibly change the stubs to something like: `This is a stub. Help our community expand it by following the links below`?

**Comment by RandellDawson** [comment]
@raisedadead What should we do about this issue now that the guide is no longer in the repo?

**Comment by raisedadead** [comment]
> now that the guide is no longer in the repo?

We should revalute all issues on their merit. The guide will be available on the forum as a wiki. All issues still apply if relevant.

**Comment by moT01** [comment]
Will the entire guide be moved over to the forum? As of right now it looks like just the guides for the curriculum were moved over, any [ones with stubs](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-problem-237-tours-on-a-4-x-n-playing-board/301882) look like this: `This is a stub. Help the community by replying below with your hints and solutions. We can use those to create a guide article for this.` - So unless the rest of the articles are added with different stubs, this shouldn't be an issue.

**Comment by raisedadead** [comment]
Yes, the guide articles now backed up here: https://github.com/freeCodeCamp/guide/tree/archive-articles-2019, will be made available in the forum.

**Comment by moT01** [comment]
Do you know if the stubs will be changed to look like the one I linked above? I assume they will be.

**Comment by raisedadead** [comment]
@RandellDawson is the best person to confirm the format. But I am guessing we would not add articles which are stubs. We want to limit the clutter in there.

**Comment by RandellDawson** [comment]
I can skip the stubs during the porting process if that is fine with everyone.  Then there would not be any stub topics (with the exception of the challenge hints/solutions topics).

**Comment by moT01** [comment]
This can probably be closed then since the stubs won't contain any links.

**Comment by RandellDawson** [comment]
I think we should keep it open, until I have successfully ported the other guide articles everything over to the forum.  Once it is complete, then I will close it.
