### ISSUE TITLE
Clearing cookies or application data for domain does not let me sign in

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#35495]
1. Sign in on the beta site. 
2. Go to Browser DevTools (Chrome) --> Application Tab --> Clear Storage --> Clear Site Data
3. Try Sign in again.

Looks like our code is setting/checking some cookie set to some other domain/subdomain.

**Comment by Bouncey** [comment]
Can be reproduced locally by deleting the `jwt_access_token` from cookies
