### ISSUE TITLE
Small typo I think

### ISSUE THREAD

**Issue by codeguy2015** [FreeCodeCamp/FreeCodeCamp#3549]
On the left it says I should use /\\d+/gi

 However if I do that throws an error... 

and the correct expression should be:

var expression = /\d+/gi;

 notice that theres an extra \ in the suggested code. Once I took that out, the code worked. Maybe its a typo?

Thanks!

Waypoint: Find Numbers with Regular Expressions
We can use special selectors in Regular Expressions to select a particular type of value.

One such selector is the digit selector \d which is used to grab the numbers in a string.

It is used like this: /\d/g.

For numbers this is often written as /\d+/g, where the + following the digit selector allows this regular expression to match multi-digit numbers.

Use the \d selector to select the number of numbers in the string, allowing for the possibility of multi-digit numbers.

**Comment by tva10** [comment]
If you look at test case and find there an extra `\` in suggested code, then there is not a typo. There is an special escape character in string (which `assert()` will should show you). This special character need to show simple `\`. It is looks like `\n` for new line or `\t` for tabulation.

[!msdn example](https://msdn.microsoft.com/en-us/library/2yfce773(v=vs.94).aspx)
```
assert(editor.getValue().match(/\/\\d\+\//gi), 
           'message: You should be using the following expression /\\d+/gi to find the numbers in the testString.');
message: You should be using the following expression /\d+/gi to find the numbers in the testString.
```

**Comment by bugron** [comment]
Closing this issue. I think @tva10 answered fully, thanks.
