### ISSUE TITLE
Pig Latin: Intermediate solution #2 is incorrect

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/freeCodeCamp#35503]
**Describe your problem and how to reproduce it:**

For the **Pig Latin** challenge, Intermediate Code Solution #2 does not handle cases where the word does not contain a vowel. 

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/pig-latin/

This is the code in question - 
```
function translatePigLatin(str) {
   function check(obj) {
      return ['a','i','u','e','o'].indexOf(str.charAt(obj)) == -1 ? check(obj + 1) : obj;
  }

  return str.substr(check(0)).concat((check(0) === 0 ? 'w' : str.substr(0, check(0))) + 'ay');
}
```
The problem is that the algorithm in `check()` keeps looking recursively for a vowel in `str`. When there is no vowel in the word, this bit - ` ['a','i','u','e','o'].indexOf(str.charAt(obj))` - always results in `-1`, leading to repeated calls to `check(obj + 1)`, untill the call stack size is exceeded.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![pl](https://user-images.githubusercontent.com/11348778/53706644-4c6eed80-3df9-11e9-8773-b96205106ddc.png)

Test it here  - https://repl.it/repls/NoisyRoundedCustomer

This can be fixed with a check to determine if the word doesn't contain a vowel, but I think we should remove this solution entirely. It is convoluted, and requires a lot of almost duplicate function calls like ` str.substr(check(0))` and `str.substr(0, check(0)))`.

I'll make a PR after we come to a decision.

**Comment by RandellDawson** [comment]
I just looked at the history of the file and this has been a solution for a long while.  Surprised no one found this before.  I say remove it totally.

**Comment by RandellDawson** [comment]
Can we use another PR's solution for intermediate?  Did we close one recently that could be used?

**Comment by Manish-Giri** [comment]
There is already another intermediate solution (intermediate code solution #1) that was recently added to the guide. The one that was recently closed has similar logic to both the first intermediate solution and the advanced solution.

**Comment by RandellDawson** [comment]
OK.
