### ISSUE TITLE
Remove stub text from filled guide articles

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35505]
Some of the guide articles were filled in, but the user forgot to remove the stub text. Resulting in stubs that don't need to be there. And incorrect style in the navigation links. In the photo, the link on the left to the article shown is gray and says 'stub' - because the stub text is still at the bottom of the article.
<img width="1212" alt="screen shot 2019-03-03 at 11 29 10 pm" src="https://user-images.githubusercontent.com/20648924/53712450-84336080-3e0c-11e9-86a5-65745cfd523d.png">

**Comment by rmfranciacastillo** [comment]
I'll be working on removing the stub tag from MongoDB and Mongoose.

**Comment by moT01** [comment]
Thanks @rmfranciacastillo, but this issue has been fixed and there should be no more articles where the stub text needs to be removed.

**Comment by rmfranciacastillo** [comment]
@moT01 No worries. :)
