### ISSUE TITLE
Footer on /news page is difficult to navigate to due to semi-infinite scrolling

### ISSUE THREAD

**Issue by JamieVaughn** [freeCodeCamp/freeCodeCamp#35515]
When on www.freecodecamp.org/news and trying to scroll to the footer, the document height repeatedly increases due to an infinite scroll effect causing new content to load which pushes the footer out of the viewport. This makes navigating to the footer very difficult and constitutes a UX bug, IMO. A narrow, fixed footer or moving the footer content to a fixed side-panel are possible solutions.

To reproduce the bug try scrolling to bottom here: https://www.freecodecamp.org/news

* Browser Name: Chrome
* Browser Version: 72.0 & 71.0
* Operating System: Linux Mint & ChromeOS

**Comment by JamieVaughn** [comment]
I'd be interested in submitting the PR for this if it is deemed an issue in need of changing.

**Comment by raisedadead** [comment]
We are currently, in the middle of shipping the learn platform. The news app is a dedicated Ghost instance currently using one of their default themes. We do plan to overhaul this in future.

So, the theme may be changed to something that we choose to vote internally.

Thanks a lot for your interest, and reporting this.

As of now, this is an intended behaviour, and may change in future.
