### ISSUE TITLE
SQL Guide files invalid

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#35518]
The file [SQL Guide - ALTER TABLE](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-alter-table-statement/index.md) is totally messed up since the user removed the images, a PR #30349 made changes to it which makes it better, but not fixes it.

We want the whole file to have statements like that we have now for `Remove a column:`

Additionally, we want the PR to be formatted properly, such as each of these:
- ![image](https://user-images.githubusercontent.com/34807532/53828951-0a82aa80-3fa5-11e9-8060-3c6aa0bd08a4.png)
- ![image](https://user-images.githubusercontent.com/34807532/53829012-32720e00-3fa5-11e9-9572-a9737a741380.png)

to be put in a list form

And this warning note:
![image](https://user-images.githubusercontent.com/34807532/53829037-4289ed80-3fa5-11e9-9dab-34ac52cc652a.png)
to be moved to a new line

# EDIT:
On a closer look, this problem is in many SQL challenges which are there. Examples:

- [1](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-create-table/index.md)
- [2](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-server-convert-function/index.md)
In (2), the images should be removed, we do not want to host them on GitHub

We can either have just the text command or text tables like in: [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-where-clause/index.md)

**Comment by ritute** [comment]
Sent an email to the author to see if we can have the images recovered and then we can create text-based tables off of them (so that we don't have to start from scratch).

**Comment by ritute** [comment]
Received the images. Updating these guides.

**Comment by thecodingaviator** [comment]
@raisedadead I’d like some input from you on if we should go ahead with this using images or text tables. Text tables should be fine. Right?

**Comment by raisedadead** [comment]
We should never use images unless there is no other way out. So its always text.

**Comment by ritute** [comment]
@raisedadead What's the reason for not using images? This feels pretty limiting for producing good content on such guides.

The set of images I got don't include everything, unfortunately, and some of them are not just tables (e.g. there's one showing the sql browser).

**Comment by raisedadead** [comment]
There are so many compelling reasons to avoid images when you can:

1. [Images hurt a11y](https://www.w3.org/WAI/tutorials/images/textual/). You can add alt text 'Image explaining ... your reason here', but that's about it.
2. They are difficult to maintain and easily get outdated. Imagine updating text regularly.
3. They hurt performance. Text is fast to deliver over network vs images.

There are probably lot more reasons, but you can imagine.

**Comment by raisedadead** [comment]
> This feels pretty limiting for producing good content on such guides.

I understand in the current state of guide, as a contributor you have some limited controls on how you can style the content.

That said, there is some feature dev happening https://github.com/freeCodeCamp/freeCodeCamp/pull/35278 which should allow more interactive content in the guide soon.

**Comment by thecodingaviator** [comment]
@ritute Could you please also go through all other SQL guide files to check if any other files have missing content?

**Comment by moT01** [comment]
The [style guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#images) should probably be updated to say not use images whenever possible. It mentions users can add videos and other things, as well - so people aren't on the same page about what can be added for these types of things.

**Comment by ritute** [comment]
This is what I received in case anyone else wants to pick this up (I won't be able to get to this in the next week or two; that might be okay though depending on priority?):
[freeCC-SQL images.zip](https://github.com/freeCodeCamp/freeCodeCamp/files/2975332/freeCC-SQL.images.zip)

Regarding use of images - I agree that in the case of tables such as in these SQL guides, where it's comprised of just text, images shouldn't be used. However, I'm not sure I agree with recommending people to avoid images for these guides; perhaps better is a recommendation to avoid images when it's just text (such as code snippets, tables), and then elsewhere to opt for less over more, use judgement on whether the image brings real value. Performance concerns could be alleviated with use of a CDN.

**Comment by umasankar1999** [comment]
Hello , Can I work on this issue ??

**Comment by umasankar1999** [comment]
> The file [SQL Guide - ALTER TABLE](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-alter-table-statement/index.md) is totally messed up since the user removed the images, a PR #30349 made changes to it which makes it better, but not fixes it.
> 
> We want the whole file to have statements like that we have now for `Remove a column:`
> 
> Additionally, we want the PR to be formatted properly, such as each of these:
> 
> * ![image](https://user-images.githubusercontent.com/34807532/53828951-0a82aa80-3fa5-11e9-8060-3c6aa0bd08a4.png)
> * ![image](https://user-images.githubusercontent.com/34807532/53829012-32720e00-3fa5-11e9-9572-a9737a741380.png)
> 
> to be put in a list form
> 
> And this warning note:
> ![image](https://user-images.githubusercontent.com/34807532/53829037-4289ed80-3fa5-11e9-9dab-34ac52cc652a.png)
> to be moved to a new line
> 
> # EDIT:
> On a closer look, this problem is in many SQL challenges which are there. Examples:
> 
> * [1](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-create-table/index.md)
> * [2](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-server-convert-function/index.md)
>   In (2), the images should be removed, we do not want to host them on GitHub
> 
> We can either have just the text command or text tables like in: [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/sql/sql-where-clause/index.md)

@thecodingaviator  ,
Hi, I am currently working on this issue.
The commands in sql - guide alter table statement are Mysql commands . 
Should I have to describe those in SQL server , Orcale etc or Mysql is enough .

**Comment by thecodingaviator** [comment]
@umassnkar1999 check with @ritute if they’re not working on it now

**Comment by umasankar1999** [comment]
@thecodingaviator  Okay.
I have one doubt .
Is Commands in sql guide are Mysql based or SQL server based ?

**Comment by thecodingaviator** [comment]
@umasankar1999 I'm not sure about that. Have a look at the files and figure it out

**Comment by umasankar1999** [comment]
@thecodingaviator , I checked the other files and got to know that all commands are Mysql based.
So, I changed the all images into text tables , text commands and added a Pull request.
Once check it and review.

**Comment by thecodingaviator** [comment]
Thanks @umasankar1999 , your PR would be reviewed as per the normal established prodcedufe

**Comment by umasankar1999** [comment]
Thanks @thecodingaviator .
