### ISSUE TITLE
ES6: destructuring with reassignment was used (Use Destructuring Assignment to Assign Variables from Objects )

### ISSUE THREAD

**Issue by akramSahbi** [freeCodeCamp/freeCodeCamp#35520]
**Describe your problem and how to reproduce it:**
In the ES6: destructing assignment to assign variables from object lesson, i make the correct answer but it is not recognized, it shows the test message warning 'destructing with reassignment was used. 
here is the code snippet:
`const AVG_TEMPERATURES = {
  today: 77.5,
  tomorrow: 79
};

function getTempOfTmrw(avgTemperatures) {
  "use strict";
  // change code below this line
  const {tomorrow:tempOfTomorrow} = AVG_TEMPERATURES; // change this line
  // change code above this line
  return tempOfTomorrow;
}

console.log(getTempOfTmrw(AVG_TEMPERATURES)); // should be 79;
;`

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-objects/

**Tell us about your browser and operating system:**
* Browser Name: google chrome
* Browser Version: 72.0.3626.119 (Official Build) (64-bit)
* Operating System: windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![es6 warning 1](https://user-images.githubusercontent.com/9323215/53837011-ca65fc80-3f91-11e9-97a4-6b5283dc87f6.png)

**Comment by RandellDawson** [comment]
You should use the forum first to post your code and ask questions first.  The challenge expects you not to use the global variable, but instead use the value passed by the call to the function.
