### ISSUE TITLE
The advice in 'How to work on coding challenges' could use fleshing out

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#35529]
This is a followup to a discussion I had with @RandellDawson in #35526 

As it stands, the guides for contributing to the coding challenges, their solution section in particular, are a little sparse.  For example, [How to work on coding challenges](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-coding-challenges.md) only shows a template with no solution.  [The Style guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-curriculum-challenges.md), unsurprisingly, covers formatting, but not content.  

It might be worth clarifying that what has to go into a solution.  I managed to convince myself that all a solution needed to do was pass the tests, since that would allow the tests to be as fast as possible.  @RandellDawson pointed out that it's standard practice to base the solution on the full seed code and only make the modifications required to pass the tests.  i.e. that the solution should be one that a user is likely to come up with.  Could the documentation be changed to hammer this home?

**Comment by raisedadead** [comment]
I think the best approach is to consolidate the 'how to work on coding challenges' and 'style guide' into one, merging the later into the former.

We could do the same with the guide's 'how to work on guide articles' and 'style guide'

**Comment by candacej97** [comment]
Hi @raisedadead @ojeytonwilliams I'd like to work on this issue. However, I'd like more clarity on if you'd want to get rid of the Style Guide altogether or just use the style guide to make the 'how to work on coding challenges' and 'how to work on guide articles' files better and more specific?

**Comment by RandellDawson** [comment]
@candacej97 We are still discussing this issue.  We will reach out to you once we get a few things ironed out.  Then it will be fairly easy for you to create the PR if you still want to.

**Comment by candacej97** [comment]
Okay that would be great thank you!

**Comment by ctfrancia** [comment]
any updates?
