### ISSUE TITLE
Bonfire: Make a Person

### ISSUE THREAD

**Issue by WalterCJ** [FreeCodeCamp/FreeCodeCamp#3552]
No tests are being displayed even if I try to reset and put my code nothing happens. I tested with another browsers and the problem is the same. Just the message is shown : "Program Execution FailureNo user tests were run."

![Error message](http://i.imgur.com/hMxsT3E.png?1)

**Comment by BerkeleyTrue** [comment]
You code is incorrect. bob.getFullname is not a function as stated in the error message. This is a syntax error that crashed the test suite. Please fix the syntax error and re-run. You tests will return.

Happy Coding
