### ISSUE TITLE
single quote symbol is worng in "Debugging: Catch Mixed Usage of Single and Double Quotes" cahllenge

### ISSUE THREAD

**Issue by tvibhu12** [freeCodeCamp/freeCodeCamp#35527]
**Describe your problem and how to reproduce it:**
in `Debugging: Catch Mixed Usage of Single and Double Quotes` challenge i found an error. single qoute symbol is wrong in guide section. symbol of single qoute should be this (') but it is showing this ("). 
**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/debugging/catch-mixed-usage-of-single-and-double-quotes
**Tell us about your browser and operating system:**
* Browser Name: chrome
* Browser Version: 71.0.3578.98 (Official Build) (64-bit)
* Operating System: ubuntu 18.04

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![imageedit_3_4134656954](https://user-images.githubusercontent.com/37179627/53894132-8f2d0180-4055-11e9-8e48-659b3ed70294.jpg)

**Comment by RandellDawson** [comment]
Good catch!  

I recommend changing the current line 9 in the challenge file to the following:
```html
JavaScript allows the use of both single (<code>'</code>) and double (<code>"</code>) quotes to declare a string. Deciding which one to use generally comes down to personal preference, with some exceptions.
```

which will then display as the following:

JavaScript allows the use of both single (<code>'</code>) and double (<code>"</code>) quotes to declare a string. Deciding which one to use generally comes down to personal preference, with some exceptions.
