### ISSUE TITLE
Make it clear to edit code between style tags

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/freeCodeCamp#35533]
**Describe your problem and how to reproduce it:**
In the Applied Visual Design challenges, the [Create Visual Balance Using the text-align Property](https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-visual-balance-using-the-text-align-property) challenge (the first challenge of the series), it doesn't make it immediately clear you need to edit the code between the style tags.

It may be obvious to some but as an anxious coder and learner, I jumped straight down to the `h4` tag mentioned in the instructions:

> Align the `h4` tag's text, which says "Google", to the center. Then justify the paragraph tag which contains information about how Google was founded.

And then I made the changes as an inline style. Only after submitting my answer did I realize the challenge wanted to change the CSS within the `style` tags.

**Suggested Fix**
Modify the instructions to mention to edit the code between the `style` tags at the top.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/create-visual-balance-using-the-text-align-property

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 72.0.3626.117 (Official Build) (64-bit)
* Operating System: Chrome OS 

**Note**: given the upcoming changes to [freeCodeCamp's next release](https://gitter.im/FreeCodeCamp/Contributors?at=5c7a23172ca5ec547462f85d) as of the writing of this issue, you may claim this issue to work on, but it being merged will probably happen after the next big release. If you have any doubts, [please ask in the contributors Gitter chat](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by rmfranciacastillo** [comment]
Sounds interesting.

Would it be clearer to add something like "Modify the CSS in <style> to align the  h4 tag's text .."

instead of 

"Align the h4 tag's text, which says "Google", to the center. "

**Comment by RandellDawson** [comment]
Another option is to modify the tests to using whatever styling (inline vs. CSS selector within the `style` element).  Otherwise, like you said, it should be clearer to modify the CSS in the `style` element.

**Comment by RandellDawson** [comment]
@erictleung They are currently deploying `master` to the beta site each day, so it is possible any changes made before the production launch will go into production.

**Comment by RandellDawson** [comment]
Actually, this is a non-issue, because the challenge already lets you use inline styling on both the `h4` and `p` elements.

**Comment by erictleung** [comment]
> Actually, this is a non-issue, because the challenge already lets you use inline styling on both the `h4` and `p` elements (production and master branch code).

@RandellDawson thanks for double checking. I went through this challenge a couple days ago, and just now thought of it. I guess I wrote the CSS wrong the first time :laughing: But I verified it does work both ways.

@RandellDawson @rmfranciacastillo if both inline and CSS selectors pass the challenge, does it matter to change the directions then?

**Comment by RandellDawson** [comment]
I don't think we need to modify the instructions at all, since both ways work.

**Comment by rmfranciacastillo** [comment]
@RandellDawson Agreed.
