### ISSUE TITLE
'lastname is not defined' but lastname is defined

### ISSUE THREAD

**Issue by yourboyvic** [FreeCodeCamp/FreeCodeCamp#3553]
![screen shot 2015-10-01 at 5 56 11 am](https://cloud.githubusercontent.com/assets/6733145/10221118/28ba5f22-6801-11e5-8924-91a9733f166c.png)
Challenge [Waypoint: Use Bracket Notation to Find the Last Character in a String](http://freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-last-character-in-a-string) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var firstName = "Ada";

var lastLetterOfFirstName = firstName[firstName.length - 1];

var lastName = "Lovelace";

var lastLetterOfLastName = lastname[lastName.length-1];


// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
// You'll learn about functions soon.
(function(v){return v;})(lastLetterOfLastName);

```

**Comment by bugron** [comment]
@yourboyvic thanks for posting this issue!
You should always remember that JavaScirpt is **case sensitive**, so `lastname` is not the same as `lastName`. Replace `lastname[lastName.length-1]` with `lastName[lastName.length-1]` and you'll be able to pass the test.
Closing this issue. If you have problems with your code, please, post a message in our [Gitter chat room](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-Get-Help-on-Gitter) first, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
