### ISSUE TITLE
Cannot access Waypoint "Get started with FreeCodeCamp"

### ISSUE THREAD

**Issue by whereissql** [FreeCodeCamp/FreeCodeCamp#3554]
Login to FreeCodeCamp and go to the first way point for "Getting started with Free Code Camp"

I get a message "Oops Something went wrong. Please try again later"

![image](https://cloud.githubusercontent.com/assets/11634760/10229200/dd1938a6-6844-11e5-8cf1-ee9811d4007b.png)

**Comment by bugron** [comment]
@whereissql thanks for posting this issue!
Also FCC redirects me to the main page when I open other "Get Started with Free Code Camp" challenges.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by BerkeleyTrue** [comment]
Removed. Sorry about that. Those are coming soon.
