### ISSUE TITLE
Need a stricter test for the Add Placeholder Text to a Text Field challenge

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#35543]
This is an issue raised by @huyenltnguyen on PR #26458.

The tests pass even for invalid code (adding the closing </input> tag).  We need to discuss here what the best "fix" is for this issue.  It could be a modification an existing test or adding a new test which checks to make sure the user's code does not have a `</input>` tag after the `<input>` tag. 

Once we finalize what the fix should do, we will attach a `Help Wanted` label on this issue.  Please wait until we have added this label before creating PRs for this issue.

Thank you.

**Comment by ojeytonwilliams** [comment]
I'm in favour of adding an extra test, since the instructions specifically reference this detail:
> Note: Remember that `input` elements are self-closing.

Also, the final test 
> The finished <code>input</code> element should have valid syntax.

could cover this, but if their mistake is putting a closing tag after a syntactically valid input element, it could be confusing.  Adding another, specific test avoids this kind of frustration.

**Comment by RandellDawson** [comment]
@ojeytonwilliams What do you think a new test's `text` should be and generally what should the test do? We need to define what we mean by a "good" test here, so a user can attempt to create a solution.  Once we have the general approach, we can add a 'help wanted' label.  If it seems easy to fix, then we can add a 'first timers welcome` label too.

**Comment by ojeytonwilliams** [comment]
@RandellDawson Something like 

>The finished `input` element should not have a closing tag.

would be fine for the text.  That test should appear before the final catchall
>The finished `input` element should have valid syntax.

and it should just fail if it sees an `</input>` tag anywhere.

Ideally, the final test would be a catch-all, so we are not giving conflicting messages like "the syntax is fine, but please fix this specific part of it".  However, the main thing is to catch the bad syntax. I don't think the contradiction would be too confusing, particularly if they're put in the order I suggested.

**Comment by moT01** [comment]
Sounds good to me @ojeytonwilliams

**Comment by RandellDawson** [comment]
Anyone who wants to try and implement @ojeytonwilliams' suggestion?

**Comment by minggas** [comment]
I can implement that solution. I will add one more test to see if the input has a closing tag and and one more match in the final catchall to get anything that pass the limit of the `<input />` final >. Any thoughts?

**Comment by RandellDawson** [comment]
@minggas Give it a try and we can test it for edge cases.
