### ISSUE TITLE
Landing page images are left-adjusted instead of centered

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#35549]
Here's a screenshot: 

<img width="898" alt="learn_to_code___freecodecamp_org" src="https://user-images.githubusercontent.com/985197/54044760-5f851300-4195-11e9-88c0-570830135cf5.png">

A CSS change elsewhere must have resulted in this outcome on the landing page.

**Comment by moT01** [comment]
This doesn't seem to be an issue for me on the current live site - only on beta/rocks, so something must have broken it
