### ISSUE TITLE
Add test to disallow extra characters in Applied Accessibility: Standardize Times with the HTML5 datetime Attribute

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#35557]
In the challenge [Applied Accessibility: Standardize Times with the HTML5 datetime Attribute](https://www.freecodecamp.rocks/learn/responsive-web-design/applied-accessibility/standardize-times-with-the-html5-datetime-attribute), if an extra character/characters is/are added in the code between the `</sup>` and `</time>` tags, the challenge still passes. The buggy code looks like this:
```html
<p>Thank you to everyone for responding to Master Camper Cat's survey. The best day to host the vaunted Mortal Kombat tournament is <time datetime="2016-09-15"> Thursday, September 15<sup>th</sup>randomweirdcharacters</time>. May the best ninja win!</p>
```
Note the `randomweirdcharacters` part, we want a test to disallow it.

Refer to the discussion on PR #35553

**Comment by seki2020** [comment]
It seems a good idea. Can I have the chance to deal with it ?

**Comment by RandellDawson** [comment]
@seki2020 The help wanted label was put on a bit prematurely.  We are awaiting a few more collaborators/mods to respond with there feedback to make sure it is an issue worth "fixing".  Once we add the help wanted label back, you are free to create a PR for this.

**Comment by ojeytonwilliams** [comment]
Looks like a reasonable requirement to me.  I don't think there's any need for a new test, though.  The first test 

>   text: Your <code>time</code> tags should wrap around the text "Thursday, September 15&lt;sup&gt;th&lt;/sup&gt;".

should just be modified to catch the extra characters.

**Comment by moT01** [comment]
There's only one solution that should work here... `<time datetime="2016-09-15">Thursday, September 15<sup>th</sup></time>`
So we can check for exactly that. I agree that the first test can be modified to check for the correct input.

Are you still interested in working on this @seki2020?

**Comment by Stevo99** [comment]
If this is still open I would like to try to fix it.  It would be my first contribution, which would mean a lot.

**Comment by moT01** [comment]
Sure @Stevo99, here's the file - https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-accessibility/standardize-times-with-the-html5-datetime-attribute.english.md

Perhaps just adding a `^` and `$` to that regex test - not sure

**Comment by Stevo99** [comment]
ok thanks looking into it now..

**Comment by Stevo99** [comment]
hey having a little trouble.  Everything I looked into tells me I can put an ^ to start a string and $ at end of string but it wont pass.  is there a way to see my output without submitting the test. (like a console.log so I can see the actual output im getting).  Im sure its something really small im missing but im unfamiliar with yml snippets so unsure how to debug that.

**Comment by ojeytonwilliams** [comment]
@Stevo99 You can put console logs before assertions, so if you wanted to see what `$('time').text()` was, it would look a bit like this:
```js
testString: console.log($('time').text());assert(...
```
Hope that helps!

**Comment by moT01** [comment]
also, there's regex tools - I like https://regex101.com/ - you can put a few stings in there and then see what your regex will match

**Comment by Stevo99** [comment]
ok thanks..  appreciate the help

**Comment by Stevo99** [comment]
so I need to match the answer to the exact string "Thursday, September 15th", however Im having trouble because  <code>$('time').text()</code> returns the 3 diff strings from all the <code>time</code> tags with out any breaks. if I could separate the time tags I can maybe compare it to string with ===.  Anyway im sorry to keep bothering just maybe need the docs so I can explore.  Is it Jquery and Chai?

**Comment by RandellDawson** [comment]
>  Is it Jquery and Chai?

@Stevo99 Yes

**Comment by Stevo99** [comment]
cool..  Im getting close. I seem to get what i need by using .html() instead of .text()

**Comment by RandellDawson** [comment]
@Stevo99 Yes, you will need to use `html()`.  You will still need to use the `^` and `$`, but I also recommend allowing space characters at the beginning and ending of what you capture, because someone may accidentally add a space and it would be nice if the tests were a bit flexible in that regards.  However, no other characters before or after should be present.

**Comment by Stevo99** [comment]
Yea no problem! I would love too. thanks for the help!

**Comment by Stevo99** [comment]
ok I think I finally got it! this is what I came up with <code>testString: assert($('time').text().match(/\s?Thursday, September 15th\s?/g) && $('time').html().trim() === "Thursday, September 15<sup>th</sup>");</code>
this seems to work for all the tests and I tested it with and without whitespace.

**Comment by RandellDawson** [comment]
Do you need the `$('time').text().match(/\s?Thursday, September 15th\s?/g)` ?

**Comment by Stevo99** [comment]
no I don't.  Just tested it and it works without it.  I also made all the other changes you requested.

**Comment by Stevo99** [comment]
is it ok to submit the PR

**Comment by RandellDawson** [comment]
Go ahead.  We can always request additional changes once it's created.

**Comment by Stevo99** [comment]
ok thanks!
