### ISSUE TITLE
Broken Tests in Add Axes to a Visualization challenge in D3

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#35554]
**Describe your problem and how to reproduce it:**
Even though the following code:

```js
    svg.append("g")
      .attr("transform",  "translate(" + 60 + ", 0)")
      .call(yAxis);
```
places the Y-Axis at the right place, it doesn't pass the challenge:

![image](https://user-images.githubusercontent.com/34807532/54075797-644ae380-42c9-11e9-8f3a-f7eec8892f4c.png)

**Add a Link to the page with the problem:**

https://www.freecodecamp.rocks/learn/data-visualization/data-visualization-with-d3/add-axes-to-a-visualization

**Comment by Sumer16** [comment]
Even I faced the same problem. How can I help you to fix it?

**Comment by thecodingaviator** [comment]
@Sumer16 A good place to start would be the `/curriculum` folder, navigate to the challenge file ans see what you can fix :) . Be sure to read the contributing documents in the `/docs` directory first though!

**Comment by cmccormack** [comment]
`padding` is a variable already provided in the code, you should be using that variable as your first argument, not an integer literal. See the `xAxis` code provided for an example.

**Comment by thecodingaviator** [comment]
@cmccormack I thought that it might be the problem, so I hard coded it, even padding does not work:
![image](https://user-images.githubusercontent.com/34807532/54087787-bf89de00-437c-11e9-847a-3cc8d369206b.png)

**Comment by cmccormack** [comment]
@thecodingaviator I've tried several variations of your issue and my tests always pass - what browser and version are you using?  Can you inspect the output element and provide a screenshot of the axis as rendered?

**Comment by cmccormack** [comment]
For reference, here is a screenshot of the rendered axis parent `g` from my passing tests using Chrome 72 
![image](https://user-images.githubusercontent.com/3016919/54087843-a3eaed00-4314-11e9-8674-4acd9076e716.png)

**Comment by thecodingaviator** [comment]
Here @cmccormack :
![image](https://user-images.githubusercontent.com/34807532/54087875-afbec980-437d-11e9-885e-15148d161ccf.png)

I'm on `Version 72.0.3626.121 (Official Build) (64-bit)`

**Comment by Sumer16** [comment]
I used padding too but was stuck with the same issue. @cmccormack 
![as](https://user-images.githubusercontent.com/31842450/54087992-f9f47a80-437e-11e9-972e-4f115ff43f31.PNG)

**Comment by cmccormack** [comment]
Hmm what's odd is if I reset the code completely and run it that particular test still passes.
Are you getting any errors in the dev console?

**Comment by thecodingaviator** [comment]
Just this:
![image](https://user-images.githubusercontent.com/34807532/54088221-b3544f80-4381-11e9-9758-d7fa0e0e45ce.png)

**Comment by Sumer16** [comment]
Same Console log error without any difference.

**Comment by Sumer16** [comment]
Can you send a screenshot of your passed test? @cmccormack

**Comment by cmccormack** [comment]
My apologies, for some reason I didn't see this was in `.rocks`.  
I took a look at the output and it appears that jQuery is showing the transform different than the element attribute:
![image](https://user-images.githubusercontent.com/3016919/54097379-1daec500-436d-11e9-8ca4-f5a1a314e8fe.png)

**Comment by ValeraS** [comment]
jQuery shows a correct value but this expression checks a wrong element

**Comment by Sumer16** [comment]
Is this one right? @thecodingaviator

**Comment by cmccormack** [comment]
Would it be a better solution to add `id` attributes to the elements and add that to the exercise criteria?  It's a requirement in the testing suite for the D3 projects, would it hurt to have it in the challenges as well @ValeraS ?

**Comment by thecodingaviator** [comment]
@cmccormack What I suggest is that we go ahead with this issue right now since that discussion and the corresponding changes would take a long time, we want this to get in before we release so that users do not fail the test. Maybe create a new issue for that discussion

**Comment by cmccormack** [comment]
As long as this doesn't affect the production challenge, that's fine with me, but IMO we should try to be more precise in the tests so something like a version upgrade to library doesn't break the tests.

**Comment by ValeraS** [comment]
We can select only 2 `g` for axes and check both.

**Comment by thecodingaviator** [comment]
@ValeraS I'm not sure what you mean by that. Also, I think we should open a new issue to fix that
