### ISSUE TITLE
Fill in introduction sections

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35550]
Some introduction sections still haven't been created.

**PR Created**
- [x] [Intermediate Algorithm Scripting](https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/) - @thecodingaviator #34405 
- [x] [Information Security and Quality Assurance Projects](https://www.freecodecamp.rocks/learn/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/) - @Sumer16 #35576 
- [x] [Take Home Projects](https://www.freecodecamp.rocks/learn/coding-interview-prep/take-home-projects/)

**PR Merged**
- [x] [Intermediate Algorithm Scripting](https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/)
- [x] [Information Security and Quality Assurance Projects](https://www.freecodecamp.rocks/learn/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/)
- [ ] [Take Home Projects](https://www.freecodecamp.rocks/learn/coding-interview-prep/take-home-projects/)

**Comment by Sumer16** [comment]
How can I help You?

**Comment by RandellDawson** [comment]
@Sumer16 The idea here is to discuss possible intros for the sections mentioned above.  Onece we agree on the verbiage, then someone can create a PR with the decided verbiage.

**Comment by Sumer16** [comment]
Can I paste in the Intros here directly?

**Comment by RandellDawson** [comment]
Sure, let's see what you think would be appropriate.  Then, we can tweak before a PR is created.

**Comment by Sumer16** [comment]
**Introduction to the Information Security and Quality Assurance Projects**

So, now it’s time to put your newly learnt skills to work! By working on these projects, you would have the opportunity of applying all the skills, principles and concepts you have learnt in Information Security using HelmetJS and Quality Assurance with Chai.

In this section you get the chance to:
•	Build a Metric-Imperial Converter
•	Build an Issue Tracker
•	Build a Personal Library
•	Build a Stock Price Checker
•	Build an Anonymous Message Board

By the end of this, you would have 5 IS & QA projects under your belt that you can show off to friends, family, employers, etc. Have fun and remember to use the Read-Search-Ask method if you get stuck.

Is this okay? @RandellDawson

**Comment by moT01** [comment]
Since what is currently there is nothing - I think this is a huge improvement.. This looks great, but a few of my suggestions...
<hr>

**Introduction to the Information Security and Quality Assurance Projects**

So, now it’s time to put your newly learnt skills to work! By working on these projects, you will have the opportunity of applying all the skills, principles, and concepts from the Information Security and Quality Assurance sections.

In this section you get the chance to:
• Build a Metric-Imperial Converter
• Build an Issue Tracker
• Build a Personal Library
• Build a Stock Price Checker
• Build an Anonymous Message Board

By the end of this, you will have five IS & QA projects under your belt, along with a certification, that you can show off to friends, family, and employers. Have fun and remember to use the [Read-Search-Ask](https://forum.freecodecamp.org/t/how-to-get-help-when-you-are-stuck/19514) method if you get stuck.
<hr>

My suggestions are just my opinion - at minimum, I would make the "read-search-ask" a link to the forum post - https://www.freecodecamp.org/forum/t/how-to-get-help-when-you-are-stuck/19514

**Comment by RandellDawson** [comment]
Going a little further, I like the idea of putting the read-search-ask link on the intro pages (as @moT01 suggests) and removing them from the individual challenges (which many have currently).

**Comment by moT01** [comment]
Feel free to make a PR @Sumer16 🍎

**Comment by Sumer16** [comment]
Okay I will make the PR for the Intros . Thanks @moT01 for the suggestions.

**Comment by Sumer16** [comment]
**Introduction to the Coding Interview Take Home Projects**

Programming interviews have always been stressful. One of the solutions is giving the applicant a take home project which they can complete on their own time. This type of interviews usually requires a lot of work but it is considered to be the most preferred interviewing process. 

The interview after project submission could be a discussion about applicant’s design decisions, scalability, and what they might have done out of the box. This approach is more effective when the applicant doesn’t have a lot of publicly available past projects to talk about.

In this section you get the chance to work on many Take Home Projects like: 
* Show Local Weather 
* Build a Wikipedia Viewer 
* Build a Recipe Box and many more…

By the end of this section, you will have 20 Take Home Projects under your belt. This will boost your confidence and make you prepared for Take Home Project Interviews. Have fun and remember to use the [Read-Search-Ask](https://www.freecodecamp.org/forum/t/how-to-get-help-when-you-are-stuck/19514) method if you get stuck.

Is this Okay? @moT01 @RandellDawson

**Comment by Sumer16** [comment]
## Introduction to the Intermediate Algorithm Scripting Challenges

This section contains intermediate level coding problems that will test your ability to solve complex problems similar to those that you may see in real situations using Javascript. All the best!

#### Hint
If you get stuck, try using `console.log()` to log variable values to the console. This will help to debug problems. 

Is this Okay?? @moT01 @RandellDawson

**Comment by thecodingaviator** [comment]
@Sumer16 That is no longer needed, we already have a fix in #34405

**Comment by Sumer16** [comment]
You have done only for Intermediate Algorithm Scripting right?

**Comment by thecodingaviator** [comment]
Affirmative

**Comment by Sumer16** [comment]
Can you please check is this one correct? Also should I PR for Take Home Projects?

**Comment by Sumer16** [comment]
I have made the PRs for Information Security and Quality Assurance Projects & Take Home Projects.

**Comment by JoKurio** [comment]
> **Introduction to the Coding Interview Take Home Projects**
> 
> Programming interviews have always been stressful. One of the solutions is giving the applicant a take home project which they can complete on their own time. This type of interviews usually requires a lot of work but it is considered to be the most preferred interviewing process.
> 
> The interview after project submission could be a discussion about applicant’s design decisions, scalability, and what they might have done out of the box. This approach is more effective when the applicant doesn’t have a lot of publicly available past projects to talk about.
> 
> In this section you get the chance to work on many Take Home Projects like:
> 
> * Show Local Weather
> * Build a Wikipedia Viewer
> * Build a Recipe Box and many more…
> 
> By the end of this section, you will have 20 Take Home Projects under your belt. This will boost your confidence and make you prepared for Take Home Project Interviews. Have fun and remember to use the [Read-Search-Ask](https://www.freecodecamp.org/forum/t/how-to-get-help-when-you-are-stuck/19514) method if you get stuck.
> 
> Is this Okay? @moT01 @RandellDawson

@Sumer16 great job on this. I have some observations though. In the first paragraph, the second sentence seems to imply that take home projects are a "solution" to the stress that comes from programming interviews, but the context of the article rightly shows that they are a major part of the interview process that can be stressful and taking this course helps prepare the students for them.
Also, in the third sentence of the first paragraph, there are subject-verb disagreements: "This type"(singular) , "interviews"(plural), "requires"(singular).
These are just some tweaks you can apply to further improve a great article.
