### ISSUE TITLE
Missing dependency to run freecodecamp on Windows 10: babel-node

### ISSUE THREAD

**Issue by Javiercerna** [freeCodeCamp/freeCodeCamp#35558]
**Describe the bug**
When I run freecodecamp on Windows 10 after following the [Set up freeCodeCamp locally](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md) guide, only the frontend shows (localhost:8000), while the backend never loads (localhost:3000). This only solves after installing babel-node:

`npm install --save-dev @babel/core @babel/node`

**To Reproduce**
Follow the steps in the guide. After installing and cloning everything, in summary:

1. `npm install`
2. `mongod`
3. `npm run seed`
4. `npm run develop`

**Expected behavior**
According to the guide, I should be able to visit both http://localhost:8000 and http://localhost:3000/explorer. However, I'm only able to see the client side and nothing loads on port 3000.

**Screenshots**
After finding out the error was related to develop:server, I tried to reproduce it.

![image](https://user-images.githubusercontent.com/7322431/54095984-ded23c80-4377-11e9-885b-4137b5607772.png)

Then, after installing babel-node, the error goes away and everything runs smoothly:

![image](https://user-images.githubusercontent.com/7322431/54096098-61f39280-4378-11e9-9d8a-6a4be1ae9470.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Version 1803
 - Browser: Google Chrome
 - Version: 72.0.3626.121 (64 bits)

**Additional context**
Using prerequisite software as indicated in the guide:
- Node: v10.15.1
- MongoDB: v3.6.10
- NPM: v6.4.1

**Comment by RandellDawson** [comment]
Did you copy sample.env to .env in the root directory?

**Comment by Javiercerna** [comment]
Yes, I did. I just mentioned the four commands to be concise, but I followed every step in the guide.

**Comment by RandellDawson** [comment]
You only need to run `npm run develop` and it will launch both the backend server and the client.

**Comment by Javiercerna** [comment]
I did,and yes,it indeed launched in theory both the client and backend server. However,the backend was not working and it was difficult to see the error there, because of the client log messages and because internally the backend runs the command 

npm run --silent babel-dev-server

I had to remove the --silent flag and run manually the backend to be able to spot what the problem was.

**Comment by raisedadead** [comment]
You do not need to install `babel-node` or any tools globally to have freeCodeCamp running locally. Usually this could be due to:

- `babel-node` not getting compiled during install on your machine.
- a permissions issue (did you launch your terminal/cmd as administrator?)

Or both of the above.

**Comment by raisedadead** [comment]
Please re-open as a topic on the forum. https://www.freecodecamp.org/forum/c/contributors 
The awesome folks there will help you through this.

Also we have a [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) where you should seek assistance.

**Comment by anthonykyi** [comment]
Hi, I can confirm this issue as well on my windows 10 setup. Running `npm run develop` only starts up the client side, but swallowed server errors. I was getting the error about babel-node not being a valid command and ran `npm install --save-dev @babel/core @babel/node` as @Javiercerna did. Now the error about node-babel is gone, and running `npm run develop` correctly starts up both the client and the server.
