### ISSUE TITLE
Improvements to the challenge ES6 Use Destructuring Assignment to Assign Variables from Objects

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#35574]
Improvements to this challenge: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-objects/

1. I suggest we remove the function from the challenge code. It just adds an extra layer of complexity with no added benefit. I suggest we just have an object and the destructuring.

```js
const AVG_TEMPERATURES = {
  today: 77.5,
  tomorrow: 79
};

const tempOfTomorrow = AVG_TEMPERATURES.tomorrow; // change this line to use destructuring instead
```

2. Instead of voxel and some random decimal numbers for the example code we should use something less abstract.

```js
var user = { name: 'John Doe', age: 34, password: 'qwerty' };

var name = user.name; // name = 'John Doe'
var age = user.age; // age = 34
var password = user.password; // password = 'qwerty'

const { name, age, password } = user; // name = 'John Doe', age = 34, password = 'qwerty'

const { name: userName, age: userAge, password: userPassword } = user; // userName = 'John Doe', userAge = 34, userPassword = 'qwerty'

const { objectProperty: variable } = object; // Same as const variable = object.objectProperty
```

3. The instructions should be clear. This is a bit tricky and I'm not 100% sure how to phrase it. If anyone has a suggestion please let me know.

> Use destructuring to assign the value of the tomorrow property from the object AVG_TEMPERATURES to a new variable named tempOfTomorrow. Look at the last code example given for help on syntax.

**Comment by IshaTr** [comment]
@lasjorg do you mind if I make the destructuring modifications?

**Comment by Dharmin2108** [comment]
Checking my project

**Comment by RandellDawson** [comment]
@moT01, @thecodingaviator I do like the simplicity of the changes suggested here for this challenge. What do you think?

**Comment by moT01** [comment]
I think the majority of the confusion here comes from the fact that you need to assign a new name to the destructed variable. Instead of `const { tomorrow } = avgTemperatures` the solution is `const { tomorrow: tempOfTomorrow } = avgTemperatures` - and that part of the description is confusing. Before the third example, I didn't think the `voxel` example was confusing. This is the first time campers are introduced to destructuring - and I think they should just have to destructure a variable and not give it a new name - that's more often how it's done. So here's my suggestions...
The last part of the description could be changed I think to something like this:
```
If instead, you want to assign a new variable name when destructuring,
you can do it like this:

    const { x : newVariable } = voxel // newVariable = 3.6

`newVariable` will be given the value of `voxel.x`. You can destructure
as many, or as few values from `voxel` as you want in a destructuring
assignment.
```

I agree that the function in the seed code is kind of confusing and not necessary - it might have worked better if it was a little more clear - I'm thinking if we change the seed code to this...
```
const AVG_TEMPERATURES = {
  yesterday: 78,
  today: 77.5,
  tomorrow: 79
};

// change code below this line
  
// change code above this line

console.log(yesterday) // should be not defined
console.log(today); // should be 77.5
console.log(tomorrow); // should be 79
```

and the instructions to this...
```
Use destructuring to assign `today` and `tomorrow` the values
of `today` and `tomorrow` from the `AVG_TEMPERATURES` object.
```

**Comment by RandellDawson** [comment]
@moT01 Maybe we have two challenges.  The first being your idea and the second what @lasjorg has above?  That way we separate destructuring with assignment to variable and destructuring with reassignment.  That way the the extra note (see below) would be part of the challenge description of the 2nd challenge.
```
If instead, you want to assign a new variable name when destructuring,
you can do it like this:

    const { x : newVariable } = voxel // newVariable = 3.6

`newVariable` will be given the value of `voxel.x`. You can destructure
as many, or as few values from `voxel` as you want in a destructuring
assignment.
```

On the forum I have had success in teaching the concept of object destructuring with the variations of the following example code:
```js
const object = {
  objectProp1: 'some value',
  objectProp2: 'another value'
};
const { objectProp1: newVariable1 } = object;
console.log(newVariable1); // 'some value';
```

**Comment by moT01** [comment]
It could work either way - an easy fix for this specific issue would be to just update this one to make it easier. But it does seem like splitting this up might be better.

**Comment by RandellDawson** [comment]
@ojeytonwilliams @Manish-Giri What are your thoughts on this discussion?

**Comment by thecodingaviator** [comment]
I agree that we should get rid of the function.

@moT01 how about this:
```
Use destructuring to assign the variable `today` and `tomorrow` the values
of the `today` and `tomorrow` properties from the `AVG_TEMPERATURES` object.
```

**Comment by ojeytonwilliams** [comment]
I like the idea of two small challenges.  One introducing destructuring and a second showing that they can be assigned new names.

@lasjorg's original idea of contrasting assignment operators with destructuring is a good one, but I think it would be better to assign two or more variables at once.  Reason being, if it's just one, the contrast is between
```js
const tomorrow = AVG_TEMPERATURES.tomorrow; 
```
and
```js
const { tomorrow } = AVG_TEMPERATURES;
```
which isn't obviously much better, but
```js
const today = AVG_TEMPERATURE.today;
const tomorrow = AVG_TEMPERATURES.tomorrow; 
```
vs
```js
const { today, tomorrow } = AVG_TEMPERATURES;
```
is.

With that in mind, I'd suggest adding 
```js
const today = AVG_TEMPERATURE.today;
const tomorrow = AVG_TEMPERATURES.tomorrow; 
```
to @moT01 seed code and maybe make it clear that destructuring can reduce that to a single line.  i.e. a slight change to @thecodingaviator's instructions:

> Replace the two assignments with a single, equivalent destructuring assignment.  It should still assign the variables `today` and `tomorrow` the values  of the `today` and `tomorrow` properties from the `AVG_TEMPERATURES` object.

**Comment by moT01** [comment]
So in total it would be like this... ?

```
## Instructions
```

**Comment by ojeytonwilliams** [comment]
Yep, that's nice.  As for the description, I see both approaches (voxel or user) to be pretty much equivalent, so I'd be happy with either.

**Comment by RandellDawson** [comment]
I am in agreement with @ojeytonwilliams on using either voxel or user.  

> And then add another challenge for destructuring + a new variable name

Can you just modify the existing challenge instead of creating a new for this?

**Comment by Manish-Giri** [comment]
I like the idea of splitting up this challenge into two - just plain destructuring and destructuring with reassignment. Object destructuring is by itself a somewhat difficult topic for those new to ES6, there's nothing to be gained by adding re-assignment at the same time when destructuring is introduced.

I do however prefer to keep the function in the seed code. While it doesn't add anything of value, it also doesn't add any unwanted complexity, and it also follows the consistent style from all the preceding ES6 challenges, which use functions (or at least IIFEs) in the seed code.

My 2 cents.

**Comment by RandellDawson** [comment]
> (or at least IIFEs) 

I thought we got rid of all of the IIFEs in a fairly recent PR merge.

**Comment by ojeytonwilliams** [comment]
I have one, somewhat meta, question.  When we have a difference of opinion like we have here (function vs. no function and one challenge vs. two), how do we want to resolve this?  The problem, as I see it, is that there's no clear winner. All the options have something to recommend them and choosing seems to come down to person preference.

Is the best option, once we've had a bit of discussion, simply to ask for a PR?  That way opinions get heard, but we don't get stuck.  What do people think?

I appreciate the irony of discussing this here, so, if anyone objects, I can just move the discussion to a separate issue.

**Comment by moT01** [comment]
We have what? 6 regular contributors here? I think we should be able to come up with something - I say we put things to a vote - it seems like the majority of us were in favor of getting rid of the function, I do believe we got rid of all those IIFE's in this section at one point. And it seemed like some of us we're fine with splitting it into two challenges, but I'm not sure we got a great voter turnout on that one. And as far as the wording - we're all going to have a little difference of opinion there - so, as long as we can come up with something close to what we want - then whoever makes the PR can just put something close to that - and if it's not good enough, we can ask for changes on the PR.

I'm not sure how else we can do it - quincy and the rest of the people that have authority here probably don't need to be bothered with something like this. Do you have any better ideas?

**Comment by ojeytonwilliams** [comment]
I'm fairly relaxed about precisely how we go about it.  I guess if the conversation grinds to a halt, we can just stick a help wanted label on to invite a PR.  Then whoever makes the PR could count the votes (or just count the opinions - I don't think it needs to be formalized) and try to make the best compromise.

**Comment by thecodingaviator** [comment]
I believe the best way to do this is that everyone who's in favor of the following changes can add their names below the list item, this way we can have a list of who voted for what. @ojeytonwilliams I believe it is best to formalize it so we can fall back to this in case we ever need it.

1. Getting rid of the function
Yes - @thecodingaviator 

2. Using less abstract values
Yes - @thecodingaviator 

3. Rewording the challenge
Yes - @thecodingaviator 

4. Splitting the challenge
No - @thecodingaviator
