### ISSUE TITLE
Do CSS semicolon rules need clarification?

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#35571]
This issue is to discuss any possible clarification of the CSS semicolon rules. This is in relation to the [first](https://learn.freecodecamp.org/responsive-web-design/basic-css/change-the-color-of-text) and the [second](https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-selectors-to-style-elements) challenges in the Basic CSS curriculum. See https://github.com/freeCodeCamp/freeCodeCamp/pull/35535 for more information.

Here are some thoughts for the first challenge:

The best practice given in the note section of the first challenge is not specific to inline styles. Technically you can always leave off the semicolon for the last style in the block. The problem is that it is easy to overlook when adding more styles and forget to add the semicolon to the previous declaration.

I think we can add a concise sentence which gives a why without really explaining it. This is taken from the Google HTML/CSS Style Guide, the last sentence is concise, gives two reasons, but does not overexplain it. This might be a good candidate for the note in the first challenge.

> [4.2.3 Declaration Stops](https://google.github.io/styleguide/htmlcssguide.html#Declaration_Stops)
> 
> Use a semicolon after every declaration.
> 
> End every declaration with a semicolon for consistency and extensibility reasons.

For the second challenge:

The next challenge talks about syntax rules but does so in an odd way by adding the information in what looks like a note section. Maybe it should be rewritten and can then include a more detailed explanation of the semicolon rules. Although, it might be hard to do so without making the challenge too long and getting too deep into technical information. It is after all only the second challenge of the Basic CSS curriculum.

**Comment by lynxlynxlynx** [comment]
When in doubt, KISS. I second the first motion, while I would just remove the note in the second. It's already shown by the example.

**Comment by moT01** [comment]
Closing as stale. I don't think semi-colon rules need to be clarified. That's a small nuance that coders will pick up over time, and I think it's probably best practice to just always use it. If anyone wants to continue this conversation, feel free to leave a comment and we can reopen this. Thanks and happy coding 🎉
