### ISSUE TITLE
MongoDB and Mongoose - Install and Set Up Mongoose

### ISSUE THREAD

**Issue by mscanza** [freeCodeCamp/freeCodeCamp#35587]
**Describe your problem and how to reproduce it:**
mLab is no longer accepting new users, cannot get mongoose to connect in order to complete challenges.  Directions are now obsolete - need update.

**Add a Link to the page with the problem:**
https://i.imgur.com/JPAgbHj.png

**Tell us about your browser and operating system:**
* Browser Name: chrome
* Browser Version: 72.0.3626.121
* Operating System: MAC OS 10.14.3

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="1095" alt="Screen Shot 2019-03-13 at 12 14 18 PM" src="https://user-images.githubusercontent.com/39040369/54308146-9c347e00-458a-11e9-9e55-2a7a9df0cb18.png">

**Comment by Dereje1** [comment]
Instructions do need changing, however challenges still work even with the new MongoDB Atlas connection setup.
https://www.freecodecamp.org/forum/t/mongodb-and-mongoose-install-and-set-up-mongoose/203270/28
