### ISSUE TITLE
Solution not working - "Truncate A String"

### ISSUE THREAD

**Issue by StefanYYC** [freeCodeCamp/freeCodeCamp#35582]
**Describe your problem and how to reproduce it:**
Hi there, I was trying to find a solution to make this challenges work [https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-algorithm-scripting/truncate-a-string](url)
And I went into the solution that wasn't working:
function truncateString(str, num) {
  // Clear out that junk in your trunk
  if (str.length > num && num > 3) {
    return str.slice(0, (num - 3)) + '...';
  } else if (str.length > num && num <= 3) {
    return str.slice(0, num) + '...';
  } else {
    return str;
  }
}
It does not valide the challenge even tho i tried to copy paste it.
I arrived to validate the challenge just by fixing this line in the first if condition : 
//before
 return str.slice(0, (num - 3)) + '...';
//now
 return str.slice(0, (num) + '...';

Idk if the problems comes from the challenge or by the solution but that's how I arrived to fix it and pass the challenge.
**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-algorithm-scripting/truncate-a-string/

**Comment by thecodingaviator** [comment]
Your solution is returning:
![image](https://user-images.githubusercontent.com/34807532/54263874-d8221000-4597-11e9-8178-0857e28195e5.png)
Whereas it should return `A-tisket...`

You're getting confused somewhere, the `...` must not be included in the integer literal count
