### ISSUE TITLE
a problem about "pig Latin"challenge

### ISSUE THREAD

**Issue by controlms** [freeCodeCamp/freeCodeCamp#35580]
there is a problem about "while" in the "Advanced Code Solution"

the loop can't stop when parameter is a word without vowels,such as 
translatePigLatin("glvvv")

the loop (while) cant' stop,i think we should add a restricted condition .

**Comment by RandellDawson** [comment]
Thank you for pointing this out.  This has already been fixed on our `master` branch with a new correct solution for the advanced solution.  It will be moved to production in the near future.  You can see it for yourself on the beta site at:

https://www.freecodecamp.rocks/guide/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/pig-latin
