### ISSUE TITLE
Missing Project Euler Challenges

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#35594]
**Describe the bug**
There are 30 missing challenges in the Project Euler section both locally and on freecodecamp.rocks:

`[8, 9, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]`

I've tried running `npm run clean`, `npm install`, and reseeding the database, but the pages for the above challenges aren't built during `npm run develop`. The challenges aren't shown on the challenge map, and going directly to the URL (http://localhost:8000/learn/coding-interview-prep/project-euler/problem-8-largest-product-in-a-series) shows a 404 page.

One thing I noticed is that hot reloading a challenge causes the page to be built. Even without making any changes in the editor, if I save Problem 8, the challenge will be shown on the on the challenge map and you can navigate to the page. However, if I restart the server, the challenges will be missing until they're hot reloaded again.

The challenge IDs all seems to be unique, and match the ones listed in the Project Euler `meta.json` file.

Do you know what might be going on here @Bouncey, @raisedadead, and @ValeraS?

**Comment by ojeytonwilliams** [comment]
It seems to be happening because the curriculum stops being built once the last file has been read, rather than the last challenge inserted into the curriculum.

I'll dig a little deep and see if I can fix it.

**Comment by scissorsneedfoodtoo** [comment]
@ojeytonwilliams, awesome! Thank you for looking into this.
