### ISSUE TITLE
Please add Angular-Bootstrap-Boilerplate

### ISSUE THREAD

**Issue by filipkappa** [freeCodeCamp/freeCodeCamp#35595]
Please consider adding the [Angular Bootstrap Boilerplate](https://github.com/mdbootstrap/Angular-Bootstrap-Boilerplate) to https://guide.freecodecamp.org/angular/angular-resources/

It's a useful, open-sourced Angular CRUD application starter with NgRx state management and Firebase backend.

**Comment by DMZ011** [comment]
Assigned to Brad plz. @cmccormack

**Comment by cmccormack** [comment]
@filipkappa - please feel free to submit a Pull Request with the content you would like to have added.

[How to work on Guide articles](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-guide-articles.md) 

If you have questions or concerns regarding a Pull Request, please feel free to drop by the [Gitter Contributors channel](https://gitter.im/FreeCodeCamp/Contributors)

I have added the help wanted label as well in case anyone else is interested.

**Comment by Manish-Giri** [comment]
Adding the `first-timers-welcome` label. This looks like a good first PR for a new contributor.

**Comment by guttume** [comment]
Hi. I am new to this. Can I take this on?

**Comment by filipkappa** [comment]
Thanks, @guttume  ;) of course, you can take this on

**Comment by filipkappa** [comment]
I stil do not see it here: https://guide.freecodecamp.org/angular/angular-resources/

**Comment by thecodingaviator** [comment]
@filipkappa We still haven’t deployed the current master to production. It will be done shortly
