### ISSUE TITLE
Markdown Previewer outdated placeholder text

### ISSUE THREAD

**Issue by WofWca** [freeCodeCamp/freeCodeCamp#35615]
**Describe your problem and how to reproduce it:**
GitHub no more continues a numbered list if it's items are preceded by `-` or `*`, but placeholder text in the [code pen](https://codepen.io/freeCodeCamp/pen/GrZVVO) assumes it is true:

> ```
> 1. But the list goes on...
> - Even if you use dashes or asterisks.
> * And last but not least, let's not forget embedded images:
> ```

**Add a Link to the page with the problem:**
[CodePen](https://codepen.io/freeCodeCamp/pen/GrZVVO)
[FCC](https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-markdown-previewer)

Here's a [fixed version](https://codepen.io/anon/pen/LampOw) (updated the "marked" CDN version. Also fixed a couple of typos and removed whitespace).

**Comment by moT01** [comment]
Closing as stale. Thanks and happy coding 🎉
