### ISSUE TITLE
Sample Tech Doc page has incorrect element nesting

### ISSUE THREAD

**Issue by sjroma** [freeCodeCamp/freeCodeCamp#35624]
The Responsive Web Design Projects [Build a Technical Documentation Page](https://codepen.io/freeCodeCamp/full/NdrKKL) sample codepen has
```
<ul> 
    <a class="nav-link" href="#Introduction" rel="internal">
      <li>Introduction</li></a>
</ul>
```
 which throws an error when run through a validator, *The &lt;a&gt; element cannot be a child of the &lt;ul&gt; element*

Browsers do support it but it's still incorrect coding. It would be better to refactor the code to something like;
```
<ul class="nav-link">
  <li>
    <a href="#Introduction"><h3>Introduction</h3></a>
  </li>
</ul>
```
so it follows the HTML spec where only the list element is a direct decendant of the ul element.

**Comment by koop4** [comment]
I can take this one.

**Comment by lasjorg** [comment]
It has been fixed some time ago https://github.com/freeCodeCamp/testable-projects-fcc/pull/750 the Codepen is just not being updated for some reason. I can open an issue and ask if someone can update the Codepen.

**Comment by moT01** [comment]
Looks like this has been fixed so it can be closed - let me know if I'm mistaken.
