### ISSUE TITLE
Make Coding Challenge: "Return a Sorted Array Without Changing the Original Array" accept .slice() to pass tests.

### ISSUE THREAD

**Issue by TimAndreJacobsen** [freeCodeCamp/freeCodeCamp#35645]
Feature Request: Add ``` array.slice() ``` as valid method to clone/copy array and as an alternative to ``` [].concat(array) ```

Link to challenge:
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/return-a-sorted-array-without-changing-the-original-array/

I often use array.slice() to return an array copy, as this is what MDN recommends. When I was working on this challenge I could not get it to pass, even though my solution was returning the correct answer.
The challenge ONLY accepts answers that use the format [].concat(arr). The wording in the challenge is clear, but experience from earlier challenges hava been lenient as long as you provide a valid solution.

Other reasons:
- When googling for array copying the top result from MDN recommends slice.()

- MDN's Array page recommends using arr.slice() for array copying https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

- Personal opinion, ``` arr.slice(0) ``` is more readable than ``` [].concat(arr) ```

**Comment by RandellDawson** [comment]
> The challenge ONLY accepts answers that use the format [].concat(arr). The wording in the challenge is clear, but experience from earlier challenges hava been lenient as long as you provide a valid solution.

You have to also view the test text as part of the instructions for the challenges.  In this case, one of the the challenge test expects you to use the `concat` method.  It even mentions the `concat` method in the Description section of the challenge.  Always read the test text to make sure you understand what is being asked of you.

**Comment by icatat** [comment]
If anyone working on this issue? I would like to take care of this. In my opinion, @TimAndreJacobsen has a point in that the test should allow .slice() if the effect is the same - we know that many times people can solve a problem in multiple ways, and that should be ok. Please let me know. I can  either clarify the text so that the user knows to use concat, or I can modify both the description and the test so that .slice(0) is accepted ( I am inclining more towards the second option though).

**Comment by TimAndreJacobsen** [comment]
I bring it up since alternative solutions has been accepted previously in the corriculum. As long as the final solution is correct.
It was frustrating to have the tests fail even though the output was correct.

**Comment by RandellDawson** [comment]
@TimAndreJacobsen I normally would agree, but the description mentioned `concat` and the test case specifically tells you to use `concat`

**Comment by TimAndreJacobsen** [comment]
Does it have to be specifically .concat() though? The test seems to be about learning mutation and which functions have side effects and how to work around that. We learn about both concat and slice earlier on, and it seems arbitrary to only accept concat.


If the point of the challenge is to learn about concat that's fair. I'd recommend mentioning that .slice() is also an option, but ask to use .concat() still. If the point is avoiding mutation and being aware that certain methods like .sort() will have side effects on the original array. Then I don't understand why it's so strict.

**Comment by RandellDawson** [comment]
@TimAndreJacobsen and @icatat  After thinking a bit more about your points, I agree this challenge could be updated to allow any valid method for copying the array (`arr.slice()`, `[],concat(arr)`, `[...arr]`, `Array.from(arr)`) and other possible ways not mentioned.  While looking at the challenge tests, I also realized someone could still technically hard-code the final return value, so I created a PR (#35801 ) which will address your concerns and attempts to not allow hard coding of the final array returned.
