### ISSUE TITLE
A recommendation on the Zipline CodePen project

### ISSUE THREAD

**Issue by oshliaer** [FreeCodeCamp/FreeCodeCamp#3564]
I use gitter.im like many others on the mobile. It would be great to add advice to use `<meta name = "viewport" content = "initial-scale = 1.0, user-scalable = no">` for settings of projects CodePen.

I think it's simple. It needs just to add an advice to each Zipline.

Motivation:
 - Understanding mobile
 - Additional CodePen
 - Easy (Fancy) preview on mobile

Cheers!

**Comment by SaintPeter** [comment]
What is it that this would do?

**Comment by ltegman** [comment]
Closing as stale. Please feel free to reopen with further details of what benefit this would provide.

Thanks and happy coding!
