### ISSUE TITLE
Need to remove Guide articles for two set Challenges which no longer exist

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#35652]
A while back, PR freeCodeCamp/freeCodeCamp#34717 was merged which combined 3 challenges into a single challenge, but the corresponding Guide articles were never removed.

I am only talking about the English versions, because at this point, the other languages for the 2 challenges are still present in the repo.  

@raisedadead I can easily remove the English Guide articles for the two challenges which no longer exist.  The question is, should I create 5 other separate PRs to do the following to each **non-English version**:

1. Delete the other two challenges and re-translate the `Create a Set Class` challenge
2. Delete the two Guide articles for the challenge
3. Re-translate the corresponding Guide article for the `Create a Set Class` challenge

I ask this question, because I am not sure if the current curriculum is going to even be translated and moved to production since the new curriculum direction has started.  Please advise so I don't waste time making translations. 

On a side note, if the non-English versions of the current curriculum will never make it to production, should we just go ahead and do a mass merge of any non-English curriculum and curriculum related Guide articles (without merge conflicts) and close the rest?

**Comment by moT01** [comment]
I think I would focus on English stuff.

**Comment by raisedadead** [comment]
I agree with Tom here.

**Comment by RandellDawson** [comment]
Actually, this issue has been resolved due to https://github.com/freeCodeCamp/freeCodeCamp/pull/35921 being merged.
