### ISSUE TITLE
Test for Calculator in Front-End Libraries projects is broken

### ISSUE THREAD

**Issue by Beachhermit** [freeCodeCamp/freeCodeCamp#35651]
**Describe your problem and how to reproduce it:**
The tests from the script that is pre-loaded in the Codepen template are wrong for the Front-End Libraries calculator project. The first few are fine, but from the middle of the list, several are repeats of each other and several from the project page are missing.
I’ve attached a screenshot so you can see that tests 7 and 8 describe exactly the same test, but one passes and one doesn’t.

All up, tests 7 and 8 in the feedback both describe user story 7, as shown on the project page. US8 is missing.
Tests 9, 10 and 11 describe US9. US10 and 11 are missing.
Tests 12, 13 and 14 describe US12 with 13 and 14 missing
Tests 15, 16 and 17 describe US15 - there is no corresponding US 16 and 17.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-javascript-calculator/

https://codepen.io/freeCodeCamp/pen/MJjpwO

**Tell us about your browser and operating system:**
* Browser Name:  Chrome
* Browser Version: Version 72.0.3626.121 (Official Build) (64-bit)
* Operating System:  Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![repeatTests](https://user-images.githubusercontent.com/15227267/54790300-bf95b200-4c89-11e9-8f2e-2ac386760d90.png)

**Comment by Beachhermit** [comment]
I've just gone and done some more digging. I ran the tests on a blank page and they look right. So, perhaps there's something in the code that I've written so far that is running interference.
So I checked my code again - thinking I could copy that here so you could see where the interference was BUT the tests look like they're working properly again.
The last thing I was fiddling with before I went to bed last night was a regex to test for an operator at the end of the input.

So, I figure at the very least you have a problem here with code that is vulnerable to being manipulated by the code it is testing. Hope that helps.

**Comment by RandellDawson** [comment]
@tbushman Is this an issue with the tests or the camper's code?

**Comment by moT01** [comment]
Can you provide any more details about this @Beachhermit? - like what code you were using that was causing the issue?

**Comment by Beachhermit** [comment]
Not really. I was having the problem, asked about it on the forum, was told to report it here, reported it, then it came good. The only clue I had was that I'd been working on a regex at the time to parse the input to the calculator and pick out operators from numbers. In the end, I went with a completely different system that processed input as it was entered.

I've been doing the d3 projects (which have their own problems with the test suite, that I just work around) for the last month or so, so all this is pretty distant memory and I don't save intermediate versions or anything super organised like that.

**Comment by moT01** [comment]
Thanks for reporting this but since we can't figure out what caused the problem or reproduce it - I think we can close it.
