### ISSUE TITLE
'Run the Tests button' is not working & result pane is showing 'Error: Request errror: 0'

### ISSUE THREAD

**Issue by SuryaDilip** [freeCodeCamp/freeCodeCamp#35657]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by thecodingaviator** [comment]
Please add more details about which link is this problem on and screenshots if possible

**Comment by SuryaDilip** [comment]
I'm pursuing 'Responsive Web Design Certification (300 hours)' course. 

When i click on an exercise, say 'https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements' then i find this button not working. 

![Run the Tests](https://user-images.githubusercontent.com/28861793/54995243-4c26d400-4fec-11e9-938a-2629122a47c8.JPG) 

When the page is loaded i can find this error (highlighted with the yellow marker).

![Responsive Web Design Certification (300 hours)](https://user-images.githubusercontent.com/28861793/54995469-ce16fd00-4fec-11e9-9787-0c5996ac24f1.jpg)

Please help.

**Comment by thecodingaviator** [comment]
@SuryaDilip Can you please provide a screenshot of your developer console? Press `F12` if you're in Chrome to open it

**Comment by SuryaDilip** [comment]
Is this the right screenshot?
![Developer Tools](https://user-images.githubusercontent.com/28861793/55011508-fa8e4180-500b-11e9-91b5-08d8126ebdd8.jpg)

**Comment by thecodingaviator** [comment]
Nope @SuryaDilip click on console next to elements and paste the screenshot
![image](https://user-images.githubusercontent.com/34807532/55012106-e9920000-500c-11e9-9d48-f802b979ecc3.png)

**Comment by SuryaDilip** [comment]
PFA

![Untitled](https://user-images.githubusercontent.com/28861793/55065279-89996900-50a1-11e9-9019-82acbc101ca0.jpg)

**Comment by thecodingaviator** [comment]
Your browser is blocking jQuery. If you type:
`$('.btn')`
as is into the console and press enter, do you see:
`<button type="button" class="btn btn-primary btn-block">Run the Tests</button>`
?

**Comment by SuryaDilip** [comment]
![Capture](https://user-images.githubusercontent.com/28861793/55075541-3a5f3280-50b9-11e9-97c5-be1ec1868fbc.JPG)

**Comment by thecodingaviator** [comment]
@ValeraS I was thinking this might be due to jQuery being blocked by the browser, but that, clearly, is not the case, any idea what might be up?

**Comment by ValeraS** [comment]
1. `$`is not always equal to jQuery. What you see is Chrome dev-tools [Console Utilities API](https://developers.google.com/web/tools/chrome-devtools/console/utilities)

2. To check jQuery you need to select JavaScript context:
![image](https://user-images.githubusercontent.com/10867286/55078977-54dedf00-50ac-11e9-9b93-ec9f34103f85.png)
![image](https://user-images.githubusercontent.com/10867286/55078936-45f82c80-50ac-11e9-95f2-61107c8e346b.png)

@SuryaDilip Could you check beta site https://freecodecamp.rocks/learn/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements Does it work for you?

**Comment by SuryaDilip** [comment]
@ValeraS I'm using the website on my office laptop. I tried the website on other PC which is on different N/W. There it is working as expected. Is this some kind of block on the website in my office N/W.

**Comment by SuryaDilip** [comment]
@ValeraS https://www.freecodecamp.rocks/ is blocked on my office N/W

**Comment by moT01** [comment]
Since this seems to be a issue with your network and not freeCodeCamp, I don't think there's anything we can do here. Thanks for reporting the issue @SuryaDilip, but I am going to close it - If I am mistaken, feel free to reopen it.
