### ISSUE TITLE
Apis and Microservices Projects - No tests applied after submitting solution

### ISSUE THREAD

**Issue by christophrus** [freeCodeCamp/freeCodeCamp#35661]
**Describe your problem and how to reproduce it:**
Im currently working on the Apis and Microservices Projects and wondering why there arent any test applied once I submit the solution. I can literally submit any valid URL (i.e. https://google.de) and it will be accepted.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice and all other projects in this section.

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 73.0.3683.86
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by christophrus** [comment]
I can see [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/timestamp-microservice.english.md) that there are tests set up at least for the first project. But why dont these tests run? Are they deactivated manually somewhere else?

**Comment by RandellDawson** [comment]
Closing this issue as it has already been reported on issue https://github.com/freeCodeCamp/freeCodeCamp/issues/17548
