### ISSUE TITLE
Poll Stripe API for no of donators

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#35669]

**Comment by moT01** [comment]
Is this issue still necessary @raisedadead? I assume you created it to remind yourself.

**Comment by raisedadead** [comment]
> Is this issue still necessary [...]

Yes. Its an internal task for the dev team. ATM, the donor no on the landing page is not real time.

**Comment by raisedadead** [comment]
Not needed any more.
