### ISSUE TITLE
Bug in 2nd test for Access Multi-Dimensional Arrays With Indexes challenge

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#35665]
I see an issue related to the mal-formed 2nd test of this challenge at least once a day on the forum.  An example is [this thread](https://www.freecodecamp.org/forum/t/bracket-notation-in-accessing-multi-dimensional-arrays-with-indexes/266940).

At some point, someone thought and second condition was needed in the assert statement to catch someone trying to solve the challenge by hard-coding the answer like:
```js
var myData = 8;
```
OR
```js
var myData = 3 + 5;
```

It could just be me, but there really is only one way to solve this challenge:
```js
var myData = myArray[2][1];
```
or some variation of the above with white space or leaving off the semi-colon.

Why would the following `testString` not suffice based on the test `text`?  
```yml
assert(/myData=myArray\[2\]\[1\]/.test(code.replace(/\s/g, ''));
```

I was also thinking maybe the `text` could be modified to the following, to make it even more clear:
```yml
  - text: You should only use bracket notation to read the correct value from <code>myArray</code>.
```

At this point, I am looking for feedback.  Once we decide the best course of action, I will add the `first timers welcome` label as it should literally be a copy/paste of the assert we come up with here.

**Comment by Nirajn2311** [comment]
@RandellDawson you're right that's the only way to answer that question with some exceptions in semicolon. 
Your regex for the second test will work without any problems so I think we can put the `first timers welcome` badge.
Also I don't think it will make much of a difference in changing the text of the test as the challenge teaches how to use bracket notation and the user has to practice it. But there's no problem in changing the text if you think it's right.

**Comment by RandellDawson** [comment]
@Nirajn2311 Yes, I think you are right about just leaving the `text` the same.

**Comment by RandellDawson** [comment]
OK, it seems like we have agreement on the assert to use.  Who wants to work on this?  We would prefer first timers, but if no one volunteers in the next couple of days, then anyone can work on it.

**Comment by Artistic18** [comment]
Hello! This is my first time with Open Source. So, if possible can you please elaborate the issue in simpler words.

**Comment by Artistic18** [comment]
Do you mean I should change the **testcase** from 
>testString: assert(/myArray\[2\]\[1\]/g.test(code) && !/myData\s*=\s*(?:.*[-+*/%]|\d)/g.test(code)

to

>assert(/myData=myArray\[2\]\[1\]/.test(code.replace(/\s/g, ''));

**Comment by RandellDawson** [comment]
@Artistic18 Yes, that is all that needs to be done at this time.
