### ISSUE TITLE
Freecodecamp becomes unresponsive and freezes the browser

### ISSUE THREAD

**Issue by Donearm** [freeCodeCamp/freeCodeCamp#35660]
**Describe the bug**
This happened here and there during the curriculum but last occurrence that I cannot fix it myself is at the React portion of it. Just adding a new component, empty at the moment, freezes the whole browser. Restarting it lose any code added and then it is impossible to proceed with the challenge

**To Reproduce**
1. Go to https://learn.freecodecamp.org/front-end-libraries/react/review-using-props-with-stateless-functional-components/?run=disabled
2. Try to extend CampSite component
3. After writing any part after the first curly braces, the CPU usage spikes to 70-80% and memory goes up to 80-85% occupied
4. Browser freezes

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser Firefox but tested also in Chrome and same issue
 - Version 66

**Additional context**
As you can see, I've already tried with the "?run=disabled" in the url without avail. Cleared all cookies and offline content in the browser too.

**Comment by Nirajn2311** [comment]
@Donearm could you check if this issue is present for you in the beta site - www.freecodecamp.rocks

**Comment by Donearm** [comment]
Can't even log in, error 400: redirect_uri_mismatch (I'm logging in through Google)

**Comment by Nirajn2311** [comment]
@Donearm the beta site doesn't support login and also the progress of your challenges done in beta site won't be added to the main site. Check #34872 for more details of the beta site.

**Comment by Donearm** [comment]
Ok, wasn't aware there was a beta site. Anyhow, same freezing of the browser with the beta one too, at the same challenge and typing the same code (or trying to actually).

**Comment by ojeytonwilliams** [comment]
@Donearm I'm having trouble reproducing this.  Could you tell me which edits you made to trigger the freeze?

**Comment by Donearm** [comment]
@ojeytonwilliams simply extending the CampSite component thus

```js
class Camper extends CampSite {
render() {
}
}
```

That's the bare minimum that cause the freeze (after the curly brackets of render). Alternatively I tried with the constructor but it also freezes after the curly braces.

**Comment by ValeraS** [comment]
@Donearm Why do you extend CampSite? You should extend React.Component.

**Comment by ojeytonwilliams** [comment]
@Donearm Sorry, I can't seem to replicate it.  I'm using Ubuntu 18.10 (Cosmic Cuttlefish) with Chrome 73.0.3683.86 and Mozilla Firefox 66.0.1 and neither freezes when that code is entered.

**Comment by Donearm** [comment]
@ojeytonwilliams tried again with Firefox 66.0.2 on Archlinux (kernel 5.0.5) and same freeze. This happened with a few challenges before, here and there, but I always managed to wait a minute or 2 and it recovered but for this one.

**Comment by srazdan4** [comment]
Have you tried running it on a different laptop altogether?

**Comment by Donearm** [comment]
I've tried on my desktop and after a little more than 1 minute the browser becomes responsive again. Probably due to the desktop being much faster than the laptop, eventually the script blocking the browser exits while on the laptop it takes too long to notice it.

But the issue is on the desktop too, definitely.

**Comment by moT01** [comment]
This seems to be pretty isolated. I did not have any freezing issues, but I did get a unique error on production/chrome...

<img width="524" alt="Screen Shot 2019-05-03 at 10 28 57 AM" src="https://user-images.githubusercontent.com/20648924/57147982-562bb780-6d8e-11e9-85af-4d37f431740a.png">

beta had a traditional failed test error.

@Donearm there was a recent fresh deployment of the beta site, do you think you can check one more time there? https://www.freecodecamp.rocks/learn/front-end-libraries/react/review-using-props-with-stateless-functional-components - Thanks! (fingers crossed)

**Comment by Donearm** [comment]
@moT01 tried it and it has a very short freeze, like 2 seconds, and then the browser's window is responsive again. It is doable now. Besides, I believe it has to do with the browser's profile as out of curiosity I tried yesterday with a fresh Firefox profile and there is no freeze at all.

**Comment by moT01** [comment]
I have had issues with extensions or add-ons to firefox affecting the website. You could try disabling them. Since nobody else can replicate this, I'm not sure how much it's worth continuing to look into it. I think we can probably close this.

**Comment by Donearm** [comment]
With the fresh profile, no addons at all, there's no freeze with the beta site so it's either something in the stable site and/or the profile got corrupted. Time to close.
