### ISSUE TITLE
Make other ways to donate expandable on the donation page instead of a separate page

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#35667]

**Comment by webdevdaemon** [comment]
I'd like to work on this issue. It's still available, correct? It looks like it is.

Anyways, I am thinking about using an accordion or tabbed sections to implement this on the donate page. I'd separate each entry by the Headings/Sections present in the source for the DonateOtherPage component. It's never that simple, but I think that's a solid starting point at least. 

Any Input, Suggestions, Guidance, Requirements, etc?

**Comment by raisedadead** [comment]
I think we would want to be able to click the link at the bottom of the current donate page and render the currently separate page content on the same page replacing the donate form.

**Comment by webdevdaemon** [comment]
OH, OK... I see. I will head in that direction then. Thank you.

**Comment by webdevdaemon** [comment]
Submitted a PR for this issue just now. I can haz feedback?

#36137
