### ISSUE TITLE
Addition of Guides on Static Site Generator

### ISSUE THREAD

**Issue by iamrajiv** [freeCodeCamp/freeCodeCamp#35670]
**Describe your problem and how to reproduce it:**

I have gone through the Guides of freeCodeCamp and I think there should be Guides on Some Static Site Generator like Hugo, Jekyll, Next, Hexo etc

The Guides have already Gatsby.js which is also used to generate static site

**Comment by iamrajiv** [comment]
If this issue is Valid and Valuable, I want to take this issue and Work on this

**Comment by RandellDawson** [comment]
Hi @iamrajiv 

I think it is fine to do that.  If you really want to do it write, I would suggest first creating a new article on Static Site Generators that would be located at `guide/english/static-site-generators/index.md`.  Then, in the same PR, I would suggest moving the existing `guide/english/gatsbyjs/index.md` to be a sub folder of the `static-site-generators/` folder you create like `guide/english/static-site-generators/gatsbyjs/index.md`.  Then, you contributors can create other folders/files like:
```
guide/english/static-site-generators/hexo/index.md
guide/english/static-site-generators/hugo/index.md
guide/english/static-site-generators/jekyll/index.md
guide/english/static-site-generators/next/index.md
```
However, please do a quick search of the repo to see if you can find existing articles which may already cover these.  In fact, before creating a PR, I suggest you document here where you find any of these and we will figure out the best strategy of how to organize everything.

**Comment by iamrajiv** [comment]
thanks, @RandellDawson for the suggestion, Yup making a separate folder for the static site generators is a good idea. I am going through the Guides and will be documenting these very soon

**Comment by moT01** [comment]
Any progress on this @iamrajiv?

**Comment by iamrajiv** [comment]
@moT01 yeah I have gone through the guides  I think the only static site generator based file in freeCodeCamp is `gatsbyjs` I am working on to add more guides on static site generator like `hugo` and `jekyll` I will make PR tomorrow

**Comment by moT01** [comment]
Take the time you need. It was just a while since any activity here so I thought I would check in.
