### ISSUE TITLE
Link in "Generate Random Fractions with JavaScript" challenge leads to 404

### ISSUE THREAD

**Issue by coinfreakgr** [freeCodeCamp/freeCodeCamp#35672]
**Describe your problem and how to reproduce it:**

Just visit this page here:

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/generate-random-fractions-with-javascript

 and click the "Storing Values with the Equal Operator" link. It leads to a 404 page.

The correct link should be this one:

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/storing-values-with-the-assignment-operator/

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 72.0.3626.121
* Operating System: Mac OS 10.14.3

<img width="1185" alt="freeecodecamp" src="https://user-images.githubusercontent.com/32580948/54896403-b47e9400-4ecc-11e9-8367-8c8c92646ef9.png">

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Nirajn2311** [comment]
@coinfreakgr can you check if this issue is there in our beta site - www.freecodecamp.rocks

**Comment by thecodingaviator** [comment]
Problem not replicable in the latest build of rocks. I'm closing this issue. @coinfreakgr the fix would soon be shipped to production. Thanks for opening the issue
