### ISSUE TITLE
Developer ethics/case studies links are broken 

### ISSUE THREAD

**Issue by wang1998tina** [freeCodeCamp/freeCodeCamp#35678]
**Describe your problem and how to reproduce it:**
Clicking on any of the case study links under the developer ethics guide in ~any language~ will all lead to the Software Engineering Ethics Research Institute (SEERI) homepage. 

**Add a Link to the page with the problem:**
[For example, in Arabic:](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/arabic/developer-ethics/case-studies/index.md)

**Tell us about your browser and operating system:**
* Browser Name: 
Chrome
* Browser Version: 
* Operating System: 
Mac OS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screen Shot 2019-03-25 at 12 40 50](https://user-images.githubusercontent.com/31293868/54937696-48675480-4efb-11e9-8460-25c2dcea94d8.png)
It seems as if the Ethical Cases tab on their website is the issue...this was probably where the case studies used to live but has since been replaced by an empty template.

I can hop onto this issue if y'all have ideas on how to proceed - find new case studies or get rid of these links?

**Comment by thecodingaviator** [comment]
@wang1998tina I'd say google the links, maybe they've moved to a new place. If you cannot find anything, I think we would need new links but also some discussion on the issue before we change links to new studies. Go ahead and take this up if you want

**Comment by sil3nthill** [comment]
i am a first timer contributor i would like to fix this if you can just show where to begin

**Comment by thecodingaviator** [comment]
@sil3nthill We'd absolutely welcome you help on this issue but we're waiting for a reply from @wang1998tina . In the meantime, have a look [here](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22first+timers+welcome%22) and check for issues which do not already have a PR made. Also make sure you read out contributor's documents properly in the /docs directory.

**Comment by wang1998tina** [comment]
Okay, I will look into this!

**Comment by wang1998tina** [comment]
@thecodingaviator It seems that the case studies are no longer on the site, but I've found a list of similar case studies at another [research institute](https://www.scu.edu/ethics/focus-areas/more/engineering-ethics/engineering-ethics-cases/computer-engineering-cases/). Also, the first link on the page also seems as if it's supposed to lead to an ethics code, but that has [moved to this page](https://www.etsu.edu/cbat/computing/seeri/ethics-code.php)

**Comment by thecodingaviator** [comment]
@wang1998tina If the new links look fine to you, go ahead and make **different PRs for each language** and replace the links

**Comment by wang1998tina** [comment]
English links are in the pull request below, but if approved, translations will be needed!

**Comment by RandellDawson** [comment]
@wang1998tina We are no longer excepting translations for the existing curriculum, so don't worry about creating PRs for the other languages.
