### ISSUE TITLE
Add guide article for new challenge

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35676]
This PR (https://github.com/freeCodeCamp/freeCodeCamp/pull/35301) added a new challenge so we need to create the associated guide article in this area of the code: https://github.com/freeCodeCamp/freeCodeCamp/tree/master/guide/english/certifications/responsive-web-design/basic-html-and-html5

@lasjorg, you expressed interest in this - not sure if you started working on it yet. Let us know if you want to do it or not, or if you need any help. If you don't want to actually write the article you could just create the file and place the "stub text" in it.

**Comment by lasjorg** [comment]
@moT01 I will give it a go.

**Comment by lasjorg** [comment]
@moT01 How do I preview the guide locally? I get a 404 on all guides when I try to view them locally.

**Comment by RandellDawson** [comment]
@lasjorg You will temporarily need to copy `guide/english/certifications` to `mock-guide/english/certifications` and then run `npm run develop`

**Comment by lasjorg** [comment]
@RandellDawson Thanks for the info. Should the guide instructions not have this information? I don't think I saw this mentioned anywhere.

**Comment by RandellDawson** [comment]
@lasjorg Probably should be in the instructions.
