### ISSUE TITLE
Basic Javascript: Use the parseInt Function link broken

### ISSUE THREAD

**Issue by SuperSafie** [freeCodeCamp/freeCodeCamp#35686]
When clicking on the "Get a hint" button it takes you to a stub that has been archived by the owner. I would like to create a guide for this problem if possible, but am a beginner and don't know how to create a new stub. 

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/use-the-parseint-function

* Browser Name: Google Chrome
* Browser Version: Version 72.0.3626.121
* Operating System: Mac OS High Sierra

**Comment by RandellDawson** [comment]
Hi @SuperSafie 

Thanks for noticing this.  However, it has already been fixed on our `master` branch, but has not been moved to production.

You can check the beta site which is a mirror of the current `master` branch, to see that the link works.

We are in the process of moving many fixes to production in the near future.

I am closing this issue for now.

Thank you.
