### ISSUE TITLE
Code passes but continuation popup doesn't load

### ISSUE THREAD

**Issue by techimunchi** [FreeCodeCamp/FreeCodeCamp#3569]
Challenge [Bonfire: Falsy Bouncer](http://www.freecodecamp.com/challenges/bonfire-falsy-bouncer) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
bouncer = function(deleteValue) {
  for (var i = 0; i < this.length; i++) {
    if (this[i] == deleteValue) {         
      this.splice(i, 1);
      i--;
    }
  }
  return this;
};


bouncer([7, "ate", "", false, 9], "");

```

![untitled](https://cloud.githubusercontent.com/assets/13052104/10254449/58d82cb2-6909-11e5-9535-149711f9e220.png)

I've left it loading for days and it never processes.

**Comment by ltegman** [comment]
This code should not pass and it doesn't when I run it in my browser. You're performing actions on and returning `this` when you should be using deleteValue. `this` is a variable that holds the bouncer function you are inside of, not the array being passed in.
