### ISSUE TITLE
Fixing test descriptions in Quality Assurance and Testing with Chai

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#35694]
The test descriptions in the `Quality Assurance and Testing with Chai` section are unclear, vague and grammatically incorrect. One example can been seen [here](https://github.com/freeCodeCamp/freeCodeCamp/pull/35471#discussion_r268825980).

These test descriptions need to be fixed to make more sense

**Comment by JulianNF** [comment]
Hi,

Re-posting here as per the suggestion of @thecodingaviator from a related issue that I opened here: #35730.

For ease, here's the quoted content that I submitted in that issue:

> Hiya,
> 
> Reporting that there are contradictory instructions in the challenge "Quality Assurance and Testing with Chai - Run Functional Tests using a Headless Browser".
> 
> Link to challenge: https://learn.freecodecamp.org/information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-using-a-headless-browser/
> 
> Towards the top of the exercise, the instructions ask the user to test submitting for Cristoforo Colombo:
> 
> ```
> test('submit "surname" : "Colombo" - write your e2e test...', function(done) {
>   // fill the form...
>   // then submit it pressing 'submit' button.
>   //
>   // in the callback...
>   // assert that status is OK 200
>   // assert that the text inside the element 'span#name' is 'Cristoforo'
>   // assert that the text inside the element 'span#surname' is 'Colombo'
>   // assert that the element(s) 'span#dates' exist and their count is 1
> ```
> 
> However, in the area where the user/student is supposed to add their assertions, the "inline" instructions ask the user to test against Marco Polo:
> 
> ```
> // assert that the text inside the element 'span#name' is 'Marco'  <== BUG: This should say, 'Cristoforo'
> 
> // assert that the text inside the element 'span#surname' is 'Polo'  <== BUG: This should say, 'Colombo'
> ```
> 
> Let me know if there is anything else I can do.
>

**Comment by ranched** [comment]
The change regarding the challenge 'run-functional-tests-using-a-headless-browser' seems it would be better made to the repo holding the boilerplate for the challenge '[freeCodeCamp/boilerplate-mochachai](https://github.com/freeCodeCamp/boilerplate-mochachai)'. That is where the referenced lines with 'Marco' and 'Polo' are used [2_functional-tests.js](https://github.com/freeCodeCamp/boilerplate-mochachai/blob/de93d44be284f35b46695c8ce9e0c1e1444f85ed/tests/2_functional-tests.js#L244-L246). 

Seems it was just a mistake in that comment. In 'freecodecamp/freecodecamp' all language curriculum files have the name is set as 'Cristoforo' and 'Colombo' in the test files. I can create a new pull request in the 'boilerplate-mochachai' repo for the change to be made.  

Let me know what you think.

**Comment by JulianNF** [comment]
I think the best to correct is the boilerplate code as the two sets of instructions within the boilerplate code contradict each other.

I say go ahead with the pull request.

(tnx!)

**Comment by ranched** [comment]
I created a pull request on the [freeCodeCamp/boilerplate-mochachai](https://github.com/freeCodeCamp/boilerplate-mochachai) repo for the corrections to the instructions referenced in [#35730](https://github.com/freeCodeCamp/freeCodeCamp/issues/35730). Let me know if there are any more changes required to this repo.
