### ISSUE TITLE
Create style element, all test pass except "create style element" 

### ISSUE THREAD

**Issue by coderstravel** [freeCodeCamp/freeCodeCamp#35712]
![free](https://user-images.githubusercontent.com/29521885/55282135-970a5980-5314-11e9-92b9-d7dc1f4186d2.PNG)

**Describe your problem and how to reproduce it:**
Create style element, all test pass except "create style element"

**Add a Link to the page with the problem:**
https://www.freecodecamp.rocks/learn/responsive-web-design/basic-css/use-css-selectors-to-style-elements

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 
User Agent is: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by thecodingaviator** [comment]
Please add screenshots of the code you are using for the challenge

**Comment by RandellDawson** [comment]
I can confirm the bug exists on the beta site (freecodecamp.rocks).  This bug was fixed on the `master` branch 4 days ago.  I tested it locally just now and the same code passes with no issues.  

I assume `master` has not been deployed to the beta site in the last 4 days.

@raisedadead, @Bouncey Can anyone confirm this?  Also, is there a way to maybe put a date/time a the bottom of the beta showing when it was updated, so we can confirm these kinds of issues?

**Comment by Suyash2810** [comment]
Yes the problem still exists on the beta site and if the problem has been rectified in the master it hasn't been deployed to the beta site.
![Screenshot (266)](https://user-images.githubusercontent.com/42000949/55293156-e0d86a00-5410-11e9-94fc-922492bae651.png)

**Comment by moT01** [comment]
This appears to no longer be an issue on beta (or production). So I think it's safe to close this. If I'm wrong, go ahead and reopen it.

<img width="831" alt="Screen Shot 2019-05-03 at 9 15 21 AM" src="https://user-images.githubusercontent.com/20648924/57143347-4c9d5200-6d84-11e9-9567-91fb88c85964.png">

However, you can see in the image that the test that must have been added to fix this passes with the default seed code. No style element was added, but the test passes. So I am going to create a new issue to resolve that.
