### ISSUE TITLE
#996icu https://github.com/996icu/996.ICU

### ISSUE THREAD

**Issue by ClrsDream** [freeCodeCamp/freeCodeCamp#35718]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by thecodingaviator** [comment]
Please add more context to issue and reopen it. I'm closing it since it does not have any content
