### ISSUE TITLE
Please add an "abandon 996" badge to support us

### ISSUE THREAD

**Issue by bofeiw** [freeCodeCamp/freeCodeCamp#35717]
[Chinese software engineers are protesting against the country ’ s 996 work schedule.](https://996.icu/#/en_US)
An unleagal work schedule (9a.m. ~ 9p.m., 6 days a week) .

Add a badge
---
Add a badge to your awesome project by pasting this line in your README.md.

```html
<a href="https://996.icu"><img src="https://img.shields.io/badge/link-996.icu-red.svg"></a>
```
<a href="https://996.icu"><img src="https://img.shields.io/badge/link-996.icu-red.svg"></a>

Working Men of All developers, Unite!

**Comment by thecodingaviator** [comment]
Please get across to @QuincyLarson with this, he'll be able to provide a better answer on whether we should or not
