### ISSUE TITLE
[beta] Challenge instruction drops to a new line mid-sentence

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#35727]
**Describe your problem and how to reproduce it:**

Go to challenge `Basic JavaScript: Global Scope and Functions`.

The instruction's last sentence breaks to a new line mid-sentence.

(This issue does not exist in production: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/global-scope-and-functions/ )

**Add a Link to the page with the problem:**

https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/basic-javascript/global-scope-and-functions

**Tell us about your browser and operating system:**
* Browser Name:
* Browser Version:
* Operating System:

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

<img width="711" alt="Screen Shot 2019-04-01 at 11 13 05 AM" src="https://user-images.githubusercontent.com/25715018/55303238-2af03880-546f-11e9-8bc9-d8571b053992.png">

**Comment by RandellDawson** [comment]
It has something to do with the **space** between the `</coding`> and another tag like <strong> (or any other tag for that matter).  Locally, when I tested removing the space and leaving the `<strong>` tag or leave the spacing and remove both the `<strong>` and `<em>` tags, it does not wrap around to the next line.  Then, I tried the following and both of these still resulted in the text wrapping to the next line.
```
Inside function <code>fun1</code>, assign <code>5</code> to <code>oopsGlobal</code> <i>without</i> using the <code>var</code> keyword.
```
```
Inside function <code>fun1</code>, assign <code>5</code> to <code>oopsGlobal</code> <span>without</span> using the <code>var</code> keyword.
```

**Comment by ojeytonwilliams** [comment]
@RandellDawson I'm happy to take a look at this, but there is a risk that even a good change to the markdown parser could create issues in currently fine challenges. Do you think using Jest to create snapshots of the challenges is feasible?  I'd want some way of making sure that I didn't create more problems than I solved!
