### ISSUE TITLE
Travis CI false positives

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#35729]
**Describe the bug**
Certain syntax errors in challenge markdown are incorrectly passed by Travis CI.  [This build](https://travis-ci.com/ojeytonwilliams/freeCodeCamp/builds/106547060) is an example that should fail, but does not.

**To Reproduce**
1. Put a syntax error into challenge markdown - I tested this by indenting `testString` with 5 spaces instead of 4 in `curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-arrow-functions-to-write-concise-anonymous-functions.english.md`
2. `npm run test`
3. This will throw an error, but the testing never finishes.
4. Push to GitHub and trigger a Travis build.
5. This should not pass, but does.

**Expected behavior**
If the local `npm run test` fails, so should Travis.

While waiting for the builds to finish, I did a little digging.  It looks like the bad YAML causes an exception that stops the tests from starting properly.  I'd be happy to try and sort this out.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.10 (Cosmic Cuttlefish)

**Comment by raisedadead** [comment]
Maybe we can enhance the linting tests a bit more, which could error out early before running the tests

**Comment by ojeytonwilliams** [comment]
@raisedadead What I've found so far is that the error is happening before the tests, but it's not handled properly.  Rather than causing the tests to fail they never really happen.

I agree that catching it in the linting stage would be ideal, but I still think there should be a fail-safe.  If the build fails, then the tests should fail too.

**Comment by raisedadead** [comment]
If the build fails, we should exit with the error code 1. That should allow us to prevent going into the next stage.
