### ISSUE TITLE
Contradictory Instructions - Quality Assurance and Testing with Chai - Run Functional Tests using a Headless Browser

### ISSUE THREAD

**Issue by JulianNF** [freeCodeCamp/freeCodeCamp#35730]
Hiya,

Reporting that there are contradictory instructions in the challenge "Quality Assurance and Testing with Chai - Run Functional Tests using a Headless Browser".

Link to challenge: https://learn.freecodecamp.org/information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-using-a-headless-browser/

Towards the top of the exercise, the instructions ask the user to test submitting for Cristoforo Colombo:

```
test('submit "surname" : "Colombo" - write your e2e test...', function(done) {
  // fill the form...
  // then submit it pressing 'submit' button.
  //
  // in the callback...
  // assert that status is OK 200
  // assert that the text inside the element 'span#name' is 'Cristoforo'
  // assert that the text inside the element 'span#surname' is 'Colombo'
  // assert that the element(s) 'span#dates' exist and their count is 1
```

However, in the area where the user/student is supposed to add their assertions, the "inline" instructions ask the user to test against Marco Polo:

```
// assert that the text inside the element 'span#name' is 'Marco'  <== BUG: This should say, 'Cristoforo'

// assert that the text inside the element 'span#surname' is 'Polo'  <== BUG: This should say, 'Colombo'
```

Let me know if there is anything else I can do.

**Comment by thecodingaviator** [comment]
I guess this PR adds to #35694 . A PR has been made on #35724, please make this comment there and request changes

**Comment by JulianNF** [comment]
Thanks thecodingaviator - will cross-post there as well.

**Comment by madurachanna** [comment]
Thanks thecodingaviator

**Comment by madurachanna** [comment]
Thanks thecodingaviator

**Comment by madurachanna** [comment]
Thanks thecodingaviator

**Comment by madurachanna** [comment]
Thanks thecodingaviator

**Comment by madurachanna** [comment]
Thanks thecodingaviator

**Comment by madurachanna** [comment]
Thanks thecodingaviator

**Comment by madurachanna** [comment]
Thanks thecodingaviator

**Comment by madurachanna** [comment]
guess this PR adds to #35694

**Comment by ranched** [comment]
After looking at this and [#35694](https://github.com/freeCodeCamp/freeCodeCamp/issues/35694) it seemed the error referenced here was in the 'boilerplate-mochachai' repo and not the curriculum repo so submitted a PR on the 'boilerplate-mochachai' repo with a fix.

**Comment by huyenltnguyen** [comment]
Closing as the issue has been resolved via https://github.com/freeCodeCamp/boilerplate-mochachai/pull/13

**Comment by NikulGoyani369** [comment]
```
suite('Headless browser', function () {
    test('should have a working "site" property', function() {
      assert.isNotNull(browser.site);
    });
  });

  suite('"Famous Italian Explorers" form', function () {
    // #5
    test('submit "surname" : "Colombo" - write your e2e test...', function(done) {
      browser.fill("surname", "Colombo").then(
        browser.pressButton("submit", function() {
          browser.assert.success();
          browser.assert.text('span#name', 'Cristoforo');
          browser.assert.text('span#surname', 'Colombo');
          browser.assert.elements('span#dates', 1);
          done();
        })
      );
    });
```
