### ISSUE TITLE
Having an issue with http://freecodecamp.com/challenges/waypoint-nest-an-anchor-element-within-a-paragraph

### ISSUE THREAD

**Issue by Cartobob** [FreeCodeCamp/FreeCodeCamp#3573]
![1](https://cloud.githubusercontent.com/assets/14951228/10262908/4f013a30-69f9-11e5-91cb-436be303bef4.png)

I dont see why this is showing up as an error. My p element does have View more with a space after it!

**Comment by wcountiss** [comment]
Seems to be working fine.  Double check your spacing.
![image](https://cloud.githubusercontent.com/assets/7219453/10263109/4d483062-69af-11e5-8e0b-490b57dd5783.png)

**Comment by Cartobob** [comment]
Yes, I missed the the fact that there was a space between <p> and View. But I dont know why this should matter.. Thanks for pointing it out though!

**Comment by Pioneer11X** [comment]
Hey, It is indeed not working if the text "View more <with a space>" and the href tag are in different lines, as it should. Please check.

**Comment by RAJAT--PALIWAL** [comment]
This test case fails because above <p> tags have "Kitty ipsum" text inside it, while test requires <p> tag should have "View more " inside it.

<p class="red-text">View more </p>
<p class="red-text">View more </p>

<p>View more <a href="http://www.freecatphotoapp.com"> cat photos</a></p>

This will work.

**Comment by sidkrip** [comment]
These kind of errors are happening a lot many times in different challenges. So, I just go back to the previous challenge from the map, solve it and then go the challenge (with the error with the error) and most of the time it gets corrected automatically.

**Comment by Cartobob** [comment]
Thanks for the info sidkrip.. I will try this the next time I face the issue..

**Comment by colleen612** [comment]
Same exact issue here. I actually did what sidkrip suggested and no such luck. Any suggestions ?

**Comment by colleen612** [comment]
nvm. fixed it.

**Comment by emcquillan** [comment]
How did you fix this?  I'm having the same issue and have tried all of the above suggestions to no avail.

**Comment by mehadi07** [comment]
check space ... i faced some space problem now it fixed :)

**Comment by LynneDixon** [comment]
I also had the issue of the space that it kept saying wasn't there. I tried the above but no change. Then I noticed that I had my "View more " line at the bottom, and I copy/pasted it as-is to just under the h2 line - and it then passed the tests.
