### ISSUE TITLE
profile progress heat map not showing the progress 

### ISSUE THREAD

**Issue by theashraf** [freeCodeCamp/freeCodeCamp#35748]
**Describe the bug**
profile progress heat map not showing the progress, kindly check the sreenshot 

**To Reproduce**
1. Go to 'https://www.freecodecamp.org/theashraf'
2. See the progress heatmap

**Expected behavior**
expected to see my progress on the heat map

**Screenshots**
![Screenshot from 2019-04-03 15-39-49](https://user-images.githubusercontent.com/39750790/55483517-06d75780-5627-11e9-9742-955eb7cff126.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 18
 - Browser: chrome
 - Version: 72

**Comment by RandellDawson** [comment]
Closing this issue as it has already been reported and being tracked in issue #17822.

Thank you.
