### ISSUE TITLE
Solution passes on current production but fails on beta site for Copy an Array with the Spread Operator challenge

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#35742]
The following code passes all the tests on the current production site, but fails the last test on the current beta site (freecodecamp.rocks) and when tested locally (`npm run test:curriculum`).  I discovered the issue while adding solutions to challenges currently missing a solutions on `master`.  I compared the tests in the archived `curriculum` repo and they appear to be the same tests.

```js
function copyMachine(arr, num) {
  let newArr = [];
  while (num >= 1) {
    // change code below this line
    newArr.push([...arr]);
    // change code above this line
    num--;
  }
  return newArr;
}
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/basic-data-structures/copy-an-array-with-the-spread-operator

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 73.0.3683.86 (Official Build) (64-bit)
* Operating System: Windows 10 Home

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
**See below the failing test on freecodecamp.rocks**
![image](https://user-images.githubusercontent.com/5313213/55436606-9e6a7680-5551-11e9-9fc2-b3ff9a0d6ae0.png)

**See below the same code passes on production**
****
![image](https://user-images.githubusercontent.com/5313213/55436692-d5d92300-5551-11e9-8c08-521803d570ae.png)

**Comment by ValeraS** [comment]
@RandellDawson Need to rewrite the test. It checks function source code after babel transform but should check user code.

**Comment by Dharmin2108** [comment]
<h1>check</h1>

**Comment by Dharmin2108** [comment]
hello

**Comment by sil3nthill** [comment]
maybe i can work on this one too ? what can i do exactly ? thanks 
i can test on the current version locally but how can i test on the beta version ?

**Comment by RandellDawson** [comment]
@sil3nthill The beta is just a version of what is on the `master` branch.  It can be up to 2-3 weeks behind it, depending on how often it gets updated.  If it works locally, then it will work on the beta.
