### ISSUE TITLE
Typo in guidePageCreator.js

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35749]
I believe there's an 'f' missing here...

https://github.com/freeCodeCamp/freeCodeCamp/blob/f8675b0bda2e43266ee84e1c75d5e4b3148fa273/client/utils/gatsby/guidePageCreator.js#L27

**Comment by raisedadead** [comment]
Thanks.

**Comment by mdalpozzo** [comment]
What is the correct/complete process for making contributions?  I have read contributing.md, but it does not mention anything about testing locally or any specifics when it comes to working on the codebase.  I see the test scripts in package.json.  In this instance would I add the 'f', run the test scripts for client locally, then push up to my forked repo, and eventually make a PR to upstream master?

**Comment by raisedadead** [comment]
Hi @mdalpozzo 

Thanks for your interest in this. Looks like someone already made a PR, which I just accepted on behalf of the team.

However, we still have lots of issues that we could use your help on.

The guide has links to all the instructions that you will need to work on freeCodeCamp locally:
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md#help-us-fix-bugs-in-freecodecamporgs-learning-platform

I understand as a first timer, you may have found out something missing that we had an oversight on as regular contributors. We would love an update to the instructions themselves that would help.

You can start by creating a fresh issue and taking it from there if you are interested?

Also we have a [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), and the awesome folks there will help you with your queries as well. 

Thanks, and happy contributing!
