### ISSUE TITLE
Bonfire "Search and Replace" tests are looking for a function called replace and not myReplace

### ISSUE THREAD

**Issue by mels065** [FreeCodeCamp/FreeCodeCamp#3574]
I noticed that a couple weeks ago, someone raised an issue about the function being called replace, and the issue was dealt with and renamed to myReplace. It seems the tests are still running on the old-named function replace and aren't accounting for the myReplace function.

The issue can be circumvented by simply renaming the function to replace, but it might not be obvious right away to some campers. It would be best to modify the tests to reflect the new name change.

**Comment by ltegman** [comment]
Looks like this is fixed in the staging branch but someone needs to merge it into master to fix the website.

**Comment by mitziw** [comment]
Im stuck with a false error "replace is not defined" on this challenge as well

**Comment by GitarMan** [comment]
I noticed this issue too. Seems to be able to be fixed by renaming myReplace() to just replace()

According to Itegman the fix is in the works. Not sure how to help beyond this.

**Comment by bugron** [comment]
Closing this issue as we have a merged PR https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3271. This PR was merged 20 days ago, but after that these changes were overwritten by this commit: https://github.com/FreeCodeCamp/FreeCodeCamp/commit/ddde4db82121c4fa639bcb57491a18d81b92ddfd. Hopefully, this will be fixed soon, thanks.
