### ISSUE TITLE
Need to add full working solutions to 47 challenges in the Front End Libraries section

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#35753]
With a quick search, I found there are currently 47 challenges in the Responsive Web Design section that are missing a full working solution.  I wan to use this issue to help track who wants to work on adding these and when the PRs get merged.

Please make sure to remove the `// solution required` and make sure to surround the solutions using `html` instead of `js` (see below for example).
````
```html
solution code goes here
```
````
Make sure to add full code (original challenge seed plus any changes needed to pass challenge) for all challenges in a section.  Please create a separate PR for each set of section challenges to make the review process faster.  I have listed the sections below with the applicable challenge file paths.  Before creating each PR, please test that all solutions pass by testing them locally using `npm run test:curriculum`.

**Notes:**  
1. Only do the English files, because we can copy the solutions over to the other languages in one PR once all have been added to the English version.
2. Instead of write `Closes #this-issue-number`, just write `Related to issue ` when creating the actual PR.  We will close this issue once all solutions for all sections have been merged.

 **PR created:**
- [x] Bootstrap (23challenges) - @Manish-Giri 
- [x] jQuery (17 challenges) - @Manish-Giri 
- [x] Sass (7 challenges) - @ojeytonwilliams

**PR merged:**
- [x] Bootstrap 
- [x] jQuery 
- [x] Sass 

**Bootstrap**
* apply-the-default-bootstrap-button-style.english.md
* call-out-optional-actions-with-btn-info.english.md
* create-a-block-element-bootstrap-button.english.md
* create-a-bootstrap-row.english.md
* create-a-class-to-target-with-jquery-selectors.english.md
* create-a-custom-heading.english.md
* create-bootstrap-wells.english.md
* ditch-custom-css-for-bootstrap.english.md
* give-each-element-a-unique-id.english.md
* house-our-page-within-a-bootstrap-container-fluid-div.english.md
* label-bootstrap-buttons.english.md
* label-bootstrap-wells.english.md
* line-up-form-elements-responsively-with-bootstrap.english.md
* make-images-mobile-responsive.english.md
* responsively-style-checkboxes.english.md
* responsively-style-radio-buttons.english.md
* split-your-bootstrap-row.english.md
* style-text-inputs-as-form-controls.english.md
* taste-the-bootstrap-button-color-rainbow.english.md
* use-a-span-to-target-inline-elements.english.md
* use-comments-to-clarify-code.english.md
* use-responsive-design-with-bootstrap-fluid-containers.english.md
* warn-your-users-of-a-dangerous-action-with-btn-danger.english.md

**jQuery**
* change-the-css-of-an-element-using-jquery.english.md
* clone-an-element-using-jquery.english.md
* delete-your-jquery-functions.english.md
* disable-an-element-using-jquery.english.md
* learn-how-script-tags-and-document-ready-work.english.md
* remove-an-element-using-jquery.english.md
* remove-classes-from-an-element-with-jquery.english.md
* target-a-specific-child-of-an-element-using-jquery.english.md
* target-elements-by-class-using-jquery.english.md
* target-elements-by-id-using-jquery.english.md
* target-even-elements-using-jquery.english.md
* target-html-elements-with-selectors-using-jquery.english.md
* target-the-children-of-an-element-using-jquery.english.md
* target-the-parent-of-an-element-using-jquery.english.md
* target-the-same-element-with-multiple-jquery-selectors.english.md
* use-appendto-to-move-elements-with-jquery.english.md
* use-jquery-to-modify-the-entire-page.english.md

**Sass**
* apply-a-style-until-a-condition-is-met-with-while.english.md
* create-reusable-css-with-mixins.english.md
* extend-one-set-of-css-styles-to-another-element.english.md
* nest-css-with-sass.english.md
* split-your-styles-into-smaller-chunks-with-partials.english.md
* store-data-with-sass-variables.english.md
* use-if-and-else-to-add-logic-to-your-styles.english.md

**Comment by Manish-Giri** [comment]
I'll take care of the Bootstrap and jQuery challenges.

**Comment by ojeytonwilliams** [comment]
I can do the Sass ones.

**Comment by moT01** [comment]
Looks like this one is completed! 🎉
