### ISSUE TITLE
[beta] Going to the homepage ('/') logs me out (sort of)

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35764]
I'm not sure if this is a known issue, I couldn't find anything from a quick search - or perhaps just a temporary one that will be fixed when beta is pushed to production.

**Steps:**
- Go to .rocks
- Log in
- Go to the homepage by clicking the icon on the top left or manually typing in the URL or however

This automatically logs me out (sort of). The `sign in` button reappears. But if I click it, I am logged back in. If I click `learn`, I am logged back in.

Issue happens on both firefox and chrome.

On a probably related issue:
If I switch to night mode, then do the last step above. Half the night mode settings stay, and half of them go away. The main page goes back to "day" mode, except for the footer.

**Comment by RandellDawson** [comment]
@moT01 Is this related to https://github.com/freeCodeCamp/freeCodeCamp/issues/35347 ?

**Comment by moT01** [comment]
Yes, that appears to be the same issue - if it's intended to be that way, I don't like it. Why would the `sign in` button display if you are already signed in. Seems misleading.

**Comment by RandellDawson** [comment]
> Seems misleading.

Exactly, but I was told this was by design.

**Comment by moT01** [comment]
So from reading your other issue. It looks like logging in will take you to `/welcome`, but what if my bookmark is to the homepage, what if I type in the URL. They both take me to the homepage, where it looks like I'm logged out. I think this should be revisited.

**Comment by moT01** [comment]
Hmm, on the live site, I am unable to get to the "homepage" - it automatically redirects me to the welcome screen every time. So I'm thinking this actually might not be a problem when it's pushed if that behavior stays.

**Comment by moT01** [comment]
Yea, I don't think that will continue when pushed to production. I think it's like that for development or something. And since this was already reviewed by several core members, I will close this. If it stays after it's pushed I'm sure it will get caught pretty quickly.
