### ISSUE TITLE
Problem with Guide solution and challenge solution for Reuse Patterns Using Capture Groups challenge

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#35765]
Below are the current instructions for the [Reuse Patterns Using Capture Groups](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/reuse-patterns-using-capture-groups) challenge.

> Use capture groups in reRegex to match numbers that are repeated only three times in a string, each separated by a space.

Reading through common questions on the forum related to this challenge, there probably should be some modifications to these instructions.  

1. It should made clearer that the numbers should appear consecutively separated by a space vs just repeated three times.  Why?  Because in the following string, the same number is repeated 3 times and the numbers are separated by a space, but they are not consecutive.
```
"42 32 42 42"
```
2. Even if we fix the wording as described above, there is still the issue that the following strings  should match, because all 3 of the "42"s are consecutive and separated by a space.
```
"100 42 42 42"
"42 42 42 100"
"100 42 42 42 100"
"42 42 42 100 100 100"
```
All the above would fail the currently "accepted" regex solutions (both seen below)
```
/^(\d+)\s\1\s\1$/

or

/^(\d+) \1 \1$/
```

**Comment by gebulmer** [comment]
I don't have a good solution for this really, because:

I think you're right that those should pass. I think the solution should really be something like: `/(\d+) \1 \1/` (without the anchors)

That unfortunately suffers from being too simple. Our explanation in this question is actually very good, so someone could just barely modify the example and not really have learnt something

Perhaps it'd be good to get the user to use more than one backreference, but I can't think of a reasonable way to phrase any question about it

For example, if they had to check if any pairs of numbers were repeated, the solution would be something like `/(\d+) (\d+) \1 \2/`, which is still simple enough for the user to solve based on the explanation (perhaps if we explicitly stated that `\2` represented the second group)

I can't think of a succinct way to phrase that question though

I'm acutely aware that I suggested another question needed to be simplified, and that this one needs to be more complicated... I do think it's for the better though

**Comment by deepanshu1959** [comment]
testing

**Comment by pratipb** [comment]
1234

**Comment by pratipb** [comment]
my comment

**Comment by pratipb** [comment]
first comment

**Comment by pratipb** [comment]
12

**Comment by moT01** [comment]
how about remove the test for "42 42 42 42". 

change the instructions to:
`Use capture groups in reRegex to match strings where a number is repeated three times in a row, each separated by a space.`

and change the solutions to not use `^` and `$`
so the solution would be `/(\d+)\s\1\s\1/` or `/(\d+) \1 \1/`

**Comment by thecodingaviator** [comment]
@RandellDawson have we fixed this one?

**Comment by RandellDawson** [comment]
@thecodingaviator No, we have not concluded on the best way to deal with this.

**Comment by moT01** [comment]
What do you think about my suggestion @thecodingaviator ?

**Comment by RandellDawson** [comment]
Related to #17645

**Comment by thecodingaviator** [comment]
@moT01 I think it's good. It will simplify the challenge and get rid of the problem.

**Comment by RandellDawson** [comment]
@moT01 I think this can be closed due to the recent change in this challenge.

**Comment by RandellDawson** [comment]
I am reopening this issue as I still think the current verbiage (below) does not reflect that the string must start and end with the same number to be a match.
> Use capture groups in `reRegex` to match numbers that are repeated only three times in a string, each separated by a space.

The way it currently reads still seems like the following should be a match:
> 32 42 42 42

Why?  Because the number `42` is only repeated three times in the string each separated by a space.  The actual regex to match the above would be fairly complex and beyond the scope of the challenge, so I think we should change the instructions.

**Comment by nhcarrigan** [comment]
What about something like:

> Use capture groups in `Regex` to match a string that consists of the same number repeated exactly three times.

**Comment by RandellDawson** [comment]
> Use capture groups in `Regex` to match a string that consists of the same number repeated exactly three times.

I think the word `only` needs to be in there, otherwise, `32 42 42 42` would still apply.

> Use capture groups in Regex to match a string that consists of only the same number repeated exactly three times.

**Comment by nhcarrigan** [comment]
That looks clear to me.

**Comment by Sky020** [comment]
I was triaging in the order of appearance (in my notifications), and only got to this now.

@RandellDawson  Should this issue be combined with #40376 ? If yes, then I recommend the body of 40376 be moved into here. If not, then please go ahead, and add back the _first timers only_ label.

**Comment by RandellDawson** [comment]
@Sky020 Since this is different issue, I think it is fine as a stand-alone issue.
