### ISSUE TITLE
Issue template to include link to file

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35769]
I think the issue template should include a request to add a link to the file where the problem exists.

**Edit:**
When you create an issue, there's a template to fill out that looks like this:
```
<!-- 
NOTE: If you're reporting a security issue, don't create a GitHub issue. Instead, email security@freecodecamp.org. We will look into it immediately. 
-->
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
```

When I'm looking at an issue (specifically issues on coding challenges), I often want to see the file so I can see what the tests are doing or what the formatting looks like or something. This requires navigating through the repository to find the file. A link to the file right in the issue would be handy.

**Comment by alzaar** [comment]
Hi I am new to github contributions, can you explain more about the issue?

**Comment by RandellDawson** [comment]
@moT01 A new camper would have no idea how to find the file on GitHub.  They are doing good just to open an issue and provide the link to the challenge.

**Comment by moT01** [comment]
Well, I suppose that's mostly true. But I think most people could find the files, and if they can't or don't want to, then they don't need to include it. Not to mention a lot of the issues are created by people who are familiar with the repo.

This was just a suggestion that I thought could make it easier. But yea, maybe not for everyone. It's not something that would really make much of a difference so go ahead and close it if you want.

**Comment by RandellDawson** [comment]
@moT01 It is not a bad idea, but I am not sure if we will be able to get people to do it.  Many people don't report all the info that is asked for on the existing template.
