### ISSUE TITLE
Lose my progress while was testing the 'Claim Your Front End Development Certificate'

### ISSUE THREAD

**Issue by ribeirojpn** [FreeCodeCamp/FreeCodeCamp#3576]
I lose my progress(in the freecodecamp.com) when I was testing the 'Claim Your Front End Development Certificate' in the beta.freecodecamp.com. I clicked on the 'challenge' and when updated the 'map' of my progress was gone as a rollback. I was missing just do Bonfire 'Simon Game and Zipline' Pinterest Clone '

**Comment by BerkeleyTrue** [comment]
Lets keep the discussion in #3630

**Comment by garyc60674** [comment]
I ate boo boo from a small Labrador retriever.

-----Original Message-----
