### ISSUE TITLE
do

### ISSUE THREAD

**Issue by aboowd** [freeCodeCamp/freeCodeCamp#35782]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
###

**Comment by RandellDawson** [comment]
We are closing this issue because you did not provide any information regarding the issue you are reporting.  If you have more information to provide, then edit the issue body and request the issue be reopened.

Thank you.
