### ISSUE TITLE
[beta] Minor grammar mistake in Applied Visual Design: Adjust the Tone of a Color challenge description

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#35798]
**Describe your problem and how to reproduce it:**
There is a grammar mistake in challenge `Applied Visual Design: Adjust the Tone of a Color`'s description.

```
Our nav element currently appears have a cyan background
```

Should be

```
Our nav element currently appears to have a cyan background
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.rocks/learn/responsive-web-design/applied-visual-design/adjust-the-tone-of-a-color

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

<img width="520" alt="Screen Shot 2019-04-09 at 5 08 48 PM" src="https://user-images.githubusercontent.com/25715018/55792187-4d76f700-5aea-11e9-871a-bd64a6d7fa45.png">

---

Here is the file that needs to be edited: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/adjust-the-tone-of-a-color.english.md

**Comment by AstiV** [comment]
May I grab this one?

**Comment by sil3nthill** [comment]
@RandellDawson  ah yes my bad didnt see the comment , thank you

**Comment by AstiV** [comment]
Thanks for bearing with me the last days. Created a pull request and happy for any feedback considering the contributing process :)
