### ISSUE TITLE
Test failure in 'Basic Data Structures: Check For The Presence of an Element With indexOf()'

### ISSUE THREAD

**Issue by guayom** [freeCodeCamp/freeCodeCamp#35793]
**Describe your problem and how to reproduce it:**
For [this challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/check-for-the-presence-of-an-element-with-indexof/), the correct answer should be something like:
```
...
return arr.indexOf(elem) >= 0
...
```

But this code will also pass all the tests, even when it is incorrect:
```
...
return arr.indexOf(elem) > 0
...
```

This can be solved by simply changing the order of the variables in the second test, so that `elem` is at index 0, thus disabling the incorrect answer, like this
```
// Before fix
quickCheck(["squash", "onions", "shallots"], "onions") should return true

// After fix
quickCheck(["onions", "shallots", "squash"], "onions") should return true
```

I'd be glad to contribute and fix this myself if the issue is confirmed and the solution approved.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/check-for-the-presence-of-an-element-with-indexof/

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 73.0.3683.86 (Official Build) (64-bit)
* Operating System: macOS Sierra v10.12.5

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Here's a screenshot taken after running all the tests. As you can see, all the tests passed, even when the answer is incorrect.

![95zjpcvQ](https://user-images.githubusercontent.com/3279037/55743794-761ac600-59f0-11e9-97d3-aafa5de5d151.png)

**Comment by aditijoshi14** [comment]
@guayom Can I work on this?

**Comment by RandellDawson** [comment]
@guayom Good catch!  I can confirm the current tests do not test all the cases.  I am fine with implementing the change you suggest on a PR.

**Comment by RandellDawson** [comment]
@aditijoshi14 Since @guayom already offered to fix on a PR, I will leave it up to him to decide if he wants to move forward with the PR or is OK letting you create the PR.

**Comment by aditijoshi14** [comment]
@RandellDawson  I was not aware about his PR. I will leave it up to him to decode.

**Comment by guayom** [comment]
@RandellDawson Thanks for the confirmation. 
@aditijoshi14 Actually this would be my first contribution, so I would really like to give it a shot. But if I run into problems, I'll let you know so you can contribute as well :)

**Comment by aditijoshi14** [comment]
@guayom No worries. Feel free to ping me if you run into problems. Happy contributing!
