### ISSUE TITLE
Cannot pass "what's in query" in Build Web Apps with Express.js(expressworks exercise)

### ISSUE THREAD

**Issue by bconner22** [FreeCodeCamp/freecodecamp#358]
The challenge is to "Write a route that extracts data from query string in the GET '/search' URL
route, e.g. ?results=recent&include_tabs=true and then outputs it back to
the user in JSON format."

After failing a few times, I looked up the solution.  Using this solution does not allow the test to pass:

                ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "{"                                 !=    "{\"results\":\"recent\",\"type\":\"quote\",\"page\":\"0\"}"
   "  \"type\": \"quote\","            !=                                       
   "  \"page\": \"0\","                !=                                       
   "  \"__proto__\": {}"               !=                                       
   "}"                                 !=                                       

────────────────────────────────────────────────────────────────────────────────
  
Oddly, when console.logging the same program, my result is this:

{ results: 'recent', type: 'quote', page: '9', [__proto__]: {} }

**Comment by bconner22** [comment]
Found some additional info, but could not fix the problem.  Expressworks' version of express seems to be 3.2.6.  I tried upgrading to 4.x, test still fails.  After reading at 
https://github.com/nodeschool/discussions/issues/327 I tried using several versions of Express, from 3.4.x all the way through 4.12.x, to no avail.

**Comment by terakilobyte** [comment]
Thanks for the feedback, but unfortunately we don't control the content of expressworks, so I recommend opening this issue there.

**Comment by ybentz** [comment]
Hey, not sure if this is the best solution as I'm just starting to learn Express but I passed the challenge on express version 3.2.6 and the latest (4.13.3) with:
```
var query = require('url').parse(req.url,true).query;
res.send(JSON.stringify(query));
```
