### ISSUE TITLE
Editor output displaying as code

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#35800]
#17925 #35004 https://github.com/freeCodeCamp/freeCodeCamp/pull/35774#discussion_r273383987 are all related problems coming from the fact that test and `console.log` output are put into a `MonacoEditor` component. This results in them being highlighted as if they were JavaScript. 

Would it be better to avoid using the `MonacoEditor` for output and instead sanitize the output and insert it as html?  This would allow challenge writers more freedom while avoiding these types of problems in the future.  Also it would increase consistency between the tests in the description panel and the editor output panel.

**Comment by thecodingaviator** [comment]
The #35574 is being fixed via #35811
