### ISSUE TITLE
Seek and Destroy issue

### ISSUE THREAD

**Issue by Amallard** [FreeCodeCamp/FreeCodeCamp#3580]
Challenge [Bonfire: Seek and Destroy](http://freecodecamp.com/challenges/bonfire-seek-and-destroy) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:35.0) Gecko/20100101 Firefox/35.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code below outputs the exact same output as the code i found in the help section beneath it. The code i found passes all the tests, yet my code does not pass any of the tests. The outputs are exactly the same. Is there an error in the system, or am I actaully missing something?

My code:
```
function destroyer(arr) {
  var arg = arguments.length;
  var newArr = [ ];
  var found = false;
  for (i = 0; i < arr.length; i++) {
    found = false;
    for (j = 1; j < arg - 1; j++) {  
      if (arr[i] == arguments[j]) {
        found = true;
      }
    } 
    if (!found) {
      newArr.push(arr[i]);
    }
  }
  return newArr;
}

destroyer([1, 2, 3, 5, 1, 2, 3], 2, 3, "");

```

code I found in the help section:
```
function destroyer(arr) {
    // get arguments
    var args = Array.prototype.slice.call(arguments, 1);
    // copy array
    var cpArr = arr.slice();
    // loop elements
    for (var elt = 0; elt < arr.length; elt++) {
        // loop args
        for (var arg = 0; arg < args.length; arg++) {
            if (arr[elt] === args[arg]) {
                // remove matches
                cpArr.splice(cpArr.indexOf(arr[elt]), 1);
            }
        }
    }
    return cpArr;
}

destroyer([1, 2, 3, 5, 1, 2, 3], 2, 3, "");

```

**Comment by ahstro** [comment]
I tested your code, and it does not seem to output the exact same thing at all, sorry.

Here's what I got from `console.log`ing the output of all test cases for the correct code:

```javascript
[ 1, 1 ]
[ 1, 5, 1 ]
[ 1 ]
[  ]
[ "hamburger" ]
```

...and here's what I got from doing the same with yours:

```javascript
[ 1, 3, 1, 3 ]
[ 1, 3, 5, 1, 3 ]
[ 5, 1 ]
[ 3, 3 ]
[ "hamburger", 53 ]
```

I don't want to straight out give you the answer, but revisit line 7 in your code might help.
Good luck :)

**Comment by Amallard** [comment]
I see now, change line 7 (arg - 1) to arg. Thank you. 

But, my actual console output with (arg-1) still had the correct answer. I saw in the explaination it was showing the answers you got, but the actual console output box displayed the correct answer.

Why is that?

**Comment by ahstro** [comment]
I think that's because using `arg - 1` made your code work for all but the last argument, and the code you were executing from the editor was `destroyer([1, 2, 3, 5, 1, 2, 3], 2, 3, "");`, which has an empty string as the last argument. Since there were no empty strings to remove from the array, the output seemed to pass.

**Comment by CamperDave2016** [comment]
Here is the solution to avoid your extra empty parameter "":

function destroyer(arr) {
  // Remove all the values
  var args = Array.prototype.slice.call(arguments,1);

  for(var j=0; j<args.length; j++) {  
    for(var i=0; i<arr.length; i++) {
      if (arr[i] === args[j]) {        
        arr.splice(arr.indexOf(arr[i]), 1);
      }
      if (arr[i] === args[j]) arr.splice(arr.indexOf(arr[i]), 1);
    }
  }
  return arr;
}

destroyer([77, 88, 99, 77, 88, 89], 89, 99);
//destroyer([1, 2, 3, 1, 2, 3], 2, 3);
//destroyer([3, 5, 1, 2, 2], 2, 3, 5);
//destroyer([1, 2, 3, 5, 1, 2, 3], 2, 3);
//destroyer([2, 3, 2, 3], 2, 3);
Have fun :)
