### ISSUE TITLE
"Search Results" placement for mini search bar

### ISSUE THREAD

**Issue by narueon** [freeCodeCamp/freeCodeCamp#35816]
**Describe the bug**
Search results are not placed correctly for mini search bar. 

**To Reproduce**
1. Go to 'https://learn.freecodecamp.org/coding-interview-prep/take-home-projects/build-a-nightlife-coordination-app/'
2. Click on 'Search Bar in Header'
3. Type 'D3.js' (well you can type anything).
4. See error (Alignment of search Result is improper)

**Expected behavior**
 * Search results should come under the search bar 
 * Width should be same or less than the search bar. (disabling position: absolute; works but breaks in full search bar)

**Screenshots**
Issue : https://imgur.com/fSmeOTb
Expected : https://imgur.com/qlCdfW4

**Desktop (please complete the following information):**
 - Device : Macbook Pro
 - OS : Mac OS 10.14.4
 - Browser : Google Chrome
 - Version : 73.0.3683.86

**Comment by RandellDawson** [comment]
This has already been fixed on our master branch, but has yet to be deployed to production.  You can see the fix in action by checking out our beta site (https://freecodecamp.rocks)
