### ISSUE TITLE
Need solutions for sorting algorithm challenges in Coding Interview Prep/Algorithms

### ISSUE THREAD

**Issue by wang1998tina** [freeCodeCamp/freeCodeCamp#35814]
**Describe your problem and how to reproduce it:**
Located in the English coding challenges, under Coding Interview Prep, under Algorithms, the sorting algorithms have no solutions.

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/tree/master/curriculum/challenges/english/08-coding-interview-prep/algorithms 

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 
* Operating System: Mac OS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by wang1998tina** [comment]
Forgot to mention that I'm super happy to just tackle this issue!

**Comment by RandellDawson** [comment]
Feel free to add full working solutions to for these challenges.  Please put them on a single PR.  Thank you.
