### ISSUE TITLE
Testing and Test Driven Development 

### ISSUE THREAD

**Issue by RizwanSyed357** [freeCodeCamp/freeCodeCamp#35821]
I am trying to learn about testing and test driven development. It is quite difficult to find n00b-friendly resources online that are clear and easy to understand.

I can't see anything in your curriculum about this. It might be a good idea to add this to your curriculum?

Cheers

**Comment by ojeytonwilliams** [comment]
Hi @RizwanSyed357 as far as I can see there isn't anything explicitly covering Test Driven Development in the curriculum.  However, there is a section on testing, [here](https://learn.freecodecamp.org/information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/) and there is a [short article](https://guide.freecodecamp.org/agile/test-driven-development) in the guide that covers it and includes some links for further reading.

If you're after more than this, the curriculum expansion, specifically freeCodeCamp/curriculumExpansion#100, might be a better place to discuss what you would like to see.  That is where the replacement for the current curriculum is being built.

**Comment by thecodingaviator** [comment]
I'm closing this issue. The problem has been addressed in the previous comment
