### ISSUE TITLE
No solutions for some  challenges :  English / data-structures

### ISSUE THREAD

**Issue by sil3nthill** [freeCodeCamp/freeCodeCamp#35820]
**Describe your problem and how to reproduce it:**
Hello so i was checking some challenges and i found some without solutions ,
Located in english/08-coding-interview-prep/data-structures/

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/tree/master/curriculum/challenges/english/08-coding-interview-prep/data-structures

**Tell us about your browser and operating system:**
* Browser Name:  Mozilla 
* Browser Version: Mozilla quantum
* Operating System: windows 8

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by sil3nthill** [comment]
i would like to start working on them now : 
create-a-hash-table.english.md
check-if-an-element-is-present-in-a-binary-search-tree.english.md
create-a-doubly-linked-list.english.md
invert-a-binary-tree.english.md
add-elements-at-a-specific-index-in-a-linked-list.english.md
i would be more than happy to contribute thanks

**Comment by sil3nthill** [comment]
add-elements-at-a-specific-index-in-a-linked-list.english.md => DONE
 check-if-an-element-is-present-in-a-binary-search-tree.english.md => DONE
going to finish the others and create on PR for all of them what do you think about that @RandellDawson

**Comment by sil3nthill** [comment]
same thing with most of  challenges in arabic , do you want me to create a new issue for this i want to work on the maximum of them , moving existed solution in english to other challenges in arabic , and also translate

**Comment by Tanmay-jana** [comment]
Hi
