### ISSUE TITLE
No solutions for  challenges in Algorithms section / russian 

### ISSUE THREAD

**Issue by PunisherCR** [freeCodeCamp/freeCodeCamp#35828]
**Describe your problem and how to reproduce it:**
in Russian challenges , in the folder algorithms , no file contain a solution 

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/tree/master/curriculum/challenges/russian/08-coding-interview-prep/algorithms

**Tell us about your browser and operating system:**
* Browser Name: Google chrome
* Browser Version: Google chrome
* Operating System: windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by PunisherCR** [comment]
Maybe i can work on this ? cheers

**Comment by RandellDawson** [comment]
Don't worry about these.  Instead, focus on challenges in the English section.  Once we get all of the English solutions added, we will create a single PR which copies them over to all the other languages.
