### ISSUE TITLE
CSS challenges - pass/fail related to attribute order

### ISSUE THREAD

**Issue by MattDBA1** [freeCodeCamp/freeCodeCamp#35830]
**Describe your problem and how to reproduce it:**
Deliberately tried to break the test by adding superfluous CSS attributes. Requested addition was "padding:1.5em", and the tests are:

Your red-box class should have a padding property.
Your red-box class should give elements 1.5em of padding.

I added CSS attributes in the following order:

    font-family:"Bauhaus 93";
    font-size:3em;
    padding:1.5em;
    color:papayawhip;   

This passed the first test but failed the second.

Next I removed the "font-size" attribute.

    font-family:"Bauhaus 93";
    padding:1.5em;
    color:papayawhip;  

 and retested with the same result.

Finally I restored the font-size attribute but reordered with the "padding" attribute first:

    padding:1.5em;
    font-family:"Bauhaus 93";
    font-size:3em;
    color:papayawhip;  

This passed both tests.

CSS is supposed to be rendered independent of attribute order, so all three attempts should have passed.

**Link to the page with the problem:**
CSS challenge:https://learn.freecodecamp.org/responsive-web-design/basic-css/understand-absolute-versus-relative-units

**Browser and operating system:**
* Browser Name: Avant Ultimate using Firefox/Gecko engine
* Browser Version: Firefox 60.0.0.6708
* Operating System: Windows 10 Professional
![screenshot1](https://user-images.githubusercontent.com/49564125/56048058-b17d0380-5d14-11e9-9337-4182be92a748.png)
![screenshot2](https://user-images.githubusercontent.com/49564125/56048074-bb066b80-5d14-11e9-8f0b-4d6b3954f4a7.png)

**Comment by RandellDawson** [comment]
@MattDBA1 Most of the challenges are testing for a very specific thing.  In this case, the tests are not expecting you to add anything else other than the `padding: 1.5em;`  The tests are not expecting the extra `font-type` or `font-size` properties in the `red-box` class definition.

You might check out the [beta site for the same challenge](https://www.freecodecamp.rocks/learn/responsive-web-design/basic-css/understand-absolute-versus-relative-units) to see if you experience similar problems.  Many of the challenges have been changed to be more flexible ("real-life) than the current production.  The changes you see on the beta site will soon be moved to production.

Let us know if you still experience any of these issues on the beta site for this challenge.  If so, then we will look into fixing them.

Thank you.

**Comment by icatat** [comment]
Hi @RandellDawson ! I checked out this issue and it happens both in the beta website as well as in the current one. It seems like the test case was requiring the `padding` to be a third argument. I tried to fix the issue and I created a PR for the English version.
