### ISSUE TITLE
Waypoint: Target the same element with multiple jQuery Selectors BUG

### ISSUE THREAD

**Issue by JensGryspeert** [FreeCodeCamp/FreeCodeCamp#3583]
Challenge [Waypoint: Target the same element with multiple jQuery Selectors](http://freecodecamp.com/challenges/waypoint-target-the-same-element-with-multiple-jquery-selectors) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:39.0) Gecko/20100101 Firefox/39.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
  $(document).ready(function() {
    $("button").addClass("animated shake");
    $(".btn").addClass("animated shake");
    $("#target1").addClass("animated shake btn-primary");
    

  });
</script>

<!-- You shouldn't need to modify code below this line -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

Your #target1 element should have the classes animated‚ shake and btn-primary. The error is marked down that my code doesn't have the right classes. Wich is in this case they are right. I asked on Gitter and I need to do all of them instead of only #target1. Just let you guys know this ;)

**Comment by ltegman** [comment]
As long as you add a different one of the given css classes in each of the requested JQuery selectors you should end up passing the tests because the `button` and `.btn` selectors apply to all buttons including the one with id `#target1` and the final JQuery selector for `#target1` will add the remaining class.

Could you give an example of what the code was you had before that was not passing? The included code passes the tests without issue, which makes it hard to know what the problem you were experiencing is.

**Comment by ltegman** [comment]
I am going to close this issue as the tests and instructions appear correct to me. Please let me know if you have any further concerns with this waypoint.

Thanks and happy coding!

**Comment by JensGryspeert** [comment]
@ltegman My apologise for the late comment. Didn't had internet access till now. well the problem is that what I posted is the correct answer. But the answer that I needed to provide was this:
```
  $(document).ready(function() {
    $("button").addClass("animated shake btn-primary");
    $(".btn").addClass("animated shake btn-primary");
    $("#target1").addClass("animated shake btn-primary");


  });
</script>
```

**Comment by ltegman** [comment]
The correct answer is actually something like
```
$(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn-primary");


  });
```
The goal of the lesson is to show a student how all the specified selectors will have an effect on `#target1` even if only one of them is looking for it specifically. Looking at the tests for this challenge again I notice that the tests are actually too permissive. The test `Only add one class with each of your three selectors.` will pass as long as you call `addClass` three times, even if each call is adding more than one class.

I'm reopening this bug if someone wants to fix that test and potentially reword the instructions, since I do feel like the explanation of what is expected of the student is not entirely clear.

Thanks again for your report!

**Comment by ltegman** [comment]
Closed by PR #3854

**Comment by bradcodd** [comment]
<script>
      $(document).ready(function() {
        $("button").addClass("animated");
        $(".btn").AddClass("shake");
        $("#target1").AddClass("btn-primary");
      });
    </script>
@ltegman i copied this code from my waypoint(challenge?). it looks exactly like yours and yet 1) the code has no effect on the appearance of the page, and 2) the "Run Tests" fails with the messages:
* Only add one class with each of your three selectors.
* Your #target1 element should have the classes animated‚ shake and btn-primary.

I'm running Google Chrome Version 46.0.2490.80 m

**Comment by mh95278** [comment]
I experienced the same issue as bradcodd. When adding only one class in each of the three selectors:
```javascript
<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addCLass("shake");
    $("#target1").addClass("btn-primary");
  });
</script>
```

I get errors: 
Only add one class with each of your three selectors.
Your #target1 element should have the classes animated‚ shake and btn-primary.

I'm running Firefox 41.0.2

**Comment by ltegman** [comment]
@bradcodd Your code does not work because you have called `AddClass` instead of `addClass`.
@mh95278 Your code does not work because you have called `addCLass` instead of `addClass`.

**Comment by bradcodd** [comment]
@ltegman wow! that's subtle. thank you for catching case sensitivity issue!

i'm used to working in a case insensitive environment for 35 years. this change to case sensitivity is going to be my single biggest challenge.

note to curriculum developer: nowhere in the courseware did i see any reference to variables needing to be case sensitive. you may want to address this for noobs, and as a reminder for those coming over from the dark side.

**Comment by omalleyjacqu** [comment]
When I added the code I got the same error but it turned out it was for not indenting the 3 addClass lines. I had the right code but until I indented those lines it wouldn't pass!

**Comment by maryod** [comment]
And the final correct answer? I tried all and doesn't seem to work at all.Thx

**Comment by kartiksyal** [comment]
This code is still not working i am using chrome.
<script>
  $(document).ready(function() {
   $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("animated shake btn-primary");
 
  });
</script>



<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

**Comment by rmrakib** [comment]
<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").AddClass("shake");
    $("#target1").AddClass("btn-primary");
  });
</script>


This is the correct answer. Works for me. Thanks @ltegman

**Comment by auranga** [comment]
<script>
  $(document).ready(function() {
    $("button").addClass("animated bounce");
    $(".well").addClass("animated shake");
    $("#target3").addClass("animated fadeOut");
  });
</script>

**Comment by rowansen** [comment]
worked for me too
<script>
  $(document).ready(function() {
    $('#target1').addClass('btn-primary');
    $('button').addClass('animated');
    $('.btn').addClass('shake');

  });
</script>

**Comment by Cipto1001** [comment]
I need a solution, because I am confused with "Only add one class with each of your three selectors."

 <Script>
 $ (Document) .ready (function () {
 $ ("Button"). AddClass ("animated");
 $ ('. Btn "). AddClass (" shake ");
 $ ("# Target1"). AddClass ("btn-primary");
 });
 </ Script>

**Comment by mola93** [comment]
I cant figure out the error in this code. help people!
<script>
  $(document).ready(function() {
    
    $("button").addClass("animated   ");
    $(".btn").addClass("shake   ");
    $("#target1").addClass("animated shake btn-primary ");


  });
</script>

**Comment by mola93** [comment]
I cant figure out the error in this code. help people!
`<script>
  $(document).ready(function() {
    
    $("button").addClass("animated   ");
    $(".btn").addClass("shake   ");
    $("#target1").addClass("animated shake btn-primary ");


  });
</script>`

**Comment by melik19** [comment]
Thanks ! works for me as well

**Comment by ItaloMilagres** [comment]
@Clipto1001 the solution of @ltegman is right. In this solution you have ONE class in each of your three selector and #target1 "have" three classes because it is "inside" to "button" and .btn.

**Comment by chandramaniadil** [comment]
the instructions are : "Your #target1 element should have the classes animated‚ shake and btn-primary." ,but that means that it should be something  like this :  $("#target1").addClass("animated shake btn-primary"); ,then how this $("#target1").addClass("btn-primary"); works then ?

**Comment by ItaloMilagres** [comment]
@chandramaniadil because the "target1" is inside to tag "button" and class "btn". Follow the code:

<button class="btn btn-default target" id="target1">#target1</button>

**Comment by chandramaniadil** [comment]
it means that it inherits property of it's parent class,correct ? @ItaloMilagres

**Comment by longcrendon** [comment]
My suggestion would be that in the educational tutorial it should be pointed out that because all the classes i.e. button , .btn and #target1 (etc.) are essentially the same the jQuery addClass function will give a cumulative effect to the final output.  (Okay, I'm still a novice, but this might just help to trigger a sense that only ONE function variable is required in the .addClass function) and take out the instruction for #target1, because it is confusing.  I followed your example - and it worked!  thanks!  :-)

**Comment by FreedomOpenProjects** [comment]
The instructions in this task are not clear. So there are many students were confused like me.

**As for the "#target1" you must addclass 3 times seperately**

**Comment by lima-BEAN** [comment]
So, is it safe to say **.btn** inherits the addClass() function animated from **button**, while **#target1** inherits the addClass() function from **.btn**? Which is why we only need to add the next specific function for the next specific selector.

**Comment by m4srur** [comment]
@lima-BEAN Each selector inherits from the previous although full declaration also works but this code is for single selector for each class so the best way is to inherit from the previous, so the answer to your question is yes. 

<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn-primary");

  });
</script>

**Comment by harpreetwasan** [comment]
@ltegman @m4srur   Thanks everyone this one helps

**Comment by soondaskeleton** [comment]
thank you @ltegman. Looking over my code and yours made it helpful.

**Comment by mbecenti** [comment]
That same code did not work for me at first because that is what I initially used. I did what the directions said. I had to switch browsers for it to work. This ended up working for me as I had that at the beginning. I noticed it is a little buggy so try in a different browser too and clear the code and run it again. Hope this helps

<script>
  $(document).ready(function() {
  $("button").addClass("animated");
  $(".btn").addCClass("shake");

  });
</script>

**Comment by vinayakshah** [comment]
Thank you @ltegman it worked so well :) :+1:

**Comment by buntheany** [comment]
[](http://i.imgur.com/oaMqAWN.jpg)  
For me not work

**Comment by buntheany** [comment]
`<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn-primary");
  });
</script>`

its solved. thanks

**Comment by texas2010** [comment]
@buntheany 
Please do not post your solution on here. You could help people at FreeCodeCamp Chat Room or Forum. GitHub Issues are for reporting bugs on the website only.

Happy Coding!

**Comment by wiki7** [comment]
First of all read Question carefully.
Question "Only add one class with each of your three selectors."
mean'n-> firstly add individually addClass to your each three selector ( like button, .btn, and btn-primary ) after that add one more addClass for "#target" and in the addClass add your all three selector in the sequence as question want 
EX- code is... or like this
$("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn-primary");
    $("#target1").addClass("animated shake btn-primary");

**Comment by meekdoyx** [comment]
@ltegman Thanks Sir!

**Comment by laluzinheaven** [comment]
Thanks wiki7 !

**Comment by flemm2016an** [comment]
this worked form... I tried each way that seemed logical and the only one that worked for me was this one.

  $(document).ready(function() {
      $("button").addClass("animated");
      $(".btn").addClass("shake");
      $("#target1").addClass("btn-primary");
