### ISSUE TITLE
Missing info about how to handle package-lock.json in setup guide

### ISSUE THREAD

**Issue by AstiV** [freeCodeCamp/freeCodeCamp#35841]
**Describe your problem and how to reproduce it:**

I just set up the freeCodeCamp project locally using this guide:
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally-using-docker.md

Thereby I stumbled upon one thing, that other beginners might stumble upon, too:

Here, you explain, that when running git status on master, the output should be `nothing to commit, working directory clean`
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally-using-docker.md#making-changes-to-your-clone-of-freecodecamp-locally

Having run `npm install before`, this is not the case, as `package-lock.json` was modified. It would be nice to explain what to do with it, here. I stashed it and applied it to my new branch.

Later on, it turned out that committing `package-lock.json` is only required if a package was actually added (https://github.com/freeCodeCamp/freeCodeCamp/pull/35839#issuecomment-482803627) and I wasn't aware of that before. Maybe you could add that info here as well?

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally-using-docker.md#making-changes-to-your-clone-of-freecodecamp-locally

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

<img width="997" alt="Screen Shot 2019-04-13 at 21 27 53" src="https://user-images.githubusercontent.com/15826773/56084418-13cc2600-5e33-11e9-8c2e-4859d2be2f5a.png">

**Comment by moT01** [comment]
This sounds useful @AstiV - As it took me a few tries to figure out how to deal with it. 

here's a `git status` with the package-lock there...
```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")
```

My method is to `git stash` then `git stash drop`

Something could definitely be added to help users out here as it just says - `If you are not on master or your working directory is not clean, resolve any outstanding files/commits and checkout master:` - but nothing on how to resolve anything.

**Comment by AstiV** [comment]
Thanks for your reply! Shall I add it?

**Comment by RandellDawson** [comment]
Like stash which only works if the files have not yet been commited, you could `checkout` the file.
```
git checkout -- curriculum/package-lock.json
```
Plus, if for some reason the package.json was to appear along with the package-lock.json (which I have seen happen), you can use a wild card like the following to revert both of them.
```
git checkout -- 'curriculum/package*.json'
```

**Comment by ojeytonwilliams** [comment]
The latest changes to the install scripts should have solved this, because they use `ci` basically everywhere which should prevent the lock file from updating.  As long the guide is followed, everything should be fine now.  @AstiV as you ran into this problem before, would you mind checking it on the latest version of master and see if the problem has gone away?

**Comment by AstiV** [comment]
@RandellDawson thanks for explaining! Will do definitely do that the next time before committing such a file.

@ojeytonwilliams sure thing, I can check it on/after the upcoming weekend!

**Comment by ojeytonwilliams** [comment]
@AstiV no rush.  If there are any problems, let us know.  If not, I think it's safe to close this.

**Comment by RandellDawson** [comment]
@ojeytonwilliams Does the following section need to be updated (with respect to npm install)?

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md#troubleshooting

**Comment by ojeytonwilliams** [comment]
@RandellDawson It does, yeah. I'll submit something soon.

**Comment by moT01** [comment]
Closing since it sounds like this doesn't need to be added anymore - let us know if you still have problems @AstiV
