### ISSUE TITLE
Regular Expressions: Restrict Possible Usernames -- instructions wording doesn't make sense

### ISSUE THREAD

**Issue by nataliecardot** [freeCodeCamp/freeCodeCamp#35842]
**Describe your problem and how to reproduce it:**
The challenge says "Usernames have to be at least two characters long. A two-**letter** username can only use alphabet letter characters."

However, this should be changed to "Usernames have to be at least two characters long. A two-**character** username can only use alphabet letter characters."

Letter already means an alphabet letter, whereas character means alphanumeric.  
**Add a Link to the page with the problem:**
[See challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/restrict-possible-usernames/)

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
There is a problem with saying two-character, as that would mean non-alphanumeric characters could be possible. It may be simplest to add a 4th requirement for usernames and make it the first requirement.  
1. Usernames can only use alpha-numeric characters
2. The only numbers in the username have to be at the end.
3. Username letters can be lowercase and uppercase.
4. Usernames have to be at least two characters long. A two-character username can only use alphabet letters as characters.

**Comment by deepanshu1959** [comment]
my first comment

**Comment by deepanshu1959** [comment]
my second comment

**Comment by Harsha1718** [comment]
sadasd

**Comment by Harsha1718** [comment]
first

**Comment by deepanshu1959** [comment]
my second comment

**Comment by deepanshu1959** [comment]
hii

**Comment by jacky1205** [comment]
hii

**Comment by jacky1205** [comment]
hii

**Comment by Harsha1718** [comment]
hiii

**Comment by jacky1205** [comment]
hii

**Comment by jacky1205** [comment]
hii

**Comment by Dharmin2108** [comment]
hii

**Comment by Dharmin2108** [comment]
hii

**Comment by deepanshu1959** [comment]
my third comment

**Comment by deepanshu1959** [comment]
fchgv jhbm

**Comment by madurachanna** [comment]
Deepanshu, I will be joining you

**Comment by Ashuanuj** [comment]
ftguyguj
