### ISSUE TITLE
example not clear

### ISSUE THREAD

**Issue by kaushalmathpal** [FreeCodeCamp/FreeCodeCamp#3584]
Challenge [Waypoint: Access Array Data with Indexes](http://www.freecodecamp.com/challenges/waypoint-access-array-data-with-indexes) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// var ourArray = [1,2,3];
// var ourData = ourArray[0]; // equals 1

var myArray = [1,2,3];
 
var myData = myArraym[]


// Only change code below this line.


// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
// You'll learn about functions soon.
if(typeof(myArray) !== "undefined" && typeof(myData) !== "undefined"){(function(y,z){return 'myArray = ' + JSON.stringify(y) + ', myData = ' + JSON.stringify(z);})(myArray, myData);}


```

**Comment by BlueAccords** [comment]
The example wants you assign the ```myData``` variable to the first value of the ```myArray``` array. Array indexes are the numbers that describe the location of data within the Array. For example, 

```var exampleArray = [4, 17, 25, 50];
console.log(exampleArray[0]); //This would output 4
console.log(exampleArray[1]); //This would output 17
console.log(exampleArray[2]); //This would output 25
console.log(exampleArray[3]); //This would output 50
``` 

and so on and so forth. So to get the first value of ```myArray``` you would write ```myArray[0]```. (this was written in the comment ```// var ourData = ourArray[0]; // equals 1``` but wasn't stated explicitly I suppose.)

If you are still confused then please explain more specifically what you're stuck on.

**Comment by ArielLeslie** [comment]
[Waypoint: Access Array Data with Indexes](http://www.freecodecamp.com/challenges/waypoint-access-array-data-with-indexes) Says
>Array indexes are written in the same bracket notation that strings use, except that instead of specifying a character, they are specifying an entry in the array.

which refers back to [Waypoint: Use Bracket Notation to Find the First Character in a String](http://www.freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-first-character-in-a-string) which says
>Computers don't start counting at 1 like humans do. They start at 0.

>For example, the character at index 0 in the word "Charles" is "C". So if var firstName = "Charles", you can get the value of the first letter of the string by using firstName[0].


In my opinion, this serves sufficiently to refer to an explanation and reinforce an earlier lesson.

**Comment by bugron** [comment]
@kaushalmathpal thanks for posting this issue!
Closing this issue. Feel free to re-open and point what is unclear for you, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
