### ISSUE TITLE
Issue with running tests locally ( with the exact current code version ) 

### ISSUE THREAD

**Issue by PunisherCR** [freeCodeCamp/freeCodeCamp#35851]
![bug1](https://user-images.githubusercontent.com/49563523/56116795-0021dc00-5f67-11e9-9f01-7a19d5bcd42a.png)
![bug2](https://user-images.githubusercontent.com/49563523/56116801-03b56300-5f67-11e9-93c8-99c68be224fe.png)

**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
so i clonned the project on my local machine , i have all the modules from npm and nodejs installed after running npm ci a lot of tests pass just fine but after that its stuck on "Populate tests" i cant see the bug 

**To Reproduce**
1. locally open the project
2. install node js and npm
3- run npm test

**Expected behavior**
all the tests pass since i didnt change anything in the code

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 8
 - Browser /
 - Version /

**Smartphone (please complete the following information):**

**Additional context**
NodeJs version : v10.15.3
npm version : 6.4.1

**Comment by sil3nthill** [comment]
hello did you copy the sample.env to .env ? 
since you are on windows try this : 
copy sample.env .env 
and then run the tests again

**Comment by PunisherCR** [comment]
thanks work like magic !!!! i spent two days looking for the bug

**Comment by sil3nthill** [comment]
sorry deleted the answer .
for anyone there facing the same thing maybe ,
just make sure to copy the sample.env file to .env if you are using windows then just run 
copy sample.env .env
cheers
