### ISSUE TITLE
Basic Data Structures: Iterate Through the Keys of an Object with a for...in Statement 

### ISSUE THREAD

**Issue by kanuos** [freeCodeCamp/freeCodeCamp#35852]
**Describe your problem and how to reproduce it:**
Basic Data Structures: Iterate Through the Keys of an Object with a for...in Statement when clicked on the hint page shows a 404 error.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement

I have solved the problem. Kindly guide me on how and where to add the solution. I am new to github

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 73
* Operating System: Windows 8.1

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by dnntrn** [comment]
Hey @kanuos!

If you haven't already:

1. Fork the freeCodeCamp repository
2. Clone the forked repository and create a branch for your issue
3. make the proper changes/fix the issue on the new branch
3. Once it's all done, submit a pull request to fix the issue.
* make sure your pull request references the issue, and has the pull request checklist (you can view some of the other pull request as an example of the formatting)
 
Here's more guidance: 

[https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md)
[https://github.com/freeCodeCamp/how-to-contribute-to-open-source](https://github.com/freeCodeCamp/how-to-contribute-to-open-source)
[https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/)

**Comment by Harsha1718** [comment]
gtyu

**Comment by RandellDawson** [comment]
@kanuos, @dnntrn This issue has already been fixed on `master` branch, but has not been deployed to production.

You can see the fix on our [beta site](https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for...in-statement).

I am closing this issue.
