### ISSUE TITLE
Images on main page are displayed in wrong place

### ISSUE THREAD

**Issue by Wishnia** [freeCodeCamp/freeCodeCamp#35879]
**Describe the bug**
Images on main page are not centered, they are too much on the left side.

**To Reproduce**
1. Go to freecodecamp.rocks
2. Oops! There is a bug 🐛

**Expected behavior**
Images should be centered.

**Screenshots**
![1](https://user-images.githubusercontent.com/44586513/56375385-ac80ee00-6205-11e9-87cd-9515f7ffe369.png)
1. PC screenshot

![pCd5Y](https://user-images.githubusercontent.com/44586513/56375540-1f8a6480-6206-11e9-9092-ea768e5b02bc.png)
2. Smartphone screenshot

**Desktop (please complete the following information):**
 - OS: Windows 7 Ultimate
 - Browser: Firefox
 - Version: 66.0.3

**Smartphone (please complete the following information):**
 - Device: Huawei P8 Lite
 - OS: Android 6.0
 - Browser: Firefox
 - Version: 66.0.2

**Comment by thecodingaviator** [comment]
Has been fixed in latest build. Would be deployed soon
