### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by Wishnia** [freeCodeCamp/freeCodeCamp#35878]
**Describe the bug**
When you go to freecodecamp.rocks favicon in cards is missing.

**To Reproduce**
1. Go to freecodecamp.rocks
2. Oops! There is a bug 🐛

**I reproduced steps on smarthphone, but there is no bug.**

**Expected behavior**
Favicon should be visible in cards

**Screenshots**
![1](https://user-images.githubusercontent.com/44586513/56374526-aee24880-6203-11e9-847f-f85678a4b9c9.png)

There is freecodecamp.org in first card and freecodecamp.rocks in second card.

**Desktop (please complete the following information):**
 - OS: Windows 7 Ultimate
 - Browser: Firefox
 - Version: 66.0.3

**Smartphone:**
- Device: Huawei P8 Lite
- OS: Android 6.0
- Browser: Firefox
- Version: 66.0.2

**Comment by thecodingaviator** [comment]
Fixed in latest build. Would be pushed to production soon.

Refer #35219 #35568
