### ISSUE TITLE
JS Challenge 162 Not Found

### ISSUE THREAD

**Issue by l3112** [freeCodeCamp/freeCodeCamp#35872]
It was working at one point, but no longer.  I did put in and submit some code (it was incorrect), but only within the parameters of the challenge.

**Chrome Screenshots;**
![Screen Shot 2019-04-17 at 2 42 27 PM](https://user-images.githubusercontent.com/45317033/56316090-0d81c680-611f-11e9-985c-c036744367a3.png)
![Screen Shot 2019-04-17 at 2 42 25 PM](https://user-images.githubusercontent.com/45317033/56316101-12467a80-611f-11e9-9aea-dc9357e35e02.png)

> A page wasn't found for "/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for...in-statement"

![Screen Shot 2019-04-17 at 2 49 34 PM](https://user-images.githubusercontent.com/45317033/56316502-0b6c3780-6120-11e9-87c1-4d33b7f5e131.png)

> 33XHR finished loading: GET "<URL>".

> createAlgoliasearch.js:107 XHR finished loading: POST "https://qmjyl5wyti-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%20(lite)%203.27.1%3Breact-instantsearch%205.0.3%3BJS%20Helper%202.26.0&x-algolia-application-id=QMJYL5WYTI&x-algolia-api-key=4318af87aa3ce128708f1153556c6108".

**Firefox Screenshots**
![Screen Shot 2019-04-17 at 2 44 34 PM](https://user-images.githubusercontent.com/45317033/56316225-5fc2e780-611f-11e9-8ce9-aded81e46111.png)

**Comment by sil3nthill** [comment]
i couldn't generate the bug again its seems ok on my browser

**Comment by ojeytonwilliams** [comment]
@l3112 did you find this via the search bar by any chance?  If so, hopefully it will be fixed by #35540

**Comment by l3112** [comment]
> @l3112 did you find this via the search bar by any chance? If so, hopefully it will be fixed by #35540

I was just doing them in order. Go to the home page, scroll down, clicking "Go to coding curriculum."

**Comment by l3112** [comment]
I ended up searching the course (Javascript basics), and clicking the last challenge I hadn't completed and it worked. I can now reach the other challenges through the first page.

**Comment by RandellDawson** [comment]
@l3112 There are no challenge numbers.  The challenges have unique titles.  The number (163) is what is known as a [brownie point]https://guide.freecodecamp.org/meta/free-code-camp-brownie-points/), which is no longer really used, but has not been removed from the platform.

**Comment by ojeytonwilliams** [comment]
@l3112 I've looked into this a bit more and as far as I can see it *should* be fixed the next time a new build is pushed to production.  It's tricky to directly test, because you need to be logged into the beta site while on the homepage, www.freecodecamp.rocks not www.freecodecamp.rocks/learn,  and I don't believe that's possible currently.  

That said, the problem (there were two functions responsible for creating dashed urls and they didn't match) has been solved, so this problem should be fixed.

**Comment by l3112** [comment]
> @l3112 I've looked into this a bit more and as far as I can see it _should_ be fixed the next time a new build is pushed to production. It's tricky to directly test, because you need to be logged into the beta site while on the homepage, [www.freecodecamp.rocks](http://www.freecodecamp.rocks) not [www.freecodecamp.rocks/learn](http://www.freecodecamp.rocks/learn), and I don't believe that's possible currently.
> 
> That said, the problem (there were two functions responsible for creating dashed urls and they didn't match) has been solved, so this problem should be fixed.

Thanks! Seems good now.
