### ISSUE TITLE
submit button are not working in ubuntu

### ISSUE THREAD

**Issue by kishan2019** [freeCodeCamp/freeCodeCamp#35875]
**Describe your problem and how to reproduce it:**
when I am clicking ctrl + enter some time it not submit.

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by thecodingaviator** [comment]
Can you add a screenshot of your browser developer console please?

**Comment by kishan2019** [comment]
Now its working some time happens I will send you when it will happen
