### ISSUE TITLE
Add auto hide the header while scrolling. 

### ISSUE THREAD

**Issue by sayansur25** [freeCodeCamp/freeCodeCamp#35881]
Hide the header tab while scrolling down. Facing difficulties while reading the blog.

**Comment by DevanandGowda** [comment]
@sayansur25 can you assign this to me! I would be glad to fix this up.

**Comment by RandellDawson** [comment]
@sayansur25 Can you please add some screenshots or animated gifs highlighting the issue you are having?  Also, can you let us know if you experience the same behavior on our [beta site](https://freecodecamp.rocks) ?

Thank you.

**Comment by madurachanna** [comment]
Even I had the same prblem

**Comment by madurachanna** [comment]
I had the same issue

**Comment by madurachanna** [comment]
I had the same issue

**Comment by madurachanna** [comment]
I had the same issue

**Comment by moT01** [comment]
Closing as stale.
