### ISSUE TITLE
Create a path that outputs an anonymized CSV of all camper activity

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3589]
We want make Free Code Camp an "open data" project.

We'd like to have a URL campers, data scientists, and academics studying Free Code Camp's community and pedagogical approaches can visit to obtain a full dump of our anonymized user database.

Basically, it would query for attributes of all of Free Code Camp's 100k+ campers' progress and initiate a download of the CSV file.

Instead of running this massive query every time someone requests the data, we'd like to run the task once a day and cache the results.

**Comment by roelver** [comment]
I looked at the collection structure for the users. In a CSV file, all records should have the same number of values. With the internal arrays for completed challenges, I think it's hard to create a CSV with a tool like mongoexport. I don't think it will be hard to build a custom node script to produce a CSV file, with null values for uncompleted challenges.
Do you already have a script for that?

**Comment by bugron** [comment]
This is partially closed by https://github.com/FreeCodeCamp/FreeCodeCamp/pull/5449. Is that PR enough to close this issue?
