### ISSUE TITLE
Stubs Littered In master/guide/english/certifications/coding-interview-prep/data-structures

### ISSUE THREAD

**Issue by StanimalTheMan** [freeCodeCamp/freeCodeCamp#35890]
**Describe your problem and how to reproduce it:**
There are simply stubs

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/tree/master/guide/english/certifications/coding-interview-prep/data-structures

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version:  73.0.3683.103 
* Operating System: Ubuntu 16.04 LTS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

Hi all.  https://github.com/freeCodeCamp/freeCodeCamp/pull/35511 says I can update stubs with solutions and whatnot, but I am making it an issue because there are solutions seemingly already located here: https://github.com/freeCodeCamp/freeCodeCamp/tree/master/curriculum/challenges/english/08-coding-interview-prep/data-structures.
Is it a matter of copying and pasting these solutions?  And adding hints etc.  I am willing to add alternate solutions that differ from the ones located in the curriculum directory but I assume those are pretty good.  Thank you.

**Comment by candacej97** [comment]
Hey maintainers, I'd be happy to work on this!

**Comment by StanimalTheMan** [comment]
@thecodingaviator  @RandellDawson  Any help or clarification is appreciated.  Thank you.

**Comment by RandellDawson** [comment]
@StanimalTheMan Just make sure the solutions use a different algorithm and not just changing syntax (i.e. change a for loop to a map).  

@candacej97, @StanimalTheMan Before creating a PR with a solution for the guide, make sure to validate if one already exists on the master branch first AND use our [Contributor Tools app](https://contribute.freecodecamp.org/dashboard/) and perform a Filename search to make sure there is not already an existing open PR with a similar solution which would be merged instead.

**Comment by moT01** [comment]
Why do the solutions need to use a different algorithm?

**Comment by RandellDawson** [comment]
I am closing this issue as the guide has been removed from the repo.  The hints/solutions for the challenges will now reside on the forum as wikis.  Until a formal process is communicated, we will be taking suggestions for changes via the comments for each challenge topic.
