### ISSUE TITLE
Missing Link in Spinal Tap Case Article

### ISSUE THREAD

**Issue by navjotjsingh** [freeCodeCamp/freeCodeCamp#35897]
**Describe your problem and how to reproduce it:**
There is no link mentioned for Regex Resources in the Spinal Tap Case Guide Article.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/spinal-tap-case/
https://www.freecodecamp.rocks/guide/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/spinal-tap-case/

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 73.0.3683.103
* Operating System: Windows 10

**Comment by kaypeter87** [comment]
Hi @navjotjsingh 

I have created a PR that should close this issue. Please reference PR #35901
