### ISSUE TITLE
Instruction Text mislabeled in challenges

### ISSUE THREAD

**Issue by AndrewZaw** [freeCodeCamp/freeCodeCamp#35908]
I noticed that many of the challenges in the ["Introduction to the Coding Interview Data Structure Questions"](https://learn.freecodecamp.org/coding-interview-prep/data-structures) have the instruction text improperly placed in the challenge template. Instead of having them inside the `<section id= "instructions">`, they have been placed inside `<section id='description'>` and thus they appear differently than how instructions normally appear on the site (below the horizontal line). 

I have a pull request fix ready for this issue so I will submit it as soon as I get feedback regarding this.

**Comment by RandellDawson** [comment]
We did something similar to when resolving issue https://github.com/freeCodeCamp/freeCodeCamp/issues/35413.
