### ISSUE TITLE
Incomplete Challenge: Invert a Binary Search Tree

### ISSUE THREAD

**Issue by StanimalTheMan** [freeCodeCamp/freeCodeCamp#35914]
**Describe your problem and how to reproduce it:**
In both the curriculum and guides directories, when you look in the invert-a-binary-tree.md and  index.md respectively, there is no solution and when I go to the challenge as a regular user of fcc, there is no invert method as the challenge description indicates to complete.

**Add a Link to the page with the problem:**
-https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-coding-interview-prep/data-structures/invert-a-binary-tree.english.md
-https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/certifications/coding-interview-prep/data-structures/invert-a-binary-tree/index.md

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 73.0.3683.103
* Operating System: Ubuntu 16.04 LTS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot from 2019-04-25 12-44-32](https://user-images.githubusercontent.com/43020892/56753143-ebf49080-6757-11e9-97b3-36962494ff8c.png)

Hi.  I am wondering if I can work on resolving this challenge e.g. solution possibly, make an invert method etc.  Thank you.

**Comment by RandellDawson** [comment]
@StanimalTheMan You are correct, those files do not have solutions.  I also checked to see if there were any existing PRs which add solutions to those files and there are none, so you are free to create a PR for the two files.

Thanks for you help.

**Comment by StanimalTheMan** [comment]
Alright. Thank you.
