### ISSUE TITLE
Calendar dates offset when hovering

### ISSUE THREAD

**Issue by hilliarj** [freeCodeCamp/freeCodeCamp#35916]
**Describe the bug**
When looking at an open profile portfolio, the pop-up that shows the corresponding date is offset. Sometimes offset by a lot, and other times only a little offset. 

**To Reproduce**
1. Go to settings.
2. Click on 'show me my public portfolio'. 
3. Scroll down to the calendar and hover over any date.

**Expected behavior**
The pop-up containing the date should hover over the exact date that was intended.

**Screenshots**
<img width="736" alt="Screen Shot 2019-04-25 at 2 12 29 PM" src="https://user-images.githubusercontent.com/21319186/56758991-de460780-6765-11e9-885f-cd14a6083d86.png">

**Desktop (please complete the following information):**
 - OS: [Mojave v10.14.4]
 - Browser [Chrome]
 - Version [Version 74.0.3729.108]

**Additional context**
This bug was slightly mentioned in two other bugs, but I felt a need to create a new bug report for this issue. It was mentioned in #17299 and #22031, but never fully discussed.

**Comment by RandellDawson** [comment]
Is this reproducible on freecodecamp.rocks?

**Comment by hilliarj** [comment]
![image](https://user-images.githubusercontent.com/21319186/56761717-0d5f7780-676c-11e9-9912-253640fe3188.png)
Above is what freeCodecamp.rocks looks like. The date does not show up at all on the screen.

**Comment by RandellDawson** [comment]
Remember that your data from production does not apply to freecodecamp.rocks which is a completely different database.  You will need to work through some challenges over a couple of days and see what the profile shows.

**Comment by hilliarj** [comment]
![image](https://user-images.githubusercontent.com/21319186/56764687-50711900-6773-11e9-88a4-ac78d611f827.png)
@RandellDawson It does not seem to change. I completed ~10 challenges and nothing showed up.

**Comment by RandellDawson** [comment]
I am not sure how often the freecodeamp.rocks updates.  I just tested it using my freecodecamp.rocks account and it does show activity, but there is no pop-up at all.

**Comment by hilliarj** [comment]
The pop-up is the main issue that I was worried about. It seems to vary in how much it is offset based on different users or machines. Cant narrow down what specifically changes it though.

**Comment by raisedadead** [comment]
We can migrate your production user data, with your consent on the .rocks for 1 to 1 simulation of this. Let us know your username here, [or over a DM](https://get.ms/chat).

**Comment by hilliarj** [comment]
Username for FCC is: jhilliard
Feel free to migrate it!

**Comment by raisedadead** [comment]
Hi @hilliarj I have copied over your production profile on the beta site. Please give it a go, you can also reach out to our [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) for any assistance.

**Comment by hilliarj** [comment]
@raisedadead @RandellDawson I have tried to replicate the bug on freecodecamp.rocks and it is still there. The dates do not appear when hovering over any date on the calendar.

**Comment by moT01** [comment]
I am going to try and take a look at this.
