### ISSUE TITLE
Please approve my pull requests from February

### ISSUE THREAD

**Issue by sophyphreak** [freeCodeCamp/freeCodeCamp#35924]
I fixed some bugs in the frontends of the [issue tracker boilerplate](https://github.com/freeCodeCamp/boilerplate-project-issuetracker) and the [stock checker boilerplate](https://github.com/freeCodeCamp/boilerplate-project-stockchecker). 

I opened these pull requests in February and they haven't been touched since. Would someone with the ability to approve these pull requests please look at them and approve or reject them.

Thank you!!!

**Comment by RandellDawson** [comment]
I am going to close this issue, because you can always reply back to the original issues with a similar request.  

We have many PRs we are still reviewing even from October 2018, so it could be a while before we get to your PRs.

**Comment by sophyphreak** [comment]
Ok, fair enough. Thanks for replying @RandellDawson and explaining the situation!

**Comment by sophyphreak** [comment]
Although I should point out that right now the front end for both of those boilerplates are broken right now. Makes it seem like a person's portfolio project is broken unless they've caught the bug and fixed it themselves. 

Both of those bugs seemed pretty urgent, and my portfolio would've suffered significantly had I not fixed them. I want to fix them for everyone.

But again, I accept your decision to close this pull request. I just wanted to make it clear that I think this is urgent, but all I can do is make that clear in text form.

**Comment by RandellDawson** [comment]
Just make sure to comment on the PRs too.
