### ISSUE TITLE
bonfire-missing-letters not passing

### ISSUE THREAD

**Issue by mitziw** [FreeCodeCamp/FreeCodeCamp#3592]
http://www.freecodecamp.com/challenges/bonfire-missing-letters
function fearNotLetter(str) {
  var chars = [ "A","B","C","D","E","F","G","H","I","J","K",
            "L","M","N","O","P","Q","R","S","T","U","V",
            "W","X","Y","Z", "a","b","c","d","e","f","g","h","i","j","k",
            "l","m","n","o","p","q","r","s","t","u","v",
            "w","x","y","z",0,1,2,3,4,5,6,7,8,9];
  var newarr = [];
  var arr = str.split("");
  var first = str.charAt(0);
  var last = str.charAt(str.length);
  for (i = 0; i<str.length-1; i++){
    var curr = chars[chars.indexOf(arr[i])];
    var next = chars[chars.indexOf(curr)+1];
    if(str.indexOf(next)===-1){
      newarr.push(next);
    }
//    console.log(curr +' '+ next);
  }
return newarr = (newarr.length ===0)? undefined : newarr;
}

fearNotLetter('abce');

**Comment by ltegman** [comment]
This is not a bug with the tests. The tests are looking for a string value and you are returning an array.

**Comment by BerkeleyTrue** [comment]
@ltegman Is correct.

Please see:
https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-get-help-when-you-get-stuck

Happy Coding!

**Comment by mitziw** [comment]
Then that should be stated clearly on the instructions. It's not clear.
