### ISSUE TITLE
[rocks/beta] logo in nav doesn't show up

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35934]
**Describe the bug**
The FCC logo on the top left of the nav doesn't show up.

**To Reproduce**
1. Go to freecodecamp.rocks or refresh the page if you're already there.
1. go to either the 'learn' or 'settings' page with a wide enough window that the logo should show up
2. It doesn't show up

- It does show up if you shrink the window and then expand it again. Strange.

**Screenshots**
![Screen Shot 2019-04-29 at 8 49 16 AM](https://user-images.githubusercontent.com/20648924/56904858-c2dc4480-6a64-11e9-83b1-acbdea6ca099.png)

**Desktop (please complete the following information):**
 - OS: high sierra 10.13.6
 - Firefox 66.0.3
 - Chrome 74.0.3729.108

**Additional context**
Tested on chrome and firefox, the issue occurs on both.

**Comment by ojeytonwilliams** [comment]
To reproduce this locally, you need to build the client - it doesn't appear in development mode.

For whatever reason, the `Media` component isn't behaving itself.  I'll take a closer look.

**Comment by raisedadead** [comment]
@ahmadabdolsaheb there is a PR in the works. Can you check this and follow up.
