### ISSUE TITLE
Need redirects for some challenges

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#35930]
A couple of users have been unable to access the "Basic Data Structures: Iterate Through the Keys of an Object with a for...in Statement" challenge from their user profile page (https://github.com/freeCodeCamp/freeCodeCamp/issues/35872). It seems that the `dasherize` function that creates URLs from the challenge names has changed sometime in the last year -- both users had completed the challenge when the URL was `/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for...in-statement/`, and not `/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement/` like it is on the current production build.

Currently on master the URL is `/learn/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for...in-statement/`, but we should create a redirect for cases where the user completed the challenge at `/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement/`. There may be other cases where the dashed names/URLs for challenges are different between production and master, so we should also create redirects for those.

**Comment by QuincyLarson** [comment]
We think this is fixed but @raisedadead will investigate.

**Comment by raisedadead** [comment]
We are going to be removing the timeline from the user portfolio. Its not helpful and clutters it up, I think those are the only places this is linked.
