### ISSUE TITLE
[rocks/beta] homepage images not centered on firefox

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35933]
**Describe the bug**
The images on the homepage aren't centered (see image below).

**Screenshots**
![Screen Shot 2019-04-29 at 9 25 34 AM](https://user-images.githubusercontent.com/20648924/56903587-3892e100-6a62-11e9-87a6-325e57d35c69.png)

**Desktop (please complete the following information):**
 - OS: high sierra 10.13.6
 - firefox 60.0.1
 - chrome 74.0.3729.108

**Additional context**
Tested on chrome and firefox - the issue only occurs on firefox

**Comment by ojeytonwilliams** [comment]
Could you inspect one of those elements and check that it has the class `img-center` and that the css 
```css
.img-center {
  margin: 0 auto;
}
```
is being applied?  As far as I can see, that's all that's responsible for the centering.

**Comment by moT01** [comment]
<img width="1171" alt="Screen Shot 2019-04-29 at 10 49 51 AM" src="https://user-images.githubusercontent.com/20648924/56908758-90364a00-6a6c-11e9-95c6-208957782a76.png">

The class is there, but the properties aren't being applied.

Looks like they're being overridden by the `img-responsive` margins...
When I uncheck those, it gets centered.
<img width="1182" alt="Screen Shot 2019-04-29 at 10 48 18 AM" src="https://user-images.githubusercontent.com/20648924/56908783-9cbaa280-6a6c-11e9-8be4-ed712817aefa.png">

**Comment by ojeytonwilliams** [comment]
That's a bit odd.  `img-responsive` should be coming from Bootstrap and should not touch margin.

**Comment by leorotondano** [comment]
Hello everybody. I'm new here and I'm trying to start contributing with some repositories on GitHub.
I tried to simulate this issue at firefox **66.0.1**, but it doesn't happen (at least not running the application locally on Ubuntu 16.04.6 LTS). 
Downgrading firefox to version **60.0.1** on Ubuntu 16.04.6 LTS is kind of painfull. I tried some options to achieve this, but Firefox crashes as I downgrade it and try to access any site (I downgraded Firefox using Ubuntuzilla). 
@moT01, if it's not a problem to you, maybe it's a good idea to check if you would get that same issue with an upgraded Firefox - maybe the same version that I tried and did not get the error (version 66.0.1).

**Comment by moT01** [comment]
It's not an issue after upgrading @leorotondano - I did not check it locally. Did you have this issue @ojeytonwilliams or did you not check it?

**Comment by ojeytonwilliams** [comment]
@moT01 I wasn't able to reproduce this one. On my machine the css for .img-responsive didn't overwrite margin, so they look fine for me.

**Comment by moT01** [comment]
Well, I can probably close this then. If it's still a problem someone else will catch it later.
