### ISSUE TITLE
[rocks/beta] nav menu briefly expands on load

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35931]
**EDIT: This issue description can be ignored - see the bug in the second post**

**Describe the bug**
While signed out on beta, and the window is small enough to display the 'menu' button in the nav - the dropdown menu doesn't open. Also, perhaps a separate issue - the nav has a bunch of wasted space here

**Screenshots**
<img width="765" alt="Screen Shot 2019-04-29 at 9 03 58 AM" src="https://user-images.githubusercontent.com/20648924/56901509-f23b8300-6a5d-11e9-9fdb-3a7d2fe07597.png">
^^Nothing happens when clicking the menu button

**Desktop (please complete the following information):**
 - OS: high sierra 10.13.6
 - Browser: firefox 66.0.1

**Additional context**
I tested on chrome and firefox - chrome does not have the issue, firefox does

**Comment by ojeytonwilliams** [comment]
I couldn't reproduce the above behaviour, the menu button works on 
* OS: Ubuntu 18.10
* Browser: Firefox 66.0.3

While checking that, I did notice the menu briefly expands when you reload the page before collapsing.  This happens for both Chrome and Firefox, but Firefox is a little more obvious:
![Menu](https://user-images.githubusercontent.com/15801806/56903153-0900ca80-6a9c-11e9-8879-415a663dc945.gif)

This only happens on rocks, not on my local version.

I wasn't sure if it was worth opening another issue for this, but if it is, I'd be happy to.

**Comment by moT01** [comment]
I updated my firefox to your version and I'm seeing the same as I saw before. I'm not getting the logo on the left either.

**Comment by ojeytonwilliams** [comment]
Maybe it's an apple specific problem?  I've tried it in Chrome and Firefox on Ubuntu, those two and Edge on Windows and it's always the same for me.

**Comment by moT01** [comment]
Looks like it probably is, I get the same behavior as you on windows.

**Comment by ahmadabdolsaheb** [comment]
I could see it locally when I build Gatsby.

To reproduce, you need to do the following:
1) cd client
2) npm run build
3) node_modules/.bin/gatsby serve
4) visit localhost:9000

**Comment by ojeytonwilliams** [comment]
@ValeraS @ahmadabdolsaheb Should the nav menu ever appear on the guide?  I wasn't sure because production has nothing
![guide](https://user-images.githubusercontent.com/15801806/56979863-0aed8b00-6b7b-11e9-9279-a7107e0fa03a.png)
but rocks has it appearing in the same way as the curriculum, like this
![guide-rocks](https://user-images.githubusercontent.com/15801806/56979870-12149900-6b7b-11e9-8e96-72f08886eb53.png)

On small screens they behave the same way - there's a menu button and it toggles display of the side nav.

**Comment by moT01** [comment]
okay, I found my problem here - I have a "Dark Mode" extension installed on my firefox that was causing style issues - after disabling it, I get the same behavior as @ojeytonwilliams

**Comment by RandellDawson** [comment]
@moT01 Is this still an issue on freecodecamp.dev?

**Comment by moT01** [comment]
I wasn't having any issues. I think we're safe to close it.
