### ISSUE TITLE
Tidying up the API Server

### ISSUE THREAD

**Issue by lightyaer** [freeCodeCamp/freeCodeCamp#35949]
**Describe the bug**
A few files in api-server folder, have redundant console.logs before throwing/rejecting errors.
May I suggest to remove these and clean the code.

I would like to work on this issue.
Please advice

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 73

**Comment by moT01** [comment]
Can you point to an example @lightyaer ?

**Comment by moT01** [comment]
Closing as stale. Feel free to comment if anyone wants this reopened.
