### ISSUE TITLE
required coding constructs can be ignored by writing the empty construct in the code

### ISSUE THREAD

**Issue by rns350** [freeCodeCamp/freeCodeCamp#35948]
**Describe your problem and how to reproduce it:**

So I noticed while working on a challenge that you could work around test requirements by abusing the system.  Granted, this would be hard for a beginner programmer to even realize they could do, but I wanted to bring it up.  I noticed that for some challenges that want you to use a specific coding construct, the challenge simply makes sure the syntax is there.  

For example, in the Basic JavaScript challenge: "Iterate through an array with a for loop," the problem can be solved by writing for() in a comment or, notably, writing an empty for loop in the code.  
EX: <code>for(int i; i < i; i ++){};</code>.  If this is done, the problem can be solved in any way as long as the final values are right.  

I noticed that this is already being worked on as far as the ability to comment, but there is still the issue that empty constructs can be used to get past the work.  It may be better to instead make sure that no while loop is being used and that .push only appears in the syntax once (Something that can be required in the challenge description).  Let me know what you guys think.  If my proposed solution seems good, I'll go ahead and update the challenge file.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/iterate-through-an-array-with-a-for-loop

**Tell us about your browser and operating system:** 
* Browser Name: Chrome
* Browser Version: Chrome 73 for windows 10
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="960" alt="example" src="https://user-images.githubusercontent.com/35731530/57044135-83b21d00-6c37-11e9-8688-06713ceda658.PNG">

**Comment by RandellDawson** [comment]
I agree the tests are a bit lenient with allowing the for loop to be used as you do and then the camper could use a while loop or for that matter a forEach or map could be used as well.  We don't want to limit the user to using a push method to solve the challenge though.  Using push would not really make much sense for this challenge as the user just needs to sum all of myArr's elements and assign to total.

I think the best we can do is improve the following test:
> You should use a <code>for</code> loop to iterate through <code>myArr</code>
which uses the following regex with `match` below.
```
code.match(/for\s*\(/g).length > 1 && code.match(/myArr\s*\[/);
```

I think you could get a little closer to validating the proper for loop declaration with something like:
```js
code.replace(/\s/g,' ').match(/for\((var|let)([a-zA-Z]\w*?)=0;\2(<myArr\.length|<=myArr\.length-1);.*\){/g)/);
```
If someone wants to go through the trouble of creating a validate for loop and then use a while loop to calculate `total`, then I think that trying to prevent something that will rarely happen with a new camper in the Basic JavaScript section.

**Comment by Sky020** [comment]
Just to triage this issue: I would say this issue can be closed, as, while the tests are lenient, the challenge is so simple that, for a user to circumvent the expected solution, they would almost certainly have to be familiar with the concept. Therefore, there would be nothing to teach them.

So, as this is stale, and not an issue of bad-code passing, I am closing this issue.
