### ISSUE TITLE
Study groups on the forum should be seperate top level category

### ISSUE THREAD

**Issue by stevenkuipers** [freeCodeCamp/freeCodeCamp#35941]
Not a bug report, more of a possible UX improvement

I posted this in the forums but will also post it here to hear what your opinions are about this. Having the study groups on the forums is a great idea but if this is going to scale properly, countries shouldn’t all be top-level categories, there are only 13 countries at the moment and the list is getting quite long already and is quite messy. 

I’m not sure about the badges either, look at the US groups, there are 13 badges already and more to follow I’m sure.

Maybe study groups can be a category and countries can be subcategories?

**Screenshots**
![www freecodecamp org_forum_](https://user-images.githubusercontent.com/13149753/56951739-e5d82880-6b38-11e9-9dfd-c32ce9a0b981.png)

**Comment by scissorsneedfoodtoo** [comment]
Very good points @stevenkuipers. What do you think @ahmadabdolsaheb and @raisedadead?

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo I already brought this up on a Staff post on the forum.  I have sent you a DM to that post on Gitter.

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, thank you, I'll check out that post.

**Comment by raisedadead** [comment]
I think this is best discussed on the forum, and if there is a code change required then we could take this on the tracker. Please drag Quincy into the discussion on the forum. He would need to sign off as well.
