### ISSUE TITLE
[rocks/beta] Sign In with Google return 400 "redirect_uri_mismatch"

### ISSUE THREAD

**Issue by lightyaer** [freeCodeCamp/freeCodeCamp#35942]
**Describe your problem and how to reproduce it:**
Browse to freecodecamp.rocks  and Click on Sign In, select Sign In with Google.
Received a 400 from Google

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 73.0.3683.103
* Operating System: Windows 10 Pro

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Annotation 2019-04-30 170408](https://user-images.githubusercontent.com/5101454/56959133-0c628780-6b6a-11e9-94a5-e57d67297ba9.png)

**Comment by raisedadead** [comment]
Thanks for your report. See https://github.com/freeCodeCamp/freeCodeCamp/issues/34872
