### ISSUE TITLE
Add article about Linux 

### ISSUE THREAD

**Issue by TomasRoj** [freeCodeCamp/freeCodeCamp#35957]
Hey,

Can I make article about using Linux in development. It think that new coders should have opportunity to choose.

**Comment by moT01** [comment]
An article in the guide @TomasRoj?

**Comment by TomasRoj** [comment]
Yes. I say that there is Linux topic but no guide

**Comment by RandellDawson** [comment]
@TomasRoj Can you provide a little more detail about what you mean about using Linux in development?

**Comment by TomasRoj** [comment]
I want to explain basics of command line or maybe how to choose and install some Linux distro

**Comment by RandellDawson** [comment]
You should review the [linux guide articles on the master branch](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/guide/english/linux) and make sure there are not already similar.  I believe some of the topics you are thinking about have already been written.  That being said, you could always improve the existing ones if you feel it is needed.

The latest version of the Guide on the master branch has yet to make it to production, but will eventually make it there in the future.  That is why you may not have seen some of the articles located in the master branch at guide.freecodecamp.org

**Comment by moT01** [comment]
There is also a number of PR's open for linux stuff...
you can go here - https://contribute.freecodecamp.org/dashboard/
click the "filename" radio button
and put "guide/english/linux" in there to see them
So maybe check there too.
Here's one I found there - https://github.com/freeCodeCamp/freeCodeCamp/pull/27328/files

There's a number of command line articles articles as well -  like @RandellDawson said, we want to not duplicate stuff as much as we can. But certainly there's always room for more articles, so find something that isn't covered - or something you want to improve.

**Comment by TomasRoj** [comment]
Ok thanks. I will look at that
