### ISSUE TITLE
Browser extensions causing style issues

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35959]
I had some style issues on my firefox browser from the "Dark Mode" extension/add-on.
Specifically these two issues: https://github.com/freeCodeCamp/freeCodeCamp/issues/35958 - https://github.com/freeCodeCamp/freeCodeCamp/issues/35931
After some frustration and help I found the add-on to be the problem. I'm not sure if there's anything that can be done to avoid issues like this, but I figured it could be discussed a little bit.

**Comment by ojeytonwilliams** [comment]
It would be tricky to come up with a generic solution, since it depends on the behaviour of each extension.  For example, we could stop #35958's problem, passing with only the seed code, by adding a filter like this:

```js
assert($("style") && $("style:not(#dark-mode-custom-style)").length >= 1)
```

That would fix the issue, but relies on an implementation detail of the extension.

I guess we could solve them on a case-by-case basis, but it might be better to put a warning somewhere.  Perhaps something that pops up when tests fail?

**Comment by moT01** [comment]
A warning might be the only way to go - adding tests on a case by case basis just isn't practical - browsers vary and change - extensions change and there's a ton of them. I'm a little concerned with a warning on the pop-up as well - it might make users start looking for problems with an extension when their code is the problem.

**Comment by ojeytonwilliams** [comment]
That's a good point.  Maybe just a suggestion to turn them off at the start of the curriculum, then.

**Comment by moT01** [comment]
I really don't see a good spot for a warning like that - I remember a notice at one point to use chrome for the best experience, but I'm not sure where it is anymore - next to that might have been a good spot - or perhaps [here](https://www.freecodecamp.rocks/support) - I don't think too many people are having issue with this so we can probably just leave it alone.

**Comment by ojeytonwilliams** [comment]
Putting something on the support page could work.  How about something like:
>#### I cannot pass a challenge, but I think my code is correct
>Some browser extensions can interfere with challenge tests.   If you are using any, try disabling them and run the tests again.  If the problem remains, click the challenge's 'Ask for Help' button to post on the forum. You will need to create a forum account if you don't already have one.

**Comment by moT01** [comment]
That actually sounds pretty good

**Comment by ojeytonwilliams** [comment]
Cool, I'll pop that in a PR.
