### ISSUE TITLE
Minor problem with the nav menu

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#35952]
**Describe the bug**
When navigating away from the guide, the menu state persists.  If the side nav is visible on the guide when the viewport is narrow, then the main nav will be expanded on the new page.

**To Reproduce**
1. Go to www.freecodecamp.rocks
2. Reduce the browser width until the menu button appears in the top right
3. Navigate to www.freecodecamp.rocks/guide
4. Click on the top right menu button
5. Click on the top left logo

The final click can be on any link that doesn't cause a page load.  About, Learn, Sponsors etc.

**Expected behavior**
Navigating to any new page should leave the main nav menu closed or close it if it was open.

**Screenshots**
![MenuBug](https://user-images.githubusercontent.com/15801806/57086868-3a2d0500-6cff-11e9-973a-0f15b939c854.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser Chrome
 - Version 74.0.3729.131 

**Additional context**
I came across this while working on #35943 because my changes for that made this bug appear more readily.  I'd be happy to work on this, since I'm already familiar with that bit of the codebase.

**Comment by ahmadabdolsaheb** [comment]
@ojeytonwilliams So the navbutton's state is hooked up to the store under guideNav(bad naming my bad).

And guideNav/DisplayMenu gets toggled on and off accordingly.

Notice, if DisplayMenu is on in the guides and user navigate to another page,  DisplayMenu's value changes, but not the other way around.

Also, it would be great if you could evaluate a scenario in which menu button is not connected to the store. would we lose any functionality?

![Screen Shot 2019-05-03 at 1 43 14 PM](https://user-images.githubusercontent.com/4591597/57132832-75840e00-6da9-11e9-94cc-beb1020b4bca.png)

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb I had a quick look at this and my first attempt was to go in the opposite direction and add another variable, `displayTopMenu`.  Then I used that to control the top menu (the one in your screen shot) and have `displayMenu` solely responsible for the guide's side nav.  This did work, but I think it was probably overly complicated for something that should be pretty simple.

> Also, it would be great if you could evaluate a scenario in which menu button is not connected to the store. would we lose any functionality?

My first thought is that that could work for the top menu, since it's contained inside `Header`, but I'm not sure how it would work for the guide's side nav.  The value of `displayMenu` needs to be passed to `Guide` and I think the simplest way to do that is via the store.  What do you think?

**Comment by ahmadabdolsaheb** [comment]
Using the store sense then.

**Comment by ojeytonwilliams** [comment]
I've put together a solution that uses `Header`'s state to track the top menu, but still uses the store for the guide's menu.  I'm not 100% sure if using internal state as well as the store is the right approach.  If you think it's better have everything in the store, I'd be happy to rewrite it.

Since this is so entangled with #35943. I will add my changes there.  I hope that's okay.

**Comment by ojeytonwilliams** [comment]
Fixed in https://github.com/freeCodeCamp/freeCodeCamp/pull/35943
