### ISSUE TITLE
[challenge] Use CSS Selectors to Style Elements - wrongfully passes

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35958]
Go to 
- https://www.freecodecamp.rocks/learn/responsive-web-design/basic-css/use-css-selectors-to-style-elements

or

- https://learn.freecodecamp.org/responsive-web-design/basic-css/use-css-selectors-to-style-elements

Run the tests with the default seed code. And get this result...

<img width="831" alt="Screen Shot 2019-05-03 at 9 15 21 AM" src="https://user-images.githubusercontent.com/20648924/57143854-6d19dc00-6d85-11e9-8ca6-b220110e73b0.png">

The "create a style element" test passes without the element added.
sort of related https://github.com/freeCodeCamp/freeCodeCamp/issues/35712

**Tell us about your browser and operating system:**
* Browser Name: firefox
* Browser Version: 66.0.3
* Operating System: high sierra 10.13.6

**Comment by RandellDawson** [comment]
I am unable to replicate this locally or on freecodecamp.rocks.

I am on Windows 10 using Chrome version 74.0.3729.131

**Locally**
![image](https://user-images.githubusercontent.com/5313213/57149489-ac91f980-6d80-11e9-9a30-5105e06b89ef.png)

**freecodecamprocks**
![image](https://user-images.githubusercontent.com/5313213/57149552-ccc1b880-6d80-11e9-8552-bf3bf5c76309.png)

Also, I get the same results on the current production.

**Comment by RandellDawson** [comment]
@moT01 If you put a console.log($('style')), what do you get?

**Comment by moT01** [comment]
<img width="1001" alt="Screen Shot 2019-05-03 at 11 23 55 AM" src="https://user-images.githubusercontent.com/20648924/57151258-0ea92980-6d96-11e9-935b-f86e3c8d2326.png">

I'm only having an issue on firefox - chrome works fine - that being the case I'm not sure how much we need to look into this

**Comment by RandellDawson** [comment]
It seems jQuery is capturing the inline style.  Let me test something using vanilla JavaScript on Firefox.

**Comment by moT01** [comment]
It's my dark mode add-on that's causing issues. It works after disabling it.

**Comment by moT01** [comment]
I wonder if that was the cause of another recent issue I had that others couldn't reproduce - I'm going to have to keep that disabled.

**Comment by RandellDawson** [comment]
@moT01 What is really interesting is that I just tested Firefox (same version as users) but on Windows 10 and do not see this issue.

**Comment by RandellDawson** [comment]
So we can close this?

**Comment by moT01** [comment]
Yes, unless we want to discuss the issue of add-ons affecting things on learn

**Comment by RandellDawson** [comment]
Maybe that should be on a completely different issue vs. just for this particular challenge?

**Comment by moT01** [comment]
yes, it probably should be - I'll create an issue and see if anyone wants to discuss it.
