### ISSUE TITLE
Footer needs to be Sticky.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#35950]
**Expected behavior**
the footer should stick to the bottom of the page when page content is shorter than the viewport height or it should be at the end of the content when content is larger than viewport height;

**Expected:**

![Screen Shot 2019-05-02 at 4 19 15 PM](https://user-images.githubusercontent.com/4591597/57078111-4b254880-6cf6-11e9-9831-c0da5208a809.png)

**Current:**

![Screen Shot 2019-05-02 at 3 50 29 PM](https://user-images.githubusercontent.com/4591597/57076693-ed433180-6cf2-11e9-8ee6-18aac8944023.png)

**Comment by raisedadead** [comment]
Check what we have done for the profile page loader. I think the content area can have a min height of the viewport.

**Comment by moT01** [comment]
Then the footer would be below the viewport when there's no content - I think it might be better to put the `min-height` on the `body`

**Comment by webdevdaemon** [comment]
is this still available, I would like to take a crack at this one if so. Gonna start working on it anyways because it sounds fun.

**Comment by moT01** [comment]
Go for it @webdevdaemon - let us know what you come up with.

**Comment by webdevdaemon** [comment]
I'm on it, day job got busy for a sec and I had a bit of trouble w/ the docker config, but I am GTG now.

Standby for a solution.

Thanks for the opportunity!

**Comment by ahmadabdolsaheb** [comment]
@webdevdaemon Looking forward to it. You are also welcome to discuss your solution here before implementation.

**Comment by ahmadabdolsaheb** [comment]
@moT01, to build on your solution. something along the lines of min-height: 100vh; for the container  div should do it.

**Comment by ValeraS** [comment]
@ahmadabdolsaheb This is done in #35989
