### ISSUE TITLE
turncate-a-string code solution 

### ISSUE THREAD

**Issue by EXPEakhasawneh** [freeCodeCamp/freeCodeCamp#35962]
**Describe your problem and how to reproduce it:**
I think the proposed solution code be achieved in a simpler way 

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blob/6f5610c4f3832d94c377eb179bd65fa15e8bf395/guide/english/certifications/javascript-algorithms-and-data-structures/basic-algorithm-scripting/truncate-a-string/index.md#-advanced-code-solution

**Tell us about your browser and operating system:**
Doesn't matter 
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Mu solution passed tests successfully 
`function truncateString(str, num) {
  // Clear out that junk in your trunk
  if (num >= str.length) {
    return str;
  }
  return str.slice(0, num) + '...';
}

truncateString("A-tisket a-tasket A green and yellow basket", 8);`

![image](https://user-images.githubusercontent.com/29892725/57170294-a0f01280-6e14-11e9-8bb7-9d7b1847f92d.png)

**Comment by RandellDawson** [comment]
@EXPEakhasawneh The [current Basic Code Solution](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/certifications/javascript-algorithms-and-data-structures/basic-algorithm-scripting/truncate-a-string/index.md#-basic-code-solution) is almost identical to yours from a logic standpoint.
```
function truncateString(str, num) {
  // Clear out that junk in your trunk
  if(str.length > num) {
    return str.slice(0,num)+"...";
  } else {
    return str;
  }
}
```
The existing solution may have an extra `else` statement, but yours does not add significant improvement in terms of performance.  I will let some other collaborators share their opinion.

**Comment by EXPEakhasawneh** [comment]
Oh looks like the actual site a bit different from the code base 
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-algorithm-scripting/truncate-a-string/

Learners still on the previous commit https://github.com/freeCodeCamp/freeCodeCamp/commit/7d9b587191b294c27e302809794d728c422c0c3e#diff-a126fcd8a27e3fc062225a78e2b5afb5

**Comment by moT01** [comment]
Yea, it looks like it will be updated on the next push to production - here's the [current beta site](https://www.freecodecamp.rocks/guide/certifications/javascript-algorithms-and-data-structures/basic-algorithm-scripting/truncate-a-string/)

Like Randell said, the solution is almost identical to yours. If you want to change it to what you have, you can go ahead and make a PR - I don't see a problem with either solution, but we probably don't need to keep an issue open for this.

**Comment by EXPEakhasawneh** [comment]
No need to, same idea. closing the issue. would love to see release shipped faster to prod.
