### ISSUE TITLE
[beta/rocks] new challenge improper test or instruction

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35979]
[This new challenge on beta](https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/regular-expressions/check-for-mixed-grouping-of-characters)

<img width="1253" alt="Screen Shot 2019-05-06 at 7 55 34 AM" src="https://user-images.githubusercontent.com/20648924/57226335-7482f480-6fd4-11e9-8f67-270f75c93dc3.png">

Fails with the code in the screen shot - `/(Franklin Roosevelt|Eleanor Roosevelt)/` - The instruction asks to look for "Franklin Roosevelt" but the test checks for "Franklin D. Roosevelt". The challenge passes with this code - `/(Franklin D. Roosevelt|Eleanor Roosevelt)/`

I suggest to just change the instructions to tell the user look for `Franklin D. Roosevelt` instead of `Franklin Roosevelt`

**Comment by lightyaer** [comment]
May I work on this?

**Comment by moT01** [comment]
Yea, I think that's fine - I suppose I should have waited for another person to confirm the issue before adding the label. But yea, go ahead - and we can test it out after the PR is made.

**Comment by RandellDawson** [comment]
@moT01 I do not believe this is a bug.  The instructions also state that the regex should make concessions for middle names.  So, the regex should allow initials or full middle names like "Franklin D. Roosevelt".  The D. is a middle name.

**Comment by moT01** [comment]
Ahh, I missed that part - I have to agree. Not sure if you started already @lightyaer, but you can ignore this as it's not a problem.

**Comment by lightyaer** [comment]
Cool.. Ignored

**Comment by themagicbean** [comment]
If the instruction is "concessions for middle names," then the test is bad because (Franklin D.|Eleanor) will pass the test (just did, Oct 23 2019 2:37 pm) even though the middle initial is hard-coded.
