### ISSUE TITLE
No user tests run.

### ISSUE THREAD

**Issue by Tim15** [FreeCodeCamp/FreeCodeCamp#3597]
Challenge [Waypoint: Iterate over Arrays with map](http://freecodecamp.com/challenges/waypoint-iterate-over-arrays-with-map) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

It says that no user tests were run.

My code:
```javascript
//Use map to add three to each value in the array
var array = [1,2,3,4,5];
// Only change code below this line.

array = array.map(function(val){
  return val + 3;
})

// Only change code above this line.
(function() {return array;})();

```

**Comment by matty22** [comment]
Try throwing a closing ; at the end after })

**Comment by bugron** [comment]
@Tim15 thanks for posting this issue!
As @matty22 mentioned you're missing a semicolon at the end of
```javascript
array = array.map(function(val){
  return val + 3;
})
```
From now on keep in mind that you need to put a semicolon after every operator.
Closing this issue. Feel free to reopen if you still experience problems, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by Tim15** [comment]
Thanks, sorry for the mistake.

**Comment by tbraden30** [comment]
I added the semicolon and i still got an error message. 
![untitled](https://cloud.githubusercontent.com/assets/15311351/10837771/509d8b4a-7e8b-11e5-95e8-0f6142a8b8c4.png)
