### ISSUE TITLE
[rocks/beta] Ugly 404 error pages

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35972]
When you go to a non-existent user profile URL. You get a pretty 404 error page...
https://www.freecodecamp.rocks/asdf
<img width="1237" alt="Screen Shot 2019-05-05 at 10 38 08 AM" src="https://user-images.githubusercontent.com/20648924/57196371-f0703480-6f21-11e9-94ba-61296c91a02d.png">

But if you go to any non-existent URL that is under `learn` or `challenges` and others. You get an ugly error page...
https://www.freecodecamp.rocks/learn/asdf
https://www.freecodecamp.rocks/challenges/asdf
https://www.freecodecamp.rocks/asdf/asdf
<img width="1380" alt="Screen Shot 2019-05-01 at 2 56 56 PM" src="https://user-images.githubusercontent.com/20648924/57196432-6e344000-6f22-11e9-8800-44833d2ebc5d.png">
<img width="515" alt="Screen Shot 2019-05-01 at 2 57 14 PM" src="https://user-images.githubusercontent.com/20648924/57196433-6ffe0380-6f22-11e9-900b-efe635265bdf.png">
These error pages are also missing the footer.

**Comment by ojeytonwilliams** [comment]
Same problem for me.  Also Chrome doesn't display the prettier 404 page properly, either, it looks like this:
![404Chrome](https://user-images.githubusercontent.com/15801806/57239927-8e045a80-702d-11e9-99a2-2a01c39cdf98.png)

I'll try and figure out what's going on.

**Comment by ahmadabdolsaheb** [comment]
I noticed a double footer the 404 as well :)
![image](https://user-images.githubusercontent.com/4591597/57839051-977c8800-77ce-11e9-9fbe-45770770776a.png)

**Comment by ojeytonwilliams** [comment]
Weird!  Does that only happen on certain pages?

**Comment by ahmadabdolsaheb** [comment]
So far, only the local 404.

**Comment by ojeytonwilliams** [comment]
Yep, it's only in development mode.  Presumably Gatsby embeds the 404 page inside an existing page, so the layout gets included twice.
