### ISSUE TITLE
Usability for better understanding

### ISSUE THREAD

**Issue by gratschultz2013** [FreeCodeCamp/FreeCodeCamp#3598]
I am very new to Javascript. I am in the learning stage and I feel these challenges are very hard. I find myself wondering why nothing is explained before starting the challenges. Im on "Waypoint: Use Conditional Logic with If and Else Statements" and there's no explanation on how to do anything or why its being done whatsoever. Making the learning process confusing. Im finding myself in the help room every single challenge because of it.

**Comment by matty22** [comment]
gratschultz2013 - I just worked through that section yesterday.

Be sure to look at the example code given in the explanation on the left and *also* the example code they insert in the editor where you type your code into. Usually they will have done one already and you just have to structure your own conditional like they did, while substituting whatever is necessary.

That waypoint provides an example in the editor.
