### ISSUE TITLE
Add projects to portfolio page?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#35984]
When I go to my settings page. I can see the projects I have completed, and click a button to go to the solutions....
<img width="550" alt="Screen Shot 2019-05-07 at 9 34 04 AM" src="https://user-images.githubusercontent.com/20648924/57308118-605df680-70ab-11e9-9ba3-984dedd0cd8b.png">

But a portfolio page just has a link to certifications and the actual challenges, but not the campers solutions.

I'm wondering if we should add something to the portfolio that gives links to the users actual project solutions. Maybe similar to how it is in the settings.

**Comment by ahmadabdolsaheb** [comment]
I am closing this issue due to the lack of activity.
The is an effort to make the portfolio page more function as a resume.
We should discuss the direction in more details in the next couple of iterations.
