### ISSUE TITLE
[learn] tests should fail when code has error

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36000]
I entered a valid solution and passed all the tests in the picture below. Then I added the `a` on the second line: `var collection = { a` - to make the build fail, but all the test results still have the green check mark like they passed. I think they should go back to failed if there's an error.

<img width="1080" alt="Screen Shot 2019-05-08 at 8 54 04 AM" src="https://user-images.githubusercontent.com/20648924/57380701-163e4900-716f-11e9-995c-8c2e486991db.png">

**Comment by raisedadead** [comment]
> [...] to make the build fail [...]

What do you mean by a build here?

Please elaborate the exact steps with details of the environment you are trying this on, for a repro.

**Comment by moT01** [comment]
it says "Build Failed" at the bottom of the error there. I just mean that when there's an error with a users code - the tests should revert to failed (meaning not green check marks)

**Comment by raisedadead** [comment]
OK, now this makes more sense. I think we should probably reset the tests components to the their initial state gray beaker icon when tests are run followed by as you correctly pointed to the red error state.

**Comment by Stevo99** [comment]
@moT01 are you working on this or is it up for grabs?

**Comment by moT01** [comment]
Go for it @Stevo99

**Comment by Stevo99** [comment]
Ok thanks I will start now!!

**Comment by Stevo99** [comment]
@moT01  hey which section is this from.  Having trouble finding the challenge you referenced up above.

**Comment by moT01** [comment]
[This is the challenge in the picture](https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/basic-javascript/record-collection) - but this needs to be fixed by changing the way the tests are ran on **all** the challenges. So it cannot be fixed in the challenge file - I didn't look into it much but somewhere here perhaps: https://github.com/freeCodeCamp/freeCodeCamp/blob/80eaccc467458b27dd001bf49a2476062289a32d/client/src/templates/Challenges/redux/index.js#L249

**Comment by Stevo99** [comment]
ok Thanks!  what do you think about resetting the tests after the modal closes.  This way either the camper proceeds to the next challenge or they close the modal and then the test is reset.

**Comment by moT01** [comment]
I feel like they should be reset when you hit the run tests button - because you can close the pop-up without going to the next challenge. Maybe they want to review their code or something.

**Comment by Stevo99** [comment]
right.  I feel personally when I was doing these challenges for the first time.  When I would pass all tests and complete the challenge, I would wait there a few moments really proud of what I accomplished and I really liked having the modal with all the green checks. I don't know if it would be as good if all those tests where back to grey.  idk just my opinion lol..

**Comment by ojeytonwilliams** [comment]
@Stevo99 We'd want to keep that behaviour, for sure.  The only thing that should change here is what happens if you click Run the Tests while you have a syntax error in your code.

**Comment by ojeytonwilliams** [comment]
@Stevo99 As Mrugesh said on Gitter, the codebase is a bit complex.  The bit responsible for updating the test results is https://github.com/freeCodeCamp/freeCodeCamp/blob/1c669fd56838b68710062bc09f6e4af34e7cf709/client/src/templates/Challenges/redux/execute-challenge-saga.js#L56-L61
and you can see that if there's an error (which is the case we're looking at) only the console gets updated, not the tests.

One approach would be to look at the code in
https://github.com/freeCodeCamp/freeCodeCamp/blob/1c669fd56838b68710062bc09f6e4af34e7cf709/client/src/templates/Challenges/redux/execute-challenge-saga.js#L82
for inspiration and try to figure out a way to update the tests so they all show as failing.

**Comment by Stevo99** [comment]
OK thanks for the explanation. I was definitely starting to feel like its way over my head.  I will look into this now and let you know how I make out.

**Comment by Stevo99** [comment]
@ojeytonwilliams  I think I may have solved it.  I ended up passing the error to the `executeTests` function.  Then changed the code in the catch statement as follows:
```
 } catch (e) {
    const testResults = yield executeTests(e); <-- I added this line
    yield put(updateTests(testResults));          <-- And this line
    yield put(updateConsole(e));
```
 Seems to be working the way you wanted.   After passing the test I closed the modal and added markup to the test.  When the test is submitted with the added markup it fails and logs error message to console.  Let me know what u think.

**Comment by ojeytonwilliams** [comment]
@Stevo99 In general, once you've got something that looks like it's working, your best bet is to submit a pull request.  That way two things happen.  The continuous integration tests get triggered and we can be 100% sure we're looking at the same changes to the code.  Though obviously the second isn't strictly necessary here, since your code is nice and concise!

My impression is that it's probably best to avoid executing the tests, since we know they fail in this case.  That said, please submit the pull request and I'll give it a proper review as soon as I can!

**Comment by ValeraS** [comment]
IMO, It's better to set an initial state for tests at the beginning, and if the build fails, none of the test results will be displayed as executed.

**Comment by Stevo99** [comment]
>It's better to set an initial state for tests at the beginning

@ValeraS  So a few of the Team Members said that your suggestion is the best way to fix this issue.  I'm not that experienced with this codebase and I was just wondering if maybe you can explain how I can go about setting an initial state for the tests.  I tried to figure it out myself but could not unfortunately.  Any help would be appreciated. Thanks!!
