### ISSUE TITLE
Strange text - declare java variable - few lessons before also (JQuery)

### ISSUE THREAD

**Issue by brettstark73** [FreeCodeCamp/FreeCodeCamp#3600]
Challenge [Waypoint: Declare JavaScript Variables](http://www.freecodecamp.com/challenges/waypoint-declare-javascript-variables) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// var ourName = "Free Code Camp";
var MyName = "Brett";

// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
// You'll learn about functions soon.

if(typeof(myName) !== "undefined"){(function(v){return v;})(myName);}

```
Undefined.

assert((function(){if(typeof(myName) !== "undefined" && typeof(myName) === "string" && myName.length > 0){return true;}else{return false;}})(), 'myName should be a string that contains at least one character in it.');

**Comment by jlslew** [comment]
Try changing `MyName` to `myName`

**Comment by brettstark73** [comment]
dang, thanks!

Brett Stark

Phone: +1 847 481 9736
Skype: brett.stark
GChat: brettstark73@gmail.com
Twitter: http://twitter.com/brettstark
LinkedIn: http://linkedin.com/in/brettstark

**Comment by bugron** [comment]
Closing this issue as it is solved. Feel free to reopen if you still experience problems, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
