### ISSUE TITLE
Dialog Says I Passed This Chalenge, but It Shows As NotPassed On The Curriculum Page

### ISSUE THREAD

**Issue by jhomme** [freeCodeCamp/freeCodeCamp#36018]
**Describe your problem and how to reproduce it:**

The title is self-explanatory. I have maybe two more like this, but this is one of them. 

I bring up the challenge by activating the link from the Curriculum page. I put the code in, and press the Run Tests  button.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/delete-html-elements

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 66.5, 64-bit
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@jhomme Can you please provide a screenshot of such a situation, so we can see what you see?

**Comment by jhomme** [comment]
Hi,
I will try. I am a screen reader user, so let me describe what I am
trying and then I will try the screen shot in the next comment.

- I take the chalenge and get the code correct.
- The dialog comes up with the cute message. "One loop to rule them
all" is my favorite so far.
- I press Submit and go to the next chalenge.
- I open the screen that lists every challenge.
- This one and some others are marked as NotPassed. It seems random to me.
- Right now, I'm pretty far through the Applied Visual Design section.
It looks to me like I have one or two in each section that will not
register as passed. Screen shot in next comment.

On 5/10/19, Randell Dawson <notifications@github.com> wrote:
> @jhomme Can you please provide a screenshot of such a situation, so we can
> see what you see?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/freeCodeCamp/freeCodeCamp/issues/36018#issuecomment-491334397


-- 
==========

Jim Homme

Twitter: @jimhomme
Facebook: http://www.facebook.com/jimhomme
LinkedIn: https://www.linkedin.com/in/jimhomme
Skype: jim.homme
FreeChess: jhomme

**Comment by jhomme** [comment]
![challenge-before](https://user-images.githubusercontent.com/6507685/57549232-fbb3cd80-7330-11e9-8a99-d58a1d2c0d1b.png)
![challenge-before](https://user-images.githubusercontent.com/6507685/57549314-361d6a80-7331-11e9-8ccb-30bae6d8083e.png)
![challenge-code-changed](https://user-images.githubusercontent.com/6507685/57549316-36b60100-7331-11e9-90ee-d59f9a43bf0f.png)
![curriculum-screen](https://user-images.githubusercontent.com/6507685/57549317-374e9780-7331-11e9-8761-f399e4cbbef2.png)
![dialog-showing-passed](https://user-images.githubusercontent.com/6507685/57549320-39185b00-7331-11e9-9469-54203b66b13a.png)




Attempts at capturing screen shots. Hope you can see what's going on.

**Comment by ojeytonwilliams** [comment]
@jhomme Sorry, I was unable to reproduce this.  After I completed a challenge, the curriculum labelled it as Passed, as expected.  Do you encounter the same error on [the beta site](www.freecodecamp.rocks/learn)?

**Comment by jhomme** [comment]
Hi Oliver,
How do I get to it?

Thanks.

Jim

On 5/14/19, Oliver Eyton-Williams <notifications@github.com> wrote:
> @jhomme Sorry, I was unable to reproduce this.  After I completed a
> challenge, the curriculum labelled it as Passed, as expected.  Do you
> encounter the same error on [the beta site](www.freecodecamp.rocks/learn)?
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/freeCodeCamp/freeCodeCamp/issues/36018#issuecomment-492275957


-- 
==========

Jim Homme

Twitter: @jimhomme
Facebook: http://www.facebook.com/jimhomme
LinkedIn: https://www.linkedin.com/in/jimhomme
Skype: jim.homme
FreeChess: jhomme

**Comment by RandellDawson** [comment]
@jhomme https://freecodecamp.rocks/learn

**Comment by jhomme** [comment]
Hi,
It is possible that the screen reader sees this, but it is invisible
to others. I will see if I can find out for sure.

Jim

On 5/14/19, Randell Dawson <notifications@github.com> wrote:
> @jhomme https://freecodecamp.rocks/learn
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/freeCodeCamp/freeCodeCamp/issues/36018#issuecomment-492291381


-- 
==========

Jim Homme

Twitter: @jimhomme
Facebook: http://www.facebook.com/jimhomme
LinkedIn: https://www.linkedin.com/in/jimhomme
Skype: jim.homme
FreeChess: jhomme
