### ISSUE TITLE
Solution is not correct in this challenge.

### ISSUE THREAD

**Issue by tvibhu12** [freeCodeCamp/freeCodeCamp#36019]
**Describe your problem and how to reproduce it:**
[In this challenge ](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method/)solution is incorrect in `Get a Hint` tab.
correct answer should be this 
```js
function alphabeticalOrder(arr) {
  // Add your code below this line
  return arr.sort(function(a,b) {
   return a > b?1:-1;
  });
  // Add your code above this line
}
alphabeticalOrder(["a", "d", "c", "a", "z", "g"]);
```
but it is showing this solution which is incorrect.
```js
function alphabeticalOrder(arr) {
  // Add your code below this line
  return arr.sort(function(a,b) {
    return a > b;
  });
  // Add your code above this line
}
alphabeticalOrder(["a", "d", "c", "a", "z", "g"]);
```

**Add a Link to the page with the problem:**
challenge : https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method/

solution page : https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method/

**Tell us about your browser and operating system:**
* Browser Name: chrome
* Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)
* Operating System: Ubuntu 18.04

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot from 2019-05-10 20-22-41](https://user-images.githubusercontent.com/37179627/57537570-34b96580-7364-11e9-8629-3331a3c08aba.png)

**Comment by RandellDawson** [comment]
This has already been corrected on the master branch and can be seen [here on our beta site](https://www.freecodecamp.rocks/guide/certifications/javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method).  We are just waiting for it to deployed to production.
