### ISSUE TITLE
Clean up references in guide files

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#36020]
Some files in the guide for example [this](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/miscellaneous/storing-mongo-username--password-persistently-using-dotenv/index.md) have user photos in them which might not render the same on client side, for example on lines **88** and **98**, etc. in the file above. The file can be seen in production [here](https://www.freecodecamp.rocks/guide/miscellaneous/storing-mongo-username--password-persistently-using-dotenv).

I'm sure there would be other instances of such in the guide.

In my opinion, these need to be changed to either get the images to display or changed to just reflect the name in text format

**Comment by moT01** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/issues/35518#issuecomment-470417848

**Comment by thecodingaviator** [comment]
Thanks @moT01 for that. So we’ve to fix it to remove the image and leave just the text link. The images would consequently need to be deleted from fCC’s CDN.

cc: @ahmadabdolsaheb

**Comment by RandellDawson** [comment]
@thecodingaviator @moT01 I believe we can close this issue now that the guide is no longer apart of the repo.

**Comment by moT01** [comment]
Sounds good to me.
