### ISSUE TITLE
The line number display issue in the light box.

### ISSUE THREAD

**Issue by jack-gaojz** [freeCodeCamp/freeCodeCamp#36027]
**Describe the bug**
If the codemirror in a lightbox, when the lightbox show, the codemirror linenumber display not correct:
![image](https://user-images.githubusercontent.com/40879710/57576912-49017d80-749e-11e9-8485-5b2f4118a6d9.png)
But when I scroll the scrollbar, the line number will display well:
![image](https://user-images.githubusercontent.com/40879710/57576959-fecccc00-749e-11e9-8011-1f5966ea0419.png)
If I focus on it, then type the "Enter" key, the new line number will display well, the original still has the display issue:
![image](https://user-images.githubusercontent.com/40879710/57577009-1e182900-74a0-11e9-9c60-aac0cc631264.png)

I have set the "autoRefresh" property and reference the "autoRefresh" plugin:
```
var codeEditor = $(".code-editor");
var editor = CodeMirror.fromTextArea(codeEditor.get(0), {
	mode: "text/x-csharp",
	indentWithTabs: true,
	smartIndent: true,
	lineNumbers: true,
	lineWrapping: false,
	matchBrackets: true,
	autoRefresh: false,
	extraKeys: { "Ctrl-Space": "autocomplete" }
});

editor.setSize("auto", "200px");
editor.on("change", function() {
	$("#Expression").val(editor.getValue());
});
```

Another issue is the text area connot get the codemirror value, I have to get the value via handle the "change" event to archived it.
```
editor.on("change", function() {
	$("#Expression").val(editor.getValue());
});
```
And if I want to select some codes vai the mouse in the code mirror, the display UI not make sense and the select behavor not comfortable.
![image](https://user-images.githubusercontent.com/40879710/57577069-63892600-74a1-11e9-9366-adf78c33b58e.png)

I try to use the "refresh()" to fix it, but still failed:
![image](https://user-images.githubusercontent.com/40879710/57577090-f629c500-74a1-11e9-9d07-a5d6501b883e.png)
The first two columns will not display well.
`editor.refresh();`

BTW, if the codemirror in a normal page, it works fine.

**Expected behavior**
1. The line number should display well.
2. The code select should works fine.

**Screenshots**
Above all screenshots.

**Desktop (please complete the following information):**
 - OS: Win 10 64bit
 - Browser: chrome
 - Version: 74.0.3729.108 (Official Build) (64-bit)

**Additional context**
Codemirror Version: 5.42.2

Thanks so much, the codemirror is a so amazing editor!

**Comment by RandellDawson** [comment]
@jack-gaojz What does this have to do with the freeCodeCamp repo?

**Comment by jack-gaojz** [comment]
Oh my god, it's my big mistake. I am very sorry for that.
