### ISSUE TITLE
Test Case bug in Challenge: Applied Visual Design: Use the s Tag to Strikethrough Text

### ISSUE THREAD

**Issue by sabique** [freeCodeCamp/freeCodeCamp#36022]
**Describe your problem and how to reproduce it:**
The test case is passed though I have not added the **s tag** around the word Google in the **h4 tag**, it is counting the **s tag** around Google word in the **p tag** as valid.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-s-tag-to-strikethrough-text/

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 74.0.3729.131 (Official Build) (64-bit)
* Operating System: Windows 10 64-bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![screenshot-learn freecodecamp org-2019 05 08-05-03-03](https://user-images.githubusercontent.com/8267052/57561925-77069500-73ac-11e9-9411-2e6c0ba89991.png)

**Comment by RandellDawson** [comment]
@sabique Thank you for reporting this bug.  I can confirm it needed to be fixed and I have created a pull request (#36022) which should resolve the issue.
