### ISSUE TITLE
Link Broken guide - Basic CSS: Improve compatibility with Browser Fallbacks

### ISSUE THREAD

**Issue by Saif-Shines** [freeCodeCamp/freeCodeCamp#36024]
**Describe your problem and how to reproduce it:**

1. Navigate to freecodecamp.org > Basic CSS section
2. Module - Basic CSS: Improve Compatibility with Browser Fallbacks
3. Click "Get A Hint"
4. I found 404 error.

**Add a Link to the page with the problem:**

- Try opening: https://guide.freecodecamp.org/certifications/responsive-web-design/basic-css/improve-compatibility-with-browser-fallbacks

**Tell us about your browser and operating system:** 

* Browser Name: Chrome
* Browser Version: [See Here](https://www.whatismybrowser.com/w/4HBWZ9E) for complete Details
* Operating System: Ubuntu 18.04

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
Thanks for reporting this issue, however, it has been fixed (a new guide article was created), but has yet to deploy to production.  You can take a [look here](https://www.freecodecamp.rocks/learn/responsive-web-design/basic-css/improve-compatibility-with-browser-fallbacks) to see for yourself.  I am closing this issue for now.
