### ISSUE TITLE
Include challenges on Promises before introducing Fetch API

### ISSUE THREAD

**Issue by leodaher** [freeCodeCamp/freeCodeCamp#36035]
There is an open PR for introducing the Fetch API (#36033). But knowledge about the concept of Promises is definitely needed before this introduction. We need to discuss where these challenges about Promises should be included, and how they are going to be structured.

**Comment by moT01** [comment]
I could come up with a rough draft for some challenges on this. Probably 2-3 challenges. Not quite sure where to put them, but perhaps right before the fetch lesson as is it pretty related.

**Comment by leodaher** [comment]
What do you think about putting them in the ES6 section of Javascript Algorithms And Data Structures Certification? I think Promises were introduced in ES6, right?

**Comment by thecodingaviator** [comment]
I believe introducing them at the very end of the ES6 section would be the best. Although, I'm not sure if this is something we'd rather want to take up on the curriculumExpansion repo rather than here

**Comment by thecodingaviator** [comment]
On a closer look, I see that we have some challenges as follows:

![image](https://user-images.githubusercontent.com/34807532/57681406-3e391b00-764d-11e9-951b-342e7e8fc0ee.png)

**Comment by moT01** [comment]
Is there something specific you are you trying to show us in that picture @thecodingaviator?

**Comment by thecodingaviator** [comment]
I wanted to say that we should plan on putting the fetch challenge in this section and the Promises challenge in the ES6 section @moT01
