### ISSUE TITLE
[beta] Challenge Basic CSS: Create a custom CSS Variable is missing a period in its description

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#36038]
**Describe your problem and how to reproduce it:**

Challenge `Basic CSS: Create a custom CSS Variable` is missing a period in its description.

![Untitled](https://user-images.githubusercontent.com/25715018/57642576-d7cae300-75e1-11e9-9c43-6cdb2f836a8a.png)

**Add a Link to the page with the problem:**

https://www.freecodecamp.rocks/learn/responsive-web-design/basic-css/create-a-custom-css-variable

---
Here is the file that needs to be edited: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-css/create-a-custom-css-variable.english.md

**Comment by huyenltnguyen** [comment]
Btw, I think there is a typo in the description as well:

> To create a CSS Variable,...

should be

> To create a CSS variable,...

**Comment by moT01** [comment]
Looks like those could both changed.
