### ISSUE TITLE
[beta] Challenge Basic CSS: Cascading CSS variables is missing a keyword

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#36036]
**Describe your problem and how to reproduce it:**

Challenge `Basic CSS: Cascading CSS variables` has a missing keyword in its description.

![Untitled](https://user-images.githubusercontent.com/25715018/57612480-1e4b1e00-759f-11e9-9cbb-01e47c0c9109.png)

**Add a Link to the page with the problem:**

https://www.freecodecamp.rocks/learn/responsive-web-design/basic-css/cascading-css-variables

**Comment by RAJESH-UIUX3D** [comment]
The missing word is 'HTML'.
**It should be like this:**
:root is a pseudo-class selector that matches the root element of the document, usually the HTML element.

https://www.freecodecamp.rocks/learn/responsive-web-design/basic-css/cascading-css-variables
