### ISSUE TITLE
Phrasing Issue on Basic JavaScript: Iterate Through an Array with a For Loop

### ISSUE THREAD

**Issue by organicdude** [freeCodeCamp/freeCodeCamp#36030]
I think the below is phrased in a confusing way.

```
Remember that Arrays have zero-based numbering, which means the last index of the array is length - 1. Our condition for this loop is i < arr.length, which stops when i is at length - 1.
```

I thought it was saying "the last index of the array has a length of -1".

This was very strange to me because how could an array index have a length of negative 1?

If it was using the grey background with red lettering, and it said "arr.length-1", then it would be much more clear. 

I nearly posted on the forum "How can an index have a length of negative 1?" - because I thought maybe when you loop past an index that exists, it loops back on itself.

Anyway - it may be worth updating.

**Comment by RandellDawson** [comment]
@organicdude Would you like to help us update this challenge?  I agree highlighting the `length - 1` part like the following, could help make it clearer.  It is as simple as adding code tags around the code parts like below:
```
Remember that Arrays have zero-based numbering, which means the last index of the array is <code>length - 1</code>. Our condition for this loop is i < arr.length, which stops when i is at <code>length - 1</code>.
```

**Comment by organicdude** [comment]
Hi Randell! That would be very fun.

Is there a document I can read to learn how to update that challenge?

**Comment by RandellDawson** [comment]
Yes, there are two.

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-coding-challenges.md

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-curriculum-challenges.md

If you need help or have any questions, drop a question on our [Contributors Gitter channel](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by organicdude** [comment]
So I found that I just have to find the file inside the code base - hit the pencil to edit it, and then make the update.

But I didn't find a link to the code base - can you please advice me on where that is?

**Comment by RandellDawson** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/iterate-through-an-array-with-a-for-loop.english.md

**Comment by organicdude** [comment]
Do you see the change I submitted? I can't tell.

**Comment by RandellDawson** [comment]
Did you fork the freeCodeCamp repo yet?  You would make the changes on your forked repo and then create a pull request to the master branch of the actual freeCodeCamp repo from your forked branch.

**Comment by RandellDawson** [comment]
It appears your current fork of the freeCodeCamp repo is extremely out of date.  The easiest way to bring your fork up to date, is to follow the instructions in the How to setup Free Code Camp locally, but I did find the following which supposedly allows you to sync up without setting up locally.  The other option is to just delete your current fork on your account, refork it, and then make your changes, then create the pull request.

https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser

**Comment by gokulsiva** [comment]
Is this open, can I take this ?

**Comment by RandellDawson** [comment]
@gokulsiva Another user has asked to work on this.

**Comment by gokulsiva** [comment]
> @gokulsiva Another user has asked to work on this.

Thanks. Will look for another and take it.

**Comment by RandellDawson** [comment]
We will leave yours open and if @organicdude does not create a PR in the next couple of days, then we can review yours.

**Comment by gokulsiva** [comment]
OOPS... Deleted my PR. Will follow this thread, if @organicdude doesn't create PR will submit a PR in couple of days. Sorry for my hastiness.

**Comment by Kungfoosian** [comment]
Is this still available? I'm new but I'm willing to give it a shot!

**Comment by RandellDawson** [comment]
@Kungfoosian Someone is already working on this one.

**Comment by organicdude** [comment]
I'm sorry for not fixing this yet. I have been under the weather.

I'm going to do an up to date pull now on the FCC code base, make the modification, and then give it to you for review.

**Comment by RandellDawson** [comment]
@organicdude Thanks for the update.  Just submit a PR when you feel like yourself again.

**Comment by organicdude** [comment]
Haha I know PR stands for pull request, so as soon as I can figure out how to do that correctly (according to the docs you've posted above), I will do that.

**Comment by organicdude** [comment]
Hi Randell - I think I submitted the changes I wanted to make. How does it look from your end?

**Comment by sudiptog81** [comment]
It could be rephrased as `... the last index of an array is one less than the length of the array (arr.length - 1)`.
