### ISSUE TITLE
Multiple Issues with Caesars Cipher Guide

### ISSUE THREAD

**Issue by navjotjsingh** [freeCodeCamp/freeCodeCamp#36044]
**Describe your problem and how to reproduce it:**
**First Issue:** The Basic solution uses call() function but doesn't include any reference to it.
**Second Issue:** The Basic solution doesn't work when you use it as a solution for the challenge. You get the following error on the beta site:

> rot13("SERR PBQR PNZC") should decode to FREE CODE CAMP
> rot13("SERR CVMMN!") should decode to FREE PIZZA!
> rot13("SERR YBIR?") should decode to FREE LOVE?
> rot13("GUR DHVPX OEBJA SBK WHZCF BIRE GUR YNML QBT.") should decode to THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG.
> 
And the following error on the old Site

> assignment to undeclared variable x
> assignment to undeclared variable x
> assignment to undeclared variable x
> assignment to undeclared variable x

I guess setting 
`x = char.charCodeAt(0);`
to
`let x = char.charCodeAt(0);`
fixes this issue.

**Add a Link to the page with the problem:**
https://www.freecodecamp.rocks/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/caesars-cipher
https://www.freecodecamp.rocks/guide/certifications/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/caesars-cipher/

**Tell us about your browser and operating system:**
* Browser Name: Mozilla Firefox
* Browser Version: 66.0.5
* Operating System: Windows 10

One more thing. The error generated on the old site is helpful whereas the one on the new site isn't. Probably something to look at.

**Comment by RandellDawson** [comment]
@navjotjsingh That is a valid point regarding the error message, but that is a different issue related to how the challenge tests are ran.  I have gone ahead and created a PR (#36046) to address the solution in the Guide, but the last issue you mentioned will have to be discussed in a separate issue (feel free to create it if you have the time).

@ValeraS I could not find any outstanding issues regarding why this does not show the error "assignment to undeclared variable x" which does show in the actual browser console.  Are errors like this being suppressed on showing in the fake console for any reason?
