### ISSUE TITLE
Waypoint isn't clear enough

### ISSUE THREAD

**Issue by Majeye** [FreeCodeCamp/FreeCodeCamp#3604]
The following waypoint isn't clear enough to understand what is expected of the coder.

Challenge [Waypoint: Manipulate Arrays With pop](http://freecodecamp.com/challenges/waypoint-manipulate-arrays-with-pop) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// var numbers = [1,2,3];
// console.log(numbers); // logs [1,2,3]
// var removed = numbers.pop();
// console.log(numbers); // logs [1,2]
// console.log(removed); // logs 3

var myArray = ["John", 23, ["cat", 2]];
// Only change code below this line.

var removed = myArray; // This should be ["cat", 2] and myArray should now be ["John", 23]

// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
// You'll learn about functions soon.
(function(y, z){return 'myArray = ' + JSON.stringify(y) + ' & removed = ' + JSON.stringify(z);})(myArray, removed);

```

**Comment by Majeye** [comment]
I figured it out on my own.. but if someone new to FCC sees it, they'll be confused.   It really is a little too vague.

**Comment by diegofcornejo** [comment]
The console.log at the init, show how use pop() function in an array, you should add pop() function to your var like var myArray = myArray.pop() 

https://gyazo.com/04f151671680c0aaa1d63f2678afa004

**Comment by bugron** [comment]
@Majeye thanks for posting this issue!
This is from description:
>.pop() is used to "pop" a value off of the end of an array. We can retrieve this value by performing pop() in a variable declaration.
>Use the .pop() function to remove the last item from myArray.

Lines 1-5 (comments) in code editor explain with an example what the `pop` does so you need to use the same for `myArray` to achieve expected result.
Closing this issue. Feel free to reopen if you still experience problems, or have a suggestion what to change to make things better, thanks.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
