### ISSUE TITLE
[curriculum] regex upper/lower bounds tests not good enough

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36058]
4 tests on this [challenge](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/specify-upper-and-lower-number-of-matches/) are able to pass with an improper regex...

```
let ohStr = "Ohhh no";
let ohRegex = /h{3,6}/; // Change this line
let result = ohRegex.test(ohStr);
```

This should fail tests 3-6. It does not.

I can make a PR for this.

**Comment by RandellDawson** [comment]
Go for it!
