### ISSUE TITLE
Proposal to update this boilerplate to allow it to be used for all advanced node challenges

### ISSUE THREAD

**Issue by clandau** [freeCodeCamp/freeCodeCamp#36050]
I am proposing that we combine this boilerplate with the socialauth and socketio challenges boilerplate. 
https://github.com/freeCodeCamp/boilerplate-socialauth
https://github.com/freeCodeCamp/boilerplate-socketio
Doing this would make the transition through the challenges smoother. The challenges build on each other and there doesn't seem to be a need to change boilerplates while working through them, in fact it adds confusion and setup work. The socket.io boilerplate uses the GitHub login that was set up in the social auth challenges. Moving to the new boilerplate for these challenges makes it necessary for the student to copy and paste the .env file, and request a new clientId and client secret from GitHub to allow the program to run. There's also a point in the challenges where the code is broken into modules (https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/clean-up-your-project-with-modules), only to change to the new boilerplate without modules in the next challenge. 

While working on this I would also like to do a few updates, including the node and mongodb versions. MongoDb to version 3.x, which would mean changing some code in the challenges as well. There's also depreciated method(s) (mongoClient) used that should be updated. 
Issue for reference:
https://github.com/freeCodeCamp/freeCodeCamp/issues/17781

Thoughts on combining the the boilerplates into one? I am willing to take this on.

**Comment by clandau** [comment]
Adding “finished projects up to this point” gists in the challenges at the points where the boilerplates change over could help. These exist in the first few projects but then stop.

**Comment by clandau** [comment]
My plan would be to add the chat.pug view to the first boilerplate, along with adding some conditional code to add to the index and profile views to show new fields as you move along the challenges. A few instructions would need to be modified in the challenges, but overall I don't think it would be that difficult to make the changes.

**Comment by moT01** [comment]
So to be clear here - you want to combine these three boilerplates...
https://github.com/freeCodeCamp/boilerplate-advancednode/
https://github.com/freeCodeCamp/boilerplate-socialauth
https://github.com/freeCodeCamp/boilerplate-socketio/

And it looks like those three boilerplates cover all the `Advanced Node and Express` lessons. 

It sounds like you have thought it out pretty good - Did you recently go through those lessons? I don't see a problem with it, if you can make it work - but I can't say for sure if it's a good idea, and I can't say if anything else would need to be changed if these are combined. Maybe someone else can weigh in here and give you the "go ahead".

**Comment by clandau** [comment]
Yes, that's what I'd like to do. I originally did the challenges about a year ago and fixed some little issues that I found along the way. I have gone through all the challenges again recently to remind myself of the pain points and identify potential issues. 

https://github.com/freeCodeCamp/freeCodeCamp/issues/17068  (here's when I first brought this up...ha)

The biggest changes to the boilerplate would be to the pug views, a slightly different index page to allow for the additional challenges. 

One potential issue is that I would have to change some instructions on a couple of challenges, and fix all the links to the repo/glitch starters. So it would involve combining multiple pull requests.
