### ISSUE TITLE
Broken Link on Challenge Guide

### ISSUE THREAD

**Issue by anEternalFlame** [freeCodeCamp/freeCodeCamp#36062]
Describe your problem and how to reproduce it:
The "Get a Hint" link to the guide page is broken for a specific challenge.

Broken link:
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement

The correct link:
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for...in-statement/

Challenge with broken "Get a Hint" Link:
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement

This was a known issue in the past and was supposedly resolved, however a recent commit reverted the fix.
https://github.com/freeCodeCamp/freeCodeCamp/issues/34782

**Comment by RandellDawson** [comment]
@anEternalFlame Not sure what commit you think reverted the fix.  I just tested the master branch locally and the links work fine.  The change will not show up in production as we are still waiting for the current master to be deployed to production.  I am going to close this issue as closed.  If you have further information which shows how this is not resolved on the master branch, please share and we can open this issue back up.

Thank you.
