### ISSUE TITLE
[curriculum] glitch doesn't allow version "1.0"

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36068]
I noticed this while looking at another issue. Glitch is giving me an error when using version "1.0" in my package.json file. It only seems to work when I use a third number: "1.0.0" - I'm not sure if this has always been the case since I don't think it threw this error in the past. But [this challenge](https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/add-a-version-to-your-package-json) suggests to use a two digit version. It should probably be changed if this isn't allowed.

EDIT: actually the project will still run with the invalid version - I thought it was causing the project not to run. But glitch does still give an error about it.

**Comment by jagzmz** [comment]
@moT01 made a PR  #36074 :+1:
