### ISSUE TITLE
APIs and Microservices Projects - Solutions links are appended with "/"

### ISSUE THREAD

**Issue by jagzmz** [freeCodeCamp/freeCodeCamp#36067]
**Describe the bug**

- Submitting the solution link as "https://xyz.com/" produces an error.
- Submitting "https://xyz.com" does not.

Whenever we submit a solution link "https://xyz.com/" it is appended with "/_api/" so resultant solution gives "Not Found/Timeout error" and the same link submitted without "/" like "https://xyz.com" gives solution as accepted.

**To Reproduce**
1. Go to [Challenge Link](https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/how-to-use-package-json-the-core-of-any-node-js-project-or-npm-package/)
2. Click on 'solution input box'
3. Enter "https://freecodecamp-practices.herokuapp.com"
4. The solution gets accepted.
5. Enter "https://freecodecamp-practices.herokuapp.com/"
6. See error

**Expected behavior**
This should be tackled as Chrome appends "/" by default to any domain URL you copy, so people who would copy URL from search bars will get URLs appended with "/" hence producing wrong results.

**[Challenge Git Link](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/managing-packages-with-npm/how-to-use-package.json-the-core-of-any-node.js-project-or-npm-package.english.md)** 
This file shows the testString is directly appended with "/_api" without checking if the input URL contains "/" at the end or not.

**Screenshots**
![Bug](https://i.imgur.com/sYPce5l.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Browser: Google Chrome
 - Version 73.0.3683.75

**Comment by moT01** [comment]
I am not having this problem - my project will pass the tests with or without the trailing `/`
https://fcc-manage-npm-packages.glitch.me/ and 
https://fcc-manage-npm-packages.glitch.me both pass for me in chrome

Can you share a share a screen shot of the error?

**Comment by jagzmz** [comment]
> I am not having this problem - my project will pass the tests with or without the trailing `/`
> https://fcc-manage-npm-packages.glitch.me/ and
> https://fcc-manage-npm-packages.glitch.me both pass for me in chrome
> 
> Can you share a share a screen shot of the error?

Updated

**Comment by moT01** [comment]
hmm, it's strange that my project will give a good response when that string is appended but not yours
https://fcc-manage-npm-packages.glitch.me//_api/package.json - package as response
https://freecodecamp-practices.herokuapp.com//_api/package.json - not found as response

not sure what is causing this - the only difference seems to be that I'm using glitch and you're using heroku

in fact mine will work like this... https://fcc-manage-npm-packages.glitch.me///////////////////////////_api///////////////////package.json

so maybe how the two websites process a route or something? can they do that? glitch strips out the extra `/` or something? weird

**Comment by jagzmz** [comment]
> in fact mine will work like this... https://fcc-manage-npm-packages.glitch.me///////////////////////////_api///////////////////package.json

Weird, would u check with an alternative hosting if the problem persists?
If the problem persists the last solution would be stripping the las `/` from input url

**Comment by jagzmz** [comment]
@moT01  Did you try this 
[https://freecodecamp-practices.herokuapp.com//_api/package.json](https://freecodecamp-practices.herokuapp.com//_api/package.json)
It gives a response with `Not Found` the same as it is shown in the screenshot I posted.
So I guess the problem is with the routing of Heroku.
