### ISSUE TITLE
grammar error

### ISSUE THREAD

**Issue by phonghly26** [FreeCodeCamp/FreeCodeCamp#3607]
Challenge  Waypoint: Condense arrays with reduce  http://www.freecodecamp.com/challenges/waypoint-condense-arrays-with-reduce  has an issue. User Agent is: code>Mozilla/5.0  Windows NT 6.1; WOW64; rv:41.0  Gecko/20100101 Firefox/41.0 /code>. Please describe how to reproduce this issue, and include links to screenshots if possible. My code:    javascript var array    4,5,6,7,8 ; var singleVal   0; // Only change code below this line. // Only change code above this line.  FUNCTION   {return singleVal;}   ;     

singleVal should have been set to the result of you reduce operation : change "you" to "your"

**Comment by bugron** [comment]
@phonghly26 thanks for pointing this out!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
