### ISSUE TITLE
My code works outside of the FCC editor, but crashes otherwise

### ISSUE THREAD

**Issue by mels065** [FreeCodeCamp/FreeCodeCamp#3608]
I can't get my code to run in the FCC editor. It crashes every time I try to run it.

HermanFassett on the FCC chat room pointed out that when he tried to run it outside of FCC, it worked. I tried it myself and it worked for me as well.

I'm not sure what the issue might be. Anyone have any ideas?

Challenge [Bonfire: Exact Change](http://freecodecamp.com/challenges/bonfire-exact-change) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
var CASH_DENOM = { 
  'ONE HUNDRED': 100.00, 
  'TWENTY': 20.00, 
  'TEN': 10.00, 
  'FIVE': 5.00, 
  'ONE': 1.00, 
  'QUARTER': 0.25, 
  'DIME': 0.10, 
  'NICKEL': 0.05, 
  'PENNY': 0.01
}; 

function drawer(price, cash, cid) { 
  var change = cash - price; 
  if (cid < change) { 
    return "Insufficient Funds"; 
  } else if (cid === change) { 
    return "Closed"; 
  } else { 
    var cash_due = []; 
    while (change > 0) { 
      for (var i = cid.length-1; i >= 0; i--) { 
        if (change >= CASH_DENOM[cid[i][0]] && 
            cid[i][1] > 0) { 
          var j = haveSomeCash(); 
          if (j === -1) { 
            cash_due.push([cid[i][0], 0.00]); 
            j = cash_due.length-1; 
          } 
          cash_due[j][1] = Number.parseFloat((cash_due[j][1] + CASH_DENOM[cid[i][0]]).toFixed(2)); 
          change = Number.parseFloat((change - CASH_DENOM[cid[i][0]]).toFixed(2)); 
          cid[i][1] = Number.parseFloat((cid[i][1] - CASH_DENOM[cid[i][0]]).toFixed(2));
          break; 
        } 
      } 
    } 
    
    return cash_due; 
  }
  
  function haveSomeCash() { 
    for (var j = 0; j < cash_due.length; j++) { 
      if (cash_due[j][0] === cid[i][0]) { 
        return j; 
      } 
    } 
    return -1; 
  } 
} 

// Example cash-in-drawer array: 
// [['PENNY', 1.01], 
// ['NICKEL', 2.05], 
// ['DIME', 3.10], 
// ['QUARTER', 4.25], 
// ['ONE', 90.00], 
// ['FIVE', 55.00], 
// ['TEN', 20.00], 
// ['TWENTY', 60.00], 
// ['ONE HUNDRED', 100.00]] 
drawer(19.50, 20.00, [['PENNY', 1.01], ['NICKEL', 2.05], ['DIME', 3.10], ['QUARTER', 4.25], ['ONE', 90.00], ['FIVE', 55.00], ['TEN', 20.00], ['TWENTY', 60.00], ['ONE HUNDRED', 100.00]]);
```

**Comment by ltegman** [comment]
Your code works for the first test case, but it goes into an infinite loop on some of the others, which is why you see the error on FCC only. Try running your code with the call `drawer(19.50, 20.00, [['PENNY', 0.01], ['NICKEL', 0], ['DIME', 0], ['QUARTER', 0], ['ONE', 0], ['FIVE', 0], ['TEN', 0], ['TWENTY', 0], ['ONE HUNDRED', 0]]);` and you will see that it gets into this infinite loop no matter where you run it.

**Comment by mels065** [comment]
Wow, I can't believe I missed that. Thanks for your help.
