### ISSUE TITLE
Accessing Nested Objects challenge could use a small change in instructions

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#36080]
Based on [this forum thread discussion](w.freecodecamp.org/forum/t/accessing-nested-objects/136398/) and others like it, I am wondering if we should slightly modify the instructions for the [Accessing Nested Objects](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/accessing-nested-objects/) challenge.

The last test is written to only accept a solution were the properties "car" and "inside" must use dot notation and the "glove box" property (of course) has to use bracket notation.  The instructions only state the camper to use bracket notation on the "glove box", but does not make it clear bracket notation can not be used on "car" and "inside".  Many campers don't understand why their solution (which would technically get the "glove box" property's value) fails the last test.  With the current instructions, all three of the following should be accepted because the only real requirement in the current instructions is "Use bracket notation for properties with a space in their name."

```
var gloveBoxContents = myStorage.car.inside["glove box"];
var gloveBoxContents = myStorage.car["inside"]["glove box"];
var gloveBoxContents = myStorage["car"].inside["glove box"];
```

Since it is a "best practice" for more readable code to use dot notation where possible, I am wondering what others think about changing the instructions to something like the following:

> Access the `myStorage` object and assign the contents of the `glove box` property to the `gloveBoxContents` variable. Use dot notation for all properties where possible, otherwise use bracket notation.

This way the existing test can be used and the camper gets to use the knowledge they have already obtained from previous lessons (i.e. properties with spaces need bracket notation) without us explicitly telling them to use bracket notation (which felt a bit like hand-holding to me).

**Comment by ojeytonwilliams** [comment]
Seems good to me.  It should help them realise that they need both forms without straight up telling them the answer.

**Comment by moT01** [comment]
I'm actually not a fan of this. I don't like when valid code will fail - It think it can get people thinking their method is wrong when it is actually correct - I would rather see something like it is and maybe just add a note about how using the dot is best practice when applicable.

**Comment by RandellDawson** [comment]
@moT01 When possible, we try to imply "best practices" without just coming out and saying it is a "best practice".  If we don't care about teaching a "best practice", then I have already written the necessary `testString` to allow all three of the following:
```
var gloveBoxContents = myStorage.car.inside["glove box"];
var gloveBoxContents = myStorage.car["inside"]["glove box"];
var gloveBoxContents = myStorage["car"].inside["glove box"];
```
I would be comfortable in doing this too, but I lean slightly towards my other idea for two reasons:
1. Teaching to use dot notation possible over bracket notation promotes better code readability.
2. Forcing users to think about alternative ways of accessing object properties (not just using bracket notation for everything) gets the users out of their comfortable zone.

**Comment by ojeytonwilliams** [comment]
I've thought about this a little more and I think it serves as a nice reminder that both forms of notation work.  This lesson appears a little bit after they're introduced, so should serve as useful reinforcement.  Ordinarily I prefer fairly permissive tests, but the strictness has a use here.

**Comment by NoobyScoob** [comment]
Hey @RandellDawson , I think it's a good idea.
Can I take this up to make my first contribution(PR) to freecodecamp?

**Comment by RandellDawson** [comment]
@NoobyScoob Go for it.  It is all yours.  Let us know if you have any questions.  For fastest replies, visit our [Contributors Gitter channel](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by Sterzing** [comment]
I was one of the folks who was confused by this and posted on the forum so I'm definitely in favor of a change. Either making bracket notation a valid solution when it is indeed valid for the code to work, or indicating that FCC requires dot notation unless the outcome requires bracket notation (string with space/variable).

I am curious why FCC doesn't state 'best practices'. Not a criticism at all, just wondering. I obviously hadn't picked up that is was implied that dot notation should take precedence over bracket if they serve the exact same purpose in that particular situation.

FWIW I found [this article](https://codeburst.io/javascript-quickie-dot-notation-vs-bracket-notation-333641c0f781) that helped a lot but not sure FCC wants to start linking to codeburst.

**Comment by NoobyScoob** [comment]
@RandellDawson I wonder what about the changes in other languages?

**Comment by RandellDawson** [comment]
Don't worry about the other languages.  We are no longer translating the current curriculum challenges.

**Comment by NoobyScoob** [comment]
@RandellDawson I submitted a PR for the update by following the contribution guidelines.
