### ISSUE TITLE
Basic Data Structures: Generate an Array of All Object Keys with Object.keys() - Get A Hint - Missing Link

### ISSUE THREAD

**Issue by TantienHime** [freeCodeCamp/freeCodeCamp#36096]
**Describe your problem and how to reproduce it:**
On the lesson for "Basic Data Structures: Generate an Array of All Object Keys with Object.keys()", when I click on the link for "Get A Hint", I get a 404 error. I also note, that when the page first loads, the message appears in the top left corner, and on hover, it recenters to the middle of the page, shown in the attached screenshot.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/generate-an-array-of-all-object-keys-with-object-keys

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 
* Operating System: MacOS Mojave

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
The screenshot is the same as my previously submitted issue, so the link is from that one.
![Screen Shot 2019-05-20 at 12 04 42](https://user-images.githubusercontent.com/6810025/58036029-1c7ddf00-7af8-11e9-9245-f90c1ae0aae8.png)

**Comment by RandellDawson** [comment]
Thank you for reporting this issue, but it has been fixed on our master branch. The reason you do not see it fixed is because the master branch has not been deployed since October 2108 after a major repo restructuring. When it is deployed, the issue will no longer be present in production.
