### ISSUE TITLE
Information Security and Quality Assurance Certification always shows today's date

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#36094]
![image](https://user-images.githubusercontent.com/4591597/58013493-5bfbf980-7aff-11e9-8490-a2cf737ff337.png)

related: #18128

**Comment by METALMAN01** [comment]
HOOK ME UP

**Comment by thecodingaviator** [comment]
@METALMAN01 If you're asking for this to be assigned to you, @ahmadabdolsaheb is already working on it. Feel free to have a look around on the other issues though!

**Comment by ahmadabdolsaheb** [comment]
@METALMAN01 thanks for your interest. I am working on a similar issue that might resolves this as well. If it did not, I will give you more context so you could work on this more efficiently.

**Comment by ahmadabdolsaheb** [comment]
Some users have this issue and some do not.

It is likely that the id of certification has been changed and the backend fails to find that record for  since it looks for the new id.

**Comment by ahmadabdolsaheb** [comment]
Thanks to @moT01 for investigation.
The issue might be caused because of the id change here.
https://github.com/freeCodeCamp/curriculum/commit/4c650a6d8544f56904a6a0a287df1465ee1d72e9#diff-83023cc91e4914f72a3af824e2bcc2e9L7

**Comment by ahmadabdolsaheb** [comment]
The issue seems to be non-existent. Please feel free to re-open this issue if anyone comes across an inaccurate date on an Information Security and Quality Assurance Certification.
