### ISSUE TITLE
Remove CSS/JS minification infrastructure

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/freecodecamp#361]
This crashed last night, and makes our js and css unreadable in the browser. It's not worth it for the marginal performance gains.

**Comment by QuincyLarson** [comment]
Hey Berkeley, since you started removing this can you finish removing it? We all agree that this is an unnecessary complication.

**Comment by BerkeleyTrue** [comment]
Alrighty. I WIll get in the next couple of days.

**Comment by QuincyLarson** [comment]
@berkeleytrue While you're fixing our static assets and removing connectAssets, could you help us decide whether we need both of these: 
```javascript
app.use(
  express.static(path.join(__dirname, 'public'), {maxAge: 31557600000})
);
// todo
// why are there two express.static declarations?
app.use(express.static(__dirname + '/public', { maxAge: 86400000 }));
```

**Comment by QuincyLarson** [comment]
@berkeleytrue Actually, I'm making a ton of progress on this. So why don't you stay focused on React and I'll take this. Bower is amazing!
