### ISSUE TITLE
Large Sum

### ISSUE THREAD

**Issue by DavidWesley** [freeCodeCamp/freeCodeCamp#36106]
**Describe your problem and how to reproduce it:**
The challenge reader does not accept my code which, apparently, is correct. How to solve?

```
function largeSum(arr) {
  const sum = arr.reduce((t, el) => Number(t) + Number(el)).toString();
  const firts10dDigits = Number(sum.substring(0, 11).split(".").join(''));

  return firts10dDigits + '.';
}

const testNums = [
  '37107287533902102798797998220837590246510135740250',
  '46376937677490009712648124896970078050417018260538'
];

 console.log(largeSum(testNums));
```
Result of Console
```
// running tests
largeSum(testNums) should return 8348422521.
largeSum(fiftyDigitNums) should return 5537376230.
// tests completed
```

**Add a Link to the page with the problem:**
[https://learn.freecodecamp.org/coding-interview-prep/project-euler/problem-13-large-sum/](url)

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Versão 74.0.3729.169
* Operating System: Windows 10 64 bits

**Comment by RandellDawson** [comment]
@DavidWesley These kinds of questions should be asked on the forum.  If the forum members indicate there is a bug in the tests, then feel free to ask for this issue to be reopened.

There is nothing wrong with the tests.  You have a simply bug you need to fix in your return statement.
