### ISSUE TITLE
Incorrect assertion.

### ISSUE THREAD

**Issue by Tim15** [FreeCodeCamp/FreeCodeCamp#3610]
Challenge [Bonfire: Check for Palindromes](http://freecodecamp.com/challenges/bonfire-check-for-palindromes) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The console says that:
```
assert(palindrome("0_0 (: /-\ :) 0-0") === true, '"0_0 (: /-\\ :) 0-0" should return true.');"0_0 (: /-\ :) 0-0" should return true.
```
however, it should not return true because it has an underscore in the first 0_0 and a hyphen in the second 0-0.

My code:
```
function palindrome(str) {
  // Good luck!
  
  str = str.toLowerCase();
  
  str = str.replace(/\s/g, "");
  str = str.replace(/\./g, "");
  str = str.replace(/,/g, "");
  str = str.replace(/\!/g, "");
  
  var regular = str;
  var rev = str.split("").reverse().join("");
  if(regular == rev){
    return true;
  } else {
    return false;
  }
}



palindrome("eye");

```

**Comment by JavascriptFTW** [comment]
Just ran into this a few minutes ago. Very annoying as I'm failing because someone made a typo

**Comment by JavascriptFTW** [comment]
The test is also wrong because the `(:` and `:)` sections are not the same.

**Comment by jlslew** [comment]
Please read issue #3400

**Comment by JavascriptFTW** [comment]
Makes sense. Thank you

**Comment by bugron** [comment]
Closing this issue. @Tim15 feel free to reopen if you still experience problems, thanks.
