### ISSUE TITLE
Set up freeCodeCamp locally on Windows 10 with Docker Toolbox

### ISSUE THREAD

**Issue by georgejean** [freeCodeCamp/freeCodeCamp#36100]
I wanted to set up freeCodeCamp locally on Windows 10.
I have followed the [guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md) with the Docker build as it is recommended (By the way, the guide is clear and well written).
I've installed the Docker Toolbox as I have Windows 10 Family (v 1803) and I've changed the DOCKER_HOST_LOCATION to the IP adress indicated by docker-machine ip.
Then I've ran `npm run docker:init` but it doesn't work as the screenshot below shows (the two other commands:  `npm run docker:install` and `npm run docker:seed`
do not succeed either).
![capture1](https://user-images.githubusercontent.com/11246966/58051969-d5253c00-7b53-11e9-9b81-3813792f7482.PNG)

A file seems to be indicated as missing but it is present:

![capture2](https://user-images.githubusercontent.com/11246966/58051975-dd7d7700-7b53-11e9-8ed2-929ea540264b.PNG)

Here is the npm log:

```text
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\tmp\\.nvm\\v10.12.0\\node.exe',
1 verbose cli   'C:\\tmp\\.nvm\\v10.12.0\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'docker:init' ]
2 info using npm@6.4.1
3 info using node@v10.12.0
4 verbose run-script [ 'predocker:init', 'docker:init', 'postdocker:init' ]
5 info lifecycle @freecodecamp/freecodecamp@0.0.1~predocker:init: @freecodecamp/freecodecamp@0.0.1
6 info lifecycle @freecodecamp/freecodecamp@0.0.1~docker:init: @freecodecamp/freecodecamp@0.0.1
7 verbose lifecycle @freecodecamp/freecodecamp@0.0.1~docker:init: unsafe-perm in lifecycle true
8 verbose lifecycle @freecodecamp/freecodecamp@0.0.1~docker:init: PATH: C:\tmp\.nvm\v10.12.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\desktop\freeCodeCamp\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\ImageMagick-7.0.7-Q16;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files (x86)\PDFtk Server\bin\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Calibre2\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Yarn\bin\;C:\Users\blanc\Miniconda3;C:\Users\blanc\Miniconda3\Library\mingw-w64\bin;C:\Users\blanc\Miniconda3\Library\usr\bin;C:\Users\blanc\Miniconda3\Library\bin;C:\Users\blanc\Miniconda3\Scripts;C:\Users\blanc\AppData\Local\Microsoft\WindowsApps;C:\ffmpeg-20171231-2906363-win64-static\bin;C:\Users\blanc\AppData\Local\Pandoc;C:\Program Files\Zeal;C:\Program Files\Microsoft VS Code\bin;C:\Users\blanc\AppData\Local\Yarn\bin;C:\Users\blanc\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Sublime Text 3;D:\Desktop\Programmation\ansifilter-2.9-x64;D:\Desktop\go\bin;C:\Program Files\Docker Toolbox;C:\tmp\.nvm\v10.12.0;C:\Users\blanc\AppData\Roaming\npm
9 verbose lifecycle @freecodecamp/freecodecamp@0.0.1~docker:init: CWD: D:\desktop\freeCodeCamp
10 silly lifecycle @freecodecamp/freecodecamp@0.0.1~docker:init: Args: [ '/d /s /c',
10 silly lifecycle   'docker-compose run -u root --rm freecodecamp bash change_volumes_owner.sh && docker-compose run -u root --rm client bash -c "cd .. && bash change_volumes_owner.sh" && docker-compose run -u root --rm api-server bash -c "cd .. && bash change_volumes_owner.sh"' ]
11 info lifecycle @freecodecamp/freecodecamp@0.0.1~docker:init: Failed to exec docker:init script
12 verbose stack Error: @freecodecamp/freecodecamp@0.0.1 docker:init: `docker-compose run -u root --rm freecodecamp bash change_volumes_owner.sh && docker-compose run -u root --rm client bash -c "cd .. && bash change_volumes_owner.sh" && docker-compose run -u root --rm api-server bash -c "cd .. && bash change_volumes_owner.sh"`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (C:\tmp\.nvm\v10.12.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:962:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
13 verbose pkgid @freecodecamp/freecodecamp@0.0.1
14 verbose cwd D:\desktop\freeCodeCamp
15 verbose Windows_NT 10.0.17134
16 verbose argv "C:\\tmp\\.nvm\\v10.12.0\\node.exe" "C:\\tmp\\.nvm\\v10.12.0\\node_modules\\npm\\bin\\npm-cli.js" "run" "docker:init"
17 verbose node v10.12.0
18 verbose npm  v6.4.1
19 error file C:\WINDOWS\system32\cmd.exe
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error @freecodecamp/freecodecamp@0.0.1 docker:init: `docker-compose run -u root --rm freecodecamp bash change_volumes_owner.sh && docker-compose run -u root --rm client bash -c "cd .. && bash change_volumes_owner.sh" && docker-compose run -u root --rm api-server bash -c "cd .. && bash change_volumes_owner.sh"`
23 error spawn ENOENT
24 error Failed at the @freecodecamp/freecodecamp@0.0.1 docker:init script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

Someone could help me?

### EDIT: 
I use the second method with npm and mongodb and **it works for me** (except I can't access my portfolio, even when I click on the Preview Custom 404 Page button: but it doesn't matter to me).
Thanks for this huge and useful work!

**Comment by ValeraS** [comment]
By default for docker toolbox setup, a `freecodecamp` folder should be in `C:\Users\<user_name>\path\to\freecodecamp`

**Comment by georgejean** [comment]
Thank you, I will give it a try.
I want to save memory by changing docker projects location, could you give me some advice on the best solution?
I hesitate between three options:
1. making a hard link from the .docker folder to another target,
2. following the docker [doc](https://docs.docker.com/toolbox/toolbox_install_windows/) below (but I don't know if it will save memory),

![capture3](https://user-images.githubusercontent.com/11246966/58134496-4da8fd00-7c27-11e9-9539-d39dcb6eb498.PNG)

3. or following the procedure shown below ([here](https://stackoverflow.com/questions/33933107
/change-docker-machine-location-windows) is the link),

![capture4](https://user-images.githubusercontent.com/11246966/58134486-441f9500-7c27-11e9-8e5a-a348c7a065ea.PNG)



Thank you again,

**Comment by georgejean** [comment]
For the storage problem, I think I will choose the above option 1 (use a hard link).

One last question:

Imagine I want put my freecodecamp folder in `D:\desktop` so that my full path to freecodecamp folder is `D:\desktop\freeCodeCamp`.
Is there a way to run the three commands

```sh
npm run docker:init
npm run docker:install
npm run docker:seed
```

so that it works?

I think we must configure shared folders in Oracle VM VirtualBox:
![shared](https://user-images.githubusercontent.com/11246966/58180521-8ccc6200-7caa-11e9-8a62-57d406e91af1.PNG)
But how to do that? Is there any additional work to be done? (Would the package.json's scripts `docker: init`,` docker: install`, `docker: seed` be compatible with such a configuration change?)?

**Comment by raisedadead** [comment]
> By default for docker toolbox setup, a `freecodecamp` folder should be in `C:\Users\<user_name>\path\to\freecodecamp`

Can we investigate instead on how to make it more agnostic of the expected location? 

> I use the second method with npm and mongodb and it works for me (except I can't access my portfolio, even when I click on the Preview Custom 404 Page button: but it doesn't matter to me).

You should be able to view the profile you signed in with, needs more investigation on why that would be the case.

P.S: We all hangout in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), feel free to hop in and discuss more.

**Comment by georgejean** [comment]
I've achieved to set up freecodecamp locally on **Windows 10 Home** with *dockerToolbox*.

Here is what I've done (I suppose Node and Git are already installed and registered to PATH environment variable):

### Step 1: Change storage location (optional)

I don't want my docker folders to be stored on my SSD C: drive, so I move them to my D: drive.

- Create two folders on D: drive (with powershell or cmd)

```powershell
mkdir .docker 
mkdir docker-projects
```

- Then, from `C:\Users\user_name`, in a powershell console (not cmd), I create two junction links (You may need to be admin and/or in developer mode to do that):

```powershell
cmd mklink .docker /J D:\.docker
cmd mklink docker-projects /J D:\docker-projects
```

The remaining steps are already given in [https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md).
See it for more details. I suppose you have already forked freeCodeCamp on GitHub.

### Step 2: Install docker-toolbox for Windows Home


### Step 3: Clone your copy of freeCodeCamp

Once the installation is complete, launch the Docker Quickstart Terminal as admin user. Wait still it's complete.

---

**Only if you don't follow step 1:** Create `docker-projects` folder in home directory
```shell
cd ~
mkdir docker-projects
```
---

Go to the user folder in bash prompt:

```shell
cd ~
cd docker-projects
```

Clone your fork of freeCodeCamp there:
```shell
git clone --depth=1 https://github.com/YOUR_USER_NAME/freeCodeCamp.git
```

Then add to your repo a remote reference to the main freeCodeCamp repository:

```shell
cd freeCodeCamp
git remote add upstream https://github.com/freeCodeCamp/freeCodeCamp.git
```

### Step 4: copy `sample.env` file

With the Git Bash prompt:

```shell
cp sample.env .env
```

Note the IP adress given by the output from `docker-machine ip` command.
Then open `.env` file and change `DOCKER_HOST_LOCATION` value to the IP value formerly noted.

### Step 5: Build with Docker

On the Git Bash (always from the freeCodeCamp folder), write the commands:

```shell
npm run docker:init
npm run docker:install
npm run docker:seed
# optional:
npm ci --ignore-scripts
```

(Wait for each command to fully complete)

### Step 6: Start up the API server

```shell
npm run docker:develop
```

To view in your browser, go to the adress indicated:
```shell
You can now view @freecodecamp/client in the browser.
client_1        |
client_1        |   Local:            http://0.0.0.0:8000/
```

Important: replace `0.0.0.0` between `http://` and `:8000/` by the IP indicated in step 4.

Repeat only this step 6 to run the next sessions (launch docker quickstart terminal as normal user).

### Step 7: update your freeCodeCamp repos

Update your local copy of the freeCodeCamp upstream repository:

```shell
git fetch upstream
git reset --hard upstream/master
git push origin master --force
# for verification (the resulting output should be empty):
git diff upstream/master
```

### One important remark

An important fact to be noted is that I've always used Git Bash from docker QuickStart terminal in order to achieve the docker build (From step 3). I've tested some commands using powershell (I've not tested cmd), but it has not worked (ssh errors).

**Comment by georgejean** [comment]
@raisedadead
> You should be able to view the profile you signed in with, needs more investigation on why that would be the case.

Thanks. I can sign in now (with both methods). I don't remember what I've done (I do not remember doing anything special to make it work). 

I think I can close this issue. Right?

**Comment by raisedadead** [comment]
Thanks @georgejean this is an excellent analysis and solution for someone one Windows 10 Home. I think we can add these to our docs. 

Maybe like a supplementary guide with a link on main local installation docs, with a disclaimer like: "If on Windows 10 Home, read this." or something.

I will let @RandellDawson and @cmccormack confirm, who I believe have been on Windows and have contributed to the setup before, to confirm if this would be helpful.

**Comment by RandellDawson** [comment]
> git fetch upstream
git reset --hard upstream/master

@raisedadead I assume the above can still be replaced with `git pull --rebase upstream master`?

**Comment by raisedadead** [comment]
> git fetch upstream
> git reset --hard upstream/master

I think this is better, considering the no of changes that go into `master` each day, its not efficient to do a rebase on pull. A hard reset is more dangerous when someone worked on a local copy on master, but I am inclined with that tradeoff vs rebase on pull.

**Comment by weiranwang99** [comment]
Hi, is this bug fixed or still in progress?

**Comment by raisedadead** [comment]
We welcome supplementary guides on supporting docker toolbox.
