### ISSUE TITLE
Cascading Css Variables

### ISSUE THREAD

**Issue by aric87** [freeCodeCamp/freeCodeCamp#36108]
I don't think this challenge is described correctly. The idea that a variable is only available to the element and it's children has nothing to do with cascading. It's a clear definition of scope. 
Cascading is the concept that if there are multiple of a thing, the last one wins, which is described in the previous challenge related to fallbacks. 

Just my 2cents for what it's worth, but if I had someone come in for an interview and tell me cascading was the idea that a variable could only be used by an element and it's children, I would consider that a wildly misunderstood concept.

**Comment by ojeytonwilliams** [comment]
Thanks for reporting this!  While this challenge isn't intended to introduce the concepts of cascade and inheritance, it clearly does not use the terms correctly.

I'll have a go at rewriting the challenge to show that CSS variables behave like ordinary properties in this respect.

**Comment by moT01** [comment]
for what it's worth, this was discussed a little bit in a previous issue that was never resolved -  https://github.com/freeCodeCamp/freeCodeCamp/issues/17804 - perhaps it should be reworded since it has now come up multiple times.
