### ISSUE TITLE
Incorrect Test Cases: Match All Numbers and Match All Non-Numbers Lessons

### ISSUE THREAD

**Issue by milikkan** [freeCodeCamp/freeCodeCamp#36119]
**Describe your problem and how to reproduce it:**
1. Click Javascript Algorithms And Data Structures Certification (300 hours)
2. Click Regular Expressions section
3. Click Match All Numbers lesson
4. Exercise instructions and test cases written below do not match the code template on the right. Under the hood tests run correctly and consistent with the code template. 
5. The exercise instruction sentence and test cases explanations under it should be changed to match the real case. It is causing confusion.
6. Same thing is present in the next lesson: Match All Non Numbers. 

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/match-all-numbers

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 74.0.3729.169 (Official Build) (64-bit)
* Operating System: Linux Mint 18.3 Cinnamon 64-bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by moT01** [comment]
Can you elaborate on exactly what the problem is? I looked at the lesson - it's a little confusing, but I was able to pass it. And what would you like to see? maybe something like this for the instructions...?
`Use the shorthand character class \d to count how many consecutive digits are in movie titles. Written out numbers ("six" instead of 6) do not count.`
I'm not sure what the problem actually is here.

**Comment by lasjorg** [comment]
I'm not really sure I understand either but I do have two comments.

1. The string in the seed code seems out of place. It would make more sense if it was one of the movie titles used by the test.

Seed code string:

`let numString = "Your sandwich will be $5.00";`

Use instead:

`let numString = "2001: A Space Odyssey";`

2. The last sentence in the instructions is just confusing.

> Written out numbers ("six" instead of 6) do not count.

I'm not even sure I know what that means or how it relates to the code requirement of the challenge?

**Comment by moT01** [comment]
It just means that you don't need to match "six", but do need to match "6" - that line really probably doesn't even need to be there.

**Comment by milikkan** [comment]
I was also able to pass the tests. The thing is the explanation of the exercise `Use the shorthand character class \d to count how many digits are in movie titles. Written out numbers ("six" instead of 6) do not count.` is unrelated with the code snippet in the editor. `let numString = "Your sandwich will be $5.00";`

So, it would be much more self expressive if we change the code to something like this. `let movieName = "2001: A Space Odyssey";`

**Comment by moT01** [comment]
I see what you're saying now - yea, that could probably be changed for the two challenges mentioned.

**Comment by siddhant034** [comment]
Can I take up this one?

**Comment by moT01** [comment]
go for it @siddhant034
