### ISSUE TITLE
[beta] Footer links' clickable area should fit to their content

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#36126]
**Describe your problem and how to reproduce it:**
At the moment, the clickable area of footer links are spanning the full width of their parent div.  I'm not sure if this is on purpose, but IMHO, they should fit to their content instead, since a user could get navigated to another page if they accidentally click somewhere within the clickable area.

This issue is on https://www.freecodecamp.rocks, but it is down for maintenance at the moment. The screenshot is of my local fCC.

![Untitled](https://user-images.githubusercontent.com/25715018/58369282-6284d980-7f22-11e9-80ee-01f2ddd48338.png)

**Comment by ojeytonwilliams** [comment]
Is that actually a problem, though?  I think having list items spread like that is pretty common.  It could be a problem if you aimed for, say, Learn and got News, but there's a reasonable amount of space between them.

How about if the box were subtly highlighted on hover?

**Comment by chipperkins4** [comment]
Thanks for the threads

**Comment by huyenltnguyen** [comment]
@ojeytonwilliams Tbh, this is the first time I have seen footer items spread like that, though it is common to me to see that on a navbar.

I have no problem with leaving it as is, but adding background color on hover would be great.

**Comment by moT01** [comment]
I, personally, would prefer if only the text was clickable - but it works either way.

**Comment by ojeytonwilliams** [comment]
@moT01 Personally I like the wider boxes, because I'm lazy and click in the general vicinity of things.  So, I've added a PR for the highlight approach, since that was a really easy fix.  If that doesn't seem right we can always shrink the links onto the text.
