### ISSUE TITLE
[beta] There is an unexpected horizontal scrollbar on /donate

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#36127]
**Describe the bug**
There is an unexpected horizontal scrollbar on `/donate`.

The beta site is being down for maintenance at the moment. Here is a screenshot of my local fCC.

![Untitled](https://user-images.githubusercontent.com/25715018/58371231-b9e27400-7f39-11e9-9898-f105f3b8c0d4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox (66.0.5), Chrome (74.0.3729.169)

**Comment by ojeytonwilliams** [comment]
That there is. I'll take a look.
