### ISSUE TITLE
Sign in on docker - localhost:8000 not showing up.

### ISSUE THREAD

**Issue by 0071241** [freeCodeCamp/freeCodeCamp#36139]
Hello, I am unable to login when I click the sign in button on localhost:8000 after running `npm run docker:develop`. I will add screenshots below. Does anybody know how to fix this? I have tried rerunning and reinstalling npm and docker, seeding it, but nothing seems to work. I am not even getting an error message, it just doesn't seem to work. I am running windows 10, on Microsoft edge. Can anybody help me with this issue?

So I go on it:

![Screenshot (1)](https://user-images.githubusercontent.com/50597817/58513907-92c0b800-816e-11e9-924d-efc35d7911df.png)

Then I click sign in:

![Annotation 2019-05-28 173834](https://user-images.githubusercontent.com/50597817/58514302-8ee16580-816f-11e9-9ed9-81372f9beaf9.png)

And then it just goes back to the page at the beginning:

![Annotation 2](https://user-images.githubusercontent.com/50597817/58514327-a0c30880-816f-11e9-924a-fea9872cf74a.png)

I have also tried localhost:8000/signin, but it gives me the following error:

![Annotation 2019-05-28 174127](https://user-images.githubusercontent.com/50597817/58514392-d9fb7880-816f-11e9-8c8f-6a0afa89ef14.png)

Any kind of help would be very appreciated, feel free to leave a comment below if you need specifications or if you are running into the same error.

**Comment by raisedadead** [comment]
Have you taken a look at your terminal for errors? Is there anything useful there, that will help diagnose this? You should jump in [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) to get in touch with our contributor team who maybe able to help you troubleshoot this.

**Comment by 0071241** [comment]
So there is a one error:

`client_1        | error (node:65) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead`

And I am already in touch with the contributor chat room, only no one has reached out to me yet. Well, here is the full code if any of you are wondering about it:

`PS C:\Users\USERNAME_HERE\freecodecamp> npm run docker:develop

> @freecodecamp/freecodecamp@0.0.1 docker:develop C:\Users\USERNAME_HERE\freecodecamp
> docker-compose up client api-server

freecodecamp_mailhog_1 is up-to-date
freecodecamp_client_1 is up-to-date
freecodecamp_db_1 is up-to-date
freecodecamp_api-server_1 is up-to-date
Attaching to freecodecamp_client_1, freecodecamp_api-server_1
api-server_1    | Debugger listening on ws://0.0.0.0:9229/c9508584-b10b-4199-aa3c-8aaee380703a
api-server_1    | For help, see: https://nodejs.org/en/docs/inspector
api-server_1    | Sun, 26 May 2019 13:48:34 GMT fcc:server:datasources using MailHog server on port 1025
api-server_1    | Sun, 26 May 2019 13:48:38 GMT fcc:server:utils:about no google applications credentials environmental variable found
api-server_1    | 'GOOGLE_APPLICATION_CREDENTIALS'
api-server_1    | 'activeUser' api will always return 0
api-server_1    | this can safely be ignored during development
api-server_1    | Sun, 26 May 2019 13:48:39 GMT fcc:models:user setting up user hooks
api-server_1    | Sun, 26 May 2019 13:48:44 GMT fcc:server freeCodeCamp server listening on port 3000 in development
api-server_1    | Sun, 26 May 2019 13:48:44 GMT fcc:server connecting to db at mongodb://db:27017/freecodecamp
api-server_1    | Sun, 26 May 2019 13:48:44 GMT fcc:server db connected
api-server_1    | Sun, 26 May 2019 13:48:44 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | No Stripe API keys were found, moving on...
api-server_1    | Sun, 26 May 2019 13:53:44 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Sun, 26 May 2019 13:58:44 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Sun, 26 May 2019 14:03:44 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Sun, 26 May 2019 14:08:44 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Sun, 26 May 2019 14:13:44 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Sun, 26 May 2019 14:18:44 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | 2019-05-26T14:19:00.655Z 302 GET 72.574 ms - /signin
api-server_1    | 2019-05-26T14:19:12.896Z 302 GET 20.059 ms - /signin
api-server_1    | Sun, 26 May 2019 14:23:44 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | 2019-05-26T14:24:21.757Z 302 GET 11.915 ms - /signin
api-server_1    | Sun, 26 May 2019 14:28:44 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Sun, 26 May 2019 14:33:44 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Sun, 26 May 2019 14:38:44 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Mon, 27 May 2019 20:29:40 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | 2019-05-27T20:34:08.069Z 302 GET 15.452 ms - /signin
api-server_1    | 2019-05-27T20:34:14.505Z 302 GET 19.083 ms - /signin
api-server_1    | Mon, 27 May 2019 20:34:40 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Mon, 27 May 2019 20:39:40 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Mon, 27 May 2019 20:44:40 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Mon, 27 May 2019 20:49:40 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Mon, 27 May 2019 20:54:40 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Mon, 27 May 2019 20:59:40 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Mon, 27 May 2019 21:04:40 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Mon, 27 May 2019 21:09:40 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Mon, 27 May 2019 21:14:40 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Mon, 27 May 2019 21:19:40 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Mon, 27 May 2019 21:24:40 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 20:20:20 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 20:25:20 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 20:30:21 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 20:35:21 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 20:40:21 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 20:45:21 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 20:50:21 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 20:55:21 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 21:00:21 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 21:05:21 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 21:10:21 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 21:21:30 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 21:26:30 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | 2019-05-28T21:27:45.998Z 302 GET 21.197 ms - /signin
api-server_1    | 2019-05-28T21:27:54.922Z 302 GET 11.011 ms - /signin
api-server_1    | 2019-05-28T21:28:02.506Z 302 GET 9.858 ms - /signin
api-server_1    | 2019-05-28T21:28:07.372Z 302 GET 28.244 ms - /signin
api-server_1    | Tue, 28 May 2019 21:31:30 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | 2019-05-28T21:33:26.856Z 302 GET 20.167 ms - /signin
api-server_1    | 2019-05-28T21:33:58.778Z 302 GET 13.223 ms - /signin
api-server_1    | 2019-05-28T21:36:19.513Z 302 GET 10.567 ms - /signin
api-server_1    | Tue, 28 May 2019 21:36:30 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | 2019-05-28T21:38:03.235Z 302 GET 8.659 ms - /signin
api-server_1    | 2019-05-28T21:38:11.513Z 302 GET 16.405 ms - /signin
api-server_1    | 2019-05-28T21:38:17.939Z 302 GET 9.519 ms - /signin
api-server_1    | Tue, 28 May 2019 21:41:30 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 21:46:30 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 21:51:30 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 21:56:30 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 22:01:30 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 22:06:30 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 22:11:30 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Tue, 28 May 2019 22:16:30 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Wed, 29 May 2019 01:21:31 GMT fcc:boot:donate activeDonator count: 0
api-server_1    | Wed, 29 May 2019 11:59:24 GMT fcc:boot:donate activeDonator count: 0
client_1        |
client_1        | > @freecodecamp/client@1.0.0 predevelop /app/client
client_1        | > npm run prebuild
client_1        |
client_1        |
client_1        | > @freecodecamp/client@1.0.0 prebuild /app/client
client_1        | > npm run build:workers && node ../tools/scripts/ensure-env.js
client_1        |
client_1        |
client_1        | > @freecodecamp/client@1.0.0 build:workers /app/client
client_1        | > node --max_old_space_size=7168 node_modules/webpack-cli --env.production --config ./webpack-workers.js --progress
client_1        |
client_1        |  69% buiHash: aed21d2ed12ba0cdeabftive ...ent/node_modules/lodash/_setCacheAdd.js
client_1        | Version: webpack 4.28.4
client_1        | Time: 26194ms
client_1        | Built at: 05/26/2019 1:48:50 PM
client_1        |                                Asset       Size  Chunks                    Chunk Names
client_1        |                    enzyme-adapter.js  185 bytes    2, 1  [emitted]         enzyme-adapter
client_1        |                enzyme-adapter.js.map   94 bytes    2, 1  [emitted]         enzyme-adapter
client_1        |                            enzyme.js  177 bytes    1, 2  [emitted]         enzyme
client_1        |                        enzyme.js.map   86 bytes    1, 2  [emitted]         enzyme
client_1        |                      frame-runner.js    185 KiB       3  [emitted]         frame-runner
client_1        |                  frame-runner.js.map    874 KiB       3  [emitted]         frame-runner
client_1        |                      sass-compile.js   1.33 KiB       4  [emitted]         sass-compile
client_1        |                  sass-compile.js.map   5.76 KiB       4  [emitted]         sass-compile
client_1        |                         sass.sync.js   3.53 MiB          [emitted]  [big]
client_1        |                    test-evaluator.js    165 KiB    5, 6  [emitted]         test-evaluator
client_1        |                test-evaluator.js.map    868 KiB    5, 6  [emitted]         test-evaluator
client_1        |                      vendors~chai.js   67.8 KiB       6  [emitted]         vendors~chai
client_1        |                  vendors~chai.js.map    419 KiB       6  [emitted]         vendors~chai
client_1        |            vendors~enzyme-adapter.js    219 KiB       7  [emitted]         vendors~enzyme-adapter
client_1        |        vendors~enzyme-adapter.js.map    595 KiB       7  [emitted]         vendors~enzyme-adapter
client_1        |     vendors~enzyme~enzyme-adapter.js    521 KiB       0  [emitted]  [big]  vendors~enzyme~enzyme-adapter
client_1        | vendors~enzyme~enzyme-adapter.js.map   1.75 MiB       0  [emitted]         vendors~enzyme~enzyme-adapter
client_1        | Entrypoint frame-runner = frame-runner.js frame-runner.js.map
client_1        | Entrypoint sass-compile = sass-compile.js sass-compile.js.map
client_1        | Entrypoint test-evaluator = test-evaluator.js test-evaluator.js.map
client_1        | [322] (webpack)/buildin/global.js 472 bytes {0} {5} {6} [built]
client_1        |       ModuleConcatenation bailout: Module is not an ECMAScript module
client_1        | [365] ./src/client/frame-runner.js 5.13 KiB {3} [built]
client_1        |       ModuleConcatenation bailout: Module uses eval()
client_1        | [369] ./src/client/workers/sass-compile.js 756 bytes {4} [built]
client_1        |       ModuleConcatenation bailout: Module is not an ECMAScript module
client_1        | [370] ./src/client/workers/test-evaluator.js 3.51 KiB {5} [built]
client_1        |       ModuleConcatenation bailout: Module uses eval()
client_1        | [416] (webpack)/buildin/module.js 497 bytes {0} [built]
client_1        |       ModuleConcatenation bailout: Module is not an ECMAScript module
client_1        | [480] readable-stream (ignored) 15 bytes {1} {2} [built]
client_1        |       ModuleConcatenation bailout: Module is not an ECMAScript module
client_1        | [489] util (ignored) 15 bytes {1} {2} [built]
client_1        |       ModuleConcatenation bailout: Module is not an ECMAScript module
client_1        | [490] util (ignored) 15 bytes {1} {2} [built]
client_1        |       ModuleConcatenation bailout: Module is not an ECMAScript module
client_1        | [556] ./util.inspect (ignored) 15 bytes {1} {2} [built]
client_1        |       ModuleConcatenation bailout: Module is not an ECMAScript module
client_1        |     + 798 hidden modules
client_1        |
client_1        | WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
client_1        | This can impact web performance.
client_1        | Assets:
client_1        |   vendors~enzyme~enzyme-adapter.js (521 KiB)
client_1        |   sass.sync.js (3.53 MiB)
client_1        |
client_1        | > @freecodecamp/client@1.0.0 develop /app/client
client_1        | > node --inspect=0.0.0.0:9228 node_modules/gatsby-cli develop "-H" "0.0.0.0"
client_1        |
client_1 Debugger listening on ws://0.0.0.0:9228/f168bffe-c751-4e0b-b2af-ca7ad0a10c5c                                  p
client_1        | For help, see: https://nodejs.org/en/docs/inspector
client_1        | ╔════════════════════════════════════════════════════════════════════════╗
client_1        | ║                                                                        ║
client_1        | ║   Gatsby has started collecting anonymous usage analytics              ║
client_1        | ║   to help improve Gatsby for all users.                                ║
client_1        | ║                                                                        ║
client_1        | ║   If you'd like to opt-out, you can use `gatsby telemetry --disable`   ║
client_1        | ║   To learn more, checkout https://gatsby.dev/telemetry                 ║
client_1        | ║                                                                        ║
client_1        | ╚════════════════════════════════════════════════════════════════════════╝
client_1        | success open and validate gatsby-configs — 0.580 s
client_1        | success load plugins — 2.281 s
client_1        | success onPreInit — 0.008 s
client_1        | success initialize cache — 0.018 s
client_1        | success copy gatsby files — 1.597 s
client_1        | success onPreBootstrap — 0.035 s
client_1        | success source and transform nodes — 28.233 s
client_1        | success building schema — 0.750 s
client_1        | success createPages — 6.245 s
client_1        | success createPagesStatefully — 0.360 s
client_1        | success onPreExtractQueries — 0.000 s
client_1        | success update schema — 0.719 s
client_1        | success extract queries from components — 1.537 s
client_1        | success run static queries — 0.054 s — 1/1 19.05 queries/second
client_1        | success run page queries — 0.335 s — 22/22 65.93 queries/second
client_1        | success write out page data — 0.117 s
client_1        | success write out redirect data — 0.006 s
client_1        | success Build manifest and related icons — 0.213 s
client_1        | success onPostBootstrap — 0.217 s
client_1        |
client_1        | info bootstrap finished - 51.822 s
client_1        |
client_1        | error (node:65) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
client_1        |  DONE  Compiled successfully in 44213ms1:51:05 PM
client_1        |
client_1        |
client_1        | You can now view @freecodecamp/client in the browser.
client_1        |
client_1        |   Local:            http://0.0.0.0:8000/
client_1        |   On Your Network:  http://172.18.0.4:8000/
client_1        |
client_1        | View GraphiQL, an in-browser IDE, to explore your site's data and schema
client_1        |
client_1        |   http://0.0.0.0:8000/___graphql
client_1        |
client_1        | Note that the development build is not optimized.
client_1        | To create a production build, use npm run build
client_1        |
client_1        | info ℹ ｢wdm｣:
client_1        | info ℹ ｢wdm｣: Compiled successfully.`

**Comment by raisedadead** [comment]
Thanks for these additional logs. I do not see anything out of the ordinary here, leading me to guess, you may have missed a step or something in the setup?

> And I am already in touch with the contributor chat room, only no one has reached out to me yet. 

The chat room is a place where fellow contributors just like you hangout and help each other voluntarily, they may be delayed but someone will sure enough help you out. I request your patience meanwhile :)

As for the error, it's worth going thru the docs and checking if you happened to miss a step.

**Comment by 0071241** [comment]
Alright, I will. Thank you.

**Comment by 0071241** [comment]
Answered: It was the fault to the browser I was using, as I was using Microsoft Edge. I tried it out in Chrome and it worked very well. Thank you to everybody.
