### ISSUE TITLE
Object Oriented Programming: Use Closure to Protect Properties Within an Object from Being Modified Externally does not properly explain what a  closure is

### ISSUE THREAD

**Issue by twhite96** [freeCodeCamp/freeCodeCamp#36148]
**Describe your problem and how to reproduce it:**
*Object Oriented Programming: Use Closure to Protect Properties Within an Object from Being Modified Externally* does not properly explain what a *closure is*.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/use-closure-to-protect-properties-within-an-object-from-being-modified-externally

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 74.0.3729.169 (Official Build) (64-bit)
* Operating System: macOS 10.14.5

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
No screenshot, however there is no explanation of what a closure is which is misguided. *I* know what a closure is and why you would use it, and while you explain it is used to hide private data, you only mention *closure* in the title without mentioning it again in the exercise.

Could we at least add a link to learn more about it if you're not going to explicitly explain closure in the challenge?

**Comment by twhite96** [comment]
Also, if you choose to address this, I can go about helping in some way. I've been dying to help with the codebase, but it's really popular and it seems I can't really find something to help with. Let me know either way. I'd like to help out.

**Comment by RandellDawson** [comment]
If you want to add anything further about closure, I suggest doing in the guide article related to the challenge.  There, you can link to other relevant resources.

**Comment by twhite96** [comment]
>If you want to add anything further about closure, I suggest doing in the guide article related to the challenge.  There, you can link to other relevant resources.  

@RandellDawson okay. Any instruction page for how to contribute to the guide article?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RandellDawson** [comment]
@twhite96 Take a look at https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md#research-write-and-update-our-guide-articles first. If you need more help, you can visit the [Contributors Gitter channel](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by twhite96** [comment]
Okay I'll do this. How can I claim it?

**Comment by RandellDawson** [comment]
@twhite96 It is yours.

**Comment by RandellDawson** [comment]
As we have removed the guide from the repo, you will now need to add new Guide articles to [our forum](https://www.freecodecamp.org/forum).  Since we are no longer accepting PRs for the guide, I am closing this issue.
