### ISSUE TITLE
[a11y] Please give the code editor a role on the page

### ISSUE THREAD

**Issue by xnt** [freeCodeCamp/freeCodeCamp#36153]
**Describe the bug**

Based on #34222 , bullet 1:

Please give the code editor an element with a role on the page. I would suggest an input role of some kind or a role="application". Do whatever looks good, but there is currently no editor actually on the page for screen reader users and the only way we can get to it is by tabbing and most screen reader users use the arrow keys rather than tabbing when browsing webpages like this.

**To Reproduce**
1. Go to any lesson
2. Open the dev tools
3. Inspect the editor
4. Observe the `role` attribute

**Expected behavior**
`role="application"`

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Additional context**

**Comment by xnt** [comment]
BTW, I'm working on this one already.

**Comment by frastlin** [comment]
Actually, could we please have an input role if an actual input element is not going to be used? Application is the most uninformative role in existence and screen reader users really don't like it as a rule. I would recommend [textbox:](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/textbox_role)

    <div role="textbox" contenteditable="true" aria-multiline="true"></div>

This is much more descriptive, the screen reader says it is a textbox, you can jump to it with the "e" key, and also says that one can navigate multiple lines with the arrow keys.

**Comment by IAmTheUnderTaker** [comment]
I think this is good for starters

**Comment by oriane212** [comment]
Hi, 

I noticed there is a `textarea` element nested inside the Monaco Editor, and I was able to jump to it using the ‘e’ key, as @frastlin described. I am using Chrome on a Mac. The element has an `aria-label`, “Editor content; Press Alt+F1 for Accessibility options”, among several other aria attributes.

I initially was going to propose adding an `aria-label` and/or `role` for each `div` containing one of the panels in the layout (ie. instructions, editor, test output, and preview) or wrapping a `section` around each. 

The react-reflex components used for the layout, however, don't seem to support these properties, and the layout seems to break when trying to add a new `div` or `section` within the tree.

**Comment by frastlin** [comment]
Hello,
Yes, this feature seems to be fixed in the latest version. Everything works very well now.
Thank you!

**Comment by moT01** [comment]
> this feature seems to be fixed in the latest version. Everything works very well now.

So it's probably safe to close this.

**Comment by moT01** [comment]
Closing, see above comment. If anyone is still having problems here, feel free to leave a comment and this can be reopened.
