### ISSUE TITLE
wrong hint within Use the Conditional (Ternary) Operator

### ISSUE THREAD

**Issue by Nanotorre** [freeCodeCamp/freeCodeCamp#36155]
**Describe your problem and how to reproduce it:**
The solution is wrong. It shoud use == instead of simple.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-javascript/use-the-conditional-ternary-operator/

**Tell us about your browser and operating system:**
* Browser Name: firefox 
* Browser Version: 67.0
* Operating System: mac os high sierra

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Captura de pantalla 2019-06-01 a las 10 24 01](https://user-images.githubusercontent.com/50929081/58745897-774bfa80-8457-11e9-8711-3374a6a92876.png)

**Comment by RandellDawson** [comment]
This is no longer an issue and has been fixed on the master branch.  In fact, the challenge instructions have changed and the solution above is no longer relevant.  Once the master branch is deployed to production, the guide will be updated, so I am closing this issue has resolved.

**Comment by smoralesjr** [comment]
Why not make this very easy fix? People are still using the curriculum and will see an incorrect hint if they check the guide for this section.
