### ISSUE TITLE
Mac ctrl + enter shortcut does not work

### ISSUE THREAD

**Issue by KaustubhD** [freeCodeCamp/freeCodeCamp#36156]
**Describe the bug**
The ctrl+enter shortcut doesn't quite work in the non-editor challenges

**Expected behavior**
In editor challenges, the shortcut works for ```cmd + enter``` (on a Mac), which is preferred and acceptable
In non-editor challenges, the shortcut works for actually ```ctrl + enter``` (Mac)
At the congratulatory dialog box, both *ctrl* and *cmd* shortcuts work
By convention shortcuts with windows' ctrl maps to Mac's cmd.

**Desktop (please complete the following information):**
 - OS: [MacOS 10.12]
 - Browser [Chrome]
 - Version [74]

**Comment by lukejoliat** [comment]
So is the request here to have ctr/cmd enter work identically for every instance on Mac?

**Comment by scissorsneedfoodtoo** [comment]
Thank you for reporting this, @KaustubhD. I believe this is being addressed in https://github.com/freeCodeCamp/freeCodeCamp/pull/36808.

**Comment by ojeytonwilliams** [comment]
Yeah, it is.  That PR should make it more consistent.  Everywhere `ctrl + enter` works, `cmd + enter` should work to.
