### ISSUE TITLE
Problem with certification challenges

### ISSUE THREAD

**Issue by rajat2502** [freeCodeCamp/freeCodeCamp#36161]
There is a major problem in the certification challenges wherein even though I enter some random link as in if I enter www.google.com, then too the challenge gets passed. Here is a screenshot that illustrates the same:
![Screenshot (365)](https://user-images.githubusercontent.com/42200276/58803358-e75fa980-862c-11e9-9217-e19871f91def.png)

Please look into the issue and try to fix it as soon as possible as this is bound to put the credibility of the project at risk. If possible, mention the apt-file that needs to be changed.

**Comment by raisedadead** [comment]
We are aware of this and making it better in the next release planned this year. 

freeCodeCamp.org's certifications are bound by our honour based [Academic Honesty Policy](https://www.freecodecamp.org/academic-honesty). 

In simple terms:
1. Your cert are only valid, if your work abides by the policy.
2. This is reinforced by making your cert publicly verifiable only if your projects are publicly verifiable.
3. Meaning the links to the submitted projects will be public along with your certs.
4. Falsifying or cheating can lead to suspension of account and revocation of the issued certs when reported by anyone.


Thanks for your issue report. Happy contributing.
