### ISSUE TITLE
Challenges use innerHTML without mentioning XSS vulnerabilities

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#36162]
Several challenges from [here](https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/get-json-with-the-javascript-xmlhttprequest-method/) to [here](https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/post-data-with-the-javascript-xmlhttprequest-method/) use `innerHTML` to update the page.  These are the first places where this technique is introduced, but don't mention any security concerns.

Since the first two challenges use `innerHTML` just to insert text, they could use `textContent` instead.  Later challenges insert actual html and would be a good place to mention the possibility of XSS.  They should have a warning about XSS and maybe include a sanitizer function to hammer home the point.  The warning would not have to go into depth, a note and a link to the [guide](https://guide.freecodecamp.org/security/xss-cross-site-scripting/) would be good.

How does this sound?

**Comment by moT01** [comment]
Seems like that's straying away from what is trying to be taught there - XMLHTTP is probably already confusing enough to a beginner, some of those challenges are already fairly long, and XSS protection is taught in the helmet lessons. You bring up a valid point, but I think it might cause confusion.

I'm not against adding something, but there's some concerns. 

On a sort of related note - I do remember some of these lessons being a little.... lacking in some ways - basically you just need to copy paste the example to pass some of the challenges - which is what I did. So I'm saying that they aren't forcing the user to do enough. Perhaps they could be rewritten slightly to have the camper do a little more and in the process change all the innerHTML to use other methods. But maybe your idea would be good for now.

**Comment by ojeytonwilliams** [comment]
@moT01 I know what you mean.  While I was looking at this, I redid a couple of the challenges and they are literally just cut and paste jobs.  Perhaps simply changing a few words of the example code would be enough, though.  That way they at least have look at it and see what's different.  For example, currently one has `req.open("GET",'/json/cats.json',true);` and that could be `req.open("GET",'/json/ninjas.json',true);`.  

As for the XSS protection, the helmet lessons deal with a very specific type of attack - they wouldn't protect against setting `innerHTML` to some arbitrary code.  Regardless, you've got a good point about the complexity of the challenges, so asking them to sanitize the code on top of that would be a bit much.  Perhaps a note in [Convert JSON Data to HTML](https://learn.freecodecamp.org/data-visualization/json-apis-and-ajax/convert-json-data-to-html/) would be enough.  Something like:

> For this challenge you need to add new html elements to the page, so you cannot rely on `textContent`.  Instead you need to use `innerHTML` which can make a site vulnerable to cross site scripting attacks. To learn more see [the guide](https://guide.freecodecamp.org/security/xss-cross-site-scripting/).

It just doesn't seem right to introduce `innerHTML` without some kind of warning!

**Comment by moT01** [comment]
Since the English version has been fixed here, it's probably safe to close this. The Spanish translation may not be merged for a while.
