### ISSUE TITLE
Changing "Note" formatting in "Remove Elements from a Linked List" challenge

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/freeCodeCamp#36171]
Following the conventions decided upon in #35464, we should change the instruction in the "Remove Elements from a Linked List" challenge - 
```
Note The length of the list should decrease by one every time an element is removed from the linked list.
```
to 
```
<strong>Note:</strong> The length of the list should decrease by one every time an element is removed from the linked list.
```
**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/coding-interview-prep/data-structures/remove-elements-from-a-linked-list/

The file to be changed is [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-coding-interview-prep/data-structures/remove-elements-from-a-linked-list.english.md). 

Since this is a simple change, we would welcome Pull Requests from first time contributors.

**Comment by minggas** [comment]
I can do it. Should i make the same change in the portuguese version too?

**Comment by RandellDawson** [comment]
> Should i make the same change in the portuguese version too?

No, just make the change for the English version.
