### ISSUE TITLE
the new update has reset all my progress. 

### ISSUE THREAD

**Issue by kanuos** [freeCodeCamp/freeCodeCamp#36177]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by raisedadead** [comment]
Thanks for reaching out. This tracker is for bugs only. Please send an email from you registered email id to `team@freecodecamp.org`
