### ISSUE TITLE
Update jest to latest

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#36216]
We want to update jest to the latest version and the related code to address the breaking changes.

**Comment by kozlovvski** [comment]
Hey, I'd like to tackle this one!

**Comment by raisedadead** [comment]
Sure, go for it. We use Jest all over the place. A good place to start understanding how many and what packages we have is to look into the https://github.com/freeCodeCamp/freeCodeCamp/blob/master/lerna.json config.
