### ISSUE TITLE
replace form tags in codeUri with fccsf/fccef

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#3622]
Seems that form tags in the uri through XSS errors. We need to alias these the same way we do script tags.

**Comment by bugron** [comment]
@BerkeleyTrue I tried
```javascript
  common.replaceScriptTags = function replaceScriptTags(value) {
    return value
      .replace(/<script>/gi, 'fccss')
      .replace(/<\/script>/gi, 'fcces')
      .replace(/<form/gi, 'fccsf')
      .replace(/<\/form>/gi, 'fccef');
  };
```
and the same in `user.js` and 
```javascript
  common.replaceSafeTags = function replaceSafeTags(value) {
    return value
      .replace(/fccss/gi, '<script>')
      .replace(/fcces/gi, '</script>')
      .replace(/fccsf/gi, '<form')
      .replace(/fccef/gi, '<\/form>');
  };
```
but this didn't work for [Waypoint: Create a Form Element](http://www.freecodecamp.com/challenges/waypoint-create-a-form-element). Am I missing something?

**Comment by BerkeleyTrue** [comment]
They must be separate functions. Also you have a typo `<form` should be `<form>`

**Comment by bugron** [comment]
But would it replace correctly, for example, `<form action='something'>` if I write `<form>`?

**Comment by BerkeleyTrue** [comment]
Good point. Yeah I guess we need to only replace `<form` and `</form>

**Comment by BerkeleyTrue** [comment]
This may be unrelated to codeUri but specific to iFrame XSS auditor and forms with actions.
