### ISSUE TITLE
Clicking magnifying glass icon clears text and search results (instead of searching text)

### ISSUE THREAD

**Issue by byco** [freeCodeCamp/freeCodeCamp#36221]
**Describe the bug**
I noticed there's a few other issues about the search bar on the main site (https://search.freecodecamp.org/) but haven't seen this particular issue mentioned before. Apologies if it's been addressed already.

Clicking on the magnifying glass icon clears the text in the search bar instead of searching for the text entered. The icon even says "Submit the search query." when hovered over. I believe it's UI standard to have clicking the icon as an alternative to hitting Enter on a keyboard, so that's unexpected behavior.

This issue is similar to this one: https://github.com/freeCodeCamp/freeCodeCamp/issues/29311

But I wanted to point out that clicking the icon has a bug too. Once the icon is clicked on, then the search results and search text clear completely.

**To Reproduce**
1. Go to https://search.freecodecamp.org/
2. Search any term
3. Now type in another term in the search bar
4. Click on magnifying icon

**Expected behavior**
I would expect a search page populated with relevant results to what I typed into the search bar. The typed in text should still be in the search bar.

**Screenshots**

Example of search page before clicking on magnifying glass icon:
![Screen Shot 2019-06-09 at 12 03 39 AM](https://user-images.githubusercontent.com/30761262/59156072-2b4a1880-8a4a-11e9-8a8d-38a61d5466da.png)

Example of search page after clicking on magnifying glass icon:
![Screen Shot 2019-06-09 at 12 03 58 AM](https://user-images.githubusercontent.com/30761262/59156078-42890600-8a4a-11e9-8f68-1d5884b4fb95.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser: Chrome
 - Version: 74.0.3729.169

**Comment by cmgonzales** [comment]
Can i try to work on this?

**Comment by RandellDawson** [comment]
@cmgonzales I would hold off as there have already been several PRs merged which fix many issues with the search bar.  The changes are on the master branch, so you can pull it down and get it running locally to test if this new issue exists as stated.  If you can reproduce it on the master branch code, then make sure to search through the other open PRs related to the search bar to make sure someone is not already working on a solution for it.

If you find out the problem reported above does not happen using the master branch code, then let us know and we can close this issue.

Thank you.
