### ISSUE TITLE
Page that redirects to the hint of generate an array of all object keys with object keys is broken

### ISSUE THREAD

**Issue by marimeireles** [freeCodeCamp/freeCodeCamp#36264]
I use a MacOS 10.14.5 and I tried to open the following link in Firefox Nightly and Chrome (both in their last versions) and I received a 404 page.

https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/generate-an-array-of-all-object-keys-with-object-keys

This is the hint link that's available in the question.

If you're interested, I can help to fix it.

**Comment by RandellDawson** [comment]
@marimeireles Thank you for letting us know, but this issue has already been fixed on our master branch but has yet to be deployed to production.  Once it is deployed, the links will work.

I am closing this issue as it has technically been address already.
