### ISSUE TITLE
Redux Certification Guide articles not showing up with complete files

### ISSUE THREAD

**Issue by NotTheBest** [freeCodeCamp/freeCodeCamp#36268]
**Describe your problem and how to reproduce it:**
There are several Redux articles that have complete files that are still listed as stubs on the website. Some of these guides were updated around 8 months ago and are still listed as stubs on the website.

**Add a Link to the page with the problem:**
Here is one example
https://guide.freecodecamp.org/certifications/front-end-libraries/redux/combine-multiple-reducers
https://guide.freecodecamp.org/certifications/front-end-libraries/redux/combine-multiple-reducers

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 
* Operating System: Mac OS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by NotTheBest** [comment]
This is also happening with other files as well, under further inspection. SASS for example, has the same problem.

**Comment by raisedadead** [comment]
Thanks for reporting, unfortunately we are a bit delayed on releasing the next version of guide content. We do not have a ETA right now, but there are several huge changes coming in which will resolve these content related issues. We thank you for your patience meanwhile.

**Comment by raisedadead** [comment]
Clicked the wrong button... 😓 !
