### ISSUE TITLE
Multiple ternary [why are you teaching this]?

### ISSUE THREAD

**Issue by kerafyrm02** [freeCodeCamp/freeCodeCamp#36260]
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/use-multiple-conditional-ternary-operators

It's important that young programmers understand how this works., but why isn't there any emphasis not to use multiple ternary? It's just bad programming.

**Comment by ojeytonwilliams** [comment]
Well, if you indent sensibly they aren't particularly hard to read:
```js
function findGreaterOrEqual(a, b) {
  return (a === b) ? "a and b are equal"
    : (a > b) ? "a is greater"
    : "b is greater";
}
```
vs. the example given the challenge

```js
function findGreaterOrEqual(a, b) {
  if (a === b) {
    return "a and b are equal";
  } else if (a > b) {
    return "a is greater";
  } else {
    return "b is greater";
  }
}
```

Obviously this is subjective, but I find those similarly easy to understand.

That said, it might be worth mentioning that they should be used with care (indented as above at least).  If you've got time to put together a PR they're always welcome!
