### ISSUE TITLE
Ditch Custom CSS for Bootstrap

### ISSUE THREAD

**Issue by VSatyavani** [freeCodeCamp/freeCodeCamp#36266]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Manish-Giri** [comment]
What's the issue?

**Comment by raisedadead** [comment]
Hi @VSatyavani 

Thanks for reporting this issue. 

Here are some next steps that you should follow before we can help you with your query:
- Check [these troubleshooting steps](https://www.freecodecamp.org/forum/t/how-to-report-a-bug/19543) first.
- Please use the [Chat Rooms](https://www.freecodecamp.org/forum/t/free-code-camp-official-chat-rooms/19390) or try looking through our [forum](https://www.freecodecamp.org/forum) for help with a specific challenge and any coding assistance.

**IMPORTANT:** 
Please NOTE that this tracker is for reporting bugs and enhancements to freeCodeCamp's code base only.

Happy Coding!
