### ISSUE TITLE
issue in "30. Waypoint: Create a Form Element"

### ISSUE THREAD

**Issue by manishdoomra** [FreeCodeCamp/FreeCodeCamp#3627]
I am writing the code as:-

<form action="/submit-cat-photo">
    <input type="text" placeholder="cat photo URL">
</form>

But still it is saying "Make sure your form has an action attribute which is set to /submit-cat-photo".

**Comment by bugron** [comment]
@manishdoomra thanks for posting this issue!
Please, provide your code and a screenshot, thanks!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by manishdoomra** [comment]
![waypoint30_create_form_element](https://cloud.githubusercontent.com/assets/10593451/10335526/052e9114-6d0f-11e5-95f6-61163da022da.png)

Please find the attached screenshot for your reference

**Comment by LastLeg** [comment]
I'm having the same issue. I even tried going to the next waypoint and copying the code from there back into this one and it still doesn't work.

**Comment by bugron** [comment]
Closing this issue. You can continue further discussion in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3628, thanks.
