### ISSUE TITLE
LinkedIn compatible Certification IDs and Integration

### ISSUE THREAD

**Issue by CarloMartini** [freeCodeCamp/freeCodeCamp#36277]
FCC certifications do not have any kind of unique identifiers: Linkedin has a specific field for that (https://developer.linkedin.com/docs/fields/certifications#) and other certification providers (like Coursera) do offer it. It makes a certificate a bit more "official". 

What about implementing such a feature?

(I asked in the forum, but have been suggested to open an issue here)

**Comment by raisedadead** [comment]
> It makes a certificate a bit more "official".

Apologies, but I find this to be a bit vague on the requirement. Can you point us to a concrete example (not just the spec), for more context on how this works? We may consider this if it's something we would want to have?

Thanks for your report.

**Comment by CarloMartini** [comment]
As far as I know, it's just a semi-random string proving that a certificate has been issued specifically for a person: such string will thus be maintained in a database for a long time, even if the domain name or the paths of a website where to change in the future, or if the user removes/changes its account name. 

In the case of CoursEra, it's part of the URL to the certificate:
https://www.coursera.org/account/accomplishments/specialization/T6W2SAPCRVYM
That "T6W2SAPCRVYM" is the ID that can be used in Linkedin.

I don't really know more than this.

**Comment by raisedadead** [comment]
Understood. 

For us we have every certificate uniquely verifiable at:
`https://www.freecodecamp.org/certification/<username>/<certification-name>`

For example:
`https://www.freecodecamp.org/certification/mot01/javascript-algorithms-and-data-structures`

We do not have any plans to change/add the schema for foreseeable future. 

There maybe a way to implement this without adding schema changes (hashing the userId and the timestamp of the cert issue, which would be unique too, I guess), but the core/dev team does not have the bandwidth for it as well.

I am tagging this as a feature request, for the community to look into and come up with solutions, but again with no guarantees of adoption. Simply put we are interested, but a QA on this will be slower than usual.

Thanks once again.

**Comment by raisedadead** [comment]
Relevant comment by @vanya829 https://github.com/freeCodeCamp/freeCodeCamp/issues/37825#issuecomment-562617696

> * Add to profile button. [addtoprofile.linkedin.com](https://addtoprofile.linkedin.com/) . The problem of this option is that "Add to profile button" doesn't support autofill of certificate data, so user have to put them manually ([linkedin.com/help/linkedin/answer/61169?query=add%20to%20profile&src=li-other&veh=www.linkedin.com%7Cli-other](https://www.linkedin.com/help/linkedin/answer/61169?query=add%20to%20profile&src=li-other&veh=www.linkedin.com%7Cli-other))
> * Create a certificate using API. This is a solution you are expecting. In this case, we can't do it just in one click, as we have to redirect a user to auth endpoint and only when he is logged in, we can send a request to create a certificate. So can you describe how do you see this interaction from a user perspective?

**Comment by raisedadead** [comment]
We have something similar to this in the works #39466
