### ISSUE TITLE
(Test Fail) Cleanup your project with Modules

### ISSUE THREAD

**Issue by tamerMarzouk** [freeCodeCamp/freeCodeCamp#36283]
**Describe your problem and how to reproduce it:**
To pass the test `  - text: Modules present
    testString: getUserInput => $.get(getUserInput('url')+ '/_api/server.js') .then(data => { assert.match(data, /require.*("|').\/routes.js("|')/gi, 'You should have required your new files'); assert.match(data, /mongo.connect[^]*routes/gi, 'Your new modules should be called after your connection to the database'); }, xhr => { throw new Error(xhr.statusText); })`
The require statement must include the '.js' file extension.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/clean-up-your-project-with-modules/

To pass this test your require statement must be 
`const routes=require('./routes.js');` instead of `const routes=require('./routes');` which is also valid.

**Comment by ojeytonwilliams** [comment]
Thanks @tamerMarzouk, I've verified this and it should definitely accept both.
