### ISSUE TITLE
Waypoint: Create a Form Element - Make sure your form has an action attribute which is set to /submit-cat-photo.

### ISSUE THREAD

**Issue by krispham** [FreeCodeCamp/FreeCodeCamp#3628]
I think I wrote correctly but it doesn't work like I thought :(
![30](https://cloud.githubusercontent.com/assets/13378727/10334974/3089e878-6d18-11e5-8f89-d9420cb51a43.jpg)

**Comment by gwartney21** [comment]
You have it correctly written i went back to mine and i had the same problem.

**Comment by bugron** [comment]
I am able to pass that test with your code. @krispham, @gwartney21 what OS and browser are you using?

**Comment by gwartney21** [comment]
@bugron I am using windows 10 and I am using Google Chrome for my browser

**Comment by tva10** [comment]
@bugron after adding example form in that task, there is an exception in conosle log (XSS Auditor....) I don't know why it is happens, but I pass this task near month ago.
![image](https://cloud.githubusercontent.com/assets/14250295/10337003/8ecd36f0-6d05-11e5-8519-842c3b5292b4.png)

**Comment by bugron** [comment]
@tva10 I can't replicate that in FF but in Chrome I can see that. I think this is caused by `?solution=..` part.

**Comment by zorfa** [comment]
I still have the same issue. I am unable to pass this test despite typing the right code

**Comment by buiphuhai** [comment]
I have same problem. I cant pass through when typing this code in browser Google Chrome. Try Internet Explorer and pass it. 

![image](https://cloud.githubusercontent.com/assets/15012982/10338328/c32b040e-6d05-11e5-9a25-36f4936f9230.png)

**Comment by zorfa** [comment]
I passed it using FireFox and it works. Is there any fix for chrome though?

**Comment by krispham** [comment]
@zorfa you was right, i change my browser and it works. @bugron What's wrong with Chrome :). But thanks you guys for help me.

**Comment by ltegman** [comment]
It looks like both this issue and #3636 are a duplicate of issue #3622

**Comment by ceautery** [comment]
I believe this is caused by a Chromium patch that addresses form actions: http://src.chromium.org/viewvc/blink?view=revision&revision=164538 which addresses this vulnerability report: https://code.google.com/p/chromium/issues/detail?id=331060

Essentially when the common framework script runs safeHTMLRun, preview.write will include a form with an action attribute, trigerring the XSS audit, replacing the action with "data:," in the iframe.

I don't see an obvious way to fix this eloquently, but you could fall back to having the test asserts check editor.getValue's content instead of the iframe DOM.

**Comment by hansinla** [comment]
I can confirm that on Mac OS X, Safari doesn't pas this test either. Firefox does.

**Comment by HusainJaffer** [comment]
If you're Mac then just do it on FireFox.

**Comment by vlcarson** [comment]
Mac and Chrome/Safari - is this going to get fixed? I shouldn't have to install another browser for a bug :(

**Comment by ceautery** [comment]
If no one is already working this, I can commit to starting a patch for it tonight.

**Comment by SaintPeter** [comment]
Not sure why the `action` attribute is getting overwritten:
![image](https://cloud.githubusercontent.com/assets/553494/10350716/794cad16-6cfa-11e5-8c86-1e30b0d76d3d.png)

**Comment by tnegherbon** [comment]
I've had the same problem on Chrome, but was able to validate on Edge.

**Comment by BerkeleyTrue** [comment]
@ceautery Thanks for relevant links. We assumed that Chrome did not like the form action in the URL. We will have to change these tests to against the editor value instead of loading in the iFrame. Unless someone can figure out how to write a form with an action in an iFrame without throwing the XSS auditor.

@bugron Do you have any ideas?

**Comment by sgolwalkar** [comment]
Same issue on Mac OS X and Chrome. Switched to FireFox and it worked. Although, shouldn't have to switch browsers to add a form element.

**Comment by BerkeleyTrue** [comment]
fix in the works

**Comment by jimmy0915** [comment]
Waypoint: Create a Form Element

**Comment by Homulvas** [comment]
I ran into this today using OS X Chrome and Safari. Should I create a new issue or can this one be reopened?

**Comment by Adomos1** [comment]
I can't get it to work in Firefox on OSX

**Comment by svt202** [comment]
Just had this same issue with Chrome/Windows 10. Internet explorer worked fine though!

**Comment by vladas1987** [comment]
you made syntax mistake:
<input type='text' placeholder='cat photo URL'>
 should be:
<input type="text" placeholder="cat photo URL">

**Comment by vladas1987** [comment]
you should use not these '   ' ,  but "  "

**Comment by xiruim** [comment]
get through Chrome / Windows 7
![creat a form element](https://cloud.githubusercontent.com/assets/24372561/21151890/6372fc4a-c18e-11e6-9ee9-5b4484b7dc20.png)

**Comment by IonZero1** [comment]
`<form action="/submit-cat-photo"> <input type="text" placeholder="cat photo URL"></form>`this work for me

**Comment by AbidRiaz** [comment]
Worked for me. I wasn't using closing > for form element before <input.....>. Thank you.

**Comment by EurekaPT** [comment]
I had the same problem. Solved with Opera browser. Thank you guys.

**Comment by martinthecoder** [comment]
I used Internet Explorer instead of Google Chrome to pass it.
<form action="/submit-cat-photo">
  <input type="text" placeholder="cat photo URL">
</form>

Hope this helps. Thanks everyone!

**Comment by dwaine619** [comment]
I just switched to incognito on chrome, and it worked!

**Comment by Neilfoster** [comment]
Same problem today, used firefox and it worked perfectly. Thanks
