### ISSUE TITLE
Guide section is not accessible through a trivial navigation

### ISSUE THREAD

**Issue by mrmowji** [freeCodeCamp/freeCodeCamp#36280]
**Describe the bug**
Currently I can only get to the Guides section using the search. No link is provided in the main menu.

**Desktop**
 - OS: Win7
 - Browser: Chrome

**Comment by Hardik500** [comment]
Apparently guide sections is in the beta version. But it is apparently down.

**Comment by RandellDawson** [comment]
This can be closed as the current master has a link to the Guide but has not been deployed to production.
