### ISSUE TITLE
Wrong hint page for iterate object keys code challenge

### ISSUE THREAD

**Issue by JackHowa** [freeCodeCamp/freeCodeCamp#36289]
**Describe your problem and how to reproduce it:**
Was working on [basic data structures iterating through an object](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement). Wanted to see the hint page. So clicked the hint button that led me to a [404 page](https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement).

**Add a Link to the page with the problem:**
Code challenge page: https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement
Linked hint page: https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement
Correct hint page url: https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for...in-statement

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 74.0.3729.169
* Operating System: Mac

**Comment by RandellDawson** [comment]
This has already been fixed on the master branch but has yet to be deployed.  Once the current master branch has been deployed, this will be resolved.
