### ISSUE TITLE
Test fail if Pug view engine path is set in How to Put a Profile Together

### ISSUE THREAD

**Issue by tamerMarzouk** [freeCodeCamp/freeCodeCamp#36281]
**Describe your problem and how to reproduce it:**
The test for "How to put a profile together" expects the res.render function call to be as follows:
`req.render('/views/pug/profile',{username:req.user.username})`
but if you already set the express view engine using:
`app.set('view engine','pug');
app.set('views',__dirname+'/'+'views/pug');`
 you can issue the render as follows:
`req.render('profile',{username:req.user.username})`

which works correctly  but it will not pass the test.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/how-to-put-a-profile-together

**Comment by KravMaguy** [comment]
regarding the same challenge, if you write ` {username:req.user.username}` it will pass the test. I originally had it as ` {username : req.user.username}`  and this did not pass the test.  Its a problem with the regex testing the challenge? Is it necessary that there be no spaces between the key:value pair?

**Comment by Sky020** [comment]
I can confirm that the test's regex is a bit too rigid:
```
/\/views\/pug\/profile[^]*username:( |)req.user.username/gi
```
To fix the original issue, the test could follow some of the other challenges by making a request to the actual `/profile` and seeing if the response is ok or not.
