### ISSUE TITLE
Passing Values to Functions with Arguments

### ISSUE THREAD

**Issue by StigEzeh** [freeCodeCamp/freeCodeCamp#36291]
My issue is that i am writing the correct code even as it is in the example but it keeps saying test passed but doesnt proceed to the next page. 

`// Example
function ourFunctionWithArgs(a, b) {
  console.log(a - b);
}
ourFunctionWithArgs(10, 5); // Outputs 5

// Only change code below this line.

function fucntionWithArgs(a, b) {
  console.log(a + b);
}
fucntionWithArgs(90, 9);`

 Google Chrome
 Windows

![image](https://user-images.githubusercontent.com/45392554/59515738-b5193c00-8eb7-11e9-8434-1484b657e6a0.png)

**Comment by Hardik500** [comment]
Please mention the link to the challenge.

**Comment by Hardik500** [comment]
Looks like you got a typo error in your code
Instead of fucntionwithArgs it needs to be functionWithArgs.
Let me know if that solves ur problem

**Comment by StigEzeh** [comment]
> Looks like you got a typo error in your code
> Instead of fucntionwithArgs it needs to be functionWithArgs.
> Let me know if that solves ur problem



> Please mention the link to the challenge.
Thanks for replying, here is the link: 

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/passing-values-to-functions-with-arguments/

**Comment by StigEzeh** [comment]
> Looks like you got a typo error in your code
> Instead of fucntionwithArgs it needs to be functionWithArgs.
> Let me know if that solves ur problem

I used functionWithArgs as it is in my screenshot, i noticed over the years a few others have complained about the same test, i suspect there is a bug

**Comment by RandellDawson** [comment]
@StigEzeh Have you asked for help on the forum for your code?  If not, that is the best place to start.  If the forum members determine there is a bug in the tests, then you would create an issue and reference the forum thread discussion.

**Comment by StigEzeh** [comment]
> @StigEzeh Have you asked for help on the forum for your code? If not, that is the best place to start. If the forum members determine there is a bug in the tests, then you would create an issue and reference the forum thread discussion.

Thank you, i will do just that.

**Comment by StigEzeh** [comment]
> Looks like you got a typo error in your code
> Instead of fucntionwithArgs it needs to be functionWithArgs.
> Let me know if that solves ur problem

Yikes, i just saw the error. Thank you.
