### ISSUE TITLE
Lost most of my work last night

### ISSUE THREAD

**Issue by anthonygallina1** [FreeCodeCamp/FreeCodeCamp#3629]
Something happened on the server and most of my work is gone. I still have over 300 points but my map does not reflect it.  Could my projects be restored please?

**Comment by scottwestover** [comment]
This happened to me as well. I still have the points for completing challenges, but a lot of them are now not showing complete on the map.

**Comment by abhisekp** [comment]
:+1:

**Comment by bugron** [comment]
Closing this issue. You can continue further discussion in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3630. Thanks for posting.
