### ISSUE TITLE
Updating the “Reuse Patterns Using Capture Groups” challenge 

### ISSUE THREAD

**Issue by enrique-cardenas** [freeCodeCamp/freeCodeCamp#36303]
**Describe your problem and how to reproduce it:**
I think that by mentioning “\1” maps to “regex” in the example given, the challenge would become more understandable.

I also brought this up in the forum:
https://www.freecodecamp.org/forum/t/updating-the-reuse-patterns-using-capture-groups-challenge/287260

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/reuse-patterns-using-capture-groups/

**Comment by RandellDawson** [comment]
@enrique-cardenas In the challenge description it states:
>An example would be \1 to match the first group.

**Comment by enrique-cardenas** [comment]
@RandellDawson my mistakes, thanks for pointing that out.
