### ISSUE TITLE
Dark-theme on Forums does not work. Background color/image for the theme is not loading.

### ISSUE THREAD

**Issue by cryptographicfool** [freeCodeCamp/freeCodeCamp#36308]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
Background color of the dark-theme on the forums is not loading. I am greeted with light gray text on white background.

**To Reproduce**
1. Go to FCC forums.
2. Click on your profile image on top right and select preferences.
3. Click on interface on bottom left.
4. Select dark-theme under theme and see how the background is not working properly. 

**Expected behavior**
I expected the dark theme to load as usual with a dark grey background, but it fails to load or the color of the background is wrong. 

**Screenshots**
![Screenshot-2019-6-20 The freeCodeCamp Forum(1)](https://user-images.githubusercontent.com/51486480/59866558-77318180-93a9-11e9-9331-b1c6952a19b4.png)
![Screenshot-2019-6-20 The freeCodeCamp Forum](https://user-images.githubusercontent.com/51486480/59866559-77318180-93a9-11e9-82d6-5288538fc004.png)

**Desktop (please complete the following information):**
 - OS: Tried on Fedora25, Debian 9-stretch, Ubuntu 18 and macOS Mojave.
 - Browser: Tried on FirefoxESR, Firefox, Chrome and Safari.

**Additional context**
That is all, I have added the screenshots, it should help explain the problem. 
Thank  you!

**Comment by wulforr** [comment]
It is not working on kali as well on FirefoxESR

**Comment by cryptographicfool** [comment]
> It is not working on kali as well on FirefoxESR

Not working anywhere, there is an open [thread](https://www.freecodecamp.org/forum/t/why-is-forum-dark-theme-no-longer-working/287647) on fcc forums about the same. They should be resolving it soon.

**Comment by raisedadead** [comment]
Resolved, thanks for reporting.

**Comment by cryptographicfool** [comment]
> Resolved, thanks for reporting.

Great, thank you! :)
