### ISSUE TITLE
README files for other languages need to be renamed/moved or deleted from root repo directory

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#36316]
Currently in the master branch the following files are in the root directory:
[README.french.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/README.french.md)
[README.italian.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/README.italian.md)
[README.korean.md](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/README.korean.md)

These should not be here.  Instead they should be located in [docs](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs) directory inside the applicable language folder. 

For the `README.italian.md` file the fix is easy.  It just needs to be renamed to `README.md` and moved to the `italian` directory within the `docs` directory.  However, for the `README.french.md` and then `README.korean.md` files, there is already a `README.md` file inside the directories of the same language name.  Which version is the better translation and reflect the most recent changes in the main `README.md` file in the root directory?

Further complicating what to do about the `README.french.md` file is there are currently two open PRs (#36202 and #36282) with changes to these files.  #36202 makes changes to `docs/french/README.md` and #36282 makes changes to `README.french.md` in the root directory.

**Comment by nguyenami** [comment]
I would like to do the same for vietnamese as well. Just wondering if fcc still accept other languages translation?

**Comment by moT01** [comment]
As far as I know, we do still accept translations for the documentation in other languages @nguyenami. But that's not what this issue is referring to. This issue is saying that some of the translated documentation is in the wrong area of the file system/repo. If you want to translate some of the documentation, you can simply create a PR for it. But be forewarned that there may be very few or no reviewers that speak Vietnamese who can get your work added. Maybe you know a few who could look over your work?

**Comment by huyenltnguyen** [comment]
The `README.md` files in `/docs/*` are translated from the [Documentation Quick Reference](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/README.md), which is the `README.md` in the `/docs` directory. This file is different from the on in the root directory, though.

This means PR #36202 and #36282 are not related to each other.

Regarding the root directory cleanup, I'd suggest we:
- Rename the `README.md` inside `/docs` to something else (`DOCUMENT_QUICK_REFERENCE`?)
- Rename the existing `README.md`s `/docs/*` to the same name as the one above
- Move the `README.*.md` from the root directory to their corresponding `/docs/*` directory, and rename them to `README.md`

**Comment by huyenltnguyen** [comment]
Hey @nguyenami, thanks for giving us a hand!

As Tom said, we welcome translation of documentation in any language, so feel free to work on them. I speak Vietnamese, so I can help review your PR once you're done.

You should follow the [Contribution Guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md) to get started, and drop a line in the [Contributors chatroom](https://gitter.im/freecodecamp/contributors) if you have any question or need any help.

Happy contributing!

**Comment by Arezohayeman** [comment]
07/10/2019 : 
[PKCS_12_-_Wikipedia.pdf](https://github.com/freeCodeCamp/freeCodeCamp/files/3370704/PKCS_12_-_Wikipedia.pdf)
05:17:20
