### ISSUE TITLE
should users be explicitly told to go to the settings to claim certificates?

### ISSUE THREAD

**Issue by Ieahleen** [freeCodeCamp/freeCodeCamp#36310]
On the FCC forum there are a few threads each week opened because users don't get the certificate immediately after completing the Responsive Web Design Projects.

I don't know what should be the better way, but I propose to make more clear to users that they need to go to the Settings to claim their certificate.

**Comment by moT01** [comment]
It would be kinda nice if it were automatically claimed when you complete the last project you need, and you get a congratulations popup

**Comment by Ieahleen** [comment]
That I wouldn't agree on, it happened to me too to submit a link by
mistake, and I don't want to have that mistakenly submitted link to give me
the certificate
Instead a pop-up that say something like "If you are satisfied with your
work and you pass all user stories go to the settings and clam your
certificate"

>

**Comment by raisedadead** [comment]
Yes, we should probably add this. /cc @ahmadabdolsaheb

**Comment by ahmadabdolsaheb** [comment]
we could have add a button to redirect to settings or claim cert on the completion modal when all of the required projects for a cert are submitted and the related cert is not claimed 
Having in mind that redux should be in sync with the DB to avoid asking users to reclaim their certs.

**Comment by deepgoonumich** [comment]
My colleague @manrajtoor and I would love to take a shot at this for a school project. Excited to learn from everyone in this community.

**Comment by ahmadabdolsaheb** [comment]
I will close this issue in favor of #38569.
Please feel free to go ahead and start working on it and refer to #38569 for more context.
