### ISSUE TITLE
palindromes 

### ISSUE THREAD

**Issue by MooohamedAli** [FreeCodeCamp/FreeCodeCamp#3631]
write a code of palindromes

**Comment by bugron** [comment]
@MooohamedAli thanks for posting this issue!
Please edit the title and the description of this issue to make them more informative, or else it will be closed, thanks.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by BerkeleyTrue** [comment]
Closing. Please feel free to re-open with steps and a description on how to reproduce the issue.

Happy Coding!
