### ISSUE TITLE
FCC: Javascript Calculator does not allow integer 0 to be the first operand

### ISSUE THREAD

**Issue by kiwisquash** [freeCodeCamp/freeCodeCamp#36327]
**Describe your problem and how to reproduce it:**
The sample calculator for [Front End Libraries Projects - Build a JavaScript Calculator](https://learn.freecodecamp.org/front-end-libraries/front-end-libraries-projects/build-a-javascript-calculator/) does not allow integer 0 to be the first operand.

To reproduce, go to the calculator link, try pressing 0, followed by an operation. Or just start using operations starting from the default screen, which shows a 0.

You will see the operation appear on its own without a first operand. 

**Add a Link to the page with the problem:**

https://codepen.io/freeCodeCamp/full/wgGVVX

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 67.0.4 (64 bit)
* Operating System: MacOS Mojave

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![Screen Shot 2019-06-25 at 8 53 32 AM](https://user-images.githubusercontent.com/34022735/60113605-0252a480-9727-11e9-8ba4-0a4e5ad6ed4c.png)

This is the result of hitting the 0 pad followed by the X pad followed by the 9 pad 3 times. You can continue entering other operations, and numbers, but the = pad will not do anything at this point. Must hit AC and start over.

**Comment by JuWeber99** [comment]
@raisedadead is there any update on this? if not i whould like to try to fix this since robert didn't update this :)

**Comment by iccir919** [comment]
The issue is a simple fix. The code references a state value named 'evaluated' that is not declared in the constructor function. To make the code work as expected requires the addition of this value equal to false. 

```
this.state = {
      currentVal: '0',
      prevVal: '0',
      formula: '',
      currentSign: 'pos',
      lastClicked: '',
      evaluated: false
};
```

**Comment by iccir919** [comment]
I think I may have a solution. The code references a state value named 'evaluated' that is not declared in the constructor function. I initiated the value back to the state declaration.
`this.state = {
      currentVal: '0',
      prevVal: '0',
      formula: '',
      currentSign: 'pos',
      lastClicked: '',
      evaluated: false
};`
Also, I added the following code in bold to the handleOperators function. 
`
    if (!this.state.currentVal.includes('Limit')) {
      const value = e.target.value;
      const { formula, prevVal, evaluated } = this.state;
      this.setState({ currentVal: value, evaluated: false });
      if (evaluated) {
        this.setState({ formula: prevVal + value });
      } **else if (formula === "") {
        this.setState({
          prevVal: 0,
          formula: formula + 0 + value
        })
      }** 
`

**Comment by raisedadead** [comment]
Hi @JuWeber99 thanks for drawing my attention to this. @scissorsneedfoodtoo can you please check the linked PR and confirm the action item on this?

**Comment by iccir919** [comment]
I believe I have a fix to this issue. I added the evaluated value back to the initial state and st it to false. 
    this.state = {
      currentVal: '0',
      prevVal: '0',
      formula: '',
      currentSign: 'pos',
      lastClicked: '',
      evaluated: false
    };
Also, I added the code below in bold to the function handleOperators:
if (evaluated) {
        this.setState({ formula: prevVal + value });
      } **else if (formula === "") {
        this.setState({
          prevVal: 0,
          formula: formula + 0 + value
        })
      }**

**Comment by scissorsneedfoodtoo** [comment]
Hi @JuWeber99, sorry for the late response and thank you both for your patience and for reporting this. I tested the changes in https://github.com/freeCodeCamp/testable-projects-fcc/pull/936 and it seems to solve this issue. 

I'll merge that once the tests pass and update the code on CodePen.
