### ISSUE TITLE
Missing paragraphs in challenges

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#36324]
**Describe your problem:**

Paragraph breaks in challenge descriptions that are present in production are missing in the master branch.  The blocks of text that are paragraphs in production are only separated by single newline characters in the source markdown (on the master branch).  This is not enough to push them into paragraphs - they need to be separated by an entire empty line.

**Add a Link to the page with the problem:**

The problem is ubiquitous, but a good example is the [first challenge](https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements/) which looks like this on live:

![HelloLive](https://user-images.githubusercontent.com/15801806/60082370-e1448080-9733-11e9-85b9-290d99e8595f.png)

and master:

![HelloMaster](https://user-images.githubusercontent.com/15801806/60082390-e99cbb80-9733-11e9-8138-032de55e04df.png)

From [Basic CSS](https://learn.freecodecamp.org/responsive-web-design/basic-css/change-the-color-of-text), live:

![BasicCSSLive](https://user-images.githubusercontent.com/15801806/60082829-dc340100-9734-11e9-92db-2038548fed31.png)

and master:

![BasicCSSMaster](https://user-images.githubusercontent.com/15801806/60082843-e7872c80-9734-11e9-98f6-a0e9319b42e4.png)

**Comment by ojeytonwilliams** [comment]
I don't think this problem can be solved by changing the parser, since it's behaving correctly when given blocks of text are separated by an empty line.  The markdown itself will need changing, but it isn't as simple as globally replacing `\n` -> `\n\n` since that will mess up any code blocks and any embedded html.  However, as long as it's restricted to text, it should be safe.

**Comment by RandellDawson** [comment]
This used to not be a problem.  Something has changed.

**Comment by ojeytonwilliams** [comment]
Any idea when it was working?  I couldn't find any obvious changes in the parser or in the challenges, and the first challenge has (probably) been wrong since [October](https://github.com/freeCodeCamp/freeCodeCamp/blob/8f39bc12887a251fc7146e6d288de44ba279612f/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/say-hello-to-html-elements.english.md).

**Comment by ojeytonwilliams** [comment]
Turns out I wasn't looking hard enough.  My PR, https://github.com/freeCodeCamp/freeCodeCamp/pull/35864 caused it, so I'll just revert that if I can't come up with a better solution.
