### ISSUE TITLE
Medium link in README.md needs to be updated

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#36320]
[The Learning Platform](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/README.md#the-learning-platform) section is still having a Medium link.

There are two things that needs to be updated: the link text and the fCC News URL.

List of doc files that need the update applied:
- [x] https://github.com/freeCodeCamp/freeCodeCamp/blob/master/README.md
- [x] https://github.com/freeCodeCamp/freeCodeCamp/blob/master/README.french.md
- [x] https://github.com/freeCodeCamp/freeCodeCamp/blob/master/README.italian.md
- [x] https://github.com/freeCodeCamp/freeCodeCamp/blob/master/README.korean.md

**Comment by raisedadead** [comment]
Thanks, @huyenltnguyen Can you please audit all the docs and we can then update all of these together? I think we will have them pointed to freeCodeCamp news. Do not worry about the new link label for now, I'll have Quincy give us the exact text.

**Comment by huyenltnguyen** [comment]
@raisedadead I've updated my original post to add the affected doc files.

I also found that we would need to update article links in many guide articles as well, since they are using Medium link (`medium.freecodecamp.org/article-title`).

**Comment by raisedadead** [comment]
The old links should redirect automatically, we do not have to worry about those.

**Comment by jonathan-grah** [comment]
Tagging @QuincyLarson for the updated way of describing our news platform.

**Comment by raisedadead** [comment]
```md 
- The [Developer News](https://www.freecodecamp.org/news), a free, open source, no-ads place to cross-post your blog articles.
```

**Comment by huyenltnguyen** [comment]
Thanks @raisedadead!

I've created a PR for the English version of the README.md, but we still need some help with the translation in other languages.

**Comment by raisedadead** [comment]
> I've created a PR for the English version of the README.md, but we still need some help with the translation in other languages.

You can just use the Google translate version of the english sentence, someone will eventually make it more accurate.

**Comment by huyenltnguyen** [comment]
Closing the issue as all the PRs have been merged.
