### ISSUE TITLE
question: why doesn't Javascript have optional static typing ? 

### ISSUE THREAD

**Issue by catastrop** [freeCodeCamp/freeCodeCamp#36321]
tc39 is adding new things to JS. But why not optional static typing ?

If they do it, we don't have to use Typescript anymore and being able to pass type information to the engine.

We will have less dev dependency.

**Comment by RandellDawson** [comment]
Please only report issues with the repo.  For discussions, you can open a topic on [our forum](https;//freecodecamp.org/forum).

Thank you.
