### ISSUE TITLE
Video instruction (Watch a Video) place to a wrong challenge 

### ISSUE THREAD

**Issue by vownfinel** [freeCodeCamp/freeCodeCamp#36333]
**Describe your problem and how to reproduce it:**
Two of the instructional videos got to switch on to each other. 
Applied Accessibility: Make Screen Reader Navigation Easier with the header Landmark (Watch a Video) shows a video for Applied Accessibility: Make Screen Reader Navigation Easier with the nav Landmark
*Vice Versa

**Add a Link to the page with the problem:**

https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/make-screen-reader-navigation-easier-with-the-header-landmark

https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/make-screen-reader-navigation-easier-with-the-nav-landmark

**Tell us about your browser and operating system:**
* Browser Name: Safari
* Browser Version: Version 12.0.3 (14606.4.5)
* Operating System: MacOs Mojave

![Screen Shot 2019-06-26 at 4 23 31 PM](https://user-images.githubusercontent.com/48802506/60194342-b65d4800-986b-11e9-8ede-77ab86bc393d.png)
![Screen Shot 2019-06-26 at 4 22 58 PM](https://user-images.githubusercontent.com/48802506/60194355-bcebbf80-986b-11e9-87e5-7d894715ca7e.png)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@vownfinel Thanks for you reporting the issue.  Actually, the mixup was fixed on PR https://github.com/freeCodeCamp/freeCodeCamp/pull/3489, but since the master branch has not been deployed to production since October, it is not reflected on the site.  Once it gets deployed (which we hope is soon), the correct video will show for each challenge.  I am closing this issue as we are just awaiting a deployment to production.

Thanks again.

**Comment by vownfinel** [comment]
@RandellDawson that was fast! this is my 1st post. 

Thank you so much! Hope you have a good day ahead. 

Regards,

**Comment by gauravkukade** [comment]
:smile: , I was here to report the same, searched the issues if it is already reported and found it here.

I will find another one for my first post. @vownfinel :slightly_smiling_face: :+1:
