### ISSUE TITLE
Profile shows about commitment which I never made.

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/FreeCodeCamp#3633]
I clicked on the $5 commitment but I never fulfilled it or don't plan to. But my profile shows about the commitment.

![](http://i.imgur.com/lSqLcNk.png)

**Comment by QuincyLarson** [comment]
These commitments are self-reported. We assume you go through with the donation. Did you click the golden "commit" button? 

That's why we use the word "pledge" instead of "donate". You can edit your commitment at the bottom of your code profile.

**Comment by abhisekp** [comment]
@QuincyLarson nice! :+1: 
I thought it would be something like another "goal" related project in which people assign a donation amount to their goal. If they don't reach the goal till the deadline, then a chosen amount is donated to the chosen campaign.
