### ISSUE TITLE
Updating challenges(courses)

### ISSUE THREAD

**Issue by saliha-naico** [freeCodeCamp/freeCodeCamp#36332]
While courses in freecodecamp are updated, is that just the .md files get updated and executing 'npm run seed' command will update the DB with the latest data? Is this the same what happens when a new course is added.

**Comment by moT01** [comment]
This doesn't sound like an issue. If you need help you can try asking on [the forum](https://www.freecodecamp.org/forum/c/contributors) or [the contributors chat room on gitter](https://gitter.im/FreeCodeCamp/Contributors)

I'm not sure what exactly your question is, but if you have an instance of the repo running locally and make changes to a challenge, it should immediately show those changes in your browser. If you add a new challenge, you may need to re-seed the database.
