### ISSUE TITLE
Editor doesn't work with Ghost Text or Atomic Chrome

### ISSUE THREAD

**Issue by mrbig033** [freeCodeCamp/freeCodeCamp#36334]
#### Runtime Environment

- MX Linux 18
- GNU Emacs 27.0.50

#### Issue

[GhostText](https://github.com/GhostText/GhostText) and [Atomic Chrome](https://github.com/danhper/atomic-chrome) are Google Chrome extensions that allow me to synchronize any text area in the browser with my text editor of choice, Emacs, using [this package](https://github.com/alpha22jp/atomic-chrome). It seems to work everywhere, but for some reason freeCodecamp's text editor cannot synchronize. 

I'm opening this issue here because every other combination worked fine.

**Comment by RandellDawson** [comment]
@raisedadead What are your thoughts?

**Comment by mrbig033** [comment]
I'm a beginner in programming and WebDev and have no experience with JavaScript. But my guess is that whatever signal these packages use to communicate is not available in the freeCodecamp's editor.

I'm sorry I can't be more helpful.

**Comment by raisedadead** [comment]
Thanks for your interest and we would love to support this, but unfortunately we do not have the bandwidth on the core development team, to work through these 'nice to have' features.

We are open to a pull request though.

**Comment by mrbig033** [comment]
I appreciate the candor and politeness and empathize with the very reasonable justification you're presenting. I will try to collaborate on this issue when I acquire more knowledge. Thank you very much for taking the time to answer me.
