### ISSUE TITLE
Testing Issue (Test passes even when it shouldn’t)

### ISSUE THREAD

**Issue by Edwinyms** [freeCodeCamp/freeCodeCamp#36330]
Coding Interview Prep - Data Structures;

The testing of challenges in the aforementioned section always passes (all the test-cases pass and I am able to move ahead to next challenge) even if the code is clearly wrong.

I have observed this issue for the past couple of days.

Thanks

**Comment by RandellDawson** [comment]
Can you be more specific about which challenges and which code you are using for the challenges?

**Comment by Edwinyms** [comment]
I have observed this issue in a number of challenges in the Data Structures section under the Coding Interview Prep category.

The issue mentioned above starts (from what I can see) from the 'Perform a Union on Two Sets' challenge and ends at 'Use Spread and Notes for ES5 Set() Integration' challenge.

I am using the Google Chrome.

And in regards to my code; simply typing anything into the editor gives me a 'Pass'. It even passes when the editor is completely empty. 

Thank you :)

**Comment by RandellDawson** [comment]
Can you post the actual code which passes for the Perform a Union on Two Sets challenge which you feel should not pass?  Thank you.

**Comment by Edwinyms** [comment]
I'm sorry for the miscommunication. 

The issue starts at 'Perform and Intersection on Two Sets of Data' challenge.

So, the below are the codes that I used for the 'Perform and Intersection on Two Sets of Data' challenge:

First example: 
```
//There is no code here at all. The editor is completely empty in this example. Test still passes.
```

Second example:
```
let x = 1;
```

Both the examples above allow me to proceed to the next challenge.


Thanks

**Comment by RandellDawson** [comment]
@Edwinyms I see what you mean on the production site.  There were some changes made a while back on the master branch of the repo which fix this issue, but the changes have yet to be deployed.  I am closing this issue for now, because I have validated your code fails the tests as it should using the latest master branch code.
