### ISSUE TITLE
Responsive image - should be width instead of max-width

### ISSUE THREAD

**Issue by rofrol** [freeCodeCamp/freeCodeCamp#36342]
**Describe your problem and how to reproduce it:**
In the task there is description:

>The max-width property of 100% scales the image to fit the width of its container

which is not true. To scale the image you need to use `width: 100%`.
**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/make-an-image-responsive

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by lasjorg** [comment]
It does exactly what it says it does.

> The max-width property of 100% scales the image to fit the width of its container, **but the image won't stretch wider than its original width.** 

Example:
https://codepen.io/anon/pen/orpMBB

**Comment by moT01** [comment]
So is this still a problem @rofrol? Seems to make sense to me. Can you close this please if you think it's fine.

**Comment by rofrol** [comment]
Right. It scales down. Closing.
