### ISSUE TITLE
NPM Introduction Page has a typo 

### ISSUE THREAD

**Issue by mtpiercey** [freeCodeCamp/freeCodeCamp#36348]
On https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm, there's a minor typo (looks like a Markdown error, but I'm not sure) regarding the ```node_modules``` folder. 

![fcc_npm_typo](https://user-images.githubusercontent.com/22581026/60389647-5943db00-9a93-11e9-950d-b4e1f2cb1d40.jpg)

**Comment by rmfranciacastillo** [comment]
Seems that in the latest pull this typo was fixed. 

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/pages/learn/apis-and-microservices/managing-packages-with-npm/index.md

**Comment by mtpiercey** [comment]
Glad to hear it!
