### ISSUE TITLE
I can't claim the front end developer certificate

### ISSUE THREAD

**Issue by jbmartinez** [FreeCodeCamp/FreeCodeCamp#3634]
I already completed the whole map, except the waypoints added in the last update, and wanted to claim the certificates. I clicked the link in the map and reached a page which says

>Let's confirm that you have completed all of our basic and intermediate Bonfires, and all our basic and intermediate Ziplines. Click the button below to verify this.

After clicking the button, I received the message

>Looks like you have not completed the neccessary steps. Please return to the challenge map.

Do I need to complete the new waypoints too?

Edit: the new waypoints are related to the sections "Get Started with Free Code Camp" and "Gear up for Success"

**Comment by QuincyLarson** [comment]
@jbmartinez You should not need to complete any of the Waypoints - we only look at Bonfires, Ziplines and Basejumps. Could you pair with either me or @BerkeleyTrue later today so we can try to figure out what happened? Thanks for reporting this.

**Comment by nickbarry** [comment]
I'm running into this same problem. I see this: "Looks like you have not completed the neccessary steps. Please return to the challenge map."

However, I have completed all the relevant steps:
![fcc map](https://cloud.githubusercontent.com/assets/8515899/10345430/6190d7d6-6cde-11e5-81ef-0401ca155c49.png)

**Comment by BerkeleyTrue** [comment]
I'm looking into it

**Comment by BerkeleyTrue** [comment]
I've found the issue. Expect a patch soon

**Comment by BerkeleyTrue** [comment]
Fix is live. Please give it a try.

**Comment by jbmartinez** [comment]
It's working fine, thank you!

**Comment by nickbarry** [comment]
@BerkeleyTrue I was able to claim my certificate, but my name isn't filled in on the certificate:
http://www.freecodecamp.com/nickbarry/front-end-certification
![image](https://cloud.githubusercontent.com/assets/8515899/10412653/70da527a-6f41-11e5-8ea5-6f795331783a.png)

**Comment by bugron** [comment]
@nickbarry, I think https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3654 should help.

**Comment by nickbarry** [comment]
Yep, @bugron , that did it! Thanks.

**Comment by g15212** [comment]
Hi,

sorry for my bad english,

I already completed erverthing to get the front end certificate but when i tried to get the certificate the buttons [open link in a new tab] doesn´t work. And I only come to step 3 not to step 4.

Please help.

**Comment by kronengold** [comment]
Hi,

I completed all of the Front-End steps and on the certification step I was presented with a certificate with the wrong name and completion date.

**Comment by vaheed-sediqi** [comment]
https://www.freecodecamp.org/vaheed-sediqi/front-end-certification

**Comment by cunleo** [comment]
check
https://forum.freecodecamp.org/t/how-can-i-get-a-copy-of-my-front-end-certificate/146927/8
