### ISSUE TITLE
Get a hint link broken for "Basic CSS: Improve Compatibility with Browser Fallbacks"

### ISSUE THREAD

**Issue by hemanthsavasere** [freeCodeCamp/freeCodeCamp#36351]
**Describe your problem and how to reproduce it:**
Get a hint link is broken. Getting 404 error status code.
Steps to follow:-
- Go to the "Basic CSS: Improve Compatibility with Browser Fallbacks" coding challenge.
- Click on get a hint on the left side. 

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/responsive-web-design/basic-css/improve-compatibility-with-browser-fallbacks

**Tell us about your browser and operating system:**
* Browser Name:  Firefox
* Browser Version: 67.0.4
* Operating System:  Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@hemanthsavasere This issue was resolved by pull request https://github.com/freeCodeCamp/freeCodeCamp/pull/34728, but does not show on the production site due to the fact that the master branch has yet to be deployed to the production site.  We are hopeful this deployment will take place soon.
