### ISSUE TITLE
Final Projects Accept Any Link as a Solution

### ISSUE THREAD

**Issue by AlvaroLuken** [freeCodeCamp/freeCodeCamp#36365]
**Describe the bug**
(SORRY IF REPEAT) Any arbitrary link is accepted as a solution for the Responsive Web Design Projects (and thus I am assuming for all other project pages). Links like https://facebook.com and https://www.amazon.com are accepted as solutions. Curriculum is checked off only if user selects 'Submit and go to next project'.

**To Reproduce**
1. Go to 'https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-projects/build-a-product-landing-page'
2. Click on 'Solution input bar and submit any arbitrary link... for example: Google, Facebook, Amazon.com (will require full https://www....)
4. Accepts the link as a solution and checks it off in your curriculum ONLY IF YOUR PRESS ADVANCE, if you press back nothing happens.

**Expected behavior**
Should maybe reject any non-codepen/github links? I know individual project checking is not done, but at least this adds a bit of integrity to these 'final projects'.

**Screenshots**
<img width="1280" alt="Screen Shot 2019-07-01 at 10 52 39 PM" src="https://user-images.githubusercontent.com/25407127/60485748-d79aab80-9c52-11e9-972a-63a6de48e066.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX latest version
 - Browser: Chrome
 - Version: 75.0.3770.100 (Official Build) (64-bit)

**Additional context**
Could create cookie in codepen doc that is saved with link ONLY IN THE CASE OF ALL TESTS PASSING then when user submits link in page, link is checked against saved cookie and test is accepted. Anyone can game the system in this case and the value of the certificate drops. I don't mean it in a bad way, just want the best for this incredible page!

**Comment by vishwasnavadak** [comment]
This is a good catch. 

I just checked for other project pages like frontend library and data visualization projects, all of them accept random links too. This makes anyone claim any certificates easily.

**Comment by Ronkiro** [comment]
There are three issues about this same topic.
Issue #34763 was closed in favor of #35015, in which ended up with this issue #35054.
I think you could share some ideas around those issues. I think your solution is nice, but would still open space for empty pens, for example...

**Comment by RomeoRaven** [comment]
Just want to add that I was not finding a way to submit my project for checking correctly via Codepen and found this github issue. Tested on my own project and the 'Solution' field even accepts non-URL input. Example...

![FCC-tribute-page-issue](https://user-images.githubusercontent.com/13630119/60926285-0ed11400-a274-11e9-98cf-22d0268edb6f.PNG)

**Comment by vishwasnavadak** [comment]
The issue @RomeoRaven is because of the type="url" being set on the input. That is the reason it treats the file path as the URL. 
![image](https://user-images.githubusercontent.com/13111030/60938141-690fba80-a2f0-11e9-9631-b43e6a99b472.png)

Even though type="url" does validate most of the cases, we might need to have a regex pattern validation for validating this type of edge cases.

**Comment by raisedadead** [comment]
Thanks for reporting the issue, I am closing this in favor of #35054. 

Thanks for all your suggestions, but programmatic evaluation while being flexible about any platform / language stack of your choice is a very difficult problem. We rely on honor and reporting instead.

That said, we are also moving to a project-based evaluation in our next iteration of the curriculum. You can read about it on or forum: [Forum](https://www.freecodecamp.org/forum)
