### ISSUE TITLE
Docker mongo db image not updating

### ISSUE THREAD

**Issue by sadikn** [freeCodeCamp/freeCodeCamp#36369]
I have updated the seedAuthUser.js to add some new fields and I have run the "npm run docker:seed" command but I am getting the old db values and can't see the new fields I have added. Is there anything else I need to update?

**Comment by raisedadead** [comment]
You will have to delete the user object from the db first I think. The script will not overwrite on a existing user I think.

I am closing this, for now for lack of information, will re-open if this is found to be a legitimate bug.

We can continue to discuss in the thread or over our [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) and [Contributors category on the Forum](https://www.freecodecamp.org/forum/c/contributors) if this is just some general query about freeCodeCamp's codebase.
