### ISSUE TITLE
Add Keywords to your package.json challenge not working

### ISSUE THREAD

**Issue by mtpiercey** [freeCodeCamp/freeCodeCamp#36375]
As the challenge stated, I added some words to my ```package.json``` file in my Glitch app (https://shaded-brook.glitch.me/). The challenge said one of the words had to be ```freecodecamp```, so I put it there.

```
"Add an array of suitable strings to the keywords-field in the package.json of your Glitch project.

One of the keywords should be freecodecamp."
```

Below is my full ```package.json```:

```json
{
  "//1": "describes your app and its dependencies",
  "//2": "https://docs.npmjs.com/files/package.json",
  "//3": "updating this file will download and update your packages",
  "name": "hello-express",
  "version": "0.0.5",
  "description": "Hello There",
  "keywords": [ "freecodecamp", "express", "hello" ],
  "author": "Matthew Piercey",
  "main": "server.js",
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.16.4"
  },
  "engines": {
    "node": "8.x"
  },
  "repository": {
    "url": "https://glitch.com/edit/#!/hello-express"
  },
  "license": "MIT",
  "keywords": [
    "node",
    "glitch",
    "express"
  ]
}
```

However, when I press the ```I've completed this challenge``` button after inputting "https://shaded-brook.glitch.me/" into the blank, the tester box says:

```
// running tests
"keywords" does not include "freecodecamp"
// tests completed
```

https://learn.freecodecamp.org/apis-and-microservices/managing-packages-with-npm/add-keywords-to-your-package-json

* Browser Name: Google Chrome
* Browser Version: 75
* Operating System: macOS Sierra

----------
Any help would be appreciated.

**Comment by fletcher-greg** [comment]
Check the bottom of your package.json again.  You may have duplicated the task.

**Comment by mtpiercey** [comment]
Ah, yes. Once again, the solution boils down to simple literacy. Thanks for pointing that out...
