### ISSUE TITLE
Remove global flag from the regex in solution of `No Repeats Please` problem

### ISSUE THREAD

**Issue by arshdkhn1** [freeCodeCamp/freeCodeCamp#36377]
**Describe your problem and how to reproduce it:**
The code solution uses global flag in regex, which should not be used unless you really want to use a global flag. The solution works fine, but it is prone to error. Try replacing match with RegExp.test and you ll see the issues that I am talking about. 

See - [why-does-a-regexp-with-global-flag-give-wrong-results](https://stackoverflow.com/questions/1520800/why-does-a-regexp-with-global-flag-give-wrong-results) and [last baa word not getting filtered](https://stackoverflow.com/questions/56894216/why-is-the-last-baa-not-getting-filtered-out-with-uncommenting-the-console-log) for more info.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/coding-interview-prep/algorithms/no-repeats-please/

**Comment by arshdkhn1** [comment]
Also `var permutations` should be assigned an empty array instead of `<a href='https://forum.freecodecamp.com/images/emoji/emoji_one/rocket.png?v=3 ":rocket:"' target='_blank' rel='nofollow'>];`

**Comment by RandellDawson** [comment]
I will take care of this.

**Comment by RandellDawson** [comment]
@arshdkhn1 I created the necessary pull request to fix the Guide.  Once it is merged, we will still have to wait for the master branch to be deployed to the production site.
