### ISSUE TITLE
Feature Request - FCC Live Events Banner

### ISSUE THREAD

**Issue by 0x0936** [FreeCodeCamp/FreeCodeCamp#3637]
It may be useful to have some kind of banner showing live FCC events within 24 hours on fcc.com. Otherwise, if someone is new or doesn't know about the monthly stream, they won't know about it unless they're on gitter as the stream is about to start.

**Comment by BerkeleyTrue** [comment]
@0x0936 We are an open source community. Do you mind putting together a pull request? Otherwise I think this issue will be closed as we communicate most of our events through Twitter/Facebook/Gitter/Email, which I think is sufficient to get the word out.

**Comment by bugron** [comment]
Not sure if anyone is going to work on this. Closing.
