### ISSUE TITLE
MEAN stack fails to install on C9.io

### ISSUE THREAD

**Issue by bwobst** [FreeCodeCamp/FreeCodeCamp#3638]
I'm starting the basejumps and noticed that following the directions on http://www.freecodecamp.com/challenges/waypoint-get-set-for-basejumps doesn't quite match the Yeoman prompts anymore and I'm not able to successfully install the MEAN stack by following the instructions on that page.

Let me know if there's another way to get MEAN on C9.io!

Brian

**Comment by QuincyLarson** [comment]
We're replacing Yeoman with Clementine. The new updated challenge will be ready in the next few days.

**Comment by levyian** [comment]
@bwobst What version of Node are you using? I was able to get mine to work by updating the default version. Try this `nvm install 0.12.7`

The main issue I had was that on the free version of C9.io, I would always run out of memory installing the modules. My workaround was to 
1. delete the entire node_modules folder
2. edit package.json file and remove all Dev-dependencies and 80% regular dependencies
3. re-add 4-5 dependencies (then finally Dev-dependencies) at a time
4. run `npm install`
5. repeat step 3 & 4 until all dependencies are installed

Another thing I noticed was that after all the modules were installed I was left with ~80mb of drive space remaining.

Hope that helps until Clementine comes out.

@QuincyLarson Do you know if Clementine will address the space issue on the free version of C9.io?

**Comment by bwobst** [comment]
@levyian Thanks for the workaround - happy to hear there is a way to get it working.  I've been wanting to experiment with Meteor so I figured I'd do the first basejump with that.  Will try out the Clementine alternative when it gets implemented.

**Comment by awesomeaniruddh** [comment]
Issue seems to have been fixed. Closing it.

**Comment by andylacroce** [comment]
@QuincyLarson Any update on the implementation of the Clementine solution?  I am still blocked setting up my dev environment.

**Comment by zakrr** [comment]
Clementine is not up yet and I can't seem to get the work around to work.

**Comment by BerkeleyTrue** [comment]
@andylacroce @zakrr It's on its way. Thanks for your patience.
