### ISSUE TITLE
Guide article stubs don't link to right repo

### ISSUE THREAD

**Issue by oyekanmiayo** [freeCodeCamp/freeCodeCamp#36386]
Guide article stubs on freeCodeCamp link to an archived repository which makes it hard to create PRs for them.

See here: https://guide.freecodecamp.org/certifications/responsive-web-design/applied-visual-design/create-texture-by-adding-a-subtle-pattern-as-a-background-image

Added images below:
<img width="1412" alt="Screen Shot 2019-07-04 at 2 28 18 PM" src="https://user-images.githubusercontent.com/26260543/60733098-dbc11480-9f43-11e9-9385-ce0e2810a651.png">
<img width="1403" alt="Screen Shot 2019-07-04 at 2 28 16 PM" src="https://user-images.githubusercontent.com/26260543/60733221-204cb000-9f44-11e9-9049-e93c78ebbe69.png">

**Comment by RandellDawson** [comment]
@oyekanmiayo The current production uses the now archived guide repo.  All changes to the guide should be done on the [mono repo](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/guide/english/certifications) which will be deployed to production (for the first time since October) in the coming weeks.  I am going to close this issue as this is the current workflow.

**Comment by oyekanmiayo** [comment]
Thank you

**Comment by underlineGalaxy** [comment]
> @oyekanmiayo The current production uses the now archived guide repo. All changes to the guide should be done on the [mono repo](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/guide/english/certifications) which will be deployed to production (for the first time since October) in the coming weeks. I am going to close this issue as this is the current workflow.

Hello, as of right now this problem hasn't been fixed yet.

**Comment by RandellDawson** [comment]
@underlineGalaxy It does not matter anymore, because after the next release to production, there will no longer be a Guide.
