### ISSUE TITLE
Tests are printing "message" instead of anything meaningful

### ISSUE THREAD

**Issue by ArielLeslie** [FreeCodeCamp/FreeCodeCamp#3641]
Challenge [Waypoint: Create a JavaScript Slot Machine](http://www.freecodecamp.com/challenges/waypoint-create-a-javascript-slot-machine) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

![untitled](https://cloud.githubusercontent.com/assets/6234475/10346605/59bfb540-6ced-11e5-8838-511c7e71e9c4.png)

All failed test print only "message" instead of the test case.  When code is correct, the test case is printed. 

![untitled2](https://cloud.githubusercontent.com/assets/6234475/10346695/a85a0728-6ced-11e5-8e69-ee68f53f8ae1.png)

**Comment by BerkeleyTrue** [comment]
@ArielLeslie Thanks for bringing this to our attention. We recently updated how we display messages in test and this challenge may have been overlooked in the update.

**Comment by Jmz0** [comment]
I am having this same issue with chrome. Is there a correct list of the messages listed somewhere?

**Comment by bugron** [comment]
@Jmz0 before this is fixed you can find that messages [here](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/basic-javascript.json#L1130).
