### ISSUE TITLE
entire progress lost

### ISSUE THREAD

**Issue by kanuos** [freeCodeCamp/freeCodeCamp#36411]
**Describe the bug**
I had completed responsive web design certification, 50% of front end certifications, more than 80% of javascript certifications. Ever since the upgrade i have lost all my progress. As far as i can remember i had 1 certification and 3 projects completed. now all my progress is gone.

**Expected behavior**
When i log in FCC i am seeing a brand new unsolved curriculum. 

**Desktop (please complete the following information):**
 - OS: windows 8.1
 - Browser : chrome 
 - Version 75

**Comment by thecodingaviator** [comment]
Hi,

Could you provide us more info? Your username or login method should be useful, besides, did you click the reset button?

**Comment by thecodingaviator** [comment]
cc: @raisedadead

**Comment by jonathan-grah** [comment]
Thanks for reaching out. Please email `team@freecodecamp.org` for account support related issues, we only use GitHub for bugs in this case. If this ends up being an issue with the codebase, we can reopen the issue. Thanks 😃
