### ISSUE TITLE
Passed "React: Pass Props to a Stateless Functional Component" challenge with wrong solution

### ISSUE THREAD

**Issue by ming-yong** [freeCodeCamp/freeCodeCamp#36414]
**Describe your problem and how to reproduce it:**
I passed the "React: Pass Props to a Stateless Functional Component" challenge with wrong solution as below, correct answer is commented beside:
```js 
const CurrentDate = (props) => {
  return (
    <div>
      { /* change code below this line */ }
      <p>The current date is: {Date()}</p>//<p>The current date is: {props.date}</p>
      { /* change code above this line */ }
    </div>
  );
};

class Calendar extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <div>
        <h3>What date is it?</h3>
        { /* change code below this line */ }
        <CurrentDate date="date"/>//<CurrentDate date={Date()} />
        { /* change code above this line */ }
      </div>
    );
  }
};
``` 

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/react/pass-props-to-a-stateless-functional-component

**Tell us about your browser and operating system:**
* Browser Name:  Google Chrome
* Browser Version: Version 75.0.3770.100 (Official Build) (64-bit)
* Operating System: Windows 10

This is my first time opening an issue, I followed ["Creating a New Github Issue" guide on freeCodeCamp forum](https://www.freecodecamp.org/forum/t/creating-a-new-github-issue/18392). Please let me know if I am doing it wrong or there is a better approach, thank you.

**Comment by thecodingaviator** [comment]
Hi, could you provide exactly what code is failing? I'm not sure I'm able to bifurcate the incorrect code from the correct one

**Comment by jonathan-grah** [comment]
@ming-yong, this code does not appear to pass the following test for me:
"The CurrentDate component should render the value from the date prop in the p tag.".

Therefore, this must be an issue on your end. Try pressing the "Reset All Code" button and see if the tests still pass with the incorrect code.

**Comment by ming-yong** [comment]
![screenshot](https://user-images.githubusercontent.com/43736500/60927301-fb599380-a2db-11e9-9b65-6399fbf808cf.png)

Hi @thecodingaviator, above is a screenshot of my issue. No code is failing but I think the challenge accept the wrong solution.

Hi @jonathan-grah. Unfortunately, after pressing "Reset All Code", I am still able to passed the challenge.

**Comment by jonathan-grah** [comment]
@freeCodeCamp/moderators can anyone reproduce?

**Comment by ojeytonwilliams** [comment]
@ming-yong Thanks for the report!  I've been able to reproduce it, both in production and locally using the latest build, so it needs addressing.

To reproduce:

- Go to https://learn.freecodecamp.org/front-end-libraries/react/pass-props-to-a-stateless-functional-component/
- Replace the code in the editor with
```jsx
const CurrentDate = (props) => {
  return (
    <div>
      { /* change code below this line */ }
      <p>The current date is: {Date()}</p>
      { /* change code above this line */ }
    </div>
  );
};

class Calendar extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <div>
        <h3>What date is it?</h3>
        { /* change code below this line */ }
        <CurrentDate date="date"/>
        { /* change code above this line */ }
      </div>
    );
  }
};
```
- Click 'Run the Tests'
- See that it passes

This should fail for the following reasons. Incorrect props are being passed to `CurrentDate` and `CurrentDate` ignores the props and simply renders `Date()`.

I'll have a look at the tests and try and put together a fix.

**Comment by ming-yong** [comment]
@ojeytonwilliams Thanks for the fix! Should I close this issue? Is that how it works?

**Comment by RandellDawson** [comment]
@ming-yong The issue will be closed once the PR has been reviewed by others and merged into the master branch.  You do not need to do anything else.

Thanks for catching the bug.

**Comment by ming-yong** [comment]
@RandellDawson Got it, thank you.

**Comment by raisedadead** [comment]
Hi @thecodingaviator we are reserving the release labels for crit action items.

**Comment by Paul---** [comment]
Is this issue resolved?

**Comment by Paul---** [comment]
Is this issue resolved or is there something else needed?

**Comment by RandellDawson** [comment]
@Paul--- We are waiting for a PR to be reviewed/tested/merged and then master to be release to production before you will see the issue completely resolved.

**Comment by danesh4545** [comment]
در تاریخ سه‌شنبه ۱۸ تیر ۱۳۹۸ ه‍.ش.،‏ ۹:۲۵ Ming Yong <
notifications@github.com> نوشت:

**Comment by danesh4545** [comment]
در تاریخ شنبه ۱۶ شهریور ۱۳۹۸ ه‍.ش.،‏ ۰:۵۳ danesh hajatpour <
danesh.hajatpour@gmail.com> نوشت:

**Comment by Dhruvrana8** [comment]
The Solution is :
![image](https://user-images.githubusercontent.com/64273345/126793240-e5882108-0655-4c3a-ad3a-7e8d84066d0a.png)
