### ISSUE TITLE
error (node:9549) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by JonDevOps** [freeCodeCamp/freeCodeCamp#36422]
I am receiving this error after when i run `npm run develop` to run freeCodeCamp locally.

**Comment by JonDevOps** [comment]
As long as everything is updated (my linux env and the freecodecamp fork) everything does compile successfully and i am still able to view freecodecamp challenges in the browser without anything breaking.

**Comment by RandellDawson** [comment]
It is not an error.  It is a warning.
