### ISSUE TITLE
Adding new challenges

### ISSUE THREAD

**Issue by saliha-naico** [freeCodeCamp/freeCodeCamp#36431]
Currently, the challenges are inserted to DB from 'md' files by running seed command. So if a new challenge is added in the master branch would that be an' md' file too? Or do we have to manually create one? Correct me if I am wrong. My understanding is that new courses are added to the branch and we can just pull the latest, run the seed command and get those in our local env.

**Comment by ojeytonwilliams** [comment]
Hey @saliha-naico.  If you're just wondering how to get the most up-to-date versions of all the challenges that're currently on master, then yes, just pull them down.  You can use `npm run seed:challenges` to populate the database, though that may not be necessary depending on what you're doing.

**Comment by raisedadead** [comment]
The instructions for these are available for the most part in our [Guidelines for Contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md), you can specifically [follow this guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-coding-challenges.md) and related resources on the same.
