### ISSUE TITLE
Can't progress in "basic css" course

### ISSUE THREAD

**Issue by BTDyeah** [freeCodeCamp/freeCodeCamp#36433]
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Version 75.0.3770.100

In the "Basic CSS" course under "Responsive Web Design", lections can't be passed although i did what i was asked for. I checked most of the lections and none of them work. For example, i had to dye header in red, and i did so but i got error message "Your h2 element should be red". I've got a screenshot of it, and i'm sending it too. Bug first happend here, where screeenshot also takes place https://learn.freecodecamp.org/responsive-web-design/basic-css/change-the-color-of-text Here's a screenshot 
![Screenshot_13](https://user-images.githubusercontent.com/36602321/60986180-2cb77b00-a33f-11e9-9c16-6128471dd99d.png)

**Comment by fcrezza** [comment]
Hi @BTDyeah, have you tried to refresh the page?

**Comment by BTDyeah** [comment]
Hi @fcrezza, yes i did try to and it doesn't work. The only thing i ddi not try is opening the website in other browser, hope that solves the problem.

**Comment by BTDyeah** [comment]
Solved, all i did was changed browsers and now it finally works, back to the work. Thanks!
