### ISSUE TITLE
Removal of all external code links from the Guide

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#36432]
Since people can delete their pens/sessions etc. from `codepen.io`, `jsbin` and `repl.it`, rendering links unusable for any user to the guide.

I believe all such links should be removed and a note added in the guide for guide articles that users are requested to not use such links anymore

Refer: #35479

**Comment by RandellDawson** [comment]
I think this can be closed, since the guide is no longer in the repo.

@raisedadead Should we attempt to remove guide links on Discourse like @thecodingaviator suggests?

**Comment by raisedadead** [comment]
Yes, the should be removed.

**Comment by raisedadead** [comment]
> I think this can be closed, since the guide is no longer in the repo.

Guide is still relevant and will be available on the forum. All issues related to guide maybe logged on this repo on a case to case basis.

**Comment by raisedadead** [comment]
@RandellDawson did we get around to sanitizing the hint articles with the script? If yes, this can now be closed.

**Comment by RandellDawson** [comment]
Yes, this was completed before porting over to forum.
