### ISSUE TITLE
Broken Test "Basic Node and Express - Chain Middleware to Create a Time Server"

### ISSUE THREAD

**Issue by Deadmano** [freeCodeCamp/freeCodeCamp#36446]
I'm trying to pass the test with the following solution:

```
app.get('/now', function(req, res, next) {
  req.time = new Date().toString();
  next();
}, function(req, res) {
  return res.json({'time': req.time});
})
```

However neither of the tests are passing. What I find strange is that, in the console, it appears the test is trying to access `/now/_api/chain-middleware-time` and when I use that as the path, instead of simply `/now` as the requirement dictates, I actually end up passing the `The /now endpoint should return a time that is +/- 20 secs from now` requirement.

**Comment by Deadmano** [comment]
I'm closing this issue as the reason the test was failing was due to the fact that I had appended `/now` to my project's live page. Technically that should still work, but I see the reasoning behind that.

**Comment by mandakini-p** [comment]
i could not find the solution in repl.it in this myApp.js is completly blank except first 2 lines

**Comment by Sky020** [comment]
@mandakini-p I recommend opening a topic on the [forum](https://forum.freecodecamp.org), if you are having issues with your code.

**Comment by admrush** [comment]
If your certain code is correct but still getting error the solutions is to set your timezone and time to automatic in your PC settings.
See more at https://enddesign.medium.com/a-problem-you-might-have-while-doing-the-chain-middleware-to-create-a-time-server-challenge-from-44027ca483b9
