### ISSUE TITLE
newest safari does not open new tab in commit

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#3644]
Seems like the newest Safari on `El Capitan` does not open the new tab to the donate page when you click on commit button.

My theory: We redirect the page and open a new tab, Safari could be redirecting the page and canceling all other effects.

We need two things:

1. Someone on OSX El Capitan with Safari 9 to verify that the donate page does not open a new tab.
2. Someone to take the time and debug the situation.

Help appreciated as I have not yet moved to newest OSX to debug myself.

**Comment by ltegman** [comment]
I am unable to repro this using El Capitan and Safari 9. Clicking on the commit link both redirected the current page and opened a new tab to the donation page for the organization.

**Comment by BerkeleyTrue** [comment]
Thanks @ltegman

**Comment by QuincyLarson** [comment]
@CodeNonprofit is also reporting this issue. We may want to do something like this: http://stackoverflow.com/questions/9514698/bypass-popup-blocker-on-window-open-when-jquery-event-preventdefault-is-set

Or make the committing two steps (disable the commit button until they've clicked the "open donate page" button.

**Comment by BerkeleyTrue** [comment]
I'm waiting to see a second confirmation that this is effecting someone before we do anything to change functionality.

**Comment by QuincyLarson** [comment]
We resolved this earlier with our UI change, so I'm closing this issue.
