### ISSUE TITLE
Broken Test For "MongoDB and Mongoose - Create Many Records with model.create()"

### ISSUE THREAD

**Issue by Deadmano** [freeCodeCamp/freeCodeCamp#36447]
The following code produces a `Timeout has occurred` message in the freeCodeCamp console, yet no errors are shown on the Glitch console, and the data does get saved to the MongoDB Atlas.

```
const { Schema } = mongoose;

const personSchema = new Schema({
  name: String,
  age: Number,
  favoriteFoods: [String],
});

const Person = mongoose.model('Person', personSchema);

const createManyPeople = (done) => {
  console.log('Done:', done);
  const arrayOfPeople = [
    { name: 'Meeva', age: 30, favoriteFoods: ['Fettuccine Alfredo', 'Sushi', 'Quiche'] },
    { name: 'Leonardo', age: 44, favoriteFoods: ['Pasta', 'Cheeseburgers', 'French Fries'] },
  ];
  Person.create(arrayOfPeople, (err, data) => {
    if (err) return done[err];
    return done[null, data];
  });
};
```

Furthermore, the Glitch console reports the following when I have the console log logging `done` enabled and the freeCodeCamp `I've completed this challenge` button is pressed:

```
OPTIONS
POST
Done: [ { name: 'John', age: 24, favoriteFoods: [ 'pizza', 'salad' ] },
  { name: 'Mary', age: 21, favoriteFoods: [ 'onions', 'chicken' ] } ]
```

**Comment by Deadmano** [comment]
So it turns out that there was confusion between the previous lesson, and the current one. In the previous one we had to specifically create a person and pass in the values as an object, but in this lesson we had to utilise the `arrayOfPeople` argument.

Updating my function to the following solved the issue and passed the test:
```
const createManyPeople = (arrayOfPeople, done) => {
  Person.create(arrayOfPeople, (err, data) => {
    if (err) return done(err);
    return done(null, data);
  });
};
```

Leaving this open so that a decision can be made on if there needs to be an update to the wording perhaps?

**Comment by jonathan-grah** [comment]
Hi @Deadmano, could you provide a glitch link? Thanks 😄

**Comment by Deadmano** [comment]
Hey @jonathan-grah! While I'm not sure if the link will still be useful, as I had to use another method to pass the test, [here it is](https://glitch.com/edit/#!/remix/alike-snap) in any event.

**Comment by jonathan-grah** [comment]
@Deadmano, I agree the wording could be better on this challenge, as it may not be obvious due to the previous challenge asking you to create an object by yourself.
