### ISSUE TITLE
missing token error  when we try to call login api

### ISSUE THREAD

**Issue by saliha-naico** [freeCodeCamp/freeCodeCamp#36464]
When we try to do passport js authentication to login to freecodecamp , we are not able to do any api calls because of error: accesstoken is required, how can we set token without login . Is this something related to the loopback or passport js. Can you help?

**Comment by raisedadead** [comment]
What are you trying to achieve? Explain detailed steps on how and where are you getting this? The more context you give us the better.

If this is just an general query about freeCodeCamp's codebase and the stack then, [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) or the [Forum](https://www.freecodecamp.org/forum) is a better place to ask question than this issue tracker.
