### ISSUE TITLE
Create NGINX mapping to handle subdomain links.

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#36468]
`https://learn.freecodecamp.org/<challenge>` should map to `https://www.freecodecamp.org/learn/<challenge>`

`https://guide.freecodecamp.org/<article>` should map to `https://www.freecodecamp.org/guide/<article>`

`https://sponsors.freecodecamp.org/<article>` should map to `https://www.freecodecamp.org/sponsors/<article>`

**Comment by iwhiz** [comment]
Hello, I am interested in solving this issue. What is the procedure to become part of this organization?

**Comment by raisedadead** [comment]
I am going to split this up into smaller tasks
