### ISSUE TITLE
Basic Javascript: Assignment with a Returned Value

### ISSUE THREAD

**Issue by talleman21** [freeCodeCamp/freeCodeCamp#36463]
**Describe your problem and how to reproduce it:**
Solution of
 ``` processed = processArg(7)```
fails the second test, while
```processed = processArg(7);```
passes.

The semicolon at the end should be optional. 

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/assignment-with-a-returned-value/

**Tell us about your browser and operating system:**
* Browser Name:  Chrome, IE11, Edge
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/29664299/61418069-23ce2880-a8ae-11e9-8770-7b8473c0a26b.png)

**Comment by ojeytonwilliams** [comment]
Thanks for the report!  I've verified this is still the case on master.

We don't need to be that restrictive, both solutions are valid JavaScript.

**Comment by ashr81** [comment]
@ojeytonwilliams  can I pick this issue and fix?

**Comment by ojeytonwilliams** [comment]
@ashr81 sure, this was a good issue to get started with.
