### ISSUE TITLE
Entire progress lost after logging in with GitHub account

### ISSUE THREAD

**Issue by bmandl** [freeCodeCamp/freeCodeCamp#36476]
Hello guys,
I described my issue on freecodeCamp forum: [https://www.freecodecamp.org/forum/t/all-progress-lost-after-logging-in-with-github-instead-of-facebook/296963/8](url)
So, I had a account, connected to Facebook, but oneday I logged in with GitHub (added account). From then on, whether I log in with Facebook or with GitHub or email, I don't see my progress and certifications. Can someone fix this?

**Comment by jonathan-grah** [comment]
Thanks for reaching out. Please email `team@freecodecamp.org` for account support related issues, we only use GitHub for bugs in this case. If this ends up being an issue with the codebase, we can reopen the issue. Thanks 😃
