### ISSUE TITLE
New welcome page

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#36479]
Mockup and proposal:

- [ ] Create and share the copy of the new proposed welcome page. ~ @QuincyLarson 

Implementation:

- [ ] Todo: Add stories and implement... @ahmadabdolsaheb

**Comment by QuincyLarson** [comment]
We may be able to make the landing page and the welcome page the same and just react differently depending on whether people are auth'ed in.

**Comment by ahmadabdolsaheb** [comment]
> We may be able to make the landing page and the welcome page the same and just react differently depending on whether people are auth'ed in.

@QuincyLarson, That sounds like a plan. I can get started on that as soon as I have the final mockup.
