### ISSUE TITLE
Update the color scheme to freeCodeCamp chic

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#36477]
This is a master issue to track all the color scheme changes to various parts of the platform main.

**Comment by ahmadabdolsaheb** [comment]
I will refactor #35508 and shave off the unnecessary changes to accomplish the following goals.

- [ ] introduce global color palette variables
- [ ] switch color palette variables based on redux's user>theme state
- [ ] replace current colors and backgrounds colors with variables
- [ ] remove .night classes
- [ ] add post css gatsby plugin for vendor prefixes
- [ ] remove excess css  such as layout.css
- [ ] replace font with monospace where applicable.
- [ ] adjust font color and background to establish visual hierarchy.
- [ ] make it all look good :)
