### ISSUE TITLE
issue with Ditch custom CSS for bootstrap exercise

### ISSUE THREAD

**Issue by gartha1** [freeCodeCamp/freeCodeCamp#36475]
I ran into this issue a long while back but it is described here 

https://www.freecodecamp.org/forum/t/what-am-i-meant-to-have-learn-from-completing-the-ditch-custom-css-for-bootstrap-exercise/162063

I could do the exercise seemed/seems a bit pointless to me , and I quit doing the exercises after running into that. 'cos they take time to do and I like to at least learn something.

**Comment by moT01** [comment]
I don't think there's an issue here - I would recommend that you not quit doing exercises because you don't see any value in one of them. The lesson shows how using bootstrap can be more efficient than making your own custom CSS.

**Comment by moT01** [comment]
Closing as stale.
