### ISSUE TITLE
Add search to navigation

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#36478]
Depends on the news indexing.

Update the search:

- [ ] Learn
- [ ] User Profiles
- [ ] Coderadio

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb I am satisfied with @scissorsneedfoodtoo's current search implementation, and I think it's ready to roll out site-wide. Have we added the search bar to universal navigation? If so, we can roll this out along with universal navigation.

**Comment by ahmadabdolsaheb** [comment]
@QuincyLarson, yes the search that we have on news needs to be rectified. And then it would be ready to go.

**Comment by raisedadead** [comment]
I am going to close this in favor of the universal navbar issue.
