### ISSUE TITLE
Missing guide articles on site, while they exist in the repo.

### ISSUE THREAD

**Issue by Hiyorimi** [freeCodeCamp/freeCodeCamp#36470]
[Combine Multiple Reducers](https://guide.freecodecamp.org/certifications/front-end-libraries/redux/combine-multiple-reducers) or [Use Middleware to Handle Asynchronous Actions](https://guide.freecodecamp.org/certifications/front-end-libraries/redux/use-middleware-to-handle-asynchronous-actions/) have stub articles online, but the [proper](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/certifications/front-end-libraries/redux/combine-multiple-reducers/index.md) [articles](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/guide/english/certifications/front-end-libraries/redux/combine-multiple-reducers) are available in the git repo.

Same is also true for other stubs.

**Comment by raisedadead** [comment]
They will be available in our next release. We are in the process of making them as a editable wiki. We will update as we progress is made. Thanks for your patience.
