### ISSUE TITLE
Local installation fails to download the required dependencies

### ISSUE THREAD

**Issue by cjfh** [freeCodeCamp/freeCodeCamp#36472]
My ISP is CANTV Venezuela, which blocks Google and many other websites (government censorship). The "[Set up freeCodeCamp locally](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md)" guide fails on the `npm run docker:install` and `npm ci` commands when I don't use a VPN. I don't know if fixing this is possible, but you could add something in the troubleshooting section about how ISP blocks can cause the install to get stuck on the "install dependencies" step with 0 warnings telling you that it's failing to download the files it needs, and telling people affected by this to try using a VPN or proxy.

**Comment by raisedadead** [comment]
That's unfortunate, and we hope we could make the codebase and resources more accessible. A PR is welcome to add a "neutral" one liner about using a VPN for network restrictions.

**Comment by Jo-IE** [comment]
I'm on it!
