### ISSUE TITLE
[Portuguese] CONTRIBUTING.md: Broken link "artigo de exemplo sobre elementos HTML aqui"

### ISSUE THREAD

**Issue by vorgano** [freeCodeCamp/freeCodeCamp#36483]
**Describe your problem and how to reproduce it:**
Link is broken on "artigo de exemplo sobre elementos HTML aqui".

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blame/61071b8afc39f5128c29c76cf15757f4b099dbee/docs/portuguese/CONTRIBUTING.md#L60

**Tell us about your browser and operating system:**
* Browser Name: FireFox
* Browser Version: 68.0 
* Operating System: Windows 10 Professional

**Comment by gugacavalieri** [comment]
The same issue is happening for spanish translation:

https://github.com/freeCodeCamp/freeCodeCamp/blame/61071b8afc39f5128c29c76cf15757f4b099dbee/docs/spanish/CONTRIBUTING.md#L60
