### ISSUE TITLE
Broken hint link in MongoDB exercise (create many records)

### ISSUE THREAD

**Issue by ailyntang** [freeCodeCamp/freeCodeCamp#36488]
**Describe your problem and how to reproduce it:**
In the exercise ["Create Many Records with model.create()"](https://learn.freecodecamp.org/apis-and-microservices/mongodb-and-mongoose/create-many-records-with-model-create), the "get a hint" button takes you to a page with a [404 error](https://guide.freecodecamp.org/certifications/apis-and-microservices/mongodb-and-mongoose/create-many-records-with-model-create).

**Add a Link to the page with the problem:**
See above

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version:  74.0.3729.169
* Operating System: macOS Sierra v10.12.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="390" alt="Screen Shot 2019-07-23 at 8 22 46 pm" src="https://user-images.githubusercontent.com/12948766/61704717-af9cf480-ad87-11e9-8ce0-0598dea8bb36.png">

**Comment by jonathan-grah** [comment]
This issue has already been resolved on the master branch, we just haven't pushed to production yet :smile:
I'm going to close this but thank you for reporting 👍
