### ISSUE TITLE
This user needs to link GitHub with their account in order to display this certificate to the public.

### ISSUE THREAD

**Issue by nemesiscodex** [FreeCodeCamp/FreeCodeCamp#3648]
I can see my certificate at http://www.freecodecamp.com/nemesiscodex/front-end-certification when I am logged in, but If I open that link in a new incognito tab this message is displayed:
![screenshot from 2015-10-08 02 01 35](https://cloud.githubusercontent.com/assets/3976562/10358147/99a9fc60-6d60-11e5-9d85-1f780099eb7c.png)
But my github is linked
![screenshot from 2015-10-08 02 03 15](https://cloud.githubusercontent.com/assets/3976562/10358156/c4c05016-6d60-11e5-9954-8f5f50cf5c2a.png)
Am I doing something wrong or there is an extra step I need to do?

**Comment by nemesiscodex** [comment]
Also It says `View My Front End Development Certification` instead of `View nemesiscodex's Front End Development Certification` on incognito.

**Comment by BerkeleyTrue** [comment]
@nemesiscodex Are you using a different username for FCC?

**Comment by BerkeleyTrue** [comment]
Patch on the way.

**Comment by nemesiscodex** [comment]
Thank you for your hard work!

**Comment by BerkeleyTrue** [comment]
Patch Is live on beta. It should be in production shortly.
