### ISSUE TITLE
Style Guide and Contributing Guidelines for Certification Solutions

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#36497]
The challenge solution guides will be wiki-like, but here are some things that we need to address while do the move:

Main Actions:
- [x] Copy over the updated guide solution articles.
   - [x] List of all Certification Guide Articles with information regarding stubs
<https://gist.github.com/RandellDawson/ec7fe71f2760e8ef92422cb776c20706>
   - [x] Consolidated Information regarding matching forum articles and Certification Guide Articles <https://gist.github.com/RandellDawson/7ef87fbb9dd64001705523fc75477217>
   - [x] Format and cleanup the solution articles:
      - [x] 67 articles are already on forum and need manual updates to the content and evaluation on the slugs. 
      - [x] 222 articles are already on forum. The need update to the content as they are from the master guide. (Todo: Automate, update?) 
      - [x] 400+ need creation from the master guide, which have content. (Todo: Automate, update?)
	  - [x] Rest ~700+ are just stubs, which we will have a default template to use. (Todo: Automate, update?)
- [x] We will need guidelines to report errors. (Todo: Where? How?)
- [x] We will need guidelines to follow and update solutions if needed after they are reported.
- [x] We also need a template to follow and add solutions to the stubs.
- [x] We need to make sure the updates to the guide do not break the slug. We are using topic ids which does not break the slug.

DevOps:
- [x] We need to turn off commenting on the main solution post itself. We have restricted comments to level3 users.
- [x] We need to lock the solution edition to certain user level, to maintain consistency. Resolved on PR #36842.

**Comment by RandellDawson** [comment]
@raisedadead I created PR #36501 which takes care of the reformatting of all the English certification folder guide articles.

I have also created the following gists which contain data we can use during the porting over articles to the forum.

[List of all Certification Guide Articles with information regarding stubs](https://gist.github.com/RandellDawson/ec7fe71f2760e8ef92422cb776c20706)

[Consolidated Information regarding matching forum articles and Certification Guide Articles](https://gist.github.com/RandellDawson/7ef87fbb9dd64001705523fc75477217)
