### ISSUE TITLE
Broken hint link in MongoDB lesson (use model.findById)

### ISSUE THREAD

**Issue by ailyntang** [freeCodeCamp/freeCodeCamp#36495]
**Describe your problem and how to reproduce it:**
In the exercise "Use model.findById() to search your database", the "get a hint" button takes you to a page with a 404 error.

**Add a Link to the page with the problem:**
*[Lesson link](https://learn.freecodecamp.org/apis-and-microservices/mongodb-and-mongoose/use-model-findbyid-to-search-your-database-by-id)
* [Hint page with 404 error](https://guide.freecodecamp.org/certifications/apis-and-microservices/mongodb-and-mongoose/use-model-findbyid-to-search-your-database-by-id)

**Tell us about your browser and operating system:**
- Browser Name: Chrome
- Browser Version: 74.0.3729.169
- Operating System: macOS Sierra v10.12.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="390" alt="Screen Shot 2019-07-23 at 8 22 46 pm" src="https://user-images.githubusercontent.com/12948766/61710927-28a34880-ad96-11e9-98e7-b16859eb5157.png">

**Comment by RandellDawson** [comment]
This issue has already been resolved on the master branch, but has not been deployed to production, so I am closing this issue.

Thank you.
