### ISSUE TITLE
Add link to coderadio in footer or somewhere?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36506]
Looks like there been some work to get code radio up and running on our own server, should we put a link to it somewhere on the main page? Probably the footer?

**Comment by raisedadead** [comment]
It's going to be in the nav actually. We are going to be doing that once we figure out some of the scaling and stability related stuff with coderadio. There is tons of work pending. Also we will have it as a page in the main Gatsby app.

Stay tuned!
