### ISSUE TITLE
Markdownlint integration with VS Code

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#36513]
As we've got some custom Markdownlint rules, it would be nice to be able to see those rules applied to challenge markdown as we work on it.  Do we want to provide support for this (create a VS Code workspace, basically)?

**Comment by jonathan-grah** [comment]
@ojeytonwilliams, do you mean a plugin for vs code?

**Comment by ojeytonwilliams** [comment]
@jonathan-grah well, Markdownlint has a VSCode extension which highlights parts of your markdown break linting rules.  

What I'm proposing is we configure VSCode workspace settings (and add that to the repo), so that anyone who uses that extension will have the custom linting rules applied correctly.

**Comment by ojeytonwilliams** [comment]
Since we're moving to mdx, this will no longer be needed.
