### ISSUE TITLE
Lost everything last night version 3

### ISSUE THREAD

**Issue by anthonygallina1** [FreeCodeCamp/FreeCodeCamp#3652]
I lost most of my work last night when there were problems on the server. I think this is the 4th time this has happened with my account. My points number reflects over 300 while my map does not.
I have been working at this for close to a year, if not over a year.
And the issue was closed even though my map is not restored to where it should be.

Lost most of my work last night #3629

Help please

**Comment by bugron** [comment]
@anthonygallina1 thanks for posting this issue!
Please, do not duplicate your issues. We are aware of this issue, as @QuincyLarson said they will manually fix this. Continue further discussion in https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3630. Also closing https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3651.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
