### ISSUE TITLE
Audit before master goes live

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#36535]
Following on from the discussion in https://github.com/freeCodeCamp/freeCodeCamp/pull/36522 this is just a reminder that `npm audit` needs running on all the packages (api-server, client etc.) before master goes live.

**Comment by QuincyLarson** [comment]
We are now live and there wasn't any more detail here, so I'm going to go ahead and close this issue.

**Comment by gugacavalieri** [comment]
Hey guys, I just did a `npm install` and I think we should take a look at this issue again.

![image](https://user-images.githubusercontent.com/4624484/70486433-94314c80-1ad0-11ea-8d21-d5bbafd3baf9.png)

What do you guys think?


I can help if you want :smile:

**Comment by ojeytonwilliams** [comment]
Anything that's dev only (which those seem to be) is not too worrying.  If there are production packages with security problems, then they usually need addressing, though.

The ones you've shown shouldn't be a problem, but updating and fixing things is a good idea in general, so please do.

By the way, if you do find any security issues please don't discuss it here. Please email `security@freecodecamp.org` instead.

**Comment by moT01** [comment]
Do we still want to keep this open @ojeytonwilliams? Probably safe to close I think.

**Comment by raisedadead** [comment]
I would hang on to this. I have a upcoming PR #38241 which should resolve most things.
