### ISSUE TITLE
Bonfire: Seek and Destroy Challenge is undone. Output is exact.

### ISSUE THREAD

**Issue by mShreyasKumar** [FreeCodeCamp/FreeCodeCamp#3653]
Challenge [Bonfire: Seek and Destroy](http://www.freecodecamp.com/challenges/bonfire-seek-and-destroy#?solution=function%20destroyer(arr)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0A%20%20%20var%20first%20%3D%20arr%3B%0A%20%20var%20filt%20%3D%20%5B%5D%3B%0A%20%20for(var%20i%3D1%3B%20i%3C%20arguments.length-1%3B%20i%2B%2B)%20%7B%0A%20%20%20%20filt.push(arguments%5Bi%5D)%3B%0A%20%20%7D%0A%20%20var%20arrnew%20%3D%20%5B%5D%3B%0A%20%20%2F%2Fconsole.log(filt)%3B%0A%20%20first%20%3D%20first.filter(function%20(val)%20%7B%0A%20%20%20%20var%20flg%20%3D%200%3B%0A%20%20%20%20for(var%20j%3D0%3B%20j%3Cfilt.length%3B%20j%2B%2B)%20%7B%0A%20%20%20%20%20%20if%20(val%20%3D%3D%20filt%5Bj%5D)%20%7B%0A%20%20%20%20%20%20%20%20flg%20%3D%201%3B%0A%20%20%20%20%20%20%20%20break%3B%20%7D%0A%20%20%20%20%20%20else%20%0A%20%20%20%20%20%20%20%20flg%20%3D%200%3B%0A%20%20%20%20%7D%0A%20%20%20%20if%20(flg%20%3D%3D%200)%20%7B%0A%20%20%20%20%20%20arrnew.push(val)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%2F%2Freturn%20val%3B%0A%20%20%7D)%3B%0A%20%20console.log(arrnew)%3B%0A%20%20return%20arrnew%3B%0A%20%20%0A%7D%0A%0Adestroyer(%5B1%2C%202%2C%203%2C%201%2C%202%2C%203%5D%2C%202%2C%203%2C%20%22%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
function destroyer(arr) {
  // Remove all the values
   var first = arr;
  var filt = [];
  for(var i=1; i< arguments.length-1; i++) {
    filt.push(arguments[i]);
  }
  var arrnew = [];
  //console.log(filt);
  first = first.filter(function (val) {
    var flg = 0;
    for(var j=0; j<filt.length; j++) {
      if (val == filt[j]) {
        flg = 1;
        break; }
      else 
        flg = 0;
    }
    if (flg == 0) {
      arrnew.push(val);
      }
    //return val;
  });
  console.log(arrnew);
  return arrnew;
  
}

destroyer([1, 2, 3, 1, 2, 3], 2, 3, "");

```

**Comment by jlslew** [comment]
Your tests are failing because your filt array is missing the last parameter.  For instance, last test is printing `["hamburger", 53]` in the console.

**Comment by mShreyasKumar** [comment]
Hi Jlslew, I tested all the test cases in both output window and console.
Here it it showing as "Hamburger" only

**Comment by mShreyasKumar** [comment]
![error](https://cloud.githubusercontent.com/assets/15031868/10366855/c3ae450e-6dea-11e5-9700-dd9c8ba9ce21.png)

**Comment by ltegman** [comment]
@jlslew is right. Your loop that grabs the list of arguments will always miss the last one. The reason it looks like it works when you test it is because you're including an extra argument of `""` at the end which makes that be the argument that gets cut off. The FCC test cases do not include this extra argument, which means one of the real arguments get left off. Here's what you'll see with the following input if you `console.log(filt)` after your loop that populates it.

`destroyer(["tree", "hamburger", 53], "tree", 53, "");` (your test)
filt is `["tree", 53]`

`destroyer(["tree", "hamburger", 53], "tree", 53);` (FCC test)
filt is `["tree"]`

**Comment by ahstro** [comment]
I created a PR that removes the empty string from the example function since it seems to confuse people and there's no reason for it to be there. Closing this since it's technically incorrect code though.
