### ISSUE TITLE
Name doesn't show up in Frontend certificate

### ISSUE THREAD

**Issue by mizujin** [FreeCodeCamp/FreeCodeCamp#3654]
Just cleared all the frontend section to get my certificate, but my name doesn't show up in the certificate !

certificate : http://www.freecodecamp.com/mizujin/front-end-certification

![image](https://cloud.githubusercontent.com/assets/7820886/10367671/c6f93a20-6d9f-11e5-851c-d03ab7b264c1.png)

**Comment by jlslew** [comment]
My guess is that it uses your Github name since all your other accounts have a name.  Could you try adding your name to your Github profile and see if it shows up?

**Comment by BerkeleyTrue** [comment]
Yes, you must have your name defined on Github and then update you account on Free Code Camp.

**Comment by mizujin** [comment]
Thanks guys, it worked !

**Comment by Davide1234** [comment]
I can't claim my front end developer certificate

**Comment by Bulelwa1** [comment]
I also facing the above problem I have saved my full name on GitHub but the certificate is still blank can somebody help me
verify this certification at: http://freecodecamp.com/bulelwa1/front-end-certification

**Comment by vaheed-sediqi** [comment]
same problem here
https://www.freecodecamp.org/vaheed-sediqi/front-end-certification

**Comment by cunleo** [comment]
I cant claim my front-end-certification, cant even see a link to it!!!!!
