### ISSUE TITLE
Code examples are one-line

### ISSUE THREAD

**Issue by teenjuna** [freeCodeCamp/freeCodeCamp#36556]
**My problem:**
My problem is that the code examples on some pages are one-line.

**Link to the page with the problem:**
[For example](https://www.freecodecamp.org/news/a-new-approach-to-react-component-design-2bf76a87add1/)

I encountered the issue on different pages in the past but didn't save the links.

**Browsers:**
* Browser Name: Chromium, Firefox (Linux), Google Chrome (Android)
* Browser Version: newest

**Screenshot:**
![image](https://user-images.githubusercontent.com/53595243/62347994-d85e8000-b525-11e9-8ccc-0746004628ec.png)

**Comment by RandellDawson** [comment]
Do you how the directory structure should look?

**Comment by ojeytonwilliams** [comment]
This looks like a problem with specific news article.  Maybe contact the author or discuss it [here](https://www.freecodecamp.org/forum/t/a-new-approach-to-react-component-design/286419).

**Comment by RandellDawson** [comment]
I have corrected that specific article to match the original post on Med.  This is a known issue.  Multi-line code sections were not properly ported over to Ghost.  I have been working on a way to fix them with a script.  The one thing which we can not fix is the missing embedded GitHub gists.  None of those were ported over, so we are depending on the original authors to add those gists as embeded HTML sections.

**Comment by RandellDawson** [comment]
I have started working on something that will at least fix the JavaScript/JSX/HTML/CSS/ code sections, but for others, it might have to be manual changes.

**Comment by moT01** [comment]
Is this still an issue @RandellDawson? I wonder how many articles, if any, still have this problem.

**Comment by RandellDawson** [comment]
Does not appear to be a problem now.
