### ISSUE TITLE
Spread operator only accepts array literal

### ISSUE THREAD

**Issue by enrider** [freeCodeCamp/freeCodeCamp#36564]
**Describe your problem and how to reproduce it:**
In [this lesson on the spread operator](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-the-spread-operator-to-evaluate-arrays-in-place/), I ran into the following issue.

This particular lesson has three tests:
1. arr2 is correct copy of arr1.
2. ... spread operator was used to duplicate arr1.
3. arr2 remains unchanged when arr1 is changed.

When I change the default text (`arr2 = []; // change this line`) to my solution of choice (`arr2 = Array(...arr1);`) I find that tests 1 and 3 pass, while test 2 fails. But, I'm clearly using the spread operator here.

I can get test 2 to pass by using an array literal, rather than a function (e.g. `arr2 = [...arr1];`), however, both solutions should be valid, as they both fulfill all requirements for this lesson.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-the-spread-operator-to-evaluate-arrays-in-place/

**Comment by enrider** [comment]
PR submitted for review: https://github.com/freeCodeCamp/freeCodeCamp/pull/36565

**Comment by RandellDawson** [comment]
What solution do you think should not pass and does with the current tests and/or what solution do you think passes when it should not?
