### ISSUE TITLE
unable to load profile picture?

### ISSUE THREAD

**Issue by bhavesh2699** [freeCodeCamp/freeCodeCamp#36561]
Recently i enter into code camp with my account  and i successfully logged in but it was not displaying my profile picture. When i tried t find issue in console i was getting error regarding
GET https://media.licdn.com/dms/image/C5103AQGN6p8Ku2EH2Q/profile-displayphoto-shrink_200_200/0?e=1557964800&v=beta&t=dZ0d3m_M40lmSd2iWOT1IBm3RoGdLOvAv_K-7Wau8ac 403 (Forbidden)

![Screenshot (75)](https://user-images.githubusercontent.com/41828589/62428597-f6dc9b00-b720-11e9-9e8a-eefb21d43791.png)

**Comment by raisedadead** [comment]
Thanks for reaching out, unfortunately it's the website (LinkedIn's CDN) you have the profile pic being linked from is not allowing you to hotlink the image with us. 

I recommend visiting your profile settings and update the image link to something that is more lenient like GitHub or Gravatar.

<https://avatars3.githubusercontent.com/u/41828589?s=400&v=4>
