### ISSUE TITLE
Missing hints in basic Javascript.

### ISSUE THREAD

**Issue by jaybaldha** [freeCodeCamp/freeCodeCamp#36567]
**Describe your problem and how to reproduce it:**
Missing hint in Basic javascript(Use Multiple Conditional (Ternary) Operators) problem.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-javascript/use-multiple-conditional-ternary-operators/

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 75.0.3770.142 (Official Build) (64-bit)
* Operating System: Windows 8.1
![Capture](https://user-images.githubusercontent.com/24391898/62557557-dafa0600-b894-11e9-8b3e-2e5fd84dcd17.JPG)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
Closing as non-issue, since the current Guide on the master branch (not yet deployed to production) has a solution.  The hints and solutions will be available on the forum soon.

![image](https://user-images.githubusercontent.com/5313213/62561466-229c7580-b834-11e9-99e4-277796c1112a.png)
