### ISSUE TITLE
Search results are misaligned

### ISSUE THREAD

**Issue by ColinAmos** [freeCodeCamp/freeCodeCamp#36568]
**Describe the bug**
When trying to search using the search bar on a lesson page, the search result preview list is misaligned to the point where the results cannot be read because they are so far outside the window space.

**To Reproduce**
1. Go to any lesson page (ex: https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements)
2. Click on the search bar at the top
3. Type a search term or phrase (ex: "react")

**Expected behavior**
The search results should be entirely within the window space.

**Screenshots**
![search pic 1](https://user-images.githubusercontent.com/35937916/62583161-083aba00-b87d-11e9-80fe-ac89fd8d9910.png)

**Desktop**
 - OS: Windows 10
 - Chrome (also happens on Firefox)
 - Version 75.0.3770.142

**Comment by RandellDawson** [comment]
This issue has already been fixed on the master branch.  We are just waiting for the master branch to be deployed to production.  I am closing this as fixed but waiting to be shipped.

**Comment by ColinAmos** [comment]
> This issue has already been fixed on the master branch. We are just waiting for the master branch to be deployed to production. I am closing this as fixed but waiting to be shipped.

This issue seems deserving of a hotfix to me. Regardless, what's causing the delay? It looks like this new master branch has been "waiting to be deployed" for 6+ months.

**Comment by RandellDawson** [comment]
@ColinAmos There are many new changes coming which required a complete re-engineering of the repo.  There are only 3 core developers currently and the rest of us are volunteers.  The entire search feature has been redesigned along with a lot of other functionality and look of the site.  Once launched, you will see most bugs fixed which are currently present in production.

**Comment by ColinAmos** [comment]
@RandellDawson Thanks for the response.
