### ISSUE TITLE
Negative margins isn't defined properly

### ISSUE THREAD

**Issue by siddtheone** [freeCodeCamp/freeCodeCamp#36574]
On the negative margin tutorial its written that "If you set an element's margin to a negative value, the element will grow larger." However this isn't completely correct and it depends on various factors as explained on "https://www.smashingmagazine.com/2009/07/the-definitive-guide-to-using-negative-margins/"

[Negative Margin](https://learn.freecodecamp.org/responsive-web-design/basic-css/add-a-negative-margin-to-an-element/)

Here the the tutorial is not much clear.

**Comment by RandellDawson** [comment]
@raisedadead Since this is a curriculum issue, does this need the `status: needs triage` label?

**Comment by raisedadead** [comment]
Well, I was not sure what is to be done with the issue when I was going thru the same. The OP has not suggested the changes like @ArielLeslie pointed them to on the forum thread.

I believe we can close this and await response from the OP. We could reopen if needed.
