### ISSUE TITLE
Add gitpod documentation and update config for remote

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#36572]
We need the ability to be able to launch the GitPod workspaces with the origin remote NOT pointing to the main repository, but the fork of the user instead.

If the later is not possible, then at least removing the remote, so that the user notices the remote missing while pushing.

Additional guidelines around this are also required to be documented for setting remotes in the terminal within GitPod.

Finally the best place to document this would be to move the same from the Contributing Guide and place it in the how to work on freeCodeCamp locally guide.

Some references:
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/.gitpod.yml#L15
https://www.gitpod.io/docs/44_config_start_tasks

**Comment by leodaher** [comment]
If the user launches GitPod from their fork, the origin remote points to the fork, doesn't it?

**Comment by raisedadead** [comment]
> If the user launches GitPod from their fork, the origin remote points to the fork, doesn't it?

It does. We are looking to solve the edge case where maintainers on this repository have write access to the upstream (this repo), and the forget about the push rights when working on a instance that the launched from the main repo.

**Comment by leodaher** [comment]
Oh, I get it now! Can I work on a PR for this issue? 

I'm guessing we could assume the user has a fork, and try to set the remote origin to it (git does not return an error if the url does not exist).

**Comment by raisedadead** [comment]
Yup. Thanks for working on this.
