### ISSUE TITLE
Unable to pass the skewX challenge, where as completed whatever required in the module

### ISSUE THREAD

**Issue by yasarshaikh** [freeCodeCamp/freeCodeCamp#36583]
**Describe your problem and how to reproduce it:**
I have a code, which looks fine as per the instructions, however challenge testing is getting me same error each time. 
Expected:
Skew the element with the id of bottom by 24 degrees along the X-axis by using the transform property.

Applied style:
 #bottom {
    background-color: blue;
    transform : skewX(24deg); //even tried with -ve value and skewY function as well. 
  }

**Add a Link to the page with the problem:**
[Module link](https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-css-transform-property-skewx-to-skew-an-element-along-the-x-axis/)

**Tell us about your browser and operating system:**
Link: [Module link](https://learn.freecodecamp.org/responsive-web-design/applied-visual-design/use-the-css-transform-property-skewx-to-skew-an-element-along-the-x-axis/)
* Browser Name:  **Chrome**
* Browser Version:  76.0.3809.100 
* Operating System:  Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/20971327/62921454-665c2580-bdc6-11e9-9461-584f3cb04cf6.png)

**Comment by Hardik500** [comment]
The problem is in your transform code
It is `transform: skewX(24deg);`
not `transform : skewX(24deg);`
There is no space after transform.

**Comment by sid995** [comment]
There should be **NO** space between the css property and semicolon.

here it should be `transform: skewY(24deg)`
not `transform : skewY(24deg)`

**Comment by yasarshaikh** [comment]
Thanks @Hardik500 and @sid995 ! I resolved it by removing that space!
