### ISSUE TITLE
Redundant cplusplus guide articles

### ISSUE THREAD

**Issue by shreyas1599** [freeCodeCamp/freeCodeCamp#36581]
I was looking at the C++ guide articles and noticed some kind of redundancy. For instance, there are 4 articles that talk about loops. One about for-loops, one about while-loops, one about range-based-for-loops and another one about loops in general. I think it's best all of them be merged into one single article titled 'Loops'. If this was deliberately done, can someone explain why? If this was a larger topic and needed to be divided into smaller chunks it would've made sense but not here.

Link: https://github.com/freeCodeCamp/freeCodeCamp/tree/master/guide/english/cplusplus

**Comment by Erik-D-Mueller** [comment]
The link does not work for me

**Comment by RandellDawson** [comment]
I am closing this issue as we are migrating the Guide over to [our forum](https://www.freecodecamp.org/forum/c/guide) where you will be able to create/edit guide articles.  As of today, the guide no longer is apart of the repo.
