### ISSUE TITLE
Can't sign in using GitHub after changing GitHub username

### ISSUE THREAD

**Issue by mehmetseckin** [freeCodeCamp/freeCodeCamp#36588]
**Describe the bug**
Cannot access my existing account after changing my GitHub username. The platform automatically registers me as a new user.

**To Reproduce**
1. Create an account using a github account.
2. Change your username on github.
3. Try to sign in to the platform.
4. See you're being registered as a new user.

**Expected behavior**
Expected to be signed in to my old account.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 76.0.3809.100 (Official Build) (64-bit)

**Additional context**
My old GitHub username: `seckin92`
My existing profile: https://freecodecamp.org/seckin92

**Comment by moT01** [comment]
Sorry to hear about your problem @mehmetseckin - you could try changing your github name back to what it was as a temporary fix. I bet that would let you back on your original account.

**Comment by mehmetseckin** [comment]
@moT01 	Thanks for your response. I thought of that, however I'm not quite fond of the idea of changing my username to back to what it was, as that'll break a lot of links everywhere, and I'm not sure if I can keep renaming my account. 

I might be able to create a new one with the old username and try to get in my old freeCodeCamp account, but if that is possible, then I think it poses a security risk as anyone would be able to do this once someone changes their GitHub username.

**Comment by huyenltnguyen** [comment]
@mehmetseckin With issues related to accounts and data, I'd suggest sending an email to `team@freecodecamp.org` and let the team know about the issue you're experiencing. I have seen many users done that and got their accounts merged with the progress restored.

**Comment by mehmetseckin** [comment]
Thanks a lot @huyenltnguyen - the team helped me regain access to my account through e-mail, and updated my GitHub profile link etc., however I still can't sign-in using GitHub, it's registering as a new user... 

This is not required at this point so I'm happy to close this issue. Hope this helps someone.
