### ISSUE TITLE
Typo in "create grids within grids" challenge video

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#36590]
Challenge: https://learn.freecodecamp.org/responsive-web-design/css-grid/create-grids-within-grids/
Video: https://scrimba.com/c/c6N78Ap

The code is supposed to create a two-column layout but there is a typo.

Video has:
`grid-template-colums`

Should be:
`grid-template-columns`

@beaucarnes It would be nice to have the video fixed if possible.

**Comment by anubhavm55** [comment]
I would like to help but I need some more information like the download link for the video to edit it and overwrite columns on colums.

**Comment by lasjorg** [comment]
@beaucarnes Is it possible to get this video updated?

**Comment by lasjorg** [comment]
@beaucarnes this still needs to be fixed, if possible.
