### ISSUE TITLE
Keep code after submit?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36599]
When you go work on a challenge, your code will stay there if you navigate around and come back to it. But after you submit the challenge, the code gets reset. Wondering if we can or should keep that code there after the challenge gets submitted.

**Comment by RandellDawson** [comment]
I tried to recreate this problem, but can not.  When I click `Submit and got to next challenge`, I can still go back and see the code I entered.  I only tested a few challenges and I was using Chrome.

**Comment by moT01** [comment]
I must be the only person that uses firefox - yea, it doesn't happen on chrome.

**Comment by RandellDawson** [comment]
@moT01 I just tried the same thing on Firefox and can see my submitted code when going back to the challenge after clicking the `Submit and got to next challenge`.  Maybe you have a different cache setting than I do.

**Comment by ValeraS** [comment]
Code is erased after submitting if you logged in.

**Comment by RandellDawson** [comment]
@ValeraS But only if logged in?  Is this by design?

**Comment by ValeraS** [comment]
By design. But not sure it is right.

**Comment by raisedadead** [comment]
This has come up several times before, and has been clarified in the closed issues. In short yes, this is by design.
