### ISSUE TITLE
A bit too difficult 

### ISSUE THREAD

**Issue by Luomint** [FreeCodeCamp/FreeCodeCamp#3659]
Hello,

I think this task is a little unrealistic because we are being asked to reverse engineer a professionally made website with complex parallax. We are being asked to design it from scratch, but the student didn't do it himself.
Example on freecodecamp - http://codepen.io/ThiagoFerreir4/full/eNMxEp 
Original - http://codepen.io/luomint/pen/Kdgqjp 

http://freecodecamp.com/challenges/zipline-build-a-personal-portfolio-webpage

**Comment by staffman76** [comment]
I agree that this assignment is too difficult. The tutorials up to this point do not show how to complete the assignment. Asking for help should not be necessary.

**Comment by lastsumerian** [comment]
Huh? Is it's what my friend said school starts? Already?

**Comment by staffman76** [comment]
@lastsumerian What are you trying to state? Your comment isn't clear.

**Comment by lastsumerian** [comment]
Password is 9856

**Comment by staffman76** [comment]
@lastsumerian Your comment does not apply to this thread.

**Comment by castellaccilaura** [comment]
guys, i need help too...lest try to do this together...any of you started the proyect? at least in a rudimentary way (scuse my english, i'm argentinian and self-taught person)

**Comment by hawaiifornia** [comment]
I'm having a lot of difficulty with this also.  I do not have any previous experience with coding before FreeCodeCamp.  I was just barely able to complete the Tribute page.  I don't understand how I'm expected to "Build a Personal Portfolio Webpage" with an empty portfolio and only the slightest understanding of the language??
