### ISSUE TITLE
[.dev] Get a hint links not working

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36596]
Go to any [backend challenge](https://www.freecodecamp.dev/learn/information-security-and-quality-assurance/information-security-with-helmetjs/hide-potentially-dangerous-information-using-helmet.hidepoweredby)
Click the "get a hint" button

It redirects to https://www.freecodecamp.org/forum/search?q=/learn/information-security-and-quality-assurance/information-security-with-helmetjs/hide-potentially-dangerous-information-using-helmet.hidepoweredby%20in%3Atitle%20order%3Aviews

It should redirect to https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-hide-potentially-dangerous-information-using-helmet-hidepoweredby/301580

So I'm not sure if it's something with the forum search query, or the link on the challenge.

It seems to be like this on all the backend challenges, looks like it works in all the other areas.

**Comment by RandellDawson** [comment]
@raisedadead I will work on this one.

**Comment by RandellDawson** [comment]
@moT01 This issue should not be resolved.  Close if you think so.

**Comment by moT01** [comment]
Looks like it's fixed on master.

**Comment by Schawnnara** [comment]
### 

> 

- jjjjjjjjj**

1. 

**

**Comment by Schawnnara** [comment]
### hi
