### ISSUE TITLE
Boo Hoo get a hint link broken

### ISSUE THREAD

**Issue by PhilipGreene08** [freeCodeCamp/freeCodeCamp#36607]
**Describe your problem and how to reproduce it:**
Link to "using typeof" at bottom of page does not take me anywhere

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-algorithm-scripting/boo-who/

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 
* Operating System: MS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
Thank you for reporting this issue, but it actually has been resolved.  The hints/solutions will soon be on the forum and the "using typeof" link has been removed from it. 

I am closing this issue as resolved but awaiting shipping to production.
