### ISSUE TITLE
found all "Pro Bono" page still active 

### ISSUE THREAD

**Issue by Ieahleen** [freeCodeCamp/freeCodeCamp#36602]
**Describe the bug**
it is still possible to reach the page title "We will build software for your nonprofit. Pro Bono."

**To Reproduce**
Go to https://www.freecodecamp.org/Nonprofits

**Expected behavior**
seeing the page for "Open Source for Goods" projects - which i can see at this link: https://www.freecodecamp.org/nonprofits/

(sorry for the title, that was typo and can't change it)

**Comment by raisedadead** [comment]
We have deprecated this pages and in our upcoming version of freeCodeCamp we would redirect these to our main landing page.

Thanks for letting us know.
