### ISSUE TITLE
[.dev] search links to old guide article urls

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36606]
<img width="850" alt="Screen Shot 2019-08-15 at 2 19 51 PM" src="https://user-images.githubusercontent.com/20648924/63120394-d81fa500-bf67-11e9-8ba5-e57706be47d6.png">

Since all the guide articles have been moved to the forum - all the search results for guide articles are linking to 404 pages.

**Comment by RandellDawson** [comment]
@raisedadead I assume all this will clear up once the search only indexes news articles?

**Comment by raisedadead** [comment]
Yes, I am triaging this a bug, but this is essentially going to resolve by not showing up the guide results anymore.
