### ISSUE TITLE
[.dev] typo on sign in page

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36605]
go to https://www.freecodecamp.dev/
click the `sign in` button
minor typo here:

![Screen Shot 2019-08-15 at 2 14 29 PM](https://user-images.githubusercontent.com/20648924/63120121-444dd900-bf67-11e9-8bfd-7893dcd1d013.png)

**Comment by raisedadead** [comment]
Resolved. Thanks for reporting.
