### ISSUE TITLE
[.dev] Unable to change email address on settings page

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36604]
I can't change my email address on the settings page. Anyone one else want to confirm this?

**Comment by lancerutkin** [comment]
@raisedadead Happy to help on this - I poked around a bit and believe I've found the source of the bug. Also glad to point you in that direction if you prefer to handle this since you've already assigned it to yourself.

**Comment by raisedadead** [comment]
Sure, thing go for a PR if you have something ready.

**Comment by lancerutkin** [comment]
I have a WIP PR ready - cool if I open that?

**Comment by moT01** [comment]
Do it @lancerutkin, you can use draft mode if it's not ready.

**Comment by ahmadabdolsaheb** [comment]
#17193
