### ISSUE TITLE
Bonfire 'Sum of all Fibonacci Numbers' odd test case failure

### ISSUE THREAD

**Issue by koustuvsinha** [FreeCodeCamp/FreeCodeCamp#3660]
Challenge [Bonfire: Sum All Odd Fibonacci Numbers](http://freecodecamp.com/challenges/bonfire-sum-all-odd-fibonacci-numbers#?solution=function%20sumFibs(num)%20%7B%0A%20%20var%20arr%20%3D%20fib(num)%0A%20%20var%20s%20%3D%200%0A%20%20arr.forEach(function(n)%20%7B%0A%20%20%20%20if(n%20%25%202%20!%3D%3D%200)%20%7B%0A%20%20%20%20%20%20s%20%3D%20s%20%2B%20n%0A%20%20%20%20%7D%0A%20%20%7D)%0A%20%20return%20s%0A%7D%0A%0Afunction%20fib(num)%20%7B%0A%20%20if(!num)%20return%20%5B%5D%0A%20%20if(num%20%3D%3D%201)%20return%201%0A%20%20var%20arr%20%3D%20%5B1%5D%0A%20%20var%20c%20%3D%200%0A%20%20var%20l%20%3D%20arr%5Barr.length%20-%201%5D%0A%20%20while(l%2Bc%20%3C%3D%20num)%20%7B%0A%20%20%20%20arr.push(l%2Bc)%0A%20%20%20%20c%20%3D%20l%0A%20%20%20%20l%20%3D%20arr%5Barr.length%20-%201%5D%0A%20%20%7D%0A%20%20return%20arr%0A%7D%0A%0AsumFibs(4)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36</code>.

My code passes all test cases except one, the first `sumFibs() should return a number` case. Apparently, the test runner cannot identify even 0 as a number where my solution returns 0 on empty params. Please review

My code:
```
function sumFibs(num) {
  var arr = fib(num)
  var s = 0
  arr.forEach(function(n) {
    if(n % 2 !== 0) {
      s = s + n
    }
  })
  return s
}

function fib(num) {
  if(!num) return []
  if(num == 1) return 1
  var arr = [1]
  var c = 0
  var l = arr[arr.length - 1]
  while(l+c <= num) {
    arr.push(l+c)
    c = l
    l = arr[arr.length - 1]
  }
  return arr
}

sumFibs(4);

```

**Comment by ltegman** [comment]
The first test case that you are failing runs the code `sumFibs(1)`. If you run your solution with 1 as the input you will see that you get an error that reads `TypeError: arr.forEach is not a function` because `arr` is the result of fib(1), which is the number `1` and not an array.

**Comment by koustuvsinha** [comment]
thanks @ltegman that solved the issue. however, i feel the test case was not designed right. When you are expecting `sumFibs()` to return a number, why the test runner runs `sumFibs(1)` in the background?

**Comment by ltegman** [comment]
The test runner has to pass some value into the function to see if the output is a number, but I do agree that the test case should explicitly state what code (including parameter) it ran when it fails. If no one else does I'll put in a PR to make this more clear later today.

**Comment by koustuvsinha** [comment]
cool :+1:

**Comment by koouty** [comment]
For me too there is a failure.
I initiated by a function to get the fibonacci numbers, I make this with a short recursion. In repl.it it is perfectly accepted and give output after few miliseconds, But in the freeCodeCamp console the code blocks the console. Here is my code. If someone understand what is the problem I'll very grateful to get an explanation
```
function sumFibs(num) {
  if (num === 1 || num === 0) {return 1;}
  else {return sumFibs(num - 2) + sumFibs(num - 1);}
}
sumFibs(2);
```

**Comment by ltegman** [comment]
@koouty I know recursion is a popular way to solve the fibonacci problem, but it's an incredible inefficient solution in Javascript. Function calls in javascript are VERY slow, so once you start doing test cases like FCC has (1000+) your recursive solution is orders of magnitude slower than using a while loop. Check out what happens when you toss your solution into a repl with some of the large number test cases and you'll see what I'm talking about.

You might be able to make the resursive solution work by implementing memoization, but you'd just be putting a bandage over the issue and it still probably won't be fast enough for the larger test cases.

**Comment by koouty** [comment]
@ltegman 
Yes!
right in repl.it up to 40 it's good but not 50.
I was innocently believing that all the interpreted languages make it with the same velocity, for example, python is slow but makes it reasonabily.
Thank's again for the knowledge.
