### ISSUE TITLE
[.dev] donate/support modal shows up a lot

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36619]
I believe you need to be signed in
Go to a challenge
Complete and submit challenges until the donate/support our non profit prompt shows up
Close it
Then use the back and fourth buttons in the challenge description area
The prompt will pop up on every move to another challenge

It's a little annoying.

Additionally, the donate prompt doesn't show up at all if you aren't signed in.

**Comment by lancerutkin** [comment]
I see someone's been assigned recently, but the help wanted label was still attached. I think I've found the source causing this behavior. Ultimately though, it's a business decision as to how frequently freeCodeCamp wants that modal popping.

Happy to take this on or lend a hand to @ahmadabdolsaheb if he'd like.

**Comment by raisedadead** [comment]
Hi @lancerutkin thanks for lending a hand, this being a critical bug, was assigned to staff. But we would love the help since you already have done the investigation.

Please open a PR if you have something ready. 

Thanks.

**Comment by raisedadead** [comment]
> how frequently freeCodeCamp wants that modal popping.

Here is the logic:

1. Do not show the modal to a user who is NOT signed in. We are not saving their streak or giving them certificates. So we do not need to show them the modal and annoy them.

2. Do not show the modal to a user who signed up and has <= 10 challenge completions.

3. Show the modal a total of 1 time per session (each browser tab is a separate session).

**Comment by raisedadead** [comment]
Eventually we would move to a different approach and may get rid of the modal completely. But for now the above comment is what we have on production and should be continued.

**Comment by vkWeb** [comment]
@raisedadead I think we should NOT at all display the donate modal. It feels as if we need to donate $5/month to continue working on challenges. We are still fixing a lot of bugs for the next release. So, I think we should take a different approach and fix this right now. We should not defer this.

We can use the modal of the settings page to ask campers to donate to the community:

![Screenshot (3)](https://user-images.githubusercontent.com/26724128/63223675-3dc59880-c1d7-11e9-94e2-ea27b051b1e2.png)

We should limit the display to about two to three times a week. Also, it would be great if we could make the donate text a bit dynamic like we have in Quincy's weekly email. I hope you got my point.

**Comment by raisedadead** [comment]
Thanks for your feedback. 

However, as of now our stand on the modal is same as current production. Please feel free to share further feedback on our forum.

@lancerutkin if you are still interested in the issue, we need to fix the parity between our production and master. This https://github.com/freeCodeCamp/freeCodeCamp/issues/36619#issuecomment-522309624 has the logic.

**Comment by lancerutkin** [comment]
@raisedadead, yes, I’ll get working on this and submit a PR when I’m done.
I’ll let you know if I have any questions.
