### ISSUE TITLE
Comment email notifications for Developer News authors

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#36611]
Currently authors are unaware of comment threads about their article unless they actively check.

The best way for notify authors of comments is by sending them an email whenever they get a new comment.

User Story: As an author, whenever someone comments on my article, I get an email with a body of that comment, and a link to the thread so I can reply to it.

**Comment by RandellDawson** [comment]
@raisedadead Would you want to implement this via the Discourse API using a webhook?  If a forum user is "watching a thread" (based on their forum settings for the topic), then they would automatically get an email anyway.  However, the author may not even have a forum account that we could set the "watching" status for the comments.  

I have not studied how you have linked the comments back to the news article, but depending on how you set up that link, we could maybe do something.

**Comment by colbyfayock** [comment]
I can attest that I wasn't automatically set as a watcher for comments on one of my posts until I updated that manually. I _thought_ that we were supposed to create an author username that was the same as the forum account but maybe I'm making that up.

At any rate, I think if there isn't a known association, maybe a minimum solution is to query the author's email against the forum users and if you find a match, set up their account as a watcher?

**Comment by colbyfayock** [comment]
@RandellDawson if Ghost supports it, you may be able to have a user-defined field within Ghost that links their forum author username. I guess the difference is opt-in to comment notifications or providing something that will work right away (for most). An argument to the latter is people may not know to look for it in Ghost settings unless some sort of notification is made that let's people know that option is available. Either way, ideally the author can find out easily so they have an opportunity to respond in the first place.

**Comment by RandellDawson** [comment]
@colbyfayock Yeah, we'll have to make it clear where a user must go to stop the notifications.  That is the issue with having Ghost for the main part and using the forum for the comments.  Each system has to be connected for features like "opt-out" to work smoothly.  If we add the "opt-out" to Ghost, ultimately has to communicate to Discourse to turn off the Watching status for the thread and maybe even having to set the status to `Muted`, if the OP does not want to receive any notifications for the comments thread.  Once we here back from the core team about the direction, I can attempt to create a solution.

**Comment by raisedadead** [comment]
@QuincyLarson 

Here are two options:

**Option A:**

- This involves developing an independent API of its own.
- Discourse API should be delivering a webhook for all comments (not limited to news), depending on the config this can be filtered (either in discourse or the api), to react to the webhook.
- The API would then query the author from the Ghost instance using the Ghost admin API.
- API would audit for the validity of the comment, (should and email be sent out? Author commented themselves?).
- How recently was a comment made, is the thread too heated? Are we filtering spamming?
- How do the author opt-in/opt-out? We need yet another lightweight DB!
- Essentially this is quickly going to blow up into a managed commenting system of its own.

**Option B:**

- While onboarding the authors, our staff should recommend them to sign up for the forum.
- After publishing an article, the authors simply visit the comments page of the article, following the comment widget on the page.
- Click the notification type button to get all the flexibility they need about comments.

![image](https://user-images.githubusercontent.com/1884376/63209890-4f8a3b80-c104-11e9-8553-60accad65306.png)

IMHO the later option solves every user story / use case and edge case about commenting, thanks to discourse.

**Comment by colbyfayock** [comment]
@raisedadead i think the hope is to be able to automate something like Option B

what is the process between when a post gets published on Ghost and subsequently posted in the forum? At that time, could you query for the author based on their Ghost account email and once posted, mark the account found via email as watching the thread? This solves all concerns if possible, the only issue is whether or not there's a matching email, which i feel like is a fair compromise for an author. this can also be documented and communicated to authors.

**Comment by raisedadead** [comment]
> At that time, could you query for the author based on their Ghost account email and once posted, mark the account found via email as watching the thread?

This has to be opt-in. Else it becomes a privacy concern. Meaning we need to build the logic/views where authors opt-in.

The current Ghost and the Discourse instances are being used out of the box. This means we do not control the source code (server side). Nor do we control the admin views.

We could fork and do our thing, but again that's more devops overhead that I would avoid for the availability of a simpler workflow.

**Comment by RandellDawson** [comment]
B sounds like it could work and would be a simpler solution.  The author just needs to remember to go to the forum to opt out of the receiving the notifications.

**Comment by colbyfayock** [comment]
B is available today

**Comment by QuincyLarson** [comment]
@raisedadead The reality is authors are busy and even our (already brutally simplified) onboarding process can be confusing to some.

We don't want to add any more steps. If anything, we want to automate these tasks.

Instead of emailing, we just need a bot that tweets to authors when someone comments on their posts. Call it the Developer News Comment bot.

- As an author, when setting up my profile, I include my Twitter handle so I will be @-mentioned when people tweet my article.
- As an author, I want to receive notifications when someone comments on my stories so I can read them and reply to them.

All the information we need is already public:
- New posts in the News category on Discourse
- The author's Twitter handle (from their Developer News article).

A bot could watch the /news category for new posts, then follow the linked posts back to Developer News to get the author's twitter.

Then it could compose a simple tweet like:
"@[username] there is a new comment on your article: [comment thread URL]."

A volunteer contributor from the freeCodeCamp community could build this entirely themselves without needing any API keys or anything.

**Comment by raisedadead** [comment]
Please note (in addition to all the good cases above):

- [ ] The application should give its subscribers a clear way to opt out.
- [ ] The application should not scarpe the comments from the application like news and forum aggressively (or make calls that will affect the stability). 
- [ ] The application should also have an ability to remove a tweet (if found as spam / malicious, .etc)
