### ISSUE TITLE
News Post Comments Visibility

### ISSUE THREAD

**Issue by colbyfayock** [freeCodeCamp/freeCodeCamp#36612]
I think it's great that the comments are hidden on load, as it avoids contributing to the initial page load. I do however think it's good to have them visible, as doing so I believe would help to encourage others to participate.

One idea for doing so would be to lazy load it in, triggered by the scroll position. Once a visitor gets, say, 75% through the article, the comments section could be loaded in.

Gives more visibility to the comments without sacrificing page load aside from the event listener.

**Comment by raisedadead** [comment]
This is something we will have once we have had figured out the infrastructural needs for our current news platform.

At the minute, any automated solution is going to put extreme loads on the platform for not much gain. I am making a guess that not much of the users are actually interested in commenting on the articles anyways (I know that's the point of this thread), the passive browse only traffic is way higher.

We could potentially look into other lightweight signals insead. Likes? Trending? View Counts? These are passive interaction builders as well.

Making this essentially an infrastructural issue. We would want to scale up (considering that our resources are limited) on the platform's backends before we encourage more engagement.

**Comment by colbyfayock** [comment]
i think the fact that the comments are kind of buried behind the link helps that traffic trend, though there would still always be a much higher percentage of passive browse. it almost appears as if there are no comments given it's just a button or not a comment section if you breeze right through it and not realize it's there. 

to be clear, what infrastructure are you concerned about? The reason i ask, is you allude to the concern being on the Ghost platform infrastructure, where the additional load of the solution im proposing would only be on the Forum embed, as it's all client-side requests to it

![image](https://user-images.githubusercontent.com/1045274/63211564-efc16f80-c0c6-11e9-8823-2d96be540558.png)

**Comment by raisedadead** [comment]
> i think the fact that the comments are kind of buried behind the link helps that traffic trend

That is correct and by design (for now). We would rather not have the engagement than the sites fall over.

We currently are limited by our stack. For various vendor support / costing and partnership reasons we do not have parts of platform hosting under our control. Unfortunately I am unable to share more details about the infra here on this thread. 

As of now the fact remains, this is a feature request that we know of and would love to have as soon as we are able to handle the load at scale.

**Comment by QuincyLarson** [comment]
I've got a simpler solution.
