### ISSUE TITLE
Previous code not saved if submitted and move on to next challenge

### ISSUE THREAD

**Issue by mbrannon** [freeCodeCamp/freeCodeCamp#36626]
**Describe the bug**
When submitting code to move on to the next challenge, previous code is wiped from local storage/cache making it impossible to check previous work without downloading json in a roundabout terrible user experience.

**To Reproduce**
1. Go to 'Submit and move on to next challenge."
2. Click back.
3. All code reset

**Expected behavior**
Previously this code was saved and you could check your work to help with future problems. If you log out, this is still the behavior you get but then you obviously can't save long term progress or completion. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Latest Update

**Additional context**
I understand that you can't save it all to your database for the millions of users but previously local storage worked in this regard and logging out allows local storage of previous code to work just how everyone expects it to. There have been consistent forum posts from many different people having this same issue but all of the solutions recommended have not worked. In general, it comes down to "you must have some sort of issue allowing freecodecamp to write to local storage". However logging out gives the desired behavior of saving previous code and others sites work fine so this can't be the case.

**Comment by mbrannon** [comment]
I didn't think it was a feature request because it worked this way previously and STILL works this way if you are logged out of your account? So I think it's a bug. Is this suppose to only work this way and working as intended when logged in for some reason? That seems counter-intuitive since the logged out experience in this regards is better than registering.

**Comment by raisedadead** [comment]
Thanks for reporting. We know this has come up several times before. We would not be able to store any solutions on the User object in DB.

The logged out experience seems a bug an not a feature. The solutions are meant to be wiped out.

If you are interested, a PR is welcome to make use of local-storage.

Some thoughts went in here:
https://github.com/freeCodeCamp/freeCodeCamp/issues/34476

**Comment by mbrannon** [comment]
Thanks for pointing out that conversation. I missed it when I submitted this. I assumed the solution would be stored locally through the browser local storage and wasn't suggesting doing so on the User in the db. The logged out solutions seem to just stay in local storage even after submitting and moving on to the next one. Clearing your browser cache removes it and confirms this. When I saw it was behaving that way when logged out, I just thought it was an oversight that the same thing wasn't happening when logged in.

**Comment by raisedadead** [comment]
> When I saw it was behaving that way when logged out, I just thought it was an oversight that the same thing wasn't happening when logged in.

Unfortunately this is the other way around. 😅 !

We would love to be able to address this, and help cut the frustration. Unfortunately as you probably know the dev team has limited bandwidth, and we would need the community to come up with a solution for this feature request.

Thanks for your feedback.

**Comment by ojeytonwilliams** [comment]
By the looks of things, https://github.com/freeCodeCamp/freeCodeCamp/issues/34476#issuecomment-444850143, making it happen wouldn't be hard.  However, any PR would need to (at least) think about what happens if the storage gets full.

Is that why you wanted it to reset on submit in the first place?

**Comment by RandellDawson** [comment]
>However, any PR would need to (at least) think about what happens if the storage gets full.

@raisedadead What do you think should happen when the storage gets full?  Some kind of warning message?  Or maybe such a message should be display right before the local storage gets full.

**Comment by mbrannon** [comment]
@RandellDawson If the storage is full, give a warning that the solution will not be saved when moving forward with a confirmation? I mean how is it handled now? Currently it still saves progress locally until you submit it to move on.

**Comment by ojeytonwilliams** [comment]
I could be wrong, but I don't think it's handled at the moment, simply because it's highly unlikely anyone will hit the limit (I assume most people want to submit their challenges and get credit).  Honestly, even if this feature was implemented, it's still unlikely there will be a problem.  Probably best to plan for the worst, though.

If we *are* planning for the worst, I'd suggest creating a cache of sorts and chuck out old entries when the cache is full.  However, you'd need to be careful and make sure that the old entries can be cleared whenever the storage is needed.  Not just when user code is stored as it's already used in several places in the codebase.

**Comment by raisedadead** [comment]
> What do you think should happen when the storage gets full? Some kind of warning message? Or maybe such a message should be display right before the local storage gets full.

This repo has got plenty conversations around the issues with local storage and reasons that we are not using it without a reliable solution. I would recommend taking a look.

**Comment by mbrannon** [comment]
Short of sounding ignorant, as I've only read what was in #34476, what is wrong with the solution presented there in that discussion where we simply stop clearing it on submission and let it stay in localstorage indefinitely until the user clears the browser. This would clear a lot of the confusion because right now it's simply not behaving the way the users expect it should. It behaves that way until you finish the problem and then suddenly your work is lost and this is where the disconnect occurs. 

It seems counter-intuitive which is evident from the regular complaints on the forums. It is already made abundantly clear the copy/paste Support response in the forums about the two ways data is saved that storing it on the User in the db is not an option but that response also tells users that it is stored in localstorage until the browser cache is cleared or if something prevents freecodecamp to write to localstorage. So the disconnect is made even worse by this response because they go there wondering why their code is disappearing since they clear their browser cache and the response informs them that it shouldn't be happening.

So with all that said, why not just allow it to work in the way that is intuitive. In #34476, he said that it was simply a point of removing that one section on submitcomplete (paraphrasing since I don't have it open). The only issue I've heard brought up here in THIS discussion is what to do if their is no space to write but this just seems like such a small edge case and it would seem the user would be aware he has 0 bytes left on his hard drive. Are there other issues I am unaware of? Also like I mentioned before, I thought this was a bug because it does work that way when you are logged out where the solution persists and its such a better feeling more logical user experience.

**Comment by ojeytonwilliams** [comment]
I don't know enough to comment on other issues, but to clarify: the storage limit isn't hard drive capacity. It's the browser's self-imposed limitation and is browser dependent.

Hard drive space obviously not a problem (we're talking megabytes here), but `localStorage` might be.

**Comment by raisedadead** [comment]
We should ensure that **there is NO solution stored in either signed out or signed states**. This way there is NO confusion about storing anything at all.

Thanks for your detailed feedback.

**Comment by raisedadead** [comment]
Here is what is needed with anyone looking into this:

- Audit the master branch behaviour in both signed in and signed out state.
- Compare if solution is stored or not in the localStorage.
- Report back if further fix is needed.

Thanks.

**Comment by mbrannon** [comment]
Wait, how did you come to that solution? It should be the opposite. The confusion isn't happening because of it happening in the logged out state. It's happening because it doesn't make sense to clear your solution you just worked hard to complete when there is no reason to. It's not being stored in the db. That's why I asked if there was an issue with it just continuing to work the way it works before you submit the code. For me specifically, I found out because it worked when you were logged out but most of the confusion just comes from "HEY, I just finished that algorithm and its gone!". We should be fixing the logged in state so that it works that way. Like I said, maybe I am ignorant of some major issue that I am not thinking of but this makes a lot more sense than going to "fix" the logged out state.

And thanks ojeytonwilliams for the clarification.

Obviously localstorage is not perfect as it can be cleared by the browser or the user even without thinking about their solutions on freecodecamp but surely, it is a better solution than nothing at all which is what is really causing a lot of confusion. Maybe we can just put a simple text notice somewhere that "Solutions are stored via localstorage which is not permanent and may be lost if the browser cache is cleared. If you want to make sure your code is never lost, please use the download solution button o save your code!". 

That combined with just allowing it to operate the way it already does previously to completing it and removing the delete on submission code would seem to be a fine solution. Unless like I said there is some major issue which as I said I could be ignorant of and am more than happy to be filled in about. 

So just from looking a the previous discussion, this is the code that affects the localstorage and specifically deleting the work on submission:

`// client/src/templates/Challenges/redux/code-storage-epic.js

/*
  store is a package for interacting with localStorage
  Code omitted for brevity 
*/

function clearCodeEpic(action$, state$) {
  return action$.pipe(
    ofType(types.submitComplete, types.resetChallenge),
    tap(() => {
      const { id } = challengeMetaSelector(state$.value);
      store.remove(id);
    }),
    ignoreElements()
  );
}`

While I don't know everything that is happening, it seems that the clear code action is being executed on the ofType for types.submitComplete and types.resetChallenge which seems to be confirmed by the same solution posted in #34476 so why not just remove types.submitComplete from the list of triggers for deleting the solution from localstorage. If you are worried about confusion from clearing the browser data somewhere, let's add a text notification somewhere. Anywhere. Because really, that is way less confusing than losing your work as soon as you finish it without choosing to clear it.

**Comment by raisedadead** [comment]
As I said a previously, a PR is welcome either to make the localStorage work covering all edge cases that we have not been able to solve in a really long while. Or removing it completely removing all confusion about storage.

In practice, notifications and any sort of communication does not work.

The dev team does not have the bandwidth to work on this at the minute, the code is open source and we would love the help from the community.

Any further guidance can be taken up by first researching the past discussions.

[We are not saying we do not care. Its just out of the scope of the priorities we have right now.]

**Comment by raisedadead** [comment]
Hi @mbrannon There is an old PR that I found: https://github.com/freeCodeCamp/freeCodeCamp/pull/35583

Would you be interested in driving the progress further on it?

**Comment by iangilman** [comment]
I have this issue too. Unfortunately I don't think I can contribute a solution, but I thought I'd add a few thoughts.

For starters, the reason I want it is that I'm mentoring a student going through the challenges, and I want to be able to go back over the completed challenges and discuss alternate possibilities with them. Having the completed code stored on the challenge page would be ideal for that use case.

A workaround is to hit the "download my solution" button before hitting "submit and go to next challenge". At least you'll have the code, although it's not as nice as having it there in the editor.

So, it seems the big question on this issue is, "What happens when localStorage fills up?" For my use case, at least, ditching the oldest solutions would be fine, since I only need to go back over a week's worth of work with my student.

localStorage can store 10 MB of data, which isn't that much by today's standards, but it's actually quite a lot of code… I just did a quick estimation based on one of my 1000 line code files and found I should be able to fit 350,000 lines of comparable code in 10 MB. Even if it's only 100,000, that's still a lot of completed challenges.

That said, if we want more headroom, indexedDB gets you more like 50 MB (or more, depending on how your browser is configured). I don't know how you feel about adding dependencies, but the localForage library puts an easy localStorage-style interface on top of indexedDB:

https://localforage.github.io/localForage/

The only caveat being that it goes from being synchronous to asynchronous (because of the underlying technology).

Anyway, I thought I'd leave these notes here in case they are useful to anyone who might pick up this issue. Sorry I can't contribute more, and thank you for freeCodeCamp! It's a wonderful resource for the web development community :-)

**Comment by moT01** [comment]
An alternative could be to just store the last 5 or 10 submitted challenges in local storage or something like that (or more). This way the hard work put in to a challenge won't immediately be lost, and they can refer back to it, but just for a little bit. And we wouldn't have to worry about the storage filling up.

@iabhishek07's case of going back through a weeks worth of challenges is probably pretty rare. I think the most common problem is when something gets submitted, it just disappears. Which is something I have been frustrated with in the past.

-- just another thought, in case someone decides to try and tackle this.
