### ISSUE TITLE
Devops: redirect footer views that have been ported to news

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#36622]
https://www.freecodecamp.dev/about/
https://www.freecodecamp.org/news/about/ 
About 

https://www.freecodecamp.dev/support/
https://www.freecodecamp.org/news/support/ 
Support 

https://www.freecodecamp.dev/sponsors/
https://www.freecodecamp.org/news/sponsors/ 
Sponsors 

https://www.freecodecamp.dev/academic-honesty/
https://www.freecodecamp.org/news/academic-honesty-policy/ 
Academic Honesty 

https://www.freecodecamp.dev/code-of-conduct/
https://www.freecodecamp.org/news/code-of-conduct/ 
Code of Conduct 

https://www.freecodecamp.dev/privacy-policy/
https://www.freecodecamp.org/news/privacy-policy/ 
Privacy Policy 

https://www.freecodecamp.dev/terms-of-service/
https://www.freecodecamp.org/news/freecodecamps-terms-of-service/ 
Terms of Service

**Comment by ahmadabdolsaheb** [comment]
/welcome should probably redirect to / as well since welcome has been removed.

**Comment by raisedadead** [comment]
Thanks @ahmadabdolsaheb can you add this to your PR in that case?
