### ISSUE TITLE
404 page has double footer.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#36647]
![image](https://user-images.githubusercontent.com/4591597/63364399-25dc4900-c37e-11e9-97f6-c1134291a145.png)

**Comment by moT01** [comment]
I'm not seeing it on the 404 I'm looking at - what URL gives you that problem?

**Comment by RandellDawson** [comment]
I see it when running it locally but not on the freecodecamp.dev site.

**Comment by moT01** [comment]
Yea, I'm pretty sure this has come up before and determined that it only happens locally and wasn't a problem. But if it's on the .dev site somewhere, then it probably is.

**Comment by ahmadabdolsaheb** [comment]
Thanks for referencing that issue @moT01. it does not show up on dev so it should be alright.
