### ISSUE TITLE
buttons with text-decoration set to none get underline for text decoration.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#36644]
On the profile page, displayed button with text-decoration set to none gets an underline most likely due to the styles of its parent (a tag)

![image](https://user-images.githubusercontent.com/4591597/63359455-7307ed00-c375-11e9-8803-e4b03cca3ff6.png)

same issue also present in the current welcome page.

![image](https://user-images.githubusercontent.com/4591597/63360072-7354b800-c376-11e9-9751-f139679fae9d.png)

**Comment by huyenltnguyen** [comment]
@ahmadabdolsaheb So we are just going to set `text-decoration: none` to the `a` tag then? Or is there another approach you prefer?

Btw, I noticed that the word `Challenges` in `Take me to the Challenges` is capitalized, is this a typo or it's on purpose?

**Comment by ahmadabdolsaheb** [comment]
@huyenltnguyen the a tags are to underlined all across. the only exceptions are navigation, footer, buttons, and a couple of more places.

@moT01, thank you for tackling this. is there are a way we could resolve this globally rather than adding classes to a tags one by one?

**Comment by moT01** [comment]
I found that [an underline is applied globally](https://github.com/freeCodeCamp/freeCodeCamp/blob/1348a5a037f0eb3cece2c3445c157706a6b20e09/client/src/components/layouts/global.css#L75) - We could just change that, but it would remove the underlines in places where we probably want them. There's one in the bottom paragraph of the homepage, for instance. A few more on the learn page.

**Comment by ahmadabdolsaheb** [comment]
interesting, wouldn't class styles override global styles? it does for everything else.

**Comment by ahmadabdolsaheb** [comment]
@moT01 
if a global solution is not possible we can perhaps define a class globally for removing the underline and give it to every a tag that we want to remove the underline from.

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb @moT01 it's all a bit weird.  The underlined links are the ones which have a `button` inside an `a`.  In this case the `text-decoration` is being inherited from the `a` and so defaults to `underline` completely ignoring the `button` style.  It's a quirk of css that I don't fully understand, but it is what it is.

I think the right approach is just to remove the `buttons`, since they should not go inside `a` elements anyway - see [this SO discussion](https://stackoverflow.com/questions/6393827/can-i-nest-a-button-element-inside-an-a-using-html5).

**Comment by ahmadabdolsaheb** [comment]
@ojeytonwilliams not sure why we do it this way.
Any thoughts @ValeraS?

**Comment by ahmadabdolsaheb** [comment]
We might have buttons around for a11y resons.
should we give the link to the formaction property of the button so it acts like a a tag?

**Comment by ojeytonwilliams** [comment]
As far as accessibility goes, I think the main thing is that links are obviously links and vice versa.  If a link looks like a button, that could potentially cause confusion, but I think it's clear what's going on in this case.

**Comment by ahmadabdolsaheb** [comment]
@moT01 yes, we should remove the ```<Button>``` when linking to other pages.
