### ISSUE TITLE
[.dev] front end project pages have no margin

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36645]
Front end project pages have no margin and hug the window:
<img width="370" alt="Screen Shot 2019-08-20 at 9 12 57 AM" src="https://user-images.githubusercontent.com/20648924/63362980-5e593400-c338-11e9-9188-b4eecdc6a5aa.png">

All other pages have a margin I believe:
<img width="373" alt="Screen Shot 2019-08-20 at 9 12 48 AM" src="https://user-images.githubusercontent.com/20648924/63362969-58635300-c338-11e9-9e38-a490b5a1e4a5.png">

I can fix this one

**Comment by ahmadabdolsaheb** [comment]
@mot01 from the screenshots. does adding  a padding that way causes a horizontal scroll?

**Comment by moT01** [comment]
No, I'm pretty sure that's just my firefox being goofy again - that screenshot is from .dev and it shows this at the bottom on my firefox...
<img width="319" alt="Screen Shot 2019-08-23 at 7 40 55 AM" src="https://user-images.githubusercontent.com/20648924/63593360-6fdd4e80-c579-11e9-9dce-8b1c385aca0d.png">
causing the horizontal scroll bar to appear, but it's fine on chrome.

**Comment by ojeytonwilliams** [comment]
That should get fixed by https://github.com/freeCodeCamp/freeCodeCamp/pull/36658, unless there's some other stuff overflowing.

It just needs
```css
.btn {
  whitespace: pre-line;
}
```

**Comment by ojeytonwilliams** [comment]
Thinking about it: do you want to make that change in your PR as well, @moT01?  That way you can see if there are any other problems.

**Comment by moT01** [comment]
Looks like it might not be my firefox - I found that when signed in, it displays the button in the picture above - but when not signed in, the button says "I've completed this challenge" 

So it's not the margin causing the scrollbar.

**Comment by moT01** [comment]
looks like that property does fix the scrollbar issue @ojeytonwilliams -
<img width="292" alt="Screen Shot 2019-08-23 at 8 23 25 AM" src="https://user-images.githubusercontent.com/20648924/63595777-5e974080-c57f-11e9-841f-7720855f2240.png">

but it's strange that the button displays different text based on authentication
