### ISSUE TITLE
Update Auth0 template to match styles

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#36654]
Action items:

- [x] Remove all meta information from the html, other than critical meta.
- [x] Replace jQuery with cash.
- [x] Update the color scheme to latest on master (single color scheme, light mode).
- [ ] Implement `webAuth.checkSession` for generating the token.
- [x] Remove all navigation links from the navbar.

<details>
<summary>
Original Report
</summary>

**Describe the bug**
The Signin page doesn't have the new theme applied. I also noticed that the link to forum on its navbar hasn't been updated (still pointing to `forum.freecodecamp.org` instead of `freecodecamp.org/forum`).

**To Reproduce**
1. Go to https://www.freecodecamp.dev/
2. Click `Signin` and wait for the redirect to `freecodecamp-dev.auth0.com/*`

**Screenshots**
<img width="1680" alt="Screen Shot 2019-08-21 at 2 01 18 PM" src="https://user-images.githubusercontent.com/25715018/63409845-2d522f80-c41c-11e9-8d6c-3e15c1c012c2.png">

---
(I don't see this page in the [won't-fix list](https://github.com/freeCodeCamp/freeCodeCamp/pull/36570#issuecomment-522638397), so I just create an issue to be safe. Let me know if this should be ignored.)

</details>

**Comment by raisedadead** [comment]
The page theme (css styling) needs to be updated. However the content on the page will be different on the production and the development versions.
