### ISSUE TITLE
A lot of my progress has disappeared

### ISSUE THREAD

**Issue by donniereese** [FreeCodeCamp/FreeCodeCamp#3665]
After one of the resets, I lost a good deal of my progress on my Map of progress.  My points also decreased.  I am really not sure if there is a way to fix this or a reason for it.

Any suggestions?

**Comment by ltegman** [comment]
This has to be manually fixed. Please let them know in #3630

**Comment by BerkeleyTrue** [comment]
Yes, please comment on #3630. We will be using that list to fix profiles.
