### ISSUE TITLE
[.dev] checkmarks on learn+night mode are hard to see 

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36666]
<img width="208" alt="Screen Shot 2019-08-22 at 9 52 02 AM" src="https://user-images.githubusercontent.com/20648924/63525034-a015e600-c4c2-11e9-98d1-cd0db18261b6.png">

It's worse than it looks in the picture, it's like an optical illusion or something.

**Comment by ahmadabdolsaheb** [comment]
you could switch the white and gray and see how it looks.
Also it should look good on modal when users finish a challenge.

**Comment by raisedadead** [comment]
I think the spacing between the check marks and the bounding circle needs to be increased.

Also another nicer way would be replace this with a GitHub like check box, a square will have more whitespace than a circle.

- [ ] Challenge name
- [x] Challenge name

**Comment by ojeytonwilliams** [comment]
Tangentially related to this, the circles are almost invisible in default mode:
![CheckCircles](https://user-images.githubusercontent.com/15801806/63705580-c83c7680-c82d-11e9-9cc9-1ff8a96f9e45.png)

For the top one, I've applied `stroke-width: 10` as quick fix.

While this'll probably be solved if we shift to checkboxes, I think we should make sure that that does actually happen.

**Comment by ojeytonwilliams** [comment]
It's possibly my eyes/monitor settings, but they're so hard for me to see that they almost disappear.
