### ISSUE TITLE
Monaco editor is not styled according to theme for unauthenticated users. 

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#36663]
to replicate.
go to incognito
do not sign in
go to learn
choose a challenge

![image](https://user-images.githubusercontent.com/4591597/63469071-01619900-c472-11e9-9894-63ad6ffa522c.png)

**Comment by huyenltnguyen** [comment]
I can take a look at this

**Comment by ahmadabdolsaheb** [comment]
@huyenltnguyen, thank you.
There might to be other inconsistencies with the theme.
If you try different scenarios like switching the theme, logging in logging out, and visiting the challenge page. 
That should expose any related issues that needs fixing.
let me know if I could be of any help.

**Comment by ahmadabdolsaheb** [comment]
in builders.js displaytheme is in charge of the code editor's theme. and in components/layout/default.js the theme colors get injected.  we need night mode by default.

**Comment by moT01** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/templates/Challenges/classic/Editor.js#L23

**Comment by huyenltnguyen** [comment]
@moT01 I haven't tested, but it does look like the cause. Hope you don't mind raising a PR, since I don't want to take your credit 😄

**Comment by moT01** [comment]
I pointed it out for you. But yea, I have it ready.
