### ISSUE TITLE
Advance code solution is not able to pass first two test cases.

### ISSUE THREAD

**Issue by aniltudu** [freeCodeCamp/freeCodeCamp#36674]
![error](https://user-images.githubusercontent.com/42162543/63593425-9d55e680-c5d1-11e9-82ee-3349afae27e2.png)
**Describe your problem and how to reproduce it:**
The advance code solution provided in Truncate a String is not able to pass first two test-cases. If you find anything wrong please forgive me.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-algorithm-scripting/truncate-a-string/

**Tell us about your browser and operating system:**
* Browser Name: Not necessary.
* Browser Version: Not necessary.
* Operating System: Not necessary.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by aniltudu** [comment]
If you think the problem mentioned above is valid and you want a solution to replace. Here is my code which passed all the test cases.

**Code:**
function truncateString(str, num) {
  // Clear out that junk in your trunk
  if(str.length <= num){
    return str
  }
  return str.slice(0, num) + "...";
}

truncateString("A-tisket a-tasket A green and yellow basket", 8);

**Proof:**
![correct](https://user-images.githubusercontent.com/42162543/63594036-012cdf00-c5d3-11e9-9bac-2203956ab6c9.png)

**Comment by moT01** [comment]
The guide is being moved over to the forum. [Here is the post for that challenge](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-truncate-a-string/16089). Both of those solutions work, so when the current guide is removed - this shouldn't be an issue.

**Comment by RandellDawson** [comment]
This can be closed as we are just waiting for master to be shipped to production.
