### ISSUE TITLE
Broken link on Basic Data Structures: Iterate Through the  Keys of an Object with a for...in Statement

### ISSUE THREAD

**Issue by wale-bant** [freeCodeCamp/freeCodeCamp#36672]
**Describe your problem and how to reproduce it:**
There is a typo linked to the “Get a hint” button on the above lesson. It sends you to:
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement

when it should send you to:

https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for...in-statement/

where the "for…in" in the url is dots not dashes!

I'd love to fix this.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/-iterate-through-the-keys-of-an-object-with-a-for---in-statement

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 76.0.3809.100 (Official Build) (64-bit)
* Operating System: Ubuntu(Linux)
![404-page-error](https://user-images.githubusercontent.com/47564977/63556368-143ca200-c534-11e9-9000-0b5509526aea.png)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
This has already been fixed.  See the most recent version of the master branch.

https://www.freecodecamp.dev/learn/javascript-algorithms-and-data-structures/basic-data-structures/iterate-through-the-keys-of-an-object-with-a-for...in-statement

I am closing this PR because we are just waiting for master to be deployed to production.
