### ISSUE TITLE
Your a element should have the anchor text of "cat photos"

### ISSUE THREAD

**Issue by EmmanuelMetrillo** [FreeCodeCamp/FreeCodeCamp#3667]
I don't get this I already do all the possible solution I think this is a bug.. Any solution will be appreciated, Thanks in advance for those who will help..

http://freecodecamp.com/challenges/waypoint-link-to-external-pages-with-anchor-elements#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%3Ca%20href%20%3D%20%22http%3A%2F%2Ffreecatphotoapp.com%22%3E%0A%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%0A%3C%2Fa%3E%0A%3Cp%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A%3Cp%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fp%3E%0A

**Comment by bugron** [comment]
@EmmanuelMetrillo thanks for posting.
Actually your code is incorrect:
```html
<a href = "http://freecatphotoapp.com">
<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">
</a>
```
Your `a` element has an image inside it instead of the text "cat photos". This should look like this:
```html
<img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat">
<a href = "http://freecatphotoapp.com">cat photos</a>
```
Closing this issue. Feel free to reopen if you still have problems.
If you have problems with your code, please post a message in our [Gitter char room](https://gitter.im/FreeCodeCamp/Help) first, thanks.
