### ISSUE TITLE
Learn Preview background should be white

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#36670]
I did not see anyone raising this issue, but I don't think the background of the preview in default or night mode should be anything other than white unless the coding exercise specifically changes the background to something else.  The preview should be exactly what you would see in a browser.  In almost all the challenges, the background would be white.

![image](https://user-images.githubusercontent.com/5313213/63539212-68ad3680-c4ce-11e9-8c43-37cc910c7080.png)

**Comment by ahmadabdolsaheb** [comment]
I share your concerns @RandellDawson.

The reason we changed the color of the display is that a white display is discomforting to the eye  on night mode when everything else is dark. so we injected some styles to harmonize the view in general. 

That convention was carried over to light mode.

**Comment by ojeytonwilliams** [comment]
It might be better to default to white in light mode, same as the editor.

As for night mode, some of the css challenges might need some changes to look reasonable in both modes.  For instance, in night mode, https://www.freecodecamp.dev/learn/responsive-web-design/basic-css/use-an-id-attribute-to-style-an-element looks like this:

![UseAnIdNightMode](https://user-images.githubusercontent.com/15801806/63586469-a6c75a80-c5a1-11e9-988a-be4152d8e352.png)

If we change the seed code to

```css
.silver-background {
  background-color: silver;
  color: black;
}
```
it would become
![UseAnIdBlack](https://user-images.githubusercontent.com/15801806/63586720-556b9b00-c5a2-11e9-84d0-b820c3460b09.png)

It would have to be case-by-case, though.

**Comment by ahmadabdolsaheb** [comment]
That is a very good point. 
I will defer this to @QuincyLarson.

**Comment by moT01** [comment]
Logically, I have to agree with @RandellDawson - displaying anything other than what the code in the editor would produce might confuse campers. 

But it is a little rough on the eyes to have the white background on night mode. And the current theme looks a lot better - so it's a tough call. 

I scrolled through a number of challenges, and there's quite a few that don't look right with the blue background. So there might be a decent amount of work to go through and fix all of them.

**Comment by RandellDawson** [comment]
I really like the new theme, but a preview should be a true preview.  We want to make this like the real world.  Developers working in some kind of night mode on their favorite local editors, still expect  to check the "real" result of the code they have written on a browser or in a preview mode in their local editors.  The night mode should only apply to the editor or the non-preview part of the FCC site.  Anything else is just not realistic.

**Comment by raisedadead** [comment]
The preview should be white.

**Comment by ahmadabdolsaheb** [comment]
Definitely.
