### ISSUE TITLE
Lesson Redesign

### ISSUE THREAD

**Issue by ArcticPirate** [freeCodeCamp/freeCodeCamp#36681]
I've not been happy with the current state of the lesson UI for a while now, and although it works, I feel there's a lot of room for improvement. I have seen the new redesign and I feel it doesn't address most of the issues here. The choice of typography in the redesign is worrying, but I don't think this is the place to discuss that issue. 

**Please note:** These designs aren't a final product. Syntax highlighting was chosen at random. Accessibility has not been fully tested.

# Link to the designs

|       Light Mode       |       Dark Mode        |
| :--------------------: | :--------------------: |
| https://ibb.co/6vjKLYY | https://ibb.co/NmRtT7z |

# Reasoning

Below is an in-depth review of the choices I've made, and why they would benefit the end-user. 

#### Separate the lesson header
First, the text has been aligned to the left to give consistency. Often, lesson names will overflow and you'll have one word in the middle of the screen. Left-aligned text is easier to read. These, along with the increased spacing, will reinforce what lesson the user is on. The course you're on is not as important as the lesson name, so they have been separated and given the appropriate hierarchy. 

#### Increase spacing
Text that almost touches the side of your monitor (which is usually black, increasing contrast and text blur) makes it harder to read. Here, the lesson description has increased whitespace to account for this issue. 

#### Button placement
The key takeaway here is that the 'Run tests' button has been put on his own. Right below it is the course checklist. This has been done for a few reasons:
- It encourages users to try and complete the lesson themselves.
- 'Run tests' is the button you'll be clicking most of the time, so it makes sense its given more importance. 
- The rest of the buttons have been placed at the bottom, for the reasons above. They're also half-width with increased spacing between them. This makes it easier to read and navigate.

#### Course checklist
This section could still use much improvement, I'd rather treat it as a prototype. However, these are the main points I've tried to address:
- Give a better indicator which points you have failed or passed. 
- Increase spacing for the icons, currently, they're making each point messy. 
- Although an X has been used, I think an exclamation mark would be better suited instead. An X usually indicates that you either want to close something or that you cannot enter. 

#### Other 
The rest of the design is rather self-explanatory, but it's been given a fresh look by cleaning up the elements and dividing the sections with clear borders. There are many unnecessary borders and visual noise in the current version.

**Comment by RandellDawson** [comment]
@ahmadabdolsaheb Thoughts?

**Comment by ahmadabdolsaheb** [comment]
@ArcticPirate, thank you for submitting the mocks. they look very good.

We are aiming to replicate the feel of a code editor in an accessible way in next couple of UI sprints and that is the reason we are using monospace, large font, high contrast, large icons.

Our current UI can benefit from the improvements you mentioned such as spacing. We will make sure to review the lesson UI before deployment and take your suggestions into account.

@QuincyLarson thoughts?

**Comment by ArcticPirate** [comment]
@ahmadabdolsaheb 


#### Monospace font 

Although monospace fonts can help certain groups of people, for you majority of people it will [decrease legibility](https://ux.stackexchange.com/questions/48753/does-the-use-of-monospaced-fonts-negatively-affect-legibility-of-article-text). This isn't what monospace fonts were designed for. There are sans-serif fonts that have been specially designed for use in graphical user interfaces. Open Sans and Source Sans are to name a few, which offer beautiful clarity when reading. 





#### Font size

[Larger fonts mean fewer characters per line which can increase reading time and legibility](https://ux.stackexchange.com/questions/108801/what-is-the-best-number-of-paragraph-width-for-readability). I can understand font size being an issue to some users, but for those who have increased the size in their browser settings, it means they will be receiving an even larger font. 

---

These two issues are shifting the problem from one groups shoulders, and placing it in another. Having a setting where you can choose your own font size and typeface would be the best option to combat this.

**Comment by Ieahleen** [comment]
I find monospace completely unreadable in large block of texts, I am totally unable to read posts on the forum if people put everything in backticks, I don't think I am the only one


please don't use monospace for challenge instructions @ahmadabdolsaheb

**Comment by vkWeb** [comment]
@ahmadabdolsaheb I have been closely observing the UI changes on the platform and I really appreciate your work on the chic man, just amazing! :) 

I do feel we need to address some UX issues @ArcticPirate has pointed to. Btw @ArcticPirate those designs are bang-on <3. But we don't need to give a full UI refresh at this point.

Addressing the below two issues will make a very big impact in terms of UX:

### 1. font-family and hierarchy

The Roboto Mono font is unreadable when there is a large block of texts. It can be used in `test output` area but not in the descriptions. Font size, site layout, contrast, icons, colors are good.

In some places, I have observed that font hierarchy has been ignored:
![Screenshot (4)](https://user-images.githubusercontent.com/26724128/63929697-87cc3b00-ca6f-11e9-98d5-a9e67c1e6614.png)

### 2. Button placement

@ArcticPirate's button placement approach is what freeCodeCamp needs but with a slight change. We should place buttons in the same way @ArcticPirate has done but below the `run tests` button.
Also, `get a hint` and `watch video` buttons should be grouped under `help`.

<hr>

@ahmadabdolsaheb I will be glad to work with you and help you in fixing these issues.

**Comment by ArcticPirate** [comment]
@vkWeb If there was a time to do a UI refresh, it's now. Unfortunately, the current site design really doesn't reflect the quality content on the site.

Why do you feel the other buttons should be below the `run tests` button? Or in other words, why do you feel they are *more important* than the lesson checklist?

**Comment by vkWeb** [comment]
> If there was a time to do a UI refresh, it's now. Unfortunately, the current site design really doesn't reflect the quality content on the site.

@ArcticPirate The current theme and feel of a dark code editor is what we need for the upcoming project-based curriculum. Also, the current UI looks nice. We should improve upon that. Once we get confirmation from a senior team member, we will start working on improving the current UI design.
 
> Why do you feel the other buttons should be below the `run tests` button? Or in other words, why do you feel they are more important than the lesson checklist?

When campers reach the algorithm section they use `Get a hint button` a lot to check if there can be a better implementation of the problem (that's what I used to do and I believe most of the campers do that too). So, we need to keep those buttons in front of their eyes. Also, the `output test area` shows the unpassed tests that's why I feel those buttons are more important than the checklist.

**Comment by ArcticPirate** [comment]
@vkWeb Without statistics, I wouldn't like to say anything about how useful the 'Get a hint' button would be in practice. I do know that it would be around 500 pixels down on the screen. Not a far way to go. Do you think the majority of campers use the `get hint` button, more than the lesson checklist?

**Comment by vkWeb** [comment]
@ArcticPirate No, you misunderstood my point friend 😅. 

I was trying to say that the majority of clicking happens in the `run test` and `get hint` buttons so they should be placed in front of camper's eyes. Most of the challenges have more than 3 test cases so the description area overflows vertically. Now imagine, scrolling down again and again and then clicking buttons. Will it be a good user experience? For me, it's a big no.

So, in terms of placement and UX, the buttons are more important than the checklist. I hope you got my point now ;)

**Comment by ArcticPirate** [comment]
@vkWeb I'm confused, do you have stats for the point you made? If so that simplifies things

**Comment by vkWeb** [comment]
@ArcticPirate Some design decisions are made without stats. I am assuming average user behavior (90% users) and design according to that. We can improve for the rest of 10% in future iterations.  

This is what my point is:
> In terms of placement and UX, the buttons are more important than the checklist. So, buttons should be placed above the checklist area.

**Comment by RandellDawson** [comment]
> I am assuming average user behavior (90% users) and design according to that.

@vkWeb But what makes you think 90% of users expect this?  If you have some data to support your theory, you can throw out numbers.  Otherwise, it is just an opinion or personal preference.

**Comment by Ieahleen** [comment]
as an user I think I would prefer to see the checklist

the buttons Get a Hint, Ask for Help and such are buttons I would press at
most once or twice, instead the checklist items I would need to have always
under eyes, I need to consult those often while writing the code. the most
I struggle with the challenge the most useful is to have the whole
checklist under eyes I would say

**Comment by ahmadabdolsaheb** [comment]
Thank you everyone for your feedback.
I would also like to hear from @QuincyLarson about the modifications he would rather have for this iteration.

**Comment by bogscode** [comment]
I just joined and I'm new to coding etc, but since this topic is about buttons etc. Can we can we make the Run the Tests button fast key configurations customizable ? I hate having to hit Ctrl + Enter. Maybe it's just me but hitting control (ctrl) stretches out my pinky uncomfortably and since we will be doing this all the time during a lesson can we try to make it a little user friendly for our fingers? Idk I respect everything you guys are doing with this project as I'm learning HTML at the moment but it's a real pain at the moment. Thanks for taking my input!

**Comment by vkWeb** [comment]
@RandellDawson Yes, it's my personal opinion or thought you can say. But I firmly believe in that UI approach :)

**Comment by ArcticPirate** [comment]
@bogscode I'm curious, my keyboard has two CTRL buttons and one of them is below the enter key. Does yours not have that?

**Comment by bogscode** [comment]
@ArcticPirate All keyboards do...I like to keep my fingers on fdsa jkl; so if anything can help where I don't have to move my hand as much would be more preferable. I'm 25 but I can imagine people who have Arthritis in their wrists etc it would be a benefit for as they could keep their hands in place  if they could map any key they want. Like I said it's just a suggestion but it would help make the site a little more user friendly. Maybe that could be an advanced setting feature.

**Comment by QuincyLarson** [comment]
Hey everyone - I'm a bit late to this conversation.

First of all, I enjoyed @ArcticPirate's proposed design.

Rather than try to redesign our old UI, I encourage you to wait until our new UI is ready, then make incremental tweaks to that.

Regarding monospace font VS proportional, proportional is indeed easier to read and we will be using it whenever we have more than a few words of text.
