### ISSUE TITLE
Git clone of freecodecamp automatically delete file's because of big path for windows .

### ISSUE THREAD

**Issue by viveksharmaui** [freeCodeCamp/freeCodeCamp#36683]
Hi ! when i clone this repo it's automatically delete file with big path in windows .
So i wrote this command in git :  `git config --system core.longpaths true`
I will try to solve this issue as soon as possible and create pull request for this .

**Comment by RandellDawson** [comment]
I use Windows and do not experience this issue.  What version of Git and Windows are you using?

**Comment by viveksharmaui** [comment]
I'm using windows 7 and git version : git version 2.8.1 :)

**Comment by RandellDawson** [comment]
Must be a Windows 7 issue.  @raisedadead What is the minimum version of Git a user should have and what do you think about adding a note regarding the special config setting for Windows 7 users?

**Comment by viveksharmaui** [comment]
I have create pull request for this issue and updated contributer.md file #36684

**Comment by raisedadead** [comment]
Technically, we do not support OS / Browsers or software which are not currently in stable release / support mode. Windows 7 EOL is January, 2020.

I am fine with adding the note, but its strongly discouraged to continue supporting legacy software / OS.

**Comment by raisedadead** [comment]
I am going to close this because this is a rare case, and we cant provide support for `Git` a standard tool. Such support maybe found elsewhere on Stackoverflow.
