### ISSUE TITLE
Delay in navigation to articles when clicking on search bar results

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#36692]
When I click on a search result sometimes, there can be a 2-4 second delay before the page even starts to navigate to the news article. It seems there should be a loading icon to let the user know that something is working. A few times I thought the page froze.

**Comment by ojeytonwilliams** [comment]
Given that the results are just links, won't this go away if we start using Gatsby for news?

**Comment by raisedadead** [comment]
We may not be using gatsby for news soon enough. As for the delay can we have a screencap (gif) of some sort to better understand and address this.
