### ISSUE TITLE
Field Guide doesn't work

### ISSUE THREAD

**Issue by kmiasko** [FreeCodeCamp/freecodecamp#367]
Completed Field Guides array has been cleared (filled with only first Field Guide id). User can show all Field Guides but can't complete any of them.

`if (data.completedFieldGuides.indexOf(data.fieldGuideIds[i]) > -1) {` 
will always return -1 because `data.fieldGuideIds[i]._id` should be used.

After clicking 'Next Field Guide' button no Post request is fired to mark field guide as completed.

**Comment by terakilobyte** [comment]
Thanks for the report. This was squashed previously but we're experiencing zombie code.
