### ISSUE TITLE
Restrict usernames

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36708]
I was able to change my username to `learn` - and when I try to view my profile, I get the learn page. We should probably not allow that, or usernames of any other pages.

<img width="624" alt="Screen Shot 2019-08-28 at 10 21 18 AM" src="https://user-images.githubusercontent.com/20648924/63869622-0ba5fa80-c97e-11e9-9f7d-a572780a3da3.png">

**Comment by raisedadead** [comment]
This file should be updates will all such keywords [`api-server/server/utils/constants.js`](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/api-server/server/utils/constants.js)
