### ISSUE TITLE
Ambiguity in the guide webpage and github repo

### ISSUE THREAD

**Issue by cs5055** [freeCodeCamp/freeCodeCamp#36710]
**Describe your problem and how to reproduce it:**
The webpage guide.freecodecamp.com is not updated with the current github guide repo. It seems like there is misspelling in "C" section of the guide with topic "Dinamic Memory Managment" which should have being "Dynamic Memory Management". However in https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/c/dynamic-memory-management/index.md the misspelling is already correct. So, the changes are not reflected to the website.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/c/Dinamic%20Memory%20Management/

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot from 2019-08-28 23-57-42](https://user-images.githubusercontent.com/26201043/63882465-abe83780-c9ef-11e9-97ce-f13bc287c5bc.png)

**Comment by raisedadead** [comment]
We are sunsetting the guide in the upcoming version of freeCodeCamp. Thanks for your report.
