### ISSUE TITLE
Curriculum hint articles which need updating

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36715]
When changes are made to a challenge, we should check that the hint article on the forum still aligns with those changes. 

This issue is for tracking those curriculum PR's. 

Keep in mind that the article doesn't need to be updated until those changes are pushed to production.

### PR's that have not been merged yet:

- 
  
### PR's that have been merged and the guide needs updating:

- ~~https://github.com/freeCodeCamp/freeCodeCamp/pull/35770~~

### Forum topic has been updated:

- ~~https://github.com/freeCodeCamp/freeCodeCamp/pull/36703~~ 
- ~~https://github.com/freeCodeCamp/freeCodeCamp/pull/36623~~

--

**Moderators, feel free to edit this.**

**Comment by tttaaannnggg** [comment]
How do we actually contribute to the guide? the guide repo points back at the monorepo, which points to contribution guidelines, which just points us back at the (empty) guide repo again....

I've tried to grep through the monorepo to figure out where the files are, but no luck. Am I missing something?

**Comment by thecodingaviator** [comment]
Hi, @tttaaannnggg please go through [this issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/36729)

**Comment by RandellDawson** [comment]
@moT01 Can this be closed now?

**Comment by moT01** [comment]
Fine with me if you want @RandellDawson, although there will probably be future changes to challenges where hints will need updating - this might be a good place to track them. But you're the one who has been keeping those up to date I think so if you think it's not needed...
