### ISSUE TITLE
Universal navigation needs to be added to learn

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#36724]
User stories:
- [x] users should see projects (/learn), forum, radio, news, portfolio (/settings), donate in the nav bar
- [x] users should land on settings page after clicking the portfolio button
- [x] unauth users should be prompted to sign in when clicking on portfolio or donate buttons
- [x] unauth users should see a button "sign in to save your progress" when visiting projects (/learn)

**Comment by ahmadabdolsaheb** [comment]
The UI is done.
here are the screenshots for the breakpoints.
![image](https://user-images.githubusercontent.com/4591597/64350477-633d0980-d001-11e9-9eee-6af3f2071d90.png)

![image](https://user-images.githubusercontent.com/4591597/64350396-40125a00-d001-11e9-9e62-2e69e76de293.png)
![image](https://user-images.githubusercontent.com/4591597/64350419-49032b80-d001-11e9-8668-44545be74b68.png)
![image](https://user-images.githubusercontent.com/4591597/64350508-6c2ddb00-d001-11e9-93c9-c0949be7bc9a.png)

**Comment by ahmadabdolsaheb** [comment]
@QuincyLarson, @raisedadead 
for the following user story:
unauth users should be prompted to sign in when clicking on portfolio or donate buttons

Currently unauthorized users who visit settings get redirected to landing page.

We could have a similar functionality for donate and portfolio buttons where unauthorized users get redirected to landing page with a  flash message saying "sign in to visit donation page" and "sign in to visit Portfolio settings" for donate and portfolio buttons respectively. Would that be the right way to go?

**Comment by raisedadead** [comment]
Please throw in a PR and we will take it from there.  

Please note that this is a significant change from the current production UX, and would need us to add unit tests before we proceed to release.

**Comment by ahmadabdolsaheb** [comment]
@raisedadead I completely agree,
Here is the PR #36744

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb One minor change we should make to the search box should be the inclusion of a magnifying glass icon to the left of the "Search 5,000+ tutorials" text. 

Even though we don't use icons anywhere else in our navigation, I think this will help convey to users "this is a search bar - you can type search queries here". 

Any generic magnifying glass icon will do - we can just load a small SVG one if we don't have Font Awesome in scope here.
