### ISSUE TITLE
Where is the Guide folder?

### ISSUE THREAD

**Issue by willydavidjr** [freeCodeCamp/freeCodeCamp#36729]
**Describe your problem and how to reproduce it:**

I am trying to find the guide folder, but it that I cannot locate it. Was it remove temporarily or relocated to a different section?

**Add a Link to the page with the problem:**

Just take a look on the freeCodeCamp repository main section and and the guide folder is missing.

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 74.0.3729.169 (Official Build) (64-bit)
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![freecodecamp](https://user-images.githubusercontent.com/20619236/64045078-feb22280-cb9a-11e9-8915-16d6bc747080.JPG)

**Comment by raisedadead** [comment]
Yes, the guide has been removed from this repo completely. See: https://github.com/freeCodeCamp/freeCodeCamp/pull/36709

The current production guide at [guide.freecodecamp.org](https://guide.freecodecamp.org), will soon be moved over to our forum as a wiki. 

The changes that were made over the past months will also be added to the forum wiki post migration.

**We are no longer accepting any pull-requests for the guide on this repository.**

Contribution Guidelines for the same will be made available soon. We request your patience.

I am closing this thread, but pinning this for visibility.
