### ISSUE TITLE
Broken test: ES6: Use export to Reuse a Code Block

### ISSUE THREAD

**Issue by RogiNicba** [freeCodeCamp/freeCodeCamp#36738]
**Describe your problem and how to reproduce it:**
There should be two possible ways to pass the test. The instructions point both of them out and say "Either approach is perfectly acceptable.". But the second approach doesn't pass the test.

1.
export const foo = "bar";
export const bar = "foo";
2.
const foo = "bar";
const bar = "foo";
export { foo, bar }

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-export-to-reuse-a-code-block

**Tell us about your browser and operating system:**
* Browser Name: Mozilla Firefox Quantum
* Browser Version: 68.0.2 (64-bit)
* Operating System: Linux Mint 19.2 "Tina"

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by sid995** [comment]
It is clearly written that the code has to be solved by the first option i.e

export const foo = "bar";
export const bar = "foo";

For this specific problem, only the above-stated solution would be correct.

**Comment by RogiNicba** [comment]
Fair enough, it does say to utilize the first way. I still think it would be better if the challenge would allow for both solutions, but due to the current instructions this does not qualify as a broken test. **Please ignore/delete post.**

**Comment by RandellDawson** [comment]
@RogiNicba This challenge has been rewritten but has not yet been released to production.  You can take a look at it [here](https://www.freecodecamp.dev/learn/javascript-algorithms-and-data-structures/es6/use-export-to-share-a-code-block).  If you feel there is still an issue with this challenge, please reply back.  If there are no further issues, please close it.

Thank you.
