### ISSUE TITLE
Night mode localStorage is not used

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#36734]
In the theme is stored using `fcc-theme` in https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/redux/night-mode-saga.js, but I can't find anywhere the stored theme is used.

Presumably it should be checked here: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/components/layouts/Default.js

Sorry to drop this vague hint of an issue, but thought it was worth mentioning and don't have time to investigate further right now!

**Comment by ojeytonwilliams** [comment]
cc: @ahmadabdolsaheb

**Comment by ahmadabdolsaheb** [comment]
Thanks for the issue. It seems like the way to go for themes would be either localStorage or cookies and bringing theme switching to the universal nav, and completely disconnecting it from the DB.

**Comment by raisedadead** [comment]
See https://github.com/freeCodeCamp/freeCodeCamp/issues/36732#issuecomment-533224825
