### ISSUE TITLE
bug(curriculum): Advanced Node Challenges fail when using localhost for url

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#36739]
Not sure if this will actually be a bug once we go to production, but I noticed if I use `http://localhost:3001` (my local running version of the first challenge in the `Advanced Node Challenges`, none of the tests pass and there are several errors in the console.  This also happens when I run everything locally.

Using the same url on the current production site for the same challenge does not fail any of the tests.

I have validated the solution is correct.

![image](https://user-images.githubusercontent.com/5313213/64068967-f8509480-cbf4-11e9-9778-228e3c1254d2.png)

![image](https://user-images.githubusercontent.com/5313213/64068977-3b126c80-cbf5-11e9-99c4-67af6d0c60c3.png)

This is annoying if you are trying to make changes to a challenge to validate the tests are working as they should (without having to run `npm run:test:curriculum`) after every code change while working on challenge tests.

**Comment by RandellDawson** [comment]
**Update:** I used a working Glitch project url for both the beta site and locally and get the same results.

**Comment by raisedadead** [comment]
Curriculum is independent of the release label. That's kept for platform mostly.

**Comment by RandellDawson** [comment]
@raisedadead I added the `release: next/beta` label because this bug is not present in the current production environment.  It has to be something related to the current master.

**Comment by RandellDawson** [comment]
It is all of the curriculum challenges in this section and not just one challenge.  To me, this is a show-stopper and must be fixed before the next release to production.

**Comment by raisedadead** [comment]
Could you reproduce this on the beta site?

**Comment by raisedadead** [comment]
This is a platform issue, which I brought in with https://github.com/freeCodeCamp/freeCodeCamp/commit/56d78a11198a0d244bd131a8b9386b247212c5a1

**Comment by Bouncey** [comment]
Don't be so hard on yourself @raisedadead. It is as @RandellDawson guessed. The CORS in the boilerplate is where the error is coming from.

Currently the boilerplate only excepts requests from `*.freecodecamp.org` domains, hence the CORS error when on `.dev` or running the learn platform locally.

In short, not a blocker for the @next release.

For developing the challenges locally, update the cors in the boilerplate to accept `/https?:\/\/localhost(:\d*)?/`

**Comment by raisedadead** [comment]
#### 🤦‍♂ 

Thanks a ton @Bouncey ! You are life saver. 15 months worth of dev has definitely kept me on the edge for a while. Lol. :)

**Comment by RandellDawson** [comment]
@raisedadead Should we close this?
