### ISSUE TITLE
Challenge "ES6: Use getters and setters to Control Access to an Object" has faulty test conditions

### ISSUE THREAD

**Issue by RogiNicba** [freeCodeCamp/freeCodeCamp#36737]
**Describe your problem and how to reproduce it:**
Despite the instructions requiring one to create a class AND a getter&setter, you can pass the test by just creating the class.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/use-getters-and-setters-to-control-access-to-an-object

**Tell us about your browser and operating system:**
* Browser Name: Mozilla Firefox Quantum
* Browser Version: 68.0.2 (64-bit)
* Operating System: Linux Mint 19.2 "Tina"

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@RogiNicba This challenge has been rewritten to remove the bug you describe. but has not yet been released to production. You can take a look at it [here](https://www.freecodecamp.dev/learn/javascript-algorithms-and-data-structures/es6/use-getters-and-setters-to-control-access-to-an-object). 

I am closing this issue as just waiting to be shipped to production.  If you feel the issue has not been solved on the beta site, you can request for us to reopen this issue. 

Thank you.
