### ISSUE TITLE
Challenge page should indicate if they have already been completed

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/freeCodeCamp#36730]
In the new beta (currently at https://www.freecodecamp.dev), it would be great if a challenge page indicated somehow when the challenge has already been completed. Currently, since user inputed code is not saved, there is no indication on a challenge page that it has already been completed.

**Comment by raisedadead** [comment]
We need a check mark in the title or a badge `completed` or `solved` to indicate the same?

**Comment by moT01** [comment]
The most elegant thing I can think of to have something like the little circular check mark next to the title like how it is on the learn homepage - only if it's been solved, and don't show anything if it hasn't.

**Comment by raisedadead** [comment]
That would be a nice way to handle it. Please go forth if you are interested in this?
