### ISSUE TITLE
[News] Reducing GA Undetermined source/medium

### ISSUE THREAD

**Issue by colbyfayock** [freeCodeCamp/freeCodeCamp#36748]
In GA there's a good amount of traffic thats showing as direct / none for the Source / Medium.

![image](https://user-images.githubusercontent.com/1045274/64137882-95175b80-cdc8-11e9-9569-e63fb820b222.png)

Quick tl;dr: In GA, when something shows as direct / none, it's basically saying it can't determine where the person came from. Here's a good article: https://moz.com/blog/guide-to-direct-traffic-google-analytics 

1 big cause is when a site that's `https` is linking to another site as `http`, which causes the loss of referral data, which is by design for security concerns. I checked that the share links are properly linking to `https` and they are, as well as things like Quincy's weekly email and some links generally on the site. Do you happen to have access logs that might be able to show where traffic is coming from when hitting `http://.../news/`?

One thing that's odd that I noticed, is there are some previous page paths that refer to themselves. I'm not entirely sure what that means though...
![image](https://user-images.githubusercontent.com/1045274/64137828-5c778200-cdc8-11e9-8b48-653f7fd804ea.png)

Anyways, I'm having a hard time trying to figure out the main cause(s).

**Comment by colbyfayock** [comment]
While here, can we get GTM `<noscript` added? i dont think this will have any impact here, but noticed it while trying to debug the above:
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5D6RKKP"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```
This snippet can be found in GTM > Admin > Install Google Tag Manager. Should go right after the opening `<body>` tag.

**Comment by raisedadead** [comment]
Hi @colbyfayock! 

I have added you to @freeCodeCamp and given you the mod privileges. You should now be able to triage and assign these issues to the @freeCodeCamp/dev-team

**Comment by raisedadead** [comment]
> While here, can we get GTM `<noscript` added? i dont think this will have any impact here, but noticed it while trying to debug the above:
> 
> ```
> 
> <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5D6RKKP"
> height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
> 
> ```
> 
> This snippet can be found in GTM > Admin > Install Google Tag Manager. Should go right after the opening `<body>` tag.

I have injected this to the body, unfortunately we do not have much control over the placement of the snippet (right after the opening `<body>` tag)

**Comment by colbyfayock** [comment]
awesome, thanks @raisedadead
