### ISSUE TITLE
Unclear instructions: Regular Expressions: Restrict Possible Usernames

### ISSUE THREAD

**Issue by RogiNicba** [freeCodeCamp/freeCodeCamp#36741]
**Describe your problem and how to reproduce it:**
Getting past the challenge one is required to specify the upper number of matches, something that you learn for the first time three challenges later in the lesson "Regular Expressions: Specify Upper and Lower Number of Matches". "Get a hint" section also references the solution that hasn't been introduced yet.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/restrict-possible-usernames/

**Tell us about your browser and operating system:**
* Browser Name: Firefox Quantum
* Browser Version: 68.0.2 (64-bit)
* Operating System: Linux Mint 19.2 "Tina"

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by alanpaulprice** [comment]
@RogiNicba This challenge doesn't require an upper and lower number of matches to be specified.

The following passes: `/[a-z]+[a-z]+[0-9]*/i`

**Comment by RandellDawson** [comment]
This issue was resolved.  The hints and solutions forum topic for this challenge includes another solution that does not user a quantifier.
