### ISSUE TITLE
The Solution in Get a hint for Sort an Array Alphabetically Using the Sort Method is not correct.

### ISSUE THREAD

**Issue by mzkev** [freeCodeCamp/freeCodeCamp#36759]
<!-- 
The Solution in Get a hint for Sort an Array Alphabetically Using the Sort Method is not correct.
It is supposed to be 
function alphabeticalOrder(arr) {
  // Add your code below this line
  return arr.sort();
  
  // Add your code above this line
}

alphabeticalOrder(["a", "d", "c", "a", "z", "g"]);

Instead of this 
function alphabeticalOrder(arr) {
  // Add your code below this line
  return arr.sort(function(a,b) {
    return a > b;
  });
  // Add your code above this line
}
alphabeticalOrder(["a", "d", "c", "a", "z", "g"]);

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method/

**Tell us about your browser and operating system:**
* Browser Name:  Chrome
* Browser Version: 
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/25280476/64316562-1af3fc00-cfad-11e9-99bf-fbaf1e1a23f4.png)

**Comment by moT01** [comment]
Both, the solution in the [production guide](https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method), and the [forum guide](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-sort-an-array-alphabetically-using-the-sort-method/18303), passed for me - can you test them again @mzkev - or clarify what one isn't passing, and where you are testing it.

**Comment by mzkev** [comment]
The Solution in the Get a hint link is this 
function alphabeticalOrder(arr) {
  // Add your code below this line
  return arr.sort(function(a,b) {
    return a > b;
  });
  // Add your code above this line
}
alphabeticalOrder(["a", "d", "c", "a", "z", "g"]);

Which isn't correct, when you run it it gives error. Please see the screenshot below.
![image](https://user-images.githubusercontent.com/25280476/64343525-97ee9800-cfe4-11e9-9a49-ce9ac7bfcea4.png)

It is supposed to be 
function alphabeticalOrder(arr) {
  // Add your code below this line
  return arr.sort();
  // Add your code above this line
}
alphabeticalOrder(["a", "d", "c", "a", "z", "g"]);

And all the Test cases passes.

**Comment by mzkev** [comment]
@moT01

**Comment by moT01** [comment]
The guide with that solution will be removed soon and replaced with forum guide posts - I linked to the post about this challenge on my last comment. If one of the forum posts needs updating, we take suggestions via replies to the post. So the solution you are referring to will be gone soon - the solution on the forum is different - I was able to pass the challenge with both of them.

<img width="1369" alt="Screen Shot 2019-09-05 at 8 02 17 AM" src="https://user-images.githubusercontent.com/20648924/64344640-7b3a6c00-cfb4-11e9-984a-3fd7dadb45e3.png">

**Comment by Ieahleen** [comment]
@moT01 : the `a > b` callback works only on some browsers since about last October, it is going to be removed from the guide because of that

**Comment by RandellDawson** [comment]
I am closing this issue as we are just waiting for master to be shipped to production.  Also, the [new Guide (on the forum)](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-sort-an-array-alphabetically-using-the-sort-method/18303) has the correct solution.
