### ISSUE TITLE
Issue in JS Challenge Description of: Use Prototype Properties to Reduce Duplicate Code...

### ISSUE THREAD

**Issue by albert-codestein** [freeCodeCamp/freeCodeCamp#36754]
**Describe your problem and how to reproduce it:**
On the 3rd paragraph in the challenge description frame on the left a **prototype** is defined as an object. While this may be true for true object oriented languages like C#.net it may not be true in this context and confuse the reader.

The paragraph in question is given below and I added the necessary addition in bold:
"A better way is to use Bird’s prototype. The prototype is an object **property** that is shared among ALL instances of Bird. "

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/object-oriented-programming/use-prototype-properties-to-reduce-duplicate-code/

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 76.0.3809.132 (Official Build) (64-bit)
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![prototype_is_a_property](https://user-images.githubusercontent.com/54712685/64261921-4b7b5d80-cefb-11e9-8d82-3756c41e1368.png)

**Comment by albert-codestein** [comment]
Nope, the prototype is really an object in this case too so I am closing this :)

**Comment by albert-codestein** [comment]
This is still confusing as objects also have prototype as a property, explaining this in the challenge description might really help others so I am reopening this.

**Comment by moT01** [comment]
I think it's fine - what would you like to see here @albert-codestein?
