### ISSUE TITLE
Loader component should wrap the full application

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#36757]
![2019-09-04 23 47 20](https://user-images.githubusercontent.com/1884376/64280409-b023d000-cf6e-11e9-95ad-ba10140f0331.gif)

---

The above will let the signin pass thru to the API, even when the user is already signed in and loading.

The navbar including signin button should be wrapped in the loaded component

**Comment by Bouncey** [comment]
You could disable the sign in button until it is known that the user is signed in or not?

**Comment by ahmadabdolsaheb** [comment]
The Sign-in button will be completely removed from navigation with #36744

**Comment by raisedadead** [comment]
> The Sign-in button will be completely removed from navigation with #36744

The problem is people would still be able to redirect to `/api/signin` without getting the userstate first.

**Comment by ojeytonwilliams** [comment]
Perhaps related, no loader appears at all:
![ProfileLoader](https://user-images.githubusercontent.com/15801806/65672430-5718fa80-e049-11e9-9b84-4f03d545caff.gif)

**Comment by raisedadead** [comment]
Yes, it's quite messy at the minute. And we have a very bad page load time for the same reason.

I think we would need to remove the full page loader from the landing page and just keep it on the buttons (components) that actually change based on the user.

I would love to do skeletons as well.
