### ISSUE TITLE
Need add new challengers about important array method ( map filter reduce) and callback Function, recursive also

### ISSUE THREAD

**Issue by maxiqboy** [freeCodeCamp/freeCodeCamp#36753]
**Describe your problem and how to reproduce it:**

Map() Filter() and Reduce() are quite advanced but FreeCodeCamp doesnt have any lesson about it, but it appeared a lot on the challenges.

Also is callback function, and recursive - as far as I remember - there is no specific challenge for them,

**Comment by Ieahleen** [comment]
`map()`
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/use-the-map-method-to-extract-data-from-an-array
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype

`filter()`
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/use-the-filter-method-to-extract-data-from-an-array
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/implement-the-filter-method-on-a-prototype

`reduce()`
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/use-the-reduce-method-to-analyze-data

callback
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/understand-functional-programming-terminology

**Comment by moT01** [comment]
Some [lessons covering recursion](https://www.freecodecamp.dev/learn/javascript-algorithms-and-data-structures/basic-javascript/use-recursion-to-create-a-range-of-numbers) were added as well - they will be available the next time we push our code to production. So I don't think there's an issue here. If you're satisfied with these you can probably close this @maxiqboy.

**Comment by maxiqboy** [comment]
> `map()`
> https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/use-the-map-method-to-extract-data-from-an-array
> https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype
> 
> `filter()`
> https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/use-the-filter-method-to-extract-data-from-an-array
> https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/implement-the-filter-method-on-a-prototype
> 
> `reduce()`
> https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/use-the-reduce-method-to-analyze-data
> 
> callback
> https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/functional-programming/understand-functional-programming-terminology

they are not in basic section, they are in advanced section, and FCC are not tell much detail about them,
Learner had to use them in challenges without understand exactly about them.
That what I asked.

**Comment by maxiqboy** [comment]
> Some [lessons covering recursion](https://www.freecodecamp.dev/learn/javascript-algorithms-and-data-structures/basic-javascript/use-recursion-to-create-a-range-of-numbers) were added as well - they will be available the next time we push our code to production. So I don't think there's an issue here. If you're satisfied with these you can probably close this @maxiqboy.

I will take a look on the new lesson, thanks,

**Comment by Ieahleen** [comment]
is it about the challenge in the es6 section? it has been removed from there so you meet first the challenges I linked above, you will see the change live with next curriculum update

**Comment by maxiqboy** [comment]
> is it about the challenge in the es6 section? it has been removed from there so you meet first the challenges I linked above, you will see the change live with next curriculum update

I don't know, but when I studied on FCC last month, I met the challenges you linked above, 

These challenges are quite complicated.

I realise that maybe map filter reduce methods are important parts but I saw no basic lesson about them.

I have to search outside and studied outside also,

So I opend this issue hope the next curriculum will update some basic lesson about them

so the new campers come after me can get the idea easily without feeling lost like me before.

Thanks,

**Comment by RandellDawson** [comment]
FCC is not meant to be a comprehensive curriculum.  At some point, campers are expected to research outside and learn to read the docs on the various methods.  That being said, when the updated curriculum is release (soon), we have rearranged some of the lessons, so certain challenges are not introduced until map, filter, and reduce have at least been mentioned.

At this point, we will not be creating any new challenges on the existing curriculum.  The new curriculum being worked on would be the best place to put such lessons.

**Comment by moT01** [comment]
Thanks for the suggestions here everyone. We are not looking to add any new challenges to curriculum at this point.
