### ISSUE TITLE
Every click on the Menu List(Side Panel) in guide.freecodecamp.org scrolls to top of the page instead of staying at the same spot of click

### ISSUE THREAD

**Issue by electronsrace** [freeCodeCamp/freeCodeCamp#36758]
**Describe your problem and how to reproduce it:**
Steps to Reproduce the Issue
1. Launch a Browser
2. Navigate to https://guide.freecodecamp.org/
3. Click on the Side panel Link, Ex: Click on Java
</br><b>Expected Behavior</b>: Sub-Menus of the Java Link should be expanded and displayed
</br><b>Actual Behavior</b>: Side panel containing menus scrolls to top of the page and Hence could not see the Java or its expanded menus
</br><b>Observation</b>: In Order to see the clicked Menu or its submenus, We need to manually scroll the left side scroll bar to the particular link which has been clicked.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 76.0.3809.100 (Official Build) (64-bit)
* Operating System: Windows 7

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by raisedadead** [comment]
Thanks for the report, unfortunately this will be a `wontfix`, as per https://github.com/freeCodeCamp/freeCodeCamp/issues/36729#issuecomment-526714451
