### ISSUE TITLE
Green checkmarks not appearing in HelmetJS section

### ISSUE THREAD

**Issue by quietplace** [freeCodeCamp/freeCodeCamp#36762]
I’ve finished the Information Security with HelmetJS section and passed all the tests and submitted but when I go to the curriculum page none of the green checkmarks are appearing?? I’ve tried logging out and in again. I have also tried reentering the link into each lesson several times.
Have tested in both Chrome and Firefox

**Comment by RandellDawson** [comment]
Have you asked for help on the forum?  If not, please try there first.  If the users there think there is a bug in the tests and not just your code, please feel free to request this issue to be reopened.  Also, please refer to the forum post you create if you would like us to reopen this issue.

Thank you.

**Comment by quietplace** [comment]
Ok thanks I'll try the forum then
