### ISSUE TITLE
Audit and update styles for error, info and warning, etc.

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#36763]
![image](https://user-images.githubusercontent.com/1884376/64418135-19632a80-d0b8-11e9-88ce-e7a26206e540.png)

**Comment by Hardik500** [comment]
So we need to update the the styles for the errors, warnings etc. right?

**Comment by raisedadead** [comment]
And add/update tests for these too.

**Comment by danesh4545** [comment]
در تاریخ جمعه ۱۵ شهریور ۱۳۹۸ ه‍.ش.،‏ ۲۳:۱۱ Hardik Khandelwal <
notifications@github.com> نوشت:

**Comment by Hardik500** [comment]
If it is not a problem, could you please mention the directories that need to changed.

**Comment by HERBOD7** [comment]
@raisedadead I can do it.

**Comment by raisedadead** [comment]
Hi Guys, thanks a lot for your interest. BUt I figured out this is not very trivial of issue to start with. I have assigned this to @ahmadabdolsaheb instead.

Please go thru some of the other help wanted issues.

Thanks and happy contributing.
