### ISSUE TITLE
Delete supporters.js component?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36764]
[In this folder](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/client/src/components) - I don't think `supporters.js` and `supporters.css` are being used anywhere anymore - Everything is redirected to /news/support I believe. Should/can they be deleted?

Edit: Looks like [this file](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/pages/software-resources-for-nonprofits.js) isn't being used either.

**Comment by ahmadabdolsaheb** [comment]
correct, support component gotta go.
software-resources-for-nonprofits is a page; however, it is not publicized anywhere.
let me double check on that and make sure we add it to the list of redirects before deleting it.

**Comment by ahmadabdolsaheb** [comment]
The software-resources-for-nonprofits was just migrated to news.
I will take care of deleting all of the above-mentioned files. 

@raisedheaded, sorry just saw your comment
https://github.com/freeCodeCamp/freeCodeCamp/issues/36622#issuecomment-527452773

would you still like to have /welcome redirect to  /  on the client side?

Also could you please redirect the following as well
/software-resources-for-nonprofits
/news/software-resources-for-nonprofits/

Thank you

**Comment by raisedadead** [comment]
> would you still like to have /welcome redirect to / on the client side?

I already added this to the redirects generator. If there something that needs to be done on the Gatsby end of things, I would like you to audit and check.

> Also could you please redirect the following as well

I think you should be able to add this to the ref to the generator on your PR, and we can land it as well? Let me know if you need help?

**Comment by ahmadabdolsaheb** [comment]
@raisedadead thanks for the feedback.  the ref generator was updated accordingly in #36778
