### ISSUE TITLE
Prevent comment-less Developer News forum threads

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#36766]
It is currently possible to create a forum comment thread for a Developer News article without leaving a comment.

For example, this thread has not actual comments in it, and merely represents noise when browsing News comments.

<img width="1022" alt="Start_from_Square_Zero__Hidden_Habits_You_Need_for_a_Successful_Career_in_Tech_-_News_Comments_-_The_freeCodeCamp_Forum" src="https://user-images.githubusercontent.com/985197/64480099-20a53980-d187-11e9-9957-01d428c35c60.png">

Currently these threads have to be suppressed due to all the noise these comment-less threads produce. Once we fix this, we will be able to start showing comments in the latest view and they will be more widely read.

**Comment by raisedadead** [comment]
Hi Quincy, I do not think this is possible at the minute, we use a script that is provided by discourse itself (just like a GA script). 

We do not control the code for the same.
