### ISSUE TITLE
Landing page photo should be an SVG

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#36777]
the logo asset should be vectorized and turned to a component similar to other assets so we could change its color according to the theme and would not need to load it from the CDN

Samples
https://github.com/freeCodeCamp/freeCodeCamp/tree/master/client/src/assets/icons

![image](https://user-images.githubusercontent.com/4591597/64601600-e7a6d800-d3c5-11e9-827e-9ba234101353.png)

**Comment by raisedadead** [comment]
Closing, as requirement change.
