### ISSUE TITLE
301 Redirect testimonials page to LinkedIn alumni page

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#36779]
I didn't realize this page was still live on freeCodeCamp. It hasn't been updated in about 4 years: https://www.freecodecamp.org/all-stories

We should point this to our LinkedIn alumni page: https://www.linkedin.com/school/free-code-camp/people/

**Comment by raisedadead** [comment]
Hi @QuincyLarson I think we decided to redirect it home long back. 

Here is the redirect generator file that we use to track and redirect our old pages:

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/tools/scripts/build/create-redirects.js

Can you confirm this is in order?

**Comment by QuincyLarson** [comment]
@raisedadead This looks perfect. Thanks for confirming this.
