### ISSUE TITLE
Broken Test: Basic JavaScript Nesting For Loops

### ISSUE THREAD

**Issue by JohnBaumlin** [freeCodeCamp/freeCodeCamp#36773]
**Describe your problem and how to reproduce it:**
The Basic Javascript Nesting For Loops can pass all their criteria while doing it incorrectly. 
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/nesting-for-loops

You can solve the problem with the following **fundamentally incorrect** code: 

```
function multiplyAll(arr) {
  var product = 1;

  for (var i = 0; undefined !== arr[i] && i < arr.length; i++) {
      for (var k = 0; undefined !== arr[i][k] && k <= arr[k].length; k++){ 
       product *= arr[i][k];  
      }
  }
  // Only change code above this line
  return product;  
}

```
I believe this is an easy mistake to make. 

To fix, simply increase the amount of array items in the third test from:
`multiplyAll([[5,1],[0.2, 4, 0.5],[3, 9]])
`
To: 
`multiplyAll([[5,1],[0.2, 4, 0.5, 5],[3, 9]]) 
`

Then only the correct nested loop will succeed the test.

**Comment by moT01** [comment]
This does not look like an easy mistake to make. I don't think anyone is going to be adding multiple conditions in a for loop test like this. There is often going to be a way to pass the tests with bad code, I don't think we can catch all of them.

Here's another function that will pass all the tests...
```
function multiplyAll(arr) {
  return arr[1][0] === 2 ? 6 : arr[1][0] === 3 ? 5040 : 54;
}
```

**Comment by JohnBaumlin** [comment]
> This does not look like an easy mistake to make. I don't think anyone is going to be adding multiple conditions in a for loop test like this. There is often going to be a way to pass the tests with bad code, I don't think we can catch all of them.
> 
> Here's another function that will pass all the tests...
> 
> ```
> function multiplyAll(arr) {
>   return arr[1][0] === 2 ? 6 : arr[1][0] === 3 ? 5040 : 54;
> }
> ```

Hmm... I see what you mean about bad code, but that's quite a specific way "around" the test, clearly manipulating the test values, and this test comes before the Ternary operator is taught. 

Not understanding what should go in the second conditional, arr[k].length or arr.length or arr[i].length seems like an intuitive error that can happen, and we can proof against this error on the student's part by by increasing the size of the test array. Because the arrays are length 2, the student can incorrectly use arr[k].length, and switching to <= for the nested arr[k].length on the final test may give the student the impression they "succeeded," but instills an incorrect fundamental regarding array element counting. 

I am reviewing the fundamentals and this was my experience until I did extra testing. I hope it can be improved by adding an additional element to the test array for any student who may experience the same.

**Comment by moT01** [comment]
Accidentally using `k <= arr[k].length` or something like it in the second loop is a mistake people would make, but that won't pass the tests. It only passes the tests because you added `undefined !== arr[i][k]` in the condition as well - which is something nobody is going to add.

Increasing the test array won't change the result for someone that uses `k <= arr[k].length` - it won't pass either way and it won't shed any light on why their code doesn't work.

I dunno - maybe I'm misunderstanding what you are getting at.

**Comment by ElPomodorro** [comment]
> > This does not look like an easy mistake to make. I don't think anyone is going to be adding multiple conditions in a for loop test like this. There is often going to be a way to pass the tests with bad code, I don't think we can catch all of them.
> > Here's another function that will pass all the tests...
> > ```
> > function multiplyAll(arr) {
> >   return arr[1][0] === 2 ? 6 : arr[1][0] === 3 ? 5040 : 54;
> > }
> > ```
> 
> Hmm... I see what you mean about bad code, but that's quite a specific way "around" the test, clearly manipulating the test values, and this test comes before the Ternary operator is taught.
> 
> Not understanding what should go in the second conditional, arr[k].length or arr.length or arr[i].length seems like an intuitive error that can happen, and we can proof against this error on the student's part by increasing the size of the test array. Because the arrays are length 2, the student can incorrectly use arr[k].length, and switching to <= for the nested arr[k].length on the final test may give the student the impression they "succeeded," but instills an incorrect fundamental regarding array element counting.
> 
> I am reviewing the basics before moving onto ES6, and this was my experience until I did extra testing. I hope it can be improved by adding an additional element to the test array for any student who may experience the same.

What's about adding hidden test case?

**Comment by moT01** [comment]
I don't think there's an issue here. Does anyone else want to share their opinion on this?

**Comment by ojeytonwilliams** [comment]
This code behaves as it should, it's just weird.  I wouldn't recommend writing code like that, but checking to see if an array element is undefined or checking to see if you've gone past the end of an array amount to the same thing.  Assuming, of course, that your arrays don't have `undefined` as elements, which is a perfectly reasonable assumption here.
