### ISSUE TITLE
The landing page should be improved

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#36775]
The landing page should undergo the following changes:

1. whitespace should be managed in a way that the last bullet point stays above fold.
2. add the text "As seen in:" centered and above the logos image
3. give margin/padding to the bullet points  so they are vertically aligned with the title of the page to be as same as the CTA button.

4.  Minimize text wrapping for smaller screens.

![image](https://user-images.githubusercontent.com/4591597/64601804-48361500-d3c6-11e9-8b4e-c3c99f7c3c2a.png)

![image](https://user-images.githubusercontent.com/4591597/64563680-9b717e80-d358-11e9-8bfa-a3bb7b58320a.png)

**Comment by matoval** [comment]
I just finished this in gitpod. This is my first time working on open source and first time working in react but I believe I have fixed the issues.

**Comment by thecodingaviator** [comment]
While we're at it
![image](https://user-images.githubusercontent.com/34807532/64858189-4da09300-d644-11e9-8728-b052910cb06c.png)

Should we make the list to be centred for mobile layouts?

**Comment by thecodingaviator** [comment]
@ahmadabdolsaheb In point 3, do you want the OP for the PR to make the bullets align with the title AND the CTA or only to the title like how the PR currently looks?

![image](https://user-images.githubusercontent.com/34807532/64858359-bab42880-d644-11e9-9273-c2cf667ab80e.png)

**Comment by Hardik500** [comment]
How about this one?
![Screenshot (5)](https://user-images.githubusercontent.com/28431356/64883874-f8817300-d67d-11e9-9fb2-27a558123a77.png)

**Comment by QuincyLarson** [comment]
What do you all think about removing the compound sentences and breaking it into more lines:

Learn to code.
Build projects.
Earn certifications.
Grow your portfolio.
Get a developer job.

[ Sign in and get started (it's free) ]

**Comment by Hardik500** [comment]
> What do you all think about removing the compound sentences and breaking it into more lines:
> 
> Learn to code.
> Build projects.
> Earn certifications.
> Grow your portfolio.
> Get a developer job.
> 
> [ Sign in and get started (it's free) ]

I think it will look great. It is quite precise and to the point.

**Comment by thecodingaviator** [comment]
@QuincyLarson That'll be too long on the page IMO. What we can do is, make it a rorating thing, as in first, the first point is available, which then fades to reveal the second and so on
