### ISSUE TITLE
Incorrect text for test cases in Balanced Brackets question

### ISSUE THREAD

**Issue by James-Crean** [freeCodeCamp/freeCodeCamp#36774]
Many of the test cases on the balanced brackets challenge state incorrect expectations. For example `isBalanced("][")should return true.`. There are many similar test cases like this.

The tests themselves seem to be correct despite the html text. It is worth noting however, that the test cases are missing at least one case that should be added. Please consider adding `isBalanced("[]]]")should return false.`  

This case covers instances where:
1. A stack approach is used to solve the problem.
2. The programmer checks for an even number of characters before iterating.  
3. The programmer does not check for an empty stack before calling `.pop()`

Example student code where the current tests pass but this case would fail:
```js
function isBalanced(str) {
    let matched = [];
    if (str.length == 0) {
        return true;
    } else if (str.length % 2 != 0) {
        return false;
    } else {
        for (let i = 0; i < str.length; i++) {
            if (str[i] == "[") {
                matched.push(str[i]);
            } else {
                matched.pop();
            }
        }
        if (matched.length !== 0) {
            return false;
        }
        return true;
    }
}
```

Page with problem: https://learn.freecodecamp.org/coding-interview-prep/rosetta-code/balanced-brackets/

**Tell us about your browser and operating system:**
* Browser Name: Chrome 
* Browser Version: 76.0.3809.100 (Official Build) (64-bit)
* Operating System: MacOS 10.13.6

**Comment by moT01** [comment]
Why would we want to add this test `isBalanced("[]]]")should return true` @James-Crean? - seems like that should be false to me. Also - I'm sure why that code should fail, seems like it should work.

**Comment by James-Crean** [comment]
Woops. I made the same mistake I'm reporting, lol. I have corrected the mistake.

The test case covers a corner case that multiple students missed but is not detected by the current tests.

The problem with the code above is that it does not check if `matched` is empty before calling `pop`. 

The current tests, such as `isBalanced("[[][]]][") should return false.` end up not catching this issue because they have an odd number of brackets, and students intuitively end up checking for that first.

**Comment by RandellDawson** [comment]
@James-Crean So do you have a test case (that does not exist yet) that would wrongly pass or wrongly fail the existing tests?

**Comment by moT01** [comment]
It's an edge case - he's saying that his code/strategy passes the current tests, but would fail his suggested test addition (`isBalanced("[]]]"`) because of the push/pop strategy. I doubt that this is a frequent problem, but since this challenge needs its test text updated - we can probably change one of the tests to accommodate this in the process.

I think we should change one of the existing tests instead of adding another one... and maybe even remove several of them, since there are 19 tests on this challenge.

**Comment by RandellDawson** [comment]
> I think we should change one of the existing tests instead of adding another one... and maybe even remove several of them, since there are 19 tests on this challenge.

@James-Crean Would you want to suggest a change for one of the tests?

**Comment by moT01** [comment]
the ninth from the top... `isBalanced("[[][]]][") should return true.` - removing the last `[` should catch the cases he is referring to - so it would become `isBalanced("[[][]]]") should return false`.
