### ISSUE TITLE
Write a Simple Counter: Preview failing to update, tests are passing

### ISSUE THREAD

**Issue by paintedskies** [freeCodeCamp/freeCodeCamp#36782]
**Describe your problem and how to reproduce it:**
I have added increment and decrement functions as per instruction, and it passes all tests and  lets me go to the next page.However, in the preview, clicking on increment and decrement doesn't update the count.
Modified code:
```
class Counter extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0
    };
    // change code below this line
  this.increment = this.increment.bind(this);
   this.decrement = this.decrement.bind(this);
     this.reset = this.reset.bind(this);
    // change code above this line
  }
  // change code below this line
  increment(){
    this.state.count = this.state.count + 1;
  }
  decrement(){
    this.state.count = this.state.count - 1;
  }

  reset(){
    this.state.count = 0;
  }
  // change code above this line
  render() {
    return (
      <div>
        <button className='inc' onClick={this.increment}>Increment!</button>
        <button className='dec' onClick={this.decrement}>Decrement!</button>
        <button className='reset' onClick={this.reset}>Reset</button>
        <h1>Current Count: {this.state.count}</h1>
      </div>
    );
  }
};
```
**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/front-end-libraries/react/write-a-simple-counter/

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Chrome 76
* Operating System: Windows 10
![bug](https://user-images.githubusercontent.com/17096397/64766416-012b5980-d557-11e9-925c-1e9277cfe67c.PNG)

**Errors in Console**
(index):1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://js.stripe.com') does not match the recipient window's origin ('https://learn.freecodecamp.org').

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@jzabala Sure, go ahead and create a PR.

**Comment by jzabala** [comment]
Hi, I already did the corrections in the file `write-a-simple-counter.english.md`. Now I want to apply the fixes to the other languages but I am having a hard time change the language of the site. I have tried:

http://localhost:8000/learn/front-end-libraries/react/write-a-simple-counter
http://localhost:8000/learn/front-end-libraries/react/write-a-simple-counter
http://localhost:8000/learn/front-end-libraries/react/write-a-simple-counter
http://localhost:8000/learn/front-end-libraries/react/write-a-simple-counter
http://localhost:8000/learn/front-end-libraries/react/write-a-simple-counter
http://localhost:8000/learn/front-end-libraries/react/write-a-simple-counter

**Comment by RandellDawson** [comment]
Don't worry about the other languages.  They will not be deployed to production in the next release.

**Comment by jzabala** [comment]
Awesome. Thanks @RandellDawson. PR created :D
