### ISSUE TITLE
404 encountered when clicking 'Go to the coding curriculum' from www.freecodecamp.org

### ISSUE THREAD

**Issue by kairstenfay** [freeCodeCamp/freeCodeCamp#36790]
**Describe the bug**
When I'm logged in at www.freecodecamp.org and click on the button, 'Go to the coding curriculum', I encounter a 404 error page with the browser URL containing `https://learn.freecodecamp.org/front-end-libraries/react/use-array.filter-to-dynamically-filter-an-array`. 

**To Reproduce**
1. Be logged in at www.freecodecamp.org
2. Click on the button 'Go to the coding curriculum'
3. Open up browser tools and enable XHR logging
4. See errors

**Expected behavior**
I expect the 'Go to the coding curriculum' button to redirect me to learn.freecodecamp.org

**Screenshots**
![image](https://user-images.githubusercontent.com/11384464/64905283-ad219180-d68a-11e9-8514-73aed33c6ff6.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Firefox
 - Version: 69.0

**Comment by RandellDawson** [comment]
Thank you for reporting this issue, but it has already been fixed on our master branch and just waiting for the master branch to be deployed to production.  I am closing this issue for now as there is nothing else to do except wait for production to be updated.
