### ISSUE TITLE
Typo in uncomment-html page

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#36794]
There's a subject-verb agreement error in the text. "Starts with" should be "start with" 

<img width="502" alt="Learn_Basic_HTML_and_HTML5__Uncomment_HTML___freeCodeCamp_org" src="https://user-images.githubusercontent.com/985197/64925920-05f14700-d7bd-11e9-9d26-ef2c882e3bc9.png">

**Comment by robertholl** [comment]
Good find.  Were you planning to make the correction or reporting for someone else to correct?  If you aren't I can correct and submit a pull request.

**Comment by RandellDawson** [comment]
@QuincyLarson Question: Do we actually need the comma before the phrase ` and ends with a ...`?

**Comment by QuincyLarson** [comment]
@RandellDawson Nice catch. We don't need that comment either. In such a sentence a comma would be optional, but here it looks kind of awkward following the code block.
