### ISSUE TITLE
How we can fix News comments and article sharing

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#36796]
Currently Developer News comments are an embedded forum page.

Instead of embedding these, we should just do [what BoingBoing does](https://boingboing.net/2019/09/13/omission-commission.html) with their Discourse integration:

![Penetration_testers_jailed_after_they_broke_into_a_courthouse_to_test_its_physical_security___Boing_Boing](https://user-images.githubusercontent.com/985197/64926546-39839f80-d7c4-11e9-969d-f3f28cb9329a.jpg)

At the bottom of their articles it says "N comments" or if there are no comments, "Leave a comment"

This is much simpler than the slow embed functionality we currently have, and it will look a lot cleaner.

I'm closing https://github.com/freeCodeCamp/freeCodeCamp/issues/36612 in favor of discussing this simpler solution here.

While we're looking at BoingBoing, another thing they do right is their social share buttons. 

We can also remove our giant "Tweet this" and "share this on Facebook" buttons (at the top and bottom of our News articles) and go with BoingBoing's more simple "Share" and "Tweet" buttons at the bottom of each article, which use the colors that correspond to these platforms. These are simple and relatively self-explanatory.

The "email this" functionality is nice but I don't think it's important enough to have a dedicated button for, so we can remove it.

**Comment by ahmadabdolsaheb** [comment]
Note: we could have a big bolded sentence at the end of each article that says this:

Did this article help you? Share it on [Twitter](twitter link) or [Facebook](facebook link). And [Leave a comment](comment page).

**Comment by ahmadabdolsaheb** [comment]
For my reference: 
 
https://meta.discourse.org/t/embedding-but-dont-automatically-create-a-topic-until-a-user-chooses-to-comment/61450/54

https://meta.discourse.org/t/paid-preference-to-create-embed-a-topic-via-javascript-only-when-a-user-clicks-the-start-discussion-link/78593/6

**Comment by colbyfayock** [comment]
@ahmadabdolsaheb is there a reason not to immediately create a topic on post creation? won't that prevent folks who come via the forum from finding new content and interacting with it?

**Comment by ahmadabdolsaheb** [comment]
@colbyfayock. we will have that functionality, and we need to have more granular control than what the current embed offers that is why we are planning to create our own.

**Comment by raisedadead** [comment]
We have been using twitter instead of the forum to discuss the articles. This way we have more engagement on the article as well.

**Comment by QuincyLarson** [comment]
@colbyfayock I agree that for now we can leave comments off, as moderating these also takes a lot of work, and discussions around these articles tend to be sparse. Once we release our updated /news client (which will most likely still use Ghost as the CMS for authors, but will use Gatsby for a headless Ghost rendering of the pages). And when we release that, we can add comments and some sort of centralized tool for moderating them.
