### ISSUE TITLE
Broken link - Basic Data Structures: Generate an Array of All Object Keys with Object.keys()

### ISSUE THREAD

**Issue by clarkngo** [freeCodeCamp/freeCodeCamp#36798]
**Describe your problem and how to reproduce it:**
When you click **Get a Hint**, it redirects to a 404 page.

Need to change this url:
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/generate-an-array-of-all-object-keys-with-object-keys/

to this working url:
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-data-structures/generate-an-array-of-all-object-keys-with-object.keys/

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-data-structures/generate-an-array-of-all-object-keys-with-object-keys

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 77.0.3865.75
* Operating System: MacOS Mojave 10.14.2

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/30854108/64926650-bc9cf980-d7b4-11e9-9d24-110a0a006ee9.png)

**Comment by RandellDawson** [comment]
@clarkngo This issue has been resolved on the master branch.  We are just waiting for it to be shipped to production.

**Comment by clarkngo** [comment]
Thank you @RandellDawson
