### ISSUE TITLE
Add comments to Ghost pages

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#36809]
Currently Ghost pages do not have comments. Is it possible to add comments to Ghost pages?

**Comment by raisedadead** [comment]
Hi @QuincyLarson,

Comments on pages can be enabled by adding this snippet from the `posts` view to the `pages` view:

https://github.com/freeCodeCamp/news-theme/blob/793b187920de52d09672c043f24fb9fede2c35ce/post.hbs#L88-L122

https://github.com/freeCodeCamp/news-theme/blob/master/page.hbs#L37

That said, do we want to filter certain pages from having the comment snippet? For instance, I think we should probably not want the snippet on About, ToS, etc?

**Comment by QuincyLarson** [comment]
@raisedadead OK - awesome. 

Yes - these comments will be helpful. We can use that same "Tweet / Share / Comments" component we're going to use on the News posts. 

The only pages I don't think we want comments on are:
About
Sponsors
Academic Honesty
Code of Conduct
Privacy Policy
Terms of Service
Copyright Policy

I think every other page can have them no problem.

**Comment by scissorsneedfoodtoo** [comment]
Comments are now available on all pages that do not have the "Disable Comments" internal tag. Internal tags are different than normal tags in that they don't render to the page, even if a user accidentally adds it to a post. Also, there is no tag page for internal tags -- https://www.freecodecamp.org/news/tag/disable-comments/ leads to a 404.

I've gone through and added the "Disable Comments" tag to the pages listed above. All other pages should have a comments section now.
