### ISSUE TITLE
Code is said to be not working inspite of fulfilling all tests

### ISSUE THREAD

**Issue by nodnops164** [FreeCodeCamp/FreeCodeCamp#3680]
Challenge [Bonfire: Seek and Destroy](http://freecodecamp.com/challenges/bonfire-seek-and-destroy#?solution=function%20destroyer(arr)%20%7B%0A%20%20%2F%2F%20Remove%20all%20the%20values%0A%20%20%2F%2Fconsole.log(arguments)%3B%0A%20%20var%20arr1%20%3D%20arguments%3B%0A%20%20console.log(arr1.length)%3B%0A%20%20var%20i%20%3D1%3B%0A%20%20var%20filtered%20%3D%200%3B%0A%20%20%20%20while(i%20%3C%20arr1.length-1)%7B%0A%20%20filtered%20%3D%20arr.filter(function%20x(element%2Cindex%2Carray)%7B%0A%20%20%20%2F%2F%20console.log(arguments)%3B%0A%20%20%20%20%20%20return%20element%20!%3D%20arr1%5Bi%5D%3B%0A%20%20%7D)%3B%0A%20%20%20%20%20%20arr%20%3D%20filtered%3B%0A%20%20%20%20%20%20i%2B%2B%3B%0A%20%20%7D%0A%20%20%2F%2Fconsole.log(arguments)%3B%0A%20%20return%20filtered%3B%0A%7D%0A%0Adestroyer(%5B1%2C2%2C3%2C4%2C7%2C1%2C2%2C5%2C8%5D%2C1%2C2%2C5%2C3%2C4%2C7%2C8%2C%20%22%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
function destroyer(arr) {
  // Remove all the values
  //console.log(arguments);
  var arr1 = arguments;
  console.log(arr1.length);
  var i =1;
  var filtered = 0;
    while(i < arr1.length-1){
  filtered = arr.filter(function x(element,index,array){
   // console.log(arguments);
      return element != arr1[i];
  });
      arr = filtered;
      i++;
  }
  //console.log(arguments);
  return filtered;
}

destroyer([1, 2, 3, 5, 1, 2, 3], 2, 3, "");

```

**Comment by ltegman** [comment]
Your code terminates the loop before hitting the final element of the `arr1` array, so you will not filter out whatever the last argument is. The sample code includes a blank string as the final argument that makes it look like your code works, but if you remove that last argument you will see that it does not.

You are not the first person to encounter a problem based on this extra argument in the sample code. There is currently PR #3656 open to remove this confusing extra argument from the sample.

**Comment by bugron** [comment]
@nodnops164 thanks for posting this issue!
Closing this issue as https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3656 is merged.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
