### ISSUE TITLE
Found some minor issues in the Free Code Camp JavaScript Style Guide

### ISSUE THREAD

**Issue by TishG** [freeCodeCamp/freeCodeCamp#36814]
**Describe your problem and how to reproduce it:**
In the Long Strings section, I discovered minor issues in both examples.
 1st example
```javascript
var longString =
  ‘long strings should ‘ +
  ‘be in this form, with the ‘ +
  ‘operator ending the line’;
```

I copied and pasted this code into the chrome console and it produced the following error:
Uncaught SyntaxError: Invalid or unexpected token

Suggested fix:
I believe those symbols should be back ticks
```javascript
var longString =
  `long strings should ` +
  `be in this form, with the ` +
  `operator ending the line.`;
```
Tested this version in the browser and it did not produce any errors.

2nd Example:
```javascript
var foo = 'bar';

var longString = [
  'long strings with variables such as ',
  foo,
  'should ',
  'be in this form, an array of strings ',
  'that are joined with the join array instance method',
].join('');
```
I pasted this code into the browser and then entered longString. The console returned:

"long strings with variables such as barshould be in this form, an array of strings that are joined with the join array instance method"

The bar and should are joined.

Suggested fix:
```javascript
var foo = 'bar';

var longString = [
  'long strings with variables such as ',
  foo,
  ' should ',
  'be in this form, an array of strings ',
  'that are joined with the join array instance method.',
].join('');
```

Outcome: No errors and logs
```javascript
"long strings with variables such as bar should be in this form, an array of strings that are joined with the join array instance method."
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/forum/t/free-code-camp-javascript-style-guide/19121

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 76.0.3809.132 (Official Build) (64-bit)
* Operating System: 64-bit operating system

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/38973991/65208307-3bff2700-da5a-11e9-9177-4ffd53e9d572.png)

I would like to go ahead and create a pull request.

**Comment by RandellDawson** [comment]
No need to create a pull request.  I have fixed the Guide topic.  Pull requests are not needed for forum topics.  In the future, you can just reply to the topic and make a comment about what needs to be fixed and someone with moderator or admin access can fix it.

Thanks for reporting.  I will close this issue for now.  If you have other issues with the forum topic, please reply to the forum topic directly.

**Comment by TishG** [comment]
I guess I am confused. I was looking to contribute to freeCodeCamp. My process was to report what I found and then make the edit in order to make a contribution.

**Comment by RandellDawson** [comment]
@TishG Sory for the confusion.  For changes to the repo, you create issues and pull requests.  For changes to the forum topics, you can just reply to let someone know what needs to be corrected.  It is still contributing, but it is not via GitHub.
