### ISSUE TITLE
Wrong videos in lessons

### ISSUE THREAD

**Issue by Joel-Howard** [freeCodeCamp/freeCodeCamp#36818]
**Describe your problem and how to reproduce it:**

This lesson and the following one contain the videos for each other.

**Add a Link to the page with the problem:**

[https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/make-screen-reader-navigation-easier-with-the-header-landmark](https://learn.freecodecamp.org/responsive-web-design/applied-accessibility/make-screen-reader-navigation-easier-with-the-header-landmark)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 76.0.3809.132
* Operating System:  Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by scissorsneedfoodtoo** [comment]
Thank you for reporting this @Joel-Howard.

To clarify, the "Make Screen Reader Navigation Easier with the header Landmark" challenge should have the video at https://scrimba.com/p/pJ5rC6/cB76vtv, and "Make Screen Reader Navigation Easier with the nav Landmark" should have the https://scrimba.com/p/pJ5rC6/czVwWSv video.
