### ISSUE TITLE
I created a tool for easy creating / editing challenges.

### ISSUE THREAD

**Issue by iliyaZelenko** [freeCodeCamp/freeCodeCamp#36810]
A topic has already been opened with this half year ago:  https://github.com/freeCodeCamp/freeCodeCamp/pull/35609

**Description:**
You can try to create / edit challenges through a handy tool (forms in the browser), which is much more convenient than editing the file on the github. [Open the tool in your browser](https://iliyazelenko.github.io/freeCodeCamp-challenges-manager/) (this is a new tool). [Instructions how to use.](https://github.com/iliyaZelenko/freeCodeCamp-challenges-manager/blob/master/HOW_TO_USE.md)

I could develop this tool further, but I need to promote this tool, you could give an audience.

**Comment by moT01** [comment]
Pretty slick @iliyaZelenko - perhaps this should be it's own repo so issues can be made specifically for this. There's a number of things that could use some work, but it's nice. This tool has a lot of potential.

**Comment by RandellDawson** [comment]
I believe the idea is incorporating it into our https://contribute.freecodecamp.org/dashboard, but we are in the middle of restructuring it to do other things.  Once restructure is complete, then we try and incorporate this tool as another feature of the dashboard.

**Comment by moT01** [comment]
Closing this as stale. Thanks and happy coding 🎉 We still welcome the use of this tool if anyone wants to try and add it to our mentioned tools.
