### ISSUE TITLE
Challenges are not mobile friendly

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#36825]
This wasn't always the case, but right now the formatting for smaller screens isn't great:

![Resize](https://user-images.githubusercontent.com/15801806/65316196-c26e5280-db99-11e9-9b67-480ba4c84003.gif)

Smaller screens used to have tabs letting you switch between the instructions, editor and so on.  You can see them briefly (in the gif) at medium screen sizes, but not for mobile.

If we still want to support this, I can look into restoring it.

**Comment by moT01** [comment]
Looks like they're just hidden behind the search bar.

**Comment by ahmadabdolsaheb** [comment]
Thanks for reporting this, we are still figuring out the final state for the nav.
Once that is settled, this issue will be resolved automatically.

**Comment by ojeytonwilliams** [comment]
This wasn't entirely resolved by #36956, as the challenge tabs are still displaying incorrectly:
![image](https://user-images.githubusercontent.com/15801806/66220379-33028c80-e6cd-11e9-8a42-99b84a71628c.png)
