### ISSUE TITLE
Bonfires not validating code

### ISSUE THREAD

**Issue by IAmMyself** [FreeCodeCamp/FreeCodeCamp#3682]
Challenge [Bonfire: Sum All Numbers in a Range](http://freecodecamp.com/challenges/bonfire-sum-all-numbers-in-a-range) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible. 
![image](https://cloud.githubusercontent.com/assets/14168457/10404377/455d8500-6ea0-11e5-9a2c-5b3824d9b170.png)

I cannot get past this [challenge](http://freecodecamp.com/challenges/bonfire-sum-all-numbers-in-a-range). It will not validate my code.

I have tried:
1. The [Gitter Help Page,](https://gitter.im/FreeCodeCamp/Help) who assured me that my code was indeed functioning.
2. Changing my browser (from Chrome to Edge).
3. Rebooting my computer.
Nothing has worked.

My code:
```
function sumAll(arr) {
  var x = 0;
  for (var i = Math.min(arr[0], arr[1]); i <= Math.max(arr[0], arr[1]); i++) {
    x += i;
  }
  return x;
}

sumAll([1, 4]);

```

**Comment by IAmMyself** [comment]
Actually, none of the Bonfires are working properly.

**Comment by BerkeleyTrue** [comment]
Can you open up the browser console and report any errors you see there. (ctrl + alt + i)

**Comment by IAmMyself** [comment]
I don't see any.

**Comment by doxanthropos** [comment]
I get these errors in the security tab of the web console in firefox:

Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw== blockiert ("img-src * http://freecodecamp.com blob: http://104.236.218.15 http://*.freecodecamp.com http://www.freecodecamp.com http://freecodecamp.com https://www.freecodecamp.com https://freecodecamp.com https://freecodecamp.org http://*.freecodecamp.org http://www.freecodecamp.org ws://freecodecamp.com/ ws://www.freecodecamp.com/ http://*.gstatic.com http://*.google-analytics.com http://*.googleapis.com http://*.google.com http://*.gstatic.com http://*.doubleclick.net http://*.twitter.com http://*.twitch.tv http://*.twimg.com 'unsafe-eval' 'unsafe-inline' http://*.bootstrapcdn.com http://*.cloudflare.com https://*.cloudflare.com http://localhost:3001 ws://localhost:3001/ http://localhost:3001 http://localhost:3000 ws://localhost:3000/ http://localhost:3000 http://*.ionicframework.com https://syndication.twitter.com http://*.youtube.com http://*.jsdelivr.net https://*.jsdelivr.net http://*.ytimg.com http://*.bitly.com http://cdn.inspectlet.com/ https://cdn.inspeclet.com/ wss://inspectletws.herokuapp.com/ http://hn.inspectlet.com/ http://*.googleapis.com http://*.gstatic.com https://hn.inspectlet.com/").

**Comment by IAmMyself** [comment]
I believe, for some reason or another, that Freecodecamp isn't running any JS, although expressly allowed to. I have tried several other sites, which all allow me to run JS.

**Comment by IAmMyself** [comment]
It might have been my firewall, I turned it off, then back on, and now it's working.

**Comment by BerkeleyTrue** [comment]
Awesome. Do you know what setting was blocking?

**Comment by IAmMyself** [comment]
No, I just turned the whole firewall off, then back on.
