### ISSUE TITLE
React migration for componentWillMount

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#36821]
![image](https://user-images.githubusercontent.com/1884376/65271141-31b45a00-db3a-11e9-85c4-192be650146e.png)

We need to migrate and move away to the recommendation as per the logs above.

**Comment by ojeytonwilliams** [comment]
So far I've found that `react-instantsearch-dom` and `@freecodecamp/react-bootstrap` are the main culprits.  Possibly also `@reach/router`.

Algolia seem to be working on this:
https://github.com/algolia/react-instantsearch/issues/1743

As for `@freecodecamp/react-bootstrap` I suspect the solution is going to be to migrate to a more recent version of `react-bootstrap`.

I'll take a closer look at this next week, but if anyone feels like investigating, please do!

**Comment by raisedadead** [comment]
> the solution is going to be to migrate to a more recent version of `react-bootstrap`.

Let's ditch that, for good. We do not need the full library. Also if I am not mistaken we are not on v4 yet. It will be a huge pain to go that route

@ahmadabdolsaheb and I have been talking about this a lot. I think we should just move to CSS-in-JS solution like theme-ui or something.

Its way lightweight that the bulky bootstrap lib.

**Comment by ojeytonwilliams** [comment]
@raisedadead oh, it'd be a massive pain to migrate, for sure.  What I should have said was "the solution is going to be to migrate *away* from the current version of `react-bootstrap`".  To be honest, it's always seemed a bit out of place.

**Comment by scissorsneedfoodtoo** [comment]
It seems like upgrading to the beta version of Algolia Instantsearch will prevent these errors: https://github.com/algolia/react-instantsearch/issues/2813#issuecomment-527179701, https://github.com/algolia/react-instantsearch/issues/2836. Should we move to the beta version for now, then upgrade once the stable version is released?

**Comment by ojeytonwilliams** [comment]
> Should we move to the beta version for now, then upgrade once the stable version is released?

Sounds good to me.  If we do that and migrate away from `react-bootstrap`, it should also make it easier to find where else those methods are being used. I.e. when we don't have to sift through a cloud of other warnings.

**Comment by Sembauke** [comment]
All these errors have seemed to disappear except one coming from the `react-lazy-load` package. 
This might be solved soon as there is an [open issue](https://github.com/loktar00/react-lazy-load/issues/147) for it.

As for now, I am closing this issue.
