### ISSUE TITLE
Curriculum map on mobile

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#36824]
Currently the map looks like this:
![MobileMap](https://user-images.githubusercontent.com/15801806/65310446-9e594400-db8e-11e9-8f6b-db4d43b7764b.png)

I think it would look a lot better if we made more use of the available space.  Something like this:
![MobileMapUpdated](https://user-images.githubusercontent.com/15801806/65310604-fabc6380-db8e-11e9-9d4d-70a2d00f4540.png)

**Comment by ojeytonwilliams** [comment]
@raisedadead I can fix the css in a separate PR, if you like.  Unless you're already handling it, of course.

**Comment by raisedadead** [comment]
I think it is handled now in the PR already. I moved things into the Grid system

**Comment by ojeytonwilliams** [comment]
That PR still has the heavy indentation:

![MapPR](https://user-images.githubusercontent.com/15801806/65319782-b934b400-dba0-11e9-8686-da178d3672d6.png)

**Comment by raisedadead** [comment]
You are correct, if you have something going please go ahead and push to the PR. I am done with the basic consolidation of the views that I was going for.
