### ISSUE TITLE
Update freeCodeCamp sitemap

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#36823]
We want to maximize the quality of pages we expose to Google. 

Arriving at (mostly set-to-private) user profiles or challenge pages that are half-way into the curriculum isn't a good user experience.

We should remove everything from freeCodeCamp's sitemap except for the main freeCodeCamp page: https://www.freecodecamp.org/sitemap.xml

We should also put the following meta property on all of our pages:

```<meta name="robots" content="noindex">```

Here's what our Google result looks like currently:

<img width="641" alt="freecodecamp_-_Google_Search" src="https://user-images.githubusercontent.com/985197/65283920-d95f6700-dafd-11e9-8fe4-b506f282e1d2.png">

We only want the following to show up:

```
<url>
<loc>http://www.freecodecamp.org/</loc>
<changefreq>weekly</changefreq>
<lastmod>2019-09-19</lastmod>
<priority>0.9</priority>
</url>
<url>
<loc>http://www.freecodecamp.org/about</loc>
<changefreq>weekly</changefreq>
<lastmod>2019-09-19</lastmod>
<priority>0.9</priority>
</url>
<url>
<loc>http://www.freecodecamp.org/donate</loc>
<changefreq>weekly</changefreq>
<lastmod>2019-09-19</lastmod>
<priority>0.9</priority>
</url>
</url>
```

And then News and Forum.

Both News and Forum have their own sitemaps, which I don't think we'll need to customize.

**Comment by raisedadead** [comment]
> Both News and Forum have their own sitemaps, which I don't think we'll need to customize.

That is correct, but I think we would still need to include them under the `freecodecamp.org/sitemap.xml` to be discovered?

**Comment by raisedadead** [comment]
> We should also put the following meta property on all of our pages:
>
> `<meta name="robots" content="noindex">`

Can you confirm by all pages you mean the top level landing page and the user profiles, and their certification pages as well?

**Comment by isa3bel** [comment]
is this issue still open?

**Comment by raisedadead** [comment]
Hi @isa3bel thanks for you interest, this is a devops issue for staff. If you would like we have some other issues that are tagged help wanted are open for contributions. Thanks.

**Comment by QuincyLarson** [comment]
@raisedadead Thanks for your patience.

Just to be 100% clear, the pages we don't want to index:
- User profiles
- Everything currently at learn.freecodecamp.org aside from the Map view itself
- Our settings page

We do still want the main www.freecodecamp.org/ landing page to be indexed.

**Comment by raisedadead** [comment]
Perfect. Thanks for the confirmation. I'll get started on getting this done.
