### ISSUE TITLE
i18n guide for translations

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#36829]
Create and add documentation for translation of curriculum. 

Refer: https://chinese.freecodecamp.org/forum/t/chinese-translation-and-contributors-meeting-on-20th-sept-2019/502

**Comment by raisedadead** [comment]
@RandellDawson I would love your advice on this. We would want to create some basic guidelines on what translators should watch for while working on translations.

**Comment by raisedadead** [comment]
Hi @freeCodeCamp/moderators !

We would want to create:

- A low friction guide for people to be able to translate the coding challenges.
- This guide is to be generic for all languages, with a notice on the top that we are currently accepting only chinese translations.
- We would want to not repeat much from the existing guide. (It can be in the same guide even).
- We would want to stress that we would like high quality human translations, one per PR per block, section etc.
- We would want to keep the files consistent with the schema.

Anyone interested in taking this up? Thanks a lot.

**Comment by myluco** [comment]
Where is the existing guide? Tx

**Comment by myluco** [comment]
... and why just chinese?

**Comment by raisedadead** [comment]
Thanks for your interest.

> Where is the existing guide? Tx

There isn't one, this issue aims to help create a guide that follows the guide for the coding challenges. If you are interested in working on this, you would want to create a guide that is written for translators to be able to follow and adhere to points in my previous comment.

> ... and why just chinese?

We want to test out the workflow on chinese language first. We already have the older curriculum deployed in chinese and it seems a good way to test out and fix caveats involved supporting different languages in the repository. 

The point being, the guide should be generic for all languages, with a notice on top saying we are working with chinese translations and deployments first.

**Comment by raisedadead** [comment]
Dumping some screenshots here for future docs:

**Editor (Set to Comfortable):**

![image](https://user-images.githubusercontent.com/1884376/96873777-fef23900-1492-11eb-93ac-95e138f2f982.png)

**Proofreader (Set to Comfortable):**

![image](https://user-images.githubusercontent.com/1884376/96874190-788a2700-1493-11eb-8315-054107631023.png)

**Proofreader (Set to Side-by-side):**

![image](https://user-images.githubusercontent.com/1884376/96874611-f2221500-1493-11eb-81ff-89b8c33687b8.png)

**Comment by raisedadead** [comment]
Voting:

![image](https://user-images.githubusercontent.com/1884376/96878345-59da5f00-1498-11eb-94f5-e43322b52e0f.png)

**Comment by RandellDawson** [comment]
@raisedadead I believe this can be close since @nhcarrigan created all of the documentation around translating and proofreading via Crowdin.
