### ISSUE TITLE
Instructions Don't Match Test Condition, or clearly separate waypoint instructions from example code

### ISSUE THREAD

**Issue by anseriformes** [FreeCodeCamp/FreeCodeCamp#3683]
The instructions say "Let's remove all the values greater than five", but the test looks for a different filter: "You should have removed all the values from the array that are greater than 4."

![image](https://cloud.githubusercontent.com/assets/10488528/10405304/e3478662-6e8c-11e5-99d8-070b74763ebe.png)

_------__----__

Challenge [Waypoint: Filter Arrays with filter](http://freecodecamp.com/challenges/waypoint-filter-arrays-with-filter#?solution=var%20array%20%3D%20%5B1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%5D%3B%0A%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0Aarray%20%3D%20array.filter(function(val)%20%7B%0A%20%20return%20val%20%3C%3D%205%3B%0A%7D)%3B%0A%0A%0A%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A(function()%20%7Breturn%20array%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [1,2,3,4,5,6,7,8,9,10];
  // Only change code below this line.
array = array.filter(function(val) {
  return val <= 5;
});


  // Only change code above this line.
(function() {return array;})();

```

**Comment by ltegman** [comment]
This is a duplicate of #3671. I have PR #3678 open to fix this issue.

**Comment by anseriformes** [comment]
Thanks! I looked, but didn't see it in the list. I'll close it.
