### ISSUE TITLE
Settings button missing when user profile is private

### ISSUE THREAD

**Issue by Bouncey** [freeCodeCamp/freeCodeCamp#36838]
The Portfolio button in the nav only takes me to my locked down profile. The settings button should be available on the user profile even when my profile is private and I am signed in.

![image](https://user-images.githubusercontent.com/18572518/65467440-4bff7800-de59-11e9-91cd-dc53d3fa1bd3.png)

Edit raisedadead:

We probably missed this while adding tests. Anyone interested can would be awesome if you could add tests while fixing this.

**Comment by ahmadabdolsaheb** [comment]
The settings button should be displayed here regardless of privacy settings.

**Comment by raisedadead** [comment]
You beat me to this, I opened #36839 without looking at the tracker.

**Comment by ivan-nikolaievskyi** [comment]
Hi guys. I want to get and fix that issue.
