### ISSUE TITLE
search bar result not showing properly

### ISSUE THREAD

**Issue by gareth-d85** [freeCodeCamp/freeCodeCamp#36833]
**Describe the bug**
When I use the search bar the results are half-hidden to the left of the browser

**Expected behaviour**
I should be able to see all of the search results.

**Screenshots**
![Screenshot from 2019-09-22 20-44-01](https://user-images.githubusercontent.com/20612560/65393539-c3f67100-dd79-11e9-9de3-b77e969fde46.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser Firefox
 - Version 69.0

**Additional context**

**Comment by RandellDawson** [comment]
This but has already been resolved on the master branch and is just awaiting deployment to production.

I am closing this issue for now.
