### ISSUE TITLE
Unable to unsubscribe from Quincy’s weekly email

### ISSUE THREAD

**Issue by neverendingqs** [freeCodeCamp/freeCodeCamp#36832]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
When I click on the link in the email next to

> If these emails aren’t worth your time, you can turn them off:

I get the following:

![image](https://user-images.githubusercontent.com/8854618/65393239-39e3e380-dd4c-11e9-9adf-7f0767a1ae5f.png)

There are no issues in the dev console. `Send me Quincy’s weekly email` is toggled off in settings.

**To Reproduce**
Appears to be an account-specific issue.

**Expected behavior**
No more weekly emails.

**Desktop (please complete the following information):**
N/A - it appears to be a backend issue

**Smartphone (please complete the following information):**
N/A - it appears to be a backend issue

**Additional context**
I was redirected here [after asking on the forum](https://www.freecodecamp.org/forum/t/unable-to-unsubscribe-from-emails/300677/2).

**Comment by raisedadead** [comment]
Hi @neverendingqs thanks for reporting the issue. I am from the freeCodeCamp.org staff. 

While we investigate this issue, Can you send me a private email from your email, so that I can manually go ahead and remove you from the list.

My email: `mrugesh at freecodecamp dot org`

I am closing this to handle your user information privately.

Thanks.

**Comment by raisedadead** [comment]
BTW, if you can sign into your account, you should be able to update the mail subscription for you account from your settings page at: https://www.freecodecamp.org/settings

**Comment by jomesario** [comment]
Hey, just wanted to comment out, the same thing is happening to me, only thing is, I also am not able to log in, I have the same "Oops, something went wrong message" both when I try to unsuscribe directly from the email and when I try to log in.
I dont know if something is wrong with my account, or something is corrupted, I would appreciate if you could take a look into that.

**Comment by raisedadead** [comment]
Hi @jomesario 

Sorry about this; chances are you have a duplicate account. Can you please send us an email from your registered email address here: `support @ freecodecamp .org`
