### ISSUE TITLE
No way to report users

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#36837]
There used to be a button to report users:
https://github.com/freeCodeCamp/freeCodeCamp/blob/46a217d0a5b4f6b499ce24a18b46fd78fff45d78/api-server/common/app/routes/Profile/Profile.jsx#L190
added to close https://github.com/freeCodeCamp/freeCodeCamp/issues/16598, but this has since been removed.  However, there's still code associated with user reports:
https://github.com/freeCodeCamp/freeCodeCamp/blob/e54a7fb35097766a187cab1a26e752e4e22e946e/client/src/client-only-routes/ShowUser.js#L136-L139

Do we still want this?  If not, all the associated code can go.

**Comment by raisedadead** [comment]
Thanks for reporting this, I do not remember the reason for removing this. I would confirm from @ahmadabdolsaheb. But I believe it should be there.

**Comment by ahmadabdolsaheb** [comment]
Thanks for noticing this. Not sure why this was removed.
But optimally I think it should be displayed regardless of user's privacy settings where we display the settings button for authorized users on portfolio.

**Comment by ojeytonwilliams** [comment]
@ahmadabdolsaheb I guess it was just lost accidentally when `Profile` was moved to the client - I couldn't find anything suggesting it was removed deliberately.

> But optimally I think it should be displayed regardless of user's privacy settings where we display the settings button for authorized users on portfolio.

Is the settings button only supposed to be visible when a user is looking at their own profile (while authorized, of course)?  If so, that does sound like the perfect spot for this.

**Comment by raisedadead** [comment]
You are correct, check #36839 which is related.

**Comment by raisedadead** [comment]
This is probably when we were removing the server side views, if I am not mistaken.

**Comment by Brechy** [comment]
I would like to take on this issue for Hacktoberfest. Thanks!

**Comment by raisedadead** [comment]
Hi @Brechy thanks for your interest, however this issue is already being worked upon with a PR for it.

We welcome you to take a look at other issues on the tracker.
