### ISSUE TITLE
Shortcuts legend modal available on pressing the `?` key.

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#36841]
Shortcuts legend modal available on pressing the `?` key.

Youtube's modal:
https://user-images.githubusercontent.com/985197/64934197-bd627980-d80e-11e9-86e3-961745d0c665.png

**Comment by gangov** [comment]
hey there, I see that there's an assignee for this one, but does it need some work?

**Comment by ojeytonwilliams** [comment]
Hey @gangov I was planning to implement it myself, but never seemed to find a moment to finish it. You are very welcome to work on it if you are interested.

**Comment by gangov** [comment]
@ojeytonwilliams  thanks for the prompt reply, I'll give it a go

**Comment by ojeytonwilliams** [comment]
Awesome, I'm looking forward to seeing what you come up with.  Let us know if you need any further context/explanation.

**Comment by gangov** [comment]
I've set the project locally yesterday, so today I'm planning on knowing myself around afterwards I'll place my stuff. One question for now is what are the shortcuts that need to be listed? Is this topic okay for start:

[https://forum.freecodecamp.org/t/free-code-camp-hotkeys/59467](https://forum.freecodecamp.org/t/free-code-camp-hotkeys/59467)

**Comment by ojeytonwilliams** [comment]
That topic is quite out of date, I'm afraid. The hotkeys we use for freecodecamp.org are defined here: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/src/templates/Challenges/components/Hotkeys.tsx
