### ISSUE TITLE
profile font may need to be adjusted

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#36851]
I feel the screenshot shows the English and Chinese words not so harmonious, English words looking bold.
![News profile](https://user-images.githubusercontent.com/19358186/60856402-a36a5080-a239-11e9-891d-ff8b2a50d9a5.jpg)
@ahmadabdolsaheb @raisedadead

**Comment by vkWeb** [comment]
@miyaliu666 @raisedadead I can't reproduce this too.

**Comment by vkWeb** [comment]
@miyaliu666 Please confirm if this issue still persists.

**Comment by miyaliu666** [comment]
@vkWeb It works well for me now https://chinese.freecodecamp.org/news/.

![image](https://user-images.githubusercontent.com/19358186/66530873-36b66900-eb3c-11e9-9321-b8182bc638ca.png)
