### ISSUE TITLE
How-to-NPM Nodeschool module workaround needed

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3685]
Lesson 10 of Node School's how-to-npm challenge doesn't work anymore. I think one of the dependencies changed.

We need to confirm that older version of the how-to-npm package works, or better yet, patch how-to-npm itself. Here's the (long open) issue: https://github.com/nodeschool/discussions/issues/995

**Comment by newswim** [comment]
I just got this error, going to investigate.. here's the error:

```
user@computer$ npm dist-tag add how-to-npm-workshopper@1.0.1 'wonderful'

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "dist-tag" "add" "how-to-npm-workshopper@1.0.1" "wonderful"
npm ERR! node v0.12.7
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 missing : -/package/how-to-npm-workshopper/dist-tags

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/me/Documents/learning/nodeschool/how-to-npm/src/npm-debug.log
```

**Comment by newswim** [comment]
I suspect it has something to do with `--tag` being changed to `dist-tag` by npm recently and the workshopper just needs an update.

**Comment by damianza** [comment]
Still the same problem. The wokshopper is using ```--distag``` but still keep error ```ERR! 404 missing : …```.

**Comment by coded9** [comment]
+1
