### ISSUE TITLE
Image being strechted in mobile view

### ISSUE THREAD

**Issue by sunnyssr** [freeCodeCamp/freeCodeCamp#36850]
Hey there,
Please check the screenshot. Here is the link to article:
https://www.freecodecamp.org/news/object-oriented-concepts/
![Screenshot_2019-08-20-20-20-59-692_com android chrome](https://user-images.githubusercontent.com/41870839/63370069-01dd2f80-c39f-11e9-8d37-a57cf83027e3.png)

**Comment by raisedadead** [comment]
Is this still the case @sunnyssr

**Comment by ahmadabdolsaheb** [comment]
I believe this has been resolved.
<img width="404" alt="Screen Shot 2019-09-26 at 11 39 45 AM" src="https://user-images.githubusercontent.com/4591597/65672880-723c3800-e052-11e9-8b00-4e65cfe4f86e.png">

**Comment by sunnyssr** [comment]
No, it's working fine now. Maybe the author of post had given some fixed value to size of image. I never found such issue with any other post.
