### ISSUE TITLE
Inconsistent parsing of Markdown in challenges

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#36879]
**Describe the bug**
Markdown in challenge description and instruction sections is parsed differently if it does or does not follow an empty line.

**To Reproduce**
1. Go to the markdown for any challenge
2. Replace the description section with the following:
```html
<section id='description'>
Line one `var`
Line two `var`

After empty line `var`
Second line after empty line `var`

After second empty line `var`
</section>
```
3. See the following in the browser:
![MarkdownInconsistency](https://user-images.githubusercontent.com/15801806/65861953-7e373b00-e36d-11e9-8079-a4dea3b470ee.png)

**Expected behavior**

That the Markdown gets parsed the second way.  Namely backticks become `<code>` tags and an empty line is needed to start a new paragraph

**Comment by ojeytonwilliams** [comment]
The main difficulty I see is that fixing this would break most challenges since they rely on the current behaviour.  If we do want to change this, all those challenges would need to be modified first.  

Fortunately if they are converted to use empty lines instead of new lines the current parser will interpret them correctly.

**Comment by raisedadead** [comment]
Nice catch @ojeytonwilliams

**Comment by ojeytonwilliams** [comment]
The root cause of this is how unified operates, namely it doesn't parse any markdown that's inside html unless there's an empty line preceding it.  This means we have to dig into the hast, pull out the text, process it under the assumption it's markdown and then put it back into the hast.  Suffice to say this is ugly and likely to create weird bugs, unless we're very careful.

I think a simpler solution would be to require blank lines via linting.  I think we'd need a custom plugin, but, if we want to go this way, I'd be happy to create one.

Also, somewhat related, it *might* be possible to do everything we want with [remark-lint](https://github.com/remarkjs/remark-lint). It has a 'fix' option which would make it a little less painful.

**Comment by raisedadead** [comment]
> I think we'd need a custom plugin, but, if we want to go this way, I'd be happy to create one.

and

> it might be possible to do everything we want with remark-lint.

OK -- I will defer to your best judgement on the approach. I would prefer the one that is maintainable long term.

**Comment by ojeytonwilliams** [comment]
> OK -- I will defer to your best judgement on the approach. I would prefer the one that is maintainable long term.

Honestly I'm not sure which one would be the easiest to maintain, but, assuming I can get it working, `remark-lint` should be less painful to use.  

So far, I've managed to create a plugin that flags up if a section doesn't start with a blank line (no ability to fix).  Shouldn't take me too long to re-create the prism language checker.

**Comment by thecodingaviator** [comment]
@ojeytonwilliams how is this going?

**Comment by ojeytonwilliams** [comment]
@thecodingaviator I'm getting there.  The tricky bit was converting all the existing challenges without inadvertently changing the formatting.  I thought this would as simple as replacing `\n` with `\n\n`, but that was a little naive!

The script to do this is now working and just needs cleaning up before I submit a PR with it and all the tidied up challenges.

As for the linter itself, that's also working, but I'll put that in a separate PR.

**Comment by Pallof** [comment]
Is this issue still open?

**Comment by thecodingaviator** [comment]
@Pallof I think you can coordinate with @ojeytonwilliams

**Comment by ojeytonwilliams** [comment]
It's basically done, but the formatting has to be reviewed dev team first and that's pretty low priority.

**Comment by moT01** [comment]
This looks to be fixed with the new format. I think it's safe to close this. Let me know if I'm wrong, and it can be reopened. Thanks and happy coding 🎉
