### ISSUE TITLE
Bonfire: Slasher Flick

### ISSUE THREAD

**Issue by GianNipitella** [FreeCodeCamp/FreeCodeCamp#3687]
I think this is a Typo the that at first lead me to confusion 
in the Bonfire: Slasher Flick the Asserts to complete the Bonfire said 
slasher([1, 2, 3], 2, [3]) should return [3]. 
slasher([1, 2, 3], 0) should return [1, 2, 3].
slasher([1, 2, 3], 9) should return [].

and I think the first one should say slasher([1, 2, 3], 2 ) should return [3]

**Comment by bugron** [comment]
@GianNipitella thanks for posting this issue!
Confirmed! Also this bonfire accepts this solution:
```javascript
function slasher(arr, howMany) {
  return arr.slice(-arr.length + howMany);
}
```
which is incorrect. I think tests should check if `arr.length >= howMany` and if so the returning value should be `[]`.
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
