### ISSUE TITLE
reporting bug issues

### ISSUE THREAD

**Issue by Dotty1526** [freeCodeCamp/freeCodeCamp#36874]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RandellDawson** [comment]
You have not reported an actual issue.  I am closing this for now.  If you have any further information to provide, you can request it to be reopened.
