### ISSUE TITLE
Audit and update news theme if needed for compatibility

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#36875]
We need to update to the latest Ghost for Developer news. This time they have some compatibility advisories as per [their release page](https://github.com/TryGhost/Ghost/releases).

We need to audit and make changes to [our news theme](https://github.com/freeCodeCamp/news-theme) as per the same, specifically [this version's advisory](https://github.com/TryGhost/Ghost/releases/tag/2.30.0) for the "Bookmark cards" feature.

**Comment by dsuarezlogans** [comment]
Hello, can I help on this one? can you explain me more what needs to be done?

**Comment by scissorsneedfoodtoo** [comment]
@dsuarezlogans, thank you for offering to help with this issue. I believe this is one that we'll handle internally, so please check our [Contributing Guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md) and [open issues](https://github.com/freeCodeCamp/freeCodeCamp/issues) for other things we need help with.
