### ISSUE TITLE
CORS / CORB error for data urls -- testable-projects

### ISSUE THREAD

**Issue by tbushman** [freeCodeCamp/freeCodeCamp#36876]
Methods tried:
```  
d3.json(DATASET.FILE_PATH, function (error, data) {
    if (error) {
        throw error;
    }  
```  
yields   
<img width="1060" alt="screen shot 2019-01-28 at 5 31 06 pm" src="https://user-images.githubusercontent.com/7049294/51875511-85133700-2322-11e9-8bdd-8e32f8777d82.png">

```  
fetch(DATASET.FILE_PATH, {mode: 'no-cors', dataType:'jsonp'}, function (error, data) {
    if (error) {
        throw error;
     }  
```  
yields  
<img width="1059" alt="screen shot 2019-01-28 at 5 29 01 pm" src="https://user-images.githubusercontent.com/7049294/51875520-90fef900-2322-11e9-838b-0a2a22cb1a27.png">
  
I feel like I've solved this before with dataType: 'jsonp' when using AJAX... I'll look into that.  
__edit__: AJAX request tried with both 'json' and 'jsonp' `dataType` , yielding the same result as with `fetch` .

**Comment by raisedadead** [comment]
We need someone to investigate and confirm if this is still the case.

**Comment by rickysyamsi** [comment]
@raisedadead Hello, I did some investigation on this with following result:

```
const URL = 'https://cdn.freecodecamp.org/testable-projects-fcc/data/tree_map/video-game-sales-data.json';

// CORS / CORB ERROR
d3.json(URL, function(error, data) {
  if (error) throw error;
});

// SUCCESS
fetch(URL, {mode: 'no-cors', dataType:'jsonp'}, function (error, data) {
  if (error) throw error;
});

// CORS / CORB ERROR
var xhttp = new XMLHttpRequest();
xhttp.open("GET", URL, true);
xhttp.send();
```

Also I did the test on CodePen via latest Chrome if it can help.

**Comment by raisedadead** [comment]
I landed a commit to enable execution https://github.com/freeCodeCamp/cdn/commit/ccd31d521d8f73c91163e4ec0a0e5145094d8136

Please comment if issue still exists.
