### ISSUE TITLE
Exclude anything other than the curriculum directory in the markdown linter

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#36884]
We should need to lint the docs, readme, contributing guide etc. Our scripts and the config need to be updated.

**Comment by ojeytonwilliams** [comment]
Perhaps linting them isn't a terrible idea. After all, the linter caught a mistake (in the conversation on gitter) ![Linter output](https://files.gitter.im/FreeCodeCamp/Contributors/jatx/image.png) - the URL wouldn't have rendered correctly.  Also, h1 should generally be at the top, [for a11y reasons](https://www.w3.org/WAI/tutorials/page-structure/headings/).  Potentially someone might navigate to h1, continue down the page and miss the links to other languages.

**Comment by raisedadead** [comment]
Yes, and you are correct. Maybe syntax errors are fine.

But I see this could be a lot of friction and frustration for people contributing to documentation. More often than not they are contributing to translations and probably are new to contributing and GitHub etc.?

I'll close this for now and see if we get more complaints.
