### ISSUE TITLE
while loop challenge in javascript. Entire web stops working on an infinite loop

### ISSUE THREAD

**Issue by VIGNESHinZONE** [freeCodeCamp/freeCodeCamp#36881]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

link for the coding challenge-

https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-while-loops/

issue:
at first i started with infinite loop and the whole site crashed
code-

// Setup
var myArray = [];

// Only change code below this line.
var i=0;
while(i < 5){
  myArray.push(i);
  
}

Pls fix this bug, if you find a infinite loop it shouldnt crash

**Comment by raisedadead** [comment]
Thanks for reporting.

Please go through this: https://www.freecodecamp.org/forum/t/19543 and confirm a bug on the forum with others before reporting.
