### ISSUE TITLE
 URL  in a code  is  not accepted my GitHub .

### ISSUE THREAD

**Issue by naimiii** [freeCodeCamp/freeCodeCamp#36883]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
A bug is in contributors.md file  in which i give my URL as all the contributors had added but it creates trouble in pushing the code .

**To Reproduce**

**Expected behavior**
I expected  to accept the  my changing in a code by GitHub.
**Screenshots**
![image](https://user-images.githubusercontent.com/28563415/65890888-19a3cc80-e3bd-11e9-934d-5a4e3cb73840.png)

**Desktop (please complete the following information):**
 - OS: [windows 10 pro]  
 - Browser [chrome, ]
 - Version [e.g. 1.3.33.5]

**Smartphone (please complete the following information):**
 - Device: [ iPhone6]
 - OS: [ iOS ]
 - Browser [ safari]
 - Version [12.4.1]

**Additional context**
kindly fix my issue ASAP

**Comment by raisedadead** [comment]
This is not an issue with the "file". You need not add links to your GitHub on the contributing guide.

Thanks for the issue.

You can seek additional help on the forum if needed: https://www.freecodecamp.org/forum/t/pull-request-is-creating-error/318466/5
