### ISSUE TITLE
Missing 'var' keyword in "Iterate with JavaScript For Loops"

### ISSUE THREAD

**Issue by brett24** [FreeCodeCamp/FreeCodeCamp#3691]
The left sidebar has var ourArray = [];

But the code only has ourArray = [];

Then the code has var myArray = [];

It runs with our without the pink var (declaration I think)...

Just might want to fix the typo or have it be consistent or explained that it will work either way...

Challenge [Waypoint: Iterate with JavaScript For Loops](http://freecodecamp.com/challenges/waypoint-iterate-with-javascript-for-loops#?solution=ourArray%20%3D%20%5B%5D%3B%0Afor(var%20i%20%3D%200%3B%20i%20%3C%205%3B%20i%2B%2B)%7B%0A%20%20ourArray.push(i)%3B%0A%7D%0Avar%20myArray%20%3D%20%5B%5D%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0A%2F%2F%20Push%20the%20numbers%20zero%20through%20four%20to%20myArray%20using%20a%20%22for%20loop%22%20like%20above.%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%2F%2F%20We%20use%20this%20function%20to%20show%20you%20the%20value%20of%20your%20variable%20in%20your%20output%20box.%0A%2F%2F%20You'll%20learn%20about%20functions%20soon.%0Aif(typeof(myArray)%20!%3D%3D%20%22undefined%22)%7B(function()%7Breturn%20myArray%3B%7D)()%3B%7D%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
ourArray = [];
for(var i = 0; i < 5; i++){
  ourArray.push(i);
}
var myArray = [];

// Only change code below this line.

// Push the numbers zero through four to myArray using a "for loop" like above.

// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
// You'll learn about functions soon.
if(typeof(myArray) !== "undefined"){(function(){return myArray;})();}


```

**Comment by tva10** [comment]
@brett24 It is not a typo. Code with `ourAray` is an example how to use `push` method. 
In this waypoint your task is write in `myArray` numbers from 0 to 4. (like previous example)

So check comments:
```
// Only change code below this line.

// Push the numbers zero through four to myArray using a "for loop" like above.

// Only change code above this line.
```

**Comment by ltegman** [comment]
This is a typo. The seed code is missing `var` in front of the initial declaration of ourArray. While this will run it's a bad practice and should be fixed.

**Comment by bugron** [comment]
@brett24 thanks for pointing this out! Confirmed and marked as easy fixable.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***
