### ISSUE TITLE
CORS error when fetching public user data on Firefox

### ISSUE THREAD

**Issue by chris-tse** [freeCodeCamp/freeCodeCamp#36921]
**Describe the bug**
When attempting to fetch the public profile data for a user using the endpoint `https://www.freecodecamp.org/api/users/get-public-profile?username=${username}` results in a CORS error on Firefox. This is when trying to fetch my own data for a personal project, both on localhost and on a hosted https URL. It is working on Chrome or if using a CORS pass-through such as https://cors-anywhere.herokuapp.com.

**To Reproduce**
1. Open Firefox
2. Open a console from a site that is not freecodecamp.org
3. Attempt to execute
 ```js
fetch('https://www.freecodecamp.org/api/users/get-public-profile?username=chris-tse').then(res => res.json()).then(data => console.log(data))
```

**Expected behavior**
Response with user data should be returned.

**Desktop (please complete the following information):**
 - OS: Kubuntu 19.04
 - Browser: Firefox
 - Version: 69.0.1

**Comment by raisedadead** [comment]
We welcome a pull-request :)

**Comment by chris-tse** [comment]
@raisedadead Do you know where in the code this might be? I was digging through the server side code and found a route for the endpoint, but couldn't find where it was calling a controller that sends a response with headers.

**Comment by moT01** [comment]
Closing as stale. If anyone is interested in adding this functionality, it's probably best to create a new issue. Thanks and happy coding 🎉
