### ISSUE TITLE
Bonfire: Check for Palindromes

### ISSUE THREAD

**Issue by bomholt** [FreeCodeCamp/FreeCodeCamp#3692]
Challenge [Bonfire: Check for Palindromes](http://www.freecodecamp.com/challenges/bonfire-check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20var%20rstr%20%3D%20str.split(%27%27).reverse().join(%27%27).toLowerCase().replace(%2F%5CW%2Fg%2C%20%27%27)%3B%0A%20%20if%20(rstr%20%3D%3D%3D%20str.toLowerCase().replace(%2F%5CW%2Fg%2C%20%27%27))%20%7B%0A%20%20%20%20return%20true%3B%0A%20%20%7D%20else%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%7D%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
function palindrome(str) {
  var rstr = str.split('').reverse().join('').toLowerCase().replace(/\W/g, '');
  if (rstr === str.toLowerCase().replace(/\W/g, '')) {
    return true;
  } else {
    return false;
  }
}

palindrome("eye");

```

One of the tests is incorrect -> [ palindrome("0_0 (: /-\\ :) 0-0") should return true ].

**Comment by RubberTendo** [comment]
rstr = str almost got me until I read lol
