### ISSUE TITLE
Some math operations give wrong results 

### ISSUE THREAD

**Issue by esdestera** [freeCodeCamp/freeCodeCamp#36937]
If you make some simple computations like addition or division the result is not correct

1. Go to any lesson from java Javascript Algorithms And Data Structures Certification (300 hours)
2. Write on the codding area console.log(96.74 - 60) or the division
3. See the result

Expected behavior:
96.74 - 60 = 36.74

Actual result:
35.739999999999995

![image](https://user-images.githubusercontent.com/18334134/66025575-79a28c00-e4ff-11e9-9806-e7c405229674.png)

 - OS: Windows 10
 - Browser chrome, safari

**Comment by raisedadead** [comment]
From your screenshot it is returning 36.739999999999995 and not 35.739999999999995

See:

![image](https://user-images.githubusercontent.com/1884376/66027033-bd08f480-e517-11e9-9c02-50dcd8145c0a.png)

As for the precision that's how browser implement it. To round off, you need to to a `toFixed`

You can learn more about this on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed

**Comment by esdestera** [comment]
yes, you are right, I made a mistake there but still it is the wrong value, it should be 36.74. I will try to add to fixed and see if it helps

**Comment by raisedadead** [comment]
I am closing this, unless you have some additional information on how this can affect a lesson.

Also you can reach out to our [Community Forum](https://www.freecodecamp.org/forum) if you need help with a challenge.

**Comment by esdestera** [comment]
using toFixed() does not help, I do not want to round the value, I just need the correct answer for the operation

**Comment by raisedadead** [comment]
> I just need the correct answer for the operation

We understand your frustration. As I mentioned the precision after the decimals is what the browsers implement.

Since I do not have much information or context about what you are doing, it would help to share more information.

Did you try `36.739999999999995.toFixed(2)` ?

**Comment by esdestera** [comment]
using toFixed(2) helped for this case, thank you!

**Comment by ojeytonwilliams** [comment]
To expand slightly on what @raisedadead is saying, it's how floating point (decimal numbers) arithmetic is implemented.  When evaluating things like 96.74 - 60, computers have to work using a binary representation which is generally going to create small rounding errors like the ones you've been seeing.

**Comment by ronaldgevern** [comment]
> using toFixed(2) helped for this case, thank you!

It seems like Math.round() is a better solution, but it is not! In some cases it will NOT round correctly. Also, toFixed() will NOT round correctly in some cases.

To correct the rounding problem with the previous Math.round() and toFixed(), you can define a custom [JavaScript round](http://net-informations.com/js/progs/round.htm) function that performs a "nearly equal" test to determine whether a fractional value is sufficiently close to a midpoint value to be subject to midpoint rounding. The following function return the value of the given number rounded to the nearest integer accurately.

```
Number.prototype.roundTo = function(decimal) {
  return +(Math.round(this + "e+" + decimal)  + "e-" + decimal);
}

var num = 9.7654;
console.log( num.roundTo(2)); //output 9.77
```
