### ISSUE TITLE
[Feature Request] Allow Single FCC Account to be associated with multiple Login Providers at once

### ISSUE THREAD

**Issue by SubhamSatyajeet** [freeCodeCamp/freeCodeCamp#36969]
Currently, a user can login using Github _or_ Facebook _or_ Google _or_ Email. If you have already logged in via, say, Github, but you forgot that, and you try to login using Google, a new account would be created. The user has to delete the new account if he doesn't want the hassle of multiple accounts (even if their email address on Google, Facebook and Github are the same).

Possible Solution:
Allow associating a single FCC account with a Facebook account, a Google account, a Github account and email, if required. This is similar to what Leetcode or Khan Academy does. They let you add your social logins in the website settings. After you do that, you can use _any_ of your accounts to sign-in to the same account.

This would help reduce the number of duplicate accounts that are created by mistake. Once the user sets up their social login, they don't have to worry about remember the method used to login.

**Comment by raisedadead** [comment]
We used to have this in the past. And we still do some extent. To commit to the best of the privacy standards and best of operations we have dropped support for tying accounts together.

All we ask is the email from the social providers.

As long as the social provider is returning the same email to us without obfuscating it in anyway, you will be signed into the same account with us.

If you updated your account's email with us or with the providers or the provider returned multiple emails (GitHub does this, I think), you will end up in a fresh new account.

That said, we are working towards making this better. However, we do not have an ETA on this.
