### ISSUE TITLE
Audit hardGoTo and unify if possible

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#36992]
As pointed out in [this comment](https://github.com/freeCodeCamp/freeCodeCamp/pull/36926#pullrequestreview-296723108) and the ones below it. The `hardGoTo` code that is used in several places in the codebase is a "legacy thing that we had before we had navigate. It can be removed and cleaned up."

A search for "hardGoTo" reveals eight results. They can probably all be changed to use `navigate` and the redux file deleted.

**Comment by dsuarezlogans** [comment]
Hello, can I help on this one?

**Comment by moT01** [comment]
go for it @dsuarezlogans

**Comment by raisedadead** [comment]
I re-audited this and realised that the `hardGoTo` is used for direct calls to the `api` endpoints without proxying through internally.

We should leave it be for now.

**Comment by ojeytonwilliams** [comment]
@raisedadead as it stands, some api calls go via `hardGoTo` and some via navigate. Is it worth leaving this open until we've decided which should be which?  Or are you already happy that they're as they should be?

**Comment by raisedadead** [comment]
In a perfect world I should be able to proxy everything, but sadly that would need a lot of re-write.

I am keeping this open for traceability.
