### ISSUE TITLE
Typos on Commit page

### ISSUE THREAD

**Issue by wildlifehexagon** [FreeCodeCamp/FreeCodeCamp#3700]
There are one too many m's on these lines at http://freecodecamp.com/commit/directory

"Commmit to Girl Develop It"
"Commmit to Black Girls CODE"

**Comment by bugron** [comment]
@wildlifehexagon thanks for pointing this out!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by uwaseem** [comment]
Has this been fixed or shall I work on it ??
