### ISSUE TITLE
NaN is not a boolean primitive

### ISSUE THREAD

**Issue by jbmartinez** [FreeCodeCamp/FreeCodeCamp#3701]
The description on the bonfire: [Boo who](http://www.freecodecamp.com/challenges/bonfire-boo-who) says:

>Check if a value is classified as a boolean primitive. Return true or false.
Boolean primitives are true and false.

Which is totally correct, but one of the tests is wrong:

> boo(NaN) should return true.

Nan is not a boolean primitive, only `true` and `false` are boolean primitives. That test should be deleted from the bonfire because is wrong.

![boo](https://cloud.githubusercontent.com/assets/4247923/10413604/564ad914-6f7a-11e5-8e94-85fc2bca1f66.png)

**Comment by jbmartinez** [comment]
From MDN:

>In computer science, a boolean is a logical data type that can have only the values true or false. https://developer.mozilla.org/en-US/docs/Glossary/Boolean

>Do not confuse the primitive Boolean values `true` and `false` with the true and false values of the Boolean object. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean

**Comment by MayankJ30** [comment]
I think it's a typo. Because `boo(NaN)` returns `false` in my code but it still passed all the tests.

**Comment by BerkeleyTrue** [comment]
Indeed, this is a typo in the message: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/54ee735f678372061dff9784f2348d7f56487e23/seed/challenges/intermediate-bonfires.json#L359

**Comment by natac13** [comment]
I will be happy to work on this!
