### ISSUE TITLE
Remove the highlight on hover on the nav logo.

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#37021]
![image](https://user-images.githubusercontent.com/1884376/66214426-4b7ba280-e6df-11e9-9d97-dbef3f173e04.png)

Remove the highlight on hover on the nav logo.

**Comment by dsuarezlogans** [comment]
Hello, can I help on this one?

**Comment by javapriyan** [comment]
I would like to work on this as well

**Comment by bodhisha** [comment]
Hey,How can  i help?

**Comment by theREALaltoid** [comment]
On it.

**Comment by raisedadead** [comment]
@dsuarezlogans I think you have already been assigned a issue, you should work on that instead.

@bodhisha @theREALaltoid 

We typically accept the first, meaningful PR. Meaning, a PR which is closest to our liking, that follows the guidelines and adds tests, etc. is favored.

Happy contributing.

**Comment by ahmadabdolsaheb** [comment]
This issue has been addressed in #36956.
