### ISSUE TITLE
Unable to remove classes.

### ISSUE THREAD

**Issue by revathynair** [FreeCodeCamp/FreeCodeCamp#3703]
![4](https://cloud.githubusercontent.com/assets/13557418/10414791/efa8584c-7002-11e5-9326-dc0ec7a80beb.JPG)
![3](https://cloud.githubusercontent.com/assets/13557418/10414793/f1c37b0c-7002-11e5-83f4-959bac4ea944.JPG)

Challenge [Waypoint: Remove Classes from an element with jQuery](http://www.freecodecamp.com/challenges/waypoint-remove-classes-from-an-element-with-jquery#?solution=fccss%0A%20%20%24(document).ready(function()%20%7B%0A%20%20%20%20%24(%22button%22).addClass(%22animated%20bounce%22)%3B%0A%20%20%20%20%24(%22.well%22).addClass(%22animated%20shake%22)%3B%0A%20%20%20%20%24(%22%23target3%22).addClass(%22animated%20fadeOut%22)%3B%0A%20%20%20%20%24(%22%23target1%22).removeClass(%22btn-default%22)%3B%0A%20%20%20%20%24(%22%23target2%22).removeClass(%22btn-default%22)%3B%0A%20%20%20%20%24(%22%23target3%22).removeClass(%22btn-default%22)%3B%0A%20%20%20%20%24(%22%23target4%22).removeClass(%22btn-default%22)%3B%0A%20%20%20%20%24(%22%23target5%22).removeClass(%22btn-default%22)%3B%0A%20%20%20%20%24(%22%23target6%22).removeClass(%22btn-default%22)%3B%0A%20%20%20%0A%20%20%7D)%3B%0Afcces%0A%0A%3C!--%20You%20shouldn't%20need%20to%20modify%20code%20below%20this%20line%20--%3E%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%20%3Ch3%20class%3D%22text-primary%20text-center%22%3EjQuery%20Playground%3C%2Fh3%3E%0A%20%20%3Cdiv%20class%3D%22row%22%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23left-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22left-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20target%22%20id%3D%22target1%22%3E%23target1%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20target%22%20id%3D%22target2%22%3E%23target2%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20target%22%20id%3D%22target3%22%3E%23target3%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3Cdiv%20class%3D%22col-xs-6%22%3E%0A%20%20%20%20%20%20%3Ch4%3E%23right-well%3C%2Fh4%3E%0A%20%20%20%20%20%20%3Cdiv%20class%3D%22well%22%20id%3D%22right-well%22%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20target%22%20id%3D%22target4%22%3E%23target4%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20target%22%20id%3D%22target5%22%3E%23target5%3C%2Fbutton%3E%0A%20%20%20%20%20%20%20%20%3Cbutton%20class%3D%22btn%20target%22%20id%3D%22target6%22%3E%23target6%3C%2Fbutton%3E%0A%20%20%20%20%20%20%3C%2Fdiv%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
  $(document).ready(function() {
    $("button").addClass("animated bounce");
    $(".well").addClass("animated shake");
    $("#target3").addClass("animated fadeOut");
    $("#target1").removeClass("btn-default");
    $("#target2").removeClass("btn-default");
    $("#target3").removeClass("btn-default");
    $("#target4").removeClass("btn-default");
    $("#target5").removeClass("btn-default");
    $("#target6").removeClass("btn-default");
   
  });
</script>

<!-- You shouldn't need to modify code below this line -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn target" id="target1">#target1</button>
        <button class="btn target" id="target2">#target2</button>
        <button class="btn target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn target" id="target4">#target4</button>
        <button class="btn target" id="target5">#target5</button>
        <button class="btn target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```

**Comment by BerkeleyTrue** [comment]
@revathynair Please reset the code. Looks like you manipulated the html and that is failing your tests. You should only use jQuery to edit the html. The jQuery code you wrote is correct.

The button classes are originally 
```html
<button class="btn btn-default target" id="target1">#target1</button>
```
Happy Coding!
