### ISSUE TITLE
Improve Italian translation of README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by f0ffee** [freeCodeCamp/freeCodeCamp#37043]
Italian mother tongue here. The Italian translations of README.md and CONTRIBUTING.md feel somewhat "mechanical", like they were translated automatically or word for word. They are still readable, but most sentences feel weird, and I feel like there's much room for improvement.

If it's okay, I would love to work on them.

**Comment by raisedadead** [comment]
Yes please.

**Comment by f0ffee** [comment]
Great! Working on it.

**Comment by moT01** [comment]
Translation PR's are welcome without an issue. Thanks for contributing @f0ffee 🎉
