### ISSUE TITLE
Bonfire: Steamroller - Unresponsive script

### ISSUE THREAD

**Issue by pwdd** [FreeCodeCamp/FreeCodeCamp#3704]
Challenge [Bonfire: Steamroller](http://freecodecamp.com/challenges/bonfire-steamroller) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0</code>.

The alert message that says that there is an `unresponsive script` also says this:
`Script: http://freecodecamp.com/js/com…-17f49f1fa1.js line 856 > eval:4`

My code:
```
function steamroller(arr) {
  var result = [];
  
  for (i = 0; i < arr.length; i++) {
    if (!Array.isArray(arr[i])) {
      result.push(arr[i]);
    } else {
      result = result.concat(steamroller(arr[i]));
    }
  }
  return result;
}

steamroller([1, [2], [3, [[4]]]]);

```
What I tried:
- clear the cache;
- change browser (besides Firefox, tried on Chrome and Safari);
- reset code;
- rewrite my code;
- going back to previous bonfire (drop it), run tests on previous bonfire (it works), go to bonfire 
steamroller. 

Nothing worked. The page is unresponsive.

**Comment by SajibDevnath** [comment]
check in `strict mode`
this may work:
```js
function steamroller(arr) {
  'use strict'
  var result = [];
  
  for (var i = 0; i < arr.length; i++) {
    if (!Array.isArray(arr[i])) {
      result.push(arr[i]);
    } else {
      result = result.concat(steamroller(arr[i]));
    }
  }
  return result;
}
```

**Comment by pwdd** [comment]
Hi! Thanks for your help. After cleaning cache and resetting the previous code, it works.
