### ISSUE TITLE
Nav logo should be served a react svg component

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#37045]
Nav logo should be served a react svg component

https://github.com/freeCodeCamp/freeCodeCamp/blob/c52c36e51ec48d3df1126b7a143da54c182ed948/client/src/components/Header/components/NavLogo.js#L3

[Take a look at the other logos](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/assets/icons) in the codebase for reference.

The alt text should read: 'freeCodeCamp.org'

https://github.com/freeCodeCamp/freeCodeCamp/blob/c52c36e51ec48d3df1126b7a143da54c182ed948/client/src/components/Header/components/NavLogo.js#L9

**Comment by raisedadead** [comment]
Removing the first timers, because it may not be very trivial.

**Comment by nawazishali** [comment]
I would love to get this done. Please assign it to me.

**Comment by raisedadead** [comment]
Issue assignment is not necessary, we accept the first valid PR, which follows our contribution guidelines.

**Comment by nawazishali** [comment]
@raisedadead Thanks for the heads up, I thought we still followed the assignment rule like in the past. I will submit a PR soon.

**Comment by raisedadead** [comment]
There you go, making an exception because of your interest :) 
Happy contributing!

**Comment by raisedadead** [comment]
Hi @nawazishali how is this coming along. Are you still working on this?

**Comment by nawazishali** [comment]
Hi @raisedadead 

I will be making a PR today hopefully. Was stuck in some other work.

**Comment by nawazishali** [comment]
Hi @raisedadead 

I ran into an Eslint issue, when I converted SVG to JSX the svg path code is so lengthy that I get 
`Line 13 exceeds the maximum line length of 80`

Any hint on how I can manage this? tried running the `npm run format:js` but it doesn't work.

**Comment by raisedadead** [comment]
You should be able to wrap using the lines at 80 in your code editor if you happen to use VS Code? 

Let's make a PR or share a link to your repo/branch for more context. 

Thanks.

**Comment by nawazishali** [comment]
Created a PR with ESLint max-len disabled. I tried wrapping the code to multiple lines but some string blocks are very long and would break the svg if put on a new line.
