### ISSUE TITLE
Bonfire: Smallest Common Multiple -issue while waiting for results

### ISSUE THREAD

**Issue by smarshy** [FreeCodeCamp/FreeCodeCamp#3705]
Challenge [Bonfire: Smallest Common Multiple](http://freecodecamp.com/challenges/bonfire-smallest-common-multiple] has an issue.

Please describe how to reproduce this issue, and include links to screenshots if possible.

The code passes for the given test cases.Maybe it wasn't check for larger numbers because it consumes too much of time.However,in that case ,wouldn't it be better to display a proper error timeout message or maybe specify in the instructions that it is expected to run for smaller numbers  itself.I tried checking my code with numbers greater than 50 and i was left blankly staring at the screen for a lot of time.It leaves you wondering if the code written just luckily passed the test cases and whether the program is running or did the browser hang.

My code:
```
function smallestCommons(arr) {
  var small=Math.min(arr[0],arr[1]);
  var large=Math.max(arr[0],arr[1]);
  var flag=0;
  var mult=1;
  for(var i=small;i<=large;i++)
    {
      mult=mult*i;
    }
  for(var i=large;i<mult;i++)
    {flag=0;
      for (var j=small;j<=large;j++)
        {
          if ((i%j)!=0)
            {
              flag=1;
            }
        }
     
     if (flag==0)
       {
         mult=i;
         break;
       }
    }
  return mult;
}

smallestCommons([1,5]);
```

**Comment by jlslew** [comment]
Thank you for posting.

The program is timing out when testing with `smallestCommons([1,50])` and you can see that in the console `resetting on fatal plugin error`.  The reason why there are no feedback is because of the line [345](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/commonFramework.js#L345-L350), `common.challengeType` for this challenge is "5".
```
if (common.challengeType === 0) {
  codeOutput.setValue(
    'Sorry, your code is either too slow, has a fatal error, ' +
    'or contains an infinite loop.'
  );
}
```
Do they want the if statement removed or change the value of `common.challengeType`?
/cc @BerkeleyTrue

**Comment by BerkeleyTrue** [comment]
This code passes fine on my end

**Comment by jlslew** [comment]
Sorry for pinging you, I guess I need a better computer.

![bonfire smallest common multiple free code camp - chromium_006](https://cloud.githubusercontent.com/assets/1538744/10529422/e737b754-736b-11e5-86c4-4822bebaee65.png)

**Comment by BerkeleyTrue** [comment]
No apologies needed. Feel free to ping me.

**Comment by ltegman** [comment]
Closing this since I can not repro and our current loop protection can be disabled if there is a false positive.
