### ISSUE TITLE
Algolia keys in sample.env

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37076]
Is there any reason not to put the real `ALGOLIA_APP_ID` and `ALGOLIA_API_KEY` in `sample.env`?

I reflexively put in a dummy key when I set this up, but now that I revisit this, that seems like a mistake.

**Comment by raisedadead** [comment]
Yes, actually it broke the .dev build unsurprisingly 🤦‍♂ , I think @RandellDawson noticed it and reported in the team chat.

The real fix is to ignore and move ahead when the keys are not available are default. We do this with google application credentials.

**Comment by ojeytonwilliams** [comment]
Oh, I assume it broke the build because .dev isn't using sample.env.  I didn't think of that...

So, we should implement the fix and add the public keys to `sample.env`, right?

**Comment by raisedadead** [comment]
I was thinking something more along the lines of (example from api-server):

```js
  if (secretInvalid || publicInvalid) {
    if (process.env.FREECODECAMP_NODE_ENV === 'production') {
      throw new Error('Stripe API keys are required to boot the server!');
    }
    console.info('No Stripe API keys were found, moving on...');
    done();
  } else {
```

I would try to avoid hundreds of contributors hitting the indexes locally. Ideally people should get their own keys. 

While the key and index is public, it's still not recommended to hit it?

**Comment by raisedadead** [comment]
As for the keys, it's actually fine because the build should fail. I have since added the keys in the build pipeline.

**Comment by ojeytonwilliams** [comment]
One thing: if we don't want contributors spamming search (fair enough!) I think there should be some docs that let people know what's what.  Either that search isn't available in development or the steps they need to take to make it work.

**Comment by raisedadead** [comment]
I agree. We should add some docs on getting keys, or perhaps creating a test index and sharing that instead
