### ISSUE TITLE
Show Completed and Remaining hours of Practice

### ISSUE THREAD

**Issue by sanspace** [FreeCodeCamp/FreeCodeCamp#3708]
Out of the 800 hours of Practice, it'd be great to know if we could see our progress.

It'd also be interesting to compete with your peers when you see your position. We'll spend more time camping this way.

**Comment by abhisekp** [comment]
Yes. It would be interesting to see a ranking of some kind like this http://fcctop100.herokuapp.com/
But it's not possible to show the hours of progress remaining because it varies from person to person. Some might take 1000 hrs while some might complete in 200 hrs.

**Comment by sanspace** [comment]
I understand that the completion time varies and everybody can learn at
their own pace.

However, as we say it's 800 hours of practice, we could also say that
someone's got 600 left. One might complete it within 600 while another may
take 800 or more.

When I said it would make one spend nurse hours, I meant they'll invest
more hours camping. Not that they'll rush through the lessons. Because no
matter when you finish, it's what you learn that matters.

Let's see what @QuincyLarson thinks.

**Comment by oharrison** [comment]
I think this is a good idea. I like seeing progress bars. It's understandable that everyone is working at different paces and hence, will complete the material at different times. However, in the same way that FCC claims an estimated time of 800 hours for completion, an estimated remaining time should be calculable. I don't really think its accuracy matters a great deal, its just really nice to see how far you have come, and how far you have to go. 

It might also be the case where the time in hours is not displayed, but instead a percentage completed. This would be similar to how video games display the percentage of the game one has already completed.
