### ISSUE TITLE
guide.freecodecamp.org contributing url pointed to the old repo

### ISSUE THREAD

**Issue by maxloh** [freeCodeCamp/freeCodeCamp#37087]
**Describe the bug**
guide.freecodecamp.org contributing url pointed to the old repo (freeCodeCamp/guide)

**To Reproduce**
1. Go to `guide.freecodecamp.org`
2. Click on `Help our community expand it`

**Expected behavior**
The url should direct me to this repo

**Comment by raisedadead** [comment]
We have permanently moved the guide for general articles: See #36729 The links will be updated in the next release in the upcoming weeks.

Thanks for your patience.

**Comment by RandellDawson** [comment]
@maxloh There is no longer a Guide in this repo, so the link is technically correct.  The decision was made to get rid of the Guide a little while back.

@raisedadead Should this issue be closed?
