### ISSUE TITLE
Portfolio doesn't update until hard reload

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#37085]
1. Go to your profile settings page
2. Change the privacy setting
3. go to the top and click `show me my public portfolio`

The privacy setting you changed will not have taken effect. 

From there, you can go back to the settings using the settings button, and the privacy setting will still show it as it was before you changed it.

I believe this is due to using [gatsby Link](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/client-only-routes/ShowSettings.js#L185) to navigate to the portfolio. The setting will have actually changed in the DB, but the effects won't show until you do a hard reload.

**Comment by moT01** [comment]
I can fix this if it's decided to change it.

**Comment by ojeytonwilliams** [comment]
As far as I can see, the problem is that the user is only pulled from the server once.  The server is getting updated correctly, but the redux store isn't being asked to mirror these changes.

**Comment by ahmadabdolsaheb** [comment]
as @ojeytonwilliams, there seems to be an issue with a redux reducer.

**Comment by raisedadead** [comment]
I was speaking to @Bouncey earlier and he says:

> Take a look at the `updateUserFlagSaga`. The `updateUserFlagComplete` action shouldn't need the `response` message, and the update becomes nested on the user at `<username>.payload`

**Comment by ojeytonwilliams** [comment]
Is someone looking into this (@moT01)?  Otherwise I can take a crack at it tomorrow.

**Comment by moT01** [comment]
Go for it @ojeytonwilliams - let me know if you want to team up on it.
