### ISSUE TITLE
Projects: use next challenge's seed as a solution

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37097]
**Is your feature request related to a problem? Please describe.**

The new project based curriculum typically uses the solution to challenge `n` as the seed for challenge `n + 1`.  As such, there's a lot of code duplication.

**Describe the solution you'd like**

The ability to reference another challenge and import it's seed as a solution.  Perhaps using the following template:
```md
## Solution
<section id='solution'>

<div id='challenge-solution' seed-id='id-of-the-next-challenge'>
</div>

</section>
```

As yet I've not put much time into working out how feasible this is, I just noticed @scissorsneedfoodtoo's comment https://github.com/freeCodeCamp/freeCodeCamp/pull/36873#issuecomment-538846699 and thought it was worth discussing.

Edit: I mixed up the seed and the solution, fixed now.

**Comment by scissorsneedfoodtoo** [comment]
I'm all for this as copying and pasting slightly modified code into the solution section will be pretty tedious for these projects.

**Comment by moT01** [comment]
I like this - I recently copy/pasted all the seed code to the solution area for one of my projects. Which makes for a lot of code in each challenge file - this would simplify things a lot I think and make them easier to maintain.

**Comment by ojeytonwilliams** [comment]
Yep, I think this is pretty much the definition of tedious and error prone.

So, now I'm thinking of reasons *not* to do it.  If you were to link to the wrong challenge, it could be pretty confusing.  How about, instead of 

```html
<div id='challenge-solution' seed-id='id-of-the-next-challenge'></div>
```
it's just 

```html
<div id='next-challenge-seed'></div>
```

and when a div with that id is found the solution is obtained automatically by querying the appropriate `meta.json` to find the next challenge.

**Comment by scissorsneedfoodtoo** [comment]
@ojeytonwilliams, using the `meta.json` file to query the next file for the solution section sounds like a good idea. Even when we start to support multiple files/directories, we'll still essentially be testing one file at a time.

**Comment by ojeytonwilliams** [comment]
I'm closing this since, when a solution is missing, challenge n automatically uses challenge n + 1's seed as it's solution.
