### ISSUE TITLE
When going to the next question the code doesn't load.

### ISSUE THREAD

**Issue by jgreen82** [FreeCodeCamp/FreeCodeCamp#3711]
Challenge [Waypoint: Use Clockwise Notation to Specify the Margin of an Element](http://freecodecamp.com/challenges/waypoint-use-clockwise-notation-to-specify-the-margin-of-an-element#?solution=) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Code doesn't load and nothing displays on the ipod. I'm able get it to work by using reset.

![free-code-camp-bug](https://cloud.githubusercontent.com/assets/957327/10417832/50045bf0-7017-11e5-8253-0c014138dc76.png)

**Comment by ltegman** [comment]
Is this still happening for you? I am unable to repro this in Firefox 41 on OSX.

**Comment by natalka01** [comment]
I had that issue for a bunch of them a few days ago too, in the html & jQuery sections, but hasn't happened lately. Using chrome, win8.1 laptop. Also fixed via opening either from Map (right-click "Open in new tab") or via Reset button in teal on screengrab above.

**Comment by jgreen82** [comment]
I believe it could be a computer slowness issue. I had a lot of tabs and
programs run at the time.

**Comment by BerkeleyTrue** [comment]
@jgreen82 If the issue is resolved please close it.

Happy Coding!

**Comment by jgreen82** [comment]
Issue seems to be caused by computer / browser slowness and not to be caused by FreeCodeCamp.

If it should happen again I'll try to take a closer look at what's going on. But for now, I'm closing the issue.
