### ISSUE TITLE
Docs: search on developer machines

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37115]
**Is your feature request related to a problem? Please describe.**
Without Algolia keys a contributor cannot use the search feature on their local machine, limiting their ability to contribute in this area.

**Describe the solution you'd like**
The documentation should include instructions on how to get keys or set up a 'mock' search: https://github.com/freeCodeCamp/freeCodeCamp/issues/37076#issuecomment-539172200.

**Comment by raisedadead** [comment]
For me, I think very few people would work on the search itself. So, we would be okay to getting asked for developer keys on a need basis.

And as for everyone else, will it be possible to render a message like "search is not available during dev" in the dropdown?

/cc @scissorsneedfoodtoo

**Comment by scissorsneedfoodtoo** [comment]
I wouldn't mind having a public API key and app ID available in case someone wants to work on the search components or tests.

We have a dev app available on Algolia that I can set up with the News index. I believe there's a limit on 50,000 operations a month for dev apps, which should be enough for anyone who wants to work on the search. If we hit the limit Algolia should just return an error for the rest of the month.
