### ISSUE TITLE
tab text should be visible on mobile

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#37137]
to reproduce, view any lesson in a screen narrower than 750px and hover on a tab

<img width="643" alt="Screen Shot 2019-10-09 at 11 21 29 AM" src="https://user-images.githubusercontent.com/4591597/66464816-59874580-ea88-11e9-91d1-b88b6fc89f80.png">

**Comment by marwicha** [comment]
i'd like to take this issue please

**Comment by ahmadabdolsaheb** [comment]
@marwicha please go ahead.

**Comment by ahmadabdolsaheb** [comment]
Just a friendly reminder that the first submitted pr will be considered for the review process regardless of assignment.

**Comment by wincentrtz** [comment]
Hello I am new to open source can I work on this?

**Comment by ahmadabdolsaheb** [comment]
@wincentrtz, please go ahead with submitting your solution as a pr.

**Comment by rickysyamsi** [comment]
Hi @ahmadabdolsaheb, I can't reproduce this on my local dev and https://freecodecamp.dev. The tab menu is in light gray with black text. Hover state make it slightly darker. Both state are easily readable.

Is it already fixed? or Am I missing something obvious?

![Screen Shot 2019-10-13 at 12 59 34](https://user-images.githubusercontent.com/54201112/66716208-b9e4f280-edba-11e9-8b1b-a0127839804e.png)

**Comment by scissorsneedfoodtoo** [comment]
@rickysyamsi, seems like you're in day mode which doesn't have this problem. Log in to freecodecamp.dev then go to Portfolio, Update my Settings, and switch to night mode. Then when you hover over these tabs in the mobile view you'll see the light colored tabs and text like in the OP.

**Comment by ahmadabdolsaheb** [comment]
Thank you for your interest @rickysyamsi,

So ```a:not(.fcc_suggestion_item):hover {``` on global.css is a very specific selector that overrides any class selector.

I would double check this issue after #37208 goes through to see if this issue can still be reproduced.

**Comment by rickysyamsi** [comment]
@scissorsneedfoodtoo @ahmadabdolsaheb Thank you for the responses guys.

I can reproduce this issue with night mode enabled.

I also still able to reproduce this issue with changes from PR #37208 copied to my local dev.

I can solve the issue with a specific selector that already exists in `classic.css`, I just add the necessary hover state.

```
#challenge-page-tabs .nav-tabs > li > a:hover {
  color: var(--secondary-background);
}
```

`var(--secondary-background)` is derived from hover state color of footer tab menu (Help, Video, Hint, Reset, Run) so it looks consistent.

I think that using a specific selector is a good approach to make sure that there are no unintended side effects. What do you guys think about this?

**Comment by ahmadabdolsaheb** [comment]
@rickysyamsi thanks for investigating that. yes that would be a good approach.
I look forward to your the PR.

**Comment by rickysyamsi** [comment]
@ahmadabdolsaheb You're welcome. I'm glad to help :)
