### ISSUE TITLE
Can submit multiple challenges with Ctrl+Enter

### ISSUE THREAD

**Issue by matjack1** [freeCodeCamp/freeCodeCamp#37131]
I'm testing beta.

**Describe the bug**
When submitting a challenge using Ctrl+Enter it automatically completes also the following challenge.

**To Reproduce**
1. As a logged out user
2. Go to the first challenge
3. Complete it
4. Press Ctrl+Enter
5. it marks as solved also the following challenge and you can go ahead

**Expected behavior**
It should solve the current challenge and present the following one.

**Screenshots**
As you can see I can submit multiple challenges:
![Peek 2019-10-08 19-33](https://user-images.githubusercontent.com/65402/66419479-7f6b0680-ea04-11e9-9836-45f5f9496c98.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 69.0.1

**Additional context**
I've been able to reproduce it on freecodecamp.dev but I could skip only one challenge. On my local dev I managed to skip 4.

**Comment by matjack1** [comment]
I've digged a bit on this issue, and I think the problem is somehow related to this line: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/templates/Challenges/components/Hotkeys.js#L36

As this is triggered also when I'm submitting the finished challenge.

If I comment that line out everything works fine, meaning I can Ctrl+Enter to run the tests and submit and the bug disappear. I'm going to dig a bit more, but does that makes any sense to you?

**Comment by raisedadead** [comment]
Thanks for testing our beta version @matjack1 and reporting this! You rock.

/cc @ojeytonwilliams

**Comment by ojeytonwilliams** [comment]
Thanks @matjack1!  It looks like I didn't test the logged out behaviour.

@raisedadead so, what do we want to happen for logged out users?  The issue I see is that it currently says '*Submit* and go to the next challenge', but clearly they can't submit.  For now, do we just want them to see the same as logged in users (and quietly not submit)?

**Comment by raisedadead** [comment]
Here is what I would do:

![image](https://user-images.githubusercontent.com/1884376/66461820-75deae80-ea97-11e9-9cc1-660e771b10f2.png)

Of course the modal should close as well like you mentioned

**Comment by ojeytonwilliams** [comment]
Turns out it's not working properly even when the user is logged in.  I think it's a race condition between `submitChallenge` and `executeChallenge`.  

@matjack1 was quite right, the problem is on that line.  It shouldn't be called if the modal is open since it's listening to `ctrl + enter` as well.

**Comment by matjack1** [comment]
yes @ojeytonwilliams I think it's with the `ctrl + enter` in the editor and the `ctrl + enter` in the `Hotkey`.

I can give a further look later if you wish.

**Comment by ojeytonwilliams** [comment]
Thanks for the offer @matjack1, but I think (with your help!) I've fixed it.  It seemed only fair, since I introduced the bug.

**Comment by matjack1** [comment]
Excellent!

**Comment by raisedadead** [comment]
Release on its way, should be available within the hour.
