### ISSUE TITLE
[Beta] Portfolio description is not wrapping at the boundary

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#37141]
**Describe the bug**
A long description of a portfolio item doesn't wrap at the boundary.
![Screenshot (25)](https://user-images.githubusercontent.com/26724128/66479311-ded71e00-eab9-11e9-9958-1109e10191dd.png)

**To Reproduce**
1. Go to the settings page
2. Put a long description in the portfolio item
3. Check out the public portfolio (hard refresh it ctrl+f5; this update bug is under triage)

**Expected behavior**
The description should wrap at the boundary of div.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 32 Bit Pro
 - Browser: Chrome
 - Version: 77.0.3865.90

**Comment by vkWeb** [comment]
@raisedadead I'm not able to update the labels. How can I do that?

**Comment by raisedadead** [comment]
> I'm not able to update the labels. How can I do that?

That is fine, the mods team will do it for you.

**Comment by vkWeb** [comment]
@raisedadead I would like to help with this. It's been very long since I have contributed to the main repo. 😅

**Comment by raisedadead** [comment]
Sure, Follow our [guidelines for contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md) and make a PR

**Comment by ahmadabdolsaheb** [comment]
I see a green-line above the description. @vkWeb while at it, could you please style it to make it consistent with the rest of hr tags.

**Comment by vkWeb** [comment]
>I see a green-line above the description. @vkWeb while at it, could you please style it to make it consistent with the rest of hr tags.

@ahmadabdolsaheb Yes, I'll make the requested changes. Actually, yesterday I wasn't able to set up the local copy so today I am trying gitpod.  

- [ ] fix word wrap in all places: portfolio title, description
- [ ] make green line consistent with hrs
- [ ] disable textarea horizontal resize
