### ISSUE TITLE
Remove introduction pages, make descriptions concise and inline on map

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#37144]
**Describe the bug**
Go to a challenge which is just after introduction, e.g. [use-display-flex-to-position-two-boxes](https://www.freecodecamp.dev/learn/responsive-web-design/css-flexbox/use-display-flex-to-position-two-boxes) and press 'p', it takes us back to the previous challenge. It should take us back to the introduction part. 

'n' (next challenge) works fine in this case. A sanity check: go to a challenge which is before an introduction part, e.g. [make-typography-responsive](https://www.freecodecamp.dev/learn/responsive-web-design/responsive-web-design-principles/make-typography-responsive) and press 'n'. It takes us to the introduction of the next part which is indeed expected.

*Note:* The hotkeys ('n' and 'p') are not working on introduction parts. I think it's intentional. If it is not then it should be fixed and work like normal challenges.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 32 Bit Pro
 - Browser: Chrome
 - Version: 77.0.3865.90

**Comment by raisedadead** [comment]
We are soon removing the introduction pages completely in favor of a more streamlined navigation. The explanation on the intro pages will be made more concise.

The current behaviour is correct.

I am re-categorizing this as feature request

**Comment by vkWeb** [comment]
@raisedadead I think we should not do this. If we make them inline on map then users won't be able to read it when through the `learn` platform, right? I hope you are getting my point.

Also, the introduction part is very important in some cases. e.g. https://www.freecodecamp.dev/learn/javascript-algorithms-and-data-structures/functional-programming/ and most of them are already pretty concised.

**Comment by raisedadead** [comment]
Yes, and we have debated that we would rather have the introductions as challenges or inline.

On a very honest note one reads though the introductions. People are in a hurry. The challenges should rather incorporate the concepts from the introductions.

Finally with the upcoming navigation changes, the optional challenges (and focus on completing them) will become lesser of the focus.

We are working on the map to not be linear any more. I would advise you should probably wait until those changes are ready and share your feedback.

**Comment by vkWeb** [comment]
>On a very honest note one reads though the introductions. People are in a hurry. The challenges should rather incorporate the concepts from the introductions.

@raisedadead If it will be possible to incorporate the concepts from the introductions to challenges then it'll be cool. 
But I personally believe that the introduction part is a good way to tell campers what they will study in the upcoming lessons. 

> We are working on the map to not be linear any more. I would advise you should probably wait until those changes are ready and share your feedback.

Okay, I'll wait to for future releases and then I'll share my feedback.

**Comment by moT01** [comment]
My opinion - I don't have any problem with how the introductions currently are - If people want to skip them, they can.

**Comment by raisedadead** [comment]
>  If people want to skip them, they can.

Which most people do. However, the way they are structured is sort of messy, as Oliver noted previously. Instead, it would rather be nice to incorporate as actual challenges or make them inline.

**Comment by thecodingaviator** [comment]
@raisedadead Do you want a new issue/new issues to track the progress for individual superblock introduction merges?

**Comment by moT01** [comment]
So what is behavior we are wanting here? It's not clear to me.

**Comment by raisedadead** [comment]
I never got the time to work on this, but the idea is to be able to move the existing pages in the intro section and convert them into regular challenges instead OR meld some of the verbiage from nicely into the first challenge in that block.

These intro pages aren't much of use because users are in hurry.

With the upcoming projects we would definitely have any, removing these would make it more consistent.

Also, the idea was to be able to make our linear map into pages, where the list of challenges for that certification is available on its own page. Removing the need for dropdown, making the navigation simpler and potentially faster page loads.

**Comment by ahmadabdolsaheb** [comment]
related https://github.com/freeCodeCamp/freeCodeCamp/issues/38820

**Comment by raisedadead** [comment]
Closing in favor of #38820
