### ISSUE TITLE
Heat map squares have rounded corners in Chrome browser

### ISSUE THREAD

**Issue by hugoender** [FreeCodeCamp/FreeCodeCamp#3715]
this may seem nit picky but it really bothers me… the heatmap squares in the user profile page look ugly in chrome browser. In safari browser they are nice little squares like in github…but in chrome browser, the corners of the square are rounded. Could you please fix this? I have attached screenshots showing the difference.

Safari:
![screen shot 2015-10-11 at 10 25 37 pm](https://cloud.githubusercontent.com/assets/6217175/10420696/61902bec-7067-11e5-99ec-e2de24a0d6d9.png)

Chrome:
![screen shot 2015-10-11 at 10 25 19 pm](https://cloud.githubusercontent.com/assets/6217175/10420698/62f7ffaa-7067-11e5-9cd6-c0eac452d79e.png)

**Comment by BerkeleyTrue** [comment]
@hugoender We are an open source community, do you mind submitting a pull request? It is a good way of giving back and gaining experience at the same time.

**Comment by hugoender** [comment]
@BerkeleyTrue I would LOVE to submit a pull request except that I do not know why it looks different in Chrome vs Safari not to mention how I would go about fixing it in the FreeCodeCamp source code. I know how to fork, branch, commit, and submit a pull request... it's just the part of how to actually find the file in question in order to fix the code that escapes me. If I could find the file then I could go about researching this topic further and try to solve it.

That said, it would be an honor if you could show me how to go about figuring out where the code for the problem is. I did an Inspect Element on the page and found the code for the squares (it uses SVG crispedges) but once I go to the FCC repo, I cannot seem to find the file responsible for this code I inspected. Help me Obi-wan Berkeley... you're my only hope! ;)

**Comment by jlslew** [comment]
Chrome is actually rendering it correctly whereas Safari and Firefox are having trouble.
![selection_003](https://cloud.githubusercontent.com/assets/1538744/10433426/c5637016-70df-11e5-83a3-1e5e67e9c96f.png)

They are using this library; https://github.com/wa0x6e/cal-heatmap (bower search cal-heatmap) and the code that displays the heatmap can be found in the `server/views/account/show.jade` file.

**Comment by hugoender** [comment]
@jlslew I would argue that Chrome is NOT rendering it correctly. If you go to the cal-heatmap page (http://cal-heatmap.com/) there you can see that the corners should not be rounded like they are in Chrome. 

That said, the fact that the code that controls these squares is in a .jade file (which I have never seen nor heard of before) probably means that I do not have the knowledge necessary to fix such an issue. Therefore, my issue submission still stands.

**Comment by BerkeleyTrue** [comment]
I don't know which one is the default. It could be either way as I do not see any css explicitly giving the rounded effect.

I personally don't think this a big deal. Most people do not switch back and forth between browsers. And most wouldn't notice such a trivial detail even if they did. I didn't. @QuincyLarson didn't when he put the code together months ago. No one till now has either. 

That being said and since pandoras box has been opened, if someone wants to take the time to open a PR then we will accept it.

**Comment by hugoender** [comment]
@BerkeleyTrue The default, or what the squares should look like, is obviously the non-rounded squares since that is how it looks on Github (which I assume is what this is trying to emulate) as well as on the cal-heatmap.com site itself (which, based on @jlslew's response, is where this plugin came from).

It is definitely not a big deal but it's something I noticed from the beginning when I started FCC. At first I figured you guys gave it that style but then when I used a different browser I realized this was not the case. It looks SO much nicer when they are normal squares and not rounded.  

I understand that you guys are busy with other more pressing matters and indeed this would be an issue that could probably be solved by someone in the community. I only wish I had the experience/knowledge to be the one to fix it since I have been dying to submit a PR that gets merged :wink: 

You guys have done and continue to do a fantastic job with FCC and I commend all of you for your hard work and dedication. Maybe one day I will have learned enough to join the FCC team and be in charge of pixel perfect design :smile:

**Comment by BerkeleyTrue** [comment]
@hugoender Thanks for the kind words :blush:

**Comment by hugoender** [comment]
@BerkeleyTrue @jlslew I FOUND IT!!!! I found the issue! I am at work right now so I cannot fork, branch, commit, and pull request but once I get home I will! Please no one solve this until then LOL!

**Comment by BerkeleyTrue** [comment]
:exclamation:

**Comment by Takumar** [comment]
@hugoender do you mean this line?
```
cal.init( ....
cellRadius: 3,
...
```

Personally I like that rounded squares much better than that on GitHub so I would not change it.
I also checked FCC page on Firefox, IE, Chrome and in all browsers squares are rounded, I don't have Safari but it looks that Safari have problem displaying them as squares.

Wow, I first looked at code of FCC. @BerkeleyTrue you should be afraid if I'll try to correct your code ;-)

**Comment by hugoender** [comment]
@Takumar Why you gotta ruin it for me!? lol Yes, that is what I am referring to. I just checked using IE and Firefox and interestingly enough, IE shows it with rounded corners but Firefox doesn't even show the heatmap! I have attached a picture of what I see in Firefox. 

Based on the fact that a cellRadius of 3 is explicitly assigned in the code means that @jlslew was right, and indeed Chrome is doing what it's supposed to be doing while Safari (and now Firefox) are not. 

I prefer square, @Takumar prefers rounded. So my argument of this being an issue because square looks better is moot. 

That said, I would argue that the cellRadius property should be removed since it causes browser compatibility issues. With "style" being subjective, all that is left is functionality and coherence/compatibility. Functionality is unaffected but coherence (cross-browser) is and thus I will still be submitting my PR and hoping for the judge...err... @BerkeleyTrue to rule in my favor :smile:
![capture](https://cloud.githubusercontent.com/assets/6217175/10438415/75d9785c-7101-11e5-92f1-a48b1c8cd2f9.PNG)

**Comment by Takumar** [comment]
@hugoender if really in Safari there is a difference in displaying these squares it could be a solution to change cellRadius to 0 (but it is a default value) so it would be displayed in the same way in all browsers.
I won't do that for you, because I haven't contributed to any source yet and I don't know Git very well. So work on that problem :+1:

**Comment by BerkeleyTrue** [comment]
If it is defined in code then a PR should find out how to get FF/Safari to render correctly instead of removing the cell radius.

**Comment by hugoender** [comment]
Alright so I just got home and checked on my Mac and Firefox (v.39) on my Mac displays the squares with the top half rounded and the bottom half not LOL! The plot thickens! 

@BerkeleyTrue I see your point but something is better than nothing so until someone can find the fix for the inconsistent behavior between browsers, I think my "fix" of reverting them to the more pleasant (imo) squares should suffice :wink:
![screen shot 2015-10-12 at 6 39 55 pm](https://cloud.githubusercontent.com/assets/6217175/10440861/cc209452-7110-11e5-9e38-a52fb08831b6.png)

**Comment by QuincyLarson** [comment]
@hugoender Thank you for bringing up this cross browser inconsistency. I actually chose the border radius myself and am rather attached to the round corners. Seeing that doesn't look particularly bad anywhere (squares, rounded squares, tombstone shapes) I don't think we need to take any action here.
