### ISSUE TITLE
adjust the font size on CTA buttons for small screens.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#37165]
The font size for the CTA could use similar breakpoints for the h1, h2. and set to 1.2 - 1.3 rem

![image](https://user-images.githubusercontent.com/4591597/66546354-82b9db80-eb45-11e9-8651-471df24e3601.png)

**Comment by Raibaz** [comment]
I'd like to work on this.

**Comment by KibarLak** [comment]
can i?

**Comment by drashti1712** [comment]
Where is this button?
