### ISSUE TITLE
Bonfire: Where art thou

### ISSUE THREAD

**Issue by EtwasShawn** [FreeCodeCamp/FreeCodeCamp#3717]
In Bonfire: Where art though the test where() should return an array of objects fails, although the other tests pass. In the results field it shows [{"a":5,"b":10}] which is an array with an object in it. Code to reproduce:

```javascript
function where(collection, source) {
  var arr = [];
  var sourceKeys = Object.keys(source);
  
  for (var i in collection){  
    var propCount = 0;   

    for(var j in sourceKeys){
     
      if(collection[i].hasOwnProperty(sourceKeys[j]) === true){
         propCount++;       
         }          
    }      
       if(propCount === sourceKeys.length){
        arr.push(collection[i]);
      }     
  }
  // What's in a name?
  
  return arr;
}

where([{ 'a': 5 }, { 'a': 5 }, { 'a': 5, 'b': 10 }], { 'a': 5, 'b': 10 });
```

**Comment by bugron** [comment]
@EtwasShawn thanks for posting this issue!
Actually, you're checking if your `collection[i]` has a key `sourceKeys[j]` **only** but you also need to check if `collection[i][sourceKeys[j]]` is equal to `source[sourceKeys[j]]`.
This is form the bonfires description:
>Make a function that looks through an array of objects (first argument) and returns an array of all objects that have **matching property and value pairs** (second argument). 

-
>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by bugron** [comment]
Closing this issue. Feel free to reopen if you still experience problems, thanks.
