### ISSUE TITLE
Add tests for backend projects

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#37185]
I am making a new issue to track the progress of this. Most of the backend projects have no tests; allowing any valid URL to be submitted to pass - more discussion here https://github.com/freeCodeCamp/freeCodeCamp/issues/36467

The purpose of creating tests here is simply to have something there, even if it's just one test, to make sure you can't just submit any random URL. Ideally, the tests would be thorough; but just one would do good enough for now, I think.

#### APIs and Microservices
- [x] [Timestamp](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/timestamp-microservice.md) - tests already exist
- [x] [Header Parser](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/request-header-parser-microservice.md) - PR merged - https://github.com/freeCodeCamp/freeCodeCamp/pull/37187
- [x] [URL Shortener](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/url-shortener-microservice.md) - PR merged - https://github.com/freeCodeCamp/freeCodeCamp/pull/39311
- [x] [Exercise Tracker](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/exercise-tracker.md) - PR merged - https://github.com/freeCodeCamp/freeCodeCamp/pull/37696
- [x] [File Metadata](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/file-metadata-microservice.md) - PR merged - https://github.com/freeCodeCamp/freeCodeCamp/pull/39625

#### Quality Assurance
- [x] [Metric Imperial Converter](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/06-quality-assurance/quality-assurance-projects/metric-imperial-converter.md) - PR merged - https://github.com/freeCodeCamp/freeCodeCamp/pull/37891
- [X] [Issue Tracker](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/06-quality-assurance/quality-assurance-projects/issue-tracker.md) - PR merged - https://github.com/freeCodeCamp/freeCodeCamp/pull/39627
- [X] [Personal Library](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/06-quality-assurance/quality-assurance-projects/personal-library.md) - PR merged - https://github.com/freeCodeCamp/freeCodeCamp/pull/39642
- [x] [Sudoku Solver](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/06-quality-assurance/quality-assurance-projects/sudoku-solver.md) - PR merged - https://github.com/freeCodeCamp/freeCodeCamp/pull/39816
- [x] [American British Translator](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/06-quality-assurance/quality-assurance-projects/american-british-translator.md) - PR merged - https://github.com/freeCodeCamp/freeCodeCamp/pull/39822

#### Scientific Computing with Python
~~- [ ] [Arithmetic Formatter](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/07-scientific-computing-with-python/scientific-computing-with-python-projects/arithmetic-formatter.md)~~ - can't add tests to learn without overhauling the project
~~- [ ] [Time Calculator](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/07-scientific-computing-with-python/scientific-computing-with-python-projects/time-calculator.md)~~ - can't add tests to learn without overhauling the project
~~- [ ] [Budget App](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/07-scientific-computing-with-python/scientific-computing-with-python-projects/budget-app.md)~~ - can't add tests to learn without overhauling the project
~~- [ ] [Polygon Area Calculator](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/07-scientific-computing-with-python/scientific-computing-with-python-projects/polygon-area-calculator.md)~~ - can't add tests to learn without overhauling the project
~~- [ ] [Probability Calculator](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/07-scientific-computing-with-python/scientific-computing-with-python-projects/probability-calculator.md)~~ - can't add tests to learn without overhauling the project

#### Data Analysis with Python
~~- [ ] [Mean-Variance-Standard Deviation Calculator](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-projects/mean-variance-standard-deviation-calculator.md)~~ - can't add tests to learn without overhauling the project
~~- [ ] [Demographic Data Analyzer](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-projects/demographic-data-analyzer.md)~~ can't add tests to learn without overhauling the project
~~- [ ] [Medical Data Visualizer](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-projects/medical-data-visualizer.md)~~ - can't add tests to learn without overhauling the project
~~- [ ] [Page View Time Series Visualizer](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-projects/page-view-time-series-visualizer.md)~~ - can't add tests to learn without overhauling the project
~~- [ ] [Sea Level Predictor](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-projects/sea-level-predictor.md)~~ - can't add tests to learn without overhauling the project

#### Infosec
- [X] [Stock Price Checker](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/09-information-security/information-security-projects/stock-price-checker.md) - PR merged - https://github.com/freeCodeCamp/freeCodeCamp/pull/39640
- [x] [Anonymous Message Board](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/09-information-security/information-security-projects/anonymous-message-board.md) - PR merged - https://github.com/freeCodeCamp/freeCodeCamp/pull/39652
~~- [ ] [Port Scanner](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/09-information-security/information-security-projects/port-scanner.md)~~ - can't add tests to learn without overhauling the project
~~- [ ] [SHA-1 Password Cracker](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/09-information-security/information-security-projects/sha-1-password-cracker.md)~~ - can't add tests to learn without overhauling the project
- [x] [Secure Real Time Multiplayer Game](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/09-information-security/information-security-projects/secure-real-time-multiplayer-game.md)

#### Machine Leaning with Python
~~- [ ] [Rock Paper Scissors](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/11-machine-learning-with-python/machine-learning-with-python-projects/rock-paper-scissors.md)~~ - can't add tests to learn without overhauling the project
~~- [ ] [Cat and Dog Image Classifier](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/11-machine-learning-with-python/machine-learning-with-python-projects/cat-and-dog-image-classifier.md)~~ - can't add tests to learn without overhauling the project
~~- [ ] [Book Recommendation Engine using KNN](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/11-machine-learning-with-python/machine-learning-with-python-projects/book-recommendation-engine-using-knn.md)~~ - can't add tests to learn without overhauling the project
~~- [ ] [Linear Regression Health Costs Calculator](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/11-machine-learning-with-python/machine-learning-with-python-projects/linear-regression-health-costs-calculator.md)~~ - can't add tests to learn without overhauling the project
~~- [ ] [Neural Network SMS Text Classifier](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/11-machine-learning-with-python/machine-learning-with-python-projects/neural-network-sms-text-classifier.md)~~ - can't add tests to learn without overhauling the project

Edit: I have updated this to include all the new projects - many of them may not be testable on our end - perhaps just one to make sure they don't submit the example project

**Comment by lkreimann** [comment]
Any suggestion on how to write a test here? I assume there aren't any examples I could look at.

**Comment by moT01** [comment]
There are some examples @lkreimann - I made a PR for the header parser project, linked above - the timestamp project has tests written, as well. And if you read through the other issue I linked, there's some more info to find.

These projects could use a little TLC in my opinion - it may be difficult to write tests for some of them.

**Comment by jenlky** [comment]
I would like to do this. Could you point me in the right direction? And do you think it should be split into two PRs? One for Microservices and one for infosec?

**Comment by ojeytonwilliams** [comment]
@jenlky it would be ideal if you could create a PR for each challenge you add tests for.  Doing so makes the review process easier.  Just reference this issue, so we know which PRs are still needed.

As for how to go about it, take a look at @moT01's PR.  He wrote tests that verify aspects of the project's api, when given a project url. So, the project is supposed to return a JSON object with the keys `ipaddress`, `language` and `software` and the three tests make sure each key is present.  

Just ask if you need any clarification.

**Comment by moT01** [comment]
The problem here is that many, or at least some, of the projects don't specify route names; so, in some cases, campers can use any routes they choose - making it impossible to hit them predictably. I mentioned this [here](https://github.com/freeCodeCamp/freeCodeCamp/pull/37122#issuecomment-541422838). So we may need to go into each project and clarify instructions so that the routes and parameters are predictable.

**Comment by ojeytonwilliams** [comment]
Yep.  I don't see any other way of making them testable, so I think they need a concrete API as part of the project.  If it's not obvious what the API for a project should be, maybe we could discuss that here?

**Comment by moT01** [comment]
I know that @cmccormack and maybe others were working on unifying a [repo for the backend projects](https://github.com/cmccormack/freecodecamp-backend-challenges) for a little while. I'm wondering if we should add that to fCC and use it to make changes to the projects. Then we can just import all the code from there to the current glitch projects - I think that was the plan when work was being done there. I'm not sure how much deviation there's been on that repo and what we now have.

**Comment by jenlky** [comment]
@moT01 I want to check if the user is actually redirected to a certain URL. To do that in Nodejs, I will need to require('url'). I can chain the code in the test case but it would be very messy and I prefer not to. Since the file is markdown, where should I require then?

**Comment by ojeytonwilliams** [comment]
`require` is out, I'm afraid.  The tests run in the browser's JavaScript engine, not node.

What you can do is use [fetch](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch).  So, something like

```yaml
    testString: 'getUserInput => fetch(getUserInput(''url'') + ''/redirect'').then(res => {
      if(!res.redirected) { throw "should be redirected"} }, error => { throw error })'
```
is how I'd check for redirects.  You can also get the url with `res.url` to verify it's redirecting to the right place.

**Comment by jenlky** [comment]
@ojeytonwilliams For URL Shortener, I need to POST URL (google for example) to shorten it and 
it should return `{ "original_url": "www.google.com", "short_url": 1 }`. When I access `$.get(getUserInput(''url'') + ''/api/shorturl/1'')`, I should be redirected to google.com.

I will need to either 1) store the original_url as a variable OR 2) POST and then GET in one function. Is there a way to do the first one because that would be cleaner and more readable?

Here's an excerpt of my test, second test incomplete:

```yml
tests:
  - text: 'It should handle a URL as parameter and return shortened URL'
    testString: 'getUserInput => $.post(getUserInput('url') + '/api/shorturl/new').then(data => assert.exists(data.short_url), xhr => { throw new Error(xhr.responseText)})'
  - text: 'It should handle a shortened URL and redirect to original link'
    testString: 'getUserInput => $.get(getUserInput(''url'') + ''/api/shorturl/3'').then()
```

**Comment by ojeytonwilliams** [comment]
It occurs to me that we should probably add tests that reject the Glitch project we provide for each project.

```yaml
tests:
  - text: 'You should supply your own project, not the example url'
    testString: 'getUserInput => assert(!(new RegExp( ".*/thread-paper\.glitch\.me\.*")).test(getUserInput("url")))'
```

Something like that.

**Comment by moT01** [comment]
FYI - there are [some tests written here](https://glitch.com/edit/#!/fcc-back-end-tester?path=public/tests.js:1:0) - There's no confirmation that they work or are complete, but it's a good place for examples.

**Comment by Aadhar3** [comment]
Hey, I would be interested in working on this issue by adding tests for URL shortener.

**Comment by ojeytonwilliams** [comment]
Thanks @Aadhar3, PRs are definitely welcome.

**Comment by PartyLich** [comment]
it isn't tracked here for some reason, but there appears to already be a #37588 for the url shortener tests

**Comment by Aadhar3** [comment]
Oh alright, i do not think there are tests for the File Metadata microservice.. I would like to contribute to that

**Comment by RandellDawson** [comment]
@Aadhar3 There are no other open PRs for the File Metadata Microservice, so feel free to submit a PR.

**Comment by Aadhar3** [comment]
I had a general question, on https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/file-metadata-microservice, why does a user have to submit both a glitch link and a github link?

**Comment by moT01** [comment]
That's just how it is at the moment @Aadhar3 - [There's an issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/37771) that plans to make the github link optional.

**Comment by jeremyfiel** [comment]
> FYI - there are [some tests written here](https://glitch.com/edit/#!/fcc-back-end-tester?path=public/tests.js:1:0) - There's no confirmation that they work or are complete, but it's a good place for examples.

Just FYI...File metadata test is working but it doesn't check if the user submitted the sample glitch.

**Comment by nhcarrigan** [comment]
Just to make sure this does not get overlooked - it looks like the **infosec** projects are now the **quality assurance** projects, and the "Stock Price Checker" and "Anonymous Message Board" were replaced by the "Sudoku Solver" and "American British Translator", respectively. 🙂

**Comment by moT01** [comment]
I looked through each section real quick, I believe each project that can have tests has at least the "You should submit your own project and not the example" test - and many of them have quite extensive tests - So I think we can finally close this. Thanks for all the hard work on this everyone 🎉 

If anyone notices something missing or any problems, leave a comment and we can either reopen this - or, probably better at this point to just create a new issue for whatever tests are having issues. Thanks and happy coding 🎉

**Comment by ShaunSHamilton** [comment]
@moT01 Just double-checking: Is [Secure Real Time Multiplayer](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/09-information-security/information-security-projects/secure-real-time-multiplayer-game.md) ticked off, because it is something that will require too much overhaul to write tests for?

**Comment by moT01** [comment]
I did check it off - the issue here was to create any kind of test for the projects where we can, that project has the one checking if the demo URL is used - so it could still use some work. I didn't look hard, but I do think that project would need some sort of overhaul to have more comprehensive tests on learn - so I thought we would be fine to close this. We could create another issue for that specific project? I'm guessing some of the other projects still have some tests that are missing, as well - but overall, the coverage should be pretty good. I was thinking to just create new issues when we come across problems. What do you think?

**Comment by ShaunSHamilton** [comment]
> What do you think?

- Unless this gets handled _in-house_, we should definitely create an issue for each project which could use some improving. That way, a simple _help wanted_ will go a long way.
- I agree, this issue has served its purpose. 👍 
So, I will open an issue for the SRTM project, and I expect other issues to be opened for the projects where some user story tests have not been written.
