### ISSUE TITLE
Use the word "portfolio" instead of profile everywhere on projects app

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#37183]
<img width="1074" alt="Profile___freeCodeCamp_org" src="https://user-images.githubusercontent.com/985197/66584589-088c5580-eb4b-11e9-8b61-fcb005d76411.png">

**Comment by Pradyumn-S** [comment]
can I take this issue?

**Comment by ahmadabdolsaheb** [comment]
Thank you @Pradyumn-S and @rodoviario for your interest.

This issue might need a little more investigation investigation before arriving at the final solution.
I encourage you to find similar issues to tackle in the meantime.

@raisedadead, should I only audit the copy to replace profile with portfolio or you would rather changing the profile instances in the client and the api-server entirely?

**Comment by kaleeaswari** [comment]
I would like to get it assigned..

**Comment by raisedadead** [comment]
@ahmadabdolsaheb this should come as a cosmetic change to the copy only, do not change any endpoints or code etc.
