### ISSUE TITLE
Codecamp not accepting my answers

### ISSUE THREAD

**Issue by JContreras210** [freeCodeCamp/freeCodeCamp#37196]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by JContreras210** [comment]
My code camp is not accepting my answers

**Comment by JContreras210** [comment]
https://learn.freecodecamp.org/responsive-web-design/basic-css/change-the-color-of-text/
My code camp is not accepting my answers

**Comment by RandellDawson** [comment]
@JContreras210 Please use [our forum](https://www.freecodecamp.org/forum) when you experience problems with your code not passing tests of a challenge.  If members of the forum believe there is an actual problem with the curriculum and not your code, then feel free to request this issue be reopened.  Always start in the forum when you have trouble with a challenge.  You can also just click on the "Ask for Help" button located on each challenge to facilitate asking for help.

Thank you.

**Comment by JContreras210** [comment]
Thank you
i was able to figure it out. I was not on the correct web browser.
