### ISSUE TITLE
The Nodeschool field guide page looks like a challenge page

### ISSUE THREAD

**Issue by AdventureBear** [FreeCodeCamp/freecodecamp#372]
And could be confusing for new campers, and seems redundant.  perhaps it can be removed altogether or consolidated? 

http://www.freecodecamp.com/field-guide/nodeschool-challenges

In addition, not all 5 of those nodeschool courses are in the challenge map (that I could find right now)

**Comment by QuincyLarson** [comment]
I've removed this field guide page
