### ISSUE TITLE
code element for cryptocurrency wallet id does not wrap

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#37209]
to reproduce:

1. go to localhost:8000/donate locally
2. click on show other ways to donate.
3. decrease the screen size below 400px

![image](https://user-images.githubusercontent.com/4591597/66653975-db6e9e80-ec41-11e9-81f5-89be0bafd400.png)

**Comment by nik72619c** [comment]
I'd like to work on this :)

**Comment by vkWeb** [comment]
@nik72619c Thanks for your interest in this but it will be fixed with https://github.com/freeCodeCamp/freeCodeCamp/pull/37189. I pushing changes to it.

@nik72619c You can keep looking for "help wanted" open issues to help us: https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22.

**Comment by nik72619c** [comment]
Okay, thanks a lot !

**Comment by ahmadabdolsaheb** [comment]
Thanks @vkWeb, did you have a chance to test it on that specific case?

**Comment by vkWeb** [comment]
@ahmadabdolsaheb Yes, I've tested. PR #37189 will fix this issue.

**Comment by joice33** [comment]
It looks like a good plan with solid guidelines. Thanks!

**Comment by oussama-pc** [comment]
Hello world hope you can help me out there thanks so much I love to see you sweetie hope you’re having fun I hope

**Comment by oussama-pc** [comment]
[SJT023E.docx](https://github.com/freeCodeCamp/freeCodeCamp/files/3721844/SJT023E.docx)

![2019-08-16_08-38-37_604](https://user-images.githubusercontent.com/34808738/66717110-6b782980-eda3-11e9-9425-aef94e1b4b8e.JPG)

**Comment by vkWeb** [comment]
Resolved with #37189.

**Comment by Taotaojin** [comment]
thanks
