### ISSUE TITLE
docs: Translate reply-templates.md to portuguese

### ISSUE THREAD

**Issue by MGenteluci** [freeCodeCamp/freeCodeCamp#37214]
**Is your feature request related to a problem? Please describe.**
The guide https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/reply-templates.md does not exist in https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/i18n-languages/portuguese

**Describe the solution you'd like**
Add this guide's translation to portuguese

**Comment by RandellDawson** [comment]
@MGenteluci It has already been decided that we only want to use the English version of the reply-templates, so we will not need these templates translated.
