### ISSUE TITLE
[Feature Request] Starting translation into Ukrainian

### ISSUE THREAD

**Issue by LastGenius-edu** [freeCodeCamp/freeCodeCamp#37228]
Create a "ukrainian" subfolder in /docs/i18n-languages.

Update the following in Ukrainian from their English version available in /docs directory:
 /ukrainian/CONTRIBUTING.md from its english version at /CONTRIBUTING.md

 /ukrainian/README.md from its english version at /docs/README.md

 /ukrainian/how-to-catch-outgoing-emails-locally.md from its english version at /docs/how-to-catch-outgoing-emails-locally.md

 /ukrainian/how-to-setup-freecodecamp-locally.md from its english version at /docs/how-to-setup-freecodecamp-locally.md

 /ukrainian/how-to-work-on-coding-challenges.md from its english version at /docs/how-to-work-on-coding-challenges.md

 /ukrainian/how-to-work-on-guide-articles.md from its english version at /docs/how-to-work-on-guide-articles.md

Once you are ready please make a pull request, preferably one for each file.

**Comment by Vozak16** [comment]
YEEEEHHAAAA

**Comment by ReyBroncas** [comment]
Yeah boy!! Nice job

**Comment by Pavlik1400** [comment]
Cool. I will work on it

**Comment by dyushez** [comment]
цьом!

**Comment by Vozak16** [comment]
OOOOHHHH, it is something I was expecting for so looooonnggggggg!!!

**Comment by JanusDG** [comment]
I start to work on this right now!

**Comment by JanusDG** [comment]
I start to work on this right now, guys))

**Comment by moT01** [comment]
How is this coming along? PR's for translating docs are welcome without an issue. If you want to keep this open to track your progress that's fine. But if you aren't using it any more, it can probably be closed. Thanks.

**Comment by LastGenius-edu** [comment]
There's not going to be any further progress on it.

Closing the PR.
