### ISSUE TITLE
Responsive Web Design Principles: Use a Retina Image for Higher Resolution Displays bug

### ISSUE THREAD

**Issue by arianneghislainerull** [freeCodeCamp/freeCodeCamp#37243]
**Describe your problem and how to reproduce it:**
The correct answer to the code does not work.

**Add a Link to the page with the problem:**
https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/use-a-retina-image-for-higher-resolution-displays

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@arianneghislainerull Please visit [our forum](https://www.freecodecamp.org/forum/) for help with coding challenges.  If the users on the forum find a bug in our tests, then feel free to request this issue to be reopened.  Then you can explain in detail what code you tried and post a link to the forum discussion.

Thank you.

**Comment by arianneghislainerull** [comment]
Greetings!

I had used another web browser, however the result is still the same. I
will reopen the issue since I have been stuck in this challenge for a month
or more. Thanks for your help.

Regards,
Arianne

**Comment by RandellDawson** [comment]
@arianneghislainerull Like I stated before, please post your question over on the forum.  Users will look at your code and guide you to a solution.
