### ISSUE TITLE
Bonfire - Truncate string: Cases where str.length < 3 not accounted for

### ISSUE THREAD

**Issue by alexhudici** [FreeCodeCamp/FreeCodeCamp#3724]
Challenge http://www.freecodecamp.com/challenges/bonfire-truncate-a-string:

For example:
`truncate("A-", 1);`
Could return '...' or 'A...', depending on the solution. This case is not covered in the description and not tested for.

Can see a version that works [here](http://freecodecamp.com/challenges/bonfire-truncate-a-string#?solution=function%20truncate%28str%2C%20num%29%20{%0A%20%20%20%20%2F%2F%20Clear%20out%20that%20junk%20in%20your%20trunk%0A%20%20%20%20if%20%28str.length%20%3C%3D%20num%29%20{%0A%20%20%20%20%20return%20str%3B%0A%20%20%20%20}%0A%20%20%20%20%2F%2Fif%20%28num%20%3E%3D%203%29%20{%0A%20%20%20%20%20%20num%20%3D%20num%20-%203%3B%0A%20%20%20%20%20%20str%20%3D%20str.slice%280%2C%20num%29%3B%0A%20%20%20%20%20%20str%20%3D%20str.concat%28%27...%27%29%3B%0A%20%20%20%20%20%20return%20str%3B%0A%20%20%20%20%2F%2F}%0A%20%20%20%20%0A%20%20}%0A%0Atruncate%28%22A-%22%2C%201%29%3B%0A)

**Comment by awesomeaniruddh** [comment]
By the current logic, it must return '...'. Can the @FreeCodeCamp/owners verify whether they want to keep the logic or make it different for strings that have a character length that is <= 3?

I'll create a PRf for an additional test based on that.

**Comment by BerkeleyTrue** [comment]
Wording states longer than, so lets go with that. `truncate("A-", 1); should return 'A...';`

**Comment by alexhudici** [comment]
Sounds good. The solution I provided for reference returns "..." and it still passes the tests.

**Comment by BerkeleyTrue** [comment]
@alexhudici Thanks for pointing this out. The quality of our challenges increase through campers such as yourself taking the time to analyze these things and I think that is fantastic!
