### ISSUE TITLE
optimize the universal navigation

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#37242]
the nav should have three items: news, forum, projects

Navigation to portfolio/settings would be through a button on the projects map.

**Comment by moT01** [comment]
Why not keep the portfolio link there? So if a user wants to sign out of freecodecamp, they would have to click projects -> portfolio -> settings -> sign out, same for any of the settings.

This just feels very buried and unintuitive. The settings feel a little too hidden the way it is in my opinion.

**Comment by RandellDawson** [comment]
I agree with @moT01 here.  Clicking on a link named Projects does not make me think I will have the option to change the settings up my account.

**Comment by moT01** [comment]
Almost every website you go to has your icon when you're signed in - usually in the top right. I vote that we go back to using the icon, and it takes you to your settings. So the links would be `[news, forum, projects, icon]` - I dunno, that just makes the most sense to me.

**Comment by ojeytonwilliams** [comment]
I feel the same way.  It's such an ingrained convention that settings should be accessible from everywhere that I'm pretty sure people will find it frustrating to have to search for it.

It doesn't have to be an icon - I know we're trying to avoid using them.  Something similar to how Amazon does it could work, though.

From
![AccountsNoHover](https://user-images.githubusercontent.com/15801806/66757841-4ec01c80-ee9d-11e9-808c-aa29e2172696.png)
to
![AccountWithHover](https://user-images.githubusercontent.com/15801806/66757857-57185780-ee9d-11e9-8977-59e619dac1e0.png)

**Comment by ahmadabdolsaheb** [comment]
Vey valid points. we will ship the current nav and optimize for the next iterations then.

Since we are not sharing the same accounts or auth across our services yet and we are planning to share the same universal nav everywhere, placing a sign-in or settings button might not be relevant if you are not on learn.

our solutions would be a secondary nav "local nav" for each service, or nesting those buttons in each service and display them contextually. 

*For the forum we will definitely have a secondary nav.

**Comment by ahmadabdolsaheb** [comment]
update: we got news and forum nav items and kept portfolio with this #37339
