### ISSUE TITLE
Code Passes all the test Cases and won't 

### ISSUE THREAD

**Issue by sreimer15** [FreeCodeCamp/FreeCodeCamp#3725]
Challenge [Bonfire: Roman Numeral Converter](http://www.freecodecamp.com/challenges/bonfire-roman-numeral-converter#?solution=var%20result%20%3D%20%22%22%3B%0A%0Afunction%20convert(num)%20%7B%0A%0A%20%20if%20(num%20%3C%3D%200)%20%7B%0A%20%20%20%20return%20result%3B%0A%20%20%7D%0A%20%20else%20if%20(num%20%3E%3D%201%20%26%26%20num%20%3C%3D%203)%20%7B%0A%20%20result%20%3D%20result%20%2B%20%22I%22.repeat(num)%3B%0A%20%20num%20%3D%20num%20-%203%3B%0A%20%20return%20convert(num)%3B%0A%0A%7D%0A%20%20else%20if%20(num%20%3D%3D%3D%204%20)%20%7B%0A%20%20result%20%3D%20result%20%2B%20%22IV%22%3B%0A%20%20num%20%3D%20num%20-%204%3B%0A%20%20return%20convert(num)%3B%0A%0A%7D%0A%20%20else%20if%20(num%20%3E%3D%205%20%26%26%20num%20%3C%3D%208%20)%20%7B%0A%20%20%20%20result%20%3D%20result%20%2B%20%22V%22%20%2B%22I%22.repeat(num-5)%3B%0A%20%20%20%20%20%20num%20%3D%20num%20-%208%3B%0A%20%20%20%20%20%20return%20convert(num)%3B%0A%20%20%7D%0A%20%20else%20if%20(num%20%3D%3D%3D%209)%20%7B%20%0A%20%20%20%20result%20%3D%20result%20%2B%20%22IX%22%3B%0A%20%20%20%20%20%20num%20%3D%20num%20-%209%3B%0A%20%20%20%20%20%20return%20convert(num)%3B%0A%20%20%7D%0A%20%20else%20if%20(num%20%3E%3D%2010)%20%7B%0A%20%20%20%20result%20%3D%20result%20%2B%20%22X%22%3B%0A%20%20%20%20num%20%3D%20num%20-%2010%3B%0A%20%20%20%20return%20convert(num)%3B%0A%20%20%20%20%0A%20%20%7D%0A%0A%7D%3B%0A%0Aconvert(29)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
var result = "";

function convert(num) {

  if (num <= 0) {
    return result;
  }
  else if (num >= 1 && num <= 3) {
  result = result + "I".repeat(num);
  num = num - 3;
  return convert(num);

}
  else if (num === 4 ) {
  result = result + "IV";
  num = num - 4;
  return convert(num);

}
  else if (num >= 5 && num <= 8 ) {
    result = result + "V" +"I".repeat(num-5);
      num = num - 8;
      return convert(num);
  }
  else if (num === 9) { 
    result = result + "IX";
      num = num - 9;
      return convert(num);
  }
  else if (num >= 10) {
    result = result + "X";
    num = num - 10;
    return convert(num);
    
  }

};

convert(29);


```

Hi, I hope this isn't a mistake with typing. I think my code should pass the tests, but it won't let me continue. Thank you.

**Comment by RobRoseKnows** [comment]
Remove 'convert(29);' from your code. It should work then.

**Comment by ltegman** [comment]
The reason the call to `convert(29)` at the end of your code is causing a problem is that you're initializing the variable `result` globally. This means that `result = ""` only happens once and every call to convert after the first time will be using a non-empty `result` string. This is one of many reasons why global variables are bad news. I would highly recommend having `result` as an optional parameter that you pass into `convert`, that way you can initialize it to an empty string on the first call to `convert` and pass it into any subsequent calls to `convert`.

**Comment by sreimer15** [comment]
Oh that makes complete sense!
That is actually really interesting.
Thank you for the help!
