### ISSUE TITLE
Add support for dark/night mode

### ISSUE THREAD

**Issue by SiddharthVarshney** [freeCodeCamp/freeCodeCamp#37274]
It will be great if there will be support for dark mode. It will reduce eye stress and stay focused for a long period of time.

**Comment by ahmadabdolsaheb** [comment]
Dark mode has been added to the staging website that will be deployed soon.
In freecodecamp.dev please sign-in and navigate to portfolio, then click on the settings button. there is a toggle for dark mode.
I will close this issue since this feature has already been implemented.
