### ISSUE TITLE
User state and the Payload for the API are not in sync for most update calls

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37279]
**Describe the bug**
If you complete a challenge and go to your Portfolio without reloading, that challenge will appear with an 'Invalid Date'

**To Reproduce**

1. Go to www.freecodecamp.dev/learn
2. Click on any challenge you have not completed
3. Submit a correct solution to that challenge
4. Click on Portfolio
5. Scroll down to Timeline
6. See the 'Invalid Date'
7. Reload the page
8. See the correct date

**Expected behavior**
You should not have to reload to see the correct date.

**Screenshots**
![TimelineUpdate](https://user-images.githubusercontent.com/15801806/66751315-0b5eb180-ee8f-11e9-86a9-b8c5d2ecf28c.gif)

**Comment by kaleeaswari** [comment]
I can look into the issue. Do assign.

**Comment by ojeytonwilliams** [comment]
@kaleeaswari we do not typically assign issues, but please do submit a PR if you can fix this. 

The rationale is covered in the [contributing guide].(https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md)

**Comment by raisedadead** [comment]
Hi @ojeytonwilliams I am closing this having landed two of the linked PRs. Both are available for test on .dev and will be reaching production within the hour.

Please re-open if this re-surfaces.
