### ISSUE TITLE
Test output style should mirror the test suite

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37307]
**Describe the bug**
The code blocks in the test output (below the editor) do not match the test suite (below the instructions)

**To Reproduce**
1. Go to [a challenge](www.freecodecamp.dev/learn/responsive-web-design/basic-css/use-css-selectors-to-style-elements)
2. Click on run the test
3. Scroll down to the output
4. See:

![OutputDefault](https://user-images.githubusercontent.com/15801806/66839951-88f5f080-ef67-11e9-92e0-a746a6c17436.png)
in the default theme
and 
![OutputNight](https://user-images.githubusercontent.com/15801806/66839974-96ab7600-ef67-11e9-97c4-c4e37c7ba56a.png)
in night mode.

**Expected behavior**
The code blocks in the output should be the same as the suite.

**Comment by vkWeb** [comment]
@ojeytonwilliams I can't reproduce. 

![Screenshot (32)](https://user-images.githubusercontent.com/26724128/66857487-fecc7d00-efa4-11e9-94ff-6a9a8eed6f5a.png)

**Comment by ojeytonwilliams** [comment]
The problem is the red text, below `// running tests`.  

`h2`, `style` and so on.

**Comment by rickysyamsi** [comment]
Hi @vkWeb. I had made PR for this issue. The code style in test output panel (red color) should mirror the code style in test suite (black color with gray background).

Did I understand it correctly @ojeytonwilliams?

**Comment by vkWeb** [comment]
@ojeytonwilliams Oh. I thought you were talking about the wordings of test output. 

Hey @rickysyamsi. Before I go into the topic, I want to thank you for the contributions you are making for us. :) But why it should mirror the style of the test suite?

**Comment by vkWeb** [comment]
@ojeytonwilliams It looks good. It looks like a terminal's syntax highlight style. Please don't change it :)

**Comment by ojeytonwilliams** [comment]
@vkWeb  It looks jarring to me, having one colour that's so different.  I don't want to impose my taste unilaterally though, so I'll leave this issue up for a bit.  Give more people time to chime in if they have strong feelings on the matter.

**Comment by vkWeb** [comment]
@ojeytonwilliams I think we are already on the edge of deployment and this isn't a bug or something which needs to be "discussed" at this stage. If someone really has a problem with it (or with its accessibility) then they are free to create issues and we will triage it. 

I am not saying we should not discuss style changes but this change doesn't feel quite right to me. What do you think?

**Comment by rickysyamsi** [comment]
You're welcome @vkWeb, I'm glad to help :)

I think that @ojeytonwilliams intention is to make the styling looks consistent. Personally red text is hard to read for me. But I wear glasses so my eyes are probably not normal people standard.

Now that you say about terminal, I just realized that was styled to looks like terminal. Also red color usually means error semantically.

Objectively, I think the most important thing is to test the color combination for accessibility. As long as it passes WCAG contrast checker. The rest should be about consistency and style preference.

**Comment by vkWeb** [comment]
@rickysyamsi Yes, you are right. It's all a matter of preference if the style qualifies WCAG. For me, its the current version with `font-size: 90%` and the test suite `code` should not overlap.

Maybe we can make changes to it in the linked PR if @ojeytonwilliams agree?

**Comment by rickysyamsi** [comment]
> I think we are already on the edge of deployment and this isn't a bug or something which needs to be "discussed" at this stage. If someone really has a problem with it (or with its accessibility) then they are free to create issues and we will triage it.
I am not saying we should not discuss style changes but this change doesn't feel quite right to me. What do you think?

@vkWeb Like what you said in your previous comment, I think it is better if we leave this issue as is. Feel free to create another issue for discussing style improvement. I will be happy to participate in the discussion :)
