### ISSUE TITLE
FCC won't stay logged in.

### ISSUE THREAD

**Issue by tknbnola** [freeCodeCamp/freeCodeCamp#37312]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
When I log in, then click the "coding curriculum" button, its as if I never logged in.
Home page does not show my profile icon either.
It shows FCC with my gray background settings until I click any other button

**To Reproduce**
1. Go to 'freecodecamp.org'
2. Click on 'go to coding curriculum' or anything else clickable on the page.

**Expected behavior**
I expect to be brought to my bookmarked location within my curriculum.

**Screenshots**
<img width="1279" alt="Screen Shot 2019-10-15 at 10 33 59 AM" src="https://user-images.githubusercontent.com/29470003/66846592-a4e19e00-ef37-11e9-8c17-df819eba2583.png">
<img width="1278" alt="Screen Shot 2019-10-15 at 10 34 10 AM" src="https://user-images.githubusercontent.com/29470003/66846593-a4e19e00-ef37-11e9-9734-ac290c15ad60.png">
<img width="1279" alt="Screen Shot 2019-10-15 at 10 34 23 AM" src="https://user-images.githubusercontent.com/29470003/66846595-a4e19e00-ef37-11e9-841c-39bc1252a514.png">
<img width="1280" alt="Screen Shot 2019-10-15 at 10 34 35 AM" src="https://user-images.githubusercontent.com/29470003/66846596-a4e19e00-ef37-11e9-878c-825d01c84630.png">

**Desktop (please complete the following information):**
    Macbook Pro
 - OS: mojave 10.14
 - Version: Google Chrome is up to date
Version 78.0.3904.50 (Official Build) beta (64-bit)

**Additional context**

**Comment by nephring** [comment]
same here, it's looks like issue described here: 
https://www.freecodecamp.org/forum/t/i-can-log-into-freecodecamp-org-but-it-logs-me-out-at-learn-freecodecamp-org/194036/60

**Comment by RandellDawson** [comment]
Closing this issue as the issue has already been reported and a fix is being implemented in the next few hours.

https://www.freecodecamp.org/forum/t/when-i-click-curriculum-it-wants-me-to-sign-in/321933
