### ISSUE TITLE
Infinite loops are somehow possible again in challenges

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3732]
Thanks to @d3ddd for reporting this and including the link. 

Warning - this will cause an infinite loop and crash your browser, but if you still take a look at the code and confirm it is indeed an infinite loop. 

We used to have safeguards against infinite loops, but it seems those are no longer working (we've gotten several complaints in the past few days about this all the sudden).

http://freecodecamp.com/challenges/bonfire-spinal-tap-case#?solution=function%20spinalCase(str)%20%7B%0A%20%20%2F%2F%20%22It's%20such%20a%20fine%20line%20between%20stupid%2C%20and%20clever.%22%0A%20%20%2F%2F%20--David%20St.%20Hubbins%0A%20%20%0A%20%20if(str.indexOf('%20')%20%3D%3D%3D%20-1%20%26%26%20str.indexOf('_')%20%3D%3D%3D%20-1)%20%7B%0A%20%20%20%20%0A%20%20%20%20str%20%3D%20str.split('')%3B%0A%20%20%20%20%0A%20%20%20%20for(var%20i%3D0%3B%20i%3Cstr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20if(str%5Bi%5D%20%3D%3D%3D%20str%5Bi%5D.toUpperCase())%20%7B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20str.splice(i%2C%200%2C%20'%20')%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%7D%0A%20%20%0A%20%20%0A%20%20%0A%20%20%20return%20str.replace(%2F%20%2Fg%2C%20'-').replace(%2F_%2Fg%2C%20'-').toLowerCase()%3B%0A%7D%0A%0AspinalCase('This%20Is%20Spinal%20Tap')%3B%0A%0A%2F%2FNOTES%3A%0A%2F%2F%20%20%20%20%20%20If%20no%20spaces%20-%20or%20_%20then%20Turn%20str%20into%20array.%20Look%20for%20capital%20letters%20and%20insert%20space%20before%20the%20capital%0A%2F%2F%20%20%20%20%20%20then%20you%20can%20join%20array%20back%20into%20screen%20and%20perfom%20classci%20regex%20like%20alrady%20done%20son.%0A

**Comment by jbmartinez** [comment]
Here is the full code:
```javascript
function spinalCase(str) {
  // "It's such a fine line between stupid, and clever."
  // --David St. Hubbins
  
  if(str.indexOf(' ') === -1 && str.indexOf('_') === -1) {
    
    str = str.split('');
    
    for(var i=0; i<str.length; i++) {
      
      if(str[i] === str[i].toUpperCase()) {
        
        str.splice(i, 0, ' ');
        
      }
      
    }
    
  }
  
  
  
   return str.replace(/ /g, '-').replace(/_/g, '-').toLowerCase();
}

spinalCase('This Is Spinal Tap');
```

The code generates an infinite loop for the second test case (which is the first test with uppercase letters), here is the offending portion:

```javascript
for(var i=0; i<str.length; i++) {
  if(str[i] === str[i].toUpperCase()) {
    str.splice(i, 0, ' ');
  }
}
```

the `splice()` method is executed when an uppercase letter is found in the `str` array, inserting a white space *before* that letter. So, the array is extended indefinitely from that point.

**Comment by BerkeleyTrue** [comment]
If the infinite loop happens only for certain test cases then our previous prevention systems will not catch it.

**Comment by jlslew** [comment]
Here are my findings after messing with the site for a few hours:
* The following code, from [client/commonFramework.js#L345-L350](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/commonFramework.js#L345-L350), will not be displayed because for this challenge, `challengeType = "5"`
```
if (common.challengeType === 0) {
  codeOutput.setValue(
    'Sorry, your code is either too slow, has a fatal error, ' +
    'or contains an infinite loop.'
  );
}
```

* The prevention systems; [asvd/jailed](https://github.com/asvd/jailed/tree/v0.2.0) mentioned by @BerkeleyTrue will catch infinite loop in the editor only but not the test.  The tests are `eval`uated directly; [commonFramework.js#L855](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/commonFramework.js#L855).

**Comment by bugron** [comment]
We are catching most of infinite loops now, closing.

**Comment by d3ddd** [comment]
I'm still experiencing the same freezing problem from this code on the
"Drop It" Bonfire. If there was even just a simple way for me to reset my
code that would be good enough for me. But currently the page freezes
before I can manage to hit the "Reset" button.

[image: Inline image 1]

**Comment by ltegman** [comment]
@d3ddd You can either [Disable Code Auto-Run](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Disable-Code-Auto-Run) or [Delete the Solution from Local Storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage)
