### ISSUE TITLE
Change in User Interface

### ISSUE THREAD

**Issue by arianneghislainerull** [freeCodeCamp/freeCodeCamp#37332]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
The user interface seems to be different, basically the front end of the website. I also can't sign in to my account. :( When I tried to inspect the website, it shows this:
////
Failed to load resource: the server responded with a status of 500 ()
api.rollbar.com/api/1/item/:1 Failed to load resource: the server responded with a status of 429 ()
///

Hope this helps. The website had an alert that they already notified the organization itself.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by raisedadead** [comment]
Thanks for reporting, please checkout our [community forum](https://www.freecodecamp.org/forum) for details

**Comment by arianneghislainerull** [comment]
The last time I checked, there is still a bug on the website.

It says this -->
"Something is not quite right. A report has been generated and the freeCodeCamp.org team have been notified."

Thanks for letting me know. I'll search up some threads to see if other people are also experiencing the bug.

**Comment by raisedadead** [comment]
We are working very hard to fix the issues. Thanks for your patience

**Comment by arianneghislainerull** [comment]
Thank you so much for sharing this information!
