### ISSUE TITLE
Email unsubscribe path isn't working

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#37331]
My weekly emails have an unsubscribe URL that follows this pattern: 

```
https://www.freecodecamp.org/ue/[unsubscribeId]
```

This path no longer works.

We will need to fix this before my Thursday email blast.

**Comment by raisedadead** [comment]
This is a stability issue. All endpoints are working.

**Comment by raisedadead** [comment]
However, I recommend waiting on a confirmation before sending out the blast

**Comment by laghee** [comment]
The unsubscribe path works, but the resubscribe doesn't -- at least it didn't for me. All I wanted to do was change the email address where I receive, but when I try to resubscribe following the link shown in the screenshot above, I get this:

![Screenshot 2019-11-01 19 40 52](https://user-images.githubusercontent.com/20972610/68048585-26c81a00-fce1-11e9-956a-692c9c8818f3.png)
