### ISSUE TITLE
Landing page shows interview prep as a cert

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#37340]
On the home page, it lists the `coding interview prep` section as a certification....

![Screen Shot 2019-10-16 at 9 06 48 AM](https://user-images.githubusercontent.com/20648924/66926954-8ee5e300-eff4-11e9-95f9-1349e0f1e3ba.png)

Maybe remove that since there's no cert for it?

**Comment by raisedadead** [comment]
Yes, you are correct. I will defer to @QuincyLarson for the correct categorization for this.

**Comment by QuincyLarson** [comment]
We could change the font size of this. Then it would be visually distinct from the other items in this list.

**Comment by iit2018110** [comment]
We can indent the list belonging to same category. And make change in font style
Like this way:-
**Certifications:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#"> _Responsive Web Design_</a>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">_JavaScript Algorithms and Data Structures_</a>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">_Front End Libraries_</a>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">_Data Visualization_</a>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">_APIs and Microservices</a>_
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="#">_Information Security and Quality Assurance_</a>
<a href="#">**_Coding Interview Prep_**</a>

**Comment by moT01** [comment]
I'm not sure I like either of these solutions - it seems like it might just make a user ask themselves something like: "what's with that last one?" - And not be quite clear enough that it is not a cert. What about something a little more specific...


**Certifications:**
&nbsp;&nbsp;<a href="#"> _Responsive Web Design_</a>
&nbsp;&nbsp;<a href="#">_JavaScript Algorithms and Data Structures_</a>
&nbsp;&nbsp;<a href="#">_Front End Libraries_</a>
&nbsp;&nbsp;<a href="#">_Data Visualization_</a>
&nbsp;&nbsp;<a href="#">_APIs and Microservices</a>_
&nbsp;&nbsp;<a href="#">_Information Security and Quality Assurance_</a>


**Additional Challenges:**
&nbsp;&nbsp;<a href="#">_Coding Interview Prep_</a>
