### ISSUE TITLE
Quotes refreshing on click

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37341]
**Describe the bug**
When you left click while on the `/learn` page the random quote gets replaced with a new one.

**To Reproduce**
1. Go to https://www.freecodecamp.dev/learn/
2. Click on anything that doesn't take you to a new page
3. See the random quote get replaced

**Expected behavior**
A random quote should appear each time you visit learn, but it should not change unless you reload.

**Screenshots**
![Quotes](https://user-images.githubusercontent.com/15801806/66931492-74ccf480-f036-11e9-8d8b-d99ecb1642fa.gif)

**Additional Context**
This only appears once the site has been built, `npm run develop` doesn't show the error.  It is not happening in production, so presumably was introduced since https://github.com/freeCodeCamp/freeCodeCamp/commit/a2762fe4c3401bd9104051b59860ee57c8ee5b5e

**Comment by moT01** [comment]
I see this on the production site as well.
