### ISSUE TITLE
portfolio page footer needs to be sticky

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#37346]
to reproduce go login and click on portfolio

the footer comes up until  the portfolio loads
![sticky footer](https://user-images.githubusercontent.com/4591597/66949430-30a21a00-f05f-11e9-9859-0355c01800d3.gif)

**Comment by GQuirino** [comment]
can i work on this issue?

**Comment by ahmadabdolsaheb** [comment]
sure, please go ahead.
and make sure to gatsby build it locally to see the effect better.

**Comment by JuWeber99** [comment]
any update on this? is @GQuirino working on it?

**Comment by Ajwerth** [comment]
I could look into this if @GQuirino isn't anymore. I'm actually trying to run **gatsby develop** and it errors out with **Error: Cannot find module '../config/env.json**

**Comment by ahmadabdolsaheb** [comment]
Thank you everyone for your interest.

There have been some changes with the navigation, so this issue might be nonexistent.
I will go ahead and close this issue for now.

Feel free to re open this issue if you think it was closed by mistake.

Thank you
