### ISSUE TITLE
[Bonfire: Symmetric Difference] Incorrect expected results for the 2nd & 3rd test cases.

### ISSUE THREAD

**Issue by tohjustin** [FreeCodeCamp/FreeCodeCamp#3735]
**[Test Case 2 & 3]: Should expect [1,4] instead of [1,4,5] since '5' is present in the all three input arrays for each test case.**

###### *Case was reported a week ago but isn't fixed when closed by original reporter*
---------------------------------------------------------------------------------------------------------------------------------

Challenge [Bonfire: Symmetric Difference](http://www.freecodecamp.com/challenges/bonfire-symmetric-difference) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.85 Chrome/45.0.2454.85 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

![image](https://cloud.githubusercontent.com/assets/8844886/10473667/d5dddf54-71e2-11e5-9a00-b339a8d5df21.png)

**Comment by BerkeleyTrue** [comment]
@tohjustin Can you link the original issue?

**Comment by ltegman** [comment]
@tohjustin `[1,4,5]` is the correct output for those test cases. [This youtube video](https://www.youtube.com/watch?v=PxffSUQRkG4) has a pretty good explanation of symmetric differences that should help explain why. Long story short though is that if the item is present in an odd number of the collections it should be in the result and if it's in an even number of the collections it should be left out of the result.

**Comment by BerkeleyTrue** [comment]
@ltegman Thanks! I seem to remember this issue popping up before but I could not remember the reason.

Happy Coding!
