### ISSUE TITLE
Own expect statements cannot be split in multiple lines

### ISSUE THREAD

**Issue by michaelkebe** [FreeCodeCamp/FreeCodeCamp#3736]
You can add you own expectations with chaijs in bonfire.

This works and the test is added to the tests on the left side.
```
expect(true).to.be.true;
```

Although correct syntax. This does not work. The test is not added.
```
expect(true).
  to.be.true;
```

This is especially bad, when you have more complex input data:
```
expect(every(
  [{"user": "Tinky-Winky", "sex": "male"},
   {"user": "Dipsy", "sex": "male"},
   {"user": "Laa-Laa", "sex": "female"},
   {"user": "Po", "sex": "female"}],
  "sex")).to.be.true;
```

**Comment by BerkeleyTrue** [comment]
That is annoying. The offending code is https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/client/commonFramework.js#L360

The regex looks for test but does not account for new lines.

A work around is to do something like this.
```js
var args = [
  [{"user": "Tinky-Winky", "sex": "male"},
   {"user": "Dipsy", "sex": "male"},
   {"user": "Laa-Laa", "sex": "female"},
   {"user": "Po", "sex": "female"}],
  "sex")
];

expect(every.apply(every, args).to.be.true;
```

This one is up for grabs!

I'll just leave this here: http://regex.inginf.units.it/

**Comment by BerkeleyTrue** [comment]
An easy way to do it is to look for semicolon but we would need add semicolons to jshint so the user would get an error if not present.

**Comment by BerkeleyTrue** [comment]
closing.

* stale
* removing support for BDD. Will move to assert only style
* removing support for BDD simplifies future flow of challenge framework


Happy Coding!
