### ISSUE TITLE
Show a skeleton loaders on the the `/learn` page

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#37369]
Show a skeleton loader on the sign in button instead of the full page loader on the learn application:

![image](https://user-images.githubusercontent.com/1884376/67012678-6f8fa880-f10f-11e9-86d3-8a9307115446.png)

This should let users see the page faster than waiting for the sync.

The other things that can be a skeleton are the welcome message

**Comment by shakti97** [comment]
Would like to work on it

**Comment by thecodingaviator** [comment]
@shakti97 Please read our [contributing guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md) before working on it and feel free to take it up

**Comment by ojeytonwilliams** [comment]
@raisedadead how about we get rid of all the full page loaders we can?  If they're there, then the HTML page Gatsby produces will just be a loader and so the user won't be able to see anything useful until the page hydrates.  I think `/donate/` could lose the loader as well - not sure about the rest.

The way I see this working is that the sign-in button would be a loader only while the user state is pending.  If they're signed out the button should be there, if they're signed in there should be nothing.  Sound reasonable?

**Comment by raisedadead** [comment]
Hold on to your thought. I really like the idea of what you are saying, we are making some changes (yet again) to the views of the pages.

**Comment by ahmadabdolsaheb** [comment]
@raisedadead, would you like a skeleton loader on learn to display custom copy and button to signed in / non signed in users?

**Comment by raisedadead** [comment]
Yes, the full page loader at the minute gives the impression that we are slow (well we are technically) but if the pages were rendered, people would continue working.
