### ISSUE TITLE
Update Scrimba video for the Word Blanks challenge

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#37367]
@beaucarnes The video for the [Word Blanks](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/word-blanks) challenge needs to be updated due to changes in the challenge.  We simplified the challenge to not introduce functions in this challenge.

**Comment by beaucarnes** [comment]
@RandellDawson Sure, I'll update the video.

**Comment by RandellDawson** [comment]
@beaucarnes Any status on this update?

**Comment by beaucarnes** [comment]
Done.
