### ISSUE TITLE
Border color change on focus state for input boxes in Account Settings with night mode

### ISSUE THREAD

**Issue by rickysyamsi** [freeCodeCamp/freeCodeCamp#37375]
**Describe the bug**
Functionally, there is no problem with distinguishing between normal and focus state because there is blinking cursor when on focus state. Filled fields will also be selected and highlighted with blue color when navigating with keyboard tab.

Aesthetically, there is suggestion from @ojeytonwilliams on issue #37309 to invert the input boxes with dark background and light text in night mode. Border color change between normal and focus state also need some visual improvements because currently it is hard to see.

**To Reproduce**
1. Go to http://localhost:8000/settings
2. Try to switch between normal and focus state on input boxes with mouse click or keyboard tab
3. Refer to **Describe the bug**

**Expected behavior**
Refer to suggestion in **Describe the bug**

**Desktop (please complete the following information):**
 - OS: Windows 10 1809 Build 17763.832
 - Browser Latest Chrome
 - Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by hannahapuan** [comment]
i'll take this one
