### ISSUE TITLE
Improve client validation for Email Settings & Your Internet Presence in Account Settings

### ISSUE THREAD

**Issue by rickysyamsi** [freeCodeCamp/freeCodeCamp#37373]
**Describe the bug**
For `New Email` field in `Email Settings`, error state can not be triggered. Warning state will be triggered when an email address with incorrect domain is entered (for example: `email@example.com.a`).

For all fields in `Your Internet Presence`, both error and success state can not be triggered.

**To Reproduce**
1. Go to http://localhost:8000/settings
2. Try to fill `Email Settings` and `Your Internet Presence`
3. Refer to **Describe the bug**

**Expected behavior**
For `New Email` field in `Email Settings`, error state should be triggered instead of warning state. There should only be two states for an email address. Success state is when it is a valid and reachable email address. Error state is when it is an invalid and unreachable email address.

For all fields in `Your Internet Presence`. Success state is when it is a valid and reachable URL. Error state is when it is an invalid and unreachable URL.

**Desktop (please complete the following information):**
 - OS: Windows 10 1809 Build 17763.832
 - Browser Latest Chrome
 - Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by rickysyamsi** [comment]
Calling @ojeytonwilliams to discuss this from issue #37309.

What do you think about this? Are there anything to add or change from the **Expected Behavior** I described?

**Comment by ojeytonwilliams** [comment]
@rickysyamsi the only thing I'm not sure about is 'unreachable'.  Do you just mean unreachable because the URL is malformed?  Like hppts:/whatever.com, for example.  If so, then I completely agree.

cc @ahmadabdolsaheb

**Comment by rickysyamsi** [comment]
@ojeytonwilliams Yes of course. 'Unreachable' is only defined by malformed email format (@, valid length, etc) and URL format (protocol, colon, double slash, etc).

It is also possible to check the top level domain part against current existing TLD programatically.

Other than that, for example checking real email address which is existing should be done by email confirmation / verification.
