### ISSUE TITLE
[Production] 404 on visiting user profiles

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#37379]
**Describe the bug**
On visiting user profiles, platform throws 404.

**To Reproduce**
1. Go to https://www.freecodecamp.org/vkweb or https://www.freecodecamp.org/QuincyLarson
2. 404

**Expected behavior**
The user profile (portfolio) should appear. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 32 bit.
 - Browser: Chrome.
 - Version: 77.0.3865.120 (Official Build) (32-bit)

**Comment by raisedadead** [comment]
It's a slow query, will be resolved with #37321
