### ISSUE TITLE
bug: footer shows twice on profile page

### ISSUE THREAD

**Issue by dboydgit** [freeCodeCamp/freeCodeCamp#37380]
**Describe the bug**
When on the profile page in development, the site footer shows twice at the bottom of the page.

**To Reproduce**
1. Visit profile page and view footer

**Expected behavior**
Footer should only appear **once.**

**Screenshots**
![Screenshot from 2019-10-17 12-14-33](https://user-images.githubusercontent.com/24216368/67035867-bd88ba00-f0d7-11e9-8e61-b493990365fe.png)

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - Chrome
 - Version 77.0.3865.120 (Official Build) (64-bit)

**Comment by ojeytonwilliams** [comment]
This is development only artifact, it'll never appear in production.  As I understand it the reason it happens is that Gatsby creates a custom 404 page (with it's own footer) into which it inserts the real 404 page (with the expected footer).  Unfortunately, that means that things like footers and headers appear twice.

It's annoying, but you can always build the site to check that the site is behaving itself.
