### ISSUE TITLE
title case a sentence

### ISSUE THREAD

**Issue by Kinderspiel86** [FreeCodeCamp/FreeCodeCamp#3738]

**Comment by Kinderspiel86** [comment]
Hey guys Im stucked in the "Bonfire: Title Case a Sentence Challenge"
The aim is to Return the provided string with the first letter of each word capitalized. 
I got code that works fine except in this case: 
titleCase("I'm a little tea pot"); --> doesnt ingnore the " ' " 
Here is the code: 

function titleCase(str) {

 str = str.toLowerCase().replace(/\b[a-z]/g, function(letter) {
    return letter.toUpperCase();
});
  return str; 
}

titleCase("I'm a little tea pot");

thank you very much!

**Comment by codehait** [comment]
Instead you can try to consider the sentence as an array,then the words as another array, capitalize the first letter and replace it with the original word

here is the code:

function titleCase(str) {
   var temp,el1,el2;
  var i=0;
  
  var arrlen=str.length;
  var sta="a";var ele,elem;
  var arr = str.split(' ');
  
  for(var k=0;k<arr.length;k++)
    {
  arr[k]=arr[k].toLowerCase();
    }

 for(var j=0;j<arr.length;j++)
 {
   ele=arr[j];
  el1=ele.charAt(0);
  el2=ele.charAt(0).toUpperCase()
   elem=ele.replace(el1,el2);
  arr[j]=elem;
 }
  
  str=arr.join(' ');
  return str;
}

titleCase("HERE IS MY HANDLE HERE IS MY SPOUT", "");

**Comment by awesomeaniruddh** [comment]
I'm gonna have to close the issue because your query is not really relevant.

You can ask for help here: gitter.im/FreeCodeCamp/Help

Happy coding!

**Comment by Kinderspiel86** [comment]
thank you very much for your help! :-)

**Comment by Ankurlvv** [comment]
Hey!! i got suck in the bonfire "title case a sentence", the code is correct  but it's keep on saying "chai is not defined" 

pls help!!

**Comment by codehait** [comment]
maybe chai is a variable you have defined but not initialized

**Comment by nethajireddy** [comment]
`function titleCase(str) 
{
return str.split(' ').map(function(a){return a.toLowerCase();}).map(function(a){return a.replace(a[0],a[0].toUpperCase());}).join(' ');
}`
