### ISSUE TITLE
Backend project submission fails quietly

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37381]
**Describe the bug**
When a backend project is submitted it does not send the solution or Github urls and is rejected, silently, by the server.

**To Reproduce**
1. Go to localhost:8000/learn/apis-and-microservices/apis-and-microservices-projects/exercise-tracker
2. Enter valid urls into Solution and Github Link
3. Click "I've completed this challenge"
4. Click "Submit..."
5. Arrive at the next challenge
6. Go to your public profile (with timeline public)
7. Reload
8. See that the project does not appear.

**Expected behavior**
Either the submission should succeed or the user should be informed that it has failed.

**Comment by ojeytonwilliams** [comment]
I was wrong about the 'silently' part.  On the .dev site you can see that there is, briefly, a message warning you that the server is not being updated
![SubmissionDev](https://user-images.githubusercontent.com/15801806/67149770-4e61c000-f2a7-11e9-87bc-0ab4792b05a4.gif), but that gets wiped out when the new page loads.

**Comment by raisedadead** [comment]
Can you re-confirm this. I just want to rule out our earlier outage, and that we need to update the template on boilerplate with the `api.freecodecamp.org` as a CORS allowed origin. I think a recent issue came up about this, @RandellDawson can you help in digging through the issues on what it was and if it is related.

**Comment by moT01** [comment]
Looks like it's still a problem. But it was not at one point. The last project on my portfolio was submitted September 29, 2018 - so it was working at that point.

On further digging - nothing is showing up in the timeline. I tried a few of each type of challenge. They can be submitted and counted as completed, but do not show up on the timeline. 

The backend projects are the only ones that seem to be giving that little error. The others don't give the error.

<img width="439" alt="Screen Shot 2019-10-20 at 10 12 03 AM" src="https://user-images.githubusercontent.com/20648924/67161647-18aded00-f322-11e9-84e8-2bf48269495b.png">

**Comment by ahmadabdolsaheb** [comment]
I can reproduce this on the current master and on production.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, I can take a look at the example projects and boilerplates to make sure `api.freecodecamp.org` is allowed as an origin.

**Comment by raisedadead** [comment]
Yup, @scissorsneedfoodtoo please test one of the projects and see if it works, which may mean we needing to do something fancy about these.

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, I've checked a few projects and those that have CORS settings all have `app.use(cors({origin: '*'}));`. I've tried explicitly allowing `api.freecodecamp.org` and disabling Helmet and CORS wherever possible, but still get the same error.

**Comment by raisedadead** [comment]
Okay, need to investigate then.

**Comment by ojeytonwilliams** [comment]
I think the forms may not be sending the URLs in the first place. Well, the server is complaining because it isn't getting them.

**Comment by alex-parra** [comment]
Hi everyone!
I've been facing this for about a week or so. Tested yesterday and today (just now) and it's still the same. 
For me it's at submitting the Issue Tracker project.
Tests pass but after clicking Submit and go to next project, the request to https://api.freecodecamp.org/internal/project-completed fails with status 403, body is just 'Forbidden' and payload has only `{id: "587d8249367417b2b2512c42", challengeType: 4}`.
For the full request output (headers, etc) see 
[api_freecodecamp_project-completed.txt](https://github.com/freeCodeCamp/freeCodeCamp/files/3758757/api_freecodecamp_project-completed.txt)

Best.

**Comment by raisedadead** [comment]
@ojeytonwilliams you were correct. 

Contributors,

The forms are not sending the links to the API and the validation checks on the API reject the calls as 403

I have created a PR which will send a json response to make this less cryptic on the XHR response. Doesn't fix the issue, but better for debugging.

Now, coming to the client:

1. We need to look into the redux wiring and understand why its not sending out the links to the API as it should.
2. We need to fix the learn (possibly in the layout) or somewhere else to show the messages received from API as Flash.

The later can some as a separate pull-request.

**Comment by ahmadabdolsaheb** [comment]
we are on it.

**Comment by kelsiestevenson** [comment]
I am still experiencing this issue when trying to submit my projects. Would you like for me to open a new issue?

**Comment by raisedadead** [comment]
Hi Kelsie,

Thanks for reporting. Yes, please open a fresh issue.
