### ISSUE TITLE
Sign in page buttons and OPT confirm button need cursor:pointer

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#37396]
When you mouse over the signin buttons on freecodecamp.org/signin the buttons do not show the pointer cursor. They just show the default cursor.

These buttons should show the cursor pointer like all the other buttons on freeCodeCamp.

**Comment by shakti97** [comment]
Should I work on this?

**Comment by ahmadabdolsaheb** [comment]
@shakti97, go ahead please.
