### ISSUE TITLE
Icon used on landing page: Git does not equal GitHub

### ISSUE THREAD

**Issue by embik** [FreeCodeCamp/FreeCodeCamp#3739]
Hello, first of all I'd like to thank you guys for your site. It looks rather nice for people to start and I might be able to recommend it some day.

I'm well aware this is nitpicky, *but* the landing page talks about learning "Git" as a skill (and the corresponding learning materials advices you to set up your own git server). It uses the GitHub icon though. That's not [Git's icon](https://git-scm.com/images/logo@2x.png), it's a different thing. GitHub does not only offer git services but also project management, social features, release downloads, etc. Using Git and GitHub as synonyms might confuse novice developers.

**Comment by BerkeleyTrue** [comment]
We considered adding the git icon but the fact of the matter is the Github Icon is much more recognizable and we are inherently tied to Github.

Happy Coding!

**Comment by embik** [comment]
I'm not sure why "recognizable" is an argument here, this is no matter of "brand", you're pushing novice developers into wrong assumptions by teaching them GitHub = Git. But ultimately, it's your page and your decision, so I have to deal with it.
