### ISSUE TITLE
We need slightly more whitespace under alert banner

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#37395]
When you sign in or change an option on settings, you get an alert banner up top. It could be a little thinner so it doesn't cut so close to the body elements
<img width="1420" alt="Learn___freeCodeCamp_org" src="https://user-images.githubusercontent.com/985197/67129866-59442400-f1c5-11e9-9bb8-458060d44795.png">

**Comment by ahmadabdolsaheb** [comment]
should we go all the way?

<img width="1198" alt="Screen Shot 2019-10-19 at 12 39 56 AM" src="https://user-images.githubusercontent.com/4591597/67130133-1c9a1c00-f209-11e9-925b-a92d97f0d373.png">

**Comment by raisedadead** [comment]
The layout element needs to be pushed below the notification. Currently it overlays on top of it.

**Comment by rickwalking** [comment]
Can I work on it?

**Comment by raisedadead** [comment]
Yes please. Note the the notification should be shorter in height and should also be "injected" in-between the nav and the layout instead of overlaying.
