### ISSUE TITLE
Escape key unfocuses the editor when not meant to.

### ISSUE THREAD

**Issue by DimaTc** [freeCodeCamp/freeCodeCamp#37398]
**Describe the bug**
When trying to exit the multi cursor function (Ctrl + D) with the escape key, the editor loses focus. before the update, it worked fine.
(happens also when trying to deselect a selected text, but can be deselected using the arrow keys instead)

**To Reproduce**
1. Select a word or a character.
2. Press Ctrl + D until you've selected the desired words that you wish to change
3. When trying to deselect with ESC, the editor loses focus.

**Expected behavior**
When a text is selected or the editor has multiple cursors, pressing ESC should only deselect or exit the multi cursor mode and not exit to navigation mode.

**GIF**
![2019-10-19_17-39-18](https://user-images.githubusercontent.com/4152450/67146997-5a468580-f299-11e9-821f-3f9aaedf280b.gif)

**Desktop :**
 - OS: Windows 10 
 - Browser Chrome
 - Version 77.0.3865.120

**Additional context**
Based on bug #37146 and PR #37167

**Comment by thecodingaviator** [comment]
With the change in the functionality of navigating challenges using `Esc`, I believe this has come about. You can snap out of multi-cursor by clicking somewhere on the editor.

What can be done is that we use `Ctrl + D` to snap out of the mode as well.

I'll now defer to @raisedadead

**Comment by DimaTc** [comment]
> What can be done is that we use ```Ctrl + D``` to snap out of the mode as well.

That could work too.

The ```ESC``` key is such a generic key that everyone uses it to cancel tasks, message and all kinds of stuff.

The change of the navigation key may cause confusion and discomfort when trying to deselect text or to hide the autocomplete pop-up window (maybe in more situations that I didn't think of).

**Comment by ojeytonwilliams** [comment]
Thanks for reporting this, looks like I should not have gone with `escape`! 

How about `ctrl+escape`? Does that conflict with anything you can think of?

**Comment by DimaTc** [comment]
```ESC``` is pretty heavily used...

- ```CTRL + ESC``` as you said opens the start menu.

- ```ALT + ESC``` some kind of  ```ALT + TAB``` in windows (also ```CTRL + ALT + ESC```)
- ```SHIFT + ESC``` is the chrome's task manager.
- ```CTRL + SHIFT + ESC``` - windows task manager.
- ```ALT + SHIFT + ESC``` - does something in windows, I don't know what but it changes focus.

Mmm, Maybe ```CTRL + N```? N for navigation, and overriding the default behavior of the browser?

**Comment by ojeytonwilliams** [comment]
Thanks for ruling those out.  Seems like all the obvious ones are taken.

Overriding default behaviour can be frustrating, we'd want to consider that carefully.  It may be better to go with a slightly obscure key combination that does not conflict with any browsers.  `CTRL + ~` seems safe, though.  Another option is `ALT + N`, which is more intuitive, but has some (fairly minor) conflicts.
  
> Edge: Alt + N | Move focus to notification or download (if available).

Firefox uses `ALT` on its own to show or hide the top menu, but `ALT + N` does nothing.

@raisedadead any thoughts?

**Comment by vkWeb** [comment]
@ojeytonwilliams shift + n? Looks safe to me: https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts

**Comment by ojeytonwilliams** [comment]
@vkWeb that's just uppercase 'N', so sadly not.

**Comment by vkWeb** [comment]
@ojeytonwilliams Woaah, shit 🤣 I totally forgot that the editor is focused.

**Comment by moT01** [comment]
Closing this as stale. I think we will just have to live with this one for the time being. Thanks and happy coding 🎉
