### ISSUE TITLE
Display something other than sign in if already signed in

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#37400]
Even when a user is logged in if they go to freecodecamp.org, they see this:
![image](https://user-images.githubusercontent.com/34807532/67147568-b0c0bd80-f2b3-11e9-9de8-b4afcbb5e403.png)

This should be replaced by something. Most likely the challenges page, IMHO.

**Comment by MathewtheCoder** [comment]
Is this fixed ? If not i did like to take this up ?

**Comment by thecodingaviator** [comment]
@MathewtheCoder please wait while we get some input from @freeCodeCamp/moderators

**Comment by raisedadead** [comment]
The landing page intentionally is the way it is to load it instantly. 

It does not have much wiring to user state. We will soon be replacing this page completely with a feed from news for all users.

The only area that the user state would show different pages will be `/learn` for which we have a PR in the works.
