### ISSUE TITLE
Request for more helpful links 

### ISSUE THREAD

**Issue by smarshy** [FreeCodeCamp/FreeCodeCamp#3740]
Challenge [Bonfire: No repeats please](http://www.freecodecamp.com/challenges/bonfire-no-repeats-please) has an issue.
Please describe how to reproduce this issue, and include links to screenshots if possible.

This isn't an easy problem.One can get stuck on it for days.Many of the campers might not have prior knowledge regarding the algorithm.Probably adding a link to heaps algorithm would help here.

**Comment by ltegman** [comment]
I am going to close this because the FCC wiki has a pretty good [article about this problem](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/bonfire-no-repeats-please) and the thought process behind it, so I don't think further documentation is necessary.

Thanks and happy coding!
