### ISSUE TITLE
Weird wrap around on completed progress

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#37415]
![image](https://user-images.githubusercontent.com/1884376/67159392-980ee100-f361-11e9-9fd5-14550beb1bc6.png)

**Comment by floookay** [comment]
Hi, this could be resolved by removing the width of the `.map-title-completed`-class. Should I do that and create a PR?

**Comment by raisedadead** [comment]
You should check locally if the fix will have any unintended side effects, of course a PR is welcome. Thanks.

**Comment by floookay** [comment]
I changed the `width` to `min-width` so the progress reports still align on mobile screens.
