### ISSUE TITLE
Profile page - Timeline - Pagination

### ISSUE THREAD

**Issue by MathewtheCoder** [freeCodeCamp/freeCodeCamp#37412]
**Is your feature request related to a problem? Please describe.**
Currently we display almost all the completed challenges in the timeline which means for some users they have to scroll a lot to reach the footer. 

**Describe the solution you'd like**
1) implementing pagination on the time line would make the profile page look more compact. Displaying max of 10 or 20 per page would be nice.
2) I had wanted to suggest to put a pagination on the API side itself but it seems we are fetching all the user data once and using it in other routes. So it seems it's not possible. If it's possible to do, please notify.

Please give your valuable insights and If it's something to be implemented. I would love to help.

**Comment by raisedadead** [comment]
We can have pagination on the react view itself. 

Honestly as of now, there is not much need in pagenating it on the API side. While we could, its simply an overkill. 

All the API returns is a map of completed challenge id hashes and timestamps. These are light enough to compute rest of rendering related needs which is already available on the client application.

Feel free to create a PR, to mock it out, you can simply replace the user object in your DB with a long list of completed challenges.

**Comment by MathewtheCoder** [comment]
@raisedadead I also felt putting it on the API would be overkill. Okay I will create a PR with a pagination on the react view only.
