### ISSUE TITLE
Profile page - GIthub icon background color not covering whole icon on hover

### ISSUE THREAD

**Issue by MathewtheCoder** [freeCodeCamp/freeCodeCamp#37410]
**Describe the bug**
When we hover over the github icon in profile page. The background color is not covering the  entire icon on hover.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to profile page.
2. Hover over the github icon below profile image
3. The background colour will not cover the icon on hover.
![image](https://user-images.githubusercontent.com/10682672/67157991-427e0880-f350-11e9-911e-a5b3f6cc1011.png)

**Expected behaviour**
The background colour should cover the icon perfectly.
![image](https://user-images.githubusercontent.com/10682672/67158038-e1a30000-f350-11e9-8b9a-20cdcf6332ed.png)
I added the following styles and it came out like what you see above.
![image](https://user-images.githubusercontent.com/10682672/67158050-00a19200-f351-11e9-95eb-1033f9a3b804.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browse: Chrome
 - Version 77

If it's something to be fixed. I would love to work on it.

**Comment by raisedadead** [comment]
Confirmed. Thanks for reporting. A PR is welcome.
