### ISSUE TITLE
[Production] "Academic honesty accepted" looks like a button

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#37425]
**Describe the bug**
When we accept the academic honesty policy and hover over the text, it feels like a button. The cursor should be auto.

**To Reproduce**
1. Go to the settings page
2. Make sure you have accepted academic honesty policy
3. Hover over "you have accepted academic honesty" button

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 32 Bit Pro
 - Browser: Chrome
 - Version: 77.0.3865.90

**Comment by evandroabukamel** [comment]
We can make this button disabled, no? I tried it and it seems good.

**Comment by raisedadead** [comment]
Please feel free to make a PR..

Here are the lines that you probably need to touch:

https://github.com/freeCodeCamp/freeCodeCamp/blob/aa62fdbfe98f872785f792108c6d55582da7e12d/client/src/components/settings/Honesty.js#L20-L30

- [ ] The panel can be a button and disabled.
- [ ] We would need some tests for these as well.

Thanks.

**Comment by raisedadead** [comment]
Please follow our [guidelines for contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md)

**Comment by evandroabukamel** [comment]
Sure, I'll do it as soon as I can, after work.

**Comment by kishore-devaraj** [comment]
@raisedadead I went ahead and created a PR for this, along with unit test. Hope it's fine.
