### ISSUE TITLE
palindrome code will not return false

### ISSUE THREAD

**Issue by phorrom** [FreeCodeCamp/FreeCodeCamp#3743]
Challenge [Bonfire: Check for Palindromes](http://freecodecamp.com/challenges/bonfire-check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20%2F%2F%20Good%20luck!%0A%20%0A%20%20%0A%20%20var%20Newstr%3Dstr.replace(%2F%20%2Fgi%2C'').replace(%2F%2C%2Fgi%2C'').replace(%2F.%2Fgi%2C'').toLowerCase()%3B%0A%0A%20if%20(Newstr%3D%3D%3DNewstr.split('%20').reverse().join())%20%7B%0A%20%20%20%0Areturn%20true%3B%7D%0A%20%20else%20%20%7B%0A%20%20%20%20return%20false%3B%0A%20%20%7D%0A%0A%20%0A%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Works for all palindromes but won't return false when the the phrase is not a palidrome

My code:
```
function palindrome(str) {
  // Good luck!
 
  
  var Newstr=str.replace(/ /gi,'').replace(/,/gi,'').replace(/./gi,'').toLowerCase();

 if (Newstr===Newstr.split(' ').reverse().join()) {
   
return true;}
  else  {
    return false;
  }

 

}



palindrome("eye");

```

**Comment by ltegman** [comment]
The problem with your solution is that the regular call to replace, `replace(/./gi,'')` is not looking for a literal `.`. In a regular expression `.` is a wildcard character that represents any character besides a newline. You need to escape the character like `\.` if you want to look for a literal `.` You current code is turning the string into an empty string, so your comparison will always return true.

Also, you're removing all spaces from your string, but the statement `Newstr.split(' ').reverse().join()` is creating an array at every space, so it doesn't end up splitting your word into characters. I think you mean to be splitting at the empty string `''`, which will split it into characters. Then after that you need to supply a string parameter to `join()` to indicate a string you would like to insert between all the characters you are joining. This can also be an empty string.

The last test case requires you be able to handle more punctuation than just `,` and `.` so you'll want to look into some of the character groupings that regular expressions provide to make this task easier. MDN has a solid list of what is available at [this link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#special-word).

I'm closing this bug as it is not a problem with the tests. Please feel free to reply though if you need further clarification.

Thanks and happy coding!

**Comment by phorrom** [comment]
Thanks!
