### ISSUE TITLE
Cant progress with jQuery

### ISSUE THREAD

**Issue by evanpizzolato** [FreeCodeCamp/FreeCodeCamp#3744]
Challenge [Waypoint: Learn how Script Tags and Document Ready Work](http://www.freecodecamp.com/challenges/waypoint-learn-how-script-tags-and-document-ready-work
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
$(document).ready(function() {

});
</script>

<!-- You shouldn't need to modify code below this line -->

<div class="container-fluid">
  <h3 class="text-primary text-center">jQuery Playground</h3>
  <div class="row">
    <div class="col-xs-6">
      <h4>#left-well</h4>
      <div class="well" id="left-well">
        <button class="btn btn-default target" id="target1">#target1</button>
        <button class="btn btn-default target" id="target2">#target2</button>
        <button class="btn btn-default target" id="target3">#target3</button>
      </div>
    </div>
    <div class="col-xs-6">
      <h4>#right-well</h4>
      <div class="well" id="right-well">
        <button class="btn btn-default target" id="target4">#target4</button>
        <button class="btn btn-default target" id="target5">#target5</button>
        <button class="btn btn-default target" id="target6">#target6</button>
      </div>
    </div>
  </div>
</div>

```
I cannot work with jQuery because every time a "run test" the mobile screen goes blank and all the instructions disappear.  not sure how to progress
using a mac and chrome.

**Comment by ltegman** [comment]
I'm unable to repro this in Chrome myself. Are you seeing any errors in the console?

**Comment by avastu** [comment]
Same here..the waypoint succeeds on my computer in Chrome.

**Comment by evanpizzolato** [comment]
this is the error im getting in chrome in the console:

waypoint-target-elements-by-class-using-jquery:1 Refused to execute script from 'http://www.freecodecamp.com/_JailedSite.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
3VM162:306 Uncaught TypeError: Cannot read property 'left' of undefined

**Comment by ltegman** [comment]
Sorry for the delayed reply. Does this error continue after you refresh the page and does it happen on any challenges other than the jQuery ones?

**Comment by jjowen** [comment]
I'm having same issues progressing through any of the jQuery stuff. (using IE 11 if that matters)

**Comment by ltegman** [comment]
It looks like this might be an issue with an extension you have installed. I would try it without any extensions and see if that helps.

Unfortunately since this issue is user specific I am going to have to close this as unable to repro.

Thanks and happy coding!

**Comment by jjowen** [comment]
I'm not running an extensions on my I.E. Seems to be I.E (also tried on 3 different computers) Specific.  Works great via chrome. I've switched to that for the time being. 

Thanks
