### ISSUE TITLE
Can't login for the last few days

### ISSUE THREAD

**Issue by nicknabdullah** [freeCodeCamp/freeCodeCamp#37457]
I'm trying to login for the last 3 days, using my google/github account but everytime getting the message: 

> "Oops! Something went wrong. Please try again in a moment." 

I've tried clearing cache/cookies/incognito. But nothing is working. Also getting the same error when starting a project task. 

![image](https://user-images.githubusercontent.com/13465486/67257769-48d6c680-f4af-11e9-8288-4c16cc3032f6.png)

**Comment by raisedadead** [comment]
Hi @nicknabdullah 

Chances are you have a duplicate account. Please email me `mrugesh@freecodecamp.org` and I will try and get this resolved for you.

**Comment by cinziaa** [comment]
Hi @raisedadead 
I've the same issue. I've tried revoking and granting access with Github and login with email and Google, but nothing. 
I hope you solve it soon. Thanks

**Comment by raisedadead** [comment]
> Chances are you have a duplicate account. Please email me `mrugesh@freecodecamp.org` and I will try and get this resolved for you.

**Comment by moT01** [comment]
Closing as stale. Please read the comment above if you are having issues with your account. Thanks and happy coding 🎉
