### ISSUE TITLE
Missing test case for the Positive and Negative Lookahead challenge

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#37481]
Per the discussion in the following forum topic, a new test case should be added which should fail if 
a password like “8pass99” which has more than 6 characters long and has 6 consecutive characters.

https://www.freecodecamp.org/forum/t/regex-look-aheads/323407/3

@ArielLeslie has already corrected the [forum hint/solution topic for the challenge](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-positive-and-negative-lookahead/301360), so the actual solution for the challenge file needs to also reflect the following corrected regex:

```js
let pwRegex = /^(?=\w{6,})(?=\D*\d{2})/;
```

**Comment by FullBinaryAlchemist** [comment]
@RandellDawson I would like to work on this issue. https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/positive-and-negative-lookahead.english.md
This is the link containing this problem , right? So I just need to modify `Tests` and add the above test case "8pass99" test case to it ?

**Comment by RandellDawson** [comment]
@FullBinaryAlchemist Yes, but please make sure to run `npm run test:curriculum` locally or use GitPod  before creating the actual PR.  This will validate your changes do not break anything.
