### ISSUE TITLE
Merge project based curriculum ports for testing

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#37493]
There are currently two projects from the upcoming [project based curriculum](https://github.com/freeCodeCamp/CurriculumExpansion) that have been ported to the current platform:

- [Functional programming spreadsheet](https://github.com/freeCodeCamp/freeCodeCamp/pull/36873)
- [CSS skyline](https://github.com/freeCodeCamp/freeCodeCamp/pull/36854)
- [JS RPG game](https://github.com/freeCodeCamp/freeCodeCamp/pull/37678)

These should be merged so we can get feedback from other contributors, but they shouldn't show up on production. All the challenges and pages from the PRs listed above has the [`isBeta`](https://github.com/freeCodeCamp/freeCodeCamp/blob/f1596458108b8dce1dd2743178f2d177dcc826e8/api-server/server/utils/map.js#L150) flag, which should mean that they're only loaded when running locally.

**Comment by moT01** [comment]
If anyone wants to see them now, they could just check out the branch.

**Comment by raisedadead** [comment]
As discussed internally, it will take me a while to get the workflow for new projects to co-exist on the master and production. As a stop gap please target the PRs to the `production-next` for now and land them.

The UI work to support the projects (which may eventually lead to schema changes to the projects' content and file structure) will go into the same branch. @ahmadabdolsaheb will lead that.

Its essentially like a alpha for us to straighten it out before we can release it for our contributors to do more aggressive testing on .dev
