### ISSUE TITLE
2nd p element in red in Waypoint: Change the Font Size of an Element

### ISSUE THREAD

**Issue by birdca** [FreeCodeCamp/FreeCodeCamp#3749]
This challenge didn't say both p should be in red-text, and the 2nd p shown in black in next challenge (Waypoint: Set the Font Family of an Element).

**Comment by ltegman** [comment]
You are absolutely right about this. I've put in a PR to remove the erroneous test :smile:

**Comment by birdca** [comment]
:smiley:

**Comment by awesomeaniruddh** [comment]
Please don't close the issue until the PR has been merged. This way we can ensure that the issue eventually does get fixed (though I'm looking at the PR right now so that won't be a problem *this* time).

Thanks :)

**Comment by birdca** [comment]
Sorry.. And thanks for the reminding~

**Comment by awesomeaniruddh** [comment]
^ and as you can see, when I merged the PR the issue auto-closed :)

**Comment by birdca** [comment]
Wow, coool! I got to spend some time to know this system~

**Comment by eagleone** [comment]
<style>
  .red-text {
    color: red;
    font-size: 16px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>

<p class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>
<p> Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</p>

not accepting...
