### ISSUE TITLE
Recommend adding "curry" link to resources on "Arguments Optional" bonfire

### ISSUE THREAD

**Issue by bconner22** [FreeCodeCamp/freecodecamp#375]
Great bonfire!  I'd never heard of currying until I asked how to start this bonfire on slack and @storbeck told me to google "javascript currying".  I did and got the concept right away.  The following link got me up to speed, recommend putting it in the bonfire or a hint to "look up currying", so campers will have something to go off of - unfortunately the 2 links provided didn't seem to show anything to that effect(they sent me down the rabbit hole of function.arguments, function.bind, etc., and a lot of frustration).  

http://www.crockford.com/javascript/www_svendtofte_com/code/curried_javascript/index.html

**Comment by terakilobyte** [comment]
This is a great recommendation, but I think it deserves a bit more love. Let me know what you think of Javascript Allonge. https://leanpub.com/javascript-allonge/read#pabc

I also recommend giving the whole book a read. It's great.

**Comment by QuincyLarson** [comment]
Closing for now, as our upcoming first-party JavaScript curriculum will cover functional programming techniques like currying better than some short article can do proper service to.

**Comment by bconner22** [comment]
Thanks a bunch for the book, Nathan.  I just started it, and the writing
style meshes much more w/ me than Eloquent.  I think a FCC library is in
order!

On Fri, May 1, 2015 at 4:32 PM, Nathan <notifications@github.com> wrote:

> This is a great recommendation, but I think it deserves a bit more love.
> Let me know what you think of Javascript Allonge.
> https://leanpub.com/javascript-allonge/read#pabc
>
> I also recommend giving the whole book a read. It's great.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/freecodecamp/issues/375#issuecomment-98242885>
> .
>



-- 
Brian Conner
