### ISSUE TITLE
Install and Set Up Mongoose - the right way to connect Mongoose

### ISSUE THREAD

**Issue by dimalapeto** [freeCodeCamp/freeCodeCamp#37516]
Lesson - https://freecodecamp.org/learn/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose

In this lesson you should Install and Set Up Mongoose. Setting up Mongoose in the .env file you should keep in mind, that url to your MongoDB must be saved as STRING. Check it in [docs](https://mongoosejs.com/docs/connections.html).
If you save it as:
`MONGO_URI=mongodb+srv://admin:6813378dima@cluster0-2qeus.gcp.mongodb.net/test?retryWrites=true&w=majority`
it will cause fail tests!
![Screenshot](https://user-images.githubusercontent.com/18643415/67520428-7b501180-f6b1-11e9-971f-3a46b6bc8d44.png)
The right way is:
`MONGO_URI='mongodb+srv://admin:6813378dima@cluster0-2qeus.gcp.mongodb.net/test?retryWrites=true&w=majority'`

Please make corrections in [getting hint](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-install-and-set-up-mongoose/301540) and pinpoint this in the lesson.

**Comment by ZoDaCoKe** [comment]
Updated me

**Comment by luke-ichpekov** [comment]
Thank you this helped!

**Comment by RandellDawson** [comment]
I just fixed the hint/solutions topic for this challenge to incorporate wrapping the uri wit single quotes and fixes a couple other issues at the same time. 

If someone else wants to create a PR to fix the challenge instructions, please go ahead.
