### ISSUE TITLE
[SUGGESTION] Make a more organised Wiki

### ISSUE THREAD

**Issue by AkiraLaine** [FreeCodeCamp/FreeCodeCamp#3752]
Right now, the FreeCodeCamp Wiki seems a bit messy with 400+ wiki pages and more being created every day. Although campers can just search for they are looking for, it might be easier to have these into specific sections.

GitHub has a section of all projects that have great Wiki: https://github.com/showcases/projects-with-great-wikis - we should maybe follow some of these.

We could have a more comprehensive "Home" that talks more about FCC and then use the sidebar as an entry to further topics, like:
* Get Started
* Bonfires
* Basejumps
* Dev Guide
* Improvements to FreeCodeCamp ...etc

**Comment by abhisekp** [comment]
Wow! This wiki is awesome! https://github.com/guard/guard/wiki

**Comment by abhisekp** [comment]
I've updated the FCC wiki with JS Links

**Comment by bugron** [comment]
I think this is closed.
