### ISSUE TITLE
Feature Request: Brownie Points displayed on portfolio

### ISSUE THREAD

**Issue by thejonathangraham** [FreeCodeCamp/FreeCodeCamp#3754]
On your portfolio page would it be possible to let people see how many gitter brownie points you have?

You should probably label this as FEATURE REQUEST

**Comment by thejonathangraham** [comment]
@awesomeaniruddh How do you add labels?

**Comment by awesomeaniruddh** [comment]
There's a label option on the right hand side panel.

**Comment by thejonathangraham** [comment]
You cant add a label though

**Comment by awesomeaniruddh** [comment]
Well, I can :)

**Comment by thejonathangraham** [comment]
Lol. It's cause you're a contributor

**Comment by awesomeaniruddh** [comment]
Yep :)

**Comment by BerkeleyTrue** [comment]
We always have. Even before they were called brownie points. 

![camper_berkeleytrue_s_portfolio___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/10524106/a5de7b82-7332-11e5-81c4-8a1d48940fc8.png)

**Comment by thejonathangraham** [comment]
Oh right lol. Didn't know gitter integrated into that

We always have. Even before they were called brownie points.

[image: camper_berkeleytrue_s_portfolio___free_code_camp]
<https://cloud.githubusercontent.com/assets/6775919/10524106/a5de7b82-7332-11e5-81c4-8a1d48940fc8.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/FreeCodeCamp/FreeCodeCamp/issues/3754#issuecomment-148486247>
.

**Comment by BerkeleyTrue** [comment]
Coolio, closing.

Happy Coding!
