### ISSUE TITLE
Console Behavior in Javascript lessons.

### ISSUE THREAD

**Issue by HumbleAssassin** [freeCodeCamp/freeCodeCamp#37570]
![Untitled](https://user-images.githubusercontent.com/35361381/67624312-1d056900-f840-11e9-8389-daf632b53f8e.png)
![Untitled1](https://user-images.githubusercontent.com/35361381/67624313-1d056900-f840-11e9-8f70-ebeb16ddac89.png)

**Reporting about Console Behaviour in Javascript Challanges in freecodecamp.org**
The console behavior has changes after the update. It is no more showing the live preview for the code. Having it before was helpful for learners as they could see what they had make or sometimes I console log my half done code to see if thinks working fine till then.

**My workarounds**
I mostly copy whole code to codepen and bring it back once the console logs the desired output.

**Thanks for the continuous support**

**Comment by RandellDawson** [comment]
You can use your browser's console to view the result of console.log statements.

**Comment by moT01** [comment]
You can also see the logs when you run the tests.

**Comment by HumbleAssassin** [comment]
Ya ,the workarounds are going well I see this change after the update. Live preview of console refreshing after few second was really helpful for me n other learners who still cannot write the whole snippet with confidence that it sure will work. Additionally it would have helped better in case I try to play with the code.

**Comment by participator** [comment]
I enjoyed that feature too.  Was it intentionally decided that this functionally would no longer be provided?  If not, shouldn't this be considered a bug that should be fixed?

**Comment by moT01** [comment]
It looks like this behavior has been reverted and/or improved. It's much better, so I am going to close this. If anyone thinks it's still an issue, leave a comment and we can reopen it.
