### ISSUE TITLE
"We cannot reach the server to update your progress."

### ISSUE THREAD

**Issue by kelsiestevenson** [freeCodeCamp/freeCodeCamp#37594]
**Describe the bug**
I am unable to submit projects to FCC and have them counted as complete.

**To Reproduce**
1. Sign in to FCC (successfully)
1. Navigate to project to be submitted 
_I see this error in the console_
![image](https://user-images.githubusercontent.com/23170565/67683357-a19ed700-f967-11e9-92da-dcb6014ebcaa.png)
1. Press "Run the Tests"
1. Press "Submit and go to next challenge..."
_I see this error in the console_
![image](https://user-images.githubusercontent.com/23170565/67683432-ca26d100-f967-11e9-9749-23255f274d2b.png)
_And I see this error on the page:_
![image](https://user-images.githubusercontent.com/23170565/67683484-dad74700-f967-11e9-988d-6d84c9dfefee.png)
1. I press the freeCodeCamp logo on top middle of page in order to see my progress on the lessons and I am suddenly logged out
_I see this page after pressing the logo:_
![image](https://user-images.githubusercontent.com/23170565/67683624-0eb26c80-f968-11e9-82de-5d92c0524297.png)

**Expected behavior**
I expect to be able to submit my lessons and have them counted toward my certification

**Screenshots**
See above for screenshots

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 77.0.3865.120

**Comment by kelsiestevenson** [comment]
connects to #37571

**Comment by thecodingaviator** [comment]
We are tracking this in #37571
