### ISSUE TITLE
Exercise Tracker 'boiler-plate'

### ISSUE THREAD

**Issue by pjonp** [freeCodeCamp/freeCodeCamp#37590]
Issue: starting template/Glitch 'remix' project needs help
Link: https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/blob/gomix/server.js
Background: (newbie, trying to complete this project)
Problems:
1) All links tests pass (already an open ticket)
2) line 8; was expecting 'MONGO_URI' for mongoose.connect NOT MLAB_URI
3) line 49; 'listener' never called, 'boiler plate' never starts.
4) project goals unclear; specifically "GET /api/exercise/log?userId" should be "GET /api/exercise/log?userId={userId}"
-minor: too much code provided; specifically lines 22-44 (newbie here added routes after these for about an hour). if required for testing, please add `//YOUR CODE ABOVE THIS LINE`
-(2) DeprecationWarning errors from Mongo
Recommendations: Add more buttons to boiler-plate HTML for testing, change testing from random userID to username (force check for Username already exists)
Ref: https://www.freecodecamp.org/forum/t/should-the-example-excercise-tracker-pass-all-the-challenge-tests/309033

**Comment by raisedadead** [comment]
Closing in favor of the linked issue.
