### ISSUE TITLE
Console log output as user types

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37597]
The test output box used to update as the user typed and any console.log messages would appear in it. This allowed the user to see how their code was behaving in real time.  At some point this stopped happening.  Assuming this wasn't deliberately removed, should it get reintroduced?

**Comment by Ieahleen** [comment]
this seems already mentioned here: https://github.com/freeCodeCamp/freeCodeCamp/issues/37570

**Comment by thecodingaviator** [comment]
Closing in favor of #37570
