### ISSUE TITLE
Konami Code

### ISSUE THREAD

**Issue by terakilobyte** [FreeCodeCamp/freecodecamp#376]
Hide an easter egg *somewhere* within fcc that is activated by the Konami Code (up up down down left right left right a b enter).

**Comment by QuincyLarson** [comment]
@terakilobyte - we could hide in on the public profile view. If you enter it, you automatically get 30 points - like the 30 lives in Contra and Lifeforce! (and add a flag to the user schema).

**Comment by QuincyLarson** [comment]
You could even have a button they could press to initiate entering a secret code, and when they finished, it would refresh the page and they'd have 30 more points

**Comment by QuincyLarson** [comment]
We've got a lot of higher priority items, so I'm going to close this. We'll include cool Easter Eggs as the opportunities arise.
