### ISSUE TITLE
Typo in direction #1 "assert.deepEqual(array, [1,2,3,4,5,6]," is unnecessary and should be removed

### ISSUE THREAD

**Issue by natalka01** [FreeCodeCamp/FreeCodeCamp#3760]
Challenge [Waypoint: Concatenate Strings with concat](http://freecodecamp.com/challenges/waypoint-concatenate-strings-with-concat#?solution=var%20array%20%3D%20%5B1%2C2%2C3%5D%3B%0A%0Avar%20concatMe%20%3D%20%5B4%2C5%2C6%5D%3B%0A%2F%2F%20Only%20change%20code%20below%20this%20line.%0A%0Aarray%20%3D%20array.concat(concatMe)%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A(function()%20%7Breturn%20array%3B%7D)()%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var array = [1,2,3];

var concatMe = [4,5,6];
// Only change code below this line.

array = array.concat(concatMe);

// Only change code above this line.
(function() {return array;})();

```
Typo in direction #1 "assert.deepEqual(array, [1,2,3,4,5,6]," is unnecessary and should be removed

**Comment by dting** [comment]
The assert part is there to indicate what the test case is testing. However, I think you did discover a typo as the closing `)` is missing and there is an unclosed apostrophe that starts the sentence. 

`assert.deepEqual(array, [1,2,3,4,5,6], 'You should concat the two arrays together.`

**Comment by ltegman** [comment]
Good catch and thanks for the report! I am currently in the middle of constructing a PR that will fix this typo and some others present in the OOP and Functional programming waypoints. I'll link it to this issue when I've finished it! :smile:
