### ISSUE TITLE
What should appear in the fcc console?

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37616]
**Is your feature request related to a problem? Please describe.**
Currently test output appears in both the test suite, in the left frame, and below the editor.  This seems like unnecessary duplication when viewing on a desktop, though it could be useful on mobile.

**Describe the solution you'd like**
The fcc console could exclusively show error reports and console logs, updating as the user edits their code.  See #37570 for more discussion.

On desktop, clicking run the tests could scroll the test suite into view (as it can disappear if there are lengthy instructions).

On mobile, it would depend. If there are no errors or logs it would show the test suite. If there are then the console would be shown instead.  The idea being the console output should be the most useful thing to help them debug, though it would involve some flipping back and forth between the console output and the test suite.  I'm not sure what's best for mobile.

Credit to @RandellDawson for pointing out this issue.

**Comment by ojeytonwilliams** [comment]
#37625 is related.  That challenge is confusing because you're told to look at the console to see the error, but it is not shown in the fcc console.  It only appears in the browser console.

**Comment by moT01** [comment]
>// running tests
// tests completed
// console output
the logs, but only one copy

I'm in favor of this - there is one log for each test which makes the output confusing. I think that it should only show exactly what the code would log.

**Comment by moT01** [comment]
Looks like this has been implemented @ojeytonwilliams? Safe to close?

**Comment by ojeytonwilliams** [comment]
It's certainly better than it was, but I'll defer to @RandellDawson on this one.

**Comment by RandellDawson** [comment]
I think it can be closed.
