### ISSUE TITLE
Style sensitivity in QA Functional Tests

### ISSUE THREAD

**Issue by PartyLich** [freeCodeCamp/freeCodeCamp#37611]
**Describe your problem and how to reproduce it:**
**Tell us what's happening:**
Test is failing on FCC while passing in the testrunner output. 
The FCC system requires you to use ' (single quotes) in your test case, while the test runner and language obviously do not. Worse still, using the built in formatter on Glitch changes single quotes to double quotes. So formatting your Glitch code will cause test failures on FCC.

**Your code so far**
Failing code excerpt (note the double quotes):
```js
assert.equal(
  res.body.surname,
  "Colombo",  // This line is problematic
  'res.body.surname should be "Colombo"'
);
```        
Passing code (change to single quotes. meaning is unchanged, purely a style difference):
```js
assert.equal(
  res.body.surname,
  'Colombo',  // This line works
  'res.body.surname should be "Colombo"'
);
```

Similar problem with destructuring. This code passes in the testrunner output, fails on FCC.
```js
test('send {surname: "da Verrazzano"}', function(done) {
        /** place the chai-http request code here... **/
        chai
          .request(server)
          .put("/travellers")
          .send({ surname: "da Verrazzano" })
          .end((err, { status, type, body }) => {  // This proves problematic
            /** place your tests inside the callback **/
            assert.equal(status, 200, "response status should be 200");
            assert.equal(type, 'application/json');

            assert.equal(body.name, 'Giovanni');
            assert.equal(body.surname, 'da Verrazzano');
            done();
          });
      });
```
Adjusting it to remove destructuring passes on FCC:
```js
test('send {surname: "da Verrazzano"}', function(done) {
        /** place the chai-http request code here... **/
        chai
          .request(server)
          .put("/travellers")
          .send({ surname: "da Verrazzano" })
          .end((err, res) => {     // Remove destructuring to pass on FCC
            /** place your tests inside the callback **/
            assert.equal(res.status, 200, "response status should be 200");
            assert.equal(res.type, 'application/json');

            assert.equal(res.body.name, 'Giovanni');
            assert.equal(res.body.surname, 'da Verrazzano');
            done();
          });
      });
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-on-an-api-response-using-chai-http-iii---put-method

**Tell us about your browser and operating system:**
* Browser Name: Chrome 
* Browser Version: 77.0.3865.120
* Operating System: Win10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by communitybicycle** [comment]
Still facing this issue. I looked around the curriculum and the example source code, and it doesn't mention anywhere that this bug exists. If we could add a quick note in the curriculum or in the relevant sections saying that only single quotes will pass the tests, that would save us some time figuring out why our correct code won't pass.

**Comment by rookiebehaviour** [comment]
I have the correct code, all 4 tests pass, but the first test (all tests should pass) fails, which of course doesn't make sense. Can someone please advise what's happening? Neither single or double quotes work for passing the test with the correct code. Thanks.
