### ISSUE TITLE
freecodecamp.org/donate should explain it is a donate page, even for unauthenticated users

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/freeCodeCamp#37617]
Currently, when an unauthenticated user visits https://freecodecamp.org/donate, it shows a sign-in page with no indication it is a donate page.

It would be a better user experience if there was a message at the top of the page saying it was a donate page and explaining why authentication is necessary. With no message about this, users could assume that they are at the wrong page to donate or there is an error happening.

**Comment by ahmadabdolsaheb** [comment]
@beaucarnes, that sounds like a good idea. if you could add the copy you have in mind, we should be able to sort it out quickly.

**Comment by QuincyLarson** [comment]
100% agreed. That has been our attention - we just wanted to curb fraud real quick.

Mrugesh is working on an updated page that will appear before prompting donors to authenticate.

**Comment by moT01** [comment]
I'm not sure why authentication is necessary - What if someone wants to donate, but doesn't want to sign up. Maybe I'm missing something.

**Comment by raisedadead** [comment]
> Maybe I'm missing something.

Because,

> we just wanted to curb fraud real quick

specifically, card testing fraud. You can learn more about these on resources available online. :)
