### ISSUE TITLE
Output error - Basic JavaScript: Local Scope and Functions

### ISSUE THREAD

**Issue by prayaganeethu** [freeCodeCamp/freeCodeCamp#37625]
**Problem and how to reproduce it:**

Console output is showing incorrect value for **Basic JavaScript: Local Scope and Functions**
Expected output for the ```console.log(myVar);``` outside the function ```myLocalScope()``` is a message which conveys that myVar is not defined. Instead, it prints out the value ```10```.

**Link to the page with the problem:**

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/local-scope-and-functions

**Browser and operating system:**
* Browser Name: Google chrome
* Browser Version: 77.0.3865.90 (Official Build) (64-bit)
* Operating System: macOS mojave version 10.14.6

**Screenshot:**
![Screenshot 2019-10-31 at 12 29 43](https://user-images.githubusercontent.com/24582438/67925727-2bee7180-fbda-11e9-8dd1-26479f064a0c.png)

**Comment by moT01** [comment]
It is printing 10 twice, once for each test in the challenge. Both logs you see there are from the `myVar` in the function. If you check the browser console, it shows the two `10`'s and two `ReferenceError: myVar is not defined` - one for each test, and this is the `myVar` at the bottom. The reference errors are not being displayed in our console.

Browser console:
<img width="256" alt="Screen Shot 2019-10-31 at 8 26 13 PM" src="https://user-images.githubusercontent.com/20648924/67996321-c96a9500-fc1c-11e9-9713-e6d0cdcedab9.png">

**Comment by prayaganeethu** [comment]
> It is printing 10 twice, once for each test in the challenge. Both logs you see there are from the `myVar` in the function. If you check the browser console, it shows the two `10`'s and two `ReferenceError: myVar is not defined` - one for each test, and this is the `myVar` at the bottom. The reference errors are not being displayed in our console.
> 
> Browser console:
> <img alt="Screen Shot 2019-10-31 at 8 26 13 PM" width="256" src="https://user-images.githubusercontent.com/20648924/67996321-c96a9500-fc1c-11e9-9713-e6d0cdcedab9.png">

Got it, thanks! Why are the reference errors not shown on the console, though?

**Comment by moT01** [comment]
There has been some work done on our console. It looks like these issues are resolved now. Can you confirm that and close this if it's fine now @prayaganeethu?

**Comment by prayaganeethu** [comment]
Thanks @moT01, verified the changes - looks good 👍 Closing the issue.
