### ISSUE TITLE
Stripe Scripts for the donation modal should not load before donation modal opens.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#37626]
Stripe scripts only load for the lesson donation modal and the donation page.
However, the scripts for the donation modal loads before the donation modal opens.

![Screen Shot 2019-10-31 at 10 33 05 AM](https://user-images.githubusercontent.com/4591597/67928726-ce075d00-fbcc-11e9-82c5-4602d273a38d.png)

here would be a good place to start the investigation.
https://github.com/freeCodeCamp/freeCodeCamp/blob/3a2db6f090821fd0bff8c7258283050552046417/client/src/components/Donation/components/DonateModal.js

**Comment by ojeytonwilliams** [comment]
The initial download of the stripe script is low priority, though, so it should not worsen the user's experience too much.

If we do want to fix this, I'd recommend just taking `<DonateModal />` out of `Learn.js`, modifying gatsby-ssr and leaving a comment that they need adding back in if the modal is going to be used.  Once we know if and when it's going to be used, we can load the scripts at the right time.
