### ISSUE TITLE
Chrome dev tool passes all conditions

### ISSUE THREAD

**Issue by iamgururaj** [FreeCodeCamp/FreeCodeCamp#3762]
Challenge [Bonfire: Check for Palindromes](http://freecodecamp.com/challenges/bonfire-check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20str%20%3D%20str.toLowerCase().replace(%2F%5Cs%2Fg%2C%22%22)%3B%0A%20%20str%20%3D%20str.replace(%2F%5C.%2Fg%2C%22%22)%3B%0A%20%20str%20%3D%20str.replace(%2F%2C%2Fg%2C%22%22)%3B%0A%20%20str%20%3D%20str.replace(%2F%5C(%2Fg%2C%22%22)%3B%0A%20%20str%20%3D%20str.replace(%2F%5C)%2Fg%2C%22%22)%3B%0A%20%20str%20%3D%20str.replace(%2F%5C%5C%2Fg%2C%22%2F%22)%3B%0A%20%20str%20%3D%20str.replace(%2F-%2Fg%2C%22_%22)%3B%0A%20%20var%20s2%20%3D%20str.split(%22%22).reverse().join(%22%22)%3B%0A%20%20return%20str%3D%3D%3Ds2%3B%0A%7D%0A%0Apalindrome(%22eye%22)%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
function palindrome(str) {
  str = str.toLowerCase().replace(/\s/g,"");
  str = str.replace(/\./g,"");
  str = str.replace(/,/g,"");
  str = str.replace(/\(/g,"");
  str = str.replace(/\)/g,"");
  str = str.replace(/\\/g,"/");
  str = str.replace(/-/g,"_");
  var s2 = str.split("").reverse().join("");
  return str===s2;
}

palindrome("eye");


```

**Comment by ltegman** [comment]
Thanks for the report -- looks like this is indeed a problem with the test. The message from the test says it is testing `palindrome("0_0 (: /-\\ :) 0-0")` but it actually ends up testing `palindrome("0_0 (: /-\ :) 0-0")`, so this does need to get fixed.

However, code that correctly answers this bonfire should be removing all punctuation and symbols, which this solution does not do, so when we fix this test we should probably also add another test with lots of symbols to ensure people aren't solving the problem by changing symbols into other ones to solve the problem.

**Comment by abhisekp** [comment]
Ah! it's my fault. 
Onto it.
