### ISSUE TITLE
group lesson buttons.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#37627]
To have a cleaner UI and to encourage users to attempt challenges before asking for help, we need to group the help buttons in lessons.

There should only be three buttons in each lesson: "run the tests", "reset all code", "get help", and their wrapper element should get a ```button-group``` class to space the buttons out and improve lighthouse scores. 

"get hint", "ask for help", "watch a video" buttons should be grouped under the "get help" button and displayed as a dropdown similar to the certification section on settings, or it could be a "dropup" to account for lessons that have a couple of tests or for mobile views. 

![Screen Shot 2019-10-31 at 11 55 39 AM](https://user-images.githubusercontent.com/4591597/67933030-11b29480-fbd6-11e9-902f-fbba71b28c3c.png)

No assignment needed. please proceed with submitting your solution in a pr.

**Comment by stefanosu** [comment]
I'll take this one.

**Comment by thecodingaviator** [comment]
@stefanosu go ahead

**Comment by RandellDawson** [comment]
@thecodingaviator Let's not remove the help wanted label until we get at least one PR submitted.
