### ISSUE TITLE
Exercise Tracker needs tests

### ISSUE THREAD

**Issue by PartyLich** [freeCodeCamp/freeCodeCamp#37633]
Individual thread for the Exercise Tracker portion of #37185

Trying to get involved, and this seems like as good a place as any to start. I haven't had a chance to get setup locally, but what I've gathered so far from the contribution docs and issues i've looked at is that
- tests are executed in a browser environment (not node)
- chai assertions are available
- tests are stored as a stringified function

I may have missed something important - hopefully not, but please let me know.

For the exercise tracker, something like the below might work. It still needs to be stringified and using `getUserInput` to grab the user's url in the actual test. 

`- text: I can create a user by posting form data username to /api/exercise/new-user and returned will be an object with username and <code>_id</code>.`
```js
fetch( 'https://fuschia-custard.glitch.me'+ '/api/exercise/new-user', {
  method: 'POST',
  headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
  // anything longer fails: 'username too long'
  body: `username=fcc_test_${ Date.now() }`.substr(0, 29)
}).then(res => {
  if (res.ok) { 
    res.json().then(data => {
      assert.exists(data._id); 
      assert.exists(data.username);
    }); 
  } else throw new Error(`${ res.status } ${ res.statusText }`);
}, e => {throw new Error(e)} );
```
Using the truncated current time to produce a unique username seems a bit sketchy though.

`- text: I can get an array of all users by getting api/exercise/users with the same info as when creating a user.`
```js
fetch('https://fuschia-custard.glitch.me' + '/api/exercise/users')
    .then(res => res.json().then(data => assert.isArray(data)), e => { throw new Error(e)});
```

And so on for the others. Am I terribly off track?

**Comment by PartyLich** [comment]
quick note for myself (and any future new contributor who stumbles in) re: how to test locally 
`npm run test:curriculum` and `npm run develop` to see the actually site live.

**Comment by RandellDawson** [comment]
> quick note for myself (and any future new contributor who stumbles in) re: how to test locally
npm run test:curriculum and npm run develop to see the actually site live.

This is covered in the documentation.

**Comment by PartyLich** [comment]
> > quick note for myself (and any future new contributor who stumbles in) re: how to test locally
> > npm run test:curriculum and npm run develop to see the actually site live.
> 
> This is covered in the documentation.

I was quite confident I'd be able to find the issue i opened. Less confident I could find the specific line in the docs with the same level of expediency. Thus I left myself a note where I knew i could find it _quickly_
