### ISSUE TITLE
Unclear/no explanation of order of operations in lookahead challenges

### ISSUE THREAD

**Issue by rmgreenstreet** [freeCodeCamp/freeCodeCamp#37639]
**Describe your problem and how to reproduce it:**
In the challenge for "Positive and Negative Lookahead", the solution is `/^(?=\w{6,})(?=\D*\d{2})/`

A couple of previous challenges used that notation of '\D*\d' in different forms, and it never made any sense to me as to why you had to say "ok, look for NO numbers, then look for numbers" after it had already looked for "beginning with at least 6 alphanumeric (word) characters".

Then joops75 clarified the order of operations in a forum post of someone who had the same question I did:

> After each lookahead completes its matching, the search index returns to what >value it was at the start of the lookahead match.

It would be great if this had been explained along the line so we would know the "why" of the second lookahead starting over and making sure that the beginning of the string was not numbers, and then had two numbers, after the first lookahead, separately, had already made sure that the password was at least 6 characters long.

It seems obvious in hindsight, but didn't "click" until that explanation.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/positive-and-negative-lookahead

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 78.0.3904.70 
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by moT01** [comment]
Closing as stale. Thanks and happy coding 🎉
