### ISSUE TITLE
Need a Korean translated version of how-to-setup-freeCodeCamp-locally.md

### ISSUE THREAD

**Issue by nancydocode** [freeCodeCamp/freeCodeCamp#37637]
I am thinking to start on translating this file into Korean. May I?

**Comment by moT01** [comment]
Yes, translation PR's are welcome without an issue - [Here are the current Korean files](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/docs/i18n-languages/korean) - and there's [one open PR for a Korean translation](https://github.com/freeCodeCamp/freeCodeCamp/pulls?q=is%3Aopen+is%3Apr+label%3A%22language%3A+Korean%22) as well. So maybe take a quick look at those.

**Comment by raisedadead** [comment]
Please feel free to create a PR as directed.
