### ISSUE TITLE
Waypoint: Generate Random Whole Numbers within a Range - Can pass the test with and incorrect solution

### ISSUE THREAD

**Issue by ggwc82** [FreeCodeCamp/FreeCodeCamp#3764]
The correct solution is:

return Math.floor(Math.random() * (max-min + 1))  + min

However, I found that the waypoint can also be completed with the following incorrect solution:

return Math.floor(Math.random() * (max-min + 1))

**Comment by jbmartinez** [comment]
`min` equals zero, so adding it makes no difference. A way to enforce the use of a more strict formula is setting `min` to a non zero value

**Comment by ggwc82** [comment]
A non-zero min should have been run in the test part of the waypoint

**Comment by awesomeaniruddh** [comment]
@sanspace please submit a PR. Instructions here: https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Pull-Request-Contribute

Thanks!
