### ISSUE TITLE
"Reverse a String" challenge assumes knowledge of functions not yet taught

### ISSUE THREAD

**Issue by rmgreenstreet** [freeCodeCamp/freeCodeCamp#37664]
**Describe your problem and how to reproduce it:**

On the challenge for "Basic Algorithm Scripting: Reverse a String", it asks you to take the input string and reverse it.

In the instructions, it notes "you may need to turn the string into an array before you can reverse it".

In the "Get a hint" link (https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-reverse-a-string/16043), it instructs you to:

1) use str.split() to separate the characters into an array, which has not been covered up to this point.

2) reverse the order of the items in the array using arr.reverse(), which has not been covered up to this point

3) re-join the items in the array back into a string using arr.join(), which has not been covered up to this point

The list of lessons in order on the /learn page seems to indicate that learners can complete challenges further down the list using information/principles learned from lessons higher up the list. This does not appear to be the case, at least with this particular challenge.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/reverse-a-string

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 78.0.3904.70 
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/50469309/68053755-ba3a2480-fcba-11e9-8ca4-986acbe45f36.png)

![image](https://user-images.githubusercontent.com/50469309/68053741-b1495300-fcba-11e9-8fc2-ae723ba9b254.png)

**Comment by RandellDawson** [comment]
Check out solution number 2 which does not use any of the methods.  The Hints need to be updated.

**Comment by RandellDawson** [comment]
@rmgreenstreet FYI - I just updated the Hints/Solutions page on the forum to reflect a hint for a solution which does not involve methods not yet introduced in the curriculum.  The first solution corresponds to the Hint I added and the other solution using split and reverse is now the second solution.

If you are satisfied with this fix, please let us know, so I can close this issue.

Thank you.

**Comment by rmgreenstreet** [comment]
Sounds good to me!
