### ISSUE TITLE
Suggested Solution to Final Basic JS Exercise is Inconsistent

### ISSUE THREAD

**Issue by damsalem** [freeCodeCamp/freeCodeCamp#37666]
The final Basic JavaScript exercise **[Use Recursion to Create a Countdown](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-recursion-to-create-a-countdown)** has an inconsistent suggested solution located within the **[Get a hint](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-use-recursion-to-create-a-countdown/305925?u=damsalem)** feature.

It suggests the following code:
```
function countdown(myArray, n){
  if(n <= 0){
    return;
  }
  else{
    myArray.push(n);
    countdown(myArray, n - 1);
  }
}
```

While that code does work and does pass the test, it is inconsistent with the previous two recursion exercise hints:

1. The **[Replace Loops using Recursion](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/replace-loops-using-recursion)** exercise and its **[Get a hint](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-replace-loops-using-recursion/301175)**
2. The **[Use Recursion to Create a Range of Numbers](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-recursion-to-create-a-range-of-numbers)** exercise and its **[Get a hint](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-use-recursion-to-create-a-range-of-numbers/301180)**

The inconsistency is that the final exercise's suggested answer does not return a countdown. Whereas the earlier two exercises will return a sum and range respectively.

My suggested answer for the final JS countdown exercise is as follows—note the final return statement:
```
function countdown(myArray, n){
  if (n <= 0) {
    return n;
  } else {
    myArray.push(n);
    countdown(myArray, n - 1);
    return myArray;
  }
}
```
This proposed code is more consistent with the earlier exercise and will reduce confusions for my fellow students.

**Comment by RandellDawson** [comment]
We are in the process of redoing this particular challenge.  I am closing this issue in favor of discussion on [pull request related to the rewriting of this challenge](https://github.com/freeCodeCamp/freeCodeCamp/pull/37548).  Please feel free to add your comments on that PR after reading through the discussion there.

Thank you.
