### ISSUE TITLE
The unsubscribe path works, but the resubscribe doesn't

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#37662]
The unsubscribe path works, but the resubscribe doesn't -- at least it didn't for me. All I wanted to do was change the email address where I receive, but when I try to resubscribe following the link shown in the screenshot above, I get this:

![Screenshot 2019-11-01 19 40 52](https://user-images.githubusercontent.com/20972610/68048585-26c81a00-fce1-11e9-956a-692c9c8818f3.png)

_Originally posted by @laghee in https://github.com/freeCodeCamp/freeCodeCamp/issues/37331#issuecomment-548916882_

**Comment by davidkwan95** [comment]
Hi, I would like to try and fix this

**Comment by PartyLich** [comment]
Is this still broken? Trying with my account I didn't manage to reproduce. Perhaps I'm missing some detail.
![image](https://user-images.githubusercontent.com/2792750/69107817-a6bfe500-0a40-11ea-805b-35a19c441bc5.png)

**Comment by davidkwan95** [comment]
I haven't been able to reproduce it as well actually

**Comment by raisedadead** [comment]
I am going to close this unless @laghee can confirm they are still seeing this error.

**Comment by laghee** [comment]
@raisedadead Weird. It's still happening to me, but only on mobile -- both Firefox and Chrome, so I don't think it's a compatibility issue. Desktop seems to work fine.

**Comment by raisedadead** [comment]
Thanks re-opening.

**Comment by davidkwan95** [comment]
I have been able to reproduce this. You have to be logged out to get that error when pressing the resubscribe button. The easiest way to reproduce it is by using incognito mode.

**Comment by davidkwan95** [comment]
Apparently the API that starts with `/internal` requires authorization, and the api for resubscribe is `/internal/resubscribe/:unsubscribeId`.
So far I can think of 2 solutions:
1. Whitelist the resubscribe api to not require authorization
2. Change the resubscribe api to not use `/internal`, e.g. `/resubscribe/:unsubscribeId`

What do you guys think? @raisedadead

**Comment by raisedadead** [comment]
Ah! Nice catch @davidkwan95. I will take a look.

**Comment by raisedadead** [comment]
Fixed.

**Comment by scissorsneedfoodtoo** [comment]
@QuincyLarson, this still seems to be an issue when you are not signed in and click the "You can click here to resubscribe" button. If you are signed in then the resubscribe button works as expected.

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Yes - this seems to still be an issue. I'm glad to hear people can resubscribe if they're logged in, though we do still want to fix this.

**Comment by QuincyLarson** [comment]
I haven't heard any complaints about this for nearly a year, and I tested this functionality myself (even when not logged in) and I am unable to reproduce this issue. So I am closing this issue.
