### ISSUE TITLE
Advanced Node and Express last 6 challenges failing

### ISSUE THREAD

**Issue by Abbas-000** [freeCodeCamp/freeCodeCamp#37673]
**Describe your problem and how to reproduce it:**
I've noticed that the challenges of Advanced Node and Express from **Sockets** challenge till the last challenge (last 6 challenges of Advanced Node and Express) not passing.
I searched a lot did everything but couldn't pass even a single test. I even copied code from the FCC own glitch project and paste it in in the input but still not passing.
Then I pasted the FCC own project into the input and noticed that wasn't passing as well.
I am uploading the picture where I put the FCC's own glitch project into the input and you will see that wasn't passing the tests as well.
Please fix this testing issues of advanced node and express...
![bug_proof](https://user-images.githubusercontent.com/25281338/68084128-5139e480-fe53-11e9-89c7-199dd00e75fd.PNG)

**Add a Link to the page with the problem:**
starts from here => [link](https://www.freecodecamp.org/learn/information-security-and-quality-assurance/advanced-node-and-express/set-up-the-environment)

ends here => [link](https://www.freecodecamp.org/learn/information-security-and-quality-assurance/advanced-node-and-express/send-and-display-chat-messages)

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 77.0.3865.120 (Official Build) (64-bit)
* Operating System: Microsoft Windows 10 Pro Education

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by skaparate** [comment]
Hey :smile:!

Most of them pass, but there are some things missing:

- I've found that using double quotes is problematic for the tests to pass, so *use single quotes*
- You must require and use cors, otherwise the projects will not pass:

```
const app = express();
const cors = require('cors');
app.use(cors());
```
- There are problems with formatting. For example, when prettier formats the code, if the lines are too long, it splits the lines, which may cause problems. I had the following problem:

```
// The following is beautified by prettier:
io.use(
    passportSocketIo.authorize({

// But the test won't pass unless it's on the same line
io.use(passportSocketIo.authorize({
```

**Comment by Abbas-000** [comment]
My friend!
I had already did as you said but the result is the same.
can you send me the link of your project that you passed these challenges?

**Comment by skaparate** [comment]
Sure!

[Here they are](https://glitch.com/~skaparate-socketio). I just tested again and they work :smile:.

Remember, **do not format/beautify the server.js** file, otherwise the tests will fail. You may need to comment out the `io.emit('user count')` if a test fails.

**Comment by TaraBryn** [comment]
Abbas, If you haven't figured it out yet, I just ran into the same issue, and skaparate linked me to this issue, and I was able to resolve it by adding `app.use(cors())` to the `fcctesting.js` file and that fixed it for me.

**Comment by Abbas-000** [comment]
yes, I did figured that out when skaparate send me the link to his project. thanks skaparate

**Comment by TaraBryn** [comment]
In case anyone else comes across this, there is an [open pull request](https://github.com/freeCodeCamp/boilerplate-socketio/pull/6) for this issue.
