### ISSUE TITLE
Tests not working in Mozilla Firefox

### ISSUE THREAD

**Issue by Spacecase94** [freeCodeCamp/freeCodeCamp#37677]
**Describe your problem and how to reproduce it:**
Using Atom text editor i wrote the code for the technical documentation page, and upon finishing up the project tested my project after refreshing the page and saving my file, the results said i passed 13 out of 16 of the tests, but when i copied and pasted my code into codepen i passed all the tests except one, and that test was #13 saying 

```When I click on a navbar element, the page should navigate to the corresponding section of the "main-doc" element (e.g. If I click on a "nav-link" element that contains the text "Hello world", the page navigates to a <section> element that has that id and contains the corresponding <header>.```

The problem is, when i click the nav-link element i am taken to the corresponding section of the main-doc element.

**Add a Link to the page with the problem:**
https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js
https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-technical-documentation-page
https://codepen.io/christopher-godsson-harwell/pen/MWWJNvK?editors=1100

**Tell us about your browser and operating system:**
* Browser Name: Mozzilla Firefox Developer Edition
* Browser Version: 
* Operating System: Linux Ubuntu version 19.10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot_2019-11-04 MWWJNvK](https://user-images.githubusercontent.com/45679995/68103278-1744fe80-fea4-11e9-96f8-146d86269696.png)
![Screenshot_2019-11-04 Technical Documentation Page](https://user-images.githubusercontent.com/45679995/68103282-1a3fef00-fea4-11e9-845f-ca3cbda880da.png)

**Comment by moT01** [comment]
There's a problem with your code. Test our your buttons and make sure they all work.
