### ISSUE TITLE
NaN is printed as null on JS challenge output

### ISSUE THREAD

**Issue by kevcomedia** [freeCodeCamp/freeCodeCamp#37674]
**Describe your problem and how to reproduce it:**
Running `console.log(NaN)` on any JS challenge outputs `null` on the console output instead of `NaN`.

Related forum topic: https://www.freecodecamp.org/forum/t/325273

User reported seeing `[null]` when it actually should be `[NaN]` with the following code:

```javascript
function bouncer(arr) {
let meh = [];
for (let i = 0; i < arr.length; i++) {
  if (arr[i] !== false && arr[i] !== null && arr[i] !== 0 && arr[i] !== "" && arr[i] !== NaN && arr[i] !== undefined) {
    meh.push(arr[i]);
  }
}
return meh;
}

console.log(bouncer([false, null, 0, NaN, undefined, ""]));
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/falsy-bouncer

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 70.0
* Operating System: Kubuntu 19.04

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

Screenshot of bug in a different challenge:

![image](https://user-images.githubusercontent.com/17902987/68085054-590b8000-fe77-11e9-9872-fc605e2315f4.png)

**Comment by RandellDawson** [comment]
@ojeytonwilliams

**Comment by lasjorg** [comment]
I don't know anything about this part of the code, but I do see JSON.stringify being used in test-evaluator.js and if you stringify `NaN` you get back "null".

```
JSON.stringify(NaN)
"null"
```

> [JSON.stringify(): Description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Description)
> 
> The numbers Infinity and NaN, as well as the value null, are all considered null.


Again, not sure if this is related or not just thought I would post it anyway.

**Comment by ojeytonwilliams** [comment]
Yeah, that's exactly the issue.  My current plan is to use `toString()` if it exists and stringify if not.  I'm just not sure how to make sure this doesn't create any weirdness.

**Comment by lasjorg** [comment]
What about using the [replacer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_replacer_parameter) parameter function?


```
function replacer(key, value) {
  if (value !== value) return 'NaN';
}

console.log(JSON.stringify(NaN, replacer));
// "NaN"
```


Would that be less likely to not cause any weirdness?

**Comment by ojeytonwilliams** [comment]
@lasjorg that sounds way better.  Do you think you'll have time to put that in a PR?
