### ISSUE TITLE
rewrite enzyme tests in react-testing-library

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#37690]
We want to re-write the enzyme based tests in react-testing-library. For example: Profile.test.js is in enzyme. Eventually we want to remove it as a dependency on the client

**Comment by theashraf** [comment]
Can I work on this?

**Comment by raisedadead** [comment]
Yes, please checkout our [guidelines for contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md) for details.

**Comment by theashraf** [comment]
could you please assign it to me?

**Comment by RandellDawson** [comment]
@theashraf We can not assign it to you, but you can work on it and create a PR.
