### ISSUE TITLE
(curriculum): Iterate with JavaScript While Loops

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#37694]
I noticed [this](https://github.com/freeCodeCamp/freeCodeCamp/pull/37683#pullrequestreview-311911070) problem when reviewing that PR.

The example in the challenge description, is the exact code that instructions say to implement...

<img width="275" alt="Screen Shot 2019-11-05 at 12 58 24 PM" src="https://user-images.githubusercontent.com/20648924/68237018-faa3e600-ffcb-11e9-9100-ea5979533e12.png">

[Link to the challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-while-loops) 

We could probably change either the example or the coding part to make them a little different.

Maybe just something as simple as changing the instructions to...
`Push the numbers 5 through 9 to myArray using a while loop.`

or perhaps slightly more difficult...
`Push the numbers 5 through 0, in that order and including both the 5 and 0, to myArray using a while loop`

**Comment by RandellDawson** [comment]
I am fine with either suggestion.

**Comment by PartyLich** [comment]
not really a feature in my mind, but not exactly a bug either. i'm curious what the ideal conventional commit style tag would be here. in any case, the content of the pull request should reflect the slightly more difficult suggestion.
