### ISSUE TITLE
Applied Visual Design: Adjust the Width of an Element Using the width Property

### ISSUE THREAD

**Issue by Tevin-wd** [freeCodeCamp/freeCodeCamp#37695]
**Describe your problem and how to reproduce it:**
I input the code exactly as it is which is just adding a width to a class. i add it but it says it is not correct. see example. 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/adjust-the-width-of-an-element-using-the-width-property

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: latest version
* Operating System: Windows

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/52752643/68255227-ebcc2c00-ffe9-11e9-865b-23f62dd759f5.png)

**Comment by RandellDawson** [comment]
Closing in favor of issue #18045
