### ISSUE TITLE
JavaScript certification not awarded.

### ISSUE THREAD

**Issue by Belengar** [freeCodeCamp/freeCodeCamp#37703]
Hi, I finished all the challenges and projects for the JavaScript Algorithms and Data Structures Certification, but my profile says that there are no certifications in my account. Do I need to do something else to see the certification?
I logged in FCC with the google account option and that is what I have been using. The code that I write is not kept anywhere after I finished each challenge. I started downloading my code each time for the project's part since I did not want to lose my code. Is this the way FCC works?

**Comment by RandellDawson** [comment]
You have to claim each certification under the Profile.

**Comment by Belengar** [comment]
Hey, thanks I got it! :)
