### ISSUE TITLE
Incorrect Info on Page 1 of Debugging

### ISSUE THREAD

**Issue by damsalem** [freeCodeCamp/freeCodeCamp#37708]
I noticed incorrect information on [page 1 of the debugging module](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/debugging/) of JavaScript.

The example of a syntax error is:
```
function willNotWork( {
  console.log("Yuck");
}
// "function" keyword is misspelled and there's a missing parenthesis
```

The comment is incorrect because the function keyword is not misspelled.

**Comment by subashiglesias** [comment]
Can anybody assign this to me ?

**Comment by RandellDawson** [comment]
@subashiglesias You already have a PR for it, so no need to assign.
