### ISSUE TITLE
Bug in ISQA Stock Price Checker example

### ISSUE THREAD

**Issue by Chris6077** [freeCodeCamp/freeCodeCamp#37700]
**Describe your problem and how to reproduce it:**
The problem is, that you can not like a stock twice. It is stuck on one like even when using different connections and devices.

Reproduce by opening the link below on two devices.

Fix: Obtain client IP with this code 

 `req.get('x-forwarded-for').split(",")[0] || req.ip.split(",")[0]`

instead of this code

> `req.connection.remoteAddress`.

Your code always returns the same remoteAddress.

Also, maybe add a hashing function if you implement this. This could be a security issue.

**Add a Link to the page with the problem:**
https://stock-price-checker.freecodecamp.rocks/api/stock-prices?stock=GOOG&like=true

**Tell us about your browser and operating system:**
* Browser Name: /
* Browser Version: /
* Operating System: / 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by moT01** [comment]
I was able to get the google stock to 3 likes. I'm not sure if I added zero or one likes to it - but I wasn't able to add a fourth from a different device. So there does seem to be some sort of issue here. I added the help wanted label in case someone wants to try and give it a fix - I'm guessing @Chris6077's suggestion would work since he probably looked into pretty good. The code is [here](https://github.com/freeCodeCamp/demo-projects/tree/master/stock-price-checker).

**Comment by alirezaghey** [comment]
Hi @moT01 
I made a few tests and @Chris6077 's solution appears to be correct. This is quite old but I'd like to do it if it's still available.
Please let me know. Thanks.

**Comment by nhcarrigan** [comment]
@alirezaghey,

Thank you for your interest in contributing - issues labelled with the `help wanted` tag are open for contribution and PRs are reviewed in the order they are received. 

You are welcome to submit a PR that resolves this issue.

**Comment by scissorsneedfoodtoo** [comment]
Hey all, just left a review in @Chris6077's PR. I also think that's an interesting point about whether storing IP addresses is a security issue.

I did some reading and it seems like a bit of a grey area. There's not much a person can do with just an IP address. At the same time, GDPR regulations consider an IP address, even dynamic ones that most of us have, to be personal identifying information.

I'm not a lawyer, or very familiar with the regulations, but I think it's fine in this case. The project doesn't require storing other identifying information (an email or home address) that can be used with a person's IP address to identify them.

Though if we want to cover all our bases, we could add a short message next to the "Like" checkbox. Something along the lines of "I consent to my IP address being collected and stored" should be enough.

Or it seems like anonymizing the IP address by leaving out the last octet would also work. Then we shouldn't need to get consent to be compliant.

But what do you all think?

**Comment by nhcarrigan** [comment]
I think anonymising the IP address is a good route to go - it ensures we aren't putting campers in a position where they need to handle data deletion requests, and offers a good opportunity to talk about the GDPR and data privacy compliance.

**Comment by alirezaghey** [comment]
How would this work? Like keeping hashes of the IPs and checking against them? Would this be GDPR compliant? How strong needs the hashing function be for GDPR compliance? Or does anonymizing here means just a reversible change, say ROT 13, that prevents only instant recognition upon seeing?

**Comment by nhcarrigan** [comment]
We'd leave off the last octet, so rather than storing `125.0.0.1` we'd store `125.0.0`.
