### ISSUE TITLE
Javascript map, filter, and reduce methods need examples and explanation of using callback functions

### ISSUE THREAD

**Issue by rmgreenstreet** [freeCodeCamp/freeCodeCamp#37704]
**Describe your problem and how to reproduce it:**
In several places in the "Functional Programming" challenges, we're asked to work with the data inside an array passed as an argument, without modifying the array.

In some of these challenges, it asks us to use `map`, `filter`, and `reduce`.

I think it would help a lot to have a lesson (maybe a series of lessons) explaining in more detail how each of those methods work.

**Add a Link to the page with the problem:**

Just one example:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/use-the-filter-method-to-extract-data-from-an-array

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 78.0.3904.87 
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@rmgreenstreet  You have referenced the lesson which deals with the `filter` method, but you say it says to use `map`.  Not seeing that anywhere in that lesson.  
>I know this could be accomplished in a similar way with the slice() method or spread ... operator, but the challenge specifically says to use map().
What challenge are you talking about in the line above?

I will agree that the [map method challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/use-the-map-method-to-extract-data-from-an-array) did not give a specific example of how it works or how to make use of its callback function, so if that is an issue, we can address that.  

It seems like you may have two separate issues here, but I need more information to make that determination.

**Comment by rmgreenstreet** [comment]
Apologies, at the time I was working on the `filter` exercise, and it required combining both `filter` and `map`. I should have brought this up on the original `map` exercise.

**Comment by RandellDawson** [comment]
Do me a favor and close the other issue you opened on reduce and update the body of this issue above to reflect all three lessons (map, filter, and reduce).  I think the copying array is a separate issue, unless I have misunderstood you.

**Comment by rmgreenstreet** [comment]
Yeah, I guess all three of those could use more explanation.

**Comment by RandellDawson** [comment]
I will create a PR to address improving these three existing challenges.
