### ISSUE TITLE
font should look the same on /news and /learn

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#37701]
Although fonts in learn and news share the same size, and weight, they look different on learn and on news.

the Navigation is a good example
![image](https://user-images.githubusercontent.com/4591597/68292647-99901700-008c-11ea-9300-c9fd389db078.png)

a good place to start the investigation would be the global and screen css files for the ghost theme.

https://github.com/freeCodeCamp/news-theme/blob/master/assets/css/global.css
https://github.com/freeCodeCamp/news-theme/blob/master/assets/css/screen.css

**Comment by raisedadead** [comment]
Just want to throw it out there that we have a custom built version of bootstrap that could be a factor? No idea :)

**Comment by lasjorg** [comment]
Are we sure it's not just a difference between the Google font used on news and the fonts [saved locally](https://github.com/freeCodeCamp/freeCodeCamp/pull/37334) used on learn?

Where did we get the fonts from that are saved locally? This [page](http://www.latofonts.com) should have the latest version and even the Lato­Latin version is 71KB and the saved locally is only 37KB.

There are other differences between the fonts, here are some screenshots. You likely have to open up the images to have them side by side. The font from the latofonts page and google looks the same, the one from the repo looks different.

Font from the latofonts page:
![font-local](https://user-images.githubusercontent.com/28780271/68328285-48554700-00cf-11ea-8cca-5a3732787092.png)
Font from google:
![font-google](https://user-images.githubusercontent.com/28780271/68328288-48eddd80-00cf-11ea-8ee8-1867d8e8fdf6.png)
Font from repo:
![font-learn](https://user-images.githubusercontent.com/28780271/68328287-48554700-00cf-11ea-891a-e01e7bfb432b.png)

**Comment by ojeytonwilliams** [comment]
Those don't seem to be Lato.  They're set to Roboto Mono by `.universal-nav .universal-nav-right a` in `universalNav.css`. You can tell by looking at the 'l's (Roboto is a straight line, Lato is fancy).

There are some other differences, though.  The search icon is missing on news (far left) and the vertical positioning is different for the menu items (different padding and line height).

**Comment by lasjorg** [comment]
Right I totally forgot to mention that. I also see Roboto Mono used for the links. But I still wanted to mention that the Lato fonts are different. I didn't check the Roboto fonts against each other but I suspect that they might be different as well. I would have to check it.

**Comment by lasjorg** [comment]
The Roboto Mono fonts seems to match (repo font vs Google font). So I guess it doesn't have the same issue as the Lato font does.

I still think it's worth switching the local Lato font out for a version that matches the Google font, just to avoid inconsistencies.

**Comment by ahmadabdolsaheb** [comment]
> Those don't seem to be Lato. They're set to Roboto Mono by .universal-nav .universal-nav-right a in universalNav.css. You can tell by looking at the 'l's (Roboto is a straight line, Lato is fancy).
Thanks for that, totally forgot that we switched the fonts on navlinks a week ago.

**Comment by ahmadabdolsaheb** [comment]
> The Roboto Mono fonts seems to match (repo font vs Google font). So I guess it doesn't have the same issue as the Lato font does.
> 
> I still think it's worth switching the local Lato font out for a version that matches the Google font, just to avoid inconsistencies.

great observation. although we used to use Lato in for the nav items and we used to use google fonts directly using a gatsby plugin before hosting the fonts, we had the exact issue regarding the font mismatch.

So other than updating the fonts, I think there is another underlying issue that we need to look into.

**Comment by moT01** [comment]
Maybe out of scope here, but the fCC logo looks different as well and news is missing the search icon in the search bar.

**Comment by LarryHu0217** [comment]
I can work on this one,  if we still need this one. @ahmadabdolsaheb

**Comment by ahmadabdolsaheb** [comment]
@LarryHu0217 yes please. 

to compare you need to run ghost locally. here are some pointers:
https://github.com/freeCodeCamp/freeCodeCamp/issues/37921#issuecomment-585603396

**Comment by LarryHu0217** [comment]
I can't find the file that contain the word of news. What do you mean to run ghost locally. @ahmadabdolsaheb

**Comment by ahmadabdolsaheb** [comment]
so news is using a CMS called ghost. you need to install and run that locally. 
https://medium.com/@letian1997/how-to-install-and-try-ghost-blog-in-your-own-computer-64616fc4fbfb

Additionally you should use our ghost theme https://github.com/freeCodeCamp/news-theme to compare the styles between navigation. 

let me know if you have further questions.

**Comment by frankarinze** [comment]
@LarryHu0217 if you need someone to join you on this issue i will be more than happy to help out
