### ISSUE TITLE
Unclear/no explanation of Javascript Array.prototype.reduce() prior to challenge

### ISSUE THREAD

**Issue by rmgreenstreet** [freeCodeCamp/freeCodeCamp#37706]
**Describe your problem and how to reproduce it:**

The linked page asks us to use reduce() on an object containing several film objects, containing several properties for each film, to get the average of ratings of films by Christopher Nolan.

Unless I've missed something, the way reduce() works and how to use it has not yet been explained, on this page or in any previous lesson.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/use-the-reduce-method-to-analyze-data

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 78.0.3904.70
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
I think we can probably add an example of using reduce and also explain more about how to use the callback function.
