### ISSUE TITLE
Waypoint: Get Set for Basejumps error while installation

### ISSUE THREAD

**Issue by iamads** [FreeCodeCamp/FreeCodeCamp#3771]
After performing the 11th step :  `rm -rf * && echo "export NODE_PATH=$NODE_PATH:/home/ubuntu/.nvm/v0.10.35/lib/node_modules" >> ~/.bashrc && source ~/.bashrc && npm install -g yo grunt grunt-cli generator-angular-fullstack && yo angular-fullstack`
when yeomann runs `npm install & bower install` gave the following error. Also when I again tried to install the installation process was killed by cloud9

```
jquery#2.1.4 client/bower_components/jquery
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v0.12.7/bin/node" "/home/ubuntu/.nvm/versions/node/v0.12.7/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED
npm ERR!     at exports._errnoException (util.js:746:11)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
npm ERR!  { [Error: connect ECONNREFUSED]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   parent: 'workspace' }
npm ERR! 
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm-debug.log
iamads:~/workspace $ ^C
iamads:~/workspace $ npm install && bower install
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN deprecated CSSselect@0.7.0: the module is now available as 'css-select'
Killed
```

**Comment by harshitanand** [comment]
just start a new workspace and in the terminal check node version using "node -v"
after that go through following steps for successful env setup

source ../.nvm/nvm.sh
nvm install v0.12.7
nvm use v0.12.7

after that use following command

echo "export NODE_PATH=$NODE_PATH:/home/ubuntu/.nvm/v0.12.7/lib/node_modules" >> ~/.bashrc && source ~/.bashrc

then type

rm -rf * && npm install -g yo grunt grunt-cli generator-angular-fullstack && yo angular-fullstack

it will give you an error try following again

yo angular-fullstack

once it is successful try following comands

npm install -g bower
bower install
npm install

then install mongodb using

mkdir data && echo 'mongod --bind_ip=$IP --dbpath=data --nojournal --rest "$@"' > mongod && chmod a+x mongod && ./mongod

then try running following in another terminal

grunt serve

I have tested above method many times and it works

**Comment by andylacroce** [comment]
@harshitanand tried your steps and hit the following error

andylacroce@basejump:~/workspace $ grunt serve

/home/ubuntu/workspace/node_modules/grunt/node_modules/findup-sync/lib/findup-sync.js:33
    }).flatten().uniq().value();
       ^
TypeError: Object Gruntfile.js has no method 'flatten'
    at Object.module.exports [as findup] (/home/ubuntu/workspace/node_modules/grunt/node_modules/findup-sync/lib/findup-sync.js:33:8)
    at Task.task.init (/home/ubuntu/workspace/node_modules/grunt/lib/grunt/task.js:427:16)
    at Object.grunt.tasks (/home/ubuntu/workspace/node_modules/grunt/lib/grunt.js:120:8)
    at Object.module.exports [as cli] (/home/ubuntu/workspace/node_modules/grunt/lib/grunt/cli.js:38:9)
    at Object.<anonymous> (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/grunt-cli/bin/grunt:45:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by harshitanand** [comment]
did your 

bower install & npm install

ran fine with no errors try running them individually

bower install 
npm install

and then run 

grunt serve 

if the previous commands successfully ran without errors

**Comment by andylacroce** [comment]
I ran both individually.  I received a bunch of warnings on the npm install (below), but no errors.

npm WARN unmet dependency /home/ubuntu/workspace/node_modules/grunt-mocha-test/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/grunt-mocha-test/node_modules/mocha/node_modules/commander,
npm WARN unmet dependency which is version 2.0.0
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/grunt-mocha-test/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/grunt-mocha-test/node_modules/mocha/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/grunt-google-cdn/node_modules/bower requires chalk@'^1.0.0' but will load
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/grunt-google-cdn/node_modules/chalk,
npm WARN unmet dependency which is version 0.5.1
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/grunt-google-cdn/node_modules/google-cdn requires bower@'~1.3.1' but will load
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/grunt-google-cdn/node_modules/bower,
npm WARN unmet dependency which is version 1.6.3
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/karma/node_modules/connect requires body-parser@'~1.13.3' but will load
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/body-parser,
npm WARN unmet dependency which is version 1.5.2
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/karma/node_modules/connect requires cookie-parser@'~1.3.5' but will load
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/cookie-parser,
npm WARN unmet dependency which is version 1.0.1
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/karma/node_modules/connect requires compression@'~1.5.2' but will load
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/compression,
npm WARN unmet dependency which is version 1.0.11
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/karma/node_modules/connect requires errorhandler@'~1.4.2' but will load
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/errorhandler,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/karma/node_modules/connect requires express-session@'~1.11.3' but will load
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/express-session,
npm WARN unmet dependency which is version 1.0.4
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/karma/node_modules/connect requires method-override@'~2.3.5' but will load
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/method-override,
npm WARN unmet dependency which is version 1.0.2
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/karma/node_modules/connect requires morgan@'~1.6.1' but will load
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/morgan,
npm WARN unmet dependency which is version 1.0.1
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/karma/node_modules/connect requires serve-favicon@'~2.3.0' but will load
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/serve-favicon,
npm WARN unmet dependency which is version 2.0.1
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/karma/node_modules/http-proxy requires colors@'0.x.x' but will load
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/karma/node_modules/colors,
npm WARN unmet dependency which is version 1.1.2
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/grunt/node_modules/js-yaml/node_modules/argparse requires underscore.string@'~2.4.0' but will load
npm WARN unmet dependency /home/ubuntu/workspace/node_modules/grunt/node_modules/underscore.string,
npm WARN unmet dependency which is version 2.2.1

**Comment by veronikabenkeser** [comment]
I am getting the following error: 

veronikabenkeser:~/workspace $ grunt serve
Running "serve" task

Running "clean:server" (clean) task

Running "env:all" (env) task

Running "concurrent:server" (concurrent) task

Running "injector:scripts" (injector) task
Missing option `template`, using `dest` as template instead
Injecting js files (13 files)

Running "injector:css" (injector) task
Missing option `template`, using `dest` as template instead
Injecting css files (5 files)

Running "wiredep:target" (wiredep) task
Warning: Cannot find module './lang/clone' Use --force to continue.

Aborted due to warnings.

When I preview the app, it says:
Cloud9 can't get you to your requested workspace. Here are some suggestions on how to figure out what's going on:

    Check that the workspace name (basejump1) and username (veronikabenkeser) are typed correctly.
    Check that the server is successfully running on Cloud9:
        If the server hit an error, the output window will have a message telling you what it is
        If you're in the middle of debugging code, your server might be paused right now
        The server might be running on a different port; make sure it's on port $PORT with $IP as the IP address.


I tried killing all processes and then running and database and the grunt command in another terminal, but I am still getting the same error.

**Comment by veronikabenkeser** [comment]
@iamads Were you able to get it to work?

**Comment by iamads** [comment]
Sorry for the delay
@harshitanand I tried the commands you provided , most of the time my installation process was killed by c9 . When I again ran the install commands I got the same warnings as @andylacroce .

@veronikabenkeser  No , for now I am doing the basejumps locally on  vm

**Comment by HexORSist** [comment]
Im seeing the same problem with "grunt serve"  that @andylacroce is.

**Comment by ltegman** [comment]
Free Code Camp has stopped supporting Angular-Fullstack for basejumps and has transitioned for Clementine.js. The setup process for Clementine is much simpler and (in my experience) less error prone, so hopefully you'll have better luck with that!

Thanks and happy coding!
