### ISSUE TITLE
Public Portfolio

### ISSUE THREAD

**Issue by rdefa001** [freeCodeCamp/freeCodeCamp#37714]
Hi there, for some reason my public portfolio its not displaying anymore. Although I have every button set to public. When I click on view public portfolio, the page never uploads completely. 

Would love to read from you guys. 

Thanks!

**Comment by ahmadabdolsaheb** [comment]
could you please share the link to your portfolio?

**Comment by rdefa001** [comment]
Hi there,

 The link is https://www.freecodecamp.org/raphael%20nunes


Thanks!
________________________________

**Comment by ojeytonwilliams** [comment]
As far as I can see there are a few problems here.  

- The username has a space (`%20`), which should not have happened.
- The path  https://www.freecodecamp.org/raphael%20nunes should go to a 404 not a blank page.
- The client side validation (which rejects spaces) doesn't match the server side validation.

@raisedadead is this assessment right?  If so, I'll create separate issues/PRs for the last two.

**Comment by raisedadead** [comment]
Hi @ojeytonwilliams you are right this is a validation issue with the username. Need to fix, thanks for taking this up.

Hi @rdefa001 you should remove the space in between your username as a workaround for now. Thanks for reporting this bug.
