### ISSUE TITLE
Cannot save new progress

### ISSUE THREAD

**Issue by troncarter** [freeCodeCamp/freeCodeCamp#37719]
I cannot save any new progress. Once I complete a challenge, I click submit and go to next challenge. When I go back to the curriculum page, it still shows the challenge as incomplete.

At the top of the page there is a blue banner that says "We cannot reach the server to update your progress at this time" (screenshot below)

* Browser Name: Chrome
* Browser Version: Version 78.0.3904.70
* Operating System: OS X El Capitan 10.11.6

![Screen Shot 2019-11-07 at 12 23 51 PM](https://user-images.githubusercontent.com/26206962/68506345-bb250600-0226-11ea-993b-edfbfb1359a5.png)

**Comment by RandellDawson** [comment]
Are you sure you are logged in?

**Comment by TimFau** [comment]
I'm having the same issue. Username 'timfau'.

**Comment by ojeytonwilliams** [comment]
The offline warning should only ever be triggered if you're not connected to the internet or not logged into your account.  

@troncarter @TimFau could you go to https://www.freecodecamp.org/settings?  If you're not logged in it will ask you to.  If you are logged in you should see something like this:
![image](https://user-images.githubusercontent.com/15801806/68533808-a5e6cf00-032d-11ea-888f-bfbb865e8125.png)

Let us know whether or not you see "We cannot reach the server to update your progress at this time" after logging in.

**Comment by TimFau** [comment]
I am logged in:
![image](https://user-images.githubusercontent.com/7255687/68534151-07437980-02ff-11ea-832e-f4126ee510ba.png)
I still see the message:
![image](https://user-images.githubusercontent.com/7255687/68534165-19bdb300-02ff-11ea-8e13-354f9dd869d2.png)

**Comment by TimFau** [comment]
Hmm I also tried logging out and back in and now I can't login at all:
![image](https://user-images.githubusercontent.com/7255687/68534229-e3ccfe80-02ff-11ea-8e4d-64bbb41ffe29.png)

Cleared cache/cookies/tried incognito, same thing.

**Comment by ojeytonwilliams** [comment]
@TimFau Ah... sorry to hear that.  It sounds like you'll need to contact support, support@freecodecamp.org, as you might have a duplicate account.  If so, they'll need to resolve that for you.  https://github.com/freeCodeCamp/freeCodeCamp/issues/37457 has some discussion about this.

It's difficult to tell exactly what was going on (why you were able to see the settings, but unable to submit challenges), but hopefully everything will be resolved once you can log in again.

**Comment by TimFau** [comment]
Thank you! I'll reach out to them.

**Comment by troncarter** [comment]
> @troncarter Are you sure you are logged in? What is your username?

Yes I am logged in. Whenever I log in, it kicks me out. My username is troncarter

**Comment by RandellDawson** [comment]
@troncarter Sounds like you may have a duplicate account.  Contact support@freecodecamp.org and explain that you are having trouble logging.  They will check to see if you have two accounts and merge them and delete one.

**Comment by GuljanKG** [comment]
Hello, is anyone experiencing issues with React section? I not being able to run the tests  (it is freezing) and not being able to save my progress. Also, I tried to login to the forum to see if other students are experiencing the same issue, and cannot login to the forum either.

**Comment by troncarter** [comment]
I may have found a workaround. It still logs me out whenever I click the 'freecodecamp' icon in the top nav bar. But if I click '/learn', it keeps me signed in - even after completing a challenge. It also seems to save the progress. Not sure if this is by design.

Regards

**Comment by raisedadead** [comment]
This is by design.
