### ISSUE TITLE
I want to join freecodecamp

### ISSUE THREAD

**Issue by viveksharmaui** [freeCodeCamp/freeCodeCamp#37724]
Hello members,
I'm contributor of freecodecamp and I'm from Pakistan . 
I wanna join freecodecamp i want to become part of this organization what is procedure of joining this organization ? 
Your help will be appreciated .
Thanks !

**Comment by moT01** [comment]
`Tip #1`: Don't create an issue for something that isn't an issue.

You can try asking in the [contributors chat room](https://gitter.im/FreeCodeCamp/Contributors), or on the [contributors topic of the forum](https://www.freecodecamp.org/forum/c/contributors), or maybe try contacting someone by email.

Other than that, I would encourage you to keep contributing and you will get more and more recognition.

**Comment by viveksharmaui** [comment]
Thank you so much for your positive response and guiding me .
