### ISSUE TITLE
Typo in Debugging Assignment Operator

### ISSUE THREAD

**Issue by damsalem** [freeCodeCamp/freeCodeCamp#37728]
In the [debugging lesson covering the assignment operator](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/debugging/catch-use-of-assignment-operator-instead-of-equality-operator), you will find a typo.

I've quote it in full below and **emboldened** the typo:

"The code below **assigns x to be 2**, which evaluates as true. Almost every value on its own in JavaScript evaluates to true, except what are known as the "falsy" values: false, 0, "" (an empty string), NaN, undefined, and null."

```
let x = 1;
let y = 2;
if (x = y) {
  // this code block will run for any value of y (unless y were originally set as a falsy)
} else {
  // this code block is what should run (but won't) in this example
}
```

The correct statement should be: The code below assigns x to be 1, which evaluates as false.

**Comment by RandellDawson** [comment]
@damsalem `2` is a truthy value, so if (2) would evaluate to `true`.

I am closing this issue as the current verbiage is correct.

**Comment by damsalem** [comment]
@RandellDawson thank you for addressing this. Will consult the forum prior to opening a ticket in the future.
