### ISSUE TITLE
Confusing task in Basic JavaScript: Comparisons with the Logical And Operator

### ISSUE THREAD

**Issue by allison-strandberg** [freeCodeCamp/freeCodeCamp#37734]
**Describe your problem and how to reproduce it:**
For this challenge, the starting code in my editor contains the following lines:
```
  if (val) {
    if (val) {
      return "Yes";
    }
  }
```
The challenge is

> Combine the two if statements into one statement which will return "Yes" if val is less than or equal to 50 and greater than or equal to 25. Otherwise, will return "No".

Since the idea behind this challenge is the ability to combine conditions with the && operator, I would expect the starting code to instead read:

```
  if (val <= 50) {
    if (val >= 25) {
      return "Yes";
    }
  }
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparisons-with-the-logical-and-operator

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 76.0.3809.100
* Operating System: MacOS Sierra

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**'
<img width="1408" alt="Screen Shot 2019-11-10 at 5 36 23 PM" src="https://user-images.githubusercontent.com/55810428/68552050-d2a7ee80-03e0-11ea-8e7f-47cef1128e02.png">

**Comment by RandellDawson** [comment]
The instructions tell you what to do regardless of the seed code.  If the seed code was provided as you describe, it would not be much of a challenge to solve.

**Comment by allison-strandberg** [comment]
I think the point of the exercise is to demonstrate the usage of the && operator, so even though it's easier with my suggestion, it's not trivial. If you'd rather not give that hint, though, there's no reason for the nested if statements in the seed code, and I was confused by them. The seed code should read:
```
if (val) {
    return "Yes";
}
```

**Comment by RandellDawson** [comment]
The point of the exercise is two-fold.  One is to teach the user how to use the `&&` operator.  The other is to have the user figure how to achieve the same logic with the `&&` operator as without the operator using the nested if statements.  I do not see any reason to change this challenge.

I will let the other collaborators/mods give their opinions on this issue.

**Comment by ojeytonwilliams** [comment]
I'm with @RandellDawson on this one - I don't think the seed needs changing.  I redid the challenge and found that the nested if statements were helpful.  You can create the intermediate solution:
```js
function testLogicalAnd(val) {
  // Only change code below this line

  if (val >= 25) {
    if (val <= 50) {
      return "Yes";
    }
  }

  // Only change code above this line
  return "No";
}
```
if you're more comfortable with nested if statements and that will pass all but the first two tests.  This allows you to confirm that you've got the logic right before refactoring it into a single conditional.

The only thing I would consider changing is 

> Combine the two if statements into one statement

to

> Replace the two if statements with one statement, using the `&&` operator, 

since 'combine' *slightly* implies that the new statement is built out of the original two, which isn't really the case here.

Doing that should make it less confusing without watering the task down.

**Comment by allison-strandberg** [comment]
Thanks @ojeytonwilliams: I like your suggestion to change the wording to
> Replace the two if statements with one statement, using the && operator,

**Comment by moT01** [comment]
Any interest in creating a PR for that @allison-strandberg?

**Comment by allison-strandberg** [comment]
Thank you for the link @moT01!
