### ISSUE TITLE
Unclear description for Basic JavaScript: Selecting from Many Options with Switch StatementsPassed

### ISSUE THREAD

**Issue by allison-strandberg** [freeCodeCamp/freeCodeCamp#37733]
**Describe your problem and how to reproduce it:**
I was confused by the text "Here is a pseudocode example:" before the switch case code sample. It seemed to imply that the code is not the actual JavaScript syntax for a switch case. I recommend including a simple non-pseudocode example instead. 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/selecting-from-many-options-with-switch-statements

**Comment by RandellDawson** [comment]
> It seemed to imply that the code is not the actual JavaScript syntax for a switch case. 

It is not valid syntax.  That is the point.

**Comment by allison-strandberg** [comment]
The exercise is to write a switch statement: it should be clear that the example is introducing the correct JavaScript syntax for a switch statement, not a pseudocode representation of switch statement logic.

**Comment by RandellDawson** [comment]
@allison-strandberg If you have an idea how best to show a real example (instead of the current pseudo-code), we can discuss it hear and get consensus with the other collaborators and then someone can create a pull request.

**Comment by allison-strandberg** [comment]
@RandellDawson how about something like this?
```
switch(lowercaseLetter) {
  case "a":
    return "A";
    break;
  case "b":
    return "B";
    break;
...
  case "z":
    return "Z";
    break;
}
```

**Comment by ojeytonwilliams** [comment]
@allison-strandberg agreed, the existing code is a bit odd, since it's actually valid JavaScript masquerading as pseudocode.  I'd be inclined to start with:

> A switch statement can be written as follows:
```js
switch(num) {
  case value1:
    /* statements to evaluate if num === value1 */
    break;
  case value2:
    /* statements to evaluate if num === value2 */
    break;
...
  case valueN:
    /* statements to evaluate if num === valueN */
    break;
}
```
and later just an abridged version of @allison-strandberg's example

```js
switch(lowercaseLetter) {
  case "a":
    console.log("A");
    break;
  case "b":
    console.log("B");
    break;
}
```

I don't think we should be returning from switch statements, since https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions is later in the curriculum.

**Comment by moT01** [comment]
You're saying you want two examples in there @ojeytonwilliams? I would just go with your first example and remove the ellipsis (`...`).

**Comment by ojeytonwilliams** [comment]
I was in two minds about the ellipsis, but it's perhaps better to just make the whole thing valid js.  

Generally I like to include working examples - hence the second one.  It does seem a little redundant, though, so I don't mind if it's not used.

The main thing, after all, is not to refer to valid syntax as pseudocode.

**Comment by moT01** [comment]
The first one is a working example (if the `...` is removed). It just uses variables instead of something more concrete. Either way I would try and stick with one example, perhaps we could just go with something like the second example so it's more obvious.

**Comment by ojeytonwilliams** [comment]
Sorry, I wasn't clear.  I think of the first one as a more a definition than an example, but, either way, I take your point that we should only have one.

**Comment by RandellDawson** [comment]
I like @ojeytonwilliams second example (the one with valid JS).

**Comment by lasjorg** [comment]
Should the code example in the challenge that follows this one be changed as well?
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/adding-a-default-option-in-switch-statements

**Comment by ojeytonwilliams** [comment]
I think it should, yes.  Again it should be something concrete.
