### ISSUE TITLE
Bonfire: Return Largest Numbers in Arrays; My code does not clear condition 2

### ISSUE THREAD

**Issue by rejreign** [FreeCodeCamp/FreeCodeCamp#3773]
Challenge [Bonfire: Return Largest Numbers in Arrays](http://freecodecamp.com/challenges/bonfire-return-largest-numbers-in-arrays#?solution=function%20largestOfFour(arr)%20%0A%7B%0A%20%20%2F%2F%20You%20can%20do%20this!%0A%20var%20newArray%20%3D%20%5B%5D%3B%0A%20%20var%20maxi%20%3D%200%3B%0A%20%0A%20%20for(x%20%3D%200%3B%20x%20%3C%20arr.length%3B%20x%2B%2B)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20for(i%20%3D%200%3B%20i%20%3C%20arr%5Bx%5D.length%3B%20i%2B%2B)%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20if(maxi%20%3C%20arr%5Bx%5D%5Bi%5D)%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20maxi%20%3D%20arr%5Bx%5D%5Bi%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20else%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20maxi%20%3D%20maxi%3B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20newArray.push(maxi)%3B%0A%20%20%20%20%7D%0A%20%20%0A%20%20return%20newArray%3B%0A%7D%0A%0AlargestOfFour(%5B%5B4%2C%205%2C%201%2C%203%5D%2C%20%5B13%2C%2027%2C%2018%2C%2026%5D%2C%20%5B32%2C%2035%2C%2037%2C%2039%5D%2C%20%5B1000%2C%201001%2C%20857%2C%201%5D%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```
>function largestOfFour(arr) 
{
  // You can do this!
 var newArray = [];
  var maxi = 0;
 
  for(x = 0; x < arr.length; x++)
    {
      
      for(i = 0; i < arr[x].length; i++)
        {
          if(maxi < arr[x][i])
            {
              maxi = arr[x][i];
            }
          else 
            {
              maxi = maxi; 
            }
        }
      newArray.push(maxi);
    }
  
  return newArray;
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 
![bonfire largest of four](https://cloud.githubusercontent.com/assets/13300617/10543631/0b6c057a-7417-11e5-9c3e-79b3796515b7.JPG)
39], [1000, 1001, 857, 1]]);

```
My code does not clear condition 2. Why please? My code was rewritten in such a way as to traverse in chronological order the given array. Please assist.

**Comment by jlslew** [comment]
You are not resetting your variable `maxi` after traversing each `arr[x]`.  The test 2 is failing because when you are traversing the 2nd array, your function is looking for a value greater than 27.

**Comment by rejreign** [comment]
Yayy! It worked. Thanks jlslew.

function largestOfFour(arr) 
{
  // You can do this!
 var newArray = [];
 
  for(x = 0; x < arr.length; x++)
    {
        var maxi = 0;
      for(i = 0; i < arr[x].length; i++)
        {
          if(maxi < arr[x][i])
            {
              maxi = arr[x][i];
            }
          else 
            {
              maxi = maxi; 
            }
        }
      newArray.push(maxi);
    }
  
  return newArray;
}

largestOfFour([[4, 5, 1, 3], [13, 27, 18, 26], [32, 35, 37, 39], [1000, 1001, 857, 1]]);
