### ISSUE TITLE
Change to description of .length function in: find-the-length-of-a-string.english.md

### ISSUE THREAD

**Issue by Kbarias** [freeCodeCamp/freeCodeCamp#37748]
**Describe your problem and how to reproduce it:**
 I think that the description of the <code>.length</code> function for the [find-the-length-of-a-string](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/find-the-length-of-a-string.english.md)  challenge should include that spaces are taken into consideration when calculating the length of a string. Being that this is basic JavaScript, I think that this detail should be included.

**Comment by ojeytonwilliams** [comment]
It does, implicitly:  
```js
"Alan Peter".length; // 10
```
is only 10 because of the space.
