### ISSUE TITLE
Intellisense obscures your code in the code editor

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/freeCodeCamp#37740]
![Screen Shot 2019-11-11 at 9 13 04 PM](https://user-images.githubusercontent.com/11348778/68639737-88536a00-04d3-11ea-8e0d-e0a8c8a134fc.png)
![Screen Shot 2019-11-11 at 9 13 22 PM](https://user-images.githubusercontent.com/11348778/68639743-8e494b00-04d3-11ea-9e90-a64de6517b3f.png)
![Screen Shot 2019-11-11 at 9 15 58 PM](https://user-images.githubusercontent.com/11348778/68639749-93a69580-04d3-11ea-88fb-55e498652393.png)

**Tell us about your browser and operating system:**
* Browser Name: Chrome 
* Browser Version: 78
* Operating System: Mac OSX

**Comment by raisedadead** [comment]
I have been long wishing to disable IntelliSense in the monaco-editor. Its not use-friendly and often counter productive. I think we should be opinionated about this and remove it completely.

**Comment by raisedadead** [comment]
Hey @Manish-Giri will you be interested in looking up the monaco docs and adding the config?

**Comment by Manish-Giri** [comment]
@raisedadead Sure! I'll take it up.

**Comment by ojeytonwilliams** [comment]
To my mind, the problem is that the parameter hints are a mess.  So, the problem is that Intellisense isn't working probably, rather than it exists.  

When I'm working through a challenge I find the suggestions are helpful, so you can do things like this:
![Intellisense](https://user-images.githubusercontent.com/15801806/69533549-47019680-0f78-11ea-8c4c-ee800fef6818.gif)

I deliberately stopped before typing `(`, since that's where it all falls apart, but we just use
```js
    parameterHints: {
        enabled: false
      }
```
to remove the malfunctioning bit.

**Comment by Manish-Giri** [comment]
@ojeytonwilliams I can make the change in #37813 to turn off just `parameterHints`, if that's the general consensus. That should solve the issue in my screenshots. Though, I don't know if we can be completely sure if leaving other "types" of intellisense on won't cause this mess in some other instance. 

Just waiting on @raisedadead's thoughts..

**Comment by ojeytonwilliams** [comment]
True, it may be safer to remove it entirely.  I would miss code completion, though!

**Comment by Manish-Giri** [comment]
Me too! Wouldn't have to type as much :/

**Comment by raisedadead** [comment]
OK - I guess we are cool with removing just the `parameterHints` for now and see if we get issues from other areas, and iterate then.

Manish please update your PR and let us know when ready.

**Comment by Manish-Giri** [comment]
@raisedadead @ojeytonwilliams I updated the PR.

**Comment by ojeytonwilliams** [comment]
Currently, in production, the code completion is really frustrating on mobile.  If you type `var` it completes to `varvar`, so it's worse than useless.

I think we should disable it on mobile, if possible, or entirely if not.
