### ISSUE TITLE
MongoDB and Mongoose - Install and Set Up Mongoose test case broken

### ISSUE THREAD

**Issue by Shaikot007** [freeCodeCamp/freeCodeCamp#37747]
**Describe your problem and how to reproduce it:**
Test for this challenge is not passing. added mongodb and mongoose with add package button and in package.json dependecy is

```json
"dependencies": {
    "express": "^4.16.4",
    "mongodb": "^3.3.4",
    "mongoose": "^5.7.9"
  },
```

added `MONGO_URI` in .env with url from mongodb atlas.

and in myApp.js added

```js
const mongoose = require('mongoose');
mongoose.connect(process.env.MONGO_URI);
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose

https://geode-wisteria.glitch.me/

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 78.0.3904.97 (Official Build) (64-bit)
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/26341505/68701667-75af6280-05b1-11ea-8743-54e64f1e64b1.png)

**Comment by RandellDawson** [comment]
@Shaikot007 Please use [our forum](https://www.freecodecamp.org/forum) for help with your projects.

**Comment by sohailtanveer01** [comment]
facing same problem
