### ISSUE TITLE
Read-search-ask links are broken

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#37751]
Many of the challenges say something like this...

Remember to use [Read-Search-Ask](http://forum.freecodecamp.org/t/how-to-get-help-when-you-are-stuck/19514) if you get stuck. Try to pair program. Write your own code.

The link there is broken. Many challenges have this problem. Here's the working link:
https://www.freecodecamp.org/forum/t/the-read-search-ask-methodology-for-getting-unstuck/137307

**Comment by Mozar10** [comment]
@moT01 I fixed this with a `grep` and `sed` command that. Will open a PR momentarily.

**Comment by Mozar10** [comment]
Here is the command to recreate 
`grep -rl 'https://forum.freecodecamp.org/t/how-to-get-help-when-you-are-stuck/19514' ./ | xargs sed -i 's@https://forum.freecodecamp.org/t/how-to-get-help-when-you-are-stuck/19514@https://www.freecodecamp.org/forum/t/the-read-search-ask-methodology-for-getting-unstuck/137307@g'`

**Comment by RandellDawson** [comment]
@moT01 @Mozar10 The [original forum topic](https://www.freecodecamp.org/forum/t/how-to-get-help-when-you-are-stuck-coding/19514)  should be used instead because it has more views.

**Comment by Mozar10** [comment]
@RandellDawson updated the PR

**Comment by raisedadead** [comment]
@Mozar10 thanks for the PR. @RandellDawson thanks for pointing to the correct link. Please review and merge.

That said, it's interesting that the redirects did not work. They should have gracefully redirected over to the correct links.
