### ISSUE TITLE
Clicking "Get Message" does nothing on "JSON APIs and Ajax: Access the JSON Data from an API"

### ISSUE THREAD

**Issue by TimFau** [freeCodeCamp/freeCodeCamp#37767]
**Describe the bug**
Instructions say "On the right, click the "Get Message" button to load the freeCodeCamp Cat Photo API JSON into the HTML." But, when you click "Get Message", nothing happens.

**To Reproduce**
1. Go to https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/access-the-json-data-from-an-api
2. Click on "Get Message"

**Expected behavior**
I'm assuming I should see this (as its is on the "[JSON APIs and Ajax: Get JSON with the JavaScript fetch method](https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/get-json-with-the-javascript-fetch-method)" lesson)
![image](https://user-images.githubusercontent.com/7255687/68979924-feeeb100-07cc-11ea-96c9-18d37366d0a4.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version:  78.0.3904.87

**Comment by RandellDawson** [comment]
There is a bug which will be fixed when both PR #37534 and PR #37621 have been merged.

Basically, there are two variables (`req` and `json`) which are not declared and are causing an error and not allowing the JSON response from displaying in the Preview area.  There is another bug which is preventing the error messages from even displaying in the FCC or browser console.

I will leave this issue open for now.  Once the PRs referenced above are merged, this issue will be closed.

FYI - If you want to see the JSON response in the Preview, you can make sure to declare the two variables I mentioned above.

**Comment by TimFau** [comment]
Got it, thanks!
