### ISSUE TITLE
Scrimba video for Use the Conditional Ternary Operator challenges needs to be updated

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#37760]
The scrimba video for [Use the Conditional Ternary Operator](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-the-conditional-ternary-operator) needs to be updated to match the updates made a while back.

**Comment by RandellDawson** [comment]
@beaucarnes Any update on this?

**Comment by LarryHu0217** [comment]
I want to do this kind of update, but I am not sure what accurate need to be updated. Could anyone explain more about that. Thanks.

**Comment by StephenTanksley** [comment]
If there's no movement on creating a new video to update this, I'd be happy to take a crack at it.

**Comment by StephenTanksley** [comment]
> The scrimba video for [Use the Conditional Ternary Operator](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-the-conditional-ternary-operator) needs to be updated to match the updates made a while back.

I checked out the video and it seemed to be factually accurate. Is the video update just needing to match the condition of "Equal" or "Not Equal" like the actual problem is asking for?
