### ISSUE TITLE
news search box magnifying glass needs repositioning

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#37778]
<img width="572" alt="How_to_create_a_music_bot_using_Discord_js" src="https://user-images.githubusercontent.com/985197/69100704-5c7c3b00-0a23-11ea-8e08-b196a4a60c5e.png">

It looks much better on /learn (though it could also be slightly centered vertically).

<img width="604" alt="Learn___freeCodeCamp_org" src="https://user-images.githubusercontent.com/985197/69100672-4b332e80-0a23-11ea-8d22-19893b8292ba.png">

**Comment by ziomecka** [comment]
Could I take it?

**Comment by ojeytonwilliams** [comment]
@ziomecka feel free!  We generally take the first (working) PR that's submitted and you're more than welcome to submit one.  

By the way, I dug into this a little - the problem comes from how rems deal with browser settings https://stackoverflow.com/questions/28718688/rems-rendering-differently-between-chrome-and-firefox, so I'd recommend using another unit for positioning (em, perhaps?) to avoid this problem..

**Comment by ziomecka** [comment]
ok :-)

**Comment by raisedadead** [comment]
Here is the code repository for the news theme if you are interested
https://github.com/freeCodeCamp/news-theme

**Comment by ziomecka** [comment]
I think it can be solved by changing the position of the wrapping div (with the role="search") from 'static' to 'relative'. Then the magnifying glass's position will be calculated versus this div. Thus, the 'left' property of 3rem can be removed, and the 'top' can be changed from 20% to something like: calc(20% + 5px).

However I cannot reproduce this issue in my browsers so I do not feel comfortable with comitting anything :-(

**Comment by ojeytonwilliams** [comment]
> However I cannot reproduce this issue in my browsers so I do not feel comfortable with comitting anything :-(

If you're using Chrome you can go to chrome://settings/fonts?search=font and change your fontsize.  Then take a look at https://www.freecodecamp.org/news. The magnifying glass should have moved.

**Comment by ziomecka** [comment]
Yes, it moved. Thank you :-)
So the commit is ready, however I cannot push branch to the news-theme repo:
'remote: Permission to freeCodeCamp/news-theme.git denied to ziomecka.'

**Comment by raisedadead** [comment]
Looks like you are new to GitHub and Contributing in general, here are some resources you should read up on:

- https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-open-a-pull-request.md

**Comment by ojeytonwilliams** [comment]
@ziomecka You're welcome!

You will not be able to push to that repo directly.  The thing to do is to create a branch in a fork and use that to create the PR.  As well as the link Mrugesh just posted, I'd recommend looking at this [guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md)

If you have any problems, the best thing to do is reach out on [Gitter](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by ziomecka** [comment]
Ok, so I have created the PR.
May I suggest adding the links you have sent me to the CONTRIBUTING.md:
https://github.com/freeCodeCamp/news-theme/blob/master/CONTRIBUTING.md

**Comment by terra9** [comment]
@ojeytonwilliams I am unable to replicate this issue locally, whereas i was able to replicate on the online version.

**Comment by ojeytonwilliams** [comment]
@terra9 stupid question, but did you build a ghost site using the news-theme?  That's where you should see the bug.

**Comment by moT01** [comment]
This looks fixed to me. I'm not sure when or where since there's still an open PR. Can anyone confirm if this is fixed or still an issue?

**Comment by raisedadead** [comment]
Its not aligned yet?

![image](https://user-images.githubusercontent.com/1884376/76383498-11938400-6382-11ea-8f03-e1d98e7b8497.png)

**Comment by moT01** [comment]
It's a lot better than the original screen shot, but looks like it could still use some vertical alignment.

**Comment by Tuuben** [comment]
Is this still an issue? Could I take a look at it in that case. :)

**Comment by ahmadabdolsaheb** [comment]
@Tuuben, yes. please do. :)
