### ISSUE TITLE
Inconsistent behavior in the "Solution" and "Github Link" texboxes of the APIs and Microservices projects 

### ISSUE THREAD

**Issue by jshaolin** [freeCodeCamp/freeCodeCamp#37771]
If I fill the "Solution" textbox only, providing a Glitch project URL, and leave the other one blank, then when I click the "I've completed this challenge" button, it complains about having to fill in the "Github Link" textbox. What I did was to put the same Glitch URL in both textboxes, the "Solution" and the "Github Link", and it worked like a charm. I did that to complete 4 of 5 projects (since the Timestamp Microservice is broken).

![Sin título2](https://user-images.githubusercontent.com/44646385/68999911-f3fa6480-0923-11ea-880a-6958da0cc8ae.png)

![Sin título](https://user-images.githubusercontent.com/44646385/68999894-c2819900-0923-11ea-8a82-46e1ee680ea3.png)

* Browser Name: Google Chrome
* Browser Version: 72.0.3626.81 (Official build) (64 bits)
* Operating System: Windows 10 Pro

**Comment by raisedadead** [comment]
At the minute we do not validate if the links are from GitHub and Glitch. We rely on the honor system for users providing the links to their work.

We can tweak this to at least check the links from Glitch and GitHub. That said, we do not want any in depth validation to avoid complexity.

**Comment by moT01** [comment]
I vote to remove the input for a github link. As far as I know, there is no requirement stated that github must be used. What if someone builds their entire project on glitch like the OP here, or just hosts their code somewhere without wanted to put it on github? Could possibly just make the github link optional as well.

**Comment by PartyLich** [comment]
I'd vote for making the github input optional. I didn't manage to find any link to the submitted urls from my public profile page, but if there was one i'd certainly want it to be able to point it to the github entry. Ideally while also having a testable glitch (or other host) version.

It may also be worth noting the user settings page that _does_ have links to my submissions labels them as Frontend and Backend, which has no clear correlation to the input labelling.
![image](https://user-images.githubusercontent.com/2792750/69105591-c1429000-0a39-11ea-8f8e-88e6d1c621e9.png)

**Comment by raisedadead** [comment]
Okay, lets make the GitHub link optional.
