### ISSUE TITLE
Move to Node LTS 12.x.x

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#37776]
We need to test our current codebase on Node LTS 12.x.x and make changes if necessary. Once done, we bump the version and do the DevOps upgrade.

**Comment by Manish-Giri** [comment]
@raisedadead I'll take this up. Will start by first testing it on LTS 12 and go from there.

**Comment by ojeytonwilliams** [comment]
I just noticed that Docker is already running using the node:lts image which has been upgraded to 12.13.1.  So, anyone using Docker is already testing it!  Also, we should probably pin it at a specific version before future upgrades.

**Comment by raisedadead** [comment]
All our instances are running Node 12. Closing.
