### ISSUE TITLE
outdated instructions

### ISSUE THREAD

**Issue by jefferson2z** [freeCodeCamp/freeCodeCamp#37788]
The page "Introduction to the MongoDB and Mongoose Challenges" says "You should be able to see the green Get Started button on the bottom left of your screen". However there's no such button on MongoDB Atlas. The text should instead guide the student to go to "Database Access" under "Security", and click the green button "Add a new user".

**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by jefferson2z** [comment]
I would like to make a PR for improving this text, however I can't find the page for "Introduction to the MongoDB and Mongoose Challenges" under curriculum/challenges on the repository.

**Comment by ojeytonwilliams** [comment]
Hi @jefferson2z, the introductions are handled a little differently to the challenges.  You can find the one you're looking for in client/src/pages/learn/apis-and-microservices/mongodb-and-mongoose/index.md.

**Comment by moT01** [comment]
Any luck here @jefferson2z?

**Comment by RandellDawson** [comment]
I thought we were going to get rid of the introductions.

**Comment by jefferson2z** [comment]
I'll work on it and send a PR linked to this issue

**Comment by Pallof** [comment]
Has this issue been resolved?

**Comment by moT01** [comment]
Doesn't look like it @Pallof - give it a go if you want 👍
