### ISSUE TITLE
Donate page hour amounts incorrect

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#37786]
At freeCodeCamp's current level of efficiency, every dollar donated to our nonprofit translates to 50 hours worth of learning.

Both the One-time and Annual options have the correct amounts, but for some reason the monthly doesn't have the correct amount:

$50 should be 25,000 hours:
<img width="507" alt="Support_our_nonprofit___freeCodeCamp_org" src="https://user-images.githubusercontent.com/985197/69195229-b3037b00-0af0-11ea-8724-e336882e6001.png">

$35 should be 1,750 hours:
<img width="517" alt="Support_our_nonprofit___freeCodeCamp_org" src="https://user-images.githubusercontent.com/985197/69195161-9f581480-0af0-11ea-824c-bcd83ce29e25.png">

$5 should be 250 hours:
<img width="522" alt="Support_our_nonprofit___freeCodeCamp_org" src="https://user-images.githubusercontent.com/985197/69195134-949d7f80-0af0-11ea-973d-afb878e592be.png">

**Comment by raisedadead** [comment]
The hour is calculated per month? For example $5:  5 * 50 / 12
