### ISSUE TITLE
Cash Register solution in guide fails for floating numbers error

### ISSUE THREAD

**Issue by Ieahleen** [freeCodeCamp/freeCodeCamp#37782]
the solution given in the guide here https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-cash-register/16012
fails in a situation like 
```
const cid = [["PENNY",1], ["NICKEL", 0], ["DIME", 0], ["QUARTER", 1], ["ONE", 1], ["FIVE", 5], ["TEN", 10], ["TWENTY", 20], ["ONE HUNDRED", 0]];
checkCashRegister(3, 3.01, cid);
```

the change due is calculated as 3.01-3, which results in a 0.009999999999999787
this number is too small for the various checks, and no penny is ever given

We need a solution that starts with the conversion to cents, and maybe an explanation, or a source to where one can read about what's going on with the numbers and why it is needed in the guide somewhere

**Comment by ankurprasad711** [comment]
Hi @leahleen I would like to solve this issue. can you assign it to me. thanks

**Comment by Ieahleen** [comment]
@ankurprasad711 no, I can't assign things myself

**Comment by ojeytonwilliams** [comment]
@ankurprasad711 we don't generally assign issues, but you're more than welcome to work on it!  Take a look at the [contributing guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md#how-do-i-get-an-issue-assigned-to-me) if you'd like to see the reasoning.

**Comment by RandellDawson** [comment]
> why it is needed in the guide somewhere

There is no longer a Guide.

**Comment by Ieahleen** [comment]
@RandellDawson there is the guide in the forum where there is a solution, and there are articles and news of disparate topics

**Comment by snigo** [comment]
There is no reason to do double conversion to cents and then back to dollars in this example. You can wrap every operation with something like this:
```
function currencify(amount) {
  return +(+amount).toFixed(2);
}
```

**Comment by gullahoo** [comment]
This apparently has to do with how Javascript's implementation of float.h will somehow read the exponent wrong and mix up its interpretation of the significand - in which case the problem which needs to be fixed lies deep in the roots of your Node.js.   If (and only if) you want more info I will forward a bit more about the barebones of it

**Comment by Sky020** [comment]
I am closing this to _triage_, as the solution in question has been modified, and passes the test conditions.
