### ISSUE TITLE
Certificate issued date is almost invisible...

### ISSUE THREAD

**Issue by AlexOrtizzz** [freeCodeCamp/freeCodeCamp#37794]
...but only if i use direct link.

Bad: https://www.freecodecamp.org/certification/alexortizzz/javascript-algorithms-and-data-structures

Good: click certificate in portfolio (https://www.freecodecamp.org/alexortizzz)

Windows 10, Chrome 78 / Firefox 70

**Comment by ojeytonwilliams** [comment]
Thanks for the report!  However, there is already an issue, https://github.com/freeCodeCamp/freeCodeCamp/issues/37378, that's tracking this, so I'm closing this one as a duplicate.
