### ISSUE TITLE
freeCodeCamp.org's Forums are down? 

### ISSUE THREAD

**Issue by Shaurya-Sarma** [freeCodeCamp/freeCodeCamp#37801]
**Describe the bug**
By trying the post on the forum, it returns an error message, called "Internal Server Error". I am unsure whether it is from my end or everyone is experiencing the same issue as the latest post is 9 hours ago as of 22:00 EST. 

**To Reproduce**
Just try to start a new post or open another one. It results in an error message.

**Comment by raisedadead** [comment]
Duplicate of #37452
