### ISSUE TITLE
Add "Joined freeCodeCamp in [month] of [year]" to profile

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#37817]
We'd like to recognize people's original date of account creation on their profile. This is a nice way of recognizing the many early adopters who joined back before freeCodeCamp was a proven path to a developer job, and who were "taking a chance on us" :)

Even though we don't store a date of account creation, it's possible to get a record creation date using the Mongo ID property.

We're looking for a contributor who's interested in helping add "Joined freeCodeCamp in [month] of [year]" to people's portfolios (shown only when they set their bio to public).

**Comment by Manish-Giri** [comment]
I'd like to give this a shot. Sounds like an interesting challenge.

**Comment by hajdarevicedin** [comment]
I vouch for this as well

**Comment by thecodingaviator** [comment]
I guess since @Manish-Giri asked for it first, he can have a go.

**Comment by QuincyLarson** [comment]
@Manish-Giri Did you ever get a chance to start working on this? This is still something we'd like to add to the profile pages. This little code tweak will make a big difference to millions of campers.

**Comment by Manish-Giri** [comment]
@QuincyLarson I did, I had also spoken briefly with Mrugesh on the changes I intend to make for this, but I had to step away for a few weeks for interview prep. I'll get back on this right away, sorry for the delay.
