### ISSUE TITLE
External links in coding challenges

### ISSUE THREAD

**Issue by Kbarias** [freeCodeCamp/freeCodeCamp#37827]
**Describe your problem and how to reproduce it:**
In a recent pull request (#37802) it was brought to attention that there are external links in coding challenges such as [this one](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/increment-a-number-with-javascript.english.md). Both @RandellDawson and @moT01 thought that it would be a good idea to remove any MDN links found in coding challenges.
I am creating this issue to discuss removing these links and where to possibly move them (such as to the corresponding forum topics, as Randell suggested).

**Comment by moT01** [comment]
This applies to all links, and not just MDN links.

I'm wondering if we should remove the `read-search-ask` links in the challenges as well...
<img width="830" alt="Screen Shot 2019-11-26 at 11 12 39 AM" src="https://user-images.githubusercontent.com/20648924/69656265-d9b83900-103d-11ea-9fda-a10d9c71f407.png">
Most of the algorithms have that link at the bottom of the description or instructions as well as other challenges I'm sure. The link is also shown when you click the `ask for help` button. Seems like just having it in the help modal would be good enough.

**Comment by RandellDawson** [comment]
@moT01 I like your idea.  @raisedadead I know another PR was recently merged which fixed this link, but since the Read Search and Ask link **is** already in the help modal, maybe we can remove these.

**Comment by raisedadead** [comment]
I think there is not much to lose in having the R-S-A links in challenges. The modal just double checks with the users that if they used it or not. 

I would defer the need for MDN links in challenges to @scissorsneedfoodtoo if we have forum topics already.

**Comment by moT01** [comment]
We could probably make it consistent. The RSA link is in some of the challenges and not others. Seems like we could either add it in all of them, or remove it from all of them.

**Comment by RandellDawson** [comment]
@raisedadead I agree with Tom here.  I think they should all have the R-S-A links (which I do not prefer) or none at all.

**Comment by raisedadead** [comment]
Alright lets clean them up from the challenges.

**Comment by LarryHu0217** [comment]
I check on many of challenges which I think this issue is fixed in previous version. Should we close this bug?

**Comment by Sky020** [comment]
Pinging this for _triage_ @scissorsneedfoodtoo : There are still lessons with links to Mozilla docs, and I cannot find equivalent forum guide posts. So, are we going to leave the links as is?

Closest guide post I found to the first mentioned lesson is [here](https://forum.freecodecamp.org/t/java-basic-operations-explained-with-examples/16714), but I am not even sure why such a guide post exists as it is for Java...

**Comment by RandellDawson** [comment]
@Sky020 You might try to search https://freecodecamp.org/news to see if you can find a good article there.  Many of the most popular Guide Topics were transported to a corresponding news article.

Currently, there are only 4 challenges with MDN links:

* [Increment a Number with JavaScript](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/increment-a-number-with-javascript) - The MDN information does not give any further incite to using the `++` operator, so I think we just remove this link all together.  Also, it would not make sense to create an entire news article for this, though we could create a Guide topic on the forum I suppose and make it a wiki.

* [Record Collection](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/record-collection) - The MDN link relates to the `push` method which is already introduced way before this challenge, so I think we can just delete this link.

* [Change Text Inside an Element Using jQuery]() - The MDN link here (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em) actually has some merit.  I think we could either create a news article or a forum Guide topic with similar information and examples and link to it instead.

* [Use Assert.isOK and Assert.isNotOK](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-and-testing-with-chai/use-assert-isok-and-assert-isnotok) - The Truthy and Falsy MDN links could be replaced by a link to the [Falsy Bouncer](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/falsy-bouncer) challenge or a news or forum article covering the information in more detail.

The above is just my thoughts on the links.  If at all possible, I think the links to MDN should be removed.

**Comment by Sky020** [comment]
@RandellDawson , That is excellent! In this case, I suggest because other members were in agreement in the linked PR, we open this to _help wanted_ (or _first-timers_), and do as you have suggested above.

One point on my side:
> Record Collection - The MDN link relates to the push method which is already introduced way before this challenge, so I think we can just delete this link.

Instead of removing the link, I suggest it be changed to direct to the challenge that introduces the `push` method.

So, if you agree, Randell, I leave it to you to open this to _first-timers_ or otherwise.

**Comment by RandellDawson** [comment]
> Instead of removing the link, I suggest it be changed to direct to the challenge that introduces the push method.

So, if you agree, Randell, I leave it to you to open this to first-timers or otherwise.

It is funny you say that, because I actually meant to put that as an option.  Thanks for noticing!

Go ahead and label this issue however you see fit.

**Comment by scissorsneedfoodtoo** [comment]
Wow, I totally missed this issue. Thanks for finding all the current challenges that still have those links, and for finding News equivalents @RandellDawson. Also, thanks for the ping @Sky020.

@brignano created #39337 recently. I'll see if I can suggest some News articles there.
