### ISSUE TITLE
Inconsistent code in Data Structures

### ISSUE THREAD

**Issue by UziTech** [freeCodeCamp/freeCodeCamp#37820]
**Describe your problem and how to reproduce it:**

Code in Data Structure challanges is inconsistent.

I believe we should use es6 class syntax across all Data Structures challenges since they are less verbose and emphasize the code in each method rather than the methods themselves.

I started a PR (#37819) to update the code.

**Add a Link to the page with the problem:**

[Create a Set Class](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/create-a-set-class) uses an es6 class
[Perform an Intersection on Two Sets of Data](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/perform-an-intersection-on-two-sets-of-data) uses a function object

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 78
* Operating System: Windows 10

**Comment by Manish-Giri** [comment]
I don't know if this is a good idea. Yes, using `class` based syntax is less verbose, but keep in mind, this section is mostly on coding interview prep, and a lot of JS-based coding interviews actually require/prefer you using the older `function` based syntax, to demonstrate you know how things (prototypal inheritance, first-class functions, etc) work under the hood.

**Comment by UziTech** [comment]
Maybe there should be lessons on `(prototypal inheritance, first-class functions, etc)` but each challenge should teach it's specific lesson (in this case implementing data structures) with as little distraction as possible, and I believe the easiest way to reduce the distraction is to use ES6 classes.

If we do want to use function objects instead, we should at least keep it consistent.

**Comment by RandellDawson** [comment]
@UziTech Unfortunately, we are no longer adding new lessons to the existing curriculum.  We can modify existing lessons, but all new lessons are to be incorporated into the [new project-based curriculum](https://github.com/freeCodeCamp/CurriculumExpansion) which will replace most of the current curriculum (excluding the `Coding Interview Prep` section).

>If we do want to use function objects instead, we should at least keep it consistent.

I do agree with this, but not necessarily that we should use the `class` syntax.

**Comment by UziTech** [comment]
@RandellDawson Why do you think function syntax would be better in teaching data structures than class syntax?

These are not lessons in JavaScript, they are lessons in common data structures. They just happen to be using JavaScript to teach the lessons.

**Comment by Manish-Giri** [comment]
> Data Structures doesn't seem like the right place to teach `(prototypal inheritance, first-class functions, etc)`

Technically, we're not teaching these concepts in the Data Structures section. That's already been done before. The challenges just build over these concepts. 

And, you could also argue that Data Structures isn't the right place to teach `class` and other ES6 based syntax. We have an entire section in the curriculum just for ES6. 

Ultimately, `class` is just syntactic sugar over `function` based syntax, it's still the same inheritance paradigm, just less verbose.

**Comment by RandellDawson** [comment]
> Ultimately, `class` is just syntactic sugar over `function` based syntax, it's still the same inheritance paradigm, just less verbose.

There are some differences.  The `class` syntax ends up keeping the methods defined in the prototype vs. within each instance.  That is what I meant above by the `collection` variable being "local/private" to the function.  With the class version, you cab technically directly manipulate the collection array outside the class by assigning a new value to the collection property.

I am curious as to what @ojeytonwilliams, @thecodingaviator, and @moT01 think about this proposed change.  I personally think we should not change the function syntax to using class in the challenge seed.  If a user wants to use it, then they can still do it that way.

**Comment by UziTech** [comment]
> If a user wants to use it, then they can still do it that way.

Actually the test framework on some challenges doesn't work with classes as is.

---

I'm fine with keeping function syntax or class syntax, I just think it should be consistent.

I do believe that `add() {` is much easier to read than `this.add = function() {` and it is more similar to syntax in other programming languages.

There are many other inconsistencies as well:

 * Putting instructions under the "Instructions" header. 
   [![image](https://user-images.githubusercontent.com/97994/69598492-1862da80-0fcf-11ea-922f-505e950cbfb4.png)](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-coding-interview-prep/data-structures/remove-an-element-from-a-max-heap.english.md)
 * Wrapping method names in `<code>` tags.
 * Using `size` and `length` interchangeably in many challenge descriptions.
 * and probably many more that I haven't found yet...

**Comment by RandellDawson** [comment]
> Actually the test framework on some challenges doesn't work with classes as is.

There is an [outstanding PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/37648) that shouldl address this issue.

**Comment by moT01** [comment]
Yes, there are inconsistencies all over the place @UziTech - I would try not to tackle too many of them in one PR to make it easier to review. If you're looking for something to do, I'm sure we can find something for ya. Those `code`, `blockquote` and other tags can be changed to use markdown (backticks) syntax - and, you're right, the instructions could probably be moved to that section of the file. 

I don't know what to think here - I, personally, prefer the `function` syntax because I have used it more. After skimming through that section, it looks like more of the challenges are using the `function` version, so it would be easier to change the few others to align with that. But I'm not against either version really. In this case, it might actually be beneficial to have some inconsistencies to get people to recognize different ways of doing the same/similar thing. 

> Unfortunately, we are no longer adding new lessons to the existing curriculum.

I would not rule out adding stuff to the coding interview prep if it's going to stick around when the projects come out - I would prefer that some of the current curriculum gets moved there when it does, mainly the algorithms - although this is a separate issue

**Comment by UziTech** [comment]
I definitely can't speak for all users, but I went to the Data Structures section to learn Data Structures, not prototypal inheritance or class syntax. I don't think we should make the decision one way or another based on if users could learn those things in Data Structures. I think the decision should be made based on which is better to teach Data Structures.

My argument for es6 classes boils down to a few points:
* they are easier to read
* they provide less distraction from actually learning the Data Structures
* they are more similar syntax to other OOP languages
* they seem to be the best practice
  * Hearsay: In a recent interview at Google I was specifically asked to use classes

**Comment by UziTech** [comment]
> I would try not to tackle too many of them in one PR

I could make each challenge a separate PR if that would be easier to review. Or maybe each data structure group (i.e. set, map, linked lists, etc. in separate PRs)

>  it might actually be beneficial to have some inconsistencies to get people to recognize different ways of doing the same/similar thing.

I believe that should be part of another lesson, not in Data Structures.

**Comment by RandellDawson** [comment]
@UziTech We have yet to concluded if any PR is even needed at this point.  That is why I told you to create an issue first when you had only made 1-2 commits.   When making larger sweeping changes, we like to get consensus first, so users does not waste their time on something deemed not needed.

**Comment by UziTech** [comment]
@RandellDawson I understand. The draft PR I created was more to save my journey through the code. If I have to scrap it I will still have learned a lot about the code base and hopefully be able to contribute more in the future. I owe a lot to Free Code Camp and hope to help more developers in the future.

**Comment by RandellDawson** [comment]
Don't get me wrong.  I like the idea of changing the `var` to `let` or `const`, but I think it would be best to break it up into PRs with very specific changes.  That makes the review process much easier.  In your PR you are changing tests (that were not originally broken) and all kinds of things. We try to stay away from changes tests unless something is broken (fails with valid code or passed with invalid code).

If you created a PR with many files but only changed the variable declarations, that is much easier and would result in a faster review.  I say this from experience of reviewing many PRs which had over 300 files with all kinds of changes.  It took almost 2 weeks for me to review such PRs.  No one else wanted to do it.

**Comment by Sky020** [comment]
Just going through: Are we leaving this open as _proof of discussion_, and planned to be closed after the release of v7?

**Comment by Sky020** [comment]
Closing, as this is no longer an issue. Both mentioned challenges use `class` syntax from the seed.
