### ISSUE TITLE
Golf Code challenge in Basic Javascript curriculum does not support "Double Eagles" 

### ISSUE THREAD

**Issue by mike-crane** [freeCodeCamp/freeCodeCamp#37824]
Instances where (strokes <= par - 3) are not accounted for in the Golf Code challenge. Currently, golfScore(5, 2) & golfScore(4, 2) both return "Eagle" rather than "Double Eagle" "Eagle". 

**Correct Solution**
```
var names = ["Hole-in-one!", "Double Eagle", "Eagle", "Birdie", "Par", "Bogey", "Double Bogey", "Go Home!"];

function golfScore(par, strokes) {
  if (strokes == 1) {
    return names[0];
  } else if (strokes <= par - 3) {
    return names[1];
  } else if (strokes == par - 2) {
    return names[2];
  } else if (strokes == par - 1) {
    return names[3];
  } else if (strokes == par) {
    return names[4];
  } else if (strokes == par + 1) {
    return names[5];
  } else if (strokes == par + 2) {
    return names[6];
  } else if (strokes >= par + 3) {
    return names[7];
  }
}

console.log(golfScore(3, 1)); // Hole-in-one!
console.log(golfScore(5, 2)); // Double Eagle
console.log(golfScore(5, 3)); // Eagle
```   

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/golf-code
![Screen Shot 2019-11-25 at 10 23 03 AM](https://user-images.githubusercontent.com/16603571/69553128-9c847600-0f6d-11ea-8039-d95bc2af41fd.png)
![Screen Shot 2019-11-25 at 10 23 44 AM](https://user-images.githubusercontent.com/16603571/69554215-72cc4e80-0f6f-11ea-8044-77abf765ccbf.png)

**Comment by moT01** [comment]
This is accurate, 3 strokes better than par is a `double eagle`. But I'm wondering if it's worth changing this around to cover that case. The challenge, video hint, and forum hints would all need to be changed. The purpose of the challenge is clearly not to teach the scoring system of golf, but to get users to write some logic. And that will be accomplished either way.

**Comment by thecodingaviator** [comment]
I guess it's fine how it is now. The challenge is achieving its objective so I guess we'll just leave it the way it is.
