### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by hjs653** [freeCodeCamp/freeCodeCamp#37828]
When going through the lessons on the website, there is no tracker on where you are.  So my suggestion would be a marker that indicates how many lessons a person has completed out of the number that are left to complete?

**Comment by RandellDawson** [comment]
If you are signed in, it shows you how many challenges you have completed in each section. 

I am closing this issue in favor of issue #18062 which already has a PR in progress to add something like you are wanting.  Feel free to comment on that issue.
