### ISSUE TITLE
Setting env in a right way on cloud9

### ISSUE THREAD

**Issue by harshitanand** [FreeCodeCamp/FreeCodeCamp#3782]
just start a new workspace and in the terminal check node version using "node -v"
after that go through following steps for successful env setup

source ../.nvm/nvm.sh
nvm install v0.12.7
nvm use v0.12.7

after that use following command

echo "export NODE_PATH=$NODE_PATH:/home/ubuntu/.nvm/v0.12.7/lib/node_modules" >> ~/.bashrc && source ~/.bashrc

then type

rm -rf * && npm install -g yo grunt grunt-cli generator-angular-fullstack && yo angular-fullstack

it will give you an error try following again

yo angular-fullstack

once it is successful try following comands

npm install -g bower
bower install
npm install

then install mongodb using

mkdir data && echo 'mongod --bind_ip=$IP --dbpath=data --nojournal --rest "$@"' > mongod && chmod a+x mongod && ./mongod

then try running following in another terminal

grunt serve

I have tested above method many times and it works

**Comment by awesomeaniruddh** [comment]
Please open a PR for this. Closing this as not an issue.
