### ISSUE TITLE
Create a Hash Table challenge tests

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#37831]
While reviewing [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/37582), I noticed that the [Create a Hash Table challenge](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/create-a-hash-table) uses some methods that the user is supposed to create for the tests. Specifically, it asks you to create `add`, `remove`, and `lookup` methods - but the tests to check if `add` and `remove` are correct use `lookup`. So if your `lookup` method is wrong, the tests for `add` and `remove` will fail even if they are correct.

**Comment by Amagon96** [comment]
Hi! Can I work on this?

**Comment by RandellDawson** [comment]
I think a possible solution for this is for testing the add and remove methods, you temporarily add in a working lookup method for the tests to use and then remove it so the other tests still use the user's lookup method.

@Amagon96 Go for it.

**Comment by Amagon96** [comment]
Thank you!
