### ISSUE TITLE
Typo in challenge

### ISSUE THREAD

**Issue by suhussai** [FreeCodeCamp/FreeCodeCamp#3783]
Challenge [Waypoint: Use Bracket Notation to Find the Nth Character in a String](http://freecodecamp.com/challenges/waypoint-use-bracket-notation-to-find-the-nth-character-in-a-string) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var firstName = "Ada";

var secondLetterOfFirstName = firstName[1];

var lastName = "Lovelace";

var thirdLetterOfLastName = lastName;


// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
// You'll learn about functions soon.
(function(v){return v;})(thirdLetterOfLastName);

```

There is a space missing in the following text:
```
You can also use bracket Notationto get the character at other positions within a string.
```

**Comment by awesomeaniruddh** [comment]
@
