### ISSUE TITLE
Typo in React Native Lesson

### ISSUE THREAD

**Issue by kengustafson** [freeCodeCamp/freeCodeCamp#37833]
#### Issue description
Typo in React Native lesson found at:
https://guide.freecodecamp.org/react-native/props

#### Steps to reproduce the issue
1.  Load webpage
2.  Inspect second code block (...functional components)
3.  Line 4 reads  <Text>{props.title}</Text>

#### What's the expected result?
Line 4 should read  <Text>{props.text}</Text>
As the header component passes a text prop

#### What's the actual result?
Alternatively, the Header component prop could be changed to 'title' on line 12
-

**Comment by thecodingaviator** [comment]
We've stopped using the guide and all articles under it.

I'm tagging @raisedadead for more info on this

**Comment by raisedadead** [comment]
Hi @QuincyLarson we are still waiting on #37125 which is further dependent on the action item

Regular articles migration from guide.frecodecamp.org to forum (tasked to you)

Can you please confirm further.
