### ISSUE TITLE
can't see the close button on the popup modals

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#37834]
When in a challenge, any of modals that popup (completion, ask for help, etc..), have a little close button at the top right that has recently become very hard to see...
![Screen Shot 2019-11-25 at 12 52 50 PM](https://user-images.githubusercontent.com/20648924/69639399-0d856580-1022-11ea-8f15-922a8299bf26.png)

**Comment by ojeytonwilliams** [comment]
Also, when you hover over it, it gets obscured by the hover effect:
![image](https://user-images.githubusercontent.com/15801806/69640073-067c4880-105e-11ea-80b8-01530d5cda51.png)

**Comment by moT01** [comment]
Seems like there's an opacity issue...
<img width="698" alt="Screen Shot 2019-11-26 at 8 11 42 AM" src="https://user-images.githubusercontent.com/20648924/69641054-1c214c00-1025-11ea-846d-0050e8b57476.png">
Removing that 1% opacity makes it look like it did before, but I can't pinpoint where it's coming from in the code.

**Comment by raisedadead** [comment]
Production or local?

**Comment by ojeytonwilliams** [comment]
The hover effect is visible in production and they are also a little hard to see.

**Comment by raisedadead** [comment]
@ahmadabdolsaheb please investigate.

**Comment by moT01** [comment]
Just a little table for reference...

| | Production | Master |
|---:|:---:|:---:|
| Chrome | <img width="36" alt="Screen Shot 2019-11-27 at 12 36 58 PM" src="https://user-images.githubusercontent.com/20648924/69750593-b7dcb600-1112-11ea-980d-d3a8a9448c60.png"> | <img width="38" alt="Screen Shot 2019-11-27 at 12 38 33 PM" src="https://user-images.githubusercontent.com/20648924/69750650-e22e7380-1112-11ea-829e-efa27d778a4c.png"> |
| Firefox | <img width="36" alt="Screen Shot 2019-11-27 at 12 36 58 PM" src="https://user-images.githubusercontent.com/20648924/69750593-b7dcb600-1112-11ea-980d-d3a8a9448c60.png"> | <img width="38" alt="Screen Shot 2019-11-27 at 12 38 33 PM" src="https://user-images.githubusercontent.com/20648924/69750650-e22e7380-1112-11ea-829e-efa27d778a4c.png"> |
| Safari | <img width="57" alt="Screen Shot 2019-11-27 at 12 42 07 PM" src="https://user-images.githubusercontent.com/20648924/69750882-74367c00-1113-11ea-9a2c-beabcefded5c.png"> | <img width="57" alt="Screen Shot 2019-11-27 at 12 42 07 PM" src="https://user-images.githubusercontent.com/20648924/69750882-74367c00-1113-11ea-9a2c-beabcefded5c.png"> |

**Comment by raisedadead** [comment]
Thanks for the confirmation. The latest master is no .dev if you want to confirm this issue is fixed. If yes, I will proceed with the deployment to .org

**Comment by raisedadead** [comment]
I have pushed further to production and can confirm that the issue is reproducible on both staging and production applications.

**Comment by raisedadead** [comment]
@ahmadabdolsaheb I have bumped this to crit path.
