### ISSUE TITLE
Decrease the Opacity of an Element - Tests won't pass on Safari after removing backticks

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/freeCodeCamp#37856]
**Describe your problem and how to reproduce it:**

Noticed the issue in [this forum post](https://www.freecodecamp.org/forum/t/will-not-pass-test-but-code-is-typed-in-identical-to-video/329446). User had backticks around their code originally - 
```css
 `opacity: 0.7;`
```
but even after I removed them, the tests won't pass on Safari. 

![Screen Shot 2019-11-29 at 11 44 42 PM](https://user-images.githubusercontent.com/11348778/69895702-14062c80-1303-11ea-866c-02ded88f4c2b.png)

It works on Chrome though.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/decrease-the-opacity-of-an-element

**Tell us about your browser and operating system:**
* Browser Name: Safari 
* Browser Version: 13.0.3
* Operating System: macOS Catalina

**Comment by thecodingaviator** [comment]
@Manish-Giri could you please log and check what the opacity of the element is returning in the dev console?

**Comment by RandellDawson** [comment]
@Manish-Giri @thecodingaviator @ojeytonwilliams and I have already discussed this issue and concluded the differences in the accuracy of the getComputedValue method across browsers was causing too much trouble, so I created #37838 to deal with it once and for all (using regex).  Can you both review and approve if everything looks good.
