### ISSUE TITLE
css style issue with certifications.

### ISSUE THREAD

**Issue by ghanhass** [freeCodeCamp/freeCodeCamp#37852]
Hello everybody.

I noticed this issue in freeCodeCamp certifications.

When opening up the web page of your certification from our main freeCodeCamp's platform, it looks fine, but when I refer to your certification from e.g Linkedin, the web-page's body contains a 'light-palette' class that comes with css variables applying colors to different elements in the certification's web page, among them the <strong> element containing the issue date of the certification that comes with a hardly-readable text (highlighted with a red closed box) as seen in the following webpage and inspector  screenshots:
![alt text](https://i.imgur.com/aAkzUYN.png)
-----------------------------------------
![alt text](https://i.imgur.com/8Qw9pbT.png)
Anyway the removal of that class at whole made the certification look back the same as when accessed from within our freeCodeCamp platform.

**Comment by jcordoba95** [comment]
If there is no one else working on this, I would like to work in this :)

**Comment by thecodingaviator** [comment]
Thanks for opening this issue @ghanhass . This is already being tracked in #37378
