### ISSUE TITLE
Timeline does not appear for public portfolio

### ISSUE THREAD

**Issue by explunit** [freeCodeCamp/freeCodeCamp#37855]
**Describe the bug**
Timeline can be marked as public in the account settings, but it does not appear for public viewers.

**To Reproduce**
1. Create an account
1. Complete at least one challenge
1. Go to [settings](https://www.freecodecamp.org/settings) and change the "My profile" and the "My timeline" settings to public
1. Click on "Show me my public portfolio"
1. Copy the URL and open in a new incognito window 

**Expected behavior**
I expected to see the timeline in both the logged-in user's browser and in the public view (the incognito window)

**Screenshots**

![image](https://user-images.githubusercontent.com/2872623/69894180-47888d00-12ea-11ea-9e00-33ca96d4da2c.png)

logged-in user:
![image](https://user-images.githubusercontent.com/2872623/69894183-4e170480-12ea-11ea-8762-41bd8adecf38.png)

incognito window:
![image](https://user-images.githubusercontent.com/2872623/69894185-52dbb880-12ea-11ea-9537-c340370a7363.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome & Firefox
 - Version: latest stable

**Comment by thecodingaviator** [comment]
@explunit please share a link to your profile

**Comment by explunit** [comment]
@thecodingaviator  here it is: https://www.freecodecamp.org/uuqwernoasdfo

**Comment by thecodingaviator** [comment]
cc: @ahmadabdolsaheb

**Comment by moT01** [comment]
I see the time line showing up on your portfolio @explunit, but it says "no challenges have been completed yet" - have you completed some of them?

**Comment by explunit** [comment]
@moT01 yes, see original screenshots

**Comment by explunit** [comment]
The bug appears to be that the Timeline is actually controlled by the setting for Certifications.

**Comment by raisedadead** [comment]
We need help investigating, fixing and adding tests for this use case. Thanks for your repost @explunit
