### ISSUE TITLE
Environment setup issues on Windows

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/freeCodeCamp#37865]
I was trying to setup the local environment on my Windows machine, and ran into issues with both the Docker and local setup.

I'm posting here for better reachability, maybe someone else has faced such similar errors and can help out. 

Error for docker setup -

```shell
PS C:\Users\Manish\Documents\Development\Github\FCC\FreeCodeCamp> npm run docker:install

> @freecodecamp/freecodecamp@0.0.1 docker:install C:\Users\Manish\Documents\Development\Github\FCC\FreeCodeCamp
> docker-compose run -u root --rm freecodecamp bash patch_npm_and_install.sh

Starting freecodecamp_db_1 ... done                                                                                     Starting freecodecamp_mailhog_1 ... done                                                                                patching file /usr/local/lib/node_modules/npm/node_modules/libcipm/index.js
npm WARN prepare removing existing node_modules/ before installation

> fsevents@1.2.9 install /app/node_modules/fsevents
> node install


> husky@1.3.1 install /app/node_modules/husky
> node husky install

husky > setting up git hooks
husky > done

> @freecodecamp/freecodecamp@0.0.1 postinstall /app
> npm run bootstrap


> @freecodecamp/freecodecamp@0.0.1 bootstrap /app
> lerna bootstrap --ci

lerna notice cli v3.16.4
lerna info versioning independent
lerna info ci enabled
lerna info Bootstrapping 10 packages
lerna info Installing external dependencies
lerna ERR! npm ci exited 240 in '@freecodecamp/curriculum'
lerna ERR! npm ci stderr:
npm WARN prepare removing existing node_modules/ before installation
npm ERR! path /app/curriculum/node_modules
npm ERR! code EBUSY
npm ERR! errno -16
npm ERR! syscall rmdir
npm ERR! EBUSY: resource busy or locked, rmdir '/app/curriculum/node_modules'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-12-03T02_12_29_891Z-debug.log

lerna ERR! npm ci exited 240 in '@freecodecamp/curriculum'
npm ERR! code ELIFECYCLE
npm ERR! errno 240
npm ERR! @freecodecamp/freecodecamp@0.0.1 bootstrap: `lerna bootstrap --ci`
npm ERR! Exit status 240
npm ERR!
npm ERR! Failed at the @freecodecamp/freecodecamp@0.0.1 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-12-03T02_12_30_167Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 240
npm ERR! @freecodecamp/freecodecamp@0.0.1 postinstall: `npm run bootstrap`
npm ERR! Exit status 240
npm ERR!
npm ERR! Failed at the @freecodecamp/freecodecamp@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-12-03T02_12_30_555Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 240
npm ERR! @freecodecamp/freecodecamp@0.0.1 docker:install: `docker-compose run -u root --rm freecodecamp bash patch_npm_and_install.sh`
npm ERR! Exit status 240
npm ERR!
npm ERR! Failed at the @freecodecamp/freecodecamp@0.0.1 docker:install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Manish\AppData\Roaming\npm-cache\_logs\2019-12-03T02_10_41_145Z-debug.log
```

Error with local setup -
```shell
PS C:\Users\Manish\Documents\Development\Github\FCC\FreeCodeCamp> npm ci
npm WARN prepare removing existing node_modules/ before installation

> fsevents@1.2.9 install C:\Users\Manish\Documents\Development\Github\FCC\FreeCodeCamp\node_modules\fsevents
> node install


> husky@1.3.1 install C:\Users\Manish\Documents\Development\Github\FCC\FreeCodeCamp\node_modules\husky
> node husky install

husky > setting up git hooks
husky > done

> @freecodecamp/freecodecamp@0.0.1 postinstall C:\Users\Manish\Documents\Development\Github\FCC\FreeCodeCamp
> npm run bootstrap


> @freecodecamp/freecodecamp@0.0.1 bootstrap C:\Users\Manish\Documents\Development\Github\FCC\FreeCodeCamp
> lerna bootstrap --ci

lerna notice cli v3.16.4
lerna info versioning independent
lerna info ci enabled
lerna info Bootstrapping 10 packages
lerna info Installing external dependencies
lerna ERR! npm ci exited 4294963248 in '@freecodecamp/client'
lerna ERR! npm ci stderr:
npm WARN prepare removing existing node_modules/ before installation
npm WARN tarball tarball data for monaco-editor@0.18.1 (sha512-fmL+RFZ2Hrezy+X/5ZczQW51LUmvzfcqOurnkCIRFTyjdVjzR7JvENzI6+VKBJzJdPh6EYL4RoWl92b2Hrk9fw==) seems to be corrupted. Trying one more time.
npm ERR! code EPERM
npm ERR! syscall unlink
npm ERR! path C:\Users\Manish\Documents\Development\Github\FCC\FreeCodeCamp\client\node_modules\monaco-editor\esm\vs\language\typescript\lib\typescriptServices.js
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\Manish\Documents\Development\Github\FCC\FreeCodeCamp\client\node_modules\monaco-editor\esm\vs\language\typescript\lib\typescriptServices.js'
npm ERR!  [OperationalError: EPERM: operation not permitted, unlink 'C:\Users\Manish\Documents\Development\Github\FCC\FreeCodeCamp\client\node_modules\monaco-editor\esm\vs\language\typescript\lib\typescriptServices.js'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, unlink 'C:\Users\Manish\Documents\Development\Github\FCC\FreeCodeCamp\client\node_modules\monaco-editor\esm\vs\language\typescript\lib\typescriptServices.js'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'unlink',
npm ERR!     path: 'C:\\Users\\Manish\\Documents\\Development\\Github\\FCC\\FreeCodeCamp\\client\\node_modules\\monaco-editor\\esm\\vs\\language\\typescript\\lib\\typescriptServices.js'
npm ERR!   },
npm ERR!   stack: "Error: EPERM: operation not permitted, unlink 'C:\\Users\\Manish\\Documents\\Development\\Github\\FCC\\FreeCodeCamp\\client\\node_modules\\monaco-editor\\esm\\vs\\language\\typescript\\lib\\typescriptServices.js'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\Manish\\Documents\\Development\\Github\\FCC\\FreeCodeCamp\\client\\node_modules\\monaco-editor\\esm\\vs\\language\\typescript\\lib\\typescriptServices.js'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Manish\AppData\Roaming\npm-cache\_logs\2019-12-03T03_44_09_184Z-debug.log

lerna ERR! npm ci exited 4294963248 in '@freecodecamp/client'
npm ERR! code ELIFECYCLE
npm ERR! errno 4294963248
npm ERR! @freecodecamp/freecodecamp@0.0.1 bootstrap: `lerna bootstrap --ci`
npm ERR! Exit status 4294963248
npm ERR!
npm ERR! Failed at the @freecodecamp/freecodecamp@0.0.1 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Manish\AppData\Roaming\npm-cache\_logs\2019-12-03T03_44_09_970Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 4294963248
npm ERR! @freecodecamp/freecodecamp@0.0.1 postinstall: `npm run bootstrap`
npm ERR! Exit status 4294963248
npm ERR!
npm ERR! Failed at the @freecodecamp/freecodecamp@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Manish\AppData\Roaming\npm-cache\_logs\2019-12-03T03_44_10_368Z-debug.log
```

A few facts about the installation -

1. I ran the above commands in Powershell as administrator.
2. I don't have any antivirus which could potentially be blocking these operations. 
3. My node version is the current LTS version (`12.13.1`), I can't downgrade to v10 because I need the LTS for running some other Mozilla projects. And even if the LTS version is the reason (which it shouldn't be), it could give some insight into #37776 which I'll start working on shortly.

Also, I just setup the environment (using docker) a few days back on another machine (mac OS), and that worked fine, so this issue is device-specific.

**Comment by ojeytonwilliams** [comment]
For docker, it sounds like an npm issue, rather than node.  Specifically how it clears out existing node_modules before installation.  I assume that lerna is locking those directories, so npm isn't allowed to remove them.

Anyway, if you look at `/usr/local/lib/node_modules/npm/node_modules/libcipm/index.js` in either the client or server containers you should find:

```js
      .then(stat => {
        stat && this.log.warn(
          'prepare', 'removing existing node_modules/ before installation'
        )
        return BB.join(
          this.checkLock(),
          stat && rimraf(path.join(this.prefix, 'node_modules/*'))
        )
```

inside `prepare()`.  If not, that's probably the culprit.

Locally it could be the same problem, I'm not sure.  Have you tried running it as administrator just to check?

**Comment by Manish-Giri** [comment]
Yes, I executed these commands in Powershell as an administrator. I'll try again using a different shell.

**Comment by ojeytonwilliams** [comment]
It's probably something to do with `libcipm`, then. You might need to find out what version of npm you have installed in both cases.  It *should* include the above code, but it sounds like it isn't.

I'll try and install docker on my Windows partition and see if I run into the same issues (Linux, like Mac is working fine).

**Comment by Manish-Giri** [comment]
So, I did some checking. My local `npm` version is `6.12.1`, which is what ships with Node LTS `12.13.1`. 

However for docker, while ` npm run docker:install` was running, I was able to get into the ` freecodecamp_freecodecamp_run_45061e72436b` container (which runs from the `node:lts` image), and looks like the npm version is `6.9.0` (probably because the node version is `10.16.3`).

Screenshot -

![e3](https://user-images.githubusercontent.com/11348778/70057151-a67c2980-15aa-11ea-893e-53111194963f.png)

I managed to get the contents of `libcipm/index.js` before the container exited, and it looks like the code you mentioned is indeed there -

https://gist.github.com/Manish-Giri/57da44bdedd50b46fb3f4fa140e096a7#file-index-js-L153-L160

```js
      .then(stat => {
        stat && this.log.warn(
          'prepare', 'removing existing node_modules/ before installation'
        )
        return BB.join(
          this.checkLock(),
          stat && rimraf(path.join(this.prefix, 'node_modules/*'))
        )
      }).
```

**Comment by ojeytonwilliams** [comment]
It's weird that the docker image has node 10.16.3, because [node:lts](https://hub.docker.com/_/node) is currently pointing to [12.13.1](https://github.com/nodejs/docker-node/blob/4f49f67ebd8d577dd7c97dabf5df69e6d947406c/12/stretch/Dockerfile).  Any clue why docker isn't getting the latest lts?

Regardless, it seems like `libcipm` has the relevant code.  So, it seems like `rimraf` is trying to delete the directory, despite being told only to hit the contents.  I'm really not sure why that would happen (or if that's actually what's going on).  I'll report back if I find anything!

**Comment by Manish-Giri** [comment]
@ojeytonwilliams Thank You! I'll dig deeper and try to figure out why docker is still using node v10.

**Comment by ojeytonwilliams** [comment]
I can confirm the local installation bug.  I get exactly the same error

>tarball data for monaco-editor@0.18.1 (sha512-fmL+RFZ2Hrezy+X/5ZczQW51LUmvzfcqOurnkCIRFTyjdVjzR7JvENzI6+VKBJzJdPh6EYL4RoWl92b2Hrk9fw==) seems to be corrupted. Trying one more time.

Also, it takes an absurdly long time to install.

**Comment by ojeytonwilliams** [comment]
@Manish-Giri the tentative solution seems to be some combination of the following (perhaps all are required, I'm not 100% sure). 

- Upgrade to the latest lts for node
- update npm
- exclude nodejs (c:\Program Files\nodejs) and npm (c:\Users\YourUserName\AppData\Roaming\npm) from your antivirus (this bit I found from [here](https://ilikekillnerds.com/2017/02/yarn-slow-windows-disable-windows-defender/)).

I say 'tentative' because it takes slow long to run `npm ci` that I've not had time to do enough installs to be confident it's reliable.  Given how appallingly slow it is, I'm going to concentrate on getting Docker working, in the hopes that that's less bad!

**Comment by Manish-Giri** [comment]
@ojeytonwilliams Thanks! I've actually given up trying to get `npm ci` to run successfully.  It takes more than 50-60 minutes to complete on average, on each run.

Regarding the docker issue, after going through my docker images, I found that the `node:lts` image I had in my local image cache dated back over 2 months - 

![node](https://user-images.githubusercontent.com/11348778/70093840-4360b600-15ef-11ea-8e52-4abd7a5425be.png)


That was probably the last time I tried to set up fcc on my windows machine, and it is quite possible that back then, Node LTS was at v10, so this `node:lts` image that was pulled from docker hub as part of the setup, referred to Node v10. And now when running the docker setup, because `node:lts` was found in my local image cache, Docker didn't pull the latest version from docker hub, even though `node:lts` should now be at v12. 

This theory is just a guess (maybe there is a way to look at `node:lts` image logs to see when it upgraded), but tonight I'll delete the `node:lts` image that I have saved locally and after the latest image gets pulled, check if the node version is correctly at v12 in the container. Will keep you updated.

Also, if this turns out to be correct, perhaps this scenario is something that we should address in the codebase, programmatically? Because it is certainly reproducible and can happen in the future too. Maybe there is a way to check if the image in the local cache is older than a certain period, and if so, invalidate the cache and trigger a `docker pull`.

**Comment by Manish-Giri** [comment]
Turns out I was right, the `node:lts` image being used was the one present in my local cache, and it was outdated, but I still get the same error (more on that in a bit).

Once I deleted that image, this is the output from `npm run docker:init` -

![d31](https://user-images.githubusercontent.com/11348778/70107063-79b02c80-1613-11ea-8e03-1b5e216d33fd.png)

Notice the first few steps, where it pulls the newer image from `library/node`. 

To confirm the new version, while `npm run docker:install` was executing, I used `docker exec -it` to get into the container and check the versions -

![d32](https://user-images.githubusercontent.com/11348778/70107195-d27fc500-1613-11ea-845a-3b016c806528.png)

Node is at 12.13.1, and npm is at 6.12.1.

Regardless, I still get the same error about ` '/app/curriculum/node_modules'` being locked. This time though I do get the input about the libcipm patch. 

```shell
PS C:\Users\Manish\Documents\Development\Github\FCC\FreeCodeCamp> npm run docker:install

> @freecodecamp/freecodecamp@0.0.1 docker:install C:\Users\Manish\Documents\Development\Github\FCC\FreeCodeCamp
> docker-compose run -u root --rm freecodecamp bash patch_npm_and_install.sh

Starting freecodecamp_mailhog_1 ... done                                                                                                                                                        Starting freecodecamp_db_1      ... done                                                                                                                                                        patching file /usr/local/lib/node_modules/npm/node_modules/libcipm/index.js
Reversed (or previously applied) patch detected!  Assume -R? [n] n
Apply anyway? [n] y
Hunk #1 FAILED at 156.
1 out of 1 hunk FAILED -- saving rejects to file /usr/local/lib/node_modules/npm/node_modules/libcipm/index.js.rej
npm WARN prepare removing existing node_modules/ before installation

> fsevents@1.2.9 install /app/node_modules/fsevents
> node install


> husky@1.3.1 install /app/node_modules/husky
> node husky install

husky > setting up git hooks
husky > done

> @freecodecamp/freecodecamp@0.0.1 postinstall /app
> npm run bootstrap


> @freecodecamp/freecodecamp@0.0.1 bootstrap /app
> lerna bootstrap --ci

lerna notice cli v3.16.4
lerna info versioning independent
lerna info ci enabled
lerna info Bootstrapping 10 packages
lerna info Installing external dependencies
lerna ERR! npm ci exited 240 in '@freecodecamp/curriculum'
lerna ERR! npm ci stderr:
npm WARN prepare removing existing node_modules/ before installation
npm ERR! path /app/curriculum/node_modules
npm ERR! code EBUSY
npm ERR! errno -16
npm ERR! syscall rmdir
npm ERR! EBUSY: resource busy or locked, rmdir '/app/curriculum/node_modules'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-12-04T02_17_04_695Z-debug.log

lerna ERR! npm ci exited 240 in '@freecodecamp/curriculum'
npm ERR! code ELIFECYCLE
npm ERR! errno 240
npm ERR! @freecodecamp/freecodecamp@0.0.1 bootstrap: `lerna bootstrap --ci`
npm ERR! Exit status 240
npm ERR!
npm ERR! Failed at the @freecodecamp/freecodecamp@0.0.1 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-12-04T02_17_04_964Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 240
npm ERR! @freecodecamp/freecodecamp@0.0.1 postinstall: `npm run bootstrap`
npm ERR! Exit status 240
npm ERR!
npm ERR! Failed at the @freecodecamp/freecodecamp@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-12-04T02_17_05_344Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 240
npm ERR! @freecodecamp/freecodecamp@0.0.1 docker:install: `docker-compose run -u root --rm freecodecamp bash patch_npm_and_install.sh`
npm ERR! Exit status 240
npm ERR!
npm ERR! Failed at the @freecodecamp/freecodecamp@0.0.1 docker:install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Manish\AppData\Roaming\npm-cache\_logs\2019-12-04T02_15_12_281Z-debug.log
```

**Comment by ojeytonwilliams** [comment]
@Manish-Giri after a long struggle getting Docker to work, I'm afraid I didn't run into the locking issue.  The problem with the local setup, yes, but this one seems to work okay.

I'm not sure where to go from here.  I'll put together a PR to document (somewhere) some of the pain points I encountered when trying to get docker to work, though.

**Comment by Manish-Giri** [comment]
@ojeytonwilliams After your recent changes to simplify the Docker development setup, I was able to get past the errors, but now it seems to be stuck (40-50 minutes) at this stage?

![e3](https://user-images.githubusercontent.com/11348778/70870872-c9bdb600-1f66-11ea-92ef-56b1665db3f8.png)

Were you able to access `localhost:8000` right after this, or is there more console output expected before the client is available?

I also noticed there seems to be a timeout error connecting to MongoDB in the logs, though the mongo container is already up -

![e4](https://user-images.githubusercontent.com/11348778/70870893-0689ad00-1f67-11ea-80d2-52d82da9089b.png)

**Comment by ojeytonwilliams** [comment]
I managed to get it working with the VM settings in the docs, but possibly that's on the edge of what it needs.  The only thing I can suggest is the obvious: increase the memory, if you can.  Are you already maxed out?

**Comment by raisedadead** [comment]
We are recommeding https://contribute.freecodecamp.org/#/how-to-setup-wsl now. I am using this setup as my daily driver.
