### ISSUE TITLE
React: Create a Controlled Input

### ISSUE THREAD

**Issue by wale-bant** [freeCodeCamp/freeCodeCamp#37860]
**Describe your problem and how to reproduce it:**
The instruction on the page are correct but the  task to be performed according to the user story are for the previous exercise (React: Write a Simple Counter).

How to produce:
Just follow the instruction and type in the required code and click submit. The code won't run even if correct because the test requires the code for the former excersie

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/react/create-a-controlled-input

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@wale-bant Not understanding what you think is an issue.  How can the instructions on the page be correct bu t the task to be performed (the instructions) be incorrect? You will need to provide more information such as the code you attempted for this challenge.

Did you bring this up on [our forum](https://www.freecodecamp.org/forum)?  If so, what did other users say?

**Comment by moT01** [comment]
Closing as stale and unresponsive OP. Thanks for the report, let us know if you can provide more details.
