### ISSUE TITLE
Tests assertion bug

### ISSUE THREAD

**Issue by kingeke** [freeCodeCamp/freeCodeCamp#37861]
Basically the projects that involves Node and Glitch are not doing the tests properly.

I'm currently on Information Security and Quality Assurance Project Challenges and I can use the glitch link to start the project, then copy the link without doing anything in the project and submit it for both my glitch solution and github link.

After submission my tests will all pass even when I basically have no code in my glitch.

Please this should be looked at.

Thank you.

**Comment by PartyLich** [comment]
There's an open issue in progress for these backend project tests. See #37185

**Comment by RandellDawson** [comment]
Closing as duplicate of #37185.
