### ISSUE TITLE
Need to allow users to use helper functions for the recursive challenges

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#37868]
Currently we recently added 3 recursion challenges to the curriculum.  Each challenge has a test that checks to see if the user used recursion to solve the challenge.  We check this by first converting the calling function to a string and then using regex to match the name of the calling function somewhere inside it (after removing comments).  This works well unless the user implements a helper function that actually makes recursive calls.

The [Use Recursion to Create a Countdown](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-recursion-to-create-a-countdown) challenge starts with the following seed code:
```js
//Only change code below this line
function countdown(n){
  return;
}
console.log(countdown(5)); // [5, 4, 3, 2, 1]
```
The following is a perfectly valid solution, but our tests expect to see `countdown` called inside the `countdown` function instead of `counter`.  
```js
function countdown(n) {
  function count(arr, n) {
    if (n >= 1) {
      arr.push(n);
      return count(arr, n - 1);
    }
    return arr;
  }
  return count([], n);
}
```
What is the best way to validate recursion is used for these challenges while allowing the user to create a helper function for the recursive calls?

**Comment by RandellDawson** [comment]
To keep things simple, I suppose we could change the test text to something like:
>You should use recursion to solve this problem by calling `countdown` within the `countdown` function.

**Comment by ojeytonwilliams** [comment]
We could use a regex along the lines of
```js
(?:const|var|let)\s(\w+)\s=\s\(\w+\)\s=>\s{\s\1\(\w+\)\s}|function\s(\w+)\(\w+\)\s{\s*\2\(\w+\)\s*}
```
it's likely to be bug prone, though, so we'd need to be careful.

Another option is to rely on the test that checks if they're using various looping functions.  I doubt many people will come up with non-recursive non-looping solutions.

**Comment by RandellDawson** [comment]
> Another option is to rely on the test that checks if they're using various looping functions. I doubt many people will come up with non-recursive non-looping solutions.

I like this option.  Does anyone want to work on achieving this with a new test or modification of an existing test?

**Comment by nhcarrigan** [comment]
I can take a look at adding this 🙂

**Comment by nhcarrigan** [comment]
Heya @RandellDawson - so poking around in the file, we already have a test that checks for the looping functions:
```js
testString: assert(!removeJSComments(code).match(/for|while|forEach|map|filter|reduce/g));
```

Should I work with the regex proposed above to test for recursion? Or would it be better to remove the recursion test?

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
