### ISSUE TITLE
I suppose arr.filter() could be a better "help link" than arr.some() for this bonfire;

### ISSUE THREAD

**Issue by zmen** [FreeCodeCamp/FreeCodeCamp#3786]
Challenge [Bonfire: Finders Keepers](http://www.freecodecamp.com/challenges/bonfire-finders-keepers) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I didn't find a concise solution by using arr.some() while I found a better one by using arr.filter().
Just like this:
My code:
```javascript
function find(arr, func) {
  return arr.filter(function(val){return func(val);})[0];
}
```
Or if there is a better one by using some()?

**Comment by ltegman** [comment]
I completely agree with this. `some` doesn't seem necessary or helpful for this problem and I've yet to see anyone come up with a solution using some that is more efficient than using `filter` or just a simple for-loop. Someone should put in a PR for this.

**Comment by xRahul** [comment]
You can just use this instead of calling the function inside another function in filter()

 ```js
function findElement(arr, func) {
  return arr.filter(func)[0];
}
```

or I'd prefer to use `find()` actually
```js
return arr.find(func);
```
