### ISSUE TITLE
The "Make an Image Responsive" challenge is missing a CSS attribute

### ISSUE THREAD

**Issue by Ragnarokkr** [freeCodeCamp/freeCodeCamp#37875]
**Describe your problem and how to reproduce it:**
In the *Responsive Web Design Principles: Make an Image Responsive* challenge, the CSS attribute `width: 100%` is missing from the code and description, which it may could not affects the challenge result, but it won't resize the image to 100% size as described into the description.

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-principles/make-an-image-responsive.english.md

**Tell us about your browser and operating system:**
* Browser Name: Brave
* Browser Version: 1.0.1 Chromium: 78.0.3904.108 (Official build) (64-bit)
* Operating System: Windows 10 x64

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![brave_2019-12-05_18-52-17](https://user-images.githubusercontent.com/893472/70260582-e13fb680-1790-11ea-8d4a-b48c44a8b60d.jpg)
![brave_2019-12-05_18-52-39](https://user-images.githubusercontent.com/893472/70260583-e1d84d00-1790-11ea-88be-8e9aa1a733c0.jpg)

**Comment by ojeytonwilliams** [comment]
There are two problems with this challenge.  The `max-width` property wording could be clearer and the image should be larger than its containing block (so the css actually does something).

I think a reasonable fix would be to wrap the image an explicit, fixed size, containing block.  Then you can see that the image starts out larger than the container and then, once the `img` style is applied, it shrinks to fix.  Perhaps the wording could be:

> The max-width property of 100% makes sure the image is no wider than its containing block (in this case a fixed width div), but has no effect unless the image is larger than its container

The seed would be something like this:

```html
<style>
body {
    background-color:green;
}
</style>

<div style="width: 200px; height: 300px; background-color: blue">
<img src="https://s3.amazonaws.com/freecodecamp/FCCStickerPack.jpg" alt="freeCodeCamp stickers set">
</div>
```

Or perhaps we could have two images, one bigger than the container and one smaller, so the user can see the difference.

**Comment by Ragnarokkr** [comment]
That sounds a reasonable rewording. Making clearer the purpose of `max-width` won't let the user think there's something wrong in their code.
