### ISSUE TITLE
Zipline 2. orphan closed tag

### ISSUE THREAD

**Issue by Nekony** [FreeCodeCamp/FreeCodeCamp#3787]
On this link: http://codepen.io/FreeCodeCamp/pen/mJNqQj from the [second challenge of Zipline](http://www.freecodecamp.com/challenges/zipline-build-a-personal-portfolio-webpage).
HTML section L7: `</button>` has no parent.

**Comment by SaintPeter** [comment]
This appears to have been resolved.

Closing as fixed.

Thank you and happy coding!
