### ISSUE TITLE
Certifications display differently if page is reloaded

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37872]
**Describe the bug**
The appearance of the donation message on the certification pages changes if you reload the page vs. navigating to it from within the site.  This is in addition to the style issues noted in https://github.com/freeCodeCamp/freeCodeCamp/issues/37378

**To Reproduce**
1. Go to your own profile (freecodecamp.org/your-user-name)
2. Click on a completed certification
3. See that the message only has a small gap at the top
4. Reload the page
5. See that the gap has grown

**Expected behavior**
It should not depend on how you navigate to the page.

**Screenshots**

![image](https://user-images.githubusercontent.com/15801806/70237808-459a5000-1768-11ea-9b03-41d4bd307719.png)
vs
![image](https://user-images.githubusercontent.com/15801806/70237845-52b73f00-1768-11ea-963b-77bd8effbf18.png)

**Context**

At its heart, this is a routing problem, as discussed in https://github.com/freeCodeCamp/freeCodeCamp/pull/37471, but there's no ETA on that fix, so I think it's okay to use some extra css rules to solve this for now.

**Comment by moT01** [comment]
I was about to create a new issue, but I think I found a related problem...

Buttons when clicking on a cert have no hover effect or background color...
<img width="963" alt="Screen Shot 2019-12-13 at 8 11 00 PM" src="https://user-images.githubusercontent.com/20648924/70842071-2db87100-1de5-11ea-861f-8e827653b4b8.png">
<img width="601" alt="Screen Shot 2019-12-13 at 8 11 23 PM" src="https://user-images.githubusercontent.com/20648924/70842073-30b36180-1de5-11ea-9845-8d91c09e2452.png">

Buttons when reloading the cert page do...
<img width="757" alt="Screen Shot 2019-12-13 at 8 21 54 PM" src="https://user-images.githubusercontent.com/20648924/70842208-5f7e0780-1de6-11ea-8142-3565d9610b0b.png">
<img width="750" alt="Screen Shot 2019-12-13 at 8 21 01 PM" src="https://user-images.githubusercontent.com/20648924/70842210-6278f800-1de6-11ea-899f-f3a7053f7c5d.png">

**Comment by thecodingaviator** [comment]
@moT01 I have incorporated that in my PR now. Please check
