### ISSUE TITLE
choose a different type.

### ISSUE THREAD

**Issue by ZoDaCoKe** [freeCodeCamp/freeCodeCamp#37886]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by thecodingaviator** [comment]
Please add further information to your problem and open a new issue or request for this to be reopened. Have a good day!
