### ISSUE TITLE
re

### ISSUE THREAD

**Issue by kosta111121** [freeCodeCamp/freeCodeCamp#37883]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Manish-Giri** [comment]
If you need help with a coding challenge, please visit the [freeCodeCamp forum](https://www.freecodecamp.org/forum/).

If you found an issue or a bug with one of the coding challenges or with the freeCodeCamp platform,  please edit your issue to include the relevant required details.
