### ISSUE TITLE
Feature Request:  Online Waypoint/Bonfire Editor

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#3788]
*Fact:*  Editing waypoint JSON is a huge pain.  
The "string in a string" formatting requirements are onerous, the need to re-seed and re-launch gulp with every change are a drag.  It's hard to iterate on exiting waypoints and hard to make new ones.

### Proposal
Make an online waypoint editor, maybe on the Beta site.  This should vastly simplify the process of making changes/corrections to current waypoints/bonfires and creating new waypoints/bonfires.

### Features
Three Modes:
1) Edit Mode
This mode should have editable text boxes for all of the features of a Waypoint/Bonfire for every different type.  Fields should be editable in "plain text".  If possible, arrays which are combined into single fields should be displayed as a single text box.  

It should also be possible to pull up the text/definition of an existing waypoint.  The waypoint ID field should have a "New Object ID" button, for making new waypoints.

A "save" option should save all of the current fields into browser local storage for the other two modes.

2) Preview Mode
Display the edited waypoint in the "end user" view.  Allow for normal testing of the waypoint in the same way a user would test it.

3) JSON Mode
Display the JSON for the waypoint in a text editor box.  Allow for direct edit of the JSON and/or cut and paste of alternate JSON.  Save button, same as the Edit mode.  

----

The overall thrust of this request should be clear:  simplify the editing and testing process for waypoints.  The final JSON would still need to be cut and pasted into the output files, but changes should be a lot easier.

**Comment by bugron** [comment]
Closing this issue as we have [COM1000](https://github.com/FreeCodeCamp/COM1000) now.
