### ISSUE TITLE
Missing information to produce desired output for a coding challenge.

### ISSUE THREAD

**Issue by Shivang-software-developer** [freeCodeCamp/freeCodeCamp#37889]
**Describe your problem and how to reproduce it:**
In "Functional Programming: Use the reduce Method to Analyze Data" coding challenge ("JavaScript Algorithms and Data Structures Certification" -> "Functional Programming"-> "Functional Programming: Use the reduce Method to Analyze Data"), as per the information, using javascript's "reduce" function to perform average of imdbRating of the movies which were directed by "Christopher Nolan", the functionality yields to 8.52 but the expected answer is 8.675. This is only achieved if additional filtering is considered (movies have to have imdbRating greater than 8.0). 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/use-the-reduce-method-to-analyze-data

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 78.0.3904.108
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/44512358/70390892-449e3400-199d-11ea-82b8-222ede107cd9.png)

**Solution **
With respect to the uploaded image, the bold phrase should include sub-phrase "and imdbRating greater than 8.0"

**Comment by RandellDawson** [comment]
There is no need to include the any sub-phrase because there are 4 movies out of the 5 contained in watchList that Christopher Nolan directed.  The average imdbRating of those 4 movies is 8.675 (the correct answer).
