### ISSUE TITLE
Font 401 errors on .dev

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37898]
The fonts cannot be downloaded on .dev:
![image](https://user-images.githubusercontent.com/15801806/70449368-24a46880-1aa2-11ea-80f9-92258aaf0647.png)

@raisedadead this not a problem in production, but I guess the CDN is rejecting .dev.

**Comment by raisedadead** [comment]
Hmm probably this is the CSP.

**Comment by ojeytonwilliams** [comment]
I don't see the problem any more:
![image](https://user-images.githubusercontent.com/15801806/72966812-15624b80-3dc0-11ea-946e-92dbd7f308e4.png)
