### ISSUE TITLE
Implement Amazon SNS for email campaign

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/freecodecamp#379]

**Comment by elimisteve** [comment]
@ajvb and I have been using MailChimp and Mandrill for automated email, and really like them.  Mandrill is more expensive than SNS IIRC -- 20 cents per thousand instead of 10 -- but totally worth it.  SNS is _really really_ bare bones in its functionality.

**Comment by ajvb** [comment]
Personally, I would almost always choose Mandrill over SNS. The cost impact is small until you are sending a ridiculous amount of emails. Even then, the built in analytic, conversion optimization testing tools, and etc features are worth it. Also, interfacing with the Mandrill API is a lot easier than SNS.

Then again, this all depends on what you are using these emails for. If they are marketing specific, I would take a look at ConstantContact and Mailchimp. Coding up HTML email templates suck (though made a little easier with http://litmus.com/email-builder), so I would always recommend utilizing premade templates if possible.
