### ISSUE TITLE
Tags not responsive @ /news/tag/tagName page

### ISSUE THREAD

**Issue by AsaoluElijah** [freeCodeCamp/freeCodeCamp#37901]
**Recommend tags shown @ /news/tag page is not responsive on mobile devices. The tags are overflowing to the main page content**

**https://www.freecodecamp.org/news/tag/ubuntu/**

**Tell us about your browser and operating system:**
* Browser Name:  Chrome
* Browser Version: 78.0.3904.62
* Operating System: Android 8.1

**Comment by AsaoluElijah** [comment]
![Screenshot_20191209-185344](https://user-images.githubusercontent.com/34748637/70460558-ea919180-1ab6-11ea-9152-bbf44cb98e48.png)

**Comment by moT01** [comment]
Looks like the menu is a little squished as well.

**Comment by AsaoluElijah** [comment]
Yeah, I don't know if anyone is currently assigned to this or working on this?. If there is none, I'll like to take it up 👩‍💻

**Comment by ojeytonwilliams** [comment]
Ideally (though not always) if an fcc member is going to work on an issue, they'll assign themselves as a heads up.  Since that's not the case, go for it!

**Comment by AsaoluElijah** [comment]
Thank you Williams, I'll be glad if you can help with a link pointing to the */news* directory. I'm having difficulties finding it

**Comment by ojeytonwilliams** [comment]
Sure thing.  The news theme has its own repo, take a look [here](https://github.com/freeCodeCamp/news-theme).

Let us know if you have any more questions.

**Comment by AsaoluElijah** [comment]
Thank you

**Comment by ahmadabdolsaheb** [comment]
@AsaoluElijah thanks for working on this.
so we need to relax the nav-padding on line 17 for very small screens.

and remove the max height for the tags container:
<img width="357" alt="Screen Shot 2019-12-13 at 1 00 50 PM" src="https://user-images.githubusercontent.com/4591597/70791895-1cea0a00-1da9-11ea-840e-83242deb1beb.png">

**Comment by AsaoluElijah** [comment]
Hello @ahmadabdolsaheb @ojeytonwilliams , i just created a pull request to fix this issue. Kindly review it.
[Here](https://github.com/freeCodeCamp/news-theme/pull/91) is a link to it

**Comment by AsaoluElijah** [comment]
Hi, Anyone here :octocat:

**Comment by moT01** [comment]
What's up @AsaoluElijah? Do you need some help with something?

**Comment by AsaoluElijah** [comment]
No, thanks Tom. The pr has been merged now. I'll close the issue asap.
Thank you Guys. 🙇
