### ISSUE TITLE
Unable to compile Bonfire: Repeat a string repeat a string

### ISSUE THREAD

**Issue by rejreign** [FreeCodeCamp/FreeCodeCamp#3791]
Challenge [Bonfire: Repeat a string repeat a string](http://freecodecamp.com/challenges/bonfire-repeat-a-string-repeat-a-string#?solution=function%20repeat(str%2C%20num)%20%0A%7B%0A%20%20%20if%20(num%20%3D%3D%3D%200)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20str%3B%0A%20%20%20%20%7D%0A%20%20%0A%20%20if(num%20%3C%200)%0A%20%20%20%20%7B%0A%20%20%20%20%20%20return%20null%3B%0A%20%20%20%20%7D%0A%0A%20%20%2F%2F%20repeat%20after%20me%0A%20%20var%20newString1%20%3D%20str.split(%22%2C%22)%3B%20%20%0A%20%20var%20newString2%20%3D%20%5B%5D%3B%0A%20%20%20%20%0A%20%20while(num%20%3E%200)%0A%20%20%20%20%7B%0A%20%0A%20%20%20%20%20%20for(var%20i%20%3D%200%3B%20i%20%3C%20newString1.length%3Bi%2B%2B)%0A%20%20%20%20%20%20%20%20%7B%20%0A%20%20%20%20%20%20%20%20%20newString2%20%3D%20newString1.push(newString1%5Bi%5D)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%20num--%3B%0A%0A%20%20%20%20%7D%0A%20%20%0A%20return%20newString2.join(%27%27)%3B%0A%0A%7D%0A%0Arepeat(%22abc%22%2C%203)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I am unable to compile my code below. This is a repeat of same issue on this Bonfire.
Please, how do I resolve this?

My code:
```javascript

function repeat(str, num) 
{
   if (num === 0)
    {
      return str;
    }
  
  if(num < 0)
    {
      return null;
    }

  // repeat after me
  var newString1 = str.split(",");  
  var newString2 = [];
    
  while(num > 0)
    {
 
      for(var i = 0; i < newString1.length;i++)
        { 
         newString2 = newString1.push(newString1[i]);
        }
      
       --num;

    }
  
 return newString2.join('');

}

repeat("abc", 3);

```

**Comment by jlslew** [comment]
Your code takes too long to complete or contains an infinite loop.  And here is what I get in the console:
![](https://cloud.githubusercontent.com/assets/1538744/10564306/da36336a-757c-11e5-84b7-1cbf6dd3d670.png)

**Comment by rejreign** [comment]
Ok. I'll take a look, review the code and revert. Thanks @jlslew

**Comment by ltegman** [comment]
Closing as not an issue with the tests, but please feel free to reply if you need further clarification.

Thanks and happy coding!
