### ISSUE TITLE
Clicking logo in nav bar on /learn should redirect to /learn

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#37926]
Currently when clicking the freeCodeCamp logo in the navbar while on /learn it takes me to the landing page: `/`

Instead, clicking the logo on the navbar should take me to /learn.

Aside from your first time arriving at / there is never a reason to be taken back there.

**Comment by moT01** [comment]
I made a PR here, although I'm not sold on the function. I agree that nobody will need to go back to the home page, but it seems a little unintuitive to have it go to `/learn` when a home page exists.
