### ISSUE TITLE
Donate modal doesn't show up unless signed in

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#37928]
I was testing a PR and quickly submitting projects to get a cert - they were all the responsive web design projects. When I was logged in, the donate modal popped up at least twice; when not logged in, it didn't pop up at all.

Perhaps there's a purpose for this, but it seems like we non-authed users should see that more often.

**Comment by ojeytonwilliams** [comment]
At least for the moment, you should only see donation requests while you're signed in and working through the curriculum (or looking at a cert you've completed).  I.e. it sounds like it's working, so I'm closing this.
