### ISSUE TITLE
Auth0 signin doesn't use cursor:pointer when hovering over buttons

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#37927]
As shown in the video below, the buttons in our Auth0 template don't show the pointer-style cursor. It should.

https://youtu.be/5IAcet7mCa8

**Comment by moT01** [comment]
Seems like there's a comma missing in that sentence at the bottom. 
By continuing`,` you agree...

**Comment by ahmadabdolsaheb** [comment]
@scissorsneedfoodtoo might have more context

**Comment by moT01** [comment]
The login area button is also missing this. Where you need to "submit your one time code".

**Comment by raisedadead** [comment]
Source code is available here: https://github.com/freeCodeCamp/auth0-templates/branches

**Comment by scissorsneedfoodtoo** [comment]
Closed via https://github.com/freeCodeCamp/auth0-templates/pull/16
