### ISSUE TITLE
need help guys

### ISSUE THREAD

**Issue by sweetybrahmbhatt** [FreeCodeCamp/FreeCodeCamp#3793]
Challenge [Waypoint: Fill in the Blank with Placeholder Text]
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<kitty ipsum text>kitty ipsum text :kitty ipsum dolor sit amet,shed everywhere shed everywhere streching attack ur ankels case the red dots,hair ball run catnip eat the Grass sniff</kitty ipsum text>

```

**Comment by ltegman** [comment]
Your kitty ipsum text is not inside a valid HTML tag. It should be inside a `<p>` tag, not a `<kitty ipsum text>` tag.

Closing this as not an issue with the tests, but please feel free to reply if you need further clarification.

Thanks and happy coding!

**Comment by sweetybrahmbhatt** [comment]
Tysm for the help Itegman

**Comment by sweetybrahmbhatt** [comment]
Can u plzz explain me ....wht does this kitty ipsum text used for .
I searched alot bt did not get a satisfactory answer

**Comment by matty22** [comment]
@sweetybrahmbhatt Lorem ipsum is filler text that is used very often when developing things for the web. You might not have the actual content when building the structure so you fill it in with Lorem Ipsum text.

Kitty ipsum is just a funny play on Lorem Ipsum.

See this Wikipedia page on Lorem Ipsum

https://en.wikipedia.org/wiki/Lorem_ipsum
