### ISSUE TITLE
new pages should have amp versions.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#37939]
Currently on posts have amp versions on news. As of now ghost does not support [/amp/](https://ghost.org/integrations/google-amp/) for pages.

**Comment by erictleung** [comment]
Unless I'm missing something, it appears that Ghost now supports "built-in integration for Google AMP". Moreover, this is enabled by default.

It appears you can transform each post to an AMP version by adding `/amp` to the end of the URLs.

This appears to work with our posts so far. 

See 

https://www.freecodecamp.org/news/helm-charts-tutorial-the-kubernetes-package-manager-explained/

compared to

https://www.freecodecamp.org/news/helm-charts-tutorial-the-kubernetes-package-manager-explained/amp

**Comment by ahmadabdolsaheb** [comment]
Yes posts ( articles ) have amp version, but not pages. Initially we had many of our organizational pages ported to ghost. Since then we moved them to articles so this feature is not required on our side anymore.

I am closing this accordingly, please feel free to re-open if the issue has not been resolved.

**Comment by tannerpace** [comment]
Unsubscribe
