### ISSUE TITLE
Certificates do not appear on the timeline

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37943]
**Describe the bug**
A user's certificates should appear on their timeline when both the timeline and the certificates are public, but they never appear.

**To Reproduce**
1. Go to /settings
2. Set both "My certifications" and "My time line" to public
3. Click on "Show me my public portfolio"
4. See that no certifications appear on the timeline.

**Expected behavior**
Either the certificates should appear on the timeline or the code for dealing with them should be simplified.  At the moment the server sends back `completedChallenges` with (or without) certs if they are public (or not), but the timeline always filters them out.

**Comment by moT01** [comment]
So what's the behavior we want? Just put the certs in the timeline like any other challenge (when they're public)?

**Comment by ojeytonwilliams** [comment]
I assume so.  @raisedadead ?

**Comment by raisedadead** [comment]
I think that would be fine for now, if we could make them visually distinct, like a bolder, larger text.

**Comment by moT01** [comment]
I can try and come up with something for this.
