### ISSUE TITLE
E2E tests

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#37944]
I'm opening this issue to keep track of things that I think should be tested when we get E2E testing up and running.  If anyone else has anything they think should be tested, feel free to edit it in here.

- [ ] When a user claims a certification their profile should update (without needing to reload)  to show this.
- [ ] A user can create a mixed-case username https://github.com/freeCodeCamp/freeCodeCamp/pull/37915#issuecomment-565292033, once https://github.com/freeCodeCamp/freeCodeCamp/issues/35525 has been resolved
- [x] Test donate pages, modals and returning (isDonating) user behaviours.
- [x] It should be possible to submit all types of challenges and projects and confirm that they have been recorded.

**Comment by iansibindi** [comment]
Hy

**Comment by ShaunSHamilton** [comment]
Hey Oliver, I assume all but the second [ ] can be ticked off?

Also, #39723 appears to be the opposite of what was discussed in #35525

**Comment by ojeytonwilliams** [comment]
> Also, #39723 appears to be the opposite of what was discussed in #35525

Hi Shaun, you're quite right about that, I've reached out to Mrugesh for clarification.

I had a look and couldn't find anything checking that certs appear on user profiles (with or without reloads). Am I missing something?

**Comment by ShaunSHamilton** [comment]
> Am I missing something?

No, it is my mistake; I skimmed the point too quickly, and thought it was just checking for claiming certificates.

I can submit a PR for this, if one is not already waiting.

**Comment by ojeytonwilliams** [comment]
> I can submit a PR for this, if one is not already waiting.

Not to my knowledge. That would be great, thanks.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
