### ISSUE TITLE
order of keys shouldn't matter

### ISSUE THREAD

**Issue by SimonSiefke** [freeCodeCamp/freeCodeCamp#37958]
**Describe your problem and how to reproduce it:**
The order of the keys shouldn't matter, but only solutions where the `title` key is above the `rating` key are accepted.

```js
// this isn't accepted
const ratings = watchList.map(({ Title, imdbRating }) => ({
  rating: imdbRating,
  title: Title,
}));
```

```js
// this is accepted
const ratings = watchList.map(({ Title, imdbRating }) => ({
  title: Title,
  rating: imdbRating,
}));
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/use-the-map-method-to-extract-data-from-an-array

**Comment by RandellDawson** [comment]
@SimonSiefke Thanks for reporting.  I created a PR to resolve the issue.  Once it gets reviewed/merged, a user will be able to put the properties in any order (as it should be).
