### ISSUE TITLE
You should add the link at the bottom as a helpful link to this problem

### ISSUE THREAD

**Issue by JAWs41493** [FreeCodeCamp/FreeCodeCamp#3795]
Bonfire: Factorialize a Number
Return the factorial of the provided integer.

If the integer is represented with the letter n, a factorial is the product of all positive integers less than or equal to n.

Factorials are often represented with the shorthand notation n!

For example: 5! = 1 * 2 * 3 * 4 * 5 = 120

Remember to use Read-Search-Ask if you get stuck. Write your own code.

Here are some helpful links:

Arithmetic Operators

<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions#Recursion>

**Comment by awesomeaniruddh** [comment]
Closing this issue. Please reopen with additional details regarding the issue.
