### ISSUE TITLE
CSS challenge doesn't accept solution without semicolon

### ISSUE THREAD

**Issue by SimonSiefke** [freeCodeCamp/freeCodeCamp#37950]

**Comment by RandellDawson** [comment]
@SimonSiefke You are correct that many of the CSS challenges do not accept a valid solution without a semi-colon after the property/value pair when it should.

This would be a valid issue and we would welcome a PR with the challenges that are affected.

**Comment by LarryHu0217** [comment]
Could you provide more details about how to fix it?

**Comment by RandellDawson** [comment]
> Could you provide more details about how to fix it?

You would need to adjust the assert in the `testString` for the test.
