### ISSUE TITLE
"for" attributes on labels in "Build a Survey Form"

### ISSUE THREAD

**Issue by nellarro** [freeCodeCamp/freeCodeCamp#37961]
**Is your feature request related to a problem? Please describe.**
No. It is related to a little added accessibility to the "Build A Survey Form" requirements.

**Describe the solution you'd like**
Adding "for" attributes to labels so that a student's eventual form is a smidge more accessible

**Describe alternatives you've considered**
Adding placeholder text.

**Comment by AshNaz87** [comment]
@raisedadead Would like a crack at this

**Comment by alti21** [comment]
Hi can I work on this?

**Comment by RandellDawson** [comment]
@alti21 To resolve this issue involves more than just adding a new user story description.  You would also need to update the user story in the [testable-projects-fcc repo](https://github.com/freeCodeCamp/testable-projects-fcc) and update the applicable tests associated with the challenge.

**Comment by AshNaz87** [comment]
@RandellDawson Submitted a [PR](https://github.com/freeCodeCamp/testable-projects-fcc/pull/1073)

Next steps?

**Comment by moT01** [comment]
Sorry it's been so long on this one everyone.

I'm not sure we want to add more tests to this project. It's been pretty static for quite some time. Adding tests will break a lot of previously submitted projects. I don't mind the extra tests, it's probably good practice to use the for attribute. I could go either way, but I think we might just want to leave it alone.
