### ISSUE TITLE
Run the tests button does not work.

### ISSUE THREAD

**Issue by sch-xiv** [freeCodeCamp/freeCodeCamp#37970]
Hi,

In the basic javascript module I've been unable to run the tests. The button just does not work. I have tried resetting and trying again and it still doesn't work. I am using google chrome but have also tried firefox and IE with no results. I also updated my google chrome and that didn't fix it either. It started randomly out of nowhere after successfully completing other modules. It started on Comparisons with the Logical And Operator. I tried just skipping it, but it seems to be doing the same thing in future lessons as well. The console is showing:
"Failed to load resource: https://www.freecodecamp.org/page-data/fccecc095c9-eb45-4eeb-b41b-f4ac9e0a6295/page-data.json the server responded with a status of 404 ()"

and

"A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>." x24 with different URLs

Thanks

**Comment by raisedadead** [comment]
Hi @sch-xiv 

Thanks for reporting. This looks like something is blocking resources on the network you are on.

Is there a chance you could try this on a different network? For example try and use a VPN? We would like to isolate the root cause of the issue.

Thanks.

**Comment by sch-xiv** [comment]
> Hi @sch-xiv
> 
> Thanks for reporting. This looks like something is blocking resources on the network you are on.
> 
> Is there a chance you could try this on a different network? For example try and use a VPN? We would like to isolate the root cause of the issue.
> 
> Thanks.

I attempted it with a VPN and still had the same issue. I will try it from work today and report back.

Thanks

**Comment by raisedadead** [comment]
Ok. If the issue persists, can you share the general area you are in like country and city?

**Comment by sch-xiv** [comment]
> Ok. If the issue persists, can you share the general area you are in like country and city?

I tried it at work yesterday and experienced the same problem. I am in Ann Arbor, Michigan.

**Comment by raisedadead** [comment]
Hi @sch-xiv we have recently moved around our servers to newer locations. Can you confirm if this is still the case? If not, can you close the issue.

**Comment by moT01** [comment]
I think it's safe to close this since the OP hasn't responded and nobody else seems to be having this issue. If you are still experiencing problems @sch-xiv, let us know and we can reopen this and try to figure out more.
