### ISSUE TITLE
Challenge times outs and crashes my computer, max out 8gb of memory

### ISSUE THREAD

**Issue by ajaxWebDev** [freeCodeCamp/freeCodeCamp#37971]
**Describe your problem and how to reproduce it:**
problems was solving the while loop, i can't finish typing the answer, the screen will change to a "AWW Snap there was a problem with this page" and at other times it will completely use up all the memory i have, freezing my computer to the point where i have to do a hard reset, restarting the computer. 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-while-loops

**Tell us about your browser and operating system:**
* Browser Name: google chrome
* Browser Version: Google Chrome is up to date
Version 79.0.3945.88 (Official Build) (64-bit)
* Operating System: Windows 7 Professional SP1

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
i was able to keep the page on longer by bringing up chrome dev tools this is the picture i was able to snip.  
![fcc](https://user-images.githubusercontent.com/32934618/71340919-497af000-2526-11ea-8f53-8089a28bcc0b.JPG)

this is just a pic of the "AWW snap" page that pops up.
![fcc1](https://user-images.githubusercontent.com/32934618/71340932-539cee80-2526-11ea-8eca-2f08dc787b5f.JPG)

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
