### ISSUE TITLE
Intermediate Algorithm Scripting: Binary Agents (No bug just clarification might be in order)

### ISSUE THREAD

**Issue by jondparadise** [freeCodeCamp/freeCodeCamp#37974]
Here is the challenge page:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/binary-agents

No real bug issue here just thought it prudent that the expected encoding for this problem be provided with the question (ASCII, UTF-8, UTF-16, etc). A google search tells me that the default encoding in JS is UTF-16.

First, that would ensure that we are using the same character set and second, it might provide some avenues for people to explore as they try to solve this problem. 

I only mention this because I have faced much frustration in the past with using a different encoding type while trying to inspect/manipulate/regex strings.

**Comment by moT01** [comment]
Closing as stale. Thanks and happy coding 🎉
