### ISSUE TITLE
Stock Price Checker Proxy should not be tracking changes to cache/db

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#37980]
I remixed the FCC Stock Picker API referenced in [this forum post](https://www.freecodecamp.org/forum/t/information-security-and-quality-assurance-projects-stock-price-checker-workaround-site-broken/335703) and notice the disk space has been maxed out.  Glitch only allows about 200 MB of disk storage and that includes the `.git` folder too.  Glitch automatically commits every single change made to the repo which would include the `cache/db`.  I suggest adding a `.gitignore` file to the project and ignoring the `cache/db` so it does not create a commit every time it gets updated.

The actual Glitch project in question is located [here](https://glitch.com/edit/#!/repeated-alpaca)

I would like to fix this issue, but I do not see a repo under freeCodeCamp for the proxy.  It appears the project was created by @Em-Ant but I could not find a stock-checker-proxy repo in his GitHub account or the freeCodeCamp account.  We should really have this under the FCC umbrella anyway.

**NOTE:**  A quick fix is to have someone who has access to the Glitch project to try and run `git prune` or `git gc`.

**Comment by Em-Ant** [comment]
@RandellDawson i can do it . let me try...

**Comment by scissorsneedfoodtoo** [comment]
Thank you for catching this @RandellDawson, and @Em-Ant for jumping in to work on this.

Please let me know if there's anything I can do to help out or if I can add anyone to the fCC Glitch team for future access.

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo This entire API should be in a GitHub repo owned by freeCodeCamp shouldn't it?  Then changes can be made to the repo and then pushed to Glitch.

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, at the moment it only exists on Glitch. I'll create a repo for it so future changes will be easier.

**Comment by Em-Ant** [comment]
i added a simple cache cleaning (only invalid items) on app restart. Unless there are other problems, i think we can close this issue

**Comment by scissorsneedfoodtoo** [comment]
Awesome! Thank you for the quick fix @Em-Ant. I'll close this and create a repo like @RandellDawson suggested.
