### ISSUE TITLE
Deprecated property grid-gap

### ISSUE THREAD

**Issue by SimonSiefke** [freeCodeCamp/freeCodeCamp#37988]

**Comment by Mstava** [comment]
Hello, @SimonSiefke is this still open to solve it or what?

**Comment by RandellDawson** [comment]
@Mstava At this point, nothing has been agreed upon on how to move forward, so there is no point in creating a PR yet.

**Comment by thecodingaviator** [comment]
My way of tackling this would be to teach both properties in the same challenge and add a note saying that `grid-gap` was the old way of doing it

**Comment by SimonSiefke** [comment]
## The new `gap` property
The new `gap` property can be used for flexbox and css-grid, so it's a bit more than just a replacement for `grid-gap` (maybe we could add a flexbox challenge for `gap`, but that would be another issue).

## Browser support 
- [x] Chrome
- [x] Chrome for Android
- [x] Firefox
- [x] Opera
- [ ] Safari (only supports `grid-gap` but not `gap`)
- [ ] IE (supports neither `gap` nor `grid-gap`)*

Sources: [caniuse](https://caniuse.com/#search=gap), [grid-layout in internet explorer](https://rachelandrew.co.uk/archives/2016/11/26/should-i-try-to-use-the-ie-implementation-of-css-grid-layout/)

\*I still haven't seen a source for @RandellDawson's claim that the prefixed property is supported in IE.

## Facts
- `grid-gap` is a **legacy property**
- `grid-gap` is still needed to support Safari
- CSS is commonly used with Autoprefixer so many users don't ever need to use `grid-gap` for Safari support because it is automatically prefixed

## My Response to arguments for using `grid-gap` instead of `gap`
From @raisedadead:
> Meaning you need to implement a API two ways.

That is a valid argument. You need to do it another way if you want to support IE. And another way if you want to support IE 6. There will always be browsers that don't support all the latest properties - but that shouldn't keep us from using them.

> Its not generic, definitely not universal 

This is the same as the previous sentence. 

> and hence not deprecated.

According to [techtarget](https://whatis.techtarget.com/definition/deprecated) (which is the first result when I search for `deprecated`): 
"A deprecated language entity is one that is tolerated or supported but not recommended". Since `grid-gap` is still tolerated and supported but not recommended, it is per definition deprecated.

## My Conclusion
The `grid-gap` property should be completely removed from the curriculum. People should not be taught the legacy property only because Safari doesn't support it yet.

I also think that adding a note saying that `grid-gap` was the old way of doing it as @thecodingaviator suggested would definitely be helpful.

**Comment by raisedadead** [comment]
> People should not be taught the legacy property only because Safari doesn't support it yet.

Take away this and only this from any discussion, *we need not be opinionated* about what people 'need' to learn. The above argument is 100% opinionated. We need to teach facts, with disclaimers if needed and let users decide what they would like to learn, use or skip.

I will recommend let's keep the thread constructive with proposals on what would be a better solution.

Mine would be teach both the things, with correct disclaimers.

**Comment by SimonSiefke** [comment]
> We need not be opinionated about what people 'need' to learn.

Take away this and only this from any discussion, we need be opinionated about what people 'need' to learn. The above argument is 100% opinionated. We need to teach relevant facts and not all facts. Why would we teach about IIRFilterNode, SVGPathSegCurvetoCubicSmoothAbs or WebGLStatusContext? 

So the real questions is:
Should we 
a) teach only about legacy property `grid-gap` or
b) teach about legacy property `grid-gap` and the `gap` property or
c) teach only about `gap` or
d) teach only about `gap` and add a note about the legacy property

> I will recommend let's keep the thread constructive with proposals on what would be a better solution.

Mine would be teach not both the things, but with correct disclaimer/note about the legacy property (d).

**Comment by RandellDawson** [comment]
@SimonSiefke Since `grid-gap` has not been deprecated, I vote for your option `b`.  As with most things in the coding world, there are typically multiple ways of doing the same thing.

**Comment by SimonSiefke** [comment]
> Since grid-gap has not been deprecated

It is deprecated and still tolerated and supported and [only kept for compatibility with legacy content](https://www.w3.org/TR/css-align-3/#gap-legacy). Why do you keep saying otherwise?

**Comment by RandellDawson** [comment]
I have always been under the impression that deprecated means no longer supported.  I see nothing in the documentation which states `grid-gap` is no longer supported.   If I am mistaken, please supply documentation stating so.  If not, why do you say it is deprecated?

**Comment by raisedadead** [comment]
Since this discussion is not getting any constructive with same points coming over and again, here is what we are going to do:

- We will wait for 15 days from this comment for any additional interest in this thread (other members that currently involved in the discussion).
- Once it picks up at least 3-4 additional users and/or experts we can do a vote on the content changes.

Until then this thread should stand closed for discussions (issue to be left open).

**Comment by SimonSiefke** [comment]
@RandellDawson I still havn't seen your source about that grid-gap is supported in IE

> I have always been under the impression that deprecated means no longer supported

According to Wikipedia: 
> In several fields, deprecation is the discouragement of use of some terminology, feature, design, or practice, typically because it has been superseded or is no longer considered efficient or safe, without completely removing it or prohibiting its use. 

This is what my definition is based on.

> It can also imply that a feature, design, or practice will be removed or discontinued entirely in the future

This is what your definition is based on.

Deprecated means that it satisfies definition 1 or definition 2 or both.

`grid-gap` satisfies definition 1, because it has been superseded by `gap`. Therefore `grid-gap` it is deprecated.

**Comment by raisedadead** [comment]
Hi @SimonSiefke thanks for your feedback, I have marked the previous comment off topic. Here is our [code of conduct](https://www.freecodecamp.org/news/code-of-conduct/), I would request you to be constructive, polite and succinct failing which we will have to enforce the COC.

**Comment by thecodingaviator** [comment]
Option b sounds good to me too.

**Comment by Mstava** [comment]
>  As with most things in the coding world, there are typically multiple ways of doing the same thing.

I agree with this option, we could add multiple ways and let the user choose what to use @RandellDawson @raisedadead

**Comment by moT01** [comment]
Closing this as stale. If anyone wants to continue the discussion, I recommend creating a new issue so it might get some attention. Thanks and happy coding 🎉
