### ISSUE TITLE
modify CardExpiryElement to display date in dropdown

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#37983]
The expiration from element needs to be replaced with a dropdown. this is an effort to make the donation form more usable.

![image](https://user-images.githubusercontent.com/4591597/71475094-cd1b3200-27ef-11ea-9bea-bbb32ae76b1a.png)

**Comment by raisedadead** [comment]
I do not this this is possible with the Stripe react elements that we have to use:

See: https://github.com/stripe/react-stripe-elements#available-components

Rolling out your own mean handling the information ourselves, which we will not be doing either.
