### ISSUE TITLE
Space issue in ( ES6: Use Destructuring Assignment to Assign Variables from Objects ) 

### ISSUE THREAD

**Issue by Easyvipin** [freeCodeCamp/freeCodeCamp#37985]
In this challenge ,if i use space between ``today(space):highToday ``  , the following ouptut genrates.
(code)
```
const {today :highToday ,tomorrow: highTomorrow } = HIGH_TEMPERATURES; 
console.log(highToday); // should be 77
console.log(highTomorrow); // should be 80
```
(output)
```
// output
You should use destructuring to create the highToday variable.
// tests completed
// console output
```
However,if i remove the space  ``today:hightoday`` , there is no error in the console.
So i crosscheck this problem in my local system and found that space does't generate the error.

**Comment by moT01** [comment]
[It's the second test here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-objects.english.md#tests).

It should allow a space there with the following...

assert(code.match(/(var|const|let)\s*{\s*(today`\s*`:\s*highToday[^}]*|[^,]*,\s*today\s*:\s*highToday\s*)}\s*=\s*HIGH_TEMPERATURES(;|\s+|\/\/)/g));

The code that needs to be added is highlighted.
