### ISSUE TITLE
News page should have a link or information about how to create articles

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#38007]
We get requests ([like this one](https://www.freecodecamp.org/forum/t/how-we-can-submit-an-article-to-fcc/337794/2)) from users wanting to know about how to write and submit articles for the News page.  Currently, we just refer them to [this forum topic](https://www.freecodecamp.org/forum/t/we-just-launched-developer-news-heres-how-you-can-use-it/279929), but I think there should be a link on the News page somewhere that links to another page detailing how the whole process works and how to get started.

**Comment by raisedadead** [comment]
This page https://www.freecodecamp.org/news/developer-news-style-guide/ should be a good fit. As for where, I believe we should add it to the support page?

@QuincyLarson can you take care of this.

**Comment by QuincyLarson** [comment]
Thanks for your patience @RandellDawson. We intentionally don't have a link on News to give people publication information. This is a buffer against would-be corporate spam that plagues more open publishing platforms.

If someone asks you how get published, please just reply with our style guide. If they read it carefully they'll figure out how to apply as an author: https://www.freecodecamp.org/news/developer-news-style-guide/
