### ISSUE TITLE
404 From Lesson Instructions

### ISSUE THREAD

**Issue by benjaminthedev** [freeCodeCamp/freeCodeCamp#38005]
**The Issue**

Whilst going through the ReactJS lessons the link to: 

'the way you apply classes to JSX elements.' Isn't working, thus giving a 404. The link it tries to go to is this:

https://www.freecodecamp.org/learn/front-end-libraries/react/learn/front-end-libraries/react/define-an-html-class-in-jsx

I've tested the link in Chrome, Firefox, Safari, Opera, Tor, Chrome Canary and Firefox Dev Edition and same 404.

**The lesson**:

https://www.freecodecamp.org/learn/front-end-libraries/react/introducing-inline-styles

**Screenshots**
![Screenshot 2020-01-02 at 11 01 13](https://user-images.githubusercontent.com/14097672/71664008-369ac380-2d4f-11ea-9120-dcade26d0854.png)

and:

![Screenshot 2020-01-02 at 11 00 59](https://user-images.githubusercontent.com/14097672/71664095-96916a00-2d4f-11ea-815a-2f319faf909e.png)

Cheers!

**Comment by raisedadead** [comment]
Hey @ojeytonwilliams this looks like a parser issue? 

Challenge source: https://raw.githubusercontent.com/freeCodeCamp/freeCodeCamp/master/curriculum/challenges/english/03-front-end-libraries/react/introducing-inline-styles.english.md

This is definitely affecting other challenges.

**Comment by raisedadead** [comment]
On that note, I think we should update the URL(s) to be 

```diff
- <a target="_blank" href="learn/front-..."> ... </a>.
+ <a target="_blank" href="/learn/front-..."> ... </a>.
```

**Comment by ojeytonwilliams** [comment]
> this looks like a parser issue?

The parser doesn't touch anchors (to my knowledge).  It's just that that link's relative to the full path, not the domain.  So, yeah, as you say: it needs another slash.

**Comment by raisedadead** [comment]
Okay, thanks for confirming. 

Looking at the [blame](https://github.com/freeCodeCamp/freeCodeCamp/blame/master/curriculum/challenges/english/03-front-end-libraries/react/introducing-inline-styles.english.md#L11) and this seems to have be touched in the past in https://github.com/freeCodeCamp/freeCodeCamp/pull/35125

We should go ahead, audit and update all such links.

**Comment by ChristianLapinig** [comment]
Hi @raisedadead. I fixed the link to the challenge that @benjaminthedev was referring to. But it sounds like there might be more challenges that might have this problem. Do you want me to help find all the broken links before submitting a PR? Or are you ok with me submitting this for now?

**Comment by raisedadead** [comment]
Yes, you should add all the changes to your PR. If you work locally using VS Code, it should just be a simple search and replace.

For the purposes of QA, I would recommend you make separate PR for different languages (English, Chinese, etc.)

Thanks for working on this.

**Comment by benjaminthedev** [comment]
Hi @raisedadead and @ChristianLapinig I am happy to keep working through the challenges and finding issues are reporting on GitHub - if you want me to?

**Comment by raisedadead** [comment]
@benjaminthedev you are welcome to report fresh issues (unrelated to this). I think for this issue, we should be able to do a simple search and replace in the codebase to fix the links :)

**Comment by rohit-ambre** [comment]
> Hi @raisedadead. I fixed the link to the challenge that @benjaminthedev was referring to. But it sounds like there might be more challenges that might have this problem. Do you want me to help find all the broken links before submitting a PR? Or are you ok with me submitting this for now?

I searched `learn/` in VS code and found 34 files with such issues where it requires `/` at start.
There can be more if I have missed anywhere

**Comment by DConstantine9** [comment]
Hey guys! I'm new in open source projects and I want to ask you how can I find a file where a bug is? Thanks. have a good day

**Comment by ahmadabdolsaheb** [comment]
@DConstantine9 please go to the following link and click on the green "New Issue" button
https://github.com/freeCodeCamp/freeCodeCamp/issues

**Comment by raisedadead** [comment]
@ahmadabdolsaheb I think they are seeking to contribute to the repo.

@DConstantine9 you should follow the contributing guidelines mentioned in the read me.

**Comment by AshNaz87** [comment]
@raisedadead Has this been done?

If not, am happy to submit a PR
