### ISSUE TITLE
adding additional theme colors.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#38009]
Users should be able to pick theme colors either from a color picker or from a preselected set of items. 

If users pick a color using a color picker, the theme should adjust the colors automatically to ensure proper contrast and usability

**Comment by naima-shk** [comment]
can i try this one please ? :)

**Comment by ahmadabdolsaheb** [comment]
thanks for your interest, @naima-shk.  We should discuss a comprehensive solution that would fit our current theme implementation. 

Once an implementation is agreed upon, we could more forward with assigning this feature to contributors.

**Comment by PiyushBhangale** [comment]
Can I present some ideas related to this task and work on it accordingly?

**Comment by ahmadabdolsaheb** [comment]
@PiyushBhangale, sure. the first submitted pr will be evaluated first.

**Comment by LarryHu0217** [comment]
Can I join this one@ahmadabdolsaheb

**Comment by ahmadabdolsaheb** [comment]
@LarryHu0217, of course. currently we will most likely include the dawn theme that is used the forum for now.

**Comment by moT01** [comment]
Is this something we still want @ahmadabdolsaheb?

**Comment by ahmadabdolsaheb** [comment]
Thanks for bringing this to my attention. We have gone in another direction at the movement, but we might consider this feature in the future.
