### ISSUE TITLE
Reincorporate dark green into the UI.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#38010]
Dark green 006400 needs to be reincorporated into our UI. 

- [ ] The navbar of the default light theme should use the fcc-green theme, and the rest of the theme colors should be adjusted accordingly to complement fcc-green and ensure good usability.
- [ ] favicon should be set to  green.
- [ ] design style guide should include fcc-green

**Comment by AshNaz87** [comment]
@ahmadabdolsaheb Is this getting the green light? If so, I'd like to help. A colour palette would also be useful

**Comment by ahmadabdolsaheb** [comment]
Thanks for your interest. I will update you with the color palette in a week or so.
it seems like we will need to touch on the light theme as a whole to account for the color change in the navbar.

**Comment by moT01** [comment]
I vote for a new "classic" theme - which reverts to green colors.

**Comment by ahmadabdolsaheb** [comment]
Thanks for bringing my attention to the issue. The feature has been reconsidered and we will continue replacing all green logos with their indigo equivalents. 

We could discuss adding a new theme in a separate issue.
