### ISSUE TITLE
Frontend Libraries: JavaScript Calculator Unit Tests Issue

### ISSUE THREAD

**Issue by jondparadise** [freeCodeCamp/freeCodeCamp#38012]
**Describe your problem and how to reproduce it:**
I have some concerns about the PASS requirements for the Frontend Libraries: JavaScript Calculator
Here is the text from my forum post in regard to the matter:

https://www.freecodecamp.org/forum/t/issue-with-javascript-calculator-certification/338033
"I am taking issue with one of the test requirements and user stories. I don’t think that entering “5 * - 5 =” should produce -25. The minus button is a math operand, not a flag. Should the test case “5 * - - 5 =” produce 25? Should “5 * - - - 5 =” produce -25? As such, I’ve added a negative flag to the calculator to perform that function. I believe that this should pass the test requirements. Anyone care to weigh in?"

**Add a Link to the page with the problem:**
Here is my current solution on CodePen:
https://codepen.io/jon-paradise/pen/NWPwbpW

**Tell us about your browser and operating system:**
* Browser Name: Chrome 
* Browser Version: 79.0.3945.88 (Official Build) (64-bit)
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ojeytonwilliams** [comment]
User story 13 deals with consecutive operators and makes an exception for `-`.  The idea being that "5 * -5" is a perfectly reasonable thing to expect a calculator to evaluate.  There's some discussion, https://github.com/freeCodeCamp/freeCodeCamp/issues/37942, about the fact that the demo calculator doesn't.

> Should the test case “5 * - - 5 =” produce 25?  

There isn't a test case for that and it isn't specified by the user stories, so anything goes.  I'd lean towards -25, personally.

**Comment by RandellDawson** [comment]
Closing in favor of #37942.
