### ISSUE TITLE
email update does not work

### ISSUE THREAD

**Issue by nurpny** [freeCodeCamp/freeCodeCamp#38013]
**Describe the bug**
The link sent to new email address for verifying updated email address does not work correctly. (it redirects (302) to freecodecamp.

**To Reproduce**
1. Go to `'https://www.freecodecamp.org/update-email/'`
2. Click on 'verify email'
3. Open your email from freecodecamp
4. Click on the link provided
5. Redirected to freecodecamp homepage (without email updated)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - macOS

**Smartphone (please complete the following information):**
 - Mac
 - Catalina
 - Chrome

**Additional context**

**Comment by raisedadead** [comment]
Thanks for the report. That route has been deprecated. You should be able to change the email directly in the email settings section on your settings page:

![image](https://user-images.githubusercontent.com/1884376/71760015-e18cb800-2edc-11ea-9b85-8f4f1445f407.png)



https://www.freecodecamp.org/settings

**Comment by raisedadead** [comment]
Thanks for the report. That route has been deprecated. You should be able to change the email directly in the email settings section on your settings page:

![image](https://user-images.githubusercontent.com/1884376/71760030-10a32980-2edd-11ea-839c-bba61edf1993.png)

https://www.freecodecamp.org/settings

**Comment by raisedadead** [comment]
Can you confirm if you followed a link somewhere to reach the `/update-email` page?

**Comment by nurpny** [comment]
hello. the result is the same when the email is updated from the settings page. thanks!

**Comment by raisedadead** [comment]
Okay, thanks for confirming. Looks like a bug, we will get working on this, in the meantime please send a request to `support@freecodecamp.org` get this resolved manually by our staff.

Please mention your username and email address that you already have on records in the same.

Thanks.

**Comment by nurpny** [comment]
will do thank you

**Comment by LarryHu0217** [comment]
I used Mac and safari browser to test, and the email is functional well. I wonder if it is a suspected bug that need to be closed.

**Comment by scissorsneedfoodtoo** [comment]
@nurpny, are you still having issues updating your email address? Also, please send an email to us at support@freecodecamp.org if you haven't already. We could take a closer look at your account and resolve this manually if necessary.

**Comment by nurpny** [comment]
@scissorsneedfoodtoo. will send a separate email to the support team. thank you.

I'm using mac + chrome. 
Currently my settings (https://www.freecodecamp.org/settings) shows: 
 Your email has not been verified. Please check your email, or request a new verification email here.

The verification email sends me to "https://api.freecodecamp.org/confirm-email?email=****&token=******&emailChange=true" -> but when i go to the settings, it's still showing the same message.

**Comment by jonasschmedtmann** [comment]
Also couldn't update my email address a few days ago from [https://www.freecodecamp.org/settings](https://www.freecodecamp.org/settings). The link in the confirmation email would always just send me back to the FCC settings page, but the email was not changed.

I'm on a Mac using Chrome, with an Adblocker and a couple of other extensions, if that's relevant.

**Comment by prolland006** [comment]
I tested on Windows+Chrome to set my email address and it is working on the production. I changed my email address.

**Comment by moT01** [comment]
I did not have any problems changing my email, either. I think it's probably safe to close this. There may still be some edge cases around this - so if anyone wants to see if they can still produce any of these errors, feel free to leave a message and this can be reopened. Thanks and happy coding 🎉
