### ISSUE TITLE
Bug: couldn't verify right answer 

### ISSUE THREAD

**Issue by goodmeow** [freeCodeCamp/freeCodeCamp#38021]
**Describe your problem and how to reproduce it:**
i tried to complete the code

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-principles/use-a-retina-image-for-higher-resolution-displays

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 79.0.3945.88 (Official Build) (64-bit)
* Operating System: Manjaro Linux x86_64

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![Screenshot_20200107_202321](https://user-images.githubusercontent.com/42605122/71898318-9b10b500-318b-11ea-8430-6ec426850255.png)

**Comment by ojeytonwilliams** [comment]
Could you verify that the `img` does have a height and width of 100px?

**Comment by goodmeow** [comment]
no, i couldn't verify img with the required value

**Comment by ojeytonwilliams** [comment]
Sorry, I mean can you open your browser's dev console and check what size the `img` is?

**Comment by goodmeow** [comment]
![image](https://user-images.githubusercontent.com/42605122/71901578-d662b200-3192-11ea-9386-ab4ae60ade4a.png)

its 100px X 100px

**Comment by ojeytonwilliams** [comment]
Thanks for confirming that.  The only things I can think of right now is that the browser extensions might be interfering and that you have two errors in the console.  Could you share those here and try again with the extensions disabled (opening an incognito window should do it)?

**Comment by moT01** [comment]
Is your zoom level at 100%?

**Comment by goodmeow** [comment]
> Thanks for confirming that. The only things I can think of right now are that the browser extensions might be interfering and that you have two errors in the console. Could you share those here and try again with the extensions disabled (opening an incognito window should do it)?

solved with incognito mode, i agree my extension maybe the problem. thanks for answering. 

here is error
![image](https://user-images.githubusercontent.com/42605122/71902518-d499ee00-3194-11ea-8cd4-c33f24d1f859.png)

**Comment by ojeytonwilliams** [comment]
> solved with incognito mode, i agree my extension maybe the problem. thanks for answering.

You're welcome.  Since we've determined it's not a problem with the site, I'm closing this.  Thanks for helping debug the problem.
