### ISSUE TITLE
Portfolio Zipline Example page breaking down

### ISSUE THREAD

**Issue by stwaldo** [FreeCodeCamp/FreeCodeCamp#3802]
The page as shown in the video has been changed since the "how to" was created, adding some neat bootstrap tricks, but it has also started breaking down - some of the images on the page aren't loading any more.  Maybe better to use a static example maintained by FCC rather than a student to keep a canonical example for this zipline.

**Comment by jlslew** [comment]
If you are referring to the weather app zipline, then they are aware of that; #3714, else would you mind posting the name of the zipline you are talking about.

**Comment by stwaldo** [comment]
Sorry, edited subject to reflect.  Link to the zipline:
http://www.freecodecamp.com/challenges/zipline-build-a-personal-portfolio-webpage

Link to the Pen:
http://codepen.io/ThiagoFerreir4/full/eNMxEp

Since I put this up, the creator has made more edits to his Pen - point still stands, I think, in that it's a bit of a moving target.

**Comment by SaintPeter** [comment]
At the time of this writing, the page appears to render properly and looks decent.

I am closing this issue, but if there are further issues with the example, feel free to re-open.

Thank you and happy coding!
