### ISSUE TITLE
Intermediate Algorithm Scripting: Seek and Destroy - Solution 3 not working (misspelled variable name)

### ISSUE THREAD

**Issue by gignupg** [freeCodeCamp/freeCodeCamp#38035]
Solution 3 of this challenge doesn't pass the test.
The 2 variables ("valuesToRemove" and "valsToRemove") are supposed to be one and the same variable. 
I suggest to either change both of them to "valuesToRemove" or both of them to "valsToRemove".

Here the link to the challenge:
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-seek-and-destroy/16046

**Comment by RandellDawson** [comment]
@gignupg I have updated the solution to use `valuesToRemove` and now passes all the tests.

Thank you for reporting.

**Comment by gignupg** [comment]
Sure, thx for fixing it!!
