### ISSUE TITLE
Navigating to freecodecamp.org/signin goes to a 404

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#38046]
**Describe the bug**
Going to freecodecamp.org/signin shows a 404 page.

**Expected behavior**
Should redirect to the Auth0 sign in page.

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Chrome, Firefox

**Comment by raisedadead** [comment]
Fixed.
