### ISSUE TITLE
Hash Table challenge test case

### ISSUE THREAD

**Issue by hisergiorojas** [freeCodeCamp/freeCodeCamp#38049]
**Describe your problem**

The test case pass when the remove method is empty
> The remove method should accept a key as input and should remove the associated key value pair 

**How to reproduce it:**
Here is link of my code: https://gist.github.com/hisergiorojas/8c3dbd57afd02663de9e5c0a70cc21e7

1. Copy and paste the code to the FreeCodeCamp editor.
2. Click on "Run the Tests"
3. There will be a check mark on: 
![alt text](https://i.imgur.com/zR6Mn26.png)

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/create-a-hash-table

**Comment by RandellDawson** [comment]
@moT01 @ojeytonwilliams Wasn't this challenge just changed?
