### ISSUE TITLE
Challenge instructions are not precise.

### ISSUE THREAD

**Issue by leebut** [freeCodeCamp/freeCodeCamp#38047]
**Describe your problem and how to reproduce it:**
I was helping a member on the forum with a challenge.
The instructions (link below) are to place an image **_after_** the main element, but a moderator told them to put it _inside_ where there are two empty lines. The mod suggested that the instructions be improved and I report it on Github.

Whether the code is placed inside or outside the main element results in a pass.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/add-images-to-your-website

Here's the forum thread:
https://www.freecodecamp.org/forum/t/i-couldnt-get-through-uploading-an-image/340110/16

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 
Irrelevant

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@leebut @ArielLeslie  What about something like the following for the instructions section.
>Let's try to add an image to our website:
>
>Within the existing `main` element, insert an `img` element before the existing `p` elements.
>
>Now set the src attribute so that it points to the following url:
>
>https://bit.ly/fcc-relaxing-cat
>
>Finally, don't forget to give your `img` element an `alt` attribute with applicable text.

**Comment by leebut** [comment]
@RandellDawson, that is much clearer, thank you. Perhaps adding a  comment in the code like other challenges would also guide the learner to the correct location.
As it stands, the code passes no matter where the image is in relation to the `main` element. Should that be fixed so that it fails when the `img` element is misplaced?
