### ISSUE TITLE
Challenge markdown style

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#38043]
**Is your feature request related to a problem? Please describe.**
I noticed, when reviewing https://github.com/freeCodeCamp/freeCodeCamp/pull/38016, that a lot of HTML was necessary to create challenges that looked good (https://github.com/freeCodeCamp/freeCodeCamp/pull/38016/commits/7b9db261ca1db495e41f7a9c9c934e86a46f0679#diff-8d5114b548781516c78ac91bc507f8ebR14, for instance).  While using HTML inside challenge Markdown is occasionally necessary, when Markdown syntax can create that HTML it should be possible to use it.  

**Describe the solution you'd like**
I think tables and lists inside challenge descriptions and instructions should be styled nicely.  Then, a challenge author can simply use 

```
| col1 | col 2 |
|---|---|
|some text | some more text |
...
```
and get something nicely formatted (as you do here):

| col1 | col 2 |
|---|---|
|some text | some more text |

**Comment by scissorsneedfoodtoo** [comment]
Carrying on the conversation from https://github.com/freeCodeCamp/freeCodeCamp/pull/38016, the plan is to target tables in `.challenge-instructions` so those in `#description` and `#instructions` are styled.

I'll start working on a PR to update the markdown table styles and converts the HTML tables in the first 100 Project Euler problems to markdown.
