### ISSUE TITLE
URL Shortener Microservices Issues

### ISSUE THREAD

**Issue by bobmatyas** [freeCodeCamp/freeCodeCamp#38056]
Hi -

I was working on the "APIs and Microservices Projects - URL Shortener Microservice" project today and experienced difficulties getting the project to connect to the MongoLabs service used in this section of the curriculum.  

After a lot of digging, I eventually found out that the Mongoose version in the project boilerplate is out of date and doesn't connect with MongoLabs. The free tier requires a newer version of Mongoose.

It looks there is already a pull request out there to get this fixed:

https://github.com/freeCodeCamp/boilerplate-project-urlshortener/pull/15

It would be nice to see this get merged in as it caused a lot of issues while I was working on this project.

**Comment by scissorsneedfoodtoo** [comment]
Hi @bobmatyas, thank you for creating this issue. You're right that a lot of the backend and API projects need their dependencies updated. I'm in the process of going through these projects and overhauling what I can.

**Comment by bobmatyas** [comment]
@scissorsneedfoodtoo Awesome, I'm glad to hear it! Thanks for looking into it.

**Comment by scissorsneedfoodtoo** [comment]
@bobmatyas, thank you again for bringing this to our attention. We can close this now that https://github.com/freeCodeCamp/boilerplate-project-urlshortener/pull/15 was merged.
