### ISSUE TITLE
Email unsubscribe path is broken after yesterday's re-architecting

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#38051]
Normally people can unsubscribe from my weekly email by clicking the link at the bottom of the email. Here's what one of these unsubscribe links looks like: https://www.freecodecamp.org/ue/WQUiOp4cl1RKo4ieQ590J

**Comment by raisedadead** [comment]
I have managed to fix the page partially. But the client only route seems to be broken somehow. The API does respond by setting the key in the DB to false.

**Comment by raisedadead** [comment]
Fixed.
