### ISSUE TITLE
connecting MongoDB Atlas through MongoClient 

### ISSUE THREAD

**Issue by ahmad-ali14** [freeCodeCamp/freeCodeCamp#38064]
**Describe your problem and how to reproduce it:**
I see that in the instructions you saied that mongo.connect(url) will connect you to the db, actually I found that there sould be one more step in order the connection to perform correctly.

=================================
Here is some information:
When you are using MongoClient to connect to MongoDB Atlas,  it is important to know that there are 3 layers of connection.

1- connect to the cluster ..

```

mongo.connect(process.env.DATABASE_URL, (err, db) => {
  if(err) {
    console.log('Database error: ' + err);
  } else {
    console.log('Successful database connection');
  }
});

  
```

using the code above will not deliver you to the database, although you will not get any errors, you will find that your operations on the database-collection are not successful.
again, there is no errors in this connection, so you won't understand why your interaction with the DB is not successful.

2- connect to the database: 

```

//DB and authentication
mongo.connect(process.env.DATABASE, (err, cluster) => {
  if(err) {
    console.log('Database error: ' + err);
  } else {
    //connecting to the cluster
    console.log('Successful database connection');
    
    //connetcing to the database
    const db = cluster.db(DATABASE_NAME);
  }
    
 });

```
in the code above, the ``` connection.db() or cluster.db() ``` function -if you want to think of it this way- to connect us our database.

3- connect to  the collection :

```

//DB and authentication
mongo.connect(process.env.DATABASE_URL, (err, cluster) => {
  if(err) {
    console.log('Database error: ' + err);
  } else {
    //connecting to the cluster
    console.log('Successful database connection');
    
    //connetcing to the database
    const db = cluster.db(DATABASE_NAME);
   
   //conneting to the collection
   const coll = db.collection(COLLECTION_NAME);
 
   //do your stuff on the collection here.

  }
});


```

in the code above we reached our collection, so we can do our operations on it correctly.

===========================

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/information-security-and-quality-assurance/advanced-node-and-express/registration-of-new-users

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: windows

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Sky020** [comment]
I take it this is no longer valid, as the challenge has changed?

**Comment by ahmad-ali14** [comment]
@sky020 I didn't take a look at the new challenges but it's important to know that the connection is giving you a connection layer and then you need to reach the db from this connection object.
connection does not give you access to the db directly

**Comment by Sky020** [comment]
I agree, that is a crucial step. However, with regards to this issue, the lesson/challenge no longer mentions the db, and, in the projects, users are welcome to choose either the VanillaMongoDB route, or use Mongoosejs, as is taught in the curriculum. Mongoosejs does not have these steps to connect to the collection, as it is all done under the hood.

Essentially, I am suggesting this issue be closed.
