### ISSUE TITLE
url redirection doesn't work for /shop 

### ISSUE THREAD

**Issue by marcin93** [freeCodeCamp/freeCodeCamp#38069]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
When I'm looking into footer on main page (https://www.freecodecamp.org/) links has structure:
https://www.freecodecamp.org/news/about/
https://www.freecodecamp.org/news/shop/
https://www.freecodecamp.org/news/support/
switching to any other page within freecodecamp app will modify /shop link.

Also ./tools/scripts/build/create-redirects.js line 46:
```
/shop                                         #{{NEWS}}/shop 200
```
seems to be not working properly as hitting url: https://www.freecodecamp.org/shop/ will return 404

**To Reproduce**
1. Go to https://www.freecodecamp.org/
2. check link below 'Shop' available in a footer
3. change page to any other within main url eg.: 'About'
4.  check link below 'Shop' available in a footer link ill be different than previously

**Expected behavior**
Both 'Shop' links will remain the same.

**Comment by ahmadabdolsaheb** [comment]
Thanks for bringing this to our attention.
The redirect issues are going be handled with nginx in the next couple of days.

related #38079
