### ISSUE TITLE
All React & Redux Challenges Fail To Load Dependencies 

### ISSUE THREAD

**Issue by pjonp** [freeCodeCamp/freeCodeCamp#38060]
All React & Redux challenges are not loading React, ReactDOM, or Redux.

```
Refused` to load the script '<URL>' because it violates the following
Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'unsafe-inline'
<URL> <URL> <URL> <URL> <URL> <URL> <URL>". 
Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

Affects ALL React and Redux challenges:
[create-a-simple-jsx-element](https://www.freecodecamp.org/learn/front-end-libraries/react/create-a-simple-jsx-element)

![image](https://user-images.githubusercontent.com/25874668/72231149-c0386580-3587-11ea-868e-9b42caf28b8f.png)

Windows 10, Chrome [Version 79.0.3945.117 (Official Build) (64-bit)]

**Comment by pjonp** [comment]
Also seems to affect D3 challenges:

[add-document-elements-with-d3](https://www.freecodecamp.org/learn/data-visualization/data-visualization-with-d3/add-document-elements-with-d3)

![image](https://user-images.githubusercontent.com/25874668/72232024-a5b4bb00-358c-11ea-87d8-17a9f8edce49.png)

**Comment by scissorsneedfoodtoo** [comment]
Thank you for reporting this @pjonp. This is related to https://github.com/freeCodeCamp/freeCodeCamp/issues/38044 and we'll fix this ASAP.

**Comment by scissorsneedfoodtoo** [comment]
Updated the CSP on .dev and .org and tested these challenges in both Firefox and Chrome. Closing this for now, but please let us know if you run into any other issues.

**Comment by L4rryFisherman** [comment]
Experiencing the above error currently: `ReferenceError: React is not defined`

(OS x 12.4 Firefox 101.01 (64-bit) & Brave 1.39.111 (arm64)) 



<img width="1146" alt="Screenshot 2022-06-09 at 19 31 06" src="https://user-images.githubusercontent.com/99208478/172908728-5ebe8c5f-fc13-4343-9988-e54bf5912d92.png">
