### ISSUE TITLE
Minor UI issue

### ISSUE THREAD

**Issue by Madhur215** [freeCodeCamp/freeCodeCamp#38076]
There is a difference in the font size and the margin between the text , on the home page (freecodecamp.org) and the learn page (freecodecamp.org/learn). Although you may not notice it on first glance but it disturbs the UI. The "sign in and get started" button on home page is also wider 
than the "sign in to save your progress button" on /learn page.

**Comment by ojeytonwilliams** [comment]
Hi @Madhur215.  Could you add some screenshots that demonstrate the problem you're describing?

**Comment by DanielOhn** [comment]
Here are two screenshots from the landing and the /learn tab, before you're logged in.

![learn](https://user-images.githubusercontent.com/11139119/72580308-e23c2b80-3898-11ea-965e-fcd2d7cbeef6.png)
![landing page](https://user-images.githubusercontent.com/11139119/72580309-e23c2b80-3898-11ea-923e-061e0868c81e.png)

- There is a difference with the button width being stretched to fit the container in the landing page, but not on the /learn page.
- There is a minor difference in the margin right below the 'Welcome' Header between the two pages.

**Comment by Madhur215** [comment]
@ojeytonwilliams I was talking about the change in margin between "Welcome to freeCodeCamp.org"
and "Learn to code." on the lading page and the /learn page , and the width of the yellow Button on the two pages , as you can see in the screenshots shared by @DanielOhn

**Comment by ojeytonwilliams** [comment]
Thanks for clarifying, @DanielOhn and @Madhur215. I'll open this up for PRs.

**Comment by AshNaz87** [comment]
Implemented some changes. Please see screenshots
<img width="1280" alt="Screenshot 2020-01-19 at 09 59 13" src="https://user-images.githubusercontent.com/20570746/72678956-804f1200-3aa2-11ea-85d6-433a2ac5d8d7.png">
<img width="1280" alt="Screenshot 2020-01-19 at 09 59 31" src="https://user-images.githubusercontent.com/20570746/72678957-80e7a880-3aa2-11ea-9367-ed4b766f8043.png">
