### ISSUE TITLE
Challenge link broken when opening in new tab/window

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#38071]
The link in question
https://www.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/use-the-.env-file

Looks like this:
![page](https://user-images.githubusercontent.com/28780271/72396774-0d5e3800-373e-11ea-8d44-ab842139f713.jpg)

It works just fine if you click it from the challenge list from /learn. I'm guessing it is a route issue or something?

**Comment by Manish-Giri** [comment]
Looks like this behavior is present for some other links too -

- https://www.freecodecamp.org/learn/apis-and-microservices/managing-packages-with-npm/add-a-description-to-your-package.json
- https://www.freecodecamp.org/learn/apis-and-microservices/managing-packages-with-npm/add-keywords-to-your-package.json
- https://www.freecodecamp.org/learn/apis-and-microservices/managing-packages-with-npm/add-a-version-to-your-package.json

**Comment by ojeytonwilliams** [comment]
Yep, I think it's all links with `.`s in.  It's also not just .org, .dev has the problem too:
https://www.freecodecamp.dev/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-do...while-loops

**Comment by raisedadead** [comment]
This is because https://github.com/zeit/serve is unable to parse and get to the correct file. We could add NGINX maps in front of it, but I am not a huge fan of such a solution.

**Comment by raisedadead** [comment]
Here is the config if you are interested, but essentially serving the `www` directory where our client files (built) are dumped by the pipeline.

**Comment by ahmadabdolsaheb** [comment]
@raisedadead,  @ojeytonwilliams was able to fix it locally by making a serve.json file in the public directory using the config you shared above and serving it using zeit serve.

I am not sure where we are using the config to serve client on azure, but would it be possible that the config is not getting applied or it is getting overwritten?

**Comment by raisedadead** [comment]
> I am not sure where we are using the config to serve client on azure, but would it be possible that the config is not getting applied or it is getting overwritten?

You mean the VM, hosting the PM2 processes. Yes it has a config and it is version controlled as well.

**Comment by RandellDawson** [comment]
Any progess on this.  This is a huge bug.  When people post a link to these challenges on the forum, we can not go to the challenge.  Instead, we have to open up the learn site, find the curriculum section and  click on the challenge manually.

Thanks

**Comment by raisedadead** [comment]
> was able to fix it locally by making a serve.json file in the public directory using the config you shared above and serving it using zeit serve.

Please share the config.

**Comment by raisedadead** [comment]
Fix deployed to production.
