### ISSUE TITLE
Section Progress Bar is mistaken as project completeness

### ISSUE THREAD

**Issue by Ieahleen** [freeCodeCamp/freeCodeCamp#38078]
This is the last thread (there have been already a few others) of people that mistakes the section progress bar with completeness of the project

https://www.freecodecamp.org/forum/t/uploading-problem-with-the-2nd-project-of-responsive-design/341893

Maybe it needs to be a bit more clear
Or maybe once enough of the people that were in the middle of things when the progress bar has been introduced have gone forward it will not be brought up anymore...

**Comment by Ieahleen** [comment]
it has happened again:
[Why do I only get 94% completed?](https://www.freecodecamp.org/forum/t/why-do-i-only-get-94-completed/342239)

**Comment by moT01** [comment]
I think these will slowly go away once people figure it out.

We could try and enlarge the section text, maybe underline it - or put it in the progress bar.

**Comment by ojeytonwilliams** [comment]
One tiny change that might help is to put a colon after the section text.  So, it'll read

>Basic HTML and HTML5:
>5% complete

seeing the colon should help some people realise the two things are connected.

**Comment by thecodingaviator** [comment]
I don't really think it's an issue as such. 

> One tiny change that might help is to put a colon after the section text. So, it'll read
> 
> > Basic HTML and HTML5:
> > 5% complete
> 
> seeing the colon should help some people realise the two things are connected.

As far as what @ojeytonwilliams says, it is surely a way of doing this but IMHO it'll be too haphazard.
