### ISSUE TITLE
Improving the BFS and DFS challenges

### ISSUE THREAD

**Issue by Manish-Giri** [freeCodeCamp/freeCodeCamp#38070]
**Describe your problem and how to reproduce it:**

I think the challenges on BFS and DFS could use a little improvement. I noticed a few things - 

1. The GIF in BFS doesn't really explain what's going on. For someone completely new to BFS and queues, it would not be immediately clear what's happening on the queue. It would only appear that there is a nearest-nodes/adjacent-nodes first traversal occurring. For instance -

![68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f342f34362f416e696d617465645f4246532e676966](https://user-images.githubusercontent.com/11348778/72394349-e08d2f00-3703-11ea-9ed5-054f8aac6c01.gif)

The steps represented by the black and gray shades actually represent that first, the node/nodes shaded in gray get added to the queue. Then, you remove the current node at the front of the queue (enqueue), and for this node/nodes, add all its adjacent neighbors to the queue (steps marked in gray), and finally, visit the removed node (step marked in black). This is repeated until the queue is empty, or in case of this gif - all nodes are marked black.

As an example, the queue begins with `a`. Remove `a`, add its adjacent neighbors (`b` and `c`) to the queue, shaded in gray, and visit `a` (shaded in black). Repeat.

2. The instruction about the usage of `queue` is at the very end -
> Last, an important data structure that will help implement the breadth-first search algorithm is the queue... 

Ideally, this should be near the beginning, so users can visualize how to approach BFS. This would also tie in nicely with explanation of how a queue figures in the GIF (step 1).

3. The challenge on DFS doesn't mention about the usage of a Stack at all. Unless this was intentional and meant for the users to figure out themselves, we should probably add some description about how/why a Stack is helpful for DFS. 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/breadth-first-search
https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/depth-first-search

**Comment by naima-shk** [comment]
@Manish-Giri  Can i try this one ?

**Comment by naima-shk** [comment]
@RandellDawson  Can i try this one please? :)

**Comment by RandellDawson** [comment]
@naima-shk Sure.  Go ahead and create a PR.
