### ISSUE TITLE
'Code of Conduct' link in CONTRIBUTING.md leads to 404

### ISSUE THREAD

**Issue by andrewsmith289** [freeCodeCamp/freeCodeCamp#38079]
**Describe the bug**
The link to 'Code of Conduct' inside CONTRIBUTING.md leads to a 404

**To Reproduce**
1. Open CONTRIBUTING.md from the repository root
2. Click on the 'Code of Conduct' link
3. See the url leads to a 404 (https://www.freecodecamp.org/code-of-conduct)

**Expected behavior**
The 'Code of Conduct' page should appear.

**Desktop (please complete the following information):**
 - Mac OSx 10.15.2
 - Brave 1.2.42

**Comment by ahmadabdolsaheb** [comment]
related #38079
