### ISSUE TITLE
Add Explanation of Type Coercion to Falsy Bouncer

### ISSUE THREAD

**Issue by ltegman** [FreeCodeCamp/FreeCodeCamp#3808]
I see a lot of answers in the Gitter chat for [Falsy Bouncer](http://www.freecodecamp.com/challenges/bonfire-falsy-bouncer) that miss the point of the challenge and explicitly check for all falsy values individually. Perhaps it would be worth adding an explanation of type coercion or a relevant sidebar link to that challenge?

**Comment by natac13** [comment]
I am just curious on the questions that come up in chat. Are they about `==` vs `===`? I have just been reading through Kyle Simpsons' [You don't Know JS](https://github.com/getify/You-Dont-Know-JS) When he has a section on  [`ToBoolean`](https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch4.md#toboolean)  and [Explicit *-> boolean](https://github.com/getify/You-Dont-Know-JS/blob/master/types%20%26%20grammar/ch4.md#explicitly-----boolean) in the Coercion chapter. I was wondering if these could be used as the links you suggested as they have helped me better understand the concept

**Comment by ltegman** [comment]
The problems I've been seeing is that people don't realize that solution to the bonfire is not to explicitly check for each possible falsey value but to take advantage of boolean type coercion to solve the problem. The solution may not actually be to change this bonfire but to better prepare students for this in the waypoints leading up to it.

**Comment by Kasperelo** [comment]
I am at that bonfire right now, and my correct answer is not accepted. It says "remove all falsy values", but then I have to remove NaN, which in turn removes the strings, which need to be there! What a lousy exercise...

**Comment by ltegman** [comment]
@Kasperelo Please ask for assistance with this exercise in the [Help Chat](https://gitter.im/FreeCodeCamp/Help) or [Bonfire Help Chat](https://gitter.im/FreeCodeCamp/HelpBonfires) and if the many helpful people in there don't see a problem with your solution file a bug with a copy of the code that should be passing.

**Comment by jamigibbs** [comment]
@ltegman I agree with your point that it's far more efficient to solve it without explicitly check for all falsy values individually but at this learning stage, I think what's most important is to simply solve the problem. 

Perhaps an extra food for thought snippet would be helpful like:

> Think about how you can solve this without explicitly checking for all falsy values individually

Denying this solution in the test suite doesn't seem useful though.

**Comment by sleepyhead-km** [comment]
Hej,

very challenging bonfire... just finished it right now, but i wouldn't have solved this, if i hadn't read this thread a few minutes ago. boolean object isn't that hard, if you know how to use it, but it wasn't that obvious to me how i should use is to solve this bonfire. maybe it would be good to have a waypoint using Boolean() in some way, so the function isn't completely new at this point anymore.

**Comment by ltegman** [comment]
@jamigibbs I think that's a good suggestion. Doing something in the style of the `Hint` included in some of the new Basic Javascript challenges might be a good way to handle this. An example of what this should look like in the json for anyone looking to tackle this can be found at https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/seed/challenges/01-front-end-development-certification/basic-javascript.json#L59

**Comment by BerkeleyTrue** [comment]
Is this still an issue

**Comment by raisedadead** [comment]
Closing as stale.
