### ISSUE TITLE
Alalmany

### ISSUE THREAD

**Issue by hiphobnabil** [freeCodeCamp/freeCodeCamp#38087]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ojeytonwilliams** [comment]
Hi, there doesn't seem to be an issue here.  Please re-open it if there is a problem you wanted to report.
