### ISSUE TITLE
How Can I Use FreeCodeCamp Code for my self ?

### ISSUE THREAD

**Issue by E-RROR** [freeCodeCamp/freeCodeCamp#38083]
Hello Guys, im Fullstack developer with react and django and i want create an website and use freecodecamp frontend codes with my django codes;
i have a question
> Where is FreecodeCamp Challenges Saves and How to Use ?

**Comment by ahmadabdolsaheb** [comment]
Challenges are here https://github.com/freeCodeCamp/freeCodeCamp/tree/master/curriculum

You can learn about how all the pieces work together here: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md

I will go ahead and close this issue for now. Please reopen if you have more specific questions.
