### ISSUE TITLE
Bug "Wherefore art thou" Solution

### ISSUE THREAD

**Issue by damsalem** [freeCodeCamp/freeCodeCamp#38081]
The [suggested solution](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-wherefore-art-thou/16092) to the ["Wherefore art thou" challenge](e) has a bug or two in it.

1. Solution 2 is nested within the "Solution 1" `details > summary` elements (see screenshot)
2. Solution 1's code explanation is all commented out in Solution 2's code.

![Screenshot_2020-01-17 freeCodeCamp Challenge Guide Wherefore art thou](https://user-images.githubusercontent.com/43794460/72586718-c482bc80-38c0-11ea-898e-b325595563ad.png)

**Comment by RandellDawson** [comment]
@damsalem Thank you for pointing out the formatting issues with the solutions for this challenge.  I have corrected them now.
