### ISSUE TITLE
Legacy Method in Solution 2 "Challenge: Search and Replace"

### ISSUE THREAD

**Issue by damsalem** [freeCodeCamp/freeCodeCamp#38091]
The [suggested solution #2](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-search-and-replace/16045) in for the "Challenge: Search and Replace" uses the legacy `substr` method. While this has not yet been deprecated, it may be removed in the future [according to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr).

The following solution replaces `substr` with `slice` and uses a ternary operator instead of an `if else` statement for brevity.
```
function myReplace(str, before, after) {
  // Check if first character of argument "before" is a capital or lowercase letter and change the first character of argument "after" to match the case
  /^[A-Z]/.test(before) === true ?
    after = after[0].toUpperCase() + after.slice(1) :
    after = after[0].toLowerCase() + after.slice(1);

  // return string with argument "before" replaced by argument "after" (with correct case)
  return str.replace(before, after);
}
myReplace("A quick brown fox jumped over the lazy dog", "jumped", "leaped");
```
If you prefer the `if else` for readability, please see the following:
```
function myReplace(str, before, after) {
  // Check if first character of argument "before" is a capital or lowercase letter and change the first character of argument "after" to match the case
  if(/^[A-Z]/.test(before) === true){
    after = after[0].toUpperCase() + after.slice(1)
  } else {
    after = after[0].toLowerCase() + after.slice(1);
  }

  // return string with argument "before" replaced by argument "after" (with correct case)
  return str.replace(before, after);
}
myReplace("A quick brown fox jumped over the lazy dog", "jumped", "leaped");
```

[Link to Search and Replace challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/search-and-replace).
![Screenshot_2020-01-21 freeCodeCamp Challenge Guide Search and Replace](https://user-images.githubusercontent.com/43794460/72777221-e9d63a00-3be2-11ea-90c8-ce421d6bc851.png)

**Comment by Manish-Giri** [comment]
IMO, the explicit check for comparison with `true` can be bypassed -
`.test(before) === true ` -> `.test(before) ?`

**Comment by snigo** [comment]
What if I run this:
```
myReplace('His name is Tom', 'tom', 'john');
```

In my opinion if you presume case insensitivity for the second argument (`'john' => 'John'`), it implicitly must be applied for the first argument as well, isn't it?

**Comment by moT01** [comment]
I updated the solution to use `substring` instead of `substr` like mdn suggests.
