### ISSUE TITLE
Test case & instructions don't add up

### ISSUE THREAD

**Issue by eternal44** [FreeCodeCamp/FreeCodeCamp#3809]
The last test case doesn't match instructions.  Instructions call for strings less than 3 letters long to simply add the three dots and doesn't mention anything about only using the first letter.

Thanks!

Challenge [Bonfire: Truncate a string](http://freecodecamp.com/challenges/bonfire-truncate-a-string#?solution=function%20truncate(str%2C%20num)%20%7B%0A%20%20%2F%2F%20Clear%20out%20that%20junk%20in%20your%20trunk%0A%20%20if%20(str.length%20%3C%3D%20num)%0A%20%20%20%20return%20str%3B%0A%0A%20%20if%20(num%20%3C%3D%203)%0A%20%20%20%20return%20str.charAt(0)%20%2B%20%22...%22%3B%0A%20%20%0A%20%20return%20str.substr(0%2C%20num-3)%20%2B%20%22...%22%3B%20%0A%7D%0A%0A%0Atruncate(%22A-tisket%20a-tasket%20A%20green%20and%20yellow%20basket%22%2C%2011)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function truncate(str, num) {
  // Clear out that junk in your trunk
  if (str.length <= num)
    return str;

  if (num <= 3)
    return str.charAt(0) + "...";
  
  return str.substr(0, num-3) + "..."; 
}


truncate("A-tisket a-tasket A green and yellow basket", 11);

```

**Comment by ltegman** [comment]
It looks like the end of the instructions state "If the length of the string is less than or equal to 3 characters, then the length of the three dots is not added to the string length." What this means is that you don't have to remove extra characters to make room for the `"..."`. So when the target length is 1 you can just take that many characters from the string and add the `"..."` to the end.

Looks like the solution I put in the wiki isn't quite right though, so I will fix that up.

Closing as not an issue with the tests, but please feel free to comment if you have further concerns.

Thanks and happy coding!
