### ISSUE TITLE
The learning part not working on Ubuntu linus Chromu

### ISSUE THREAD

**Issue by SagirGarba** [freeCodeCamp/freeCodeCamp#38095]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
the Learning part is not working on Linus chromium browser, it keeps on saying "something is not quite right, a report have been generated and the freCodeCamp team have been notified. althought is working perfectly on windows chrome.

**Comment by ojeytonwilliams** [comment]
Hi, @SagirGarba, thanks for the report.  Could you give us more detail about which pages you see the problem on?  It would be a big help if you could take screenshots and include any console logs (if there are any).

**Comment by SagirGarba** [comment]
it has been showing this since last couple weeks. it is only the leaning part that is not working on my Ubuntu Linus, but the forum and news site are working perfectly. if i try login on windows/phone it will all work

![Screenshot from 2020-01-22 07-03-47](https://user-images.githubusercontent.com/51879687/72869546-f2fbff80-3ce5-11ea-9e04-4ec3ac40ade3.png)
![Screenshot from 2020-01-22 07-03-55](https://user-images.githubusercontent.com/51879687/72869554-f7c0b380-3ce5-11ea-91ae-bd12d053ea4e.png)

**Comment by ojeytonwilliams** [comment]
Thanks. Is there anything in the dev console?

**Comment by ojeytonwilliams** [comment]
Finally checked this myself and, yep, you can't sign in on Chromium.  Trying to sign in leaves you on https://api.freecodecamp.org/signin with the 502 error @SagirGarba showed above. Some sort of routing issue, I guess, but I have no idea why it's only Chromium.

I've checked Chrome, Brave and Firefox and none of them have the problem.

cc: @raisedadead

**Comment by scissorsneedfoodtoo** [comment]
Thank you for bringing this to our attention @SagirGarba, and for looking more into this @ojeytonwilliams.

Turns out this was a problem with the way NGINX handles really long SSO URLs with some browsers like Chromium. @ahmadabdolsaheb and I pushed a fix using the settings mentioned here: https://stackoverflow.com/questions/3704626/nginx-502-bad-gateway-error-only-in-firefox/3710649

@SagirGarba, could you try signing in again and let us know if you're still having issues?
