### ISSUE TITLE
TypeValue: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by rostaryms** [freeCodeCamp/freeCodeCamp#38096]
Hi,

I'm following along a udemy video tutorial and when I type 'npm run dev' into the command prompt I get the error below. Anyone know what's going on?

![JS_Error](https://user-images.githubusercontent.com/56840832/72833595-204c9d00-3c55-11ea-90e2-9a05b13e80e5.png)

**Comment by LarryHu0217** [comment]
Maybe add sudo before the command. I met the similar problem before.

**Comment by ojeytonwilliams** [comment]
Hi, this doesn't seem to be freeCodeCamp related, so I'm closing this.
