### ISSUE TITLE
All certification projects should show up on profile after cert claimed

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#38098]
It's currently possible to claim a certification without your certification projects not being public.

Whenever someone claims a certification, their certification project URLs should be publicly visible to reduce the ease with which someone can cheat. (We will catch cheaters eventually, but the faster the better.)

Certification project links should all be visible if they've claimed a certification (unless they've made their profile completely private, in which case the certification shouldn't show up on their profile, either).

![Profile___freeCodeCamp_org](https://user-images.githubusercontent.com/985197/72930242-214b0080-3d21-11ea-90df-79a74d2e2b17.png)

**Comment by RandellDawson** [comment]
@QuincyLarson On a related note, is there a way to query the database to find all users' projects used to claim certifications?  I have been thinking about a way to create a validation script that would go through each project url submitted and validate each user's projects pass the current tests.  Obviously, there is a cutoff date (you will need to tell me what that is) for projects that can be tested with the testable-projects test script.  My validation script would not attempt to test them.  

Anyway, if I can get this script working, then it could be modified to incorporate as part of the certificate claiming process.  Basically, once the user goes to claim a certification, the validation script would execute and return the results of each project test.  If any fail, then it would report back the results to the user and until all projects pass all the tests, the certificate would not be given.

**Comment by moT01** [comment]
Seems like a good way to test the projects already existing in the database @RandellDawson. But after that, I would think it would be best to test the projects when they get submitted and not when they claim a cert.

**Comment by moT01** [comment]
I'm trying to figure out what needs to be done here. Currently, the projects are all part of the `timeline`. So they will only be visible if that is public. Wondering if we want to leave it like that, or separate the projects into their own setting.

So without any separation of the projects... if someone goes to claim a cert -> check if timeline is public -> if not -> message "your timeline needs to be public to claim a cert" -> if so -> give them the cert. From there, if they try to make the timeline private -> give a warning "you cannot hide your timeline while your certs are public" - something like that anyway seems like it would work.

**Comment by moT01** [comment]
It looks like this feature has been added via @ShaunSHamilton's work [here](https://github.com/freeCodeCamp/freeCodeCamp/pull/40071). So I think we can safely close this. Thanks and happy coding 🎉 

If we want to continue discussion on any sort of project settings/visibility, I think a new issue would be best. If anyone disagrees, feel free to leave a comment and this can be reopened.
