### ISSUE TITLE
Bug - Regex: Check Grouping of Characters

### ISSUE THREAD

**Issue by alexnbuchanan** [freeCodeCamp/freeCodeCamp#38090]
**Describe your problem and how to reproduce it:**
I'm on the Regular Expressions: Check For Mixed Grouping of Characters. I was able to pass this checkpoint with a solution that doesn't meet the objectives of the assignment. I used the following code:

``` 
let myString = "Eleanor Roosevelt";
let myRegex = /(Franklin|Eleanor)? Roosevelt/; // Change this line
let result = myRegex.test(myString); // Change this line
```
With this code I match just “Roosevelt” which is only part of the name(s), yet I still pass the assignment. 

**Add a Link to the page with the problem:**
With this code I match just “Roosevelt” which is only part of the name(s) we are supposed to match for this assignment, yet I still pass the assignment. 

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 79.0.3945.117 (Official Build) (64-bit)
* Operating System: Windows 10 pro

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by AshNaz87** [comment]
@alexnbuchanan I think that the regex you've written should pass the test.

The `(Franklin|Eleanor)?` part is a capturing group, so the regex will match `Franklin` or `Eleanor`. The `?` as a quantifier will match the above 0 or 1 times.

This means that your regex will capture `Franklin Roosevelt` as well as `Eleanor Roosevelt`

Unless, I'm mistaken, I hope this helps :)

**Comment by AshNaz87** [comment]
Apologies...

Actually, I've re-read the instructions. I think you may be onto something.

**Comment by ojeytonwilliams** [comment]
Yeah, the problem is that it matches the string " Roosevelt".  A simple solution would be to add another test that makes sure it fails if you use, say, "Frank Roosevelt".

**Comment by AshNaz87** [comment]
@ojeytonwilliams Would like to have a crack at this

**Comment by RandellDawson** [comment]
@AshNaz87 Go ahead and create a PR.

**Comment by AshNaz87** [comment]
@ojeytonwilliams Had a go

Please see `#38097`
