### ISSUE TITLE
Broken Links in FCC news/about

### ISSUE THREAD

**Issue by andrescaroc** [freeCodeCamp/freeCodeCamp#38106]
**Describe the bug**
When you click the link, it doesn't load the expected page

**To Reproduce**
1. Go to https://www.freecodecamp.org/news/about/
2. Click on text 1: browse our alumni network on LinkedIn here.
or text 2: one of the hundreds of companies
3. Both url text, links to the same linkedIn page: https://www.linkedin.com/school/4831032/alumni/
4. LinkedIn sites open, but no page found.

**Expected behavior**
when you click both texts, it should go to https://www.linkedin.com/company/freecodecamp-alumni-network/people/ 

**Screenshots**
web page to reproduce the behavior:
![Captura de pantalla 2020-01-23 a la(s) 7 39 39 p  m](https://user-images.githubusercontent.com/38670654/73036058-3e162f80-3e18-11ea-9d00-c9bbb0e48d03.png)

reproduced: 
![Captura de pantalla 2020-01-23 a la(s) 7 37 03 p  m](https://user-images.githubusercontent.com/38670654/73035961-f2fc1c80-3e17-11ea-8a16-ece95b894713.png)

expected:
![Captura de pantalla 2020-01-23 a la(s) 7 37 14 p  m](https://user-images.githubusercontent.com/38670654/73035975-fdb6b180-3e17-11ea-937b-9ceec7e9a02d.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Browser: Chrome 
 - Version 79

**Smartphone (please complete the following information):**
 - Device: Xiaomi
 - OS: Android One]
 - Browser Firefox
 - Version 

**Additional context**
There is another broken link in the same page:
Page: https://www.freecodecamp.org/news/about/
url text: donor-supported public charity.
broken link: https://www.freecodecamp.org/news/donate/

Total broken links in https://www.freecodecamp.org/news/about/ = 3

**Comment by NhatTanVu** [comment]
Seems that some editor might need to edit those pages in news Ghost.

**Comment by RandellDawson** [comment]
@andrescaroc Are you sure the Alumni link should not be linking to https://www.linkedin.com/school/free-code-camp/people/?

**Comment by scissorsneedfoodtoo** [comment]
Thank you for reporting this @andrescaroc. I've gone ahead and updated those links in Ghost. As @RandellDawson mentioned, I believe that link should point to https://www.linkedin.com/school/free-code-camp/people/ like it does in the footer.

Cc @QuincyLarson to confirm that all these links are pointing to the correct pages.

**Comment by ahmadabdolsaheb** [comment]
I was not able to reproduce this.
I visited the about page editor and got the following links for the following texts.

companies
https://www.linkedin.com/school/free-code-camp/people/   

linkedin
 https://www.linkedin.com/school/free-code-camp/people/

There might have been changes since this issue was created.  could you please confirm that you still have this issue? if not please go ahead and close this accordingly.

**Comment by andrescaroc** [comment]
I have checked the links again and they work fine right now.

**Comment by QuincyLarson** [comment]
Note: There are two freeCodeCamp pages on LinkedIn - a tiny LinkedIn group (which I should probably delete because it's confusing) and a much larger alumni group here: https://www.linkedin.com/school/4831032

This https://www.linkedin.com/school/4831032 is what we should link to.

**Comment by QuincyLarson** [comment]
@scissorsneedfoodtoo Thanks for updating these links.
