### ISSUE TITLE
Freecodecamp.org not working on Chromium (linux browser) 

### ISSUE THREAD

**Issue by ggroshansii** [freeCodeCamp/freeCodeCamp#38103]
freecodecamp.org is not working on linux using the Chromium browser.  Chromium is the most popular browser on linux distributions and it would be great if FCC was available on it. Thank you for looking into this issue.

**Comment by RandellDawson** [comment]
Closing in favor of issue https://github.com/freeCodeCamp/freeCodeCamp/issues/38095.

@ggroshansii Feel free to add more details of what you mean by "not working" on the issue mentioned above.

Thank you.
