### ISSUE TITLE
Issues in "Jazz Up Your “ZSH” Terminal In Seven Steps — A Visual Guide"

### ISSUE THREAD

**Issue by Mashley1** [freeCodeCamp/freeCodeCamp#38104]
When trying to change to the homebrew version of zsh it would not allow me to do so until I had added /usr/local/bin/zsh to the /etc/shells file. I did this by using the command below.
<pre><code>sudo sh -c "echo $(which zsh) >> /etc/shells" && chsh -s $(which zsh)</pre></code>

Here is the page with the problem, https://www.freecodecamp.org/news/jazz-up-your-zsh-terminal-in-seven-steps-a-visual-guide-e81a8fd59a38/

* Browser Name: Firefox
* Browser Version: 72.0.2
* Operating System: macOS Catalina

I also found a typo, I think it should be <pre><code>source ~./zshrc</pre></code>, not <pre><code>source ~./zhrc</pre></code>

**Comment by RandellDawson** [comment]
@Mashley1 GitHub is for reporting issues with the actual freeCodeCamp.org site and not articles written by contributors.  Please contact the author of the article via the twitter link at the bottom of the article.

Thank you.

**Comment by Mashley1** [comment]
I tried to put this in the freecodecamps forum but got told that it was the wrong place and I had to do it here, now I am told this is the wrong place 😤😤 feels like I am on the phone to my insurance company 😂😂. I have no idea how to get in touch with the individual contributor as they seem to have no contact or email address in the site (or I can't find it anyway)

**Comment by RandellDawson** [comment]
@Mashley1 As I said in my previous reply, the author has a twitter link at the bottom of the article.  I would start there.

**Comment by Mashley1** [comment]
Would be easy if I had a Twitter account. Tried to help :/

**Comment by RandellDawson** [comment]
@Mashley1 I was able to make the change.  It appears the typo was on the original article published on Medium.

In the future, you should be able to make such a request under the [Contributors forum category](https://www.freecodecamp.org/forum/c/contributors/).  If anyone gives you trouble, you can tell them I said it was fine.

Thank you for helping to make the article better.

**Comment by Mashley1** [comment]
Thanks 👍
