### ISSUE TITLE
Bad redirection in Build a Product Landing Page

### ISSUE THREAD

**Issue by andrescaroc** [freeCodeCamp/freeCodeCamp#38112]
**Describe your problem and how to reproduce it:**
Go to: Responsive Web Design Certification 
Then: Responsive Web Design Projects
Then: Build a Product Landing Page
Find this: "User Story #12: When I click the #submit element, the email is submitted to a static page (use this mock URL: https://www.freecodecamp.com/email-submit) that confirms the email address was entered and that it posted successfully."
The mock URL is making a redirection to url: https://www.freecodecamp.org/news/email-submit/
The url throw error 404

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-product-landing-page

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 79
* Operating System: Mac OS 10.13.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Captura de pantalla 2020-01-24 a la(s) 3 19 27 p  m](https://user-images.githubusercontent.com/38670654/73101103-fa293600-3ebc-11ea-89a2-81cdb24a39be.png)

**Comment by RandellDawson** [comment]
@raisedadead Why is this trying to redirect to news?

**Comment by raisedadead** [comment]
@ahmadabdolsaheb @scissorsneedfoodtoo please investigate.

**Comment by scissorsneedfoodtoo** [comment]
This is interesting. http://www.freecodecamp.com redirects to https://www.freecodecamp.org correctly, but https://www.freecodecamp.com redirects to https://www.freecodecamp.org/news/ as @RandellDawson pointed out.

**Comment by scissorsneedfoodtoo** [comment]
@ahmadabdolsaheb and I updated the config to handle this earlier today. Both http://www.freecodecamp.com/email-submit and https://www.freecodecamp.com/email-submit should now redirect properly.

The only issue now is that .com URLs without www. or a sub domain do not redirect properly. So while https://www.freecodecamp.com/email-submit works, https://freecodecamp.com/email-submit does not.

We will continue to look into this and open another issue for better visibility.

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo Thanks for resolving this.  I have a slightly unrelated question regarding this project.  
> <strong>User Story #12:</strong> When I click the <code>#submit</code> element, the email is submitted to a static page (use this mock URL: <a href='https://www.freecodecamp.com/email-submit' target='_blank'>https://www.freecodecamp.com/email-submit</a>) that confirms the email address was entered and that it posted successfully.

Is it just me, or should we remove the last part of the last sentence (since the static link does does confirm anything?  What about rewording to the following?
> When I click the <code>#submit</code> element, the email is submitted to a static page (use this mock URL: <a href='https://www.freecodecamp.com/email-submit' target='_blank'>https://www.freecodecamp.com/email-submit</a>).

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, that looks much better, and also won't give the impression that we're testing whether or not any data actually gets sent to that URL. The way that user story currently reads it does seem like https://www.freecodecamp.com/email-submit is an API endpoint.

**Comment by RandellDawson** [comment]
I will create a PR.
