### ISSUE TITLE
Add REST, GraphQL, and RPC to curriculum?

### ISSUE THREAD

**Issue by brillout** [freeCodeCamp/freeCodeCamp#38111]
Hi!

API creation is something many beginner do wrong.

For example, nowadays, many default to GraphQL although creating ad-hoc express routes is most of the time just fine. GraphQL is nice and it's good to know about it but it shouldn't be the default choice.

There are many valuable lessons to teach in this area.

Would adding REST, GraphQL, and RPC to freeCodeCamp's curriculum be of interest?

**Comment by RandellDawson** [comment]
> Would adding REST, GraphQL, and RPC to freeCodeCamp's curriculum be of interest?

The current curriculum would not incorporate them, but the [next version of the curriculum (a project based approach)](https://github.com/freeCodeCamp/CurriculumExpansion), might want to have some of these types of projects.

Feel free to open an issue on the repo referenced above, to see if it gains any traction.

**Comment by brillout** [comment]
Oh, didn't know about it, thanks & I will.
