### ISSUE TITLE
Need help installing FCC locally on linux mint.

### ISSUE THREAD

**Issue by fmoya89** [freeCodeCamp/freeCodeCamp#38116]
Hello. I have been following the instructions to try and install FCC locally on my computer for offline use. I have downloaded all the prerequisites no problem. But I'm stuck at step 1 and have no clue what the directions are telling me to do. I'm pretty new to linux so that doesn't help. But this is the only machine available to me. Thank you for any support!

I tried following the Docker build install? and this is what I got. 

 npm run docker:run-once
npm ERR! Linux 5.0.0-37-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "docker:run-once"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /home/mycomputer/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/mycomputer/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/mycomputer/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mycomputer/npm-debug.log

**Comment by raisedadead** [comment]
Please reachout to [contributors chat room](https://gitter.im/FreeCodeCamp/Contributors). The awesome people their will sort you :)
