### ISSUE TITLE
unable to submit code

### ISSUE THREAD

**Issue by chethu6** [FreeCodeCamp/FreeCodeCamp#3811]
Challenge [Bonfire: Check for Palindromes](http://freecodecamp.com/challenges/bonfire-check-for-palindromes#?solution=function%20palindrome(str)%20%7B%0A%20%20str%20%3D%20str.toLowerCase()%3B%0A%20%20arr%3D%20str.split('')%3B%0A%20%20arr%20%3D%20arr.filter(function(val)%20%7B%0A%20%20%E2%80%89%E2%80%89return%20(val%20!%3D%20%22%20%22)%20%26%26%20(val%20!%3D%20%22.%22)%20%26%26%20(val%20!%3D%20%22%2C%22)%3B%0A%20%20%20%7D)%3B%0A%20%20l%20%3D%20arr.length%3B%0A%20%20l1%20%3DMath.floor(l%2F2)%3B%0A%20%20i%3D0%3B%0A%20%20j%3Dl-1%3B%0A%20%20while(j%20%3D%3E%200)%7B%0A%20%20%20%20%20%20%20%20if(arr%5Bi%5D%20!%3D%20arr%5Bj%5D)%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20r%20%3D%20false%3B%0A%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20r%20%3D%20true%3B%0A%20%20%20%20%20%20%20%20%20%20i%2B%2B%3B%0A%20%20%20%20%20%20%20%20%20%20j--%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%7D%0A%20%20return%20r%3B%0A%7D%0A%0A%0A%0Apalindrome(%22eye%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
when i click on run tests it is not responding 
My code:
```javascript
function palindrome(str) {
  str = str.toLowerCase();
  arr= str.split('');
  arr = arr.filter(function(val) {
    return (val != " ") && (val != ".") && (val != ",");
   });
  l = arr.length;
  l1 =Math.floor(l/2);
  i=0;
  j=l-1;
  while(j => 0){
        if(arr[i] != arr[j]){
            r = false;
        } else {
            r = true;
          i++;
          j--;
        }
  }
  return r;
}



palindrome("eye");

```

**Comment by soyginnie** [comment]
Try with this:
```
function palindrome(str) {
  str = str.toLowerCase().split('').filter(function(val) {
    return (val != " ") && (val != ".") && (val != ",");
   }).join("");
  var str2 = str.split('').reverse().join('');

  if(str == str2)
    return true;
  else
    return false;
}
```
Is easier if you keep working with *str* as a string.

**Comment by jlslew** [comment]
Your code takes too long to complete or contains an infinite loop.  `while(j => 0)` should be `while(j >= 0)`.
![](https://cloud.githubusercontent.com/assets/1538744/10596960/fe8a6e3e-76b7-11e5-98db-d403a7826691.png)

**Comment by BerkeleyTrue** [comment]
@jlslew Thanks for the quick response.

Happy Coding!
