### ISSUE TITLE
Forum hint/solution topics' challenge back links not working

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#38119]
I am not sure when it started, but all the back links to the challenges from the forum hints/solutions Guide topics, no longer work.  They all redirect to https://freecodecamp.org.  For example, go to [this topic](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-storing-values-with-the-assignment-operator/18310) and click on the top link titled **Storing Values with the Assignment Operator**.

**Comment by RandellDawson** [comment]
**Update:**  I was thinking there might be an outstanding issue for this already (but could not find one), but I also notice, you can no longer go directly to a challenge anymore regardless if you click from the forum or type in the url to the browser address bar.

**Comment by raisedadead** [comment]
Thanks for reporting, I have updated the config.

**Comment by xiaocheng-master** [comment]
it is great
