### ISSUE TITLE
broken link on readme

### ISSUE THREAD

**Issue by kerolloz** [freeCodeCamp/freeCodeCamp#38113]
academic honesty link in readme doesn't work and redirects to 404 page

**Comment by RandellDawson** [comment]
@raisedadead What should the correct link be for this?  The contributor made a PR to replace it to `https://www.freecodecamp.org/news/academic-honesty-policy/`, but why is this link under news?  Shouldn't it be under the main site?

**Comment by ahmadabdolsaheb** [comment]
@RandellDawson, all org pages have been moved the news. 
@kerolloz, thanks for bringing this to our attention.  This change should be handled from Nginx where we handle our redirects. I will take care of this at the beginning of the week.

**Comment by scissorsneedfoodtoo** [comment]
@kerolloz, thank you for catching this and for creating a PR. We decided to handle this with an NGINX redirect in case there are some other links that need to be updated. Going to https://www.freecodecamp.org/academic-honesty/ should now redirect to https://www.freecodecamp.org/news/academic-honesty-policy/.
