### ISSUE TITLE
Project Euler: Problem 2: Typo in formula

### ISSUE THREAD

**Issue by andrescaroc** [freeCodeCamp/freeCodeCamp#38117]
**Describe your problem and how to reproduce it:**
Go to: Project Euler: Problem 2: Even Fibonacci NumbersPassed Challenge
Then: Get help -> Get a hint
New browser tab is open at: https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-problem-2-even-fibonacci-numbers/301838
Find: "Problem Explanation"
Find:A fibonacci sequence is a sequence where fib(n) = fib(n-1) + fib(n-1).
Watch out the formula:  It should be: "where fib(n) = fib(n-1) + fib(n-**2**)."

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-problem-2-even-fibonacci-numbers/301838

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 79
* Operating System: Mac OS 10.13.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Captura de pantalla 2020-01-26 a la(s) 12 42 55 a  m](https://user-images.githubusercontent.com/38670654/73131229-3bad0480-3fd5-11ea-9f09-2d8f2d653f54.png)

**Comment by RandellDawson** [comment]
@andrescaroc Thank you for pointing out the typo.  I have since corrected the typo in that Guide solution.
