### ISSUE TITLE
Add support for British version of gray

### ISSUE THREAD

**Issue by snigo** [freeCodeCamp/freeCodeCamp#38123]
**Describe your problem and how to reproduce it:**
As per [this forum post](https://www.freecodecamp.org/forum/t/deaclaring-a-variable-in-css/344859) we need to add support for British `grey` in [Basic CSS: Create a custom CSS Variable](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/create-a-custom-css-variable) challenge as it's totally valid.

Also test regex might be slightly improved to ensure proper syntax:
```
/\.penguin\s*\{[^{}]*?--penguin-skin\s*:\s*gr[ae]y\s*;[^{}]*?\}/
```

**Comment by RandellDawson** [comment]
The instructions tell the user the value to accept, so there is no need to change the tests.

> In the penguin class, create a variable name --penguin-skin and give it a value of gray.

**Comment by moT01** [comment]
I agree with Randell, it explicitly says to use "gray" - what about the hex and rgb values of gray? I don't think we need accommodate for any of these when it says exactly what to use.

**Comment by ojeytonwilliams** [comment]
I'd say accept both values.  Someone using the British spelling hasn't misunderstood the challenge. They've taken the time to type an answer, rather than just copy-pasting.  Given that `grey` and `gray` are equivalent in this context, nothing of consequence changes.

**Comment by snigo** [comment]
Yes exactly, it’s not a matter of changing instructions, rather the matter of user experience in case they make this valid typo

**Comment by moT01** [comment]
I still don't think it's necessary, but I suppose there isn't any harm in it either. So I'm fine with it either way.

**Comment by RandellDawson** [comment]
@Manish-Giri @thecodingaviator Can we get your input here?  We have two for and two against allowing "grey" in the test.

**Comment by thecodingaviator** [comment]
Instead of checking for grey or gray why not check the rgb of the elements?

**Comment by LarryHu0217** [comment]
I can help this one. Do we need to change grey to gray?@RandellDawson

**Comment by RandellDawson** [comment]
@LarryHu0217 Nothing has been decided yet.  Still waiting on some other mods to chime in.

**Comment by ahmadabdolsaheb** [comment]
Although I agree with @RandellDawson and @moT01, it would not hurt to add gery to the test since some users are genuinely getting confused.

I'm fine with it either way.

**Comment by RandellDawson** [comment]
OK, someone go ahead and create a PR to allow either `grey` or `gray`.

**Comment by Pallof** [comment]
Is anyone currently working on this? If not, may I take a go at it?

**Comment by moT01** [comment]
Go for it @Pallof 👍

**Comment by deepgoonumich** [comment]
Me and my colleague @manrajtoor also worked on this for a school project. Should we submit a pull request still or is it too late?

**Comment by ojeytonwilliams** [comment]
Hi @deepgoonumich, the existing PR has already been accepted and will be merged once the code freeze is over.  So, yes, it's too late for this one!

There are some new issues with the help wanted label.  I would take a look at https://github.com/freeCodeCamp/freeCodeCamp/issues/38589 and https://github.com/freeCodeCamp/freeCodeCamp/issues/38606
