### ISSUE TITLE
freeCodeCamp Challenge Guide: Render HTML Elements to the DOM **** TYPO ***

### ISSUE THREAD

**Issue by geist-ahnen** [freeCodeCamp/freeCodeCamp#38129]
**Describe your problem and how to reproduce it:**
The freeCodeCamp Challenge Guide: Render HTML Elements to the DOM mentions the following method: 

Use the Document method getElementByID() to target a specfic node in the DOM

getElemtnByID should be spelled getElementById (lower d)

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-render-html-elements-to-the-dom/301406

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: latest version
* Operating System: Windows

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/18492002/73353571-eeaa8600-4293-11ea-8154-c6757277681c.png)

**Comment by AshNaz87** [comment]
@geist-ahnen Think this is an issue with the guide page and not the website itself

**Comment by RandellDawson** [comment]
@geist-ahnen Thanks for reporting the typo.  In the future, just create a topic under the `Contributors` category to report issues with the forum guide.  I have corrected the typo, so I am closing this issue.

Thank you.
