### ISSUE TITLE
Two identical challenges in Basic HTML and HTML5

### ISSUE THREAD

**Issue by snigo** [freeCodeCamp/freeCodeCamp#38121]
**Describe your problem and how to reproduce it:**

We have identical [Uncomment HTML](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/uncomment-html) and [Comment out HTML](https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/comment-out-html) one after another in Basic HTML and HTML5 section.

Screenshot:
<img width="577" alt="Screenshot 2020-01-27 at 01 24 38" src="https://user-images.githubusercontent.com/56631054/73144224-d542e780-40a3-11ea-9b16-1ecf5b61052f.png">

**Comment by RandellDawson** [comment]
The challenge instructions are different.  Also, the challenge seed is different.

**Comment by snigo** [comment]
Uncommenting 3 elements vs uncommenting 2 elements and leaving 1 commented looks extremely similar to me, clearly last one supersedes the first one.

Additionally, challenge seed should not start with `h1` and `p` elements already commented out as it contradicts the task

**Comment by moT01** [comment]
I don't think there's a problem here. A single challenge that is a little redundant isn't a big deal. I do think they could be better, but you could probably say the same for most of the challenges. Did you have something better in mind @snigo? I wouldn't be opposed if you wanted to improve them, but I don't think it's necessary.

**Comment by snigo** [comment]
No, I prefer to let it go... to advanced for me to improve :)
