### ISSUE TITLE
URLs Are All Forwarding to Homepage

### ISSUE THREAD

**Issue by AryanJ-NYC** [freeCodeCamp/freeCodeCamp#38122]
**Describe the bug**
I clicked https://www.freecodecamp.org/learn/front-end-libraries/front-end-libraries-projects/build-a-pomodoro-clock. I was brought to the freeCodeCamp homepage instead of the Pomodoro clock spec page.

**To Reproduce**
1. Click https://www.freecodecamp.org/learn/front-end-libraries/front-end-libraries-projects/build-a-pomodoro-clock
2. Realize you were redirected to the freeCodeCamp homepage

**Expected behavior**
Clicking on https://www.freecodecamp.org/learn/front-end-libraries/front-end-libraries-projects/build-a-pomodoro-clock (or any other address) should take you to the correct page.

**Screenshots**
I want to go to this page:
![Screen Shot 2020-01-26 at 9 32 41 PM](https://user-images.githubusercontent.com/8263430/73147021-74a3b280-4083-11ea-9811-5c7a7bc7714f.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Brave and Safari

**Comment by raisedadead** [comment]
Thanks for reporting. I have updated the config.
