### ISSUE TITLE
issue with sort method

### ISSUE THREAD

**Issue by chethu6** [FreeCodeCamp/FreeCodeCamp#3812]
Challenge [Bonfire: Find the Longest Word in a String](http://freecodecamp.com/challenges/bonfire-find-the-longest-word-in-a-string#?solution=function%20findLongestWord(str)%20%7B%0A%20%20arr%20%3D%20str.split('%20')%3B%0A%20%20var%20larr%20%3D%20%5B%5D%3B%0A%20%20for(i%20%3D%200%20%3Bi%20%3C%20arr.length%3Bi%2B%2B)%7B%0A%20%20%20%20str%20%3D%20arr%5Bi%5D%3B%0A%20%20%20%20larr%5Bi%5D%20%3D%20str.length%3B%0A%20%20%7D%0A%20%20%0A%20%20%2F%2Freturn%20larr%5Blarr.length-1%5D%3B%0A%20%20larr%20%3D%20larr.sort()%3B%0A%20%20return%20larr%3B%0A%7D%0A%0AfindLongestWord(%22What%20if%20we%20try%20a%20super-long%20word%20such%20as%20otorhinolaryngology%22)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.
when im sorting this array [4,2,2,3,1,10,4,4,2,19] it results [1,10,19,2,2,2,3,4,4,4]
![image](https://cloud.githubusercontent.com/assets/7278998/10596936/5c4404c8-7707-11e5-9bbe-de175bd1d430.png)

My code:
```javascript
function findLongestWord(str) {
  arr = str.split(' ');
  var larr = [];
  for(i = 0 ;i < arr.length;i++){
    str = arr[i];
    larr[i] = str.length;
  }
  
  //return larr[larr.length-1];
  larr = larr.sort();
  return larr;
}

findLongestWord("What if we try a super-long word such as otorhinolaryngology");

```

**Comment by jlslew** [comment]
This is normal behaviour, please read the docs; [Array.sort()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort).

**Comment by ltegman** [comment]
@jlslew is correct. You need to create a custom sorting function to do numerical sort as the default is alphabetical.

Closing as not an issue with the curriculum, but please feel free to reply if you have further questions.

Thanks and happy coding!

**Comment by chethu6** [comment]
Now I got it.Thank q guys.
