### ISSUE TITLE
Learn Sass: Use @if and @else to Add Logic To Your Styles (¿Broken test?)

### ISSUE THREAD

**Issue by andrescaroc** [freeCodeCamp/freeCodeCamp#38125]
**Describe your problem and how to reproduce it:**
Go to: https://www.freecodecamp.org/learn/front-end-libraries/sass/use-if-and-else-to-add-logic-to-your-styles

My code is the following:
`<style type='text/sass'>
  @mixin border-stroke ($val) {
    @if $val == light {
      border: 1px solid black;
    }
    @else if $val == medium {
      border: 3px solid black;
    }
    @else if $val == heavy {
      border:: 6px solid black;
    }
    @else {
      border: none;
    }
  }

  #box {
    width: 150px;
    height: 150px;
    background-color: red;
    @include border-stroke(heavy);
  }
</style>

<div id="box"></div>`

The automated test said my code didn't pass the 4th test:
// running tests
Your mixin should have an @else if statement to check if $val is heavy, and to set the border to 6px solid black.
// tests completed

But my code do have it, and the browser indeed styled the red square with a heavy border as expected

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/sass/use-if-and-else-to-add-logic-to-your-styles

**Tell us about your browser and operating system:**
* Browser Name: chrome
* Browser Version: 79
* Operating System: Mac OS 10.13.6

Also tested in firefox with the same result:
* Browser Name: Firefox
* Browser Version: 72.0.2 (64-bit)
* Operating System: Mac OS 10.13.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
In chrome:
![Captura de pantalla 2020-01-27 a la(s) 5 02 28 p  m](https://user-images.githubusercontent.com/38670654/73219409-09f98200-412a-11ea-8a4a-a1c516778c29.png)

In firefox:
![Captura de pantalla 2020-01-27 a la(s) 5 26 25 p  m](https://user-images.githubusercontent.com/38670654/73219477-38775d00-412a-11ea-91b3-9bcb78c5870b.png)

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

FYI - You have a typo that is causing your issue.
