### ISSUE TITLE
404 error when clicking on donation dashboard link on the support page

### ISSUE THREAD

**Issue by DimplePatel** [freeCodeCamp/freeCodeCamp#38139]
**Describe the bug**
There is a broken link which leads to a 404 page when clicking on the hyperlink on "a full guide to this donation dashboard" inside the the page titled "Common Technical Support Questions - freeCodeCamp FAQ".

**To Reproduce**
1. Go to https://www.freecodecamp.org/
2. Click on 'Support' in the footer
3. Click on the hyperlink under the text 'a full guide to this donation dashboard.'
4. Notice the 404 error you are taken to: https://www.freecodecamp.org/news/donation-settings/ 

**Expected behavior**
The user should be taken to a donation dashboard guide.

**Screenshots**
![Screenshot 2020-01-30 at 20 32 09](https://user-images.githubusercontent.com/6122821/73487784-9d87b880-439f-11ea-897d-624ee99aad92.png)

**Desktop (please complete the following information):**
 - OS: Apple MacOS 10.14.4
 - Browser Chrome
 - Version 79.0.3945.130

**Comment by ahmadabdolsaheb** [comment]
Thanks, we are working on the donation settings.
Meanwhile, we should add a redirect to address this until it is fixed.

**Comment by ahmadabdolsaheb** [comment]
@scissorsneedfoodtoo should we redirect this on directly on ghost?

**Comment by ahmadabdolsaheb** [comment]
or perhaps remove that sentence until  we get the donations settings back?

**Comment by scissorsneedfoodtoo** [comment]
Thank you for reporting this @DimplePatel.

It seems like @QuincyLarson already changed the wording on https://www.freecodecamp.org/news/support/ and removed that broken link. The text now reads: 

"Answer: Just forward one of your monthly donation receipts to team@freecodecamp.org and tell us what you'd like to update your donation or cancel it. We'll take care of this for you and send you confirmation." 

Also, https://www.freecodecamp.org/donation/settings redirects to https://www.freecodecamp.org/donate.

I think it's safe to close this for now. Please feel free to reopen this if you think it's still an issue.
