### ISSUE TITLE
Syntax Highlighter Issue

### ISSUE THREAD

**Issue by blakeburdpy** [freeCodeCamp/freeCodeCamp#38132]
Upon finishing the Beginning JavaScript tutorials and entering the ES6 tutorials, the Syntax Highlighter in Night mode was showing `var` names as black text making code snippets unreadable. The issue was resolved after turning Night mode off and then on again (yes, I know...).

As I thought to do this before I thought to take a screenshot, I have no proof of this behavior. If I am able to duplicate, I will update with screenshots and edits.

**Comment by RandellDawson** [comment]
Clear your browser's cache for the site and try again.

**Comment by raisedadead** [comment]
Thanks, I am closing this for now. Please feel free to post some screenshots here and we will re-open.
