### ISSUE TITLE
Steamroller challenge solution - 

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#38133]
The following solution is mentioned in the [hints/solutions page](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-steamroller/16079) for the [Steamroller challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/steamroller).

```javascript
function steamrollArray(arr) {
  while (arr.some(element => Array.isArray(element))) {
    arr = arr.flat();
  }
  return arr;
}
```

My question is, should we modify the instructions to state the `flat` method should not be used as it is not really much of an algorithm challenge once you use that method.  [Here is another challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/remove-whitespace-from-start-and-end), where we do not let them use the `trim`, method to make the user "think" a bit more.

If it is agreed we should make this change, then we need to add a test to validate the solution does not use the `flat` method.

**Comment by RandellDawson** [comment]
The following solution is mentioned in the [hints/solutions page](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-steamroller/16079) for the [Steamroller challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/steamroller).

```javascript
function steamrollArray(arr) {
  while (arr.some(element => Array.isArray(element))) {
    arr = arr.flat();
  }
  return arr;
}
```

My question is, should we modify the instructions to state the `flat` method should not be used as it is not really much of an algorithm challenge once you use that method.  [Here is another challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/remove-whitespace-from-start-and-end), where we do not let them use the `trim`, method to make the user "think" a bit more.

If it is agreed we should make this change, then we need to add a test to validate the solution does not use the `flat` method.

**Comment by RandellDawson** [comment]
@ojeytonwilliams @moT01 @thecodingaviator @Manish-Giri @ArielLeslie Would be great to have some feedback about my proposal.

**Comment by ArielLeslie** [comment]
I agree that the point of this challenge is defeated by using `flat()`.

**Comment by ojeytonwilliams** [comment]
I agree too. As for the validation, looking for `.flat(` should suffice, if we say "solutions must not use `Array.prototype.flat()`".

**Comment by thecodingaviator** [comment]
+1 to @ojeytonwilliams and @ArielLeslie

**Comment by RandellDawson** [comment]
OK, anyone want to work on this one?  Just let us know.

**Comment by hassaanp** [comment]
> OK, anyone want to work on this one? Just let us know.

Hi,

I would like to take this up.

From what I understand, the scope for this issue is:

1. Add a test to check if the `flat` method was used
2. Change the hint/solution to be more appropriate

Let me know if my understanding is correct.

**Comment by RandellDawson** [comment]
@hassaanp All you would need to do is:

1. Add a test to check if the `flat` or `flatmap` method was NOT used.
2. Change the instructions to indicate the `flat` and `flatmap` are not to be used.

Someone else will take care of removing the solutions on the forum that use the two methods.

**Comment by hassaanp** [comment]
@RandellDawson acknowledged.

Working on a fix.
