### ISSUE TITLE
Tests running after navigating away from challenge

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#38135]
**Describe the bug**
Test continue running after the user has left the challenge

**To Reproduce**
1. Go to https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/find-the-symmetric-difference (any js challenge will do, but this one makes it obvious since it has many tests)
2. Enter
```js
for (let i = 0; i < 100000000; i++) {

}
```
3. Click 'Run the Tests'
4. Navigate to any other challenge (click on /learn, then navigate via the curriculum tree)
5. See the test results in the new challenge's console

**Expected behavior**
The tests should be terminated, without console feedback, when the user leaves the challenge.  

**Screenshots**
![TestsContinuing](https://user-images.githubusercontent.com/15801806/73453791-0d308000-436d-11ea-932c-640a6eda7891.gif)

**Comment by vanya829** [comment]
@ojeytonwilliams Hi. I'd like to get this one to fix.

**Comment by ahmadabdolsaheb** [comment]
@vanya829, please go ahead with proposing a solution or submitting a pr.
