### ISSUE TITLE
Intermittant CSP problem

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#38147]
**Describe the bug**
Occasionally I see what looks to be a CSP error in the console:
>(index):1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://js.stripe.com') does not match the recipient window's origin ('https://www.freecodecamp.org').
rn @ (index):1
value @ (index):1
value @ (index):1
value @ (index):1
value @ (index):1
r @ (index):1

**To Reproduce**
As yet, I'm not sure, sorry!  I've seen it a few times, but not consistently.  When I encountered it most recently I was [here](https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/find-the-symmetric-difference).

**Comment by ahmadabdolsaheb** [comment]
I can confirm that stripe loads on modal and donate page on producttion

**Comment by ahmadabdolsaheb** [comment]
has this been resolved?

**Comment by ojeytonwilliams** [comment]
I'm not sure, since I never knew what caused it.  However, no one else seems to have have plus oned, so I guess it's not a problem.
