### ISSUE TITLE
404 error when clicking prototype link for Javascript example

### ISSUE THREAD

**Issue by DimplePatel** [freeCodeCamp/freeCodeCamp#38140]
**Describe the bug**
A prototype link leads to a 404 error on the Javascript example page 

**To Reproduce**
1. Go to https://www.freecodecamp.org/news/javascript-example/
2. Click on the 'prototypes' hyperlink under the section 'JavaScript Class Example'
3. The user is taken to a 404 error page: 
https://guide.freecodecamp.org/src/pages/javascript/prototypes/index.md

**Expected behavior**
The user is taken to a page on prototypes.

**Screenshots**
![Screenshot 2020-01-30 at 20 43 46](https://user-images.githubusercontent.com/6122821/73488674-4256c580-43a1-11ea-8891-12f02195e614.png)

**Desktop (please complete the following information):**

- OS: Apple MacOS 10.14.4
- Browser Chrome
- Version 79.0.3945.130

**Comment by ahmadabdolsaheb** [comment]
I changed the article to point to a working link.
Any idea why this is not working? @scissorsneedfoodtoo

**Comment by piankot** [comment]
Was checking the same page and found that the hyperlink for "this reference in javascript" under the JavaScript Prototype example is giving the same error now but for https://guide.freecodecamp.org/src/pages/javascript/this-reference/index.md  instead.

**Comment by weiranwang99** [comment]
I followed the instruction of the bug and clicked on the prototype link. It shows the right page. Is this fixed?

**Comment by fatengh** [comment]
i think it is fixed

**Comment by DimplePatel** [comment]
I have rechecked this and I can confirm it's fixed

**Comment by RandellDawson** [comment]
@raisedadead I closed this issue, because the link does appear to work now.  Should it remain open for another reason?
