### ISSUE TITLE
Project Euler: Problem 31: Coin sums should modify question so that the input is in pennies

### ISSUE THREAD

**Issue by victorWeiFreelancer** [freeCodeCamp/freeCodeCamp#38143]
**Describe your problem and how to reproduce it:**
For Project Euler Problem 31
The questions asks "How many different ways can £(n) be made using any number of coins?" but the automated tests actually expect input n in pennies

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-31-coin-sums

**Tell us about your browser and operating system:**
* Browser Name: Chrome 
* Browser Version: 79.0.3945.130 (Official Build) (64-bit)
* Operating System: MacOS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ojeytonwilliams** [comment]
Thanks for reporting this, it definitely should be pennies.  PRs are welcome.
