### ISSUE TITLE
404 error when clicking on reference link on JavaScript example

### ISSUE THREAD

**Issue by LarryHu0217** [freeCodeCamp/freeCodeCamp#38148]
**Describe the bug**
This is a broken website page when clicking on the hyper line on "this reference in JavaScript"
 this donation dashboard" inside the the page titled "Common Technical Support Questions - freeCodeCamp FAQ".

**To Reproduce**
To Reproduce

1. Go to https://www.freecodecamp.org/news/javascript-example/
2. Find there is a JavaScript Prototype Example section 
2. Click on the hyperlink on  the text 'this reference in JavaScript'.
3. Notice the 404 error you are taken to:https://guide.freecodecamp.org/src/pages/javascript/this-reference/index.md

**Expected behavior**

**Screenshots**

<img width="1138" alt="截屏2020-01-30下午4 46 13" src="https://user-images.githubusercontent.com/35699841/73568697-f2c2d900-4436-11ea-86e3-b7021d029197.png">

**Desktop (please complete the following information):**
 - OS:iOS
 - Browser:chrome 

**Additional context**

**Comment by raisedadead** [comment]
The link was old and we have since updated the article.

**Comment by scissorsneedfoodtoo** [comment]
I believe this is still an issue, and the link @LarryHu0217 mentioned still points to a Guide article that 404s.

I started the process of porting that article to News. Once it's approved and live, I'll update the link in the https://www.freecodecamp.org/news/javascript-example/ article.

**Comment by scissorsneedfoodtoo** [comment]
We just ported over the original guide article mentioned above. Now the previously broken link points to https://www.freecodecamp.org/news/the-complete-guide-to-this-in-javascript/.

Thanks again for reporting this @LarryHu0217.
