### ISSUE TITLE
Font misalignment on intro to managing npm packages

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#38156]
<img width="682" alt="Screen Shot 2020-02-03 at 7 30 48 PM" src="https://user-images.githubusercontent.com/20648924/73706284-ae953a00-46bd-11ea-96bd-0c571709edff.png">

For some reason, the font changes halfway down this introduction. [The file is here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/pages/learn/apis-and-microservices/managing-packages-with-npm/index.md). I don't see the problem at first glance. Probably just a spacing issue or something.

**Comment by vanya829** [comment]
Hi @moT01 . It looks like the problem caused by HTML tags in the text. I removed them and it looks better. Please check PR.
