### ISSUE TITLE
404 error when clicking podcast link on About page

### ISSUE THREAD

**Issue by DimplePatel** [freeCodeCamp/freeCodeCamp#38167]
**Describe the bug**
When clicking the podcast hyperlink on the About page, it leads to a 404 error.

**To Reproduce**
1. Go to https://www.freecodecamp.org/news/about/
2. Click on the hyperlink 'freeCodeCamp Podcast'
3. Notice the 404 error at https://podcast.freecodecamp.org/ 

**Expected behavior**
The hyperlink should lead to the podcast page. Not sure if this is the correct link? https://freecodecamp.libsyn.com/ 

**Screenshots**
<img width="1437" alt="Screenshot 2020-02-05 at 17 19 21" src="https://user-images.githubusercontent.com/6122821/73865877-d9a59800-483b-11ea-9d9f-9e5abe7d3912.png">

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.6
 - Browser Chrome
 - Version 79.0.3945.130

**Comment by Pranav2612000** [comment]
@DimplePatel Couldn't reproduce the issue. Which hyperlink are you referring to?
The one in 

> Does freeCodeCamp have a mobile app?
> You can learn on the go by listening to the freeCodeCamp Podcast or watching freeCodeCamp's YouTube channel. And if you want a mobile app designed specifically for learning to code, we recommend Grasshopper. It's free and designed by a freeCodeCamp contributor and her team. You can download it on iOS or Android.
redirect me correctly.

**Comment by Pranav2612000** [comment]
@DimplePatel Couldn't reproduce the issue. Which hyperlink are you referring to?
The one in

> Does freeCodeCamp have a mobile app?
> You can learn on the go by listening to the freeCodeCamp Podcast or watching freeCodeCamp's YouTube channel. And if you want a mobile app designed specifically for learning to code, we recommend Grasshopper. It's free and designed by a freeCodeCamp contributor and her team. You can download it on iOS or Android.

redirect me correctly.

**Comment by DimplePatel** [comment]
The one under the title "Does freeCodeCamp have a mobile app?"

**Comment by weiranwang99** [comment]
I clicked on the one under the title, but it doesn't show up. Is this still an issue?

**Comment by Pranav2612000** [comment]
> The one under the title "Does freeCodeCamp have a mobile app?"

The same link worked fine for me too.

**Comment by DimplePatel** [comment]
Closing the issue because link is now working for me
