### ISSUE TITLE
Challenge [Waypoint: Line up Form Elements Responsively with Bootstrap] - Solution URL causing browser failures in bug submission

### ISSUE THREAD

**Issue by trs4ece** [FreeCodeCamp/FreeCodeCamp#3816]
Challenge [Waypoint: Line up Form Elements Responsively with Bootstrap](freecodecamp.com/challenges/waypoint-line-up-form-elements-responsively-with-bootstrap#?solution=<link href%3D"http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster" rel%3D"stylesheet" type%3D"text%2Fcss">%0A<style>%0A  h2 {%0A    font-family%3A Lobster%2C Monospace%3B%0A  }%0A%0A  .thick-green-border {%0A    border-color%3A green%3B%0A    border-width%3A 10px%3B%0A    border-style%3A solid%3B%0A    border-radius%3A 50%25%3B%0A  }%0A%0A<%2Fstyle>%0A%0A<div class%3D"container-fluid">%0A  <div class%3D"row">%0A    <div class%3D"col-xs-8">%0A      <h2 class%3D"text-primary text-center">CatPhotoApp<%2Fh2>%0A    <%2Fdiv>%0A    <div class%3D"col-xs-4">%0A      <a href%3D"%23"><img class%3D"img-responsive thick-green-border" src%3D"https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat"><%2Fa>%0A    <%2Fdiv>%0A  <%2Fdiv>%0A  <img src%3D"http%3A%2F%2Fbit.ly%2Ffcc-running-cats" class%3D"img-responsive">%0A  <div class%3D"row">%0A    <div class%3D"col-xs-4">%0A      <button class%3D"btn btn-block btn-primary"><i class%3D"fa fa-thumbs-up"><%2Fi> Like<%2Fbutton>%0A    <%2Fdiv>%0A    <div class%3D"col-xs-4">%0A      <button class%3D"btn btn-block btn-info"><i class%3D"fa fa-info-circle"><%2Fi> Info<%2Fbutton>%0A    <%2Fdiv>%0A    <div class%3D"col-xs-4">%0A      <button class%3D"btn btn-block btn-danger"><i class%3D"fa fa-trash"><%2Fi> Delete<%2Fbutton>%0A    <%2Fdiv>%0A  <%2Fdiv>%0A  <p>Things cats <span class%3D"text-danger">love%3A<%2Fspan><%2Fp>%0A  <ul>%0A    <li>cat nip<%2Fli>%0A    <li>laser pointers<%2Fli>%0A    <li>lasagna<%2Fli>%0A  <%2Ful>%0A  <p>Top 3 things cats hate%3A<%2Fp>%0A  <ol>%0A    <li>flea treatment<%2Fli>%0A    <li>thunder<%2Fli>%0A    <li>other cats<%2Fli>%0A  <%2Fol>%0A  <form fccfaa%3D"%2Fsubmit-cat-photo">%0A    <div class%3D"row">%0A      <div class%3D"col-xs-6">%0A        <label><input type%3D"radio" name%3D"indoor-outdoor"> Indoor<%2Flabel>%0A      <%2Fdiv>%0A      <div class%3D"col-xs-6">%0A        <label><input type%3D"radio" name%3D"indoor-outdoor"> Outdoor<%2Flabel>%0A      <%2Fdiv>%0A    <%2Fdiv>%0A    <div class%3D"row">%0A      <div class%3D"col-xs-4">%0A        <label><input type%3D"checkbox" name%3D"personality"> Loving<%2Flabel>%0A      <%2Fdiv>%0A      <div class%3D"col-xs-4">%0A        <label><input type%3D"checkbox" name%3D"personality"> Lazy<%2Flabel>%0A      <%2Fdiv>%0A      <div class%3D"col-xs-4">%0A        <label><input type%3D"checkbox" name%3D"personality"> Crazy<%2Flabel>%0A      <%2Fdiv>%0A    <%2Fdiv>%0A    <div class%3D"row">%0A    <div class%3D"col-xs-7"><input type%3D"text" class%3D"form-control" placeholder%3D"cat photo URL" required><%2Fdiv>%0A    <div class%3D"col-xs-5"><button type%3D"submit" class%3D"btn btn-primary"><i class%3D"fa fa-paper-plane"><%2Fi> Submit<%2Fbutton><%2Fdiv>%0A    <%2Fdiv>%0A  <%2Fform>%0A<%2Fdiv>%0A)

When attempting to create a new bug from this challenge, both Firefox (41.0) and Internet Explorer (11.0) fail. Firefox throws a "414 Request-URI Too Large" error and Internet Explorer throws a "Internet Explorer has modified this page to help prevent cross-site scripting." error and replaces the page with a #.

**Comment by patsul12** [comment]
So this seems to happen because there is a limit that most web servers use when accepting a url of 10kb. I took the url generated by FreeCodeCamp and it clocked in at 10.2kb. If you run the html through a html minimizer and then request a bug report it goes through fine. I personally don't have a solution for this but it would seem there needs to be some sort of shortening happening on the links being passed to github.

**Comment by bugron** [comment]
@trs4ece thanks for posting. Not sure if we can do anything with this right now so I'll close this issue.
