### ISSUE TITLE
404 error for IEEE link on Python Example page

### ISSUE THREAD

**Issue by DimplePatel** [freeCodeCamp/freeCodeCamp#38168]
**Describe the bug**
When clicking the hyperlink "IEEE site" on the Python Example page, the user is taken to a 404 error. 

**To Reproduce**
1. Go to https://www.freecodecamp.org/news/python-example/
2. Click on the hyperlink 'IEEE site'
3. You are taken to a 404 error on the IEEE website: http://grouper.ieee.org/groups/754/ 

**Expected behavior**
The user is taken to a page regarding IEEE 754 specification: Standard for Binary Floating-Point Arithmetic. Not sure if this is now the current link: http://grouper.ieee.org/groups/msc/ANSI_IEEE-Std-754-2019/background/ieee-computer.pdf 

**Screenshots**

<img width="1417" alt="Screenshot 2020-02-05 at 17 22 00" src="https://user-images.githubusercontent.com/6122821/73866240-6cdecd80-483c-11ea-94db-a3c60c8d507b.png">

Desktop (please complete the following information):

OS: Mac OS X 10.14.6
Browser Chrome
Version 79.0.3945.130

**Comment by RandellDawson** [comment]
Maybe use the following Wikipedia link?

> https://en.wikipedia.org/wiki/IEEE_754

**Comment by QuincyLarson** [comment]
@DimplePatel Thanks for catching this. I've fixed this.

@RandellDawson I've used your recommended wikipedia link.
