### ISSUE TITLE
Tests Failing: Data Visualization with D3: Change Styles Based on Data

### ISSUE THREAD

**Issue by hchiam** [freeCodeCamp/freeCodeCamp#38162]
https://www.freecodecamp.org/learn/data-visualization/data-visualization-with-d3/change-styles-based-on-data

"The first h2 should have a color of red."

My solution matches the hints, but I think the test is not there/working?

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
