### ISSUE TITLE
UI Jittering when scrolling

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#38163]
**Describe the bug**
Whilst on the forum, using the dark-beta theme, the UI on the page jumps side to side, either when stationary on a specific point, or when scrolling past certain elements.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the forum. Use the beta-theme
2. Click on any post.
3. Scroll up and down using trackpad
4. See GIF

**Expected behaviour**
Obviously, this should not happen, but I wonder if there is some media query doing this, or if a component is being rendered incorrectly.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 79

![fCC-Forum-Bug](https://user-images.githubusercontent.com/51722130/73785681-aefe0580-478f-11ea-87f1-46343f1b8acb.gif)

**Comment by moT01** [comment]
That little `3/3` with the wrench that is flashing at the beginning of the gif keeps switching from that to the built in vertical scroll bar that shows the same `3/3` that you can see later in the gif. It happens at a specific width or something and the vertical bar is off the page causing the horizontal scroll bar to show up and disappear.

**Comment by ahmadabdolsaheb** [comment]
Thanks for submitting this issue @Sky020,

There is a similar behavior with the default theme. When the desktop UI loads and width changes, the vertical progress bar stays out of view. This is more apparent on the new theme since icons have been replaced with text and the buttons are wider.
 
I think this would be a none-issue since for that width discourse would not load the vertical scrollbar at all when it detects a tablet or a mobile.

Please see if you have the same issue after toggling the device toolbar or visiting that page with a tablet.
If not, feel free to close this issue.

**Comment by Sky020** [comment]
@ahmadabdolsaheb The GIF was not all that clear, but the issue is not so much with the blinking 3/3, but when I am scrolling through topics.
When I scroll (at a reasonable speed), the page jumps, causing me to scroll less than I am trying. This only happens with the beta themes. I showed the 3/3 flashing, because I thought it was connected.

Some of my hypotheses:
1) When scrolling past new posts, a request is sent to confirm that the post has been read. This could cause the window to refresh (wrong word).
- This is doubtful, because it occurs in posts I have already read.
2) Potentially, this is something that occurs only/more when fCC Forum is under high load. Maybe multiple users on the same post??
- I do not know why, but I am unable to reproduce the issue at certain times.

I hope that makes it more clear. I have considered the issue being my laptop/browser, but am unable to confirm/deny, and am unable to think of why this would be the cause.

Thank you, for your time in all of this.

**Comment by ahmadabdolsaheb** [comment]
I was not able to reproduce this. Let's keep this open and see if other users are experiencing this issue.

**Comment by Sky020** [comment]
Since the beta themes were merged, I have not been able to reproduce it either. I would close this issue. If someone reopens it, or creates a similar one, then we will just need to remember.

Thank you, for your help
