### ISSUE TITLE
Broken link on Redux Challenge Intro Page

### ISSUE THREAD

**Issue by andrescaroc** [freeCodeCamp/freeCodeCamp#38171]
**Describe your problem and how to reproduce it:**

**1) Go to:** https://www.freecodecamp.org/learn/front-end-libraries/redux/

**2) Find this text:** "Improve this intro on GitHub."

**3)** Link to GitHub to improve the intro is broken

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/redux/

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 79
* Operating System: Mac OS 10.13.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Captura de pantalla 2020-02-05 a la(s) 11 07 52 p  m](https://user-images.githubusercontent.com/38670654/73905179-72eca280-486c-11ea-8c60-0633bc814595.png)
![Captura de pantalla 2020-02-05 a la(s) 11 08 06 p  m](https://user-images.githubusercontent.com/38670654/73905189-797b1a00-486c-11ea-97b8-95762a5bd42d.png)

**Comment by RandellDawson** [comment]
I am not even sure why that last sentence is present.  I think it is best if it is removed completely from the introduction.  If you see anymore links like this, please add them to this issue, so someone can create a PR to fix them all at the same time.

**Comment by moT01** [comment]
What do you think about removing the link to the redux website @RandellDawson? (the first word in the intro)

**Comment by RandellDawson** [comment]
@moT01 I think for now, we can leave it alone.  I think the discussion of external links should be on a separate issue (if there is not already an outstanding issue).  I thought I had an open issue at one point about external links.  It may have gotten closed at some point (can't remember why).

**Comment by andrescaroc** [comment]
> If you see anymore links like this, please add them to this issue, so someone can create a PR to fix them all at the same time.

Hey guys, the same issue is happening in the React and Redux section, please check: https://www.freecodecamp.org/learn/front-end-libraries/react-and-redux/
