### ISSUE TITLE
Refreshing page when on forum loads freeCodeCamp.org instead of the forum

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#38177]
The title says it all.  Goto the forum and then refresh your page.  Instead of reloading the forum, the main freecodecamp.org site loads.

**Comment by raisedadead** [comment]
This is a known issue after a recent discourse issue, unfortunately this is not an easy fix and we are investigating without any ETA on the resolution unfortunately.
