### ISSUE TITLE
Unclear test output - use-array.map-to-dynamically-render-elements

### ISSUE THREAD

**Issue by andrescaroc** [freeCodeCamp/freeCodeCamp#38170]
**Describe your problem and how to reproduce it:**

**1) Go to:** https://www.freecodecamp.org/learn/front-end-libraries/react/use-array.map-to-dynamically-render-elements
**2) Then:** look for the third expected test output on the left-bottom UI of the challenge.

**3) What it says:** 

> The third child of MyToDoList should be a button element.

**4) what it should says:**

> The second child of MyToDoList should be a button element.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/react/use-array.map-to-dynamically-render-elements

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 79
* Operating System: Mac OS 10.13.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Captura-de-pantalla-2020-02-05-a-la(s)-10 59 39-p -m](https://user-images.githubusercontent.com/38670654/73904936-a0851c00-486b-11ea-9608-bc5066b7485b.jpg)

**Comment by ojeytonwilliams** [comment]
Thanks for the report, but the second child is `<br />`, so the test is correct.  I think this would be clearer if the `<br />` was alone on a separate line, so I can see a case for changing the seed to make this clearer.

**Comment by andrescaroc** [comment]
Oh, I didn't know that <br /> count as a child, it was confusing for me. Maybe in a separate line would make it clear a you say.
