### ISSUE TITLE
Font misalignment on introductions

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#38175]
<img width="666" alt="Screen Shot 2020-02-06 at 7 36 58 AM" src="https://user-images.githubusercontent.com/20648924/73941870-a1da3700-48b3-11ea-9e4d-a9c81e8867a1.png">

In the screenshot, the font changes about midway through the introduction. Here's a list of introductions with this problem...
[basic css](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/)
[applied accessibility](https://www.freecodecamp.org/learn/responsive-web-design/applied-accessibility/)
[es6](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/)
[basic algorithm scripting](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/) - the word `hint` doesn't seem quite right. Not sure if this one is an issue, but take a look while doing the rest.
[functional programming](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/)
[bootstrap](https://www.freecodecamp.org/learn/front-end-libraries/bootstrap/)
[algorithms](https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/) - this one doesn't have the same issue, but it has a giant heading or something in the middle of the page. It could probably be fixed along with the rest of these.

[npm](https://www.freecodecamp.org/learn/apis-and-microservices/managing-packages-with-npm/) - this one is already fixed via https://github.com/freeCodeCamp/freeCodeCamp/pull/38159

All of these files are located [here](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/client/src/pages/learn)

**Comment by EkaterinaVu** [comment]
It's probably because the second half of the text is wrapped directly in .intro-layout \<div> instead in \<p> element.

**Comment by ojeytonwilliams** [comment]
> It's probably because the second half of the text is wrapped directly in .intro-layout <div> instead in <p> element.

Yep, that's basically it.  Reason being, the markdown parser can't tell that the text should be interpreted as a paragraph since it's adjacent to raw html.  Ideally there should be no html at all, but it's probably sufficient to insert empty lines before the paragraphs that are being displayed incorrectly.

**Comment by shivam250** [comment]
.intro-layout is using inherit font-family called .. Roboto mono, monospace,, but for  .intro-layout p, . intro-layout li it's set to lato, sans-serief ...  This can be fix via setting font family for .intro-layout or by wrapping text into the p tag

**Comment by EkaterinaVu** [comment]
Those are .md files, and the rest of it is written in pure markdown. So just to be consistent, maybe they should be simply rewritten without any HTML tags inside, since there are only 5-6 files.

**Comment by ojeytonwilliams** [comment]
> maybe they should be simply rewritten without any HTML tags inside, since there are only 5-6 files.

@EkaterinaVu I think that's the best solution.

**Comment by LarryHu0217** [comment]
I have solved the problem and have tested on my local host, and I want to submit the pull request  for applied accessibility. Please Let me know how can I do that?@ojeytonwilliams

**Comment by RandellDawson** [comment]
@LarryHu0217 This was resolved when PR #38196 was merged 3 days ago.  It is no longer an issue.
