### ISSUE TITLE
Duplicated test output: Connect Redux with the messages app

### ISSUE THREAD

**Issue by andrescaroc** [freeCodeCamp/freeCodeCamp#38182]
**Describe your problem and how to reproduce it:**

**Go to:** https://www.freecodecamp.org/learn/front-end-libraries/react-and-redux/connect-redux-to-the-messages-app

**Look for:** Test outputs in the bottom-left corner

**Duplicated test output:** `The Presentational component should render an h2, input, button, and ul elements.`

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/react-and-redux/connect-redux-to-the-messages-app

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 79
* Operating System: Mac OS 10.13.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Captura-de-pantalla-2020-02-07-a-la(s)-5 30 04-p -m](https://user-images.githubusercontent.com/38670654/74070910-54072100-49d0-11ea-909b-1fce61c02d8d.jpg)

**Comment by andrescaroc** [comment]
The same duplicated test output exist in the following Challenge: 

**Go to:** https://www.freecodecamp.org/learn/front-end-libraries/react-and-redux/extract-local-state-into-redux

**Look for:** Test outputs in the bottom-left corner

**Duplicated test output:** The Presentational component should render an h2, input, button, and ul elements.

![Captura-de-pantalla-2020-02-07-a-la(s)-5 53 17-p -m](https://user-images.githubusercontent.com/38670654/74071917-37201d00-49d3-11ea-8737-27efb4b4ca69.jpg)

**Comment by RandellDawson** [comment]
@andrescaroc You are correct, the 2nd test should actually state:
>The <code>Presentational</code> component should render to the page.

**Comment by hassaanp** [comment]
Taking this up.
