### ISSUE TITLE
Wrong data shows in strikes in profile page.

### ISSUE THREAD

**Issue by santhosh-natarajan** [freeCodeCamp/freeCodeCamp#38192]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
Camper profile strike to shows in the calendar have some issue, It shows tomorrows data

**To Reproduce**
1. Go to the profile page
2. In the calendar view, you can see the error when hovering the cell

**Expected behavior**
It should show the current date, not tomorrow's.

**Screenshots**
![image](https://user-images.githubusercontent.com/55872828/74174050-46180100-4c59-11ea-923b-b1e7b1a764df.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 79.0.3945.130

**Smartphone (please complete the following information):**

**Comment by raisedadead** [comment]
Duplicate of #38037
