### ISSUE TITLE
Please update title and meta contents for Chinese /news

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#38197]
I want to update them like below, especially the `content`. Thanks!

```
<head>
<title>freeCodeCamp中文社区 - 技术文章 - 免费学习编程</title>
<meta name="description" content="freeCodeCamp是GitHub上的优质开源项目，是一个免费在线学习编程的社区，技术文章由技术大牛和极客为你编辑出最优质的干货，包括前端、后端、Android、iOS等方面的内容。StackOverflow、CSDN、开源中国、掘金、知乎等社区的开发者在这里也能有所收获。">
<meta name="keywords" content="freeCodeCamp,freeCodeCamp中文,编程,前端,程序员,文章,正则表达式,Python,JavaScript,AWS,json,HTML,CSS,Bootstrap,React,Vue,Webpack">
</head>
```

**Comment by LarryHu0217** [comment]
I can update this one.@miyaliu666

**Comment by LarryHu0217** [comment]
Can I help with this one ? @ahmadabdolsaheb

**Comment by ahmadabdolsaheb** [comment]
Thank you for your interest. I need to look into our ghost config since we need to change meta only for specific pages. 

do you have ghost running locally?

**Comment by LarryHu0217** [comment]
Yes I have!@ahmadabdolsaheb

**Comment by LarryHu0217** [comment]
I am not sure about what is ghost running. Also, I can't find the update file in the Chinese file. Could anyone give the path maybe? @ahmadabdolsaheb @miyaliu666

**Comment by ahmadabdolsaheb** [comment]
we have a Chinese branch on our ghost theme
https://github.com/freeCodeCamp/news-theme/tree/lang-chinese

**Comment by ahmadabdolsaheb** [comment]
@miyaliu666, I changed the tile and description from the ghost admin and then visiting general
Also I removed the top most message while I was at it.

thank you for your patience, and let me know if I could be of any help.
