### ISSUE TITLE
Regex Exercises

### ISSUE THREAD

**Issue by IvanDerlich** [freeCodeCamp/freeCodeCamp#38190]
This exercise:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/find-characters-with-lazy-matching

Can also be solve with this regex: ->      `/<h1>/`

* Browser Name: Firefox
* Browser Version: 
* Operating System:  Unbuntu

**Comment by ojeytonwilliams** [comment]
Good point.  I think we should add a second test that checks the regex uses lazy matching.  Possibly even a third to forbid matching 'h1' directly.

**Comment by AshNaz87** [comment]
@ojeytonwilliams I wish to work on this
