### ISSUE TITLE
Show Tweet buttons when camper is viewing own certification

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#38194]
When a camper is viewing their own certification, they can see a message that says "Tweet your certification".

The auto text should be "After 100s of hours of learning, I've earned @freeCodeCamp's [certification name] Certification."

**Comment by DZuz14** [comment]
@ahmadabdolsaheb @QuincyLarson Hopefully this is somewhere along the lines of what you guys were looking for. https://github.com/freeCodeCamp/freeCodeCamp/pull/38431

**Comment by raisedadead** [comment]
Re-assigning you @ahmadabdolsaheb to steer progress.
