### ISSUE TITLE
Some challenges' restrictions can be bypassed by re-assigning methods to different names

### ISSUE THREAD

**Issue by MohamedElidrissi** [freeCodeCamp/freeCodeCamp#38204]
Hey all, so after spending a few minutes trying to solve the [Steamroller challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/steamroller) from the Intermediate Algorithm Scripting section, I decided to try and reassign the `Array.prototype.flat` to a new method I named `Array.prototype.flatten` for the fun of it but surprisingly enough the challenge passed. So I think that this means all challenges which restrict the use of a certain method to pass can be bypassed with this same trick.

P.S: I'm gonna retry the challenge again legitimately.

**Comment by hassaanp** [comment]
I believe we can fix this by adding in checks for the usage of targetted prototype methods, like this:
```
assert(!code.match(/\.flat\([\s\S]*?\)/)
&& !code.match(/\.flatMap\([\s\S]*?\)/)
&& !code.match(/Array[\s\S]*?\.[\s\S]*?prototype[\s\S]*?\.[\s\S]*?flat));
```
@RandellDawson do you want me to push a fix for this and all other challenges where all Array methods are being validated? Let me know, I can take care of this ASAP :)

**Comment by RandellDawson** [comment]
@hassaanp I think this will work.  Create a PR and we can test it out extensively.

Thanks.

**Comment by hassaanp** [comment]
Hey, I have gone through the challenges library and tested out each where there were disallowed methods specified. There were several instances where adding newlines or reassigning the prototype method bypassed the checks.

I was able to modify the regex to prevent those bypass scenarios. I have verified the challenges on my end but would recommend someone else to test it as well.

**Comment by hassaanp** [comment]
@RandellDawson hi, did you get a chance to review this?

**Comment by snigo** [comment]
There will be countless other ways to reassign method :) Are you sure you want to track it with regex, it's a bit painful to watch to be honest.

Maybe something like this:
```
function callSniff(fn, sniffObject = global) {
  // Used to revert method to its original function after tests
  sniffObject._originalFn = fn;
  return function (...args) {
      sniffObject.called = true;
      sniffObject.callCount = (sniffObject.callCount || 0) + 1;
      return fn.apply(this, args);
  }
}

const arr = [1, 2, 3];
const sniffer = {};
Array.prototype.map = callSniff(Array.prototype.map, sniffer);
const reassignedMap = Array.prototype.map;
let mapped = arr.map(n => n * 2);
mapped = reassignedMap.call(mapped, n => n.toString());

console.log(mapped);
console.log(sniffer);
```

**Comment by moT01** [comment]
I may be a little late to the party here, but I don't think any of this is necessary. There's many ways on many of the challenges to pass the tests by hacking the tests. The project euler area, for example, only asks for a specific number to be returned on many of them. You could simply return that number without writing any algorithm. Most users aren't here to cheat themselves like that, and the ones that are - are doing exactly that.

Like @snigo mentioned...
> There will be countless other ways to reassign method

So the PR here will only make this slightly harder. All that being said, I guess I'm not against it - just that I don't think it's necessary.
