### ISSUE TITLE
Update congratulatory quotes

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#38200]
Refers changes from #37952

The changes from the linked PR should go into the correct file, I believe there are multiple such files.

We need to audit and combine all of them to one, and at the same time move them into the common config location.

**Comment by QuincyLarson** [comment]
@raisedadead Thanks for pointing this out and creating this new issue. Yes - these should all be in a single place, and should be easily editable by people who are unfamiliar with the codebase (since they're just strings of text).

**Comment by rdm100** [comment]
Hi, @QuincyLarson @raisedadead could I work on this?

Which file should the changes from [#37952 ](https://github.com/freeCodeCamp/freeCodeCamp/pull/37952) go into?

Also what are the multiple files that need audited and combined into one to then move on to the common config location?

**Comment by raisedadead** [comment]
You should look at the linked pull request that we closed. Then a quick search using your favorite code editor will give you the list of the files. 

We would want to keep the files in the common utils folder in the root of the repository.

**Comment by rdm100** [comment]
Hi, @raisedadead this might be a stupid question, but I'm not sure what I should be searching for in the code editor?

I looked at the files in the repository on the branch from the closed pull request and do not see any other folders that contain a resources.json file, which is where the congratulatory quotes were stored within the api-server/server/utils/ folder.

**Comment by raisedadead** [comment]
No worries, ask as many questions as you like. We are happy to help.

You would be correct, if you went looking for `resources.json`.

If your code editor allows searching in all files at once then look for one of the strings like `Over the top` for example, in all the files.

You would hit multiple json files. We would want them to be consolidated into one, which also means we replace how these old files are used.

Let me know if you need more help.

**Comment by rdm100** [comment]
@raisedadead cool thanks, ah ok, I hadn't realised my code editor did that, just because I've never had to do that before. I'm trying to get some open source experience and finding it difficult to get involved with different projects, as a lot of the bugs that I see seem too complex for me to fix.

I am quadriplegic from a spinal cord injury which has hindered me being able to get a development role at a company as few companies want to employ someone with a disability like mine. I did get down to the final 2 for a developer position at JP Morgan, but messed up the last interview through lack of experience.

I do have a degree in computer science from 2006 and refreshed my skills at a software development bootcamp last year, but I need to get some more practical development experience like open source to maybe be able to get some remote contracts or a developer role somewhere.

You have done a lot of cool stuff in tech and obviously are highly skilled, so any tips I can get from someone like yourself is much appreciated!

So, I should clone this repository [#37952](https://github.com/freeCodeCamp/freeCodeCamp/pull/37952) to search through not the master, yeah? 

Should I create another new branch from the or work on the existing branch?

Cheers

**Comment by rdm100** [comment]
@raisedadead @QuincyLarson  hey, ok so I found 3 files containing congratulatory quotes. I have compared the files in an app called DiffMerge to see the difference in content between them.

So I should take all unique content from the 3 files and consolidate them into one file containing congratulatory quotes and also remove the questionmarks, is that correct?

**Comment by raisedadead** [comment]
Hi @rdm100 

Thanks a lot for sharing your story. freeCodeCamp strives to be a resource for everyone.

As for getting started, I highly recommend our [how to contribute to open source guide](https://github.com/freeCodeCamp/how-to-contribute-to-open-source).

As for this PR I would advice you to give [guidelines for contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md) a thorough read.

You should also probably setup a free editor like VSCode, Atom or Sublime, etc. which can help you lookup code, etc.

Now, we would want to limit the interaction on this thread for the issue in the OP only, so I recommend that you should definitely reach-out to [contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) and our [community forum](https://www.freecodecamp.org/forum) instead for general contributing help.

Thanks.
 

> So I should take all unique content from the 3 files and consolidate them into one file containing congratulatory quotes, remove the questionmarks and put the file the utils folder at the root is that correct?
> 
> Do you have a preference for the name of the file or should I just name it congratulatory-quotes.json?

Yes, that should be a good place to start. The file name is fine, as long as its relevant. Also you may want to look up how the old files are wired to the code and logic. Let me know if you need help there.

**Comment by rdm100** [comment]
@raisedadead I will check out all the links on contributing you suggest.

I have already searched the project with atom and found the 3 files that contain the congratulatory quotes.

I have also found how the 2 words.json files are wired to the code and logic and will be able to adjust that to the new consolidated file, but I cannot find any reference to the 3rd file that contains congratulatory quotes which is resources.json, could you point me to where resources.json is imported and used in the code?

**Comment by raisedadead** [comment]
> could you point me to where resources.json is imported and used in the code?

If you did not find an import, it has been removed from use, which is good and should not affect your changes.

**Comment by rdm100** [comment]
Hi there, I just submitted a pull request for this let me know if it is ok?

**Comment by raisedadead** [comment]
Thanks for the PR, its not made to the correct upstream repository. I recommend you read our [guidelines for contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md), which has detailed steps.

**Comment by rdm100** [comment]
@raisedadead sorry I have read the guidelines for contributing, but do not understand  what I have done wrong, could you help guide me how to make the pull request to the correct upstream repository?

**Comment by RandellDawson** [comment]
@rdm100 You should have forked the `freeCodeCamp` repo and made changes on a branch of your fork and then targeted the `master` branch of the `freeCodeCamp` repo.  As it stands now, your branch may not include changes to the very files you modified, because you did not create your working branch off your forked `freeCodeCamp` repo.

**Comment by rdm100** [comment]
@RandellDawson thanks for the information. I thought I had forked the freeCodeCamp repo, so I'm not sure what I did wrong still, when I forked the freeCodeCamp repo the fix/update-congratulatory-quotes was the branch displayed, should the branch being displayed be the master when I fork the repository, so is that where I went wrong?

Thanks for your patience, much appreciated.

**Comment by RandellDawson** [comment]
@rdm100 You appear to have forked from:
>https://github.com/QuincyLarson/freecodecamp

which is 220 commits behind the `master` branch of the of the correct repo (shown below):
>https://github.com/freecodecamp/freecodecamp

I suggest closing the PR you created,  fork the correct repo, and start the process over to create a pull request.

**Comment by rdm100** [comment]
@RandellDawson ah I see thank you for the correction. I thought the repository I had forked had been the original, when clearly I should have seen it had been forked already! I will redo it correctly and submit another pull request.

**Comment by rdm100** [comment]
@raisedadead @RandellDawson @QuincyLarson Hi there, I just submitted a pull request for this let me know if it is ok?

**Comment by raisedadead** [comment]
Thanks, we will review it in due course. The dev team usually gets pings when a PR is opened. Thanks for your patience.

**Comment by Ieahleen** [comment]
As I see this is still open, there is this feedback that I think should be considered: https://www.freecodecamp.org/forum/t/why-is-there-a-winston-churchill-quote/401215

**Comment by Ieahleen** [comment]
now I have the new JSON file, there are some quotes that differ just for a symbol, I can delete them by hand or add a line to my code, just, which do you prefer, smart quote, or plain quote (or apostrophe maybe?)
```
{
      quote: "Don't let yesterday take up too much of today.",
      author: "Will Rodgers",
    },
    {
      quote: "Don’t let yesterday take up too much of today.",
      author: "Will Rodgers",
    },
```

here the "don't" is the only difference, and it happens a few more times, which one do you want me to keep?

**Comment by rdm100** [comment]
Hi,

I had finished it apart from the testing. I couldn't get it tested because I couldn't get it set up locally because I have windows 10 home and not pro. Pro is needed for part of it to work normally and the workaround didn't work.

Can the repo be tested on gitpod?

**Comment by Ieahleen** [comment]
> Can the repo be tested on gitpod?

yes it can, I am actually working totally on gitpod. If you have the changes in your branch you can launch the gitpod workspace from your guthub brunch and you have a complete work environment there

**Comment by raisedadead** [comment]
@Ieahleen 

> which one do you want me to keep?

I would say, just use your best judgement, there are no wrong answers with minor things like that. And if anything, this will go thru the QA on the PR. Yes, you would defnitely want to remove the duplicated strings of course.

@rdm100 

> I couldn't get it tested because I couldn't get it set up locally because ...

and 

> Can the repo be tested on gitpod?

Yes, it can be. You do not need to be on a physical machine per se.

We had recommended reaching out to the contributors channels on forum and chat, and had waited for a bit for an update on your PR. We could not confirm your interest, after a while and per our normal policies, chose to let others work on this.

But please do not be dishartened. There are several other issues that you can take up if you are still interested in working on something.

Happy contributing.

**Comment by rdm100** [comment]
I had asked on the channel, but no one had suggested using gitpod. Anyway I figured out how to test the repo on gitpod so that is useful.

**Comment by Ieahleen** [comment]
> I had asked on the channel, but no one had suggested using gitpod. Anyway I figured out how to test the repo on gitpod so that is useful.

I mean, if you have already finished, I will not be offended if you create the pull request, I am stuck anyway. I can work on something else.

**Comment by rdm100** [comment]
would be cool to finish it. What are you stuck on?

**Comment by Ieahleen** [comment]
> would be cool to finish it. What are you stuck on?

I was stuck on making the JSON valid... but I resolved it, and I am actually almost ready to do the pull request. If you want to finish it, I will not, I will work on something else.

**Comment by rdm100** [comment]
I have it fully working so I will submit the pull request if that is ok?

**Comment by Ieahleen** [comment]
> I have it fully working so I will submit the pull request if that is ok?

go for it, I have already told so

**Comment by rdm100** [comment]
thanks
