### ISSUE TITLE
https://www.freecodecamp.com/ does not redirect to org properly

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#38201]
Although https://www.freecodecamp.com/ does not redirect properly to .org,  http:// does.

**Comment by raisedadead** [comment]
Looks like the certificate has not been working on this domain for a while. We used to have a redirect always rule on the domain. I will check what changed.

**Comment by raisedadead** [comment]
Created and assigned fresh origin certificates for .com domain. There will be browser caching of old certs for a while, but eventually it should resolve correctly.
