### ISSUE TITLE
Can't copy and paste on iphone

### ISSUE THREAD

**Issue by rmgraphicdesign** [FreeCodeCamp/FreeCodeCamp#3820]
On some challenges you have to put in a URL to images etc.
On the iPhone I'm guessing the Navigation bar is indexed on top of the website, so every time you hold your finger down to hi-light text (URL'S) it jumps to the Navigation bar every-time.

Not a major issue but would save a lot of time typing out long URL's

**Comment by ltegman** [comment]
Unfortunately support for completing challenges on mobile phones is not a practical goal for Free Code Camp, especially since mobile browsers don't always support the same features as their desktop counterparts. We appreciate your interest though :smile:
