### ISSUE TITLE
Solution not working! - Find Characters with Lazy Matching (Regular Expressions) 

### ISSUE THREAD

**Issue by gignupg** [freeCodeCamp/freeCodeCamp#38219]
I think you have to revise the solution. It's not working!

**Comment by Sky020** [comment]
**Issue**
Guide post solution does not pass tests.

I believe this became an problem, when this _issue_ on GitHub was merged:
https://github.com/freeCodeCamp/freeCodeCamp/issues/38190

Solution on Guide Post: https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-find-characters-with-lazy-matching/301341

Challenge in question: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/find-characters-with-lazy-matching

**Comment by hassaanp** [comment]
This regex would work but I cannot modify the guidepost solution.

`/\<[a-z]*?[0-9]*?\>/`

**Comment by gignupg** [comment]
Your solution works, but it's too complicated for someone who is just learning that there is a concept called lazy/greedy matching. 
Also the escape character hasn't been taught so far (at least not with regular expressions), so we cannot expect students to use escape characters to solve this challenge!

**Comment by Sky020** [comment]
I would expect the solution to look something like:
`let myRegex = /<.*?>/;`
All of that has been taught before. And is what the lesson was trying to get at: Use the `?` to fix the expression for _lazy matching_.

**Comment by raisedadead** [comment]
Hi @RandellDawson can you please take a look and update the guide if needed.

**Comment by RandellDawson** [comment]
It seems @Sky020 updated it already.

**Comment by thaominh1996** [comment]
I don't think it's exactly...but it's true.
let text = "<h1>Winter is coming</h1>";
let myRegex = /<[a-z.1?]*>/; // Change this line
let result = text.match(myRegex);
