### ISSUE TITLE
Roman Numeral Converter should test L (50), C (100), D (500) and M (1000)

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3822]
Challenge [Bonfire: Roman Numeral Converter](http://freecodecamp.com/challenges/bonfire-roman-numeral-converter) has an issue.

We need a few additional tests to cover these situations. This will make the challenge more difficult, but it shouldn't make it excessively difficult.

**Comment by awesomeaniruddh** [comment]
I have a PR open for this: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3483

**Comment by QuincyLarson** [comment]
Awesome - thanks for updating it. I can't wait to pull this in - sorry it's taken so long to get this pulled in.

**Comment by awesomeaniruddh** [comment]
The PR has been updated and all the conflicts have been resolved.
