### ISSUE TITLE
Incorrect Instructions: Applied-visual-design, lesson Lock-an-element...

### ISSUE THREAD

**Issue by terrifricker** [freeCodeCamp/freeCodeCamp#38234]
**Describe your problem and how to reproduce it:**
The current instruction is incorrect.  The current instruction is:
_Lock the #searchbar element to the top-right of its section parent by declaring its position as absolute. Give it top and right offsets of 50 pixels each._

The absolute position's default position is the top-right.  Giving top and right offsets moves the #searchbar towards the bottom-left.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/lock-an-element-to-its-parent-with-absolute-positioning

**Tell us about your browser and operating system:**
* Browser Name: Safari
* Browser Version: 13.0.4
* Operating System: macOS Mojave 10.14.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screen Shot 2020-02-18 at 1 23 07 PM](https://user-images.githubusercontent.com/51532684/74779295-0dc48400-5252-11ea-9be0-7b3315043d31.png)

**Comment by RandellDawson** [comment]
@terrifricker Not sure what you are talking about here.  If you do as requested in the instructions, it will work.  I suggest bringing this up on [our forum](https://www.freecodecamp.org/forum/).  If others there agree there is a problem, then feel free to request this issue to be reopened. 

Thank you.
