### ISSUE TITLE
Universal nav links should not open in a new tab

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#38235]
The top nav items on the forum and news does not open in a new tab.
We would like the same functionality on learn for consistency.

**Comment by ojeytonwilliams** [comment]
Do we want all external links to navigate without opening a tab?  A quick search suggests that all the links in the footer open new tabs, as do a couple in `/accept-privacy-terms`.  

I think it's better UX to leave tab opening to the user, but I thought I'd check.

**Comment by AshNaz87** [comment]
If you decide to go ahead with this, I'd like to have a go at this

**Comment by raisedadead** [comment]
I think we want this to remain as is except for the navigation links up top on the navbar, which are the most used links on the platform. This is to make it consistent with the behaviour on forum and news.

@ahmadabdolsaheb can you proceed and make the changes. This will likely affect some of the routing. I would like to test this before working on the client app for chinese curriculum.
