### ISSUE TITLE
Inconsistent capitalization of buttons

### ISSUE THREAD

**Issue by ArielLeslie** [freeCodeCamp/freeCodeCamp#38245]
Most action buttons are capitalized, but not all.
![image](https://user-images.githubusercontent.com/6234475/73395470-d55a0780-429c-11ea-98e8-084849310266.png)
![image](https://user-images.githubusercontent.com/6234475/73395570-02a6b580-429d-11ea-8bcf-5cac0a88c89d.png)
![image](https://user-images.githubusercontent.com/6234475/73396453-9fb61e00-429e-11ea-9937-8f6caebee2ef.png)

**Comment by ahmadabdolsaheb** [comment]
the above mentioned issue has been addressed and currently only Reply is capitalized on our theme for consistency.
