### ISSUE TITLE
Bronken links in Get a Hint from /learn Basic Algorithm Scripting: Find the Longest Word in a String

### ISSUE THREAD

**Issue by BoyeongYoon** [freeCodeCamp/freeCodeCamp#38248]
**Describe your problem and how to reproduce it:**
The three relevant links under [Solution 2](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-find-the-longest-word-in-a-string/16015) are broken. 

If I click the link, the browser shows that 

"This site can’t be reached.
forum.freecodecamp.com’s server IP address could not be found."

So, I think that there must be according links from the forum. 

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 
* Operating System: MacOS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screen Shot 2020-02-21 at 3 32 09 PM](https://user-images.githubusercontent.com/30683150/75069531-5cc32100-54bf-11ea-82d8-a196c783d077.png)

![Screen Shot 2020-02-21 at 3 31 34 PM](https://user-images.githubusercontent.com/30683150/75069487-46b56080-54bf-11ea-9732-96721d0c46e8.png)

**Comment by RandellDawson** [comment]
I removed the middle link and added valid urls for the other two.  Let us know if you are still having trouble with this forum topic.

Thank you.
