### ISSUE TITLE
TypeError: Cannot read property 'presets' of undefined

### ISSUE THREAD

**Issue by mikecullen76** [freeCodeCamp/freeCodeCamp#38252]
Hello, I receive this error message:

TypeError: Cannot read property 'presets' of undefined

With this challenge:

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/add-items-to-an-array-with-push-and-unshift.english.md

Solution:

```js
function mixedNumbers(arr) {
  // change code below this line
  arr.push(7,'VIII',9);
  arr.unshift('I',2,'three');
  // change code above this line
  return arr;
}
```

Link to page with problem:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/remove-items-from-an-array-with-pop-and-shift

(Message: TypeError: Cannot read property 'presets' of undefined)

* Browser Name: Chrome
* Browser Version: Version 79.0.3945.130 (Official Build) (64-bit)
* Operating System: macOS High Sierra 10.13.6

![Screen Shot 2020-02-23 at 7 18 07 pm](https://user-images.githubusercontent.com/57419044/75117394-4230a980-5671-11ea-9292-b72e0b67d036.jpg)

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

**Comment by ojeytonwilliams** [comment]
This isn't a problem with the user's code, when I use their code the tests pass.  It's probably related to #38077 since I changed how the presets were loaded.

@mikecullen76 are you still seeing this problem?

**Comment by mikecullen76** [comment]
@ojeytonwilliams Thank you, the problem is now solved.
