### ISSUE TITLE
Slow react tests

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#38254]
**Describe your problem and how to reproduce it:**
Several React challenges have asynchronous tests that include numerous timeouts.  This can cause `npm run test` to fail randomly causing ci tests to, mistakenly, flag a commit as failing when it should not.  Most recently curriculum/challenges/english/03-front-end-libraries/react/add-event-listeners.english.md failed, but it may not be the only one.

I don't think there is a need to wait, since the testing framework is synchronous. So, they should be re-written as synchronous tests.

Reproduction is difficult, but it should be fixed if the tests run quickly (i.e under a second).

**Comment by Sky020** [comment]
@ojeytonwilliams , is this still something worth working on?

**Comment by ojeytonwilliams** [comment]
@Sky020 Sure thing.  It's not often a problem, but it's annoying to have someone's PR fail the tests through no fault of their own.

It won't be necessary to change all challenges with redundant timeouts. If you time them and fix any of the worst offenders that would be great.

**Comment by Sky020** [comment]
I have been unable to even get the tests to finish with `npm run test:curriculum`

I get this error:
```
  8387 passing (6m)
  568 pending
  2 failing

  1) Check challenges
       Check challenges (english)
         Access the JSON Data from an API
           Test suite must fail on the initial contents:
     Error: Timeout of 6000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\shauh\Documents\freeCodeCamp\freeCodeCamp\curriculum\test\test-challenges.js)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  2) Check challenges
       "after all" hook:
     Uncaught Error: unhandledRejection: Error, Protocol error (Runtime.callFunctionOn): Target closed.
      at process.<anonymous> (test\test-challenges.js:94:11)
      at processPromiseRejections (internal/process/promises.js:165:18)
      at processTicksAndRejections (internal/process/task_queues.js:90:32)

```
I have tried changing the flags in the `package.json` in _curriculum_. I have removed `--bailout`, and cannot find any useful flags for purposes of timing in the Mocha documentation.

Also, what has happened to the functionality of this:
```
npm run test:curriculum --block='React'
```
Or:
```
npm run test -- -g 'Add Event Listeners'
```
Neither work. The whole test suite is run.

@ojeytonwilliams , could you help by pointing in the correct direction?

**Comment by ojeytonwilliams** [comment]
@Sky020 I've sent you a message on Gitter about the failing tests.  

To get timing info from Mocha, you can use
```
 "test": "mocha --delay --reporter spec --bail"
```
in `scripts` and then search the output for any tests with 4 digit times.  When I did that I found:

- Use Array.filter() to Dynamically Filter an Array
- Use Advanced JavaScript in React Render Method
- Use a Ternary Expression for Conditional Rendering
- Render Conditionally from Props
- Optimize Re-Renders with shouldComponentUpdate
- Create a Controlled Form

Any of those would be worth investigating.

**Comment by Sky020** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Slow React Tests](https://trello.com/c/kkeQQ7Ir/14-slow-react-tests)
