### ISSUE TITLE
Forum badge images aren't showing up

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#38265]
The badges page of freeCodeCamp's forum doesn't show the badge icons anymore. Even though we are emphasizing text over icons, this is a case where we do want to show the big icons that we had before.

Here's how our https://www.freecodecamp.org/forum/badges looks:

<img width="1385" alt="Badges_-_The_freeCodeCamp_Forum" src="https://user-images.githubusercontent.com/985197/75280136-7ff91380-57d2-11ea-8ca3-84312fb5c464.png">

Here's how Discourse's official discourse instance badge page (https://meta.discourse.org/badges) looks: 

<img width="1226" alt="Badges_-_Discourse_Meta" src="https://user-images.githubusercontent.com/985197/75280112-7374bb00-57d2-11ea-997b-1dc8bec85bdd.png">

**Comment by hassaanp** [comment]
Hi,

I was able to find and fix the issue on my fork of the discourse-theme repo.
A little unsure of the workflow/guideline for submitting PRs to the target repository since it is disjoint from the main one.

Here is the [link to the PR](https://github.com/freeCodeCamp/discourse-theme/pull/20)
