### ISSUE TITLE
"<b>Stanford University.</b>" is wrong

### ISSUE THREAD

**Issue by chuckadams** [freeCodeCamp/freeCodeCamp#38268]
**Describe your problem and how to reproduce it:**

If you didn't see the problem in the title, then you have lots of company.

An issue that comes up at least once a week involves the "wrap the bold tags around ``Stanford University’’ challenge (I can’t seem to find it in the TOC for some reason), where we have to tell people to not include the period at the end. I know attention to detail is a big thing in programming, but this is one of the very first challenges, and that period is REALLY easy to miss.

Maybe have them just wrap the tag around “Stanford” instead?

**Comment by raisedadead** [comment]
Hi @chuckadams we should make the tests a little flexible instead. Please link the challenge in the OP and someone can pick this up.

**Comment by LarryHu0217** [comment]
I can help with this one, if someone can specify which specify challenge and which is the actually issue on the page @chuckadams

**Comment by raisedadead** [comment]
Hi @LarryHu0217 looks like this issue has been picked up by someone. I would encourage you to reach-out to [contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) seeking help in identifying issues that you could help us with.

Issues that are tagged `help wanted` are open for contribution, and do not need prior approval. The first PR (that resolves the issue) is typically merged. 

Thanks.

**Comment by RandellDawson** [comment]
@LarryHu0217 [This is the challenge file](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/use-the-strong-tag-to-make-text-bold.english.md) that needs the test (line 29) updated.

**Comment by raisedadead** [comment]
Hi @LarryHu0217 we have gone ahead and assigned you the issue, please let us know if you are interested and would be making a PR. 

Thanks

**Comment by LarryHu0217** [comment]
I think I figure out the solution. @raisedadead

**Comment by LarryHu0217** [comment]
How can I submit my pull request? @RandellDawson

**Comment by RandellDawson** [comment]
@LarryHu0217 Start by [reading our contributing guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).  You will need to also read the [How to work on coding challenges](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-coding-challenges.md) guide.  If you get stuck or have further questions, please use our [Contributors channel on Gitter](https://gitter.im/FreeCodeCamp/Contributors) where you should receive a faster response.

**Comment by AshNaz87** [comment]
Am happy to do this if required

**Comment by LarryHu0217** [comment]
[use-the-strong-tag-to-make-text-bold.english.zip](https://github.com/freeCodeCamp/freeCodeCamp/files/4263113/use-the-strong-tag-to-make-text-bold.english.zip)

**Comment by LarryHu0217** [comment]
I just submit my solution first, and then find if  there is a way to open a new PR. 
@chuckadams

**Comment by RandellDawson** [comment]
@LarryHu0217 Please refer to the contributing guidelines I reference in a previous reply.  Everything you need to know about creating a PR is in the documentation.  If you get stuck, ask questions in the [Contributors room on Gitter](https://gitter.im/FreeCodeCamp/Contributors).

Thank you.

**Comment by AshNaz87** [comment]
@RandellDawson PR submitted

**Comment by ikenna4peace** [comment]
I don't really understand
