### ISSUE TITLE
API integration Waypoints

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3828]
NOTE: This is an example issue for the purpose of the discussion going on in https://gitter.im/freecodecamp/curriculumdevelopment

We need a series of challenges that addresses: 

- [x] how JSON works
- [ ] how to fetch JSON from a URL
- [ ] how to loop through JSON
- [ ] how to use AJAX to generate HTML elements containing the results from the API call

These Waypoints would follow our basic Ziplines and precede our intermediate Ziplines.

**Comment by codybousc** [comment]
I was just going to suggest this! I found a quality resource that condenses all necessary background info into something that's easily digestible--both in length and and in a 'light-handed' technical intro. At the very least, it may be a nice reference for folks until an FCC waypoint is up and running. 

https://zapier.com/learn/apis/
