### ISSUE TITLE
Chinese challenges needing auditing (Responsive Web Design)

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#38299]
Following on from https://github.com/freeCodeCamp/freeCodeCamp/pull/38040 these are the Chinese challenges that may need looking at.  

This issue only covers challenges in the **Responsive Web Design** certification.

All the challenges below have Description or Instructions sections with changes to the English version after December 1st, 2019.  Also, any challenges with `Tests` where at least one test's `text` has changed in the English version since Dec, 1 2019 or where the number of tests in the current English version is different than the number of tests in the current Chinese version.

- [x] [Change the Color of Text](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-css/change-the-color-of-text.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test `text`(s) do not match:**
  **Test 2**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your <code>h2</code> element should be red.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  Your <code>h2</code> element should have color set to <code>red</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [x] [Use the u Tag to Underline Text](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/use-the-u-tag-to-underline-text.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **Number of tests do not match (English: 2, Chinese: 3)**

</details>

---
- [x] [Lock an Element to the Browser Window with Fixed Positioning](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/lock-an-element-to-the-browser-window-with-fixed-positioning.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [x] [Align Elements Using the justify-content Property](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/align-elements-using-the-justify-content-property.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**
- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>#box-container</code> element should have a <code>justify-content</code> property set to a value of center.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>#box-container</code> element should have a <code>justify-content</code> property set to a value of <code>center</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [x] [Use display: flex to Position Two Boxes](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-display-flex-to-position-two-boxes.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**
- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  <code>#box-container</code> should have the <code>display</code> property set to a value of flex.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  <code>#box-container</code> should have the <code>display</code> property set to a value of <code>flex</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [x] [Add Images to Your Website](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/add-images-to-your-website.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [x] [Add Placeholder Text to a Text Field](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/add-placeholder-text-to-a-text-field.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **Number of tests do not match (English: 4, Chinese: 3)**

</details>

---
- [x] [Use Clockwise Notation to Specify the Margin of an Element](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-css/use-clockwise-notation-to-specify-the-margin-of-an-element.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **Number of tests do not match (English: 5, Chinese: 4)**

</details>

---
- [x] [Use CSS Selectors to Style Elements](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-css/use-css-selectors-to-style-elements.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **Number of tests do not match (English: 5, Chinese: 4)**

</details>

---
- [x] [Override Styles in Subsequent CSS](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-css/override-styles-in-subsequent-css.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [x] [Make an Image Responsive](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-principles/make-an-image-responsive.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**
- **Number of tests do not match (English: 2, Chinese: 3)**

</details>

---
- [x] [Build a Product Landing Page](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-product-landing-page.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [x] [Use the flex Shorthand Property](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-flex-shorthand-property.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**
- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>#box-1</code> element should have the <code>flex</code> property set to a value of 2 2 150px.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>#box-1</code> element should have the <code>flex</code> property set to a value of <code>2 2 150px</code>.
  ```
  </td>
  </tr>
  </table>

  **Test 2**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>#box-2</code> element should have the <code>flex</code> property set to a value of 1 1 150px.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>#box-2</code> element should have the <code>flex</code> property set to a value of <code>1 1 150px</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [x] [Use the order Property to Rearrange Items](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-order-property-to-rearrange-items.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**
- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>#box-1</code> element should have the <code>order</code> property set to a value of 2.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>#box-1</code> element should have the <code>order</code> property set to a value of <code>2</code>.
  ```
  </td>
  </tr>
  </table>

  **Test 2**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>#box-2</code> element should have the <code>order</code> property set to a value of 1.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>#box-2</code> element should have the <code>order</code> property set to a value of <code>1</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [x] [Use the flex-direction Property to Make a Column](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-flex-direction-property-to-make-a-column.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**

</details>

---
- [x] [Use the flex-shrink Property to Shrink Items](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-flex-shrink-property-to-shrink-items.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**
- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>#box-1</code> element should have the <code>flex-shrink</code> property set to a value of 1.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>#box-1</code> element should have the <code>flex-shrink</code> property set to a value of <code>1</code>.
  ```
  </td>
  </tr>
  </table>

  **Test 2**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>#box-2</code> element should have the <code>flex-shrink</code> property set to a value of 2.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>#box-2</code> element should have the <code>flex-shrink</code> property set to a value of <code>2</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [x] [Use the flex-grow Property to Expand Items](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-flex-grow-property-to-expand-items.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**
- **`Instructions` section has changed**
- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>#box-1</code> element should have the <code>flex-grow</code> property set to a value of 1.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>#box-1</code> element should have the <code>flex-grow</code> property set to a value of <code>1</code>.
  ```
  </td>
  </tr>
  </table>

  **Test 2**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>#box-2</code> element should have the <code>flex-grow</code> property set to a value of 2.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>#box-2</code> element should have the <code>flex-grow</code> property set to a value of <code>2</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [x] [Add Flex Superpowers to the Tweet Embed](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/add-flex-superpowers-to-the-tweet-embed.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your <code>header</code> should have a <code>display</code> property set to flex.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  Your <code>header</code> should have a <code>display</code> property set to <code>flex</code>.
  ```
  </td>
  </tr>
  </table>

  **Test 2**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your <code>footer</code> should have a <code>display</code> property set to flex.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  Your <code>footer</code> should have a <code>display</code> property set to <code>flex</code>.
  ```
  </td>
  </tr>
  </table>

  **Test 3**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your <code>h3</code> should have a <code>display</code> property set to flex.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  Your <code>h3</code> should have a <code>display</code> property set to <code>flex</code>.
  ```
  </td>
  </tr>
  </table>

  **Test 4**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your <code>h4</code> should have a <code>display</code> property set to flex.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  Your <code>h4</code> should have a <code>display</code> property set to <code>flex</code>.
  ```
  </td>
  </tr>
  </table>

  **Test 5**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your <code>.profile-name</code> should have a <code>display</code> property set to flex.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  Your <code>.profile-name</code> should have a <code>display</code> property set to <code>flex</code>.
  ```
  </td>
  </tr>
  </table>

  **Test 6**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your <code>.follow-btn</code> should have a <code>display</code> property set to flex.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  Your <code>.follow-btn</code> should have a <code>display</code> property set to <code>flex</code>.
  ```
  </td>
  </tr>
  </table>

  **Test 7**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  Your <code>.stats</code> should have a <code>display</code> property set to flex.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  Your <code>.stats</code> should have a <code>display</code> property set to <code>flex</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [x] [Create a Bulleted Unordered List](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/create-a-bulleted-unordered-list.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **Number of tests do not match (English: 5, Chinese: 4)**

</details>

---
- [x] [Align Elements Using the align-items Property](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/align-elements-using-the-align-items-property.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**
- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>#box-container</code> element should have an <code>align-items</code> property set to a value of center.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>#box-container</code> element should have an <code>align-items</code> property set to a value of <code>center</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [x] [Use the align-self Property](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-align-self-property.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**
- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>#box-1</code> element should have the <code>align-self</code> property set to a value of center.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>#box-1</code> element should have the <code>align-self</code> property set to a value of <code>center</code>.
  ```
  </td>
  </tr>
  </table>

  **Test 2**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>#box-2</code> element should have the <code>align-self</code> property set to a value of flex-end.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>#box-2</code> element should have the <code>align-self</code> property set to a value of <code>flex-end</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [x] [Use the align-items Property in the Tweet Embed](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-align-items-property-in-the-tweet-embed.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>.follow-btn</code> element should have the <code>align-items</code> property set to a value of center.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>.follow-btn</code> element should have the <code>align-items</code> property set to a value of <code>center</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [x] [Build a Tribute Page](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-tribute-page.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [x] [Create a Media Query](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-principles/create-a-media-query.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **Number of tests do not match (English: 3, Chinese: 2)**

</details>

---
- [x] [Use the flex-wrap Property to Wrap a Row or Column](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-flex-wrap-property-to-wrap-a-row-or-column.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Instructions` section has changed**
- **The following test `text`(s) do not match:**
  **Test 1**
  <table>
  <tr>
  <th>
  Version
  </th>
  <th align="left">
  Text
  </th>
  </tr>
  <tr>
  <td align>Old</td>
  <td align>

  ```
  The <code>#box-container</code> element should have the <code>flex-wrap</code> property set to a value of wrap.
  ```
  </td>
  </tr>
  <td>New</td>
  <td>

  ```
  The <code>#box-container</code> element should have the <code>flex-wrap</code> property set to a value of <code>wrap</code>.
  ```
  </td>
  </tr>
  </table>

</details>

---
- [x] [Build a Personal Portfolio Webpage](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-personal-portfolio-webpage.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [x] [Build a Survey Form](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-survey-form.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

---
- [x] [Build a Technical Documentation Page](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-technical-documentation-page.english.md)

<details><summary>Show/Hide sections with changes/issues</summary>

- **`Description` section has changed**

</details>

**Comment by RandellDawson** [comment]
@raisedadead I have updated the issue body to show all the challenges that need to be reviewed since the work was started in December of 2019 on converting the English version to the Chinese version for the Responsive Web Design section.

**Comment by raisedadead** [comment]
Hi @freeCodeCamp/chinese team, can you please go through the OP and prioritise this audit and any changes via pull requests.

Thanks.

**Comment by RandellDawson** [comment]
@raisedadead I think we can close this issue now, since PR #38309 made changes as a result of the audit of the files above.
