### ISSUE TITLE
404 error for Free Code Camp Pull Request

### ISSUE THREAD

**Issue by LarryHu0217** [freeCodeCamp/freeCodeCamp#38306]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
This is a broken website page when clicking on the hyper line on "How to Setup and Maintain a Local Instance of Free Code Camp" inside the the page titled "Editing via your Local Fork (Recommended)"

**To Reproduce**
1.Go to  https://guide.freecodecamp.org/miscellaneous/how-to-make-a-pull-request-on-free-code-camp/
2.Find there is a  Editing via your Local Fork (Recommended) section
3.Click on the hyperlink on the text "How to Setup and Maintain a Local Instance of Free Code Camp"
4.Notice the 404 error you are taken to:http://forum.freecodecamp.com/t/how-to-fork-and-maintain-a-local-instance-of-free-code-camp/19116

**Expected behavior**

**Screenshots**
<img width="1186" alt="截屏2020-02-29下午7 27 11" src="https://user-images.githubusercontent.com/35699841/75617172-887e8080-5b29-11ea-8e06-4e3e5b25c1ca.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RandellDawson** [comment]
@LarryHu0217 Can you tell us how you found that Guide page to begin with?  Was it linked from the contributing guide on GitHub?

**Comment by LarryHu0217** [comment]
I find it on the GitHub contribution page.@RandellDawson

**Comment by RandellDawson** [comment]
@LarryHu0217 I meant where specifically?  Which document and where in the document is the link to this particular Guide page?

**Comment by LarryHu0217** [comment]
I just search on the freecodecamp website. I don't remember which guideline

**Comment by RandellDawson** [comment]
Those guides are deprecated.  The only documentation for contributing you need to read through starts [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).

**Comment by raisedadead** [comment]
Thanks for reporting this.

We are in the process of improving all the guide articles and migrating them over to /news. (The Guide codebase and its many contributions will remain on GitHub.)

So rather than spending time to fix this specific issue, we will stay focused on finishing this big migration as fast as possible.
