### ISSUE TITLE
Need to update a few challenges' test texts to wrap certain values in code tags to prevent translation in other languages

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#38312]
Following up on the [comment on PR 38309](https://github.com/freeCodeCamp/freeCodeCamp/pull/38309#discussion_r386444356), the following English challenge tests need to be updated as described, as the non-English version were translating these when they should not have been translated.

* Standardize Times with the HTML5 datetime Attribute
**Issues:** All tests need to be re-translated

* Use the strong Tag to Make Text Bold 
**Issues:**  "Stanford University" needs code tags so it is not translated.

* Add a Submit Button to a Form
**Issues:** "Submit" needs code tags so it is not translated

* Add Placeholder Text to a Text Field
**Issues:** "cat photo URL" needs code tags so it is not translated

* Create an Ordered List
**Issues:** The first test text "Top 3 things cats hate:" needs code tags so it is not translated.  The same goes for the second test text "Things cats love:"

* Headline with the h2 Element
**Issues:** The third test text "CatPhotoApp" needs code tags so it is not translated. 

* Inform with the Paragraph Element
**Issues:**  The second test text "Hello Paragraph" needs code tags so it is not translated.

* Use the u Tag to Underline Text
**Issues:** The second test text "Ph.D. students" needs code tags so it is not translated.

**Comment by millwala53** [comment]
I would like to work on this issue, please.

**Comment by millwala53** [comment]
@RandellDawson  I have managed to fix all the issues, just need some clarification related to the first issue.
Standardize Times with the HTML5 datetime Attribute, When you say all tests need to be re-translated do you mean that the important text in each test e.g "Thursday, September 15&lt;sup&gt;th&lt;/sup&gt;" in test 2 need to be wrapped in a code tag so they aren't translated?

**Comment by RandellDawson** [comment]
@millwala53 I mean the Chinese version of this challenge was never updated with [the changes made to the English version on June 28th, 2019](https://github.com/freeCodeCamp/freeCodeCamp/commit/438e7d4c51389363a445040c4d518d01589734b2#diff-4959fbcb7d95c0dc2360d36bb5fd2807).  This means the all of the `text` needs to be modified so that the parts in quotes are surrounded by `code` tags and the rest gets translated to Chinese.  Also, in the last test `2016-09-15` should be surrounded with `code` tags.

**Comment by RandellDawson** [comment]
@millwala53 In the time I wrote my last comment @Sky020 created a PR to resolve this issue.
