### ISSUE TITLE
Change Solution 2 for Algorithms: Inventory Update

### ISSUE THREAD

**Issue by elisecode247** [freeCodeCamp/freeCodeCamp#38313]
Link: https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-inventory-update/16019

Solution 2 uses nested maps to mutate the array. This is an anti-pattern. 

> You shouldn't be using map if:
> 1. you're not using the array it returns; and/or
> 2. you're not returning a value from the callback.

[Source: MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)

`.map()` is a higher-order function, and using it to mutate the calling array will confuse learners about its purpose.

**Comment by RandellDawson** [comment]
@elisecode247 We could change all the `map`s to `forEach`s.  Would that suffice?

**Comment by elisecode247** [comment]
Yes, that works.

**Comment by RandellDawson** [comment]
@elisecode247 Done.
