### ISSUE TITLE
Bug on CSS Grid: Divide the Grid into an Area Template

### ISSUE THREAD

**Issue by LSFerrand** [freeCodeCamp/freeCodeCamp#38319]
I'm learning how to code on your site and it's super! Just that I'm blocked on one particular question on CSS Grid: Divide the Grid into an Area Template. The instruction was to change the "advert" cell into empty cell. I removed "advert" and put (.) but it didn't work and I cannot move on to the next question.

Original code:

.container{
"header header header"
"advert content content"
"footer footer footer";
}

Instruction: make advert into empty cell

What I did:
.container{
"header header header"
". content content"
"footer footer footer";
}

Please help me to fix this!
Thanks a lot in advance!!

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
