### ISSUE TITLE
Broken Tests on challenge Basic CSS: Use Attribute Selectors to Style Elements

### ISSUE THREAD

**Issue by enigma0160** [freeCodeCamp/freeCodeCamp#38329]
**Describe your problem and how to reproduce it:**
This is expected to work, and it works in the preview.
There is a space before and after the `=` symbol.
```css
  [type = 'checkbox'] {
    margin-top: 10px;
    margin-bottom: 15px;
  }
```
It fails tests with this error, although it is expected to pass.
```
// running tests
The type attribute selector should be used to select the checkboxes.
```
The same code without the spaces passes.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/basic-css/use-attribute-selectors-to-style-elements

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 79.0.3945.130
* Operating System: Fedora 31

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Sky020** [comment]
Whilst I agree there is no reason the tests should not pass, I think it is important to note that having space on either side of the `=` is not good syntax, and could cause issue with integration with SASS. HTML is just so forgiving.
https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

**Comment by enigma0160** [comment]
Oh, I didn't know that wasn't good practice. It would be nice if it was mentioned in the lesson. I agree, if it's not good practice then, it would be best to fail the test and mention such an error message.

**Comment by moT01** [comment]
I don't think it's necessary to point out the best practices here. This is the basic css section so if it's valid css, it should pass the tests. I think just adjusting the one test would be enough. [Here's the file](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-css/use-attribute-selectors-to-style-elements.english.md#tests)

**Comment by kshashwat007** [comment]
Hi, Wanted to ask if its possible to work on this issue?

**Comment by ahmadabdolsaheb** [comment]
@kshashwat007, please go ahead 👍. No assignment is necessary as described in our [contribution docs](https://contribute.freecodecamp.org/#/index?id=where-do-i-start-if-i-want-to-work-on-an-issue). The first comprehensive PR will be considered for review.

**Comment by moT01** [comment]
There's an actually an open PR to fix this @kshashwat007. I would look for another issue.

**Comment by FiberesimaJoseph** [comment]
hello have work on this issue and seen some other contribution to this issue and the solution provide is this, which suit it most .
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, monospace;
  }

  p {
    font-size: 16px;
    font-family: monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }

  .silver-background {
    background-color: silver;
  }
  [type='checkbox'] {
    margin-top: 10px;
    margin-bottom: 15px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<main>
  <p class="red-text">Click here to view more <a href="#">cat photos</a>.</p>
  
  <a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>
  
  <div class="silver-background">
    <p>Things cats love:</p>
    <ul>
      <li>cat nip</li>
      <li>laser pointers</li>
      <li>lasagna</li>
    </ul>
    <p>Top 3 things cats hate:</p>
    <ol>
      <li>flea treatment</li>
      <li>thunder</li>
      <li>other cats</li>
    </ol>
  </div>
  
  <form action="/submit-cat-photo" id="cat-photo-form">
    <label><input type="radio" name="indoor-outdoor" checked> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label><br>
    <label><input type="checkbox" name="personality" checked> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Energetic</label><br>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</main>

**Comment by D4rk-night** [comment]
That was the best solution I found:

<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, monospace;
  }

  p {
    font-size: 16px;
    font-family: monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }

  .silver-background {
    background-color: silver;
  }
  [type='checkbox']{
    margin-top: 10px;
    margin-bottom: 15px;

  }
</style>
