### ISSUE TITLE
Waypoint: Target Elemeny by Class not working

### ISSUE THREAD

**Issue by KristenWilde** [FreeCodeCamp/FreeCodeCamp#3832]
Hi,

I've added 
$(".well").addClass("animated shake");
to the code and it doesn't pass the tests. I've tried refreshing the page, restarting the browser, and refreshing the code.

**Comment by ltegman** [comment]
I'm unable to repro this. If you are still experiencing this issue please reply with the full code you're submitting that does not work.

Thanks and happy coding!
