### ISSUE TITLE
Broken links from the forum

### ISSUE THREAD

**Issue by BoyeongYoon** [freeCodeCamp/freeCodeCamp#38323]
**Describe your problem and how to reproduce it:**
The relevant links are broken.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-title-case-a-sentence/16088

**Tell us about your browser and operating system:**
* Browser Name:  Google Chrome
* Browser Version: 
* Operating System: MacOS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screen Shot 2020-03-06 at 11 25 14 AM](https://user-images.githubusercontent.com/30683150/76101969-44620480-5f9d-11ea-87ae-90ee17d3a104.png)

![Screen Shot 2020-03-06 at 1 06 40 PM](https://user-images.githubusercontent.com/30683150/76109989-9c076c80-5fab-11ea-8edf-d1fadd186f78.png)

![Screen Shot 2020-03-06 at 1 09 13 PM](https://user-images.githubusercontent.com/30683150/76110050-c35e3980-5fab-11ea-82e3-1047bd9c1682.png)

**Comment by hassaanp** [comment]
@RandellDawson the links mentioned have the incorrect base url. It is supposed to be `.org` instead of `.com`

Don't have access to edit this.

**Comment by RandellDawson** [comment]
@hassaanp Yes, we are aware of this problem.  There are actually hundreds of such instances I found across the Guide.  We are working on a solution.

**Comment by RandellDawson** [comment]
@BoyeongYoon @hassaanp This issue is now resolved.  A change was made to the DNS settings, so that `forum.freecodecamp.com` now correctly forwards to `freecodecamp.com/forum`.
