### ISSUE TITLE
Program aplication is wrong

### ISSUE THREAD

**Issue by fernandousmail** [freeCodeCamp/freeCodeCamp#38328]
Challenge: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/use-getters-and-setters-to-control-access-to-an-object

If user were to SET a farenheit temperature, it would be passed through the celsius to farenheit equation storing a wrong value

**Comment by RandellDawson** [comment]
@fernandousmail Not exactly sure what you mean.  The `Thermostat` should be initialized by passing a value in Fahrenheit.    After initialization, a user should be able to **set** the temperature in Celsius.  Regardless, the **get** should always return the value in Celsius.

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
