### ISSUE TITLE
Unsubscribe link not working

### ISSUE THREAD

**Issue by povilasraciunas** [freeCodeCamp/freeCodeCamp#38322]
1. Getting emails from quincy@freecodecamp.org
2. Tried clicking on unsubscribe link (https://www.freecodecamp.org/ue/WWtGC_9cRB0T0oqlPD8sw) 
3. Getting "Oops! Something went wrong. Please try again in a moment." error message every single time I press on link.
4. Result: not possible to unsubscribe.

**Comment by raisedadead** [comment]
Hi @povilasraciunas 

Thanks for reporting this. 

As a work around, you can login to freeCodeCamp using the email that you receive the weekly emails on, and toggle the button off in the settings here:

https://freecodecamp.org/settings

Also, can you send us an email at: support@freecodecamp.org, with your registered email (the ones that you are getting emails from Quincy)?

We could look into your user records and address this further.
