### ISSUE TITLE
Add a help text about top contributors on the profile

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#38334]
> It might be nice to add a hover-over and/or link over the `Top Contributor` verbiage that links to a page explaining what it means to be awarded this honor. 
>
> I say this because right below this designation, the heat map shows.  My current heat map looks below, because I have finished most of the challenges and do not complete very many (if any) each day.  Some might think the Top Contributor and the heat map are related.

_Originally posted by @RandellDawson in https://github.com/freeCodeCamp/freeCodeCamp/issues/38138#issuecomment-596090813_

We would want to have a link to the news article that @QuincyLarson has posted. It could be right below the "Top Contributors" in small text.

Here is the link:
https://www.freecodecamp.org/news/fcc100-top-contributors-2019

**Comment by thecodingaviator** [comment]
@raisedadead would it not be better to link to an article which just describes what Top Contibutors are? I believe the way we're doing it right now will need updatin every year and every new year, the previous article would get removed i.e. the article would not be linked to the year

**Comment by RandellDawson** [comment]
@thecodingaviator That is what [I suggested in my comment on PR 38138](https://github.com/freeCodeCamp/freeCodeCamp/issues/38138#issuecomment-596090813).

**Comment by ahmadabdolsaheb** [comment]
I see your point, maybe we should have a link with definition of a top contributor a list of all 2018/2019 contributors. it would be updated annually, but it would be inclusive.
