### ISSUE TITLE
Night mode doesnt work by me.

### ISSUE THREAD

**Issue by rocnogu** [freeCodeCamp/freeCodeCamp#38336]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**

**To Reproduce**
1. Go to '...' https://www.freecodecamp.org/settings
2. click on night mode ON
4. See error: Something is not quite right. A report has been generated and the freeCodeCamp.org team have been notified.

**Expected behavior**
Night mode 

**Screenshots**
no

**Desktop (please complete the following information):**
 - OS: [] win 10 pro 64b 18262.657
 - Browser [ chrome, ]
 - Version [] Version 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
i tried to log in from microsoft edge and torch browser but it failed. should i open one more bug report?

**Comment by RandellDawson** [comment]
@rocnogu Are you logged into your account when this happens?

**Comment by rocnogu** [comment]
@RandellDawson  
bot or something? your comments look absolutely random with quite zero connection to the reality. either a bot or ... very unintelligent person. which is fine by me as long as you keep a distance from me. so, if you don't know a solution, DO NOT POST ANY COMMENTS.
it says: Member of freeCodeCamp.org but that means you actually know the system. do you?
can you go to https://www.freecodecamp.org/settings without logging in?

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...' https://www.freecodecamp.org/settings
2. click on night mode ON
4. See error: Something is not quite right. A report has been generated and the freeCodeCamp.org team have been notified.

and again
 if you don't know a solution, DO NOT POST ANY COMMENTS.

**Comment by lasjorg** [comment]
@rocnogu There is no need for personal insults or caps. You may want to go over the [Contribution Guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md) and read the [Code of Conduct](https://www.freecodecamp.org/news/code-of-conduct/).

1. Do you get any error messages in the console when you try to switch modes?

2. Can you try in [Incognito mode](https://support.google.com/chrome/answer/95464) and/or in Firefox just to test?

I can't reproduce it. So we need something more to go on.

**Comment by rocnogu** [comment]
@lasjorg
i dint yet started the insults. its called personal observation. look it up.

1 what consoles and what modes? (did you actually read the ''To Reproduce'' ????? i have the feeling you didnt)

2 i don't have firefox at all. never had.

**Comment by rocnogu** [comment]
hm.. after bit thinking...
console is the settings page?
modes is night/light modes?

regardless firefox ill just repeat my self:
i tried to log in from microsoft edge and torch browser but it failed. should i open one more bug report?

**Comment by rocnogu** [comment]
firefox give the same error

**Comment by RandellDawson** [comment]
@ronaldcs I am closing this issue as you keep throwing out insults when we are only trying to help.

**Comment by raisedadead** [comment]
Hi @rocnogu 

I am from the freeCodeCamp.org Staff.

I would like to draw your attention that freeCodeCamp is safe place for all. You are currently in violation of our [code of conduct](https://www.freecodecamp.org/news/code-of-conduct/), with comments.

We sure understand that you would like to report something is broken or not working, but we absolutely do not tolerate any violation of the CoC.

We have gone ahead and banned your account from posting comments on freeCodeCamp.org

If you wish to get this re-instated please let us know, why we should do that. Have a great day ahead.

Thanks.
