### ISSUE TITLE
curriculum not on 100%

### ISSUE THREAD

**Issue by rocnogu** [freeCodeCamp/freeCodeCamp#38335]
short story: curriculum not on 100%
long story:
""Basic HTML and HTML5"" is ""Not Passed"" because ""Use the value attribute with Radio Buttons and Checkboxes"" doesn't complete.
 I complete it 3 times and it shows: ""Basic HTML and HTML5
100% complete""

but in the curriculum is not.

**Comment by RandellDawson** [comment]
@rocnogu I am not understanding what the problem is.  Can you explain how we can recreate the issue?

**Comment by rocnogu** [comment]
@RandellDawson   i finish the assignment but the system doesn't recognize it.

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

**Comment by rocnogu** [comment]
how about you do it?
it's literally your job.
or you are here just to spam random stuff till people get pissed off and leave?

**Comment by RandellDawson** [comment]
I am a volunteer as most of Free Code Camp's contributors are.
