### ISSUE TITLE
CSS Grid: Use Media Queries to Create Responsive Layouts

### ISSUE THREAD

**Issue by tsabunkar** [freeCodeCamp/freeCodeCamp#38333]
CSS Grid Challenge : When the viewport width is 400px or more, make the header area occupy the top row completely and the footer area occupy the bottom row completely.

```
  @media (min-width: 400px){
    .container{
      grid-template-areas:
      /* Only change code below this line */
        "header header"
        "advert content"
        "footer footer";
      /* Only change code above this line */
    }
```

But still **not** able to pass the test case : When the viewport is 400px or more, container class should have a grid-template-areas property in which the header and footer areas occupy the top and bottom rows respectively and advert and content occupy the left and right columns of the middle row.

**Comment by rkdgr8** [comment]
This seems to be a common bug in all challenges related to grid-template areas. As rightly described in https://www.freecodecamp.org/forum/t/bug-in-one-of-the-css-grid-challenges/356023 , test cases pass only when all the comments are removed inside the grid-template-areas. Would like to resolve this issue as my first OSS contribution.

**Comment by tsabunkar** [comment]
> This seems to be a common bug in all challenges related to grid-template areas. As rightly described in https://www.freecodecamp.org/forum/t/bug-in-one-of-the-css-grid-challenges/356023 , test cases pass only when all the comments are removed inside the grid-template-areas. Would like to resolve this issue as my first OSS contribution.

Yes, @rkdgr8 you are correct just by removing the comments inside .container class the test case had passed. Thanks for your response. Please go-ahead and resolve this issue !!
