### ISSUE TITLE
Mobile forum theme navbar disappears with scroll

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#38346]
I've created a video demonstrating this bug here: https://youtu.be/MAq8fLMndmY

**Comment by AshNaz87** [comment]
@ahmadabdolsaheb Can help with this issue if you would like

**Comment by ahmadabdolsaheb** [comment]
sure, @AshNaz87.

**Comment by AshNaz87** [comment]
@ahmadabdolsaheb Cannot replicate locally. Is there another channel where discussions can take place?

**Comment by ahmadabdolsaheb** [comment]
should be able to if you toggle device toolbar in devtools and scroll up and down in multiple pages.
It is most likely that the display is set to none when scrolling down to open room for the title. but since we have already removed the tile, we should just make sure the local navigation is always displayed.

**Comment by AshNaz87** [comment]
`/forum` doesn't render the forum in development. But yes, elements did have the declaration `display: none;`

**Comment by ahmadabdolsaheb** [comment]
Yes so /forum is another application (discourse)
There are two ways for fixing this:
1) run discourse cli and connect it to discourse theme maker. Then pull our discourse theme, make changes and view your changes in the discourse theme maker.

2) or if the changes are minor, change the css using the devtools until you get the desired results and submit a pr.

**Comment by ahmadabdolsaheb** [comment]
The fix has been deployed to production. Please reopen this issue if the problem still persists.
