### ISSUE TITLE
Add test to Set the child prototype... challenge to check for correct output

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#38349]
> We could try and add an additional test that would make sure  `beagle.eat()` logs "nom nom nom" to the console

_Originally posted by @RandellDawson [here](https://github.com/freeCodeCamp/freeCodeCamp/pull/38267#discussion_r388450988)_

**Comment by akhilkh2000** [comment]
Can you explain exactly where the issue is

**Comment by marioweid** [comment]
The issue i see is that, if i overwrite the eat function f.e. i still pass the test even if it doesnt print out "nom nom nom" like it should, based on the comment.
```
Dog.prototype = Object.create(Animal.prototype)
Dog.prototype.constructor = Dog
Dog.prototype.bark = function (){
    console.log("Woof!")
}
Dog.prototype.eat = function(){
    console.log("im eating in a weird way")
}


// Add your code above this line

let beagle = new Dog();

beagle.eat(); // Should print "nom nom nom"
```
Console output:
```
im eating in a weird way
Woof!
```
Still passing the lession

**Comment by marioweid** [comment]
We could spy on the console and assert, that after beagle.eat() is called, the spy got called once with "nom nom nom".
Since we are using chai allready, i assumed we could just use it in the markdown files. 
My code so far (`./curriculum/challanges/english/02-javascript-algoriths-and-data-structures/add-methods-after-inheritance.english.md`):
```yaml
  - text: <code>beagle.eat()</code> should print <code>"nom nom nom"</code>
    testString: |
      const spy = chai.spy.on(console,'log');
      beagle.eat();
      expect(spy).to.have.been.called.with("nom nom nom");
```
Maybe it's helping someone :)

**Comment by ojeytonwilliams** [comment]
@marioweid it's a nice idea, but we only use the core `chai` package, not `chai-spies`.  A custom solution where you proxy `console.log` should work, albeit with a little more effort.

**Comment by hassaanp** [comment]
I tried doing this
```
  - text: <code>beagle.eat()</code> should print <code>"nom nom nom"</code>
    testString: |
      console.log = function(msg){throw msg;}
      expect(beagle.eat()).to.throw("nom nom nom");
```

Unfortunately, this does not work.

**Comment by ojeytonwilliams** [comment]
@hassaanp that's almost right and it's a neat approach.  I played with it for a bit and came up with:

```yml
  - text: <code>beagle.eat()</code> should log <code>"nom nom nom"</code>
    testString: |
      console.log = function(msg){throw msg;}
      assert.throws(() => beagle.eat(),"nom nom nom");
```

Since each test is isolated, there's no need to restore the original `console.log`.

**Comment by hassaanp** [comment]
@ojeytonwilliams awesome!
Do you mind if I push this or will you do that?

**Comment by ojeytonwilliams** [comment]
> Do you mind if I push this or will you do that?

Not at all, go for it!

**Comment by marioweid** [comment]
@hassaanp 
I guess you can add the change for all languages :)

**Comment by RandellDawson** [comment]
> I guess you can add the change for all languages :)

@marioweid No need to do that.  We are working to using the English version of the file's `textString` to work across all languages.  See PR #38040 for more information.

**Comment by RandellDawson** [comment]
@hassaanp Once we merge your PR, you can find all the challenges where we need to test for a specific value being logged to the console.

**Comment by hassaanp** [comment]
> @hassaanp Once we merge your PR, you can find all the challenges where we need to test for a specific value being logged to the console.

Acknowledged. Thanks for the heads up. I will push the fixes for all such instances.

**Comment by RandellDawson** [comment]
@hassaanp Make sure to put the others on a different PR, so as not to hold up your PR.

**Comment by hassaanp** [comment]
@RandellDawson 
of course :)
