### ISSUE TITLE
Oops! Something went wrong. Please try again in a moment.

### ISSUE THREAD

**Issue by rocnogu** [freeCodeCamp/freeCodeCamp#38342]
**Describe your problem and how to reproduce it:**
can't log in from other browsers(edge and torch) than chrome
it gives me the ""Oops! Something went wrong. Please try again in a moment."" error

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/?messages=danger%5B0%5D%3DOops%2521%2520Something%2520went%2520wrong.%2520Please%2520try%2520again%2520in%2520a%2520moment.

* Browser Name:  torch
* Browser Version: Version 69.0.0.2990 (Official Build) (32-bit)
* Operating System:  win 10 pro 64b 18262.657

**Comment by rocnogu** [comment]
edge and firefox do the same
logging with email code give the same error as well.

**Comment by hassaanp** [comment]
Please take a look at this [comment](https://github.com/freeCodeCamp/freeCodeCamp/issues/37457#issuecomment-544905365)

**Comment by hassaanp** [comment]
This has been addressed in #37457 
Closing this.
