### ISSUE TITLE
Update redux challenge to allow for backticks

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#38341]
The challenge:
https://www.freecodecamp.org/learn/front-end-libraries/redux/use-const-for-action-types

Forum thread with more information:
https://www.freecodecamp.org/forum/t/backtick-strings-not-accepted/356848

The proposed change to the test:
https://www.freecodecamp.org/forum/t/backtick-strings-not-accepted/356848/4

New contributors are welcome.

**Comment by AshNaz87** [comment]
@RandellDawson Would like to do this

**Comment by AshNaz87** [comment]
@RandellDawson PR submitted
