### ISSUE TITLE
curriculum not on 100% 

### ISSUE THREAD

**Issue by rocnogu** [freeCodeCamp/freeCodeCamp#38343]
""Basic HTML and HTML5"" is ""Not Passed"" because ""Use the value attribute with Radio Buttons and Checkboxes"" doesn't actually 'complete'.

pic1
I complete it 3 times and it shows: ""Basic HTML and HTML5
100% complete""

pic2
but in the curriculum its not complete.

@RandellDawson decided to close the first request without solving it.
so, someone else might. i hope.

![2](https://user-images.githubusercontent.com/22155288/76155889-d2033880-60f2-11ea-9777-0e06b6fc0f8d.jpg)
![1](https://user-images.githubusercontent.com/22155288/76155894-d6c7ec80-60f2-11ea-87f8-abebb561ffd0.jpg)

**Comment by thecodingaviator** [comment]
I'm not sure what is happening with you. I have the challenge incomplete too but I get this:
![image](https://user-images.githubusercontent.com/34807532/76157026-4d7fdc80-6129-11ea-8aae-131dd37649f6.png)
![image](https://user-images.githubusercontent.com/34807532/76157028-5d97bc00-6129-11ea-97cd-4845210b1c3a.png)
What is the link you're working on?

**Comment by hassaanp** [comment]
@rocnogu 
Can you try clearing your browser cache or using the incognito mode? See if that helps. Please share your browser information too so we can reproduce it.

**Comment by moT01** [comment]
I cannot reproduce this. Is it only this challenge @rocnogu? Have you completed any other challenges that have counted after this first occurred? You could try logging in with a different browser.

**Comment by RandellDawson** [comment]
Since I had not actually worked through this challenge, in the list of challenge for that the section, itcorrectly showed that I had not.  I added my solution code and passed the tests.  After submitting, I went back to the list of the challenges in the section and validated, the radio button was marked.  I recorded a video of the process.  I used the latest version of Chrome.

![ezgif com-video-to-gif (8)](https://user-images.githubusercontent.com/5313213/76164341-68435880-610b-11ea-88c0-9766a437741f.gif)

**Comment by ojeytonwilliams** [comment]
I think there is a problem with OPs account.  In the first screenshot there is a flash message (hidden beneath the completion modal) and I suspect that's saying that the server could not be reached.  The client behaviour will be weird if that's the case, so I don't think we can diagnose until their account has been fixed.

**Comment by raisedadead** [comment]
This user has been hostile in their queries. We have received email as well, I found and deleted their duplicate account. For now, we have take administrative steps preventing them from commenting on the GitHub tracker.

Issue stands closed, unless similar is reported by someone else.
