### ISSUE TITLE
"Run the Tests" button on freeCodeCamp doesn´t work

### ISSUE THREAD

**Issue by aguskurincic** [freeCodeCamp/freeCodeCamp#38357]
I have a problem that the button doesn´t work AT ALL. It starts at "if/else" statements on the Javascript course. The button doesn´t run the code, literally nothing happens. I search already on the web for a solution but nothing, and I can´t continue practicing with this situation.

**Comment by RandellDawson** [comment]
@aguskurincic Do you see any errors showing in the browser console (not the FCC console)?

**Comment by moT01** [comment]
Can you be more specific about your problem @aguskurincic? what exactly are you doing that causes this, what browser/operating system you are using - maybe some screen shots. Anything to help us understand the problem is a big help. Is it only one specific challenge? or is it many/all of the challenges?

**Comment by raisedadead** [comment]
Hi @aguskurincic let us know with additional clarifications as requested above and we can have this re-opened. You can also reach out to our [community forum](https://www.freecodecamp.org/forum) for more help.

**Comment by aguskurincic** [comment]
@RandellDawson it shows an undefined error in the console, but never happened with this page. The button must run the code anyways

**Comment by aguskurincic** [comment]
@moT01 I´m almost 67/68% of the course complete using Chrome, always works good. When this happens I change to Firefox, but still the same, it looks like is problem of the page. I´m using Widnwos 10 Pro. But this doesnt make sense, I did amost 3/4 parts of the course without problem, the page has a bug there I think. It´s the "Chaining If Else Statements" challenge. But the one before starts with this problem, somehow I could run it.

**Comment by aguskurincic** [comment]
> 
> 
> Hi @aguskurincic let us know with additional clarifications as requested above and we can have this re-opened. You can also reach out to our [community forum](https://www.freecodecamp.org/forum) for more help.

Would be cool if you re-open this.

**Comment by aguskurincic** [comment]
Forget it, I could solve it! Thanks

**Comment by RandellDawson** [comment]
@aguskurincic What was the issue?

**Comment by aguskurincic** [comment]
It had a couple of { } more than I need, really weird that the page doesn´t show you what is going on, since you are learning...

**Comment by aguskurincic** [comment]
@RandellDawson It had a couple of { } more than I need, really weird that the page doesn´t show you what is going on, since you are learning...

**Comment by ojeytonwilliams** [comment]
@aguskurincic do you remember what the buggy code was?  The console should be more informative than 'undefined error'.
