### ISSUE TITLE
Right-Click on Monaco editor missing options

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#38352]
**Describe the bug**
Right-clicking on the Monaco editor in a freeCodeCamp lesson brings up the options menu, but it appears to be missing features/options.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any lesson on the curriculum
2. Right-click on the editor
3. Behold the selection menu appearing miss-formatted.

**Expected behaviour**
I would expect to see more options. At the least, I expect to see the option to _paste_ from clipboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/51722130/76349618-4233d900-6302-11ea-8730-7e46a7133a94.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80.0.3987

**Additional context**
This issue was pointed out in this thread: https://www.freecodecamp.org/forum/t/copy-and-paste-paste-function-do-not-work/357623

**Comment by moT01** [comment]
> Behold the selection menu appearing miss-formatted.

What formatting do you mean? It looks fine to me, other than that the paste option is missing. I'm not sure where why that isn't there - it probably should be. Is there anything else missing that you noticed @Sky020?

**Comment by Sky020** [comment]
@moT01 , I do not know how it appears on your screen. From the screenshot I sent, I presumed there are 3 missing options, and it looks as though something in their text has caused them to render as rectangles.

**Comment by MyIrish1993** [comment]
What the hell is this? How did I end up on a geek thread

**Comment by MyIrish1993** [comment]
What are you guys doing? Is this what nerds do? It's kinda cool y'all. Are
we deciphering NASA or what? I'm down

**Comment by Sky020** [comment]
As I was trying to load fCC locally, I got this error and wondered if it is related:
>npm WARN tarball tarball data for monaco-editor@0.18.1 (sha512-fmL+RFZ2Hrezy+X/5ZczQW51LUmvzfcqOurnkCIRFTyjdVjzR7JvENzI6+VKBJzJdPh6EYL4RoWl92b2Hrk9fw==) seems to be corrupted. Trying one more time.

**Comment by moT01** [comment]
I don't think those rectangles are something missing. I've always just thought there were separators, like an `<hr>`. Seems to make sense since the options sort of have different categories. I suppose they could be something missing, but I don't think that's the case.

**Comment by RandellDawson** [comment]
FYI - The screenshot on the left is what it used to look like before the site color changes and the one on the right is the current version.

![Untitled-3](https://user-images.githubusercontent.com/5313213/76424867-0cc0d700-6366-11ea-992f-209cc47653b8.jpg)

**Comment by ojeytonwilliams** [comment]
> As I was trying to load fCC locally, I got this error and wondered if it is related:
> 
> > npm WARN tarball tarball data for monaco-editor@0.18.1 (sha512-fmL+RFZ2Hrezy+X/5ZczQW51LUmvzfcqOurnkCIRFTyjdVjzR7JvENzI6+VKBJzJdPh6EYL4RoWl92b2Hrk9fw==) seems to be corrupted. Trying one more time.

That's unlikely to be related.  Looks like the package did not download correctly, which should result it in failing to work at all, rather than behaving strangely.

**Comment by Sky020** [comment]
@RandellDawson So it is just formatting?
Was it ever intended that the option to _paste_ not be available? Or, can that be opened as a feature request?

**Comment by RandellDawson** [comment]
@Sky020 It never had `paste`.  I personally prefer it does not.  It encourages users to copy/paste code instead of typing it out (which helps yours learn more).

**Comment by RandellDawson** [comment]
I do think the separators are a bit too wide (vertically).
