### ISSUE TITLE
Testing Objects for Properties - Tests too weak

### ISSUE THREAD

**Issue by nkskalyan** [freeCodeCamp/freeCodeCamp#38361]
**Describe your problem and how to reproduce it:**
In https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/testing-objects-for-properties, my wife made the test pass with if else condition for all keys in the javascript object.
I expect the tests should have a stronger test enforcement by testing for other objects in codebase. Would love to contribute to this one by myself

```function checkObj(checkProp) {
  // Only change code below this line
  if(checkProp == "gift") {
    return "pony";
  } else if(checkProp == "pet") {
    return "kitten";
  } else if(checkProp == "bed") {
    return "sleigh";
  } else {
    return "Not Found";
  }
  // Only change code above this line
}```

I'm teaching my wife to code with Freecodecamp, thanks a lot for all the effort in here :) 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/testing-objects-for-properties

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 
* Operating System: Mac


**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@nkskalyan You could use the `Before Test` or `After Test` section in the challenge file, to create some additional objects to test.  The only issue of creating additional objects and tests for those objects, is that you would need to modify the instructions and code seed to make it where the `checkObj` function takes two arguments.  One for the property to check and one for the object being checked.  Also, the `text` for each test would need to show the user the full object in the call to the function and the expected return value.  See below for an example:
```yml
    - text: <code>checkObj({ gift: "pony", pet: "kitten", bed: "sleigh" }, "gift")</code> should return <code>"pony"</code>.
      testString: assert(checkObj(testObj1, "gift") === "pony");
```

**Comment by RandellDawson** [comment]
We are seeking PRs to fix this issue.
