### ISSUE TITLE
Having to add --no-verify to all commits to freeCodeCamp repo

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#38363]
This may or may not affect others.  It could be a Windows only thing.  About 2 weeks ago, I started having to add `--no-verify` option to all of my commits to the freeCodeCamp repo.  @ojeytonwilliams and I attempted to figure out what settings may have changed in the repo that would affect Husky, but did not come up with any.

I first tried uninstalling and reinstalling Husky using the package.json `npm run hooks:uninstall` and then `npm run hooks:install`, but that did not change anything.  

Next, I deleted the repo from my machine and cloned/reinstalled the repo on my machine.  That did not change anything either.

I am using Windows 10 64bit Home edition and have tried using the Windows cmd line, GitBash, and Windows PowerShell with no success. I also validated that I did not have a globally installed version of Husky that might have been causing some kind of conflict with the repo version.

Here is an example of what I see when I make a change to a file in the `doc` folder:
```
D:\Coding\fcc>git commit -m "fix: testing change"
husky > pre-commit (node v10.15.0)
The system cannot find the path specified.
No staged files match any of provided globs.
husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by Sky020** [comment]
Forgive me, if this has nothing to do with the issue, but could it be linked to this missing import:
>internal/modules/cjs/loader.js:626
>    throw err;
>    ^
>
>Error: Cannot find module '@freecodecamp/challenge-md-parser'
>Require stack:
>- C:\Users\shauh\Documents\freeCodeCamp\freeCodeCamp\curriculum\getChallenges.js

This was linked to an error I got with the `lint` script.

**Comment by RandellDawson** [comment]
@Sky020 I do not think so. I have no trouble running the development site.  It is just affecting my ability to commit to the repo locally.  Really, the only trouble is that I have to add the extra option after I first run the commit to check for actual linting issues.  I basically have to run `npm commit -m "some message"` to check for linting issues and then `npm commit -m "some message" --no-verify` to perform the actual commit.

**Comment by raisedadead** [comment]
Hi Randell, we would need to eliminate causes and isolate the issue. 

- Have you done a clean install of the repo and seen the same issue? Yes/No
- Have you cloned a fresh copy of the repo and seen the same issue? Yes/No
- Which version of `node` are you on?
- Which version of `npm` are you on?

**Comment by RandellDawson** [comment]
> Have you done a clean install of the repo and seen the same issue? Yes/No

Yes

> Have you cloned a fresh copy of the repo and seen the same issue? Yes/No

Yes

> Which version of node are you on?

v10.15.0

> Which version of npm are you on?

6.4.1

**Comment by ojeytonwilliams** [comment]
From our investigations, it seemed like it's some mismatch between different shells.  The error message appeared when husky tried to execute a command with cwd of `D:/some/path`, but it was running in git-bash, right?  Why it's started doing that all of a sudden, I don't know.

**Comment by raisedadead** [comment]
> ... it seemed like it's some mismatch between different shells.

Can you elaborate more on this?

**Comment by ojeytonwilliams** [comment]
> Can you elaborate more on this?

I can go through my thinking, but clearly I don't understand it.

So, when `husky` tries to run a hook it calls

```js
const cwd = path.resolve(scriptPath.split('node_modules')[0]);
```

to get the directory.  On Randell's machine this is a Windows path (something like `D:\path\to\fcc`).

`cwd` is then used to execute a script via `execa`

```js
console.log(`husky > ${hookName} (node ${process.version})`);
execa.shellSync(command, { cwd, env, stdio: 'inherit' });
```

we isolated the problem to there.  That command (`lint-staged`) fails to execute properly, an error is throw and the commit aborted.  

My suspicion about the shells was that this was running inside git-bash in `d/path/to/fcc` (not `D:\path\to\fcc`), but that might be irrelevant.  It could be something to do with `lint-staged`, we haven't investigated further yet.

**Comment by RandellDawson** [comment]
@raisedadead Adding to what @ojeytonwilliams said above, I manually modified the `execa.shellSync` line to use `/d/path/to/fcc` and it still did not work.
