### ISSUE TITLE
Add solutions to Basic Bonfires

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3836]
Reference this closed pull request if you're need a guide as to the formatting: https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3835

For each challenge, add a solution like this to it's object: 
      "solutions": [
        "function pairwise(arr, arg) {\n  var sum = 0;\n  arr.forEach(function(e, i, a) {\n    if (e != null) {      \n      var diff = arg-e;\n      a[i] = null;\n      var dix = a.indexOf(diff);\n      if (dix !== -1) {\n        sum += dix;\n        sum += i;\n        a[dix] = null;\n      }  \n    }\n  });\n  return sum;\n}\n\npairwise([1,4,2,3,0,5], 7);\n"
      ],

Solutions can be pulled from @dting's profile (he has completed all of them). Open up the 

Once you have opened his solution, open up the console and paste in this JavaScript:
JSON.stringify(editor.getValue());

Copy the string that it returns and paste it into your new solutions array. Make sure you get rid of any excess double quotes at the beginning or end of the string.

**Comment by abhisekp** [comment]
@dting has solutions listed here https://tonicdev.com/dting/

**Comment by krantzinator** [comment]
Thanks, I'll add in these tonight
