### ISSUE TITLE
Implement Infra for Lecture Challenges

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#38362]
We are going to embed video lectures for the Python curriculum. We need additional infrastructure for the Youtube embeds.

We are going to use Plyr - https://github.com/sampotts/plyr for this.

This lib, has the below format for embedding videos:

  ```html
  <div class="plyr__video-embed" id="player">
    <iframe
        src="https://www.youtube.com/embed/3muQV-Im3Z0?iv_load_policy=3&amp;modestbranding=1&amp;playsinline=1&amp;showinfo=0&amp;rel=0&amp;enablejsapi=1"
        allowfullscreen
        allowtransparency
        allow="autoplay"
    ></iframe>
  </div>
  ```

We should be able to just use the `3muQV-Im3Z0` as the identifier from the markdown syntax and construct the player from it. The example above is just for reference and the actual config for the player will be finalized later during development.

Here are some things that we need to address as a part of this:
- [ ] Create a new view template (like others) for this.
- [ ] Figure out and create the react component for the player for `Plyr`. 
- [ ] Update the challenge parser and schema to have a field, or key that can be used, for example: `forumTopicId`

**Comment by ojeytonwilliams** [comment]
@raisedadead we're not planning on going back to Plyr are we?  I assume not, so I'm closing this.
