### ISSUE TITLE
General UI/UX improvements

### ISSUE THREAD

**Issue by Tuuben** [freeCodeCamp/freeCodeCamp#38376]
I've been going around the site a bit and there are a lot of small fixes that could be done to improve the UI/UX of FreeCodeCamp.org. For the sake of length, I kept it to the home view. 

Here is a couple of things.

**Make clickable list buttons full width.**

Currently:
![before-list](https://user-images.githubusercontent.com/22411478/76843091-f58d5800-6843-11ea-83df-8d0af2882b1f.gif)

Full width hover:
![after-list](https://user-images.githubusercontent.com/22411478/76843299-42712e80-6844-11ea-9d16-5efe93c696db.gif)

**Search results are very unreadable**

Current:
<img width="488" alt="Screenshot 2020-03-17 at 11 12 08" src="https://user-images.githubusercontent.com/22411478/76843390-646ab100-6844-11ea-948e-b2b3b3f4e5f9.png">

Suggested solution:
<img width="505" alt="Screenshot 2020-03-17 at 11 11 52" src="https://user-images.githubusercontent.com/22411478/76843413-6c2a5580-6844-11ea-9ec7-fc0b59bd1601.png">

**Home view is quite cluttered and unwelcoming**

Current:
<img width="1749" alt="Screenshot 2020-03-17 at 11 35 59" src="https://user-images.githubusercontent.com/22411478/76843507-8ebc6e80-6844-11ea-9f9d-3aa64700c488.png">

Very quick fix suggestion, done by moving things around in the inspector. I would like to edit this page more extensively.
<img width="1748" alt="Screenshot 2020-03-17 at 11 35 49" src="https://user-images.githubusercontent.com/22411478/76843651-c4f9ee00-6844-11ea-90d1-1c48a37adeeb.png">

I like what you're doing with this project and I'd love to contribute and work on these things to improve the site. I'd love to hear your input @QuincyLarson and @ahmadabdolsaheb.

**Comment by ojeytonwilliams** [comment]
Just to make sure: the change to search is the addition of lines separating the results, not the removal of the blue background?  An indicator of the currently selected result is important.

That caveat aside, these look like good changes.

**Comment by Tuuben** [comment]
No, the blue background on hover is good. I would keep it.

**Comment by moT01** [comment]
I like these - I would also change that blue hover on the search results to our dark blue. And possibly use a lighter blue for the background of the "since 2014" sentence - and include the companies in the box.

**Comment by DannyBoris** [comment]
A newbie question. Are those suggestions that you want to implement or is it anyone can pull and try?

**Comment by Tuuben** [comment]
@DannyBoris I'm new to the project as well so I'm not too familiar with how things are done. But I guess if you want to tackle some part of this issue we could split the tasks. Since there are multiple things here and they're easy to separate. Then we could do 2 pull requests? Maybe @ojeytonwilliams can give some input on this? :) Otherwise, you can check issues tagged with "help wanted".

**Comment by moT01** [comment]
These are suggestions for improvements @DannyBoris. 

I would wait for more input for making a PR.

**Comment by DannyBoris** [comment]
@Tuuben Hey, 
Yeah let's take it easy. I have never actually contributed to open source and fcc seems like a good start (when it comes to small changes). ill also vote for waiting a bit more.
Thanks for the response

**Comment by ojeytonwilliams** [comment]
If you don't mind waiting, then you'll waste less time creating a feature that's not quite what's desired.  Chances are the broad strokes are what's wanted, but perhaps not the specifics.  I can't speak for the core team, though.

As for the practicalities, small focused PRs are ideal.  They are easy to review and maintain, so splitting this into three different PRs (landing, search and curriculum) makes sense to me.  It's not critical, though, so however you want to divide it up is likely fine.

**Comment by ahmadabdolsaheb** [comment]
Thank you for the suggestions, here is my take:
1. let's implement the full width hover on map
2. I am onboard with search results padding and border addition. note: it should be updated for news, forum, and learn since the universal navigation is used across services.
3. the landing page could use an update. I believe the current mock looks good, but here are some considerations:

* the CTA button should be above the fold on 13 inch displays.
* it would be great if we could avoid the dark " since 2014" div
* we could probably make the front size difference a bit smaller
* the width of the CTA could be narrower

General note for the landing page: There are a variety of minimal text and cta landing pages around that we could use to inspired our re-design.

Also, since the landing page and the upper div of /learn look the same, they should use the same component.

**Comment by AshNaz87** [comment]
Happy to chip in when consensus is gathered

**Comment by DannyBoris** [comment]
Hey all, 
@ojeytonwilliams 's suggestions found reasonable. I be up for taking search once we can work on it

**Comment by moT01** [comment]
It's probably safe to make some PR's at this point. The hover effect and search results have some clarity on what needs to be done there. Not sure on the landing page. I still like my suggestion of changing the blue hover on search to one of our other blue's. But I think if PR's are made, we can probably tweak things from there if needed.

**Comment by Tuuben** [comment]
@DannyBoris I've made a PR for the menu list. Are you still interested to take a look at the search?

**Comment by alexgignilliat** [comment]
This is a great idea - willing to help if needed.

**Comment by ahmadabdolsaheb** [comment]
Thank you for your help everyone, I believe most of the items mentioned in this issue has been addressed.  Only the general aesthetics of the landing page remains that deserves an issue of its own.

I will close this issue for now. Please feel free to open an issue to discuss the landing page specifically.
