### ISSUE TITLE
Donation Implementation Enhancements

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#38373]
General:
- [x] Get the button and the text labels for the donate amounts in the modal from config.
- [x] Get the button and the text labels for the donate amounts in the certificates from config.
- [x] Unify donation forms and make them atomic
- [ ] Unify component state for Paypal and Stripe (overlap processing message when displaying)
- [ ] Add [Guidestar](https://www.guidestar.org/App_Themes/MainSite2/images/ProfilePageSvgs/profile-PLATINUM2019-seal.svg) and [SSL secure](https://23-59.net/wp-content/uploads/2017/02/SSL.png) images to the button of donation forms
- [ ] Add cypress tests for modal donation page
- [x] Add GA to all donation related buttons and views

PayPal:
- [x] Implement PayPal for one-time donations.
- [ ] The logging needs to be improved to fix errors: https://github.com/freeCodeCamp/freeCodeCamp/pull/38239/files#r392905021
- [ ] If a user is having a recurring donation before the rollout, we should handle those gracefully.
- [ ] an identifier other than e mail should be added to the donations 
- [ ] resolve double rendering of paypal button 
- [ ] Make the donation and amount dynamic and audit records

Stripe:
- [ ] Move to `@stripe/stripe-js` and `@stripe/react-stripe-js`
- [ ] Implement Payment Request button.
- [ ] Receive and react to web-hooks from stripe.

**Comment by ojeytonwilliams** [comment]
From the linked PR:

> Well I think we should be hooking up something similar to rollbar for this. And the reply is lost by PayPal, I did not say a way that they log it.

I couldn't find much about this, just what Ahmad pointed out: that they try again 25 times over the next 3 days.  That's if they either don't get a response or the response is not 200.   So, I guess we trigger that if we think that if it's conceivable that something weird could happen causing a valid POST to fail when it hits /update-paypal and that subsequent POSTs could work.

>  So we should depend on our logging for this.

Agreed, regardless of what we send back to PayPal.

**Comment by russsaidwords** [comment]
Can we add tabindex to the donation page as well? I can't tab through the form or the buttons available and that impacts accessibility. Thank you!

**Comment by raisedadead** [comment]
Making @ahmadabdolsaheb the owner.

**Comment by ahmadabdolsaheb** [comment]
I am closing this in favor of lists in trello cards.
