### ISSUE TITLE
[Broken]CSS Grid: Use Media Queries to Create Responsive Layouts

### ISSUE THREAD

**Issue by Saikamesh** [freeCodeCamp/freeCodeCamp#38370]
![issue](https://user-images.githubusercontent.com/51651413/76694682-dc49a780-669b-11ea-97d0-f6cbfa3f4f13.jpg)

**Describe your problem and how to reproduce it:**
It seems like the test is broken, even though the code is correct and all the test cases are satisfied it says Wrong.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/css-grid/use-media-queries-to-create-responsive-layouts

**Tell us about your browser and operating system:**
* Browser Name: Chrome 
* Browser Version: Version 80.0.3987.132
* Operating System: Windows 10 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@Saikamesh This issue has been fixed on the `master` branch by PR #38351, but we are still waiting on deployment to production.  Should not be long until it is fixed on production.

I am closing as we are just awaiting on deployment.
