### ISSUE TITLE
Flash message when updating email address is incorrect.

### ISSUE THREAD

**Issue by beaucarnes** [freeCodeCamp/freeCodeCamp#38380]
I updated the email address for my freeCodeCamp account. A confirmation email was sent to me. I clicked the link in the email and then saw the following message:
![image](https://user-images.githubusercontent.com/1513130/76901061-e8d32900-6870-11ea-83d5-792f2bfbece1.png)
This message should be changed to be something like: "Success! You have updated your email address. Happy Coding!"

**Comment by sudiptog81** [comment]
The e-mail address change flag is already being used in `api-server/server/boot/authentication.js` to determine whether the new e-mail is incorrect or not. We can use this flag and similar logic and change the success message based on the conditions.

https://github.com/freeCodeCamp/freeCodeCamp/blob/aa62fdbfe98f872785f792108c6d55582da7e12d/api-server/server/boot/authentication.js#L156

https://github.com/freeCodeCamp/freeCodeCamp/blob/aa62fdbfe98f872785f792108c6d55582da7e12d/api-server/server/boot/authentication.js#L192

**Comment by anshul2807** [comment]
Is this still an issue...? I'm new to this community and I'm looking forward for my first contribution.

**Comment by raisedadead** [comment]
Yes - it is. Please be sure to read the [contributing guidelines](https://contribute.freecodecamp.org) first.

**Comment by ShaunSHamilton** [comment]
@anshul2807 GitPod is set up to be a 1-button setup. That is, you do not need to use the `npm run seed` or `develop` commands - GitPod start with those commands already being run. You can see this in the `client:npm` and `server:npm` terminals.

So, what you can do, if you want, is kill those terminals, and restart the development process yourself. However, unless you are making specific changes which require a restart, this should not be necessary.

Hope this clarifies

**Comment by Arkadipta-Chatterjee** [comment]
Is this still an issue?I am new to open source programming.Would like to work on this

**Comment by anshul2807** [comment]
> Is this still an issue?I am new to open source programming.Would like to work on this

I'm already working on this issue.

**Comment by ieahleen** [comment]
@Arkadipta-Chatterjee @anshul2807 
An issue with the _help wanted_ or _first timers only_ label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)
