### ISSUE TITLE
Sign In with GitHub gives 403 TypeError...

### ISSUE THREAD

**Issue by xmelsky** [freeCodeCamp/freeCodeCamp#38381]
**Describe the bug**
When trying to sign in with the link "Continue with GitHub" it shows 
```
TypeError
403 res.redirectWithFlash is not a function
```

and in URL shows this link: `https://api.freecodecamp.org/auth/auth0/callback?code=6X57g2PAyhwjKAz-`

**To Reproduce**
1. Go to 'https://www.freecodecamp.org/learn/'
2. Click on 'Sign in to save your progress'
3. On the next page click "Continue with GitHub"
4. See error as above

**Expected behavior**
Sign in with no errors.

Any browser, any device. Obvious it's a server-side bug

**Comment by jleeent** [comment]
Also having this issue when logging in with any of the sign-in options.

**Comment by rtmcoder** [comment]
same issue

**Comment by phamin2001** [comment]
Same problem here!

**Comment by Ordnas1** [comment]
Had this problem for a while but just logged in with my GitHub account.

**Comment by xmelsky** [comment]
It seems that issue has been already resolved
