### ISSUE TITLE
JSON APIs and Ajax: Render Images from Data Sources challenge accepts incorrect answer

### ISSUE THREAD

**Issue by geoffreyjball** [freeCodeCamp/freeCodeCamp#38394]
**Describe your problem and how to reproduce it:**
The **JSON APIs and Ajax: Render Images from Data Sources** challenge seems to accept an answer that it shouldn't.

Entering the following code passes the challenge:

```
          // Add your code below this line
          html += `<img src='${val.imageLink}' alt='${altText}'>`;
          // Add your code above this line
```

However, `altText` on its own is not defined. It should be `val.altText`.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/data-visualization/json-apis-and-ajax/render-images-from-data-sources

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 80.0
* Operating System: macOS 10.13.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
@geoffreyjball Thank you for reporting this issue.  I have submitted a pull request that adds a new test to validate `val.altText` is used.
