### ISSUE TITLE
Test Gets Pass No Matter What URL I Submit

### ISSUE THREAD

**Issue by ThePrakashKumar** [freeCodeCamp/freeCodeCamp#38397]
No matter what URL I paste in the project section of APIs & Microservices and Information Security and Quality Assurance Certification curriculum all tests get a pass. As long as I put https:// followed by some string all test is passing. As for as I have observed this problem is happening in below project section:

**APIs and Microservices Projects**
* [URL Shortener Microservice](https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/url-shortener-microservice)
* [Exercise Tracker](https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/exercise-tracker)
* [File Metadata Microservice](https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/file-metadata-microservice)

**Information Security and Quality Assurance Projects**
* [Metric-Imperial Converter](https://www.freecodecamp.org/learn/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/metric-imperial-converter)
* [Issue Tracker](https://www.freecodecamp.org/learn/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/issue-tracker)
* [Personal Library](https://www.freecodecamp.org/learn/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/personal-library)
* [Stock Price Checker](https://www.freecodecamp.org/learn/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/stock-price-checker)
* [Anonymous Message Board](https://www.freecodecamp.org/learn/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/anonymous-message-board)

**Desktop Information:**
 - Windows 7
 - Google Chrome
 - Version: 80.0.3987.132 

Regards!

**Comment by raisedadead** [comment]
Hi,

Thanks for your report. We recommend you to please search issues and check on the forum before adding a fresh report on the tracker.

This is an expected behaviour. We rely on the academic honesty policy for submissions.

Happy coding.

**Comment by ThePrakashKumar** [comment]
I have already searched and reported in [forum](https://www.freecodecamp.org/forum/t/something-wrong-with-testing-in-apis-and-microservices-project-section/360919/). Here is another user reporting the same issue:
https://www.freecodecamp.org/forum/t/apisand-microservices-url-shortener-microservice/348800
And this is expected behavior? How the test working fine in the first two project of APIs and Microservices section. The test is not working at all in the above-mentioned challenges it is justing pass on ANY URL. Kindly check the issue, please.

**Comment by raisedadead** [comment]
Thanks for the updates. @RandellDawson @scissorsneedfoodtoo please investigate.

**Comment by RandellDawson** [comment]
@raisedadead @ThePrakashKumar I replied back to [this topic](https://www.freecodecamp.org/forum/t/something-wrong-with-testing-in-apis-and-microservices-project-section/360919) with more questions.

**Comment by raisedadead** [comment]
Hi @RandellDawson lets discuss here instead.

I vaguely remember Valery added the ability to test projects for the first few projects, and if I remember correctly, and we were supposed to write the tests for others.

I am not sure, if there is a PR waiting for this or something.

**Comment by ojeytonwilliams** [comment]
@moT01 this looks familiar.  Weren't you working something related to this?

**Comment by moT01** [comment]
Yea - tests don't exist for most of the backend projects so any URL passes. https://github.com/freeCodeCamp/freeCodeCamp/issues/37185 - there's a few open PR's to add tests for some of them.

**Comment by raisedadead** [comment]
Thanks for the update @moT01 !

**Comment by ThePrakashKumar** [comment]
So I have to wait till the PR's get merged to my code.

**Comment by raisedadead** [comment]
You should not wait to submit the challenges, I would recommend you complete the projects to the best of your abilities sticking to the user stories and requirements and move ahead to get your certifications.

You can always re-submit this later, if you want to test it against the test suite in future.

**Comment by ThePrakashKumar** [comment]
@raisedadead already completed some projects and doing the rest. And one more thing there are some open PR in the boilerplate repo and also did one but no one seems to respond there. Her is the link: https://github.com/freeCodeCamp/boilerplate-socketio/pulls
Thanks!

**Comment by raisedadead** [comment]
Thanks for those updates, would you be interested in contributing to these boiler plate repos? 

Let me know, we can add you to the @freeCodeCamp/moderators team , which would give you access to review and merge pull-requests.
