### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by mawil583** [freeCodeCamp/freeCodeCamp#38390]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
There is a link that doesn't work. 

**To Reproduce**
1. Go to 'https://www.freecodecamp.org/news/this-is-why-we-need-to-bind-event-handlers-in-class-components-in-react-f7ea1a6f93eb/'
2. There is a section that says:

How ‘this’ binding works in JavaScript
As I mentioned, this happens because of the way this binding works in JavaScript. I won’t go into a lot of detail in this post, but HERE is a great resource to understand how the this binding works in JavaScript.

3. "HERE" is a hyperlink that does not work.

**Expected behavior**

**Screenshots**
![Screen Shot 2020-03-18 at 10 32 56 PM](https://user-images.githubusercontent.com/45023612/77034928-76457480-6968-11ea-91c0-70217608808c.png)

![Screen Shot 2020-03-18 at 10 33 43 PM](https://user-images.githubusercontent.com/45023612/77034967-9117e900-6968-11ea-9930-285499be80ad.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sky020** [comment]
Going to the intended link: [You Don't Know JS](https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/objects-classes/ch2.md)
You can see that it is a work in progress. There is a previous version's content in the file. So, I do not know if the link should be changed to an alternate source, or if a _work-in-progress_ link will suffice.

**Comment by raisedadead** [comment]
Thanks for the report, I am forwarding this to our editorial team.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @mawil583, and for finding the intended link @Sky020.

I went in and changed it to fCC's article, [The Complete Guide to this in JavaScript](https://www.freecodecamp.org/news/the-complete-guide-to-this-in-javascript/) for now. Perhaps we can go back and change it to the updated YDKJS article once the second edition is released.
