### ISSUE TITLE
Timestamp Project Instructions need to be adjusted

### ISSUE THREAD

**Issue by andrescaroc** [freeCodeCamp/freeCodeCamp#38393]
**Describe your problem and how to reproduce it:**
Go to: https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice
Click on: "... similar to this: https://curse-arrow.glitch.me/."
It will take you to: https://curse-arrow.glitch.me/
User story #5 says: "...having the structure {"error" : "Invalid Date" }"

**Compare to the following:**
Go to: https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice
Click on: "Start this project on Glitch using **this link** or..."
it will create a new glitch project
Go to: the public link of that new glitch project
User story #5 says: "...having the structure {"unix": null, "utc" : "Invalid Date" }. It is what you get from the date manipulation functions used above."

### *User story #5 are different, the one that passes as the solution is the first one, so I think the user story in the glitch project to clone must be corrected to avoid confusion.*

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice

**Tell us about your browser and operating system:**
* Browser Name:  Chrome
* Browser Version: 80
* Operating System: Mac OS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screen Shot 2020-03-19 at 2 46 27 PM](https://user-images.githubusercontent.com/38670654/77108601-7f7a2400-69f0-11ea-9842-5567cc7e741c.png)

**Comment by hassaanp** [comment]
I have pushed a fix for this to the target repo.

https://github.com/freeCodeCamp/boilerplate-project-timestamp/pull/32
