### ISSUE TITLE
Local Weather App throws TypeError

### ISSUE THREAD

**Issue by ltongues** [FreeCodeCamp/freecodecamp#384]
I'm trying the Local Weather App demo and it doesn't work for me. Console displays a TypeError. Do you know what that might be about?

![screenshot from 2015-04-28 19 52 45](https://cloud.githubusercontent.com/assets/7702679/7375300/4369c506-ede0-11e4-8fa7-ed23a8002459.png)

**Comment by terakilobyte** [comment]
Whatever you are calling the `.deg` property of is undefined.

**Comment by ltongues** [comment]
Yeah. I just started this challenge and I don't want to get into the source cause I'm not supposed to see the original source. But the demo doesn't work for me.

**Comment by QuincyLarson** [comment]
@adventurebear since you created this Zipline, could you take a look at this and try to fix it when you get a moment? Thanks!

**Comment by AdventureBear** [comment]
ltongues, the undefined requires a postal code which should be returned along with the object that's partially shown in you screenshot.  Can you you expand the object and show me another screenshot? 

or maybe we could pair this evening...

**Comment by AdventureBear** [comment]
ahh...st. Petersburg, is that in Russia?  So the postal code will be different but the weather app should still work...let me look into that.

**Comment by AdventureBear** [comment]
In the meantime, you can work with this weather service API from Russia by using a different query method that does not rely on zip code/ postal code.  It looks like right now (as of July 2014) most of their postal code queries are for US only. I will fix this but it shouldn't affect your implementation as you can't use zip anyway, you'd have to make the adjustment I will go ahead and implement. So if/when you sneak a look at the source code you'll see my fix.   I'll attach a screenshot of what it looks like so you can try to move forward.   Thanks for pointing this out.  

![screen shot 2015-04-28 at 2 50 52 pm](https://cloud.githubusercontent.com/assets/7183950/7377674/ff20d850-edb5-11e4-9256-90e9c81f35e8.png)

**Comment by ltongues** [comment]
Thanks for the quick response. I think I'll do it much easier with lat/lon, since that's what ipinfo.io return anyway. I already tested it and it works, should work for any city! Maybe you should do it with coordinates too.

**Comment by AdventureBear** [comment]
Yep there are a lot of ways to do it. The original user story stated to find weather by zip code, but now its apparent where those limits are.  lots of advantages to using country code also for units (metric vs imperial preference) as well as language localization.  Thanks for pointing it out!

**Comment by QuincyLarson** [comment]
It's a lot easier to implement with latlong - @adventurebear - thank you for making this improvement. I agree with @itongues that this is the way to go. I'll update the user story.

**Comment by ltongues** [comment]
Great. Thanks for the picture, by the way, that will definitely help :)

**Comment by ltongues** [comment]
This is what I see right now. Good job! If you feel adventurous you can try to display that in celsius :)
![screenshot from 2015-04-28 22 35 33](https://cloud.githubusercontent.com/assets/7702679/7378555/eaf874aa-edf6-11e4-97d8-2b705e40abcc.png)

**Comment by AdventureBear** [comment]
Sorry about your lousy weather right now.  :)   It should be fixed to show you celsius.   

I'm going to call this issue closed. This was fun...my first bug fix!

**Comment by ltongues** [comment]
Still Farenheit. Console shows this: 
http://api.openweathermap.org/data/2.5/weather?lat=59.8944&lon=30.2642&units=imperial

I believe it should be 'metric' at the end.

**Comment by AdventureBear** [comment]
fixed!

**Comment by ltongues** [comment]
Ok, it displays Celcius, but I think the temperature is incorrect. It shows 5.2, but when I get the json from the console url it says 8.774, and this is the correct temperature as far as I know. Can you look into that? Good job with your first bug fix! I'm going to bed now.
![screenshot from 2015-04-28 23 47 57](https://cloud.githubusercontent.com/assets/7702679/7379945/33c826ee-ee01-11e4-974d-10d926140e5b.png)

![screenshot from 2015-04-28 23 47 43](https://cloud.githubusercontent.com/assets/7702679/7379940/20f73eec-ee01-11e4-9184-7c0f9dd39967.png)

**Comment by AdventureBear** [comment]
Hmm, that's really strange because there is no further temperature
conversion from teh object. I DID have a conversion function in there, and
yesterday  I noticed my codepen console was running source that was no
longer in the actual codepen.

When you wake up in the morning and reload it, can you see if it's still
behaving that way? As far as I can see in my source it pushes the
temperature directly to the DOM from the weather object now.

-----
Suzanne Atkinson, MD
Clinical Instructor of Emergency Medicne
University of Pittsburgh School of Medicine
Emergency Resource Management, Inc.

Head Coach & Founder
Steel City Endurance Coaching

*Schedule a Swim lesson, Podcast or Coaching consult here:*
http://www.booknow.so/SteelCity

**Comment by ltongues** [comment]
Sure, I'll check.

**Comment by ltongues** [comment]
Ok, seems to be working. Good job @AdventureBear!

**Comment by ltongues** [comment]
One other thing: right now the wind speed is shown in knots for me and presumably for you, judging by your previous screenshot. However, it seems like the right unit would be meters/sec for metric and feet/sec for imperial (see https://openweathermap.desk.com/customer/portal/questions/9877867-what-is-the-units-of-wind-speed-in-metric-and-imperial-?t=535697).

**Comment by ltongues** [comment]
Oh, and you probably want to round the temperature and wind speed to the nearest integer :)

**Comment by ltongues** [comment]
Temperature should be displayed with the degree sign: U+2103 ℃ and U+2109 ℉.

**Comment by terakilobyte** [comment]
Has the original issue surrounding this been resolved? I'd like to close this ticket.

**Comment by AdventureBear** [comment]
Yes! Minor details remain main issue resolved

On Friday, May 1, 2015, Nathan <notifications@github.com> wrote:

> Has the original issue surrounding this been resolved? I'd like to close
> this ticket.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeCodeCamp/freecodecamp/issues/384#issuecomment-98242605>
> .
>


-- 
Schedule a Swim lesson, Podcast or Coaching consult here:
http://www.booknow.so/SteelCity
