### ISSUE TITLE
While loops causing error "resetting on fatal plugin error"

### ISSUE THREAD

**Issue by MeganJClark** [FreeCodeCamp/FreeCodeCamp#3840]
Challenge [Bonfire: Chunky Monkey](http://www.freecodecamp.com/challenges/bonfire-chunky-monkey#?solution=function%20chunk(arr%2C%20size)%20%7B%0A%20%20%0A%20%20var%20temp%20%3D%20Array()%3B%20%2F%2F%20temp%20variable%20to%20hold%20slices%0A%20%20var%20multi%20%3D%20Array()%3B%20%2F%2F%20the%20multidimensional%20array%20we%20will%20return%0A%20%20var%20index%20%3D%200%3B%0A%20%20var%20iterations%20%3D%20Math.round(arr.length%20%2F%20size)%3B%0A%20%20var%20i%20%3D%200%3B%0A%20%20while(i%20%3C%204)%7B%0A%20%20%20%20%0A%20%20%7D%0A%0A%20%20return%20temp%3B%0A%20%20%0A%7D%0A%0Achunk(%5B%22a%22%2C%20%22b%22%2C%20%22c%22%2C%20%22d%22%5D%2C%202)%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function chunk(arr, size) {
  
  var temp = Array(); // temp variable to hold slices
  var multi = Array(); // the multidimensional array we will return
  var index = 0;
  var iterations = Math.round(arr.length / size);
  var i = 0;
  while(i < 4){
    
  }

  return temp;
  
}

chunk(["a", "b", "c", "d"], 2)


```
if I remove the while  loop entirely, the page functions fine but if I add any kind of ```while(argument){}``` I get the "resetting on fatal plugin error" showing up in the console, "run tests" no longer functions and test cases do not load.  This may be something in my code, but I've tried different arguments in the while loop and it seems to happen regardless of the arguments.

**Comment by jlslew** [comment]
"resetting on fatal plugin error" is displayed when your code is too slow or has an infinite loop.  "run tests" aren't working is because the system timed out to prevent your browser from crashing.

**Comment by ltegman** [comment]
Your while loop needs to have an argument that at some point will become untrue due to some code within the while loop. For example, in the code you posted above you would stop having a problem with your while loop if you added a line of code that said `i++;` within your while loop. That way at some point `i` will no longer be less than 4 and the loop while end.

Closing as not a problem with the tests, but feel free to reply if you need further clarification.

**Comment by dsabhrawal** [comment]
fix the infinite loop only then it will resolve.
