### ISSUE TITLE
Basic JavaScript divsion operator interacting with comment syntax highlighting

### ISSUE THREAD

**Issue by connorhsm** [freeCodeCamp/freeCodeCamp#38403]
**Describe your problem and how to reproduce it:**
When viewing the following lesson: Basic JavaScript: Divide One Decimal by Another with JavaScript
You can observe the division operator in the beginning code is interfering with the single line comment at the end of the line.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/divide-one-decimal-by-another-with-javascript

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 74.0
* Operating System: macOS 10.15

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Appearance:
![Screen Shot 2020-03-21 at 12 17 08 am](https://user-images.githubusercontent.com/20902771/77169489-a8dca200-6b0d-11ea-87a4-437a4443a17e.png)

Intended appearance:
![Screen Shot 2020-03-21 at 12 17 18 am](https://user-images.githubusercontent.com/20902771/77169521-ba25ae80-6b0d-11ea-9a47-35dde569387f.png)

**Comment by PATHAKABHISHEK** [comment]
I am working on it

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/93721806-32197380-fb47-11ea-9076-a57aeb44f617.png)

This appears to have been fixed, so I will go ahead and close this issue. If you find that the bug persists, feel free to request we reopen this and provide the relevant information. 🙂
