### ISSUE TITLE
Broken tests (APIs and microservices)

### ISSUE THREAD

**Issue by slesarevns** [freeCodeCamp/freeCodeCamp#38413]
**Describe your problem and how to reproduce it:**
Hi, I've noticed that "APIs and microservices" tests broken, to reproduce put any links to the solution field and click on ''I've completed this challenge" we'll have always the same result "100% complete"
![Без названия - 2020-03-21T182507 089] (https://user-images.githubusercontent.com/10522353/77231127-914ef900-6ba1-11ea-8403-8b12346ad336.png)

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/url-shortener-microservice
https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/exercise-tracker
https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/file-metadata-microservice

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version:  80.0.3987.149
* Operating System: MacOS Catalina

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by RandellDawson** [comment]
Please see [this closed issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/38397) regarding why.
