### ISSUE TITLE
MongoDB and Mongoose - Perform Classic Updates by Running Find, Edit, then Save

### ISSUE THREAD

**Issue by anilvrs90** [freeCodeCamp/freeCodeCamp#38418]
**Describe your problem and how to reproduce it:**
The tests seems to be broken, Please find the attached screenshots and code.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/apis-and-microservices/mongodb-and-mongoose/perform-classic-updates-by-running-find-edit-then-save

**Tell us about your browser and operating system:**
Browser Name:  Google Chrome
Browser Version:   80.0.3987.149 (Official Build) (64-bit)
Operating System: Windows 10 (64-bit)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![error-screenshot-freeCodecamp](https://user-images.githubusercontent.com/9390986/77292846-156ec100-6d07-11ea-9bc7-c85e4c9dbe54.png)
![error-screenshot-glitch](https://user-images.githubusercontent.com/9390986/77292851-17d11b00-6d07-11ea-9b35-26e2f308837e.png)

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
