### ISSUE TITLE
Remove video for the challenge in question

### ISSUE THREAD

**Issue by kevthew** [freeCodeCamp/freeCodeCamp#38410]
**Describe your problem and how to reproduce it:**
I followed along with the video entered the code exactly and the first test fails second test passes the code is correct so the test I think is broke

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-principles/make-an-image-responsive

**Tell us about your browser and operating system:**
* Browser Name: microsoft edge
* Browser Version: 
* Operating System: windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by kevthew** [comment]
worked in chrome only test I have had trouble with so far

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

**Comment by kevthew** [comment]
not n issue with code issue with test it worked in chrome and not edge test is broken on Microsoft edge

**Comment by RandellDawson** [comment]
What code did you try on Microsoft Edge?  

What errors (if any) did you see in the browser's console (not the FCC console)?

**Comment by kevthew** [comment]
I followed the code in the video for help

**Comment by RandellDawson** [comment]
Please post what you see in your browser's console.  Thank you.  Also, please post the code you tried.

**Comment by RandellDawson** [comment]
@lasjorg I notice if I add the following console.log to the first test's testString (when testing locally):
```
    testString: console.log(JSON.stringify(getComputedStyle(document.querySelector('.responsive-img')))); assert(getComputedStyle($('.responsive-img')[0]).maxWidth === '100%');
```
I only see the following in Edge
```
{"WebkitAnimation":""}
```
vs the following in Chrome:
```
{
  "0": "animation-delay",
.
.
.

  "maxWidth": "100%",
.
.
.
  "zIndex": "auto",
  "zoom": "1"
}
```

**Comment by lasjorg** [comment]
What version of Edge are you running? @kevthew  and @RandellDawson

It passes for me in the Chromium-based version which is the only version I have, so I'd like to know what version you are running.

@RandellDawson Does it give you the same output if you run the log from the browser console? I get the full object when I run it in the console. Not sure where it is getting `-webkit-animation` from, I only see that on the fa icons (animated icons) and in the bootstrap file for the main site. I don't think it should show up in the output/test iframe context. I don't see in the object when I run the log in the browser console.

Side note, not really sure why the test is using getComputedStyle, as far as I know using `$('.responsive-img').css('max-width') === '100%'` should be exactly the same. It's a bit shorter and maybe less confusing than mixing Jquery and plain JS. Or just switching it to only plain JS for all of it.

**Comment by RandellDawson** [comment]
@lasjorg I tested it using Edge version 44.18362.449.0 on Windows 10 Home.  It gives the same from the browser console. On Chrome it works as expected.

**Comment by lasjorg** [comment]
Well, I can't test it using that version (unless I set up a VM for it).

Not sure where it is getting the pixel value from, that seems very odd. I don't understand how `max-width` set to 100% would ever compute to a pixel value.

Using `$(selector).css(property)` should be the same as using getComputedStyle. Looking at the jQuery source I'm not sure why it wouldn't be the same.

Jquery source for reference
https://github.com/jquery/jquery/blob/master/src/css.js#L267
https://github.com/jquery/jquery/blob/master/src/css/curCSS.js
https://github.com/jquery/jquery/blob/master/src/css/var/getStyles.js

**Comment by Pallof** [comment]
Can I take a look at this issue?

**Comment by ojeytonwilliams** [comment]
@Pallof sure, go for it.

**Comment by Sky020** [comment]
For these challenges, are the helper-functions ready to be used in the tests? Or, can a simple fix be made like:
```
assert(code.match(/max-width:\s*100%;/));
```

**Comment by Sky020** [comment]
For these challenges, are the helper-functions ready to be used in the tests? Or, can a simple fix be made like:
```
assert(code.match(/max-width:\s*100%;/));
```

**Comment by lasjorg** [comment]
That is what it was before https://github.com/freeCodeCamp/freeCodeCamp/pull/37934. So I don't see why not. As for the helper-functions, I don't know anything about that.

I'd still like to know why Edge is giving the result it is, but I guess it doesn't matter much.

**Comment by Sky020** [comment]
Well, @moT01 , you were involved with the current change. Are we better leaving it as is, changing the test to use regex, or change it to what it was before #37934 ?

**Comment by moT01** [comment]
> For these challenges, are the helper-functions ready to be used in the tests?

No, the helper functions aren't ready

> FYI - When I console.log $('.responsive-img').css('max-width') in the browser console, I see 268px not 100% using Edge. For Chrome, I see 100%.

Looks like the `getComputedStyle` method won't work for edge. So yes, probably need to go back to regex here if we want it to work on edge.

Here's a modification of something I have used in the past to isolate the styles of a selector...
`const resImg = code.match(/\.responsive-img\s*{[\s\S]+?[^}]}/g)[0]; assert(/max-width\s*:\s*22%\s*(;|})/g.test(resImg));`

^ I modified without testing, hoping to get a helper function for isolating styles added to the PR for those.

**Comment by lasjorg** [comment]
This is still causing problems every now and then.

Have we abandoned the support of the older Edge versions (prior to the switch to Chromium), or should we fix this by switching back to a regex?
