### ISSUE TITLE
Waypoint: Target HTML Elements with Selectors Using jQuery - animated.css not added to code

### ISSUE THREAD

**Issue by trs4ece** [FreeCodeCamp/FreeCodeCamp#3842]
**From the instructions:**
"Note that we've already included both the jQuery library and the Animate.css library in your code editor."

**Problem:**
Neither the jquery library nor Animate.css are actually included in the code editor. There's also no explanation about the animated class being required to enable animation. This challenge feels like we're simply to copy/paste text and then click done without any explanation or understanding of what we're doing.

**Solution:**
Show where jquery and animate.css are included by adding them into the code editor. In the same way that we were explained that FA is needed to use the FA fonts, explain that animated needs to be included to use animations.

**Comment by abhisekp** [comment]
@QuincyLarson @benmcmahon100  IMO, the code editor should look more like the http://JSBin.com code editor in which we have to write complete valid full HTML code.

**Comment by benmcmahon100** [comment]
Including libraries like that is just copy and paste. We are teaching people how to use the libraries and nothing else. Adding the requirement to completely write out the source for each challenge will make it difficult to create tests and obfuscate the purposes of the lesson. If you're curious to see where they exist just inspect the element of the iframe. Before it's asked the feature to have the pure source of the iframe spat into a window will not be added at this moment in time as @BerkeleyTrue is about to start completely remaking those views anyway

**Comment by abhisekp** [comment]
@benmcmahon100 Moreover, I don't even like the jade source. It spreads out too much. Doesn't look any better in the diff view.

**Comment by BerkeleyTrue** [comment]
> IMO, the code editor should look more like the http://JSBin.com

Thank you for you opinion @abhisekp but we are not JSBin and have no plans to become JSBin. We act purposefully when create, and we choose how we present our challenges in the same fashion. Unless you are willing to invest the time to actually replicate those technologies I'd ask that you stop asking we be like other websites (not the first time I've notice you do this). 

> Moreover, I don't even like the jade source. It spreads out too much due to the syntax. Doesn't look any better in the diff view.

This discussion has nothing to do with Jade. Please stick to the topic of each thread. Github issues are not the place to express your grievances on the syntax of technologies that we have no control over.

> Show where jquery and animate.css are included by adding them into the code editor. 

I don't see how this adds any value to the challenges. The purpose of these challenges is to teach jQuery and its API. If a user doesn't understand how to import a script using a script tag, or how to import a stylesheet using a link tag at this point then the fault is in not preparing the camper on the basics of importing using html and that is what needs to be fixed. A challenge should be added to the html waypoints that explains the basics of importing using script and link tags. @benmcmahon100 Please correct me if we already have something to this effect.

**Comment by abhisekp** [comment]
@BerkeleyTrue I just want FCC to present a better experience with a nice code editor. And my citations of other websites is just a way to show a sample/demo of the experience. 

The current code editor is good but what's so wrong with making it better?

> Unless you are willing to invest the time to actually replicate those technologies I'd ask that you stop asking we be like other websites

Do I got to have the skills to work on the idea before presenting an idea?

**Comment by benmcmahon100** [comment]
@BerkeleyTrue I'm not sure actually but it wouldn't take two seconds to add. @abhisekp we can't invest anyone it perusing minor graphical modifications right now . We are trying to add a lot of new and meaningful features while creating new curricula. If you feel this improvement is necessary why not run the idea but quincy and then make it. Once it's made, submit a pr and that way it'll be merged in

**Comment by trs4ece** [comment]
>>Show where jquery and animate.css are included by adding them into the code editor.

>I don't see how this adds any value to the challenges. The purpose of these challenges is to teach jQuery and its API. If a user doesn't understand how to import a script using a script tag, or how to import a stylesheet using a link tag at this point then the fault is in not preparing the camper on the basics of importing using html and that is what needs to be fixed. A challenge should be added to the html waypoints that explains the basics of importing using script and link tags. @benmcmahon100 Please correct me if we already have something to this effect.

I agree that adding script import tags would distract from the lesson. It is, however, confusing that the instructions state that these scripts have been included *in the editor* but we do not see them in the editor. Perhaps rephrasing to the following would be sufficient: "We have included jQuery and animate.css in the background for the code editor. This enables you to use these powerful libraries as can be seen in this challenge." That can probably be phrased better but the general idea would be to convey that we have access to the libraries even if we don't see them in the code editor.
