### ISSUE TITLE
EBUSY Error When Using Docker to Run Project Locally

### ISSUE THREAD

**Issue by AshNaz87** [freeCodeCamp/freeCodeCamp#38421]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**

When running `npm run docker:run-once`, Husky reports that the git version is not supported and an `EBUSY` error appears while installing:

```
> husky@4.2.3 install /app/node_modules/husky
> node husky install

husky > Setting up git hooks
Husky requires Git >=2.13.0. Got v2.11.0.
husky > Failed to install
```
and

```
lerna ERR! npm ci stderr:
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code EBUSY
npm ERR! syscall rmdir
npm ERR! path /app/curriculum/node_modules
```

**To Reproduce**

1. Download latest version of project from upstream
2. Run `npm run docker:run-once`

**Expected behavior**
Project to run successfully using Docker

**Screenshots**

**Desktop (please complete the following information):**
- Mac OS Catalina
- Version 10.15.3

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by DZuz14** [comment]
@AshNaz87  The latest release of his git version is all the way back in 2017-09-22. You should probably upgrade. Not really sure this needs to be an issue?

**Comment by AshNaz87** [comment]
@DZuz14 to keep track of this. The complaint about the git version is specific to Docker

**Comment by raisedadead** [comment]
Thanks, we have retired the docker setup for the lack of maintenance. We understand the need for isolation by some and recommend using GitPod instead.
