### ISSUE TITLE
Rosetta Code-Strip Control Codes: Assertions Assert Incorrect Strings

### ISSUE THREAD

**Issue by MarkNixon** [freeCodeCamp/freeCodeCamp#38436]
The testing assertion argument strings don't match the input strings. They're missing second slashes. Therefore the test won't accept correct answers:

![image](https://user-images.githubusercontent.com/5247545/77496724-e50f4b80-6e08-11ea-8d1d-eebdc1d681e6.png)

Test Page: [Strip Control Codes](https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/strip-control-codes-and-extended-characters-from-a-string)
Assertions found here: [Strip Control Codes](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-coding-interview-prep/rosetta-code/strip-control-codes-and-extended-characters-from-a-string.english.md)

**Comment by Sky020** [comment]
@MarkNixon , The tests do accept at least one correct answer:
![image](https://user-images.githubusercontent.com/51722130/77564802-31b35f00-6ebb-11ea-8c99-8bb650a0998a.png)
```
function strip(s) {
  return s.split('').filter(function(x) {
    let n = x.charCodeAt(0);
    return 31 < n && 127 > n;
  }).join('');
}
```

Is something not working on your end?

**Comment by moT01** [comment]
To be clear, the text needs to be changed to match the assertions....

```
text: <code>strip("\\ba\\x00b\\n\\rc\\fd\\xc3")</code> should return <code>"abcd"</code>.
    testString: assert.equal(strip("\ba\x00b\n\rc\fd\xc3"), "abcd");
```

should be changed to...
```
text: <code>strip("\ba\x00b\n\rc\fd\xc3")</code> should return <code>"abcd"</code>.
    testString: assert.equal(strip("\ba\x00b\n\rc\fd\xc3"), "abcd");
```

and similar for the rest of the text.
