### ISSUE TITLE
Test and/or solution for the Add Methods After Inheritance challenge seems to be incorrect

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#38433]
After seeing a [question on the forum](https://www.freecodecamp.org/forum/t/dogs-own-properties/362853/2) concerning the [Add Methods After Inheritance](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/object-oriented-programming/add-methods-after-inheritance) challenge, I am wondering if either the following test's `text` and/or `textString` is incorrect.

```
  - text: <code>Dog</code> should have the <code>bark()</code> method as an <code>own</code> property.
    testString: assert(Dog.prototype.hasOwnProperty('bark'));
```

If the `bark` method is really an `own` property, then when I write the following:
```
const beagle = new Dog();
for (let prop in beagle) {
  if (beagle.hasOwnProperty(prop) {
    console.log(prop);
  }
}
``` 
I would expect to see `bark` displayed in the console, but do not.

The current test is checking if `bark` is part of Dog's prototype, which would not be an `own` property would it?  If I am correct, then the solution (below) is incorrect as it adds `bark` to Dog's prototype.  
```
function Animal() {}
Animal.prototype.eat = function() {
  console.log("nom nom nom");
};

function Dog() {}

// Add your code below this line
Dog.prototype = Object.create(Animal.prototype);
Dog.prototype.constructor = Dog;
Dog.prototype.bark = function() {
  console.log("Woof!");
};
// Add your code above this line

let beagle = new Dog();

beagle.eat(); // Should print "nom nom nom"
beagle.bark(); // Should print "Woof!"
```
Shouldn't the solution really be a matter of changing the original function declaration of Dog to be the following or should the test `text` not mention the `own` property?
```
function Animal() {}
Animal.prototype.eat = function() {
  console.log("nom nom nom");
};

function Dog() {
  // Only change code below this line
  this.bark = function() {
    console.log("Woof!")
  }
  // Only change code above this line
}

Dog.prototype = Object.create(Animal.prototype);
Dog.prototype.constructor = Dog;

let beagle = new Dog();

beagle.eat(); // Should print "nom nom nom"
beagle.bark(); // Should print "Woof!"
```

**Comment by Sky020** [comment]
@RandellDawson If the test is `Dog should have the bark() method as an own property`, then, does this not satisfy that:
```
for (let prop in Dog.prototype) {
  if (Dog.prototype.hasOwnProperty(prop)) {
    console.log(prop);
  }
}
```
It is not the `beagle`s property, but the `Dog`.

**Comment by moT01** [comment]
I tried to find a way around changing the text, but I don't think that's going to happen. My suggestion is to change the text to `The <code>Dog</code> prototype should have a <code>bark()</code> method.`

**Comment by ShaunSHamilton** [comment]
@moT01 
>Then add a bark() method to the Dog prototype so that beagle can both eat() and bark().

This could quite easily go into bike-shedding, and I have not seen this come up on the forums since (inheritance/prototyping has, but not anything about this lesson being incorrect/confusing). All I would ask is: what is the _"Dog prototype"_?

**Comment by raisedadead** [comment]
Hi @Nirajn2311 will you be interested in making a PR. I understand because haven't had any objections to your recommendation in a while we should go forth with this.

Thanks.

**Comment by Nirajn2311** [comment]
Sure will create a PR soon.
