### ISSUE TITLE
TypeError: Cannot read property 'presets' of undefined

### ISSUE THREAD

**Issue by beggycev** [freeCodeCamp/freeCodeCamp#38445]
**Describe your problem and how to reproduce it:**

1. Go to Curriculum-> jQuery -> lesson 1
1. Enter correct solution (tested with own code as well as sample solution from forum)
1. Output pane displays: _TypeError: Cannot read property 'presets' of undefined_

To me seems similar/same as #38252 

**Add a Link to the page with the problem:**
[https://www.freecodecamp.org/learn/front-end-libraries/jquery/learn-how-script-tags-and-document-ready-work]

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 80.0.3987.149 (Official Build) (64-bit)
* Operating System: Win 10, 1909

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![2020-03-26_12h31_43](https://user-images.githubusercontent.com/6053730/77642332-c79fc600-6f5d-11ea-8fdf-4b3e79e8ea7f.png)
![2020-03-26_12h39_27](https://user-images.githubusercontent.com/6053730/77642998-e5215f80-6f5e-11ea-89c1-f1c20384fc05.png)

**Comment by ojeytonwilliams** [comment]
Hi @beggycev, thanks for the report.  It looks like your browser has a old version of one of the scripts.  Right now production is using `app-832149905078e58275f3.js`, but I see from the logs that yours is using `app-293d778...`

If you've got a moment, could you confirm it's still not working, then open your dev console, go to the network tab and make sure 'disable cache' is checked.  Then try reloading the challenge that's failing and let me know if it starts to work or now.

**Comment by beggycev** [comment]
Hi @ojeytonwilliams ,

it works now, thank you for getting back. This is something I did not think of.
Sorry for unnecessary issue.

**Comment by ojeytonwilliams** [comment]
@beggycev not at all, you've shed some light on a problem - it should not be necessary to clear your case every time we update the site!

I'm going to reopen this for now, since it's a nice example of that type of problem.

**Comment by raisedadead** [comment]
Closing in favour of https://github.com/freeCodeCamp/freeCodeCamp/issues/35259
