### ISSUE TITLE
Concatenating Strings with Plus Sign solution not working

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#38447]
**Describe your problem and how to reproduce it:**
As described in the linked forum posts, the correct solution is not passing one of the test.
1) Go to lesson
2) Paste in correct solution: `var myStr = "This is the start. " + "This is the end.";`
3) See test fail

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/concatenating-strings-with-plus-operator

* Browser Name: Chrome
* Browser Version: 80.0.3987.149
* Operating System: Windows 10

**Linked Forum Posts:**
https://www.freecodecamp.org/forum/t/bug-javascript-concatenation/363779
https://www.freecodecamp.org/forum/t/concatenating-strings-with-plus-operator-bug/363780

**Comment by Sky020** [comment]
Upon testing: Posting in this solution works, but only because of the added variable:
```
var ourStr = "I come first. " + "I come second.";
var myStr = "This is the start. " + "This is the end.";
```
You can pass the challenge with this:
```
"" + "";
var myStr = "This is the start. " + "This is the end.";
```

**Comment by lasjorg** [comment]
I didn't test this but the seed code was changed (moved to challenge text) so now the solution code doesn't match.

Code changes:
https://github.com/freeCodeCamp/freeCodeCamp/commit/e0e633462807b69e08dfb5cc7171fcc9294b613f#diff-1b554bd4d9d3d478b0cf24500394c8cd
https://github.com/freeCodeCamp/freeCodeCamp/commit/e0e633462807b69e08dfb5cc7171fcc9294b613f#diff-076de93d4dcbbbf202da03cedb3e8482

**Comment by moT01** [comment]
[Here's the file with the problem](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/concatenating-strings-with-plus-operator.english.md).

The second test needs to be changed, and the solution needs to be changed.

**Comment by lasjorg** [comment]
Yep, I saw that. I was trying to figure out Gitpod so I didn't post back. Still not 100% sure of the workflow.

But it's an easy enough fix so I think maybe we should let someone new get a commit in.

**Comment by ojeytonwilliams** [comment]
> But it's an easy enough fix so I think maybe we should let someone new get a commit in.

Let's not leave it too long, it'll be frustrating for people trying to learn.

**Comment by lasjorg** [comment]
This challenge is affected as well I'm guessing
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/concatenating-strings-with-the-plus-equals-operator

`testString: assert(code.match(/\w\s*\+=\s*["']/g).length > 1 && code.match(/\w\s*\=\s*["']/g).length > 1);`

**Comment by RandellDawson** [comment]
Due to the PR merged yesterday, there are several challenges that I am fixing right now that were using the match.length > 1.  The reason the tests did not break, is because the solutions still had the example code that was removed from the challenge seed of the challenges.  If there are any others like this particular challenge, please post here and I will fix them all in a single PR this morning, so we can get it merged ASAP.

**Comment by RandellDawson** [comment]
Update:  There were only 42 files on that PR and only a few of the challenges were affected.  Almost finished with the PR that will fix this mess.  I also changed some of the tests to make them more robust at the same time.

**Comment by lasjorg** [comment]
Does code comments in the seed code need to be matched in the solution code?

Just in case it helps, here are some challenges that looks like the solution code needs to be changed in (some verification would be nice)
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/appending-variables-to-strings
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/find-the-length-of-a-string
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-odd-numbers-with-a-for-loop
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-for-loops
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-bracket-notation-to-find-the-nth-to-last-character-in-a-string

**Comment by RandellDawson** [comment]
@lasjorg I modified all of those and a few more.  The comments should not make any difference.  We had planned on removing the comments from the solutions at one point during this whole process, but we concluded a separate PR after all of set of 4 PR which consolidated comments in the JavaScript challenges would be better.  We can do that once we have validated my latest PR fixes the latest bugs.

**Comment by lasjorg** [comment]
Do we need a temporary pinned forum message just to acknowledge the bugs and avoid a flood of posts?

**Comment by RandellDawson** [comment]
My goal is to get this PR merged in the next 30 minutes and then ask @raisedadead to deploy to production as soon as possible.  @raisedadead Should we create a pinned message or just get this PR merged and deployed to production?

**Comment by RandellDawson** [comment]
@Sky020 @lasjorg Please feel free to review PR #38450.
