### ISSUE TITLE
Donation page text showing wrong donation frequency

### ISSUE THREAD

**Issue by geoff616** [freeCodeCamp/freeCodeCamp#38440]
When navigating to https://www.freecodecamp.org/donate/ and selecting a monthly donation, the text below says "Confirm your donation of $X / year with PayPal" when I would expect it to say "Confirm your donation of $X / month with PayPal"

This text is coming from: 

https://github.com/freeCodeCamp/freeCodeCamp/blob/8866ed74c201be69ace03101fca942ce06f74ee7/client/src/components/Donation/DonateForm.js#L258

There is logic elsewhere in this file that handles the different frequencies, it seems like this logic is needed here as well. 

https://github.com/freeCodeCamp/freeCodeCamp/blob/8866ed74c201be69ace03101fca942ce06f74ee7/client/src/components/Donation/DonateForm.js#L123-L125

**Comment by alti21** [comment]
Can I try this?
