### ISSUE TITLE
Delete properties from a JS Object solution not working

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#38448]
**Describe your problem and how to reproduce it:**
Following the linked forum post, this challenge does not pass with the correct solution. Similar to #38447 
1) Go to lesson
2) Type in solution: `delete myDog.tails;`
3) See test **2** never passes.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/delete-properties-from-a-javascript-object

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 80
* Operating System: Windows 10

**Linked Forum Post**
https://www.freecodecamp.org/forum/t/issue-with-exercise-86/363797

**Comment by Sky020** [comment]
Similar issue with https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-for-loops

This also has poor English: `Use a for loop to work to push the values 1 through 5 onto myArray.`

Should this go in its own issue? I feel there may be even more, and it will clog-up the repo.

**Comment by Sky020** [comment]
Another lesson: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/count-backwards-with-a-for-loop

**Comment by RandellDawson** [comment]
@Sky020 Related to issue #38447

I have a PR on the way.
