### ISSUE TITLE
DevOps: re-structure and re-work on deployment pipeline

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#38451]
- [ ] Currently adding dependencies breaks the API deployments.

  We do not install dependencies on the VM because it will mutate the node_modules while we are serving the API. So, we have to stop the processes and then do install, build start.

  This is fine in production because we have multiple instances and can take them offline one by one.

- [ ] ... more.

**Comment by Leodau** [comment]
Hello, how would you think it should be re-structured?. Could you please provide a description?
