### ISSUE TITLE
Spelling error in the instructions

### ISSUE THREAD

**Issue by kingdopamine** [freeCodeCamp/freeCodeCamp#38459]
**Describe your problem and how to reproduce it:**
You said 'LocalStartegy' instead of 'LocalStrategy'

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/information-security-and-quality-assurance/advanced-node-and-express/authentication-strategies
![Screenshot 2020-03-27 at 11 08 56](https://user-images.githubusercontent.com/22297192/77750340-7d7d1a00-701b-11ea-9ac6-2835395a8635.png)

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by sohaibimalik** [comment]
I'll take it up.
