### ISSUE TITLE
Hotkey clash between search and save code

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#38469]
Currently SearchBox from react-instantsearch-dom listens to the key event `s` and focuses the search box when it receives it.  When `ctrl+s` is pressed (to save user code) this also triggers the search listener and focuses the search box.

Ideally, if possible, the hotkeys should only be handled by react-hotkeys, which listens to `s` and `ctrl+s` separately.  If not, different hotkeys should be used.

**Comment by Sky020** [comment]
@ojeytonwilliams , does this occur in a specific browser? On Chrome, it works exactly how I would expect it to: When the code editor window is in focus, `Ctrl + S` saves to browser, and when the lesson window is in focus, `Ctrl + S` puts the Searchbox in focus.
![HotkeyGIF](https://user-images.githubusercontent.com/51722130/78503000-e2dbb400-775b-11ea-9994-92191d1b1da0.gif)

**Comment by ojeytonwilliams** [comment]
@Sky020, I'm not sure what I was thinking when I created this issue.  This problem would appear if https://github.com/freeCodeCamp/freeCodeCamp/pull/38203 were merged as is, but I need to change that.

Sorry!
