### ISSUE TITLE
Remove redundant challenge (or fix it)

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#38463]
Challenge: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/add-key-value-pairs-to-javascript-objects

The challenge is part of the Basic Data Structures. It seems completely redundant, not to mention incorrectly implemented.

1. It is redundant because we already have [a challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/add-new-properties-to-a-javascript-object) in the basic javascript part of the curriculum that is exactly the same (except it actually shows the syntax).

2. It is incorrectly implemented because it does not show the syntax for setting key/values, it just shows how to get them. Which is not the requirement of the challenge.

I suggest we remove this challenge. Or if nothing else, correct it to show the syntax for setting key/values.

Forum report: https://www.freecodecamp.org/forum/t/dont-need-help-more-reporting/364888

**Comment by ojeytonwilliams** [comment]
I vote for adding examples.  It's true that it's repeating an earlier challenge, but refreshing people's memory seems fine to me.

Also, the next challenge, https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/modify-an-object-nested-within-an-object, could do with an example as it's slightly more complicated.

**Comment by moT01** [comment]
I vote to keep it around as well. Redundancy is kind of the whole goal of the project based curriculum. I would give it a slight rewrite so that the examples show how to set values, and get rid of the current examples.

**Comment by AshNaz87** [comment]
@ojeytonwilliams What do you mean by adding examples? E.g. where it says `Add three more entries`, add more todos there?

**Comment by ojeytonwilliams** [comment]
@AshNaz87 I meant demonstrations of the code we want users to write.  For example, in the description there should be something like

```js
FCC_User['email'] = 'foo@bar.com'
FCC_User.avatar = 'example.com/img.png'
```

to remind them of the syntax for setting members.

I think there are enough todos.

**Comment by zebwilson** [comment]
Maybe we can work together for another project?

**Comment by danielramosbh74** [comment]
> @ojeytonwilliams What do you mean by adding examples? E.g. where it says `Add three more entries`, add more todos there?

I've read #38468 and think @AshNaz87 have solved this topic (#38463).

**Comment by lasjorg** [comment]
@danielramosbh74 The PR that needs to be updated is #38472 it is still missing example code showing how to add and/or update key/values.

**Comment by Pallof** [comment]
Could I work on this? What kind of examples are we looking specifically?

**Comment by lasjorg** [comment]
@Pallof The work is already in progress in the #38472 PR
