### ISSUE TITLE
Example could be added to explain to users how to modify an object within a nested object

### ISSUE THREAD

**Issue by AshNaz87** [freeCodeCamp/freeCodeCamp#38467]
**Describe your problem and how to reproduce it:**
Follow up from issue #38463

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/modify-an-object-nested-within-an-object

**Comment by RandellDawson** [comment]
Closing as a duplicate of #38463
