### ISSUE TITLE
React build error

### ISSUE THREAD

**Issue by marc-turner** [freeCodeCamp/freeCodeCamp#38479]
**Describe the bug**
ERROR in Console when doing "React: Review Using Props with Stateless Functional Components":
Won't render components. Tested in Chrome and Firefox. Occurs on other React leassons as well.

"unpkg.com/react-dom@16.4.0/umd/react-dom.production.min.js:110 Invariant Violation: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=Camper for the full message or use the non-minified dev environment for full errors and additional helpful warnings."

**Comment by ojeytonwilliams** [comment]
Hi @marc-turner, you may need to clear your browser's cache.  If you open the dev console, go to the network tab, check disable cache and reload the problem might go away.

If not, I'd bring this up on the forum.

**Comment by marc-turner** [comment]
Still happening after noted advice. Will hit forums. Thanks

**Comment by ojeytonwilliams** [comment]
From https://www.freecodecamp.org/forum/t/react-build-error-152/366605 it looks like this has been resolved, so I'm closing this.
