### ISSUE TITLE
Tab is 4 spaces in editor, should be 2

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#38470]
This is pretty minor, and I'm not sure if it's in our control.

But if you go to any challenge that has the built in code editor.
Pressing tab adds four spaces to the code.
It would be nice to switch that to two if possible.

I think two spaces is the standard, but perhaps it's just my preference.

**Comment by AshNaz87** [comment]
Agree 👍

**Comment by ojeytonwilliams** [comment]
It's an option we can set: https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodelupdateoptions.html#tabsize
