### ISSUE TITLE
mY Answer even it matches the answerObject.freeze(MATH_CONSTANTS); given it is still not going to the next and showing an error "You should not change original MATH_CONSTANTS." though I did not do any changes to MATH_CONSTANTS.  

### ISSUE THREAD

**Issue by satyan-dot** [freeCodeCamp/freeCodeCamp#38471]
**Describe your problem and how to reproduce it:**
mY Answer even it matches the answerObject.freeze(MATH_CONSTANTS); given it is still not going to the next and showing an error "You should not change original MATH_CONSTANTS." though I did not do any changes to MATH_CONSTANTS.  

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/prevent-object-mutation

**Tell us about your browser and operating system:**
* Browser Name: GOOGLE CHROME
* Browser Version: Version 80.0.3987.149 (Official Build) (64-bit)
* Operating System: windows 7
**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/56076913/77916490-c69cca80-72b6-11ea-8324-5de16fa5cdb4.png)

**Comment by satyan-dot** [comment]
Awaiting an immediate answer please.

**Comment by satyan-dot** [comment]
I am stuck please

**Comment by RandellDawson** [comment]
@satyan-dot Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

**Comment by satyan-dot** [comment]
Thank you for your response

**Comment by satyan-dot** [comment]
Hi! Mr.RandalDawson
I could understand by running the code in the Chrome Browser - it is due to the browser issue and not that there is any wrong in the code i completed.  
THIS IS FOR YOUR INFORMATION  PLEASE;
Reset
> TypeError: Cannot assign to read only property 'PI' of object '#<Object>'
6
Nothing can be added to or removed from the properties set of a frozen object. Any attempt to do so will fail, either silently or by throwing a TypeError exception (most commonly, but not exclusively, when in strict mode).

For data properties of a frozen object, values cannot be changed, the writable and configurable attributes are set to false. Accessor properties (getters and setters) work the same (and still give the illusion that you are changing the value). Note that values that are objects can still be modified, unless they are also frozen. As an object, an array can be frozen; after doing so, its elements cannot be altered and no elements can be added to or removed from the array.

freeze() returns the same object that was passed into the function. It does not create a frozen copy.

**Comment by ojeytonwilliams** [comment]
Hi @satyan-dot the problem is that, in the screenshot, there is a space after `PI`.  The test expects that you don't modify code above `  // Only change code below this line`, and so is quite strict.

In future, please use the forums for these kinds of problems.  If the community sees that's the problem with the site, then opening an issue would be a big help.
