### ISSUE TITLE
challenge Basic HTML and HTML5: Create a Form Element can pass with wrong code

### ISSUE THREAD

**Issue by Ieahleen** [freeCodeCamp/freeCodeCamp#38478]
**Describe your problem and how to reproduce it:**
this challenge instruct to next the existing input element inside a form tag. It is possible to pass this challenge by creating a new input tag inside the form element without nesting the existing one.

The following code with two input elements passes:
```
<h2>CatPhotoApp</h2>
<main>
<p>Click here to view more <a href="#">cat photos</a>.</p>

<a href="#"><img src="https://bit.ly/fcc-relaxing-cat" alt="A cute orange cat lying on its back."></a>

<p>Things cats love:</p>
<ul>
  <li>cat nip</li>
  <li>laser pointers</li>
  <li>lasagna</li>
</ul>
<p>Top 3 things cats hate:</p>
<ol>
  <li>flea treatment</li>
  <li>thunder</li>
  <li>other cats</li>
</ol>
<input type="text" placeholder="cat photo URL">
<form action="/submit-cat-photo">
 <input type="text">   <!-- the issue is here, there is a new element instead of nesting ht eexisting one -->
</form>
</main>
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/create-a-form-element

see this topic in the forum: https://www.freecodecamp.org/forum/t/form-element-problem/366128

**Comment by ojeytonwilliams** [comment]
@Ieahleen thanks for reporting this!

How about an extra test to count the number of `<input>`s?

**Comment by moT01** [comment]
Sounds good to me @ojeytonwilliams. I would make the text: `You should not any additional input elements.`

**Comment by RandellDawson** [comment]
I also suggest changing the instructions to:
> Nest your existing <code>input</code> element inside a <code>form</code> element, and add the action="/submit-cat-photo" attribute to the <code>form</code> element.

**Comment by RandellDawson** [comment]
@ojeytonwilliams We don't really care if the user adds extra input elements outside the form element.  We just want to make sure there is just one input element nested with the desired action attribute nested inside the form element.

**Comment by moT01** [comment]
I don't mind making users nest the existing input. I agree that the concept of the challenge is to add an action to a form. But if that were all we cared about, why check for an input at all? I think this little bit of extra work gives the challenge a little more depth without complicating it.

**Comment by ojeytonwilliams** [comment]
> We just want to make sure there is just one input element nested with the desired action attribute nested inside the form element. It is the latter part we should be testing for.

The first test could also be made into an equality, then. The second test checks that the form (with the nested input) has the right action.
