### ISSUE TITLE
Possible solution to Locked issue #37457

### ISSUE THREAD

**Issue by MarceloDamian** [freeCodeCamp/freeCodeCamp#38487]
***Describe the bug**
Hi!!  I have been documenting the source code trying to understand and possibly improve efficiency. The pathway I looked at is:  "freeCodeCamp/client/src/components/Header/components/Login.js ".  The locked issue #37457 might be happening because a portion of the code is documented as "Non-standard". This bug could possibly be causing issues with some users in signing in, from different browsers. It also is redundant.  

**Screenshots**
This is some of the documentation I have for the code: 

<img width="896" alt="Screen Shot 2020-04-01 at 23 11 00" src="https://user-images.githubusercontent.com/60354250/78212763-ac154d80-747e-11ea-89a4-8776fe0f785d.png">

**Additional context**
A better explanation can be looked at: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/displayName

P.S. Thank you for taking the time to read this issue. 

Closes #37457

**Comment by raisedadead** [comment]
Thanks for your report. The linked issue details the reasons of login issues faced by some users. Its existential in nature.
