### ISSUE TITLE
Forum: Bootom border on .d-header looks wierd on hover

### ISSUE THREAD

**Issue by seshaljain** [freeCodeCamp/freeCodeCamp#38489]
**Describe the bug**
The header on [https://freecodecamp.org/forum](https://freecodecamp.org/forum) has a `border-bottom: 1px solid #3b3b4f;`.
On hovering over the buttons, they get an inverted background-color, but the border on header remains, leading to a bottom border which looks out of place.

Removing the border give it a seamless look.

The dark/dawn theme do not have this problem, but the header looks fine without border-bottom as well.

**To Reproduce**
1. Go to [https://freecodecamp.org/forum](https://freecodecamp.org/forum)
2. Choose the light theme
3. Hover over `menu` or `profile`

**Screenshots**
![Screenshot_2020-04-02 The freeCodeCamp Forum](https://user-images.githubusercontent.com/11702800/78225052-28dc1200-74e7-11ea-81de-417ac41f225b.png)

**Comment by seshaljain** [comment]
Can I create a PR for this?

**Comment by ahmadabdolsaheb** [comment]
@seshaljain, please go ahead.
