### ISSUE TITLE
Two <g> elements with the same id = “legend”

### ISSUE THREAD

**Issue by randomSveta** [freeCodeCamp/freeCodeCamp#38496]
Hi! I’ve noticed that the two "g" elements have the same id. This is not a big deal but I think it would be better to change it somehow. 
(https://www.freecodecamp.org/forum/t/two-g-elements-with-the-same-id-legend/366365)

**Description:**
In the CodePen example for https://www.freecodecamp.org/learn/data-visualization/data-visualization-projects/visualize-data-with-a-scatterplot-graph two <g> elements have the same id = “legend”.

**Steps:**
    1. Go to CodePen:
    https://codepen.io/freeCodeCamp/full/bgpXyK
    2. Open Dev Tools and inspect “legend” element.

**Actual Result:** There are two elements with the same id = “legend”.
Test for the 'User Story #13: I can see a legend containing descriptive text that has id="legend"' is passing ok.
![ same-ids](https://user-images.githubusercontent.com/38963057/78362175-918fc100-75b1-11ea-8baf-30d05c6a1ad3.png)

**Expected Result:** “id” should be unique.

**Comment by scissorsneedfoodtoo** [comment]
@randomSveta, thank you for reporting this and for your detailed description. I'll update this project in the testing repo and on CodePen as soon as possible.

**Comment by randomSveta** [comment]
Hi @scissorsneedfoodtoo,
Thank you very much! Happy to help.

**Comment by scissorsneedfoodtoo** [comment]
Thank you again for reporting this @randomSveta! We updated the code in the [testable projects](https://github.com/freeCodeCamp/testable-projects-fcc) repo and deployed it to [CodePen](https://codepen.io/freeCodeCamp/full/bgpXyK).

Could you take a look at the project on CodePen and confirm that there's only one `legend` id now?

**Comment by randomSveta** [comment]
HI @scissorsneedfoodtoo,

I've checked. Yes, there is only one id="legend".
![one-id](https://user-images.githubusercontent.com/38963057/79049035-0b125980-7c19-11ea-805a-2f620ff7ec74.png)

Thank you for the quick response and problem-solving!

**Comment by scissorsneedfoodtoo** [comment]
@randomSveta, awesome! Thank you again for reporting this issue and confirming that there's only one `legend` id now. Stay safe and happy coding.
