### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by ghanhass** [freeCodeCamp/freeCodeCamp#38492]
Hello.

I noticed a small grammatical error in freeCodeCamp’s team account homepage of our Forum https://www.freecodecamp.org/forum/u/freecodecamp , as seen in this screenshot, the red-framed text being  '**and not**' should either be '**are**' or '**are not**':
![alt text](https://i.imgur.com/M3Abd8w.png "'and not' is not right")

Anyway good day.

**Comment by raisedadead** [comment]
Fixed. Thanks for reporting.
