### ISSUE TITLE
Cannot Claim Certification

### ISSUE THREAD

**Issue by ArnaldoManjate12** [freeCodeCamp/freeCodeCamp#38499]
Good Day Free Code camp Team , My name is Arnaldo MandIate  an aspiring Dev from South Africa .I am sending this to report a troubling matter , After Completing all the activities required to receive my Free code camp certificate i have not received anything. and when i check my profile it says that i have not earned anything. I was really let down after working so hard, please assist with this matter.

NB:  @QuincyLarson  All my tests are passing for the web design Challenges

I have attached screenshot for reference

the challenges:
![certification](https://user-images.githubusercontent.com/52455180/78507543-d3bb2d00-7780-11ea-8ad1-ee3d06f1637f.png)

**Comment by ArnaldoManjate12** [comment]
I sorted it out Thanks

**Comment by ahmadabdolsaheb** [comment]
Thanks.  I am going to close this issue, but please let us know what went wrong or if any thing was not clear.
