### ISSUE TITLE
change challenge "Nest an anchor element in a paragraph" description to avoid users confusion

### ISSUE THREAD

**Issue by Ieahleen** [freeCodeCamp/freeCodeCamp#38507]
After a long extenuating discussion (not yet resolved) in which an user refuses to change the existing anchor element on line 4 because challenge description says 

> Now nest the existing a element within a new p element (just after the existing main element).

can it be changed to say "just after the existing opening main tag"?

https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph

**Comment by RandellDawson** [comment]
What about the following?
>Within the existing `main` element, nest the existing `a` element within a new `p` element. The new paragraph should have text that says "View more cat photos", where "cat photos" is a link, and the rest of the text is plain text.

**Comment by Ieahleen** [comment]
It could also be considered a case of bad wording, as the anchor element is inside the main element, not after it. The current text specifically say "after the main element".
Would it be bike shedding if there is an error?

**Comment by moT01** [comment]
I do think there's a slight inaccuracy in the words there. I vote to just remove the text in the parenthesis since it isn't really providing any helpful information. There's only one `a` element - no need to point out where it is or needs to be. Users just to nest it in a `p`.

**Comment by hassaanp** [comment]
I agree with @moT01 
The text in the parenthesis is not particularly useful since the test passes whether you add it before or after or inside the `main` element.
