### ISSUE TITLE
Change the position of “Basic JavaScript: Return Early Pattern for Functions”

### ISSUE THREAD

**Issue by GrimPixel** [freeCodeCamp/freeCodeCamp#38504]
**Describe your problem and how to reproduce it:**
We can see that as early as “Basic JavaScript: Comparison with the Equality Operator”, there are already two “returns”, but “Basic JavaScript: Return Early Pattern for Functions”, which explains how multiple “returns” work, is taught after this lesson. Thus “Basic JavaScript: Return Early Pattern for Functions” should be moved to before “Basic JavaScript: Comparison with the Equality Operator”.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-equality-operator

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by hassaanp** [comment]
This makes sense to me. I have pushed a PR that addresses this.
Would like to know what other contributors think.

**Comment by RandellDawson** [comment]
We no longer can change the order of the existing curriculum. We can update existing challenges, but not restructure the challenges. The project-based curriculum will eventually replace the current curriculum to deal with situations like this.
