### ISSUE TITLE
Cannot pass the make a person bonfire, the length of objects doesn't return anything

### ISSUE THREAD

**Issue by AromaR** [FreeCodeCamp/FreeCodeCamp#3850]
Challenge [Bonfire: Make a Person](http://freecodecamp.com/challenges/bonfire-make-a-person#?solution=var%20Person%20%3D%20function(firstAndLast)%20%7B%0A%20%20var%20arr%3DfirstAndLast.split(%22%20%22)%3B%0A%20%20%20%20%20%20%20%20%0A%20%20var%20arr%3DfirstAndLast.split(%22%20%22)%3B%0A%20%20this.first%3Darr%5B0%5D%3B%0A%20%20this.last%3Darr%5B1%5D%3B%0A%20%20this.full%3DfirstAndLast%3B%0A%20%20%0A%20%20%20%20return%20firstAndLast%3B%0A%7D%3B%0APerson.prototype%20%3D%20%7B%0A%20%20%20%20getFirstName%3A%20function()%20%7B%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20return%20this.first%3B%0A%20%20%20%20%7D%2C%0A%0A%20%20%20%20setFirstName%3A%20function(name)%20%7B%0A%20%20%20%20%20%20%2F%2Fvar%20arr%3Dname.split(%22%20%22)%3B%0A%20%20%20%20%20%20%20%20this.first%20%3D%20name%3B%0A%20%20%20%20%7D%2C%0A%20%20getFullName%3A%20function()%20%7B%0A%20%20%20%20%0A%20%20%20%20var%20str%3D''%3B%0A%20%20%20%20var%20res%3Dstr.concat(this.first)%3B%0A%20%20%20%20str%3Dres%3B%0A%20%20%20%20var%20res%3Dstr.concat(%22%20%22)%3B%0A%20%20%20%20str%3Dres%3B%0A%20%20%20%20var%20res%3Dstr.concat(this.last)%3B%0A%20%20%20%20str%3Dres%3B%0A%20%20%20%20this.full%3Dstr%3B%0A%20%20%20%20%20%20%20%20return%20this.full%3B%0A%20%20%20%20%7D%2C%0A%0A%20%20%20%20setLastName%3A%20function(name)%20%7B%0A%20%20%20%20%20%20%20%20%2F%2Fvar%20arr%3Dname.split(%22%20%22)%3B%0A%20%20%20%20%20%20%20%20this.last%20%3D%20name%3B%0A%20%20%20%20%7D%2C%0A%20%20getLastName%3A%20function()%20%7B%0A%20%20%20%20%20%20%20%20return%20this.last%3B%0A%20%20%20%20%7D%2C%0A%0A%20%20%20%20setFullName%3A%20function(name)%20%7B%0A%20%20%20%20%20%20var%20arr%3Dname.split(%22%20%22)%3B%0A%20%20this.first%3Darr%5B0%5D%3B%0A%20%20this.last%3Darr%5B1%5D%3B%0A%20%20%20%20%20%20%20%20this.full%20%3D%20name%3B%0A%20%20%20%20%7D%0A%7D%0A%0A%0Avar%20bob%20%3D%20new%20Person('Bob%20Ross')%3B%0AObject.keys(bob).length%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
var Person = function(firstAndLast) {
  var arr=firstAndLast.split(" ");
        
  var arr=firstAndLast.split(" ");
  this.first=arr[0];
  this.last=arr[1];
  this.full=firstAndLast;
  
    return firstAndLast;
};
Person.prototype = {
    getFirstName: function() {
      
        return this.first;
    },

    setFirstName: function(name) {
      //var arr=name.split(" ");
        this.first = name;
    },
  getFullName: function() {
    
    var str='';
    var res=str.concat(this.first);
    str=res;
    var res=str.concat(" ");
    str=res;
    var res=str.concat(this.last);
    str=res;
    this.full=str;
        return this.full;
    },

    setLastName: function(name) {
        //var arr=name.split(" ");
        this.last = name;
    },
  getLastName: function() {
        return this.last;
    },

    setFullName: function(name) {
      var arr=name.split(" ");
  this.first=arr[0];
  this.last=arr[1];
        this.full = name;
    }
}


var bob = new Person('Bob Ross');
Object.keys(bob).length;

```

**Comment by ltegman** [comment]
The reason you aren't passing this test is because you only have three properties on the Object bob (`first`, `last`, `full`) and it's looking for six.The goal for this challenge is that you will have stored the name being held by the object in a way that isn't exposed through object properties. This means you need to use closures and can't add the Person methods via prototype. Closures work by capturing a variable inside a function so that it exists even after the scope that originally created it no longer exists.

I'm not going to solve the whole problem for you, but here's an example of how you'd use a closure in this problem.

```Javascript
function Person(firstAndLast) {
  var fullName = firstAndLast;

  this.getFullName = function() {
    return fullName;
  };
}
```

Closing as not an issue with the tests but feel free to reply if you need further clarification.

Thanks and happy coding!
