### ISSUE TITLE
can someone please help me with this instruction? "My tribute page should have an element with a corresponding id="main", which contains all other elements." What do they mean about . corresponding id="main", should contains all other elements?

### ISSUE THREAD

**Issue by mhw0001** [freeCodeCamp/freeCodeCamp#38501]
can someone please help me with this instruction? "My tribute page should have an element with a corresponding id="main", which contains all other elements." What do they mean about . corresponding id="main", should contains all other elements?

_Originally posted by @mhw0001 in https://github.com/freeCodeCamp/testable-projects-fcc/issues/450#issuecomment-609564959_

**Comment by huyenltnguyen** [comment]
Hi @mhw0001, the instruction says that you need to create an element with an id `main` and wrap it around other elements.

```html
<div id="main">
  <div id="some-element"></div>
  <div id="another-element"></div>
  ...
</div>
```
---
I hope that answers your question.

I'm going to close the issue as GitHub issues are meant for bug reporting only. Please use the [forum](https://www.freecodecamp.org/forum/) if you need help with the curriculum challenges. Happy coding!

**Comment by PaulWM556** [comment]
Hello,
I am having the same issue with the previous question about using id="main" and when using <div id="main"> the question still arises.  So, is there something along with the coding for why I am questioned about id="main"?  Thank you.

**Comment by Aza-di** [comment]
we should write this code on HTML or CSS?

**Comment by texas2010** [comment]
@Aza-di if you need help or ask questions. please use freeCodeCamp forum. so you can have help from great people at the forum. https://forum.freecodecamp.org/

**Comment by Aza-di** [comment]
Thanks for responding.
Firstly I would like to ask about it is right if I am learning alone?
I mean without coding partner.
Secondly I got stuck in web design project
I should learn further Java script?


Thank you in advance,

Azat Bolgambayev

вт, 29 июн. 2021 г., 22:37 Lance ***@***.***>:
