### ISSUE TITLE
Text on donate button needs centering vertically

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#38503]
For some users donate button text on news is not centered vertically.
note: was not able to reproduce this issue locally or on production.

![image](https://user-images.githubusercontent.com/4591597/78546110-92209580-7805-11ea-97ac-ab9a07c699e4.png)

there is a related issue withe the magnifying glass on learn which is not reproducible by all users.
ref: #37778

**Comment by hassaanp** [comment]
unable to reproduce this as well.
Tried Firefox and Chrome

**Comment by ojeytonwilliams** [comment]
The issue is reproducible if you change your browser's font settings.  I should have a fix shortly.

**Comment by AshNaz87** [comment]
Also seemed a little off, when playing with the viewport
