### ISSUE TITLE
Algorithms: Implement Merge Sort - Issue

### ISSUE THREAD

**Issue by BoCode84** [freeCodeCamp/freeCodeCamp#38518]
**Describe your problem and how to reproduce it:**
Tests break with “sort” in the comments. Talked with ArielLeslie about it in the forum. 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-merge-sort

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: NA
* Operating System: WIndows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by bryce-mcmath** [comment]
Bump. Same issue but not just with `sort` in comments it's happening for me if `sort` is part of a variable name as well. In my case (had a variable named `sorted`) when I changed the variable to `s` the error went away. Hopefully the above PR will fix this variant of the issue as well. Let me know if I can help
