### ISSUE TITLE
"refer back" vs. "refer"

### ISSUE THREAD

**Issue by lpham2525** [freeCodeCamp/freeCodeCamp#38519]
In the lesson on Basic Javascript: Record Collection, I think that the term is "refer" instead of "refer back". I read in a Reader's Digest Magazine that the latter is redundant.

**Comment by moT01** [comment]
I don't think there's a problem with 'refer back' here. I read [this article](https://www.grammarphobia.com/blog/2013/06/refer-back.html) - and specifically this sentence...

“In 1995, 65 percent of the Panel disapproved of this construction, but by 2011, 81 percent accepted it in the sentence _To answer your question it is necessary to refer back to the minutes of the previous meeting_.”

And in the case of the challenge, users are being asked to "refer back" to a previous challenge, so back has some purpose here I think.

**Comment by lpham2525** [comment]
Okay.

**Comment by moT01** [comment]
Thanks for reporting. We can leave the issue open for now in case someone else wants to weigh in.

**Comment by ahmadabdolsaheb** [comment]
I think refer back makes sense here.
