### ISSUE TITLE
New project inquiries

### ISSUE THREAD

**Issue by inoxstasy** [freeCodeCamp/freeCodeCamp#38511]
Hello :) 

I am totally new at programming, and wanted some advice. 
I want to create a program using the google maps api. 

Is JavaScript the adequate programming language to use? 

Thanks in advance for your answer :)

**Comment by RocktimSaikia** [comment]
@inoxstasy You should generally ask these types of questions in the [forum](https://www.freecodecamp.org/forum/). There is a whole developer community out there helping new coders like you in every way.
And to answer your question, yes you can easily integrate google maps api with javascript.

**Comment by inoxstasy** [comment]
Oh sorry I did not where to post it ! Thanks a lot :)

**Comment by moT01** [comment]
Try the forum @inoxstasy. This is for issues with the freeCodeCamp platform. Thanks and happy coding 🍡
