### ISSUE TITLE
Spelling Mistake in the Documentation "deveops.md"

### ISSUE THREAD

**Issue by l-Mana-l** [freeCodeCamp/freeCodeCamp#38522]
Hello, I am new to getting involved in open-source projects and simply want to start off slow in getting involved in the community. Under the topic header  "Pushing changes to Staging Application" as stated in the second paragraph after step 5, "The release pipeline is triggered automatically when a fresh **artefact** is available from the connected build pipeline." did you mean **"artifact"**?

**Comment by jordanliu** [comment]
In this context, it's discussing build artifacts. Might just be the case of US English and British English.

**Comment by raisedadead** [comment]
Yes. We should probably change it to US English version, `artifact`. PR is welcome.

**Comment by jordanliu** [comment]
> Hello, I am new to getting involved in open-source projects and simply want to start off slow in getting involved in the community. Under the topic header  "Pushing changes to Staging Application" as stated in the second paragraph after step 5, "The release pipeline is triggered automatically when a fresh **artefact** is available from the connected build pipeline." did you mean **"artifact"**?

You got this?

**Comment by raisedadead** [comment]
Oh - Looks like I had accidentally closed this. Up for grabs.

**Comment by jordanliu** [comment]
PR #38528
