### ISSUE TITLE
Basic CSS: Use Hex Code to Mix Colors

### ISSUE THREAD

**Issue by Czespo** [freeCodeCamp/freeCodeCamp#38521]
- https://www.freecodecamp.org/learn/responsive-web-design/basic-css/use-hex-code-to-mix-colors

If a hex triplet (i.e. ```#F00```) is used in the bodies of the ```.red-text``` and ```.green-text``` selectors, the tester complains:
```
The hex code for the color red should be used instead of the word red.
The hex code for the color green should be used instead of the word green.
```
Don't penalize learners for being smart!

**Comment by moT01** [comment]
I agree. The [tests are here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-css/use-hex-code-to-mix-colors.english.md#tests). The regex for the second and fourth tests should be changed to allow for either version of the hex code.

**Comment by YemiAdebayo** [comment]
If there is an agreement about allowing the triplet hex for red, green and blue, I will like to take it

**Comment by moT01** [comment]
Looks like someone already jumped on it @YemiAdebayo. Want to take a look at that PR and see if it looks good?
