### ISSUE TITLE
waypoint: override styles in subsequent css

### ISSUE THREAD

**Issue by eagle122** [FreeCodeCamp/FreeCodeCamp#3853]
Challenge [Waypoint: Override Styles in Subsequent CSS](http://www.freecodecamp.com/challenges/waypoint-override-styles-in-subsequent-css#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%20%20color%3A%20green%3B%0A%20%20%7D%0A%20%20.pink-text%20%7B%0A%20%20%20%20color%3A%20pink%3B%0A%20%20%7D%0A%20%20.blu-text%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%3Ch1%20class%3D%22blue-text%20pink-text%22%3EHello%20World!%3C%2Fh1%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/7.1.7 Safari/537.85.16</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  body {
    background-color: black;
    font-family: Monospace;
    color: green;
  }
  .pink-text {
    color: pink;
  }
  .blu-text{
    color: blue;
  }
</style>
<h1 class="blue-text pink-text">Hello World!</h1>


ok Hello World is still pink wether i put blue first or pink first.  however if I remove the "e" from blue, (<h1 class="blu-text" )  Hello world turns blue. But then the h1 class blue text is (x) like I didnt complete it. 
```

![Uploading Screen Shot 2015-10-22 at 1.22.38 PM.png…]()
![Uploading Screen Shot 2015-10-22 at 1.23.59 PM.png…]()

**Comment by eagle122** [comment]
never mind  I found the problem

**Comment by AlexMogoryan** [comment]
Ok what was the problem? How did you fix it?

**Comment by eagle122** [comment]
I needed to proof read everything.  .blue-text in the style. i left off the e on blue.

**Comment by AlexMogoryan** [comment]
;)

**Comment by balajichari31** [comment]
![image](https://user-images.githubusercontent.com/19181631/26990524-7cf2ec80-4d74-11e7-83c9-d378661505ec.png)
