### ISSUE TITLE
Capture groups should be explained clearly

### ISSUE THREAD

**Issue by breatheloud** [freeCodeCamp/freeCodeCamp#38539]
**Describe your problem and how to reproduce it:**
I found the challenge _Regular Expressions: Reuse Patterns Using Capture Groups_ does not give an adequate description of what capture groups do, I would suggest firstly: 
- restructuring the description so that it gives an adequate introduction, e.g. likening them to variables in that they are references to a portion of the Regex.
- Showing that we can reference them with `$` and `\` depending on whether it's used outside the regex or within it, respectively.

AND ONLY THEN describing that "Some patterns you search for will occur multiple times in a string. It is wasteful to manually repeat ..."

**Add a Link to the page with the problem:**

[Regular Expressions: Reuse Patterns Using Capture Groups](
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/reuse-patterns-using-capture-groups)

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by moT01** [comment]
I don't see a huge problem with how it is now. Certainly things could always be better. If you or someone else wants to give it a slight rewrite and make a PR, I wouldn't object - there are a number of forum posts on this challenge.

**Comment by erictleung** [comment]
I agree with some criticisms that were raised. Thanks for sharing.

Here is my suggested changes.

> Say you want to match words that occur twice, like below.
>
> ```
> let repeatStr = "regex regex";
> ```
>
> You could write a regex as `/regex regex/` and this would succeed. But what if you don't know what specific word repeats? This is where <dfn>capture groups</dfn> can be used to find patterns and save those strings in temporary "variables" to be used later.
> 
> Parentheses, `(` and `)`, are used to find repeat substrings. You put the regex of the pattern that will repeat in between the parentheses. In this case, we want any word with alphanumeric letters so we can start building our regex with `/(\w+)/`.
> 
> The contents of what is between the parentheses (here is it is `\w+`) is saved to a temporary "variable". To specify where that repeat string will appear, you use a backslash (`\`) and then a number. This number starts at 1 and increases with each additional capture group you use. An example would be `\1` to match the first group and `\2` to match the second set of parentheses if you had one.
> 
> The example below matches any word that occurs twice separated by a space:
> 
> ```
> let repeatRegex = /(\w+)\s\1/;
> repeatRegex.test(repeatStr); // Returns true
> repeatStr.match(repeatRegex); // Returns ["regex regex", "regex"]
> ```
>
> Using the `.match()` method on a string will return an array with the string it matches, along with its capture group.
