### ISSUE TITLE
Broken links in README.md in docs

### ISSUE THREAD

**Issue by owais4321** [freeCodeCamp/freeCodeCamp#38532]
There are two links README.md in docs. Following are the two links 
1.  how to work on coding challenges.
2. set up freeCodeCamp locally
I am also adding screenshot to show more clearly that which links are broken.
![image](https://user-images.githubusercontent.com/39921596/79116286-e44d4380-7d3c-11ea-9295-51842c978ad0.png)

so when we click on these links in README in docs it shows page not found

**Comment by SemperDisco** [comment]
Nice catch! I will correct this.

**Comment by owais4321** [comment]
@SemperDisco i have linked pr for this kindly merge it thanks

**Comment by raisedadead** [comment]
We will have to figure out a better way to handle links. 

We are currently using `docsify` to host our documentation at http://contribute.freecodecamp.org

This means we have to handle links in a way that they work on that page. I think a quick way to work around this would be to rename `/docs/README.md` to `index.md` which we render on the contribute page.

Then we create a `README.md` in `/docs` which just has a notice similar to the CONTRIBUTING.md

Thoughts?
