### ISSUE TITLE
Recursion typos

### ISSUE THREAD

**Issue by lpham2525** [freeCodeCamp/freeCodeCamp#38531]
Recursion can be tough to understand — especially for new programmers. In it's _//probably should be "its"//_ simplest form, a recursive function is one that calls itself. Let me try to explain with an example.

Imagine you go to open your bedroom door and it’s locked. Your three-year-old son pops in from around the corner and let's _//should read as "lets"//_ you know he hid the only key in a box. (“Just like him,” you think.) You're late for work and your _//author might have meant "you" instead of "your"//_ really need to get in the room to get your shirt.

You open the box only to find…more boxes. Boxes inside of boxes. And you don’t know which one has the key !? _//no space needed between "key" and "!?" punctuation//_.

The iterative approach with loops can sometimes be faster. But many _// the author might have meant to write "mainly" //_ the simplicity of recursion is sometimes preferred.

**Comment by hassaanp** [comment]
Hi @lpham2525 - can you point to the article where you found these errors since this does not look like a part of the curriculum.

**Comment by scissorsneedfoodtoo** [comment]
Hi @lpham2525, thank you for reporting this. I believe you're referring to this article from 2017: https://www.freecodecamp.org/news/how-recursion-works-explained-with-flowcharts-and-a-video-de61f40cb7f9/.

I went through and edited the article based on the errors you found. Could you give it another read and confirm that everything is fixed? I'll close this issue for now, but please feel free to reopen it and add a comment if you notice anything else.

**Comment by lpham2525** [comment]
Thank you  for the edits! Everything looks good.

**Comment by scissorsneedfoodtoo** [comment]
@lpham2525, great! Thank you for catching these errors and confirming that everything looks good now.
