### ISSUE TITLE
Add code radio to /learn

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#38538]
Add [code radio](https://coderadio.freecodecamp.org/) to /learn.

**Comment by moT01** [comment]
I was digging into this a little. My plan was to make a package out of the [coderadio-client repo](https://github.com/freeCodeCamp/coderadio-client) that we could include in the site where it is now, and on the main repo. I have a [good start to it here](https://github.com/moT01/coderadio).

Where it is now would just render all the elements like they are now, and I was going to make a second "UI" for /learn. And decide which UI to render based on a prop.

For example, `<Coderadio />` would just render the full version for the main site and `<Coderadio mini={true} />` would be a real simple UI with just a few buttons that we could put on learn.

Curious what anyone thinks of that plan.

**Comment by AshNaz87** [comment]
Has implementing this feature into the website ever been discussed? I mean just the option of listening to coderadio, i.e. having a play/pause button

**Comment by ahmadabdolsaheb** [comment]
the initial implementation would be a navigation item that would switch between [radio] and [silience]. most of the logic is already handeled in the coderadio repo.

**Comment by ahmadabdolsaheb** [comment]
#38596 is just the working initial pr so we could gather technical requirements.

@raisedadead, what direction would you prefer?

should coderadio become a npm module that we could use across platforms?
let us know what you have in mind for the implementation.

**Comment by ahmadabdolsaheb** [comment]
https://github.com/AzuraCast/AzuraCast/issues/2793

**Comment by moT01** [comment]
We decided to just include a link to coderadio from learn. So I think it's safe to close this. If I'm wrong, and the intent is to still add this at some point - feel free to leave a message, and we can reopen it. Thanks and happy jammin 🎧
