### ISSUE TITLE
Change all green logos and icons to indigo versions.

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#38540]
I believe we want to change all the green icons and logos to their indigo counterparts. If so, we can make a list here as we find them.

**Comment by lasjorg** [comment]
The sign-in/log-in page has a green icon.

**Comment by AshNaz87** [comment]
https://design-style-guide.freecodecamp.org/ has the green favicon

**Comment by ahmadabdolsaheb** [comment]
coderadio has a green favicon

**Comment by Twaha-Rahman** [comment]
@moT01 @ahmadabdolsaheb I'd like to update the logo's if you guys say so😉!

**Comment by moT01** [comment]
I believe it's okay to change these, so you can probably make a PR if you want @Twaha-Rahman.

**Comment by Twaha-Rahman** [comment]
@moT01 @ahmadabdolsaheb  I'm using the `GitPod` to make changes and preview them. Is there any way, I can preview pages like `https://design-style-guide.freecodecamp.org/` and `https://coderadio.freecodecamp.org/`?

**Comment by moT01** [comment]
It looks like those are both separate repositories. [code radio](https://github.com/freeCodeCamp/coderadio-client) and [design style guide](https://github.com/freeCodeCamp/design-style-guide). I haven't used gitpod so I'm not sure if you can use that over on those. But that's where they are.

**Comment by Twaha-Rahman** [comment]
@moT01 I did a PR on the  `design style guide` repo. All of the favicons were hosted from `https://s3.amazonaws.com/freecodecamp/favicons/`, so I created a folder and added the new logos there. (I also update the `index.html` accordingly).

Here's a screenshot of the new logo in action ->

![Capture](https://user-images.githubusercontent.com/39026437/81330860-89500780-90c2-11ea-9a94-bcee7c8f0e75.png)

**Comment by Twaha-Rahman** [comment]
Lemme know if I need to change or update anything ;)

**Comment by ahmadabdolsaheb** [comment]
@Twaha-Rahman, I think I need to change those manually on the amazon bucket and bust the cache. thanks for looking into it tho.

**Comment by Twaha-Rahman** [comment]
> @Twaha-Rahman, I think I need to change those manually on the amazon bucket and bust the cache. thanks for looking into it tho.

After you update the resources, if the link to the resource's change, please let me know. I'll update them...

**Comment by nhcarrigan** [comment]
Hi folks!
The cdn still uses some [green logos](https://cdn.freecodecamp.org/platform/universal/fcc-og-1200-social-green.png). 

This particular one appears on the forum:
![image](https://user-images.githubusercontent.com/63889819/83938403-b6a6d880-a788-11ea-8696-5e6683e69a43.png)

**Comment by ahmadabdolsaheb** [comment]
The current social card meta uses green background
![image](https://user-images.githubusercontent.com/4591597/86538649-d3593c00-beff-11ea-9d77-8310bfb42fbc.png)

**Comment by moT01** [comment]
All of the backend example projects and boilerplates use the green logos. If you go to the [timestamp microservice project page](https://www.freecodecamp.dev/learn/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice) and click the example link at the top. The green icons appears in the browser tab...
![Screen Shot 2020-08-17 at 6 59 12 PM](https://user-images.githubusercontent.com/20648924/90455474-c5c8d180-e0bb-11ea-99ec-af615d29723b.png)

The same is true with all the boilerplates for the lessons and projects in the backend area (pretty sure).

**Comment by moT01** [comment]
auth.freecodecamp.org has the green icons...
![Screen Shot 2020-08-20 at 9 34 54 AM](https://user-images.githubusercontent.com/20648924/90785837-6e4b8100-e2c8-11ea-9254-d4dc35709c86.png)

**Comment by nhcarrigan** [comment]
Heya @ahmadabdolsaheb - it looks like the Design Style Guide is still using the green logos. I had prepped a PR to use the assets from the CDN before I saw your comment about replacing the S3 images on Amazon instead. Is that still the planned route?

**Comment by ahmadabdolsaheb** [comment]
Thanks for double checking. We are pulling our favicons from here at the moment. https://github.com/freeCodeCamp/cdn/tree/master/build/universal/favicons.

**Comment by Moseschand003** [comment]
Still there is a green logo in auth.freecodecamp.org.

**Comment by ojeytonwilliams** [comment]
Hi @Moseschand003, thanks for the offer of help.  The auth pages are stored here: https://github.com/freeCodeCamp/auth0-templates

In that repo the `org-tenant` and `dev-tenant` branches contain the code for auth.freecodecamp.org and auth.freecodecamp.dev, so I would start by looking here: https://github.com/freeCodeCamp/auth0-templates/tree/org-tenant

**Comment by ieahleen** [comment]
it's probably related to something already mentioned
but linking to contribute.freecodecamp.org, the embed has the green icon:
![image](https://user-images.githubusercontent.com/26656284/106453553-ca2a5080-6489-11eb-8658-511d073c0c0f.png)

**Comment by nhcarrigan** [comment]
Thanks @ieahleen - I'll take a look at this today :)

**Comment by gikf** [comment]
Demo projects with green favicon:
https://request-header-parser-microservice.freecodecamp.rocks
https://url-shortener-microservice.freecodecamp.rocks
https://exercise-tracker.freecodecamp.rocks
https://file-metadata-microservice.freecodecamp.rocks

**Comment by moT01** [comment]
Only thing left to fix here is the demo projects it looks like. If we fix those two, we can get this closed and create new issues for individual icons as we find more.

**Comment by nhcarrigan** [comment]
I'll tackle fixing those today.
