### ISSUE TITLE
Monaco Editor: Add delay to hover or disable

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#38541]
In some cases, the hover is blocking the code and it seems a bit intrusive with the default delay. See gif.

![editor-hover](https://user-images.githubusercontent.com/28780271/79150865-c4b02c80-7dc9-11ea-9ad9-ec20ac128dcb.gif)

Do we even want the hover?

I think we should at least add a delay of like 2000 or more. Not sure how the positioning of the tooltip is done?

[Editor.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/templates/Challenges/classic/Editor.js) options (one or the other):
```
hover: {
  enabled: false,
  delay: 2000
}
```

https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorhoveroptions.html

**Comment by raisedadead** [comment]
I think I have made comments about this before, but IMHO we should prevent all autocomplete, right click context and any other in context things like in the OP.

None of this is useful especially for new learners. Its distracting IMO.

We want to disable all the additional features like above using the config.

**Comment by lasjorg** [comment]
I'm all for disabling the hover.

About disabling the context menu. Personally, I'd be fine with it. I'm just not sure if it's a good UX choice.

Having copy/paste functionality from a context menu is pretty ubiquitous in text editors. I have already seen a few threads where people have asked about the missing paste functionality in the context menu we have now.

Although the fact that the copy/paste functionality is already incomplete and we do not see more user feedback from it might point to it not being very important. So maybe I'm just overthinking it.

**Comment by raisedadead** [comment]
I am fine with having copy/paste or anything which would be considered a utility.

**Comment by Manish-Giri** [comment]
@raisedadead I had a feeling we were better off disabling it entirely back then - https://github.com/freeCodeCamp/freeCodeCamp/pull/37813/commits/43736455119b0a9bf4168ac90b4992af7ad777df

😄
