### ISSUE TITLE
Timestamp Mictoservice test crash

### ISSUE THREAD

**Issue by robtejeda** [freeCodeCamp/freeCodeCamp#38557]
**Describe your problem and how to reproduce it:**
The assignment says
If the date string is invalid the api returns a JSON having the structure
**{"unix": null, "utc" : "Invalid Date" }**. It is what you get from the date manipulation functions used above.

And the test evaluates for this object **{"error": "Invalid Date" }**
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/timestamp-microservice.english.md

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice

**Tell us about your browser and operating system:**
* Browser Name: Brave
* Browser Version: 1.7.92
* Operating System: MacOs 10.12.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![screenshot-www freecodecamp org-2020 04 15-23_24_21](https://user-images.githubusercontent.com/4252320/79421799-696c6e80-7f70-11ea-8016-2d594415838d.png)

**Comment by Sky020** [comment]
It seems the tests were written for the example project: https://curse-arrow.glitch.me/
```
If the date string is invalid the api returns a JSON having the structure
{"error" : "Invalid Date" }.
```
