### ISSUE TITLE
ES6: Use getters and setters to Control Access to an Object , issue with resolved values

### ISSUE THREAD

**Issue by zoitberg** [freeCodeCamp/freeCodeCamp#38558]
In this task obtained values aren't checked to clear the task, it is possible to pass the test without any errors, despite the fact that returned values are incorrect 

```js
class Thermostat {
  constructor(fahrenheit) {
    this.fahrenheit = fahrenheit;
  }
  
  get temperature() {
    return (5 / 9) * (this.fahrenheit - 32);
  }
  
  set temperature(celsius) {
    this.fahrenheit = (celsius * 9.0) / 5 + 32;
  }
}

const thermos = new Thermostat(76); // Setting in Fahrenheit scale
let temp = thermos.temperature; // 24.44 in Celsius
thermos.temperature = 26;
temp = thermos.temperature; // 26 in Celsius
<!-- solution pass the test though assignment returns improper value --> 

  //setter 
  set temperature(tempInC) {
    this._temp = tempInC;
  }
}
const thermos = new Thermostat(76); // Setting in Fahrenheit scale
let temp = thermos.temperature; // 24.44 in Celsius
thermos.temperature = 26;
temp = thermos.temperature; //  -3.3333333333333335 in Celsius
```

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Sky020** [comment]
Could you explain further what you are referring to? You have pasted unformatted code that contains incorrect syntax, and it is unclear what tests you are expecting to fail that do not.

**Comment by nhcarrigan** [comment]
```js
class Thermostat {
  constructor(fahrenheit) {
    this.fahrenheit = fahrenheit;
  }

  get temperature() {
    return (this.fahrenheit - 32);
  }

  set temperature(celsius) {
    this.fahrenheit = 18;
  }
}
```

So I poked around with this challenge, and the above code passes the tests. 

The `getter` assigns an incorrect value, but is tested against a `new Thermostat(32)` call (which should return a Celcius temp of 0). 

The `setter` assigns a hard-coded value I randomly chose, and appears to be tested only against this call:
`t = new Thermostat(32); t.temperature = 26;` 
As long as the resulting temperature is not 0, the test will pass. 

Ultimately, though, I think the purpose of the challenge is more the functionality and syntax of the get/set keywords, so is it worth refactoring the tests to confirm the math is correct?

**Comment by Ieahleen** [comment]
it may be worth it, it may create the wrong assumption that the conversion is somewahat magically done
