### ISSUE TITLE
Help video is outdated on "Basic JavaScript: Testing Objects for Properties"

### ISSUE THREAD

**Issue by colinthornton** [freeCodeCamp/freeCodeCamp#38555]
**Describe your problem and how to reproduce it:**
1. Click the "Get Help" button
2. Select "Watch a video"

The code used in the video is outdated. This has caused several campers to post for help on the forum because the answer they copied from the video does not pass the current tests. Here are three just from the past day:

- https://www.freecodecamp.org/forum/t/testing-object-for-properties-issue/373914
- https://www.freecodecamp.org/forum/t/basic-js-testing-objects-for-properties/373801
- https://www.freecodecamp.org/forum/t/wrong-solution-on-the-video/373568

The current starter code is as follows:
```javascript
function checkObj(obj, checkProp) {
  // Only change code below this line
  return "Change Me!";
  // Only change code above this line
}
```

The starter code in the video is as follows:
```javascript
// Setup
var myObj = {
  gift: "pony",
  pet: "kitten",
  bed: "sleigh"
};

function checkObj(checkProp) {
  // Your Code Here

  return "Change Me!";
}

// Teset your code by modifying these values
console.log(checkObj("gift"));
```

I suggest the video be removed in order to cut down on these forum posts.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/testing-objects-for-properties

**Comment by colinthornton** [comment]
This is another topic of discussion, but based on those forum posts it seems that many people have directly copied the code from the video, possibly without even reading the instructions or looking at the starter code before overwriting it all. It makes me wonder if the help videos are actually that useful as an educational tool.

**Comment by colinthornton** [comment]
Just now: https://www.freecodecamp.org/forum/t/testing-objects-for-properties-exercise/373973

**Comment by Sky020** [comment]
Whilst, at one stage, the code in the videos did correspond to the correct solution, and users could just copy to pass, the videos are still quite helpful. In my opinion, with the code being slightly _off_, but still relevant, the videos are even more helpful, as it prevents users from _just_ copying the answer, and they have to think for themselves.

In my opinion, the videos should remain as is, unless something in them becomes deprecated, as the person in the video still goes through an explanation of _what they are doing and why_, which is invaluable as a user who wants to learn.

**Comment by colinthornton** [comment]
I get your point and agree with you that a slightly off video is more beneficial to those who *want to learn*, it's just that there are 30+ forum posts with people who have copied directly from the video in the past 3 weeks (since the problem was changed).

If the video were removed, then those posts would never show up in the first place. Likewise, for learners who aren't able to solve the new problem on their own, they'll still be able to ask for help on the forum just like always. Only, instead of asking why the video code they copied doesn't pass "even though it should", they'll instead ask about about *how* to solve the problem as it's written. Then the posters on the forum would be able to answer
> This is how you do *xxx* in JavaScript

instead of

> Press reset. Don't copy the code in the video.

In my opinion, the former is a much more valuable learning experience for all involved.

**Comment by Sky020** [comment]
Yes, fair enough. I guess we should be asking the questions:
1) Will the videos ever be updated? (I assume not, as the style of curriculum is changing)
2) If not, could a note explaining that the video code is not enough to pass the tests be added to the introductory page? (just some way to make it clear to avoid the clogging of the forum)

**Comment by ojeytonwilliams** [comment]
@beaucarnes are you still updating the videos for the old curriculum?

**Comment by raisedadead** [comment]
I have forwarded this to Beau for a response. Thanks for your patience. Meanwhile recommend linking to this thread from the forum and closing the topics while we arrive at a conclusion.

**Comment by beaucarnes** [comment]
I'm working on this. I'll update the video.
