### ISSUE TITLE
Add certificates to learn map?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#38566]
It might be nice to have the certificates display on the map like another challenge with a little check mark.

![Screen Shot 2020-04-17 at 3 45 39 PM](https://user-images.githubusercontent.com/20648924/79612628-a6e11100-80c2-11ea-830d-c646c6cb637c.png)

**Comment by ojeytonwilliams** [comment]
Perhaps it could have a little trophy icon, rather than just a tick.

**Comment by moT01** [comment]
I'm not sure of the exact implementation we want here, but there seems to be support for this feature so I added the help wanted label. I think it works with the `1/1` or a little trophy icon - or perhaps both. I would use the icon that appears on the timeline if we go that route...
![Screen Shot 2020-09-15 at 10 43 59 AM](https://user-images.githubusercontent.com/20648924/93233234-75877280-f740-11ea-8cc6-605f62e86286.png)

**Comment by ojeytonwilliams** [comment]
> I think I might like to see the icon to the right of the cert name and the 1/1 with the checkmark.

That sounds good to me.  I think that would look nice.

**Comment by Samibanley** [comment]
I would like to take this on if this is still available.

**Comment by ojeytonwilliams** [comment]
Hi @Samibanley. It's still available - your PR would be very welcome.

**Comment by Samibanley** [comment]
Oh, do you all not assign issues?

**Comment by nhcarrigan** [comment]
Issues labelled with `help wanted` are open to contributions. Rather than assigning them, we accept PRs on a `FIFO` basis - the first PR that provides a *comprehensive* resolution for the issue is typically accepted. 

If you have not done so already, I recommend reviewing our [contributing guidelines](https://contribute.freecodecamp.org) 🙂

**Comment by moT01** [comment]
This was added with a recent PR. There's [some discussion happening here](https://github.com/freeCodeCamp/freeCodeCamp/issues/38569) about if we will be keeping them or changing them. So I think it's safe to close this. Thanks and happy coding 🎉
