### ISSUE TITLE
freeCodeCamp Challenge Guide: Truncate a String - Incorrect Link

### ISSUE THREAD

**Issue by benjaminthedev** [freeCodeCamp/freeCodeCamp#38563]
Hi folks, 

Reading the guide here:

https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-truncate-a-string/16089

and it suggests you go to Relevant Links:

String.prototype.slice()

but the link takes you to :

https://github.com/freeCodeCamp/freeCodeCamp

but it should go here:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice

Cheers, 

Ben.

**Comment by raisedadead** [comment]
Fixed. Thanks for reporting Ben.
