### ISSUE TITLE
Claiming certification after certificate completion 

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#38569]
Some users seem to be confused after completing projects for the first certification on how they could receive their certification.

A redirect or a flash message notifying users after finishing the required projects to complete a certificate could be helpful.

**Comment by emaamodt** [comment]
I think that's a great idea. When I earned my first certification for the updated curriculum, it wasn't clear how I was supposed to claim it.

**Comment by raisedadead** [comment]
Why redirect and not use the modal. The primary reason we had this weird way of claiming the cert from the settings page was because:

1. Learn was deployed at `learn.fcc.domain`
2. The API could work on `www.fcc.domain`
3. The user profile was at `www.fcc.domain/<username>`

All these legacy limitations are gone.

There is no need for us to redirect them to the settings. All the functionality is right there in the challenge page.

**Comment by ahmadabdolsaheb** [comment]
We are planning to  show status of each certification on each certification page. It might be more useful to have a claim/show certification button similar to the one we have on the settings page instead, so users don't have to go to the settings page to claim/show their certifications.

<img width="823" alt="Screen Shot 2021-01-29 at 11 51 31 AM" src="https://user-images.githubusercontent.com/4591597/106253313-5dfce200-6228-11eb-804f-bd101bf4effe.png">

@moT01 @raisedadead any thoughts?

**Comment by raisedadead** [comment]
Yes - this seems logical to me. We should still keep a button in the settings at the same time for users who are used to finding it there. 

We can revamp the settings page a bit in the upcoming days to make it cleaner.

**Comment by moT01** [comment]
I'm a little biased - but, I kinda like the first image - an empty circle that fills in when you finally get the cert. Feels like it gives it a little gamification. I would maybe try and put the cert in with the white background though. FYI - That text will link to the cert if it's claimed. What about adding the button from the right image at the bottom of the left image if the cert is claimable? One other thing to maybe consider, is that there's at least one obstacle before you can claim a cert - they need to accept the honesty policy. I think they need to enter their name as well. So if they try to claim the cert from here, they may just get a flash message about having to do those - in which case, they will need to go to the settings page.

I do agree that it would be nice to have some easier ways to claim certs.

**Comment by ahmadabdolsaheb** [comment]
- I agree that some of our error messages could provide a link where the user could resolve the error. For instance, errors about the honesty policy might be confusing as some users might not know honesty policy is located in the settings page. (even if they are claiming the cert from the settings page)

- One of the other motives to remove that cert completion element is to avoid information overload at the end of each superblock page where 5-4 elements are completing for the user's attention.
<img width="963" alt="Screen Shot 2021-02-01 at 11 04 12 AM" src="https://user-images.githubusercontent.com/4591597/106431404-4159e780-647e-11eb-8f1f-bc39525cbef5.png">


I think we should do one or few of the followings:

1) eliminate the less important elements ( do we need the sign in button there?)
2) group/ separate elements if possible ( should we use spacing and break lines to group items in the UI?)
3) give emphasis selectively (can we lower the width, size, contract, and remove some icons and still achieve the same results?)

**Comment by moT01** [comment]
1. I added the sign in button, seemed like a good spot for it - definitely not necessary - although, it does add some color - which I think is nice.
2. Seems like the items are grouped pretty good - each block has a white background, with a space between them - there could possibly be something better though

**Comment by raisedadead** [comment]
Logically to me: 

- The "Sign in" button and a "Claim your X cert." button should be mutually replacing each other depending on the user state. 
- The issue of user not having a name and not having accepted the honesty policy could be handled with a modal with one/two messages explaining the needs, with links to settings page (open in a new page, maybe be even auto scroll to the item).

Something like:

```
------------------------------------------------

  You are almost there! All you need is to:
  - [ ] Add a name to your profile {link here}.
  - [ ] Read and accept our academic honesty 
        policy {link here}.
------------------------------------------------
```

**Comment by Sembauke** [comment]
> * I agree that some of our error messages could provide a link where the user could resolve the error. For instance, errors about the honesty policy might be confusing as some users might not know honesty policy is located in the settings page. (even if they are claiming the cert from the settings page)

@ahmadabdolsaheb 

- Why don't we redirect the user to the honesty policy when the first course is completed? After that make the certification claimable on the curriculum page.
- Why not redirect the user to the login page if the user is not logged in and just completed one of the courses?

This should already remove most of the unneeded error messages and elements that are displayed in the superblock.

Thoughts?

**Comment by raisedadead** [comment]
> Why not redirect the user to the login page if the user is not logged in and just completed one of the courses?

One of the philosophies that we believe in is to be able to go through the curriculum (but not claiming a cert.) without creating an account. You can be an anonymous learner. We do not need your data (email, name, etc.) unless you want us to have it for awarding a cert.

**Comment by Sembauke** [comment]
I understand, 

I think my first statement is still valid. If the user is logged in (I don't know if the user has to be logged in to accept the honest policy) Why not directly move them to the honest policy (when the course is completed) with a notice that they are about to enter the certification part of the current course and recommend to log in to be able to claim the certification?

**Comment by ahmadabdolsaheb** [comment]
Here is the current user journey for the user to claim their certification. 
1. Enter the  the link to last project, click on  'I have completed this challenge'
2. See progress modal 100%, click on 'submit ...'
3. See Donation modal, click 'maybe later'
4. land on the first project of the next certificate (this is confusing)

If we don't mind showing a third modal, I think we can have one after the donation modal with a minimal confetti animation that have relevant info and links for claiming the cert that the user worked so hard for.

We could also, have a claim certificate card that display this relevant info and links with claim cert button in certification map so the user has a place to go back to in case there are multiple items that needs attention before.

Thoughts?

**Comment by Sembauke** [comment]
Fun idea to add a confetti animation after completing a course. I also recommend showing the donation model after completing the course.  

What if the user is able to claim the certificate inside the confetti-course-completion widget?

**Comment by ahmadabdolsaheb** [comment]
We could have the cert claimable if all requirements are passed.
If the user visits settings or claim and visit cert we will not be able to show the donation modal with relevant info. Therefore, donation modal need to come first.

Additionally, we might need to research what an optimal flow would be regardless of what we are offering currently.

**Comment by Sembauke** [comment]
I don't really understand what you mean by: "showing a donation modal with relevant info" ?

**Comment by ShaunSHamilton** [comment]
@Sembauke I understand the issue to be: Unless a Camper is donating, a modal containing a reminder about donating pops up every few challenges (5, I think).

So, with the current workflow, there is a conflict at step 2 (summarised this https://github.com/freeCodeCamp/freeCodeCamp/issues/38569#issuecomment-777745309):
1) Finish 5 projects, and submit
2) Donation modal appears (action must be taken - donate or close)
3) Camper needs to go to settings to claim cert

---

@ahmadabdolsaheb Personally, I would say please do not have a third modal.

What about changing the progress modal to include the certificate claiming information Mrugesh mentioned?
- If it is a project modal && progress is 100%

**Comment by Sembauke** [comment]
That is a great idea Shaun. I understand an other modal popping up could be annoying. 

Ps- After reading so many different messages in this discussion I get a bit lost.

**Comment by ahmadabdolsaheb** [comment]
> @Sembauke I understand the issue to be: Unless a Camper is donating, a modal containing a reminder about donating pops up every few challenges (5, I think).
> 

We do have a block completion donation modal that pops up after every 100% block completion and has a congratulatory message regarding the recently completed block.  
 
> What about changing the progress modal to include the certificate claiming information Mrugesh mentioned?
> 
> * If it is a project modal && progress is 100%

I thought about that, but the project submission from the completion modal needs happen before showing certification info.

**Comment by ShaunSHamilton** [comment]
@ahmadabdolsaheb Can we combine this and #40873 to make the _"widget"_ a button which brings up a _Claim Certification  with Check_ modal?

**Comment by ahmadabdolsaheb** [comment]
Here is the the user journey that I think would make the most sense at this point. Feel free to leave your feedback.

#### Current 
- User enters the solution on the project form and clicks on button
- User sees a completion modal and click submit
- User is taken to the next superblock’s first project challenge.
- User is shown a donation Modal and closes it.
- User searches for how to claim a freeCodeCamp certificate
- User lands on settings page
- User finds and completes certification requirements one by one
- User claims certificate and visits it
- User sees donation element on top of the certification

#### Proposed 
- User enters the solution on the project form and clicks on button
- User sees a completion modal and click submit
- User is taken to the certificate part of super block page ( which has links to cert requirements, their status, and claim/show cert button)
- User is shown a donation Modal and closes it
- User follows links and completes requirements
- User claims certificate and visits it from superblock page
- User sees donation element on top of the certification.

note:
- If this is implemented, we could a/b test removal of the donation modal for the projects block.
- the certification card will be combined with the certification  or replace it.

**Comment by ShaunSHamilton** [comment]
I do not understand this section:
> the certification card will be combined with the certification or replace it.

What is a 'certification card' ?

**Comment by ahmadabdolsaheb** [comment]
It is a pattern we use in the superblock page and landing page to group related information in a container.

ex. https://github.com/freeCodeCamp/freeCodeCamp/issues/38569#issuecomment-770375970

**Comment by ahmadabdolsaheb** [comment]
<img width="902" alt="Screen Shot 2021-02-18 at 5 09 00 PM" src="https://user-images.githubusercontent.com/4591597/108368980-1efcf380-720c-11eb-81af-52e5cb7e175c.png">

Here is what I have in mind for the certification card. We would probably just show the `Show certification` button after the certificate has been claimed.

I agree that incorporating the card into @moT01's widget would make it more appealing, but I could not find a way to make it functional and aesthetic at the same time.

Please let me know about your feedback so we could move forward with the implementation.

**Comment by moT01** [comment]
Might be my first thumbs down ever - it's a sarcastic thumbs down though. It's fine to get rid of my widget - I just liked it. This does look pretty good, I suppose.

**Comment by raisedadead** [comment]
We can have that widget replace this "card" when the cert is claimed? I kind of liked that too.

**Comment by moT01** [comment]
Some side notes on our current flow that I just noticed: you don't actually need to have your timeline or certifications public to claim a cert. Also, setting your timeline to private doesn't actually disable your certs, this look like a bug - you can still view the cert.

**Comment by nhcarrigan** [comment]
> Also, setting your timeline to private doesn't actually disable your certs

Should it? I know the settings page *says it does*, but why? The timeline is the bit at the bottom, but the certificates would still be visible as buttons at the top. I'm wondering if that message should be removed, instead.

**Comment by moT01** [comment]
That's certainly something we can discuss. I suppose if you hide your timeline, you perhaps intend to hide your submitted projects - which need to be visible for the certs?

**Comment by ShaunSHamilton** [comment]
@ahmadabdolsaheb I am alo _"thumbs down"_ in **approval**. That looks excellent.

> We can have that widget replace this "card" when the cert is claimed?

I would like this too.

> Should it?


@nhcarrigan This is related here, I think: https://github.com/freeCodeCamp/freeCodeCamp/issues/40403#issuecomment-779957353

**Comment by nhcarrigan** [comment]
You'd also have to hide the actual certifications, tho - since we now have the projects showing up there.

**Comment by moT01** [comment]
I made [an issue] to move the discussion around the private timeline over there, but it might be related enough to just keep here.
