### ISSUE TITLE
"Waypoint: Create a Set of Radio Buttons" Redundant Lesson Text

### ISSUE THREAD

**Issue by CodeNonprofit** [FreeCodeCamp/FreeCodeCamp#3856]
Lesson text repeats itself:

"You can use radio buttons for questions where you want the user to only give you one answer.

Radio buttons are a type of input.

Each of your radio buttons should be nested within its own label element.

All related radio buttons should have the same name attribute.

Here's an example of a radio button: <label><input type="radio" name="indoor-outdoor"> Indoor</label>.

Add to your form a pair of radio buttons. Each radio button should be nested within its own label element. They should share a common name attribute. One should have the option of indoor and the other should have the option of outdoor."

**Comment by mrobin88** [comment]
It is a style choice of the writer of this lesson. A bug would be error in the code the stopped the the script or program from executing as intended.

**Comment by RalucaBaila** [comment]
What's the SOLUTION ?
Is not working for me too
