### ISSUE TITLE
Challenge gets completed without ";" in the code

### ISSUE THREAD

**Issue by hirawatt** [freeCodeCamp/freeCodeCamp#38574]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/declare-string-variables

**Tell us about your browser and operating system:**
* Browser Name: Brave Browser
* Browser Version: 
* Operating System: Linux Mint

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ojeytonwilliams** [comment]
We try not to be opinionated about JavaScript style and
```js
var myFirstName = "first"
var myLastName = "last"
```
is syntactically valid, so it should pass the tests.
