### ISSUE TITLE
Waypoint: Build Web Apps with Expressjs - N/A: version "v0.11.14" is not yet installed

### ISSUE THREAD

**Issue by UziTech** [FreeCodeCamp/FreeCodeCamp#3857]
if you get this error  you have to install nvm v0.11.14 before running `fcc_express/setup.sh`

`nvm install v0.11.14`
`git clone http://github.com/reddock/fcc_express && chmod 744 fcc_express/setup.sh && fcc_express/setup.sh && source ~/.profile`

**Comment by awesomeaniruddh** [comment]
Closing this as not an issue.
