### ISSUE TITLE
Unexplained scopes in ES6: Compare Scopes of the var and let Keywords

### ISSUE THREAD

**Issue by GrimPixel** [freeCodeCamp/freeCodeCamp#38575]
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/compare-scopes-of-the-var-and-let-keywords
In this lesson, “block scope” is not explained, at least not so clear as what https://www.w3schools.com/js/js_let.asp does.

The sentence 

> `i` is not defined because it was not declared in the global scope

is especially confusing because if `i` is declared with `var` in the same situation, the console will not return “`i` is not defined”.

The points are: 
1. What kinds of scope exist?
2. What scopes can `var` and `let` have?

**Comment by moT01** [comment]
Any suggestions @GrimPixel?

I think the challenge as a whole could use some simplification. The code examples feel more complicated than they need to be to illustrate the concept. The description is quite long as well. But that's a whole rewrite of the challenge. I'm not sure it's worth it.

**Comment by GrimPixel** [comment]
I think

**1.**

```
console.log(printNumTwo());
// returns 3
```

can be added to the end of the 3rd section.

**2.**

> This behavior will cause problems if you were to create a function and store it for later use inside a for loop that uses the i variable.

> This is because the value assigned to i was updated and the printNumTwo() returns the global i and not the value i had when the function was created in the for loop.

“because” can be replaced with “for”, like this:

“For `var`, if they are declared in loop scope or function scope, they are ...”

“For `let`, if they are declared in loop scope or function scope, they are ..., besides, `let` can have block scope, which is ...”

**Comment by jasnkwcz** [comment]
I'm a new contributor but as someone who has struggled with understanding unclear verbiage like this before, I'd really love to help out. Is there any way I can help contribute to this issue?

**Comment by ptkpyitheim** [comment]
How should we go about this? I have a feeling that the entire problem statement can be significantly shortened and still be more effective in delivering the concept

**Comment by udayanshevade** [comment]
Hey @moT01 I tried out some different options. I'll post some screenshots in sequence.

---

(1) For the first code example, I tried a `while` loop comparing variable declarations.

Showcasing both a `while` and a `for` loop (in combination with the `if` statement in the challenge) might further cement the idea of the block scope.

I also reworded the text a bit:

<img width="891" alt="Screen Shot 2020-10-05 at 1 14 23 PM" src="https://user-images.githubusercontent.com/11330558/95127489-e8b35180-070c-11eb-92a9-41ed3d2727a5.png">

---

(2) In general, I'm having issues retaining all the current content and cutting the length. In addressing the `printNumTwo` scenario that follows, I actually ended up adding a paragraph and an example to clarify things 😅

In the end, it might be better to cut that example or replace it with a simpler one, but I do feel it conveys some useful ideas. Maybe it should be separated into its own follow-up lesson?

Introducing the `printNumTwo` scenario:

<img width="886" alt="Screen Shot 2020-10-05 at 2 53 39 PM" src="https://user-images.githubusercontent.com/11330558/95136299-bf012700-071a-11eb-8784-64cd09a9a305.png">

Explaining a possible solution with `var`:

<img width="894" alt="Screen Shot 2020-10-05 at 2 56 53 PM" src="https://user-images.githubusercontent.com/11330558/95136515-1901ec80-071b-11eb-8e88-ff1bd4df9db0.png">

Finally a solution using `let`:

<img width="882" alt="Screen Shot 2020-10-05 at 1 27 03 PM" src="https://user-images.githubusercontent.com/11330558/95128919-01246b80-070f-11eb-856d-3b3a516e0e06.png">

**Comment by Ieahleen** [comment]
the challenge seems to have been updated since when this issue was opened, do you think there are still issues with this challenge?

**Comment by udayanshevade** [comment]
@Ieahleen that's strange, I wasn't able to see any updates. The challenge still looks the same for me.

**Comment by Ieahleen** [comment]
oh, sorry, it seems the version I remember was changed before this then
