### ISSUE TITLE
Update the styles on the contributing documentation

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#38589]
We want to update the styles and theme on the [contributing documentation](https://contribute.freecodecamp.org) site. [Here is a guide](https://contribute.freecodecamp.org/#/how-to-work-on-the-docs-theme) on how to work on the theme and styles.

We would want to:

1. Remove the extraneous CSS 
   - I had shamelessly copied the code from Netflix's awesome pollyjs project [here](https://github.com/Netflix/pollyjs/blob/master/docs/assets/styles.css) while setting up the site.
   - The CSS above depends on the `vue.css` that ships with `docsify`.
2. Write our own theme with [`docsify-themeable`](https://jhildenbiddle.github.io/docsify-themeable/#/).
3. ~Have the Universal Nav~ (already done).
4. Fonts and colors should follow our [design style guide](https://design-style-guide.freecodecamp.org/).
5. Use larger font size similar to our main sites

**Comment by raisedadead** [comment]
I did some more monkey patching to make the site look nicer. We would still want to write our own theme. Standardise the fonts and colors a little bit.

**Comment by KBB99** [comment]
Can I work on this?

**Comment by raisedadead** [comment]
Yes. 

You should give the guidelines a read 😅 . [Check this](https://contribute.freecodecamp.org/#/index?id=what-do-these-different-labels-that-are-tagged-on-issues-mean), you do not need permission to work on help wanted issues.

**Comment by KBB99** [comment]
Got it, I'll try to have it finished by Monday

**Comment by sujithnath** [comment]
@KBB99 Let's do it together if @raisedadead is okay with it? I will read the contribution guide too :D

**Comment by KBB99** [comment]
Sounds good @sujithnath . I'll change the fonts to match the Free Code Camp font.

**Comment by Twaha-Rahman** [comment]
@KBB99 Are you still working on the PR to change the font? If you are busy, I can take it from here.....

**Comment by Twaha-Rahman** [comment]
@raisedadead Would you like to create a new CSS file for the docsify theme or add the CSS to the already existing `custom.css`?

**Comment by raisedadead** [comment]
We would prefer updating the `theme.css` currently in the `/docs/components`. You are welcome to purge and tweak as per your best judgement.

Criteria:
- We want the fonts to be legible and readable using the typography from the design guide.
- Modular if posible, to be able to use dark/light mode would be nice touch.

**Comment by ojeytonwilliams** [comment]
@raisedadead any thoughts on hosting the FontAwesome fonts rather than using the kit?  The kit creates a flash of unstyled content and sometimes takes a while to load.

**Comment by raisedadead** [comment]
I think I used our pro license. We sure can host it too, but I am not sure it can be bundled any better because all of this is client side.

**Comment by ojeytonwilliams** [comment]
Unless there's a licensing issue with putting pro fonts on GitHub, I think it should be okay. Rather than going render -> get kit -> re-render it would be get fonts from GitHub -> render.  Everything style related should be ready before the first render.

I guess the ideal solution would be to inline the svgs, but that's both a pain and possibly not okay as far as FontAwesome are concerned.

**Comment by raisedadead** [comment]
I will check about hosting, but we are a public repo, so I think it would not be possible to host the licensed icons. We could always swap these for the free (open-source) ones and host that instead, which I am fine with.

**Comment by thecodingaviator** [comment]
Hi, I'll pick this up. No promises on when I'll get it done though

**Comment by NinjaInShade** [comment]
Hi! Looking to contribute. Can you explain/clarify what still needs to be done. Thanks. 😊

**Comment by Renenelw23** [comment]
Why are you being a Pic help me pls is ll bout money i dinyhave work my
husband jobless ND I have 2 kids sure u saw my fb. God help me pla I was
playing round why who gives u the power to now u need to please se help me

Rene Nel
0739871719
