### ISSUE TITLE
helper functions for challenge tests across curriculum

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#38584]
Implement all the features that was attempted in the https://github.com/freeCodeCamp/freeCodeCamp/pull/38358

**Comment by whoAbhishekSah** [comment]
@raisedadead can you please assign me to this issue. 
I would like to contribute.

**Comment by raisedadead** [comment]
Hi thanks for your interest. 

It is not required to be assigned an issue. You are welcome to ask queries here on in the [contributors chat room](https://gitter.im/FreeCodeCamp/Contributors).

I recommend you to read our guidelines for contributing first, and [why typically do not assign issues](https://contribute.freecodecamp.org/#/?id=how-do-i-get-an-issue-assigned-to-me).

**Comment by hassaanp** [comment]
Hey @raisedadead 
Correct me if I am wrong. Is this issue asking to use the helper functions in place of the existing regex checks and local functions across the `curriculum` directory?

**Comment by raisedadead** [comment]
Yes, that is correct. 

We have permission from Randell that we are able to use the code that he attempted on his PR and work from there.

When ready, I will add their email in the commit to give them credit. Thanks for taking this up. Let us know if you have any queries.

**Comment by hassaanp** [comment]
Thank you for clarifying.

Why was the original attempt discarded?

**Comment by raisedadead** [comment]
No particular technical reason, other than the OP having to work on other things.

**Comment by hassaanp** [comment]
acknowledged
