### ISSUE TITLE
Re-enable linting

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/FreeCodeCamp#3858]
A linter needs to be added to the FCC code editor. 

#3566 
cc: @benmcmahon100 @QuincyLarson

**Comment by BerkeleyTrue** [comment]
There already is one. Currently we use jshint. This will change in the future.

**Comment by abhisekp** [comment]
@BerkeleyTrue I don't see any linting marks in the gutter.

### FCC
![](http://i.imgur.com/e36YzUX.png)

### JSBin
![](http://i.imgur.com/qxB43Kg.png)

**Comment by abhisekp** [comment]
@BerkeleyTrue could you please explain the reason of marking it **blocked** label?

**Comment by BerkeleyTrue** [comment]
It's blocked because we already have lint. It looks like something might have disabled it.

**Comment by abhisekp** [comment]
Today, FCC was restarted but I don't see any linting.

![](http://i.imgur.com/zonOhNI.png)

Can you please check it?

**Comment by ltegman** [comment]
@abhisekp The latest commit to the master branch was 7 days ago, so this isn't in the production codebase yet.

**Comment by abhisekp** [comment]
@ltegman ah! Alright. I thought FCC is constantly updated every day.
