### ISSUE TITLE
Convert email to lowercase when receiving from OAuth 2 Provider

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#38581]
The email string is received as is before a db query. This makes it for a rare bug, when OAuth 2 providers send it in the case the users chose to store it with them.

A mismatch can happen between emails: `Someone@example.com` and `somone@example.com`, etc, leading to failed login attempts.

We should convert the email received to lowercase to be safe (because that's how we store it in db).

**Comment by raisedadead** [comment]
https://github.com/freeCodeCamp/freeCodeCamp/blob/2b60f3e61e20e0dd8813bf658672e08538b1d24f/api-server/common/models/User-Identity.js#L44-L47

**Comment by Sky020** [comment]
I have created a straight-forward fix to the issue, but was wondering if you were expecting something similar to the `ensureLowerCaseString` function?

**Comment by AshNaz87** [comment]
My bad @Sky020 

Just saw your PR. Please ignore my PR if it doesn't help

**Comment by Sky020** [comment]
@AshNaz87 , no worries. I think both of our PRs are not going to cut it though. I am looking to see the possible values of `profile.emails[0].value`, and we both have uncaught type errors if it evaluates to `undefined`.

**Comment by raisedadead** [comment]
Hi Ashraf, thanks for your PR. I just closed yours, I would encourage you and Shaun to pair on this maybe?

As for the values, I think you can simply add something along these lines:

```js
let val = '' + profile.emails[0].value.
val.toLowerCase()
```

This should be enough. Everything is from then on is handled I think. So we should be good.

**Comment by AshNaz87** [comment]
@Sky020 Go for it :)

**Comment by Sky020** [comment]
Thank you, @raisedadead and @AshNaz87 . I have committed as you put it.
