### ISSUE TITLE
Some jQuery challenges often won't pass with a passing solution

### ISSUE THREAD

**Issue by glenmoyes** [freeCodeCamp/freeCodeCamp#38592]
Many of the jQuery challenges won't pass even with a passing solution. Sometimes just changing the indenting affects the ability for the test to pass, and just running the test again without changing anything can cause the tests to pass as well.

Example of one such challenge: https://www.freecodecamp.org/learn/front-end-libraries/jquery/target-the-parent-of-an-element-using-jquery

I've upload a video on the problem and how to reproduce the bug: https://youtu.be/a3LKWyk_4YE

Windows is the host OS. Problems occurred in Firefox (75.0 64-bit, with plugins) and Chrome (Version 80.0.3987.163 Official Build 64-bit, without plugins). I didn't have any problems using the Edge browser.

**Comment by raisedadead** [comment]
Hi @glenmoyes 

Thanks for your report.

We would need you to add the issue report in the requested format, along with the code that you used and as much details as possible.

We understand that you recorded and added a video, but it does not help us copy and test the code you had to reproduce and investigate.

I am closing this for now. But please re-open a fresh issue filling the issue template.
