### ISSUE TITLE
Buggy behaviour in the pomodoro clock

### ISSUE THREAD

**Issue by ukchukx** [FreeCodeCamp/FreeCodeCamp#3859]
When the break and sessions are set to 0, and the clock is clicked, the display cycles between 'Session' and 'Break!' every second, while playing "the sound". 
Here's my 2 cents: If both durations are 0, the clock shouldn't start when the user clicks it, as there is no time to count down from.
Keep up the good work.

**Comment by platypusrex** [comment]
I figured the better solution was just making sure going below a minute wasn't an option. After all, it is a count down timer of sorts. What's the point of a timer with no initial time to count down?

**Comment by SaintPeter** [comment]
Paging @storbeck :smile:

**Comment by storbeck** [comment]
I've switched it to having a minimum session and break length of 1 minute instead of 0. Thanks for reporting this issue.

**Comment by ukchukx** [comment]
Ok. Thanks.

**Comment by SaintPeter** [comment]
Thank you @storbeck for the fix.
