### ISSUE TITLE
steamroller fifth test fails for function names containing flat

### ISSUE THREAD

**Issue by piouson** [freeCodeCamp/freeCodeCamp#38593]
Edit: sorry, same as #38491
**Describe your problem and how to reproduce it:**
The fifth test for Steamroller algorithm fails for function names containing **flat**

> Your solution should not use the `Array.prototype.flat()` or `Array.prototype.flatMap()` methods.
```js
const flatten = array => { } // this will fail the fifth test
function steamrollArray(arr) {
  return arr; // even without the function call
}
```

**Add a Link to the page with the problem:**
[Intermediate Algorithm Scripting: Steamroller](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/steamroller)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: v81
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/17856665/79809044-6f46c300-8367-11ea-86fc-2f549afb1614.png)

**Comment by scissorsneedfoodtoo** [comment]
@piouson, awesome, great catch here. The issue seems to be with this `testString`, which is a bit too flexible:

```
testString: assert(!code.match(/\.?[\s\S]*?flat/) && !code.match(/\.?[\s\S]*?flatMap/));
```

For some reason `.` characters before `flat` or `flatMap` are optional. This could be changed to ensure that we're only catching those array methods, not other variables, functions, or even comments that include "flat".

**Comment by piouson** [comment]
My bad @scissorsneedfoodtoo same as #38491 and #38497

**Comment by scissorsneedfoodtoo** [comment]
@piouson, ah, I didn't notice those other ones. Thanks for bringing this up, though! It's definitely something we want to fix.
