### ISSUE TITLE
Universal nav overlaps on anchor navigation

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#38606]
![2020-04-22 17 27 10](https://user-images.githubusercontent.com/1884376/79980886-6538d780-84c1-11ea-968e-f4d8465c1303.gif)

**Comment by raisedadead** [comment]
Sample URL: <https://contribute.freecodecamp.org/#/index?id=our-open-source-codebase>

**Comment by Sky020** [comment]
@raisedadead , I am trying to work on the docs locally, and I have cloned the latest push of the repo, but my docs do not have the navbar. Am I missing something about running the docs locally?

**Comment by raisedadead** [comment]
See: https://contribute.freecodecamp.org/#/how-to-work-on-the-docs-theme

**Comment by raisedadead** [comment]
If you have installed and set up freeCodeCamp locally, you can simply do:

```sh
npm run docs:serve
```

which should prompt a URL at which its serving the site.

**Comment by Sky020** [comment]
Right. I did all that. Turns out, I was syncing with my fork, and not fCC's.
