### ISSUE TITLE
Wrong calculation results

### ISSUE THREAD

**Issue by ukchukx** [FreeCodeCamp/FreeCodeCamp#3860]
The sample calculator displays wrong answers for calculations performed. E.g
3-6+2 produces 1- instead of -1.

**Comment by SaintPeter** [comment]
@storbeck 
Can you please fix your sample calculator?

**Comment by storbeck** [comment]
This has been fixed. Thanks for reporting it.

**Comment by SaintPeter** [comment]
Thank you @storbeck for the fix.
