### ISSUE TITLE
Package organization

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#38626]
# The plan

- [ ] Move all packages to a common directory
- [ ] Make those packages into modules
- [ ] Publish them (ideally this should be automated)
- [ ] Only allow use of the published packages

# The justification

Currently there are multiple packages inside the freeCodeCamp monorepo.  Those packages are a little disorganised:
https://github.com/freeCodeCamp/freeCodeCamp/blob/987297fa2f4dab3e15f0c40a67403e59383a899d/lerna.json#L2-L11

rather than just being in a single `packages` directory and are tightly coupled: https://github.com/freeCodeCamp/freeCodeCamp/blob/987297fa2f4dab3e15f0c40a67403e59383a899d/client/utils/buildChallenges.js#L3-L7

i.e. the `client` is importing directly from the `curriculum`.

Separating these out should make their roles and interactions clearer and easier to understand.

**Comment by ojeytonwilliams** [comment]
The publishing part may or may not be necessary, but I do think it's important to keep the different packages decoupled.

**Comment by raisedadead** [comment]
I think:

- The tools should become pure tools and publishable packages that we can consume. 
- The client, API and the contributors dashboard apps do not make sense to be treated like the tools packages. We should make their bootstrapping independent. 
- So we should instead do two types of bootstrapping, one for tools and the other for apps.
- The curriculum directory can become a pure content directory. Which would later allow us to build abstraction from even outside of GitHub and Git (\*cough\* challenge editor CMS \*cough\*).
- Search indexing can be moved into tools.

**Comment by raisedadead** [comment]
**Yes, we should decouple as much as possible. This will make local setup cleaner, and deployments easy**

**Comment by raisedadead** [comment]
**Relevant discussion moved here: https://github.com/freeCodeCamp/freeCodeCamp/issues/39297#issue-663897024**

We should make sure the `devDependencies` have all the dev tooling and none of the production tooling.  For instance, `copy-webpack-plugin` is in `devDependencies`, but is used in production.  Once we've done this, we can cut them out of the pipelines.

Also, some Babel packages are only included as dependencies of Gatsby, not directly in `package.json`, since Gatsby is just a site generator, I think it makes sense to explicitly include everything we use.  Thoughts?

**Comment by ojeytonwilliams** [comment]
To clarify slightly what 'dev' and 'production' mean for the client:  the client has dependencies that it only uses in testing (which can be dev deps) and the rest that it needs when being built (which can be prod deps).  

**Based on #40834:**

For simplicity's sake, I think the structure should be:

| directory | depends on |
| - | - |
| everything except tools | utils, config, root prod dependencies |

and their own packages, of course.  This far, far easier to understand, build and maintain, but we would have to do a bit of work to make sure the client still reloads quickly whenever a challenge changes.

I'm not sure what we want to do with the tools, honestly.  A lot of them are used in development, so maybe it's enough to confirm that everything they use is a dev dep.

**Comment by ojeytonwilliams** [comment]
This is pretty stale and has been complicated by the TypeScript migration and the need for additional tooling: https://github.com/freeCodeCamp/freeCodeCamp/issues/42892
