### ISSUE TITLE
Background colour of "Donate" button in /news could be changed

### ISSUE THREAD

**Issue by AshNaz87** [freeCodeCamp/freeCodeCamp#38627]
As the colour red is widely considered to be prohibitive or an error, would it be better if we could use another colour from the fCC palette?

Had a cursory search of charities and most had shades of blue and even yellow as a background colour.

**Comment by moT01** [comment]
Red is certainly attention grabbing, but I think yellow might look a little better and still have the same effect.

**Comment by AshNaz87** [comment]
Shade of blue/green? Though that may be not be performant in terms of a11y, depending on the shade

**Comment by raisedadead** [comment]
Quincy is opinionated about the colour of the donate button on `/news`. As per him, he did some research and has some analytics to back it up. 

Thanks for your thoughts though.
