### ISSUE TITLE
Add forum topic ID to rosetta challenges

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#38629]
I noticed that @NitronR has added a ton of content to mostly the rosetta code section (thanks BTW). You can see a [list of his PR's here](https://github.com/freeCodeCamp/freeCodeCamp/pulls?q=is%3Apr+author%3AnitronR+is%3Aclosed). I did forum search for a couple of the challenges and it looks like guide pages have been created, but I noticed that the `forumTopicId` wasn't added to many of the challenges. We should go through those PR's and add the `forumTopicId` field to the frontmatter and make sure a guide page is created. If the PR is getting large, it might be a good idea to break it up into several.

**Comment by rajatgupta24** [comment]
Hi, I'm a beginner and want to contribute to this issue can you please guide me sir.

**Comment by moT01** [comment]
Here's what you can do @rajatgupta24 - if you're up for it. 
- Create a draft PR
- go through the rosetta code challenge files and find the ones that don't have the forumTopicId at the top
- do a forum search for the challenge and add the forumTopicId to the file if you find a guide page already exists
- make a list of the ones that don't exist, and I can find a way to make new pages for those - which can then be added to the PR.

If you haven't contributed before or set up freeCodeCamp locally, you can learn how from the [steps in our documentation](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md).

Let me know if you need more assistance - or you can try reaching out in the [contributors room on gitter](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by aaryandewan** [comment]
Here's the list of the Rosetta Challenges that don't have `forumTopicId `. They all don't have any guides in the forums as well.

1. Last letter-first letter
2. Letter frequency
3. Levenshtein distance
4. Linear congruential generator
5. Long multiplication
6. Longest common subsequence
7. Longest increasing subsequence
8. Longest string challenge
9. Look-and-say sequence
10. Loop over multiple arrays simultaneously
11. LU decomposition
12. Lucas-Lehmer test

**Comment by aaryandewan** [comment]
@rajatgupta24 Are you still working on this? If you're not, I'd love to.

**Comment by rajatgupta24** [comment]
@aaryandewan sorry for being late but i'm still working on this, thanks btw.
@moT01 
here's list of Rosetta Chanllenges that don't have `forumTopicId` & whose guide pages don't exist : 

1. Last letter-first letter
2. Letter frequency
3. Levenshtein distance
4. Linear congruential generator
5. Long multiplication
6. Longest common subsequence
7. Longest increasing subsequence
8. Longest string challenge
9. Look-and-say sequence
10. Loop over multiple arrays simultaneously
11. LU decomposition
12. Lucas-Lehmer test

**Comment by moT01** [comment]
Note: Add these to the list of challenges without guide pages... https://github.com/freeCodeCamp/freeCodeCamp/pull/38624/files

**Comment by moT01** [comment]
I created guide articles for all the challenges mentioned here @rajatgupta24...

the 12 you and @aaryandewan found:
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-last-letter-first-letter/385256
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-letter-frequency/385263
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-levenshtein-distance/385264
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-linear-congruential-generator/385266
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-long-multiplication/385269
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-longest-common-subsequence/385271
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-longest-increasing-subsequence/385272
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-longest-string-challenge/385275
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-look-and-say-sequence/385277
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-loop-over-multiple-arrays-simultaneously/385279
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-lu-decomposition/385280
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-lucas-lehmer-test/385281

the first PR I linked:
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-ludic-numbers/385282
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-luhn-test-of-credit-card-numbers/385284
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-lychrel-numbers/385287
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-lzw-compression/385288

the second PR I linked:
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-self-describing-numbers/385289

Where did you find those numbers you added on the PR @rajatgupta24? Each number should correspond to the ending numbers in the links above.

**Comment by cr38t1v3m1ndxlx** [comment]
Hello and good morning I hope to seek assistance with my process of learning and development. Where should I go to get started.
