### ISSUE TITLE
Bonfire: Were Art Thou - Incorrectly reports "Not an Array of Objects"

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/FreeCodeCamp#3862]
Was helping a user with Where Art Thou:
Challenge [Bonfire: Where art thou](http://www.freecodecamp.com/challenges/bonfire-where-art-thou#?solution=function%20where(collection%2C%20source)%20%7B%0A%20%20var%20arr%20%3D%20%5B%5D%3B%0A%0A%20%20var%20arr%20%3D%20collection.filter(function(item)%7B%0A%20%20%20%20%20%20var%20have%20%3D%20true%3B%0A%20%20%20%20%20%20for%20(var%20j%20in%20Object.keys(source))%7B%0A%20%20%20%20%20%20%20%20var%20key%20%3D%20Object.keys(source)%5Bj%5D%3B%0A%20%20%20%20%20%20%20%20if%20(!item.hasOwnProperty(key)%20%26%26%20item%5Bkey%5D%20!%3D%3D%20source%5Bkey%5D)%7B%0A%20%20%20%20%20%20%20%20%20%20have%20%3D%20false%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20if%20(have)%7B%0A%20%20%20%20%20%20%20%20return%20true%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%7D)%3B%0A%0A%20%20return%20arr%3B%0A%7D%0A%0Awhere(%5B%7B%20first%3A%20'Romeo'%2C%20last%3A%20'Montague'%20%7D%2C%20%7B%20first%3A%20'Mercutio'%2C%20last%3A%20null%20%7D%2C%20%7B%20first%3A%20'Tybalt'%2C%20last%3A%20'Capulet'%20%7D%5D%2C%20%7B%20last%3A%20'Capulet'%20%7D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function where(collection, source) {
  var arr = [];

  var arr = collection.filter(function(item){
      var have = true;
      for (var j in Object.keys(source)){
        var key = Object.keys(source)[j];
        if (!item.hasOwnProperty(key) && item[key] !== source[key]){
          have = false;
        }
      }
      if (have){
        return true;
      }
      return false;
  });

  return arr;
}

where([{ first: 'Romeo', last: 'Montague' }, { first: 'Mercutio', last: null }, { first: 'Tybalt', last: 'Capulet' }], { last: 'Capulet' });

```

This code is not correct, because it returns 3 objects, however this is the failing test:
"where() should return an array of objects."

It is returning an array of objects, just not the CORRECT array of objects.
This test should either be changed to see if it is an array of objects, or the failing test should report what is actually happening - that it doesn't match the expected output.

**Comment by ribeirojpn** [comment]
I believe the right message is supposed to be: "where([{ first: 'Romeo', last: 'Montague' }, { first: 'Mercutio', last: null }, { first: 'Tybalt', last: 'Capulet' }], { last: 'Capulet' }) should return an array of objects."
