### ISSUE TITLE
Basic HTML and HTML5: Define the Head and Body of an HTML Document - Hangs indefinitely if missing a backslash.

### ISSUE THREAD

**Issue by Kiralessence** [freeCodeCamp/freeCodeCamp#38621]
I know I wrote the code wrong initially, but I believe the RESPONSE to that incorrect code to be the bug here. The whole time I've been doing freecodecamp, it's been telling me, when you hit the 'Run the test' button, what is wrong in the bottom of the page. Standard stuff. I got to this segment and when I hit the test button, the browser window (google chrome), would cease to function. No forward, back, refresh etc. The middle test text would just read 'running tests'. I had to close the browser tab in order for it to restart. The first time, I lost my data on 5 previous sections which I had to re-do. No big deal, I knew how to do them quickly now. I did this 5 more times with various losses. Below is the code I wrote. 
![Screenshot (46)](https://user-images.githubusercontent.com/64227121/80144969-a2a66f00-856c-11ea-80c2-987531510849.png)

Note the lack of / on </body> For some reason, that creates a hang/freeze in the website when attempting to test that section. I fixed the code to reflect the proper </body> and it was accepted.

**Comment by raisedadead** [comment]
Hi, thanks for the report.

Please open a fresh issue adding all the details that were requested to you on the template. It will help us understand and address your concern. 

The above report is quite vague and doesn't help us much in investigation or reproducing the issue.

Help us help you :)

Thanks.
