### ISSUE TITLE
Skip Cypress installation locally?

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#38636]
Should we provide a way to skip installing cypress locally by default? This could save some bandwidth and time for users who do not want to install it / will not be working on e2e tests

**Comment by raisedadead** [comment]
Here is how we can disable binary installation: https://docs.cypress.io/guides/getting-started/installing-cypress.html#Environment-variables

**Comment by ojeytonwilliams** [comment]
Makes sense.  How about putting CYPRESS_INSTALL_BINARY=0 in .npmrc, it defaults to not installing?  We'd need to figure out how to make sure (pre scripts, probably) it's available if someone tries to run cypress, but that should be possible.

I can take a look next week, if you like.

**Comment by raisedadead** [comment]
That would be great. Thanks.
