### ISSUE TITLE
Syncing remote copy to local copy (fetching from upstream)

### ISSUE THREAD

**Issue by MarceloDamian** [freeCodeCamp/freeCodeCamp#38644]
**Describe your problem and how to reproduce it:**
I was attempting to make a pull request with the specified instructions in ["making changes locally"](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally). I followed all of the instructions to update my local copy, but somehow I wasn't able to update my local copy successfully. I am not sure if this might be a relative error or an actual bug. After a few days I found a workaround. I used git's [website](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) to have all the commits synced up and it worked. I attached the output below using git's website. This worked beautifully for me and could work for others if decided to be integrated on the contribution page. Thank you so much for reviewing my case. 

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 80.0.3987.163
* Operating System: macOS Mojave

![Image 4-26-20 at 04 44](https://user-images.githubusercontent.com/60354250/80302566-b7efe900-8778-11ea-8ffc-5d54dd47a027.jpg)

**Comment by Sky020** [comment]
The usual workflow is:
**on master**
```
git fetch upstream
git reset --hard upstream/master
git push origin master --force
```
Then, create a new branch to work on. Publish and push to your remote, and create the pull request from GitHub.

**Comment by MarceloDamian** [comment]
> The usual workflow is:
> **on master**
> 
> ```
> git fetch upstream
> git reset --hard upstream/master
> git push origin master --force
> ```
> 
> Then, create a new branch to work on. Publish and push to your remote, and create the pull request from GitHub.

Right this is what I had originally attempted

**Comment by Sky020** [comment]
Did you get an error with any of those actions? Are you sure you set-up your remotes and upstream correctly?

**Comment by MarceloDamian** [comment]
yes the remotes were set up correctly, as I stated I had followed the instructions.

**Comment by raisedadead** [comment]
> I’m not sure as to why it wasn’t letting me continue forward with the pull request.

Thanks for the feedback. Unless you can specify the errors, there is not much we can do.

However, if we were making a guess, and assumed you followed the instructions to the teeth your fork may have been soiled before you took a look at the guidelines and instructions?

You fork is  not same as your local copy, BTW. 

Not saying that this happened in your case, but if you started by quickly editing a file and submitted a PR that was merged you fork may have been soiled. 

We make this evident multiple times I think. Anyways, IMHO instructions do not need changes, we have had them verified over time.

> Nonetheless, Git’s instructions seemed to work in this case.

You meant GitHub's instructions (Git and GitHub are not related). Using them is fine, but they may not fit in the practices for this repo. 

They are too generic and will lead to inconsistencies sooner or later.

I am closing this, but please continue in [contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) for further troubleshooting.

**Comment by MarceloDamian** [comment]
Thank you so much for reviewing my case, and I definitely think it might have just been soiled. Thank you again !
