### ISSUE TITLE
Bug in: Regular Expressions: Specify Exact Number of Matches

### ISSUE THREAD

**Issue by enigma0160** [freeCodeCamp/freeCodeCamp#38640]
**Describe your problem and how to reproduce it:**
In the lesson linked below,
This will pass:
```js
let timRegex = /tim{4}ber/i;
``` 
But this wont:
```js
let timRegex = /tim{4}ber/ig;
```
The error message says: `Your regex should match "Timmmmber"` 

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/specify-exact-number-of-matches

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 81.0.4044.113 (Official Build) (64-bit)
* Operating System: Fedora 31

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Sky020** [comment]
Interestingly, this code passes:
```
let timStr = "Timmmmber";
let timRegex = /tim{4}ber/ig; // Change this line
let result = timStr.match(timRegex);
```

**Comment by Sky020** [comment]
Considering this is the testString:
```
- text: Your regex should match <code>"Timmmmber"</code>
testString: assert(timRegex.test("Timmmmber"));
```
It seems like a potential issue with the console, @ojeytonwilliams ? Related to #38474 
```
// In fCC console
const timStr = "Timmmmber";
let timRegex = /Tim{4}ber/ig;
console.log(timRegex.test(timStr)); // Returns false

// In the browser console
console.log(timRegex.test(timStr)); // Returns true
```

**Comment by moT01** [comment]
I believe the method used to solve a similar problem in [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/37941) would work here.

**Comment by Sky020** [comment]
On a side note: Should this code be left to be allowed to pass the tests?:
```
let timRegex = /T{1}immmmber/g; 
```

**Comment by ojeytonwilliams** [comment]
I don't think 
```
let timRegex = /T{1}immmmber/g; 
```
should pass, since it's just an odd way of writing `/Timmmmber/g`, rather than how you'd actually use `{n}`.

As for the console, I get
```
true
false
```
in both consoles, which seems fine.

**Comment by moT01** [comment]
I don't mind `let timRegex = /T{1}immmmber/g;` passing all that much. Mostly because I am doubting that anyone has actually used that. But I also don't mind fixing it since it's not really how it was intended to be completed. I think the easiest fix would be to change the first test...
>Your regex should use curly brackets.

to something like... `Your regex should use curly brackets to detect the number of M's.` - and update the test to check for that.

**Comment by ojeytonwilliams** [comment]
It's pretty inconsequential, honestly.  I'd prefer it to fail, but you're right - it's unlikely many people have done that while actually trying to solve the problem.

If it's fiddly to reject that while allowing valid solutions, don't worry about it.

**Comment by whyIdream** [comment]
It's straight forward and should use curly brackets.
