### ISSUE TITLE
Waypoint: Center Text with Bootstrap code validation

### ISSUE THREAD

**Issue by iTypeSlow** [FreeCodeCamp/FreeCodeCamp#3864]
<img width="993" alt="screen shot 2015-10-23 at 3 08 25 pm" src="https://cloud.githubusercontent.com/assets/13988427/10703792/13eaf734-7998-11e5-81f7-4662084e13a1.png">

in this challenge you are supposed to change the first line: 
  h2 class="red-text">CatPhotoApp</h2>
into.... this next line.
  h2 class="red-text text-center">CatPhotoApp</h2>
however if you just put in h2 class="text-center">CatPhotoApp</h2>
it sends you through and says you're awesome and stuff, however you lose the red text in the process.

I'm new to FreeCodeCamp and I know this isn't a huge issue, I just wanted to contribute.

**Comment by angelariggs** [comment]
I'm also seeing this; if I add the class 'text-center' to the h2 element after the 'red-text' class, the title flashes briefly and then stays red and left-aligned. If I put 'text-center' before 'red-text', the title turns black  but becomes center-aligned. I can't get both classes to apply. I even tried adding 'text-align: center' to the h2 element and the 'text-center' class, which centered the title, but still did not let me pass the waypoint.
