### ISSUE TITLE
jQuery: Target HTML Elements With Selectors Using jQuery

### ISSUE THREAD

**Issue by Czespo** [freeCodeCamp/freeCodeCamp#38648]
- https://www.freecodecamp.org/learn/front-end-libraries/jquery/target-html-elements-with-selectors-using-jquery

Code:
```
$(document).ready(function()
{
  $("button").addClass("animated bounce");
});
```
Errors: `You should use the jQuery addClass() function to give the classes animated and bounce to your button elements.
Your jQuery code should be within the $(document).ready(); function.`

Code:
```
$(document).ready(function(){
  $("button").addClass("animated bounce");
});
```
Error: `You should use the jQuery addClass() function to give the classes animated and bounce to your button elements.`

But:
```
$(document).ready(function() {
  $("button").addClass("animated bounce");
});
```
passes flawlessly. The test regular expressions are obviously poorly written.

**Comment by moT01** [comment]
How does that PR look @Czespo?

**Comment by Czespo** [comment]
@moT01 @AshNaz87 

PR looks good, though I have a minor suggestion for the regular expression:

`/\$\(document\)\.ready\(function\s*\(\)\s*{\n\s*\$.*button.*.addClass.*/g`
->
`/\$\(document\)\.ready\(function\s*\(\)\s*{\s*\$.*button.*.addClass.*/g`

This allows the entire function to be on a single line.

Also, should ES6 syntax be allowed? Another thing, jQuery recommends `$(<callback>)` instead of `$(document).ready(<callback>)` (which are equivalent); should that also be allowed?

**Comment by Sky020** [comment]
Just my two-cents: Ideally, all tests would look at output, and be almost impartial to method (unless the challenge explicitly excludes a method). However, the seed code is structured in such a way that a user is not asked to change it, and testing for every possible way a user might is odd.

I am all for exhaustive tests, but I think users following instructions is more pertinent.

**Comment by Czespo** [comment]
@Sky020 Hmm, you're right. I thought the seed code contained no JS. In that regard, this issue was misguided.
