### ISSUE TITLE
Improvements to the landing page

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#38658]
Here are a few improvement that could increase our conversion rate.

Todo:

- [x] use react svg components as company logos instead of company names. ( this has been done in the past, we need to revert the changes).

- [x] add as seen on section with the following image:
https://github.com/freeCodeCamp/assets/blob/master/assets/other%20assets/as-seen-on.png
(we use to have this; however, the image should be converted to an svg react component for consistency)

- [x] increase the size of the CTA button

- [x]  change the text of the CTA button "Get started (it's free)"

- [x] redirect to map if user is signed in

**Comment by sujithnath** [comment]
@ahmadabdolsaheb I will take this

**Comment by vincentendrahadi** [comment]
Hi @ahmadabdolsaheb , did anyone worked on this issue yet? If not, I want to contribute by working on this issue.
Thanks

**Comment by ahmadabdolsaheb** [comment]
@vincentendrahadi please go ahead

**Comment by ahmadabdolsaheb** [comment]
@vincentendrahadi here is the commit that made the svg components for the company logos
https://github.com/freeCodeCamp/freeCodeCamp/commit/8c921a05d6e02e89ff085a716bcbfb7a5907cbf6#diff-ac541a3ccae9520a08531d656b1223ff

and this one deleted it.https://github.com/freeCodeCamp/freeCodeCamp/commit/8c921a05d6e02e89ff085a716bcbfb7a5907cbf6#diff-ac541a3ccae9520a08531d656b1223ff

we just need to bring back @thecodingaviator's changes

**Comment by vincentendrahadi** [comment]
@ahmadabdolsaheb okay thanks
and where should i put this?
- add as seen on section with the following image:
https://github.com/freeCodeCamp/assets/blob/master/assets/other%20assets/as-seen-on.png
(we use to have this; however, the image should be converted to an svg react component for consistency)

**Comment by ahmadabdolsaheb** [comment]
It could be centered after the CTA button. If you decide to make the svg, please minify the svg first.

Here is how it used to look like.
https://medium.com/@shibajyotidebbarma/freecodecamp-my-experience-913b8398cf09

**Comment by vincentendrahadi** [comment]
@ahmadabdolsaheb done
