### ISSUE TITLE
Unable to login to freecodecamp.org using Github

### ISSUE THREAD

**Issue by bjorno43** [freeCodeCamp/freeCodeCamp#38653]
**Describe the bug**
First I wanted to login to the forums with my Github profile. It pulled my information from Github, but kept forcing me to make a new profile with that information instead of just logging me in.

Then I tried logging in on the website itself, but was presented with "Oops! Something went wrong. Please try again in a moment.". I've tried both Firefox and Chrome, but the issue remained the same.

**To Reproduce**
1. Just try logging in with a Github profile. Not sure if it's me specific or everyone though.

**Expected behavior**
It should've just logged me in.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/29444287/80323566-7d478880-882c-11ea-8144-3df5c3969dfb.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Firefox / Chrome
 - Version Firefox 75.0 / Chrome 81.0.4044.122

**Additional context**
It might be a conflict with having 2 accounts on the same Github profile now. Since the forums kept forcing me to create a new profile instead of logging me in.

**Comment by raisedadead** [comment]
Closing as discussed over email.
