### ISSUE TITLE
Issue with Bonfire: Factorialize a Number

### ISSUE THREAD

**Issue by GeminiTruth** [FreeCodeCamp/FreeCodeCamp#3865]
Challenge [Bonfire: Factorialize a Number](http://www.freecodecamp.com/challenges/bonfire-factorialize-a-number) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Whenever I try to look at my code it shows me the exercise for a second, then it shows me a blank page with 5 5 10 20

I can't look at my code from the exercise, but I have the closest copy I can give you. 

function factorialize(num) {
  if(num == 0){
	return 1;
   }
  else{
  var myArray = new Array(num);
  var size = myArray.length;
  for (i=0;i<size;i++){
    myArray[i]=num;
  }
  var fac = -1;
  myArray = myArray.map(function(val){
    fac = fac + 1;
    return val-fac;
  });
  var facTotal = myArray[0];
	document.writeln(facTotal);
  for (i=1;i<size;i++){
	facTotal = facTotal*myArray[i];
  }
    num = facTotal
	  return num;
  }
}

Would you be able to reset my exercise and I'll try to solve it a different way.

**Comment by ltegman** [comment]
In progress challenge code is stored in localStorage, so you will need to reset it yourself. You can follow this guide from the wiki on how to do that:

[How to clear specific values from your browser's local storage](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/How-to-clear-specific-values-from-your-browser's-local-storage)

Closing this issue but please feel free to comment if you need further help.

Thanks and happy coding!
