### ISSUE TITLE
Update the universal footer

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#38664]
We just rolled a new universal footer on [news](https://www.freecodecamp.org/news/) and we need to update the footer on our other platforms for consistency.
Todo:
- [ ] update the footer on /learn

**Comment by MarceloDamian** [comment]
The link "news" on the issue redirects to a faulty page. Did you by any chance mean "https://www.freecodecamp.org/news/"?

**Comment by ahmadabdolsaheb** [comment]
@MarceloDamian, Yes. Thanks for letting me know.

**Comment by abhi0977** [comment]
@ahmadabdolsaheb can I pick this?

**Comment by ahmadabdolsaheb** [comment]
Please, go ahead. @abhi0977

**Comment by Twaha-Rahman** [comment]
I'd like to update the forum's footer. Is there anyway to preview changes of other sites like `forum` or `news` on `GitPod` ?

**Comment by ahmadabdolsaheb** [comment]
@Twaha-Rahman, thanks for your interest.
For updating the footer on the forum you need to use Discourse theme creator.

Please refer to the guide for using it:
https://meta.discourse.org/t/beginners-guide-to-using-theme-creator-and-theme-cli-to-start-building-a-discourse-theme/108444

**Comment by ahmadabdolsaheb** [comment]
@abhi0977, how is the progress on this? meanwhile if anyone else is interested, they could submit a pr. The first comprehensive pr will be reviewed first.

**Comment by abhi0977** [comment]
@ahmadabdolsaheb 
I haven't started yet. Working on other things now. i'll update here once I start. 
Meanwhile if anyone is interested they can pick this up.

**Comment by ahmadabdolsaheb** [comment]
The footer requirements has changed.
