### ISSUE TITLE
Broken Test 'Basic JavaScript: Profile Lookup'

### ISSUE THREAD

**Issue by joelszn** [freeCodeCamp/freeCodeCamp#38673]
**Describe your problem and how to reproduce it:**
The problem is for test cases:
"Bob", "number"
"Bob", "potato"

To reproduce run solution 1 which is the same solution I came up with
https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-profile-lookup/18259

Attached is a screenshot of me running the same code on my browser's console returning the correct result.
![Screen Shot 2020-04-29 at 1 52 34 AM](https://user-images.githubusercontent.com/23111335/80564582-35576b80-89bc-11ea-97bf-40d63bad763c.png)

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/profile-lookup

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 81.0.4044.122 (Official Build) (64-bit)
* Operating System: macOS 10.15.4

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
### PS Love the platform and the format keep up the awesome work. I guess this is part of my giveback.

**Comment by hassaanp** [comment]
Hi @joelszn 
The second return on line 41 should return `No such property`, in the screenshot it shows that both returns are `No such property`.
The code pasted in the JS console is correct.

**Comment by moT01** [comment]
Nice eyes @hassaanp. Yea, I think this is just a typo there. Take another look @joelszn and let us know if you still think there's a problem. Otherwise, you can probably close this. Thanks.

**Comment by joelszn** [comment]
good eyes @hassaanp I didn't notice this. It ran successfully afterward. Sometimes it's the simple things that we look over!
