### ISSUE TITLE
Answer for "React: Create a Controlled Input" outputs desired outcome but without {this.state.input}

### ISSUE THREAD

**Issue by yourcontact** [freeCodeCamp/freeCodeCamp#38674]
**Describe your problem and how to reproduce it:**

An answer for "React: Create a Controlled Input" outputs desired outcome but does not pass the test

The answer:

```
class ControlledInput extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      input: ''
    };
    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(event) {
    this.setState({
      input: event.target.value
    })
  }

  render() {
    return (
      <div>
        < input value={this.input} onChange={this.handleChange} />
        <h4>Controlled Input:</h4>
        <p>{this.state.input}</p>
      </div>
    );
  }
};
```

Error message:

```
// running tests
Typing in the input element should update the state and the value of the input, and the p element should render this state as you type.
// tests completed
```

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/front-end-libraries/react/create-a-controlled-input

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 75.0 (64-bit)
* Operating System: macOS Mojave Version 10.14.6 (18G4032)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![Screenshot 2020-04-29 at 11 37 31](https://user-images.githubusercontent.com/46404814/80581726-dde1eb80-8a0d-11ea-8b05-bcba356b10b6.png)

**Comment by Sky020** [comment]
Hello there.

For future issues like this, please open a topic on the [forum](https://www.freecodecamp.org/forum). The reason for this is to iron out issues that are user-based, and not an issue with the source code.

In your example, you are not passing the test, because you are not:
>update...the value of the input

Have a look at this line:
```
< input value={this.input} onChange={this.handleChange} />
```
There is a mistake.

Thank you, for helping us keep the tests valid. I am closing this issue.

**Comment by yourcontact** [comment]
Thank you, @Sky020.
