### ISSUE TITLE
Minimum font-size in browser error

### ISSUE THREAD

**Issue by vedanthv** [freeCodeCamp/freeCodeCamp#38680]
This is a problem I found in the "Applied Visual Design: Set the font-size for Multiple Heading Elements".Even though the styling of headers in this challenge may be correct,the console gives an error stating that "h6" is not properly styled. I figured this may be due to the minimum-font-size issue of the browsers usually set to 15 or 16px(In Google Chrome and Firefox).
Just wondered if we can put a note on the left pane where the question is present.

* Link
https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/set-the-font-size-for-multiple-heading-elements

* Browser Name: Google Chrome
* Browser Version: 80.0.3987.116 
* Operating System: Linux

**Comment by vedanthv** [comment]
> This is a problem I found in the "Applied Visual Design: Set the font-size for Multiple Heading Elements".Even though the styling of headers in this challenge may be correct,the console gives an error stating that "h6" is not properly styled. I figured this may be due to the minimum-font-size issue of the browsers usually set to 15 or 16px(In Google Chrome and Firefox).
> Just wondered if we can put a note on the left pane where the question is present.
> 
> * Link
>   https://www.freecodecamp.org/learn/responsive-web-design/applied-visual-design/set-the-font-size-for-multiple-heading-elements
> * Browser Name: Google Chrome
> * Browser Version: 80.0.3987.116
> * Operating System: Linux

**Comment by moT01** [comment]
Yes, I believe this has come up before. I would rather see the [last test here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/applied-visual-design/set-the-font-size-for-multiple-heading-elements.english.md#tests) use regex I think.

**Comment by vedanthv** [comment]
But this issue comes up every now and then in the forum.
How is it possible for a beginner to use regex in this challenge ocnsidering that they may be only a few   days into the course

**Comment by moT01** [comment]
I meant to use regex to test that users entered "14px". Not that users should use regex at all. Right now the test is checking the value of the `h6` as it is rendered by the browser. If we check the input from the user, it wouldn't matter what size the browser gave the element.

**Comment by vedanthv** [comment]
I am new to Open Source Contributions,can you guide me on fixing this issue?

**Comment by moT01** [comment]
I would recommend following the [steps in our documentation to get freeCodeCamp running locally](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md).

After that you need to fix the file I linked above and make a pull request.

You can also reach out to us in our [contributors room on gitter](https://gitter.im/FreeCodeCamp/Contributors)

**Comment by AshNaz87** [comment]
Hi @moT01,

How would you target the `<h6>` element inside the `<style>` tag, as it's inside HTML?

**Comment by thecodingaviator** [comment]
@AshNaz87 I don't understand. You want to check the CSS of the `h6`. Right?

**Comment by moT01** [comment]
[Here's a test I made in the past.](https://github.com/freeCodeCamp/freeCodeCamp/blob/next-curriculum/curriculum/challenges/english/01-responsive-web-design/css-variables-skyline/part-94.md#tests)

The first part, `const fb3w = code.match(/\.fb3-window\s*{[\s\S]+?[^}]}/g)[0];`, isolates the styles for the `.fb3-window` class. Then you can more easily find if the correct styles are in there.

**Comment by AshNaz87** [comment]
Thanks @moT01. It was the `code` variable that I was missing
