### ISSUE TITLE
Dark mode for news forum

### ISSUE THREAD

**Issue by vedanthv** [freeCodeCamp/freeCodeCamp#38709]
Issue Description:
The dark mode is a feature in FCC learn and FCC forum but it is not there in FCC news.
This makes it hard to read articles in dim light.

To do:
Add Dark mode on /news

**Comment by raisedadead** [comment]
Thanks for this feature request, I think we will have to objectively gauge the interest about this. Can you post about this on the forum? Maybe tagging Quincy on the thread would be great as well.

Once we have some interest we should be able to take it up here.

Thanks.
