### ISSUE TITLE
Objective 2 text is wrong

### ISSUE THREAD

**Issue by DrewSz** [FreeCodeCamp/FreeCodeCamp#3870]
Challenge [Waypoint: Use RGB values to Color Elements](http://freecodecamp.com/challenges/waypoint-use-rgb-values-to-color-elements#?solution=%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20RGB(0%2C0%2C0)%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Text for objective two says "Use rgb to give your body element the background-color of black. For example body { color: rgb(0, 0, 0); }." 

There should be "background-" in front of the "color" in the example.

**Comment by XianPalin** [comment]
Fixed with https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3931
