### ISSUE TITLE
Meta tag - WeChat

### ISSUE THREAD

**Issue by miyaliu666** [freeCodeCamp/freeCodeCamp#38707]
Could we add a meta tag to the Chinese /news, so it shows the cover images when shared in WeChat moments? Thanks!

**Comment by ahmadabdolsaheb** [comment]
@scissorsneedfoodtoo, I believe this has been implemented if I am not mistaken.

**Comment by scissorsneedfoodtoo** [comment]
@ahmadabdolsaheb, I believe we adjusted the meta description sometime back, but there doesn't seems to be any special meta images besides what's picked up from Ghost.

Also the Chinese version of Ghost seems a bit older, and doesn't have as much granular control over the meta images and descriptions under General in the settings menu.

As a quick workaround, we could probably just add some meta tags via the Code Injection option.

**Comment by scissorsneedfoodtoo** [comment]
Heard from @miyaliu666 and it seems like we need to use the [Weixin JS SDK](https://developers.weixin.qq.com/doc/offiaccount/en/OA_Web_Apps/JS-SDK.html#0) for WeChat moments to pick up the correct cover image from each Chinese /news story that's shared.

Here's Miya's screenshot with two Chinese /news stories that are missing images:

![image](https://user-images.githubusercontent.com/2051070/93587164-6b859e00-f9e4-11ea-94af-64c68c549dc8.png)

We may need to set up an environment variable for the `appId`, but the other values for verification can be generated on the fly (`timestamp`, `nonceStr`, and so on).

Then we'll need to grab the meta data from the page that's being shared using something like `[...metaTags].filter(metaTag => metaTag.getAttribute("property") && metaTag.getAttribute("property").startsWith("og:"))...` and use the SDK to pass the correct image along. WeChat seems to pick up the correct title.

I'm thinking we can do most of this with the script injection option. How does that sound @ahmadabdolsaheb?

**Comment by ahmadabdolsaheb** [comment]
Script injection sounds good to me. We could pair on this when you wish.

**Comment by scissorsneedfoodtoo** [comment]
@ahmadabdolsaheb, sure, that sounds great :+1: :+1: 

I talked with @miyaliu666 about this last week and she will check with Quincy about creating a Weixin account. Then once she can register an app and give us the `clientId` and a few other things we'll be in business.

**Comment by ahmadabdolsaheb** [comment]
I am closing this issue since it would need an ICP license.
