### ISSUE TITLE
Feature Request for freeCodeCamp learning platform

### ISSUE THREAD

**Issue by arianneghislainerull** [freeCodeCamp/freeCodeCamp#38713]
**Is your feature request related to a problem? Please describe.**
I'm not necessarily frustrated by this problem.. However, I find it difficult for me to focus while learning programming in general. In my own opinion, there are people who work better when they are listening to music. Maybe it stimulates their mind or it energizes them? It just happens that I'm one of those people who likes learning/working while listening to music. 

**Describe the solution you'd like**
Perhaps, having more music on the background of freeCodeCamp would be better for audio learners! Also, I've noticed that there are no videos as hints for ES6 in JavaScript. I find the videos to be genuinely helpful in terms of explanation. If you'd like, you can make a bot that speaks the text.. Lastly, having a background music/sound effect when the learner gets something correctly or incorrectly would help. I find that music just makes the overall experience more enjoyable and less straining.

**Describe alternatives you've considered**
NA

**Additional context**
Thank you very much for reading my feature request. Again, this request is only a suggestion! However, it would improve learners' experience (especially audio learners)!!

**Comment by Twaha-Rahman** [comment]
Not a bad nor difficult feature request. I believe if the maintainer agree, this shouldn't the be that hard considering FCC already has [music site](https://coderadio.freecodecamp.org/). But on the flip side, it shouldn't be that hard to open a separate browser tab and play music by using FCC's [Code Radio](https://coderadio.freecodecamp.org/).

**Comment by vedanthv** [comment]
I second @arianneghislainerull on the use of bot for reading out the text but I feel the need of music is not very important at the moment because music can be played on other platforms as well(like YT,Spotify or Prime Music). What are your thoughts?

**Comment by Twaha-Rahman** [comment]
@vedanthv It'll be a low priority for sure but since FCC already has [Code Radio](https://coderadio.freecodecamp.org/), it maybe considered because merging these two features can help both of these projects

**Comment by vedanthv** [comment]
@Twaha-Rahman Yes,maybe we can add a toggle button which switches the music on and off. Will work on it today

**Comment by raisedadead** [comment]
We are working on a feature to make Code radio available right within freeCodeCamp, thanks for your patience. There are existing threads talking about this.
