### ISSUE TITLE
Bug in challenge: Rosetta Code: 24 Game

### ISSUE THREAD

**Issue by dostuffthatmatters** [freeCodeCamp/freeCodeCamp#38710]
**Describe your problem and how to reproduce it:**
My solution (see below) produces the correct result: For `solve24("4878")` my algorithm produces `(4-8+7)*(8)` which equals 24. However the automated test on this example fails - error message: `solve24("4878") should return (7-8/8)*4 or 4*(7-8/8)`.

My Code:
```javascript

function solve24 (numStr) {

  // Generate all possible combinations of ordering the numbers
  let numberCombinations = [];

  for (let i1=0; i1<4; i1++) {
    for (let i2=0; i2<4; i2++) {
      for (let i3=0; i3<4; i3++) {
        // not very elegant but short and simple ...
        if (i1 !== i2 && i2 !== i3 && i1 !== i3) {
          let i4 = 6 - i1 - i2 - i3;
          numberCombinations.push([
            numStr[i1], numStr[i2], numStr[i3], numStr[i4]
          ])
        }
      }
    }
  }

  // Format: "_n_n_n_n_"

  // Choices for symbols to fill in the gaps
  const startChoices = ["", "(", "(("];
  const midChoices = ["+", "-", "*", "/", 
  "(", ")", "((", "))", ")*(", ")/("];
  const endChoices = ["", ")", "))"];
  
  // Iterate through all number combinations
  for (let i=0; i<24; i++) {

    let combination = numberCombinations[i];

    // Again ... not pretty but simple and stupid
    for (let i1=0; i1<3; i1++) {
      for (let i5=0; i5<3; i5++) {

        for (let i2=0; i2<10; i2++) {
          for (let i3=0; i3<10; i3++) {
            for (let i4=0; i4<10; i4++) {
      
                let mathString = 
                startChoices[i1] + combination[0] + midChoices[i2] +
                combination[1] + midChoices[i3] + combination[2] +
                midChoices[i4] +combination[3] +endChoices[i5];

                try {
                  if (eval(mathString) == 24) {
                    return(mathString);
                  }
                } catch (e) {}
            }
          }
        }
      }
    }

  }

  return "no solution exists";
}

console.log(solve24("4878"));
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/24-game

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 81.0.4044.129
* Operating System: Mac OS Catalina (10.15.4)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="1680" alt="Bildschirmfoto 2020-05-02 um 19 01 02" src="https://user-images.githubusercontent.com/29046316/80870543-5a432b80-8ca7-11ea-8b7c-e129f6042bc4.png">

**Comment by scissorsneedfoodtoo** [comment]
Hi @dostuffthatmatters, thanks for reporting this. It seems like your answer `(4-8+7)*(8)` is valid and appears in the test suite:

```
['(7-8/8)*4', '4*(7-8/8)', '(4-8+7)*8', '(4+7-8)*8', '(7+4-8)*8', '(7-8+4)*8', '8*(4-8+7)', '8*(4+7-8)', '8*(7+4-8)', '8*(7-8+4)']
```

The only issue is the parentheses around the last 8. I think your answer is technically correct, but our test doesn't expect it.

**Comment by dostuffthatmatters** [comment]
You could recursively remove all parentheses around single numbers in the produced output before checking your test.

**Comment by Sky020** [comment]
To triage this, why not have the tests `assert(eval(solve24('1234')) === 24)` or similar?

**Comment by dostuffthatmatters** [comment]
@Sky020 Using eval is really unsafe - See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Never_use_eval!

The code executed from a string is being executed with the same priviliges as if the caller did so. This would be a doorway for easier XSS attacks.

**Comment by Sky020** [comment]
@dostuffthatmatters . Ah, right. Completely slipped my mind. Thank you.

**Comment by ptkpyitheim** [comment]
Hi all,

I think I've come up with a solution that would solve the problem. But the solution would only solve for situations like single numbers wrapped in unnecessary parenthesis such as `(4-8+7)*(8)` or `(4-8+7)*(((8)))` for that matter.

However it won't work for situations like `((4-8+7))*8` where there are extra parenthesis for a collection of numbers and operations. It gets trickier to solve that issue. We could leverage the use of Stack Data Structure.

If anybody is interested in finding a solution for this, please let me know. Otherwise, I can create a PR for the solution that detected extra parenthesis around single numbers.

**Comment by ptkpyitheim** [comment]
@dostuffthatmatters  Just made a pull request that has a checking that removes extra parentheses around single digits. I haven't checked for situations like this though `1*2*(3*4)` where there are extra parentheses in non-single digits
