### ISSUE TITLE
Prefilter challenge issue

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/FreeCodeCamp#3871]
Challenge [Waypoint: Prefilter JSON](http://freecodecamp.com/challenges/waypoint-prefilter-json#?solution=fccss%0A%20%20%24(document).ready(function()%20%7B%0A%0A%20%20%20%20%24(%22%23getMessage%22).on(%22click%22%2C%20function()%20%7B%0A%E2%80%89%E2%80%89%20%20%20%20%24.getJSON(%22%2Fjson%2Fcats.json%3Fcallback%3D%22%2C%20function(%20json%20)%20%7B%0A%0A%20%20%20%20%20%20%20%20var%20html%20%3D%20%22%22%3B%0A%0A%20%20%20%20%20%20%20%20json.map(function(val)%7B%0A%0A%E2%80%89%E2%80%89%E2%80%89%20%20%20%20%20%20%20val%20%3D%20%22%3Cimg%20src%20%3D%20'%22%20%2B%20val.imageLink%20%2B%20%22'%2F%3E%22%E2%80%89%0A%0A%20%20%20%20%20%20%20%20%20%20html%20%3D%20html%20%2B%20%22%3Cdiv%20class%20%3D%20'cat'%3E%22%0A%0A%20%20%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20below%20this%20line.%0Ajson%20%3D%20json.filter(function(val)%20%7B%0A%0A%E2%80%89%E2%80%89return(val.id%20!%3D%3D%201)%3B%0A%0A%7D)%3B%0A%0A%0A%20%20%20%20%20%20%20%20%20%20%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%0A%20%20%20%20%20%20%20%20%20%20for(var%20key%20in%20val)%7B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20html%20%3D%20html%20%2B%20'%3Cdiv%20class%20%3D%20%22'%20%2B%20key%20%2B%20'%22%3E'%20%2B%20val%5Bkey%5D%20%2B%20'%3C%2Fdiv%3E'%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20%20%20%20%20html%20%3D%20html%20%2B%20%22%3C%2Fdiv%3E%22%0A%0A%20%20%20%20%20%20%20%20%7D)%3B%0A%0A%E2%80%89%E2%80%89%E2%80%89%E2%80%89%20%20%20%20%24(%22.message%22).html(html)%3B%0A%0A%E2%80%89%E2%80%89%20%20%20%20%7D)%3B%0A%20%20%20%20%7D)%3B%0A%20%20%7D)%3B%0Afcces%0A%0A%0A%3Cdiv%20class%3D%22container-fluid%22%3E%0A%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%3Ch2%3ECat%20Photo%20Finder%3C%2Fh2%3E%0A%20%3C%2Fdiv%3E%0A%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%20well%20message%22%3E%0A%20%20%20%20%20The%20message%20will%20go%20here%0A%20%20%20%3C%2Fdiv%3E%0A%20%3C%2Fdiv%3E%0A%20%3Cdiv%20class%20%3D%20%22row%20text-center%22%3E%0A%20%20%20%3Cdiv%20class%20%3D%20%22col-xs-12%22%3E%0A%20%20%20%20%20%3Cbutton%20id%20%3D%20%22getMessage%22%20class%20%3D%20%22btn%20btn-primary%22%3E%0A%20%20%20%20%20%20%20Get%20Message%0A%20%20%20%20%20%3C%2Fbutton%3E%0A%20%20%20%3C%2Fdiv%3E%0A%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<script>
  $(document).ready(function() {

    $("#getMessage").on("click", function() {
      $.getJSON("/json/cats.json?callback=", function( json ) {

        var html = "";

        json.map(function(val){

          val = "<img src = '" + val.imageLink + "'/>" 

          html = html + "<div class = 'cat'>"

          // Only change code below this line.
json = json.filter(function(val) {

  return(val.id !== 1);

});


          // Only change code above this line.

          for(var key in val){

            html = html + '<div class = "' + key + '">' + val[key] + '</div>';

          }

          html = html + "</div>"

        });

        $(".message").html(html);

      });
    });
  });
</script>


<div class="container-fluid">
 <div class = "row text-center">
   <h2>Cat Photo Finder</h2>
 </div>
 <div class = "row text-center">
   <div class = "col-xs-12 well message">
     The message will go here
   </div>
 </div>
 <div class = "row text-center">
   <div class = "col-xs-12">
     <button id = "getMessage" class = "btn btn-primary">
       Get Message
     </button>
   </div>
 </div>
</div>


```

If I press the "Get Message" button, the output is one character per line,

**Comment by bugron** [comment]
Seems this issue is fixed. Closing.
