### ISSUE TITLE
Broken Test Case in Basic CSS: Size Your ImagesPassed

### ISSUE THREAD

**Issue by ojas360** [freeCodeCamp/freeCodeCamp#38712]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
When i run with 100% zoom it fails and it runs successfully for 90% zoom
![test-fail-error](https://user-images.githubusercontent.com/7880879/80893047-93ea5580-8cec-11ea-8a6d-8216a52e9972.gif)

**To Reproduce**
1. Go to 'Basic CSS: Size Your ImagesPassed' and complete the challenge
2. Click on 'Run tests with 100% on Incognito Chrome'

**Expected behavior**
Should work for 100% zoom.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Version: 81

**Additional context**
![test-fail-error](https://user-images.githubusercontent.com/7880879/80893058-a2d10800-8cec-11ea-8c12-7e1d2124e5c2.gif)

**Comment by Sky020** [comment]
Are there any objections to me changing the [test](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/basic-css/size-your-images.english.md) to regex?

This is one of those challenges that frequently comes up on the forum.

**Comment by raisedadead** [comment]
Go ahead Shaun.
