### ISSUE TITLE
Gitter Chat Embed Aside Blocks Menu in Safari OSX

### ISSUE THREAD

**Issue by hrtovey** [FreeCodeCamp/FreeCodeCamp#3874]
I'm unable to access links on the right side of the page due to an invisible aside sitting on top of the page. Works fine in Chrome. Setting this aside to display:none fixes the issue I'm having, but probably doesn't help whatever you're trying to do with the aside in the first place. :)

**Comment by abhisekp** [comment]
@hrtovey Are you referring to something related to https://gitter.im ? 

You can post issues related to it in https://github.com/gitterHQ/gitter/issues

**Comment by hrtovey** [comment]
No, this is unrelated to Gitter itself. This is the chat featured on the freecodecamp.com website itself. Even while the Gitter chat aside is collapsed, it is still sitting on top of the menu links and anything on the right side of the page.
![screen shot 2015-10-24 at 12 24 06 pm](https://cloud.githubusercontent.com/assets/5010287/10712016/324fc364-7a4a-11e5-8a6f-52735f61134b.png)

**Comment by ltegman** [comment]
Seems to be multiple issues with the gitter overlay in Safari. I can't even get the gitter sidebar to ever appear.

**Comment by ltegman** [comment]
@hrtovey Are you still able to reproduce this? All issues I was seeing with the gitter sidebar in Safari are no longer happening and I can not repro the error you were seeing.

**Comment by hrtovey** [comment]
Looks like it's been fixed. Thank you!

**Comment by ltegman** [comment]
Awesome, glad to hear it!
