### ISSUE TITLE
Test times out in Project Euler: Problem 3: Largest prime factor

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#38755]
**Describe your problem and how to reproduce it:**
The last test times out on the given problem and needs to either be removed or replaced with a smaller number.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-3-largest-prime-factor

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/34807532/81296581-b8995100-908f-11ea-8462-6a9c1ab42a9a.png)

**Comment by ojeytonwilliams** [comment]
I think it's fair to require people to use efficient algorithms for this section, so I don't think that last test should be removed.  Perhaps it's worth stressing (in the first few Euler challenges) that speed is a requirement.

That said, the solution in the challenge is wrong:

```js
const largestPrimeFactor = (number)=>{
  let largestFactor = number;
  for(let i = 2;i<largestFactor;i++){
  if(!(largestFactor%i)){
    largestFactor = largestFactor/i;
    largestPrimeFactor(largestFactor);
  }
  }
  return largestFactor;
}
```

returns 4 when given 8.  We should test for that.

I think

```js
const largestPrimeFactor = number => {
  let largestFactor = number;

  for (let i = 2; i <= Math.sqrt(largestFactor); i++) {
    if (!(largestFactor % i)) {
      let factor = largestFactor / i;
      let candidate = largestPrimeFactor(factor);
      return i > candidate ? i : candidate;
    }
  }
  return largestFactor;
};
```

Is fast enough and (hopefully!) correct.

**Comment by thecodingaviator** [comment]
Yup. That works. I see the part about efficiency.

**Comment by ojeytonwilliams** [comment]
Cool, I think this is a good candidate for a first contribution.

**Comment by UgRoss** [comment]
Hello guys! Can I take this?
as I understand the task is to update the solution block with a function that performs faster?
Thank you!

**Comment by ojeytonwilliams** [comment]
Hi @UgRoss  please do!  If you could also add one more test that validates that

> largestPrimeFactor(8) should return 2.

that would be great, since the existing solution gets that wrong.

**Comment by UgRoss** [comment]
Cool, thank you! 
Will add that too
