### ISSUE TITLE
Sign In Issues: Not able to sign into my freecodecamp account using my credentials or by using my github account

### ISSUE THREAD

**Issue by Ashwin7mak** [freeCodeCamp/freeCodeCamp#38761]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Ieahleen** [comment]
without any additional info it would totally be impossible to help you, so please complete the template with the infos required, or also check if one of the open issues on login trouble seems to describe what's going on, for example this one: https://github.com/freeCodeCamp/freeCodeCamp/issues/37457

**Comment by raisedadead** [comment]
See https://freecodecamp.org/support
