### ISSUE TITLE
for Euler Problem 43 - numbers must be in a certain order to pass the tests (but it is not specified)

### ISSUE THREAD

**Issue by Ieahleen** [freeCodeCamp/freeCodeCamp#38769]
challenge link: https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-43-sub-string-divisibility
file link: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-coding-interview-prep/project-euler/problem-43-sub-string-divisibility.english.md

for this challenge it asks for array `[ 1430952867, 1460357289, 1406357289, 4130952867, 4160357289, 4106357289 ]` as result to pass the tests
and in fact the following pass the tests:
```
function substringDivisibility() {
  // Good luck!
  return  [ 1430952867, 1460357289, 1406357289, 4130952867, 4160357289, 4106357289 ];
}

substringDivisibility();
```

but if I take that array and change the order of the numbers, like for example the below, the tests do not pass anymore:
```
function substringDivisibility() {
  // Good luck!
  return  [ 1406357289, 1430952867, 1460357289, 4106357289, 4130952867, 4160357289 ];
}

substringDivisibility();
```

there is not written anything about a required order.

suggestions: request the array to be sorted in some way, or sort the array in the tests before comparing it to keep using `assert.deepEqual` or change the tests to be a bit less rigid

**Comment by Sky020** [comment]
Perhaps better to use `assert.sameMembers`
