### ISSUE TITLE
"Basic Javascript: Local scope and functions" tests throws a regex error in firefox

### ISSUE THREAD

**Issue by ngrosso** [freeCodeCamp/freeCodeCamp#38767]
**Describe your problem and how to reproduce it:**
Using Firefox and Firefox Developer edition and doing the challenge ["Basic JavaScript: Local Scope and Functions"](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/local-scope-and-functions), when completing the challenge the console throws the error: 
`// running tests
You should add a local myVar variable.
// tests completed
// console output
SyntaxError: invalid regular expression flag s`
When the local var is well defined, tested in Chrome and worked

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/local-scope-and-functions

**Tell us about your browser and operating system:**
* Browser Name: Not working in Firefox and Firefox Developer edition (worked in Chrome)
* Browser Version: Firefox developer edition v77.0b3(64-bit)
* Operating System: Ubuntu 18.04.4 LTS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/11824720/81416302-e928cb80-911f-11ea-8ade-d2a53a099ae2.png)

**Comment by Sky020** [comment]
Thank you, for bringing this up. We are aware of the issue. This is expected to be fixed by #38762.
