### ISSUE TITLE
Add a test to check that each challenge file ends with .language.md

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#38763]
A number of challenges were added that just have the `.md` extension. I'm not sure if that's a problem, but most challenges end with `.english.md` or `.other-language.md`. We could maybe add a test to check that each file ends with that.

**Comment by AshNaz87** [comment]
@moT01 Where are the tests located for this?

**Comment by moT01** [comment]
here are tests that will likely need changing:
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/test/test-challenges.js
and here is a file that may need to be changed:
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/getChallenges.js

**Comment by Sky020** [comment]
Is anyone currently working on this?
Also, is the idea to implement a test that throws an error, if a challenge does not have the language in the extension?

**Comment by Sky020** [comment]
@moT01 I assume we can either close this, or change its description to reflect the move away from `.language.md`?
