### ISSUE TITLE
Footer get disappeared after opening advanced search dropdown in forum page (mobile devices)

### ISSUE THREAD

**Issue by Binu42** [freeCodeCamp/freeCodeCamp#38779]
**Looking forward for reporting a security issue:**
no, not a security issue.

**Describe the bug**
In mobile devices on forum page, it make sense to hide footer after opening advance search dropdown but why to hide footer even after user close advance search dropdown, doesn't make sense, don't even look good, not user friendly and make difficulty in navigations according to user choice.

**To Reproduce**
Steps to reproduce the behavior: (follow it in your mobile)
1. Go to 'https://www.freecodecamp.org/forum/search'
2. Scroll down to see footer, no go up Click on ''Advanced Search"
3. close Advanced search by clicking on dropdown.
4. See error footer will not appear...

**Expected behavior**
Footer should comeback when user will close Advanced search.

**Screenshots**
![20200510_125125](https://user-images.githubusercontent.com/45959932/81493394-a56bc880-92bd-11ea-8945-0b99f2322372.gif)

**Smartphone (please complete the following information):**
common problem in all smartphones.

**Additional context**
if this will get accepted, assigned it to me.

**Comment by ahmadabdolsaheb** [comment]
I believe this the default functionality. 
You would need to dig into discourse's source code. Not sure if it is worth the hassle.
But, let us see other contributor's opinion.

Although if you are interested in looking into the forum's footer, you could start by re-implement the new footer on forum here: #38664

**Comment by TheTechnologyLover** [comment]
Can I try to fix this problem?

**Comment by arfbacem** [comment]
Hi, i think you can fix this issue in the css file, by adding for example :

.footer {
  display: block;
}

**Comment by ahmadabdolsaheb** [comment]
Upon further review I could confirm that this is the default functionality for the footer on the search page.

Here is a similar example: https://community.smartthings.com/search

I don' think it is feasible to roll out a custom solution for this specific feature since doing so would be much more involved than changing the CSS.
