### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by souvikmaity777** [FreeCodeCamp/FreeCodeCamp#3877]
Challenge [Waypoint: Uncomment HTML](http://freecodecamp.com/challenges/waypoint-uncomment-html#?solution=%3C!--%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A--%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<!--
<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>
-->

```

**Comment by bugron** [comment]
@souvikmaity777 thanks for posting this issue!
Please, provide the description of your issue/screenshot and change the title of this issue to be more descriptive, thanks!

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by awesomeaniruddh** [comment]
Closing this. Please feel free to reopen with a description of your issue @souvikmaity777. Thanks!
