### ISSUE TITLE
Fix Project Euler: Problem 70 Typo

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#38776]
**Describe your problem and how to reproduce it:**
Following this post on the forum: https://www.freecodecamp.org/forum/t/project-euler-problem-70-totient-permutation-error-in-description/377577

The instructions should have `1 < n < 107`, be `1 < n < 10**7`.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-70-totient-permutation

First-timers welcome.

**Comment by daksh-goyal** [comment]
Hey, I'm a newbie to open-source. Would like to contribute. Is the issue still open and can I get to fix it?

**Comment by Sky020** [comment]
Hello, @daksh-goyal . Yes, this issue is still open. Absolutely, go ahead and create a PR. Be sure to read the [documentation](https://contribute.freecodecamp.org/#/index) for contributing, if you have not already.

**Comment by daksh-goyal** [comment]
@Sky020 I have just created a pull request fixing the issue. Please guide me on what I could do to contribute further. Thanks :)

**Comment by Sky020** [comment]
@daksh-goyal , thank you, for getting that out. The main thing you can do is have a look at helping on issues with the _help wanted_ label.
