### ISSUE TITLE
JavaScript Algorithms & Data Structures

### ISSUE THREAD

**Issue by Gimhan-minion** [freeCodeCamp/freeCodeCamp#38784]
**Describe your problem and how to reproduce it:**
This code challenge completes only if the given solution is done exactly. Alternative methods doesn't Work. Even the description isn't much clear. Please look into this.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-data-structures/iterate-through-the-keys-of-an-object-with-a-for...in-statement

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome 
* Browser Version: Version 81.0.4044.129 (Official Build) (64-bit)
* Operating System: Ubuntu 20.04

**Comment by snigo** [comment]
What do you mean by alternative methods? Challenge specifically asks to use `for in` loop

**Comment by Gimhan-minion** [comment]
Sorry This worked fine. My bad! I'll close the issue.
