### ISSUE TITLE
Project Euler: Problem 199: Iterative Circle Packing missing picture

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#38783]
**Describe your problem and how to reproduce it:**
`After 3 iterations (pictured), there are 108 gaps and the fraction of the area which is not covered by circles is 0.06790342, rounded to eight decimal places` reads the challenge. The picture, however, is missing

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/project-euler/problem-199-iterative-circle-packing
https://projecteuler.net/problem=199

**Comment by Sky020** [comment]
Where do we host images for use-cases like this?

**Comment by thecodingaviator** [comment]
Amazon cdn afaik

**Comment by scissorsneedfoodtoo** [comment]
Thanks for creating an issue for this @thecodingaviator.

For the current challenges in the coding interview prep section, if there is an image, it was added to our S3 bucket manually and added to the challenge via a PR. Someone will have to create a PR for this, and hopefully improve the formatting, and add additional tests and a solution.
