### ISSUE TITLE
Bonfire: Sum All Odd Fibonacci Numbers freeze

### ISSUE THREAD

**Issue by KwenString** [FreeCodeCamp/FreeCodeCamp#3878]
Challenge [Bonfire: Sum All Odd Fibonacci Numbers]
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.

My code:
```javascript
var sumFibs = function(num) {
  var prev0 = 0;
  var prev1 = 1;
  var fib = 1;
  var sum = 1;
  
  //start from the second fibonacii
  while(fib <= num) {
    sum += fib;
    prev0 = prev1;
    prev1 = fib;
    fib = prev0 + prev1;
  }
  var boundary = fib;
  // star means odd, and o means even, and $ means argument : 'num'
  // * * o * * o * * $ o
  if(boundary % 2 === 0) {
    sum += boundary;
    return sum / 2;
  }
  // * * o * * o * $ *
  if((boundary % 2) && (prev1 % 2)) {
    sum -= prev1;
    return sum / 2 + prev1; 
  }
  //* * o * * o $ *
  if((boundary % 2) && (0 === prev1 % 2)) {
    return sum / 2;
  }
}


```

When I click the button to Run Tests, the `Chrome Dev Tool`  logs a message below
```
Uncaught TypeError: Cannot read property 'length' of null
bonfireExecute @ commonFramework-0ad89d818f.js:1049
(anonymous function) @ commonFramework-0ad89d818f.js:1132
n.event.dispatch @ jquery.js:4430
r.handle @ jquery.js:4116
```

And nothing happened...

**Comment by KwenString** [comment]
Clear chrome://setting/cookies  for freecodecamp cannot help

**Comment by KwenString** [comment]
oh... Great Fire Wall  = == =

**Comment by bugron** [comment]
@KwenString thanks for pointing this out! I've created a PR to fix this. Your code is correct. You'll be able to pass this challenge if you change your comment `//* * o * * o $ *` to `// * * o * * o $ *`.

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by KwenString** [comment]
So it's a RegExp problem, thanks for your suggestion,
for safety consideration, the asterisk symbol shouldn't appears in code comment

**Comment by abhisekp** [comment]
Might be related to #3763

**Comment by bugron** [comment]
Closing this issue as now editor catches this: `Error: SyntaxError: Unfinished multi-line comment`.

**Comment by iamglenbacs** [comment]
i also have this its annoying i cannot run tests

**Comment by joaoeffting** [comment]
this is happening to me yet. Cannot run or reset my code and the browser freeze
