### ISSUE TITLE
Report a bug link to learning curriculums 

### ISSUE THREAD

**Issue by ashwinchandran13** [freeCodeCamp/freeCodeCamp#38790]
**Is your feature request related to a problem? Please describe.**
I found some test outputs where not being accepted even when the produced outputs were right and I wanted to report it but couldn't find a link assigned to tat particular lesson

**Describe the solution you'd like**
A report a bug button in /learn interface within each tests
**Describe alternatives you've considered**
The problem I faced was hugely time consuming to find out what went wrong as it was html/css so the output was right but the test case failed so i couldn't proceed
**Additional context**
### Why the test case failed was an extra space i.e., Expected test case input
` .silver-background {
    background-color: silver; 
  }`
_My Input_
` silver-background {
    background-color: silver ; 
  }`

Thus it was extreamly time consuming procedure to find that

**Comment by ashwinchandran13** [comment]
This commit may solve the issue on that particular lesson but will a feature like report a bug appear in lessons just to ease the hassle of reporting bugs associated to lesson?

**Comment by lasjorg** [comment]
@ashwinchandran13 Why would you put a space after the property value?

In my opinion, it's poor formating and I'm honestly not even sure we should allow it. Sure if the output is correct the challenge is technically solved, but we do have some responsibility to enforce some proper formating.

**Comment by ashwinchandran13** [comment]
@lasjorg Yeah it's poor formatting but it isn't written anywhere that formatting is stictly enforced. Think about beginners man, how will they ever find out about a space that might have came by mistake. Or atleast some indicators would do that. Even if it's a tedious mistake, a report a bug option must be available within lessons if the former is to pushed off.

**Comment by lasjorg** [comment]
We can't teach proper formatting without enforcing it and we can't add tests for every type of improper formatting a camper might do.

If we were to add a bug report feature it would be misused (unintentionally for the most part). It would lead to people opening up bug reports when they have just written incorrect code. That is why we have an ask for help feature on the challenges that will create a forum thread so people can ask for help.

**Comment by ashwinchandran13** [comment]
> We can't teach proper formatting without enforcing it and we can't add tests for every type of improper formatting a camper might do.

Then indicate it somewhere that spacing is **strictly enforced**

> If we were to add a bug report feature it would be misused (unintentionally for the most part). It would lead to people opening up bug reports when they have just written incorrect code. That is why we have an ask for help feature on the challenges that will create a forum thread so people can ask for help.

Can't argue with this as it would definitely would occur

Keep up the good work
