### ISSUE TITLE
[News] article missing code snippets: Learn ES6 The Dope Way Part II: Arrow functions and the ‘this’ keyword

### ISSUE THREAD

**Issue by Ieahleen** [freeCodeCamp/freeCodeCamp#38799]
This article on news is missing a lot of stuff and is not understandable like this:
freecodecamp.org/news/learn-es6-the-dope-way-part-ii-arrow-functions-and-the-this-keyword-381ac7a32881/

there are also some urls that link to medium

I have found the article on medium and it has much more stuff:

https://medium.com/free-code-camp/learn-es6-the-dope-way-part-ii-arrow-functions-and-the-this-keyword-381ac7a32881#.59q9th108

**Comment by tabaddor** [comment]
I can look into this issue. Is there anything else I should know?

**Comment by ptkpyitheim** [comment]
Hmm. So what are you suggesting here? Refactor the way the the original FCC website has it, integrate more explanations in it?

**Comment by Ieahleen** [comment]
these articles where migrated from medium once freeCodeCamp decided to have
its own publishing medium, various articles lost pieces in the migration.
This is one of those.

Ideally it should be restored as it was, with links pointing to
corresponding articles on /news

**Comment by scissorsneedfoodtoo** [comment]
Hi @Ieahleen, thanks for reporting this. I was asked to fix this article and the rest of the series a little while ago. Just seeing the issue now.

All of the articles should have the correct code blocks now, and all the links should be pointing to the /news version of the article. Please let me know if you notice any other articles with these issues.
