### ISSUE TITLE
Replace CodeCademy Angular courses with CodeSchool 'Shaping Up With AngularJS'

### ISSUE THREAD

**Issue by Lumiras** [FreeCodeCamp/freecodecamp#388]
The CodeCademy Angular courses, which are lessons 35-38 on the Waypoints track, are confusing and not great illustrations of Angular's inner workings. Most of the projects included within the lessons are simple checklists with very unclear instructions that throw jargon around that isn't properly explained. It also barely explains what MVC frameworks are, something very important for learning why to use Angular.

I suggest replacing the lessons with the similar (and similarly free) Angular offering from CodeSchool called ['Shaping Up With Angular.js'](https://www.codeschool.com/courses/shaping-up-with-angular-js). This is a much more step-by-step walkthrough of Angular that shows in detail how to use Angular to build a very nice app.

**Comment by AdventureBear** [comment]
not an official reply, but just counterpoint...the original lessons / waypoints in FCC were from code school, and I did all of them and was confused even though I successfully completed them AND wrote a parallel app on my local dev environment. 

Now I'm doing codecademy and it's all making a lot more sense. For me it was simply the 2nd time through that helped, not necessarily that I think codecademy is better.  I think angular is  a tough thing to expect to stick in 4 or 5  1 hour lessons.  

Curious to see what quincy & Nathan et al have to suggest.

**Comment by ltongues** [comment]
AngularJS is a really quirky thing, and I think what help here the most is repetition. Codecademy has got you covered.

**Comment by Lumiras** [comment]
I agree Itongues, but I would say that the CodeSchool courses illustrate how Angular works better. Maybe the better solution is to have us do both? I think Angular is important and complex enough to spent quite a bit of time with it.

**Comment by ltongues** [comment]
Sure. I did both too.

**Comment by terakilobyte** [comment]
We don't recommend CodeSchool anymore for a few reasons. While they do offer some free content, they closed their "Hall Pass" access to some of the other content we recommended so it became a cherry picking task.

We want to reduce the number of accounts campers have to sign up for and manage.

We will take all of the recommendations into consideration. I agree that Angular is a deep topic that deserves more attention.
