### ISSUE TITLE
No code/text in window.

### ISSUE THREAD

**Issue by Thraganux** [FreeCodeCamp/FreeCodeCamp#3880]
Challenge [Waypoint: Uncomment HTML](http://freecodecamp.com/challenges/waypoint-uncomment-html#?solution=) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

When I start this challenge, there is absolutely nothing in the text editor window.  No tags, no comment tags, nothing.

**Comment by awesomeaniruddh** [comment]
Please access the challenge with this URL: http://freecodecamp.com/challenges/waypoint-uncomment-html#?solution=%3C!--%0A%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A--%3E%0A

That should fix it.

**Comment by bugron** [comment]
@Thraganux is this issue resolved for you?

**Comment by ltegman** [comment]
Closing. Please feel free to reopen if that solution did not work for you.

Thanks and happy coding!
