### ISSUE TITLE
Navigation Overhaul

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#38808]
In an effort to simplify and localize navigation we need to replace /news, /forum, and /learn nav items on the right side of the navigation with only one or two items conditionally. Here are the user stories:

- If users are signed in,  they should see two navigation items on the right side of the navigation:
Curriculum (goes to /learn)  and Portfolio( goes to the user's portfolio)

- if users are donating, they should see their picture in gold halo (refer to profile page for logic and styling) instead of the Portfolio item.

- If users are not signed in, they should see a call to action sign in button (refer to /news navigation donate button) instead of the Portfolio item.

Donation page specific:
- All users only see the centered logo with no nav items or search.

**Comment by Upinder123** [comment]
i can help you with the issue if possible assign this to me
