### ISSUE TITLE
[Feature request] Switch on community contribution for youtube channel subtitles

### ISSUE THREAD

**Issue by Ieahleen** [freeCodeCamp/freeCodeCamp#38811]
Here in the contributing guidelines there is adding subtitles as a way to contribute:
https://contribute.freecodecamp.org/#/

But when I went to youtube to do that, there is written that video author has community contributors switched off so it is impossible to contribute.

![image](https://user-images.githubusercontent.com/26656284/81826632-4796e500-9538-11ea-8d8c-54f8ef4584f9.png)

**Comment by raisedadead** [comment]
Thanks for reporting, this sure looks like a bug to me.

**Comment by beaucarnes** [comment]
@leahleen Thanks for pointing this out. It should be fixed now and you should be able to submit a translation now.

**Comment by Ieahleen** [comment]
Yes, now it is possible to contribute, thank you!
