### ISSUE TITLE
Running the local version for non-development purposes

### ISSUE THREAD

**Issue by no95typem** [freeCodeCamp/freeCodeCamp#38821]
Hello.

There is a good guide on how to run the local version. But every time you run "npm run develop", a new build happens. This is a long time, in addition, node.exe uses a lot of CPU resources (about 60% on my PC). I am an absolute noob in nodejs. And in js in general. So I ask for help. Please tell me whether it is possible to save the build and run it? Or reduce the CPU load if I just want to use freecodecamp locally for learning?

**Comment by raisedadead** [comment]
Thanks for reaching out.

The stack is not designed to learn locally at the minute, we do not have any plans to implement or support the same.
