### ISSUE TITLE
Testing Problem

### ISSUE THREAD

**Issue by jashminkaur** [freeCodeCamp/freeCodeCamp#38823]
For Problem Lexicographic permutation I am getting error to submit

Error log is attached, please verify

**Comment by Ieahleen** [comment]
You have not attached anything.

But please, before opening an issue, use the Ask for Help button in the challenge to open a topic in the forum with your code included.

**Comment by Sky020** [comment]
Hello, jashminkaur.

Ditto to what Ieahleen has said. Here is a link to the forum: https://www.freecodecamp.org/forum
When opening an issue/topic, please include as much _useful_ information as possible.

I am closing this issue, for now. Thank you
