### ISSUE TITLE
Several Major Issues: Challenges Not Passing, Dependencies Out of Date, More...

### ISSUE THREAD

**Issue by krisb1220** [freeCodeCamp/freeCodeCamp#38837]
**Describe your problem and how to reproduce it:**

# Quality Assurance and Testing with Chai - Run Functional Tests using a Headless Browser:

Link: https://www.freecodecamp.org/learn/information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-using-a-headless-browser

## Issue 1: Tests not passing (***Major***)
The Headless Browser challenges are not passing. I tried replacing my code with the `Solution` on the `Hint` page, and it's not working. For some reason, however, "You should assert that the headless browser request succeeded." is passing.  All 29 tests are passing. 

### Relevant Information
My logs when I run the test: https://gist.github.com/krisb1220/a76a7db2ae66adf3f60ba5caa9bcb097#file-log-txt

My 2_functional_tests.js file: https://gist.github.com/krisb1220/a76a7db2ae66adf3f60ba5caa9bcb097#file-2_functional_tests-js

My project: https://glitch.com/edit/#!/krisb-fcc-information-quality

## Issue 2: Outdated Packages (Minor)
Packages are out of date

# Quality Assurance and Testing with Chai - Run Functional Tests using a Headless Browser II:

Link: 
https://www.freecodecamp.org/learn/information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-using-a-headless-browser-ii

## Issue 1: Tests not passing (***Major***)
Same as above; except no tests are passing, even though all tests are passing.

### Relevant information: 
SEE ABOVE -- SAME AS ABOVE. 

# Exercise Tracker Project

## Issue 1: Outdated Mongoose/Mongo (***Major***)
Mongoose is outdated. It doesn't allow you to connect using the normal connection method as taught in the cirriculum. The `package.json` needs to be changed to the following: 
https://github.com/krisb1220/boilerplate-project-exercisetracker/blob/glitch/package.json

I've added a PR to the boilerplate repo that changes the Package.json and fixes this issue. 
https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/pull/24

## Issue 2: Outdated Node Version (***Major***)
The Node version is ***heavily*** outdated. It's running Node 6. `async` and `await` keywords are not able to be used - along with all other ES6 features. I've created a Package.json that fixes the issue. I've also gone ahead and created an entirely new Glitch template that fixes the issue. 

## Issue 3: Unclear Instructions 1 (Minor)
Although this isn't a huge issue, it's a requirement that the "duration" variable from response after posting to `/api/exercise/add` is required to be an integer. 

## Issue 4: Unclear instructions 2 (Minor)

![image](https://user-images.githubusercontent.com/22512957/82134111-116c9600-97c2-11ea-923d-52cd26c464cc.png)

The third requirement states that "User object needs to be returned with the added exercise". This is not the case. From the instructions, it appears that it's required to return the **full** user object as you would on the `/api/exercise/log` page. What needs to be returned is a summary object with the users `username`, their `_id`,  as well as the exercise data. The returned object should look like the below: 

```JSON
{
"username":"krisb1220",
"_id":"5eba18ae93e4aa5b2434991f",
"description":"coded",
"duration":20,
"date":"Thu May 14 2020"
}
```

## Issue 3: Code breaks server.js (***Major***)
Also, on the Exercise Tracker project, the following code breaks the server if users do not place their endpoints before it. See my pull request on the boilerplate repo, as I've clarified this with comments: 

```javascript

// Not found middleware
app.use((req, res, next) => {
  return next({status: 404, message: 'not found'})
})

// Error Handling middleware
app.use((err, req, res, next) => {
  let errCode, errMessage

  if (err.errors) {
    // mongoose validation error
    errCode = 400 // bad request
    const keys = Object.keys(err.errors)
    // report the first validation error
    errMessage = err.errors[keys[0]].message
  } else {
    // generic or custom error
    errCode = err.status || 500
    errMessage = err.message || 'Internal Server Error'
  }
  res.status(errCode).type('txt')
    .send(errMessage)
})

```

## Fixes 
Repo: https://github.com/krisb1220/boilerplate-project-exercisetracker/tree/glitch (NOT `MASTER `BRANCH, `GLITCH` BRANCH) --- **Pull request on the original repo has been submitted**

Project Page: https://glitch.com/~freecodecamp-exercise-tracker-project

Project Code Page: https://glitch.com/edit/#!/freecodecamp-exercise-tracker-project

# Advanced Node and Express - Implement the Serialization of a Passport User
https://www.freecodecamp.org/learn/information-security-and-quality-assurance/advanced-node-and-express/implement-the-serialization-of-a-passport-user

# Issue 1: Deprecated Connection Method (***Major***)
The MongoDB connection method shown in the instructions has been deprecated. The challenge doesn't currently pass using the non-deprecated option. I simply used the non-deprecated option to pass the challenge and changed it after, but some users may not realize this is an option.

### Proper Connection Method:
```javascript
const MongoClient = require('mongodb').MongoClient;
const MongoOptions = {useUnifiedTopology: true, useNewUrlParser:true};
const Client = new MongoClient(process.env.DATABASE, MongoOptions);

Client.connect((err, db)=>{
  if(err) console.error(err);
  else console.log("connected to databse");
})
```

### Method Shown  (Deprecated, soon to be removed)

```javascript
mongo.connect(process.env.DATABASE, (err, db) => {
  if(err) {
    console.log('Database error: ' + err);
  } else {
    console.log('Successful database connection');

    //serialization and app.listen
  }
});
```

# Advanced Node and Express - Create New Middleware (MAJOR) [Edited]

## Issue 1: Challenge only passes if you change the index.pug template's <title> attribute to `Home Page`. Thanks to @magnus195 for pointing this out to me :) 

**Tell us about your browser and operating system:**

* Browser Name: Chrome
* Browser Version: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![image](https://user-images.githubusercontent.com/22512957/82133902-314e8a80-97bf-11ea-8d7c-0e3920da8a93.png)

![image](https://user-images.githubusercontent.com/22512957/82133840-77571e80-97be-11ea-89ef-05f30bc2b474.png)

![image](https://user-images.githubusercontent.com/22512957/82133904-37dd0200-97bf-11ea-8d23-ef4c3bc959ea.png)

**Comment by krisb1220** [comment]
Also, on the Exercise Tracker project, the following code breaks the server: 

```javascript

// Not found middleware
app.use((req, res, next) => {
  return next({status: 404, message: 'not found'})
})

// Error Handling middleware
app.use((err, req, res, next) => {
  let errCode, errMessage

  if (err.errors) {
    // mongoose validation error
    errCode = 400 // bad request
    const keys = Object.keys(err.errors)
    // report the first validation error
    errMessage = err.errors[keys[0]].message
  } else {
    // generic or custom error
    errCode = err.status || 500
    errMessage = err.message || 'Internal Server Error'
  }
  res.status(errCode).type('txt')
    .send(errMessage)
})

```

**Comment by krisb1220** [comment]
#

**Comment by magnus195** [comment]
Just had the issue with my middleware not passing at advanced Node. Had to add "Home page" to the template :|

**Comment by neenjaw** [comment]
Just came here to write this issue up as well.  This a good summary of the issues I have found with the exercises on glitch, so much that I decided to write them locally and use `ngrok` to tunnel them externally to be tested.

But to reiterate the biggest points that need some touching up:
- outdated node version (glitch supports to ver. 12.0.0), node package versions
- outdated mongo/mongoose connection conventions that don't align with the mongo atlas URI
  - lots of remnants of the old mlab connection details
- each boilerplate has lots of extra boilerplate
  - an example is the error handling middleware in the exercise tracker boilerplate.
- inconsistent boiler plate
  - things are defined in several ways, while this may convey how unopinionated expressjs is, it may be detrimental to students developing a style from reading examples
- microservice problems are generally poorly specified for return values and format.
  - exercise tracker is by far the most egregious example of this
    - my issue here <https://www.freecodecamp.org/forum/t/exercise-tracker-4th-user-story/397475>

I am willing to help with these things if it can be triaged and pointed out where best to contribute by a more senior contributor

**Comment by neenjaw** [comment]
Just to increase visibility, #37590 describes challenges with this exercise from another perspective

**Comment by rogfut** [comment]
+1 for Exercise Tracker Project having outdated package versions for mongoose and mongodb.  Just today I was copying code blocks from the previous project, URL shortener, wondering why my mongoose save() method was failing to save the document.

**Comment by mwinser** [comment]
Hello! First time posting, sorry if this is the wrong place.

In regards to the first issues mentioned for **Quality Assurance and Testing with Chai**: 

The challenge instructions, the Repl.it boilerplate comment instructions and the test failure messages are inconsistent to what the challenge submission test is actually asserting.

**Run Functional Tests using a Headless Browser** challenge and Repl.it instructions and the test failure messages indicate to use `"Cristoforo"` and `"Colombo"`, but the [the test assertions](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/06-quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-using-a-headless-browser.md). require `"Marco"` and `"Polo"`, respectively.

**Run Functional Tests using a Headless Browser II** Repl.it instructions and the test failure messages indicate to use `"Amerigo"` and `"Vespucci"`, but  the challenge instructions and [the test assertions](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/06-quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-using-a-headless-browser-ii.md) require `"Cristoforo"` and `"Colombo"`, respectively.


I personally wasn't able to pass these tests, until I checked the challenge testing repositories.

Hope this helps!

**Headless I:**
![Headless I](https://user-images.githubusercontent.com/74273216/100522282-610f1f80-315e-11eb-81c4-154aa87906dc.png)

**Headless II:**
![Headless II](https://user-images.githubusercontent.com/74273216/100522298-73895900-315e-11eb-8996-2849be348873.png)

**Comment by nhcarrigan** [comment]
Heya @mwinser - we are working on a PR currently to fix those concerns. 🙂

**Comment by scissorsneedfoodtoo** [comment]
Thanks again @krisb1220 for all of these details and everyone else for your input.

Some general notes:
- We decided to remove Mongo, Mongoose, some other dependencies, and the Node version from the boilerplates and allow learners to install them as they work on the projects. This will allow for some extra practice with the command line and setup, and prevent us from having to review and merge package / Node updates.
- The endpoints for several of the API challenges, including the Exercise Tracker project, were recently updated. Some of the test text has also been updated since this issue was opened.

Here's a checklist so we can keep track of everything that still need further investigation or a fix:

### Quality Assurance and Testing with Chai

#### Run Functional Tests using a Headless Browser and Run Functional Tests using a Headless Browser II
- [x] Tests not passing (https://github.com/freeCodeCamp/freeCodeCamp/pull/40330)
- [ ] Packages outdated (will be fixed in https://github.com/freeCodeCamp/freeCodeCamp/pull/43065 and https://github.com/freeCodeCamp/boilerplate-mochachai/pull/42)

###  Exercise Tracker Project
- [x] Outdated Mongoose / Mongo versions (https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/pull/42)
- [x] Outdated Node version (https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/pull/45)
- [ ] Unclear instructions for user story 4 and / or 5 (Needs further investigation)
- [ ] Unclear instructions for user story 4 (Needs further investigation)
- [x] Code breaks `server.js` (Boilerplate was simplified in https://github.com/freeCodeCamp/boilerplate-project-exercisetracker/pull/42)

### Advanced Node and Express

#### Implement the Serialization of a Passport User
- [x] Deprecated connection method (https://github.com/freeCodeCamp/boilerplate-advancednode/pull/11)

#### Create New Middleware
- [x] Challenge only passes if you change the `index.pug` template's `<title>` attribute to `Home Page` (https://github.com/freeCodeCamp/boilerplate-advancednode/pull/11)

**Comment by scissorsneedfoodtoo** [comment]
All of the points mentioned above, along with some others, should be fixed with the PRs in my last comment.

Thanks again everyone for your valuable feedback, and for helping us improve the backend curriculum.
