### ISSUE TITLE
Finders Keepers and the "Truth Test"

### ISSUE THREAD

**Issue by joshisplutar** [freeCodeCamp/freeCodeCamp#38832]
**Describe your problem and how to reproduce it:**
The instructions are unclear to a new developer regarding the term "truth test". As somebody still learning I was stuck trying to figure out what a truth test was until a mentor revealed to me that it was not some sort of programming term at all but just what the second argument was being referred to as. I propose that the examples of the function that is the second argument be renamed to truthTest instead of num.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/finders-keepers

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by ojeytonwilliams** [comment]
Thanks @joshisplutar, you're right, it's not particularly clear.  What do you think about the following wording?

> Create a function that looks through an array, `arr`, and returns the first element in the array that passes a 'truth test'.  That is to say, given an element `x` the 'truth test' is passed if `func(x)` is `true`. If no element passes the test, return `undefined`.

Technically `func(x)` only has to be truthy, not true, but we don't introduce that concept until later in the curriculum.

**Comment by joshisplutar** [comment]
I think that's a great improvement!

**Comment by ojeytonwilliams** [comment]
Okay, cool.  I don't think we need to do more than that, so if a new contributor wants to help, I think it should be reasonably clear.

@joshisplutar thanks again for letting us know about this.

**Comment by omer727** [comment]
I'm on it (first timer 😊)
