### ISSUE TITLE
Bonfire: Falsy Bouncer

### ISSUE THREAD

**Issue by yielder** [FreeCodeCamp/FreeCodeCamp#3883]
Challenge [Bonfire: Falsy Bouncer](http://freecodecamp.com/challenges/bonfire-falsy-bouncer#?solution=function%20bouncer(arr)%20%7B%0A%20%20return%20arr.filter(isTruthy)%3B%0A%7D%0A%0Afunction%20isTruthy(a)%20%7B%0A%20%20arr%20%3D%20%5Bfalse%2C%20null%2C%200%2C%20%22%22%2C%20undefined%2C%20NaN%5D%3B%0A%20%20for%20(i%20%3D%200%3B%20i%20%3C%20arr.length%3B%20i%2B%2B)%20%7B%0A%20%20%20%20if%20(arr%5Bi%5D%20%3D%3D%3D%20a)%20return%20false%3B%0A%20%20%7D%0A%20%20return%20true%3B%0A%7D%0A%0Abouncer(%5Bfalse%2C%20null%2C%200%2C%20NaN%2C%20undefined%2C%20%22%22%5D)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function bouncer(arr) {
  return arr.filter(isTruthy);
}

function isTruthy(a) {
  arr = [false, null, 0, "", undefined, NaN];
  for (i = 0; i < arr.length; i++) {
    if (arr[i] === a) return false;
  }
  return true;
}

bouncer([false, null, 0, NaN, undefined, ""]);

```

**Comment by bugron** [comment]
@yielder thanks for posting this issue!
The problem is that `NaN === NaN` returns `false`. To check if the value is `NaN` use [isNaN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN).

>***
>Please review the [**Guidelines for Contributing**](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md), thank you!.
>***

**Comment by yielder** [comment]
@bugron Thanks for your answer. I'll notice that next time.
