### ISSUE TITLE
Word several is repeated in create portfolio zipline

### ISSUE THREAD

**Issue by tdugger** [FreeCodeCamp/FreeCodeCamp#3884]
In step 11 of the "Build a Personal Portfolio Webpage" the word "several" is repeated.

**Comment by tdugger** [comment]
duplicate of 3885.  I didn't know the pull request would create an issue and I guess it wouldn't have if I had put "Closes 3884" in the description of the pull request.  Sorry.

**Comment by abhisekp** [comment]
Put a hash symbol before the PR number to make a link. #3885

**Comment by bugron** [comment]
Closing this issue as https://github.com/FreeCodeCamp/FreeCodeCamp/pull/3885 is merged.
