### ISSUE TITLE
Nginx config

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#38841]
Since `redirect` results in an extra round trip, could we improve performance by using the following? 

```
rewrite ^ https://www.freecodecamp.org$request_uri permanent;
```

instead of 

```
return 301 https://www.freecodecamp.org$request_uri;
```

inside the subdomains redirection section of the Nginx config.

Also, the some static resources (like fonts and icons) have a relatively short `max-age` (4 hours), but have cache busting arguments.  Assuming the arguments are generated correctly, I would have thought these could be longer.  I'm not sure where these get set, though.

**Comment by raisedadead** [comment]
301 are meant for permanent changes. The perfo gain is negligible considering the traffic patterns we get and Cloudflare does do the heavy lifting for caching.
