### ISSUE TITLE
Serbian Translation

### ISSUE THREAD

**Issue by b0c0de** [freeCodeCamp/freeCodeCamp#38843]
**Is your feature request related to a problem? Please describe.**
It is not an issue but it could help a lot of people who speak ex-Yugoslavian languages pass through tests and bring lots more members. 

**Describe the solution you'd like**
Translate all the files to ensure everybody is aware what is going on. 

**Describe alternatives you've considered**
N/A

**Additional context**
Please, advise of the steps what could be done.

**Comment by raisedadead** [comment]
Hi.

Thanks for your interest and reporting. Please see: https://contribute.freecodecamp.org/#/index?id=can-i-translate-freecodecamp39s-curriculum

While we are interested, we do not have any timelines when we will be able to make it available in the language of your choice.
