### ISSUE TITLE
I Found 300+ problems security issues in codebase

### ISSUE THREAD

**Issue by viveksharmaui** [freeCodeCamp/freeCodeCamp#38845]
**Describe your problem and how to reproduce it:**
I added eslint security within project and found more than 300 problems mostly security problem in codebase.

**Add a Link to the page with the problem:**
PR: #38844

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot from 2020-05-19 01-44-28](https://user-images.githubusercontent.com/28563357/82257916-50d9e480-9972-11ea-98b3-0c8095cd35ec.png)

**Comment by viveksharmaui** [comment]
After adding Eslint Security Plugin I find out a lot of bugs in codebase these all warnings are related to security which we should fix as soon as possible I have also attached the PR we need to fix these warnings.

**Comment by raisedadead** [comment]
Thanks for your report. We recommend reaching out on the security channels for issues like this.

Can you be more succinct on the issues? The screenshot and your reports is quite vague?

**Comment by viveksharmaui** [comment]
I have added a Pull Request for this.

**Comment by viveksharmaui** [comment]
These issue are related to security best practices they are simply eslint security rules i think we should work on that, This will improve codebase and follows best practices.

**Comment by raisedadead** [comment]
We are aware of the PR. Can you expand on the specifics of the errors that this plugin catches along with a sample fix? 

In the current state of the PR, all it has are cryptic warnings. Please note we are interested in adopting the practices, but not before we understand what these are.

I recommend you add some demo commits to the PR, that shows the errors (we are probably not keen on the warnings, but it may change) followed by a sample fix.

**Comment by viveksharmaui** [comment]
Sure! I will add a commit for fix within that PR I will get back to you.

**Comment by nhcarrigan** [comment]
Heya @viveksharmaui - are you able to provide a status update? It looks like raisedadead has requested additional information for the specifics of this functionality. Additionally, the PR #38844 you have opened appears to be in need of a rebase against our master branch. 🙂
