### ISSUE TITLE
Pathnames are case sensitive

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#38850]
`/learn` is not the same as `/LEARN` or `/LeArN`. The second two take you to user profiles, I believe they are the same user profiles. Just starting an issue about it, I haven't looked into it at all.

**Comment by jordanliu** [comment]
Steps to reproduce, please?

**Comment by tabaddor** [comment]
Should pathnames be case sensitive? Is what you are saying that all routes /learn, /LEARN, /LeArN, should all take you to the same path?

**Comment by BoCode84** [comment]
As per what I was able to find on StackOverflow, Case-sensitive URLs are a web-standard and GitHub does not allow any changes so, yes, there will be different web addresses if you type it differently.

**Comment by ojeytonwilliams** [comment]
While using different cases does change the request, it's up to the server which page it sends back.  For example, this issue can be reached by going to `https://github.com/freecodecamp/freecodecamp/issues/38850` as well as `https://github.com/FREECODECAMP/freecodecamp/issues/38850`.

The problem is that, as Tom said, someone has a variant of /LEARN as their username. They would need to be told if we were going to change it.  I think this has happened before, though, when someone had 404 as their username.

**Comment by thecodingaviator** [comment]
I totally agree that this is a problem in progress, but we don't know when we might add a link or something that clashes with another user in the future. I think changing the format to `freecodecamp.org/u/username` is a way to future proof against these problems.
cc: @raisedadead

**Comment by ojeytonwilliams** [comment]
@thecodingaviator if we can do that, it would simplify the client code and cut down on the number of unavoidable 404s.  Mrugesh will know if there's a reason not to beyond "it'll be a complicated rewrite".

**Comment by raisedadead** [comment]
We will not be using `/u/username` pattern, there are a lot of backlinks that will be broken.

We also reserve the right to claim a path for our use as needed. Its on the user's part to NOT choose that is something unconventional. 

Practically why would you choose a username 'LEARN'? 

We have claimed paths in the past, by sending a notification to users for the change.

That said, this is a valid issue, we should add a middleware to make paths case-insentive.

**Comment by ruchivora** [comment]
I think solution to this problem can be , before hitting the end point the path name should be converted to appropriate format . i.e if the path should always be in lower case then before hitting the end point convert the path name to lower case and then hit the corresponding end point

**Comment by ojeytonwilliams** [comment]
Hi @ruchivora that sounds reasonable. If you've got time, a PR would be very welcome.

**Comment by Easyvipin** [comment]
Yes ,The path name is case sensitive ,although it should work fine in localhost , but if you deploy to some hosting site ,it will generate an internal server error.

**Comment by godslayer201** [comment]
Is this issue still requiring help? Would like to work on this.

**Comment by ojeytonwilliams** [comment]
Hey @godslayer201, yes, this is still open. If you want to work on it, that would be great.

**Comment by moT01** [comment]
This is possibly a duplicate of, or closely related to: https://github.com/freeCodeCamp/freeCodeCamp/issues/35525
