### ISSUE TITLE
Broken Link in 'Make a Person' Intermediate Algorithm Challenge

### ISSUE THREAD

**Issue by virenb** [freeCodeCamp/freeCodeCamp#38859]
**Problem:**
The Get Help -> Get a Hint link is broken for the Intermediate Algorithm Challenge, "Make a Person."  I looked through the forums and it does not look like a guide is there for this challenge. 
The button currently directs the user to https://www.freecodecamp.org/forum/t/16020

**Link(s):**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/make-a-person

**Browser and operating system:**
* Browser Name: Mozilla Firefox
* Browser Version: 76.0.1 
* Operating System: macOS Catalina (version 10.15.4)

Also, tried it on Google Chrome (version 81.0.4044.138)

**Screenshot:**
![Screen Shot 2020-05-20 at 2 50 14 PM](https://user-images.githubusercontent.com/10731287/82485320-cc4ea980-9aca-11ea-8d6c-47a54c5c4822.png)

**Comment by JordanMooree** [comment]
Hello, is anyone working on this? I would like to work on this issue

**Comment by Sky020** [comment]
Thank you, for pointing this out.

@RandellDawson , this Guide post went with the system delete. Is a new one in the pipeline?

**Comment by raisedadead** [comment]
I reverted this. Mods need to be careful when approving deletions when users flags things.
