### ISSUE TITLE
docs: add cypress tests documentaton to contribution guides

### ISSUE THREAD

**Issue by luqven** [freeCodeCamp/freeCodeCamp#38853]
**Is your feature request related to a problem? Please describe.**

Had trouble getting up to speed with [Cypress](https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell) since there's currently no documentation on for how it's implemented in the code base.

**Describe the solution you'd like**

I suggest we create a documentation page for Cypress that outlines how to:

- 1) run the tests locally and 
- 2) create end-to-end tests using Cypress whenever adding to the code base.

This section could potentially be under the ["Open a pull request"](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request) section of "Code Contribution Guides".

**Describe alternatives you've considered**

A a link to the docs already on [cypress.io](https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell) could be added to the [introduction](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=how-to-open-a-pull-request-pr), but in my opinion this would probably be insufficient.

**Additional context**

- the PR where I created a Cypress test: #38806 
- Cypress.io [docs](https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell)

_ps: I'd love to give a PR for this a stab if it's decided it's needed._

**Comment by ojeytonwilliams** [comment]
Sounds good to me.  I think it would be best to focus on freeCodeCamp specific issues, rather than diving too deep into how Cypress tests work.  The Cypress docs cover that, after all.

> ps: I'd love to give a PR for this a stab if it's decided it's needed.

Great, thanks!  Since you've just looked at this, that makes perfect sense.

**Comment by luqven** [comment]
Picking this up again. Sorry the the multi-month delay 😬, life took some crazy turns.

**Comment by ojeytonwilliams** [comment]
Hey @luqven no apology necessary, it's always nice to see someone come back.
