### ISSUE TITLE
Data Visualization Projects - Visualize Data with a Heat Map

### ISSUE THREAD

**Issue by ltdan681** [freeCodeCamp/freeCodeCamp#38857]
This project has two user stories that are listed as #16 

![heat-map-user-stories](https://user-images.githubusercontent.com/46683727/82468623-069b5500-9a91-11ea-9baa-d938c1b1ef80.png)

**Comment by Sky020** [comment]
Thank you, for spotting this. This is an easy fix; Here is the culprit file:
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/04-data-visualization/data-visualization-projects/visualize-data-with-a-heat-map.english.md

**Comment by rajat641** [comment]
hi @Sky020 , Can I go ahead with this?

**Comment by Sky020** [comment]
Hello @rajat641 , As you are considered a _Contributor_ (made at least 1 contribution), I suggest you leave this open to _first timers_. Thank you, for your understanding.

**Comment by b0c0de** [comment]
Hey @Sky020 
I figured I'll mention here. I was not aware that we could not do it ourselves. 
I apologize for the inconvenience.

**Comment by vardhinipawar** [comment]
Hi can I work on this? I am a first-timer

**Comment by rajat641** [comment]
Hi @vardhinipawar ,

I think this issue has already been picked up. Feel free to claim an issue with label `first timers`.

**Comment by ltdan681** [comment]
I think that I sent it through but I'm unsure if I did it correctly. It might still need someone with Write access to accept the edits?

**Comment by vardhinipawar** [comment]
Sure I can do that

**Comment by vardhinipawar** [comment]
I can check it for you

**Comment by ltdan681** [comment]
Hi @Sky020 I'm unsure if I am doing this correctly but I have a pending pull request. It needs approval to be submitted.

**Comment by Sky020** [comment]
Hello @ltdan681 , sorry, things are quite busy. You have done what you needed to, and, as it stands, your PR is approved.

Thank you, for your patience.

**Comment by ltdan681** [comment]
@Sky020 Ok thanks for the heads up!
