### ISSUE TITLE
'Let’s Learn JavaScript Closures' article doesn't show the example codes

### ISSUE THREAD

**Issue by namitry** [freeCodeCamp/freeCodeCamp#38862]
**Describe your problem and how to reproduce it:**
The webpage lacks example codes.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/news/lets-learn-javascript-closures-66feb44f6a44/

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by raisedadead** [comment]
Thanks for reporting. 

Could you also send an email to team@freecodecamp.org? I have pinged our team, but we could use some detailed feedback from you on the article via email which will get across directly to the editorial team.

Thanks.

**Comment by namitry** [comment]
Hello,

I have informed that I cannot see the codes on this article, and was said
to send an email to you.
The article is this.
https://www.freecodecamp.org/news/lets-learn-javascript-closures-66feb44f6a44/

I appreciate your help.

Yuta

**Comment by namitry** [comment]
Hi Yuta,

Thanks for letting us know. We will fix this article real quick :)

- Quincy Larson

The teacher who founded https://www.freecodecamp.org
I share useful things on Twitter at https://www.twitter.com/ossia

**Comment by namitry** [comment]
Hi Quincy,

I saw the updated article, thank you for your quick work.
Now it seems very easy to grasp since I don't have to utilize my
imagination for imaginary codes...lol
I appreciate it!

Yuta
