### ISSUE TITLE
Solution required for project ?

### ISSUE THREAD

**Issue by b0c0de** [freeCodeCamp/freeCodeCamp#38868]
**Describe your problem and how to reproduce it:**
When we look at the file, it says "solution required" for projects that are required to be done for ie. Responsive Web Design certificate. Is there really a need for solution when in reality, we are just submittting our solution and our work?

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-tribute-page.english.md

**Tell us about your browser and operating system:**
* Browser Name: Mozilla 
* Browser Version: 5.0
* Operating System: Microsoft Windows 7

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by raisedadead** [comment]
That's just boilerplate code which does note reach the views. We need them in certain challenges for our CI tests.
