### ISSUE TITLE
Main anchor element missing href for 'FCC: Cash Register', relevant links section

### ISSUE THREAD

**Issue by tannercd** [freeCodeCamp/freeCodeCamp#38860]
**Describe the bug**
The forum's [challenge guide](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-cash-register/16012) for the last JS project 'Cash Register' contains a broken link inside 'Relevant Links' underneath the problem explanation. It seems that the anchor element with innerText "Data Structure Array" is missing its `href=""` property. 

I tracked down the correct MDN link and it should be, [Data Structure Array MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array)

**To Reproduce**
1. Go to [FCC Cash Register - Challenge Guide](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-cash-register/16012)
2. Scroll down to 'Relevant Links' (which is right under problem explanation)
3. Click the only link inside "Data Structure Array"
4. See the error: its a broken link that has no action upon click. (its missing an href property)

**Expected behavior**
The expected behavior of the anchor element within the Relevant links section should redirect me to the proper page upon click. 

**Screenshots**
<img width="379" alt="Screen Shot 2020-05-20 at 3 57 31 PM" src="https://user-images.githubusercontent.com/48612525/82505583-f300e600-9ab2-11ea-9cd4-d9e0a9cbadeb.png">

<img width="544" alt="Screen Shot 2020-05-20 at 3 57 48 PM" src="https://user-images.githubusercontent.com/48612525/82505497-bfbe5700-9ab2-11ea-800b-e7e58abf2650.png">

**Desktop :**
 - OS: Mac OS
 - Browser: chrome
 - Version: Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by Sky020** [comment]
Thank you, for pointing this out to us. I have changed the guide to include a link to this _News_ article: https://www.freecodecamp.org/news/data-structures-101-arrays-a-visual-introduction-for-beginners-7f013bcc355a/
