### ISSUE TITLE
Forum avatar list should not wrap.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#38871]
The avatar list should include 5 items in a row without wrapping:

![Latest_Career_Advice_topics_-_The_freeCodeCamp_Forum](https://user-images.githubusercontent.com/4591597/82629760-5301a480-9bf9-11ea-82d6-f3701e63bc73.png)

possible solution:
set 
.topic-list .posters {
    width: 165px;
}

**Comment by Sky020** [comment]
Potentially:
```
.topic-list td.posters {
    height: -webkit-fill-available;
    overflow: hidden;
    display: flex;
    justify-content: center;
    align-items: center;
}
```
`-webkit-fill-available` appears to work for Chromium-based browsers, but needs a fall-back for Firefox for the meantime.

**Comment by JapneetSingh5** [comment]
Can I work on this one? is this still up for grabs?

**Comment by ahmadabdolsaheb** [comment]
@JapneetSingh5, I will handle it today with other forum related issues.

**Comment by JapneetSingh5** [comment]
okay cool

**Comment by JapneetSingh5** [comment]
Okay!

**Comment by Sky020** [comment]
Hey @ahmadabdolsaheb , I cannot explain this: 
![image](https://user-images.githubusercontent.com/51722130/83953731-8fa8df00-a83a-11ea-9e01-ce2b4d7d60a2.png)

It appears to happen to random lists, but I have found at least 5 in 60 topics.
