### ISSUE TITLE
Anchor element missing href attribute in relevant links

### ISSUE THREAD

**Issue by tannercd** [freeCodeCamp/freeCodeCamp#38874]
**Describe the bug**
Just another anchor element needing to be updated within [Search and Replace Challenge Guide](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-search-and-replace/16045) solution five. 

**To Reproduce**
1. Go to [Search and Replace Challenge Guide](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-search-and-replace/16045)
2. Click on Solution number 5
3. Scroll down to Relevant links
4. See error upon inspection and click at the fourth list item 'String.length' 

**Expected behavior**
Anchor element should have href attribute to allow the hyperlink to function as expected.

**Screenshots**
<img width="693" alt="Screen Shot 2020-05-22 at 12 10 43 PM" src="https://user-images.githubusercontent.com/48612525/82701758-9b36bc00-9c25-11ea-839d-aa9ef826e892.png">

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser: chrome
 - Version: Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by Sky020** [comment]
Thank you, for pointing this out. I have edited the post.
