### ISSUE TITLE
News sub headlines are covered by navbar

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#38870]
When a news article is navigated to using an id, the fixed navbar covers that id.

For example: when visiting the "Visual Studio Code" id of this article
https://www.freecodecamp.org/news/getting-started-with-react-a-modern-project-based-guide-for-beginners-including-hooks-2/#visualstudiocode

The sub headline "visual studio code" with the id `visualstudiocode` is covered by the navigation and users should scroll to bring it into view.

possible solution
https://stackoverflow.com/questions/15676399/prevent-fixed-navigation-bar-from-covering-texts-titles-after-clicking-a-link-or

**Comment by psjishnu** [comment]
@ahmadabdolsaheb  Is the code that needs to be modified is in repo https://github.com/freeCodeCamp/freeCodeCamp ?

**Comment by AshNaz87** [comment]
Ah, yes.

Think there is a CSS hack to this type of problem. Not sure if that's desired though

**Comment by Peppece** [comment]
Did someone claim this? I'd be happy to

**Comment by ahmadabdolsaheb** [comment]
@psjishnu, the code is here. https://github.com/freeCodeCamp/news-theme

Please go ahead 👍. No assignment is necessary as described in our [contribution docs](https://contribute.freecodecamp.org/#/index?id=where-do-i-start-if-i-want-to-work-on-an-issue). The first comprehensive PR will be considered for review.
