### ISSUE TITLE
Formating issue when printing the certificate

### ISSUE THREAD

**Issue by rajat29gupta** [freeCodeCamp/freeCodeCamp#38877]
Describe the bug
I found formatting issue when I was printing the certificate using Google Chrome

To Reproduce
- Visit the link in incognito mode (Ctrl+Shift+N): https://www.freecodecamp.org/certification/fcc865bea72-a1c9-4112-b30b-ef8424d2deef/responsive-web-design
- Print the certificate using Google Chrome using Ctrl+P.

Expected behavior
- The certificate should be format properly 

Screenshots
![DRTqTN6y](https://user-images.githubusercontent.com/34648003/82721435-b7e0fb80-9cda-11ea-9dcd-e2c8c88dcd4a.png)
![WaQ9_Xnj](https://user-images.githubusercontent.com/34648003/82721439-bca5af80-9cda-11ea-8791-2fdbe73fd8ae.jpg)

Desktop 
OS: Window 10
Browser: chrome
Version: 83.0.4103.61 (Official Build) (64-bit)

**Comment by raisedadead** [comment]
The certificate is meant to be digitally verifiable by design. If you insist on getting printed copy we recommend capture a screenshot and print the image instead.
