### ISSUE TITLE
Anchor element missing href inside relevant links

### ISSUE THREAD

**Issue by tannercd** [freeCodeCamp/freeCodeCamp#38873]
**Describe the bug**
The link 'JS Regex Resources' under Relevant links for the [Pig Latin challenge guide](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-pig-latin/16039) is missing its href property. The issue is right underneath the code explanation for solution number 2 and number 3 as the first list item in relevant links. 

I found the same hyperlink in another challenge guide. I think it should be linking to [MDN Regular Expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)

**To Reproduce**
1. Go to [Pig Latin Challenge Guide](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-pig-latin/16039)
2. Click on Solution number 2 and 3
3. Scroll down to the code explanation and relevant links for solutions 2 and 3.
4. See error in the first list element item 'JS Regex Resource'. Notice upon click event it does not have action.

**Expected behavior**
The anchor element should have an href attribute specified so when the element is clicked it redirects us to the link provided.

**Screenshots**
<img width="688" alt="Screen Shot 2020-05-22 at 12 54 16 AM" src="https://user-images.githubusercontent.com/48612525/82644831-cf2ec480-9bc6-11ea-8262-5f610e19c85a.png">

**Desktop:**
 - OS: Mac OS 
 - Browser: Google Chrome
 - Version: Version 81.0.4044.138

**Comment by Sky020** [comment]
Thank you, for pointing this out, the links have been updated.
