### ISSUE TITLE
Up and down arrow key don't work after typing JavaScript reserved words

### ISSUE THREAD

**Issue by Berkeley-Reject** [freeCodeCamp/freeCodeCamp#38880]
**Describe the bug**
Up and down arrow key don't work after typing JavaScript reserved words

**To Reproduce**
1. Navigate to a challenge in Basic JavaScript (Example: [Comment Your JavaScript Code](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/comment-your-javascript-code))
2. Write the following code:
```
let a = 1;

let c = 3;
```
3. Write `let` (or other JavaScript reserved words) in the second line
4. Press up or down arrow key on the keyboard
5. The pointer can't move to the previous or the next line 

**Expected behavior**
The pointer can move to the previous or the next line 

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.61

**Comment by Twaha-Rahman** [comment]
Yeah, I just tested it. It's reproducible.

**Comment by ojeytonwilliams** [comment]
It looks like it happens if there's a syntax error.  Also it can be cleared by typing anything else.

I reproduced it by clearing the editor and then typing

```js
//
a
```

At which point the cursor will not move up.  However, if you press `left`, everything starts working properly again.

**Comment by Twaha-Rahman** [comment]
Yeah... it's definitely not a big bug. Might cause minor annoyance though.

**Comment by ojeytonwilliams** [comment]
Agreed.  It's not urgent, but it's definitely not working quite right.

**Comment by lasjorg** [comment]
I'm guessing it has to do with the changes we made to the editor in https://github.com/freeCodeCamp/freeCodeCamp/pull/38551

I think the arrow input is stuck inside a hidden suggest menu. I would need to look into it some more but here is a gif showing `suggest-aria-id` changing as I click the up and down arrow. I suspect this happens after triggering the menu and the arrow up/down input is supposed to be moving up and down inside the menu.
![suggest-aria-id](https://user-images.githubusercontent.com/28780271/82836609-1d91db00-9ec7-11ea-8c76-fb98e5866c20.gif)

The menu from the monaco editor playground
![menu](https://user-images.githubusercontent.com/28780271/82836845-b1fc3d80-9ec7-11ea-9f0f-6531d091ea3e.png)
