### ISSUE TITLE
Link to "undefined is a keyword" is broken

### ISSUE THREAD

**Issue by vipranarayan14** [freeCodeCamp/freeCodeCamp#38895]
**Describe your problem and how to reproduce it:**
1. Visit https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions
2. Click on the link to undefined in Hint section.
3. It opens https://www.freecodecamp.org/challenges/understanding-uninitialized-variables 
4. 404 is shown on the opened page.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 76.0.1
* Operating System: macOS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="1920" alt="Screenshot 2020-05-25 at 8 39 04 PM" src="https://user-images.githubusercontent.com/17687018/82825302-9e050b80-9ec8-11ea-8842-851d5cf24b0c.png">
<img width="1920" alt="Screenshot 2020-05-25 at 8 39 31 PM" src="https://user-images.githubusercontent.com/17687018/82825318-a3625600-9ec8-11ea-8208-a1730193b290.png">

**Comment by raisedadead** [comment]
Thanks for reporting.

Here is the correct link that should be updated on the challenge:

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/understanding-uninitialized-variables

**Comment by mkochalko** [comment]
Hello, this is my first time trying to contribute and hoping to help! To clarify you are looking to update the broken link with the correct link provided above?

**Comment by Sky020** [comment]
Hello, @mkochalko .

Yes. If you go to the file in question: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions.english.md
The link at the end of the instructions needs to be updated.

@raisedadead , are you sure we want the link to refer to a challenge, and not one of the guide posts: https://www.freecodecamp.org/forum/t/the-javascript-undefined-primitive-value/15976

**Comment by JapneetSingh5** [comment]
I have opened a pull request, what do I have to do next?

**Comment by JapneetSingh5** [comment]
Please guide me further, this is my first contribution to an open source project.

**Comment by raisedadead** [comment]
> ... are you sure we want the link to refer to a challenge, and not one of the guide posts ...

From my initial investigation, that's what the original link was, which is it pointed to a challenge. I am open to other recommendations though.

**Comment by niteshseram** [comment]
I think it should not refer to any link. It is just a hint for the learner.

**Comment by niteshseram** [comment]
Can I work on this?

**Comment by JapneetSingh5** [comment]
I have already posted a PR
