### ISSUE TITLE
Sum All Odd Fibonacci won't execute

### ISSUE THREAD

**Issue by SEGrooms** [FreeCodeCamp/FreeCodeCamp#3890]
Challenge [Bonfire: Sum All Odd Fibonacci Numbers](http://www.freecodecamp.com/challenges/bonfire-sum-all-odd-fibonacci-numbers#?solution=function%20sumFibs(num)%20%7B%0A%20%20var%20a%20%3D%201%3B%20%20%2F%2F%20k%20%20%20%20number%20in%20sequence%0A%20%20var%20b%20%3D%201%3B%20%20%2F%2F(k%2B1)%20number%20in%20sequence%0A%20%20var%20odd_sum%20%3D%20a%20%2B%20b%3B%0A%20%20%0A%20%20while(odd_sum%20%3C%20num)%7B%0A%0A%20%20%20%20a%20%3D%20b%3B%20%20%20%20%2F%2F(k%2B1)%20number%20in%20sequence%0A%20%20%20%20b%20%2B%3D%20a%3B%20%20%20%2F%2F(k%2B2)%20number%20in%20sequence%20%0A%20%20%20%20%0A%20%20%20%20if(a%20%25%202%20%3D%3D%3D%201)%7B%0A%20%20%20%20%20%20odd_sum%20%2B%3D%20a%3B%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%0A%20%20return%20num%3B%0A%7D%0A%0AsumFibs(4)%3B) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
function sumFibs(num) {
  var a = 1;  // k    number in sequence
  var b = 1;  //(k+1) number in sequence
  var odd_sum = a + b;
  
  while(odd_sum < num){

    a = b;    //(k+1) number in sequence
    b += a;   //(k+2) number in sequence 
    
    if(a % 2 === 1){
      odd_sum += a;
    }
  }
  
  return num;
}

sumFibs(4);
```

I have been trying to execute my code, but it won't run. I have refreshed the page on numerous occasions, but it still won't run.

**Comment by abhisekp** [comment]
I guess, you've an infinite loop. So it's running but it just seems not to.
