### ISSUE TITLE
Make A Person Test Suite Fragile

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#38906]
**Describe your problem and how to reproduce it:**
The test suite for 'Make A Person' is a little fragile and needs some `// Only change...` comments.

The below code will fail the test suite even though the object definition is correct because a user changed the code outside of the object definition:
```
var Person = function(firstAndLast) {
  const names = firstAndLast.split(' ');
  let firstName = names[0];
  let lastName = names[1];
  // Complete the method below and implement the others similarly
  // Getters
  this.getFirstName = function() {
    return firstName;
  };
  this.getLastName = function() {
    return lastName;
  };
  this.getFullName = function() {
    return firstName + " " + lastName;
  };
  // Setters
  this.setFirstName = function(name) {
    firstName = name;
  };
  this.setLastName = function(name) {
    lastName = name;
  }
  this.setFullName = function(name) {
    const names = name.split(' ');
    firstName = names[0];
    lastName = names[1];
  }
};

var bob = new Person('Bob Ross');
bob.getFullName();
bob.setFirstName("Haskell") // This code passes if this line is removed
```

A fix is to add the `// Only change...` comments

New starter code:
```
var Person = function(firstAndLast) {
  // Only change code below this line
  // Complete the method below and implement the others similarly
  this.getFullName = function() {
    return "";
  };
  return firstAndLast;
  // Only change code above this line
};

var bob = new Person('Bob Ross');
bob.getFullName();
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/make-a-person

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 76.0.1 (64-bit)
* Operating System: Linux

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/25011573/82940936-c3d6f280-9f52-11ea-8d86-007074462412.png)

**Comment by ojeytonwilliams** [comment]
Good catch!  Rather than restricting what the user can do with `bob`, what do you think about adding the following code before the tests are run:

```js
if (bob) {
  bob = new Person("Bob Ross");
}
```

That way they can mess around with the object in their own tests, but it should be ready for the challenge tests.

**Comment by jeremylt** [comment]
Agreed, I like this better.

Credit goes to ieahleen on the forums for catching this, I just whipped up the reproducer.

**Comment by ojeytonwilliams** [comment]
Thanks to @Ieahleen, too then!

I think this should not be too hard to fix, so I'll pop the label on it.
