### ISSUE TITLE
Add a Show Solution button for certification projects on the timeline

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#38918]
Currently when you complete a project it's shown on the timeline, but there isn't an easy way to see the solution that was submitted:

![image](https://user-images.githubusercontent.com/2051070/83040547-58884000-a07a-11ea-90f7-e0dcc0aa9676.png)

We should add a "Show Solution" button between the link to the project's page on the left and the date on the right. The button can be similar to the on the settings page, and it should open the solution that was submitted.

However, we'll need to handle the solutions for the JS Data Structures and Algorithm projects differently. Since the solutions are stored in the DB, maybe we can seed the solution back to the editor when the link in clicked. Or showing the submitted code in a popup modal might also be an option.

**Comment by raisedadead** [comment]
I am assigning this to @ahmadabdolsaheb to cut the turn around time and feedback loop.

**Comment by ahmadabdolsaheb** [comment]
implementing this functionality seems straight forward since we have a similar feature in the settings page.

the users' solutions should be stored in the redux store, however since the store and db are not in sync after the project submission, it takes a refresh for the solution to show up on the client.

I was wondering if we would need show the responses to show up specifically for project since we are not showing solutions for other challenges?

**Comment by scissorsneedfoodtoo** [comment]
@ahmadabdolsaheb, I think it would be fine if it takes a refresh to show the solution. It's my understanding that this feature is mainly to dissuade academic dishonesty, and to give potential employers an easy way to view live versions of person's projects.

**Comment by ahmadabdolsaheb** [comment]
I am removing my assignment in case another contributor is interested in making a pull request.

**Comment by ojeytonwilliams** [comment]
Hi @dipayanDebTheCoder. You are correct. This issue is open to anyone and no-one else has said they're working on it. Regardless, issues like this are open for anyone, so please go ahead.

**Comment by dipayanDebTheCoder** [comment]
Does this look good ? @ojeytonwilliams @ahmadabdolsaheb . Also while coding I noticed that completedChallanges has a field called files. Is that somehow related to the solution for the  submitted solutions. At the moment I can only see that the fields solution and githubLink is used. 
![Screenshot (55)](https://user-images.githubusercontent.com/72683956/97426139-0a34e100-1939-11eb-848a-ae4b7d9eea0f.png)
![Screenshot (54)](https://user-images.githubusercontent.com/72683956/97426203-1faa0b00-1939-11eb-8fbf-3123bc748027.png)

**Comment by Sky020** [comment]
>  I noticed that completedChallanges has a field called files. Is that somehow related to the solution for the submitted solutions

@dipayanDebTheCoder The `files` field is used in the _JavaScript and Data Structures_ projects. A modal should pop up showing the JS code.

**Comment by dipayanDebTheCoder** [comment]
@Sky020 Thanks. I will take a look at it and then do a PR request
