### ISSUE TITLE
Update "Report This User" link

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#38919]
On the profile page, we should change the text from "Report This User" to "Flag This User's Account for Abuse".

Also, we should change the email address it sends an alert to from team@freecodecamp.org to support@freecodecamp.org.

Cc @QuincyLarson for feedback on the text.

**Comment by hi-matbub** [comment]
I'll jump on this

**Comment by Sky020** [comment]
@hi-matbub , it is good that you are willing to help, but perhaps wait for clarification on the text that should be implemented, before submitting any PR.

**Comment by moT01** [comment]
That text should be good. If there's a problem, it can be changed later.

**Comment by scissorsneedfoodtoo** [comment]
Echoing what @moT01 said, go ahead and change the text to "Flag This User's Account for Abuse" for now. Looking forward to your PR @hi-matbub.
