### ISSUE TITLE
Waypoint: Create a Bulleted Unordered List instructions are wrong

### ISSUE THREAD

**Issue by thenexttexploration** [FreeCodeCamp/FreeCodeCamp#3891]
Within the challenge it instructs you to create bullets by replacing all the p elements with(no spaces of course) < li > elements to get a bulleted list.  When I follow it as instructed it leaves my style coding visible (class="red-text") is then displayed.  When I remove the end closure  < l i (obviously no spaces), it leaves everything intact but the practice won't allow me to advance without adding the closure... even though the closure is added at the end of the style portion of my closure 
Example:
For it to look right I remove the end closure  making it < l i  this happens: <li class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</li>

BUT for it to be marked correctly I have to Complete the closure < li > class="red-text">Kitty ipsum...... and it looks like this:
<li> class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</li>
So In order to fix it, and still make sure my code isn't displayed on my final work, i'd have to remove my styling from the code or simply leave it exposed

See below for the link to the segment and below that is my full code
Challenge [Waypoint: Create a Bulleted Unordered List](http://freecodecamp.com/challenges/waypoint-create-a-bulleted-unordered-list#?solution=%3Clink%20href%3D%22http%3A%2F%2Ffonts.googleapis.com%2Fcss%3Ffamily%3DLobster%22%20rel%3D%22stylesheet%22%20type%3D%22text%2Fcss%22%3E%0A%3Cstyle%3E%0A%20%20.red-text%20%7B%0A%20%20%20%20color%3A%20red%3B%0A%20%20%7D%0A%0A%20%20h2%20%7B%0A%20%20%20%20font-family%3A%20Lobster%2C%20Monospace%3B%0A%20%20%7D%0A%0A%20%20p%20%7B%0A%20%20%20%20font-size%3A%2016px%3B%0A%20%20%20%20font-family%3A%20Monospace%3B%0A%20%20%7D%0A%0A%20%20.thick-green-border%20%7B%0A%20%20%20%20border-color%3A%20green%3B%0A%20%20%20%20border-width%3A%2010px%3B%0A%20%20%20%20border-style%3A%20solid%3B%0A%20%20%20%20border-radius%3A%2050%25%3B%0A%20%20%7D%0A%0A%20%20.smaller-image%20%7B%0A%20%20%20%20width%3A%20100px%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cul%3E%0A%3Cli%3EClick%20here%20for%20%3Ca%20href%3D%22%23%22%3Ecat%20photos%3C%2Fa%3E.%3C%2Fli%3E%0A%0A%3Ca%20href%3D%22%23%22%3E%3Cimg%20class%3D%22smaller-image%20thick-green-border%22%20src%3D%22https%3A%2F%2Fbit.ly%2Ffcc-relaxing-cat%22%3E%3C%2Fa%3E%0A%0A%3Cli%20class%3D%22red-text%22%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fli%3E%0A%3Cli%20class%3D%22red-text%22%3EPurr%20jump%20eat%20the%20grass%20rip%20the%20couch%20scratched%20sunbathe%2C%20shed%20everywhere%20rip%20the%20couch%20sleep%20in%20the%20sink%20fluffy%20fur%20catnip%20scratched.%3C%2Fli%3E%0A%3C%2Ful%3E) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  .red-text {
    color: red;
  }

  h2 {
    font-family: Lobster, Monospace;
  }

  p {
    font-size: 16px;
    font-family: Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

  .smaller-image {
    width: 100px;
  }
</style>

<h2 class="red-text">CatPhotoApp</h2>
<ul>
<li>Click here for <a href="#">cat photos</a>.</li>

<a href="#"><img class="smaller-image thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>

<li class="red-text">Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</li>
<li class="red-text">Purr jump eat the grass rip the couch scratched sunbathe, shed everywhere rip the couch sleep in the sink fluffy fur catnip scratched.</li>
</ul>
```

**Comment by ltegman** [comment]
What the instructions for this challenge mean to be asking is for you to completely remove the bottom two paragraphs and put an unordered list at the bottom instead. This avoids the problem you're running into of having an anchor tag in the middle of your `ul` block (which is not valid markup). I agree that the wording is confusing since there is another `p` tag earlier in the page with other types of tags in between.

This should be clarified to reflect that the bottom two `p` tags should be removed and a three item list created in it's place.

**Comment by masonblack1** [comment]
I can't complete the challenge either
