### ISSUE TITLE
Python for Everybody - Introduction: Elements of PythonPassed

### ISSUE THREAD

**Issue by casraysa** [freeCodeCamp/freeCodeCamp#38925]
**Describe your problem and how to reproduce it:**
All the code should be aligned at the same starting position.

**Add a Link to the page with the problem:**
https://www.freecodecamp.dev/learn/scientific-computing-with-python/python-for-everybody/introduction-elements-of-python

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 78.0.3904.87 (Build oficial) (64 bits)
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/14315712/83065130-3afbac00-a063-11ea-943f-5944b94055b0.png)

**Comment by moT01** [comment]
Yes, that appears correct. I confirmed this by [testing the code here](https://trinket.io/python/f7ad7f9864)
[Here's the file](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/introduction-elements-of-python.md) that needs updating

**Comment by casraysa** [comment]
Hi,

There is an extra space in the second and third line of code:

[cid:78f51308-c943-4d3a-b18b-404d31c0511a]

As you know, if you try to execute these lines of code copying and pasting in a Python interperter, it will give you an indentation error. That's what I mean.

Cheers,
Salva

________________________________
De: Tom <notifications@github.com>
Enviado: miércoles, 27 de mayo de 2020 22:03
Para: freeCodeCamp/freeCodeCamp <freeCodeCamp@noreply.github.com>
Cc: casraysa <casraysa@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [freeCodeCamp/freeCodeCamp] Python for Everybody - Introduction: Elements of PythonPassed (#38925)


Yes, that appears correct. I confirmed this by testing the code here<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftrinket.io%2Fpython%2Ff7ad7f9864&data=02%7C01%7C%7Cfe0424e4174a4e309c5808d8027904ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637262066073315001&sdata=wfqU33iFHJ6FnWXN5NUfr7ej%2FEM9km%2FVD15%2FP7E9mtg%3D&reserved=0>
Here's the file<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FfreeCodeCamp%2FfreeCodeCamp%2Fblob%2Fmaster%2Fcurriculum%2Fchallenges%2Fenglish%2F07-scientific-computing-with-python%2Fpython-for-everybody%2Fintroduction-elements-of-python.md&data=02%7C01%7C%7Cfe0424e4174a4e309c5808d8027904ee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637262066073325003&sdata=wVvyTvZR%2BwGvkowTeecUmzNYvX7HL%2FEAYkQEWxrqF9U%3D&reserved=0> that needs updating

**Comment by Sky020** [comment]
Related: https://www.freecodecamp.dev/learn/scientific-computing-with-python/python-for-everybody/intermediate-strings
Unintended indentation

**Comment by Sky020** [comment]
Related: https://www.freecodecamp.dev/learn/scientific-computing-with-python/python-for-everybody/python-lists
Unintended indentation

**Comment by raisedadead** [comment]
I am removing the first timer limitation on this to speed up turn around time on the python related dev work. 

If you are a first timer, please feel free to make a PR regardless, we welcome a fix from you.

**Comment by Sky020** [comment]
To whoever works on this: Please note, there are some code formatting issues linked to this: #38930

**Comment by moT01** [comment]
Also note that you can [use markdown](https://contribute.freecodecamp.org/#/how-to-help-with-video-challenges?id=use-markdown-to-format-your-question) if you want. I would recommend it, but whatever works.

**Comment by Ieahleen** [comment]
if someone wants to work on this, should they fix all the linked challenges in a single pull request?

**Comment by Sky020** [comment]
@Ieahleen , that would make things much easier to keep track of, but I suppose not entirely necessary.

**Comment by ojeytonwilliams** [comment]
If someone only has time to do a few challenges, it's fine, though a single PR would be ideal. We can always edit this issue to track partial completion.

**Comment by Ieahleen** [comment]
it's not a thing I am being able to fix
it seems an issue more with how the file is rendered than with the file itself, in the file they are perfectly lined one below the other. 
Probably there is some hacky way to remove that extra indentation trying to add and remove spaces or something, but it would require being able to see easily how changes you make affect the result and I don't have a setup that allow me that yet

**Comment by Sky020** [comment]
@Ieahleen , Have you tried using the `<code>` tags?

**Comment by Ieahleen** [comment]
@Sky020 : Before that, I don't know how to use GitPod to check how that affects the challenge page without creating the pull request, so I will stay with the "I am not able to fix this"

**Comment by moT01** [comment]
I'm not sure exactly what you are trying to change @Ieahleen, but I think if you use markdown - it may be easier.

Here's the question in the OP with markdown...
````
question:
  text: |
What will the following program print out:
```
x = 43
x = x + 1
print(x)
```
  answers:
    - 'x'
    - 'x + 1'
    - '44'
  solution: 3
````

Here's how the code part would look:

```
x = 43
x = x + 1
print(x)
```

You can try out markdown right here in the github comments.

**Comment by Ieahleen** [comment]
@moT01 I don't know how to check if that works without creating the pull request and opening the gitpod environment from there, so for now I am going to study how GitPod works

**Comment by Ieahleen** [comment]
ok, I have it, terribly hacky, and no markdown (it refuses to show anything at that point, so I imagine it can't be rendered like that): just adding a space before the first line of code will make all three lines match.
I am just going to figure out how to create a pull request (as draft, I imagine), and then move on to the other ones.
If someone else can make it work in an other way and wants to do the pull request, totally fine too, it's all experience.
