### ISSUE TITLE
Python for Everybody - More Conditional Structures

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#38926]
**Describe your problem and how to reproduce it:**
The answer to this is incorrect. Due to the existance of the `try...catch`, the code does not get interrupted, and runs to completion:
```
temp = "5 degrees"
cel = 0
try:
	fahr = float(temp)
	cel = (fahr - 32.0) * 5.0 / 9.0
except:
	print("temp should be a number")
print(cel)
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.dev/learn/scientific-computing-with-python/python-for-everybody/more-conditional-structures

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this, @Sky020.

As an alternative, perhaps the question could read:

````
Which lines should be surrounded by a `try` block?:

```py
1 |temp = "5 degrees"
2 |cel = 0
3 |
4 |fahr = float(temp)
5 |cel = (fahr - 32.0) * 5.0 / 9.0
7 |
6 |print(cel)
```
````

Or perhaps the same code and ask the same question, "Which line would cause the script to immediately stop because of an error?"

**Comment by Sky020** [comment]
@scissorsneedfoodtoo , I would leave answering that question to someone who has an idea of what students should be able to answer at this point.

After watching the video, I would say this is too easy of a question:
>"Which line would cause the script to immediately stop because of an error?"

So, I would go with this. But, perhaps get input from another mod...
>Which lines should be surrounded by a `try` block?:

**Comment by niteshseram** [comment]
I can work on this?

**Comment by niteshseram** [comment]
@Sky020  so, I am going with changes
`Which lines should be surrounded by a try block?` instead.
It is fine, I guess??

**Comment by Sky020** [comment]
@niteshseram, Yes. I suppose something you can do is create a PR with that change, and other contributors can chime in, if they see it better another way. After changing the question, you will need to change the answers to match...

**Comment by niteshseram** [comment]
Okay, sure. Will be creating a PR by tomorrow.
