### ISSUE TITLE
Waypoint: Override Class Declarations by Styling ID Attributes - an opinion

### ISSUE THREAD

**Issue by ParkinT** [FreeCodeCamp/FreeCodeCamp#3892]
I understand the principle you are trying to teach here.  But have a dispute with the choice of nomenclature for the `id`.
It is inappropriate to use an `id` that is "style specific".  This challenge would be more 'real world' (and not teach poor habits) if the name for the `h1` element was something like "main-heading" or "primary-header".  It should be *contextual* and not *stylistic*.

**Comment by SaintPeter** [comment]
Our overriding concerns are pedagogical in nature.  We need to teach true novices how these operators work and interact and that is simplified by having simple descriptive names.

Thank you and happy coding!
