### ISSUE TITLE
Python for Everybody - Regular Expressions

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#38928]
**Describe your problem and how to reproduce it:**
I think the wording of the question should be re-done. Whilst I perfectly understood what was being asked for, there are **3** correct answers, as `.` does match _"a white space character"_.

**Add a Link to the page with the problem:**
https://www.freecodecamp.dev/learn/scientific-computing-with-python/python-for-everybody/regular-expressions

**Comment by scissorsneedfoodtoo** [comment]
Another great catch @Sky020.

We could remove or change the last choice, and change the wording to something like "Which regex matches only a whitespace character?"

Alternatively we could change both the dots to other special characters and keep the question the same.

**Comment by Sky020** [comment]
@scissorsneedfoodtoo , This is what I was thinking too:
>"Which regex matches only a whitespace character?"

It requires the user to think a little more, but I would only have **1** `.`

**Comment by Sky020** [comment]
Just looking at the file, it appears the parser is removing the backslashes:
```
answers:
    - '\S'
    - '\s'
    - '.'
    - '\_'
    - '\.'
```
