### ISSUE TITLE
checking of Projects after submission

### ISSUE THREAD

**Issue by Advitya-sharma** [freeCodeCamp/freeCodeCamp#38922]
- When ever a user submits a projects their are no checks if the user has correctly completed the assignment,Its expected from the user to complete the tests and submit a 100% correct working assignment.

- though I don't have any simple solution for this issue but we can perform some validation checks on the submitted assignment.

- Instead of checking the link after submission, we can design a custom script that checks the user progress example if the user passed 9 out of 10 test then it will be updated in the FCC db that user has one test to complete,after the user gets 10/10 we can update his/her progress and mark the assignment complete

![SharedScreenshot](https://user-images.githubusercontent.com/54709416/83053069-c843fe00-a06d-11ea-984c-c9f90e974ab2.jpg)

**Comment by raisedadead** [comment]
Thanks for this report. 

There are previously open issues on similar lines. I would request you to continue the discussion on them instead ?

Thanks.

**Comment by Advitya-sharma** [comment]
okok, can you share issue id

**Comment by raisedadead** [comment]
Sure, its a quick search away: https://github.com/freeCodeCamp/freeCodeCamp/issues/37185
