### ISSUE TITLE
Entry on the timeline when finishing the new Python certificates is not working

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#38920]
Currently when you complete/claim a certificate there's an entry on the timeline:

<img width="582" alt="Screen Shot 2020-05-27 at 9 37 55 AM" src="https://user-images.githubusercontent.com/2051070/83041908-f3cde500-a07b-11ea-84ea-dd112b91ddf5.png">

This doesn't seem to be working for the new Scientific Computing with Python, Data Analysis with Python, and Machine Learning with Python certificates.

**Comment by jasnkwcz** [comment]
I'm a new contributor but I'd like to help out on this.

**Comment by moT01** [comment]
I think this is mostly working. You just need to refresh the page before it shows up...
<img width="598" alt="Screen Shot 2020-05-27 at 11 34 12 AM" src="https://user-images.githubusercontent.com/20648924/83047462-06a9d080-a00e-11ea-8689-fe14352c72ab.png">

**Comment by scissorsneedfoodtoo** [comment]
Ah, interesting. This does seem to work locally but not on .dev for some reason.

**Comment by scissorsneedfoodtoo** [comment]
This may be a one off issue related to https://github.com/freeCodeCamp/freeCodeCamp/issues/39002 where the new/split certificates (Quality Assurance, Information Security, Scientific Computing with Python, Data Analysis with Python, and Machine Learning with Python) were not seeded to the .dev database for some reason. I can confirm this is working locally like @moT01 mentioned above.

@jasnkwcz, thank you for your interest in contributing. Please check out issues with the [help wanted](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) label for other things we need help with.
