### ISSUE TITLE
I can’t see the code examples in this article

### ISSUE THREAD

**Issue by ABourassine** [freeCodeCamp/freeCodeCamp#38933]
Hello everyone,

https://discourse-user-assets.s3.dualstack.us-east-1.amazonaws.com/original/3X/7/9/792eba16694e0048d2f7a644e04b181204a2889c.png

As you can see in the image, there is no code to be found (and it’s the same with all the other examples in the article)
i’ve tried more than one browser and it’s all the same
link to the article: https://www.freecodecamp.org/news/how-to-write-simple-modern-javascript-apps-with-webpack-and-progressive-web-techniques-a30354eab214/
please help I need this

thank you very much

**Comment by raisedadead** [comment]
Thanks for your report.  We are pinging the editorial team to check and resolve this.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for bringing this to our attention @ABourassine. I just finished updating the article.

Please feel free to @ mention me if you notice any other issues.

**Comment by ABourassine** [comment]
thank you everyone it works now 👍
