### ISSUE TITLE
Wrong CSS selector type passes challenge

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#38932]
The challenge is asking to use an element selector but the regex allows for a class selector.

Challenge: https://www.freecodecamp.org/learn/responsive-web-design/basic-css/import-a-google-font

Forum post: https://www.freecodecamp.org/forum/t/html-css-font-help/395209

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @lasjorg. I agree that this can be confusing even if the text makes it clear to use an element selector.

To anyone who works on this, it seems like changing the third `testString` to the following will fix this:

`assert(/^\s*h2\s*\{\s*font-family\:\s*(\"|")?Lobster(\"|")?(.{0,})\s*;\s*\}/gim.test(code));`

That change should still allow all valid rules targeting `h2`, but not match `.h2`.

**Comment by 1t1e1** [comment]
Hi. I understand the bug. I want to do this. Can I take it.

**Comment by Ieahleen** [comment]
@1t1e1 : as per [contribution guidelines](https://contribute.freecodecamp.org/#/index?id=where-do-i-start-if-i-want-to-work-on-an-issue) all the issues with Help wanted label are up for grabs and you do not need to seek permission before start working on them

**Comment by g4rry420** [comment]
hello, I am working on the issue, just one question ,  the last line testString should include gim.test(code));   OR gi.test(code));

**Comment by Sky020** [comment]
@g4rry420 , probably best using:
```
assert(code.match(regex)
```

**Comment by 1t1e1** [comment]
@g4rry420 I think it must be `gim`. I guess it part of regex and `m` stand for multi line. This will solve to pass challenge with rule that does not ask like `font-size:30px`.

@Ieahleen Thank you. I missed. Actually I found this document too late. newbie problems. :relieved:

**Comment by g4rry420** [comment]
#38944

**Comment by ptkpyitheim** [comment]
@scissorsneedfoodtoo 

The regex works if you test it with

`h2 {
     font-family: "Lobster";
   }

h2 {
     font-family: Lobster;
   }`

but not
`
h2 {
     font-family: 'Lobster';
   }
`

So I added something to the regex. Regex101 says it should work. I linked it below. However, when I changed it in the code and test it locally, it doesn't work. It only works for Lobster with double quotes or without it. Single quote doesn't seem to work. This is what I tried:

` testString: 'assert(code.match(/\s*h2\s*\{\s*font-family\:\s*(\"|"|')?Lobster(\"|"|')?(.{0,})\s*;\s*\}/));' `

I tried it on both Safari and Chrome and on incognitos windows too. This is the directory path where I changed the code. If there's somewhere else that I need to change please let me know.

`client/curriculum/challenges/basic-css/import-a-google-font.english.md`

https://regex101.com/r/g9WCbi/7

**Comment by ptkpyitheim** [comment]
@scissorsneedfoodtoo 

Your regex works for 

`
h2 {
     font-family: "Lobster";
   }

h2 {
     font-family: Lobster;
   }
`
but doesn't work for single quoted Lobster as such : ` 'Lobster' `

I changed the regex to be this and it works for all three test cases.

` assert(/\s*h2\s*\{\s*font-family\:\s*(\"|"|\')?Lobster(\"|"|\')?(.{0,})\s*;\s*\}/gi.test(code)); `

Making pull request soon.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for catching that @ptkpyitheim and for submitting a PR so quickly.

**Comment by programmerraja** [comment]
is still open ? i like to contribute can i?

**Comment by Sky020** [comment]
@programmerraja , Sorry, this issue has a linked pull-request that is likely to close the issue. You are welcome to work on other issues with the _help wanted_ label which do not have open PRs.

**Comment by RandellDawson** [comment]
@Sky020 @scissorsneedfoodtoo See [my comment](https://github.com/freeCodeCamp/freeCodeCamp/pull/39084#pullrequestreview-446711596) on the original issue.  If we expect the user to use a type selector, then why don't we ask the user to use a type selector.  Other, the user should be allowed to create an `.h2` selector and specify `h2` in the `class` attribute.   Then, the testString changes in #39084 make sense.  If you all agree, I can make the additional commit and we can get this PR approved/merged.  Let me know your thoughts.

**Comment by Sky020** [comment]
@RandellDawson . In that case, shall we edit the test to be inclusive of all selector types?

We could edit the instructions to be more specific, but I am concerned there will be too much jargon which will confuse more.

**Comment by lasjorg** [comment]
I don't see why we should complicate this any more than we have to. The [previous challenge](https://www.freecodecamp.org/learn/responsive-web-design/basic-css/set-the-font-family-of-an-element) shows how to set the font family on an element using the element selector. This challenge was in my opinion clearly made with the intention of the camper using an element selector to set the font, even if it is not explicitly said so.

I suggest we limit the valid selector to just the element selector. If we can get @ptkpyitheim to update the challenge instructions with the proposed change to the text that @RandellDawson gave in the PR I'd be in favor of this.

**Comment by prakharindoria** [comment]
I would like to contribute.

**Comment by RandellDawson** [comment]
@prakharindoria There currently is an outstanding PR #39084 that we are waiting on the contributor to update based on the latest discussion in this issue.  If the user does not make the changes in the next week, then you could go ahead and create a PR.

There are many other issues listed where you could help.  See if you can find one that does not currently have a PR for it.

**Comment by prakharindoria** [comment]
Its great to hear from you @RandellDawson. I will look into something else.

**Comment by RandellDawson** [comment]
@Sky020 Would you be OK with @lasjorg's latest suggestion?  If so, then can one of you make the necessary commit?  I will approve such a change.

**Comment by ptkpyitheim** [comment]
> Awesome, thanks for catching that @ptkpyitheim and for submitting a PR so quickly.

Yes, no problem. I'm checking out the comments on the PR link.
