### ISSUE TITLE
Confirm the shape of full-stack cert

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#38934]
The fullstack cert doesn't yet include the the three new python certificates, however it does include the InfoSec Cert and QA Cert (that have been split from the single InfoSec & QA cert).

We need clarity on the what is happening to the retired projects (there are new required projects in both certs).

We also need clarity on what is required to claim the fullstack cert. As is it does not have the three new python certs. At the same time, it needs one additional cert (from the split as mentioned earlier).

This could be a source of support queries. 

Refer: https://github.com/freeCodeCamp/freeCodeCamp/pull/38912#pullrequestreview-419094596

**Comment by raisedadead** [comment]
@beaucarnes @QuincyLarson 

I would like some inputs on the plans that was formulated how to mitigate this. Validations you would implement for the various scenarios.

1. Partial Curriculum Progress.
2. ~Past certifications~ (this is implemented and tested already)

**Comment by QuincyLarson** [comment]
@raisedadead I think we should call it the "Legacy Full Stack Development Certification" and it should include the first 6 certifications.

Once we've added the Relational Database Certification projects and merged the Data Visualization Certification into the Front End Libraries certification, we can create a new Full Stack Development Certification that you get for completing all 10 certifications.

**Comment by raisedadead** [comment]
> I think we should call it the "Legacy Full Stack Development Certification" and it should include the first 6 certifications.

Thanks for the confirmation. This needs some visual changes to the settings and timelines. From my guess this does not need any change to the API. 

I am assigning @ahmadabdolsaheb to work on this.

Ahmad, this is a potential show stopper for shipping to production.

> Once we've added the Relational Database Certification projects and merged the Data Visualization Certification into the Front End Libraries certification, we can create a new Full Stack Development Certification that you get for completing all 10 certifications.

I have created https://github.com/freeCodeCamp/freeCodeCamp/issues/38943 to track this specifically.

**Comment by ahmadabdolsaheb** [comment]
> I think we should call it the "Legacy Full Stack Development Certification" and it should include the first 6 certifications.

Are we referring to the following 7 certificates? 

1. responsive web design
2. javascript data structures and algorithms
3. front end libraries
4. data visualisation
5. api and microservices
6. quality assurance
7. info security

**Comment by raisedadead** [comment]
Maybe @QuincyLarson and @beaucarnes have thought of how this to be mitigated? The certificates were split and did replace some projects?

So it has to be both ways?

**Comment by ahmadabdolsaheb** [comment]
Also, 
> Once we've added the Relational Database Certification projects and merged the Data Visualization Certification into the Front End Libraries certification, we can create a new Full Stack Development Certification that you get for completing all 10 certifications.

I think it implies Relational Database will be a certification of its own.
In that case, 7 js certs, 3 python certs, and relational db would make 11 certs.

**Comment by QuincyLarson** [comment]
@ahmadabdolsaheb Just to be 100% clear, here are the two terms I've been using:

"Front 3" (called "front" because they can be done right on freeCodeCamp.org without any additional tools or servers)
1. Responsive Web Design
2. JavaScript Algorithms and Data Structures
3. Front End Libraries (will include the Data Visualization Certification, which will be merged in during phase 3)

"Back 7" (called "back" because because they will require a back end, and will be completed either in a VS Code environment in a browser or on a local computer in a Docker container):
1. Relational Databases
2. APIs and Microservices
3. Quality Assurance
4. Scientific Computing
5. Data Analysis
6. Machine Learning
7. Information Security

We want the Full Stack Developer Certification to only be claimable after completing all 50 certification projects. Once we ship our current beta, 45 of these 50 certification projects will be live in production. We will ship the Relational Database Certifications once @moT01 is done with them.)

In the meantime, we have the Legacy Full Stack Development Certification, which can be earned by completing the projects from:
- the front 3
- the 5 data visualization projects
- the 5 API and Microservice projects
- the 5 Quality Assurance projects

I think we can immediately start calling this the "Legacy Full Stack Certification", and just introduce the new Full Stack Certification with Phase 3 when we've added these final 5 Relational Database Projects.

**Comment by raisedadead** [comment]
@moT01 in his https://github.com/freeCodeCamp/freeCodeCamp/pull/38995#issuecomment-638586622 says:

> What if someone is like one project away, and all of a sudden there's 5 new projects before it can be claimed.

Now, from the discussion in this thread, **it seems to imply** that we will have the certification renamed and anyone **who is midway or almost done** with the cert will have to go thru with additional projects for certification?

@QuincyLarson can you confirm this? IMHO, So far this thread has only covered users who are "going to start" the InfoSec or the QA Cert.

**Comment by raisedadead** [comment]
@QuincyLarson 

Ahmad, Kris, Oliver and me met to discuss and QA the implementation in https://github.com/freeCodeCamp/freeCodeCamp/pull/38995. We hit some hurdles, while trying to address the requirement in the changes you requested for the Legacy Full Stack Development Certification. 

After much deliberation we concluded this is what we can do to be able to mitigate all sorts of technical limitations around the legacy schema we have had.

1. The current Full Stack Certification in the settings is to be moved to the legacy section (below everything in that legacy stack).
2. It is to be called 'Legacy Full Stack Development Certification' as per the thread above.
3. It will list all the certifications needed to claim it:

- Responsive Web Design
- Algorithms and Data Structures
- Front End Libraries
- Data Visualization
- APIs and Microservices
- ~~Quality Assurance~~ Legacy Infosec and QA Certs
	- Metric Imperial Converter
	- Issue Tracker
	- Personal Library
	- Stock Price Checker
	- Anonymous Message Board
4. All projects should link back to their own pages (already on learn) for quick navigation.
5. We will have a 'coming soon' style section for the  'Full Stack Development Certification' as a replacement for the above move. 


Doing the above will address:

1. Anyone who has completed the projects from the 'Legacy InfoSec and QA Cert' will be able to claim the Legacy Full Stack Development certification.
2. We will not advertise this on the learn map for new users, which means mostly users who were continuing this certification will claim it.
3. It will make all the implementation quite simple and straight for the @freeCodeCamp/dev-team without delaying the new curriculum, effectively unblocking it.
4. Finally we agreed that the upcoming Phase 3 changes will make this a good transitional choice without users needing to wait on claiming certifications. They can claim certs as they become available. They can also go back and claim legacy certs should they choose to.
