### ISSUE TITLE
Python for Everybody: malformed sentence in "Variables, Expressions, and Statements" challenge

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#38939]
Challenge: https://www.freecodecamp.dev/learn/scientific-computing-with-python/python-for-everybody/variables-expressions-and-statements

Sentence has an extra "is" in it.

What is the symbol is used in an assignment statement?

Should be:

What is the symbol used in an assignment statement?

**Comment by mahitha22** [comment]
Hi, I am a beginner to open source projects and would like to make a contribution here. 

I have cloned the project, created a new branch, made the changes to the text. When I do the commit by adding just the file that I edited, Git is giving a list of files "delete mode 100644 <filename>". Did I do something wrong? Could anyone please help.

Thank you
