### ISSUE TITLE
Waypoint: Create a Block Element Bootstrap Button - more descriptive regarding block-element?

### ISSUE THREAD

**Issue by ParkinT** [FreeCodeCamp/FreeCodeCamp#3893]
I want to suggest that, at this point, in addition to the comment about the block element '...will stretch to fill your page's entire horizontal space.', there is a comment that any element *following* it will flow to a "new line".
You could argue that is [almost] "assumed".  But I believe it should be stated.

**Comment by ltegman** [comment]
Closed by #3946
