### ISSUE TITLE
Python for Everybody: python functions, better indication of multiple choice answers

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#38941]
Challenge: https://www.freecodecamp.dev/learn/scientific-computing-with-python/python-for-everybody/python-functions

I'd prefer "Answers b and c are both true" instead of "b and c are both true", just to avoid any confusion. Or some other clear indication of multiple choice answers.

**Comment by Sky020** [comment]
#38927
