### ISSUE TITLE
[Video challenges]: Code blocks are inconsistent 

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#38942]
#### [Video challenge with code block in html tags...](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/web-services-xml.english.md)
<img width="492" alt="Screen Shot 2020-05-28 at 1 29 28 PM" src="https://user-images.githubusercontent.com/20648924/83179372-92dbf680-a0e7-11ea-8dcb-a4540b17463b.png">

#### [Video challenge with code block in markdown...](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/networking-write-a-web-browser.english.md)
<img width="511" alt="Screen Shot 2020-05-28 at 1 28 37 PM" src="https://user-images.githubusercontent.com/20648924/83179365-8eafd900-a0e7-11ea-97b9-9592097a122a.png">

#### I vote to switch them all to markdown, or possibly change the html styles to match.

<hr>

### Additionally, somewhat related - code blocks in the answers look bad...
<img width="518" alt="Screen Shot 2020-05-28 at 1 53 35 PM" src="https://user-images.githubusercontent.com/20648924/83181622-c4a28c80-a0ea-11ea-9f94-2a1fdc1c2d48.png">

**Comment by scissorsneedfoodtoo** [comment]
@moT01, thanks for catching the code blocks in the answer section looking off. Didn't notice it at first -- maybe it required a refresh? But yeah, looks off with the darker background.

Tested this locally and it seems like we can just remove the language (py or python) from the triple backticks:

![image](https://user-images.githubusercontent.com/2051070/83221340-8374b000-a1b0-11ea-939e-7e3456c95121.png)

I also think it would be better to have all the code in markdown. It's a bit finicky in conjunction with YAML, but makes it much easier to control the formatting/spacing than `<pre>` tags.

**Comment by ojeytonwilliams** [comment]
How about something like this:

![image](https://user-images.githubusercontent.com/15801806/83237350-2c151680-a195-11ea-8edf-6a5863841377.png)

this is with a background of `--secondary-background` and using https://github.com/freeCodeCamp/freeCodeCamp/pull/38730 to enable highlighting.  I'm not sure what the best background is. This one looks a little better than white and is a bit better from a contrast perspective.

**Comment by moT01** [comment]
I would like to see the same background color for answers like in Kris's photo, but the code highlighting, like in Oliver's.

I think the only way to achieve this is to change some styles after the fact in the css.

**Comment by ojeytonwilliams** [comment]
Makes sense to me.  They might look a little better with a dark border, but either way, I think the white background is the way to go.
