### ISSUE TITLE
Minor Typo in 'Waypoint: Taste the Bootstrap Button Color Rainbow'

### ISSUE THREAD

**Issue by ParkinT** [FreeCodeCamp/FreeCodeCamp#3894]
~~I believe the intention was for "The `btn-primary` class is the main color you'll use in your app." to read "The btn-primary is the main class you'll use in your app."~~
I was mistaken.  Please ignore this issue.

**Comment by Richbward** [comment]
Hhhmmm...I was just about to add this as well.  It is minor - but it shouldn't be, "color" and should instead be, "class".  This is correct - and it is used correctly twice later in the description:
1. "Add Bootstrap's btn-primary class to your button."
2.  "Your button should have the class btn-primary."
