### ISSUE TITLE
Feature request: high contrast mode

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#38947]
**Is your feature request related to a problem? Please describe.**
Syntax highlighting lowers the contrast ratio of the text.  The use of colours is helpful for many users, but could make it harder to read for others. 

**Describe the solution you'd like**
It should be possible for a user to disable syntax highlighting.  Possibly via a toggle, similarly to night mode.

**Describe alternatives you've considered**
Altering the colours used in syntax highlighting and the background.  It is difficult to find choices that both look good and maintain high contrast.

**Additional context**
Here's https://www.freecodecamp.dev/learn/javascript-algorithms-and-data-structures/basic-javascript/comment-your-javascript-code with the WebAIM tool running:

![image](https://user-images.githubusercontent.com/15801806/83240214-59fc5a00-a199-11ea-913b-c2dd58844cac.png)

showing that it has flagged up the JavaScript comments.

**Comment by moT01** [comment]
If the comments are the only contrast issue, maybe it would be easier to try and just change the color of those instead of creating a whole new contrast mode.

**Comment by ojeytonwilliams** [comment]
The WAVE tool shows problems with various things.  For example

HTML tags:

![image](https://user-images.githubusercontent.com/15801806/83308333-e7c25e80-a206-11ea-9a83-5cbe3b48f5de.png)

attributes and quotes:

![image](https://user-images.githubusercontent.com/15801806/83308590-661f0080-a207-11ea-9e57-ac6758e0d67f.png)

HTML comments:

![image](https://user-images.githubusercontent.com/15801806/83308683-99618f80-a207-11ea-8f4e-c9c36ffe3c33.png)

Semi-colons:

![image](https://user-images.githubusercontent.com/15801806/83308755-c746d400-a207-11ea-89cd-900095781fd0.png)

We could go through, find them all and up the contrast.  If we do it right that could be fine.

The reason I suggested a toggle is that we'd get pretty code for those that want it and readable code for people that need it, rather than having to compromise one of those.

**Comment by ahmadabdolsaheb** [comment]
ref #38954

**Comment by ahmadabdolsaheb** [comment]
ref #37166

**Comment by bbsmooth** [comment]
As user in the forums just [mentioned this issue](https://forum.freecodecamp.org/t/accessibility-contrast-ratio-for-hljs-built-in/502883).

**Comment by karenjoycelowe** [comment]
We could go through, find them all and up the contrast. If we do it right that could be fine.

The reason I suggested a toggle is that we'd get pretty code for those that want it and readable code for people that need it, rather than having to compromise one of those.

I'm the forum user bbsmooth mentioned. Ideally the readable code would be pretty as well. I don't know when I'll be ready to take on a toggle, but could do some search and destroy on the offending classes. Do we have control over the syntax highlighting in the forum for the Challenge Guide?

**Comment by moT01** [comment]
Closing as fixed.
