### ISSUE TITLE
Passing Algorithm Challenge, without actually writing an Algorithm.

### ISSUE THREAD

**Issue by JoshuaPelealu** [freeCodeCamp/freeCodeCamp#38950]
**Describe your problem and how to reproduce it:**
I was trying to help a user with their challenges for JavaScript Intermediate Challenge. Then I looked at his code and the challenge, and it seems like the user is not using an algorithm. They wrote the code a little bit wrong, but I corrected it for myself and tried it, and it worked. Without even doing any algorithm. They just look at the test saying that the function should return true if the string is a certain string, and took them one by one and return true or false depending on what the string is.

**Add a Link to the page with the problem:**
Here is the code to the solution without even using an algorithm:

https://www.freecodecamp.org/forum/t/passing-algorithm-challenges-without-using-algorithms/395736

**Tell us about your browser and operating system:**
* Browser Name: Chromium Edge 
* Browser Version: 83.0.478.37
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![img](https://user-images.githubusercontent.com/45566099/83257264-016d9280-a182-11ea-900c-fe5575b19c44.gif)

**Comment by nhcarrigan** [comment]
Realistically this could be done with any of the algorithm projects. Seems against the spirit of things, but it would work. 
I'd assume the code would get rejected if audited by the FCC team, but that takes time. I suppose we could add a test that looks for the `if (str == "eye)` type items.

**Comment by JoshuaPelealu** [comment]
Well, I thought of a solution where the test just say, `The function will work with any string` and give in another test in the background without telling what it needs to be.

**Comment by Sky020** [comment]
Whilst, ideally, the tests would be robust enough to prevent behaviour like this, we have discussed the fact that:
1) If a user _cheats_ in this way, they are _'shooting themselves in the foot'_.
 - The purpose of the curriculum is to teach.
 - The curriculum is free.
 - The certificate is counterfeit-able anyway.
2) No code-base is perfect, and someone will submit an _incorrect_ solution some-time-or-another.

Essentially, it takes effort to fake most of the tests, and we do not lose anything from someone else doing it.
I am not particularly bothered by the what the tests check for, now.

**Comment by JoshuaPelealu** [comment]
Ok, so if the're purposely cheating, it's just their fault. FCC is a free resource that people can use. If they do not use it accordingly, they're just wasting their time. Understand, thanks for the replies.
