### ISSUE TITLE
Preload video challenges

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#38955]
**Is your feature request related to a problem? Please describe.**
Opening a new video challenge takes slightly longer than I'd expect

**Describe the solution you'd like**
Since a user is likely to be going through the challenges sequentially, it would be good if as much as possible was loaded in the background while they worked on the current challenge.

**Describe alternatives you've considered**
I have not looked into this closely, yet, it's possible that there's not much that can be done.

**Additional context**
It's not painfully slow, but is noticeably slower than switching between classic challenges.

**Comment by raisedadead** [comment]
The player is an iframe embed that is controller by YouTube.

**Comment by ojeytonwilliams** [comment]
In that case any solution might be a bit hacky.  I'll leave this up for now, in case someone gets inspired.

**Comment by raisedadead** [comment]
Hi, 

We are closing old issues/pull-requests that we think are stale. If you need still need help with this or are fixing this, please open a fresh issue/pull-request.

Thanks for your understanding. 

Happy contributing.
