### ISSUE TITLE
Lack of visual feedback with no explanation in grid-template-areas challenge

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#38959]
Forum thread: https://www.freecodecamp.org/forum/t/possible-bug-in-a-lesson/396043

The challenge is asking the camper to make changes to the `grid-template-areas` string, but it has no effect because no `grid-area` is defined.

I think at least the challenge should explain that it has no effect just yet but that the next challenge will show how to use the `grid-template-areas` by using the `grid-area` property.

Personally I'd like to change the focus of the challenge to simply be having the camper write the `grid-template-areas` string using the example code as a guide. But I realize this will require changes to not only the challenge text but also the test and video which is a lot of effort for such a small correction.

**Comment by moT01** [comment]
I'm fine with adding a sentence at the bottom of the instructions. How about "This will not have any visual effect right now. In the next lesson, you will make one of the items use an area to see how it works."
