### ISSUE TITLE
RWDC - CSS: Flexbox - Tweet - Tests Not Registering Correct Change to Follow Button 

### ISSUE THREAD

**Issue by KaiReidCasey** [freeCodeCamp/freeCodeCamp#38957]
**Describe your problem and how to reproduce it:**

I have not been able to pass the test titled, "Your .follow-btn should have a display property set to flex." I can pass all of the other tests. I believe this is a bug.

I have tried adding "display: flex;" to the empty space reserved for doing so on  "header .follow-btn {" (line 18) and to "header .follow-btn button {" (line 22). I have tried creating a new CSS selector for just ".follow-btn" as well as refreshing the page, resetting the code, adding "display: flex;" to line 18 without making any other code changes or after passing all other tests, and opening a new tab and trying again there.

The follow button flickers onto the page briefly after I make any change to the code, however it is not visible even after resetting all code, or after adding what I believe to be the correct answers, unless I copy it to just above its current container, "<button>Follow</button>".  This may be related.

**Add a Link to the page with the problem:**

Responsive Web Design Certification (300 hours)
CSS Flexbox: Add Flex Superpowers to the Tweet Embed

https://www.freecodecamp.org/learn/responsive-web-design/css-flexbox/add-flex-superpowers-to-the-tweet-embed

**Tell us about your browser and operating system:**

* Browser Name:  Chrome
* Browser Version: I updated it to Version 83.0.4103.61 (Official Build) (64-bit) from an older version and repeated the above tests with the same results. I did not save the older version information.
* Operating System: Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

![Screenshot (394)](https://user-images.githubusercontent.com/9575844/83298115-de62d300-a1c1-11ea-9878-0c9047421e29.png)

**Comment by Sky020** [comment]
Hello there,

I notice you have a browser extension enabled with access to freecodecamp.org

In general, we recommend users disable all extensions with access to freeCodeCamp, as they can influence the tests. Also, freeCodeCamp is advertisement free. So, not need for an ad-block ;)

Disable the extension, refresh the page, and try again. Let us know if it works.

**Comment by KaiReidCasey** [comment]
That did it, thank you! It was the Adblock Plus extension. It's enabled on all of my sites by default and I hadn't had an issue before.

**Comment by multiwebinc** [comment]
Adblock and Adblock Plus are very common extensions (each report over 10 million installs installs in the Chrome store and over 10 million combined in the Mozilla store) and likely a disproportionate number of devs use them. Could you maybe consider changing the class name to something else like `follow-me-btn`? This should be fairly trivial.
