### ISSUE TITLE
Get Data from POST Requests

### ISSUE THREAD

**Issue by nansha3120** [freeCodeCamp/freeCodeCamp#38952]
can't get through the test. Challenge link:https://www.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/get-data-from-post-requests

My solution:
Link to live app:
https://heartbreaking-shimmering-stop.glitch.me
editable link:
https://glitch.com/edit/#!/join/730d4b1d-ce6c-4bc3-b330-334ecff974cc

**Comment by Sky020** [comment]
Hello there,

That does not appear to be the correct boilerplate for the _Basic Node and Express_ challenges.

In general, I recommend you open a topic on the [forum](https://www.freecodecamp.org/forum), as this is not an issue with the source code.

I am closing this issue. Thank you.
