### ISSUE TITLE
Scientific Computing with Python Projects - Budget App - README.md

### ISSUE THREAD

**Issue by sanityto** [freeCodeCamp/freeCodeCamp#38960]
**Describe your problem and how to reproduce it:**
There are two errors in README.md for the Budget App project.
* Description of the _transfer_ method has swapped texts that should be used as description for the transfer in source and destination Budget Categories. The relevant test attached.
>A transfer method that accepts an amount and another budget category as arguments. The method should add a withdrawal with the amount and the description **"Transfer from [Source Budget Category]"**. The method should then add a deposit to the other budget category with the amount and the description **"Transfer to [Destination Budget Category]"**.
```
  def test_transfer(self):
    self.food.deposit(900, "deposit")
    self.food.withdraw(45.67, "milk, cereal, eggs, bacon, bread")
    good_transfer = self.food.transfer(20, self.entertainment)
    actual = self.food.ledger[2]
    expected = {"amount": -20, "description": "Transfer to Entertainment"}
    self.assertEqual(actual, expected, 'Expected `transfer` method to create a specific ledger item in food object.')
    self.assertEqual(good_transfer, True, 'Expected `transfer` method to return `True`.')
    actual = self.entertainment.ledger[0]
    expected = {"amount": 20, "description": "Transfer from Food"}
    self.assertEqual(actual, expected, 'Expected `transfer` method to create a specific ledger item in entertainment object.')
```
* Description of the _check_funds_ method is inconsistent with the relevant test - test_check_funds() regarding what should be returned when amount is the same as balance.
>A check_funds method that accepts an amount as an argument. It returns **True if the amount is less than the balance** of the budget category and returns False otherwise.
```
def test_check_funds(self):
    self.food.deposit(10, "deposit")
    actual = self.food.check_funds(20)
    expected = False
    self.assertEqual(actual, expected, 'Expected `check_funds` method to be False')
    actual = self.food.check_funds(10)
    expected = True
    self.assertEqual(actual, expected, 'Expected `check_funds` method to be True')
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.dev/learn/scientific-computing-with-python/scientific-computing-with-python-projects/budget-app
https://repl.it/@freeCodeCamp/fcc-budget-app#README.md

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @sanityto. Great catch with the `check_funds` method.

The first issue you noticed was reported here and fixed yesterday: https://github.com/freeCodeCamp/CurriculumExpansion/issues/280#issuecomment-635650893

And I just went into the Readme and fixed the second issue with `check_funds`:  https://repl.it/@freeCodeCamp/fcc-budget-app#README.md
