### ISSUE TITLE
Data Analysis with Python Course - Numpy Operations - incorrect answer

### ISSUE THREAD

**Issue by sanityto** [freeCodeCamp/freeCodeCamp#38966]
**Describe your problem and how to reproduce it:**
None of the available answers are correct. Without the `5` second option (marked as solution) would have the right numbers.
>What is the value of `a` after you run the following code?:
```
a = np.arange(5)
a + 20
```
>Answers
```
[20, 21, 22, 24, 24]
[0, 1, 2, 3, 4, 5]
[25, 26, 27, 28, 29]
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.dev/learn/data-analysis-with-python/data-analysis-with-python-course/numpy-operations

**Comment by Sky020** [comment]
Confirmed. Thank you, for pointing this out. For whoever submits a PR for this, only the second answer option needs to be changed to:
```
[0, 1, 2, 3, 4]
```

**Comment by scissorsneedfoodtoo** [comment]
Thanks for catching this @sanityto. Please feel free to report any other issues you find and submit PRs to fix them if you're able to.

**Comment by niteshseram** [comment]
@scissorsneedfoodtoo I want to work on this

**Comment by niteshseram** [comment]
@scissorsneedfoodtoo I think the answer is also wrong. It should be option 1? Please do confirm me on this.

**Comment by scissorsneedfoodtoo** [comment]
@niteshseram, thanks for fixing this problem and helping us improve the curriculum! Also, congratulations on your first open source contribution. Looking forward to your next PR :+1: :+1:

**Comment by niteshseram** [comment]
@scissorsneedfoodtoo Thanks. Surely, I am looking forward to contribute more.
