### ISSUE TITLE
Stylistic change: Waypoint: Use jQuery to Modify the Entire Page

### ISSUE THREAD

**Issue by ParkinT** [FreeCodeCamp/FreeCodeCamp#3896]
In this particular lesson there is a sudden (and unexplained) switch from double-quotes to single-quotes in all the JQuery parameters.
This will, likely, be confusing to students and - although I suspect it was simply a mistake - it should be explained that either is acceptable.

**Comment by awesomeaniruddh** [comment]
Thanks for reporting the issue @ParkinT, but the waypoint uses double quotes (see attached screenshot)?

Nevertheless, I'll open a PR with a note in the waypoint ASAP. Thanks :)
![screenshot 1](https://cloud.githubusercontent.com/assets/5279150/10793553/594e96fe-7dcc-11e5-8778-67172d235dc6.png)

**Comment by ParkinT** [comment]
@awesomeaniruddh That screenshot illustrates my point.
Perhaps you misunderstood.

I am referring to the examples in the instructions.
Up to this point they were consistent and used double-quotes.  At this Waypoint the 'sample' in the instructions uses single-quotes.

**Comment by awesomeaniruddh** [comment]
Ah, I just noticed. Thanks for bringing that to my notice.

**Comment by bugron** [comment]
@awesomeaniruddh what's your progress on this?

**Comment by erictleung** [comment]
It looks like the single quotes in the instructions were changed to double quotes already. Maybe we should close this?

![image](https://cloud.githubusercontent.com/assets/2754821/12166307/d46ec298-b4d9-11e5-8c85-1cb165a298af.png)
