### ISSUE TITLE
Scientific Computing with Python Projects - Polygon Area Calculator - README.md

### ISSUE THREAD

**Issue by sanityto** [freeCodeCamp/freeCodeCamp#38961]
**Describe your problem and how to reproduce it:**
There's inconsistency between description of _get_picture_ method and relevant test. Description suggests to return _error_ when width or height is larger than 50, while test expects it also when the value is equal 50.
>get_picture: Returns a string that represents the shape using lines of "*". The number of lines should be equal to the height and the number of "*" in each line should be equal to the width. There should be a new line (\n) at the end of each line. **If the width or height is larger than 50, this should return the string: "Too big for picture."**.
```
    def test_big_picture(self):
        self.rect.set_width(50)
        self.rect.set_height(3)
        actual = self.rect.get_picture()
        expected = "Too big for picture."
        self.assertEqual(actual, expected, 'Expected message: "Too big for picture."')
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.dev/learn/scientific-computing-with-python/scientific-computing-with-python-projects/polygon-area-calculator
https://repl.it/@freeCodeCamp/fcc-shape-calculator#README.md

**Comment by scissorsneedfoodtoo** [comment]
Thank you for reporting this @sanityto.

In this case it seems like we can change the test (`self.rect.set_width(50)`) or the text in the readme to something like:

...If the width or height greater than or equal to 50, this should return the string: "Too big for picture.".

What do you think @beaucarnes?

**Comment by beaucarnes** [comment]
I just updated the test so it matched the instruction.
