### ISSUE TITLE
where can I find challenge code?

### ISSUE THREAD

**Issue by WAINGOR** [freeCodeCamp/freeCodeCamp#38971]
Hi all, I was interested to see how the coding challenges were actually built? Does anybody know where I can find the actual code of the js algorithmic challenges? Wherever I navigate to in the source code I cant seem to find anything except for .md formatted files.

**Comment by ojeytonwilliams** [comment]
Hi @WAINGOR.  The challenges are all stored as markdown, so if you're looking in curriculum\challenges, then you're looking in the right place.  Have a look at https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges if you want to learn more.  The contribute site is pretty comprehensive and tells you where you can look for extra info.
