### ISSUE TITLE
Python for Everybody - Objects: A Sample ClassPassed - indentation and incorrect options

### ISSUE THREAD

**Issue by mpinheir** [freeCodeCamp/freeCodeCamp#38977]
**Describe your problem and how to reproduce it:**
I believe that there are two issues on this exercise:
1-Exercise sample code indentation does not appear to be correct.
2-I believe that the correct solution is 2 and 4 but that option is not listed.

**Add a Link to the page with the problem:**
https://www.freecodecamp.dev/learn/scientific-computing-with-python/python-for-everybody/objects-a-sample-class

**Tell us about your browser and operating system:**
* Browser Name: 
Brave
* Browser Version: 
Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)
* Operating System: 
macOS Catalina - Version 10.15.4

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screen Shot 2020-05-31 at 11 10 54 AM](https://user-images.githubusercontent.com/8754015/83359501-6f0af180-a32f-11ea-93c8-40bcb011cceb.png)

**Comment by Sky020** [comment]
Thank you, for pointing this out. This has been:
Noticed in: #38931
and is closed by: #38953
