### ISSUE TITLE
Data Analysis with Python Projects - Demographic Data Analyzer - missing pyproject.toml

### ISSUE THREAD

**Issue by sanityto** [freeCodeCamp/freeCodeCamp#38978]
**Describe your problem and how to reproduce it:**
Demographic Data Analyzer project doesn't have `pyproject.toml` file to manage required packages (pandas in this case). There's `requirements.txt` file, but it seems that repl.it no longer uses it - 
[repl.it thread](https://repl.it/talk/ask/requirementstxt-not-working/34267) - and its presence, without the _currently expected_ `pyproject.toml` file, will end up with following error. 
>Looks like this project uses requirements.txt. To install dependencies on Repl.it please use pyproject.toml or the built in packager.

Attempt to use the build-in packager will in such case actually also result in error.

**Add a Link to the page with the problem:**
https://www.freecodecamp.dev/learn/data-analysis-with-python/data-analysis-with-python-projects/demographic-data-analyzer
https://repl.it/@freeCodeCamp/fcc-demographic-data-analyzer

**Comment by scissorsneedfoodtoo** [comment]
Hi @sanityto, thank you for bringing this to our attention. We went through all the projects and removed the `requirements.txt` files and made sure the `pyproject.toml` files are present.

Please feel free to reopen this issue if you notice other projects with this issue.
