### ISSUE TITLE
Data Analysis with Python Projects - Medical Data Visualizer - draw_cat_plot() / CatPlotTestCase

### ISSUE THREAD

**Issue by sanityto** [freeCodeCamp/freeCodeCamp#38989]
**Describe your problem and how to reproduce it:**
There appear to be inconsistency between `draw_cat_plot()` function and corresponding tests in `CatPlotTestCase`. `draw_cat_plot()` function returns plt, while `setUp` of the `CatPlotTestCase` expects function to return `fig` object.
>draw_cat_plot()
```
  # Do not modify the next two lines
  plt.savefig('catplot.png')
  return plt
```
>CatPlotTestCase
```
    def setUp(self):
        self.fig = medical_data_visualizer.draw_cat_plot()
        self.ax = self.fig.axes[0]
```
Due to difference tests in the `CatPlotTestCase` ends up in exception.
```
======================================================================
ERROR: test_bar_plot_number_of_bars (test_module.CatPlotTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/fcc-medical-data-visualizer/test_module.py", line
 10, in setUp
    self.ax = self.fig.axes[0]
TypeError: 'function' object is not subscriptable

======================================================================
ERROR: test_line_plot_labels (test_module.CatPlotTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/fcc-medical-data-visualizer/test_module.py", line 10, in setUp
    self.ax = self.fig.axes[0]
TypeError: 'function' object is not subscriptable

----------------------------------------------------------------------
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.dev/learn/data-analysis-with-python/data-analysis-with-python-projects/medical-data-visualizer
https://repl.it/@freeCodeCamp/fcc-medical-data-visualizer#medical_data_visualizer.py
https://repl.it/@freeCodeCamp/fcc-medical-data-visualizer#test_module.py

**Comment by beaucarnes** [comment]
Thanks for catching this @sanityto. I just fixed it.
