### ISSUE TITLE
Data Analysis with Python Projects - Page View Time Series Visualizer - test_box_plot_labels

### ISSUE THREAD

**Issue by sanityto** [freeCodeCamp/freeCodeCamp#38988]
**Describe your problem and how to reproduce it:**
`test_box_plot_labels` in the `test_module.py` has expected ylabel on ax1 and ax2 as 'Page Views'. However if it's something else, the error will suggest that the correct label is 'Average Page Views'.
```
        actual = self.ax1.get_ylabel()
        expected = "Page Views"
        self.assertEqual(actual, expected, "Expected box plot 1 ylabel to be 'Average Page Views'")
```
```
        actual = self.ax2.get_ylabel()
        expected = "Page Views"
        self.assertEqual(actual, expected, "Expected box plot 1 ylabel to be 'Average Page Views'")
```

**Add a Link to the page with the problem:**
https://www.freecodecamp.dev/learn/data-analysis-with-python/data-analysis-with-python-projects/page-view-time-series-visualizer
https://repl.it/@freeCodeCamp/fcc-time-series-visualizer#test_module.py

**Comment by scissorsneedfoodtoo** [comment]
@sanityto, awesome, thank you for catching this. I'll go to the project boilerplate and fix this now.

**Comment by sanityto** [comment]
@scissorsneedfoodtoo Yes, it looks fixed now.

**Comment by huyenltnguyen** [comment]
I'm closing the ticket as the issue has been fixed. Thanks for reporting it, @sanityto
