### ISSUE TITLE
Boilerplate default to master

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#38987]
This has been discussed a bit before, so this issue is just to keep track of things.

https://github.com/freeCodeCamp/boilerplate-mongomongoose/pull/24 is an example where a pull request was created accidentally due to the default branch being `gomix` not `master`.  To simplify the development process for users that want to create their projects with tools other than Glitch, I think we should switch the default branches to `master`.

@jeremyfiel any thoughts on this?  I know you've spent some time looking at the projects and possibilities for improving the process.  Could we do this independently of what you've been considering?

**Comment by jeremyfiel** [comment]
@ojeytonwilliams  I don't believe changing to master will have any ill effects. I also haven't seen any push back on the previous PR we changed for advanced node. {freeCodeCamp/boilerplate-advancednode/pull/9}

**Comment by moT01** [comment]
Closing in favor of the tracker I linked above.
