### ISSUE TITLE
Convert all video questions to markdown style?

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#38991]
The questions in the video challenges are a mix of markdown and html. [Some use markdown](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/build-your-own-functions.english.md) - and [some use html style](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/08-data-analysis-with-python/numpy/basics-of-numpy.english.md).

This issue is for a discussion on if we want to convert them all to use markdown and possibly remove all the references of html availability in the documentation.

There's certainly cases where formatting with markdown makes the question harder to read. If the question doesn't have any code or html tags, the only reason to use the markdown format (all the `|`'s) is to just make it consistent and maybe keep some confusion down when people come across the different versions.

**Comment by Sky020** [comment]
Personally, I find writing and reading any challenges with code much simpler and easier with MarkDown. I am not bothered, if the challenges without code in the question/answer use HTML, but then we have the situation without consistency.

**Comment by ojeytonwilliams** [comment]
It's a good question.  I think it would help to convert challenges like the one Tom linked to, as they are (at least to my eyes) needlessly hard to read.

As for the less obvious stuff, I've created a PR, https://github.com/freeCodeCamp/freeCodeCamp/pull/38992,  that deals with one confusing issue - namely that you had to quote numbers for the challenge to be parsable.  That leaves weird edge cases like

```yml
question:
  answers:
  - *5*
```
which throws
```
  unidentified alias "5*" at line 6, column 8:
      - *5*
           ^ in file ...
```

but that's unlikely to come up much.  

Finally `"word"`, `'word'` and `word` all just parse to `word`, while doing the same with `|` gives you 
![image](https://user-images.githubusercontent.com/15801806/83543347-8cd98180-a4fc-11ea-8e2b-6a18928128c0.png).  How confusing is that to everyone?

**Comment by moT01** [comment]
I vote to just make them all markdown. It gives us a standard that gives people a concrete way to make them. And hopefully stop anyone from having to decide, 'should this use markdown', or 'can I leave it html'. Everyone will have an answer to that, and hopefully be on the same page.

**Comment by ojeytonwilliams** [comment]
People seem broadly in favour, so PRs are welcome.  There's no need to change all the challenges in one go, but if anyone is planning to do a large batch please comment here (to avoid work duplication).

**Comment by JapneetSingh5** [comment]
I would love to do it, will appreciate some guidance !

**Comment by ojeytonwilliams** [comment]
@JapneetSingh5 please do!  If you're worried about the 'first timers welcome' label, I added that to indicate that it should not be too hard, not that *only* first timers should submit PRs.

**Comment by JapneetSingh5** [comment]
Awesome, I’ll get to work then!

**Comment by JapneetSingh5** [comment]
I am experiencing failed build tests.

**Comment by pulkitgovrani** [comment]
is it still open. If it is open then may i work on this

**Comment by ojeytonwilliams** [comment]
@JapneetSingh5 is https://github.com/freeCodeCamp/freeCodeCamp/pull/39022 intended to convert all the challenges?  If not, could you leave a note here? 

@pulkitgovrani you're welcome to work on this, but it could save time to wait on @JapneetSingh5's response.

**Comment by JapneetSingh5** [comment]
im working on 03-frontend roght now, we can divide folders i think

**Comment by ojeytonwilliams** [comment]
Great stuff.  Might be worth chatting on Gitter/discord to co-ordinate.  As you wish.

**Comment by JapneetSingh5** [comment]
I'm really sorry for the delay on this, I will open a pull request next week for sure.
