### ISSUE TITLE
JS concatenation example typo

### ISSUE THREAD

**Issue by sesamsys** [freeCodeCamp/freeCodeCamp#39007]
**Describe your problem and how to reproduce it:**
Example on the page has a double space instead of a single.

`var ourStr = "I come first._" + "I come second."
// ourStr is "I come first.__I come second."`

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/concatenating-strings-with-plus-operator

**Tell us about your browser and operating system:**
* Browser Name: Safari
* Browser Version: 13.1.1
* Operating System: macOS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="620" alt="Skjermbilde 2020-06-04 kl  21 13 12" src="https://user-images.githubusercontent.com/6814068/83802927-e9c76a00-a6ab-11ea-8c9d-3f5040d469c3.png">

**Comment by Sky020** [comment]
I can confirm this. Thank you, for spotting it, and pointing it out.

**Comment by nhcarrigan** [comment]
Okay, I believe I have corrected this error.
