### ISSUE TITLE
New certificates can be claimed whiteout submitting required projects on .dev 

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#39002]
Some users can claim python, new QA, and new infosec certifications without  submitting their required projects on .dev.

It seems the api does not find the cert challenge and proceeds by setting the related cert flag on the user object to true. 

The issue can be resolved by reseeding the db locally.

I cannot reproduce this issue at the moment, but I will keep this open in case other users are experiencing the same issue.

**Comment by nhcarrigan** [comment]
Hello!

I tested this issue, and I **was** able to claim the certifications without completing the projects.

**Comment by ojeytonwilliams** [comment]
@nhcarrigan could you check if you can see the certification after claiming it?  I'm just wondering if this is purely a client-side issue.

**Comment by nhcarrigan** [comment]
I am able to see the four certificates I could claim, yes.

**Comment by ojeytonwilliams** [comment]
Thanks for checking that.

> It seems the api does not find the cert challenge and proceeds by setting the related cert flag on the user object to true.

> The issue can be resolved by reseeding the db locally.

In that case, while it seems likely that it will fine if the database is migrated, the api should definitely default to rejecting certifications it does recognise.

**Comment by code-with-garvit** [comment]
Yes We Can Claim Python Certification Without submitting the Projects.

**Comment by Khrees2412** [comment]
that's really serious
