### ISSUE TITLE
Cypress failing to install during ci

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39003]
For example:
https://github.com/freeCodeCamp/freeCodeCamp/runs/737483891

While Cypress installation is intended to be skipped locally, https://github.com/freeCodeCamp/freeCodeCamp/pull/38660, it needs to be installed for ci.  It's possible this is a caching issue, but we might simply need to provide `CYPRESS_INSTALL_BINARY` during ci.  Hopefully it's the former, since we don't want to have to keep updating the environment variables every time we update Cypress.

**Comment by raisedadead** [comment]
I think this will be addressed in the linked PR. Mind taking a look.
