### ISSUE TITLE
Save oauth method used in signin page to localStorage

### ISSUE THREAD

**Issue by BerkeleyTrue** [FreeCodeCamp/FreeCodeCamp#3901]
We'd like to reduce the amount of accidental account creation when a camper forgets which oauth they use. 

We'd like to store in localStorage which oauth a camper uses and highlight the button the next time the camper visits the sign in page.

**Comment by iTypeSlow** [comment]
you could set something up to send new campers an email with their user info in it.

**Comment by bugron** [comment]
We can store an identifier of the last login method (for example the specific class name, like `btn-linkedin`, or the link, like `/auth/linkedin`) and then try to read that value from `localStorage` and highlight the appropriate button.
![](http://i.imgur.com/g4fN3Fl.png)
@BerkeleyTrue what do you think about this idea?

**Comment by BerkeleyTrue** [comment]
:+1:
