### ISSUE TITLE
Missing SameSite header in CDN

### ISSUE THREAD

**Issue by Twaha-Rahman** [freeCodeCamp/freeCodeCamp#39015]
**Describe the bug**

All the modern browsers have started to enforce the `SameSite` header for security reasons. Previously, `None` used to be the default value, but recent browser versions made `Lax` the default value to have reasonably robust defense against some classes of [cross-site request forgery (CSRF)](https://developer.mozilla.org/en-US/docs/Glossary/CSRF) attacks.

FCC doesn't specify the `SameSite` header and the current browsers default to `None`
 but in the near future this will change. Browsers in the near future will default to `Lax`, so to ensure the expected behaviour, we need to add the `SameSite` header with the `Secure` header.

**To Reproduce**
1. Open any page or resurce that uses the CDN
2. Open the console (in Chrome) and see the warning

**Expected behavior**

The expected behaviour is to see no warning and the CDN should work as normal.

**Screenshots**

Here's a screenshot of the warning ->

![Capture](https://user-images.githubusercontent.com/39026437/83936829-0cab6880-a7e9-11ea-9838-b703b097a70e.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 (64 Bit)
 - Browser: Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Comment by Twaha-Rahman** [comment]
I have made a PR that fixes this issue, it can found here -

https://github.com/freeCodeCamp/cdn/pull/51

**Comment by nhcarrigan** [comment]
I can confirm the presence of the bug. 
![image](https://user-images.githubusercontent.com/63889819/83936888-c4eef780-a77c-11ea-9f5a-7ab351f701f2.png)

OS: Windows 10 (64 Bit)
Browser: Chrome
Version: 83.0.4103.97 (Official Build) (64-bit)

**Comment by ojeytonwilliams** [comment]
https://blog.chromium.org/2020/05/resuming-samesite-cookie-changes-in-july.html?m=1 Google's planning on rolling this out by the 14th of July, so we have a deadline.

**Comment by ojeytonwilliams** [comment]
Is there a quick way of auditing the site to see if any other resources need this header specifying?

**Comment by raisedadead** [comment]
Hi @Twaha-Rahman 

Thanks a lot for the report. 

Please note while we are scincerely grateful for the report and the PR. We highly recommend reporting security issues to our dedicated email for these. You would have been presented with this template when opening an issue:

![image](https://user-images.githubusercontent.com/1884376/83941089-260edd80-a806-11ea-906d-66a66682fb1e.png)

This gives us a chance to brace ourselves quickly :)

I have left review comments on the PR.

> Is there a quick way of auditing the site to see if any other resources need this header specifying?

Yes, we would have public deploy-previews. It would not be matched to the domain though.

**Comment by Twaha-Rahman** [comment]
@raisedadead I've updated the PR accordingly!

**Comment by ojeytonwilliams** [comment]
@Twaha-Rahman @nhcarrigan which pages did you see the warning on?

**Comment by nhcarrigan** [comment]
I get the warning on all of the /news pages, it seems.

**Comment by Twaha-Rahman** [comment]
> @Twaha-Rahman @nhcarrigan which pages did you see the warning on?

I can see the warning on the **Test Suite**.

**Comment by ahmadabdolsaheb** [comment]
The issue seems to be resolved.
I would appreciate it if you could test, confirm, and close this issue accordingly. Thank you.

**Comment by nhcarrigan** [comment]
Hey @ahmadabdolsaheb,

Is the fix deployed on the live site? Because I am still seeing the error on the [/news](https://www.freecodecamp.org/news/) page.
Or was there somewhere else I should test the fix?

**Comment by ahmadabdolsaheb** [comment]
@nhcarrigan, thanks for looking into this.

There is similar issue with http://runkit.com/ which is a script injected in ghost. 

It seems the issue with the freecodecamp.dev cookie has been resolved. can you confirm that?
![image](https://user-images.githubusercontent.com/4591597/83951902-a69d0080-a83d-11ea-9864-b0f31da1168a.png)

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/83951967-55175600-a7ea-11ea-90d0-162fe50b2515.png)
On the dev/news page, I get the runkit cookie but also show a freecodecamp.org cookie.

**Comment by ahmadabdolsaheb** [comment]
I see, how about freecodecamp.org/news?

**Comment by nhcarrigan** [comment]
That one appears to have been fixed now.

**Comment by imabp** [comment]
It is still there on /news 
![image](https://user-images.githubusercontent.com/53480076/83953631-6babc480-a85f-11ea-8194-9dc9562e9e5e.png)

**Comment by Twaha-Rahman** [comment]
Shouldn't the warning appear in any site that uses the CDN? From my understanding, the CDN is missing header which show the warning. So, any FCC site (even the **Test Suite**) will show the warning cause it uses the CDN
