### ISSUE TITLE
Formatting iconsistency in issue template

### ISSUE THREAD

**Issue by Twaha-Rahman** [freeCodeCamp/freeCodeCamp#39017]
**Describe the bug**

There's some formatting inconsistency in the issue templates.

**To Reproduce**
1. Try to create an issue
2. Check the issue template and you'll find the formatting inconsistency

**Screenshots**

![Capture](https://user-images.githubusercontent.com/39026437/83937514-fbfdf100-a7ee-11ea-8357-8e892ddaaa33.PNG)

**Comment by nhcarrigan** [comment]
Good catch @Twaha-Rahman! Also want to thank you for helping a new contributor with the process of submitting a pull request.
