### ISSUE TITLE
New Forum Header - "Curriculum" obscures menus on mobile

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#39018]
**Describe the bug**
The new forum header seems to have added a link to the curriculum - this link remains on top of the view when the forum menu is opened, obscuring a couple of links, when the forum is viewed from a mobile device.

**To Reproduce**
1. Go to the [forums](https://freecodecamp.org/forum)
2. Click on '"menu" or "profile" to open a sidebar.
3. "Curriculum" link is rendered on top of the sidebar text.

**Expected behavior**
The sidebar should cover the "Curriculum" text as it does the "Search", "Menu", and "Profile" texts.

**Screenshots**
![image](https://user-images.githubusercontent.com/63889819/83946805-eaedb980-a7c7-11ea-80cb-de02663cdf0b.png)

**Smartphone (please complete the following information):**
 - Device: LG G7 ThinQ
 - OS: Android 9 (Kernel 4.9.112)
 - Browser: Chrome
 - Version:  81.0.4044.138

**Additional context**
This issue also occurs on the PWA version.

**Comment by ahmadabdolsaheb** [comment]
@nhcarrigan, thanks for reporting this issue.
I am closing this issue as I have updated the themes with a fix.
Feel free to reopen if the issue persists.
