### ISSUE TITLE
assignment test not passing

### ISSUE THREAD

**Issue by Advitya-sharma** [freeCodeCamp/freeCodeCamp#39012]
I was doing jQuery assignment questions and I faced a bug

here's how to reproduce it 
1> submit a assignment
2> press Esc
3> submit the assignment (you code which is correct is still there)
> a test will fail 
>if test does not fail try repeating step 1,2 and 3 

I'm facing this now in jQuery questions but may be present elsewhere 
https://www.freecodecamp.org/learn/front-end-libraries/jquery/disable-an-element-using-jquery

**Tell us about your browser and operating system:**
* Browser Name: vivaldi
* Browser Version: latest
* Operating System: windows 10

**Comment by Twaha-Rahman** [comment]
I could reproduce the issue even in Chrome. This is not a **Vivaldi** specific problem.

**Comment by Sky020** [comment]
Same problem as #38980.

**Comment by ojeytonwilliams** [comment]
Thanks for the report and checks, it seems like this problem affects several jQuery challenges.  We should track them in one place, though, so I'm closing this issue.
