### ISSUE TITLE
Rename Full Stack certification to Legacy Full Stack certification

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/freeCodeCamp#39013]
Once https://github.com/freeCodeCamp/freeCodeCamp/pull/38995 is merged, the settings page will describe how to claim a Legacy Full Stack certification.

However, if you claim the Legacy Full Stack certification, it will show as a Full Stack certification instead. This is a reminder that we need to change this before the new [2020 Full Stack Development Certification](https://github.com/freeCodeCamp/freeCodeCamp/issues/38943) is created.

Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/38934 and https://github.com/freeCodeCamp/freeCodeCamp/issues/38943.

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo I am assigning this to you, if its all the same considering you have worked closest to this in the last PRs.

**Comment by jacktnkr** [comment]
Are there any plans to offer a new "full stack" cert? Without "Legacy" stamp?   Legacy means and sounds outdated according to my understanding. :(
