### ISSUE TITLE
Machine Learning with Python Projects - Linear Regression Health Costs Calculator - wrong notebook link

### ISSUE THREAD

**Issue by sanityto** [freeCodeCamp/freeCodeCamp#39028]
**Describe your problem and how to reproduce it:**
Notebook linked from the project page contains full solution for the project.

**Add a Link to the page with the problem:**
https://www.freecodecamp.dev/learn/machine-learning-with-python/machine-learning-with-python-projects/linear-regression-health-costs-calculator
https://colab.research.google.com/drive/1h6SMDpC6o-6TFsgdizb3tk5zgE_DYWEo

**Comment by scissorsneedfoodtoo** [comment]
Thanks for catching this @sanityto.

Could you take a look at this @beaucarnes?

**Comment by beaucarnes** [comment]
I just made a PR adding in the correct link.
