### ISSUE TITLE
Verbiage change for MongoDB and Mongoose/Install and Set Up Mongoose

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#39020]
**Describe your problem and how to reproduce it:**
A couple of concerns were brought up in the Discord server regarding the verbiage on this challenge. 

First, the language "make sure no space exists between both the variable and the `=` and the value and `=`" is not particularly clear, and could possibly be re-written to something like "make sure no space exists between the variable, the `=`, and the value."

Second, it seems that Glitch has added a GUI to the .env file which is confusing some users. We could either add text to the instructions to say "We recommend you click `plaintext` to switch the .env file to a text view", or change the instructions to match Glitch's format. I definitely recommend the first option, as it would be more universal to other IDE platforms. This change would likely need to be made in a few places, though.

**Add a Link to the page with the problem:**
[Install and Set Up Mongoose](https://www.freecodecamp.org/learn/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: 
* Operating System: Windows 10 Home 1909

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Glitch's new GUI
![image](https://user-images.githubusercontent.com/63889819/83962098-0e0f7c00-a84f-11ea-9779-762d41cfbfe6.png)

**Comment by Twaha-Rahman** [comment]
I agree. The instructions can be made simpler. Also, we should teach how to use the proper syntax in `.env` file.... not the GUI that Glitch offers.
