### ISSUE TITLE
Resolution issue swithcing between phone and computer

### ISSUE THREAD

**Issue by abacaxication** [FreeCodeCamp/FreeCodeCamp#3903]
Challenge [Waypoint: Say Hello to HTML Elements](http://freecodecamp.com/challenges/waypoint-say-hello-to-html-elements#?solution=) has an issue.
User Agent is: <code>Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; InfoPath.3; .NET4.0C; .NET4.0E; MS-RTC LM 8)</code>.
Please describe how to reproduce this issue, and include a screenshots if possible.

Hi. I started this account on my phone, but switched to my laptop. the resolution seems to have changed. My profile pic header takes up half the page and theres no coding dialog box, and exercise instructions seem to be to the far right and far left of the page.

**Comment by benmcmahon100** [comment]
Hey @abacaxication we sadly can't support Internet explorer right now. It also seems that you are on quite an old version of IE. I'd recommend chrome or firefox and that issue will disappear

**Comment by BerkeleyTrue** [comment]
@abacaxication Can you post some screenshots?
