### ISSUE TITLE
nodemon restarting due to changes but isn't starting node file.js and doesn't reflect the changes but gives the same output.

### ISSUE THREAD

**Issue by boranaveen007** [freeCodeCamp/freeCodeCamp#39033]
nodemon restarting due to changes... but isn't starting `node file.js` and also doesn't reflect the changes made in the file.js but gives the same output as before.
tried installing nodemon locally and globally.
please help!
thank you.

![nodemon problem](https://user-images.githubusercontent.com/49654880/84167890-6aafa880-aa94-11ea-8bfc-b31c231ec7e5.jpeg)
![nodemon](https://user-images.githubusercontent.com/49654880/84167895-6c796c00-aa94-11ea-83c8-96ee66dee6d1.jpeg)

**Comment by raisedadead** [comment]
Thanks for reporting, this tracker is for issues related to the freeCodeCamp.org's platform only, if you need help with the curriculum please reachout to the [community forum](https://www.freecodecamp.org/forum) instead.
