### ISSUE TITLE
Npm start gives my this error

### ISSUE THREAD

**Issue by lolleri200** [freeCodeCamp/freeCodeCamp#39037]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactnative@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the reactnative@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ahmadabdolsaheb** [comment]
You would need to `npm run develop`.

Please refer to the [docs](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally) for setting up freecodecamp locally.

I am closing this issue for now. Feel free to reopen if this issue has not been resolved on your side.
