### ISSUE TITLE
Scaled images on /news

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39043]
**Describe the bug**
Unnecessarily large images are being served on the main /new page.

**To Reproduce**
Steps to reproduce the behaviour (on a > 768px wide screen):
1. Go to https://www.freecodecamp.org/news/
2. Inspect an image next to an article
3. See that the width on the screen is 283px
4. Check the downloaded image
5. See that it's 1000px wide

**Expected behavior**

The image served should be roughly 283 by 166px.

I think what's happening is that it's getting the wrong hint from `sizes`.  For large screens only a relatively small thumbnail is shown, but on small screens it stretches across most of the screen, so needs a larger image.

**Screenshots**
Large screen, small image:
![image](https://user-images.githubusercontent.com/15801806/84297168-63000a80-ab4d-11ea-89c2-a462526694ad.png)

Small screen, large image:
![image](https://user-images.githubusercontent.com/15801806/84297241-8034d900-ab4d-11ea-94e7-3ba2fd2e573f.png)

**Comment by darek-grund** [comment]
@ojeytonwilliams the issue was indeed problem with incorrect hints from `sizes` attribute. I've created PR to `freeCodeCamp/news-theme` that fixes this issue

**Comment by ojeytonwilliams** [comment]
Thanks @darek-grund that PR looks good.

As noted in that PR, and in the [Ghost docs](https://ghost.org/docs/api/v3/handlebars-themes/responsive-images/#compatibility), images that are hosted on Unsplash will not get scaled.  If possible, that is something we should address.

**Comment by darek-grund** [comment]
@ojeytonwilliams I was not aware you are planning to host images on Unsplash. My fix will work as long as there are images with different sizes provided in `srcset` attribute. In other words it will automatically work with what you currently have on https://www.freecodecamp.org/news/ - in `srcset` there are already urls to images of different sizes. Looking at the urls it seems like created by Ghost.

Ghost will automatically create images for different resolutions on the fly. But if you are planning to use third party hosting service then you need to somehow create these images yourself and provide urls in `scrset`. I may be able to help with that, but I need to know more details as this is broader topic.

**Comment by ojeytonwilliams** [comment]
@darek-grund I think it's down to individual authors to pick images to go with their articles.  Either way, there are currently Unsplash images on various articles.

And, yes, it would definitely have to be handled differently for those images, since Ghost will not do it automatically.  However, Unsplash does let you scale the images via a query parameter
`w=200`
![image](https://images.unsplash.com/photo-1508004680771-708b02aabdc0?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=200&fit=max&ixid=eyJhcHBfaWQiOjExNzczfQ)
vs
`w=400`
![image](https://images.unsplash.com/photo-1508004680771-708b02aabdc0?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjExNzczfQ)

so in principle that could be made use of.

**Comment by darek-grund** [comment]
@ojeytonwilliams - generating images for different resultions is just first step - it's great we already have that possibility, but make Ghost use the images is another.
Is anyone working on how to use Unsplash images in freeCodeCamp news page? If not, I would be happy to help with that issue. Le me know if you are interested and we can discuss it in more details.

**Comment by ahmadabdolsaheb** [comment]
@darek-grund, thank you for the help. Please go ahead.

**Comment by ahmadabdolsaheb** [comment]
It might be a good first step to go through https://forum.ghost.org/ posts and ask a question there to see if a solution has already been developed for this issue.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
