### ISSUE TITLE
video is missing footage – python for everybody

### ISSUE THREAD

**Issue by borntofrappe** [freeCodeCamp/freeCodeCamp#39041]
**Describe your problem and how to reproduce it:**

The video for the challenge _Python for Everybody - Relational Databases: Relationship Building_ cuts abruptly before the instructor has had a chance to finish the discourse.

**Add a Link to the page with the problem:**

https://www.freecodecamp.dev/learn/scientific-computing-with-python/python-for-everybody/relational-databases-relationship-building

**Additional notes**

Compared to the original video, it seems there is a single minute missing, starting roughly at **10:32:49** and ending at the **10:33:45** mark.

https://youtu.be/8DvywoWv6fI?t=37969

**Comment by beaucarnes** [comment]
I just uploaded the complete video and then made a PR with the videoID.

**Comment by borntofrappe** [comment]
That was remarkably quick @BeaCodes 

I've watched the video at the new URL and it works swimmingly 👍
