### ISSUE TITLE
Issue with answers on How Neural Networks Work - How Deep Neural Networks Work

### ISSUE THREAD

**Issue by thecodingaviator** [freeCodeCamp/freeCodeCamp#39048]
**Describe your problem and how to reproduce it:**
On [this](https://www.freecodecamp.dev/learn/machine-learning-with-python/how-neural-networks-work/how-deep-neural-networks-work) Python curriculum challenge, the correct answer is already selected. Just so we're having the learner do something, I guess either rearranging the options or at the very least not having the correct option already selected should be made.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/34807532/84363016-bd4fa880-abeb-11ea-8922-998f40bc9447.png)

**Comment by Sky020** [comment]
I assume this applies to all of the Video Challenges with a solution of **1**?

**Comment by thecodingaviator** [comment]
It should be that case, even though I haven't personally verified it

**Comment by ojeytonwilliams** [comment]
Could we avoid the problem by leaving the radio buttons unselected at the start?  It's slightly weird UX, since people expect radio buttons to always have one selected, but it should not be too confusing in the context of a multiple choice question.

**Comment by thecodingaviator** [comment]
> Could we avoid the problem by leaving the radio buttons unselected at the start? It's slightly weird UX, since people expect radio buttons to always have one selected, but it should not be too confusing in the context of a multiple choice question.

It is a valid workaround

**Comment by ahmadabdolsaheb** [comment]
> Could we avoid the problem by leaving the radio buttons unselected at the start? It's slightly weird UX, since people expect radio buttons to always have one selected, but it should not be too confusing in the context of a multiple choice question.

That works. Unselected radio buttons seems to be a convention for multiple choice questions. 
Additionally, we could display the multiple choice questions as a button group and avoid having the users select the multiple choice question and click on the Check Your Answer.

**Comment by ojeytonwilliams** [comment]
> we could display the multiple choice questions as a button group and avoid having the users select the multiple choice question and click on the Check Your Answer.

Just to check, do you mean: remove Check Your Answer and have the modal pop up as soon as the user clicks on the correct answer?

Also, since we're discussing UX, keyboard navigation is a bit tricky.  There's no visible indicator when you have the answers selected.

**Comment by ahmadabdolsaheb** [comment]
>Just to check, do you mean: remove Check Your Answer and have the modal pop up as soon as the user clicks on the correct answer?

Yes, what do you think?

**Comment by ojeytonwilliams** [comment]
Sounds good.  The only concern I have is that we don't want to encourage people to just guess. However, forcing them click back and forth between the radio buttons and 'Check your answer' probably does not solve that and it's definitely irritating.

**Comment by ahmadabdolsaheb** [comment]
For now, let us unselect radio buttons and we take it from there.

**Comment by thecodingaviator** [comment]
@ojeytonwilliams w.r.t https://github.com/freeCodeCamp/freeCodeCamp/issues/39048#issuecomment-647338171 , should we leave this issue open?

**Comment by ojeytonwilliams** [comment]
@thecodingaviator since it's already been moved to 'done' on the project board, I'll create a new feature request to track the remaining points.
