### ISSUE TITLE
Improve description for Chai QA testing challenges

### ISSUE THREAD

**Issue by crandalj** [freeCodeCamp/freeCodeCamp#39047]
**Describe your problem and how to reproduce it:**
The Chai challenges start off with [challenge link](https://www.freecodecamp.org/learn/information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/learn-how-javascript-assertions-work) and it tells you to make asserts but not where exactly.
The glitch link does allow you to make a copy of the project, however it is unclear where you start. I navigated around the project and the README didn't have any hints as to where these asserts were supposed to be taking place.

The README:

> FCC Test Challenge Prototype
> QA with mocha & chai

When you click on the hint button, then you get told where to actually start. 

> Problem Explanation
To begin, locate the file “tests/1_unit_tests.js”.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/learn-how-javascript-assertions-work 

**Suggestion**
Add the two file locations to the introduction to the challenge section, to the challenge pages, and on the README.
In addition to this, there are issues occasionally where you may need to submit multiple times for it to properly detect, either due to glitch issues or something else. So it may be worth adding a mention of this, at least in the section introduction page.

**Comment by scissorsneedfoodtoo** [comment]
@crandalj, thanks a lot for these details and your helpful suggestions. We'll take all of this into consideration while we update this project.

**Comment by jessanova** [comment]
It looks like this is fixed by https://github.com/freeCodeCamp/boilerplate-mochachai/pull/16/files.

**Comment by moT01** [comment]
This should be fixed with some recent changes to these projects. The instructions are [now on the website](https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-and-testing-with-chai/learn-how-javascript-assertions-work). I think it's safe to close this. Thanks and happy coding 🎉
