### ISSUE TITLE
Lesson: ES6: Write Arrow Functions with Parameters - allows pass with incorrect code

### ISSUE THREAD

**Issue by Teredell** [freeCodeCamp/freeCodeCamp#39049]
**Describe your problem and how to reproduce it:**
The lesson on page will allow the user to pass the test using the following answer;
const myConcat = (arr1, arr2) => arr1.push(arr2);
console.log(myConcat([1, 2], [3, 4, 5]));

And the console below displays "3"
Further testing reveals it will also pass with the following code;
const myConcat = () => {};
console.log(3);
*The HINT answer also advises to use the .concat method, which likely hasn't been presented to the user before.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/write-arrow-functions-with-parameters

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 77.0.1 (64-bit)
* Operating System: Linux Mint 19.3 Tricia
![Screenshot_2020-06-11 freeCodeCamp org](https://user-images.githubusercontent.com/44662148/84372356-90ac8880-ac0d-11ea-922d-d4442032dd99.png)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by bjorno43** [comment]
Confirmed. It you really want to go crazy and break the thing, even this is accepted:

```
const myConcat = eval("(func"+"tion(){})");
```

**Comment by ojeytonwilliams** [comment]
I think this is the culprit:

```yml
  - text: <code>myConcat()</code> should return <code>[1, 2, 3, 4, 5]</code>.
    testString: assert(() => { const a = myConcat([1], [2]); return a[0] == 1 && a[1] == 2; });
```

That assert passes no matter what. If it's changed to

```yml
  - text: <code>myConcat([1, 2], [3, 4, 5])</code> should return <code>[1, 2, 3, 4, 5]</code>.
    testString:  assert.deepEqual(myConcat([1, 2], [3, 4, 5]), [1, 2, 3, 4, 5]);
```

it should be fine.  @Teredell @bjorno43 seem reasonable?  If you think so, I'll open this up for first-timers.

**Comment by bjorno43** [comment]
@ojeytonwilliams Yup. Seems fine to me. Go ahead and give it to first-timers.

**Comment by rajatgupta24** [comment]
Hey,
I'm a beginner and wanted to do this can you please help me. 

Thank You.

**Comment by Ieahleen** [comment]
> Hey,
> I'm a beginner and wanted to do this can you please help me.
> 
> Thank You.

if you want to contribute, you should start with [the contributing docs](https://contribute.freecodecamp.org/#/index?id=our-open-source-codebase), and if need help you are welcome to ask in the [gitter contributors room](https://gitter.im/FreeCodeCamp/Contributors?source=orgpage), [discord channel](https://discord.com/channels/692816967895220344/715074489422970962) or [contributors subforum on the forum](https://www.freecodecamp.org/forum/c/contributors)

**Comment by ojeytonwilliams** [comment]
@rajatgupta24 we'd like to reserve this for first time contributors for a bit.  If none of them takes it, we'll open it up to the rest of the community.

**Comment by rajatgupta24** [comment]
@ojeytonwilliams sure 😊.

**Comment by faraz16iqbal** [comment]
Is this issue still open?

**Comment by Ieahleen** [comment]
@faraz16iqbal : the issue is still open, but someone is working on it, there is the `status: fix in progress` label to say that

**Comment by IC1101Virgo** [comment]
Hey!
I am new too. As I was reading the comments I saw you have a discord channel as well. However unfortunately I can't find your server room there? Can I join?
Thanks!

**Comment by Ieahleen** [comment]
Look at this article for the discord channel:
https://www.freecodecamp.org/news/freecodecamp-discord-chat-room-server/amp/

Il giorno mar 14 lug 2020 alle 14:46 Anjali Chaturvedi <
notifications@github.com> ha scritto:

**Comment by bkbranden** [comment]
Hey I am looking for an issue to make a first contribution to and I stumbled upon this one! It seems like someone is working on this issue, but I don't see any updates since Jul 14.

Is someone still working on this issue?

**Comment by Sky020** [comment]
@bkbranden The current PR does resolve the current issue. So, I suggest you look for another issue to work on with the _help wanted_ label. Thank you, for your interest.

**Comment by Rohit-Arora-0508** [comment]
Is it still open? I'd like to contribute to it.
