### ISSUE TITLE
Should freeCodeCamp teach more than code?

### ISSUE THREAD

**Issue by irlcatgirl** [freeCodeCamp/freeCodeCamp#39057]
I had some thoughts given recent situations with COVID-19 and employability factors as well. So as the title states I was wondering if freeCodeCamp should teach more than code. The various critical thinking skills, in the United States a strong mastery of English Grammar (this will vary from country to country), understanding of discrete mathematics among other fields employers may value aside from “can you code in X languages?”? With the understanding that freeCodeCamp probably can’t replace a college degree any time soon, is it worth considering an expansion of freeCodeCamps goal to teach people to code in aim of getting more people jobs without a college degree by teaching crucial skills that typically aren’t learned through freeCodeCamp? I’m no longer an active contributor for various personal reasons although thinking back I was wondering if this is a good discussion to start? I don’t claim to have all of the answers or even whether it’s possible but the size of the freeCodeCamp contributor community could work out in its favor.

**Comment by Ieahleen** [comment]
freeCodeCamp should focus on coding, if we try to spread it too thin, nothing will be able to be done. For anything else, https://www.khanacademy.org/ is doing a really good job. They have a lot of materials, and at the same time needs a lot of work to keep everything updated. I don't think freeCodeCamp should go away from the Code part.

And anyway, there is already a big update being done: https://www.freecodecamp.org/forum/t/freecodecamps-python-certifications-are-now-in-open-beta/395607

**Comment by thecodingaviator** [comment]
My personal opinion would be that with the project-based and Python curriculums, the project already has a lot of its hands, and expanding into non-code skills kinds goes against the "Code" part of freeCodeCamp. It is, once again, my personal opinion, nonetheless, I'm tagging @QuincyLarson for their opinion.

**Comment by raisedadead** [comment]
These are great ideas. However, we are keeping the tracker for concrete action items. 

I encourage you to move the discussion to the forum instead. Thanks for your understanding.
