### ISSUE TITLE
/learn Profile Requests and Console Behaviour

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#39053]
**Describe the bug**
1) It appears a `console.log()` was accidentally left in the `Profile.js` script.
2) A request to my/(a user's) _page-data_ is returning a 404.

**To Reproduce**
1. Go to https://www.freecodecamp.org/learn
2. Open DevTools
3. See log `true` or `false` in console, due to: `console.log(showDonation);`
 - File: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/components/profile/Profile.js
 - Line 126
4. See error in console as in picture below.

**Expected behavior**
No Errors, no logs.

**Screenshots**
![image](https://user-images.githubusercontent.com/51722130/84425228-1f72d280-ac19-11ea-80f2-539c36b8b9f3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.97

**Additional Info**
I believe the:
>'progress updates processed where possible'

Is useful, and should stay.

**Comment by ojeytonwilliams** [comment]
I think it would be better to remove all the logs, since we can use the flash messages if we need to communicate information.

Ideally, all errors should go to Sentry. This currently does happen for the server, but we haven't implemented it for the client, yet. Basically because there's still a bit too much noise (like the page-data.json 404 in your screenshot).

**Comment by raisedadead** [comment]
> 1. It appears a `console.log()` was accidentally left in the `Profile.js` script.

Yep, git blame @ahmadabdolsaheb and me for missing it in the QA. Reference: https://github.com/freeCodeCamp/freeCodeCamp/blame/f6aaa5f38a37c6739291ca51790a1e660aec182c/client/src/components/profile/Profile.js#L126

> 2. A request to my/(a user's) _page-data_ is returning a 404.

This is an expected side-effect of us using Gatsby's routing to query and get the user profile available at `/your-username`.

Essentially, when you hit `/some-path`, we first let Gatsby check in the static files if something is available at that path, if not we query the API to lookup there for a username. If both conditions fail, we would render an actual 404 page.

But for this to work the status code 404 is sort of abused. Its hacky but there is no way around this to the best of my knowledge.

**Comment by Ieahleen** [comment]
> any other rogue logs.

any suggestions where to search? I am trying to search around, but there doesn't seem to be, or I am finding those in the challenges code

**Comment by ojeytonwilliams** [comment]
@Ieahleen It's a bit tricky, because we use console logs as part of the challenge code, but the place to look is in `client/src`

@Sky020 could you explain why 'progress updates processed where possible' should appear in the console?

**Comment by Ieahleen** [comment]
there are a few, but they all seems needed where they are
```
gitpod /workspace/freeCodeCamp/client/src $ grep -n "console.log(" * -R

client/workers/test-evaluator.js:39:      console.log(msg.toString());
pages/learn/javascript-algorithms-and-data-structures/debugging/index.md:19:  console.log("Yuck");
pages/learn/javascript-algorithms-and-data-structures/debugging/index.md:29:    console.log("Hello, world!");
pages/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/index.md:14:**Hint**: If you get stuck, try using `console.log()` to log variable values to the console. This will help to debug problems.
templates/Challenges/utils/frame.js:28:      console.log(msg);
templates/Challenges/redux/execute-challenge-saga.js:200:    console.log(err);
templates/Challenges/rechallenge/transformers.js:27:  console.log(
templates/Challenges/rechallenge/transformers.js:33:  console.log(
templates/Challenges/rechallenge/throwers.js:64:          '`if (null) console.log(1)` detected. This will break tests'
```

**Comment by Ieahleen** [comment]
> @Sky020 could you explain why 'progress updates processed where possible' should appear in the console?

I don't know why, but it comes from file `client/src/redux/failed-updates-epic.js` line 98

**Comment by ojeytonwilliams** [comment]
@Ieahleen there are some `info`s, `error`s `warn`s, too. `grep -n "console\." * -R` gets me:

```
client/workers/test-evaluator.js:20:  const oldLog = self.console.log.bind(self.console);
client/workers/test-evaluator.js:39:      console.log(msg.toString());
client/workers/test-evaluator.js:44:    self.console.log = on ? proxyLog : oldLog;
client/workers/test-evaluator.js:71:      // Logging is proxyed after the build to catch console.log messages
client/frame-runner.js:70:        console.error(err);
components/profile/Profile.js:126:  console.log(showDonation);
components/Donation/DonateForm.js:175:    console.error(error);
pages/learn/javascript-algorithms-and-data-structures/debugging/index.md:19:  console.log("Yuck");
pages/learn/javascript-algorithms-and-data-structures/debugging/index.md:29:    console.log("Hello, world!");
pages/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/index.md:14:**Hint**: If you get stuck, try using `console.log()` to log variable values to the console. This will help to debug problems.
pages/donate.js:91:    console.info('stripe has loaded');
redux/failed-updates-epic.js:84:                  console.info(`${update.id} succeeded`);
redux/failed-updates-epic.js:98:        .then(() => console.info('progress updates processed where possible'))
redux/failed-updates-epic.js:100:          console.warn('unable to process progress updates', err.message)
templates/Challenges/rechallenge/throwers.js:64:          '`if (null) console.log(1)` detected. This will break tests'
templates/Challenges/rechallenge/transformers.js:27:  console.log(
templates/Challenges/rechallenge/transformers.js:33:  console.log(
templates/Challenges/utils/frame.js:28:      console.log(msg);
templates/Challenges/utils/frame.js:88:  const oldLog = ctx.window.console.log.bind(ctx.window.console);
templates/Challenges/utils/frame.js:89:  ctx.window.console.log = function proxyConsole(...args) {
templates/Challenges/redux/execute-challenge-saga.js:127:    // only the last test outputs console.logs to avoid log duplication.
templates/Challenges/redux/execute-challenge-saga.js:159:// updates preview frame and the fcc console.
templates/Challenges/redux/execute-challenge-saga.js:200:    console.log(err);
utils/format.test.js:28:  it('formats functions the same way as console.log', () => {
utils/report-error.js:3:  return console.error(`Client: ${message}`, e);
utils/format.js:4:  // we're trying to mimic console.log, so we avoid wrapping strings in quotes:
```

of which 

```
components/profile/Profile.js:126:  console.log(showDonation);
components/Donation/DonateForm.js:175:    console.error(error);
pages/donate.js:91:    console.info('stripe has loaded');
redux/failed-updates-epic.js:84:                  console.info(`${update.id} succeeded`);
redux/failed-updates-epic.js:98:        .then(() => console.info('progress updates processed where possible'))
redux/failed-updates-epic.js:100:          console.warn('unable to process progress updates', err.message)
```

probably should not be there.  I'd like to get @raisedadead's input before we remove them, though.  I think `components/Donation/DonateForm.js:175:    console.error(error);` should eventually make it to Sentry and possibly `redux/failed-updates-epic.js:100:          console.warn('unable to process progress updates', err.message)` should too.

**Comment by Sky020** [comment]
>@Sky020 could you explain why 'progress updates processed where possible' should appear in the console?

@ojeytonwilliams , Sorry - my language was too strong. I meant to say:
> Is useful, and could stay.

For no other reason than it is a debugging message. Re-thinking about it, I think it could be more useful being changed to `console.warn`, as that is how I interpret the message. After all, it is a `failedUpdate` component.
