### ISSUE TITLE
White dots 

### ISSUE THREAD

**Issue by Advitya-sharma** [freeCodeCamp/freeCodeCamp#39052]
When I open FCC on firefox,I see some white dots on the screen

![SharedScreenshot](https://user-images.githubusercontent.com/54709416/84413390-2fe17800-ac2e-11ea-94d4-68242bbcdfb4.jpg)

**Comment by ojeytonwilliams** [comment]
Thanks for the report @Advitya-sharma  

Could you right-click on the dots and Inspect Element?  Unfortunately I cannot see them on my machine, so any extra information you can give us will be a great help.

**Comment by Advitya-sharma** [comment]
yeah,I tried to inspect but can't find anything
did you tried in firefox ?
![Screenshot (260)](https://user-images.githubusercontent.com/54709416/84519700-16a10000-acf0-11ea-951b-b9684af933a8.png)
![Screenshot (261)](https://user-images.githubusercontent.com/54709416/84519726-1c96e100-acf0-11ea-890e-1cb77d0ab59d.png)

**Comment by ojeytonwilliams** [comment]
Yep, I tried Firefox and I don't see them.  That's why I was hoping you could pin them down to a particular element!

At a guess, it's caused by a browser extension, but it's hard to tell.  If you can try disabling any extensions that would at least rule out that possibility.

**Comment by raisedadead** [comment]
Try incognito/private window (which should disable all browser extentions/add-ons).

**Comment by Advitya-sharma** [comment]
but it does not opens in dark mode @raisedadead

**Comment by raisedadead** [comment]
> but it does not opens in dark mode

Did you sign in?

**Comment by Advitya-sharma** [comment]
got it ! its an issue with `turn off the lights` extension
dots are getting triggered even if extension is turned off
only disabling removes the dots. @raisedadead
