### ISSUE TITLE
Solution for Exercise Contradicts Directions

### ISSUE THREAD

**Issue by Jutkus** [freeCodeCamp/freeCodeCamp#39064]
### **Link To Exercise:**
[https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/repeat-a-string-repeat-a-string](url)

### **Link To Contradiction (Solution 3):**
["https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-repeat-a-string-repeat-a-string/16041"](url)

### Issue:

> **Challenge states:** The built-in repeat() method should not be used.
> **Solution 3:** Uses repeat()

**Comment by thecodingaviator** [comment]
I'll edit the forum post to remove the solution.
