### ISSUE TITLE
Typo in the hints list of "Never Mutate State" Redux challenge guide

### ISSUE THREAD

**Issue by tannercd** [freeCodeCamp/freeCodeCamp#39063]
**Describe your problem and how to reproduce it:**
Navigate to [Never Mutate State Redux Challenge Guide](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-never-mutate-state/301445). Scroll down slightly to view the "Hints" list. There are two list items with typos, "Hint 32" and "Hint 33". 

**Add a Link to the page with the problem:**
[Never Mutate State Redux Challenge Guide](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-never-mutate-state/301445)

**Recommended fix, suggestions (how would you update it?):**
Change "Hint 32" and "Hint 33" inside the Hints list to "Hint 2" and "Hint 3".

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
<img width="741" alt="reduxIssue" src="https://user-images.githubusercontent.com/48612525/84549947-20aa0b00-acbe-11ea-9af1-1a62cd2f0616.png">

**Comment by nhcarrigan** [comment]
Thank you for bringing this to our attention! As this is a forum post, I went ahead and corrected the typo. For forum post issues, I believe you can flag the post for moderator attention on the forum itself, rather than creating a GitHub issue, since the fix does not require a change on the GitHub repo. 🙂

**Comment by tannercd** [comment]
@nhcarrigan Your welcome! Okay, I will make sure to flag the post for moderator attention in the future. Some of the mods had previously instructed me to open an issue for "Broken anchor element links" and other bugs I had found while on the forum. Be well! 😃
