### ISSUE TITLE
Winston churchill quote not fixed

### ISSUE THREAD

**Issue by DivyanshTiwari0** [freeCodeCamp/freeCodeCamp#39072]
On this fine morning, Im in a good study mood and I see this yet again 
![winston](https://user-images.githubusercontent.com/66130777/84584587-e0fd3380-ae23-11ea-8b5e-496b7fbd3865.PNG)

**Comment by nhcarrigan** [comment]
Hello! I just wanted to let you know that we have heard you, and that we are not trying to ignore this. The Winston Churchill quotes slated for removal as part of #36069, which appears to be in the review process. 🙂

**Comment by nhcarrigan** [comment]
For the dev team: this issue appears to be linked to #39039.

**Comment by raisedadead** [comment]
Please do not open duplicate issues. It doesnt help you, doesnt help the maintainers of the repo. 

There is already a related issue thread which is open. I had specifically mentioned the same in your original report.
