### ISSUE TITLE
Content of certificate get's misplaced when zoomed in or zoomed out.

### ISSUE THREAD

**Issue by MrFullStackDev** [freeCodeCamp/freeCodeCamp#39089]
When we zoom in or zoom out the browser, the content inside the certificate ('This certifies that') get's misplaced.

Tested on Google Chrome 83, Microsoft Edge 83, and Mozilla Firefox Developer edition 78.

Out of these, it was fine on Mozilla Firefox Developer edition 78. 

Regards

![ezgif com-crop](https://user-images.githubusercontent.com/43752898/85098807-4d5ba680-b219-11ea-9159-013459d69287.gif)

**Comment by nhcarrigan** [comment]
I was able to reproduce this bug.

**Screenshot**
![image](https://user-images.githubusercontent.com/63889819/84924478-6deef980-b07d-11ea-9e7c-1be085d79a13.png)

**Steps to Reproduce**
1. Go to a certificate page on your portfolio.
2. Change your browser zoom level - I saw the bug at zoom levels 25%, 75%, 90%, 125%, and 175%.

**System Information**
OS: Windows 10 Version 1909
Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by thecodingaviator** [comment]
On my machine, it's happening for multiples of 100/3.

**Comment by ahmadabdolsaheb** [comment]
Hi @thecodingaviator, could you see if you can still reproduce this? if so, what browser/version. Thanks

**Comment by nhcarrigan** [comment]
@ahmadabdolsaheb - I am no longer able to reproduce this bug.

**Comment by ahmadabdolsaheb** [comment]
Thanks for confirming @nhcarrigan. I will be closing this issue for now. @MrFullStackDev, please let me know if you are still experiencing this issue so we could reopen and resolve this issue accordingly.
