### ISSUE TITLE
Remove example code from seed/starter code

### ISSUE THREAD

**Issue by lasjorg** [freeCodeCamp/freeCodeCamp#39081]
Challenge: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/generate-random-whole-numbers-with-javascript

Forum post: https://www.freecodecamp.org/forum/t/problems-with-generate-random-whole-numbers-with-javascript/404092

I think we should remove the example code from the seed code. We already have an example in the challenge text. Right now, it's just some odd unused code at the beginning of the challenge.

If we still want the example code it should be moved to the challenge text instead.

**Comment by nhcarrigan** [comment]
Okay to submit a PR for this? 🙂

**Comment by lasjorg** [comment]
@nhcarrigan Fine with me. If nobody objects to the change we will use the PR.
