### ISSUE TITLE
You can pass Metric-Imperial Converter Project by just using the BASE Glitch Project given

### ISSUE THREAD

**Issue by Symbolistic** [freeCodeCamp/freeCodeCamp#39085]
https://www.freecodecamp.org/learn/information-security-and-quality-assurance/information-security-and-quality-assurance-projects/metric-imperial-converter

I literally wanted to test if the helmetJS securities I added were working and passed, I ended up passing everything.
I commented out the helmetJS .use lines and still passed everything.

This section really needs to be updated, lol.

**Comment by nhcarrigan** [comment]
Related to #37815.

**Comment by nhcarrigan** [comment]
Related to #37185

**Comment by huyenltnguyen** [comment]
Hi @Symbolistic Thanks for reporting! As @nhcarrigan said, this issue has been reported in #37185, and in fact, there is already a PR to add tests for this project (https://github.com/freeCodeCamp/freeCodeCamp/pull/37891). We will try to review and get the PR merged as soon as we can.

I'm closing the issue as it is a duplicate. Thanks again for the report.

Happy coding!
