### ISSUE TITLE
Rename Master branch to Main and modernize references to master-slave db replication

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#39098]
We are changing freeCodeCamp's Master branch to "Main".

We are also going through our curriculum and our publication and changing references to Master-Slave Database Replication to "Primary" and "Replica".

Master was the default branch name on GitHub when we created this repo back in 2014, and [GitHub itself is changing this going forward](https://wersm.com/github-is-switching-to-more-inclusive-language/).

The terms "Primary" and "Replica" are clearer anyway, and we can avoid the baggage of this poorly-chosen naming convention from decades past.

Tasks:

- [x] All freecodecamp.org/news references to master-slave database replication and master branches are updated
- [ ] All freeCodeCamp GitHub repository branch names renamed
- [ ] Readme.md, Contributing.md, and other Documentation files on repos are updated

**Comment by raisedadead** [comment]
IMHO, instead of `main` we could do one better called it `dev` or `development` (I prefer later), which fits better in our context of other branches which we have been using for a while now:

~~master~~ development
production-staging
production-current

**Comment by nhcarrigan** [comment]
Hello~!

If help is welcome, I'd be willing to update the documentation to reflect the name change. 🙂

**Comment by Ieahleen** [comment]
I will follow this issue, so that I can update the italian docs when the change is done, and start working on them to make them a bit better and updated

**Comment by moT01** [comment]
Closing in favor of the more detailed tracker I linked right above this.
