### ISSUE TITLE
Numpy - Copying Arrays Warning – unnecessary commas

### ISSUE THREAD

**Issue by borntofrappe** [freeCodeCamp/freeCodeCamp#39096]
**Describe your problem and how to reproduce it:**

The challenge in the numpy module [Numpy - Copying Arrays Warning](https://www.freecodecamp.dev/learn/data-analysis-with-python/numpy/copying-arrays-warning) provides the different options separating the items with `,` comma characters

```
[1, 2, 3, 4, 5]
[1, 2, 20, 4, 5]
[1, 20, 3, 4, 5]
```

Since the challenge describes numpy arrays however, the correct syntax would be

```
[1 2 3 4 5]
[1 2 20 4 5]
[1 20 3 4 5]
```

I'd be more than glad to fix this with a pull request if you agree 👍 

**Add a Link to the page with the problem:**

https://www.freecodecamp.dev/learn/data-analysis-with-python/numpy/copying-arrays-warning

**Comment by ojeytonwilliams** [comment]
That makes sense to me.  @borntofrappe a PR would be very welcome!

**Comment by borntofrappe** [comment]
Apologies for the mess. I tried making a PR, but while updating the fork with the commits of the master branch, it seems the request was merged in the previous pull request I made for another challenge.

Do you have any suggestion on how to fix this? I'm so sorry, again apologies for this git-mess 😢

**Comment by ojeytonwilliams** [comment]
Don't worry, it happens.  So, the first thing to do is make sure you make a backup of your work, because you'll need to reset your master branch.  Once you've backed it up these are the steps

```
git fetch upstream master
git checkout master
git reset --hard FETCH_HEAD
```

at this point your master will only have the commits that this remote has.

Now, create a new branch off master:

```
git checkout -b fix/copying-arrays-warning
```

That branch is where you can put the commits to fix this issue.

The other PR looked fine, so I merged it.  No need to worry about that one!

**Comment by borntofrappe** [comment]
Thank you thank you thank you @ojeytonwilliams 

I thought creating a branch would be excessive for such a minor pull request, but indubitably, that was the way to go (I was also afraid you'd have way too many branches to juggle through)

Thanks again for the help 😄

**Comment by ojeytonwilliams** [comment]
No problem, I'm glad you were able to sort it out!

**Comment by moT01** [comment]
Looks like this one is fixed, so I think it's safe to close this. If I am misunderstanding the issue or something, let me know and we can reopen it. Thanks 😄 

For future reference @borntofrappe - if you put "Closes #xxxxx" in the PR description, with "xxxxx" as the issue number the PR closes, it will close the issue automatically when the PR is merged. 😄
