### ISSUE TITLE
Challenge freezing on incorrect input

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39101]
**Describe your problem and how to reproduce it:**
The Define the Head and Body of an HTML Document challenge freezes if you enter in code like

```html
<!DOCTYPE html>
<html>
  <head>
    <title>The best page ever</title>
  <head>

  <body>
    <h1>The best page ever</h1>
    <p>Cat ipsum dolor sit amet, jump </p>
  <body> <!-- this tag should be closing -->
</html>
```

where the `body` tag is not closed.  This is a common enough mistake and the freezing is not directly caused by the user code - it's how our tests interact with it.

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/define-the-head-and-body-of-an-html-document

**The cause**

The last test causes the problem, I think the regex gets stuck in a loop.

**Comment by Sky020** [comment]
Classic regex runaway.

Something closer to this should do:
```
<body>\s*(((<h1>\s*.*\s*<\/h1>\s*)(<p>(\S*\s)*<\/p>\s*))|((<p>\s*.*\s*<\/p>\s*)(<h1>(\S\s)*<\/h1>\s*)))<\/body>
```
I do not know why this would be used anywhere: `*?`

**Comment by ojeytonwilliams** [comment]
`.*?` some makes sense if you want to grab whatever's between, say, an opening and closing tag.  `\s*?`, on the other hand, doesn't, in part because white space does not really matter here, so we might as well remove it before trying to match.

**Comment by ojeytonwilliams** [comment]
@Sky020 what do you think to the following?

```
<body>\s*(<h1>.*?<\/h1>\s*<p>.*?<\/p>\s*)|(<p>.*?<\/p>\s*)(<h1>.*?<\/h1>\s*)<\/body>
````

(or the same, without the `\s`s and applied to the code with whitespace removed)

As far as I could see the problem comes from expressions like `(.*)*` (with or without a `?`) which blow up.

**Comment by Sky020** [comment]
@ojeytonwilliams ,Well, that would work, if we added more parentheses to prevent the `|` from applying to the `<\/body>`:
```
<body>\s*((<h1>.*<\/h1>\s*?<p>.*<\/p>\s*)|((<p>.*?<\/p>\s*)(<h1>.*?<\/h1>\s*)))<\/body>
```
It is not nice to look at. So, I would prefer the spaces and tabs be removed, and the `\s` can go.

**Comment by ojeytonwilliams** [comment]
Good point about the brackets.  

We can remove the spaces by using `const noSpaces = code.replace(/\s/g, '')`, so that it will be easy to find when we use https://github.com/freeCodeCamp/freeCodeCamp/pull/38605

**Comment by morgan-sam** [comment]
Is help still wanted with this issue? Asking because #39112 is still open

**Comment by ojeytonwilliams** [comment]
Thanks for the heads up @morgan-sam, I should have removed the label.  I'm in the process of updating how user code makes it into the test frame and, once that's done, #39112 should work.
