### ISSUE TITLE
Test Case bug: Basic Node and Express - Use the .env File

### ISSUE THREAD

**Issue by sriramvsharma** [freeCodeCamp/freeCodeCamp#39108]
**Describe your problem and how to reproduce it:**

Bug Description: I am unable to pass the test case even though my code is doing exactly what the challenge is asking it to in order to pass the challenge. 

![image](https://user-images.githubusercontent.com/6435829/85178028-4ee59880-b232-11ea-9921-4dfe78bdd1f4.png)

My code solution: 

`app.get('/json', (req, res)=> {
  var response;
if (process.env.MESSAGE_STYLE === "uppercase") {
  response = "Hello json".toUpperCase();
} else {
  response = "Hello json";
}
  res.json ({
    message: response
  });
});
`

**Link to the page with the problem:**
https://www.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/use-the-.env-file

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: Version 83.0.4103.106 (Official Build) (64-bit)
* Operating System: MacOS Mojave

Link to solution with the code: https://eastern-earthy-rake.glitch.me

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Sky020** [comment]
Hello there,

There is already an issue up. So, I am closing this as a duplicate.

You can follow the issue here: #39095
