### ISSUE TITLE
My % operator somehow is not working

### ISSUE THREAD

**Issue by A-coder-beep** [freeCodeCamp/freeCodeCamp#39103]
**Describe your problem and how to reproduce it:**
my answer to the exercise is correct, however when i click on execute the tests it puts me that i did not use the operator% while i did it.

**Add a Link to the page with the problem:**
https://www.freecodecamp.dev/learn/javascript-algorithms-and-data-structures/basic-javascript/finding-a-remainder-in-javascript

**Tell us about your browser and operating system:**
* Browser Name: Lenovo
* Browser Version: chrome 83 on windows 10
* Operating System: windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/65826720/85158742-dba54c00-b25c-11ea-914c-2d6b6176e79a.png)
![image](https://user-images.githubusercontent.com/65826720/85158775-e95ad180-b25c-11ea-9051-886117e5babf.png)

**Comment by nhcarrigan** [comment]
Hello~!

I was able to reproduce this bug. After some digging, it looks like the `%` operator test will fail if the line does not end with a `;`. 
I am not sure if this is considered a bug as ending lines with `;` is a *good practise*, but if there is agreement that this should be changed I believe I can update the test to not require the semi-colon.

**Comment by A-coder-beep** [comment]
ok i will try thanks!

**Comment by A-coder-beep** [comment]
IT WORKED THHHAAANKKKSSS

**Comment by A-coder-beep** [comment]
BRRUUUUH
