### ISSUE TITLE
Bonfire: Chunky Monkey code is not being executed

### ISSUE THREAD

**Issue by JonathanKumar95** [FreeCodeCamp/FreeCodeCamp#3911]
Challenge [Bonfire: Chunky Monkey](http://freecodecamp.com/challenges/bonfire-chunky-monkey#?solution=function%20chunk(arr%2C%20size)%20%7B%0A%20%20%2F%2F%20Break%20it%20up.%0A%20%20var%20returnArr%20%3D%20%5B%22%22%5D%2C%0A%20%20%20%20%20%20tempArr%20%20%20%3D%20%5B%22%22%5D%3B%0A%20%20for(var%20i%3D0%3Bi%20%3C%20size%3B%20i%20%3D%20i%2B%2B)%7B%0A%20%20%20%20returnArr%5Bi%5D%20%3D%20arr%5Bi%5D%3B%0A%20%20%7D%0A%20%20return%20arr%3B%0A%7D%0A%0Achunk(%5B%22a%22%2C%20%22b%22%2C%20%22c%22%2C%20%22d%22%5D%2C%202)%3B%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Okay so i was working on this test for a while and all of a sudden it got stuck and stopped executing code.

My code:
```javascript
function chunk(arr, size) {
  // Break it up.
  var returnArr = [""],
      tempArr   = [""];
  for(var i=0;i < size; i = i++){
    returnArr[i] = arr[i];
  }
  return arr;
}

chunk(["a", "b", "c", "d"], 2);

...

**Comment by BerkeleyTrue** [comment]
Hello @JonathanKumar95 

The third field in you for loop should not re-assign the variable you are tracking. Try:
```js
// for loop signature ( variable to track, conditional to validate against, expression that should increment variable)
for(var i=0; i < size;  i++){
```

**Comment by JonathanKumar95** [comment]
Oh gosh, i didn't identify that before, the entire program got stuck so i thought it was a fault with the test. Thanks a lot btw.

**Comment by BerkeleyTrue** [comment]
Happy Coding!
