### ISSUE TITLE
Autofill Bug

### ISSUE THREAD

**Issue by 0x476C31746368** [freeCodeCamp/freeCodeCamp#39110]
**The Problem**
I wanted to type "Hello World" but something happened which i can't really explain so you can watch a video <a href="https://www.youtube.com/watch?v=ePd9P9D7uvA" title="O_O"> here. </a>
When i tried to delete the word "Hello" in the beginning it kept changing the selected word. Also at the end you can see after i type "wtf" and press enter 4 more "wtf" appear.

**Steps to Reproduce**
Enter freecodecamp(dot)org with mobile phone, start the first challenge, go to the code tab and type anything.

It's my first issue I'm writing so if anything is missing I'm happy to provide the missing information.
I use Firefox Nightly 200619 06:01 (Build #2015747123). My Phone runs Android Version 10 and EMUI Version 10.0.0 and i have the default keyboard app: MS SwiftKey Keyboard.

**Comment by nhcarrigan** [comment]
Hello~!

This is usually an issue with your mobile device's autocorrect and keyboard settings. I recommend taking a look at the [FreeCodeCamp Mobile Coding article](https://www.freecodecamp.org/news/freecodecamp-mobile/) for instructions on installing a coding keyboard.

**Comment by Sky020** [comment]
Hello there,

Whilst freeCodeCamp is made responsively, the main focus has always been for the challenges to be completed on a full-pc (not mobile). That being said, I suggest reading the tips mentioned in this article for using fCC on a mobile: https://www.freecodecamp.org/news/freecodecamp-mobile/

Unfortunately, we cannot cater for all, as of yet. So, I am closing this issue. If you have any more enquiries, the [forum](https://www.freecodeCamp.org/forum) is usually a good place to start.
