### ISSUE TITLE
Back-end Problem

### ISSUE THREAD

**Issue by OfficielSalah** [freeCodeCamp/freeCodeCamp#39116]
**Describe your problem and how to reproduce it:**
So Basically i found out that it's possible to pass all the projects and earn the certificate Responsive Web Design and front-end libraries and maybe more i didn't check it yet just like in 5 minute or less ,how to do that :  you only need to make a new project in codepen and write some basic code and then paste the link of the project in freecodecamp and it's done , but i found out that when you go to the next project the button "I've completed this challenge" become disabled , but it's possible  to make it enabled  just by going to the developer tools in the browser and delete the "disabled" proprety from the a tag , and then you paste the link , so i suggest to make a middelware in the backend to prevent things like that otherwise people gonna keep earning certificates with no knowledge , and i mean by that like make the user be able to make only 1 project daily . keep it up you are making a good thing.

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 
* Operating System: Kali Linux

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by raisedadead** [comment]
Thanks for your recommendation. We have an open issue that discusses this. I am closing this as a duplicate.
