### ISSUE TITLE
it thte tile

### ISSUE THREAD

**Issue by zepekenio9542** [freeCodeCamp/freeCodeCamp#39113]
**Describe your problem and how to reproduce it:**

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Sky020** [comment]
Hello there,

I am closing this issue, as it contains no information. If you are experiencing a bug, feel free to open a valid issue with more information. If you are needing help with something to do with the fCC curriculum, head over to the [forum](https://www.freecodecamp.org/forum), and search around/open a topic.

Thank you.
