### ISSUE TITLE
Blog Instructions Unclear and Seem to Promote Copyright Infringement:

### ISSUE THREAD

**Issue by themagicbean** [freeCodeCamp/freeCodeCamp#39117]
> Technically as a writer, you’re liable for copyright infringement, and Medium is not. The simplest way to attribute an image is to put the words “Image credit” below an image, and link this text to its original source.
> 

(This bug report is not legal advice and should not be relied on in taking any course of action.   No attorney-client or other relationship is formed by this report, and no legal duties are intended to be formed.)

The quoted paragraph is extremely troubling, because (1) Medium (or FCC or whoever) could have secondary copyright infringement liability under some circumstances [(cite)](https://en.wikipedia.org/wiki/Secondary_liability) and (2) merely citing a work taken from is not enough to prevent an infringement claim.  [A](http://www.dmlp.org/legal-guide/linking-copyrighted-materials) [few](https://www.searchenginejournal.com/using-images-legally-online-guide/319403/#close) [resources](https://www.searchenginejournal.com/using-images-legally-online-guide/319403/#close)/).  

The second paragraph, encouraging using reusable images, appears to be much better.  Using CC or public domain (or other shareable licenses) is generally the better practice..  Of course, many of those authors (photographers) want credit and credit should be given.

Please consider revising.  

Restate of first paragraph:  This bug report is not legal advice and should not be relied on in taking any course of action.   No attorney-client or other relationship is formed by this report, and no legal duties are intended to be formed.

**Comment by QuincyLarson** [comment]
@themagicbean Thanks for pointing this out. I enjoyed reading these articles you linked to.

Due to this ambiguity, I've gone ahead and removed this sentence from this old article. (We don't use Medium anymore, anyway.)
