### ISSUE TITLE
Python For Everybody - radio button options 

### ISSUE THREAD

**Issue by COAB1** [freeCodeCamp/freeCodeCamp#39115]
**Describe your problem and how to reproduce it:**
In the section of the Python For Everybody curriculum, when you are watching the video to answer the questions, the radio button comes already marked as the first option every time. This can be a little confusing for starters. I think it should come without the radio button marked.

**Add a Link to the page with the problem:**

[https://www.freecodecamp.dev/learn/scientific-computing-with-python/python-for-everybody/iterations-loop-idioms](https://www.freecodecamp.dev/learn/scientific-computing-with-python/python-for-everybody/iterations-loop-idioms)

**Tell us about your browser and operating system:**
* Browser Name: Firefox Web Browser
* Browser Version: 77.0.1 (64-bit)
* Operating System: Ubuntu 20.04 LTS

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot from 2020-06-21 16-31-34](https://user-images.githubusercontent.com/50220493/85233457-b8090f80-b3dc-11ea-9721-e4d1d370daa6.png)

**Comment by Sky020** [comment]
Hello there,

Thank you, for taking the time to report this. An issue for this has already been created (#39048). Therefore, I am closing this as a duplicate.

Thank you.
