### ISSUE TITLE
Smoother multiple choice UX

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39123]
**Is your feature request related to a problem? Please describe.**
Currently the user has to click back and forth between the answer radio buttons and the 'Check your answer' button.

**Describe the solution you'd like**
As soon as the user clicks on an answer, it could trigger the check automatically.

**Describe alternatives you've considered**
Leaving it as is, if this seems likely to encourage guessing.

**Additional context**
Originally suggested here: https://github.com/freeCodeCamp/freeCodeCamp/issues/39048#issuecomment-645798776

**Comment by raisedadead** [comment]
> As soon as the user clicks on an answer, it could trigger the check automatically.

We were doing this intially or had thought of doing this. The idea is to encourage thinking over the problem and strongly discourage click-thru completions.

I am quite open to alternatives.

**Comment by ojeytonwilliams** [comment]
>  The idea is to encourage thinking over the problem and strongly discourage click-thru completions.

That's true.  Requiring that extra step might just be enough impetus to encourage thinking rather than just clicking multiple times.  I'm not sure, so let's see if anyone has any clever ideas.

**Comment by ptkpyitheim** [comment]
I'm going to look into this issue and see if I can just automatically check the correct answer instead of having to click through Check You Answer. If any of you have looked into this, any hints on how to go about it?

**Comment by Sky020** [comment]
>If any of you have looked into this, any hints on how to go about it?

@ptkpyitheim , Automatically submitting the answer would be as easy as calling one already made function. My understanding is that we do not want this approach, and are looking for more ideas on reducing the faff, whilst not encouraging _half-hearted_ guesses.

**Comment by Sky020** [comment]
@ojeytonwilliams What about handling double-clicks as a way to submit the answer?

That is the only idea I can come up with, and, if that is still too encouraging of _click-throughs_, then I suggest we close this issue.

**Comment by ojeytonwilliams** [comment]
@Sky020 on reflection, it's probably fine as is.  Double-clicking is a bit counter-intuitive - I'm not sure I've come across a UI that requires that before.

As an aside, do you know what happened with the outlining?  I feel sure we both worked on that at one point, but production has no outlining at all, which isn't great from an a11y perspective.

**Comment by Sky020** [comment]
> As an aside, do you know what happened with the outlining?

@ojeytonwilliams , We did, and you still have a PR for this: https://github.com/freeCodeCamp/freeCodeCamp/pull/39148

**Comment by raisedadead** [comment]
Going to go ahead and close this. Thanks everyone.
