### ISSUE TITLE
Audit navigation (opening new tabs only when necessary)

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#39127]
You can go to [my profile](https://www.freecodecamp.org/mot01) and click on one of the certifications - it opens in the current tab. The only way to go back is to use the browsers back button. Seems like those should open in a new tab.

**Comment by saideepesh000** [comment]
Hi, can i do this

**Comment by rajatgupta24** [comment]
Hi, @moT01 
I'm interested in this, can you please guide me with this as i wasn't understand it using devTools.
Thank You.

**Comment by thecodingaviator** [comment]
@moT01 I think this is a great idea. Low effort as well. Do you want to wait for more input from the community?

**Comment by PeterF521** [comment]
To open links in a new tab you need to use **'target:"_blank"'** arg.

**Comment by moT01** [comment]
I believe that [right here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/components/profile/components/Certifications.js#L46), and [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/components/profile/components/TimeLine.js#L89) is where to update this. The first link is for the big links on a profile, and the second is for the cert links in peoples timelines.

**Comment by DavidJSykes** [comment]
Is it okay if I have a go at making the changes? I haven't contributed before and this seems relatively straight forward

**Comment by moT01** [comment]
You certainly can @DavidJSykes. Several people have already asked to do this before you. We usually just accept the first PR that fixes the issue, so you don't need to ask.

**Comment by secan** [comment]
In general, W3C recommends against opening links into new tab, pages or pop-ups, because of accessibility concerns (https://www.w3.org/TR/WCAG20-TECHS/G200.html); maybe a better solution would be adding a link back to the profile in the certificate page.

**Comment by ojeytonwilliams** [comment]
@secan I agree that we should generally avoid opening new tabs.  We do need to be careful modifying the certificate, though. The goal for the certificate page is it should just show certificate itself, and nothing else, so you can display it to other people.  Any extra links would detract from that.

One possibility is to keep the current behaviour (navigation in a single tab), but add in a link back to the profile that's only visible when you're signed in.  It should also be clearly labelled, so that people know that it will display properly when other people see it.

**Comment by DavidJSykes** [comment]
There are a lot of links on freecodecamp.org that open in new tabs, everything in the Trending Guides section for instance which does seem a bit strange to me. Would a dismissable popover for the certificates be a better idea? I'll try and code something up soon along those lines and see what you guys think.

**Comment by RandellDawson** [comment]
@DavidJSykes Popups are typically frowned up, but  you might show a mockup first before writing a lot of code.

**Comment by ojeytonwilliams** [comment]
@raisedadead while the PR that closed this was a good one, is worth leaving this open? I think it was a useful discussion for anyone that wants to submit a PR to align us with the W3C accessibility guidelines.

**Comment by DavidJSykes** [comment]
@ojeytonwilliams is it something that needs to be looked at across the entire site? Perhaps it's a bit broader than just the certificates links?

**Comment by ojeytonwilliams** [comment]
@DavidJSykes I think it is, yes.  Since this worsens accessibility, we should avoid it if possible.

I'll edit the title to reflect the broader discussion.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
