### ISSUE TITLE
/forum → forum.freecodecamp.org

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#39138]
We are migrating to the managed Discourse by the Discourse team. Until now we had been doing a semi-on-premise setup.

This migration unfortunately involves us going back to the subdomain for various technical limitations with the new setup.

We need to audit and update the links in the codebase.

Fallback redirects will be setup, but changing as many links as we can will take the load off of the webservers.

**Comment by raisedadead** [comment]
Because this is time sensitive, we would want prior contributors with familarity with the codebase to take a look at this to help us make the changes as quick as possible.

**Comment by nhcarrigan** [comment]
Hello~! 

I've submitted a pull request that should have caught most of the /forum links and replaced them with the subdomain link.

**Comment by RandellDawson** [comment]
@ojeytonwilliams What needs to be done (if anything) with the following sections of code?

Line 26 in [Header.test.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/components/Header/Header.test.js)

Line 20 in [NavLinks.js](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/components/Header/components/NavLinks.js)

**Comment by ojeytonwilliams** [comment]
I'll update those to the new location.  I think Nicholas's PR should cover everything else.
