### ISSUE TITLE
Tests for some projects can be bypassed

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#39132]
On the settings page, I can submit "legacy" projects and, if they are still part of the curriculum, they will automatically be filled in for that project as well.

For example, I can submit the timestamp microservice project like this...
<img width="393" alt="Screen Shot 2020-06-24 at 9 17 19 PM" src="https://user-images.githubusercontent.com/20648924/85645752-43de9e00-b660-11ea-954f-d0614af6cd7b.png">

and it automatically gets filled in here...
<img width="412" alt="Screen Shot 2020-06-24 at 9 19 02 PM" src="https://user-images.githubusercontent.com/20648924/85645800-5d7fe580-b660-11ea-9893-b532b22584b2.png">

If I were to try and submit this URL on the [page for that project](https://www.freecodecamp.dev/learn/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice), the tests fail and I can't submit.

Wondering if we should remove the input fields for legacy projects on the settings page and make them like the rest. I believe all the legacy projects pages are all still available either in the current curriculum, or the take home projects.

**Comment by ojeytonwilliams** [comment]
It's also possible to claim certifications where some have been submitted this way, which is not great.

So, just to state the obvious: the problem is with the non-legacy projects that appear in legacy certifications.  I think we could solve this by replacing the form with a link to the challenge.  @moT01 what do you think?

**Comment by moT01** [comment]
> I think we could solve this by replacing the form with a link to the challenge.

I like the second picture in the post there. Which, yes, is basically a link to the project - but it also has the solution there. Basically, just make them like all the others is what I was thinking.

**Comment by gikf** [comment]
While investigating what needs to be changed to implement this, I've confirmed that with all projects in the legacy section are linked with (submitting one submits another) either challenge in `Take Home Projects` or project in current curriculum.

In one case this linking doesn't really point to the same project. In `Legacy Front End` project `Stylize Stories on Camper News` is linked with the `Build a Tribute Page` project from `Responsive Web Design`.

`Build a Camper Leaderboard` from `Legacy Data Visualization`, appears as `Build a freeCodeCamp Forum Homepage (Take Home Projects)`.

There are some other that have some slight differences in naming, ie. `Use the TwitchTV JSON API` vs `Use the Twitch JSON API` or having appended `Build an` before the name.

What should be done with these? Change their names to fully match current projects and challenges? Or just change URLs to make them point to equivalent project? With the first one from above every option doesn't seem to be ideal.
