### ISSUE TITLE
User should receive an alert when a section is completed

### ISSUE THREAD

**Issue by CodeNonprofit** [FreeCodeCamp/FreeCodeCamp#3914]
As it stands you can only see this option to share the portfolio on Facebook from the map. 

If the last challenge of a section is completed && all other challenges in that section have also been completed, alert w/ option to share user portfolio on facebook.

**Comment by gasperno** [comment]
I have this [commit](https://github.com/gasperno/FreeCodeCamp/commit/71645f7211dab29415775a8e4d400f053d32a38c
) on my fork. I need help to determine if this way is right.
I filtered challenges based on the current `challengeId` found the SuperBlock and filtered out completedChallenges to count the number of unsolved challenges in a given super block. 
Any comments related to the approach would help.
