### ISSUE TITLE
"How to teach programming" News Article Broken

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#39159]
**Describe your problem and how to reproduce it:**
The article appears to have been unfinished.
1) Go to: https://www.freecodecamp.org/news/how-to-teach-programming-to-teenagers-2ecd43846f0d/
2) See the article end abruptly

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/news/how-to-teach-programming-to-teenagers-2ecd43846f0d/

**Recommended fix, suggestions (how would you update it?):**
Either remove the article, or find the missing content (if exists)

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/51722130/86350642-eac3cb00-bc5a-11ea-9291-0a5428352076.png)

**Comment by DavidJSykes** [comment]
@Sky020 has this issue been fixed? Clicking the link seems to pull up the whole article now.

**Comment by Sky020** [comment]
@DavidJSykes , Yes. All the content appears to be there.

Thank you, to whoever fixed it.
