### ISSUE TITLE
Broken "Leaderboard" Link on Forum

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#39156]
**Describe the bug**
The "Leaderboard" button in the top nav of the forums is still set to use the old link format - it links to `forum.freecodecamp.org/forum/users`.

**To Reproduce**
1. Log in to the [forums](https://forum.freecodecamp.org)
2. Click on the "Leaderboard" button.
3. Get the 404 page.

**Expected behavior**
The "Leaderboard" button should link to `forum.freecodecamp.org/users`.

**Screenshots**
![image](https://user-images.githubusercontent.com/63889819/86269869-37d26f00-bb7f-11ea-85fc-3a2babb7bfc2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1909
 - Browser: Chrome
 - Version: 83.0.4103.116

**Comment by raisedadead** [comment]
Thanks for the issue.

This line here needs updating:
https://github.com/freeCodeCamp/discourse-users-nav/blob/b9baba51aeca02b55a48556ebc7106f0a8a51515/common/head_tag.html#L15

Any takers?

**Comment by nhcarrigan** [comment]
I can give it a shot. 🙂

**Comment by raisedadead** [comment]
I merged your PR but I realised that we can switch back to the official component

https://github.com/discourse/discourse-users-nav

The repo we had was a fork for supporting subpaths, which is not relevant any longer. I am going to go ahead and archive it.

Thanks for the issue and the PR. Sorry for wasting your time, I should have realised this before requesting help.

**Comment by nhcarrigan** [comment]
No worries! Always happy to get the opportunity to practise. 😅
