### ISSUE TITLE
404 broken link for hint text (Basic Javascript: Return Early Pattern for Functions)

### ISSUE THREAD

**Issue by andrewjbeattie** [freeCodeCamp/freeCodeCamp#39155]
There is a broken link to hint information on the "_Basic JavaScript: Return Early Pattern for Functions_" page. 

Look for the text just before the "Run the Tests" button:
 
Remember that **[undefined is a keyword](https://www.freecodecamp.org/challenges/understanding-uninitialized-variables)**, not a string.

Click on the linked words "undefined is a keyword" and you will be taken to a 404 "Page Not Found" here:

https://www.freecodecamp.org/challenges/understanding-uninitialized-variables

Page with the problem:

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/return-early-pattern-for-functions

* Browser Name: Firefox Developer Edition
* Browser Version: 78.0.b2 (64 bit)
* Operating System: Manjaro (Gnome) (Kernel: 5.6.16-1-MANJARO)

**Comment by RandellDawson** [comment]
I suggest we change the note to:
> Remember that `undefined` is not a string.

This will get rid of the non-existent link and also remove the incorrect `keyword` reference.

**Comment by sinclair-guthrie** [comment]
I was looking into this and realized there's already been a fix for the broken link that's been merged in https://github.com/freeCodeCamp/freeCodeCamp/pull/38897

Not sure if we're still interested in updating the note, or if we want to leave it as is.

**Comment by Sky020** [comment]
@RandellDawson , _sinclair_ is correct. The link should have been fixed by the last commit. Is there any reason this commit would not have been pushed to production?

**Comment by raisedadead** [comment]
Yes, we are waiting on a release which is overdue. Should be out in a bit (spoiler alert: Its a big one \*wink\* \*wink\*).

I am closing this as "shipping".
