### ISSUE TITLE
Video 'copy link' does not appear to work

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39152]
**Describe the bug**
When click on the embedded video a 'Copy link' icon appears in the top right.  Clicking on this should copy the video link into your clipboard, but it does not.

**To Reproduce**
1. Go to https://www.freecodecamp.dev/learn/scientific-computing-with-python/python-for-everybody/introduction-why-program
2. Click on the embedded video
3. Click on the 'Copy link' icon
4. Paste the text anywhere
5. See that it does not contain the link

**Expected behavior**
The video link should be copied into the clipboard.

**Screenshots**
![CopyLink](https://user-images.githubusercontent.com/15801806/86033208-def8be80-ba38-11ea-8b18-8ebc318aeaa3.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome, Firefox, Brave
 - Version: Latest

**Comment by PeterF521** [comment]
Yes, It doesn't work

**Comment by ojeytonwilliams** [comment]
Since we're no longer using Plyr, this is moot.
