### ISSUE TITLE
Legacy Certificates Not Labelled As Legacy

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#39169]
**Describe the bug**
With the first wave of v7 going live, the Information Security and Full Stack certificates have correctly moved to a "Legacy" header. The certificates, themselves, have not been labelled as "legacy", however. 

**To Reproduce**

**Expected behavior**
The Legacy certificates should probably say "Legacy" on them, and the URL should be updated from `https://www.freecodecamp.org/certification/nhcarrigan/information-security-and-quality-assurance` to `https://www.freecodecamp.org/certification/nhcarrigan/legacy-information-security-and-quality-assurance`, as an example, to prevent possible conflict with the new certificates.

**Screenshots**
![image](https://user-images.githubusercontent.com/63889819/86386301-6cf5c480-bc46-11ea-89fc-81e2e8ca12e0.png)
![image](https://user-images.githubusercontent.com/63889819/86386343-75e69600-bc46-11ea-9679-e7cdf85de189.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 v. 1909
 - Browser: Chrome
 - Version: 83.0.4103.116

**Additional Context**
I will update this issue after I've claimed the new information security certificate to see how that behaviour is implemented.

**Comment by ojeytonwilliams** [comment]
Hey @nhcarrigan thanks for bringing this up.  As for the URLs, they're not supposed to change.  The intention is that people can link to them from outside and rely on those links continuing to point to their certificates.

Once you have the newer one it should have a unique link (and not have the word legacy in it!).

**Comment by dboydgit** [comment]
Is there an issue here? Was going to work on it, but not sure what the issue is.

**Comment by scissorsneedfoodtoo** [comment]
Hi @nhcarrigan, thanks for catching this.

If I remember correctly, leaving the slug as `/information-security-and-quality-assurance` was a conscious decision so links to already claimed certificates don't break as @ojeytonwilliams mentioned. While we did change the URLs to other certificates in the past, we have to manage those redirects manually.

The new certificates have different names/versioned slugs (`/information-security-v7`). Going forward, the plan is to use the versioned slugs to determine whether a certificate is legacy or not. For instance, if we make a change to the information security certificate, `/information-security-v7` will have the legacy header like in your screenshots, and `/information-security-v8` will be the current one.

I think we can probably close this issue if all the new certificates behave the same way.

**Comment by nhcarrigan** [comment]
I ran into no issues when testing the certificates on the local instance with the development user. 🙂

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for confirming that @nhcarrigan. I'll close this for now, but please feel free to reopen it if you notice anything else that we missed earlier.
