### ISSUE TITLE
Disable YouTube recommendations in embeded player

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/freeCodeCamp#39163]
We previously attempted this in https://github.com/freeCodeCamp/freeCodeCamp/commit/df6a4f649d762a347add209c7323c0f9bcf0288c, which had its own set of issues.

We need the Plyr to work natively with Youtube or alternatively make the YouTube embed not show related videos.

**Comment by lopeselio** [comment]
Can I work on this ?

**Comment by raisedadead** [comment]
I think this is resolved by a recent PR. We are keeping this open for verification. We have lots of other issues open which we could use your help with. 

Thanks.
