### ISSUE TITLE
URL shortener project's example looks like it's broken

### ISSUE THREAD

**Issue by willnwhite** [freeCodeCamp/freeCodeCamp#39161]
The URL shortener project's [example](https://thread-paper.glitch.me/) would not pass the project's tests.

[URL shortener project](https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/url-shortener-microservice)

**Comment by raisedadead** [comment]
Closing in favor of https://github.com/freeCodeCamp/freeCodeCamp/issues/37305
