### ISSUE TITLE
Get send back to the login screen after login in it's an endless loop

### ISSUE THREAD

**Issue by Mia1993-star** [freeCodeCamp/freeCodeCamp#39165]
**Describe your problem and how to reproduce it:**
https://www.freecodecamp.dev/learn/scientific-computing-with-python/scientific-computing-with-python-projects/arithmetic-formatter
When i click the ask for help button it ask me to login while I am already am logged in.
I get send to the next page
https://forum.freecodecamp.dev/categories
When i then try to login  with my google account it does nothing and just returns me to the login page

**Add a Link to the page with the problem:**

**Tell us about your browser and operating system:**
* Browser Name: Chrome newest version
* Browser Version: Chrome 83.
* Operating System:  Windows 10

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by raisedadead** [comment]
The dev site is a staging/test instance. You should be using the live site. We just launched the Python curriculum on the live site BTW.

I will check the issues with the dev site. Chances are its broken. Can you confirm you are able to work on the production/live site:

https://freecodecamp.org/learn

**Comment by raisedadead** [comment]
Closing to avoid confusing contributors, I will have the dev site at parity with production soon
