### ISSUE TITLE
Example app link not working: APIs and Microservices Projects - URL Shortener Microservice

### ISSUE THREAD

**Issue by limvus** [freeCodeCamp/freeCodeCamp#39173]
Go to :
https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/url-shortener-microservice

Then click on:
 https://thread-paper.glitch.me/.

Expected:
- sample url shortner app

Sees:
- blank page with title: "listing directory/"
- blank page with character: "~ /"

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @limvus. This seems to be a problem on Glitch's end, though it hasn't been reported on https://status.glitch.com/ yet.

I've reached out to the Glitch support team to see if they can restore the project. If they're not able to for some reason, we'll create a new sample project and update the link on the challenge page.

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo Can we close this issue now that we are using repl.it?

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, thanks for catching this.

@limvus, thanks again for reporting this. While this project is still available on Glitch, we've moved the backend projects to Repl.it. The URL for the Repl.it version is here: https://url-shortener.freecodecamp.repl.co/.
