### ISSUE TITLE
Landing page redesign

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#39179]
Here is a mock that illustrates the different sections that will be included in the redesign.

The followings will be implemented differently from the following mock:
- the camper images should be squared and form a perfect grid.
- the logo icon in each link button will display the most prominent technology that each certification teaches.
- the pattern in the background of the certification section will have more white space and the legos will be smaller.
- the CTA's will be smaller.
- the camper images should not load for mobile.
- the order of the certificates should reflect the current order of the landing page.

The list of logo/icons for the cert list:
* a monitor screen overlapped by cellphone : Responsive Web Design 
* JS logo: JavaScript Algorithms and Data Structures 
* React logo: Front End Libraries 
* D3 logo: Data Visualization 
* Node logo: APIs and Microservices 
* clipboard with checkmark:   Quality Assurance 
* PY logo:	Scientific Computing with Python 
*  Chart: Data Analysis with Python 
*  Shield: Information Security 
* TensorFlow logo: Machine Learning with Python

![image](https://user-images.githubusercontent.com/4591597/86466792-f687be00-bd3c-11ea-881a-93b17ebef653.png)

**Comment by RandellDawson** [comment]
I really like the look of the home page!

**Comment by PeterF521** [comment]
Yes, I also like very much

**Comment by Stephenklop** [comment]
I really like it! Is someone already working on this?

**Comment by ahmadabdolsaheb** [comment]
Thank you @Stephenklop for you interest.
I am finalizing some details regarding the logos, and we will divide this issue into manageable pieces. I will keep you updated.

**Comment by Stephenklop** [comment]
Awesome! Let me know.

**Comment by ahmadabdolsaheb** [comment]
Most of the objectives mentioned in this pr have been met.
