### ISSUE TITLE
Validate test text before next-curriculum goes live

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39177]
The test `text` strings need auditing before 

https://github.com/freeCodeCamp/freeCodeCamp/pull/39176

goes into production.

**Comment by raisedadead** [comment]
Can you elaborate what this is about a bit more? Thanks.

**Comment by ojeytonwilliams** [comment]
Yeah, I could have been clearer.

Before that PR, the `text` description of a test was just a snippet of html.  No processing happened.  After that PR, they are parsed as markdown.  In most cases this won't matter, but something like `x = 2*3*2` would become `x = 2<em>3</em>2`.

**Comment by RandellDawson** [comment]
@ojeytonwilliams Any suggestions on how best to perform an audit to find odd cases?  Could we create a one-off script that compares all the `text` strings as the final compiled markdown to the original string (removing any backticks) to make sure they ar the same?

**Comment by raisedadead** [comment]
Ah - this is something that can be easily overlooked. Will we be able to catch this with some form of linting.

**Comment by ojeytonwilliams** [comment]
> @ojeytonwilliams Any suggestions on how best to perform an audit to find odd cases? Could we create a one-off script that compares all the `text` strings as the final compiled markdown to the original string (removing any backticks) to make sure they are the same? You may have some code already written that could be easily modified to do such a comparison. If not, I can probably write something fairly quickly.

Basically, yes, what I was thinking was something similar to this:

```js
for(let text of tests) {
  let parsed = parseMarkdown(text);
  if(trimPTags(parsed) !== text) {
   console.log(text);
  }
}
```

That will catch all the tests with any markdown in.  If that proves to be too many, we'd need to rethink, but hopefully that's enough that a human can quickly scan through and fix.

Backticks are tricky, since someone might put them in expecting them to make it into the final html.  We probably shouldn't remove them unless we're faced with a crazy amount of `<code>` tags.
