### ISSUE TITLE
Data Analysis with Python Projects - pyproject.toml - 'description' is a required property

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#39175]
**Describe your problem and how to reproduce it:**
Repl.it started to fail to update package configuration when `description` property is missing from `pyproject.toml` file.
```
Repl.it: Updating package configuration

--> python3 -m poetry lock

[RuntimeError]
The Poetry configuration is invalid:
  - 'description' is a required property

exit status 1


Repl.it: Package operation failed.
```
There are currently 3 affected projects with this issue. This can be solved even by empty description as it is in one of the working projects - https://repl.it/@freeCodeCamp/fcc-demographic-data-analyzer#pyproject.toml.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/medical-data-visualizer
https://repl.it/@freeCodeCamp/fcc-medical-data-visualizer#pyproject.toml
https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/page-view-time-series-visualizer
https://repl.it/@freeCodeCamp/fcc-time-series-visualizer#pyproject.toml
https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/sea-level-predictor
https://repl.it/@freeCodeCamp/fcc-sea-level-predictor#pyproject.toml

**Comment by RandellDawson** [comment]
@beaucarnes Is this an issue still needing resolution?

**Comment by RandellDawson** [comment]
@gikf The boilerplates have been fixed, so I am closing this issue.  If you are still experiencing an problems, please request it to be reopened
