### ISSUE TITLE
Failure to unsubscribe from freecodecamp Quincy Larson emails

### ISSUE THREAD

**Issue by povilasraciunas** [freeCodeCamp/freeCodeCamp#39183]
Link: https://www.freecodecamp.org/ue/WWtGC_9cRB0T0oqlPD8sw
Pressing on the provided link throws user to page with error: "Oops! Something went wrong. Please try again in a moment."

Email: 

Quincy Larson <quincy@freecodecamp.org> | Quincy Larson <quincy@freecodecamp.org> | 8:49 AM (12 hours ago) |   |  
-- | -- | -- | -- | --
Quincy Larson <quincy@freecodecamp.org>
to me | to me
to me

**Comment by raisedadead** [comment]
Hi @povilasraciunas 

Thanks for reporting, you had a duplicate account with us. I have now removed the duplicate account and set the unsubscription on your records. 

You will not be receiving the weekly emails from Quincy. Sorry about the inconvenience.

**Comment by povilasraciunas** [comment]
Hey Mrugesh,

Great many thanks! :)

**Comment by XuanLi-Leong** [comment]
Hi @raisedadead , I'm having the same problem. This is my unsubscribe link: https://www.freecodecamp.org/ue/1C495Xaw8ToisryzCOKLs

**Comment by scissorsneedfoodtoo** [comment]
Hey @XuanLi-Leong, thanks for your patience.

Please send us an email at support@freecodecamp.org and I can help you with this.
