### ISSUE TITLE
Forum Category Dropdown values are not full width

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#39185]
**Describe the bug**
When trying to reclassify a category using the Category dropdown menu, the text content does not take up the full width of the dropdown.   This seems to have changed in the recent migration.

**To Reproduce**
1. Go to any preexisting topic.
2. Click on the Category dropdown to change the category,
3. See issue.

**Expected behavior**
I expect the text to take up the full width so that you do not have to scroll down as far to find the desired category.

**Screenshots**
![image](https://user-images.githubusercontent.com/5313213/86500145-035be000-bd44-11ea-94b3-de2ee09b71a1.png)

**Desktop (please complete the following information):**
 - OS: Windows 2010 Home Edition
 - Browser: Chrome
 - Version: 83.0.4103.116 (Official Build) (64-bit)

**Comment by ptkpyitheim** [comment]
@ahmadabdolsaheb Hi! Have you had any progress on this bug? I see you self-assigned. I was wondering if you'd need any help? I'm trying to look into it right now.

**Comment by ptkpyitheim** [comment]
@RandellDawson Could you describe more in details how to reproduce the screenshot you have?

**Comment by nhcarrigan** [comment]
Hello~!

I can confirm this bug - it appears when trying to modify the categories of a topic after it has been posted. 
![image](https://user-images.githubusercontent.com/63889819/87053695-1ee93f80-c1b7-11ea-8a1f-ac8e8883c8e7.png)

**Comment by ahmadabdolsaheb** [comment]
@ptkpyitheim, please go ahead if you have a solution in mind.

**Comment by RandellDawson** [comment]
I have updated the issue body to reflect what @nhcarrigan stated (which I should have done originally).

**Comment by ptkpyitheim** [comment]
@RandellDawson For some reason I cannot reproduce the bug. Would you be able to send a link? I'm using MacOS and I'm using Chrome

**Comment by RandellDawson** [comment]
@ptkpyitheim If you go to any topic that you have already created and try to change the category, you should see the issue.  Can you show a screen shot of what you see when you attempt to change an existing topic's category?

**Comment by ptkpyitheim** [comment]
Okay I see the issue now. I wish I knew I had to sign up for an account and create a new topic in order to see the bug. The original description assumed that and going to a preexisting topic doesn't necessarily means it's a topic I created.

I'll take a better look.

**Comment by ptkpyitheim** [comment]
It seems like there's a max-width that's being set. In my inspector I see that a max-width has been set for each `li` tags. Unselected that stretches out.

![Deselected](https://user-images.githubusercontent.com/36285777/87557065-155f4c00-c67d-11ea-8930-7c09bc5b66b4.png)
![Selected](https://user-images.githubusercontent.com/36285777/87557077-17290f80-c67d-11ea-8941-6ed944c1672a.png)

**Comment by RandellDawson** [comment]
I [reported the issue](https://meta.discourse.org/t/category-dropdown-content-not-full-width/157875) to Discourse and they acknowledged the issue and merged a PR to fix it about an hour after reporting.

@raisedadead What do we need to do to get this update from Discourse?  Will it just get added to their next release?

If it is just a matter of waiting till they ship to production, should I go ahead and close this issue and add the `status: resolved/shipping` label to it?

**Comment by RandellDawson** [comment]
> Okay I see the issue now. I wish I knew I had to sign up for an account and create a new topic in order to see the bug. The original description assumed that and going to a preexisting topic doesn't necessarily means it's a topic I created.
> 
> I'll take a better look.

@ptkpyitheim Sorry for any confusion in the issue description.  I forgot about the fact that moderators can go in and modify anyone's category.  I wrote the description without considering that normal users can only change their own topic.

**Comment by ahmadabdolsaheb** [comment]
if we are not planning to update our discourse, I can make the necessary changes from our theme.

**Comment by RandellDawson** [comment]
This bug was fixed by Discourse and has been applied to our instance.
