### ISSUE TITLE
Can You fix the typos in the landing page ? About the 40,000 freeCodeCamp.org graduates !

### ISSUE THREAD

**Issue by medaminefh** [freeCodeCamp/freeCodeCamp#39184]
**Describe your problem and how to reproduce it:**
the number of the graduates , it seems must be updated ...
Just want to try contributing on open source lol 
**Add a Link to the page with the problem:**

https://www.freecodecamp.org/
**Recommended fix, suggestions (how would you update it?):**
50,000 freeCodeCamp.org graduates 
actually you have the exact number

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by raisedadead** [comment]
Not sure where you are getting that no from? Can you send us an email on team@freecodecamp.org instead for a clarification before we check and get this updated.
