### ISSUE TITLE
Create a redirect for www.freecodecamp.com/wiki to the Github Wiki

### ISSUE THREAD

**Issue by CodeNonprofit** [FreeCodeCamp/FreeCodeCamp#3918]

**Comment by krantzinator** [comment]
I will take a crack at this

**Comment by BerkeleyTrue** [comment]
All yours!

**Comment by iTypeSlow** [comment]
good luck!

**Comment by QuincyLarson** [comment]
I added this real quick. It'll be in tonight's wave of curriculum commits. Sorry for jumping the queue, @krantzinator

**Comment by krantzinator** [comment]
no worries @QuincyLarson I was still in the research phase. I'll look for something else to help with

**Comment by ltegman** [comment]
Closed by commit baaae04.
