### ISSUE TITLE
update /learn footer based on /news

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#39195]
The footer on /lean should be changed to look identical to /news.
Here is the footer on news: https://github.com/freeCodeCamp/news-theme/blob/master/partials/footer.hbs
and here is the footer styles https://github.com/freeCodeCamp/news-theme/blob/4b1e1a52c9900147095ee2d3202b43b0dc116870/assets/css/screen.css#L2204

**Comment by PeterF521** [comment]
What do you want to do? Explain it better, please ;)

**Comment by ahmadabdolsaheb** [comment]
@PeterF521, thanks for taking a look. I updated the description. It should be easier to understand now.

**Comment by PeterF521** [comment]
I understanded now!

**Comment by PeterF521** [comment]
So do you want to upgrade the `Trending Guides`, right? I think that is better also add `Our Nonprofit` section on */news* page.

**Comment by ahmadabdolsaheb** [comment]
The trending guides and the styles of the footer will be changed and the current news version of the footer is optimized for SEO so we will stick to that for this iteration.

**Comment by PeterF521** [comment]
Ok
