### ISSUE TITLE
Stubs in Hint pages can't be replied to or edited

### ISSUE THREAD

**Issue by dstollbyu** [freeCodeCamp/freeCodeCamp#39198]
**Describe your problem and how to reproduce it:**
I’ve noticed that a number of hint pages for exercises have “This is a stub. Help the community by replying below with your hints and solutions. We can use those to create a guide article for this.”

There is no option to reply or edit the document, and I can understand that it’s to prevent a flood of unwanted edits. In that case, what should we do if we have a solution to suggest?

**Add a Link to the page with the problem:**
[https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-perform-classic-updates-by-running-find-edit-then-save/301541](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-perform-classic-updates-by-running-find-edit-then-save/301541)

**Recommended fix, suggestions (how would you update it?):**
Add a reply option, perhaps?

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/9387346/86803835-9726f800-c033-11ea-81e4-9b1f8946ecf4.png)

**Comment by raisedadead** [comment]
> In that case, what should we do if we have a solution to suggest?

I think, creating an issue on this tracker is the best approach here. Hey @RandellDawson can you guide here.

**Comment by RandellDawson** [comment]
If someone wants to suggest a solution for a challenge, would the Contributor's category not be the place for it?  Also, the user should explain what makes their approach unique.  If it is just a syntax change, we may not accept it.  It would need to be an algorithmic approach not already covered by the existing solutions.

**Comment by dstollbyu** [comment]
If the contributor's category is the place to make suggestions, could that be indicated in the stub pages?

**Comment by raisedadead** [comment]
> If the contributor's category is the place to make suggestions, could that be indicated in the stub pages?

That's actually how it should be. @RandellDawson do you know how we could possibly do this programatically.

**Comment by RandellDawson** [comment]
@raisedadead I already have a query that gets the topic id  of any stub topic.  I have a script that can be modified to replace the content with anything you want.  I used the same script to create these stub pages when everything was ported over from the repo.

There are currently 698 stub pages.  Just let me know what you think the content should state and I can update all of them in one pass.

**Comment by raisedadead** [comment]
Sure go ahead.

**Comment by Sky020** [comment]
@RandellDawson , would it be possible to have the stub contain a link with a template for creating the post? Something including (at a minimum) the link to the stub?

**Comment by raisedadead** [comment]
Yup, we have the template on the contributing docs, right? That could be linked.

**Comment by RandellDawson** [comment]
Yes, the documentation has the template, but that would only be useful for the mods, since we have locked down the wikis.  

I finished updating the 673 stub topics with the content we discussed earlier in this issue, but we can accomplish two things at once:
1. Use the same stub message I just used earlier at the top of the topic (below the heading back link to the challenge)
2. Add the template we are currently using to stub.  This would make it easier for mods to start putting information in as they receive the suggestions via the `Contributors` category topics.  For demonstration purposes, I have updated [this topic](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-problem-480-the-last-question/302158) with my newly proposed stub.

**Comment by Sky020** [comment]
@RandellDawson , sorry, miscommunication. What I meant is, users are posting asking for stubs to be changed, without providing a link to the stub. So, I was wondering how easy it would be for a template to be made similar to how using the _Ask for Help_ button on a challenge creates one...

**Comment by RandellDawson** [comment]
@Sky020 Can you take the existing Ask for help content and create a template with what you would want the topic to look like?

**Comment by RandellDawson** [comment]
Actually, I have come up with a way to add a link which creates a new topic like the Ask For Help button does.  Check out [this topic](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-problem-305-reflexive-position/301959) to see how it looks.

@raisedadead If you and @Sky020 think this is a good idea, that I can run the script I created to do this for the 690+ stubs.  It will take about 30 minutes to complete, so we don't overload the forum down too much.

**Comment by nhcarrigan** [comment]
I really like the addition of that link.

**Comment by Sky020** [comment]
@RandellDawson That is excellent! The only thing I might suggest is for the title to also be pre-filled. Perhaps something simple to sort through the topics in Contributors so we **know** it is a suggestion?

**Comment by RandellDawson** [comment]
> Perhaps something simple to sort through the topics in Contributors so we know it is a suggestion?

I could add something but the user will still have to create a unique title because Discourse does not allow duplicate titles.  It also needs to be short to allow the user to add something to the end of it.  Any suggestions are welcome.

**Comment by RandellDawson** [comment]
I am closing this issue as there is now a link in the stub that allows a user to create a new topic in the Contributors category which will automatically have the challenge title and challenge url in it.
