### ISSUE TITLE
Spelling bug 

### ISSUE THREAD

**Issue by shivam17299** [freeCodeCamp/freeCodeCamp#39191]
**Describe your problem and how to reproduce it:**

There is spelling mistake of "KERAS" instead of "KARAS" in first paragraph first row.

**Add a Link to the page with the problem:**
link: https://www.freecodecamp.org/learn/machine-learning-with-python/machine-learning-with-python-projects/cat-and-dog-image-classifier

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/32490866/86529206-7001e680-becc-11ea-9541-fdd4f00f7b1c.png)

**Comment by Sky020** [comment]
Thank you, for spotting this. I am opening this to _first-timers_.
