### ISSUE TITLE
learn: Change instructions to be less restrictive in Slice and Splice challenge

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#39192]
In the [Slice and Splice](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/slice-and-splice) challenge, the following line tells users to use `slice` and `splice`, but the tests do not force the user to use `slice` and `splice`.  Since this is an algorithm challenge, I believe we should let the users write the code any way that solves the problem.  My suggestion is to change the line's text to the following:
> Copy each element of the first array into the second array, in order.

@scissorsneedfoodtoo @thecodingaviator @Manish-Giri Any thoughts?

**Comment by PeterF521** [comment]
I'll try to solve problem

**Comment by RandellDawson** [comment]
@PeterF521 Before creating a PR, let's wait for feedback from at least one of the users I tagged.

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, sure, that sounds like a good idea, especially since we're not testing for those methods.

**Comment by thecodingaviator** [comment]
@RandellDawson I think this sounds like a good improvement

**Comment by PeterF521** [comment]
ok

**Comment by RandellDawson** [comment]
@PeterF521 Go for it.

**Comment by PeterF521** [comment]
Nice, I'm thinking use `asset.CallTracker` on the testString, but I first want to know what's the asset version used on this repository.
If you want that I use other way, please tell me. I also want to learn more about JavaScript

**Comment by PeterF521** [comment]
Or use `typeof` keyword?

**Comment by Sky020** [comment]
Hello @PeterF521 ,

There should be no need for either of those. The idea is to change the wording of this line of text: 
>Use the array methods slice and splice to copy each element of the first array into the second array, in order.

To this:
> Copy each element of the first array into the second array, in order.

There is no need to change the tests, as they do not check for the `slice` or `splice` methods.

**Comment by PeterF521** [comment]
Thanks. It's very much easy!
