### ISSUE TITLE
Logical Mistake in JS course

### ISSUE THREAD

**Issue by emrahkilic** [freeCodeCamp/freeCodeCamp#39200]
In JS Record Collection topic, there is a logical mistake. When you try to update the collection object, if the input is an empty track, then you completely delete the tracks array. Your aim should be to update the object, not to delete existing data inside the object.

Link of the course topic: https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/record-collection

**Comment by RandellDawson** [comment]
@emrahkilic 

> Your aim should be to update the object, 

To what would you update the object in the case of an empty track input value?  How else would you be able to know when to delete the property from the object?

**Comment by emrahkilic** [comment]
You don't have to update it but you are not supposed to delete the existing data, right? Check out the element with id = 2548. You have nothing to add in tracks array but your code/logic delete the whole already existing array.  Why? This is problematic. It took hours for me to understand the logic behind because it's nonsense. Why would I want to delete my existing data if I don't have anything to add or change? That function's main aim is to add new data to the object. Not to delete existing data. Please check it out again, you'll see what I mean.

**Comment by RandellDawson** [comment]
@emrahkilic 

> That function's main aim is to add new data to the object. Not to delete existing data.

According to the instructions, one of the requirements (rules) of of the function is to delete a property if the value passed to it is an empty string.  See below for the stated rule in the instructions.

>If value is empty (""), delete the given prop property from the album.

So yes, you are supposed to delete the property "tracks" if the `value` argument is an empty string.

> Why would I want to delete my existing data if I don't have anything to add or change?

Like all challenges and real-life code, you will be given requirements that a particular section of code or function must be able to meet.  You may not always agree with the requirements, but you still must make your code work within the constraints.  In this particular challenge, they wanted to be able to delete a property from the album.  There are a many ways this could have been handled and deleting the property when the `value` argument is an empty string is just one such approach.

In the future, please use our [forum](https:://forum.freecodecamp.org) when have problems on a challenge.  The users there will almost always be able to guide you to a better understanding of a challenge's requirements.  Thank you.

**Comment by RandellDawson** [comment]
I am closing this issue for now, since there is no bug in the challenge.  If you ask others on the forum about the problems you had with this challenge and they conclude a change is warranted, please reply back here and we can reopen the issue for further discussion. 

Thank you.

**Comment by emrahkilic** [comment]
You are right, there is no bug in the challenge. What I tried to emphasize is that it makes more sense if the logic behind the challenge is rational. That's all. I tried not to delete the existing array while coding and it gave error. Anyway, challenge is challenge. I just wanted to inform you in this instance.

Thank you.
