### ISSUE TITLE
challenges: add keyboard shortcut to run the tests

### ISSUE THREAD

**Issue by PeterF521** [freeCodeCamp/freeCodeCamp#39206]
**Is your feature request related to a problem? Please describe.**
If we stop to think better, It's so boring when we finish a challenge need to click in `Run the tests` button.

**Describe the solution you'd like**
It's more faster add a keyboard shortcut for this, like CTRL+ENTER.

**Additional context**
![Captura de ecrã de 2020-07-08 09-21-45](https://user-images.githubusercontent.com/61094663/86896449-e174ab80-c0fd-11ea-8d6e-1f0d84f40e5f.png)

**Comment by Sky020** [comment]
Hello there,

I will refer you to this guide: https://forum.freecodecamp.org/t/free-code-camp-hotkeys/59467

`Ctrl + Enter` does do exactly that, already. However, the editor frame must be in focus.

I am closing this for now.

**Comment by PeterF521** [comment]
ok
