### ISSUE TITLE
Rosetta Code: Tokenize a string with escaping - swapped parameters in starting code

### ISSUE THREAD

**Issue by sanityto** [freeCodeCamp/freeCodeCamp#39205]
**Describe your problem and how to reproduce it:**
`esc` and `sep` parameters are swapped in the starting code. As description and tests suggests second parameter should be separator character and third one escape character.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/tokenize-a-string-with-escaping

**Comment by Sky020** [comment]
Thank you, for pointing this out. Not a major issue, but makes sense to change. I am opening this up for _first-timers_
