### ISSUE TITLE
Add "annotations" to news articles

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/freeCodeCamp#39202]
**Is your feature request related to a problem? Please describe.**
Not much of a problem. More of an enhancement to the news platform. Currently, there is no way to engage with the content or comment on certain sections to update the code to any updates or caveats from within the article. Comments could work, but are disconnected with the content and you have to go back and forth on the area of the content and the comment itself.

**Describe the solution you'd like**
There is an open-source project initiative, called Hypothesis https://web.hypothes.is/, where you can essentially make comments and make note of additions to the existing content. See this page for examples of how it might work https://web.hypothes.is/examples-of-classroom-use/.

Here is a visual example of what it looks like. Note the right hand side of the page. It is collapsible so it doesn't have to be there all the time.

![](https://d242fdlp0qlcia.cloudfront.net/uploads/2016/03/25223636/2016-03-23_1448-1.png)

It appears you'll just need to add in a script tag to add it to the site https://web.hypothes.is/for-publishers/#embedding.

```html
<script src="https://hypothes.is/embed.js" async></script>
```

In sum, hypothesis could be a good intermediate to go full on Wikipedia everyone can edit content and to add in helpful notes for others to follow in case the articles themselves are not clear or readers find other insightful and related to share. Low priority feature, but it might be interesting to have.

**Describe alternatives you've considered**
Adding a comment section.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
