### ISSUE TITLE
code block does not show horizontal scroll bar on Chrome, macOS

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#39217]
When the the code in the code block is wider that the containing column, the horizontal scroll bar is not displayed.
Note: the horizontal scroll is displayed when the user scrolls horizontally, but it is not displayed otherwise.

for instance:
https://www.freecodecamp.org/learn/machine-learning-with-python/tensorflow/natural-language-processing-with-rnns-building-the-model

OS: macOS
browser: Chrome

![image](https://user-images.githubusercontent.com/4591597/87076255-2a298300-c22a-11ea-97ec-9d35e76013bd.png)

**Comment by finhaa** [comment]
Hey @ahmadabdolsaheb, I think this is an expected behavior as the same we can observe in the right scrollbar on the page right here in github and on the freecodecamp itself.

**Comment by ahmadabdolsaheb** [comment]
Correct. the browser itself is expected to be scrollable, but I was wondering if it obvious to the user that code block is scrollable?

If it is not, we might need display the scrollbar.

**Comment by finhaa** [comment]
Yeah, correct! 

I can't solve this doubt about that. In my view, I see the code block as something scrollable, but I can't guarantee that all users see it that way.

We may wait for more people on this discussion.

**Comment by fuzzyray** [comment]
This works as expected for me on MacOS Mojave 10.14.6 with Chrome, Safari, Firefox and Opera. I see the horizontal scrollbar for the code block and can use it.

**Comment by ahmadabdolsaheb** [comment]
I am closing this issue as the behavior  seems to be expected for mac users.
