### ISSUE TITLE
Make sure each of your div elements has a closing tag????

### ISSUE THREAD

**Issue by leonardolatorre** [FreeCodeCamp/FreeCodeCamp#3921]
Waypoint: Line up Form Elements Responsively with Bootstrap

Can't find a solution...

<img width="1263" alt="screen shot 2015-10-26 at 21 25 06" src="https://cloud.githubusercontent.com/assets/12745976/10743213/8f16dfc0-7c29-11e5-808a-9222e96ffb53.png">

```

<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
    </div>
  </div>
  <img src="http://bit.ly/fcc-running-cats" class="img-responsive">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <div class="row">
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Indoor</label>
      </div>
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Loving</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Lazy</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Crazy</label>
      </div>
    </div>
<div class="row">
    <div class="col-xs-7"> 
      <input type="text" class="form-control" placeholder="cat photo URL" required>
    </div>
    <div class="col-xs-5">
      <button type="submit" class="btn btn-primary">
        <i class="fa fa-paper-plane"> Submit</i>
      </button>
    </div>
  </form>
</div>

```

**Comment by ltegman** [comment]
Please include the name of the challenge you're working on and a text copy of your code (formatted with markdown) in your bugs so that we can properly assist in figuring out what is wrong.

**Comment by QuincyLarson** [comment]
@leonardolatorre You were missing a closing div. One of your div elements wasn't properly indented, and that threw off everything below it. Here's the fixed code for your reference:

```
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }

</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
    </div>
  </div>
  <img src="http://bit.ly/fcc-running-cats" class="img-responsive">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
  </div>
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <div class="row">
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Indoor</label>
      </div>
      <div class="col-xs-6">
        <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Loving</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Lazy</label>
      </div>
      <div class="col-xs-4">
        <label><input type="checkbox" name="personality"> Crazy</label>
      </div>
    </div>
<div class="row">
    <div class="col-xs-7"> 
      <input type="text" class="form-control" placeholder="cat photo URL" required>
    </div>
    <div class="col-xs-5">
      <button type="submit" class="btn btn-primary">
        <i class="fa fa-paper-plane"> Submit</i>
      </button>
    </div>
  </form>
</div>
```

**Comment by leonardolatorre** [comment]
Quincy, I copied the code but still doesn't work. Which of my DIV elements is not properly indexed?

**Comment by ESinopoli** [comment]
I get the same error - even when I copy and paste the code.

**Comment by ESinopoli** [comment]
I threw in a pretty random closing div and it worked. None of my code has the nice indents and formatting yours has. Is there a way to make it look like this? Its much easier to read.

**Comment by eheisse87** [comment]
I assume that what happened is that @QuincyLarson was right in that you were missing a </div> tag but it's not in the code he posted, so that's why it doesn't work if you copy and paste. It would also explain why @ESinopoli seemed to get it to work by throwing in a "random" closing div. You need another </div> tag for the <div class="row"> for the input and button elements below your closing </div> tag for the <div class="col-xs-5">. So many divs!

**Comment by sandboxmagician** [comment]
Oh my god, thank you for that Eheisse87. That extra div was driving me nuts!

**Comment by roseberry** [comment]
But what is the last </div> of all closing?? It wasn't there, or needed at the beginning of the challenge, and all new divs created during the challenge are already closed without it aren't they??

**Comment by tlwilliams895** [comment]
Same for me!! So glad I was able to figure out this code after reviewing the comments. Ughhhhhhh, I love to code!! LOL

**Comment by CantWeAllJustGitAlong** [comment]
Guys, I was stuck on this for awhile! I posted my code in the help forum and nobody could figure it out. Luckily, I found this string of posts. The only thing that worked was putting an EXTRA </div> before </form> but it makes no sense to me. All of the other challenges before this one passed without that EXTRA </div>. If someone can explain this to me like I'm 3 years old, I would appreciate it. Thanks.

**Comment by klingonunderwearmodel** [comment]
Yeah, this one threw me off as well until I added an extra </div> but I don't know why that fixed it.

**Comment by pleabargain** [comment]
I triple checked the divs... same problem as others above... 
here's the code https://gist.github.com/pleabargain/bdc1cf9a2f55eb814e03493f1152bc63
here's the video https://youtu.be/huEVjM0Qd9I

**Comment by VSatyavani** [comment]
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

<style>
  h2 {
    font-family: Lobster, Monospace;
  }

  .thick-green-border {
    border-color: green;
    border-width: 10px;
    border-style: solid;
    border-radius: 50%;
  }
</style>

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8">
      <h2 class="text-primary text-center">CatPhotoApp</h2>
    </div>
    <div class="col-xs-4">
      <a href="#"><img class="img-responsive thick-green-border" src="https://bit.ly/fcc-relaxing-cat"></a>
    </div>
  </div>
  <img src="http://bit.ly/fcc-running-cats" class="img-responsive">
  <div class="row">
    <div class="col-xs-4">
      <button class="btn btn-block btn-primary"><i class="fa fa-thumbs-up"></i> Like</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-info"><i class="fa fa-info-circle"></i> Info</button>
    </div>
    <div class="col-xs-4">
      <button class="btn btn-block btn-danger"><i class="fa fa-trash"></i> Delete</button>
    </div>
  </div>
 
  
  <p>Things cats <span class="text-danger">love:</span></p>
  <ul>
    <li>cat nip</li>
    <li>laser pointers</li>
    <li>lasagna</li>
  </ul>
  <p>Top 3 things cats hate:</p>
  <ol>
    <li>flea treatment</li>
    <li>thunder</li>
    <li>other cats</li>
  </ol>
  <form action="/submit-cat-photo">
    <label><input type="radio" name="indoor-outdoor"> Indoor</label>
    <label><input type="radio" name="indoor-outdoor"> Outdoor</label>
    <label><input type="checkbox" name="personality"> Loving</label>
    <label><input type="checkbox" name="personality"> Lazy</label>
    <label><input type="checkbox" name="personality"> Crazy</label>
    <input type="text" placeholder="cat photo URL" required>
    <button type="submit">Submit</button>
  </form>
</div>
