### ISSUE TITLE
Test Error on "Implement Selection Sort"

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/freeCodeCamp#39220]
**Describe your problem and how to reproduce it:**
The tests for this challenge require the user to NOT use the `.sort()` function. The particular testString that checks this uses a regex, but that regex will match an occurrence of the word `sort` (case-sensitive), so using a variable name such as `sortedArray` will cause this test case to fail erroneously.

**Add a Link to the page with the problem:**
[Implement Selection Sort challenge](https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-selection-sort)

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version:  83.0.4103.116
* Operating System: Windows 10 Home 1909

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Failing Code:
![image](https://user-images.githubusercontent.com/63889819/87102857-238a1400-c208-11ea-906c-a3293d467524.png)
Passing Code: 
![image](https://user-images.githubusercontent.com/63889819/87102870-2edd3f80-c208-11ea-9293-0d1aa244d2c4.png)
As a note, the code is not mine but was provided by a user when they requested debugging assistance.

**Comment by ruhci28** [comment]
Hye. Can I Work on this .?

**Comment by nhcarrigan** [comment]
Hello~!

While your eagerness to contribute is admirable and I do not want to discourage you, I think it best if we wait until the issue has been triaged first. 🙂

**Comment by ruhci28** [comment]
okay

**Comment by ojeytonwilliams** [comment]
Thanks for posting this @nhcarrigan, this definitely isn't working as intended.

@ruhci28 this is open for contributions now, so PRs are welcome.

**Comment by ruhci28** [comment]
okay I will start working on that

**Comment by Sky020** [comment]
Something similar to this should do: https://github.com/freeCodeCamp/freeCodeCamp/pull/38801/files

**Comment by ruhci28** [comment]
okay thanks for help

**Comment by nhcarrigan** [comment]
It looks like the issue is also present on the [Insertion Sort](https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-insertion-sort) and [Quick Sort](https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-quick-sort) challenges as well.

**Comment by KartikSoneji** [comment]
Note that adding this comment also fails the challenge:
```javascript
//sort
```

While this passes:
```javascript
array["s" + "ort"]((a, b) => a - b);
return array;
```

Maybe it is better to do
```javascript
delete Array.prototype.sort;
```
or
```javascript
Array.prototype.sort = () => failChallenge("Cannot use built-in Array.sort");
```

**Comment by KartikSoneji** [comment]
@RandellDawson did you see my comment?

**Comment by RandellDawson** [comment]
> @RandellDawson did you see my comment?

@KartikSoneji No I did not notice this comment before merging.  Sorry about that.  I am fine if you want to create a PR that implements something like the following for the 3 challenges PR #39230 affected.:

```
Array.prototype.sort = () => failChallenge("Cannot use built-in Array.sort");
```

**Comment by KartikSoneji** [comment]
@RandellDawson I have created a pull request, please take a look.
#39360
