### ISSUE TITLE
Confusing question in: Python for Everybody - Conditional Execution

### ISSUE THREAD

**Issue by aminah-sc** [freeCodeCamp/freeCodeCamp#39224]
**Problem:**

The question given on this page is: 'Which code is indented correctly to print "Yes" if x = 0 and y = 10?' Who can definitively say  anything about anyone's intention? It would be clearer to say something like, 'Which code is written correctly to print "Yes" if x = 0 and y = 10?'

**Link to the page with the problem:**

https://www.freecodecamp.org/learn/scientific-computing-with-python/python-for-everybody/conditional-execution

**Comment by nhcarrigan** [comment]
Hello!

It sounds like you might have misread the question as "Which code is intended", when the question says "Which code is *indented* correctly". 🙂

**Comment by aminah-sc** [comment]
Alas, you are absolutely right, so sorry!

**Comment by nhcarrigan** [comment]
No worries! Happens to all of us! 😅
