### ISSUE TITLE
Graph/Shortest Path Coding Challenge Suggestion

### ISSUE THREAD

**Issue by c-logan** [freeCodeCamp/freeCodeCamp#39238]
Hello all,

This is my first issue I have opened so please tell me if I am doing anything wrong. 

After brainstorming possible additions to the coding challenges, I feel that adding a problem (or a few problems) related to graphs/shortest path algorithms could be considered... I've gone through the challenges and while there are problems on BFS and DFS, graph problems seem like a fairly major topic that is not covered very heavily.

I would be happy to work on a challenge for implementing Dijkstra's algorithm, Kruskal's algorithm, or a related problem if others feel that this would be a good idea. I believe I have a pretty good idea of how to get started on it if the consensus is that this would be a worthwhile contribution, but if anyone has suggestions for how to go about doing this, it would of course be appreciated.

**Comment by c-logan** [comment]
![Weighted_Graph](https://user-images.githubusercontent.com/54512885/89246180-889f1280-d5d8-11ea-851d-a55d33d90cb8.jpg)

**Comment by moT01** [comment]
Sorry, you never got a response on this @c-logan. I think we would be okay adding something like that to the coding-interview-prep area. Do you still have any interest in this?

**Comment by moT01** [comment]
Closing as stale. If anyone thinks I am wrong in closing this, feel free to leave a comment and we can discuss revisiting it. Thanks and happy coding 🎉
