### ISSUE TITLE
Algorithms: Implement Insertion Sort - You can get it to pass even though the algorithm is not correct 

### ISSUE THREAD

**Issue by Azalen** [freeCodeCamp/freeCodeCamp#39233]
https://www.freecodecamp.org/learn/coding-interview-prep/algorithms/implement-insertion-sort

`
function insertionSort(array) {
  for(let i=1; i<array.length; i++){
    let toInsert = array[i];
    let j = i-1;
    while(j >= 0){
      if(toInsert < array[j]){
        array[j+1] = array[j];
      }
      else{
        array[j+1] = toInsert;
        break;
      } 
      j--
    }
    console.log(array)
  }
  return array;
}
insertionSort([5, 4, 33, 2, 8]);
`

Will make the challenge pass even though the code is not correct which my example shows. 

The test in the challenge passes, because by chance the first element in the test array is also the smallest and doesnt have to be changed. So adding a second test array with a first element not being the smallest element would solve that issue.

Browser: Chrome

**Comment by nhcarrigan** [comment]
I am able to confirm this bug.

**Comment by RandellDawson** [comment]
Would either of you like to add the necessary test?

**Comment by nhcarrigan** [comment]
I will defer to @Azalen for the opportunity to make a contribution.

If they do not want to make this change, then I can go ahead and do so. 🙂
