### ISSUE TITLE
Make hierarchy more clear for /learn

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#39231]
**Is your feature request related to a problem? Please describe.**
Recently I saw a tweet which I agree with:

![Screenshot (16)](https://user-images.githubusercontent.com/26724128/87220633-3f65f500-c383-11ea-9887-37e8993f9792.png)

**Describe the solution you'd like**
We need to make the hierarchy more clear. This issue is open for discussion.

**Comment by ahmadabdolsaheb** [comment]
I believe the issue request is regarding the map which will be split into multiple certification related mini maps when #39154 is finalized and merged.

**Comment by raisedadead** [comment]
Please continue on the #38820 thred instead.
