### ISSUE TITLE
Add to video courses links to repos

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/freeCodeCamp#39232]
We need to audit all of the video courses and add links to relevant repos, Jupyter Notebooks, and other resources.

For example, [this video challenge](https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/data-analysis-example-a) mentions a project but does not link to that project.

In this case, I believe all the necessary links for this particular video series are here: https://www.youtube.com/watch?v=r-uOLxNrNk8

**Comment by beaucarnes** [comment]
Just made a PR with resource links for every Data Analysis video challenge.

**Comment by Sky020** [comment]
Hello there,

I am just pinging this to make sure nothing has missed the pipeline, as the live platform still does not have the links?

**Comment by WPDChristos** [comment]
I cannot find the exercises guys, sorry!

**Comment by gaurav9799** [comment]
I cannot find the exercises
