### ISSUE TITLE
Proposed tool for community translations

### ISSUE THREAD

**Issue by ilyaspiridonov** [freeCodeCamp/freeCodeCamp#39235]
Please consider using [GitLocalize](https://gitlocalize.com) to manage community translations.
It's free, supports .md and syncs with GitHub directly.

**Comment by raisedadead** [comment]
Hi @ilyaspiridonov 

Thanks for your recomendation. We are already in the process of integrating a tool. Although, its too early for us to announce the same, we are making good progress. 

I would recommend to keep an eye out by joining our [community forum](https://www.freecodecamp.org/forum) to know when we make an announcement.

Happy contributing.
