### ISSUE TITLE
Python Project - Time Series Visualizer

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#39244]
**Describe your problem and how to reproduce it:**
As mentioned in [this forum post](https://forum.freecodecamp.org/t/page-view-time-series-visualizer-test-error/409465), the tests appear to be missing a flag to allow the dataframe to be converted to an integer.

Whilst the README.md does allude to starting by converting the data to purely `index -> value`, I believe it would be more useful to include the flag:
>Use Pandas to import the data from "fcc-forum-pageviews.csv". Set the index to the "date" column.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/page-view-time-series-visualizer
Project to test: https://repl.it/@Sky020/fcc-time-series-visualizer#test_module.py

**Fix**:
Add the `numeric-only=True` argument to the `df.count()` method.

**Comment by KaniahDunn** [comment]
Hi, I would like to take a try at this - if it is still available.

**Comment by Sky020** [comment]
Hello @KaniahDunn .

This issue has yet to be _triaged_. What this means is we are yet to decide whether to go ahead with resolving it.

You are welcome to pick up any issue which has a _help wanted_ label, and does not already have a PR likely to close it.

@scissorsneedfoodtoo Do you think this change would be useful?

**Comment by KaniahDunn** [comment]
Ah, thank you for the clarification @Sky020 . I will look around for other issues that I might be able to pick up. 

Thank you 😊

**Comment by scissorsneedfoodtoo** [comment]
Hi @Sky020, thanks for your patience. This looks good to me. It makes sense to add that flag to the tests since they were probably designed to expect numeric values.

What do you think @beaucarnes?

**Comment by Sky020** [comment]
File with the problem: https://github.com/freeCodeCamp/boilerplate-page-view-time-series-visualizer/blob/master/test_module.py

Inside the `boilerplate-page-view-time-series-visualizer` repo

**Comment by tareq12345** [comment]
@Sky020  I have added a pull request can you review it

**Comment by Sky020** [comment]
Hello @tareq12345 , Thank you, for your PR. However, _ricknjacky_ already opened a PR before yours. So, we are going to prioritise theirs.

We welcome you to work on another open issue.

**Comment by jaenilparekh1234** [comment]
hi
what is this for?
