### ISSUE TITLE
Date Analysis with Python: demographic-data-analyzer has incorrect `assertAlmostEqual` function calls

### ISSUE THREAD

**Issue by moustachio-belvedere** [freeCodeCamp/freeCodeCamp#39243]
**Describe your problem and how to reproduce it:**
The three issues with the `assertAlmostEqual` function calls are as follows:

- an assertion error message is passed as a positional argument, resulting in the assertion not being called correctly. Changing this to pass as a keyword argument with keyword `msg` fixes this.

- the expected values in the assertion are rounded to one decimal place, but actual values outputted in (correct) program is many decimal places so the assertion fails. Manually rounding each result in the function before sending to test fixes this. But rounding seems unneccessary burden to the user, especially as you would only know to do it if you looked at the tests very carefully.

- expected `top_IN_occupation` appears to be incorrect, I get `Private` but expected in test is `Prof-specialty` even though there are none of this profession (in India and salary >50K) in the dataset. Apologies if I'm incorrect here.

**Add a Link to the page with the problem:**
https://repl.it/@freeCodeCamp/fcc-demographic-data-analyzer#README.md

**Tell us about your browser and operating system:**
* Browser Name: Mozilla Firefox
* Browser Version: 78.02
* Operating System: Windows 7

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
n/a

========================================================
I'm happy to create a PR for this but it would be good to have other opinions to make sure I'm not mistaken about anything before I go ahead.

In case it is of any use, my modified version is here: https://repl.it/@moustachiobelve/fcc-demographic-data-analyze

**Update: corrected link, thanks for spotting the mistake @nhcarrigan**

**Comment by nhcarrigan** [comment]
> expected top_IN_occupation appears to be incorrect, I get Private but expected in test is Prof-specialty even though there are none of this profession (in India and salary >50K) in the dataset. Apologies if I'm incorrect here.

On this test, I think the comment in the `demographic_data_analyser.py` file might be incorrect? 
I mistakenly looked for the top occupation in India *overall*, and that returned the expected `Prof-specialty`.

**Comment by moustachio-belvedere** [comment]
> 
> 
> > expected top_IN_occupation appears to be incorrect, I get Private but expected in test is Prof-specialty even though there are none of this profession (in India and salary >50K) in the dataset. Apologies if I'm incorrect here.
> 
> On this test, I think the comment in the `demographic_data_analyser.py` file might be incorrect?
> I mistakenly looked for the top occupation in India _overall_, and that returned the expected `Prof-specialty`.

Interesting, so if you look at India overall for both "<=50K" and ">50K" then top profession is Prof-specialty? That's straightforward to fix then, but I guess we need to decide whether it is the comment that should be amended or the test.

**Comment by gideonjeffrey** [comment]
I have an individual issue with one of the assertAlmostEquals calls, documented below.

One of the project requirements is to produce a Pandas series containing names of races in the dataset and a count of individuals in the dataset for each race. The prompt and my line of code are below:

```
# How many of each race are represented in this dataset? This should be a Pandas series with race names as the index labels.
    race_count = df.groupby('race').size()
```

The test module code creates a list from the resultant series and compares to a list of the expected values:

```
def test_race_count(self):
        actual = self.data['race_count'].tolist()
        expected = [27816, 3124, 1039, 311, 271]
        self.assertAlmostEqual(actual, expected, msg="Expected race count values to be [27816, 3124, 1039, 311, 271]")
```
Here’s the problem: assertAlmostEqual can’t take two lists as arguments!

```
ERROR: test_race_count (test_module.DemographicAnalyzerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/boilerplate-demographic-data-analyzer/test_module.py", line 11, in test_race_count
    self.assertAlmostEqual(actual, expected, msg="Expected race count values to be [27816, 3124, 1039, 311, 271]")
  File "/usr/lib/python3.8/unittest/case.py", line 943, in assertAlmostEqual
    diff = abs(first - second)
TypeError: unsupported operand type(s) for -: 'list' and 'list'
```

So I believe that something like assertCountEqual in this case is required instead.

**Comment by gikf** [comment]
Looks like wrong usage of arguments in `assertAlmostEqual` was fixed in https://github.com/freeCodeCamp/boilerplate-demographic-data-analyzer/pull/2.

Expected values of answers should be rounded to the nearest tenth, per specification in `README.md`. I'm not sure if this was added in the meantime, or if it was like that from the start, but this also seems to be solved.

Regarding `top_IN_occupation`, here are grouped occupations which I'm getting after filtering `native-country` to 'India' and `salary` to `>50K`
```
occupation
Adm-clerical         1
Exec-managerial      8
Other-service        2
Prof-specialty      25
Sales                1
Tech-support         2
Transport-moving     1
```

I'm closing this issue as it looks as completed. If that's a mistake feel free to request re-opening it.
