### ISSUE TITLE
Errors in challenge description

### ISSUE THREAD

**Issue by multiwebinc** [freeCodeCamp/freeCodeCamp#39269]
**Describe your problem and how to reproduce it:**

The challenge says:

> In these kind of requests, the data doesn’t appear in the URL, it is hidden in the request body. This is a part of the HTML request, also called payload. Since HTML is text-based, even if you don’t see the data, it doesn’t mean that it is secret.

It should be “HTTP request”, not “HTML request”.

Also I don’t get the point in the third sentence “Since HTML is text-based, even if you don’t see the data, it doesn’t mean that it is secret”. What does HTML being text-based have to do with not seeing the data from a POST request? The response to an HTTP request doesn’t even necessarily have to be HTML, or even text-based. None of the examples up to this point has the response been HTML, but JSON. And how does HTML being text-based and not being able to see the data being sent in the request relate to the data being “secret” and why is that important?

**Add a Link to the page with the problem:**
[Use body-parser to Parse POST Requests](https://www.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/use-body-parser-to-parse-post-requests)

**Comment by ojeytonwilliams** [comment]
> It should be “HTTP request”, not “HTML request”.

Agreed, thanks for pointing that out.

And, yes, the third sentence is misleading.  The paragraph in question is

> In these kind of requests, the data doesn’t appear in the URL, it is hidden in the request body. This is a part of the HTML request, also called payload. Since HTML is text-based, even if you don’t see the data, it doesn’t mean that it is secret. The raw content of an HTTP POST request is shown below:

I think what the challenge should say is the following:

> In these kind of requests, the data doesn’t appear in the URL, it is hidden in the request body. The body is a part of the HTTP request, also called the payload.  Even though the data is not visible in the URL, this does not mean that it is private.  To see why, look at the raw content of an HTTP POST request:

Basically it's a warning that POSTs may look more secure, but you still need encryption!

**Comment by nakul251197** [comment]
Hello!
This is my first time contributing in the code. I would like to take up this issue if no one is working on it.

Thank You!

**Comment by ojeytonwilliams** [comment]
Welcome @nakul251197! No one else seems to have taken this up yet, so please do.
