### ISSUE TITLE
React: Pass an Array as Props Bug

### ISSUE THREAD

**Issue by Himanshunitrr** [freeCodeCamp/freeCodeCamp#39263]
**Describe your problem and how to reproduce it:**
In the Front End Libraries Certification, there is a sub-unit in React portion named "React: Pass an Array as Props", in which we have to pass an array as props and to render them in p tag by using  .join() method. The question asks us to display the array in the p element as a comma-separated list. The problem is that if we use .join(",") then the test fails but if we use .join(", ") then the test is passed. I think the first (using .join(",")) should also pass the test. 
I will love to work on this issue if someone tells me the file which has the logic which tests the test. I think it needs a small tweaking which I can do !

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/react/pass-an-array-as-props

**Tell us about your browser and operating system:**
* Browser Name: 
* Browser Version: 
* Operating System: 
Google Chrome Dev 
85.0.4183.16 (Official Build) dev (64-bit) (cohort: Dev-nonPGO)
Windows

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![fcc-bug](https://user-images.githubusercontent.com/53482681/87578310-dfa87a80-c6f1-11ea-9eb2-ead9563c1aa2.png)

**Comment by RandellDawson** [comment]
@Himanshunitrr The actual file is [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/03-front-end-libraries/react/pass-an-array-as-props.english.md).  You will want to make sure to read [our documentation on  a working on coding challenges](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges).  Before [creating a PR](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request), you must [run tests](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=testing-challenges) on your changes to validate your changes allow all the tests to pass with our existing working solution.

We recommend [setting up the repo locally](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally) or using Gitpod to make and test your changes before creating a PR.

If you have any questions, check out our [Contributor's channel on Gitter](https://gitter.im/FreeCodeCamp/Contributors).

**Comment by Himanshunitrr** [comment]
Thanks a lot !

**Comment by Himanshunitrr** [comment]
Created a PR #39268
