### ISSUE TITLE
React course, incorrect usage of setState

### ISSUE THREAD

**Issue by manorius** [freeCodeCamp/freeCodeCamp#39267]
Not sure if a bug per se but I believe the code that is used should reflect what is being taught.
In the React lesson “Use State To Toggle An Element” 
https://www.freecodecamp.org/learn/front-end-libraries/react/use-state-to-toggle-an-element
it is advised not to use code like this 
`
this.setState({
  counter: this.state.counter + this.props.increment
});
`
but this code style:
`
this.setState((state, props) => ({
  counter: state.counter + props.increment
}));
`

but in following lessons like the "Change Inline CSS Conditionally Based on Component State"
https://www.freecodecamp.org/learn/front-end-libraries/react/change-inline-css-conditionally-based-on-component-state
the non-recomended code style is used:
`
    this.setState({
      counter: 0 // change code here
    });
`
Sorry for being so pedantic… Just saw this and I wanted to raise it to make sure that my understanding is correct.

**Comment by ojeytonwilliams** [comment]
Hi @manorius thanks for pointing this out.  The rationale for using the updater function is explained in the first challenge:

> This means you can't rely on the previous value of `this.state` or `this.props` when calculating the next value. So, you should not use code like this:
```js
this.setState({
  counter: this.state.counter + this.props.increment
});
```

There's nothing intrinsically wrong with the object form - it's only a problem if it includes references to `this.state` or `this.props`.  However, there are examples of that mistake in subsequent challenges for example [here](https://www.freecodecamp.org/learn/front-end-libraries/react/add-event-listeners) and [here](https://www.freecodecamp.org/learn/front-end-libraries/react/render-with-an-if-else-condition).  I think those should be changed.

**Comment by ruhci28** [comment]
hye can i work on this .?

**Comment by Manish-Giri** [comment]
@Ruchika8 Go ahead.

**Comment by ruhci28** [comment]
hye @Manish-Giri  sorry to ask you but does you by mistake assign this to someone else .?

**Comment by ojeytonwilliams** [comment]
This is not assigned to anyone.  Whoever wants to work on it is free to do so.

**Comment by Manish-Giri** [comment]
@ruhci28 Yes, sorry. Tagged someone else due to Github autocomplete. You can work on this 👍

**Comment by ruhci28** [comment]
Okay Thanks

**Comment by ruhci28** [comment]
Hye, I changed the setState usage in challenges above mention by the @ojeytonwilliams.
![Screenshot 2020-07-19 at 3 44 06 PM](https://user-images.githubusercontent.com/59759735/87872592-7d909380-c9d7-11ea-8f0d-56d63cfdd757.png)
![Screenshot 2020-07-19 at 3 44 27 PM](https://user-images.githubusercontent.com/59759735/87872594-841f0b00-c9d7-11ea-99e1-4a9d3799fdff.png)

**Comment by ojeytonwilliams** [comment]
Hi @ruhci28, if you're happy with the code, please go ahead and create the PR so we can review it there.

**Comment by ruhci28** [comment]
okay

**Comment by RandellDawson** [comment]
If we are going to do this right, then we should fix all such instances at the same time:

* [Add Event Listeners](https://www.freecodecamp.org/learn/front-end-libraries/react/add-event-listeners)
* [Create a Controlled FormPassed](https://www.freecodecamp.org/learn/front-end-libraries/react/create-a-controlled-form)
* [Optimize Re-Renders with shouldComponentUpdate](https://www.freecodecamp.org/learn/front-end-libraries/react/optimize-re-renders-with-shouldcomponentupdate)
* [Render with an If-Else Condition](https://www.freecodecamp.org/learn/front-end-libraries/react/render-with-an-if-else-condition)
* [Connect Redux to React](https://www.freecodecamp.org/learn/front-end-libraries/react-and-redux/connect-redux-to-react)
* [Extract State Logic to Redux](https://www.freecodecamp.org/learn/front-end-libraries/react-and-redux/extract-state-logic-to-redux)
* [Manage State Locally FirstPassed](https://www.freecodecamp.org/learn/front-end-libraries/react-and-redux/manage-state-locally-first)
* [Use Provider to Connect Redux to React](https://www.freecodecamp.org/learn/front-end-libraries/react-and-redux/use-provider-to-connect-redux-to-react)

**Comment by uziau** [comment]
Hi, if we change all of such instances, I'm afraid new learners will have the impression that this form is wrong:

```
this.setState({ counter: 0 })
```

which, as @ojeytonwilliams had pointed out, is not true.

Maybe a better way is to update the information in https://www.freecodecamp.org/learn/front-end-libraries/react/use-state-to-toggle-an-element, so instead of using words like:

```
This means that the above should be rewritten as:
```

We could say that there is an alternative form of setState() which receive previous state as an argument.

Sorry I have problems expressing my thought in english, I hope you got what I mean.

**Comment by RandellDawson** [comment]
@uziau I have only suggested making the change to the functional version of `setState` in the challenges referenced above which were trying to update state with `this.state` or `this.props`.

**Comment by RandellDawson** [comment]
@uziau Would you mind creating a separate issue for the challenge description change you would like to see.  This will make it easier, since it is a different scope of the current issue (which is strictly about changing the challenge seed code).  Once you create the new issue, I can add a `help wanted` label, so others can discuss what the exact wording should be.

Thank you

**Comment by rashmikagamage** [comment]
can i help?

**Comment by RandellDawson** [comment]
@rashmikagamage There is already an open PR that is almost ready to be merged, so it is probably better if you find another issue to work on.  There are plenty to choose from though.
