### ISSUE TITLE
Use Brython in the new python courses

### ISSUE THREAD

**Issue by SaumitraVerma** [freeCodeCamp/freeCodeCamp#39271]
brython can be used as an web based interpreter and can make the python courses like the others.

https://cdnjs.cloudflare.com/ajax/libs/brython/3.4.0/brython.min.js

**Comment by SaumitraVerma** [comment]
It's been over a month and still no response from anyone!!!!!.

**Comment by RandellDawson** [comment]
@beaucarnes Any thoughts?

**Comment by etnnth** [comment]
I have been trying to do something similar with [pyodide](https://github.com/iodide-project/pyodide).
It is somewhat similar to Brython. It also allow the use of the scientific python stack with numpy and stuff.
I managed to hack my way through FreeCodeCamp code and add a way to run python code given in the editor.
If you are interested, I made a pull request #39493.

**Comment by beaucarnes** [comment]
We've looked into Brython but I've never seen pyodide before. We decided to go in a different direction. We've started creating the Python challenges in an in-browser VS Code environment, complete with a terminal. This will allow it to be a more real-world experience for learners.
