### ISSUE TITLE
Local Dev Connection Refused Error

### ISSUE THREAD

**Issue by Sky020** [freeCodeCamp/freeCodeCamp#39278]
**Describe your problem and how to reproduce it:**
Running up fCC locally often leads to this error:
![image](https://user-images.githubusercontent.com/51722130/87810065-4a71c700-c854-11ea-89b6-021ce5403027.png)

Some useful logs:
DB:
```
2020-07-17T17:29:53.837+0100 I NETWORK  [conn1] end connection 127.0.0.1:38498 (1 connection now open)
2020-07-17T17:29:53.837+0100 I NETWORK  [conn2] end connection 127.0.0.1:38500 (0 connections now open)
```
Server:

Potentially related (but I have seen this error, before the one in question)
```
fcc:server freeCodeCamp server listening on port 3000 in development +11s
fcc:server connecting to db at mongodb://localhost:27017/freecodecamp +0ms
Connection fails: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connection timed out
```

For full server logs, visit: https://github.com/Sky020/freeCodeCamp/blob/temp/logs.txt (PS: if someone could recommend a better way to display/host logs, I would be grateful)

**The problem:**
This prevents information from being saved to the DB, and occurs more frequently than not.

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Operating System: Windows 10, WSL2, Ubuntu 20.04

**Additional Info**
This occurs on the latest master branch with no changes.

Ping @ojeytonwilliams

**Comment by ojeytonwilliams** [comment]
Thanks Shaun, I think it's a node compatibility problem.  fCC is only able to run on the current lts version, so if you try switching to that (`nvm install lts/*` makes that trivial) and reinstalling everything should be fine.

**Comment by Sky020** [comment]
Thank you, for pointing that out, Oliver. It appears I need to set `nvm use` each time I open up WSL. However, after switching to the lts, I get the same errors. I have updated the linked logs.

**Comment by ojeytonwilliams** [comment]
It seems that Mongodb is refusing to connect.  I would check that it is starting automatically and see if it is producing any logs.

**Comment by Sky020** [comment]
I have added all of the db logs to the above mentioned logs.

**Comment by Sky020** [comment]
Closing, until further development arises. Likely cause - slow start-up causing lack of concurrency.
