### ISSUE TITLE
Fix typos on React Quiz news post

### ISSUE THREAD

**Issue by kettultim** [freeCodeCamp/freeCodeCamp#39272]
There are a couple of typos in the 3rd paragraph on https://www.freecodecamp.org/news/how-to-build-a-quiz-app-using-react-and-typescript/

*Original*
> Using Typescript can help make sure your variables and props are what you indend since it evaluates your code during compile-time (as opposed to run-time). This becomes especially important as your progarm becomes larger.

*Fix*
> Using Typescript can help make sure your variables and props are what you intend since it evaluates your code during compile-time (as opposed to run-time). This becomes especially important as your program becomes larger.

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks for catching this @kettultim. :+1: :+1: I went in and fixed both of those typos.

The updated article text is here: https://www.freecodecamp.org/news/how-to-build-a-quiz-app-using-react-and-typescript/
