### ISSUE TITLE
chore: add ES6 import syntax throughout curriculum

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/freeCodeCamp#39277]
- [ ] Add ES6 import syntax

Following from a conversation on Gitter, after getting this error:
```
import timezones from '../../../config/timezones.json';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```
Either Babel should be enabled throughout, or something like _esm_ used.

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
