### ISSUE TITLE
Possible bug with Scientific Computing with Python Projects - Budget App

### ISSUE THREAD

**Issue by dcsohn913** [freeCodeCamp/freeCodeCamp#39288]
**Describe your problem and how to reproduce it:**
If you go into test_module.py for the budget app challenge and scroll all the way down to the function test_create_spend_chart. The expected result is false. It says the expected results for the percentage withdrawal should be business - 0%, food - 70%, and entertainment - 20%.
Business should be at 10%.
Given:
        self.food.deposit(900, "deposit")
        self.entertainment.deposit(900, "deposit")
        self.business.deposit(900, "deposit")
        self.food.withdraw(105.55)
        self.entertainment.withdraw(33.40)
        self.business.withdraw(10.99)
total withdrawal is 105.55 + 33.4 + 10.99 = 149.94
food = 105.55/149.94 = 70% 
entertainment = 33.40/149.94 = 22% -> 20%
business = 10.99/149.94 = 7% -> 10%

rounding to nearest 10

I don't know if I keep failing because of this mathematical error or because of some other minor problem in my code. Visually, it seems like my code is printing the bar graph correctly but I keep getting an error somehow.

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/87856321-45079180-c8d3-11ea-8734-b57024a18da7.png)

From the challenge instructions,  the height of each bar should be *rounded down* to the nearest 10. 🙂 

This does not appear to be a bug in the tests or the boilerplate code. As such, I am going to go ahead and close this issue. If you feel that this is in error, feel free to reopen the issue with an explanation of the bug you think is occurring. For help with code that you have written, you can visit the [forums](https://forum.freecodecamp.org). Happy Coding!

**Comment by pedromperezc** [comment]
Hi guys.

I have the same problem with the test. 

I think the sum of the three percentages has to be 100 %. If you look at the expected result, it is 90 %:
![image](https://user-images.githubusercontent.com/9473332/88551059-c7d9cc00-cff8-11ea-971b-3a33d585e804.png)

Rounding to nearest 10 7% is 10 %

**Comment by nhcarrigan** [comment]
Hello~! As I mentioned above, the challenge expects you to round *down* to the nearest 10. So 7% would become 0% 🙂

**Comment by pedromperezc** [comment]
Ahh, That's right I didn't see the word "down". 

Thank you !
