### ISSUE TITLE
Typo in scientific computing with python certificate

### ISSUE THREAD

**Issue by hailelagi** [freeCodeCamp/freeCodeCamp#39284]
**Describe your problem and how to reproduce it:**
There is a typo in the scientific computing with python certificate which displays "400" hours instead of "300" as the conservative estimated time of completion.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/certification/obsessedyouth/scientific-computing-with-python-v7

**Tell us about your browser and operating system:**
* Browser Name: 
Google Chrome
* Browser Version: 
Version 84.0.4147.89 (Official Build) (64-bit
* Operating System: 
Windows 10 Enterprise

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Screenshot (364)](https://user-images.githubusercontent.com/52631736/87842264-09ed6a00-c8a3-11ea-9314-bb2299f547ca.png)

**Comment by nhcarrigan** [comment]
This bug is also present on the Machine Learning and Data Analysis certificates.

![image](https://user-images.githubusercontent.com/63889819/87842459-7e9fb480-c861-11ea-9282-fae079610bb8.png)
![image](https://user-images.githubusercontent.com/63889819/87842466-89f2e000-c861-11ea-95b6-6be097da5ba6.png)

**Comment by Himanshunitrr** [comment]
I went to https://github.com/freeCodeCamp/freeCodeCamp/tree/master/curriculum/challenges/english/12-certificates/ and saw some .md files. There were no certificate templates where one can fix the typos. (They might be in some other location) If so then tell me the right location please !

**Comment by raisedadead** [comment]
The correct estimates of the completion is defined in our API (used on the certificate):

https://github.com/freeCodeCamp/freeCodeCamp/blob/76879f9e7e77dc3bd263c55246c07c965bfded4e/api-server/server/boot/certificate.js#L182-L198

The map is just using a hard coded version of the same:

https://github.com/freeCodeCamp/freeCodeCamp/blob/76879f9e7e77dc3bd263c55246c07c965bfded4e/client/src/components/Map/components/SuperBlock.js#L51-L55

This could possibly go into the common config and used from there instead.

**Comment by Himanshunitrr** [comment]
Let me fix this

**Comment by Himanshunitrr** [comment]
Everyone is doing the same mistake. Sir @raisedadead can you please elaborate on what is wrong and how it can be fixed.

**Comment by Ieahleen** [comment]
@Himanshunitrr : the values here are correct:
https://github.com/freeCodeCamp/freeCodeCamp/blob/76879f9e7e77dc3bd263c55246c07c965bfded4e/api-server/server/boot/certificate.js#L182-L198

what seems to be needed is to use those values here, instead of the hardcoded 300
https://github.com/freeCodeCamp/freeCodeCamp/blob/76879f9e7e77dc3bd263c55246c07c965bfded4e/client/src/components/Map/components/SuperBlock.js#L51-L55

**Comment by Himanshunitrr** [comment]
Thanks @Ieahleen 
I went from one file to another to fix it, but couldn't though I enjoyed my effort !!

**Comment by raisedadead** [comment]
@Himanshunitrr 

This is a bit more involving (while the fix is easy) because you would need some familiraity with the codebase. (Magic numbers seem to be a consitent mistake in our design choices 😓)

1. We want to put all the values in a [config file](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/config) common to the client and API. (See the donation config, etc. for example)
2. We want to use these common config values at their required places. 
3. We want some tests (another consistenly lacking feature) to go with this to avoid future issues.

**Comment by raisedadead** [comment]
@ahmadabdolsaheb in interest of time, I have assigned this to you instead.

**Comment by Himanshunitrr** [comment]
@raisedadead Will love to get familiarise with the code with some help !!

**Comment by Himanshunitrr** [comment]
Any tips regarding how should I start  ??

**Comment by ahmadabdolsaheb** [comment]
We have a [config](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/config) directory. We could introduce an exportable object with keys for certifications and values for hours.
Then, we need to replace all instances of certificate hours used in our codebase (e.x landing page, /learn, the api certificates.js) the config values so we have one source of truth.

**Comment by HiThereImCam** [comment]
@raisedadead  Can I hop on this bug? I have the time to familiarize myself with the codebase so that we can fix this issue.

**Comment by HiThereImCam** [comment]
@ahmadabdolsaheb 

I'm working on this problem. I'm not sure if your on Gitter but I have two questions that I hope will point me in the right direction

1.) I'm trying to duplicate the problem and the only way to do that is by receiving a course certificate. Is there a way to by pass the challenges and receive the certificate?
2.) Are you familiar with SuperBlock.js? Before I make changes, I'm trying to understand how and where it's being used. Without comments in the file, it's usage is pretty vague to me.

**Comment by moT01** [comment]
To quickly gain a certificate - you can log in locally, go to your account settings page and scroll down to the projects/certifications. Open all the projects for the cert you want in new tabs, most of them don't have tests so you can submit any URL.

Second option would be to open up your mongo database locally and change these values for a local user:
```bash
	"isFrontEndCert" : false,
	"isDataVisCert" : false,
	"isBackEndCert" : false,
	"isFullStackCert" : false,
	"isRespWebDesignCert" : false,
	"is2018DataVisCert" : false,
	"isFrontEndLibsCert" : false,
	"isJsAlgoDataStructCert" : false,
	"isApisMicroservicesCert" : false,
	"isInfosecQaCert" : false,
	"isQaCert" : false,
	"isInfosecCert" : false,
	"is2018FullStackCert" : false,
	"isSciCompPyCert" : false,
	"isDataAnalysisPyCert" : false,
	"isMachineLearningPyCert" : false
```
I think that would work.
 
It looks like the superblock.js file is what renders the map on [https://www.freecodecamp.org/learn](/learn). Where it shows...
![Screen Shot 2020-08-20 at 9 55 08 PM](https://user-images.githubusercontent.com/20648924/90847330-dd0ff500-e32f-11ea-8295-1f5b0685a7d3.png)

So it looks like the values would need to be changed there, as well as possibly [on the certificates](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/client-only-routes/ShowCertification.js#L270)

It actually looks like the certificates are displaying the intended hours.

**Comment by HiThereImCam** [comment]
Hi @moT01 

Thank you for the reply! Thank you so much for pointing me in the right direction. As pointed earlier in the thread, they want a 
> 
>     1. We want to put all the values in a [config file](https://github.com/freeCodeCamp/freeCodeCamp/tree/master/config) common to the client and API. (See the donation config, etc. for example)
> 
>     2. We want to use these common config values at their required places.
> 
>     3. We want some tests (another consistenly lacking feature) to go with this to avoid future issues.

I looked at the config file and noticed that a completion hours file and tests were not created so I was planning on taking of that.

Thanks Tom!

**Comment by ahmadabdolsaheb** [comment]
A quick update:
Based on our latest talked with Quincy, all of the certificates( except the full stack) should be 300 hours.
@HiThereImCam, in the Interest of time I am planning to tackle this issue in the next two days, but you are welcome to submit a pr before then.
