### ISSUE TITLE
Why does it keep saying red when it wants blue???

### ISSUE THREAD

**Issue by FineBlend** [FreeCodeCamp/FreeCodeCamp#3928]
Challenge [Waypoint: Use a CSS Class to Style an Element](http://freecodecamp.com/challenges/waypoint-use-a-css-class-to-style-an-element#?solution=%3Cstyle%3E%0A%20%20h2%20%7B%0A%20%20%20%20color%3A%20blue%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<style>
  h2 {
    color: blue;
  }
</style>

<h2>CatPhotoApp</h2>

<p>Kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff.</p>

```

**Comment by dexrualo** [comment]
If I read it correctly, I think it wants us to add a new 'red-text' class within the  <style> tag and apply that class to the the h2 element.

**Comment by dexrualo** [comment]
*within the '<style>' tag

**Comment by dexrualo** [comment]
Please ignore that last comment. That was a mess. lol. I meant within the style tag.

**Comment by ltegman** [comment]
I'm not quite sure I understand the issue. It looks like the lesson is using blue as an example and then asking you to do something similar in the editor but with red instead.

**Comment by FineBlend** [comment]
Because on the instructions, the word blue never actually appears. I figured it out, and I'm not new to HTML or CSS, it's just worded wrong. 

Thanks all

**Comment by ltegman** [comment]
Sounds like this has been resolved. Closing but let us know if you think this needs further attention.

Thanks and happy coding!
