### ISSUE TITLE
Data Analysis with Python Projects - Sea Level Predictor -- suggestion of removal of one test

### ISSUE THREAD

**Issue by moustachio-belvedere** [freeCodeCamp/freeCodeCamp#39280]
**Describe your problem and how to reproduce it:**
There is a test that checks the plot's x-ticks are exactly as expected, see line 25 of the test python file in the link below. This was not the x-ticks I got by default, so I had manually set the ticks to what the test required (a very minor change). This changing of x-ticks is not specified in the readme or comments yet setting the title, x-label and y-label are described. It seems that perhaps either the challenge needs to mention to set the x-ticks explicitly or the test should be removed.

My version for reference (original version also linked further down):
https://repl.it/@moustachiobelve/fcc-sea-level-predictor

**Add a Link to the page with the problem:**
https://repl.it/@freeCodeCamp/fcc-sea-level-predictor

**Comment by erictleung** [comment]
Good catch. To be consistent, I think it might be nice to have the axis tick marks to be standardized. But then it might be good to just explicitly tell students what the ticks should be.

So I might suggest that we just add in the README that the x ticks should be 

```
[1850.0, 1875.0, 1900.0, 1925.0, 1950.0, 1975.0, 2000.0, 2025.0, 2050.0, 2075.0]
```

**Comment by moustachio-belvedere** [comment]
Sounds good. We could also add a comment in the template `sea_level_predictor.py` on line 18, next to the comment reminding people to add title and axis labels.

**Comment by raisedadead** [comment]
Hi, 

We are closing old issues/pull-requests that we think are stale. If you need still need help with this or are fixing this, please open a fresh issue/pull-request.

Thanks for your understanding. 

Happy contributing.
