### ISSUE TITLE
Chore: audit dependencies

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#39297]
We should make sure the `devDependencies` have all the dev tooling and none of the production tooling.  For instance, `copy-webpack-plugin` is in `devDependencies`, but is used in production.  Once we've done this, we can cut them out of the pipelines.

Also, some Babel packages are only included as dependencies of Gatsby, not directly in `package.json`, since Gatsby is just a site generator, I think it makes sense to explicitly include everything we use.  Thoughts?

**Comment by ruhci28** [comment]
Hii @ojeytonwilliams I want to work on this

**Comment by ojeytonwilliams** [comment]
Hey @ruhci28 I'd like to speak to @raisedadead about this before we make any large changes (he understands the pipelines far better than I do).  So, while you're very welcome to work on this, you might want to wait until I've got the OK from him.  That way you can be sure these changes are needed.

**Comment by ruhci28** [comment]
yeah sure
