### ISSUE TITLE
Python courses are all youtube videos?

### ISSUE THREAD

**Issue by gimseng** [freeCodeCamp/freeCodeCamp#39293]
**Is your feature request related to a problem? Please describe.**
Almost all Python learning courses (except for the projects) are youtube-videos plus multiple-choice-questions (MCQ).
The Python course, for e.g.,  asked me what's the output of 'x=5;x=x+1;print(x)', while they could have asked the learners to code this.

This feels more like the datacamp model rather than the dataquest model. I like the latter because I learn web dev from FCC's learning path and really learnt a lot. I don't like reading blog and watching youtube to learn but like FCC web dev model to learn by coding.

**Describe the solution you'd like**
I'd like the Python courses to be redesigned or supplemented with actual coding exercises. For e.g. in html/css courses, I learnt a new tag/idea, and right away I got to code it in a codepen type environment. 
I think the quality of the Python courses will be better if we implement codepen type exercise. It seems like dataquest/datacamp could do that, so I think the technology is there.
**Describe alternatives you've considered**
We could have videos + coding exercise combinations for each exercise (instead of videos+MCQs), rather than just coding projects at the end (which are important and good to have).

**Additional context**

**Comment by Sky020** [comment]
Hello there,

I recommend you read this article on the new version of the curriculum: https://www.freecodecamp.org/news/python-curriculum-is-live/

In short, the video lessons with multiple choice questions are more of a supplement/placeholder whilst the project-based section is being worked on.

If you have any more questions, the [forum](https://forum.freecodecamp.org) is a useful place to start.

Therefore, I am closing this issue. Thank you.

**Comment by gimseng** [comment]
@Sky020 great, thanks ! That answered my questions and confusions. Is there anyway I can help or contribute to the Python upcoming interactive courses?

**Comment by Sky020** [comment]
Glad to hear.
>Is there anyway I can help or contribute to the Python upcoming interactive courses?

Excellent. This forum post outlines the best ways to contribute to the upcoming curriculum. There are links floating aroung to Python projects which still need QAing/creating.

**Comment by beaucarnes** [comment]
@gimseng All the new Python instructional content will be in the form of building projects step-by-step. We've already developed the projects and the best thing you can do to help is to QA the projects that have been developed. You can find the projects to review here (look for the ones with 'python' in their title): https://github.com/freeCodeCamp/CurriculumExpansion

What we are working on now is taking those projects and breaking them down into individual steps and instructions. At this time, that part is being done in-house by freeCodeCamp staff members.

**Comment by gimseng** [comment]
@beaucarnes great ! I was lost in the forum trying to figure out where the new exercises were. I will be sure to create issue tickets if I found bugs or any issues. Many thanks !
