### ISSUE TITLE
error:unable to create file while cloning

### ISSUE THREAD

**Issue by Vinay0001** [freeCodeCamp/freeCodeCamp#39309]
when i was cloning the repo locally there was an error: 
C:\Users\Vinay\Desktop\CS projects\OpenSource>git clone https://github.com/Vinay0001/freeCodeCamp.git
Cloning into 'freeCodeCamp'...
remote: Enumerating objects: 253141, done.
remote: Total 253141 (delta 0), reused 0 (delta 0), pack-reused 253141R                                53141), 125.16 MiB | 3
Receiving objects: 100% (253141/253141), 125.18 MiB | 3.39 MiB/s, done.
Resolving deltas: 100% (137932/137932), done.
error: unable to create file curriculum/challenges/portuguese/02-javascript-algorithms-and-data-structures/object-oriented-programming/use-closure-to-protect-properties-within-an-object-from-being-modified-externally.portuguese.md: Filename too long
error: unable to create file curriculum/challenges/portuguese/06-information-security-and-quality-assurance/information-security-with-helmetjs/mitigate-the-risk-of-cross-site-scripting-xss-attacks-with-helmet.xssfilter.portuguese.md: Filename too long
error: unable to create file curriculum/challenges/portuguese/06-information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-on-an-api-response-using-chai-http-iii---put-method.portuguese.md: Filename too long
error: unable to create file curriculum/challenges/portuguese/06-information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-on-an-api-response-using-chai-http-iv---put-method.portuguese.md: Filename too long
Updating files: 100% (9768/9768), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
![file-name-too-long](https://user-images.githubusercontent.com/32284606/88363591-3111d300-cd9e-11ea-8b5f-9446ed6d15d3.png)

**Comment by RandellDawson** [comment]
What version of Windows are you using?

**Comment by Vinay0001** [comment]
it's windows 10 home edition. 
and thanks! that worked.

**Comment by RandellDawson** [comment]
Glad I could help.
