### ISSUE TITLE
Constructor call not checked in React lesson to create component from scratch

### ISSUE THREAD

**Issue by JRodDynamite** [freeCodeCamp/freeCodeCamp#39301]
**Describe your problem and how to reproduce it:**
In one of the React lessons, _[write a react component from scratch](https://www.freecodecamp.org/learn/front-end-libraries/react/write-a-react-component-from-scratch)_, one of the tasks mentioned is to "Make sure to call the constructor for your component, too." This is not checked in the solution.

The solution that I submitted was:
```
// change code below this line
class MyComponent extends React.Component {
  render() {
    return (
      <div>
        <h1>My First React Component!</h1>
      </div>
    )
  }
}

ReactDOM.render(<MyComponent />, document.getElementById('challenge-node'))
```

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version:  84.0.4147.89 (64 bit)
* Operating System: Windows 10

**Comment by christinealuo** [comment]
Hello! I'm trying to get into open source and was wondering if this issue was taken or not and if it would be suitable for first timers 😊

**Comment by Sky020** [comment]
@JRodDynamite , Thank you, for taking the time to bring this up.

I can confirm that this is an issue, and the likely fix is adding one more test along the lines of:
> `myComponent` should have a constructor calling `super` with `props`

`assert(someRegex.test(code));`

@christinealuo , No one has eluded to be working on this issue. And you are welcome to submit a PR. No assignment is necessary as described in our [contribution docs](https://contribute.freecodecamp.org/#/index?id=where-do-i-start-if-i-want-to-work-on-an-issue). The first comprehensive PR will be considered for review.

**Comment by christinealuo** [comment]
@Sky020 Got it, thanks 🤗 I will work on getting a PR submitted soon!
