### ISSUE TITLE
Text under the icon in block completion donation modal should be centered.

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#39300]
![image](https://user-images.githubusercontent.com/4591597/88279856-6ad6d100-cced-11ea-9032-83ee4a734482.png)

To replicate locally, submit any url to the data visualization projects. The modal should pop up after the last submission.

**Comment by shraddhavp** [comment]
want to work on the issue

**Comment by shraddhavp** [comment]
@ahmadabdolsaheb

**Comment by ojeytonwilliams** [comment]
@shraddhavp please do - this issue is perfect for new contributors.

**Comment by ahmadabdolsaheb** [comment]
@shraddhavp,  please go ahead 👍. No assignment is necessary as described in our [contribution docs](https://contribute.freecodecamp.org/#/index?id=where-do-i-start-if-i-want-to-work-on-an-issue). The first comprehensive PR will be considered for review.

**Comment by shraddhavp** [comment]
ok @ahmadabdolsaheb

**Comment by Vinay0001** [comment]
how to find the file where we have to center the text?

**Comment by RandellDawson** [comment]
I could be wrong, but I believe the following lines can make use of the applicable offsets feature in Bootstrap.  

https://github.com/freeCodeCamp/freeCodeCamp/blob/86f908744407da8c9190567001626fcd84cd4fbf/client/src/components/Donation/DonationModal.js#L114

https://github.com/freeCodeCamp/freeCodeCamp/blob/86f908744407da8c9190567001626fcd84cd4fbf/client/src/components/Donation/DonationModal.js#L131

You would offset by half of the number of each type:
```jsx
<Col sm={10} smOffset={5} xs={12} xsOffset={6}>
```

**Comment by ahmadabdolsaheb** [comment]
@Vinay0001, you could search for "Nicely done" and it should come up. the DonationModal.js should come up.
