### ISSUE TITLE
 Responsive Web Design - Product Landing Page - Layout test 1 passes inconsistently 

### ISSUE THREAD

**Issue by DavidMatthewFraser** [freeCodeCamp/freeCodeCamp#39315]
Responsive Web Design - Product Landing Page - Layout test 1

_1. The navbar should always be at the top of the viewport'_ - can be passed AND not passed for the same code depending on the window size when the tests are run:

![Navbar-Issue](https://user-images.githubusercontent.com/47202564/88416903-41c24900-cd9e-11ea-97e2-3b43e814f56a.gif)

My Code: https://codepen.io/David_Mat_Fraser/pen/rNxPPMx

To Recreate:
- Run The Product Landing Page tests with a window height of at-least 800px : You should get 16/16 Tests Passed
- Run The Product Landing Page tests with a window height less than 800px : You should get 15/16 Tests Passed

(I use a media query to change the size of the #video element at window height less than 800px)

- Perhaps the test in question could also check if the #navbar position is fixed 
rather than JUST if it appears at the top of the viewport in order to have consistent results
with the test.

* Browser Name: Google Chrome
* Browser Version: Chrome 83
* Operating System: MacOS 10.15.4

Thanks!

**Comment by RandellDawson** [comment]
Please try using [our forum](https://www.freecodecamp.org/forum) first for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.
