### ISSUE TITLE
Logging in with Safari does not work

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#39316]
Trying to log in with Safari throws me into some sort of redirect loop. Notice the address bar in the gif below.

![Jul-24-2020 14-06-06](https://user-images.githubusercontent.com/20648924/88426495-e8b2df00-cdb6-11ea-9770-2adec953e055.gif)

Here's a screenshot of the text at the end of the gif...

<img width="562" alt="Screen Shot 2020-07-24 at 2 06 31 PM 1" src="https://user-images.githubusercontent.com/20648924/88426492-e6508500-cdb6-11ea-9508-661f90a51efa.png">

Can anyone else reproduce this?

**Comment by JoshuaPelealu** [comment]
Have you tried restarting your browser and clearing the cache?

**Comment by moT01** [comment]
Thanks for the tip @JoshuaPelealu - I had cookies blocked that was causing it.

**Comment by RandellDawson** [comment]
Maybe this should be documented on https://www.freecodecamp.org/news/support/?
