### ISSUE TITLE
Suggestion of an exercise for Javascript Constructors section

### ISSUE THREAD

**Issue by santimirandarp** [freeCodeCamp/freeCodeCamp#39319]
I'm just proposing an exercise

Constructors area is important in javascript and there are no exercises integrating the knowledge. 

Write a simplified version of the `.join` and `push` methods (of course the constructor does not create an array, idk how to achieve that, probably with a factory function instead). I've attempted a simple one:

```javascript
function Errey(...values){
    this.name=values
    }
Errey.prototype={
  constructor:Errey,
    //join method
  myJoin(union = ' '){
  let result=""
  const length = this.name.length
  for(let i=0; i<length; i++)
  { 
   i<length-1 ? result += this.name[i] + union: result+=this.name[i]
  }
  return result
  },
    //push method
    myPush(value){
    this.name = [...this.name, value]
    return this.name.length
    }
  }

let myArray = new Errey("3","blue","1","brown")
myArray.myJoin()
//result "3 blue one brown"
myArray.myPush("hey")
const a = myArray.myPush("hey")
//result [3, "blue",1, "brown", "hey"]
//a=5
```

**Comment by moT01** [comment]
As far as I know, there will not be any new challenges added to the current curriculum with the exception of the coding interview prep section. This is in favor of the [project based curriculum](https://forum.freecodecamp.org/t/help-us-build-version-7-0-of-the-freecodecamp-curriculum/263546) in the works.

**Comment by Aceeper2** [comment]
Got it!

**Comment by moT01** [comment]
Thanks for the input everyone. I think it's safe to close this for the reason mentioned. If anyone thinks I am wrong in closing it, feel free to leave a comment and we can revisit it. Thanks and happy coding 🎉
