### ISSUE TITLE
link insertion 

### ISSUE THREAD

**Issue by xAdvitya** [freeCodeCamp/freeCodeCamp#39321]
when we are doing assignments that need glitch or github assignment its tiring to paste link again and again 

it woud be good it same link remains pasted after we open next challenge , user still will be able to replace it with new glitch or github link if he/she wants 

![Screenshot (373)](https://user-images.githubusercontent.com/54709416/88511443-6f0f3100-d002-11ea-8464-2a296e4f947b.png)

**Comment by ahmadabdolsaheb** [comment]
so you mean the link of a previous project should show up as default for the current one?

**Comment by Advitya-sharma** [comment]
> 
> 
> so you mean the link of a previous project should show up as default for the current one?

yes of the previous challenge

**Comment by RandellDawson** [comment]
If each section used the same boilerplate throughout, the first lesson's solution link field would be empty with only the normal placeholder test , then local storage could be used to track/populate each proceeding lesson with the url used for the previous lesson  However, since some sub sections have multiple boilerplates, it might be confusing for users to auto-populate a previously used url for a lesson where they would need to enter a new url.  Ideally, when a new boilerplate is used, the lesson 's solution link would be empty again with only the normal placeholder text.

**Comment by Advitya-sharma** [comment]
> 
> 
> If each section used the same boilerplate throughout, the first lesson's solution link field would be empty with only the normal placeholder test , then local storage could be used to track/populate each proceeding lesson with the url used for the previous lesson However, since some sub sections have multiple boilerplates, it might be confusing for users to auto-populate a previously used url for a lesson where they would need to enter a new url. Ideally, when a new boilerplate is used, the lesson 's solution link would be empty again with only the normal placeholder text.

but it would be great where it same link can be used eg:- glitch link

**Comment by JoshuaPelealu** [comment]
What we might be able to do is just set a local storage that will contain something like this:
```json
{
  "challenge-name/link": {
     saved-link: "https://link-to-the-project.com"
  }
  "challenge-name/link": {
     saved-link: "https://link-to-the-project.com"
  } 
}
```

And then make the `I've Completed This Challenge` button trigger a function that will take the link, parse it into the json, and store it into the local storage. 

Then have a function check if there is an input or if there is already a way to check if the challenge requires a link, and take the url the user is currently in, and then take the JSON and search for the specific challenge-name/link and then fill in the input with the saved url.

Just a suggestion 🙂

**Comment by moT01** [comment]
Thank you for reporting this issue.

This is a standard message notifying you that the issue has become stale, so we are going to close it.

If you think we're wrong in closing this issue, please request for it to be reopened. Thank you and happy coding.
