### ISSUE TITLE
False Positive: Confirm The Ending Challenge

### ISSUE THREAD

**Issue by dyneskye** [freeCodeCamp/freeCodeCamp#39320]
**Describe your problem and how to reproduce it:**

During a challenge, testing various methods of completing them, I’ve noticed one of the coding questions seems to be a little too easy to pass and I believe it could be fixed with a simple additional test.

consider this code

```
function confirmEnding(str, target) {

  for (let i = target.length, j = 0; i > 0; i--, j++) {
    if (str[str.length-i] == target[j]) {
      return true;
    } else {
      return false;
    }
  }
}

// an actual test

confirmEnding("Open sesame", "same");
```
This code will pass all the tests provided, even though, when the target is changed to for example “sage” it returns

```
true
true
false
true
```
I think a test should be added with some incorrect middle letters such as

`confirmEnding("Open sesame", "sage");`

testing if each individual letter is correct.

Let me know what you think or if I’m being silly!

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-algorithm-scripting/confirm-the-ending

**Tell us about your browser and operating system:**
* Browser Name:  Google Chrome
* Browser Version: Version 84.0.4147.89 (Official Build) (64-bit)
* Operating System: Windows 10 Pro

**Comment by RandellDawson** [comment]
@dyneskye I concur you have found an edge case missed by the current tests.  Go ahead and create a PR.

**Comment by dyneskye** [comment]
Will do. This is exciting!

**Comment by dyneskye** [comment]
> @dyneskye I concur you have found an edge case missed by the current tests. Go ahead and create a PR.

Will do. This is exciting!
