### ISSUE TITLE
Data Analysis with Python Projects - Medical Data Visualizer with matplotlib 3.3.0

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#39332]
**Describe your problem and how to reproduce it:**
Making Medical Data Visualizer run with matplotlib updated to version 3.3.0 results in `test_heat_map_values` test fail due to differences in the ax data, comparing with 3.2.2 version of matplotlib.

```
======================================================================
FAIL: test_heat_map_values (test_module.HeatMapTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/fcc-medical-data-visualizer-1/test_module.py", line 47, in test_heat_map_values
    self.assertEqual(actual, expected, "Expected differnt values in heat map.")
AssertionError: Lists differ: ['0.0[607 chars] '0.2', '0.1', '0.1', '-0.0', '0.0', '-0.0', '0.1'] != ['0.0[607 chars] '0.2', '0.1', '0.1', '-0.0', '0.0', '-0.0', '0.1', '', '', '']

Second list contains 3 additional elements.
First extra element 91:
''

Diff is 989 characters long. Set self.maxDiff to None to see it. : Expected differnt values in heat map.

----------------------------------------------------------------------
```

Outputs from the test, wraps added by me to make it easier to compare. Difference is the three empty entries in 3.2.2 version that are not present in 3.3.0
> version 3.3.0
```
['0.0', '0.0', '-0.0', '0.0', '-0.1', '0.5', '0.0', '0.1', '0.1', '0.3', '0.0', '0.0',
'0.0', '0.0', '0.0', '0.0', '0.2', '0.1', '0.0', '0.2', '0.1', '0.0', '0.1', '-0.0',
'-0.1', '0.1', '0.0', '0.2', '0.0', '0.1', '-0.0', '-0.0', '0.1', '0.0', '0.1', '0.4',
'-0.0', '-0.0', '0.3', '0.2', '0.1', '-0.0', '0.0', '0.0', '-0.0', '-0.0', '-0.0', '0.2',
'0.1', '0.1', '0.0', '0.0', '0.0', '0.0', '0.3', '0.0', '-0.0', '0.0', '-0.0', '-0.0',
'-0.0', '0.0', '0.0', '-0.0', '0.0', '0.0', '0.0', '0.2', '0.0', '-0.0', '0.2', '0.1',
'0.3', '0.2', '0.1', '-0.0', '-0.0', '-0.0', '-0.0', '0.1', '-0.1', '-0.1', '0.7', '0.0',
'0.2', '0.1', '0.1', '-0.0', '0.0', '-0.0', '0.1']
```
>version 3.2.2
```
['0.0', '0.0', '-0.0', '0.0', '-0.1', '0.5', '0.0', '0.1', '0.1', '0.3', '0.0', '0.0',
'0.0', '0.0', '0.0', '0.0', '0.2', '0.1', '0.0', '0.2', '0.1', '0.0', '0.1', '-0.0',
'-0.1', '0.1', '0.0', '0.2', '0.0', '0.1', '-0.0', '-0.0', '0.1', '0.0', '0.1', '0.4',
'-0.0', '-0.0', '0.3', '0.2', '0.1', '-0.0', '0.0', '0.0', '-0.0', '-0.0', '-0.0', '0.2',
'0.1', '0.1', '0.0', '0.0', '0.0', '0.0', '0.3', '0.0', '-0.0', '0.0', '-0.0', '-0.0',
'-0.0', '0.0', '0.0', '-0.0', '0.0', '0.0', '0.0', '0.2', '0.0', '-0.0', '0.2', '0.1',
'0.3', '0.2', '0.1', '-0.0', '-0.0', '-0.0', '-0.0', '0.1', '-0.1', '-0.1', '0.7', '0.0',
'0.2', '0.1', '0.1', '-0.0', '0.0', '-0.0', '0.1', '', '', '']
```
There's no visible difference in the actual plots files between the two. 

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-projects/medical-data-visualizer
https://repl.it/@freeCodeCamp/fcc-medical-data-visualizer#test_module.py

**Comment by fuzzyray** [comment]
I hit this same error, but with a different version of matplotlib. 

I cloned the boilerplate project from github to my local machine, ran `poetry install` and implemented the project.

Running the tests showed the exact same error. The version of matplotlib installed by poetry was 3.1.2 and the seaborn version was 0.9.0

I then created a different virtual environment using pipenv with `pipenv install pandas seaborn`, entered that virtual environment and the tests passed. The matplotlib version installed by pipenv was 3.3.4 and the seaborn version was 0.11.1

Finally, I cloned the project to repl.it, ran the tests and it succeeded there as well. The versions installed there were also matplotlib-3.3.4 and seaborn-0.11.1.

It looks to me that as of right now, it works on repl.it, so not sure if this is something worth looking into further.

**Comment by gikf** [comment]
Hm, seems this was changed in the boilerplate to follow expected value from newer version https://github.com/freeCodeCamp/boilerplate-medical-data-visualizer/pull/5, hence the error appearing on older matplotlib.

No need to keep this open then.
