### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by LeQuadratico** [freeCodeCamp/freeCodeCamp#39333]
**Describe your problem and how to reproduce it:**
There is a dead link on https://www.freecodecamp.org/news/best-git-tutorial/, it is the link to the article about Git Hosting.
(https://guide.freecodecamp.org/git/git-hosting)

**Recommended fix, suggestions (how would you update it?):**
Remove the link.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Anmerkung 2020-07-28 130931](https://user-images.githubusercontent.com/45048954/88658405-abf72880-d0d3-11ea-87bb-6e4d2cdf9e5a.jpg)

**Comment by namnguyen21** [comment]
I'd like to fix this by removing the 'For more on this ...' sentence.

**Comment by raisedadead** [comment]
Hi @namnguyen21 thanks for your interest in fixing this, however at the minute only the editioral team has access to the publication. I have assigned this to one of our editors instead.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this @LeQuadratico. I happened to see this while browsing through open issues and decided to update the link. Now it points to https://www.freecodecamp.org/news/the-beginners-guide-to-git-github/.

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo  Since the link was originally pointing to a Guide article about GitHub hosting, wouldn't one of the following be a better fit?
https://www.freecodecamp.org/news/hosting-custom-domain-on-github-pages-8c598248d2bc/

https://www.freecodecamp.org/news/create-a-free-static-site-with-github-pages-in-10-minutes/
Tue 5:48pm
I think the first one is better than the second article since it does not introduce Jekyll.

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, the title for that old Guide article was a bit of a misnomer. While it seems like it'll talk about hosting a static site, it's actually about hosting a Git repository.

Unfortunately there's not a great news article that goes into all the different options, at least as far as I could tell.

**Comment by RandellDawson** [comment]
@scissorsneedfoodtoo Then I guess the link should just be removed?

**Comment by scissorsneedfoodtoo** [comment]
@RandellDawson, I think it's fine to leave it. The original guide article was pretty light on information, but the new link covers some of the stuff that was in there, like mentioning self-hosting and online options.
