### ISSUE TITLE
Google account creation, cannot change Email after creating a Google account

### ISSUE THREAD

**Issue by realAlpe** [freeCodeCamp/freeCodeCamp#39340]
**Is your feature request related to a problem? Please describe.**
When I created an account on https://www.freecodecamp.org/, I had the option to choose between four options: Google, GitHub, Facebook, and Email. I chose Google and now I am frustrated to see that I am not able to change to an account with an Email.

**Describe the solution you'd like**
Since I signed up with my google account I would love an option to be able to transfer my account on FCC to an Email address. This option could be implemented in the settings section.

**Describe alternatives you've considered**
If a transfer is not possible, then I would appreciate the option to change my Google account.

**Additional context**
My Email under the "Email Settings" has still not been verified despite verifying it multiple times with the link they sent to the Email. I believe this is due to me having a Google account. The same applies to "New Email" and "Confirm New Email", where I can not change my Email presumably due to it being a Google account.
[Image of not being able to change my Email](https://i.imgur.com/dg7EVSm.png)

If you have any further questions to solve this issue, let me know!

**Comment by JoshuaPelealu** [comment]
Are you saying that you have a gmail google accoutn, and you're trying to change it into a different email that is not gmail, or is it also a gmail email account?

**Comment by realAlpe** [comment]
I have a Gmail Google account and I cannot change it into a different email that is not Gmail. I don't think you can change from a Gmail Google account to another Gmail Google account, but I am not 100% sure about that statement.

**Comment by JoshuaPelealu** [comment]
Have you gone through the process of verifying your email and then refreshing the browser?

**Comment by realAlpe** [comment]
I have refreshed it multiples times. Just now I tried signing out and in again after verifying my Email. That seemed to verify my account. 
But the issue with not being able to change from a Gmail Google account to an Email account still remains. Perhaps this issue is too cumbersome to solve, or in other words, too much effort for something so irrelevant. If that is the case I might consider closing this issue. Let me hear your thoughts about that.

**Comment by JoshuaPelealu** [comment]
Why do you want to change it to a different email? Is there a specific reason?

**Comment by realAlpe** [comment]
I have multiple Emails and I have them sorted as well. That is, everything "productive" related goes into Email1 and everything else goes into Email2. In other words, Email2 is my junk Email. When I was creating a new account I was unsure whether I would stay on this platform for a longer, which is why I chose my Gmail Google account which is linked to the junk Email.

But as stated before, this is nothing more than a slight nuisance for me. It is not an obligatory feature request.

**Comment by realAlpe** [comment]
Look above.
