### ISSUE TITLE
Use prefers-color-scheme for dark mode to change automatically.

### ISSUE THREAD

**Issue by LazaroFilm** [freeCodeCamp/freeCodeCamp#39350]
**Is your feature request related to a problem? Please describe.**
The dark mode needs to be toggles manually from the settings menu.

**Describe the solution you'd like**
It would be great to use prefers-color-scheme to the color scheme changes automatically. 

**Describe alternatives you've considered**
-
**Additional context**
https://web.dev/prefers-color-scheme/

**Comment by ahmadabdolsaheb** [comment]
That is a feature we are working on in this pr.
https://github.com/freeCodeCamp/freeCodeCamp/pull/39292

Thanks for opening this issue. I will close it for now since the requested feature is under development.
