### ISSUE TITLE
Wrong number of padding-spaces in article about padding-function

### ISSUE THREAD

**Issue by mhombach** [freeCodeCamp/freeCodeCamp#39356]
**Describe your problem and how to reproduce it:**
On "3. String padding" there in the line of ".padStart(10)", there are 10 spaces but there should only be 9. In this scenario this was very misleading.

**Add a Link to the page with the problem:**
https://medium.freecodecamp.org/here-are-examples-of-everything-new-in-ecmascript-2016-2017-and-2018-d52fa3b5a70e

**Recommended fix, suggestions (how would you update it?):**
Correct the number of spaces.

**Comment by Ieahleen** [comment]
Other article on /news that needs attention @raisedadead @AbbeyRenn

**Comment by RandellDawson** [comment]
@Ieahleen @AbbeyRenn I edited the article to remove the extra space.  You may have to refresh the page to see the change.

I am closing this as resolved.
