### ISSUE TITLE
Repeat a string repeat a string

### ISSUE THREAD

**Issue by duggiemitchell** [FreeCodeCamp/FreeCodeCamp#3935]
Challenge [Bonfire: Repeat a string repeat a string](http://freecodecamp.com/challenges/bonfire-repeat-a-string-repeat-a-string has an issue.
User Agent is: <code>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

I used JSBin to debug my solution and it passes.  It even prints the correctly in the editor on freecodecamp.  Screen shot and code below:

function repeat(str, num) {
  if (num <1) {
    return " ";
  } else {
    return str.repeat(num);
  }
}
repeat("abc", 2);
repeat("abd", -3);

![screenshot from 2015-10-27 10 31 53]
(https://cloud.githubusercontent.com/assets/12376362/10761275/fcc249f2-7c96-11e5-85b7-2dfae9522bf3.png)

**Comment by Varedis** [comment]
@duggiemitchell you haven't returned an empty string, you have returned a string that contains a space.

**Comment by duggiemitchell** [comment]
Duh :( So (""); 
instead of (" ");

Thank you!
