### ISSUE TITLE
Tracking button not working as expected on freeCodeCamp forum

### ISSUE THREAD

**Issue by thevirtualbuddy** [freeCodeCamp/freeCodeCamp#39366]
**Description of the bug**
The tracking button doesn't change to other options available.

**To Reproduce**
1. Go to the community forum : [https://forum.freecodecamp.org/](url)
2. Click on any topic from the home page.
3. Select the tracking button which is available at the right bottom corner.
4. Try changing to other options.
5. See an error, the button still says "tracking".

**Expected behavior**
The button is expected to change to the option which is selected. Eg: if we select "Watching", the button should show watching as text on it.

**Screenshots**
![Tracking-button](https://user-images.githubusercontent.com/42694653/89257531-ff252a00-d643-11ea-9658-b4e16b479488.gif)

**Desktop (system details):**
 - OS: [Windows 10]
 - Browser: [Firefox]
 - Version: [79.0 (64-bit)]

**Comment by Sky020** [comment]
Thank you, for taking the time to report this.

I can confirm that this is also happening with me. I will also add that the button does change the value, but does not display this change. It appears to be an issue with the state change not being saved, when the component is reloaded.

However, (and someone else can confirm), I think this is a bug that needs to be reported to Discourse (the forum platform provider), not freeCodeCamp.

**Comment by RandellDawson** [comment]
> However, (and someone else can confirm), I think this is a bug that needs to be reported to Discourse (the forum platform provider), not freeCodeCamp.

@Sky020 FCC should report it or at least check on their GitHub issues to see if it is an outstanding issue already.  Would you be up for the task?

**Comment by thevirtualbuddy** [comment]
> 
> 
> 
> I can confirm that this is also happening with me. I will also add that the button does change the value, but does not display this change. It appears to be an issue with the state change not being saved, when the component is reloaded.
> 

Thank you @Sky020  for putting down it appropriately. 
I'm happy to be of some help to the FCC.

**Comment by Sky020** [comment]
> Would you be up for the task?
@RandellDawson , Sure, I will look into it.

**Comment by raisedadead** [comment]
I am almost certain this is the broken theme. You can confirm by switching to the default Discourse theme available for debuging.

/cc @ahmadabdolsaheb

**Comment by raisedadead** [comment]
Yep, confirmed myself.

**Comment by Sky020** [comment]
@RandellDawson , A Discourse member says that this is a modification, and not part of the default Discourse: https://meta.discourse.org/t/freecodecamp-topic-timeline-tracker-button-bug/159804/2

What do we do in this case?

**Comment by RandellDawson** [comment]
@Sky020 I did not think about the theme being the issue.  @raisedadead How were you able to guess this was the problem all along?

**Comment by raisedadead** [comment]
I tested it with the default Discourse theme.

![image](https://user-images.githubusercontent.com/1884376/89389661-4fbf8480-d723-11ea-8b54-0072fadda86c.png)

I use this for my needs because the freeCodeCamp themes are broken for most admin areas, etc.

**Comment by ahmadabdolsaheb** [comment]
a lot of the icons were replaced with words one of which was the bell icon.
The word "tracking" should be replaced with "notification" so it would not be confused with "tracking" which is also a notification option.  let me if this would resolve this issue so I move forward with a pr.

**Comment by raisedadead** [comment]
Reopening.

----

Issue 1: It's not mapped correctly at all places.

Custom theme:

![image](https://user-images.githubusercontent.com/1884376/100386834-86136d80-304c-11eb-879c-1dcfb4bf885a.png)

Default:

![image](https://user-images.githubusercontent.com/1884376/100386902-ad6a3a80-304c-11eb-844f-c4d2c4dbf005.png)

----

Issue 2: Its lowercased, which is not consistent with other Labels.

----

Issue 3: It does not solve the OP's issue, that is the button's label does not change to the selected option of the user and they have to open the drop down to see their choice.

**Comment by ahmadabdolsaheb** [comment]
Thanks for noticing that. The above-mentioned pr that completely removes the words in favor of icons should do the trick.
