### ISSUE TITLE
Bug: Avoid Mutations and Side Effects Using Functional Programming needs to validate the global variable is used in the incrementer function

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#39364]
While reviewing a PR (#39363) that fixes a separate issue on the [Avoid Mutations and Side Effects Using Functional Programming](Avoid Mutations and Side Effects Using Functional Programming) challenge, I noticed the following test does not validate that the value returned from the `incrementer` function returns a value that is one larger than the `fixedValue` global variable's value.

```yml
  - text: Your <code>incrementer</code> function should return a value that is one larger than the <code>fixedValue</code> value.
    testString: const newValue = incrementer(); assert(newValue === 5);
```
A user can simply write the following and pass the challenge without even using the `fixedValue` variable in the code.

```js
var fixedValue = 4;

function incrementer () {
  // Only change code below this line
   return 5;
  // Only change code above this line
}
```
I suggest adding a third test, so that we set the value of `fixedValue` to a different value before calling the function.  However, since the user could technically write `const fixedValue = 4;` instead of `var fixedValue = 4;`, one way of approaching this would be to use an IIFE: like the following:

```yml
  - text: Your <code>incrementer</code> function return a value based on the global `fixedValue` variable value.
    testString: |
      (function() {
       const fixedValue = 10;
       const newValue = incrementer();
       assert(fixedValue === 10 && newValue === 11);
      })()
```

Before adding a `help wanted` label, I am looking for feedback from others about this approach to fixing the challenge.

**Comment by nhcarrigan** [comment]
I think this is a good fix. The only other alternative I could think of would be a regex to test that the incrementer function references the `fixedValue` variable, but this method would catch more edge cases.

**Comment by RandellDawson** [comment]
>  The only other alternative I could think of would be a regex to test that the incrementer function references the fixedValue variable,

When we can avoid using regex, we avoid regex.

**Comment by nhcarrigan** [comment]
I am 100% on board with avoiding regex. 🙂

I can go ahead and prepare a fix for this if you'd like, after the other PR gets merged or closed.

**Comment by RandellDawson** [comment]
I would like to open this one up for first timers, since we already have a "fix".  Let's see if anyone else comments about the suggestion before adding the label though.

**Comment by Sky020** [comment]
This looks like a decent approach. However, would it not suffice to edit the first test to this, instead of creating a new test?

**Comment by RandellDawson** [comment]
> This looks like a decent approach. However, would it not suffice to edit the first test to this, instead of creating a new test?

@Sky020 They are testing similar but different things.  The first one is testing if they changed the global variable and the third test is indirectly checking that but also validating they did not just use `return 5` in the `incrementer` function.

**Comment by Sky020** [comment]
@RandellDawson , true, but do we care if they alter the variable (manually)? As in, can we make do with two tests total, because your suggestion already checks to see if the variable has been manipulated by the function?

**Comment by RandellDawson** [comment]
I just want it to be clear to the user why the test is not passing.  Is it because they changed the global variable or that they did not use the global variable in the value returned?  I could be wrong, but I think adding the 3rd test makes it clearer what has happened to the user.

**Comment by RandellDawson** [comment]
So we are in agreement about adding the 3rd test?  If so, I will add the `first timer` label to it.

**Comment by Sky020** [comment]
> So we are in agreement about adding the 3rd test?

Yes, I agree that the clarity will be beneficial.

**Comment by Mayank1795** [comment]
@RandellDawson The call to incrementor function inside the IIFE does not refer to the fixedValue variable created inside. That's why the assertion will give an error. 
![te](https://user-images.githubusercontent.com/5724551/89719742-2d5e8d00-d9e9-11ea-8bde-f76c8ebaba08.png)

**Comment by RandellDawson** [comment]
@Mayank1795 I should have tested the code before suggesting it.  The problem is closure.  The original `fixedValue` variable is declared in the same scope that the `incrementer` function is.  This means when `fixedValue` is referenced inside it, the function will always use the globally declared `fixedValue`.  We will have to come up with another way to do this.

**Comment by weeisunthi-gmail** [comment]
weeisunthi-gmail

**Comment by Mayank1795** [comment]
@RandellDawson We can do something like this. Change the global variable to some other value for testing and later assign the original value. I will update the PR.

```var fixedValue = 4;

function incrementer (){
  return fixedValue+1;
}

(function() {
       fixedValue = 10;
       const newValue = incrementer();
       console.log(fixedValue, newValue);  // prints 10, 11
       fixedValue = 4;
      })();

console.log(fixedValue); // prints 4
```

**Comment by Rohit-Arora-0508** [comment]
Is this issue still open? I will like to work on it.

**Comment by nhcarrigan** [comment]
Heya @Rohit-Arora-0508 

Thank you for your interest in contributing! There is currently an active PR that will close this issue, and it looks like that PR is on track for approval. We typically accept the first comprehensive PR that fixes an issue - as such, I would recommend looking for other issues labelled `help wanted` (or `first timers only`, if this is your first contribution) and check for ones that do not yet have a linked PR. 🙂

**Comment by Rohit-Arora-0508** [comment]
Ok Thanks 🙂🙂

**Comment by weeisunthi-gmail** [comment]
X11@gibhub/weeisunthi-.com
