### ISSUE TITLE
Avoid Mutations and Side Effects incomplete error testing

### ISSUE THREAD

**Issue by multiwebinc** [freeCodeCamp/freeCodeCamp#39362]
**Describe your problem and how to reproduce it:**

Part of the problem description states:

> Let's try to master this discipline and not alter any variable or object in our code

Therefore the following should not pass, however it does:

```
var fixedValue = 4;

function incrementer () {
  return ++fixedValue;
}
```

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/avoid-mutations-and-side-effects-using-functional-programming.english.md

**Comment by nhcarrigan** [comment]
![image](https://user-images.githubusercontent.com/63889819/89228641-dbef7180-d594-11ea-99d6-358d94d09889.png)

I can confirm that the code snippet you provided modifies the value of the global variable. 

This could be corrected by adding a test to confirm that the value of `fixedValue` does not change after the function call.
