### ISSUE TITLE
Confusing Placeholder at Backend Challenges

### ISSUE THREAD

**Issue by variousnabil** [freeCodeCamp/freeCodeCamp#39375]
i found a problem that cause confusion when first trying backend challenges because at the first introduction of the challenges we were instructed to use `glitch` to solve the problem, then at the challenges, the solution placeholder shown the `codepen` link. it's kinda confusing at first! i think it will be better that the placeholder shown the glitch link for better clarity. 

https://www.freecodecamp.org/learn/apis-and-microservices/basic-node-and-express/get-route-parameter-input-from-the-client

Browser Name: Firefox 
Browser Version: 79
Operating System: Windows 10

![issue1](https://user-images.githubusercontent.com/25002923/89435265-d9e10a80-d76e-11ea-821d-50824927abb2.PNG)

Regards.

**Comment by nhcarrigan** [comment]
Heya~! I agree this can be potentially confusing. 

At a quick glance, this appears to be the case for all of the `API And Microservices` and `Quality Assurance` challenges, as well as the `helmetJS` challenges in `Information Security` - the projects, however, use the correct placeholder.

**Comment by Sky020** [comment]
This should have been fixed by #38411 , but might have been undone with a more recent PR.
