### ISSUE TITLE
Accepted answer error

### ISSUE THREAD

**Issue by MedRatid** [freeCodeCamp/freeCodeCamp#39372]
[This](https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/numpy-operations) accepts [0, 1, 2, 3, 4] as a correct answer, when it should be [20, 21, 22, 24, 24]
![Capture](https://user-images.githubusercontent.com/16351312/89319960-c81d3b80-d678-11ea-8256-1858af19fd4d.PNG)
![Capture](https://user-images.githubusercontent.com/16351312/89320081-ec791800-d678-11ea-9ce5-76207a63d547.PNG)

**Comment by RandellDawson** [comment]
Why do you think the answer is `[20, 21, 22, 24, 24]`?

**Comment by MedRatid** [comment]
> Why do you think the answer is `[20, 21, 22, 24, 24]`?

@RandellDawson The result in the second capture

**Comment by MedRatid** [comment]
> Why do you think the answer is `[20, 21, 22, 24, 24]`?

@RandellDawson Ok my bad It asked for the value of "a"

**Comment by RandellDawson** [comment]
Glad you figured it out.

In the future, please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can feel free to create an issue.  In general, GitHub issues are meant for reporting bugs and not necessarily for troubleshooting the code in your projects.

Thank you for understanding.

**Comment by MedRatid** [comment]
> Glad you figured it out.
> 
> In the future, please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects. If the forum members determine there is nothing wrong with your code, you can feel free to create an issue. In general, GitHub issues are meant for reporting bugs and not necessarily for troubleshooting the code in your projects.
> 
> Thank you for understanding.

Fair enough Thank you
