### ISSUE TITLE
Same result but different outcome based on the 'code style'

### ISSUE THREAD

**Issue by SeasonLeee** [freeCodeCamp/freeCodeCamp#39370]
**Describe your problem and how to reproduce it:**
In this challenge(screenshot below):
![image](https://user-images.githubusercontent.com/13610283/89290229-23582980-d68b-11ea-8dda-d251339f5955.png)

If I answer the question as I typed in the code editor, it won't pass... and get error like this:
![image](https://user-images.githubusercontent.com/13610283/89290450-7500b400-d68b-11ea-90ad-158794ea0616.png)

But if I change the answered code into a different code style, it will pass....
![image](https://user-images.githubusercontent.com/13610283/89290598-b1341480-d68b-11ea-85cd-b33febaf05d3.png)

![image](https://user-images.githubusercontent.com/13610283/89290669-c610a800-d68b-11ea-85d7-3c43106f9491.png)

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/front-end-libraries/react/render-state-in-the-user-interface

**Tell us about your browser and operating system:**
* Browser Name: Chrome 
* Browser Version: Version 84.0.4147.105 (Official Build) (64-bit)
* Operating System: macOS 10.15.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
Check above~

**Comment by SeasonLeee** [comment]
Actually I would love to check the 'freecodecamp' project code to give this issue a shot, but my schedule is quite full currently... but if this can wait to the weekend and no one check on it, I will be the first one to check on it~

**Comment by Sky020** [comment]
Hello there,

The reason the code above does not pass:
```
<h1> {this.state.name} </h1>
```
is because of the spaces on either side of the `name`.

[Here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/03-front-end-libraries/react/render-state-in-the-user-interface.english.md) is the file containing the tests, and here is the failed assertion:
```
assert(firstValue === ''<div><h1>TestName</h1></div>'');
```
As you can see, your code would evaluate to:
```
<div><h1> TestName </h1></div>
```

Unless someone else disagrees, I suggest this be closed.

**Comment by moT01** [comment]
There seems to be an inconsistency between how the test mocks the component and how a browser renders it. I see the spaces get removed on rendering in firefox...

<img width="644" alt="Screen Shot 2020-08-04 at 8 12 17 AM" src="https://user-images.githubusercontent.com/20648924/89298158-88c7fe00-d62a-11ea-874e-2ee2f5edcc73.png">

but the test is failing. Seems like we could probably fix this if someone wants. Same result in Chrome.

**Comment by moT01** [comment]
I may have prematurely went for the help wanted label - maybe we should discuss it a little more first.

**Comment by Sky020** [comment]
@moT01 , thank you, for pointing that out. In Chrome, the browser also trims the whitespace (for `h` elements), but the devTools do show the whitespace in the doc tree.

Seeing as the browser trims it, should we alter the tests to also `removeWhiteSpace`?

**Comment by moT01** [comment]
That would probably be fine enough I think @Sky020.

**Comment by SeasonLeee** [comment]
> Hello there,
> 
> The reason the code above does not pass:
> 
> ```
> <h1> {this.state.name} </h1>
> ```
> 
> is because of the spaces on either side of the `name`.
> 
> [Here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/03-front-end-libraries/react/render-state-in-the-user-interface.english.md) is the file containing the tests, and here is the failed assertion:
> 
> ```
> assert(firstValue === ''<div><h1>TestName</h1></div>'');
> ```
> 
> As you can see, your code would evaluate to:
> 
> ```
> <div><h1> TestName </h1></div>
> ```
> 
> Unless someone else disagrees, I suggest this be closed.

Hi, thanks for the reply and the linking to file containing the test, it help me understand a lot of what's going on behind the error given on my problem submission, thank you!

However, I disagree at there that you initially thinking 'if no one disagree then just close this issue'

But to my relief, with more informations from @moT01   you decide to "alter the tests to also `removeWhiteSpace`", which should be the right thing to do, I believe.

Because, the lesson there is merely telling the user how the UI in React getting their data from, which from state per the lesson, so the main focus of the lesson should avoid those irrelevant problems as much as possible, just for the sake of confuse less those who are learning the course not some else, the test rule as you point out for instance.

And as I am stating here, I also need to point out the fact that there are tons of lessons that fail to pass due to the difference of code style. 

I am not trying to blame anyone or making a big fuss over something 'seems' trivial, but I am saying make those error as concise as possible, and I am willing to help, by the way! 😆 

Freecodecamp pave my way to become a front-end developer at the very first place, by contributing back to the code base or anything is the least I can do!😆

**Comment by Sky020** [comment]
I am opening this up to be fixed. Problem statement:

- Tests need to be altered to first remove (trim) whitespace from the code, before being compared to the expected value.

Tests for this lesson are found here: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/03-front-end-libraries/react/render-state-in-the-user-interface.english.md

**Comment by SeasonLeee** [comment]
Could this assign to me??? Oh my god... I would love to try this... please? thank you😆

**Comment by Sky020** [comment]
@SeasonLeee , we do not typically assign issues to people, but you are welcome to work on anything with a _help wanted_ label. The first decent PR is QAed and merged.

Be sure to read the [contributing docs](https://contribute.freecodecamp.org/#/index)

**Comment by SeasonLeee** [comment]
@Sky020 hey, sorry for the late reply, I was sick during the weekend but I still managed to read through the contribution guideline and understand the situation you have talked about. 

So, if I can't search #39370 in the PR list, does that mean that I can still work on it?

Besides, there's a holiday coming in our country so our company plans to take the heat of holiday and make some promotion of the project I am in charge of, meaning I might not be so quick to work on this issue, but I do my best for it.

And I believe if there's any questions about the contribution I should head to gitter for it, right? Well...

**Comment by SeasonLeee** [comment]
@Sky020 Hey, I posted something on the gitter but it seems no one online...

So, when I set up docker for the project, there one red error in the log:
![image](https://user-images.githubusercontent.com/13610283/89763546-55530b00-db25-11ea-949c-c4b4a3bb4afb.png)

Is that a big deal? Should I be concerned?

**Comment by SeasonLeee** [comment]
@Sky020 Hey, man, I just got some reply from gitter and it's said that's nothing to worry about regarding working with the project, but there's still problem that after I run `npm run docker:develop`

And after a while... I tried to access the project from browser by enter 'localhost:8000', but nothing happen!

The browser just shows this...
![image](https://user-images.githubusercontent.com/13610283/89769936-9a306f00-db30-11ea-9cac-ab9b4665ffba.png)

Seems like the project can't be access from outside of docker... but my docker is.... why?

**Comment by Sky020** [comment]
Hello @SeasonLeee ,

Regarding working on this issue: There is no problem with you submitting  a PR for it. All I wanted to clarify is, we do not typically assign issues, and if someone else submitted a working PR before you, we would merge the first submitted PR.

Regarding issues when setting up locally: Unfortunately, I have hardly any experience with the Docker setup. So, your best bet for help is either the Gitter chatroom, or the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3?order=default). Remember to provide as much detail as necessary.

Regarding the Husky warning: Do not worry much about that warning, as it should not affect the development process. However, it could be indicative of something else being buggy. We will need to see more logs to help.

**Comment by SeasonLeee** [comment]
Hey, @Sky020  Thanks for the detail response

And, 

1. I understand the issue won't hold for me if there's a PR for it, and I'm totally ok with it, because we are all want to contribute here, I don't mean to compete or something

2. Well, yeah, there are lots of kind people around the gitter, I hope I can solve the issue quicker with their help

3. By saying more logs, did you mean the entire install log or?

Again, really thanks for your response!

**Comment by Sky020** [comment]
> By saying more logs, did you mean the entire install log or?

I cannot say...just more logs because the above you have posted do not appear to be related. Generally, we are only interested in the anomalous data which is logged, but, unless you know what that is, then providing all of the logs would be best. Let us continue this chat on Gitter, if you have more.
