### ISSUE TITLE
Site not loading

### ISSUE THREAD

**Issue by aditya197322** [freeCodeCamp/freeCodeCamp#39376]
**Describe the bug**
I was going great with this sites for a couple of days but today suddenly in the middle of my coding lesson it started showing me loading symbol and it just continues to show it. And now it has been atleast 3 hours since it is showing me loading

Desktop 
 - OS: Windows 10
-Browser: Chrome

**Comment by RandellDawson** [comment]
Can you provide more information such as a screenshot of what you are seeing.  What challenge (include url) were you working on when this happened?  Does it happen on the main page or other lessons?

**Comment by willmeck** [comment]
@RandellDawson I am also seeing this. It happens with the learn section of the website. Here is my console log `GET https://www.freecodecamp.org/webpack-runtime-4cda38d3762cd23fb48d.js net::ERR_ABORTED 404`

**Comment by RandellDawson** [comment]
> It happens with the learn section of the website.

@willmeck Can you answer the same questions I asked the OP?

**Comment by willmeck** [comment]
![image](https://user-images.githubusercontent.com/2678328/89571626-fb390980-d7f5-11ea-976d-4e4193e812b1.png)

**Comment by willmeck** [comment]
Tried Edge which works fine, so far just experienced the problem on chrome

**Comment by raisedadead** [comment]
Thanks for reporting, chances are its a stale cache. While I am unable to reproduce this myseld, I just purged the file from our CDN.

Can you check again? If the same persists can you toggle the disable cache on Chrome and reload the page again? Like so:

![image](https://user-images.githubusercontent.com/1884376/89575251-239f2300-d84b-11ea-99df-592775d4b7cc.png)

**Comment by willmeck** [comment]
Worked for me on Chrome now

**Comment by raisedadead** [comment]
Thanks, it should be a stale cache. Closing.
