### ISSUE TITLE
Misleading description of CSS flex-wrap

### ISSUE THREAD

**Issue by cklutzke** [freeCodeCamp/freeCodeCamp#39371]
**Describe your problem and how to reproduce it:**
The descriptions of the wrap and wrap-reverse options for "CSS Flexbox: Use the flex-wrap Property to Wrap a Row or Column" are misleading. wrap-reverse doesn’t wrap items from right-to-left (that would be the row-reverse value for the flex-direction property). I propose the following:

- wrap: In a row, wraps overflowing items below the previous row. In a column, wraps overflowing items to the right of the previous column.
- wrap-reverse: In a row, wraps overflowing items above the previous row. In a column, wraps overflowing items to the left of the previous column.

**Add a Link to the page with the problem:**
 https://www.freecodecamp.org/learn/responsive-web-design/css-flexbox/use-the-flex-wrap-property-to-wrap-a-row-or-column

**Tell us about your browser and operating system:**
* Browser Name: Chrome
* Browser Version: Version 84.0.4147.105 (Official Build) (64-bit)
* Operating System: Windows 10 Pro version 1903

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![Untitled](https://user-images.githubusercontent.com/32312459/89303183-d861f600-d639-11ea-8793-b11204b69c8d.png)

**Comment by cklutzke** [comment]
It looks like someone started to address this in a previous issue (#17736), but it wasn't deployed?
https://github.com/freeCodeCamp/freeCodeCamp/issues/17736

**Comment by RandellDawson** [comment]
[This PR](https://github.com/freeCodeCamp/curriculum/pull/70) was merged to address the issue reported in #17736.   So, it was deployed, but made the wrong changes?

**Comment by cklutzke** [comment]
If it was deployed, the change that was made did not correct the issue. The erroneous text reported in #17736 is the same as when the issue was reported.

**Comment by ChoukseyKhushbu** [comment]
Hi @RandellDawson, 
I would like to fix this issue if it's open for first-time contributors.
Can I?

**Comment by RandellDawson** [comment]
@ChoukseyKhushbu We are still discussing here.  Once we put a help wanted label on it, some one is free to take up the task.

**Comment by moT01** [comment]
I dunno - I feel like I like what we currently have better because it says `bottom-to-top`, `right-to-left`, etc. 

The suggestion `wrap-reverse: In a row, wraps overflowing items above the previous row.` is true, but it makes it sound like it pushed the row down and adds another one on top. When actually, it starts at the bottom, and adds a row above when needed - this is why I like `bottom-to-top` better.

I feel like this could be left as-is, but if someone wants to try and come up with a better suggestion or make their case for why it should be changed, feel free.

**Comment by raisedadead** [comment]
Hi, 

We are closing old issues/pull-requests that we think are stale. If you need still need help with this or are fixing this, please open a fresh issue/pull-request.

Thanks for your understanding. 

Happy contributing.
