### ISSUE TITLE
Basic CSS: Improve Compatibility with Browser Fallbacks tests fail on Firefox latest version

### ISSUE THREAD

**Issue by Pablo-No** [freeCodeCamp/freeCodeCamp#39389]
**Describe your problem and how to reproduce it:**
My problem is that when doing "Basic CSS: Improve Compatibility with Browser Fallbacks" challenge the test fails despite I'm doing things well.
I've verified that in Chrome it works properly

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/responsive-web-design/basic-css/improve-compatibility-with-browser-fallbacks

**Tell us about your browser and operating system:**
* Browser Name: Firefox Quantum
* Browser Version: 68.11.0esr (64-bit)
* Operating System: Windows 10 Home, version 1903, operative system version 18362.959.

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![](https://i.imgur.com/eWE1op7.png)
You can see that test fails but the code is correct

**Comment by RandellDawson** [comment]
Please use [our forum](https://www.freecodecamp.org/forum) for debugging the code of your projects.  If the forum members determine there is nothing wrong with your code, you can request this issue to be reopened.  GitHub issues are meant for reporting bugs and not troubleshooting the code in your projects.

Thank you for understanding.

**Comment by Pablo-No** [comment]
Created a [forum post](https://forum.freecodecamp.org/t/basic-css-improve-compatibility-with-browser-fallbacks-tests-fail-on-firefox-latest-version/414573).
I'll make a new comment when forum members determine whether my code is wrong or not.

Thank for your reply.

**Comment by Pablo-No** [comment]
Oops, it was a typo in background.
