### ISSUE TITLE
Undefined?

### ISSUE THREAD

**Issue by leonardolatorre** [FreeCodeCamp/FreeCodeCamp#3938]
Challenge [Waypoint: Declare String Variables](http://freecodecamp.com/challenges/waypoint-declare-string-variables#?
<img width="1272" alt="screen shot 2015-10-27 at 21 12 10" src="https://cloud.githubusercontent.com/assets/12745976/10772738/6055e4ee-7cef-11e5-90c6-ae46add6b8e8.png">
solution=%2F%2F%20var%20name%20%3D%20%22Alan%20Turing%22%3B%0A%2F%2F%20var%20firstName%20%3D%20%22Alan%22%3B%0A%2F%2F%20var%20lastName%20%3D%20%22Turing%22%3B%0A%0Avar%20myfirstName%20%3D%20%22Leonardo%22%3B%0Avar%20mylastName%20%3D%20%22Latorre%22%3B%0A%0A%2F%2F%20Only%20change%20code%20above%20this%20line.%0A%2F%2F%20We%20use%20this%20function%20to%20show%20you%20the%20value%20of%20your%20variable%20in%20your%20output%20box.%0A%2F%2F%20You'll%20learn%20about%20functions%20soon.%0Aif(typeof(myFirstName)%20!%3D%3D%20%22undefined%22%20%26%26%20typeof(myLastName)%20!%3D%3D%20%22undefined%22)%7B(function()%7Breturn%20myFirstName%20%2B%20'%2C%20'%20%2B%20myLastName%3B%7D)()%3B%7D%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// var name = "Alan Turing";
// var firstName = "Alan";
// var lastName = "Turing";

var myfirstName = "Leonardo";
var mylastName = "Latorre";

// Only change code above this line.
// We use this function to show you the value of your variable in your output box.
// You'll learn about functions soon.
if(typeof(myFirstName) !== "undefined" && typeof(myLastName) !== "undefined"){(function(){return myFirstName + ', ' + myLastName;})();}

```

**Comment by iTypeSlow** [comment]
Hey your variables are named improperly, variables in this challenge are case sensitive :) 

var myfirstName = "Leonardo";
var mylastName = "Latorre";

should be

var myFirstName = "Leonardo";
var myLastName = "Latorre";

**Comment by ltegman** [comment]
@iTypeSlow is correct that the variable names are case sensitive.

Closing as not an issue with the tests, but please feel free to reply if you have further concerns.

Thanks and happy coding!
