### ISSUE TITLE
Some Coding Challenges on ES6 are showing ReferenceError: despite submitting correct answer

### ISSUE THREAD

**Issue by itshally** [freeCodeCamp/freeCodeCamp#39382]
I have been doing the **ES6** challenges on **JavaScript Algorithms and Data Structures** just fine until I reached these parts: 

- [Use export to Share a Code Block](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/use-export-to-share-a-code-block)
- [Reuse JavaScript Code Using import](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/reuse-javascript-code-using-import)
- [Use * to Import Everything from a File](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/use--to-import-everything-from-a-file)
- [Create an Export Fallback with export default](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/create-an-export-fallback-with-export-default)
- [Import a Default Export](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/es6/import-a-default-export)

which are showing me a `ReferenceError:` on the console like on the images below..

![screenshot-www freecodecamp org-2020 08 07-20_26_42](https://user-images.githubusercontent.com/39101336/89699635-3f133800-d8f6-11ea-9a13-82a97f3dfcb4.png)

![screenshot-www freecodecamp org-2020 08 07-20_35_38](https://user-images.githubusercontent.com/39101336/89699637-3fabce80-d8f6-11ea-9b7a-dd75e5f856b6.png)

At first, I thought there was something wrong with my code but surely there was none. 
Then after submitting my code, it still accepted even though there was a `ReferenceError:` displaying before going to the next challenge.

* Browser Name:  Chrome
* Browser Version: 84.0
* Operating System: Windows 10

**Comment by RandellDawson** [comment]
@ojeytonwilliams Is this related to Babel (see [this issue on Babel's repo](https://github.com/babel/babel/issues/9187))?

**Comment by moT01** [comment]
Are you still having this problem @itshally? I gave it a quick test and did not see it on the first two links you gave in firefox or chrome. 

Were you able to reproduce this @RandellDawson?

**Comment by itshally** [comment]
@moT01 I just tested it and it's fixed now. Thanks!
