### ISSUE TITLE
nonMutatingSort(globalArray) should not be hard coded.

### ISSUE THREAD

**Issue by j836** [freeCodeCamp/freeCodeCamp#39396]
I am facing this issue even though I have used the local variable arr.And I had also tried copying the local variable into another varialbe if in case the passed argument somehow may be mutating the array.
I had googled it several times and also posted the same on free code camp forum.But I didnt get any proper Solution for it.
Also , I am a newbie to javascript and if this is not a potential issue ,please ignore!
Thank you!

 #39396 [@freecodecamp
`var globalArray = [5, 6, 3, 2, 9];
function nonMutatingSort(arr) {
  // Only change code below this line
   //var arr2 =arr.concat([]);
   //console.log(arr2);
  // return [...globalArray].sort(function(a,b) { return a-b;});
  //var globalArray = [5, 6, 3, 2, 9];
  return [].concat(arr).sort(function(a, b) {
    return a - b;
  });
   //console.log(arr2)
   //console.log(arr)
   //return arr2;
  // Only change code above this line
}
nonMutatingSort(globalArray);
`

**Comment by nhcarrigan** [comment]
Hello~!

Thank you for your interest in contributing to freeCodeCamp! Do you have a link to the challenge you believe has the bug?

**Comment by j836** [comment]
> Hello~!
> 
> Thank you for your interest in contributing to freeCodeCamp! Do you have a link to the challenge you believe has the bug?

I have just updated my comment.Thank you for quick reply1

**Comment by j836** [comment]
> Hello~!
> 
> Thank you for your interest in contributing to freeCodeCamp! Do you have a link to the challenge you believe has the bug?

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/return-a-sorted-array-without-changing-the-original-array

The above mentioned link shall redirect to the required page.
Thank you for your quick reply!

**Comment by nhcarrigan** [comment]
It appears this bug is related to the regex used for the test. 
```js
  - text: <code>nonMutatingSort(globalArray)</code> should not be hard coded.
    testString: assert(!nonMutatingSort.toString().match(/[23569]/g));
```

Your `arr2` variable is erroneously causing this test to fail, as the regex is matching the `2`. This test may need to be adjusted to account for these cases.

**Comment by j836** [comment]
Thank You Sir @nhcarrigan !But I got the desired result..Thank You!
