### ISSUE TITLE
Rosetta Code: Knapsack problem/Unbounded - one incorrect test

### ISSUE THREAD

**Issue by gikf** [freeCodeCamp/freeCodeCamp#39398]
**Describe your problem and how to reproduce it:**
One of the tests in this challenge has wrong result, both in test code and description. It says:
```
knapsackUnbounded([
  { name:"panacea", value:3000, weight:0.3, volume:0.025 },
  { name:"ichor", value:1800, weight:0.2, volume:0.015 },
  { name:"gold", value:2500, weight:2, volume:0.002 }
  ], 35, 0.35)
should return 75300.
```
This isn't correct. For example: knapsack having 11 panacea, 3 ichor and 15 gold has value 75900, while being within the weight and value constrains:
```
11 * 3000 + 3 * 1800 + 15 * 2500 = 75900  // value
11 * 0.3 + 3 * 0.2 + 15 * 2 = 33.9  // weight
11 * 0.025 + 3 * 0.015 + 15 * 0.002 = 0.35  // volume
```
This seems to be case of precision issue. Multiplication input item weights, volumes and max values for those parameters, to start operations without decimals, makes result as it should be, also for the problematic test.

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/rosetta-code/knapsack-problemunbounded

**Comment by Ieahleen** [comment]
Yes, it seems you are right - do you want to propose a solution?

**Comment by gikf** [comment]
Yes, sorry. The least invasive way to correct the [solution](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/10-coding-interview-prep/rosetta-code/knapsack-problem-unbounded.md#--solutions--) seems to be to multiply in function, by the same factor, initial items weights, volumes, and in the first recursive call multiply `maxweight` and `maxvolume`.
```
  for (let i = 0; i < items.length; i++) {
      items[i].weight *= 1000;
      items[i].volume *= 1000;
  }
```

```
recurseKnapsack(0, 0, maxweight * 1000, maxvolume * 1000);
```
This is enough to make calculations on integers and get correct answers. I don't know if just such change would be okay or if more desirable would be more elaborate rewrite of solution. Or at least changing `var` to `let` / `const` and renaming some variables to better names.

**Comment by ieahleen** [comment]
would you be willing to open a PR for it?

**Comment by gikf** [comment]
Definitely yes, although I need advice which approach here would be preferred. Considering that the sample solution in code is just used for internal testing and just small change to it can fix the issue.
