### ISSUE TITLE
The demo link of Timestamp Microservice is not working in api-microservice Projects

### ISSUE THREAD

**Issue by Easyvipin** [freeCodeCamp/freeCodeCamp#39394]
AFTER Clicking the link ..
![a](https://user-images.githubusercontent.com/55550953/89877910-6ca1ff00-dbde-11ea-888e-b445e8f50a6d.png)
The projects seems to be broken.
![sd](https://user-images.githubusercontent.com/55550953/89877931-762b6700-dbde-11ea-8f1b-11a240961b66.png)

**Comment by Sky020** [comment]
I believe this is related to: #39392

**Comment by AlanJereb** [comment]
Hello,

The same problem goes for https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/exercise-tracker. Glitch demo won't load

**Comment by fuzzyray** [comment]
It's not clear from this issue title, but none of the API and Microservices Project examples are working. I've been using the github repository links on the project page to get the user stories and description of what I am supposed to be doing.

Maybe we could consolidate it with #39392 and change the title to reflect that it is all of the example projects on Glitch?

**Comment by Sky020** [comment]
Thank you, for this report. We have consolidated all of the projects into one issue. As such, I am closing this.
