### ISSUE TITLE
Change the account creation flow

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [freeCodeCamp/freeCodeCamp#39401]
On the weekly email blast confirmation page, replace the content with the followings

[/learn intro text]

- Quincy Larson, the teacher who founded freeCodeCamp.org

By the way, each Friday I send an email with 5 links about programming and computer science. I send these to about 4 million people. Would you like me to send this to you, too?

[ Yes ] [ No thanks ]

**Comment by Mvrs** [comment]
Was this just edited? I was looking at this one and it had four steps. But what do expect the flow to be?

**Comment by ahmadabdolsaheb** [comment]
yes, we had a meeting :)

**Comment by Mvrs** [comment]
Oh~~~😅
