### ISSUE TITLE
Metric-Imperial Converter sample project link not working

### ISSUE THREAD

**Issue by xAdvitya** [freeCodeCamp/freeCodeCamp#39412]
got to 
 - https://www.freecodecamp.org/learn/quality-assurance/quality-assurance-projects/metric-imperial-converter
 - then go to sample project link
or 
- go to https://incongruous-beard.glitch.me/

I tried in private tab but the problem presists 

* Browser Name:  firefox 
* Browser Version: latest
* Operating System: windows 10

**Comment by nhcarrigan** [comment]
Hello~!

I believe this is related to #39392 and is due to an issue with the glitch projects running out of CPU time.

**Comment by Sky020** [comment]
Thank you, for this report. We have consolidated all of the projects into one issue. As such, I am closing this.
