### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ApplePieAndCrime** [freeCodeCamp/freeCodeCamp#39415]
**Describe your problem and how to reproduce it:**
Broken example link: https://curse-arrow.glitch.me/
Output (glitch): "Oops! This project isn't running."

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/apis-and-microservices/apis-and-microservices-projects/timestamp-microservice

**Recommended fix, suggestions (how would you update it?):**

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by Sky020** [comment]
Hello there,

I am closing this as a duplicate of #39394
