### ISSUE TITLE
Change solution placeholder to user repl.it url

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/freeCodeCamp#39425]
Replace codepen placeholder URL's with Repl.it URL's. I believe the only place they need to be replaced is the backend lessons. I haven't audited, but the backend projects all use the repl.it placeholders already, I believe. The backend lessons are using codepen still - they should be changed.

![Screen Shot 2020-08-17 at 5 49 45 PM](https://user-images.githubusercontent.com/20648924/90455675-4982be00-e0bc-11ea-8613-3ba40742ff0b.png)

**Comment by RandellDawson** [comment]
@moT01 This is similar to an existing issue (#39321).  Do you want to close this one and add your suggestion there?

**Comment by ojeytonwilliams** [comment]
Might as well track this separately since the placeholder should still appear whenever the form is empty.

**Comment by Sky020** [comment]
I assumed I fixed this with #38411 . So, I must have done this with only the projects. Except, it should have pointed to Glitch.

**Comment by ojeytonwilliams** [comment]
@Sky020 your PR did the job, I've doubled-checked it locally.  Something must have changed since then.
